### ISSUE TITLE
Assertion error on trivial query

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#10016]
### What happens?

Hello, this morning I was trying a trivial query on DuckDB, and an assertion error was triggered.

### To Reproduce

Run these queries:
```
CREATE TABLE t0 (c0 INT);
INSERT INTO t0 VALUES (1);
SELECT 1 FROM t0; --src/parallel/executor.cpp:603: bool duckdb::Executor::GetPipelinesProgress(double&, uint64_t&, uint64_t&): Assertion `current_cardinality < total_cardinality' failed
```

### OS:

Linux x86_64

### DuckDB Version:

Latest from master branch

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
What was the git hash of the version you tried?

**Comment by PedroTadim** [comment]
> What was the git hash of the version you tried?

24148408432d05bda7cf86f2736d24920c51577c

The latest one.

**Comment by Mause** [comment]
> > What was the git hash of the version you tried?
> 
> 24148408432d05bda7cf86f2736d24920c51577c
> 
> The latest one.

I'm not able to reproduce with that hash, can you double check?

**Comment by PedroTadim** [comment]
I just reproduced it. This is my cmake setup compiling with GCC 11:

cmake -DCMAKE_GENERATOR=Ninja -DCMAKE_INSTALL_PREFIX=... -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_C_FLAGS="-DDUCKDB_USE_STANDARD_ASSERT -DDUCKDB_CRASH_ON_ASSERT -fsanitize=address,undefined" -DCMAKE_CXX_FLAGS="-DDUCKDB_USE_STANDARD_ASSERT -DDUCKDB_CRASH_ON_ASSERT -fsanitize=address,undefined" -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=address,undefined" -DBUILD_BENCHMARKS=ON -DBUILD_TPCE=ON -DBUILD_SHELL=ON <source_dir>

**Comment by yiyuanliu** [comment]
While attempting to fix another bug, I also discovered this issue and fixed it (#10013). There is a bug in an assert statement, it should be `D_ASSERT(current_cardinality <= total_cardinality)` rather than `D_ASSERT(current_cardinality < total_cardinality)`.

**Comment by Mause** [comment]
Yeah, it being fixed is why I'm confused. I'm definitely not able to reproduce it even with that cmake config

**Comment by yiyuanliu** [comment]
> Yeah, it being fixed is why I'm confused. I'm definitely not able to reproduce it even with that cmake config

I can also reproduce this issue. The method of compilation I used is `make debug`. I think that the problem should be reproducible as long as it's in debug mode and the progress bar has been enabled.

**Comment by Mytherin** [comment]
Seems to be fixed
