### ISSUE TITLE
Duckdb is consuming too much memory way beyond what is specified using max_memory parameter in case of approx_count_distinct function

### ISSUE THREAD

**Issue by mozz3** [duckdb/duckdb#10023]
### What happens?

When query is fired on duckdb database that uses "approx_count_distinct" function, seems that duckdb is consuming way too much memory than what is specified in max_memory parameter

### To Reproduce

1. Launch terminal/command prompt/shell and go the directory where duckdb exe is present
2. Attach to the duckdb database using below command. You can find lineorder_flat.db file in the attachment (attachment contains .txt extension, so please remove .txt extension): [lineorder_flat.db.txt](https://github.com/duckdb/duckdb/files/13817506/lineorder_flat.db.txt)
[lineorder_flat.db.txt](https://github.com/duckdb/duckdb/files/13817506/lineorder_flat.db.txt)

    This file contains empty table
    ```
    duckdb lineorder_flat.db
    ```

3. insert data to the table using below command and [csv file, de-normalised SSB line order data](https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/lineorder_flat.tar.bz2)

    ```sql
    INSERT INTO lineorder_flat SELECT * FROM read_csv('lineorder_flat.tbl', AUTO_DETECT=TRUE);
    ```

4. Set max memory to the database using following SQL.

    ```sql
    set max_memory="2GB";
    ```

5. Run the query that uses "approx_count_distinct" function. In this case I ran below query

    ```sql
    select lo_orderkey, lo_linenumber, lo_custkey, lo_partkey, lo_suppkey, lo_orderdate, lo_commitdate, c_nation, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment, s_name, s_address, s_city, s_nation, s_region, s_phone, p_name, p_mfgr, p_category, p_brand, p_color, p_type, p_size, p_container, sum(lo_tax), sum(lo_discount), sum(lo_extendedprice), approx_count_distinct(c_name)
    from lineorder_flat
    group by all;
    ```

6. Monitor the duckdb usage using top command or on activity monitor in Mac

7. In my case memory usage is going beyond 30GB that duckdb process is consuming. Please see the attached screenshot of Activity monitor of my MacBook

8. Please note that if instead of "approx_count_distinct", if I use "count" function then memory usage is within 2GB limit.

### OS:

MACOS

### DuckDB Version:

Latest

### DuckDB Client:

Command Line

### Full Name:

Mozz3

### Affiliation:

Self

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

<img width="857" alt="memory utilisation" src="https://github.com/duckdb/duckdb/assets/41934476/f0111208-6be9-4d2d-bb51-92c51b714a06">

**Comment by mozz3** [comment]
I used [de-normalised SSB line order data](https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/lineorder_flat.tar.bz2)
It's a de-normalised SSB line order data.

**Comment by l1t1** [comment]
try count(distinct c_name)

**Comment by mozz3** [comment]
This will not work in my case because of

1. This memory issue will still come with other aggregate functions like "string_agg", "entropy" etc.
2. The work around you suggested will give exact count instead of approximate count

**Comment by hawkfish** [comment]
The file you provided is a CSV without a header row. Do you have it handy?

**Comment by mozz3** [comment]
> Not every piece of memory is tracked by the buffer manager. An especially horrible version of this happens when you have a large number of aggregates with complex state (e.g., `list`, `approx_XXX`, `string_agg`, `quantile`, `mode`). I believe that is what is happening here.

Yes, This is exactly what is happening in my case, aggregates are large in number around 500K-600K.

**Comment by mozz3** [comment]
> The file you provided is a CSV without a header row. Do you have it handy?

My bad. Now I have attached a db file containing empty table. Table name is 'lineorder_flat'. 
Please remove .txt extension from uploaded file

Please load the csv using below SQL

`INSERT INTO lineorder_flat SELECT * FROM read_csv_auto('<CSV File Path>');`
[lineorder_flat.db.txt](https://github.com/duckdb/duckdb/files/13748847/lineorder_flat.db.txt)

**Comment by mozz3** [comment]
> @mozz3 I was unable to reproduce this issue with the provided `lineorder_flat.db[.txt]` file. Could you please revise the original post in the thread to ensure that the query reproduces the issue?

Hello, I updated the original post and replicated the issue by following those steps

**Comment by szarnyasg** [comment]
Reproduced 
<img width="974" alt="Screenshot 2024-01-17 at 17 01 39" src="https://github.com/duckdb/duckdb/assets/1402801/56f1b8fa-9cc6-489f-addb-5b28e5b2c1f1">
