### ISSUE TITLE
Performance issue with parquet and a simple filter

### ISSUE THREAD

**Issue by ericemc3** [duckdb/duckdb#10027]
### What happens?

Six equivalent requests on a big parquet file (26 M records), sorted by a quadkey column.

The first two take about 1 second.
The next 4 take more than 25 seconds.

Also, much more bandwidth is consumed with the latter 4. The advantages of range requests on a parquet format seem lost.

The last request is the one I'm interested in: being able to filter on a quadkey resulting from a previous query.

### To Reproduce

```sql
.timer on

CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey = '120222030220' ;

CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey LIKE '120222030220' ;

CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey IN ('120222030220') ;

CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey LIKE (SELECT '120222030220') ;

CREATE OR replace TABLE buffer(quadkey VARCHAR(12)) ; INSERT INTO buffer VALUES ('120222030220');

CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey LIKE (SELECT quadkey FROM buffer) ;

CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet' a
CROSS JOIN buffer
WHERE a.quadkey LIKE buffer.quadkey ;
```

### OS:

Win11

### DuckDB Version:

9.3 -dev1616

### DuckDB Client:

DuckDB cli

### Full Name:

eric mauviere

### Affiliation:

icem7

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
I download the parquet file and query local, same question.
explain analyze shows different plans.

**Comment by szarnyasg** [comment]
Filter pushdown for the `IN` operator is not yet implemented but it is on our short-term roadmap.

**Comment by Tmonster** [comment]
Hi @ericemc3,

I would like to fix this since I've seen this issue popping up. Specifically the performance difference between queries like
`CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey IN ('120222030220') ;`
and 
`CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231218-091031/adresses-france-geo.parquet'
WHERE quadkey = '120222030220' ;`

Those should execute the same plan and have the same performance.

The files don't seem to be available anymore, however, could you upload them here? Or maybe update the URLS to they point to valid links again?

Thanks!

**Comment by ericemc3** [comment]
Hi @Tmonster,
thank you for taking this into account.
Here is an updated test case:
```
CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231228-103716/adresses-france-2023.parquet' WHERE quadkey IN ('120222030220') ;
-- 8 s
CREATE OR REPLACE TABLE t AS SELECT code_insee, geometry FROM 'https://static.data.gouv.fr/resources/ban-format-parquet/20231228-103716/adresses-france-2023.parquet' WHERE quadkey = '120222030220' ;
-- 0.7 s
```

**Comment by Tmonster** [comment]
Thanks! this helps a lot. 
hopefully will have a fix soon 👍

**Comment by Tmonster** [comment]
I think https://github.com/duckdb/duckdb/pull/11473 should address this. Unfortunately to test you have to build feature

**Comment by ericemc3** [comment]
Indeed it looks fixed in last dev version, thanks!
