### ISSUE TITLE
DuckDB raises Out of Memory error after repeated queries despite sufficient memory

### ISSUE THREAD

**Issue by erikhuck** [duckdb/duckdb#10034]
### What happens?

Other issues related to memory seem to correspond to tasks that actually do require too much memory but this is not the case in this issue. After calling `con.sql` repeated times, DuckDB eventually runs out of memory even though the initial queries do **not** use too much memory. DuckDB evidently does not clear its memory usage in between queries so its memory usage appears to continuously build up in one query after the next. When a connection to a database closes, any memory that DuckDB used should be released upon returning the resulting pandas dataframe. DuckDB's memory usage should be empty by the time we loop around to the next query. The previous query result has already become a pandas dataframe and has been processed so any memory used in that query is no longer needed and should be restored to make room for the proceeding queries.

### To Reproduce

The below example is for a table of TableName with about a million rows and about 23000 columns. Due to its size, processing it is split into batches. But DuckDB runs out of memory anyway no matter how small the batches are, suggesting that the memory builds up continuously without releasing it in between queries.
```
import shutil
import duckdb
import numpy as np
import os
import multiprocessing as mp
import tqdm

N_WORKERS = 5
MPP_CACHE_DIR = 'cache_dir'

def main():
    with duckdb.connect('database-file.db', read_only=True) as conn:
        entry_ids = conn.sql(f'SELECT "primary_key" FROM TableName').df().squeeze().to_list()
        print('Entry IDs obtained.')
    entry_ids = [f"'{entry_id}'" for entry_id in entry_ids]
    dataset_size = len(entry_ids)
    process_batch_size = dataset_size // 4000 + 1
    print(f'Process batch size: {process_batch_size}')
    batch_ids = [entry_ids[i:i + process_batch_size] for i in range(0, dataset_size, process_batch_size)]
    if os.path.isdir(MPP_CACHE_DIR):
        shutil.rmtree(MPP_CACHE_DIR)
        print(f'{MPP_CACHE_DIR} removed.')
    os.mkdir(MPP_CACHE_DIR)
    print(f'{MPP_CACHE_DIR} created.')
    workers = list[mp.Process]()
    for batch in tqdm.tqdm(batch_ids):
        process = mp.Process(target=_store_batch, kwargs={'primary_keys': batch})
        process.start()
        workers.append(process)
        if len(workers) == N_WORKERS:
            for process in workers:
                process.join()
                process.close()
            workers = list[mp.Process]()


def _store_batch(primary_keys: list[str]):
    sql = f'SELECT * FROM TableName f JOIN OtherTable l\n' \
          f'ON f."primary_key"=l."primary_key"\n' \
          f'WHERE f."primary_key" IN ({",".join(primary_keys)})'
    with duckdb.connect('database-file.db', read_only=True) as conn:
        conn.sql("SET memory_limit = '60GB'")
        df = conn.sql(sql).df()
    for entry_id, features in df.iterrows():
        path = f'{MPP_CACHE_DIR}/{entry_id}.npy'
        assert not os.path.isfile(path)
        np.save(path, features.to_numpy())


if __name__ == '__main__':
    mp.set_start_method('spawn')
    main()
```

### OS:

linux

### DuckDB Version:

0.8.1

### DuckDB Client:

python

### Full Name:

Erik Huckvale

### Affiliation:

University of Kentucky

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@erikhuck Thanks for reporting this. Unfortunately, we cannot tackle issues without a data set to reproduce the issue.
