### ISSUE TITLE
Binder Error in LATERAL join may indicate wrong column in error description

### ISSUE THREAD

**Issue by thomas-daniels** [duckdb/duckdb#10043]
### What happens?

When using a LATERAL join with references to multiple columns in the subquery, and you mistype one of the column names, the Binder Error may refer to the wrong column (i.e. it will complain about the column which is correct, not the one which is mistyped). That can of course be quite confusing. 

### To Reproduce

```
create table temp1 (a int, b int);
create table temp2 (c int, d int);
select * from temp2, lateral (select count(1) from temp1 where a = c and b > e);
```

The last query fails because `e` is not a column that exists. However, the error message points to the wrong column (`c`, which is not the problem here):

```
Error: Binder Error: Referenced column "c" not found in FROM clause!
Candidate bindings: "temp1.a", "temp1.b"
```

### OS:

macOS 13.6.3, arm64

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI, Python

### Full Name:

Thomas Daniels

### Affiliation:

DNS Belgium

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This is now resolved on `main`:

```sql
v0.9.3-dev2083 6d80c0e347
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
⚪◗ create table temp1 (a int, b int);
⚪◗ create table temp2 (c int, d int);
⚪◗ select * from temp2, lateral (select count(1) from temp1 where a = c and b > e);
Error: Binder Error: Referenced column "e" not found in FROM clause!
Candidate bindings: "temp2.c", "temp2.d"
```
