### ISSUE TITLE
copy to csv doesn't respect memory_limit

### ISSUE THREAD

**Issue by rikuiki** [duckdb/duckdb#10066]
### What happens?

DuckDB RAM consumption grows until exhausts machine total RAM (128GB in my case) when exporting large table to csv.

### To Reproduce

```sql
.open test
.timer on

-- 20B
create table t as
select
  v.range % 2000000000 v
from range(20000000000) v;

SET memory_limit='8GB';
SET threads TO 30;

COPY t TO 't.tsv'
WITH (HEADER, DELIMITER '\t');
```

### OS:

Debian

### DuckDB Version:

Main

### DuckDB Client:

CLI

### Full Name:

Riku Iki

### Affiliation:

nextintelligent.com

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by kshitijrajsharma** [comment]
Same for me on this , Trying to export the table in other formats as well , I tried geojson ( Spatial ) it exhaust the memory

**Comment by szarnyasg** [comment]
Hi @rikuiki, indeed DuckDB can consume more memory than the memory limit in this case. For the time being, you can work around the memory exhaustion by limiting the number of threads. E.g. the following allowed me to finish the export on a MacBook Pro with 64 GB RAM:

```sql
SET threads TO 4;
```

**Comment by rikuiki** [comment]
I tested, and issue still exists.
