### ISSUE TITLE
Catalog Error: Scalar Function with name list_zip does not exist!

### ISSUE THREAD

**Issue by jayzhan211** [duckdb/duckdb#10067]
### What happens?

`list_zip` is not working

```
D SELECT list_zip([1,2,3]);
Error: Catalog Error: Scalar Function with name list_zip does not exist!
Did you mean "list"?
LINE 1: SELECT list_zip([1,2,3]);
               ^
D SELECT list_zip([1,2], [3,4], [5,6]);
Error: Catalog Error: Scalar Function with name list_zip does not exist!
Did you mean "list"?
LINE 1: SELECT list_zip([1,2], [3,4], [5,6]);
```

### To Reproduce

run `select list_zip([1,2,3])`

### OS:

macos 14.1.2, Apple M2

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Jay Zhan

### Affiliation:

Tiktok

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
`list_zip` was added after 0.9.2 was released
