### ISSUE TITLE
Python: import csv gives Invalid Input Error, last version it worked 0.8.0

### ISSUE THREAD

**Issue by dubblej15** [duckdb/duckdb#10068]
### What happens?

When it try to convert CSV to Parquet using, for example:
`Copy ( Select * read_csv('file.csv',delim='␇',header=true, QUOTE=false, ESCAPE=false, columns={'A':'VARCHAR', 'B':'VARCHAR'}) ) to 'file.parquet' (FORMAT PARQUET)`

I receive the following error in Duckdb version 0.9.2 
`duckdb.duckdb.InvalidInputException: Invalid Input Error: The delimiter option cannot exceed a size of 1 byte.`

My file has 65 columns, i don't know how to include that properly as demo data.

But in Duckdb version 0.8.0 it all seems to run fine, only after my upgrade to 0.9.1 i got into issues.

I have tried using other delimiters as well like pipe and comma, but all the error provided is the same.

### To Reproduce

This is a code snap of what would show you the issue, this would run fine in 0.8.0, but would provide error in 0.9.2.
Use the file as attached.

`import os
import duckdb

def Test_defect(folder_ímport_path,folder_export_path):
    bracket_opening = "{"
    bracket_closing = "}"
    for filename in os.listdir(folder_ímport_path):
        if os.path.isfile(os.path.join(folder_ímport_path, filename)):
            print(filename)
            query=f"""Copy (Select * From read_csv('{folder_ímport_path + filename}',delim='␇',header=true, QUOTE=false, ESCAPE=false, columns={bracket_opening}'A':'VARCHAR', 'B':'VARCHAR'{bracket_closing})) to '{folder_export_path + filename[:-4] + '.parquet'}' (FORMAT PARQUET)"""
            print(query)
            run_query_and_save_as_parquet(query)

Test_example_input = "E:/Storage/Example/"
Test_example_output = "E:/Storage/"
Test_defect(Test_example_input,Test_example_output)`

### OS:

Windows 10 x64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Jan-Jaap Loos

### Affiliation:

EY

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
![Screenshot_20231223-193311.png](https://github.com/duckdb/duckdb/assets/1405026/173ad2ae-822a-4821-ad63-fe17fc7723fc)

Did you intend to use a bell byte here?

**Comment by dubblej15** [comment]
> ![Screenshot_20231223-193311.png](https://private-user-images.githubusercontent.com/1405026/292623717-173ad2ae-822a-4821-ad63-fe17fc7723fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzE1MjMsIm5iZiI6MTcwMzMzMTIyMywicGF0aCI6Ii8xNDA1MDI2LzI5MjYyMzcxNy0xNzNhZDJhZS04MjJhLTQ4MjEtYWQ2My1mZTE3ZmM3NzIzZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjNUMTEzMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ3NjNkNmNlZDI4OGQxNWMxNzNjMDhmNWI0NjFmZDhjYjg0NzI4YzUyYzMwNzE4MGNmZDBmMWU2ZDc5YzRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-wiUzGOJZWATKcbhJC4wj4Zs8L-qsObx7c5JVGwh1nY)
> 
> Did you intend to use a bell byte here?

Yes i did, i added an example file as well and my code example.

**Comment by Mause** [comment]
The error message here is (somewhat) correct, the "bel" symbol you're using here is the unicode bel, which is made of up three bytes: https://www.compart.com/en/unicode/U+2407 using UTF-8 (which is the only encoding DuckDB supports)

**Comment by dubblej15** [comment]
Thanks for your reply!

Apologies, I'm new here ;), below some example files.
[Example comma.csv](https://github.com/duckdb/duckdb/files/13761379/Example.comma.csv)
[Example tab.csv](https://github.com/duckdb/duckdb/files/13761380/Example.tab.csv)
[Example pipe.csv](https://github.com/duckdb/duckdb/files/13761381/Example.pipe.csv)
[Example BEL.csv](https://github.com/duckdb/duckdb/files/13761382/Example.BEL.csv)

Any of the above works in 0.8.0, but it gives errors in 0.9.2.
It could be that the intent was not to support it, but it ran before, so hopefully it can be considered.
This was something i really liked :).

Perhaps a bit background for my use: 
As an user of Duckdb this was one of the options which i really liked, as part of a data analyst role i work with many different systems and exports and often in .csv. If i can include a delimiter I always try to include the "bel" symbol, since this really should never occur anymore in modern exports. If that is not possible then I try "tab" separated.
Just based on experience and different libraries used, i always try to avoid the quotation of text fields. This gave often headaches in the past (especially when working with larger files).

**Comment by pdet** [comment]
Indeed, support to multibyte delimiter, quotes and escapes has been dropped in the latest version! 

It might come back in a future version of the reader, but there are currently no plans for that.

**Comment by dubblej15** [comment]
@Mause and @pdet thanks for your replies.

However, I believe the characters i have attempted are all one byte delimiters. Please educate me if I'm wrong here.

About UTF-8 what i know:
[Backward compatibility with ASCII](https://www.twilio.com/docs/glossary/what-utf-8#backward-compatibility-with-ascii)
UTF-8 **uses one byte** to represent code points from 0-127. These first 128 Unicode code points correspond one-to-one with [ASCII](https://en.wikipedia.org/wiki/ASCII) character mappings, so ASCII characters are also valid UTF-8 characters.

As well the , (comma), | (pipe), \t (tab) as BEL are originally ASCII characters and therefore should be one byte characters right?

More than happy to adjust, however i don't know which other character i could use to get the feature working, with any of those characters it throws me errors (incorrectly if you'd ask me).

**Comment by tobilg** [comment]
As per the Discord chat, you can use `E'\n'` to escape those characters eventually: 

https://discord.com/channels/909674491309850675/921073327009853451/1252317019601240237
