### ISSUE TITLE
New database file not created after hard deletion of same named file

### ISSUE THREAD

**Issue by rcaught** [duckdb/duckdb#10070]
### What happens?

My tests are cleaning by hard deleting the database files, but creating a new connection with the same database file path does not result in a file being created.

### To Reproduce

>>> import duckdb
>>> con = duckdb.connect("mydb.db")
>>> import os
>>> os.path.exists("mydb.db")
True
>>> os.remove("mydb.db")
>>> os.path.exists("mydb.db")
False
>>> con = duckdb.connect("mydb.db")
>>> os.path.exists("mydb.db")
False
>>> con.sql("show tables")
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ 0 rows  │
└─────────┘

### OS:

Debian Bullseye

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Ryan Caught

### Affiliation:

Personal

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Lilneo786** [comment]
```
import duckdb

db_path = "mydb.db"

con = duckdb.connect(db_path)

# Now you can perform operations on the database
result = con.execute("SHOW TABLES")
print(result.fetchdf())

# Close the connection when you're done
con.close()

```

**Comment by Mytherin** [comment]
As mentioned the database connection is not closed in your test which means it is still working with the previous (already deleted) file. This is possible in Linux because the old file is kept around by the operating system as long as any process is using the file.
