### ISSUE TITLE
Undefined symbols in local_file_system.obj

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb#10073]
### What happens?

When I'm linking with Zig the shell I will get the following error message:
```
error: lld-link: undefined symbol: RmStartSession
    note: referenced by common.lib(local_file_system.obj):(duckdb::AdditionalLockInfo(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>>))
error: lld-link: undefined symbol: RmRegisterResources
    note: referenced by common.lib(local_file_system.obj):(duckdb::AdditionalLockInfo(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>>))
error: lld-link: undefined symbol: RmGetList
    note: referenced by common.lib(local_file_system.obj):(duckdb::AdditionalLockInfo(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>>))
    note: referenced by common.lib(local_file_system.obj):(duckdb::AdditionalLockInfo(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>>))
error: lld-link: undefined symbol: RmEndSession
    note: referenced by common.lib(local_file_system.obj):(duckdb::AdditionalLockInfo(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>>))
```
The undefined symbol message came first time last week before that I didn't any problems.

### To Reproduce

You can find my fork and build files for Zig from [Github](https://github.com/kimmolinna/duckdb-zig-build)

### OS:

Windows 11

### DuckDB Version:

v0.9.3-dev2114

### DuckDB Client:

-

### Full Name:

Kimmo Linna

### Affiliation:

home

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
You likely need to link in the new windows dll we've added a requirement on, the restart manager dll

**Comment by kimmolinna** [comment]
It's a bit strange that I don't have any problems to compile dll.

**Comment by kimmolinna** [comment]
I should have checked `setup.py`. This should help:
```python
if platform.system() == 'Windows':
    linker_args.extend(['rstrtmgr.lib'])
```
