### ISSUE TITLE
INTERNAL Error: Failed to bind column reference "" [1.2] (bindings: [1.1])

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#10087]
### What happens?

An unexpected internal error happened: `Error: INTERNAL Error: Failed to bind column reference "" [1.2] (bindings: [1.1])`

### To Reproduce

```sql
CREATE TABLE t0(c1 INT);
INSERT INTO t0(c1) VALUES (1);
CREATE VIEW v0(c0, c1, c2) AS SELECT '1', true, t0.c1 FROM t0 ORDER BY -1-2 LIMIT 2; 

SELECT v0.c2 FROM v0 WHERE (NOT (v0.c1 IS NOT NULL));
```

### OS:

ubuntu 22.04

### DuckDB Version:

v0.9.3-dev1998 51c70f3987

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This has been resolved in 0.10.2.
