### ISSUE TITLE
Inconsistent JSON behavior from cli vs copy to. 

### ISSUE THREAD

**Issue by shaunfinnerty** [duckdb/duckdb#10080]
### What happens?

When using .mode json or jsonlines in the cli, the output of an array is inconsistent when using the COPY Statement to a file.   

### To Reproduce

Using the CLI for mode json or jsonlines the array is serialized as a string

```sql
.mode json
select (['apples', 'oranges']) as fruits;
```
```
[{"fruits":"[apples, oranges]"}]
```
or 
```sql
.mode jsonlines
select (['apples', 'oranges']) as fruits;
```
```
{"fruits":"[apples, oranges]"}
```
or 
```sh
duckdb -json -c "select (['apples', 'oranges']) as fruits"
```
```
[{"fruits":"[apples, oranges]"}]
```

Using the CLI and COPY Statement syntax 
```sql
copy (select (['apples', 'oranges']) as fruits) to 'fruits.json';
```
produces a file fruits.json with the array serialized as a json array (expected behavior)
```
{"fruits":["apples","oranges"]}
```

The inconsistency is 
```
{"fruits":"[apples, oranges]"}
{"fruits":["apples","oranges"]}
```

### OS:

macOS 14.2 (23C64)

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Shaun Finnerty

### Affiliation:

none

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by aprock** [comment]
we are still seeing this issue in 1.1.3. 

steps to reproduce.

```
.mode json

--json lists are serialized as strings in json output mode: 
select ([1, 3, 5]) as intlist;
[{"intlist":"[1, 3, 5]"}]

--COPY produces correct json lists:
COPY (select ([1, 3, 5]) as intlist) to STDOUT (FORMAT json, ARRAY true);
[
	{"intlist":[1,3,5]}
]
```

**Comment by Rick-Phoenix** [comment]
Any updates on this? It is still hapening as of today.
