### ISSUE TITLE
Build failure compiling extension/httpfs/create_secret_functions.cpp on Ubuntu 22.04 using GCC 11.4.0.

### ISSUE THREAD

**Issue by redviking1** [duckdb/duckdb#10094]
### What happens?

The DuckDB build fails when attempting to compile `extension/httpfs/create_secret_functions.cpp` on Ubuntu 22.04 using gcc 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04).  This compiler error first occurred after 2023-12-21T06:00:00+00:00 when the virtual machine successfully built version v0.9.3-dev1861.  Note that commit 07f2e8fb6c introduced this error when it introduced source file `extension/httpfs/create_secret_functions.cpp` into branch main.

```
$ git log --abbrev-commit --first-parent --name-status -- extension/httpfs/create_secret_functions.cpp
commit 07f2e8fb6c
Merge: 09a7e42bf4 018ea2c353
Author: Mark <mark.raasveldt@gmail.com>
Date:   Thu Dec 21 13:20:54 2023 +0100

    Merge pull request #10042 from samansmink/stored-credentials

    DuckDB Secrets

A       extension/httpfs/create_secret_functions.cpp
```

Note that commit 09a7e42bf4 (version v0.9.3-dev1872), the commit that immediately precedes commit 07f2e8fb6c on branch main, builds successfully.

### To Reproduce

```
DUCKDB_EXTENSIONS='httpfs;icu;json' \
  GEN=ninja \
  EXTENSION_STATIC_BUILD=1 \
  STATIC_LIBCPP=1 \
  make
```

Compiler output:

```
[4/178] Building CXX object extension/httpfs/CMakeFiles/httpfs_extension.dir/create_secret_functions.cpp.o                                                                                      FAILED: extension/httpfs/CMakeFiles/httpfs_extension.dir/create_secret_functions.cpp.o
/usr/bin/c++ -DDUCKDB_BUILD_LIBRARY -DDUCKDB_EXTENSION_HTTPFS_LINKED=1 -DDUCKDB_EXTENSION_ICU_LINKED=1 -DDUCKDB_EXTENSION_JEMALLOC_LINKED=1 -DDUCKDB_EXTENSION_JSON_LINKED=1 -DDUCKDB_EXTENSION_PARQUET_LINKED=1 -I/home/redviking/projects/duckdb/src/include -I/home/redviking/projects/duckdb/third_party/fsst -I/home/redviking/projects/duckdb/third_party/fmt/include -I/home/redviking/projects/duckdb/third_party/hyperloglog -I/home/redviking/projects/duckdb/third_party/fastpforlib -I/home/redviking/projects/duckdb/third_party/skiplist -I/home/redviking/projects/duckdb/third_party/fast_float -I/home/redviking/projects/duckdb/third_party/re2 -I/home/redviking/projects/duckdb/third_party/miniz -I/home/redviking/projects/duckdb/third_party/utf8proc/include -I/home/redviking/projects/duckdb/third_party/miniparquet -I/home/redviking/projects/duckdb/third_party/concurrentqueue -I/home/redviking/projects/duckdb/third_party/pcg -I/home/redviking/projects/duckdb/third_party/tdigest -I/home/redviking/projects/duckdb/third_party/mbedtls/include -I/home/redviking/projects/duckdb/third_party/jaro_winkler -I/home/redviking/projects/duckdb/extension/httpfs/extension -I/home/redviking/projects/duckdb/extension/httpfs/include -I/home/redviking/projects/duckdb/extension/icu/include -I/home/redviking/projects/duckdb/extension/json/include -I/home/redviking/projects/duckdb/extension/parquet/include -I/home/redviking/projects/duckdb/extension/jemalloc/include -I/home/redviking/projects/duckdb/extension/httpfs/../../third_party/httplib -I/home/redviking/projects/duckdb/extension/httpfs/../parquet/include -I/home/redviking/projects/duckdb/third_party/libpg_query/include -O3 -DNDEBUG -ffunction-sections -fdata-sections -O3 -DNDEBUG   -fPIC -fdiagnostics-color=always -std=c++11 -MD -MT extension/httpfs/CMakeFiles/httpfs_extension.dir/create_secret_functions.cpp.o -MF extension/httpfs/CMakeFiles/httpfs_extension.dir/create_secret_functions.cpp.o.d -o extension/httpfs/CMakeFiles/httpfs_extension.dir/create_secret_functions.cpp.o -c /home/redviking/projects/duckdb/extension/httpfs/create_secret_functions.cpp
.
.
.
In file included from /home/redviking/projects/duckdb/extension/httpfs/include/s3fs.hpp:9,
                 from /home/redviking/projects/duckdb/extension/httpfs/create_secret_functions.cpp:2:
/home/redviking/projects/duckdb/src/include/duckdb/main/secret/secret.hpp: In instantiation of ‘static duckdb::unique_ptr<duckdb::BaseSecret> duckdb::KeyValueSecret::Deserialize(duckdb::Deserializer&, duckdb::BaseSecret) [with TYPE = duckdb::KeyValueSecret]’:
/home/redviking/projects/duckdb/extension/httpfs/create_secret_functions.cpp:122:45:   required from here
/home/redviking/projects/duckdb/src/include/duckdb/main/secret/secret.hpp:188:24: error: could not convert ‘result’ from ‘unique_ptr<duckdb::KeyValueSecret>’ to ‘unique_ptr<duckdb::BaseSecret>’
  188 |                 return result;
      |                        ^~~~~~
      |                        |
      |                        unique_ptr<duckdb::KeyValueSecret>

```

### OS:

Ubuntu Server 22.04 x86_64

### DuckDB Version:

0.9.3

### DuckDB Client:

DuckDB CLI

### Full Name:

Red Viking

### Affiliation:

Self-employed

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by derekmahar** [comment]
gcc 12.2.0 (Debian 12.2.0-14) running on Debian 12 reports the same compiler error.

**Comment by redviking1** [comment]
gcc 12.2.0 (Debian 12.2.0-14) running on Debian 12 reports the same compiler error.

**Comment by redviking1** [comment]
According to the [build log](https://github.com/duckdb/duckdb/actions/runs/7281785494/job/19844913633#step:6:1) for job [Linux HTTPFS](https://github.com/duckdb/duckdb/actions/runs/7281785494/job/19844913633) for [LinuxRelease](https://github.com/duckdb/duckdb/actions/workflows/LinuxRelease.yml) workflow [DuckDB Secrets #10320](https://github.com/duckdb/duckdb/actions/runs/7281785494), job Linux HTTPFS used [GNU C++ 9.4.0](https://github.com/duckdb/duckdb/actions/runs/7281785494/job/19844913633#step:6:31) to successfully compile [`extension/httpfs/create_secret_functions.cpp`](https://github.com/duckdb/duckdb/actions/runs/7281785494/job/19844913633#step:6:353).

GNU C++ 11.4.0 and 12.2.0 must follow a slightly different C++ standard than 9.4.0 that fails to compile `extension/httpfs/create_secret_functions.cpp`.

**Comment by redviking1** [comment]
Following the instructions in [How to Install GCC on Ubuntu 22.04 or 20.04](https://www.linuxcapable.com/how-to-install-gcc-compiler-on-ubuntu-linux/) to install both GCC 10 and GCC 11 and using [`update-alternatives`](https://manpages.ubuntu.com/manpages/jammy/en/man1/update-alternatives.1.html) to prioritize GCC 10, I used GCC 10.5.0 to successfully compile the DuckDB binary and the HTTPFS extension including source file `extension/httpfs/create_secret_functions.cpp`.
