### ISSUE TITLE
OOM for heavy join with strings

### ISSUE THREAD

**Issue by rikuiki** [duckdb/duckdb#10091]
### What happens?

DuckDB OOMs when I am trying to join table with 20B unique rows.

### To Reproduce

```sql
.open test
.timer on

SET memory_limit='16GB';
SET threads TO 30;

create table t as
select
  v
from range(20000000000) v;

create table t2 as select cast(v as varchar) v from t;

create table t3 as select a.v v1, b.v v2 from t2 a join t2 b using (v);

Result: Error: Out of Memory Error: could not allocate block of size 256.0 KiB (14.9 GiB/14.9 GiB used)
```

DuckDB process consumes 66GB at the time of error.

### OS:

Debian

### DuckDB Version:

Main branch

### DuckDB Client:

CLI

### Full Name:

Riku Iki

### Affiliation:

nextintelligent.com

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@rikuiki can you please provide an actual affiliation? According to Google, the string `nextintelligent.com` only exists in this issue tracker.

**Comment by rikuiki** [comment]
> @rikuiki can you please provide an actual affiliation? According to Google, the string `nextintelligent.com` only exists in this issue tracker.

there will be new service eventually on that address, short description: large knowledge graph with search and reasoning. Sorry, I don't have better relevant affiliation at the moment.

**Comment by rikuiki** [comment]
I tested this on 0.10.1, and while duckdb doesn't print OOM message anymore, it consumes RAM well over specified 16GB limit: 70GB+, and process is OOMing on my workstation.
