### ISSUE TITLE
Endless loop in the TPC-H queries

### ISSUE THREAD

**Issue by wangyuancheng964** [duckdb/duckdb#10105]
### What happens?

In a testing environment of TPCH_SF100, after I set the memory limit, the TPC-H query 11 may fall into an endless loop. Note that this does not necessarily occur, it only occurs after repeatedly executing the query dozens of times.

### To Reproduce

1. open database
`./duckdb tpch100g.db`

2.  install and load tpch extension
`INSTALL tpch;`
`LOAD tpch;`

3. generate data for scale factor 100
`CALL dbgen(sf = 100);` 

4. set the memory limit and threads
` set memory_limit = '200MB';` 
` set threads = 8;` 

5. run the query
` PRAGMA tpch(11);` 

### OS:

linux

### DuckDB Version:

master

### DuckDB Client:

duckdb cli

### Full Name:

Wang Yuancheng

### Affiliation:

Wang Yuancheng

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by wangyuancheng964** [comment]
stack trace information：
Thread 8 (Thread 0x7ff88cabc700 (LWP 74289)):
#0  0x00007ff88eb24b2b in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007ff88eb24bbf in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007ff88eb24c5b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x0000000000a5efb9 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#4  0x00000000019e8850 in execute_native_thread_routine ()
#5  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ff88e52af1d in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7ff88d2bd700 (LWP 74288)):
#0  0x00007ff88eb24b2b in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007ff88eb24bbf in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007ff88eb24c5b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x0000000000a5efb9 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#4  0x00000000019e8850 in execute_native_thread_routine ()
#5  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ff88e52af1d in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7ff88dabe700 (LWP 74287)):
#0  0x00007ff88eb24b2b in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007ff88eb24bbf in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007ff88eb24c5b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x0000000000a5efb9 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#4  0x00000000019e8850 in execute_native_thread_routine ()
#5  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ff88e52af1d in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7ff85c25b700 (LWP 74286)):
#0  0x00000000009b81a4 in duckdb::RadixHTGlobalSourceState::AssignTask(duckdb::RadixHTGlobalSinkState&, duckdb::RadixHTLocalSourceState&) ()
#1  0x00000000009c9732 in duckdb::RadixPartitionedHashTable::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::GlobalSinkState&, duckdb::OperatorSourceInput&) const ()
#2  0x0000000001065dc7 in duckdb::PhysicalHashAggregate::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const ()
#3  0x0000000000a5e92f in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) ()
#4  0x0000000000a672eb in duckdb::PipelineExecutor::Execute(unsigned long) ()
#5  0x0000000000a6d7d9 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) ()
#6  0x0000000000a5d3e3 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) ()
#7  0x0000000000a5ed25 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#8  0x00000000019e8850 in execute_native_thread_routine ()
#9  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ff88e52af1d in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7ff85ba5a700 (LWP 74285)):
#0  0x00000000009c9711 in duckdb::RadixPartitionedHashTable::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::GlobalSinkState&, duckdb::OperatorSourceInput&) const ()
#1  0x0000000001065dc7 in duckdb::PhysicalHashAggregate::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const ()
#2  0x0000000000a5e92f in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) ()
#3  0x0000000000a672eb in duckdb::PipelineExecutor::Execute(unsigned long) ()
#4  0x0000000000a6d7d9 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) ()
#5  0x0000000000a5d3e3 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) ()
#6  0x0000000000a5ed25 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#7  0x00000000019e8850 in execute_native_thread_routine ()
#8  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#9  0x00007ff88e52af1d in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7ff85b259700 (LWP 74284)):
#0  0x00007ff88eb24b2b in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007ff88eb24bbf in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007ff88eb24c5b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x0000000000a5efb9 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#4  0x00000000019e8850 in execute_native_thread_routine ()
#5  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ff88e52af1d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7ff85aa58700 (LWP 74283)):
#0  0x00000000009aaf1b in duckdb::RadixHTLocalSourceState::TaskFinished() ()
#1  0x00000000009c9720 in duckdb::RadixPartitionedHashTable::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::GlobalSinkState&, duckdb::OperatorSourceInput&) const ()
#2  0x0000000001065dc7 in duckdb::PhysicalHashAggregate::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const ()
#3  0x0000000000a5e92f in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) ()
#4  0x0000000000a672eb in duckdb::PipelineExecutor::Execute(unsigned long) ()
#5  0x0000000000a6d7d9 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) ()
#6  0x0000000000a5d3e3 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) ()
#7  0x0000000000a5ed25 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#8  0x00000000019e8850 in execute_native_thread_routine ()
#9  0x00007ff88eb1ee25 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ff88e52af1d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7ff88ef5d780 (LWP 74177)):
#0  0x0000000000a60873 in duckdb::Executor::CancelTasks() ()
#1  0x0000000000a66bbb in duckdb::Executor::ExecuteTask() ()
#2  0x0000000000a22516 in duckdb::ClientContext::ExecuteTaskInternal(duckdb::ClientContextLock&, duckdb::PendingQueryResult&) ()
#3  0x0000000000a23a8b in duckdb::PendingQueryResult::ExecuteInternal(duckdb::ClientContextLock&) ()
#4  0x0000000000a23b65 in duckdb::PendingQueryResult::Execute() ()
#5  0x0000000000a273c0 in duckdb::PreparedStatement::Execute(duckdb::vector<duckdb::Value, true>&, bool) ()
#6  0x00000000006771af in duckdb_shell_sqlite3_print_duckbox ()
#7  0x000000000066023a in exec_prepared_stmt ()
#8  0x0000000000661299 in shell_exec ()
#9  0x0000000000662eea in runOneSqlLine ()
#10 0x000000000066b365 in process_input ()
#11 0x000000000064d0ea in main ()

**Comment by lnkuiper** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/10245
