### ISSUE TITLE
MultiIndex lost when saving pandas dataframe into duckdb

### ISSUE THREAD

**Issue by qiuwei** [duckdb/duckdb#1011]
First of all, thanks for the great project. It is lightning fast based on my preliminary benchmark.

I followed the document to load a pandas dataframe with MultiIndex into duckdb.
However, the MultiIndex is not stored in the table.

Is there built-in support for storing the MultiIndex as well?

**Comment by hannesmuehleisen** [comment]
This is true, we ignore the multi index when reading the Pandas DF. What would you expect if there is a multi index present? That we automatically create an index in DuckDB as well? That the pandas multi index is used to speed up queries?

**Comment by qiuwei** [comment]
@hannesmuehleisen The multi index can be stored as normal columns in DuckDB.
Automatic indexing is also preferred.

In our case the multi index is not only used to speed up queries, it is part of the data.
I could manually convert the index to column before saving the pandas dataframe in DuckDB, but it feels cumbersome.

**Comment by hannesmuehleisen** [comment]
I see so those columns are simply lost. That is indeed a bug.

**Comment by polidore** [comment]
still an issue, right?

**Comment by steinwaywhw** [comment]
Does DuckDB drop normal index (an index, but not a multi-index) too? The following snippet shows that normal index is dropped, as far as I can tell. I was looking for documentations on this behavior but haven't found any. It would be nice to document this.

```py
import duckdb
import pandas as pd 

conn = duckdb.connect()
data = pd.DataFrame.from_dict(
  {
    "index": [91, 92, 93],
    "random": [42, 43, 44],
  }
)
data.set_index(keys=["index"], inplace=True)
rel = conn.from_df(data)
rel.create("testtable")

result = conn.execute("select * from testtable").fetch_df()
result
```

My current workaround is to do `data.reset_index()` before using it with DuckDB. But as mentioned above, often times there's real data in the index. So it would be nice if

1. document the behavior regarding data frame index
2. consider offering the support to 
   a. turn indices into columns upon importing into DuckDB
   b. turn columns back into indices when exporting from DuckDB back to DataFrame

I think making corresponding DB indices in DuckDB is not necessary.

**Comment by Ture2019** [comment]
The workaround is maybe not so bad. 
It is quite common to reindex a dataframe multiple times during a data wrangling session.
And not considering any pandas index gives a clear seperation.
Maybe a good idea to update the documentation with a sentence about this...

**Comment by ThomasRolfsnes-EP** [comment]
I was recently bitten by this. I think the most user-friendly solution would be make the index/multi-index available as regular columns. I.e., the following would succeed:
![Uploading CleanShot 2023-12-12 at 09.58.57.png…]()
