### ISSUE TITLE
Process Exits on Invalid PRAGMA with DuckDB Golang Binding

### ISSUE THREAD

**Issue by amigooy** [duckdb/duckdb#10127]
### What happens?

I'm experiencing an issue with the DuckDB Golang binding (go-duckdb v1.5.6) where executing a PRAGMA statement with a non-existent function causes the process to exit unexpectedly. 

### To Reproduce

```go
package main

import (
	"database/sql"
	_ "github.com/marcboeker/go-duckdb"
)

func main() {
	db, _ := sql.Open("duckdb", "")
	_, _ = db.Query(`PRAGMA something`)
}

```

Outputs:
```
libc++abi.dylib: terminating with uncaught exception of type duckdb::CatalogException: Catalog Error: Pragma Function with name something does not exist!
Did you mean "show"?
SIGABRT: abort
PC=0x7fff20423462 m=0 sigcode=0
signal arrived during cgo execution

```

### OS:

MacOS 11.2.3

### DuckDB Version:

v0.9.2(source_id: 3c695d7)

### DuckDB Client:

go-duckdb v1.5.6

### Full Name:

Yang Ou

### Affiliation:

Duozhuayu

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, I could reproduce the issue. The problem seems to occur within the Go binding, so I opened an issue there (with the content of this issue): https://github.com/marcboeker/go-duckdb/issues/142

**Comment by marcboeker** [comment]
I think the problem is located in the `duckdb_extract_statements` function of the C-API. I was able to reproduce the SIGABRT with the following C program:

```
#include "duckdb.h"

duckdb_database db;
duckdb_connection con;

int main() {
	if (duckdb_open(NULL, &db) == DuckDBError) {
		// handle error
	}
	if (duckdb_connect(db, &con) == DuckDBError) {
		// handle error
	}

	duckdb_extracted_statements stmts;
	idx_t foo = duckdb_extract_statements(con, "PRAGMA something", &stmts);

	// cleanup
	duckdb_disconnect(&con);
	duckdb_close(&db);
}
```

Replacing `PRAGMA something` with `PRAGMA show_tables` works, as this command exists.

**Comment by szarnyasg** [comment]
Thanks @marcboeker for clarifying this. We'll look into it.

**Comment by amigooy** [comment]
@marcboeker @szarnyasg  Thank you for your responses. I hesitated before posting the issue but decided it was important to raise it here in the DuckDB project. It seems to me that throwing a `duckdb::CatalogException` exception in the [duckdb_extract_statements](https://github.com/duckdb/duckdb/blob/731829d9dbbd11a9bb1254e5b1730545f8805ce6/src/main/capi/prepared-c.cpp#L25) interface is not the intended behavior, right?

I believe we need to catch exceptions within this interface and assign the error message to the `error` field of `ExtractStatementsWrapper`. This way, bindings in different languages can retrieve the error information via `duckdb_extract_statements_error` interface, eliminating the need to convert C++ exceptions into native exceptions for each language. This is particularly crucial for languages like Go, which lack a traditional exception mechanism.
