### ISSUE TITLE
Recursive CTE with lag returns nulls

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10129]
### What happens?

`WITH RECURSIVE` in combination with `lag(X) OVER ()` produces nulls instead of lagged values.
Maybe it's not supposed to work? (but maybe should there be an error thrown then?)

### To Reproduce

Trying to compute Fibonacci numbers via recursion:
```sql
WITH RECURSIVE X AS (
       SELECT * FROM (VALUES (0, 1), (1, 1)) initial(I, V)
       UNION 
       SELECT I + 1, V + lag(V) OVER () FROM X
       WHERE 0 < I
) SELECT * FROM X LIMIT 4;
```
gives
```
┌───────┬───────┐
│   I   │   V   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     1 │
│     0 │     1 │
│     2 │  NULL │
│     3 │  NULL │
└───────┴───────┘
```

### OS:

Linux

### DuckDB Version:

0.9.3

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
This looks like expected behaviour - Postgres does the same thing. The problem is that RTEs only iterate on the delta table and `LAG` will always be handed a 1 row table here.
