### ISSUE TITLE
regex_replace shows different results in different python versions

### ISSUE THREAD

**Issue by tomiddev** [duckdb/duckdb#10125]
### What happens?

I am trying to remove special characters from a string column using regex_replace using the pattern `'[^a-zA-Z\\s ]+$'`. Initially, I was using Python version 3.9.0 in Visual Studio which was cleaning the special characters in the column but in some places, it failed to remove special characters  `)` and a record value like this `"Provence - alpescote d'azur"` . Now when I used Python version 3.9.7 in Jupyter Notebook it removed all the special characters except the special characters in this record `"Provence - alpescote d'azur"`. What is the best solution to resolve this? 

Input data:
[test_data.csv](https://github.com/duckdb/duckdb/files/13849161/test_data.csv)

Code:
```py
import duckdb
conn = duckdb.connect()
sql_query = """UPDATE blr_sale
                SET State=REGEXP_REPLACE(State, '[^a-zA-Z\s ]+', '')
                WHERE regexp_matches(State, '[^a-zA-Z\s ]+') and State is not null;"""
result = conn.execute(sql_query)
```

Results from python version 3.9.0 Visual studio:-
```
['MO' 'OR' 'TN' 'NY' 'TX' 'ID' 'NJ' 'UT' 'CA' 'IL' 'FL' 'VA' 'AZ' 'VT'
 'GA' "Soult'ukpyolsi" 'Cork' 'Kerry' 'Dublin' 'Limerick' 'Waterford'
 'Andhra Pradesh' 'Haryana' None 'Budapest' 'BacsKiskun' 'Pest'
 'Guatemala' 'Attiki' 'NordrheinWestfalen' 'Hessen' 'Lower Saxony'
 'Saxony' 'Bayern' 'RhinelandPalatinate' 'Berlin' 'Hamburg' 'Thuringia'
 'BadenWurttemberg' 'Saarland' 'Ilede-France' 'Upper Normandy' 'Brittany'
 "ProvenceAlpes-Cote d'Azur" 'Pays de la Loire' 'RhoneAlpes'
 'FrancheComte' 'Alsace' 'Lorraine' 'ItaSuomen Laani' 'EtelaSuomen Laani'
 'Distrito Nacional' 'Frederiksborg' 'Kobenhavn' 'Storstrom'
 'Vestsjalland' 'Staden Kobenhavn' 'Arhus' 'Prague' 'Central Bohemia'
 'East Bohemia' 'Heredia' 'Guangdong' 'Ontario' 'British Columbia'
 'Saskatchewan' 'Alberta' 'Quebec' 'Northwest Territories' 'Manitoba'
 'Yukon Territory' 'Stara Zagora' 'Ceara' 'Sao Paulo' 'Rio Grande do Sul'
 'Minas Gerais' 'Santa Catarina' 'Hamilton' 'Brussels Bruxelles)'
 'Antwerpen' 'Hainaut' 'Al Manamah' 'Vienna' 'Lower Austria' 'Tyrol'
 'Victoria' 'Queensland' 'New South Wales' 'South Australia'
 'Western Australia' 'Tasmania' 'Buenos Aires']
```

Results from python version 3.9.7 Jupter Notebook:-
```
['MO', 'OR', 'TN', 'NY', 'TX', 'ID', 'NJ', 'UT', 'CA', 'IL', 'FL',
       'VA', 'AZ', 'VT', 'GA', 'Soultukpyolsi', 'Cork', 'Kerry', 'Dublin',
       'Limerick', 'Waterford', 'Andhra Pradesh', 'Haryana', None,
       'Budapest', 'BacsKiskun', 'Pest', 'Guatemala', 'Attiki',
       'NordrheinWestfalen', 'Hessen', 'Lower Saxony', 'Saxony', 'Bayern',
       'RhinelandPalatinate', 'Berlin', 'Hamburg', 'Thuringia',
       'BadenWurttemberg', 'Saarland', 'IledeFrance', 'Upper Normandy',
       'Brittany', "ProvenceAlpesCote d'Azur", 'Pays de la Loire',
       'RhoneAlpes', 'FrancheComte', 'Alsace', 'Lorraine',
       'ItaSuomen Laani', 'EtelaSuomen Laani', 'Distrito Nacional',
       'Frederiksborg', 'Kobenhavn', 'Storstrom', 'Vestsjalland',
       'Staden Kobenhavn', 'Arhus', 'Prague', 'Central Bohemia',
       'East Bohemia', 'Heredia', 'Guangdong', 'Ontario',
       'British Columbia', 'Saskatchewan', 'Alberta', 'Quebec',
       'Northwest Territories', 'Manitoba', 'Yukon Territory',
       'Stara Zagora', 'Ceara', 'Sao Paulo', 'Rio Grande do Sul',
       'Minas Gerais', 'Santa Catarina', 'Hamilton', 'Brussels Bruxelles',
       'Antwerpen', 'Hainaut', 'Al Manamah', 'Vienna', 'Lower Austria',
       'Tyrol', 'Victoria', 'Queensland', 'New South Wales',
       'South Australia', 'Western Australia', 'Tasmania', 'Buenos Aires']
```

 

### To Reproduce

The end output should remove all the special characters.

### OS:

x64

### DuckDB Version:

0.9.3

### DuckDB Client:

Python

### Full Name:

Tom

### Affiliation:

Grek

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @tomiddev, can you please share some initial data and the code you used? Please paste them as plain text and avoid screenshots as they are not searchable and difficult to copy from.

**Comment by tomiddev** [comment]
Sorry I assumed I was using a wrong pattern but after testing multiple patterns I ended up with the same issue.

**Comment by Mause** [comment]
Do you see the same issue if you properly escape the slashes in the query? And please clarify which exact version of DuckDB you're using - 0.9.3 doesn't exist, only 0.9.3-dev versions

**Comment by Mause** [comment]
Looking at the sample file as well, it doesn't actually seem to be valid UTF-8, which might be causing issues as well

**Comment by szarnyasg** [comment]
@tomiddev unfortunately the issue is still not reproducible. How do we turn `test_data.csv` into the table `blr_sale`? Trying to use the built-in CSV reader fails due to Unicode issues mentioned by @Mause.
```
    conn.execute("""CREATE TABLE blr_sale AS FROM 'test_data.csv'""")
duckdb.duckdb.InvalidInputException: Invalid Input Error: Error in file "test_data.csv" at line 2: Invalid unicode (byte sequence mismatch) detected in CSV file.
```

**Comment by chrisiou** [comment]
hey @tomiddev, regarding your question:
> I am trying to remove special characters from a string column using regex_replace using the pattern `'[^a-zA-Z\\s ]+$'`. Initially, I was using Python version 3.9.0 in Visual Studio which was cleaning the special characters in the column but in some places, it failed to remove special characters `)` and a record value like this `"Provence - alpescote d'azur"` . Now when I used Python version 3.9.7 in Jupyter Notebook it removed all the special characters except the special characters in this record `"Provence - alpescote d'azur"`. What is the best solution to resolve this?

`regex_replace` by default only replaces the first occurrence of the regular expression. To replace all occurrences, use the global replace (g) flag. You can refer [here](https://duckdb.org/docs/sql/functions/patternmatching#using-regexp_replace) for more information.

**Comment by tomiddev** [comment]
I was using the wrong syntax fo regex_replace. It worked now. Thank you all
