### ISSUE TITLE
WITH RECURSIVE with self-JOIN doesn't work as expected (bug?)

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10136]
### What happens?

No recursion is happening when recursive CTE is used twice in FROM clause. I'm not sure whether this is a bug or a failure in my own understanding of recursive CTE.

### To Reproduce
The following attempt at computing Fibonacci numbers
```sql
WITH RECURSIVE X AS (
    SELECT * FROM (VALUES (0, 1), (1, 1)) initial(I, V)
    UNION ALL
    SELECT current.I + 1, current.V + previous.V 
    FROM X AS current
    JOIN X as previous ON current.I = previous.I + 1
    WHERE 0 < current.I
) SELECT * FROM X LIMIT 5;
```
gives 
```
┌───────┬───────┐
│   I   │   V   │
│ int32 │ int32 │
├───────┼───────┤
│     0 │     1 │
│     1 │     1 │
│     2 │     2 │
└───────┴───────┘
```
instead of 
```
┌───────┬───────┐
│   I   │   V   │
│ int32 │ int32 │
├───────┼───────┤
│     0 │     1 │
│     1 │     1 │
│     2 │     2 │
│     3 │     3 │
│     4 │     5 │
└───────┴───────┘
```

In other words, it's as if `X` was materialized with the first part of the `UNION ALL` and then the `SELECT` in the second part of the `UNION ALL` was computed with the fixed materialized `X`. Note that the ever so slightly changed (two lines modified by `--` comment)
```sql
WITH RECURSIVE X AS (
    SELECT * FROM (VALUES (0, 1), (1, 1)) initial(I, V)
    UNION ALL
    SELECT current.I + 1, current.V -- + previous.V 
    FROM X AS current
    -- JOIN X as previous ON current.I = previous.I + 1
    WHERE 0 < current.I
) SELECT * FROM X LIMIT 5;
```
returns the expected (trivially) recursive output
```
┌───────┬───────┐
│   I   │   V   │
│ int32 │ int32 │
├───────┼───────┤
│     0 │     1 │
│     1 │     1 │
│     2 │     1 │
│     3 │     1 │
│     4 │     1 │
└───────┴───────┘
```

### OS:

Linux

### DuckDB Version:

0.9.3-dev1996

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @soerenwolfers did you try using Postgres? For your first query, it gives a warning:

```sql
postgres=# WITH RECURSIVE X AS (
postgres(#     SELECT * FROM (VALUES (0, 1), (1, 1)) initial(I, V)
postgres(#     UNION ALL
postgres(#     SELECT current.I + 1, current.V + previous.V
postgres(#     FROM X AS current
postgres(#     JOIN X as previous ON current.I = previous.I + 1
postgres(#     WHERE 0 < current.I
postgres(# ) SELECT * FROM X LIMIT 5;
ERROR:  recursive reference to query "x" must not appear more than once
LINE 6:     JOIN X as previous ON current.I = previous.I + 1
                 ^
```

This can be worked around with a lesser-known trick, namely adding `WITH tablename AS (TABLE tablename)` before the subquery after `UNION ALL`. So let's apply this trick:

```sql
WITH RECURSIVE X AS (
    SELECT * FROM (VALUES (0, 1), (1, 1)) initial(I, V)
    UNION ALL (
        WITH X AS (TABLE x)
        SELECT current.I + 1, current.V + previous.V 
        FROM X AS current
        JOIN X as previous ON current.I = previous.I + 1
        WHERE 0 < current.I
    )
) SELECT * FROM X LIMIT 5;
```

With this, Postgres gives an identical result:
```text
postgres(# ) SELECT * FROM X LIMIT 5;
 i | v
---+---
 0 | 1
 1 | 1
 2 | 2
(3 rows)
```

**Comment by szarnyasg** [comment]
Here's a Gist that implements Fibonacci using the Postgres `WITH RECURSIVE`:
```
with recursive r(a, b) as (
  select 0::int, 1::int
  union all
  select b, a + b from r where b < 1000
)
select a from r
limit 10;
```
This works fine in DuckDB:
```text
┌───────┐
│   a   │
│ int32 │
├───────┤
│     0 │
│     1 │
│     1 │
│     2 │
│     3 │
│     5 │
│     8 │
│    13 │
│    21 │
│    34 │
└───────┘
```

**Comment by soerenwolfers** [comment]
@szarnyasg sorry, I didn't try postgresql, I have no experience with SQL beyond duckdb. Is the conclusion that there is no bug?

I did see the solution from your second comment before, but I didn't like that it duplicates the results essentially.

**Comment by szarnyasg** [comment]
> Is the conclusion that there is no bug?

Yes, barring the small difference of the `WITH X AS (TABLE x)` workaround (which is not needed in DuckDB), DuckDB's behavior is identical to Postgres, so the query works as expected.
