### ISSUE TITLE
Incorrect stats size for type DECIMAL(x,0) whil reading parq.snappy files generated with Talend

### ISSUE THREAD

**Issue by Jbcot** [duckdb/duckdb#10148]
### What happens?

Hello ! 

It is my first bug report with Github, please apologize if some details are missing.

I am faced to the following issue : 
```
"InternalException: INTERNAL Error: Incorrect stats size for type DECIMAL(3,0)"
```
I am using DuckDB 0.9.2 and I try to do a DESCRIBE or a SELECT * from a snappy parquet file.
In the structure of the file, there are DECIMAL(X,0) columns.
I have issues only when I have try to read files that are generated with [Talend 8 - R2023-08 using parquet component hadoop 3.3.5](https://help.talend.com/r/en-US/8.0/parquet/tfileoutputparquet-standard-properties).

Note that I have the same message error with parquet viewer tool Tad.

But I have no issue when I read this file with other tools like [parquetviewer of mukunku](https://github.com/mukunku/ParquetViewer) or through an external table with Synapse SQL Dedicated Pool .

When the same data is generated from Synapse SQL Dedicated Pool, DuckDB has no issue to read the data that has DECIMAL(x,0) data.

thank for your support !

Jibc

### To Reproduce

```sql
FROM read_parquet('sample.parq.snappy');
```
```text
Error: INTERNAL Error: Incorrect stats size for type DECIMAL(3,0)
```

### OS:

x64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Jean-Blaise Cottenceau

### Affiliation:

Manitou Group

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@Jbcot thanks for opening this issue. Would it be possible for you to share a Parquet file that reproduces this issue? Of course, this should only contain synthetic data and no internal/confidential data.

**Comment by Jbcot** [comment]
Hello, here is an extract of a file that fails while reading with DuckDB.
[sample.parq.snappy.zip](https://github.com/duckdb/duckdb/files/13863253/sample.parq.snappy.zip)

**Comment by szarnyasg** [comment]
Thanks! The file makes it very easy to reproduce the error.

**Comment by Jbcot** [comment]
Thank you ! great !
