### ISSUE TITLE
Python relational API show() method extremely slow.

### ISSUE THREAD

**Issue by ibmzzj** [duckdb/duckdb#10169]
### What happens?

It appears when using Python relational API show() method, the query is significantly slower than when the result is retrieved by other methods, say df(). The slowness is observed when running group by of more than 1 column on a table of 18K rows in a ~7MB duckdb file.

### To Reproduce

To reproduce,

```py
with duckdb.connect("db_file_on_disk.db") as con:
        con.sql(f"""
            SELECT col1, col2, col3, count(*) c FROM tbl1 GROUP BY ALL;
        """).show()
```

Query cannot finish after a few minutes, but when running

```py
with duckdb.connect("db_file_on_disk.db") as con:
        d = con.sql(f"""
            SELECT col1, col2, col3, count(*) c FROM tbl1 GROUP BY ALL;
        """).df()
        print(d)
```
Query finishes almost instantaneously.

When simply using execute + fetchall, the speed is also fast. so this seems like an issue with just the show method.

### OS:

RHEL8

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Jason

### Affiliation:

Independent

### Have you tried this on the latest `main` branch?

I have NOT tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ibmzzj** [comment]
Hi Gabor, 
there is nothing special about the data. It can be easily reproduced with randomnized string data. See below
```
import duckdb
import pandas as pd
import random
import string

    with duckdb.connect("random_sample.db") as con:
        def random_string(length):
            return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

        n_rows = 18000
        n_cols = 130

        # Create a DataFrame with specified dimensions and random string values
        df = pd.DataFrame({
            f'col_{i}': [random_string(random.randint(1, 8)) for _ in range(n_rows)] 
            for i in range(n_cols)
        })
        con.execute(f"""
            CREATE OR REPLACE TABLE tbl1 AS
                SELECT * FROM df
        """)
        print("table created")

        # Fast
        dfr = con.sql(f"""
            SELECT col_0, col_1, col_2, count(*) FROM tbl1 GROUP BY ALL;
        """).df()
        print(dfr)

        # Never finishes
        con.sql(f"""
            SELECT col_0, col_1, col_2, count(*) FROM tbl1 GROUP BY ALL;
        """).show()

**Comment by szarnyasg** [comment]
Thanks, this is super helpful!

**Comment by Tishj** [comment]
Seems to be fixed as a side-effect of https://github.com/duckdb/duckdb/pull/10245
