### ISSUE TITLE
NaNs are converted to nulls when querying from pandas dataframe

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10196]
### What happens?

NaNs are converted to nulls when querying from pandas dataframe

### To Reproduce

```py
import duckdb
import pandas as pd
import numpy as np
df = pd.DataFrame({'a': [np.nan, 1]})
duckdb.query("""FROM df""")
```
```
┌────────┐
│   a    │
│ double │
├────────┤
│   NULL │
│    1.0 │
└────────┘
```

### OS:

Linux

### DuckDB Version:

'0.9.3-dev1996'

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
I think this is expected behavior, see @Tishj's comment at https://github.com/duckdb/duckdb/issues/4066#issuecomment-1179414986

**Comment by soerenwolfers** [comment]
@szarnyasg I think that issue is about NaN not being the appropriate value to represent missing data (in form of SQL Null) in columns of object type (or any other non-floating point type) when converting from SQL to pandas. 

NaN, however, is definitely the only correct value to represent NaN when converting from a floating point type column to another floating point column (the type of which duckdb decides itself, and correctly chooses a floating point type with the same precision).

**Comment by corwinjoy** [comment]
I will investigate and see if I can reproduce / fix what is happening here.

**Comment by soerenwolfers** [comment]
Thanks for the confirmation. 

I will just state my objection again for the record:

Closing this as won't fix means converting a most regular, non-nullable, float32 column from pandas->polars->duckdb gives different results than pandas->duckdb and it means that pandas->duckdb->pandas gives not the identity. 

Pandas is inconsistent about it's behavior only in **nullable** columns: there, it occasionally converts NaN to NA(=null). Within **non-nullable** columns it always keeps a NaN a NaN.
