### ISSUE TITLE
S3 Authentication Fails with https:// url

### ISSUE THREAD

**Issue by b-schmeling** [duckdb/duckdb#10198]
### What happens?

It seems that the s3 authentication is not working when we use the url format that starts with `https://` instead of an `s3://` uri. 

### To Reproduce

Upload a csv file to an s3 bucket with a secret access key:

```python
import sqlalchemy

REGION = "REPLACE_ME"
ACCESS_KEY_ID = "REPLACE_ME"
SECRET_ACCESS_KEY = "REPLACE_ME"
BUCKET = "REPLACE_ME"

FILE = "REPLACE_ME"

url = f"https://{BUCKET}.s3.{REGION}.amazonaws.com/{FILE}"
s3_uri = f"s3://{BUCKET}/{FILE}"

endpoint_no_https = f"s3.{REGION}.amazonaws.com"

if __name__ == "__main__":
    engine = sqlalchemy.create_engine(
        "duckdb:///:memory:",
        connect_args={
            "config": {
                "s3_region": REGION,
                "s3_access_key_id": ACCESS_KEY_ID,
                "s3_secret_access_key": SECRET_ACCESS_KEY,
                "s3_endpoint": endpoint_no_https,
                "s3_use_ssl": True,
            },
        },
    )
    with engine.begin() as conn:
        conn.execute("INSTALL spatial; LOAD spatial;")
        conn.execute("INSTALL https; LOAD https;")
        result = conn.execute(f"SELECT * FROM read_csv_auto('{url}') LIMIT 10;")
        print(result.fetchall())

```

Try running this code by saving to a file as `csv_ssl.py` with:
```
docker run -it --rm --volume=./csv_ssl.py:/csv_ssl.py --platform=linux/amd64 --entrypoint sh python:3.11.6-slim -c "pip install sqlalchemy==1.4.46 duckdb_engine certifi duckdb==0.9.2 && python -m csv_ssl"

```

You receive the error:
> sqlalchemy.exc.OperationalError: (duckdb.duckdb.IOException) IO Error: HTTP GET error on 'https://temp-bucket-b.s3.us-east-2.amazonaws.com/titanic.csv' (HTTP 403)

If you replace `url` with `s3_uri` in the SQL string, it works as expected.

### OS:

linux/amd64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Bethany Schmeling

### Affiliation:

Datachat

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
Hi @b-schmeling, this is expected behaviour. DuckDB auto-selects a file systems based on the path prefix. For the `https://` prefix this means that the HTTP file system is chosen and not the S3 file system, therefore now authentication headers are included. To make authenticated requests to s3 files, you should use their `s3://` urls
