### ISSUE TITLE
CASCADE or RESTRICT have no effect when dropping VIEW

### ISSUE THREAD

**Issue by sikmike** [duckdb/duckdb#10205]
### What happens?

The child view still exists when using CASCADE while dropping a parent view. 
The parent view gets deleted using RESTRICT while the child VIEW still depends on it. 

### To Reproduce

```
-- Cascade example
CREATE TABLE t1 (i INTEGER, j INTEGER); 
SELECT * FROM t1;
CREATE VIEW t1_parent_view AS SELECT * FROM t1;
SELECT * FROM t1_parent_view;
CREATE VIEW t1_child_view AS SELECT * FROM t1_parent_view;
SELECT * FROM t1_child_view;
DROP VIEW t1_parent_view CASCADE;
SELECT * FROM duckdb_views;
```

```
-- Restrict example
CREATE TABLE t1 (i INTEGER, j INTEGER); 
SELECT * FROM t1;
CREATE VIEW t1_parent_view AS SELECT * FROM t1;
SELECT * FROM t1_parent_view;
CREATE VIEW t1_child_view AS SELECT * FROM t1_parent_view;
SELECT * FROM t1_child_view;
DROP VIEW t1_parent_view RESTRICT;
SELECT * FROM duckdb_views;
```

### OS:

Linux x64

### DuckDB Version:

0.9.2

### DuckDB Client:

DuckDB JDBC driver

### Full Name:

Sik Mike

### Affiliation:

No affiliation

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Views dont currently create dependencies, the plan is to have them create dependencies in the future, at which point RESTRICT and CASCADE should behave as expected 👍
