### ISSUE TITLE
Keyboard interrupt kills Python kernel

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10216]
### What happens?

Keyboard interrupts in Jupyter notebook are often either ignored by duckdb or kill my Python kernels. 

### To Reproduce

I have a MWE that reliably kills my kernel if I keyboard interrupt it (via double pressing "I" in Jupyter) at any time after the progress bar appears. 

```py
import pandas as pd
import numpy as np
import duckdb

n = 1_000_000
columns = 100
df = pd.DataFrame({f'col{i}': 1000 * np.random.sample(n) for i in range(columns)})
duckdb.query("""
SELECT 
DISTINCT ON (floor(col0))
*
FROM df
ORDER by col0 DESC
""")
```
results in 
![image](https://github.com/duckdb/duckdb/assets/16045385/55439e1f-39a1-4b7b-8658-8850376b2572)

If it helps at all, I occasionally get a traceback printed shortly before the kernel dies:

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
File /.../venv103/lib/python3.10/site-packages/IPython/core/formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

File /.../venv103/lib/python3.10/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /.../venv103/lib/python3.10/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

Error: Invalid Error: KeyboardInterrupt: <EMPTY MESSAGE>

At:
  /.../venv103/lib/python3.10/site-packages/traitlets/traitlets.py(723): __set__
  /.../venv103/lib/python3.10/site-packages/IPython/lib/pretty.py(778): _repr_pprint
  /.../venv103/lib/python3.10/site-packages/IPython/lib/pretty.py(410): pretty
  /.../venv103/lib/python3.10/site-packages/IPython/core/formatters.py(708): __call__
  /.../venv103/lib/python3.10/site-packages/IPython/core/formatters.py(223): catch_format_error
  /.../venv103/lib/python3.10/site-packages/decorator.py(232): fun
  /.../venv103/lib/python3.10/site-packages/IPython/core/formatters.py(179): format
  /.../venv103/lib/python3.10/site-packages/IPython/core/displayhook.py(157): compute_format_data
  /.../venv103/lib/python3.10/site-packages/IPython/core/displayhook.py(268): __call__
  /tmp/ipykernel_416160/4183307959.py(8): <module>
  /.../venv103/lib/python3.10/site-packages/IPython/core/interactiveshell.py(3508): run_code
  /.../venv103/lib/python3.10/site-packages/IPython/core/interactiveshell.py(3448): run_ast_nodes
  /.../venv103/lib/python3.10/site-packages/IPython/core/interactiveshell.py(3269): run_cell_async
  /.../venv103/lib/python3.10/site-packages/IPython/core/async_helpers.py(129): _pseudo_sync_runner
  /.../venv103/lib/python3.10/site-packages/IPython/core/interactiveshell.py(3064): _run_cell
  /.../venv103/lib/python3.10/site-packages/IPython/core/interactiveshell.py(3009): run_cell
  /.../venv103/lib/python3.10/site-packages/ipykernel/zmqshell.py(546): run_cell
  /.../venv103/lib/python3.10/site-packages/ipykernel/ipkernel.py(422): do_execute
  /.../venv103/lib/python3.10/site-packages/ipykernel/kernelbase.py(740): execute_request
  /.../venv103/lib/python3.10/site-packages/ipykernel/kernelbase.py(412): dispatch_shell
  /.../venv103/lib/python3.10/site-packages/ipykernel/kernelbase.py(505): process_one
  /.../venv103/lib/python3.10/site-packages/ipykernel/kernelbase.py(516): dispatch_queue
  /usr/lib/python3.10/asyncio/events.py(80): _run
  /usr/lib/python3.10/asyncio/base_events.py(1909): _run_once
  /usr/lib/python3.10/asyncio/base_events.py(603): run_forever
  /.../venv103/lib/python3.10/site-packages/tornado/platform/asyncio.py(195): start
  /.../venv103/lib/python3.10/site-packages/ipykernel/kernelapp.py(736): start
  /.../venv103/lib/python3.10/site-packages/traitlets/config/application.py(1043): launch_instance
  /.../venv103/lib/python3.10/site-packages/ipykernel_launcher.py(17): <module>
  /usr/lib/python3.10/runpy.py(86): _run_code
  /usr/lib/python3.10/runpy.py(196): _run_module_as_main

```

I haven't managed to get a MWE where the interrupt is ignored (and I imagine it's quite hard to write code that can be keyboard-interrupted instantly anytime).

This is happening in a Jupyter notebook running in a Docker container running Ubuntu22.04 with a 16 core and 500 GB memory limit on a flatcar host in a Kubernetes cluster.

### OS:
ubuntu-jammy-0.1.98
Linux-5.15.0-76-generic-x86_64-with-glibc2.35

### Versions:

DuckDB: 0.9.3-dev1996
Python: 3.10.6.final.0
jupyter_server: 2.7.0
jupyterlab: 4.0.9
jupyternotebook: 7.0.6
pandas: 2.1.4
numpy: 1.24.4
IPython: 8.14.0

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
That reproduction looks very odd
Mostly because I am confident wecheck for keyboard interrupts periodically inside of .query

So I'm pretty sure jupyter is not raising a proper keyboard interrupt
I'm curious what they do to cause this

**Comment by soerenwolfers** [comment]
It is true that I cannot reproduce this with a regular python script execution. 
However, I would be surprised if Jupyter wasn't just sending SIGINTs to the kernel.
For example, on a simpler query, I get exactly the exacted behavior, even in Jupyter:
```
KeyboardInterrupt                         Traceback (most recent call last)
KeyboardInterrupt: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
File /.../lib/python3.10/site-packages/IPython/core/formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

File /.../lib/python3.10/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /.../lib/python3.10/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

RuntimeError: Query interrupted
```

**Comment by corwinjoy** [comment]
This is going to be hard to diagnose (and fix) but I'm guessing what is happening is something like the following:
1. The query launches a subprocess to compute the distinct values.
2. The subprocess does not receive the sigint signal.
3. After waiting, the IPython kernel kills the kernel.

This idea is based on a couple of observations:
1. Here is the code for shell interrupt. (I'm not yet sure where the cell code is, but I believe the logic will be similar). It tries a SIGINT, waits 0.1s for a response, then kills the kernel if no response. https://github.com/ipython/ipython/blob/112e5968ed00432584dac5dc31c2311d50506f19/IPython/core/magics/script.py#L289

2. There is a recently fixed bug in IPython where interrupts are having problems with subprocesses in Windows and possibly other platforms.
https://github.com/ipython/ipython/issues/3400

**Comment by soerenwolfers** [comment]
Thanks for looking into this, @corwinjoy . I don't think there is a connection of the problem I'm having to the referenced issues:

1. Your first reference is from the code of the `%%script` cell magic. That's unrelated to the code that runs regular Python cells (but even that doesn't kill the kernel after unsuccessful sigint timeouts but rather kills the subprocess that executes the script). Note that duckdb does not start subprocesses, but operates in-process. 
2. Your second reference is about the notebook becoming indefinitely unresponsive while stuck waiting for input to a subprocess., and the fix is specific to the way these things were implemented on Windows. The problem I have is that the kernel dying (or being unresponsive for the limited time while the query executes, but I think this issue should focus on the dying aspect).

**Comment by corwinjoy** [comment]
@soerenwolfers @m4rs-mt I have created a branch with unit tests to replicate this problem. (Based on the PR I posted above for Windows). You can see the new tests here:
[https://github.com/corwinjoy/duckdb/tree/test_interrupt_query](https://github.com/corwinjoy/duckdb/blob/5d331349440bc19bcecbfc4f128670ce5dd4eda2/tools/pythonpkg/tests/fast/api/test_duckdb_interrupt.py#L1)

I'm not sure, but I think that this problem comes from retrieving wide tables. Essentially, I suspect there is a check for keyboard interrupt between rows but not between columns for certain operations. So, very wide table fetches can be unresponsive. (It looks like there may be a long-running array allocation or copy to handle all the columns, but I need to trace it more precisely). For example, the query below which is similar to your example, can be interrupted just fine:
```
    SELECT 
    DISTINCT ON (floor(col0))
    col0, col1, col2
    FROM df
    ORDER by col0 DESC
```

**Comment by soerenwolfers** [comment]
@corwinjoy Does your unit test replicate dying kernels or only unresponsive queries?

**Comment by corwinjoy** [comment]
@soerenwolfers The test shown here runs the query and detects when duckdb does not react to an interrupt signal promptly.  This lack of response to an interrupt signal is what is causing the kernel manager to step in and kill the kernel.
To understand the above tests, you have to look at the runtime of the two queries. The first query, with limited columns returned, finishes in under 2s and is able to respond to interrupts. The second query, the one you list in the bug report, takes 4.7s to respond to an interrupt on my machine. Why does this matter?
First, you have to understand how Jupyter kernels are launched and monitored:
https://hex.tech/blog/jupyter-kernel-overview/#:~:text=Here%20is%20a%20high%2Dlevel,the%20results%20to%20the%20frontend

So, if we take the example you give, place it in a notebook, run the cells and interrupt the query we get the following log:
`jupyter notebook --debug > logfile.txt 2>&1`
```
[D 18:56:17.792 NotebookApp] activity on f9cd4286-2b39-4ec5-a3af-af426a5bebfb: execute_input
[I 18:56:18.873 NotebookApp] Kernel interrupted: f9cd4286-2b39-4ec5-a3af-af426a5bebfb
[D 18:56:18.873 NotebookApp] 204 POST /api/kernels/f9cd4286-2b39-4ec5-a3af-af426a5bebfb/interrupt (127.0.0.1) 1.310000ms
[I 18:56:51.634 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel f9cd4286-2b39-4ec5-a3af-af426a5bebfb restarted
```

Note the time gap (about 30s) between when the interrupt is sent (during the running of the query) and when the KernelRestarter steps in.  Basically, what is happening is that the hearbeat channel on the kernel has stopped responding during the query so Jupyter steps in. What does this look like in code? Something like this is the logic chain for the KernelRestarter message above:
```
 jupyter_client/restarter.py: 114
 
 def poll(self) -> None:
        if self.debug:
            self.log.debug("Polling kernel...")
        if self.kernel_manager.shutting_down:
            self.log.debug("Kernel shutdown in progress...")
            return
        now = time.time()
        if not self.kernel_manager.is_alive():
            self._last_dead = now
            if self._restarting:
                self._restart_count += 1
            else:
                self._restart_count = 1

            if self._restart_count > self.restart_limit:
                self.log.warning("KernelRestarter: restart failed")
                self._fire_callbacks("dead")
                self._restarting = False
                self._restart_count = 0
                self.stop()
            else:
                 ##########################   <- restart event
                newports = self.random_ports_until_alive and self._initial_startup 
                self.log.info(
                    "KernelRestarter: restarting kernel (%i/%i), %s random ports",
                    self._restart_count,
                    self.restart_limit,
                    "new" if newports else "keep",
                )
 
 # The local is_alive() method looks like:
 
 jupyter_client/client.py line 408:
	async def _async_is_alive(self) -> bool:
        """Is the kernel process still running?"""
        from .manager import KernelManager

        if isinstance(self.parent, KernelManager):
            # This KernelClient was created by a KernelManager,
            # we can ask the parent KernelManager:
            return await self.parent._async_is_alive()
        if self._hb_channel is not None:
            # We don't have access to the KernelManager,
            # so we use the heartbeat.
            return self._hb_channel.is_beating()
        # no heartbeat and not local, we can't tell if it's running,
        # so naively return True
        return True
        
                       
# Here is the hearbeat channel code                
jupyter_client/channels.py:
class HBChannel(Thread):
...
time_to_dead: float = 1.0
...
async def _async_run(self) -> None:
...
            # Wait until timeout
            self._exit.wait(self.time_to_dead)
            # poll(0) means return immediately (see http://api.zeromq.org/2-1:zmq-poll)
            self._beating = bool(self.poller.poll(0))
            if self._beating:
                # the poll above guarantees we have something to recv
                await ensure_async(self.socket.recv())
                continue
            elif self._running:
                # nothing was received within the time limit, signal heart failure
                ...
                
    def is_beating(self) -> bool:
        """Is the heartbeat running and responsive (and not paused)."""
        if self.is_alive() and not self._pause and self._beating:  # noqa
            return True
        else:
            return False
```

**Comment by soerenwolfers** [comment]
Interesting. Any idea why this wouldn't trigger when I try to interrupt a cell that is just
```
import time

for i in range(5):
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        pass
```

**Comment by soerenwolfers** [comment]
Also, the gap of 30s that you report doesn't match the instant kernel death that I experience with my MWE.

**Comment by corwinjoy** [comment]
@soerenwolfers The reason that your python example doesn't have any problems is that python has built in interrupt handlers which will trap interrupt signals and handle them. In contrast, when you bind C++ extension code to python using mechanisms like pybind you have to have an explicit signal loop to catch any interrupt signals or they will be ignored. See, for example,
https://stackoverflow.com/questions/14707049/allowing-ctrl-c-to-interrupt-a-python-c-extension

**Comment by corwinjoy** [comment]
@soerenwolfers One other possibility here is that your kernel is running out of memory with this large query and crashing. So, when I look at the default duckdb settings in jupyter:
```
df_settings = duckdb.query("""
SELECT * FROM duckdb_settings() order by name;
""").df()

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_settings)
```

It seems the default is to only allocate 50GB of memory, and when I run this query in python (see tests above), I will sometimes get an out-of-memory exception like: 
```
E       duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 16384 bytes   
```
It also seems that kernel exceptions are sometimes not correctly conveyed to jupyter. In my tests if I set a higher memory limit I could avoid out-of-memory errors. e.g.
```
SET memory_limit = '5000GB';
```
I will do some research and see if there is a better way to get kernel information from Jupyter.

**Comment by soerenwolfers** [comment]
I'm definitely not running out of memory. I'm on a machine with 500GB (out of which sucks sets 75% as its limit).

I can see how C extension interrupt handling can be different, but I'm still surprised my kernel dies instantly rather than after a 30s wait.

Is it possible for you to attach a debugger to the notebook server process? I can see a AsyncIOKernelRestarter log entry in my terminal, but for some reason I can't attach my pycharm so I can't figure out what exactly the notebook server is thinking why it has to kill the kernel so instantly.

**Comment by corwinjoy** [comment]
@soerenwolfers 
It seems that the clearest way to get kernel crash information is to just run the notebook code directly. That is:
From the notebook: File -> Download as -> Python (.py)
Then, with a conda environment activated (the same environment as used by your notebook)
```
python your_notebook.py
```
(Or run this from a debugger). On my machine I am getting something like `Fatal Python error: Aborted` but not much detail. If you have time, I would be curious to see what error you get / this could provide more details on your crash.

**Comment by corwinjoy** [comment]
@soerenwolfers @Tishj I have put in a PR to fix this issue: https://github.com/duckdb/duckdb/pull/10545

**Comment by corwinjoy** [comment]
@soerenwolfers The latest version of the duckdb code fixes this issue. See https://github.com/duckdb/duckdb/issues/10699 for details and tests.
For now, you have two solutions:
1. Turn off the progress bar so that queries can be safely interrupted.
2. Update to the latest version of duckdb (the latest dev version fixes this, not sure when a release will come out).

**Comment by soerenwolfers** [comment]
Thanks!
