### ISSUE TITLE
Table function can't work with a macro defined as a subquery

### ISSUE THREAD

**Issue by goldmedal** [duckdb/duckdb#10228]
### What happens?

If a macro is defined as a subquery, it cannot be invoked in a table function. Is this behavior considered a bug? If not, I believe DuckDB should offer additional information or provide a modification hint. Alternatively, we may need to document this restriction.

### To Reproduce

```sql
create macro add_exp(a, b) as a + b;
create macro add_subquery(a, b) as (select a + b);
select * from generate_series(1, add_exp(2, 3));
```
```text
┌─────────────────┐
│ generate_series │
│      int64      │
├─────────────────┤
│               1 │
│               2 │
│               3 │
│               4 │
│               5 │
└─────────────────┘
```
```sql
select * from generate_series(1, add_subquery(2, 3));
```
```
Error: Binder Error: Table function cannot contain subqueries
```

### OS:

MacOS

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

Jax Liu

### Affiliation:

Canner

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
Macros only substitute their expression wherever they are used, as such, the error is expected and seems relatively reasonable.
