### ISSUE TITLE
GROUP BY with last(x ORDER BY y) runs OOM; GROUP BY with argmax(x, y) doesn't 

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10224]
### What happens?

Two equivalent and extremely trivial queries; one fail's drastically, one is blazing fast.

### To Reproduce

```
import pandas as pd
import numpy as np
import duckdb
n = 70_000_000
df = pd.DataFrame({
    'time': np.random.choice(pd.date_range('2019-01-01 00:00:00', '2020-01-01 00:00:00', 25_000), n),
    'value': np.random.sample(n),
    'id': np.random.choice(range(300), n)
})
```

then
```
duckdb.query("""
SELECT time::DATE, id, argmax(value, time)
FROM df
GROUP BY ALL
""").df()
```
finishes in 0.7s but
```
duckdb.query("""
SELECT time::DATE, id, last(value ORDER BY time ASC)
FROM df
GROUP BY ALL
""").df()
```
runs OOM after ~2min.

I would have expected duckdb optimizes away the `ORDER BY` in a last. I would have definitely not expected it run OOM. By the way, the OOM can be avoided by pre-sorting the dataframe by the `time` column. Even on a fully presorted dataframe, `argmax` is 3x faster than `last(ORDER BY)` which I imagine shouldn't be possible if `last(ORDER BY)` was handled correctly.

Yet another way of skinning the cat runs OOMs as well, but I don't have as good a reason as for `last` why it definitely shouldn't (and it requires slightly higher `n` to fail, or more columns to be added to DISTINCT):
```
duckdb.query("""
SELECT 
DISTINCT ON (time::DATE, id)
*
FROM df
ORDER by time DESC
""").df()
```

### OS:

Linux-5.15.0-76-generic-x86_64-with-glibc2.35

### DuckDB Version:

0.9.3-dev1996

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello, on my M1Max Mac, it finishes in <10 seconds but indeed uses a lot of memory. So I could partially reproduce this issue – I see that is uses more memory but it doesn't crash for me.

**Comment by soerenwolfers** [comment]
That's interesting. I'm running this on a way overpowered machine at work with 500GB of memory.

I'd be interested if you still see success with the "extra cols" test below.

For me, memory increments (as measured by the memory_profiler jupyter extension) and timings for values leading up to `n=70e6` are

|      n   | (MWE, last)     | (MWE, argmax) | (extra cols, last) | (extra cols, argmax) |
| ------ | ------- | ------- | ---------------- | -------- |
| 10e6    |  5.7GB, 9s   |      340MB, 288ms      |      11.6GB, 20s                    |     1.8GB, 1s        | 
| 20e6   |  11.2GB, 22s   |   640MB, 386ms         |       dnf                   |    2.4GB, 1.3s         | 
| 30e6   |  13.9GB, 31s |   760MB, 446ms         |         dnf                 |  3.6GB, 1.5s           | 
| 40e6   |  21.9GB, 37s |   1.1GB, 564ms         |           dnf               |    4.4GB, 1.7s         | 
| 50e6   |  does not finish |  1.7GB, 530ms         |      dnf                    |  5.7GB, 1.9s           | 

where I restart my kernel after each experiment, 
where "does not finish" means it takes longer than 10min, 
and where I've added two columns 
```
   'region': np.random.choice(list('ABCDEF'), n),
   'client': np.random.choice(list('GHIJKL'), n),
```
to the dataframe and the select clause for the "extra cols" test.

It almost feels like beyond the probelm that `last` uses too much memory, there is a separate problem that duckdb can't use all the available memory?

FWIW, I get 
```
duckdb.query("SELECT * FROM duckdb_settings() WHERE name ILIKE '%mem%'")
```
```
┌──────────────┬───────────┬─────────────────────────────────────────────┬────────────┐
│     name     │   value   │                 description                 │ input_type │
│   varchar    │  varchar  │                   varchar                   │  varchar   │
├──────────────┼───────────┼─────────────────────────────────────────────┼────────────┤
│ max_memory   │ 806.0 GiB │ The maximum memory of the system (e.g. 1GB) │ VARCHAR    │
│ memory_limit │ 806.0 GiB │ The maximum memory of the system (e.g. 1GB) │ VARCHAR    │
└──────────────┴───────────┴─────────────────────────────────────────────┴────────────┘
```
(which is more than 500GB because I'm running in a container with 500GB limit but the host has 1000GB)

**Comment by hawkfish** [comment]
This is an issue with sorted aggregates that comes up from time. Basically, they are holistic (needing all the inputs before they can start) so we accumulate all the values. At scale, this can blow out memory as the intermediate state for the values grows to the size of the data set, and we can't yet spool complex intermediate aggregate states to disk.

That said, you are probably correct that we should be able to add a rewrite rule here for `FIRST` and `LAST`. The only issues I can see are `NULL` semantics (`ORDER BY` lets you specify them) and multi-argument orderings (`ARG_MIN/MAX` only accept scalar ordering fields). But even with those restrictions, we should be able to cover a lot of common cases.

Supporting nested types for the ordering argument would be useful in another optimisation issue I'm looking at (`ASOF` joins with tiny probe tables and large lookup tables) so I may get to that in the not too distant future.

**Comment by soerenwolfers** [comment]
@hawkfish glad to hear it's on your list. Do you think the slowness of the `DISTINCT ON` query is going to be addressed as part of this as well, or do you think it's worth opening a separate issue for it?

**Comment by hawkfish** [comment]
The `DISTINCT ON` query takes 2.5s without the `ORDER BY` clause and about 35s with it. The `ORDER BY` plan has a sorted `FIRST` in the aggregation, which seems unnecessary, so please file that as a separate issue.

**Comment by soerenwolfers** [comment]
To be honest, I'm not sure what the separate issue should look like:

I'm confused how much faster the `DISTINCT ON` is for you than for me. I just double checked, and for me the `DISTINCT ON` with and without `ORDER BY` applied to the MWE didn't go anywhere in the last 15min. (in fact, they froze my machine, using 100% of the memory and CPU :) )

You also say there is a sorted `FIRST` in the `DISTINCT ON` with `ORDER BY`, but to me that makes at least superficial sense (unless you mean there is actual sorting going on when there should be another rewrite rule?).

**Comment by hawkfish** [comment]
I'm working off `HEAD` and I recently made some changes to sorted aggregates that drastically reduces the memory footprint and performance for small (<16) element groups, so that may have something to do with the differences. But the fact that the plan differs when you add an `ORDER BY` clause seems like something someone more familiar with the optimiser should look at.

**Comment by hawkfish** [comment]
My run peaks at 13GB using 14 (hyper-threaded) cores.

**Comment by soerenwolfers** [comment]
The data set is strange indeed, but representative of both the schema and performance characteristics that I got with essentially the same query for something I actually needed to do.

I'm still not sure why the plan shouldn't differ; after all, I do want the last result of each day per group, and only the ORDER BY guarantees that.

Finally, I'm running this myself on a new Linux machine with 16 physical cores and 500GB memory. I could provide more information on the type of CPU if you're interested.

**Comment by hawkfish** [comment]
I have added a new set of logic for `FIRST` and related ("comparable ordering") aggregates that keeps only a single value and key. The key is a `BLOB` that can be binary compared. My current version is restricted to fixed-width ordering keys but @Mytherin has a PR under review that produces binary comparable blobs for arbitrary types.

The improvement for your case is significant:

| Branch | Time | Memory |
| :--- | ---: | ---: |
| first-argmax | 3.5s | 4GB |
| main |15.5s | 13GB |

**Comment by soerenwolfers** [comment]
@hawkfish Thanks for your great work on this! While discussing my performance problems with DISTINCT ON, you mentioned that you were working off HEAD. 
Now that 0.10.0 is out, I was hoping I'd have caught up with you, but I'm still running into lots of problems with DISTINCT ON. I opened a separate ticket for that at https://github.com/duckdb/duckdb/issues/10675 now.
