### ISSUE TITLE
INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

### ISSUE THREAD

**Issue by qzbqzb** [duckdb/duckdb#10233]
### What happens?

When I use the command of load httpfs, I have meetted the exception:INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

### To Reproduce

```
 ./duckdb
v0.9.2 3c695d7ba9
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .timer on
D
D
D
D install httpfs;
Run Time (s): real 0.000 user 0.000047 sys 0.000033
D load httpfs;
Run Time (s): real 0.036 user 0.341400 sys 0.016883
Error: Invalid Input Error: Initialization function "httpfs_init" from file "/root/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/httpfs.duckdb_extension" threw an exception: "INTERNAL Error: Attempted to dereference unique_ptr that is NULL!"
D
```

![图片](https://github.com/duckdb/duckdb/assets/39759821/46bef7f2-9129-433b-9bc7-3834e49999d7)

### OS:

x86

### DuckDB Version:

0.9.1

### DuckDB Client:

shell、java

### Full Name:

qzbqzb

### Affiliation:

Data Developer

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @qzbqzb,
1) What is your DuckDB version? Your issue contains both 0.9.1 and 0.9.2.
2) What operating system are you running exactly? Which Linux distribution and which version?
3) What CPU are you running on? The output of `lscpu` could be useful.

**Comment by szarnyasg** [comment]
@qzbqzb additionally, can you please try with the latest nightly release? It's available here:
https://artifacts.duckdb.org/latest/duckdb-binaries-linux-aarch64.zip

**Comment by qzbqzb** [comment]
> Hello @qzbqzb, thanks for opening this issue. We need additional information to reproduce the issue.
> 
>     1. What is your DuckDB version? Your issue contains both 0.9.1 and 0.9.2.
> 
>     2. What operating system are you running exactly? Which Linux distribution and which version?
> 
>     3. What CPU are you running on? The output of `lscpu` could be useful.

@szarnyasg I am sorry, please excute me! My answer to the above question is as follows:
1. My DuckDB version is only 0.9.2
2. My OS is CentOS, Architecture is x86_64
3. The return of `lscpu` is as follows:
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         42 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               GenuineIntel
  BIOS Vendor ID:        QEMU
  Model name:            Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz
    BIOS Model name:     pc-i440fx-4.1
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  6
    Socket(s):           1
    Stepping:            6
    BogoMIPS:            5200.01
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc re
                         p_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xs
                         ave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2
                          smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves
                          wbnoinvd arat avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq fsrm md_clear arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   288 KiB (6 instances)
  L1i:                   192 KiB (6 instances)
  L2:                    7.5 MiB (6 instances)
  L3:                    42 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-11
Vulnerabilities:
  Gather data sampling:  Unknown: Dependent on hypervisor status
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Vulnerable
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
  Spectre v2:            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by szarnyasg** [comment]
Which CentOS version? You can get it by running:
```bash
cat /etc/issue
```
And could you please try the latest version at https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip?

**Comment by qzbqzb** [comment]
> Which CentOS version? You can get it by running:
> 
> ```shell
> cat /etc/issue
> ```
> 
> And could you please try the latest version at https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip?

thank you,There is my os detail:
![图片](https://github.com/duckdb/duckdb/assets/39759821/68014c99-e702-429b-adc7-b94de706c6e2)

When I try the latest verison at  [](https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip), I have meetted anonther error:
![图片](https://github.com/duckdb/duckdb/assets/39759821/21cfaf22-e426-42bd-9d52-95a6b6c85a46)

**Comment by Peng-Lei** [comment]
If I ``` INSTALL httpfs``` and ```LOAD httpfs``` online on centos7/8 , it is successful

**But,**
 If I run as follow under path ```~/.duckdb/extensions/v0.9.2/linux_amd64_gcc4```:

```wget https://extensions.duckdb.org/v0.9.2/linux_amd64/httpfs.duckdb_extension.gz```
```gzip -d httpfs.duckdb_extension.gz``` 
it will be failed. and report error:
 ```Error: Invalid Input Error: Initialization function "httpfs_init" from file "/root/.duckdb/extensions/v0.9.2/linux_amd64_gcc4/httpfs.duckdb_extension" threw an exception: "INTERNAL Error: Attempted to dereference unique_ptr that is NULL!"```
same as the issue reported.

**Comment by Peng-Lei** [comment]
The file sizes are different between the file that install online and the file that ```wget & gzip -d``` from ```https://extensions.duckdb.org/v0.9.2/linux_amd64/httpfs.duckdb_extension.gz```.

The file installed online is bigger.

**Comment by qzbqzb** [comment]
@szarnyasg Hello
I noticed a problem, For the same CentOS machine, when I use duckdb of 0.8.1 and duckdb of 0.9.2, I have obtained different platforms. For 0.8.1duckdb，it is linux_amd, but for 0.9.2, it is linux_amd_gcc4. Can you tell us the reason for this?

![图片](https://github.com/duckdb/duckdb/assets/39759821/ee4b6d0f-694b-41c2-82ba-343155779440)
![图片](https://github.com/duckdb/duckdb/assets/39759821/9d914894-9592-407c-a87e-f73ca421047d)

And  I understand that the reason for the above error(
INTERNAL Error: Attempted to dereference unique_ptr that is NULL) is this

**Comment by samansmink** [comment]
@Peng-Lei
It appears you either made a typo or you are mixing up binaries here:
```
If I  INSTALL httpfs and LOAD httpfs online on centos7/8 , it is successful

But,
If I run as follow under path ~/.duckdb/extensions/v0.9.2/linux_amd64_gcc4:

wget https://extensions.duckdb.org/v0.9.2/linux_amd64/httpfs.duckdb_extension.gz
gzip -d httpfs.duckdb_extension.gz
it will be failed.
```

Note that we switched our main linux binaries recently to use manylinux2014 image which switched the  platform to linux_amd64_gcc4 (using the old 4.8 ABI). Could you try: `force install httpfs` to ensure you have the correct binary installed?

**Comment by Peng-Lei** [comment]
> @Peng-Lei It appears you either made a typo or you are mixing up binaries here:
> 
> ```
> If I  INSTALL httpfs and LOAD httpfs online on centos7/8 , it is successful
> 
> But,
> If I run as follow under path ~/.duckdb/extensions/v0.9.2/linux_amd64_gcc4:
> 
> wget https://extensions.duckdb.org/v0.9.2/linux_amd64/httpfs.duckdb_extension.gz
> gzip -d httpfs.duckdb_extension.gz
> it will be failed.
> ```
> 
> Note that we switched our main linux binaries recently to use manylinux2014 image which switched the platform to linux_amd64_gcc4 (using the old 4.8 ABI). Could you try: `force install httpfs` to ensure you have the correct binary installed?

Thank you. I mixing up the binaries, because I download extension binaries manually. I think maybe it is better to check the platform between the duckdb and extension as like the version check.

**Comment by szarnyasg** [comment]
Thanks for reporting back – glad it's resolved.
