### ISSUE TITLE
 Invalid unicode (byte sequence mismatch) detected in CSV file

### ISSUE THREAD

**Issue by sahuguet** [duckdb/duckdb#10247]
### What happens?

duckdb cannot parse CSV file with ISO-8859-1 characters.

### To Reproduce

`echo "SELECT * FROM 'sample_FR.csv'" | duckdb`
against the following file
```
ESPECES;DEP;DEPARTEMENT;REGION;ANNEE;CULT_SURF;CULT_REND;CULT_PROD
Autres c�r�ales         ;75 ;PARIS                    ;ILE DE FRANCE                 ;2000;0,00;0,00;0,00
```

### OS:

Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Arnaud Sahuguet

### Affiliation:

Gro Intelligence

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
@sahuguet the CSV reader currently only supports UTF-8 encoded CSV files. A simple workaround it to use [`iconv`](https://en.wikipedia.org/wiki/Iconv) to convert your CSV files before handing them over to DuckDB.
