### ISSUE TITLE
Partitioned write performance

### ISSUE THREAD

**Issue by kylelundstedt** [duckdb/duckdb#10250]
### What happens?

This issue is a continuation of #8690.

I'm trying to convert 750GB of CSV files into Parquet files partitioned by year and month.  I want to take advantage of DuckDB's filter pushdown when reading the Parquet files, so I need to do a partitioned write.

The threaded **non-partitioned** version of my code runs great!  

When trying to do **partitioned** writes (explicit threading not allowed), however, the database temp storage keeps doubling until the hard disk is exhausted.

### To Reproduce

My raw data is 93 CSV files totaling 750 GB uncompressed.  The smallest file is 125 MB; the largest file is 40 GB; and about 20 files are larger than 10 GB.

I'm using the duckdb 0.9.2 CLI on a Mac M1 Max with 32 GB of RAM.

I use duckdb CLI with a permanent database file, running `duckdb my.db < my_code.sql` at the command line.

```{my_code.sql}
copy (
  select *, year(period) as period_year, month(period) as period_month,
  from read_csv('data/stage/*.csv',
    HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', FILENAME = TRUE,
    COLUMNS = {
      'reference_pool_id': 'VARCHAR', 'loan_identifier': 'VARCHAR',
      'period': 'DATE', <more columns> } )
) to 'data/public/performance' (
    FORMAT PARQUET, COMPRESSION GZIP,
    PARTITION_BY (period_year, period_month) );
```

Unfortunately, I can't partition by period_year OR by period_year and period_month.

In both cases, the permanent database file `my.db` creates a `my.db.tmp` folder when the code first runs.  Then, the code gets about 15-20% completed, then the job runs out of hard disk space.

Within the `my.db.tmp` folder, regardless of how I partition, the code generates a series of .tmp files where each .tmp file appears to be about twice as big as the last .tmp file.  See below for an example:

<img width="615" alt="image" src="https://github.com/duckdb/duckdb/assets/3020028/7df1fe42-f8f3-4453-a556-4f4dd53cb6d7">

The "non-partitioned" threaded version writes directly to about 20 GB of Parquet files (one per thread) with no use of tmp files.  So, the PARTITION_BY option seems not to work correctly.

### OS:

macOS Sonoma 14.0

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

Kyle Lundstedt

### Affiliation:

IndustryVault

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by kylelundstedt** [comment]
I also loaded all of the CSV files into a single DuckDb table without any issue.

I then tried to copy that table to Parquet using `PARTITION_BY`.

`copy my_table to 'data/public/my_parquet' (FORMAT PARQUET, COMPRESSION GZIP, PARTITION_BY('period_year');`

I get the same "out of disk space" problem as described above.  The code generates a series of .tmp files associated with the `my.db.tmp` folder, where each .tmp file appears to be about twice as big as the last .tmp file.

**Comment by kylelundstedt** [comment]
The `my.db` DuckDB file is just over 100 GB.  It has 2.8 billion records, with multiple records for each of 54 million unique loans.

I also tried to create a new table containing only the first record for each of the 54 million loans, using window functions as follows. 

```sql
create table loans as
    select * 
    from performance
    qualify row_number() over (
        partition by LOAN_IDENTIFIER 
        order by MONTHLY_REPORTING_PERIOD desc ) = 1
;
```

I got the same "out of disk space" problem as before, with the .tmp files continuing to double in size.

I apologize if these problems are all simply a matter of my Mac not having enough resources (e.g., disk space, RAM).  If anyone can point me to some references about estimating resource requirements, I'd gladly check them out.

**Comment by kylelundstedt** [comment]
I tried to improve my process, and take a smaller "bite" of the apple.

First, I took the 93 CSV files (750 GB total), and gzipped them down to 52 GB.

Then, I took the first 4 gzipped CSV files (600 MB total), and re-ran my code using PARTITION_BY for just the period_year.

```SQL
copy (
  select *, year(period) as period_year, month(period) as period_month,
  from read_csv('data/stage/2000Q*.csv.gz',
    HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', FILENAME = TRUE,
    COLUMNS = {
      'reference_pool_id': 'VARCHAR', 'loan_identifier': 'VARCHAR',
      'period': 'DATE', <more columns> } )
) to 'data/public/performance' (
    FORMAT PARQUET, COMPRESSION GZIP,
    PARTITION_BY (period_year) );
```

Like before, the permanent database file my.db creates a my.db.tmp folder when the code runs.  Within the my.db.tmp folder, the code generates a series of .tmp files where each .tmp file appears to be about twice as big as the last .tmp file.

Using the 600 MB of gzipped CSV files, the tmp directory balloons up to 60 GB.  Then, roughly 370 MB of gzipped Parquet files partitioned by period_year get written to disk.

So, to partition by year all 93 gzipped CSV files (52 GB total), my quick experiment suggest that I'll need ~5 TB of temp space to write out ~30 GB of partitioned Parquet files.  Does that seem right?  I'm still unsure why so much tmp space is necessary.

**Comment by kylelundstedt** [comment]
Hi @hannes.  I'm not sure why this would be a feature request, but I defer to your expertise.  I've also tossed this question out to the DuckDB Discord.
In the interim, I'll look into getting a big external HD, and continue to use our corporate Snowflake account.
DuckDB v0.10 is really awesome; thanks to you and the team for bringing the "laptop data warehouse" closer and closer to reality!

**Comment by firewall413** [comment]
@kylelundstedt I've been in the same boat for that last couple days trying to figure out why my partitioned writes take 80% of the processing time. And bumped into your issue: **Can't combine PER_THREAD_OUTPUT and PARTITION_BY for COPY** . How have you been able to get around this constraint?

**Comment by kylelundstedt** [comment]
Hi @firewall413!  Alas, I've never figured out why partitioned writes perform so poorly and take up so much disk space.  Per Hannes' comment above, perhaps I just don't understand what's required to do the partitioning?

Unfortunately, using DuckDB 1.0+ doesn't solve the problem either.  I've given up on using DuckDB for partitioned writes of TB+ sized datasets, and just used Snowflake instead.  I'm able to do the partitioned writes of these same files without an issue there.
