### ISSUE TITLE
Duckdb Spatial and SQLite Scanner Extension

### ISSUE THREAD

**Issue by ratheesh-kr** [duckdb/duckdb#10253]
### What happens?

We installed duckdb 0.9.2. after installing we were trying to install the Spatial and SQLite Scanner extensions.
the following are the commands used.

```sql
INSTALL spatial; 
LOAD spatial;
```

we get an error message as follows and Spatial and SQLite extensions are not properly working.

```console
Error: near line 37: IO Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.9.2/windows_amd64/spatial.duckdb_extension.gz"
Extension "spatial" is an existing extension.
 (ERROR Read)
Error: near line 41: Catalog Error: Table Function with name "st_read" is not in the catalog, but it exists in the spatial extension.
```

Please try installing and loading the spatial extension:

```sql
INSTALL spatial;
LOAD spatial;
```

### To Reproduce

We tried this in 2 windows machines and in a Windows Sandbox, the errors will be same.

### OS:

Windows 11

### DuckDB Version:

0.9.2

### DuckDB Client:

duckdb cli

### Full Name:

Ratheesh

### Affiliation:

Netspective

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @ratheesh-kr, the URL is valid:
http://extensions.duckdb.org/v0.9.2/windows_amd64/spatial.duckdb_extension.gz

I tried installing it on a Windows laptop and `INSTALL spatial;` followed by `LOAD spatial;` worked fine.

Are you maybe running into a firewall/proxy issue?
