### ISSUE TITLE
Segmentation fault when using udf.

### ISSUE THREAD

**Issue by rkarthik29** [duckdb/duckdb#10257]
### What happens?

get a segmentation fault

### To Reproduce

The segmentation fault occurs when trying to read an input avro file and for each blcok in the avro, convert the records to a pyarrow table. register the pyarrow table as a duckdbtable. Register custom udf, use the custom udf against the registered table. you will get a seg fault 
this is a snippet of my harness, unfortunately cant share exact details and data.
for i in range(n):
        if read_in_loop:
            paTable=pa.Table.from_pylist(records)
        schemas={}
        for field in paTable.schema:
            schemas[field.name]=get_schema(field.type)
        duckdb.register("test",paTable)
        print(duckdb.sql("select * from test"))
        dschema=duckdb.typing.DuckDBPyType(schemas['payload'])
        eschema=duckdb.typing.DuckDBPyType(schemas['event'])
        duckdb.create_function("parse_payload", parse_column,[dschema,VARCHAR],dschema)
        duckdb.create_function("parse_event", parse_column,[eschema,VARCHAR],eschema)
        print(duckdb.sql("select parse_payload(payload,'payload.app.line1') from test"))
        print(duckdb.sql("select parse_event(event,'event.quality.ruleid') from test"))
        duckdb.remove_function("parse_payload")
        duckdb.remove_function("parse_event")

if set read_in_loop to True, we get a segault always. if set to False, i got a segfault once. i can read and create PaTable a million times in a loop, as long as i dont perform the duckdb operations. I feel there is some issue in how duckdb uses pyarrow and how we are doing the operation. Any help is appreciated
[sys.log](https://github.com/duckdb/duckdb/files/13966224/sys.log)

### OS:

macos

### DuckDB Version:

0.9.2, 0.8.0

### DuckDB Client:

python

### Full Name:

Karthik Narayanan

### Affiliation:

capital one

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @rkarthik29, thanks for reporting this. Unfortunately, we cannot tackle an issue without a reproducer.
Please
1) try to provide a minimal working example with data that you can share
2) include the complete Python code (including imports)
3) format your code using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
Cheers
