### ISSUE TITLE
Sequence missing from catalog with ATTACH

### ISSUE THREAD

**Issue by manzt** [duckdb/duckdb#10263]
### What happens?

I'm not sure this is an issue or expected behavior, but I found the following suprising.

Attaching to database with `ATTACH` for a database with a sequence raises a Catalog Error (for a missing sequence).

### To Reproduce

**Create DB**

```sh
duckdb db.duckdb
```

```sql
CREATE SEQUENCE 'id_seq';
CREATE TABLE person (id INT DEFAULT nextval('id_seq'), age INT NOT NULL);
INSERT INTO person (age) VALUES (10);
```

**Attach in a new session**

```sh
duckdb
```

```sql
ATTACH 'db.duckdb';
# Error: Catalog Error: Sequence with name id_seq does not exist!
```

Everything works fine connecting to existing db when starting cli:

```
duckdb db.duckdb
```

### OS:

macOS 14.2 

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Trevor Manz

### Affiliation:

Harvard Medical School

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello, this is fixed on main – can you please try it on the bleeding edge build from 
 https://duckdb.org/docs/installation/?

**Comment by manzt** [comment]
I tried a fresh build on `main` as well as the latest binary from the link you shared:

```
~/downloads/duckdb-binaries-osx on  main took 13s
❯ ./duckdb
v0.9.3-dev2907 64ce105793
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D attach 'db.duckdb';
Error: Catalog Error: Sequence with name id_seq does not exist!
D
```

**Comment by szarnyasg** [comment]
Yes, I was just looking at this issue again. There was a minor inconsistency in the original reproducer (hcc.duckdb vs. db.duckdb). I edited that and the reproduction now workd.

**Comment by manzt** [comment]
Ah, my apologies! Thanks.

**Comment by lhoestq** [comment]
Hi ! Having the exact same issue here on any DuckDB index on Hugging Face, e.g. using nvidia/HelpSteer [index.duckdb](https://huggingface.co/datasets/nvidia/HelpSteer/resolve/refs%2Fconvert%2Fduckdb/default/validation/index.duckdb)

Do you know a workaround we could use in the meantime ? We are experimenting with using ATTACH and remote DuckDB files

**Comment by rzykov** [comment]
I have the same issue - duckdb 0.10

**Comment by liveuser123** [comment]
Facing the same issue. Any idea when this will get fixed or any workaround that we can use meanwhile. @szarnyasg

**Comment by lhoestq** [comment]
Still getting this issue on 0.10.2 btw, e.g. in python:

```python
>>> con.sql("ATTACH 'https://huggingface.co/datasets/fka/awesome-chatgpt-prompts/resolve/refs%2Fconvert%2Fduckdb/default/train/index.duckdb' as fka;")
---------------------------------------------------------------------------
CatalogException                          Traceback (most recent call last)
[<ipython-input-7-803b9003e2bd>](https://localhost:8080/#) in <cell line: 1>()
----> 1 con.sql("ATTACH 'https://huggingface.co/datasets/fka/awesome-chatgpt-prompts/resolve/refs%2Fconvert%2Fduckdb/default/train/index.duckdb' as fka;")

CatalogException: Catalog Error: Sequence with name serial does not exist!
Did you mean "fka.serial"?
```
(same if you load from a local disk instead of using the httpfs extension btw)

**Comment by Mytherin** [comment]
Thanks for reporting, we'll have another look

**Comment by afoltzm** [comment]
I observe a similar issue with sequences using the JDBC driver to execute an ATTACH statement like so:

```java
stmt.execute("ATTACH '/path/to/test.db' AS testdb;");
```

Here's a redacted/edited example of a JDBC error message. It seems to suggest that information about this sequence is present in the catalog:

```
java.sql.SQLException: Catalog Error: Sequence with name num does not exist!
Did you mean "testdb.test_schema.num"?
```

I don't know whether it's related, but I observe a similar issue when trying to reimport an exported database (similar to previous discussions around #2466 and #8496) - the resulting SQL file does not prepend the appropriate schema name (`test_schema`) to the sequence.

I hope this added context helps - I can try to create a reproducible example for both errors if it would be helpful.

**Comment by iMeany** [comment]
Not sure if much additional information for reproduction, but I'm getting a similar error when trying to add a connection to persistent duckdb file from the [Rill](https://github.com/rilldata/rill) application:
`failed to ingest source: failed to attach db "/path/to/my/db": Catalog Error: Sequence with name my_sequence does not exist!`  
  
When connecting from Python or DBeaver, the database works just fine and has the sequence, so maybe something to do with catalogues/schemas, I can provide more info if needed.
