### ISSUE TITLE
COPY does not support compression when writing to s3

### ISSUE THREAD

**Issue by sahuguet** [duckdb/duckdb#10275]
### What happens?

Writing a `csv` file to s3 works.
Writing a `csv.gz` file to s3 does not.

```
% echo "LOAD httpfs; COPY (SELECT 12) TO 's3://sahuguet-bucket/a1.csv'" | duckdb
% aws s3 ls s3://sahuguet-bucket
2024-01-19 00:56:17          6 a1.csv
```

```
% echo "LOAD httpfs; COPY (SELECT 12) TO 's3://sahuguet-bucket/a1.csv.gz'" | duckdb
% aws s3 ls s3://sahuguet-bucket
```

### To Reproduce

Run the same queries on your favorite S3 bucket.

### OS:

Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Arnaud Sahuguet

### Affiliation:

Gro Intelligence

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
FYI this now works on v1.1.3
