### ISSUE TITLE
split_part() is not case insensitive to column name

### ISSUE THREAD

**Issue by ericemc3** [duckdb/duckdb#10287]
### What happens?

split_part() is not case insensitive to column name

### To Reproduce

```
WITH t1 AS (
	FROM VALUES('Paris 1'),('Lyon 2'),('Marseille 3')
	AS t(LIBGEO)
) select split_part(libgeo, ' ', 1) FROM t1 ;
```
```
Error: Binder Error: Macro split_part does not have default parameter LIBGEO!
LINE 4: ) select split_part(libgeo, ' ', 1) FROM t1 ;
```

### OS:

Win11

### DuckDB Version:

9.2

### DuckDB Client:

DuckDB cli

### Full Name:

eric mauviere

### Affiliation:

icem7

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @ericemc3, thanks for opening this issue. This works on `main` now:

```sql
WITH t1 AS (
	FROM VALUES('Paris 1'),('Lyon 2'),('Marseille 3')
	AS t(LIBGEO)
) select split_part(libgeo, ' ', 1) FROM t1 ;
```
```text
┌────────────────────────────┐
│ split_part(libgeo, ' ', 1) │
│          varchar           │
├────────────────────────────┤
│ Paris                      │
│ Lyon                       │
│ Marseille                  │
└────────────────────────────┘
```

**Comment by ericemc3** [comment]
Thank you for your quick reaction!
