### ISSUE TITLE
VALUES clause doesn't produce the right result

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#10304]
### What happens?

When I run a simple values clause, the table seems to be a transpose where cols are really rows. When I convert it to a pandas df it gets further munged.

### To Reproduce

```
>>> import duckdb
>>> duckdb.sql("values((1,'a'), (2, 'b'))")
┌──────────────────────────┬──────────────────────────┐
│           col0           │           col1           │
│ struct(integer, varchar) │ struct(integer, varchar) │
├──────────────────────────┼──────────────────────────┤
│ (1, a)                   │ (2, b)                   │
└──────────────────────────┴──────────────────────────┘

>>> duckdb.__version__
'0.9.3-dev2938'
```

### OS:

linux

### DuckDB Version:

0.9.2 and 0.9.3-dev2938

### DuckDB Client:

python

### Full Name:

Eric Scott

### Affiliation:

Roku

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by scottee** [comment]
Looks like the problem is the outer parens. (Copy and paste from a different sql engine example.) So I don't know if this is correct behavior or not, but it's at least understandable why duckdb does what it does.

**Comment by szarnyasg** [comment]
@scottee thanks for investigating. This is indeed the intended behavior as Postgres also returns the same result:

```
postgres=# values((1,'a'), (2, 'b'));
 column1 | column2
---------+---------
 (1,a)   | (2,b)
(1 row)
```

**Comment by scottee** [comment]
Close this then. I should have double checked it more before submitting.

**Comment by szarnyasg** [comment]
No problem, it is indeed a somewhat confusing behavior to begin with. Cheers, Gabor
