### ISSUE TITLE
Python client casts boolean to Pandas object type (not boolean)

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#10305]
### What happens?

If I `SELECT` a `boolean` and use `.df()` the series has the `object` type, but Pandas has a [`boolean`](https://pandas.pydata.org/docs/user_guide/boolean.html) type.

I can use [`astype`](https://stackoverflow.com/a/67405428/21115) as a workaround, but it would be nicer to have it be `boolean` by default.

### To Reproduce

I tried various queries and they all result in `object` type:

```py
import duckdb

con = duckdb.connect()
con.sql('select true as a;').df().dtypes
# a    bool

con.sql('select cast (NULL as bool) as a;').df().columns
# a    object

con.execute('create table foo (bar bool);')
con.execute('insert into foo values (NULL);')
con.sql('select bar from foo;').df().dtypes
# bar    object

con.execute('delete from foo;')
con.execute('insert into foo values (True);')
con.sql('select bar from foo;').df().dtypes
# bar    bool

con.execute('drop table foo;')
con.execute('create table foo (bar bool not null);')
con.execute('insert into  foo values (True);')
con.sql('select bar from foo;').df().dtypes
# bar    bool
```

### OS:

Ubuntu 20.04.6 LTS x64

### DuckDB Version:

0.9.3.dev2938

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
You should take this up with pandas I think, because this is essentially what we do internally:
```py
import duckdb
import pandas

con = duckdb.connect()
res = con.sql('select true as a;').fetchnumpy()
print(res['a'].dtype)
# bool
df = pandas.DataFrame.from_dict(res)
print(df.columns)
# Index(['a'], dtype='object')
```

**Comment by davetapley** [comment]
Okay, this was quite the rabbit hole 🤪 

First, FYI @Tishj my initial post was misleading (I will edit it too, documenting here for clarity). 

As I now understand it:
The `dtype` from `df.columns` is the type of the _index_ (`a`), not the type of the column.

So instead of `print(df.columns)`, it should be:
```py
print(df.dtypes)
# a    bool          <- type of 'a'
# dtype: object        <- type of the series of types
```
Alternatively, perhaps less confusingly:
```py
print(df['a'].dtype)
# bool
```

Either way: Wait! It works? It says `bool`.
... and yes: it works, but **only if the result set is non-null**.

To see what happens when there is a `null` in there:

```py
res = con.sql('select * from values (True), (NULL) AS t (a);').fetchnumpy()
df = pandas.DataFrame.from_dict(res)

df.dtypes
# a    object
# dtype: object

# or:
df['a'].dtype
# dtype('O')    <--- I assume O is Object, not sure why
```


---

With that said, I found Pandas provides [`convert_dtypes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html) to: 
> Convert columns to the best possible dtypes using dtypes supporting `pd.NA`.

Which we can see working like this:
```py
df_ = df.convert_dtypes()

print(df_.dtypes)
# a    boolean
# dtype: object

print(df_['a'].dtype)
# BooleanDtype
```

I'd argue that that if DuckDB is going to use the `fetchnumpy` / `DataFrame.from_dict` approach to marshaling, then perhaps it can also `convert_dtypes` as well?

Thoughts?

**Comment by davetapley** [comment]
Ugh, one unpleasant edge case: if the result set contains **only** nulls, then `convert_dtypes` makes it an `Int64`:

```py
res = con.sql('select cast(null as bool) a;').fetchnumpy()
df = pandas.DataFrame.from_dict(res)
df_ = df.convert_dtypes()
print(df_.dtypes)
# a    Int64
```

**Comment by davetapley** [comment]
... but if the result set contains **no rows** then it correctly gets `boolean` 🤯 

```py
con.execute('create table foo (bar bool);')
res = con.sql('select * from foo').fetchnumpy()
df = pandas.DataFrame.from_dict(res)
print(df.dtypes)
# bar    bool

df_ = df.convert_dtypes()
print(df_.dtypes)
# bar    boolean
```

**Comment by davetapley** [comment]
Tracked the `Int64` weirdness down to a bug in Pandas:
- https://github.com/pandas-dev/pandas/issues/57077

This manifests here because `fetchnumpy` returns a [masked array](https://numpy.org/doc/stable/reference/maskedarray.html) if there are nulls in the result set.

**Comment by Tishj** [comment]
Yes I'm aware of the issues in pandas surrounding conversion of masked array

We might write some workaround eventually but ideally pandas fixes it on their end

**Comment by DarthKitten2130** [comment]
Uh soo, I was having this conversation on the pandas end with @davetapley and while I have no knowledge of what goes on here, I think to solve this issue on your end you should implement your dtypes with pyarrow, as pyarrow has more consistent types than the traditional numpy dtypes that the majority of pandas code is built on. If you guys find an alternative let me know!

**Comment by davetapley** [comment]
I'm getting a bit off topic for this specific issue, but it just occurred to me:

@Tishj if internal implementation really is `fetchnumpy` / `DataFrame.from_dict`, wouldn't it be _much_ faster to use [Arrow](https://duckdb.org/2021/12/03/duck-arrow.html) (in addition to getting benefit of richer types)? 🤔

**Comment by Tishj** [comment]
If that were stable and supported on all supported python versions I'd be open to making that change, I don't think that's the case however :)

**Comment by davetapley** [comment]
I retract my 'much faster' statement. 

Assuming I'm not doing anything silly in ⬇️ then it seems comparable.

(using https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
```
import duckdb
import timeit


sql = '''
select year(tpep_pickup_datetime), month(tpep_pickup_datetime), dayofmonth(tpep_pickup_datetime), sum(total_amount)
from trips
group by year(tpep_pickup_datetime), month(tpep_pickup_datetime), dayofmonth(tpep_pickup_datetime)
'''


def numpy():
    con = duckdb.connect('./trips.duckdb')
    con.sql(sql).df()

print(timeit.timeit(numpy, number=10))

def arrow():
    con = duckdb.connect('./trips.duckdb')
    con.sql(sql).arrow().to_pandas()

print(timeit.timeit(arrow, number=10))
```
