### ISSUE TITLE
Full seq scan + nested loop join with a subquery in the filter condition

### ISSUE THREAD

**Issue by milicevica23** [duckdb/duckdb#10315]
### What happens?

Hi, while using dbt-duckdb, we started to experience OOM and huge temp tables. After looking into the problem, we discovered that the optimizer didn't create a physical plan as we would have expected. A full scan followed by a nested loop join. 

![image](https://github.com/duckdb/duckdb/assets/46800472/89be5105-3681-4779-85b2-15202c76638c)

The query context is a very simple incremental model in dbt (see steps to reproduce):

1. first run creates a target table with the current batch
2. second run
    a) take the max date from the target table
    b) filter the current batch by max date from a) and execute the transformation

I think this two-step mental model confuses the optimizer that the 2.b) is very inefficient.  
One of the workarounds is that the filter context 2.a) is executed in compilation time from dbt, and the query is already fully prepared/rendered for 2.b)

I gave minimal examples to reproduce those execution plans.  

### To Reproduce

```SQL
INSTALL tpch;
LOAD tpch;
CALL dbgen(sf = 1);

PRAGMA enable_profiling;
PRAGMA profiling_output = 'plan.txt';
```
```sql
-- first dbt run: create target table with some data
CREATE TABLE target AS 
SELECT 
	*
	FROM main.lineitem 
	WHERE l_shipdate <= '1995-11-22'; -- just to take a subset
```
```sql
--second dbt run: take max of the date to find a subset from current batch to process	
--makes nested loop join and full seq scan on the lineitem (screenshot in description)
SELECT 
	count(*) 
	FROM main.lineitem 
	WHERE l_shipdate > (select max(l_shipdate) FROM main.target);
```
```sql
--this plan is something what i expect
SELECT 
	count(*) 
	FROM main.lineitem 
	WHERE l_shipdate > '1995-11-22';
```

### OS:

Windows x64

### DuckDB Version:

v0.9.3-dev2938

### DuckDB Client:

SQL

### Full Name:

Aleksandar Milicevic

### Affiliation:

T-systems

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by jwills** [comment]
👋  following along on this one-- if the best approach for the near term is for me to change how the incremental models are built here to avoid this query pattern, I think I can override dbt's defaults here.

**Comment by Tommel71** [comment]
@milicevica23 I ran into the same problem, would love to see your solution!

**Comment by milicevica23** [comment]
Hi @Tommel71,
We implemented it with a simple macro, which gets the necessary information for the partition.

- macro: 
You can build it as you want. My recommendation is to use the get_single_value macro from dbt_utils
https://github.com/dbt-labs/dbt-utils/blob/23ddc9e1526416b6a8ceeb9a317ca75ba0e92acf/macros/sql/get_single_value.sql#L4

- in a model 

```sql
{{ set  last_day = get_max( table_name = this <you can put another reference>, col_name = '<some column>')}}
-- this executes the query in the compile time

SELECT * FROM table 
WHERE {{ last_day }} == <column>
```

**Comment by tojuasp** [comment]
Thanks for the tip on the macro, running to this issue as well.

I have a query to hive partitioned json files which also starts with a full scan.
```sql
select * from read_ndjson('az://source/*/*/*/*.json', hive_partitioning=true)
where year::int >= (select 2023);
```

But if I simply remove the subquery:
```sql
select * from read_ndjson('az://source/*/*/*/*.json', hive_partitioning=true)
where year::int >= 2023;
```

It works just fine.  Get the same query plans as you.
