### ISSUE TITLE
read_csv_auto sniffer confused by last empty value

### ISSUE THREAD

**Issue by dbold** [duckdb/duckdb#10336]
### What happens?

The CSV type detector gets confused if the last line in the CSV has an empty (ie. null) value.

### To Reproduce

This file test.csv has an int and a float column with null (empty) values:

```csv
ColumnName,FloatColName
1,1.0
1,
,2.0
3,4.5
4,
```

Note how the last line has an empty value for the 2nd column.

The same file without the last line looks about the same. Let's call it `test2.csv`:

```csv
ColumnName,FloatColName
1,1.0
1,
,2.0
3,4.5
```

Here is how DuckDB detect the type differently based on that last line:

```
v0.9.2 3c695d7ba9
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
select typeof(#1), typeof(#2) from read_csv_auto('test.csv') limit 1 ;
```
```text
┌────────────┬────────────┐
│ typeof(#1) │ typeof(#2) │
│  varchar   │  varchar   │
├────────────┼────────────┤
│ BIGINT     │ VARCHAR    │
└────────────┴────────────┘
```
```sql
select typeof(#1), typeof(#2) from read_csv_auto('test2.csv') limit 1 ;
```
```text
┌────────────┬────────────┐
│ typeof(#1) │ typeof(#2) │
│  varchar   │  varchar   │
├────────────┼────────────┤
│ BIGINT     │ DOUBLE     │
└────────────┴────────────┘
```

That extra line with the null value switches the whole type of the 2nd column from `DOUBLE` to `VARCHAR`. Note that the 2nd column has a empty value on the row 2.

(From my tests this bug only happens if the last column has a null value on the last row).

### OS:

x64

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

Emilian Bold

### Affiliation:

DataChat

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @dbold, I tested with the dev version and it detects the type correctly now:
```sql
v0.9.3-dev3244 bf77fe948d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
D select typeof(#1), typeof(#2) from read_csv_auto('test.csv') limit 1 ;
┌────────────┬────────────┐
│ typeof(#1) │ typeof(#2) │
│  varchar   │  varchar   │
├────────────┼────────────┤
│ BIGINT     │ DOUBLE     │
└────────────┴────────────┘
Run Time (s): real 0.002 user 0.001731 sys 0.000566
```
```sql
D select typeof(#1), typeof(#2) from read_csv_auto('test2.csv') limit 1 ;
┌────────────┬────────────┐
│ typeof(#1) │ typeof(#2) │
│  varchar   │  varchar   │
├────────────┼────────────┤
│ BIGINT     │ DOUBLE     │
└────────────┴────────────┘
```

**Comment by dbold** [comment]
Oh, this is great! Awaiting for the next release.

**Comment by szarnyasg** [comment]
Cool, glad it's fixed already on `main`!
