### ISSUE TITLE
case insensitive behavior when using duckdb.connect().register() with pyarrow dataset

### ISSUE THREAD

**Issue by Tonylin1998** [duckdb/duckdb#10356]
### What happens?

I was trying to use duckdb to register a pyarrow dataset in in-memory database.
But when querying the registered view, the output column names become case insensitive.
origin column name in pyarrow dataset is ['cola', 'colA'], but the duckdb query result will become ['cola', 'colA_1']

### To Reproduce

First using following code to register pyarrow dataset to a view name.
```
conn = duckdb.connect()
ds_dataset = ds.dataset(
    file_paths,
    format='parquet',
)
conn.register(
    'test_view',
    ds_dataset
)
```
And query with `sql()`
```
conn.sql('DESCRIBE test_view')
```
| column_name | column_type | null   | key   | default | extra |
| ------------ | ------------ | ------ | ----- | ------- | ----- |
| varchar      | varchar      | varchar | varchar | varchar | int32 |
| ------------ | ------------ | ------ | ----- | ------- | ----- |
| cola         | VARCHAR      | YES    | NULL  | NULL    | NULL  |
| colA_1       | VARCHAR      | YES    | NULL  | NULL    | NULL  |

### OS:

ubuntu

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

Tony Lin

### Affiliation:

LinPoShao

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
minimal reproduction

```py
import duckdb
import pyarrow as pa

data = {
    'id': [1, 2, 3],
    'name': ['John', 'Alice', 'Bob'],
    'age': [25, 30, 28],
    'Id': [101, 102, 103],
    'score': [85.5, 90.3, 88.7],
    'age': [30, 35, 32]
}

# Create a PyArrow table from the data
table = pa.Table.from_pydict(data)
print(table)

conn = duckdb.connect()

conn.register(
    'test_view',
    table
)

conn.sql('DESCRIBE test_view').show()
```

**Comment by Mytherin** [comment]
Thanks for the report! This is intentional behavior. Identifiers in DuckDB are case insensitive. That means that `cola` and `colA` are the same identifier in DuckDB. In the Arrow scan operator, these identical identifiers are disambiguated by appending `_X` to them.
