### ISSUE TITLE
Confusing Parser Error when sampling with an invalid seed value

### ISSUE THREAD

**Issue by ogrisel** [duckdb/duckdb#10361]
### What happens?

Passing an invalid integer seed to `REPEATABLE` raises `Parser Error` with a non-informative error message.

Ideally the range of admissible integer seed values should be specified in the error message.

### To Reproduce

Seeding with `2 ** 31 - 1` works as expected:

```sql
SELECT * FROM 'data.parquet' USING SAMPLE reservoir(1%) REPEATABLE (2147483647);
```

but seeding with larger values raise a

```sql
SELECT * FROM 'data.parquet' USING SAMPLE reservoir(1%) REPEATABLE (2147483648);
```
```
Error: Parser Error: syntax error at or near "2147483648"
LINE 1: ...USING SAMPLE reservoir(1%) REPEATABLE (2147483648);
```

### OS:

macOS

### DuckDB Version:

0.9.3.dev3077

### DuckDB Client:

CLI or Python via Ibis

### Full Name:

Olivier Grisel

### Affiliation:

Inria

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
@szarnyasg Still an issue (also on negative seeds).

**Comment by Dtenwolde** [comment]
With the new parser, using large numbers for seeds is no longer a parsing error: 
```sql
memory D create table foo (i bigint); 
memory D SELECT * FROM foo USING SAMPLE reservoir(1%) REPEATABLE (2147483648);
┌────────┐
│   i    │
│ int64  │
└────────┘
  0 rows
```

Using negative numbers is still a syntax error though (I would say expected to be an error, though it could be more descriptive): 
```sql
memory D SELECT * FROM foo USING SAMPLE reservoir(1%) REPEATABLE (-1);
Parser Error:
syntax error at or near "-"

LINE 1: SELECT * FROM foo USING SAMPLE reservoir(1%) REPEATABLE (-1);
                                                                 ^
```
