### ISSUE TITLE
Selecting entire rows fails when the source table is named 'user'

### ISSUE THREAD

**Issue by joshgelbard** [duckdb/duckdb#10363]
### What happens?

If you select "entire rows" (as in `select foo from foo`), you generally get back each row as a struct. But if the table is named `user`, or if it's aliased to `user` in the query, you get the string `"duckdb"`—at least at the command line.

```sql
with x as (select 1) select foo from x foo;
```
```
┌─────────────────────┐
│         foo         │
│ struct("1" integer) │
├─────────────────────┤
│ {'1': 1}            │
└─────────────────────┘
```
```sql
with x as (select 1) select user from x user;
```
```
┌─────────┐
│  user   │
│ varchar │
├─────────┤
│ duckdb  │
└─────────┘
```

### To Reproduce

```sql
with x as (select 1) select user from x user;
```
```
┌─────────┐
│  user   │
│ varchar │
├─────────┤
│ duckdb  │
└─────────┘
```

### OS:

macos aarch64

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

Joshua Gelbard

### Affiliation:

Ladder Financial Inc.

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by tlm365** [comment]
@joshgelbard Your queries makes me a bit confuse, I don't really understand your intention. However, hopefully the following explanations can help you.
About the issue you raised "But **if the table is named user** (1), or **if it's aliased to user in the query** (2), you get the string "duckdb"—at least at the command line."

(1) -> No, it not.
```
with x as (select 1) select * from x user;
┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
└───────┘
```
(2) -> Not really, if your target table's schema has a "user" column it still works fine.
```
with x as (select 1 as user) select * from x;
┌───────┐
│ user  │
│ int32 │
├───────┤
│     1 │
└───────┘
```
But if there is no "user" column in the schema then it behaves like the "SELECT USER" query in standard SQL, it is used to get information about the currently logged-in user executing the statement.
```
select user;
┌─────────┐
│  user   │
│ varchar │
├─────────┤
│ duckdb  │
└─────────┘
```
