### ISSUE TITLE
lambda Indexes as Parameters does not work

### ISSUE THREAD

**Issue by NielsKorschinsky** [duckdb/duckdb#10379]
### What happens?

Hi,
Executing the example from the [documentation](https://duckdb.org/docs/sql/functions/lambda#indexes-as-parameters):
`SELECT list_filter([1, 3, 1, 5], (x, i) -> x > i);`

The bug is that the syntax of `(x,i)` in a lambda arg does not seem to be supported:
`Binder Error: Incorrect number of parameters in lambda function! list_filter expects 1 parameter(s).`

It is expected to be able to access the index.

### To Reproduce

1. Go to the [documentation](https://duckdb.org/docs/sql/functions/lambda#indexes-as-parameters)
2. Copy the sql statement: `SELECT list_filter([1, 3, 1, 5], (x, i) -> x > i);`
3. Execute it -> Fails

```python
import duckdb
duckdb.sql("SELECT list_filter([1, 3, 1, 5], (x, i) -> x > i);")
```

Error message: 
```
---------------------------------------------------------------------------
BinderException                           Traceback (most recent call last)
Cell In[5], [line 1](vscode-notebook-cell:?execution_count=5&line=1)
----> [1](vscode-notebook-cell:?execution_count=5&line=1) duckdb.sql("SELECT list_filter([1, 3, 1, 5], (x, i) -> x > i);")

BinderException: Binder Error: Incorrect number of parameters in lambda function! list_filter expects 1 parameter(s).
```

### OS:

MacOS

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Niels Korschinsky

### Affiliation:

IBM

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
The version says `dev`, have you tried this on latest `main` ?

**Comment by NielsKorschinsky** [comment]
Hi @Tishj !
I dont see where I've linked dev - sorry for that!

I tested the issue on the main `duckdb-0.9.2` and on the pre-release `duckdb-0.9.3.dev3257`.
Both show the very same issue.

**Comment by NielsKorschinsky** [comment]
Ah, I found the `dev` you mentioned.
It seems like google directly pointed me to the dev documentation and not the 0.9.2 documentation.
In the main documentation the page for lamdas is completely missing.

**Comment by szarnyasg** [comment]
@NielsKorschinsky lambda's are only supported in the dev version, which you can acquire by building `main` or downloading a nightly build. They will be part of DuckDB v0.10, planned to be released in ~two weeks.

**Comment by NielsKorschinsky** [comment]
Thanks a lot for that update!
I tried installing the pre-release, but notice on `duckdb.__version__` that it was still using the main one.
Excited for the new release!
