### ISSUE TITLE
Segmentation Fault in Python Script When Executing DuckDB Queries

### ISSUE THREAD

**Issue by mustafahasankhan** [duckdb/duckdb#10375]
### What happens?

Encountering a segmentation fault in a Python script during the execution of specific DuckDB queries. The program exits abruptly with Error code 139, without any DuckDB exceptions or error messages,

### To Reproduce

1. Set up a DuckDB environment with version 0.9.2 in a Docker container using Python slim 3.11 on an EKS container.
2. Execute the following SQL queries in DuckDB:
```
CREATE TABLE IF NOT EXISTS test AS
SELECT unnest(inputs) as asset, * EXCLUDE (inputs, outputs) FROM raw_data;

ALTER TABLE test ADD COLUMN matching_asset STRUCT(type_name VARCHAR, name VARCHAR);

UPDATE test SET matching_asset = (
    SELECT row(type_name, name) FROM old_assets
    WHERE asset.database = old_assets.database AND
    asset.schema = old_assets.schema
    LIMIT 1
);

CREATE TABLE tmp_last_timestamp AS
SELECT matching_asset as asset, EPOCH_MS(MAX(record_time)) as last_record_timestamp
FROM test
WHERE matching_asset IS NOT NULL
GROUP BY matching_asset;

CREATE TABLE tmp_query_tags_raw AS
SELECT matching_asset AS asset, tag, count(tag) AS tag_count
FROM ( SELECT matching_asset, UNNEST(tags) AS tag FROM test)
WHERE matching_asset IS NOT NULL AND tag IS NOT NULL
GROUP BY matching_asset, tag;
```

3. Observe that the Python script exits with Error code 139 upon executing the last query.

The data I am dealing with is sensitive hence I might not be able to share it, would definitely help with any follow up questions around the same.

Worth to mention that it is not reproducible on my local Mac M1 machine [Sonoma].

### OS:

Python 3.11 slim [Debian]

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Mustafa Hasan Khan

### Affiliation:

Atlan

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I'm sorry but this is far from a reproducable example, for starters there is no python script attached
Unless you can reproduce this with the CLI, I would have to see a python script

**Comment by mustafahasankhan** [comment]
> I'm sorry but this is far from a reproducable example, for starters there is no python script attached Unless you can reproduce this with the CLI, I would have to see a python script

I do agree but I am afraid I won't be able to provide data for now, I created this ticket as it was suggested to me on official discord channel.
I will check whether I can morph the data and share it.
Regards

**Comment by mustafahasankhan** [comment]
@szarnyasg I mentioned these details specifically as I am not able to reproduce it locally on my Mac M1 machine on Sonoma.
