### ISSUE TITLE
InvalidInputException when using dicts with different set of keys in python

### ISSUE THREAD

**Issue by suchanlee** [duckdb/duckdb#10381]
### What happens?

In python, when trying to query a dataframe that has nested dict column values with different keys, duckdb throws `duckdb.duckdb.InvalidInputException: Invalid Input Error: Failed to cast value`.

A similar issue has been raised in https://github.com/duckdb/duckdb/issues/7734 and it seems like the particular case in that issue seems to work now. But 

Tested on duckdb 0.8.1, 0.9.2.

### To Reproduce

Running this code
```python
import duckdb
import pandas as pd

con = duckdb.connect(database=':memory')

df = pd.DataFrame(data={
    'col1': [
        {'a': {'b': {'x': 'A', 'y': 'B'}}},
        {'c': {'b': {'x': 'A'}}}
    ]
})


con.register('tbl', df)
con.execute("SELECT * FROM tbl").fetchdf()
```

will result in:
`duckdb.duckdb.InvalidInputException: Invalid Input Error: Failed to cast value: Unimplemented type for cast (STRUCT(b STRUCT(x VARCHAR)) -> MAP(VARCHAR, MAP(VARCHAR, VARCHAR)))`

The only difference between the dataframe created here and in https://github.com/duckdb/duckdb/issues/7734 is in 7734 the keys of the dict are the same but in here the key of the dicts are different.

### OS:

OSX

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Suchan Lee

### Affiliation:

Hex Technologies

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ntjess** [comment]
@Mytherin I cam across the issue with the following test:

```python
conn = duckdb.connect(":memory:")
conn.execute("CREATE OR REPLACE TABLE Object (Metadata MAP(VARCHAR, VARCHAR))")
conn.execute("INSERT INTO Object VALUES (?::MAP(VARCHAR, VARCHAR))", [{}])
display(conn.table("Object"))
conn.execute("INSERT INTO Object VALUES (?::MAP(VARCHAR, VARCHAR))", [{"Id": "test"}])
```
![image](https://github.com/user-attachments/assets/92eabe28-a835-4c93-ad8f-ffae3cdefb95)

Is it a result of the same issue, or should I submit a new ticket?

Thanks!

**Comment by Mytherin** [comment]
That's unrelated to this issue
