### ISSUE TITLE
Query optimizer introduces BLOCKWISE_NL_JOIN

### ISSUE THREAD

**Issue by lbb** [duckdb/duckdb#10387]
### What happens?

When running the below query with double Left Joins, it results in a very slow `BLOCKWISE_NL_JOIN`. However, removing the enum 

```sql
     LEFT JOIN "filter" AS f ON (q.ident = f.ident AND q.x = f.x AND q.y = f.y AND f.filtered = TRUE AND q.link = 'R')

-- Remove q.link = 'R'
     LEFT JOIN "filter" AS f ON (q.ident = f.ident AND q.x = f.x AND q.y = f.y AND f.filtered = TRUE)
```

constraint on `q.link` results in a much faster `HASH_JOIN`. This behaviour seems odd to me but I might be mistaken. Thanks to @hawkfish  for creating this reproducer!
 
<img width="418" alt="Screenshot 2024-01-28 at 22 22 59" src="https://github.com/duckdb/duckdb/assets/7387703/9b3fbd74-f7c6-4f83-a87c-6a3dc218617e">

### To Reproduce

```sql
--- Prepare tables
CREATE type link_code AS enum ('R', 'S', 'T'    );

create table links (
    link_id int,
    link link_code,
);

insert into links values
    (0, 'R'),
    (1, 'S'),
    (2, 'T')
;

create table queue as
    select
        case when q % 2 = 0 then null else q end as ident,
        link,
        q // 7 as x,
        q // 5 as y,
    from range (17461861) r(q) inner join
         links l
         on (r.q % 3 = l.link_id);

create table sent as
    select
        case when q % 2 = 0 then null else q end as ident,
        link,
        q // 7 as x,
        q // 5 as y,
    from range (14804132) r(q) inner join
         links l
         on (r.q % 3 = l.link_id);

create table filter as
    select
        case when q % 2 = 0 then null else q end as ident,
        link,
        q // 7 as x,
        q // 5 as y,
        q  % 29 = 0 as filtered,
        
    from range (2612729) r(q) inner join
         links l
         on (r.q % 3 = l.link_id);

--- THE QUERY
EXPLAIN ANALYZE
SELECT *
FROM queue q
     LEFT JOIN sent s ON (q.ident = s.ident AND q.link = s.link AND q.x = s.x AND q.y = s.y)
     LEFT JOIN "filter" AS f ON (q.ident = f.ident AND q.x = f.x AND q.y = f.y AND f.filtered = TRUE AND q.link = 'R')
WHERE f.ident IS NULL AND s.ident IS NULL
```

### OS:

macOS

### DuckDB Version:

0.9.2

### DuckDB Client:

cli

### Full Name:

Luk Burchard

### Affiliation:

In private capacity

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by xuke-hat** [comment]
This is because hash join doesn't support left join with left side predicate in join conditions.

**Comment by lbb** [comment]
A terrible workaround is to add a column to the `"filter"` with a default value of `'R'` and use if for the join.

```sql
 LEFT JOIN (.... AND q.link = f.link)
```

But is there a better way of doing this without altering the table?

**Comment by xuke-hat** [comment]
You can replace
```
select a.xxx, b.xxx from a left join b on (... and a.link = 'R')
```
with
```
select a.xxx, b.xxx from a left join b on (...) where a.link = 'R'
union all
select a.xxx, null from a where a.link != 'R'
```
