### ISSUE TITLE
TO_JSON function and CAST TO JSON are not equivalent

### ISSUE THREAD

**Issue by jaceksan** [duckdb/duckdb#10391]
### What happens?

I derived extraction from JSON from how I did it in PostgreSQL.
The same call does not work in DuckDB.
Soon I found out that it works if I CAST the column to JSON.
Moreover, I found out that the TO_JSON function returns JSON data type but enclosers are escaped in the content, so follow-up functions such as JSON_EXTRACT_PATH_TEXT do not extract anything, they return empty value.

### To Reproduce

```
import duckdb
duckdb.sql("""
select 
  '{"accountId": "test"}' as raw,
  '{"accountId": "test"}'::JSON as cast_to_json,
  to_json('{"accountId": "test"}') as to_json,
  json_extract_path_text('{"accountId": "test"}'::JSON, 'accountId') as extract_with_cast,
  json_extract_path_text(to_json('{"accountId": "test"}'), 'accountId') as extract_with_to_json
""").show()
```

Result:

| raw | cast_to_json | to_json | extract_with_cast | extract_with_to_json |
| --- | --- | --- | --- | --- |
| {"accountId": "test"} | {"accountId": "test"} | "{\\"accountId\\": \\"test\\"}" | test | NULL |

### OS:

Ubuntu 22.04

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Jan Soubusta

### Affiliation:

GoodData

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
They're not supposed to be equivalent. `to_json` turns a string into a JSON-string (a JSON object that contains a single string), whereas `::JSON` parses a string representation of a JSON object into a JSON object.
Check
https://duckdb.org/docs/extensions/json.html
-- since `to_json('duck')` has to return a JSON-string (a JSON object that contains the single string `"duck"`, your result for `to_json(<yourstring>)` is the correct result too.

**Comment by soerenwolfers** [comment]
@szarnyasg I think you should close this.

**Comment by jaceksan** [comment]
It's OK that TO_JSON does not work the same as in PostgreSQL.
I just didn't understand how it works from the DOC:
https://duckdb.org/docs/extensions/json.html#json-creation-functions
There is no single line about JSON-string and escaped enclosers.
Would it be worth extending the DOC?

**Comment by jaceksan** [comment]
Btw it's weird to me that both `TO_JSON(column)` and `column::JSON` return the same data type(JSON), but the content behaves differently.

**Comment by soerenwolfers** [comment]
I agree: if this difference is actually desired, it's worth adding some lines to the documentation.
