### ISSUE TITLE
[Python] DirFileSystem injects protocol name into destionation path

### ISSUE THREAD

**Issue by thomafred** [duckdb/duckdb#10404]
### What happens?

When writing data to a parquet-file using an ffspec file system based on `DirFileSystem`, the protocol name is injected into the destination path.

To help illustrate, consider the following example:

```sql
CREATE TABLE foobar (some_int INTEGER, some_str STRING);
INSERT INTO foobar VALUES (1, 'foo'), '(2, 'bar');

COPY foobar to myfs://foobar.parquet (FORMAT 'PARQUET', OVERWRITE_OR_IGNORE true);
```

Here `myfs` is a local filesystem wrapped by a DirFileSystem which sets the path `/path/to/my/dir`. The resulting file should be written to `/path/to/my/dir/foobar.parquet`, but instead ends up in `/path/to/my/dir/:myfs/foobar.parquet`

Could be related to #8177, where I see an issue was fixed was [fixed upstream in fsspec](https://github.com/fsspec/filesystem_spec/pull/1307)

### To Reproduce

Snippet to reproduce:

```python
from duckdb import duckdb
from fsspec import filesystem

fs = filesystem(
    "dir", path="path/to/my/dir", fs=filesystem("file", auto_mkdir=True)
)
fs.protocol = "myfs"

duckdb.register_filesystem(fs)

duckdb.sql("CREATE TABLE foobar (some_int INTEGER, some_str STRING)")
duckdb.sql("INSERT INTO foobar VALUES (1, 'foo'), (2, 'bar')")

print(duckdb.sql("SELECT * FROM foobar").fetchall())

duckdb.sql("COPY foobar TO 'myfs://foobar.parquet' (FORMAT 'PARQUET', OVERWRITE_OR_IGNORE true)")
```

### OS:

Linux Fedora

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Thomas Li Fredriksen

### Affiliation:

HUB Ocean

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by thomafred** [comment]
For anyone having the same issue, creating soft-linking the `myfs:`-directory (or whatever the protocol name is) to its parent directory mitigates the issue:

```sh
cd path/to/my/dir
ln -s . "myfs:"
```

**Comment by szarnyasg** [comment]
Thanks for opening the issue and adding a workaround. We'll look into ti.

**Comment by Mause** [comment]
As you noted, I did already submit a fix for a similar issue upstream. Which fsspec version are you using?

**Comment by thomafred** [comment]
> As you noted, I did already submit a fix for a similar issue upstream. Which fsspec version are you using?

I am using `2023.12.2`.

@Mause I agree. From the diff it seems your PR should fix this.

**Comment by Mause** [comment]
(I'm not able to reproduce this with fsspec 2023.12.2)

**Comment by Mause** [comment]
Beg pardon, I didn't look close enough

**Comment by Mause** [comment]
Okay, having looked a bit closer, DirFsFilesystem.protocol is actually a class field, rather than an instance field

This means you have to override it on the class, either by creating a subclass, or doing something like

```py
type(fs).protocol = 'myfs'
```

This will have the side effect of changing it for every instance of DirFsFilesystem to. If you want to avoid that, you'll need the subclass strategy instead

**Comment by thomafred** [comment]
Ah, my bad.

Thanks for your help, @Mause!

Building on your response - subclassing the `DirFileSystem`-class inline is a convenient way of doing this:

```python
FsCls = type("MyFsCls", (DirFileSystem,), {"protocol": "myfs"})

fs = FsCls(
    path="path/to/my/dir", fs=filesystem("file", auto_mkdir=True)
)
```
