### ISSUE TITLE
Unable to query duckdb file on S3

### ISSUE THREAD

**Issue by NatElkins** [duckdb/duckdb#10409]
### What happens?

When I try to attach to a DuckDB file on S3, I receive the following error:

```
Catalog Error: Cannot open database "s3://bucket/path/to/test.duckdb" in read-only mode: database does not exist
```

Related issue: https://github.com/duckdb/dbt-duckdb/issues/249

Nightly I used: https://github.com/duckdb/duckdb/actions/runs/7648092822/artifacts/1193564377 from https://github.com/duckdb/duckdb/actions/runs/7648092822

### To Reproduce

1. Create a new DuckDB database called `test.duckdb`.
2. Upload into S3 bucket
3. Set vars and install/load extensions:
```
INSTALL httpfs;
LOAD httpfs;

SET s3_region = 'us-east-1';
SET s3_access_key_id = 's3_access_key_id';
SET s3_secret_access_key = 's3_secret_access_key'; 
```
4. Try to attach to database:
```
attach 's3://bucket/path/to/test.duckdb' as test (READ_ONLY)
```

You should receive an error such as:

```
Catalog Error: Cannot open database "s3://bucket/path/to/test.duckdb" in read-only mode: database does not exist
```

### OS:

macOS 14.2.1  M1 aarch64

### DuckDB Version:

DuckDB v0.9.3-dev3121

### DuckDB Client:

Nightly JDBC, used via DBeaver

### Full Name:

Nat Elkins

### Affiliation:

Knoetic

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] Yes, I have

**Comment by NatElkins** [comment]
Seems like this test should've caught this? https://github.com/duckdb/duckdb/blob/main/test/sql/attach/attach_httpfs.test

Is there a way to easily run this one test locally?

Also, I was trying to hunt through the nightly test run to see the result of this test, but didn't see it.  Is this test not run regularly, or is there some other place I should be looking?

https://github.com/duckdb/duckdb/actions/runs/7734313938/job/21088398577

Also, any pointers on how I can begin investigating this would be greatly appreciated!  Thank you!

**Comment by carlopi** [comment]
Can you try to reproduce the following:
```
carlo@ScroogeMcDuck duckdb % ./build/release/duckdb
v0.9.3-dev3586 25e1745715
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 's3://duckdb-blobs/data/my.db' as test (READ_ONLY);
D USE test;
D FROM t;
┌────────┐
│   x    │
│ int32  │
├────────┤
│ 0 rows │
└────────┘
```
`s3://duckdb-blobs/data/my.db` is a publicly accessible database file on s3, file has been uploaded via CLI.

Can you test if you can read / list other files in that bucket?
There might be some corner case related to authentication, but READ_ONLY should work.

**Comment by NatElkins** [comment]
@carlopi I pulled main and ran the following:

<img width="826" alt="image" src="https://github.com/duckdb/duckdb/assets/1795462/01e33577-9b70-4f98-b0da-b06320f5cd86">

Same error.

**Comment by NatElkins** [comment]
I'm able to download it using S3:

```
➜  release git:(main) aws s3 cp s3://duckdb-blobs/data/my.db ./my.db
download: s3://duckdb-blobs/data/my.db to ./my.db
➜  release git:(main) ./duckdb
v0.9.3-dev3585 f0ab7a4f64
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH './my.db' as test (READ_ONLY);
D USE test;
D FROM t;
┌────────┐
│   x    │
│ int32  │
├────────┤
│ 0 rows │
└────────┘
D
```

**Comment by carlopi** [comment]
I think I have it, you need to explicitly INSTALL / LOAD the httpfs extension.

```
carlo@ScroogeMcDuck duckdb % duckdb-latest
v0.9.3-dev3597 64785543f8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 's3://duckdb-blobs/data/my.db' as test (READ_ONLY);
Error: Catalog Error: Cannot open database "s3://duckdb-blobs/data/my.db" in read-only mode: database does not exist
D FROM duckdb_extensions();
... shows httpfs is not loaded
D INSTALL httpfs;
D LOAD httpfs;
D ATTACH 's3://duckdb-blobs/data/my.db' as test (READ_ONLY);
D 
```

Can you reproduce?

**Comment by NatElkins** [comment]
Hi @carlopi, I don't believe this is resolved.  I followed these steps:

1. Checked out `64785543f8`, the same commit that you were using, and built duckdb.
2. Installed and loaded the `httpfs` and `iceberg` extensions.
3. Tried selecting an iceberg table in S3, just to show that it didn't work initially.
4. Set my S3 cred info.
5. Ran the same query against the iceberg table, showing that it is a success.
6. Tried attaching to a duckdb file in that same bucket --> Failed.
7. Tried attaching to the duckdb file that you specified --> Success.

See my logs below:

```
➜  release git:(64785543f8) ./duckdb
v0.9.3-dev3597 64785543f8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D INSTALL httpfs;
D LOAD httpfs;
D INSTALL iceberg;
D LOAD iceberg;
D SELECT count(*) FROM iceberg_scan('s3://knoetic-airbyte-sync-iceberg-experiment/prod/default/airbyte_raw_applications', allow_moved_paths = true);
Error: HTTP Error: HTTP GET error on 'https://knoetic-airbyte-sync-iceberg-experiment.s3.amazonaws.com/prod/default/airbyte_raw_applications/metadata/version-hint.text' (HTTP 403)
D SET s3_region = 'us-east-1';
D SET s3_access_key_id = 'removed';
D SET s3_secret_access_key = 'removed';
D SELECT count(*) FROM iceberg_scan('s3://knoetic-airbyte-sync-iceberg-experiment/prod/default/airbyte_raw_applications', allow_moved_paths = true);
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        28272 │
└──────────────┘
D ATTACH 's3://knoetic-airbyte-sync-iceberg-experiment/test/test.db' as asdf (READ_ONLY);
Error: Catalog Error: Cannot open database "s3://knoetic-airbyte-sync-iceberg-experiment/test/test.db" in read-only mode: database does not exist
D ATTACH 's3://duckdb-blobs/data/my.db' as test (READ_ONLY);
D
```

Are you able to attach to a duckdb file that isn't in a public bucket?

**Comment by NatElkins** [comment]
I've also confirmed that if I move `test.db` to a public bucket, I'm able to attach to it.

**Comment by JRocki** [comment]
Commenting so I am on future notifications - also running into this issue.

**Comment by DataroDave** [comment]
I am also running into this issue with 0.10.3

This works:

```import duckdb

duckdb.sql("install httpfs")
duckdb.sql("load httpfs")
duckdb.sql("attach 's3://duckdb-blobs/data/my.db' as test (READ_ONLY)")
duckdb.sql("use test")
duckdb.sql("from t")```

But even after `load_aws_credentials()` we cannot attach a database from a private bucket, even through I can read a parquet file from the same location.

**Comment by AmanSinghAS** [comment]
Also commenting so I am on future notifications

**Comment by rmenzie** [comment]
commenting for notification

**Comment by josejo9423** [comment]
following

**Comment by DataroDave** [comment]
My test case still not working in 1.0.0

**Comment by jdbarillas** [comment]
Also running into this issue with private buckets

**Comment by djiangc** [comment]
+1, I have experience the same issue with 1.0.0

**Comment by samansmink** [comment]
Okay I can indeed reproduce this issue, the workaround for me is to switch from the `load_aws_credentials()` to the [recommended](https://duckdb.org/docs/extensions/httpfs/s3api#config-provider) way of using secrets. 

So for example:

```SQL
CREATE SECRET (TYPE s3, provider credential_chain);
attach 's3://test-bucket-ceiveran/test_attach_issue/test.db' as test (readonly);
```

I see the `aws` extension docs are outdated and still advocate using the `load_aws_credentials()` function

**Comment by JRocki** [comment]
@samansmink Thanks for the update. I upgrading to 1.0.0 and tried your solution, but I am getting the following:

**Comment by JRocki** [comment]
Adding a follow-up. While this solution did work for me locally, it does not seem to work in my deployed state. I am deploying this to AWS EKS and using a k8s service account for my AWS credentialing. This results in a `duckdb.duckdb.HTTPException: HTTP Error: HTTP GET error on .... (HTTP 400)`. I have confirmed that in the same deployment, I can pull the parquet file using `boto3`, so I believe the credentialing is valid. Also, this might be off-topic now and happy to post in a new thread.

**Comment by leestorm4520** [comment]
I got into this problem also. I can query files (parquet, csv, json, excel) from S3 but not sqlite or duckdb. I am not sure if the way they set up the secret for ATTACH and read_parquet()/read_json_auto() is different or not

**Comment by DataroDave** [comment]
I just tried with Eatoni (1.1.0) and I'm still unable to attach databases from S3:

![image](https://github.com/user-attachments/assets/e726ab8b-addc-4ac3-9608-102cd34173f7)

`read_parquet` from the same private bucket using that same script works.

I think there is some confusion in the thread for the issue. I'm quite sure that the original problem is related to `attach` and that `read_*` issues are not related.

**Comment by carlopi** [comment]
@DataroDave: can you give it a try using the syntax:
```
INSTALL httpfs; 
LOAD httpfs;
CREATE SECRET secret1 (
        TYPE S3,
        ENDPOINT '***',
        KEY_ID '****',
        SECRET '****',
        REGION '****'
);
```
Wrapping that to Python, and using the relevant credentials?

I believe the problem is that `load_aws_credentials` is now deprecated, see https://duckdb.org/docs/extensions/aws#legacy-features for more details

**Comment by DataroDave** [comment]
Thanks @carlopi 

OK so huge win, I can get it to work, although like this:

![image](https://github.com/user-attachments/assets/0c7c1858-504c-436d-bab2-531afb65a81f)

Explicitly creating the secret like your example doesn't work for me and it also stops `read_*` working correctly.

Possibly confounding the issue is that we are using AWS SSO, maybe this is having side effects somewhere.

**Comment by seanbirchall** [comment]
Any solution if a private file is being shared from a presigned URL? I'm using cloudfare R2 and getting Catalog Error: Cannot open database "presigned url to database" in read-only mode: database does not exist. When trying to attach a presigned URL to duckdb wasm.

Probably related to this issue.

**Comment by ketozhang** [comment]
Getting all the same issues with `IMPORT database`

```sql
D DROP PERSISTENT SECRET AWS; CREATE PERSISTENT SECRET aws (
      TYPE S3,
      PROVIDER CREDENTIAL_CHAIN);
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D import database 's3://bucket/path/to/redacted';
HTTP Error: HTTP GET error on 'https://bucket/path/to/redacted/schema.sql' (HTTP 400)
```

**Comment by carlopi** [comment]
@seanbirchall: can you possibly open an issue in duckdb/duckdb-wasm? Thanks

@ketozhang: can you open a separate issue here? Thanks

I think this is solved, but if issue persist please re-open a separate issue, ideally with a reproducer.

Note that the docs on AWS extension in particular have been updated, please check: https://duckdb.org/docs/extensions/aws

**Comment by seanbirchall** [comment]
@carlopi I believe this issue covers what I'm running into https://github.com/duckdb/duckdb-wasm/issues/1852. Also looks like this PR might fix the issue https://github.com/duckdb/duckdb-wasm/pull/1856. Though I did test out a demo app by the creator of this PR that should allow for querying presigned URLs, but was not able to locally https://github.com/e1arikawa/duckdb-wasm-samples. So hopefully I was just doing something wrong and adding opfs will fix my problem on duckdb-wasm.

**Comment by akshayah3** [comment]
```
conn = duckdb.connect()
conn.execute("install httpfs")
conn.execute("load httpfs")
conn.execute(
    f"""CREATE SECRET secret1 (
    TYPE S3,
    ENDPOINT '{ENDPOINT}',
    KEY_ID '{AWS_ACCESS_KEY_ID}',
    SECRET '{AWS_SECRET_ACCESS_KEY}',
    REGION '{AWS_REGION}'
);"""
)

s3_fs = s3fs.S3FileSystem()
if s3_fs.exists(s3_path):
    # Attach the S3 DuckDB database
    conn.execute(f"ATTACH '{s3_path}' AS {table_name}")
```

This gives me the **Cannot open database "s3://xyz/" in read-only mode: database does not exist**. Please let me know where I am going wrong

**Comment by mike-luabase** [comment]
@akshayah3 the path needs to be to a `.duckdb` file. What does your `s3_path` look like?

**Comment by akshayah3** [comment]
@mike-luabase I initally was trying with .db file but later switched to a .duckdb file with no luck. My path looks something like this `s3://test-schedule/routes/routes.duckdb`
