### ISSUE TITLE
Anti-join on bigint when right table is empty returns wrong result

### ISSUE THREAD

**Issue by k-abram** [duckdb/duckdb#10406]
### What happens?

Anti join when the right table is empty should return the left table. This works for tables where the join column is a varchar but not for bigint (possibly other data types too). 

### To Reproduce

Create some tables and load some data into them:
```sql
create table test_str(k varchar);
create table test_str_del(pk varchar);
create table test_int(k bigint);
create table test_int_del(pk bigint);
insert into test_str values('abc'), ('def');
insert into test_int values(1), (2);
```

Anti join of `test_str` with `test_str_del` gives the correct result:
```sql
select l.* from test_str l anti join test_str_del r on l.k = r.pk;
```
```
┌─────────┐
│    k    │
│ varchar │
├─────────┤
│ abc     │
│ def     │
└─────────┘
```
Anti join of `test_int` with `test_int_del` gives 0 rows (wrong result):
```sql
select l.* from test_int l anti join test_int_del r on l.k = r.pk;
```
```
┌────────┐
│   k    │
│ int64  │
├────────┤
│ 0 rows │
└────────┘
```

### OS:

MacOS

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

K Abram

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@k-abram thanks for reporting this and producing a small reproducible example, we'll look into it.
