### ISSUE TITLE
COLLATE NOCASE not working for LIKE operator

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#10416]
### What happens?

The COLLATE clause does not seem to affect the behavior of the LIKE comparison operator. 
It was expected that the COLLATE clause would affect the behavior of the LIKE comparison in a similar way as it affects the equals operator.

### To Reproduce

1) run `SELECT 'hello' COLLATE NOCASE LIKE 'hElLO';`
2) observe that the result is `false`

Compare with `SELECT 'hello' COLLATE NOCASE = 'hElLO';`, which results in `true` - it was expected that the LIKE comparison would also return `true`

### OS:

Windows 10 Pro

### DuckDB Version:

v0.9.2

### DuckDB Client:

CLI

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks for the report, this is a known issue - see also #604

**Comment by rpbouman** [comment]
Apologies for the duplicate report - I didn't realize it was known. Thanks for picking it up!
