### ISSUE TITLE
SELECT table alias cannot be defined the same as a view's WITH table alias

### ISSUE THREAD

**Issue by dmonder** [duckdb/duckdb#10428]
### What happens?

I created a view that utilized a WITH statement with the name `r` (see below for the code to reproduce). In a subsequent SELECT using the view, I gave the view an alias of `r` and receive `Catalog Error: Table with name r does not exist!` If I do not use the alias in the select statement, the query returns all the values in the view as appropriate.

### To Reproduce

```
INSTALL httpfs;
LOAD httpfs;
CREATE TABLE trek_facts AS
    SELECT *
    FROM 'https://raw.githubusercontent.com/Alex-Monahan/example_datasets/main/Star_Trek-Season_1.csv'
    ;

CREATE VIEW recent_treks AS
    WITH r AS (
        SELECT *
          FROM trek_facts
         WHERE aired_date == (DATE '1967-01-05')
    )
    SELECT r.*
      FROM r
    ;

SELECT episode_num
  FROM recent_treks
;
-- ┌─────────────┐
-- │ episode_num │
-- │    int64    │
-- ├─────────────┤
-- │          16 │
-- └─────────────┘

SELECT r.episode_num
  FROM recent_treks r
;
-- Error: Catalog Error: Table with name r does not exist!
-- Did you mean "pg_am"?
```

### OS:

Windows 11

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI, Python, harlequin, DBeaver

### Full Name:

David Onder

### Affiliation:

Haywood Community College

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by dmonder** [comment]
This issue was fixed in v1, just don't know when it was fixed.

**Comment by Mytherin** [comment]
Thanks for reporting! As mentioned this has since been fixed - most likely as part of fixing binding issues with CTEs.
