### ISSUE TITLE
0.9.2 installation error on Fedora 39 with Python 3.12.1

### ISSUE THREAD

**Issue by schu** [duckdb/duckdb#10427]
### What happens?

The installation of duckdb 0.9.2 on Fedora 39 with Python 3.12.1 doesn't seem to work (same error as previously discussed in issue #9563) - did I miss something or is the installation not working on Fedora systems?

```
pip install duck==0.9.2
[...]
src/numpy/numpy_scan.cpp:402:69: error: ‘PyUnicode_WCHAR_KIND’ was not declared in this scope; did you mean ‘PyUnicode_4BYTE_KIND’?
[...]
error: command '/usr/bin/gcc' failed with exit code 1
[...]
```

I'm using

```
pip 23.2.1
Python 3.12.1
gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)
Fedora 39
```

### To Reproduce

python3 -m venv /tmp/venv
source /tmp/venv/bin/activate
pip install duckdb==0.9.2

### OS:

Fedora Linux 39 x86_64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Michael Schubert

### Affiliation:

none

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
DuckDB 0.9.2 does not support Python 3.12, please try with a nightly build

**Comment by schu** [comment]
> DuckDB 0.9.2 does not support Python 3.12

Ah, I misunderstood the closing comment in #9563 then. Thanks!
