### ISSUE TITLE
Conflict with the name of folder and column when reading parquet files

### ISSUE THREAD

**Issue by viviakemik** [duckdb/duckdb#10431]
### What happens?

I am using duckdb_jdbc v0.9.2 and I store a parquet file in the folder with the name DATA=2023-08-28 and this file has a column with the same name as the folder DATA. But this column is a timestamp column and has values like 2023-08-28 07:04:58.013. When I use read_parquet file the resultset returns DATA=2023-08-28 instead of 2023-08-28 07:04:58.013. Is it expected?

### To Reproduce

1- Create a folder with the name DATA=2023-08-28 in S3
2- Upload a parquet file with column DATA, but it can store hours like 2023-08-28 07:04:58.013
3- Use SELECT * FROM  read_parquet(.../DATA=2023-08-28/*.parquet) and print the column DATA in the resultset. It will show 2023-08-28 instead of 2023-08-28 07:04:58.013hours

### OS:

Windows

### DuckDB Version:

0.9.2

### DuckDB Client:

Java

### Full Name:

Viviani Kasahara

### Affiliation:

Autbank

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @viviakemik, thanks for opening this report. Please note that we can only answer questions and tackle issues, which are accompanied with a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). In this case, we need the Parquet file (or a script that produces it) as well as the Java source file that runs the instructions. Could you please provide these, so we can investigate the issue?

**Comment by viviakemik** [comment]
[ParquetDuckDB.zip](https://github.com/duckdb/duckdb/files/14138941/ParquetDuckDB.zip)

Hi! 
Attached are the files to simulate reading the file (can be tested locally, it does not need to be on S3). 
Thanks!

**Comment by cmdlineluser** [comment]
This is Python, but I think this is the issue being asked about - perhaps @viviakemik can confirm.

The *"hive name"* is added as a column, meaning if there is an existing column of the same name, it is being "clobbered" / overwritten.

```python
import duckdb
import tempfile
from   pathlib  import Path

subdir = "DATA=2023-08-08"

with tempfile.TemporaryDirectory() as d:
    tmpdir = Path(d)
    (tmpdir / subdir).mkdir()
    filename = (tmpdir / subdir) / "filename.parquet"
    
    duckdb.sql(f"""
    copy (select '2023-08-28 07:04:58.013'::timestamp as MY_COL) to '{filename}'
    """)
    
    print("MY_COL")
    print(duckdb.sql(f"from read_parquet('{tmpdir}/*/*.parquet')"))

    # MY_COL
    # ┌─────────────────────────┬────────────┐
    # │         MY_COL          │    DATA    │
    # │        timestamp        │    date    │
    # ├─────────────────────────┼────────────┤
    # │ 2023-08-28 07:04:58.013 │ 2023-08-08 │
    # └─────────────────────────┴────────────┘

    duckdb.sql(f"""
    copy (select '2023-08-28 07:04:58.013'::timestamp as DATA) to '{filename}'
    """)
    
    print("DATA")
    print(duckdb.sql(f"from '{tmpdir}/*/*.parquet'"))

    # DATA
    # ┌────────────┐
    # │    DATA    │ # <- ERROR: ORIGINAL COLUMN OVERWRITTEN
    # │    date    │
    # ├────────────┤
    # │ 2023-08-08 │
    # └────────────┘

    print("DATA HIVE_PARTITIONING=false")
    print(duckdb.sql(f"from read_parquet('{tmpdir}/*/*.parquet', hive_partitioning=false)"))

    # DATA HIVE_PARTITIONING=false
    # ┌─────────────────────────┐
    # │          DATA           │
    # │        timestamp        │
    # ├─────────────────────────┤
    # │ 2023-08-28 07:04:58.013 │
    # └─────────────────────────┘
```

From what I can tell, `hive_partitioning=false` is how to prevent the column inclusion?

**Comment by viviakemik** [comment]
Hi, @cmdlineluser !

Yes, with `hive_partitioning=false` it prevents the column overwriting.

Thanks!
