### ISSUE TITLE
Julia client segfaults on more than one query

### ISSUE THREAD

**Issue by suvayu** [duckdb/duckdb#10456]
### What happens?

The Julia client segfaults when running more than one query.

I know that the Julia client isn't officially supported, but if someone could guide me a bit, I could debug this, and try to fix it myself.  Thanks for taking interest in the issue.

### To Reproduce

```julia
julia> import DuckDB as dd

julia> using DataFrames

julia> conn = dd.DBInterface.connect(dd.DB)
DuckDB.DB(":memory:")

julia> res1 = dd.execute(conn, "SELECT * FROM range(100)")
(range = Union{Missing, Int64}[0, 1, 2, 3, 4, 5, 6, 7, 8, 9  …  90, 91, 92, 93, 94, 95, 96, 97, 98, 99],)

julia> res2 = dd.execute(conn, "SELECT * FROM range(10)")

[370735] signal (11.1): Segmentation fault
in expression starting at REPL[9]:1
duckdb_execute_pending at /home/user/.julia/artifacts/66fc38b368f0801d407519dea3c5cc3dfd619e8c/lib/libduckdb.so (unknown line)
duckdb_pending_execution_is_finished at /home/user/.julia/packages/DuckDB/HzSSp/src/api.jl:1362 [inlined]
pending_execute_tasks at /home/user/.julia/packages/DuckDB/HzSSp/src/result.jl:641
execute_singlethreaded at /home/user/.julia/packages/DuckDB/HzSSp/src/result.jl:690
execute at /home/user/.julia/packages/DuckDB/HzSSp/src/result.jl:729
execute at /home/user/.julia/packages/DuckDB/HzSSp/src/result.jl:755
#execute#6 at /home/user/.julia/packages/DuckDB/HzSSp/src/result.jl:763 [inlined]
execute at /home/user/.julia/packages/DuckDB/HzSSp/src/result.jl:763
unknown function (ip: 0x7f733952ca8a)
unknown function (ip: 0x7f739e06539b)
unknown function (ip: 0x7f739e064b51)
unknown function (ip: 0x7f739e065c9a)
unknown function (ip: 0x7f739e066bb8)
unknown function (ip: 0x7f739e082730)
unknown function (ip: 0x7f739e083139)
unknown function (ip: 0x7f739e083139)
unknown function (ip: 0x7f739e083139)
ijl_toplevel_eval_in at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7f737cb96e2b)
unknown function (ip: 0x7f737cb98e89)
unknown function (ip: 0x7f737c331937)
unknown function (ip: 0x7f737c331cf6)
unknown function (ip: 0x7f737c2222fa)
unknown function (ip: 0x7f737c222a2f)
unknown function (ip: 0x7f737c222a6f)
unknown function (ip: 0x7f737c207d87)
unknown function (ip: 0x7f737c207ddb)
jl_f__call_latest at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7f737cf5857d)
unknown function (ip: 0x7f737cf60d58)
unknown function (ip: 0x7f737c987cff)
unknown function (ip: 0x7f737c987e08)
unknown function (ip: 0x7f739e0afcb7)
jl_repl_entrypoint at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
main at julia (unknown line)
__libc_start_call_main at /usr/bin/../lib64/libc.so.6 (unknown line)
__libc_start_main at /usr/bin/../lib64/libc.so.6 (unknown line)
_start at julia (unknown line)
Allocations: 13553515 (Pool: 13543002; Big: 10513); GC: 20
Segmentation fault (core dumped)
```

### OS:

Linux 6.6.13-200.fc39.x86_64

### DuckDB Version:

DuckDB v0.9.1 (installed using Julia package manager)

### DuckDB Client:

Julia

### Full Name:

Suvayu

### Affiliation:

NL eScience Center

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for reporting this. Please note that Julia is currently not officially supported as part of our [community support policy](https://duckdblabs.com/news/2023/10/02/support-policy#extensions-and-apis).

**Comment by suvayu** [comment]
@szarnyasg as I mentioned in the original report, I realise that Julia isn't completely supported. But I'm also willing and capable to debug and possibly fix things myself if someone can guide me a bit.

Since this is a segfault, I'm guessing I'ld need to look at the C++ layer. So pointers to how to attach a debugger, or which functions to look at in the source (C++/Julia) would help greatly.

**Comment by szarnyasg** [comment]
Hi @suvayu, apologies, I didn't read the full post before replying. I'll discuss this issue with the team tomorrow.

**Comment by suvayu** [comment]
Thanks a lot!  I compiled the main branch from source, and tried out my minimal example, as well as my actual use case, both work as expected!  You may consider this as resolved :)
