### ISSUE TITLE
the error message should be `cannot use keyword "user" here` when use one of the keywords as a column alias 

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#10454]
### What happens?

when use one of the keywords as a column alias, it failed.
but the error message could be better if points out that is a keyword
D select 1 user;
Error: Parser Error: syntax error at or near "user"
LINE 1: select 1 user;
                 ^
D select 1 name;
Error: Parser Error: syntax error at or near "name"
LINE 1: select 1 name;
                 ^
 
D from duckdb_keywords() where keyword_name like 'u%';
┌──────────────┬──────────────────┐
│ keyword_name │ keyword_category │
│   varchar    │     varchar      │
├──────────────┼──────────────────┤
│ unbounded    │ unreserved       │
│ uncommitted  │ unreserved       │
│ unencrypted  │ unreserved       │
│ union        │ reserved         │
│ unique       │ reserved         │
│ unknown      │ unreserved       │
│ unlisten     │ unreserved       │
│ unlogged     │ unreserved       │
│ unpivot      │ reserved         │
│ until        │ unreserved       │
│ update       │ unreserved       │
│ use          │ unreserved       │
│ user         │ unreserved       │
│ using        │ reserved         │
├──────────────┴──────────────────┤
│ 14 rows               2 columns │
└─────────────────────────────────┘

### To Reproduce

select 1 user;
Error: Parser Error: syntax error at or near "user"

### OS:

windows7

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @l1t1,

Two things:

1) Please read the instructions by the @duckdblabs-bot in the previous comment and apply them to your post.

2) Can you please provide an explanation on what your use case for DuckDB is? Your recent issues present corner cases that are extremely rare and have little to no practical impact DuckDB's users. For example, using more than a few `UNION ALL` clauses is very rare as there are many other ways to insert multiple rows into database, which renders #10452 irrelevant. Is your goal to find bugs in DuckDB a part of an assignment (e.g., a thesis work)?

Thanks,
Gabor
Developer relations @ DuckDB

**Comment by Mytherin** [comment]
Thanks for the report! This is not a bug as `user` is a keyword. Better error messages in the parser would be great but that would require a parser rewrite/move away from yacc/bison which is not happening in the short to medium term.
