### ISSUE TITLE
Is it the aberrant behavior of correlated subqueries？

### ISSUE THREAD

**Issue by qianchanger** [duckdb/duckdb#10463]
### What happens?
```
SELECT c.*
FROM   t1 c
WHERE  c.v1 = (SELECT bc.v1
               FROM   t2 bc
               WHERE  c.v2 = bc.v2
               ORDER  BY bc.v3
               LIMIT  2); 
```
When I execute this correlated subquery, for each row of the main query, if more than one row is found in the subquery, other databases such as MySQL、PostgreSQL、Oracle will throw an error, whereas DuckDB does not. I am wondering if this is considered reasonable behavior？

MySQL:
<img width="427" alt="image" src="https://github.com/duckdb/duckdb/assets/19400870/e48e987f-4b4f-482e-be16-4fb22f004c38">

DuckDB:
<img width="354" alt="image" src="https://github.com/duckdb/duckdb/assets/19400870/4fa8aa1f-006c-40ec-995a-ee86bf8a0759">

### To Reproduce

```
create table t1(v1 int, v2 int);
create table t2(v1 int, v2 int, v3 int);

insert into t1 values(1,1);
insert into t2 values(1,1,1);
insert into t2 values(1,1,3);
SELECT c.*
FROM   t1 c
WHERE  c.v1 =(SELECT bc.v1
               FROM   t2 bc
               WHERE  c.v2 = bc.v2
               ORDER  BY bc.v3
               LIMIT  2); 
```
### OS:

macos

### DuckDB Version:

v0.9.2

### DuckDB Client:

mac, brew install duckdb

### Full Name:

Allen

### Affiliation:

Student

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! This is currently intended behavior - see also https://github.com/duckdb/duckdb/issues/4113#issuecomment-1183057908
