### ISSUE TITLE
Casting structs with fields of the same name, but in a different order fails with `Mismatch Type Error`

### ISSUE THREAD

**Issue by plaflamme** [duckdb/duckdb#10486]
### What happens?

Casting structs with fields of the same name, but in a different order fails with `duckdb.duckdb.TypeMismatchException: Mismatch Type Error`.

[The documentation](https://duckdb.org/docs/sql/data_types/struct.html) about casting structs only mention that field names have to match:

> When casting structs, the names of fields have to match

If the requirement is that the fields have to be in the same order, then perhaps it could be made more explicit in the documentation.

### To Reproduce

```sql
CREATE TABLE t1 (s STRUCT(a STRING, b INT));
INSERT INTO t1 SELECT {'b': 42, 'a': 'foo'};
```

```
duckdb.duckdb.TypeMismatchException: Mismatch Type Error: Type STRUCT(b INTEGER, a VARCHAR) does not match with STRUCT(a VARCHAR, b INTEGER). Cannot cast STRUCTs with different names
```

### OS:

aarch64

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

Philippe Laflamme

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! I've implemented the casting in #10537 so this should work as expected now
