### ISSUE TITLE
Julia Duck DB Errors when Creating Table

### ISSUE THREAD

**Issue by jjAtNxtPt** [duckdb/duckdb#10497]
### What happens?

I installed DuckDB and Julia 1.10 and added the DuckDB package.  I tried following the steps in the documentation at [https://duckdb.org/docs/archive/0.9.1/api/julia](https://duckdb.org/docs/archive/0.9.1/api/julia) , but when I submitted the create table statement in the REPL I get the error in the following snippet:

`(@v1.10) pkg> status DuckDB
Status `C:\Users\james.johnson\.julia\environments\v1.10\Project.toml`
  [d2f5444f] DuckDB v0.9.1

julia> using DuckDB

julia> con = DBInterface.connect(DuckDB.DB, ":memory:")
DuckDB.DB(":memory:")

julia> DBInterface.execute(con, "CREATE TABLE integers(i INTEGER)")

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64c92738 -- duckdb_execute_pending at C:\Users\james.johnson\.julia\artifacts\306ea973f74bf26fd30dc460b1dc38159a29d67b\bin\libduckdb.dll (unknown line)
in expression starting at REPL[6]:1
duckdb_execute_pending at C:\Users\james.johnson\.julia\artifacts\306ea973f74bf26fd30dc460b1dc38159a29d67b\bin\libduckdb.dll (unknown line)
duckdb_pending_execution_is_finished at C:\Users\james.johnson\.julia\packages\DuckDB\HzSSp\src\api.jl:1362 [inlined]
pending_execute_tasks at C:\Users\james.johnson\.julia\packages\DuckDB\HzSSp\src\result.jl:641
execute_singlethreaded at C:\Users\james.johnson\.julia\packages\DuckDB\HzSSp\src\result.jl:690
execute at C:\Users\james.johnson\.julia\packages\DuckDB\HzSSp\src\result.jl:729
execute at C:\Users\james.johnson\.julia\packages\DuckDB\HzSSp\src\result.jl:830 [inlined]
execute at C:\Users\james.johnson\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:130 [inlined]
#execute#2 at C:\Users\james.johnson\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:152 [inlined]
execute at C:\Users\james.johnson\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:152
unknown function (ip: 0000023c2b43005f)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:223
eval_stmt_value at C:/workdir/src\interpreter.c:174 [inlined]
eval_body at C:/workdir/src\interpreter.c:635
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:775
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:934
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:877
ijl_toplevel_eval at C:/workdir/src\toplevel.c:943 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:985
eval at .\boot.jl:385 [inlined]
eval_user_input at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:150
repl_backend_loop at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:246
#start_repl_backend#46 at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:231
start_repl_backend at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:228
#run_repl#59 at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:389
run_repl at C:\workdir\usr\share\julia\stdlib\v1.10\REPL\src\REPL.jl:375
jfptr_run_repl_95895.1 at C:\Users\james.johnson\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\lib\julia\sys.dll (unknown line)
#1013 at .\client.jl:432
jfptr_YY.1013_86694.1 at C:\Users\james.johnson\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:812
#invokelatest#2 at .\essentials.jl:887 [inlined]
invokelatest at .\essentials.jl:884 [inlined]
run_main_repl at .\client.jl:416
exec_options at .\client.jl:333
_start at .\client.jl:552
jfptr__start_86719.1 at C:\Users\james.johnson\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1982 [inlined]
true_main at C:/workdir/src\jlapi.c:582
jl_repl_entrypoint at C:/workdir/src\jlapi.c:731
mainCRTStartup at C:/workdir/cli\loader_exe.c:58
BaseThreadInitThunk at C:\windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 2885530 (Pool: 2882928; Big: 2602); GC: 5
`

### To Reproduce

Windows 10
Install Julia 1.10
  - open REPL
  - type "]" 
  - submit command:  add DuckDB
Install DuckDB 0.9.2
Add Environment Variable if needed
Go back to Julia REPL
submit commands:
  - using DuckDB
  - DBInterface.execute(con, "CREATE TABLE integers(i INTEGER)")
  - 

### OS:

Windows 10

### DuckDB Version:

v0.9.2

### DuckDB Client:

Julia DuckDB v0.9.1

### Full Name:

James Johnson

### Affiliation:

Liberty Tax

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by jjAtNxtPt** [comment]
Thanks for the response.  I took a look at that post but I'm not able to debug any of the source myself.  I did, however, re-download and test against the 0.9.2 duckdb bug fix release, which I already had, and ensured that the Julia client is the 0.9.1 version specified in the bug fix.  The same thing happened.

**Comment by Mytherin** [comment]
As mentioned there the released version of DuckDB currently does not work with Julia 1.10. This has been fixed in the development branch and will be fixed with the next DuckDB release.

**Comment by mzy2240** [comment]
Can we bump the DuckDB version in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil)? Thanks!
