### ISSUE TITLE
Unclear error message when using describe (wrongly).

### ISSUE THREAD

**Issue by arjenpdevries** [duckdb/duckdb#10506]
### What happens?

```sql
describe fts_main_ciff_metadata.terms.terms;
```
```text
Error: Binder Error: Catalog "fts_main_ciff_metadata" does not exist!
```
```sql
describe fts_main_ciff_metadata.terms;
```
```text
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ docid       │ BIGINT      │ YES     │         │         │         │
│ fieldid     │ BIGINT      │ YES     │         │         │         │
│ termid      │ BIGINT      │ YES     │         │         │         │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

### To Reproduce

Create a table, and issue `DESCRIBE main.tablename.tablename;`

Of course, this was a copy paste error on my side, but the error message reports that `Catalog "main" does not exist!` which is confusing. I'd say low priority.

### OS:

fc38.x86_64

### DuckDB Version:

v0.9.3-dev3269 8de2d291d8

### DuckDB Client:

CLI

### Full Name:

Arjen P. de Vries

### Affiliation:

Radboud University

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
Because of the multiple dots it interprets `fts_main_ciff_metadata` as catalog instead of a schema name. Expected behaviour, hard to give a better error message here.
