### ISSUE TITLE
Out of Memory Error when using appender in Java

### ISSUE THREAD

**Issue by viviakemik** [duckdb/duckdb#10515]
### What happens?

I'm using appender to insert 2 million rows (there is a varchar(max) column) that comes from SQL Server to DuckDB. I set the temp_directory and max_memory = 8G. The number of threads is at the default (= number of cores = 8). When using 8G it writes locally (I saw that it created duckdb_temp_storage-X.tmp). But the error occurs: **java.util.concurrent.ExecutionException: java.sql.SQLException: Out of Memory Error: failed to allocate data of size 536.8MB (8.1GB/8.0GB used)**.

Is there any way to prevent this error? Or do I really need to increase the amount of memory?

### To Reproduce

Using the method below generates the OutOfMemory error when the resultSet is too large (even when I try to flush it manually)

```
public static int insertDuckDBViaAppender(DuckDBConnection con, ResultSet resultSet, ResultSetMetaData rsmd, ToolOptions options, int columnCount) throws SQLException {
		int countRows = 0;
		DuckDBAppender duckDbAppender = null;
		try{
			duckDbAppender = con.createAppender("main", options.getSinkNameDirOrTable());
			while (resultSet.next()) {
				countRows+=1;
				duckDbAppender.beginRow();
				for (int i = 1; i <= columnCount; i++) {
					duckDbAppender.append(resultSet.getString(i));
				}
				duckDbAppender.endRow();
				//try to flush to avoid out of memory
			    /*if (countRows % options.getFetchSize() == 0) {
	                duckDbAppender.flush();
	            }*/
			}
			//duckDbAppender.flush();
		}finally {
			if (duckDbAppender != null) duckDbAppender.close();
		}
		return countRows;
	}
```

### OS:

Windows

### DuckDB Version:

0.9.2

### DuckDB Client:

Java

### Full Name:

Viviani Kasahara

### Affiliation:

Autbank

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
We need some more context here, as it stands the issue is not reproducible. For example, is the DuckDB database in memory or not? A reproducible stand alone example (e.g. full java program) would help.

**Comment by viviakemik** [comment]
Hi! I am using  DuckDB database in memory. Attached is the code to simulate the error.
In my tests, when I reduce the number of threads, the OutOfMemory error stops occurring. But I don't understand how I should do it to guarantee that OutOfMemory won't occur. Is there any way to calculate the number of threads based not only on the number of CPU cores but on the amount of memory available?

Thanks!
[TestWriteParquet.zip](https://github.com/duckdb/duckdb/files/14269992/TestWriteParquet.zip)
