### ISSUE TITLE
How estimated cardinality (EC) is calculated when explain analyze a query?

### ISSUE THREAD

**Issue by qzbqzb** [duckdb/duckdb#10523]
### What happens?

Hello!  I am testing the performance of read_parquet function , The number of data records is 143997065，Size of parquet files is about 29GB, every file  has 144 columns. But in my three cases, I got different results，the difference is significant。

### To Reproduce

**Case 1:**
29GB is a big parquet file,here is the profiling：
![image](https://github.com/duckdb/duckdb/assets/39759821/ec111bf1-02b0-4c34-853d-06eb650fd8f1)
![image](https://github.com/duckdb/duckdb/assets/39759821/516ea50a-f494-4ef5-8047-ebb30c18133c)

**Case 2:**
29GB parquet files are divided into 12 files，here is the profiling:
![image](https://github.com/duckdb/duckdb/assets/39759821/28084a12-f3e3-44ea-b05f-2bc4e9ac006b)
![image](https://github.com/duckdb/duckdb/assets/39759821/02266980-fff4-49c6-aad9-76c54cee88dc)

**Case 3:**
29GB files are divided into 128MB small files，about 268 files。
![image](https://github.com/duckdb/duckdb/assets/39759821/5f53bfe6-0121-47e0-9eb2-dd907fead01d)
![image](https://github.com/duckdb/duckdb/assets/39759821/ae9725b2-7915-4e04-81fa-cf47bc7ebc02)

The results are different, I compared the results of the above three cases, Case 1 is similar to case 3， case 2 is slower than others,
I noticed that estimated cardinality (EC) is different, EC resulted in different query plans. could tell me How estimated cardinality (EC) is calculated when explain analyze a query?

### OS:

windows10

### DuckDB Version:

0.9.2

### DuckDB Client:

duckdb_cli-windows-amd64.zip

### Full Name:

Tom

### Affiliation:

Strive

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tmonster** [comment]
Hi qzbqzb,

Can you provide details on the following?

- Number of cores available to Duckdb
- The number of rows in files data_[12-16].parquet

I have found that duckdb estimates that cardinality of multiple parquet files to be the (row_count of the first file) * (number of files).

The number of threads that are used to read parquet files is then the MAX( (number of cores on your system), (row_groups in first file * amount of files)). 

My hunch is that when you read the 12 parquet files, the first file found has cardinality 0. The number of threads allocated to reading the 12 parquet files is the 12 (the number of parquet files). In your other two cases, I imagine we have better estimates and we allocate more threads to read the parquet files.

Can you confirm that this might be the case? To fix this we plan on defaulting the parquet reader to use the maximum number of threads by default.

**Comment by Tmonster** [comment]
@qzbqzb Can you let me know if the new version of Duckdb (v0.10.0) fixes your issue?
Thanks!

**Comment by qzbqzb** [comment]
> Hi qzbqzb,
> 
> Can you provide details on the following?
> 
> * Number of cores available to Duckdb
> * The number of rows in files data_[12-16].parquet
> 
> I have found that duckdb estimates that cardinality of multiple parquet files to be the (row_count of the first file) * (number of files).
> 
> The number of threads that are used to read parquet files is then the MAX( (number of files), (row_groups in first file * amount of files)).
> 
> My hunch is that when you read the 12 parquet files, the first file found has cardinality 0. The number of threads allocated to reading the 12 parquet files is the 12 (the number of parquet files). In your other two cases, I imagine we have better estimates and we allocate more threads to read the parquet files.
> 
> Can you confirm that this might be the case? To fix this we plan on defaulting the parquet reader to use the maximum number of threads by default.


Sorry for replying so late,

1. Number of cores available to Duckdb is 12；
![image](https://github.com/duckdb/duckdb/assets/39759821/218b28c1-ecf3-41bb-b275-64bf08962406)
2. I have founded another question，when I export parquet files with sql of **copy (select xxx) to xxx (format parquet, codec ZSTD, PER_THREAD_OUTPUT true)**, my number of cores available to duckdb is 12, so I hope to get 12 files, but actually I get 19 files, file0 to file11 are data files, file12 to file18 are very small and the number of rows is 0，Is this  a bug?
![image](https://github.com/duckdb/duckdb/assets/39759821/0fc8780b-2c27-453a-bf62-dd077457bc3e)

**Comment by qzbqzb** [comment]
> @qzbqzb Can you let me know if the new version of Duckdb (v0.10.0) fixes your issue? Thanks!

I hava tested with v0.9.2 and v0.10.0. And v0.10.0 have fixed my issue, thanks very much.
This is v0.9.2:
![image](https://github.com/duckdb/duckdb/assets/39759821/bf24d317-d319-49fa-999b-b0e2911ea319)
This is v0.10.0:
![image](https://github.com/duckdb/duckdb/assets/39759821/51b38552-cb17-4312-aeb2-c0350fc050e1)

**Comment by Tmonster** [comment]
closing since @qzbqzb  reported the issue as fixed
