### ISSUE TITLE
Different results when there are duplicate columns with different capitalization

### ISSUE THREAD

**Issue by suchanlee** [duckdb/duckdb#10543]
### What happens?

When there are duplicate column names but with different capitalization (e.g. `one`, `ONE`), it doesn't dedupe the column names for the first query, but does dedupe them in the second query, which is unexpected.

In addition, column name deduping isn't consistent between querying a dataframe and CTE. The former will dedupe via `_index` (e.g. `one`, `ONE_1`), the latter dedupes via `:index` (e.g. `one`, `ONE:1`).

Tested on duckdb 0.8.1, 0.9.2.

### To Reproduce

```python
import duckdb
import pandas as pd

con = duckdb.connect(database=':memory')
df = con.execute('select 1 as one, 2 as "ONE"').fetchdf()
print(df)

con.register('tbl', df)
df2 = con.execute("select * from tbl").fetchdf()
print(df2)

df3 = con.execute('with t as (select 1 as one, 2 as "ONE") select * from t').fetchdf()
print(df3)
```

This will output:
```
# df
   one  ONE
0    1    2

# df2
   one  ONE_1
0    1      2

# df3
   one  ONE:1
0    1      2
```

### OS:

OSX

### DuckDB Version:

0.8.1, 0.9.2

### DuckDB Client:

Python

### Full Name:

Suchan Lee

### Affiliation:

Hex Technologies

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
https://github.com/duckdb/duckdb/pull/10532

I'll have a look at the case where it doesnt deduplicate, that might not be covered by that PR yet

**Comment by suchanlee** [comment]
awesome, thanks

**Comment by Tishj** [comment]
```
➜  duckdb git:(deduplicate_columns) ✗ python3 tmp/duplicate_df.py 
   one  ONE_1
0    1      2
   one  ONE_1
0    1      2
   one  ONE:1
0    1      2
```

Not entirely deduplicated it seems, I'll hunt down the ":" version
