### ISSUE TITLE
Duckdb send request to amazon.aws when partition by statement is present and s3_endpoint is customized

### ISSUE THREAD

**Issue by alexisdondon** [duckdb/duckdb#10556]
### What happens?

When launching with custom s3_endpoint this script with PARTITION BY statement.
```
INSTALL httpfs;
LOAD httpfs;
CREATE TABLE mytable as select * from (values ('a','1'),('b','2')) as t(col1,col2);
SET s3_url_style='path';
SET s3_endpoint='yours3endpointnotamazon';
COPY mytable TO 's3://bucket/table' (FORMAT PARQUET, PARTITION_BY (col1));
```

https://github.com/duckdb/duckdb/discussions/10547
https://github.com/duckdb/duckdb/issues/7167

the script is quite long trying to reach s3.amazon.aws
we can see dropped tcp 443 paquet to amazon each 30s with 4 retry for long minutes.

### To Reproduce

go in an offline environment and launch the script

### OS:

linux windows

### DuckDB Version:

v0.9.2

### DuckDB Client:

duckdb cli and python

### Full Name:

Alexis D.

### Affiliation:

Insee

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @alexisdondon, I tried to reproduce this on macOS (latest stable version, running on an M2 Pro CPU).

For me, the timeout was reasonably quick:
```
D COPY mytable TO 's3://bucket/table' (FORMAT PARQUET, PARTITION_BY (col1));
Run Time (s): real 2.131 user 0.019306 sys 0.009609
Error: IO Error: Connection error for HTTP GET to '/bucket/?encoding-type=url&list-type=2&prefix=table%2F'
```

**Comment by alexisdondon** [comment]
Hi , thanks for checking this.

From my understanding of duckdb if you change nothing and depending of your network configuration, let say your network configuration have a timeout (proxy for example) > duckdb http_timeout 

```
http_retry_backoff | Backoff factor for exponentially increasing retry wait time (default 4) | FLOAT | 4
http_retry_wait_ms | Time between retries (default 100ms) | UBIGINT | 100
http_timeout | HTTP timeout read/write/connection/retry (default 30000ms) | UBIGINT | 30000
```

you should experienced at least 4 retries of 30s for each query made on a non reachable/wanted dns.

Anyway, is the problem a network configuration latency or is the problem some query made on a non wanted endpoints?

**Comment by alexisdondon** [comment]
@Mause @szarnyasg problem do not occur on duckdb v08.1

**Comment by alexisdondon** [comment]
@Mause @szarnyasg 
Digging the problem i think that when
```
COPY mytable TO 's3://bucket/table' (FORMAT PARQUET, PARTITION_BY (col1));
```
there is a first try of the copy with default httpfs s3 variable leading to vhost style to bucket.s3.amazonaws.com.
If your environment is offline but resolve the dns, the duckdb client send 30s*5 retry*nb ip of s3.amazonaws.com dns that is quite long.
After the fail, the copy is executed with specific s3 env variable like custom s3_endpoint.

In my environment i need to force non dns resolution of amazon domain and then the client fallback quickly with specific s3 env variable like custom s3_endpoint.

Anyway, i am pretty sur that the first try is a bug from duckdb those requests should not be attempt.
