### ISSUE TITLE
pip install duckdb build fails

### ISSUE THREAD

**Issue by vlsireddy** [duckdb/duckdb#10566]
### What happens?

1. pip install duckdb fails in pycharm

============================
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for duckdb
Failed to build duckdb
ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects
=================

3.  did it independently outside of pycharm ide using cmd window. still it fails.

### To Reproduce

Python version 3.12.0, 
Visual studio Community 2022 17.8.2,
Pycharm 2023.2.5 

 "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iduckdb_build/src/include -Iduckdb_build/third_party/fmt/include -Iduckdb_build/third_party/fsst -Iduckdb_build/third_party/re2 -Iduckdb_build/third_party/miniz -Iduckdb_build/third_party/utf8proc/include -Iduckdb_build/third_party/utf8proc -Iduckdb_build/third_party/hyperloglog -Iduckdb_build/third_party/fastpforlib -Iduckdb_build/third_party/tdigest -Iduckdb_build/third_party/libpg_query/include -Iduckdb_build/third_party/libpg_query -Iduckdb_build/third_party/concurrentqueue -Iduckdb_build/third_party/pcg -Iduckdb_build/third_party/httplib -Iduckdb_build/third_party/fast_float -Iduckdb_build/third_party/mbedtls -Iduckdb_build/third_party/mbedtls/include -Iduckdb_build/third_party/mbedtls/library -Iduckdb_build/third_party/jaro_winkler -Iduckdb_build/third_party/jaro_winkler/details -Iduckdb_build/extension/parquet/include -Iduckdb_build/third_party/parquet -Iduckdb_build/third_party/snappy -Iduckdb_build/third_party/thrift -Iduckdb_build/third_party/zstd/include -Iduckdb_build/extension/icu/include -Iduckdb_build/extension/icu/third_party/icu/common -Iduckdb_build/extension/icu/third_party/icu/i18n -Iduckdb_build/extension/fts/include -Iduckdb_build/third_party/snowball/libstemmer -Iduckdb_build/third_party/snowball/runtime -Iduckdb_build/third_party/snowball/src_c -Iduckdb_build/extension/tpch/include -Iduckdb_build/extension/tpch/dbgen/include -Iduckdb_build/extension/tpcds/include -Iduckdb_build/extension/tpcds/dsdgen/include -Iduckdb_build/extension/tpcds/dsdgen/include/dsdgen-c -Iduckdb_build/extension/json/include -Iduckdb_build/extension/json/yyjson/include -Iduckdb_build/extension/jemalloc/include -Iduckdb_build/extension/jemalloc/jemalloc/include -Iduckdb_build -IC:\Users\mypc\AppData\Local\Temp\pip-install-j76altoc\duckdb_758950cffa4142fcb31c93f33027e2ab\src\include -IC:\Users\mypc\AppData\Local\Temp\pip-build-env-lub50x4i\normal\Lib\site-packages\pybind11\include -IC:\Users\mypc\AppData\Local\Temp\pip-build-env-lub50x4i\normal\Lib\site-packages\pybind11\include -IC:\Users\mypc\PycharmProjects\duckdb_check1\venv\include -IC:\Users\mypc\AppData\Local\Programs\Python\Python312\include -IC:\Users\mypc\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpduckdb_build/extension/jemalloc/jemalloc/src/arena.cpp /Fobuild\temp.win-amd64-cpython-312\Release\duckdb_build/extension/jemalloc/jemalloc/src/arena.obj /wd4244 /wd4267 /wd4200 /wd26451 /wd26495 /D_CRT_SECURE_NO_WARNINGS /utf-8 -DDUCKDB_PYTHON_LIB_NAME=duckdb -DDUCKDB_BUILD_LIBRARY -DWIN32 -DDUCKDB_EXTENSION_PARQUET_LINKED -DDUCKDB_EXTENSION_ICU_LINKED -DDUCKDB_EXTENSION_FTS_LINKED -DDUCKDB_EXTENSION_TPCH_LINKED -DDUCKDB_EXTENSION_JSON_LINKED -DDUCKDB_EXTENSION_AUTOLOAD_DEFAULT=1 -DDUCKDB_EXTENSION_AUTOINSTALL_DEFAULT=1
      arena.cpp
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(267): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(269): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(273): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(275): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(279): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(281): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/internal/jemalloc_internal_macros.h(36): warning C4005: 'restrict': macro redefinition
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/internal/jemalloc_internal_decls.h(87): note: see previous definition of 'restrict'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for duckdb
Failed to build duckdb
ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects

(venv) C:\Windows\System32>

### OS:

Windows X64

### DuckDB Version:

duckdb-0.9.2.tar.gz

### DuckDB Client:

Python

### Full Name:

RC Reddy

### Affiliation:

Individual

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
0.9.2 does not support Python 3.12, please try a nightly version instead, or wait for the next release
