### ISSUE TITLE
Remove NullValue<T> and friends

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1056]
We still use a special value in the domain to represent null values for integers in some places (specifically hash tables); this is a remnant from an earlier implementation of null values. These need to go because they make interfacing with other file formats much more difficult (now we need to check all int32 before importing a parquet file, for example). Instead the hash tables should have a bitmask at the start of every row that indicates null-ness of every value.

**Comment by hawkfish** [comment]
I think `NullValue` itself is not so much the problem (it seems useful to stick a specific value into the spot) but rather `IsNullValue`. So invalid => `NullValue` but *not* `IsNullValue`=> invalid?

**Comment by Mytherin** [comment]
Do you mean it would be useful for e.g. debugging purposes? I think that having this NullValue<T> exist is a bit confusing if it is not meant to be read back in, so if it is just for debugging purposes perhaps writing DEADBEEF is better?

**Comment by hawkfish** [comment]
I was thinking more for stability in the face of bugs, but crashing may be better. In any case, my point is more that there should be an easy way to put something in the slot for a `NULL` value, which is what `NullValue` then becomes. *What* it returns is a different issue.

**Comment by hawkfish** [comment]
I have a similar fix in the works for `JoinHashTable`.  After that, the only users of `IsNullValue` are some serialisation code. I'm not sure what to do about that.

**Comment by hawkfish** [comment]
I figured out the serialisation stuff and I have a fix for that once this is approved. At that point it will all be dead.

**Comment by hawkfish** [comment]
The *what* of `NullValue` seems somewhat moot to me. The existing values are mostly uncommon bit patterns (integers) or NANs (which seems reasonable). The only places it will be used after `IsNullValue` is gone are as placeholders in fixed-size data structures (e.g. `Vector` data, row layouts) and for hashing (Who ya gonna hash? Null-Value!). The hashing thing make me not want to change it to avoid disturbing results.

**Comment by Mytherin** [comment]
I'm fine with keeping the NullValue as-is as long as `IsNullValue` is gone, the values are indeed pretty reasonable. I would add a clear comment that states that `NullValue<T>` is used only for hashes and as placeholder value, and comparing to `NullValue<T>` to check for nullness is incorrect.
