### ISSUE TITLE
duckdb.connect uses the wrong path connecting to duckdb file on SMB share

### ISSUE THREAD

**Issue by dan9401** [duckdb/duckdb#10561]
### What happens?

duckdb.connect uses the wrong path when connecting to duckdb file on SMB share

with `duckdb.connect("smb:// /path/to/db/mydb.duckdb")`, the error thrown shows **duckdb is concatenating cwd and the smb connection**, `IO Error: Cannot open file "local_cwd\smb: \ \path\to\db\mydb.duckdb"`

### To Reproduce

For smb to work at all, I need to add `path=self._strp_protocol(path)` in `fsspec.implementations.smb.SMBFileSystem.info()`, as stated here in this comment: https://github.com/duckdb/duckdb/issues/9298#issuecomment-1768976227.

For the error:

```python
import duckdb
from fsspec import filesystem

fs = filesystem('smb', host='host.address.com')
duckdb.register_filesystem(fs)

fs.isfile("/path/to/db/mydb.duckdb") # True
duckdb.sql("attach 'smb:// /path/to/db/mydb.duckdb/' as mydb") # success

conn = duckdb.connect("smb:// /path/to/db/mydb.duckdb/") # IO Error
```

### OS:

Windows 10

### DuckDB Version:

0.9.2/0.9.3dev4040

### DuckDB Client:

Python

### Full Name:

Daniel Xia

### Affiliation:

*

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by dan9401** [comment]
Given that directly working with `fsspec.filesystem` seems to have no problem, perhaps the `path=self._strp_protocal(path)` need to be implemented on the duckdb side instead?

**Comment by Mause** [comment]
This is an upstream issue with fsspec, we've had similar issues before: https://github.com/fsspec/filesystem_spec/pull/1307/

Additionally, I'd strongly recommend not storing DuckDB database files on samba, as you'll see a significant performance decrease

**Comment by dan9401** [comment]
Thx for the info, I'll try the fix upstream before fsspec updates it.
