### ISSUE TITLE
The 0.10.0 release on PyPI has only Windows wheels

### ISSUE THREAD

**Issue by no23reason** [duckdb/duckdb#10620]
### What happens?

In the 0.10.0 release, there are only Windows wheels: https://pypi.org/project/duckdb/0.10.0/#files so installation on macOS fails for that version.

### To Reproduce

Run `pip install duckdb==0.10.0` on macOS

### OS:

macOS

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Dan Homola

### Affiliation:

GoodData

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
The builds are still running so please stand by

**Comment by no23reason** [comment]
Thank you for the quick response. I did not know you can add things to the release gradually. Maybe it would be less confusing to have the wheels ready first and then create a version in PyPI? :)

**Comment by no23reason** [comment]
Anyway, the wheels seem to be appearing gradually, closing this. Sorry for the false alarm.
