### ISSUE TITLE
Error loading extension / access denied

### ISSUE THREAD

**Issue by axkirst** [duckdb/duckdb#10639]
### What happens?

I've found similar issues, but I'm working on the current stable version und no solution fits:

When installing / loading any extension (e.g. "spatial") I get  

`HTTP Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.10.0/windows_amd64/spatial.duckdb_extension.gz"
Extension "spatial" is an existing extension.`

When trying any suffix of this URL in my browser, I get a small XML file with error "access denied"

### To Reproduce

```
import duckdb

duckdb.install_extension('spatial')
duckdb.load_extension('spatial')

def iter_excel_duckdb(file):
    rows = duckdb.sql(f"""
        SELECT * FROM st_read(
            '{file.name}',
            open_options=['HEADERS=FORCE', 'FIELD_TYPES=AUTO'])
    """)
    while row := rows.fetchone():
        yield dict(zip(rows.columns, row))
        

with open(r'data/test.xlsx', 'rb') as f:
    rows = iter_excel_duckdb(f)
    row = next(rows)
    print(row)
```

### OS:

Win 11

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Axel Kirst

### Affiliation:

abat+ GmbH

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by fordmustang5l** [comment]
See if this comment. https://github.com/duckdb/duckdb/issues/10637#issuecomment-1941990934

**Comment by Mytherin** [comment]
The Windows extensions have now been published.

**Comment by axkirst** [comment]
Ah,  https://github.com/duckdb/duckdb/issues/10637#issuecomment-1941990934 was nearly exact at the same time (and may be I didn't understood it completly). 
Works fine now, Thank you very much.
