### ISSUE TITLE
httpfs extension access denied

### ISSUE THREAD

**Issue by OneCyrus** [duckdb/duckdb#10637]
### What happens?

can't load the httpfs extensions as the destination gives an access denied

### To Reproduce

install httpfs extension in duckdb

```
self.db.query("install httpfs; load httpfs;")
duckdb.duckdb.HTTPException: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.10.0/linux_amd64_gcc4/httpfs.duckdb_extension.gz"
Extension "httpfs" is an existing extension.
```

the response at this url gives:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D8VD75S1TW00RVQM</RequestId>
<HostId>asjGY8iXi8tEqutad/sL8Zcqlpo9M+oCBldHYZNzv93Up6ieb0pxHcoSgwJUI14nGmryM6rW4tk=</HostId>
</Error>
```

### OS:

Ubuntu 22.04

### DuckDB Version:

0.10

### DuckDB Client:

Python / Dagster

### Full Name:

Daniel Gut

### Affiliation:

Aveniq

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by notedwin** [comment]
I was also running into this issue. I temporarily solved it by downgrading to version 0.9.2.

**Comment by Mytherin** [comment]
The Linux extensions should now all be uploaded. Windows extensions are still being built.

**Comment by OneCyrus** [comment]
it works again. thanks everyone!
