### ISSUE TITLE
DUCKDB_TYPE_UHUGEINT breaks compatibility with C api clients

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#10634]
### What happens?

In the `DUCKDB_TYPE` enum a new member, `DUCKDB_TYPE_UHUGEINT` was inserted in the middle causing all other member values to increment. This breaks compatibility with every library that uses C Api.

### To Reproduce

Try using an existing library with DuckDB 0.10.0

### OS:

Doesn't matter

### DuckDB Version:

0.10.0

### DuckDB Client:

Any client via C API

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ak-coram** [comment]
I'm not sure this is a good idea since it essentially would break compatibility again (with 0.10.0), but I agree that this should be done for similar changes in the future.

**Comment by Mytherin** [comment]
Thanks for the report! It is indeed unfortunate that this broke C ABI compatibility in a way that could have been avoided. I will submit a patch to add explicit enum numbering and a warning to ensure we don't break this in the future.
