### ISSUE TITLE
Database file not decreasing in size

### ISSUE THREAD

**Issue by skinkie** [duckdb/duckdb#10651]
### What happens?

After TRUNCATE I would expect the database to slim down. It remains huge.

### To Reproduce

```
[skinkie@de2 vdvserver]$ ls -l vdv453.duckdb 
-rw-r--r-- 1 skinkie skinkie 3206819840 Feb 14 09:47 vdv453.duckdb
[skinkie@de2 vdvserver]$ ./duckdb vdv453.duckdb 
v0.10.0 20b1486d11
Enter ".help" for usage hints.
D .schema
CREATE TABLE abo(sender VARCHAR, abo_id INTEGER, linien_filter BOOLEAN, umlauf_filter BOOLEAN, hysterese INTEGER, vorschauzeit INTEGER, verfall_zst INTEGER, PRIMARY KEY(sender, abo_id), FOREIGN KEY (sender) REFERENCES sender(sender));
CREATE TABLE linien_filter(sender VARCHAR, abo_id INTEGER, linien_id VARCHAR, richtungs_id VARCHAR, PRIMARY KEY(sender, abo_id, linien_id), FOREIGN KEY (sender, abo_id) REFERENCES abo(sender, abo_id));
CREATE TABLE queue(journeyref VARCHAR, linien_id VARCHAR, richtungs_id VARCHAR, umlauf_id VARCHAR, expiry INTEGER, epoch INTEGER, message VARCHAR, PRIMARY KEY(journeyref));
CREATE TABLE sender(sender VARCHAR, epoch INTEGER, uri VARCHAR, PRIMARY KEY(sender));
CREATE TABLE umlauf_filter(sender VARCHAR, abo_id INTEGER, umlauf_id VARCHAR, PRIMARY KEY(sender, abo_id, umlauf_id), FOREIGN KEY (sender, abo_id) REFERENCES abo(sender, abo_id));
D truncate abo;
D truncate linien_filter;
D truncate queue;
D truncate umlauf_filter;
D CHECKPOINT ;
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows  │
└─────────┘
D 

[skinkie@de2 vdvserver]$ ls -la *duckdb
-rwxr-xr-x 1 skinkie skinkie   44358120 Feb 13 14:27 duckdb
-rw-r--r-- 1 skinkie skinkie 3206557696 Feb 14 09:49 vdv453.duckdb
```

### OS:

Linux

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

3.11.6

### Full Name:

Stefan de Konink

### Affiliation:

Stichting OpenGeo

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Sounds related to this discussion?
https://discord.com/channels/909674491309850675/921073327009853451/1202313395466928138

You might need to also purge the metadata for us to be able to reclaim the lost space

**Comment by skinkie** [comment]
> Sounds related to this discussion? https://discord.com/channels/909674491309850675/921073327009853451/1202313395466928138
> 
> You might need to also purge the metadata for us to be able to reclaim the lost space

What would be the purge metadata command?

**Comment by szarnyasg** [comment]
Hi, unfortunately we cannot tackle this without a reproducer. If a reproducer is available, feel free to reopen.

**Comment by skinkie** [comment]
@szarnyasg what part can't you reproduce? Insert + truncate is easy to do right?
