### ISSUE TITLE
ARRAY and parquet: not quite complete

### ISSUE THREAD

**Issue by lstefano71** [duckdb/duckdb#10663]
### What happens?

A table containing an ARRAY column won't be written to a parquet file.

### To Reproduce

```
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select array_value(1,2,3);
┌──────────────────────┐
│ array_value(1, 2, 3) │
│      integer[3]      │
├──────────────────────┤
│ [1, 2, 3]            │
└──────────────────────┘
D create table test as select array_value(1,2,3);
D describe test;
┌──────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│     column_name      │ column_type │  null   │   key   │ default │  extra  │
│       varchar        │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ array_value(1, 2, 3) │ INTEGER[3]  │ YES     │         │         │         │
└──────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
D copy test to 'array.parquet';
Error: Not implemented Error: Unimplemented type for Parquet "INTEGER[3]"
```

### OS:

Windows 10

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Stefano Lanzavecchia

### Affiliation:

private

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
`ParquetWriter::TypeIsSupported` is missing support for the ARRAY type
