### ISSUE TITLE
Unable to install custom extensions from S3 bucket

### ISSUE THREAD

**Issue by Dtenwolde** [duckdb/duckdb#10668]
### What happens?

When running `duckdb -unsigned` from the CLI, I am unable to install a custom extension from an S3 bucket after setting `SET custom_extension_repository` to the correct bucket. 
The error I get is `Error: IO Error: Failed to copy local extension "duckpgq" at PATH "s3://duckpgq/v0.10.0/osx_arm64/duckpgq.duckdb_extension"` which seems to indicate that it is looking for a local file, not at the actual S3 bucket. Installing and loading the `httpfs` extension does not resolve the issue. 

Seems related to https://github.com/duckdb/duckdb/issues/9835

The extension file I am trying to load is in a public S3 bucket downloadable [here](https://duckpgq.s3.eu-north-1.amazonaws.com/v0.10.0/osx_arm64/duckpgq.duckdb_extension)

### To Reproduce

Run `duckdb -unsigned` 
```sql
SET custom_extension_repository = 's3://duckpgq';
install 'duckpgq';
```
Results in: 
`Error: IO Error: Failed to copy local extension "duckpgq" at PATH "s3://duckpgq/v0.10.0/osx_arm64/duckpgq.duckdb_extension"`

### OS:

macOs 13 - Apple M1 Pro

### DuckDB Version:

V0.10.0

### DuckDB Client:

CLI

### Full Name:

Daniel ten Wolde

### Affiliation:

CWI

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
This is not currently supported, see https://github.com/duckdb/duckdb/issues/9835, you are expected to use the equivalent HTTP path, that probably looks like:
http://duckpgq.s3.us-east-2.amazonaws.com/v0.10.0/osx_arm64/duckpgq.duckdb_extension
(unsure what region are you using)

**Comment by Dtenwolde** [comment]
Thank you, that seems to resolve the issue. I then run into an issue that the file cannot be loaded 
`could not be loaded: dlopen(/Users/dljtw/.duckdb/extensions/v0.10.0/osx_arm64/duckpgq.duckdb_extension, 0x0006)`
But that seems unrelated.
