### ISSUE TITLE
The C-API and ARRAYs

### ISSUE THREAD

**Issue by lstefano71** [duckdb/duckdb#10667]
### What happens?

I am using the C-API through an interpreted language and when I use a sequence of calls that looks like this:
```
      row_count←api.duckdb_data_chunk_get_size _data_chunk
      _vector←api.duckdb_data_chunk_get_vector _data_chunk data_chunk_ind
      _column_type←api.duckdb_vector_get_column_type _vector
      type_id←api.duckdb_get_type_id _column_type
 ```
 `type_id` is assigned 0 (DUCKDB_TYPE_INVALID). Indeed (?) `duckdb_type`'s enum from [`dubkdb.h`](https://github.com/duckdb/duckdb/blob/82e85721e40d13d1cd0571c92674c28e9a5c90c5/src/include/duckdb.h#L70C1-L136C15) does not contain an entry for ARRAY. Am I missing something or was the C-API not updated to cater for ARRAYs?

You'll have to believe here that the _data_chunk is valid (it was obtained via `duckdb_query -> duckdb_result_get_chunk` from the simple query `select array_value(1,2,3)`.

### To Reproduce

 I will eventually be able to build a full repro in C but it's going to take a while...

### OS:

Windows

### DuckDB Version:

0.10.0

### DuckDB Client:

C-API

### Full Name:

Stefano Lanzavecchia

### Affiliation:

private

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Maxxen** [comment]
The C-API has not been updated to support ARRAY's explicitly.
