### ISSUE TITLE
Performance regression: DISTINCT ON got slower and more memory hungry

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10675]
### What happens?

DISTINCT ON has undergone a significant performance regression at some point between 0.9.2 and 0.9.3.dev3715 (unfortunately, I sit behind a corporate proxy and cannot use anything in-between). It's taking up to 3times longer when successful, and it's taking up to 10x VIRT memory and 4x RES memory, making it run OOM more often.
(Also, surprisingly the memory consumption is additive across queries, which to the uninformed observer might indicate a memory leak).

I have previously hinted at this in https://github.com/duckdb/duckdb/issues/10224 but since the main issue there has since been resolved, I figured it's time to create a separate issue for this.

### To Reproduce

First, produce a MWE dataframe:
```python
import duckdb
import pandas as pd
import numpy as np
times = pd.date_range('2019-01-01 00:00:00', '2020-12-31 00:00:00', freq='30 min')
n_times = len(times)
n_products = 3000
n = n_times * n_products
df = pd.DataFrame({
    'time': np.repeat(times, n_products),
    'value': np.arange(n),
    'product': np.tile(np.arange(n_products), n_times)
})
df['time'] = df['time'].dt.tz_localize('UTC').astype('datetime64[us, UTC]')
duckdb.query("""
SET MEMORY_LIMIT='64GB';
SELECT * FROM duckdb_settings()  
WHERE name SIMILAR TO '.*mem.*'
""")
```
Then, using 0.9.3.dev3715 or 0.10.0, the following query 
```
duckdb.query("""
SELECT 
DISTINCT ON (time::DATE, product)
*
FROM df
ORDER by time DESC
""")
```
takes one minute on the first run, peaking at 190GB VIRT and 50GB RES memory usage as reported by htop. On rerunning the query, it almost immediately fails with 
```
OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes
```

On 0.9.2, the same query completes in 25 seconds, peaking at 19GB VIRT and 16GB RES memory usage as reported by htop. Also, the query can be rerun arbitrarily often without increasing VIRT or RES and finishing in ~18s on reruns.

If I reduce `n_products` to `2000`, 0.10.0 takes 41s, peaking at 100GB VIRT / 30GB RES, whereas 0.9.2 finishes in 10-14s, peaking at 10GB VIRT / 8GB RES.

NOTES: 
- The memory limit of 64GB doesn't seem to do anything, I just put it in as a safety because while playing around with the parameters of this MWE I quite frequently made my machine freeze to a point where it wouldn't even accept ssh connections anymore (the freezing happens on the duckdb query). This is probably for another ticket though, and I do get the same problems with a 128GB limit.
- The UTC localization is only needed because the query will fail on the date cast in 0.9.2 otherwise. It doesn't affect memory usage and runtime on later versions.

### OS:

Linux

### DuckDB Version:

0.10.0

### DuckDB Client:
python '3.10.6
pandas '2.1.4'
numpy '1.26.3'

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! In https://github.com/duckdb/duckdb/pull/10684 I've pulled through the optimization made in https://github.com/duckdb/duckdb/pull/10457 to the DISTINCT ON clause which makes the query complete in 5 seconds on my laptop. The memory issue is likely separate - I will have a look there as well.

**Comment by Mytherin** [comment]
I did not manage to reproduce the memory issue after the fix. Feel free to re-open if you encounter it again on the latest main.

**Comment by soerenwolfers** [comment]
Thanks, can confirm it finishes in 1.8s for me now and it can now handle n_products=1e5 multiple times without memory problems

**Comment by soerenwolfers** [comment]
I think out of the performance problems I have reported here the only remaining one is https://github.com/duckdb/duckdb/issues/10214. Related to that: is there a reason DISTINCT on isn't converted to a group by? Seehttps://github.com/duckdb/duckdb/discussions/10687
