### ISSUE TITLE
JOIN clause can be aliased, but alias cannot be referenced

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#10685]
### What happens?

I can alias a `JOIN` clause like in the SQL standard and some other RDBMS (e.g. PostgreSQL), but I cannot reference that alias from the query.

### To Reproduce

Try this query, it works:

```sql
select *
from (
  (values (1), (2)) as t1 (a)
  cross join
  (values (3), (4)) as t2 (b)
) as t
```

And produces:

```
|a  |b  |
|---|---|
|1  |3  |
|1  |4  |
|2  |3  |
|2  |4  |
```

So, I can alias the `JOIN` clause, even if that's not documented here:
https://duckdb.org/docs/sql/statements/select#from-clause

<img width="728" alt="image" src="https://github.com/duckdb/duckdb/assets/734593/1b952ca1-aa2c-47f3-9b59-8d3a24e3e7ea">

However, I now cannot reference the `t` alias. Both of these fail:

```sql
select t.*
from (
  (values (1), (2)) as t1 (a)
  cross join
  (values (3), (4)) as t2 (b)
) as t
```

And

```sql
select t.a, t.b
from (
  (values (1), (2)) as t1 (a)
  cross join
  (values (3), (4)) as t2 (b)
) as t
```

The error is:

> SQL Error: java.sql.SQLException: Binder Error: Referenced table "t" not found!
> Candidate tables: "t1", "t2"

### OS:

Microsoft Windows [Version 10.0.22631.3007]

### DuckDB Version:

0.10.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in #10691. Indeed our parser supported it but we were not handling this case correctly in the binder.
