### ISSUE TITLE
gcs filesystem query that worked in 0.9.2 no longer works in 0.10.0

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#10698]
### What happens?

I cannot read GCS data using the `filesystem` integration, in DuckDB version 0.10. This used to work in 0.9.

I get this exception:

```
duckdb.duckdb.HTTPException: HTTP Error: HTTP GET error on 'https://ibis-examples.s3.amazonaws.com/data/band_members.csv.gz' (HTTP 403)
```

### To Reproduce

```python
import duckdb
import fsspec

con = duckdb.connect()
con.load_extension("httpfs")

gcs = fsspec.filesystem("gcs")
con.register_filesystem(gcs)
con.sql("from 'gcs://ibis-examples/data/band_members.csv.gz'")
```

The strange thing is that when I avoid loading the `httpfs` extension, this code works:

```python
import duckdb
import fsspec

con = duckdb.connect()
# con.load_extension("httpfs")

gcs = fsspec.filesystem("gcs")
con.register_filesystem(gcs)
con.sql("from 'gcs://ibis-examples/data/band_members.csv.gz'")
```

### OS:

Linux x86_64

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
Hey @cpcloud thanks for reporting! This is indeed a bug. Without a secret we currently do not set the gcs endpoint correctly. 

A workaround is to create an empty GCS secret, which will take a slightly different codepath picking up the correct endpoint here:

```Python
# Note: no fsspec required
import duckdb
con = duckdb.connect()
con.load_extension("httpfs")

# Workaround for this issue: create an empty GCS secret
con.sql("create secret (type GCS)")

# Query now works!
con.sql("from 'gcs://ibis-examples/data/band_members.csv.gz'")
```
