### ISSUE TITLE
Crash when interrupting complex query

### ISSUE THREAD

**Issue by corwinjoy** [duckdb/duckdb#10699]
### What happens?

When interrupting a long running query, the query shutdown process may produce a core dump due to what I believe is a race condition. This is a followup to https://github.com/duckdb/duckdb/issues/10216 to reproduce the issue inside a regular python script.

### To Reproduce

1. Create a complex query.
```
import pandas as pd
import numpy as np
import duckdb

duckdb.execute(
            """
            -- set the memory limit of the system 
            SET memory_limit = '200GB';
            -- configure the system to use x threads
            SET threads TO 16;
            -- enable printing of a progress bar during long-running queries
            SET enable_progress_bar = true;
            -- temp dir
            SET temp_directory='.tmp';
            """
        )

n = 1_000_000
columns = 100
df = pd.DataFrame({f'col{i}': 1000 * np.random.sample(n) for i in range(columns)})
duckdb.query("""
SELECT 
DISTINCT ON (floor(col0))
*
FROM df
ORDER by col0 DESC
""")
```

2. Simulate an interrupt:
In src/main/client_context.cpp: 404 we simulate a python interrupt from the progress bar:
```
#include <thread>         // std::this_thread::sleep_for
#include <chrono>         // std::chrono::seconds

...
		if (active_query->progress_bar) {
			auto is_finished = PendingQueryResult::IsFinishedOrBlocked(query_result);
			active_query->progress_bar->Update(is_finished);
			query_progress = active_query->progress_bar->GetDetailedQueryProgress();
			std::this_thread::sleep_for (std::chrono::seconds(3));
			throw int(0); // Throw a non standard exception to simulate a python exception
		}
```
You should get a core dump from the query improperly shutting down.
I will add a draft PR to show this change and an expanded test.

### OS:

Ubuntu 22.04.3 LTS

### DuckDB Version:

duckdb-0.1.dev38227

### DuckDB Client:

Python

### Full Name:

Corwin Joy

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by corwinjoy** [comment]
Here is the draft PR with a more complete test example:
https://github.com/duckdb/duckdb/pull/10700

**Comment by Mytherin** [comment]
Thanks for the report! I've tried your reproduction and I only get the following error:

```cpp
fast/api/test_duckdb_interrupt.py:85: in <module>
    run_test()
fast/api/test_duckdb_interrupt.py:81: in run_test
    mytest.test_query_interrupt()
fast/api/test_duckdb_interrupt.py:71: in test_query_interrupt
    self.configure_duckdb()
fast/api/test_duckdb_interrupt.py:34: in configure_duckdb
    duckdb.execute(
E   duckdb.duckdb.Error: Unhandled exception in ExecuteTaskInternal
```

This is expected behavior - note that throwing an exception that is not derived from `std::exception` is in general a programmer error and should not happen.

Also note that Python exceptions and C++ exceptions, despite their name, are not related. A Python exception does not work in the same way as a C++ exception. Python exceptions are internal to the Python library/interpreter. They are translated into C++ exceptions through the `pybind11` library that we use - but that library turns them into regular C++ exceptions again that should derive from `std::exception`.

**Comment by Mytherin** [comment]
As an aside - I noticed your fork is based on a DuckDB version of >1 week ago. I tested the PR which is merged with the latest main. Perhaps the bug you are encountering has already been fixed in https://github.com/duckdb/duckdb/pull/10512?

**Comment by corwinjoy** [comment]
1. In this draft PR I was deliberately throwing an `int`, because when I was debugging this issue before it looked like the `py::error_already_set` (the translation of a Python exception to a C++ exception) did not inherit from `std::error`. Investigating further, it does, so I updated the code.
2. Updating my copy of the fork did seem to fix the problem. It may well be that https://github.com/duckdb/duckdb/pull/10512 does fix the issue. To confirm the updated duckdb main fixes the problem:
    - I created a Google Colab which reproduces the error https://colab.research.google.com/drive/1z33p9vj7BWJvou2_-z98iycXXm7W8eU1?usp=sharing .  The current version of Colab uses duckdb 0.9.2 and can crash when interrupted, as per the original error report.
    - I then created a docker backend for Colab (see branch / PR [10700](https://github.com/duckdb/duckdb/pull/10700) ). Under duckdb 0.9.2 I get the error, but with the latest duckdb main we no longer get a crash. So, the latest code does seem to fix this.

One point to note, depending on where KeyboardInterrupt / SIGINT is intercepted (in the duckdb loop or in the python progress bar) we get different exception messages. At some point, it may make sense to update the progress bar code to catch `py::error_already_set`  and translate keyboard interrupts to a better exception that the base code can recognize. Here are the two cases (note the "Invalid error" from the progress bar, it would probably be better to recoginize this as an interrupt).
```
Top level interrupt: (From tools/pythonpkg/src/pyconnection.cpp: 397)
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
KeyboardInterrupt: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-60-4fb9a9b8cade> in <cell line: 1>()
      5     FROM df
      6     ORDER by col0 DESC
----> 7 """).fetchdf()

RuntimeError: Query interrupted


Progress bar interrupt: (Handled in src/main/client_context.cpp ClientContext::ExecuteTaskInternal)
---------------------------------------------------------------------------

<ipython-input-48-4fb9a9b8cade> in <cell line: 1>()
      5     FROM df
      6     ORDER by col0 DESC
----> 7 """).fetchdf()

Error: Invalid Error: KeyboardInterrupt: <EMPTY MESSAGE>

At:
  /usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py(1268): __new__
  <ipython-input-48-4fb9a9b8cade>(7): <cell line: 1>
  /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3553): run_code
  /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3473): run_ast_nodes
  /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3257): run_cell_async
  /usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py(78): _pseudo_sync_runner
  /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3030): _run_cell
  /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(2975): run_cell
  /usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py(539): run_cell
  /usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py(302): do_execute
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
  /usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(539): execute_request
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
  /usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(261): dispatch_shell
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
  /usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(361): process_one
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(786): run
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(748): __init__
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(250): wrapper
  /usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(377): dispatch_queue
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(786): run
  /usr/local/lib/python3.10/dist-packages/tornado/gen.py(825): inner
  /usr/local/lib/python3.10/dist-packages/tornado/ioloop.py(738): _run_callback
  /usr/local/lib/python3.10/dist-packages/tornado/ioloop.py(685): <lambda>
  /usr/lib/python3.10/asyncio/events.py(80): _run
  /usr/lib/python3.10/asyncio/base_events.py(1909): _run_once
  /usr/lib/python3.10/asyncio/base_events.py(603): run_forever
  /usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py(195): start
  /usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py(619): start
  /usr/local/lib/python3.10/dist-packages/traitlets/config/application.py(992): launch_instance
  /usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py(37): <module>
  /usr/lib/python3.10/runpy.py(86): _run_code
  /usr/lib/python3.10/runpy.py(196): _run_module_as_main
```

**Comment by corwinjoy** [comment]
As per above, it seems that the latest version of main does fix this issue.
