### ISSUE TITLE
[Python] Unable to substitute "COPY ... TO" target using prepared statement

### ISSUE THREAD

**Issue by mars-lan** [duckdb/duckdb#10697]
### What happens?

The following parser exception is thrown when using [Prepared Statements](https://duckdb.org/docs/sql/query_syntax/prepared_statements.html) to set the target of "COPY ... TO" in Python:

```
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "?"
```

The same exception is throw for "COPY ... FROM" as well.

### To Reproduce

Working w/o prepared statements
```python
import duckdb

duckdb.execute("COPY (SELECT 1) TO 'test.parquet'")
```

Parser exception thrown:
```python
import duckdb

duckdb.execute("COPY (SELECT 1) TO ?", ['test.parquet'])
```

### OS:

macOS

### DuckDB Version:

0.9.2 & nightly

### DuckDB Client:

Python

### Full Name:

Mars Lan

### Affiliation:

Metaphor Data

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @mars-lan, thanks for raising this issue.

This can be reproduced from vanilla SQL:
```sql
PREPARE q AS COPY (SELECT 1) TO ?;
```
```text
Error: Parser Error: syntax error at or near "?"
```
The reason for the error is that the `COPY` statement expects a string literal for the filename. So this is currently expected behavior.

As a workaround in Python, I recommend using [f-strings](https://peps.python.org/pep-0498/).

**Comment by mars-lan** [comment]
Thanks for the quick resopnse, @szarnyasg. Could you explain why string literal isn't supported here, whereas it's supported in the case of WHERE clause and INSERT VALUES, e.g. https://duckdb.org/docs/api/python/dbapi.html#prepared-statements?

**Comment by szarnyasg** [comment]
I can think of two reasons
1) This is a limitation may be inherited from the PostgreSQL parser (which form the basis of DuckDB's parser).
2) During the query processing's binding phase, we use the filename to identify its format based on the extension. So writing a `COPY` statement with a filename that ends in `.parquet` or `.csv` will result in a different query plan.
HTH
