### ISSUE TITLE
Queries to a long df that worked in pip duckdb==0.9.2 does not work in duckdb==0.10.0

### ISSUE THREAD

**Issue by hellund** [duckdb/duckdb#10693]
### What happens?

I get the error `IndexError: index 2015628 is out of bounds for axis 0 with size 2015628` when running the same code that ran fine in pip duckdb==0.9.2. The code was a simple `select * from df where column is not null`. Tried to roll back and everything worked. Made a synthetic dataframe to test in new version, but still did not work. The synthetic example worked with few rows, but failed when i added as many rows as i had in my real scenario. 

### To Reproduce

```python
import pandas as pd
import duckdb

# Create a DataFrame with 5 rows
df = pd.DataFrame({'A': range(2015628),
                   'B': range(2015628),
                   'C': None})
# Doing stuff to it in duckdb
sql =  """
        select * from df
        where A is not null
        """
new_df = duckdb.sql(sql).to_df()
new_df
```

### OS:

iOS M2

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Eirik Duesund Helland

### Affiliation:

NAV IKT

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by empowerVictor** [comment]
Had the same issue here
```python
select * from df
limit 10
```
This also raises the same error.

**Comment by nsiicm0** [comment]
Encountered the same issue when reading a parquet file (containing around 3m records) from s3 storage that worked previously on 0.9.2 using the python api on linux.
