### ISSUE TITLE
FATAL Error: Failed to create checkpoint because of error: Out of Range Error: Underflow in HUGEINT addition (0.9.2)

### ISSUE THREAD

**Issue by OneCyrus** [duckdb/duckdb#10709]
### What happens?

last night suddenly the following error appeared in our pipelines. not sure what caused this. also it happens when running the full  pipeline. if i run only the asset which leads to this error duckdb has no issue. So it looks like it's a combination of multiple tables which results in this issue. this happens with 0.9.2

```
duckdb.duckdb.FatalException: FATAL Error: Failed to create checkpoint because of error: Out of Range Error: Underflow in HUGEINT addition

Stack Trace:
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 738, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/storage/db_io_manager.py", line 140, in handle_output
    self._db_client.ensure_schema_exists(context, table_slice, conn)
  File "/usr/local/lib/python3.11/site-packages/dagster_duckdb/io_manager.py", line 268, in ensure_schema_exists
    connection.execute(f"create schema if not exists {table_slice.schema};")
```

```
duckdb.duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "FATAL Error: Failed to create checkpoint because of error: Out of Range Error: Underflow in HUGEINT addition"""
```

### To Reproduce

Running a dagster pipeline with duckdb 0.9.2. This started suddenly without any specific changes in the pipeline. likely caused by some data changes. Unfortunately it happens only when materializing many tables/assets and not the single assets which produce the error above. so probably some side effects :\

### OS:

Ubuntu 22.04

### DuckDB Version:

0.9.2

### DuckDB Client:

Python / Dagster

### Full Name:

Daniel Gut

### Affiliation:

Aveniq

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @OneCyrus, thanks for reporting the issue. Can you please try v0.10.0 or the nightly/main build?

**Comment by OneCyrus** [comment]
looks like we can't reproduce it with 10.x anymore. so let's close this.
