### ISSUE TITLE
SUBSTRING's results are not the same with those by PostgreSQL for negative offset

### ISSUE THREAD

**Issue by zedware** [duckdb/duckdb#10721]
### What happens?

Looks like DuckDB's logic for the negative `offset` of SUBSTRING is not the same as that used in PostgreSQL.
Not sure which if the correct way according to the SQL standard.

### To Reproduce

# Postgres

```
postgres=# select version();
                                                                version
----------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
(1 row)

postgres=# select substring('abc', -1, 1);
 substring
-----------

(1 row)

postgres=# select substring('abc', -1, 2);
 substring
-----------

(1 row)

postgres=# select substring('abc', -1, 3);
 substring
-----------
 a
(1 row)
```

# DuckDB

```
D select version();
┌───────────┐
│ version() │
│  varchar  │
├───────────┤
│ v0.10.0   │
└───────────┘
D select substring('abc', -1, 1);
┌──────────────────────────────┐
│ main.substring('abc', -1, 1) │
│           varchar            │
├──────────────────────────────┤
│ c                            │
└──────────────────────────────┘
D select substring('abc', -1, 2);
┌──────────────────────────────┐
│ main.substring('abc', -1, 2) │
│           varchar            │
├──────────────────────────────┤
│ c                            │
└──────────────────────────────┘
D select substring('abc', -1, 3);
┌──────────────────────────────┐
│ main.substring('abc', -1, 3) │
│           varchar            │
├──────────────────────────────┤
│ c                            │
└──────────────────────────────┘
```

### OS:

Ubuntu Linux x64

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

William ZHANG

### Affiliation:

Renmin University

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by maiadegraaf** [comment]
Hi, thanks for the issue, this is expected behavior, implemented in this PR (https://github.com/duckdb/duckdb/pull/8087#issuecomment-1625323452).  Since SQL-convention is 1-indexed, it made more sense to use it in both the forward and backward index. See this comment (https://github.com/duckdb/duckdb/issues/9267#issuecomment-1752542972) as well.
