### ISSUE TITLE
Out of Memory writing to Parquet

### ISSUE THREAD

**Issue by TimJMartin** [duckdb/duckdb#10737]
### What happens?

I am trying to read 30 CSV files, around 12Gb uncompressed and 30million rows, into a single Parquet file using DuckDB. I have upgraded today to the latest version 0.10.0. 

```
Error: Out of Memory Error: failed to allocate data of size 4.2 MiB (13.9 GiB/13.9 GiB used)
```

### To Reproduce

Each one of my CSV is standardised so I am able to define the column names and types upfront and have done that as part of my query

```
COPY (SELECT * FROM read_csv('*.csv',
  delim = ',',
  header = false,
  parallel = true,
  auto_detect = false,
  columns = {
    'UPRN': 'BIGINT',
    'UDPRN': 'INT',
    'CHANGE_TYPE': 'VARCHAR(1)',
70 more attributes)) 
TO 'output.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100000)
```

Each time I run this I experience an Out of Memory error. 

So I have since tried loading the CSV data into a persistent local database and then doing a COPY export

```
COPY table TO 'output.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100000)
```
I read the recent release notes and there is a new Temporary Memory Manager which I can use and set a memory limit using

```
PRAGMA memory_limit = '10GB';
```

This definitely seems to make the loading more stable but has no impact in the Parquet export. 

I am on a Windows laptop with 32Gb of RAM using the latest DuckDB CLI. 

### OS:

Windows

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Tim Martin

### Affiliation:

Ordnance Survey

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @TimJMartin, did you try running the workload with the following setting?
```sql
SET preserve_insertion_order = false;
```
https://duckdb.org/docs/guides/performance/how_to_tune_workloads#the-preserve_insertion_order-option

**Comment by TimJMartin** [comment]
@szarnyasg - that has fixed it. **Thank you so much** for pointing me towards that setting. 

Reading the docs "When importing or exporting data sets that are much larger than the available memory, out of memory errors may occur." Because my dataset (12Gb uncompressed CSV) is much smaller than my memory (32Gb) I wonder if this is happening more often to people.

**Comment by Mytherin** [comment]
There's a fix for this on the latest main - see https://github.com/duckdb/duckdb/pull/10756
