### ISSUE TITLE
Read csv hangs on imdb dataset

### ISSUE THREAD

**Issue by fithisux** [duckdb/duckdb#10749]
### What happens?

I try to load file with

```
select * from read_csv('title.principals.tsv.gz') limit 10;
```

and it hangs

file from here https://developer.imdb.com/non-commercial-datasets/

used to work in 0.9.2

### To Reproduce

Just download files from https://datasets.imdbws.com/title.principals.tsv.gz

and try to load the TSVs in Duck DB

### OS:

Windows 11

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Vasileios Anagnostopoulos

### Affiliation:

Agile Actors

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@fithisux thanks, this is indeed reproducible. We'll take a look.
