### ISSUE TITLE
 Attempted to dereference unique_ptr that is NULL when inserting many rows

### ISSUE THREAD

**Issue by Miksu82** [duckdb/duckdb#10745]
### What happens?

When inserting (in my case) over 80000 rows results in "duckdb.duckdb.FatalException: FATAL Error: Failed to create checkpoint because of error: Attempted to dereference unique_ptr that is NULL!". I first encountered this when I was updating 2000 rows like this

```
duckdb.sql("CREATE TABLE temp AS SELECT * FROM df")
duckdb.sql("UPDATE target SET col = temp.col FROM temp WHERE target.id = temp.id")
duckdb.sql("DROP TABLE temp")
```

And I got the same error at `DROP TABLE`. I cannot share that code because it is propetiary, but I'll try to see if I can create something else to reproduce it. Below a code snippet that triggers the crash when inserting.

### To Reproduce

```
import duckdb
import random
import string

# Step 1: Generate 2000 random strings of max length 10
def generate_random_strings(n=90000, max_length=10):
    random_strings = []
    for _ in range(n):
        length = random.randint(1, max_length)  # Random length up to 10
        random_str = ''.join(random.choices(string.ascii_letters + string.digits, k=length))
        random_strings.append(random_str)
    return random_strings

random_strings = generate_random_strings()

# Step 2: Connect to DuckDB. This will create an in-memory database by default.
# To persist data, you can specify a file name e.g., duckdb.connect('mydata.db')
con = duckdb.connect(database='test.db', read_only=False)

# Step 3: Create a table with an autoincrement ID
con.execute("""
    CREATE TABLE test_table (
        id INTEGER,
        random_string VARCHAR,
        emb FLOAT[]
    );
""")

con.execute("")

# Insert the strings into the table
insert_query = "INSERT INTO test_table (id, random_string) VALUES (?, ?)"

# DuckDB's executemany is used for batch insertion.
con.executemany(insert_query, [(i, s,) for i, s in enumerate(random_strings)])

# Verify the insertion
result = con.execute("SELECT COUNT(*) FROM test_table").fetchall()
print(f"Inserted rows: {result[0][0]}")

# Optional: Display some inserted rows to verify
sample_result = con.execute("SELECT * FROM test_table LIMIT 5;").fetchall()
print("Sample inserted rows:")
for row in sample_result:
    print(row)

# Close the connection (in case of a persistent database)
con.close()
```

### OS:

macOS M3 Pro 14.1

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

python 3.12.1

### Full Name:

Mika Ristimäki

### Affiliation:

Private

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Miksu82** [comment]
I tried with Python 3.10.13 and DuckDB 0.9.2, and there it works fine. Seems to only affect the newest version

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in https://github.com/duckdb/duckdb/pull/10863

**Comment by sambcom** [comment]
@Mytherin I'm having difficulty reproducing this, but I get this every 50 or so S3 queries. Not always glob queries, but here's an example:

SELECT * FROM glob(['s3://foo-baz-test/shards/canada/h3level7=608025765988007935/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764729716735/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764813602815/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764075405311/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025766021562367/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764243177471/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025765467914239/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764293509119/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025765954453503/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764746493951/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025765937676287/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764780048383/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025769863544831/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764763271167/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025766004785151/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764276731903/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764209623039/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764192845823/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025764259954687/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025765971230719/single_shard*.parquet', 's3://foo-baz-test/shards/canada/h3level7=608025766038339583/single_shard*.parquet'])

duckdb.duckdb.InternalException: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

**Comment by Mytherin** [comment]
Are you using v0.10.1 or an older version of DuckDB? If an older version - could you try on v0.10.1?

**Comment by sambcom** [comment]
v0.10.1 and should've mentioned that I'm using the Python API.

% pip show duckdb
Name: duckdb
Version: 0.10.1
% python -V
Python 3.12.2

**Comment by Mytherin** [comment]
Could you share the exact python statement you are using instead of only the SQL query?

**Comment by Mytherin** [comment]
I've tried replicating by running the following snippet in a loop, but no dice after 100+ iterations:

```py
import duckdb
for i in range(1000000):
    print(i)
    duckdb.sql("""from glob (['s3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1998*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1997*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1996*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1995*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1994*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1993*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1992*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1991*/data_0.csv',
's3://test-bucket-aws-private/lineitem_partitioned/l_shipdate=1990*/data_0.csv']);""")
```

How many files are returned by your glob method?

**Comment by sambcom** [comment]
5 files. Aha, I'm using asyncio. Guessing that is the problem? I will remove and update if I get the error again.

**Comment by Mytherin** [comment]
Could you share the code snippet? An internal exception is always a DuckDB bug, so I would love to resolve it.

**Comment by sambcom** [comment]
Having a tough time reproducing outside of my app. Thanks for the quick replies will let you know if I manage to do it.

**Comment by jivanic-demystdata** [comment]
Same error here: https://github.com/duckdb/duckdb-java/issues/137, probably not same issue tho
