### ISSUE TITLE
Unable to unpivot columns of different types after implicit casting change

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#10757]
### What happens?

If I try to unpivot multiple columns that have different types, I receive an error that explicit casts are needed. However, the unpivot operator does not allow casting within its syntax, so I don't have the ability to manually cast. Additionally, having to manually cast is undesirable in the case of doing dynamic unpivoting using the `columns(*)` expression. 

### To Reproduce

```sql
unpivot (select 42 as col1, 'woot' as col2)
    on columns(*);
/* 
Error: near line 203: Binder Error: Cannot create a list of types INTEGER and VARCHAR - an explicit cast is required
Full list: col1 INTEGER, col2 VARCHAR
*/
```
If I try to insert into a specific table that already has types defined, I still receive the same error:
```sql
create or replace table unpivot_destination (name varchar, value varchar);
insert into unpivot_destination
    unpivot (select 42 as col1, 'woot' as col2)
        on columns(*);
/*
Error: near line 211: Binder Error: Cannot create a list of types INTEGER and VARCHAR - an explicit cast is required
Full list: col1 INTEGER, col2 VARCHAR
*/
```

However, the below query succeeds after reverting to the older implicit casting rules:
```sql
set old_implicit_casting = true;
unpivot (select 42 as col1, 'woot' as col2)
    on columns(*);
```
```
┌─────────┬─────────┐
│  name   │  value  │
│ varchar │ varchar │
├─────────┼─────────┤
│ col1    │ 42      │
│ col2    │ woot    │
└─────────┴─────────┘
```

### OS:

MacOS

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Alex Monahan

### Affiliation:

DuckDB Labs and MotherDuck

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Alex-Monahan** [comment]
I also tried another workaround that failed for a very different reason. It seems like using a `columns(*)` expression in the input subquery to an `unpivot` causes an error. I was trying to pre-convert everything to varchars before unpivoting. The goal is to avoid having to know the names of the columns I'm working with, hence all the `columns(*)`...
```sql
unpivot (select cast(columns(*) as varchar) from (select 42 as col1, 'woot' as col2))
    on columns(*);
```
```
Error: near line 221: Binder Error: Referenced column "CAST(unnamed_subquery2.col1 AS VARCHAR)" not found in FROM clause!
Candidate bindings: "__internal_pivot_alias_0.CAST(unnamed_subquery15.col1 AS VARCHAR)", "__internal_pivot_alias_0.CAST(unnamed_subquery15.col2 AS VARCHAR)"
```

**Comment by cmdlineluser** [comment]
In case it's of any use for debugging purposes, the workaround approach appears to work in this case:

```python
duckdb.sql("""
with tbl as (select 42 as col1, 'woot' as col2)
unpivot (from tbl select columns(*)::varchar) on *
""")
```

```python
┌───────────────────────────┬─────────┐
│           name            │  value  │
│          varchar          │ varchar │
├───────────────────────────┼─────────┤
│ CAST(tbl.col1 AS VARCHAR) │ 42      │
│ CAST(tbl.col2 AS VARCHAR) │ woot    │
└───────────────────────────┴─────────┘
```

The names get lost though.

There are a few discussions asking for the ability to preserve them when using `columns()`

- https://github.com/duckdb/duckdb/discussions/7107
- https://github.com/duckdb/duckdb/discussions/7898

**Comment by Alex-Monahan** [comment]
Thank you for the workaround! I'll take it for a spin and see if it will work for this case. 

I had one other thought. Would it be possible to use a `UNION` type when unpivoting multiple types? Then unpivot/pivot may be able to round-trip all the types. (There may be an enhancement needed when pivoting unions, I haven't checked!)

**Comment by Mytherin** [comment]
Thanks for the report! This was an intended change as part of the casting rework. Unpivot combines values of different columns and folds them into a single column, e.g.:

```sql
D unpivot (select '42' as col1, 'woot' as col2)
      on columns(*);
┌─────────┬─────────┐
│  name   │  value  │
│ varchar │ varchar │
├─────────┼─────────┤
│ col1    │ 42      │
│ col2    │ woot    │
└─────────┴─────────┘
```

As you can see we need to make a decision on what column type `value` will be. Previously we would (implicitly) convert that column to `VARCHAR` - but that might not be desirable - hence we now require explicit casts 

The `COLUMNS(*)` cast is pretty elegant - perhaps I can push a change to maintain column names for `COLUMNS(*)` statements since that seems to be generally desirable. 

The `UNION` type idea is interesting as well.

**Comment by Mytherin** [comment]
> I also tried another workaround that failed for a very different reason. It seems like using a `columns(*)` expression in the input subquery to an `unpivot` causes an error. I was trying to pre-convert everything to varchars before unpivoting. The goal is to avoid having to know the names of the columns I'm working with, hence all the `columns(*)`...
> 
> ```sql
> unpivot (select cast(columns(*) as varchar) from (select 42 as col1, 'woot' as col2))
>     on columns(*);
> ```
> 
>  ```
> Error: near line 221: Binder Error: Referenced column "CAST(unnamed_subquery2.col1 AS VARCHAR)" not found in FROM clause!
> Candidate bindings: "__internal_pivot_alias_0.CAST(unnamed_subquery15.col1 AS VARCHAR)", "__internal_pivot_alias_0.CAST(unnamed_subquery15.col2 AS VARCHAR)"
> ```

This is a bug related to using unnamed subqueries in the UNPIVOT, adding an alias fixes the issue:

```sql
D unpivot (select cast(columns(*) as varchar) from (select 42 as col1, 'woot' as col2) AS t)
      on columns(*);
┌─────────────────────────┬─────────┐
│          name           │  value  │
│         varchar         │ varchar │
├─────────────────────────┼─────────┤
│ CAST(t.col1 AS VARCHAR) │ 42      │
│ CAST(t.col2 AS VARCHAR) │ woot    │
└─────────────────────────┴─────────┘
```

I have pushed a fix for this issue here - https://github.com/duckdb/duckdb/pull/10765

**Comment by Alex-Monahan** [comment]
Thank you for your help and for thinking through this for me! I did one other test that may be close to a workaround. If I convert all columns to a union type beforehand, I am able to unpivot them.

```sql
set old_implicit_casting = false;
create or replace table TBL as 
    select 42 as int_column, 'woot' as text_column, 42.01::float as float_column
    union all
    select 43 as int_column, 'woot_again' as text_column, 43.001::float as float_column
;
with all_unions as (
    select 
        cast(columns(*) as union(a int, b varchar, c float)) 
    from TBL
)
unpivot all_unions 
    on columns(*);
```
```
┌────────────────────────────────────────────────────────────────┬──────────────────────────────────────┐
│                              name                              │                value                 │
│                            varchar                             │ union(a integer, b varchar, c float) │
├────────────────────────────────────────────────────────────────┼──────────────────────────────────────┤
│ CAST(TBL.int_column AS UNION(a INTEGER, b VARCHAR, c FLOAT))   │ 42                                   │
│ CAST(TBL.text_column AS UNION(a INTEGER, b VARCHAR, c FLOAT))  │ woot                                 │
│ CAST(TBL.float_column AS UNION(a INTEGER, b VARCHAR, c FLOAT)) │ 42.01                                │
│ CAST(TBL.int_column AS UNION(a INTEGER, b VARCHAR, c FLOAT))   │ 43                                   │
│ CAST(TBL.text_column AS UNION(a INTEGER, b VARCHAR, c FLOAT))  │ woot_again                           │
│ CAST(TBL.float_column AS UNION(a INTEGER, b VARCHAR, c FLOAT)) │ 43.001                               │
└────────────────────────────────────────────────────────────────┴──────────────────────────────────────┘
```

**Comment by Mytherin** [comment]
@Alex-Monahan I have a PR up with some changes to the UNPIVOT here - both to improve the error message and to allow casting  - https://github.com/duckdb/duckdb/pull/10773

**Comment by Mytherin** [comment]
Has been fixed
