### ISSUE TITLE
Linux ODBC driver installer missing update_odbc_path.py

### ISSUE THREAD

**Issue by rgoubet** [duckdb/duckdb#10754]
### What happens?

The zip file for Linux (AMD64) that can be found [here](https://duckdb.org/docs/installation/?version=latest&environment=odbc&installer=binary&platform=linux) is missing a file named `update_odbc_path.py`.

### To Reproduce

Follow the installation instructions. Upon execution of `./unixodbc_setup.sh -u`, the following error is returned:

```
python3: can't open file 'path/to/file/update_odbc_path.py': [Errno 2] No such file or directory
```

### OS:

Ubuntu

### DuckDB Version:

23.02

### DuckDB Client:

ODBC

### Full Name:

R. Goubet

### Affiliation:

Private

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Seems to not properly bundle https://github.com/duckdb/duckdb/blob/main/tools/odbc/linux_setup/update_odbc_path.py then?
