### ISSUE TITLE
Export to Parquet file with encryption

### ISSUE THREAD

**Issue by alexandroid11** [duckdb/duckdb#10752]
### What happens?

Export to encrypted Parquet file failed with Error: Invalid Error: Unable to generate random data for Windows DuckDB client

### To Reproduce

I'm doing very simple test for .10 version on fresh DuckDB client on windows instance.
(Downloaded latest version with winget install DuckDB.cli )

```SQL
create table md (Id int);
select * from md;
```
Output:
```
┌────────┐
│ Id │
│ int32 │
├────────┤
│ 0 rows │
└────────┘
```
```SQL
insert into md (Id) values (1);
insert into md (Id) values (2);
select * from md;
```
Output:
```
┌───────┐
│ Id │
│ int32 │
├───────┤
│ 1 │
│ 2 │
└───────┘
```
```SQL
PRAGMA add_parquet_key('key256', '01234567891123450123456789112345');
```
Output:
```
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows │
└─────────┘
```
```SQL
COPY md TO 'tbl.parquet' (ENCRYPTION_CONFIG {footer_key: 'key256'});
```
Output:
```
Error: Invalid Error: Unable to generate random data
```

I tried with nightly build with the same results.
Also tried to use .open test.db first , also the same error.

### OS:

Windows 10 Pro x64

### DuckDB Version:

0.10.0

### DuckDB Client:

Win DuckDB.cli

### Full Name:

Alex Nikitin

### Affiliation:

Partners Intl

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, I could indeed reproduce this on Windows (Win11, DuckDB installed via WinGet).
