### ISSUE TITLE
IndexError: index 2001 is out of bounds exception during dataframe registration

### ISSUE THREAD

**Issue by Piotr-Wagner** [duckdb/duckdb#10750]
### What happens?

An exception (IndexError: index 2001 is out of bounds for axis 0 with size 2001) is raised during registering pandas data frame with 2001 rows (and any 2001 + 2n where 0, 1, 2 ...) rows having None value in any column in the last row.

### To Reproduce

```py
import pandas as pd
import duckdb

if __name__ == '__main__':

    max_row_number = 2000
    ids = []
    contents = []

    for i in range(0, max_row_number):
        contents.append(None)
        ids.append(i)

    contents.append(None)
    ids.append(max_row_number)

    content_df = {"id":ids, "content" : contents}

    pdf = pd.DataFrame(data=content_df)
    print(max_row_number)

    con = duckdb.connect(database=":memory:")

    con.register("content", pdf)
```

### OS:

Win 11

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Piotr Wagner

### Affiliation:

Trylobit

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, we'll take a look!

**Comment by Piotr-Wagner** [comment]
Thank you

**Comment by mferryRV** [comment]
I'm still getting an index out of bounds error in Python 0.10.0 when I string together multiple select statements converted to dfs. Converting to `.fetchnumpy()` instead of `.df()` resolves the error.

Unfortunately I'm not able to share a reproducible error instruction, but wanted to at least share a quick fix for those facing this error.

**Comment by Mytherin** [comment]
Do you still get the error if you run `python3 setup.py install --pre --upgrade` to install the latest nightly?
