### ISSUE TITLE
Ignore_errors causes empty result in read_csv

### ISSUE THREAD

**Issue by b-schmeling** [duckdb/duckdb#10769]
### What happens?

Using `ignore_errors=true` in read_csv results in an empty result set where loading without that option returns data. 

### To Reproduce

Use file: [titanic.csv](https://github.com/duckdb/duckdb/files/14348045/titanic.csv)

```python
import duckdb

if __name__ == "__main__":
    res = duckdb.connect().execute(
        "SELECT * FROM read_csv('titanic.csv', ignore_errors=true)"
    )
    print(res.fetch_df())


```

### OS:

arm64

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Bethany Schmeling

### Affiliation:

Datachat

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by b-schmeling** [comment]
Thanks for the fix! Are there any plans to patch this issue?

**Comment by pdet** [comment]
> Thanks for the fix! Are there any plans to include this in 0.10.1?

Yes, anything that goes into the `main` branch will be released in the next release :-).

To give a bit of context to this issue, the `ignore_errors` flag also affects CSV Sniffing, which could cause the wrong dialect options to be picked. If you have a situation where you need to always toggle that flag to true, a possible workaround would be to manually define the dialect, with the quotes, delimiter, and escape options!
