### ISSUE TITLE
Loading a CSV file with large number of columns takes extremely long time.

### ISSUE THREAD

**Issue by lkordos** [duckdb/duckdb#10770]
### What happens?

The loading of a large CSV file takes too much time. Here are the specs of the file and the environment I am using:

OS: Windows 11
Lang: C++
Duckdb: 0.8.2
CSV:	15 781 columns, 298 rows
CSV has a header: YES
Size:  ~30MB
Content type: all values are decimal

Here are some execution time measurements:

1/
`SELECT * FROM 'aa.csv'`
60 min

2/
`SELECT * FROM read_csv_auto('aa.csv', HEADER=TRUE, ALL_VARCHAR=TRUE, DELIMITER=',')`
15 min

3/
`COPY tbl FROM 'aa.csv' (DELIMITER ',', HEADER, ALL_VARCHAR)`
I aborted the process after few minutes

Using the MS Excel, the loading time is ~1 sec.

Is there any way to speed the loading up? Is this an expected behavior or is this a symptom of an issue in the duckdb?

### To Reproduce

Create a CSV file with 15 000 columns and 300 rows on WINDOWS system and execute the SQL, mentioned above, using C++ API.

### OS:

Windows 11

### DuckDB Version:

0.8.2

### DuckDB Client:

C++

### Full Name:

Lubomir Kordos

### Affiliation:

Lukosoft Canada

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello, can you please try the latest version, v0.10.0? The CSV reader has been almost completely rewritten.

**Comment by lkordos** [comment]
Hello, I just tried it with v0.10.0. it is much better. The loading time is down to ~5min for query 2/ (There is a breaking change in the argument name, delimiter vs delim).

However, in comparison with the MS Excel, duckdb loading is magnitude slower. Excel loads the same file in no time.

**Comment by szarnyasg** [comment]
Thanks for giving it a try with DuckDB v0.10. I don't think we can do much about this issue at the moment:

1) Having this many columns is a rare cornercase and sounds somewhat of a data modelling issue.
If having 298 rows (like in your example) is normal for your use case, then I would consider transposing the file so it has 298 columns an ~16k rows. This is doable in Excel using Pivot or via some Bash/Python script. Sure enough, pre-processing data to be loadable to DuckDB is unusual but this is an unusual data set.

2) To improve the speed of DuckDB's CSV reader on similar files, we need a reproducible example.

As an alternative, you may try [directly reading the file using `read_text`](https://duckdb.org/docs/guides/import/read_file) and splitting the rows using string split. This should be fast. Then how you model your data is up to the queries you'd like to evaluate on it.

**Comment by lkordos** [comment]
Thanks, I will give it a try.
I can't do the transposing as the data come from a data scientist and the format is essential.

**Comment by szarnyasg** [comment]
One thing you can try is to turn off the CSV sniffer by passing [`auto_detect = false`](https://duckdb.org/docs/data/csv/overview). However, this requires you to manually specify the schema with a (long) `CREATE TABLE` statement.

**Comment by eknowles** [comment]
I have a similar issue, I'm imported compressed partitioned csvs. the test has 10 files, 2.68gb compressed.

0.9.2 runs it 3x faster than 0.10.0

```
hyperfine --runs 5 "./duckdb_9 -c '.read command.sql'" "./duckdb_10 -c '.read command.sql'"
Benchmark 1: ./duckdb_9 -c '.read command.sql'
  Time (mean ± σ):      8.857 s ±  0.586 s    [User: 76.792 s, System: 2.542 s]
  Range (min … max):    8.257 s …  9.560 s    5 runs

Benchmark 2: ./duckdb_10 -c '.read command.sql'
  Time (mean ± σ):     31.772 s ±  0.636 s    [User: 48.087 s, System: 1.943 s]
  Range (min … max):   31.024 s … 32.712 s    5 runs

Summary
  ./duckdb_9 -c '.read command.sql' ran
    3.59 ± 0.25 times faster than ./duckdb_10 -c '.read command.sql'
```

```
CREATE
OR REPLACE TABLE mydata AS
SELECT id,
       <redacted>,
       epoch_ms(timestamp) AS timestamp
FROM read_csv('/mydata/month=07/day=20/*.gz', SEP=',', HEADER= False, COLUMNS={
    <redacted>
});
```

**Comment by szarnyasg** [comment]
@eknowles thanks for reporting this regression. Is there a chance you can share you're data? (Sharing privately is also fine.)
