### ISSUE TITLE
INSERT OR REPLACE complains about multiple unique indexes when there is only one unique index

### ISSUE THREAD

**Issue by dbeer1** [duckdb/duckdb#10772]
### What happens?

The INSERT OR REPLACE statement fails with an error about multiple unique indexes when there are multiple indexes but only one unique index. This seems to be a regression in 0.10.0, the same query works fine in 0.9.2

### To Reproduce

The following statements should reproduce the error:
```
CREATE TABLE test (a integer primary key, b integer) ;
CREATE INDEX test_index ON test (b);
INSERT OR REPLACE INTO test (a, b) VALUES (1, 2);
```

On 0.10.0 and nightly build:
```
Error: Binder Error: Conflict target has to be provided for a DO UPDATE operation when the table has multiple UNIQUE/PRIMARY KEY constraints
```

On 0.9.2 this executes without an error.

### OS:

Linux x64

### DuckDB Version:

0.10.0

### DuckDB Client:

Same behavior in duckdb-cli and python bindings

### Full Name:

Daniel Beer

### Affiliation:

Bloomberg LP

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by dbeer1** [comment]
Potentially related to code changes in https://github.com/duckdb/duckdb/pull/9730

**Comment by Tishj** [comment]
Primary key counts as an index in this context, so this is expected

**Comment by dbeer1** [comment]
> Primary key counts as an index in this context, so this is expected

Right, but the other index ("test_index") is non-unique. The primary key is the only unique index on the table.

**Comment by dbeer1** [comment]
In other words, the "INSERT OR REPLACE" statement is not ambiguous as the only column that can conflict is "a" due to the primary key. "b" can never cause a conflict as it has no unique index on it.

Btw, thanks for taking a look so quickly all!

**Comment by Tishj** [comment]
> Potentially related to code changes in #9730

Yes you're right, this is expecting all these indexes to be unique, which is not true
We should fix this 👍
