### ISSUE TITLE
Python connection does not support Array type

### ISSUE THREAD

**Issue by paradiddle-luuk** [duckdb/duckdb#10785]
### What happens?

When I execute a query with `con = duckdb.connect(...); con.execute(query)` that uses the Array type it fails with:

_duckdb.duckdb.NotImplementedException: Not implemented Error: Unsupported type: "FLOAT[3]"_

note: no relevant extension was found related to the Array type and no extension was loaded into the connection.

### To Reproduce

* run the minimal python script below
* see that the NotImplementedException is raised

Minimal python script that reproduces the error:

```
import duckdb


with duckdb.connect() as con:

    con.execute("CREATE TABLE embeddings (id INTEGER, embedding FLOAT[3]);")
    con.execute("INSERT INTO embeddings VALUES (1, [1.0, 2.0, 3.0]);")

    result = con.execute("SELECT id, embedding FROM embeddings;")
    print(result.fetchall())

```

### OS:

Ubuntu 22.04

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Luuk van der Velden

### Affiliation:

Codebeez

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Where this breaks is in result collection, that's why `.sql(...)` didn't result in the error yet, when you use `.fetchall` it'll run into the same issue

**Comment by luuk-codebeez** [comment]
thank you @Maxxen ! Looking forward to your updates.

**Comment by luuk-codebeez** [comment]
@szarnyasg 

Here is a complete reproducible python script on version 0.10.1 (nightly)

`import duckdb


with duckdb.connect() as con:

    con.execute("CREATE TABLE embeddings (id INTEGER, embedding FLOAT[3]);")
    con.execute("INSERT INTO embeddings VALUES (1, [1.0, 2.0, 3.0]);")

    result = con.execute("SELECT id, CAST(embedding AS FLOAT[3]) FROM embeddings;")
    print(result.fetchall())
`

**Comment by szarnyasg** [comment]
@luuk-codebeez – thanks! I could reproduce the error by running the script.
