### ISSUE TITLE
Bug in map to Arrow conversion.

### ISSUE THREAD

**Issue by yiyuanliu** [duckdb/duckdb#10795]
### What happens?

When `arrow_large_buffer_size` is enabled, conversion of map data type to Arrow results in incorrect data. It looks like DuckDB uses 64-bit offsets when generating Arrow MapArray, but MapArray only supports 32-bit offsets. There is no LargeMapArray type in Arrow.

### To Reproduce

```
import duckdb

# correct
arrow = duckdb.sql("select map(['non-inlined string', 'test', 'duckdb'], [42, 1337, 123])").to_arrow_table()
print(arrow)

# incorrect
duckdb.sql("set arrow_large_buffer_size=true")
arrow = duckdb.sql("select map(['non-inlined string', 'test', 'duckdb'], [42, 1337, 123])").to_arrow_table()
print(arrow)
```

```
pyarrow.Table
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): map<string, int32>
  child 0, entries: struct<key: string not null, value: int32> not null
      child 0, key: string not null
      child 1, value: int32
----
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): [[keys:["non-inlined string","test","duckdb"]values:[42,1337,123]]
```
```
pyarrow.Table
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): map<large_string, int32>
  child 0, entries: struct<key: large_string not null, value: int32> not null
      child 0, key: large_string not null
      child 1, value: int32
----
map(main.list_value('non-inlined string', 'test', 'duckdb'), main.list_value(42, 1337, 123)): [[keys:[]values:[]]]
```

### OS:

ubuntu 20.04

### DuckDB Version:

main

### DuckDB Client:

python

### Full Name:

Yiyuan Liu

### Affiliation:

High-Flyer AI

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks, I think you're right
This is not mentioned on https://arrow.apache.org/docs/format/Columnar.html which I think it should be, perhaps we should raise an issue with them as well
