### ISSUE TITLE
Importing large dataframes causes core dump

### ISSUE THREAD

**Issue by rhollen** [duckdb/duckdb#10790]
### What happens?

When writing large dataframes with a sequence for generating an autoincrement id, the following error occurs:

`libc++abi: terminating due to uncaught exception of type duckdb::InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1`

If you remove the sequence column, this issue goes away

### To Reproduce

```python
import duckdb
import pandas as pd
import numpy as np

num_rows = 2000000
num_columns = 10

con = duckdb.connect()
con.execute("CREATE SEQUENCE id_seq")
column_names = ',\n'.join([f'column_{i} FLOAT' for i in range(1, num_columns + 1)])
create_table_query = f"""
CREATE TABLE my_table (
    id INTEGER DEFAULT nextval('id_seq'),
    {column_names}
)
"""
con.execute(create_table_query)


for i in range(20):
    data = np.random.rand(num_rows, num_columns)
    columns = [f'Column_{i+1}' for i in range(num_columns)]
    df = pd.DataFrame(data, columns=columns)
    df_columns = ", ".join(df.columns)
    con.execute(f"INSERT INTO my_table ({df_columns}) SELECT * FROM df")
    print(f"inserted {i}")
    con.commit()
```

### OS:

macos sonoma 14.3

### DuckDB Version:

0.9.2, 0.10.1-dev240

### DuckDB Client:

Python

### Full Name:

Richmond Hollen

### Affiliation:

Ouster, Inc

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @rhollen, thanks, this is indeed reproducible!

**Comment by rhollen** [comment]
btw, we have a workaround in our use case that works. If you break the dataframe into chunks of 100k rows, it works with the sequence in place. I'm also considering removing the default and writing the sequence to the dataframe itself, which should also fix it, although I haven't tested that.
