### ISSUE TITLE
Lists leak disk space in persistent databases.

### ISSUE THREAD

**Issue by michael-hlavacek** [duckdb/duckdb#10803]
### What happens?

Using lists of various data types seems to be leaking disk space when using persistent DBs.

When a table containing lists is created and immediately dropped, not all disk space seems to be freed. This can be reproduced by doing a simple script which repeatedly creates table with some dummy data and immediately drops it. (See the reproduction steps for the complete script). The script produces a csv [sizes.csv](https://github.com/duckdb/duckdb/files/14374387/sizes.csv) with the evolution of the size of the DB file and the size of the WAL.

When plotted, the sizes produce the following plot:

![sizes](https://github.com/duckdb/duckdb/assets/58769376/af54b726-d0b7-45a8-8c36-8e6cd00e61d2)

It seems that every now and then, some disk space gets claimed if a table contains a list of things. More over, the frequency of the disk claims is the same as the frequency of WAL syncs. However, if the table contains just regular text column, the file size stays the same.

After the script is finished, we end up with databases which are empty (contain no tables), but have several megabytes each. On my machine, this resulted in the following sizes:

| db | size|
|-|-|
| lists_of_ints.duckdb | 2.6M |
| lists_of_texts.duckdb | 7.3M |
| plain_texts.duckdb | 268K |

This makes working with long-lived persistent databases somewhat difficult. 

As a workaround a the issue can be sidestepped by storing a JSON instead of a list. JSONs do not seem to suffer from this problem, so if one has a datatype serializable to JSON and back it can be used as an intermediate storage format.

### To Reproduce

Use the following script to obtain empty dabatase files of _very_ non-empty sizes; and a csv with the progress of said sizes.

```python
import csv
from pathlib import Path

import duckdb

REPEATS = 100_000

lists_of_texts_db_path = Path("lists_of_texts.duckdb")
lists_of_texts_wal_path = Path("lists_of_texts.duckdb.wal")
lists_of_texts_db_path.unlink(missing_ok=True)
lists_of_texts_wal_path.unlink(missing_ok=True)
lists_of_texts_db_conn = duckdb.connect(str(lists_of_texts_db_path))

lists_of_ints_db_path = Path("lists_of_ints.duckdb")
lists_of_ints_wal_path = Path("lists_of_ints.duckdb.wal")
lists_of_ints_db_path.unlink(missing_ok=True)
lists_of_ints_wal_path.unlink(missing_ok=True)
lists_of_ints_db_conn = duckdb.connect(str(lists_of_ints_db_path))

plain_texts_db_path = Path("plain_texts.duckdb")
plain_texts_wal_path = Path("plain_texts.duckdb.wal")
plain_texts_db_path.unlink(missing_ok=True)
plain_texts_wal_path.unlink(missing_ok=True)
plain_texts_db_conn = duckdb.connect(str(plain_texts_db_path))

with Path("sizes.csv").open("w", newline="") as size_csv:
    size_writer = csv.writer(size_csv)
    size_writer.writerow(["iteration", "kind", "size"])

    for i in range(REPEATS):
        lists_of_texts_db_conn.execute(f"create table foo_{i} as select [uuid()]::text[] from generate_series(1, 100);")
        lists_of_texts_db_conn.execute(f"drop table foo_{i};")
        size_writer.writerow([i, "lists_of_texts_db", lists_of_texts_db_path.stat().st_size])
        size_writer.writerow([i, "lists_of_texts_wal", lists_of_texts_wal_path.stat().st_size])

        lists_of_ints_db_conn.execute(f"create table foo_{i} as select [random()]::int[] from generate_series(1, 100);")
        lists_of_ints_db_conn.execute(f"drop table foo_{i};")
        size_writer.writerow([i, "lists_of_ints_db", lists_of_ints_db_path.stat().st_size])
        size_writer.writerow([i, "lists_of_ints_wal", lists_of_ints_wal_path.stat().st_size])

        plain_texts_db_conn.execute(f"create table foo_{i} as select uuid()::text from generate_series(1, 100);")
        plain_texts_db_conn.execute(f"drop table foo_{i};")
        size_writer.writerow([i, "plain_texts_db", plain_texts_db_path.stat().st_size])
        size_writer.writerow([i, "plain_texts_wal", plain_texts_wal_path.stat().st_size])
```

### OS:

Ubuntu x64 in WSL on Windows 11

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Míma Hlaváček

### Affiliation:

Blindspot.ai

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @michael-hlavacek, thanks for reporting this with a detailed reproducer. Currently `DROP` does not necessarily reclaim space, see the documentation: https://duckdb.org/docs/sql/statements/drop#limitations-on-reclaiming-disk-space
That said, I'll keep this issue open for future investigations.

**Comment by michael-hlavacek** [comment]
What I get from the docs is that the regions get marked as free space, which gets potentially reused later. This is what happens in all usual cases. However, in the reproduction case with lists we have data of constant size which get dropped and re-inserted. I have cases in our app where an empty DB grows to over 1GB in size even though we keep rotating a couple of kB worth of data. Which leads me to believe that what happens underneath is something else than a simple free region marking.

**Comment by szarnyasg** [comment]
Thanks for clarifying, we'll take a look!

**Comment by michael-hlavacek** [comment]
Thanks very much! Just wanted to add that I _really_ appreciate the work you all are putting into DuckDB 🦆 🥇 ❤️
