### ISSUE TITLE
The performance of the join operation in version 0.10.0 has significantly decreased

### ISSUE THREAD

**Issue by richand112233** [duckdb/duckdb#10802]
### What happens?

The performance of the join operation in version 0.10.0 has significantly decreased
The performance of the df() function also seems to have decreased.
**For calculations that require a lot of looping, it may increase the runtime by around 1x.**
My pandas version is 2.2.0

### To Reproduce

[df_trade.csv](https://github.com/duckdb/duckdb/files/14374494/df_trade.csv)
[df_pos.csv](https://github.com/duckdb/duckdb/files/14374495/df_pos.csv)

```
import pandas as pd
import duckdb,time

df_trade = pd.concat([pd.read_csv('df_trade.csv')]*100)
df_pos = pd.read_csv('df_pos.csv')

t = time.time()
for i in range(1000):
    duckdb.sql(f"""
        select p.code
        from 
            df_pos as p
            full join df_trade as t on p.code = t.code
    """).df()
print(time.time()-t)
```

to df time used: (duckdb.sql().df())
v0.10.0 - 5.1716s
v0.9.2  - 2.1184s

not to df time used:
v0.10.0 - 2.3784s
v0.9.2  - 0.8652s

### OS:

windows

### DuckDB Version:

0.10.0

### DuckDB Client:

python

### Full Name:

richand

### Affiliation:

0

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by richand112233** [comment]
Hello @szarnyasg, I have updated the issue.

> Hello @richand112233, thanks for reporting this! Can you please send us the 2 input dataframes as raw CSV files? Pasting or drag'n'dropping them to the GitHub issue would work fine.

**Comment by szarnyasg** [comment]
The query plans are identical, so it's unlikely that this is an optimizer issue:

```python
print(f"DuckDB version: {duckdb.__version__}")
print(duckdb.sql("""select p.code
        from 
        df_pos as p
        full join df_trade as t on p.code = t.code""").explain())
```

```
DuckDB version: 0.9.2
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            code           │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         HASH_JOIN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            FULL           │
│        code = code        ├──────────────┐
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │              │
│          EC: 500          │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│        PANDAS_SCAN        ││        PANDAS_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            code           ││            code           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 5           ││          EC: 500          │
└───────────────────────────┘└───────────────────────────┘
```

```
DuckDB version: 0.10.0
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            code           │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         HASH_JOIN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            FULL           │
│        code = code        ├──────────────┐
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │              │
│          EC: 500          │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│        PANDAS_SCAN        ││        PANDAS_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            code           ││            code           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          EC: 500          ││           EC: 5           │
└───────────────────────────┘└───────────────────────────┘
```

**Comment by Tmonster** [comment]
Hi @richand112233,

Can you provide some details about the available memory and number of cores for your machine?

Thanks!

**Comment by richand112233** [comment]
> Hi @richand112233,
> 
> Can you provide some details about the available memory and number of cores for your machine?
> 
> Thanks!

Hi @Tmonster ,
CPU: i7-14700K 28 cores    (I tested in "PRAGMA threads={max(int(multiprocessing.cpu_count()/2), 1)};")
Memory: 32Gx2 6000MHz    (The test did not reach the memory_limit config)

**Comment by Tmonster** [comment]
Hi Richand112233,

Thanks! We've had a couple of regressions pop up/reported by users that we are going to be looking into. Hopefully we can get this fixed in an upcoming bug fix release 👍

**Comment by Tmonster** [comment]
Hi @richand112233,

I've been investigating this a bit more, and I think the culprit is a re-work in how we materialize reads from dataframes. To provide a workaround though, I would suggest ingesting whatever CSV's you have directly into a duckdb in-memory database. This should get rid of the regression.

something like below will work

```
import pandas as pd
import duckdb,time

t = time.time()
con = duckdb.connect()

# This doesn't replicate df_trade 100 times, but you get the idea
con.sql("create table df_trade as select * from 'df_trade.csv'")
con.sql("create table df_pos as select * from 'df_pos.csv'")
for i in range(1000):
    con.sql(f"""
            select p.code
        from 
            df_pos as p
            full join df_trade as t on p.code = t.code""").df()
print(time.time()-t)
```

**Comment by richand112233** [comment]
> Hi @richand112233,
> 
> I've been investigating this a bit more, and I think the culprit is a re-work in how we materialize reads from dataframes. To provide a workaround though, I would suggest ingesting whatever CSV's you have directly into a duckdb in-memory database. This should get rid of the regression.
> 
> something like below will work
> 
> ```
> import pandas as pd
> import duckdb,time
> 
> t = time.time()
> con = duckdb.connect()
> 
> # This doesn't replicate df_trade 100 times, but you get the idea
> con.sql("create table df_trade as select * from 'df_trade.csv'")
> con.sql("create table df_pos as select * from 'df_pos.csv'")
> for i in range(1000):
>     con.sql(f"""
>             select p.code
>         from 
>             df_pos as p
>             full join df_trade as t on p.code = t.code""").df()
> print(time.time()-t)
> ```

Thanks for your response. This provides a good solution. 👍
However, when there are many temporary dataframes, it may increase code complexity and memory overhead. 
I am looking forward to the future versions of DuckDB ~
