### ISSUE TITLE
Window function results should not be affected by row order when using INTERVAL RANGE with dates

### ISSUE THREAD

**Issue by melody-lui3** [duckdb/duckdb#10809]
### What happens?

When using a window function with range such as `RANGE BETWEEN INTERVAL 3 DAYS PRECEDING AND INTERVAL 1 DAYS`, duckdb takes the order of rows into account instead of purely the date range specified, and produces different result from the windows function based on the row order. 

This shouldn't happen because the aggregate function in window should be applied on all the rows with dates in range, rather than being affected by the row order. it seems like window function is only applied to preceding rows that satisfy the interval constraint.

This issue only starts appearing from duckdb version `0.9.0` and above. 

### To Reproduce

given table:
| id | requested_date | city | wait_time |
|-----------|--------------------------|------------------------|---------------------|
| 0         | 2023-01-05               | San Francisco       | 2925            |
| 1         | 2023-01-03               | San Francisco       | 755             |
| 2         | 2023-01-03               | San Francisco       | 2880            |
| 3         | 2023-01-05               | San Francisco       | 1502            |
| 4         | 2023-01-03               | San Francisco       | 2900            |
| 5         | 2023-01-01               | San Francisco       | 1210            |
| 6         | 2023-01-04               | San Francisco       | 200             |
| 7         | 2023-01-02               | San Francisco       | 980             |
| 8         | 2023-01-02               | San Francisco       | 430             |
| 9         | 2023-01-05               | San Francisco       | 2999            |
| 10        | 2023-01-01               | San Francisco       | 856             |
| 11        | 2023-01-02               | San Francisco       | 490             |
| 12        | 2023-01-02              | San Francisco       | 720             |

If we randomize the row order in a table using 
`SELECT * FROM TABLE ORDER BY random()`

Then running this query on the below table will give different results
`SELECT "requested_date",
       "city",
       (min("wait_time"::DOUBLE) OVER win_3d)::DOUBLE
  FROM table WINDOW win_3d AS (PARTITION BY "city" ORDER BY requested_date ASC RANGE BETWEEN INTERVAL 3 DAYS PRECEDING AND INTERVAL 1 DAYS PRECEDING)
 ORDER BY "requested_date",
          "city"
`

### OS:

OS 14.1, Apple M3 Pro

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Melody Lui

### Affiliation:

Delphina

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by cmdlineluser** [comment]
The reproducer as runnable Python if it helps:

<details><summary>repro.py</summary>

```python
import duckdb
import io

def example_db():
    f = io.BytesIO(b"""
    id,requested_date,city,wait_time
    0,2023-01-05,San Francisco,2925
    1,2023-01-03,San Francisco,755
    2,2023-01-03,San Francisco,2880
    3,2023-01-05,San Francisco,1502
    4,2023-01-03,San Francisco,2900
    5,2023-01-01,San Francisco,1210
    6,2023-01-04,San Francisco,200
    7,2023-01-02,San Francisco,980
    8,2023-01-02,San Francisco,430
    9,2023-01-05,San Francisco,2999
    10,2023-01-01,San Francisco,856
    11,2023-01-02,San Francisco,490
    12,2023-01-02,San Francisco,720
    """.strip()
    )

    return duckdb.read_csv(f)


def run_query():
    return duckdb.sql("""
    from 
       (from db order by random())
    select 
       "requested_date", 
       "city", 
       (min("wait_time"::double) over win_3d)::double
    window win_3d as (
       partition by "city" 
       order by requested_date asc 
       range between interval 3 days preceding and interval 1 day preceding
    ) 
    order by "requested_date", "city" 
    """)
    
db = example_db()

print(
    [ 
        len(set(tuple(run_query().fetchall()) for _ in range(5))) 
        for _ in range(20)
    ]
)
# [3, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 3, 5, 5, 4, 5]
```

</details>

```python
print([ 
    len(set(tuple(run_query().fetchall()) for _ in range(5))) 
    for _ in range(20)
])
# [3, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 3, 5, 5, 4, 5]
```
