### ISSUE TITLE
Connecting from SAS via SAS/ACCESS Interface to JDBC throws multiple ERROR: java.sql.SQLFeatureNotSupportedException: 

### ISSUE THREAD

**Issue by ahmedanadwc** [duckdb/duckdb#10805]
### What happens?

Attempting to establish connection from SAS Software using the latest DuckDB JDBC jar file ([duckdb_jdbc-0.10.0.jar](https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/0.10.0/duckdb_jdbc-0.10.0.jar)), and SAS/ACCESS Interface to JDBC, generates/throws multiple java.sql.SQLFeatureNotSupportedException Error messages!

Here are some trace call output:

JDBC: DatabaseMetaData#getNumericFunctions
JDBC: Error calling DatabaseMetadata#getNumericFunctions(): java.sql.SQLFeatureNotSupportedException: getNumericFunctions
JDBC: DatabaseMetaData#getStringFunctions
JDBC: Error calling DatabaseMetadata#getStringFunctions(): java.sql.SQLFeatureNotSupportedException: getStringFunctions
JDBC: DatabaseMetaData#getTimeDateFunctions
JDBC: Error calling DatabaseMetadata#getTimeDateFunctions(): java.sql.SQLFeatureNotSupportedException: getStringFunctions
JDBC: Connection#getIdentifierQuoteString
JDBC: DatabaseMetaData#storesLowerCaseIdentifiers
JDBC: DatabaseMetaData#supportsSchemasInDataManipulation
JDBC: Connection#getSchema
JDBC: DatabaseMetaData#supportsOpenStatementsAcrossCommit
JDBC: DatabaseMetaData#getTypeInfo

ERROR: java.sql.SQLFeatureNotSupportedException: getTimeDateFunctions
ERROR:  at org.duckdb.DuckDBDatabaseMetaData.getTimeDateFunctions(DuckDBDatabaseMetaData.java:190)
ERROR: java.sql.SQLFeatureNotSupportedException: getTypeInfo
ERROR:  at org.duckdb.DuckDBDatabaseMetaData.getTypeInfo(DuckDBDatabaseMetaData.java:964)
ERROR: Error retrieving DatabaseMetaData: java.sql.SQLFeatureNotSupportedException: getTypeInfo

Typically, when SAS/ACCESS to JDBC makes the initial connection, one of the first things it does is get the DatabaseMetadata and query for the JDBC escape functions. This is the call DatabaseMetaData#getNumericFunctions(), etc.
https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getNumericFunctions

With a "compliant JDBC driver", such as the PostgreSQL JDBC driver, here are sample of the trace call produced upon successful connection to PostgreSQL database from SAS using the SAS/ACCESS Interface to JDBC.

JDBC: DatabaseMetaData#supportsBatchUpdates= TRUE
JDBC: DatabaseMetaData#getIdentifierQuoteString= """
JDBC: DatabaseMetaData#storesLowerCaseIdentifiers= TRUE
JDBC: DatabaseMetaData#supportsCatalogsInDataManipulation= FALSE
JDBC: DatabaseMetaData#supportsSchemasInDataManipulation= TRUE
JDBC: DatabaseMetaData#supportsResultSetConcurrency(1004, 1008)= TRUE
JDBC: DatabaseMetaData#getNumericFunctions=
abs,acos,asin,atan,atan2,ceiling,cos,cot,degrees,exp,floor,log,log10,mod,pi,power,radians,round,sign,sin,sqrt,tan,truncate
JDBC: DatabaseMetaData#getStringFunctions= ascii,char,concat,lcase,left,length,ltrim,repeat,rtrim,space,substring,ucase,replace
JDBC: DatabaseMetaData#getTimeDateFunctions=
curdate,curtime,dayname,dayofmonth,dayofweek,dayofyear,hour,minute,month,monthname,now,quarter,second,week,year,timestampadd
JDBC: Connection#getSchema= public

DatabaseMetaData (Java Platform SE 8 )

### To Reproduce

Pre-requisites
- A deployment of SAS 9.4 M7/M8 Software with SAS/ACCESS Interface to JDBC licensed (Windows/Linux)
- Once the SAS session is started, use the following statement to attempt establishing a connection
   **libname x JDBC driverclass="org.duckdb.DuckDBDriver" URL="jdbc:duckdb::memory:" classpath="/[SomePath]/duckdb_jdbc-0.10.0.jar";**

### OS:

RHEL Linux

### DuckDB Version:

0.10.0

### DuckDB Client:

Java

### Full Name:

Ahmed Al-Attar

### Affiliation:

AnA Data Warehousing Consulting, LLC

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ahmedanadwc** [comment]
The attachment spreadsheet lists the JDBC API's used by SAS/ACCESS Interface to JDBC.
[SAS_jdbc_api_rqrmnts.xlsx](https://github.com/duckdb/duckdb/files/14378009/SAS_jdbc_api_rqrmnts.xlsx)

**Comment by szarnyasg** [comment]
Hi @ahmedanadwc, thanks for sharing the requirements document. Unfortunately, this request falls outside of the scope of our [community support policy](https://duckdblabs.com/news/2023/10/02/support-policy). We are happy to review PRs implementing the required features. Alternatively, please look into [support options](https://duckdblabs.com/support/) and reach out to us.

**Comment by ahmedanadwc** [comment]
Hi @szarnyasg, 
Thank you for your response. How would I go about putting-in/submitting the PRs for implementing the required features?
In all honesty I strongly believe, implementing these features would increase DuckDB adoption and integration within the SAS 9.4 eco-system, as it fills-in a highly needed functionality gap :-)
