### ISSUE TITLE
read_json_auto schema detection inconsistency 

### ISSUE THREAD

**Issue by zsoltc** [duckdb/duckdb#10823]
### What happens?

Hi,

`read_json_auto` schema detection seems to depend on percentage of objects with fields filled out.

### To Reproduce

Executing the following statement:

```python
import duckdb
duckdb.sql("describe select * from read_json_auto('test.json')").show()
```

With `test.json` as below (10 rows):
```json
[
  { "a": 1 },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
]
``` 

Output:
```
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ a           │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

With `test.json` as below (11 rows):
```json
[
  { "a": 1 },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
]
```

Output:
```
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ json        │ JSON        │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

It seems that if less than 10% of objects contain a field, then the object will be detected as JSON.
Is this intentional? Can this behaviour be changed with some config so in the second case the field `a` would be detected as `BIGINT`, just like in the first case?
Thank you!

Tagging @NielsKorschinsky

### OS:

MacOS

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Zsolt Czinege

### Affiliation:

IBM

### Have you tried this on the latest main branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @zsoltc, thanks for opening this issue. I could reproduce it – we'll take a look.

**Comment by Maxxen** [comment]
The `read_json_auto` function has an undocumented `field_appearance_threshold = <DOUBLE>` option which can control this behavior. The default = 0.1. From what I gather from the internal comments, basically if the number of appearances divided by the sample size is less than this threshold for any given field the field gets generalized.

So if you can change it to be more sensitive, e.g.

```
SELECT COUNT(*) FROM read_json_auto('./test.json');
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│           11 │
└──────────────┘

DESCRIBE SELECT * FROM read_json_auto('./test11.json', field_appearance_threshold = 0.01);
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ a           │ BIGINT      │ YES     │         │         │         │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

**Comment by zsoltc** [comment]
@Maxxen 
Thank you, working perfectly!
