### ISSUE TITLE
Unable detect 'date' datatype from a csv file 

### ISSUE THREAD

**Issue by koulika** [duckdb/duckdb#10820]
### What happens?

It is not able to detect "January 10, 2012" as Date rather it is considering it as Varchar. Suggest a way to convert this to Date datatype in csv file

### To Reproduce

 data=duckdb.sql("SELECT * FROM read_csv('google play store data.csv', dateformat = '%Y/%m/%d')")## it is not changing the datatype from VARCHAR to DATE
Output:
["{'App': 'VARCHAR', 'Category': 'VARCHAR', 'Rating': 'DOUBLE', 'Reviews': 'VARCHAR', 'Size': 'VARCHAR', 'Installs': 'VARCHAR', 'Type': 'VARCHAR', 'Price': 'VARCHAR', 'Content Rating': 'VARCHAR', 'Genres': 'VARCHAR', 'Last Updated': 'VARCHAR', 'Current Ver': 'VARCHAR', 'Android Ver': 'VARCHAR'}"]

### OS:

Windows 11 Pro, 22H2, 22621.3155

### DuckDB Version:

0.10.0

### DuckDB Client:

3.12.1

### Full Name:

K. Paul

### Affiliation:

IDEAS-TIH, Kolkata

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @koulika, the sniffer only auto-detects the datetime and timestamp formats listed in the documentation: https://duckdb.org/docs/data/csv/auto_detection#dates-and-timestamps

However, you can specify your own datetime format, see for CSV parsing, see:
https://duckdb.org/docs/sql/functions/dateformat.html#csv-parsing

**Comment by skandaramesh** [comment]
@szarnyasg seems like the read_csv( .., dateformat='%m/%d/%Y, %I:%M:%S %p') does not pick up this custom format setting. It only relies on one of the default ones, notice the difference between this custom format and the ISO format is a comma after the date. An example here is. -> as csv file with one field Created date = 7/2/2023, 08:32:45 PM. Is this expected behavior? It was working in the previous build with 0.9.2 and using read_csv_auto()

**Comment by skandaramesh** [comment]
Looks like the Select * from read_csv('SampleData.csv', header=true, dateformat='%m/%d/%Y, %-I:%-M %p' ) does not work in 0.10.0

SampleData.csv
ID,Date_Time
123,"1/2/2023, 12:33 PM"
124,"12/2/2023, 11:57 AM"

Note: the date format differs from ISO format 8601, this has a comma after the date.
