### ISSUE TITLE
Excel is launched after quitting cli

### ISSUE THREAD

**Issue by hboutou** [duckdb/duckdb#10835]
### What happens?

Switching output mode to excel and quitting cli launches Excel 

### To Reproduce

```
duckdb -c .excel
```

### OS:

macos 14.3.1 aarch64

### DuckDB Version:

v0.10.0

### DuckDB Client:

duckdb cli

### Full Name:

Hamza Boutou

### Affiliation:

personal

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @hboutou, thanks for raising this issue. This may be intended behaviour but I'll double-check (and document my findings). FWIW, it opens VS Code for me (on macOS).

**Comment by hannes** [comment]
This is expected behaviour, SQLite does the same
