### ISSUE TITLE
"FATAL Error: fsync failed!" when `COPY ... TO "/dev/stdout"` called through nodejs script

### ISSUE THREAD

**Issue by srenatus** [duckdb/duckdb#10849]
### What happens?

When I run the following duckdb script with a shell script, it'll succeed and output binary parquet data to stdout:
```sh
#!/bin/bash
duckdb :memory: <<EOF
copy (select * from range(100000) tbl(i)) to '/dev/stdout' (format parquet, use_tmp_file false)
EOF
```

*But* when I run the same script via a nodejs script, it'll somehow get wired up so that duckdb calls `fsync` on the target fd and it fails -- see "To Reproduce"

### Why?

For context -- why would someone want to do that kind of thing? -- this problem occurred to me when using a similar duckdb call in a bash script, to use it with https://github.com/observablehq/framework.

Turns out there are two workarounds: 
1. `COPY ... TO 'tmp.parquet'` followed by (in the bash script) `cat tmp.parquet && rm tmp.parquet`
2. leaving the `COPY TO` intact, but adding a `exit 0` afterwards: the duckdb call would still fail with the `fsync failed`, but the output is apparently written to the pipe before, and the `exit 0` will make the node script believe everything was OK. But this isn't desirable to keep around, since it could hide other problems.

### To Reproduce

```js
# t.js
import {spawn} from "node:child_process";
import {mkdir, open, readFile, rename, unlink} from "node:fs/promises";
import {WriteStream, createReadStream, existsSync, statSync} from "node:fs";

async function exec(cmd, args, output) {
  const subprocess = spawn(cmd, args, {windowsHide: true, stdio: ["ignore", "pipe", "inherit"]});
  subprocess.stdout.pipe(output);
  const code = await new Promise((resolve, reject) => {
    subprocess.on("error", reject);
    subprocess.on("close", resolve);
  });
  if (code !== 0) {
    throw new Error(`loader exited with code ${code}`);
  }
}

const tempPath = "test.tmp";
const tempFd = await open(tempPath, "w");
exec("sh", ["test.sh"], tempFd.createWriteStream({highWaterMark: 1024 * 1024}));
// same result for the direct call:
// const d = "duckdb";
// exec(d, [":memory", "-c", "copy (select * from range(10000) tbl(i)) to '/dev/stdout' (format parquet, use_tmp_file false)"], tempFd.createWriteStream({highWaterMark: 1024 * 1024}));
```

With the script above and nodejs 21, we'll get this:

```
$ node t.js     
Error: FATAL Error: fsync failed!
file:///Users/stephan/Sources/xyz/t.js:14
    throw new Error(`loader exited with code ${code}`);
          ^

Error: loader exited with code 1
    at exec (file:///Users/stephan/Sources/xyz/t.js:14:11)

Node.js v21.6.2
```

ℹ️ I've started looking into how to fix the problem, and this change seemed promising,

```diff
diff --git a/src/common/local_file_system.cpp b/src/common/local_file_system.cpp
index 3f2fc92114..c8843508d8 100644
--- a/src/common/local_file_system.cpp
+++ b/src/common/local_file_system.cpp
@@ -591,7 +591,7 @@ bool LocalFileSystem::ListFiles(const string &directory, const std::function<voi
 
 void LocalFileSystem::FileSync(FileHandle &handle) {
        int fd = handle.Cast<UnixFileHandle>().fd;
-       if (fsync(fd) != 0) {
+       if ((fsync(fd) != 0) && (errno != ENOTSUP)) {
                throw FatalException("fsync failed!");
        }
 }
```

**however** I was unable (after trying for some time) to reproduce the nodejs setup with `tools/shell/tests/conftest.py`.

### OS:

macos

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Stephan Renatus

### Affiliation:

Styra Inc

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

~I have tested with a nightly build~ I've done a release build from main and used that.

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by mbostock** [comment]
We’ve fixed (or avoided) this bug in Framework: https://github.com/observablehq/framework/pull/1386
