### ISSUE TITLE
Swift API not suitable for large dataset retrieval

### ISSUE THREAD

**Issue by prmelehan** [duckdb/duckdb#10843]
### What happens?

I'm using the Swift API to show previews of datasets (around 50,000 rows, and 40ish columns). It's not large, but it's bigger than the examples given in the documentation on the DuckDB website for Swift.

When I load my frame in using a simple SELECT * FROM ... LIMIT 50000, I'd expect to be able to access row/column information quickly in an O(1) fashion, or convert it to a frame I can use (such as TabularData's DataFrame).

However, it seems like the access on the `ResultSet` is extremely slow. This makes it almost impossible to use as a standalone object, or to convert it to `DataFrame`.

For example, when I try the simple subscript accessor on `ResultSet`, and measure the time to fetch, it is suspiciously long.

```swift
let results = try connection.query("SELECT * FROM read_csv_auto('...some path here...') LIMIT 50000"

let st = Date()
results[0][0] // <- Attempt to get the value from col0, row0.
let et = Date()

let rt = et.timeIntervalSince(st)
print("Runtime for initial access \(rt * 1000) ms") // Between 26ms and 45ms. Some variance here, but orders of magnitude too large
```

Considering that in a development build for swift the `subscript` accessor on an native Swift array takes around 100µs, it seems like the complexity of ResultSet `subscript` accessor is closer to O(n).

Even when following the guides on the website, i.e:

```swift

let col1 = results[0].cast(to: Int.self)

let frame = DataFrame(columns: [col1.eraseToAnyColumn()])

```

The type erasure takes a crazy long time. Like several minutes for a single column...

Was the Swift API ever tested or optimized for larger sets of data? In the example on the website it seemed like there were a few dozen rows but that's all... 

### To Reproduce

1. Install DuckDB Swift (0.10.0)
2. Load a file (Parquet, CSV, etc -- Doesn't matter) and limit to a sizable amount of rows (50k-ish, although at 10k it will still be noticeable).
3. Measure time of `subscript` accessor. Take note of the time for accessing a single value...
```swift
let results = try connection.query("SELECT * FROM read_csv_auto('...some path here...') LIMIT 50000"

let st = Date()
results[0][0] // <- Attempt to get the value from col0, row0.
let et = Date()

let rt = et.timeIntervalSince(st)
print("Runtime for initial access \(rt * 1000) ms") // Between 26ms and 45ms. Some variance here, but orders of magnitude too large

```
4. Optionally, try the same code from the website, but on 10k, or 50k rows. You should notice a long hang time. (several minutes). https://duckdb.org/docs/api/swift.html

### OS:

macOS

### DuckDB Version:

0.10.0

### DuckDB Client:

Swift

### Full Name:

Ryan Melehan

### Affiliation:

Personal Project

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @prmelehan, currently, the Swift API is experimental and unsupported, see the support policy: https://duckdblabs.com/news/2023/10/02/support-policy#extensions-and-apis

> the Julia and Swift APIs are rather experimental and not supported.

So it's quite possible that it was not tested for large-scale retrievals.

**Comment by prmelehan** [comment]
@szarnyasg Thanks for letting me know. I'd be happy to tackle this myself with some guidance...

Is there any relevant documentation that would allow me to understand which methods I should call to fetch data? I'm not super familiar with DuckDB intervals but would be happy to familiarize myself if pointed in the right direction! 

Thanks

**Comment by tcldr** [comment]
If I recall correctly, the issue is that the C API fully materialises the result on first access. I expect the hot path will be here: https://github.com/duckdb/duckdb-swift/blob/f295a76a1470aa15533547d415a22632bb68a8ab/Sources/DuckDB/Internal/Vector.swift#L200.

**Comment by prmelehan** [comment]
@tcldr That could be one culprit, but I have found several other performance bottlenecks. Most of which seem to be around the fetching of the data chunks...

I found the follow other issues:
1. The .count on a ResultSet is not cached, meaning that a call from Column.endIndex reinvokes the count each time... This is important because Column's next() method calls .endIndex for each iteration, which means an explosive growth compute.
2. Function
```swift
func transformer<T>(
    forColumn columnIndex: DBInt,
    to type: T.Type,
    fromTypes columnTypes: Set<DatabaseType>? = nil,
    _ body: @escaping (Vector.Element) -> T?
  ) -> @Sendable (DBInt) -> T?
``` is not caching chunks up front and is fetching chunks again from the C API on every invocation. If my understanding is correct, we should cache all chunks upfront and just re-use those for each call...

I've made fixes to the above in my local branch, and the performance seems to be better than before, but still too slow to be useful for anything of the size I need.

I'm still looking into the Instruments traces to pinpoint what's going on. Attached is a .trace file which you can see the usage. Take a look at 0m56s -> 2m54s on thread `0x27fc6f`

Everything is traceable to the Column.subscript.getter. Almost all other issues stem from that...

I think the majority of the issues here have to do with the Swift code – and not C++

[SlowFetching.trace.zip](https://github.com/duckdb/duckdb/files/14519819/SlowFetching.trace.zip)

**Comment by tcldr** [comment]
@prmelehan thanks for the feedback. I think you're right about fetching the chunks upfront. I believe DuckDB materialises the whole lot upfront anyway – at least in the C API. So, fetching on-demand doesn't have much utility.

Using an in-memory store, adding these changes I see element access drop from 10,000 ns to 2500 ns in debug mode. And from 2500 ns to 1000 ns in release mode. For reference, it takes about 600 ns to access a regular Swift array element on my machine.

You can take a look here: https://github.com/tcldr/duckdb

Let me know if that improves things for you.

In terms of using it with the TabularData framework. The TabularData initialiser takes a Swift Sequence, which tells me that Apple just do a copy in place, otherwise they would have picked something like a RandomAccessCollection over a Sequence.

**Comment by prmelehan** [comment]
@tcldr this worked like a charm! Thanks so much. I'd highly suggest merging this into the main codebase.
