### ISSUE TITLE
Writing parquet with large strings runs out of memory

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#10858]
### What happens?

I have many parquet files each of which has the following schema:
```
┌───────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│  column_name  │ column_type │  null   │   key   │ default │  extra  │
│    varchar    │   varchar   │ varchar │ varchar │ varchar │ varchar │
├───────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ evaluation_id │ VARCHAR     │ YES     │         │         │         │
│ row_id        │ BIGINT      │ YES     │         │         │         │
│ variable      │ VARCHAR     │ YES     │         │         │         │
│ trace         │ VARCHAR     │ YES     │         │         │         │
│ fingerprint   │ VARCHAR     │ YES     │         │         │         │
└───────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

The `trace` column is large: 1748 bytes on average. I have between 100-200 of these files, and each one contains about 120,000 rows.

When running the following query, DuckDB runs out of memory:
```sql
COPY (FROM 'test/*.parquet') TO 'out.parquet' (COMPRESSION ZSTD);
```

I have tried with a `temp_directory` and with a `memory_limit` of ~16GB and neither works. This example is extracted from a production workload with similar characteristics running on machines with a `memory_limit` of 64GB.

### To Reproduce

I have an anonymized parquet file available on request: `carl@watershedclimate.com`. I put this file at `anon.parquet`, then:
```sh
mkdir test
for i in {1..150}; do cp anon.parquet test/shard$i.parquet; done
duckdb -c "COPY (FROM 'test/*.parquet') TO 'out.parquet' (COMPRESSION ZSTD);"
```

This results in the following error:
```
  0% ▕                                                            ▏ Error: Out of Memory Error: failed to allocate data of size 64.0 MiB (12.7 GiB/12.7 GiB used)
Database is launched in in-memory mode and no temporary directory is specified.
Unused blocks cannot be offloaded to disk.

Launch the database with a persistent storage back-end
Or set SET temp_directory='/path/to/tmp.tmp'
```

### OS:

M1 Mac, also x64 Linux

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @zenazn, can you please try the nightly build?

```bash
wget https://artifacts.duckdb.org/latest/duckdb-binaries-osx.zip && unzip duckdb-binaries-osx.zip && unzip duckdb_cli-osx-universal.zip
```

This build contains PR #10756, which specifically targeted reducing memory usage for Parquet exports.

**Comment by szarnyasg** [comment]
Hi @zenazn, I maybe 0.10.1 helped resolve this issue? If not, feel free to reopen this.
