### ISSUE TITLE
uhugeints are truncated when imported from json data

### ISSUE THREAD

**Issue by n-e** [duckdb/duckdb#10866]
### What happens?

Very large numbers in json files are truncated/corrupted when read from json (see the reproduction below).

I'd say it's not really a bug since RFC 7159 allows implementations to set limits on the range and precision of numbers, but it'd be nice not to have to use workarounds such as representing the number as a string since duckdb supports large ints.

### To Reproduce

When reading a large integer as a uhugeint, it gets corrupted (col ends with 82 in the json, with 36 in duckdb):

```sh
echo '{"col": 277447099861456945273576150847928801582 }' | duckdb -c "select col,hex(col) from read_json('/dev/stdin', columns={col: 'uhugeint'})"
┌─────────────────────────────────────────┬──────────────────────────────────┐
│                   col                   │             hex(col)             │
│                 uint128                 │             varchar              │
├─────────────────────────────────────────┼──────────────────────────────────┤
│ 277447099861456950424513728867138011136 │ D0BA5E258FFD00000000000000000000 │
└─────────────────────────────────────────┴──────────────────────────────────┘
```

### OS:

macOS aarm64

### DuckDB Version:

- v0.10.0 20b1486d11
- v0.10.1-dev414 372c514af8 (nightly as of Feb. 27)

### DuckDB Client:

N/A

### Full Name:

Nicolas Even

### Affiliation:

https://chessdata.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by n-e** [comment]
There is a similar issue with the DuckDB CLI : 

```sql
D select 277447099861456945273576150847928801582,277447099861456945273576150847928801582::uhugeint, '277447099861456945273576150847928801582'::uhugeint;
┌────────────────────────┬──────────────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│ 2.7744709986145695e+38 │ CAST(2.7744709986145695e+38 AS UHUGEINT) │ CAST('277447099861456945273576150847928801582' AS UHUGEINT) │
│         double         │                 uint128                  │                           uint128                           │
├────────────────────────┼──────────────────────────────────────────┼─────────────────────────────────────────────────────────────┤
│ 2.7744709986145695e+38 │  277447099861456950424513728867138011136 │                     277447099861456945273576150847928801582 │
└────────────────────────┴──────────────────────────────────────────┴─────────────────────────────────────────────────────────────┘
```

**Comment by szarnyasg** [comment]
Thanks, we'll take a look.
