### ISSUE TITLE
ASOF JOIN applies WHERE clause of right-hand-side to entire result set

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10867]
### What happens?

ASOF JOIN drops some rows in a way that indicates the WHERE of a subquery is applied to the entire result set.

### To Reproduce

```sql
CREATE OR REPLACE TABLE debug(time INTEGER, value FLOAT);
INSERT INTO debug VALUES
    (0, 0), 
    (1, NULL), 
;
SELECT 
d1.time,
d2.time,
d1.value, 
d2.value
FROM debug d1
ASOF JOIN (SELECT * FROM debug WHERE value is not NULL) d2
ON d1.time >= d2.time;
```
produces 
```
┌───────┬───────┬───────┬───────┐
│ time  │ time  │ value │ value │
│ int32 │ int32 │ float │ float │
├───────┼───────┼───────┼───────┤
│     0 │     0 │   0.0 │   0.0 │
└───────┴───────┴───────┴───────┘
```
but should produce 
```sql
CREATE OR REPLACE TABLE debugFiltered AS SELECT * FROM debug WHERE value is not NULL;
SELECT 
d1.time,
d2.time,
d1.value, 
d2.value
FROM debug d1
ASOF JOIN debugFiltered d2
ON d1.time >= d2.time;
```
```
┌───────┬───────┬───────┬───────┐
│ time  │ time  │ value │ value │
│ int32 │ int32 │ float │ float │
├───────┼───────┼───────┼───────┤
│     0 │     0 │   0.0 │   0.0 │
│     1 │     0 │  NULL │   0.0 │
└───────┴───────┴───────┴───────┘
```

Same thing happens when I replace NULL by any float value that I then filter out via a `>`

PS: In fact, I have to run the reproduction in two different `duckdb.query` commands (I'm using the Python client) to get it to do anything; otherwise I'm getting `BinderException: Binder Error: table "unnamed_relation_ba19970fb2ddcb80" has duplicate column name "time"`. I've decided to not report this as separate issue until someone can weigh in on what's going on

### OS:

Linux

### DuckDB Version:

0.10.1-dev397

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
The predicate is not being pushed down. We need to check what other DBs do in this situation.

**Comment by soerenwolfers** [comment]
Are you saying it's not clear whether this is a bug? Is it not true in general in duckdb that replacing a subquery by a materialized table filled with that subquery (not sure of the terminology here) is a no-op?

**Comment by hawkfish** [comment]
I tend to agreee with you, but I need to check the semantics of what other databases do for this type of join (ClickHouse, TimeBase?)

**Comment by soerenwolfers** [comment]
CLickHouse works as expected:
```sql
CREATE TABLE debug(time INTEGER, value FLOAT, dummy INTEGER) ENGINE = MergeTree PRIMARY KEY (time);
INSERT INTO debug VALUES
    (0, 0, 0), 
    (1, NULL, 0), 
;
SELECT 
d1.time,
d2.time,
d1.value, 
d2.value
FROM debug d1
ASOF JOIN (SELECT * FROM debug WHERE value is not NULL) d2
USING (dummy, time);
```
```
┌─time─┬─d2.time─┬─value─┬─d2.value─┐
│    0 │       0 │     0 │        0 │
│    1 │       1 │     0 │        0 │
└──────┴─────────┴───────┴──────────┘
```

```

**Comment by hawkfish** [comment]
It's even worse - we _do_ push down left joins!

**Comment by soerenwolfers** [comment]
Ha, glad you're back on the net then
