### ISSUE TITLE
CLI copy of large table to parquet with compression causes segmentation fault

### ISSUE THREAD

**Issue by GregOliven** [duckdb/duckdb#10874]
### What happens?

CLI on Pop!_OS. With tables in in the range of 16-25 million rows, 165 columns, and in the database filesize range of 5.6GB to 9.4GB (though this size comprises 3 tables like the one that I am exporting), I get the following results:

`COPY (FROM mytable) TO './mytable.parquet' (FORMAT 'parquet');`
-- segmentation fault

`COPY (FROM mytable) TO './mytable.parquet' (FORMAT 'parquet', per_thread_output true, overwrite_or_ignore true);`
-- segmentation fault only on the largest of my tables
--  CODEC 'zstd' fails too

`COPY (FROM mytable) TO './mytable.parquet' (FORMAT 'parquet',  CODEC 'uncompressed', per_thread_output true, overwrite_or_ignore true);`
-- succeeds

`COPY (FROM mytable) TO './mytable.parquet' (FORMAT 'parquet',  CODEC 'snappy', row_group_size 1_000_000);`
-- succeeds

### To Reproduce

Just run the commands above.

### OS:

Pop!_OS on x64, new computer, Intel I9

### DuckDB Version:

v0.10.0 20b1486d11 and nightly build from 2-26-2024

### DuckDB Client:

CLI

### Full Name:

Greg Oliven

### Affiliation:

Polygon Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! It would be very helpful if you could provide the dataset on which this triggers, or a script to generate a similar data set on which you can reproduce the problem. I could not reproduce the issue with a random table.

**Comment by GregOliven** [comment]
I can't share it, but I'd be happy to show it  / reproduce on a call.

**Comment by soerenwolfers** [comment]
You could also try the typical steps towards a MWE: First try identifying a single column that causes problems, then try identifying a single row that causes problems, then see if a random table with the same schema causes the same problems.

**Comment by Mytherin** [comment]
After more thorough investigation we did not manage to reproduce the issue except on one particular machine - and based on that machine also crashing during tests the current conclusion is that either the machine has broken hardware or there is a bug in the OS. Feel free to re-open if the issue can be reproduced elsewhere.
