### ISSUE TITLE
Assert in debug_heap.cpp

### ISSUE THREAD

**Issue by lkordos** [duckdb/duckdb#10887]
### What happens?

Consuming a result from a query with C++ API in a **Debug** build, triggers the ASSERT exception in debug_heap.cpp.
The query result contains 1 column with several thousands rows, containing a string. No cell contains NULL.
The code is as follow:

````
auto f = res->FetchRaw();
for (size_t r = 0; r != rows; ++r)
{
   auto test1 = f->data[0];
   auto test2 = test1.GetValue(r);
   test = test2.GetValue<std::string>();    // ASSERT !
}
````
Continuing debugging after ASSERT, the 'test' contains a valid value. The Release build works as expected.

The line with ASSERT in debug_heap.cpp:

![image](https://github.com/duckdb/duckdb/assets/53355767/b3440ef5-4245-43b9-a9a3-3caa730a08f4)

### To Reproduce

OS: Windows 11
C++
duckdb v0.10.0

### OS:

Windows 11

### DuckDB Version:

v0.10.0

### DuckDB Client:

C++

### Full Name:

Lubomir Kordos

### Affiliation:

Lukosoft Canada

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @lkordos, unfortunately, the C++ API falls outside [the scope of our community support policy](https://duckdblabs.com/news/2023/10/02/support-policy#extensions-and-apis). We are happy to review PRs resolving the issue but are unable to guarantee that it will be fixed in the near future. For guaranteed fixes, please consider our [support options](https://duckdblabs.com/support/).

**Comment by lkordos** [comment]
Hm, that's unfortunate. It would be helpful to clearly state in the docs that the C++ is outside of community support, so proper decisions could be made regarding using this API in real projects.

At this stage, any hint about resolution would help. Thanks.

**Comment by lkordos** [comment]
Changing the runtime library for linking from static to dynamic (/MD flag in VS) fixes the problem.

Saying that, this solution has implication for deployment and is not favorable. The suspect for reason probably is, that allocation and deallocation by duckdb C++ API, when traversing results and de-alocating memory,  is not done in the same heap (MS runtime libs vs duckdb).

**Comment by soerenwolfers** [comment]
The community support policy doesn't explicitly include C++ (like it does with C or Python) but also doesn't explicitly exclude it (like Julia and Rust) and given that duckdb seems to be mostly written in C++ I agree it would be good to clarify the policy by explicitly excluding the C++ API.

**Comment by szarnyasg** [comment]
@lkordos @soerenwolfers that's a fair point, I updated the support policy: https://duckdblabs.com/news/2023/10/02/support-policy#apis

> The C++ API is intended for internal use and is not designed as a stable user-facing API.
