### ISSUE TITLE
`PRAGMA create_fts_index(…)` doesn't work in Julia package

### ISSUE THREAD

**Issue by mlhetland** [duckdb/duckdb#10892]
### What happens?

In Julia, using `DuckDB.jl` and `DBInterface.jl`, executing `PRAGMA create_fts_index(…)` results in the following exception:

```
ERROR: Invalid Input Error: Cannot prepare multiple statements at once!
Stacktrace:
 [1] DuckDB.Stmt(con::DuckDB.Connection, sql::String, result_type::Type)
   @ DuckDB ~/.julia/packages/DuckDB/NRSoQ/src/statement.jl:12
 [2] prepare
   @ ~/.julia/packages/DuckDB/NRSoQ/src/result.jl:834 [inlined]
  …
```

### To Reproduce

Here's a Julia function that produces the error, using the FTS example from [the documentation](https://duckdb.org/docs/extensions/full_text_search.html):

```julia
using DuckDB

function fts_debug()

    con = dbi.connect(DuckDB.DB, ":memory:")

    DBInterface.execute(con, "INSTALL fts")
    DBInterface.execute(con, "LOAD fts")

    DBInterface.execute(con, """
    CREATE TABLE documents (
        document_identifier VARCHAR,
        text_content VARCHAR,
        author VARCHAR,
        doc_version INTEGER
    )
    """)

    DBInterface.execute(con, """
    INSERT INTO documents
        VALUES ('doc1',
                'The mallard is a dabbling duck that breeds throughout the temperate.',
                'Hannes Mühleisen',
                3),
               ('doc2',
                'The cat is a domestic species of small carnivorous mammal.',
                'Laurens Kuiper',
                2
               )
    """)

    DBInterface.execute(con, """
    PRAGMA create_fts_index(
        'documents', 'document_identifier', 'text_content', 'author'
    )
    """)

end
```

### OS:

macOS Ventura 13.6, Intel

### DuckDB Version:

Library version v0.10.1-dev23; source ID 21389fa530

### DuckDB Client:

DuckDB.jl (Julia)

### Full Name:

Magnus Lie Hetland

### Affiliation:

NTNU

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
It sounds like this is solved by https://github.com/duckdb/duckdb/pull/10886
