### ISSUE TITLE
Vacuum Deletes

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#109]
While updates are in-place, deletes leave holes in the table right now. We need to figure out how to deal with that, either by vacuuming or in some other way. Deletes are not mentioned at all in the MVCC paper as far as I remember. We can reuse the space for inserts later on if we know where the gaps are, or move stuff around.

**Comment by zzl221000** [comment]
Any updates?

**Comment by dmoklaf** [comment]
This is preventing DuckDB to be updated on a daily basis in my architecture: every day I have a batch which updates some tables based on external data feeds. This database is growing indefinitely, adding 5 gigabytes every day.

**Comment by Mytherin** [comment]
Fixing this (and several other issues related to the storage) are on the roadmap for the next release.

**Comment by tsriharsha** [comment]
@Mytherin any idea on when this will be? or when there will be a release candidate? Been having to do exports to parquet and load back and its very painful to manage without some degree of vacuum command.

**Comment by bzbzbz** [comment]
> @Mytherin any idea on when this will be? or when there will be a release candidate? Been having to do exports to parquet and load back and its very painful to manage without some degree of vacuum command.

@tsriharsha  We've found the following process to be much faster/ more efficient than exporting to parquet and reloading:

1. `duckdb temp.db`
2. `ATTACH '/my/bloated/duckd.db' as source (READ_ONLY);`
3. `CREATE TABLE mytable AS SELECT * from source.main.mytable;`
4. `DETACH source;`
5.  bash: `mv temp.db /my/bloated/duck.db` 

Hope this helps

**Comment by michaelmdresser** [comment]
I believe I've noticed a similar problem with a bloated DuckDB file after dropping tables (via `DROP` and `CREATE OR REPLACE`). Will the upcoming fix address this situation as well?

**Comment by yxiao315** [comment]
Is there new progress on this? my db file size in disk keep increasing, delete rows/truncate table can not reduce the size.

**Comment by mitchdevenport** [comment]
Would also like to know if there are any updates here, this is crucial for us to be able to scale with DuckDB.

**Comment by pablodcar** [comment]
Don't know if this is the same or a different issue, but it also happens with `:memory:` DB. When I delete or recreate a table, memory consumption of the process is not affected and keeps increasing. I can open a new issue with the details and script to reproduce if you think it's not related to this one.

**Comment by Mytherin** [comment]
> I believe I've noticed a similar problem with a bloated DuckDB file after dropping tables (via `DROP` and `CREATE OR REPLACE`). Will the upcoming fix address this situation as well?

The upcoming release has support for truncating database files, so data can actually be freed on disk (instead of keeping the blocks labeled as free for future release). However, it is limited in the sense it does not move around blocks, so if your file looks like this:

```bash
[HEADER][Table 1][Table 2]
```

And you drop `Table 1`, then no space will be freed (since `Table 2` occupies space later on in the file). We aim to add support for an explicit `VACUUM` in the future that will address this but it will not be part of the next release.

> Don't know if this is the same or a different issue, but it also happens with :memory: DB. When I delete or recreate a table, memory consumption of the process is not affected and keeps increasing. I can open a new issue with the details and script to reproduce if you think it's not related to this one.

That's likely unrelated.

**Comment by mitchdevenport** [comment]
> > I believe I've noticed a similar problem with a bloated DuckDB file after dropping tables (via `DROP` and `CREATE OR REPLACE`). Will the upcoming fix address this situation as well?
> 
> The upcoming release has support for truncating database files, so data can actually be freed on disk (instead of keeping the blocks labeled as free for future usage). However, it is limited in the sense it does not move around blocks, so if your file looks like this:
> 
> ```shell
> [HEADER][Table 1][Table 2]
> ```
> 
> And you drop `Table 1`, then no space will be freed (since `Table 2` occupies space later on in the file). We aim to add support for an explicit `VACUUM` in the future that will address this but it will not be part of the next release.
> 
> > Don't know if this is the same or a different issue, but it also happens with :memory: DB. When I delete or recreate a table, memory consumption of the process is not affected and keeps increasing. I can open a new issue with the details and script to reproduce if you think it's not related to this one.
> 
> That's likely unrelated.

@Mytherin were any improvements made in the most recent release for freeing up space while using a `memory` DB or does it only address database files?

**Comment by thbley** [comment]
I have a similar issue where disk space is not freed after dropping all tables.
```
./duckdb db3.db
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D show tables;
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ 0 rows  │
└─────────┘
D CREATE TABLE t1 AS SELECT * FROM read_parquet('output-zstd.parquet');
100% ▕████████████████████████████████████████████████████████████▏ 
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │    int64     │    int64    │    int64    │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ db3           │ 1.0GB         │     262144 │         3826 │        3826 │           0 │ 0 bytes  │ 1.0GB        │ 13.3GB       │
└───────────────┴───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
D DROP TABLE t1;
D show tables;
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ 0 rows  │
└─────────┘
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │    int64     │    int64    │    int64    │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ db3           │ 1.0GB         │     262144 │         3826 │        3826 │           0 │ 22 bytes │ 786KB        │ 13.3GB       │
└───────────────┴───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
```

Would be nice to have some "optimize database;", "optimize table <table_name>;", "vacuum rebuilt ...", etc. even though it's a slow and blocking operation.

**Comment by brianwyka** [comment]
@pablodcar opened similar.

**Comment by thbley** [comment]
@Mytherin thanks for implementing vacuuming partial deletes! Regarding performance, maybe it would be an option to have 2 delete statements, e.g.:
`ALTER TABLE table DELETE WHERE filter_expr` using vacuuming partial deletes
`DELETE FROM table WHERE filter_expr` using non-vacuuming deletes
