### ISSUE TITLE
"Invalid keyword" error in SQLDriverConnect when connecting via Power Query SDK

### ISSUE THREAD

**Issue by guenp** [duckdb/duckdb#10907]
### What happens?

When connecting to DuckDB from [Power Query SDK](https://learn.microsoft.com/en-us/power-query/install-sdk) using the latest build on `main`, I cannot see any tables in the [Odbc.DataSource](https://learn.microsoft.com/en-us/powerquery-m/odbc-datasource) that is returned by the query.
I have tested this with the latest release (0.10.0) as well and confirmed that this _did_ return the tables when running the test script.

### To Reproduce

- Download latest nightly build for [Windows](https://duckdb.org/docs/installation/?version=main&environment=cli&installer=binary&platform=win)
- Install the `duckdb_odbc` driver
- Create a test database using the `duckdb.exe` from the nightly build, for example, `.\duckdb.exe test.db`, and create a table, `create table numbers as select * from generate_series(1,10) g(x)`
- Connect to the test database with Power Query SDK, for example, using this [SqlODBC sample](https://github.com/microsoft/DataConnectors/tree/master/samples/ODBC/SqlODBC) with the following Power Query script:
```
let
    Database = "\path\to\my\test.db",
    OdbcDatasource = SqlODBC.Contents(Database)
in
    OdbcDatasource{[Item="numbers"]}[Data]
```

Make sure to set `HierarchicalNavigation = false` in the `SqlODBC.pq` file.

This returns the following error:
```
The key didn't match any rows in the table
```

<img width="792" alt="Capture2" src="https://github.com/duckdb/duckdb/assets/4041805/65a72100-9bbc-43a0-b860-618849cb566d">

wheras with the 0.10 release, it returns a table.

<img width="370" alt="Capture1" src="https://github.com/duckdb/duckdb/assets/4041805/dd4ac11c-c47b-4371-813d-9c64de649a75">

When looking at the trace logs, the following line shows up in the logs for the nightly build that is not in the 0.10 build:

```
Microsoft.Mashu 6ce4-5210	EXIT  SQLDriverConnectW  with return code 1 (SQL_SUCCESS_WITH_INFO)
		HDBC                0x000001C52CE6A750
		HWND                0x0000000000000000
		WCHAR *             0x00007FFD478FC3D0 [      -3] "******\ 0"
		SWORD                       -3 
		WCHAR *             0x00007FFD478FC3D0 <Invalid buffer length!> [-3]
		SWORD                       -3 
		SWORD *             0x0000000000000000
		UWORD                        0 <SQL_DRIVER_NOPROMPT>

		DIAG [01S09] O (0) 
```

Where `01S09` is an "Invalid keyword" error in SQLDriverConnect. See [docs](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-a-odbc-error-codes?view=sql-server-ver16).

Here are the trace logs for the `main` build and the 0.10.0 build, respectively:
[ODBC_TRACE_main_build_VSC.log](https://github.com/duckdb/duckdb/files/14442012/ODBC_TRACE_main_build_VSC.log)
[ODBC_TRACE_010_VSC.log](https://github.com/duckdb/duckdb/files/14442013/ODBC_TRACE_010_VSC.log)

### OS:

Windows 10

### DuckDB Version:

Latest main (0.10.1-dev596)

### DuckDB Client:

ODBC

### Full Name:

Guen Prawiroatmodjo

### Affiliation:

MotherDuck

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by guenp** [comment]
Note that the `main` build nor 0.10 show tables on Power BI. Here are the trace logs for those.

[ODBC_TRACE_main_build_PBI.log](https://github.com/duckdb/duckdb/files/14442038/ODBC_TRACE_main_build_PBI.log)
[ODBC_TRACE_010_PBI.log](https://github.com/duckdb/duckdb/files/14442037/ODBC_TRACE_010_PBI.log)

![image](https://github.com/duckdb/duckdb/assets/4041805/87245a60-04f1-4d35-b31a-db5a38289d8b)

**Comment by jordandakota** [comment]
Can confirm I'm seeing the same thing:

![image](https://github.com/duckdb/duckdb/assets/32461077/f6ad0197-66a6-4715-8259-e5ac40f17850)

What's your dsn settings in odbc ?

**Comment by guenp** [comment]
> Can confirm I'm seeing the same thing:
> 
>
> What's your dsn settings in odbc ?

Data source name: test
Database: \path\to\test.db

**Comment by maiadegraaf** [comment]
Hi @guenp, thanks for your issue.  I recently reworked the way the driver reads the connection string. I suspect that `SQLDriverConnectW` returned `SQL_SUCCESS_WITH_INFO` since `HierarchicalNavigation` is not a valid [DuckDB config](https://duckdb.org/docs/sql/configuration.html#configuration-reference). Previously only the database path and the DSN was read out of the connection string so everything else was just ignored, now a `SQL_SUCCESS_WITH_INFO` is returned when an unknown keyword is encountered as per the docs.  Is it possible to print out the diagnostic records to confirm `HierarchicalNavigation` is what's causing this? Also could you let me know if this is still a problem if `HierarchicalNavigation` is removed?

**Comment by kmatt** [comment]
> Note that the `main` build nor 0.10 show tables on Power BI. 

I have gotten as far as seeing data in the Power Query editor using:

```
let
    ConnectionString = [
        Driver = "DuckDB Driver",
        Database = "C:\data\test.duckdb"
    ],
    Source = Odbc.DataSource(
        ConnectionString,
		[HierarchicalNavigation=false]
    ),
	sample = Source{[Item="sample",Schema="main",Catalog="test"]}[Data]
  in
    sample	
```

But when applying to Power BI Desktop, an error dialog

```
Load
  Query1
    This query does not have any columns with the supported data types. It will be disabled from being loaded to the model.
```

**Comment by guenp** [comment]
@kmatt could you share repro steps for how you connected to the database with Power BI Desktop? Did you use the generic ODBC connector?

**Comment by kmatt** [comment]
@guenp - Example repro for a DuckDB with tables and data in the database:

1. Get data -> Blank query
2. Advanced Editor
3. Enter Power Query query, with a DSN as below, or without a DSN as above:

```
let
    Source = Odbc.DataSource("dsn=DuckTest", [HierarchicalNavigation=false]),
    testdata = Source{[Item="testtbl",Schema="main",Catalog="testdb"]}[Data]
in
    testdata
```

I will see data in Power Query, but `Close & Apply` fails with the above errors.

If I connect to a memory database, and query files in the file system, the ODBC connector dialog can be used, but this does not address DuckDB files with table data within:

![image](https://github.com/duckdb/duckdb/assets/435936/aa7fa6e6-ef5f-4c5b-84c8-4240c57dc2b9)

**Comment by kmatt** [comment]
@guenp Adding my Power Query is only working for a DuckDB view joining DuckDB tables. Referencing a table directly fails with the "This query does not have any columns with the supported data types" error.

**Comment by guenp** [comment]
@kmatt , thanks for sharing the repro! I think your issue might be addressed by doing type conversions in the Power Query script by overriding `SQLColumns`, which is then passed to `Odbc.DataSource` via `Options`, see to [this example](https://github.com/microsoft/DataConnectors/blob/master/samples/ODBC/SnowflakeODBC/SnowflakeODBC.pq#L121). I can take a look at this later and see if I can repro your scenario and suggest a fix.

I assume you ran this on the 0.10.0 release? The issue I reported here originally occurs on the bleeding edge build (0.10.1-dev), and for me that failed with an "Invalid keyword" keyword error and didn't make the table visible or available to query in the source at all. I'm worried this is a regression, and it might be an issue with which connection config options Power Query passes to the ODBC driver (as @maiadegraaf mentioned, 0.10.0 ignores invalid ones and 0.10.1-dev throws an exception if invalid options are passed). Now it's a matter of figuring out which invalid option(s) it's trying to pass to the ODBC driver.

**Comment by kmatt** [comment]
Current 0.10.0 release. I added to this issue because of https://github.com/duckdb/duckdb/issues/10907#issuecomment-1970280569 but I can create a new issue if it should be tracked separately.

I have tried to define column types using `Table.TransformColumnTypes(test,{{"Region", type text} ...` which also works in Power Query, but attempting to load that into the PBI Desktop yields a more generic error

`ODBC: An error occurred but no ODBC error information was available.`

**Comment by kmatt** [comment]
> The issue I reported here originally occurs on the bleeding edge build (0.10.1-dev)

@guenp I don't see a `0.10.1-dev` tag. Is this just the current head?

**Comment by guenp** [comment]
@kmatt  yes, it's the latest nightly build that is published here: https://duckdb.org/docs/installation/?version=main
I just abbreviated it to `0.10.1-dev`, but the full name of the version I used was `v0.10.1-dev585 25720d7112`

> I added to this issue because of https://github.com/duckdb/duckdb/issues/10907#issuecomment-1970280569 but I can create a new issue if it should be tracked separately.

Sorry for the confusion, I added that for context on why I used `HierarchicalNavigation=false` in the Power Query script. We could definitely open an issue for that but it may become moot given that we have this regression on the latest `main` (my guess is that pushing a fix for that will require fixing this issue first)

**Comment by maiadegraaf** [comment]
@kmatt could your issue be related to this one: https://github.com/duckdb/duckdb/issues/6528 its an issue we've had for a while.

**Comment by guenp** [comment]
@kmatt, thanks again for sharing repro steps. I think I was able to partially fix your issue, but I need to do some more investigation on the root cause before I can share a sustainable fix. Basically, it looks like the ODBC driver is returning the wrong column types to Power BI, which makes it unable to parse the column which causes the error you saw (`This query does not have any columns with the supported data types.`). I tested this by creating a simple table with two `INT8` columns and running your repro steps. After some inspection it looks like ODBC returned the columns as type `11` which is `TIMESTAMP` (see [ODBC spec](https://github.com/microsoft/ODBC-Specification/blob/master/Windows/inc/sqlext.h#L469C48-L469C51)). I was able to "fix" this by converting the type to `TINYINT` (type `-6`). Note that this is not possible to do via Power BI directly and can only be done by writing a custom connector and overriding `SQLColumns` (see [docs](https://learn.microsoft.com/en-us/power-query/odbc-parameters)).

Loading the data via "Blank Query":
![image](https://github.com/duckdb/duckdb/assets/4041805/dc727798-c051-4ef5-a1db-0b5c4c76d47b)

After loading the data and creating plots:
![image](https://github.com/duckdb/duckdb/assets/4041805/c0fcaa6b-e478-4c1b-913d-4d7b62177071)

Sorry I can't be more helpful, but I'll keep you posted on my progress and will share the code with you once it's ready! Note that I ran the above on 0.10.0, to make this work in 0.10.1 we still need to fix this "Invalid keyword" error (which will hopefully be an easy fix).

**Comment by guenp** [comment]
@kmatt, could you give [this connector](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector) a try and see if it works for you with the `duckdb` v0.10.0 ODBC driver? It contains the fix I mentioned last week. It's still in beta so does not support all data types yet - if you find any related bugs please post them [here](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/issues/5) or create a [new issue](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/issues/new). Thanks so much!

**Comment by dewulf** [comment]
Struggling with the same issues. Have some workaround to get data loaded into Power Query.
```
Source = Odbc.Query("dsn=DuckDB", 
        "attach 'c:\\duck.db' (READ_ONLY);                    
         use duck; 
         select * from table;")
```
Still not getting data in UTF-8, but I'm still searching for a solution.

**Comment by guenp** [comment]
@dewulf, there are a bunch of workarounds implemented in [this Power Query connector](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector), that might help you get the data in UTF-8. Note that this only works with duckdb_odbc 0.10.0 and there are some [known bugs](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/issues)

**Comment by dewulf** [comment]
@guenp Thanks a lot for the hint. Just tried it but the connector doesn't show up. Placed it correctly in the expected folder. Also installed 0.10.0 odbc driver. Adjusted the security config in Power BI. I work in Windows. You linked the linux odbc drivers in your Repo...

**Comment by dewulf** [comment]
@guenp got it working. FYI - connector needs to be placed in the onedrive folder. Now the connector shows me all tables, thats very fine. But UTF-8 still not working...

**Comment by guenp** [comment]
@dewulf 
> You linked the linux odbc drivers in your Repo...

Oops! thanks for the heads up! I'll fix that.

> But UTF-8 still not working...

OK, thanks for letting me know, I'll try to reproduce and create an issue.
