### ISSUE TITLE
Mismatch between uuid bind to as variable vs value returned from db with jdbc

### ISSUE THREAD

**Issue by solita-kattelus** [duckdb/duckdb#10914]
### What happens?

Testing new UUID binding and somehow get mismatching UUID back
```
    @Test
    public void testUUIDBinding() throws SQLException {
        UUID uuid = UUID.fromString("0b17ce61-375c-4ad8-97b3-349d96d35ab1");
        Connection conn = DriverManager.getConnection("jdbc:duckdb:");
        PreparedStatement statement = conn.prepareStatement("select ? as value");
        statement.setObject(1, uuid);
        ResultSet resultSet = statement.executeQuery();
        Assertions.assertTrue(resultSet.next());
        Object object = resultSet.getObject(1);
        Assertions.assertEquals(uuid, object);
        Assertions.assertFalse(resultSet.next());
    }
```

And it fails with Assertions.assertEquals(uuid, object); check as:
```
Expected :0b17ce61-375c-4ad8-97b3-349d96d35ab1
Actual   :8b17ce61-375c-4ad8-97b3-349d96d35ab1
```

### To Reproduce

Reproduce can be done with junit test above.

### OS:

macOs arm64

### DuckDB Version:

0.10.0

### DuckDB Client:

JDBC

### Full Name:

Marko Kattelus

### Affiliation:

Solita Oy

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by rsmckinney** [comment]
Just ran into the same problem. Ouch. Is there a fix underway?

**Comment by rsmckinney** [comment]
This is a bit too severe to ignore, no?
