### ISSUE TITLE
Cannot use correlated column name in FROM clause of LATERAL join

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10927]
### What happens?

Cannot use correlated column name in FROM clause of LATERAL join. This might not be a bug (although it does differ from POSTGRESQL), but I'd still be interested whether something like this is possible. 

In practice, rather than a `range`, I'd be calling `read_parquet`.

### To Reproduce

```sql
SELECT *
FROM (
    SELECT 1
) tb(i), 
LATERAL (
    SELECT * FROM range(tb.i)
)
```
```
BinderException: Binder Error: No function matches the given name and argument types 'range(VARCHAR)'.
```
(an attempted cast to integer reveals that `tb.i` is treated like a string literal)
In POSTGRESQL, the following works:

```sql
SELECT * FROM (VALUES (1), (2)) tb1(i)
LEFT JOIN LATERAL
(
  SELECT * FROM generate_series(1, tb1.i)
) tb2(j)
ON true;
```

| i   | j   |
| --- | --- |
| 1   | 1   |
| 2   | 1   |
| 2   | 2   |

[View on DB Fiddle](https://www.db-fiddle.com/)

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by kryonix** [comment]
This is related to https://github.com/duckdb/duckdb/pull/7522, https://github.com/duckdb/duckdb/issues/5762, and https://github.com/duckdb/duckdb/issues/6917. The issue here is that neither `range` nor `generate_series` are table in-out functions. Same is true for `read_parquet`, apparently. Therefore the functions cannot take the columns of the lateral join as input parameters.

**Comment by soerenwolfers** [comment]
Clear error message added at https://github.com/duckdb/duckdb/pull/11436 -- prioritization of actual fix up to maintainers and doesn't require this ticket.
