### ISSUE TITLE
INTERNAL Error: Attempted to access index N within vector of size N

### ISSUE THREAD

**Issue by davidcorcoran** [duckdb/duckdb#10950]
### What happens?

Running the given query causes ``INTERNAL Error: Attempted to access index 3 within vector of size 3`` after which point the database will produce the error `'Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.'`

### To Reproduce

Run the following querying.
```sql
SELECT t1.Transaction_ID
FROM transactions t1
WHERE t1.Transaction_ID IN
    (SELECT t2.Referred_Transaction_ID
     FROM transactions t2
     WHERE t2.Transaction_ID IN (123606, 123602, 131522, 123604, 131470)
         AND t2.Transaction_ID NOT IN (SELECT t2_filter.Transaction_ID FROM transactions t2_filter))
```

That query is a very stripped down version of the query which caused the error for me. So although it looks odd, and pointless, it still produces the `INTERNAL ERROR`.
Use the following database:
[bug.db.zip](https://github.com/duckdb/duckdb/files/14465216/bug.db.zip)

Just to note something odd: If you export as CSV from that database, then reimport into a new database, the query will succeed.

### OS:

x64, aarch64

### DuckDB Version:

0.9.2, 0.10.0, nightly on 2024-03-01

### DuckDB Client:

Java, CLI

### Full Name:

David Corcoran

### Affiliation:

Topaz (https://topaz.technology/)
We use DuckDB as an in memory pivoting database. We migrated from originally using MonetDB for the same job.

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Can you edit the repro to:
```sql
SELECT t1.Transaction_ID
FROM transactions t1
WHERE t1.Transaction_ID IN
      (SELECT t2.Referred_Transaction_ID
       FROM transactions t2
       WHERE t2.Transaction_ID IN (123606, 123602, 131522, 123604, 131470)
         AND t2.Transaction_ID NOT IN (SELECT t2_filter.Transaction_ID FROM transactions t2_filter))
```

Thanks for the report

**Comment by sirfz** [comment]
I get this error randomly when querying CSV files (using `read_csv_auto`). Apologies for the lack of reproduction code/data but is it possible this happens when running aggregation queries (e.g. `select count()`) with `read_csv_auto`? Right now I consistently hit the error by running this query:

```
conn.query("select count() from read_csv_auto('/path/to/pairs*_data.csv.gz', header=true, filename = true)").show()
```

The pattern matches two files.

Although I can load the files without issue:

```
dp = conn.query("select * from read_csv_auto('/path/to/pairs*_data.csv.gz', header=true, filename = true)").arrow()
```

**Comment by tboddyspargo** [comment]
I ran into `INTERNAL Error: Attempted to access index 62 within vector of size 62` when loading a ~100MiB CSV file that had some type diversity and long string values, but then a redundant header row was inserted in the middle of the file (i.e. someone had just concatenated the rows of two CSV files without removing the header row from the second file). We use`header=true`, `names`, `null_padding `, and `ignore_errors` (didn't help in this case). I've only observed this error on linux/amd64 platform, although I'm not sure that's necessarily relevant.

**Comment by tboddyspargo** [comment]
**UPDATE:** I have a reproducer for python! Hopefully this helps to identify a root cause!

This reproducer demonstrates one flavor of this issue on both v0.9.2 and v0.10.1 as well as the latest pre-release version (v0.10.2.dev213).

```python
def test_csv_load():
    conn = duckdb.connect()
    rel: duckdb.DuckDBPyRelation = conn.read_csv(
        "/tmp/youtube_videos_sm.csv",
        header=True,
        null_padding=True,
    )
    rel.show()
```

[youtube_videos_sm.csv](https://github.com/duckdb/duckdb/files/14763783/youtube_videos_sm.csv)

Result:
```
duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 63 within vector of size 63
```

Shrinking the file further (by removing rows) seems to cause a different CSV dialect to be sniffed (i.e different delimiter or quote character or escape character), and the `InternalException` error no longer occurs. However, at that point, I can't seem to correct the dialect options manually...  Providing the ones I want just seems to provoke: `duckdb.duckdb.InvalidInputException: Invalid Input Error: Error in file "[...]": CSV options could not be auto-detected. Consider setting parser options manually.`.

**Comment by Tmonster** [comment]
> **UPDATE:** I have a reproducer for python! Hopefully this helps to identify a root cause!
> 
> This reproducer demonstrates one flavor of this issue on both v0.9.2 and v0.10.1 as well as the latest pre-release version (v0.10.2.dev213).
> 
> ```python
> def test_csv_load():
>     conn = duckdb.connect()
>     rel: duckdb.DuckDBPyRelation = conn.read_csv(
>         "/tmp/youtube_videos_sm.csv",
>         header=True,
>         null_padding=True,
>     )
>     rel.show()
> ```
> 
> [youtube_videos_sm.csv](https://github.com/duckdb/duckdb/files/14763783/youtube_videos_sm.csv)
> 
> Result:
> 
> ```
> duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 63 within vector of size 63
> ```
> 
> Shrinking the file further (by removing rows) seems to cause a different CSV dialect to be sniffed (i.e different delimiter or quote character or escape character), and the `InternalException` error no longer occurs. However, at that point, I can't seem to correct the dialect options manually... Providing the ones I want just seems to provoke: `duckdb.duckdb.InvalidInputException: Invalid Input Error: Error in file "[...]": CSV options could not be auto-detected. Consider setting parser options manually.`.

I @tboddyspargo I've managed to fix the issue the author had, but could not manage to reproduce your issue. I also looked at your csv file and there seem to be 2 types of separators, both `","` and `"|"`. I think that is why you get the `InvalidInputException`. Can you try specifying a delimiter in your options? If the problem persists, can you also try with a fresh install of duckdb? That way it is more likely that I can reproduce the issue.

**Comment by tboddyspargo** [comment]
> I also looked at your csv file and there seem to be 2 types of separators, both `","` and `"|"`.

You're right! I didn't notice it before, but there's inconsistency with quoting and escaping quotes in the `tags` column. That would explain why the sniffer was getting confused depending on how I truncated the file. It seems to have been sniffing `\0` quote and escape characters whenever it sampled among those inconsistent rows. With `null_padding=true`, that resulted in a bunch of extra columns from the `,` characters in the rows with long description values. With `null_padding=false`, it usually just truncated any of those extra columns that didn't align with the header row.

> I @tboddyspargo I've managed to fix the issue the author had, but could not manage to reproduce your issue.

It seems I may have too aggressively truncated the file without re-testing on other versions. Here are the results of my repro with [youtube_videos_sm.csv](https://github.com/duckdb/duckdb/files/14763783/youtube_videos_sm.csv):

```
>>> print(duckdb.__version__)
0.9.2
>>> conn = duckdb.connect()
>>> rel: duckdb.DuckDBPyRelation = conn.read_csv(
...     "/Users/tyler/Downloads/youtube_videos_sm_broken.csv",
...     header=True,
...     null_padding=True,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 63 within vector of size 63
```

```
>>> print(duckdb.__version__)
0.10.1
>>> conn = duckdb.connect()
>>> rel: duckdb.DuckDBPyRelation = conn.read_csv(
...     "/Users/tyler/Downloads/youtube_videos_sm_broken.csv",
...     header=True,
...     null_padding=True,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.InvalidInputException: Invalid Input Error: Error when sniffing file "/Users/tyler/Downloads/youtube_videos_sm_broken.csv".
CSV options could not be auto-detected. Consider setting parser options manually.
```

```
>>> print(duckdb.__version__)
0.10.2-dev311
>>> conn = duckdb.connect()
>>> rel: duckdb.DuckDBPyRelation = conn.read_csv(
...     "/Users/tyler/Downloads/youtube_videos_sm_broken.csv",
...     header=True,
...     null_padding=True,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.InvalidInputException: Invalid Input Error: Error when sniffing file "/Users/tyler/Downloads/youtube_videos_sm_broken.csv".
CSV options could not be auto-detected. Consider setting parser options manually.
```

---

With the issue (presumably in the sniffer) addressed after 0.9.2, I think the `Invalid Input Error` is appropriate given the formatting issues with the file. I don't think I have any remaining reproducible behavior that I'm concerned about. If I'm able to identify concerning scenarios in the future, I'll raise separate issues. Thank you for checking back in with me!

**Comment by mdp1125** [comment]
hey @tboddyspargo I just encountered a similar case Original error: "Attempted to access index 1 within vector of size 1"", possibly due to long strings and formatting. I seem to be blocked on this, do you know what I should do to the file to resolve this? Any help would be really appreciated, thank you

**Comment by tboddyspargo** [comment]
Based on this issue, you may just want to try with the latest pre-release version to start with. If that doesn't address the issue, then sharing a reproducer that fails on the latest pre-release would help the maintainers to effectively triage and investigate.

**Comment by NielsKorschinsky** [comment]
Hi,
I just want to comment here as I still have with v1.1.3 the very same issue as described in this thread.
It has a similar error pattern like this comment: https://github.com/duckdb/duckdb/issues/10950#issuecomment-2021347583

I'm sadly not able to share the source data & havn't found the issue in the dirty csv file, but wanted to post here in case others have the same issue.

**Comment by NielsKorschinsky** [comment]
Thanks for your answer and trying to help!

I've tested the pre-version: `1.1.4.dev4815`
However, now the statement hangs without continuing.

It is hanging idle at an other file it was able to load before.
This file also has errors, but duckdb was able to manage it.
It dropped the invalid lines via `ignore_errors` & `store_rejects`.

When explicitly testing the faulty file mentioned with the `INTERNAL ERROR`, same behavior - hands without continuing.

Thus, I'm switching back to the live version. 
I'm getting again the internal error.

For reference, I'm using the following SQL statement:

```
CREATE OR REPLACE TABLE
    "LT_orderables"
AS
    SELECT
"COL1"::VARCHAR AS "COL1",
"COL2"::DATE AS "COL2",
    FROM
        read_csv_auto(
            "s3://bucket-name/file-name.csv",
            normalize_names=false,
            header=true,
            delim=',',
            quote='"',
            auto_detect=true,
            null_padding=false,
            ignore_errors=true,
            store_rejects=true,
            sample_size=-1,
            types={'COL1':'VARCHAR','COL2':'DATE'}
        )
```
with a total of 19 columns.

```
duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 19 within vector of size 19
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by NielsKorschinsky** [comment]
However, I've noticed that if I remove `quote='"',` , it works again:

```
normalize_names=false,
            header=true,
            delim=',',
            auto_detect=true,
            null_padding=false,
            ignore_errors=true,
            store_rejects=true,
            sample_size=-1,
            columns={'COL1':'VARCHAR','COL2':'DATE'}
```

However, now it incorrectly detects the quoting character as `'`, which is invalid and causes many rows to be rejected even though they should not be.

**Comment by NielsKorschinsky** [comment]
I will try to filter the data, as I'm not sure yet which lines are the problematic ones, I'm not sure which set to give you.
The original file has 150k+ lines

**Comment by Mytherin** [comment]
If it's possible the original file is also fine - the problem might be related to the size of the file. You can send it to mark@duckdblabs.com

**Comment by NielsKorschinsky** [comment]
@Mytherin I have to revert some of my previous statements.

* using the pre-version works 🥳 
  *  I'm not sure why it did hang before, it does not anymore. 
  * I will continue testing if I still have it somehow
* I've tried the live version after truncating the faulty file down to 10k lines
  *  live still failed, pre did work.
  * if I continue seeing errors, I'm positive I will get a truncated data set I could share with you.
* With pre, the data is loaded correctly, the `store_rejects` table only shows expected failures.


thus, I would say the pre-version resolves this issue. 
Do you have any info when the pre version is going live?
I thank you a lot for your help!

For reference, I'm using currently the following options:

```
read_csv_auto(
            "s3://bucket/file-name.csv",
            normalize_names=false,
            header=true,
            delim=',',
            quote='"',
            auto_detect=true,
            null_padding=false,
            ignore_errors=true,
            store_rejects=true,
            sample_size=-1,
            columns={...})
```

**Comment by Mytherin** [comment]
Great!

The next release is scheduled for next week.

**Comment by g-diwakar** [comment]
The issue has been  closed but I am still facing the similar kind of problem as [/issues/10950]  the one above. 

I am having incremental load using dbt (delete + insert ) which runs similar kind of subquery to first delete the pre-existing rows. It was working fine when data volume was small. But when it grows to like 50 million I am facing the similar problem with the incremental load. The other non-incremental load works fine as expected. The only difference in these kind of load is the incremental runs the similar kind of subquery 

`delete from table where id in ( select id from table_temp)
`

 before loading data. 

The error looks like this : 

`what():  {"exception_type":"INTERNAL","exception_message":"Attempted to access index 9223372036854775807 within vector of size 2"}`

**Comment by g-diwakar** [comment]
My version is v1.0.0 1f98600c2c .

**Comment by Mytherin** [comment]
This has been fixed since v1.2.0 - try upgrading and then checking if the error persists.

**Comment by g-diwakar** [comment]
Thanks for the info. 

I don't know if this is the right place to ask. Actually its the dbt-duckdb package inside the meltano project which manages the whole duckdb file. Going through the instruction mentioned [https://duckdb.org/docs/internals/storage#how-to-move-between-storage-formats](here) would do the work or do I need to follow other ways. 

I mean with here is installing the newer version and exporting the existing file to the newer version as specified above. 

Your words will be greatly appreciated. Thank you.

**Comment by Mytherin** [comment]
DuckDB v1.2.0 can read files written by DuckDB v1.0.0 - so no migration should be necessary.
