### ISSUE TITLE
.wal file stay open on exit after a parquet file import

### ISSUE THREAD

**Issue by dsolito** [duckdb/duckdb#10952]
### What happens?

When I create a new table from a parquet file in the cli, the .wal file is not merged on exit (ctrl-d).
If I open the db in R, the table is not there and when I close the connection, .wal file is deleted.
If I open the db again in the cli, the table is lost.

I have not the problem when importing a csv file.

### To Reproduce

```bash
duckdb mydb.db
```
```sql
CREATE TABLE imported_table AS SELECT * FROM 'table.parquet';
.quit
```

### OS:

Mac OS 14.3.1

### DuckDB Version:

v0.10.0_20b1486d11

### DuckDB Client:

CLI, R

### Full Name:

David Solito

### Affiliation:

Adwire

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @dsolito I was unable to reproduce this issue on macOS 14.3.1. How does your imported table look like? Does it have a lot of data, unusual types (e.g. nested), etc.?

**Comment by dsolito** [comment]
Hi @szarnyasg,

thank you for your reply.
You are right, the parquet file come from a GA4 raw data export. It has several nested columns. 
Maybe I can put the file here for a test?

**Comment by szarnyasg** [comment]
Sure! You can also email it to me if that helps (`gabor@duckdblabs.com`).

**Comment by dsolito** [comment]
Sure. Tomorrow (I am on away for the weekend). 
Thank you!

**Comment by dsolito** [comment]
Hi Gabor, I tested your code and its fine.
But with my file the issue is still there.
I Sent the file by email.
Br,

David

**Comment by szarnyasg** [comment]
Hello, thanks, I could reproduce this with the stable version (v0.10.0) and the nightly build (v0.10.1-dev784 459094ea54). Interestingly, a fresh local build of the exact same version (v0.10.1-dev784 459094ea54) does not reproduce the issue, likely due to small differences in compiler flags. We'll take a look!

**Comment by dsolito** [comment]
thanks!

**Comment by Mytherin** [comment]
It looks like this is fixed already in the latest nightly - I can reproduce it with v0.10.0 but I cannot reproduce it with recent builds. It seems to have been caused by an exception being thrown during the checkpoint on shutdown - but this seems resolved now.

**Comment by dsolito** [comment]
Hi @Mytherin, 
tanks for the feedack.
I will give a try.
