### ISSUE TITLE
Cannot install httpfs on Linux -- DuckDb 0.10.0

### ISSUE THREAD

**Issue by athensofamerica** [duckdb/duckdb#10953]
### What happens?

When I try to install httpfs on Linux under duckdb 0.10.0
Here is the error:
Error: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.10.0/linux_amd64_gcc4/httpfs.duckdb_extension.gz
Extension "httpfs" is an existing extension.

### To Reproduce

1) start duckdb CLI
2) INSTALL httpfs;

### OS:

Linux 4.14.366-253.554.amzn2.x86_64

### DuckDB Version:

0.10.0

### DuckDB Client:

DuckDB CLI and Python

### Full Name:

Phil Chen

### Affiliation:

Arrowstreet

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
I can download that file successfully, are you having network issues perhaps? Or running behind a firewall?

**Comment by athensofamerica** [comment]
Yes, this might be firewall issue. I am able to download the extension in other mean and install and load it with custom local repo. Thanks for your quick response. I'm closing this ticket.
