### ISSUE TITLE
Can not attach to a duckdb database in S3

### ISSUE THREAD

**Issue by pvaezi** [duckdb/duckdb#10967]
### What happens?

When trying to connect to a duckdb database in s3, I can not successfully attach to the db file.

### To Reproduce

```
D INSTALL httpfs;
D LOAD httpfs;
D SET s3_region='...';
D SET s3_access_key_id='...';
D SET s3_secret_access_key='...';
D ATTACH 's3://.../test.db';
Error: Not implemented Error: Cannot open an HTTP file for both reading and writing
D ATTACH 's3://.../test.db' (READ_ONLY);
Error: Catalog Error: Cannot open database "s3://.../test.db" in read-only mode: database does not exist
```

### OS:

Mac OSx

### DuckDB Version:

v0.10.0

### DuckDB Client:

CLI

### Full Name:

Payam Vaezi

### Affiliation:

Personal

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by NatElkins** [comment]
See also: https://github.com/duckdb/duckdb/issues/10409

**Comment by rambalachandran** [comment]
Its still failing for the latest release. For example here is a sample code

**Comment by rambalachandran** [comment]
Its still failing, for example here is sample code that fails
```py
# %%
import duckdb

from utils import get_aws_credentials

# %%
conn = duckdb.connect(':memory:', read_only=False)
conn.execute("INSTALL aws;")
conn.execute("INSTALL aws;")
conn.execute("INSTALL httpfs;")
conn.execute("LOAD aws;")
conn.execute("LOAD httpfs;")

# %%
aws_credentials = get_aws_credentials(profile="td-test-mlops")

command = f"""
CREATE SECRET secret1 (
    TYPE S3,
    KEY_ID '{aws_credentials["aws_access_key_id"]}',
    SECRET '{aws_credentials["aws_secret_access_key"]}',
    REGION 'ap-southeast-2'
);
"""
conn.execute(command)

# %%

# %%
conn.execute("""ATTACH 's3:/bucket-name/folder-name/sample_db2.db' AS s3_db""")
```
The above code fails with error

```
{
	"name": "NotImplementedException",
	"message": "Not implemented Error: Cannot open an HTTP file for both reading and writing",
	"stack": "---------------------------------------------------------------------------
NotImplementedException                   Traceback (most recent call last)
File /home/ubuntu/sdg_bb_repo/sdg-td-cloud/scratch/test_duckdb.py:2
      1 # %%
----> 2 conn.execute(\"\"\"ATTACH 's3://bucket-name/folder-name/sample_db2.db' AS s3_db\"\"\")

NotImplementedException: Not implemented Error: Cannot open an HTTP file for both reading and writing"
}
```

**Comment by samansmink** [comment]
@rambalachandran its currently read only, so if you will need to add READ_ONLY, e.g. `ATTACH 's3://.../test.db' (READ_ONLY);`

**Comment by rambalachandran** [comment]
Adding `READ ONLY` fixed the error. Any timeline on when read & write implementation is considered?

**Comment by samansmink** [comment]
@rambalachandran No timeline here, note that S3 does not allow modifying blobs. Therefore, this is sort of a fundamental issue, the entire DB file would need to be rewritten which is prohibitively slow.

AFAICT we could implement this on azure, which [does allow modifying blobs](https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs) but i can also not give a timeline for that.

**Comment by rambalachandran** [comment]
Thats helpful to know. Thank you again for your prompt response.

**Comment by MdFakrulIslamTaraque** [comment]
@samansmink , I was trying to do the same for GCS, added the `READ ONLY` part, but getting error like: 

`IO Error: Cannot open database "gs://[bucket_name]/gcp_call.db" in read-only mode: database does not exist`.

Any clue??

**Comment by octopyth** [comment]
I get the same error. I tried to connect from duckdb cli and from the python console. In python you can see that in fact the s3:// is not recognised and instead it tries to open database located in
local/path/s3://bucket/database.db
Maybe we are missing some steps before attaching to s3 located database.

**Comment by akshayah3** [comment]
@octopyth Could you provide the python snippet if possible. I am stuck at this and not sure how to proceed

**Comment by octopyth** [comment]
Here is the python snippet:
```
import duckdb
import os

duckdb.sql("install httpfs;")
duckdb.sql("load httpfs;")
duckdb.sql(f"""CREATE SECRET (
    TYPE S3,
    KEY_ID '{os.getenv("S3_ACCESS_KEY_ID")}',
    SECRET '{os.getenv("S3_SECRET_ACCESS_KEY")}',
    REGION 'eu-central-1'
);""")
duckdb.sql("select * FROM duckdb_secrets();").show()

duckdb.sql("ATTACH 's3://test/test_duck.db' AS test_duckdb;")
duckdb.sql("select * from test_duckdb.test;").show()

duckdb.sql("select * from 's3://test/ended_events.parquet';").show()
```
