### ISSUE TITLE
Inconsistency in read_csv behavior when csv file has 1 vs more columns and quoted strings with quote and escape chars

### ISSUE THREAD

**Issue by ilijaljubicic** [duckdb/duckdb#10975]
### What happens?

There is inconsistency in read_csv behavior when csv file has 1 or more columns and quoted strings in the values.

The case below which works  with single column csv file, does not if having more than 1 column:
 * there is a column with quoted string 
 * escape chars inside quoted string present
 * one or more quotes inside quoted string present
 * line break in quoted string present

There is a test case covering quotes and escapes in single column csv quoted string but not in multi column csv :
 * https://github.com/pdet/duckdb/blob/0f9a7e2a3fe14b0d499681849a3c8e6e5bbdf8db/test/sql/copy/csv/code_cov/csv_dialect_detection.test#L9

### To Reproduce

Create 2 csv files, single column 'test_single_column.csv' and 2-columns 'test.csv'.
'query' column in both has a same values including:
 * multiline string
 * quote character
 * escape character

query column values are quoted.

>test_single_column.csv
```
query
"Some multiline
text ......"
"Random text that has " char inside"
"Another random text with \ char inside"
```

>test.csv
```
query,time
"Some multiline
text ......",10
"Random text that has " char inside",10
"Another random text with \ char inside",10
```

2-column cvs file fails parsing:
>./duckdb -c "CREATE TABLE queries AS SELECT * FROM read_csv('test.csv', delim=',',escape='\',header=1); SELECT query FROM queries"
```
Error: Invalid Input Error: Error when sniffing file "events_1.csv".
CSV options could not be auto-detected. Consider setting parser options manually.
```

single column csv file works:
>./duckdb -c "CREATE TABLE queries AS SELECT * FROM read_csv('test_single_column.csv', delim=',',escape='\',header=1); SELECT query FROM queries"
```
┌──────────────────────────────────────────┐
│                  query                   │
│                 varchar                  │
├──────────────────────────────────────────┤
│ "Some multiline                          │
│ text ......"                             │
│ "Random text that has " char inside"     │
│ "Another random text with \ char inside" │

```

Expectation is that:
 * it works in both cases the same way
 * quoted string  parsing to work if quoted string has escape and quote characters present 
 * 
### OS:

Ubuntu 22.04.3 LTS

### DuckDB Version:

0.10.0

### DuckDB Client:

linux x86_64 binnary

### Full Name:

Ilija Ljubicic

### Affiliation:

GrapheneDB

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @ilijaljubicic 

I think these results are expected; the file is just too corrupted to be read. The reason these queries appear to work differently is due to the sniffer doing its best to read improper files.

On the file with one column, the sniffer will choose \0 as a quote because " is not properly escaped. Because it selects \0 as a quote, it will read 4 lines.

The same would happen with the file with two columns, but this time, due to the two-column restriction, selecting \0 as a quote would be invalid since "Some multiline would only have one column.

If you manually set the options for both files, I imagine they will then behave as you expect.

Let me know if that makes sense, or if I got anything wrong :-)

**Comment by ilijaljubicic** [comment]
@pdet thank you for the clarification. Consistency is not broken given logic of choosing \0 when " is not properly escaped.

The part about escaping logic when there is " inside quoted string, well that is a choice of implementation , not a bug.
When I saw what I though was inconsistent behavior, I made assumption that single " inside quoted string is not considered corrupt (like is case with some parsers).

**Comment by pdet** [comment]
> @pdet thank you for the clarification. Consistency is not broken given logic of choosing \0 when " is not properly escaped.
> 
> The part about escaping logic when there is " inside quoted string, well that is a choice of implementation , not a bug. When I saw what I though was inconsistent behavior, I made assumption that single " inside quoted string is not considered corrupt (like is case with some parsers).

@ilijaljubicic out of curiosity, which systems have you encountered that would accept unescaped quotes mid-value?

**Comment by ilijaljubicic** [comment]
I tried to parse  same test.csv file with python and nodejs csv parsers.

Python example:

```parse.py 
import csv

csv_file_path = 'test.csv'
with open(csv_file_path, mode='r') as file:
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        print("Query:|{}| time:{}".format(row['query'],row['time']))
        print("")

print('CSV file successfully processed')

```

>python parse.py 
```
Query:|Some multiline
text ......| time:10

Query:|Random text that has  char inside"| time:10

Query:|Another random text with \ char inside| time:10

CSV file successfully processed
```

**Comment by ilijaljubicic** [comment]
Regarding the example above, I just noticed that python didn't parse well this one:
 * Query:|Random text that has  char inside"| time:10

**Comment by pdet** [comment]
I see, thanks for the clarification, I was wondering because being able to properly parse it because it could lead to drastic errors later on.

Thanks for having a look at it! :-)
