### ISSUE TITLE
Database file does not free space when tables are dropped

### ISSUE THREAD

**Issue by pachadotdev** [duckdb/duckdb#1099]
Hi

It's not possible to delete tables in R.

Here's a MWE

Step 1: Create a DB

```
library(dplyr)
library(DBI)
library(duckdb)

con <- DBI::dbConnect(
      duckdb::duckdb(),
      "mtcars.duckdb"
)

copy_to(
    con,
    mtcars,
    "mtcars",
    temporary = FALSE
)
```

Step 2: Delete the table (doesn't work, the file size remains the same but then the table is unaccessible)
```
dbRemoveTable(con, "mtcars")
```

**Comment by hannesmuehleisen** [comment]
This should be cleaned up on checkpointing, at the moment however, checkpointing only occurs on startup. So if you restart your R shell and reconnect it should free up that storage space. See also #49

**Comment by pachamaltese** [comment]
> This should be cleaned up on checkpointing, at the moment however, checkpointing only occurs on startup. So if you restart your R shell and reconnect it should free up that storage space. See also #49

I tested that and it doesn't work either

**Comment by hannesmuehleisen** [comment]
Indeed I can confirm the issue of space not being freed. Here is a script that reproduces the issue.

````R
library(DBI)

db_file <- tempfile("duckdb_")

con <- dbConnect(duckdb::duckdb(), db_file)
dbWriteTable(con, "test", data.frame(a=integer(10000000)))
dbDisconnect(con, shutdown=TRUE)

system(sprintf("du -hs %s*", db_file))

con <- dbConnect(duckdb::duckdb(), db_file)
dbRemoveTable(con, "test")
dbDisconnect(con, shutdown=TRUE)

system(sprintf("du -hs %s*", db_file))

con <- dbConnect(duckdb::duckdb(), db_file)
dbListTables(con)
dbDisconnect(con, shutdown=TRUE)

system(sprintf("du -hs %s*", db_file))
````

**Comment by hannesmuehleisen** [comment]
Please note though that the storage space is not lost, it can be used by another table.
