### ISSUE TITLE
Can't cast to specific DECIMAL type when using double quotes

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#10999]
### What happens?

```sql
select "c0"::"DECIMAL(18,1)"::VARCHAR from original_rel
```
```
Catalog Error: Type with name DECIMAL(18,1) does not exist!
```

### To Reproduce

```sql
CREATE TABLE decimals AS SELECT i::DECIMAL(18,1) as i FROM (VALUES (1), (2), (3)) tbl(i);
select c0::"DECIMAL(18,1)" FROM (SELECT SUM(i) FROM decimals) t(c0);
```

### OS:

MacOS

### DuckDB Version:

main

### DuckDB Client:

CLI

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report - this is not a bug. Quotes are for identifiers, as such the correct syntax would be `select 10.0::"DECIMAL"(18,1);`. The modifiers (i.e. the `(18, 1)` part) are separate from the type name and hence should not be quoted. This behavior is the same as Postgres:

```sql
postgres=# select 10.0::"numeric"(18,1);
 numeric 
---------
    10.0
(1 row)

postgres=# select 10.0::"numeric(18,1)";
ERROR:  type "numeric(18,1)" does not exist
LINE 1: select 10.0::"numeric(18,1)";

```
