### ISSUE TITLE
Benchmark Comparison against Other Systems

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#110]
Right now we already have SQLite-compatibility in the benchmarks (by running sqlite_[XXX] the benchmark can be run in SQLite instead). We should add a similar compatibility layer for PostgreSQL, Hyper and MonetDB and create a separate web-page where we lay out the results side by side for the systems for an overview of where we stand and where we can improve.

**Comment by danielarantes** [comment]
Would be nice to create scripts to follow this benchmark: https://h2oai.github.io/db-benchmark/
It's not a TPC-H...but compares with several analytical tools and libraries in Python, R and Julia. And most importantly, it runs with some frequency against the latest releases...so it's not stale within a few months.
For example it compares runtimes (and I think will compare memory usage soon) for:
- pandas
- data.table
- pydatatable
- dask
- spark
- clickhouse
and others against a set of queries with 10M, 100M and 1B rows (0.5GB, 5GB, 50GB)

https://github.com/h2oai/db-benchmark

**Comment by Mytherin** [comment]
That's a great idea, thanks for the link! We should work on adding DuckDB there at some point. But first we should optimize for those benchmarks of course ;)

**Comment by danielarantes** [comment]
I think the queries there are pretty straightforward. I've cloned the repo and will try to create the code for duckdb (which I've never used but I'm **very** curious to check).

**Comment by sdmcallister** [comment]
Just looking at https://h2oai.github.io/db-benchmark/
Group By 50gb

![image](https://user-images.githubusercontent.com/16430997/124494390-c5453200-dd84-11eb-8b16-40f00cda5862.png)

Those are some interesting results... Under notes I noticed 

->ClickHouse and DuckDB queries are CREATE TABLE ans AS SELECT ... to match the functionality provided by other solutions in terms of caching results of queries, see #151.

Is it just me or should the 2nd run really be a more accurate representation of performance?

**Comment by Mytherin** [comment]
You are correct that the second time is the correct time here - the problem is that DuckDB currently releases blocks after a checkpoint. This is not a problem for in-memory datasets since the block is still cached by the OS, but is a problem for larger than memory datasets since the blocks need to be read from disk again. This is a (performance) bug in DuckDB though, not related to the benchmark itself.
