### ISSUE TITLE
The results of 'abc' > 'CCC' and greatest('abc', 'CCC') are inconsistent?

### ISSUE THREAD

**Issue by Toexplore** [duckdb/duckdb#11003]
### What happens?

The result of statement1 shows that 'abc' is not great than 'CCC',  while the result of statement2 is the opposite. 

statement1:
```statement1
D select 'abc' > 'CCC';
┌─────────────────┐
│ ('abc' > 'CCC') │
│     boolean     │
├─────────────────┤
│ false           │
└─────────────────┘
```
statement2:
```statement2
D SELECT greatest('abc', 'CCC');
┌────────────────────────┐
│ greatest('abc', 'CCC') │
│        varchar         │
├────────────────────────┤
│ abc                    │
└────────────────────────┘
```

### To Reproduce

statement1:
```statement1
D select 'abc' > 'CCC';
┌─────────────────┐
│ ('abc' > 'CCC') │
│     boolean     │
├─────────────────┤
│ false           │
└─────────────────┘
```
statement2:
```statement2
D SELECT greatest('abc', 'CCC');
┌────────────────────────┐
│ greatest('abc', 'CCC') │
│        varchar         │
├────────────────────────┤
│ abc                    │
└────────────────────────┘
```

### OS:

linux

### DuckDB Version:

0.10.0

### DuckDB Client:

cli

### Full Name:

Eric Wong

### Affiliation:

personal

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@Toexplore Thanks for reporting this! `greatest` is also not documented for strings, I'll update the documentation about it.

**Comment by Mytherin** [comment]
Thanks for reporting! Are you running with any collations enabled? I cannot reproduce the issue:

```sql
D select 'abc' > 'CCC';
┌─────────────────┐
│ ('abc' > 'CCC') │
│     boolean     │
├─────────────────┤
│ true            │
└─────────────────┘
D select greatest('abc', 'CCC');
┌────────────────────────┐
│ greatest('abc', 'CCC') │
│        varchar         │
├────────────────────────┤
│ abc                    │
└────────────────────────┘

```

Note that least/greatest does not currently support collations - so it not working with collations is currently expected behavior.

**Comment by Toexplore** [comment]
> Thanks for reporting! Are you running with any collations enabled? I cannot reproduce the issue:
> 
> ```sql
> D select 'abc' > 'CCC';
> ┌─────────────────┐
> │ ('abc' > 'CCC') │
> │     boolean     │
> ├─────────────────┤
> │ true            │
> └─────────────────┘
> D select greatest('abc', 'CCC');
> ┌────────────────────────┐
> │ greatest('abc', 'CCC') │
> │        varchar         │
> ├────────────────────────┤
> │ abc                    │
> └────────────────────────┘
> ```
> 
> Note that least/greatest does not currently support collations - so it not working with collations is currently expected behavior.

Yes, I found that the statement1('abc' >'CCC'）will utilize the capabilities of ICU, while the statement2(greatest) will not.

**Comment by Mytherin** [comment]
I've added greatest/least to the collation issue - https://github.com/duckdb/duckdb/issues/604
