### ISSUE TITLE
Temp tables dropped when creating cursor

### ISSUE THREAD

**Issue by solomspd** [duckdb/duckdb#11018]
### What happens?

When a temp table is created on a connection and a cursor is used to duplicate the connection, the temp table is dropped from the connection duplicated through `connection.cursor()` when it is expected for the temp table to be carried over since it is till part of the same connection.
The use case is to be able to support concurrent reads from the temp table across threads, following a similar pattern to [multiple threads python docs](https://duckdb.org/docs/guides/python/multiple_threads.html) but operating on temp tables instead.

### To Reproduce

An example based on the [python threads docs](https://duckdb.org/docs/guides/python/multiple_threads.html)

This following code
```py
import duckdb
from threading import Thread

duckdb_con = duckdb.connect("my_peristent_db.duckdb")
# Use connect without parameters for an in-memory database
# duckdb_con = duckdb.connect()
duckdb_con.execute(
    """
    CREATE TEMP TABLE my_inserts (data_id INTEGER)
"""
)

duckdb_con.execute(
    """
	INSERT INTO my_inserts (data_id) VALUES (1), (2), (3), (4), (5)
"""
)


def read_from_thread(duckdb_con):
    # Create a DuckDB connection specifically for this thread
    local_con = duckdb_con.cursor()
    # Query the current row count
    results = local_con.execute(
        """
		SELECT * FROM my_inserts
    """,
    ).fetchall()
    print(results)


write_thread_count = 50
read_thread_count = 5
threads = []

for j in range(read_thread_count):
    threads.append(
        Thread(
            target=read_from_thread, args=(duckdb_con,), name="read_thread_" + str(j)
        )
    )


# Kick off all threads in parallel
for thread in threads:
    thread.start()

# Ensure all threads complete before printing final results
for thread in threads:
    thread.join()

```

Will result in errors stating that it cannot find the temp table called `my_inserts` using the local connections despite being able to read it from the original connection.

### OS:

Arch Linux, x64

### DuckDB Version:

0.10.0, 0.10.1-dev893

### DuckDB Client:

Python

### Full Name:

Abdelsalam ElTamawy

### Affiliation:

the American University in Cairo

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
`cursor()` does not duplicate the connection, it creates a new connection to the same database.
Temporary tables are part of a connection, not of the database.

I believe this behavior is expected

**Comment by solomspd** [comment]
![image](https://github.com/duckdb/duckdb/assets/40343437/51aeb91f-15cf-4a24-a462-78ae4273143a)
@Tishj I was using the terminology mentioned in the [docs](https://duckdb.org/docs/api/python/reference/)^. If that's the case, I feel it could be made a bit clearer.
Does this mean duckdb does not support concurrent read from a temp table?

**Comment by Tishj** [comment]
That's fair, we might need to improve the wording there, "duplicate" comes with some assumptions that arent all met

Using the same Connection concurrently is not supported, since temporary tables are stored only on the Connection they can't be read concurrently

You could make the temporary table an arrow table instead and register it on cursors, so it can be read concurrently
