### ISSUE TITLE
Missing nanosecond support in string literals

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11029]
### What happens?

Nanoseconds in string literals are ignored.

### To Reproduce

```sql
SELECT '00:00:00.123456789'::TIME = '00:00:00.123456'::TIME;
SELECT epoch_ns('1970-01-01 00:00:00.123456789'::TIMESTAMP) = epoch_ns('1970-01-01 00:00:00.123456'::TIMESTAMP);;
SELECT '2020-01-01 00:00:00.123456789'::TIMESTAMP = '2020-01-01 00:00:00.123456'::TIMESTAMP;
```

all return true, indicating that literals are truncated to microsecond precision. There is also missing nanosecond support in various utility functions, such as `date_part`, and in the string display itself.

In general nanosecond support does exist and work, as verified via 
```python
import pandas as pd
import duckdb
df = pd.DataFrame({'a': [pd.Timestamp(2020, 1, 1, nanosecond=999), pd.Timestamp(2020, 1, 1)]})
duckdb.query("""SELECT DISTINCT a FROM df""")
```

### OS:

Linux

### DuckDB Version:

'0.10.1-dev717'

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
@Mytherin I read that page before, it says `TIMESTAMP` is an alias for `TIMESTAMP_NS`. Maybe that just needs correction then

**Comment by Mytherin** [comment]
Ah yes, you're right - that's an issue in the docs. I have opened an issue here - https://github.com/duckdb/duckdb-web/issues/2460
