### ISSUE TITLE
reading csv does not support custom date format in new version 0.10.0

### ISSUE THREAD

**Issue by skandaramesh** [duckdb/duckdb#11026]
### What happens?

When using the sql query to read csv which has custom dateformat, it fails in 0.10.0 but works in 0.9.2

### To Reproduce

When using the below query to read csv, it fails in 0.10.0 but works in 0.9.2

```sql
Select * from read_csv('SampleData.csv', header=true, dateformat='%m/%d/%Y, %-I:%-M %p' );
```
Note: I am using read_csv() instead of read_csv_auto() as suggested in the release of 0.10.0 and comparing it to the usage of  read_csv_auto() in v0.9.2

**SampleData.csv**
```csv
ID,Date_Time
123,"1/2/2023, 12:33 PM"
124,"12/2/2023, 11:57 AM"
```

Note: the date format differs from ISO format 8601 the above dateformat has a comma after the date. Seems to me that the dateformat is not being handled for custom format

### OS:

Mac OS

### DuckDB Version:

0.10.0

### DuckDB Client:

Rust

### Full Name:

Skanda Ramesh

### Affiliation:

Okoservices

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by pdet** [comment]
Indeed the sniffer is ignoring this option, I'll patch a fix for the next release.

Meanwhile, you can do :
```sql
Select * from read_csv('data/csv/custom_date.csv', header=true, dateformat='%m/%d/%Y, %-I:%-M %p', types = ['BIGINT', 'DATE'] );
```
