### ISSUE TITLE
CSV read, INTERNAL Error: Attempted to access index 1 within vector of size 1

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb#11040]
### What happens?

Hi,
I try to read a big CSV file and I have INTERNAL Error.

### To Reproduce

I cannot attach a sample file, because it's big.

The source is a CSV, with delim=";" https://opencoesione.gov.it/media/open_data//progetti_esteso_20231231.zip

Decompress it and get the top 290k lines:

```bash
progetti_esteso_20231231.zip
<progetti_esteso_20231231.csv head -n 290000 >tmp.csv
```

Then I run

```
duckdb --csv -c "SET preserve_insertion_order=false;SELECT count(*) FROM read_csv_auto('tmp.csv',parallel=false,all_varchar=true)"
```

and I have 

```
Error: INTERNAL Error: Attempted to access index 1 within vector of size 1
```

### OS:

Debian 12

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

0.10.0

### Full Name:

Andrea Borruso

### Affiliation:

onData

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, we'll take a look.

**Comment by niger-prequel** [comment]
👋 we are also experiencing this issue on 0.10.0. I've attached a testing file we've managed to generate that produces a similar issue:


[2746457131.csv](https://github.com/duckdb/duckdb/files/14542869/2746457131.csv)

```sql
SELECT COALESCE(MAX(CAST(ROUND(epoch(CAST(last_updated_at AS timestamp)), 0) AS BIGINT)), 0) FROM    read_csv('2746457131.csv', header=true, delim='|');
```

The above query fails with `Error: INTERNAL Error: Attempted to access index 1 within vector of size 1`. This is using the go-driver pinned to commit `61c6c9e1caa257f4a32a31bb19856198e7342edd`.

**Comment by Mytherin** [comment]
> 👋 we are also experiencing this issue on 0.10.0. I've attached a testing file we've managed to generate that produces a similar issue:
> 
> [2746457131.csv](https://github.com/duckdb/duckdb/files/14542869/2746457131.csv)
> 
> ```sql
> SELECT COALESCE(MAX(CAST(ROUND(epoch(CAST(last_updated_at AS timestamp)), 0) AS BIGINT)), 0) FROM    read_csv('2746457131.csv', header=true, delim='|');
> ```
> 
> The above query fails with `Error: INTERNAL Error: Attempted to access index 1 within vector of size 1`. This is using the go-driver pinned to commit `61c6c9e1caa257f4a32a31bb19856198e7342edd`.

I can confirm I can reproduce the error on v0.10.0, and it also seems to be fixed by https://github.com/duckdb/duckdb/pull/11056.

```bash
 pip install duckdb --pre --upgrade
```

```py
>>> import duckdb
>>> duckdb.sql('pragma version')
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.10.1-dev1037 │ ce34abc51f │
└─────────────────┴────────────┘

>>> duckdb.sql('''
... SELECT COALESCE(MAX(CAST(ROUND(epoch(CAST(last_updated_at AS timestamp)), 0) AS BIGINT)), 0) FROM    read_csv('2746457131.csv', header=true, delim='|');
... '''
... )
┌───────────────────────────────────────────────────────────────────────────────────────┐
│ COALESCE(max(CAST(round(epoch(CAST(last_updated_at AS TIMESTAMP)), 0) AS BIGINT)), 0) │
│                                         int64                                         │
├───────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                 99999 │
└───────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by niger-prequel** [comment]
Great, we'll try an upgrade tomorrow and report if we see the same issue for whatever reason. Thanks for the quick fix

**Comment by nileshtrivedi** [comment]
I am still getting this error with v0.10.3-dev779 :

```
>>> import duckdb
>>> duckdb.sql('pragma version')
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.10.3-dev779  │ d26007417b │
└─────────────────┴────────────┘

>>> duckdb.sql('''
... CREATE TABLE up_jan as SELECT * FROM read_csv('UP Reports/Jan-24/up_transformation/UP_Merge_Orders_Items_Output.csv', columns = {'Order ref ID': 'VARCHAR'}, ignore_errors=true);
... '''
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mac/.asdf/installs/python/3.10.14/lib/python3.10/site-packages/duckdb/__init__.py", line 455, in sql
    return conn.sql(query, **kwargs)
duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by pdet** [comment]
> I am still getting this error with v0.10.3-dev779 while importing a CSV file that is about 450MB in size:
> 
> ```
> >>> import duckdb
> >>> duckdb.sql('pragma version')
> ┌─────────────────┬────────────┐
> │ library_version │ source_id  │
> │     varchar     │  varchar   │
> ├─────────────────┼────────────┤
> │ v0.10.3-dev779  │ d26007417b │
> └─────────────────┴────────────┘
> 
> >>> duckdb.sql('''
> ... CREATE TABLE up_jan as SELECT * FROM read_csv('UP Reports/Jan-24/up_transformation/UP_Merge_Orders_Items_Output.csv', columns = {'Order ref ID': 'VARCHAR'}, ignore_errors=true);
> ... '''
> ... )
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/mac/.asdf/installs/python/3.10.14/lib/python3.10/site-packages/duckdb/__init__.py", line 455, in sql
>     return conn.sql(query, **kwargs)
> duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1
> This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
> For more information, see https://duckdb.org/docs/dev/internal_errors
> ```

Hi @nileshtrivedi, Could you share a minimally reproducible example? As in the smallest dataset where you encounter the issue.

**Comment by nileshtrivedi** [comment]
@pdet I was able to reduced it to a dataset of ~82KB (128 rows). [Here is the link to the test10.csv file](https://drive.google.com/file/d/1BmYlrJro6ffd4f4e5iB69ftjVLFPl1w2/view?usp=sharing).

Here is how I reproduce the error:

```
Python 3.10.14 (main, Apr 23 2024, 16:26:32) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> duckdb.sql('pragma version')
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.10.3-dev779  │ d26007417b │
└─────────────────┴────────────┘

>>> duckdb.sql("CREATE TABLE up_jan as SELECT * FROM read_csv('test10.csv', columns = {'Order ref ID': 'VARCHAR'}, ignore_errors=true);")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mac/.asdf/installs/python/3.10.14/lib/python3.10/site-packages/duckdb/__init__.py", line 455, in sql
    return conn.sql(query, **kwargs)
duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 1 within vector of size 1
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by pdet** [comment]
Hi @nileshtrivedi, Thanks for reporting a reproducible example! Indeed, there is an issue with escaped values not being properly skipped when `ignore_errors = 'true'`. I've submitted a PR for that.
https://github.com/duckdb/duckdb/pull/12027

However, I think that in this case, you should use the 'types' option, not the 'column' option, assuming that you simply want to replace the type  `'Order ref ID'` to `VARCHAR` :-)

**Comment by nileshtrivedi** [comment]
Amazing! 👏 😲  Thank you so much @pdet for the prompt fix. Looking forward for the v0.103 release! :-)
