### ISSUE TITLE
SQL `insert into ... values` throw unexpected error

### ISSUE THREAD

**Issue by yuanyan** [duckdb/duckdb#11049]
### What happens?

Error: Constraint Error: Violates foreign key constraint because key "employeeNumber: 1002" does not exist in the referenced table

```sql
insert  into employees(employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle) values
(1002,'Murphy','Diane','x5800','dmurphy@classicmodelcars.com','1',NULL,'President'),(1056,'Patterson','Mary','x4611','mpatterso@classicmodelcars.com','1',1002,'VP Sales');
```

table schema:
```sql
CREATE TABLE employees (
  employeeNumber int,
  lastName varchar(50) NOT NULL,
  firstName varchar(50) NOT NULL,
  extension varchar(10) NOT NULL,
  email varchar(100) NOT NULL,
  officeCode varchar(10) NOT NULL,
  reportsTo int DEFAULT NULL,
  jobTitle varchar(50) NOT NULL,
  PRIMARY KEY (employeeNumber),
  FOREIGN KEY (reportsTo) REFERENCES employees (employeeNumber)
);
```

### To Reproduce

Execute this sql.

### OS:

macos

### DuckDB Version:

0.10

### DuckDB Client:

cli

### Full Name:

yuanyan

### Affiliation:

opensource

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello, this is expected behavior: if you take the [Tree Traversal](https://duckdb.org/docs/sql/query_syntax/with#tree-traversal) example from the documentation and change the schema, it will also fail:

```sql
CREATE TABLE tag (id INT, name VARCHAR, subclassof INT, PRIMARY KEY (id), FOREIGN KEY (subclassof) REFERENCES tag (id) );
INSERT INTO tag VALUES
    (1, 'U2',     5),
    (2, 'Blur',   5),
    (3, 'Oasis',  5),
    (4, '2Pac',   6),
    (5, 'Rock',   7),
    (6, 'Rap',    7),
    (7, 'Music',  9),
    (8, 'Movies', 9),
    (9, 'Art', NULL);
```
```text
Error: Constraint Error: Violates foreign key constraint because key "id: 5" does not exist in the referenced table
```
I'll expand the documentation to point this out.
