### ISSUE TITLE
INTERNAL Error: Failed to bind column reference "xx" [21.0] (bindings: [0.0 0.1 1.0])

### ISSUE THREAD

**Issue by exaroj** [duckdb/duckdb#11042]
### What happens?

 INTERNAL Error: Failed to bind column reference "parentExists" [21.0] (bindings: [0.0 0.1 1.0])

### To Reproduce

```sql
CREATE OR REPLACE TABLE BaseData AS (
    SELECT
      '10' AS my_key,
      '20' AS parent_key,
      '30' AS payload
)
;

WITH
Example AS (
    SELECT
        c.my_key,
        (c.parent_key IN (SELECT my_key FROM BaseData)) AS parentExists,
        p.my_key IS NOT NULL AS parentExists2,
    FROM BaseData AS c
    LEFT JOIN BaseData AS p ON c.parent_key = p.my_key
)
SELECT *
FROM Example
WHERE parentExists -- fails
-- WHERE parentExists2 -- works
;
```

### OS:

macOS 14.3.1

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Rob Jackson

### Affiliation:

Exaforce

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, we'll take a look.
