### ISSUE TITLE
CSVL new_line parameter for COPY results in literal, not escaped characters

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#11058]
### What happens?

bla.csv has CR LF lines. These are correctly parsed with read_csv. But when using the same value for COPY, the data is written with '\r\n' instead.

### To Reproduce

In duckdb:

```sql
copy (select * from read_csv('bla.csv', new_line = '\r\n')) to 'bla2.csv' (new_line  '\r\n');
```

Afterwards, in git bash:

```
$ git diff bla.csv bla2.csv
diff --git a/bla.csv b/bla2.csv
index e74aed1..9cc2ab5 100644
--- a/bla.csv
+++ b/bla2.csv
@@ -1,3 +1 @@
-Name;Value
-name1;value1
-name2;value2
+Name,Value\r\nname1,value1\r\nname2,value2\r\n
\ No newline at end of file
```
[bla.csv](https://github.com/duckdb/duckdb/files/14538279/bla.csv)
[bla2.csv](https://github.com/duckdb/duckdb/files/14538280/bla2.csv)

(Files are attached)

### OS:

Windows 10 Pro

### DuckDB Version:

v0.10.1-dev969

### DuckDB Client:

CLI (any)

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @rpbouman, using an [escape string literal](https://duckdb.org/docs/sql/data_types/literal_types#escape-string-literals) does the trick for me:

```sql
copy (select * from read_csv('bla.csv', new_line = '\r\n')) to 'bla2.csv' (new_line e'\r\n');
```

Can you please check whether this works for you?

**Comment by rpbouman** [comment]
Hi Gabor! That works - thanks! 
Still, it's different between read and copy - is that intended?

**Comment by szarnyasg** [comment]
I think this is just a side-effect of the parser using a different expression for function calls and the `COPY` statement. We'll take a look.
