### ISSUE TITLE
out of memory converting many large CSVs to parquet unless one single thread

### ISSUE THREAD

**Issue by karlcellcarta** [duckdb/duckdb#11054]
### What happens?

I have ~ 60 large CSV files, ~ 1.3G each.
I convert them to parquet using:
```
    COPY (SELECT * FROM read_csv('{CSV_DIR}/data*.csv', AUTO_DETECT=true, header=true))
    TO '{PARQUET_DIR}/{parquet}'
    (FORMAT PARQUET, CODEC 'SNAPPY', PER_THREAD_OUTPUT false);
```
If fails with `duckdb.duckdb.OutOfMemoryException: Out of Memory Error: failed to allocate data xxxx`
I tried setting memory_limit, temp_directory with no success.

What worked is setting a single thread with `SET threads=1`.
In which case the progress reporting is really not accurate: it stays at 1% during 99% of the time, then finally goes to 100% just before finishing. 

Just reporting this in case it can help other users, or help the developers improving this.

### To Reproduce

python 3.11.8
duckdb                     

```
import duckdb
con = duckdb.connect(database='tmp/duckdb.tmp.db') # does not really matter, same behavior with in memory
csv = "data_*.csv"
parquet = "data.parquet"
con.execute(f"""
    COPY (SELECT * FROM read_csv('{CSV_DIR}/{csv}', AUTO_DETECT=true, header=true))
    TO '{PARQUET_DIR}/{parquet}'
    (FORMAT PARQUET, CODEC 'SNAPPY', PER_THREAD_OUTPUT false);
  """)
```

N.B: I tried with the latest nightly build 0.10.1.dev969, whose behavior was quite different:
- with default threads setting (8)
- it seemed to use the 'tmp/duckdb.tmp.db' as temporary storage
- it eventually failed with an Out of memory error at 14/18G completion progress

### OS:

Debian GNU/Linux 11

### DuckDB Version:

0.10.0

### DuckDB Client:

python 0.10.0

### Full Name:

Karl Forner

### Affiliation:

none

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @karlcellcarta – PR #10756 made improvement in this, and this is already part of the nightly build. Can you please test with the nightly build available via pip?
```bash
pip install duckdb --pre --upgrade
```

**Comment by karlcellcarta** [comment]
hi @szarnyasg 
I indicated in the issue that I did try. Look near the end under `N.B`

**Comment by szarnyasg** [comment]
Ah, sorry, I missed that. A potential option then is to turn off the [preserve_insertion_order option](https://duckdb.org/docs/guides/performance/how_to_tune_workloads#the-preserve_insertion_order-option):
```sql
SET preserve_insertion_order = false;
```
