### ISSUE TITLE
`list_sum([])` results in NULL, but `list_dot_product([], [])` results in 0

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#11066]
### What happens?

`SELECT list_sum(ARRAY[]::INTEGER[]);` gives NULL.

`SELECT list_dot_product(ARRAY[]::INTEGER[], ARRAY[]::INTEGER[]);` gives 0.0

I would expect them both to result in the same thing (probably NULL)

### To Reproduce

see above

### OS:

shell.duckdb.org

### DuckDB Version:

v0.10.0

### DuckDB Client:

@duckdb/duckdb-wasm@1.28.1-dev159.0

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
I would want integer zero for both ;)

**Comment by NickCrews** [comment]
Those are great reasons!

If I do a SUM over a column with no rows (`SELECT SUM(l_tax) FROM 'https://shell.duckdb.org/data/tpch/0_01/parquet/lineitem.parquet' WHERE l_tax<0;`), then I get NULL. Should this also be 0?   I feel like `SUM(empty column)` should have the same behavior as` LIST_SUM(empty list)`.

**Comment by Maxxen** [comment]
CC @Mytherin I could look into fixing this this week as Im planning to do some related list/array fixes, but what is the desired behavior here?

**Comment by Mytherin** [comment]
The current behavior actually seems correct to me. `list_sum` should return the same as the SQL `SUM` aggregate - and the SQL `SUM` aggregate is defined by the SQL standard to be `NULL` for an empty set.

The dot product returning 0 for two empty lists seems consistent with NumPy:

```py
import numpy
print(numpy.dot([], []))
# 0.0
```

As such I think this is also correct behavior.

**Comment by NickCrews** [comment]
`numpy.sum([])` produces 0 as well. So numpy is self-consistent, returning 0s for these aggs. This unfortunately implies that SQL and numpy are never going to be consistent with each other 😢 . In that case, `list_dot_product()` has the choice of being consistent with `numpy.dot()`, or with `sql.sum()`. I think I would rather it be consistent within the same ecosystem, and be consistent with `sql.sum()`.

**Comment by soerenwolfers** [comment]
I agree with @NickCrews: I'd prefer `list_sum` to return `0` and disagree with the `SUM` aggregate (is there a strong case they have to behave the same? A column entry that's an empty list is different from an empty group in a GROUP BY, no?); but if that's not desired I'd find the second best option to have all return NULL.
