### ISSUE TITLE
Linking error in aarch64 debug python build when using ccache

### ISSUE THREAD

**Issue by code1704** [duckdb/duckdb#11078]
### What happens?

To build a debug version of DuckDB Python, I use
```bash
export CC="ccache gcc"   # enable cache
BUILD_PYTHON=1 PYTHON_USER_SPACE=1 make debug
```
This used to be fine until I upgraded to DuckDB v0.10.0.

On my AArch64 machine (Mac multipass vm), it emits the following error on linking:
```
aarch64-linux-gnu-g++ gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-aarch64-3.10/duckdb_python.o ... (many object files)

      ld: error: cannot open gcc: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/aarch64-linux-gnu-g++' failed with exit code 1
```
which is weird since the compiler appeared twice in the command (`aarch64-linux-gnu-g++` and  `gcc`), which leads to the linking error.

If I don't use `ccache` (i.e. `export CC="ccache gcc"`) it successfully builds. I used to use `CXX=/usr/bin/clang++` for faster compilation, it gives:
```
/usr/bin/clang++ gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-aarch64-3.10/duckdb_python.o ... (many object files)
```
So, I managed to solve this problem by setting `CXX=` (i.e. to nothing). I'd like to report this problem, given that this linking problem isn't present on a x86_64 machine.

### To Reproduce

See above.

### OS:

Ubuntu 22.04.2 LTS, aarch64

### DuckDB Version:

v.0.10.0

### DuckDB Client:

Python

### Full Name:

Mark

### Affiliation:

bq

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @code1704, thanks for reporting this. Unfortunately, [debug builds are out of scope](https://duckdblabs.com/news/2023/10/02/support-policy#debug-builds) in the community support policy.
