### ISSUE TITLE
Out of buffer error when querying parquet file created from a JOIN query

### ISSUE THREAD

**Issue by mustafahasankhan** [duckdb/duckdb#11084]
### What happens?

I have some parquet files. 
I am facing `duckdb.duckdb.Error: Invalid Error: Out of buffer` when querying them.

Points worth to mention.
- It only occurs when I create a parquet file from a select query using COPY statement and try to query that file.
Like, this example works:
```python
import duckdb
duckdb.sql("""
CREATE VIEW assets AS SELECT * FROM read_parquet('assets.parquet');
CREATE VIEW st AS SELECT * FROM read_parquet('st.parquet');
COPY (
    SELECT 
               *
            FROM st
            JOIN assets a ON a.table_name LIKE CONCAT(st.table_name_pattern, '%')
               AND a.qf LIKE st.qf_pattern
               AND a.type_name <> 'Column'
) to 'result.parquet';

SELECT * FROM read_parquet('result.parquet')""").show()
```
but as in reproducible example below, it does not.
- If I explicitly specify columns in the SELECT query I see same issue but if I don't include `asset` column it works.

### To Reproduce

[Archive.zip](https://github.com/duckdb/duckdb/files/14558006/Archive.zip)
1. Extract Archive.zip into '/tmp' folder
2. Run the following query
```
duckdb.sql("""
CREATE VIEW assets AS SELECT * FROM read_parquet('/tmp/assets.parquet');
CREATE VIEW st AS SELECT * FROM read_parquet('/tmp/st.parquet');
COPY (
    SELECT 
               *
            FROM st
            JOIN assets a ON a.table_name LIKE CONCAT(st.table_name_pattern, '%')
               AND a.qf LIKE st.qf_pattern
               AND a.type_name <> 'Column'
) to '/tmp/result.parquet';

SELECT * FROM read_parquet('/tmp/result.parquet')""").show()
```
3. Notice that it throws out of buffer error.

### OS:

Mac M1 (Sonoma)

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Mustafa Hasan Khan

### Affiliation:

Atlan

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks, we can confirm that this is a bug.

**Comment by Mytherin** [comment]
Thanks for reporting - this should be fixed in https://github.com/duckdb/duckdb/pull/11094
