### ISSUE TITLE
Error: Unsupported compression function type

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb#11097]
### What happens?

I try to drop a table that is newly been filled up, in a database that has recently been created with a high amount of data inserted. I have tried to exit the CLI program and go in again etc but the problem persists. Also when trying a select I get the same error.

While I do not know if it is related to this, I had my process to insert into this table killed twice due to going low on ram (before changing the code to insert per year instead of all at once). Any lock issues seem to have been resolved, but maybe not?

Its obviously hard to reproduce, but if anything it would be interesting if the error message could be fleshed out and/or I could get help to dig around a bit to see whats wrong.

### To Reproduce

```
D drop table mytable_downsampled;

drop table mytable_downsampled;

Run Time (s): real 0.002 user 0.000488 sys 0.001241

Error: TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported compression function type

```
```
D select * FROM mytable_downsampled limit 1;
select * FROM mytable_downsampled limit 1;
Run Time (s): real 0.007 user 0.008424 sys 0.000000
Error: INTERNAL Error: Unsupported compression function type
```
Interestingly - a query to the failing table means that other tables fail, even though it works to query before:

```
D SELECT * FROM abv limit 1;
SELECT * FROM abv limit 1;
....(result)
Run Time (s): real 0.102 user 0.083785 sys 0.149879
D select * FROM mytable_downsampled limit 1;
select * FROM mytable_downsampled limit 1;
Run Time (s): real 0.004 user 0.005554 sys 0.002008
Error: INTERNAL Error: Unsupported compression function type
D SELECT * FROM abv limit 1;
SELECT * FROM abv limit 1;
Run Time (s): real 0.006 user 0.005995 sys 0.000000
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "INTERNAL Error: Unsupported compression function type"
```
### OS:

Ubuntu x64

### DuckDB Version:

0.10

### DuckDB Client:

DuckDB CLI 

### Full Name:

Bjørnar Brende Smestad

### Affiliation:

NTNU

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by bjornasm** [comment]
> Thanks for the report! I believe this has already been fixed on the latest nightly build. Could you perhaps try downloading the [nightly build](https://duckdb.org/docs/installation/?version=main&environment=cli&platform=macos&download_method=package_manager) and checking if the issue persists?

Thank you! If I am not mistaken this was triggered by the process running out of memory - but if the nightly build can open the database from the previous version I can download and check!

**Comment by Mytherin** [comment]
It can indeed. If the issue persists some more details or a data set would be very helpful.

**Comment by hannes** [comment]
Please reopen if issue persists with latest version
