### ISSUE TITLE
Insert or ignore throws error when inserting several constraint violating values

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb#11102]
### What happens?

This was a little rabbit hole, that started out as getting errors when inserting rows that violates some constraint even though using insert or ignore. After some debugging I think I have some grasp on the problem:

When you try to insert into a table with constraints you get an error if **several** of the rows you are inserting are violating the constraints, even though you use `INSERT OR IGNORE` or `ON CONFLICT DO NOTHING`. I think I have read something about this behavior before, however I cant find it. The error message I get, `Error: Invalid Input Error: ON CONFLICT DO UPDATE can not update the same row twice in the same command.`, points to a bug in the implementation as I do not try to update.

```sql
INSERT INTO TBL VALUES (1,42), (4,84), (1,23) ON CONFLICT DO NOTHING;
```
```text
Error: Invalid Input Error: ON CONFLICT DO UPDATE can not update the same row twice in the same command. Ensure that no rows proposed for insertion within the same command have duplicate constrained values
```

Being able to do INSERT OR IGNORE for a large number of rows, with possibly more than one violation, without stopping the whole transaction would be very beneficial obviously. See under for examples. I hope we are not forced to do row for row inputs if we want to input to a table with constraints.

### To Reproduce

Works with only one violation:
```sql
CREATE TABLE tbl (i INT PRIMARY KEY, j INT);
INSERT INTO tbl VALUES (1, 42);
INSERT INTO tbl VALUES (1, 84) ON CONFLICT DO NOTHING;
INSERT INTO tbl VALUES (3,42), (1,84) ON CONFLICT DO NOTHING;
INSERT INTO tbl VALUES (1,42), (4,84) ON CONFLICT DO NOTHING;
```
Fails with two violations (notice the error message):
```sql
CREATE TABLE tbl (i INT PRIMARY KEY, j INT);
INSERT INTO tbl VALUES (1, 42);
INSERT INTO tbl VALUES (1,42), (1,84) ON CONFLICT DO NOTHING;
```
```text
Error: Invalid Input Error: ON CONFLICT DO UPDATE can not update the same row twice in the same command. Ensure that no rows proposed for insertion within the same command have duplicate constrained values
```
```sql
INSERT INTO tbl VALUES (1,42), (4,84), (1,23) ON CONFLICT DO NOTHING;
```
```text
Error: Invalid Input Error: ON CONFLICT DO UPDATE can not update the same row twice in the same command. Ensure that no rows proposed for insertion within the same command have duplicate constrained values
```
```sql
INSERT OR IGNORE INTO tbl VALUES (1,42), (4,84), (1,23);
```
```text
Error: Invalid Input Error: ON CONFLICT DO UPDATE can not update the same row twice in the same command. Ensure that no rows proposed for insertion within the same command have duplicate constrained values
```

### OS:

Ubuntu x64

### DuckDB Version:

0.10

### DuckDB Client:

DuckDB CLI

### Full Name:

Bjørnar Brende Smestad

### Affiliation:

NTNU

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for the detailed report, this is however currently an expected limitation of our upsert implementation.
Our upsert handles constraint violations between existing data and new data, it seems your constraint violations are between new data (i.e you have duplicate rows in your new data)

I suggest using DISTINCT ON to filter out the duplicates in your new data.

**Comment by bjornasm** [comment]
Thank you @Tishj - wow that solves this problem perfectly, I was not aware of DISTINCT ON.

[DISTINCT ON Clause](https://duckdb.org/docs/sql/query_syntax/select#distinct-on-clause)
```
-- select only the highest population city for each country
SELECT DISTINCT ON(country) city, population
FROM cities
ORDER BY population DESC;

The DISTINCT ON clause returns only one row per unique value in the set of expressions as defined in the ON clause. If an ORDER BY clause is present, the row that is returned is the first row that is encountered as per the ORDER BY criteria. If an ORDER BY clause is not present, the first row that is encountered is not defined and can be any row in the table.
```

Should it be mentioned in the docs that upsert have to have no duplicate rows (per the target tables constraints), and that DISTINCT ON is the way to go?

**Comment by Tishj** [comment]
> Should it be mentioned in the docs that upsert have to have no duplicate rows (per the target tables constraints), and that DISTINCT ON is the way to go?

That's a good idea, that would help combat this common pitfall until we fix this limitation 👍
