### ISSUE TITLE
Index error when reading pandas DataFrame

### ISSUE THREAD

**Issue by one800hotline** [duckdb/duckdb#11107]
### What happens?

I am pulling data from a _postgre DB 12.17_ RDS in AWS using _Docker_ and _python:3.12.0-slim_ image and _Pandas 2.2.1_. When I have loaded 4 different tables into _pandas DataFrame_, I try and query them using _duckdb 0.10.0_, but I get a strange error like below, for 3 of the 4 tables. Error from table below has 3280 rows:

IndexError: index 3280 is out of bounds for axis 0 with size 3280.

### To Reproduce

Cant reproduce error given the facit that I am pulling data which is company sensitive and tables are large, residing in a closed off environment. The code for getting error on one of the _pandas DataFrame_ is below:

`duckdb.query("""select * from df_buyer_new""")`

Producing the following error:
![image](https://github.com/duckdb/duckdb/assets/22394862/3a92bb38-be48-4b92-a452-fd1036e7814e)

### OS:

Ubuntu server 18.04 x86

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Patrik B

### Affiliation:

Visma

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Sounds like it's already fixed by https://github.com/duckdb/duckdb/pull/10768
