### ISSUE TITLE
Maps can't handle NULL keys or values

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#11115]
### What happens?

```sql
SELECT MAP(NULL::INT[], [1, 2, 3]); 
--- Binder Error: Key and value list sizes don't match
SELECT MAP([1,2,3], NULL::INT[]);
--- Binder Error: Key and value list sizes don't match
SELECT MAP(NULL::INT[], NULL::INT[]);
--- results in {}, I would expect NULL
--- This only is apparent in the CLI version.
--- If I try this on shell.duckdb.org, you can't see a result as a result of unrelated bug https://github.com/duckdb/duckdb-wasm/issues/1671
--- As a workaround to that bug:
SELECT MAP(NULL::INT[], NULL::INT[]) IS NULL;
--- gives false, should be true
```

I would expect all of these to give me NULL

### To Reproduce

see above

### OS:

shell.duckdb.org

### DuckDB Version:

0.10.0

### DuckDB Client:

@duckdb/duckdb-wasm@1.28.1-dev166.0

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by NickCrews** [comment]
@szarnyasg Note I just updated the original post, I originally thought `SELECT MAP(NULL::INT[], NULL::INT[]);` gave NULL, but it actually gives `{}`. So that is also incorrect.

**Comment by NickCrews** [comment]
oooh, I just tested on `0.10.1-dev1206`, and now the errors are slightly different (but I think still incorrect):

```python
# https://github.com/duckdb/duckdb/issues/11117
import duckdb

print(duckdb.__version__)
# 0.10.1-dev1206

conn = duckdb.connect(":memory:")

try:
    conn.sql("SELECT MAP(NULL::INT[], [1, 2, 3]);").fetchall()
except Exception as e:
    print(e)
    # Invalid Input Error: The list of map keys must not be NULL.

try:
    conn.sql("SELECT MAP([1, 2, 3], NULL::INT[]);").fetchall()
except Exception as e:
    print(e)
    # Invalid Input Error: The list of map values must not be NULL.

print(conn.sql("SELECT MAP(NULL::INT[], NULL::INT[]);"))
# ┌───────────────────────────────────────────────────────┐
# │ map(CAST(NULL AS INTEGER[]), CAST(NULL AS INTEGER[])) │
# │                 map(integer, integer)                 │
# ├───────────────────────────────────────────────────────┤
# │ {}                                                    │
# └───────────────────────────────────────────────────────┘
```

**Comment by Tishj** [comment]
Thanks for the report, but this is expected behavior as far as we are concerned, is there a good reason to change this?

**Comment by NickCrews** [comment]
It feels inconsistent with the NULL propagation behavior with many other functions. For example `SELECT map_from_entries(NULL) IS NULL;` gives `true`. Especially the last (null, null) -> {} behavior is weird. Is there another example of a constructor-like function that takes all nulls and gives a non-null that I'm not thinking of? In https://github.com/ibis-project/ibis/pull/8649 I am adding workarounds to Ibis to make duckdb behave the same as the other backends.

Does the current behavior have inherent advantages, or is it just that we should prefer stability, and so we should lean towards the status quo?

**Comment by NickCrews** [comment]
@gforsyth @cpcloud in case they have thoughts

**Comment by cpcloud** [comment]
Trino is probably the database I'm aware of that supports generic maps and adheres to a pretty rigorous interpretation of SQL and is relatively close to DuckDB in terms of semantics and SQL functionality.

Their `MAP` constructor returns `NULL` if any argument is `NULL`.

```
trino:default> select map(null, null);
 _col0
-------
 NULL
(1 row)

Query 20240319_181750_02725_36bw5, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.07 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> select map(null, array[1]);
 _col0
-------
 NULL
(1 row)

Query 20240319_181922_02782_36bw5, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.03 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> select map(array[1], null);
 _col0
-------
 NULL
(1 row)
```

**Comment by cpcloud** [comment]
Empty map doesn't really makes sense IMO since `NULL` in nearly every other case functions as "unknown", and so you can't say whether the keys, values, or both are empty or not.

**Comment by cpcloud** [comment]
@Tishj Friendly ping here, duckdb differs from every other engine that supports nullable maps AFAICT (Trino, PySpark, Snowflake).

**Comment by Tishj** [comment]
I ran these through PySpark because I could not get Trino to function locally in a reasonable enough time (might need to go the docker route, I've seen that that is less painful)

```py
>>> con.sql("SELECT MAP(CAST(NULL AS ARRAY<INT>), CAST(NULL AS ARRAY<INT>)) IS NULL").show()
+-------------------------+
|(map(NULL, NULL) IS NULL)|
+-------------------------+
|                    false|
+-------------------------+
```

```py
>>> con.sql("SELECT MAP(CAST(NULL AS ARRAY<INT>), CAST(NULL AS ARRAY<INT>))").show()
pyspark.errors.exceptions.captured.SparkRuntimeException: [NULL_MAP_KEY] Cannot use null as map key.
```

```py
>>> con.sql("SELECT MAP(CAST(NULL AS ARRAY<INT>), ARRAY(1, 2, 3))").show()
pyspark.errors.exceptions.captured.SparkRuntimeException: [NULL_MAP_KEY] Cannot use null as map key.
```

```py
>>> con.sql("SELECT MAP(ARRAY(1, 2, 3), CAST(NULL AS ARRAY<INT>))").show()
+-------------------------+
|map(array(1, 2, 3), NULL)|
+-------------------------+
|      {[1, 2, 3] -> NULL}|
+-------------------------+
```

**Comment by Tishj** [comment]
```py
con.sql("SELECT map_from_entries(ARRAY(STRUCT(NULL, NULL), STRUCT(NULL, NULL)))").show()
pyspark.errors.exceptions.captured.SparkRuntimeException: [NULL_MAP_KEY] Cannot use null as map key.
```

```py
>>> con.sql("SELECT map_from_entries(ARRAY(STRUCT(NULL, NULL), STRUCT(NULL, NULL))) IS NULL").show()
+-------------------------------------------------------------------------+
|(map_from_entries(array(struct(NULL, NULL), struct(NULL, NULL))) IS NULL)|
+-------------------------------------------------------------------------+
|                                                                    false|
+-------------------------------------------------------------------------+
```

Actually this is still not equivalent to our MAP function, for that we need MAP_FROM_ARRAYS

**Comment by Tishj** [comment]
```py
>>> con.sql("SELECT map_from_arrays(CAST(NULL AS ARRAY<INT>), CAST(NULL AS ARRAY<INT>))").show()
+---------------------------+
|map_from_arrays(NULL, NULL)|
+---------------------------+
|                       NULL|
+---------------------------+
```

**Comment by Tishj** [comment]
@cpcloud I've made a PR that should make our behavior compatible with the other systems you mentioned 👍 
Thanks for the reminder, it sort of fell through the cracks / I wasn't entirely sure what the action should be at the time
