### ISSUE TITLE
Parser Error: `SELECT [1,2,3][1];`

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#11120]
### What happens?

This gives `Parser Error: syntax error at or near "["`

however, `SELECT list_value(1,2,3)[1];` works fine.

### To Reproduce

run that in https://shell.duckdb.org/

### OS:

https://shell.duckdb.org/

### DuckDB Version:

0.10.0

### DuckDB Client:

https://shell.duckdb.org/

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report - but this already works in the nightly build:

```sql
SELECT [1,2,3][1];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[1] │
│            int32            │
├─────────────────────────────┤
│                           1 │
└─────────────────────────────┘
```

**Comment by NickCrews** [comment]
Oops, I'm sorry, I thought shell.duckdb.org was nightly. Thank you!
