### ISSUE TITLE
crashed when do insertorupdate becasue of assert in a large db

### ISSUE THREAD

**Issue by xubobbs** [duckdb/duckdb#11124]
### What happens?

my test db work fine for server days .and today I use insertOrReplace some data .is seems no any error. but when test again ,and use the same data for doing insertOrreplace, error happend. I build a debug so ,and change the test code ,it throw a assert , 
INTERNAL Error: Assertion triggered in file "/home/xubo/go/src/testcode/duckdb/duckdbLib/duckdb/src/storage/compression/string_uncompressed.cpp" on line 406: dict_offset >= -1 * int32_t(Storage::BLOCK_SIZE) && dict_offset <= int32_t(Storage::BLOCK_SIZE)  and I debug the value of dict_offset ,it is -925352919

this db file has ten tables .and each tables has 200 ,000 rows data . and each test will do some data insertorreplace. this test db file size is near 1G size.

### To Reproduce

int main(int argc, char **argv)
{
  DuckDB db("/home/xubo/preload_duckdb.db");

  Connection con(db);
  std::string test_sql = "INSERT INTO dsmock_group_tree (_id, tree_id, org_id, asset_id, updated_at, deleted_at) VALUES ('1492bbd9-6a8a-4f62-9751-71ad1afc4828', '9fd27437-887b-424b-8f61-9eb8fd9607e0', 276195621352, 276195621352, 1709260345874609, 0) ON CONFLICT (_id) DO UPDATE SET tree_id=EXCLUDED.tree_id, org_id=EXCLUDED.org_id, asset_id=EXCLUDED.asset_id, updated_at=EXCLUDED.updated_at, deleted_at=EXCLUDED.deleted_at ";
  auto result = con.Query(test_sql);
  result->Print();
  con.~Connection();
  db.~DuckDB();
  std::this_thread::sleep_for(std::chrono::hours(1));
  exit(1);
}

### OS:

x86 linux

### DuckDB Version:

latest

### DuckDB Client:

c++

### Full Name:

bo,xu

### Affiliation:

qianxin.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by xubobbs** [comment]
void UncompressedStringStorage::StringScanPartial(ColumnSegment &segment, ColumnScanState &state, idx_t scan_count,
                                                  Vector &result, idx_t result_offset) {
	// clear any previously locked buffers and get the primary buffer handle
	auto &scan_state = state.scan_state->Cast<StringScanState>();
	auto start = segment.GetRelativeIndex(state.row_index);

	auto baseptr = scan_state.handle.Ptr() + segment.GetBlockOffset();
	auto dict = GetDictionary(segment, scan_state.handle);
	auto base_data = reinterpret_cast<int32_t *>(baseptr + DICTIONARY_HEADER_SIZE);
	auto result_data = FlatVector::GetData<string_t>(result);

	int32_t previous_offset = start > 0 ? base_data[start - 1] : 0;

	for (idx_t i = 0; i < scan_count; i++) {
		// std::abs used since offsets can be negative to indicate big strings
		uint32_t string_length = std::abs(base_data[start + i]) - std::abs(previous_offset);
		result_data[result_offset + i] =
		    FetchStringFromDict(segment, dict, result, baseptr, base_data[start + i], string_length);

-->here I dump the debug:
scan_count
105
string_length
925352919
segment
{...}
duckdb::SegmentBase<duckdb::ColumnSegment> (base):
duckdb::SegmentBase<duckdb::ColumnSegment>
db:
{...}
type
type_size:
16
segment_type:
duckdb::PERSISTENT
function
stats
block:
std::shared_ptr (count 15, weak 1) 0x808248
block_id:
2452
offset:
180912
segment_size:
262136
segment_state

**Comment by xubobbs** [comment]
.schema dsmock_group_tree 
CREATE TABLE dsmock_group_tree(_id VARCHAR PRIMARY KEY, tree_id VARCHAR NOT NULL DEFAULT(''), org_id BIGINT NOT NULL DEFAULT(0), asset_id BIGINT NOT NULL DEFAULT(0), updated_at BIGINT NOT NULL DEFAULT(0), deleted_at BIGINT NOT NULL DEFAULT(0));
select count(1) from dsmock_group_tree; it work ok and got  result:
┌──────────┐
│ count(1) │
│  int64   │
├──────────┤
│      105 │
└──────────┘
 select org_id from dsmock_group_tree ; it ok 
select asset_id from dsmock_group_tree ;it ok 
but  select tree_id from dsmock_group_tree it crashed by the assert

**Comment by Tishj** [comment]
Please make a reproducable example, I have extracted the following queries from your report, with those I can't reproduce the issue, please adjust where necessary
```
statement ok
CREATE TABLE dsmock_group_tree(
    _id VARCHAR PRIMARY KEY,
    tree_id VARCHAR NOT NULL DEFAULT(''),
    org_id BIGINT NOT NULL DEFAULT(0),
    asset_id BIGINT NOT NULL DEFAULT(0),
    updated_at BIGINT NOT NULL DEFAULT(0),
    deleted_at BIGINT NOT NULL DEFAULT(0)
)

statement ok
INSERT INTO dsmock_group_tree (
	_id,
	tree_id,
	org_id,
	asset_id,
	updated_at,
	deleted_at
) VALUES (
	'1492bbd9-6a8a-4f62-9751-71ad1afc4828',
	'9fd27437-887b-424b-8f61-9eb8fd9607e0',
	276195621352,
	276195621352,
	1709260345874609,
	0
)
ON CONFLICT (
	_id
) DO UPDATE SET
	tree_id = EXCLUDED.tree_id,
	org_id = EXCLUDED.org_id,
	asset_id = EXCLUDED.asset_id,
	updated_at = EXCLUDED.updated_at,
	deleted_at = EXCLUDED.deleted_at
```

(note `statement ok` is syntax for our unittester, you can disregard those)

**Comment by xubobbs** [comment]
I can give you my test db .but it is over 1G size .how can I send it to you ?

**Comment by xubobbs** [comment]
I test I can drop some table,and it still keep crash when i use the test sql .hope the total file size can get smaller

**Comment by xubobbs** [comment]
this file is still 800M ... how can I send it to you?

**Comment by Tishj** [comment]
Feel free to send it to me at thijs@duckdblabs.com, using something like wetransfer.com should work

**Comment by xubobbs** [comment]
got it and send the downlink link mail to you

**Comment by xubobbs** [comment]
> Feel free to send it to me at [thijs@duckdblabs.com](mailto:thijs@duckdblabs.com), using something like wetransfer.com should work Note that I am making an exception this one time

hi..I’m wondering if you received my email last week

**Comment by Tishj** [comment]
> > Feel free to send it to me at [thijs@duckdblabs.com](mailto:thijs@duckdblabs.com), using something like wetransfer.com should work Note that I am making an exception this one time
> 
> hi..I’m wondering if you received my email last week

I replied and asked you to send it through another service, Baidu is not something we can use, can you use SendBig? That should be available in china as well

**Comment by xubobbs** [comment]
has send db to you by sendbig .thanks

**Comment by Tishj** [comment]
I received the file and can indeed reproduce the issue, but since the error occurs in decompression, there's too little information for us to work with.

Please let us know if you can make a minimal reproduction of steps that can cause this error to occur when performed on a clean database

**Comment by xubobbs** [comment]
maybe I need do a test demo for reproduce this .because I also don't know what happend before this issue.but in my test env , it happened twice ..

----- 原始邮件 -----
发件人：Thijs ***@***.***>
收件人：duckdb/duckdb ***@***.***>
抄送人：xubobbs ***@***.***>,  Author ***@***.***>
主题：Re: [duckdb/duckdb] crashed when do insertorupdate becasue of assert in a large db (Issue #11124)
日期：2024年03月20日 21点36分


I received the file and can indeed reproduce the issue, but since the error occurs in decompression, there's too little information for us to work with.
Please let us know if you can make a minimal reproduction of steps that can cause this error to occur when performed on a clean database

**Comment by fanvanzh** [comment]
I also meet this problem.
for this code:
 `uint32_t string_length = std::abs(base_data[start + i]) - std::abs(previous_offset);`
string_length is a overflow uint32 if   std::abs(base_data[start + i]) < std::abs(previous_offset);

@Tishj
