### ISSUE TITLE
NOT NULL constraint leads to unjustified error in "INSERT INTO ... ON CONFLICT DO UPDATE"

### ISSUE THREAD

**Issue by lschneiderbauer** [duckdb/duckdb#11147]
### What happens?

"INSERT INTO ... DO UPDATE" throws a "NOT NULL constraint failed" error when attempting to update columns not including the NOT NULL constrained column.

For the user perspective no contstraint violation has occured (since the values are NOT NULL before and after the transaction) and the transaction should be accepted.

### To Reproduce

``` SQL
  CREATE TABLE t1 (id INT PRIMARY KEY, val1 DOUBLE, val2 DOUBLE NOT NULL);
  CREATE TABLE t2 (id INT PRIMARY KEY, val1 DOUBLE);
  INSERT INTO t1 VALUES (1, 2, 3);
  INSERT INTO t2 VALUES (1, 5);
  
  INSERT INTO t1 BY NAME (SELECT * FROM t2)
    ON CONFLICT DO UPDATE
    SET val1 = EXCLUDED.val1;
    
  SELECT * FROM t1;
```
leads to
> Constraint Error: NOT NULL constraint failed: t1.val2

If there are no NOT NULL constraints, it is happily accepted:
 ``` SQL
  CREATE TABLE t1 (id INT PRIMARY KEY, val1 DOUBLE, val2 DOUBLE);
  CREATE TABLE t2 (id INT PRIMARY KEY, val1 DOUBLE);
  INSERT INTO t1 VALUES (1, 2, 3);
  INSERT INTO t2 VALUES (1, 5);
  
  INSERT INTO t1 BY NAME (SELECT * FROM t2)
    ON CONFLICT DO UPDATE
    SET val1 = EXCLUDED.val1;
    
  SELECT * FROM t1;
```
>   id val1 val2
>   1    5    3
(and no NULL values occur)

### OS:

MS Windows 11, x64

### DuckDB Version:

0.9.2

### DuckDB Client:

R

### Full Name:

Lukas Schneiderbauer

### Affiliation:

None

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @lschneiderbauer this is currently an expected restriction. We'll clarify the documentation.
