### ISSUE TITLE
CSVRead( ..., ignore_errors = true) does not work?

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11153]
### What happens?

```sql
CREATE TABLE venue (
    venueid          SMALLINT        NOT NULL /*PRIMARY KEY*/
    , venuename      VARCHAR (100)
    , venuecity      VARCHAR (30)
    , venuestate     CHAR (2)
    , venueseats     INTEGER
)
;

INSERT INTO venue SELECT * FROM read_csv('venue_pipe.txt', ignore_errors = true);
```

Please why would that still fail instead of skipping the rows:
```
java.sql.SQLException: Conversion Error: Could not convert string '\' to INT32
	at org.duckdb.DuckDBNative.duckdb_jdbc_execute(Native Method)
```

### To Reproduce

Download: https://docs.aws.amazon.com/redshift/latest/gsg/samples/tickitdb.zip
Read `venue_pipe.txt` into a table via CSV.

### OS:

Linux

### DuckDB Version:

0.10.0

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @manticore-projects, thanks for raising this issue. Can you please share the `CREATE TABLE` SQL command you used to create the schema of the `venue` table? Using "create table as select" (CTAS) works fine for me:

```sql
CREATE TABLE venue AS SELECT * FROM read_csv('venue_pipe.txt', ignore_errors = true);
```

```
DESCRIBE venue;
```
```text
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ column0     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ column1     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ column2     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ column3     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ column4     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

**Comment by manticore-projects** [comment]
Apologies, here is the DDL according to https://docs.aws.amazon.com/redshift/latest/dg/r_venuetable.html

```sql
CREATE TABLE venue (
    venueid          SMALLINT        NOT NULL /*PRIMARY KEY*/
    , venuename      VARCHAR (100)
    , venuecity      VARCHAR (30)
    , venuestate     CHAR (2)
    , venueseats     INTEGER
)
;
```

They mention: "Maximum number of seats available at the venue, if known, such as 73200. For demonstration purposes, this column contains some null values and zeroes. "


In the meantime, I have to work around this by cleaning those "null values":
```java
              // remove some silly '\N' entries since
              // @todo: find a better way to clean those CSVs
              try {
                ProcessBuilder processBuilder =
                    new ProcessBuilder("sed", "-i", "s/\\\\N//g", outputFile.getAbsolutePath());
                Process process = processBuilder.start();
                int exitCode = process.waitFor();
              } catch (InterruptedException e) {
                throw new RuntimeException(e);
              }
```

**Comment by szarnyasg** [comment]
Thanks, I could reproduce the issue. We'll take a look.

**Comment by pdet** [comment]
Thanks for the report @manticore-projects. Indeed `ignore_errors` should skip this conversion.

Semi-related, from your description, I imagine that what you really want is the `nullstr = '\N'` option, no?

**Comment by manticore-projects** [comment]
Thank you very much for quick round turn.
Honestly, this came up only during unit tests for a Redshift/Big Query/Snowflake SQL into DuckDB SQL Transpiler since we use that public sample for testing.

So yes, I think `nullstr = '\N'` would make a lot of sense, but just ignoring the cell would also work for me.

Also, this would be a good time to synchronize the documentation on CSV options between `ReadCSV()` and `COPY ... FROM ..`. I am still confused if `ignore_errors` would work with `COPY ... FROM ...` or not.

Thanks a lot for your effort agin.
