### ISSUE TITLE
Syntax error near ? when use prepared statement with operator 'in'

### ISSUE THREAD

**Issue by zillionare** [duckdb/duckdb#11158]
### What happens?

prepare statement doesn't allow parameter appears after operator `in`. For example, my query is:

```python
sql = "select * from bars_cache_status where symbol in ? and frame_type=?"
cursor.execute(sql, (symbols, 6))
```
will raise error:

![图片](https://github.com/duckdb/duckdb/assets/7206696/7794c1f6-4597-45e8-b7f0-c4fbda617b84)

if I use this one:

```python
sql = "select * from bars_cache_status where symbol in ('000001.SZ', '000002.SZ') and frame_type=?"
cursor.execute(sql, (symbols, 6))
```
duckdb will be happy.

However, symbols maybe a very large list, so I'm afraid I can't hardcode it into sql clause.

So is this a feature not supported yet, or just I don't know how to use `in` operator and prepare statement together?

### To Reproduce

1. create the following table:
```bash
duckdb test.duckdb
```
```sql
CREATE SEQUENCE IF NOT EXISTS bars_cache_status_id;
create table if not exists bars_cache_status (
    "id" INT default nextval('bars_cache_status_id') primary key,
    "start" date,
    "stop" date,
    "symbol" string, --同步的证券代码
    "frame_type" int  --记录属于哪个周期。1分钟和1天允许不一样的起点
);

insert into bars_cache_status (start, stop, SYMBOL, frame_type) values (
    '2022-01-01', '2024-01-01', '000001.SZ', 6);
insert into bars_cache_status (start, stop, SYMBOL, frame_type) values (
    '2022-01-01', '2024-01-01', '000004.SZ', 6);
```
2. execute the following code:
```python
import duckdb
con = duckdb.connect("test.duckdb")

symbols = ("000001.SZ", "000002.sz")

with con.cursor() as cursor:
    sql = "select * from bars_cache_status where symbol in ? and frame_type=?"
    query = cursor.execute(sql, (symbols, 6))
    records = query.fetchnumpy()

```

### OS:

windows

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Aaron Yang

### Affiliation:

NA

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I believe this needs to be `IN (?)`

**Comment by Mytherin** [comment]
Currently this is expected behavior, and matches Postgres' behavior:

```sql
postgres=# PREPARE v1 AS SELECT 42 IN $1;
ERROR:  syntax error at or near "$1"
LINE 1: PREPARE v1 AS SELECT 42 IN $1;
                                   ^

```

You can use `unnest` in a subquery here if you want to pass in a list/array:

```sql
D PREPARE v1 AS SELECT 42 IN (SELECT UNNEST(?)) AS result;
D EXECUTE v1([1,2,3,4,5]);
┌─────────┐
│ result  │
│ boolean │
├─────────┤
│ false   │
└─────────┘
D EXECUTE v1([1,2,3,4,5,42]);
┌─────────┐
│ result  │
│ boolean │
├─────────┤
│ true    │
└─────────┘

```
