### ISSUE TITLE
CSV incorrectly imports files with rows having fewer commas

### ISSUE THREAD

**Issue by dioptre** [duckdb/duckdb#11164]
### What happens?

Consider a file:
```
h1,h2,h3
a,b,c
d,
```

The file sees the import as broken, or if ignore_errors are on, removes the row starting with d.

### To Reproduce

See above

### OS:

m2

### DuckDB Version:

0.10.0

### DuckDB Client:

python

### Full Name:

Andrew Grosser

### Affiliation:

Sourcetable

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @dioptre, could you please share the SQL statements (optionally with the surrounding shell/Python script) that reproduce the issue?

**Comment by dioptre** [comment]
```
CREATE TABLE x AS SELECT * FROM read_csv('/asddas/aas.csv'); 
```

The issue is with the CSV parser, not the SQL 

Thanks!

**Comment by szarnyasg** [comment]
> The file sees the import as broken, or if ignore_errors are on, removes the row starting with d.

This is expected behavior. The CSV file is too small for the CSV dialect detection to work if one of the two rows is malformed (it has one less comma than it should). For CSV files that are both small and have malformed rows, I recommend manually creating the table and loading the data manually (with/without ignore_errors, depending on your use case).

**Comment by dioptre** [comment]
That was just an example - the original file has 60k rows (can't share due to proprietary data).

Missing commas does not seem like a reason for a malformed csv.

Seems like the importer needs to be fixed over creating a manual process for all people with this type of csv. I think this could be solved with a one liner and if it's an effort thing, perhaps I can submit a pr?

**Comment by hello-world-bfree** [comment]
In these cases, it's typical to run a quick shell command on the file to inject the missing commas before parsing the csv file:

`awk 'BEGIN{FS=OFS=","} {NF=4; print}' file `

That would ensure there are four commas in the file.

**Comment by cmdlineluser** [comment]
In case it is of any interest, here are some of the other common CSV readers:

pyarrow considers it malformed and raises.

```python
pyarrow.csv.read_csv("broken.csv")
# ArrowInvalid: CSV parse error: Expected 3 columns, got 2: d,
```

Both pandas and Polars "fill" the missing column.

```python
pd.read_csv("broken.csv")
#   h1   h2   h3
# 0  a    b    c
# 1  d  NaN  NaN
```

```python
pl.read_csv("broken.csv")
# shape: (2, 3)
# ┌─────┬──────┬──────┐
# │ h1  ┆ h2   ┆ h3   │
# │ --- ┆ ---  ┆ ---  │
# │ str ┆ str  ┆ str  │
# ╞═════╪══════╪══════╡
# │ a   ┆ b    ┆ c    │
# │ d   ┆ null ┆ null │
# └─────┴──────┴──────┘
```

**Comment by dioptre** [comment]
Thanks for the comparison @cmdlineluser seems like others are doing what makes sense.

@hello-world-bfree the problem with this/or other pre-fixing methods is that the file needs to be read/written to & analyzed for fields at least twice. This is a non trivial operation esp when the csv sizes exceed 1M/1B rows.

It feels (at least for me) that if the vectors assume the correct number of values per row, lack of commas should just fill in nulls per Polars.

**Comment by Mytherin** [comment]
You can use the [`null_padding` option](https://duckdb.org/docs/data/csv/overview.html) to enable this behavior if desired:

```sql
D from read_csv('test.csv', null_padding=true, header=True);
┌─────────┬─────────┬─────────┐
│   h1    │   h2    │   h3    │
│ varchar │ varchar │ varchar │
├─────────┼─────────┼─────────┤
│ a       │ b       │ c       │
│ d       │ NULL    │ NULL    │
└─────────┴─────────┴─────────┘
```

**Comment by dioptre** [comment]
Amazing! Thankyou!!!
