### ISSUE TITLE
Attaching a database with sequence fails

### ISSUE THREAD

**Issue by liveuser123** [duckdb/duckdb#11167]
### What happens?

When I try to attach a database with a sequence, it fails and throws an error saying "Sequence missing from catalog".

### To Reproduce

Create a table in a database with a sequence column
attach this database 

### OS:

ubuntu

### DuckDB Version:

0.10

### DuckDB Client:

Python

### Full Name:

Sam 

### Affiliation:

Freelancing

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @liveuser123, could you please share a reproducible example?
