### ISSUE TITLE
No Retry on S3 for HTTP 500 errors

### ISSUE THREAD

**Issue by jexp** [duckdb/duckdb#11166]
### What happens?

While loading a lot of files  from S3, I get an HTTP 500 error which aborts the CTAS

`HTTP Error: HTTP GET error on 'https://s3-logging.xxx.com.s3.amazonaws.com/downloads.xxx.com2024-02-02-11-21-59-18BAA8F106270BDF' (HTTP 500)`

Looking at the source code for httpfs.cpp it seems there is retry / backoff for a number of http status codes:  400, 418,  429, 503, 504, **but not 500**.

see https://github.com/duckdb/duckdb/blob/main/extension/httpfs/httpfs.cpp#L92-L147

the s3fs implementation just calls out to httpfs GetRequest, so it uses the same base code:
https://github.com/duckdb/duckdb/blob/main/extension/httpfs/s3fs.cpp#L766

Seems running duckdb on an ec2 instance with 8 cores, causes to exceed the s3 request limit of 5k requests / second.
I reduced the number of threads to 4, which at least allowed me to load the 775.000 files.

### To Reproduce

Here's a simple CTAS that reproduces it for me if you have a lot of small CloudFront log files on S3

```
create table s3_logs_raw as (
    SELECT
        col1,
        filename
    FROM
        -- Trick the CSV reader into reading as a single column
        read_csv(
            's3://s3-logging.xxx.com/downloads.xxx.com2024-*',
            columns={'col1': 'VARCHAR'},
            delim='^',ignore_errors=true, filename=true
        )
    WHERE contains(col1,'GET /') AND not contains(col1,'.yml ') AND not contains(col1,'.json ')
   );
```

### OS:

AWS Linux

### DuckDB Version:

v0.10.1-dev1244 0f4a300465

### DuckDB Client:

cli

### Full Name:

Michael Hunger

### Affiliation:

Neo4j

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ryguyrg** [comment]
FWIW, AWS specifically recommends retrying on 500: [How do I troubleshoot a HTTP 500 or 503 error from Amazon S3?](https://repost.aws/knowledge-center/http-5xx-errors-s3)
