### ISSUE TITLE
Progress bar jumps from 0% to 100% when working with multiple local CSV files

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb#11197]
### What happens?

Progress sits at 0% when copying in multiple CSV files regardless of the progress of the job and jumps to 100% when complete.

### To Reproduce

```sql
COPY trips FROM 'trips*.csv.gz';
```

### OS:

Ubuntu for Windows

### DuckDB Version:

main branch

### DuckDB Client:

CLI

### Full Name:

Mark Litwintschik

### Affiliation:

Green Idea

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by marklit** [comment]
Just an update on this. I'm trying to import ~100 of GZIP-compressed CSVs into DuckDB. After a few hours, the progress jumped to 46%. The DuckDB file was around 50 GB at this time.

**Comment by soerenwolfers** [comment]
Maybe related: https://github.com/duckdb/duckdb/issues/11071

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm the progress bar issue when importing gzipped CSV files - we'll have a look.

**Comment by marklit** [comment]
The issue is still present. Keep this issue open.

**Comment by carlopi** [comment]
I think PR that will solve this is https://github.com/duckdb/duckdb/pull/12728

**Comment by marklit** [comment]
This is rectified in v1.1.1 af39bd0dcf.

I imported a single file and the progress bar jumped between 40%, 81% and 97% over ~20 seconds. The second time it jumped between 37%, 79% and 97% when I imported the data again.

When importing 4 files it jumped between 12%, 20%, 24%, etc.. over ~5 minutes.

So it's not super granular but it's much better than before. Thanks for sorting this out.
