### ISSUE TITLE
Incorrect equality comparison for BIT type

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11211]
### What happens?

BIT equality comparison is broken (or at least inconsistent, in case I'm missing something).
_Originally posted by @orzom411 in https://github.com/duckdb/duckdb/discussions/10720_

### To Reproduce

```sql
FROM
(
  SELECT 
  ( 2::bit & 2::bit ) AS a, 
  2::bit AS b, 
  (a = b) AS '(a = b)',
)
SELECT a, b, a = b, "(a = b)";
```
```
┌──────────────────────────────────┬──────────────────────────────────┬─────────┬─────────┐
│                a                 │                b                 │ (a = b) │ (a = b) │
│               bit                │               bit                │ boolean │ boolean │
├──────────────────────────────────┼──────────────────────────────────┼─────────┼─────────┤
│ 00000000000000000000000000000010 │ 00000000000000000000000000000010 │ true    │ false   │
└──────────────────────────────────┴──────────────────────────────────┴─────────┴─────────┘
```

### OS:

Linux

### DuckDB Version:

0.10.1-dev717

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @soerenwolfers, thanks for opening this issue. I cannot reproduce this on Apple Silicon. Could you please help pin-point the issue by providing additional information:
1) Are you running it on Linux x86 or ARM64?
2) Is the issue deterministic?

**Comment by soerenwolfers** [comment]
Running on Linux x86 and it's deterministic

**Comment by szarnyasg** [comment]
Thanks! I could reproduce this on my MacBook when running Ubuntu in Docker, using the vanilla DuckDB CLI client.

**Comment by Mytherin** [comment]
Thanks for reporting! I have a fix up in https://github.com/duckdb/duckdb/pull/11231
