### ISSUE TITLE
Improve Node.js support

### ISSUE THREAD

**Issue by willium** [duckdb/duckdb#1122]
We're so excited to see [initial Node.js support](https://github.com/cwida/duckdb/pull/1112)—thank you @hannesmuehleisen!

Below is a list of some features we'd like to add (or partner with you to add, depending on your bandwidth/priorities):
- [ ] TypeScript types (can easily be based on [Sqlite3's types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sqlite3))
- [ ] Apache Arrow support (and/or typed columnar array output, IOW: ["Fetching DuckDB query results as Arrow Arrays"](https://github.com/cwida/duckdb/pull/866))

**Comment by hannesmuehleisen** [comment]
Any help is appreciated, happy to review PRs.
