### ISSUE TITLE
Range requests error using API

### ISSUE THREAD

**Issue by ju4e** [duckdb/duckdb#11221]
### What happens?

Hello,
I encountered an error when querying an API allowing to retrieve a csv.
When querying the API via duckdb I get the following error:
IO Error: HTTP GET error: Content-Length from server mismatches requested range, server may not support range requests.

The request used is : 
```sql
select * from read_csv_auto('http://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr.csv?code_entite=Y251002001&size=3&pretty&grandeur_hydro=H&fields=code_station,date_debut_serie,date_fin_serie,date_obs,resultat_obs,continuite_obs_hydro');
```

how can I resolve this error?

thank you!
regards, 
Julien

### To Reproduce

Run the request above.

### OS:

WINDOWS 10

### DuckDB Version:

10

### DuckDB Client:

CLI, dbeaver

### Full Name:

Julien

### Affiliation:

Postgres

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ju4e** [comment]
Hello, Do you have an idea to resolve the error encountered?

Thank you
Julien

**Comment by samansmink** [comment]
Hey sorry for letting this one hang for a while, did some investigation: the server seems to produce some weird responses here. It responds with a 206 to our HEAD request, but then when handling the actual GET request with the Range header, it will just send the full file. Even if I change DuckDB code to ignore the fact that it returns 206 on the HEAD request, the server will then also mark the Get request to the full file with 206, which will trip up DuckDB again.

My worry would be that allowing 206 http codes for full files downloads would potentially hide other errors in more confusing ways while this behaviour is at least sane: DuckDB throws an error about a server that send back confusing http requests. 

So unless there are some high profile servers that follow this  behaviour, my proposal would be to consider this an edge case that requires manually downloading the file.
