### ISSUE TITLE
Aggregating on a date range join using between and ifnull wrong result

### ISSUE THREAD

**Issue by Alaburda** [duckdb/duckdb#11234]
### What happens?

Our team frequently runs a query to count the number of rows in a SCD2-type table (i.e. a row has a start and an end date) for each month. When the SCD2 table has no end date, performing a range join and using ifnull produces wrong counts.

This seems to behave correctly at fewer rows but produces different counts when using larger tables.

### To Reproduce

```sql

--Create a range of dates
create table calendar as SELECT *
FROM range(DATE '2022-01-01', DATE '2024-02-01', INTERVAL '1' MONTH);

--Create an SCD2 dummy table with nullable end dates
create table scd2 as 
select 
  range as range_start,
  case when date_part('year', range) < 2023 then range + interval 4 month - interval 1 day end as range_end,
  n
from calendar
cross join generate_series(1, 40000) as n

--Create an SCD2 dummy table with non-nullable end dates
create table scd2_non_null as 
select 
  range as range_start,
  case when date_part('year', range) < 2023 then range + interval 4 month - interval 1 day else '2099-01-01' end as range_end,
  n
from calendar
cross join generate_series(1, 40000) as n

--Aggregate each table by using a range join
create table scd2_agg as 
select 
range, 
count(*) as n
from scd2 
inner join calendar 
on range between range_start and ifnull(range_end,'2099-01-01')
group by range
order by range
           
create table scd2_non_null_agg as 
select 
range, 
count(*) as n
from scd2_non_null 
inner join calendar 
on range between range_start and ifnull(range_end,'2099-01-01')
group by range
order by range

--The tables are different!
select * from scd2_non_null_agg a inner join scd2_agg b on a.range = b.range where a.n != b.n

```

### OS:

Windows 11

### DuckDB Version:

0.9.2-1

### DuckDB Client:

DBeaver

### Full Name:

Paulius Alaburda

### Affiliation:

Ignitis

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Thanks for the report - I'll have a look.

Incidentally, we support `±infinity` for dates and timestamps, which can simplify these kinds of range queries, and this might be a workaround for now?
