### ISSUE TITLE
DuckDB JDBC 0.10.1 Not Available in Maven Central

### ISSUE THREAD

**Issue by brianwyka** [duckdb/duckdb#11244]
### What happens?

The [0.10.1](https://github.com/duckdb/duckdb/releases/tag/v0.10.1) release was completed 17 hours ago, however the `duckdb_jdbc` Java library has not yet been made available in [Maven Central](https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/).

I would have expected this to have been available within a few hours.

### To Reproduce

N/A

### OS:

N/A

### DuckDB Version:

`0.10.1`

### DuckDB Client:

Java (JDBC)

### Full Name:

Brian Wyka

### Affiliation:

LogicMonitor

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @brianwyka, thanks for the report, we are working to resolve this problem.

**Comment by lukaseder** [comment]
For the record, this download is also not available right now:

https://artifacts.duckdb.org/latest/java-jars.zip

From here: https://duckdb.org/docs/installation/?version=main&environment=java&download_method=direct

**Comment by louisnow** [comment]
Can we please expedite the fix for this or if we have a workaround available?

**Comment by carlopi** [comment]
@lukaseder: also that will be fixed, you can get the binaries here: https://github.com/duckdb/duckdb/releases/tag/v0.10.1 (assets connected with the github release are a bit down)

@louisnow: would the assets from github release work as a temporary workaround?

**Comment by brianwyka** [comment]
@szarnyasg , @carlopi , anything I can do to help here?

**Comment by brianwyka** [comment]
@lnkuiper, @szarnyasg things look promising in some local tests I have done with the release download JAR, but I won't know for sure until I test out on a larger dataset.  Will try that sometime in near future.

**Comment by manticore-projects** [comment]
Greetings!

Accessing Snapshot builds also does not work:

```gradle
repositories {
    mavenLocal()
    mavenCentral()

    // Sonatype OSSRH
    maven {
        url = uri('https://oss.sonatype.org/content/repositories/snapshots/')
    }
}

dependencies {
    testImplementation 'org.duckdb:duckdb_jdbc:+'
}
```

--> results in:
Execution failed for task ':JSQLTranspiler:compileTestJava'.
> Could not resolve all files for configuration ':JSQLTranspiler:testCompileClasspath'.
   > Could not find duckdb_jdbc-0.11.0-SNAPSHOT.jar (org.duckdb:duckdb_jdbc:0.11.0-SNAPSHOT:20240331.014453-96).
     Searched in the following locations:
         https://oss.sonatype.org/content/repositories/snapshots/org/duckdb/duckdb_jdbc/0.11.0-SNAPSHOT/duckdb_jdbc-0.11.0-20240331.014453-96.jar


```gradle
dependencies {
    testImplementation 'org.duckdb:duckdb_jdbc:0.10.+'
}
```
Pulls version 0.10.0 only.


```gradle
dependencies {
    testImplementation 'org.duckdb:duckdb_jdbc:0.10.2-SNAPHOT'
}
```

--> fails with too

**Comment by brianwyka** [comment]
@manticore-projects , this is due to #8240

**Comment by manticore-projects** [comment]
Would this problem not be solve more reliable with a `Gradle` or `Maven` build on the Java part (instead of those hand written methods). I deploy Snapshot builds on all of my projects and usually this stuff "just works", without even thinking about it.

**Comment by wdroste** [comment]
@szarnyasg just checking if that next week target is holding.

**Comment by brianwyka** [comment]
Looks like the `0.10.1` artifact is now in central:
https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/0.10.1/

**Comment by szarnyasg** [comment]
@brianwyka, indeed. I merged https://github.com/duckdb/duckdb-web/pull/2539, which will update the website to 0.10.1.
