### ISSUE TITLE
Using parquet extension from C++

### ISSUE THREAD

**Issue by rprovodenko** [duckdb/duckdb#1124]
Good day!

I'm not a C++ developer, so maybe what I'm asking is naive. The parquet extension can be used like so: https://github.com/cwida/duckdb/pull/653#issue-427144670, but since these headers are not included in the C++ binary distribution does that mean I have to compile the whole duckdb in order for me to use the extension?

**Comment by hannesmuehleisen** [comment]
We should start shipping those extensions with the binary builds.

**Comment by chilarai** [comment]
@hannesmuehleisen, I get the following error when using a SQL query using Parquet
`Catalog: Table Function with name parquet_scan does not exist!`

Here is my query `"CREATE TABLE table1 AS SELECT * FROM PARQUET_SCAN('/path/to/parquet/file')";`
What could be the issue?

**Comment by hannes** [comment]
We now have installable extensions
