### ISSUE TITLE
Python sdist missing from PyPI for 0.10.1

### ISSUE THREAD

**Issue by edgarrmondragon** [duckdb/duckdb#11253]
### What happens?

The latest (0.10.1) release of the Python duckdb library is missing the source distribution:

<img width="1123" alt="Screenshot 2024-03-19 at 9 37 05 a m" src="https://github.com/duckdb/duckdb/assets/16805946/955883bd-0f01-4871-9ead-921739e5de3a">

https://pypi.org/project/duckdb/0.10.1/#files

### To Reproduce

If there are no wheels for the user's platform or the user has requested an sdist with `pip install 'duckdb==0.10.1' --no-binary 'duckdb'`, they're going to encounter an error like:

```
ERROR: Could not find a version that satisfies the requirement duckdb==0.10.1 (from versions: 0.0.0, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1.dev1005, 0.10.1.dev1037, 0.10.1.dev1151, 0.10.1.dev1244)
ERROR: No matching distribution found for duckdb==0.10.1
```

### OS:

NA

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Edga Ramírez

### Affiliation:

Arch.dev

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Thanks for raising this.
I will be back with an update in a bit.

**Comment by carlopi** [comment]
Update: source distribution is now available (see https://pypi.org/project/duckdb/0.10.1/#files) BUT it will not actually work for building from sources given the setup.py will look up some environment variable that will not be present.

Mistake is on me, both the original one and failing to detect that this would have caused problems.

I will fix up the CI job so that nightly version will have all artifacts uploaded. This will likely happen tomorrow. Also process will be improved with more automatic checks in place to avoid this.

I am not sure if using duckdb v0.10.1 without a properly working source distribution is viable for your use case, or if using a nightly version can be viable.

**Comment by edgarrmondragon** [comment]
> BUT it will not actually work for building from sources given the setup.py will look up some environment variable that will not be present.

Gotcha, thanks for the heads up. Makes me more concerned about wheels being available then 😅

**Comment by carlopi** [comment]
Can you possibly clarify what sort of concern?

DuckDB source code is in the repository, GitHub CI that is building the package is available here, happy to walk you through it.

To rebuild the wheels yourself (I am double checking the actual process, might have to amend the script), but something along the like of:

```
# go to https://pypi.org/project/duckdb/0.10.1/#files, get the link for the source tar.gz
$ wget https://files.pythonhosted.org/packages/47/15/f78b67a07f53f4072c3ab81ab7942850968614098ef577cea8e44a8729fc/duckdb-0.10.1.tar.gz
$ sha512sum duckdb-0.10.1.tar.gz 
a70125658ca68a2cbc27402a3d3fd81a734c3adc240e307201265523db3d1c122d51c6dc3c27bfd49c4990f98f8518569daacd7a325a2276867fe843531c537c  duckdb-0.10.1.tar.gz
$ GIT_OVERRIDE_DESCRIBE=v0.10.1-0-g4a89d97db8 pip install duckdb-0.10.1.tar.gz 
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/duckdb-0.0.0-py3.11-macosx-10.9-universal2.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Processing ./duckdb-0.10.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: duckdb
  Building wheel for duckdb (pyproject.toml) ... done
  Created wheel for duckdb: filename=duckdb-0.0.0-cp311-cp311-macosx_10_9_universal2.whl size=29252410 sha256=c7834eec8ce96c19ca10f55a6831c948b1d1656c8278af935df653a582141f15
  Stored in directory: /Users/carlo/Library/Caches/pip/wheels/eb/0e/8e/38b313e9e9362c0d16f5ecde48b8542e60e24ce21d15472216
Successfully built duckdb
Installing collected packages: duckdb
  Attempting uninstall: duckdb
    Found existing installation: duckdb 0.0.0
    Uninstalling duckdb-0.0.0:
      Successfully uninstalled duckdb-0.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
duckdb-engine 0.9.2 requires duckdb>=0.4.0, but you have duckdb 0.0.0 which is incompatible.
Successfully installed duckdb-0.0.0
$ python3                                                                     
Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
^[[A
>>> duckdb.__version__
'0.10.1'
>>> duckdb.sql("PRAGMA version");
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.10.1         │ 4a89d97db8 │
└─────────────────┴────────────┘
```
This will succeed, produce wheels that are functionally equivalent to the one that are distributed, BUT the metadata version for the package will be wrong. I think that CI does the same but after having cloned duckdb at the right hash and it gets metadata from the git environment. This is a mistake that will be fixed.

**Comment by carlopi** [comment]
This has been fixed for development versions, see https://pypi.org/project/duckdb/0.10.2.dev189/#files, and has been fixed in the CI that will build for the upcoming tag 0.10.2 (see https://duckdb.org/dev/release-calendar#planned-releases).

Version v0.10.1 can't be re-uploaded to pypi due to policy on file versioning, but looking forward I consider this to be addressed.

Thanks again for raising this
