### ISSUE TITLE
DISTINCT not compatible with ORDER BY in aggregate functions 

### ISSUE THREAD

**Issue by aryeht** [duckdb/duckdb#11269]
### What happens?

When using `DISTINCT` **together with** `ORDER BY` in an aggregate function, the DISTINCT clause is ignored

output:
```
┌─────────┬────────────────────────────────────────────────┐
│ user_id │                     causes                     │
│  int32  │                   varchar[]                    │
├─────────┼────────────────────────────────────────────────┤
│       1 │ [Environmental, Environmental, Health, Social] │
└─────────┴────────────────────────────────────────────────┘

```

Expected output for causes: `[Environmental, Health, Social]`

### To Reproduce

```
import duckdb

SQL = '''
-- Create table
CREATE TABLE user_causes (
    user_id INT,
    cause VARCHAR,
    "date" DATE
);

-- Insert sample values
INSERT INTO user_causes (user_id, cause, "date") VALUES
(1, 'Environmental', '2024-03-18'),
(1, 'Environmental', '2024-02-18'),
(1, 'Health', '2024-01-18'),
(1, 'Social', '2023-12-18'),
(1, NULL, '2023-11-19');

SELECT 
    user_id, 
    list(DISTINCT cause ORDER BY "date" DESC) FILTER(cause IS NOT NULL) AS causes
FROM user_causes 
GROUP BY user_id;

'''

duckdb.sql(SQL).show()

```

### OS:

Ubuntu 22.04 LTS x64

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Arye Halioua

### Affiliation:

Tikal

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
The problem is that we are grouping on both cause and date (otherwise the result is ambiguous). Postgres does not allow this (or it requires that the `ORDER BY` expressions be regular arguments).

**Comment by aryeht** [comment]
With the `0.10.2` release, I get the error below with the exact same code as above.

Exception:
```
Traceback (most recent call last):
  File "/home/.../agg_distinct.py", line 27, in <module>
    duckdb.sql(SQL).show()
    ^^^^^^^^^^^^^^^
duckdb.duckdb.BinderException: Binder Error: In a DISTINCT aggregate, ORDER BY expressions must appear in the argument list
```

**Comment by hawkfish** [comment]
Yes, because the query was not valid. We added a check with this error message.

**Comment by hawkfish** [comment]
Consider a slightly different example:

| cause | date |
| :--- |  :--- |
| Environmental | 2023-12-18 |
| Health | 2024-01-18 |
| Environmental | 2024-02-18 |

The ordering here is ambiguous because depending on which row the aggregate sees first, `Environmental` could sort before or after `Health` (remember, SQL data is unordered)

**Comment by hieunm89** [comment]
Is there any way to use string_agg with distinct and a specific order of values after this? Before, this works
`string_agg(distinct field1,'&' ORDER BY list_position(['Value1','Value2','Value3'], field1))` 
I haven't found a solution to replace it.

**Comment by hawkfish** [comment]
This is an interesting use case (ordering by a functional dependency). For now I think you need to do what Teggy suggested in the chat, but I'll think about relaxing the requirements.

**Comment by hawkfish** [comment]
@hieunm89 I improved the constraints and I think your query should work now (it's in the test suite!)
