### ISSUE TITLE
Performance issue with DuckDBPyRelation::FetchOne() and FetchMany() due to stream_result being true

### ISSUE THREAD

**Issue by josler** [duckdb/duckdb#11278]
### What happens?

I've noticed that `fetchone()` (or `fetchmany()`) on a relation is way slower (5x for me on 50M row dataset) than `fetchall()[0]` - this was pretty surprising to me.

I _think_ the difference comes down to stream_result being set as true.

### To Reproduce

```py
import duckdb

conn = duckdb.connect(database=':memory:')
conn.execute(f"CREATE TABLE my_table AS SELECT * FROM read_parquet('my_file')") # data provenance doesn't matter, nor does the actual data being loaded. In this case it's 50M rows.

conn.sql("SELECT * FROM my_table WHERE Company = 'Ochoa PLC';").fetchone() # pretty slow, ~1s ish
conn.sql("SELECT * FROM my_table WHERE Company = 'Ochoa PLC';").fetchmany(1) # pretty slow, ~1s ish
conn.sql("SELECT * FROM my_table WHERE Company = 'Ochoa PLC';").fetchall()[0] # ~5x faster than first run
conn.sql("SELECT * FROM my_table WHERE Company = 'Ochoa PLC';").execute().fetchone() # ~5x faster than first run
```

note that the order doesn't matter here; these are independent.

Now, I think calling `.execute()` first before `.fetchone()` makes it faster because:

https://github.com/duckdb/duckdb/blob/ac97a91d7045bf0535bb2a0745840b2d30e96ee0/tools/pythonpkg/src/pyrelation.cpp#L756

Here, stream_result is false:

```cpp
auto query_result = ExecuteInternal(stream_result);
```

For FetchOne and FetchMany stream_result is true, for FetchAll stream_result is false (the calls to `ExecuteOrThrow`):

https://github.com/duckdb/duckdb/blob/ac97a91d7045bf0535bb2a0745840b2d30e96ee0/tools/pythonpkg/src/pyrelation.cpp#L781-L821

I would guess this is because whatever executor is being used for when stream_result is true isn't as fast here. Nevertheless it's pretty surprising that identical queries accessed in different ways end up being quite meaningfully different in performance, with no obvious way to control it - perhaps converging into one way of doing things would be better, or exposing whether we want the streaming or not. FWIW other client libraries for duckdb don't have the issue.

### OS:

macOS

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Jamie Osler

### Affiliation:

equals.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for the report, I believe we're aware of this issue already.

This limitation is mentioned under the "Future work" section of the PR:
<https://github.com/duckdb/duckdb/pull/10245>

To really confirm that that is the culprit though it would be great if you could provide the parquet file, or give information about the size and schema of the file

**Comment by Tishj** [comment]
Also, you can help confirm/deny this claim by turning off `preserve_insertion_order`.
By default this is on, when scanning from a table of sufficient size we resort to batched execution in that case.

Since the StreamQueryResult does not support batched collection yet, we fall back to running the non-batched version in single threaded mode - causing the slow down you're experiencing

**Comment by josler** [comment]
I turned off `preserve_insertion_order` to no effect.

https://github.com/datablist/sample-csv-files has same CSV files that exhibit this behaviour - it's easier to see on larger ones of course. I was using these converted to parquet, but confirm same behaviour with CSV as well.

**Comment by Tishj** [comment]
This should be fixed by https://github.com/duckdb/duckdb/pull/11494
