### ISSUE TITLE
DuckDB CLI can't find views in attached databases.

### ISSUE THREAD

**Issue by derekmahar** [duckdb/duckdb#11277]
### What happens?

DuckDB CLI can't find views in attached DuckDB or SQLite databases.

```
$ duckdb cryptocurrency.duckdb
v0.10.2-dev39 e245e2927f
Enter ".help" for usage hints.
D .tables
transactions
D ATTACH 'currency.duckdb';
D SHOW DATABASES;
┌────────────────┐
│ database_name  │
│    varchar     │
├────────────────┤
│ cryptocurrency │
│ currency       │
└────────────────┘
D .tables
currency_exchange_rate_intervals  currency_exchange_rates_pacific
currency_exchange_rates           transactions
D SELECT * FROM currency.currency_exchange_rates_pacific LIMIT 5;
┌─────────────────────┬──────────────────────┬──────────────────────┬───────────────┐
│        date         │ source_currency_code │ target_currency_code │ exchange_rate │
│      timestamp      │       varchar        │       varchar        │ decimal(12,6) │
├─────────────────────┼──────────────────────┼──────────────────────┼───────────────┤
│ 1999-12-31 20:00:00 │ PHP                  │ CAD                  │      0.035790 │
│ 1999-12-31 20:00:00 │ USD                  │ CAD                  │      1.443300 │
│ 2000-01-04 20:00:00 │ PHP                  │ CAD                  │      0.036430 │
│ 2000-01-04 20:00:00 │ USD                  │ CAD                  │      1.452000 │
│ 2000-01-05 20:00:00 │ PHP                  │ CAD                  │      0.037250 │
└─────────────────────┴──────────────────────┴──────────────────────┴───────────────┘
D SELECT * FROM currency.currency_exchange_rates LIMIT 5;
Catalog Error: Table with name currency_exchange_rates_pacific does not exist!
Did you mean "currency.currency_exchange_rates_pacific"?
LINE 1: ...currency.currency_exchange_rates LIMIT 5;
                                                  ^
D SELECT * FROM currency.currency_exchange_rate_intervals LIMIT 5;
Catalog Error: Table with name currency_exchange_rates does not exist!
Did you mean "currency.currency_exchange_rates"?
D .schema
CREATE VIEW currency_exchange_rate_intervals AS SELECT date AS start_date, lead(date) OVER (PARTITION BY source_currency_code, target_currency_code ORDER BY date) AS end_date, source_currency_code, target_currency_code, exchange_rate FROM currency_exchange_rates ORDER BY start_date, source_currency_code, target_currency_code;

CREATE VIEW currency_exchange_rates AS (SELECT * FROM currency_exchange_rates_pacific) UNION ALL (SELECT * FROM (VALUES (CAST('1999-12-31T15:00:00-05:00' AS TIMESTAMP), 'CAD', 'CAD', 1), (main.timezone('UTC', now()), 'CAD', 'CAD', 1)) AS valueslist);

CREATE TABLE currency_exchange_rates_pacific(date TIMESTAMP, source_currency_code VARCHAR, target_currency_code VARCHAR, exchange_rate DECIMAL(12,6));
CREATE TABLE transactions(Date TIMESTAMP, "Type" VARCHAR, "Received Currency" VARCHAR, "Received Amount" DECIMAL(25,8), "Received Net Worth" DECIMAL(25,8), "Sent Currency" VARCHAR, "Sent Amount" DECIMAL(25,8), "Sent Net Worth" DECIMAL(25,8), "Fee Currency" VARCHAR, "Fee Amount" DECIMAL(25,8), "Fee Net Worth" VARCHAR);
```

Note that DuckDB CLI can query table `currency.currency_exchange_rates_pacific`, but it can't find views `currency.currency_exchange_rates` or `currency.currency_exchange_rate_intervals`.  Furthermore, when it cannot find these views, DuckDB reports inaccurate error messages.

DuckDB encounters the same problem when querying views in attached SQLite databases.

### To Reproduce

Attach a DuckDB or SQLite database that contains views to another DuckDB database and execute a query on a view in the attached database.

### OS:

Ubuntu 22.04.4 LTS

### DuckDB Version:

v0.10.2-dev39 e245e2927f

### DuckDB Client:

CLI

### Full Name:

Derek Mahar

### Affiliation:

Self-employed

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @derekmahar – thanks for raising this issue. I tried to reproduce it following your description but couldn't trigger the error. Could you please share a script that reproduces it?

**Comment by derekmahar** [comment]
After thinking more about the error messages that DuckDB CLI reported, I realised that the issue is not that a DuckDB database can't find views in an attached database, but that views in an attached database can no longer find other tables or views in the attached database.  In effect, when a database is attached, its tables and views are no longer within the local scope of that database.

```
$ bash test_share_views
┌───────────────┐
│ database_name │
│    varchar    │
├───────────────┤
│ memory        │
│ share         │
└───────────────┘
share_table   share_view_1  share_view_2  share_view_3
┌───────┐
│  c1   │
│ int32 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
Catalog Error: Table with name share_table does not exist!
Did you mean "share.share_table"?
Catalog Error: Table with name share_view_1 does not exist!
Did you mean "share.share_view_1"?
┌───────┐
│  c1   │
│ int32 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
```
(See scripts in [duckdb-test-share-views.tar.gz](https://github.com/duckdb/duckdb/files/14692681/duckdb-test-share-views.tar.gz).)

**Comment by szarnyasg** [comment]
Hi @derekmahar, we discussed this internally and this is currently an expected limitation. We plan to fix this in the future.

**Comment by alexisdeh** [comment]
Hi @szarnyasg, I just faced this issue (attaching to a db with views in it, and I cannot use the views).
Tested with version 1.1.1
Do you know if this is planned to be solved ?

**Comment by szarnyasg** [comment]
Hi, this features is not on our immediate roadmap.
