### ISSUE TITLE
`TIMESTAMP` is not consistently detected as `TIMESTAMPTZ`, when Zone information is provided.

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11279]
### What happens?

`TIMESTAMP` is not consistently detected as `TIMESTAMPTZ`, when Zone information is provided.

### To Reproduce

```sql
-- surprisimgly works and returns correct result `7`
SELECT
  DATE_DIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00+07', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;

-- fails: Binder Error: No function matches the given name and argument types 'date_diff(STRING_LITERAL, TIMESTAMP WITH TIME ZONE, TIMESTAMP)'
SELECT
  DATE_DIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;

-- works  and returns correct result `7`
SELECT
  DATE_DIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMPTZ '2010-07-07 10:20:00+00') AS hours;

-- technically works, but returns wrong result `0`
SELECT
  DATE_DIFF('HOUR',  TIMESTAMPTZ '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;
```

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by manticore-projects** [comment]
For reference, `H2` returns correct results for all 4 statements:
```sql
-- H2 returns correct result `7`
SELECT
  DATEDIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00+07', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;

-- H2 returns correct result `7`
SELECT
  DATEDIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;

-- H2 returns correct result `7`
SELECT
  DATEDIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;

-- H2 returns correct result `7`
SELECT
  DATEDIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;
```

**Comment by hawkfish** [comment]
What is your time zone setting for the two tests?

Also the bottom two tests in your H2 suite are not the same as the DuckDB tests (`TIMESTAMP` vs `TIMESTAMPTZ`)?

**Comment by hawkfish** [comment]
The second query works in Postgres, but the result depends on the time zone:

```sql
hawkfish=# select TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00';
        timezone        |      timestamp      
------------------------+---------------------
 2010-07-06 20:20:00-07 | 2010-07-07 10:20:00
(1 row)

hawkfish=# select TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok' - TIMESTAMP '2010-07-07 10:20:00+00';
 ?column?  
-----------
 -14:00:00
(1 row)

hawkfish=# set timezone='UTC';
SET
hawkfish=# select TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok' - TIMESTAMP '2010-07-07 10:20:00+00';
 ?column?  
-----------
 -07:00:00
(1 row)
```

(I am in `US/Pacific`).

**Comment by hawkfish** [comment]
The issue title suggests that you are expecting that adding an offset will result in the string being cast to TSTZ even though you specified TS? Both DuckDB and Postgres interpret the expression `TIMESTAMP '2010-07-07 10:20:00+00'` as TS, not TSTZ. If H2 does this, then it is a behavior difference.

**Comment by manticore-projects** [comment]
Good Morning and greetings to the US.

I see two issues:

1) this should work and it should return '7' (or at least the same result as the first test)

```
sql
-- fails: Binder Error: No function matches the given name and argument types 'date_diff(STRING_LITERAL, TIMESTAMP WITH TIME ZONE, TIMESTAMP)'
SELECT
  DATE_DIFF('HOUR',  TIMESTAMP '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;
```

2) I am lost about what  `TIMESTAMP '2010-07-07 10:20:00+00'` really does and I did not find any good documentation

a) does it ignore the provided TZ `+00` and always returns the civil timestamp according to Locale? If so the first example should return Zero?

b) does it interpret the provided TZ `+00` and returns the civil timestamp accordingly (UTC in this case)? Only then the first example can return `7` but then the last example should return `7` also (and not `0`)?

**Comment by manticore-projects** [comment]
Last but not least two more related. DuckDB function specific questions:

a) when I have a TIMESTAMP (without a TZ) how can I enforce/set a certain timezone. `CAST ... AS TIMESTAMPTZ AT TIME ZONE ...` does not work

b) when I have a TIMESTAMPTZ (with a TZ) how can translate/move it into a certain timezone? (without format printing the, building the hour difference and then to DATE_ADD it to the TIMESTAMP please).

**Comment by hawkfish** [comment]
Thanks for the report. I have found that Postgres does promote TS => TSTZ so I am looking into that.

WRT #2 above, all the offset is parsed and applied, but the type is still `TIMESTAMP` (which is consistent with Postgres).

WRT a) above, I'm not sure what you mean by "enforce a certain timezone". SQL does not model row-level TZ values. What the `timezone(TIMESTAMP, ...)` function does (and `AT TIME ZONE`  is just syntactic sugar that gets translated into that function) is pull out the UTC date parts from the instant and use them to construct a new TSTZ. This is what the standard requires.

WRT b) above, be aware that a TSTZ does not "have" a TZ - it uses the current setting of the `TImeZone` (and `Calendar`) settings to generate time bin values when requested. Casting to`VARCHAR` is such an operation.

Incidentally, I strongly recommend reading my [blog post](https://duckdb.org/2022/01/06/time-zones.html) on this to help understand the SQL TZ model. From your questions I think you are expecting it to work differently than it does.

**Comment by manticore-projects** [comment]
> https://duckdb.org/2022/01/06/time-zones.html

Thank you so much, this is what I have been look for desperately!
Maybe this would better be shown in the documentation, but not just as a blog entry?

**Comment by manticore-projects** [comment]
Sorry for being a pain:

```sql
-- technically works, but returns wrong result `0`
SELECT
  DATE_DIFF('HOUR',  TIMESTAMPTZ '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;
```

This is still wrong in my opinion and I would like to expect `7` since it contradicts example 1.
Why exactly would example 1 and 3 return different results?

**Comment by hawkfish** [comment]
> Why exactly would example 1 and 4 return different results?

Because the result depends on your time zone setting. In #1 you are using plain TZ values, so it always differs by 7 hours. In #2 the `TIMESTAMPTZ '2010-07-07 10:20:00' expression produces an instant that depends on your TZ setting.

```sql
D set TimeZone='America/Los_Angeles';
D SELECT
    DATEDIFF('HOUR',  TIMESTAMP WITH TIME ZONE '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;
```

| hours |
|------:|
| -14   |

```sql
D set TimeZone='UTC';
D SELECT
    DATEDIFF('HOUR',  TIMESTAMP WITH TIME ZONE '2010-07-07 10:20:00' AT TIME ZONE 'Asia/Bangkok', TIMESTAMP '2010-07-07 10:20:00+00') AS hours;
```

| hours |
|------:|
| -7    |

If you want to nail down the offset when casting strings to TSTZ you need to specify an offset explicitly. I suspect you (or maybe H2?) assumed the `+00` to be implicit but that is not what Postgres does.

Incidentally, we model Postgres' behaviour, not H2's, so there may be differences. If we differ from PG (which we seem to on automatic promotion) then there is an issue, but H2 might be different.

I hear you about the documentation (and there are a few small things in that post that are incorrect) but I'm not clear where to put it. A a lot of it is general temporal modelling background, but I do end up linking that post a lot so I'll think about it.

**Comment by hawkfish** [comment]
The bug here is the binder error in #2 and I will take a look at that.

**Comment by manticore-projects** [comment]
> If you want to nail down the offset when casting strings to TSTZ you need to specify an offset explicitly. I suspect you (or maybe H2?) assumed the `+00` to be implicit but that is not what Postgres does.

@hawkfish : I would like to thank you so much, this nailed it and I understand now that:

1) TIMESTAMP with given timezone is set at this given timezone
2) TIMESTAMP without given timezone is set at UTC
3) TIMESTAMPTZ with given timezone is set at this given timezone
4) but TIMESTAMPTZ without given timezone is set at the Locale/System Time Zone

Indeed this was not clear to me.

**Comment by manticore-projects** [comment]
Last thing: `DATE_DIFF`  does not work for `TIMEZONE`, `TIMEZONE_HOUR` and `TIMEZONE_MINUTE ` -- bug or feature?

**Comment by hawkfish** [comment]
> Last thing: `DATE_DIFF` does not work for `TIMEZONE`, `TIMEZONE_HOUR` and `TIMEZONE_MINUTE ` -- bug or feature?

Implementing it would be a feature I suppose. Not sure what you would use it for though.
