### ISSUE TITLE
Duplicate key error when updating LIST typed columns in a table with a primary key

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#11288]
### What happens?

I cannot update array columns in a table with a primary key.

### To Reproduce

```sql
create table t (i int primary key, j int[]);
insert into t values (1, array[1]);

update t 
set 
  j = array[2]
where i = 1;
```

This produces an error:

```
SQL Error: Constraint Error: Duplicate key "i: 1" violates primary key constraint. If this is an unexpected constraint violation please double check with the known index limitations section in our documentation (https://duckdb.org/docs/sql/indexes).
```

The page at https://duckdb.org/docs/sql/indexes documents a case where the primary key column is updated as well (or any indexed column), but I'm not doing that so I feel this case is different. At least, I don't see any explicit or implicit (via `duckdb_indexes()`) indexes here.

The problem also happens with `MAP` types:

```sql
create table t (i int primary key, j map(varchar, varchar));
insert into t values (1, map(['a'], ['b']));

update t 
set 
  j = map(['c'], ['d'])
where i = 1;
```

No such problem appears with `STRUCT` types, though. This works:

```sql
create table t (i int primary key, j struct(a varchar, b varchar));
insert into t values (1, ('a', 'b'));
update t 
set 
  j = ('c', 'd')
where i = 1;
```

I think this should either be:

- Fixed
- Documented on https://duckdb.org/docs/sql/indexes

Note, I couldn't test the latest snapshots because of:

- https://github.com/duckdb/duckdb/issues/11244

### OS:

Microsoft Windows [Version 10.0.22631.3296]

### DuckDB Version:

0.10.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for the very thorough issue reports, @lukaseder! We'll look into them.

**Comment by Mytherin** [comment]
Thanks for the report! This is an expected restriction, and similar to the one documented in the page you mention - https://duckdb.org/docs/sql/indexes#updates-become-deletes-and-inserts. Updates on `LIST` and `MAP` are also converted into deletes and inserts which causes the problem to happen. @szarnyasg could we perhaps address this current limitation in the documentation as well?
