### ISSUE TITLE
"postgres_scanner.duckdb_extension" version (v0.10.1) does not match DuckDB version (v0.10.1-dev1494)

### ISSUE THREAD

**Issue by tts-sdrissen** [duckdb/duckdb#11287]
### What happens?

Hey guys,
I think you messed up either the metadata of the postgres extension, or the algorythm which determine the compatibility for extensions.

After I pulled the new version of duckdb, I get this error:
```
DuckDB.NET.Data.DuckDBException (0x00000001): Invalid Input Error: Extension "C:\Users\tts-sdrissen\.duckdb\extensions\4a89d97db8\windows_amd64\postgres_scanner.duckdb_extension" version (v0.10.1) does not match DuckDB version (v0.10.1-dev1494)
```

### To Reproduce

I updated the C# nuget package DuckDB.NET.Data.Full to version 0.10.1
After that I could not connect to postgres anymore.
This is the query:
```
INSTALL postgres; 
LOAD postgres;
ATTACH 'dbname=some_db user=me host=127.0.0.1 password=secret1234' AS some_db (TYPE postgres);
```

### OS:

Windows

### DuckDB Version:

0.10.1

### DuckDB Client:

0.10.1

### Full Name:

Simon Drissen

### Affiliation:

TeleTrain Software GmbH

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Giorgi** [comment]
@tts-sdrissen I just uploaded a new version on NuGet that includes the fixed version of the DuckDB library.
