### ISSUE TITLE
UNION [ DISTINCT ] and EXCEPT [ DISTINCT ] is ignored when subquery returns no rows

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#11294]
### What happens?

`UNION [ DISTINCT ]` and `EXCEPT [ DISTINCT ]` should remove duplicate rows irrespective of whether both of its subqueries produce any rows. But it doesn't in some cases.

### To Reproduce

```sql
create table t (i int);
insert into t values (1),(2),(3),(4),(4);
select i from t union select 1 where false order by 1;
```

This produces:

```
|i  |
|---|
|1  |
|2  |
|3  |
|4  |
|4  |
```

It should produce:

```
|i  |
|---|
|1  |
|2  |
|3  |
|4  |
```

This seems to be due to an optimisation done for "obviously false" predicates, e.g. `WHERE FALSE`. It doesn't happen here, for example:

```sql
select i from t union select 1 from t where i = -1 order by 1;
```

`EXCEPT` is also affected:

```sql
-- Incorrect result:
select i from t except select 1 where false order by 1;

-- Correct result:
select i from t except select 1 from t where i = -1 order by 1;
```

Note, I couldn't test the latest snapshots because of:

- https://github.com/duckdb/duckdb/issues/11244

### OS:

Microsoft Windows [Version 10.0.22631.3296]

### DuckDB Version:

0.10.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Previously reported at https://github.com/duckdb/duckdb/issues/11163
