### ISSUE TITLE
OVERWRITE_OR_IGNORE doesn't delete directory, only overwrites files, for S3 file systems

### ISSUE THREAD

**Issue by zsoltc** [duckdb/duckdb#11307]
### What happens?

Adding `OVERWRITE_OR_IGNORE` to `COPY` statements doesn't delete the output directory, only overwrites files, leaving previous files.

### To Reproduce

Executing the following statements:
```python
import duckdb

duckdb.sql(
    f"""
drop table if exists tbl;
create table tbl (x int);
insert into tbl values {('(1),' * 100_000)[:-1]};
copy (
    select * from tbl
) to 'test_partitioned.csv' (
    file_size_bytes '20k',
    overwrite_or_ignore true
);
"""
)
```
This will create `data_0.csv` - `data_5.csv` in the `test_partitioned.csv` directory.

Executing the above statements again, but with a smaller amount of dummy data (which will fit in one file):
```python
import duckdb

duckdb.sql(
    f"""
drop table if exists tbl;
create table tbl (x int);
insert into tbl values {('(1),' * 100)[:-1]};
copy (
    select * from tbl
) to 'test_partitioned.csv' (
    file_size_bytes '20k',
    overwrite_or_ignore true
);
"""
)
```
This will overwrite `data_0.csv` but will leave the old `data_1.csv` - `data_5.csv` files.

Is this expected behaviour?
Thank you!

Tagging @NielsKorschinsky

### OS:

MacOS

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Zsolt Czinege

### Affiliation:

IBM

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by NielsKorschinsky** [comment]
Related to #10282 .
This might also affect hive partitioning (UNTESTED):

* data.csv
* data.csv/x=1/data_0.csv
* data.csv/x=2/data_0.csv

if we now remove the value x=2 and re-write the data, it seems like the file will still exist.
Everything below the path `data.csv` top level, must be purged to fix such an issue.

**Comment by NielsKorschinsky** [comment]
Hi @Mytherin 
thanks for proving a fix quickly for a local system!

However, I'd like to re-open this issue as it was explicitly pointed at S3 which is excluded in your PR.
S3 does also support the option to list the contents and to delete them.

With this issue closed, it might get confusing to have different behavior between S3 and local file system undocumented.

**Comment by Mytherin** [comment]
I agree that it should get documented, and ideally we would like to support this for S3 in the future, but as we don't support these APIs yet internally that is not easily possible currently.

**Comment by sergun** [comment]
Hi @Mytherin 

Are there any plans to support (at least partially) for s3 `OVERWRITE_OR_IGNORE` for entire directory as @zsoltc mentioned and `OVERWRITE`?
