### ISSUE TITLE
S3 special characters like "?" in folder path trigger Legacy Authentication Scheme

### ISSUE THREAD

**Issue by johannesboyne** [duckdb/duckdb#11311]
### What happens?

Loading a data (e.g., CSV, Parquet, ...) file from S3 
```SQL
SELECT * FROM 's3://dqc-testing-bucket/host_name=a.new.host-with-more-dots.than.i.would.expect.com?a=test/inventory_50k_rows.csv';
```
Leads to an IO Error:
```
IO Error: Invalid query parameters found. Supported parameters are:
's3_region', 's3_access_key_id', 's3_secret_access_key', 's3_session_token',
's3_endpoint', 's3_url_style', 's3_use_ssl'
```

### To Reproduce

- Create an S3 folder for example named `host_name=a.new.host-with-more-dots.than.i.would.expect.com?a=test` 
- Place a data file
- Try to load the file via DuckDB

### OS:

macOS

### DuckDB Version:

v0.10.1

### DuckDB Client:

Shell

### Full Name:

Johannes Boyne

### Affiliation:

Data Q Company GmbH

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
Hey @johannesboyne we will deprecated/remove the fully qualified urls solving this issue, in the meantime you can consider using the `URL_COMPATIBILITY_MODE` option (https://duckdb.org/docs/extensions/httpfs/s3api#overview-of-s3-secret-parameters) as a workaround

**Comment by johannesboyne** [comment]
Hi @samansmink thanks a lot for the info! It works very well for us!
