### ISSUE TITLE
Excel Extension format for 'dddd' (day of week name) maps sundays to the empty string

### ISSUE THREAD

**Issue by jonathanswenson** [duckdb/duckdb#11319]
### What happens?

When the excel format functions are used (as part of the excel extension) the day of week name formatter `dddd` seems to not map Sundays properly, instead mapping them to the empty String. 

### To Reproduce

```
> SELECT excel_text(i.generate_series, 'dddd') FROM generate_series(0, 14) as i;
┌───────────────────────────────────────┐
│ excel_text(i.generate_series, 'dddd') │
│                varchar                │
├───────────────────────────────────────┤
│ Saturday                              │
│                                       │
│ Monday                                │
│ Tuesday                               │
│ Wednesday                             │
│ Thursday                              │
│ Friday                                │
│ Saturday                              │
│                                       │
│ Monday                                │
│ Tuesday                               │
│ Wednesday                             │
│ Thursday                              │
│ Friday                                │
│ Saturday                              │
├───────────────────────────────────────┤
│                15 rows                │
└───────────────────────────────────────┘
```

### OS:

mac

### DuckDB Version:

0.10.1, 0.9.2

### DuckDB Client:

shell, cli, wasm

### Full Name:

Jonathan Swenson

### Affiliation:

Omni

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! Fix is up here - https://github.com/duckdb/duckdb/pull/11328
