### ISSUE TITLE
`REGEX_EXTRACT` fails with variable `IDX`

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11338]
### What happens?

`REGEX_EXTRACT` fails with variable `IDX` (like a column reference).
This is at least unexpected and undocumented.

### To Reproduce

```sql

-- fails: Invalid Input Error: Group specification field must be a constant!
WITH example AS (
    SELECT 'Hello Helloo and Hellooo' AS value, 'H?ello+' AS regex, 1 as pos
    UNION ALL
    SELECT 'Hello Helloo and Hellooo', 'H?ello+', 1
) SELECT  value
        , regex
        , pos
        , Regexp_Extract( value, regex, pos ) AS regexp_value
FROM example
;

-- works
WITH example AS (
    SELECT 'Hello Helloo and Hellooo' AS value, 'H?ello+' AS regex, 1 as pos
    UNION ALL
    SELECT 'Hello Helloo and Hellooo', 'H?ello+', 1
) SELECT  value
        , regex
        , pos
        , Regexp_Extract( value, regex, 1 ) AS regexp_value
FROM example
;
```

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @manticore-projects, this restriction is currently expected but it is indeed undocumented. We'll clarify it in the documentation.

**Comment by szarnyasg** [comment]
Fixed via updating the docs – https://github.com/duckdb/duckdb-web/issues/2596
