### ISSUE TITLE
`UNNEST` still returns `Struct` instead of plain column

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11335]
### What happens?

Sometimes, `UNNEST` seems to return `STRUCT(... VARCHAR)` instead of `VARCHAR` (when a `SELECT ARRAY[...]` is provided instead of an `ARRAY[...]`).
Of course I can forceful cast that to `VARCHAR` but this was not predictable and depended on a kind of `casting` trial'n error (which a code generator for example won't be able to do, unless you want to always cast just everything).

### To Reproduce

```sql
-- works
SELECT
  email,
  REGEXP_MATCHES(email, '@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+') AS is_valid
FROM
  (SELECT UNNEST(['foo@example.com', 'bar@example.org', 'www.example.net']) AS email);


-- fails: No function matches the given name and argument types 'regexp_matches(STRUCT(addresses VARCHAR), STRING_LITERAL)'.
SELECT
  email,
  REGEXP_MATCHES(email, '@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+') AS is_valid
FROM
  (SELECT
    ['foo@example.com', 'bar@example.org', 'www.example.net']
    AS addresses),
  UNNEST(addresses) AS email;
```

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by manticore-projects** [comment]
`Cast` alone does not solve the problem though:

```sql
SELECT
  email,
  REGEXP_MATCHES(email, '@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+') AS is_valid
FROM
  (SELECT UNNEST(['foo@example.com', 'bar@example.org', 'www.example.net']) AS email);
```

```
┌─────────────────┬──────────┐
│ email           │ is_valid │
├─────────────────┼──────────┤
│ foo@example.com │ true     │
├─────────────────┼──────────┤
│ bar@example.org │ true     │
├─────────────────┼──────────┤
│ www.example.net │ false    │
└─────────────────┴──────────┘
```

But with the `UNNEST( SELECT ARRAY[...] )` I will receive `Structs`:

```sql
SELECT
  email,
  REGEXP_MATCHES(Cast(email as VARCHAR), '@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+') AS is_valid
FROM
  (SELECT
    ['foo@example.com', 'bar@example.org', 'www.example.net']
    AS addresses),
  UNNEST(addresses) AS email;
```

```
┌─────────────────────────────┬──────────┐
│ email                       │ is_valid │
├─────────────────────────────┼──────────┤
│ {addresses=foo@example.com} │ true     │
├─────────────────────────────┼──────────┤
│ {addresses=bar@example.org} │ true     │
├─────────────────────────────┼──────────┤
│ {addresses=www.example.net} │ false    │
└─────────────────────────────┴──────────┘
```

**Comment by manticore-projects** [comment]
Sorry for the noise, I think I could narrow it down to `UNNEST as SelectItem` (working as expected) vs. `UNNEST as FromItem` (not working as expected).

**Comment by soerenwolfers** [comment]
- You're using a [lateral join](https://duckdb.org/docs/sql/query_syntax/from.html#lateral-joins) here, which happens magically without you having to specify the `LATERAL` keyword
- The laterally joined dataframe has a single column named "addresses"
- You're renaming the joined dataframe `email`. It still has a single column named "addresses"
- You're then using the "magic" functionality that when you select an entire dataframe, you get a single column of structs that contain all the columns of that dataframe

In summary: Everything is as expected (albeit a bit magic).

MWE: The below query does a cross-join of two dataframes; names these two dataframes `df1` and `df2`; and selects the entire dataframes.
```sql
SELECT df1, df2 FROM (VALUES (0)) df1, (VALUES (1)) df2
```
```
┌──────────────────────┬──────────────────────┐
│         df1          │         df2          │
│ struct(col0 integer) │ struct(col0 integer) │
├──────────────────────┼──────────────────────┤
│ {'col0': 0}          │ {'col0': 1}          │
└──────────────────────┴──────────────────────┘
```
