### ISSUE TITLE
Spill-to-disk does not work as expected: Out-of-Memory Errors Raised

### ISSUE THREAD

**Issue by oneturkmen** [duckdb/duckdb#11334]
### What happens?

When running a SQL script to process larger-than-memory set of CSV files, `duckdb` fails with 

```bash
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: could not allocate block of size 30.5 MiB (12.3 GiB/12.3 GiB used)
``` 

#### Little update: Still fails with DuckDB 0.10.1:

If I run DuckDB in-memory mode with 4 GB ram:

```bash
    duckdb.sql("""
duckdb.duckdb.Error: std::bad_alloc
```

If I run DuckDB persistent file mode 4 GB ram:

```bash
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 32002048 bytes (bad allocation)
```

### To Reproduce

0. Install Poetry in Python 3.11
1. Check out this repo: https://github.com/oneturkmen/experiments-with-olap-triad
2. To have all packages for the benchmark, run `poetry shell` and `poetry install`. For quick reproduction `pip install duckdb` suffices.
3. Download [hard drive failure data](https://www.backblaze.com/cloud-storage/resources/hard-drive-test-data#downloadingTheRawTestData) from 2022 Q1 and Q2, and all of 2023 data for our setup:

    ```bash
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q1_2022.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q2_2022.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q1_2023.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q2_2023.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q3_2023.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q4_2023.zip
    unzip '*.zip'
    ```

4. It should look like this:

    ```bash
    $ du -sh data_* --total
    
    6.2G	data_Q1_2022
    7.1G	data_Q1_2023
    6.4G	data_Q2_2022
    7.6G	data_Q2_2023
    8.6G	data_Q3_2023
    9.0G	data_Q4_2023
    45G	total
    ```

5. Run:
    ```bash
    (ulimit -v 4000000; python duckdb_main.py)
    ```
    or
    ```bash
    (ulimit -v 4000000; python duckdb_persistentmode_main.py)
    ```
    inside the poetry environment with `ulimit` helping limit RAM to 4GB.

The python script contains the following code:

```python
import duckdb
import time


def duckdb_test():
    duckdb.sql("""
        SET preserve_insertion_order = false;
        SET temp_directory = './temp';
        CREATE VIEW metrics AS 
        SELECT date, SUM(failure) as failures
        FROM read_csv('*/*.csv', union_by_name = true)
        GROUP BY date;
    """)

    duckdb.sql("""
        COPY metrics TO 'results_duckdb.csv';
    """)

start_time = time.time()
duckdb_test()
end_time = time.time()
print(f"It took {end_time - start_time} seconds to run DuckDB test.")
```

Reference blog post: https://batyr.dev/tech/2024/03/17/data-analysis-with-less-memory.html

### OS:

x86_64

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Batyr

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@oneturkmen Thanks for opening this very detailed issue with a nice reproducer. We'll look into this.

**Comment by szarnyasg** [comment]
Just to double-check, are you running on Linux? (It seems so based on the use of `ulimit`.)

**Comment by michaelkovatt** [comment]
@oneturkmen , did you try setting the following duckdb configs and check if spills to disk.
```
conn.execute("SET memory_limit = '3GB';")
conn.execute("SET max_memory = '3GB';")
```
Noticed that without this setting explicitly set, larger than memory operations caused OOM exceptions for me.

**Comment by grant-arbuckle** [comment]
I am experiencing this same issue when trying to utilize spilling to disk when running on linux for Windows (WSL2). When I explicitly set the memory_limit to a low number in the database config and provide a persistent database, I see a block start to get written, but then the process errors out with "Out of Memory Error: could not allocate block of size 10.6 MiB...".

Why is Duckdb throwing an OOM error when there is plenty of disk space available and I have explicitly told it to use the persistent db? So weird...

**Comment by grant-arbuckle** [comment]
@szarnyasg is there any update on this yet?

**Comment by Mytherin** [comment]
Thanks for reporting! This should now be fixed in https://github.com/duckdb/duckdb/pull/12730. The issue reported here was specifically about the `union_by_name` setting in the CSV reader which causes too many files to be opened and too much data to be kept cached when reading many files using this setting.

**Comment by Zaczero** [comment]
I'm also facing this issue on duckdb v1.2.0, while creating an in-memory index:

```py
@contextmanager
def duckdb_connect():
    with (
        TemporaryDirectory(prefix='osm-ng-duckdb-') as tmpdir,
        duckdb.connect(
            config={
                'checkpoint_threshold': '2GB',
                'memory_limit': '24GB',
                'preserve_insertion_order': False,
                'temp_directory': tmpdir,
            },
        ) as conn,
    ):
        yield conn

...

    with duckdb_connect() as conn:
        parquets = conn.read_parquet(_PARQET_PATHS)  # ~200GB of compressed parquet files
        conn.sql("""
        CREATE TEMP TABLE sequence AS
        SELECT
            sequence_id,
            type,
            id
        FROM parquets
        """)
        conn.sql('CREATE INDEX type_id_sequence_id_idx ON sequence (type, id, sequence_id)')
```

```log
Traceback (most recent call last):
  File "/data/osm-ng/scripts/replication_convert.py", line 140, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "/nix/store/prvvds72d2fswkrncdszk55dxl4pwkgv-python/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/nix/store/prvvds72d2fswkrncdszk55dxl4pwkgv-python/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/prvvds72d2fswkrncdszk55dxl4pwkgv-python/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/data/osm-ng/scripts/replication_convert.py", line 132, in main
    _write_element()
    ~~~~~~~~~~~~~~^^
  File "/data/osm-ng/scripts/replication_convert.py", line 59, in _write_element
    conn.sql('CREATE INDEX type_id_sequence_id_idx ON sequence (type, id, sequence_id)')
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: could not allocate block of size 256.0 KiB (22.3 GiB/22.3 GiB used)
```

**Comment by Mytherin** [comment]
That is unrelated to this issue - which is about reading CSV files with `union_by_name`. Indexes must currently fit in memory. See the documentation at https://duckdb.org/docs/sql/indexes.html#adaptive-radix-tree-art.

Before creating an index I would check to see if you need to create an index. Most workloads in DuckDB do not benefit from the presence of an index. See https://duckdb.org/docs/guides/performance/indexing#art-indexes
