### ISSUE TITLE
TPCH300 Parquet, Query 8 , failed: value is out of range!

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#11359]
### What happens?

running TPCH300, Query8

```
Conversion Error: Casting value "13259183300.8490" to type DECIMAL(12,2) failed: value is out of range!
```

### To Reproduce

generate TPCH300 parquet files using duckdb, then run the 22 queries, they all works except query 8

```sql
PRAGMA tpch(8);
```

### OS:

Linux

### DuckDB Version:

0.10.2.dev213

### DuckDB Client:

Python, Linux

### Full Name:

Mim

### Affiliation:

personal

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @djouallah, I am unable to reproduce this:

```
D PRAGMA tpch(8);
100% ▕████████████████████████████████████████████████████████████▏
┌────────┬──────────────────────┐
│ o_year │      mkt_share       │
│ int64  │        double        │
├────────┼──────────────────────┤
│   1995 │   0.0404593692613372 │
│   1996 │ 0.039514984070003145 │
└────────┴──────────────────────┘
```

**Comment by djouallah** [comment]
just to be sure are you using parquet ?

**Comment by szarnyasg** [comment]
I'm using the built-in TPC-H generator. Can you please provide instructions to export the Parquet files and to run Q8 on them?

**Comment by djouallah** [comment]
sure

https://colab.research.google.com/drive/1ybdfVJdZq5HVRwm7J9OjbLXxYwyaqOdc?usp=sharing

**Comment by djouallah** [comment]
my apology the issue was with the sql query , sorry for the noise

**Comment by szarnyasg** [comment]
No worries, thanks for letting us know!
