### ISSUE TITLE
Group By not commutative

### ISSUE THREAD

**Issue by TreeHappy** [duckdb/duckdb#11361]
### What happens?

In the later attached .db file when i create these two tables:

```sql
create or replace table userVersionConversionProblem as
    (select versions, count(*), month, day from userVersionConversion group by month, day, versions);
create or replace table userVersionConversionWorks as
    (select versions, count(*), month, day from userVersionConversion group by versions, month, day);
```

I would expect them to yield the same rows.

The parquet files have been written with https://github.com/G-Research/ParquetSharp

### To Reproduce

Run the sql statements on the db provided here.

https://github.com/TreeHappy/duckdbIssue

### OS:

Windows

### DuckDB Version:

10.1

### DuckDB Client:

CLI

### Full Name:

Happy Tree

### Affiliation:

Woods

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@TreeHappy thanks for reporting. I'm unable to access the repository, could you please double-check the URL and that it is set to public?

**Comment by TreeHappy** [comment]
Also the parquet files have been written with https://github.com/G-Research/ParquetSharp

**Comment by szarnyasg** [comment]
Hi @TreeHappy, this was fixed by #11340, so it no longer occurs in the nightly build.

**Comment by TreeHappy** [comment]
May i inquire out of curiosity what the cause was?

**Comment by szarnyasg** [comment]
I'm unaware of the specifics – please consult the diff of #11340
