### ISSUE TITLE
Using PER_THREAD_OUTPUT option with EXPORT DATABASE results in unloadable database dump

### ISSUE THREAD

**Issue by dbeer1** [duckdb/duckdb#11362]
### What happens?

I'm trying to use the `PER_THREAD_OUTPUT` to speed up a database export in Parquet format. The export works fine but when I try to import the dump from the same directory I get an error "Not implemented Error: Unsupported option for COPY FROM parquet: PER_THREAD_OUTPUT".

### To Reproduce

In SQL:
```sql
CREATE TABLE test (test INT);
EXPORT DATABASE 'export' (FORMAT 'PARQUET', PER_THREAD_OUTPUT true);
DROP TABLE test;
IMPORT DATABASE 'export';
```
```
Not implemented Error: Unsupported option for COPY FROM parquet: PER_THREAD_OUTPUT
```

### OS:

Linux x64

### DuckDB Version:

0.10.1

### DuckDB Client:

duckdb

### Full Name:

Daniel Beer

### Affiliation:

Bloomberg LP

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
Hi @dbeer1, `PER_THREAD_OUTPUT` is currently not supported with `IMPORT`/`EXPORT`, so this is a feature request. The error should be thrown earlier, when exporting, such that the unloadable dump is never created.
