### ISSUE TITLE
java.lang.RuntimeException: java.sql.SQLException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result

### ISSUE THREAD

**Issue by O-OF-N** [duckdb/duckdb#11373]
### What happens?

When I run DuckDB from my java application, I run into 
`java.lang.RuntimeException: java.sql.SQLException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result` 

This happens only when multiple threads try to read the data. This eventually leads to `table with name does not exist`.

This is pretty similar to https://github.com/duckdb/duckdb/issues/6652 except that this happens in the latest version.

I have attached a minimal example and a minimal parquet file that goes with the example.
[duck_db_error.zip](https://github.com/duckdb/duckdb/files/14764389/duck_db_error.zip)

### To Reproduce

I have attached a minimal example and corresponding parquet

### OS:

mac aarch64

### DuckDB Version:

0.10.0

### DuckDB Client:

Java

### Full Name:

Vinod Mohanan

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
1. This is expected behaviour, connections are stateful, and generally shouldn't be shared across threads

**Comment by jaymmodi** [comment]
@O-OF-N did you find a solution for this?

**Comment by O-OF-N** [comment]
Since they claim this as a feature not a bug, I switched to using something else instead of duckdb

**Comment by jethro-huddle-tech** [comment]
Is there any plan to change this behaviour in the future to allow connections to work with multiple threads simultaneously?

Our current "workaround" is to use a lock around the database connection to ensure threads can only execute one request at a time, but obviously this is not ideal.

**Comment by Mause** [comment]
You should be using one connection per thread, rather than sharing a connection across threads

**Comment by jethro-huddle-tech** [comment]
I understand the limitation, and that is what we are doing. 

However, I was asking if there are plans to support this in the future. It would be a really useful feature to have, especially for people using DuckDB for highly scalable solutions that require local in-memory databases.

**Comment by zhangdapen** [comment]
I also encountered similar problems, but I am using nodejs client

```TypeScript
    async function test4() {
        const db = await Database.create(':memory:');
        await Promise.all(
            Array.from({ length: 10 }, async (_, i) => {
                const stream = db.stream(`
                    SELECT *
                    FROM 'xxx'
                `);
                let count = 0
                for await (const item of stream) {
                    count ++;
                }
                console.log(count);
            })
        )
    }
```
```
libc++abi: terminating due to uncaught exception of type duckdb::InvalidInputException: {"exception_type":"Invalid Input","exception_message":"Attempting to execute an unsuccessful or closed pending query result"}

```
