### ISSUE TITLE
Unable to connect to buenavista duckdb/postgres instance

### ISSUE THREAD

**Issue by liquidcarbon** [duckdb/duckdb#11370]
### What happens?

Trying to make local duckdb mimic postgres via [buenavista](https://github.com/jwills/buenavista).  Seems like you should be able to connect to that from another machine or even the same machine using DuckDB Postgres adapter.

It does not work (see below).

I'm not sure if this is the an issue with DuckDB Postgres or with buenavista thus cc @jwills 

## Buenavista:

```bash
$ pip install buenavista pyarrow duckdb starlette

$ pip list | egrep "buenavista|duckdb|starlette"
buenavista                0.4.0
duckdb                    0.10.1
starlette                 0.36.3

$ python -m buenavista.examples.duckdb_postgres
Using in-memory DuckDB database
Listening on 0.0.0.0:5433
Catalog Error: unrecognized configuration parameter "server_version"

Did you mean: "user"
Catalog Error: unrecognized configuration parameter "server_version"

Did you mean: "user"
```

## DuckDB from the same box
```
$ ./duckdb
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 'dbname=memory host=localhost port=5433' AS db (TYPE postgres, READ_ONLY);
Invalid Error: Failed to execute query "SELECT CURRENT_SETTING('server_version'), (SELECT COUNT(*) FROM pg_settings WHERE name LIKE 'rds%')": Catalog Error: unrecognized configuration parameter "server_version"

Did you mean: "user"

D ATTACH 'host=localhost port=5433' AS db (TYPE postgres, READ_ONLY);
Invalid Error: Failed to execute query "SELECT CURRENT_SETTING('server_version'), (SELECT COUNT(*) FROM pg_settings WHERE name LIKE 'rds%')": Catalog Error: unrecognized configuration parameter "server_version"

Did you mean: "user"

D ATTACH 'host=0.0.0.0 port=5433' AS db (TYPE postgres, READ_ONLY);
Invalid Error: Failed to execute query "SELECT CURRENT_SETTING('server_version'), (SELECT COUNT(*) FROM pg_settings WHERE name LIKE 'rds%')": Catalog Error: unrecognized configuration parameter "server_version"

Did you mean: "user"
```

## DuckDB from remote box:

```
IO Error: Unable to connect to Postgres at dbname=memory host=1.2.3.4 port=5433: connection to server at "1.2.3.4", port 5433 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request
```

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

CLI

### Full Name:

Alex

### Affiliation:

self

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by jwills** [comment]
Hey that’s my fault— BV doesn’t support enough of the Postgres wire protocol to include the more obscure bits of it that DuckDB takes advantage of. Super interesting idea tho— would you mind moving the issue to the BV repo? Thanks!

**Comment by liquidcarbon** [comment]
Wow that was fast :D 

Sure I'll open in BV.  But also... I don't know the function of `SELECT CURRENT_SETTING('server_version'), (SELECT COUNT(*) FROM pg_settings WHERE name LIKE 'rds%')` but maybe worth considering, on the DuckDB side, to not fail if this query won't run?
