### ISSUE TITLE
DuckDB's division behavior is slightly anachronistic in corner cases

### ISSUE THREAD

**Issue by westonpace** [duckdb/duckdb#11374]
### What happens?

DuckDb's floating point division behavior, in corner cases, is a blend of postgres and "IEEE 754 (e.g. datafusion, pandas) and it is not quite the same as either one.

To be clear, I am only attempting to catalog various dialect behaviors.  My goal is not unification.  So please feel free to close this defect if the current behavior is desired (or if a change to current behavior is not warranted).

A summary of current behaviors is this:

| X | Y | DuckDb | Postgres | IEEE 754 | MySQL | SQL Server | Sqlite |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | 0 | NULL | ERROR  | NAN | NULL | ERROR | NULL |
| 0 | NAN | NAN | NULL  | NAN | | | NULL |
| 0 | Infinity | 0 | 0  | 0 | | | NULL |
| NAN | 0 | NULL | ERROR  | NAN | | | NULL |
| NAN | NAN | NAN | NULL  | NAN | | | NULL |
| NAN | Infinity | NAN | NULL  | NAN | | | NULL |
| Infinity | 0 | NULL | ERROR  | Infinity | | | NULL |
| Infinity | NAN | NAN | NULL  | NAN | | | NULL |
| Infinity | Infinity | NAN | NULL  | NAN | | | NULL |

If a change is indeed desired I would be happy to create a PR.  However, I am holding off on that work until confirming what the desired behavior is.

Thanks for the great product!

Update: I had previously listed mysql / sql server in the chart but I realized my data for that column was wrong and I will add it back in soon.

Update2: SQL Server and MySQL appear to have no concept of NaN / Infinity.

### To Reproduce

```sql
SELECT CAST(0 AS DOUBLE PRECISION) / CAST(0 AS DOUBLE PRECISION);
```

### OS:

aarch64

### DuckDB Version:

0.10.2-dev213

### DuckDB Client:

Python

### Full Name:

Weston Pace

### Affiliation:

Substrait

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, we'll take a look

**Comment by soerenwolfers** [comment]
I tried starting this discussion before at https://github.com/duckdb/duckdb/discussions/10956

**Comment by prmelehan** [comment]
I too find this interesting. Is there any detailed documentation on this directly from duckdb?

**Comment by soerenwolfers** [comment]
which part? the operations in the OP now all return ieee754
