### ISSUE TITLE
Memory usage increases after performing update on column of list types, e.g. integer[]

### ISSUE THREAD

**Issue by MSpanik1** [duckdb/duckdb#11383]
### What happens?

If I have an in-memory table with a list column type, e.g. `integer[]`, with no indexes or other specialities, and run an update statement that modifies the list column, memory consumption for the table increases after each update execution. Eventually it starts failing on errors like this:
`TransactionContext Error: Failed to commit: could not allocate block of size 256.0 KiB (95.3 MiB/95.3 MiB used)`

Looking at variables in debugger, it seems that MemoryTag::IN_MEMORY_TABLE is the tag of the memory.

Also before failing, as more and more memory is consumed, speed of these update statments starts getting slower.

### To Reproduce

This table
`create table testing_table(id integer, value_int_list integer[])`
with several rows takes more and more memory if I repeatedly run this update:
`update testing_table set value_int_list = [id]`

Here is C++ testing code that starts failing on my computer after about 30 seconds:

```
#include <iostream>

#include <duckdb.h>
#include <duckdb.hpp>


int main()
{
    duckdb::DBConfig databaseConfig;
    databaseConfig.options.maximum_memory = 100'000'000;
    duckdb::DuckDB database(nullptr, &databaseConfig);

    {
        duckdb::Connection createConnection(database);
        createConnection.Query("create table testing_table(id integer, value_int_list integer[])");
    }

    {
        duckdb::Connection insertConnection(database);
        insertConnection.SetAutoCommit(false);

        duckdb::Appender appender(insertConnection, "testing_table");
        for (int i = 0; i < 1000; i++)
        {
            appender.AppendRow(i, duckdb::Value::EMPTYLIST(duckdb::LogicalType::INTEGER));
        }

        insertConnection.Commit();
    }

    int updates = 0;

    while (true)
    {
        {
            duckdb::Connection updateConnection(database);
            std::unique_ptr<duckdb::MaterializedQueryResult> updateResult = updateConnection.Query("update testing_table set value_int_list = [id]");
            if (updateResult->HasError())
            {
                std::cerr << "Error after " << updates << " updates: " << updateResult->GetError() << std::endl;
            }
        }

        {
            // this doesn't help with RAM usage
            duckdb::Connection checkpointConnection(database);
            checkpointConnection.Query("CHECKPOINT");
            checkpointConnection.Query("VACUUM ANALYZE");
            checkpointConnection.Query("VACUUM ANALYZE testing_table(value_int_list)");
        }

        updates++;
    }

    return 0;
}


```

### OS:

Windows 10 x64

### DuckDB Version:

0.10.1

### DuckDB Client:

C++

### Full Name:

M S

### Affiliation:

ESET, spol. s r.o.

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @MSpanik1 - apologies, I forgot to reply to this issue in detail. Updates on list types are implemented as a sequence of delete and insert operations. On in-memory tables, there are not vacuumed, therefore this is an expected restriction at the moment. A potential workaround is to use an on-disk table and invoke [`CHECKPOINT` to reclaim space](https://duckdb.org/docs/sql/statements/checkpoint.html#reclaiming-space).
