### ISSUE TITLE
java.nio.BufferUnderflowException when reading Blob.getBytes() from JDBC

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#11381]
### What happens?

I cannot read a `Blob` value using `Blob.getBytes()` via JDBC

### To Reproduce

```java
try (Statement s = connection.createStatement();
    ResultSet rs = s.executeQuery("select cast('abc' as varbinary)")
) {
    while (rs.next()) {
        Blob b = rs.getBlob(1);
        System.out.println(Arrays.toString(b.getBytes(1, (int) b.length())));
    }
}
```

This results in:

```
Exception in thread "main" java.nio.BufferUnderflowException
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:826)
	at org.duckdb.DuckDBResultSet$DuckDBBlobResult.getBytes(DuckDBResultSet.java:446)
	at org.jooq.testscripts.JDBC.main(JDBC.java:44)
```

I can't call `rs.getBytes()` either, as that's not implemented (seems worth implementing IMO!)

As a workaround, I can read `Blob.getBinaryStream()`

```java
try (Statement s = connection.createStatement();
    ResultSet rs = s.executeQuery("select cast('abc' as varbinary)")
) {
    while (rs.next()) {
        Blob b = rs.getBlob(1);
        System.out.println(Arrays.toString(b.getBinaryStream().readAllBytes()));
        b.free();
    }
}
```

### OS:

Microsoft Windows [Version 10.0.22631.3296]

### DuckDB Version:

0.10.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Interesting, I'm not sure what the jdbc specified behaviour here is if you try to read beyond the end of a blob (or is the intention that blobs are 1-indexed?)

If you read from the 0-index, it seems to work fine
```java
try (Statement s = connection.createStatement();
    ResultSet rs = s.executeQuery("select cast('abc' as varbinary)")
) {
    while (rs.next()) {
        Blob b = rs.getBlob(1);
        System.out.println(Arrays.toString(b.getBytes(0, (int) b.length())));
    }
}
```

**Comment by Mause** [comment]
Ah, looks like we have implemented it incorrectly: https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/sql/Blob.html#getBytes(long,%20int)

```
pos - the ordinal position of the first byte in the BLOB value to be extracted; the first byte is at position 1
```

**Comment by lukaseder** [comment]
Yes, it's a 1-based index
