### ISSUE TITLE
Conversion Error: Could not convert string 'xx' to INT64

### ISSUE THREAD

**Issue by prophetss** [duckdb/duckdb#11398]
### What happens?

duckdb version 0.10.1 reports an exception when converting numbers to string in case/else, version 0.9.2 is normal.

### To Reproduce

```python
import duckdb
import pandas as pd

t = pd.DataFrame({"a": [48, 49]})
r = duckdb.sql(
    f"""
        select
            CASE
                WHEN a = 48 THEN 'xx'
                WHEN a = 49 THEN 'xxx'
            ELSE a
            END as a1,
        from
            t
        """
)
print(r)    # duckdb.duckdb.ConversionException: Conversion Error: Could not convert string 'xx' to INT64
````

### OS:

linux

### DuckDB Version:

0.10.1

### DuckDB Client:

py39

### Full Name:

N/A

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
This looks expected to me. Replace the else arm by  `a::VARCHAR`. Duckdb did remove some implicit casts in recent versions.

**Comment by Tishj** [comment]
```
D create or replace table tbl as select * from (VALUES (48), (49)) t(a);
D select * from tbl;
┌───────┐
│   a   │
│ int32 │
├───────┤
│    48 │
│    49 │
└───────┘
D select case WHEN a = 48 THEN 'xx' WHEN a = 49 THEN 'xxx' else a end as a1 from tbl;
Conversion Error: Could not convert string 'xx' to INT32
LINE 1: select case WHEN a = 48 THEN 'xx' WHEN a = 49 THEN 'xxx' else a end ...
```

Yea I agree, this looks expected

**Comment by prophetss** [comment]
> This looks expected to me. Replace the else arm by `a::VARCHAR`. Duckdb did remove some implicit casts in recent versions.
It works,thinks!

**Comment by prophetss** [comment]
> This looks expected to me. Replace the else arm by `a::VARCHAR`. Duckdb did remove some implicit casts in recent versions.

It works,thanks!
