### ISSUE TITLE
Cannot reference column from CTE in a set returning function

### ISSUE THREAD

**Issue by redneb** [duckdb/duckdb#11393]
### What happens?

I want to call the `range` function on an integer that is produced by an expensive computation. This integer will also be used in other places as well, so I don't want to run the expensive computation multiple times. A CTE seemed like the right choice here, but I cannot reference the column from the CTE in `FROM`.

### To Reproduce

Just try to run this very minimal example (no setup is required):
```
WITH t1(a) AS (SELECT 7) SELECT * FROM t1, generate_series(1, a)
```
This works fine on postgres & sqlite. But on duckdb, I get this error:
```
Binder Error: No function matches the given name and argument types 'generate_series(INTEGER, VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	generate_series(BIGINT)
	generate_series(BIGINT, BIGINT)
	generate_series(BIGINT, BIGINT, BIGINT)
	generate_series(TIMESTAMP, TIMESTAMP, INTERVAL)
	generate_series(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, INTERVAL)

LINE 1: ... t1(a) AS (SELECT 7) SELECT * FROM t1, generate_series(1, a);
                                                  ^
```

### OS:

Linux

### DuckDB Version:

v0.10.1 4a89d97db8 & nightly v0.10.2-dev263 9247deefc8

### DuckDB Client:

duckdb shell

### Full Name:

John Doe

### Affiliation:

Oracle

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by redneb** [comment]
An additional experiment: Since it is complaining that the second argument of `generate_series` is a `VARCHAR`, let's try to explicitly cast it to an `int`:
```
> WITH t1(a) AS (SELECT 7) SELECT * FROM t1, generate_series(1, a::int);
Conversion Error: Could not convert string 'a' to INT32
LINE 1: ... SELECT * FROM t1, generate_series(1, a::int);
```
So it thinks that the column name, i.e. `a`, is the string `'a'`!

**Comment by redneb** [comment]
Also:
```
> SELECT * FROM (SELECT 7 AS a) t1, generate_series(1, a);
Binder Error: No function matches the given name and argument types 'generate_series(INTEGER, VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	generate_series(BIGINT)
	generate_series(BIGINT, BIGINT)
	generate_series(BIGINT, BIGINT, BIGINT)
	generate_series(TIMESTAMP, TIMESTAMP, INTERVAL)
	generate_series(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, INTERVAL)

LINE 1: SELECT * FROM (SELECT 7 AS a) t1, generate_series(1, a);
                                          ^
```
So it is not specific to CTEs as I originally thought.

**Comment by kryonix** [comment]
This is a known issue currently. See also: https://github.com/duckdb/duckdb/issues/10927. It is currently not possible to use columns of the (here: implicit) lateral join as input parameters.

**Comment by kryonix** [comment]
> I don't want to run the expensive computation multiple times. A CTE seemed like the right choice [...]

A non-materialized CTE will not do what you are trying to do. You will have to use a materialized CTE:

```
WITH t1(a) AS MATERIALIZED [...]
```

**Comment by Mytherin** [comment]
As mentioned this is currently an expected restriction - but the error message is very confusing. I've added a more clear error message in https://github.com/duckdb/duckdb/pull/11436.

**Comment by ggPeti** [comment]
As a workaround, I used `unnest(range(...))`.
