### ISSUE TITLE
CLI fails to detect json array format when reading with STDIN

### ISSUE THREAD

**Issue by quentin-sommer** [duckdb/duckdb#11407]
### What happens?

Reading json array file from STDIN with auto format fails but reading from filename works

### To Reproduce

`example.json`

```json
[
  {
    "k": "v"
  },
  {
    "k": "v2"
  }
]
```

ok

```bash
duckdb -s "SELECT * FROM read_json_auto('example.json', format='auto')"
```

fail

```bash
cat example.json | duckdb -s "SELECT * FROM read_json_auto('/dev/stdin', format='auto')"
```
```text
Invalid Input Error: JSON transform error in file "/dev/stdin", in record/value 1: Expected ARRAY, but got OBJECT: {"k":"v"}
Try increasing 'sample_size', reducing 'maximum_depth', specifying 'columns', 'format' or 'records' manually, setting 'ignore_errors' to true, or setting 'union_by_name' to true when reading multiple files with a different structure.
```

**Expected**

format is correctly resolved to array like for the explicit format:

```bash
cat example.json | duckdb -s "SELECT * FROM read_json_auto('/dev/stdin', format='array')"
```

### OS:

macOS 14.4

### DuckDB Version:

v0.10.1 4a89d97db8

### DuckDB Client:

CLI

### Full Name:

Quentin Sommer

### Affiliation:

Transit App

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
Fixed via #11378
