### ISSUE TITLE
Error setting config `TimeZone` with Python client on `connect`

### ISSUE THREAD

**Issue by seruman** [duckdb/duckdb#11404]
### What happens?

Trying to set `TimeZone` with Python client with `connect()` by passing a config dictionary causes `InvalidInputException`;

AFAIK from docs ICU extension is loaded by default on Python and reference to configuration options in Python docs contains `TimeZone` as a configuration option;
https://duckdb.org/docs/api/python/overview.html#configuration
https://duckdb.org/docs/configuration/overview#configuration-reference

```python
import duckdb
conn.sql("select * from duckdb_extensions() where extension_name = 'icu'").show()
```

```
┌────────────────┬─────────┬───────────┬──────────────┬──────────────────────────────────────────────────────────────────┬───────────┐
│ extension_name │ loaded  │ installed │ install_path │                           description                            │  aliases  │
│    varchar     │ boolean │  boolean  │   varchar    │                             varchar                              │ varchar[] │
├────────────────┼─────────┼───────────┼──────────────┼──────────────────────────────────────────────────────────────────┼───────────┤
│ icu            │ true    │ true      │ (BUILT-IN)   │ Adds support for time zones and collations using the ICU library │ []        │
└────────────────┴─────────┴───────────┴──────────────┴──────────────────────────────────────────────────────────────────┴───────────┘
```

Setting it with `SET ...` directive seems to work fine;
```python
import duckdb

conn = duckdb.connect()
conn.sql("select current_timestamp").show()
conn.sql("set TimeZone = 'UTC'")
conn.sql("select current_timestamp").show()
```

```
┌────────────────────────────┐
│     current_timestamp      │
│  timestamp with time zone  │
├────────────────────────────┤
│ 2024-03-28 16:41:07.292+03 │
└────────────────────────────┘

┌────────────────────────────┐
│     current_timestamp      │
│  timestamp with time zone  │
├────────────────────────────┤
│ 2024-03-28 13:41:07.293+00 │
└────────────────────────────┘
```

### To Reproduce

```python
import duckdb
conn = duckdb.connect(config={"TimeZone" : "UTC"})
```

```
Traceback (most recent call last):
  File "repro.py", line 3, in <module>
    conn = duckdb.connect(config={"TimeZone" : "UTC"})
duckdb.duckdb.InvalidInputException: Invalid Input Error: Unrecognized configuration property "TimeZone"
```

### OS:

macOS

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Selman Kayrancioglu

### Affiliation:

Peak

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
I suspect the problem is just that the ICU extension has not been loaded yet. It is what defines the `Calendar` and `TimeZone` settings.

**Comment by Tishj** [comment]
Yea Gabor ran into this issue about a week ago actually and I suspect as much, I'll have to see if we can delay setting these settings until the extension is loaded.

It's a little difficult because some settings have to be set before the database is started.
Since these are `connect` options, it also makes some sense to say these only accept options that can be set on Database creation.

You have the option to set the other settings after startup

**Comment by adriangb** [comment]
I'd like to point out that there's a conflict with #9381: on a connection that has `lock_configuration=true` there is no way to do `SET timestamp='UTC'` and hence no way to get UTC timestamps out of DuckDB.
