### ISSUE TITLE
quantile_cont/disc ORDER BY support

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11419]
### What happens?

`quantile_cont` and `quantile_disc` doesn't currently support ordering, so that the ugly SQL standard `WITHIN GROUP` aggregates are required when `quantile_cont(column, q ORDER BY column DESC)`  is desired. 

Additionally, it is not currently possible even with the `WITHIN GROUP` aggregates, to achieve `quantile_disc(column, q ORDER BY other_column)`  (which seems nonsensical at first, but is perfectly well-defined and useful, I promise.)

### To Reproduce

```sql
SELECT 
    percentile_cont(0.8) WITHIN GROUP (ORDER BY x DESC),
    quantile_cont(x, 0.8 ORDER BY x DESC),
FROM 
    (VALUES (2), (1)) _(x);
```
```
BinderException: Binder Error: No function matches the given name and argument types 'quantile_cont(INTEGER, INTEGER, DECIMAL(2,1))'. You might need to add explicit type casts.
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Sorry, battling features. We should not be injecting the missing arguments when they are not missing...

Incidentally I hope to get to [windowed versions](https://dl.acm.org/doi/pdf/10.1145/3514221.3526184) with independent sorting axes after 1.0.

**Comment by soerenwolfers** [comment]
Great to hear that's on your radar. Am I justified to be optimistic that this will bring a positive resolution to https://github.com/duckdb/duckdb/discussions/11425 eventually as well?

**Comment by soerenwolfers** [comment]
Also, sorry to hijack this even more, but since you seem to be the window expert: do you think there is any hope for https://github.com/duckdb/duckdb/discussions/10703?
