### ISSUE TITLE
DuckDB secret_manager not retaining persistent secrets across sessions when using secret_directory

### ISSUE THREAD

**Issue by JichaoS** [duckdb/duckdb#11430]
### What happens?

It seems like duckdb doesn't remember persistent secrets when I use SET secret_directory across different sessions.

However, if I don't use SET secret_directory everything works as expected (secrets remembered across restarts). Maybe there's some scanning of secret_directory on init that's not done on SET secret_directory

### To Reproduce

```bash
mkdir ~/.duckdb/secrets
```

```sql
SET secret_directory='~/.duckdb/secrets';
CREATE PERSISTENT SECRET my_persistent_secret ( TYPE S3, KEY_ID 'my_secret_key', SECRET 'my_secret_value' );
```
Exit the session
Start a new session

```
SET secret_directory='~/.duckdb/secrets';
FROM duckdb_secrets();
```

Before existing the session,  FROM `duckdb_secrets();` yields the expected secret. 

### OS:

OSX

### DuckDB Version:

v0.10.2-dev311 62d1fb0c5a

### DuckDB Client:

CLI

### Full Name:

Jichao Sun

### Affiliation:

Definite

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by JichaoS** [comment]
Hey @samansmink any luck in reproducing?

**Comment by JichaoS** [comment]
Ping @samansmink

**Comment by samansmink** [comment]
Sorry for the late response here @JichaoS, I can reproduce this and will look into fixing this

**Comment by samansmink** [comment]
In the meantime I think the culprit is the `~` is not expanded properly, manually expanding the home directory solves the issue for me
