### ISSUE TITLE
DIVIDE() function does not return NAN or INFINITE, but NULL

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11450]
### What happens?

```
Divide(25,0)  --> NULL, but should be +Infinity
Divide(-25,0) --> NULL, but should be -Infinity
Divide(0,0)   --> NULL, but should be NAN
```

This becomes a problem when the functions `IsNan()` or `IsInf()` are used, because those also will return NULL.

```sql
select IsInf( Divide(25, 0)) IsInf;
-- Expect TRUE
/*
┌───────┐
│ IsInf │
├───────┤
│       │
└───────┘
*/
```

However, this works:
```sql
select IsNan( Divide(FLOAT 'Infinity', FLOAT 'Infinity')  ) IsNan;

/*
┌───────┐
│ IsNan │
├───────┤
│ true  │
└───────┘
*/
```

### To Reproduce

```sql
select divide(25,0)
union all
select divide(0,0);
```

### OS:

Linux

### DuckDB Version:

0.11-Snapshot

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
See https://github.com/duckdb/duckdb/discussions/10956
