### ISSUE TITLE
0.11 Snapshot: Cannot create a list of types STRUCT(t VARCHAR, len INTEGER) and STRUCT(VARCHAR, INTEGER)

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11467]
### What happens?

Generating Lists from STRUCT suddenly fails with version 0.11-Snapshot

### To Reproduce

```sql
-- works with 0.10.0
select Unnest([
  { t:'abc', len:5 }::STRUCT(t VARCHAR, len integer),
   ('abc', 2),
], recursive => true);
```

Fails with 0.11-Snapshot
```sql
select Unnest([
  { t:'abc', len:5 }::STRUCT(t VARCHAR, len integer),
   ('abc', 2),
], recursive => true);
```
```
Binder Error: Cannot create a list of types STRUCT(t VARCHAR, len INTEGER) and STRUCT(VARCHAR, INTEGER) - an explicit cast is required LINE 3:    ('abc', 2),
```

### OS:

Linux

### DuckDB Version:

0.11-Snapshot

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I imagine this is a result of <https://github.com/duckdb/duckdb/pull/11396>
Though I can't immediately tell if this is intended or an unwanted side effect / bug?

**Comment by manticore-projects** [comment]
> I would guess it's the latter, because unnamed structs should be able to be cast implicitly to a named struct of the same types

I concur or else you would have to explicitly cast every single row of your array?

At the same time I wonder: are there no standard unit tests to catch such things before merging?
