### ISSUE TITLE
Julia bindings: Appender does not accept missing/nothing values

### ISSUE THREAD

**Issue by xitology** [duckdb/duckdb#11475]
### What happens?

Using Julia package DuckDB.jl, I populate a table using Appender interface. I represent NULL values as Julia's `missing` constant, just as DuckDB.jl does. However, Appender rejects this value with an error: "unsupported type for append".

This appears to be a bug. Here is the respective code that is supposed to handle missing values:
https://github.com/duckdb/duckdb/blob/main/tools/juliapkg/src/appender.jl#L87-L88
```julia
append(appender::Appender, val::Type{Missing}) = duckdb_append_null(appender.handle);
append(appender::Appender, val::Type{Nothing}) = duckdb_append_null(appender.handle);
```

However the type declaration is incorrect: `Type{Missing}` or `Type{Nothing}` indicates that the expected value is a *type* `Missing` or `Nothing`, not a (singleton) value of that type.  The correct way to write this type declaration is:
```julia
append(appender::Appender, ::Union{Missing, Nothing}) = duckdb_append_null(appender.handle)
```

### To Reproduce

Here is the script `duckdb-appender-bug.jl` that reproduces the problem:
```julia
using DuckDB
using DataFrames

db = DuckDB.DB()

DBInterface.execute(db, "CREATE OR REPLACE TABLE data (x INT)")

df = DataFrame(x = [1, 2, missing, nothing])
appender = DuckDB.Appender(db, "data")
for i in eachrow(df)
    for j in i
        DuckDB.append(appender, j)
    end
    DuckDB.end_row(appender)
end
DuckDB.flush(appender)
DuckDB.close(appender)
```

It triggers the following error:
```bash
julia duckdb-appender-bug.jl 
```
```text
missing
ERROR: LoadError: unsupported type for append
Stacktrace:
 [1] append(appender::DuckDB.Appender, val::Missing)
   @ DuckDB ~/.julia/packages/DuckDB/HNc3K/src/appender.jl:102
 [2] top-level scope
   @ ~/duckdb-appender-bug.jl:12
in expression starting at ~/duckdb-appender-bug.jl:10
```

### OS:

Linux x64

### DuckDB Version:

v0.10.1

### DuckDB Client:

Julia

### Full Name:

Kyrylo Simonov

### Affiliation:

Tufts CTSI

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! That makes sense. Would you be open to submitting a PR that addresses this?

**Comment by Mytherin** [comment]
Thanks - should be fixed now by https://github.com/duckdb/duckdb/pull/11508
