### ISSUE TITLE
0.10.1 breaks build on FreeBSD 13

### ISSUE THREAD

**Issue by patmaddox** [duckdb/duckdb#11487]
### What happens?

#10297 introduces the following lines:

```c++
#ifndef __MVS__
	/* control modes - set 8 bit chars */
	raw.c_iflag |= IUTF8;
#endif
```

which breaks compilation on FreeBSD 13.

When I remove those lines (using latest `main` which is currently 5345a494c7d2d9f69f3d2486c66c191e67a93474), compilation succeeds and I get a usable binary.

Given that [`__MVS__` indicates z/OS](https://www.ibm.com/docs/en/zos/2.4.0?topic=macros-related-platform), I think this check is overly broad. Instead there should be an `#ifdef` that targets the platform that uses `IUTF8` - which based on [this man page](https://man7.org/linux/man-pages/man3/tcsetattr.3.html) appears to be Linux 2.6.4+.

### To Reproduce

#10719 reported this issue on 13.x, and apparently it builds successfully on 14. I'm not sure why, as 14 does not define `__MVS__`.

1. clone the repo on FreeBSD 13
2. `gmake`

log:

```
[ 89%] Building CXX object tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/terminal.cpp.o
/tmp/duckdb/tools/shell/linenoise/terminal.cpp:72:17: error: use of undeclared identifier 'IUTF8'
        raw.c_iflag |= IUTF8;
                       ^
1 error generated.
gmake[3]: *** [tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/build.make:146: tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/terminal.cpp.o] Error 1
gmake[3]: Leaving directory '/tmp/duckdb/build/release'
gmake[2]: *** [CMakeFiles/Makefile2:7719: tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/all] Error 2
gmake[2]: Leaving directory '/tmp/duckdb/build/release'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/tmp/duckdb/build/release'
gmake: *** [Makefile:290: release] Error 2

```

### OS:

FreeBSD 13.2

### DuckDB Version:

0.10.1

### DuckDB Client:

CLI

### Full Name:

Pat Maddox

### Affiliation:

Ratio PBC

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by patmaddox** [comment]
FreeBSD 14 [adds `IUTF8`](https://github.com/freebsd/freebsd-src/blame/6e77fccf3445760d44ce132c9fc35d4a2f25ec0e/sys/sys/_termios.h#L98) which is why it compiles there.

**Comment by Mause** [comment]
z/OS being indicated by that def sounds pretty specific to me, this sounds like an issue with freebsd?

**Comment by carlopi** [comment]
@patmaddox: we were planning on adding a CI run that checks for compilation failures against docker images , something like:

```
docker run -i --rm -v $(pwd)/duckdb:/duckdb --workdir /duckdb alpine:latest <<< "apk add g++ git make cmake ninja && GEN=ninja make" 2>&1
```

Would you be wiling to contribute the FreeBSD equivalent so that we have the means to catch this earlier going forward?
Even just putting that in a [not yet existent] `scripts/check_docker.sh` file would be handy to have.

**Comment by patmaddox** [comment]
> z/OS being indicated by that def sounds pretty specific to me, this sounds like an issue with freebsd?

It’s not specific… it’s an `ifndef` which means “everything in the world that is not z/OS.”

FreeBSD 13 doesn’t define `IUTF8`. As the man page says, it’s not POSIX so you can’t rely on it being present.

#11488 proposes a fix that I believe makes sense

**Comment by patmaddox** [comment]
> Would you be wiling to contribute the FreeBSD equivalent so that we have the means to catch this earlier going forward?

I’m not aware of reliable GitHub actions support for FreeBSD. [Cirrus CI](http://cirrus-ci.org/) supports it - do you want to add another CI service for FreeBSD specifically? I’ve set it up in the past, but most projects don’t want to add it to their build, which I understand.

One thing to consider for this specific issue is to do a docker build using an older Linux image that doesn’t define `IUTF8`. That wouldn’t catch all FreeBSD-related things, but it would catch this one.

**Comment by carlopi** [comment]
> I’m not aware of reliable GitHub actions support for FreeBSD. [Cirrus CI](http://cirrus-ci.org/) supports it - do you want to add another CI service for FreeBSD specifically?

Most likely not, or not at this point.

Thanks for the feedback.

**Comment by Mause** [comment]
> > Would you be wiling to contribute the FreeBSD equivalent so that we have the means to catch this earlier going forward?
> 
> I’m not aware of reliable GitHub actions support for FreeBSD. [Cirrus CI](http://cirrus-ci.org/) supports it - do you want to add another CI service for FreeBSD specifically? I’ve set it up in the past, but most projects don’t want to add it to their build, which I understand.
> 
> One thing to consider for this specific issue is to do a docker build using an older Linux image that doesn’t define `IUTF8`. That wouldn’t catch all FreeBSD-related things, but it would catch this one.
> 

Are there really no docker images of freebsd available?

**Comment by patmaddox** [comment]
> Are there really no docker images of freebsd available?

I’ve never seen/used FreeBSD within Docker before. I did a quick search of Docker Hub and found a few things people have put together. I suppose it’s a similar technique to [windows-inside-docker](https://hub.docker.com/r/dockurr/windows) - use docker to launch a VM running the guest OS. Seems like a lot of layers of virtualization to me… but an interesting technique nonetheless, that could make FreeBSD CI available to more open source projects.
