### ISSUE TITLE
Issue found on page 'Nested Functions': `ARRAY_REVERSE` (not working) vs. `ARRAY_REVERSE_SORT` (working) 

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11491]
Page URL: <https://duckdb.org/docs/sql/functions/nested.html>

(At least to me) any difference between `ARRAY_REVERSE` and `ARRAY_REVERSE_SORT` is not clear. The description sounds like they are doing the same?
The example for `ARRAY_REVERSE` is also mood since the input is not explained.

Although an example makes it look like only `ARRAY_REVERSE_SORT` was working:

``` sql

WITH example AS (
  SELECT [1, 2, 3] AS arr UNION ALL
  SELECT [4, 5] AS arr UNION ALL
  SELECT [] AS arr
)
SELECT
  arr,
  ARRAY_REVERSE(arr) AS reverse_arr_fails
FROM example;


/* returns
┌───────────┬───────────────────┐
│ arr       │ reverse_arr_fails │
├───────────┼───────────────────┤
│ [3, 2, 1] │ [3, 2, 1]         │
├───────────┼───────────────────┤
│ [5, 4]    │ [5, 4]            │
├───────────┼───────────────────┤
│ []        │ []                │
└───────────┴───────────────────┘
*/
```

Edit: this is utterly confusing! It appears like `ARRAY_REVERSE_SORT` does not alter the array but returns a new reversed copy while `ARRAY_REVERSE` alters the array but returns the original not-reversed array?! Does this make any sense?

**Comment by szarnyasg** [comment]
@manticore-projects thanks for the reproducer. I think the documentation is now in a good shape, so I transferred this thread to the main DuckDB repository. Our engineers will take a look.

**Comment by kryonix** [comment]
This issue sounds related to the bug discovered in https://github.com/duckdb/duckdb/pull/10587. However, it should have been fixed with https://github.com/duckdb/duckdb/pull/10747.

**Comment by manticore-projects** [comment]
I just have tried 0.11 snapshot and there it seems to work correctly.

```sql

-- 0.11
WITH example AS (
  SELECT [1, 2, 3, 1, 2, 3] AS arr UNION ALL
  SELECT [4, 5] AS arr UNION ALL
  SELECT [] AS arr
)
SELECT
  arr,
  ARRAY_REVERSE(arr) AS reverse_arr,
  ARRAY_REVERSE_SORT(arr) AS reverse_arr,
  ARRAY_REVERSE(ARRAY_REVERSE_SORT(arr)) test
FROM example;

/*
┌────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│ arr                │ reverse_arr        │ reverse_arr        │ test               │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┤
│ [1, 2, 3, 1, 2, 3] │ [3, 2, 1, 3, 2, 1] │ [3, 3, 2, 2, 1, 1] │ [1, 1, 2, 2, 3, 3] │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┤
│ [4, 5]             │ [5, 4]             │ [5, 4]             │ [4, 5]             │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┤
│ []                 │ []                 │ []                 │ []                 │
└────────────────────┴────────────────────┴────────────────────┴────────────────────┘
*/

I think we can close this then, shall we?
