### ISSUE TITLE
LIST_EXTRACT not working with composed type containing a fixed length array

### ISSUE THREAD

**Issue by FredoH1010** [duckdb/duckdb#11492]
### What happens?

When trying to execute a LIST_EXTRACT on a composite type containing a fixed length array, i.e. list of fixed length array "int[2][]" or a list of structs "struct(pos int[2], x int)[]", the execution will result in a not implemented error. While actually the expected behaviour is of it to function normally, as the condition for nesting (https://duckdb.org/docs/sql/data_types/overview#nesting) is met.

### To Reproduce

Execute the following statement in duckdb:

```sql
SELECT list_extract(ARRAY[[0, 0], [1, 1]] :: int[2][], 1);
```

To produce error:

Not implemented Error: Unimplemented type for LIST_EXTRACT

### OS:

Windows

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Fredo Hogen

### Affiliation:

Universität Tübingen

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @FredoH1010 thanks for reporting this. I could reproduce the issue – we'll take a look.

**Comment by cabreraalex** [comment]
Hi, I am running into this issue as well

**Comment by Maxxen** [comment]
This has been fixed on main/nightly.

```sql
v1.0.1-dev4162 2077b0afed
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT list_extract(ARRAY[[0, 0], [1, 1]] :: int[2][], 1);
┌──────────────────────────────────────────────────────────────────────────────────────────────┐
│ list_extract(CAST((ARRAY[main.list_value(0, 0), main.list_value(1, 1)]) AS INTEGER[2][]), 1) │
│                                          integer[2]                                          │
├──────────────────────────────────────────────────────────────────────────────────────────────┤
│ [0, 0]                                                                                       │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by cabreraalex** [comment]
great, thanks!
