### ISSUE TITLE
json_merge_patch removes nulls when they should be left alone during merge

### ISSUE THREAD

**Issue by dioptre** [duckdb/duckdb#11500]
### What happens?

When I:
```sql
select json_merge_patch('{"g":5}', '{"g":null}');
```
Result:
```
┌───────────────────────────────────────────┐
│ json_merge_patch('{"g":5}', '{"g":null}') │
│                   json                    │
├───────────────────────────────────────────┤
│ {}                                        │
└───────────────────────────────────────────┘
```
g is removed. 

g should be null

Think that might suit some people, but the merge technically should keep the null. Can we add an option for both options?

### To Reproduce

-

### OS:

Mac

### DuckDB Version:

10

### DuckDB Client:

Python

### Full Name:

Andrew Grosser

### Affiliation:

Sourcetable

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
Hi @dioptre, we've copied [MySQL's behavior](https://dev.mysql.com/doc/refman/8.3/en/json-modification-functions.html#function_json-merge-patch) for `json_merge_patch`, and we use [`yyjson`](https://github.com/ibireme/yyjson)'s [RFC 7386](https://datatracker.ietf.org/doc/html/rfc7386)-compliant implementation to achieve this. I agree that keeping `null` would be nice, but that is not compliant with the RFC, and not implemented in `yyjson`, so the feature that you are requesting will not be implemented until it is implemented in `yyjson`.
