### ISSUE TITLE
`JSON_GROUP_ARRAY(DISTINCT key)`  returns invalid input

### ISSUE THREAD

**Issue by trevorstarick** [duckdb/duckdb#11503]
### What happens?

I was trying to run a query containing a `JSON_GROUP_ARRAY` and got the following error: 

![image](https://github.com/duckdb/duckdb/assets/494354/a1ccfd2b-a87d-43b2-a0ee-c08c2aab8ceb)

I did a bit of digging and from what I can see `TO_JSON(LIST(x))` is the macro that replaces `JSON_GROUP_ARRAY` and then I noticed that `TO_JSON(LIST(DISTINCT name))` seems to work as intended.

### To Reproduce

```
CREATE TABLE example (name TEXT);
INSERT INTO example (name) VALUES ('a'), ('b'), ('a');
SELECT JSON_GROUP_ARRAY(DISTINCT name) FROM example; -- this doesn't work
SELECT TO_JSON(LIST(DISTINCT name)) FROM example; -- this does work
```

### OS:

aarch64

### DuckDB Version:

v0.10.1

### DuckDB Client:

CLI

### Full Name:

Trevor Starick

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by yuphing-ong** [comment]
This seems to be present in client v1.0.0 1f98600c2c as well as go-duckdb v1.6.5.  Changing to to_json(list(<query>)) also is a workaround.
