### ISSUE TITLE
ODBC to named file does not work

### ISSUE THREAD

**Issue by ErikJansenIRefact** [duckdb/duckdb#11510]
### What happens?

I try to connect to existing duckdb database with ODBC on a Mac. 
The connect succeeds but it seems the connection is made to an empty in memory database.
No tables are available although they are in the database.

### To Reproduce

Install ODBC as documented.
Create a database test.db in home folder and create a table with name test (by means of duckdb without odbc). Insert a record into the table:

```bash
duckdb test.db
```

```sql
create table test (id integer);
insert into test values (1);
```

Create an entry in `~/.odbc.ini`:
```
[duckdb-test]
Driver = DuckDB Driver
Database=/Users/erik/test.db
allow_unsigned_extensions=true
```

Connect with isql:

```bash
isql duckdb-test
```

```sql
select * from test;
```

Returns error. 

### OS:

macOS Sonoma

### DuckDB Version:

10.0.0

### DuckDB Client:

odbc

### Full Name:

Erik Jansen

### Affiliation:

I-Refact BV

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by kimmolinna** [comment]
Have you tried to use the default duckdb DSN with the following command `isql "DRIVER={DuckDB Driver};DATABASE=/Users/erik/test.db"`? At least on Windows I can use `:memory:` DSN with DATABASE-connection string on Power Bi.

**Comment by ErikJansenIRefact** [comment]
iusql "DRIVER={DuckDB Driver};DATABASE=/Users/erik/test.db" seems to work. Thanks for that ( isql doesn't accept a connection string where iusql does).

So it seems that connecting with a dsn (specified in odbc.ini) doesn't work?

**Comment by kimmolinna** [comment]
It looks like that. I tested this also on macOS and opened an issue on https://github.com/duckdb/duckdb-odbc/issues/27

**Comment by kimmolinna** [comment]
And It's working on Linux.
