### ISSUE TITLE
json_valid() only short-circuits sometimes

### ISSUE THREAD

**Issue by tongyliu** [duckdb/duckdb#11536]
### What happens?

One use case for the `json_valid()` function is checking whether a string column contains valid JSON before performing further JSON operations on it. I'd expect something like `WHERE json_valid(col) AND json_type(col) == 'OBJECT')` to work, but in DuckDB v0.10.1 an error is thrown when `col` contains text that can't be parsed as JSON.

We've noticed that short-circuiting behavior differs depending on whether a column reference or literal is used. We haven't tested with other functions but could it be plausible that there's a broader issue with conditional short-circuiting? 

### To Reproduce

```sql
select json_valid(x) FROM VALUES ('{}'), ('true'), ('oh no') t(x);
```
```text
┌───────────────┐
│ json_valid(x) │
│    boolean    │
├───────────────┤
│ true          │
│ true          │
│ false         │
└───────────────┘
```
```sql
select json_valid(x) and json_type(x) == 'OBJECT' FROM VALUES ('{}'), ('true'), ('oh no') t(x);
```
```
Invalid Input Error: Malformed JSON at byte 0 of input: unexpected character.  Input: oh no
```
```sql
select json_valid('oh no') and json_type('oh no') == 'OBJECT';
```
```text
┌───────────────────────────────────────────────────────────┐
│ (json_valid('oh no') AND (json_type('oh no') = 'OBJECT')) │
│                          boolean                          │
├───────────────────────────────────────────────────────────┤
│ false                                                     │
└───────────────────────────────────────────────────────────┘
```

### OS:

MacOS (Apple Silicon)

### DuckDB Version:

v0.10.1

### DuckDB Client:

shell

### Full Name:

Tong Liu

### Affiliation:

Watershed

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
You can use this as a workaround for now:
```sql
create table test (s varchar);
insert into test values ('{}'), ('true'), ('oh no');
D select case when json_valid(s) then json_type(s) = 'OBJECT' else false end is_obj from test;
┌─────────┐
│ is_obj  │
│ boolean │
├─────────┤
│ true    │
│ false   │
│ false   │
└─────────┘
```
The `AND` expression does not properly short-circuit, but `CASE` does - nothing to do with `json_valid`
