### ISSUE TITLE
Unable to download Arrow extension on Windows

### ISSUE THREAD

**Issue by nconsulting** [duckdb/duckdb#11538]
### What happens?

I'm trying to download the Arrow extension for Windows (amd64), using the following URLS:

http://extensions.duckdb.org/v0.10.0/windows_amd64/arrow.duckdb_extension.gz
http://extensions.duckdb.org/v0.10.1/windows_amd64/arrow.duckdb_extension.gz

Both give me access denied errors. I tested a couple of other urls, which do work:

http://extensions.duckdb.org/v0.10.1/windows_amd64/json.duckdb_extension.gz
http://extensions.duckdb.org/v0.10.0/linux_amd64/arrow.duckdb_extension.gz

### To Reproduce

Manual download from http://extensions.duckdb.org/v0.10.0/windows_amd64/arrow.duckdb_extension.gz

### OS:

Windows

### DuckDB Version:

0.10.0 and 0.10.1

### DuckDB Client:

DBeaver

### Full Name:

Nick Snels

### Affiliation:

NConsulting

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Hi, thanks for raising this.

This current limitation is tracked at https://github.com/duckdb/arrow/issues/20 in the apposite duckdb/arrow repository.
