### ISSUE TITLE
IO Error: Could not read file temp storage file: Reached the end of the file.

### ISSUE THREAD

**Issue by kobusherbst** [duckdb/duckdb#11543]
### What happens?

When executing a query on a large table (>900 million records) I get the following error:
Query
``` sql
WITH resdays AS (
    SELECT 
    md.IndividualId,
    md.HouseholdId,
    md.DayDate,
    md.HHResLocationId,
    rd.LocationId IndResLocationId,
    md.HHMemStartType,
    md.HHMemEndType,
    md.HHMemStart,
    md.HHMemEnd,
    rd.StartType IndResStartType,
    rd.EndType IndResEndType,
    rd.Episode,
    rd."Start" IndResStart,
    rd."End" IndResEnd,
    CASE
        WHEN md.HHResLocationId IS NULL OR rd.LocationId IS NULL THEN COALESCE(md.HHRelationshipTypeId + 100, 999)
        WHEN md.HHResLocationId = rd.LocationId THEN COALESCE(md.HHRelationshipTypeId, 12)
        ELSE COALESCE(md.HHRelationshipTypeId + 100, 999)
    END HHRank,
    md.HHRelationshipTypeId
    FROM main.HouseholdMembershipDaysWithLocation md
    LEFT JOIN main.IndividualResidencyDays rd USING(IndividualId, DayDate)
),
ranked_resdays AS (
    SELECT
        IndividualId, DayDate, HouseholdId, HHResLocationId, IndResLocationId,
        HHMemStartType, HHMemEndType, HHMemStart, HHMemEnd,
        IndResStartType, IndResEndType, IndResStart, IndResEnd,
        HHRank, HHRelationshipTypeId, Episode,
        ROW_NUMBER() OVER (PARTITION BY IndividualId, DayDate ORDER BY HHRank, HouseholdId) seq,
        COUNT(*) OVER (PARTITION BY IndividualId, DayDate) Memberships
    FROM resdays
)
INSERT INTO IndividualPreferredHHDays SELECT
  * EXCLUDE (seq)
FROM ranked_resdays
WHERE seq = 1;
```
failed: IO Error: Could not read file "E:\Data\Demography\AHRI\AHRI.duckdb.tmp\duckdb_temp_storage-1.tmp" (error in ReadFile(location: 1162608640, nr_bytes: 262144)): Reached the end of the file.

Table HouseholdMembershipDaysWithLocation has 987 534 557 records, table IndividualResidencyDays has 669 390 224 records. There are no indexes defined on these tables. There is more than 200GB free space on the disk E, the operating system disk has >100GB free.

### To Reproduce

The error is reproducible, but difficult to provide a MRE due to the size of the tables involved. When I run the query with about 10% of the records, it completes without problems. HouseholdMembershipDaysWithLocation: 11 077 828 records, table IndividualResidencyDays: 7 196 924 records.

### OS:

Windows 11 Education 23H2 22631.3296 x64 128GB RAM 8 processors

### DuckDB Version:

v0.10.0

### DuckDB Client:

Julia

### Full Name:

Kobus Herbst

### Affiliation:

Africa Health Research Institute, Durban, South Africa

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @kobusherbst, unfortunately, this issue is not reproducible without the data set. Let us know how you'd like to proceed.

**Comment by kobusherbst** [comment]
This problem has not recurred with the 1.0 release
