### ISSUE TITLE
Views with non qualified references don't work outside of their schema

### ISSUE THREAD

**Issue by ebrassell** [duckdb/duckdb#11549]
### What happens?

This seems related to #6704 but I can reproduce without using an attached database.

It seems that object references are resolved in the context of the running query, and not in the schema in which they are deployed.  I would expect that the latter is ideal behavior since a view should return the same result regardless of the where it is queried from.

### To Reproduce

```sql
use memory;
create schema schema_a;
create schema schema_b;
use memory.schema_a;
create table model_a1 as select 1 as col_1;
create view model_a2 as select * from model_a1;
use memory.schema_b;
select * from schema_a.model_a2;
```
<img width="541" alt="image" src="https://github.com/duckdb/duckdb/assets/31701272/20b968b3-c691-40b2-a2c9-827023c55f8a">

### OS:

macOS,x64

### DuckDB Version:

v0.10.1,0.10.2.dev311

### DuckDB Client:

Python, DuckDB Web Shell

### Full Name:

Eric Brassell

### Affiliation:

Working on OSS dbt alternative (repo not public yet)

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
This has been fixed by https://github.com/duckdb/duckdb/pull/13921
