### ISSUE TITLE
Internal exception after referencing unnested column

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11540]
### What happens?

Referencing the name of a `unnest` column breaks the duckdb connection and requires a restart.

### To Reproduce

```sql
SELECT 
unnest([]) AS unnested,
sum(unnested) OVER ();
```
```
Error: INTERNAL Error: Failed to bind column reference "unnested" [7.1] (bindings: [0.0])
```
then
```sql
SELECT 1;
```
```
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed to bind column reference "unnested" [7.1] (bindings: [0.0])"
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

CLI

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by guenp** [comment]
Is this related to https://github.com/duckdb/duckdb/issues/5703?
I am unable to reproduce this in 0.10.2, I get "`Binder Error: UNNEST not supported here`"

**Comment by soerenwolfers** [comment]
I cannot reproduce this anymore, neither with 0.10.2 nor with nightly. 

I did recently notice that I hadn't upgraded my CLI for a while (thinking that upgrading my Python installation would update my CLI as well), so maybe my version specification in this ticket was incorrect.

 I'd be tempted to close, but @szarnyasg since you added a "reproduced" here, I'll wait for you to also confirm before closing.

**Comment by szarnyasg** [comment]
@guenp @soerenwolfers indeed this is related to #5703 and it no longer occurs in 0.10.2+. Thanks for the original report and the request for conformation!
