### ISSUE TITLE
FATAL Error: Failed to create checkpoint because of error: Operation requires a flat vector but a non-flat vector was encountered

### ISSUE THREAD

**Issue by user8555** [duckdb/duckdb#11542]
### What happens?

The app is reading stream events, converting it into UPSERT styles statements as follows. Usually this works. I have validated syntax for correctness, have correct indexes, the correct columns are specified in conflict target etc. 

This app was running fine last few days. today it suddenly failed with error
FATAL Error: Failed to create checkpoint because of error: Operation requires a flat vector but a non-flat vector was encountered

```
INSERT INTO ... ON CONFLICT (keys) do update set ...
```

### To Reproduce

The program was ingesting from a high rate event stream events and consuming it into DuckDB. Ran for a few minutes and then suddenly crashed with this error.

I cannot provide the specific schema of the table and its contents but it is a table with 22 columns with mostly bigints and varchars.

The table only had 380 rows when it threw this error.

### OS:

x86

### DuckDB Version:

0.10.1

### DuckDB Client:

C++

### Full Name:

Ajay Gopalakrishnan

### Affiliation:

Meta

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by user8555** [comment]
I could not reproduce it again. Even if I can produce it, I may not be able to share the data with you for privacy reasons. How would you like to proceed?

As of now I have put a retry loop in the code if I see this INTERNAL error to see if a re-attempt fixes it after re-establishing a new connection. Would that be sufficient?

**Comment by user8555** [comment]
And btw - the exception type is not INTERNAL. It's FATAL = 30

**Comment by user8555** [comment]
Also, during this reproduction, this checkpoint operation returns 1.5 seconds or so on my machine, and during that time all read queries are blocked. Should that be expected?

**Comment by szarnyasg** [comment]
Hi @user8555, it's expected that reads are blocked during checkpoints. Regarding the reproducer:

> Try doing that insert or replace with a statement that is 1MB long (a large batch of rows being inserted all at once)
> And do this in a loop.

Could you please compile a Python script/C++ program that performs these steps? If that's available, we can then take a look and fix the issue.

**Comment by user8555** [comment]
Ok. Will work on a C++/Py program for it.

If I increase the wal_autocheckpoint config value to say 10GB does it make reads any slower than compared to default of 16MN?

**Comment by Tishj** [comment]
> Also, during this reproduction, this checkpoint operation returns 1.5 seconds or so on my machine, and during that time all read queries are blocked. Should that be expected?

Mytherin on discord:
> Writes don't block reads, but checkpointing blocks all concurrent access to the database. Perhaps that's happening in this instance?

**Comment by user8555** [comment]
Looks like the bug is caused only when the original database size is 70GB+ and then you are upserting a lot of data.
How do I transfer all of this to you?

I have a standalone cpp file that I can share which mimics my setup and can share the CSV files as well, but I will need to recreate the 70GB worth of data in a form that reproduces the bug.

Can you please not do a theoretical analysis of the bug given that we know that checkpointing is when this happens? and we know the error message as well?

**Comment by user8555** [comment]
s3://bugreportuser855/s417_duckdb.db.zip
s3://bugreportuser855/cmds_single.sql

This the simplest repro. This was producing the checkpoint error for 1 or 2 times and then changed to producing Segment not found error. I believe they are both related.

**Comment by user8555** [comment]
@Mytherin  

I got eager and just pulled your patch and tried it directly after applying on top of 0.10.1 ... 
I'm aware there is a big difference between 0.10.1 and master so I'm missing a lot of updates but wanted to give it a shot.

I think the fix partially worked. It got past that error looks like ... I don't see those checksum errors anymore.

However, it did throw a Null Pointer Error on column_data.cpp:155 in here

```
        if (SCAN_COMMITTED) {
            updates->FetchCommitted(vector_index, result);
```
updates was nullptr.

Just passing along this info to you in case it helps in fixes. It is also possible this is a redherring since I just picked your specific 2 commits and ignore all other changes on top of 0.10.1

```
    @ 000000000a21e247 duckdb::unique_ptr<duckdb::UpdateSegment, std::default_delete<duckdb::UpdateSegment>, true>::operator->() const                                                       source/duckdb/common/unique_ptr.hpp:24
    @ 000000000a21e5f1 unsigned long duckdb::ColumnData::ScanVector<true, true>(duckdb::TransactionData, unsigned long, duckdb::ColumnScanState&, duckdb::Vector&)
                       ./duck/0.10.1/src/storage/table/column_data.cpp:155                                                                           @ 000000000a21b2d0 duckdb::ColumnData::ScanCommitted(unsigned long, duckdb::ColumnScanState&, duckdb::Vector&, bool)                                                                     ./duck/0.10.1/src/storage/table/column_data.cpp:178                                                                           @ 000000000a268571 duckdb::StandardColumnData::ScanCommitted(unsigned long, duckdb::ColumnScanState&, duckdb::Vector&, bool)                                                             ./duck/0.10.1/src/storage/table/standard_column_data.cpp:77
    @ 000000000a252f44 void duckdb::RowGroup::TemplatedScan<(duckdb::TableScanType)1>(duckdb::TransactionData, duckdb::CollectionScanState&, duckdb::DataChunk&)
                       ./duck/0.10.1/src/storage/table/row_group.cpp:494                                                                             @ 000000000a25008f duckdb::RowGroup::ScanCommitted(duckdb::CollectionScanState&, duckdb::DataChunk&, duckdb::TableScanType)
                       ./duck/0.10.1/src/storage/table/row_group.cpp:593
    @ 000000000a2681ed duckdb::CollectionScanState::ScanCommitted(duckdb::DataChunk&, duckdb::TableScanType)                                                                                 ./duck/0.10.1/src/storage/table/scan_state.cpp:128
    @ 000000000a16c24d duckdb::DataTable::ScanTableSegment(unsigned long, unsigned long, std::function<void (duckdb::DataChunk&)> const&)
                       ./duck/0.10.1/src/storage/data_table.cpp:789
    @ 000000000a16ccf7 duckdb::DataTable::RevertAppend(unsigned long, unsigned long)
                       ./duck/0.10.1/src/storage/data_table.cpp:856
    @ 000000000a297ef7 duckdb::UndoBuffer::RevertCommit(duckdb::UndoBuffer::IteratorState&, unsigned long)
                       ./duck/0.10.1/src/transaction/undo_buffer.cpp:166
    @ 000000000a292c2e duckdb::DuckTransaction::Commit(duckdb::AttachedDatabase&, unsigned long, bool)
                       ./duck/0.10.1/src/transaction/duck_transaction.cpp:147
    @ 000000000a293179 duckdb::DuckTransactionManager::CommitTransaction(duckdb::ClientContext&, duckdb::Transaction&)
                       ./duck/0.10.1/src/transaction/duck_transaction_manager.cpp:202
    @ 000000000a296191 duckdb::MetaTransaction::Commit()
                       ./duck/0.10.1/src/transaction/meta_transaction.cpp:98
    @ 000000000a2971ac duckdb::TransactionContext::Commit()
                       ./duck/0.10.1/src/transaction/transaction_context.cpp:46
    @ 0000000009e95ecf duckdb::ClientContext::EndQueryInternal(duckdb::ClientContextLock&, bool, bool)
                       ./duck/0.10.1/src/main/client_context.cpp:226
    @ 0000000009e954 duckdb::ClientContext::CleanupInternal(duckdb::ClientContextLock&, duckdb::BaseQueryResult*, bool)                                                                    ./duck/0.10.1/src/main/client_context.cpp:261
    @ 0000000009e96aa1 duckdb::ClientContext::FetchResultInternal(duckdb::ClientContextLock&, duckdb::PendingQueryResult&)
                       ./duck/0.10.1/src/main/client_context.cpp:292
    @ 0000000009eed106 duckdb::PendingQueryResult::ExecuteInternal(duckdb::ClientContextLock&)
                       ./duck/0.10.1/src/main/pending_query_result.cpp:79
    @ 0000000009e9f946 duckdb::ClientContext::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
                       ./duck/0.10.1/src/main/client_context.cpp:1012
    @ 0000000009ead1d6 duckdb::Connection::Query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
                       ./duck/0.10.1/src/main/connection.cpp:88
```

**Comment by user8555** [comment]
@Mytherin  I'm novice in your codebase, so take it with a grain of salt ...

in column_data.cpp

```
bool ColumnData::HasUpdates() const {
	lock_guard<mutex> update_guard(update_lock);
	return updates.get();
}
```

```
bool has_updates = HasUpdates();
```

and then few lines later ...


```
	if (has_updates) {
		lock_guard<mutex> update_guard(update_lock);
```

Since you are using locks, I presume there is concurrency involved here. Btw, my application just has 1 writer.

Isn't it possible that between the if (has_updates) being true and the lock being re-acquired the updates is set to null again? And so in line 155 if the updates is dereferenced it can be nullptr and throw a NPE error.
