### ISSUE TITLE
Passing parameters from Python

### ISSUE THREAD

**Issue by DiptenduIDEAS** [duckdb/duckdb#11554]
### What happens?

```
def save_df_as_table(df, tablename):
    connection.execute('CREATE TABLE ? AS SELECT * from df', tablename)

```
I get the following error

 `duckdb.duckdb.ParserException: Parser Error: syntax error at or near "?"`

### To Reproduce

Run the above code 

```
def save_df_as_table(df, tablename):
    connection.execute('CREATE TABLE ? AS SELECT * from df', tablename)

```

### OS:

Windows

### DuckDB Version:

duckdb==0.10.1

### DuckDB Client:

Python

### Full Name:

Diptendu Dutta

### Affiliation:

IDEAS TIH

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for the report

Prepared parameters extend to expressions, create table does not accept the name of the table as an expression, this is an expected limitation currently.

**Comment by DiptenduIDEAS** [comment]
Could this be considered as a feature request and the relevant tag added to
this issue?
