### ISSUE TITLE
Memory usage increases 100x when using row instead of column majorness in input

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11568]
### What happens?

Whether I feed 
```python
b1 = pd.DataFrame(b_array).stack().reset_index()
```
or 
```python
b2 = pd.DataFrame(b_array.T).stack().reset_index().iloc[:, [1, 0, 2]] 
```
into `duckdb` makes no semantic difference (the two dataframes have the same contents) but with the former, memory usage during execution of the query below is 70MB (most of it is likely just the new dataframe being created) while with with the the latter, the memory usage is 7GB.

### To Reproduce

```python
import duckdb
import pandas as pd
import numpy as np

n = 725
a_array = np.random.rand(n * n).reshape([n, n])
b_array = np.random.rand(n * n).reshape([n, n])
a = pd.DataFrame(a_array).stack().reset_index()
b1 = pd.DataFrame(b_array).stack().reset_index()
b2 = pd.DataFrame(b_array.T).stack().reset_index().iloc[:, [1, 0, 2]] 
def execute_query(b):
    return duckdb.query("""
        SELECT 
        a.key,
        b.key,
        sum(a.value * b.value)
        FROM a a(key, match, value)
        JOIN b b(key, match, value)
        ON a.match = b.match
        GROUP BY a.key, b.key
        """).df()
r1 = execute_query(b1)
r2 = execute_query(b2)
assert np.abs(r1.sort_values(['key', 'key_1']).values - r2.sort_values(['key', 'key_1']).values).sum() < 1e-6
```

PS: I found this in my quest of figuring out why queries that are essentially "matrix multiplication" are surprisingly slow in duckdb, see https://github.com/duckdb/duckdb/discussions/11563.

### OS:

Linux

### DuckDB Version:

0.10.2-dev311

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
@soerenwolfers if I understand this correctly, using `iloc` will swap the positions of the columns in the DataFrame.
You are aliasing the columns `b(key, match, value)`

Meaning `execute_query(b1)` and `execute_query(b2)` are not equivalent right?

**Comment by soerenwolfers** [comment]
The transpose `.T` on `b2` swaps the two axes of the matrix (i.e. swaps key and match in my notation). The `iloc[:, [1, 0,...` swaps them back. 

Combined, this is just an awkward trick to swap storage contiguousness in pandas.

**Comment by soerenwolfers** [comment]
Unfortunately, that's only true on my work computer. On the Ubuntu 20 laptop I reported this originally from, this still persist. SOme more information:

```
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2
python                : 3.12.2.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.0-113-generic
Version               : #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_GB.UTF-8
LOCALE                : en_GB.UTF-8
```

**Comment by soerenwolfers** [comment]
Not an issue there anymore either, on 1.1.3
