### ISSUE TITLE
DuckDB spill to disk takes longer time more than 20mins and keeps the machine resources occupied. Is there a way to cancel the duckdb operation

### ISSUE THREAD

**Issue by michaelkovatt** [duckdb/duckdb#11564]
### What happens?

**Summary**
For larger than memory operations duckdb operations results in spill to disk. However, it takes longer time to write to disk. Approximately more than >20 Mins for a join operation of 200M dataset with 2M lookup table on a Column having duplicates.

**Datasets Used and operation performed**
Data format: Parquet
200M Dataset 
2M Lookup table
Inner join on J_ID Columns. This column has duplicate records in the 200M Dataset.

**Machine Config**
CPU: 6
MEMORY: 30Gi

### To Reproduce

**Datasets Used and operation performed**
Data format: Parquet
200M Dataset 
2M Lookup table
Inner join on J_ID Columns. This column has duplicate records in the 200M Dataset.

**Machine Config**
CPU: 6
MEMORY: 30Gi 

**Sample Code - inner join between parquet files**
Please see the code that caused spill to disk.  

```
import duckdb 
import time
import pandas as pd
conn = duckdb.connect(":default:")
#conn = duckdb.connect("test.duckdb")
conn.execute("SET preserve_insertion_order = false;")
conn.execute("SET memory_limit = '29GB';")
conn.execute("SET max_memory = '29GB';")

totalstart = time.time()
df_join = conn.sql("""SELECT * from 
                   read_parquet("tbl_200rm.parquet") AS R1 
 INNER JOIN read_parquet("tbl_2mns.parquet") AS R2 
                   on R1.J_ID = R2.J_ID""")
df_result = conn.execute("select * from df_join LIMIT 200")
print(df_result.df())

totalendtime = time.time()
print(f'{totalendtime - totalstart} seconds taken to perform operation')
conn.close()
````

### OS:

Linux

### DuckDB Version:

0.10

### DuckDB Client:

Python

### Full Name:

Michael Lin Kovattuparambil Antony

### Affiliation:

EY

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
"Takes longer" _than_ what? Longer than you'd expect given that disks are 10 to 100 times slower than memory?

 Can you upload  `tbl_200rm.parquet` and `tbl_2mns.parquet` or recreate equivalent datasets in Python?

**Comment by szarnyasg** [comment]
Hi @michaelkovatt, thanks for opening this issue. As @soerenwolfers remarked, we need a reproducible example to further progress on this issue. This can be a synthetic data set created via DuckDB (with `range`, `generate_series`, etc.)

**Comment by michaelkovatt** [comment]
Hi @szarnyasg , @soerenwolfers. I will share you the sample datasets to replicate. However, what i am looking for is a way to cancel the duckdb operation. If any operations goes beyond a certain time i need to cancel the operation.
Ex. If a join takes more than 20 mins, cancel the duckdb operation.

Also noticed that sometimes spill to disk doesn't work as expected. For memory intensive operations, instead of spilling to disk, it throws an out of memory exception. The behavior is not consistent. refer: [https://github.com/duckdb/duckdb/issues/11334](url)

**Comment by michaelkovatt** [comment]
Hi @szarnyasg , @soerenwolfers , please find the sample code with synthetic data generation.   You can try to export to csv/parquet. If it doesnt cause a spill, could you please run on a lower machine config. Please guide on how to cancel a spill to disk operation/query that runs for a longer duration.
```
import duckdb 
import time
import pandas as pd
from duckdb import DuckDBPyRelation

totalstart = time.time()


duckdb.sql("SET preserve_insertion_order = false;  SET temp_directory = './temp';")

df_test = duckdb.sql("""SELECT ROW_NUMBER() OVER () AS rowid,  gs.value as J_Id,  'J_Name' || gs.value AS J_Name,
                   'A_Name' || gs.value AS A_Name, 'B_Name' || gs.value AS B_Name,'C_Name' || gs.value AS C_Name,
                   'D_Name' || gs.value AS D_Name, 'E_Name' || gs.value AS E_Name,'F_Name' || gs.value AS F_Name,
                   'G_Name' || gs.value AS G_Name, 'H_Name' || gs.value AS H_Name, 'I_Name' || gs.value AS I_Name,
                   'K_Name' || gs.value AS K_Name, 'L_Name' || gs.value AS L_Name, 'M_Name' || gs.value AS M_Name,
                   'AA_Name' || gs.value AS AA_Name, 'BB_Name' || gs.value AS BB_Name,'CC_Name' || gs.value AS CC_Name,
                   'DD_Name' || gs.value AS DD_Name, 'EE_Name' || gs.value AS EE_Name,'FF_Name' || gs.value AS FF_Name,
                   'GG_Name' || gs.value AS GG_Name, 'HH_Name' || gs.value AS HH_Name, 'II_Name' || gs.value AS II_Name,
                   'KK_Name' || gs.value AS KK_Name, 'LL_Name' || gs.value AS LL_Name, 'MM_Name' || gs.value AS MM_Name,
                     999999.99 AS 'Name_Total', '12-12-2024' as 'DateString',
                     199999.99 AS 'Name_Total1', '12-12-2024' as 'DateString1'
FROM generate_series(1, 20000) AS gs(value)
CROSS JOIN generate_series(1, 20000) AS duplicates(id)""")


df_testlookup = duckdb.sql("""SELECT
  i AS J_Id,
  'J_Name' || i AS J_Name,
                               'A_Name' || i AS A_Name, 'B_Name' || i AS B_Name,'C_Name' || i AS C_Name,
                   'D_Name' || i AS D_Name, 'E_Name' || i AS E_Name,'F_Name' || i AS F_Name,
                   'G_Name' || i AS G_Name, 'H_Name' || i AS H_Name, 'I_Name' || i AS I_Name,
                   'K_Name' || i AS K_Name, 'L_Name' || i AS L_Name, 'M_Name' || i AS M_Name,
                   'AA_Name' || i AS AA_Name, 'BB_Name' || i AS BB_Name,'CC_Name' || i AS CC_Name,
                   'DD_Name' || i AS DD_Name, 'EE_Name' || i AS EE_Name,'FF_Name' || i AS FF_Name,
                   'GG_Name' || i AS GG_Name, 'HH_Name' || i AS HH_Name, 'II_Name' || i AS II_Name,
                   'KK_Name' || i AS KK_Name, 'LL_Name' || i AS LL_Name, 'MM_Name' || i AS MM_Name
FROM generate_series(1, 20000) AS t(i)""")



duckdb.sql("""
        create view vw_result as select * from df_test d inner join df_testlookup dl on d.J_Id = dl.J_Id;
    """)


duckdb.sql("""
        COPY vw_result TO 'final_par.parquet';
    """)


totalendtime = time.time()
print(f'{totalendtime - totalstart} seconds taken to perform operation')


```

**Comment by soerenwolfers** [comment]
To cancel a duckdb operation, you can send KeyboardInterrupts. Depending on your use case you can either do that by hand, or from a calling process, or by wrapping the duckdb operation in a thread. Afaik there is no duckdb specific support for cancelling operations (e.g. a timeout parameter).
