### ISSUE TITLE
TRUNCATE <TABLE > Uses excessive amount of RAM

### ISSUE THREAD

**Issue by an0sv** [duckdb/duckdb#11571]
### What happens?

I have a table with quite a lot of rows, 1.2 billon and when performing a "truncate <table>" duckdb seems to do a lot of processing and consumes a lot of memory ~25GB. To me this seems to be a bug or at least a very undesirable behavior as this operation should actually be very simple for the DB engine to handle and should not consume memory to this degree.

### To Reproduce

Just create a table with a  few columns and a billion rows, using generate_series() and perform a truncate on the table. The table I created had 4 int64 columns and 2 varchar columns

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

duckdb shell/cli

### Full Name:

Anders Svensson

### Affiliation:

Agama

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Truncate gets turned into DELETE FROM <table> I believe

The reason this is taking so much resources is probably because of the overhead of making this transactionally safe if I would have to guess

**Comment by szarnyasg** [comment]
Hi @an0sv, unfortunately, this issues is not reproducible. Please provide a reproducible script (SQL/Python) and data set (if applicable).

As @Tishj explained, `TRUNCATE <table>` is indeed equivalent to `DELETE FROM <table>` without a filtering condition, see https://duckdb.org/docs/sql/statements/delete.

**Comment by an0sv** [comment]
create table test(st int64, et int64, uaid int64, did int64, stype varchar, aid varchar);
insert into test values (1711020766,1711022403,5817020420761251821, 4072841771867899197,'abrVod','12 Angry Men');
insert into test select st, et, uaid+gs.i, did+gs.i,stype, aid  from test cross join generate_series(1,100000) as gs(i);
insert into test select st, et, uaid+gs.i, did+gs.i,stype, aid  from test cross join generate_series(1,10000) as gs(i);

Then do a "truncate test"

Watch the duckdb process memory usage. For me it uses 15GB+ RES RAM  and 40GB VIRT
