### ISSUE TITLE
duckdb "crashes" when unnest(), COUNT, UNION ALL and OFFSET are used together

### ISSUE THREAD

**Issue by smilingthax** [duckdb/duckdb#11578]
### What happens?

duckdb-wasm "crashes" with one of these:
```
Out of bounds call_indirect (evaluating 's(...o)')
call_indirect to a null table entry (evaluating 's(...o)')
Out of bounds memory access (evaluating 's(...o)')
```

With native (amd64) cli I see:
```
INTERNAL Error: Attempted to access index 1 within vector of size 1
-- and for further queries:
FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Attempted to access index 1 within vector of size 1"
```

### To Reproduce

shell.duckdb.org:
```sql
SELECT unnest([{name: 'No', count: COUNT(*)}], recursive:= true) UNION ALL SELECT unnest([{name: 'No', count:COUNT(*) }], recursive:=true) OFFSET 0;
```
```text
Out of bounds call_indirect (evaluating 's(...o)')
```

```sql
SELECT unnest({name: 'No', count: COUNT(*)}) UNION ALL SELECT unnest([{name: 'No', count:COUNT(*) }], recursive:=true) offset 0;
```
```text
call_indirect to a null table entry (evaluating 's(...o)')
```

```sql
SELECT unnest({name: 'No', count: COUNT(*)}) UNION ALL SELECT unnest({name: 'No', count:COUNT(*) }) OFFSET 0;
```
```text
Out of bounds memory access (evaluating 's(...o)')
```

x86_64 cli (error seems to be the same in all cases):
```sql
SELECT unnest([{name: 'No', count: COUNT(*)}], recursive:= true) UNION ALL SELECT unnest([{name: 'No', count:COUNT(*) }], recursive:=true) OFFSET 0;
```
```text
INTERNAL Error: Attempted to access index 1 within vector of size 1
```

### OS:

wasm, x86_64

### DuckDB Version:

Wasm: v0.10.1 Package: @duckdb/duckdb-wasm@1.28.1-dev178.0 (current shell.duckdb.org); x86_64: nightly: v0.10.2-dev504 2e6f74803b

### DuckDB Client:

shell / cli

### Full Name:

Tobias Hoffmann

### Affiliation:

cueconcept

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! I bumped into this myself recently - I've pushed a fix for this issue (and a number of others) in https://github.com/duckdb/duckdb/pull/11580.
