### ISSUE TITLE
read_csv does not automatically detect dates in format '%b %-d, %Y'.

### ISSUE THREAD

**Issue by derekmahar** [duckdb/duckdb#11583]
### What happens?

Function [`read_csv`](https://duckdb.org/docs/data/csv/overview.html#csv-functions) does not automatically detect and convert date strings that follow the format "%b %-d, %Y" unless you specify parameter `columns` with data type `DATE` for date string columns.  (Note that according to the documentation for the `read_csv` [parameters](https://duckdb.org/docs/data/csv/overview.html#parameters), parameter `columns` should actually disable automatic type detection.)  Function [`strptime`](https://duckdb.org/docs/sql/functions/timestamp#strptimetext-format) correctly converts date strings in this format.

### To Reproduce

Run script `example_read_csv_dates` in [example_read_csv_dates.tar.gz](https://github.com/duckdb/duckdb/files/14922697/example_read_csv_dates.tar.gz):

```
$ cat ./example_read_csv_dates
#!/usr/bin/env bash

cat << DATES > dates.csv
Date
"Dec 8, 2022"
"Sep 26, 2022"
"Aug 31, 2022"
"Aug 14, 2022"
"May 16, 2022"
"Apr 28, 2022"
"Apr 14, 2022"
"Jan 10, 2022"
DATES

trap "rm dates.csv" EXIT

duckdb <<- SQL
SELECT Date
FROM read_csv(
  'dates.csv',
  dateformat = '%b %-d, %Y'
);
SQL

duckdb <<- SQL
SELECT Date
FROM read_csv(
  'dates.csv',
  columns = {'Date': 'DATE'},
  dateformat = '%b %-d, %Y'
);
SQL

duckdb <<- SQL
SELECT strptime(Date, '%b %-d, %Y')::DATE AS Date
FROM read_csv(
  'dates.csv',
  all_varchar = TRUE
);
SQL

```
Output:
```
$ ./example_read_csv_dates
┌──────────────┐
│     Date     │
│   varchar    │
├──────────────┤
│ Dec 8, 2022  │
│ Sep 26, 2022 │
│ Aug 31, 2022 │
│ Aug 14, 2022 │
│ May 16, 2022 │
│ Apr 28, 2022 │
│ Apr 14, 2022 │
│ Jan 10, 2022 │
└──────────────┘
┌────────────┐
│    Date    │
│    date    │
├────────────┤
│ 2022-12-08 │
│ 2022-09-26 │
│ 2022-08-31 │
│ 2022-08-14 │
│ 2022-05-16 │
│ 2022-04-28 │
│ 2022-04-14 │
│ 2022-01-10 │
└────────────┘
┌────────────┐
│    Date    │
│    date    │
├────────────┤
│ 2022-12-08 │
│ 2022-09-26 │
│ 2022-08-31 │
│ 2022-08-14 │
│ 2022-05-16 │
│ 2022-04-28 │
│ 2022-04-14 │
│ 2022-01-10 │
└────────────┘
```

### OS:

Ubuntu 22.04.4 LTS

### DuckDB Version:

v0.10.2-dev504 2e6f74803b

### DuckDB Client:

CLI

### Full Name:

Derek Mahar

### Affiliation:

Self-employed

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by dmcmurchy** [comment]
I also ran into this with `read_csv` and the `%B %-d, %Y` dateformat pattern with version 1.0.0. `strptime` does the conversion correctly.

**Comment by derekmahar** [comment]
I confirm that DuckDB v1.0.1-dev4803 c84676023c fixes this issue:

```
derek@ubuntu-server-1:~/projects/read_csv$ ./example_read_csv_dates
┌────────────┐
│    Date    │
│    date    │
├────────────┤
│ 2022-12-08 │
│ 2022-09-26 │
│ 2022-08-31 │
│ 2022-08-14 │
│ 2022-05-16 │
│ 2022-04-28 │
│ 2022-04-14 │
│ 2022-01-10 │
└────────────┘
┌────────────┐
│    Date    │
│    date    │
├────────────┤
│ 2022-12-08 │
│ 2022-09-26 │
│ 2022-08-31 │
│ 2022-08-14 │
│ 2022-05-16 │
│ 2022-04-28 │
│ 2022-04-14 │
│ 2022-01-10 │
└────────────┘
┌────────────┐
│    Date    │
│    date    │
├────────────┤
│ 2022-12-08 │
│ 2022-09-26 │
│ 2022-08-31 │
│ 2022-08-14 │
│ 2022-05-16 │
│ 2022-04-28 │
│ 2022-04-14 │
│ 2022-01-10 │
└────────────┘
derek@ubuntu-server-1:~/projects/read_csv$ duckdb --version
v1.0.1-dev4803 c84676023c
```

**Comment by derekmahar** [comment]
I created project [duckdb_read_csv_dates](https://github.com/derekmahar/duckdb_read_csv_dates) to host the test examples that demonstrated this issue.
