### ISSUE TITLE
Slow performance when simulating matrix multiplication in SQL

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11588]
### What happens?

Duckdb is, I believe, unreasonably slow on queries of the form

```sql
SELECT 
    t1.key AS key1,
    t2.key AS key2,
    <aggregate>(<function>(t1.value, t2.value))
FROM t1 t1(key, match, value)
JOIN t2 t2(key, match, value)
ON t1.match = t2.match
GROUP BY key1, key2
```

I previously started a discussion/asked for help about the specific example of matrix multiplication at https://github.com/duckdb/duckdb/discussions/11563 

However, since queries of this form are quite generic, and I now have evidence that even a few lines of Python can outperform duckdb by a factor 550x (see second benchmark below) I think now  that this may warrant an issue. 

I am aware that a general purpose descriptive tool like duckdb/SQL is never going to be as fast as fine-tuned imperative code. However: the numba examples below are not fine-tuned (on my side, obviously they are by the numba developers) and I got the same numbers for some shoddy C# that took 20 minutes to write and didn't use anything outside the `System` namespace. I'm not writing to complain about duckdb, I'm just feeling there might be something that's going wrong here.

---
#### (2000 x 2000) x (2000 x 2000) matrix multiplication (aggregate=`sum`, function=`x * y`):

|  Tool  |        Time |         Speedup |
|---:|---------:|----------:|
|  Duckdb | 22.96s | 1|
|  numba | 7.88s| 2.91x |
|  numba2 | 0.31s| 74x |
|  BLAS | 0.036s| 638x |

I implemented the query above using numba. I was careful to write "sparse" code that isn't aware the matrices at hand are actually dense, but rather just operates on "long" tables of `(rowIdx: int, columnIdx: int, value: float)` schema.

For comparison, I also included a BLAS matrix gemm, which of course is unfair but gives a reference frame.

#### (1000 x 1000) x (1000 x 1000) matrix multiplication, with reshuffled rows 

|  Tool  |        Time |         Speedup |
|---:|---------:|----------:|
|  Duckdb | 24.22s | 1|
|  numba | 1.02s| 23.7x |
|  numba2 | 0.04s| 550x |
|  BLAS | - | - |

Adds 
```python
long_1 = long_1.sample(frac=1, ignore_index=True)
long_2 = long_2.sample(frac=1, ignore_index=True)
```

Note that the numba methods don't slow down at all but duckdb becomes 8x slower (relative to the expected n^3 scaling).

#### (2000 x 2000) x (2000 x 2000) `max(abs(t1.value - t2.value))` contraction  (aggregate=`max`, function=`abs(x - y)`)

|  Tool  |        Time |         Speedup |
|---:|---------:|----------:|
|  duckdb | 25.79s | 1|
|  numba | 8.46s | 3x |
|  numba2 | 0.56s | 46x |
|  BLAS | - | - |

I reused the same code, only swapping out the obvious inner aggregation logic in duckdb and numba.

### To Reproduce

```python
import duckdb
import pandas as pd
import numpy as np
from collections import defaultdict
import itertools
from numba.typed import Dict
import numba
from numba import prange
import timeit
from typing import Tuple, List

class Timer:
    def __init__(self, name):
        self.name = name
    def __enter__(self):
        self.t1 = timeit.default_timer()
    def __exit__(self, *args, **kwargs):
        t2 = timeit.default_timer()
        print(f"{self.name} took {t2 - self.t1}s")

def create_matrix(n:int) -> pd.DataFrame:
    return pd.DataFrame(np.random.rand(n * n).reshape([n, n]))

def wide_to_long(m: pd.DataFrame, names: List[str]) -> pd.DataFrame:
    return m.stack().reset_index().rename(columns=dict(zip(['level_0', 'level_1', 0], names)))

def long_to_list(df: pd.DataFrame) -> List[Tuple[int, int, float]]:
    return duckdb.query("""SELECT * FROM df""").fetchall()

def columns_to_df(groups_array: "array[(int, int)]", values_array: "array[float]") -> pd.DataFrame:
    res = [(gg[0], gg[1], rr) for (gg, rr) in zip(groups_array, values_array)]
    return pd.DataFrame(res, columns=['key1', 'key2', 'agg'])

n = 1000
wide_1 = create_matrix(n)
long_1 = wide_to_long(wide_1, ['key', 'match', 'value'])
wide_2 = create_matrix(n)
long_2 = wide_to_long(wide_2, ['key', 'match', 'value'])
long_1 = long_1.sample(frac=1, ignore_index=True)
long_2 = long_2.sample(frac=1, ignore_index=True)

with Timer("pandas"):
    res_pandas = wide_1 @ wide_2.T
result_pandas = wide_to_long(res_pandas, ['key1', 'key2', 'agg'])

with Timer("duckdb"):
    result_duckdb = duckdb.query("""
    SELECT 
        long_1.key AS key1,
        long_2.key AS key2,
        sum(long_1.value * long_2.value) AS agg
    FROM long_1
    JOIN long_2
    ON long_1.match = long_2.match
    GROUP BY key1, key2
    """).df()

def to_hashed(long_list: List[Tuple[int, int, float]]) -> Dict[int, Dict[int, float]]:
    res = defaultdict(lambda: Dict())
    for x in long_list:
        res[x[0]][x[1]] = x[2]
    return Dict(res.items())
hashed_1, hashed_2 = to_hashed(long_to_list(long_1)), to_hashed(long_to_list(long_2))

@numba.njit(parallel=True)
def agg(hashed_1: Dict[int, Dict[int, float]], hashed_2: Dict[int, Dict[int, float]]):
    groups_array = np.array([(key1, key2) for key1 in hashed_1 for key2 in hashed_2])
    results_array  = np.zeros(len(groups_array))
    for i in prange(len(groups_array)):
        key_1, key_2 = groups_array[i]
        data1 = hashed_1[key_1]
        data2 = hashed_2[key_2]
        result = 0
        for (match1, value1) in data1.items():
            result += value1 * data2.get(match1, 0)
        results_array[i] = result
    return (groups_array, results_array)

agg(hashed_1, hashed_2) # compile
with Timer("numba"):
    res_numba = agg(hashed_1, hashed_2)
result_numba = columns_to_df(*res_numba)

def to_hashed_arrays(hashed: Dict[int, Dict[int, float]], all_match: List[int]) -> Dict[int, np.ndarray]:
    hashed_arrays = dict()
    for x, y in hashed.items():
        out = np.zeros(len(all_match))
        for i in range(len(all_match)):
            out[i] = y.get(all_match[i], 0)
        hashed_arrays[x] = out
    return Dict(hashed_arrays.items())

all_match: List[int] = list(set([x[1] for x in long_to_list(long_1)] + [x[1] for x in long_to_list(long_2)]))
hashed_arrays_1, hashed_arrays_2 = to_hashed_arrays(hashed_1, all_match), to_hashed_arrays(hashed_2, all_match) 

@numba.njit(parallel=True, fastmath=True)
def agg_fast(ha1: Dict[int, Dict[int, float]], ha2: Dict[int, Dict[int, float]]) -> Tuple[np.ndarray, np.ndarray]:
    groups_array = np.array([(key1, key2) for key1 in ha1 for key2 in ha2])
    results_array  = np.zeros(len(groups_array))
    for i in prange(len(groups_array)):
        key_1, key_2 = groups_array[i]
        data1 = ha1[key_1]
        data2 = ha2[key_2]
        result = 0
        for j in range(len(data1)):
            result += data1[j] * data2[j]
        results_array[i] = result
    return (groups_array, results_array)

agg_fast(hashed_arrays_1, hashed_arrays_2) # compile
with Timer("numba_fast"):
    res_numba_fast = agg_fast(hashed_arrays_1, hashed_arrays_2)
result_numba_fast = columns_to_df(*res_numba_fast)

def max_diff(df1, df2):
    return np.max(df1.sort_values(['key1', 'key2'])['agg'].values - df2.sort_values(['key1', 'key2'])['agg'].values)
results = [result_pandas, result_duckdb, result_numba, result_numba_fast]
assert max([max_diff(x, y) for x in results for y in results]) < 1e-6
```

PS1: I might not have been completely fair in deciding what does or does not go into the respective timers, but since most of the time of each method is spent in the aggregations, I think this doesn't matter (and doing some of the required transformations for the numba methods in numba is annoying, so I'd rather not and leave them out of the timing. You be the judge)

PS2: I've removed a polars comparison because even though polars is up to 3x faster for smaller matrices, it breaks completely for larger matrices. For reference:

```python
long_1_pl = pl.from_pandas(long_1)
long_2_pl = pl.from_pandas(long_2)
with Timer("polars"):
    res_polars = (
        long_1_pl.lazy()
        .join(long_2_pl.lazy(), on="match")
        .group_by(["key", "key_right"])
        .agg(
            (pl.col("value") * pl.col("value_right")).sum().alias("agg")
        )
        .select([pl.col("key").alias("key1"), pl.col("key_right").alias("key2"), "agg"])
        .collect()
    )
result_polars = res_polars.to_pandas()
```

PS3: reference, this is duckdb's `EXPLAIN ANALYZE` output:
```
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
 EXPLAIN ANALYZE SELECT  long_1.key AS key1, long_2.key AS key2, sum(long_1.value * long_2.value) AS agg FROM long_1 JOIN long_2 ON long_1.match = long_2.match GROUP BY key1, key2 
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 22.68s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐                             
│      RESULT_COLLECTOR     │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│             0             │                             
│          (0.00s)          │                             
└─────────────┬─────────────┘                                                          
┌─────────────┴─────────────┐                             
│      EXPLAIN_ANALYZE      │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│             0             │                             
│          (0.00s)          │                             
└─────────────┬─────────────┘                                                          
┌─────────────┴─────────────┐                             
│       HASH_GROUP_BY       │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│             #0            │                             
│             #1            │                             
│          sum(#2)          │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│          4000000          │                             
│         (272.11s)         │                             
└─────────────┬─────────────┘                                                          
┌─────────────┴─────────────┐                             
│         PROJECTION        │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│            key1           │                             
│            key2           │                             
│      (value * value)      │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│         8000000000        │                             
│          (34.48s)         │                             
└─────────────┬─────────────┘                                                          
┌─────────────┴─────────────┐                             
│         HASH_JOIN         │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│           INNER           │                             
│       match = match       │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ├──────────────┐              
│        EC: 4000000        │              │              
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │              │              
│         8000000000        │              │              
│         (184.37s)         │              │              
└─────────────┬─────────────┘              │                                           
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│        PANDAS_SCAN        ││        PANDAS_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           match           ││           match           │
│            key            ││            key            │
│           value           ││           value           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        EC: 4000000        ││        EC: 4000000        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          4000000          ││          4000000          │
│          (0.02s)          ││          (0.02s)          │
└───────────────────────────┘└───────────────────────────┘ 
```

### OS:

Linux

### DuckDB Version:

v0.10.2-dev311

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I suspect that these numbers are heavily influenced by using non-native data sources, if these are turned into duckdb tables beforehand I expect the execution time to go down a lot

**Comment by Mytherin** [comment]
Thanks for the report. Looking at the queries here - it seems that you are simulating matrix multiplication in SQL by turning every single (value, value) combination into a separate row using an exploding join - and then comparing it against an implementation that does not do any such materialization, but instead just does a simple multiplication for every combination of values. As you might imagine, a single multiplication is much cheaper than doing a dance of `joining rows -> materializing an exponential amount of rows -> aggregating + grouping that same very large amount of rows`.

This is not a very useful performance comparison because the implementations are doing completely different things. *Given the dataset that you have provided* (a matrix) the SQL query computes the same result as the matrix multiplication program - but that is not true in the general case. The Python scripts are not doing joins or aggregations, and cannot compute the same results that the SQL query can given different data sets. 

It would be more interesting to see how the SQL query executed in DuckDB stacks up to the SQL query executed in other systems. If there are still such drastic performance differences, then it might be worth investigating. I don't doubt there might be some performance left on the table for exploding joins - since exploding joins in general are not very commonly used in regular SQL this is not something that has been optimized as much as other operators.

Fundamentally there is not a good way of doing matrix multiplication in SQL, since matrix multiplication heavily relies on *positional* semantics of values (i.e. being able to look-up a single value based on its [x, y] position). As relational algebra/SQL operates on bag semantics, that positional aspect of values does not exist. The only way to efficiently implement this would be to either provide a dedicated matrix multiplication operator, or to somehow further expose information about positional semantics that could be somehow utilized during query processing. We might at some point do the former or an extension might come along to do the former (or, if you are interested, you could develop an extension yourself - see [the extension template](https://github.com/duckdb/extension-template)).

**Comment by soerenwolfers** [comment]
@Tishj 

Prepending (outside the timer)
```sql
CREATE OR REPLACE TABLE long_native_1 AS (FROM long_1);
CREATE OR REPLACE TABLE long_native_2 AS (FROM long_2);
```
brings the 1000 x 1000 shuffled-rows example from 24.22s to 20.7s (I verified by afterwards zeroing out `long_1` that it does do this eagerly. Let me know if there is something else.

Prepending (outside the timer)
```sql
CREATE OR REPLACE TABLE long_native_1 AS (SELECT key, match, random() AS value FROM range(2000) k(key) CROSS JOIN range(2000) m(match) );
CREATE OR REPLACE TABLE long_native_2 AS (SELECT key, match, random() AS value FROM range(2000) k(key) CROSS JOIN range(2000) m(match) );
```

brings the 2000 x 2000 plain matrix multiplication example from 22.96s to 27.93s (not sure whether shuffled or not is the fair comparison, but since duckdb doesn't let me do any _less_ shuffling, I think it's fair to compare to the non-shuffled version)

**Comment by soerenwolfers** [comment]
@Mytherin 

(1) I didn't realize the O(n^3) combinations are actually being materialized.

(2) I'm not sure what you mean by "The Python scripts are not doing joins or aggregations, and cannot compute the same results that the SQL query can given different data sets." It was my understanding that they do (morally):

They first figure out what the resulting groups in the group by are going to be by computing the cartesian product of the unique values of key1 and key2. Then, you are right, rather than materializing all rows in the exploding join, they collect values that can contribute to each groups (in dictionaries in the first script; in arrays padded to the number of unique values of the "match" column in the second script). Finally they aggregate by aligning the "match" column in a loop (via dictionary lookup in the first, and via padded-array-iteration in the second).

If I provide an example where I randomly delete rows from the two long tables that go into the computation and the Python scripts still return the same result as the duckdb, would that change your opinion that "and cannot compute the same results that the SQL query can given different data sets."?

**Comment by Mytherin** [comment]
> (1) I didn't realize the O(n^3) combinations are actually being materialized. (n=8000 does prove that.)

They are not being materialized at the same time, but rather in a streaming fashion. Nevertheless at some point they are created in memory which is why this takes so long. The system performs a join *followed by* an aggregation, and the join results in `n^3` rows. 

> They first figure out what the resulting groups in the GROUP BY are going to be by computing the cartesian product of the unique values of key1 and key2. Then, you are right, rather than materializing all rows in the exploding join, they collect values that can contribute to each groups (in dictionaries in the first script; in arrays padded to the number of unique values of the match columns in the second script). Finally they aggregate by aligning the match column in a loop (via dictionary lookup in the first, and via padded-array-iteration in the second).

> In particular, I didn't rely on positional semantics (and I thought the shuffled-rows example was fair evidence of that, but I might be unaware or gloss over a million other details that apply here from the view of a database).

That's fair - I was looking mostly at the BLAS inclusion and considering how matrix multiplication works in general. Still the scripts are not actually doing a join followed by an aggregate but rather doing the aggregate and the join as a single operation. First iterating over all of the keys for both tables - computing the unique set of keys - and only then doing the join. I agree that in queries of exactly this format that is sufficient to compute the answer regardless of data set, although I wonder how efficient this will be in the case where the join is not an exploding join but a regular key-key join or in cases where there are many more groups.

In a general purpose query engine you do not have this level of knowledge about the data set and problem you are completing. The numba scripts use the fact that you know the amount of groups is small (1000 x 1000), and are built for the fact that there are many join matches and hence avoid the materialization but do a pre-grouping instead. They are not suitable to answer arbitrary joins or arbitrary aggregations but are essentially custom-built to solve this specific instance of this specific problem. 

Now it *might* be worthwhile to implement such a join + aggregate operator that does all of this in one pass as well, but that is only worthwhile if the operation itself is common. We cannot implement every single algorithm to solve every single query for every data set optimally - so trade-offs must be made. Exploding joins are very uncommon, and even in this case, you don't actually want to run this query - you want to perform a matrix multiplication - so time would be better spend implementing a matrix multiplication operator. 

> (4) I'll run this in clickhouse tonight.

Running the query in ClickHouse over Parquet files gets me a timing of 12.8s, versus a timing of 14.0s in DuckDB on my laptop.

**Comment by soerenwolfers** [comment]
> They are not being materialized at the same time, but rather in a streaming fashion

My memory usage did grow by a factor 55 when u switched from 2000^3 to 800^3.

Regardless: I do realize that not every arbitrary combination of joins and aggregates can have an optimal implementation in a general purpose system; however: do the numba scripts really rely on the number of groups being small? My understanding was that they'd work equally fine for (20k x 100) x (100 x 20k) multiplication; since they have memory consumption O(original matrix sizes). I agree they are less likely to be materially faster the thinner the match dimensions get, but I think they'll still be always faster, so I was hoping any potential rewrite could be kept relatively general. 

Anyway, I get that there is a complexity tradeoff that's yours to make. 

Just wanted to make a final advertisement for my use case, regarding 

> you don't actually want to run this query - you want to perform a matrix multiplication

I'm working with time series a lot, and I'm writing a lot of throw away code where most of my time is spent pulling days from different sources, duckt (ho ho) taping it together in duckdb, running some quick analysis, and moving on. Duckdb is great because it allows me to do everything in one place.  The alternative to the query above, which typically computes a correlation matrix (between a filtered and windowed etc. subset of the time series in my data set) is to (1) do the gathering, filtering and windowing, in duckdb (2) convert to pandas (3) do a `.unstack` to convert long to wide format (4) fill missing cells with zeroes) (5) do the matrix multiplication (6) convert back and join back with original data in SQL, hoping I didn't accidentally reorder things or forget to add the right ids along the way. It's doable, but it's an O(1) contributor to total wall clock time. The cost of leaving duckdb is much higher than advantage from getting the extreme speeds of BLAS.

**Comment by Mytherin** [comment]
> Regardless: I do realize that not every arbitrary combination of joins and aggregates can have an optimal implementation in a general purpose system; however: do the numba scripts really rely on the number of groups being small? My understanding was that they'd work equally fine for (20k x 100) x (100 x 20k) multiplication; since they have memory consumption O(original matrix sizes). I agree they are less likely to be materially faster the thinner the match dimensions get, but I think they'll still be always faster, so I was hoping any potential rewrite could be kept relatively general.

If I change the data set size to have more unique matches (i.e. so it is more similar to a key-key join) in this manner:

```py
long_1['match'] = long_1['key'] *  long_1['match']
long_2['match'] = long_2['key'] *  long_2['match']
```

I get the following timings:

```py
pandas took 0.016310665989294648s
duckdb took 0.3918338749790564s
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
numba took 2.7297689170227386s
numba_fast took 29.00743291695835s
[1000000 rows x 3 columns]
Traceback (most recent call last):
  File "/Users/myth/Programs/duckdb/test.py", line 121, in <module>
    assert max([max_diff(x, y) for x in results for y in results]) < 1e-6
AssertionError
```

So it is definitely not always faster. For more regular (non-exploding) joins DuckDB's implementation seems to be a lot faster.

> I'm working with time series a lot, and I'm writing a lot of throw away code where most of my time is spent pulling days from different sources, duckt (ho ho) taping it together in duckdb, running some quick analysis, and moving on. Duckdb is great because it allows me to do everything in one place. The alternative to the query above, which typically computes a correlation matrix (between a filtered and windowed etc. subset of the time series in my data set) is to (1) do the gathering, filtering and windowing, in duckdb (2) convert to pandas (3) do a .unstack to convert long to wide format (4) fill missing cells with zeroes) (5) do the matrix multiplication (6) convert back and join back with original data in SQL, hoping I didn't accidentally reorder things or forget to add the right ids along the way. It's doable, but it's an O(1) contributor to total wall clock time. The cost of leaving duckdb is much higher than advantage from getting the extreme speeds of BLAS.

That's fair - and I can definitely see us providing a matrix multiplication operator, either through an extension or natively in the future.

**Comment by soerenwolfers** [comment]
Cool. By the way, the cost of moving outside and back into duckdb becomes even higher if I'm doing "one matrix multiplication per another join/group key"; especially if the matrix multiplications are of different sizes then. Looking forward to potential improvements in the future.
