### ISSUE TITLE
Ungraceful Handling of Apache Arrow `ArrowNotImplementedError` with `timestamp` Datatype

### ISSUE THREAD

**Issue by elsell** [duckdb/duckdb#11608]
### What happens?

Executing a query against an Apache Arrow table from LanceDB that includes a column of datatype `timestamp[ns]`:
- FAILS if the query contains a `WHERE` clause;
- SUCCEEDS if the query does _not_ contain a `WHERE` clause.

Specifically, this behavior seems to be present when creating a LanceDB table from a `pandas.DataFrame`.

## Minimum Reproducible Example

```python
import lancedb
import duckdb
import pandas as pd

# Connect to a fresh database
db = lancedb.connect("./test_db")

# Create a LanceDB table (uses Apache Arrow)
data = pd.DataFrame({
    "corpus": ["day", "night"],
    "date": [pd.Timestamp(1708951076175900000, unit="ns")] * 2
})
table = db.create_table('test-table', data=data, exist_ok=True, mode="overwrite")

print("✨ Table Schema:\n", table.schema, "\n\n")

# Convert the "Table" to a "dataset" which is an Apache Arrow
dataset = table.to_lance() # type: ignore (it works :shrug:)

# Succeeds
print("✅ ", duckdb.execute('SELECT * FROM dataset').arrow(), "\n\n")

args = {"corpus": "day"}

# Fails
print(duckdb.execute('SELECT * FROM dataset WHERE corpus LIKE $corpus', args).arrow())
```

## Output:
```bash
✨ Table Schema:
corpus: string
date: timestamp[ns] 


✅  pyarrow.Table
corpus: string
date: timestamp[ns]
----
corpus: [["day","night"]]
date: [[2024-02-26 12:37:56.175900000,2024-02-26 12:37:56.175900000]] 


Traceback (most recent call last):
  File "<redacted>", line 39, in <module>
    test()
  File "<redacted>", line 34, in test
    print(duckdb.execute('SELECT * FROM dataset WHERE corpus LIKE $corpus', args).arrow())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Invalid Error: ArrowNotImplementedError: conversion to substrait::Type from timestamp[ns]

At:
  pyarrow/error.pxi(91): pyarrow.lib.check_status
  ```

> [!Important]
> It turns out that if you replace the `data` variable with a list of dicts instead of a DataFrame, there are no errors. Curious!
> ```python
>data = [
>    {"corpus": "day", "date": pd.Timestamp(1708951076175900000, unit="ns")},
>    {"corpus": "night", "date": pd.Timestamp(1708951076175900000, unit="ns")},
>]
>```

### OS:

Linux (Ubuntu x64)

### DuckDB Version:

0.10.1

### DuckDB Client:

Python (Python 3.11)

### Full Name:

John

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hey thanks for raising the issue, did you also raise a corresponding issue on Arrow?
As I mentioned this is caused by pushdown of the filter into Arrow, they are causing this error

All we can do is handle the error more gracefully :)

**Comment by Tishj** [comment]
That likely doesn't get pushed down, so yes, please make an issue in Arrow 👍
