### ISSUE TITLE
Builtins least() and greatest() do not respect order of ENUM values

### ISSUE THREAD

**Issue by Teggy** [duckdb/duckdb#11606]
### What happens?

The order of values in an `enum` type is specified by their order in the type's definition.  The evaluation of `least()` and `greatest()` does not respect this order.

### To Reproduce

```sql
CREATE TYPE t AS ENUM ('z','y','x');  -- 'z' is least, 'x' is greatest value of t

.columns
SELECT greatest('x'::t, 'z'::t), 'x'::t > 'z'::t;
```
```text
┌──────────────────────────────────────────┬─────────┬─────────┐
│                  Column                  │  Type   │  Row 1  │
├──────────────────────────────────────────┼─────────┼─────────┤
│ greatest(CAST('x' AS t), CAST('z' AS t)) │ varchar │       z │ -- oops, should be 'x'
│ (CAST('x' AS t) > CAST('z' AS t))        │ boolean │    true │ -- OK!
└──────────────────────────────────────────┴─────────┴─────────┘
```

The evaluation of `greatest()` and `least()` unexpectedly appears to follow the regular `varchar` order.

P.S.: The result type of `greatest(e₁::t, e₂::t)` should be `t` (not `varchar`).

### OS:

macOS (arm64)

### DuckDB Version:

v0.10.2-dev717 529abad2ee

### DuckDB Client:

CLI

### Full Name:

Torsten Grust

### Affiliation:

U Tübingen, Germany

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @Teggy, thanks for the report. This indeed contradicts the documentation's [Comparison of Enums](https://duckdb.org/docs/sql/data_types/enum#comparison-of-enums) section. We'll take a look.

**Comment by Teggy** [comment]
Dear all, is this issue dormant now?

**Comment by szarnyasg** [comment]
Hi @Teggy sorry for the radio silence – we discussed this internally. Currently, this is expected behaviour as we want enums and varchar columns to behave identically so that we can emit them and have enums "pretend" to be varchars. This needs to be documented (and that documentation then needs to be kept in sync with the changes in the system later).

**Comment by Teggy** [comment]
Uh oh... very disappointed to hear this.  I truly hope that this is going to be reconsidered.  

That `enum` values are declared in the form of `varchar` values is a technicality (of SQL syntax) and should definitely not lead to confusion with textual values.  Avoidance of such confusion _is_ the purpose of any type system.  You are promoting DuckDB to be _strongly typed database system_ (first sentence on https://duckdb.org/docs/api/c/types.html). This resolution of the issue renders that statement questionable, I'd say.  

(Sorry for the negativity.  Keep up the good work, friends.)

**Comment by Mytherin** [comment]
Thanks for reporting! I've pushed a PR that fixes this here - https://github.com/duckdb/duckdb/pull/13019

**Comment by Teggy** [comment]
Wonderful! Thank you, @Mytherin!
