### ISSUE TITLE
Calculating the absolute value of a REAL type results in a higher precision number than argument.

### ISSUE THREAD

**Issue by richtia** [duckdb/duckdb#11624]
### What happens?

Calculating the absolute value of a REAL type results in a higher precision number.

### To Reproduce

```
import duckdb
conn = duckdb.connect()
conn.execute("SELECT abs(2.55::REAL);").fetchone()[0]
2.549999952316284
```

### OS:

macOS

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Richard Tia

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by richtia** [comment]
Another observation

```
>>> conn.execute("SELECT abs(2.55::FLOAT8);").fetchone()[0]
2.55
>>> conn.execute("SELECT abs(2.55::FLOAT4);").fetchone()[0]
2.549999952316284
```

**Comment by soerenwolfers** [comment]
I'd guess you get the same answer without the `abs`, i.e. with just `2.55::REAL`.

If so, then what you're seeing is just the fact that not all decimals can be represented exactly in all binary floating point formats, see https://duckdb.org/docs/sql/data_types/numeric.html#floating-point-types and the links there.

**Comment by soerenwolfers** [comment]
To lessen the load on the maintainers, you can close issues yourself if you're satisfied they're resolved.
