### ISSUE TITLE
Issue with where condition on  COLUMNS Expression

### ISSUE THREAD

**Issue by erwanj** [duckdb/duckdb#11620]
### What happens?

I would like to filter a table with a columns expression in where clause to get all records where at least one field is not null.
I describe below what I get and what I expect to get.

### To Reproduce

```
CREATE TABLE test AS 
SELECT * FROM (VALUES ('aa', 'aa'), ('aa', null), (null, null)) test(aa, bb);
```

1. condition "where columns(*) is null" working

```
select COLUMNS(*) from test
where columns(*) is null
```
result : 
```
aa|bb|
--+--+
  |  |
```

2. condition "where not(columns(*) is null)" not working as expected

```
select COLUMNS(*) from test
where not(columns(*) is null)
```
result : 
```
aa|bb|
--+--+
aa|aa|
```
expected result : 
```
aa|bb|
--+--+
aa|aa|
aa|  |
```

### OS:

x64

### DuckDB Version:

10.1

### DuckDB Client:

dbeaver

### Full Name:

Erwan

### Affiliation:

home

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I don't think that's how COLUMNS(*) works, as it expands to multiple expressions

I have worked on a variation of COLUMNS that will instead unpack the * in place, so we can do this:
```sql
select COLUMNS(*) from test where COALESCE(*COLUMNS(*)) is not null
```
Which does result in:
```
aa	aa
aa	NULL
```

<https://github.com/Tishj/duckdb/pull/111>
I'm not entirely sure when we'll get around to making a PR out of it, as it is technically a feature

**Comment by soerenwolfers** [comment]
I'm surprised `WHERE not(columns(*) is null)` even works, given that `not(columns(*) is null)` expand to two separate columns and in general `WHERE column1, column2` does not work. Personally, I think it shouldn't work.

**Comment by Tishj** [comment]
It `AND`s the expressions I believe

**Comment by Mytherin** [comment]
`COLUMNS(*)` in the `WHERE` clause unifies the generated conditions using `AND`, as such this is not a bug but expected behavior. `WHERE NOT(COLUMNS(*) IS NULL)` selects all rows for which **all** values are not null, which is what we see happening here.
