### ISSUE TITLE
DuckDB CSV reader unable to handle `DECIMAL` types through `auto_type_candidates`

### ISSUE THREAD

**Issue by d33bs** [duckdb/duckdb#11639]
### What happens?

Thanks for the great work on DuckDB! I noticed that the CSV reader option for `auto_type_candidates` is unable to handle `DECIMAL` types making large number reads from CSV challenging. The alternative here seems to be to read the large number as a `VARCHAR` then convert to a `DECIMAL` but this may be unfavorable due to the amount of memory required for a `VARCHAR` vs the `DECIMAL` version of the values. If it's not possible to use the `DECIMAL` type through the CSV reader `auto_type_candidates` options, I recommend updating documentation to reflect this for users.

Please don't hesitate to let me know if you have any questions or if I may further clarify.

### To Reproduce

See here for a [Google Colab notebook](https://colab.research.google.com/drive/112x55m_YOfid3_Lt8SBdnbShCmoTl76l) with an exploration of this (and a [gist backup](https://gist.github.com/d33bs/bf6e71c381e1d8bcc50c4c69e500caf8)).

More directly, see the following for a quick example:

```python
import duckdb

# write a one column, one value csv with the floating point number
with open(file="example.csv", mode="w", encoding="utf-8") as file:
  file.write("col_a\n")
  file.write("3.5215257120407011")

# try to use a simpler name for decimal type
import duckdb

with duckdb.connect() as ddb:
  result = ddb.execute("""
  SELECT *
  FROM read_csv('example.csv');
  """).arrow()

print(result)

with duckdb.connect() as ddb:
  result = ddb.execute("""
  SELECT *
  FROM read_csv('example.csv' auto_type_candidates=['SQLNULL', 'BOOLEAN', 'BIGINT', 'DECIMAL', 'DOUBLE', 'TIME', 'DATE', 'TIMESTAMP', 'VARCHAR']);
  """).arrow()

print(result)
```

### OS:

Linux x86_64

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

David Bunten

### Affiliation:

University of Colorado Anschutz Medical Campus

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @d33bs thanks for opening the issue :-)

I've pushed a PR to allow for Decimal Types to be used in the `auto_type_candidates` option.

It's important to notice that DuckDB doesn't do decimal precision sniffing, so you will have to add those manually, and only one will be accepted auto_type_candidates.

**Comment by d33bs** [comment]
Thank you so much @pdet for quickly addressing this!
