### ISSUE TITLE
memory issue happened while merging two tables inside duckdb EVEN THOUGH we have enough space in the system

### ISSUE THREAD

**Issue by RVaidhy** [duckdb/duckdb#11632]
### What happens?

we are trying to perform join on two tables using duckdb.
We were able to create index on those tables but while performing the join it stopped in the middle of the process.

After indexing the file (file.db) size became 18 GB. During join process it created 150GB of file.db content and failed after that. 
We have enough space but it failed with the following error.

duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 2097152 bytes

We are prcocessing this file in a 8vcpu core and 32G ec2 with 500GB space in that directory. 
I have attached the screenshot for your reference. 

Please help. What else should be done in order to get this processed like introducing threads etc. please suggest us.

Thanks,
Vaidhy R
<img width="696" alt="Screenshot 2024-04-12 at 8 06 54 PM" src="https://github.com/duckdb/duckdb/assets/141009243/b4264f80-6fbe-4bfa-85fc-aaa501d8f298">
<img width="911" alt="Screenshot 2024-04-12 at 8 06 46 PM" src="https://github.com/duckdb/duckdb/assets/141009243/e3fe262a-b8ec-49d9-87a9-a330e25d7b6f">

it created a file for   

### To Reproduce

We have a custom data that we have exetracted from our servers.

But the snippet that we used is as follows.

```py
con = duckdb.connect("db/file.db")

con.sql("create table files_usercomp_master_tbl as \
SELECT comp.blob_sha256, comp.component_idcomponents, comp.pkg_type, \
f.id, comp.created, comp.package, comp.top_severity, comp.mds_updated, \
f.path, f.name , f.modified, f.parent_sha256, f.user_component_tbl_id \
FROM files f  \
LEFT OUTER JOIN comp_usercomp as comp \
ON f.sha256 = comp.blob_sha256")
time.sleep(2)
count_master_files_usercomp=con.sql("select count(*) from files_usercomp_master_tbl")
time.sleep(2)
print("table files_usercomp_master_tbl count :- "+str(count_master_files_usercomp))
```

Error:

```
Traceback (most recent call last):
  File "/apps/opt/emr_workspace/duckdb_deltalake_testing.py", line 143, in <module>
    con.sql("create table files_usercomp_master_tbl as \
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 2097152 bytes
```

System space details.

```
Filesystem                Type      Size  Used Avail Use% Mounted on
devtmpfs                  devtmpfs   31G     0   31G   0% /dev
tmpfs                     tmpfs      31G   84K   31G   1% /dev/shm
tmpfs                     tmpfs      31G   17M   31G   1% /run
tmpfs                     tmpfs      31G     0   31G   0% /sys/fs/cgroup
/dev/mapper/vgroot-lvroot xfs       105G  6.2G   99G   6% /
/dev/mapper/vgroot-lvtmp  xfs       212G   19G  194G   9% /tmp
/dev/mapper/vgroot-lvhome xfs        26G  220M   26G   1% /home
/dev/mapper/vgroot-lvapps xfs       505G  148G  358G  30% /apps
/dev/nvme0n1p1            xfs      1014M  454M  561M  45% /boot
/dev/mapper/vgroot-lvvar  xfs        30G  962M   29G   4% /var
tmpfs                     tmpfs     6.2G     0  6.2G   0% /run/user/810
tmpfs                     tmpfs     6.2G     0  6.2G   0% /run/user/2589981
```

### OS:

Linux RHEL 13

### DuckDB Version:

0.10.0

### DuckDB Client:

Python3

### Full Name:

Vaidyanathan R

### Affiliation:

Verizon

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting - could you try to make a reproducible example that includes the data set?
