### ISSUE TITLE
Regression with inferring data type of partitions

### ISSUE THREAD

**Issue by liquidcarbon** [duckdb/duckdb#11636]
### What happens?

There's data in Hive-style partitioned folders:
```
.
├── partition=123
│   └── table.csv
└── partition=abc
    └── table.csv
```

Upgrading to from DuckDB 0.9 to 0.10 breaks queries against these tables that were previously working.

0.10 brought all kinds of other issues due to stricter typing, but this one is giving me more trouble than any others.

In retrospect, I shouldn't have allowed numeric partitions, but for the time being I'm stuck with this.  I have an option to rename the numeric folders but this would be painful to work around this with incoming data.

### To Reproduce

```bash
mkdir -p /tmp/ddb && cd /tmp/ddb
for partition in 123 abc; do mkdir "partition=$partition" && echo "a,b" > "partition=$partition/table.csv" && echo "1,2" >> "partition=$partition/table.csv"; done
```

```sql
SELECT COUNT(*) FROM '/tmp/ddb/*/table.csv'
/* returns 2 as expected */
```

```sql
SELECT * FROM '/tmp/ddb/*/table.csv'
/* InvalidInputException: Invalid Input Error: Unable to cast 'abc' (from hive partition column 'PARTITION') to: 'BIGINT' */
```

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

any

### Full Name:

Alex

### Affiliation:

self

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by liquidcarbon** [comment]
Hack: place a folder named `partition=!` that would come in natural sorting before `partition=123`.  Then it works.
```for partition in "!" 123 abc; do mkdir -p "partition=$partition" && echo "a,b" > "partition=$partition/table.csv" && echo "1,2" >> "partition=$partition/table.csv"; done```

**Comment by Mytherin** [comment]
Thanks for reporting! I can reproduce the issue.
