### ISSUE TITLE
Window functions: syntax error using `exclude` inside `over`

### ISSUE THREAD

**Issue by Bilbottom** [duckdb/duckdb#11647]
### What happens?

Using the `exclude` keyword inside an `over` clause generates the following error and stops the query from producing an output:

> Parser Error: syntax error at or near "exclude"

### To Reproduce

Here's an MWE (no data required):

```sql
select count(*) over (
    order by 1
    rows between unbounded preceding
             and unbounded following
         exclude current row
)
from (values (1), (2), (3))
```

The result set should be:

| count(*) |
|---------:|
|        2 |
|        2 |
|        2 |

This works on SQLite, and I think the syntax is correct for DuckDB too according to the window function docs:

- https://duckdb.org/docs/sql/window_functions.html#syntax
- https://duckdb.org/docs/sql/window_functions.html#exclude-clause

---

Tested locally (_Windows 10 x64_ and _macOS Sonoma_) and on MotherDuck, all for DuckDB version 0.9.2

### OS:

MotherDuck

### DuckDB Version:

0.9.2

### DuckDB Client:

MotherDuck

### Full Name:

Bill Wallis

### Affiliation:

Sainsbury's PLC

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by cmdlineluser** [comment]
If it helps:

The docs default to the latest stable release:

<blockquote>

<img width="576" alt="Screen Shot 2024-04-14 at 11 16 15" src="https://github.com/duckdb/duckdb/assets/99486669/e53905b1-a6fb-42f6-9368-8baad1a43866">

</blockquote>

`WINDOW EXCLUDE` was only added in 0.10.0

- https://duckdb.org/2024/02/13/announcing-duckdb-0100#new-features

```sql
┌──────────────────────────────────────────────────────────────────────────────┐
│ count() OVER (ORDER BY 1 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FO…  │
│                                    int64                                     │
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                            2 │
│                                                                            2 │
│                                                                            2 │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Bilbottom** [comment]
> * https://duckdb.org/2024/02/13/announcing-duckdb-0100#new-features

Ah the 0.9 docs have `exclude` in [the syntax diagram](https://duckdb.org/docs/archive/0.9/sql/window_functions#syntax), so I didn't think to check the release notes for 0.10 😅 In that case, happy to close this -- thank you 🤓
