### ISSUE TITLE
Can't `printf` any currency/amount with Thousand-separator and Digits like '999,990.00'

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11657]
### What happens?

`Printf` allows Thousand-separator only for integers, but not for floats.
So how exactly am I supposed to pretty-print any kind of currency amounts? Something like `TO_CHAR(amount, '999,990.00')` or the normal C/printf `"%,.2f"`?

### To Reproduce

```sql

-- Invalid Input Error: Thousand separators are not supported for floating point numbers
select printf('%0,10.3f', DECIMAL(15,2) '20202023.15252');
```

### OS:

Linux

### DuckDB Version:

0.10.1

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by manticore-projects** [comment]
I know this looks more like a feature request, but for any kind of reporting this is an essential feature.

**Comment by Mytherin** [comment]
Implemented in https://github.com/duckdb/duckdb/pull/12717

**Comment by manticore-projects** [comment]
Thank you big time!
