### ISSUE TITLE
Pivot Operation Fails with Case-Sensitive column values

### ISSUE THREAD

**Issue by rajvindrasingh** [duckdb/duckdb#11669]
### What happens?

Running the given query causes

```text
Binder Error: table "__unnamed_pivot" has duplicate column name "Test"
```

### To Reproduce

```sql
CREATE TABLE Cities (Name VARCHAR, id INTEGER);
INSERT INTO Cities VALUES ('Test', 1);
INSERT INTO Cities VALUES ('test',2);
INSERT INTO Cities VALUES ('random3',3);
INSERT INTO Cities VALUES ('random4',4);
INSERT INTO Cities VALUES ('random5',5);
INSERT INTO Cities VALUES ('random6',6);
INSERT INTO Cities VALUES ('random7',7);
INSERT INTO Cities VALUES ('random8',8);
INSERT INTO Cities VALUES ('random9',9);
INSERT INTO Cities VALUES ('random10',10);
INSERT INTO Cities VALUES ('random11',11);
INSERT INTO Cities VALUES ('random12',12);
INSERT INTO Cities VALUES ('random13',13);
INSERT INTO Cities VALUES ('random14',14);
INSERT INTO Cities VALUES ('random15',15);
INSERT INTO Cities VALUES ('random16',16);
INSERT INTO Cities VALUES ('random17',17);
INSERT INTO Cities VALUES ('random18',18);
INSERT INTO Cities VALUES ('random19',19);
INSERT INTO Cities VALUES ('random20',20);
FROM Cities
PIVOT (
    array_agg(id)
    FOR
        name IN ('test','Test','random3','random4','random5','random6','random7','random8','random9','random10'
        ,'random11'
        )
);
```

### OS:

windows

### DuckDB Version:

0.10.1

### DuckDB Client:

node v16

### Full Name:

Rajvindra Singh

### Affiliation:

Paxcom India Pvt Limited 

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in https://github.com/duckdb/duckdb/pull/11678

**Comment by rajvindrasingh** [comment]
The above query after PR merge returns 'Test_1' instead of 'Test'
