### ISSUE TITLE
`read_json_auto` requires higher memory limit than it uses

### ISSUE THREAD

**Issue by cfahlgren1** [duckdb/duckdb#11684]
### What happens?

It seems that the DuckDB `memory_limit` and the actual memory required isn't 1:1. 

## Issue

With a **315 MB** JSON file with a DuckDB memory limit of `3GB`, the reproduction script runs and the memory profiler shows it uses a max memory ~414 MB.

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    17     57.2 MiB     57.2 MiB           1   @profile
    18                                         def run():
    19    414.4 MiB    357.2 MiB           2       duckdb_conn.execute(
    20     57.2 MiB      0.0 MiB           1           f"CREATE TABLE output AS SELECT * FROM read_json_auto(['output.json'], format=auto, maximum_object_size=536870912.0)"
    21                                             )
```

**However**, with a memory_limit of `2GB` it fails:

```
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: failed to allocate data of size 1.0 GiB (1.0 GiB/1.8 GiB used)
```

Curious if I am missing anything to why there seems to be a need for >2GB memory limit when it only uses ~414 MB. I had another different example where it only worked with memory limit of > 12.7GB, but only used 1GB.  

### To Reproduce

# Generate JSON
Here's a script to generate the `output.json` used in the reproduction.

```python
import json
import random
import string


def random_string(length):
    return "".join(random.choices(string.ascii_letters + string.digits, k=length))


def generate_data(num_records):
    data = []
    for _ in range(num_records):
        row = {
            "column1": {
                "nested1": [
                    {
                        "field1": random_string(10),
                        "field2": random_string(20),
                        "field3": random_string(30),
                        "field4": random_string(40),
                        "field5": random_string(50),
                    }
                    for _ in range(random.randint(1, 5))
                ]
            },
            "column2": {
                "nested2": [
                    {
                        "field6": random_string(15),
                        "field7": random_string(25),
                        "field8": random_string(35),
                        "field9": random_string(45),
                    }
                    for _ in range(random.randint(1, 3))
                ]
            },
            "column3": {
                "nested3": [
                    {
                        "field10": random_string(20),
                        "field11": random_string(30),
                        "field12": random_string(40),
                        "field13": random_string(4000),
                        "field14": random_string(60),
                    }
                    for _ in range(random.randint(1, 4))
                ]
            },
        }
        data.append(row)
    return data


def main():
    num_records = 30000
    data = generate_data(num_records)
    with open("output.json", "w") as file:
        json.dump(data, file)


if __name__ == "__main__":
    main()
```
# Benchmark

```python
from memory_profiler import profile
import duckdb

DUCKDB_MEMORY_LIMIT = "3GB"
DUCKDB_WORKER_THREADS = 1

duckdb_conn = duckdb.connect(
    database=":memory:",
    config={
        "memory_limit": DUCKDB_MEMORY_LIMIT,
        "worker_threads": DUCKDB_WORKER_THREADS,
    },
)


@profile
def run():
    duckdb_conn.execute(
        f"CREATE TABLE output AS SELECT * FROM read_json_auto(['output.json'], format=auto, maximum_object_size=536870912.0)"
    )

run()
```

### OS:

Mac M1 Pro arm64

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Caleb Fahlgren

### Affiliation:

Shipt

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I assume the profiler is incorrect, but to verify this, try setting the thread limit to 1 (`pragma threads=1`) and try the experiments again, I assume the memory limit can be much lower without erroring in that case.

**Comment by cfahlgren1** [comment]
> I assume the profiler is incorrect, but to verify this, try setting the thread limit to 1 (`pragma threads=1`) and try the experiments again.

Wouldn't that accomplish the same as the 
```python
DUCKDB_WORKER_THREADS = 1
```
in the reproduction script?

I tried with a 

```python
duckdb_conn.execute("SET THREADS=1;")
```

I am seeing the same results. I am also checking with [asitop](https://github.com/tlkh/asitop) on the OS level to view memory limit when I run it and am seeing about `380.3 MiB` to match.

**Comment by cfahlgren1** [comment]
Using DuckDB CLI with the default memory limit of `12.7GB` and `10` threads doesn't seem to be using a ton of memory for the file, but inside a server it seems to be trying to need more than 26GB of memory even though it works fine on a 16 GB Mac M1. The example above is the closest example I could find to replicate the behavior. 

Might have to do with having a few nested columns 🤔

**Comment by Mytherin** [comment]
MacOS has compressed memory which is why the physical memory usage might be different than the memory usage reported by DuckDB. DuckDB's memory limit and memory usage is measured in uncompressed memory usage.

**Comment by cfahlgren1** [comment]
> MacOS has compressed memory which is why the physical memory usage might be different than the memory usage reported by DuckDB. DuckDB's memory limit and memory usage is measured in uncompressed memory usage.

Thanks for your response and help. Good to know. 

Are there any methods / tricks to be able to load / query JSON without so much memory? 

For ex:
- loading json from pandas and querying the resulting dataframe
- providing json structure so it doesn't need to infer etc

**Comment by Mytherin** [comment]
I would recommend using [ndjson](https://jsonlines.org/) as your json format - that should be more (memory) efficient

**Comment by MotazBellah** [comment]
I am also facing the same problem. Does anyone knows how to resolve this ?
