### ISSUE TITLE
Bump the DuckDB.jl version

### ISSUE THREAD

**Issue by mzy2240** [duckdb/duckdb#11698]
### What happens?

DuckDB_jll is already update, could you please also bump the DuckDB.jl version? Thanks!

### To Reproduce

DuckDB.jl is still 0.10.1

### OS:

x86

### DuckDB Version:

0.10.2

### DuckDB Client:

Julia

### Full Name:

Zeyu Mao

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by Mytherin** [comment]
It has been updated - https://juliahub.com/ui/Packages/General/DuckDB/
