### ISSUE TITLE
`read_parquet('s3://...', union_by_name=True)` throws "Connection error for HTTP HEAD" but `union_by_name=False` does not

### ISSUE THREAD

**Issue by rajivpatki** [duckdb/duckdb#11695]
### What happens?

Executing a query using duckdb's read_parquet with wildcard paths to read several thousand parquet files in a heavily partitioned dataset:
```
SELECT * FROM
read_parquet('s3://path_here/*/*/*/*.parquet', union_by_name=True')
```

throws `IOError: Connection error for HTTP HEAD to <http file path of one particular file>`. The issue shows the same file each time in the error and the issue goes away if `union_by_name=True` is not passed. Note that `SELECT * FROM read_parquet('s3://path_to_file_mentioned_in_the_error', union_by_name = True)` works fine with no errors.

In an earlier instance of this same issue with a different dataset, there wasn't a fixed file that was mentioned in the error but it used to be different files each time with no perceivable pattern. The problem was resolved by changing the partitioning so that there were fewer files.

### To Reproduce

The dataset on s3 contains several thousand parquet files partitioned by 4 columns. Some files happen to be very small and may contain 10-50 rows

### OS:

x86

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Rajiv Patki

### Affiliation:

Jodaro

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @rajivpatki thanks for reporting this. Did you try the workaround suggested in https://github.com/duckdb/duckdb/issues/10047#issuecomment-1875127995?

**Comment by rajivpatki** [comment]
> Hi @rajivpatki thanks for reporting this. Did you try the workaround suggested in [#10047 (comment)](https://github.com/duckdb/duckdb/issues/10047#issuecomment-1875127995)?

`SET http_keep_alive=false;`

This worked! Thank you

**Comment by chlimaferreira** [comment]
For those using MinIO in Docker, use port 9000:9000 instead of 9000:9001.

docker run -p 9000:9000 -p 9090:9090 --name minio_name -e "MINIO_ROOT_USER=minio" -e "MINIO_ROOT_PASSWORD=minio123" -v ${HOME}/minio/data:/data quay.io/minio/minio server /data --console-address ":9090"

In my case it worked.
