### ISSUE TITLE
append_data_chunk not returning DuckDBError for malformed chunk

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#11699]
### What happens?

According to [duckdb_append_data_chunk docs](https://duckdb.org/docs/api/c/api#duckdb_append_data_chunk)

> Appends a pre-filled data chunk to the specified appender.
> 
> The types of the data chunk must exactly match the types of the table, no casting is performed. **If the types do not match or the appender is in an invalid state, DuckDBError is returned.** If the append is successful, DuckDBSuccess is returned.

In my testing when the types don't match, I don't get `DuckDBError`. I either get success or an exception depending on the table definition.

### To Reproduce

```c
duckdb_database db;
duckdb_connection con;
duckdb_state state;
duckdb_result result;

duckdb_open(NULL, &db);
duckdb_connect(db, &con);

std::cout << duckdb_library_version();
state = duckdb_query(con, "CREATE TABLE AppenderWrongTypeTest(c Date, b Integer);", &result);

duckdb_appender appender;
duckdb_appender_create(con, NULL, "AppenderWrongTypeTest", &appender);

duckdb_logical_type types[2];

types[0] = duckdb_appender_column_type(appender, 0);
types[1] = duckdb_appender_column_type(appender, 1);

duckdb_data_chunk data_chunk = duckdb_create_data_chunk(types, 2);

duckdb_vector v0 = duckdb_data_chunk_get_vector(data_chunk, 0);
duckdb_vector v1 = duckdb_data_chunk_get_vector(data_chunk, 1);

auto d0 = (int32_t*)duckdb_vector_get_data(v0);
*d0 = 42;

auto d1 = (int32_t*)duckdb_vector_get_data(v1);
*d0 = 84;

duckdb_data_chunk_set_size(data_chunk, 1);

//I expected DuckDBError  but got success.
state = duckdb_append_data_chunk(appender, data_chunk);

duckdb_disconnect(&con);
duckdb_close(&db);
```

If I change table definition to `CREATE TABLE AppenderWrongTypeTest(c Date, b Varchar)` I get `Access violation`:

![image](https://github.com/duckdb/duckdb/assets/580749/66aede15-72fe-4fdd-8c38-fc8c62a5e92f)

### OS:

Windows 11 x64

### DuckDB Version:

0.10.2

### DuckDB Client:

C Api

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I'm confused, you create the DataChunk with types obtained from the Appender, so the types will always match in your example?

**Comment by Giorgi** [comment]
I create data chunk from the types right, but I cast the first vector data to `(int32_t*)` when the column is `Date`. I expected `duckdb_append_data_chunk` to return `DuckDBError` in such case.

**Comment by Tishj** [comment]
> The doc says: **If the types do not match or the appender is in an invalid state, DuckDBError is returned.**

That is talking about this:
```c++
	if (chunk_types != types) {
		for (idx_t i = 0; i < chunk.ColumnCount(); i++) {
			if (chunk.data[i].GetType() != types[i]) {
				throw InvalidInputException("Type mismatch in Append DataChunk and the types required for appender, "
				                            "expected %s but got %s for column %d",
				                            types[i].ToString(), chunk.data[i].GetType().ToString(), i + 1);
			}
		}
	}
```

**Comment by Giorgi** [comment]
Can the crash be avoided in case of string? If you add a check that the pointer is valid.

**Comment by Tishj** [comment]
> Can the crash be avoided in case of string? If you add a check that the pointer is valid.

In this case we really can't, the data is uninitialized so the pointer is "valid"
it's not NULL, it's just random.
There technically are *some* checks you can do to check if those values are valid, given that the valid address space leaves around 10~ bits unoccupied, but that would not catch all cases either.

So you would need to zero initialize everything to be able to do that, which comes with a cost
And on top of that you would need to check every pointer for NULL before accessing it, which also has a cost

**Comment by Mytherin** [comment]
As indicated by @Tishj this is really not avoidable. You cannot check if pointers are valid in C. Even if we could - we might not want to given that this is performance sensitive code. This is really a "use at your own risk" API - your code needs to make sure the DataChunk is filled in correctly.

**Comment by Giorgi** [comment]
I see. A note about it in the docs would be probably helpful.
