### ISSUE TITLE
Performance issues using LEFT JOIN 

### ISSUE THREAD

**Issue by ASaltedFishBoy** [duckdb/duckdb#11709]
### What happens?

I created a timestamp that (ordered timestamp,trace_id PRIMARY) table CAN_TEST_timestamp, and a main table CAN_TEST with a (ordered trace_id PRIMARY) that contains a number of columns. And the main table CAN_TEST indexes trace_id. In the following statement, I think the performance should be the same, because the data in the left table all meet the joint table condition, but there is a ten-fold performance difference.Both results are consistent.

### To Reproduce

```
0.485s
SELECT * FROM (SELECT * FROM (SELECT * FROM main.CAN_TEST_timestamp ORDER BY "timestamp" ) LIMIT 4000 OFFSET 8000000 )AS timeOrder **INNER** JOIN main.CAN_TEST ON main.CAN_TEST.trace_id == timeOrder.trace_id ORDER BY (timeOrder."timestamp",timeOrder.trace_id )
4s
SELECT * FROM (SELECT * FROM (SELECT * FROM main.CAN_TEST_timestamp ORDER BY "timestamp" ) LIMIT 4000 OFFSET 8000000 )AS timeOrder **LEFT** JOIN main.CAN_TEST ON main.CAN_TEST.trace_id == timeOrder.trace_id ORDER BY (timeOrder."timestamp",timeOrder.trace_id )
```

### OS:

x64

### DuckDB Version:

0.10.1

### DuckDB Client:

c++

### Full Name:

ASaltedFishBoy

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by soerenwolfers** [comment]
"To reproduce" means you are supposed to provide concrete code that reproduces the observed problem, at least on your hardware and software setup. In particular,  you have to add the definition and contents of the table in your snippet. Ideally, this would all happen in pure SQL without reference to external data. If you find it impossible to reproduce the problem in this way, you should upload the contents, e.g. as parquet file, and include the code that reads the parquet file.

**Comment by ASaltedFishBoy** [comment]
> "To reproduce" means you are supposed to provide concrete code that reproduces the observed problem, at least on your hardware and software setup. In particular, you have to add the definition and contents of the table in your snippet. If you find it impossible to reproduce the problem on a toy table with a few manually inserted values, you should upload the contents of your table, e.g. as parquet file, and include the code that reads the parquet file in your snippet.

This is my table construction statement,the part that does not contain data insertion of CAN_TEST.That's about all I have to offer.

```
CREATE SEQUENCE id_sequence START 1
CREATE TABLE CAN_TEST (trace_id BIGINT PRIMARY KEY DEFAULT nextval('id_sequence'),timestamp BIGINT, others...)
CREATE UNIQUE INDEX CAN_TEST_trace_id_IDX ON main.CAN_TEST  (trace_id)

CREATE TABLE CAN_TEST_timestamp (trace_id BIGINT PRIMARY KEY ,timestamp BIGINT)
INSERT INTO CAN_TEST_timestamp (SELECT trace_id,timestamp FROM main.CAN_TEST ORDER BY "timestamp")
```

Then there are the two statements in issue.

**Comment by soerenwolfers** [comment]
You could have turned this into a MWE like this:

```sql
CREATE OR REPLACE SEQUENCE id_sequence START 1;

CREATE OR REPLACE TABLE CAN_TEST (trace_id BIGINT PRIMARY KEY DEFAULT nextval('id_sequence'), timestamp BIGINT, other1 REAL, other2 TIMESTAMP);
CREATE UNIQUE INDEX CAN_TEST_trace_id_IDX ON main.CAN_TEST  (trace_id);

INSERT INTO CAN_TEST (SELECT 
    unnest(ARRAY(SELECT * FROM range(10_000_000))),
    unnest(ARRAY(SELECT random() * 100 FROM range(10_000_000))),
    unnest(ARRAY(SELECT random() FROM range(10_000_000))),
    unnest(ARRAY(SELECT '2020-01-01'::DATE + to_seconds(range) FROM range(10_000_000)))
);

CREATE OR REPLACE TABLE CAN_TEST_timestamp (trace_id BIGINT PRIMARY KEY, timestamp BIGINT);
INSERT INTO CAN_TEST_timestamp (SELECT trace_id,timestamp FROM main.CAN_TEST ORDER BY "timestamp");
```

```sql
SELECT * FROM (SELECT * FROM (SELECT * FROM main.CAN_TEST_timestamp ORDER BY "timestamp") LIMIT 4000 OFFSET 8000000) AS timeOrder INNER JOIN main.CAN_TEST ON main.CAN_TEST.trace_id == timeOrder.trace_id ORDER BY (timeOrder."timestamp",timeOrder.trace_id);
```
```
449 ms ± 18.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```sql
SELECT * FROM (SELECT * FROM (SELECT * FROM main.CAN_TEST_timestamp ORDER BY "timestamp") LIMIT 4000 OFFSET 8000000) AS timeOrder LEFT JOIN main.CAN_TEST ON main.CAN_TEST.trace_id == timeOrder.trace_id ORDER BY (timeOrder."timestamp",timeOrder.trace_id);
```
```
603 ms ± 32.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I do see a performance difference, but nowhere near the size you observe. Maybe it's the "other" columns? Maybe it's the number of rows? Maybe it's the datatypes of the other columns?

**Comment by ASaltedFishBoy** [comment]
> You could have turned this into a MWE like this:
> 
> ```sql
> CREATE OR REPLACE SEQUENCE id_sequence START 1;
> 
> CREATE OR REPLACE TABLE CAN_TEST (trace_id BIGINT PRIMARY KEY DEFAULT nextval('id_sequence'), timestamp BIGINT, other1 REAL, other2 TIMESTAMP);
> CREATE UNIQUE INDEX CAN_TEST_trace_id_IDX ON main.CAN_TEST  (trace_id);
> 
> INSERT INTO CAN_TEST (SELECT 
>     unnest(ARRAY(SELECT * FROM range(10_000_000))),
>     unnest(ARRAY(SELECT random() * 100 FROM range(10_000_000))),
>     unnest(ARRAY(SELECT random() FROM range(10_000_000))),
>     unnest(ARRAY(SELECT '2020-01-01'::DATE + to_seconds(range) FROM range(10_000_000)))
> );
> 
> CREATE OR REPLACE TABLE CAN_TEST_timestamp (trace_id BIGINT PRIMARY KEY, timestamp BIGINT);
> INSERT INTO CAN_TEST_timestamp (SELECT trace_id,timestamp FROM main.CAN_TEST ORDER BY "timestamp");
> ```
> 
> ```sql
> SELECT * FROM (SELECT * FROM (SELECT * FROM main.CAN_TEST_timestamp ORDER BY "timestamp") LIMIT 4000 OFFSET 8000000) AS timeOrder INNER JOIN main.CAN_TEST ON main.CAN_TEST.trace_id == timeOrder.trace_id ORDER BY (timeOrder."timestamp",timeOrder.trace_id);
> ```
> 
> ```
> 449 ms ± 18.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> ```
> 
> ```sql
> SELECT * FROM (SELECT * FROM (SELECT * FROM main.CAN_TEST_timestamp ORDER BY "timestamp") LIMIT 4000 OFFSET 8000000) AS timeOrder LEFT JOIN main.CAN_TEST ON main.CAN_TEST.trace_id == timeOrder.trace_id ORDER BY (timeOrder."timestamp",timeOrder.trace_id);
> ```
> 
> ```
> 603 ms ± 32.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> ```
> 
> I do see a performance difference, but nowhere near the size you observe. Maybe it's the "other" columns? Maybe it's the number of rows? Maybe it's the datatypes of the other columns?

There are roughly 30 columns of data here, of different types, but the data itself is not large (1 row of total bytes is roughly 200bytes), and the other differences seem to be absent
