### ISSUE TITLE
Builds on Alpine linux are failing

### ISSUE THREAD

**Issue by timfi** [duckdb/duckdb#11703]
### What happens?

PR #11663 introduced a [magical line](https://github.com/duckdb/duckdb/blob/v0.10.2/src/common/local_file_system.cpp#L43) that fixes builds on some linux setups but apparently it breaks builds on alpine linux (at least in Docker).

### To Reproduce

**Broken:**
```Dockerfile
FROM alpine:latest AS duckdb-build

ARG DUCKDB_REPO https://github.com/duckdb/duckdb.git
ARG DUCKDB_VERSION v0.10.2

RUN apk add git
RUN git clone \
  --depth 1 \
  --branch "${DUCKDB_VERSION}" \
  "${DUCKDB_REPO}" \
  /duckdb
WORKDIR /duckdb

RUN apk add \
  build-base \
  cmake \
  ninja \
  python3

RUN GEN=ninja make clean release
```

**"Fixed":**
```Dockerfile
FROM alpine:latest AS duckdb-build

ARG DUCKDB_REPO https://github.com/duckdb/duckdb.git
ARG DUCKDB_VERSION v0.10.2

RUN apk add git
RUN git clone \
  --depth 1 \
  --branch "${DUCKDB_VERSION}" \
  "${DUCKDB_REPO}" \
  /duckdb
WORKDIR /duckdb

# "fix"
RUN apk add sed
RUN sed -i \
  's/#include <linux\/falloc.h>//g' \
  /duckdb/src/common/local_file_system.cpp

RUN apk add \
  build-base \
  cmake \
  ninja \
  python3

RUN GEN=ninja make clean release
```

### OS:

x86_64

### DuckDB Version:

v0.10.2

### DuckDB Client:

build system?

### Full Name:

Tim Fischer

### Affiliation:

Universtity of Tübingen

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Thanks for raising this. We have a CI job now that checks for compatibility in alpine:latest, and hopefully that should help prevent similar problems moving forward.
