### ISSUE TITLE
0.10.2: error: non-const lvalue reference to type 'idx_t' (aka 'unsigned long') cannot bind to a value of unrelated type 'optional_idx'

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#11707]
### What happens?

```
/usr/ports/databases/duckdb/work/duckdb-0.10.2/extension/sqlite_scanner/src/storage/sqlite_table_entry.cpp:56:28: error: non-const lvalue reference to type 'idx_t' (aka 'unsigned long') cannot bind to a value of unrelated type 'optional_idx'
   56 |         if (!db.GetMaxRowId(name, result.cardinality)) {
      |                                   ^~~~~~~~~~~~~~~~~~
/usr/ports/databases/duckdb/work/duckdb-0.10.2/extension/sqlite_scanner/src/include/sqlite_db.hpp:48:52: note: passing argument to parameter 'row_id' here
   48 |         bool GetMaxRowId(const string &table_name, idx_t &row_id);
      |                                                           ^
1 error generated.
```

### To Reproduce

Regular build.

### OS:

FreeBSD 14.0

### Complier:

Clang-17

### DuckDB Version:

0.10.2

### DuckDB Client:

C++

### Full Name:

Yuri Victorovich

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Sounds like it's [this](https://github.com/duckdb/sqlite_scanner/issues/89) issue in the relevant repo?

**Comment by carlopi** [comment]
What sqlite_scanner version are you compiling in? I think this has been solved in v0.10.2 + sqlite_scanner at 091197efb34579c7195afa43dfb5925023c915c0, that is the version declared in https://github.com/duckdb/duckdb/blob/main/.github/config/out_of_tree_extensions.cmake#L92

**Comment by carlopi** [comment]
I think this is solved, as is the issue linked by @Tishj (https://github.com/duckdb/sqlite_scanner/issues/89).

----

One thing that we could improve on is having some way to specify extension dependencies like:
```
duckdb_extension_load( sqlite
     GIT_URL https://github.com/duckdb/sqlite_scanner
     GIT_TAG auto
     )
that inherits the GIT_TAG from some other file part of duckdb sources.

That would allow instructions to keep working across versions mirroring the equivalent duckdb setup.

**Comment by carlopi** [comment]
This is solved, workflow can be improved, but solution here is using a more recent sqlite_scanner.
