### ISSUE TITLE
python : query parameterization fails for IN clause

### ISSUE THREAD

**Issue by ShruthiPersonal** [duckdb/duckdb#11712]
### What happens?

**no parameters : query Works:**
```
>>> duckdb.execute("SELECT 'English' IN ('CS', 'Math', NULL, 'English');").df()
   ('English' IN ('CS', 'Math', NULL, 'English'))
0                                            True
```

**Trying to make the list parameter**
```
>>> l = ('CS', 'Math', None, 'English')
>>> duckdb.execute("SELECT 'English' IN $list_l;", {'list_l': l} ).df()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**_duckdb.duckdb.ParserException: Parser Error: syntax error at or near "$"_**
```

**The same query works outside python ( from Dbeaver)**
```
@set l =  ('CS', 'Math', NULL, 'English')
SELECT 'English' IN ${l};"
```

### To Reproduce

```
import duckdb
l = ('CS', 'Math', None, 'English')
duckdb.execute("SELECT 'English' IN $list_l;", {'list_l': l} ).df()
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

python

### Full Name:

Shruthi Chidambara

### Affiliation:

Ericsson

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
`duckdb.execute("SELECT 'English' IN (UNNEST($list_l));", {'list_l': l} ).df()`
