### ISSUE TITLE
ParamsToString() in GET table filters missing apostrophes in VARCHAR fields

### ISSUE THREAD

**Issue by ila** [duckdb/duckdb#11729]
### What happens?

The ParamsToString() function does not properly convert VARCHAR fields (missing the apostrophes) when being called on the table filters of `LOGICAL_GET` nodes. This would be useful because I am implementing new optimizer rules turning (modified) logical plans back to SQL strings (within incremental view maintenance, for example). Tested with the last commit of DuckDB.

### To Reproduce

```sql
create table test(id1 int, id2 string);
insert into test values (1, 'a'), (2, 'b'), (3, 'c');
explain update test set id1 = 4 where id2 = 'a';
```
```text
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           UPDATE          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│             #0            │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            test           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: id2=a AND id2 IS │
│          NOT NULL         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 1           │
└───────────────────────────┘ 
```

Desired output:
`Filters: id2='a' AND id2 IS NOT NULL` in the bottom node. 

Basically I need strings to be properly enclosed between apostrophes (`'a'` and not `a`). I can try and fix it myself if it's too much of a hassle - or alternatively please let me know if this is the intended behaviour, such that I will implement a workaround.

### OS:

Ubuntu 23.10

### DuckDB Version:

10

### DuckDB Client:

shell

### Full Name:

Ilaria Battiston

### Affiliation:

CWI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for the report

I don't see any problem in making this change.
I have not worked on the EXPLAIN output before so I'm not entirely sure what the purpose of the output is, other than simply visualizing, so I might be wrong.

This can be fixed by using `ToSQLString` in the ConstantFilter::ToString rather than `ToString` for the `constant` Value
`src/planner/filter/constant_filter.cpp`

**Comment by ila** [comment]
Just a clarification - this is unrelated to the EXPLAIN output, I just used EXPLAIN in this example to print the logical plan. In my implementation, I'm using C++ to call this function on a LogicalGet object, to extract the corresponding string representation of the table filters and then reuse it :)

**Comment by Mytherin** [comment]
Happy to review a PR here

**Comment by rcurtin** [comment]
I happen to have a similar need, and have been poking around the internal guts, so @ila if you aren't already planning on submitting a PR I'm happy to open one.  This one looks very simple, presuming that changing from `ToString()` to `ToSQLString()` in `ConstantFilter` doesn't break any assumptions anywhere else.  (I don't have the internal knowledge to say either way, sounds like it will be ok?)

**Comment by ila** [comment]
I'm travelling these days so if you are in urgent need, I won't object :) I agree that it sounds quite simple to do, so I really don't mind either way - also no problem if you prefer me to fix it, I can allocate a couple hours before EOW. 

Keep me posted and no pressure! May I ask what your use case of this is?

**Comment by rcurtin** [comment]
We're using the DuckDB internal planner to analyze SQL statements to extract pushed-down filters for object storage scans, so recovery of the filter in a way we can reuse it is important.  I opened #11797 to address the issue, it is an easy PR (hopefully I didn't overlook something).

**Comment by rcurtin** [comment]
#11797 is merged now, so I suppose that this issue can be closed (but I don't have permissions to do that).
