### ISSUE TITLE
0.10.2 introduces new Error: Binder Error: Cannot compare values of type VARCHAR and type DATE - an explicit cast is required

### ISSUE THREAD

**Issue by rajivpatki** [duckdb/duckdb#11731]
### What happens?

A query on a dataset that has a `date` column of type `VARCHAR` could earlier be used as `DATE` type without explicit typecasts. This was extremely convenient since a lot of datasets that we use are partitioned by date.

Now 

```
SELECT date, COUNT(*)
FROM dataset
WHERE date >= CURRENT_DATE - 14
GROUP BY ALL;
```
yields `Error: Binder Error: Cannot compare values of type VARCHAR and type DATE - an explicit cast is required ...`

### To Reproduce

In python 3.10 execute this query:
```
CREATE OR REPLACE TABLE dataset AS 
    SELECT * FROM read_parquet('s3://mybucket/dataset/date=*/*.parquet');

SELECT
    date, COUNT(*) FROM dataset
WHERE date >= CURRENT_DATE - 14
GROUP BY ALL
```
to get the error

This is fixed by:
```
SELECT
    date::DATE, COUNT(*)
FROM dataset
WHERE date:DATE >= CURRENT_DATE - 14
GROUP BY ALL
```
**Explicit typecasting was not required until `0.10.1` and worked perfectly before `0.10.2`**

### OS:

x86

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Rajiv Patki

### Affiliation:

Jodaro

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! This was an intentional change because implicit casting causes ambiguity which can cause odd/unexpected results - see the [v0.10.0 blog post](https://duckdb.org/2024/02/13/announcing-duckdb-0100.html#breaking-sql-changes) and the [PR that introduced this behavior](https://github.com/duckdb/duckdb/pull/10115). You can use `SET old_implicit_casting=true` to revert to the old behavior.

**Comment by rajivpatki** [comment]
from https://github.com/duckdb/duckdb/pull/10115#issue-2063584830
> setting `old_implicit_casting` can be used to revert to the old behavior (for now - potentially to be deprecated in the future

Thank you for the very prompt response. Really loved the ease of implicit typecasting. How likely is the deprecation of this setting? We update the version of duckdb to the latest and the typecasting breaking was quite inconvenient. Although the inconvenience is solved for now with `SET old_implicit_casting=true`, it is possibly only temporary given that there are plans to deprecate the setting.

If someone's taking a [vote](https://github.com/duckdb/duckdb/pull/10115#issuecomment-2053514291), would love to vote a strong "Please don't" on deprecation of `old_implicit_casting`

**Comment by Mytherin** [comment]
We might rename the setting in the future, it's unlikely we will remove the functionality entirely.
