### ISSUE TITLE
Documentation for COPY TO: Please mention there is no need for overwrite guard code

### ISSUE THREAD

**Issue by SteampunkIslande** [duckdb/duckdb#11738]
### What happens?

When trying to aggregate parquet files into one, it is unclear whether I should protect the aggregate from reading and writing back to itself.

I learned the hard way that duckdb already seems to implement some guards to prevent overwriting a parquet on itself when copying the result of a query.

I'd say this is an awesome feature, but not knowing it existed from the doc really was frustrating.

### To Reproduce

This reproducible script produces test1.parquet, test2.parquet, test3.parquet, and aggregate.parquet

```python
import duckdb as db

# Input data to aggregate
db.sql("COPY (SELECT 'a' col1, 'b' col2) TO 'test1.parquet'")
db.sql("COPY (SELECT 'c' col1, 'd' col2) TO 'test2.parquet'")

# Aggregate first two parquet files into one called aggregate.parquet
db.sql("COPY (SELECT * FROM read_parquet(['test1.parquet','test2.parquet'],union_by_name=True))TO 'aggregate.parquet'")

# Create new parquet
db.sql("COPY (SELECT 'e' col1, 'f' col2) TO 'test3.parquet'")

# Try being safe: I want to take new values from test3.parquet, and aggregate them with the content of aggregate.parquet
# So I implement it myself by renaming the destination with... .tmp
db.sql("COPY (SELECT * FROM read_parquet(['test3.parquet','aggregate.parquet'],union_by_name=True)) TO 'aggregate.parquet.tmp'")

# And now the file is corrupted
db.sql("SELECT * FROM read_parquet('aggregate.parquet.tmp')")
```

So this code works fine, no overwriting/data race condition because
it silently created a new intermediate file with .tmp suffix.
```python
import duckdb as db

# Input data to aggregate
db.sql("COPY (SELECT 'a' col1, 'b' col2) TO 'test1.parquet'")
db.sql("COPY (SELECT 'c' col1, 'd' col2) TO 'test2.parquet'")

# Aggregate first two parquet files into one called aggregate.parquet
db.sql("COPY (SELECT * FROM read_parquet(['test1.parquet','test2.parquet'],union_by_name=True))TO 'aggregate.parquet'")

# Create new parquet
db.sql("COPY (SELECT 'e' col1, 'f' col2) TO 'test3.parquet'")

# Copy aggregate from aggregate and test3 back into aggregate! Similar behavior as moreutils sponge :)
db.sql("COPY (SELECT * FROM read_parquet(['test3.parquet','aggregate.parquet'],union_by_name=True)) TO 'aggregate.parquet'")

# And now the file is fine
db.sql("SELECT * FROM read_parquet('aggregate.parquet')")
```

### OS:

Linux Mint x86_64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Charles Monod-Broca

### Affiliation:

Bioinformatician - Public hospital

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
The file is not corrupted, it's simply not in parquet format because how could duckdb possibly know that you wanted it in parquet format? You need to add `(FORMAT PARQUET)` to your `COPY` statement if you want to write a parquet file but don't want to use a parquet file ending. 

As to duckdb getting this right automatically: personally I'd be more surprised if it didn't, but feel free to make a PR at the documentation repository (note that each page of the documentation website has a link at the bottom to the corresponding source in GitHub, e.g. https://duckdb.org/docs/sql/statements/copy.html links to https://github.com/duckdb/duckdb-web/edit/main/docs/sql/statements/copy.md)

**Comment by SteampunkIslande** [comment]
> The file is not corrupted, it's simply not in parquet format because how could duckdb possibly know that you wanted it in parquet format? You need to add `(FORMAT PARQUET)` to your `COPY` statement if you want to write a parquet file but don't want to use a parquet file ending.

Thanks, I had forgot about this FORMAT statement, feeling stupid now...

> As to duckdb getting this right automatically: personally I'd be more surprised if it didn't, but feel free to make a PR at the documentation repository (note that each page of the documentation website has a link at the bottom to the corresponding source in GitHub, e.g. https://duckdb.org/docs/sql/statements/copy.html links to https://github.com/duckdb/duckdb-web/edit/main/docs/sql/statements/copy.md)

Thanks, I like this feature but it feels like this kind of guard code should always be under the responsibility of the user. But now I know it's not required when working with duckdb :)

**Comment by soerenwolfers** [comment]
It's not required *in this instance*. It might fail in more complex problems, and I agree with you that it's bad practice to overwrite an input file, especially when using a declarative system like duckdb.

**Comment by SteampunkIslande** [comment]
Oooof, so I guess I should remove my pull request...
