### ISSUE TITLE
FLOAT/Integer gives FLOAT, when it should be a Double

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11739]
### What happens?

FLOAT/Integer gives FLOAT, when it should get promoted to a Double (Precision).
This is a problem when DuckDB produces inaccurate results which can't be reproduced in Java, C or Python or any other RDBMS.

### To Reproduce

```sql
select pg_typeof( 0.07::FLOAT/12 ) AS type;

/* DuckDB returns FLOAT
┌───────┐
│ type  │
├───────┤
│ float │
└───────┘
*/

/* Postgres returns DOUBLE, see: https://onecompiler.com/postgresql/42as368hk */
```

```sql
-- real life example
SELECT 345349 * POW((1+7::FLOAT/100/12),120) qty2010;

-- result: 694,039.0214962073
-- expected:  694,034.54678046
-- 5 Dollar difference!

-- illustration
select printf('%21.15f', 0.07::DOUBLE/12 -  0.07::FLOAT/12 ) diff;

/* 
┌───────────────────────┐
│ diff                  │
├───────────────────────┤
│ -0.000000000024835    │
└───────────────────────┘
*/
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
C, Java, and C# all behave like duckdb. 
MySQL behaves like duckdb.
SQLite doesn't offer single precision floats. 

Out of the languages I tested, only PostgreSQL behaves in the way you describe with the magic upcast. 

Personally, I'd consider PostgreSQL to be "in the wrong" here.

**Comment by manticore-projects** [comment]
I have tested Oracle
```sql
SELECT 345349 * POWER((1+Cast(7 AS FLOAT)/100/12),120) qty2010 from dual;

/*
┌───────────────┐
│ QTY2010       │
├───────────────┤
│ 694,034.54678 │
└───────────────┘
*/
```

I have tested H2:
```sql
SELECT 345349 * POWER((1+Cast(7 AS FLOAT)/100/12),120) qty2010;

/*
┌───────────────┐
│ QTY2010       │
├───────────────┤
│ 694,034.54678 │
└───────────────┘
*/
```

**Comment by soerenwolfers** [comment]
The equivalent of duckdb's `FLOAT` in Oracle DB is `BINARY_FLOAT`,  see https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html

**Comment by soerenwolfers** [comment]
The equivalent of duckdb's `FLOAT` in H2 is `REAL` (but u haven't tested H2 myself).

**Comment by soerenwolfers** [comment]
The equivalent of duckdb's `FLOAT` in MSSQL is `REAL`, the equivalent of duckdb's `DOUBLE` in MSSQL is `FLOAT`, see https://learn.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-ver16

**Comment by soerenwolfers** [comment]
The equivalents of duckdb's `FLOAT` and `DOUBLE` in PostgreSQL are `REAL` AND `DOUBLE PRECISION`, see
 https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by soerenwolfers** [comment]
What's uncommon is therefore not promotion/upcasting, but that duckdb resolves the ambiguity allowed by the SQL standard by letting `FLOAT` be a 32 bit floating point type, whereas most other dialects let it be a 64 bit floating point type. 

If you don't like that, best to be explicit and write `FLOAT4` or `FLOAT8` always.

**Comment by manticore-projects** [comment]
Thank you very much, I get your explanation.
I still think, the FLOAT = FLOAT4 instead of FLOAT = FLOAT8 confusing (at least for anyone coming from traditional databases).

1) we are not aiming for embedded (where 4 bytes matter), are we?
2) we are aiming for Oracle and BigQuery and MS SQL Server (not for MySQL), are we?
3) what exactly would be lost when aliasing FLOAT8 as FLOAT (instead of FLOAT4)

Of course I understand, that all of this is no issue when starting from scratch on DuckDB and casting to FLOAT8 explicitly.

But what about "migration from and compatibility with existing RDBMS/Applications"?

Maybe a special Web Page on those topics would help also.

**Comment by soerenwolfers** [comment]
- If you are coming from "traditional databases", wouldn't you have expected `FLOAT` = `DOUBLE PRECISION`? Your OP suggests you expected `FLOAT`!=`DOUBLE`.
- As I've written above, Oracle doesn't define `FLOAT` the same way as MS SQL, so what should duckdb do if it were "aiming for traditional databases"?
- I agree a "Important differences to other databases" page in the documentation could be useful. Personally, I haven't used other databases but have used all the regular programming languages mentioned above, so I for one am happy with the current definitions in duckdb. 
- 32 bits can be very useful if you have lots of data and not as much RAM. Also, 32 bits can be faster even if you have infinite memory; many things are RAM throughout limited, and needing to move half the amount of data from RAM to CPU can help. 
- Personally, I would be fine if `FLOAT` were `FLOAT8`, but changing the meaning of something as fundamental as`FLOAT` can be difficult / scare off users, while writing `DOUBLE` is easy.

**Comment by manticore-projects** [comment]
> * If you are coming from "traditional databases", wouldn't you have expected `FLOAT` = `DOUBLE PRECISION`? Your OP suggests you expected `FLOAT`!=`DOUBLE`.

No, I would have wanted a `DOUBLE PRECISION` based calculation.

>     * As I've written above, Oracle doesn't define `FLOAT` the same way as MS SQL, so what should duckdb do if it were "aiming for traditional databases"?

I get that, but Oracle's `FLOAT` is closer to `DOUBLE PRECISION` regarding the calculation.

>     * I agree a "Important differences to other databases" page in the documentation could be useful. Personally, I haven't used other databases but have used all the regular programming languages mentioned above, so I for one am happy with the current definitions in duckdb. Maybe you can start with adding a warning that could have helped you to https://duckdb.org/docs/sql/data_types/numeric.html (which you can edit yourself, see link at bottom)?

Ok, will do so and we can close this issue.

Again, thank you for explanation and time. I do appreciate!

**Comment by manticore-projects** [comment]
@soerenwolfers, please pardon me for pardon further:

```sql
select typeOf(1/10)
union all
select typeOf(1.0::float/10)

/*
┌────────┐
│ typeof │
├────────┤
│ DOUBLE │
├────────┤
│ FLOAT  │
└────────┘
*/
```

Why is Integer upcast to Double, but Float is not?
Allow me to explain my thought. We are dealing with 2 different questions here: storing data and calculating with data. It makes totally sense to store FLOAT4. But why would you ever want to calculate with FLOAT4 instead of FLOAT8? Depending on your answer the above example should either return INT FLOAT or DOUBLE DOUBLE.

I think it should be DOUBLE DOUBLE because we can always round down when storing the data in a FLOAT column.

**Comment by manticore-projects** [comment]
```sql

select 1/3 - Cast(1 AS float)/3;
-- MS SQLServer: -0.3
-- H2: -0.3
-- Postgres: -0.3

select 1/3 - Cast(1 AS binary_float)/3  from dual;
-- Oracle: 0.00 sharp (because DOUBLE DOUBLE)

select printf('%15.14f', 1/3 - Cast(1 AS float)/3 );
-- DuckDB: -0.00000000993411 (because DOUBLE FLOAT)
```

I do understand the first team and I understand Oracle. DuckDB puzzles me.

**Comment by soerenwolfers** [comment]
You'd want to calculate with float4 because it's faster. 

float / int is float because that requires only one cast. It'd be pretty strange if 3f / 2 returned a different answer than 3f / 2f. 

int / int could have been double or float. 

Personally, I'd prefer if both float / int and int / int were errors and you'd need to explicitly cast or use integer division (//), but a lot of people would disagree. 

The only difference between duckdb and PostgreSQL+MSSQL is that duckdb uses // for integer division.
