### ISSUE TITLE
Can't replace single quote character

### ISSUE THREAD

**Issue by jaanli** [duckdb/duckdb#11750]
### What happens?

Cannot replace single quotes in column names or row entries like "GOV'T AGENCY" occurring in many common databases such as https://data.cityofnewyork.us/Housing-Development/DOB-Permit-Issuance/ipu4-2q9a/about_data. 

Might be missing something basic here :) this is to augment a NYC map: https://jaanli.github.io/new-york-real-estate/ for public utility.

### To Reproduce

Save `sample_data.csv` file with contents:

```
id,name,description
1,John,This is John's data
2,Alice,Alice's data has a single quote
3,Bob,Bob's data is also not fine
```

In duckdb:

```
SELECT id, name, regexp_replace(description, "'", '') AS description FROM 'sample_data.csv';
```

Error:

```
Error: Binder Error: Referenced column "'" not found in FROM clause!
Candidate bindings: "sample_data.id", "sample_data.name"
LINE 1: ... id, name, regexp_replace(description, "'", '') AS description FROM 'sample_da...
                                                  ^
```

The escape character is listed as a double quote character, `"`, in the documentation: https://duckdb.org/duckdb-docs.pdf

### OS:

MacOS

### DuckDB Version:

0.10

### DuckDB Client:

CLI

### Full Name:

Dr. Jaan Lı 

### Affiliation:

University of Tartu

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Double quotes are reserved for quoting identifiers (https://duckdb.org/docs/sql/keywords_and_identifiers#identifiers)

It looks like you're trying to create a string literal, which requires surrounding in `'`

Because your string contains `'` it should be doubled to be properly escaped:
`regexp_replace(description, '''', '')`

**Comment by jaanli** [comment]
Yup that was it, thank you @Tishj !! Very hard to google this gotcha :)

```
SELECT id, name, regexp_replace(description, '''', '') AS description FROM 'sample_data.csv';
```

This works :) would be nice to have it documented somewhere (or I am searching for the wrong thing in documentation - was searching for escape characters, quotes, single quotes, etc)...

**Comment by Tishj** [comment]
Yea I agree, I thought it would be documented under the identifiers section but I was also surprised not to find better mention of this
