### ISSUE TITLE
Cannot `insert into ... with foo as materialized (...) select * from foo` in 0.10.2

### ISSUE THREAD

**Issue by mima-hlavacek** [duckdb/duckdb#11767]
### What happens?

From 0.10.2 it is no longer possible to use a select with a materialized CTE as a body of an insert query.

### To Reproduce

```sql
create table foo(bar int);
insert into foo(bar) with baz as materialized (select 1) select * from baz;
```

Both on `v0.10.2` and `v0.10.3-dev306 c861b2d70f` we get

```
Binder Error: Duplicate alias "baz" in query!
```

On `v0.10.1` the query works.

Also, without the `materialized` the query works fine in all versions

```sql
insert into foo(bar) with baz as (select 1) select * from baz;
```

I'd suspect it has to do with the fact that you can do `with foo as materialized ... insert into ...` since `0.10.2`. So maybe it's expected that the query does not work 🤷 . If that is the case, it's just a matter of a confusing error message.

### OS:

Ubuntu x64 in WSL on Windows 11

### DuckDB Version:

v0.10.2, v0.10.3-dev306 c861b2d70f

### DuckDB Client:

cli and python

### Full Name:

Míma Hlaváček

### Affiliation:

Blindspot.ai

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
@mima-hlavacek could you please reach out to me at hannes@duckdblabs.com
