### ISSUE TITLE
Incorrect TIMETZ comparisons

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11766]
### What happens?

duckdb says `'09:00:00+00:00'::TIMETZ  < '09:01:00+01:00'::TIMETZ`.

(Side problem: duckdb displays TIMETZ different than TIMESTAMPTZ: It doesn't consistently display TIMETZ using the settings-time-zone, but sometimes uses `+00:00` offset)

### To Reproduce

```sql
SET TimeZone='Europe/London';
SELECT 
'09:00:00+00:00'::TIMETZ AS NineUTC,
'09:00:00'::TIMETZ AS EightUTC,
'09:01:00'::TIMETZ AS EightOneUTC,
NineUTC > EightUTC,
NineUTC > EightOneUTC,
```
```
┌─────────────────────┬─────────────────────┬─────────────────────┬──────────────────────┬─────────────────────────┐
│       NineUTC       │      EightUTC       │     EightOneUTC     │ (NineUTC > EightUTC) │ (NineUTC > EightOneUTC) │
│ time with time zone │ time with time zone │ time with time zone │       boolean        │         boolean         │
├─────────────────────┼─────────────────────┼─────────────────────┼──────────────────────┼─────────────────────────┤
│ 09:00:00+00         │ 09:00:00+01         │ 09:01:00+01         │ true                 │ false                   │
```

Same result with
```sql
SET TimeZone='UTC';
SELECT 
'09:00:00+00:00'::TIMETZ AS NineUTC,
'09:00:00+01:00'::TIMETZ AS EightUTC,
'09:01:00+01:00'::TIMETZ AS EightOneUTC,
NineUTC > EightUTC,
NineUTC > EightOneUTC,
```
```
┌─────────────────────┬─────────────────────┬─────────────────────┬──────────────────────┬─────────────────────────┐
│       NineUTC       │      EightUTC       │     EightOneUTC     │ (NineUTC > EightUTC) │ (NineUTC > EightOneUTC) │
│ time with time zone │ time with time zone │ time with time zone │       boolean        │         boolean         │
├─────────────────────┼─────────────────────┼─────────────────────┼──────────────────────┼─────────────────────────┤
│ 09:00:00+00         │ 09:00:00+01         │ 09:01:00+01         │ true                 │ false                   │
└─────────────────────┴─────────────────────┴─────────────────────┴──────────────────────┴─────────────────────────┘
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Plan of record is to add a collation function and fold the fix into the JSON collation work. Short term, I will update the class to provide a collate function and expose it in the function library. This will allow the two? people with the issue to use it manually until the full fix is in.

**Comment by hawkfish** [comment]
Just tried this on feature and it works now:

|   NineUTC   |  EightUTC   | EightOneUTC | (NineUTC > EightUTC) | (NineUTC > EightOneUTC) |
|-------------|-------------|-------------|---------------------:|------------------------:|
| 09:00:00+00 | 09:00:00+01 | 09:01:00+01 | true                 | true                    |
