### ISSUE TITLE
`DATE_TRUNC` returns wrong results for `TIMESTAMPTZ`

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11799]
### What happens?

When `DATE_TRUNC` is provided with a `TIMESTAMPTZ`, the result:
1) still carries the `TIME` part
2) is of type `TIMESTAMPTZ` instead of `DATE`
3) with the actual Date shifted back

### To Reproduce

```sql
SELECT TIMESTAMPTZ '2015-05-08T23:39:20.123-07:00' AS "DATE1",
       DATETRUNC('YEAR', "DATE1") AS "TRUNCATED TO YEAR",
       DATETRUNC('MONTH', "DATE1") AS "TRUNCATED TO MONTH",
       DATETRUNC('DAY', "DATE1") AS "TRUNCATED TO DAY";

/* 
-- result
┌──────────────────────────┬───────────────────┬────────────────────┬───────────────────┐
│ DATE1                    │ TRUNCATED TO YEAR │ TRUNCATED TO MONTH │ TRUNCATED TO DAY  │
├──────────────────────────┼───────────────────┼────────────────────┼───────────────────┤
│ 2015-05-09T06:39:20.123Z │ 2014-12-31T17:00Z │ 2015-04-30T17:00Z  │ 2015-05-08T17:00Z │
└──────────────────────────┴───────────────────┴────────────────────┴───────────────────┘

-- expected was
┌───────────────────┬───────────────────┬────────────────────┬──────────────────┐
│ DATE1             │ TRUNCATED TO YEAR │ TRUNCATED TO MONTH │ TRUNCATED TO DAY │
├───────────────────┼───────────────────┼────────────────────┼──────────────────┤
│ 09/05/2015, 06:39 │    01/01/2015     │     01/05/2015     │    09/05/2015    │
└───────────────────┴───────────────────┴────────────────────┴──────────────────┘


*/

```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
What time zone are you running the queries in?

**Comment by hawkfish** [comment]
Also, `DATE_TRUNC` always returns `TIMESTAMP_TZ` - this matches the behaviour of Postgres:

```sql
hawkfish=# set timezone='US/Pacific';
SET
hawkfish=# select date_trunc('year', '2015-05-08T23:39:20.123-07:00'::TIMESTAMPTZ);
       date_trunc       
------------------------
 2015-01-01 00:00:00-08
```

**Comment by hawkfish** [comment]
> Bangkok/Thailand - UTC+7 But why would that matter for date trunc please?

I don't know, but it's part of the environment that need for reproducing TZ issues. (I've even had issues where the  calendar was not Gregorian...)

**Comment by manticore-projects** [comment]
> Also, `DATE_TRUNC` always returns `TIMESTAMP_TZ` - this matches the behaviour of Postgres:

```sql
SELECT TIMESTAMP '2015-05-08T23:39:20.123-07:00' AS "DATE1",
       typeof(DATE_TRUNC('YEAR', "DATE1")) AS "TRUNCATED TO YEAR",
       typeof(DATE_TRUNC('MONTH', "DATE1")) AS "TRUNCATED TO MONTH",
       typeof(DATE_TRUNC('DAY', "DATE1")) AS "TRUNCATED TO DAY";

/*
┌───────────────────┬───────────────────┬────────────────────┬──────────────────┐
│ DATE1             │ TRUNCATED TO YEAR │ TRUNCATED TO MONTH │ TRUNCATED TO DAY │
├───────────────────┼───────────────────┼────────────────────┼──────────────────┤
│ 09/05/2015, 06:39 │ DATE              │ DATE               │ DATE             │
└───────────────────┴───────────────────┴────────────────────┴──────────────────┘
*/


But not for TIMESTAMP?

**Comment by hawkfish** [comment]
Do you mean `Asia/Bangkok`? 

```sql
D from duckdb_settings() where name = 'TimeZone';
```
|   name   |        value        |      description      | input_type | scope  |
|----------|---------------------|-----------------------|------------|--------|
| TimeZone | America/Los_Angeles | The current time zone | VARCHAR    | GLOBAL |

**Comment by hawkfish** [comment]
Ah it looks like we have tweaked the binder for `TIMESTAMP` and this does not match PG. I think the reason we didn't is that with TSTZ truncating to a `DATE` depends on the TZ, which could cause problems (if the date was stored and then cast back to TSTZ in a different TZ there would be data corruption).

**Comment by hawkfish** [comment]
I can't reproduce your problem on 0.10.2, but the display of your values is a bit concerning. `2014-12-31T17:00Z` is not what we usually display? It looks like you may not have ICU loaded?

```sql
D from duckdb_extensions() where extension_name ='icu';
```
| extension_name | loaded | installed | install_path |                           description                            | aliases | extension_version |
|----------------|-------:|----------:|--------------|------------------------------------------------------------------|---------|-------------------|
| icu            | true   | true      | (BUILT-IN)   | Adds support for time zones and collations using the ICU library | []      |                   |

**Comment by manticore-projects** [comment]
My output is from out own JDBC Database browser, not from DuckDB2 directly.
I use it for simplified ASCII copy'n paste.

**Comment by hawkfish** [comment]
> My output is from out own JDBC Database browser, not from DuckDB2 directly. I use it for simplified ASCII copy'n paste.

Ah that's the confusion then. The results you are getting are the timestamps truncated to the start of the year in your time zone, but displayed in UTC.

**Comment by manticore-projects** [comment]
I am honestly confused here. In my simple world, a DATE TRUNC would return  a DATE which is not sensitive to a Time Zone because Date has no time. So when applying DATE TRUNC on a TIMESTAMPTZ I would have expected 1) translation to UTC TIMESTAMP and then truncating the time.

**Comment by hawkfish** [comment]
Sadly we do not [live in a simple world](https://xkcd.com/2867/) where time is concerned!

But dates _are_sensitive to time zone: A date is a [range of instants](https://duckdb.org/2022/01/06/time-zones.html). But to get the behaviour you want, just add a cast to `DATE`:

```sql
D select date_trunc('year', '2015-05-08T23:39:20.123-07:00'::TIMESTAMPTZ)::DATE y;
```
|     y      |
|------------|
| 2015-01-01 |

**Comment by hawkfish** [comment]
Think this got sorted?
