### ISSUE TITLE
`ATTACH` , `search_path` and create `DDL` on current database

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#11839]
### What happens?

When I : 

1. Create a database in `read_only=False` mode
2. Attach third party READ ONLY databases
3. Set the search path to the two remote database
4. Try to create a table
5. The statement fails complaiing that the database is in READ ONLY mode while I would have exptected it to create the table on the current main database

### To Reproduce

Below the script : 

```python
import duckdb
con = duckdb.connect(database='opt-nc-acronyms-genai.duckdb', read_only=False)

con.execute("ATTACH IF NOT EXISTS '/kaggle/input/ai-enhanced-opt-nc-acronyms/opt-nc-acronyms.duckdb' AS genai (READ_ONLY)")
con.execute("ATTACH IF NOT EXISTS '/kaggle/input/codes-romes-database/codes-rome.duckdb' AS rome (READ_ONLY)")
```

then update the `search_path` : 

```python
con.execute("SET search_path = 'genai,rome'")
```

....finally try to create a table : 

```python
con.execute("create or replace table test(i integer)")
```

### OS:

Linux

### DuckDB Version:

v0.10.2

### DuckDB Client:

Python

### Full Name:

Adrien Sales

### Affiliation:

dev.to/adriens

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! When creating a table without specifying which database it belongs to, it is created in the first database in the search path. This is equivalent to running `USE genai`. The remaining entries in the search path are used for reading in case entries are not found in the other catalogs in the search path.

I've opened an issue in the documentation so we can work on clarifying this in the documentation.

**Comment by adriens** [comment]
> Thanks for the report! When creating a table without specifying which database it belongs to, it is created in the first database in the search path. 

Yep, so I searched if there was a kind of `.` ie. current alias to specify the main database but I did not know how I should call it... 

Thanks for the fast answer, that's really cool... and the `ATTACH`  option is so convenient :magic_wand:

**Comment by adriens** [comment]
Hi, please keep this issue alive :pray:

**Comment by Mytherin** [comment]
The corresponding issue has been created in the documentation repo - https://github.com/duckdb/duckdb-web/issues/2786 - we shouldn't need to keep this issue around here
