### ISSUE TITLE
`UHUGEINT` columns cause errors when trying to export results to `ArrowReader`

### ISSUE THREAD

**Issue by kirankpandi** [duckdb/duckdb#11833]
### What happens?

`UHUGEINT` columns doesn't seem to be getting mapped to Arrow types when exporting results to `ArrowReader`. This results in the error - `Unsupported Arrow type UHUGEINT`, when trying to get vector schema.

### To Reproduce

Run the java code below with DuckDB 0.10.2. For the SQL with `HUGEINT`, the column in result gets properly mapped to `DECIMAL`. But the SQL with `UHUGEINT` results in an exception.
```
public class UHugeIntTest {

    public static void main(String[] args) throws SQLException, IOException {
        String[] sql = new String[] {"select val from (VALUES (1::HUGEINT)) TestVals(val)",
                "select val from (VALUES (1::UHUGEINT)) TestVals(val)"};

        ArrowReader arrowReader = null;
        try(BufferAllocator allocator = new RootAllocator();
            Connection connection = DriverManager.getConnection("jdbc:duckdb:");
            Statement statement = connection.createStatement()) {
            for(int i = 0; i < sql.length; i++) {
                System.out.println("SQL =====> " + sql[i]);
                try(ResultSet rs = statement.executeQuery(sql[i])) {
                    arrowReader = (ArrowReader)((DuckDBResultSet) rs).arrowExportStream(allocator, 256);
                    try {
                        VectorSchemaRoot schemaRoot = arrowReader.getVectorSchemaRoot();
                        for(FieldVector vector: schemaRoot.getFieldVectors()) {
                            System.out.println(vector.getField().getName() + "->" + vector.getField().getFieldType().getType());
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    } finally {
                        if(arrowReader != null) {
                            arrowReader.close();
                        }
                    }
                }
            }
        }
    }
}
```

### OS:

Mac

### DuckDB Version:

0.10.2

### DuckDB Client:

Java

### Full Name:

Kiran Pandi

### Affiliation:

Thoughtspot

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by jraymakers** [comment]
I submitted a fix/workaround for this a while back, but it was closed: https://github.com/duckdb/duckdb/pull/12298

**Comment by carlopi** [comment]
https://github.com/duckdb/duckdb/pull/13576 might be relevant (and would close this issue)
