### ISSUE TITLE
DuckDB on NoteBooks cannot connect to Persistent storage on a NAS.

### ISSUE THREAD

**Issue by MPizzotti** [duckdb/duckdb#11845]
### What happens?

On a notebook environment, duckdb cannot connect to a file, using duckdb.connect('file'), but in memory work just as expected.
I wanted to connect to a db so that i can run some transformation on cloud during a pipeline, and later on use the same db file for querying the same data inside a dashboard.
currently as a workaround i'm using parquet files, but also, since i need to run the db in memory, i'm using a way bigger cloud compute machine (in terms of memory) then actually needed.

I've tried 2 different variations, both giving back the same result:
`
FatalException: FATAL Error: Failed to create checkpoint because of error: Could not write file "{FILEPATH_REDACTED}": Operation not supported
`

### To Reproduce

1) On cloud Environment: DataBricks + Azure Blob Storage (attached to the VM as local disk)

Scenario: I've created a notebook on databricks, and created a new DuckDB Connection inside a cell, as follows:
```
ddb = duckdb.connect(f"{PATH_TO_MY_DBFILE}")
ddb.execute("PRAGMA disable_progress_bar;")
ddb.execute("PRAGMA enable_optimizer;")
ddb.execute("PRAGMA enable_object_cache;")
ddb.execute("SET errors_as_json = true;")
```
running this cell, everything works as expected, and now i have a connection.
but if i create a new cell immidiately after, and running a simple query where i'm reading from a parquet file like so:
```
    ddb.execute(f"""
    CREATE OR REPLACE TABLE mytable AS
    SELECT *
    FROM '{MYTABLE_PARQUET_FILEPATH}'
    """
```

2: ON LOCAL MACHINE: Jupyter notebook + Azure Blob Storage, connected via the Duckdb Azure connector.

scenario: the same as before:
Scenario: I've created a notebook on databricks, and created a new DuckDB Connection inside a cell, as follows:
```
ddb = duckdb.connect(f"{AZURE_PATH_TO_MY_DBFILE}")
ddb.execute("PRAGMA disable_progress_bar;")
ddb.execute("PRAGMA enable_optimizer;")
ddb.execute("PRAGMA enable_object_cache;")
ddb.execute("SET errors_as_json = true;")
```
running this cell, everything works as expected, and now i have a connection.
but if i create a new cell immidiately after, and running a simple query where i'm reading from a parquet file like so:
```
    ddb.execute(f"""
    CREATE OR REPLACE TABLE mytable AS
    SELECT *
    FROM '{AZURE_MYTABLE_PARQUET_FILEPATH}'
    """
```

### OS:

Linux x86 (databricks vm),  Windows 11 x86

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Massimiliano Pizzotti

### Affiliation:

EssilorLuxottica

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by geekypilot** [comment]
I'm able to reproduce the issue as well on Databricks + Azure Data Lake Storage Gen2 storage mounted to /mnt/REDACTED.

**Comment by MPizzotti** [comment]
related to the same problem:
I've created a DB file on databricks, using the databricks file system,  and then i've copied the file inside Azure BLOB Storage.
then, i've tried to connect using a new duckdb BOTH on my local PC and on Databricks, as follows:

```
# connecting to the COPIED file inside AZURE, NOT IN LOCAL SYSTEM
ddb3 = duckdb.connect(f"{AZ_BLOB_PATH}/mydb.duckdb", read_only=True)
ddb3.execute("PRAGMA disable_progress_bar;")
ddb3.execute("PRAGMA enable_optimizer;")
ddb3.execute("PRAGMA enable_object_cache;")
ddb3.execute(f"""SET GLOBAL temp_directory = '/local_disk0';""")
ddb3.execute("SET errors_as_json = true;")
```

once i have this ddb3 connection, i've tried to query a table like:
`ddb3.sql("select * from persistent_table where col1= 'code1' and col2='2024-04-20'")`

but the query hangs, i've waited for over 15 minutes without any results.

if i run the SAME QUERY, ON THE SAME FILE, inside databricks file system ("/local_disk0/mydb.duckdb")
example of connection:
```
# connecting to the COPIED file inside LOCAL SYSTEM
ddb2 = duckdb.connect(f"/local_disk0/mydb.duckdb", read_only=True)
ddb2.execute("PRAGMA disable_progress_bar;")
ddb2.execute("PRAGMA enable_optimizer;")
ddb2.execute("PRAGMA enable_object_cache;")
ddb2.execute(f"""SET GLOBAL temp_directory = '/local_disk0';""")
ddb2.execute("SET errors_as_json = true;")
```
the query runs perfectly fine, in less than a second.

I would love to give more details on How it hangs, but i don't have in depth skills regarding lower level APIs and connections.

**Comment by erincon01** [comment]
Hi, did you find a workaround?
