### ISSUE TITLE
Read CSV sniffer inconsistency depending on number of columns and order of columns content

### ISSUE THREAD

**Issue by alexanderluiscampino** [duckdb/duckdb#11840]
### What happens?

I have noticed that the CSV sniffer with auto-detect turned on returns inconsistent results for the same file* depending on the order of the data in the column, even when sample_size  = -1 (reading the entire file). Also, when some columns are removed, the result of sniffing changes. 

I would expect that the sniffer would be deterministic within the columns regardless of the data order on the number of columns in the file, given the sample size is the entire file. 

I have only observed this for the the date related formats, cannot speak if this happen to other data types. 

### To Reproduce

```python
import duckdb


def read(filename: str):
    try:
        query = f"""
            SELECT Date_Completed FROM read_csv(
                '{filename}',
                header = true,
                auto_detect = true,
                sample_size = -1
                )
            order by Date_Completed desc
            limit 5;
        """

        duckdb.sql(query).show()

    except Exception as e:
        print(e)


if __name__ == "__main__":
    for filename in [
        "webexport.tsv",
        "webexport_slim.tsv",
        "webexport_sorted.tsv",
        "webexport_slim_sorted.tsv",
    ]:
        print(f"\n\n-------- READING {filename!r}--------\n\n")
        read(filename)
```

console result:
```
-------- READING 'webexport.tsv'--------


Conversion Error: CSV Error on Line: 3
Error when converting column "property_id".
Could not parse string "84.00" according to format specifier "%m/%d/%Y"
84.00
^
Error: Month out of range, expected a value between 1 and 12

  file=webexport.tsv
  delimiter =    (Auto-Detected)
  quote = " (Auto-Detected)
  escape = " (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Auto-Detected)
  date_format = %m/%d/%Y (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=18446744073709549568
  ignore_errors=0
  all_varchar=0



-------- READING 'webexport_slim.tsv'--------


┌────────────────┐
│ date_completed │
│    varchar     │
├────────────────┤
│ 84.00          │
│ 12/17/2019     │
│ 07/01/2020     │
│ 0.00           │
│ NULL           │
└────────────────┘



-------- READING 'webexport_sorted.tsv'--------


┌────────────────┐
│ date_completed │
│    varchar     │
├────────────────┤
│ 84.00          │
│ 12/17/2019     │
│ 07/01/2020     │
│ 0.00           │
│ NULL           │
└────────────────┘



-------- READING 'webexport_slim_sorted.tsv'--------


┌────────────────┐
│ date_completed │
│    varchar     │
├────────────────┤
│ 84.00          │
│ 12/17/2019     │
│ 07/01/2020     │
│ 0.00           │
│ NULL           │
└────────────────┘
```

I have attached the 4 files I used for this test [webexport.zip](https://github.com/duckdb/duckdb/files/15123608/webexport.zip)

I can ignore this error for now, by doing:
```
auto_type_candidates = ['NULL', 'BOOLEAN', 'BIGINT', 'DOUBLE', 'VARCHAR']
```

but ideally this discrepancy should have a root cause that can create other pain points.

### OS:

Linux

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Alex Campino

### Affiliation:

Zillow

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by PeterSlickers** [comment]
I also observed that the outcome of read_csv depends on the size of the sample. If some rare lines of the full CSV file are not in the sample, than the result of column type detection may differ.

However, in your case, it seems that lines 125, 126 and 127 in 'webexport.tsv' are corrupted:
```
    7z x webexport.zip webexport.tsv
    grep -n -C2 628330 webexport.tsv

123-1285        2508    #19495  CNTY    BEATRICE SLOAN  08/01/2008                                      0.00            5800
124-1294        1611    #18471  CNTY    EVANS CONST & DEVEL CO  06/21/2006                                      0.00            89990
125:1294        5442    628330
126:628330
127:628330      CNTY            07/02/2018                                      0.00    MH
128-1294        5450    23894                   07/06/2018      09/11/2018                              0.00
129-1294        5451    23894                   07/06/2018      09/11/2018                              0.00
```

**Comment by alexanderluiscampino** [comment]
@PeterSlickers 

I believe the reason you are saying the file is corrupted is becase in those lines there are values that are shifted in the columns, which is a fair remark. But as fair as being correctly formatted as a TSV, the file is not corrupted. 

![image](https://github.com/duckdb/duckdb/assets/32500355/d0dc633f-55df-4126-a8ad-c217a159f4a4)

My sample size is the full size, so every row should be available to the sniffer, hence, if the sniffer dictates a column to be of the type date because the first N lines respected a given pattern, upon arriving to line #126, it should drop the date type and adopt a `varchar` type, in my opinion. 

I do accept that if you just give it a sample, of course we run the risk of the some data type not being present in the same ruining it. But that's the case here, I believe. Also, why does the presence of other columns affect the sniffing?

**Comment by PeterSlickers** [comment]
> I believe the reason you are saying the file is corrupted is becase in those lines there are values that are shifted in the columns, which is a fair remark. But as fair as being correctly formatted as a TSV, the file is not corrupted.
> 
Packages like duckdb or pandas are highly optimized for reading CSV files where the data in each column is homogenious. CSV files with homogenous columns are a subset of all possible CSV files. I would call them data-centric CSV files.

In Excel, there is no requirement for homogenious columns, cells in a column may have different types or formattings.
