### ISSUE TITLE
Python function `DuckDBPyConnection.type()` cannot resolve JSON type

### ISSUE THREAD

**Issue by ZiyaZa** [duckdb/duckdb#11849]
### What happens?

Similar to #11250, `duckdb.connect().type('JSON')` throws a transaction error. This issue was resolved when the `type()` function was called on `duckdb` directly, but calling it on `DuckDBPyConnection` is still problematic.

### To Reproduce

```python
import duckdb
duckdb.connect().type('JSON')
```

### OS:

Fedora Linux 38, x86

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Ziya Mukhtarov

### Affiliation:

CWI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I believe that's fixed on `main`

**Comment by ZiyaZa** [comment]
Indeed, it looks to be fixed with that PR. Apologies, I was looking at an older version of the main branch. Thank you!
