### ISSUE TITLE
Combining function chaining and reusable aliases fails in where clause

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#11854]
### What happens?

Howdy folks! 

I found a small issue when combining 2 of my favorite friendly SQL features. 

If I combine the use of function chaining and reusable aliases together in my select clause, then use that column in my where clause, I receive an error. 

### To Reproduce

It seems to be something to do with the combination of the two. Using just function chaining or just reusable aliases works correctly in the where clause. However, both together fails. 

```sql
-- Fails
with test as (
    select 'woot' as my_column
)
from test
select 
    my_column.substr(2) as partial_woot,
    partial_woot.substr(2) as more_partially_woot
where 
    more_partially_woot = 'ot'
;
```
```sql
Catalog Error: Scalar Function with name substr does not exist!
Did you mean "main.substr"?
LINE 7:     partial_woot.substr(2) as more_partially_woot
where 
    more_partially_woot = 'ot'
;...
            ^
```
```sql
-- Works: Multiple chains without reusable aliases
with test as (
    select 'woot' as my_column
)
from test
select 
    my_column.substr(2) as partial_woot,
    my_column.substr(2).substr(2) as more_partially_woot
where 
    more_partially_woot = 'ot'
;

-- Works: Single chain and reusing the alias in the where clause only
with test as (
    select 'woot' as my_column
)
from test
select 
    my_column.substr(2) as partial_woot,
where 
    partial_woot = 'oot'
;

-- Works: Reusable aliases that don't use function chaining
with test as (
    select 'woot' as my_column
)
from test
select 
    substr(my_column,2) as partial_woot,
    substr(partial_woot,2) as more_partially_woot
where 
    more_partially_woot = 'ot'
;
```

### OS:

MacOS

### DuckDB Version:

0.10.2, 0.10.3-dev388

### DuckDB Client:

CLI

### Full Name:

Alex Monahan

### Affiliation:

DuckDB Labs and MotherDuck (lol at Oracle placeholder)

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Alex-Monahan** [comment]
Worth keeping open for sometime in the future!

**Comment by chris-dailey** [comment]
I have a similar issue which seems to be related to this one. Using function chaining in a macro produced the exact same error message for me. For example,
```
CREATE OR REPLACE TEMP MACRO
    SINGLE_SPACE (VALUE) AS
VALUE.REGEXP_REPLACE('( ){2,}', ' ', 'g')
;
SELECT
        SINGLE_SPACE('HELLO     THERE')
    AS RESULT
;
```
```
Catalog Error: Scalar Function with name regexp_replace does not exist! Did you mean "main.regexp_replace"? LINE 3: AS RESULT
```

**Comment by douenergy** [comment]
@chris-dailey  

```sql 
CREATE OR REPLACE TEMP MACRO
     SINGLE_SPACE (VALUE) AS
 (VALUE).REGEXP_REPLACE(' {2,}', ' ', 'g')
 ;

SELECT SINGLE_SPACE('HELLO     THERE') AS RESULT ;
```

Adding parentheses around the `VALUE` .   This should work !

**Comment by douenergy** [comment]
@Alex-Monahan  I have a patch fix this. I'll finish this weekend
