### ISSUE TITLE
Clearing fsspec filesystem caches segfaults Python runtime

### ISSUE THREAD

**Issue by nicholasjng** [duckdb/duckdb#11875]
### What happens?

As per title. Minimal repro below (only needs duckdb>=0.10.1 and fsspec installed).

This reproduces on my local machine (MacOS ARM64) as well as in Linux GitHub CI, I'm not sure about Windows.

I believe this is a pybind11 return value policy bug - currently, there are no return policies configured for any of the bound `DuckDBPyConnection` APIs, so pybind11 takes ownership of each file system passed from Python. This seems fine in general, unless Python file systems are destroyed in the meantime, which is the case here through a cache eviction.

Source: https://github.com/duckdb/duckdb/blob/f8715b2de031312cba3ac4d800407573f03a443c/tools/pythonpkg/src/pyconnection.cpp#L131-L138

Unless there are other intricacies of which I am not aware, setting the return policy to `py::return_value_policy::reference` should fix this issue.

Return value policies docs for pybind: https://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies

PS: I'm happy to help work on this if there is interest.

PPS: Here is the Apple crash report stack trace, showing conclusively that pybind attempts to dealloc the file system in the connection cleanup.

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Python                        	       0x1051cfee0 list_dealloc + 256
1   Python                        	       0x10521a50c subtype_dealloc + 668
2   duckdb.cpython-312-darwin.so  	       0x109ea4f00 duckdb::PythonFilesystem::~PythonFilesystem() + 64
3   duckdb.cpython-312-darwin.so  	       0x108e7c75c duckdb::VirtualFileSystem::~VirtualFileSystem() + 192
4   duckdb.cpython-312-darwin.so  	       0x108e7a058 duckdb::VirtualFileSystem::~VirtualFileSystem() + 12
5   duckdb.cpython-312-darwin.so  	       0x109a08804 duckdb::DBConfig::~DBConfig() + 912
6   duckdb.cpython-312-darwin.so  	       0x109a08d18 duckdb::DatabaseInstance::~DatabaseInstance() + 388
7   duckdb.cpython-312-darwin.so  	       0x1099f0a10 duckdb::ClientContext::~ClientContext() + 276
8   duckdb.cpython-312-darwin.so  	       0x109a02fc0 duckdb::Connection::~Connection() + 100
9   duckdb.cpython-312-darwin.so  	       0x109e52ec0 duckdb::DuckDBPyConnection::~DuckDBPyConnection() + 104
10  duckdb.cpython-312-darwin.so  	       0x109e6f858 duckdb::DuckDBPyConnection::Cleanup() + 132
11  Python                        	       0x1051a85a8 capsule_dealloc + 64
12  Python                        	       0x1051e58e8 dictkeys_decref + 172
13  Python                        	       0x1051e8880 dict_dealloc + 240
14  Python                        	       0x1052ccb98 _PyImport_ClearModulesByIndex + 236
15  Python                        	       0x1052e6f90 finalize_modules + 1616
16  Python                        	       0x1052e65e8 Py_FinalizeEx + 196
17  Python                        	       0x105311174 Py_RunMain + 380
18  Python                        	       0x1053114b0 Py_BytesMain + 40
19  dyld                          	       0x180f0e0e0 start + 2360
```

### To Reproduce

```python
import duckdb
from fsspec.implementations.local import LocalFileSystem

def main():
    loc = LocalFileSystem()
    duckdb.register_filesystem(loc)
    loc.clear_instance_cache()
    return 0

if __name__ == "__main__":
    main()
```

### OS:

macOS 14.4.1

### DuckDB Version:

\>=0.10.1

### DuckDB Client:

Python

### Full Name:

Nico Junge

### Affiliation:

appliedAI Institute gGmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! Should be fixed now in https://github.com/duckdb/duckdb/pull/11980
