### ISSUE TITLE
JSON_GROUP_STRUCTURE is now (incorrectly?) case sensitive

### ISSUE THREAD

**Issue by ankrgyl** [duckdb/duckdb#11886]
### What happens?

```
select json_group_structure(json('{"a": 1, "A": 1}'));
```

now returns

```
Invalid Input Error: Duplicate key "A" in object {"a":1,"A":1}
```

This did not repro with 10.1

### To Reproduce

see above

### OS:

mac os x, wasm, etc

### DuckDB Version:

v0.10.2

### DuckDB Client:

all

### Full Name:

Ankur Goyal

### Affiliation:

Braintrust

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
Hi @ankrgyl, we use the same function to auto-detect the schema in our JSON reader. DuckDB is case-insensitive, and duplicate column names are not allowed in tables/structs, so this behavior is the result of a fix (https://github.com/duckdb/duckdb/pull/11271).

The `json_structure` function is just a function that exposes this automatic type detection, so its behavior also changed.

There are two options, we can either:
1. Throw the error (like we do now)
2. Ignore the error (like when using `ignore_errors=true` in our JSON reader) and return the first encountered `"a"`, i.e.,`{"a":"UBIGINT"}`

**Comment by ankrgyl** [comment]
Thanks for the clarification. In our case, we actually use `json_group_structure` _without_ using `json_transform`. Specifically, we:

* Call `json_group_structure` to find the distinct set of fields
* Populate a UI dropdown based on those fields
* If the user selects one of the subfields, run a query using `json_extract` (which is case sensitive) to project / group by it

So my preference would be #2. One suggestion could be that `json_transform` could error if you try to use it with something like `{"a":"UBIGINT","A":"UBIGINT"}`, or you could have a flag to `json_group_structure` which allows you to pick your adventure.

**Comment by lnkuiper** [comment]
Thanks, I've sent out a PR that fixes this for `json_structure` specifically, without changing the behavior of our JSON reader.

**Comment by ankrgyl** [comment]
Appreciate it!
