### ISSUE TITLE
Quarter doesn't work as interval in window functions

### ISSUE THREAD

**Issue by aszenz** [duckdb/duckdb#11892]
### What happens?

The docs mentions that quarter is supported as a date interval, but using it in a query like this fails:

```sql
select
 count(*) over(order by departure_time asc range between 1 quarter preceding and interval 1 quarter following) 
from train_services
limit 1
```

### To Reproduce

https://shell.duckdb.org/#queries=v0,%20%20-Create-table-from-Parquet-file%0ACREATE-TABLE-train_services-AS%0A----FROM-'s3%3A%2F%2Fduckdb%20blobs%2Ftrain_services.parquet'~,%20%20-Get-the-top%203-busiest-train-stations%0ASELECT-station_name%2C-count(*)-AS-num_services%0AFROM-train_services%0AGROUP-BY-ALL%0AORDER-BY-num_services-DESC%0ALIMIT-3~,select-count(*)-over-(order-by-departure_time-asc-range-between-1-quarter-preceding-and-interval-1-quarter-following)-limit-1~,select-count(*)-over-(order-by-departure_time-asc-range-between-interval-1-quarter-preceding-and-interval-1-quarter-following)-limit-1~

### OS:

x64

### DuckDB Version:

0.10.2

### DuckDB Client:

WASM

### Full Name:

asrar

### Affiliation:

qbil

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Are you not just missing the `INTERVAL` keyword at the start of your range?

**Comment by aszenz** [comment]
> Are you not just missing the `INTERVAL` keyword at the start of your range?

I had tried adding it but it still errors out, see the shell link
