### ISSUE TITLE
Upsert complains about lack of constrains despite the fact they are present

### ISSUE THREAD

**Issue by jhabermas** [duckdb/duckdb#11911]
### What happens?

Trying to upsert into a table with primary key / unique constraint results in an error:
`BinderException: Binder Error: The specified columns as conflict target are not referenced by a UNIQUE/PRIMARY KEY CONSTRAINT`
The same query works fine when using psycopg2 or in an SQL client.

### To Reproduce

Minimal reproducible example:
```Python
conn.sql(
    f"""
        DROP TABLE IF EXISTS meta_test;

        CREATE TABLE meta_test (
            id TEXT NOT NULL UNIQUE,                
            last_ts TIMESTAMPTZ,
            first_ts TIMESTAMPTZ,
            PRIMARY KEY (id),
        );            
    """
)

conn.sql(
    f"""
        INSERT INTO meta_test (id, last_ts, first_ts)
        VALUES ('uuid42', NULL, NULL)
        ON CONFLICT (id)
        DO UPDATE 
        SET last_ts = NULL
        """
)

```

### OS:

Windows

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Jurgen Habermas

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
```py
import duckdb
conn = duckdb.connect()

conn.sql(
    f"""
        DROP TABLE IF EXISTS meta_test;

        CREATE TABLE meta_test (
            id TEXT NOT NULL UNIQUE,                
            last_ts TIMESTAMPTZ,
            first_ts TIMESTAMPTZ,
            PRIMARY KEY (id),
        );            
    """
)

conn.sql(
    f"""
        INSERT INTO meta_test (id, last_ts, first_ts)
        VALUES ('uuid42', NULL, NULL)
        ON CONFLICT (id)
        DO UPDATE 
        SET last_ts = NULL
        """
)
```

runs without problems

**Comment by Tishj** [comment]
```sql
statement ok
CREATE TABLE meta_test (
	id TEXT NOT NULL UNIQUE,
	last_ts TIMESTAMPTZ,
	first_ts TIMESTAMPTZ,
	PRIMARY KEY (id),
);

statement ok
INSERT INTO meta_test (id, last_ts, first_ts)
VALUES ('uuid42', NULL, NULL)
ON CONFLICT (id)
DO UPDATE
SET last_ts = NULL

statement ok
INSERT INTO meta_test (id, last_ts, first_ts)
VALUES ('uuid42', NULL, NULL)
ON CONFLICT (id)
DO UPDATE
SET last_ts = NULL

query III
select * from meta_test;
----
uuid42	NULL	NULL
```

also runs without problems

**Comment by jhabermas** [comment]
Could it be postgres extension specific then?

Here's my connection setup:
`
duckdb.install_extension("postgres")
duckdb.load_extension("postgres")

def postgres_connection(tz="UTC"):
    db_config = settings[env_settings.ts_datastore]
    conn = duckdb.connect(
        f"postgres:user={db_config.user} password={db_config.password} host={db_config.host} dbname={db_config.db_name}"
    )
    conn.sql(f"SET timezone to '{tz}'")
    return conn
`

**Comment by Tishj** [comment]
https://github.com/duckdb/postgres_scanner/issues/189
