### ISSUE TITLE
Compilation warnings in re2 with `-Wpedantic`

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#11917]
### What happens?

Building duckdb v0.10.2 with `-Wpedantic` gives four warnings in re2:

```
  duckdb/third_party/re2/re2/prog.h:148:14: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  duckdb/third_party/re2/re2/prog.h:426:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  duckdb/third_party/re2/re2/dfa.cc:124:25: warning: ISO C++ forbids flexible array member ‘next_’ [-Wpedantic]
  duckdb/third_party/re2/re2/onepass.cc:146:12: warning: ISO C++ forbids flexible array member ‘action’ [-Wpedantic]
```

This affects the R package because CRAN checks this: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/duckdb-00check.html

### To Reproduce

Compile duckdb with gcc13 and `-Wpedantic` .

### OS:

Linux

### DuckDB Version:

v0.10.2

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by krlmlr** [comment]
@szarnyasg: Thanks for looking into it.

In gcc14, there are even more warnings:

```
    /usr/local/gcc14/include/c++/14.0.1/bits/move.h:221:11: warning: '((__vector(2) long unsigned int*)this)[1]' is used uninitialized [-Wuninitialized]
    /usr/local/gcc14/include/c++/14.0.1/bits/move.h:221:11: warning: '*(__vector(2) long unsigned int*)this' is used uninitialized [-Wuninitialized]
    /usr/local/gcc14/include/c++/14.0.1/bits/move.h:221:11: warning: '((void (**)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >))this)[2]' is used uninitialized [-Wuninitialized]
    /usr/local/gcc14/include/c++/14.0.1/bits/move.h:221:11: warning: '((duckdb::FileBuffer**)this)[2]' is used uninitialized [-Wuninitialized]
```

Check results: https://cran.r-project.org/web/checks/check_results_duckdb.html

**Comment by hannes** [comment]
The first two issues are easily fixable, but found this comment:

```C++
// Work around the bug affecting flexible array members in GCC 6.x (for x >= 1).
// (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70932)
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ == 6 && __GNUC_MINOR__ >= 1
    std::atomic<State*> next_[0];   // Outgoing arrows from State,
#else
    std::atomic<State*> next_[];    // Outgoing arrows from State,
#endif
```

So this seems intentional to work around a GCC bug?

**Comment by hannes** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70932

**Comment by hannes** [comment]
second PR is here: https://github.com/duckdb/duckdb/pull/11978

**Comment by hannes** [comment]
@krlmlr do we have a CI run already that would have found those?

**Comment by krlmlr** [comment]
Yes. Easiest when that PR is merged and vendored here.

**Comment by hannes** [comment]
Fixed in upstream

**Comment by krlmlr** [comment]
Looks super-green now: https://github.com/duckdb/duckdb-r/actions/runs/9162129815/job/25188491799 .

Filed the clang-asan problem: https://github.com/duckdb/duckdb/issues/12142 .

The atlas check is not a problem.

I don't understand why valgrind still finds problems. Investigating.
