### ISSUE TITLE
'Duplicate key' error when update column with list data type and table has a primary key

### ISSUE THREAD

**Issue by lpfy** [duckdb/duckdb#11915]
### What happens?

This behaviour happens for both Python and WASM (https://shell.duckdb.org/) environments. There is no way to update the column with the list data type and the table has a primary key. The UPDATE query always return 'Duplicate key' error.

### To Reproduce

```
create or replace table test (
	aid INT, 
        comments TEXT,
	alist STRUCT(username VARCHAR, lid INT)[],
	PRIMARY KEY (aid)
);

insert into test select 1, 'abc', [{username:'t1',lid:1},{username:'t2',lid:2}];
insert into test select 2, 'def', [{username:'t3',lid:3},{username:'t4',lid:4}];
UPDATE test SET comments = 'test test' WHERE aid = 1;
UPDATE test SET alist = [{username:'t5',lid:5},{username:'t6',lid:6}] WHERE aid = 1;
```
the last update query will return the following error:

`Constraint Error: Duplicate key "aid: 1" violates primary key constraint. If this is an unexpected constraint violation please double check with the known index limitations section in our documentation (docs - sql - indexes).`

I am not updating the primary key column, and the comments column can be updated, just the column with list data type is causing the problem.

### OS:

Browser / Windows / Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

WASM or Python

### Full Name:

Sasha Zhang

### Affiliation:

Unisa

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @lpfy, thanks for raising this issue. As described in [this (quite well-hidden) comment](https://github.com/duckdb/duckdb/issues/11383#issuecomment-2064271279), updates on lists are implemented as as sequence of delete and insert operations, which can trigger duplicates. I'll update this in the documentation.

**Comment by lpfy** [comment]
@szarnyasg Thanks, I have noticed the new documentation is live. https://duckdb.org/docs/sql/data_types/list

**Comment by karlseguin** [comment]
@szarnyasg  can you update the documentation at https://duckdb.org/docs/sql/indexes#over-eager-unique-constraint-checking? This is the page that the error message points to (not the list page):

> ...If this is an unexpected constraint violation please double check with the known index limitations section in our documentation (https://duckdb.org/docs/sql/indexes)

Furthermore, the documentation on the index page implies that these limitations are on updates to the constrained columns themselves:

> For example, in the following query, SET id = 1 causes a Constraint Error to occur

However, this error seems to greatly expand on the possible cause for such errors and it would be nice to know all types/cases where updates are turned into deletes and inserts, and to have this in 1 single place. Right now, we know that: (a) updating a column with a constraint and (b) updating a list. Are there more?
