### ISSUE TITLE
PIVOT does not support geomean as aggregation function

### ISSUE THREAD

**Issue by AlexHelloWorld** [duckdb/duckdb#11922]
### What happens?

`PIVOT` does not allow `geomean` to be used as a valid aggregation function.

### To Reproduce

```sql
CREATE TABLE train_services AS FROM 'http://blobs.duckdb.org/train_services.parquet';
PIVOT train_services
ON type
USING geomean(train_number)
GROUP BY station_code
LIMIT 3; 
```
returns the following error:
```
Catalog Error: geomean is not an aggregate function
```

### OS:

e.g. wasm

### DuckDB Version:

v0.10.2, @duckdb/duckdb-wasm@1.28.1-dev190.0

### DuckDB Client:

http://shell.duckdb.org

### Full Name:

Hongyu Shi

### Affiliation:

benchling

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by AlexHelloWorld** [comment]
In addition to `PIVOT`, `WINDOW` function also doesn't seem to support `geomean`

**Comment by szarnyasg** [comment]
Hi @AlexHelloWorld, thanks for reporting this issue. This is currently an expected restriction as `geomean(x)` is substituted with `exp(avg(ln(x))`. As a workaround, you can perform this operation manually by first computing the natural logarithm `ln`, then doing the `PIVOT` operation with `avg` and finally performing the `e^` part with `exp`.
