### ISSUE TITLE
`CAST( 'yes' AS BOOLEAN)` fails

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11925]
### What happens?

`CAST( 'yes' AS BOOLEAN)` fails, when all other RDBMS support it.
Same for `no` of course.

### To Reproduce

```sql
-- Conversion Error: Could not convert string 'yes' to BOOL
SELECT Cast('yes' AS BOOLEAN);
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Python casts "yes" and "no" both to True. Best to not pick a siade. I prefer there being no cast at all and requiring the user to write down themselves what strings they consider "truths". For example, you might be interested in yes/no parsing, the next person might be interested in True/False parsing, the next person in Y/N, the next person in non-empty vs empty string, the next person in string vs null.

**Comment by hannes** [comment]
SQLite casts to false (0)

**Comment by manticore-projects** [comment]
> SQLite casts to false (0)

I can't argue about that because it really depends what DuckDB is aiming for. My recommendation was to aim for H2 or HyperSQL at least and most time you refer to Postgres yourself. (SQLLite and MySQL are less appealing to me.)

We can close this issue immediately. I just write down things I notice while going through all DuckDB functions systematically. Your call please.
