### ISSUE TITLE
`Round()` and `Round_Even()` return different type

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11930]
### What happens?

`Round()` returns `Decimal` while `Round_Even` returns `Double`.
It should be consistent, especially since you made casting must more strict and explicit in 0.10

### To Reproduce

```sql

-- expected
SELECT typeof(ROUND(2.5, 0)) AS r1, typeof(ROUND_EVEN(2.5, 0)) AS r2;

-- result
/*
┌──────────────┬────────┐
│ r1           │ r2     │
├──────────────┼────────┤
│ DECIMAL(2,0) │ DOUBLE │
└──────────────┴────────┘
*/
```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by hannes** [comment]
The round function predates the decimal type, so that's probably why. I agree it should be consistent though.
