### ISSUE TITLE
Shadowing of variable names in Python

### ISSUE THREAD

**Issue by davidjbrennan** [duckdb/duckdb#11945]
### What happens?

In builds subsequent to 10.2, names from the duckdb module appear to be shadowing Python variables when used in queries. 

### To Reproduce

When I use a variable name for a dataframe in an SQL query that happens to be the name of some function in the duckdb module, I run in to the following problem. I'm using the variable name "df" in this case but I could have use "pl" or "arrow" or many other to reproduce the same error.

```python
import pandas as pd
import duckdb

df = pd.DataFrame({"a":[1,2,3]})
duckdb.sql("from df")
```
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/venv/lib/python3.12/site-packages/duckdb/__init__.py", line 455, in sql
    return conn.sql(query, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Python Object "df" of type "builtin_function_or_method" found on line "/Users/username/venv/lib/python3.12/site-packages/duckdb/__init__.py:455" not suitable for replacement scans.
Make sure that "df" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format
```
When I use a variable name for the dataframe that is not visible in the duckdb module then there are no problems.

```python
pdf = df
duckdb.sql("from pdf")
```
```
┌───────┐
│   a   │
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
```

### OS:

MacOS Sonama 14.4.1 (silicon)

### DuckDB Version:

0.10.3-dev777

### DuckDB Client:

Python

### Full Name:

David Brennan

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Might be related to #11202 actually, since it shows up in `duckdb.sql`

**Comment by Mytherin** [comment]
Can we perhaps ignore objects of type `builtin_function_or_method` in replacement scans instead? That seems less likely to produce future problems
