### ISSUE TITLE
`REGEXP_REPLACE` replaces only the first match without any option for all matches

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11942]
### What happens?

`REGEXP_REPLACE`  should replace all matches (like all other RDBMS do), especially since there is no alternative way to replace all matches. Also, the documentation is not clear about this and the provided example does not illustrate this behavior. (So I am not sure if this was a bug or a feature.)

### To Reproduce

```sql
SELECT regexp_replace('100-200', '(\d+)', 'num') AS s;

-- result
"s"
"num-200"

-- result
"s"
"num-num"

```

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@manticore-projects the global (`g`) flag works:

```sql
D SELECT regexp_replace('100-200', '(\d+)', 'num', 'g') AS s;
┌─────────┐
│    s    │
│ varchar │
├─────────┤
│ num-num │
└─────────┘
```

**Comment by manticore-projects** [comment]
Sorry, its partially my fault -- because the flag is not shown in the function table, but only when you scroll down. (I thought I added this last week already, but I seem to mix things up.)

Thank you for pointing me on it.
