### ISSUE TITLE
Boolean implicitly cast to integer in UNION clause

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#11958]
### What happens?

Booleans are implicitly cast to integers in `UNION` clauses. 
This contradicts a statement made by @Mytherin at https://github.com/duckdb/duckdb/issues/7011#issuecomment-1501441330 so is likely a bug. If it's not a bug, I will update my documentation PR at https://github.com/duckdb/duckdb-web/pull/2830 to reflect the correct rules.

Note that booleans aren't implicitly casted to integers in other contexts, e.g., the following query fails:
```sql
SELECT 1::BOOLEAN + 1::INT
```

in accordance with https://duckdb.org/docs/sql/data_types/typecasting#implicit-casting.

### To Reproduce

```sql
SELECT 1::BOOLEAN UNION ALL SELECT 1::INT
```

| CAST(1 AS BOOLEAN) |
|--------------------|
| 1                  |
| 1                  |

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

CLI

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
As discussed in the documentation PR (https://github.com/duckdb/duckdb-web/pull/2830), this is expected behaviour.

**Comment by soerenwolfers** [comment]
@szarnyasg I'm confused. On the documentation PR, which you merged, I'm stating the UNION ALL is performing implicit casts only. 

In the issue here, I'm complaining that UNION ALL performs more than that, because BOOL is not usually implicitly castable to integer types (as evidenced by the attempt to add bool and integer, and by the linked casting matrix)

**Comment by soerenwolfers** [comment]
But the expected behavior really is that the casting rules in the UNION ALL clause are different from those anywhere else?

**Comment by soerenwolfers** [comment]
Issue still persists on 1.0.0

**Comment by soerenwolfers** [comment]
documented as expected behavior in duckdb/duckdb-web#4222
