### ISSUE TITLE
Python: Package pytz not included

### ISSUE THREAD

**Issue by thiagola92** [duckdb/duckdb#11974]
### What happens?

Can't use `current_timestamp` with duckdb python package.  
Not sure if this is intended.  

### To Reproduce

```python
import duckdb
duckdb.execute("SELECT current_timestamp").fetchone()
```
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.InvalidInputException: Invalid Input Error: Required module 'pytz' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pytz'
```

Solution:  
`pip install pytz`  

```python
import duckdb
duckdb.execute("SELECT current_timestamp").fetchone()
```
```text
(datetime.datetime(2024, 5, 8, 6, 57, 59, 485000, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>),)
```

### OS:

Ubuntu 23.10, 64-bit, X11, Linux 6.5.0-28-generic

### DuckDB Version:

0.10.2

### DuckDB Client:

Python 3.11.6

### Full Name:

Thiago Lages de Alencar

### Affiliation:

None (looking for job)

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Yes that's intended:
```c++
		if (type.id() == LogicalTypeId::TIMESTAMP_TZ) {
			// We have to add the timezone info
			auto tz_utc = import_cache.pytz.timezone()("UTC");
			auto timestamp_utc = tz_utc.attr("localize")(py_timestamp);
			auto tz_info = import_cache.pytz.timezone()(client_properties.time_zone);
			return timestamp_utc.attr("astimezone")(tz_info);
		}
```
We need pytz to be able to convert the value to the right python type

**Comment by thiagola92** [comment]
Sorry, I meant "It's intended not being included in the package?"  
Take in count that duckdb is suppose to be light, this would make sense but I wasn't sure.

**Comment by Tishj** [comment]
Yes that's intended, we don't include dependencies in the package
You could circumvent this issue by casting the TIMESTAMPTZ column to VARCHAR, or TIMESTAMP if you prefer not to install `pytz`

**Comment by thiagola92** [comment]
> Yes that's intended, we don't include dependencies in the package You could circumvent this issue by casting the TIMESTAMPTZ column to VARCHAR, or TIMESTAMP if you prefer not to install `pytz`

No problem at all, I can totally install pytz.  
For some reason I though that datetime conversion would be standard and was not expecting an error.  

As this is expected, I'm closing this.

**Comment by soerenwolfers** [comment]
@Tishj what's the reason for not specifying dependencies, if I may ask? Users that don't want dependencies to be installed can already use `--no-deps` in pip or equivalent options elsewhere. Alternatively, you could provide a `duckdb[full]` installation option for users to opt into dependencies.
