### ISSUE TITLE
No comma separator writing list to csv in python

### ISSUE THREAD

**Issue by Dtenwolde** [duckdb/duckdb#11983]
### What happens?

In a Python environment, when writing a column with the type list to CSV, there is no comma written between elements of the list. 

### To Reproduce

```python
import duckdb
duckdb.sql("select [1,2,3]").df().to_csv("no_comma_separator.csv", index=False)
```
Results in the following file: 
```
"main.list_value(1, 2, 3)"
[1 2 3]
```

### OS:

macOs 13 - Apple M1 Pro

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Daniel ten Wolde

### Affiliation:

CWI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I think that's a Pandas issue, no?

**Comment by Dtenwolde** [comment]
I don't understand how that'd be a Pandas issue. Printing the result of `duckdb.sql("select [1,2,3]").df()` gives the expected result. Doing a similar thing in Pandas:

```python
import pandas as pd

data = [
    ["Alice", 25, ["Marketing", "Social Media"]],
    ["Bob", 30, ["Sales", "Business Development"]],
    ["Charlie", 28, ["Engineering", "Software Development"]]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Department"])
df.to_csv("pandas.csv")
```
Results in the following file with correct output: 
```
,Name,Age,Department
0,Alice,25,"['Marketing', 'Social Media']"
1,Bob,30,"['Sales', 'Business Development']"
2,Charlie,28,"['Engineering', 'Software Development']"
```

**Comment by szarnyasg** [comment]
@Dtenwolde thanks for raising the issue. @Tishj 

```python
import duckdb
import pandas as pd

df1 = pd.DataFrame([[[1, 2, 3]]], columns=["c1"])
print(df1)
df1.to_csv("df1.csv", index=False)

df2 = duckdb.sql("select [1,2,3] AS c1").df()
print(df2)
df2.to_csv("df2.csv", index=False)
```

outputs:

```python
>>> print(df1)
          c1
0  [1, 2, 3]
```

```python
>>> print(df2)
          c1
0  [1, 2, 3]
```

df1.csv:

```
c1
"[1, 2, 3]"
```

df2.csv:

```
c1
[1 2 3]
```

**Comment by Tishj** [comment]
Ah interesting, I just meant you are using pandas's `to_csv` method of the DataFrame class, that's not our CSV writer that's being used here.

Perhaps the way we construct the lists that make up the produced DataFrame are different, which is causing their csv writer to act up?

**Comment by Tishj** [comment]
I still think this is a pandas issue, I can't imagine it's intended that numpy arrays are written differently than native lists

**Comment by Dtenwolde** [comment]
I found this https://github.com/pandas-dev/pandas/issues/48478 which seems related,  and if I understand correctly it is their intentional way of writing arrays. 
Conversely (and out of curiosity), what is the reason DuckDB converts lists to `numpy.ndarray` instead of `list`

**Comment by Tishj** [comment]
Performance
Arrays can be preallocated and the same methods we use to populate a column can be used to populate the LIST/ARRAY conversion

**Comment by Tishj** [comment]
Perhaps we can try creating a `list` out of the numpy array and see if that comes with any severe performance impact
If it doesn't then I'm fine restoring the old behavior that way
