### ISSUE TITLE
Can't load Pandas Datetime

### ISSUE THREAD

**Issue by jrdzha** [duckdb/duckdb#11993]
### What happens?

Loading a pandas datetime causes unknown time zone issue. This breaks for `pandas==2.2.2` and `duckdb==0.10.2`, but works for `pandas==2.2.2` and `duckdb==0.8.1`.

### To Reproduce

```bash
python3 -m pip install pandas==2.2.2 duckdb==0.10.2
```

```python
import duckdb
import pandas as pd

df = pd.DataFrame({
    "a": ["2024-03-19 16:27:00-04:00", "2024-03-19 16:27:00-04:00", "2024-03-19 16:27:00-04:00"]
})

df["a"] = pd.to_datetime(df["a"])

conn = duckdb.connect(":memory:")
conn.register("df", df)
conn.execute("SELECT * FROM df").fetchdf()
```

### OS:

x86 Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Jared Zhao

### Affiliation:

Athenic

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
You didn't include an error message

**Comment by szarnyasg** [comment]
@jrdzha I did not get an error when running the reproduction script.
