### ISSUE TITLE
duckdb的0.10.2版本用VS2019编译成功了，debug版本库嵌入到Qt项目中程序运行报错

### ISSUE THREAD

**Issue by luxtzy** [duckdb/duckdb#12001]
### What happens?

用VS2019编译了0.10.2版本成功了，duckdb的release库可以在Qt项目中正常编译运行，debug模式的库能在Qt中成功编译，运行的时候报无法找到程序输入点，请帮忙解答一下，谢谢！

### To Reproduce

是在Qt pro文件中引用，拷贝duckdb.dll到执行文件下面，运行exe弹窗报无法定位程序输入点，其他Qt依赖库都在执行文件所在目录

### OS:

win10

### DuckDB Version:

0.10.2

### DuckDB Client:

Qt

### Full Name:

luis

### Affiliation:

song

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by hawkfish** [comment]
>What happens?  I successfully compiled version 0.10.2 with VS2019. The release library of duckdb can be compiled and run normally in the Qt project. The library in debug mode can be successfully compiled in Qt. When running, it reports that the program input point cannot be found. Please help me answer. Thanks!

> To reproduce: It is referenced in the Qt pro file. Copy duckdb.dll to the executable file. When running the exe, a pop-up window will report that the program input point cannot be located. Other Qt dependent libraries are in the directory where the executable file is located.

**Comment by luxtzy** [comment]
我的意思是，debug模式下，用duckdb的库，Qt项目跑不起来，直接弹窗提示"无法找到程序输入点"，但是release模式下，Qt项目能跑起来，或许您方便提供Qt demo调用duckdb的库参考么，谢谢！




------------------ 原始邮件 ------------------
发件人: "Richard ***@***.***&gt;; 
发送时间: 2024年5月12日(星期天) 凌晨5:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [duckdb/duckdb] duckdb的0.10.2版本用VS2019编译成功了，debug版本库嵌入到Qt项目中程序运行报错 (Issue #12001)















会怎么样我成功地用VS2019编译了0.10.2版本。duckdb的发布库可以在Qt项目中编译和正常运行。调试模式下的库可以在Qt中成功编译。运行时，它会报告找不到程序输入点。请帮我解答一下。谢了！

复制:在Qt pro文件中引用它。将duckdb.dll复制到可执行文件。exe运行时，会弹出一个窗口，报告程序输入点找不到。其他Qt相关库位于可执行文件所在的目录中。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:<鸭子/鸭子/问题/ 12001 / ***@***.***和&gt;

**Comment by szarnyasg** [comment]
Hi @luxtzy, unfortunately, debug builds are [out of scope according to our support policy](https://duckdblabs.com/news/2023/10/02/support-policy#debug-builds). There are some 3rd party QT examples available, e.g., https://github.com/chilarai/qt-duckdb.
