### ISSUE TITLE
INTERNAL Error: Time With Time Zone logicalType is set but unit is not defined

### ISSUE THREAD

**Issue by sspaeti** [duckdb/duckdb#12041]
### What happens?

I have an exported Parquet file that I can't query with DuckDB as I get the error mentioned in the title. I narrowed it down to data type `TIME` (see examples below). Pandas can read it fine.

#### Example DuckDB

First I query the parquet with only one column ` pruefbahn_id` --> No problem.
Second, I added the problematic column `arbeits_beginn`, which is a data type `TIME` in the source Postgres database and now I get the error `INTERNAL Error: Time With Time Zone logicalType is set but unit is not defined`:

```bash
❯ duckdb
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
select pruefbahn_id from 'hd_pruefbahn.minimal_example.parquet' where pruefbahn_id = '58981';
```
```text
┌──────────────┐
│ pruefbahn_id │
│    int32     │
├──────────────┤
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
│        58981 │
├──────────────┤
│   15 rows    │
└──────────────┘
```
```sql
select pruefbahn_id, arbeits_beginn from 'hd_pruefbahn.minimal_example.parquet' where pruefbahn_id = '58981';
```
```text
Error: INTERNAL Error: Time With Time Zone logicalType is set but unit is not defined
```
```sql
select pruefbahn_id, arbeits_beginn from 'hd_pruefbahn.minimal_example.parquet' where pruefbahn_id = '70125';
```
```text
Error: INTERNAL Error: Time With Time Zone logicalType is set but unit is not defined
```

#### Example with Pandas:
If I read the same file with Pandas, I do not get any error with the timestamp. The columns contains None (NULL) and nano seconds. 

Side-note: We had other problems with nanosecond with exporting Parquet with [Connector-X](https://github.com/sfu-db/connector-x) when the timestamp was `9999-12-31 23:59:59.999999`.  But as we converted these to NULL, we were left with below `TIME` fields that caused an error.

```bash
❯ python
Python 3.9.15 (main, Dec  1 2022, 23:05:41)
[Clang 15.0.5 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
```python
import pandas as pd
import pandasql as ps

df = pd.read_parquet('hd_pruefbahn.minimal_example.parquet')
ps.sqldf("select pruefbahn_id, arbeits_beginn from df", locals())
```
```text
pruefbahn_id   arbeits_beginn
0          58981  07:20:00.000000
1          58981  07:20:00.000000
2          58981  07:20:00.000000
3          58981  07:20:00.000000
4          58981  07:20:00.000000
5          58981  07:20:00.000000
6          58981  07:20:00.000000
7          58981  07:20:00.000000
8          58981  07:20:00.000000
9          58981  07:20:00.000000
10         58981  07:20:00.000000
11         58981  07:20:00.000000
12         70125             None
13         58981  07:20:00.000000
14         70125             None
15         58981  07:20:00.000000
16         58981  07:20:00.000000
17         70125             None
18         70125             None
19         70125             None
```

Here's a minimal file used above to reproduce this error (I had to zip it as parquet wasn't allowed):
[hd_pruefbahn.minimal_example.parquet.zip](https://github.com/duckdb/duckdb/files/15305862/hd_pruefbahn.minimal_example.parquet.zip)

### OS:

MacOS, arm64

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

Python 3.9.15 (main, Dec  1 2022, 23:05:41)

### Full Name:

Simon Späti

### Affiliation:

Bedag Solution AG

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, I could reproduce the error. We'll take a look.

**Comment by sspaeti** [comment]
Amazing how fast this got fixed, thank you so much. Looking forward to testing it with the next release of DuckDB.
