### ISSUE TITLE
Creating DuckDB in-memory connection throws exception [Java API]

### ISSUE THREAD

**Issue by grjzwaan** [duckdb/duckdb#12113]
### What happens?

When executing the following snippet in a Tomcat server I get an exception:
```java
Class.forName("org.duckdb.DuckDBDriver");
DuckDBConnection conn = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:");
```

Exception:
```
java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\Program Files (x86)\apache-tomcat-9.0.69\temp\libduckdb_java16991498082687051807.so [in thread "http-nio-8080-exec-10"]
```

Stacktrace:
```
0 = {StackTraceElement@12379} "org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:48)"
1 = {StackTraceElement@12380} "org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:41)"
2 = {StackTraceElement@12381} "java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)"
3 = {StackTraceElement@12382} "java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)"
```

I followed the instruction/installation of duckdb on the website and included it as a maven dependency:
```xml
<dependency>
	<groupId>org.duckdb</groupId>
	<artifactId>duckdb_jdbc</artifactId>
	<version>0.10.2</version>
</dependency>
```

### To Reproduce

```java
Class.forName("org.duckdb.DuckDBDriver");
DuckDBConnection conn = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:");
```

Tomcat 9
Windows 11

### OS:

Windows 11 Pro

### DuckDB Version:

10.2

### DuckDB Client:

Java

### Full Name:

Ruben van der Zwaan

### Affiliation:

Personal project

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mause** [comment]
The issue here is that the process doesn't have access to write to the configured temporary directory for some reason, so I'd suggest looking into that

**Comment by grjzwaan** [comment]
Aah...apologies! Makes total sense, and I've got it working.

I was somehow completely thrown for a loop by the attempt to open/create an `libduckdb.so` in the temporary folder under windows, and stopped thinking.
