### ISSUE TITLE
[Question]: is there any graphical client to be used by non-tech?

### ISSUE THREAD

**Issue by verajosemanuel** [duckdb/duckdb#1216]
I use extensively duckdb for my analytics but I need to share my database with some of my clients.
They do not know any programming language so they need a client software to open database.

is there any software available to open duckdb database?

thanks in advance

**Comment by hannesmuehleisen** [comment]
Could you describe that use case a bit more? What does "open" mean in this case? Look at data in tables?

**Comment by verajosemanuel** [comment]
yes, imagine another colleague from marketing department. Usually lives in windows, Word, Excel, Access, web browser...and the like

I can share the DuckDB file via shared folder and they want to open the file and have look at the tables and content, maybe issue some simple SQL queries at most

**Comment by Mause** [comment]
I have thrown together a very basic sqlalchemy driver for duckdb (https://pypi.org/projects/duckdb_engine), you could probably find a program that uses that to display the data contained in your database?

**Comment by verajosemanuel** [comment]
thanks @Mause but the users are non techies, and they cannot request suppor from me or IT on this matter

**Comment by Mause** [comment]
I mean that you could find a UI that supports sqlalchemy, and use that with the above

**Comment by verajosemanuel** [comment]
something like this:
https://sqlitebrowser.org/

**Comment by verajosemanuel** [comment]
anyone?

**Comment by hannesmuehleisen** [comment]
@verajosemanuel I am not aware of anything. I like the SQLite browser, I'm sure it could be patched to support DuckDB. Maybe you would like to give it a go?

**Comment by verajosemanuel** [comment]
Tried renaming duckdb file to sqlite.db bit sqlitebrowser cannot open it

**Comment by hannesmuehleisen** [comment]
The database file formats of DuckDB and SQLite are very different, simply renaming is not enough.

**Comment by exaatto** [comment]
@verajosemanuel I personally use DBeaver[1] for graphical DB view/admin. It supports DuckDB. Actually it's Java/Eclipse based and supports all generic JDBC-ready DBMSs. They also include a nice guide[2] to add new JDBC driver for new DBMS. The only drawback is it may be a bit too sophisticated for non-IT guys.

@Mause Thanks for the SQLAlchemy engine, it just works. It would be very nice if DuckDB can make it official support.

However, as for Python/SQLAlchemy based DB viewer sort of thing, I never success to find any good ones.

[1] https://dbeaver.io/
[2] https://github.com/dbeaver/dbeaver/wiki/Database-drivers

**Comment by verajosemanuel** [comment]
I LOVE dbeqver but  my work laptop has no jav installed .So It won't work

**Comment by alanpaulkwan** [comment]
How does one install this into DBeaver? Can someone post instructions? It's far from obvious.

**Comment by Mause** [comment]
@verajosemanuel fairly sure Dbeaver includes its own installation of java I believe?

@alanpaulkwan try the following driver settings:
![image](https://user-images.githubusercontent.com/1405026/102684512-34f23600-4214-11eb-96d8-c586132879d8.png)

**Comment by hannesmuehleisen** [comment]
@Mause @exaatto did not know that this worked, but sooo cool! Thanks for pointing this out.

**Comment by alanpaulkwan** [comment]
@Mause thank you. What do you enter on this screen when making the final connection?
![image](https://user-images.githubusercontent.com/8321252/102686000-97046880-421f-11eb-9e16-27fc55a8baec.png)

**Comment by Mause** [comment]
@alanpaulkwan the path to your duckdb database file

**Comment by alanpaulkwan** [comment]
@Mause  amazing

**Comment by alanpaulkwan** [comment]
Unfortunately, the bleeding edge DuckDB version is reverse incompatible with the available JAR. Oops. But definitely now this will help my students who I will teach via DuckDB ... (the command line is scary!)

**Comment by hannesmuehleisen** [comment]
You can download bleeding edge JARs from here: https://github.com/cwida/duckdb/releases/tag/master-builds

**Comment by verajosemanuel** [comment]
> @verajosemanuel fairly sure Dbeaver includes its own installation of java I believe?
> 
Yes, but I have no privileges to install anything

**Comment by exaatto** [comment]
> Yes, but I have no privileges to install anything

I'm pretty sure DBeaver has a portable version with bundled JRE, download&unzip and it just works.

**Comment by wdkrnls** [comment]
Someone please create a way to "serialize" duckdb as a file system containing directories of read-only broadly accessible plain text delimited data files. Then everyone could access the data regardless of whether they are using a currently fashionable analytics platform. That feature would quickly make duckdb the lingua franca of inclusive and open data science.

**Comment by exaatto** [comment]
@wdkrnls I believe this is already part of DuckDB.

COPY TO statement to export single table:
https://duckdb.org/docs/sql/statements/copy

EXPORT statement to export the whole DB:
https://duckdb.org/docs/sql/statements/export

**Comment by wdkrnls** [comment]
@exaatto I guess I was hoping for `mount-duck db tmp/`. Requiring scientists who are casual users of database systems (at best!) to get comfortable with a completely alien environment is a big barrier. If the mounted read only filesystem view could be shared over e.g. SAMBA, then even Excel users could painlessly access the data just by double clicking the delimited file of containing the view of interest.

**Comment by alanpaulkwan** [comment]
I'm experimenting with ways of embedding this inside another DB, such as MySQL or Drill, to embed DuckDB as a web service or to fix those DB's parquet compatibility issues. Just for fun. Anyone try something like this?

**Comment by hannesmuehleisen** [comment]
Closing this now, feel free to continue in discussions

**Comment by ryanhamilton** [comment]
Hi,

I've added what I think is good DuckDB support to our free SQL tool qStudio (perhaps I should rename this edition quackStudio :)).  
https://www.timestored.com/qstudio/

As shown below you can:
- Create a new DuckDB from within the File->Menu
- Open an existing .duckdb file by clicking in windows
- Close the file from the UI
- Send queries

I have added some example SQL, taht you can see in the video but I would really like to improve it.
Please let me know what you think as I would like to improve it further if people like it.

![duckdb-qstudio](https://user-images.githubusercontent.com/7273208/221204784-d140698f-265f-4078-aa81-70d0b6797d81.png)

File associations in Windows, just click to open:
![duckdb-file-association](https://user-images.githubusercontent.com/7273208/221204793-0eb10310-1780-4da1-bcdd-da909cc4d03b.png)

Full documentation here: https://www.timestored.com/qstudio/help/duckdb-sql-editor

**Comment by eirikbakke** [comment]
There's support for DuckDB in [Ultorg](https://www.ultorg.com/) now. It's a graphical database UI that came out of my old PhD project, now commercialized. (DuckDB demo [here](https://www.youtube.com/watch?v=jzOVUbN6eVk).)

In Ultorg's case it's assumed that you have a DuckDB file already available with data somewhere. You'd connect to it with the **Add Data Source→Connect to File** action:

<img width="1059" alt="Image" src="https://github.com/user-attachments/assets/0392f04d-d0d5-4524-a3da-67f3e1c6b655" />
