### ISSUE TITLE
duckdb gives an internal error when trying to select from multiple GRAPH_TABLE's

### ISSUE THREAD

**Issue by jcavano** [duckdb/duckdb#12178]
### What happens?

When attempting to run a query that selects from multiple property graph tables, the following error is given: "Error: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!"

According to the property graph sql standard described in ISO/IEC 9075-16, selecting from multiple GRAPH_TABLE's (implicit cross join) should be possible.

### To Reproduce

CREATE TABLE cities (
          name VARCHAR,
          lat  DECIMAL,
          lon  DECIMAL
);

CREATE TABLE cities_are_adjacent (
          city1name VARCHAR,
          city2name VARCHAR
);

-CREATE PROPERTY GRAPH citymap
VERTEX TABLES (
cities PROPERTIES (name,lat,lon) LABEL city
)
EDGE TABLES (
cities_are_adjacent 	SOURCE KEY ( city1name ) REFERENCES cities ( name )
DESTINATION KEY ( city2name ) REFERENCES cities ( name )
LABEL adjacent
);

D -select * from GRAPH_TABLE (citymap MATCH (s:city)-[r:adjacent]->(t:city)) g1;

┌─────────┬───────────────┬───────────────┬───┬───────────────┬───────────────┐
│  name   │      lat      │      lon      │ … │     lat_1     │     lon_1     │
│ varchar │ decimal(18,3) │ decimal(18,3) │   │ decimal(18,3) │ decimal(18,3) │
├─────────────────────────────────────────────────────────────────────────────┤
│                                   0 rows                                    │
└─────────────────────────────────────────────────────────────────────────────┘
D -select * from GRAPH_TABLE (citymap MATCH (s:city)-[r:adjacent]->(t:city)) g1, GRAPH_TABLE (citymap MATCH (s:city)-[r:adjacent]->(t:city)) g2;
Error: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

### OS:

Linux x86_64

### DuckDB Version:

v0.10.1-dev17 bb9b820715

### DuckDB Client:

c++

### Full Name:

Jeff Cavano

### Affiliation:

eBay

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! Perhaps you meant to file this in the [duckdb_pgq](https://github.com/cwida/duckdb-pgq) repository? DuckDB itself does not support property graphs.

**Comment by Dtenwolde** [comment]
Hi there, I'm the developer of the duckdb-pgq extension. Currently multiple graph_table's are not yet supported. They are on my short term to-do list though. I have an issue open for it [here](https://github.com/cwida/duckpgq-extension/issues/88) :)
