### ISSUE TITLE
Improve error message for databases named 'system'

### ISSUE THREAD

**Issue by dpetz** [duckdb/duckdb#12190]
### What happens?

When naming a database `system` the error resulting message [1] is unhelpful.
As a result, users unaware of https://duckdb.org/docs/sql/keywords_and_identifiers.html may spend many hours debugging.
In addition to improving the error message, the documentation should say "mandatory" instead "best practice".

[1] BinderException: Binder Error: Cannot create entry in system catalog

### To Reproduce

# python file
import duckdb
con = duckdb.connect(database="system.db")
con.execute("CREATE TABLE test (name varchar)")

### OS:

iOS

### DuckDB Version:

0.10

### DuckDB Client:

Python

### Full Name:

Dirk Petzoldt

### Affiliation:

founder

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! I've pushed a fix in #12206
