### ISSUE TITLE
CREATE OR REPLACE...AS no longer works if there are downstream views that reference the target table

### ISSUE THREAD

**Issue by izeigerman** [duckdb/duckdb#12191]
### What happens?

https://github.com/duckdb/duckdb/pull/12159 has introduced the `DROP ... CASCADE` mechanics to drop entities that have downstream dependencies (like views).

Unfortunately this broke the `CREATE OR REPLACE` queries which now fail with:
```
Cannot drop entry... because there are entries that depend on it... Use DROP...CASCADE to drop all dependents.
```
when the target table or a view has a view downstream from it.

This behavior seems weird since the replacement suppose to happen atomically, as a single operation. Doesn't requiring the use of `DROP...CASCADE` defeat the purpose of `CREATE OR REPLACE`?

### To Reproduce

1. Create a table or a view.
2. Create a view which references the table / view created in (1).
3. Run `CREATE OR REPLACE ... AS SELECT ...` targeting the table / view created in (1).

```
In [1]: import duckdb

In [2]: conn = duckdb.connect()

In [3]: conn.execute("CREATE OR REPLACE TABLE tbl_a  AS SELECT 1 AS a")
Out[3]: <duckdb.duckdb.DuckDBPyConnection at 0x102b7a8f0>

In [4]: conn.execute("CREATE OR REPLACE VIEW view_a AS SELECT * FROM tbl_a")
Out[4]: <duckdb.duckdb.DuckDBPyConnection at 0x102b7a8f0>

In [5]: conn.execute("CREATE OR REPLACE TABLE tbl_a  AS SELECT 2 AS a")
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[5], line 1
----> 1 conn.execute("CREATE OR REPLACE TABLE tbl_a  AS SELECT 2 AS a")

Error: Cannot drop entry "tbl_a" because there are entries that depend on it.
view "view_a" depends on table "tbl_a".
Use DROP...CASCADE to drop all dependents.
```

### OS:

MacOS

### DuckDB Version:

0.10.3

### DuckDB Client:

Python

### Full Name:

Iaroslav Zeigerman

### Affiliation:

TobikoData

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

0.10.3

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
That PR is not relevant here, this one is
https://github.com/duckdb/duckdb/pull/11493

Views create dependencies now

**Comment by Tishj** [comment]
> Doesn't requiring the use of `DROP...CASCADE` defeat the purpose of `CREATE OR REPLACE`

I don't agree, I just think what is missing here is the option to provide `CASCADE` to `CREATE OR REPLACE`
They control two different intentions

CREATE OR REPLACE indicates your intent to drop the table, it doesn't necessarily indicate your intent to drop the views/indexes/sequences, etc.. that have a dependency on the table

**Comment by izeigerman** [comment]
> We could argue whether the VIEW should be recreated instead of dropped if CASCADE is provided, but that's a different discussion. I don't think performing a CASCADE implicitly when OR REPLACE is used is the right move

I do believe that `CREATE OR REPLACE` should not be destructive towards downstream dependencies. With or without `CASCADE`. 

A typical use case for `CREATE OR REPLACE` is to atomically refresh the entire table without changing the schema and without exposing the clients to partial (empty) data caused by the intermediate table truncation step.

The existing behavior renders this use cases impossible. Is there a way to disable binding for views and go back to previous behavior?

**Comment by aersam** [comment]
This also broke us, for me this is really unexpected. `CREATE OR REPLACE` should really not be destructive, and it's heavily breaking

**Comment by Mytherin** [comment]
https://github.com/duckdb/duckdb/pull/12209 adds a new setting for view dependencies (`enable_view_dependencies`) which now defaults to false
