### ISSUE TITLE
:bug: `v0.10.3` Regression while adding a new column to a table "because there are entries that depend on it."

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#12217]
### What happens?

Since latest [`v0.10.3`](https://github.com/duckdb/duckdb/releases/tag/v0.10.3), my scheduled notebook is broken, a regression has been introduced.

As a proof, see : 

- [:+1:  Before](https://www.kaggle.com/code/adriensales/fiches-emploi-nouvelle-cal-donie)
- [:-1: Now](https://www.kaggle.com/code/adriensales/fiches-emploi-nouvelle-cal-donie?scriptVersionId=179423277)

### To Reproduce

See notebook [here](https://www.kaggle.com/code/adriensales/fiches-emploi-nouvelle-cal-donie/log?scriptVersionId=179423277), still here are the steps to reproduce : 

# :one:  Create a main table : 

```python
con.execute("""create or replace table familles(id varchar primary key)""")
con.execute("""insert into familles
                    select distinct famille
                        from load_fiches
                    order by famille;""")
df = con.query("from familles").to_df()
df
```

# :two: Create a table that references it

```python
con.execute("""create or replace SEQUENCE id_fiche START 1; """)
con.execute("""create or replace table fiches(
                id integer DEFAULT nextval('id_fiche') primary key,
                famille varchar not null references familles(id),
                titre varchar not null,
                url_pdf_fiche_emploi varchar not null
                )""")

con.execute("""insert into fiches (famille, titre, url_pdf_fiche_emploi)
                    select famille, titre, url_pdf_fiche_emploi
                        from load_fiches
                    order by famille, titre;""")
df = con.query("from fiches").to_df()
df
```

# :three: Add a column to the main table

```python
con.execute("""alter table familles add column code_rome varchar""")
```

### OS:

Kaggle

### DuckDB Version:

`v0.10.3` 

### DuckDB Client:

Python

### Full Name:

Adrien Sales

### Affiliation:

https://dev.to/adriens

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
https://github.com/duckdb/duckdb/pull/11524

**Comment by adriens** [comment]
- https://github.com/duckdb/duckdb/pull/11524

Is there a planning fo the release of `v0.10.4` ?

**Comment by Tishj** [comment]
Hey sorry, I wasn't clear

The problem is introduced by that PR, I just wanted to point to the relevant context
There is no real reason the ALTER you're doing should be blocked by this dependency but there is no fine grained control on this yet

Perhaps we should take the same approach as #12209 to fix this problem until the handling is more mature and we don't block ALTERs unnecessarily
