### ISSUE TITLE
Hive partitioned append/write 0.10.3 

### ISSUE THREAD

**Issue by daniarleagk** [duckdb/duckdb#12225]
### What happens?

Before version 0.10.3, you could enforce partitioned append to a Hive partitioned table by specifying the FILENAME_PATTERN 
property and setting OVERWRITE_OR_IGNORE to true. 
However, since the recent changes (as documented in this GitHub pull request https://github.com/duckdb/duckdb/pull/11787),
 the behavior has been modified. Now I am experiencing breaking changes in my applications.  Is there any alternative approach for partitioned append? The code below  illustrates the problem.

### To Reproduce

```sql
create or replace temp view t_val_v  as 
select *
from ( 
    values 
    ('p_1', 'key_1', 'val_1'),
    ('p_2', 'key_1', 'val_1'),
    ('p_3', 'key_1', 'val_1')
) as t_val(p_key, key, val);
copy (
    select *
    from  t_val_v
) to '/home/da/output_tmp/t_val' (
format parquet,
PARTITION_BY (p_key),
FILENAME_PATTERN "pv1_{i}",
OVERWRITE_OR_IGNORE false
);
copy (
    select *
    from  t_val_v
) to '/home/da/output_tmp/t_val' (
format parquet,
PARTITION_BY (p_key),
FILENAME_PATTERN "pv2_{i}",
OVERWRITE_OR_IGNORE false
);
```

output before. changes (version 0.10.2):

```bash
before 0.10.3 
~/output_tmp/t_val/p_key=p_1$ ls -la
total 16
drwxr-xr-x 2 da da 4096 May 24 10:46 .
drwxr-xr-x 5 da da 4096 May 24 10:44 ..
-rw-r--r-- 1 da da  367 May 24 11:49 pv1_0.parquet
-rw-r--r-- 1 da da  367 May 24 11:49 pv2_0.parquet
```
output with version 0.10.3 (removes all old files)

```bash
~/output_tmp/t_val/p_key=p_1$ ls -la
total 12
drwxr-xr-x 2 da da 4096 May 24 11:51 .
drwxr-xr-x 5 da da 4096 May 24 10:44 ..
-rw-r--r-- 1 da da  367 May 24 11:51 pv2_0.parquet
```

### OS:

windows, ubuntu

### DuckDB Version:

0.10.3

### DuckDB Client:

python

### Full Name:

Daniar Achakeev

### Affiliation:

HMS Analytical Software GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by djouallah** [comment]
yes, I reported the issue in discussion 3 weeks ago, current workaround is not to upgrade

https://github.com/duckdb/duckdb/discussions/11928

**Comment by Mytherin** [comment]
Thanks for reporting! I've pushed a fix in https://github.com/duckdb/duckdb/pull/12240 that reverts `OVERWRITE_OR_IGNORE` to the previous behavior, and moves the new behavior to `OVERWRITE`.

**Comment by daniarleagk** [comment]
Thank you!
