### ISSUE TITLE
Possible downtime on DuckDB Extensions Repository

### ISSUE THREAD

**Issue by mustafahasankhan** [duckdb/duckdb#12230]
## Issue:
We encountered failures during attempts to download extensions from the DuckDB extensions repository. [in our K8s environment which runs containers (DuckDB on Python slim image and JVM) to process data in regular intervals]

## Error Messages:

- duckdb.duckdb.IOException: IO Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/00924b709c/linux_amd64_gcc4/sqlite_scanner.duckdb_extension.gz"
- duckdb.duckdb.Error: Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'aws': Failed to download extension "aws" at URL "http://extensions.duckdb.org/v0.9.2/linux_amd64_gcc4/aws.duckdb_extension.gz"

## Affected Timeframe:
The downtime occurred between UTC 8 AM to 9 AM today, Friday 24 May, 2024.

Following Discord communication, I am reporting this here as an issue.

### To Reproduce

N/A

### OS:

Debian

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Mustafa Hasan Khan

### Affiliation:

Atlan

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
There were no changes on our side, and the extensions are downloaded through AWS CloudFront behind a CloudFlare cache - difficult to imagine an hour's downtime there would be missed so not sure what we can do about this.
