### ISSUE TITLE
Unable to COPY to remote Hugging Face dataset repo

### ISSUE THREAD

**Issue by AndreaFrancis** [duckdb/duckdb#12234]
### What happens?

Previously, registering the HF file system in Python allowed us to push files to dataset repositories.
Now, I tried with duckdb CLI 0.10.3 and expected to be able to push files given that the HF filesystem was already integrated, but it looks to be not working; maybe I am doing something wrong.

**FAILED with the message: Not implemented Error: Writing to HTTP files not implemented**

### To Reproduce

- First, create the repository
```
from huggingface_hub import HfApi
HfApi().create_repo(repo_id="username/dataset_name", repo_type="dataset")

```
- And then, try to fetch some data and upload it to the new dataset repo created:

```
from huggingface_hub import HfFileSystem
import duckdb
fs = HfFileSystem()
duckdb.register_filesystem(fs)
duckdb.sql("SELECT * FROM 'hf://datasets/asoria/stories_for_kids/seed_data.json';")
duckdb.sql("COPY (SELECT * FROM 'hf://datasets/asoria/stories_for_kids/seed_data.json') TO 'hf://datasets/username/dataset_name/seed_data.parquet' (FORMAT PARQUET);")

```
It works OK

Now, I tried with duckdb CLI 0.10.3 and expected to be able to push files given that the HF filesystem was already integrated, but it looks to be not working; maybe I am doing something wrong.

```
CREATE SECRET hf_token (TYPE HUGGINGFACE, PROVIDER credential_chain);
SELECT * FROM 'hf://datasets/asoria/stories_for_kids/seed_data.json';
COPY (SELECT * FROM 'hf://datasets/asoria/stories_for_kids/seed_data.json') TO 'hf://datasets/username/dataset_name/data.parquet' (FORMAT PARQUET);
Not implemented Error: Writing to HTTP files not implemented
```
**FAILED with the message: Not implemented Error: Writing to HTTP files not implemented**

### OS:

Ubuntu 22.04.2 LTS x86_64

### DuckDB Version:

v0.10.3

### DuckDB Client:

v0.10.3

### Full Name:

Andrea Soria Jimenez

### Affiliation:

Hugging Face

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by samansmink** [comment]
Yea we support reads only for now, you will need to go the fsspec route if you want to write from DuckDB

**Comment by severo** [comment]
asked again on Discord today: https://discord.com/channels/909674491309850675/921073327009853451/1422429843467014184

> Is it possible to write to hugging face directly with duckdb?

cc @onnimonni
