### ISSUE TITLE
Too many files generated when setting temp_directory property in in-memory mode

### ISSUE THREAD

**Issue by nswdxqq** [duckdb/duckdb#12247]
### What happens?

I'm testing with DuckDB-JDBC 0.10.3 and the in-memory mode was used in my testing. According to the documentation, the temp_directory and max_temp_directory_size settings were set for the case that the data set is too large to fit into the memory.
In the testing, the "duckdb_temp_storage-0.tmp" file was created when the data was larger than the setting for the memory_limit, and there was many "duckdb_temp_block-*********.block" files created in the temp_directory also, is this expected result for the case? And is the size of these "duckdb_temp_block-*********.block" files also taken into account when checking the setting for max_temp_directory_size property?

### To Reproduce

To reproduce the issue, please follow the below steps:
1. Create a standalone Java application using DuckDB-JDBC;
2. Create in-memory DB with DuckDB-JDBC;
3. Configure the in-memory DB as follows:
    SET temp_directory to system temporary directory
    SET memory_limit to 1GB
    SET max_temp_directory_size to 10GB
5. Create some tables in DuckDB and populate them with large data sets, in my case, 15 tables were created and 300MB~400MB data was populated in each table
6. Check the temp_directory for files generated by DuckDB, there was more than 1500 "duckdb_temp_block-*********.block" files and only one "duckdb_temp_storage-0.tmp" file in it

### OS:

Windows 10 x64

### DuckDB Version:

0.10.3

### DuckDB Client:

DuckDB-JDBC

### Full Name:

Jie

### Affiliation:

qilin

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
> Create some tables in DuckDB 

Were these temporary tables?

**Comment by szarnyasg** [comment]
Hi @nswdxqq, thanks for reporting this issue. Could you please create a Java project and share it (e.g. as a GitHub repository)? You have a lot more context and information (e.g. what types, data distribution, etc. occur), all which may contribute to the error. Based on your description alone it would be very difficult to reproduce the error.

**Comment by nswdxqq** [comment]
> > Create some tables in DuckDB
> 
> Were these temporary tables?

No, they are regular tables.

**Comment by nswdxqq** [comment]
> Hi @nswdxqq, thanks for reporting this issue. Could you please create a Java project and share it (e.g. as a GitHub repository)? You have a lot more context and information (e.g. what types, data distribution, etc. occur), all which may contribute to the error. Based on your description alone it would be very difficult to reproduce the error.

I'm busy on evaluating some solutions now. I'll try to do it later when convenient.

**Comment by Mytherin** [comment]
I can't reproduce this with `lineitem`, e.g.:

##### generate file
```sql
CALL dbgen(sf=1);
COPY lineitem TO lineitem.parquet;
```

##### run test
```sql
SET memory_limit to '1GB';
SET max_temp_directory_size to '10GB';
set temp_directory='/tmp/test';
create table lineitem1 as from lineitem.parquet;
create table lineitem2 as from lineitem.parquet;
create table lineitem3 as from lineitem.parquet;
create table lineitem4 as from lineitem.parquet;
create table lineitem5 as from lineitem.parquet;
create table lineitem6 as from lineitem.parquet;
create table lineitem7 as from lineitem.parquet;
create table lineitem8 as from lineitem.parquet;
create table lineitem9 as from lineitem.parquet;
create table lineitem10 as from lineitem.parquet;
-- Out of Memory Error: failed to offload data block of size 256.0 KiB (9.3 GiB/9.3 GiB used).
-- This limit was set by the 'max_temp_directory_size' setting.
-- By default, this setting utilizes the available disk space on the drive where the 'temp_directory' is located.
-- You can adjust this setting, by using (for example) PRAGMA max_temp_directory_size='10GiB'
```

The directory has only a few files at this point:
```
$ > ls -trlah /tmp/test 
total 18136576
drwxrwxrwt  15 root  wheel   480B May 28 12:12 ..
-rw-r--r--   1 myth  wheel   1.7G May 28 12:12 duckdb_temp_storage-0.tmp
-rw-r--r--   1 myth  wheel   2.5G May 28 12:12 duckdb_temp_storage-1.tmp
-rw-r--r--   1 myth  wheel   4.4G May 28 12:12 duckdb_temp_storage-2.tmp
drwxr-xr-x   6 myth  wheel   192B May 28 12:12 .
-rw-r--r--   1 myth  wheel   103M May 28 12:12 duckdb_temp_storage-3.tmp
```
