### ISSUE TITLE
Version 0.10.3 cannot recognize the pd.DataFrame with the variable name 'df'

### ISSUE THREAD

**Issue by richand112233** [duckdb/duckdb#12243]
### What happens?

**Version 0.10.3 cannot recognize the pd.DataFrame with the variable name 'df'.
There was no such issue in version 0.10.2.
The issue can be temporarily resolved by using "duckdb.register('df', df)", but this would make the code less concise and reduce compatibility.**

> InvalidInputException: Invalid Input Error: Python Object "df" of type "builtin_function_or_method" found on line "C:\Users\richand\AppData\Local\Programs\Python\Python311\Lib\site-packages\duckdb\__init__.py:457" not suitable for replacement scans.
Make sure that "df" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format

### To Reproduce

```
import duckdb
import pandas as pd
df = pd.DataFrame([['a','b'],['c','d']], columns=['x','y'])
duckdb.sql("from df")
```

### OS:

windows10 x64

### DuckDB Version:

0.10.3

### DuckDB Client:

python 3.11.4

### Full Name:

richand

### Affiliation:

0

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by Tishj** [comment]
#11945 
Has been fixed, will be in the next release, thanks

To work around, create a connection
con = duckdb.connect()
con.sql(...)
