### ISSUE TITLE
Error parsing dataframe from variable name in 0.10.3

### ISSUE THREAD

**Issue by jakkes** [duckdb/duckdb#12254]
### What happens?

When running `duckdb.sql("select * from df")`, where `df` is a function argument, duckdb fails to recognize the dataframe.

### To Reproduce

```python
>>> import duckdb; import pandas as pd
>>> def f(df):
...     return duckdb.sql("select * from df").to_df()
...
>>> f(pd.DataFrame({"x": [0, 1, 2]}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
  File "/nas/data/upsync/home/jakob/tmpvenv/lib/python3.10/site-packages/duckdb/__init__.py", line 457, in sql
    return conn.sql(query, **kwargs)
duckdb.duckdb.InvalidInputException: Invalid Input Error: Python Object "df" of type "builtin_function_or_method" found on line "/nas/data/upsync/home/jakob/tmpvenv/lib/python3.10/site-packages/duckdb/__init__.py:457" not suitable for replacement scans.
Make sure that "df" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format
```

### OS:

Ubuntu22.04

### DuckDB Version:

0.10.3

### DuckDB Client:

Python 3.10.12

### Full Name:

Jakob Stigenberg

### Affiliation:

Qubos

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
see #11945
