### ISSUE TITLE
C API: Writing (large) list with Appender fails

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#12268]
### What happens?

When writing a list with size > 2050 to an Appender the code throws `A heap has been corrupted` error at `duckdb_append_data_chunk`. Depending on the size of the list I sometimes get `Access violation reading location` or `Access violation writing location` error. The code works fine if list size is <=2050. I have verified it by writing to the db on disk and reading from it.

I guess this is happening because DuckDB allows only 2048 items in the vector. Not sure why it works for 2050, probably a coincidence.

Haven't tested with Array type.

### To Reproduce

```c
auto vectorMaxSize = duckdb_vector_size();

state = duckdb_query(con, "CREATE TABLE AppenderList(a Integer, b Integer[]);", &result);

duckdb_appender appender;
duckdb_appender_create(con, NULL, "AppenderList", &appender);

duckdb_logical_type types[2];

types[0] = duckdb_appender_column_type(appender, 0);
types[1] = duckdb_appender_column_type(appender, 1);

duckdb_data_chunk data_chunk = duckdb_create_data_chunk(types, 2);

duckdb_vector intVector = duckdb_data_chunk_get_vector(data_chunk, 0);
duckdb_vector listVector = duckdb_data_chunk_get_vector(data_chunk, 1);

auto intVectorData = (int32_t*)duckdb_vector_get_data(intVector);
*intVectorData = 42;

duckdb_list_entry entry;
auto listData = (duckdb_list_entry*)duckdb_vector_get_data(listVector);

duckdb_vector listChildVector = duckdb_list_vector_get_child(listVector);
auto listChildVectorData = (int32_t*)duckdb_vector_get_data(listChildVector);

auto listLength = vectorMaxSize + 3;

for (int32_t i = 0; i < listLength; i++)
{
	listChildVectorData[i] = i;
}

entry.offset = 0;
entry.length = listLength;
*listData = entry;

duckdb_data_chunk_set_size(data_chunk, 1);
state = duckdb_append_data_chunk(appender, data_chunk);

duckdb_destroy_logical_type(&types[0]);
duckdb_destroy_logical_type(&types[1]);

duckdb_destroy_data_chunk(&data_chunk);

duckdb_appender_close(appender);
state = duckdb_appender_destroy(&appender);
```

Depending on what number you put on `auto listLength = vectorMaxSize + 3;` line you will see different behavior:

No error if it is 0, 1 or 2.

If it is 3:
![image](https://github.com/duckdb/duckdb/assets/580749/57a8a745-d706-49dd-9fd6-c416fc10b025)
![image](https://github.com/duckdb/duckdb/assets/580749/df3056ec-f695-4aa7-a018-8417c28b0050)

If it is 300:
![image](https://github.com/duckdb/duckdb/assets/580749/4b3074be-90fe-4d13-b6e2-d9a17561020e)

If it is 1000:
![image](https://github.com/duckdb/duckdb/assets/580749/b6eabf62-e537-4170-a1d4-2cd5c7b924e0)

### OS:

Windows 11 x64

### DuckDB Version:

0.10.3

### DuckDB Client:

C Api

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report!

`duckdb_create_data_chunk` allocates vectors with as size `duckdb_vector_size()`. Writing more than `duckdb_vector_size()` entries to any of the vectors is undefined behavior. For lists, as in this example, the child vector similarly is allocated with space for `duckdb_vector_size()` entries.

The `duckdb_list_vector_reserve` can be used to resize the child vector of a list. Note that this must be done **before** calling methods like `duckdb_vector_get_data` on the list child vector because calling `duckdb_list_vector_reserve` can invalidate the pointer previously used by `duckdb_vector_get_data`.

Below is a fix for the original example:

```cpp
duckdb_list_entry entry;
auto listData = (duckdb_list_entry*)duckdb_vector_get_data(listVector);

auto listLength = vectorMaxSize + 3;

duckdb_vector listChildVector = duckdb_list_vector_get_child(listVector);
// reserve enough space for the elements
duckdb_list_vector_reserve(listVector, listLength);
auto listChildVectorData = (int32_t*)duckdb_vector_get_data(listChildVector);

```

**Comment by Giorgi** [comment]
Thanks for the explanation @Mytherin. This will work if the caller knows the required size upfront, but I guess very frequently they won't know how many rows or how big lists they will be appending. For example, when reading data from some REST service, or sensor data, or something else. In such cases, it's not possible to call `duckdb_list_vector_reserve` only once.

The only workaround that I see is to keep data for all rows in memory and actually build the data chunk after every `duckdb_vector_size` row. Can the list child vector be resized **without** invalidating the data that was already written?

**Comment by Mytherin** [comment]
`duckdb_list_vector_reserve` does not invalidate the written data, only the pointer. Think of it like `realloc`.

**Comment by Giorgi** [comment]
Ok, I'll give it a try.

**Comment by Giorgi** [comment]
What is the downside of allocating a larger vector and writing only part of the data? Is it just increased memory usage (which I hope gets freed when I call `duckdb_append_data_chunk`) or is there some other hidden cost?

I'm asking because I'm thinking of doubling the allocating size when I reach the current allocation size.

**Comment by Mytherin** [comment]
Just memory usage yes, doubling sounds like a good idea in an append scenario.

**Comment by Giorgi** [comment]
Thanks. Actually, I made it a little bit smarter to avoid extra allocation. As I have to call `duckdb_append_data_chunk` I already need to track how many rows there are. I use this row count and if I'm at the end of the chunk I will increase it only by 1.2, if in the beginning I will double it and do something in the middle in between.
