### ISSUE TITLE
cannot define a macro inside a cursor - Cross catalog dependencies are not supported.

### ISSUE THREAD

**Issue by exaroj** [duckdb/duckdb#12272]
### What happens?

An error is thrown when trying to create a TEMP MACRO inside a cursor with a dependency.
This worked prior to 0.10.3

```
duckdb.duckdb.Error: Error adding dependency for object "m2" - dependency "m1" is in catalog "memory", which does not match the catalog "temp".
Cross catalog dependencies are not supported.
```

### To Reproduce

```python
import duckdb


def temp_macro() -> None:
    with duckdb.connect() as con:
        print(con.execute("SELECT * FROM pragma_version()").fetchall())
        con.execute("CREATE MACRO m1() AS (SELECT 1 AS x);")
        with con.cursor() as cur:
            cur.execute(
                """CREATE OR REPLACE TEMP MACRO m2() AS (SELECT m1() AS y);""")
            
temp_macro()

```

```sh
% python3 /tmp/macro.py 
[('v0.10.2', '1601d94f94')]

% python3 /tmp/macro.py 
[('v0.10.3', '70fd6a8a24')]
Traceback (most recent call last):
  File "/tmp/macro.py", line 12, in <module>
    temp_macro()
  File "/tmp/macro.py", line 5, in temp_macro
    with duckdb.connect() as con:
  File "/tmp/macro.py", line 8, in temp_macro
    with con.cursor() as cur:
  File "/tmp/macro.py", line 9, in temp_macro
    cur.execute(
duckdb.duckdb.Error: Error adding dependency for object "m2" - dependency "m1" is in catalog "memory", which does not match the catalog "temp".
Cross catalog dependencies are not supported.

% python3 /tmp/macro.py 
[('v0.10.4-dev72', '896686ffdf')]
Traceback (most recent call last):
  File "/tmp/macro.py", line 12, in <module>
    temp_macro()
  File "/tmp/macro.py", line 5, in temp_macro
    with duckdb.connect() as con:
  File "/tmp/macro.py", line 8, in temp_macro
    with con.cursor() as cur:
  File "/tmp/macro.py", line 9, in temp_macro
    cur.execute(
duckdb.duckdb.Error: Error adding dependency for object "m2" - dependency "m1" is in catalog "memory", which does not match the catalog "temp".
Cross catalog dependencies are not supported.
```

### OS:

macOS 14.5

### DuckDB Version:

0.10.3

### DuckDB Client:

Python

### Full Name:

Rob Jackson

### Affiliation:

exaforce.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for raising this

This dependency did not exist previously, it was introduced as part of https://github.com/duckdb/duckdb/pull/11493

That means there was nothing preventing m1 from being dropped while m2 was still alive (not dropped)

We'll review what action to take based on this issue

Perhaps we'll make temporary item exempt from this, not creating dependencies for created temporary objects

**Comment by Tishj** [comment]
The error is supposed to surface when you're attempting to reference an object (macro in this case) from another db, that was added using ATTACH

Hitting this on temporary objects is a bit of an oversight, not a case I considered yet

**Comment by Tishj** [comment]
I think CREATE OR REPLACE should get a CASCADE option which applies when the `OR REPLACE` kicks in.
Though that might create the expectation that all the affected objects are recreated, which I think would not be the goal
