### ISSUE TITLE
Aggregate Regression function SLOPE and INTERCEPT seem to produce wrong results

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#12299]
### What happens?

```sql
--  regr_slope(y, x) = covar_pop(x, y) / var_pop(x), see https://duckdb.org/docs/sql/aggregates
SELECT covar_pop(x, y) , var_pop(x), regr_slope(y, x) AS regr_slope FROM VALUES (1, 2), (2, 3), (2, 3), (null, 4), (4, null) AS T(y, x);

-- but results are:
/* 
┌─────────────────┬────────────┬────────────┐
│ covar_pop(x, y) │ var_pop(x) │ regr_slope │
├─────────────────┼────────────┼────────────┤
│         0.22222 │       0.50 │       1.00 │
└─────────────────┴────────────┴────────────┘
*/

-- expected Slope (according to DataBricks) was  .333333
```

### To Reproduce

```sql
SELECT covar_pop(x, y) , var_pop(x), regr_slope(y, x) AS regr_slope FROM VALUES (1, 2), (2, 3), (2, 3), (null, 4), (4, null) AS T(y, x);
```

### OS:

Linux

### DuckDB Version:

0.10.3

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
That's just s documentation problem. `regr_slope` uses `covar_pop(x, x)` instead of `var_pop(x, x)`. The slope returned by duckdb is clearly the correct one, as you will notice by plotting your points and the regression line.

**Comment by manticore-projects** [comment]
> That's just a documentation problem. `regr_slope` uses `covar_pop(x, x)` instead of `var_pop(x, x)`. The slope returned by duckdb is clearly the correct one, as you will notice by plotting your points and the regression line.

Please read my issue again. I am referring to the `COVAR_POP(x,y)` function already as documented, which returns `0.222`.
So how will `0.2222 / 0.5 = 1.00`?

**Comment by manticore-projects** [comment]
Although the result is actually correct:
```python
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the x and y values
x = np.array([1, 2, 2]).reshape(-1, 1)
y = np.array([2, 3, 3])

# Fit the linear model
model = LinearRegression().fit(x, y)

# Get the slope (coefficient)
slope = model.coef_[0]
slope

Result

0.9999999999999997
```

**Comment by soerenwolfers** [comment]
Yes, it's correct because `covar_pop(x, x) = 0.222` as well, and `0.222 / 0.222 = 1.0`

**Comment by soerenwolfers** [comment]
You can change the docs yourself by the way! Just click on the "Edit page" link on the bottom of the documentation page. In the meantime, this ticket can be closed and if you don't want to make the edit yourself, you can open a ticket at the documentation repository.

**Comment by manticore-projects** [comment]
> Yes, it's correct because `covar_pop(x, x) = 0.222` as well, and `0.222 / 0.222 = 1.0`

Thanks, now I understand you better. So the actual Documentation shall state: 
` regr_slope(y, x) = covar_pop(x, y) / covar_pop(x,x) `?!

**Comment by manticore-projects** [comment]
> You can change the docs yourself by the way! Just click on the "Edit page" link on the bottom of the documentation page. In the meantime, this ticket can be closed and if you don't want to make the edit yourself, you can open a ticket at the documentation repository.

Yes, I know that and I did that several times -- but only on things I am very sure of, and this did not fall into this category.

**Comment by szarnyasg** [comment]
Thanks for resolving this @soerenwolfers and @manticore-projects! I'll update the documentation.

**Comment by soerenwolfers** [comment]
https://github.com/duckdb/duckdb-web/pull/3048 Fixes the documentation (there were actually quite a few very minor flaws).

A remaining point of confusion that documentation alone can't fix: `regr_sxx` / `regr_sxy / `regr_syy` currently compute (sample) variances in duckdb but sums-of-squares in snowflake. This doesn't affect the regression slopes and intercepts though, since those use fractions, where the difference cancels out.

By the way: In my above I really meant `regr_sxx(y, x)`, not `covar_pop(x, x)` (which is actually the same as `var_pop(x, x)`). In any case, it's really best to think of this all as: (1) First filter out pairs where either Y or X is NULL. (2) Then, `regr_slope = regr_sxy / regr_sxx = covar_pop / var_pop = covar_samp / var_samp`
