### ISSUE TITLE
Parquet hive partition write error with OVERWRITE_OR_IGNORE - Deleting other partition data

### ISSUE THREAD

**Issue by jrothbaum** [duckdb/duckdb#12324]
### What happens?

I am looping over a series of datasets to create a partitioned parquet file by year and state of the following form:
* fips={US State FIPS Code}
	* year={year}

The command is:
copy df to '{partition_path}' (FORMAT PARQUET, COMPRESSION zstd, OVERWRITE_OR_IGNORE 1, PARTITION_BY ("fips","year"));

This exact code runs without issue on python duckdb 9.2.

On duckdb 10.3, when I loop over a state-year, it adds the new data, while deleting all the files *.parquet files in any other state-year combination.  It does, however, leave the folders intact.  So if I run on 1) fips=15, year=2018, then 2) fips=15, year=2019.  After 2), there will be a folder /fips=15/year=2018/ that is empty (but had data after 1) and another /fips=15/year=2019/ with the 2019 data in it.

### To Reproduce

I can't share my code, to this unfortunately.  It is effectively as follows, though:

import polars as pl
import duckdb

df1 = ... polars code to load the data for where year = 2018 (or some fixed value for all observations) and fips = 15 (or some fixed value for all observations)
df2 = ... polars code to load the data for where year = 2019 (or some fixed value for all observations) and fips = 15 (or some fixed value for all observations)

con = duckdb.connect()
#code to set threads and memory_limit
con.sql('copy df1 to '{partition_path}' (FORMAT PARQUET, COMPRESSION zstd, OVERWRITE_OR_IGNORE 1, PARTITION_BY ("fips","year"));')
con.sql('copy df2 to '{partition_path}' (FORMAT PARQUET, COMPRESSION zstd, OVERWRITE_OR_IGNORE 1, PARTITION_BY ("fips","year"));')

### OS:

x86_64

### DuckDB Version:

10.3

### DuckDB Client:

Python

### Full Name:

Jonathan Rothbaum

### Affiliation:

U.S. Census Bureau

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by jrothbaum** [comment]
I should add that the actual code is running in each state-year combination in separate, parallel jobs, so it's possible that the con.sql calls are happening at the same time.

**Comment by djouallah** [comment]
the behavior was changed in 0.10 but reverted back, just wait for the next release 0.10.4

https://github.com/duckdb/duckdb/pull/12240

**Comment by Mytherin** [comment]
Thanks for the report! As mentioned this has already been fixed
