### ISSUE TITLE
Treatment of interval type in Python

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#12339]
### What happens?

I noticed some idiosyncrasies with how the interval type gets treated in the Python bindings. The most glaring manifestation is that it will report that a year is 360 days:

### To Reproduce

```python
import duckdb

with duckdb.connect(database=':memory:') as conn:
    print(conn.execute("select interval 1 year as year").df())

>       year
> 0 360 days
```

This appears to be because the [conversion code](https://github.com/duckdb/duckdb/blob/c3903e44e0d70f4fae6d9c068c0792ebc62b882f/tools/pythonpkg/src/native/python_objects.cpp#L620) uses a value of [30 days per month](https://github.com/duckdb/duckdb/blob/c3903e44e0d70f4fae6d9c068c0792ebc62b882f/src/include/duckdb/common/types/interval.hpp#L92).

Even if that better handled year intervals, it seems strange that intervals get converted to `Timedelta` values which as documented [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#overview) are absolute time durations. By comparison if you first convert to Arrow and then to Pandas you will end up with `DateOffset` values which seem like a closer fit with how intervals work within duckdb.

### OS:

macOS, Linux

### DuckDB Version:

0.10.3

### DuckDB Client:

Python

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by makaveli2P** [comment]
Hey, I saw this issue and was trying to understand the codebase. 


Is there a reason for [30 days per month](https://github.com/duckdb/duckdb/blob/c3903e44e0d70f4fae6d9c068c0792ebc62b882f/src/include/duckdb/common/types/interval.hpp#L92) for interval purposes.
```
//! only used for interval comparison/ordering purposes, in which case a month counts as 30 days
static constexpr const int64_t DAYS_PER_MONTH = 30;
```

can it be considered to have DAYS_PER_MONTH as an average of the DAYS_PER_YEAR and MONTHS_PER_YEAR
```
static constexpr const int64_t DAYS_PER_MONTH = DAYS_PER_YEAR/MONTHS_PER_YEAR;
```
The [interval calculation](https://github.com/duckdb/duckdb/blob/c3903e44e0d70f4fae6d9c068c0792ebc62b882f/tools/pythonpkg/src/native/python_objects.cpp#L620)  would be 365 days

```
int64_t days = duckdb::Interval::DAYS_PER_MONTH * interval_value.months + interval_value.days;
```
