### ISSUE TITLE
read_csv with with store_rejects=true does not work as intented with constraints

### ISSUE THREAD

**Issue by teucer** [duckdb/duckdb#12331]
### What happens?

I get an constraint error when reading a faulty csv file.

### To Reproduce

```sql
CREATE TABLE users ( 
        id INTEGER NOT NULL,  /*primary key*/
        name VARCHAR(10) NOT NULL,  
        email VARCHAR,
        CONSTRAINT pk_users PRIMARY_KEY (id)
);

INSERT INTO users
SELECT *
FROM read_csv('data.csv', store_rejects=true, null_padding=true); 
``` 

data.csv:

id,name,email 
1,alice,alice@email.com 
2,eve, 
3r,bob, 
2,jack

**error**: PRIMARY KEY or UNIQUE constraint failed

I would have expected the loading to continue and duckdb to log the 4th row to "reject_errors" table 

### OS:

x64

### DuckDB Version:

0.10.3

### DuckDB Client:

Python

### Full Name:

NA

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for the report, the error is unrelated to `read_csv` however.
`read_csv` `store_rejects` handles errors that happen during reading of the csv file
This error originates from writing the data to the table, which is not related to csv read.

The constraint information could perhaps be pushed down into the csv reader so it's aware and can act accordingly, but that's definitely a feature request

**Comment by teucer** [comment]
Thank you for your answers. How could I add such cases to reject_errors table? My goal is to use duckdb + sqlalchemy as a data quality assessment framework.

**Comment by Mytherin** [comment]
The `reject_errors` table is specifically meant for finding errors within CSV files. Duplicate keys is not an error within a CSV file but a manually inserted constraint. As such you would need to do this outside of the rejects table.
