### ISSUE TITLE
Issue with Python duckdb.read_csv not working with 0.10.2+

### ISSUE THREAD

**Issue by obronco** [duckdb/duckdb#12338]
### What happens?

Reading from a StringIO buffer works in 0.10.1, but not in 0.10.2 or 0.10.3.

### To Reproduce

download the csv files from:

* https://www.dropbox.com/scl/fi/3xpwlfgfc0seoe4lw3vwk/cad_fi_cp1252.csv?rlkey=2wanizbvs6nr7tzrgwvquj6mf&dl=1
* https://www.dropbox.com/scl/fi/anbvm5n9gpp0dgxfanipp/cad_fi_utf8.csv?rlkey=mxdqw3disqn12lqb4d88j6woo&dl=1

and run the following script:

from io import StringIO

import duckdb

def load_csv(filename, encoding, newline="\r\n"):
    with open(filename, "rb") as fp:
        content = fp.read().decode(encoding)
        _buffer = StringIO(content.replace(newline, "\n"), newline="\n")
        return duckdb.read_csv(
            _buffer,
            normalize_names=True,
            sample_size=-1,
        )

cad_fi_utf8 = load_csv("cad_fi_utf8.csv", "utf-8")
cad_fi_cp1252 = load_csv("cad_fi_cp1252.csv", "cp1252")

assert (
    duckdb.sql("SELECT count(*) FROM cad_fi_utf8").fetchone()
    == duckdb.sql("SELECT count(*) FROM cad_fi_cp1252").fetchone()
), "Different number of rows"

### OS:

Windows 11

### DuckDB Version:

0.10.3

### DuckDB Client:

0.10.3

### Full Name:

Leo Horta

### Affiliation:

Sparta Fundos de Investimento

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by obronco** [comment]
Running the following command in duckdb cli works in v0.10.1, but not in v0.10.3:

select * from 'cad_fi_utf8.csv';

If the sample_size is set to -1 or a number big enough, both work:

select * from read_csv('cad_fi_utf8.csv', sample_size=-1);

78864 rows, 41 columns

**Comment by Tishj** [comment]
That makes me think that the python API is not the cause and using the `read_csv` method directly through SQL has the same result

**Comment by obronco** [comment]
This works in v0.10.1, but not in v0.10.3:

def load_csv(filename, encoding, newline="\r\n"):
    with open(filename, "rb") as fp:
        content = fp.read().decode(encoding)
        _buffer = StringIO(content.replace(newline, "\n"), newline="\n")
        return duckdb.read_csv(
            _buffer,
            normalize_names=True,
            sample_size=-1,
        )


cad_fi_utf8 = load_csv("data/cad_fi_utf8.csv", "utf-8")
assert duckdb.sql("SELECT count(*) FROM cad_fi_utf8").fetchone() == (78864,), "Wrong number of rows"

assert duckdb.sql("SELECT count(*) FROM cad_fi_utf8").fetchone() == (78864,), "Wrong number of rows"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: CSV Error on Line: 426
Original Line: FIDC;13.039.712/0001-66;FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS PREMIUM SOLIS;2010-12-29;2011-01-11;210104;;EM FUNTP_FUNDO;CNPJ_FUNDO;DENOM_SOCIAL;DT_REG;DT_CONST;CD_CVM;DT_CANCEL;SIT;DT_INI_SIT;DT_INI_ATIV;DT_INI_EXERC;DT_FIM_EXERC;CLASSE;DT_INI_CLASSE;RENTAB_FUNDO;CONDOM;FUNDO_COTAS;FUNDO_EXCLUSIVO;TRIB_LPRAZO;PUBLICO_ALVO;ENTID_INVEST;TAXA_PERFM;INF_TAXA_PERFM;TAXA_ADM;INF_TAXA_ADM;VL_PATRIM_LIQ;DT_PATRIM_LIQ;DIRETOR;CNPJ_ADMIN;ADMIN;PF_PJ_GESTOR;CPF_CNPJ_GESTOR;GESTOR;CNPJ_AUDITOR;AUDITOR;CNPJ_CUSTODIANTE;CUSTODIANTE;CNPJ_CONTROLADOR;CONTROLADOR;INVEST_CEMPR_EXTER;CLASSE_ANBIMA
Expected Number of Columns: 41 Found: 42
Possible fixes:
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file=
  delimiter = ; (Set By User)
  quote = \0 (Set By User)
  escape = \0 (Set By User)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Set By User)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=18446744073709549568
  ignore_errors=false
  all_varchar=0

**Comment by obronco** [comment]
As I try different combinations of read_csv parameters, the error is thrown at different lines. The line where the error happened is shown with header columns appended.

**Comment by Tishj** [comment]
Can you verify if this same problem is present when reading from a file using pure SQL?
I'm just trying to narrow down if this is a problem in the Python API or a regression in read_csv in general

**Comment by obronco** [comment]
By pure SQL you mean using the CLI ? I tested it above with duckdb.exe v0.10.1 and v0.10.3 in Windows. To make it work in v0.10.3 I needed to include a larger sample_size:

Running the following command in duckdb cli works in v0.10.1, but not in v0.10.3:

select * from 'cad_fi_utf8.csv';

If the sample_size is set to -1 or a number big enough, both work:

select * from read_csv('cad_fi_utf8.csv', sample_size=-1);

78864 rows, 41 columns

**Comment by obronco** [comment]
Tested v0.10.1 vs v0.10.3 duckdb cli in WSL2. The csv file from the dropbox download had some issue with encoding. Downloaded a new one from the source: https://dados.cvm.gov.br/dados/FI/cad/DADOS/cad_fi.csv. Had to convert it to utf-8 using 'iconv -f windows-1252 -t utf-8 cad_fi.csv -o cad_fi_utf8.csv'. The behaviour was the same as above, had to adjust the sample_size, but at least got a more interesting error message in v0.10.3:

Invalid Input Error: CSV Error on Line: 43558
Original Line:
FI;37.267.399/0001-81;SANTANDER PB ALOCAÇÃO AÇÕES LONG ONLY FIC FI;2020-10-27;2020-04-30;381373;;EM FUNCIONAMENTO NORMAL;2020-10-29;2020-10-29;2024-01-01;2024-12-31;Fundo de Ações;2020-04-30;Índice de Preços ao Consumidor Amplo (IPCA/IBGE);Aberto;S;N;;Qualificado;;10;"1" é calculado de acordo com a seguinte fórmula: média ponderada, calculada diariamente, das taxas indicativas dos títulos que compõem o índice IMA-B de acordo com o peso dos títulos na composição do próprio índice, de acordo com as taxas diárias divulgadas pela ANBIMA - Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais, em seu website.;1;;72689801.68;2024-05-28;ALESSANDRO CHAGAS FARIAS;03.502.968/0001-04;SANTANDER DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.;PJ;03.502.968/0001-04;SANTANDER DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.;61.366.936/0001-25;ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.;62.318.407/0001-19;S3 CACEIS BRASIL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS S.A;62.318.407/0001-19;S3 CACEIS BRASIL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS S.A;N;Ações Livre
Value with unterminated quote found.

**Comment by pdet** [comment]
Opa Leonardo, tudo bem? :-)

I tested the  
```sql
select count(*) from read_csv('cad_fi_utf8.csv', sample_size=-1)
```
and it seems to work fine.

Notice that 
```sql
select count(*) from read_csv('cad_fi_utf8.csv')
```
will fail because the sniffer only sniffs the first 20480 lines, and it will not detect that " should not be a quoted option.

You can tell that from the line 
`FI;37.267.399/0001-81;SANTANDER PB ALOCAÇÃO AÇÕES LONG ONLY FIC FI;2020-10-27;2020-04-30;381373;;EM FUNCIONAMENTO NORMAL;2020-10-29;2020-10-29;2024-01-01;2024-12-31;Fundo de Ações;2020-04-30;Índice de Preços ao Consumidor Amplo (IPCA/IBGE);Aberto;S;N;;Qualificado;;10;"1" é calculado de acordo com a seguinte fórmula: média ponderada, calculada diariamente, das taxas indicativas dos títulos que compõem o índice IMA-B de acordo com o peso dos títulos na composição do próprio índice, de acordo com as taxas diárias divulgadas pela ANBIMA - Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais, em seu website.;1;;72689801.68;2024-05-28;ALESSANDRO CHAGAS FARIAS;03.502.968/0001-04;SANTANDER DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.;PJ;03.502.968/0001-04;SANTANDER DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.;61.366.936/0001-25;ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.;62.318.407/0001-19;S3 CACEIS BRASIL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS S.A;62.318.407/0001-19;S3 CACEIS BRASIL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS S.A;N;Ações Livre`
the value
`"1" é calculado de acordo com a seguinte fórmula: média ponderada, calculada diariamente, das taxas indicativas dos títulos que compõem o índice IMA-B de acordo com o peso dos títulos na composição do próprio índice, de acordo com as taxas diárias divulgadas pela ANBIMA - Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais, em seu website.` is poorly quoted.

Another option is to instead of setting the sample size to -1, you can also set it the quote value to something other than `"`.
e.g.,
`select count(*) from read_csv('cad_fi_utf8.csv', quote='')`

I ran these based in feature, so please try them out on a feature build and let me know if it works or if you still have any questions!

**Comment by obronco** [comment]
Thanks for the reply. It seems the CLI is fine, so the python API is the probable cause. The following code works (all tests pass) in v0.10.1, but not in v0.10.3 and v1.0.0:

csv files: [cad_fi.zip](https://github.com/user-attachments/files/15534895/cad_fi.zip)

test.py:

from io import StringIO

import duckdb

print("DuckDB version:", duckdb.__version__)


def load_csv(filename, encoding, newline="\r\n"):
    with open(filename, "rb") as fp:
        # Bytes to string
        content = fp.read().decode(encoding)
        # Normalize newlines
        _buffer = StringIO(content.replace(newline, "\n"), newline="\n")
        return duckdb.read_csv(
            _buffer,
            normalize_names=True,
            sample_size=-1,
        )


cad_fi = load_csv("cad_fi.csv", "utf-8")
assert duckdb.sql("SELECT count(*) FROM cad_fi").fetchone() == (
    78894,
), "Wrong number of rows"

cad_fi_cp1252 = load_csv("cad_fi_cp1252.csv", "cp1252")
assert duckdb.sql("SELECT count(*) FROM cad_fi_cp1252").fetchone() == (
    78894,
), "Wrong number of rows"

print("All tests passed!")

Results:

DuckDB version: 0.10.1
All tests passed!

DuckDB version: 0.10.3
Traceback (most recent call last):
  File "C:\Users\leonardo.horta\OneDrive - Sparta Fundos de Investimento\containers\duckdb-debug\test.py", line 22, in <module>
    assert duckdb.sql("SELECT count(*) FROM cad_fi").fetchone() == (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: CSV Error on Line: 428
Original Line: FIDC;12.796.029/0001-00;FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS MERCANTIS AUTO PEÇAS;2014-04-23;2014-06-02;214037;;EM FUNCIONAMENTTP_FUNDO;CNPJ_FUNDO;DENOM_SOCIAL;DT_REG;DT_CONST;CD_CVM;DT_CANCEL;SIT;DT_INI_SIT;DT_INI_ATIV;DT_INI_EXERC;DT_FIM_EXERC;CLASSE;DT_INI_CLASSE;RENTAB_FUNDO;CONDOM;FUNDO_COTAS;FUNDO_EXCLUSIVO;TRIB_LPRAZO;PUBLICO_ALVO;ENTID_INVEST;TAXA_PERFM;INF_TAXA_PERFM;TAXA_ADM;INF_TAXA_ADM;VL_PATRIM_LIQ;DT_PATRIM_LIQ;DIRETOR;CNPJ_ADMIN;ADMIN;PF_PJ_GESTOR;CPF_CNPJ_GESTOR;GESTOR;CNPJ_AUDITOR;AUDITOR;CNPJ_CUSTODIANTE;CUSTODIANTE;CNPJ_CONTROLADOR;CONTROLADOR;INVEST_CEMPR_EXTER;CLASSE_ANBIMA
Expected Number of Columns: 41 Found: 42
Possible fixes:
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file=
  delimiter = ; (Set By User)
  quote = \0 (Set By User)
  escape = \0 (Set By User)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Set By User)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=18446744073709549568
  ignore_errors=false
  all_varchar=0

DuckDB version: 1.0.0
Traceback (most recent call last):
  File "C:\Users\leonardo.horta\OneDrive - Sparta Fundos de Investimento\containers\duckdb-debug\test.py", line 22, in <module>
    assert duckdb.sql("SELECT count(*) FROM cad_fi").fetchone() == (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: CSV Error on Line: 428
Original Line: FIDC;12.796.029/0001-00;FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS MERCANTIS AUTO PEÇAS;2014-04-23;2014-06-02;214037;;EM FUNCIONAMENTTP_FUNDO;CNPJ_FUNDO;DENOM_SOCIAL;DT_REG;DT_CONST;CD_CVM;DT_CANCEL;SIT;DT_INI_SIT;DT_INI_ATIV;DT_INI_EXERC;DT_FIM_EXERC;CLASSE;DT_INI_CLASSE;RENTAB_FUNDO;CONDOM;FUNDO_COTAS;FUNDO_EXCLUSIVO;TRIB_LPRAZO;PUBLICO_ALVO;ENTID_INVEST;TAXA_PERFM;INF_TAXA_PERFM;TAXA_ADM;INF_TAXA_ADM;VL_PATRIM_LIQ;DT_PATRIM_LIQ;DIRETOR;CNPJ_ADMIN;ADMIN;PF_PJ_GESTOR;CPF_CNPJ_GESTOR;GESTOR;CNPJ_AUDITOR;AUDITOR;CNPJ_CUSTODIANTE;CUSTODIANTE;CNPJ_CONTROLADOR;CONTROLADOR;INVEST_CEMPR_EXTER;CLASSE_ANBIMA
Expected Number of Columns: 41 Found: 42
Possible fixes:
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file=
  delimiter = ; (Set By User)
  quote = \0 (Set By User)
  escape = \0 (Set By User)
  new_line = \n (Auto-Detected)
  header = true (Set By User)
  skip_rows = 0 (Set By User)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=18446744073709549568
  ignore_errors=false
  all_varchar=0

**Comment by obronco** [comment]
I've noticed a difference in the `sniff_csv` function's behavior. In DuckDB version 0.10.1, the escape and quote characters are determined as `\0` with the default sample size. However, in version 0.10.3 and later, they are correctly identified as `"`. It seems there was a bug in the earlier version that left the escape and quote characters as `\0`, which inadvertently solved my parsing error by ignoring poorly quoted fields. When this bug was fixed, it broke my application.

Now, there's seems to be another issue in the Python API: I can't override the quote and escape characters to correctly parse my poorly quoted CSV file.

**Comment by obronco** [comment]
Anyone observed this commentary: "I can't override the quote and escape characters to correctly parse my poorly quoted CSV file."

**Comment by DanCranford** [comment]
I'm also experiencing this issue in SQL.  I'm using DBeaver.  I'm currently running DuckDB 1.0.0 and experiencing the following error.
```
SQL Error: Invalid Input Error: CSV Error on Line: 38498
Original Line: 0001684166,130123,"Big Bend Telephone Company, Inc",1094499274,60,0,0,0,X,TX,483719505003312,88488d45adfffff
Expected Number of Columns: 12 Found: 13
Possible fixes:
* Enable ignore errors (ignore_errors=true) to skip this row

  file=C:\Users\dav11274\Desktop\Projects\TX Broadband\Keith Script\input_data\bdc\bdc_48_Cable_fixed_broadband_D23_09jul2024.csv
  delimiter = , (Auto-Detected)
  quote = \0 (Auto-Detected)
  escape = \0 (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Auto-Detected)
  skip_rows = 0 (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=1
  sample_size=20480
  ignore_errors=false
  all_varchar=0
```

In DuckDB 0.10.0 and before, this was not an issue.  I can see that the issue is that I have a comma inside a string that is confusing the CSV reader.  I would prefer not to read and rewrite this CSV to change the delimiter.  Any thoughts?

**Comment by pdet** [comment]
> I'm also experiencing this issue in SQL. I'm using DBeaver. I'm currently running DuckDB 1.0.0 and experiencing the following error.
> 
> ```
> SQL Error: Invalid Input Error: CSV Error on Line: 38498
> Original Line: 0001684166,130123,"Big Bend Telephone Company, Inc",1094499274,60,0,0,0,X,TX,483719505003312,88488d45adfffff
> Expected Number of Columns: 12 Found: 13
> Possible fixes:
> * Enable ignore errors (ignore_errors=true) to skip this row
> 
>   file=C:\Users\dav11274\Desktop\Projects\TX Broadband\Keith Script\input_data\bdc\bdc_48_Cable_fixed_broadband_D23_09jul2024.csv
>   delimiter = , (Auto-Detected)
>   quote = \0 (Auto-Detected)
>   escape = \0 (Auto-Detected)
>   new_line = \n (Auto-Detected)
>   header = true (Auto-Detected)
>   skip_rows = 0 (Auto-Detected)
>   date_format =  (Auto-Detected)
>   timestamp_format =  (Auto-Detected)
>   null_padding=1
>   sample_size=20480
>   ignore_errors=false
>   all_varchar=0
> ```
> 
> In DuckDB 0.10.0 and before, this was not an issue. I can see that the issue is that I have a comma inside a string that is confusing the CSV reader. I would prefer not to read and rewrite this CSV to change the delimiter. I can skirt the issue by increasing the sample size to 100k, but I'm curious as to how to mitigate this in the future.

You can also set the quote to `"`.
