### ISSUE TITLE
cli: Stuck at the intialization

### ISSUE THREAD

**Issue by semsphy** [duckdb/duckdb#12350]
### What happens?

It just stuck on the initialization, I can't use it.

```
❯ duckdb
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```

### To Reproduce

From the terminal, just run `duckdb`

```
❯ duckdb
```

### OS:

MacOS sonoma 14.5 (23F79)

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

cli

### Full Name:

Sophy SEM

### Affiliation:

Go24 Cambodia

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by Mause** [comment]
What's the contents of the .duckdbrc file in your home directory?

**Comment by Tishj** [comment]
Can you test with the latest release?

**Comment by carlopi** [comment]
How did you obtained the binary ? `homebrew` or downloaded from our releases? or compiled from source?

You can likely track this down by doing `which duckdb` that should point to the path to the actual binary.

**Comment by szarnyasg** [comment]
@semsphy, v1.0.0 came out yesterday, and is available in Brew. Can you please give it a try?

**Comment by carlopi** [comment]
Can you report the output of: `tree ~/.duckdb` ?

Thanks

**Comment by rocholojavinar** [comment]
![IMG](https://img.youtube.com/vi/yHU6g3-35IU/maxresdefault.jpg)

**Comment by carlopi** [comment]
Semi random guess: could it be that you at some point executed `sudo duckdb`, and that somehow has some of the relevant files have the wrong permissions.

Unsure how that leads to deadlock, it will not using current duckdb, but it's entirely possible that some older version would set the wrong permissions (if run with too high privileges).

I think those files are of interest: `~/.duckdbrc`, `~/.duckdb_history` and the `~/.duckdb` folder or subfolders.

@semsphy: can you possibly do `ls -la ~/.duckdbrc ~/.duckdb_history ~/.duckdb` and post it here? Thanks

Only other env variable that could modify this is `printenv DUCKDB_HISTORY`, if that points to a file, that file's permission might also be relevant.

As a workaround, deleting (possibly with `sudo`) all or ~/.duckdbrc, ~/.duckdb_history and ~/.duckdb should allow you to move forward with regular duckdb.

(adding needs documentation for the part where we might want to explain what files are ever read by DuckDB on a given computer)

**Comment by rocholojavinar** [comment]
![IMG](https://img.youtube.com/vi/CyD8hAjj8L8/maxresdefault.jpg)

What thumbnail is that?

**Comment by maurice1408** [comment]
This "stuck in initialization" also happened to me today. Running duckdb under strace showed that the last thing it did was open .duckdb_history, looking at that it turned out that the history file was ~1Gb - I think I did a .read on a data file rather than a sql file at some point. Deleting the history file resolved this.

**Comment by rocholojavinar** [comment]
![](https://img.youtube.com/vi/sXZk9u3I_EI/maxresdefault.jpg)

**Comment by carlopi** [comment]
I think this can be closed, we will document the findings here in the docs, thanks you all for raising / contributing on this.

**Comment by rocholojavinar** [comment]
![](https://img.youtube.com/vi/VSxuNRF8RHY/maxresdefault.jpg)
