### ISSUE TITLE
DuckDB throws InternalError when creating a table from an empty DataFrame with a categoric column

### ISSUE THREAD

**Issue by whyhive-simon** [duckdb/duckdb#12364]
### What happens?

I received an inscrutable internal error from DuckDb under certain conditions in my app;
```
con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
duckdb.duckdb.InternalException: INTERNAL Error: Information loss on integer cast: value -1 outside of target range [0, 255]
```

Upon digging, and paring back details of my use case I found that the cause was when creating a table from an empty pandas DataFrame which included a categoric column.

I understand this may be a bit of an invalid edge case, but a more intelligible error message would have made it easier to debug.

### To Reproduce

Reproduction script:

```
import pandas as pd
import duckdb

con = duckdb.connect()

data = {'category': pd.Categorical(['A', 'B', 'C'])}
populated_categoric_df = pd.DataFrame(data)

con.execute("CREATE TABLE test AS SELECT * FROM populated_categoric_df")

empty_categoric_df = pd.DataFrame({'category': pd.Series(dtype='category')})

print(empty_categoric_df)
print(empty_categoric_df.dtypes)
print(empty_categoric_df['category'].cat.categories)
print(empty_categoric_df['category'].cat.codes)

con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
```

The former case works, of course, the latter throws the error.

Output from the above reproduction script:
```
Empty DataFrame
Columns: [category]
Index: []
category    category
dtype: object
Index([], dtype='object')
Series([], dtype: int8)
Traceback (most recent call last):
  File <redacted>, line 18, in <module>
    con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
duckdb.duckdb.InternalException: INTERNAL Error: Information loss on integer cast: value -1 outside of target range [0, 255]
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### OS:

linux/amd64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Simon Grant

### Affiliation:

n/a

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by whyhive-simon** [comment]
My workaround for the issue:

```
            if df.empty:
                for col in df.select_dtypes(include='category').columns:
                    df[col] = df[col].astype(str)
            connection.sql(f"CREATE TABLE {name} AS SELECT * FROM df")
```

**Comment by Tishj** [comment]
Thanks for the report

Just out of curiosity, what is the use case of this? This would create an ENUM with no entries, which isn't particularly useful.
The fix will likely be to disallow this and throw a non-fatal exception instead

**Comment by whyhive-simon** [comment]
So my app ingests data, cleans it and stores it.  Any invalid data is saved to a parquet file and potentially retrieved via duckdb later on (if its to be re-evaluated).  The invalid-data table is created based on the schema of the original table but in some cases may be empty (i.e. if all the table data is valid) - so while there is a concept out there of the categories available to the column, I wasn't specifying them in the columns' dtype.

So, since this works
```
con = duckdb.connect()
empty_categoric_df = pd.DataFrame({'category': pd.Series(dtype=CategoricalDtype(categories=list("abcd")))})

con.execute("CREATE TABLE test AS SELECT * FROM empty_categoric_df")
```
My real solution is to ensure the categoric dtype isn't relying on the default behavior to populate categories.

I think, from my POV, I'd probably expect the empty categoric column to be accepted even if it's seemingly useless.  But the main thing I'd have needed was just an error message that spoke to the problem since I can rectify the situation.
