### ISSUE TITLE
Timezones for timestamp columns are changed during conversion from Arrow

### ISSUE THREAD

**Issue by pablodcar** [duckdb/duckdb#12368]
### What happens?

Arrow columns with timezone information are changed to local when reading from a Pyarrow Table.

### To Reproduce

1. Create a table with a column of type timestamp with timezone
```python
import pyarrow
import duckdb
from datetime import *

timestamps = pyarrow.Table.from_pylist([{"ts": datetime.now(UTC)}])
timestamps.schema
```
```console
>>> ts: timestamp[us, tz=UTC]
```

2. Query the table using DuckDB and transform the result back to Python/Arrow
```python
duckdb.execute("SELECT * FROM timestamps").fetchall()
```
```console
>>> [(datetime.datetime(2024, 6, 4, 10, 34, 22, 414862, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>),)]
```

Timestamp column's timezones are changed to my local timezone.

### OS:

iOS

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Pablo Carballo

### Affiliation:

Revolut

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks for the report

I believe this is expected behavior
Timestamp tz columns don't store a timezone, instead the timezone is stored in the connection (`set timezone='utc'`) and is applied to the column when it's displayed to the user or converted to a string

**Comment by soerenwolfers** [comment]
That's unavoidable: duckdb (like PostgreSQL) doesn't store timezones, despite the data type being called `TIMESTAMPTZ`. Have a look at https://duckdb.org/2022/01/06/time-zones.html

**Comment by soerenwolfers** [comment]
See also https://duckdb.org/docs/sql/functions/timestamptz.html: 

```
Despite the name, these values do not store a time zone – just an instant like TIMESTAMP. Instead, they request that the instant be binned and formatted using the current time zone.
```

**Comment by pablodcar** [comment]
> That's unavoidable: duckdb (like PostgreSQL) doesn't store timezones, despite the data type being called `TIMESTAMPTZ`. Have a look at https://duckdb.org/2022/01/06/time-zones.html

AFAIK Postgres displays datetime with timezone as UTC. from Postgres docs:

"The appropriate time zone offset is recorded in the time with time zone value and is output as stored; it is not adjusted to the active time zone."

> See also https://duckdb.org/docs/sql/functions/timestamptz.html:
> 
> ```
> Despite the name, these values do not store a time zone – just an instant like TIMESTAMP. Instead, they request that the instant be binned and formatted using the current time zone.
> ```
> 
> It takes some getting used to when coming from another ecosystem, but, IMO, it's almost always cleaner.

Interesting, I found it surprising, since the output depends on which machine it runs.

**Comment by soerenwolfers** [comment]
Huh, seems I was wrong about PostgreSQL.

**Comment by hawkfish** [comment]
> The appropriate time zone offset is recorded in the time with time zone value and is output as stored; it is not adjusted to the active time zone.

This is `time with time zone`, not `timestamp with time zone`. `time with time zone` is also poorly named by the SQL standards committee and actually means `time with offset`. So yes it stores an offset (not a TZ!).

**Comment by Mytherin** [comment]
As mentioned this is expected behavior - DuckDB has Postgres semantics w.r.t. time zones. `TIME WITH TIME ZONE` stores the offset with each value, but `TIMESTAMP WITH TIME ZONE` does not. You can change the time zone value you get back using the `TimeZone` setting (e.g. `SET TimeZone='UTC'`).

**Comment by hawkfish** [comment]
@pablodcar have we answered your questions? I'm pretty sure that all that is happening is that the instants are coming back into Arrow with the current TZ setting. No data should have been lost, just the TZ information.  If that is different for each row, then you should add a `VARCHAR` column to the table. Otherwise, you can change the TZ that DuckDB uses for temporal binning to `UTC` with `SET TimeZone='UTC'`. This will also attach the TZ information to Arrow exports. 

You might consider using timestamps without time zone - binning for `TIMESTAMP` is significantly faster.

**Comment by pablodcar** [comment]
Hi @Mytherin and @hawkfish .

Thanks for the answers, I understand how it behaves and why this is expected now.
