### ISSUE TITLE
Weird behavior inserting polars df into duckdb table when same columns diff order

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [duckdb/duckdb#12363]
### What happens?

duckdb seems not to recognize polars df column names as expected, or as I expected, when:
* inserting a polars df into a duckdb table, and
* when the order of the polars df columns may vary from the order of those same columns in the duckdb table

### To Reproduce

```
import polars as pl
import duckdb
import pyarrow as pa

df1 = pl.DataFrame({'mynum': [1, 2, 3], 'mystr': ['a', 'b', 'c']})
df2 = pl.DataFrame({'mystr': ['d', 'e', 'f'], 'mynum': [4, 5, 6]})
with duckdb.connect(database="S:\IsForStaging\max_staging.db", read_only=False) as conn:
    conn.execute(f'CREATE TABLE test_table AS SELECT * FROM df1;')

with duckdb.connect(database="S:\IsForStaging\max_staging.db", read_only=False) as conn:
    conn.execute(f'INSERT INTO test_table SELECT * FROM df2;')
```
throws error:
```
duckdb.duckdb.ConversionException: Conversion Error: Could not convert string 'd' to INT64
```

### OS:

windows server and ubuntu

### DuckDB Version:

0.10.3

### DuckDB Client:

python

### Full Name:

Max Epstein

### Affiliation:

Max Power Consulting, LLC

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
By default INSERT works on position, it sounds like you're looking for <https://duckdb.org/docs/sql/statements/insert#insert-into--by-name>

**Comment by Mytherin** [comment]
Thanks for reporting - as mentioned `INSERT INTO` is positional in SQL. `INSERT BY NAME` is provided in case you would prefer to match columns by name instead of by position.
