### ISSUE TITLE
DuckDB v1.0.0 released

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#12374]
We have released DuckDB v1.0.0. See the [announcement blog post](https://duckdb.org/2024/06/03/announcing-duckdb-100) for details.

**Comment by vsevolod-volkov** [comment]
The latest usable tag I see in duckdb/duckdb-swift repository is v0.10.3, and only "...dev" tags follow that.
How do I use Swift Client API with DuckDB v1.0.0? Thanks.
