### ISSUE TITLE
READ_CSV doesn't release memory in between files it imports

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb#12389]
### What happens?

I'm having another look at the [1.1B taxi rides benchmark](https://tech.marksblogg.com/duckdb-1b-taxi-rides.html) with v1.0.0 that was just released on Windows 11. Since that post, I've upgraded to 96 GB of DDR5.

I was hoping to make a single call to `read_csv` with a glob and have it import the 56 GZIP-ed CSVs (~104 GB compressed) into a DuckDB table. With past versions of DuckDB, I'd run out of memory and have to individually import each file one at a time to allow DuckDB to release memory between imports.

I've tried running the following insert statement:

```sql
INSERT INTO trips
    SELECT *
    FROM READ_CSV('../taxi/trips*.csv.gz');
```

With the first attempt, 75 GB of RAM was allocated before DuckDB raised the following issue:

```
Out of Memory Error: failed to pin block of size 256.0 KiB (75.0 GiB/75.0 GiB used)
```

I was hoping with the 48 GB limit that read_csv would find a way to work in a constrained environment but instead, I got this error message:

```sql
SET memory_limit = '48GB';
SET max_memory = '48GB';

INSERT INTO trips
    SELECT *
    FROM READ_CSV('../taxi/trips*.csv.gz');
```

```
Out of Memory Error: could not allocate block of size 30.5 MiB (44.7 GiB/44.7 GiB used)
```

Is there some way `read_csv` could release memory in between each file being imported like it would if I called it for each file individually?

### To Reproduce

See the above

### OS:

Windows 11

### DuckDB Version:

v1.0.0

### DuckDB Client:

duckdb.exe

### Full Name:

Mark Litwintschik

### Affiliation:

Green Idea

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! I can reproduce the high memory pressure when reading many large gzipped CSV files in parallel. A work-around for me seems to be to limit the threads while ingesting (`SET threads=1`). Perhaps you could give that a shot?

We'll have a look to see if we can improve memory utilisation here.

**Comment by marklit** [comment]
DuckDB loaded in 14% of the data before it crashed. I'll pick up on this at some point when I have more time available.

**Comment by marklit** [comment]
That was quick, thanks. I'll have another look when the next DuckDB release comes out and my schedule frees up a bit.
