### ISSUE TITLE
Review patches from duckdb-r

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#12385]
### What happens?

I have accumulated a set of patches I'm applying after vendoring the duckdb source into the R package. Could some of those be upstreamed? Happy to discuss!

### To Reproduce

https://github.com/duckdb/duckdb-r/tree/main/patch

### OS:

all

### DuckDB Version:

main

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
All of the uninitialized-move patches look good to me. Could you upstream those?
