### ISSUE TITLE
[C-API] Problem adding empty strings to vector with duckdb_vector_assign_string_element[_len]. 

### ISSUE THREAD

**Issue by ajzo90** [duckdb/duckdb#12380]
### What happens?

While using/implementing table UDF from go-duckdb.

Having problem inserting empty strings to a `duckdb_vector` with the C API. Instead of empty string it looks like `""` is inserted. Selecting `len(col)` confirms that the length is in fact 2.

Same result with both functions:
```
v = []byte{0}
cstr := (*C.char)(unsafe.Pointer(&v[0]))
C.duckdb_vector_assign_string_element(d.vector, C.uint64_t(d.pos), cstr)
```

and 
```
C.duckdb_vector_assign_string_element_len(d.vector, C.uint64_t(d.pos), nil, C.idx_t(0))
```

Most cases is likely covered by NULL, but an empty string should be a valid value. Have I misunderstood how to use the functions to insert empty strings?

### To Reproduce

I am not familiar with the C environment, and I guess it is trivial to reproduce this with a 
unit test to confirm or deny this issue. 

### OS:

iOS

### DuckDB Version:

1.0.0

### DuckDB Client:

go-duckdb

### Full Name:

Christian Persson

### Affiliation:

go-duckdb

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Giorgi** [comment]
I'm not sure what you are doing wrong but `duckdb_vector_assign_string_element` works as expected:

![image](https://github.com/duckdb/duckdb/assets/580749/30836d30-2a90-4154-a2b1-71714833e76d)

**Comment by ajzo90** [comment]
Ok, thanks, I'll double check. Closing until I can confirm.

**Comment by ajzo90** [comment]
Found the origin for this issue, it is unrelated to duckdb. 
I was using table UDF's in two layers and the bug was introduced in the intermediate representation.
