### ISSUE TITLE
read parquet file from s3 1.0.0 slower than 0.9.2

### ISSUE THREAD

**Issue by SheepPP** [duckdb/duckdb#12404]
### What happens?

There are 50+ parquet files in s3，I want to read files by filter like this:
```
select projectId, detail from read_parquet(['s3://mybucket/file1.parquet','s3://mybucket/file2.parquet',...])
where id=? and collectTime >= ? AND collectTime <= ? order by collectTime
```
The cost time is 3s+ run in duckdb v0.9.2, and is 20s+ run in duckdb v1.0.0 with the same code in same OS environment.

### To Reproduce

duckdb run in java8
<dependency>
            <groupId>org.duckdb</groupId>
            <artifactId>duckdb_jdbc</artifactId>
            <version>1.0.0</version>
</dependency>

### OS:

windows 10

### DuckDB Version:

1.0.0

### DuckDB Client:

jdbc

### Full Name:

SheepPP

### Affiliation:

company

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @SheepPP, thanks for raising this issue. To tackle it, we'll need a reproducible example. Can you please provide one?

**Comment by szarnyasg** [comment]
Hi, unfortunately, this is not enough for reproduction. We can only fix an issue if we have the code and dataset, which reproduce it. It you or someone reading this thread has a reproducer, we are happy to fix the issue.

**Comment by SheepPP** [comment]
```
DuckDBConnection conn = DuckDBConnection.newConnection("jdbc:duckdb:", false, new Properties());
        Statement stmt = conn.createStatement();
        stmt.execute("SET extension_directory = 'D:/mycode/extension';");
        stmt.execute("INSTALL httpfs ");
        stmt.execute("LOAD httpfs;");
        stmt.execute("SET s3_endpoint='obs.cn-north-5.myhuaweicloud.com';");
        stmt.execute("SET s3_access_key_id='xxx';");
        stmt.execute("SET s3_secret_access_key='yyy';");


        List<String> filteredKeys = createObjectKeyByTimeRange();
        String commonPrefix = "s3://mybucketName/";
        String parquetList = filteredKeys.stream().map(val -> "'" + commonPrefix + val + "'").collect(Collectors.joining(","));
        int count = 0;
        try (ResultSet rs = stmt.executeQuery(String.format("select projectId, detail from read_parquet([%s]) where carId=%s and collectTime >= %d AND collectTime <= %d order by collectTime",
                parquetList, segmentInfo.getCarId(), segmentInfo.getStartTime(), segmentInfo.getEndTime()))) {
            ResultSetMetaData md = rs.getMetaData();
            while (rs.next()) {
                count++;
                System.out.printf("%d,%s,%s\n",count, rs.getString(1), rs.getString(2));
            }
        }
        System.out.println(count);
```

**Comment by szarnyasg** [comment]
Regrettably this still doesn't contain the data required to reproduce the issue. Feel free to reopen the issue when you have a full reproducible example.
