### ISSUE TITLE
BETWEEN incorrectly pushed into ASOF JOIN

### ISSUE THREAD

**Issue by stevenpelley** [duckdb/duckdb#12412]
### What happens?

a predicate from an outer query block gets pushed, even through a CTE, into an ASOF JOIN predicate.
This is a follow up to https://github.com/duckdb/duckdb/issues/12215
The exact example in that bug has been fixed, but a similar query produces incorrect results.

### To Reproduce

consider the query 
```
SELECT
    t1.col0 AS left_val,
    t2.col0 AS right_val,
FROM
    (VALUES (0), (5), (10), (15)) AS t1
    ASOF JOIN (VALUES (1), (6), (11), (16)) AS t2
    ON t2.col0 > t1.col0
```

This correctly returns
```
|    |   left_val |   right_val |
|---:|-----------:|------------:|
|  0 |         15 |          16 |
|  1 |         10 |          11 |
|  2 |          5 |           6 |
|  3 |          0 |           1 |
```
printed via a pandas dataframe, hence the implicit index as the first column.

placing the above query in a CTE (t) and filtering rows based on right_value:
```
WITH t as (
    SELECT
        t1.col0 AS left_val,
        t2.col0 AS right_val,
    FROM
        (VALUES (0), (5), (10), (15)) AS t1
        ASOF JOIN (VALUES (1), (6), (11), (16)) AS t2
        ON t2.col0 > t1.col0
)
SELECT *
FROM t
WHERE right_val BETWEEN 3 AND 12
;
```

returns
```
|    |   left_val |   right_val |
|---:|-----------:|------------:|
|  0 |         10 |          11 |
|  1 |          5 |           6 |
|  2 |          0 |           6 |
```

It should return
```
|    |   left_val |   right_val |
|---:|-----------:|------------:|
|  0 |         10 |          11 |
|  1 |          5 |           6 |
```

left_val 0 is joining to right_val 6, but it should have joined to right_val 1 and then get filtered out.  The filter is being pushed such that t2.col0 = 1 is filtered out prior to the join changing the _values_ of the join instead of _which rows_ are later filtered.

Note that the same predicate applied to left_value returns the correct result.

### OS:

M1 MacOS 14.4.1 (23E224) inside a docker container uname -a: Linux 4f7cfa19b600 6.6.22-linuxkit #1 SMP Fri Mar 29 12:21:27 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Steven Pelley

### Affiliation:

None (retired/not currently employed)

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Have you verified this against another database that supports AsOf joins (e.g., ClickHouse, Snowflake)?

**Comment by hawkfish** [comment]
Verified with ClickHouse:

```sql
create table t1(col0 integer, grp integer) PRIMARY KEY col0;
insert into t1 VALUES (0, 1), (5, 1), (10, 1), (15, 1);

create table t2(col0 integer, grp integer) PRIMARY KEY col0;
insert into t2 VALUES (1, 1), (6, 1), (11, 1), (16, 1);

WITH t as (
    SELECT
        t1.col0 AS left_val,
        t2.col0 AS right_val
    FROM
        "t1" ASOF JOIN "t2" ON t1. grp = t2. grp AND t2.col0 > t1.col0
)
SELECT *
FROM t
WHERE right_val BETWEEN 3 AND 12
```

left_val | right_val
---|---
5 | 6
10 | 11

**Comment by stevenpelley** [comment]
I just confirmed this against the latest clickhouse:
```
create temporary table t1 (key int, left_val int);
create temporary table t2 (key int, left_val int);
insert into t1 values (0, 0), (0, 5), (0, 10), (0, 15);
insert into t2 values (0, 1), (0, 6), (0, 11), (0, 16);
```

Then
```
SELECT
  t1.val,
  t2.val,
FROM
  t1
  asof join t2
  ON t2.val > t1.val and t1.key = t2.key;
WHERE (t2.val >= 3) AND (t2.val <= 12)
```

produces
```
   ┌─val─┬─t2.val─┐
1. │   5 │      6 │
2. │  10 │     11 │
   └─────┴────────┘
```

Note that this does not require the CTE, which I included for clarity: semantically the WHERE clause evaluates after the FROM and predicates should only be pushed so long as they do not change the semantics/results.

As a further example consider this view and query in duckdb:
```
D create or replace temporary view asof_joined as
        SELECT
            t1.col0 AS left_val,
            t2.col0 AS right_val,
        FROM
            (VALUES (0), (5), (10), (15)) AS t1
            ASOF JOIN (VALUES (1), (6), (11), (16)) AS t2
            ON t2.col0 > t1.col0;
```

```
D select * from asof_joined;
┌──────────┬───────────┐
│ left_val │ right_val │
│  int32   │   int32   │
├──────────┼───────────┤
│       15 │        16 │
│       10 │        11 │
│        5 │         6 │
│        0 │         1 │
└──────────┴───────────┘
```

```
D select * from asof_joined where right_val BETWEEN 3 AND 12;
┌──────────┬───────────┐
│ left_val │ right_val │
│  int32   │   int32   │
├──────────┼───────────┤
│       10 │        11 │
│        5 │         6 │
│        0 │         6 │
└──────────┴───────────┘
```

The existence of a WHERE predicate has changed the rows in the underlying view ( (0, 6) does not exist in the view).  This shouldn't happen.  The same restriction/definition should always hold for a CTE as well.

**Comment by hawkfish** [comment]
Thanks - I managed to get CH installed and work through their AsOf requirements and I see the same thing. 

There is no real difference between a view definition and a CTE, so I would expect them to behave the same.
