### ISSUE TITLE
cmake target exports use fixed paths (not relocatable)

### ISSUE THREAD

**Issue by ino-josh** [duckdb/duckdb#12416]
### What happens?

The contents of `DuckDBExports.cmake` and `DuckDBExports-release.cmake` use fixed paths.
I don't know enough about cmake to know _why_ these differ from other projects, but they do.
`DuckDBExports.cmake` has this:

```
# The installation prefix configured by this project.
set(_IMPORT_PREFIX "/usr")
```
whereas other projects (fmt in this example) equivalent export/target cmake file has something like this:
```
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
# Use original install prefix when loaded through a
# cross-prefix symbolic link such as /lib -> /usr/lib.
get_filename_component(_realCurr "${_IMPORT_PREFIX}" REALPATH)
get_filename_component(_realOrig "/usr/lib/cmake/fmt" REALPATH)
if(_realCurr STREQUAL _realOrig)
  set(_IMPORT_PREFIX "/usr/lib/cmake/fmt")
endif()
unset(_realOrig)
unset(_realCurr)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()
```

And then the `DuckDBExports-release.cmake` file has `/usr` where it should have `{_IMPORT_PREFIX}` in many places.

I ran into this trying to link against duckdb while building a project using a yocto based SDK (where the sysroot is defined in the SDK's environment).

### To Reproduce

Install and look at the resulting cmake files in `/user/lib/cmake`.

### OS:

aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

N/A

### Full Name:

Josh McAtee

### Affiliation:

Inovonics, Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by cryos** [comment]
I was just taking a look at this and [these lines](https://github.com/duckdb/duckdb/blob/main/CMakeLists.txt#L73-L79) push the install paths to be absolute. If I remove them then the logic to make the include path relative on line 1387 or so needs fixing up, but the targets all become relative using normal CMake code after that.
