### ISSUE TITLE
Regression in 1.0 for representation of SQLNULL in Python API

### ISSUE THREAD

**Issue by Dutcho** [duckdb/duckdb#12422]
### What happens?

`SQLNULL` is represented with double quotes `"NULL"` in 1.0, while it didn't have quotes in 0.10 `NULL`

This regression became evident from automated unit tests after upgrading.
It's easily fixed and either way is okay for me, but I need to know whether the quotes are here to stay, or we'll revert to quote-less in 1.01.

### To Reproduce

# previously 0.10
```
(.venv) >pip list duckdb
Package           Version        Editable project location
----------------- -------------- ----------------------------------------
duckdb            0.10.1
[...]

(.venv) >py
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> print(duckdb.typing.SQLNULL)
NULL
>>> exit()
```
no quotes on penultimate line
# upgrade to 1.0
```
(.venv) >pip install -U duckdb
[...]
Successfully installed duckdb-1.0.0
```
# now in 1.0
```
(.venv) >pip list duckdb
Package           Version        Editable project location
----------------- -------------- ----------------------------------------
duckdb            1.0.0
[...]

(.venv) >py
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> print(duckdb.typing.SQLNULL)
"NULL"
>>> exit()
```
see quotes on penultimate line

### OS:

Windows 11

### DuckDB Version:

1.0

### DuckDB Client:

Python

### Full Name:

Olaf

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
This is caused by #11625 
The reason this change was made is because it's needed to round-trip SQL.

We could take the same approach as we do for Value:
```c++
	//! Convert this value to a string
	DUCKDB_API string ToString() const;
	//! Convert this value to a SQL-parseable string
	DUCKDB_API string ToSQLString() const;
```
But I can't give a timeline on that, as it's not a very crucial thing to fix
