### ISSUE TITLE
Plan change between Memory and File TPCH Q2, Q5, Q8, Q10, Q12, Q18 

### ISSUE THREAD

**Issue by jtommaney** [duckdb/duckdb#1242]
TPCH Q2, Q5, Q8, Q10, Q12, Q18 plan difference between Memory and File.  Timings and plan are at SF10.

Note:  Q13, Q16 and Q19 have other issues not related to plan changes. 

![Plan_changes](https://user-images.githubusercontent.com/8917575/102811500-0b0f4f80-438b-11eb-8c15-2130117c183d.png)

Q2 File, Memory:

![Q2_CLI_File](https://user-images.githubusercontent.com/8917575/102811435-f0d57180-438a-11eb-97cd-fbe176423e44.png)

![Q2_CLI_Memory](https://user-images.githubusercontent.com/8917575/102811436-f0d57180-438a-11eb-917b-5531e077bfed.png)

Q5 File, Memory:

![Q5_CLI_File](https://user-images.githubusercontent.com/8917575/102811426-ef0bae00-438a-11eb-9c03-23521b2c56d8.png)

![Q5_CLI_Memory](https://user-images.githubusercontent.com/8917575/102811427-efa44480-438a-11eb-82b8-f6fb0ca01134.png)

Q8 File, Memory:

![Q8_CLI_File](https://user-images.githubusercontent.com/8917575/102811429-efa44480-438a-11eb-8728-58fc30aa7db6.png)

![Q8_CLI_Memory](https://user-images.githubusercontent.com/8917575/102811430-f03cdb00-438a-11eb-9f9b-3adf0f13c345.png)

Q10 File, Memory:

![Q10_CLI_File](https://user-images.githubusercontent.com/8917575/102811424-ef0bae00-438a-11eb-83df-d9316f280d90.png)

![Q10_CLI_Memory](https://user-images.githubusercontent.com/8917575/102811425-ef0bae00-438a-11eb-90a3-7bea853c1551.png)

Q12 File, Memory:

![Q12_CLI_File](https://user-images.githubusercontent.com/8917575/102811422-ef0bae00-438a-11eb-872e-61bd12d481e5.png)

![Q12_CLI_Memory](https://user-images.githubusercontent.com/8917575/102811421-ee731780-438a-11eb-8ccb-365b79a6ca85.png)

Q18 File, Memory:
![Q18_CLI_File](https://user-images.githubusercontent.com/8917575/102811419-ee731780-438a-11eb-8026-30eabe18f7de.png)

![Q18_CLI_Memory](https://user-images.githubusercontent.com/8917575/102811417-edda8100-438a-11eb-8688-5ef10755aef4.png)

**Comment by Mytherin** [comment]
Thanks for the report! Nice catch. It seems to me that likely the statistics are not correctly read from file, which results in choosing a different (worse) join order.

**Comment by jtommaney** [comment]
Are there any methods to (re) capture statistics on the file that I can try?  Analyze did not seem to impact.  

Can the statistics be viewed and/or dumped for inspection?

**Comment by Mytherin** [comment]
Table-level statistics (which I assume to be the culprit here!) cannot be dumped yet. Column-level statistics can be inspected as follows:

```sql
select stats(l_orderkey) from lineitem limit 1;
```

**Comment by jtommaney** [comment]
Nice! 

Any visibility into min/max meta-data for data skipping opportunities?

**Comment by Mytherin** [comment]
Currently only the global stats are shown; but that would be useful as well, good point.

**Comment by hannes** [comment]
This is likely outdated, feel free to reopen/comment if you're still experiencing this issue.
