### ISSUE TITLE
INTERNAL Error reading from CSV file

### ISSUE THREAD

**Issue by ivan-tkatchev** [duckdb/duckdb#12439]
### What happens?

```
select count() from read_csv('s3://api-data/metrics/ts-1717762124-0008220836-bi-ng.lan:9900-metrics.gz',ignore_errors=true)
```
```
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <module>
duckdb.duckdb.InternalException: INTERNAL Error: Attempted to access index 8 within vector of size 8
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

DuckDB 0.10.2, revision 86fee9ed386eaa2d50a7154416ebb824980e8d59 

### To Reproduce

I can provide the failing .gz file in private conversation.

### OS:

Linux

### DuckDB Version:

0.10.2

### DuckDB Client:

Python

### Full Name:

Ivan Tkachev

### Affiliation:

Hyper AdTech

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hey @ivan-tkatchev thanks for raising this issue, can you please send the csv file or a link to it to gabor@duckdblabs.com?

**Comment by ivan-tkatchev** [comment]
Done.

**Comment by szarnyasg** [comment]
Thanks @ivan-tkatchev! I tried your file – it indeed crashes v0.10.2 but it works fine with v1.0.0:

```text
v1.0.0 1f98600c2c
```
```sql
select count() from read_csv('bad.csv.gz',ignore_errors=true);
```
```text
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        13681 │
└──────────────┘
```

**Comment by szarnyasg** [comment]
Closing this for now, feel free to reopen if the error persists with v1.0.0+.
