### ISSUE TITLE
Q19 performance difference Python vs. Command Line

### ISSUE THREAD

**Issue by jtommaney** [duckdb/duckdb#1243]
TPCH Q19 shows performance degradation when running from Python3 vs from command line.

                         | DoP=1 | DoP=2 | DoP=4  | DoP=8 | DoP=16 | DoP=32 | DoP=64
Q19 - CLI         |    7.9    |      10.7 |    6.611  |   3.605 |      2.121 |     1.056 |    0.662
Q19 - Python  |  9.764 |  17.406 |  18.967 |  16.816 |   14.925 |   15.861  | 13.185

explain plan appears to be the same.  

Command line plan:
![Q19_CLI_plan](https://user-images.githubusercontent.com/8917575/102814801-d56d6500-4390-11eb-8662-b0da7145ed32.png)

Python plan:
![Q19_Python_plan](https://user-images.githubusercontent.com/8917575/102814804-d605fb80-4390-11eb-843c-a1b6d7cbae29.png)

**Comment by jtommaney** [comment]
SF10 
repeatable across multiple versions, latest python was this:  duckdb-0.2.4.dev239

**Comment by hannesmuehleisen** [comment]
Which OS is this? Windows?

**Comment by jtommaney** [comment]
Linux environment:
Linux version 3.10.0-327.ali2011.alios7.x86_64 (admin@ba7ee01966d8) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Tue Jun 6 14:29:12 CST 2017

**Comment by hannes** [comment]
This is likely outdated, feel free to reopen/comment if you're still experiencing this issue
