### ISSUE TITLE
Invalid Input Error: CSV Error on Line: 729

### ISSUE THREAD

**Issue by rodryquintero** [duckdb/duckdb#12449]
### What happens?

When importing CSV data with spanish language special characters, the database trigger the following error:

```console
Invalid Input Error: CSV Error on Line: 729
Original Line:
1510,1,2,S100,S100
Invalid unicode (byte sequence mismatch) detected.

Possible Solution: Enable ignore errors (ignore_errors=true) to skip this row

  file=tTests.csv
  delimiter = , (Auto-Detected)
  quote = " (Auto-Detected)
  escape = \0 (Auto-Detected)
  new_line = Single-Line File (Auto-Detected)
  header = false (Auto-Detected)
  skip_rows = 0 (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=20480
  ignore_errors=false
  all_varchar=0
```

The data in the line reference by the error is the following.

```csv
1511,1,2,NSE (Enolasa Específica Neuronal),NSE
```

In the above case, the accent on the word `Específica` breaks the import process. The error also occurs with `ñ` characters.

The CSV file is UTF-8 encoded.

### To Reproduce

Import the attached CSV file using the following command:

```sql
create table tTests as select * from 'tTests.csv';
``` 

[tTests.csv](https://github.com/user-attachments/files/15750408/tTests.csv)

### OS:

Windows 11

### DuckDB Version:

1.0.0

### DuckDB Client:

duckdb.exe

### Full Name:

ivan Rodrigo Quintero

### Affiliation:

Healthcare

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! The UTF-8 encoding in this file appears to be invalid. Reading with Python confirms this and produces the same error message as DuckDB:

```py
>>> open('tTests.csv').read()
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "<frozen codecs>", line 322, in decode
# UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 25257: invalid continuation byte
```

DuckDB currently only supports reading files that are encoded in (valid) UTF-8. You can use the `ignore_errors=true` option to skip rows with incorrect encodings, e.g.:

```sql
from read_csv('tTests.csv', ignore_errors=true);
```
