### ISSUE TITLE
Python client fails to install via pip

### ISSUE THREAD

**Issue by kevinlacaille** [duckdb/duckdb#12466]
### What happens?

When attempting to install the python client via `pip`, it gets stuck trying to build the wheel for `duckdb`, indefinitely.

```bash
> pip install duckdb
Collecting duckdb
  Using cached duckdb-1.0.0.tar.gz (11.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: duckdb
  Building wheel for duckdb (pyproject.toml) ... /
```

This also happens with the pre-release
```bash
> pip install duckdb --upgrade --pre
Collecting duckdb
  Downloading duckdb-1.0.1.dev109.tar.gz (11.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 9.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: duckdb
  Building wheel for duckdb (pyproject.toml) ... /
```

### To Reproduce

Run `pip install duckdb`

### OS:

MacOS 14.3.1, aarch64 (M2 Pro)

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Kevin Lacaille

### Affiliation:

Spexi

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Can you share which version of Python you are compiling for?

I would assume by "it gets stuck ... indefinitely" you mean that building from source takes up to 20 minutes (that is a lot).

It's possibly you might have Python 3.7 (that we don't package wheels for on OSX), that according to https://devguide.python.org/versions/#supported-versions is past end-of-life, or Python 3.13 (not yet released) ?

**Comment by kevinlacaille** [comment]
Hi @carlopi, thanks for getting to this so quickly!

Python version: 3.11.5

By indefinitely, I mean something like 20 minutes, though I didn't actually measure it.

**Comment by carlopi** [comment]
This is then surprising, if you download the 
duckdb-1.0.0-cp311-cp311-macosx_12_0_arm64.whl from Pypi (https://pypi.org/project/duckdb/#files), say by clicking on the link, then moving the file to your current folder, and then do `pip install duckdb-1.0.0-cp311-cp311-macosx_12_0_arm64.whl`, does that work?

I would expect this should take a couple of second and install the pre-build wheel. If this work, then the question is why is that not fetched. If that doesn't work, could you possibly try with the universal macos wheel named 
duckdb-1.0.0-cp311-cp311-macosx_12_0_universal2.whl ?

Thanks a lot for being available to track this down.

**Comment by kevinlacaille** [comment]
Thank you for your suggestions. I followed the steps you outlined and tested both the ARM64 and the universal macOS wheel files, but neither worked for my setup. Here are the details of my findings:

```bash
> pip install -v duckdb-1.0.0-cp311-cp311-macosx_12_0_arm64.whl
ERROR: duckdb-1.0.0-cp311-cp311-macosx_12_0_arm64.whl is not a supported wheel on this platform.

> pip install -v duckdb-1.0.0-cp311-cp311-macosx_12_0_universal2.whl
ERROR: duckdb-1.0.0-cp311-cp311-macosx_12_0_universal2.whl is not a supported wheel on this platform.
```

I've also updated pip to the latest version to ensure there are no compatibility issues from that side.
```bash
> pip install --upgrade pip
Requirement already satisfied: pip in /Users/kevinlacaille/miniconda/lib/python3.11/site-packages (24.0)
```
It seems like the pre-built wheels are not recognized as compatible with my environment. Any further guidance or troubleshooting steps would be greatly appreciated.

Thanks again for your assistance in resolving this!

**Comment by kevinlacaille** [comment]
Great idea, here's the output attached: [debug_verbose.txt](https://github.com/user-attachments/files/15777677/debug_verbose.txt)

**Comment by carlopi** [comment]
I can't go much further, it's possible that `conda install duckdb` might work, unsure, very wild guess based on the fact that your python installation is in the `miniconda` folder.

Someone else will pass by with more knownledge hopefully.

**Comment by Tishj** [comment]
You stated that you are on MacOS 14.3.1, but the output from `debug --verbose` seems to indicate that's not the case?
Seeing as the only `Compatible tags` listed are `macosx_10_...`

**Comment by kevinlacaille** [comment]
You're right, that's really strange, because here's what I'm seeing for my OS version:

```bash
> sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60
```

**Comment by Tishj** [comment]
My listed `pip` version is `24.0`
It seems related to virtual envs? <https://github.com/pypa/pip/issues/9621>

**Comment by kevinlacaille** [comment]
Interestingly, it does appears that my system is being recognized as macOS 10.16 instead of the expected macOS 14.x, which is likely leading to the compatibility issue. 

```bash
> python -c "import platform; print(platform.platform())"

macOS-10.16-x86_64-i386-64bit
```

I gave up on `pip` and successfully installed via `conda` with the following commands:
```bash
conda update conda
conda update --all
conda install -c conda-forge duckdb
```

Thanks for both of your help!

**Comment by carlopi** [comment]
I think this can be considered closed, mix and match of conda with pip is not working great, but that's fine / not really on duckdb.

**Comment by AlonSam** [comment]
I'm actually experiencing the same issue and I'm not using Conda.
Macbook Pro M1, MacOS 14.4.1

**Comment by carlopi** [comment]
@AlonSam, can you possibly follow the same steps as above, in particular:

```
python -c "import platform; print(platform.platform())"
```
and
```
pip debug --verbose > pip_debug.output
```
?

**Comment by carlopi** [comment]
@AlonSam: can you provide the information needed to help solve this? Thanks

**Comment by AlonSam** [comment]
I'm not sure how, but somehow it was simply solved by itself.. working now.
Sorry for re-opening the issue.
Thanks

**Comment by carlopi** [comment]
Cool, thanks.
