### ISSUE TITLE
ORDER BY ALL not working in window functions

### ISSUE THREAD

**Issue by frosshirt** [duckdb/duckdb#12464]
### What happens?

The `ORDER BY ALL` statement is not functioning as expected in window functions such as `ROW_NUMBER() OVER (ORDER BY ALL)`. Instead of sorting the values by all columns, DuckDB produces an output with as many columns as the input has rows.

According to the documentation, the `ORDER BY ALL` clause should work within window functions and should sort the values by all columns. However, this does not seem to be the case.

### To Reproduce

Run the following SQL query using DuckDB:

```sql
SELECT i, j, ROW_NUMBER() OVER (ORDER BY ALL) AS rn
FROM (
    SELECT i ,j
    FROM generate_series(1, 5) s(i)
    CROSS JOIN generate_series(1, 2) t(j)
) t;
```
**Expected Behavior:**

The `ROW_NUMBER() OVER (ORDER BY ALL)` should sort the values by all columns and produce a single column for the row numbers. The output should be the same as using `ROW_NUMBER() OVER (ORDER BY i, j)`

**Actual Behavior:**

DuckDB produces an output with 2 rn columns (where the first rn column is correct):

```
i|j|rn|rn|
-+-+--+--+
1|1| 1| 1|
2|1| 3| 2|
3|1| 5| 3|
4|1| 7| 4|
5|1| 9| 5|
1|2| 2| 6|
2|2| 4| 7|
3|2| 6| 8|
4|2| 8| 9|
5|2|10|10|
```

### OS:

Windows 11 (x64)

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Fabian Roßhirt

### Affiliation:

IBIS Prof. Thome AG

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Looks like the planner decided to create two window functions. Which is quite strange!

**Comment by hawkfish** [comment]
Sorry the documentation is wrong. This is not allowed.

**Comment by frosshirt** [comment]
Ok, thanks for confirming that!
