### ISSUE TITLE
greatest(null, 0) = 0?

### ISSUE THREAD

**Issue by dah33** [duckdb/duckdb#12463]
### What happens?

`select greatest(null, 0)` returns zero (as an `int64`, but `0.0` similar). I would expect `null`. Similarly for `least`. I've tested on Python API, DBeaver (Java) and CLI.

### To Reproduce

`select greatest(null, 0)`

### OS:

Windows 11

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Dan Houghton

### Affiliation:

LAB77 (I'm a contractor)

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Postgres seems to have the same result:
```
psql (16.0)
Type "help" for help.

postgres=# select greatest(null, 0);
 greatest 
----------
        0
(1 row)
```

**Comment by dah33** [comment]
You are right! Looks like NULLS are ignored, similar to max() for a column, so it makes sense.
