### ISSUE TITLE
Precedence for @ is too low when used with +

### ISSUE THREAD

**Issue by norcalli** [duckdb/duckdb#12518]
### What happens?

```
D select @x + 5 from (select -1 as x);
┌────────────┐
│ @((x + 5)) │
│   int32    │
├────────────┤
│          4 │
└────────────┘
```
As the column header shows, it is parsing as `@(x + 5)` not `(@x) + 5`, which seems very surprising to me.

### To Reproduce

```
D select @x + 5 from (select -1 as x);
┌────────────┐
│ @((x + 5)) │
│   int32    │
├────────────┤
│          4 │
└────────────┘
```

### OS:

x64 linux

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Ashkan Kiani

### Affiliation:

Jane Street

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @norcalli, thanks for opening this issue. PostgreSQL also returns `4` for the same query.

```
postgres=# select @x + 5 from (select -1 as x) s;
 ?column?
----------
        4
(1 row)
```

In general, we strive to be [compatible with PostgreSQL](https://duckdb.org/docs/sql/postgresql_compatibility), so this is expected behaviour.

**Comment by norcalli** [comment]
Thank you for the quick response, I didn't realize this was also an operator in postgres.
I did find it pretty surprising, so I'll stick to using abs() instead.
Thanks!
