### ISSUE TITLE
"How can I use the GBK encoding?

### ISSUE THREAD

**Issue by tealin** [duckdb/duckdb#12529]
### What happens?

My files are encoded in GBK, which cannot be converted to UTF-8 without losing a lot of information. When will the official support for the GBK encoding format be available?"

### To Reproduce

My files are encoded in GBK, which cannot be converted to UTF-8 without losing a lot of information. When will the official support for the GBK encoding format be available?"

### OS:

x86 mac

### DuckDB Version:

1.0

### DuckDB Client:

cli

### Full Name:

no

### Affiliation:

no

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
> which cannot be converted to UTF-8 without losing a lot of informatio

Please provide a source for this, I cant find anything confirming that.
As the source below states, *treating* GBK as UTF-8 loses information, converting doesn't

<https://programmersought.com/article/77465155132/>
