### ISSUE TITLE
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation)

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#12528]
### What happens?

duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation)

### To Reproduce

```
[root@prod ~]# ls -lh /data/prod/
total 480M
-rw-r--r-- 1 root root   0 Jun 14 09:57 gto_skc_org_feature_pivot.parquet
-rw-r--r-- 1 root root 76M Jun 13 21:23 gto_skc_org_feature_unpivot2024-06-07.parquet
-rw-r--r-- 1 root root 76M Jun 13 21:15 gto_skc_org_feature_unpivot2024-06-08.parquet
-rw-r--r-- 1 root root 77M Jun 13 21:14 gto_skc_org_feature_unpivot2024-06-09.parquet
-rw-r--r-- 1 root root 83M Jun 13 21:10 gto_skc_org_feature_unpivot2024-06-10.parquet
-rw-r--r-- 1 root root 85M Jun 13 21:07 gto_skc_org_feature_unpivot2024-06-11.parquet
-rw-r--r-- 1 root root 85M Jun 13 21:00 gto_skc_org_feature_unpivot2024-06-12.parquet
-rw-r--r-- 1 root root 185 Jun 13 21:13 gto_skc_org_feature_unpivot2024-06-13.parquet
-rw-r--r-- 1 root root 12K Jun 14 09:04 my.duckdb
```
I need pivot these parquet , and use file as duckdb, even create table or copy to parquet , both OOM,
```sql
copy (
PIVOT 'gto_skc_org_feature_unpivot*.parquet' 
ON feature_code
USING max(feature_value)
group by id, skc_sk, org_sk, day_date, etl_time
) TO 'gto_skc_org_feature_pivot.parquet';
```
```
 57% ▕██████████████████████████████████▏                         Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in exesql
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation)
```
even only one day parquet, still error:
```sql
copy (
PIVOT 'gto_skc_org_feature_unpivot2024-06-12.parquet' 
ON feature_code
USING max(feature_value)
group by id, skc_sk, org_sk, day_date, etl_time
) TO 'gto_skc_org_feature_pivot2024-06-12.parquet';
```
```
 76% ▕█████████████████████████████████████████████▌              ▏ Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in exesql
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 134217728 bytes (bad allocation)
```
How to solve this ,and my machine has 128 GB memory total， and my python is 3.8.9
```
[root@prod ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:         128358       92758        5688        3045       29912       31959
Swap:          4095        3686         409
```
and then I use 7 pivot parquet and union by name, total 164M ,also OOM:
```
total 164M
-rw------- 1 gpadmin gpadmin  23M Jun 14 14:01 gto_skc_org_feature_pivot2024-06-08.parquet
-rw------- 1 gpadmin gpadmin  24M Jun 14 14:03 gto_skc_org_feature_pivot2024-06-09.parquet
-rw------- 1 gpadmin gpadmin  23M Jun 14 14:04 gto_skc_org_feature_pivot2024-06-10.parquet
-rw------- 1 gpadmin gpadmin  23M Jun 14 14:05 gto_skc_org_feature_pivot2024-06-11.parquet
-rw------- 1 gpadmin gpadmin  23M Jun 14 14:06 gto_skc_org_feature_pivot2024-06-12.parquet
-rw------- 1 gpadmin gpadmin  24M Jun 14 14:06 gto_skc_org_feature_pivot2024-06-13.parquet
-rw------- 1 gpadmin gpadmin 9.9M Jun 14 14:54 gto_skc_org_feature_pivot2024-06-14.parquet
```
attachment I upload one day of the parquet:( parquet not allowed, changed to txt file)
[gto_skc_org_feature_pivot2024-06-14.parquet.txt](https://github.com/user-attachments/files/15833236/gto_skc_org_feature_pivot2024-06-14.parquet.txt)

I used plpython to run duckdb:
```
SQL 错误 [XX000]: ERROR: duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation) (plpy_elog.c:121)
  在位置：Traceback (most recent call last):
  PL/Python function "p_gto_skc_org_feature_py", line 48, in <module>
    ducksql(sql)
  PL/Python function "p_gto_skc_org_feature_py", line 33, in ducksql
    dd.execute(sql)
PL/Python function "p_gto_skc_org_feature_py"
  ERROR: duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation) (plpy_elog.c:121)
  在位置：Traceback (most recent call last):
  PL/Python function "p_gto_skc_org_feature_py", line 48, in <module>
    ducksql(sql)
  PL/Python function "p_gto_skc_org_feature_py", line 33, in ducksql
    dd.execute(sql)
PL/Python function "p_gto_skc_org_feature_py"
  ERROR: duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation) (plpy_elog.c:121)
  在位置：Traceback (most recent call last):
  PL/Python function "p_gto_skc_org_feature_py", line 48, in <module>
    ducksql(sql)
  PL/Python function "p_gto_skc_org_feature_py", line 33, in ducksql
    dd.execute(sql)
PL/Python function "p_gto_skc_org_feature_py"

```
### OS:

centos7

### DuckDB Version:

0.10.3 and 1.0.0 both

### DuckDB Client:

python 3.8.9

### Full Name:

wang cz

### Affiliation:

Linezone

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @wonb168, thanks for opening this issue.

I'm trying to reproduce this issue but the provided Parquet file and the code do not work together: the query needs the `unpivot` file as its input but you provided the `pivot` file which has different fields. Can you please provided e.g. `gto_skc_org_feature_unpivot2024-06-12.parquet`? You can also email it to me (`gabor@duckdblabs.com`).

**Comment by wonb168** [comment]
pivot file is the second way，use union by name also oom，and I test run in python is OK，but I need run in postgres via plpython，oom。

**Comment by szarnyasg** [comment]
So far, I could not reproduce the issue in CLI:

```sql
D copy (
  PIVOT 'gto_skc_org_feature_unpivot*.parquet'
  ON feature_code
  USING max(feature_value)
  group by id, skc_sk, org_sk, day_date, etl_time
  ) TO 'gto_skc_org_feature_pivot.parquet';
```
```
100% ▕████████████████████████████████████████████████████████████▏
Run Time (s): real 40.158 user 385.518482 sys 46.019776
```

```sql
D copy (
  PIVOT 'gto_skc_org_feature_unpivot2024-06-12.parquet'
  ON feature_code
  USING max(feature_value)
  group by id, skc_sk, org_sk, day_date, etl_time
  ) TO 'gto_skc_org_feature_pivot2024-06-12.parquet';
```
```
100% ▕████████████████████████████████████████████████████████████▏
Run Time (s): real 7.001 user 63.899097 sys 6.259074
```

So the code in Python works for you but the problem only occurs when running it in PL/Python?

**Comment by wonb168** [comment]
but you runned in cli？
not in python，
and my pc’s py3.11 is OK，
but server is py3.8.9，and can't upgrade
.
not only plpython, run in python
3.8 directly also OOM

**Comment by wonb168** [comment]
one day parquet to pivot:
duckdb cli: 
python3.8: 50s
plpython: 52s
duckdb cli：OK
![image](https://github.com/duckdb/duckdb/assets/25274931/b8bd8158-d618-4571-973e-511433ce585a)
python3.8: OK
```
import duckdb as dd
print(dd.__version__)
sql="""copy (
PIVOT 'gto_skc_org_feature_unpivot2024-06-12.parquet' 
ON feature_code
USING max(feature_value)
group by id, skc_sk, org_sk, day_date, etl_time
) TO 'gto_skc_org_feature_pivot2024-06-12.parquet';"""
dd.execute(sql)
```
![image](https://github.com/duckdb/duckdb/assets/25274931/bc29642d-1dd7-4f00-bf56-7354debb8bfa)
plpython:
![image](https://github.com/duckdb/duckdb/assets/25274931/df514d72-3b00-41cd-86b8-90de976adb1e)

**Comment by szarnyasg** [comment]
@stanwsh thanks for joining the discussion. Is there a chance you can share the database with us? We need a reproducer to tackle this issue. Feel free to send me an email (`gabor@duckdblabs.com`).

**Comment by hrshdhgd** [comment]
Potential solution: https://github.com/duckdb/duckdb/issues/9880#issuecomment-2302076955
