### ISSUE TITLE
Cannot specify the name of the filename column using the filename argument

### ISSUE THREAD

**Issue by hieunm89** [duckdb/duckdb#12533]
### What happens?

In document, since v0.10.2, there is a feature to specify the name of the filename column using the filename argument:

```sql
SELECT * FROM read_csv(['flights1.csv', 'flights2.csv'], union_by_name = true, filename = "my_filename_column");
```

However when I try this feature, I got the following error:

```console
Invalid Input Error: Failed to cast value: Could not convert string 'original_filename' to BOOL
```

### To Reproduce

Have a test.csv with filename column

```
filename, content
abc.csv, hello
```

Try this query:

```sql
select * from read_csv('test.csv', filename="original_filename");
```

```console
Invalid Input Error: Failed to cast value: Could not convert string 'my_filename_column' to BOOL
```

### OS:

Window 11

### DuckDB Version:

0.10.2 and 1.0

### DuckDB Client:

Python, Java

### Full Name:

Hieu Nguyen

### Affiliation:

Telsoft

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @hieunm89, thanks, this is indeed an issue. We'll fix it but it may take a while, so in the meantime I recommend you to use a workaround, e.g. updating the columns after loading:

```sql
create or replace table tbl as select * from read_csv('test.csv', filename=true);
create or replace table tbl as select content, filename as original_filename from tbl;
```

**Comment by hieunm89** [comment]
Hi @szarnyasg ,

The problem is I'm reading a glob of csv, and need the name of the file in glob. So for now I have to rewrite the original csv files to change the filename column,otherwise I will have this error.
```
select * from read_csv('*.csv',filename=true);

"SQL Error: java.sql.SQLException: Binder Error: Using filename option on file with column named filename is not supported" 
 ```

**Comment by Tishj** [comment]
> The problem is I'm reading a glob of csv, and need the name of the file in glob. So for now I have to rewrite the original csv files to change the filename column,otherwise I will have this error.

You could use `names` to specify the names for the columns, providing a different name for the problematic `filename`  column

Using `sniff_csv` this should be trivial as the right `read_csv` call is already given to you, just the `columns` has to be changed
