### ISSUE TITLE
odd `extract` interval behavior

### ISSUE THREAD

**Issue by gzheng92** [duckdb/duckdb#12535]
### What happens?

In duckdb 1.0.0, using the python library, I ran the following:
```python
duckdb.sql("select datepart('year', INTERVAL '640 days')")
```
and it returned
```
┌────────────────────────────────────────────────┐
│ datepart('year', CAST('640 days' AS INTERVAL)) │
│                     int64                      │
├────────────────────────────────────────────────┤
│                                              0 │
└────────────────────────────────────────────────┘
```

I would have expected the answer to be 1, or perhaps for there to be an error warning me that the mapping from days to years is leap year-dependent but maybe there's some justification for this behavior.

### To Reproduce

Run the following:
```
import duckdb
duckdb.sql("select datepart('year', INTERVAL '640 days');")
```

### OS:

aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Geoff Zheng

### Affiliation:

NYU Shanghai

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Postgres behavior:

```sql
postgres=# select date_part('years', (interval '640 days'));
 date_part 
-----------
         0
(1 row)

postgres=# select date_part('days', (interval '640 days'));
 date_part 
-----------
       640
```

**Comment by gzheng92** [comment]
I see, so it's replicating / matching postgres behavior.

**Comment by soerenwolfers** [comment]
https://github.com/duckdb/duckdb-web/pull/3064 gives the explanation (and, in my opinion, somewhat sensible justification).

**Comment by soerenwolfers** [comment]
This has now been merged and is available in the docs at https://duckdb.org/docs/sql/data_types/interval.html 

If you're happy with the description, you can close this ticket.
