### ISSUE TITLE
Inconsistency between duckdb_settings() and duckdb_get_config_flag

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#12542]
### What happens?

As [discussed on Discord](https://discord.com/channels/909674491309850675/921073327009853451/1251263233827012720), when using the C Api to enumerate DuckDB configuration options, `duckdb_config_count` and `duckdb_get_config_flag` only return built-in options. On the other hand, `duckdb_settings()` will return options from an extension if they are already loaded.

### To Reproduce

Enumerate configuration options with `duckdb_get_config_flag` when some extension is already loaded and compare with `duckdb_settings()`

### OS:

Windows 11 x64

### DuckDB Version:

1.0.0

### DuckDB Client:

C Api

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Giorgi** [comment]
Another thing to consider: Should `duckdb_set_config` auto load an extension if it is called with a config option that belongs to an autoloadable extension?

**Comment by Giorgi** [comment]
Still present

**Comment by Mytherin** [comment]
Thanks for the report!

`duckdb_config` is intended to setup a configuration **before** a database is constructed. The only place where a `duckdb_config` can be used is when opening a database (`duckdb_open_ext`). It is not possible to have extensions loaded prior to having a database opened, and none of the configuration settings take a database object as a parameter, hence it is not possible to extend these methods to expose extension options, or to auto-load extensions. 

The idea behind this API is that, prior to opening a database instance, you can only use this API to configure the database. After the database is opened, SQL commands can be used to configure it instead.

Is there are particular use case you are running into where SQL commands are not sufficient?

**Comment by Giorgi** [comment]
Thanks for the explanation, Mark. I understand it but I think there are some cases not covered by the API. First, it's possible to set a config option from an extension before a database connection is opened: https://github.com/duckdb/duckdb/issues/11404

I tried and it is possible to set the `Timezone` option from the C API `duckdb_set_config(config, "Timezone", "Asia/Tbilisi")` and it will autoload the ICU extension and autoload it when connection is opened. But if I iterate over config options with `duckdb_config_count` and `duckdb_get_config_flag`, I won't get `Timezone` as a possible config option. What is the purpose of these two functions if there are config options that I can set but are not returned by these functions?

Also, if building a GUI application I may want to show a configuration screen where users will enter desired values but if there is no way to enumerate all these options I can't build such a screen.

It would be great to extend the Configuration API to enumerate config options from these autoloadable extensions.

**Comment by Mytherin** [comment]
That's fair, we could include the names (but not descriptions) of [autoloadable extension settings](https://github.com/duckdb/duckdb/blob/f9e96b191088e65b4a1f95918312c40e31096dd9/src/include/duckdb/main/extension_entries.hpp#L394) since those are always the same and can indeed be set using `duckdb_set_config`. That will include most of the settings from extensions made by us, but will not include settings from community extensions or non-auto-loadable extensions.

For your GUI application - can't you just enumerate `duckdb_settings`?

**Comment by Giorgi** [comment]
Yes, I enumerate `duckdb_settings`. It will be great if you include the settings from the auto-loadable extensions in the API.

**Comment by Mytherin** [comment]
I've implemented it here - https://github.com/duckdb/duckdb/pull/14021

**Comment by Giorgi** [comment]
Thanks! That was fast
