### ISSUE TITLE
INSERT OR IGNORE with Autoincrement primary key / sequence RETURNING wrong id;

### ISSUE THREAD

**Issue by ghpu** [duckdb/duckdb#12540]
### What happens?

Given a table with a unique constraint index, and an autoincrement primary key based on a sequence :

```sql
CREATE SEQUENCE seq START 1;
CREATE TABLE bug (id INTEGER PRIMARY KEY DEFAULT NEXTVAL(seq), name VARCHAR);
CREATE UNIQUE INDEX idx ON bug (name);

INSERT OR IGNORE INTO bug VALUES (DEFAULT, 'toto') RETURNING(id);  # 1st try ok on empty table
```

```
┌───────┐
│  id   │
│ int32 │
├───────┤
│     1 │
└───────┘
```
OK

```sql
INSERT OR IGNORE INTO bug VALUES (DEFAULT, 'toto') RETURNING(id); # 2nd try insertion is ignored, but returning id has a bad value;
```

```
┌───────┐
│  id   │
│ int32 │
├───────┤
│     2 │
└───────┘
```

KO, should be id=1 because entry already exists in the table.

### To Reproduce

see above in description

### OS:

linux ubuntu 23.10 x86_64

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

command line

### Full Name:

Ghislain Putois

### Affiliation:

Orange

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by ghpu** [comment]
I guess that the ever increasing sequence is normal (same behaviour as postgres), but RETURNING(id) should return existing id instead of the incremented sequence value.

**Comment by Tishj** [comment]
I agree that this behavior is a little weird

To compare with SQLite:
```
sqlite> CREATE TABLE bug (
(x1...> id INTEGER PRIMARY KEY AUTOINCREMENT,
(x1...> name VARCHAR
(x1...> );
sqlite> CREATE UNIQUE INDEX idx ON bug (name);
sqlite> INSERT OR IGNORE INTO bug VALUES (DEFAULT, 'toto') RETURNING(id);
Parse error: near "DEFAULT": syntax error
  INSERT OR IGNORE INTO bug VALUES (DEFAULT, 'toto') RETURNING(id);
                      error here ---^
sqlite> INSERT OR IGNORE INTO bug VALUES (NULL, 'toto') RETURNING(id);
1
sqlite> select * from bug;
1|toto
sqlite> INSERT OR IGNORE INTO bug VALUES (NULL, 'toto') RETURNING(id);
sqlite> select * from bug;
1|toto
```

They don't return anything the second time around, which makes more sense

**Comment by ghpu** [comment]
Validated on master : c61d1ba . The new behaviour is working and useful, thanks!
