### ISSUE TITLE
datepart('quarter', INTERVAL) is broken

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#12544]
### What happens?

Extracting quarters from intervals is broken.

### To Reproduce

```sql
SELECT 
INTERVAL 3 QUARTERS AS ninemonths,
INTERVAL 1 HOURS AS onehour,
datepart('quarter', ninemonths),
datepart('quarter', onehour),
```

```
┌────────────┬──────────┬─────────────────────────────────┬──────────────────────────────┐
│ ninemonths │ onehour  │ datepart('quarter', ninemonths) │ datepart('quarter', onehour) │
│  interval  │ interval │              int64              │            int64             │
├────────────┼──────────┼─────────────────────────────────┼──────────────────────────────┤
│ 9 months   │ 01:00:00 │                               4 │                            1 │
└────────────┴──────────┴─────────────────────────────────┴──────────────────────────────┘
```

### OS:

Linux

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
While it seems strange to me, this is what Postgres does:

```sql
WITH intervals AS (
    SELECT 
        INTERVAL '2 YEARS' AS twoyears,
        INTERVAL '9 MONTHS' AS ninemonths,
        INTERVAL '1 HOURS' AS onehour
)
SELECT
    twoyears,
    ninemonths,
    onehour,
	date_part('quarter', twoyears),
	date_part('quarter', ninemonths),
	date_part('quarter', onehour)
FROM intervals;
```

|  twoyears | ninemonths | onehour  | date_part | date_part | date_part |
| ----------|------------|----------|-----------|-----------|-----------|
| 2 years  | 9 mons     | 01:00:00 |         1 |         4 |         1 |

**Comment by soerenwolfers** [comment]
Ohhh, it's simply one based. I don't catch that.

**Comment by hawkfish** [comment]
Yeah I though this was a copy and paste error, but it's deliberate.
