### ISSUE TITLE
Insert on conflict always returning nextval of primary key sequence

### ISSUE THREAD

**Issue by andymurd** [duckdb/duckdb#12552]
### What happens?

I created a table that uses a sequence for its primary key. When I insert a row with a conflict, the returned value is the next value of the sequence, not the primary key of the row.

### To Reproduce

To reproduce, just paste this into the CLI:

```sql
CREATE SEQUENCE test_id_sequence START 1;

CREATE OR REPLACE TABLE test (
    id    INTEGER PRIMARY KEY DEFAULT nextval('test_id_sequence'),
    value VARCHAR NOT NULL UNIQUE
);

INSERT INTO test (value) values ('abc') RETURNING id;
INSERT INTO test (value) values ('abc') ON CONFLICT (value) DO NOTHING RETURNING id;
```

Actual output:
```
./duckdb test.db
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
D CREATE SEQUENCE test_id_sequence START 1;
D 
D CREATE OR REPLACE TABLE test (
      id    INTEGER PRIMARY KEY DEFAULT nextval('test_id_sequence'),
      value VARCHAR NOT NULL UNIQUE
  );
D 
D INSERT INTO test (value) values ('abc') RETURNING id;
┌───────┐
│  id   │
│ int32 │
├───────┤
│     1 │
└───────┘
D 
D 
D INSERT INTO test (value) values ('abc') ON CONFLICT (value) DO NOTHING RETURNING id;
┌───────┐
│  id   │
│ int32 │
├───────┤
│     2 │
└───────┘
D 
```

I expect that last `2` to be `1` as the row has not changed.

Testing with the latest nightly python module produces the same result.

### OS:

Ubuntu 20.04

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

Python and CLI

### Full Name:

Andy Murdoch

### Affiliation:

maxmine.com.au

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Is this not the exact same issue as <https://github.com/duckdb/duckdb/issues/12540> raised 2 days ago?

**Comment by andymurd** [comment]
You are absolutely correct, my apologies.
