### ISSUE TITLE
Execution time increasing when running a query multiple times on Windows

### ISSUE THREAD

**Issue by Samuele-Tarantino** [duckdb/duckdb#12563]
### What happens?

Within one of our specific use case we noticed that when running a query in a loop the execution time increase at every iteration.

### To Reproduce

[The parquet file to reproduce the behavior](https://www.dropbox.com/scl/fi/xxsogd2cmkhmdqa7esoef/IncreasingTime.parquet?rlkey=ru12s3v4u1gv5cel50n5sn29f&st=yftod4pl&dl=0)

[The query to reproduce the behavior](https://www.dropbox.com/scl/fi/lmbvyfbqxtjoz5shf1qkv/IncreasingTimeQuery.sql?rlkey=8eq73a5day3xh9n8hkdzwk8gb&st=rznnnoyj&dl=0) (it read from the parquet)

Using a connection with ```datasource = :memory:``` in order to execute the specified query we duplicate this connection for every iteration.
The behavior is reproducible even without duplicating the connection.

Our implementation is based on Giorgi's C# DuckDB wrapper, but we have reproduced the issue also on Python and the CLI (by manually executing the query multiple time in sequence).

### OS:

Microsoft Windows 10 Enterprise x64

### DuckDB Version:

1.0.0

### DuckDB Client:

C#, CLI, Python

### Full Name:

Samuele Tarantino

### Affiliation:

Irion

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @Samuele-Tarantino, thanks for opening the issue. I tried to reproduce it on macOS with the CLI by running the script 10 times but did the query times stayed table.

```sql
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
.read 'IncreasingTimeQuery.sql'
```

How many times did you run the query

**Comment by Samuele-Tarantino** [comment]
Hi @szarnyasg, thanks for the quick reply. We use a benchmark system that runs the query about 100 times but we start seeing the slowdown already from around the 10th execution, from CLI we see a significant increase in time from the 20th execution.

**Comment by szarnyasg** [comment]
@Samuele-Tarantino thank, I could reproduce this on Windows, where the runtime went up from ~10 seconds to 30+ seconds at the end of the execution.

**Comment by Samuele-Tarantino** [comment]
Great, thank you!

**Comment by magneto-81** [comment]
@szarnyasg any news?
