### ISSUE TITLE
Changing precision prints incorrect value (number of leading zeros) when using precision {:.2} vs {:.3}

### ISSUE THREAD

**Issue by norcalli** [duckdb/duckdb#12569]
### What happens?

It prints 0.002 with precision `.2` and `0.00023` with precision `.3` using input number 0.000234.

### To Reproduce

```sql
select format('{:.2}', 0.00023404094995959);
```
```text
┌──────────────────────────────────────┐
│ format('{:.2}', 0.00023404094995959) │
│               varchar                │
├──────────────────────────────────────┤
│ 0.0023                               │
└──────────────────────────────────────┘
```
```sql
select format('{:.3}', 0.00023404094995959);
```
```
┌──────────────────────────────────────┐
│ format('{:.3}', 0.00023404094995959) │
│               varchar                │
├──────────────────────────────────────┤
│ 0.000234                             │
└──────────────────────────────────────┘
```

### OS:

x64

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Ashkan Kiani

### Affiliation:

Jane Street

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@norcalli thanks, I could reproduce this.
