### ISSUE TITLE
Illegal Predicate Pushdown leads to Casting error

### ISSUE THREAD

**Issue by OrangieLou** [duckdb/duckdb#12577]
### What happens?

The query plan for the query mentioned below rearranges the predicate `WHERE position('*' in b) = 0` such that it is executed *after* the cast which leads to an error. Since predicate and cast specifically happen in the cte, this should not be rearranged.

Plan:
```
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│     CAST(a AS INTEGER)    │
│     CAST(b AS INTEGER)    │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ ((CAST(col0 AS INTEGER) < │
│ CAST(col1 AS INTEGER)...  │
│ (position(col1, '*') = 0))│
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 5           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│      COLUMN_DATA_SCAN     │
└───────────────────────────┘  
```

### To Reproduce

Query using CTE:
```sql
WITH t(a, b) AS (
  SELECT a :: int, b :: int
  FROM (VALUES
    ('1', '4'),
    ('5', '3'),
    ('2', '*'),
    ('3', '8'),
    ('7', '*')) AS _(a, b)
  WHERE position('*' in b) = 0
)
SELECT a, b
FROM   t
WHERE  a < b;
```

Same applies when directly inlining:
```sql
SELECT a, b
FROM   (SELECT a :: int, b :: int
  FROM (VALUES
    ('1', '4'),
    ('5', '3'),
    ('2', '*'),
    ('3', '8'),
    ('7', '*')) AS _(a, b)
  WHERE position('*' in b) = 0) AS t(a,b)
WHERE  a < b;
```

### OS:

MacOS 14.3.1: aarch64 (Apple M1 Pro)

### DuckDB Version:

v1.0.1

### DuckDB Client:

CLI

### Full Name:

Louisa Lambrecht

### Affiliation:

University of Tübingen

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@OrangieLou, thanks, I could reproduce the issue and this is indeed failing and producing a different behavior compared to Postgres.
