### ISSUE TITLE
Query unnesting with grouping sets results in wrong output

### ISSUE THREAD

**Issue by hbirler** [duckdb/duckdb#12582]
### What happens?

The following two queries should return the same result:
```sql
select x, a, b
from
(values (1), (2)) t2(x),
lateral (select count(*), count(a) from (select 1, 2 where 1 = x) t(a, b) group by grouping sets ((), (b), (a, b))) t3(a, b);

select x, a, b
from
(
select 1, count(*), count(a) from (select 1, 2 where 1 = 1) t(a, b) group by grouping sets ((), (b), (a, b))
union all
select 2, count(*), count(a) from (select 1, 2 where 1 = 2) t(a, b) group by grouping sets ((), (b), (a, b))
) t3(x, a, b);
```

The correct result for both queries (also returned by Postgres) is:
```
x,a,b
1,1,1
1,1,1
1,1,1
2,0,0
```

However, for the first query, duckdb returns:
```
x,a,b
1,1,1
1,1,1
1,1,1
```

### To Reproduce

The queries require no database, thus DuckDB CLI can be used to reproduce.
I can also reproduce on DuckDB WASM.

### OS:

Linux

### DuckDB Version:

1.0

### DuckDB Client:

CLI

### Full Name:

Altan Birler

### Affiliation:

TUM

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@hbirler thanks, I could reproduce the issue. We'll take a look.

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in https://github.com/duckdb/duckdb/pull/13291

**Comment by hbirler** [comment]
Thanks!
