### ISSUE TITLE
accept failure when casting

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#1259]
Some datasets have wildcards to indicate missing values. Not the best practice but I can see why. For example imagine a column that was like "12345,N/A,123155". 

So, I would like to do something like CAST(x as BIGINT DEFAULT NULL), which would produce 12345,NULL,123155. This is like Clickhouse's toInt64OrNull.

**Comment by hannesmuehleisen** [comment]
We will likely introduce some TRY/CATCH facility to support this and related use cases.

**Comment by alanpaulkwan** [comment]
Elegant.

**Comment by hannesmuehleisen** [comment]
Sorry this was closed by accident

**Comment by Mytherin** [comment]
`TRY_CAST` exists now (see #2050).
