### ISSUE TITLE
DuckDB lag seems to be much slower than Polars

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#12600]
### What happens?

As reported in https://github.com/ibis-project/ibis/issues/9405, the lag operation in Polars appears to be much faster than in DuckDB.

### To Reproduce

```python
import time
import duckdb
import polars as pl
import numpy as np


rng = np.random.default_rng(1)
N = 10_000_000
a = rng.normal(size=N)
b = rng.normal(size=N)
c = rng.normal(size=N)
data = {'a': a, 'b': b, 'c': c}
df_pl = pl.LazyFrame(data)

cols = ["a", "b", "c"]
lags = [1, 2]


def add_lags_polars():
    return df_pl.select(
        pl.col(col).shift(-lag).alias(f'{col}_{lag}')
        for col in cols
        for lag in lags
    )


def add_lags_duckdb():
    sql = """
SELECT
  LAG(a, -1) OVER () AS a_1,
  LAG(a, -2) OVER () AS a_2,
  LAG(b, -1) OVER () AS b_1,
  LAG(b, -2) OVER () AS b_2
FROM df
    """
    rel = con.sql(sql)
    return rel.pl()

start = time.time()
add_lags_polars().collect()
stop = time.time()
print(f"polars:   {stop - start:.4f}s")

con = duckdb.connect()
con.execute("CREATE OR REPLACE TABLE df AS FROM df_pl")
start = time.time()
add_lags_duckdb()
stop = time.time()
print(f"duckdb:   {stop - start:.4f}s")
```

Sticking this in a script in `/tmp/test_duckdb_lags.py`, I get these results:

```
❯ python /tmp/test_duckdb_lags.py
polars:   0.0022s
duckdb:   1.4958s
```

### OS:

x86_64-linux, 16 physical cores, 32 logical cores, 64GB RAM, AMD Ryzen 9 3950X

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by cpcloud** [comment]
Just tried with https://pypi.org/project/duckdb/1.0.1.dev167/ and I'm seeing the same results.

**Comment by szarnyasg** [comment]
Thanks @cpcloud for the issue – I could reproduce it. We'll take a look.

**Comment by hawkfish** [comment]
What I meant by "look-ahead" is just that we accept negative LAGs and translate them to LEADs. The example here is relying heavily on random access to the data frame, which is hard to mimic in our streaming model.

**Comment by hawkfish** [comment]
I am curious about the use of negative lags - would it be possible to perform the desired operations by using a positive lag and swapping the semantics of the two columns?

**Comment by cpcloud** [comment]
Probably, I'm not sure what the original motivation was for their use.

**Comment by cpcloud** [comment]
> I am curious about the use of negative lags - would it be possible to perform the desired operations by using a positive lag and swapping the semantics of the two columns?

I think I misunderstood the context here! @hawkfish Was this rhetorical? Reading it again it seems like you're thinking out loud about the implementation, as opposed to asking about the use case.

**Comment by hawkfish** [comment]
I was wondering about the use of `LEAD` here (negative `LAG`) but upon reflection, that is how you turn an event table into a state table:

```sql
CREATE OR REPLACE TABLE states AS (
    SELECT * EXCLUDE(event_time),
        event_time AS event_begin, 
        LEAD(event_time, 1, 'infinity') OVER(PARTITION BY event_type ORDER BY event_time) AS event_end
    FROM events
);
```

**Comment by cpcloud** [comment]
Tried out 861cbbc and I see around a 6x improvement for positive lags, great work!
