### ISSUE TITLE
motherduck pivot Invalid Error: PendingQuery can only take a single statement erro

### ISSUE THREAD

**Issue by iamvarol** [duckdb/duckdb#12620]
### What happens?

I exported my data to the `mother duck` (https://app.motherduck.com/) after GA.
When I tried to use pivot on a table, I got the following error:
`Invalid Error: PendingQuery can only take a single statement`
To localize the problem, I tried to reproduce the official doc example and got the same error.
- https://duckdb.org/docs/sql/statements/pivot

### To Reproduce

Try to reproduce the official doc example (https://duckdb.org/docs/sql/statements/pivot).

```sql
--  table creation
CREATE TABLE Cities (
    Country VARCHAR, Name VARCHAR, Year INTEGER, Population INTEGER
);
INSERT INTO Cities VALUES ('NL', 'Amsterdam', 2000, 1005);
INSERT INTO Cities VALUES ('NL', 'Amsterdam', 2010, 1065);
INSERT INTO Cities VALUES ('NL', 'Amsterdam', 2020, 1158);
INSERT INTO Cities VALUES ('US', 'Seattle', 2000, 564);
INSERT INTO Cities VALUES ('US', 'Seattle', 2010, 608);
INSERT INTO Cities VALUES ('US', 'Seattle', 2020, 738);
INSERT INTO Cities VALUES ('US', 'New York City', 2000, 8015);
INSERT INTO Cities VALUES ('US', 'New York City', 2010, 8175);
INSERT INTO Cities VALUES ('US', 'New York City', 2020, 8772);

-- pivotting
PIVOT Cities
ON Year
USING sum(Population);
```

Error:
- Invalid Error: PendingQuery can only take a single statement

### OS:

motherduck

### DuckDB Version:

v1.0.0

### DuckDB Client:

v1.0.0-2024-06-142

### Full Name:

Emre Varol

### Affiliation:

Freelance

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Flogex** [comment]
Florian from MotherDuck here. Thanks for reporting this. I have reached out to you in our [Slack community](https://slack.motherduck.com/).
Since this problem is not related to core DuckDB, I think we can close this issue. cc @szarnyasg

**Comment by szarnyasg** [comment]
Hi @iamvarol – thanks for opening this issue. As @Flogex remarked, indeed, please raise this at the MotherDuck Slack, where they are best equipped to resolve it quickly.
