### ISSUE TITLE
current_timestamp cannot be used in having clause (Binder Error) 

### ISSUE THREAD

**Issue by jonathanswenson** [duckdb/duckdb#12646]
### What happens?

in 0.10.X+ (tried 1.0.0 as well) it appears as though current_timestamp cannot be used in a having clause anymore. 

A BinderError is thrown when I try. 

in 0.10.2 (cli)
```
v0.10.2 1601d94f94
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select 1 as one, max(cast('2024-06-21 12:00:00' as timestamp)) as mt group by one having mt <= current_timestamp;
Binder Error: column current_timestamp must appear in the GROUP BY clause or be used in an aggregate function
```

in 1.0.0
```
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select 1 as one, max(cast('2024-06-21 12:00:00' as timestamp)) as mt group by one having mt <= current_timestamp;
Binder Error: column current_timestamp must appear in the GROUP BY clause or be used in an aggregate function
```

In 0.9.2 this still works
```
❯ duckdb
v0.9.2 3c695d7ba9
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select 1 as one, max(cast('2024-06-21 12:00:00' as timestamp)) as mt group by one having mt <= current_timestamp;
┌───────┬─────────────────────┐
│  one  │         mt          │
│ int32 │      timestamp      │
├───────┼─────────────────────┤
│     1 │ 2024-06-21 12:00:00 │
└───────┴─────────────────────┘
```

It appears as though get_current_timestamp() is a workaround. 

Notably these queries also work in postgres (but can't use the alias 😭 )
```sql
select 
  1 as one, 
  max(cast('2024-05-01 00:00:00' as timestamp)) as mt 
group by one 
having max(cast('2024-05-01 00:00:00' as timestamp))  <= current_timestamp;
```

### To Reproduce

Simple SQL Query:

```sql
select 
  1 as one, 
  max(cast('2024-05-01 00:00:00' as timestamp)) as mt 
group by one 
having mt <= current_timestamp;
```

### OS:

macOS 14.2 aarch64

### DuckDB Version:

0.10.2, 1.0.0

### DuckDB Client:

cli, java, wasm

### Full Name:

Jonathan Swenson

### Affiliation:

Omni

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
I do reproduce.

This equivalent query works around the problem, working correctly:
```
select 
    1 as one, 
    max(cast('2024-05-01 00:00:00' as timestamp)) as mt 
  group by one 
  having mt <= get_current_timestamp();
```
