### ISSUE TITLE
Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation)

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#12667]
### What happens?

Out of Memory Error: Failed to allocate block of 262144 bytes (bad allocation)
7500000rows table（less than 18Mb） join itself，OOM，
both in python and cli
![image](https://github.com/duckdb/duckdb/assets/25274931/d2d7eb78-1666-4eb4-a491-5904ce8e1636)

### To Reproduce

sql is following, and duckdb file send to email: gabor@duckdblabs.com

```sql
create or replace table tmp_full_org_path as

	select

		a.biz_action_type_code, a.operating_unit_sk, a.stockorg_sk send_stockorg_sk, b.stockorg_sk receive_stockorg_sk, 1 send_level,

		case

			when a.scene_type in ('调拨') or (a.scene_type = '补调' and a.org_flag = 1) then 'gto.store_path_rule'

			when a.scene_type in ('补货', '返仓') or (a.scene_type = '补调' and a.org_flag = 2) then 'gto.warehouse_store_path_rule'

		end parameter_code-- select count(*)

	from tmp_skc_org_basic a

	inner join tmp_skc_org_basic b on a.operating_unit_sk = b.operating_unit_sk and a.biz_action_type_code = b.biz_action_type_code and a.skc_sk = b.skc_sk

	where

		case

			when a.scene_type in ('调拨', '返仓') then a.org_flag = 1

			when a.scene_type in ('补货') then a.org_flag = 2

			when a.scene_type in ('补调') then a.org_flag in (1, 2)

		end 

		and

		case

			when a.scene_type in ('补货', '调拨', '补调') then b.org_flag = 1

			when a.scene_type in ('返仓') then b.org_flag = 2

		end 

		and a.stockorg_sk <> b.stockorg_sk

	group by

		a.biz_action_type_code, a.operating_unit_sk, a.stockorg_sk, b.stockorg_sk, a.scene_type, a.org_flag

;
```

### OS:

centos7

### DuckDB Version:

1.0.0

### DuckDB Client:

python and cli

### Full Name:

wonb168

### Affiliation:

Linezone

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @wonb168, thanks, I got the database file. I started an EC2 instance with Ubuntu 22.04 / Aarch64 architecutre and 16 GB of memory and it completed the query, so I could not yet reproduce the issue.
```
$ ./duckdb path_parameter.duckdb -c '.read my.sql'
100% ▕████████████████████████████████████████████████████████████▏
```

**Comment by wonb168** [comment]
In production environment, one day's parquet have 7500 0000rows, about 400MB, attachment is zipped parquet file.
then pivot OOM,
and I send the file to your email : [abor@duckdblabs.com](mailto:gabor@duckdblabs.com)
thanks!

**Comment by szarnyasg** [comment]
@wonb168 as mentioned earlier, I am unable to reproduce the issue. How much memory do you have and what architecture are you using (x86_64/arm64)?

**Comment by wonb168** [comment]
64g memory，centos7，x86 intel

**Comment by szarnyasg** [comment]
On Ubuntu 22.04 with 32 GB RAM, I cannot reproduce the issue. The output shows that the query is only using 10.5 GB memory.

```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
...
```

```
$ /usr/bin/time -v ./duckdb path_parameter.duckdb -c ".read my.sql"
100% ▕████████████████████████████████████████████████████████████▏
        Command being timed: "./duckdb path_parameter.duckdb -c .read my.sql"
        User time (seconds): 82.61
        System time (seconds): 5.62
        Percent of CPU this job got: 374%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:23.56
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 10548976
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 2653286
        Voluntary context switches: 9082
        Involuntary context switches: 1053
        Swaps: 0
        File system inputs: 0
        File system outputs: 24584
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

There are slim chances that it will help but what you can try as a workaround is building a DuckDB from source with jemalloc disabled: https://duckdb.org/docs/extensions/jemalloc

**Comment by hrshdhgd** [comment]
Potential solution: https://github.com/duckdb/duckdb/issues/9880#issuecomment-2302076955
