### ISSUE TITLE
`clang_format` doesn't support Apple Silicon so format-fix doesn't run

### ISSUE THREAD

**Issue by rustyconover** [duckdb/duckdb#12661]
### What happens?

Unable to use `make format-fix` on Apple M3 laptop due to clang_format not supporting the CPU type.

### To Reproduce

First get some Apple hardware.  Then create a python environment and install the listed requirements like:

`pip3 install clang_format==11.0.1`

Then try to run format-fix.

```
$ make format-fix
rm -rf src/amalgamation/*
python3 scripts/format.py --all --fix --noconfirm
Traceback (most recent call last):
  File "/Users/rusty/Development/duckdb-crontab-extension/.venv/bin/clang-format", line 8, in <module>
    sys.exit(clang_format())
             ^^^^^^^^^^^^^^
  File "/Users/rusty/Development/duckdb-crontab-extension/.venv/lib/python3.12/site-packages/clang_format/__init__.py", line 11, in clang_format
    return _run("clang-format")
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/Development/duckdb-crontab-extension/.venv/lib/python3.12/site-packages/clang_format/__init__.py", line 7, in _run
    return os.execv(executable, [name] + sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 86] Bad CPU type in executable
you need to run `pip install clang_format==11.0.1 - ` Command '('clang-format', '--version')' returned non-zero exit status 1.
make: *** [format-fix] Error 255
```

### OS:

Mac OS X

### DuckDB Version:

main

### DuckDB Client:

N/a

### Full Name:

Rusty Conover

### Affiliation:

self

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mause** [comment]
You'll need to install Rosetta support first for it to work, though we'll likely look into bumping the version in the future

**Comment by rustyconover** [comment]
Works great with Rosetta thanks.
