### ISSUE TITLE
Unexpected error raised by PRINTF

### ISSUE THREAD

**Issue by chenglinLiang** [duckdb/duckdb#12686]
### What happens?

Updating a column using PRINTF raises `primary key constraint` and `Invalid Input` errors.

### To Reproduce

```sql 
CREATE TABLE t0(c0 VARCHAR, PRIMARY KEY(c0));
```
**Case one**
``` sql
INSERT INTO t0(c0) VALUES (-112498833);
UPDATE t0 SET c0=PRINTF(t0.c0);
```
```
Constraint Error: Duplicate key "c0: -112498833" violates primary key constraint. If this is an unexpected constraint violation please double check with the known index limitations section in our documentation (https://duckdb.org/docs/sql/indexes).
```
**Case two**
``` sql
INSERT INTO t0(c0) VALUES ('ay<L,%Ite');
UPDATE t0 SET c0=PRINTF(t0.c0);
```
```
Invalid Input Error: Argument index "0" out of range
```
I have reproduced these cases on the latest version of SQLite and did not encounter any problems.

### OS:

Ubuntu 20.04.6 x64

### DuckDB Version:

v1.0.0 (1f98600)

### DuckDB Client:

cli

### Full Name:

Personal

### Affiliation:

Personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@chenglinLiang thanks, we'll take a look!

**Comment by szarnyasg** [comment]
This is expected behaviour as updates are implemented as deletes and inserts, which triggers the constraint: https://duckdb.org/docs/sql/indexes#updates-become-deletes-and-inserts

That said, the documentation on this should be improved.

**Comment by szarnyasg** [comment]
FWIW, the following script also triggers the issue:

```sql
CREATE TABLE tbl(id VARCHAR PRIMARY KEY);
INSERT INTO tbl VALUES ('123');
UPDATE tbl SET id = id;
```
