### ISSUE TITLE
NaN behaves erratically

### ISSUE THREAD

**Issue by soobrosa** [duckdb/duckdb#12696]
### What happens?

Column is a DOUBLE
```sql
select wordword_id, count(*) from x group by 1 order by 2 desc limit 1;
```
```
┌─────────────┬──────────────┐
│ wordword_id │ count_star() │
│   double    │    int64     │
├─────────────┼──────────────┤
│         nan │      3863225 │
└─────────────┴──────────────┘
```
```sql
select count(*) from x where wordword_id = 'nan';
```
```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       480277 │
└──────────────┘
```

### To Reproduce

Ran from the CLI on a Parquet.

### OS:

Mac M3

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Daniel Molnar

### Affiliation:

Thema AI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @soobrosa, thanks for opening this issue. To tackle it, we need a reproducer. Would it be possible for you to create a synthetic dataset that allows reproducing the issue?

**Comment by soerenwolfers** [comment]
Whatever the resolution here, it probably needs some documentation. Even in IEEE754, NaN has surprising behavior (there can be multiple NaNs, and even two bitwise equal NaNs don't compare equal), but duckdb isn't even fully IEEE754 compliant (which may work in your favor here depending on your expectations) 

Related: https://github.com/duckdb/duckdb/discussions/10956

**Comment by dmcmurchy** [comment]
@soobrosa  - Have you tried using `WHERE ISNAN(wordword_id)` instead of using `where wordword_id = 'nan' ` 

FYI - I came for another reason but saw your post and tried it on a much smaller dataset (created the table from a CSV file and the column contained no NULLs).  I didn't observe the same behaviour.

![image](https://github.com/duckdb/duckdb/assets/5430744/b1b2abf7-002d-4c06-a35e-a26ca5c8ba22)

**Comment by soobrosa** [comment]
@dmcmurchy thanks for chiming in! I tried to reproduce also with a synthetic dataset and failed to do so.

BUT great idea as

```
select count(*) from x where isnan(wordword_id);
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      3863225 │
└──────────────┘
```
Maybe it's a clue @szarnyasg

**Comment by Tishj** [comment]
It might be unrelated, but I had a run-in with IEEE nan spec quirks and this reminded me of it, here's the PR that addressed it:
<https://github.com/duckdb/duckdb/pull/5283>

**Comment by Tishj** [comment]
@soobrosa You can also use this in reverse, I think it's worth checking if your dataset contains different variations of NaN, for debugging purposes:
```sql
D select 'nan'::double::BITSTRING;
┌──────────────────────────────────────────────────────────────────┐
│                CAST(CAST('nan' AS DOUBLE) AS BIT)                │
│                               bit                                │
├──────────────────────────────────────────────────────────────────┤
│ 0111111111111000000000000000000000000000000000000000000000000000 │
└──────────────────────────────────────────────────────────────────┘
```
