### ISSUE TITLE
Can't stream record batches from the same cursor that I'm using to insert rows

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#12713]
### What happens?

When I stream Arrow record batches from a query, I can't then use that same connection to insert rows into another table in the same database.

I **can** do that if I create a new cursor, but then I've lost access to all the temporary tables that I've registered on the top level connection.

### To Reproduce

```python
import duckdb
import pyarrow as pa

con = duckdb.connect()
con.execute("CREATE OR REPLACE TEMP TABLE source AS SELECT x FROM RANGE(100) _ (x)")
con.execute("CREATE OR REPLACE TABLE target(x INTEGER)")

n = 0

for batch in con.sql("FROM source").fetch_arrow_reader(batch_size=10):
    source_batch = pa.Table.from_batches([batch])
    con.execute("INSERT INTO target FROM source_batch")
    n += len(source_batch)

assert n == 100
```

```
    assert n == 100
           ^^^^^^^^
AssertionError
```

### OS:

x86_64-linux

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
`fetch_arrow_reader` creates a StreamQueryResult, which starts query execution and keeps query execution occupied until the result is fully consumed.

Currently it is not possible to have multiple queries executing on the same connection, the `con.execute("INSERT INTO target FROM source_batch")` call is silently canceling the ongoing execution and starting a new one.
The next time you try to fetch the StreamQueryResult::Fetch will either report an error, or just give you back an empty chunk to indicate end-of-result

**Comment by cpcloud** [comment]
So, I guess the current state is that you effectively cannot:

1. stream out record batches of temporary objects
2. process those batches in Python
3. insert the processed batch back into a non-temporary table in the same connection

**Comment by Tishj** [comment]
You can, but not while streaming.
Perhaps we could add a boolean to `fetch_arrow_reader` to materialize the result entirely, though that doesn't directly help you right now

**Comment by jcrist** [comment]
Is there a way we could make the original reader error when the next batch is requested (if it's invalidated by another query executing), rather than silently terminating and returning no further batches? That way users wouldn't accidentally get incorrect results, and it's easier for us to point them to alternate patterns they can use to accomplish the same task.

**Comment by Tishj** [comment]
Yea that makes sense to me, I was also a little surprised it didn't error
