### ISSUE TITLE
struct: no support for UPDATE?

### ISSUE THREAD

**Issue by enote-kane** [duckdb/duckdb#12715]
### What happens?

I was trying to update struct values, but couldn't find any documentation about it and also no way to make it work.

Using `struct_insert` inside an `UPDATE` statement to set the column fails with:
```
Mismatch Type Error: Type STRUCT(<field-spec-new>) does not match with STRUCT(<field-spec-old>). Cannot cast STRUCTs of different size
```
...if the struct previously had not defined the to-be-updated field, or with:
```
Binder Error: Duplicate struct entry name "<field>"
```

Trying to just set a specific field value fails as well with (same error, no matter whether the field already exists or not):
```
Conversion Error: Type <field-value-type> with value <new-value> can't be cast to the destination type STRUCT
```

### To Reproduce

```sql
CREATE TABLE test_add AS
SELECT { name: 'Alice', role: 'admin' } AS a;

UPDATE test_add SET a = struct_insert(a, auth_type := 'oidc');
UPDATE test_add SET a.auth_type = 'oidc';


CREATE TABLE test_set AS
SELECT { name: 'Alice', role: 'admin', auth_type: NULL::VARCHAR } AS a;

UPDATE test_set SET a = struct_insert(a, auth_type := 'oidc');
UPDATE test_set SET a.auth_type = 'oidc';
```

### OS:

GNU/Linux x64

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Ancoron Luciferis

### Affiliation:

Enote GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @enote-kane, thanks for opening this issue. Structs have a fixed schema, which cannot be changed with updated. Indeed this should be covered better in the documentation. From DuckDB's perspective, this is expected behavior.

**Comment by enote-kane** [comment]
@szarnyasg OK, that makes sense for the first case (table `test_add`), but shouldn't it be allowed to somehow change a struct field value (table `test_set`)?

As I see the current behavior, it's not only the struct schema that is immutable, but any struct value seems to be immutable, or did I make any mistake when creating the struct?
