### ISSUE TITLE
Result returned for incorrect sub-query

### ISSUE THREAD

**Issue by pmg1991** [duckdb/duckdb#12733]
### What happens?

Result generated for incorrect sub-query : for eg. 
Reproduced on Live demo Duckdb Shell
```
select season_num from train_services;
Binder Error: Referenced column "season_num" not found in FROM clause!
Candidate bindings: "train_services.station_name"
LINE 1: select season_num from train_services;
```

But this query runs fine on small data set, For large data set takes lot of time to run .
```
select * from t2 where episode_num in ( select season_num from train_services);
 1 ┆ 1 ┆ 1966-09-08  ┆ 0 ┆ 1 ┆ 0 ┆ 1 ┆ 0 ┆ 0 ┆ 0 ┆ 0 ┆ 0 ┆ 0 ┆ 5 ┆ 0 ┆ 0 ┆ 0 ┆ 1 
```

### To Reproduce

```
Create table t2 as from 's3://duckdb-blobs/data/Star_Trek-Season_1.csv';
CREATE TABLE train_services AS  FROM 's3://duckdb-blobs/train_services.parquet';
select * from t2 where episode_num in ( select season_num from train_services);  -- Executed Successfuly 
select season_num from train_services; -- Binder Error
```
This query should fail : select * from t2 where episode_num in ( select season_num from train_services); 
### OS:

Any

### DuckDB Version:

1.0.0

### DuckDB Client:

DuckDB Shell

### Full Name:

Pmg

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello @pmg1991, I cannot reproduce the issue:

```
D Create table t2 as from 's3://duckdb-blobs/data/Star_Trek-Season_1.csv';
CREATE TABLE train_services AS  FROM 's3://duckdb-blobs/train_services.parquet';
select * from t2 where episode_num in ( select season_num from train_services);
Run Time (s): real 0.768 user 0.086061 sys 0.038507
D CREATE TABLE train_services AS  FROM 's3://duckdb-blobs/train_services.parquet';
Run Time (s): real 1.330 user 0.147855 sys 0.022847
D select * from t2 where episode_num in ( select season_num from train_services);
┌────────────┬─────────────┬────────────┬──────────────────┬───┬──────────────────────┬──────────────────────┬──────────────────────┐
│ season_num │ episode_num │ aired_date │ cnt_kirk_hookups │ … │ cnt_im_givin_her_a…  │ cnt_highly_illogic…  │ bool_enterprise_sa…  │
│   int64    │    int64    │    date    │      int64       │   │        int64         │        int64         │        int64         │
├────────────┼─────────────┼────────────┼──────────────────┼───┼──────────────────────┼──────────────────────┼──────────────────────┤
│          1 │           1 │ 1966-09-08 │                0 │ … │                    0 │                    0 │                    1 │
├────────────┴─────────────┴────────────┴──────────────────┴───┴──────────────────────┴──────────────────────┴──────────────────────┤
│ 1 rows                                                                                                       18 columns (7 shown) │
```

Can you please revise the issue's text so it's clear what instructions exactly need to be executed for reproduction? Thanks.

**Comment by pmg1991** [comment]
@szarnyasg  in sub query  column season_num is not present in  table train_services it should give Binder error.  If sub query (select season_num from train_services;) is run individually it gives binder error . So both the queries should give error.  

```
D select season_num from train_services;
Binder Error: Referenced column "season_num" not found in FROM clause!
Candidate bindings: "train_services.station_name"
LINE 1: select season_num from train_services;
```

**Comment by szarnyasg** [comment]
Thanks for the clarification! The following query is a correlated subquery, see:

* https://duckdb.org/docs/sql/expressions/subqueries#correlated-subqueries
* https://duckdb.org/2023/05/26/correlated-subqueries-in-sql.html
* https://en.wikipedia.org/wiki/Correlated_subquery

```sql
select * from t2 where episode_num in ( select season_num from train_services);  -- Executed Successfuly 
```

It takes `season_num` from the `FROM` clause of the outer query, and uses it when running the subquery.

**Comment by pmg1991** [comment]
Thanks for clarification , now it makes sense . Please close the issue.

**Comment by szarnyasg** [comment]
No problem, was happy to clarify!
