### ISSUE TITLE
Documentation for read_csv function claims header is false by default, but isn't

### ISSUE THREAD

**Issue by brenochoa** [duckdb/duckdb#12742]
### What happens?

The [documentation for the read_csv function](https://duckdb.org/docs/data/csv/overview#csv-loading) claims the default for the header parameter is FALSE, but it actually isn't **EDIT: when the file contains all VARCHAR columns**

### To Reproduce

With any valid CSV file with no header (I tried with a single column and three **EDIT: all VARCHAR type**):

`SELECT count(*) FROM read_csv('path_to.csv')` is one less than `SELECT count(*) FROM read_csv('path_to.csv', header = false)`, which according to the documentation shouldn't be the case.

### OS:

Linux, x64

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI, Python

### Full Name:

Bren Ochoa

### Affiliation:

Illumina

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
```bash
$ cat path_to.csv
```
```text
1
2
3
```

SQL queries:
```sql
FROM read_csv('path_to.csv');
```
```
┌─────────┐
│ column0 │
│  int64  │
├─────────┤
│       1 │
│       2 │
│       3 │
└─────────┘
```

```sql
SELECT count(*) FROM read_csv('path_to.csv');
```
````
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            3 │
└──────────────┘
```

**Comment by brenochoa** [comment]
Hm, maybe it needs to be a CSV with text columns?

![image](https://github.com/duckdb/duckdb/assets/35033582/421cbfc5-dfa3-4eb3-9e6f-448f34f1504e)

**Comment by szarnyasg** [comment]
What's happening in your case is that CSV schema auto-detection, which is turned on by default. You can turn it off using `read_csv(..., auto_detect = false)`.

**Comment by brenochoa** [comment]
Ah, I see... Still, the behaviour seems to deviate from what [the documentation says](https://duckdb.org/docs/data/csv/auto_detection.html#header-detection) (emphasis mine):

> Note that headers cannot be detected correctly if all columns are of type VARCHAR – as in this case the system cannot distinguish the header row from the other rows in the file. In this case **_the system assumes the file has no header_**. This can be overridden using the header option.

In my all VARCHAR case, it seems that the assumption is made that the file DOES have a header, when in fact it isn't intended to have one.

**Comment by pdet** [comment]
Thanks for reporting this; indeed, the documentation is not up to date.

We decided to add a breaking change some months ago (see https://github.com/duckdb/duckdb/pull/10714).

**Comment by szarnyasg** [comment]
@brenochoa, indeed this is an issue with the documentation. Thanks for pointing out the erroneous part and thanks @pdet for confirming. I submitted a fix at https://github.com/duckdb/duckdb/issues/12742.
