### ISSUE TITLE
Conversion Error: Malformed JSON

### ISSUE THREAD

**Issue by PDEUXA** [duckdb/duckdb#12752]
### What happens?

When trying to de an operation on JSON fields, strange error appears.
This works fine:
![image](https://github.com/duckdb/duckdb/assets/56270922/5cbd384f-7d60-4aa2-ba32-beecb6707aa4)

However doing operations on both fields fail:
![image](https://github.com/duckdb/duckdb/assets/56270922/c0e8d0f9-d3bf-46cb-b688-66ae38c8ccdf)

The only way to overcome this is to explicitely cast field to STRING.
![image](https://github.com/duckdb/duckdb/assets/56270922/b2fd4558-058c-441a-a3e2-f8a4b0878e5f)

In fact the field returned is JSON type, even if we take the value of the json object retrieved by the path, (that should be string).

```sql
SELECT data.data.stuff FROM dataframe
```
should have a return type of the same type of 'data.data.stuff' not JSON by default

### To Reproduce

See example above

### OS:

linux, macos(arm)

### DuckDB Version:

1.0

### DuckDB Client:

3.12

### Full Name:

Pierre Arnaud

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, could you please paste the code from the screenshots and attach the data that's loaded to the `df` dataframe?
