### ISSUE TITLE
Unexpected results from INNER JOIN

### ISSUE THREAD

**Issue by chenglinLiang** [duckdb/duckdb#12767]
### What happens?

When I performed a join between two tables, inconsistent results appeared. The issue seems to be with the INNER JOIN.

### To Reproduce

``` sql
CREATE TABLE t0(c0 FLOAT4);
CREATE TABLE t1(c0 FLOAT4);
INSERT INTO t0(c0) VALUES ('0');
INSERT INTO t1(c0) VALUES ('-0');
```
**Case one**
``` sql
SELECT t1.c0 FROM t1 INNER JOIN t0 ON t1.c0 = t0.c0;
```
```
┌───────┐
│  c0   │
│ float │
├───────┤
│   0.0 │
└───────┘
```
**Case two**
``` sql
SELECT t1.c0 FROM t1 LEFT JOIN t0 ON t1.c0 = t0.c0;
```
```
┌───────┐
│  c0   │
│ float │
├───────┤
│  -0.0 │
└───────┘
```

### OS:

Ubuntu 20.04.6 x64

### DuckDB Version:

v1.0.0 (1f98600)

### DuckDB Client:

Cli

### Full Name:

Personal

### Affiliation:

Personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Since `-0=0`, that seems fine.

**Comment by chenglinLiang** [comment]
> Since `-0=0`, that seems fine.

You are right, the results of these two values are the same in practice. I have reproduced this in both SQLite3 and Postgresql. In SQLite3, the results of both INNER JOIN and LEFT JOIN are `0`, while in Postgresql, the results are `-0`. Therefore, I believe there might be some inconsistency in data display in Duckdb.

**Comment by carlopi** [comment]
If you try on main (I tried `v1.0.1-dev2074 5ebd8ca697`, both results in:
```
D SELECT t1.c0 FROM t1 INNER JOIN t0 ON t1.c0 = t0.c0;
┌───────┐
│  c0   │
│ float │
├───────┤
│  -0.0 │
└───────┘
D SELECT t1.c0 FROM t1 LEFT JOIN t0 ON t1.c0 = t0.c0;
┌───────┐
│  c0   │
│ float │
├───────┤
│  -0.0 │
└───────┘
```

I am not sure whether we want to commit to this exact behaviour, or positive and negative nulls are basically the same and so implementation dependent.

Possible test:
```sql
SELECT t1.c0::VARCHAR == '-0.0' FROM t1 LEFT JOIN t0 ON t1.c0 = t0.c0;
```
to be true

**Comment by chenglinLiang** [comment]
Thanks for your suggestion, I tried the latest commit in main (5ebd8ca)
**In v1.0.0**
``` sql
D SELECT t1.c0::VARCHAR == '-0.0' FROM t1 INNER JOIN t0 ON t1.c0 = t0.c0;
┌───────────────────────────────────┐
│ (CAST(t1.c0 AS VARCHAR) = '-0.0') │
│              boolean              │
├───────────────────────────────────┤
│ false                             │
└───────────────────────────────────┘
```
**In main (5ebd8ca)**
``` sql
D SELECT t1.c0::VARCHAR == '-0.0' FROM t1 INNER JOIN t0 ON t1.c0 = t0.c0;
┌───────────────────────────────────┐
│ (CAST(t1.c0 AS VARCHAR) = '-0.0') │
│              boolean              │
├───────────────────────────────────┤
│ true                              │
└───────────────────────────────────┘
```
In the latest commit, INNER JOIN yields the correct results, but I am not sure if the development version has fully resolved this issue. In the current stable version, this problem seems to still exist.

**Comment by Mytherin** [comment]
Thanks for reporting! As mentioned, while `-0.0` and `0.0` are distinct floating point values, they are equivalent. What is happening here is that the system is optimizing `t1.c0` to instead return `t0.c0` - which is allowed as there is a predicate that enforces these two values are equivalent (`t1.c0 = t0.c0`). The reason for this is improved query performance.

We could resolve this by disabling these types of optimizations for floating point numbers. However, as previously stated, the results are correct here as `-0.0` = `0.0`. Disabling these optimizers would introduce additional complexity to the optimizer and slow down processing of floating point numbers for queries where these optimizations could now no longer be applied. As such, this does not seem like a worthwhile trade-off. As such, I would say this is working as expected.
