### ISSUE TITLE
duckdb.duckdb.IOException: IO Error: Failed to create directory "/root/.duckdb/": Read-only file sy

### ISSUE THREAD

**Issue by MarcSkovMadsen** [duckdb/duckdb#12775]
### What happens?

When I try to execute `connection.sql(query=query, params=params)` inside my deployed docker container I get

`duckdb.duckdb.IOException: IO Error: Failed to create directory "/root/.duckdb/": Read-only file system`.

The problem is that my filesystem is readonly for security reasons. I'm not allowed to deploy if its not readonly.

The writeable place I can use is `/tmp`. I also have a netapp fileshare which is writeable at `/home/jovyan/fshared`. I tried looking in the documentation - but I cannot see it described anywhere how I can change this.

### To Reproduce

Deploy in docker with readonly filesystem. Run `connection.sql(query, params)`.

### OS:

linux

### DuckDB Version:

1.0.0

### DuckDB Client:

python

### Full Name:

Marc Skov Madsen

### Affiliation:

Ørsted

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by MarcSkovMadsen** [comment]
I'll try `SET home_directory=/tmp` and report back.

**Comment by MarcSkovMadsen** [comment]
`SET home_directory='/tmp'` solved the problem.

**Comment by iamzul** [comment]
thanks Marc, I had the same problem with my aws glue so I set up conn.execute("SET home_directory='/tmp';") and it solved my problem
