### ISSUE TITLE
Discrepancy in Handling Interval Operations Between PostgreSQL and DuckDB

### ISSUE THREAD

**Issue by arifsaslam** [duckdb/duckdb#12784]
### What happens?

There appears to be a discrepancy in the results of interval arithmetic between PostgreSQL and DuckDB. When subtracting a complex interval from a timestamp, PostgreSQL and DuckDB yield different results. 

### To Reproduce

the query 
```sql
select ('1920-12-12 01:02:02+05:30'::timestamptz + interval '-1 month 400 day 6000 minute 121 hour 12 second')::timestamptz as r;
```
in Postgres returns
```
             r             
---------------------------
 1921-12-26 06:02:14+05:30
(1 row)


```
and in duckdb returns:
```
┌───────────────────────────┐
│             r             │
│ timestamp with time zone  │
├───────────────────────────┤
│ 1921-12-25 06:02:14+05:30 │
└───────────────────────────┘

```

### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

1.0

### DuckDB Client:

python

### Full Name:

Arif Aslam

### Affiliation:

Mammoth Analytics Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
@arifsaslam Please include your time zone when reporting issues like this.

**Comment by hawkfish** [comment]
Looks like `Asia/Kolkata `?

```sql
D from pg_timezone_names() where utc_offset = interval '5 hours 30 minutes';
```

|     name      |    abbrev    | utc_offset | is_dst |
|---------------|--------------|------------|-------:|
| Asia/Calcutta | IST          | 05:30:00   | false  |
| Asia/Colombo  | Asia/Colombo | 05:30:00   | false  |
| Asia/Kolkata  | IST          | 05:30:00   | false  |
| IST           | IST          | 05:30:00   | false  |
