### ISSUE TITLE
Slow read compared to SQLite

### ISSUE THREAD

**Issue by ucicelos** [duckdb/duckdb#1281]
I am building a database with options data. It was reading really fast when I had few days loaded but as I loaded couple of years the select started taking 100 seconds or so....I copied same data over to SQLite and it takes 5-6 seconds. The table is about 15 GB.

The files are stored on NVMe Gen4 drives and I am using fetchdf to get the data, anything else I could be doing wrong?

**Comment by Alex-Monahan** [comment]
Could you post your code, or even better your code and a sample of your DB?

**Comment by hannesmuehleisen** [comment]
Any more details here @ucicelos
