### ISSUE TITLE
Connection Error : existing extension

### ISSUE THREAD

**Issue by Victordeleusse** [duckdb/duckdb#12814]
### What happens?

An error occured when trying to connect to the cloud service

`
con = duckdb.connect('md:')
          ^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Failed to download extension "motherduck" at URL "http://extensions.duckdb.org/v1.0.0/windows_amd64/motherduck.duckdb_extension.gz"
Extension "motherduck" is an existing extension.
 (ERROR Connection)
`

### To Reproduce

`
import duckdb

con = duckdb.connect('md:')
`

### OS:

windows amd_64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python 3.12.4

### Full Name:

Victor de Leusse

### Affiliation:

42

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @Victordeleusse, the URL <http://extensions.duckdb.org/v1.0.0/windows_amd64/motherduck.duckdb_extension.gz> is valid – do you have any firewall/proxy configuration that may disallow downloading via `http://`?

Can you install the extension manually by running `INSTALL md;` or install other extensions such as `INSTALL httpfs;` ?
