### ISSUE TITLE
InternalException: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

### ISSUE THREAD

**Issue by karansampath** [duckdb/duckdb#12818]
### What happens?

After closing my connection on my Python client, connecting and writing to it causes this error. If I am understanding correctly, this shouldn't happen since I am reopening the connection and therefore it should allow a write.

### To Reproduce

```
import duckdb
schema = {
            "doc_id": "VARCHAR",
            "embeddings": "FLOAT[384]",
            "properties": "MAP(VARCHAR, VARCHAR)",
            "text_representation": "VARCHAR",
            "bbox": "DOUBLE[]",
            "shingles": "BIGINT[]",
            "type": "VARCHAR",
        }
in_memory_db = duckdb.connect(":default:")
in_memory_db.execute(f"""CREATE TABLE in_memory_table (doc_id {schema.get('doc_id')},
                      embeddings {schema.get('embeddings')}, properties {schema.get('properties')}, 
                      text_representation {schema.get('text_representation')}, bbox {schema.get('bbox')}, 
                      shingles {schema.get('shingles')}, type {schema.get('type')})"""
in_memory_db.close()
in_memory_db = duckdb.connect(":default:")
in_memory_db.execute(f"""CREATE TABLE in_memory_table (doc_id {schema.get('doc_id')},
                      embeddings {schema.get('embeddings')}, properties {schema.get('properties')}, 
                      text_representation {schema.get('text_representation')}, bbox {schema.get('bbox')}, 
                      shingles {schema.get('shingles')}, type {schema.get('type')})"""
```

### OS:

arm64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Karan Sampath

### Affiliation:

Aryn AI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I can't reproduce this on `main`

```
➜  duckdb git:(main) ✗ python3 tmp/default_connection_close.py
Traceback (most recent call last):
  File "/Users/thijs/DuckDBLabs/duckdb/tmp/default_connection_close.py", line 18, in <module>
    in_memory_db.execute(f"""CREATE TABLE in_memory_table (doc_id {schema.get('doc_id')},
duckdb.duckdb.ConnectionException: Connection Error: Connection has already been closed
```

**Comment by karansampath** [comment]
Hi, please find the full code below, I missed a line which should hopefully make it reproducible now. The full error is as follows:
`InternalException: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
`

The code is below:
```
schema = {
            "doc_id": "VARCHAR",
            "embeddings": "FLOAT[384]",
            "properties": "MAP(VARCHAR, VARCHAR)",
            "text_representation": "VARCHAR",
            "bbox": "DOUBLE[]",
            "shingles": "BIGINT[]",
            "type": "VARCHAR",
        }
in_memory_db = duckdb.connect(":default:")
in_memory_db.install_extension("vss")
in_memory_db.load_extension("vss")
in_memory_db.execute(f"""CREATE TABLE in_memory_table (doc_id {schema.get('doc_id')},
                      embeddings {schema.get('embeddings')}, properties {schema.get('properties')}, 
                      text_representation {schema.get('text_representation')}, bbox {schema.get('bbox')}, 
                      shingles {schema.get('shingles')}, type {schema.get('type')})"""
    )
in_memory_db.execute("""INSERT INTO in_memory_table SELECT * FROM df; 
                      CREATE INDEX in_memory_table_index ON in_memory_table USING HNSW(embeddings)""")
in_memory_db.sql(f"ALTER TABLE in_memory_table ADD COLUMN metadata VARCHAR")
in_memory_db.close()
in_memory_db = duckdb.connect(":default:")
in_memory_db.install_extension("vss")
```
It fails on the last line for me.

**Comment by Tishj** [comment]
Thanks, that makes it reproducable for me
I know what the issue is, and there are likely other places that suffer from this, I have worked on a generic fix that should cover all of those 👍
