### ISSUE TITLE
Bug loading multiple tables, with mutltiple parquets each at the same time on multiple cursors/threads

### ISSUE THREAD

**Issue by dioptre** [duckdb/duckdb#12839]
### What happens?

TransactionContext Error: Catalog write-write conflict on create with "Schema\0f87fffac340b11efbd83cd513e73c5df\0f87fffac340b11efbd83cd513e73c5df\0Table\0f87fffac340b11efbd83cd513e73c5df\0issue_label" 

### To Reproduce

Load multiple tables with multiple threads, cursors, parquets

### OS:

Mac

### DuckDB Version:

1

### DuckDB Client:

Python

### Full Name:

Andrew Grosser

### Affiliation:

Sourcetable

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Please provide a reproduction for your issue.

From what little you've given though, this looks like expected behavior.

You have two connections that are both trying to create the same schema

**Comment by dioptre** [comment]
I have locks on both schema and table creation of duplicate names.

The only way to stop this from happening is to prevent the “create or
replace table xxx” of different tables of the same schema at the same time.

This equates to “you can’t reliably create tables in parallel across
cursors”.

I don’t think this is expected.

When I have more time I can provide a concrete example.

This is for others to track as well as more people get the error.

The workaround isn’t great as it prohibits parallel loading of tables using
the native duck parquet/csv loader.

Thanks

**Comment by Tishj** [comment]
As mentioned, please provide a reproduction, we can't work with this.

**Comment by Tishj** [comment]
I did not mean to change the status of this issue.
As per my last comment, this issue is entirely not actionable in its current state.
