### ISSUE TITLE
make failure on MacOS in master branch

### ISSUE THREAD

**Issue by qubin-ben** [duckdb/duckdb#12857]
### What happens?

I just download the duckdb and try to compile from my macOS. It report the following error in master branch. Note: the error disappear when I checkout the branch to V1.0. 

```
 ericqu@ERICBQU-MB0  ~/git/duckdb   main  GEN=ninja make
mkdir -p ./build/release && \
	cd build/release && \
	cmake -G "Ninja" -DFORCE_COLORED_OUTPUT=1        -DENABLE_EXTENSION_AUTOLOADING= -DENABLE_EXTENSION_AUTOINSTALL= -DLOCAL_EXTENSION_REPO=""  -DOVERRIDE_GIT_DESCRIBE=""  -DCMAKE_BUILD_TYPE=Release ../.. && \
	cmake --build . --config Release
-- Found Python3: /usr/bin/python3 (found version "3.9.6") found components: Interpreter
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)")
CMake Error at CMakeLists.txt:314 (message):
  Computed GIT_DESCRIBE 'list-0-g6b0889c968' is not in the expected form
  'vX.Y.Z-N-gGITHASH123'.  Consider providing OVERRIDE_GIT_DESCRIBE
  explicitly to CMake
```

### To Reproduce

```bash
git clone https://github.com/duckdb/duckdb.git
brew install cmake ninja
GEN=ninja make
```

Above steps are executed on a MacOS and the target branch is master

### OS:

x86

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Eric 

### Affiliation:

Tencent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
You might want to check your environment variables, it sounds like `OVERRIDE_GIT_DESCRIBE` is set

**Comment by carlopi** [comment]
DuckDB builds are tagged with the version of the library, and that version depends either on providing it explicitly OR having `git` compute it.

Git works most of the times, but if that's not the case, you can provide like `OVERRIDE_GIT_DESCRIBE=v1.0.0-2216` or `OVERRIDE_GIT_DESCRIBE=v1.0.0-2216-g5be7060722`

Locally on current main I have:
```
% git describe --tags
v1.0.0-2216-g5be7060722
```
or, for the commit you are on:
```
% git describe --tags 6b0889c968
v1.0.0-2218-g6b0889c968
```
Those can also be computed querying github API on the duckdb/duckdb repository on a given commit.

**Comment by szarnyasg** [comment]
@qubin-ben did you create a full clone of the repository?
Note that the name of the default branch was changed last august from `master` to `main`, so if your branch is called `master`, you have an outdated version.

**Comment by qubin-ben** [comment]
> `n`, so if your branch is call

Actually I encountered the issue in main branch, the subject is NOT accurate when mentioning master.  
![image](https://github.com/duckdb/duckdb/assets/7158137/06ce3ece-dd31-4dd6-a757-fc24a0885c4d)

**Comment by qubin-ben** [comment]
> Tagging as needs documentation since I am not sure if this is properly explained / should be expanded on.
> 
> But I think this should solve the issue, could you confirm @qubin-ben ?
> 
> EDIT: this is documented at https://duckdb.org/docs/dev/building/build_configuration#overriding-git-hash-and-version

Yeap, the error could be fixed when I explicitly set OVERRIDE_GIT_DESCRIBE

 OVERRIDE_GIT_DESCRIBE=v1.0.0 GEN=ninja make

Thank you for your help @carlopi !

**Comment by carlopi** [comment]
I think than this can be closed, thanks
