### ISSUE TITLE
INFORMATION_SCHEMA.KEY_COLUMN_USAGE only lists first column of composite keys

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#12867]
### What happens?

The `INFORMATION_SCHEMA.KEY_COLUMN_USAGE` view doesn't list all columns of composite keys

### To Reproduce

```sql
CREATE TABLE a (a1 int, a2 int, PRIMARY KEY (a1, a2));
CREATE TABLE b (a1 int, a2 int, FOREIGN KEY (a1, a2) REFERENCES a);

SELECT * FROM information_schema.key_column_usage;
```

This only lists `a1` for each table, not both columns:

```
|constraint_catalog|constraint_schema|constraint_name|table_catalog|table_schema|table_name|column_name|ordinal_position|position_in_unique_constraint|
|------------------|-----------------|---------------|-------------|------------|----------|-----------|----------------|-----------------------------|
|duckdb-dummy      |main             |b_a1_fkey      |duckdb-dummy |main        |b         |a1         |1               |1                            |
|duckdb-dummy      |main             |a_a1_pkey      |duckdb-dummy |main        |a         |a1         |1               |                             |
```

As a workaround, at least for the primary keys, this query could be used:

```sql
SELECT constraint_column_names FROM duckdb_constraints();
```

But since the `INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME` is just a made up identifier that doesn't really exist in the catalog, it's not possible to formally correlate `DUCKDB_CONSTRAINTS()` results with `INFORMATION_SCHEMA.KEY_COLUMN_USAGE` results (or also `INFORMATION_SCHEMA.TABLE_CONSTRAINTS`), except if the constraint is the only one of its type on a given table (e.g. the primary key).

### OS:

Microsoft Windows [Version 10.0.22631.3737]

### DuckDB Version:

1.0.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks @lukaseder for another round of high-quality and easy-to-reproduce issues! We'll take a look.
