### ISSUE TITLE
failure tolerance for parquet schema mismatch

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#1286]
In case of querying globbed Parquet files with different types - something we all hope to avoid it happens to the best of us..

1. In general, there are some types that should be easy to string together (like integers ... bigint vs int vs mediumint etc)

2. When a column type mismatches and cannot be resolved, but is not used in a query, this should be acceptable. For example if the column A is a string in block 1 and A is a integer in block 2.... and the query only involves columns B and C, I see no reason the query should fail.

**Comment by hannes** [comment]
See #2877
