### ISSUE TITLE
Equi Height doesn't work for beers dataset

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#12873]
### What happens?

```
D select * from histogram('beers.csv', abv, technique := 'equi-height');
┌────────────────────┬────────┬──────────────────────────────────────────────────────────────────────────────────┐
│        bin         │ count  │                                       bar                                        │
│      varchar       │ uint64 │                                     varchar                                      │
├────────────────────┼────────┼──────────────────────────────────────────────────────────────────────────────────┤
│ x <= 0.046         │    137 │ ████████████████████████████████████████████████████████▏                        │
│ 0.046 < x <= 0.05  │    195 │ ████████████████████████████████████████████████████████████████████████████████ │
│ 0.05 < x <= 0.051  │     34 │ █████████████▉                                                                   │
│ 0.051 < x <= 0.054 │    125 │ ███████████████████████████████████████████████████▎                             │
│ 0.054 < x <= 0.057 │    138 │ ████████████████████████████████████████████████████████▌                        │
│ 0.057 < x <= 0.06  │    115 │ ███████████████████████████████████████████████▏                                 │
│ 0.06 < x <= 0.065  │    115 │ ███████████████████████████████████████████████▏                                 │
│ 0.065 < x <= 0.07  │    124 │ ██████████████████████████████████████████████████▊                              │
│ 0.07 < x <= 0.08   │    120 │ █████████████████████████████████████████████████▏                               │
│ 0.08 < x <= 0.125  │    100 │ █████████████████████████████████████████                                        │
├────────────────────┴────────┴──────────────────────────────────────────────────────────────────────────────────┤
│ 10 rows                                                                                              3 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

I would expect the counts to be the same or similar. 

### To Reproduce

Running the above query in DuckDB over https://github.com/uwdata/arquero/blob/main/test/format/data/beers.csv.

I was testing https://github.com/duckdb/duckdb/pull/12590. 

### OS:

macOS

### DuckDB Version:

v1.0.1-dev2218 6b0889c968

### DuckDB Client:

CLI

### Full Name:

Dominik Moritz

### Affiliation:

CMU

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting!

The bucket boundaries for `equi-height` are computed with quantiles. When there are many duplicate values (as is the case in this data set) - the boundaries can deviate from the expected equi-height. The deviation here comes from selecting  `0.05` as a boundary for the second bucket while there are `97` rows (~8% of the dataset) that has the value `0.05`. 

I'm not sure if there is a great way of dealing with this in these edge cases. Selecting `0.049` would lead to more balanced (but still unbalanced) boundaries but knowing that without e.g. doing a full sort of the column does not seem too easy.

**Comment by domoritz** [comment]
I see. An easier approach might be to get the overall count and then to just grab n/bins consecutive values into each bin. This might even be faster.

**Comment by Mytherin** [comment]
That sounds to me like it is identical to the quantile approach, unless I'm missing something?

In the example data set here there are 1200 values, trying to partition that into 120 values each bin, you will reach a point at `0.05` where your current bin holds 98 values, and you can either include `0.05` (overshooting to 195 values) or exclude `0.05` (undershooting at 98). 

With a quantile you end up including it and overshooting (since the quantile at `20%` is `0.05`). I agree that in this scenario undershooting is slightly better, but I'm not sure this particular edge case is worth implementing a different algorithm.

**Comment by domoritz** [comment]
I see. Since we want the boundary values, it makes sense that the algorithm doesn't work well for the edge case where there are a ton on points with the same value on a quantile boundary.
