### ISSUE TITLE
java-jdbc libstdc++.so.6 version GLIBCXX_3.4.22 NOT FOUND

### ISSUE THREAD

**Issue by rapidark** [duckdb/duckdb#12876]
### What happens?

duckdb 1.0 version , when use java-jdbc start duckdb, cause libstdc++.so.6 version GLIBCXX_3.4.22 NOT FOUND exception,
my linux is ubuntu 16.04 and the os can not upgrade glibcxx in some reason, could duckdb lowdown the glibcxx to 3.4.21 that ubuntu 16.04 default supported

### To Reproduce

when use java-jdbc start duckdb

### OS:

ubuntu 16.04

### DuckDB Version:

1.0

### DuckDB Client:

java-jdbc

### Full Name:

Rapdiark

### Affiliation:

Oracle

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
Hi @rapidark, our [community support](https://duckdblabs.com/news/2023/10/02/support-policy#platforms) only covers recent Ubuntu LTS releases. Ubuntu 16.04 is quite outdated at this point, therefore, it is very unlikely that we'll downgrade DuckDB's glibc requirement to support it. DuckDB Labs may provide builds for older versions via [custom support](https://duckdblabs.com/contact/) – please reach out if you're interested.
