### ISSUE TITLE
Out of bound bins create weird bin label

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#12898]
### What happens?

Maybe this is the extra bin for everything beyond the last bin (something like infinity) but it's a bit surprising nonetheless. 

Maybe I am not reading the semantics correctly but I feel it could make sense to get n+1 bins for n thresholds where the first bin holds everything below the first threshold and the last holds everything above. 

```sql
CREATE TABLE obs(n BIGINT);
INSERT INTO obs VALUES (0), (5), (7), (12), (20), (23), (24), (25), (26), (28), (31), (34), (36), (41), (47);
SELECT histogram(n, [10, 20, 30, 40]) FROM obs;
```
```text
┌─────────────────────────────────────────────────┐
│  histogram(n, main.list_value(10, 20, 30, 40))  │
│              map(bigint, ubigint)               │
├─────────────────────────────────────────────────┤
│ {10=3, 20=2, 30=5, 40=3, 9223372036854775807=2} │
└─────────────────────────────────────────────────┘
```

### To Reproduce

Not sure what the 

### OS:

macOS

### DuckDB Version:

v1.0.1-dev2315 b760a3f8c0

### DuckDB Client:

CLI

### Full Name:

Dominik Moritz

### Affiliation:

CMU

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting!

> Maybe this is the extra bin for everything beyond the last bin (something like infinity) but it's a bit surprising nonetheless.

Indeed this is intentional - but since an `int64` does not have an `infinity` value the highest value in the class is used instead (`2^63 - 1`). For doubles infinity is used, e.g.:


```sql
D SELECT histogram(n::double, [10, 20, 30, 40]) AS hist FROM obs;
┌─────────────────────────────────────────┐
│                  hist                   │
│          map(double, ubigint)           │
├─────────────────────────────────────────┤
│ {10.0=3, 20.0=2, 30.0=5, 40.0=3, inf=2} │
└─────────────────────────────────────────┘
```

The `is_histogram_other_bin` can be used to figure out if a bin is the infinity bin.

**Comment by domoritz** [comment]
I see. I have to process that the bins are defined as x <= bins[0], bins[0] < x <= bins[1], ..., bins[n-1] < x <= bins[n], and an extra bin for x > bins[n]. I guess it works fine if you can ensure that your data is in a particular range (max being <= bins[n]). 

Either way, not a bug.
