### ISSUE TITLE
CREATE TABLE: inconsistent quote handling with enum column?

### ISSUE THREAD

**Issue by derhuerst** [duckdb/duckdb#12901]
### What happens?

When using an `ENUM` column in a `CREATE TABLE` statement, it behaves weird. I'd expect the quotes to be completely optional as long as the schema/table/type identifiers don't contain special characters.

### To Reproduce

```sql
-- works
CREATE SCHEMA "foo";
CREATE TYPE "foo.bar" AS ENUM ('a', 'b');
CREATE TABLE foo.baz (
	bar_col "foo.bar" NOT NULL
);
```

```sql
-- does not work
CREATE SCHEMA "foo";
CREATE TYPE foo.bar AS ENUM ('a', 'b');
CREATE TABLE foo.baz (
	bar_col "foo.bar" NOT NULL
);
```

```sql
-- does not work either
CREATE SCHEMA "foo";
CREATE TYPE "foo.bar" AS ENUM ('a', 'b');
CREATE TABLE foo.baz (
	bar_col foo.bar NOT NULL
);
```

```sql
-- does not work either
CREATE SCHEMA "foo";
CREATE TYPE foo.bar AS ENUM ('a', 'b');
CREATE TABLE foo.baz (
	bar_col foo.bar NOT NULL
);
```

```sql
-- does not work either
CREATE SCHEMA "foo";
CREATE TYPE "foo".bar AS ENUM ('a', 'b');
CREATE TABLE foo.baz (
	bar_col "foo".bar NOT NULL
);
```

### OS:

macOS Sonoma 14.5

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

DuckDB CLI (`duckdb`)

### Full Name:

Jannis

### Affiliation:

freelancer

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by derhuerst** [comment]
It seems to be the quote handling in general?

```sql
-- works
CREATE TABLE "main.stops" (
	stop_id TEXT NOT NULL,
	parent_station TEXT
);

SELECT
	stops.stop_id,
	stations.stop_id AS station_id
FROM (
	"main.stops" stops
	LEFT JOIN "main.stops" stations ON stops.parent_station = stations.stop_id
);
```

```sql
-- does not work
CREATE TABLE "main.stops" (
	stop_id TEXT NOT NULL,
	parent_station TEXT
);

SELECT
	stops.stop_id,
	stations.stop_id AS station_id
FROM (
	"main.stops"
	LEFT JOIN "main.stops" stations ON stops.parent_station = stations.stop_id
);
```

**Comment by Mytherin** [comment]
Thanks for reporting! There's a fix up for the enum issue here - https://github.com/duckdb/duckdb/pull/13106

> It seems to be the quote handling in general?

The example that you link there behaves correctly - you are using "stops" in the `ON` clause instead of "main.stops` as you are using in the `FROM` clause, so an error is thrown.
