### ISSUE TITLE
`COUNT(*)` on wildcard Parquet reads all columns?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#12903]
### What happens?

I've observed a difference in the `EXPLAIN` output between reading a couple of Parquet files with a wildcard and with `UNION ALL` . Is the wildcard read really reading all columns, or is this a limitation of the `EXPLAIN` output?

I want to track down a performance problem in duckplyr when reading in multiple Parquet files, and I would like to understand if there is a difference between wildcard reads and single file reads in terms of pushdown.

### To Reproduce

```sql
COPY (SELECT 1 AS a, 1 AS b) TO 'test-1.parquet' (FORMAT 'parquet');
COPY (SELECT 2 AS a, 1 AS b) TO 'test-2.parquet' (FORMAT 'parquet');

EXPLAIN SELECT COUNT(*) FROM 'test-*.parquet';
EXPLAIN SELECT COUNT(*) FROM (SELECT * FROM 'test-1.parquet' UNION ALL SELECT * FROM 'test-2.parquet');
```

Output:

```
EXPLAIN SELECT COUNT(*) FROM 'test-*.parquet';

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│    UNGROUPED_AGGREGATE    │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        count_star()       │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│       PARQUET_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 2           │
└───────────────────────────┘

EXPLAIN SELECT COUNT(*) FROM (SELECT * FROM 'test-1.parquet' UNION ALL SELECT * FROM 'test-2.parquet');

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│    UNGROUPED_AGGREGATE    │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        count_star()       │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           UNION           ├──────────────┐
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│       PARQUET_SCAN        ││       PARQUET_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             ││             a             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 1           ││           EC: 1           │
└───────────────────────────┘└───────────────────────────┘
```

### OS:

macOS

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
It does not read all columns - it reads a single column (this just so happens to only have a single column in the file).

**Comment by krlmlr** [comment]
Thanks for the confirmation. I don't understand "this just so happens to only have a single column in the file".

I'm curious where the difference in the output comes from -- it's clear in the second case that only one column is read, but not in the first case.
