### ISSUE TITLE
[C-API] `duckdb_data_chunk_reset` should mention stale pointers

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#12910]
### What happens?

Calling `duckdb_data_chunk_reset` could turn these into dangling pointers:
- `duckdb_vector_get_validity`
- `duckdb_vector_get_data`

After calling `duckdb_data_chunk_reset` these methods should be called again and the results from calls before `duckdb_data_chunk_reset` should be considered stale and outdated.

The inline docs in the `duckdb.h` header should mention this.

**Comment by Giorgi** [comment]
It should be documented for `duckdb_list_vector_set_size` too, possibly also for `duckdb_list_vector_reserve`, not sure if it's needed for that.
