### ISSUE TITLE
Inconsistent behavior when inserting date/time data from CSV into timestamptz column

### ISSUE THREAD

**Issue by arifsaslam** [duckdb/duckdb#12926]
### What happens?

When inserting data from a CSV file into a table with a `timestamptz` column, the behavior is inconsistent. Direct insertion from the CSV results in NULL values, while inserting through an intermediate table works correctly.
Use the following csv file:
[abc.csv](https://github.com/user-attachments/files/16157070/abc.csv)

### To Reproduce

```sql
-- This works correctly
SELECT * FROM 'abc.csv';

-- This results in NULL values for the timestamptz column
CREATE TABLE test (column0 timestamptz, column1 numeric, column2 numeric, column3 numeric);
INSERT INTO test SELECT * FROM 'abc.csv';

-- This works correctly
CREATE TABLE test2 AS SELECT * FROM 'abc.csv';
INSERT INTO test SELECT * FROM test2;
```
### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

1.0

### DuckDB Client:

python

### Full Name:

Arif Aslam

### Affiliation:

Mammoth Analytics Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @arifsaslam, thanks for opening this issue. The second approach, i.e. inserting through the intermediate table `test2` uses the CSV reader's auto-inferencing mechanism. This results in `column0` being a `DATE` field instead of a `TIMESTAMPTZ` column, which explains why the results are different.

```sql
describe test2;
```

```
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ column0     │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ column1     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ column2     │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ column3     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

**Comment by arifsaslam** [comment]
@szarnyasg I appreciate your explanation, but I'm still confused. The CSV data is inferred as DATE both when read directly and when creating the intermediate table. So why does direct insertion into a `timestamptz` column fail?
```sql
 describe select * from 'abc.csv';
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ column0     │ DATE        │ YES     │         │         │         │
│ column1     │ BIGINT      │ YES     │         │         │         │
│ column2     │ DOUBLE      │ YES     │         │         │         │
│ column3     │ BIGINT      │ YES     │         │         │         │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

```

**Comment by szarnyasg** [comment]
That's a good point, probably some automatic casts happen differently. I passed it on to the team to take a look.
