### ISSUE TITLE
ParserException: Parser Error: syntax error at or near "COPY" when using WITH clause

### ISSUE THREAD

**Issue by mfouesneau** [duckdb/duckdb#12925]
### What happens?

It seems that the COPY statement does not accept the WITH clause.

### To Reproduce

The following works:
```sql
COPY ( select 42 as x ) TO 'file.parquet';
COPY ( select * from 'file.parquet' limit 10 ) TO 'test.parquet' (FORMAT 'parquet');
```
But any `WITH` in the query leads to a `ParserException`
```
with inputdata as ( select * from 'file.parquet' limit 10 )
COPY (select * from inputdata) TO 'test.parquet' (FORMAT 'parquet');
```
(even if the with does not relate to COPY statement)

### OS:

aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

python

### Full Name:

Morgan Fouesneau

### Affiliation:

Max-Planck Institute

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by mfouesneau** [comment]
I am not sure, but it may be related to the limitations of COPY?
https://duckdb.org/docs/sql/statements/copy.html#limitations

If I create a table (even if in-memory) instead of `WITH` it works

```
with inputdata as ( select * from 'file.parquet' limit 10 )
COPY (select * from inputdata) TO 'test.parquet' (FORMAT 'parquet');
```
becomes
```
DROP TABLE IF EXISTS inputdata;
CREATE TABLE temporary_table as ( select * from 'file.parquet' limit 10 );
COPY (select * from temporary_table) TO 'test.parquet' (FORMAT 'parquet');
```

The latter seems to be working as expected, but I am not sure of the memory overhead with large datasets

**Comment by szarnyasg** [comment]
Hi @mfouesneau, this is an expected behavior – `COPY` statements cannot be preceded by CTEs. Instead, you can use `with` inside the `COPY` statement as follows:

```sql
COPY (
    with inputdata as ( select * from 'file.parquet' limit 10 ) select * from inputdata
)
TO 'test.parquet' (FORMAT 'parquet');
```
