### ISSUE TITLE
Casting JSON to a struct turns `null` into the string null

### ISSUE THREAD

**Issue by GrantJamesPowell** [duckdb/duckdb#12939]
### What happens?

Casting from a json string (varchar) to a struct succeeds, but will convert `null` in the json to the string `'null'` in the resulting struct. It seems like it should convert to SQL `null` which is not the string `'null'`? This also means I can't cast into other nullable data types

### To Reproduce

```
D select version();
┌───────────┐
│ version() │
│  varchar  │
├───────────┤
│ v1.0.0    │
└───────────┘
D select (cast('{"bar": null}' as struct("bar" text))).bar;
┌────────────────────────────────────────────────────┐
│ (CAST('{"bar": null}' AS STRUCT(bar VARCHAR))).bar │
│                      varchar                       │
├────────────────────────────────────────────────────┤
│ null                                               │
└────────────────────────────────────────────────────┘
D select (cast('{"bar": null}' as struct("bar" int))).bar;
Conversion Error: Could not convert string 'null' to INT32
```

Weirdly enough _capital_ `NULL` seems to work, but isn't valid JSON 😢 
```
D select (cast('{"bar": NULL}' as struct("bar" int))).bar;
┌────────────────────────────────────────────────────┐
│ (CAST('{"bar": NULL}' AS STRUCT(bar INTEGER))).bar │
│                       int32                        │
├────────────────────────────────────────────────────┤
│                                                    │
└────────────────────────────────────────────────────┘
```

### OS:

Macos 12.5

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Grant Powell

### Affiliation:

cotera.co

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks for reporting this, this should indeed be fixed.

**Comment by lnkuiper** [comment]
Hi @GrantJamesPowell, thanks for the bug report! This is expected behavior.

In your query, you are casting a SQL string (`VARCHAR`) to a `STRUCT`, which will use our `VARCHAR` to `STRUCT` cast.
```sql
D select (cast('{"bar": null}' as struct("bar" text))).bar;
```
To cast from `JSON` to `STRUCT`, you will first need to cast the SQL string to `JSON` like so:
```sql
D select (cast('{"bar": null}'::json as struct("bar" text))).bar as bar;
┌─────────┐
│   bar   │
│ varchar │
├─────────┤
│         │
└─────────┘
```
This will parse and validate the SQL string, and convert it to the `JSON` type, which will indeed recognize the uppercase `NULL` as invalid JSON:
```sql
D select (cast('{"bar": NULL}'::JSON as struct("bar" int))).bar as bar;
Conversion Error: Malformed JSON at byte 8 of input: unexpected character.  Input: {"bar": NULL}
LINE 1: select (cast('{"bar": NULL}'::JSON as struct("bar" int))).bar as ba...
                                    ^
```
You have, however, uncovered and issue in our `VARCHAR` to `STRUCT` cast, which is that it reads `NULL` case sensitively.
