### ISSUE TITLE
Regression in R package after join filter pushdown

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#12947]
### What happens?

After https://github.com/duckdb/duckdb/pull/12908, tests in the R package fail with a `std::exception` .

### To Reproduce

- Find a Linux box (repro'd in Ubuntu, can't repro on macOS)
- Clone https://github.com/duckdb/duckdb-r/tree/f-joinfilterpushdown (not the main branch)
- Run `install.packages("duckdb", dependencies = TRUE)` to get the necessary dependencies
- Run `R CMD INSTALL .`
- Run `R -q -e 'testthat::test_local()'`

Symptoms: https://github.com/duckdb/duckdb-r/actions/runs/9887438002/job/27309194811#step:9:436

### OS:

Ubuntu Linux

### DuckDB Version:

https://github.com/duckdb/duckdb/pull/12908

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting!

This is somewhat expected as I had removed a work-around for the R client scans (and forgotten about it). I've added this back under the `initialize_in_main_thread` setting in https://github.com/duckdb/duckdb/pull/12990. The setting will just need to be set in the R client.

Note that this setting effectively disabled dynamic join filter pushdown. Given that we haven't had that before anyway that's not a big problem - but it means that the optimizations in the join filter pushdown PR won't apply to the R client.

Perhaps we can do something more fine-grained in the future if required.

**Comment by krlmlr** [comment]
Thanks, Mark. It's weird, applying the PR on top of #12908 fixes our checks even without the `initialize_in_main_thread` setting. Is there anything else I need to be aware of?

**Comment by krlmlr** [comment]
Corresponding PR: https://github.com/duckdb/duckdb-r/pull/198 .

**Comment by krlmlr** [comment]
Update: CI/CD fails, all well from my end 🙃
