### ISSUE TITLE
Underscore string comparison is not working as expected

### ISSUE THREAD

**Issue by lijose** [duckdb/duckdb#12951]
### What happens?

I was trying to pull some strings where '_' (underscore) is part of. 
I tried using query as mentioned below, but query was returning no records. 
I tried running similar query in Hive and it returned records.

### To Reproduce

To reproduce 
```
with src as 
(
  select 'a_bb_c' col 
  union all
  select 'a_b_c' col
  union all
  select 'a_bd_c' col
)
select *
from src 
where col like '%\_b\_%'
-- where col like '%[_]b[_]%'

```
expected output >> **a_b_c**
actual output >> No records

### OS:

Mac

### DuckDB Version:

v0.8.1

### DuckDB Client:

DBeaver

### Full Name:

Lijo

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
You're trying to escape inside a string in sql, that's not supported.
I imagine using `%_b_%` would work just fine

**Comment by Mytherin** [comment]
`LIKE` by default does not have an escape in DuckDB, meaning all characters except for `_` and `%` are literal characters. You can specify an `ESCAPE` explicitly, e.g.:

```sql
with src as 
  (
    select 'a_bb_c' col 
    union all
    select 'a_b_c' col
    union all
    select 'a_bd_c' col
  )
  select *
  from src 
  where col like '%\_b\_%' escape '\'
  ;
┌─────────┐
│   col   │
│ varchar │
├─────────┤
│ a_b_c   │
└─────────┘
```
