### ISSUE TITLE
CSV parsing gives different name format for empty vs. whitespace header

### ISSUE THREAD

**Issue by RLesser** [duckdb/duckdb#12977]
### What happens?

When parsing a CSV, a header row with an empty column will turn into `column{i}`
For instance, `a,b,c,,e` becomes `a,b,c,column3,e` 

But if the header row has a column that is just whitespace, that empty column will turn into `C{i}`
For instance, `a,b,c,  ,e` becomes `a,b,c,C3,e`

These names should probably be consistent.

Note: I'm using duckdb-wasm, but I don't believe this is a WASM specific problem. If that is the case this can be moved to that repo.

### To Reproduce

1. Create two CSVs (or just change the header in one csv) with the above differences in the first row.
2. Load both into DuckDB. I'm using the WASM bindings but I believe it still happens with other CSV parsing methods.
3. Observe the difference in column names

### OS:

macOS 

### DuckDB Version:

1.0.0

### DuckDB Client:

WASM (version 1.28.1-dev106.0)

### Full Name:

Robert Lesser

### Affiliation:

Nomic AI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by hannes** [comment]
Thanks for reporting, indeed this is not consistent and should be fixed.
