### ISSUE TITLE
Improper error message: LATERAL join cannot contain window functions

### ISSUE THREAD

**Issue by code1704** [duckdb/duckdb#12988]
### What happens?

```sql
  create table customers (name varchar, age integer, something_easy_to_type_wrong integer, city varchar);
  create table zipcodes (city varchar, zipcode varchar);
  insert into customers values ('Alice', 24, 7, 'Seattle'),
                              ('Bob', 34, 2, 'Portland'),
                              ('Charlie', 23, 3, 'Seattle'),
                              ('David', 36, 9, 'Portland'),
                              ('Sam', 35, 5, 'Seattle');

  insert into zipcodes values ('Seattle', '98101'), 
                              ('Portland', '97201');

  with cte as (
      select *,
          rank() over (order by something_easy_to_typo_wrong) as rk
      from customers
      where age <= 42
  )
  select *
  from zipcodes
  join cte
  using (city)
```
The above SQL query emits the following error message:
```
 Binder Error: LATERAL join cannot contain window functions!
```
If we switch the join order as `from cte join zipcodes` (i.e., put the subquery `cte` on the LHS of the join), a super-friendly error message is produced:
```
Binder Error: Referenced column "something_easy_to_typo_wrong" not found in FROM clause!
Candidate bindings: "customers.something_easy_to_type_wrong"
LINE 15:             rank() over (order by something_easy_to_typo_wrong) as rk
                                           ^
```
The latter is exactly what everybody wants. Super helpful (thanks to the AMAZING effort the DuckDB team has done)! For the former case, however, if there are tons of (aggregate) window expressions in the subquery, we will have a poor chance of recognizing the problem.

### To Reproduce

See the description above.

### OS:

Ubuntu 22.04.2 LTS, aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Mark

### Affiliation:

bq

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by hannes** [comment]
Thanks for reporting this, the error message there could indeed be improved.

**Comment by Mytherin** [comment]
Thanks for the report - I've pushed a fix in https://github.com/duckdb/duckdb/pull/13001
