### ISSUE TITLE
COPY misreads NEW_LINE parameter input '\r' as '\n'

### ISSUE THREAD

**Issue by bradenhenrichs** [duckdb/duckdb#13007]
### What happens?

When manually setting the NEW_LINE parameter while using COPY, DuckDB interprets '\r' as '\n'. This prevents the CSV from loading if you have values of \n in the CSV file that do not represent a new line.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/15ca50c0-21c7-4bd3-bc6c-7d7a104045dc">

### To Reproduce

```
COPY <table_name> FROM <file_name.csv> (NEW_LINE '\r');
```

### OS:

Windows

### DuckDB Version:

latest nightly  build

### DuckDB Client:

CLI

### Full Name:

Braden Henrichs

### Affiliation:

personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot easily share my data sets due to their large size

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by bradenhenrichs** [comment]
Realized this was due to an outdated version - resolved in 1.0

**Comment by bradenhenrichs** [comment]
just FYI I was able to recreate this issue in the latest nightly build

**Comment by hannes** [comment]
Thanks for filing this, I was able to reproduce it. We will have a look.

**Comment by pdet** [comment]
Could you try running with ` nullstr = '\N'` and maybe `allow_quoted_nulls = true`?

From the error message it seems that the issue is that the nullstr is not defined, and DuckDB is trying to convert "\N" to a `INT128`

**Comment by bradenhenrichs** [comment]
will try those - what's weird about the error is that "\N" is going into a column defined as string, so I took that to mean DuckDB got column processing out of order due to processing the new line.
just FYI - with the nightly build I used it worked as is

**Comment by bradenhenrichs** [comment]
@pdet that worked. hitting another error after, but that's a different story!

```
INTERNAL Error: CSV Buffer is not available to reconstruct CSV Line, please open an issue with your query and dataset.
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by pdet** [comment]
> @pdet that worked. hitting another error after, but that's a different story!
> 
> ```
> INTERNAL Error: CSV Buffer is not available to reconstruct CSV Line, please open an issue with your query and dataset.
> This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
> For more information, see https://duckdb.org/docs/dev/internal_errors
> ```

Can you share the a minimal reproducible dataset and example for this issue?

**Comment by bradenhenrichs** [comment]
I think that new error is just due to the sheer volume of files and records and has no connection to this issue. This new error occurs when attempting process about 1.5 billion records across nearly 1700 csv files. It succeeds when processing individual files, but struggles in batches of multiple files.
