### ISSUE TITLE
[Julia] Import database

### ISSUE THREAD

**Issue by whatsthecraic** [duckdb/duckdb#13006]
### What happens?

As posted on Discord, importing a database with multiple definitions does not seem to be supported within the Julia API, or is there a specific command to use ?

### To Reproduce

Step 1: create and export a database with multiple views, e.g. 
```
CREATE VIEW v1 AS (SELECT 1);
CREATE VIEW v2 AS (SELECT 2);
EXPORT DATABASE '/tmp/testdb';
```

Step 2. With the julia API, try to import it:
```
julia> DBInterface.execute(connection, "IMPORT DATABASE '/tmp/testdb'")
ERROR: Invalid Error: Cannot prepare multiple statements at once!
```

### OS:

MacOS Sonoma v14.4.1

### DuckDB Version:

1.0

### DuckDB Client:

Julia

### Full Name:

Dean De Leo

### Affiliation:

RelationalAI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
As mentioned [here](https://duckdblabs.com/news/2023/10/02/support-policy.html), the Julia client does fall under our support policy, so this issue will likely not be picked up by the team.

You're welcome to provide a pull request to fix the issue yourself however
