### ISSUE TITLE
Version 1.0.0 Can't join tables across multiple Azure Blob Containers

### ISSUE THREAD

**Issue by joshbellradix** [duckdb/duckdb#13012]
### What happens?

in version 0.10.0, i am able to join tables from multiple different azure blob storage containers. In version 1.0.0, i receive error 
'The specified container does not exist'

### To Reproduce

In version 0.10.0, i create secrets for the blob connections and join easily, this works as expected:
```
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .version
SQLite v0.10.0 20b1486d11
msvc-1937
D --Az Platform Pipelines Prod
D INSTALL httpfs;
D LOAD httpfs;
D INSTALL azure;
D LOAD azure;
D 
D CREATE SECRET IF NOT EXISTS platformpipes (
┬╖     TYPE AZURE, 
┬╖     CONNECTION_STRING 'BLOBLCREDENTIALS1',
┬╖     SCOPE 'azure://parquets'
┬╖ );
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D
D CREATE SECRET IF NOT EXISTS scraped (
┬╖     TYPE AZURE,
┬╖     CONNECTION_STRING 'BLOBLCREDENTIALS2',
┬╖     SCOPE 'azure://scraped-data'
┬╖ );
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D select p.address, c.INPUT_ADDRESS, * from 'azure://parquets/core/addresses.parquet' as c
┬╖ inner join 'azure://scraped-data/r/2024-07-01/properties.parquet' as p on p.address=c.input_address 
┬╖ ;
100% ?████████████████████████████████████████████████████████████? 
┌──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬───┬───────────┬──────────────────────┬─────────┬──────────────────────┐
│       Address        │    INPUT_ADDRESS     │          ID          │    INPUT_ADDRESS     │ . │ YearBuild │      WebSiteUrl      │  State  │     ImportedDate     │
│       varchar        │       varchar        │       varchar        │       varchar        │   │   int32   │       varchar        │ varchar │      timestamp       │
├──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼───┼───────────┼──────────────────────┼─────────┼──────────────────────┤
│DATA APPEARS HERE!!  │
├──────────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴───┴───────────┴──────────────────────┴─────────┴──────────────────────┤
│ 32244 rows (40 shown)        
```

In version 1.0.0, same query returns error 'The specified container does not exist'

```
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D --Az Platform Pipelines Prod
D INSTALL httpfs;
D LOAD httpfs;
D INSTALL azure;
D LOAD azure;
D 
D CREATE SECRET IF NOT EXISTS platformpipes (
┬╖     TYPE AZURE, 
┬╖     CONNECTION_STRING 'BLOBLCREDENTIALS1',
┬╖     SCOPE 'azure://parquets'
┬╖ );
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D
D CREATE SECRET IF NOT EXISTS scraped (
┬╖     TYPE AZURE,
┬╖     CONNECTION_STRING 'BLOBLCREDENTIALS2',
┬╖     SCOPE 'azure://scraped-data'
┬╖ );
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D select p.address, c.INPUT_ADDRESS, * from 'azure://parquets/core/addresses.parquet' as c
┬╖ inner join 'azure://scraped-data/r/2024-07-01/properties.parquet' as p on p.address=c.input_address
┬╖ ;
IO Error: AzureBlobStorageFileSystem open file 'azure://scraped-data/r/2024-07-01/properties.parquet' failed with code'', Reason Phrase: 'The specified container does not
exist.', Message: ''
```

### OS:

Windows 11 Business Version	10.0.22631 Build 22631 x64

### DuckDB Version:

1.0.0

### DuckDB Client:

DuckDB sql

### Full Name:

Joshua Bell

### Affiliation:

Radix

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by naimsulejmani** [comment]
Yep, it happens to me also, the same issue when I switched to the latest stable release 1.0.0.

**Comment by samansmink** [comment]
Thanks for reporting! 

Could you try two things for me:

firstly confirm that the credential string itself does work in duckdb v1.0.0 with:

```SQL
CREATE SECRET IF NOT EXISTS scraped (
    TYPE AZURE,
    CONNECTION_STRING 'BLOBLCREDENTIALS2',
);
FROM 'azure://scraped-data/r/2024-07-01/properties.parquet'
```

Secondly,  after creating your secrets, could you run:
```
from duckdb_secrets()
from which_secret('azure://scraped-data', 'azure');
from which_secret('azure://parquets', 'azure');
```
and send me the output?

**Comment by naimsulejmani** [comment]
@joshbellradix has this issue been fixed, did you have a try on the new 1.1.1 version !?

**Comment by joshbellradix** [comment]
@naimsulejmani  @samansmink i tried this today on the 1.1.2 stable release and received the same error message as 1.0.0, however i learned a new thing, if i put a trailing / on SCOPE it works. . . 
**Doesn't work:**
`CREATE SECRET IF NOT EXISTS platformpipes (
    TYPE AZURE, 
    CONNECTION_STRING 'CRED',
    SCOPE 'azure://parquets'
);`

**Does work:**
`CREATE SECRET IF NOT EXISTS platformpipes (
    TYPE AZURE, 
    CONNECTION_STRING 'CRED',
    SCOPE 'azure://parquets/'
);`

so i think we are good here and probably this worked in 1.0.0 if my past self had been clever enough to try a / , closing this now

**Comment by szarnyasg** [comment]
@joshbellradix thanks for following up on this. I documented the trailing slash requirement at https://github.com/duckdb/duckdb-web/pull/3888
