### ISSUE TITLE
[CSV Sniffer] `gzip` compressed, tab delimited file throws odd error

### ISSUE THREAD

**Issue by hello-world-bfree** [duckdb/duckdb#13043]
### What happens?

When attempting to use `read_csv` to read in a gzip compressed, tab-delimited file, I get the error 

> Invalid Input Error: Error when sniffing file "/my/path/file.gzip". CSV options could not be auto-detected. Consider setting parser options manually.

This is unexpected because the file is parsed as expected (without proper column association) when any other delimiter is used. You can see that it's tab delimited, yet something about setting the delim option to `\t` breaks the ingest.

The issue appears to be with the column header.

Skipping another row and supplying my own columns works, but is undesirable.

### To Reproduce

Using the provided file, run `read_csv` without a specified delimiter or other conventional non-tab delimiter

```
from read_csv('test_apple_financial.csv.gz', compression='gzip', header=true, skip=3);
```

You'll see the columns and data, all in one column. It's possible to see the data and columns are tab-delimited.

Then run 

```
from read_csv('test_apple_financial.csv.gz', compression='gzip', header=true, skip=3, delim='\t');
```

This will prompt the error. 

The following will work but is undesirable

```
from read_csv('~/test_apple_financial.csv.gz', compression='gzip', skip=4, columns={
       'Transaction Date': 'varchar',
       'Settlement Date': 'varchar',
       'Apple Identifier': 'varchar',
       'SKU': 'varchar',
       'Title': 'varchar',
       'Developer Name': 'varchar',
       'Product Type Identifier': 'varchar',
       'Country of Sale': 'varchar',
       'Quantity': 'varchar',
       'Partner Share': 'varchar',
       'Extended Partner Share': 'varchar',
       'Partner Share Currency': 'varchar',
       'Customer Price': 'varchar',
       'Customer Currency': 'varchar',
       'Sale or Return': 'varchar',
       'Promo Code': 'varchar',
       'Order Type': 'varchar',
       'Region': 'varchar'
  });
```

[test_apple_financial.csv.gz](https://github.com/user-attachments/files/16273762/test_apple_financial.csv.gz)

### OS:

macOS arm64

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Brandon Freeman

### Affiliation:

Hallow

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks for reporting this, I'm getting the same error whether the compressed file contains tab or comma separators. In general, auto-detection is harder on compressed files but this should indeed work.
