### ISSUE TITLE
duckdb.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN14duckdb_mbedtls14MbedTlsWrapper18AESGCMStateMBEDTLSC1Ev

### ISSUE THREAD

**Issue by skinkie** [duckdb/duckdb#13060]
### What happens?

Custom compiled DuckDB python extension cannot load.

### To Reproduce

source /path/to/env/bin/activate
mkdir -p build
cd build
cmake ..
make -j10

### OS:

Linux

### DuckDB Version:

Current head

### DuckDB Client:

Python

### Full Name:

Stefan de Konink

### Affiliation:

Stichting OpenGeo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
You're building with added options

To refer to the `README.md` in `tools/pythonpkg`:
> When building DuckDB it outputs which extensions are linked into DuckDB, the python package does not deal with linked in extensions very well.
The output looks something like this:
`-- Extensions linked into DuckDB: [json, fts, tpcds, tpch, parquet, icu, httpfs]`
> 
> `httpfs` should not be in that list, among others.
Refer to `extension/extension_config_local.cmake` or the other `*.cmake` files and make sure you add DONT_LINK to the problematic extension.
`tools/pythonpkg/duckdb_extension_config.cmake` contains the default list of extensions built for the python package
Anything that is linked that is not listed there should be considered problematic.

**Comment by skinkie** [comment]
@Tishj the `BUILD_PYTHON=1 make debug` directly from the root folder worked without issue.
