### ISSUE TITLE
current_timestamp bad performance in Linux

### ISSUE THREAD

**Issue by kaiohenrique** [duckdb/duckdb#13066]
### What happens?

When running the application in Linux we have noticed a degradation when comparing with Windows version
Whe have run perf command and noticed some internal exceptions being thrown 
For some reason, when query has a current_timestamp usage we see ColumnNotFound exception in the traces and a lot of CPU is stuck in " __backtrace_symbols"

```
+   55.95%     0.00%  .NET TP Worker   libc.so.6                     [.] __backtrace_symbols
+   55.20%     0.00%  .NET TP Worker   libc.so.6                     [.] 0x00007f732676a9e0
+    6.60%     6.60%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eb43
+    4.91%     4.91%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eb5f
+    3.70%     3.70%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eafd
+    3.70%     3.70%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eb2a
+    3.63%     3.63%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eb2d
+    3.57%     3.57%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eb5a
+    3.25%     0.00%  C2 CompilerThre  [unknown]                     [.] 0x00007fdc0ba3aa33
+    3.19%     0.00%  C2 CompilerThre  [unknown]                     [.] 0x00007fdc0ba39a1e
+    2.97%     2.97%  .NET TP Worker   libc.so.6                     [.] 0x000000000014eb20
+    2.92%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::Exception::ToJSON
+    2.66%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::ExpressionBinder::QualifyColumnName
+    2.65%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::Binder::BindSelectNode
+    2.64%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::ExpressionBinder::QualifyColumnName
+    2.59%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::BinderException::ColumnNotFound
+    2.59%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::BinderException::BinderException
+    2.59%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::Exception::Exception
+    2.59%     0.00%  .NET TP Worker   libduckdb.so                  [.] duckdb::Exception::GetStackTrace
```

### To Reproduce

Execute:
SELECT current_timestamp

### OS:

x64

### DuckDB Version:

v1.0.0

### DuckDB Client:

.Net

### Full Name:

Kaio Henrique

### Affiliation:

Agile Content

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by kaiohenrique** [comment]
To workaround this issue we have created a macro with a fixed timestamp and the performance is acceptable now

**Comment by kaiohenrique** [comment]
Seems it is related to this flag 
https://github.com/duckdb/duckdb/blob/c8fa71cd5ed2546c08f1ef5f2c4b0fb1420ddaff/.github/workflows/LinuxRelease.yml#L64

https://github.com/duckdb/duckdb/blob/c8fa71cd5ed2546c08f1ef5f2c4b0fb1420ddaff/src/common/exception.cpp#L81

**Comment by kaiohenrique** [comment]
Also reproducing the ColumnNotFound when running sub-queries

min-repro:
```
create table table_base (ID INTEGER);     
create table table_relation (REF INTEGER) 
```
```sql
SELECT   ID
FROM     table_base base
WHERE    
            (SELECT COUNT(*)
                  FROM   table_relation
                  WHERE  REF = base.ID
                         ) > 0
```

**Comment by Mytherin** [comment]
Thanks for reporting! It is expected that we generate these error messages also during successful queries, when binding the inner subquery we don't know yet that `base.ID` exists and generate an error message. Only when we have bound the full query do we know whether or not this error should have been thrown.

What is not expected here is that we are generating the stack traces in release builds causing the performance degradation - this should be fixed in https://github.com/duckdb/duckdb/pull/13070.
