### ISSUE TITLE
Provide Android Packages

### ISSUE THREAD

**Issue by Grufy** [duckdb/duckdb#1307]
I try adopt duckdb into android via mavecentral,
compilation is fine but hit error on runtime

Able to provide fix in mavecentral gradle plugin?

Module gradle
dependencies {
 implementation 'org.duckdb:duckdb_jdbc:0.2.3'
}

Example java
url = "jdbc:duckdb:/sdcard/app/test.db";
(DuckDBConnection) DriverManager.getConnection(url);

Error
 java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/attribute/FileAttribute;
        at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:32)
        at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)
        at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)

**Comment by Mause** [comment]
It looks like the version of Java might be too old? But even if you got past that, the binary inside the jar isn't compiled for ARM so it wouldn't work anyway

**Comment by hannesmuehleisen** [comment]
In general, we should provide Android packages. It appears like different SDKs should be used to create those builds, and then there is some CPU-differences in resulting builds. If possible, integrate those binaries into the normal JDBC driver, but I have my doubts.

**Comment by omo** [comment]
Android is not compatible with Java when it comes with JNI. It has to be built using Android [NDK](https://developer.android.com/ndk/) (+SDK), and it has to come with architecture specific libraries, finally it has to be packaged as [AAR](https://developer.android.com/studio/projects/android-library#aar-contents), not JAR when it has the native dependency. It's not a simple maven fix, unfortunately.

**Comment by Mause** [comment]
I've been looking into this the last couple of days - the good thing is that the android gradle plugin has really good support for cmake native libraries. The bad side is that the copy of the java standard library that android includes is missing a number of methods that we use (a couple of methods from the jdbc interfaces, and a number from the time conversion side of things).

It still looks possible to implement, just requires some tinkering to try to keep a single codebase for both desktop and android

**Comment by bangonkali** [comment]
Being able to add/embed Duckdb on a native Android or ios application as a native plugin would be a killer feature. That would mean we can create mobile apps that has the duckdb interface in an offline environment. Ie for products requiring to run Analytics on the field away from connectivity. I would technically use it to replace sqlite. Are there any plans to support this use case in the future?

**Comment by Mause** [comment]
> Being able to add/embed Duckdb on a native Android or ios application as a native plugin would be a killer feature. That would mean we can create mobile apps that has the duckdb interface in an offline environment. Ie for products requiring to run Analytics on the field away from connectivity. I would technically use it to replace sqlite. Are there any plans to support this use case in the future? 

We already provide a Swift binding: https://duckdb.org/docs/api/swift

**Comment by kesavkolla** [comment]
Any update on this?

**Comment by redek91** [comment]
+1 would be nice to have this on android

**Comment by danbrough** [comment]
I had a tinker and it builds fine on android if you disable all the extensions.
See: build.sh on [https://github.com/danbrough/duckdb](https://github.com/danbrough/duckdb).
Plenty of linkage errors if you have `BUILD_ICU=1` for example.



```
In file included from /home/dan/workspace/duckdb/duckdb/build/release_android34_x86_64/extension/icu/third_party/icu/i18n/ub_duckdb_icu_i18n.cpp:>
/home/dan/workspace/duckdb/duckdb/extension/icu/third_party/icu/i18n/plurrule.cpp:1665:24: warning: implicit conversion from 'int64_t' (aka 'long>
          if (scaled > U_INT64_MAX) {
                     ~ ^~~~~~~~~~~
/home/dan/workspace/duckdb/duckdb/extension/icu/third_party/icu/common/unicode/umachine.h:248:33: note: expanded from macro 'U_INT64_MAX'
#     define U_INT64_MAX       ((int64_t)(INT64_C(9223372036854775807)))
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[269/278] : && /usr/bin/cmake -E rm -f extension/icu/libicu_extension.a && /mnt/files/sdk/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linu>
[270/278] : && /mnt/files/sdk/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android34 -->
FAILED: extension/icu/icu.duckdb_extension
: && /mnt/files/sdk/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android34 --sysroot=/m>
ld.lld: error: undefined symbol: duckdb::Timestamp::Convert(duckdb::timestamp_t, duckdb::date_t&, duckdb::dtime_t&)
>>> referenced by icu-dateadd.cpp:78 (/home/dan/workspace/duckdb/duckdb/extension/icu/icu-dateadd.cpp:78)
```

**Comment by Mause** [comment]
> I had a tinker and it builds fine on android if you disable all the extensions. See: build_android.sh on https://github.com/danbrough/duckdb. Plenty of linkage errors if you have `BUILD_ICU=1` for example.
> 
> ```
> In file included from /home/dan/workspace/duckdb/duckdb/build/release_android34_x86_64/extension/icu/third_party/icu/i18n/ub_duckdb_icu_i18n.cpp:>
> /home/dan/workspace/duckdb/duckdb/extension/icu/third_party/icu/i18n/plurrule.cpp:1665:24: warning: implicit conversion from 'int64_t' (aka 'long>
>           if (scaled > U_INT64_MAX) {
>                      ~ ^~~~~~~~~~~
> /home/dan/workspace/duckdb/duckdb/extension/icu/third_party/icu/common/unicode/umachine.h:248:33: note: expanded from macro 'U_INT64_MAX'
> #     define U_INT64_MAX       ((int64_t)(INT64_C(9223372036854775807)))
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 warning generated.
> [269/278] : && /usr/bin/cmake -E rm -f extension/icu/libicu_extension.a && /mnt/files/sdk/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linu>
> [270/278] : && /mnt/files/sdk/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android34 -->
> FAILED: extension/icu/icu.duckdb_extension
> : && /mnt/files/sdk/android/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android34 --sysroot=/m>
> ld.lld: error: undefined symbol: duckdb::Timestamp::Convert(duckdb::timestamp_t, duckdb::date_t&, duckdb::dtime_t&)
> >>> referenced by icu-dateadd.cpp:78 (/home/dan/workspace/duckdb/duckdb/extension/icu/icu-dateadd.cpp:78)
> ```

We actually added offical android binaries last week: https://github.com/duckdb/duckdb/pull/12550

**Comment by danbrough** [comment]
Thanks for that. I'm not familiar with github "workflows" but got enough special sauce from those commits to fix my issues.
This worked for building duckdb for android with the icu,jemalloc,parquet and json extensions:
```bash

[ -d android-ndk ] && ANDROID_NDK="$PWD/android-ndk"

if [ -z "$ANDROID_NDK" ]; then
  URL=https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
  echo ANDROID_NDK not set .. downloading $URL
  wget $URL && \
  unzip android-ndk-r26d-linux.zip && \
  mv android-ndk-r26d-linux android-ndk
fi

#ANDROID_ABI=arm64-v8a //or whatever
ANDROID_ABI=x86_64
ANDROID_PLATFORM=21
DUCKDB_EXTENSIONS="icu;parquet;json;jemalloc"

PLATFORM_NAME="android_$ANDROID_ABI"
BUILDDIR=./build/$PLATFORM_NAME
mkdir -p $BUILDDIR && \
cd $BUILDDIR && \
cmake -G "Ninja" -DEXTENSION_STATIC_BUILD=1 \
-DDUCKDB_EXTRA_LINK_FLAGS="-llog" \
-DBUILD_EXTENSIONS=$DUCKDB_EXTENSIONS \
-DENABLE_EXTENSION_AUTOLOADING=1 -DENABLE_EXTENSION_AUTOINSTALL=1 \
-DCMAKE_VERBOSE_MAKEFILE=on \
-DANDROID_PLATFORM=$ANDROID_PLATFORM \
-DLOCAL_EXTENSION_REPO=""  -DOVERRIDE_GIT_DESCRIBE="" \
-DDUCKDB_EXPLICIT_PLATFORM=$PLATFORM_NAME -DBUILD_UNITTESTS=0 -DBUILD_SHELL=1 \
-DANDROID_ABI=$ANDROID_ABI -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release ../.. && \
cmake --build . --config Release

```
