### ISSUE TITLE
Avoid inconsistent state when writing same persistent from multiple threads

### ISSUE THREAD

**Issue by samansmink** [duckdb/duckdb#13077]
### What happens?

creating persistent secrets using `LocalFileSecretStorage::WriteSecret` can result in secrets ending up in an inconsistent state. 

The solution is to do a write to tmp file, then move the tmp file to the actual file once written, similar to what we do in `ExtensionHelper::InstallExtensionInternal`

### OS:

All

### DuckDB Version:

v1.0.0

### DuckDB Client:

All

### Full Name:

Sam Ansmink

### Affiliation:

DuckDB Labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by devanbenz** [comment]
@samansmink Can I take on this issue if it's not currently being worked on?

**Comment by samansmink** [comment]
Yea of course! Happy to review your PR. Please ping me know if anything is unclear.

**Comment by devanbenz** [comment]
> Yea of course! Happy to review your PR. Please ping me know if anything is unclear.

Sounds good! Is there a place where duckdb development discussion takes place? I'm a bit newer to both C++ and systems development as I'm currently attempting to transition out of web dev to this niche of development :D so I def may have some questions.

**Comment by devanbenz** [comment]
Seeing a test failure on my branch -- but this also appears to be happening on main as well.

```
Filters: test/sql/secrets/create_secret_persistence.test
[0/1] (0%): test/sql/secrets/create_secret_persistence.test                     ================================================================================
Query unexpectedly failed (test/sql/secrets/create_secret_persistence.test:52)
================================================================================
SELECT name, scope FROM duckdb_secrets();
================================================================================
Actual result:
Serialization Error: Failed to deserialize secret 'my_tmp_secret_3' from 'duckdb_unittest_tempdir/94638/create_secret_persistence/my_tmp_secret_3.duckdb_secret': file appears empty! Please remove the file, restart and try again


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/sql/secrets/create_secret_persistence.test
-------------------------------------------------------------------------------
/Users/devan/Documents/OSS/duckdb/test/sqlite/test_sqllogictest.cpp:210
...............................................................................

test/sql/secrets/create_secret_persistence.test:52: FAILED:
explicitly with message:
  0

[1/1] (100%): test/sql/secrets/create_secret_persistence.test
===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 15 | 14 passed | 1 failed
```

When running 
`./build/release/test/unittest test/sql/secrets/create_secret_persistence.test`

Thought it was my changes in the PR but appears to happen on main. 
I could attempt to put in a fix for this as well?

**Comment by samansmink** [comment]
@devanbenz I can't reproduce that on main, nor do i see it in CI, are you sure thats not caused by your changes? it looks very much like it has to do with the change :)

**Comment by devanbenz** [comment]
> @devanbenz I can't reproduce that on main, nor do i see it in CI, are you sure thats not caused by your changes? it looks very much like it has to do with the change :)

Hm interesting, maybe it has to do with my already existing persistent secrets? I'll take a more in depth look later today 🙃

**Comment by devanbenz** [comment]
@samansmink looks like this is merged in, how do you folks generally go about closing issues?

**Comment by samansmink** [comment]
@devanbenz oops I missed this one, yea this can be closed!
