### ISSUE TITLE
Wrapping DISTINCT with UNNEST eliminates DISTINCT's effect

### ISSUE THREAD

**Issue by keremulutas** [duckdb/duckdb#13080]
### What happens?

For demonstration, consider the following table:

`select * from sample;`
| name | value | description |
|------|------:|-------------|
| a    | 1     | d1          |
| b    | 2     | d2          |
| b    | 2     | d3          |
| c    | 4     | d4          |
| c    | 4     | d5          |

With the following query I can get distinct name and value combinations:

`SELECT DISTINCT("name", "value") FROM sample;`
| main.row("name", "value") |
|---------------------------|
| (a, 1)                    |
| (c, 4)                    |
| (b, 2)                    |

The result has 1 column which is of struct type. When I try to unnest this struct, results are not distinct any more:

`SELECT UNNEST(DISTINCT("name", "value")) FROM sample;`
| element1 | element2 |
|----------|---------:|
| a        | 1        |
| b        | 2        |
| b        | 2        |
| c        | 4        |
| c        | 4        |

Basically I would expect distinct `name` and `value` for this query:

`SELECT TODAY() AS create_date, UNNEST(DISTINCT("name", "value")) FROM sample;`
| create_date | element1 | element2 |
|-------------|----------|---------:|
| 2024-07-19  | a        | 1        |
| 2024-07-19  | b        | 2        |
| 2024-07-19  | b        | 2        |
| 2024-07-19  | c        | 4        |
| 2024-07-19  | c        | 4        |

### To Reproduce

```sql
CREATE TABLE sample(name STRING, value INT, description STRING);

INSERT INTO sample VALUES ('a', 1, 'd1'), ('b', 2, 'd2'), ('b', 2, 'd3'), ('c', 4, 'd4'), ('c', 4, 'd5');

-- below query returns distinct rows
SELECT DISTINCT("name", "value") FROM sample;

-- below query returns not distinct rows
SELECT UNNEST(DISTINCT("name", "value")) FROM sample;

-- below query also returns not distinct rows
SELECT TODAY() AS create_date, UNNEST(DISTINCT("name", "value")) FROM sample;
```
### OS:

MacOS 13.5.1

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

CLI

### Full Name:

Kerem Ulutaş

### Affiliation:

Oredata Yazılım Limited Şirketi

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks for reporting, this does not look right. We will have a look.

**Comment by soerenwolfers** [comment]
Btw, to get what you want you should use `DISTINCT ON` https://duckdb.org/docs/sql/query_syntax/select.html#distinct-on-clause
