### ISSUE TITLE
regexp_matches() does not recognise "(?!"

### ISSUE THREAD

**Issue by dforsber** [duckdb/duckdb#1310]
We have this kind of regular expression, which works e.g. with NodeJS string.match(), but not with DuckDB.

```
regexp_matches(header_content_type, ' *(?![tT][eE][xX][tT]/[Hh][Tt][Mm][Ll]).*') 
```

```
invalid perl operator: (?!
```

Is this a bug or a feature? :)

**Comment by Mytherin** [comment]
Internally we use [RE2](https://github.com/google/re2) to handle regular expressions. It seems that RE2 does not support the `?!` operator. The error message "invalid perl operator" actually means that it recognizes the operator (i.e. it parses it), but it is an operator that it cannot support. The reason for that is that RE2 uses a state machine to handle regexes, which is very fast but cannot be used to implement some of the more exotic perl regex features (such as backtracking).

Perhaps as a solution we could add a fall back to std::regex when RE2 fails to compile a certain regex. It would also be worth it to see the performance difference between RE2 and std::regex; if they are in the same ballpark we might be better off replacing RE2 entirely.

**Comment by dforsber** [comment]
Yes, I think RE2 is POSIX and differs from PCRE in this manner. Some negative lookahead regexps can be converted to posivite and adding `NOT` on SQL level, so this helps us. But I think it would nicer to have PCRE supported.

**Comment by wizzard0** [comment]
> if they are in the same ballpark
they aren't :) please keep re2 at least as an option, pcre is next to unusable on large datasets

**Comment by hannesmuehleisen** [comment]
Thats exactly the reason why we went for RE2 and not PCRE

**Comment by dforsber** [comment]
Closing this issue.

**Comment by Djfe** [comment]
just a note for others stumbling across this issue:
I was able to establish what I wanted using pattern matching: "NOT SIMILAR TO". I could match all strings not ending in "xyz" this way.
not sure how this works since SIMILAR TO is supposedly using regular expressions and therefore likely RE2 but it does work. (maybe the NOT is on SQL level like descrived by @dforsber)
