### ISSUE TITLE
Scalar function without input parameters

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#13128]
### What happens?

When I register a scalar function without any parameters, the chunk that I get in the callback has size 1 no matter how many rows there are in the table.

### To Reproduce

```c
int main()
{
	duckdb_database db;
	duckdb_connection con;
	duckdb_state state;
	duckdb_result result;
	duckdb_prepared_statement preparedStatement;

	duckdb_open(NULL, &db);
	duckdb_connect(db, &con);

	std::cout << duckdb_library_version();
	state = duckdb_query(con, "CREATE TABLE big_table_1 AS SELECT (greatest(random(), 0.1) * 1000)::BIGINT i FROM range(1000) t(i);", &result);

	auto scalar_function = duckdb_create_scalar_function();
	duckdb_scalar_function_set_name(scalar_function, "my_random");

	//duckdb_scalar_function_add_parameter(scalar_function, duckdb_create_logical_type(DUCKDB_TYPE_BIGINT));

	duckdb_scalar_function_set_return_type(scalar_function, duckdb_create_logical_type(DUCKDB_TYPE_INTEGER));
	duckdb_scalar_function_set_function(scalar_function, my_random);

	state = duckdb_register_scalar_function(con, scalar_function);

	state = duckdb_query(con, "select my_random() from big_table_1;", &result);
	//state = duckdb_query(con, "select my_random(i) from big_table_1;", &result);

	duckdb_disconnect(&con);
	duckdb_close(&db);
}

void my_random(duckdb_function_info, duckdb_data_chunk input, duckdb_vector output) {
	auto size = duckdb_data_chunk_get_size(input);  --Size is 1 after this call
}
```

If you uncomment the commented lines, `size` will be 1000 in the `my_random` calllback

### OS:

Windows 11 x64

### DuckDB Version:

1.0.1-dev3196

### DuckDB Client:

C Api

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! Functions need to be labeled as volatile if you want to ensure they are re-run for every row. I've pushed a PR in #13186 that adds this setting to the C API.
