### ISSUE TITLE
python UDF: NULLs intercepted for scalars but not columnar args

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#13138]
### What happens?

According to https://duckdb.org/docs/api/python/function.html#null-handling, if you pass a NULL into a python UDF, duckdb will short-circuit and immediately resolve to NULL, and won't ever call the python with None.

This short-circuiting appears to happen when the input is a scalar, but doesn't when it is a column.

PS I think this short-circuiting (with a configurable override) is fantastic UX

### To Reproduce

```python
import duckdb
from duckdb.typing import INTEGER


def add_one(x):
    return x + 1


duckdb.create_function("add_one", add_one, [INTEGER], INTEGER, type="native")
duckdb.sql("SELECT add_one(1), add_one(NULL)").fetchall()
# [(2, None)]
duckdb.sql("SELECT add_one(x) FROM (SELECT UNNEST([1, NULL]) as x)").fetchall()
# Invalid Input Error: Python exception occurred while executing the UDF: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

### OS:

MacM1, MacOS 14.5

### DuckDB Version:

1.0.0

### DuckDB Client:

python

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Giorgi** [comment]
I was testing the very same thing today and noticed the same thing for user defined scalar functions. It works if you explicitly pass NULL as one of the arguments but doesn't if the NULL value is passed as a column value.

**Comment by Giorgi** [comment]
Repro with C API:

```c
state = duckdb_query(connection, "CREATE TABLE big_table_1 AS SELECT (greatest(random(), 0.1) * 1000)::BIGINT i FROM range(10) t(i);", &result);
state = duckdb_query(connection, "Insert into big_table_1 values (NULL);", &result);

auto function = duckdb_create_scalar_function();
duckdb_scalar_function_set_name(function, "my_null_count");

// set the variable arguments
auto any_type = duckdb_create_logical_type(DUCKDB_TYPE_ANY);
duckdb_scalar_function_set_varargs(function, any_type);
duckdb_destroy_logical_type(&any_type);

// set the return type uto bigint
auto return_type = duckdb_create_logical_type(DUCKDB_TYPE_UBIGINT);
duckdb_scalar_function_set_return_type(function, return_type);
duckdb_destroy_logical_type(&return_type);

// set up the function
duckdb_scalar_function_set_function(function, CountNULLValues);

// register and cleanup
state = duckdb_register_scalar_function(connection, function);
duckdb_destroy_scalar_function(&function);

state = duckdb_query(connection, "Select my_null_count(i, 42) from big_table_1", &result);

void CountNULLValues(duckdb_function_info, duckdb_data_chunk input, duckdb_vector output) {

	// Get the total number of rows and columns in this chunk.
	auto input_size = duckdb_data_chunk_get_size(input);
	auto column_count = duckdb_data_chunk_get_column_count(input);

	// Extract the validity masks.
	std::vector<uint64_t*> validity_masks;
	for (idx_t col_idx = 0; col_idx < column_count; col_idx++) {
		auto col = duckdb_data_chunk_get_vector(input, col_idx);
		auto validity_mask = duckdb_vector_get_validity(col);
		validity_masks.push_back(validity_mask);
	}

	// Execute the function.
	auto result_data = (uint64_t*)duckdb_vector_get_data(output);
	for (idx_t row_idx = 0; row_idx < input_size; row_idx++) {
		idx_t null_count = 0;
		for (idx_t col_idx = 0; col_idx < column_count; col_idx++) {
			if (!duckdb_validity_row_is_valid(validity_masks[col_idx], row_idx)) {
				null_count++;
			}
		}
		result_data[row_idx] = null_count;
	}
}
```

When `CountNULLValues` is executed `input_size` is 11: 10 rows in the table without NULL and one row with NULL

**Comment by Tishj** [comment]
This is expected behavior, constant NULLs can be short-circuited because we know the input is NULL, a column can contain anything, we won't know what it returns until runtime

**Comment by Giorgi** [comment]
If the custom UDF still has to handle NULL input, what's the point of short-circuiting?

**Comment by NickCrews** [comment]
I see two potential benefits of short-circuiting:
1. UX, the python programmer doesn't have to worry about this case.
2. performance, we can avoid slow python computation in some cases

If we only short-circuit on scalars, we lose the benefit of 1. We almost entirely lose the benefit of 2 as well, since I think it is reasonable to assume that calling a UDF with a column of N elements is O(N), whereas calling with a scalar is O(1), so we are only getting a performance boost in the O(1) case, which is going to only account for a tiny fraction of a queries runtime.

So, unless we can short-circuit in the columnar case too, I think we should remove the complexity and NEVER short-circuit.

The other thing confounding this is that short-circuiting a python UDF is probably much easier than short-circuiting a pyarrow UDF. But ideally these two flavors should have the same behavior. So unless we can get consistent behavior, I think we should err on the side of usability/simplicity and never short-circuit.
