### ISSUE TITLE
Python UDF with struct return type has incorrect result

### ISSUE THREAD

**Issue by jcrist** [duckdb/duckdb#13135]
### What happens?

The results of a Python UDF returning a struct seem to sometimes have the struct fields and values shuffled.

### To Reproduce

```python
import duckdb


con = duckdb.connect()


def example():
    return {
        "country": "country",
        "postal_code": "postal_code",
        "state": "state",
        "city": "city",
        "street2": "street2",
        "street1": "street1",
    }


return_type = """
STRUCT(
    "street1" STRING,
    "street2" STRING,
    "city" STRING,
    "state" STRING,
    "postal_code" STRING,
    "country" STRING
)
"""

con.create_function("example", example, return_type=return_type)


sol = example()
(res,) = con.sql("SELECT example()").fetchone()

assert res == sol
```

### OS:

Linux x86

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Jim Crist-Harif

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Wasn't really clear from your issue what the actual problem was, it initially seemed to me that the keys were just shuffled, but yea this is indeed not working correctly:
```
for item in zip(sol.items(), res.items()):
    print(item)
```

```
(('country', 'country'), ('street1', 'country'))
(('postal_code', 'postal_code'), ('street2', 'postal_code'))
(('state', 'state'), ('city', 'state'))
(('city', 'city'), ('state', 'city'))
(('street2', 'street2'), ('postal_code', 'street2'))
(('street1', 'street1'), ('country', 'street1'))
```
