### ISSUE TITLE
Sample Reservoir with Repeatable arg yield to not repeatable results

### ISSUE THREAD

**Issue by TommasoBendinelli** [duckdb/duckdb#13143]
### What happens?

I have the following complex query:
```
    SELECT 
    t2.*,
    t1.toolname,
    c.*
    FROM df_X t1
    JOIN df_X_snapshot t2 ON t1.tid = t2.tid
    JOIN df_c c ON t1.tid = c.tid
    WHERE t1.re IN ('ME-22')
    AND t2._t < '2024-03-01 00:00:00' 
    AND t2.r = false
    AND t2.b = false
    AND t2.xxx > 100
    AND t2.xxx < 10000000
    AND t2.is_last_measurement = false AND t1.hasRepair = false AND t2.snapshot_count > 5 USING SAMPLE reservoir(101000 ROWS) REPEATABLE (42);
```
  I would expect to always get the same results. However I get different results each time I am calling the function with
con.execute(con)

### To Reproduce

```
df1 = con.execute(query).pl()
df2 = con.execute(query).pl()
```
where query is the one mentioned above

df2 != df1 

### OS:

Linux T7144 5.15.0-113-generic #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### DuckDB Version:

1.0.0

### DuckDB Client:

Python 3.10.9 

### Full Name:

Tommaso Bendinelli

### Affiliation:

CSEM

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
Hey thanks for filing this but it would really help if you could make a stand-alone reproducible example.

**Comment by Tmonster** [comment]
Hi @TommasoBendinelli ,

DuckDB cannot guarantee the exact same results if multiple threads are used. There is too much randomness involved when sampling in parallel. If you really want the same result for every sample, you can call `pragma threads=1` before running your sampling query with `repeatable (42)`. This will ensure the same results between runs
Let me know if that clears things up

**Comment by Tmonster** [comment]
Hi @TommasoBendinelli this should be fixed now in latest main. One caveat though is that when you have `repeatable` in your query, the table being sampled is queried using only one thread.
