### ISSUE TITLE
Ambiguous Name not reported as an error

### ISSUE THREAD

**Issue by mzinsmeister** [duckdb/duckdb#13159]
### What happens?

When a binding with column names contains duplicate names (e.g. FROM (...) **r(a,a)**), this ambiguity is not reported as an error. Instead DuckDB just takes the first column with a given name.

### To Reproduce

```
select  a from (values (1,2)) r(a,a);
```

returns 
```
┌───────┐
│   a   │
│ int32 │
├───────┤
│     1 │
└───────┘
```

### OS:

Linux x86 (5.15.0-117-generic)

### DuckDB Version:

v1.0.0

### DuckDB Client:

CLI

### Full Name:

Michael Zinsmeister

### Affiliation:

Technical University of Munich

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by flashmouse** [comment]
duplicate column name would be renamed to {original}_1 automaticlly, so second column is  renamed to a_1;

**Comment by mzinsmeister** [comment]
Ah ok, i didn't think of that.
