### ISSUE TITLE
SSLConnection Error Connecting To Minio Over LAN

### ISSUE THREAD

**Issue by SgtGilly** [duckdb/duckdb#13164]
### What happens?

Trying to establish a connection between duckdb and a Minio instance over the local network, however I receive this error:
`IO Error: SSLConnection error for HTTP HEAD to 'https://IP:port/bucket/parquet'`

### To Reproduce

```
#  Make sure to have a Minio instance available on the local network.

import duckdb
try:
    connection = duckdb.connect()
    duckdb_py_connection = connection.execute(f"""
                            INSTALL httpfs;
                            LOAD httpfs;
                            SET s3_endpoint='IP:port';
                            SET s3_region='region';
                            SET s3_access_key_id='key_id';
                            SET s3_secret_access_key='access_key';
                            SET s3_use_ssl = true;
                            SET s3_url_style = path;""")
   
    duckdb_py_connection = connection.execute(f"SELECT * FROM read_parquet('s3a://bucket/parquet') LIMIT 100")
    
except Exception as e:
    print(f"Error querying minio: {e}")
  
   ``` 

### OS:

Ubuntu (20.04, 22.04) x86

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Seth Gillis

### Affiliation:

BAE Systems Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
I would suspect this is an SSL issue? What happens if you use I.e. curl to try to connect to the local server?

**Comment by SgtGilly** [comment]
When I try to do a curl of a json file we have in our Minio instance, I get `<Error><Code>AccessDenied</Code><Message>Access Denied.</Message>`

**Comment by prkane92** [comment]
To give a little more context, when using the duckdb python API, I can successfully specify a connection to Minio with normal http: 
```
import os
os.environ["AWS_EC2_METADATA_DISABLED"] = "true" # Necessary due to AWS IMDS requests timing out

so = {
    "aws_access_key_id": "asdfghjkl:,
    "aws_secret_access_key": "asdfghjkl",
    "endpoint_url": "http://minio.example.net",
    "use_ssl": "false",
    "verify": "false",
    'allow_http': 'true',
    "region": 'us-east-1',
    "signature_version": "s3v",
    **"AWS_EC2_METADATA_DISABLED": "true"** 
}
```

Then I'm able to connect with `quack = duckdb.arrow(DeltaTable(s3_path, storage_options=so).to_pyarrow_dataset())`

I'm trying to use the new duckdb integration with Delta Kernel, specifically the delta_scan() functionality. I've tried a handful of different option, however each seem to be giving the same DeltaKernel FFI error: 
```
import os
import duckdb
from sqlalchemy import create_engine, text

os.environ["AWS_EC2_METADATA_DISABLED"] = "true"
os.environ["AWS_ACCESS_KEY_ID"] = "asdfghjkl"
os.environ["AWS_SECRET_ACCESS_KEY"] = "asdfghjkl"
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
os.environ["AWS_S3_ENDPOINT"] = "http://minio.example.net"
os.environ["AWS_METADATA_SERVICE_TIMEOUT"] = "1"
os.environ["AWS_METADATA_SERVICE_NUM_ATTEMPTS"] = "1"
os.environ["AWS_EC2_METADATA_DISABLED"] = "true"
engine = create_engine(
    'duckdb:///:memory:',
    connect_args={
        'preload_extensions': ['https'],
        'config': {
            's3_endpoint': 'http://minio.example.net',
            's3_access_key_id': 'asdfghjkl',
            's3_secret_access_key': 'asdfghjkl',
            's3_region': 'us-east-1',
            's3_use_ssl': 'false'
        }
    }
)

with engine.connect() as conn:
    result = conn.execute(text(f"""
        SELECT * FROM delta_scan('s3a://test/path/to/data')
    """))
```

This fails with `OperationalError: (duckdb.duckdb.IOException) IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 's3a://test/path/to/data'): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic S3 error: Error after 10 retries in 13.602079555s, max_retries:10, retry_timeout:180s, source:error sending request for url (http://169.254.169.254/latest/api/token))`

Do you have any recommendations for connecting to minio using duckdb's new delta_scan functionality? I went down the road of configuring TLS with nginx terminating the endpoint, but it didn't seem to make a difference.
