### ISSUE TITLE
ERROR attaching to a duckdb database in S3 in latest release v1.0.0 1f98600

### ISSUE THREAD

**Issue by rambalachandran** [duckdb/duckdb#13166]
### What happens?

Trying to attach a duckdb file in s3 (private bucket) is still failing even for duckdb version v1.0.0 1f98600c2c. Example code provided below

### To Reproduce

```py
# %%
import duckdb

from utils import get_aws_credentials

# %%
conn = duckdb.connect(':memory:', read_only=False)
conn.execute("INSTALL aws;")
conn.execute("INSTALL httpfs;")
conn.execute("LOAD aws;")
conn.execute("LOAD httpfs;")

# %%
aws_credentials = get_aws_credentials(profile="test-mlops")

command = f"""
CREATE SECRET secret1 (
    TYPE S3,
    KEY_ID '{aws_credentials["aws_access_key_id"]}',
    SECRET '{aws_credentials["aws_secret_access_key"]}',
    REGION 'ap-southeast-2'
);
"""
conn.execute(command)

# %%

# %%
conn.execute("""ATTACH 's3:/bucket-name/folder-name/sample_db2.db' AS s3_db""")
```
The above code fails with error

```
{
	"name": "NotImplementedException",
	"message": "Not implemented Error: Cannot open an HTTP file for both reading and writing",
	"stack": "---------------------------------------------------------------------------
NotImplementedException                   Traceback (most recent call last)
File /test_duckdb.py:2
      1 # %%
----> 2 conn.execute(\"\"\"ATTACH 's3://bucket-name/folder-name/sample_db2.db' AS s3_db\"\"\")

NotImplementedException: Not implemented Error: Cannot open an HTTP file for both reading and writing"
}
```

### OS:

Ubuntu

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

Python

### Full Name:

Ram Balachandran

### Affiliation:

SpiralData

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
I think this is expected behaviour, try opening the database in read-only mode.
