### ISSUE TITLE
Parquet reader only uses performance cores, not e cores.

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb#13198]
### What happens?

I have an Intel Core i9 14900K. It has 8 performance cores and 16 'e' cores (which are slower but more energy-efficient).

When I run a count on ~200 Parquet files around ~1.1GB each I can see the P cores maxing out but the e cores are left untouched.

```sql
SELECT DISTINCT filename
FROM   READ_PARQUET('*.parquet', filename=true) a
WHERE  bbox.xmin > ?
AND    bbox.xmax < ?
AND    bbox.ymin > ?
AND    bbox.ymax < ?;
```

![Photos_s5OwT6aXdF](https://github.com/user-attachments/assets/ad7cdae4-a767-4cf6-a955-76aa2c40bfa7)

Is there some performance being left on the table here? Is this something that is within DuckDB's control?

The SSD these files are on can do ~600 MB/s but was averaging around 50-100 MB/s during the above count.

DuckDB's settings says it has 24 threads available.

```sql
D SELECT * FROM duckdb_settings() where value = '24';
```

```
┌────────────────┬─────────┬─────────────────────────────────────────────────┬────────────┬─────────┐
│      name      │  value  │                   description                   │ input_type │  scope  │
│    varchar     │ varchar │                     varchar                     │  varchar   │ varchar │
├────────────────┼─────────┼─────────────────────────────────────────────────┼────────────┼─────────┤
│ threads        │ 24      │ The number of total threads used by the system. │ BIGINT     │ GLOBAL  │
│ worker_threads │ 24      │ The number of total threads used by the system. │ BIGINT     │ GLOBAL  │
└────────────────┴─────────┴─────────────────────────────────────────────────┴────────────┴─────────┘
```

### To Reproduce

See the above. If you need the dataset it's Overture's Building Footprints from this month's release https://tech.marksblogg.com/overture-2024-revisit.html

### OS:

Ubuntu for Windows on Windows 11

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

DuckDB CLI

### Full Name:

Mark Litwintschik

### Affiliation:

Green Idea

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
It should indeed parallelise over all cores. If DuckDB is configured to use 24 threads, it will, if it is not starved for files or row groups, which does not seem to be the case here. Does other software on that hardware successfully parallelise over all cores? I could imagine OS-level restrictions being at play here.

**Comment by marklit** [comment]
Yeah, FFMPEG can stress all cores at the same time.

**Comment by szarnyasg** [comment]
@marklit thanks for opening this issue, it is an interesting one. Unfortunately I do not have access for a desktop Intel CPU, so could you please check how regular queries (without the Parquet reader) behave? Take this simple cross-join as an example:

```sql
CREATE TABLE tbl AS SELECT n FROM range(1, 5_000_000) r(n);
SELECT count(*) FROM tbl tbl1, tbl tbl2;
```

`tbl` consists of 30+ row groups, so it should give enough work for all cores. On a 12-core MacBook M2 Pro, this query takes ~10 minutes. Does this use the efficiency cores on the Intel Core i9 14900K?

**Comment by marklit** [comment]
That query is able to saturate every core.

```
C:\Users\markl\Downloads>duckdb.exe test.duckdb
```

```sql
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
D CREATE TABLE tbl AS SELECT n FROM range(1, 5_000_000) r(n);
D SELECT count(*) FROM tbl tbl1, tbl tbl2;
```

<img width="749" alt="Taskmgr_apc41JdjYe" src="https://github.com/user-attachments/assets/eb0b066f-9b05-4ab4-91df-ef196cae6b98">

**Comment by szarnyasg** [comment]
So even if the IO is sufficient, there may be many reasons why cores might not be able to be saturated (e.g., bottlenecked by memory access, etc). Since DuckDB can [saturate all cores with a different query](https://github.com/duckdb/duckdb/issues/13198#issuecomment-2268907239), I would say this is likely related to the individual query. It's also not possible for us to reproduce it without the same setup (OS/CPU), so regrettably we cannot tackle this at the moment.
