### ISSUE TITLE
DUCKDB access violation with c++ api 

### ISSUE THREAD

**Issue by ANDO-LOK** [duckdb/duckdb#13208]
### What happens?

Hello, I encountered an error with using the c++ api example code below :

DuckDB db(nullptr);
duckdb::Connection con(db);
con.Query("CREATE TABLE integers (i INTEGER, j INTEGER)");

Exception thrown at 0x00007FFED4ED7937 (duckdb.dll) in ____.exe: 0xC0000005: Access violation reading location 0x000002DEE5029000.

the third line with con query will yield the exception mentioned above .

### To Reproduce

DuckDB db(nullptr);
duckdb::Connection con(db);
con.Query("CREATE TABLE integers (i INTEGER, j INTEGER)");

### OS:

windows

### DuckDB Version:

1.0.0 stable

### DuckDB Client:

c++

### Full Name:

Anderson

### Affiliation:

n/a

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks for filing, could you please try to make a more complete reproducible example? E.g. exact code, compiler command line, linker flags, etc. Thanks!

**Comment by zhouw** [comment]
duckdb dll is compiled in release mode. If your c++ program is in debug mode, it won't work with release dll.
