### ISSUE TITLE
Trying to read an empty compressed JSON file deadlocks

### ISSUE THREAD

**Issue by njaremko** [duckdb/duckdb#13212]
### What happens?

If you have two compressed NDJSON files. One empty, and the other non-empty. Attempting to load them deadlocks duckdb.

t1.json (empty):
```
```

t2.json:
```
{"id": 1, "name": "bob"}
{"id": 2, "name": "tom"}
```

```bash
gzip t1.json
gzip t2.json
```

### To Reproduce

```
SELECT * FROM read_ndjson_auto(['t1.json.gz', 't2.json.gz'])
```

### OS:

MacOS 14.5 aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Nathan Jaremko

### Affiliation:

Census

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
Thanks for reporting, we can reproduce this.

**Comment by lnkuiper** [comment]
Closed via https://github.com/duckdb/duckdb/pull/13317
