### ISSUE TITLE
(Nightly Build) Fuzzer: DuckDB Internal Error with the ROUND and CAST function

### ISSUE THREAD

**Issue by fuboat** [duckdb/duckdb#13226]
### What happens?

**DuckDB with the nightly build** throws internal error with the ROUND and CAST function: `Information loss on integer cast: value -100.300000 outside of target range [-100.300003, -100.300003]`

### To Reproduce

```sql
SELECT ROUND(CAST(CAST('-100.3' AS DECIMAL(18, 1)) AS REAL), 1);
```

Output:
```
INTERNAL Error: Information loss on integer cast: value -100.300000 outside of target range [-100.300003, -100.300003]
```

**Note**
On stable version v1.0.0, the output is:
```
SELECT ROUND(CAST(CAST('-100.3' AS DECIMAL(18, 1)) AS REAL), 1);
┌──────────────────────────────────────────────────────────┐
│ round(CAST(CAST('-100.3' AS DECIMAL(18,1)) AS FLOAT), 1) │
│                          float                           │
├──────────────────────────────────────────────────────────┤
│                                                   -100.3 │
└──────────────────────────────────────────────────────────┘
```

### OS:

Ubuntu 20.04 x64

### DuckDB Version:

v1.0.1-dev3542 and v1.0.1-dev3550

### DuckDB Client:

python nightly build & cli source build

### Full Name:

Jingzhou Fu

### Affiliation:

Wingtecher Lab of Tsinghua University and ShuiMuYuLin Ltd.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by fuboat** [comment]
It can also be reproduced with the ROUND_EVEN function on the nightly build:
```sql
select round_even(-100.3::DECIMAL(18,1)::REAL, 1);
```

**Comment by szarnyasg** [comment]
@fuboat thanks, I could reproduce the issue. We'll take a look.
