### ISSUE TITLE
Fuzzer: DuckDB assertion failed by LIST_RESIZE with crafted arguments

### ISSUE THREAD

**Issue by fuboat** [duckdb/duckdb#13224]
### What happens?

DuckDB assertion failed by LIST_RESIZE with crafted arguments.

### To Reproduce

```sql
SELECT LIST_RESIZE([1, 2, 3], 4000999999999999999)
```

output:
```
duckdb: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
fish: './duckdb' terminated by signal SIGABRT (Abort)
```

### OS:

Ubuntu 20.04 x64

### DuckDB Version:

v1.0.0 and v1.0.1-dev3550

### DuckDB Client:

cli

### Full Name:

Jingzhou Fu

### Affiliation:

Wingtecher Lab of Tsinghua University and ShuiMuYuLin Ltd.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the reports! I've pushed fixes for most of the issues in https://github.com/duckdb/duckdb/pull/13240
