### ISSUE TITLE
Feature Request : add support for csv compressed as a zip file

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#1322]
specially in the windows world, there are a lot of source data in CSV but compressed using ZIP, it will be nice if supported natively.

**Comment by hannesmuehleisen** [comment]
ZIP files can contain complex folder structures and many files. How do you envision this should be handled? Should it be assumed all files within the ZIP follow the same schema?

**Comment by djouallah** [comment]
my use case, all the files have the same schema.

**Comment by hannes** [comment]
This is unlikely to be supported soon.
