### ISSUE TITLE
Casting Varint to Varchar prints wrong result

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#13239]
### What happens?

As discussed on Discord, casting Varint to Varchar prints wrong result

![image](https://github.com/user-attachments/assets/472bd8bb-1893-45d2-aa9b-c08887c19a6b)

### To Reproduce

```sql
Select 85070591730234614260976917445211069672::VARINT ;
```

### OS:

Windows 11 x64

### DuckDB Version:

1.0.1-dev3550

### DuckDB Client:

CLI

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, @Giorgi!
