### ISSUE TITLE
Scalar function without input parameters

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#13238]
### What happens?

When I register a scalar function without any parameters, the results from the callback are cached even if the function is marked as volatile.

I now get a data chunk with the correct size, but the query result prints the value of the first execution of the scalar function.

![image](https://github.com/user-attachments/assets/843f4832-5773-4203-a903-14061225d18a)

### To Reproduce

```c
state = duckdb_query(connection, "CREATE TABLE big_table_1 AS SELECT (greatest(random(), 0.1) * 1000)::BIGINT i FROM range(10) t(i);", &result);

auto scalar_function = duckdb_create_scalar_function();
duckdb_scalar_function_set_name(scalar_function, "my_random");

duckdb_scalar_function_set_volatile(scalar_function);
duckdb_scalar_function_set_return_type(scalar_function, duckdb_create_logical_type(DUCKDB_TYPE_INTEGER));
duckdb_scalar_function_set_function(scalar_function, my_random);

state = duckdb_register_scalar_function(connection, scalar_function);

state = duckdb_query(connection, "select my_random() from big_table_1;", &result);

auto chunk = duckdb_result_get_chunk(result, 0);

auto vector = duckdb_data_chunk_get_vector(chunk, 0);
auto data = (int32_t*)duckdb_vector_get_data(vector);

std::cout << "Printing values from query result" << std::endl << std::endl;

for (size_t i = 0; i < duckdb_data_chunk_get_size(chunk); i++)
{
	std::cout << data[i] << std::endl;
}
```

```c
void my_random(duckdb_function_info, duckdb_data_chunk input, duckdb_vector output) {
	auto size = duckdb_data_chunk_get_size(input);

	auto result_data = (int32_t*)duckdb_vector_get_data(output);

	for (size_t i = 0; i < size; i++)
	{
		result_data[i] = rand();
	}

	std::cout << "Printing values from scalar function callback" << std::endl << std::endl;

	for (size_t i = 0; i < size; i++)
	{
		std::cout << result_data[i] << std::endl;
	}
}
```

### OS:

Windows 11 x64

### DuckDB Version:

1.0.1-dev3542

### DuckDB Client:

C Api

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in https://github.com/duckdb/duckdb/pull/13241

**Comment by Giorgi** [comment]
Thanks for the quick fix, it's now working as expected.
