### ISSUE TITLE
CLI - incorrect decimal representation in ".mode insert"

### ISSUE THREAD

**Issue by milancio42** [duckdb/duckdb#13237]
### What happens?

Decimals are being represented incorrectly in ".mode insert". It looks like there is an implicit cast to `float`.

### To Reproduce

```
create table t (a decimal(38,18));
insert into t values (3.14), (2.71);

from t;
```

Output (decimals are precise):
```
┌──────────────────────┐
│          a           │
│    decimal(38,18)    │
├──────────────────────┤
│ 3.140000000000000000 │
│ 2.710000000000000000 │
└──────────────────────┘

```

```
.mode insert

from t;
```

Output (decimals are imprecise):
```
INSERT INTO "table"(a) VALUES(3.1400000000000001243);
INSERT INTO "table"(a) VALUES(2.7099999999999999644);
```

### OS:

macOS 14.5 (M1)

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Milan Opath

### Affiliation:

independent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@milancio42 thanks, I could reproduce the issue.
