### ISSUE TITLE
S3 to HTTP path conversion when writing to AWS S3 in Gov Cloud

### ISSUE THREAD

**Issue by ryvdx** [duckdb/duckdb#13248]
### What happens?

I believe your S3 path to HTTP path conversion is incorrect for AWS Gov Cloud.  I am trying to write duckdb tables out to parquet files in S3. Here is a snippit of what I'm doing:

```
# Initialize an in-memory DuckDB connection
conn = duckdb.connect(database=':memory:')
conn.execute("INSTALL aws;LOAD aws;")
conn.execute("INSTALL httpfs;LOAD httpfs;")
conn.execute("CALL load_aws_credentials();")
...
...
...
# Write the duckdb table to S3 as parquet
file_name = f's3://{s3_bucket}/data/{table_name}/{table_name}.parquet'
conn.execute(f"COPY {table_name} TO '{file_name}' (FORMAT 'parquet')")
```

The error occurs on execute:
```
self.conn.execute(f"COPY {table_name} TO '{file_name}' (FORMAT 'parquet')")
duckdb.duckdb.HTTPException: HTTP Error: Unable to connect to URL "https://{bucket...}.s3.amazonaws.com/data/encounters/encounters.parquet": 400 (Bad Request)
```

That HTTP path above is correct and runs in AWS Commercial.  However, when I run this in AWS Gov cloud it fails with that error above because the paths for gov cloud should look like:
https://{bucket...}.s3.us-gov-east-1.amazonaws.com/

the url slug "us-gov-east-1" is missing in your s3 to http path ranslation for s3 paths into gov cloud accounts.

### To Reproduce

```
# Initialize an in-memory DuckDB connection
conn = duckdb.connect(database=':memory:')
conn.execute("INSTALL aws;LOAD aws;")
conn.execute("INSTALL httpfs;LOAD httpfs;")
conn.execute("CALL load_aws_credentials();")
...
... (make some generic table here)
...
# Write the duckdb table to S3 as parquet
file_name = f's3://{s3_bucket}/data/{table_name}/{table_name}.parquet'
conn.execute(f"COPY {table_name} TO '{file_name}' (FORMAT 'parquet')")
```

### OS:

x86

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Mark Sawczuk

### Affiliation:

Ryveal Analytics, LLC

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @ryvdx, I am unable to test this but I believe that this is the case. I passed it on to the team.

For the time being, can you try the [S3 API legacy authentication scheme](https://duckdb.org/docs/extensions/httpfs/s3api_legacy_authentication), which allows defining a custom S3 endpoint?

**Comment by samansmink** [comment]
Hi @ryvdx you are `load_aws_credentials()` which is deprecated in favor of  secrets: https://duckdb.org/docs/configuration/secrets_manager.html.

You should be able to create a secret with:
```SQL
CREATE SECRET s1 (
    TYPE S3,
    PROVIDER credential_chain,
    ENDPOINT 's3.us-gov-east-1.amazonaws.com',
)
from 's3://test/test.parquet';
```
Which queries the path `https://test.s3.us-gov-east-1.amazonaws.com/test.parquet` using the automatically loaded credentials
