### ISSUE TITLE
Mismatch Type Error for Struct when reading multiple parquet files

### ISSUE THREAD

**Issue by thbley** [duckdb/duckdb#13245]
### What happens?

Reading multiple json files with different structs is ok:

```
echo '{"header":{"a":["a1", "a2"],"b":["b1", "b2"],"c":["c1", "c2"]}}' > a.json
echo '{"header":{"b":["b2", "b3", "b4"],"c":["c"],"d":["d"]}}' > b.json

duckdb -c "select * from '*.json';"
┌────────────────────────────────────────────────────────────┐
│                           header                           │
│ struct(a varchar[], b varchar[], c varchar[], d varchar[]) │
├────────────────────────────────────────────────────────────┤
│ {'a': [a1, a2], 'b': [b1, b2], 'c': [c1, c2], 'd': NULL}   │
│ {'a': NULL, 'b': [b2, b3, b4], 'c': [c], 'd': [d]}         │
└────────────────────────────────────────────────────────────┘
```

Converting the json files to parquet files and read them gives an error

```
duckdb -c "copy (select * from 'a.json') to 'a.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);"
duckdb -c "copy (select * from 'b.json') to 'b.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);"

duckdb -c "select * from '*.parquet';"
Mismatch Type Error: Type STRUCT(b VARCHAR[], c VARCHAR[], d VARCHAR[]) does not match with STRUCT(a VARCHAR[], b VARCHAR[], c VARCHAR[]). Cannot cast STRUCTs - element "d" in source struct was not found in target struct
```

I tried union_by_name=true, but same error.

I'm not sure this is the expected behavior or is there any other parameter I need to set when reading from multiple parquet files?

### To Reproduce

```
echo '{"header":{"a":["a1", "a2"],"b":["b1", "b2"],"c":["c1", "c2"]}}' > a.json
echo '{"header":{"b":["b2", "b3", "b4"],"c":["c"],"d":["d"]}}' > b.json
duckdb -c "select * from '*.json';"
```

```
duckdb -c "copy (select * from 'a.json') to 'a.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);"
duckdb -c "copy (select * from 'b.json') to 'b.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);"
duckdb -c "select * from '*.parquet';"
```

### OS:

Linux, amd64

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

duckdb cli

### Full Name:

Thomas Bley

### Affiliation:

myself

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @thbley, thanks for opening this issue. These JSON files encode tables with a single header column called `header` that has a different type. See the following:

```
D DESCRIBE (FROM 'a.json');
┌─────────────┬───────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │                  column_type                  │  null   │   key   │ default │  extra  │
│   varchar   │                    varchar                    │ varchar │ varchar │ varchar │ varchar │
├─────────────┼───────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ header      │ STRUCT(a VARCHAR[], b VARCHAR[], c VARCHAR[]) │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴───────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
```
```
D DESCRIBE (FROM 'b.json');
┌─────────────┬───────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │                  column_type                  │  null   │   key   │ default │  extra  │
│   varchar   │                    varchar                    │ varchar │ varchar │ varchar │ varchar │
├─────────────┼───────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ header      │ STRUCT(b VARCHAR[], c VARCHAR[], d VARCHAR[]) │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴───────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
```

Using `union_by_name` cannot help unify these two schemas. Try lifting the struct's items to the schema level, i.e.:

```
echo '{"a":["a1", "a2"],"b":["b1", "b2"],"c":["c1", "c2"]}' > a.json
echo '{"b":["b2", "b3", "b4"],"c":["c"],"d":["d"]}' > b.json
duckdb -c "select * from '*.json';"

duckdb -c "copy (select * from 'a.json') to 'a.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);"
duckdb -c "copy (select * from 'b.json') to 'b.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);"
duckdb -c "select * from read_parquet('*.parquet', union_by_name = true);"
```

This results in:

```
┌───────────┬──────────────┬───────────┬───────────┐
│     a     │      b       │     c     │     d     │
│ varchar[] │  varchar[]   │ varchar[] │ varchar[] │
├───────────┼──────────────┼───────────┼───────────┤
│ [a1, a2]  │ [b1, b2]     │ [c1, c2]  │ NULL      │
│ NULL      │ [b2, b3, b4] │ [c]       │ [d]       │
└───────────┴──────────────┴───────────┴───────────┘
```

**Comment by thbley** [comment]
`DESCRIBE (FROM 'a.parquet');` and `DESCRIBE (FROM 'a.json');` have the same schema and the same data.

`DESCRIBE (FROM 'b.parquet');` and `DESCRIBE (FROM 'b.json');` have the same schema and the same data.

Therefore, `FROM '*.json';` and `FROM '*.parquet';` should also give the same results.

Wouldn't it make sense to have consistent behavior between reading json files and reading parquet files?

**Comment by szarnyasg** [comment]
That's a good observation, thanks for pointing this out! I assume that the JSON variant is more lenient because of JSON's semi-structured nature. We'll take a look internally!

**Comment by lnkuiper** [comment]
There is a very slight difference. As @szarnyasg says, the JSON reader is more lenient because JSON is semi-structured. JSON uses _keys_ to identify columns, while Parquet is _positional_. The error that is thrown actually describes this well:
```
Mismatch Type Error: Type STRUCT(b VARCHAR[], c VARCHAR[], d VARCHAR[]) does not match with STRUCT(a VARCHAR[], b VARCHAR[], c VARCHAR[]). Cannot cast STRUCTs - element "d" in source struct was not found in target struct
```
The problem is that
```
STRUCT(b VARCHAR[], c VARCHAR[], d VARCHAR[])
```
Is not equal to
```
STRUCT(a VARCHAR[], b VARCHAR[], c VARCHAR[])
```
The JSON type detection is much more lenient than the Parquet reader, especially with nested data.

The JSON reader always unifies the schema from the first few files by default (because it is very common to have, e.g., thousands of JSON files with just one object in them), while the Parquet reader only unifies the schema of multiple files when you do `union_by_name=true`. The JSON reader also does recursive schema unification, while the Parquet reader only does top-level schema unification.

For now, this behavior is expected.

**Comment by thbley** [comment]
> The JSON reader also does recursive schema unification, while the Parquet reader only does top-level schema unification.

Any chances to change this? e.g. nested_union_by_name=true

The use case is http client logs. So the http response headers can be pretty anything, any nested schema. Using parquet files is much faster and easier to handle the traffic. Would be great to have a solution for this.

**Comment by lnkuiper** [comment]
I think we may add that at some point, but it's not a priority at the moment. However, in the next release, you will be able to infer the type as `MAP` instead of `STRUCT`:
```sql
copy (
    select *
    from read_json('a.json', map_inference_threshold=0)
) to 'a.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);
copy (
    select *
    from read_json('b.json', map_inference_threshold=0)
) to 'b.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);
select * from '*.parquet';
┌───────────────────────────────────────────────┐
│                     json                      │
│     map(varchar, map(varchar, varchar[]))     │
├───────────────────────────────────────────────┤
│ {header={a=[a1, a2], b=[b1, b2], c=[c1, c2]}} │
│ {header={b=[b2, b3, b4], c=[c], d=[d]}}       │
└───────────────────────────────────────────────┘
```
