### ISSUE TITLE
Support HH:MM for TIME type in csv_sniffer

### ISSUE THREAD

**Issue by dioptre** [duckdb/duckdb#13247]
### What happens?

Importing 21:30, or 05:40 does not import correctly

### To Reproduce

```sql
FROM read_csv('xxx.csv');
```

Where `xxx.csv` is:

```csv
a,b
05:40, 7
21:30, 21
17:45, 99
```

### OS:

Mac

### DuckDB Version:

Latest

### DuckDB Client:

Python

### Full Name:

Andrew Grosser

### Affiliation:

Sourcetable

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@dioptre thanks for opening this issue. This is expected behavior at the moment, see https://duckdb.org/docs/data/csv/auto_detection.html#dates-and-timestamps.

**Comment by pdet** [comment]
This is not related to dates/timestamps but rather to the casting to time types.

We were not following the casts from Postgres and would have a cast failure on time types without seconds.

This should be fixed with https://github.com/duckdb/duckdb/pull/13267
