### ISSUE TITLE
`read_csv_auto` fails to parse column as timestamp when meets YYYY-MM-DDTHH:mm format

### ISSUE THREAD

**Issue by kolmakova** [duckdb/duckdb#13266]
### What happens?

Column that has mixed ISO 8601 timestamps with **YYYY-MM-DDTHH:mm** timestamp being parsed BY `read_csv_auto` as `VARCHAR` instead of `TIMESTAMP`.

### To Reproduce

using 
`CREATE TABLE test AS SELECT * FROM read_csv_auto(%path to csv file%);
DESCRIBE test;`

---

time 
2021-10-11T18:59:14Z
2021-10-11T12:55Z

time column parsed as `VARCHAR`

---

time 
2021-10-11T18:59:14Z

time column parsed as `TIMESTAMP`

---

time 
2021-10-11T12:55Z

time column parsed as `VARCHAR`

### OS:

windows

### DuckDB Version:

@duckdb/duckdb-wasm@1.28.1-dev245.0

### DuckDB Client:

shell

### Full Name:

Dasha Kolmakova

### Affiliation:

-

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
Hi @kolmakova, thanks for opening this issue. This is currently intended behavior due to two factors: (1) DuckDB's CSV reader doesn't allow a mix of formats and doesn't support the `YYYY-MM-DDTHH:mm` format by default (unless it is specified explicitly), see here: https://duckdb.org/docs/data/csv/auto_detection#dates-and-timestamps

**Comment by kolmakova** [comment]
Thank you for the answer. I'll close issue then.
