### ISSUE TITLE
Segmentation fault with (repeated?) AWS S3 access through httpfs

### ISSUE THREAD

**Issue by valpesendorfer** [duckdb/duckdb#13265]
### What happens?

I'm creating a new file database with two tables - one from parquet files read from AWS S3 and a second table created as a copy from a table within an attached read-only database, also on AWS S3. 

The first step finishes just fine, but creating the table from the attached database produces a segmentation fault.

I've confirmed that this issue happens specifically when the attached database is on S3 (both public & private), it works if it's a local database or available via HTTPS.

Potentially related to #8258:

I tried updating `httpfs` and did the force install but the issue remains

### To Reproduce

```bash
# intitialize cli with `duckdb /tmp/duck.db`

v1.0.0 1f98600c2c
Enter ".help" for usage hints.
D INSTALL httpfs;
D     LOAD httpfs;
D     CREATE OR REPLACE TEMPORARY SECRET secret (
      TYPE S3,
      PROVIDER CREDENTIAL_CHAIN
  );
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D ATTACH 's3://.../duck.db' AS src (READ_ONLY);
D CREATE TABLE vim as SELECT * FROM read_parquet('s3://.../admins/iso3=wld/*/*/vam=vim/*.parquet', hive_partitioning = 1);
100% ▕████████████████████████████████████████████████████████████▏ 
D CREATE TABLE rfb AS (SELECT * FROM src.rfb);
Segmentation fault (core dumped)
```

If I replace the attached DB with one that's local or HTTPS (in this example) it all works fine:

```bash
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
D INSTALL httpfs;
D     LOAD httpfs;
D     CREATE OR REPLACE TEMPORARY SECRET secret (
      TYPE S3,
      PROVIDER CREDENTIAL_CHAIN
  );
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ true    │
└─────────┘
D ATTACH 'https://data.earthobservation.vam.wfp.org/public-share/duckdb-test/duck.db' AS src (READ_ONLY);
D CREATE TABLE vim as SELECT * FROM read_parquet('s3://.../admins/iso3=wld/*/*/vam=vim/*.parquet', hive_partitioning = 1);
100% ▕████████████████████████████████████████████████████████████▏ 
D CREATE TABLE rfb AS (SELECT * FROM src.rfb);
100% ▕████████████████████████████████████████████████████████████▏ 
```
To reproduce, the readonly db can be accessed at:

https://data.earthobservation.vam.wfp.org/public-share/duckdb-test/duck.db (168MB)

and the parquet files are zipped up and available at:

https://data.earthobservation.vam.wfp.org/public-share/duckdb-test/admins.zip (507MB)

### OS:

centos rhel fedora Amazon Linux 2 x86_64

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

CLI & python

### Full Name:

Val Pesendorfer

### Affiliation:

UN WFP

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks @valpesendorfer, I could reproduce the issue!

**Comment by szarnyasg** [comment]
@valpesendorfer I tested the script on the nightly build and the error no longer occurs. Can you please try the nightly build? It is available both for CLI and Python at https://duckdb.org/docs/installation/

**Comment by valpesendorfer** [comment]
Thanks @szarnyasg. 

I've tried using the python client (just upgraded through pip) and I get

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> duckdb.duckdb.InternalException: INTERNAL Error: Information loss on integer cast: value 23.333327 outside of target range [23.000000, 23.000000]
> This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.

during the step that creates the first table from the parquet files.

I've tried to run it with the CLI, but I'm having trouble installing the `httpfs` extension:

```bash
1.0.1-dev3700 e42a9f4279
Enter ".help" for usage hints.
D INSTALL httpfs;
HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/e42a9f4279/linux_amd64_gcc4/httpfs.duckdb_extension.gz" (HTTP 403)
Extension "httpfs" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
D     LOAD httpfs;
IO Error: Extension ".../.duckdb/extensions/e42a9f4279/linux_amd64_gcc4/httpfs.duckdb_extension" not found.
Extension "httpfs" is an existing extension.

Install it first using "INSTALL httpfs".
```

**Comment by Mytherin** [comment]
Thanks for the PR!

There have been a few fixes in httpfs recently - e.g. https://github.com/duckdb/duckdb/pull/13052 - so this has likely been fixed in the latest development branch already.

The internal error should be fixed in https://github.com/duckdb/duckdb/pull/13275 which will be available with the next nightly.

**Comment by valpesendorfer** [comment]
Tested with `duckdb==1.0.1-dev3777` and can confirm no issues!

**Comment by Mytherin** [comment]
Great, thanks for investigating!
