### ISSUE TITLE
After successfully loading large text CSV file, SUMMARIZE fails with OOM at exactly 80% of physical memory

### ISSUE THREAD

**Issue by rbpasker** [duckdb/duckdb#13270]
### What happens?

after loading a large text table (see https://github.com/duckdb/duckdb/issues/13177 to load the data), `SUMMARIZE` fails with OOM at exactly 80% of the physical memory footprint (2 different machines: 12.8/16gb and 51.2/64gb).

I would have thought that the execution plan would perform the operation out-of-core, instead of exhausting memory

### To Reproduce

load data as per: https://github.com/duckdb/duckdb/issues/13177

```
SUMMARIZE opinions;
```

### OS:

MacOS 12.7.5 (21H1222)  (fails on other machines too)

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

CLI

### Full Name:

Bob Pasker

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by rbpasker** [comment]
i am actually trying to do a `JOIN` with this table, and it fails in exactly the same way (OOM @80%), but this is a more minimal example. Hopefully, if `SUMMARIZE` works, `JOIN` will as well

**Comment by rbpasker** [comment]
Further update, i tried restricting the size of the JOIN to smaller result by adding  `where MOD(o.id, 10) == 0` (rows with '0' in the units digit of the `PRIMARY KEY`) to the query, but it still fails.

**Comment by xgdgsc** [comment]
I' m also doing join and tips at https://duckdb.org/2024/07/09/memory-management.html#intermediate-spilling doesn't work.

**Comment by hrshdhgd** [comment]
Potential solution: https://github.com/duckdb/duckdb/issues/9880#issuecomment-2302076955
