### ISSUE TITLE
INTERNAL Error: Incorrect stats size for type TIMETZ

### ISSUE THREAD

**Issue by eli-daniels** [duckdb/duckdb#13272]
### What happens?

Loading parquet file into DuckDB table with read_parquet leads to internal error. But, the R arrow package can successfully load the parquet file with no issues leading me to think that the parquet is fine and the duckdb parquet reader may have an issue.

### To Reproduce

Reading these time columns leads to an internal error.
```
library(duckdb)
con <- dbConnect(duckdb())
dbSendQuery(con, "CREATE TABLE mytable AS FROM read_parquet('times.parquet');")
```
Gives error:
```
Error: rapi_prepare: Failed to prepare query CREATE TABLE mytable AS FROM read_parquet('pk/1.pk');
Error: INTERNAL Error: Incorrect stats size for type TIMETZ
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```
But using arrow package I get : 
```
arrow::read_parquet('times.parquet')
# A tibble: 1 × 2
  col1   col2  
  <time> <time>
1 00'00" 00'00"
```
I've reduced the original file down to the minimum required to reproduce the internal error, 1 line, 2 columns. I didn't check if only one column is the issue or if its both.
[times.zip](https://github.com/user-attachments/files/16467664/times.zip)

### OS:

Windows 10 Professionnel x64

### DuckDB Version:

R package version 1.0.0-2

### DuckDB Client:

R version 4.3.2

### Full Name:

Eli Daniels

### Affiliation:

ArData

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks! This also reproduces from the CLI client:

```sql
CREATE TABLE mytable AS FROM read_parquet('times.parquet');
```

**Comment by Mytherin** [comment]
Thanks for the report! I've pushed a fix in https://github.com/duckdb/duckdb/pull/13283

**Comment by eli-daniels** [comment]
Sorry one last question, how long would it generally take for the fix to come through to the R package on the cran?

**Comment by szarnyasg** [comment]
It will be on CRAN a few days after the next release which is currently scheduled for September 2, see https://duckdb.org/docs/dev/release_calendar.html.

Given that this is still a month, you may want to compile the package from source following the [instructions in the R README](https://github.com/duckdb/duckdb-r?tab=readme-ov-file#building).
