### ISSUE TITLE
python import error

### ISSUE THREAD

**Issue by smalltalk96** [duckdb/duckdb#1327]
I got a message when "import duckdb" in python
ImportError: DLL load failed

**Comment by Mause** [comment]
Can you provide more details?
Which version of which operating system?
Which version of python?
Which version of duckdb?

**Comment by smalltalk96** [comment]
windows 10 64bit
3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
duckdb 0.2.3

**Comment by hannesmuehleisen** [comment]
We test this in our CI. Your environment may be slightly different, and we would like to know how it is different. How did you install DuckDB? How did you install Python? Any other relevant changes? Are you running this in WSL?

**Comment by hannesmuehleisen** [comment]
@smalltalk96 any additional details?

**Comment by hannesmuehleisen** [comment]
Have not heard anything in months, closing

**Comment by gutzbenj** [comment]
Dear @hannes ,

first of all thanks for this amazing library!

I was just running in the same error.

The venv I'm running is based on Python 3.7.4 64bit on a Windows Server. I successfully installed duckdb 0.3.2 and 0.3.1 via the corresponding wheel, however when importing duckdb into the env like `import duckdb` it just states  *ImportError: DLL load failed*. Might there be any DLL in the backend, that has conflicts with Python 3.7/3.7.4? The ImportError itself isn't really helpful. This may be originating in cpp backend.



Cheers
Benjamin

**Comment by Mytherin** [comment]
That's related to #3425, there are several missing wheel builds for 0.3.3

**Comment by gutzbenj** [comment]
Thanks for the fast answer! I will try older versions as well an tuesday and report back here!
