### ISSUE TITLE
csv_read() creates table with only VARCHARs when all headers and values are surrounded by quotes

### ISSUE THREAD

**Issue by pronzato** [duckdb/duckdb#13305]
### What happens?

This is probably not a bug but I cannot find anyway around this problem (have scoured the duckdb documentation and posts but cannot seem to find a solution).  I have CSV files which have quotes around all the headers and values but I cannot find the magic combo to effectively have the CSV reader ignore those quotes and infer the correct types.  As such, it treats everything as `VARCHAR.`

### To Reproduce

example csv file would be:

```
"DATE", "ID", "NAME", "AGE"
"2024/08/05","ID1","DAVE",47
"2024/08/05","ID2","ANNA",32
"2024/08/05","ID3","BILL",49
```

creates table with all columns as `VARCHAR`

### OS:

Windows

### DuckDB Version:

1.0.0

### DuckDB Client:

Java

### Full Name:

Gianni Pronzato

### Affiliation:

Bank Of America

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @pronzato, I am unable to reproduce the issue. The CSV reader correctly detects the types for me in both 1.0.0 and the nightly build:

```sql
FROM 'my.csv';
```
```
┌────────────┬─────────┬─────────┬───────┐
│    DATE    │   ID    │  NAME   │  AGE  │
│    date    │ varchar │ varchar │ int64 │
├────────────┼─────────┼─────────┼───────┤
│ 2024-08-05 │ ID1     │ DAVE    │    47 │
│ 2024-08-05 │ ID2     │ ANNA    │    32 │
│ 2024-08-05 │ ID3     │ BILL    │    49 │
└────────────┴─────────┴─────────┴───────┘
```

**Comment by pronzato** [comment]
Resolved
