### ISSUE TITLE
Bitstring equality fails when in select position

### ISSUE THREAD

**Issue by rharink** [duckdb/duckdb#13318]
### What happens?

Im was trying to use BITSTRING in a where clause and noticed I didn't receive the expected results. After asking around on the Discord channel (https://discord.com/channels/909674491309850675/1032659480539824208/1270137420360450179) This seemed to be a bug, hence the bug report here.

The conclusion in the Discord thread: 
the bitstring created by the & operator seems to not have the right internal structure somehow causing the equality operator to return false.

### To Reproduce

```sql
CREATE TABLE IF NOT EXISTS mask_test (
    flags        BITSTRING,
);

INSERT INTO mask_test (flags) VALUES ('00000001'::BIT);
INSERT INTO mask_test (flags) VALUES ('00000011'::BIT);

-- This select statement shows that the flags & <MASK> equals '0000001' for both entries
SELECT (flags & '00000001'::BIT) from main.mask_test;

-- The select statement below returns 0 results, where i would expect it to return 2 rows.
SELECT * from main.mask_test WHERE (flags & '00000001'::BIT) = '00000001'::BIT;


-- This works after casting
SELECT (flags & '00000001')::VARCHAR::BIT = '00000001'::BIT from main.mask_test;

-- This doesn't work
SELECT (flags & '00000001')::BIT = '00000001'::BIT from main.mask_test;

```

### OS:

macOS

### DuckDB Version:

1.0

### DuckDB Client:

Rust

### Full Name:

Robert den Harink

### Affiliation:

Full Join

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I actually can't reproduce this on `main`.

With out test framework:
```sql
statement ok
CREATE TABLE IF NOT EXISTS mask_test (
    flags        BITSTRING,
);

statement ok
INSERT INTO mask_test (flags) VALUES ('00000001'::BIT);

statement ok
INSERT INTO mask_test (flags) VALUES ('00000011'::BIT);

query I
SELECT (flags & '00000001')::BIT = '00000001'::BIT from main.mask_test;
----
true
true
```

This passes, where based on your report the last statement would return `false` for one or both of the rows

**Comment by soerenwolfers** [comment]
Last time I reported the same bug, it was hardware dependent
https://github.com/duckdb/duckdb/issues/11211 

On my hardware, the OP (and the example in my previous issue) are now working.

**Comment by szarnyasg** [comment]
@rharink thanks for reporting this. Similarly @Tishj and @soerenwolfers, I am also unable to reproduce it.

I have two questions to help pinpoint the cause:
1) What architecture do you run macOS on, Intel or Apple Silicon?
2) Can you reproduce the error using the CLI client?

**Comment by rharink** [comment]
I figured it out. I tested the queries on what i thought was version `1.0`, but its version `0.10.1`. I ran the queries via a external tool called Pilot DB. The software we're working on uses `1.0` (bundled with duckdb-rs). Thanks for the help!
