### ISSUE TITLE
Copying a parquet with nano timestamps degrade the timestamp to micros. 

### ISSUE THREAD

**Issue by Kuinox** [duckdb/duckdb#13325]
### What happens?

Hello,

When using `copy to`, duckdb degrade the `timestamp_utc` field from nanos to micros.  
This does not happen with a parquet generated with duckdb or pyarrow.  

Note: In the issue template, the link to the DuckDB Arrow extension lead to a 404.

### To Reproduce

Parquet file: [data.zip](https://github.com/user-attachments/files/16512584/data.zip)

```sql
copy (select * from "data.parquet") to 'duckdb.parquet' (format parquet);
```
In my parquet sample, the metadata shows:  
```json
"Children": [
      {
        "Path": "timestamp_utc",
        "Type": "INT64",
        "TypeLength": null,
        "LogicalType": {
          "Name": "TIMESTAMP",
          "IsAdjustedToUTC": true,
          "Unit": "NANOS"
        },
        "RepetitionType": "OPTIONAL",
        "ConvertedType": "",
        "Children": []
      }
    ]
```

DuckDB generated parquet:
```json
"Children": [
      {
        "Path": "timestamp_utc",
        "Type": "INT64",
        "TypeLength": null,
        "LogicalType": {
          "Name": "TIMESTAMP",
          "IsAdjustedToUTC": true,
          "Unit": "MICROS"
        },
        "RepetitionType": "OPTIONAL",
        "ConvertedType": "TIMESTAMP_MICROS",
        "Children": []
      }
    ]
```

### OS:

Windows 11

### DuckDB Version:

v1.0.1-dev3700 e42a9f4279

### DuckDB Client:

CLI

### Full Name:

Nicolas Vandeginste

### Affiliation:

@Abc-Arbitrage

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @Kuinox 

> Note: In the issue template, the link to the DuckDB Arrow extension lead to a 404.

Thanks, I submitted a fix for this: #13333

I could reproduce the error and we'll take a look.

**Comment by hawkfish** [comment]
Unfortunately, this is expected behavior because the column has an attached time zone, so we map it to `TIMESTAMP WITH TIME ZONE`, which only has µs precision.

```sql
D describe from 'data.parquet';
```
|  column_name  |       column_type        | null | key | default | extra |
|---------------|--------------------------|------|-----|---------|-------|
| timestamp_utc | TIMESTAMP WITH TIME ZONE | YES  |     |         |       |

**Comment by Kuinox** [comment]
Hi, even if I remove the timezone:
```
┌───────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│  column_name  │ column_type │  null   │   key   │ default │  extra  │
│    varchar    │   varchar   │ varchar │ varchar │ varchar │ varchar │
├───────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ timestamp_utc │ TIMESTAMP   │ YES     │         │         │         │
│ value         │ INTEGER     │ YES     │         │         │         │
└───────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
D copy (select * from "data.parquet") to 'duckdb.parquet' (format parquet);
```
The produced parquet is still Micros.

**Comment by hawkfish** [comment]
Can you attach the new `data.parquet` file and I'll have another look?

**Comment by Kuinox** [comment]
[data.zip](https://github.com/user-attachments/files/16604198/data.zip)

**Comment by hawkfish** [comment]
Your build is two weeks old and I think this has been fixed:

```sql
copy( from 'data.parquet') to 'ns.parquet';
describe from 'ns.parquet';
```

|  column_name  | column_type  | null | key | default | extra |
|---------------|--------------|------|-----|---------|-------|
| timestamp_utc | TIMESTAMP_NS | YES  |     |         |       |
| value         | INTEGER      | YES  |     |         |       |

Can you try with the latest?

```sql
select version();
```

|  "version"()   |
|----------------|
| v1.0.1-dev4155 |

**Comment by Kuinox** [comment]
It does indeed work with latest (and now i'm not sure anymore with which version I re-ran the tests.), sorry for that.  

Then if the original issue is intended behavior, is there a way to migrate/query parquets that have a timestamp without degrading it to a micros, with duckdb ?

**Comment by hawkfish** [comment]
Remove the time zone. That is usually presentation layer data anyway. If you really need it for the analysis, then put it in a separate column.

**Comment by Kuinox** [comment]
Thanks a lot for the answers
