### ISSUE TITLE
Can you add a Python Appender API?

### ISSUE THREAD

**Issue by fintron** [duckdb/duckdb#1333]
It would be really helpful to be able to use the Appender API:
https://duckdb.org/docs/data/appender

in Python. Unfortunately, the best way to do this in Python right now is the Pandas dataframe option:
https://duckdb.org/docs/api/python
This isn't a great option when you want to bulk append to an existing table.

**Comment by Mytherin** [comment]
You can also insert into a table from any query, including from a pandas dataframe. For example:

```sql
INSERT INTO test_df_table SELECT * FROM test_df_view
```

Does that resolve the issue, or would you propose a different method of appending?

The problem with porting the Appender as-is is that constructing Python objects is really expensive. Perhaps it would help if you could tell us what you would envision this API to look like. A straightforward wrapper like e.g.:

```python
appender = con.append("table");
appender.append(1, 2);
appender.append(1, 2);
```

Would still be very slow because of all the Python object allocation and de-allocation overhead.

**Comment by fintron** [comment]
I would recommend two different APIs for appending.

1. Via dataframes:
Append a dataframe to an existing table. This is already possible via the APIs you built, but it could. be slightly simpler for users. Eg:
```
table.append_df(df)
```
That would basically create a virtual reference to the dataframe, insert the values in, and then delete the virtual reference. 

2. Via the appender API you recommended

While you are correct that this will add latency b/c of Python object allocation overhead, this might still pale in comparison to the overhead of writing to disk?

This will be especially useful when writing entries to the DuckDB that are too big to fit into memory. This appender API would let us basically add things in batch (into memory) and then flush it to disk.

**Comment by frankier** [comment]
+1 on the append_df API. Another nice thing would be able to force a pandas df dataframe to use datatypes from a table for its columns. There is a risk when constructing a df from a list of rows that it will infer the wrong datatype. This could all be detailed in the "getting your data into duckdb" guide.

This is the utility function I just wrote for myself which could perhaps be eliminated:

```
def flush_rows(schema, conn, rows):
    import pandas
    df = pandas.DataFrame(rows)
    conn.register('df', df)
    conn.execute(f"INSERT INTO {schema} SELECT * FROM df;")
    conn.unregister('df')
    rows.clear()
    conn.commit()
```

And then I call this every time rows gets to some big chunksize

On the other hand I don't see why there shouldn't be an appender API. Surely it could still be faster than going via pandas in the case that you're already starting off with Python objects.

**Comment by hannes** [comment]
You can already insert into an existing tables by doing something like `INSERT INTO some_table SELECT * FROM some_data_frame`. Adding specific syntax to the API for this seems not necessary.
