### ISSUE TITLE
extension on android (arm)

### ISSUE THREAD

**Issue by zcatav** [duckdb/duckdb#13337]
### What happens?

Hi, 
I am using Duckdb in Termux on my Android phone. When I want to install sqlite support to open the sqlite database, I get the following error. Thanks in advance for your help in resolving it.

```
duckdb
v1.0.0 1f98600
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D install sqlite;

HTTP Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/v1.0.0/linux_arm64_android/sqlite_scanner.duckdb_extension.gz"
Extension "sqlite_scanner" is an existing extension.
```

### To Reproduce

`duckdb
v1.0.0 1f98600
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D install sqlite;

HTTP Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/v1.0.0/linux_arm64_android/sqlite_scanner.duckdb_extension.gz"
Extension "sqlite_scanner" is an existing extension.`

### OS:

android 14

### DuckDB Version:

v1.0.0 1f98600

### DuckDB Client:

terminal

### Full Name:

zcatav

### Affiliation:

personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @zcatav, unfortunately, Android is not (yet) [an officially supported platform for extensions](https://duckdb.org/docs/extensions/working_with_extensions#platforms), so this is expected behavior.
