### ISSUE TITLE
`INSTALL ... FROM ...;` failure

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#13379]
### What happens?

The manual says: "INSTALL can be used with the path to [...] a .duckdb_extension file."

I built duckdb locally with BUILD_JSON=1 and verified that the file:

/Users/me/github/duckdb/build/release/extension/json/json.duckdb_extension

exists.

However, running duckdb commands such as:

install json from 'local_build_release';

or

install json from '/Users/me/github/duckdb/build/release/extension/json';

all fail.  The last fails with the message:

IO Error: Failed to copy local extension "json" at PATH "/Users/me/github/duckdb/build/release/extension/json/f5ab7c167e/osx_amd64/json.duckdb_extension"

Fortunately, creating a symbolic link based on the above line did solve the problem.

Version: v1.0.1-dev4052

### To Reproduce

From the Mac OS prompt: 
```
cd ~/github/duckdb   # home of local duckdb repository
export BUILD_JSON=1
make
cd  ~
~/github/build/release/duckdb
```
From the DuckDB prompt: as shown above.

### OS:

Mac OS

### DuckDB Version:

v1.0.1-dev4052

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @pkoppstein, thanks for opening this issue. I cannot reproduce it on macOS (version 14.6.1, Apple Silicon architecture):

```bash
cd duckdb
GEN=ninja BUILD_JSON=1 make
build/release/duckdb -c "install 'build/release/extension/json/json.duckdb_extension';"
```

This completes fine.

**Comment by pkoppstein** [comment]
@szarnyasg - Thanks for the explanation.
