### ISSUE TITLE
Confusing error message when creating a MACRO to parameterize the argument of read_csv_auto()

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#13382]
### What happens?

The SQL command:
```
CREATE MACRO read(fn) AS (SELECT * FROM read_csv_auto(fn));
```
results in a Binder Error:
```
Table function "read_csv_auto" does not support lateral join column parameters - cannot use column "fn" in this context
```
The same issue arises with similar "read" functions, e.g. read_parquet.

It would be more helpful if the error message could suggest that the TABLE keyword is missing.

### To Reproduce

```
CREATE MACRO read(fn) AS (SELECT * FROM read_csv_auto(fn));
```

### OS:

MacOS

### DuckDB Version:

v1.0.1-dev4052

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Maxxen** [comment]
Hi! Looks like you're trying to create a scalar macro that returns multiple rows - that won't work. I think what you want to do is create a ["table macro"](https://duckdb.org/docs/sql/statements/create_macro.html#table-macros), e.g. `CREATE MACRO read(fn) AS TABLE (SELECT * FROM read_csv_auto(fn));`

**Comment by pkoppstein** [comment]
@Maxxen. OK, but that was not a very helpful error message.  I'll edit the "subject".

**Comment by Maxxen** [comment]
Well, what else would the error message be? Some table functions (so called table-in-out functions) _do_ allow you to pass scalar arguments, for example (in the next release) the `range` function can (will).
```sql
CREATE MACRO read(fn) AS (SELECT * FROM range(fn));
SELECT read(i) from (values (5), (10), (20)) as c(i);
┌───────────┐
│ "read"(i) │
│   int64   │
├───────────┤
│         4 │
│         9 │
│        19 │
└───────────┘
``` 
Although its probably not very useful to create a scalar macro that calls the range table-in-out function in a subquery, from the docs: "If a scalar subquery returns more than a single value, the first value returned will be used". Im having a hard time coming up with a good example of when you would like to be able to pass a scalar argument into a subquery that executes a table function in a macro, but here's an attempt:

```sql
CREATE TABLE t1 (I INTEGER)
INSERT INTO t1 values (1), (2), (3);
CREATE MACRO is_in_table(arg) AS (SELECT EXISTS (SELECT FROM t1 WHERE i = arg));

SELECT is_in_table(2);
----
┌────────────────┐
│ is_in_table(2) │
│    boolean     │
├────────────────┤
│ true           │
└────────────────┘

SELECT is_in_table(5);
----
┌────────────────┐
│ is_in_table(5) │
│    boolean     │
├────────────────┤
│ false          │
└────────────────┘

**Comment by pkoppstein** [comment]
@Maxxen wrote:
> what else would the error message be?

The current error message certainly seems erroneous as it refers to "fn" as a column, whereas it is a formal argument.  From my point of view, an error message that is helpful would be ideal (e.g., that recommends checking whether the keyword TABLE is missing), but at least it should not be erroneous or easily subject to an erroneous interpretation.

**Comment by pkoppstein** [comment]
As of v1.1.4, the error message has vanished, so closing this issue.
