### ISSUE TITLE
INTERNAL Error when client_context.GetCurrentQuery() is called in an optimizer extension

### ISSUE THREAD

**Issue by juja0** [duckdb/duckdb#13391]
### What happens?

An internal error is raised when client_context.GetCurrentQuery() is called in an optimizer extension.

Raising an issue here based on discussion on discord.

A minimal repro can be found here: https://github.com/juja0/current_query_error

Note: This works without issue when executed via tests, so it could be related to the absence of an active transaction in the "prepare" stage of query execution from cli.

### To Reproduce

1. clone repo: https://github.com/juja0/current_query_error
2. Execute: "make debug"
3. Launch duckdb: "./build/debug/duckdb"
4. run any query

### OS:

osx_x64

### DuckDB Version:

v1.0.0

### DuckDB Client:

cli

### Full Name:

Gautham Kumar

### Affiliation:

Protium Finance

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @juja0, thanks for opening this issue and providing a reproducer!

When I issue `make debug`, I get the following error message:

```console
Makefile:8: extension-ci-tools/makefiles/duckdb_extension.Makefile: No such file or directory
make: *** No rule to make target `extension-ci-tools/makefiles/duckdb_extension.Makefile'.  Stop.
```

I'm on macOS / Apple Silicon.

**Comment by juja0** [comment]
Based on the error message, I think submodules may not have been cloned. Can you try cloning the repo with submodules included ? The git command for that would be 

git clone --recurse-submodules https://github.com/juja0/current_query_error

Note: The reproducer is based on the duckdb extension template: https://github.com/duckdb/extension-template

Just to confirm again, I ran the following on a macos+apple silicon machine and I'm able to reproduce the original issue.

1. git clone --recurse-submodules https://github.com/juja0/current_query_error
2. cd current_query_error
3. make debug
4. ./build/debug/duckdb
5. select 42;

**Comment by szarnyasg** [comment]
@juja0, thanks, I could reproduce the issue now!
