### ISSUE TITLE
Fields for indexes are not present anywhere  in metadata/information schema

### ISSUE THREAD

**Issue by Locustv2** [duckdb/duckdb#13414]
### What happens?

When querying `duckdb_indexes()` the fields belonging to the index are not present.

According to this link: https://discord.com/channels/909674491309850675/921073327009853451/1273234124177408051
The fields should be present under `expressions` but is not.

### To Reproduce

```
create table test_index (id integer primary key, name varchar, age tinyint, class int);

CREATE UNIQUE INDEX test_idx ON test_index (name, age, class);

select * from duckdb_indexes() WHERE table_name ='test_index' ;
```

### OS:

MacOS Sonoma

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

Command Line

### Full Name:

Yuv

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
At the time of creation of `duckdb_indexes` the IndexCatalogEntry was very minimal:
```c++
class IndexCatalogEntry : public StandardEntry {
public:
	//! Create a real TableCatalogEntry and initialize storage for it
	IndexCatalogEntry(Catalog *catalog, SchemaCatalogEntry *schema, CreateIndexInfo *info);
	~IndexCatalogEntry() override;

	Index *index;
	shared_ptr<DataTableInfo> info;
	string sql;

public:
	string ToSQL() override;
};
```

I think that's the reason "expressions" was left blank at the time
The PR that introduces this: <https://github.com/duckdb/duckdb/pull/1847> (2021) also likely predates the existence of the LIST type, which would be more suitable for "expressions" nowadays

**Comment by Tishj** [comment]
Compared to what the IndexCatalogEntry looks like nowadays:
```c++
class IndexCatalogEntry : public StandardEntry {
public:
	static constexpr const CatalogType Type = CatalogType::INDEX_ENTRY;
	static constexpr const char *Name = "index";

public:
	//! Create an IndexCatalogEntry
	IndexCatalogEntry(Catalog &catalog, SchemaCatalogEntry &schema, CreateIndexInfo &info);

	//! The SQL of the CREATE INDEX statement
	string sql;
	//! Additional index options
	case_insensitive_map_t<Value> options;

	//! The index type (ART, B+-tree, Skip-List, ...)
	string index_type;
	//! The index constraint type
	IndexConstraintType index_constraint_type;
	//! The column ids of the indexed table
	vector<column_t> column_ids;
	//! The set of expressions to index by
	vector<unique_ptr<ParsedExpression>> expressions;
	vector<unique_ptr<ParsedExpression>> parsed_expressions;

public:
	//! Returns the CreateIndexInfo
	unique_ptr<CreateInfo> GetInfo() const override;
	//! Returns the original CREATE INDEX SQL
	string ToSQL() const override;

	virtual string GetSchemaName() const = 0;
	virtual string GetTableName() const = 0;

	//! Returns true, if this index is UNIQUE
	bool IsUnique() const;
	//! Returns true, if this index is a PRIMARY KEY
	bool IsPrimary() const;
};
```
