### ISSUE TITLE
create_function -> Invalid Input Error: This function can not be called with an active transaction!, commit or abort the existing one first

### ISSUE THREAD

**Issue by radi2015** [duckdb/duckdb#13429]
### What happens?

  ```
conn = duckdb.connect(database=':memory:')
conn.execute(f"SELECT installed,loaded FROM duckdb_extensions() ;").fetchone()   
conn.create_function("line_3point_min_angle",CheckUdf.line_3point_min_angle )
```
before create_function,fetchone will be error 
`    conn.create_function(attr_name, attr_value,
duckdb.duckdb.InvalidInputException: Invalid Input Error: This function can not be called with an active transaction!, commit or abort the existing one first`

but fetchall()  not error
```
 conn = duckdb.connect(database=':memory:')
conn.execute(f"SELECT installed,loaded FROM duckdb_extensions() ;").fetchall()
conn.create_function("line_3point_min_angle",CheckUdf.line_3point_min_angle )

```

### To Reproduce

```
    conn = duckdb.connect(database=':memory:')
    conn.execute(f"SELECT installed,loaded FROM duckdb_extensions() ;").fetchone()
    conn.create_function(CheckUdf.line_3point_min_angle, "line_3point_min_angle")
```
fetchone() then create_function will be error
```
conn.create_function(attr_name, attr_value,
duckdb.duckdb.InvalidInputException: Invalid Input Error: This function can not be called with an active transaction!, commit or abort the existing one first

```
but fetchall() not error
```
    conn = duckdb.connect(database=':memory:')
    conn.execute(f"SELECT installed,loaded FROM duckdb_extensions() ;").fetchall()
    conn.create_function(CheckUdf.line_3point_min_angle, "line_3point_min_angle")
```

### OS:

MACOS

### DuckDB Version:

1.0.0

### DuckDB Client:

python

### Full Name:

s

### Affiliation:

l

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Fetchone() creates a stream, an active query execution which is wrapped in a transaction.

Perhaps we should just cancel the active query execution + transaction instead of letting this fail
