### ISSUE TITLE
JSON_EXTRACT and similar functions don't allow for distinguishing between SQL NULL and JSON null

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#13437]
### What happens?

When a JSON document contains JSON `null` values, I cannot extract them, i.e. distinguish between the presence of a `null` value and the absence of the value.

### To Reproduce

Consider these two queries:

```sql
SELECT json '{"a":1,"b":null}'->'b';
SELECT json '[1, 2, null]'->2;
```

They should both produce `CAST('null' AS JSON)`. But they produce `CAST(NULL AS JSON)`, instead. As such, I cannot be certain if the value exists in the document at all, or not. E.g. the result is the same as for these queries, where the value is absent:

```sql
SELECT json '{"a":1,"b":null}'->'c';
SELECT json '[1, 2, null]'->3;
```

E.g. MySQL and PostgreSQL don't expose this behaviour but clearly distinguish between SQL `NULL` and JSON `null`.

A workaround seems to be to check also `JSON_TYPE`:

```sql
SELECT COALESCE(j->'b', CASE WHEN json_type(j, 'b') = 'NULL' THEN CAST('null' AS JSON) END)
FROM
  (VALUES (json '{"a":1,"b":null}')) AS j (j);
```

But that workaround doesn't work in general if the JSON path is an expression, see this related problem:

- https://github.com/duckdb/duckdb/issues/13436

I cannot think of other workarounds right now, given that most standard SQL JSON features aren't available either, including `JSON_EXISTS` or `JSON_QUERY`, etc.

At first, I thought this bug here might not be a bug, but just a limitation. But given #13436, I got sceptical

### OS:

Microsoft Windows [Version 10.0.22631.3880]

### DuckDB Version:

1.0.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pkoppstein** [comment]
I would like to describe the problem slightly differently.

First, the good news is that JSON's null and SQL's NULL are properly distinguished:
```
D SELECT ('null'::JSON  IS NULL) as check;
┌─────────┐
│  check  │
│ boolean │
├─────────┤
│ false   │
└─────────┘
D SELECT ('null'::JSON  = 'null'::JSON) as check;
┌─────────┐
│  check  │
│ boolean │
├─────────┤
│ true    │
└─────────┘
```

The problem seems in essence with `json_extract()`:
```
D SELECT (('{"a":null}'::JSON -> '.[a]') IS NULL);
┌────────────────────────────────────────────────────┐
│ ((CAST('{"a":null}' AS "JSON") -> '.[a]') IS NULL) │
│                      boolean                       │
├────────────────────────────────────────────────────┤
│ true                                               │
└────────────────────────────────────────────────────┘
D SELECT (('{"a":null}'::JSON ->> '.[a]') IS NULL);
┌─────────────────────────────────────────────────────┐
│ ((CAST('{"a":null}' AS "JSON") ->> '.[a]') IS NULL) │
│                       boolean                       │
├─────────────────────────────────────────────────────┤
│ true                                                │
└─────────────────────────────────────────────────────┘
D 
```

**Comment by lukaseder** [comment]
> I would like to describe the problem slightly differently.

Well, as I said in the title and in the description, I believe...? (It was all about `JSON_EXTRACT`)

**Comment by lnkuiper** [comment]
Hi @lukaseder, thanks for the bug report.

I'm a bit confused by this:
> E.g. MySQL and PostgreSQL don't expose this behaviour but clearly distinguish between SQL `NULL` and JSON `null`.

As doing this in PostgreSQL:
```sql
postgres=# SELECT '[1, 2, null]'::JSON->3;
 ?column? 
----------
 
(1 row)

postgres=# SELECT '[1, 2]'::JSON->3;
 ?column? 
----------
 
(1 row)

```
Has the exact same behavior in DuckDB:
```sql
D SELECT '[1, 2, null]'::JSON->3;
┌───────────────────────────────────────┐
│ (CAST('[1, 2, null]' AS "JSON") -> 3) │
│                 json                  │
├───────────────────────────────────────┤
│                                       │
└───────────────────────────────────────┘
D SELECT '[1, 2]'::JSON->3;
┌─────────────────────────────────┐
│ (CAST('[1, 2]' AS "JSON") -> 3) │
│              json               │
├─────────────────────────────────┤
│                                 │
└─────────────────────────────────┘
```
A SQL `NULL` is returned when the path exists, and the JSON is `null`, and if the path does not exist.

So am I right in that this issue is essentially a feature request for the `json_exists` function?

**Comment by lukaseder** [comment]
@lnkuiper JSON arrays use 0-based indexes... Try the queries from my report, e.g.

```
postgres=# select json '[1, 2, null]'->2;
 ?column?
----------
 null
(1 row)

postgres=# select json '[1, 2]'->2;
 ?column?
----------

(1 row)
```

**Comment by lukaseder** [comment]
> So am I right in that this issue is essentially a feature request for the `json_exists` function?

Well, that would be useful as well :) But I still think the behaviour here is wrong, or at least, not as useful as it could be.

**Comment by lnkuiper** [comment]
This was once changed because of https://github.com/duckdb/duckdb/issues/6779

Currently, it is impossible to overload DuckDB's `IS NULL` and `IS NOT NULL` expressions for the JSON type. Once this is possible, we should probably revert to returning a JSON `null` when extracting. For now, you will have to work around it using `json_type`, or possibly `json_exists`, but I'm not sure if that will make the next release.

**Comment by lukaseder** [comment]
> Currently, it is impossible to overload DuckDB's `IS NULL` and `IS NOT NULL` expressions for the JSON type.

Hmm, I don't think I've seen a dialect yet that implements `CAST('null' AS JSON) IS NULL` to be `TRUE`, this would be very surprising to me. It's just not the same thing, even if it's occasionally convenient. To me, this is similar as the discussion whether Oracle's ancient `'' IS NULL` behaviour is right. It's not, it's very confusing, though it's occasionally convenient...

> For now, you will have to work around it using `json_type`

I was going to, but then... https://github.com/duckdb/duckdb/issues/13436 :-)

**Comment by lnkuiper** [comment]
I've thought about this a bit, and I agree. For https://github.com/duckdb/duckdb/issues/6779, users can use a `CASE` expression to convert a JSON `null` to a SQL `NULL` and get the desired behavior. The implementation right now does not allow for distinguishing, which is necessary. I will look into fixing this.

**Comment by lukaseder** [comment]
> I've thought about this a bit, and I agree. For #6779, users can use a `CASE` expression to convert a JSON `null` to a SQL `NULL` and get the desired behavior.

Or, just `NULLIF(expr, `CAST('null' AS JSON))`...

**Comment by lnkuiper** [comment]
Closed via https://github.com/duckdb/duckdb/pull/13481
