### ISSUE TITLE
Calling read_csv on this https://www.fdic.gov/system/files/2024-07/banklist.csv crashes DuckDB

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#13456]
### What happens?

When I call read_csv on the csv file https://www.fdic.gov/system/files/2024-07/banklist.csv while passing parameters to ignore errors and store rejects, DuckDB CLIcrashes. No error is reported

With DuckDB WASM, it also crashes but I get at least an error message back:
```
Error: INTERNAL Error: Information loss on integer cast: value -3 outside of target range [0, -1]
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
    at ma.runQuery (bindings_base.ts:172:19)
    at Fo.onMessage (worker_dispatcher.ts:202:51)
    at Wc.globalThis.onmessage (duckdb-browser-eh.worker.ts:29:19)
```
after this event, any subsequent access to the duckdb instance results in 
```
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Information loss on integer cast: value -3 outside of target range [0, -1]"
    at ma.runQuery (bindings_base.ts:172:19)
    at Fo.onMessage (worker_dispatcher.ts:202:51)
    at Wc.globalThis.onmessage (duckdb-browser-eh.worker.ts:29:19)
```

### To Reproduce

```sql
SELECT * 
FROM read_csv( 'banklist.csv'
, store_rejects = true
, rejects_scan = 'reject_scans'
, rejects_table = 'reject_errors'
, rejects_limit = 0 
) LIMIT 1;
```
[banklist.csv](https://github.com/user-attachments/files/16644646/banklist.csv)
(File source: https://www.fdic.gov/system/files/2024-07/banklist.csv)

### OS:

windows 11 enterprise

### DuckDB Version:

v1.0.1-dev4226 77a322a4cc

### DuckDB Client:

Cli, WASM

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pkoppstein** [comment]
The non-breaking space on the first line, and the unusual character on the  Silicon Valley Bank" line cause the problem.

One solution would be to run `iconv` to convert the file to utf-8:
```
 iconv -f ISO-8859-1 -t utf-8 < banklist.csv > banklist-utf8.csv
```

**Comment by rpbouman** [comment]
Hi @pkoppstein, I really don't think DuckDB should crash though. All the options that instruct it to ignore errors are passed, that really ought to be enough.

**Comment by pkoppstein** [comment]
The DuckDB documentation is quite clear:
```
The CSV reader only supports input files using UTF-8 character encoding. 
```

On my macOS:
``` $ isutf8 < banklist.csv
(standard input): line 1, char 9, byte 9: Expecting bytes in the following ranges: 00..7F C2..F4.
```

**Comment by rpbouman** [comment]
> The DuckDB documentation is quite clear:

Yes it is. And this is how it should behave in case of encoding errors:

```
select *
from read_csv('C:\roland\projects\QuaQuery\files\OrderLine_v4.csv');
```

> Invalid Input Error: CSV Error on Line: 17
> Original Line:
> 100044327,300,OUTBOUND,PS-SL-INFO,LT-2,COLA - Los Alamos,,2021-07-11T00:00:00,2021-08-02T00:00:00,2021-08-10T00:00:00,2021-08-02T00:00:00,2021-08-10T00:00:00,12,EA,0,0,USD,
> Invalid unicode (byte sequence mismatch) detected.
> 
> Possible Solution: Enable ignore errors (ignore_errors=true) to skip this row
> 
>   file=C:\roland\projects\QuaQuery\files\OrderLine_v4.csv
>   delimiter = , (Auto-Detected)
>   quote = " (Auto-Detected)
>   escape = \0 (Auto-Detected)
>   new_line = Single-Line File (Auto-Detected)
>   header = false (Auto-Detected)
>   skip_rows = 0 (Auto-Detected)
>   date_format =  (Auto-Detected)
>   timestamp_format =  (Auto-Detected)
>   null_padding=0
>   sample_size=20480
>   ignore_errors=false
>   all_varchar=0
[OrderLine_v4.csv](https://github.com/user-attachments/files/16646656/OrderLine_v4.csv)

**Comment by pkoppstein** [comment]
I was able to reproduce the problem using v1.0.0 on a Mac, but not using v1.0.1-dev4226.

**Comment by szarnyasg** [comment]
I was also unable to reproduce the crash with the nightly and latest builds - I got a reasonable output:
```
┌───────────────────────────────────────┬──────────────┬─────────┬─────────┬───────────────────────────────────┬───────────┬───────┐
│                column0                │   column1    │ column2 │ column3 │              column4              │  column5  │ Fund  │
│                varchar                │   varchar    │ varchar │  int64  │              varchar              │  varchar  │ int64 │
├───────────────────────────────────────┼──────────────┼─────────┼─────────┼───────────────────────────────────┼───────────┼───────┤
│ Republic First Bank dba Republic Bank │ Philadelphia │ PA      │   27332 │ Fulton Bank, National Association │ 26-Apr-24 │ 10546 │
└───────────────────────────────────────┴──────────────┴─────────┴─────────┴───────────────────────────────────┴───────────┴───────┘
```
That said, I'll pass the issue on to Pedro to take a closer look at whether the error message can be improved in the general case.

**Comment by rpbouman** [comment]
> I was also unable to reproduce the crash with the nightly and latest builds - I got a reasonable output:

@szarnyasg, is that on windows? I just downloaded latest (nightly v1.0.1-dev4368 10ea4832d3), and there I can still reproduce it (duckdb_cli-windows-amd64).
