### ISSUE TITLE
Crash in libduckdb-src if fetching Time as int64_t like your test projects do.

### ISSUE THREAD

**Issue by einhugur** [duckdb/duckdb#1347]
In the libduckdb-src then it will plain crash if getting time by int64 like one of your test project does.

template <> int64_t Value::GetValue() const {
	if (type_.id() == LogicalTypeId::TIMESTAMP) {
		return value_.bigint;
	}
	return GetValueInternal<int64_t>();
}

Needs to be changed to the following to fix it:

template <> int64_t Value::GetValue() const {
	if (type_.id() == LogicalTypeId::TIMESTAMP || type_.id() == LogicalTypeId::TIME) {
		return value_.bigint;
	}
	return GetValueInternal<int64_t>();
}

**Comment by einhugur** [comment]
On 2nd thought then I think the error is in the example project here:

https://github.com/cwida/duckdb/blob/master/test/api/test_results.cpp

Time probably is intended to be based on int32_t, not int64_t, making the fix above not needed, and the only error being in the example project.

**Comment by hannes** [comment]
This seems to be resolved, feel free to reopen if not
