### ISSUE TITLE
Using GROUP BY ALL with conditional projection causes "Binder Error: Cannot mix aggregates with non-aggregated columns!"

### ISSUE THREAD

**Issue by thbley** [duckdb/duckdb#13470]
### What happens?

if you have a conditional projection with GROUP BY ALL,  you get `Binder Error: Cannot mix aggregates with non-aggregated columns!`

My wish would be that `group by all` could also be applied on conditional projections (if(), case when, etc.).

### To Reproduce

```
create table testgroup (id int, isB2b int, priceGross decimal(10, 2), priceNet decimal(10, 2));
insert into testgroup values (1, 2, 3, 4);

select *, if(isB2b = 1, sum(priceGross), sum(priceNet)) FROM testgroup group by all;
Binder Error: Cannot mix aggregates with non-aggregated columns!

select *, case when isB2b = 1 then sum(priceGross) else sum(priceNet) end FROM testgroup group by all;
Binder Error: Cannot mix aggregates with non-aggregated columns!

select *, case when isB2b = 1 then sum(priceGross) else 0 end FROM testgroup group by all;
Binder Error: Cannot mix aggregates with non-aggregated columns!
```

### OS:

Linux, amd64

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

CLI

### Full Name:

Thomas Bley

### Affiliation:

myself

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
The problem is that the `CASE` mixes aggregate and non-aggregate expressions. I think you need to push the case into the aggregate like so:

```sql
SELECT *, 
    SUM( IF(isB2b = 1, priceGross, priceNet)) 
FROM testgroup 
GROUP BY ALL;
```

**Comment by thbley** [comment]
in some cases it's possible to embed if into sum, but I have a few cases where it's not possible, e.g.

```
select *, if(isB2b = 1, sum(priceGross), avg(priceNet)) FROM testgroup group by all;
select *, if(isB2b = 1, sum(priceGross), 42) FROM testgroup group by all;
```

**Comment by hawkfish** [comment]
Bu the problem is the same: You have an expression that mixes aggregate and non-aggregate functions. The solutions are similar:

```sql
-- Assuming you really do want two different types of values in the same column
SELECT *, 
    COALESCE(SUM(IF(isB2b = 1 , priceGross, NULL)), AVG(IF(isB2b = 1 ,  NULL, priceNet))))
FROM testgroup
GROUP BY ALL;

SELECT *, 
    COALESCE(SUM(IF(isB2b = 1 , priceGross, NULL)), 42)
FROM testgroup
GROUP BY ALL;
```
