### ISSUE TITLE
Incorrect error message for out-of-order join conditions

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#1348]
I was experimenting with formulating graph patterns on the LDBC graph using joins in DuckDB.

I used a SQL schema consisting of 4 "edge" tables and two views that allow handling comments and posts together as messages:

```sql
create table comment_hasTag_tag(CommentId bigint not null, TagId bigint not null);
create table comment_replyOf_comment(CommentId bigint not null, ParentCommentId bigint not null);
create table comment_replyOf_post(CommentId bigint not null, ParentPostId bigint not null);
create table post_hasTag_tag(PostId bigint not null, TagId bigint not null);

create view comment_replyOf_message as
  select CommentId, ParentCommentId as ParentMessageId from comment_replyOf_comment
  union all
  select CommentId, ParentPostId as ParentMessageId from comment_replyOf_post;

create view message_hasTag_tag as
  select CommentId as MessageId, TagId from comment_hasTag_tag
  union all
  select PostId as MessageId, TagId from post_hasTag_tag;
```

I found that running the query –

```sql
SELECT count(*)
FROM message_hasTag_tag, comment_replyOf_message
JOIN comment_hasTag_tag
  ON comment_hasTag_tag.TagId = message_hasTag_tag.TagId;
```

– gives the following error even though the table `comment_hastag_tag` exists.

```console
Error: Binder Error: Referenced table "message_hastag_tag" not found!
Candidate tables: "comment_hastag_tag"
```

If we remove the `comment_replyOf_message` table from the `FROM` clause, it works (and returns 0 results as expected):

```sql
SELECT count(*)
FROM message_hasTag_tag
JOIN comment_hasTag_tag
  ON comment_hasTag_tag.TagId = message_hasTag_tag.TagId;
```

The error occurs with the latest stable (v0.2.3) and the latest upstream (2d6cf867be) versions. Please advise on how to work around this.

**Comment by hannesmuehleisen** [comment]
I think its just the error message that is off there. Try aliasing the first instance of `message_hasTag_tag` in your query.

**Comment by szarnyasg** [comment]
Indeed, the error message is incorrect but my query was also off:

This is what Postgres prints:
```console
test=# SELECT count(*)
test-# FROM message_hasTag_tag, comment_replyOf_message
test-# JOIN comment_hasTag_tag
test-#   ON comment_hasTag_tag.TagId = message_hasTag_tag.TagId;
ERROR:  invalid reference to FROM-clause entry for table "message_hastag_tag"
LINE 4:   ON comment_hasTag_tag.TagId = message_hasTag_tag.TagId;
                                        ^
HINT:  There is an entry for table "message_hastag_tag", but it cannot be referenced from this part of the query.
```

**Comment by Mytherin** [comment]
The error message seems correct to me and the behavior is as expected. The query gets parsed as:

```
CROSS_PRODUCT(message_hasTag_tag, JOIN(comment_replyOf_message, comment_hasTag_tag, comment_hasTag_tag.TagId = message_hasTag_tag.TagId))
```

i.e. the join is:

```
JOIN(comment_replyOf_message, comment_hasTag_tag, comment_hasTag_tag.TagId = message_hasTag_tag.TagId)
```

In the join condition there exists no table called `message_hasTag_tag`, since our only candidate tables are `comment_replyOf_message` and `comment_hasTag_tag`, so an error is correctly reported. Postgres reports the same error, but looks through the remainder of the query plan to look for tables of this name so it can provide this hint.

We could extend the error reporting with a similar hint if you believe that the hint is helpful. Did the hint help you fix the query or clarify the behavior of the system?

**Comment by szarnyasg** [comment]
@Mytherin thanks for the explanation! I think the hint Postgres provides is definitely helpful – I was rewriting the query from an initial variant using `WHERE` plus equality conditions to `JOIN` clauses and got confused in the process.
