### ISSUE TITLE
Joins seem broken

### ISSUE THREAD

**Issue by dioptre** [duckdb/duckdb#13492]
### What happens?

This join should return no more than 30, but returns 522.

Some columns work as expected, strings etc. but some data types not. Ex. the "Date" column.

```sql
create table t1 as select * from read_csv('covid-small.csv');
create table t2 as select * from read_csv('covid-small.csv');
select count(*) total from t1 inner join t2 on t1."Date"=t2."Date" ;
```

[covid-sample.csv](https://github.com/user-attachments/files/16694014/covid-sample.csv)

### To Reproduce

See above

### OS:

mac

### DuckDB Version:

1

### DuckDB Client:

python

### Full Name:

andrew grosser

### Affiliation:

Sourcetable

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
This is an inner join, so it returns _all_ matches. There are a lot of duplicate dates, so all pairs will be returned. By contrast, the strings are unique, so they will only match one row.
