### ISSUE TITLE
Unexpected result when casting negative integer to `BIT`

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#13506]
### What happens?

Consider the following test case. The third query should return an empty result, as `CAST(CAST(t1.c1 AS BIT) AS INTEGER)` is evaluated to `-1` and the expression should be false. However, the query returns `-1`, which is unexpected. 

I found in PostgreSQL, the second query would be evaluated as `true`. Either the second or the third query is unexpected.

### To Reproduce

```sql
CREATE TABLE  t1( c1 INTEGER);
INSERT INTO t1(c1) VALUES (-1);

SELECT t1.c1 FROM t1; -- -1
SELECT (1 BETWEEN -1 AND CAST(CAST(t1.c1 AS BIT) AS INTEGER)) FROM t1; -- false
SELECT t1.c1 FROM t1 WHERE (1 BETWEEN -1 AND CAST(CAST(t1.c1 AS BIT) AS INTEGER));
-- Expected: empty
-- Actual: -1
```

### OS:

ubuntu 22.04

### DuckDB Version:

v0.0.1 367aa8d

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
This does return an empty result on '1.0.1-dev5078' (and likely much earlier). 0.0.1 is quite old.

**Comment by suyZhong** [comment]
I just copied the version from the DuckDB CLI. Something like this:
```
./duckdb 
v0.0.1 367aa8d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D 
```

I downloaded the nightly build through this link https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip according to the installation page. Not sure if there's a typo issue in the CLI.

**Comment by carlopi** [comment]
Thanks for raising this side quest about `v0.0.1`: discussion and fix is here https://github.com/duckdb/duckdb/pull/13730.

---

On the original issue, I have on latest nightly:
```
v1.0.1-dev5143 1e883cd4d8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE  t1( c1 INTEGER);
D INSERT INTO t1(c1) VALUES (-1);
D 
D SELECT t1.c1 FROM t1; -- -1
┌───────┐
│  c1   │
│ int32 │
├───────┤
│    -1 │
└───────┘
D SELECT (1 BETWEEN -1 AND CAST(CAST(t1.c1 AS BIT) AS INTEGER)) FROM t1; -- false
┌────────────────────────────────────────────────────────┐
│ (1 BETWEEN -1 AND CAST(CAST(t1.c1 AS BIT) AS INTEGER)) │
│                        boolean                         │
├────────────────────────────────────────────────────────┤
│ false                                                  │
└────────────────────────────────────────────────────────┘
D SELECT t1.c1 FROM t1 WHERE (1 BETWEEN -1 AND CAST(CAST(t1.c1 AS BIT) AS INTEGER));
┌────────┐
│   c1   │
│ int32  │
├────────┤
│ 0 rows │
└────────┘
```
What is the problem you are seeing?

**Comment by carlopi** [comment]
Actually solved in https://github.com/duckdb/duckdb/pull/13595
