### ISSUE TITLE
VARCHAR type casting documentation is wrong, error when try_cast BLOB to VARCHAR

### ISSUE THREAD

**Issue by arcutright** [duckdb/duckdb#13521]
From https://duckdb.org/docs/sql/data_types/typecasting#varchar

> The [VARCHAR](https://duckdb.org/docs/sql/data_types/text.html) type acts as a univeral target: any arbitrary value of any arbitrary type can always be cast to the VARCHAR type. This type is also used for displaying values in the shell.

And then when I try to cast invalid utf-8 to VARCHAR (it's a byte array, it isn't a string), I get an error

```python
conn = duckdb.connect('file.duckdb')
conn.execute("SET GLOBAL sqlite_all_varchar = true;") # needed to avoid a bug where it refuses to cast "" to null for a different nullable float column in sqlite
conn.execute("INSTALL sqlite; LOAD sqlite;")
conn.execute("ATTACH 'file.sqlite' as _sqlite (TYPE sqlite);")
conn.execute("CREATE TABLE mytable (data VARCHAR)") # data is a BLOB column in sqlite
# ... later
conn.execute("INSERT INTO mytable SELECT TRY_CAST(data as VARCHAR) FROM _sqlite.mytable")

duckdb.duckdb.InvalidInputException: Invalid Input Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update
```

2 problems here:
- typecasting doc should say `VARCHAR` is limited to valid utf-8, not a universal target
- `TRY_CAST(x as VARCHAR)` shouldn't throw an error

**Comment by szarnyasg** [comment]
Hi @arcutright thanks for opening this issue. Can you please provide a minimal working example that triggers the `try_cast` error?

**Comment by rpbouman** [comment]
Might be duplicate? https://github.com/duckdb/duckdb/issues/13097

**Comment by szarnyasg** [comment]
Likely a duplicate, closing for now.
