### ISSUE TITLE
string_agg() with "order by" can't join by "_"

### ISSUE THREAD

**Issue by fengchutadie** [duckdb/duckdb#13520]
### What happens?

`string_agg(DISTINCT kind order by kind, '_') `
for this code, it could not by joined "_",
for example, if kind is ['A', 'B', 'C'], result would not be A_B_C, but A,B,C.

`string_agg(DISTINCT kind, '_') `
if delete "order by kind", it works well, and result is A_B_C

### To Reproduce

```py
import duckdb
import pandas as pd

data = {
    "kind": ["A", "B", "A", "C", "B", "D", "A"],
    "year": [2020, 2020, 2021, 2021, 2021, 2020, 2022],
    "score": [10, 15, 20, 10, 25, 30, 18]
}

df = pd.DataFrame(data)

con = duckdb.connect()
con.execute("CREATE TABLE my_table AS SELECT * FROM df")

result = con.execute("""
    SELECT
        year,
        string_agg(DISTINCT kind order by kind, '_') AS kinds,
        MAX(score) AS max_score
    FROM my_table
    GROUP BY year
""").fetchdf()

print(result)

con.close()
```

### OS:

x64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Cong Ma

### Affiliation:

individual

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@fengchutadie thanks! I could reproduce it with SQL-only code:

```sql
CREATE TABLE my_table AS
    SELECT kind, year, score
    FROM (VALUES
        ('A', 2020, 10),
        ('B', 2020, 15),
        ('A', 2021, 20),
        ('C', 2021, 10),
        ('B', 2021, 25),
        ('D', 2020, 30),
        ('A', 2022, 18),
    ) t(kind, year, score);

SELECT
    year,
    string_agg(DISTINCT kind, '_') AS kinds,
    MAX(score) AS max_score
FROM my_table
GROUP BY year;

SELECT
    year,
    string_agg(DISTINCT kind order by kind, '_') AS kinds,
    MAX(score) AS max_score
FROM my_table
GROUP BY year;
```

**Comment by Mytherin** [comment]
Thanks for the report!

This is not a bug - `ORDER BY` needs to come after **all** of the arguments to a function. In your example you are executing `string_agg(distinct kind)` with an `ORDER` modifier that orders on two expressions: `kind, '_'`. `string_agg` with a single parameter uses `,` as the delimiter.

The correct syntax for what you intent here is `string_agg(DISTINCT kind, '_' ORDER BY kind)`.

That being said - perhaps we can throw an exception here when ordering by a string literal as I agree this is confusing.
