### ISSUE TITLE
Regression: query that runs instantly on GA release hangs indefinitely on the last few nightlies

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#13525]
### What happens?

A query of moderate complexity and based on small-ish datasets hangs indefinitely on the past few nighty builds. The same query finishes correctly instantly on the GA release.

### To Reproduce

```sql
  select      row_number() over ()
  ,           count(distinct upper_ch1_ch2) over()::int  as num_bigrams
  ,           sum(count_ch1_ch2) over ()            as bigram_count_all
  ,           count_ch1_ch2 / bigram_count_all         as actual_bigram_frequency
  ,           ch1.actual_frequency * ch2.actual_frequency as expected_bigram_frequency
  from        read_csv('stat_bigrams.csv')    as stat_bigrams
  inner join  read_csv('stat_stat_chars.csv') as ch1
  on          stat_bigrams.ascii_upper_ch1  = ch1.ascii_upper_ch
  inner join  read_csv('stat_stat_chars.csv') as ch2
  on          stat_bigrams.ascii_upper_ch2 = ch2.ascii_upper_ch;
```
[stat_bigrams.csv](https://github.com/user-attachments/files/16726998/stat_bigrams.csv)
[stat_stat_chars.csv](https://github.com/user-attachments/files/16726999/stat_stat_chars.csv)

### OS:

windows 11 enterprise

### DuckDB Version:

v1.0.0 1f98600c2c (duckdb_cli-windows-amd64)

### DuckDB Client:

CLI 

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, reproduced!

**Comment by rpbouman** [comment]
I have tried to peel off as much of the complexity as I could but I am at a loss to provide a clear definition of what triggers this.

I have a  few variations of the query that run as expected on both the nightly and the GA:

no1 lacks `expected_bigram_frequency` column

```
  select      row_number() over ()
  ,           count(distinct upper_ch1_ch2) over()::int  as num_bigrams
  ,           sum(count_ch1_ch2) over ()            as bigram_count_all
  ,           count_ch1_ch2 / bigram_count_all         as actual_bigram_frequency
  from        read_csv('C:\Users\Roland_Bouman\Downloads\stat_bigrams.csv')    as stat_bigrams
  inner join  read_csv('C:\Users\Roland_Bouman\Downloads\stat_stat_chars.csv') as ch1
  on          stat_bigrams.ascii_upper_ch1  = ch1.ascii_upper_ch
  inner join  read_csv('C:\Users\Roland_Bouman\Downloads\stat_stat_chars.csv') as ch2
  on          stat_bigrams.ascii_upper_ch2 = ch2.ascii_upper_ch
```

no2 lacks `row_number() over ()` expression
```
  select      count(distinct upper_ch1_ch2) over()::int  as num_bigrams
  ,           sum(count_ch1_ch2) over ()            as bigram_count_all
  ,           count_ch1_ch2 / bigram_count_all         as actual_bigram_frequency
  ,           ch1.actual_frequency * ch2.actual_frequency as expected_bigram_frequency
  from        read_csv('C:\Users\Roland_Bouman\Downloads\stat_bigrams.csv')    as stat_bigrams
  inner join  read_csv('C:\Users\Roland_Bouman\Downloads\stat_stat_chars.csv') as ch1
  on          stat_bigrams.ascii_upper_ch1  = ch1.ascii_upper_ch
  inner join  read_csv('C:\Users\Roland_Bouman\Downloads\stat_stat_chars.csv') as ch2
  on          stat_bigrams.ascii_upper_ch2 = ch2.ascii_upper_ch
```
However, a query that combines just those two columns executes instantly with expected results, so the cause is not just in combining these two columns.:
```
  select      count(distinct upper_ch1_ch2) over()::int  as num_bigrams
  ,           ch1.actual_frequency * ch2.actual_frequency as expected_bigram_frequency
  from        read_csv('C:\Users\Roland_Bouman\Downloads\stat_bigrams.csv')    as stat_bigrams
  inner join  read_csv('C:\Users\Roland_Bouman\Downloads\stat_stat_chars.csv') as ch1
  on          stat_bigrams.ascii_upper_ch1  = ch1.ascii_upper_ch
  inner join  read_csv('C:\Users\Roland_Bouman\Downloads\stat_stat_chars.csv') as ch2
  on          stat_bigrams.ascii_upper_ch2 = ch2.ascii_upper_ch

```

**Comment by szarnyasg** [comment]
For me, the no2 variant (without the window function) runs instantly on both v1.0 and the latest `main`.

**Comment by rpbouman** [comment]
> For me, the no2 variant runs instantly on both v1.0 and the latest main.

That's interesting - do you mean the other variants also show the hanging behavior? For me all these variants run instantly on both nightly and GA, that's why I'm stumped to guess what the cause might be.

**Comment by szarnyasg** [comment]
No, I was just reading too superficially. All your variants under this comment run quickly on my machine too:
> I have a few variations of the query that run as expected on both the nightly and the GA:

**Comment by hawkfish** [comment]
Thanks @rpbouman - this is a recent issue with the new window threading system and the distinct aggregate accelerator. I really appreciate that someone is testing this stuff now!

**Comment by rpbouman** [comment]
> Thanks @rpbouman - this is a recent issue with the new window threading system and the distinct aggregate accelerator. I really appreciate that someone is testing this stuff now!

Ah no worries, glad to help where I can. I suppose I ran into it because I recently started using nightlies.

**Comment by szarnyasg** [comment]
@rpbouman this should be fixed by the recent PRs – I built DuckDB from `main` (v1.0.1-dev4693 19a3247316) and the query now runs in <50 ms:

**Comment by rpbouman** [comment]
Thanks! I'll check it out.
