### ISSUE TITLE
Correlated subquery related? Failed to bind column reference "once_state2" [35.0] (bindings: {#[1.0], #[33.0]})

### ISSUE THREAD

**Issue by JakeWheat** [duckdb/duckdb#13542]
### What happens?

See the reproduction. The difference between the first query that succeeds, and the second that gives an error is only that a column is referenced in the where clause in the second query. This column is generated from a exists correlated subquery "self join".

### To Reproduce

```
$ ./duckdb 
v1.0.0 1f98600c2c
```
```sql
select version();
```
```text
┌───────────┐
│ version() │
│  varchar  │
├───────────┤
│ v1.0.0    │
└───────────┘
```
```sql
create table stuff (
      ts timestamp,
      item_id int,
      type text
    );
```
```sql
with
    unique_items as (
       select distinct item_id from stuff
    ),
    state_stuff as (
      select
        item_id,
        exists (select 1 from stuff c where s.item_id = c.item_id
                and type = 'state1') as once_state1,
        exists (select 1 from stuff c where s.item_id = c.item_id
                and type = 'state2') as once_state2
      from unique_items s)
    select * from state_stuff;
```
```text
┌─────────┬─────────────┬─────────────┐
│ item_id │ once_state1 │ once_state2 │
│  int32  │   boolean   │   boolean   │
├─────────┴─────────────┴─────────────┤
│               0 rows                │
└─────────────────────────────────────┘
```
```sql
with
    unique_items as (
       select distinct item_id from stuff
    ),
    state_stuff as (
      select
        item_id,
        exists (select 1 from stuff c where s.item_id = c.item_id
                and type = 'state1') as once_state1,
        exists (select 1 from stuff c where s.item_id = c.item_id
                and type = 'state2') as once_state2
      from unique_items s)
    select * from state_stuff where not once_state2;
```
```console
INTERNAL Error: Failed to bind column reference "once_state2" [35.0] (bindings: {#[1.0], #[33.0]})
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### OS:

x64 Debian GNU/Linux 12

### DuckDB Version:

1.0.0

### DuckDB Client:

duckdb cli

### Full Name:

Jake Wheat

### Affiliation:

n/a

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, I could reproduce this!

**Comment by kryonix** [comment]
This bug will likely be fixed with PR https://github.com/duckdb/duckdb/pull/13404. I tested it, and in my local version, both queries work.

**Comment by szarnyasg** [comment]
This is now fixed on nightly.
