### ISSUE TITLE
Support remaining LDBC SNB Interactive queries

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#1354]
Followup of #1075 and #1088.

I've attempted implementing the remaining LDBC SNB Interactive queries. Here are my notes on how it went:

* [Q1 could be formulated](https://github.com/szarnyasg/duckdb/blob/snb-interactive-queries/benchmark/ldbc/queries/interactive-complex-1.sql) but cannot be serialized:
  * It prints `Error: Not implemented Error: FIXME: unimplemented serialize` from https://github.com/cwida/duckdb/blob/b401f7e18ae24d4a999af0ebff7a2b15a4b5c1cf/src/execution/join_hashtable.cpp#L206
  * The JDBC driver also lacks array support: https://github.com/cwida/duckdb/blob/b401f7e18ae24d4a999af0ebff7a2b15a4b5c1cf/tools/jdbc/src/main/java/org/duckdb/DuckDBResultSet.java#L814-L816
* [Q13 works](https://github.com/szarnyasg/duckdb/blob/snb-interactive-queries/benchmark/ldbc/queries/interactive-complex-13.sql), I've implemented the arrays with strings (`concat` and `regexp_matches`)
* [Q14](https://github.com/szarnyasg/duckdb/blob/snb-interactive-queries/benchmark/ldbc/queries/interactive-complex-14.sql) needs the [`generate_subscripts`](https://www.postgresql.org/docs/9.1/functions-srf.html) Postgres function.

**Comment by Mytherin** [comment]
Thanks for the progress report! This is very useful to get some insights into which features we are missing :)

The Q1 failure seems related to nested types not being supported in hash joins yet. In general nested types are not supported in a lot of places; so more work to do there for sure. As for Q14, I have added `generate_subscripts` to the list of desired functions from other systems in #193.

**Comment by szarnyasg** [comment]
I have now fully implemented the LDBC SNB Interactive in DuckDB: https://github.com/ldbc/ldbc_snb_interactive/pull/199

Will optimize the queries a bit, then port them as tests to this repository.
Note: issue #2709 is related to Q14's parallel execution.
