### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by xubobbs** [duckdb/duckdb#13544]
### What happens?

create temp table with auto seq column will failed.error is like "Dependency Error: Error adding dependency for object "ds_temp_client_online_info_1" - dependency "auto_seq_ds_temp_client_online_info_1" is in catalog "preload_duckdb", which does not match the catalog "temp"."

### To Reproduce
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/marcboeker/go-duckdb"
)

var duckHandle *sql.DB
var duckHandle2 *sql.DB

type tableDef struct {
	tableName string
	sql       string
	tmpsql    string
}

func main() {
	main_test_temp_table()
	select {}
}

func initDb() {
	db, err := sql.Open("duckdb", "./preload_duckdb.db")
	if err != nil {
		fmt.Printf("open failed with err %v ===========\n", err)
		panic(err)
	}
	duckHandle = db
	db.SetMaxOpenConns(1)
}

func initDb2() {
	db, err := sql.Open("duckdb", "./preload_duckdb.db")
	if err != nil {
		fmt.Printf("open failed with err %v ===========\n", err)
		panic(err)
	}
	duckHandle2 = db
	db.SetMaxOpenConns(1)
}
func main_test_temp_table() {
	initDb()
	initDb2()
	db := duckHandle2
	fmt.Print("create table \n")
	_, e := db.Exec(test_tabel_def.sql)
	if e != nil {
		panic(e)
	}
	fmt.Print("create table ok \n")
	fmt.Print("create tmp table\n")
	_, e = db.Exec(test_tabel_def.tmpsql)
	if e != nil {
		panic(e)
	}
	fmt.Print("create tmp table ok \n")
	_, e = db.Exec(test_tabel3_def.sql)
	if e != nil {
		panic(e)
	}
	_, e = db.Exec(test_tabel3_def.tmpsql)
	if e != nil {
		panic(e)
	}
}

var test_tabel_def = tableDef{
	tableName: "test_tabel_def",
	sql:       `CREATE TABLE test_tabel_def ( _id varchar(255) NOT NULL PRIMARY KEY, client_id varchar(255) NOT NULL DEFAULT '' , asset_id bigint NOT NULL DEFAULT 0 , asset_oid bigint NOT NULL DEFAULT 0 , is_online bool, last_time bigint NOT NULL DEFAULT 0 , update_time bigint NOT NULL DEFAULT 0 , delete_at bigint NOT NULL DEFAULT 0  );`,
	tmpsql:    `CREATE TEMP TABLE temp_test_tabel_def ( _id varchar(255) NOT NULL PRIMARY KEY, client_id varchar(255) NOT NULL DEFAULT '' , asset_id bigint NOT NULL DEFAULT 0 , asset_oid bigint NOT NULL DEFAULT 0 , is_online bool, last_time bigint NOT NULL DEFAULT 0 , update_time bigint NOT NULL DEFAULT 0 , delete_at bigint NOT NULL DEFAULT 0  );`,
}

var test_tabel2_def = tableDef{
	tableName: "test_tabel2_def",
	sql:       `CREATE TABLE "ds_temp_client_meta_1" ( "auto_pk" bigint PRIMARY KEY DEFAULT NEXTVAL('auto_seq_ds_client_meta_1'), "asset_oid" bigint, "name" varchar(255), "asset_id" bigint, "client_id" varchar(64) );`,
	tmpsql:    `CREATE TEMPORARY TABLE "ds_temp_client_meta_1" ( "auto_pk" bigint PRIMARY KEY DEFAULT NEXTVAL('auto_seq_ds_temp_client_meta_1'), "asset_oid" bigint, "name" varchar(255), "asset_id" bigint, "client_id" varchar(64) );`,
}

var test_tabel3_def = tableDef{
	tableName: "test_tabel3_def",
	sql:       `CREATE SEQUENCE IF NOT EXISTS auto_seq_ds_temp_client_online_info_1;`,
	tmpsql:    `CREATE TEMPORARY TABLE "ds_temp_client_online_info_1" ( "auto_pk" bigint PRIMARY KEY DEFAULT NEXTVAL('auto_seq_ds_temp_client_online_info_1'), "last_time" bigint, "client_id" varchar(255));`,
}
```

compile it like

```bash
CGO_ENABLED=1  CGO_LDFLAGS="-L./" go build -o ducktest main.go"
```

Dependency Error: Error adding dependency for object "ds_temp_client_online_info_1" - dependency "auto_seq_ds_temp_client_online_info_1" is in catalog "preload_duckdb", which does not match the catalog "temp".
Cross catalog dependencies are not supported

### OS:

linux

### DuckDB Version:

latest

### DuckDB Client:

go

### Full Name:

bo,xu

### Affiliation:

qianxin.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @xubobbs, thanks for opening this issue. To fix this issue, we need to understand it better:
1) Does this issue occur in the DuckDB CLI client without using the Go API?
2) Can you please format your code using triple backtick blocks, such as

    ````
    ```sql
    ...
    ```
    ````

**Comment by xubobbs** [comment]
format it use "```" , and the demo code seems look ok .copy libduck.a in the worksapce and this can reproduct it.
thanks

**Comment by Tishj** [comment]
Very related to #13543 
Your sequence was not created in the temp catalog, so it cant be found/referenced by the temp table

**Comment by xubobbs** [comment]
I look into https://github.com/duckdb/duckdb/issues/13543, but I still don't know  what I should do to make the code work ?
