### ISSUE TITLE
"INTERNAL Error: Failed to drop entry ... - could not find entry" and inappropriate invalidation of database

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#13540]
### What happens?

To reproduce:

1) Download and unzip the "well-known" SQLite database at https://www.kaggle.com/datasets/hugomathien/soccer

2) Assuming database.sqlite is in the pwd invoke duckdb and execute the program shown below.

The "INTERNAL Error" message begins:

INTERNAL Error: Failed to drop entry "PlayerStatistics" - could not find entry
This error signals an assertion failure within DuckDB. 

Subsequent read-only operations result in a message:
```
FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed to drop entry "PlayerStats" - could not find entry" 
```

I understand that the SQL program is faulty (the reference to PlayerStats is interpreted as db.PlayerStats), but the error message makes no mention of db or the likelihood that a `USE` is missing); and the invalidation of the database only adds to the confusion (especially as the previous message alluded to an "INTERNAL ERROR") and seems unwarranted. 
### To Reproduce

```
LOAD sqlite;

SET GLOBAL sqlite_all_varchar = true;

ATTACH 'database.sqlite' AS db (TYPE sqlite); USE db; 

CREATE OR REPLACE VIEW PlayerStats AS
SELECT * EXCLUDE(rn, id, player_api_id, player_fifa_api_id)
FROM Player
JOIN (
    select *,
           ROW_NUMBER()
           OVER (partition by player_api_id ORDER BY date DESC) rn
    FROM Player_Attributes
) AS attrs
ON attrs.player_api_id = Player.player_api_id AND rn = 1;

```
produces:
```
INTERNAL Error: Failed to drop entry "PlayerStatistics" - could not find entry
This error signals an assertion failure within DuckDB. 
```

### OS:

MacOS

### DuckDB Version:

v1.0.0  and  v1.0.1-dev4509

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed by https://github.com/duckdb/sqlite_scanner/pull/112
