### ISSUE TITLE
Window range ending in `0 preceding` invalid result

### ISSUE THREAD

**Issue by jakkes** [duckdb/duckdb#13598]
### What happens?

Running a window function with upper limit `0 preceding` excludes the current row and produces identical results to when running with `1 preceding`.

### To Reproduce

```sql
select x, sum(x) over (order by x range between 5 preceding and 1 preceding) as y from (select unnest(range(10)) as x);
select x, sum(x) over (order by x range between 5 preceding and 0 preceding) as y from (select unnest(range(10)) as x);
```

![image](https://github.com/user-attachments/assets/bfc6c760-7178-4a52-bd4d-644e54c8aa0e)

These look identical. I would expect `out2` to include the current row's `x` in its sum.

### OS:

Ubuntu22.04

### DuckDB Version:

1.0.0

### DuckDB Client:

Python 3.10.12

### Full Name:

Jakob Stigenberg

### Affiliation:

Qubos

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by hawkfish** [comment]
Yes it looks like this is being clamped to 1 instead of 0. Until I fix this, the workaround is to use `CURRENT ROW` instead, but I can see that if this is being machine generated, that might not be an option.

**Comment by jakkes** [comment]
Thank you for the very quick turnaround!

**Comment by jakkes** [comment]
Will the resolvement of this issue allow for fixing https://github.com/duckdb/duckdb/issues/10885 ?

**Comment by hawkfish** [comment]
I'm afraid not - the fix was a fencepost error. I don't believe that negative offsets are even allowed.
