### ISSUE TITLE
Newly imported tables not showing

### ISSUE THREAD

**Issue by cemhany** [duckdb/duckdb#13625]
### What happens?

Hello,

Newly imported CSV files **_sometimes_** won't show up in the table list. But I am able to query the tables in question. Both CLI and duckdb node packages have the same issue.

### To Reproduce

When I import a file using the command with duckdb node package:

```sql
CREATE TABLE ${tableName} AS SELECT * FROM read_csv('${filePath}');
```

Newly created table won't show up in the list when using one of the following queries both in CLI and node package:
```sql
SHOW ALL TABLES;
SELECT * FROM information_schema.tables;
```

But I can list table content using the following query:
```sql
SELECT * FROM ${tableName};
```

### OS:

iOS

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

Node, CLI

### Full Name:

Cemhan Yaşaraşkın

### Affiliation:

Freelance

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by cemhany** [comment]
Also a similar issue here:

https://github.com/dbeaver/dbeaver/issues/34304

**Comment by szarnyasg** [comment]
Hi @cemhany, thanks for reporting this. Can you please provide a script (+ CSV file) that reproduces this in the CLI (with at least some probability)?

**Comment by cemhany** [comment]
Hey, thanks for the response. I'll look into it on the weekend.
