### ISSUE TITLE
Date Difference Discrepancy in DuckDB

### ISSUE THREAD

**Issue by arifsaslam** [duckdb/duckdb#13629]
### What happens?

There appears to be a discrepancy in the way DuckDB calculates the difference between two dates in weeks compared to SQL Server.
When calculating the difference in weeks between '2023-01-22 05:30:00+05:30' and '2024-09-13 05:30:00+05:30', the expected result is 85 weeks, as observed in SQL Server. DuckDB returns 86 weeks for the same calculation.

### To Reproduce

SQL Server
```sql
SELECT DATEDIFF(week, CAST('2023-01-22 05:30:00+05:30' AS DATETIMEOFFSET), CAST('2024-09-13 05:30:00+05:30' AS DATETIMEOFFSET));
```
```
Result: 85
```
DuckDB
```sql
SELECT date_diff(
    'WEEK',
    '2023-01-22 05:30:00+05:30'::timestamptz,
    '2024-09-13 05:30:00+05:30'::timestamptz
) AS column;
```
```
Result: 86
```

Questions

1. Is this difference in behavior expected?
2. If not, can DuckDB's behavior be made compatible with SQL Server?
3. If it is expected, could you please explain the reasoning behind DuckDB's calculation method?

Note: Timezone is `Asia/Kolkata`

### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

1.0

### DuckDB Client:

python

### Full Name:

Arif Aslam

### Affiliation:

Mammoth Analytics Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
No this is a bug. Shouldn't' be hard to fix though.

**Comment by hawkfish** [comment]
OK the problem is that MS-SQL uses a specific convention for `date_diff` for every other date part _except_ weeks. That convention is that it counts period boundary crossings (e.g., the first of the month). What they do for weeks is just divide the number of days by 7 and round down. This is what our `date_sub('week', ...)` function does. 

Incidentally, this has nothing to do with ICU - regular dates do the same thing.
