### ISSUE TITLE
query hangs forever using views, completes immediately with equivalent tables

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#13657]
### What happens?

This code never finishes:

```python
import duckdb

create_tables = False
con = duckdb.connect()
con.sql("CALL dsdgen(sf=0.01)")
con.sql("COPY store_sales TO 'store_sales.parquet'")
con.sql("COPY customer_demographics TO 'customer_demographics.parquet'")
cd = con.read_parquet("customer_demographics.parquet")
ss = con.read_parquet("store_sales.parquet")

if create_tables:
    ss.create("ss")
    cd.create("cd")
else:
    ss.create_view("ss")
    cd.create_view("cd")

sql = """
SELECT
  t3.cd_marital_status
FROM ss AS t2
JOIN cd AS t3
  ON ss_cdemo_sk = cd_demo_sk
JOIN cd AS t4
  ON t3.cd_marital_status <> t4.cd_marital_status
LIMIT 1
"""

print("starting query")

result = con.sql(sql)
result = result.arrow()
assert len(result) == 1
```

Additionally it starts to create an enormous `.tmp` directory that doesn't stop growing.

If I replace all the `read_parquet` calls with equivalent tables created with `CREATE TABLE` the query finishes immediately. Setting `create_tables = True` does that in the example.

### To Reproduce

```python
import duckdb

create_tables = False
con = duckdb.connect()
con.sql("CALL dsdgen(sf=0.01)")
con.sql("COPY store_sales TO 'store_sales.parquet'")
con.sql("COPY customer_demographics TO 'customer_demographics.parquet'")
cd = con.read_parquet("customer_demographics.parquet")
ss = con.read_parquet("store_sales.parquet")

if create_tables:
    ss.create("ss")
    cd.create("cd")
else:
    ss.create_view("ss")
    cd.create_view("cd")

sql = """
SELECT
  t3.cd_marital_status
FROM ss AS t2
JOIN cd AS t3
  ON ss_cdemo_sk = cd_demo_sk
JOIN cd AS t4
  ON t3.cd_marital_status <> t4.cd_marital_status
LIMIT 1
"""

print("starting query")

result = con.sql(sql)
result = result.arrow()
assert len(result) == 1
```

### OS:

Linux

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by cpcloud** [comment]
So, the script eventually finishes, so perhaps "never finishes" isn't quite correct.

I think it's strange though that the parquet version is so much slower than the native version:

- Native: 0.3s
- Parquet: 34s

100x difference seems pretty rough :)

Bumping up the scale factor to 0.1 things start to go haywire (and the massive `.tmp` directory gets created):

- Native: 0.3s
- Parquet: ? (still waiting on this to finish, up to 174GB of `.tmp` now)

**Comment by cpcloud** [comment]
Well with `sf=0.1`, I got this error message eventually:

```
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: failed to offload data block of size 256.0 KiB (791.4 GiB/791.4 GiB used).
```

**Comment by szarnyasg** [comment]
Hi Phillip, thanks for opening this. Did you try it on the latest nightly build (`pip install duckdb --pre --upgrade`)?

```bash
$ time python my.py
```
```console
starting query
python3.11 my.py  0.97s user 0.22s system 245% cpu 0.484 total
```

**Comment by cpcloud** [comment]
Excellent, seems to fixed on nightly. 🎉 

Any idea what the fix was?
