### ISSUE TITLE
Behavior change between 0.2.3 and 0.2.4,  unable to completely shutdown duckdb in Java

### ISSUE THREAD

**Issue by Baoqi** [duckdb/duckdb#1365]
I'm working on a ETL tool to manipulate data in both Java & Python.  Java is the main program, and it will launch Python sub-process when necessary. And Java and Python will share the same duckdb data folder.

The work flow is as following:
  1. In Java program, I first create a new DuckDBDatabase , and reuse it all the time.
  2. When I encounter Python script, then, I will first close the DuckDBDatabase,  By call DuckDBDatabase's .shutdown() function in Java.
  3. Then, Java will launch Python program, and Python side will manipulate the same duckdb folder
  4. Finally, when Python program exist, Java side can continue to re-open duckdb in Java side.

This works fine in 0.2.3 release,  but when I update to 0.2.4, it stop to work:  when "step 3", when Python side try to open duckdb folder,  it will error with:

>     duckdb_connection = duckdb.connect(database='20210204_165520.612/duckdb', read_only=False)
> RuntimeError: IO Error: Could not set lock on file "20210204_165520.612/duckbd.wal": Resource temporarily unavailable

Seems it is related with:

  - https://github.com/cwida/duckdb/commit/59ca2a9a064f4d0c39900d3f311d53ded27fe83b#diff-d03371961a89203317886e42b3e6c034c493599244cb6a177195049a54ed9661
  - https://github.com/cwida/duckdb/commit/eb9f257f14a9266d6409e6a9563fb932055b8b0c#diff-d03371961a89203317886e42b3e6c034c493599244cb6a177195049a54ed9661

But I don't know why, can we support to close duckdb completely as before. Thanks a lot.

**Comment by hannes** [comment]
Closed in favour of  #1683
