### ISSUE TITLE
product of unnested array versus not unnested array give very different answers

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#13666]
### What happens?

Two queries that I would expect to give the same answer give different results:

```sql
SELECT product(a) FROM UNNEST(RANGE(1, 11)) _ (a)
```

should produce the same answer as

```sql
SELECT product(a) FROM RANGE(1, 11) _ (a)
```

### To Reproduce

```python
import duckdb

first_sql = "SELECT product(a) FROM UNNEST(RANGE(1, 11)) _ (a)"
second_sql = "SELECT product(a) FROM RANGE(1, 11) _ (a)"

first_answer = duckdb.execute(first_sql).fetchone()[0]
second_answer = duckdb.execute(second_sql).fetchone()[0]

assert first_answer == second_answer, f"{first_answer} != {second_answer}"
```

produces

```
❯ python test.py
Traceback (most recent call last):
  File "/home/cloud/src/github.com/ibis/test.py", line 11, in <module>
    assert first_answer == second_answer, f"{first_answer} != {second_answer}"
AssertionError: 8.173669102896943e+209 != 3628800.0
```

### OS:

Linux

### DuckDB Version:

1.0.1-dev5058

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Already:

``` sql
SELECT sum(a) FROM UNNEST(RANGE(1, 2)) _ (a);
8
```
vs
``` sql
SELECT sum(a) FROM RANGE(1, 2) _ (a);
1
```
shows the problem, somewhere something goes wrong an the Table scan on UNNEST(RANGE(1,2)) shows 8 columns (via `EXPLAIN ANALYZE`).

This has to be a regression, duckdb v1.0.0 works as expected, only recent (how recent) nightly branches have this.

**Comment by cpcloud** [comment]
The version I used is `1.0.1-dev5058` which is the latest nightly from PyPI:

![image](https://github.com/user-attachments/assets/558f8f14-1c3d-43c2-ad70-dce2762f952c)

**Comment by cpcloud** [comment]
Did a bisect, looks like this commit is the first bad commit according to git:

```
❯ git bisect good
9c622efb4b2ed06cfa58580b90196e1257dbe2d6 is the first bad commit
commit 9c622efb4b2ed06cfa58580b90196e1257dbe2d6
Date:   Fri Jun 7 10:49:43 2024 +0200

    Add cardinality estimation back for range function with constant parameters by reverting back to old binding method when parameters are all scalar
```

**Comment by cpcloud** [comment]
Spelunking around a bit, it looks like `range` is an `in_out_function` and the check for scalar expressions that was introduced in that commit short circuits before detecting that.

**Comment by pkoppstein** [comment]
Just to be clear, the bug surfaces when UNNEST is used in the FROM clause.

When `unnest` is used in the SELECT clause, the results are as expected:
```
SELECT product(a) FROM (select UNNEST(RANGE(1, 11)) as a);
┌────────────┐
│ product(a) │
│   double   │
├────────────┤
│  3628800.0 │
└────────────┘
```

But when the UNNEST occurs in the FROM clause, recent versions of DuckDB get confused.

On the one hand, as expected, we see:
```
select * FROM unnest(RANGE(1, 3)) as t(a);
┌───────┐
│   a   │
│ int64 │
├───────┤
│     1 │
│     2 │
└───────┘
```
but:
```
select product(a) FROM unnest(RANGE(1, 3)) as t(a);
┌────────────┐
│ product(a) │
│   double   │
├────────────┤
│       16.0 │
└────────────┘
```

**Comment by Mytherin** [comment]
Thanks for the report! I have a fix up in https://github.com/duckdb/duckdb/pull/13689 - the issue is related to the same task being incorrectly scheduled on multiple threads, causing duplicate rows to be produced.
