### ISSUE TITLE
Wrong number of results when calling a MACRO that calls a scalar function

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#13664]
### What happens?

```sql
create or replace function rnv(a,b) as (select a + b * pi());
select rnv(0, 1) from unnest( range(0,2) );
```
```
┌───────────────────┐
│     rnv(0, 1)     │
│      double       │
├───────────────────┤
│ 3.141592653589793 │
│ 3.141592653589793 │
│ 3.141592653589793 │
│ 3.141592653589793 │
│ 3.141592653589793 │
│ 3.141592653589793 │
│ 3.141592653589793 │
│ 3.141592653589793 │
└───────────────────┘
```

Note: this is similar to one of the problems reported at #13639, but here random() is not called at all.

### To Reproduce

```
create or replace function rnv(a,b) as (select a + b * pi());

select rnv(0, 1) from unnest( range(0,2) );
```

### OS:

macOS

### DuckDB Version:

v1.0.1-dev5058 (August 30)

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pkoppstein** [comment]
@ mytherin - thanks, especially for the responsiveness. It’s rather disappointing that an easy-to-check cardinality violation wasn’t caught earlier in the development process, or even at runtime.  Shouldn’t there be various types of assertion mechanisms at work to guard against and/or flag cardinality errors?

**Comment by Mytherin** [comment]
This issue was caused by a table function (unnest) returning more rows than expected - there is no "easy-to-check" cardinality violation here at the system level, as you do not know how many rows a table function should return in the first place.

**Comment by pkoppstein** [comment]
@mytherin - So a run-time assertion-style warning might be the best option.  

Incidentally, the other problem originally associated with this issue has not yet been resolved:
```
duckdb < rnv-2.sql
┌────────────────┐
│  "version"()   │
│    varchar     │
├────────────────┤
│ v1.0.1-dev5122 │
└────────────────┘
┌──────────────────────┐
│      rnv(0, 1)       │
│        double        │
├──────────────────────┤
│ -0.21754466146294435 │
│ -0.21754466146294435 │
└──────────────────────┘
(venv) peter:~/duckdb$ cat rnv-2.sql
cat rnv-2.sql
select version();

create or replace function rnv(mean, sd) as 
  (select ( sqrt(-2 * ln(random())) * cos(2 * pi() * random()) * sd) + mean);

create or replace table t as
  select rnv(0, 1) from unnest(range(0,2));

from t;
```

Thanks.
Thanks.

**Comment by Mytherin** [comment]
> So a run-time assertion-style warning might be the best option

And what do you envision such an assertion to check?

> Incidentally, the other problem originally associated with this issue has not yet been resolved:

Thanks, I'll re-open the other issue.

**Comment by pkoppstein** [comment]
@mytherin asked
> what do you envision such an assertion to check?

For the SELECT _ FROM _ part of the query, whatever cardinality constraints can be readily inferred.  Presumably if the FROM part generates n rows, and the SELECT part is purely functional, then the result should have n rows.  

If the runtime costs of such checing is deemed unacceptable, then an option to issue run-time warnings would be welcome.  Or is it already available?

**Comment by Mytherin** [comment]
> For the SELECT _ FROM _ part of the query, whatever cardinality constraints can be readily inferred. Presumably if the FROM part generates n rows, and the SELECT part is purely functional, then the result should have n rows.

The bug here was that the `FROM` part generated too many rows due to an issue in the `UNNEST` function, so that would not detect this issue.

**Comment by pkoppstein** [comment]
@Mytherin  - The original post in this thread was about the pair of lines:
```
create or replace function rnv(a,b) as (select a + b * pi());
select rnv(0, 1) from unnest( range(0,2) );
```
I would have hoped that at runtime, the FROM clause would have yielded the expectation of 2 results, since the SELECT clause involves only "scalars" (no unnestings).  I could image, though, that at compile-time, an "assertion" could be generated for generation at run-time.

(In using the word "assertion" here, I do not mean to imply that an assertion failure would imply program termination.)
