### ISSUE TITLE
Does DuckDB support "Create or Replace Function" kind UDF? 

### ISSUE THREAD

**Issue by alitrack** [duckdb/duckdb#1374]
thanks.

**Comment by hannesmuehleisen** [comment]
We do support Macro-style functions, see #1129. Does this address your use case?

**Comment by jdf-id-au** [comment]
I wonder whether @alitrack meant support for the syntax `CREATE OR REPLACE MACRO macro_name ...`, which would match what's avaliable for `VIEW`. I think it'd be nicer than `DROP` followed by `CREATE`.

**Comment by seajhawk** [comment]
@jdf-id-au - What timing! I was just looking for exactly what you described. 

Since it appears that it doesn't exist, I'll go ahead and use the `DROP` ... `CREATE` syntax, but I wouldn't want to use that on a database with multiple apps talking to it for fear of hitting a race condition.

**Comment by Mytherin** [comment]
CREATE OR REPLACE is just syntactic sugar for DROP and CREATE happening in the same transaction. Transaction isolation (as part of ACID) should prevent any race conditions as long as it is happening in the same transaction.

**Comment by seajhawk** [comment]
That makes sense. Thanks!
