### ISSUE TITLE
DuckDB returns different results on different OS

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#13746]
### What happens?

When running a simple statement on different OS Linux, Windows and MacOS the result can differ.
This frustrates unit tests.

### To Reproduce

```sql
SELECT ARRAY_DISTINCT(['A', 'A', 'B', NULL, NULL]) AS arr;
```

On my Linux and GitHub Linux, reliably I will get:
```
[B, A]
```

On my Windows VM and GitHub Windows, reliably I will get:
```
[A, B]
```

Although I have experimented already with all kind of configurations:
```java
        Properties info = new Properties();
        info.put("old_implicit_casting", "true");
        info.put("default_null_order", "NULLS FIRST");
        info.put("default_order", "ASC");
        info.put("memory_limit", "1GB");
        info.put("threads", "1");
```

### OS:

Any

### DuckDB Version:

1.0

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
This is expected, there is some non-deterministic behavior around parallelism and hashing, which happens here.

**Comment by manticore-projects** [comment]
Thank you for the feedback.
I get your point, but it is really difficult to catch this reliably on the user's side and the impact can be quite big. Imagine a developer on one OS, testing successfully and then deploying to another OS. Both the rocket and the stock market can crash from this.

Especially when using Java/Python/R this will become even more pronounced because we simple minded developers don't think about different OSes but would expect same outcome.

**Comment by manticore-projects** [comment]
At least with `threads=1` option in place I would have hoped for reliable outcomes.

**Comment by manticore-projects** [comment]
Thank you again for your feedback and time. Your explanations are sound and clear and the `list_sort` works of course. Furthermore I can amend my Unit Tests and compare Arrays by elements, instead by string representation.

However, from a Java Developpers perspective I still would like to recommend a big exclamation mark on the functions which are non-deterministic. "Shuffled" and "Shuffled differently depending on the OS" are still not the same (at least for Java/Python/R guys). Also, I don't know of any other RDBMS having a similar behavior, so good expectation management may help.

All the best and thanks again, we can close this issue.
