### ISSUE TITLE
Unexpected result after creating index on varchar column

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#13785]
### What happens?

Consider the following test case. The third query is unexpected as it falsely returns an empty table. The second query shows that the expression `t0.c0<='a'` is true for all the rows and thus the third query should return `'a', 'a'`. 

I could reproduce it on both nightly build v1.0.1-dev5272 4d18b9d05c and source build v1.0.1-dev5276 0e6dacd893. Things go well on stable release v1.0.0 1f98600c2c.

### To Reproduce

```sql
DROP TABLE IF EXISTS t0;

CREATE  TABLE  t0(c0 VARCHAR);
INSERT INTO t0(c0) VALUES ('a');
CREATE INDEX t0i0 ON t0(c0 );
INSERT INTO t0(c0) VALUES ('a');

SELECT * FROM t0; -- 'a', 'a'
SELECT ((t0.c0)<=('a')) FROM t0; -- true, true
SELECT * FROM t0 WHERE ((t0.c0)<=('a'));
-- Expected: 'a', 'a'
-- Actual: empty table
```

### OS:

ubuntu 22.04

### DuckDB Version:

v1.0.1-dev5272 4d18b9d05c

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@suyZhong thanks, I could reproduce the issue!
