### ISSUE TITLE
normalize_names does not work properly with `/dev/stdin`

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb#13794]
### What happens?

Hi,
if I apply `normalize_names` to `/dev/stdin` duckdb normalizes the field `text` to `_text`.

It should remain `text`.

### To Reproduce

To reproduce

```
printf "name,text\nJohn,ipsum\n" | duckdb -line -c "select * from read_csv_auto('/dev/stdin',normalize_names=true);"
```

It gives in output

```
_name = John
_text = ipsum
```

### OS:

Debian 12

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

cli

### Full Name:

Andrea Borruso

### Affiliation:

onData

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@aborruso Indeed, I can reproduce this very easily. Thanks!

**Comment by pdet** [comment]
This is expected behavior.

The `normalize_names=true` also normalizes CSV column names from words used in the parser.

e.g., (`SELECT`, `JOIN`, `INSERT`, `TEXT`,...)

**Comment by aborruso** [comment]
> This is expected behavior.

And why does it normalize `text` to `_text`? `text` does not need any normalization.

**Comment by pdet** [comment]
> > This is expected behavior.
> 
> And why does it normalize `text` to `_text`? `text` does not need any normalization.

Text is a type https://www.postgresql.org/docs/current/datatype.html

**Comment by pdet** [comment]
I'm not opposed to making the matching more restrictive to `PG_KEYWORD_RESERVED`; I wonder if @Mytherin has a stronger opinion here.

**Comment by Mytherin** [comment]
I think we should only normalize keywords that cannot be used as regular column names, i.e.:

```sql
select * from duckdb_keywords() where keyword_category in ('reserved', 'type_function') order by all;
```

**Comment by pdet** [comment]
> I think we should only normalize keywords that cannot be used as regular column names without quotes, i.e.:
> 
> ```sql
> select * from duckdb_keywords() where keyword_category in ('reserved', 'type_function') order by all;
> ```

Alright-o, since the words in this issue are `PG_KEYWORD_UNRESERVED`, that should also solve this.

**Comment by aborruso** [comment]
Thank you very much!
