### ISSUE TITLE
TransactionContext Error: Failed to commit: DistinctStats called without distinct_stats

### ISSUE THREAD

**Issue by lujjjh** [duckdb/duckdb#13803]
### What happens?

After upgrading DuckDB to version 1.0.1-dev, I encountered an error when trying to insert data into certain tables in an existing database. The error message was:

> TransactionContext Error: Failed to commit: DistinctStats called without distinct_stats

I was able to reproduce the issue with DuckDB built from the main branch as well. After performing a bisect on the builds, I found that the issue was introduced by #13489. The suspicious code seems to be:

https://github.com/duckdb/duckdb/blob/10a018a5b9c34840c02db906a604745258867f55/src/storage/table/row_group_collection.cpp#L414-L421

I attempted the following changes to the code:

```diff
	for (idx_t col_idx = 0; col_idx < types.size(); col_idx++) {
 		auto &global_stats = stats.GetStats(*global_stats_lock, col_idx);
 		if (!global_stats.HasDistinctStats()) {
 			continue;
 		}
 		auto &local_stats = state.stats.GetStats(*local_stats_lock, col_idx);
+		if (!local_stats.HasDistinctStats()) {
+			continue;
+		}
 		global_stats.DistinctStats().Merge(local_stats.DistinctStats());
```

After applying this modification, the issue disappeared, but I am not sure if this change is entirely correct or appropriate.

### To Reproduce

I'm not entirely sure how to reproduce this issue from scratch, but I can provide an existing database file to help replicate the problem.

1. Open test.duckdb using the DuckDB CLI built from the main branch.
2. Execute: `INSERT INTO foo (id) VALUES (1);`

[test.duckdb.zip](https://github.com/user-attachments/files/16910892/test.duckdb.zip)

### OS:

x86_64

### DuckDB Version:

v1.0.1-dev5286 d454d24586

### DuckDB Client:

Python

### Full Name:

Jiahao Lu

### Affiliation:

Independent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
Hi @lujjjh, thanks for reporting this and proposing the workaround. @Mytherin implemented the fix recently in #13806 and the latest main now doesn't exhibit the issue:

```text
v1.0.1-dev5313 64bacde85e
Enter ".help" for usage hints.
D INSERT INTO foo (id) VALUES (1);
Run Time (s): real 0.009 user 0.001855 sys 0.004359
```
