### ISSUE TITLE
"Table with name [...] does not exist" when reading file that exists

### ISSUE THREAD

**Issue by bertday** [duckdb/duckdb#13805]
### What happens?

Trying to read a zipped CSV file and getting an error that the file doesn't exist. I've verified it exists.

### To Reproduce

I'm trying to read a zipped CSV file from the DuckDB shell:

```
D select count(*) from '~/03nov2023.csv.zip';
```

but getting an error:

```sh
Catalog Error: Table with name ~/03nov2023.csv.zip does not exist!
Did you mean "temp.information_schema.schemata"?
LINE 1: select count(*) from '~/03nov2023.csv.zip';
```

I suspect that DuckDB may not like my ZIP file (or may not decompress ZIP files at all); if that's the case, I think the error message could be tweaked to say something like "DuckDB does not decompress ZIP files" rather than "the file doesn't exist". I'm new to the project, but happy to help contribute in any way I can 😄 

### OS:

macOS 14.4.1 M1 (arm64)

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

DuckDB shell

### Full Name:

Robert Martin

### Affiliation:

Robert Martin

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
The issue here is that `from 'file.csv.zip'` does not trigger the replacement scan that transforms to `from read_csv('file.csv.zip')` as the file extension isnt recognized

That might be fixed on 1.1.0 as work was recently done on this logic iirc

**Comment by bertday** [comment]
Thanks for the quick and helpful answer @Tishj!

Just to clarify, does DuckDB not perform ZIP decompression?

**Comment by djouallah** [comment]
@bertday no unfortunately :(

**Comment by bertday** [comment]
That's helpful to know. Thank you @djouallah 😄

**Comment by Mytherin** [comment]
With https://github.com/duckdb/duckdb/pull/13871 this now throws a more helpful error message
