### ISSUE TITLE
Unexpected result when using `IN` with `TIME` values

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#13813]
### What happens?

Consider the following test cases. The second query should return `true` since the value after casting is `12:34:56` and the IN expression should be evaluated to true. Besides, if the `false` is expected, its negation query should not be evaluated as `false`.

### To Reproduce

```sql
DROP TABLE IF EXISTS t1;
CREATE   TABLE  t1(c0 TIME WITH TIME ZONE);
INSERT INTO t1(c0) VALUES ('12:34:56');

SELECT t1.c0 FROM t1; -- 12:34:56+08

SELECT (CAST(t1.c0 AS TIME) IN ('12:34:56')) FROM t1; -- false (unexpected)
SELECT NOT (CAST(t1.c0 AS TIME) IN ('12:34:56')) FROM t1; -- false

```

### OS:

ubuntu 22.04

### DuckDB Version:

v1.0.1-dev5313 64bacde85e

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, thanks for reporting this! Interestingly, it doesn't reproduce on macOS:

```sql
v1.0.1-dev5313 64bacde85e
D DROP TABLE IF EXISTS t1;
D CREATE   TABLE  t1(c0 TIME WITH TIME ZONE);
D INSERT INTO t1(c0) VALUES ('12:34:56');
D
D SELECT t1.c0 FROM t1; -- 12:34:56+08
┌─────────────────────┐
│         c0          │
│ time with time zone │
├─────────────────────┤
│ 12:34:56+00         │
└─────────────────────┘
D
D SELECT (CAST(t1.c0 AS TIME) IN ('12:34:56')) FROM t1; -- false (unexpected)
┌───────────────────────────────────────┐
│ (CAST(t1.c0 AS TIME) IN ('12:34:56')) │
│                boolean                │
├───────────────────────────────────────┤
│ true                                  │
└───────────────────────────────────────┘
D SELECT NOT (CAST(t1.c0 AS TIME) IN ('12:34:56')) FROM t1; -- false
┌───────────────────────────────────────────┐
│ (CAST(t1.c0 AS TIME) NOT IN ('12:34:56')) │
│                  boolean                  │
├───────────────────────────────────────────┤
│ false                                     │
└───────────────────────────────────────────┘
```

I will test it on Ubuntu in a moment.

**Comment by suyZhong** [comment]
Have just tested on my M2 Mac by install through this [link](https://duckdb.org/docs/installation/?version=main&environment=cli&platform=macos&download_method=direct). Looks like it's an old version (perhaps we should also update the mac install [link](https://github.com/duckdb/duckdb/actions/runs/10587966032/artifacts/1863098716)), but I could also reproduce it.
```sql
./duckdb
v1.0.1-dev4917 45787e5f9f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D DROP TABLE IF EXISTS t1;
D CREATE   TABLE  t1(c0 TIME WITH TIME ZONE);
D INSERT INTO t1(c0) VALUES ('12:34:56');
D
D SELECT t1.c0 FROM t1; -- 12:34:56+08
┌─────────────────────┐
│         c0          │
│ time with time zone │
├─────────────────────┤
│ 12:34:56+08         │
└─────────────────────┘
D
D SELECT (CAST(t1.c0 AS TIME) IN ('12:34:56')) FROM t1; -- false (unexpected)
┌───────────────────────────────────────┐
│ (CAST(t1.c0 AS TIME) IN ('12:34:56')) │
│                boolean                │
├───────────────────────────────────────┤
│ false                                 │
└───────────────────────────────────────┘
D SELECT NOT (CAST(t1.c0 AS TIME) IN ('12:34:56')) FROM t1; -- false
┌───────────────────────────────────────────┐
│ (CAST(t1.c0 AS TIME) NOT IN ('12:34:56')) │
│                  boolean                  │
├───────────────────────────────────────────┤
│ false                                     │
└───────────────────────────────────────────┘
D
```

So I guess it's about `timezone`. When I change the timezone to `UTC`, there's not issue:

```sql
SET TimeZone = 'UTC';
```

I guess you can try this:
```sql
SET TimeZone='Asia/Singapore';
```

**Comment by szarnyasg** [comment]
It's an `icu` issue! I also tried to set the timezone which failed due to `icu` not being available in my (default) build. I rebuilt DuckDB with a few core extension and now it reproduces the problem.

```bas
CORE_EXTENSIONS='autocomplete;icu;parquet;json' GEN=ninja make
```

Thanks for helping with the troubleshooting!

**Comment by hawkfish** [comment]
Yup - `BoundCastExpression::CastIsInvertible` doesn't even check.

**Comment by hawkfish** [comment]
I may be able to get to this today but I'm on a weekend trip and this is really obscure. LMK if w need it for 1.1.0

**Comment by hawkfish** [comment]
Hi @suyZhong - Thanks for the report!  

The problem is really that `TIMETZ`/`TIME WITH TIME ZONE` is not very well tested right now because almost no one uses it, partly because it was not the standards committee's finest design. I'd recommend avoiding it if you can. You are in a time zone that doesn't use Daylight Savings Time, so it might be less useless for you, but even so, sticking with full timestamps is probably more robust.

**Comment by hawkfish** [comment]
FWIW, `TIMESTAMP`, `TIMESTAMPTZ` and `TIMETZ` take 64 bits/value, so switching wouldn't even increase your storage footprint. It might even improve it as the offsets in `TIMETZ` are stored in the low 24 bits, which means that even if they are all the same (e.g., +08) any compression will likely be less efficient.

**Comment by suyZhong** [comment]
@hawkfish Thanks for your insights! I'm actually developing a testing tool that automatically integrates new features, and thus may cover some corner features.
