### ISSUE TITLE
Incorrect cast from varchar to int8

### ISSUE THREAD

**Issue by ajzo90** [duckdb/duckdb#13828]
### What happens?

Expecting EXPLAIN to show casting of `'i8'::int8` to `TINYINT` to be consistent with other shorthand casts.

### To Reproduce

```
duckdb> EXPLAIN SELECT 'i8'::int8,'i16'::int16,'i32'::int32, 'i64'::int64, 'u8'::uint8, 'u16'::uint16, 'u32'::uint32, 'u64'::uint64;
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│    CAST('i8' AS BIGINT)   │
│  CAST('i16' AS SMALLINT)  │
│   CAST('i32' AS INTEGER)  │
│   CAST('i64' AS BIGINT)   │
│   CAST('u8' AS UTINYINT)  │
│  CAST('u16' AS USMALLINT) │
│  CAST('u32' AS UINTEGER)  │
│   CAST('u64' AS UBIGINT)  │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘   
```

### OS:

iOS

### DuckDB Version:

1.1

### DuckDB Client:

CLI + web demo

### Full Name:

Christian Persson

### Affiliation:

Sift Lab

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @ajzo90, `INT8` is a shorthand to `BIGINT`, see https://duckdb.org/docs/sql/data_types/numeric

The values of `n` for `INTn` follow powers of two bits (n = 8*2^k) (INT16, INT32, INT64) or bytes (INT1, INT2, INT4, INT8).
The value 8 would be a valid choice for both the number of bits and bytes, but we can only have one, so `INT8` corresponds  to bytes.

**Comment by ajzo90** [comment]
Ah ok, thanks.
I find it quite confusing that it is inconsistent with the other short hand conversions, in particular uint8. It would likely be better to not support overlapping shorthand at all, but I understand it is hard to go back on that decision now.
