### ISSUE TITLE
duckdb1.1 crash with open file in windows 10

### ISSUE THREAD

**Issue by de1tran** [duckdb/duckdb#13864]
### What happens?

When i try to open file store in duckdb v1.0 with duckdb v1.1,the duckdb process crashed,
i try to open a new file,crash again

### To Reproduce

Microsoft Windows [版本 10.0.19044.4780]
(c) Microsoft Corporation。保留所有权利。
C:\Users\Digital>D:
D:\>cd duckdb
D:\duckdb>duckdb1.1.exe
v1.1.0 fa5c2fe15f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .open duckdb.file
D:\duckdb>

### OS:

windows 10 amd64

### DuckDB Version:

1.1.0

### DuckDB Client:

windows

### Full Name:

detran

### Affiliation:

sunline

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
@de1tran as I wrote in https://github.com/duckdb/duckdb/issues/13848#issuecomment-2343817545, this crash seems to occur when using an old version of the Microsoft Visual C++ Redistributable package.

I upgraded to the latest one from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and the problem went away.

**Comment by de1tran** [comment]
@szarnyasg thanks,it works well after upgrade Microsoft Visual C++ Redistributable package to latest
