### ISSUE TITLE
`duckdb.duckdb.InvalidInputException: Invalid Input Error: PandasScan called but GIL was already held!` on recursive python calls

### ISSUE THREAD

**Issue by pankajp** [duckdb/duckdb#13863]
### What happens?

A code previously working until duckdb 1.0.0 started erroring out in duckdb 1.1 by raising following error:

```
    res = eval(code, gs, ns)
          ^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
duckdb.duckdb.InvalidInputException: Invalid Input Error: PandasScan called but GIL was already held!
```

### To Reproduce

```
import pandas as pd
import duckdb

get_data = lambda start, N=10: pd.DataFrame({'a':range(N), 'b':[f'{i+1}' for i in range(start, start+N)]})

tab1 = get_data(65)
tab2 = get_data(66)

db = duckdb.connect()
sql = '''
create table fixed_ids as
with recursive fanout as (
    SELECT c1.a as node_id, c2.a as comp_id2,
        from tab1 c1
        inner JOIN tab2 c2 on c1.b = c2.b
        inner JOIN tab2 c2l2 on c2.a = c2l2.a
    UNION all
    SELECT fo.comp_id2 as node_id, c2l1.b as comp_id2
        FROM tab1 c1 inner JOIN fanout fo ON fo.comp_id2 = c1.a
        inner JOIN tab2 c2l1 on c1.b = c2l1.b
)
SELECT node_id, first(comp_id2)::uint64 as fixed_id from fanout group by node_id;

SELECT * from fixed_ids
'''
if 0: # Enable to run sql statement-by-statement to workaround https://github.com/duckdb/duckdb/issues/13863
    stmts = db.extract_statements(sql)
    for stmt in stmts[:-1]:
        db.execute(stmt.query)
    sql = stmts[-1].query
print(db.execute(sql).df())
```

### OS:

RH8

### DuckDB Version:

1.1.0

### DuckDB Client:

python

### Full Name:

Pankaj Pandey

### Affiliation:

Cadence

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

Tested with duckdb 1.1 release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! A reproducer would be very helpful to track this down.

**Comment by pankajp** [comment]
I have sent an inordinately long time to get a reproducible example!

1. The error happens in a recursive CTE when it it used to create a table and queried at the same time. Nothing to do with the "virtual computed table" implementation in OP (can update the description)
2. I was able to work around the error by splitting the multi-statement query into individual statements in my wrapper function:
```
import pandas as pd
import duckdb

get_data = lambda start, N=10: pd.DataFrame({'a':range(N), 'b':[f'{i+1}' for i in range(start, start+N)]})

tab1 = get_data(65)
tab2 = get_data(66)

db = duckdb.connect()
sql = '''
create table fixed_ids as
with recursive fanout as (
    SELECT c1.a as node_id, c2.a as comp_id2,
        from tab1 c1
        inner JOIN tab2 c2 on c1.b = c2.b
        inner JOIN tab2 c2l2 on c2.a = c2l2.a
    UNION all
    SELECT fo.comp_id2 as node_id, c2l1.b as comp_id2
        FROM tab1 c1 inner JOIN fanout fo ON fo.comp_id2 = c1.a
        inner JOIN tab2 c2l1 on c1.b = c2l1.b
)
SELECT node_id, first(comp_id2)::uint64 as fixed_id from fanout group by node_id;

SELECT * from fixed_ids
'''
if 0: # Enable to run sql statement-by-statement to workaround https://github.com/duckdb/duckdb/issues/13863
    stmts = db.extract_statements(sql)
    for stmt in stmts[:-1]:
        db.execute(stmt.query)
    sql = stmts[-1].query
print(db.execute(sql).df())

```

**Comment by Tishj** [comment]
Thanks for the reproduction!
Especially the detail that multiple statements are run with a single `.execute` call will be helpful and gives me a good idea of where to search for the issue 👍
