### ISSUE TITLE
Random generator gives repeated results 

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#13867]
### What happens?

random() gives repeated results even when run only 100k times and single-threaded.

In comparison, numpy gives unique results even when asked for 100M random numbers.

### To Reproduce

```sql
SET THREADS to 1;
SELECT count() FROM (SELECT DISTINCT random() AS a FROM range(100_000));
```
```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        99998 │
└──────────────┘
```

### OS:

Ubuntu22.04

### DuckDB Version:

1.1.0

### DuckDB Client:

Python3.9

### Hardware:

i5, x64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
I don't think so. Issue over there is about a specific scenario where all the numbers are the same.


I did realize, but can't check for the next four days: @szarnyasg does what I wrote produce single precision random numbers? In that case, could you verify whether the same problem exists for double precision, and if not close this issue?

For single precision numbers between 0 and 1, of which there are 2^30, the number of draws you need to get a 50% chance of a repeated number is only ~2^15=32 thousand, by the Birthday paradox. 

For double precision numbers, there are 2^62 in that range, so you'd need ~2^32=4 billion.

**Comment by soerenwolfers** [comment]
ah, that's not right, a uniform distribution doesn't pick those numbers uniformly. anyway, it's still likely the difference between single and double precision and the behavior should just be verified against numpy

**Comment by Mytherin** [comment]
Thanks for the report! I've fixed this in https://github.com/duckdb/duckdb/pull/13920 - the issue is indeed that we were using a 32-bit random generator to saturate the `double` column. Switching to a 64-bit random generator fixes the issue.
