### ISSUE TITLE
Two settings named 'http_proxy'

### ISSUE THREAD

**Issue by philleach** [duckdb/duckdb#13880]
### What happens?

There are two settings named 'http_proxy' : 

|        name         |         value         |                                       description                                        |
|---------------------|-----------------------|------------------------------------------------------------------------------------------|
| http_proxy          | 127.0.0.1:8999 | HTTP proxy host                                                                          |
| http_proxy_username |                       | Username for HTTP proxy                                                                  |
| http_proxy          |                       | Password for HTTP proxy                                                                  |
| http_logging_output |                       | The file to which HTTP logging output should be saved, or empty to print to the terminal |

### To Reproduce

```
D select name, value, description from duckdb_settings() where name like 'http%';
|        name         | value |                                       description                                        |
|---------------------|-------|------------------------------------------------------------------------------------------|
| http_proxy          |       | HTTP proxy host                                                                          |
| http_proxy_username |       | Username for HTTP proxy                                                                  |
| http_proxy          |       | Password for HTTP proxy                                                                  |
| http_logging_output |       | The file to which HTTP logging output should be saved, or empty to print to the terminal |
D set http_proxy to '127.0.0.1:8999' ;
D select name, value, description from duckdb_settings() where name like 'http%';
|        name         |         value         |                                       description                                        |
|---------------------|-----------------------|------------------------------------------------------------------------------------------|
| http_proxy          | 127.0.0.1:8999        | HTTP proxy host                                                                          |
| http_proxy_username |                       | Username for HTTP proxy                                                                  |
| http_proxy          |                       | Password for HTTP proxy                                                                  |
| http_logging_output |                       | The file to which HTTP logging output should be saved, or empty to print to the terminal |
```

### OS:

Windows 10 x86_64

### DuckDB Version:

v1.1.0 fa5c2fe15f

### DuckDB Client:

CLI

### Full Name:

Phil Leach

### Affiliation:

Bloomberg

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! Indeed it seems the password setting has gotten the wrong name. I've pushed a fix in #13890.

As a work-around you could try using the secret syntax:

```sql
CREATE SECRET http (
    TYPE HTTP, 
    http_proxy '${HTTP_PROXY_PRIVATE}',
    http_proxy_username '${HTTP_PROXY_PRIVATE_USERNAME}',
    http_proxy_password '${HTTP_PROXY_PRIVATE_PASSWORD}'
);
```
