### ISSUE TITLE
Using read_parquet crash python process when script previously imported pandas

### ISSUE THREAD

**Issue by Kuinox** [duckdb/duckdb#13910]
### What happens?

On a query using read_parquet, duckdb crash the process if pandas was imported before duckdb.

### To Reproduce

```python
import pandas as pd
import duckdb

try:
    print('pre crash')
    duckdb.sql("SELECT 1 FROM read_parquet('s3://somefile')")
except Exception as e:
    print(e)
print('post crash') # will never be printed
```

Using pandas 1.5.2.

### OS:

Windows 11, X86_64

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Full Name:

Nicolas Vandeginste

### Affiliation:

@Abc-Arbitrage

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Kuinox** [comment]
I couldn't reproduce on nightly, but I also didn't found any GitHub issue on the subject.

**Comment by szarnyasg** [comment]
Hi @Kuinox I am unable to reproduce this – is reading from S3 necessary for this or does the issue also occur with local Parquet files?

**Comment by Kuinox** [comment]
> Hi @Kuinox I am unable to reproduce this – is reading from S3 necessary for this or does the issue also occur with local Parquet files?

The snipper I provided is reproducible, you don't need a valid S3 url, it doesn't occur with local parquet.  

> @Kuinox, can you possibly try, on v1.1.0:  

This runs fine.

**Comment by Kuinox** [comment]
Ah, also mind that it doesn't reproduce with a debugger attached, this bug is a fun one ^^'.

**Comment by carlopi** [comment]
@Kuinox: I did reproduced this locally, but can't reproduce this anymore after performing `FORCE INSTALL httpfs` or the equivalent `UPDATE EXTENSIONS`.

Problem at its core is a variant of https://github.com/duckdb/duckdb/issues/13848, that can be solved by building DuckDB and DuckDB-extensions in a Windows 2019 runner instead of Windows 2022 runner.

I am not completely positive of why that's the case, I would imagine something along the lines of the fact that newer container builds artefacts that require a newer (and potentially incompatible) version of the MSVC package.

**Comment by carlopi** [comment]
I would consider this closed, since by doing:

```bash
python3 -m pip install duckdb==1.1.0 --upgrade
python3 -m pip install pandas=1.5.2 --upgrade
python3
```
```python3
import pandas as pd
import duckdb
duckdb.sql("FORCE INSTALL httpfs FROM 'path/to/broken-extensions-repository'");
duckdb.sql("select 1 from read_parquet('s3://duckdb-blobs/nl-railway/services-2023.parquet');")
```
It crashes
And doing 
```python3
import pandas as pd
import duckdb
duckdb.sql("FORCE INSTALL httpfs");
duckdb.sql("select 1 from read_parquet('s3://duckdb-blobs/nl-railway/services-2023.parquet');")
```
it works correctly (here it fetches from `http://extensions.duckdb.org`)
