### ISSUE TITLE
Unexpected result when comparing `STRUCT` with `INET`

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#13924]
### What happens?

Consider the following test case generated by my fuzzer. There should be an issue in either the second query or the third, since the second query return `NULL`, and thus the third query should return an empty table. However, one row is fetched.

I built duckdb with `CORE_EXTENSIONS='inet' GEN=ninja make`. It could also be triggered by nightly build of duckdb-java.

### To Reproduce

```sql

CREATE TABLE  t1(c0 INT, c1 INET);
INSERT INTO t1(c0, c1) VALUES (1, '192.168.1.1');

SELECT * FROM t1; -- 1 192.168.1.1
SELECT ((NULL, t1.c0, NULL)<>(t1.c1)) FROM t1; -- NULL
SELECT * FROM t1 WHERE ((NULL, t1.c0, NULL)<>(t1.c1));
-- Expected: empty
-- Actual: 1 192.168.1.1

-- original test case found by TLP
SELECT * FROM t1 WHERE ((NULL, t1.c0, NULL)<>(t1.c1)) UNION ALL SELECT * FROM t1 WHERE (NOT ((NULL, t1.c0, NULL)<>(t1.c1))) UNION ALL SELECT * FROM t1 WHERE ((((NULL, t1.c0, NULL)<>(t1.c1))) IS NULL);
-- 2 rows (unexpected)
```

### OS:

Ubuntu 22.04

### DuckDB Version:

v1.1.1-dev116 a2c119f76d

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by paultiq** [comment]
Minimizing / reproducing: 

## Original Comparison
```sql
SELECT * FROM t1 WHERE ((NULL, t1.c0, NULL)<>(t1.c1)) 
    UNION ALL 
SELECT * FROM t1 WHERE (NOT ((NULL, t1.c0, NULL)<>(t1.c1))) 
    UNION ALL 
SELECT * FROM t1 WHERE ((((NULL, t1.c0, NULL)<>(t1.c1))) IS NULL);
```

## Minimized
```
CREATE OR REPLACE TABLE  t1 as
select 1 c0, '192.168.1.1'::inet as c1;

SELECT t1.c1, 
    (NULL, t1.c0, NULL) v1, 
    (NULL, t1.c0, NULL) <> t1.c1 comp1, 
    comp1 is null comp2 
FROM t1
WHERE comp1 and comp1 is null  # comp1 is both Null and True? 
```
![image](https://github.com/user-attachments/assets/f19abdf4-0c38-4c24-85e5-12186cca823e)

The surprising part is that the condition evaluates to Null yet also is evaluating to True
