### ISSUE TITLE
read_csv fails to auto detect dates in some cases

### ISSUE THREAD

**Issue by crholm** [duckdb/duckdb#13923]
### What happens?

v1.1.0 fa5c2fe15f

Autodetect and parsing date does not honor dateformat in `read_csv` in some cases. Surrounding columns seems to play a role in the auto detection.

Tested using cli and also golang lib with same results as far as i can tell.

### To Reproduce

**Failing example**
```csv
ACCESSION_NUMBER,FILING_DATE
1-1-1A,31-OCT-2023
1-1-1B,31-OCT-2023
```

```sql
SELECT * FROM read_csv('date-failing.csv',  header=true,dateformat='%d-%b-%Y');
```
```
┌──────────────────┬─────────────┐
│ ACCESSION_NUMBER │ FILING_DATE │
│     varchar      │   varchar   │
├──────────────────┼─────────────┤
│ 1-1-1A           │ 31-OCT-2023 │
│ 1-1-1B           │ 31-OCT-2023 │
└──────────────────┴─────────────┘
```

Working example 

```csv
ACCESSION_NUMBER,FILING_DATE
1-1-A,31-OCT-2023
1-1-B,31-OCT-2023
```

```sql
SELECT *  FROM read_csv('date-succeed.csv',header=true,dateformat='%d-%b-%Y'  );
```
```
┌──────────────────┬─────────────┐
│ ACCESSION_NUMBER │ FILING_DATE │
│     varchar      │    date     │
├──────────────────┼─────────────┤
│ 1-1-A            │ 2023-10-31  │
│ 1-1-B            │ 2023-10-31  │
└──────────────────┴─────────────┘
```

### OS:

Linux

### DuckDB Version:

v1.1.0 fa5c2fe15f

### DuckDB Client:

./duckdb

### Hardware:

Intel PC

### Full Name:

Rasmus Holm

### Affiliation:

Modular Finance

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by mtstnt** [comment]
Hi maintainers, I looked into this and found out that this may be caused by the CSVSniffer not recognizing the types correctly.

Can I try to work on this one?

![image](https://github.com/user-attachments/assets/97499808-4ff2-48a8-96b2-221e1c63724f)

**Comment by pdet** [comment]
Hi @mtstnt, thank you for offering to contribute to this issue; this is highly appreciated, and we are very much open to contributions. However, I think it would be best for this specific issue to be tackled internally because we will have a [bug-fix release](https://duckdb.org/docs/dev/release_calendar.html) in a few days; hence, the time frame is quite short.

Please, let us know if you find other issues (or features) that interest you!

**Comment by mtstnt** [comment]
Hi @pdet, thanks for the heads up.

I understand the reasons and hopefully I can contribute in other issues in the future. 

Best of luck for you and your team!
