### ISSUE TITLE
Explain Analyze Error

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#13926]
### What happens?

`duckdb.sql("select * from range(10)").explain('analyze')` yields:
`Not implemented Error: No mapping from ExplainFormat::HTML to ProfilerPrintFormat`

### To Reproduce

```
import duckdb 
duckdb.sql("select * from range(10)").explain('analyze')
```

### OS:

Windows

### DuckDB Version:

1.1.1-dev100

### DuckDB Client:

Python - Jupyter

### Full Name:

Paul T

### Affiliation:

Iqmo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by paultiq** [comment]
Note: Works on 1.0.0, but breaks on 1.1.0 and 1.1.0dev100.

`import duckdb 
duckdb.sql("PRAGMA enable_profiling=json;select 'a'").explain('analyze')
`

**Comment by Tishj** [comment]
> Note:
> 
> * Works on 1.0.0, but breaks on 1.1.0 and 1.1.0dev100.
> * Works in .py, fails in ipython/Jupyter
> 
> `import duckdb duckdb.sql("PRAGMA enable_profiling=json;select 'a'").explain('analyze') `

now results in:
```
{
    "query_name": "0.0",
    "blocked_thread_time": 0.0,
    "cpu_time": 0.0,
    "extra_info": {},
    "cumulative_cardinality": 0,
    "operator_type": "INVALID",
    "operator_cardinality": 0,
    "cumulative_rows_scanned": 0,
    "operator_rows_scanned": 0,
    "operator_timing": 0.0,
    "result_set_size": 0,
    "children": [
        {
            "result_set_size": 0,
            "operator_timing": 0.000003,
            "operator_rows_scanned": 0,
            "cumulative_rows_scanned": 0,
            "operator_cardinality": 0,
            "cumulative_cardinality": 0,
            "extra_info": {},
            "operator_type": "EXPLAIN_ANALYZE",
            "cpu_time": 0.0,
            "children": [
                {
                    "result_set_size": 16,
                    "operator_timing": 0.000048,
                    "operator_rows_scanned": 0,
                    "cumulative_rows_scanned": 0,
                    "operator_cardinality": 1,
                    "cumulative_cardinality": 0,
                    "extra_info": {
                        "Projections": "'a'",
                        "Estimated Cardinality": "1"
                    },
                    "operator_type": "PROJECTION",
                    "cpu_time": 0.0,
                    "children": [
                        {
                            "result_set_size": 4,
                            "operator_timing": 0.000007,
                            "operator_rows_scanned": 0,
                            "cumulative_rows_scanned": 0,
                            "operator_cardinality": 1,
                            "cumulative_cardinality": 0,
                            "extra_info": {},
                            "operator_type": "DUMMY_SCAN",
                            "cpu_time": 0.0,
                            "children": []
                        }
                    ]
                }
            ]
        }
    ]
}
```

as expected

**Comment by paultiq** [comment]
That's not what I get in Jupyter or VSCode notebooks:

![image](https://github.com/user-attachments/assets/b40f1edb-27f4-40ad-9436-ff0b0681fa05)

![image](https://github.com/user-attachments/assets/9dd5b674-777f-432d-82cc-3cc5c788f62d)
