### ISSUE TITLE
INTERNAL Error: Attempted to dereference unique_ptr that is NULL

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#13938]
### What happens?

The below test case (after some seconds creduce) causes an INTERNAL error in DuckDB. This [test case](https://github.com/user-attachments/files/17001454/backup.txt) before further reduced could sometimes cause segmentation fault.

### To Reproduce

```sql
CREATE TABLE t0(c0 TIMESTAMP, c1 VARCHAR[]);
CREATE TABLE t1(c0 FLOAT, c1 TIMESTAMP, c2 FLOAT);
INSERT INTO t0 VALUES('2023-10-10 00:00:00+00:00', NULL);
INSERT INTO t0 VALUES('2025-12-25 12:00:00+02:00', []), ('2004-07-27 10:00:00+02', []);
INSERT INTO t0(c1, c0) VALUES([], '2023-01-01 00:00:00+00:00'), ([], '2021-01-01 00:00:00+01');
INSERT INTO t0(c1, c0) VALUES([], '2021-01-01 00:00:00+00');
INSERT INTO t1 VALUES(2.71, '1999-12-31 23:59:59', 1.41421356237);
INSERT INTO t1 VALUES(1.61803, '1970-01-01 00:00:00', 1.61803);
INSERT INTO t1(c0) VALUES(1064961652.34), (123.45);
INSERT INTO t1(c0) VALUES('514332609.12');
INSERT INTO t1(c0, c2, c1) VALUES(2.71828, 2.345, '1995-05-23 08:45:00'), ('1308880808', 12.34, '2021-01-01 15:30:45');
INSERT INTO t1(c0) VALUES(92857950), (840458867);
INSERT INTO t1 VALUES('3.14', '1999-12-31 23:59:59', 3.1415);

SELECT * FROM t0 RIGHT JOIN t1 ON(CAST(t1.c1 AS TIMESTAMP) BETWEEN t0.c0 AND t0.c0);
-- INTERNAL Error: Attempted to dereference unique_ptr that is NULL! This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic. For more information, see https://duckdb.org/docs/dev/internal_errors
```

### OS:

Ubuntu 22.04

### DuckDB Version:

v1.1.1-dev122 b369bcb4e0

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@suyZhong Reproduce, thanks!
