### ISSUE TITLE
Schema resolution for custom types broken

### ISSUE THREAD

**Issue by shoffmeister** [duckdb/duckdb#13939]
### What happens?

DuckDB 1.1.0 SQL finds a custom type which does not exist in the given database schema.

### To Reproduce

Using the DuckDB CLI run

```sql
create schema myschema;
create type myschema.mytype as struct(i int);
create table myschema.mytable(v mytype);
```

Actual: Executes without an error; this is unexpected.

Expected: In `(v mytype);` the reference to `mytype` is flagged as not existing, i.e. an error
```
Catalog Error: Type with name mytype does not exist!
Did you mean "myschema.mytype"?
```
The _error_ is expected because the `create table` (implicitly) refers to the `main` schema, where `mytype` does not exist.

### OS:

Arch Linux x86_64

### DuckDB Version:

1.1.0

### DuckDB Client:

DuckDB CLI

### Full Name:

Stefan Hoffmeister

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks @shoffmeister indeed this produced an error in v1.0.0 but no longer does so in v1.1.0 or v1.1.0-dev. We'll take a look!

**Comment by shoffmeister** [comment]
A regression, in other words :)

For the record (in case that is not obvious), I am attempting to isolate all objects into one well-defined schema - and then run https://github.com/jOOQ/jOOQ on top of that.

I am getting issues _there_ also with schema resolution of custom types, but cannot tell right now where those originate (might be in the DuckDB information schema? in other DuckDB metadata? in jOOQ?). For the moment, and magically, both DuckDB 1.1.0 and jOOQ 3.19.11 are happy to find the type in the "unnamed" main schema when put there (which I'd prefer to not have there).

**Comment by Guo-Heng** [comment]
it seems to work fine.
```shell
v1.1.0 fa5c2fe15f
Enter ".help" for usage hints.
D create schema myschema;
D create type myschema.mytype as struct(i int);
D create table myschema.mytable(v mytype);
D .tables
mytable
D 
```

**Comment by shoffmeister** [comment]
The challenge is that this works - it should not.

**Comment by Tishj** [comment]
I don't see why it wouldn't be expected for `mytype` to resolve to `myschema.mytype` when used in the schema of a table that lives in the `myschema` schema

Explicitly adding the schema to `mytype` would stop this behavior, and I assume if `mytype` existed in multiple schemas we would throw an AmbiguityError
