### ISSUE TITLE
max_by/min_by() new behavior - feature or bug?

### ISSUE THREAD

**Issue by pedroerp** [duckdb/duckdb#13934]
### What happens?

The behavior of min_by() and max_by() has changed in the new 1.1.0 release. `max_by(a, b)` seems to now return `a` if there is a `null` in `b`, instead of returning `null` like in the previous version (I tested at least until 0.8.1). Returning null is the behavior of other engines like Presto (and perhaps the most intuitive for users?)

Was the change a feature or a bug? (please close in case the change was intentional)

### To Reproduce

```
pedroerp@fedora:~/Github/duck-0.8.1$ ./duckdb 
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
SELECT max_by(c0, c1) FROM (values (1, null)) t(c0,c1);
```
```
┌────────────────┐
│ max_by(c0, c1) │
│     int32      │
├────────────────┤
│                │
└────────────────┘
```
```
pedroerp@fedora:~/Github/duck-0.8.1$ cd ../duck-1.1.0/
pedroerp@fedora:~/Github/duck-1.1.0$ ./duckdb 
v1.1.0 fa5c2fe15f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
SELECT max_by(c0, c1) FROM (values (1, null)) t(c0,c1);
```
```
┌────────────────┐
│ max_by(c0, c1) │
│     int32      │
├────────────────┤
│              1 │
└────────────────┘
```

### OS:

Fedora

### DuckDB Version:

1.1.0 and 0.8.1

### DuckDB Client:

Command line client

### Full Name:

Pedro Pedreira

### Affiliation:

Meta

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! This indeed looks like a bug - I've pushed a fix in #14053

**Comment by pedroerp** [comment]
@Mytherin thank you for the quick fix! When should we expect to have this fix available, in terms of releases?

**Comment by Mytherin** [comment]
It's part of v1.1.1 which was released yesterday

**Comment by pedroerp** [comment]
Great news, thanks :)
