### ISSUE TITLE
`replacement_scan` not working anymore after 1.1.0

### ISSUE THREAD

**Issue by AtomBaf** [duckdb/duckdb#13977]
### What happens?

In python, doing an example code like [this](https://duckdb.org/docs/guides/python/sql_on_pandas.html) used to work even if the variable `my_df` was defined in another python file.
With 1.1.0, this is not working anymore.

### To Reproduce

In a `file1.py`

```python
import duckdb

def func1(query):
    return duckdb.sql(query)
```

In another file `file2.py`
```python
import pandas
from file1 import func1

# Create a Pandas dataframe
my_df = pandas.DataFrame.from_dict({'a': [42]})

# query the Pandas DataFrame "my_df"
results = func1("SELECT * FROM my_df").df()
```

```bash
python file2.py
```
Will fail with `CatalogException: Catalog Error: Table with name my_df does not exist!`

From my understanding the `globals` which is used by duckdb to know which variable should be used during replacement scans is now limited to the caller function since 1.1.0.

### OS:

linux

### DuckDB Version:

1.1.0

### DuckDB Client:

python

### Full Name:

John Doe

### Affiliation:

Acme Corp

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
#13896 should give you this behavior back

**Comment by AtomBaf** [comment]
Thanks for your quick answer, looking forward to have this option.

Also, the new 1.1.0 limiting the frame inspection seems genuine and I would love to have more control on this behaviour: let's say that I'm wrapping the duckdb call inside my own package like the above example, I would like the inspection to go beyond my package to the calling frame, but not too far away in the stack.

Intuitively, I would like the replacement scan to occur only with variables declared in the very same frame that is itself declaring the SQL query. I'm sure it is however difficult to achieve and probably error prone.

**Comment by Tishj** [comment]
> Intuitively, I would like the replacement scan to occur only with variables declared in the very same frame that is itself declaring the SQL query.

That's exactly what's happening though, you're calling `sql` in a deeper frame that does not have access to the `my_df` variable
