### ISSUE TITLE
CentOS install error

### ISSUE THREAD

**Issue by mba1398** [duckdb/duckdb#13984]
### What happens?

when I try to install DuckDB on CentOS, I get the error, please check:
1. first: `sudo yum install -y git g++ cmake ninja-build openssl-devel`
2. then I run the command `git clone https://github.com/duckdb/duckdb.git` , get the flowing error
```sh
[root@hadoop102 opt]# git clone https://github.com/duckdb/duckdb.git
正克隆到 'duckdb'...
remote: Enumerating objects: 588819, done.
remote: Counting objects: 100% (1692/1692), done.
remote: Compressing objects: 100% (797/797), done.
error: RPC failed; result=18, HTTP code = 200450.00 KiB/s
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
```

### To Reproduce

none

### OS:

x86_64

### DuckDB Version:

1.1.0

### DuckDB Client:

cnetos

### Full Name:

alex bob

### Affiliation:

acdm

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @mba1398, unfortunately we do not officially support CentOS – our community support [only includes Ubuntu](https://duckdblabs.com/news/2023/10/02/support-policy). Patches that make sure the build works on other Linux distributions are welcome.
