### ISSUE TITLE
Seeing a single value changed after inserting ~1.5million row polars df to duckdb and then querying back out

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [duckdb/duckdb#14020]
### What happens?

When I write these 9 polars dataframes (saved as parquet files here: https://drive.google.com/drive/folders/18-xFUBLvPyux-erwETaATOV_fUpkLp4B?usp=sharing) to a duckdb table, I find that one single value from one single column is changed when I read the data back out.

### To Reproduce

First, download these 9 parquet files to your local machine: https://drive.google.com/drive/folders/18-xFUBLvPyux-erwETaATOV_fUpkLp4B?usp=sharing

Then, run the following code:
```
import duckdb
import polars as pl
import os
from datetime import date
from zipfile import ZipFile

### Constants
FILESDIR = "path_you_saved_downloaded_parquet_files_to" 
DAYS = range(1,10)
DUCKDB_FILE = os.path.join("path_you_saved_downloaded_parquet_files_to", "so_test.ddb")

### Read data from disk and write to duckdb
for day in DAYS:
    pldf = pl.read_parquet(os.path.join(FILESDIR, f"f{day}_masked.parquet"))
    with duckdb.connect(database=DUCKDB_FILE, read_only=False) as conn:
        if day == 1:
            conn.execute(f"CREATE OR REPLACE TABLE so_test AS SELECT * FROM pldf")
        else:
            conn.execute(f"INSERT INTO so_test SELECT * FROM pldf")        

### Verify that the data has changed by comparing a specific row from last df to its record in duckdb
PROBLEM_ROW = 1108956

print(pldf.slice(PROBLEM_ROW,1))  # hour=4.0
with duckdb.connect(database=DUCKDB_FILE, read_only=False) as conn:
    print(conn.execute(f"SELECT * from so_test WHERE (DAILY_FILE_ROW_ORDER = {PROBLEM_ROW}) and (DAILY_FILE_DATE = '2021-01-09')").pl())  # hour=3.0 now
```

Below is a screenshot of what I see when I run the code above. Note the rows are identical except `hour` has been changed from `4.0` to `3.0` (Also, I see `hour` for that row has been changed to `3.0` even if I read the result as a pandas `.df()`). 
<img width="834" alt="screenshot for duckdb issue" src="https://github.com/user-attachments/assets/ee217594-528c-49d3-861e-016758a19c02">

### OS:

Windows Server 2019 Datacenter, Version 10.0.17763 Build 17763 x64

### DuckDB Version:

1.1.0

### DuckDB Client:

python (python version 3.9.6)

### Full Name:

Max Epstein

### Affiliation:

Max Power Consulting, LLC

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by MaxPowerWasTaken** [comment]
I'll note one more fact here in case it's a helpful hint as to what's going on:

Many records leading up to row `1108956` had `hour`=`3.0`. And in my duckdb table, `hour` changes to being `4.0` at the next row `1108957`, one record after it should change to `4.0`...

**Comment by Mytherin** [comment]
Thanks for the detailed report! This was an off-by-one in the RLE compression algorithm that would occur when a value was repeated exactly `65535` times. I've pushed a fix in https://github.com/duckdb/duckdb/pull/14030.

**Comment by MaxPowerWasTaken** [comment]
Awesome, glad to help and thanks for the quick fix @Mytherin! Am I correct in inferring from [this duckdb releases page](https://duckdb.org/docs/dev/release_calendar.html) that I should be able to `pip install` duckdb 1.1.1 on Monday and incorporate this fix?

**Comment by Mytherin** [comment]
Yes, that is the scheduled date for the bug-fix release

**Comment by MaxPowerWasTaken** [comment]
Hi @Mytherin, just FYI the new 1.1.1 release also fixed a different but apparently related version of this bug for us, where a column took consecutive values of 0-65,535 (it was a file-index column where one of the files in the table happened to have 2^16 rows). 

The relevant data for a given day would be correct in duckdb right after insertion, then after inserting a new day's worth of data (apparently triggering a new internal compression run), I would suddenly have an extra row in the prior day's data in duckdb. guessing it was due to something like range(0,65,535) looking like "a value was repeated exactly 65535 times" internally to the RLE compression. Anyway, thanks again for the super quick fix!
