### ISSUE TITLE
Feature Request , Add support for Google Cloud Storage

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#1403]
all my data is stored in google cloud storage, and I like to use Duckdb to do some Queries there, probably using cloud function, Currently I am using this code and it works perfectly for Pandas, but Duckdb give me error, could not find the file

```
import duckdb
import pandas as pd
import gcsfs
df = pd.read_csv('gs://xxxxx/log_roof.csv',names=["name"])
con = duckdb.connect(database=':memory:', read_only=False)
con.execute("CREATE TABLE NEM AS SELECT * FROM read_csv_auto('gs://xxxxx/log_roof.csv')")
```

**Comment by hannesmuehleisen** [comment]
This boils down to figuring out how to read from Google Could via HTTP. It looks like they use OAuth: https://cloud.google.com/storage/docs/authentication 
Happy to review a PR

**Comment by hannesmuehleisen** [comment]
In a totally shocking move it looks like Google Cloud also supports the HMAC authentication method that S3 uses: https://cloud.google.com/storage/docs/authentication/managing-hmackeys
So I think thats a pretty simple way to get this working.

**Comment by djouallah** [comment]
@hannesmuehleisen I am not a programmer, all I know it is SQL, if you have a working sample it will be nice :)

**Comment by hannesmuehleisen** [comment]
Yeah I am going to add support for Google Cloud storage via its "Interoperability" feature.

**Comment by biellls** [comment]
> Yeah I am going to add support for Google Cloud storage via its "Interoperability" feature.

Does that mean it will also support S3? That would be amazing. I have not programmed much in C++ but I've worked a lot on data and AWS so let me know if you want any help.

Thanks for the great work I'm really enjoying using DuckDB!

**Comment by hannesmuehleisen** [comment]
You can already query Parquet files on S3, see #1369

**Comment by biellls** [comment]
Nice I tried to search S3 in the issues but didn't find it, I'll check it out. Any plans to support profiles? It would be nice to do `SET aws_profile=myprofile` and have that get the region and keys from the `~/.aws/` that the aws CLI sets up.

Another idea is to have something like stages in Snowflake so you can have multiple profiles (or the same profile but multiple buckets). You can create a stage with keys and later reference it:

```SQL
create or replace stage TEST
  url='s3://bucket-test/data/'
  credentials=(aws_key_id='XXXX' aws_secret_key='XXXX');

select * from @TEST/some/path.parquet
```

Regardless, great stuff.

**Comment by hannesmuehleisen** [comment]
well the file approach is a bit at odds with an in-process system. Maybe it would be better to be able to encode the credentials in the s3 url so you can create a view or so. But I also like those stages

**Comment by biellls** [comment]
Yeah on second thought reading the configuration file seems like a bad idea. Having the credentials in the URL seems like it would get annoying quick too. Something like stages would be ideal, it lets you forget about credentials once you've set them and you can easily query different buckets and environments. https://docs.snowflake.com/en/sql-reference/sql/create-stage.html#examples

**Comment by julienflyr** [comment]
It would be great if DuckDB could support GCS stored parquet-files. 🚀

**Comment by arjenpdevries** [comment]
You may benefit from https://rclone.org/ as a workaround until this would be solved differently (re: @julienflyr)?!

**Comment by julienflyr** [comment]
Thanks. Indeed syncing and mounting the files from GCS looks like a sufficient solution for now. And I can imagine DuckDB isn't too keen on taking up many 3rd party libraries to mount to all kinds of storage solutions.

**Comment by EralpB** [comment]
It would be great if DuckDB could support GCS stored parquet-files. 🚀

the reason is I don't want to download terabytes of files to the local filesystem, duckdb is smart enough to know what files to look at and what parts of them so I guess making network'd files first class would be a huge benefit in terms of bandwidth and the ability to analyze big data :)

**Comment by AdeelK93** [comment]
This would be really valuable. If I knew any C++ I'd make the PR myself, but unfortunately I don't

**Comment by hannes** [comment]
We support setting another S3 endpoint, see #2166. So is there a reason the Google HMAC authentication route cannot be used for this?

**Comment by AdeelK93** [comment]
Oh sweet! I wasn't quite sure how to do that, so hopefully this example helps the next person to come along. Be sure to get your HMAC key from [here](https://console.cloud.google.com/storage/settings;tab=interoperability).

```sql
load 'httpfs';
set s3_endpoint='https://storage.googleapis.com';
set s3_access_key_id='key_id';
set s3_secret_access_key='access_key';
select count(*) from 's3://my_bucket/myparquet.parquet';
```

**Comment by diogommartins** [comment]
> Oh sweet! I wasn't quite sure how to do that, so hopefully this example helps the next person to come along. Be sure to get your HMAC key from [here](https://console.cloud.google.com/storage/settings;tab=interoperability).
> 
> ```sql
> load 'httpfs';
> set s3_endpoint='https://storage.googleapis.com';
> set s3_access_key_id='key_id';
> set s3_secret_access_key='access_key';
> select count(*) from 's3://my_bucket/myparquet.parquet';
> ```

s3_endpoint shouldn't contains the protocol:

 `set s3_endpoint='storage.googleapis.com';`

**Comment by michael-go** [comment]
It's nice there exists this workaround with replacing the s3 endpoint and providing keys, however it will be even nicer to handle it like pandas (using gcsfs does) - get the GCS credentials automatically from the environment.
see: https://gcsfs.readthedocs.io/en/latest/#credentials

In an environment which already has gcloud access, like a VM running in GCP with attached workload identity / service-account, or a machine which has done `gcloud auth application-default`, or given the `GOOGLE_APPLICATION_CREDENTIALS` env-var, etc. will be cool to just start querying with duckdb immediately like is possible now with pandas.
In some cases the user might not even have direct access to the secret access key, but is given access to a machine with GCS credentials pre-configured.
Even cooler if the GCS functionality is implemented in the C core, so one can query directly a "gs://" path with the duckdb CLI.

**Comment by Mause** [comment]
You can use `gcsfs` with DuckDB as well: https://duckdb.org/docs/guides/python/filesystems

**Comment by ttjmartinez** [comment]
> You can use gcsfs with DuckDB as well: https://duckdb.org/docs/guides/python/filesystems

One problem with `gcsfs` is that it doesn't support wildcards in the file path, only specific files.

**Comment by ccancellieri** [comment]
> In an environment which already has gcloud access, like a VM running in GCP with attached workload identity / service-account, or a machine which has done `gcloud auth application-default`, or given the `GOOGLE_APPLICATION_CREDENTIALS` env-var, etc. will be cool to just start querying with duckdb immediately ...

I've planned using duckdb into our webservices which works across our buckets and all the services are using GOOGLE_APPLICATION_CREDENTIALS to access any of the buckets, this is a suggested approach:

Moreover HMAC keys are safe for service accounts when:

- Properly rotated.
- Paired with least-privilege permissions.
- Used only for XML API interoperability.

Note also that service-account HMAC keys should be avoided as it challenges google service permissions management and general maintenance of the keys.

Ref also: https://www.vectra.ai/blog/working-as-intended-the-unauditable-unmanageable-keys-in-google-cloud

Dear @hannes how can we help to introduce some other authorization support to this driver?
Do you think it's possible to reopen this or other issues?
Thank you.

**Comment by adriangb** [comment]
I'll point out that querying GCS in DataFusion "just works" with workload identity, etc.

**Comment by ccancellieri** [comment]
Okay I see here there are better options:
https://github.com/duckdb/duckdb/issues/15140
Thank you so much!
