### ISSUE TITLE
CASE statements in TABLE MACRO

### ISSUE THREAD

**Issue by lmangani** [duckdb/duckdb#14042]
### What happens?

`CASE` conditional statements are only working as documented in scalar macros, while table macros throw a parser error.

Is this intentionally unsupported? Documentation doesn't state incompatibility and this feature can be crucial for table macros.

### To Reproduce

```sql
CREATE OR REPLACE MACRO url(url, format) AS TABLE (CASE WHEN format == 'JSON' THEN (SELECT * FROM read_json_auto(url)) ELSE (SELECT * FROM read_csv(url)) END);
```

```
Parser Error: syntax error at or near "CASE"
```

### OS:

*

### DuckDB Version:

1.1.0

### DuckDB Client:

CLI

### Full Name:

Lorenzo Mangani

### Affiliation:

qxip bv

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
It's don't think this is supported, maybe you can get away with this:

```sql
CREATE OR REPLACE MACRO parse_them_all(url, format) AS TABLE (
    WITH "JSON" as (SELECT * FROM read_json_auto(url)),
    "CSV" as (SELECT * FROM read_csv(url))
    FROM query_table(format)
);
FROM parse_them_all('some.csv', 'CSV');
```

**Comment by lmangani** [comment]
@carlopi works like a charm! Grazie 👍
