### ISSUE TITLE
copy with read_csv produces syntax error

### ISSUE THREAD

**Issue by skinkie** [duckdb/duckdb#14049]
### What happens?

I cannot use copy with read_csv. I don't know if this is user error or expected.

### To Reproduce

```
v1.1.0 fa5c2fe15f
Enter ".help" for usage hints.
D select * from read_csv('kv6-20240919.log', delim = ';') limit 1;
┌──────────────────────┬─────────────────────┬─────────────────────┬──────────┬────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│       column00       │      column01       │      column02       │ column03 │  column04  │ column05 │ column06 │ … │ column14 │ column15 │ column16 │ column17 │ column18 │ column19 │
│      timestamp       │      timestamp      │      timestamp      │ varchar  │    date    │ varchar  │ varchar  │   │  int64   │  int64   │  int64   │ boolean  │ varchar  │  int64   │
├──────────────────────┼─────────────────────┼─────────────────────┼──────────┼────────────┼──────────┼──────────┼───┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 2024-09-19 00:00:1…  │ 2024-09-18 22:00:10 │ 2024-09-18 22:00:09 │ INIT     │ 2024-09-19 │ CXX      │ Z160     │ … │          │   200001 │     1114 │ false    │ VEHICLE  │        1 │
├──────────────────────┴─────────────────────┴─────────────────────┴──────────┴────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┤
│ 1 rows                                                                                                                                                         20 columns (13 shown) │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
D copy kv6_import from read_csv('kv6-20240919.log', delim = ';');
Parser Error: syntax error at or near "'kv6-20240919.log'"
LINE 1: copy kv6_import  from read_csv('kv6-20240919.log', delim = ';');

D copy kv6_import from 'kv6-20240919.log' (DELIMITER ';');
```

### OS:

Linux

### DuckDB Version:

1.1.0

### DuckDB Client:

cli

### Hardware:

amd64

### Full Name:

Stefan de Konink

### Affiliation:

Stichting OpenGeo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
This doesn't look like it's supported this way
you can rewrite it and it should work however: <https://duckdb.org/docs/sql/statements/copy.html#syntax>

**Comment by skinkie** [comment]
Yes, the last line in the reproduce works. I guess it would also work as an actual subquery.

**Comment by Mytherin** [comment]
Thanks for the report! Indeed this is not a bug but rather intended behavior. `COPY` is a separate syntax for ingestion than `read_csv`, provided mostly for Postgres compatibility at this point.
