### ISSUE TITLE
Inserting a TIMESTAMPTZ into a TIMESTAMP column ignores the time zone

### ISSUE THREAD

**Issue by sugendran** [duckdb/duckdb#14082]
### What happens?

If I have a table with a TIMESTAMP column and I insert a timestamp that includes a timezone it ignores the timezone, so when I read the value and apply a time zone for presentation the values no longer make sense. My assumption was that the TIMESTAMP column was microseconds from epoch based on the docs, so inserting a timestamp with a timezone should still keep the same time since epoch if that's what we're storing

from the docs:
>Timestamps represent points in absolute time, usually called instants. DuckDB represents instants as the number of microseconds (µs) since 1970-01-01 00:00:00+00.

### To Reproduce

test case:

```sql
CREATE TABLE test(d TIMESTAMP, d2 TIMESTAMPTZ);

SET timezone = 'UTC';
INSERT INTO test(d, d2) VALUES(now(), now());

SET timezone = 'Australia/Sydney';
INSERT INTO test(d, d2) VALUES(now(), now());

SELECT
    d, d at TIME ZONE 'Australia/Sydney' as d_sydney,
    d2, d2 at TIME ZONE 'Australia/Sydney' as d2_sydney
FROM test;
```

output:

```
┌─────────────────────────┬────────────────────────────┬────────────────────────────┬─────────────────────────┐
│            d            │          d_sydney          │             d2             │        d2_sydney        │
│        timestamp        │  timestamp with time zone  │  timestamp with time zone  │        timestamp        │
├─────────────────────────┼────────────────────────────┼────────────────────────────┼─────────────────────────┤
│ 2024-09-24 00:38:01.061 │ 2024-09-24 00:38:01.061+10 │ 2024-09-24 10:38:01.061+10 │ 2024-09-24 10:38:01.061 │
│ 2024-09-24 10:38:01.061 │ 2024-09-24 10:38:01.061+10 │ 2024-09-24 10:38:01.061+10 │ 2024-09-24 10:38:01.061 │
└─────────────────────────┴────────────────────────────┴────────────────────────────┴─────────────────────────┘
```

My expectation is that the values for when we cast to the Sydney timezone match in both cases.

### OS:

OSX

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Sugendran Ganess

### Affiliation:

Ordermentum

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @sugendran, thanks for reporting this. Postgres produces the same results, so I think this behavior is expected:

```bash
$ psql postgres
psql (16.4)
```
```text
             d              |           d_sydney            |              d2               |         d2_sydney
----------------------------+-------------------------------+-------------------------------+----------------------------
 2024-09-24 07:17:58.435048 | 2024-09-24 07:17:58.435048+10 | 2024-09-24 17:17:58.435048+10 | 2024-09-24 17:17:58.435048
 2024-09-24 17:17:58.45637  | 2024-09-24 17:17:58.45637+10  | 2024-09-24 17:17:58.45637+10  | 2024-09-24 17:17:58.45637
 ```

**Comment by szarnyasg** [comment]
Here's the reproducer with a fixed date:

```sql
CREATE TABLE test(d TIMESTAMP, d2 TIMESTAMPTZ);

SET timezone = 'UTC';
INSERT INTO test(d, d2) VALUES(TIMESTAMP '1992-03-02 20:32:45', TIMESTAMP '1992-03-02 20:32:45');

SET timezone = 'Australia/Sydney';
INSERT INTO test(d, d2) VALUES(TIMESTAMP '1992-03-02 20:32:45', TIMESTAMP '1992-03-02 20:32:45');

SELECT
    d, d at TIME ZONE 'Australia/Sydney' as d_sydney,
    d2, d2 at TIME ZONE 'Australia/Sydney' as d2_sydney
FROM test;
```

DuckDB's output:

```text
┌─────────────────────┬──────────────────────────┬──────────────────────────┬─────────────────────┐
│          d          │         d_sydney         │            d2            │      d2_sydney      │
│      timestamp      │ timestamp with time zone │ timestamp with time zone │      timestamp      │
├─────────────────────┼──────────────────────────┼──────────────────────────┼─────────────────────┤
│ 1992-03-02 20:32:45 │ 1992-03-02 20:32:45+10   │ 1992-03-03 06:32:45+10   │ 1992-03-03 06:32:45 │
│ 1992-03-02 20:32:45 │ 1992-03-02 20:32:45+10   │ 1992-03-02 20:32:45+10   │ 1992-03-02 20:32:45 │
└─────────────────────┴──────────────────────────┴──────────────────────────┴─────────────────────┘
```

Postgres' output:

```text
          d          |        d_sydney        |           d2           |      d2_sydney
---------------------+------------------------+------------------------+---------------------
 1992-03-02 20:32:45 | 1992-03-02 20:32:45+10 | 1992-03-03 06:32:45+10 | 1992-03-03 06:32:45
 1992-03-02 20:32:45 | 1992-03-02 20:32:45+10 | 1992-03-02 20:32:45+10 | 1992-03-02 20:32:45
```

**Comment by hawkfish** [comment]
Here is what is going on...

The `AT TIME ZONE` syntax (along with the underlying `timezone` function) really convert between instants and naïve timestamps.  So `d_sydney` interprets the instant (µs since the epoch) as a naïve timestamp (although is it not...) and uses the timestamp UTC bin values to to construct a `TSTZ` in the `Australia/Sydney` time zone - which will then be displayed in that time zone (as that is the current `TimeZone ` setting.) 

Going the other way, `d2_sydney` takes the instant in the `TSTZ` column, converts it to a naïve timestamp using the `Australia/Sydney` bin values and then displays those same values, because the result of the conversion is just a `TIMESTAMP` and its display is independent of the `TimeZone ` setting.

The confusing thing about the SQL Standard's `TIMESTAMP WITH TIME ZONE` is that it _sounds_ like the TZ is attached to the value, but all it means is "use the current `TimeZone` setting for all binning operations" (including presentation).

HTH!

**Comment by sugendran** [comment]
Thanks for that explanation @hawkfish
