### ISSUE TITLE
`AT TIME ZONE` no longer supports a timezone number (i.e. `-0400`) which used to work on v1.0.0

### ISSUE THREAD

**Issue by jviotti** [duckdb/duckdb#14098]
### What happens?

I can no longer do something like `nested.date AT TIME ZONE nested.timezone` where `nested.timezone` is `-0400`. It used to work on v1.0.0, but on v1.1.0 I get:

```
Not implemented Error: Unknown TimeZone '-0400'
```

### To Reproduce

Try `<date> AT TIME ZONE <timezone>` where `timezone` is `-0400` or any other numeric timezone

### OS:

macOS

### DuckDB Version:

v1.1.1

### DuckDB Client:

CLI

### Full Name:

Juan Cruz Viotti

### Affiliation:

Intelligence.AI

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by szarnyasg** [comment]
Hi @jviotti, thanks for reporting this. I could reproduce it with the following SQL statement:

```sql
SELECT TIMESTAMP '1992-03-02 20:32:45' AT TIME ZONE '-0400';
```

## v1.0.0

```
D SELECT TIMESTAMP '1992-03-02 20:32:45' AT TIME ZONE '-0400';
┌──────────────────────────────────────────────────────────────────┐
│ main.timezone('-0400', CAST('1992-03-02 20:32:45' AS TIMESTAMP)) │
│                     timestamp with time zone                     │
├──────────────────────────────────────────────────────────────────┤
│ 1992-03-02 21:32:45+01                                           │
└──────────────────────────────────────────────────────────────────┘
```

## v1.1.0 and v1.1.1

```
D SELECT TIMESTAMP '1992-03-02 20:32:45' AT TIME ZONE '-0400';
Not implemented Error: Unknown TimeZone '-0400'
```

**Comment by hawkfish** [comment]
Ah, that is because we were not validating time zones at all! The old behaviour was to assume that unknown TZs were UTC, so the old behaviour was not even correct.  For example, if I run @szarnyasg 's query at `US/Pacific` in 1.0.0 I get:

|           t            |
|------------------------|
| 1992-03-02 12:32:45-08 |

So all this used to do is treat the timestamp as UTC and convert it to the current time zone.

The current behaviour also matches Postgres:

```sql
hawkfish=# SELECT TIMESTAMP '1992-03-02 20:32:45' AT TIME ZONE '-0400';
ERROR:  time zone "-0400" not recognized
```

so this is correct behaviour. 

Sorry if this is causing problems, but our old behaviour was probably masking a data problem.

**Comment by hawkfish** [comment]
To find the bad time zones, try the following query:

```sql
SELECT DISTINCT nested.timezone
FROM data
LEFT JOIN pg_timezone_names() p ON (nested.timezone = p.name)
WHERE p.name IS NULL
```
