### ISSUE TITLE
read_json_auto parametric url from subquery

### ISSUE THREAD

**Issue by AntonioL** [duckdb/duckdb#14106]
### What happens?

```sql

WITH matches AS (
    SELECT * FROM VALUES(
        (1),
        (2)
    ) t1(val)
)
SELECT * FROM matches m,
LATERAL (
    SELECT * FROM read_json_auto('https://httpbin.org/base64/' || m.val)
) url
```

I am trying to understand if DuckDB would support this use case, Where the url is not static but parametrized for each row. I believe that plays at odds with a few optimization DuckDB does, but if this case is not supported would love to know the precise rule for that!

### To Reproduce

I provided the repro instructions in the above in the form of a standalone query.

### OS:

Ubuntu 22.04 - x86_64

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Antonio Lombardo

### Affiliation:

BloombergLP

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by AntonioL** [comment]
I have now found an explanation for why that use case is not supported. But I believe that in here DuckDB should just fail the query!

**Comment by szarnyasg** [comment]
Hi @AntonioL, running the query on v1.1.1 produces an error:

```sql
-- Loading resources from /Users/szarnyasg/.duckdbrc
v1.1.1 af39bd0dcf
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D WITH matches AS (
      SELECT * FROM VALUES(
          (1),
          (2)
      ) t1(val)
  )
  SELECT * FROM matches m,
  LATERAL (
      SELECT * FROM read_json_auto('https://httpbin.org/base64/' || m.val)
  ) url
  ;
Binder Error: Table function "read_json_auto" does not support lateral join column parameters - cannot use column "m.val" in this context.
The function only supports literals as parameters.
LINE 9: ...T * FROM VALUES(
        (1),
        (2)
    ) t1(val)
)
SELECT * FROM matches m,
LATERAL (
    SELECT * FROM read_json_auto('https://httpbin.org/base64/' || m.val)
```

**Comment by AntonioL** [comment]
Totally makes sense. I guess the reason is that it needs to inspect the schema right?
