### ISSUE TITLE
read_csv_auto Loads data to a different column for a specific row when provided some UTF-8/Unicode sequences

### ISSUE THREAD

**Issue by sbbhardwa** [duckdb/duckdb#14116]
### What happens?

I have csv Load like this 

![image](https://github.com/user-attachments/assets/434494ec-015d-4c64-912f-84678e70acd7)

Pasting here the exact csv 

```
id,name,age
1,João,25
2,李华,30
3,aنايف,40
4,"Robert, Albert", 😈
```

This was just a test for a unicode load 

I noticed the data is loaded correctly untl row 2 , row 3 is loaded incorrectly 

```sql
SELECT * FROM read_csv_auto("test.csv");
```

![image](https://github.com/user-attachments/assets/424c0fc1-af4e-4be5-b5b0-268f4c069af6)

### To Reproduce

Unicode Data for csv loaded incorrectly in a different column 

### OS:

Windows 

### DuckDB Version:

1.1.0

### DuckDB Client:

jdbc:duckdb

### Hardware:

12th Gen Intel(R) Core(TM) i5-1250P   1.70 GHz

### Full Name:

Sandeep Bhardwaj

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@sbbhardwa Thanks, I could reproduce this and it seems to be a bug. We'll take a look.

**Comment by szarnyasg** [comment]
Hi @sbbhardwa we took a look at this issue. The value in question has a mix of Arabic characters (reading from right to left) and Latin characters (reading from left to right). This makes it confusing for some text editors.
However, if you open it in e.g. Sublime Text, you can observe the correct byte order:

![image](https://github.com/user-attachments/assets/3a49baf1-3fdd-4e54-8800-dca523fc7ccc)

So DuckDB is behaving here correctly.
