### ISSUE TITLE
Sniff_csv is providing incorrect information about delimeter 

### ISSUE THREAD

**Issue by sbbhardwa** [duckdb/duckdb#14115]
### What happens?

FROM sniff_csv('C:/rs/flights.csv');

![image](https://github.com/user-attachments/assets/626174b8-1994-4fe8-9f44-1c2290583153)

Delimeter sniffed should be a pipe '|' 

but the Query returns ',' 

![image](https://github.com/user-attachments/assets/71bcdbf8-10be-4fb4-b0e2-12ec6e41fd15)

### To Reproduce

Delimeter sniffed should be a pipe '|' 

### OS:

Windows 

### DuckDB Version:

1.1.0

### DuckDB Client:

jdbc:duckdb

### Hardware:

12th Gen Intel(R) Core(TM) i5-1250P   1.70 GHz

### Full Name:

Sandeep Bhardwaj

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pdet** [comment]
This is expected, as the sniffer tries to find the best options to read the file consistently.

Since you have an invalid delimiter, you could try it with `ignore_errors = true` or you can define the delimiter manually.

**Comment by sbbhardwa** [comment]
a Pipe is a valid value I think as per the documentation as in https://duckdb.org/docs/data/csv/auto_detection.html

![image](https://github.com/user-attachments/assets/199627f3-233f-475b-8f50-0ddab53cc3ad)

**Comment by pdet** [comment]
It is valid indeed.

However, the sniffer is a best-effort technique for finding dialects and types of CSV files while maintaining consistency.

One of your rows has an unquoted extra pipe, which makes that line inconsistent with the others if the pipe is selected. Hence, the sniffer selects the comma, which would cause all rows of your file to have two columns (i.e., fully consistent).

This is the way the sniffer is intended to work; it's, of course, not perfect, especially for inconsistent files. In cases with inconsistent files, like the one you depict in this issue, you might have to provide options manually.

**Comment by sbbhardwa** [comment]
sure , agree the data had an extra 'I' but when loading that row is actually not loaded using 

SELECT * FROM read_csv_auto("C:/rs/flights.csv") ; 

![image](https://github.com/user-attachments/assets/e39d72b3-51be-4986-bc5b-aca2fbe6cf12)

So basically the sniffer will default to a , in cases where there is a rejected row of data ?

Fyi , I did fixed the file and tried the sniffer again 

FlightDate|UniqueCarrier|OriginCityName|DestCityName
1988-01-01|AA|New York, NY|Los Angeles, CA
1988-01-02|AA|New York, NY|Los Angeles, CA
1988-01-03|AA|New York, NY|Los Angeles, CA


![image](https://github.com/user-attachments/assets/7daf15c7-ea5c-4492-909a-4961b73467f2)


May be the conclusive evidence is sniffer defaulting to a , here

**Comment by sbbhardwa** [comment]
may be not I did another test with a malformed and the sniffer now detects as a pipe for some reasons here 

Sample csv 

id,name,age
2,"Alice,Doe",30
1,"John, Doe,25
3,"Bob",35
4,"John","45

Notice row 2 is malformed without a end " for John,Doe 

sniffer detects this csv delimeter as a pipe 

FROM sniff_csv('C:/rs/malformed.csv');

![image](https://github.com/user-attachments/assets/2a4c333a-33b1-4272-8c93-e68526261cd6)

**Comment by szarnyasg** [comment]
As @pdet wrote, this is expected behavior. The sniffer tries to find the best option to read the file, with very few rows this is often not possible and it has to pick one – sometimes leading to an incorrect conclusion. There isn't much we can do about this if the sample size is low. Manually specifying the schema or using larger CSV files ensures that the CSV dialect is correctly detected.

**Comment by sbbhardwa** [comment]
As i mentioned in https://github.com/duckdb/duckdb/issues/14117 

I did loaded with more rows but the results are same ?

**Comment by ws-garcia** [comment]
That is the primary reason for why is so important to implement auditable heuristics, so users can view why a dialect is choosen ahead another.
