### ISSUE TITLE
INNER JOIN returns inconsistent results

### ISSUE THREAD

**Issue by bhmayer** [duckdb/duckdb#14140]
### What happens?

When I run the following inner join I get inconsistent results. This has occured with the CSV files as seen below and with trying to join a csv file with a sqlite database.

```sql
    SELECT COUNT(*)
    FROM media_filenames.csv m
    INNER JOIN media_filenames_2.csv c 
    ON m.filename = c.filename
    where m.filename is not Null and c.filename is not Null;
```
```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      1395487 │
└──────────────┘
```
```sql
    SELECT COUNT(*)
    FROM media_filenames.csv m
    INNER JOIN media_filenames_2.csv c 
    ON m.filename = c.filename
    where m.filename is not Null and c.filename is not Null;
```
```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      1394553 │
└──────────────┘
```
```sql
    SELECT COUNT(*)
    FROM media_filenames.csv m
    INNER JOIN media_filenames_2.csv c 
    ON m.filename = c.filename
    where m.filename is not Null and c.filename is not Null;
```
```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      1394913 │
└──────────────┘
```

### To Reproduce

Run the following SQL query on the linked CSV files

```sql
SELECT COUNT(*)
FROM media_filenames.csv m
INNER JOIN media_filenames_2.csv c 
ON m.filename = c.filename
where m.filename is not Null and c.filename is not Null;
```

https://drive.google.com/file/d/1STL_Zoj67oWaojJRxBAdkg_CO22rGusH/view?usp=sharing

https://drive.google.com/file/d/1CcVnAgDRziIK7DU96YFpnxK3Fd46_-nP/view?usp=sharing

### OS:

Ubuntu arm64

### DuckDB Version:

v1.1.1 af39bd0dcf

### DuckDB Client:

CLI

### Hardware:

AWS EC2

### Full Name:

Ben Mayer

### Affiliation:

University of Chicago

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pkoppstein** [comment]
Good news, at least for Mac users: three different versions of DuckDB 
running on a Mac **consistently** produce identical counts (1398397) for the query.(*)

Even better news, this happens to be the correct number! (**)

---

(*) The statement was run three times per version, the DuckDB versions being:

v1.0.0 (v1.0.0 1f98600c2c)
v1.1.0 (v1.1.0 fa5c2fe)
v1.1.2-dev38

(**) 
In the first file, the only duplicated lines are blank lines and NA; 
in the second file, there are no duplicates, and there are neither blank lines nor NA values.

So, including the header line, the correct count would be:

sort <( grep -v '^ *$' media_filenames.csv | grep -v '^NA$') media_filenames_2.csv | histogram | grep ' 2 $' | wc -l
1398398

Thus the SQL query should yield 1398397.

**Comment by szarnyasg** [comment]
@bhmayer thanks, I could reproduce this on Ubuntu ARM running in Docker on MacOS.

**Comment by bhmayer** [comment]
Thanks all! Let me know if any immediate work arounds can be identified. I was also able to reproduce this error on v1.1.0 on Ubuntu ARM. I will try using the python bindings later today.

**Comment by bhmayer** [comment]
Running the below code in python with duck-db v1.1.1 on amazon linux x86 I am able to get the correct answer. So maybe the issues is with the Linux ARM binary?

```
import duckdb 
import pandas
con = duckdb.connect(config={'threads':8})

query = """
SELECT COUNT(*)
FROM media_filenames.csv m
INNER JOIN media_filenames_2.csv c 
ON m.filename = c.filename;
"""
result = con.sql(query)
print(result)

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      1398397 │
└──────────────┘
```

**Comment by szarnyasg** [comment]
Thanks for the report, this is now fixed on `main`.
