### ISSUE TITLE
Question: Using Full Text Search from the R package

### ISSUE THREAD

**Issue by mskyttner** [duckdb/duckdb#1414]
I would like to use the FTS or Full Text Search extension through the R package. I have tried v 0.2.4 and also installing duckdb for R from the latest master.  However, I run into the following message when executing `PRAGMA create_fts_index(....)`:

`Error: Catalog Error: Pragma Function with name create_fts_index does not exist!
`
I believe it might be caused by the extension not being enabled?

How can I install the R package with the FTS extension enabled?

**Comment by mskyttner** [comment]
Is it possible to enable extensions when installing the duckdb R package, in order to get FTS and HTTP/HTTPS/S3 file system adapter functionality? Can this be done using some arguments passing (via R CMD or install.packages() using configure.args or configure-vars, or should one build from source after making modifications to https://github.com/cwida/duckdb/blob/master/tools/rpkg/rconfigure.py#L6?

**Comment by Mytherin** [comment]
Unfortunately for now the only way of enabling extensions is by recompiling from source. In the future we will make extensions available in a nicer way, but for now you indeed will need to alter the configure script and run `R CMD INSTALL .`

**Comment by mskyttner** [comment]
Thanks for this info! I'll try this.

My use case is to load a parquet file over https and then enable FTS when exposing the data to R in a package.

I started by trying this in the duckdb shell using master branch install (a statement similar to what is in the generated load.sql file when exporting):

```bash
COPY projectPublications FROM 'https://github.com/KTH-Library/cordis-data/releases/download/0.0.1/projectPublications.parquet' (FORMAT 'parquet');
```
But this reported `Error: Parser Error: syntax error at or near "parquet_scan"`

So I was about to try to get it like this instead:

```r
con <- duckdb::dbConnect(duckdb::duckdb("mycordisdb"))
url <- "https://github.com/KTH-Library/cordis-data/releases/download/0.0.1/projectPublications.parquet"
sql <- sprintf("CREATE TABLE projectPublications AS SELECT * FROM parquet_scan('%s');", url)
DBI::dbExecute(con, sql)
duckdb::dbDisconnect(con)
```

**Comment by sdmcallister** [comment]
@Mytherin 

Is this extension not included in all the 0.3.1 builds by default? I am curious as I am compiling on Centos 7, but will hopefully soon move to Ubuntu where I may not need to compile from source.  

Is there any documentation that I can refer to which describes the modified build process to enable the extension?

**Comment by hannes** [comment]
We have installable extensions now, `INSTALL 'its';` should do it

**Comment by cboettig** [comment]
@hannes is this available in the 0.3.4 release? Maybe I'm doing this wrong:

```
#install.packages("https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_r_src.tar.gz", repos = NULL)
library(duckdb)
con = dbConnect(duckdb(), ":memory:")
DBI::dbExecute(con, "INSTALL 'its'")
```
but I get:

```
DBI::dbExecute(con, "INSTALL its")
Error: rapi_execute: Failed to run query
Error: IO Error: Failed to download extension http://extensions.duckdb.org/662041e2b/linux_amd64/its.duckdb_extension.gz
```

(FWIW, I can't wget the extension URL http://extensions.duckdb.org/662041e2b/linux_amd64/its.duckdb_extension.gz either, I get a 403 denied error)

**Comment by hannes** [comment]
There is no extension with the name “its”, what are you looking for?

**Comment by cboettig** [comment]
Whoops, I was just blindly copy-pasting from above -- it should have been `fts` right?

> We have installable extensions now, INSTALL 'its'; should do it

**Comment by hannes** [comment]
Ah yes

**Comment by cboettig** [comment]
ok cool, thanks for the quick reply!  Looks like I'll just want to #3416 is merged so that I can load the module as well.
