### ISSUE TITLE
Querying single Parquet file in S3

### ISSUE THREAD

**Issue by pugpapa** [duckdb/duckdb#14153]
### What happens?

I created a secret with key_id / secret / session_token, and attempted to run a select query on a parquet file.  This is the error I got:

```
[Code: 0, SQL State: ]  java.sql.SQLException: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### To Reproduce

```
install aws; load aws;

create secret tbsbeta (
    type s3,
    key_id 'KEY',
    secret 'SECRET,
    session_token TOKEN'
);

FROM duckdb_secrets();



select * from 's3://BUCKET/KEY.parquet'
```

### OS:

macOS

### DuckDB Version:

1.1

### DuckDB Client:

Java

### Full Name:

Jon Lin

### Affiliation:

Amazon

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by arjenpdevries** [comment]
Is the `session_token` as in your example really contained inside the `secret` string, or is that a copy paste mistake?

**Comment by szarnyasg** [comment]
Hi @pugpapa, thanks for reporting this. Does the error occur on 1.1.0, 1.1.1, or both?

**Comment by pugpapa** [comment]
> Is the `session_token` as in your example really contained inside the `secret` string, or is that a copy paste mistake?

Copy paste mistake

> Does the error occur on 1.1.0, 1.1.1, or both?

Just trying on 1.1.0 for now

> Are there anything special about this setup?

The files were written as part of a Lake Formation managed Glue catalog.  The specific role secrets I pulled were those for the role that wrote the data.

**Comment by pugpapa** [comment]
At the end of the day, I'm looking for a way to expose other compute to our Iceberg tables other than typical AWS cloud compute - Athena / Glue / Redshift / EMR

**Comment by pugpapa** [comment]
UGH - sorry, I didn't read the docs closely enough. I didn't install the `httpfs` extension as well.  It's working now.
