### ISSUE TITLE
Previously working unnesting JSON Sql script breaking in v1.1.x

### ISSUE THREAD

**Issue by Confused-Donut** [duckdb/duckdb#14158]
### What happens?

Updated to 1.1.1 and previously working SQL scripting breaks in specific nested JSON use case.

### To Reproduce

Reading a nested JSON file with contents (simplified example):

```
{
   "MainLevel":[
      {
         "More":{
         }
      },
      {
         "More":{
            "Level2":[
               {
                  "Field1":"A"
               }
            ]
         }
      }
   ]
}

```
---------------
Using this SQL statement:

```
SELECT 
    Level2.Field1,
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    unnest(MainLevel.More.Level2) as Level2;
```
	
----------------
Error (using dbeaver or CLI on Windows10):

```
SQL Error: java.sql.SQLException: Binder Error: Table "Level2" does not have a column named "Field1"
LINE 2:     Level2.Field1,
```

----------------

This script worked prior to updating beyond 1.0
**If this is new planned behavior, can someone explain how to fix this code example?**  I do need to pick out specific data elements and not read in whole file as there are thousands of elements.

### OS:

Windows10, x86

### DuckDB Version:

1.1.1

### DuckDB Client:

Windows CLI and DBeaver

### Full Name:

Mike Biesanz

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Fix is 
```sql
SELECT 
    Level2.Field1,
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('test.json'))
     as MainLevel,
    unnest(MainLevel.More.Level2) as _(Level2);
```

-- this way you're naming the second table `_` and the only column within that table `Level2`, whereas your original query named the second table `Level2` and kept the auto-generated name of its single column, which was `unnest`. Therefore, you could also fix your query as 

```sql
SELECT 
    unnest.Field1
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('test.json'))
     as MainLevel,
    unnest(MainLevel.More.Level2) as Level2;
```

**Comment by zmajeed** [comment]
I debugged your query by replacing `Level2.Field1` with `*`

```sql
SELECT 
    *
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    unnest(MainLevel.More.Level2) as Level2;
```

```
┌──────────────────────────────────────────────────────┬────────────────────────┐
│                      MainLevel                       │         unnest         │
│ struct(more struct(level2 struct(field1 varchar)[])) │ struct(field1 varchar) │
├──────────────────────────────────────────────────────┼────────────────────────┤
│ {'More': {'Level2': [{'Field1': A}]}}                │ {'Field1': A}          │
└──────────────────────────────────────────────────────┴────────────────────────┘
```

Now we see the column name is `unnest` not `Field1` - so `select unnest.Field1` would work

Or we could use parentheses to make `Level2` an alias for `unnest`

```sql
SELECT 
    *
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    (unnest(MainLevel.More.Level2) as Level2);
```

```
┌──────────────────────────────────────────────────────┬────────────────────────┐
│                      MainLevel                       │         Level2         │
│ struct(more struct(level2 struct(field1 varchar)[])) │ struct(field1 varchar) │
├──────────────────────────────────────────────────────┼────────────────────────┤
│ {'More': {'Level2': [{'Field1': A}]}}                │ {'Field1': A}          │
└──────────────────────────────────────────────────────┴────────────────────────┘
```

then this works

```sql
SELECT 
    Level2.Field1
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    (unnest(MainLevel.More.Level2) as Level2);
```

```
┌─────────┐
│ Field1  │
│ varchar │
├─────────┤
│ A       │
└─────────┘
```

**Comment by Confused-Donut** [comment]
soerenwolfers - your solutions both worked. 
 Thank you.  I did have issues with these solutions in the case of more nesting levels deep.  Ex:

```
{
   "MainLevel":[
      {
         "More":{
         }
      },
      {
         "More":{
            "Level2":[
               {
                  "Field1":"A",
				  "Level3": [
                       {
                          "Field1": "B"
                       }
                   ]
               }
            ]
         }
      }
   ]
}
```
Tried using this code:

```
SELECT 
    Level2.Field1 AS Level2Field1,
    Level3.Field1 AS Level3Field1
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    unnest(MainLevel.More.Level2) as _(Level2),
    unnest(Level2.Level3) as _(Level3);
```
Just trying to get my scripts working again.

**Comment by Confused-Donut** [comment]
zmajeed - for some reason I could not get your solution to work for me.  Step 1 - yes.  Step 2 - no

```
SELECT 
    *
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    (unnest(MainLevel.More.Level2) as Level2);
```

Gives me:

`SQL Error: java.sql.SQLException: Parser Error: syntax error at or near ")"`

**Comment by soerenwolfers** [comment]
@Confused-Donut what's your error message? presumably you can't use the "_" name twice, so just use any other name. I can't test right now

**Comment by zmajeed** [comment]
Sorry about that - it's a typo - I missed the extra `SELECT` needed to associate the `Level2` alias - I've fixed my note above - here's the correct query again

```sql
SELECT 
    Level2.Field1
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('*.json'))
     as MainLevel,
    (SELECT unnest(MainLevel.More.Level2) as Level2);
```

```
┌─────────┐
│ Field1  │
│ varchar │
├─────────┤
│ A       │
└─────────┘
```

**Comment by Confused-Donut** [comment]
zmajeed - Have validated that this solutions works!

Also, validated for the 3 level nesting that this solution also works as follows:

```
SELECT 
    Level2.Field1 AS Level2Field1,
    Level3.Field1 AS Level3Field1
FROM 
    (SELECT unnest(MainLevel) as MainLevel
     FROM read_JSON_auto('C:\\jsonfiles\\*.json'))
     as MainLevel,
    (SELECT unnest(MainLevel.More.Level2) as Level2),
    (SELECT unnest(Level2.Level3) as Level3);
```
Returns:
____________________________
|Level2Field1 |Level3Field1 |
|-------------|-------------|
|A                 |B                  |

**Comment by Confused-Donut** [comment]
Interesting side note:  This way of processing must take more memory as for a historical dataset that worked fine previously (ie: same number of records) I get

`Out of Memory Error: failed to allocate data of size 1.8 GiB (13.0 GiB/12.5 GiB used)`

**Comment by soerenwolfers** [comment]
you should open a separate ticket for this, including:

- the dataset, or an anonymized version that exhibits the same performance problems 
- the exact query you're running, or even better, a simplified version that exhibits the same performance problems 
- profile information (hardware and OS description at the least, and memory usage information if you can)

you should also retry this with an older duckdb version to make sure it's not just a symptom of, e.g., what else is currently running on your machine.

**Comment by Confused-Donut** [comment]
sorenwolfers - 

1)  hmmm, perhaps I could take time and create an anonymized dataset (if I have time)
2)  Could do this no problem
3)  Sure, although it would be nice to know how to profile this myself (WITHIN duckdb) before submitting as an issue.  Seems like it is throwing an error but not using much system resources to come up with that error (at least as I can see.  perhaps there is an obscure perf metric but it isn't the big obvious ones as I can see.

lots of permutations to think about here:

a) the sql query itself and how it gets processed (I have 2 different queries that work on smaller datasets, one errors when more files added to the mix but the other one doesn't)
b) the size of data overall being processed (Could concat all files into one big file and see if it works)
c) the number of files being processed
d) system resources (although the data is not big so really doubt this is it)

**Comment by lnkuiper** [comment]
Thanks for chiming in everyone! This is now expected behavior, as we have changed the table reference when `unnest` is used in the `FROM` clause in https://github.com/duckdb/duckdb/pull/12431/files

This also no longer works, as both table refs are called "unnest", causing a conflict:
```sql
with cte as (select [1, 2, 3] l) select * from cte, unnest(cte.l), unnest(cte.l);
```
