### ISSUE TITLE
Install sqlite hangs indefinetely

### ISSUE THREAD

**Issue by rousbound** [duckdb/duckdb#14163]
### What happens?

duckdb hangs indefinetely while installing sqlite:
Obs: No other duckdb processes opened in parallel other than the one instaling sqlite.

### To Reproduce

```bash
user@machine:~$ duckdb
v1.1.1 af39bd0dcf
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install sqlite;

```

### OS:

I'm using ubuntu 24.04.1

### DuckDB Version:

1.1.1

### DuckDB Client:

duckdb-cli

### Full Name:

Geraldo Luiz

### Affiliation:

PUC-RJ

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by rousbound** [comment]
Rebooting the computer fixed it. Don't know why.

**Comment by erlag** [comment]
I encountered the same issue, but on macOS. It happened consistently and repeatedly but rebooting actually resolved it for me too.

Not sure if this will be helpful, but while it was hanging, I attached a debugger to check what was going on. The main thread seemed to be waiting for an event with `poll`, while all other threads were waiting on semaphores.

```
(lldb) thread list
Process 80332 stopped
* thread #1: tid = 0x25ca7b5, 0x0000000182c716e0 libsystem_kernel.dylib`poll + 8, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0x25ca88d, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #3: tid = 0x25ca88e, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #4: tid = 0x25ca88f, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #5: tid = 0x25ca890, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #6: tid = 0x25ca891, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #7: tid = 0x25ca892, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #8: tid = 0x25ca893, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #9: tid = 0x25ca894, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
  thread #10: tid = 0x25ca895, 0x0000000182c68d50 libsystem_kernel.dylib`semaphore_wait_trap + 8
(lldb) s
Process 80332 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = instruction step into
    frame #0: 0x0000000182c716e4 libsystem_kernel.dylib`poll + 12
libsystem_kernel.dylib`poll:
->  0x182c716e4 <+12>: pacibsp 
    0x182c716e8 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x182c716ec <+20>: mov    x29, sp
    0x182c716f0 <+24>: bl     0x182c6a668               ; cerror
Target 0: (duckdb) stopped.
```
