### ISSUE TITLE
format issues with COPY FROM CSV

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#14205]
### What happens?

`COPY ... FROM ...` does not use the same auto-detection as `read_csv` (on column separators).

```sql
are@ryzen ~> duckdb
v1.1.1 af39bd0dcf
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE sales (
      salesid          INTEGER         NOT NULL PRIMARY KEY
      , listid         INTEGER         NOT NULL
      , sellerid       INTEGER         NOT NULL
      , buyerid        INTEGER         NOT NULL
      , eventid        INTEGER         NOT NULL
      , dateid         SMALLINT        NOT NULL
      , qtysold        SMALLINT        NOT NULL
      , pricepaid      DECIMAL (8,2)
      , commission     DECIMAL (8,2)
      , saletime       TIMESTAMP
  )
  ;
D COPY sales FROM '~/tickitdb/sales_tab.txt' (FORMAT CSV, AUTO_DETECT true, timestampformat '%m/%d/%Y %I:%M:%S', ignore_errors true);
Invalid Input Error: Mismatch between the number of columns (1) in the CSV file and what is expected in the scanner (10).
```

Instead, one must set `DELIMITER` explicitely:
```sql
COPY sales FROM '~/tickitdb/sales_tab.txt' (FORMAT CSV, AUTO_DETECT true, DELIMITER '\t', timestampformat '%m/%d/%Y %I:%M:%S', ignore_errors true);
```

Interestingly, this is not the case for `csv_read` where the TAB delimiter would be detected correctly.

### To Reproduce

see above.

### OS:

Linux

### DuckDB Version:

1.1.1

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @manticore-projects could you provide a sufficient sample of the CSV file?

**Comment by manticore-projects** [comment]
Of course. I will create a self containing example tomorrow.

**Comment by manticore-projects** [comment]
Greetings!

Please see a complete, self containing Test/illustration here: https://github.com/manticore-projects/duckdbtest

You can run it via
```sh
./gradlew check
```

2 out of 3 tests will fail with DuckDB 1.1.1 (but work with 1.0.0). The relevant tests are here: 

https://github.com/manticore-projects/duckdbtest/blob/502aad209d235a5ac656df31772bca7c3843b94d/src/test/java/CsvTest.java#L99
https://github.com/manticore-projects/duckdbtest/blob/502aad209d235a5ac656df31772bca7c3843b94d/src/test/java/CsvTest.java#L118

The CSV file is from Amazon's TickitDB: https://docs.aws.amazon.com/redshift/latest/gsg/samples/tickitdb.zip

Please do let me know if I can help anything else and thanks for caring!

**Comment by pdet** [comment]
Hi @manticore-projects thank you for providing the queries and the data, I managed to reproduce the issue and pushed a PR to fix it for the next release! :-)

**Comment by manticore-projects** [comment]
Thank you very much!

**Comment by manticore-projects** [comment]
Testing this with release 1.1.2 the `COPY` statement detects now the delimiter correctly,. however the false Duplicate error still persists.
Again, this does NOT happen with INSERT, but only with COPY. Please see a complete, self containing Test/illustration here: https://github.com/manticore-projects/duckdbtest (same as before):

```sql
COPY sales FROM '/tmp/fd2b922b-08c6-4373-875a-7f4ae1130e4d/sales_tab.txt' (FORMAT CSV, AUTO_DETECT true, TIMESTAMPFORMAT '%m/%d/%Y %I:%M:%S', IGNORE_ERRORS true);

/*
Constraint Error: PRIMARY KEY or UNIQUE constraint violated: duplicate key "125681"
java.sql.SQLException: Constraint Error: PRIMARY KEY or UNIQUE constraint violated: duplicate key "125681"
*/
```

You can check the CSV file, key 125681 is distinct. And it always fails with the same key.

**Comment by Mytherin** [comment]
I can't reproduce the false duplicate error using the stand-alone SQL statements, this now succeeds for me:

```sql
 CREATE TABLE sales (
        salesid          INTEGER         NOT NULL PRIMARY KEY
        , listid         INTEGER         NOT NULL
        , sellerid       INTEGER         NOT NULL
        , buyerid        INTEGER         NOT NULL
        , eventid        INTEGER         NOT NULL
        , dateid         SMALLINT        NOT NULL
        , qtysold        SMALLINT        NOT NULL
        , pricepaid      DECIMAL (8,2)
        , commission     DECIMAL (8,2)
        , saletime       TIMESTAMP
    )
    ;
COPY sales FROM 'src/test/resources/sales_tab.txt' (FORMAT CSV, DELIMITER '\t',  TIMESTAMPFORMAT '%m/%d/%Y %I:%M:%S', IGNORE_ERRORS true);
```

I haven't tested the Java program since DuckDB 1.1.2 isn't released yet for Java. 

Could you perhaps create a pure SQL reproducer that triggers the issue?

**Comment by manticore-projects** [comment]
Hi @Mytherin 

sorry, this has been my mistake. I did not notice that 1.1.2 is NOT on Maven yet, apologies for the noise.
