### ISSUE TITLE
Compressed Storage Battle Plan

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#1420]
We will support compressed storage. However, on the way there the following smaller issues need addressing:

- [ ] handling half-empty blocks (half-empty blocks in free list, etc)
- [x] handling null values as separate boolean column
- [x] move updates from in-place to out of place somehow
- [x] scan handles not vector aligned blocks on disk

**Comment by djouallah** [comment]
@hannesmuehleisen I hope it is the start of a long journey, there is a need in the market for a storage file format that support multiple tables,  Congratulations

**Comment by wizzard0** [comment]
@djouallah beware -- I believe the storage format is not considered stable at all yet ;)

**Comment by dforsber** [comment]
Sounds really cool! Parquet with ZSTD compression is already really good compression with low cpu overhead. That would be a nice comparison point, for us at least. (Parquet metadata is not optimised for low number of round trips, which adds latency when accessing Parquet files over network. But anyway, less data to transfer reduces latency as well).

**Comment by alanpaulkwan** [comment]
I would definitely just convert to DuckDB native storage as my tests suggest it is the fastest, although my dream scenario would be DuckDB would have an alternative Parquet-based storage engine (inclusive of indices and hive partitions) as if it were an embeddable Impala.

**Comment by alanpaulkwan** [comment]
So is DuckDB a usable storage format now (e.g. files stored in the format won't need conversion )?
