### ISSUE TITLE
Literal in SELECT DISTINCT ON clause raises ORDER BY non-integer literal has no effect.

### ISSUE THREAD

**Issue by wadinj** [duckdb/duckdb#14212]
### What happens?

After upgrading to DuckDB 1.1.1, I encountered an issue where DuckDB raises `Binder Error: ORDER BY non-integer literal has no effect` when having literal in `SELECT DISTINCT ON (..)` clause.

Turning order_by_non_integer_literal=true resolves the issue, allowing literal in DISTINCT ON.

The error message is really confusing as the initial cause does not come from the ORDER BY clause.

I would rather accept literal in SELECT DISTINCT clause by default or rework the error message to point out the correct SQL clause. 

### To Reproduce

```
con = duckdb.connect(":memory:")
con.execute('CREATE TABLE my_table AS SELECT 42 AS "column_name";')
con.execute("SET order_by_non_integer_literal = true;")
con.execute(
    "SELECT DISTINCT ON (my_table.column_name, 'co2') my_table.column_name FROM my_table"
).fetchone()

```

### OS:

iOS/Linux

### DuckDB Version:

1.1.1

### DuckDB Client:

Python

### Full Name:

Jonathan Wadin

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
Hi @wadinj, thanks for opening this issue. What's the error message that you're getting? For me, this works fine in the CLI client:

```sql
CREATE TABLE my_table AS SELECT 42 AS "column_name";
SELECT * FROM my_table ORDER BY "column_name";
```

**Comment by wadinj** [comment]
Hi @szarnyasg, here's a reproduction: 
```
con = duckdb.connect(":memory:")
con.execute('CREATE TABLE my_table AS SELECT 42 AS "column_name";')
con.execute("SET order_by_non_integer_literal = true;")
con.execute(
    "SELECT DISTINCT ON (my_table.column_name, 'any_string') my_table.column_name FROM my_table"
).fetchone()
```
My initial analysis was wrong. 

The issue come from the `DISTINCT ON (...)` having literal. I would rather change the error message to specify `DISTINCT ON` vs `ORDER BY` or allow literal in `DISTINCT ON (...)` (if there's no other restrictions I'm not aware).
