### ISSUE TITLE
Add column to a struct

### ISSUE THREAD

**Issue by ErikJansenIRefact** [duckdb/duckdb#14219]
### What happens?

Assume an existing table with a single row of type struct.
Now we want to add a column to the name struct with 'alter table ...'.
It either seems not possible to do this or the documentation is lacking how this can be done?

Is this supported in duckdb as we rely heavily on structs and sometimes we need to add a column to a struct.

### To Reproduce

```sql
create table test ( name struct(firstname varchar, lastname varchar));
insert into test values ( {lastname:'Jansen', firstname:'Erik'});
```

```sql
alter table test alter column name type struct(firstname varchar, lastname varchar, gender varchar);
```

```console
Mismatch Type Error: Type STRUCT(firstname VARCHAR, lastname VARCHAR) does not match with STRUCT(firstname VARCHAR, lastname VARCHAR, gender VARCHAR). Cannot cast STRUCTs of different size
```

### OS:

IOS

### DuckDB Version:

1.1.1

### DuckDB Client:

cli

### Full Name:

Erik Jansen

### Affiliation:

i-Refact

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, changing structs is not supported, so this is expected behavior.

**Comment by ErikJansenIRefact** [comment]
Should I somewhere create a change request such that this is supported in a future release?
