### ISSUE TITLE
Issue found on page 'WITH Clause'

### ISSUE THREAD

**Issue by wrb2** [duckdb/duckdb#14250]
> Please describe the problem you encountered in the DuckDB documentation and include the "Page URL" link shown below.

When running the query 

> [Enumerate All Paths from a Node](https://duckdb.org/docs/sql/query_syntax/with#enumerate-all-paths-from-a-node)

I don't actually get the result described. Not sure if this is issue with the query or something else.

See screenshots:

<img width="394" alt="Screenshot 2024-10-05 at 22 54 30" src="https://github.com/user-attachments/assets/85730941-8744-4d3a-812a-0f59cf28ac3d">
<img width="322" alt="Screenshot 2024-10-05 at 22 56 35" src="https://github.com/user-attachments/assets/e27aa2a4-5b73-4493-b33f-4097ce8795b3">

Page URL: <https://duckdb.org/docs/sql/query_syntax/with.html>

**Comment by hannes** [comment]
CC @kryonix

**Comment by kryonix** [comment]
This is related to PR https://github.com/duckdb/duckdb/pull/13406. In this PR, `list_position` has been changed. Instead of returning value `0` to indicate, that a value is not part of a list, now `NULL` is returned.

```
WITH RECURSIVE paths(startNode, endNode, path) AS (
          SELECT -- Define the path as the first edge of the traversal
              node1id AS startNode,
              node2id AS endNode,
              [node1id, node2id] AS path
          FROM edge
          WHERE startNode = 1
          UNION ALL
          SELECT -- Concatenate new edge to the path
              paths.startNode AS startNode,
              node2id AS endNode,
              array_append(path, node2id) AS path
          FROM paths
          JOIN edge ON paths.endNode = node1id
          -- Prevent adding a repeated node to the path.
          -- This ensures that no cycles occur.
          WHERE list_position(paths.path, node2id) IS NULL
      )
  SELECT startNode, endNode, path
  FROM paths
  ORDER BY length(path), path;
```

----

Will be fixed with PR https://github.com/duckdb/duckdb-web/pull/3795

**Comment by wrb2** [comment]
Seems fixed in the docs I see on the webpage. Thank you!
