### ISSUE TITLE
duckdb native file take a lot of space compared to parquet

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#14262]
### What happens?

load the same csv using 
export to parquet : 72 mb
natie file               :  450 mb

### To Reproduce

https://drive.google.com/file/d/1N8oZYPT3oK5S4HwYdss9DQC_PJGTb9be/view?usp=sharing

### OS:

linux

### DuckDB Version:

1.1.1

### DuckDB Client:

Python

### Full Name:

Mim

### Affiliation:

personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
This is expected, you are enabling `COMPRESSION 'zstd'` on the generated Parquet file. DuckDB's native format currently does not expect heavy compression like that.
