### ISSUE TITLE
Decimal to double conversion results in slightly incorrect values

### ISSUE THREAD

**Issue by PaulCherian** [duckdb/duckdb#14387]
### What happens?

Casting a decimal column from a parquet dataset to double results in slightly incorrect values

### To Reproduce

```
 import pandas as pd
import duckdb
import pyarrow as pa
import os
from decimal import Decimal, getcontext

getcontext().prec = 20

PARQUET_FOLDER_PATH = '<put file path here>'
column = [Decimal(x) / Decimal(1.0) for x in range(2806)]
df = pd.DataFrame({
  'decimal_column': column
})
schema = pa.schema([('decimal_column', pa.decimal128(38, 18))])
parquet_file_path = os.path.join(PARQUET_FOLDER_PATH, 'test.parquet')
df.to_parquet(parquet_file_path, schema=schema)
duckdb_connection = duckdb.connect()
output = duckdb_connection.sql('SELECT CAST("decimal_column" as double) as casted_column from read_parquet("{}")'.format(parquet_file_path))
duckdb_connection.close()
```
If you print `output`, you can see that 2805.0 in being displayed as 2804.9999999999995, 2803 as 2803.0000000000005 and so on. 

### OS:

ios, centos

### DuckDB Version:

1.1

### DuckDB Client:

python

### Full Name:

Paul Cherian

### Affiliation:

Qualtrics

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @PaulCherian – I'm not yet able to reproduce this. Adding the following print block produces the output below:

```python
print(duckdb.__version__)
print(pa.__version__)
print(output)
```

```console
1.1.2
17.0.0
```
┌───────────────┐
│ casted_column │
│    double     │
├───────────────┤
│           0.0 │
│           1.0 │
│           2.0 │
│           3.0 │
│           4.0 │
│           5.0 │
│           6.0 │
│           7.0 │
│           8.0 │
│           9.0 │
│            ·  │
│            ·  │
│            ·  │
│        2796.0 │
│        2797.0 │
│        2798.0 │
│        2799.0 │
│        2800.0 │
│        2801.0 │
│        2802.0 │
│        2803.0 │
│        2804.0 │
│        2805.0 │
├───────────────┤
│   2806 rows   │
│  (20 shown)   │
└───────────────┘
```

**Comment by PaulCherian** [comment]
My bad, I checked my version again and I was on duckdb 1.0. You are right, the issue looks to have been fixed in the latest version. Thanks for looking in to this. I will close this ticket.

**Comment by PaulCherian** [comment]
@szarnyasg would you by any change know what has changed between version 1.0 and 1.1.2 that would have fixed this issue, I couldn't find the fix explicitly listed out in the changelog?

**Comment by szarnyasg** [comment]
Sorry, I'm not aware of the exact PR that fixed this.
