### ISSUE TITLE
`read_csv` does not detect columns correctly with `rejects_table`

### ISSUE THREAD

**Issue by darthf1** [duckdb/duckdb#14393]
### What happens?

When reading a specific CSV with `rejects_table`, I get unexpected results. If I remove `rejects_table`, the results are as expected.

### To Reproduce

Run:

```sh
echo "Naam;Rekeningnummer;Omschrijving of betalingskenmerk;Omschrijving of betalingskenmerk aangepast;Transactiestatus;Valuta;Transactiebedrag;Transactiebedrag aangepast;Batchnaam;Gewenste uitvoerdatum;Gewenste uitvoerdatum aangepast;Werkelijke uitvoerdatum;Eigen rekening ccy;Eigen rekening;Eigen rekening naam;Batchtype;Batchstatus;Eerste handtekening;Eerste handtekening datum tijd;Tweede handtekening;Tweede handtekening datum tijd;Bestandsnaam;Controlegetal SHA1;Controlegetal SHA2;Bestand aangepast\nDummy Naam;DUMMYREKENINGNUMMER;1234567890; ;Dummy Transactiestatus;USD;123,45; ;DUMMYBATCHNAAM;2023-01-01; ;2023-01-01;USD;DUMMYEIGENREKENING;Dummy Eigen Rekening Naam;Dummy Batchtype;Dummy Batchstatus; ; ; ; ;dummy_file.xml;DUMMYCHECKSUMSHA1;DUMMYCHECKSUMSHA2;false" > error.csv
```

```sh
v1.1.2 f680b7d08f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
SELECT * FROM read_csv('error.csv');
```
```
┌────────────┬─────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬───┬──────────────────────┬────────────────┬────────────────────┬────────────────────┬───────────────────┐
│    Naam    │   Rekeningnummer    │ Omschrijving of be…  │ Omschrijving of be…  │   Transactiestatus   │ … │ Tweede handtekenin…  │  Bestandsnaam  │ Controlegetal SHA1 │ Controlegetal SHA2 │ Bestand aangepast │
│  varchar   │       varchar       │        int64         │       varchar        │       varchar        │   │       varchar        │    varchar     │      varchar       │      varchar       │      boolean      │
├────────────┼─────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼───┼──────────────────────┼────────────────┼────────────────────┼────────────────────┼───────────────────┤
│ Dummy Naam │ DUMMYREKENINGNUMMER │           1234567890 │                      │ Dummy Transactiest…  │ … │                      │ dummy_file.xml │ DUMMYCHECKSUMSHA1  │ DUMMYCHECKSUMSHA2  │ false             │
├────────────┴─────────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴───┴──────────────────────┴────────────────┴────────────────────┴────────────────────┴───────────────────┤
│ 1 rows                                                                                                                                                                                    25 columns (10 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
```sql
SELECT * FROM read_csv('error.csv', rejects_table='rejects_table');
```
```
┌──────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Dummy Naam;DUMMYRE…  │ 45; ;DUMMYBATCHNAAM;2023-01-01; ;2023-01-01;USD;DUMMYEIGENREKENING;Dummy Eigen Rekening Naam;Dummy Batchtype;Dummy Batchstatus; ; ; ; ;dummy_file.xml;DUMMYCHECKSUMSHA1;DUMMYCHECKSUMSHA2;f…  │
│       varchar        │                                                                                            varchar                                                                                            │
├──────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Dummy Naam;DUMMYRE…  │ 45; ;DUMMYBATCHNAAM;2023-01-01; ;2023-01-01;USD;DUMMYEIGENREKENING;Dummy Eigen Rekening Naam;Dummy Batchtype;Dummy Batchstatus; ; ; ; ;dummy_file.xml;DUMMYCHECKSUMSHA1;DUMMYCHECKSUMSHA2;f…  │
└──────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

With `rejects_table`, it shows the results as separated with a comma. But with `sniff_csv`, you can see both delimiters are correctly detected:

```sh
v1.1.2 f680b7d08f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```
```sql
SELECT * FROM sniff_csv('error.csv');
```
```
┌───────────┬─────────┬─────────┬──────────────────┬─────────┬───┬────────────┬─────────────────┬───────────────┬──────────────────────┐
│ Delimiter │  Quote  │ Escape  │ NewLineDelimiter │ Comment │ … │ DateFormat │ TimestampFormat │ UserArguments │        Prompt        │
│  varchar  │ varchar │ varchar │     varchar      │ varchar │   │  varchar   │     varchar     │    varchar    │       varchar        │
├───────────┼─────────┼─────────┼──────────────────┼─────────┼───┼────────────┼─────────────────┼───────────────┼──────────────────────┤
│ ;         │ "       │ "       │ \n               │ \0      │ … │ %Y-%m-%d   │                 │               │ FROM read_csv('err…  │
├───────────┴─────────┴─────────┴──────────────────┴─────────┴───┴────────────┴─────────────────┴───────────────┴──────────────────────┤
│ 1 rows                                                                                                          12 columns (9 shown) │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
```sql
SELECT * FROM sniff_csv('error.csv', rejects_table='rejects_table');
```
```
┌───────────┬─────────┬─────────┬──────────────────┬─────────┬───┬────────────┬─────────────────┬──────────────────────┬──────────────────────┐
│ Delimiter │  Quote  │ Escape  │ NewLineDelimiter │ Comment │ … │ DateFormat │ TimestampFormat │    UserArguments     │        Prompt        │
│  varchar  │ varchar │ varchar │     varchar      │ varchar │   │  varchar   │     varchar     │       varchar        │       varchar        │
├───────────┼─────────┼─────────┼──────────────────┼─────────┼───┼────────────┼─────────────────┼──────────────────────┼──────────────────────┤
│ ;         │ "       │ "       │ \n               │ \0      │ … │ %Y-%m-%d   │                 │ rejects_table='rej…  │ FROM read_csv('err…  │
├───────────┴─────────┴─────────┴──────────────────┴─────────┴───┴────────────┴─────────────────┴──────────────────────┴──────────────────────┤
│ 1 rows                                                                                                                 12 columns (9 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Bonus question ^^: in the original file, each line is enclosed with a ". So each line starts with a ", and ends with a ", and there are no " in between. Is there a way to detect this, and clean this with duckdb? Now I do this step separately in python.

### OS:

x86_64

### DuckDB Version:

1.1.2

### DuckDB Client:

CLI

### Full Name:

Frank Verschuren

### Affiliation:

1 Giant Leap Solutions

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @darthf1,

First, thanks for providing an easy-to-reproduce example! :-)

The `rejects_table` has the same effect on the sniffer as setting `ignore_errors=true`. So, the results you see from `FROM read_csv('error.csv', rejects_table='rejects_table');` are correct.

However, the results from `FROM sniff_csv('error.csv', rejects_table='rejects_table');` do indicate a bug. The `rejects_table` correctly sets `ignore_errors` in `read_csv` but not in `sniff_csv`. I'll fix that shortly.

To clarify:
`FROM sniff_csv('error.csv', rejects_table='rejects_table');` should return the same as:
`FROM sniff_csv('error.csv', ignore_errors=true);`
which is:
`, " " \n \0 0 true [{'name': Dummy Naam;DUMMYREKENINGNUMMER;1234567890; ;Dummy Transactiestatus;USD;123, 'type': VARCHAR}, {'name': 45; ;DUMMYBATCHNAAM;2023-01-01; ;2023-01-01;USD;DUMMYEIGENREKENING;Dummy Eigen Rekening Naam;Dummy Batchtype;Dummy Batchstatus; ; ; ; ;dummy_file.xml;DUMMYCHECKSUMSHA1;DUMMYCHECKSUMSHA2;false, 'type': VARCHAR}] NULL NULL ignore_errors=true FROM read_csv('error.csv', auto_detect=false, delim=',', quote='"', escape='"', new_line='\n', skip=0, comment='', header=true, columns={'Dummy Naam;DUMMYREKENINGNUMMER;1234567890; ;Dummy Transactiestatus;USD;123': 'VARCHAR', '45; ;DUMMYBATCHNAAM;2023-01-01; ;2023-01-01;USD;DUMMYEIGENREKENING;Dummy Eigen Rekening Naam;Dummy Batchtype;Dummy Batchstatus; ; ; ; ;dummy_file.xml;DUMMYCHECKSUMSHA1;DUMMYCHECKSUMSHA2;false': 'VARCHAR'}, ignore_errors=true);`

Regarding your additional question: if I understand correctly, you're saying that the original data might contain non-escaped quotes within quoted values, e.g., `" bla " bla"`. If so, the CSV reader within DuckDB isn't currently equipped to handle this easily, and it would likely throw an error. Ignoring or cleaning them before or after processing is the best approach at this time.

That said, I've started working on a new project to automatically clean up these kinds of errors, though it will still take some time before it sees the light of day. (:

**Comment by darthf1** [comment]
Hi @pdet,

I read what your saying, but I don't quite understand :). From my perspective, the file is not an invalid CSV file, it just has `;` as a delimiter. Why should setting `rejects_table` or `ignore_errors` have any effect at all and not just return `;` as a delimiter in all cases?

> Regarding your additional question: if I understand correctly, you're saying that the original data might contain non-escaped quotes within quoted values, e.g., " bla " bla". If so, the CSV reader within DuckDB isn't currently equipped to handle this easily, and it would likely throw an error. Ignoring or cleaning them before or after processing is the best approach at this time.

The data is formatted like this:

```csv
"header1;header2;header3"
"value1;value2;value3"
"value1;value2;value3"
"value1;value2;value3"
```
I now parse the CSV file via python separately, and check if the first and last character of a line is `"`, and if there are only 2 of those in a line. Not really foolproof.

**Comment by pdet** [comment]
> Hi @pdet,
> 
> I read what your saying, but I don't quite understand :). From my perspective, the file is not an invalid CSV file, it just has `;` as a delimiter. Why should setting `rejects_table` or `ignore_errors` have any effect at all (for this file) and not just return `;` as a delimiter in all statements, instead of only where `rejects_table` and `ignore_errors` are not set?
> 
> > Regarding your additional question: if I understand correctly, you're saying that the original data might contain non-escaped quotes within quoted values, e.g., " bla " bla". If so, the CSV reader within DuckDB isn't currently equipped to handle this easily, and it would likely throw an error. Ignoring or cleaning them before or after processing is the best approach at this time.
> 
> Apologies for not being clear enough; the data is formatted like this:
> 
> ```
> "header1;header2;header3"
> "value1;value2;value3"
> "value1;value2;value3"
> "value1;value2;value3"
> ```
> 
> I now parse the CSV file via python separately, and check if the first and last character of a line is `"`, and if there are only 2 of those in a line. Not really foolproof.

Oh yeah, you are absolutely right, sorry I had understood that the file had some kind of inconsistency.
The sniffer should be able to pick this up correctly, even with ignore_errors on, I'll have a look.

**Comment by Arengard** [comment]
The CSV is incorrectly formatted.”  working on Mac
```
csv_1
"header1";"header2";"header3"
"value1;"value2;"value3"
"value1";"value2;"value3"
"value1";"value2;"value3"

csv_2
header1;header2;header3
value1;"value2;"value3
value1;"value2;"value3
value1;"value2;"value3
```

**Comment by pdet** [comment]
> "header1;header2;header3"
> "value1;value2;value3"
> "value1;value2;value3"
> "value1;value2;value3"

Hi @darthf1, thanks again for opening this issue, I've fixed the problems in a recent PR.

Regarding this specific file
```
"header1;header2;header3"
"value1;value2;value3"
"value1;value2;value3"
"value1;value2;value3"
``` 

The sniffer will automatically detect it a single quoted value. 

An option to bypass this, is to set quotes to empty (e.g., `quote=''`) and to use [string slicing ](https://duckdb.org/docs/sql/functions/char.html#stringbeginend)on the result, to remove the first quote from the first value and the last quote from the last value

**Comment by darthf1** [comment]
Awesome. Thanks for the fix and thanks for the suggestion!

If I may ask; is there a new patch release planned for the near future or is this going to land in the next minor? :)
