### ISSUE TITLE
Crash in debug build

### ISSUE THREAD

**Issue by xolopivo** [duckdb/duckdb#14412]
### What happens?

Running pivot function with group by on non existent column in debug build on Windows fails with debug assertion "Incompatible list iterators"

### To Reproduce

any pivot statement

### OS:

Windows

### DuckDB Version:

1.1.2

### DuckDB Client:

C client

### Full Name:

Alex G

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by xolopivo** [comment]
Here's the example

create table t (col1 integer, col2 integer);
pivot t on col1 using sum(col2) group by zz;

**Comment by Mytherin** [comment]
Thanks for the report!

This query works fine for me. Can you reproduce the issue using an official distribution?

This sounds like there is a problem with your build process (e.g. linking to the C++ standard library).

**Comment by Mytherin** [comment]
Actually after investigating more this does seem to be an issue in the code - we've pushed a fix in https://github.com/duckdb/duckdb/pull/14437
