### ISSUE TITLE
group by a timestamp column in a parquet file can cause the process to crash

### ISSUE THREAD

**Issue by ClockGet** [duckdb/duckdb#14430]
### What happens?

Group by a timestamp column in a parquet file can cause the process to crash.
[demo.parquet.zip](https://github.com/user-attachments/files/17427101/demo.zip)

### To Reproduce

```sql
SELECT a FROM 'demo.parquet' GROUP BY a;
```

### OS:

windows 11, x86_64

### DuckDB Version:

1.1.2

### DuckDB Client:

CLI

### Full Name:

Jason Jia

### Affiliation:

personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report!

The provided parquet file is actually corrupt - the statistics are invalid:

```sql
D SELECT COLUMNS('stats*') FROM parquet_metadata('data/parquet-testing/corrupt_stats.parquet');
┌─────────────────────┬─────────────────────┬──────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│      stats_min      │      stats_max      │ stats_null_count │ stats_distinct_count │   stats_min_value   │   stats_max_value   │
│       varchar       │       varchar       │      int64       │        int64         │       varchar       │       varchar       │
├─────────────────────┼─────────────────────┼──────────────────┼──────────────────────┼─────────────────────┼─────────────────────┤
│ 2021-01-01 04:00:00 │ 2021-01-01 04:00:00 │                0 │                    1 │ 2021-01-01 04:00:00 │ 2021-01-01 04:00:00 │
│ 2021-01-01 04:00:00 │ 2021-01-01 04:00:00 │                1 │                    1 │ 2021-01-01 04:00:00 │ 2021-01-01 04:00:00 │
└─────────────────────┴─────────────────────┴──────────────────┴──────────────────────┴─────────────────────┴─────────────────────┘
D SELECT * FROM 'data/parquet-testing/corrupt_stats.parquet';
┌─────────────────────┬─────────────────────┐
│          A          │          B          │
│      timestamp      │      timestamp      │
├─────────────────────┼─────────────────────┤
│ 2021-01-01 12:00:00 │ NULL                │
│ 2021-01-01 12:00:00 │ 2021-01-01 12:00:00 │
│ 2021-01-01 12:00:00 │ 2021-01-01 12:00:00 │
│ 2021-01-01 12:00:00 │ 2021-01-01 12:00:00 │
│ 2021-01-01 12:00:00 │ 2021-01-01 12:00:00 │
└─────────────────────┴─────────────────────┘
```

DuckDB uses these statistics to make optimization decisions that in this case lead to a problem. I've pushed a fix in #14442 that now throws an exception in this case:

```
D SELECT a FROM 'data/parquet-testing/corrupt_stats.parquet' GROUP BY a;
Invalid Input Error: Perfect hash aggregate: aggregate group 28800000001 exceeded total groups 4. This likely means that the statistics in your data source are corrupt.
* PRAGMA disable_optimizer to disable optimizations that rely on correct statistics
```

As a work-around, you can use `PRAGMA disable_optimizer`.

However, I would also have a look at who wrote this Parquet file - as that writer seems to have a bug that is causing it to write corrupt Parquet files.
