### ISSUE TITLE
Help Connecting to duckdb in vscode connections panel

### ISSUE THREAD

**Issue by verajosemanuel** [duckdb/duckdb#1443]
I use vscode for programming and very happy with it.
I tend to use sql connections panel for mysql, postgresql and SQLite but I want to create a connection element in that panel to DuckDb.
I assume I have to use it with jdbc driver but no clue so far.

any suggestion will be much appreciated

regards

**Comment by hannesmuehleisen** [comment]
I could not see any generic JDBC/ODBC options in VS Code. So it looks like we would need to ship our own extension. For me that's out of scope but if anyone wants to have a go please do.
