### ISSUE TITLE
failed to build from source in windows

### ISSUE THREAD

**Issue by walterhong** [duckdb/duckdb#14456]
### What happens?

I followed the link：https://duckdb.org/docs/dev/building/build_instructions#windows to build duckdb 1.1.2 from source in windows，except that I changed CMAKE_BUILD_TYPE from Release to Debug. All the thing went well, but at the stage of linking, a lot of undefined reference errors occured.
The steps I used to build from source is shown as below:
1、cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=D:/software/msys2/msys2/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=D:/software/msys2/msys2/mingw64/bin/g++.exe -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXTENSIONS=icu;parquet;json -DCMAKE_MAKE_PROGRAM=D:\software\msys2\msys2\mingw64\bin\ninja.exe -S D:\software\msys2\msys2\home\16282\duckdb -B D:\software\msys2\msys2\home\16282\duckdb\cmake-build-debug
2、cmake --build "D:\software\msys2\msys2\home\16282\duckdb\cmake-build-debug" -j 1 --config Debug

Part of the errors are show as below:
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_stat

### To Reproduce

1、cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=D:/software/msys2/msys2/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=D:/software/msys2/msys2/mingw64/bin/g++.exe -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXTENSIONS=icu;parquet;json -DCMAKE_MAKE_PROGRAM=D:\software\msys2\msys2\mingw64\bin\ninja.exe -S D:\software\msys2\msys2\home\16282\duckdb -B D:\software\msys2\msys2\home\16282\duckdb\cmake-build-debug
2、cmake --build "D:\software\msys2\msys2\home\16282\duckdb\cmake-build-debug" -j 1 --config Debug

### OS:

windows

### DuckDB Version:

1.1.2

### DuckDB Client:

shell

### Full Name:

hong warren

### Affiliation:

jianxin Fintech

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by walterhong** [comment]
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKN6duckdb8string_tENS2_11PointerLessIS5_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<duckdb::string_t const*, duckdb::PointerLess<duckdb::string_t const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKN6duckdb7dtime_tENS2_11PointerLessIS5_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<duckdb::dtime_t const*, duckdb::PointerLess<duckdb::dtime_t const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKN6duckdb11timestamp_tENS2_11PointerLessIS5_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<duckdb::timestamp_t const*, duckdb::PointerLess<duckdb::timestamp_t const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKN6duckdb6date_tENS2_11PointerLessIS5_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<duckdb::date_t const*, duckdb::PointerLess<duckdb::date_t const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKN6duckdb9hugeint_tENS2_11PointerLessIS5_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<duckdb::hugeint_t const*, duckdb::PointerLess<duckdb::hugeint_t const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKxN6duckdb11PointerLessIS3_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<long long const*, duckdb::PointerLess<long long const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKiN6duckdb11PointerLessIS3_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<int const*, duckdb::PointerLess<int const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKsN6duckdb11PointerLessIS3_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<short const*, duckdb::PointerLess<short const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKdN6duckdb11PointerLessIS3_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<double const*, duckdb::PointerLess<double const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list8HeadNodeIPKfN6duckdb11PointerLessIS3_EEEE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::HeadNode<float const*, duckdb::PointerLess<float const*> >'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN6duckdb25ReservoirQuantileBindDataE+0x8): undefined reference to `typeinfo name for duckdb::ReservoirQuantileBindData'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN6duckdb27ApproximateQuantileBindDataE+0x8): undefined reference to `typeinfo name for duckdb::ApproximateQuantileBindData'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN18duckdb_skiplistlib9skip_list10ValueErrorE+0x8): undefined reference to `typeinfo name for duckdb_skiplistlib::skip_list::ValueError'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_aggr_holistic.cpp.obj):ub_duckdb_aggr_holistic.cpp:(.rdata$_ZTIN6duckdb16QuantileBindDataE+0x8): undefined reference to `typeinfo name for duckdb::QuantileBindData'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_func_table.cpp.obj):ub_duckdb_func_table.cpp:(.rdata$.refptr._ZTVN6duckdb19SimpleMultiFileListE[.refptr._ZTVN6duckdb19SimpleMultiFileListE]+0x0): undefined reference to `vtable for duckdb::SimpleMultiFileList'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/libduckdb_static.a(ub_duckdb_common_arrow.cpp.obj):ub_duckdb_common_arrow.cpp:(.rdata$.refptr._ZTVN6duckdb14ChunkScanStateE[.refptr._ZTVN6duckdb14ChunkScanStateE]+0x0): undefined reference to `vtable for duckdb::ChunkScanState'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: extension/parquet/libparquet_extension.a(parquet_extension.cpp.obj):parquet_extension.cpp:(.rdata$.refptr._ZTVN6duckdb20CompressedFileSystemE[.refptr._ZTVN6duckdb20CompressedFileSystemE]+0x0): undefined reference to `vtable for duckdb::CompressedFileSystem'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: extension/parquet/libparquet_extension.a(parquet_extension.cpp.obj):parquet_extension.cpp:(.rdata$.refptr._ZTVN6duckdb10FileSystemE[.refptr._ZTVN6duckdb10FileSystemE]+0x0): undefined reference to `vtable for duckdb::FileSystem'
D:/software/msys2/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: extension/parquet/libparquet_extension.a(zstd_file_system.cpp.obj):zstd_file_system.cpp:(.rdata$.refptr._ZTVN6duckdb13StreamWrapperE[.refptr._ZTVN6duckdb13StreamWrapperE]+0x0): undefined reference to `vtable for duckdb::StreamWrapper'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by szarnyasg** [comment]
Hi, I updated the build instructions on Windows: https://github.com/duckdb/duckdb-web/pull/3887
Please try creating a debug build with the VS toolchain instead of MINGW64.

**Comment by walterhong** [comment]
thanks a lot, I will try the new build instructions today, and give feed back here.

**Comment by walterhong** [comment]
I have tried the new build instructions, and success build duckdb in debug type. I put the build steps I used here for anyone who needs them.
1. prerequisite:
(1) clion(https://www.jetbrains.com/clion/promo/?source=google&medium=cpc&campaign=APAC_en_ASIA_Clion_Branded&term=clion&content=489240779651&gad_source=1&gclid=Cj0KCQjw99e4BhDiARIsAISE7P-QlxcY8Ps6so_3klV9Gpt3iE_GwxEGy6csoe4a05YXNal5bC5_BqYaAoKHEALw_wcB),
(2) visual studio(https://visualstudio.microsoft.com/zh-hans/vs/)
https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html#MSVC
2. build steps:
(1) open clion
(2) choose open
(3) select the cmakelist.txt in duckdb project directory
(4) select open as project
(5) select trust project
(6)
![image](https://github.com/user-attachments/assets/30724542-270b-4578-9c7c-810dd281c486)
click manage toolchain
(7)
![image](https://github.com/user-attachments/assets/c13d86f9-feb0-458c-be11-c305b6d1bc1a)
 after selecting visual studio install directory, clion will auto detect visual studio toolchain.
(8)
![image](https://github.com/user-attachments/assets/ba84ccd5-1bd0-4188-944c-eb268a378484)
put the instructions shown above into cmake options and build options 
(9) apply and exit
(10) clion will auto config the duckdb project
(11) click build and clion will do all the build work for you!

**Comment by szarnyasg** [comment]
Thanks for sharing the instructions!
