### ISSUE TITLE
Python api alter dataframes

### ISSUE THREAD

**Issue by moheikal** [duckdb/duckdb#14479]
### What happens?

DuckDB does not alter dataframes. Erorr BinderException: Binder Error: Can only delete from base table!

```
import duckdb

con = duckdb.connect()

df= con.read_csv('df.csv')

con.execute('DELETE FROM df WHERE i=4')
```

[df.csv](https://github.com/user-attachments/files/17466051/df.csv)

### To Reproduce

n/a

### OS:

Windows

### DuckDB Version:

1.1.2

### DuckDB Client:

Python

### Hardware:

AMD Ryzen 7

### Full Name:

Mohamed Heikal

### Affiliation:

Own business

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @moheikal, thanks for raising this issue. This is currently expected behavior: dataframes are treated as read-only by DuckDB.
