### ISSUE TITLE
Aggregate functions in pivot statement

### ISSUE THREAD

**Issue by xolopivo** [duckdb/duckdb#14481]
### What happens?

Not sure if this is by design but inside pivot statement it's not possible to cast results of aggregate functions.
For example following statement causes error: Pivot expression must be an aggregate
 pivot algoorder on clientid using sum(orderqty)::INT64

### To Reproduce

pivot algoorder on clientid using sum(orderqty)::INT64

### OS:

Windows

### DuckDB Version:

1.1.2

### DuckDB Client:

C

### Full Name:

Alex G

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
I think fixed via https://github.com/duckdb/duckdb/pull/14800
