### ISSUE TITLE
Inability to write to parquet file when filename is stored as VARIABLE

### ISSUE THREAD

**Issue by mtsardakas** [duckdb/duckdb#14490]
### What happens?

While storing the path of a local file in a `VARIABLE` works great for `read_parquet`/`read_csv`, it's impossible to use it when exporting data.

### To Reproduce

```
CREATE TABLE sample_table (
    sample_column TEXT
);

INSERT INTO sample_table (sample_column)
VALUES ('Row 1'), ('Row 2');

SET VARIABLE filename = 'local_file.parquet';
-- Line below works fine
COPY (SELECT * FROM sample_table) TO 'local_file.parquet';
-- Line below fails with 
-- Parser Error: syntax error at or near "'filename'"
-- LINE 1: ...CT * FROM sample_table) TO getvariable('filename');
COPY (SELECT * FROM sample_table) TO getvariable('filename');
```

This is not the case for `read_parquet` as this can handle variables fine. Same holds when reading/writing to csv too.

### OS:

MacOS 4.6.1 (23G93)

### DuckDB Version:

v1.1.2 f680b7d08f

### DuckDB Client:

CLI

### Full Name:

Michael Tsardakas

### Affiliation:

Gower Stree Analytics

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @mtsardakas thanks for opening this issue. This is very likely an expected limitation: the `COPY` statement expects a string literal as its target.

**Comment by Maxxen** [comment]
Duplicate of this discussion https://github.com/duckdb/duckdb/discussions/14006

**Comment by mtsardakas** [comment]
Closing in favour of https://github.com/duckdb/duckdb/discussions/14006
