### ISSUE TITLE
IO Error: No space left on device

### ISSUE THREAD

**Issue by chenyangkang** [duckdb/duckdb#14501]
### What happens?

I was partitioning a csv file into 10000+ partitions using python API. After hours of run, it raised error: `duckdb.duckdb.IOException: IO Error: Cannot open file "../XXX.parquet": No space left on device`.

I checked with myself and contact with technique guys and we both confirmed that my account on the HPC still has a large storage space, which should be enough to run this job.

### To Reproduce

```py
# %%
import numpy as np
import duckdb
import pandas as pd
import glob

# configuration
duckdb.sql("SET threads TO 10")
duckdb.sql("SET memory_limit = '50GB'")
duckdb.sql("SET temp_directory = '/home/yc85/scratch/XXX'") # scratch is a soft link from /scratch/users/XXX

duckdb.sql("select current_setting('threads')")
duckdb.sql("select current_setting('memory_limit')")
duckdb.sql("select current_setting('temp_directory')")

query = """
COPY (
    SELECT 
        "A", "B", "C"
    FROM 
        read_csv('../../XXX.txt', delim = '\t', header = true)
) TO '../../prepartitioned_XXX_data/' 
    (FORMAT PARQUET, PARTITION_BY "B", OVERWRITE_OR_IGNORE);
"""
duckdb.sql(query)

```

The slurm script to submit this:
```bash
#!/bin/bash
#SBATCH --partition=aces       # Partition name
#SBATCH --ntasks=1                # Run on a single CPU
#SBATCH --cpus-per-task=10         # Number of CPU cores per task
#SBATCH --time=07-00:00:00      # 7days
#SBATCH --mem=50GB                  # Total memory for job
##SBATCH --output=/home/XXX/scratch/%j.log    # Standard output and error log
#SBATCH --mail-type=ALL           # Send email on all job events (BEGIN, END, FAIL)
#SBATCH --mail-user=yc85@illinois.edu  # Email address to notify

source activate base

python -u run_partitioning.py



```

### OS:

x86_64

### DuckDB Version:

1.1.2

### DuckDB Client:

Python

### Hardware:

Slurm system. Job submitted through sbatch.

### Full Name:

Yangkang Chen

### Affiliation:

University of Illinois Urbana Champaign

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot easily share my data sets due to their large size

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @chenyangkang, thanks for opening this issue. Unfortunately, this is nearly impossible for us to reproduce as we do not have a Slurm cluster or the exact workload. It may also be a problem with the underlying disk system (or the disk system's interaction with DuckDB). I understand if this is frustrating but there's just no way we can reproduce this based on the available information and therefore we're not able to fix it.
