### ISSUE TITLE
CatalogException: Catalog Error: Scalar Function with name date does not exist! Did you mean "age"?

### ISSUE THREAD

**Issue by cppt** [duckdb/duckdb#14518]
### What happens?

Recently installed `duckdb` and trying to demo its usage but getting an error with a simple join.

This:
```
s = '''
select a.ticker, a.clean_pub_date, a.trade_id, a.wgt, b.Date, b.value
from trade_list a
left join cr_melt b
on a.ticker = b.variable
and b.Date between a.clean_pub_date and DATE(a.clean_pub_date, '+1 year')
and a.clean_pub_date >= '2020-12-01'

'''

newdf = duckdb.query(s)
```
Gives this error:
```
CatalogException: Catalog Error: Scalar Function with name date does not exist!
Did you mean "age"?
```

My query doesn't contain any reference to 'date' so not clear what it's communicating.  

Have tried a simple test case and it works without issue:
`newdf = duckdb.query('select * from trade_list where 1=1').df()`

Completes successfully and returns the contents of the `trade_list` df.  

Any guidance on what this error indicates.

### To Reproduce

```
import pandas as pd
import duckdb

s = '''
select a.ticker, a.clean_pub_date, a.trade_id, a.wgt, b.Date, b.value
from trade_list a
left join cr_melt b
on a.ticker = b.variable
and b.Date between a.clean_pub_date and DATE(a.clean_pub_date, '+1 year')
and a.clean_pub_date >= '2020-12-01'
'''

newdf = duckdb.query(s).df()
```

### OS:

Ubuntu 22.04

### DuckDB Version:

0.10.3

### DuckDB Client:

Python

### Full Name:

Chris

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot easily share my data sets due to their large size

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
It seems the `DATE(a.clean_pub_date, '+1 year')` is interpreted as a function
Try something like `DATE a.clean_pub_date + INTERVAL 1 YEAR` (https://duckdb.org/docs/sql/functions/date).

**Comment by cppt** [comment]
Thanks a bunch, the below worked:

```
s = '''
select a.ticker, a.clean_pub_date, a.trade_id, a.wgt, b.Date, b.value
from trade_list a
left join cr_melt b
on a.ticker = b.variable
and b.Date between a.clean_pub_date and date_add(a.clean_pub_date, '1 YEAR')
and a.clean_pub_date >= '2020-12-01'

'''

newdf = duckdb.query(s).df()
```
