### ISSUE TITLE
std::bad_cast raised when getting file from s3

### ISSUE THREAD

**Issue by etorreborre** [duckdb/duckdb#14529]
### What happens?

I am trying to read files from s3 and I'm getting the following error `Invalid error: std::bad_cast`.

### To Reproduce

Here is an example of a session:
```
D INSTALL aws; LOAD aws; LOAD httpfs;
D CREATE SECRET (TYPE S3, PROVIDER credential_chain, CHAIN 'sso', PROFILE 'prod', REGION 'us-west-1');
D SELECT * from read_csv('s3://my-bucket/my-file');
Invalid Error: std::bad_cast
```

With the nightly build I am getting a HTTP 403 error.

### OS:

MacOS M2

### DuckDB Version:

1.1.2, 1.1.1, 1.0.0, 0.10.2

### DuckDB Client:

duckdb

### Full Name:

Eric Torreborre

### Affiliation:

ockam.io

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by etorreborre** [comment]
I can confirm that I eventually made it work with the nightly build `v1.1.3-dev56 39f9863ef8`.

**Comment by carlopi** [comment]
I think this has been solved in v1.1.3, published earlier today.

**Comment by etorreborre** [comment]
Thanks @carlopi.

**Comment by carlopi** [comment]
I think fix was from @Mytherin in https://github.com/duckdb/duckdb/pull/14585
