### ISSUE TITLE
Scoping problem with function argument

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#14563]
### What happens?

Somehow, `z` seems to disappear:
```sql
create or replace function demo(n, z) as table (
  select list_transform(range(0,n), x -> z) as row
);  

from demo(3,0);
```
```
Binder Error: Referenced column "z" not found in FROM clause!
```

### To Reproduce

```sql
create or replace function demo(n, z) as table (
  select list_transform(range(0,n), x -> z) as row
);  

from demo(3,0);
```

### OS:

macos

### DuckDB Version:

v1.0, v1.1.3-dev38 │

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by lcostantino** [comment]
If it helps, this seems to work when adding the var within an expression (0+z, x-z, etc)

create or replace function demo(n, z) as table (
    select list_transform(range(0,n), x -> 0+z) as row
  );  
D from demo(3,1);
┌───────────┐
│    row    │
│  int32[]  │
├───────────┤
│ [1, 1, 1] │
└───────────┘

**Comment by pkoppstein** [comment]
@lcostantino - Good to know, thanks. I was able to find another workaround too (adding a FROM clause).  Hopefully the problem will be easy for the gurus to fix.
