### ISSUE TITLE
Left join with subquery exception on empty tables

### ISSUE THREAD

**Issue by xolopivo** [duckdb/duckdb#14582]
### What happens?

Left join with subquery on empty tables causes substract overflow exception:

```cpp
if (!TrySubtractOperator::Operation(left, right, result)) {
	throw OutOfRangeException("Overflow in subtraction of %s (%s - %s)!", TypeIdToString(GetTypeId<TA>()),
			                        NumericHelper::ToString(left), NumericHelper::ToString(right));
}
```

### To Reproduce

```sql
create table t1 (id integer, revision integer, col integer);
create table t2 (id integer, revision integer, col1 integer);

select col, col1 from t1
  left join t2 on t1.id = t2.id
    and t1.revision = t2.revision
where t1.revision = (select max(z.revision) from t1 z where z.id = t1.id);
```

### OS:

Windows

### DuckDB Version:

1.1.2

### DuckDB Client:

C API

### Full Name:

Aex G

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @xolopivo I tried reproducing this issue on Windows and on macOS using the debug build but was not successful. Are you using the C API or the CLI client? Is there any date in the tables?

**Comment by xolopivo** [comment]
Tables are empty. Using C API building from source on Windows. Tables created exactly as above. Source is from 1.1.2
For me it happens consistently. After tables populated with some data it goes away

**Comment by szarnyasg** [comment]
Thanks for the clarification. Three questions:
1. Which compiler are you using?
2. Which architecture are you using (AMD64 / AArch64)?
3. Can you please provide the complete C file for reproduction?

**Comment by xolopivo** [comment]
1. Latest Visual Studio version
2. x64
3. There's nothing special. I just call duckdb_query
One note. The exception itself is not causing query to return DuckDbErro. It's somehow handled inside. It's just strange that internally it fails with OutOfRangeException

**Comment by szarnyasg** [comment]
Hi @xolopivo, this is expected behavior. Most likely what's happening is that this is an exception that is caught internally but shows up in the debugger.
