### ISSUE TITLE
Support for explicit schema in column reference

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#146]
```sql
CREATE SCHEMA a;
CREATE SCHEMA b;
CREATE TABLE a.integers(i INTEGER);
CREATE TABLE b.integers(i INTEGER);
INSERT INTO a.integers VALUES (3);
INSERT INTO b.integers VALUES (4);
SELECT a.integers.i, b.integers.i FROM a.integers i1, b.integers i2;
-- schema should also be used for aliasing
SELECT a.integers.i, b.integers.i FROM a.integers, b.integers;
```

**Comment by JakeWheat** [comment]
Do you have any advice on how to go about fixing this? I thought of two options, but I have no idea if either make sense (or how to implement them)
1. make sure there's an alias for every tref, then rewrite to use this alias for column refs which have a schema in them
2. change columnref to optionally support a schema part too

These are the files I looked at:
https://github.com/cwida/duckdb/blob/master/src/include/duckdb/parser/expression/columnref_expression.hpp
https://github.com/cwida/duckdb/blob/master/src/parser/transform/expression/transform_columnref.cpp

**Comment by Mytherin** [comment]
There are two components to fixing this. The first is supporting the schema in the column reference. To do that, we would add an extra `schema` qualifier to the column reference (which defaults to empty). When it is not empty, the column reference can **only** match base tables, and needs to match their schema. For example, the following will throw an error:

```sql
-- ERROR: wrong schema
SELECT a.integers.i FROM b.integers;
-- SUCCESS!
SELECT b.integers.i FROM b.integers;
```

That should not be so difficult to implement, and will already be useful for e.g. tools generating queries. 

However, there is one restriction in the binding phase right now that limits its usefulness: aliases need to be unique. This means that table entries with the same name but a different schema cannot co-exist unless they have been given an explicit alias, i.e. this throws an error:

```sql
create schema a;
create schema b;
create table a.integers(i integer);
create table b.integers(i integer);
select * from a.integers, b.integers;
--Binder Error: Duplicate alias "integers" in query!
select * from a.integers, b.integers AS bintegers;
-- SUCCESS!
```

This is a bit harder. I think the first part can be implemented without needing to implement the second part and it would already be useful, however.

**Comment by JakeWheat** [comment]
Is there some documentation or a good place to start in the code to understand the current binding process?
