### ISSUE TITLE
[CSV] INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#14626]
### What happens?

INTERNAL Error: Attempted to dereference unique_ptr that is NULL!
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors

===csv2tsv.csv===
```
a,"
a,"b"
```

### To Reproduce

```
select version();
create or replace table t as
from read_csv('csv2tsv.csv',
   header=false,
   quote='"',
   escape = '"',
   sep=',',
   ignore_errors=true);
```

### OS:

MacOS

### DuckDB Version:

v1.1.3-dev119

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by lcostantino** [comment]
If it's help, in debug the assertion is triggered

/duckdb/src/execution/operator/csv_scanner/sniffer/type_detection.cpp
```
	if (!best_candidate) {
		DialectCandidates dialect_candidates(options.dialect_options.state_machine_options);
		auto error = CSVError::SniffingError(options, dialect_candidates.Print());
		error_handler->Error(error);
	}
	// Assert that it's all good at this point.
	D_ASSERT(best_candidate && !best_format_candidates.empty());
```

I'm not sure how the error is handler in the entire CSV scanner, but the process after TypeDetection continues with TypeRefinement(), etc.. and given the best_candidate is nullptr it fails.
