### ISSUE TITLE
Out of memory message when starting the CLI

### ISSUE THREAD

**Issue by sreeramcoder** [duckdb/duckdb#14636]
### What happens?

When I start duckdb in my debian server, I get the below error at the top

I also get the error with nightly build as of today.

```
machine ~> duckdb
<jemalloc>: Out-of-range conf value: narenas:0
v1.1.2 f680b7d08f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D 
```

### To Reproduce

Happens in debian machine right after starting the cli. 

### OS:

Debian GNU/Linux 12 (bookworm)

### DuckDB Version:

1.1.2

### DuckDB Client:

cli

### Hardware:

below are my server details

Physical memory : 1 GB
1 vCPU of AMD Ryzen 9 3900X 12-Core Processor

### Full Name:

Sreeram V

### Affiliation:

Independent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @sreeramcoder, thanks for reporting this!

Is there a chance that you can produce a debug build? Following the [build instructions](https://duckdb.org/docs/dev/building/build_instructions), it should be as simple as installing a few packages and running the build:

```bash
sudo apt-get update
sudo apt-get install -y git g++ cmake ninja-build libssl-dev wget zip unzip
```
```bash
https://github.com/duckdb/duckdb/archive/refs/heads/main.zip
unzip main.zip
cd duckdb-build
GEN=ninja make debug
build/debug/duckdb
```

Hopefully the output of this has more information on where this is happening.

**Comment by szarnyasg** [comment]
Hi @sreeramcoder, PR #14688 may fix this issue
