### ISSUE TITLE
Sequences in COPY FROM <database>TO <otherDB> causes Dependency Error

### ISSUE THREAD

**Issue by JohnApps** [duckdb/duckdb#14639]
### What happens?

> ./duckdb original.db
v1.1.2 f680b7d08f
Enter ".help" for usage hints.
D create sequence seq start 1;
D create table tbl (id int default nextval('seq'));
D attach 'backup.db';
D copy from database original to backup;
Dependency Error: Error adding dependency for object "tbl" - dependency "seq" is in catalog "original", which does not match the catalog "backup".
Cross catalog dependencies are not supported.

### To Reproduce

```bash
./duckdb original.db
```
```sql
create sequence seq start 1;
create table tbl (id int default nextval('seq'));
attach 'backup.db';
copy from database original to backup;
```
```console
Dependency Error: Error adding dependency for object "tbl" - dependency "seq" is in catalog "original", which does not match the catalog "backup".
Cross catalog dependencies are not supported.
```
### OS:

Windows 10

### DuckDB Version:

1.1.2

### DuckDB Client:

CLI

### Full Name:

johndapps

### Affiliation:

4LP

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Reproduced, thanks!
