### ISSUE TITLE
Copying from Parquet to Parquet causes segfault with big Parquet file

### ISSUE THREAD

**Issue by dforsber** [duckdb/duckdb#1464]
## Parquet to Parquet streaming

I'm running a query in the hopes of being able to filter the results, add `ROW_NUMBER() OVER ()` etc. while copying. This query segfaults on a decent laptop with a 22G source Parquet file (snappy), with 15m rows and a bit less than 300 columns.

However, it maybe that DuckDB tries to read all into memory and not streaming through? (`v0.2.4 d1b02c270`)

```
COPY (SELECT * FROM parquet_scan('source.parquet')) TO 'transformed.parquet' (FORMAT 'parquet', CODEC 'ZSTD');
```

**Comment by dforsber** [comment]
Wondering if the appender could be used to write to Parquet. If yes, then at least getting iterator (stream) from the source parquet and then outputting with appender to target Parquet would not take that much memory (if that's the issue at all).

**Comment by hannesmuehleisen** [comment]
It should be streaming, but if you use window functions you run into #144

**Comment by dforsber** [comment]
It segfaults with that query on the ticket, no window functions.

**Comment by dforsber** [comment]
Anyway, that #144 would be really nice feature 👍🏻 as e.g. Presto (AWS Athena) can't cope with it if the data set is too large as it also tries to read all into memory.

**Comment by hannesmuehleisen** [comment]
Are there very many columns in the file? Right now there is a 100000 row limit to flushing...

**Comment by dforsber** [comment]
Around 300 columns. A wide table yes.

**Comment by dforsber** [comment]
It would explain the situation if the row group doesn't fit into existing buffer as the SEGFAULT happens quite quickly when starting the query.

**Comment by dforsber** [comment]
Another concern for this use case is that if the Parquet reader is using row by row iterator on the source Parquet file, it is by design very slow. For column store Parquet, the stream reader should probably grab data row group by row group (especially with `COPY` and e.g. `SELECT *`). But this may be the case already, I'm not sure.

**Comment by hannesmuehleisen** [comment]
That is already the case

**Comment by dforsber** [comment]
I can confirm that the latest duckdb cli does not have this bug anymore 👍🏻 
`v0.2.5 f480a3293`

**Comment by dforsber** [comment]
This has re-appeared on 0.2.6, at least on the command line client downloadable version.

**Comment by hannesmuehleisen** [comment]
Any more context on this? Something reproducible perhaps?

**Comment by dforsber** [comment]
Seems like the latest master cli build works 👍🏻 .. so, closing this.
