### ISSUE TITLE
[CSV] comment='#' produces `INTERNAL Error`

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#14648]
### What happens?

With v1.1.3-dev119, the comment='#' produces:

```console
INTERNAL Error: Attempted to dereference unique_ptr that is NULL!
```

when read_csv() is given the following two lines as per the program below:

```csv
a,b
a#b
```

### To Reproduce

```sql
select version();
create or replace table t as
from read_csv('comment.csv',
    header=false,
    sep=',',
    comment='#', -- breaks this file when a#b is encountered
    ignore_errors=true
  );
```

### OS:

macos

### DuckDB Version:

v1.1.3-dev119

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by lcostantino** [comment]
This should be fixed by https://github.com/duckdb/duckdb/pull/14661

```
D CREATE OR REPLACE TABLE repromarket_creds AS
  SELECT *
  FROM read_csv('./comment.csv',
    header=false,
      sep=',',
      comment='#', -- breaks this file when a#b is encountered
      ignore_errors=true
    );
Invalid Input Error: Error when sniffing file "./comment.csv".
It was not possible to automatically detect the CSV Parsing dialect/types
The search space used was:
Delimiter Candidates: ','
Quote/Escape Candidates: ['"','"'],['"','\0'],['"','''],['"','\'],[''','\'],['\0','\0']
Comment Candidates: '#'
Possible fixes:
* Delimiter is set to ','. Consider unsetting it.
* Set quote (e.g., quote='"')
* Set escape (e.g., escape='"')
* Comment is set to '#'. Consider unsetting it.
* Set skip (skip=${n}) to skip ${n} lines at the top of the file
* Enable null padding (null_padding=true) to pad missing columns with NULL values
* Check you are using the correct file compression, otherwise set it (e.g., compression = 'zstd')
```

**Comment by pkoppstein** [comment]
@Mytherin - As of v1.1.3-dev158 (Nov 1, 2024), the commit c3ca3607c221d315f38227b8bf58e68746c59083
changes the behavior, but in my view does not address the problem satisfactorily.

That is, the sniffer now fails and exits early, even
when read_csv() is being used with ignore_errors=true

I realize there's a lot of history and complexity here,
but apart from the details of this particular case,
it seems clear that **it should be possible to configure
the CSV reader to ensure that ignore_errors=true has top priority.**

To this end, I would suggest that it should be possible to turn off
the CSV sniffer altogether, e.g. by setting SAMPLE_SIZE=0 and using
read_csv().

As to the details of the particular case, I am not sure
what the intended semantics of `comment='#'` are, but however
one looks at it, it should be easy enough to handle the input line:

a#b

That is, under the interpretation of #-comments as extending to the end of the
line, the DuckDB sniffer and reader should see the line simply as 'a'
and processing as appropriate from then on.

And under the interpretation of #-commands as requiring the # to be the
first (or first non-blank) character, the DuckDB sniffer and reader
should presumably treat the embedded # as it would any other character.


The problem, as of v1.1.3-dev158 (Nov 1, 2024) is that
the input file comment.csv causes processing to stop with
the message:

Invalid Input Error: Error when sniffing file "comment.csv".

===Input file: comment.csv===
```
a,b
a#b
x,y
```
===Program===
```
select version();
create or replace table t as
from read_csv('comment.csv',
   header=false,
   sep=',',
   null_padding=true,
   comment='#',
   ignore_errors=true
   );
```

**Comment by lcostantino** [comment]
You are right there are different problems, the behavior changed is to stop propagating a NULL ptr that will crash.

Without that fix, in debug mode the processing will stop there (at the same place there's a change)

	// Assert that it's all good at this point.
	D_ASSERT(best_candidate && !best_format_candidates.empty());


INTERNAL Error: Assertion triggered in file "/Users/lcostant/repos/duckdb/src/execution/operator/csv_scanner/sniffer/type_detection.cpp" on line 494: best_candidate && !best_format_candidates.empty()

**Comment by lcostantino** [comment]
@pkoppstein  you can "somehow" disable the sniffer if the schema is provided, won't this work on your case?

```
create or replace table t as
  from read_csv('comment.csv',
     header=false,
     sep=',',
     null_padding=true,
     comment='#',
     columns={'col1': 'varchar', 'col2': 'varchar'},
     auto_detect=false,
     ignore_errors=false
     );
```

**Comment by pkoppstein** [comment]
@lcostantino - I have numerous test cases. It's nice to know the workarounds but the goal is correctness, hopefully with some measure of simplicity.  E.g. it should be possible to give a simple set of rules that will ensure ignore_errors=true has priority.

Incidentally, the commit that triggers an error on sniffer failure seems to break ignore_errors=true in many cases where it should have priority.

**Comment by lcostantino** [comment]
Thanks @pkoppstein , i will check some of the examples meanwhile, jut just for the record, the next function after invoking 

DetectTypes() -> where the error now stops
RefineTypes() -> is accessing a nullptr, so if it was working before IN release mode, it was just by coincidence...

if you have same example that worked before please share that and will try a fix.
