### ISSUE TITLE
JSON parses `false` but fails on `FALSE`

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#14686]
### What happens?

JSON fails to understand uppercase `FALSE`.

### To Reproduce

```sql
select json_valid('{ "x" : "abc", "y" : FALSE, "z": 10} ') v;
/*
┌───────┐
│ v     │
├───────┤
│ false │
└───────┘
*/


select json_valid('{ "x" : "abc", "y" : false, "z": 10} ') v;

/*
┌──────┐
│ v    │
├──────┤
│ true │
└──────┘
*/
```

### OS:

Linux

### DuckDB Version:

1.1.2

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pkoppstein** [comment]
`FALSE` is not a valid JSON value.  See e.g. jsonlint.com or the JSON specs. Go DuckDB!

**Comment by lnkuiper** [comment]
Indeed, as @pkoppstein says: DuckDB can only parse valid JSON. We have no plans to support reading invalid JSON. Closing as this is the expected behavior.
