### ISSUE TITLE
Regex capture groups above 9 break

### ISSUE THREAD

**Issue by sebastienvercammen** [duckdb/duckdb#14697]
### What happens?

```
# String w/ more than 10 groups
a:b:c:...:i:j:k
# Capture groups in search, 11 times the same:
# All characters that aren't the separator : ([^:]+)
([^:]+):([^:]+):([^:]+):...:([^:]+):([^:]+):([^:]+)
# Replace, unchanged
replace = \1:\2:\3:...:\9:\10:\11
```

Expected: All 11 unique values.

Actual:
```
result = a:b:c:...:i:a0:b1
```

### To Reproduce

```
SELECT regexp_replace('a:b:c:d:e:f:g:h:i:j:k', '([^:]+):([^:]+):([^:]+):([^:]+):([^:]+):([^:]+):([^:]+):([^:]+):([^:]+):([^:]+):([^:]+)', '\10');
```

Expected:

> j

Actual:

> a0

### OS:

Windows 11

### DuckDB Version:

Confirmed on both 1.1.3 and 1.0.0

### DuckDB Client:

Python

### Full Name:

Sébastien Vercammen

### Affiliation:

Self-employed

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @sebastienvercammen, thanks for opening this issue. This is an expected limitation that 'leaks through' from the underlying RE2 library. I'm documenting the limitation in a second.

**Comment by sebastienvercammen** [comment]
Hey @szarnyasg thanks for the quick response. Any chance to (some day) get named groups, e.g. via \name, to bypass the limited numbered groups?
