### ISSUE TITLE
INTERNAL Error: Attempted to access index 3 within vector of size 3

### ISSUE THREAD

**Issue by nsulikowski** [duckdb/duckdb#14691]
### What happens?

Running this query:
```
select * from 'SecuritiesOrganizationsMapping__UPDATES.parquet' limit 10;
```
Produces:
```
INTERNAL Error: Attempted to access index 3 within vector of size 3
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```
I'm able to see the file with the "Parquet Floor v5.0.1" utility.
[SecuritiesOrganizationsMapping_Bulk__UPDATES.zip](https://github.com/user-attachments/files/17619409/SecuritiesOrganizationsMapping_Bulk__UPDATES.zip)

### To Reproduce

query the attached file

### OS:

x86_64

### DuckDB Version:

1.1.2

### DuckDB Client:

cli

### Full Name:

Nestor Sulikowski

### Affiliation:

Personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by nsulikowski** [comment]
Note. I discovered that this parquet file might not be perfectly well formatted. Therefore, it reads well from Parquet Floor, but might not from Duckdb. Perhaps this ticket should trigger a better error name than a fix. Not sure

**Comment by carlopi** [comment]
I am not able to reproduce on Macos, either DuckDB v1.1.2 or v1.1.3, I would have expected this to be cross platform.

**Comment by nsulikowski** [comment]
Hi. I downloaded my attachment to double-check, and now it works ! Very sorry. I can't replicate either. Weird.
