### ISSUE TITLE
COPY … TO with hive partitioning behavior inconsistency between CSV and PARQUET formats and with the documentation

### ISSUE THREAD

**Issue by olcolin-twm** [duckdb/duckdb#14707]
### What happens?

By using COPY … TO with PARTITION_BY and without WRITE_PARTITION_COLUMNS options we don’t get rid of partitions fields with PARQUET as we do with CSV.

### To Reproduce

```
COPY (
	SELECT
		1 AS foo, 
		2024 AS year,
		11 AS month,
		5 AS day
) TO '.' (
	FORMAT PARQUET,
	OVERWRITE_OR_IGNORE,
	PARTITION_BY (year, month, day),
	FILENAME_PATTERN 'test'
);
```
We get the following file content (with partitioning fields):
```
foo|day|month|year|
---+---+-----+----+
  1|  5|   11|2024|
```
If we choose CSV instead of PARQUET, we get the expected result (without partitioning fields):
```
foo
1
```
According to the documentation (https://duckdb.org/docs/sql/statements/copy.html, version 1.1), WRITE_PARTITION_COLUMNS is a Boolean option, I should  be able to use it with a true or false value.
With the following options:
```
	FORMAT CSV,
	OVERWRITE_OR_IGNORE,
	PARTITION_BY (year, month, day),
	WRITE_PARTITION_COLUMNS false,
	FILENAME_PATTERN 'test'
```
I get the same result with WRITE_PARTITION_COLUMNS set to true or false:
```
foo|year|month|day|
---+----+-----+---+
  1|2024|   11|  5|
```
With WRITE_PARTITION_COLUMNS set to false, I would expect to get rid of partition fields (like when this option is absent).

### OS:

Windows 11, x64

### DuckDB Version:

1.1.2

### DuckDB Client:

duckdb.exe

### Full Name:

Olivier Colin

### Affiliation:

Teamwork

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by nodakai** [comment]
It seems that setting `WRITE_PARTITION_COLUMNS` to either `true` or `false` results in partition columns being written to Parquet files, whereas omitting the option entirely skips writing the partition columns.

(Linux CLI v1.1.3)

**Comment by olcolin-twm** [comment]
<<whereas omitting the option entirely skips writing the partition columns>>: this is true for CSV. With Parquet files, we always write the partition columns.

**Comment by nodakai** [comment]
> With Parquet files, we always write the partition columns.

That seem to disagree with my observation

`D COPY (SELECT 1 as foo, 2024 as year, 11 as month, 5 as day) to '/tmp/test1' (FORMAT PARQUET, COMPRESSION ZSTD, OVERWRITE_OR_IGNORE, PARTITION_BY(year, month, day), WRITE_PARTITION_COLUMNS false);`
```
D select path_in_schema, type from parquet_metadata('/tmp/test1/year=2024/month=11/day=5/data_0.parquet');
┌────────────────┬─────────┐
│ path_in_schema │  type   │
│    varchar     │ varchar │
├────────────────┼─────────┤
│ foo            │ INT32   │
│ year           │ INT32   │
│ month          │ INT32   │
│ day            │ INT32   │
└────────────────┴─────────┘
```
`D COPY (SELECT 1 as foo, 2024 as year, 11 as month, 5 as day) to '/tmp/test1' (FORMAT PARQUET, COMPRESSION ZSTD, OVERWRITE_OR_IGNORE, PARTITION_BY(year, month, day));`
```
D select path_in_schema, type from parquet_metadata('/tmp/test1/year=2024/month=11/day=5/data_0.parquet');
┌────────────────┬─────────┐
│ path_in_schema │  type   │
│    varchar     │ varchar │
├────────────────┼─────────┤
│ foo            │ INT32   │
└────────────────┴─────────┘
```

**Comment by olcolin-twm** [comment]
Now I agree with you. Instead of checking the actual content of the parquet file with the "parquet_metadata" function, I was using the function "read_parquet" that adds automatically the partition columns to the result of the select query (I realize that now). Thank you for the point !
* Behavior of COPY...TO/PARTITION_BY is consistent between CSV and PARQUET
* Behavior of COPY...TO/PARTITION_BY with  "WRITE_PARTITION_COLUMNS false" is inconsistent (for both CSV and Parquet)

**Comment by ykskb** [comment]
Hi @olcolin-twm and @nodakai,

Thanks for reporting this and checking the behaviors. I've opened a PR to handle explicit false value for `WRITE_PARTITION_COLUMNS` as linked above. This should fix the inconsistent behavior.
