### ISSUE TITLE
ROW_NUMBER OVER PARTITION BY returns bigint

### ISSUE THREAD

**Issue by daviddabingu** [duckdb/duckdb#14704]
### What happens?

Hello. I am trying to use DuckDB-WASM to conduct some sql queries with my csv file.
Then I just encountered this situation where ROW_NUMBER OVER PARTITION BY does not really return a proper integer.

The problem is, when I run this query,
```
WITH SalesCTE AS (
  SELECT
    Region,
    Category,
    SUM(Sales) AS total_sales
  FROM newTable
  GROUP BY Region, Category
)
SELECT
  Region,
  Category,
  total_sales,
  ROW_NUMBER() OVER (PARTITION BY Region ORDER BY total_sales DESC) AS rank
FROM SalesCTE
```

I get this.
<img width="480" alt="image" src="https://github.com/user-attachments/assets/209223a0-0505-4720-bafa-2595a2b2415c">

So, `ROW_NUMBER() OVER (PARTITION BY Region ORDER BY total_sales DESC) AS rank` actually returned bigint, rather than double or integer. Sure I can CAST it into double, but why is this happening?

By the way, I am using this custom function to parse the result into json.
```
async function queryToJSON(dbConnection, query) {
  const queryResult = await dbConnection.query(query);
  const columns = queryResult.schema.fields.map(({ name }) => name);
  const out = [];
  for (const row of queryResult.toArray()) {
  	out.push(Object.fromEntries(columns.map((col) => [col, row[col]])));
  }
  return out;
}
```

### To Reproduce

[Global Superstore_latest.csv](https://github.com/user-attachments/files/17625398/Global.Superstore_latest.csv)
This is the open source csv file that I am testing these queries.

### OS:

MacOS

### DuckDB Version:

duckdb-wasm@1.28.1-dev106.0

### DuckDB Client:

javascript(WASM)

### Full Name:

David Gu

### Affiliation:

IDK2

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Well, that's what the [documentation says](https://duckdb.org/docs/sql/functions/window_functions.html#row_number). In general, we can' know ahead of time how much data there will be. Moreover, suppose the windows have extreme skew - we need to make the return type wide enough for the largest partition.

The solution (which you have found) is to add a cast when you know the cardinality.

**Comment by hawkfish** [comment]
(Also, randomly changing the result type of a function based on the input data is a recipe for broken code.)

**Comment by hawkfish** [comment]
FWIW, this is also [Postgres' behaviour](https://www.postgresql.org/docs/16/functions-window.html)

**Comment by daviddabingu** [comment]
> FWIW, this is also [Postgres' behaviour](https://www.postgresql.org/docs/16/functions-window.html)

@hawkfish Thank you for the concise reply
