### ISSUE TITLE
odd window function behavior before window

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#1472]
```r
# forgive my wrapper function name :) 


quackQuery("
           select permno,exp(sum(log(1+ret)))-1 over (PARTITION BY permno ORDER BY date
                  rows between 12 preceding and 2 preceding),ret from parquet_scan('crsp_msf.parquet') limit 500
           
           ")[1:20,]
```

which thusly returns this odd response in row 1. the rest of the rows seeem right. and, oddly it only occurs for the first window frame out of, in this case, 33559 permnos

![image](https://user-images.githubusercontent.com/8321252/110262467-bc1ea100-7fee-11eb-8db5-9d77532be541.png)

**Comment by hannesmuehleisen** [comment]
Probably an off-by-one somewhere. Can you try to make a minimal reproducible example please?

**Comment by alanpaulkwan** [comment]
Sorry about the delay. HEre's a tiny example.

```{r}

setwd('~')

dbGetQuery(con,"select permno,sum(log(ret+1)) over (PARTITION BY permno ORDER BY date
                  rows between 12 preceding and 2 preceding),ret 
              from parquet_scan('example_window_function.parquet')
              limit 500
           ")




```

[example_window_function.zip](https://github.com/cwida/duckdb/files/6175035/example_window_function.zip)

**Comment by hawkfish** [comment]
I think this is also the cause of a crash bug I was investigating. At line 80 of `window_segment_tree.cpp` the code has a fencepost error with large windows:

```cpp
		if (start_in_vector + inputs.size() < STANDARD_VECTOR_SIZE) {
```

I think it should be `<=` because it is comparing endpoints.

**Comment by Alex-Monahan** [comment]
Is this present in 0.2.5? We were planning to deploy that next week and we
use window functions heavily. Thank you for your optimization work, by the
way!!

**Comment by hawkfish** [comment]
I don't know if it fixes _this_ problem, but it fixed mine ;-). I still haven't pushed it, but if someone wanted to grab it and pull it separately, please go ahead.

**Comment by hawkfish** [comment]
I will try to finish up the window multithreading work for #1367 on Monday. I also need to set a minimum horizontal partition using the `STANDARD_VECTOR_SIZE` (my application has a lot of small windows, so combining them is probably a Good Idea...)

**Comment by hawkfish** [comment]
I tried your test case and it looks like my change fixed it:

```sql
D select permno,sum(log(ret+1)) over (PARTITION BY permno ORDER BY date
   ...> rows between 12 preceding and 2 preceding),ret 
   ...> from parquet_scan('example_window_function.parquet')
   ...> limit 500;
┌─────────┬────────────────────────┬────────────────────────┐
│ permno  │         WINDOW         │          ret           │
├─────────┼────────────────────────┼────────────────────────┤
│ 10000.0 │ -1.3010300517677804    │ -0.2571428716182709    │
│ 10000.0 │                        │ 0.36538460850715637    │
│ 10000.0 │ -0.12909470484217817   │ -0.09859155118465424   │
│ 10000.0 │ 0.006160298054551344   │ -0.22265625            │
│ 10000.0 │ -0.038918077590690346  │ -0.005025125574320555  │
│ 10000.0 │ -0.14830496649283326   │ -0.08080808073282242   │
│ 10000.0 │ -0.15049285261751696   │ -0.6153846383094788    │
│ 10000.0 │ -0.18708665485841564   │ -0.05714285746216774   │
```

**Comment by hawkfish** [comment]
Is that the expected result?

**Comment by alanpaulkwan** [comment]
@hawkfish thank you, but shouldn't the first entry be NULL?  I would have thought 2 preceding to mean the first two entries of the window are null - the 2nd one is but the first one isn't. If you move to Permno 10001 you'll see that the first two entries for 10001 are NULL - which should be appropriate.

**Comment by Alex-Monahan** [comment]
I am seeing this issue in 0.2.5 as well with that test case. Is it safe to say that the issue is only occurring when using a specific number in the rows preceding clause? Our users utilize unbounded preceding and current row extensively - are there any issues in those calculations?

Thanks!
-Alex

**Comment by hawkfish** [comment]
There is a signed/unsigned bug in the window boundary computations that causes any end values greater than 1 preceding to turn into computing the entire range.

**Comment by hawkfish** [comment]
Can this be closed?
