### ISSUE TITLE
LIST(DISTINCT V ORDER BY V) ignores DISTINCT keyword

### ISSUE THREAD

**Issue by mhseiden** [duckdb/duckdb#14737]
### What happens?

When the DISTINCT modifier is used inside of the LIST aggregate it produces an expected result. When the ORDER BY modifier is also added the DISTINCT modifier is ignored.

### To Reproduce

```sql
select list(distinct v % 2) c2 from generate_series(20) s(v);
```
```
┌─────────┐
│   c2    │
│ int64[] │
├─────────┤
│ [0, 1]  │
└─────────┘
```
```sql
select list(distinct v % 2 order by v) c2 from generate_series(20) s(v, i);
```
```
┌─────────────────────────────────────────────────────────────────┐
│                               c2                                │
│                             int64[]                             │
├─────────────────────────────────────────────────────────────────┤
│ [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0] │
└─────────────────────────────────────────────────────────────────┘
```

### OS:

OSX

### DuckDB Version:

v1.1.2 f680b7d08f

### DuckDB Client:

CLI

### Full Name:

Max Seiden

### Affiliation:

Sigma Computing

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
This is not valid:

```cpp
	// If the aggregate is DISTINCT then the ORDER BYs need to be functional dependencies of the arguments.
```

but we are not catching it.
