### ISSUE TITLE
not running:No module named'duckdb.duckdb.functional';'duckdb.duckdb'is not a package

### ISSUE THREAD

**Issue by gentium9999** [duckdb/duckdb#14778]
### What happens?

when I use nuitka complie my deskapp using duckdb package,if run the exe_file,errors happend:"**No module named'duckdb.duckdb.functional';'duckdb.duckdb'is not a package**"
but it running well when I use vscode
`import duckdb`
Please tell me how to resolve the problem
![2024-11-11_142919](https://github.com/user-attachments/assets/2d55d5b3-4b72-4134-aaf6-18b8c3948b64)

### To Reproduce

![2024-11-11_142919](https://github.com/user-attachments/assets/32a66648-1d6f-48d9-8c7e-d600bff167e3)

### OS:

x86_64

### DuckDB Version:

1.1.3

### DuckDB Client:

python

### Full Name:

gentium

### Affiliation:

gentium

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot easily share my data sets due to their large size

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by gentium9999** [comment]
i.e.:
   when use pyinstaller complied,exe_file is running ok

**Comment by mgrazianoc** [comment]
Did you figure out how to make it work?

**Comment by numbworks** [comment]
I leave this message here, for whom may end up in this thread.

It seems that using `Nuitka 2.8.9` in combination with `DuckDb 1.4.3` fixes the issue.

You can read the details in in the bug report I did on Nuitka's Github:

[[Nuitka 2.8.9, Python 3.12.5] ModuleNotFoundError: No module named 'duckdb.duckdb.functional'; 'duckdb.duckdb' is not a package](https://github.com/Nuitka/Nuitka/issues/3719)
