### ISSUE TITLE
Error parsing query containing both SAMPLE and GROUP BY-clauses

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#14773]
### What happens?

A query with SAMPLE and GROUP BY clauses gives a parser error. The same query without GROUP BY clause, or the same query that uses TABLESAMPLE rather than SAMPLE parsers and executes correctly.

The query that fails to parse seems to fit the syntax documentation on the SAMPLE clause https://duckdb.org/docs/sql/query_syntax/sample, which reads: 

> The sample clause is applied right after anything in the FROM clause (i.e., after any joins, but before the WHERE clause or any aggregates) 

To me this suggests that in a query that has a GROUP BY-clause, the SAMPLE clause should come after the FROM-clause, and before the GROUP BY clause 

### To Reproduce

```
from (values(1))
using sample 1 rows
group by all
```

results in:

```
Parser Error: syntax error at or near "group"
LINE 3: group by all;
```

Interestingly, the same query but using TABLESAMPLE rather than SAMPLE works (as expected):
```
from (values(1))
tablesample 1 rows
group by all;
```

Also, when placing the USING SAMPLE after the GROUP BY clause, the query does work:
```
from (values(1))
group by all
tablesample 1 rows;
```

### OS:

windows 11 enterprise

### DuckDB Version:

v1.1.3 19864453f7

### DuckDB Client:

CLI

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
The `GROUP BY` should be before the `SAMPLE`.
