### ISSUE TITLE
Memory leakage with fetch_arrow_reader() -> BatchRecordReader.read_next_batch()

### ISSUE THREAD

**Issue by jeremyarancio** [duckdb/duckdb#14789]
### What happens?

I have been struggling with this error for a while now.

## The problem:

I have a large JSONL file (43GB once decompressed) that i'm converting into Parquet using DuckDB.
I need to perform additional post-processing, therefore I use Arrow.
The data being too large, I cannot transform the query into an Arrow table directly with .arrow(), thus I use `fetch_arrow_reader()`
However, whenever I try to iterate over the BatchRecord's, the process runs out of memory, even when reducing the first query.

Am I the only one to face this issue?

### To Reproduce

```python
import duckdb
import pyarrow

query = open("iss14789.sql", "r").read()
arrow_batches = duckdb.sql(query).fetch_arrow_reader(batch_size=1000)
```

```python
arrow_batches.read_next_batch()
> [1]    254276 segmentation fault (core dumped)
```

### OS:

wsl2

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Hardware:

32GB RAM, i7

### Full Name:

Jérémy Arancio

### Affiliation:

Freelance

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot easily share my data sets due to their large size

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by jeremyarancio** [comment]
No problem!

### SQL query
SET threads to 4;
SET preserve_insertion_order = false;
SELECT
    code,
    additives_n,
    additives_tags,
    allergens_from_ingredients,
    allergens_from_user,
    allergens_tags,
    brands_tags,
    categories_properties_tags,
    categories,
    checkers_tags,
    cities_tags,
    compared_to_category,
    complete,
    completeness,
    correctors_tags,
    countries_tags,
    to_timestamp(created_t)::datetime AS created_t, -- Convert from unixtime to datetime
    creator,
    data_quality_errors_tags,
    data_quality_info_tags,
    data_quality_warnings_tags,
    data_sources_tags,
    ecoscore_data,
    ecoscore_grade,
    ecoscore_score,
    ecoscore_tags,
    editors,
    emb_codes,
    emb_codes_tags,
    entry_dates_tags,
    environment_impact_level,
    food_groups_tags,
    forest_footprint_data,
    generic_name,
    grades,
    images,
    informers_tags,
    ingredients_analysis_tags,
    ingredients_from_palm_oil_n,
    ingredients_n,
    ingredients_tags,
    ingredients_text_with_allergens,
    ingredients_text,
    COLUMNS('ingredients_text_\w{2}$'), -- All columns containing ingredients_text_..
    ingredients_with_specified_percent_n,
    ingredients_with_unspecified_percent_n,
    ciqual_food_name_tags,
    ingredients_percent_analysis,
    ingredients_original_tags,
    ingredients_without_ciqual_codes_n,
    ingredients_without_ciqual_codes,
    ingredients,
    known_ingredients_n,
    labels_tags,
    lang,
    languages_tags,
    languages_codes,
    last_edit_dates_tags,
    last_editor,
    to_timestamp(last_image_t)::datetime AS last_image_t,
    last_modified_by,
    to_timestamp(last_modified_t)::datetime AS last_modified_t,
    to_timestamp(last_updated_t)::datetime AS last_updated_t,
    link,
    main_countries_tags,
    manufacturing_places,
    manufacturing_places_tags,
    max_imgid,
    misc_tags,
    minerals_tags,
    new_additives_n,
    no_nutrition_data,
    nova_group,
    nova_groups,
    nova_groups_markers,
    nova_groups_tags,
    nucleotides_tags,
    nutrient_levels_tags,
    unknown_nutrients_tags,
    nutriments,
    nutriscore_data,
    nutriscore_grade,
    nutriscore_score,
    nutriscore_tags,
    nutrition_data_prepared_per,
    nutrition_data,
    nutrition_grades_tags,
    nutrition_score_beverage,
    nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients,
    nutrition_score_warning_no_fiber,
    nutrition_score_warning_no_fruits_vegetables_nuts,
    obsolete_since_date,
    obsolete,
    origins_tags,
    packaging_recycling_tags,
    packaging_shapes_tags,
    packaging_tags,
    packagings_materials,
    packagings_n,
    packagings_n,
    photographers,
    pnns_groups_1_tags,
    pnns_groups_2_tags,
    popularity_key,
    popularity_tags,
    product_name,
    product_quantity_unit,
    product_quantity,
    purchase_places_tags,
    quantity,
    rev,
    scans_n,
    scores,
    serving_quantity,
    serving_size,
    sources,
    sources_fields,
    specific_ingredients,
    states_tags,
    stores,
    stores_tags,
    traces_tags,
    unique_scans_n,
    unknown_ingredients_n,
    vitamins_tags,
    weighers_tags,
    with_non_nutritive_sweeteners,
    with_sweeteners,
FROM read_ndjson('{dataset_path}', ignore_errors=True)
;

### The data 
You can find the jsonl dataset in the Open food Facts [website](https://world.openfoodfacts.org/data#:~:text=full%20MongoDB%20dump.-,JSONL%20data%20export,-The%20whole%20database).

**Comment by szarnyasg** [comment]
Hi, I ran this on macOS with DuckDB v1.1.3 on a laptop with 32 GB RAM – and it did not run out of memory. Can you please try with the latest stable `duckdb` package?

**Comment by jeremyarancio** [comment]
Indeed, it seems to work when I reproduce the example with DuckDB 1.1.3
I close the issue then.
Thanks for your time !
