### ISSUE TITLE
COALESCE with aggregate function in PIVOT query does not work

### ISSUE THREAD

**Issue by pjain1** [duckdb/duckdb#14787]
### What happens?

In pivot we cannot use COALESCE over aggregate function, for example something like 
```
PIVOT Cities
ON Year
USING COALESCE(sum(Population), 0);
```
fails with 
```
Binder Error: Pivot expression must be an aggregate
```
It would be great to support it as some combination of `Year` and `Cities` might not be present in the source data so just ` USING sum(COALESCE(Population, 0))` does not solve the issue. May be related issue - https://github.com/duckdb/duckdb/issues/14481

### To Reproduce

```
CREATE TABLE Cities (
    Country VARCHAR, Name VARCHAR, Year INTEGER, Population INTEGER
);
INSERT INTO Cities VALUES
    ('NL', 'Amsterdam', 2000, 1005),
    ('NL', 'Amsterdam', 2010, 1065),
    ('NL', 'Amsterdam', 2020, 1158),
    ('US', 'Seattle', 2000, 564),
    ('US', 'Seattle', 2010, 608),
    ('US', 'Seattle', 2020, 738),
    ('US', 'New York City', 2000, 8015);
```
Then run 
```
 PIVOT Cities
    ON Year
    USING COALESCE(sum(Population), 0);
```

### OS:

arm64

### DuckDB Version:

v1.1.3

### DuckDB Client:

go-duckdb

### Full Name:

Parag Jain

### Affiliation:

Rill Data

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
#14787 fixes this. Until it's out in a stable release, I added a workaround at https://duckdb.org/docs/sql/statements/pivot.html#limitations
