### ISSUE TITLE
Parsing Exception when reading files from s3

### ISSUE THREAD

**Issue by sephib** [duckdb/duckdb#14812]
### What happens?

when running
```
s3_parq_path=f"s3://{s3_bucket}/{s3_path}"
con.read_parquet(s3_parq_path)
```
there is no problem
However when running (as suggested in duckdb  [docs](https://duckdb.org/docs/data/parquet/overview.html#inserts-and-views))
```
sql_com=f"""
CREATE TABLE test_trip AS
SELECT *
 FROM read_parquet({s3_parq_path});
"""
con.sql(sql_com)
```
There is an error
> ParserException: Parser Error: syntax error at or near ":"

### To Reproduce

```
import duckdb

s3_bucket="BUCKET"
s3_path="PATH/TO/*.parquet"
parq_path=f"s3://{s3_bucket}/{s3_path}"

con = duckdb.connect(":memory:")
con.sql("""CREATE OR REPLACE SECRET (
    TYPE S3,
    PROVIDER CREDENTIAL_CHAIN
);""")
con.read_parquet(parq_path)
```
This Fails
```
sql_com=f"""
CREATE TABLE test_trip AS
SELECT *
 FROM read_parquet({parq_path});
"""
con.sql(sql_com)
```
With a `ParserException`
> ParserException: Parser Error: syntax error at or near ":"

### OS:

Ubuntu 22.04.4 LTS aws instance   ml.t3.2xlarge

### DuckDB Version:

1.1.3

### DuckDB Client:

Python 

### Hardware:

PRETTY_NAME="Ubuntu 22.04.4 LTS" NAME="Ubuntu" VERSION_ID="22.04" VERSION="22.04.4 LTS (Jammy Jellyfish)" VERSION_CODENAME=jammy ID=ubuntu ID_LIKE=debian HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" UBUNTU_CODENAME=jammy

### Full Name:

Joseph Berry

### Affiliation:

Fairmatic

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I think you meant to use
```
read_parquet({s3_parq_path})
```
instead ?

**Comment by sephib** [comment]
Yes - same error - updated the report

**Comment by Tishj** [comment]
`read_parquet('{...}')`

**Comment by sephib** [comment]
Thx! 
yes - that solved the issue
