### ISSUE TITLE
Unexpected result when using `INTERVAL` and `INNER JOIN` subquery

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#14834]
### What happens?

Consider the following test case. The second query with a `WHERE` filter returns 36 rows, and it's more than the first query without a `WHERE` filter, which is unexpected. 

Considering PostgreSQL returns 36 rows for both queries, I suppose the first query is unexpected.

### To Reproduce

```sql
CREATE  TABLE  t0(c1 INTERVAL);
INSERT INTO t0(c1) VALUES ('2 years 3 months');
INSERT INTO t0(c1) VALUES ('-1734799452 DAYS'), ('2 DAYS');
INSERT INTO t0(c1) VALUES ('13 days');
INSERT INTO t0(c1) VALUES ('1 month');
INSERT INTO t0(c1) VALUES ('3 days');

SELECT * FROM t0 INNER  JOIN  (SELECT  INTERVAL 1000 DAY AS col0 FROM t0) AS sub0  ON (t0.c1 < sub0.col0); -- 24 rows (unexpected)
SELECT * FROM t0 INNER  JOIN  (SELECT  INTERVAL 1000 DAY AS col0 FROM t0) AS sub0  ON (t0.c1 < sub0.col0) WHERE (NOT (t0.c1 != t0.c1)); -- 36 rows


```

### OS:

Ubuntu 22.04

### DuckDB Version:

v1.1.4-dev1859 b484c2d96f

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks@!
