### ISSUE TITLE
Not rounding

### ISSUE THREAD

**Issue by dchimeno** [duckdb/duckdb#14844]
### What happens?

Not the desired output.

### To Reproduce

```sql
WITH total AS
  (SELECT round(amount, 4) AS amount_rounded
   FROM
     (SELECT 4.12313123 AS amount)
   UNION ALL
     (SELECT 4.33333333 AS amount))
SELECT *
FROM total;
```

Result:

4.66670000
4.33333333

Expected:

```
amount_rounded|
--------------+
        4.6667|
        4.3333|
```

This query works as expected:

```sql
with total as (
    select round(amount, 4) as amount_rounded
    from (
        select 4.66666666 as amount 
        union all 
        select 4.33333333 as amount
    )
)
select * from total;
```

This is relevant as the first query is generated by dbt and other tools.

### OS:

aarch64

### DuckDB Version:

1.1.2

### DuckDB Client:

python, cli, dbeaver

### Full Name:

Daniel

### Affiliation:

Telefonica

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @dchimeno thanks for reporting this. Which operating system are you running on? I am unable to reproduce the results on macOS / Ubuntu and get this result:

```text
┌────────────────┐
│ amount_rounded │
│ decimal(13,8)  │
├────────────────┤
│     4.12310000 │
│     4.33333333 │
└────────────────┘
```

**Comment by Mytherin** [comment]
Thanks for the report!

This seems like intended behavior to me. The indentation makes the example a little confusing, but the query explicitly only rounds the first number, and not the second number. Fixing the indentation and clearing up the example this is the query that is being run:

```sql
SELECT round(amount, 4) AS amount_rounded
FROM (SELECT 4.12313123 AS amount)

UNION ALL

SELECT 4.33333333 AS amount;

```

As you can see, `round` is only called for the first query, hence only the first amount is rounded. This is correctly reflected in the result:

```sql
┌────────────────┐
│ amount_rounded │
│ decimal(13,8)  │
├────────────────┤
│     4.12310000 │
│     4.33333333 │
└────────────────┘
```


Postgres produces the same result:

```sql
WITH total AS
  (SELECT round(amount, 4) AS amount_rounded
   FROM
     (SELECT 4.12313123 AS amount) sub_query
   UNION ALL
     (SELECT 4.33333333 AS amount))
SELECT *
FROM total;

 amount_rounded 
----------------
         4.1231
     4.33333333
(2 rows)

```

**Comment by dchimeno** [comment]
I just checked. you are right. thanks!
