### ISSUE TITLE
bug affecting simple function to pick an item at random

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#14869]
### What happens?

My bug, my apologies.

**Comment by carlopi** [comment]
I think using:
```
create or replace function list_random(lst) as
·   lst[ 1 + prn(length(lst)) ];
```
results looks to be as expected.

I was just remembered today, that SQL-array indexing is 1 based. I can't find a reference to the docs, but examples confirm that.

**Comment by pkoppstein** [comment]
@carlopi - Yes, indexing is 1-based, which is why there's the "1 + ".  That is, range(0,length(lst)) ranges from 0 to length(lst)-1.

**Comment by szarnyasg** [comment]
Thanks @pkoppstein, I could reproduce this. The resulting `count_star` is indeed non-deterministic.

**Comment by pkoppstein** [comment]
@szarnyasg - I'm a bit puzzled by the fact that you've added the "Needs Documentation" tag.  This is a bug that has nothing to do with count_star.  I only included the count to indicate that list_random() returns NULL quite often.  To be clear, list_random() should return a random element from the list.  It should never return NULL, or at least, if it ever did, it would only be exceedingly rare, corresponding to the frequency with which @(random() - 1.0) = 0.   

(It would be nice if DuckDB could guarantee that `@(random() - 1.0) != 0` but that indeed is a separate issue.)

**Comment by carlopi** [comment]
I might be missing something, and have not have actually tried with latest main, but:

1. range of `prn(n)` is an integer between `0` `n-1`, both included
2. range of `prn(1 + length(lst))` is an integer between `0` and `1+length(lst)-1 = length(lst)`, both included
3. accessing a list at index 0, is valid, but returns NULL

So it's by design that for a list of length 3, about 1/4th of the time your function return NULL, with the remaining 3/4 split between 1,2,3.

I think if the intended semantic is "pick an element from the list at random", the formula should be:
`lst[ 1 + prn(length(lst)) ]`

I had not found (with very little effort) a line in the docs saying "duckdb follows SQL spec (and Postgres!) in using 1 based indexes for lists / arrays, and 0 based indexes for JSON", that might potentially be a source of confusion (or has been for me in the past).

**Comment by carlopi** [comment]
To be more clear, I think  this issue is a non-issue, everything works as intended.

**Comment by Tishj** [comment]
```
D select [1,2,3][0];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[0] │
│            int32            │
├─────────────────────────────┤
│                             │
└─────────────────────────────┘
D select [1,2,3][1];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[1] │
│            int32            │
├─────────────────────────────┤
│                           1 │
└─────────────────────────────┘
D select [1,2,3][2];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[2] │
│            int32            │
├─────────────────────────────┤
│                           2 │
└─────────────────────────────┘
D select [1,2,3][3];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[3] │
│            int32            │
├─────────────────────────────┤
│                           3 │
└─────────────────────────────┘
```

To illustrate what Carlo has already pointed out
Your function is hitting the first case of `[1,2,3][0]` about 1/4th of the time, there is no bug here

**Comment by pkoppstein** [comment]
My bug, my apologies.

**Comment by szarnyasg** [comment]
> I'm a bit puzzled by the fact that you've added the "Needs Documentation" tag.

Hi, I added it due to Carlo's comment:

> SQL-array indexing is 1 based. I can't find a reference to the docs, but examples confirm that.

This should be obvious from our documentation but I also couldn't find it in a few seconds, so it's not obvious enough.

**Comment by pkoppstein** [comment]
@szarnyasg - There's a clear statement at the very top of the page https://duckdb.org/docs/sql/dialect/indexing.html

> DuckDB uses 1-based indexing except for [JSON objects](https://duckdb.org/docs/data/json/overview.html), which use 0-based indexing.

ChatGPT knows about this too:

Q: What is DuckDB's index origin for arrays?
A: ChatGPT
In DuckDB, the index origin for arrays (or lists) is 1-based, ...


At present, however, entering "index origin" in the  DuckDB search box does not narrow the search results as one might have hoped, so perhaps that's an area for improvement if you're looking for one.

Thanks.

**Comment by szarnyasg** [comment]
@pkoppstein, that's a great point, thanks. I added the term `index origin` on the page: https://github.com/duckdb/duckdb-web/pull/4088
