### ISSUE TITLE
CSV Sniffer refuses to read simple file

### ISSUE THREAD

**Issue by DanCory** [duckdb/duckdb#14883]
### What happens?

DuckDB will not read this file as CSV no matter which settings I try.
[stops.txt](https://github.com/user-attachments/files/17804278/stops.txt)

```sql
select * from read_csv('stops.txt'); reads the file as a single column
select * from read_csv('stops.txt', header=true, delim=','); returns
```
```console
Invalid Input Error: Error when sniffing file "stops.txt".
It was not possible to automatically detect the CSV Parsing dialect/type
```

Adding additional parameters causes the same result.

### To Reproduce

Have the previously attached file available

```sql
select * from read_csv('stops.txt', header=true, delim=',');
```

### OS:

Windows amd64

### DuckDB Version:

1.1.3

### DuckDB Client:

CLI

### Full Name:

Dan Cory

### Affiliation:

self

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @DanCory, the problematic line is 1466 with the unqouted quote character in the middle of the field:

```csv
"de:08317:12007:2:1","Lahr Schlüssel "Vis-à-Vis Bus"","48.3411985847104","7.87932997062448"
```

I'll pass this along to the team to see if there's a way to get more information from DuckDB in such cases.

**Comment by DanCory** [comment]
Thanks! I tried setting ignore_errors and that didn't help. But I guess I could have turned off auto_detect entirely.

**Comment by DanCory** [comment]
FYI turning off auto_detect entirely turned out to be a lot of additional work, because this was one file in a set and the schemas are not tightly defined. I wanted to have DuckDB generate the column information, while fixing the CSV structure options. This does not appear to be possible from the documentation and my experimentation, but I might have missed an option.

I ended up using the sniff_csv function to detect the format, then picking and choosing what I wanted for read_csv with auto_detect off. But that was a lot of logic.

**Comment by DanCory** [comment]
I tried using select "Prompt" from sniff_csv('stops.txt', delim=',', ignore_errors=true);
but it returns:
FROM read_csv('stops.txt', auto_detect=false, quote='''', escape='\', new_line='\r\n', skip=0, comment='', header=true, columns={'"de:08216:32095:0:1"': 'VARCHAR', '"Ottersweier Maria Linden': 'VARC...
which is data from row 58, which happens to be the first one where a value contains the delimiter.
I could not find a way to get ignore_errors to return reasonable values.

**Comment by DanCory** [comment]
FWIW the defunct univocity parser has a few ways to handle unescaped quotes.
Excel reads these files and reads that value as Lahr Schlüssel Vis-à-Vis Bus""

**Comment by dmcmurchy** [comment]
@DanCory - I was playing around with your text file as I'd run into similar issues before. Even fixing the extra `"` on line 1466 doesn't resolve the issue as you'll still be missing rows as the csv_sniffer thinks there should be five columns instead of four. If you can, you might want to change the delimiter in the stops.txt file from comma (`','` to pipe `'|'`), you could then get rid of the quotes.

**Comment by DanCory** [comment]
Thanks @dmcmurchy. I don't control generation of this file - it's from a general transit feed (GFTS) file. The specification says the files are supposed to be proper CSV, but sometimes they are not. It would be nice to be able to read them with DuckDB, even if ignore_errors is needed.
