### ISSUE TITLE
ROW_GROUP_SIZE parameter doesn't work for some parquet files

### ISSUE THREAD

**Issue by nbc** [duckdb/duckdb#14898]
### What happens?

When using `COPY ... TO ...` to generate a new parquet file from another parquet file the `ROW_GROUP_SIZE` parameter doesn't work.

The final row group size is very low (under 10 000)

### To Reproduce

Parquet file to reproduce is available here : https://drive.google.com/file/d/1qKeMmM1UmE8KlmYEilVzQghl8l_R64Pu/view?usp=drive_link
It's generated from [this SAS file](https://www2.census.gov/programs-surveys/ahs/2019/AHS%202019%20National%20PUF%20v1.1%20Flat%20SAS.zip) with [readstat](https://github.com/curtisalexander/readstat-rs)

I have the same problem with every parquet generated by readstat

The SQL code to reproduce it : 

```sql
SET preserve_insertion_order = false;

SELECT * FROM duckdb_settings() WHERE name = 'memory_limit';

SELECT MAX(row_group_num_rows) FROM parquet_metadata('ahs.parquet');

COPY (FROM read_parquet('ahs.parquet')) TO 'mynewfile.parquet' (FORMAT PARQUET, ROW_GROUP_SIZE 122_880);

SELECT COUNT(*) FROM read_parquet('mynewfile.parquet');

SELECT MAX(row_group_num_rows) FROM parquet_metadata('mynewfile.parquet');
```

Output is : 

```
duckdb-bleeding < reprex.sql
┌──────────────┬───────────┬─────────────────────────────────────────────┬────────────┬─────────┐
│     name     │   value   │                 description                 │ input_type │  scope  │
│   varchar    │  varchar  │                   varchar                   │  varchar   │ varchar │
├──────────────┼───────────┼─────────────────────────────────────────────┼────────────┼─────────┤
│ memory_limit │ 403.0 GiB │ The maximum memory of the system (e.g. 1GB) │ VARCHAR    │ GLOBAL  │
└──────────────┴───────────┴─────────────────────────────────────────────┴────────────┴─────────┘
┌─────────────────────────┐
│ max(row_group_num_rows) │
│          int64          │
├─────────────────────────┤
│                   10000 │
└─────────────────────────┘
100% ▕████████████████████████████████████████████████████████████▏
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        63185 │
└──────────────┘
┌─────────────────────────┐
│ max(row_group_num_rows) │
│          int64          │
├─────────────────────────┤
│                    4096 │
└─────────────────────────┘
```

### OS:

ubuntu 22.04 x86_64 

### DuckDB Version:

1.1.2, 1.1.3 and bleeding

### DuckDB Client:

cli and R

### Full Name:

Nicolas chuche

### Affiliation:

Ministere de la transition écologique

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by nbc** [comment]
Ok, I thought it was linked to readstat but it's not . The problem seems to appear when there"s a lot of column.

To reproduce it (you need around 40Gb of memory) :

```
library(duckdb)

n_colonnes <- 4000
n_lignes <- 400000

set.seed(123)
data <- as.data.frame(matrix(runif(n_colonnes * n_lignes), nrow = n_lignes, ncol = n_colonnes))
colnames(data) <- paste0("col_", seq_len(n_colonnes))

con <- dbConnect(duckdb())
duckdb_register(con, "data", data)

dbExecute(con, "COPY data TO 'file.parquet' (FORMAT PARQUET, ROW_GROUP_SIZE 100000)")
dbGetQuery(con, "SELECT MAX(row_group_num_rows) FROM parquet_metadata('file.parquet');")
```

And the output : 

```
> dbExecute(con, "COPY data TO 'file.parquet' (FORMAT PARQUET, ROW_GROUP_SIZE 100000)")
[1] 4e+05
> dbGetQuery(con, "SELECT COUNT(*) FROM read_parquet('file.parquet');")
  count_star()
1        4e+05
> dbGetQuery(con, "SELECT MAX(row_group_num_rows) FROM parquet_metadata('file.parquet');")
  max(row_group_num_rows)
1                    4096
```

**Comment by Mytherin** [comment]
Thanks for the report!

This is most likely related to `ROW_GROUP_SIZE_BYTES`, which defaults to allowing up to 1KB per row and writes shorter row groups if the rows are too large. With a row group size of `122880` the row-group limit is `122880KB` (or `122MB`). You could configure that to a higher number if desired.

**Comment by nbc** [comment]
Thanks @Mytherin , TIL about ROW_GROUP_SIZE_BYTES and my row group size is "a bit" above (2Go for 100 000).

If I understand well the documentation, there's no way to change the default value when `preserve_insertion_order = true` ? (just asking, not a problem for me)

```
SET preserve_insertion_order = false;
COPY (FROM read_parquet('/nfs/partage-r-sas/temp/pote_diff_2013/part-0.parquet'))
               TO 'mynewfile.parquet' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000, ROW_GROUP_SIZE_BYTES '4GB');
SELECT MAX(row_group_num_rows), MAX(row_group_bytes) FROM parquet_metadata('~/sas2parquet/mynewfile.parquet');
```

```
┌─────────────────────────┬──────────────────────┐
│ max(row_group_num_rows) │ max(row_group_bytes) │
│          int64          │        int64         │
├─────────────────────────┼──────────────────────┤
│                  101568 │           2077198838 │
└─────────────────────────┴──────────────────────┘
```

**Comment by Mytherin** [comment]
Yes, you're right, this is a bit confusing. With `preserve_insertion_order = true` **and** using a scan that supports parallel insertion-order preservation, the `ROW_GROUP_SIZE_BYTES` parameter is ignored entirely and we only write `ROW_GROUP_SIZE`, and `ROW_GROUP_SIZE_BYTES` cannot be set manually. I think you're running into this specifically because you're writing from an R data frame that doesn't support parallel insertion-order preservation.

I think this is pretty confusing actually. I think the best way forward is to remove the automatic setting of `ROW_GROUP_SIZE_BYTES` and require the user to specify it.
