### ISSUE TITLE
A confusion about Top-N operator

### ISSUE THREAD

**Issue by yiliangyl** [duckdb/duckdb#14896]
### What happens?

In `TopNHeap::Reduce`, the reduce threshold is determined by `payload_chunk.size()`. However, the `payload_chunk` is only used as a temporary data holder in `TopNHeap::Combine`. It's `heap_data` right?

### To Reproduce

```cpp
void TopNHeap::Combine(TopNHeap &other) {
	other.Finalize();

	// FIXME: heaps can be merged directly instead of doing it like this
	// that only really speeds things up if heaps are very large, however
	TopNScanState state;
	other.InitializeScan(state, false);
	while (true) {
		payload_chunk.Reset();
		other.Scan(state, payload_chunk);
		if (payload_chunk.size() == 0) {
			break;
		}
		Sink(payload_chunk);
	}
	Reduce();
}

void TopNHeap::Reduce() {
	if (payload_chunk.size() < ReduceThreshold()) {
		// only reduce when we pass the reduce threshold
		return;
	}
	...
}
```

### OS:

x86_64

### DuckDB Version:

newest commit id: b470dea7ee47dc2debcc37a4e94976f8eff6670c

### DuckDB Client:

none

### Full Name:

Yiliang Qiu

### Affiliation:

Baidu Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! You are correct that Reduce was not called correctly. I've added a few optimizations for large heaps for which the new approach regressed - see https://github.com/duckdb/duckdb/pull/14900
