### ISSUE TITLE
C API - Cannot get named parameter type

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#14904]
### What happens?

When using [named parameters](https://duckdb.org/docs/sql/query_syntax/prepared_statements.html#named-parameters-parameter), `duckdb_param_type` always returns `Invalid`. Works fine for other types of parameters.

### To Reproduce

```c
state = duckdb_open(NULL, &db);
state = duckdb_connect(db, &connection);

state = duckdb_prepare(connection, "CREATE TABLE person (name VARCHAR, age BIGINT);", &preparedStatement);
state = duckdb_execute_prepared(preparedStatement, &result);

state = duckdb_prepare(connection, "INSERT INTO person VALUES ('Alice', 37), ('Ana', 35), ('Bob', 41), ('Bea', 25);", &preparedStatement);
state = duckdb_execute_prepared(preparedStatement, &result);

state = duckdb_prepare(connection, "Select * from person where age=$age;", &preparedStatement);

//paramType is Invalid. Works fine if I use positional or auto-incremented parameters.
auto paramType = duckdb_param_type(preparedStatement, 1);
```

### OS:

Windows 11 x64

### DuckDB Version:

1.1.3

### DuckDB Client:

C Api

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by jraymakers** [comment]
I looked into this a little while ago, and noticed that the code path for `duckdb_param_type` [converts the provided index directly to a string](https://github.com/duckdb/duckdb/blob/448b46937fcafdc789b053536d093ef22b9105b5/src/main/capi/prepared-c.cpp#L143), without using the `named_param_map` as is done [elsewhere](https://github.com/duckdb/duckdb/blob/448b46937fcafdc789b053536d093ef22b9105b5/src/main/capi/prepared-c.cpp#L104). This seems likely to be the problem.

**Comment by Giorgi** [comment]
Thanks for the hint @jraymakers
