### ISSUE TITLE
Invalid json output for cli -json

### ISSUE THREAD

**Issue by thbley** [duckdb/duckdb#14905]
### What happens?

Example cli output:

```
┌──────────────────────┬───────────────┐
│          a           │       b       │
│        double        │ decimal(38,2) │
├──────────────────────┼───────────────┤
│ 0.013835631366566025 │     -29641.68 │
│ 0.014779952408172961 │     -10296.42 │
│ 0.003024374814074319 │      -5077.02 │
│ 0.010121712177079566 │      -2664.09 │
│ 0.034948037785923564 │       -795.75 │
│                  0.0 │       -531.77 │
│                  0.0 │       -437.56 │
│                  0.0 │        -75.62 │
│                 -nan │          0.00 │
│                 -nan │          0.00 │
├──────────────────────┴───────────────┤
│ 10 rows                    2 columns │
└──────────────────────────────────────┘

```
becomes with -json

```json
[{"a":0.013835631366566025,"b":-29641.68},
{"a":0.014779952408172961,"b":-10296.42},
{"a":0.003024374814074319,"b":-5077.02},
{"a":0.010121712177079566,"b":-2664.09},
{"a":0.034948037785923564,"b":-795.75},
{"a":0.0,"b":-531.77},
{"a":0.0,"b":-437.56},
{"a":0.0,"b":-75.62},
{"a":-nan,"b":0.00},
{"a":-nan,"b":0.00}]
```

E.g. php json parser does not accept "-nan" as a number.

https://datatracker.ietf.org/doc/html/rfc8259 says: Numeric values that cannot be represented in the grammar below (such
   as Infinity and NaN) are not permitted.

### To Reproduce

```bash
duckdb :memory: "select 0.0 / 0.0" -json
```

```text
[{"(0.0 / 0.0)":-nan}]
```

### OS:

Ubuntu

### DuckDB Version:

1.1.3

### DuckDB Client:

cli

### Full Name:

Thomas Bley

### Affiliation:

myself

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by thbley** [comment]
Also sorting is a big mess:

```
D SELECT cast(id as double) FROM (VALUES (1), (2), (0.0/0.0), (null)) cities(id) order by id asc;
┌────────────────────┐
│ CAST(id AS DOUBLE) │
│       double       │
├────────────────────┤
│                1.0 │
│                2.0 │
│               -nan │
│                    │
└────────────────────┘
D SELECT cast(id as double) FROM (VALUES (1), (2), (0.0/0.0), (null)) cities(id) order by id desc;
┌────────────────────┐
│ CAST(id AS DOUBLE) │
│       double       │
├────────────────────┤
│               -nan │
│                2.0 │
│                1.0 │
│                    │
└────────────────────┘
```

**Comment by pkoppstein** [comment]
It's reasonable to expect that DuckDB's cast to JSON will return JSON, especially since JSON's `null` is available as an option.  For comparison:
```
$ jq -n '[-infinite, nan, infinite]'
[
  -1.7976931348623157e+308,
  null,
  1.7976931348623157e+308
]

$ gojq -n '[-infinite, nan, infinite]'
[
  -1.7976931348623157e+308,
  null,
  1.7976931348623157e+308
]

$ jaq -n '[-infinite, nan, infinite]'
[
  null,
  null,
  null
]
```

**Comment by szarnyasg** [comment]
@thbley Thanks for reporting this. Indeed the JSON standard doesn't allow `nan` values. We'll see what we can come up with an alternative (such as using `null` for `nan`).

Sorting is not a "big mess", what you're seeing is the effect of the [`NULLS LAST` NULL order modifier](https://duckdb.org/docs/sql/query_syntax/orderby#null-order-modifier).

**Comment by thbley** [comment]
> such as using null for nan

For those coming from MariaDB/MySQL, this would be preferred.

> SET null_order = 'NULLS_FIRST_ON_ASC_LAST_ON_DESC';

Thanks, I only read https://duckdb.org/docs/configuration/overview.html .

**Comment by thbley** [comment]
```
D SET null_order = 'NULLS_FIRST_ON_ASC_LAST_ON_DESC';
D SELECT cast(id as double) FROM (VALUES (1), (2), (0.0/0.0), (null)) cities(id) order by id asc;
│                    │
│                1.0 │
│                2.0 │
│                nan │
```

Maybe you could add a configuration setting for "nan_order" ?
