### ISSUE TITLE
Python - all_varchar ignored for text that looks like a boolean

### ISSUE THREAD

**Issue by cc-jrtapsell** [duckdb/duckdb#14928]
### What happens?

DuckDB versions after 1.0.0 force the value to a boolean even when told to keep it as text.

```
DuckDB Version 1.0.0
┌─────────┐
│ enabled │
│ varchar │
├─────────┤
│ yes     │
│ no      │
│ yes     │
└─────────┘

DuckDB Version 1.1.0
┌─────────┐
│ enabled │
│ boolean │
├─────────┤
│ true    │
│ false   │
│ true    │
└─────────┘

DuckDB Version 1.1.1
┌─────────┐
│ enabled │
│ boolean │
├─────────┤
│ true    │
│ false   │
│ true    │
└─────────┘

DuckDB Version 1.1.2
┌─────────┐
│ enabled │
│ boolean │
├─────────┤
│ true    │
│ false   │
│ true    │
└─────────┘

DuckDB Version 1.1.3
┌─────────┐
│ enabled │
│ boolean │
├─────────┤
│ true    │
│ false   │
│ true    │
└─────────┘
```

### To Reproduce

```python
import duckdb

with open("temp.csv", "w", encoding="ascii") as fd:
    fd.write("\n".join([
        "enabled",
        "yes",
        "no",
        "yes"
    ]))

con = duckdb.connect()
con.read_csv(
    path_or_buffer="temp.csv",
    all_varchar=True,
    # dtype=["varchar"],
    # auto_type_candidates=["varchar"],
)

print(con.sql("SELECT * from 'temp.csv'"))
```

### OS:

Windows 11 22H2 x86_64

### DuckDB Version:

> 1.0.0

### DuckDB Client:

Python

### Full Name:

James Tapsell

### Affiliation:

ClearChannel

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
```py
rel = con.read_csv(
    path_or_buffer="temp.csv",
    all_varchar=True,
    # dtype=["varchar"],
    # auto_type_candidates=["varchar"],
)
rel.show()
```

You're entirely discarding the result of your `read_csv` call in your example

**Comment by cc-jrtapsell** [comment]
Thanks, in the minimal example it just prints out the relation - in the real code it's part of a larger pipeline, but the same issue can be reproduced without needing to setup the full environment, which helps narrow down the cause.

It looks like the behaviour changed in 1.1.0, so it always converts the type to a boolean?

In our use case we want to validate that the input is explicitly "yes" or "no", and treat true and false as invalid values.\

Thanks,
James
