### ISSUE TITLE
Adding an index returns inconsistent results

### ISSUE THREAD

**Issue by nishanthkarthik** [duckdb/duckdb#14955]
### What happens?

My table has a `cluster_id` field which multiple rows share. This table was originally generated using the rust bindings but I use the CLI for queries.

```sql
SELECT * FROM clusters LIMIT 1;
```

returns one row with `event_cluster_id = 1`. But when I run

```sql
SELECT * FROM clusters WHERE event_cluster_id = 1;
```

I get 0 rows.

Dropping the index on cluster_id fixes the issue. Is there any reason why adding an index produces inconsistent results?

I can't attach the db file because it is too large (500M rows).

### To Reproduce

I use the CLI (queries listed above)

### OS:

x86_64

### DuckDB Version:

v1.1.3 19864453f7

### DuckDB Client:

CLI

### Full Name:

Karthik Nishanth

### Affiliation:

personal project

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot easily share my data sets due to their large size

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, thanks for opening this issue. This seems to be a bug but we cannot proceed with it without a reproducer or at least the database file. Would it be possible for you to share the database file privately, e.g., via Google Drive? If so, please send me an email (gabor@duckdblabs.com).

**Comment by szarnyasg** [comment]
Hi, thanks for sending the database along, I could reproduce the issue.

**Comment by iamsachin45** [comment]
Hi @szarnyasg ,
I would like to work on this issue.

**Comment by taniabogatsch** [comment]
Hi @nishanthkarthik! I just had a look at your issue, and either
1. it was fixed in a [recent PR](https://github.com/duckdb/duckdb/pull/15092) that addressed a bug in our index code.
2. or I used a different index creation approach, where it does not reproduce.

Here are my steps.
- opening your DB file + checking that the index is there.
- reproducing the issue
- dropping the index
- using `CREATE INDEX ...` with the latest (today) duckdb version, which fixes a bug in the index creation
- the new index lookup succeeds
- drop the index again and verify that the results match

```sql
tania@motorbook duckdb % build/release/duckdb event.db 
v1.1.4-dev3472 7e3dca3b06
Enter ".help" for usage hints.
D FROM duckdb_indexes();
┌───────────────┬──────────────┬─────────────┬────────────┬─────────────┬───────────┬────────────┬───────────┬─────────┬──────────────────────┬───────────┬────────────┬────────────────────┬─────────────────────────────────────────┐
│ database_name │ database_oid │ schema_name │ schema_oid │ index_name  │ index_oid │ table_name │ table_oid │ comment │         tags         │ is_unique │ is_primary │    expressions     │                   sql                   │
│    varchar    │    int64     │   varchar   │   int64    │   varchar   │   int64   │  varchar   │   int64   │ varchar │ map(varchar, varch…  │  boolean  │  boolean   │      varchar       │                 varchar                 │
├───────────────┼──────────────┼─────────────┼────────────┼─────────────┼───────────┼────────────┼───────────┼─────────┼──────────────────────┼───────────┼────────────┼────────────────────┼─────────────────────────────────────────┤
│ event         │     538      │ main        │    540     │ cluster_idx │    555    │ clusters   │    549    │ NULL    │ {}                   │ false     │ false      │ [event_cluster_id] │ CREATE INDEX cluster_idx ON clusters(…  │
└───────────────┴──────────────┴─────────────┴────────────┴─────────────┴───────────┴────────────┴───────────┴─────────┴──────────────────────┴───────────┴────────────┴────────────────────┴─────────────────────────────────────────┘
D SELECT * FROM clusters LIMIT 1;
-- 1 row, I removed the actual data
D SELECT * FROM clusters WHERE event_cluster_id = 1;
-- 0 rows -> this is the bug
D DROP INDEX cluster_idx;
D CREATE INDEX cluster_idx ON clusters(event_cluster_id);
100% ▕████████████████████████████████████████████████████████████▏         
D SELECT * FROM clusters WHERE event_cluster_id = 1;
-- 4 rows, again, I removed the actual data
D DROP INDEX cluster_idx;
D SELECT * FROM clusters WHERE event_cluster_id = 1;
-- also four rows
```

Can you still reproduce this with duckdb's latest `main`? If so, can you give me the exact steps how you create the index? :)

**Comment by nishanthkarthik** [comment]
Thank you for the fixes. I don't remember if I used any specific kind of index - I think it's the default (zonemaps?). Based on your steps to reproduce, it is likely that it was fixed by the PR. Your steps looks similar to what I did initially so I think we can close the issue. I'll reopen the issue I can reproduce it on my end.
