### ISSUE TITLE
Table name with df does not exist

### ISSUE THREAD

**Issue by ededovic** [duckdb/duckdb#14961]
### What happens?

I use a helper wrapper function to query pandas dataframes but ever since upgrade from 1.0 to 1.1.3 duckdb no longer sees  dataframes. 
This issue exists in PyCharm Python Console, but not in iPython. The workaround was to register dataframes, but based on documentation, I do not need to do that. I'm unsure what changed to cause this issue. Below is full minimal viable example to reproduce the issue.

### To Reproduce

create `sql_duck.py`. note that it will work if esql is defined inside the pycharm console but not if defined via module
```
import duckdb


def esql(q):
   '''original version that errors now'''
    if not hasattr(esql, 'connection'):
        esql.connection = duckdb.connect()

    return esql.connection.sql(q).to_df()



def sql(q):
    '''working version in pycharm'''
    if not hasattr(sql, 'connection'):
        sql.connection = duckdb.connect()

    # Get the caller's global variables
    import inspect
    frame = inspect.currentframe()
    caller_globals = frame.f_back.f_globals
    caller_locals = frame.f_back.f_locals
    frame.f_back

    # Register all pandas DataFrames from the caller's scope
    for name, value in {**caller_globals, **caller_locals}.items():
        if type(value).__module__ == 'pandas.core.frame':
            sql.connection.register(name, value)

    try:
        return sql.connection.sql(q).to_df()
    finally:
        frame = None  # Clear the frame reference to avoid memory issues
```

inside `python console` in pycharm:
```
import sql_duck 
df = pd.DataFrame(dict(a=range(10)))
sql_duck.esql('select sum(a) from df')
```
error message inside `pycharm`:
```
sql_duck.esql('from df select sum(a)')
Traceback (most recent call last):
  File "....\Anaconda3\envs\py310\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-04f905fa3fdc>", line 1, in <module>
    sql_duck.esql('from df select sum(a)')
  File "sql_duck.py", line 8, in esql
    return esql.connection.sql(q).to_df()
duckdb.duckdb.CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "pg_depend"?
```
`sql` function is a temp fix that re-registers dataframes: 
```

df = pd.DataFrame(dict(a=range(10)))
sql_duck.sql('from df select sum(a)')
Out[15]: 
   sum(a)
0  45.000
```

### OS:

windows 10

### DuckDB Version:

1.1.3

### DuckDB Client:

pycharm 2024.3; python 3.10, 3.11 console

### Full Name:

e d

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
#13836

**Comment by Tishj** [comment]
https://github.com/duckdb/duckdb/pull/13896

**Comment by ededovic** [comment]
to save others on reading, it appears that simply adding `set python_scan_all_frames=true` will do. 

updated version of the function works: 

```
import duckdb
def sql(q):
    '''modified to work with duckdb 1.1. and higher'''
    if not hasattr(sql, 'connection'):
        sql.connection = duckdb.connect()
    if Version(duckdb.__version__) >= Version("1.1.0"):
      connection.execute("set python_scan_all_frames=true")

    return sql.connection.sql(q).to_df()
```

```
df = pd.DataFrame(dict(a=range(10)))
sql('select sum(a) from df')
> 45
```
