### ISSUE TITLE
literal max uhugeint raises exception

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#15012]
### What happens?

The page https://duckdb.org/docs/sql/data_types/numeric
correctly states that the max value of a UHUGEINT should be
340282366920938463463374607431768211455

But the CLI gets confused:
```
D select 340282366920938463463374607431768211455::UHUGEINT;
Conversion Error:
Type DOUBLE with value 3.402823669209385e+38 can't be cast because the value is out of range for the destination type UINT128
```
Evidently it first attempts to parse the digit sequence before it gets to the type declaration.

The good news is DuckDB correctly handles 2^127 + (2^127 - 1):
 
select 170141183460469231731687303715884105728::UHUGEINT + 170141183460469231731687303715884105727;
```
┌──────────────────────────────────────────────────────────────────────────────────────┐
│ (CAST(1.7014118346046923e+38 AS UHUGEINT) + 170141183460469231731687303715884105727) │
│                                       uint128                                        │
├──────────────────────────────────────────────────────────────────────────────────────┤
│                                              340282366920938463463374607431768211455 │
└──────────────────────────────────────────────────────────────────────────────────────┘
```

### To Reproduce

select 340282366920938463463374607431768211455::UHUGEINT;

### OS:

MacOC

### DuckDB Version:

1.1.4

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Casting from string like `select '340282366920938463463374607431768211455'::UHUGEINT;` works around the issue, that I think is that literal -> double -> UHUGEINT is not information preserving. Thanks
