### ISSUE TITLE
read_csv_auto silently loads only a subset of data

### ISSUE THREAD

**Issue by cpa** [duckdb/duckdb#1501]
I have found a bug related to CSV and quoting in `read_csv_auto`. I have reduced the test file as much as I could, although it's still a 1k line csv. It consists of 1 column (so no delimiter, although it reproduces nicely with several columns) and the only value which is not an `A` is on the last line and is `""A""` ([test.txt](https://github.com/cwida/duckdb/files/6152567/test.txt))

Test: `CREATE TABLE bug AS SELECT * FROM read_csv_auto('test.txt'); select count(*) from bug`
Expected number of rows in table: 1035 or a parse error
Actual result: 1025
Actual result when replacing the last line with `"A"` or `A`: 1035

DuckDB version: 0.2.5
Python version: 3.8.3

**Comment by tdoehmen** [comment]
Thanks for the report! That seems to be a bug in the underlying CSV parser logic.

For now, try setting the `quote` parameter as in the example below to circumvent the issue:
`CREATE TABLE bug AS SELECT * FROM read_csv_auto('test.txt',quote=''); select count(*) from bug`
