### ISSUE TITLE
`TO_JSON` results in weird number translation

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#15038]
### What happens?

`TO_JSON` translates `9007199254740993` into `9007199254740992.0`.

### To Reproduce

```sql
-- this translation creates a strange number
WITH t1 AS ( (
            SELECT 9007199254740993 AS id  )
        UNION ALL (
            SELECT 2.1 AS id  ) )
SELECT To_Json( t ) AS json_objects
FROM t1 AS t;
```
```text
┌───────────────────────────┐
│ JSON_OBJECTS              │
├───────────────────────────┤
│ {"ID":9007199254740992.0} │
├───────────────────────────┤
│ {"ID":2.1}                │
└───────────────────────────┘
```
```sql
-- although this works
(SELECT 9007199254740993 AS ID)UNION ALL(SELECT 2.1 AS ID);
```
```text
┌──────────────────────────┐
│ ID                       │
├──────────────────────────┤
│ 9,007,199,254,740,993.00 │
├──────────────────────────┤
│                     2.10 │
└──────────────────────────┘
```

### OS:

Linux

### DuckDB Version:

1.1.3

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

Reichel

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks!

**Comment by lnkuiper** [comment]
Hi @manticore-projects, this is expected (but unfortunate) behavior.

Your CTE:
```sql
D SELECT 9007199254740993 AS id UNION ALL SELECT 1.2 AS id;
┌────────────────────┐
│         id         │
│   decimal(20,1)    │
├────────────────────┤
│ 9007199254740993.0 │
│                1.2 │
└────────────────────┘
```
Results in type `DECIMAL(20,1)`.

JSON only supports integers, strings, floats, and booleans (and nested types object/array). So, to convert this to JSON, we are forced to choose a float. However, floats do not have enough precision to store your large number:
```sql
D WITH cte AS (SELECT 9007199254740993 AS id UNION ALL SELECT 1.2 AS id) SELECT id::DOUBLE FROM cte;
┌────────────────────┐
│ CAST(id AS DOUBLE) │
│       double       │
├────────────────────┤
│ 9007199254740992.0 │
│                1.2 │
└────────────────────┘
```
The cast to `DOUBLE` loses some precision, which is the cast that is used when you do `to_json`.

**Comment by manticore-projects** [comment]
Thank you very much for the explanation @lnkuiper. I am able to understand what is happening.
Although: would it not be better to quote the Number when exceeding the Float? As it is right now it may crash your rocket.

**Comment by lnkuiper** [comment]
Hi @manticore-projects, I've looked into this and it has been possible to support full precision in yyjson (the JSON library we use) for some time now. When this was originally implemented, this was not supported. I've opened a PR https://github.com/duckdb/duckdb/pull/15112
