### ISSUE TITLE
Amalgamation  Compile

### ISSUE THREAD

**Issue by celibol** [duckdb/duckdb#15034]
### What happens?

I created the amalgamation files of DUCKDB.

But it cannot be compiled with QT and MingW.

The compiler gives the following errors

error: 'UnicodeType' does not name a type; did you mean 'DOMNodeType'?
error: 'GraphemeIterator' does not name a type
error: expected declaration before '}' token ---> namespace end

How to compile and use amalgamation files with QT and MingW or MS VC++ 2019

Can you help me please

### To Reproduce

error: 'UnicodeType' does not name a type; did you mean 'DOMNodeType'?
error: 'GraphemeIterator' does not name a type
error: expected declaration before '}' token ---> namespace end

### OS:

Windows

### DuckDB Version:

1.1.3

### DuckDB Client:

QT

### Hardware:

x86

### Full Name:

Cuneyt ELİBOL

### Affiliation:

Personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment]
Hi @celibol, thanks for raising this issue. Compiling with MinGW is not officially supported. That said, we have some instructions for compiling with MinGW in our documentation, see this section: https://duckdb.org/docs/dev/building/build_instructions#msys2-and-mingw64.

**Comment by celibol** [comment]
> Hi @celibol, thanks for raising this issue. Compiling with MinGW is not officially supported. That said, we have some instructions for compiling with MinGW in our documentation, see this section: https://duckdb.org/docs/dev/building/build_instructions#msys2-and-mingw64.

But It is not amalgamation compilation.

**Comment by szarnyasg** [comment]
Hi, indeed it isn't, so that's likely not useful.

More importantly: do you absolutely have to build with MinGW? 
It is not officially supported, so it's unlikely that the amalgamation MinGW build will be fixed by the core team. Of course, PRs are welcome! (as long as they don't break other builds)

If building with MSVC is possible, please try to apply the instructions here (https://duckdb.org/docs/dev/building/build_instructions#visual-studio) to the amalgamation build.

**Comment by celibol** [comment]
> Merhaba, kesinlikle öyle değil, bu yüzden pek işe yaramayacaktır.
> 
> Daha da önemlisi: MinGW ile inşa etmek zorunda mısınız? Resmi olarak desteklenmiyor, bu yüzden birleştirilmiş MinGW inşasının çekirdek ekip tarafından düzeltilmesi pek olası değil. Elbette, PR'ler hoş karşılanır! (diğer inşaları bozmadıkları sürece)
> 
> MSVC ile derleme yapmak mümkünse, lütfen burada ( https://duckdb.org/docs/dev/building/build_instructions#visual-studio ) verilen talimatları birleştirme derlemesine uygulamaya çalışın.

I Was try with VC++ 2019 

* Compile Orignal Source codes. Load ICU, CSV, PARQUEET, JSON Extension. But not load any another extension. (DBManager Not Found Error)

* VC++ 2019 Do not Compile Amalgamatin Sources

CMake Commands

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DENABLE_EXTENSION_AUTOLOADING=1 -DENABLE_EXTENSION_AUTOINSTALL=1 -DDISABLE_UNITY=1  -DOVERRIDE_GIT_DESCRIBE='v1.1.3' -DBUILD_EXTENSIONS="icu;parquet;autocomplete;json"

cmake --build . --config Release --parallel

And another question

What should I write for -DDUCKDB_EXTENSION_CONFIGS="${GITHUB_WORKSPACE}/.github/config/bundled_extensions.cmake"

**Comment by celibol** [comment]
**VC++ 2019 Compile Result**

![image](https://github.com/user-attachments/assets/4df28561-4c34-4dc5-984c-a5592426e4cc)

1. Dİfferent Exe, dll, lib Sizes
2. Compiled exe do not load any extension (Missin DB Managr Error)

**Comment by celibol** [comment]
I Was compile ...
