### ISSUE TITLE
current_date & current_time PostgreSQL incompatibility 

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#15069]
### What happens?

I opened a PR to the duckdb docs (https://github.com/duckdb/duckdb-web/pull/4206) stating current incompatibilty in the `current_date` and `current_time` pseudo-columns.

Usually, when duckdb differs from PostgreSQL it's for reasons I support. In this case, I think PostgreSQL's behavior is clearly better, so I wanted to raise this as an issue before it's enshrined into the docs.

DuckDB isn't even consistent within itself! `current_timestamp` returns a `TIMESTAMPTZ` and `current_localtimestamp()` a `TIMESTAMP` -- perfect --, but `current_time` returns a `TIME` while `current_localtime()` correctly returns a `TIME`. Clearly, `current_time` should return a `TIMETZ` like PostgreSQL does.

Also, there is no `current_localdate()` to get the correct local date (and that'd be perfectly fine if `current_date` did what it was supposed to; nobody needs to know the `current_date` in UTC, and if they were sure they absolutely did need to know, they could achieve that by setting their timezone or by using `timezone('UTC', current_timestamp)::DATE`)

### To Reproduce

```sql
SET TimeZone = 'Asia/Novosibirsk';
SELECT current_date, current_time, current_timestamp 
```
```
┌──────────────┬──────────────┬────────────────────────────┐
│ current_date │ current_time │     current_timestamp      │
│     date     │     time     │  timestamp with time zone  │
├──────────────┼──────────────┼────────────────────────────┤
│ 2024-11-30   │ 21:13:31.918 │ 2024-12-01 04:13:31.918+07 │
└──────────────┴──────────────┴────────────────────────────┘
```

### OS:

Linux

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Hardware:

i5, AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by krlmlr** [comment]
This breaks tests in the R bindings. CLI reproducer:

```sh
✗ echo 'SELECT current_date AS a' | build/debug/duckdb
duckdb(24121,0x1eac14f80) malloc: nano zone abandoned due to inability to reserve vm space.
Conversion Error:
Unimplemented type for cast (TIMESTAMP WITH TIME ZONE -> DATE)

LINE 1: SELECT current_date AS a
               ^
```

Opening an issue.

**Comment by hawkfish** [comment]
Sorry, this is a recent change:  You now need to have ICU loaded for `current_date` to function. SQL says it should return the date in the current time zone.

**Comment by krlmlr** [comment]
Indeed:

```
✗ echo 'INSTALL icu; LOAD icu; SELECT current_date AS a' | build/debug/duckdb
duckdb(27309,0x1eac14f80) malloc: nano zone abandoned due to inability to reserve vm space.
100% ▕████████████████████████████████████████████████████████████▏
┌────────────┐
│     a      │
│    date    │
├────────────┤
│ 2024-12-27 │
└────────────┘
```

**Comment by hawkfish** [comment]
`current_time` is the same, but `current_timestamp` works because we just use the raw instant value.
