### ISSUE TITLE
`age` PostgreSQL incompatibility and non-sensicality

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#15067]
### What happens?

In PostgreSQL, `age(arg)` returns ` current_date - arg`.

In DuckDB, `age(arg)` returns `current_timestamp - arg` when `arg` is a `TIMESTAMPTZ` and
`timezone('UTC', current_timestamp) - arg` when `arg` is a `TIMESTAMP`.

While I do prefer DuckDB's idea, so I hope this PostgreSQL incompatibility gets an official sign off, the implementation for `TIMESTAMP` in DuckDB is currently non-sensical. It should be `current_localtimestamp() - arg` instead.

### To Reproduce

```sql
SET timezone='Asia/Novosibirsk';
SELECT 
current_localtimestamp() AS local, age(current_localtimestamp()) AS age_local, timezone('UTC', current_timestamp) - current_localtimestamp() AS synth,
current_timestamp AS localtz, age(current_timestamp) AS age_localtz, current_timestamp - current_timestamp AS synthtz
```
```
┌─────────────────────────┬───────────────┬───────────┬────────────────────────────┬──────────────┬──────────┐
│          local          │   age_local   │   synth   │          localtz           │ age_localtz  │ synthtz  │
│        timestamp        │   interval    │ interval  │  timestamp with time zone  │   interval   │ interval │
├─────────────────────────┼───────────────┼───────────┼────────────────────────────┼──────────────┼──────────┤
│ 2024-12-01 04:00:05.254 │ -06:59:59.999 │ -07:00:00 │ 2024-12-01 04:00:05.254+07 │ 00:00:00.001 │ 00:00:00 │
└─────────────────────────┴───────────────┴───────────┴────────────────────────────┴──────────────┴──────────┘
```

`age_local` should be all zeros!

### OS:

Linux

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Hardware:

i5, AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Th e big issue here is that `age` is not really even using `current_timestamp`! It should be using the [date of the current transaction](https://www.postgresql.org/docs/16/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT):

```
These SQL-standard functions all return values based on the start time of the current transaction
```

Instead, it grabs the system clock, which is not correct.

Another wrinkle is that `current_date` depends on the current time zone, which will be tricky since TZ may not even be available if ICU is not loaded.

**Comment by hawkfish** [comment]
It might make sense to add a rewrite for single-argument `age` to add the default argument.

**Comment by hawkfish** [comment]
OK, here is the deal: Unlike PG we have to be able to function without ICU being loaded, so we overload the `age` function for both TS and TSTZ arguments. The latter will behave like PG, but the former will act like it is in UTC. 

There is an issue here that the single argument versions are not using the correct timestamp in either place, and that is a bug.

**Comment by hawkfish** [comment]
I have no explanation for the bizarre "negative" behaviour of PG:

```sql
hawkfish=# select current_timestamp, age(current_timestamp);
       current_timestamp       |       age        
-------------------------------+------------------
 2024-11-30 17:19:04.271379-08 | -17:19:04.271379
(1 row)
```

But this is what we will emulate.

**Comment by soerenwolfers** [comment]
> the former will act like it is in UTC"
Does that mean that after your fix, the `TIMESTAMP` version still sometimes return negative answers for `age(current_localtimestamp())` ? Can't this function simply be defined to be `current_localtimestamp()::DATE - arg` (modulo the transaction thing), which shouldn't need ICU? 

By the way, given that ICU ships with DuckDB by default and afaict can't even unloaded (at least in the Python client), wouldn't it be best to hide the fact that that functionality started out as an extension from users?

**Comment by hawkfish** [comment]
Both implementations will return negative answers for today, andI have verified that the new behaviour matches PG.

ICU is not always loaded (the WASM version does not load its automatically).

**Comment by soerenwolfers** [comment]
@hawkfish I think DuckDB still gets it wrong:

In DuckDB, I just got 

```sql
SET timezone='Asia/Novosibirsk';
SELECT 
  current_timestamp,
  testTimestamp, 
  age(testTimestamp) AS ageOfTestTimestamp, 
  timezone('UTC', current_timestamp)::DATE - testTimestamp AS whatDuckDBDoes,
  current_timestamp::DATE - testTimestamp AS whatPostgreSQLDoes
FROM (SELECT '2024-12-07 20:00:00'::TIMESTAMP as testTimestamp)
```
|    | current_timestamp                | testTimestamp       | ageOfTestTimestamp   | whatDuckDBDoes    | whatPostgreSQLDoes   |
|---:|:---------------------------------|:--------------------|:---------------------|:------------------|:---------------------|
|  0 | 2024-12-08 03:00:05.575000+07:00 | 2024-12-07 20:00:00 | -1 days +04:00:00    | -1 days +04:00:00 | 0 days 04:00:00      |

but in PostgreSQL, I got 

```sql
SET timezone='Asia/Novosibirsk';
SELECT 
  current_timestamp,
  testTimestamp, 
  age(testTimestamp) AS ageOfTestTimestamp, 
  timezone('UTC', current_timestamp)::DATE - testTimestamp AS whatDuckDBDoes,
  current_timestamp::DATE - testTimestamp AS whatPostgreSQLDoes
FROM (SELECT '2024-12-07 20:00:00'::TIMESTAMP as testTimestamp)
```

| current_timestamp             | testtimestamp       | ageoftesttimestamp | whatduckdbdoes | whatpostgresqldoes |
| ----------------------------- | ------------------- | ------------------ | -------------- | ------------------ |
| 2024-12-08 03:00:08.373331+07 | 2024-12-07 20:00:00 | 04:00:00           | -20:00:00      | 04:00:00           |


[View on DB Fiddle](https://www.db-fiddle.com/)

**Comment by hawkfish** [comment]
I'm not seeing that on `HEAD` at the moment:

DuckDB:

```sql
D SET timezone='Asia/Novosibirsk';
D SELECT 
    current_timestamp,
    testTimestamp, 
    age(testTimestamp) AS ageOfTestTimestamp, 
    timezone('UTC', current_timestamp)::DATE - testTimestamp AS whatDuckDBDoes,
    current_timestamp::DATE - testTimestamp AS whatPostgreSQLDoes
  FROM (SELECT '2024-12-08 20:00:00'::TIMESTAMP as testTimestamp) t;
````
|     current_timestamp      |    testTimestamp    | ageOfTestTimestamp | whatDuckDBDoes | whatPostgreSQLDoes |
|----------------------------|---------------------|--------------------|----------------|--------------------|
| 2024-12-08 12:27:21.909+07 | 2024-12-08 20:00:00 | -20:00:00          | -20:00:00      | -20:00:00          |

Postgres:

```sql
SET timezone='Asia/Novosibirsk';
SET
SELECT 
  current_timestamp,
  testTimestamp, 
  age(testTimestamp) AS ageOfTestTimestamp, 
  timezone('UTC', current_timestamp)::DATE - testTimestamp AS whatDuckDBDoes,
  current_timestamp::DATE - testTimestamp AS whatPostgreSQLDoes
FROM (SELECT '2024-12-08 20:00:00'::TIMESTAMP as testTimestamp) t;
       current_timestamp       |    testtimestamp    | ageoftesttimestamp | whatduckdbdoes | whatpostgresqldoes 
-------------------------------+---------------------+--------------------+----------------+--------------------
 2024-12-08 12:25:57.809954+07 | 2024-12-08 20:00:00 | -20:00:00          | -20:00:00      | -20:00:00
(1 row)
```

**Comment by soerenwolfers** [comment]
@hawkfish You have to pick a timezone where the current date is different from the current UTC date. 

E.g., right now, on a duckdb built fresh from today's main:

```
(ins)11:12~/ddb/duckdb$ ./build/release/duckdb
v1.1.4-dev3046 63a971e742
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET timezone='NZ';
D SELECT 
    current_timestamp,
    testTimestamp, 
    age(testTimestamp) AS ageOfTestTimestamp, 
    timezone('UTC', current_timestamp)::DATE - testTimestamp AS whatDuckDBDoes,
    current_timestamp::DATE - testTimestamp AS whatPostgreSQLDoes
  FROM (SELECT '2024-12-07 20:00:00'::TIMESTAMP as testTimestamp);
┌────────────────────────────┬─────────────────────┬────────────────────┬────────────────┬────────────────────┐
│     current_timestamp      │    testTimestamp    │ ageOfTestTimestamp │ whatDuckDBDoes │ whatPostgreSQLDoes │
│  timestamp with time zone  │      timestamp      │      interval      │    interval    │      interval      │
├────────────────────────────┼─────────────────────┼────────────────────┼────────────────┼────────────────────┤
│ 2024-12-09 00:12:56.205+13 │ 2024-12-07 20:00:00 │ 04:00:00           │ 04:00:00       │ 1 day 04:00:00     │
└────────────────────────────┴─────────────────────┴────────────────────┴────────────────┴────────────────────┘
```

**Comment by hawkfish** [comment]
Ah right I forgot - this is deliberate. When there are no TZ types involved, we don't use ICU, so `age(TS)` will always use the UTC `DATE`.

**Comment by soerenwolfers** [comment]
Couldn't you get the best of both worlds by making `age(TS)` always return the PG-compatible result, only that without ICU loaded, the interpretation is that the timezone is UTC? (Similar to how TSTZ are displayed using UTC offset when ICU isn't loaded and how TSTZ->TS conversion assumes UTC.)

**Comment by hawkfish** [comment]
We can't (currently) override function definitions in extensions, only add them (they get added to the end of the catalog lookup, but the original function will match first.) 

Casts can override, though, and that is why we can display differently (it's a cast to `VARCHAR`).  If we ever have function replacement, then we could do this.

**Comment by soerenwolfers** [comment]
Thanks for the explanations 👍
