### ISSUE TITLE
`* RENAME (...) LIKE ...` is broken

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#15073]
### What happens?

The combination of `RENAME` and `LIKE` in a star expression currently ignores the `RENAME`.

### To Reproduce

```sql
SELECT * RENAME (number2 as test) LIKE '%number%'
FROM (SELECT 1 AS number1, 2 AS number2)
```
```
┌─────────┬─────────┐
│ number1 │ number2 │
│  int32  │  int32  │
├─────────┼─────────┤
│       1 │       2 │
└─────────┴─────────┘
```
but should return only `number1`. 

Alternatively, the combination of `RENAME` and `LIKE` should simply be disallowed.

(Currently, combinations of `RENAME` / `REPLACE` / `EXCLUDE` / `LIKE` are only allowed if [the first modifier is `EXCLUDE` and there is only one additional modifier] or [the combination in this issue, which is broken].) 

### OS:

Linux

### DuckDB Version:

1.1.4-devxxxx

### DuckDB Client:

Python

### Hardware:

i5, AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Maxxen** [comment]
On DuckDB 1.1.3 this throws a parse error:
```sql
SELECT * RENAME (number2 as test) LIKE '%number%'
FROM (SELECT 1 AS number1, 2 AS number2);
----
Parser Error: syntax error at or near "RENAME"
LINE 1: SELECT * RENAME (number2 as test) LIKE '%number%...
```

**Comment by soerenwolfers** [comment]
Oh sorry I'm on the latest `pip install duckdb --upgrade --pre ` release, not 1.1.0 as originally stated in my issue.
