### ISSUE TITLE
read_csv: "preservation of insertion order" vs parallel=true: bug? documentation issue? enhancement?

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#15098]
### What happens?

https://duckdb.org/docs/sql/dialect/order_preservation.html
says that read_csv() preserves insertion order.

But when last() is used, there is a dependence on whether or not parallel=true:
```
D select version();
┌────────────────┐
│  "version"()   │
│    varchar     │
├────────────────┤
│ v1.1.4-dev2677 │
└────────────────┘

.system jot 10000000 1 > seq.txt

D select last(line) from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false);
┌──────────────┐
│ "last"(line) │
│   varchar    │
├──────────────┤
│ 10000000     │
└──────────────┘

SET memory_limit = '100MB';
D select last(line) from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=true);
┌──────────────┐
│ "last"(line) │
│   varchar    │
├──────────────┤
│ 9138889      │
└──────────────┘
```
Now it is true that the documentation at order_preservation.html does
carve out an exception for order-sensitive aggregate functions, but
the caveat is in the `GROUP BY` section, so it's not entirely clear
whether the caveat is supposed to apply when there is no GROUP BY.

In any case, if the use of last() without `GROUP BY` is intended to void
order preservation, then the question becomes: if I want last() to retrieve
the last row as if there were an appropriate ORDER BY clause, how
could this be done efficiently in the absence of a suitable column?

That is, using the seq.txt example, something more efficient than:
```
select last(line order by rowid) 
  from (select *, row_number() OVER () as rowid
        from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}));
```

**Would `last(line order by table)` be a viable enhancement?**

### To Reproduce

```sql
.system jot 10000000 1 > seq.txt
SET memory_limit = '100MB';
select last(line) from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=true);
```

### OS:

MacOS

### DuckDB Version:

v1.1.4-dev2677 et al

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This is a bug! Thanks, we'll take a look.

**Comment by soerenwolfers** [comment]
@szarnyasg What is the intended behavior exactly? I'd be eager to amend the "Order Preservation" page. 

I have previously said in a comment under https://github.com/duckdb/duckdb/issues/15011 that I think

> All order-sensitive aggregate functions should default to using the rowid-order or the explicit ORDER BY clause of the table/query in the FROM clause, where applicable, so to remove a very common footgun

Are you saying that this is in fact *already* true (up to the bug here?) for `GROUP BY ()` statements but not for `GROUP BY <any-non-empty-group>` statements?

**Comment by pdet** [comment]
Hi @pkoppstein 

Indeed, this is currently intended behavior, the `LAST` function does not guarantee order if parallelism is on.

This is also for any of our scanners.

If you do export it to a new csv file, you can see that the order is preserved.

``` sql
COPY (from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR})) TO 'seq_2.txt'
```

You can for example perform the same test with a parquet file:

```sql
COPY (from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false)) TO '/Users/holanda/Desktop/seq.parquet'

select last(line) from read_csv('/Users/holanda/Desktop/seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false);

select last(line) from 'seq.parquet';
```

Also this is already documented in https://duckdb.org/docs/sql/functions/aggregates:

```
his clause ensures that the values being aggregated are sorted before applying the function. Most aggregate functions are order-insensitive, and for them this clause is parsed and discarded. However, there are some order-sensitive aggregates that can have non-deterministic results without ordering, e.g., first, last, list and string_agg / group_concat / listagg. These can be made deterministic by ordering the arguments.
```
