### ISSUE TITLE
INSERT ignores column names and assumes positional order matches table

### ISSUE THREAD

**Issue by evantahler** [duckdb/duckdb#15097]
### What happens?

When inserting data into a table from another table, the column names used are not considered when inserting.  Similarly, explicit `AS` statements are also ignored.  

This is likely related to https://github.com/duckdb/duckdb/issues/3506

### To Reproduce

```sql
create table test_table ( id integer, name string, created_at timestamptz );

-- works fine, because the insert order matches the table order
insert into test_table (select 1 as id, 'aaa' as name, NOW() as created_at);

-- does not work, because the insert order has changed from the table order (name is before id)
insert into test_table (select 'bbb' as name, 2 as id, NOW() as created_at);
```

The last statement raises an error of the form: `Conversion Error: Could not convert string 'bbb' to INT32`

### OS:

Apple Mac M1, MacOS 15

### DuckDB Version:

v1.1.2 f680b7d08f

### DuckDB Client:

command line

### Full Name:

Evan Tahler

### Affiliation:

Airbyte

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Maxxen** [comment]
I think you need to pass `BY_NAME` https://duckdb.org/docs/sql/statements/insert.html#insert-column-order

**Comment by evantahler** [comment]
That's exactly what I want!
