### ISSUE TITLE
read_csv(): excessive memory requirements even when the task is only to count or retrieve a single line.

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#15108]
### What happens?

Please note that this issue is being reported in the hopes of making a great tool even greater!

Given the general orientation of DuckDB to managing memory frugally
and smartly, one might expect that DuckDB could handle a query that only
requires retaining at most one CSV line in memory at a time, but in fact it
requires enough memory to hold almost the entire file.

### The file:

```
.system jot 10000000 1 > seq.txt
```

#### So each line is tiny.

If the file is read in as a whole and saved to an in-memory table, the
total temporary_storage_bytes is 104,330,128, and
memory_usage_bytes = 46,223,360.

The following queries succeed as expected:

```
SET memory_limit = '105MB';
select count(*) from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false, auto_detect=false) OFFSET 10000000 - 1 LIMIT 1;
select last(line) from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false);
select line from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false, auto_detect=false) OFFSET 10000000 - 1 LIMIT 1;
```

However, they all fail with memory_limit values as high as 96MB.

Comments:

(1) One might have hoped that the push-down and counting logic would mean the RAM requirements would be tiny in all three cases.

(2) Even without any push-down logic, DuckDB is supposed to be able to use disk space when it runs
out of memory.  Since it seems that by DuckDB's own accounting, at most 46MB of memory (memory_usage_bytes) is
actually required, it is difficult to see why it fails when allowed to use significantly more than that.

### To Reproduce

```
SET memory_limit = '50MB';
select line from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false, auto_detect=false) OFFSET 10000000 - 1 LIMIT 1;
```

### OS:

MacOS

### DuckDB Version:

 v1.1.4-dev2677

### DuckDB Client:

CLI

### Hardware:

MacMini

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report!

DuckDB is not really designed for these extremely low memory scenarios - and a base amount of memory is expected to be available. In this case, the CSV reader uses a default buffer size of 32MB with the expectation that a lot of data will be processed, which is very close to the memory limit set here.

The query works fine if the CSV readers' buffer size is reduced:

```sql
SET memory_limit = '50MB';
select line from read_csv('seq.txt', header=false, sep='', columns={'line': VARCHAR}, parallel=false, auto_detect=false, buffer_size=3200) OFFSET 10000000 - 1 LIMIT 1;
┌──────────┐
│   line   │
│ varchar  │
├──────────┤
│ 10000000 │
└──────────┘
```

This could be addressed in various ways - but it is not an immediate priority.

**Comment by pkoppstein** [comment]
@Mytherin - Thanks for the response and in particular for mentioning buffer_size.

We've had some reports about memory-management issues in a complex
environment involving DuckDB on a cluster, and I've been trying to get
a better understanding of how DuckDB does (or is supposed to) handle
various challenging scenarios.  It's so convenient to be able to
lower the memory_limit artificially that it's often tempting to do so!
