### ISSUE TITLE
The code needs more const

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1511]
As we move towards greater threading, it would be nice if we started using `const` more carefully. As of C++11, `const` really means "thread safe" and it would be great if we could start using it in objects that get passed around a lot.

In aid of this, it would be great if we could get rid of the formatting rule that require `const` instance variables to be in UPPERCASE. This does not improve readability IMHO and takes me back to the coding standards of the 1970s. In particular, this formatting rule makes moving code into a `Task` class somewhat onerous because you have to go and change all the cases of the variables.

**Comment by Mytherin** [comment]
Agreed, sounds good.

**Comment by hawkfish** [comment]
I think you can add a `// NOLINT` comment after the variable to defeat this but I haven't tried it yet.

**Comment by Mytherin** [comment]
I would rather change the formatting rules for const variables in the `.clang-tidy`. NOLINT should be kept to a minimum.

**Comment by hawkfish** [comment]
So I can remove

```   - key:             readability-identifier-naming.ClassConstantCase
    value:           UPPER_CASE
```

Or make it `lower_case` to match the non-`const` members?

**Comment by Mytherin** [comment]
If you remove it it will fall back to the more general case (which I believe is the variable, i.e. lower_case, see [the docs here for more info](https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html)). I'm fine with changing it to aNy_CasE, that should be easier.

**Comment by hawkfish** [comment]
Ah that makes more sense.

**Comment by hawkfish** [comment]
This is more of a coding standard now.
