### ISSUE TITLE
new_line parameter of read_csv method not working

### ISSUE THREAD

**Issue by Shinena1998** [duckdb/duckdb#15143]
### What happens?

My data set may contain LF, so when I generate the csv file, the new line character(s) is set to '\r\n'. 
However, when reading the csv file, even if the new_line option is set, the LF is still considered a new line character.

### csv file
[1.csv](https://github.com/user-attachments/files/18019800/1.csv)

```
❯ cat 1.csv | xxd
00000000: 312c 322c 330a 342c 352c 360d 0a37 2c38  1,2,3.4,5,6..7,8
00000010: 2c39 0a                                  ,9.
```
You can see that the first and second lines are LF, and the second and third lines are CRLF

### read csv
```
❯ ./duckdb
v1.1.3 19864453f7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select * from read_csv('./1.csv', delim = ',', header = false,new_line = '\r\n', columns = {'a':'VARCHAR','b':'VARCHAR','c':'VARCHAR'});
┌─────────┬─────────┬─────────┐
│    a    │    b    │    c    │
│ varchar │ varchar │ varchar │
├─────────┼─────────┼─────────┤
│ 1       │ 2       │ 3       │
│ 4       │ 5       │ 6       │
│ 7       │ 8       │ 9       │
└─────────┴─────────┴─────────┘

```
It was expected to report an error, but 3 lines were read normally.

### OS:

macos 14.6.1 arm

### DuckDB Version:

v1.1.3 19864453f7

### DuckDB Client:

brew install

### Full Name:

z

### Affiliation:

b

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by iamsachin45** [comment]
I would like to contribute on this issue. Please let me know.
