### ISSUE TITLE
Incorrect EXPLAIN details for query

### ISSUE THREAD

**Issue by whelanmike** [duckdb/duckdb#15162]
### What happens?

Firstly, the query works as expected, but EXPLAIN is giving an error in the output.
The predicate in my subquery only returns a single row, yet I get the following from EXPLAIN.

```┌─────────────┴─────────────┐
│         PROJECTION        │
│    ────────────────────   │
│ CASE  WHEN ((#1 > 1)) THEN│
│  (error('More than one row│
│   returned by a subquery  │
│   used as an expression - │
│    scalar subqueries can  │
│  only return a single row.│
│          Use "SET         │
│ scalar_subquery_error_on_m│
│   ultiple_rows=false" to  │
│     revert to previous    │
│   behavior of returning a │
│ random row.')) ELSE #0 END│
│                           │
│          ~1 Rows          │
└─────────────┬─────────────┘
```

### To Reproduce

```sql
create schema repro
;

create table repro.file_load_history(
     filename           varchar     not null
    ,load_timestamp     timestamp   not null
)
;

create table repro.load_on_first_run(
     id         int
    ,who        varchar
    ,event_date date
)
;


-- only allow insertions if file_load_history table has one or less rows
explain 
insert into repro.load_on_first_run
    select 
           0                        as id
          ,'system'                 as who
          ,current_timestamp::date  as event_date
    where 1=1
          and (select case when count(1) <=1 then true else false end as x from repro.file_load_history) 
;          
```

### OS:

Microsoft Windows [Version 10.0.22621.4460] x64-based PC

### DuckDB Version:

v1.1.1

### DuckDB Client:

DBeaver

### Full Name:

Mike Whelan

### Affiliation:

none

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
That's not an error, that is the crafted CASE expression used to check if a scalar subquery produces more than a single row, which would be an error

**Comment by Mytherin** [comment]
As indicated that's the error function, this is intentional
