### ISSUE TITLE
JDBC: Connection reopening issues between version 0.2.3 and 0.2.4/0.2.5 + Differences with Python Client API

### ISSUE THREAD

**Issue by k138z** [duckdb/duckdb#1516]
My Java application wants to open a read-write connection to a file-backed DuckDB database once (on startup), run a few DDL queries and close the connection. After this I want to allow multiple read-only connections to the same database. Here are a few scenarios I have observed across versions and between the JDBC and Python client APIs:

**JDBC**:

```java
DuckDBDatabase db = new DuckDBDatabase(dbpath,false); //read-write connection
Connection c1 = new DuckDBConnection(db);
//execute DDL query e.g. CREATE TABLE
c1.close();
db.shutdown();

Connection c2 = new DuckDBConnection(new DuckDBDatabase(dbpath,true)); //read-only connection
//execute SELECT query
c2.close()
```

**version 0.2.3** - works as expected
**version 0.2.4, 0.2.5** - c2 throws 'file is being used by another process' exception

Although the example code above is running in the same process, I see the same behaviour when c1 and c2 are created in different processes. Within the same process I can get the code to work if I do `c2 = (DuckDBConnection) c1.duplicate()` - but here c2 is also a read-write connection which is not ideal, and this solution will not work across processes anyway.

**Python**: works with 0.2.5, both within the same process and across processes

```python
c1 = duckdb.connect(database=dbpath, read_only=False)
#execute DDL query
c1.close()
c2 = duckdb.connect(database=dbpath, read_only=True)
#execute SELECT query
c2.close()
```

I'm not sure if my access pattern is incorrect here. Another thing to note is if I remove the `db.shutdown()` line from the Java code then none of the 3 tested DuckDB versions work (as is expected, I guess). Any help here is appreciated - we would really like to use the new features the latest DuckDB versions provide but we're stuck with this issue now.

**Comment by hannesmuehleisen** [comment]
Indeed there was some behaviour change around shutdown recently. Will have to investigate.

**Comment by k138z** [comment]
Also, another way this problem shows up is when using a client like DBeaver to make a read-write connection to the database - the file is held in use by the DBeaver process even after the connection is closed and deleted from the GUI. Only when the DBeaver process is closed that other process can open connections to the database file.

**Comment by hannes** [comment]
Tracked in #1683
