### ISSUE TITLE
OOM on ORDER BY query

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#15174]
### What happens?

While sorting a table with 200M double entries (=1.6GB of uncompressed data) and writing the results back to parquet, DuckDB uses more than the `MEMORY_LIMIT` and gets out-of-memory killed.

### To Reproduce

In a plain `./duckdb` terminal instance, run 
```sql
SET memory_limit='9GB';
CREATE OR REPLACE TABLE df AS (SELECT random() AS x FROM range(200_000_000));
COPY (SELECT * FROM df ORDER BY x) TO '/tmp/test.parquet';
```
```
 45% ▕███████████████████████████                                 ▏ Killed
```

At the time of the OOM-kill, DuckDB uses >10.5GB of memory according to htop-RES. 

### OS:

Ubuntu 20.04, x86_64

### DuckDB Version:

1.1.3

### DuckDB Client:

Terminal

### Hardware:

16GB RAM

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, I re-ran this but couldn't reproduce it on either macOS or Linux. Here's the output for Linux on stable and nightly:
```
v1.1.3 19864453f7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET memory_limit='9GB';
D CREATE OR REPLACE TABLE df AS (SELECT random() AS x FROM range(200_000_000));

100% ▕████████████████████████████████████████████████████████████▏
D COPY (SELECT * FROM df ORDER BY x) TO '/tmp/test.parquet';
100% ▕███████████████████████████████████████████████████████████
```
```
v1.1.4-dev2261 ed90e384ef
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET memory_limit='9GB';
D CREATE OR REPLACE TABLE df AS (SELECT random() AS x FROM range(200_000_000));

100% ▕████████████████████████████████████████████████████████████▏
D COPY (SELECT * FROM df ORDER BY x) TO '/tmp/test.parquet';
 49% ▕█████████████████████████████▍                              ▏

100% ▕████████████████████████████████████████████████████████████▏
```

**Comment by soerenwolfers** [comment]
@szarnyasg this might require some fine tuning. The main point being that duckdb doesn't stick to the limit, in case you can verify that elsehow.

**Comment by szarnyasg** [comment]
DuckDB doesn't fully stick to the limit. There is a comment in the documentation: https://duckdb.org/docs/configuration/pragmas#memory-limit

![Screenshot 2024-12-09 at 07 39 33](https://github.com/user-attachments/assets/fa27b050-fccb-46f6-8a01-b85a946034b2)

This took me a few minutes to find, which is not ideal... I'll also add it to the operations manual where people are more likely to look for this.
