### ISSUE TITLE
Apply time zone on timestamp when reading parquet

### ISSUE THREAD

**Issue by srmarjani** [duckdb/duckdb#15192]
### What happens?

Hi.
I have a parquet files that has a column that is timestamp with format like  '2024-12-06 00:00:00'
when i import this parquet into duckdb it convert timestamp to '2024-12-05 20:30:00'
In source parquet there is no time zone info, but  duckdb use system timezone

### To Reproduce

No

### OS:

linux

### DuckDB Version:

1.1.3

### DuckDB Client:

CLI

### Full Name:

Razi Marjani

### Affiliation:

Cafebazaar

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by soerenwolfers** [comment]
You can solve your "problem" with 
```sql
SET timezone='UTC';
```

If you want to learn more about the subject and learn why the behavior you describe in your post is not actually a problem, see https://duckdb.org/2022/01/06/time-zones.html.

**Comment by hawkfish** [comment]
I believe @soerenwolfers is correct, but it would help if you could include a small example parquet file. Even one value would be enough.

**Comment by srmarjani** [comment]
This solution doesn't work for me.
How can I send sample parquet files

**Comment by szarnyasg** [comment]
Please mail them to gabor@duckdblabs.com
