### ISSUE TITLE
UPDATE triggers assertion

### ISSUE THREAD

**Issue by hannesmuehleisen** [duckdb/duckdb#1522]
As reported by @skinkie, minified somewhat by me

````SQL
CREATE TABLE filehash(hash VARCHAR, size BIGINT, filename VARCHAR, deleted boolean);
COPY filehash (hash, size, filename) FROM 'hash-combined-small.gz' (DELIMITER ',', QUOTE '"');
CREATE TABLE symlink (filename varchar);
COPY symlink FROM 'symlink-small.gz' (delimiter '!');
UPDATE filehash SET deleted = true WHERE filename IN (SELECT filename FROM symlink);
````

[hash-combined-small.gz](https://github.com/cwida/duckdb/files/6176960/hash-combined-small.gz)
[symlink-small.gz](https://github.com/cwida/duckdb/files/6176961/symlink-small.gz)

This reliably triggers the following assertion:
`
Error: near line 6: INTERNAL Error: Assertion triggered in file "/Users/hannes/source/duckdb/src/storage/table/update_segment.cpp" on line 437: (idx_t)ids[i] >= vector_offset && (idx_t)ids[i] < vector_offset + STANDARD_VECTOR_SIZE
`

**Comment by Mytherin** [comment]
This appears to be fixed - I can no longer trigger the assertion on the latest master.
