### ISSUE TITLE
"out of range" error when reading parquet with unsigned tinyint or unsigned smallint

### ISSUE THREAD

**Issue by datbth** [duckdb/duckdb#15221]
### What happens?

"out of range" error when reading parquet with unsigned tinyint (unsigned int8) or unsigned smallint (unsigned int16).  

Error message for tinyint:
```
Invalid Input Error: Failed to cast value: Type UINT32 with value 4294967295 can't be cast because the value is out of range for the destination type UINT8
```

Error message for smallint:
```
Invalid Input Error: Failed to cast value: Type UINT32 with value 4294967295 can't be cast because the value is out of range for the destination type UINT16
```

### To Reproduce

Create a **parquet** file **containing at least 1 row** with this **schema**:
```
message schema {
  OPTIONAL INT32 hcol0 (INTEGER(8,false));
}
```
or
```
message schema {
  OPTIONAL INT32 hcol0 (INTEGER(16,false));
}
```

Use Duckdb to query the parquet:
```sql
select hcol0 from READ_PARQUET('data.parquet');
```

Example parquet files (the extension is put as `.txt` to be able to upload here)
[utinyint.txt](https://github.com/user-attachments/files/18060837/utinyint.txt)
[usmallint.txt](https://github.com/user-attachments/files/18060836/usmallint.txt)

```sql
select hcol0 from read_parquet('utinyint.txt');
select hcol0 from read_parquet('usmallint.txt');
```

### OS:

linux

### DuckDB Version:

1.1.3

### DuckDB Client:

CLI

### Full Name:

Dat Bui

### Affiliation:

holistics.io

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, I could reproduce the issue!

**Comment by Mytherin** [comment]
Thanks for the report!

DuckDB trips up over the statistics - which look corrupt to me:

```sql
D select stats_min_value, stats_max_value from parquet_metadata('data/parquet-testing/out_of_range_stats.parquet');
┌─────────────────┬─────────┬────────────┐
│     Column      │  Type   │   Row 1    │
├─────────────────┼─────────┼────────────┤
│ stats_min_value │ varchar │ 4294967295 │
│ stats_max_value │ varchar │        255 │
└─────────────────┴─────────┴────────────┘
```

As you can see, `stats_min_value` is larger than `stats_max_value`, and larger than the largest allowable value in the domain of the type.

We can ignore the stats in this case - I've pushed a fix for this in #15233 - but you might also want to file an issue with the tool that produced the file.

**Comment by datbth** [comment]
hi @Mytherin, thank you for looking into this.

I got these stats when using python with `pyarrow 18.1.0`.   
Is there a chance those stats are also inferred by duckdb itself? :thinking:

**Comment by Mytherin** [comment]
Most likely Arrow sets the `min` value to the `max` value if it is bigger than the `max` value. The values encoded in the file are `min: 4294967295, max: 255`.
