### ISSUE TITLE
"Information loss on integer cast" for pre-1970 timestamp_ns

### ISSUE THREAD

**Issue by eirikbakke** [duckdb/duckdb#15246]
### What happens?

The query "select '1969-01-01T23:59:59.9999999'::timestamp_ns;" gives the following error:

```
INTERNAL Error: Information loss on integer cast: value -99952 outside of target range [-128, 127]
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### To Reproduce

Run the query
```sql
select '1969-01-01T23:59:59.9999999'::timestamp_ns;
```
on DuckDB v1.1.3 19864453f7. The error will appear.

### OS:

MacOS ARM (Darwin 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8122 arm64)

### DuckDB Version:

v1.1.3 19864453f7

### DuckDB Client:

Command-line "duckdb" on MacOS

### Hardware:

MacBook Air Apple M3

### Full Name:

Eirik Bakke

### Affiliation:

Ultorg Inc.

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @eirikbakke, thanks for reporting this. I could also reproduce the error on the nightly build.

**Comment by eirikbakke** [comment]
That was quick; thanks for the fix! --Eirik
