### ISSUE TITLE
Failed to download Postgres extension

### ISSUE THREAD

**Issue by davidjbrennan** [duckdb/duckdb#15265]
### What happens?

The OSX nightly build for yesterday completed successfully so I downloaded the cli using the following link from the installation web page. I then proceeded to install postgres, as I always do, and was surprised to see that it couldn't find the extension despite the job having succeeded.

### To Reproduce

Download the CLI using the link on the installation page of the website.
https://artifacts.duckdb.org/latest/duckdb-binaries-osx.zip
Extract and run duckdb.
```
install postgres;
Failed to download extension "postgres_scanner" at URL "http://extensions.duckdb.org/067ecb1c7f/osx_arm64/postgres_scanner.duckdb_extension.gz" (HTTP 403)
```

### OS:

OSX

### DuckDB Version:

v1.1.4-dev3162 067ecb1c7f

### DuckDB Client:

CLI

### Full Name:

David Brennan

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
This is expected to be solved in the nightly to be triggered in 12 hours.

Thanks a lot for raising this.

**Comment by davidjbrennan** [comment]
Thanks for being so responsive on this and thanks for such an awesome product.
