### ISSUE TITLE
unescaped double-quote in column lookup in Python relational API

### ISSUE THREAD

**Issue by nickzoic** [duckdb/duckdb#15267]
### What happens?

When using the python relational API, column names with `"` in them don't seem to be escaped properly.

### To Reproduce

python code:

```
import duckdb
c = duckdb.connect()
t = c.sql('select 1 as "tricky"", ""quotes", 2 as tricky, 3 as quotes')

print("t:")
print(t)

print("t[t.columns[0]]:")
print(t[t.columns[0]])
```

output:

```
t:
┌──────────────────┬────────┬────────┐
│ tricky", "quotes │ tricky │ quotes │
│      int32       │ int32  │ int32  │
├──────────────────┼────────┼────────┤
│                1 │      2 │      3 │
└──────────────────┴────────┴────────┘

t[t.columns[0]]:
┌────────┬────────┐
│ tricky │ quotes │
│ int32  │ int32  │
├────────┼────────┤
│      2 │      3 │
└────────┴────────┘
```

It looks like internally it's translating that lookup to `SELECT "tricky", "quotes"` instead of the correct `SELECT "tricky"", ""quotes"`

### OS:

Linux 6.8.0-49-generic x86_64

### DuckDB Version:

1.1.3 

UPDATE: Also 1.1.4-dev3247

### DuckDB Client:

Python, on Python 3.12.3

### Full Name:

Nick Moore

### Affiliation:

Mnemote Pty Ltd

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

UPDATE: Also 1.1.4-dev3247

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by Tishj** [comment]
The python client is not doing anything special here, this is the same result you'd get with the CLI for this query.

As seen by your result, every quote you intend to escape should be doubled

**Comment by nickzoic** [comment]
Yep, and in SQL / the CLI that makes sense.  But the within the Python API, the `[]` operator should be doing the quoting for you, and `t[t.columns[0]]` should always get the first column!

As it is, it does do *some* quoting when constructing the query, it seems to be inserting `"` before and after the identifier, just not escaping `"` to `""` within the identifier.

**Comment by szarnyasg** [comment]
Hi @nickzoic thanks for opening this. I could reproduce it as follows:

```python
import duckdb
t=  duckdb.sql('select 1 as "hello ""quoted"" world", 2 as asd, 3 as qwe;')
print(t[t.columns[0]])
```

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "" world""
```

**Comment by nickzoic** [comment]
Awesome, thanks!
