### ISSUE TITLE
In Python, `create()` function from `read_csv()` source doesn't work

### ISSUE THREAD

**Issue by OlivierBinette** [duckdb/duckdb#15288]
### What happens?

Trying to read a 1Gb csv file and create a corresponding table. Works fine if I save as parquet file as intermediate step, doesn't work if I try to call `table.create()` after `table = con.read_csv()`. Full example here: https://github.com/PatentsView/PatentsView-Code-Examples/blob/duckdb-csv-bug/data-downloads/1-joining-tables.ipynb

### To Reproduce

Full source: https://github.com/PatentsView/PatentsView-Code-Examples/blob/duckdb-csv-bug/data-downloads/1-joining-tables.ipynb

Doesn't work - keeps running for more than 10 minutes:

```python
import duckdb

ddb = duckdb.connect('./patentsview.ddb')
csv_read_in = ddb.read_csv('g_patent.tsv', header=True, quotechar='"', delimiter="\t", all_varchar=True)

csv_read_in.create('g_patent_from_csv')  # Issue is with the create statement
```

Works fine, runs in 4 seconds:

```python
import duckdb

ddb = duckdb.connect('./patentsview.ddb')

csv_read_in = ddb.read_csv('g_patent.tsv', header=True, quotechar='"', delimiter="\t", all_varchar=True)
csv_read_in.write_parquet("g_patent.parquet")

parquet_read_in = ddb.read_parquet("g_patent.parquet")
parquet_read_in.create('g_patent')
ddb.table('g_patent')
```

Environment (full environment.yml file at https://github.com/PatentsView/PatentsView-Code-Examples/blob/duckdb-csv-bug/environment.yml)
```
dependencies:
  - duckdb-cli=1.1
  - python=3.13
  - pip
  - pip:
    - jupyter==1.1.*
    - ipykernel==6.29.*
    - pandas==2.2.*
    - duckdb==1.1.*
    - fsspec==2024.10.*
```

### OS:

MacOS Sonoma 14.7

### DuckDB Version:

1.1.3

### DuckDB Client:

Python

### Hardware:

MacBook Pro M3 Max, 64Gb

### Full Name:

Olivier Binette

### Affiliation:

American Institutes for Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
This finished for me in under 10 sec on a similar MacBook so not sure what's going on there. Are you running this on Colab or so?

**Comment by OlivierBinette** [comment]
@hannes I tried it again running it locally on my MacBook, same behavior. I use conda to configure the environment:
```
conda env update
conda activate patentsview-code-examples
```
Then restart my jupyter kernel, make sure I have the right environment selected, and run try to run the notebook. I tried executing the notebook programmatically as well:
```
conda run -n pv-code-examples jupyter nbconvert --execute data-downloads/1-joining-tables.ipynb --to html
```

I'll experiment a bit more and keep you posted if I find duckdb or Python versions for which it works.

**Comment by OlivierBinette** [comment]
Script works fine when using ipython or python (same environment), still doesn't complete when executing vscode jupyter cell.

**Comment by OlivierBinette** [comment]
@hannes No problem when I run `ddb.execute('SET enable_progress_bar = false;')`. Seems like this is an issue with the progress bar or jupyter widgets.

**Comment by hannes** [comment]
Thanks for tracking this down to the progress bar!

**Comment by OlivierBinette** [comment]
@pdet No issue on duckdb-1.1.4.dev3666. Thank you, this is great!
