### ISSUE TITLE
Undocumented column name collisions in multi-column PIVOT

### ISSUE THREAD

**Issue by nickzoic** [duckdb/duckdb#15293]
### What happens?

OK, so I'm not sure this is even truly a bug, more just an annoying corner case.

The problem is: when pivoting on multiple columns, the new column names are made from joining the pivot values with '_', so pivot value `('foo', 'bar')` becomes column `foo_bar`.

So if you're pivoting a table on string columns whose values contain `_`, the new columns' names can be a bit confusing.
In the rather contrived case below, pivot values `('w', 'x_y_z')`, `('w_x', 'y_z')` and `('w_x_y', 'z')` all map to column `w_x_y_z`.

DuckDB does a sensible thing here, notices the collision and renames the columns to `w_x_y_z`, `w_x_y_z_1` and `w_x_y_z_2`, but this isn't documented anywhere I can find.

Possible solutions:
* Allow the `_` joiner to be changed, perhaps by a "set" variable?
* Do something to escape `_` in pivot values? 
* Document it as a weird and silly corner case, including what order the `_n` suffixes are applied in?

### To Reproduce

duckdb:
```
create table foo (a varchar, b varchar, z integer);
insert into foo values ('w', 'x_y_z', 1), ('w_x', 'y_z', 2), ('w_x_y', 'z', 4);
pivot foo on a, b using sum(z);
```

output:
```
┌─────────┬────────┬────────┬───────────┬───────────┬────────┬─────────────┬───────────┬───────────┐
│ w_x_y_z │ w_y_z  │  w_z   │ w_x_x_y_z │ w_x_y_z_1 │ w_x_z  │ w_x_y_x_y_z │ w_x_y_y_z │ w_x_y_z_2 │
│ int128  │ int128 │ int128 │  int128   │  int128   │ int128 │   int128    │  int128   │  int128   │
├─────────┼────────┼────────┼───────────┼───────────┼────────┼─────────────┼───────────┼───────────┤
│    1    │  NULL  │  NULL  │   NULL    │     2     │  NULL  │    NULL     │   NULL    │     4     │
└─────────┴────────┴────────┴───────────┴───────────┴────────┴─────────────┴───────────┴───────────┘
```

### OS:

Linux 6.8.0-49-generic x86_64

### DuckDB Version:

v1.1.4-dev3247 04d8f995da

### DuckDB Client:

CLI

### Full Name:

Nick Moore

### Affiliation:

Mnemote Pty Ltd

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
The collision avoidance is mentioned at https://duckdb.org/docs/sql/dialect/keywords_and_identifiers.html#deduplicating-identifiers but I agree it should maybe be in the proper docs too. Maybe it is. 

(Personally, I think it's one of the bigger foot guns in DuckDB and have asked for a way to opt out at https://github.com/duckdb/duckdb/issues/11520)

To choose your own separator, you can simply pivot on a new column that combines values however you like, e.g., 
```sql
pivot foo on a || '+' || b using sum(z)
```

 An example is in the docs at https://duckdb.org/docs/sql/statements/pivot.html#multiple-on-columns-and-on-expressions
