### ISSUE TITLE
Queries using `SAMPLE` with `PERCENT` from file-based tables sometimes result in no data

### ISSUE THREAD

**Issue by d33bs** [duckdb/duckdb#15302]
### What happens?

Thank so much for the awesome stuff with this project - keep quacking!

When using DuckDB's `SAMPLE` SQL syntax with `PERCENT` I've noticed it sometimes produces no results. While I expect the results to be non-deterministic due to the feature that `SAMPLE` provides, what I'm seeing is that it sometimes produces no results when using simple datasets. My understanding is that this stems from a cluster sample approach by default (I haven't tried this with bernoulli sampling). When I attempt to use `ROWS` as an option instead things seem to work as expected. I tested this with both CSV and Parquet readers within DuckDB, which both exhibit the same behavior.

Specifically, if we have a table with one column and 5 values, numbers 1-5, and we query that table using `SAMPLE 50 PERCENT` I'd expect there to always be 2-3 rows returned. Instead what I noticed is that sometimes the return includes 0 results.

### To Reproduce

Please see this Google Colab notebook for a reproducible example of what I noticed: https://colab.research.google.com/drive/1RtHICbmDg5SnYGXLA2NgATHGVothx8IF . I also made a GitHub Gist as a backup, in case this is more helpful: https://gist.github.com/d33bs/7d9dab111574dc4e270e1df4a74fd45b .

Note: the behavior is relatively inconsistent so I use a loop of 10 iterations for each file type to demonstrate what I noticed.

### OS:

Ubuntu 22.04.3 LTS

### DuckDB Version:

1.1.3

### DuckDB Client:

Python

### Full Name:

Dave Bunten

### Affiliation:

University of Colorado Anschutz Medical Campus

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by d33bs** [comment]
Thanks @szarnyasg ! This is more clear to me now. Perhaps a red warning near the top the sampling docs could help with this (something like `Please note: default sampling may result in no data being returned based on reservoir sampling (see more below)`).

I used `SAMPLE` through DuckDB from the lens of Pandas [`pd.DataFrame.sample()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html) which I think might use simple random sampling by default. I'd suggest that simple random sampling should be the default within DuckDB too, moving the existing default to an argument like `(bernoulli)`, e.g. `(reservoir)` (`USING SAMPLE 50 PERCENT (reservoir)`).

Is there a way to achieve simple random sampling by percentage today within DuckDB? Using `ROWS` seemed to work okay but might be a challenge to work with in cases where you don't know how large the dataset is.

**Comment by szarnyasg** [comment]
Hi @d33bs, Soeren updated the documentation to elaborate on the sampling methods. This should help clarify the common pitfalls and the differences between the sampling methods.
