### ISSUE TITLE
Hash Join performance issue

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#1531]
When running an LDBC SNB-like benchmark, DuckDB takes forever to run the following query on scale factor 1:
```
SELECT count(*)
FROM
  City AS CityA,
  City AS CityB,
  City AS CityC,
  Person AS personA,
  Person AS personB,
  Person AS personC,
  Person_knows_Person AS pkp1,
  Person_knows_Person AS pkp2,
  Person_knows_Person AS pkp3
WHERE CityB.isPartOf_Country = CityA.isPartOf_Country
  AND CityC.isPartOf_Country = CityA.isPartOf_Country
  AND personA.isLocatedIn_Place = CityA.id
  AND personB.isLocatedIn_Place = CityB.id
  AND personC.isLocatedIn_Place = CityC.id
  AND personA.id = pkp1.Person1Id
  AND personB.id = pkp2.Person1Id
  AND personC.id = pkp3.Person1Id
  AND pkp1.Person2Id = pkp2.Person1Id
  AND pkp2.Person2Id = pkp3.Person1Id
  AND pkp3.Person2Id = pkp1.Person1Id;
```
With City having 1343 rows, Person having 11000 rows, and Person_knows_Person having 452586 rows. While running, DuckDB takes up almost 400GB of memory. I built reldebug and halted execution after ~30 seconds, at which point it seemed stuck to be stuck on TemplatedGatherResult forever. This is the query plan:
![Screenshot from 2021-03-26 11-36-50](https://user-images.githubusercontent.com/14329666/112619476-abac5a00-8e27-11eb-97e6-b28b38ead2e8.png)

When trimming down the query, I found that the following also looped forever, also stuck on TemplatedGatherResult.
```
SELECT count(*)
FROM
  City AS CityA,
  City AS CityB,
  City AS CityC,
  Person AS personA,
  Person AS personB,
  Person AS personC
WHERE CityB.isPartOf_Country = CityA.isPartOf_Country
  AND CityC.isPartOf_Country = CityA.isPartOf_Country
  AND personA.isLocatedIn_Place = CityA.id
  AND personB.isLocatedIn_Place = CityB.id
  AND personC.isLocatedIn_Place = CityC.id;
```

Which has this query plan:
![Screenshot from 2021-03-26 11-39-05](https://user-images.githubusercontent.com/14329666/112619706-ec0bd800-8e27-11eb-8c94-968942d9577a.png)

The same query takes around 2 seconds on PostgreSQL on the same machine.

This benchmark is not yet released, but I can show it if you'd like.

**Comment by Mytherin** [comment]
It is hard to judge without the data, but it seems very likely this is down to a poor join order leading to an exploding intermediate, which then gets pushed into a subsequent hash table construction (leading to the exploding memory size). 

Could you perhaps check the join order used by Postgres, disable the DuckDB optimizer (`PRAGMA disable_optimizer`) and manually alter the query so DuckDB uses the same join order as Postgres? If that works as expected the issue seems unrelated to the hash join specifically, and more related to poor cardinality estimation (#75).

**Comment by lnkuiper** [comment]
I re-wrote the query as you suggested without optimizer:
```
SELECT count(*)
FROM
  Person AS personC
JOIN
  City AS CityC
ON
  personC.isLocatedIn_Place = CityC.id
JOIN
  Person_knows_Person AS pkp2
ON
  pkp2.Person2Id = PersonC.Id
JOIN
  (SELECT personB.id, CityB.isPartOf_Country FROM Person AS personB JOIN City AS CityB ON PersonB.isLocatedIn_Place = CityB.Id) bb
ON
  CityC.isPartOf_Country = bb.isPartOf_Country AND pkp2.Person1Id = bb.Id
JOIN
  (SELECT PersonA.Id, PersonA.isLocatedIn_Place, CityA.ispartof_country, pkp1.person2id FROM Person AS PersonA JOIN City AS CityA ON PersonA.isLocatedIn_Place = CityA.Id JOIN Person_knows_Person AS pkp1 ON pkp1.Person1Id = PersonA.id) aa
ON
  aa.ispartof_country = bb.ispartof_country AND aa.person2id = bb.id
JOIN
  person_knows_person as pkp3
ON
  (pkp3.person2id = aa.id) AND (pkp3.person1id = personc.id);
```
And got a runtime of 2 seconds, this is the plan:
![Screenshot from 2021-03-26 13-45-38](https://user-images.githubusercontent.com/14329666/112633398-99d3b280-8e39-11eb-94ad-4f53f1b6e8f6.png)

Adding more threads didn't help, but it's good to know it's a cardinality estimation issue.

**Comment by hannesmuehleisen** [comment]
I guess we need to work on cardinality estimation. Hint, hint, @lnkuiper :)

**Comment by arjenpdevries** [comment]
They say you need query re-optimization

**Comment by hannes** [comment]
Related to #75
