### ISSUE TITLE
View not created in default schema cannot be queried from other schema

### ISSUE THREAD

**Issue by Androidown** [duckdb/duckdb#15315]
### What happens?

If a view is not created in default schema and the relation name in view's definition is not qualified with its schema, the view cannot be queried in any other schema.

### To Reproduce

```sql
D create schema new;
D use new;
D CREATE TABLE t1 AS SELECT 42 AS i, 84 AS j;
D create view v as (select * from t1);
D select * from v;  -- ok
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘
D use main;
D select * from new.v;  -- error
Catalog Error: Table with name t1 does not exist!
Did you mean "new.t1"?
```

### OS:

x86_64

### DuckDB Version:

1.1.13

### DuckDB Client:

CLI

### Full Name:

Wei

### Affiliation:

Freelancer

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks, this is already fixed by <https://github.com/duckdb/duckdb/pull/13921>
