### ISSUE TITLE
Unable to query a table in an attached database using the query_table function.

### ISSUE THREAD

**Issue by AlexisVLRT** [duckdb/duckdb#15336]
### What happens?

Query fails with error: `Error: Catalog Error: Table with name attached_db.table does not exist!` when attempting to use query_table on an attached database.

### To Reproduce

In the duckdb shell:
```sql
ATTACH '/path/to/db2.duckdb' AS attached_db;
CREATE TABLE attached_db.test_table AS SELECT 1;
SELECT * FROM query_table('attached_db.table');
```

Output:
```shell
Catalog Error: Table with name attached_db.test_table does not exist!
Did you mean "pg_database"?
LINE 1: SELECT * FROM query_table('attached_db.test_...
```

### OS:

iOS 14.2.1 (23C71)

### DuckDB Version:

1.1.0

### DuckDB Client:

CLI

### Full Name:

Alexis VIALARET

### Affiliation:

Wild Apex

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by AlexisVLRT** [comment]
Some additionnal context : I'm trying to write a macro that uses data from tables in two different duckdb files. Ideally I would like the table names to be passed as parameters.

This works:
```sql
CREATE OR REPLACE MACRO dummy_macro(__table1, __table2) AS TABLE
    SELECT * FROM query_table(__table1)
    UNION ALL
    SELECT * FROM query_table(__table2);

CREATE TABLE table1 AS SELECT 1;
CREATE TABLE table2 AS SELECT 2;

SELECT * FROM dummy_macro('table1', 'table2');
```
```
┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
│     2 │
└───────┘
```
However this does not:
```sql
CREATE OR REPLACE MACRO dummy_macro(__table1, __table2) AS TABLE
    SELECT * FROM query_table(__table1)
    UNION ALL
    SELECT * FROM query_table(__table2);

CREATE TABLE table1 AS SELECT 1;
ATTACH '/path/to/second_db.duckdb' AS attached_db;
CREATE TABLE attached_db.table2 AS SELECT 2;

SELECT * FROM dummy_macro('table1', 'attached_db.table2');
```
```
Error: Catalog Error: Table with name attached_db.table2 does not exist! Did you mean "duckdb_databases"? LINE 1: SELECT * FROM dummy_macro('table1', 'attache... ^
```

I'm unsure if I'm missing something, making wrong assumptions, or maybe what I'm trying to do is just not possible with `query_table`.
If it's the latter, and the feature is something worth implementing in the maintainer's opinion, I'm happy to try and contribute.

**Comment by carlopi** [comment]
Not exactly 1-1, but this does work:
```
CREATE OR REPLACE MACRO dummy_macro(__table1, __table2) AS TABLE
      SELECT * FROM query('FROM '||__table1)
      UNION ALL
      SELECT * FROM query('FROM '||__table2);
SELECT * FROM dummy_macro('table1', 'attached_db.table2');
```
Here it's using query() that takes string and evaluates that as query.

`query_table` should also be able to handle this case basically in the same way, code is a somewhat limited function at  https://github.com/duckdb/duckdb/blob/main/src/function/table/query_function.cpp#L19 if anyone wants to have a go.

**Comment by Tishj** [comment]
Thanks, I'm pretty sure I fixed this on main a month or two ago 👍

**Comment by carlopi** [comment]
Then solved on main, and you got also a workaround.

Thanks for raising this!
