### ISSUE TITLE
length of lpad result off-by-one when padding a regexp_replace match variable 

### ISSUE THREAD

**Issue by malcook** [duckdb/duckdb#15345]
### What happens?

I beleive the value of pad1 and pad2 should be the same in this result, but they are not.

### To Reproduce

```sql
SELECT
    'A' || lpad('9', 2, '0') AS pad1,
    regexp_replace('A9', '(A)(\d+)', '\1' || lpad('\2', 2, '0')) AS pad2,
;
```
```
pad1,pad2
A09,A9
```

### OS:

linux

### DuckDB Version:

v1.1.0 fa5c2fe

### DuckDB Client:

duckdb CLI

### Full Name:

malcolm cook

### Affiliation:

self

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Not a bug. The `lpad('\2', 2, 0)` becomes `\2` because it's already two characters.

**Comment by szarnyasg** [comment]
@malcook thanks for opening this issue. As @soerenwolfers says, this is expected behavior. A possible workaround is to extract the subgroups of the regex match into an intermediate table, then run `lpad` on them.

**Comment by soerenwolfers** [comment]
```sql
SELECT
    input,
    regexp_extract(input, '^([^\d]+)(\d{1,2})$', ['letters', 'digits']) AS components,
    components['letters'] || lpad(components['digits'], 2, '0') padded
FROM (VALUES ('A9'), ('test19'), ('GA03'), ('ABC1')) _(input)
```
```text
SELECT
    input,
    regexp_extract(input, '^([^\d]+)(\d{1,2})$', ['letters', 'digits']) AS components,
    components['letters'] || lpad(components['digits'], 2, '0') padded
FROM (VALUES ('A9'), ('test19'), ('GA03'), ('ABC1')) _(input)
```

**Comment by malcook** [comment]
agreed - definitely not a bug -

definitely "operator error" ;)

thanks for the consideration and suggesting a working approach!
