### ISSUE TITLE
Syntax surprise: failure of dot syntax for function chaining

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#15348]
### What happens?

Is this a software bug or a symptom of inaccurate documentation?

### To Reproduce

``` 
create or replace function l() as [1,2];

create or replace function pp(lst) as table (select unnest(lst));

-- Good to go:
from pp(l());

-- Whoops:
from l().pp();
```

### OS:

macos

### DuckDB Version:

 v1.1.4-dev3570 et al

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @pkoppstein, thanks for opening this issue. At the moment, this is an expected limitation. We'll improve the documentation to include this.
