### ISSUE TITLE
scalar function returns binder error for `select f(n) from ...`

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#15350]
### What happens?

The following snippet shows that f(1) is calculated properly but then produces
```
Binder Error:
Referenced column "s" not found in FROM clause!
Candidate bindings: "n"
```

### To Reproduce

```
create or replace function f(number) as (
  with cte as (select 
         trim(number::VARCHAR) as s,
         length(s) as nn,
         'x' as x)
  select x
  from cte
  limit 1
);

select f(1);

select f(n)
from (select 1 as n);
```

### OS:

MacOS

### DuckDB Version:

 v1.1.4-dev3570

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This is indeed a bug / limitation. Several of these limitations may go away when we'll offer a new PEG-based parser but that will take a while to be rolled out.

**Comment by pkoppstein** [comment]
@szarnyasg - Thanks for the explanation about the bug/limitation.  I was, however, disappointed that the ticket was "closed as completed" without a link to an active "Issue" or PR or indication that the documentation has been updated.  This kind of bug/limitation is very serious and can be time-consuming to diagnose, so other users ought to be easily able to find the relevant information.  Since it seems the resolution may be some time in coming,  would an update to the documentation be appropriate?
