### ISSUE TITLE
PostgreSQL incompatibility: Should regexp functions return NULLs when there are no matches?

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#15351]
### What happens?

The `regexp_extract\w+` functions all return empty strings when the specified pattern is not contained in the specified string.

I believe it'd be more user friendly if they threw or returned `NULL`, the latter of which the PostgreSQL's `regexp_substr` function and `substring` operator do.

If the current behavior is intended, I'll add it to the docs and the PostgreSQL incompatibility page (despite the slight naming difference between PG and DuckDB).

### To Reproduce

The following snippet returns two empty strings in DuckDB:

```sql
.nullvalue NULL
SELECT
    regexp_extract('a', '\d+'),
    regexp_extract('a', '\d*');
```
```console
┌────────────────────────────┬────────────────────────────┐
│ regexp_extract('a', '\d+') │ regexp_extract('a', '\d*') │
│          varchar           │          varchar           │
├────────────────────────────┼────────────────────────────┤
│                            │                            │
└────────────────────────────┴────────────────────────────┘
```

whereas the following snippet returns a `NULL` and an empty string in PostgreSQL:

```sql
\pset null null
SELECT
    regexp_substr('a', '\d+'),
    regexp_substr('a', '\d*');
```

```console
 regexp_substr | regexp_substr
---------------+---------------
 null          |
(1 row)
```

### OS:

Linux

### DuckDB Version:

1.1.3

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @soerenwolfers, we discussed this yesterday internally. Indeed it is a Postgres incompatibility but for now we opted to fix it from the documentation's side.

**Comment by soerenwolfers** [comment]
Okay, I'll make the doc PR (under protest ;)).

**Comment by NickCrews** [comment]
I just encountered this in https://github.com/ibis-project/ibis/issues/10950

@szarnyasg can you clarify if
1. The current behavior is as intended, or...
2. Ideally duckdb followed postgres's behavior, and the documentation PR above is just a workaround. If someone wanted to contribute a PR that actually adjusted behavior, then duckdb maintainers would appreciate it.

Thanks!
