### ISSUE TITLE
support cast STRUCTs of different sizes when union_by_name is set to true

### ISSUE THREAD

**Issue by tanejagagan** [duckdb/duckdb#15375]
### What happens?

Since union_by_name support parquet files with different number of fields supporting different length struct should also be supported

### To Reproduce

```sql
copy ( select {'i' : 2 } as s ) TO '1.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);

copy ( select {'i' : 3, 'j' : 99 } as s ) TO '2.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);

select * from read_parquet(['1.parquet', '2.parquet'], union_by_name = True);
```
```console
Mismatch Type Error: Type STRUCT(i INTEGER, j INTEGER) does not match with STRUCT(i INTEGER). Cannot cast STRUCTs of different size
```

### OS:

All

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

command line

### Full Name:

Gagan Taneja

### Affiliation:

dazzleduck

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, unfortunately, merging structs of different sizes together is not supported by the `union_by_name` flag. A potential workaround is to read these files separately and repack the structs to a shared schema.

**Comment by tanejagagan** [comment]
I understand this is not currently supported by duckdb but similar functionality is supported by iceberg and other engines.
The issue can be treated as enhancement request.
We are in the process of identifying our query engine for production use cases between polars and duckdb and this would be major blocker since data is accumulated over last several years and schema evolution is something we expect to work fine seamlessly

**Comment by bavaria95** [comment]
I had a similar issue and it appears this patch fixed it: https://github.com/duckdb/duckdb/pull/15477
