### ISSUE TITLE
provide ability to specify schema while reading parquet

### ISSUE THREAD

**Issue by tanejagagan** [duckdb/duckdb#15380]
### What happens?

(Followup of #15375)

This is an enhancement request as we are evaluating DuckDB to replace existing engine in production.  
In my environment Terabytes of data is stored in partitioned parquet files and we analyze the dataset partition by partition. 
However some of the partitions are old and do not have few columns as those columns were added later.
While running sql on those old partitions even when  `union_by_name = true` we run into error
```
Binder Error: Referenced column "a" not found in FROM clause!
Candidate bindings: "read_parquet.s"
LINE 1: select a from read_parquet('2.parquet') ;
```
Other engine such as spark let you specify the schema in the query itself so that they can be replaced with `null` even though those columns are not present in any of those files.
By providing the ability to specify the schema the performance penalty of `union_by_name` parameter can also be avoided since schema resolution is not required.

### To Reproduce

```sql
copy ( select {'i' : 3, 'j' : 99 } as s ) TO '2.parquet' (FORMAT 'parquet', COMPRESSION 'zstd', ROW_GROUP_SIZE 100_000);
select a from read_parquet('2.parquet') ;
```

### OS:

All

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

command line

### Full Name:

Gagan Taneja

### Affiliation:

self 

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
This exists, but it works on field_ids in the parquet file:
<https://github.com/duckdb/duckdb/pull/9123>

**Comment by hannes** [comment]
This can already be done by (ab) using `UNION ALL BY NAME` like so:
Say we have `f.parquet` with two columns, `c1` and `c2`

```SQL
COPY (FROM (VALUES (42, 43)) t(c1, c2)) TO 'f.parquet';
```
And now we want to add another column `c3` if its not present in the file, we can 
```SQL
FROM (VALUES(NULL, NULL, NULL)) t(c1, c2, c3) WHERE false 
UNION ALL BY NAME
FROM  'f.parquet';
```
The first `FROM` here generates an empty tables with *three* columns, then we use `UNION ALL BY NAME` to union the parquet file. The result here is

```
┌───────┬───────┬───────┐
│  c1   │  c2   │  c3   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│    42 │    43 │  NULL │
└───────┴───────┴───────┘
```

as expected. This also works for casting, say we want `c1` to be turned into a string, but it's an `INTEGER` in the Parquet file:

```SQL
FROM (VALUES(NULL::VARCHAR, NULL, NULL)) t(c1, c2, c3) WHERE false 
UNION ALL BY NAME
FROM  'f.parquet';
```

results in 

```
┌─────────┬───────┬───────┐
│   c1    │  c2   │  c3   │
│ varchar │ int32 │ int32 │
├─────────┼───────┼───────┤
│ 42      │    43 │  NULL │
└─────────┴───────┴───────┘
```

Otherwise the column ID trick like @Tishj has described would also work

**Comment by tanejagagan** [comment]
Thanks Tishj and Hannes for  the help. This is very useful solution

**Comment by tanejagagan** [comment]
Any such workaround for this issue with struct of different length
https://github.com/duckdb/duckdb/issues/15375

**Comment by hannes** [comment]
I think this was discussed in the other issue. Closing here. Feel free to reach out to hannes@duckdblabs.com if you're interested in commercial support.
