### ISSUE TITLE
Define temp directory at runtime from Python

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#1538]
Hi Folks!

We are using DuckDB in a multithreaded environment, and we are running into a need to select a temporary folder (currently .tmp) at runtime. This would allow us to ensure that we use a temporary directory that will not conflict with any other threads, as well as make sure that it is in a location where our users have permission to access it. We are using the Python client, so we would like to be able to modify this from Python for each new connection (possibly a PRAGMA would be a good fit?). Python does not appear to allow a separate working directory per thread (only per process), so we can't manipulate the overall working directory. 

Ideally, we would like to be able to specify this separately from the path of the database since we would like to continue using the special ':memory:' keyword for in-memory performance. Our current workaround is to create a file-based DuckDB that we put in a thread-specific folder, but we would prefer to use the in memory option if possible.

Thanks!
-Alex

**Comment by hannesmuehleisen** [comment]
Yeah we should export more of the `DBConfig` settings to Python. I think we should pass a DBConfig object to connect that can take settings parameters in its constructor. This simplifies adding more flags in the future.

**Comment by Mytherin** [comment]
This has been implemented as part of #1808. You can now run `PRAGMA temp_directory='/path/to/my/dir'` to set the temporary directory at run-time (even for in-memory databases).

Feel free to re-open if there are more issues relating to this.
