### ISSUE TITLE
PRIMARY KEY AUTOINCREMENT is not supported

### ISSUE THREAD

**Issue by yaochao05** [duckdb/duckdb#15436]
### What happens?

```sql
CREATE TABLE my_table (
    id INTEGER PRIMARY KEY,  -- 自增字段
    name TEXT,
    age INTEGER
);
INSERT INTO my_table (name, age) VALUES ('Alice', 30), ('Bob', 25);
```

result:

```console
SQL 错误: Constraint Error: NOT NULL constraint failed: my_table.id
```

### To Reproduce

```sql
CREATE TABLE my_table (
    id INTEGER PRIMARY KEY,  -- 自增字段
    name TEXT,
    age INTEGER
);
INSERT INTO my_table (name, age) VALUES ('Alice', 30), ('Bob', 25);
```

### OS:

x86_64

### DuckDB Version:

1.1.3

### DuckDB Client:

dbeaver 24.3.0

### Full Name:

tester007

### Affiliation:

toweryao@gmail.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Reason for error message, including examples, explained at https://duckdb.org/docs/sql/constraints.html#primary-key-and-unique-constraint

Auto incrementing index sequence, including example, explained at https://duckdb.org/docs/sql/statements/create_sequence.html#using-sequences-for-primary-keys

**Comment by szarnyasg** [comment]
@yaochao05, DuckDB and PostgreSQL do not auto increment primary keys and do not support the `AUTO_INCREMENT` modifier (as supported by e.g. MySQL).

As @soerenwolfers pointed out, auto incrementing can be achieved [using a sequence](https://duckdb.org/docs/sql/statements/create_sequence.html#using-sequences-for-primary-keys), which is the recommended approach for this use case.
