### ISSUE TITLE
Memory usage grows monotonically when COPYing into table with primary key

### ISSUE THREAD

**Issue by frankier** [duckdb/duckdb#1546]
Running the following against duckdb master, memory usage grows continually, and is >10x database size.

```
#!/usr/bin/python3

import sys
import duckdb

dbout = sys.argv[1]
conn = duckdb.connect(dbout)
print("Creating tables", flush=True)
conn.execute("PRAGMA memory_limit='4GB'; ")
conn.execute(
    """
create table table (
    ID int primary key
);
"""
)

for start in range(0, 1000000000, 1000000):
    with open("/tmp/pks.csv", "w") as outf:
        for idx in range(start, start + 1000000):
            outf.write(str(idx))
            outf.write("\n")
    print("Inserting starting from", start)
    conn.execute("COPY table FROM '/tmp/pks.csv';")
```

At about "Inserting starting from 30000000" memory usage is ~8GiB on my machine.

The memory limit doesn't seem to do anything, and checkpointing or closing and reopening the connection doesn't seem to do much either. I guess the indices for primary keys are always being constructed in memory. I suppose there should be some guidance that these type of indices should be constructed after bulk insertion.

**Comment by Mytherin** [comment]
Indeed if your schema has indexes that is likely the culprit. Indexes are not buffer managed right now, which means they ignore any memory limit you set. They are also not persisted on disk yet, which means that indexes need to be rebuilt whenever you reload the database from disk. These two issues are related, as both relate to modifying the index so it can use disk-based blocks to offload data to disk (either for persistence or for memory-saving purposes).

**Comment by hannes** [comment]
Indexes are buffer managed now

**Comment by besquared** [comment]
I tested this against main v0.5.2-dev582 dfd82a3d4 and creating and dropping indexes has no impact on the `memory_usage` of `pragma database_size`. Is this functionality in a branch somewhere?
