### ISSUE TITLE
Histogram function returns error on Python API

### ISSUE THREAD

**Issue by Manerone** [duckdb/duckdb#1548]
The following code:
```python
def histogram(con, table, column, bins):
    sql_code = f"""
        SELECT histogram({column}) FROM {table}
    """
    con.execute(sql_code)
    return con.fetchall()
```

Returns the following error:
`RuntimeError: unsupported type: LIST<STRUCT<bucket: INTEGER, count: UBIGINT>>`

**Comment by Mytherin** [comment]
Lists are not supported in the Python client right now. As a work-around you could convert the result to a string before moving it to Python land, e.g.:

```sql
SELECT histogram({column})::STRING FROM {table}
```

**Comment by hannesmuehleisen** [comment]
We should probably work on being able to return lists in the client APIs at some point

**Comment by Manerone** [comment]
I will give it a shot, might be able to fix this at least for the Python API.
Pointers on where to begin would be appreciated, but not necessary if there is no time for that.

**Comment by Mytherin** [comment]
@pdet perhaps you would be interested in working on this together with @Manerone , as you are working on the Python API and have also recently worked on the lists.

**Comment by pdet** [comment]
I'm happy to help, @Manerone  I can show you the ropes if you want.
I'm implementing a map type, although conceptually is just a struct of lists. 
The histogram function is already using it [map-branch](https://github.com/pdet/duckdb/tree/map).

**Comment by Manerone** [comment]
I tried building DuckDB using the following command:
`BUILD_PYTHON=1 BUILD_FTS=1 make debug`
However when I call `import duckdb` on Python I get:
```
Traceback (most recent call last):
  File "/Users/matheusan/Workspace/duckdb/bug.py", line 1, in <module>
    import duckdb
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/duckdb-0.2.6.dev548+g59de07a92-py3.9-macosx-11-x86_64.egg/duckdb.cpython-39-darwin.so, 2): Symbol not found: __ZN6duckdb16utf8proc_iterateEPKhlPi
  Referenced from: /usr/local/lib/python3.9/site-packages/duckdb-0.2.6.dev548+g59de07a92-py3.9-macosx-11-x86_64.egg/duckdb.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/duckdb-0.2.6.dev548+g59de07a92-py3.9-macosx-11-x86_64.egg/duckdb.cpython-39-darwin.so
```

I am still trying to find a solution, but maybe this happened before to someone.
I also tried using virtualenv to isolate the package installation but the same thing happened.
