### ISSUE TITLE
Unexpected decimal rounding

### ISSUE THREAD

**Issue by magneto-81** [duckdb/duckdb#15492]
### What happens?

Using version 1.1.3 I execute the following statement:
```
SELECT
                4.625 AS a,
                4.625::decimal(38,6) AS b,
                004.625 AS c,
                0004.625 AS d,              
                a::decimal(6,2) AS a_1,
                b::decimal(6,2) AS b_1, -- BUG! Unexpected 4.62 (4.63 is correct)
                c::decimal(6,2) AS c_1,
                d::decimal(6,2) AS d_1, -- BUG! Unexpected 4.62 (4.63 is correct, start from decimal (7,3) or major)
                b::decimal(6,3)::decimal(6,2) AS w_1; -- work around (double cast)
```
This is a simplified scenario, it took me several days to understand this rounding problem in my more complex scenario.

### To Reproduce

```
SELECT
                4.625 AS a,
                4.625::decimal(38,6) AS b,
                004.625 AS c,
                0004.625 AS d,              
                a::decimal(6,2) AS a_1,
                b::decimal(6,2) AS b_1, -- BUG! Unexpected 4.63 (4.62 is correct)
                c::decimal(6,2) AS c_1,
                d::decimal(6,2) AS d_1, -- BUG! Unexpected 4.63 (4.62 is correct, start from decimal (7,3) or major)
                b::decimal(6,3)::decimal(6,2) AS w_1; -- work around (double cast)
```

### OS:

Windows 11 64-bit operating system

### DuckDB Version:

1.1.3

### DuckDB Client:

Cli

### Full Name:

Francesco Gargiulo

### Affiliation:

Irion

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
Previously reported in https://github.com/duckdb/duckdb/issues/11557 and fixed via https://github.com/duckdb/duckdb/pull/14860 in nightly.

**Comment by szarnyasg** [comment]
Hi @magneto-81, as @soerenwolfers pointed out, this is indeed fixed in the latest nightly build:

```console
v1.1.4-dev3836 ec7be6f00e
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .mode line
D SELECT
                  4.625 AS a,
                  4.625::decimal(38,6) AS b,
                  004.625 AS c,
                  0004.625 AS d,
                  a::decimal(6,2) AS a_1,
                  b::decimal(6,2) AS b_1, -- BUG! Unexpected 4.62 (4.63 is correct)
                  c::decimal(6,2) AS c_1,
                  d::decimal(6,2) AS d_1, -- BUG! Unexpected 4.62 (4.63 is correct, start from decimal (7,3) or major)
                  b::decimal(6,3)::decimal(6,2) AS w_1; -- work around (double cast)
    a = 4.625
    b = 4.625000
    c = 4.625
    d = 4.625
  a_1 = 4.63
  b_1 = 4.63
  c_1 = 4.63
  d_1 = 4.63
  w_1 = 4.63
```
