### ISSUE TITLE
Set default schema that is used at runtime

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#155]
e.g.
```sql
CREATE SCHEMA s1;
SET default_schema TO s1;
```

**Comment by swayamraina** [comment]
Hi @Mytherin,

can you please guide about the changes. Will be happy to pick this up.

**Comment by Mytherin** [comment]
Thanks for the offer :)

Apologies for the late reply, I have been a bit busy. Here are the changes required as I see them:

What needs to happen for this change is that anytime the DEFAULT_SCHEMA is bound, we instead use the default schema that is specified by the user. The default schema is client-dependent, and should reset every session, so we can store this in the `ClientContext` as a simple string. It should have the default `DEFAULT_SCHEMA` as default value (which is "main" currently).

We then need to support actually changing this variable. An easy way of doing that for now would be through the `PRAGMA` statement, e.g. `PRAGMA default_schema='s1'`. This case should be handled in `physical_pragma.cpp`.

The variable then needs to be used in the actual binding. This all happens in `catalog.cpp`. Anytime we encounter `DEFAULT_SCHEMA` there, we need to switch this to use the variable located in the client context. Note that we should also do this for create statements. For example, if you do `CREATE TABLE integers(i INTEGER);`, the actual table created should be in the default schema.

I believe those are all the changes required, at least as I see it right now.

**Comment by jtommaney-alibaba** [comment]
This is a highly useful feature.  Syntax variants include:

postgres flavors-
set schema 'schema_name';
set search_path to 'schema_name';

mysql flavor-
use 'schema_name';
