### ISSUE TITLE
SelectionVector::get_index should handle sel_vector == nullptr

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1558]
I was wondering whether we should change `SelectionVector::get_index` to pass through when `sel_vector` is `nullptr`.  This would make `FlatVector::INCREMENTAL_SELECTION_VECTOR` obsolete and solve corner cases like [this one](https://github.com/cwida/duckdb/blob/a4340e84db5c36123e8bff4bb7dc4c05dc333c93/src/common/vector_operations/vector_copy.cpp#L213). This could also lead to some efficiencies if the loop tested for this condition and was able to perform more efficient batch operations like appending list or string dictionaries instead of extracting from them.

The only issue I can see is that it would add a test to every selection vector access, but in this century, the processor branch predictor should make that a non-issue. And if the `SelectionVector` was `const`, some compilers might promote the test out of the loop and effectively create two loops.

I was also a bit concerned by the `SelectionVector(idx_t start, idx_t count)` method, which doesn't check that `count <= STANDARD_VECTOR_SIZE` or pass that into `Initialize`.

**Comment by hawkfish** [comment]
Making this change seems to make `make allunit` run 6-7s faster on my iMac Pro.  Do we have a more scientific test I could run?

**Comment by Mytherin** [comment]
Selection vectors are used all over the place; the list case where vectors are longer than the vector size is more of an edge case. I would hesitate to optimize only for that edge case. However, if the change is positive in other areas we could of course consider it.

Perhaps you could run TPC-H using the benchmark_runner (`BUILD_BENCHMARK=1 make opt && build/release/benchmark/benchmark_runner .*/sf.*/.*`) and see what the effects are there as a starting point?

**Comment by hawkfish** [comment]
```
------------------
|| Q01_PARALLEL ||
------------------
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Extension tpch is not available/was not compiled. Cannot run this benchmark.
zsh: abort      build/release/benchmark/benchmark_runner ".*/sf.*/.*"
```shell

**Comment by Mytherin** [comment]
Whoops, needs `BUILD_TPCH=1` as well

**Comment by hawkfish** [comment]
Thanks -I just found that!

**Comment by hawkfish** [comment]
Looks [about the same](https://public.tableau.com/views/DuckDBIssue1558/Issue1558?:language=en-GB&:display_count=y&publish=yes&:origin=viz_share_link) really.

**Comment by hawkfish** [comment]
One other advantage is that we can lose the large, prebuilt indexing arrays.
