### ISSUE TITLE
Implement ARRAY_SLICE

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1560]
It looks like the expression binder binds slice notation to a function called `array_slice`, which has not been implemented.

**Comment by Mytherin** [comment]
For strings, array_slice should be an alias for `substring`.

**Comment by hawkfish** [comment]
I meant for `LIST`s but it doesn't seem to be implemented for anything:

```
hawkfish@Richards-MacBook-Pro duckdb % git grep -i array_slice
src/common/enums/expression_type.cpp:   case ExpressionType::ARRAY_SLICE:
src/common/enums/expression_type.cpp:           return "ARRAY_SLICE";
src/include/duckdb/common/enums/expression_type.hpp:    ARRAY_SLICE = 154,
src/parser/transform/expression/transform_array_access.cpp:                             result = make_unique<OperatorExpression>(ExpressionType::ARRAY_SLICE, move(children));
src/planner/binder/expression/bind_operator_expression.cpp:     case ExpressionType::ARRAY_SLICE:
src/planner/binder/expression/bind_operator_expression.cpp:             function_name = "array_slice";
```sh

**Comment by Mytherin** [comment]
I understand, I was just adding a note that for strings this should also work so we can use the slicing syntax (e.g. x[1:3]) for strings as well. array_slice was added as a stub function and indeed doesn't exist yet.

**Comment by hawkfish** [comment]
It's not quite the same - the `NULL` semantics are different and `substring` takes positive position and length instead of signed `begin:end` pairs.
