### ISSUE TITLE
Test "Use sequences over different runs without checkpointing" succeeds, but with a runtime error

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#1567]
Ran into this when running `make unit`. The test file in question is: sql/storage/catalog/test_storage_sequences.cpp

Run the test with `./build/debug/test/unittest "Use sequences over different runs without checkpointing"` The test succeeds, but a runtime error is thrown:
```
../../src/include/duckdb/main/query_profiler.hpp:97:7: runtime error: load of value 190, which is not a valid value for type 'bool'
```

**Comment by hannes** [comment]
This should be fixed by now
