### ISSUE TITLE
Boolean Parquet column showing wrong result after `ORDER`

### ISSUE THREAD

**Issue by rostislavdeepcrawl** [duckdb/duckdb#1578]
Following https://github.com/duckdb/duckdb/issues/1554 as advised I tested the latest  duckdb version (6c7c9805fdf1604039ebed47d233ea55cabb4b2c). And I found another bug that also has to do with an incorrect result being returned:

```
SELECT rownum, is_self_canonical FROM parquet_scan('myparquetfile') ORDER BY id LIMIT 1
```
Returns `true` as the second value. It should be `false`. Interestingly,
```
SELECT rownum, is_self_canonical FROM parquet_scan('myparquetfile') WHERE rownum = 87309
```
Returns `false` as it should. 
Duckdb version 0.2.2 returns `false` for the former query.

I will send the parquet file.

**Comment by hannesmuehleisen** [comment]
Confirmed, that's a bug.

**Comment by hannesmuehleisen** [comment]
Should be fixed in the PR. Thanks for reporting.

**Comment by rostislavdeepcrawl** [comment]
thanks!
