### ISSUE TITLE
Unable to disconnect from a database in R: `file used by another process`

### ISSUE THREAD

**Issue by matteodefelice** [duckdb/duckdb#1582]
I am using DuckDB with the R API (Windows 10, latest DuckDB release)
When I connect to a db with:
```
con <- DBI::dbConnect(duckdb(), 'test.db')
```
and disconnect with:
```
DBI::dbDisconnect(con)
```
Then if I try to delete the database file or move it I get:
```
The process cannot access the file because it is being used by another process.
```
This lock disappears if I close or restart the R session.

**Comment by hannesmuehleisen** [comment]
Try: `DBI::dbDisconnect(con, shutdown=TRUE)`

**Comment by matteodefelice** [comment]
Yes, it works, thanks!
