### ISSUE TITLE
Feature request: nextafter() in SQL

### ISSUE THREAD

**Issue by drstmane** [duckdb/duckdb#1584]
**Is your feature request related to a problem? Please describe.**
Given a floating point value range (say, between min(C) and max(C) value of a column C), the IMHO easiest(?) way to divide that range into N ranges/partitions/clusters of equal width (e.g., to calculate an equi-width histogram with N bins) and easily determine the range/partition/cluster P(V) each value V belongs to, requires using C(99?) math library function nextafter[f]() (or C++(11?) std::nextafter()) to get a tight exclusive upper bound as follows: calculate width of each range/partition/cluster as W=(nextafter(max(C))-min(C))/N , then determine range/partition/cluster of value V as P(V) = floor((V-min(C))/W).
Doing so in SQL requires C/C++ function nextafter() to be made available in SQL.

**Describe the solution you'd like**
Please expose C/C++ function nextafter() (for floating point types) in SQL.

**Describe alternatives you've considered**
None.

**Additional context**
For convenience of (canonical) use, one could consider also adding nextafter() for integer and decimal types:
for integer, it would boil down to a simple +1 (or -1); for decimal type decimal(x,y) it would be a + (or -) 10^(-y).

Thanks!
Best,
Stefan

**Comment by hannesmuehleisen** [comment]
Should be quite straightforward implementing the SQL function `NEXTAFTER` for `double` and `float`. For example, `SinFun::RegisterFunction` in `numeric.cpp` is a good template. Do you want to have a go at it? Happy to review a PR.

**Comment by hannesmuehleisen** [comment]
Curious to see https://github.com/MonetDB/MonetDB/issues/7101

**Comment by pdet** [comment]
@drstmane if I'm correct you only needed the float/double exposition of c functions right?
I've done that for you (#1862), but if you need it for the other data types let me know, and I can spend a few more minutes doing those as well :-)

**Comment by hannesmuehleisen** [comment]
This has been implemented by @pdet
