### ISSUE TITLE
LIST_EXTRACT alias [] Parser Error

### ISSUE THREAD

**Issue by tobymao** [duckdb/duckdb#1590]
import duckdb
conn = duckdb.connect()

conn.execute("SELECT LIST_VALUE(0, 1, 2)[0]").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Parser Error: syntax error at or near "["
LINE 1: SELECT LIST_VALUE(0, 1, 2)[0]

**Comment by Mytherin** [comment]
This query works correctly in the master branch. The bracket operator ([]) has been reworked recently, so it might not work in older versions of DuckDB.

**Comment by hannesmuehleisen** [comment]
This is supported in the latest pre-release. Try updating duckdb with `pip install duckdb --upgrade --pre`

**Comment by tobymao** [comment]
thanks
