### ISSUE TITLE
Scan ZIP files

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#1591]
We should extend file reading/globbing to ZIP file entries.

**Comment by hannesmuehleisen** [comment]
I seem to recall to have stripped the ZIP file functionality from the vendored miniz at the time. But should be straightforward to put it back.

**Comment by ankoh** [comment]
Summarizing the discussion today for later:

The only real hurdle is finding the offset of the central dictionary in the back of the ZIP file without loading it fully into memory.
The smallest diff would probably be to just call [mz_zip_reader_locate_header_sig](https://github.com/duckdb/duckdb/blob/bce2db2ba91d3c1964dff2f0ccc8104298f33302/third_party/miniz/miniz.cpp#L3426) directly and provide an own pRead function that proxies duckdb filesystem reads.

The matching files themselves can already be read in a streaming manner with [mz_zip_reader_extract_iter_read](https://github.com/duckdb/duckdb/blob/bce2db2ba91d3c1964dff2f0ccc8104298f33302/third_party/miniz/miniz.cpp#L4843).

**Comment by hannes** [comment]
Not now

**Comment by Maxxen** [comment]
@isaacbrodsky Cool! I started working on a zipfs around the time I made tar-fs, but shelved it as I got annoyed at handling globbing properly, and shifting priorities. Glad to see the idea come to life in another form!

**Comment by Maxxen** [comment]
Found it hiding in my stash, not sure if there's anything useful there, it seems mostly forked off tar-fs as well
https://github.com/duckdb/duckdb/compare/main...Maxxen:duckdb:zipvfs-proto
