### ISSUE TITLE
PhysicalOrder::MaxThreadCount doesn't check sink_state

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1592]
I ran into this while debugging `PhysicalWindow` and found that the CTE code can call `MaxThreadCount` before `Finalize` (the game of life test triggered this), which would mean that `sink_state` is `null`. I handled it by working off the `estimated_cardinality`, but I'm not sure how the logic works there.

**Comment by hannesmuehleisen** [comment]
Maybe @lnkuiper  can have a look?

**Comment by lnkuiper** [comment]
I was wondering when this was the case when I implemented parallel reads from an ordered result, but when all the tests came through I thought it was fine.

Good catch. Using the estimated cardinality is a good workaround
