### ISSUE TITLE
Implement "previousval" for sequences

### ISSUE THREAD

**Issue by travis-leith** [duckdb/duckdb#1598]
The only [scalar function for sequences](https://github.com/duckdb/duckdb/tree/6c7c9805fdf1604039ebed47d233ea55cabb4b2c/src/function/scalar/sequence) currently is nextval. How about getting the previously issued value?

This would be useful in cases where I insert a new entity into a master table, and then want the auto increment id for inserting stuff into a related tabled.

For example, a new sensor is added with a bunch of readings. I want to insert a master record for the sensor, get the ID, then create records for the readings associated with that sensor.

**Comment by travis-leith** [comment]
Consider this pattern: https://github.com/duckdb/duckdb/issues/1308 for generating the ids. How can I get the ids back efficiently?

**Comment by Mytherin** [comment]
`nextval` is copied from the [Postgres sequence implementation](https://www.postgresql.org/docs/9.1/functions-sequence.html). I think it would make a lot of sense to implement the same interface (at least `currval` and `setval`, not so sure about `lastval`). Happy to review a PR on this if you are interested in working on this.

**Comment by travis-leith** [comment]
That might just be the worst PR you will ever review :stuck_out_tongue_winking_eye:

**Comment by travis-leith** [comment]
@Mytherin I have a [working version](https://github.com/travis-leith/duckdb) of this for `currval`. 

I want to add some tests, but I have no idea to run the tests.
I am using cmake on Windows and Visual Studio 2019.
I build the project using `cmake -S . -B build`, I then open the resulting sln file in VS2019 and build it there to get an exe, which I can use to manually run some tests.
At what part of this workflow can I run the tests mentioned [here](https://github.com/travis-leith/duckdb/blob/master/CONTRIBUTING.md#testing)?
