### ISSUE TITLE
Update + Transactions raises RuntimeError: Not implemented Error: operator

### ISSUE THREAD

**Issue by Manerone** [duckdb/duckdb#1599]
Hello,
The following code:
```Python
import duckdb

c = duckdb.connect()

c.execute(f"""
    start transaction;
    CREATE TABLE t1 (i INTEGER, j INTEGER);
    CREATE TABLE t2 (i INTEGER, j INTEGER, id INTEGER);

    INSERT INTO t1 VALUES (0, 0);
    INSERT INTO t1 VALUES (1, 1);
    INSERT INTO t1 VALUES (2, 2);


    INSERT INTO t2 VALUES (0, 0, 0);
    INSERT INTO t2 VALUES (1, 1, 1);
    INSERT INTO t2 VALUES (2, 2, 2);

    ALTER TABLE t1 ADD COLUMN ref INTEGER;
    UPDATE "t1" SET "ref" = (
        SELECT "id"
        FROM "t2"
        WHERE "t2"."i" == "t1"."i" AND "t2"."j" == "t1"."j"
    );
    commit;
""")
```
Raises the following error:
`RuntimeError: Not implemented Error: operator`

However, it works fine without using a transaction.

I don't know if it is a known issue or not, but here it is :)

**Comment by hannesmuehleisen** [comment]
This fails in `execute_operator.cpp:83`, Expression in question is `IS_NOT_NULL(i, j)`.

**Comment by Mytherin** [comment]
Thanks for the report, I will have a look.

**Comment by hannesmuehleisen** [comment]
Should be fixed, please confirm

**Comment by Manerone** [comment]
> Should be fixed, please confirm

Worked for me on my local git clone of DuckDB.
Thanks for the very quick fix! :)
