### ISSUE TITLE
INSERT INTO/DELETE/etc... should also support CTEs

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#160]

**Comment by jwills** [comment]
Hey @Mytherin, I'm hitting a variant of this problem with `CREATE VIEW` statements (dbt thing where I need them to support CTEs as well)-- is this something I can knock out? I'm winding my way through the code on `QueryNode` vs. `SelectStatement` but I wanted to see if there were any dragons I should watch out for.

**Comment by Mytherin** [comment]
I can't immediately see any reasons why this would be particularly difficult, as you seem to have found out already :) This is just something we haven't gotten to yet.

**Comment by aryann** [comment]
It looks like CTEs are now supported in "insert into", "delete", and "create view" statements, so this issue can be closed.

```
D create table my_table(c int);
D select * from my_table;
D insert into my_table with my_cte as (select 1) select * from my_cte;
D select * from my_table;
┌───┐
│ c │
├───┤
│ 1 │
└───┘

D create view my_view as with my_cte as (select c + 1 from my_table) select * from my_cte;
D select * from my_view;
┌───────┐
│ c + 1 │
├───────┤
│ 2     │
└───────┘

D delete from my_table where 42 = (with my_cte as (select 42) select * from my_cte);
D select count(*) from my_table;
┌──────────────┐
│ count_star() │
├──────────────┤
│ 0            │
└──────────────┘
```

**Comment by hannesmuehleisen** [comment]
Wow this one was a classic :)
