### ISSUE TITLE
R API support for `DBI::dbGetInfo()`

### ISSUE THREAD

**Issue by mrcaseb** [duckdb/duckdb#1600]
I am not sure if this is intended behavior so please feel free to close this issue if irrelevant.

The output of a `duckdb::duckdb()` DBI connection in `DBI::dbGetInfo()` is useless and I wonder if it is intended or not. I'll try to show by comparing to the output of an `RSQLite::SQLite()` connection. 

I am depending on this function to get the path to the db. Is there a better method to get the path to the db via the connection?

Thanks!

``` r
con_sqlite <- DBI::dbConnect(RSQLite::SQLite(), tempfile())
con_duckdb <- DBI::dbConnect(duckdb::duckdb(), tempfile())
DBI::dbGetInfo(con_sqlite)
#> $db.version
#> [1] "3.35.2"
#> 
#> $dbname
#> [1] "C:\\Users\\{username}\\AppData\\Local\\Temp\\Rtmpy4fGoA\\file401c136a1aa7"
#> 
#> $username
#> [1] NA
#> 
#> $host
#> [1] NA
#> 
#> $port
#> [1] NA
DBI::dbGetInfo(con_duckdb)
#> $dbname
#> character(0)
#> 
#> $db.version
#> [1] NA
#> 
#> $username
#> [1] NA
#> 
#> $host
#> [1] NA
#> 
#> $port
#> [1] NA
```

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hannesmuehleisen** [comment]
You are absolutely right, this should be extended.
