### ISSUE TITLE
R doesn't let go of database file even after `dbDisconnect`

### ISSUE THREAD

**Issue by travis-leith** [duckdb/duckdb#1602]
I am using R to view DuckDb tables, and I am writing code (in .Net via the c++ lib) separately to create the data.
I have some unit tests which start by deleting the database file and recreating it.
I want to use R to look at some of the tables after the tests have run.
However, if I do so, I cannot run the tests again unless I restart R. It seems that a call to `dbDisconnect` does not let go of the file so that something else can delete it.

**Comment by hannesmuehleisen** [comment]
Try `dbDisconnect(con, shutdown=TRUE)`

**Comment by travis-leith** [comment]
Yes, this works. Thanks.
