### ISSUE TITLE
Move to single CSV reader implementation?

### ISSUE THREAD

**Issue by frankier** [duckdb/duckdb#1603]
Currently there are two readers for CSV-like formats in DuckDB. There is the reader used by `COPY` and `read_csv` which is part of DuckDB proper, and the reader used by `.import` in the shell which is from SQLite. They likely have subtle differences in their implementation and also performance differences which can be a bit confusing when moving from one to another. I wonder whether it might be desirable to shim the CSV import functionality from the SQLite shell to use the same implementation as the other methods. To be clear, I don't have time to work on this, but I thought it would be worth flagging up as a potential future pain-point around the data import process.

**Comment by hannesmuehleisen** [comment]
Indeed replacing the sqlite shell import method would be a good idea. We tried to not change the shell when starting to use it, but that ship has sailed since. So mapping `.import` to `CSV_READ[_AUTO])` would be great. Happy to review a PR!
