### ISSUE TITLE
[Docs] Add Parquet `codec` options to the Copy command's documentation page

### ISSUE THREAD

**Issue by JoshLipschultz** [duckdb/duckdb#1606]
First off — thanks a ton for making such an awesome piece of software! 

This small issue is just a note to add some documentation to https://duckdb.org/docs/sql/statements/copy to indicate that the Parquet codec can be specified. (I found this by checking the tests, but it would be good to publicize this.) If there are other undocumented Parquet-specific export options which I'm unaware of, it would be good to include those as well.

**Comment by hannesmuehleisen** [comment]
Thanks! Would you be able to have a go at this yourself? The website is Open Source as well, its repo is here: https://github.com/duckdb/duckdb-web

**Comment by hannesmuehleisen** [comment]
There are no other parquet specific flags, I think the whole point of Parquet is not to have flags but that's just me.
