### ISSUE TITLE
how to establish JDBC remote connection in Jmeter?

### ISSUE THREAD

**Issue by SeepenL** [duckdb/duckdb#1609]
Hello, I'm doing a concurrent testing with Jmeter, and I meet some problem in how to write a correct JDBCurl to connect Duckdb file in server... Jmeter run in my test machine(Win) and Duckdb in another machine(CentOS)

I use this JDBCurl:    `jdbc:duckdb:root:123456@myServerIP/usr/local/dbtest/duckdb/db/d-1G`  with absolute path, and Jmeter throw error Cannot open file.

Many thanks.

**Comment by hannesmuehleisen** [comment]
Try `jdbc:duckdb:/usr/local/dbtest/duckdb/db/d-1G`, if that's the file name you want to use. DuckDB does not use a socket protocol, hece it makes no sense to specify an IP. Username/password also don't exist.
