### ISSUE TITLE
Arrow CDataInterface Leaks Memory

### ISSUE THREAD

**Issue by ankoh** [duckdb/duckdb#1612]
The CDataInterface is currently leaking the memory of all children for both, ArrowSchema and ArrowArray.

According to the [CDataInterface](https://github.com/apache/arrow/blob/master/docs/source/format/CDataInterface.rst) document:

```
Consumers MUST call a base structure's release callback when they won't be using it anymore, but they MUST not call any of its children's release callbacks (including the optional dictionary). The producer is responsible for releasing the children.

In any case, a consumer MUST not try to access the base structure anymore after calling its release callback -- including any associated data such as its children.
```

The following example will currently leak the memory of the column arrays which can actually pile up memory very quickly.
`ImportRecordBatch` takes over the ownership of `array` here but calls the release callback only for the base struct.
The release callback of DuckDB currently does not cleanup the children which leaves them dangling.

```c++
ArrowArray array;
chunk->ToArrowArray(&array);
ARROW_ASSIGN_OR_RAISE(auto batch, arrow::ImportRecordBatch(&array, schema));
ARROW_RETURN_NOT_OK(writer->WriteRecordBatch(*batch));
```

As confirmation, this fixes the leak in asan:
```c++
ArrowArray array;
chunk->ToArrowArray(&array);
std::vector<ArrowArray*> tmp;
for (auto i = 0; i < array.n_children; ++i) {
    tmp.push_back(array.children[i]);
}
ARROW_ASSIGN_OR_RAISE(auto batch, arrow::ImportRecordBatch(&array, schema));
ARROW_RETURN_NOT_OK(writer->WriteRecordBatch(*batch));
for (auto* array: tmp) {
    array->release(array);
}
```

I can send a PR later.

**Comment by hannesmuehleisen** [comment]
Thanks please do and coordinate with @pdet who is also on this right now
