### ISSUE TITLE
I'm a Python developer - how best can I contribute?

### ISSUE THREAD

**Issue by thesketh** [duckdb/duckdb#1615]
Hi there!

I came across DuckDB a few days ago and I'm really impressed - it's a really nice alternative to SQLite and I've really enjoyed working with it so far. Thanks for your work!

I'd like to contribute, but I don't know any C++. How best can I help, given current priorities? I noticed that the web section for the Python API is quite sparse (though the examples were really helpful), would this be a good use of time?

**Comment by Mytherin** [comment]
Great that you are enjoying DuckDB, and thanks for the offer to help out :)

Writing documentation would be a great way of contributing. The entire website is open source and is hosted [here](https://github.com/duckdb/duckdb-web). If you see any parts that are lacking please feel free to send us a PR with the updated changes.

**Comment by hannesmuehleisen** [comment]
Also tests for the Python API, especially the relational one

**Comment by thesketh** [comment]
Thanks for the prompt responses! I'll see what I can do. :)
