### ISSUE TITLE
Support for parquet fixed_len_byte_array columns

### ISSUE THREAD

**Issue by nelhage** [duckdb/duckdb#1617]
Attempting to read a `fixed_len_byte_array` column from a parquet file yields the very unhelpful error:

```
Error: Not implemented Error: INVALID
```

Reproducer:
```
$ curl -O https://nelhage.com/files/fixed.parquet
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135  100   135    0     0    480      0 --:--:-- --:--:-- --:--:--   480
$ duckdb test.duckdb "select * from parquet_scan('fixed.parquet');"
Error: Not implemented Error: INVALID
```

**Comment by hannesmuehleisen** [comment]
What data type are you storing in the FLBA? Strings?

**Comment by nelhage** [comment]
Yes, for my use case I'm storing fixed-length strings

**Comment by hannesmuehleisen** [comment]
Yes that's something we're happy to add. Just mapping to a `STRING` type in DuckDB is okay, right?

**Comment by nelhage** [comment]
Yeah, that'd work fine. In general I don't know if parquet supports a UTF-8 ConvertedType on FLBA fields, so I'm not sure how you'd decide between `STRING` and `BLOB`, though.

**Comment by hannesmuehleisen** [comment]
This is also an issue for normal strings, because not all parquet files have the ConvertedType

**Comment by hannesmuehleisen** [comment]
Your example file also does not set a converted_type, is that intentional?

**Comment by nelhage** [comment]
It was unclear to me from the docs/tools I was using whether/which converted types are valid on FLBAs. I control the tooling in my use case so I could easily set one if appropriate.

e.g. per https://github.com/apache/parquet-format/blob/master/LogicalTypes.md
> STRING may only be used to annotate the binary primitive type
