### ISSUE TITLE
Parquet reader doesn't appear to handle (some) fields inside nested objects

### ISSUE THREAD

**Issue by nelhage** [duckdb/duckdb#1618]
Given a parquet file with this schema:
```
message test {
  required group inner {
    optional binary str_field (STRING);
    optional double f64_field;
  }
}
```

`parquet_scan` does not appear to read the `str_field` fields correctly. Using the file in `data/struct.parquet` in https://github.com/nelhage/duckdb-parquet-bugs I see:

```
[nelhage@monolithique:~/code/duckdb-parquet]$ parquet-tool cat data/struct.parquet
inner:
.str_field = hello

inner:
.f64_field = 1.23

(GIT: master)
[nelhage@monolithique:~/code/duckdb-parquet]$ duckdb test.duckdb "select * from parquet_scan('data/struct.parquet');"
┌────────────────────────────────────────┐
│                 inner                  │
├────────────────────────────────────────┤
│ <str_field: NULL, f64_field: 1.230000> │
│ <str_field: NULL, f64_field: NULL>     │
└────────────────────────────────────────┘
```

We can see that the `f64_field` is read properly, but the `str_field` is `NULL` even when present in the file.

That test file is generated by https://github.com/nelhage/duckdb-parquet-bugs/blob/master/gen-struct.go in case it is relevant.

**Comment by hannesmuehleisen** [comment]
This is interesting, from looking at the file in detail and I'm a bit confused. Specifically, the repetition levels of the two columns seem off, the string one has `[1, 0]` and the float one has `[2, 0]`, neither of which makes too much sense to me.  However, Arrow's parquet reader seems to read it correctly, so the issue may be a misunderstanding on my side. Will continue.

**Comment by hannesmuehleisen** [comment]
Aha! This turned out to be an issue how we calculate the max define for struct fields, which should have been 1 in this case but was 2. Unclear how the other setting survived so long.
