### ISSUE TITLE
db cannot open after a series of simple operations

### ISSUE THREAD

**Issue by XuPeng-SH** [duckdb/duckdb#1625]
DB reports exception when opening. It can be solid reproduced by the following steps

1.  Open DB
2. Create table: "CREATE TABLE TBL (id INT NOT NULL, age INT NOT NULL, PRIMARY KEY ( id ))"
3. Insert a row: "INSERT INTO TBL VALUES (1, 1);"
4. Delete the row: "DELETE FROM TBL WHERE id = 1;"
5. Insert a row: "INSERT INTO TBL VALUES (1, 1);"
6. Check the result and everything is ok: "SELECT * FROM TBL"
7.  Close the DB

8. Open the DB: Exception: "terminating with uncaught exception of type duckdb::ConstraintException: Constraint Error: Cant create unique index, table contains duplicate data on indexed column(s)"

**Comment by Mytherin** [comment]
Thanks for the report! This is related to both index storage and #109. The index is recreated on startup, but is created on all tuples of the table (including deleted ones). Implementing either index storage or vacuuming of deletes should solve the issue.

**Comment by XuPeng-SH** [comment]
Thanks for your reply.

I am reading the source code of Duckdb, and some of the code logic is different from what I understand. 

1. UpdateSegment::HasUncommittedUpdate: 
2. UpdateSegment::FetchCommitted: Always use the first update info, which is probably uncommitted.

In my understanding, the update info chain is from latest to oldest like this, which is visible by all transactions:
[head: Uncommitted] ---> [Committed] ---> [ Committed ] ---> [ Uncommitted ]  ---> [...]

In this case, the internal logic of the above two functions is inconsistent with the meaning of the function name.
Is my understanding wrong, or the function name here is a bit misleading?

**Comment by Mytherin** [comment]
The function name is indeed a bit misleading, in that it returns the root data which might not necessarily be committed. However, this function is only used in two scenarios:

* Index scans. In this case any uncommitted updates will result in an abort of the index creation - indexes cannot be created right now with uncommitted updates)
* Checkpoints. Right now we only support running checkpoints when there are no other active transactions. Hence, again, it is guaranteed that there are no uncommitted updates.

You are correct that a name such as FetchRootData might be more descriptive, but in the scenarios where FetchCommitted is used only committed data will actually be fetched, so in practice the name is accurate.
