### ISSUE TITLE
Is the storage format of development version (v0.2.6-dev320) incompatible with the stable (v0.2.5) version?

### ISSUE THREAD

**Issue by emres** [duckdb/duckdb#1626]
Hello,

Is the storage format of development version (v0.2.6-dev320) incompatible with the stable (v0.2.5) version?

Yesterday I've created a sample database file with the stable version (`v0.2.5 f480a3293`), and now I'm trying to open this same database file with the development version (`v0.2.6-dev320 6c7c9805f`), but it gives me the following error:

`Error: unable to open database "sample_meter_reading.db":
`

Nothing follows after that, it immediately exits without giving any more information about the error.

I've tried again with the stable version, and it works fine, it can open the database file and I can query the table I've created yesterday.

**Comment by Mytherin** [comment]
The storage format is currently under active development, and is not backwards compatible yet. Our plan is to stabilize the storage format with the V1.0 release, after which we will ensure backwards compatibility such that all V1.X versions can read the V1.0 format. For now in the pre-release version we have opted not to include backwards compatibility to avoid spending developer cycles on data migrations/upgrade paths/etc.  

For now you can perform a data migration manually by running `EXPORT DATABASE 'backup'` in the old version, and `IMPORT DATABASE 'backup'` in the new system.

**Comment by emres** [comment]
Thanks a lot for the explanation and workaround!

**Comment by victorlin** [comment]
I also ran into this after running different versions for testing another issue. It took me a while to figure out that version difference was the problem.

Would it be appropriate to change the error message to something more specific? For example:

```
Error: unable to open database "sample_meter_reading.db": this file might have been created using a different DuckDB version.
```

I see there's supposed to be another message after the `:`, but I haven't seen anything.

https://github.com/duckdb/duckdb/blob/b701ecd1dd2540f6680c8996a001726b279eeb28/tools/shell/shell.c#L14252-L14254

**Comment by Mytherin** [comment]
This was a bug in the shell specifically that resulted in an error not being printed, see #2770. This should be fixed in the latest master (and will be fixed in the next release).
