### ISSUE TITLE
Feature Request: Add support for offset parsing in timestamp string values

### ISSUE THREAD

**Issue by emres** [duckdb/duckdb#1627]
Hello,

I've exported a large PostgreSQL 12 table to a CSV file using the [PostgreSQL COPY](https://www.postgresql.org/docs/12/sql-copy.html) command, and I want to evaluate DuckDB's performance for some analytical queries for that data set.

This is an [IoT](https://en.wikipedia.org/wiki/Internet_of_things) type of sensor readings data and there's a field that stores the date and time information; the PostgreSQL data type of that field is `timestamp with time zone (timestamptz)` as described in "[PostgreSQL: Documentation: 12: 8.5. Date/Time Types](https://www.postgresql.org/docs/12/datatype-datetime.html)". 

PostgreSQL stores these values as [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) values and when I export the data to a CSV  in my 'Europe/Brussels' time zone, a sample timestamp value in the CSV file is like:

`2020-12-31 21:25:58.745232+02`

that is, with the **offset** added.

When I check the TIMESTAMP functionality of DuckDB, I can see that it can parse timestamp values **without offset**, e.g. `'2020-12-31 21:25:58.745232'` :
```

D SELECT TIMESTAMP '2020-12-31 21:25:58.745232';
┌───────────────────────────────────────────────┐
│ CAST(2020-12-31 21:25:58.745232 AS TIMESTAMP) │
├───────────────────────────────────────────────┤
│ 2020-12-31 21:25:58.745232                    │
└───────────────────────────────────────────────┘
```

but it can't do the similar operation for string values **including a time offset** such as `'2020-12-31 21:25:58.745232+02`:

```
D SELECT TIMESTAMP '2020-12-31 21:25:58.745232+02';
Error: Conversion Error: timestamp field value out of range: "2020-12-31 21:25:58.745232+02", expected format is (YYYY-MM-DD HH:MM:SS[.MS]
```

What do you think about this feature request? 

If DuckDB had this feature, and if this was also supported during the automatic type inferring when importing CSV (as described in https://duckdb.org/docs/data/csv), it would be very straightforward to import CSV files generated by PostgreSQL from tables that have  `timestamp with time zone (timestamptz)` fields.

**Comment by Mytherin** [comment]
That sounds like a good idea. Converting these to regular timestamps seems rather simple; we would need to add support for these offsets to `strptime` and add this offset style format to the auto detect options. I can have a look at this.

**Comment by Mytherin** [comment]
Can you check if #1632 implements this behavior as expected?

**Comment by emres** [comment]
Yes. I've just tried it with a CSV file that has timestamp with hour offset values and it looks like it's working as expected. 

Thanks a lot!

**Comment by emres** [comment]
Just one thing: it parses such timestamp with offset values correctly and stores the value as UTC as expected, but the the following still gives the same error:

```
SELECT TIMESTAMP '2020-12-31 21:25:58.745232+02';
Error: Conversion Error: timestamp field value out of range: "2020-12-31 21:25:58.745232+02", expected format is (YYYY-MM-DD HH:MM:SS[.MS])
```

I think this is inconsistent, in the sense that if it is working as expected when reading from the CSV file, then it should also work for the SELECT statement above. Am I wrong?

**Comment by Mytherin** [comment]
You are correct, the default timestamp conversion should also allow for (optional) UTC offsets. For now you can work-around this by using `strptime` (e.g. `select strptime('2020-12-31 21:25:58.745232+02', '%Y-%m-%d %H:%M:%S.%f%z');`).

I also realized the UTC offsets need to support an optional colon (i.e. `+02:00`, instead of `+02`/ `+0200`).

Will have another go at those after the weekend.

**Comment by emres** [comment]
Indeed! 

Your effort is making DuckDB more and more usable for time-based data sets (that need to integrate with other databases).

Thanks a lot for your efforts!

**Comment by Mytherin** [comment]
#1647 should fully resolve this now.
