### ISSUE TITLE
When connecting to local duckDB file in Jmeter, I met a problem...

### ISSUE THREAD

**Issue by SeepenL** [duckdb/duckdb#1628]
The response message is "cannot creat poolableConnectionFactory(IO Erorr: Could not set lock on file "**/usr/tets/d-1G.wal**")".
But my Database URL is "jdbc:duck:/usr/test/d-1G". Is something wrong with write ahead log?

btw, every time Jmeter fail to connect DuckDB file, the file seems to  be broken, with "Error: unable to open database "d-1G": "  when I want to .open it.

Many thanks.

**Comment by hannesmuehleisen** [comment]
I see from the error message that this is running in a connection pool. Can you try without?

**Comment by SeepenL** [comment]
Yes I try to close Jmeter and then the DuckDB file is available. But still cannot connect to duckdb file in Jmeter. I wonder if it is the problem of version, I use DuckDB v0.2.2 (because the lastest 0.2.5 need high version GLIBC that is too hard to update...) and its corresponding JDBCDriver, with Jmeter 5.4.1.
Or can you please recommend some tool to test the cocurrency performance of duckDB if you had ever done it? This will be very grateful help.

**Comment by hannesmuehleisen** [comment]
Could you please share some more details on what exactly you are trying to do, how exactly you are setting up Jmeter? Out of curiosity, what are you trying to measure in the first place?

**Comment by SeepenL** [comment]
Sorry for neglecting the context...I am currently comparing the performance of duckdb and h2db under tpch benchmark for an education task. Performance indicators include query response time, memory cost, and CPU utilization. 

The test is divided into single concurrency and multiple concurrency (btw, the performance of duckdb under single concurrency is much better than h2db), but there are some problems in the multiple concurrency test.

I'm new for Jmeter so I didn't set much, just add a JDBC connection, a JDBC request with simple SQL, and some monitor.

**Comment by hannesmuehleisen** [comment]
Try enabling read-only mode for DuckDB for the parallel tests by setting JDBC connection property `duckdb.read_only` to `true`

**Comment by hannes** [comment]
Closing since there has not been any activity here for over a year. Feel free to comment or reopen if the issue persists.
