### ISSUE TITLE
Is there a way to update a table with records from a csv?

### ISSUE THREAD

**Issue by travis-leith** [duckdb/duckdb#1630]
The kind of SQL I have tried looks like

```SQL
update mytbl
set col1 = x.col1, col2 = x.col2
from read_csv_auto('mycsv') x
where mytbl.id = x.id
```
But trying this I get `"Binder Error: Table "x" does not have a column named "col1"`.

One workaround would be to create a temp table from the csv, do the update, drop the temp table. But would be nice if there was a way to do it without a temp table.

**Comment by Mytherin** [comment]
Would adding column aliases to the subquery fix this? e.g.

```sql
update mytbl
set col1 = x.col1, col2 = x.col2
from read_csv_auto('mycsv') x(id, col1, col2, ...)
where mytbl.id = x.id
```

**Comment by travis-leith** [comment]
I would have fixed it. But the problem was that my csv headers looked like "id, col1, col2" so the column names in the db looked like ' col1' and ' col2' (with the space characters). Removing the space characters in my csv solved the problem, but I guess column aliases is more robust.
I wonder if there should be an option in read_csv_auto to trim spaces from header names?
