### ISSUE TITLE
Discussion / feature request - "query" relation type

### ISSUE THREAD

**Issue by akdor1154** [duckdb/duckdb#1634]
Context: I'm a python/sql guy.

The relational api (in my context, the python interface to it) has a bunch of nice features:
 - it's composable
 - I can easily save results as a view or as a table
 - I can see a quick preview of its results

However there is one (subjective) drawback:
 - i don't want to learn or use a duckdb specific data manipulation api, I would rather express all manipulation in sql.

To address this drawback while keeping the nice stuff above, it would be really useful if I could create a Relation that just expressed the results of a sql query. Would this be feasible? It makes sense in the context of the python interface to duckdb, I don't understand enough to know if it makes sense in the context of the relation c++ object model.

Unrelated: I'm noticing you guys are starting to deal with a ramp-up in github issues.. have you considered enabling discussions as well for not-quite-issues such as this? Not sure if that would help or hinder your maintenance duties :)

Cheers
Jarrad

**Comment by Mytherin** [comment]
I think this is a great idea, and this should actually be quite simple to implement. This would work in both the C++ interface and the Python API built on top of that.
