### ISSUE TITLE
Count() gives incorrect results -- sometimes.

### ISSUE THREAD

**Issue by akdor1154** [duckdb/duckdb#1636]
Hiya,
I'm really giving this thing a workout, sorry for the torrent of issues.

I'm seeing a weird situation: when I run a query based on 
```sql
count(case when condition then 1 else null end)
```
then in small datasets, the query returns correct results, but on large tables (~ million rows), the query will consistently return incorrect results for some rows. If you go and run the query on just those incorrect rows with a `where` clause, it will return correct results again.

Full reproduction:
data at https://drive.google.com/file/d/1cPVh7lxCCJe_G-LKdVpHTAOQ4LMF0yK5/view?usp=sharing

```sql
with Counted as (
	select
		left_group,
		sum(count_tx) as num_tx,

		first(left_in_many_right) as left_in_many_right,
		count(*) as number_of_right_groups,

		count(
			case when
				left_in_many_right and not right_in_many_left
			then 1 else null end
		)
			as num_right_subgroups,

		count(
			case when
				not left_in_many_right and right_in_many_left
			then 1 else null end
		)
			as num_right_supergroups,

		count(
			case when
				not left_in_many_right and not right_in_many_left
			then 1 else null end
		)
			as num_exact,

		count(
			case when
				left_in_many_right and right_in_many_left
			then 1 else null end
		)
			as num_messy

	from THE_PARQUET_I_SHARED
	group by left_group
),
Classified as (
	select
		*,

		case
			when num_messy > 0 then 'messy'
			when num_exact = 1 and num_right_subgroups = 0 and num_right_supergroups = 0 then 'exact'
			when num_exact = 0 and num_right_subgroups > 0 and num_right_supergroups = 0 then 'split'
			when num_exact = 0 and num_right_subgroups = 0 and num_right_supergroups > 0 then 'subset'
			else 'error'
		end as classification

	from Counted
),
Aggregated as (
	select
		classification,
		count(*)
	from Classified
	group by classification
)

-- 1: see we have some errors
--select * from Aggregated

-- 2: look at some
--select * from Classified where classification = 'error' order by left_group desc limit 10

-- 3: look at one - wtf!!! not an error any more!!
--select * from Classified where left_group = 'fff96204d9a7a1913b4a1bb9ec8b741a'
```

`Classification` is able to pick up when `count(case..)` is not working, and will label these rows as 'error'. These are shown to exist in `Aggregated`. (end query 1)
We can even go and look at specific rows by filtering on `error` (end query 2).

However, when we filter by one of those in `error` state, it's not an `error` any more, and the count(case..)-es start counting properly again!

Replacing count(case ... 1 null) with sum(case ... 1 0) make everything work fine.

You can reproduce this by making a Relation directly on top of the parquet I shared, but I first experienced it pulling directly from a table in my database.

**Comment by akdor1154** [comment]
this appears fixed in latest master.

**Comment by hannesmuehleisen** [comment]
If its fixed in master this can be closed or am I missing something?

**Comment by akdor1154** [comment]
yep i guess so,  sorry.
