### ISSUE TITLE
AddressSanitizer: new-delete-type-mismatch

### ISSUE THREAD

**Issue by chybz** [duckdb/duckdb#1653]
Hello,

Address Sanitizer fires off when executing a query similar to the following (real query has 20 non-aggregated fields and 37 aggregations, removed for briefty):

```sql
CREATE TABLE
    agg
AS SELECT
    field1,
    field46,
    min(start_time) as StartTime,
    max(end_time) as EndTime,
    sum(duration) as Duration,
    sum(up_pkt) as UpPacket,
    max(dn_thruput_max) as DnThruMax,
    first(dn_thruput_avg) as FirstDnThruAvg,
    sum(tcp_attempt) as TcpAttempt
FROM
    imported_table
WHERE
    field46 not in ('foo', 'bar')
GROUP BY
    field1,
    field46
```
You will find ASAN trace in the attached file.
[asan-log.txt](https://github.com/duckdb/duckdb/files/6342382/asan-log.txt)

Environment is: Debian bullseye, gcc 10.2.1, DuckDB 0.2.5

Could you please have a look ?

Thank you !

**Comment by Mytherin** [comment]
This seems related to #1490. Can you verify that this also breaks on the master branch?

**Comment by chybz** [comment]
It's ok on master, no warnings. I'll stick to that. Thank you !
