### ISSUE TITLE
Support USING clause in DELETE

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#1655]
I am looking for a way to delete from a table based on the content of another table (or multiple tables `JOIN`ed together):

The Postgres compatible way seems to be [`DELETE`'s `USING` clause](https://stackoverflow.com/questions/1590799/delete-all-rows-in-a-table-based-on-another-table/37656639):

```sql
CREATE TABLE t1(id int);
CREATE TABLE t2(id int);

DELETE FROM t1
USING t2
WHERE t1.id = t2.id;
```

Postgres output:
```console
postgres=# CREATE TABLE t1(id int);
CREATE TABLE
postgres=# CREATE TABLE t2(id int);
CREATE TABLE
postgres=# 
postgres=# DELETE FROM t1
postgres-# USING t2
postgres-# WHERE t1.id = t2.id;
DELETE 0
```

Postgres supported [`MERGE` in version 8](https://www.postgresql.org/message-id/attachment/23520/sql-merge.html) but this [no longer seems to be the case](https://www.postgresql.org/message-id/CANP8+jKitBSrB7oTgT9CY2i1ObfOt36z0XMraQc+Xrz8QB0nXA@mail.gmail.com) and it's not included in the parser used by DuckDB.

For my use case (LDBC SNB), I have now settled with a workaround using subqueries. For deleting rows based on their primary key:
```sql
DELETE FROM Person
WHERE id IN (SELECT id FROM Delete_Candidates_Person);
```

For rows with composite primary keys, I use string concatenation to determine which rows need to be deleted:
```sql
DELETE FROM Person_knows_Person
WHERE concat(Person1id, '->', Person2Id)
  IN (SELECT concat(src, '->', trg) FROM Delete_Candidates_Person_knows_Person);
```
(I'm only using DuckDB for testing in this project so it's not performance-critical - if performance matters, a multiplication resulting in a `BIGINT` would be much faster than string concatenation.)

**Comment by hannesmuehleisen** [comment]
I think the title is a bit misleading, this is entirely possible already as you state yourself just not with the `USING` keyword (that I find odd personally)

**Comment by Mytherin** [comment]
Could you check if #1659 solves this for your use case?

**Comment by szarnyasg** [comment]
@Mytherin Thanks for the patch! I quickly tested it with a weird cornercase (mix of `USING` and `JOIN`)  and it works as expected (it produces the same result as Postgres, keeping just number `2` in `t1`).

```sql
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;

CREATE TABLE t1(id int);
CREATE TABLE t2(id int);
CREATE TABLE t3(id int);

INSERT INTO t1 VALUES (1), (2);
INSERT INTO t2 VALUES (1), (2);
INSERT INTO t3 VALUES (1);

SELECT * FROM t1;

DELETE FROM t1
USING t2
JOIN t3
  ON t3.id = t2.id
WHERE t1.id = t2.id;

SELECT * FROM t1;
```

I will test with the more complex LDBC queries later today.

**Comment by szarnyasg** [comment]
I tested it with more corner cases, in particular when used with `WITH RECURSIVE` queries. I could get it working but it needed a workaround of using a subquery containing the `WITH RECURSIVE` query.

Example scenario: I have a comment tree where I want to delete a comment and recursively all its replies.
My Comment table has 5 comments and one comment (`3`) is selected for the recursive deletion.

```sql
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Delete_Candidates_Comment;

CREATE TABLE Comment(id int, replyof_comment int);
CREATE TABLE Delete_Candidates_Comment(id int);

INSERT INTO Comment VALUES (1, NULL), (2, 1), (3, 1), (4, 3), (5, 3);
INSERT INTO Delete_Candidates_Comment VALUES (3);
```

This works in both DuckDB and Postgres:
```sql
DELETE FROM Comment
USING (
  WITH RECURSIVE message_thread AS (
      SELECT id
      FROM Delete_Candidates_Comment -- starting from the delete candidate comments
      UNION ALL
      SELECT comment.id AS id
      FROM message_thread
      JOIN comment
        ON comment.replyof_comment = message_thread.id
  )
  SELECT id
  FROM message_thread
  ) sub
WHERE sub.id = Comment.id
;
```
This only works in Postgres:
```sql
WITH RECURSIVE message_thread AS (
      SELECT id
      FROM Delete_Candidates_Comment -- starting from the delete candidate comments
      UNION ALL
      SELECT comment.id AS id
      FROM message_thread
      JOIN comment
        ON comment.replyof_comment = message_thread.id
  )
DELETE FROM Comment
USING message_thread
WHERE message_thread.id = Comment.id
;
```
```console
DuckDB returns
Error: Catalog Error: Table with name message_thread does not exist!
Did you mean "person"?
LINE 11: USING message_thread
               ^
```
I'm fine with using a subquery, so just logging this here in case anyone bumps into this issue.

**Comment by Mytherin** [comment]
That seems related to #160

**Comment by szarnyasg** [comment]
Yes! Thanks for the pointer.
