### ISSUE TITLE
QUANTILE_CONT

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1658]
The existing `quantile` aggregate is actually the discrete version, sometimes called `quantile_disc`. This works for all categorical (orderable) domains, but for quantitative domains [an interpolated value](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions110.htm) can be computed:

> The result of PERCENTILE_CONT is computed by linear interpolation between values after ordering them. Using the percentile value (P) and the number of rows (N) in the aggregation group, we compute the row number we are interested in after ordering the rows with respect to the sort specification. This row number (RN) is computed according to the formula RN = (1+ (P*(N-1)). The final result of the aggregate function is computed by linear interpolation between the values from rows at row numbers CRN = CEILING(RN) and FRN = FLOOR(RN).
>
>The final result will be:

```sql
  If (CRN = FRN = RN) then the result is
    (value of expression from row at RN)
  Otherwise the result is
    (CRN - RN) * (value of expression for row at FRN) +
    (RN - FRN) * (value of expression for row at CRN)

```

**Comment by hannesmuehleisen** [comment]
We had a look at this some time ago. R (which I'm taking as a reference here) has like seven quantile implementations and about half do not interpolate. Do you think users will expect interpolation?

**Comment by hawkfish** [comment]
I don't think we need to compute with R(!) But I included the link because both Oracle and MS-SQL have this, so it seems relatively popular.

**Comment by domoritz** [comment]
[`percentile_cont`](https://www.postgresql.org/docs/9.4/functions-aggregate.html) in Postgres also interpolates.

**Comment by JunranY** [comment]
We are also interested! It matches what Vega does for quartiles too.

**Comment by hawkfish** [comment]
Naturally, we should also include `QUANTILE_DISC` as a synonym for the existing `QUANTILE`.

**Comment by domoritz** [comment]
Backwards compatibility if of course important but if you had to design the feature from scratch, do you think the continuous version would have been the default?

**Comment by hawkfish** [comment]
You mean that now we have `QUANTILE` == `QUANTILE_DISC`? Yes, that might not have been my first choice!  We also have `MEDIAN` to worry about.

**Comment by domoritz** [comment]
I think it would be good if MEDIAN = QUANTILE at 1/2. Since median is interpolated (I think it always is?), I would also vote for QUANTILE = QUANTILE_CONT.

**Comment by Mytherin** [comment]
I don't have strong feelings either way - what do other systems use as a default? Perhaps we could use the continuous version as default for numerics, and the discrete version for strings/types that don't allow for interpolation?

**Comment by hawkfish** [comment]
That makes sense to me. I was going to add missing types like strings at some point too.

**Comment by domoritz** [comment]
That makes sense for median. I wonder whether it would make sense to expect an additional argument to quantile that specifies the interpolation? This is what Pandas does: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html.
