### ISSUE TITLE
parquet nesting support

### ISSUE THREAD

**Issue by mrgleeco** [duckdb/duckdb#1660]
First: thank you for this project. This looks amazing!

My initial experiments were with parquet which were generated as a set of files (exported from BigQuery, snappy compression).  This does not seem to work due to nested columns. Is this documented? On a roadmap?

Or perhaps I am doing it wrong™️ 

```
>>> print(cursor.execute("SELECT * FROM parquet_scan('data/000000000027');").fetchall())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Failed to read Parquet file "data/000000000027": Only flat tables are supported (no nesting)
```

**Comment by hannesmuehleisen** [comment]
Nested columns should work. Can you share a file that demonstrates the issue? The wildcard syntaxis supported.

**Comment by mrgleeco** [comment]
indeed! newer version unlocks this feature. Happy to call this issue done; but can also share some other first impressions: 

- declare in docs nested is supported, wildcard is supported (self-memo:  docs PR)
- unclear how to query nested properties (naive first go was dot-delimited); finally found `struct_extract`
- a column named `order` seems incompatible with query parser: `Error: Parser Error: syntax error at or near "order"`
- this seems true too for `extract(order, 'id')`: `Error: Parser Error: syntax error at or near "order"`
- error copying nested, compressed parquet to table: `Error: TransactionContext Error: Failed to commit: Not implemented Error: Unimplemented type for uncompressed segment`

**Comment by hannesmuehleisen** [comment]
Try quoting `order` with double-quotes `"order"`. Indeed copying nested data to a persistent table is not supported yet.
