### ISSUE TITLE
Python relational API: `unregister` does not delete reference to relation/DataFrame

### ISSUE THREAD

**Issue by thesketh** [duckdb/duckdb#1662]
**What does happen?**
Queries can still be run against relation objects after `unregister`-ing the table names.

**What should happen?**
The `unregister` method should delete references to a relation object / Pandas DataFrame.

**To Reproduce**

```python
import duckdb
import pandas as pd
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
connection = duckdb.connect(":memory:")
connection.register("dataframe", df)

print(connection.execute("SELECT * FROM dataframe;").fetchdf())
#    0  1  2
# 0  1  2  3
# 1  4  5  6
connection.unregister("dataframe") # Should delete reference to dataframe.
print(connection.execute("SELECT * FROM dataframe;").fetchdf())
#    0  1  2
# 0  1  2  3
# 1  4  5  6

connection.execute("DROP VIEW dataframe;")  # Drop view with SQL.
# This _does_ stop us from printing the df.
print(connection.execute("SELECT * FROM dataframe;").fetchdf())
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# RuntimeError: Catalog Error: Table with name dataframe does not exist!
# Did you mean "dataframe"?
# LINE 1: SELECT * FROM dataframe;
#                       ^


```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - DuckDB Version: 0.2.5

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Indeed we don't drop the view in `unregister` yet.

**Comment by thesketh** [comment]
It looks like the handle is saved in the database, so this can lead to a segfault if the dataframe is out of memory:

```python
import gc
import duckdb
import pandas as pd

connection = duckdb.connect("some_database.db")
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])

connection.register("dataframe", df)
connection.unregister("dataframe")  # Attempting to unregister.
# Still saved in catalog.
connection.close()

# Reconnecting while DataFrame still in mem.
connection = duckdb.connect("some_database.db")
print(connection.execute("PRAGMA show_tables;").fetchdf())
#         name
# 0  dataframe
print(connection.execute("SELECT * FROM dataframe;").fetchdf())  # No issues printing.
#    0  1  2
# 0  1  2  3
# 1  4  5  6
connection.close()

# Force garbage collection of DataFrame.
del df
gc.collect()

# Reconnecting after DataFrame freed.
connection = duckdb.connect("some_database.db")
print(connection.execute("PRAGMA show_tables;").fetchdf())
#         name
# 0  dataframe
print(connection.execute("SELECT * FROM dataframe;").fetchdf())
# [1]    9807 segmentation fault (core dumped)
connection.close()
```

**Comment by hannesmuehleisen** [comment]
Yes, that's exactly what will happen there. This is a bug and should be fixed.

**Comment by thesketh** [comment]
Does the Python API keep track of everything that has been `register`ed? It could be a good idea to drop these implicitly when a connection is closed, but that might break some workflows if people are closing and reopening connections to a database file within the same process.

**Comment by hannesmuehleisen** [comment]
It does, and those are dropped when the connection is closed since its destroyed and the refs from pybind are destroyed too.
