### ISSUE TITLE
Cannot roundtrip "week" format %W with strftime / strptime

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#1669]
**What does happen?**

Not all the date-time formats listed in https://duckdb.org/docs/sql/functions/dateformat appear to be implemented yet.  In particular, strptime does not understand week format, `%W`:

Throws the error:

```
Error: Not implemented Error: Unimplemented specifier for strptime
```

Related issue in documentation and possibly implementation: The docs do not say if %W is the ISO definition or the UK definition (both start on Monday, but ISO matches the year that gets the most days and is typically denoted by %V, which is not implemented.  In general I think most users would prefer the ISO standard to the less-standard week notation).   

(Context: I simply want to be able to perform weekly averages and preserve the column in date format)

**What should happen?**

We should be able to round-trip dates, e.g. in R something like
```
  df %>% 
  mutate(week = strftime(date, "%Y W%W")) %>% 
  mutate(time = strptime(date, "%Y W%W"))
```

Ideally the docs would be clear that %W is not the ISO week definition, and %V would be supported for ISO week.  

(apologies I couldn't figure out a CLI example for  the function call)  

**Environment (please complete the following information):**
 - OS: Linux 
 - DuckDB Version Current R release (R 2.5.0, I think is duckdb 13?)

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
These indeed seem like good ideas. I assume that on the "round-trip" you default to the first day of the week, unless other information is given that specifies e.g. the day of the week.

For your use case, I think you might be find `date_trunc` to be useful, e.g.:

```sql
select date_trunc('week', date '1992-01-01'), date_trunc('week', date '1992-01-05'), date_trunc('week', date '1992-01-07');
┌────────────────────────────────────────────┬────────────────────────────────────────────┬────────────────────────────────────────────┐
│ date_trunc(week, CAST(1992-01-01 AS DATE)) │ date_trunc(week, CAST(1992-01-05 AS DATE)) │ date_trunc(week, CAST(1992-01-07 AS DATE)) │
├────────────────────────────────────────────┼────────────────────────────────────────────┼────────────────────────────────────────────┤
│ 1991-12-30 00:00:00                        │ 1991-12-30 00:00:00                        │ 1992-01-06 00:00:00                        │
└────────────────────────────────────────────┴────────────────────────────────────────────┴────────────────────────────────────────────┘
```

**Comment by cboettig** [comment]
Thanks @Mytherin ! 

Yup, defaulting to the first day is the convention I believe, though I probably should have just given an example with the day specified as well.  I had overlooked `date_trunc`!  that's excellent, just what I need! :rocket:

**Comment by Mytherin** [comment]
Yes, I think we should support this. Python also (semi) supports this:

```python
import datetime
# %W by itself seems to do nothing
datetime.datetime.strptime('1992-50', '%Y-%W')
# datetime.datetime(1992, 1, 1, 0, 0)
# %W together with %w result in an actual date
datetime.datetime.strptime('1992-50-1', '%Y-%W-%w')
# datetime.datetime(1992, 12, 14, 0, 0)
```

**Comment by hawkfish** [comment]
So the spec is "Do what Python does"?!

**Comment by Mytherin** [comment]
Generally, something like that, as long as it is not too surprising ;)

Here is R for good measure:

```r
> strptime('1992-50', '%Y-%W')
[1] "1992-05-11 CEST"
> strptime('1992-50-1', '%Y-%W-%w')
[1] "1992-12-14 CET"
```

**Comment by hawkfish** [comment]
@cboettig can we close this?

**Comment by cboettig** [comment]
Looks excellent, thanks much!
