### ISSUE TITLE
Window function LAG with negative number as parameter results in an assertion being triggered

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1676]
**What does happen?**
Running `select lag(i, -1) over () from integers;` results in the following assertion:

`Error: INTERNAL Error: Assertion triggered in file "/Users/myth/Programs/duckdb-bugfix/src/common/types/data_chunk.cpp" on line 51: index < size()`

**What should happen?**
lag with negative numbers should be identical to lead with positive numbers (e.g. lag(i, -1) == lead(i, 1)).

**To Reproduce**
```sql
CREATE TABLE integers AS SELECT * FROM generate_series(0, 10, 1) tbl(i);
select lag(i, -1) over () from integers;
-- this should be identical to the following query:
-- select lead(i) over () from integers;
```

**Environment (please complete the following information):**
 - MacOS
 - DuckDB master

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Negative lag?! Who would do something as mad as that :)

**Comment by hawkfish** [comment]
[No clue](file:///Users/hawkfish/Documents/Development/textform/docs/_build/html/transforms/reformats/lag.html)

**Comment by hawkfish** [comment]
Offsets are typed to be unsigned. Hilarity ensues.
