### ISSUE TITLE
Convert temporal data types to structs

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1680]
The existing temporal data types are aliased to various signed integers. This can make it difficult to write templated code that references both types with different semantics e.g, the continuous promotion of `date_t` (currently an `int32_t`) to `timestamp_t` (currently `int64_t`) requires scaling by the number of µs in a day, not simply prompting the integer representation.

The underlying physical types should remain the same for operations such as hashing and packing.

**Comment by hannesmuehleisen** [comment]
One thing to consider here is adding support for structs to join/aggr hash tables, which is not there yet. So testing joins and aggregations with those types both as key and as payload columns is important

**Comment by hawkfish** [comment]
Are they based on physical types?
