### ISSUE TITLE
Import database fails when table's name have '.' or '-'

### ISSUE THREAD

**Issue by Manerone** [duckdb/duckdb#1690]
**What does happen?**
Fails to import a database created via the export command. This happens when the exported table has some symbols in its name (like . or -).

**What should happen?**
Given that DuckDB accepts creating these tables it also should be able to load tables with symbol when using EXPORT + IMPORT.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. `duckdb original_db`
2. CREATE TABLE "a-1"(id int);
3. INSERT INTO "a-1" VALUES (1);
4. EXPORT DATABASE 'exported';
5. .quit
6. `duckdb imported`
7. IMPORT DATABASE 'exported';
```
Error: Parser Error: syntax error at or near "-"
LINE 7: COPY a-1...
```

**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - DuckDB Version: master

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Looks some quotes are missing in the export. Happy to review a PR.
