### ISSUE TITLE
R API tutorial error when running the inserting row example

### ISSUE THREAD

**Issue by vincentvanhees** [duckdb/duckdb#1696]
**What does happen?**

When running the steps from the R API tutorial on https://duckdb.org/docs/api/r

```
# insert a row using prepared statements
dbExecute(con, "INSERT INTO items VALUES (?, ?, ?)", 'laptop', 2000, 1)
```
causes:

```
Error in dbBind(res, params) : 
  duckdb_bind_R: bind parameters need to be a list of length 3
```

**What should happen?**

I suppose it should add a row using the prepared statement.
Does this mean the feature has been deprecated? If yes, maybe good to remove that command from the tutorial.

**To Reproduce**

Run queries from https://duckdb.org/docs/api/r step by step from top to bottom.

**Environment:**
 - OS: Ubuntu 20.04.2
 - DuckDB Version 0.2.5 (from CRAN)
 - R version 4.0.5
 - DBI Version 1.1.1

**Comment by hannesmuehleisen** [comment]
Good catch, that should be a `list()` I believe.

**Comment by hannesmuehleisen** [comment]
Should be fixed, thanks for reporting, Vincent!
