### ISSUE TITLE
registering a temp table from a pandas DataFrame fails on timedelta64 types

### ISSUE THREAD

**Issue by leifwalsh** [duckdb/duckdb#1700]
**What does happen?**
If I have a pandas DataFrame with some timedelta64 types, and I try to use DuckDB's register() function to create a temp view, it fails on those columns. 

**What should happen?**
I think those should be inserted as INTERVAL types.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. `df = pandas.DataFrame({'a': [pandas.Timestamp.now()], 'b': [pandas.Timedelta(1, unit='s')]})`
2. `con = duckdb.connect('example.db', read_only=False)`
3. `con.register('example', df)`

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version 0.2.5

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

I haven't tried this on master yet. I think this is sort of related to #1426.

**Comment by leifwalsh** [comment]
A workaround is to store seconds instead:

```py
con.register('example', df.assign(b=df['b'].dt.total_seconds())
```

But now this is a DOUBLE type instead of INTERVAL and I don't think it's possible to do math between TIMESTAMP and DOUBLE.

**Comment by hannesmuehleisen** [comment]
Yes that's indeed one of the more exotic pandas types but we should support it

**Comment by pdet** [comment]
This can be closed.

**Comment by leifwalsh** [comment]
Thanks!

**Comment by pdet** [comment]
@leifwalsh let me know if you still face any problem on that matter :-)
