### ISSUE TITLE
Compile error on Windows with MSVC 2019 due to Lazy load extension test failure

### ISSUE THREAD

**Issue by chilarai** [duckdb/duckdb#1701]
**What does happen?**
During the Linking step, I get the following error `Error LNK2001 unresolved external symbol __delayLoadHelper2`. Seems like the project cannot locate the symbol in the project-generated lib file. When I tried to look for the symbol, I also can't seem to locate it inside the project. The error is generated from the `test\extension\CMakeLists.txt`

```
if(WIN32)
  set_target_properties(loadable_extension_demo
                        PROPERTIES LINK_FLAGS "/DELAYLOAD:duckdb.dll")
endif()
``` 

**What should happen?**
For the time being, I commented out the above lines to successfully compile the project

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1.  Open the latest code in Visual Studio 2019 (v16.8.5)
2.  Generate Cache
3.  Build project

**Environment (please complete the following information):**
 - Windows 10 x_64
 - Visual Studio 2019 (v16.8.5)
 - Latest source code in the master branch

**Comment by hannesmuehleisen** [comment]
Can you try to add `delayimp.lib` to the libraries of `loadable_extension_demo` when on WIN32?

**Comment by chilarai** [comment]
Thanks. I have tried what you have suggested and it did work after changes to environment variables and adding delayimp.lib paths to CMake. But, it results in configuring the existing source code on every individual system on Windows before building.

However, if I change the above-mentioned CMake code to the following, it works like a charm without any other tweaks. Could you please confirm the same?

```
if(WIN32)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}  /DELAYLOAD:duckdb.dll")
endif()
```

**Comment by hannesmuehleisen** [comment]
Great that you came up with a generic fix! Can you send a PR with this change please?

**Comment by chilarai** [comment]
Sure. I have sent a PR
