### ISSUE TITLE
How to insert a tuple containing a Python 'bytes' object as a BLOB?

### ISSUE THREAD

**Issue by penguian** [duckdb/duckdb#1703]
I am trying to convert my existing Python Sqlite3 code to use duckdb.
The original table creation code contains
```
    curs.execute("""
        CREATE TABLE bent_function(
        nvariables INTEGER,
        bent_function BLOB,
        name TEXT UNIQUE,
        PRIMARY KEY(nvariables, bent_function))""")
```
The original row insertion code contains
```
    curs.execute("""
        INSERT INTO bent_function
        VALUES (?,?,?)""",
        (nvar, bftt, name))
```
where the types are `nvar: <class 'int'>`, `bftt: <class 'bytes'>, `name: <class 'str'>`.
This works in Sqlite3.

Dropping the same code into duckdb by just changing the import statement results in the error message:
```
RuntimeError: String value is not valid UTF8
```
1. Is this the correct place to ask how to work around this issue, or is there a DuckDB support forum somewhere?
2. Is this a bug in the DuckDB Python interface for `INSERT INTO` that it can't interpet `class 'bytes'` as a BLOB?

**Comment by penguian** [comment]
My existing code is in (e.g.) https://github.com/penguian/Boolean-Cayley-graphs/blob/master/boolean_cayley_graphs/classification_database_sqlite3.py

**Comment by hannesmuehleisen** [comment]
The Python API needs to be extended to support this. Happy to review a PR!

**Comment by hannesmuehleisen** [comment]
Specifically, this needs to be addressed in `DuckDBPyConnection::TransformPythonParamList` in `pyconnection.cpp`

**Comment by penguian** [comment]
Thanks. I can see that there is a for loop in that function:
```
        for (pybind11::handle ele : params) {
		if (ele.is_none()) {
			args.emplace_back();
        [...]
		} else if (py::isinstance<py::str>(ele)) {
			args.emplace_back(ele.cast<string>());
		} else if (py::isinstance(ele, decimal_decimal)) {
			args.emplace_back(py::str(ele).cast<string>());
        [...]
		} else {
			throw std::runtime_error("unknown param type " + py::str(ele.get_type()).cast<string>());
		}
	}
```
The test for `py::isinstance<py::str>(ele)` is probably matching objects of Python classs `byte`. There is no test here for something like `py::isinstance<py::bytes>(ele)` or even `py::isinstance<py::memoryview>(ele)` so I can't see how this code can transform objects into blobs. After matching on the correct type for `bytes` it would need to do something like
```
args.push_back(Value::BLOB(ele.cast<string>()));
```
if this makes sense, or is even possible. Is this correct?

Right now, I can't even see how to work around the issue, since not even `memoryview` works, and there is no case in this function where something is transformed into a BLOB type. In contrast, [the sqlite3 documentation](https://docs.python.org/3/library/sqlite3.html#sqlite-and-python-types) is quite clear that the BLOB type is to be converted to and from the Python `bytes` class. I don't undertand how the DuckDB Python interface tests for the BLOB type have worked up until now.

**Comment by penguian** [comment]
See also [pybind11 PR 2348 ](https://github.com/pybind/pybind11/pull/2348). It looks to me like the correct behaviour of pybind11 wrt Python 3 str vs byte types has not yet been merged into master? This could explain some of the strange behaviour of the DuckDB Python interface as above.

**Comment by penguian** [comment]
See also [pybind11 PR 2442](https://github.com/pybind/pybind11/pull/2442) which was merged into master. So at least part of the correct behaviour is in pybind11 master as of 28 August 2020.

**Comment by Mytherin** [comment]
I'm not sure if those pybind issues are related. Looking at the Python prepared statement parameter conversion it seems to me like BLOB is simply not implemented there yet. The BLOB type was added after the Python API was created, so this is not necessarily very surprising. I also don't see any tests relating to BLOB prepared statement parameters, only tests relating to reading blobs stored in DuckDB into Python, which uses a different code path.

> if this makes sense, or is even possible. Is this correct?

That makes sense to me. I would try that and see if that fixes the issue.

**Comment by penguian** [comment]
About tests: indeed. See https://github.com/python/cpython/blob/main/Lib/sqlite3/test/types.py which contains a `CheckBlob` test that inserts a blob into the blob column `b` vs https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/tests/sqlite/test_types.py which does not have the blob column or the test. 

I suppose that the first step towards creating the PR would be to update the [types.py](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/tests/sqlite/test_types.py) test as per sqlite3 and make sure that it currently fails. Then change `DuckDBPyConnection::TransformPythonParamList` so that the test succeeds and no other tests fail.

**Comment by Mytherin** [comment]
> I suppose that the first step towards creating the PR would be to update the types.py test as per sqlite3 and make sure that it currently fails. Then change DuckDBPyConnection::TransformPythonParamList so that the test succeeds and no other tests fail.

That sounds good to me.
