### ISSUE TITLE
Aggregation parallelism question

### ISSUE THREAD

**Issue by chybz** [duckdb/duckdb#1718]
Hi,

while running a grouping aggregation query on 4 tables, I see that only 1 thread is used and was wondering if this is the expected behavior. `PRAGMA threads` is set to `std::thread::hardware_concurrency()` (28, no HyperThreading). Query is 
[agg_query.txt](https://github.com/duckdb/duckdb/files/6435163/agg_query.txt). The 4 sub-tables contain 31M rows total (equally distributed) and query returns 13M rows. Runtime is ~55s, and seems pretty high.

Am I missing something ?
Thank you for any insight.

**Comment by Mytherin** [comment]
Thanks for the report! `UNION ALL` currently blocks any parallelism in the individual pipelines. This is a known limitation that should be resolved with #1583.

**Comment by chybz** [comment]
Nice ! From your experience as a core developer, is there anything I can do (multiple queries, no sub-tables, other syntax, ...) to circumvent that issue the time being ?

**Comment by Mytherin** [comment]
For now the easiest option would be to concatenate everything into a single table.

**Comment by chybz** [comment]
Understood. Do you think it's preferable to append to a single table from multiple threads or have each thread append to its own table and concat that before aggregating ?

**Comment by Mytherin** [comment]
It should be fine to append to a single table from multiple threads.

**Comment by chybz** [comment]
Thanks for the quick and quality support !
