### ISSUE TITLE
Index join hangs

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#1721]
**What does happen?**
Query hangs when `PRAGMA force_index_join` is forced on a PK-FK join.

**What should happen?**
The query should use an index join and return the results.

**To Reproduce**

```sql
CREATE TABLE Person (id bigint PRIMARY KEY);
CREATE TABLE Person_knows_Person (Person1id bigint, Person2id bigint);

INSERT INTO Person VALUES (1), (2), (3), (4), (5);
INSERT INTO Person_knows_Person VALUES (1, 2), (1, 3), (1, 4), (2, 3), (3, 4), (4, 5);

PRAGMA force_index_join;

SELECT *
FROM Person_knows_Person pkp
JOIN Person p1
  ON p1.id = pkp.Person1id
JOIN Person p2
  ON p2.id = pkp.Person2id;
```

This hangs with 0.2.5 and a fresh build from `master`. Explain shows that the plan contains two `INDEX_JOIN` operators (as expected).

**Environment (please complete the following information):**
 - OS: Fedora 34
 - DuckDB Version: 0.2.5, e2361416d7

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by szarnyasg** [comment]
@pdet thanks for the quick fix. I rebuilt DuckDB on your branch and it no longer hangs.

**Comment by pdet** [comment]
Hi @szarnyasg, my pleasure, the index join is a bit of an uncharted land since the optimizer will only use it for very selective queries. Let me know if you face any other issues! :-)

**Comment by pdet** [comment]
@Mytherin I think this can be closed.
