### ISSUE TITLE
CREATE TABLE from parquet crashes latest bleeding edge

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#1723]
**What does happen?**
R seems to crash whenever I try to create a table from Parquet. 

**What should happen?**
Create the table without a hitch

**To Reproduce**
create table test select * from parquet_scan('H:/parquet_zstd/crsp/dsf/*')

**Environment (please complete the following information):**
Windows 10, R 4.0.2
packageVersion('duckdb')
[1] '0.2.6'

**Before submitting**
I have tried this on the latest master branch, then I resorted to 2.6 from CRAN just to make sure.

I've uploaded one example parquet file (zipped b/c that's the only accepted format).
[leftdate3_192_loop_1.zip](https://github.com/duckdb/duckdb/files/6437850/leftdate3_192_loop_1.zip)

**Comment by hannesmuehleisen** [comment]
Can you please remember to use our issue template next time?

**Comment by alanpaulkwan** [comment]
Didn't see it - is it pinned somewhere?

**Comment by hannesmuehleisen** [comment]
Also this does not crash for me. Template should be shown when creating issue, is it not?

**Comment by alanpaulkwan** [comment]
Ah yes, I noticed it now. In any case, let me try to debug a bit more on various environments.

**Comment by Mytherin** [comment]
As this involves a CREATE TABLE AS, this could be related to #1745.

**Comment by alanpaulkwan** [comment]
I think I have an inkling of what's going on. The column that's causing a problem is numtrd, which is completely null in this file. Early in the history of stock trading, exchanges did not record numtrd, hence in this file it is null. I'm more confident as later files - where numtrd is non-null for a significant share of entries - do not crash. It must be something related to that.


[leftdate3_192_loop_1.zip](https://github.com/duckdb/duckdb/files/6460569/leftdate3_192_loop_1.zip)

**Comment by Mytherin** [comment]
Thanks for the investigation! I will have a look at this.

**Comment by alanpaulkwan** [comment]
The problem is still there @Mytherin  :(

**Comment by Mytherin** [comment]
Did you rebuild the master or the PR that I sent? The PR has not been merged into master yet.

**Comment by alanpaulkwan** [comment]
Oh - how do I compile a PR?

**Comment by Mytherin** [comment]
You can follow the instructions provided by Github underneath the PR to fetch the code. I have just merged it with master though, so you can rebuild master now as well.

**Comment by alanpaulkwan** [comment]
I am happy to report this is good now.
