### ISSUE TITLE
Lower bound and subtraction overflow bugs in hugeint_t

### ISSUE THREAD

**Issue by MingjiHan99** [duckdb/duckdb#1724]
**What does happen?**
1. The minimum value of `hugeint_t` defined in `src/common/limits.cpp` does not match the minimum value in https://duckdb.org/docs/sql/data_types/numeric.  
 
2.  `NumericLimits<hugeint_t>::Maximum() - 1` minus `-1` (both of them are `hugeint_t`) causes subtraction overflow.

**What should happen?**
Describe what you expect DuckDB to do instead.
Here is the existing definition of minimum value of hugeint_t.
```cpp
hugeint_t NumericLimits<hugeint_t>::Minimum() {
	hugeint_t result;
	result.lower = 1;
	result.upper = numeric_limits<int64_t>::lowest() + 1;
	return result;
}
```
The actual value is `-170141183460469231713240559642174554111` instead of `-170141183460469231731687303715884105727`
I think it might be :
```cpp
hugeint_t NumericLimits<hugeint_t>::Minimum() {
	hugeint_t result;
	result.lower = 1;
	result.upper = numeric_limits<int64_t>::lowest();
	return result;
}
```
2. The subtraction should not lead to overflow and return `NumericLimits<hugeint_t>::Maximum()`, that is `170141183460469231731687303715884105727`

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1.  Use `HugeInt::ToString( NumericLimits<hugeint_t>::Minimum()` to get the string of existing minimum value.
2. The bug could be reproduced by the following python code.

```python
import duckdb
cur = duckdb.connect(database=':memory:', read_only=False)
cur.execute("select 170141183460469231731687303715884105726 - (-1)").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Out of Range Error: Underflow in HUGEINT addition
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - DuckDB Version 22
 
**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Thanks for the report and in-depth investigation! I think you are correct, the +1 should not be there in the `upper` part of the hugeint. Could you perhaps send a PR with a fix for this, ideally combined with a SQL test that demonstrates the issue?

**Comment by MingjiHan99** [comment]
> Thanks for the report and in-depth investigation! I think you are correct, the +1 should not be there in the `upper` part of the hugeint. Could you perhaps send a PR with a fix for this, ideally combined with a SQL test that demonstrates the issue?

Thanks for the reply. 
I think the reason why the bug is implicit is that the minimum value of `hugeint_t` is only used in https://github.com/duckdb/duckdb/blob/master/src/common/operator/cast_operators.cpp#L1548. I tried many SQL statements to trigger the bug but failed.  
I am wondering if my second issue is a bug or a just feature.

**Comment by Mytherin** [comment]
Indeed it seems that this issue might not be triggerable from SQL, as the hugeint <> string conversion uses a separate code path, and the double <> hugeint conversion path has floating point accuracy problems that might make it difficult to come up with an exact test case. Could you just send a PR that corrects the minimum value?

**Comment by MingjiHan99** [comment]
For the second problem, the overflow detection in https://github.com/duckdb/duckdb/blob/master/src/common/types/hugeint.cpp#L349 looks strange. I am wondering why there is a `+1`. I think `lhs.upper >= (std::numeric_limits<int64_t>::max() + rhs.upper + underflow` is enough.

**Comment by MingjiHan99** [comment]
> That should be detectable using SQL. If that is wrong could you make a SQL test that shows that?

I use python API to show the bug.

```
import duckdb
cur = duckdb.connect(database=':memory:', read_only=False)
cur.execute("select 170141183460469231731687303715884105726 - (-1)").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Out of Range Error: Underflow in HUGEINT addition
```

**Comment by Mytherin** [comment]
Great! Thanks. Could you submit a PR that fixes this and adds the broken query to the hugeint arithmetic tests (`test/sql/types/hugeint/test_hugeint_arithmetic.test`)?
