### ISSUE TITLE
Fix parallelisation for filtered aggregates

### ISSUE THREAD

**Issue by hannesmuehleisen** [duckdb/duckdb#1725]
Currently, filtered aggregates crash in multi threaded builds (for vector size = 2 `test_filter_clause.test` triggers this) because of a global hash mal in the operator object that's modified concurrently in `Sink`. This should be fixed.

**Comment by hawkfish** [comment]
Ah, you had already figured this out.  Fix being tested in my fork.

**Comment by pdet** [comment]
Just double-checking because I was planning to check it this morning, from the messages it seems @hawkfish already had a go at this?

**Comment by hannesmuehleisen** [comment]
Yes he has fixed it already. The Duck never sleeps.

**Comment by hawkfish** [comment]
The Duck is cosmopolitan and international!

**Comment by hawkfish** [comment]
@pdet Yeah sorry, it was part of larger set of fixes, including making `Sink` `const`. Those will be coming shortly.
