### ISSUE TITLE
Python client using a (hidden) global default connection instead of using the last created one.

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#1732]
**What does happen?**
The problem is that the python client has this global default connection that exists in the background and is used before setting up a connection. From a user perspective, this is rather confusing and can cause undesired behaviors under the assumption you would be using the same connection.
Perhaps we should change that so that it instead uses the last-created connection or something instead of this hidden global connection.

**What should happen?**
Not have python use this global default connection.

**To Reproduce**
In this example we set the threads to 4 and force parallelism by using a connection from  duckdb.connect(), however if we don't use  duckdb_conn when creating the duckdb relation (last line), it will use the global default connection, that does not have the threads set to 4 or the force parallelism.
```python
duckdb_conn = duckdb.connect()
duckdb_conn.execute("PRAGMA threads=4")
duckdb_conn.execute("PRAGMA force_parallelism")
data = (pyarrow.array(np.random.randint(800, size=1000000), type=pyarrow.int32()))
tbl = pyarrow.Table.from_batches(pyarrow.Table.from_arrays([data],['a']).to_batches(10000))
rel = duckdb.from_arrow_table(tbl) 
```

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version: Latest

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by pdet** [comment]
One thing to keep in mind is that is also the problem of not having a connection yet at the beginning, which would probably end up using a hidden global connection.

e.g.,
``` python
import duckdb
arrow = duckdb.arrow('..')
con = duckdb.connect()
```

**Comment by hannesmuehleisen** [comment]
The default connection is there so you don't have to make one always. If you want to keep the context you should probably use duckdb_conn.from_arrow_table ? Or is this not intuitive?

**Comment by pdet** [comment]
I crossed paths with this when implementing the parallel arrow scans, and at least my immediate reaction was to debug the parallel framework of duckdb. Later realizing the connection I had created was not the same one used.
Even after knowing it, I made the same mistake when implementing the cardinality/progressive bars for Arrow, hehe.
Maybe I'm the only one that finds it non-intuitive, but I guess is worth bringing it up to be discussed.

**Comment by Mytherin** [comment]
Perhaps the first call to `duckdb.connect` can hand out the global connection?

**Comment by hannesmuehleisen** [comment]
if connect() does not have a file parameter that could work. otherwise we need to re-init anyway. seems a bit shaky

**Comment by hannesmuehleisen** [comment]
So after some discussions we think it would be best if the default connection is externally visible in the `duckdb.` namespace, for example as `duckdb.default_connection`. Then, the shorthand functions like `duckdb.from_arrow_table`  would get another parameter, `con`, and we make `duckdb.default_connection` the default value for that parameter. That way, what happens is transparent, and you can also run `PRAGMAs` on the default connection if you should choose to. In addition, we make the connection also visible as a property on relation objects. What do you think?

**Comment by pdet** [comment]
I think if it's visible and explicit it should already minimize this kind of user errors.
 I like it. I can have a go at this next week.
