### ISSUE TITLE
median function seems to be inaccurate

### ISSUE THREAD

**Issue by jangorecki** [duckdb/duckdb#1738]
**What does happen?**
Getting different results for median function comparing to data.table and pandas

duckdb 0.2.6
```
       task           data                   question        data.table                pandas            duckdb
 1: groupby G1_1e7_1e2_0_0 median v3 sd v3 by id4 id5 499920.1;288648.1  499920.14;288648.108   499674;288648.1
 2: groupby G1_1e7_1e1_0_0 median v3 sd v3 by id4 id5 4999.573;2887.162     4999.573;2887.162 4999.542;2887.162
 3: groupby G1_1e7_2e0_0_0 median v3 sd v3 by id4 id5 199.9701;115.4886        199.97;115.489   199.97;115.4886
 4: groupby G1_1e7_1e2_0_1 median v3 sd v3 by id4 id5 499920.1;288648.1  499920.14;288648.108   499674;288648.1
 5: groupby G1_1e7_1e2_5_0 median v3 sd v3 by id4 id5 460771.2;266006.9                  <NA> 460528.4;266006.9
 6: groupby G1_1e8_1e2_0_0 median v3 sd v3 by id4 id5   500020;288668.4 500019.998;288668.357 499995.4;288668.4
 7: groupby G1_1e8_1e1_0_0 median v3 sd v3 by id4 id5 4999.826;2886.819     4999.826;2886.819 4999.824;2886.819
 8: groupby G1_1e8_2e0_0_0 median v3 sd v3 by id4 id5 199.9981;115.4678       199.998;115.468 199.9981;115.4678
 9: groupby G1_1e8_1e2_0_1 median v3 sd v3 by id4 id5   500020;288668.4 500019.998;288668.357 499995.4;288668.4
```

**Comment by hannesmuehleisen** [comment]
There are many different definitions of the median. I suspect that that's where the (small) differences comes from.

**Comment by jangorecki** [comment]
The one we would like to test in benchmark is basically this
https://upload.wikimedia.org/wikipedia/commons/c/cf/Finding_the_median.png
Do I understand correctly that duckdb's median is an approximation of this median?

**Comment by Mytherin** [comment]
The median is not an approximation, but rather based on a discrete quantile. In your example it would return 6 in the first one, and 4 in the second one (rather than 4.5). What you are looking for is a continuous quantile. You could achieve this in DuckDB by using `quantile_cont(i, 0.5)`.

**Comment by jangorecki** [comment]
@Mytherin thanks, that solves my problem. I think it could be documented in https://duckdb.org/docs/sql/aggregates as I think most commonly user can assume median to be continuous quantile rather than discrete. As of now I don't see median function in documentation there.

**Comment by hawkfish** [comment]
After some discussion, we have decided to reopen this and convert `MEDIAN` to produce continuous values. In addition to matching the behaviour of `pandas` and `data.table` makes DuckDB compatible with other databases:

* [Oracle](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions086.htm) "`MEDIAN` is an inverse distribution function that assumes a *continuous* distribution model"
*
