### ISSUE TITLE
Missing libssl 1.0.0 dependency on Fedora 33+

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#1741]
**What does happen?**
DuckDB v0.2.6 fails to start on Fedora 33+ due to missing libssl 1.0.0 dependency (the system comes with libssl 1.1).

**What should happen?**
It should start.

**To Reproduce**

Start a Docker container:
```bash
docker run -it fedora:34 /bin/bash
```
Run the following commands:
```bash
yum install -y wget unzip
wget -q https://github.com/cwida/duckdb/releases/download/v0.2.6/duckdb_cli-linux-amd64.zip -O duckdb_cli-linux-amd64.zip
unzip duckdb_cli-linux-amd64.zip 
./duckdb 
```
Output:
```console
./duckdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Environment (please complete the following information):**
 - OS: Fedora 33+
 - DuckDB Version: 0.2.6

**Comment by szarnyasg** [comment]
The problems also pops up on Ubuntu 20.04:

```
docker run -it ubuntu:20.04 /bin/bash
```
```
apt update && apt install -y wget unzip
wget -q https://github.com/cwida/duckdb/releases/download/v0.2.6/duckdb_cli-linux-amd64.zip -O duckdb_cli-linux-amd64.zip
unzip duckdb_cli-linux-amd64.zip 
./duckdb
./duckdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

It can be worked around by [installing the package from 16.04](https://askubuntu.com/a/1264351/415610) but that's bad practice and should be avoided outside of throwaway (CI/Docker) environments.

**Comment by hannesmuehleisen** [comment]
Yes we are thinking to make the HTTPFs extension an external loadable extension so this does not blow up everywhere.

**Comment by szarnyasg** [comment]
@hannesmuehleisen This issue seems to have been resolved - the following test worked in both the `fedora:34` and the `ubuntu:20.04` Docker containers:
```
wget -q https://github.com/cwida/duckdb/releases/download/v0.2.7/duckdb_cli-linux-amd64.zip -O duckdb_cli-linux-amd64.zip
unzip duckdb_cli-linux-amd64.zip 
./duckdb
```

**Comment by belzecue** [comment]
I updated from duckdb_cli-linux-amd64 0.2.9, which worked fine, to duckdb_cli-linux-amd64 0.3.0 CLI and immediately got this error on Ubuntu 20.04.3.

./duckdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by koizumihiroo** [comment]
As I use v0.3.0 cli on Ubuntu 20.04.3 (WSL2, Windows 10), I resolved this error but not sure whether or not it is a good solution (for security reason)

- Add `deb http://security.ubuntu.com/ubuntu/xenial-security main` into `/etc/apt/sources.list` by sudo
- `sudo apt update && sudo apt install libssl1.0.0`

**Comment by darked89** [comment]
**re  `GLIBC_2.23' on Centos 7**

It has a rather old GLIBC version:

```
# 3.10.0-1160.11.1.el7.x86_64

ldd --version
ldd (GNU libc) 2.17
```

For that reason I am using a Singularity container.

**Comment by hannesmuehleisen** [comment]
Try the new release please it should no longer have the ssl dep

**Comment by szarnyasg** [comment]
The SSL dependency problem has been resolved but this revealed that the last version working on CentOS 7 (compiled from the binary package) was 0.2.3.

Since v0.2.4, the glibc versions do not align or the SSL dependency is missing:

```bash
for i in `seq 3 9`; do
    rm -f *.zip duckdb
    echo "v0.2.${i}"
    wget -q https://github.com/cwida/duckdb/releases/download/v0.2.${i}/duckdb_cli-linux-amd64.zip -O duckdb_cli-linux-amd64.zip && unzip duckdb_cli-linux-amd64.zip && ./duckdb
done
```

```
v0.2.3
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
0.2.4-dev0 436f6455f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D 
D 

v0.2.4
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./duckdb)
v0.2.5
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
v0.2.6
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
v0.2.7
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
v0.2.8
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
v0.2.9
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by hannesmuehleisen** [comment]
different issue?

**Comment by szarnyasg** [comment]
Yes. Maybe reopen #1708?
