### ISSUE TITLE
Nim API and difficulties calling `free`

### ISSUE THREAD

**Issue by sdmcallister** [duckdb/duckdb#1748]
Several months ago I reached out to the Nim community to see if anyone uses duckdb.  I got some very helpful responses and one member went as far as to generate a wrapper using Nimteropt based on the C api!   I was able to, after a bit of tweaking, use it on windows.  But I then ran into an issue where I was unable to successfully call `free` on variable created by `duckdb_value_varchar`.  When I didn't call free the script would compile and run, but I assumed I would be introducing memory leaks. In the end, I really couldn't tell what was causing the free issue. Unfortunately, my inexperience in C/C++ will hinder my ability to troubleshoot detailed issues like memory leaks. 

You can read more here: https://forum.nim-lang.org/t/7285

**Comment by sdmcallister** [comment]
Here is the relevant Nim code which is similar to the basic C example.  It doesn't crash if I omit free but it doesn't mean I not doing something wrong!

I notice in the C example `free` is called in a loop so I assume by multiple times you mean something like it being called twice in succession or something like that. Am I wrapping the right free function perhaps?

```
include duckdb_wrapper

# wraps free,strdup functions
proc free(p: pointer) {.importc: "free", header: "<stdlib.h>".} 
proc strdup(c: cstring) : cstring {.importc: "strdup", header: "<stdlib.h>".}

proc main() =
  var db: duckdb_database
  var con: duckdb_connection
  
  if (duckdb_open("test.db", db.addr) == DuckDBError):
    echo "Error"
  if (duckdb_connect(db, con.addr) == DuckDBError):
    echo "Error"
  
  if duckdb_query(con, "CREATE TABLE IF NOT EXISTS integers(i INTEGER, j INTEGER);", nil) == DuckDBError:
    echo "Error"
  if duckdb_query(con, "INSERT INTO integers VALUES (3, 4), (5, 6), (7, NULL);", nil) == DuckDBError:
    echo "Error"
  
  var res: duckdb_result
  if duckdb_query(con, "SELECT * FROM integers", addr(res)) == DuckDBError:
    echo "Error"
  
 
    var foo: cstring = "abcdefg"
    
    var bar = strdup(foo)
    
    free(bar) # works no prob.
    
    var val = duckdb_value_varchar(addr(res), 0.idx_t, 0.idx_t)
    
    free(val) # SIGSEGV: Illegal storage access.

  
  duckdb_destroy_result(addr(res))
  duckdb_disconnect(addr(con))
  duckdb_close(addr(db))

main()
```

**Comment by Mytherin** [comment]
> Here is the relevant Nim code which is similar to the basic C example. It doesn't crash if I omit free but it doesn't mean I not doing something wrong!

I am not familiar with Nim, but this seems to be correct. I have written this C program that mirrors yours, and this works correctly for me:

```c

	duckdb_database db;
	duckdb_connection con;
	duckdb_result res;

	auto rc = duckdb_open("test.db", &db);
	REQUIRE(rc != DuckDBError);

	rc = duckdb_connect(db, &con);
	REQUIRE(rc != DuckDBError);

	rc = duckdb_query(con, "CREATE TABLE IF NOT EXISTS integers(i INTEGER, j INTEGER);", nullptr);
	REQUIRE(rc != DuckDBError);

	rc = duckdb_query(con, "INSERT INTO integers VALUES (3, 4), (5, 6), (7, NULL);", nullptr);
	REQUIRE(rc != DuckDBError);

	rc = duckdb_query(con, "SELECT * FROM integers;", &res);
	REQUIRE(rc != DuckDBError);

	auto val = duckdb_value_varchar(&res, 0, 0);
	REQUIRE(string(val) == "3");
	free(val);

	duckdb_destroy_result(&res);
	duckdb_disconnect(&con);
	duckdb_close(&db);
```

If I comment out the free I get a memory leak, so it is required.

> I notice in the C example free is called in a loop so I assume by multiple times you mean something like it being called twice in succession or something like that. Am I wrapping the right free function perhaps?

 Indeed I mean free'ing the same value twice. Every single call to `duckdb_value_varchar` should be accompanied by one call to `free`.

**Comment by sdmcallister** [comment]
I don't see anything in the terminal related to the previous queries.  Thanks, for clarifications on free.  

In my example above I can't call free on the foo on cstring but I can on bar even though they are both cstrings.  

I found this commnet in another form thread regarding cstring:
>Because when you do var x: cstring = "1234" you get a pointer to static maybe read-only memory.

**Comment by Mytherin** [comment]
You should never call `free` on a statically allocated C string (e.g. a string that is allocated using a string constant, such as foo in your example). `free` should only be used for freeing memory that is explicitly allocated on the heap (using `malloc` and friends, `strdup` will use malloc internally).

**Comment by sdmcallister** [comment]
Yes, that makes sense to me. I guess I am just having difficulty with the Nim cstring `val` which is cstring returned from the wrapped function to be like cstring `bar` (which is allocated on the heap).

This line in my code returns a cstring: 
`var val = duckdb_value_varchar(addr(res), 0.idx_t, 0.idx_t)`

The function wrapper :
```
proc duckdb_value_varchar*(result: ptr duckdb_result; col: idx_t; row: idx_t): cstring {.
    importc, cdecl, impduckdbDyn.}
```

**Comment by Mytherin** [comment]
I would love to help you further, but I am not especially familiar with Nim, and I could not reproduce similar issues using the C API directly. Perhaps it is better to take this up with people more familiar with Nim itself.

**Comment by sdmcallister** [comment]
All good. The help has been appreciated. I think I just need to dig deeper into Nim to understand what is going on.

**Comment by danz68** [comment]
I am not sure if this is the case, but it will always be safer to invoke the expected dll "free" not the implemented host "free". Depending on implementation, malloc, free can have many nuances (different memory managers and such). Any structure that is created by the API (objectx_create), whose memory is not internally managed, requires a counterpart (objectx_free). Doing this will allow any language that can use the library to properly manage the allocated memory. 

The alternative would be to always provide results which need memory into the host allocated buffers. 
reqlen = duckdb_value_varchar_len(...);
host_buffer = make_or_use_some_valid_room(reqlen);
duckdb_value_varchar_len_get(..., buffer);

**Comment by sdmcallister** [comment]
@danz68  Thanks. I think Araq might have mentioned issues with different free implementations which, on the surface, sounds similar to what you are saying.

**Comment by Mytherin** [comment]
That is indeed a good point, and I can see how that can get nasty. I have pushed a PR (#1805) that adds a separate `duckdb_free` function to the C API. Could you have a look to see if using that instead of the system free fixes the issue?

**Comment by danz68** [comment]
It might worth to look into another perspective related to the added duckdb_free functionality. I am not sure about duckdb internals, but it is a common technique to use a transactional related memory pool that has a built in garbge collection. If this is the case (or it will be) a duckdb_malloc might worth be exposed as well. This way, the host application can benefit not only from the same garbage colector, but it will also be able to safely use host built structures as well with their own timing persistance (asynchronous host data processing and such, without the need of duplicating memory). 

It might not be the case now, but you never know when this can become handy in the future. As it is now, a simple wrap around dll-malloc is enough and is as simple as the duckdb_free C api extension.

**Comment by Mytherin** [comment]
Thanks for the additional feedback. I have added a corresponding `duckdb_malloc` function. For consistency this makes sense, and I agree it is nice to have in case we want to expand in this direction in the future.

**Comment by sdmcallister** [comment]
The `duckdb_free` seems to fix the issue on my end.
