### ISSUE TITLE
Memory usage/flush question

### ISSUE THREAD

**Issue by chybz** [duckdb/duckdb#1752]
Hi !

In an always running C++ application, data is appended to tables and at some point these tables are aggregated into another table, then results are flushed somewhere else. As soon as any of those tables is no longer needed, I issue either a `DROP` or `DELETE FROM`. No issue there, but RAM usage never decreases. Is there something I miss, like closing connections or calling an API or is this the expected behavior ?

Thanks for any input !

**Comment by hannesmuehleisen** [comment]
This seems related to #1099

**Comment by chybz** [comment]
Believe it or not, I really searched in existing issues. Sorry for the noise.
