### ISSUE TITLE
Cannot override JDBC fetch size with DuckDB

### ISSUE THREAD

**Issue by msumner91** [duckdb/duckdb#1754]
**Question:**
Is it possible for the DuckDB JDBC driver to honor a different fetch size value than the default 'hint'? 

I have tried overriding this at the Statement and ResultSet level - but it does not appear to honor this at the moment at least...

**Goal:**
Each call to resultSet.next() to pull back more than the default number of rows to improve performance when pulling large amounts of data out.

**Comment by hannesmuehleisen** [comment]
Not really, why would you like to modify this? DuckDB produces results in its internal chunk size, which cannot be changed at runtime, which is why this is not exported to the JDBC client.

**Comment by msumner91** [comment]
Hey -- thanks for the quick response...

So the reason is that when I consume results from the result set via something like:
while(resultSet.next()){
 // consume row(s)
}

If there are n rows in the result, currently I get n iterations of this loop (i.e. a chunk size of 1) which I imagine will not scale well for really large results vs. if we could batch these.

Is it possible to change this through configuration or other means if not at runtime?

**Comment by hannesmuehleisen** [comment]
Ah it will scale well, it has linear complexity after all. Plus the Java JIT will hopefully compile this loop.

**Comment by msumner91** [comment]
Fair enough - it was less of a concern on the JIT and more if we could make less trips to/from duckdb on disk by increasing this fetch size.

This is fairly normal for typical remote DB interaction it seems - though perhaps the penalty of single chunks isn't as large for local DBs?

E.g. [Oracle JDBC Docs](https://docs.oracle.com/cd/E18283_01/java.112/e16548/resltset.htm#insertedID4)

If that's not possible it's not an issue it was more of a question :)

**Comment by hannesmuehleisen** [comment]
There is no disk round trip for fetching from result sets

**Comment by msumner91** [comment]
Ok thanks for the info - will close this issue as I think it's better solved by changing the data model so it's one row per month in a blob
