### ISSUE TITLE
Segfault when using struct column and inserting null in it

### ISSUE THREAD

**Issue by ceymard** [duckdb/duckdb#1763]
**What does happen?**

```sql
create table test(s struct(a int));
insert into test(s) values (null);
```

I get `fish: “duckdb pouet.db” terminated by signal SIGSEGV (Address boundary error)`

**What should happen?**
A `null` value should be inserted into a new row.

**Environment (please complete the following information):**
 - OS: Ubuntu 21.04
 - DuckDB Version 0.2.6 and also current master

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Creating persistent tables with STRUCTs in them is not supported yet. Regardless, it should of course not crash.

**Comment by ceymard** [comment]
do you mean that for now structs and lists are only used in views ?

any idea when this feature will be available ?

**Comment by Mytherin** [comment]
I'm going to work on struct storage next.
