### ISSUE TITLE
Auto DataFrame scans give too much access to server data

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#1771]
**What does happen?**
When DuckDB is used in a server environment, the automatic Pandas DataFrame, csv, and parquet scan capabilities grant too much authority on the server to users and is a security risk. The read_csv and read_csv_auto, as well as the parquet reader also have the same issue.
There is a related issue here: [#823](https://github.com/duckdb/duckdb/pull/823) 

**What should happen?**
We would love a configuration option that is accessible from the Python API to disable these features. Our code should need to register a table or a file prior to DuckDB querying it so that we can appropriately control permission to files and DataFrames on the server. 

**To Reproduce**
Access a Pandas DataFrame without registering it.

**Environment (please complete the following information):**
 - OS: Windows
 - DuckDB Version 0.2.6

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Indeed I think its best if we expand/rename `config.enable_copy` to also apply to replacement scans

**Comment by Alex-Monahan** [comment]
Thank you! I think that would work well. A Pragma would also work if that is easier! The trick for us is just to be able to adjust that setting from Python.

**Comment by hannesmuehleisen** [comment]
if its a pragma a malicious actor could also re-enable ay

**Comment by Alex-Monahan** [comment]
Great point. Avoiding a Pragma would be better.

Thanks!
