### ISSUE TITLE
Unsigned integer types in Python API

### ISSUE THREAD

**Issue by cyvb** [duckdb/duckdb#1784]
**What does happen?**
Not implemented Error when using fetchone() and fetchall() after executing SELECT when there is NULL in the tuple (more than 1 element) returned

**What should happen?**
Return the correct data such as (1, None, 2)

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. Create a table where col_1 and col_2 are UINTERGER (I'm using UINTEGER in my own project, but I think it also happens in other data types)
    | col_1 | col_2 |
    | :-----: | :----: |
2. Insert 2 rows ```INSERT INTO table VALUES(100, DEFAULT)```, ```INSERT INTO table VALUES(DEFAULT, 100)```
    | col_1 | col_2 |
    | :-----: | :----: |
    | 100    |         |
    |           | 100  |
3. Retrieve a row in python like ```db.execute('SELECT * FROM table').fetchone()``` or a column ```db.execute('SELECT col_2 FROM table').fetchone()``` where the returned tuples are supposed to be  (100, None) and (None, 100)
    | col_1 | col_2 |
    | :-----: | :----: |
    | 100    |         |

    and

    | col_2 |
    | :----: |
    | 100   |
    |    -    |
4. The error appears
5. When the SELECT happens to return only 1 element like using ```db.execute('SELECT col_2 FROM table WHERE col_1=100').fetchone()```, which is NULL from the row 1 column 2, It correctly returns the tuple (None, )

**Environment (please complete the following information):**
 - OS: Windows 10 with Python 3.9.5
 - DuckDB Version 0.2.6 through pip

**Comment by hannesmuehleisen** [comment]
I am fairly certain this is due to the unsigned integer type

**Comment by cyvb** [comment]
Thanks a lot. I have tested retrieving the unsigned int and it failed. Look like it's certainly due to the unsigned int type. Now I'm converting them to BIGINT using CAST. Since Python 3 basically has only one integer type <int>. Is it possible to do this conversion in the python module? I think this is what has been done to other signed integer types in duckdb because BIGINT works fine. I'd like to help but I don't know where to start. Sorry.

**Comment by hannesmuehleisen** [comment]
Yes we should fix this

**Comment by pdet** [comment]
I think this can be closed.
@cyvb let me know if you still experience these issues  in the master :-)

**Comment by cyvb** [comment]
Thanks a lot!
