### ISSUE TITLE
Python | ALTER TABLE causes constraints lost in database file after exiting

### ISSUE THREAD

**Issue by cyvb** [duckdb/duckdb#1785]
**What does happen?**
In python, when I alter a table (I am adding columns to the table) the PRIMARY KEY constraint in the existing columns are lost, causing duplicated values when I insert new rows. The cli-tools, on the contrary, works correctly.

**What should happen?**
The constraints remains

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. Create a table ```db.execute('CREATE TABLE IF NOT EXISTS a(id INT PRIMARY KEY)')```
2. Insert a value ```db.execute('INSERT INTO a(id) VALUES (1)')```
    | id |
    | :-: |
    | 1  |
3. Add a new column ```db.execute('ALTER TABLE a ADD COLUMN c REAL')```
4. Insert the value above again ```db.execute('INSERT INTO a(id) VALUES (1)')```
5. Now there are two rows with id=1
    | id |  c   |
    | :-: |  :-:  |
    | 1  |   -  |
    | 1  |   -  |

**Environment (please complete the following information):**
 - OS: Windows 10 with Python 3.9.5
 - DuckDB Version 0.2.6

**Comment by Mytherin** [comment]
Thanks for the report! Testing this on the latest version of DuckDB it seems to me that the values are being correctly refused, however, no error seems to be reported. 

```python
import duckdb
db = duckdb.connect()
db.execute('CREATE TABLE IF NOT EXISTS a(id INT PRIMARY KEY)')
db.execute('INSERT INTO a(id) VALUES (1)')
db.execute('INSERT INTO a(id) VALUES (1)')
# RuntimeError: Constraint Error: duplicate key value violates primary key or unique constraint

db.execute('select * from a').fetchall()
# [(1,)]

db.execute('ALTER TABLE a ADD COLUMN c REAL')
db.execute('select * from a').fetchall()
# [(1, None)]

db.execute('INSERT INTO a(id) VALUES (1)')
# no error when there should be an error
# the row is not added though...

db.execute('select * from a').fetchall()
# [(1, None)]

# inserting a non-conflicting row does work
db.execute('INSERT INTO a(id) VALUES (2)')
db.execute('select * from a').fetchall()
# [(1, None), (2, None)]



```

**Comment by cyvb** [comment]
Thanks a lot for the reply. Sorry I didn't have time to view the update on the issue in the last few days.
I have figured out what caused the issue now.
It happens when you use a real database file rather than a in-memory one.

```
import duckdb
db = duckdb.connect('a.db')
db.execute('CREATE TABLE IF NOT EXISTS a(id INT PRIMARY KEY)')
db.execute('INSERT INTO a(id) VALUES (1)')
# Connect a db file. Create a table. Insert a value. Everything works fine.

db.execute('select * from a').fetchall()
# [(1,)]

db.execute('ALTER TABLE a ADD COLUMN c REAL')
db.execute('select * from a').fetchall()
# [(1, None)]

exit()
# Close python.

import duckdb
db = duckdb.connect('a.db')
# New python instance. Connect the db again.

db.execute('select * from a').fetchall()
# [(1, None)]
# What we inserted last time.

db.execute('INSERT INTO a(id) VALUES (1)')
db.execute('select * from a').fetchall()
# [(1, None), (1, None)]
# Now things go wrong. 2 rows, same value.
```

**Comment by hannes** [comment]
Still an issue
