### ISSUE TITLE
SQLite UDF API

### ISSUE THREAD

**Issue by tiagokepe** [duckdb/duckdb#1792]
Start the support for SQLite UDF API related to PR #712 and issue #471.
The first attempt should be implementing _sqlite3_create_function()_:
```
int sqlite3_create_function(
  sqlite3 *db,
  const char *zFunctionName,
  int nArg,
  int eTextRep,
  void *pApp,
  void (*xFunc)(sqlite3_context*,int,sqlite3_value**),
  void (*xStep)(sqlite3_context*,int,sqlite3_value**),
  void (*xFinal)(sqlite3_context*)
);
```
Some questions to answer/discuss:

1) How do we propagate the _sqlite3_context_ (first argument of the ***xFunc**)?
1.1) The UDFs in SQLite do not return values, whereas they internally consume the result values, adding them into the _sqlite3_context_, using functions such as _sqlite3_result_value()_, _sqlite3_result_text()_, and so.

The _sqlite3_context_ looks like:

```
struct sqlite3_context {
  Mem *pOut;              /* The return value is stored here */
  FuncDef *pFunc;         /* Pointer to function information */
  Mem *pMem;              /* Memory cell used to store aggregate context */
  Vdbe *pVdbe;            /* The VM that owns this context */
  int iOp;                /* Instruction number of OP_Function */
  int isError;            /* Error code returned by the function. */
  u8 skipFlag;            /* Skip accumulator loading if true */
  u8 argc;                /* Number of arguments */
  sqlite3_value *argv[1]; /* Argument set */
};
```
We can get the result values from `sqlite3_context->pOut`, but how to propagate such a context till the vector executors (_unary_executor.hpp, binary_executor.hpp  etc_)

2) We need to translate _sqlite3_value_ to _duckdb:Value_ . That translation might be easy, and maybe it already exists in the code.

3) As the result type is not defined in the **_xFunc_**, what should it be?  (_LogicalType::ANY, string_?)

**Comment by Mytherin** [comment]
Thanks for creating the issue! Good initial thoughts.

> We can get the result values from sqlite3_context->pOut, but how to propagate such a context till the vector executors (unary_executor.hpp, binary_executor.hpp etc)

I would recommend against using these vector executors, and instead writing a scalar function directly (see for example `src/function/scalar/string/regexp.cpp:142`). You could perform a loop over the input arguments by converting them to the canonical representation using `Vector::Orrify`, and then looping over the input vectors and invoking the UDF once for every input tuple. 

What is interesting is what the `sqlite3_context` is used for. Passing input types and arguments seems clear enough (`pOut, argv, argc, isError`). Certain properties seem to be tied to aggregates which we will not support in an initial pass (`skipFlag, pMem`). I am not sure about `iOp` and `pVdbe`, though.

Perhaps we could find some example sqlite3 functions and see how these different properties are used.

> We need to translate sqlite3_value to duckdb:Value . That translation might be easy, and maybe it already exists in the code.

Indeed! This doesn't exist yet, but should be relatively straightforward to add. There are a bunch of nop functions related `sqlite3_value` in `tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:1370` that should probably be filled out as well. 

> As the result type is not defined in the xFunc, what should it be? (LogicalType::ANY, string?)

I think VARCHAR is fine for now. We can't do much better than that, unless we add better support for a variable argument type. That is outside the scope of this issue though and can always be bolted onto the functions later later.

**Comment by hannes** [comment]
Closing since an initial implementation of this has been merged.
