### ISSUE TITLE
Segfault when querying parquet strings

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#1796]
DuckDB 0.2.6 reproducibly segfaults when querying a parquet file containing NULL strings from Python

I've attached [simple.parquet.zip](https://github.com/duckdb/duckdb/files/6543205/simple.parquet.zip), a minimal reproducing parquet file (wrapped in a zip so I can upload it to github). I created this parquet file using Pandas (using pyarrow 4.0.0 as the underlying parquet library) in the following way:
```python
import pandas as pd
df = pd.DataFrame(data={'col1': [None, None]}, dtype='string')
df.to_parquet('simple.parquet')
```

`parq` (part of https://pypi.org/project/parquet-tools/, which uses pyarrow under the hood) believes the schema of this parquet file is:
```
 # Schema
 <pyarrow._parquet.ParquetSchema object at 0x11d0a1f40>
required group field_id=0 schema {
  optional binary field_id=1 col1 (String);
}
```

The following is enough to segfault duckdb:
```python
import duckdb
con = duckdb.connect(database=':memory:')
con.execute("create view test as select * from parquet_scan('path/to/simple.parquet')")
con.execute("select * from test").fetchall()
```

I haven't tried other data types to see if they are also affected.

**Comment by hannesmuehleisen** [comment]
Will have a look thanks for sharing the file.

**Comment by hannesmuehleisen** [comment]
This looks like its fixed in the latest `master` branch. Could you perhaps try with that? (`pip install duckdb --pre`)

**Comment by zenazn** [comment]
I tried with `pip install duckdb==0.2.7.dev336` and it seems to work!

Does duckdb treat prereleases any differently than named releases? Would you recommend avoiding deploying pre-releases to production?

**Comment by hannesmuehleisen** [comment]
Well for now there is not that much of a difference of releases and whatever is in the master branch. We try to keep things stable in there.

**Comment by zenazn** [comment]
Thanks! Will give `dev336` a shot in production
