### ISSUE TITLE
Cannot open database in read-only directory (with R)

### ISSUE THREAD

**Issue by JenniferC-TEU** [duckdb/duckdb#1802]
**What does happen?**
I created a database in a directory. My colleague only has read-only access to this directory (controlled by our central IT) and is unable to open the database, even when setting read_only=TRUE.

It fails with error
```
Error in initialize(value, ...) : 
  duckdb_startup_R: Failed to open database
```

We believe this is happening because when opening a database a [dbname].tmp temporary directory is created in the folder with the database - and with read-only access, the user is not allowed to create this temporary directory.

**What should happen?**
The database should be able to open in read_only mode.

Looking at the C++ code it seems that there is an option to specify the location of the temporary directory that duckdb creates; unfortunately this configuration option is not available through the R wrapper.

This may be similar to https://github.com/duckdb/duckdb/issues/1538 ?

**To Reproduce**
Steps to reproduce the behavior.
1. Individual with write access to the directory creates database
```
library(DBI)
library(duckdb)
data(iris)
con <- dbConnect(duckdb::duckdb(), "directory/test.db", read_only=FALSE)
duckdb::dbWriteTable(con, name="iris", value=iris, 
                       overwrite=TRUE, append=FALSE, temporary=FALSE)
dbDisconnect(con, shutdown=TRUE)
```
2. Individual with read-only access to the directory attempts to open database
```
library(DBI)
library(duckdb)
con <- dbConnect(duckdb::duckdb(), "directory/test.db", read_only=TRUE)
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - DuckDB Version: 0.2.6
 - DBI Version: 1.1

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- I am unable to test both sides myself, as we are unable to set directories to read-only in Windows. I did the read-write access part and my colleague tested the read-only part!
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds
- Sorry, I can't get colleague to use custom builds!

**Comment by hannesmuehleisen** [comment]
Indeed we should export that setting to the R and Python clients.

**Comment by Mytherin** [comment]
This should be resolved in the master branch now, as the temporary directory is only created when required and can be set at run-time using `PRAGMA temp_directory='/path/to/my/tempdir.tmp'`.
