### ISSUE TITLE
windows compile syntax issue

### ISSUE THREAD

**Issue by sdmcallister** [duckdb/duckdb#1806]
On windows 10. Using VS 2019 developer cmd prompt. GNU Make 3.81 and CMake 3.17.20032601-MSVC_2

Not sure if this is bug or an issue with my set up. 

Error:
```
\duckdb>make
mkdir -p build/release && \
        cd build/release && \
        cmake       -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Release ../.. && \
        cmake --build .
The syntax of the command is incorrect.
make: *** [release] Error 1
```

**Comment by hannesmuehleisen** [comment]
This is not really supposed to work on Windows. To build there, you may check our CI config here: https://github.com/duckdb/duckdb/blob/master/.github/workflows/main.yml#L100

For example,
````
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64
cmake --build . --config Release<br class="Apple-interchange-newline">
````

should work on Windows, too
