### ISSUE TITLE
Implement GroupJoin

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1810]
Once we have unified the hash tables for joins and aggregation, we will be able to implement the [`GroupJoin`](http://www.vldb.org/pvldb/vol4/p843-moerkotte.pdf) physical operator by storing aggregates in the join hash table.

**Comment by hannesmuehleisen** [comment]
Funny, saw that talk at my very first conference, in Seattle no less, and immediately liked Prof. Moerkotte a lot...

**Comment by hawkfish** [comment]
It's funny how long some of this stuff sits on the shelf. Having done some work on temporal analytics at Tableau, I'm always surprised that no one seems to implement [`IEJoin`](http://www.vldb.org/pvldb/vol8/p2074-khayyat.pdf) or [planar sweep joins](http://vldb.org/pvldb/vol10/p1346-bouros.pdf). When you are [intersecting temporal ranges](https://www.youtube.com/watch?v=iwgxgdYiGd4) these are the joins you want!

**Comment by hungptit** [comment]
@hawkfish Do you mind if I can email you to get more detail information for the above comment?

**Comment by hawkfish** [comment]
> @hawkfish Do you mind if I can email you to get more detail information for the above comment?

@hungptit Sure, but I'd rather not post it in a public forum. You can message me on LI maybe?

**Comment by hungptit** [comment]
@hawkfish What is LI?

**Comment by hawkfish** [comment]
Sorry LinkedIn
