### ISSUE TITLE
SQL AND/OR logic error with LIKE string matching

### ISSUE THREAD

**Issue by dforsber** [duckdb/duckdb#1812]
**What does happen?**

```
SELECT COUNT(*) FROM table -- 117
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' -- 117
SELECT COUNT(*) FROM table WHERE url LIKE '%about%' AND url LIKE '%we%' -- 3
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' OR (url LIKE '%about%' AND url LIKE '%we%') -- 3 BUG
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' OR ( url LIKE '%we%' AND url LIKE '%about%' ) -- 3 BUG
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' OR ( url LIKE '%w%' AND url LIKE '%about%' ) -- 117
```

**What should happen?**

```
SELECT COUNT(*) FROM table -- 117
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' -- 117
SELECT COUNT(*) FROM table WHERE url LIKE '%about%' AND url LIKE '%we%' -- 3
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' OR (url LIKE '%about%' AND url LIKE '%we%') -- 117 CORRECT
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' OR ( url LIKE '%we%' AND url LIKE '%about%' ) -- 117 CORRECT
SELECT COUNT(*) FROM table WHERE url LIKE '%we%' OR ( url LIKE '%w%' AND url LIKE '%about%' ) -- 117
```

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. See the queries above

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version: `https://github.com/cwida/duckdb/archive/7c1a2f2867dfe5b02717e7bd7cf7ed46fbe08a34.tar.gz` (quite recent/latest master)

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by dforsber** [comment]
May have relation to this https://github.com/duckdb/duckdb/issues/1391

**Comment by dforsber** [comment]
Not that I know anything about the internals - but it looks like it would take the already calculated "index" for "%we%" then applies the AND "%about%" on it and gives the results (3). Whilst, instead it should honor the OR and calculate them separately (separate "index" for "%we%" for both queries on the sides of the OR statement).

**Comment by hannesmuehleisen** [comment]
Thanks, still missing whatever is in `table` here. Could you try to share a file that demonstrates the issue? Does this also happen with data in regular tables?

**Comment by dforsber** [comment]
It actually does not have anything to do with Parquet.

```
CREATE TABLE t (str VARCHAR);
INSERT INTO t VALUES ('hello1'), ('hello2'), ('hello3'), ('world1'), ('world2'), ('world3');
SELECT COUNT(*) FROM t WHERE str LIKE '%o%'; -- 6
SELECT COUNT(*) FROM t WHERE str LIKE '%rld%'; -- 3
SELECT COUNT(*) FROM t WHERE str LIKE '%o%' OR (str LIKE '%o%' AND str LIKE '%rld%'); -- 3 BUG, should still be 6
```

**Comment by Mytherin** [comment]
Could you verify that #1823 fixed this issue?

**Comment by dforsber** [comment]
> Could you verify that #1823 fixed this issue?

Yes, the issue is fixed! Thank you 👍🏻
