### ISSUE TITLE
"Test parallel dependencies in multiple connections" intermittent crash

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1817]
**What does happen?**
The named unit test can crash

**What should happen?**
Not crash...

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. `./build/relassert/test/unittest "Test parallel dependencies in multiple connections"
2. Repeat until you get an address sanitiser error, 

**Environment (please complete the following information):**
 - OS: OSX
 - DuckDB Version: HEAD

**Before submitting**
- [ x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

I was able to reproduce it once or twice under the Xcode debugger but then it stopped happening. One side of the crash was [here](https://github.com/duckdb/duckdb/blob/39da8ef39b0c530422f6cdbb1fb3b5787d6a0dd2/src/catalog/catalog_set.cpp#L216) and didn't seem to protected by the [mutex](https://github.com/duckdb/duckdb/blob/39da8ef39b0c530422f6cdbb1fb3b5787d6a0dd2/src/transaction/transaction_manager.cpp#L174) on another thread. There was a third thread active but I didn't get the line.

From the CL I got this message:
```
libc++abi.dylib: terminating with uncaught exception of type duckdb::InternalException: INTERNAL Error: Assertion triggered in file "/Users/hawkfish/Documents/Development/duckdb/src/catalog/dependency_manager.cpp" on line 111: entry->second.find(object) != entry->second.end()
```shell

Wish I had a bit more but it stopped happening.

**Comment by Mytherin** [comment]
I have fixed some thread sanitizer issues in this test in #1808, so there is a chance that this problem has been fixed.

**Comment by hawkfish** [comment]
I haven't seen it lately so I will close it.
