### ISSUE TITLE
date difference calculation wrong if dates are in different year

### ISSUE THREAD

**Issue by dzhang** [duckdb/duckdb#1825]
Hi

I tried following code to calculate the difference between two dates
sql = "select date_part('day', age(date '2018-01-17', date '2017-11-15'))"
duckdb.query(sql)

it returns 2 instead of 63.

I also tried on other dates, this error seems only happens on dates in different year.

Thanks
Dong

**Comment by Mytherin** [comment]
Thanks for the report!

This is not a bug, `age` returns an interval, e.g.:

```sql
D select age(date '2018-01-17', date '2017-11-15');
┌─────────────────────────────────────────────────────────┐
│ age(CAST(2018-01-17 AS DATE), CAST(2017-11-15 AS DATE)) │
├─────────────────────────────────────────────────────────┤
│ 2 months 2 days                                         │
└─────────────────────────────────────────────────────────┘
```

`date_part` explicitly extracts *only* the days portion of the interval, which is 2 days. This matches the behavior in Postgres.

If you want to find out the *days* between two dates, you can simply subtract them:

```sql
D select date '2018-01-17' - date '2017-11-15';
┌─────────────────────────────────────────────────────┐
│ CAST(2018-01-17 AS DATE) - CAST(2017-11-15 AS DATE) │
├─────────────────────────────────────────────────────┤
│ 63                                                  │
└─────────────────────────────────────────────────────┘
```

**Comment by dzhang** [comment]
thanks, that worked.
