### ISSUE TITLE
Arrow dataset + aggregation + multithreading

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#1835]
**What does happen?**
I'm testing out the new abilities to query an Arrow source from DuckDB. Things work well for Tables and record batches, however I've found that with datasets, when using aggregations, with multithreading I get hangs.

The following will (almost always) hang on the last line:
```
ds <- arrow::open_dataset("userdata1.parquet")
duckdb::duckdb_register_arrow(con, "mydatasetreader", ds)
dbExecute(con, "PRAGMA threads=4")
dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
```

I've noticed that this will _sometimes_ succeed (with a correct result), though when it hangs it hangs forever. I've tried smaller numbers of threads (2, 3) and those seem to work slightly more frequently — 1 thread always works. Higher numbers of threads (e.g. 8) always hang. 

I'm happy to dig more / debug on my end if there are obvious places I should look.

**What should happen?**
Return the result of the query without hanging.

**To Reproduce**
This code (in the style of / could be inserted into duckdb/tools/rpkg/tests/testthat/test_register_arrow.R)
```
test_that("duckdb_register_arrow() works with datasets", {
    skip_on_os("windows")
    skip_if_not_installed("arrow", "4.0.1")
    con <- dbConnect(duckdb::duckdb())

    # Registering a dataset + aggregation
    ds <- arrow::open_dataset("userdata1.parquet")
    duckdb::duckdb_register_arrow(con, "mydatasetreader", ds)
    res1 <- dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
    res2 <- dbGetQuery(con, "SELECT count(*) FROM parquet_scan('userdata1.parquet')")
    expect_true(identical(res1, res2))
    # we can read with > 3 cores
    dbExecute(con, "PRAGMA threads=4")
    res3 <- dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
    expect_true(identical(res2, res3))
    duckdb::duckdb_unregister_arrow(con, "mydatasetreader")

    dbDisconnect(con, shutdown = T)
})
```

**Environment (please complete the following information):**
 - OS: macOS 11.3.1 on a Mac Pro 6-core Xeon E5
 - DuckDB Version: the `master` branch from today

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by pdet** [comment]
Thanks for opening the issue @jonkeane. I'll have a look at this soon!

**Comment by pdet** [comment]
I'm actually surprised this somewhat works from R land.

On Python land, we explicitly only accept table objects, so the following code will give a runtime error.

```python 
userdata_parquet_dataset= pyarrow.dataset.dataset(parquet_filename, format="parquet")
duckdb_conn.register_arrow("arrow_dataset", userdata_parquet_dataset)
```

I'm happy to support datasets though, but as a quick measure, I think a similar check should be performed on R-land until this is properly implemented (Maybe @hannesmuehleisen can add this?). Also would avoid the reading of unexpected objects.

```cpp
auto py_object_type = string(py::str(table.get_type().attr("__name__")));
if (table.is_none() || py_object_type != "Table" ) {
	throw std::runtime_error("Only arrow tables are supported");
}
```

Related to the support of the datasets, we could either internally transform them to arrow_tables, with an extra parameter of the partition number, which is necessary for parallelism, since our current implementation only parallelizes partitions.

**Comment by jonkeane** [comment]
Interesting. From what I understand both datasets and tables in R land are having recordbatchreaders exposed + exported. I believe the interface for those two is the same or similar enough, but I can dig more and confirm that.

I looked through the duckdb python code, but couldn't find this right away: what scanner are you using on the Python side? I don't see a recordbatchreader, but I might be looking in the wrong place!

**Comment by nealrichardson** [comment]
You don't want to convert a Dataset to a Table: Datasets must not be assumed to fit into memory, as a Table does. Jon is right though, at least in R you aren't actually consuming a Dataset or a Table, you're consuming an ArrowArrayStream struct in both cases.

And if it works to query a dataset with 1 or few threads, then it's not a problem with Dataset per se.
