### ISSUE TITLE
User-Defined Types

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1839]
The SQL standard defines user-defined types, which are mostly aliases for named structs, e.g.:

```sql
CREATE TYPE compfoo AS (f1 int, f2 text);
CREATE TYPE point AS (x int, y int);
```

See the [postgres page](https://www.postgresql.org/docs/current/sql-createtype.html) for more details. As we support named structs, supporting these is not that much more work and seems like a good idea.

Postgres also supports ENUM types, which we may want to add support for as well for performance reasons, e.g.:

```sql
CREATE TYPE bug_status AS ENUM ('new', 'open', 'closed');
```

**Comment by hannes** [comment]
This is supported now
