### ISSUE TITLE
Assertion failure in ART Big index update with vector size 2

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1844]
**What does happen?**
While investigating a [different failure](https://github.com/hawkfish/duckdb/runs/2757930719?check_suite_focus=true#logs), I noticed that `test/sql/index/art/test_art_big_update.test` has an
[assert failure](https://github.com/duckdb/duckdb/blob/8045e42405bf5c5f2a995b186e9a8390cc69a79c/src/storage/data_table.cpp#L718)

**What should happen?**
No assertion.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. build debug with `SVS == 2`
2. `./build/debug/test/unittest test/sql/index/art/test_art_big_update.test`

**Environment (please complete the following information):**
 - OS: OSX, 
 - DuckDB Version master 2021-06-06

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hawkfish** [comment]
I should add that the assertion is valid - we are attempting to read element ~243 of 2 element array.

**Comment by pdet** [comment]
I'll check that

**Comment by pdet** [comment]
I think this can be closed
