### ISSUE TITLE
Cursor doesn't see views

### ISSUE THREAD

**Issue by korommatyi** [duckdb/duckdb#1848]
**What does happen?**
When I create a view by registering a pandas dataframe, I can query that through the connection but not through the cursor.

**What should happen?**
View is visible through the cursor.

**To Reproduce**
```
In [1]: import pandas as pd

In [2]: import duckdb

In [3]: df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': ['1', '2', '3', '4']})

In [4]: con = duckdb.connect(database=':memory:')

In [5]: con.register('data', df)
Out[5]: <duckdb.DuckDBPyConnection at 0x10b0ab1f0>

In [6]: q = 'select a from data'

In [7]: con.execute(q)
Out[7]: <duckdb.DuckDBPyConnection at 0x10b0ab1f0>

In [8]: con.cursor().execute(q)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-d9a1058aae9c> in <module>
----> 1 con.cursor().execute(q)

RuntimeError: Catalog Error: Table with name data does not exist!
LINE 1: select a from data
```

**Environment (please complete the following information):**
 - OS: MacOS
 - 0.2.6

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
The `cursor` call there is completely optional. If you register the view after creating the cursor or directly query the connection it should work. Internally, cursor() creates a new connection, and we mostly have it to be compatible with the - questionable - python DB API.

**Comment by korommatyi** [comment]
Hm, I see. The problem is that I don't use the connection directly, instead I pass it to `pandas.read_sql` and that uses the `cursor`.
