### ISSUE TITLE
Keep row id of last inserted row in connection context

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#185]
to support something like `sqlite3_last_insert_rowid`

**Comment by Mytherin** [comment]
For this I would propose the following solution: the PhysicalInsert returns the set of row ids of all the rows that are inserted. The SQLite API can then use the return value of INSERT statements to keep track of the last inserted row id. This is a bit more general as it also supports inserts of multiple rows at the same time.

**Comment by fsaintjacques** [comment]
`O(|inserted rows|)` versus` O(1)` memory usage, think about large batch inserts (which a lot of OLAP application do). Maybe toggle this via a runtime flag?

**Comment by wangfenjin** [comment]
Any update on this issue? How can we get the rowid now?

**Comment by erezsh** [comment]
I am also interested if this feature is planned for anytime soon.

Usual solutions are:

- get_last_row_id() function, like in Sqlite
- INSERT .. RETURNING syntax, like in Postgres

**Comment by hannes** [comment]
See #3191 and #3244
