### ISSUE TITLE
Parquet file with compression created by `parquetjs` cannot be read

### ISSUE THREAD

**Issue by rprovodenko** [duckdb/duckdb#1870]
**What does happen?**
When attempting to query a parquet file with compression, the following error occurs:
```
D SELECT * FROM parquet_scan(<file>);
Error: Unhandled exception in Fetch
```
The file has been tested in other readers, it's valid.
**What should happen?**
Rows to be returned, no error raised.

**To Reproduce**
Run the query above on the files I have emailed (they all give exceptions).

**Environment (please complete the following information):**
 - OS: MacOS
 - DuckDB Version: 0.2.7

**Comment by hannesmuehleisen** [comment]
[test_parquet_files.zip](https://github.com/duckdb/duckdb/files/6682930/test_parquet_files.zip)

**Comment by hannesmuehleisen** [comment]
Which software created those files? To me their contents look quite fishy, could be some other tools are more lenient there.

**Comment by hannesmuehleisen** [comment]
To be more precise, there are compressed blobs in the files but the parquet metadata over-reports the compressed length which trips the decompressors.

**Comment by rostislavdeepcrawl** [comment]
> Which software created those files? To me their contents look quite fishy, could be some other tools are more lenient there.

https://www.npmjs.com/package/parquetjs
