### ISSUE TITLE
Compressed Vector Tests

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1871]
Now that we are moving towards compressed storage and more complex nested types, I believe it is a good idea to add more tests for various compressed vector representations. The problem is that generating these is not always obvious.

My suggestion for this is to add a series of table functions that specifically generate vectors with different vector types. For example:

```sql
-- generates the values [0...999] in different formats
SELECT flat, dictionary, sequence, rle FROM compressed_range(1000);

-- generates a series of constant vectors with the specified value
SELECT constant FROM compressed_repeat(0, 1000);

-- generates 5 lists with the values [0...999] spread between them uniformly, i.e. list 1 has entries [0...200], list 2 has entries [200..400]
SELECT flat, dictionary, sequence, rle FROM compressed_list(5, 1000);
```

These could be located in a separate `test` extension so we don't need to ship them, as they don't have any point besides testing functionality.

**Comment by hannesmuehleisen** [comment]
We can also have an op that we push for tests that converts to one particular type at boundaries and re-run test sets like that
