### ISSUE TITLE
JOIN on register tables skip duplicate columns

### ISSUE THREAD

**Issue by abionescu** [duckdb/duckdb#1874]
**What does happen?**
When tables registered (from Pandas) are joined duplicate columns are removed.

**What should happen?**
Return all columns (as it's the case with tables created in DuckDB), eventually prefix common columns with source table name.

**To Reproduce**
```
df1 = pd.DataFrame(data={'a': [1], 'b': [1]})
conn.register('df1', df1)
df2 = pd.DataFrame(data={'c': [1], 'b': ['test']})
conn.register('df2', df2)
conn.execute('select * from df1 JOIN df2 on df1.a = df2.c').fetchdf()
```
 the result has only 3 columns:
|a|b|c|
|-|-|-|
|1|test|1|

when the same select is issued against tables created in DuckDB the result has 4 columns:
|a|b|c|b|
|-|-|-|-|
|1|1|1|test|

**Environment (please complete the following information):**
 - OS: Win10 64bit
 - Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] on win32
 - DuckDB Version 0.2.7

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by abionescu** [comment]
actually the issue occurs in **.fetchdf()** only, executing **.fetchall()** returns correct result.

**Comment by Tishj** [comment]
This issue appears to be fixed?
Walking through the steps provided in the description resulted in this:
```
   a  b  c   b_2
0  1  1  1  test
```
(with `df = duckdb.default_connection.execute('select * from df1 JOIN df2 on df1.a = df2.c').fetchdf()`)
