### ISSUE TITLE
Cannot not build without shared library

### ISSUE THREAD

**Issue by calvin2021y** [duckdb/duckdb#1882]
**What does happen?**
try build with -DBUILD_SHARED_LIBS=OFF -DSTATIC_LIBCPP=ON,  stop at "Linking CXX shared library libduckdb.so"

**What should happen?**
set BUILD_SHARED_LIBS=OFF should not build libduckdb.so.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1.  mkdir build && cd build
2. cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_SHELL=OFF -DBUILD_TESTING=OFF -DBUILD_UNITTESTS=OFF -DEXPORT_DLL_SYMBOLS=OFF -DSTATIC_LIBCPP=ON -DENABLE_SANITIZER=OFF -DENABLE_UBSAN=OFF -DASSERT_EXCEPTION=OFF .. -LA
3. make

**Environment (please complete the following information):**
 - OS: linux
 - DuckDB v0.2.7

**Comment by hannesmuehleisen** [comment]
Why do you want to disable building the shared libraries in the first place? But in order to disable this, you would add the `BUILD_SHARED_LIBS`  flag to the CMake config. Happy to review a PR.
