### ISSUE TITLE
INTERVAL not working as expected across day boundry

### ISSUE THREAD

**Issue by lighthill** [duckdb/duckdb#1890]
When subtracting x minutes from a timestamp, the wrong timestamp occurs if the new timestamp crosses a day boundary (midnight).

e.g. _SELECT TIMESTAMP '2000-01-01 00:00:00' - INTERVAL 1 MINUTE_ 
should return '1999-12-31 23:59:00', instead it returns '2000-01-01 23:59:00'

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm this is incorrect. I will have a look.
