### ISSUE TITLE
Can't connect to existing database with RStudio

### ISSUE THREAD

**Issue by tom-christie** [duckdb/duckdb#1898]
**What does happen?**
I can't connect to an existing database using R.  When I try, I get this error:

    > conn <- dbConnect(duckdb::duckdb(), "~/test.duckdb")
    Error in l$contains : $ operator is invalid for atomic vectors

**What should happen?**
`conn` should be an object I can use to execute queries...but the error causes no `conn` object to be created.

**To Reproduce**
```
    conn <- dbConnect(duckdb::duckdb(), "~/test.duckdb")
    df <- data.frame(a=c(1,2,3),
                     b=c('1','2','3'))
    dbWriteTable(conn, "df", df)
    dbDisconnect(conn, shutdown=TRUE) 
    rm(conn)
    conn <- dbConnect(duckdb::duckdb(), "~/test.duckdb")
```

**Environment (please complete the following information):**
 - OS: MacOS 10.15.7
 - DuckDB Version: 0.2.7
 - R Version: 4.0.4

**Comment by hannesmuehleisen** [comment]
This works fine for me, could you share some additional context please? What happens if you use a different file name?

**Comment by tom-christie** [comment]
Interesting, I tried in R (rather than RStudio) and it works. Sometimes in RStudio when I try the `dbDisconnect` line, I get a 'R code execution error'.  When I replace that line with `duckdb::duckdb_shutdown(conn@driver)`, it seems to behave better. I'm wondering if there is an issue with the dbDisconnect.  I'll close for now, but may re-open if I learn more.

**Comment by tom-christie** [comment]
On my machine, the issue happens consistently from within RStudio, but not running R from terminal.

**Comment by hannesmuehleisen** [comment]
Its likely related to the Rstudio connection pane integration that we have

**Comment by tom-christie** [comment]
Is there a way to turn off the connection pane integration?

**Comment by hannesmuehleisen** [comment]
looking into this now

**Comment by hannesmuehleisen** [comment]
This is being worked on in #2044
