### ISSUE TITLE
Support DATE and TIMESTAMP in nodejs

### ISSUE THREAD

**Issue by tanin47** [duckdb/duckdb#1900]
**What does happen?**
A short, clear and concise description of what the bug is.

Nodejs doesn't support DATE and TIMESTAMP as seen here: https://github.com/duckdb/duckdb/blob/08277d7a604c9329df049244c95d2a81b8872e05/tools/nodejs/src/statement.cpp#L165

**What should happen?**
Describe what you expect DuckDB to do instead.

It should output the javascript's Date.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. `SELECT DATE '2020-01-01'` using Nodejs' binding.

**Environment (please complete the following information):**
 - DuckDB Version: 0.2.7

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

The code doesn't support DATE and TIMESTAMP, so I haven't tested on the latest master branch. But it shouldn't work.

Thank you!

**Comment by hawkfish** [comment]
Creating JS UTC dates/timestamps can be perilous if you are [not careful](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCFullYear):

>  If you do not specify the `monthValue` and `dayValue` parameters, the values returned from the `getUTCMonth()` and `getUTCDate()` methods are used.

In other words, the result will depend on the current date...

**Comment by hawkfish** [comment]
@tanin47 Does this work for you now?
