### ISSUE TITLE
https://duckdb-node.s3.amazonaws.com/duckdb-v0.2.6-node-v83-win32-x64.tar.gz returns access denied

### ISSUE THREAD

**Issue by tanin47** [duckdb/duckdb#1903]
**What does happen?**
A short, clear and concise description of what the bug is.

The prebuilt binaries don't exist. I'm not sure if you intend for them to exist.

**Comment by hannesmuehleisen** [comment]
I'm not sure they should exist either. Could you describe the steps that led you to this problem please?

**Comment by tanin47** [comment]
I ran "yarn install" on Windows on a project with duckdb as a dependency.

It tried to download the prebuilt binary.

According to the config under tools/nodejs, it seems it is intended to be published on AWS

**Comment by tanin47** [comment]
Here's the said config: https://github.com/duckdb/duckdb/blob/master/tools/nodejs/package.json#L15

**Comment by hannesmuehleisen** [comment]
Indeed it looks like we are not uploading windows binaries at this point. We should probably fix that.

**Comment by tanin47** [comment]
I was trying to build duckdb in CircleCI's Windows (through yarn install), and it failed because CreateDirectoryA didn't exist.

But CreateDirectoryA should have been included in fileapi.h, which should have existed in any Window.

Do you have an idea how to fix this?

Today I will try to build it on my window laptop instead.

**Comment by hannes** [comment]
This is most likely fixed.

**Comment by chrisbrain** [comment]
Is this really fixed? I am getting the following when running `npm install duckdb` on Windows:

`
485 error node-pre-gyp http GET https://duckdb-node.s3.amazonaws.com/duckdb-v0.4.0-node-v102-win32-x64.tar.gz
485 error node-pre-gyp ERR! install response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.4.0-node-v102-win32-x64.tar.gz
485 error node-pre-gyp WARN Pre-built binaries not installable for duckdb@0.4.0 and node@17.0.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
485 error node-pre-gyp WARN Hit error response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.4.0-node-v102-win32-x64.tar.gz
`

**Comment by Mause** [comment]
> Is this really fixed? I am getting the following when running `npm install duckdb` on Windows:
> 
> ```
> 485 error node-pre-gyp http GET https://duckdb-node.s3.amazonaws.com/duckdb-v0.4.0-node-v102-win32-x64.tar.gz
> 485 error node-pre-gyp ERR! install response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.4.0-node-v102-win32-x64.tar.gz
> 485 error node-pre-gyp WARN Pre-built binaries not installable for duckdb@0.4.0 and node@17.0.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
> 485 error node-pre-gyp WARN Hit error response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.4.0-node-v102-win32-x64.tar.gz
> ```

Looks like we don't prebuild for NodeJS 17 on Windows yet

**Comment by chrisbrain** [comment]
Ah thanks - I get the same with node 18 by the way but just tried node 16 and that works so at least I have a way forward for now.

**Comment by chrisbrain** [comment]
@Mause Should this be fixed now for NodeJS17/18 with duckdb npm package 0.4.0? As I am still seeing same.

Maybe we need to wait for next release?

**Comment by Mause** [comment]
@chrisbrain which version are you trying to install?

**Comment by chrisbrain** [comment]
@Mause Just tried both 0.4.0 and still failing with NodeJS 17 and 18 for me.

**Comment by chrisbrain** [comment]
@Mause OK thanks for confirming.

**Comment by cookiejest** [comment]
whats the normal native compilation time for duckdb? these binaries would be really helpful

**Comment by aryzing** [comment]
Seems this is still an issue. Recently ran `npm i` on a project with duckdb, which errored with:

```
npm error node-pre-gyp http GET https://duckdb-node.s3.amazonaws.com/duckdb-v0.9.2-node-v127-linux-x64.tar.gz
npm error node-pre-gyp ERR! install response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.9.2-node-v127-linux-x64.tar.gz 
```
