### ISSUE TITLE
Cannot "yarn install" on Windows; Fail with  "error C2039: 'RemoveDirectoryA': is not a member"

### ISSUE THREAD

**Issue by tanin47** [duckdb/duckdb#1908]
**What does happen?**
A short, clear and concise description of what the bug is.

When running "yarn install" on a project that depends on duckdb on Windows, it seems duckdb fails to compile on Windows.

Here are the error messages:

```
error C2039: 'CreateDirectoryA': is not a member of 'duckdb::FileSystem' 
error C2039: 'RemoveDirectoryA': is not a member of 'duckdb::FileSystem'
```

CreateDirectoryA and RemoveDirectoryA are actually members of fileapi.h. Not sure why it cannot find those methods.

Then, there are a lot of warnings like below:

```
 warning C4273: 'duckdb::StreamQueryResult::FetchRaw': inconsistent dll linkage
```

**What should happen?**
Describe what you expect DuckDB to do instead.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. Make a node project whose package.json contains duckdb as a dependency
2. Run "yarn install"

**Environment (please complete the following information):**
 - OS: Windows 10, Surface
 - DuckDB Version: 0.2.7

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds --- not yet

**Comment by tanin47** [comment]
Interestingly, 0.2.3 builds successfully but 0.2.4 doesn't (fail with the above exception).

https://github.com/duckdb/duckdb/pull/1454/files has something to do with it. I'm not familiar with node-pre-gyp, but it seems mapbox's node-pre-gyp has some difference.

**Comment by marius-klimantavicius** [comment]
I am getting the same error while trying to compile amalgamation (v0.2.7) in Visual Studio 2019:
```
'CreateDirectoryA': is not a member of 'duckdb::FileSystem'
'RemoveDirectoryA': is not a member of 'duckdb::FileSystem'
```

It seems to be coming from:
```
#ifdef UNICODE
#define CreateDirectory  CreateDirectoryW
#else
#define CreateDirectory  CreateDirectoryA
#endif // !UNICODE
```

in windows sdk.

**Comment by hannesmuehleisen** [comment]
This is a good find, looks like we need to rename CreateDirectory in the FileSystem class to make this work cleanly.

**Comment by marius-klimantavicius** [comment]
Checked that non-amalgamated source code compiles (in VS2019 via CMake) as original cpp has `#undef CreateDirectory`, see https://github.com/duckdb/duckdb/blob/master/src/common/file_system.cpp#L35

**Comment by Mytherin** [comment]
This should be fixed.
