### ISSUE TITLE
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\functional(940): fatal error C1128: number of sections exceeded object file format  limit: compile with /bigobj [C:\Program Files\nodejs\node_modules\duckdb\build\duckdb.vcxproj]"

### ISSUE THREAD

**Issue by tanin47** [duckdb/duckdb#1910]
**What does happen?**
A short, clear and concise description of what the bug is.

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include\functional(940): fatal error C1128: number of sections exceeded object file format
 limit: compile with /bigobj [C:\Program Files\nodejs\node_modules\duckdb\build\duckdb.vcxproj]
```

When installing duckdb 0.2.3 through npm on windows. (i.e. `npm install -g duckdb@0.2.3`)

A fix would be to add `"AdditionalOptions": ["/bigobj"],` in binding.gyp.

Apology for reporting a few issues on Windows at the same time. Great project, and I'd love to help making this change since it is straightforward (and I have made this change locally and it builds).

**Comment by hannesmuehleisen** [comment]
Could you send a PR please?

**Comment by tanin47** [comment]
Yes! I'll send the PR soon. I notice that this only happens some of the times as well. I'm not sure why. But I suppose it's still good to have to handle different machines.

**Comment by Mytherin** [comment]
This should be fixed.
