### ISSUE TITLE
DuckDB via dbplyr doesn't support INTERVAL

### ISSUE THREAD

**Issue by koaning** [duckdb/duckdb#1920]
**What does happen?**

It seems you cannot use `AGE` via the dplyr connector.

I have a dataset:

```
    char level race  charclass zone                   guild timestamp          
   <int> <int> <chr> <chr>     <chr>                  <int> <dttm>             
 1 59425     1 Orc   Rogue     Orgrimmar                165 2008-01-01 00:02:04
 2 65494     9 Orc   Hunter    Durotar                   -1 2008-01-01 00:02:04
 3 65325    14 Orc   Warrior   Ghostlands                -1 2008-01-01 00:02:04
 4 65490    18 Orc   Hunter    Ghostlands                -1 2008-01-01 00:02:04
 5  2288    60 Orc   Hunter    Hellfire Peninsula        -1 2008-01-01 00:02:09
 6  2289    60 Orc   Hunter    Hellfire Peninsula        -1 2008-01-01 00:02:09
 7 61239    68 Orc   Hunter    Blade's Edge Mountains   243 2008-01-01 00:02:14
...
```

When I try to run this code:

```r
library(DBI)
library(dplyr)
library(tidyverse)

con <- dbConnect(duckdb::duckdb())
path <- "/Users/vincent/Development/calmcode.io/wowah_data.parquet/"

wow <- arrow::open_dataset(path, unify_schema=TRUE)
duckdb::duckdb_register(con, "wowah", wow %>% collect())

tbl(con, "wowah") %>% 
  group_by(char) %>% 
  arrange(timestamp) %>% 
  mutate(timediff = AGE(timestamp)) %>% 
  head(10) %>% 
  collect()
```

I get this error:

```
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Unknown column type for prepare: INTERVAL
```

Would I be correct in saying that DuckDB doesn't support interval types or is this a bug? 

I'm using duckdb version 0.2.7.

**Comment by koaning** [comment]
The issue also persists when I run;

```r
dbExecute(con, "SELECT *, AGE(timestamp) AS diff FROM wowah LIMIT 5")
```

**Comment by koaning** [comment]
Here's a minimum viable example without my dataset.

```r
df <- tibble(dates = as.POSIXct("2010-01-01") + 1:10)
duckdb::duckdb_register(con, "just_dates", df)
dbExecute(con, "SELECT dates, AGE(dates) AS diff FROM just_dates LIMIT 5")
```

**Comment by hannesmuehleisen** [comment]
Which R type would you expect this to return? We indeed have not implemented the INVERVAL type in the R API yet.

**Comment by koaning** [comment]
I want to session-ize some data. That means that I need to calculate the time between the current event and a previous one. Technically, if I was able to cast the timestamp to a unix-timestamp I wouldn't need to worry about an interval type.

I'm wondering what the best R-type would be for an interval though. I usually resort to [difftime](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/difftime) but this casts to an integer because the user can declare if they want seconds/minutes/hours.

**Comment by Mytherin** [comment]
> I want to session-ize some data. That means that I need to calculate the time between the current event and a previous one. Technically, if I was able to cast the timestamp to a unix-timestamp I wouldn't need to worry about an interval type.

You can use the `epoch` function to convert a timestamp to a unix timestamp.

```sql
select epoch(timestamp '2021-07-01');
┌──────────────────────────────────────┐
│ epoch(CAST(2021-07-01 AS TIMESTAMP)) │
├──────────────────────────────────────┤
│ 1625097600                           │
└──────────────────────────────────────┘
```

Perhaps that helps as a temporary work-around.

**Comment by koaning** [comment]
Ah! Epoch should do the trick then. 

One thing though: it seems like `epoch` isn't documented that way though. Looking at the docs [here](https://duckdb.org/docs/sql/functions/timestamp) it suggests that the epoch function is used to turn
ints to datetime.

```
epoch(0) -> 1970-01-01 00:00:00
```

**Comment by Mytherin** [comment]
That example indeed seems to be incorrect. `epoch_ms` does in fact do what it says there, whereas `epoch` is short for `extract(epoch from timestamp)`. The timestamp functions in the docs seem very out of date in general as we have a lot more of them now.

**Comment by Mytherin** [comment]
I have updated the documentation now to fix the mistake and reflect the timestamp functions we have.
