### ISSUE TITLE
duckdb capi: connection still can be used after duckdb_close

### ISSUE THREAD

**Issue by wangfenjin** [duckdb/duckdb#1924]
After call [duckdb_connect](https://github.com/duckdb/duckdb/blob/master/src/main/duckdb-c.cpp#L58) multiple times, and hold the connection, then call duckdb_close(), the opened connection still can be used.

Is that what we want?

**Comment by Mytherin** [comment]
This is because the connection holds a shared pointer to the database, which means as long as any connection is alive the database will be kept alive. If you want to close the database you will need to call `duckdb_disconnect` on every client as well.
