### ISSUE TITLE
Invalid string encoding aborts Parquet import

### ISSUE THREAD

**Issue by erikcw** [duckdb/duckdb#1932]
I'm trying to import a series of parquet files into duckdb.  Unfortunately, the import aborts with the following error:

```python
In [51]: cursor.execute("INSERT INTO master_email SELECT * FROM 'master_email/*.parquet'").df()    
 ---------------------------------------------------------------------------                                                            RuntimeError                              Traceback (most recent call last)                                                            
<ipython-input-51-90580d0a8a82> in <module>                                                                                           
----> 1 cursor.execute("INSERT INTO master_email SELECT * FROM 'master_email/*.parquet'").df() 
                                                                                                                                                                               
RuntimeError: INTERNAL Error: Invalid string encoding found in Parquet file: value is not valid UTF8! 

```

Pandas (via pyarrow), Spark and Presto all read these same parquet files without issue.

Would be nice to have the option to either ignore invalid rows, or at least include details about the bad record in the error so they can be manually cleaned up.

**Comment by erikcw** [comment]
Just in case it is helpful, it seems the following will clean up individual files.  I'm using it as a workaround for the time being.

```python
In [22]: cleaned_up = []
...: for fname in path.glob("part*"):
...:     try:
...:         cursor.execute(f"SELECT count(email) FROM '{fname}'").df()
...:     except RuntimeError as exc:
...:         print(exc, fname)
...:         df = pd.read_parquet(fname)
...:         df.email = df.email.apply(lambda e: e.encode('utf-8'))
...:         df.to_parquet(fname)
...:         cleaned_up.append(fname)
...:         # Test again to ensure file is clean.
...:         cursor.execute(f"SELECT count(email) FROM '{fname}'").df()

```

**Comment by Mytherin** [comment]
If possible (i.e. the file is not private) could you share the file here so we can test/verify this behavior?

**Comment by erikcw** [comment]
The file contains PII (email addresses).  I can share a sample of it with you privately.

**Comment by Mytherin** [comment]
Could you send it to my email (m.raasveldt@cwi.nl)? Thanks!

**Comment by erikcw** [comment]
Email sent.

**Comment by Mytherin** [comment]
Thanks. #1942 seems to fix this issue for me. The Parquet file seems to contain a null byte in one of the e-mail fields. This seems like a corrupt file or broken writer to me, but since the other readers accept and truncate the null byte I have implemented the same behavior in our Parquet reader.
