### ISSUE TITLE
use INTERVAL function Time out of bounds report error

### ISSUE THREAD

**Issue by winstoninthewhitehouse** [duckdb/duckdb#1933]
<version>0.2.7</version>
today is 6.30
in postgres
![image](https://user-images.githubusercontent.com/86718222/123948415-f5cb4b80-d9d3-11eb-906a-41cd69043125.png)

in duckdb

 ** preparedStatement = conn.prepareStatement("SELECT CURRENT_DATE - INTERVAL '4 MONTH';");
    rs = preparedStatement.executeQuery();**

![image](https://user-images.githubusercontent.com/86718222/123948532-14314700-d9d4-11eb-88ea-e9c727696dfa.png)

**Comment by Mytherin** [comment]
Thanks for the report! This seems like a bug in the interval arithmetic. I will have a look.

**Comment by Mytherin** [comment]
This should be fixed on the master now. Thanks again for the report!

**Comment by winstoninthewhitehouse** [comment]
When will the new version be released? I use java environment.
