### ISSUE TITLE
SQLite Table/View Reader

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1934]
We want to make an extension (`duckdb_sqlite`) that enables reading of SQLite tables from within DuckDB. The interface should look something like this:

```sql
SELECT * FROM read_sqlite('test.db', 'table_name');
```

Some points of consideration:
* Types should be retrieved from the table info if present. If no types are present (because `CREATE TABLE tbl(a,b,c)` is valid in SQLite) we should default to BLOB or VARCHAR.
* The extension should use the SQLite API to read the file (sqlite3_open, sqlite3_step, etc)
* Parallel execution can be achieved by partitioning on row-id. We can fire a query (`SELECT MAX(rowid) FROM tbl`) to get the maximum row-id. We can then launch jobs that fire queries based on that rowid (`SELECT col1, col2, ..., coln FROM tbl WHERE rowid BETWEEN 0 AND 100000`). The internal SQLite B-tree will take care of partitioning.
* Filter and projection pushdown can be performed into the queries, which also allows us to use SQLite indexes.
* We can also support views by just executing the view inside SQLite. How to retrieve the types for views is unclear. 
* Using this extension the shell could support opening SQLite databases. If the shell is used with a SQLite database as a parameter (`duckdb test.db`) we can register all the tables/views in there as views locally (e.g. `CREATE VIEW tbl AS SELECT * FROM read_sqlite('test.db', 'tbl')`, ...). The database should be read-only, however.

**Comment by Alex-Monahan** [comment]
This sounds great!! Do you think it would be possible to support the ATTACH keyword to have the same behavior as the shell's ability to register all views? I think that could be really convenient! That would possibly allow multiple SQLite files to be read simultaneously in a simple way.

As a side note, this could be another path to a clean webassembly data transfer. SQL.js and AlaSQL both can operate directly on SQLite files fetched into the browser.

**Comment by Mytherin** [comment]
> This sounds great!! Do you think it would be possible to support the ATTACH keyword to have the same behavior as the shell's ability to register all views? I think that could be really convenient! That would possibly allow multiple SQLite files to be read simultaneously in a simple way.

I think that is an excellent idea and should be feasible. Actually thinking about it we should probably provide a `read_duckdb` function that allows you to read a (separate!) duckdb database file, that you could also attach to.

**Comment by ak2k** [comment]
I think this specific design may overlap functionality with this older issue #892, the latter of which can be closed if so.

**Comment by hannes** [comment]
This is now available, see here https://github.com/duckdblabs/sqlitescanner
