### ISSUE TITLE
JSON function support

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#1939]
I'm working with a dataset that contains text columns that store JSON-encoded data. For example, the value `'{"name": "carl", "favorite_number": 3}'`. We'd like to retrieve a field like `name` from the value.

Today, as a stop-gap, we extract the field using a regular expression like `regexp_replace(json, '.*"name": "([^"]*)".*', '\1')` (which would return the string `'carl'`). This works fine for our use case for now, but we're obviously not suuuuper happy with it.

I'm familiar with the JSON functions from both [Postgres](https://www.postgresql.org/docs/13/functions-json.html) and [Presto](https://prestodb.io/docs/current/functions/json.html). Postgres has a full JSON type, which would certainly be helpful, but a "path query" function like Postgres's `jsonb_path_query` or Presto's `json_extract` or `json_extract_scalar` would be much more narrow and perfect for us! If we had `json_extract_scalar`, for instance, we'd implement the example above as `json_extract_scalar(json, '$.name')`.

Would something like this be a thing duckdb would be willing to support? I understand the space of possible designs is large, and I wouldn't want to lift a function out of another database that doesn't suit the goals of duckdb. But if there's a design folks are excited about, I'm happy to contribute code!

**Comment by hannesmuehleisen** [comment]
JSON support is on our roadmap for sure, we had just not considered it further because of very limited engineering resources. I think we were thinking to do something around a logical JSON type that maps to physical strings for now. Add to that some extract functions and support in loaders and we should be good.

**Comment by ak2k** [comment]
Might there be a way to leverage the [Sqlite JSON1 extension](https://www.sqlite.org/json1.html) [implementation](https://github.com/sqlite/sqlite/blob/master/ext/misc/json1.c) with sufficiently limited modification to be appealing? I know duckdb has leveraged the sqlite shell and implements some level of sqlite API compatibility, so curious if you think that this might be another candidate.

**Comment by wizzard0** [comment]
yeah (1) loadable functions for JSON are totally fine too, no need to put it into a type system imho. (2) loosely related: are [indexes on expressions](https://www.sqlite.org/expridx.html) supported? (1) + (2) + maybe JSONL loading would be enough to completely eliminate json dbs from a lot of scenarios

**Comment by hannesmuehleisen** [comment]
See #2970
