### ISSUE TITLE
Support multiple paths via parquet_scan

### ISSUE THREAD

**Issue by ParadoxShmaradox** [duckdb/duckdb#1944]
parquet_scan currently supports a single file path or a glob pattern to load multiple files to be treated as one.

Supplying multiple locations results in an error

**What does happen?**

java.sql.SQLException: Binder Error: No function matches the given name and argument types 'parquet_scan(VARCHAR, VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	parquet_scan(VARCHAR)

**What should happen?**
parquet_scan should be able to handle multiple locations (which could be glob patterns themselves)

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1.  SELECT * FROM parquet_scan('<location_1>', '<location_2>')

My scenario involves reading parquet files that are partitioned across multiple folders with and non trivial naming 
I want to read multiple files spreads across different folders and be treated as one table.

Thanks

**Comment by hannesmuehleisen** [comment]
As a workaround, you could already combine the two paths by doing something like
```SQL
SELECT * FROM PARQUET_SCAN('<location_1>') 
UNION ALL
SELECT * FROM PARQUET_SCAN('<location_2>');
```

**Comment by ParadoxShmaradox** [comment]
Thanks for the answer,

Unfortunately the query is user generated and I thought of doing simple table name substitution.
I could split it and do the where clause per select, union and then do any group by.

Unless duckdb is smart enough to do the predicate pushdown on a union of parquet tables?

Having parquet_scan read multiple file simplifies the query rewrites in this case.

**Comment by Mytherin** [comment]
DuckDB should do predicate and projection pushdown into a UNION ALL. However, for now UNION ALL disables parallelism (see #1583).

I will have a go at this but it will likely be a list parameter instead of multiple varchar arguments.
