### ISSUE TITLE
Null values with pandas autoinfering dataframe column types as object

### ISSUE THREAD

**Issue by Ariel-dono** [duckdb/duckdb#1955]
**What does happen?**
After load data as dataframe and run duck register function some values load as null, the pattern I noticed was that the dtype was autoinfered by pandas as object.

**What should happen?**
It would be great to have a consistent way to provide a C++ friendly datatype mapping manually or something similar.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. load a dataframe from data with objects like Decimal
2. register in duckdb as a view
3. see the content

**Environment (please complete the following information):**
 - OS: docker -> alpine
 - DuckDB Version: 0.2.7
 - ClientAPI: Python

Cheers!! Thank you for your work on this geat tool!!

**Comment by Mytherin** [comment]
Thanks for the bug report! Could you provide a code sample for easier reproducibility?

**Comment by Ariel-dono** [comment]
In my use case the data comes from a dictionary list provided by pymssql holding ctypes for instance for fields with "Decimal" types.

Code sample: 
...
dict_with_ctype_objects_as_values = {...}
dataframe_with_none_values = pandas.DataFrame.from_dict(dict_with_ctype_objects_as_values)
cursor.register('<view_name>', dataframe_with_none_values)
...

if you read the data all fields loaded with ctype objects have been loaded by pandas autoinfered as object, duckdb load it as null, but it works forcing the field typing by manually set each one as a pandas dtype different than object, like float32.

**Comment by Ariel-dono** [comment]
Hello again, I could provide my fix, it is not overwhelming. :grin:

**Comment by Mytherin** [comment]
> In my use case the data comes from a dictionary list provided by pymssql holding ctypes for instance for fields with "Decimal" types.
> 
> Code sample:
> ...
> dict_with_ctype_objects_as_values = {...}
> dataframe_with_none_values = pandas.DataFrame.from_dict(dict_with_ctype_objects_as_values)
> cursor.register('<view_name>', dataframe_with_none_values)
> ...
> 
> if you check all data fields loaded as pandas autoinfered as dtype object object duckdb loads it as null, but it is not forcing the field typing by manually set each one as a pandas dtype different than object, like float32.

Thanks, while that helps somewhat I meant a code sample that we could actually run (e.g. including actual data that triggers the error, ideally a piece of code we can just copy paste and run). It is difficult to trigger these kind of data dependent errors otherwise. 

> Hello again, I could provide my fix, it is not overwhelming. 😁

Sure, happy to review a PR.
