### ISSUE TITLE
How to get the column names and types from a result set query to Parquet

### ISSUE THREAD

**Issue by pgschr** [duckdb/duckdb#1962]
I have a table stored in Parquet format and can run a select statement with no issues in Python:

    sql = "SELECT * FROM parquet_scan('/the/path/*.parquet')" 
    data = cursor.execute(sql).fetchall()

What I need is the result set information with column names and types.  I cannot use `PRAGMA table_info('table_name');` because it retrieves all the columns from a table, and I need the columns from a result set. Any suggestions?

**Comment by Mause** [comment]
Does `cursor.description` give you the information you need?

**Comment by pgschr** [comment]
`cursor.description` returns column names, but not the types

**Comment by Mause** [comment]
Ah, you're right. Unfortunately is looks like this is one of the ways the python module deviates from the specification: https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyresult.cpp#L257

**Comment by pgschr** [comment]
My solution is to create a Pandas dataframe with `fetchdf()` instead of `fetchall()` then get the names and types from the dataframe with Pandas

**Comment by Mytherin** [comment]
You can also prepend DESCRIBE to any query and it will give you a description of the result set (e.g. ‘DESCRIBE SELECT * FROM tbl’).

**Comment by pgschr** [comment]
Thanks, DESCRIBE works perfectly, I would use it as I assume native `fetchall` works faster than `fetchdf`
