### ISSUE TITLE
CREATE TABLE AS support for defining constraints

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#1964]
Currently it is only possible to define table constraints (for a new table) in the ordinary ```CREATE TABLE``` statement, i.e.

```
CREATE TABLE t1(id INTEGER PRIMARY KEY, j VARCHAR)
```

It would be nice to be able to define table constraints when using one of the alternative ```CREATE TABLE AS ... ```  methods

e.g. creating the table from the view:

```
import pandas as pd
test_df = pd.DataFrame.from_dict({"i":[1, 2, 3, 4], "j":["one", "two", "three", "four"]})
con.register('test_df_view', test_df)
con.execute('CREATE TABLE test_df_table AS SELECT * FROM test_df_view')   # define contraints here
```
or from the csv:

```CREATE TABLE t1 AS SELECT * FROM read_csv_auto ('path/file.csv')    # define constraints here```

These methods are obviously helpful but are limited in scope by the inability to add & drop constraints in the ALTER TABLE statement (#57)

**Comment by DefinitelyAHuman** [comment]
can this be reopened instead of making a new issue? im looking for this functionality in duckdb because im creating duckdb tables from arrow tables
