### ISSUE TITLE
Python DBAPI 2.0 Compatibility

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#1967]
I figured it might be worth documenting some of the gaps that I've found while trying to build out the [sqlalchemy driver for duckdb](https://pypi.org/project/duckdb_engine)

The specification is available here: https://peps.python.org/pep-0249/

 * [x] `description` throws an exception instead of returning None when no result set is open (fixed in https://github.com/duckdb/duckdb/pull/1963)
 * [x] `description` is missing mandatory `type_code` value (https://github.com/duckdb/duckdb/pull/1990)
 * [x] missing `fetchmany` method on cursor
 * [x] Throw exceptions per standard, rather than using std::runtime_error for everything (working on this myself in https://github.com/duckdb/duckdb/pull/4075)
 * [ ] Missing the extension `lastrowid` (raised in https://github.com/duckdb/duckdb/issues/3976)

**Comment by Mause** [comment]
This is related to https://github.com/duckdb/duckdb/issues/469 as well

**Comment by thesketh** [comment]
@Mause Yeah, I noticed this when I started trying to port the SQLite tests. I think there are two things in play, there's compatibility with the DB-API and compatibility with SQLite (which isn't _completely_ conformant, and implements some of the extensions as well). I had a go at trying to build a pure Python wrapper which was more conformant, but I've unfortunately been waylaid with other things: https://github.com/thesketh/pyduckdb

**Comment by Florents-Tselai** [comment]
Having an iterable Cursor is pretty standard in Python
so the following works as expected,
especially if you `yield` the row in a generator.

```python
 import sqlite3
con = sqlite3.connect(':memory:')
cur = con.cursor()
cur.execute("CREATE TABLE bar (c1 TEXT, c2 INTEGER);")
cur.execute("INSERT INTO bar (c1, c2) values ('c0', 0);")
cur.execute("INSERT INTO bar (c1, c2) values ('c1', 1);")
cur.execute("INSERT INTO bar (c1, c2) values ('c2', 2);")
for row in cur.execute("select * from bar"):
    print(row)
```

The equivalent doesn't work in duckdb. 
```python
import duckdb
con = duckdb.connect(':memory:')
cur = con.cursor()
cur.execute("CREATE TABLE bar (c1 TEXT, c2 INTEGER);")
cur.execute("INSERT INTO bar (c1, c2) values ('c0', 0);")
cur.execute("INSERT INTO bar (c1, c2) values ('c1', 1);")
cur.execute("INSERT INTO bar (c1, c2) values ('c2', 2);")
for row in cur.execute("select * from bar"):
    print(row)
```

Which gives `TypeError: 'duckdb.duckdb.DuckDBPyConnection' object is not iterable` .
Haven't look at the implementation internally, but I guess it's hard having an object act as both a Connection and a Cursor.

Yes, you can, `fetchall`, but once you do the transaction will be closed too implicitly. 
Which in turn make lifecycle management (e.g. sharing the connection) a bit hard .

I guess as a client I would like to avoid having to create a list somehow.
Am I missing something too obvious here?
