### ISSUE TITLE
DuckDBAppender.java not append timestamp correctly

### ISSUE THREAD

**Issue by jeffreyorihuela** [duckdb/duckdb#1971]
**What does happen?**

When append a timestamp the date is not the same

**What should happen?**

I would like to see the correct date in the table

**To Reproduce**

```java
            Statement statement = conn.createStatement();
            statement.execute("CREATE TABLE dates (createdAt TIMESTAMP )");
            DuckDBAppender appender = new DuckDBAppender(conn, "","dates");
            for (int i = 0; i < 4; i++) {
                Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                Long time = timestamp.getTime();
                long l = time;
                System.out.println(timestamp + " Long: "+time + " long: "+l);
                appender.beginRow();
                appender.append(l);
                appender.endRow();

            }
            appender.flush();
            ResultSet rs = statement.executeQuery("SELECT * FROM dates");
            while(rs.next()) {
                System.out.println(rs.getString(1));
            }
            rs.close();
```
Output:
```
2021-07-08 13:47:30.896 Long: 1625770050896 long: 1625770050896
2021-07-08 13:47:30.901 Long: 1625770050901 long: 1625770050901
2021-07-08 13:47:30.901 Long: 1625770050901 long: 1625770050901
2021-07-08 13:47:30.901 Long: 1625770050901 long: 1625770050901
1970-01-19 19:36:10.050896
1970-01-19 19:36:10.050901
1970-01-19 19:36:10.050901
1970-01-19 19:36:10.050901
```

**Environment (please complete the following information):**
 - OS: Ubuntu 21.04
 - D .version
 - SQLite v0.2.7 8bc050d05
 - gcc-5.5.0 20171010
 - jdks/corretto-1.8.0_292-2

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Timestamps in DuckDB are stored as microseconds since epoch, it seems to me like you are inputting milliseconds since epoch, which is off by a factor of 1000. Perhaps include a multiplication by 1000 and see if that fixes the problem:

```java
appender.append(l * 1000);
```

**Comment by jeffreyorihuela** [comment]
Yes , that fixes the problem thanks!. It would be useful to indicate that in the documentation.
