### ISSUE TITLE
Indexes for sorted columns?

### ISSUE THREAD

**Issue by dforsber** [duckdb/duckdb#1973]
Is it possible to have indexes for sorted column ordering (top N)?

So, that e.g. a query of `CREATE INDEX idx_col1 t(col1); SELECT * FROM t ORDERY BY col1 LIMIT 2` would be using the index to pick up the first entries from it, instead of doing live sorting of `col1`.

If not, is there a way to implement similarly efficient JOIN that would use e.g. rowid from a table that already has sorted `col1`. Like `CREATE TABLE col1_sorted AS SELECT rowid AS rownum, col1 FROM t ORDER BY col1`, and then have a JOIN query that would do the Top N but with additional filtering, like `SELECT * FROM col1_sorted JOIN (SELECT * FROM t AS main WHERE col2 > 10 AND main.id=col1_sorted.id) LIMIT 10`. Sorry, the SQL is probably wrong and the sort order may not be preserved by the JOIN from the `col1_sorted`, but hopefully it clarifies the point :).

**Comment by pdet** [comment]
Hey Dan, we already have equality index joins.

You can force its use with the following pragma:
-- Force index joins where applicable
PRAGMA force_index_join;

**Comment by dforsber** [comment]
> Hey Dan, we already have equality index joins.
> 
> You can force its use with the following pragma:
> -- Force index joins where applicable
> PRAGMA force_index_join;

I tried to use that but can't see any difference in performance or `EXPLAIN SELECT ...` query plans. Would that apply only for the JOIN or would also apply to `SELECT * FROM t ORDER BY col1` when there is index for `t(col1)`?

**Comment by pdet** [comment]
That only applies for inner joins with at most one join condition

So something like this should work:

```sql
SELECT *
FROM col1_sorted INNER JOIN t ON ( t.id = col1_sorted.id) 
WHERE t.col2 > 1
LIMIT 10
```

**Comment by dforsber** [comment]
Ok, thank you. It may still be faster to do that "ORDER BY" without JOIN (or I just can't use it properly).

Is there any plan to support indexes for column sorting without JOIN?
Like a "normal index" that SQLite for example uses that would support ORDER BY as well.

**Comment by pdet** [comment]
Yes, I think that should be possible to implement that transformation in the optimizer.

I'll add it to my dev stack ;-)

**Comment by dforsber** [comment]
> Yes, I think that should be possible to implement that transformation in the optimizer.
> 
> I'll add it to my dev stack ;-)

Fabulous! All our non-aggregation queries use top N approach with sorted columns. Having indexes for them would make them ”10x” faster with indexes.

**Comment by dforsber** [comment]
Closing this in favor of the new Top N sorting implementation :).
