### ISSUE TITLE
Runtime Error when connecting to database

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#1976]
**What does happen?**
tried to connect to my databases and duckdb threw the following error:

```
import duckdb
con = duckdb.connect(database='database.db')
````

RuntimeError: Constraint Error: Cant create unique index, table contains duplicate data on indexed column(s)

**What should happen?**
If there was indeed duplicate data then a transaction should have been prevented or previously thrown an error.  In any event I can't see how tables with primary key constraints can be left in such a state, although it's hard to pinpoint exactly where the error is.

**To Reproduce**
Hard to reproduce this one.  If I manage to think of something I will add it.

**Environment (please complete the following information):**
 - OS: Windows 10
 - DuckDB Version: 0.2.7

**Comment by Admolly** [comment]
To provide a bit more background, I am doing a sequence of queries that does the following:

- fetch rows from a MySQL database satisfying the condition ```WHERE updated_at > "some time"```
- register the resulting DataFrame as a view in DuckDB ```con.register('view', df)```
- delete rows from DuckDB table satisfying the condition ```DELETE FROM table WHERE id IN (SELECT id FROM view)```
- create relation from DataFrame and insert into table: ```con.from_df(df).insert_into(table)```

Moreover, upon querying each table AFTER deleting & inserting the data, I can confirm that the values for the primary key are indeed unique.  I'm guessing that something is not being deleted from the index when I execute the ```DELETE``` query.

**Comment by Admolly** [comment]
Finally have a reproducible example:

```
import duckdb
con = duckdb.connect('example.db')
con.execute("CREATE TABLE tbl (i INTEGER PRIMARY KEY)")
con.execute("INSERT INTO tbl VALUES (0), (1)")
con.execute("DELETE FROM tbl WHERE i IN (0)")
con.execute("INSERT INTO tbl VALUES (0)")
con.commit()
con.close()
duckdb.connect('example.db')
```

**Comment by Mytherin** [comment]
This seems related to #1625

**Comment by Admolly** [comment]
I see.  So it looks like neither index storage or vacuuming have been implemented yet?

In the meantime, perhaps it's simply best to simply use UPDATE instead?
