### ISSUE TITLE
Copy table to parquet does not work in Node.js environment

### ISSUE THREAD

**Issue by sashakorman** [duckdb/duckdb#1977]
**What does happen?**
Trying to export a table to parquet file using COPY TO syntax in Node.js environment.
Got the following error:

> [Error: Catalog Error: Copy Function with name parquet does not exist!
> Did you mean "csv"?] {
>   errno: -1,
>   code: 'DUCKDB_NODEJS_ERROR'
> }

**What should happen?**
Table should be exported into parquet file

**To Reproduce**
Run the following code.

```
const duckdb = require('duckdb');

const db = new duckdb.Database(':memory:'); 
const connection = db.connect();
connection.run(`CREATE TABLE posix (path VARCHAR, size BIGINT)`);
connection.run(`INSERT INTO posix (path, size) VALUES ('/work', 1)`);
connection.run(`COPY posix TO 'out.csv' (FORMAT 'CSV')`);
connection.run(`COPY posix TO 'out.parquet' (FORMAT 'PARQUET')`);
connection.all(`COPY posix TO 'out.parquet' (FORMAT 'PARQUET')`, (err, res) => {
    if (err) {
      throw err;
    }
    console.log(res);
  });
```

- Export to CSV does work.

- Export to PARQUET does work using CLI.

**Environment:**
 - OS: Amazon Linux 2
 - DuckDB version: 0.2.7
 - Node version: 16.4.2

**Comment by hannesmuehleisen** [comment]
Yes, we are currently not shipping the Parquet extension with the node client. We probably should do that.

**Comment by hamilton** [comment]
Found this issue after searching. Could someone point us to where in the repo we might make this happen? I would be happy to submit a patch that does this to get the ball rolling.

**Comment by hannesmuehleisen** [comment]
Getting a PR ready hang on

**Comment by davidtheclark** [comment]
I'm using Node.js SDK v0.3.3, and I'm successfully copying into Parquet files. Should this issue be closed?

**Comment by hannes** [comment]
Yes, we also ship the Parquet reader as a loadable extension now
