### ISSUE TITLE
Hi , DuckDB is a pure memory database  ?  it stores all the data in memory , right ?   Thanks!

### ISSUE THREAD

**Issue by triump2020** [duckdb/duckdb#1981]

**Comment by Mytherin** [comment]
DuckDB has an option of being memory only (‘:memory:’) but can also persistently store the data on disk if a path to a database file is provided. When a database file is used DuckDB will cache (parts of) the database in memory using a buffer manager. The maximum memory used by this cache can be modified using `PRAGMA memory_limit='Xgb’`. This defaults to 80% of the systems RAM. In practice for smaller databases, this means it will keep the entire database cached in memory after reading it once.

**Comment by triump2020** [comment]
Thanks !    It's a great project !
