### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by vishalmo** [duckdb/duckdb#1983]
Hi , I am getting this error
error: command 'gcc' failed with exit status 1

when installing python package on RED HAT LINUX 7.7
**Error is below:**

In file included from src/pandas_scan.cpp:2:0:
    /tmp/pip-build-99f7i1hq/duckdb/src/include/duckdb_python/array_wrapper.hpp:16:8: warning: ‘duckdb::RawArrayWrapper’ declared with greater visibility than the type of its field ‘duckdb::RawArrayWrapper::array’ [-Wattributes]
     struct RawArrayWrapper {
            ^
    In file included from src/pandas_scan.cpp:6:0:
    /tmp/pip-build-99f7i1hq/duckdb/src/include/duckdb_python/vector_conversion.hpp:34:8: warning: ‘duckdb::NumPyArrayWrapper’ declared with greater visibility than the type of its field ‘duckdb::NumPyArrayWrapper::numpy_array’ [-Wattributes]
     struct NumPyArrayWrapper {
            ^
    /tmp/pip-build-99f7i1hq/duckdb/src/include/duckdb_python/vector_conversion.hpp:41:8: warning: ‘duckdb::PandasColumnBindData’ declared with greater visibility than the type of its field ‘duckdb::PandasColumnBindData::numpy_col’ [-Wattributes]
     struct PandasColumnBindData {
            ^
    src/pandas_scan.cpp:12:8: warning: ‘duckdb::PandasScanFunctionData’ declared with greater visibility than the type of its field ‘duckdb::PandasScanFunctionData::df’ [-Wattributes]
     struct PandasScanFunctionData : public TableFunctionData {
            ^
    src/pandas_scan.cpp: In static member function ‘static std::unique_ptr<duckdb::FunctionOperatorData> duckdb::PandasScanFunction::PandasScanInit(duckdb::ClientContext&, const duckdb::FunctionData*, const std::vector<long unsigned int>&, duckdb::TableFilterCollection*)’:
    src/pandas_scan.cpp:74:9: error: cannot bind ‘std::unique_ptr<duckdb::PandasScanState, std::default_delete<duckdb::PandasScanState> >’ lvalue to ‘std::unique_ptr<duckdb::PandasScanState, std::default_delete<duckdb::PandasScanState> >&&’
      return result;
             ^
    In file included from /usr/include/c++/4.8.2/memory:81:0,
                     from duckdb/src/include/duckdb/common/constants.hpp:11,
                     from duckdb/src/include/duckdb/common/enums/profiler_format.hpp:11,
                     from duckdb/src/include/duckdb/main/connection.hpp:11,
                     from duckdb/src/include/duckdb.hpp:11,
                     from /tmp/pip-build-99f7i1hq/duckdb/src/include/duckdb_python/pandas_scan.hpp:11,
                     from src/pandas_scan.cpp:1:
    /usr/include/c++/4.8.2/bits/unique_ptr.h:169:2: error:   initializing argument 1 of ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = duckdb::PandasScanState; _Ep = std::default_delete<duckdb::PandasScanState>; <template-parameter-2-3> = void; _Tp = duckdb::FunctionOperatorData; _Dp = std::default_delete<duckdb::FunctionOperatorData>]’
      unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
      ^
    src/pandas_scan.cpp:75:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    error: command 'gcc' failed with exit status 1

**Comment by Mytherin** [comment]
Thanks for opening the issue!

This seems to be missing a `move` on the return on line 74. This is something that old versions of GCC complain about. We do test with GCC-4.9 but only the core system, not the Python package. We should perhaps add a test for that as well.

**Comment by vishalmo** [comment]
Thanks Mytherin 
I have gcc 4.8 , and it is failing to install package.
Not sure what to do.

**Comment by Mytherin** [comment]
I have pushed a fix to the master now, could you retry with `pip install duckdb --pre`?

**Comment by vishalmo** [comment]
Thanks Mytherin , 

I am able to install successfully.

**Comment by vishalmo** [comment]
HI Mytherin , 

I found new issue with python duckdb on windows. The program automatically exiting and stop the python command. i am using python3.7. RAM 24 gb 

command i am using : duckdb.query().todf() ( it is not working for both dev package & production package).

*

**Comment by hannes** [comment]
This seems to have gotten side-tracked and the original issue is likely fixed.
