### ISSUE TITLE
Change in Lists Offset Representation

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#1984]
We currently represent our lists offsets as pairs of offset and lengths.

For example:
[[1,2,3],[4],NULL,[5,6]]
Would have:
offsets[0]: {0,3}
offsets[1]: {3,1}
offsets[2]: {4,0}
offsets[3]: {4,2}

The idea is to change this to be an array of offsets, to allow for better integration with multiple different Arrow types (e.g., strings, blobs, lists) and to facilitate/save space on the list storage.

We would then support uin32 and uint64 types on the offsets.

Following the same example as before we would have, only one offset list:
offsets:{0,3,4,4,6}

**Comment by Mytherin** [comment]
We have decided to go another path.
