### ISSUE TITLE
DuckDB Reader & Attach Functionality

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1985]
Spin-off from #1934, but related to creating a reader for our own database files.

```sql
SELECT * FROM read_duckdb('test.db', 'table_name');
```

**Comment by danz68** [comment]
Will this include memory databases? If this is the case, and more than one memory database connections are possible, then it will be required sort of unique identification per memory db, even if that is just an incremental integer.

**Comment by ankoh** [comment]
It won't include memory databases.
The idea here is to just read a table from an existing (persistent) duckdb database file.
For example,  `CREATE VIEW foo AS (SELECT * FROM read_duckdb('test.db', 'foo');` would just make the table `foo` in the persistent database file `test.db` accessible in the current database via a view named `foo`.

**Comment by ankoh** [comment]
The real magic will happen with `CREATE VIEW foo AS (SELECT * FROM read_duckdb('https://some-remote-database', 'foo'));`

**Comment by Mytherin** [comment]
We could envision a method for attaching to a different in-memory database as well, but that would not be done through a global counter but rather by passing the database into some function, e.g. something like this:

```cpp
DuckDB db1;
DuckDB db2;

Connection con(db1)
con.Attach(db2);
```

Likely not in a first iteration, however.

**Comment by danz68** [comment]
I can think to at least two scenarios where these memory connections can help. 

1. custom extractions (host application knows how to load other datasources, ADO Drivers, ODBC, custom, for which creates memory databases for caching purposes)
2. custom calculations (the host application has custom computing algorithms that can use an indefinite amount of columns as input and exports an indefinite amount of columns and constant values that can be subsequently cached for fast access in the original environment)

As a workaround I can use temporary disk databases and temporary tables for the same matter, but with memory databases and proper "communication" between connections, I might avoid duplicating the memory (I assume).

**Comment by RandomFractals** [comment]
> The real magic will happen with `CREATE VIEW foo AS (SELECT * FROM read_duckdb('https://some-remote-database', 'foo'));`

When will this be available, and in that example, could https data source be any public data folder with parquet data files, csv, arrow data, or `.duckdb`?

Is this currently supported by duckdb wasm for the 4 data file types mentioned? and how robust is it to support up to 1GB datasets loaded in a browser?
