### ISSUE TITLE
Casting decimal column to integer requires explicit 0 decimal specifier

### ISSUE THREAD

**Issue by chrisfw** [duckdb/duckdb#1987]
Casting a decimal column to an integer does not match rows without explicitly appending a ".0".  The SQL statement should not require a decimal specifier to match an integer value

**To Reproduce**
```
>>> con.execute("create table test (consumption decimal(14,5))")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> con.execute("insert into test values(17953.2)")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> con.execute("select * from test where cast(consumption as int) = 17953")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> print(con.fetchall())
[]
>>> con.execute("select * from test where cast(consumption as int) = 17953.0")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> print(con.fetchall())
[(Decimal('17953.20000'),)]
```
I tried the same experiment with Postgres and it works as I would expect
![postgres-sample](https://user-images.githubusercontent.com/6135741/125290974-e4950f80-e2ee-11eb-9b39-b8a30db698be.png)

**Environment (please complete the following information):**
 - OS: [e.g. MacOS (M1)]
 - DuckDB Version  0.2.7 -> 8bc050d05

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm. This appears to be a bug in one of the optimizers. I will have a look.
