### ISSUE TITLE
Modify DATE/TIME/TIMESTAMP in C API

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#1992]
Currently we use the following structs for dates/times/timestamps in the C API:

```cpp
typedef struct {
	int32_t year;
	int8_t month;
	int8_t day;
} duckdb_date;

typedef struct {
	int8_t hour;
	int8_t min;
	int8_t sec;
	int32_t micros;
} duckdb_time;

typedef struct {
	duckdb_date date;
	duckdb_time time;
} duckdb_timestamp;
```

This works, but is rather inefficient since the structs do not match our own internal date/time/timestamp representation. It would be better if these would be stored as our own internal representation, and we would expose functions that could extract different components, e.g.:

```cpp
typedef struct {
    int32_t days;
} duckdb_date;

int32_t duckdb_date_years(duckdb_date date);
int32_t duckdb_date_months(duckdb_date date);
int32_t duckdb_date_days(duckdb_date date);
```

**Comment by danz68** [comment]
Absolutely. But you need functions in both directions, DateTime2DuckDB and DuckDB2DateTime. Internal representation is required for append operations.
