### ISSUE TITLE
Difference between two dates

### ISSUE THREAD

**Issue by marcelned** [duckdb/duckdb#1998]
Is there a way to get the difference between two dates similar to [T-SQL](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver15)?

I can't find  a `DATEDIFF` functionality, nor are `INTERVAL` types supported:

```SQL
SELECT TIMESTAMP '1992-09-20 11:30:00' - TIMESTAMP '1992-09-20 11:30:00'
```

yields

```console
unsupported type: INTERVAL
```

**Comment by hannesmuehleisen** [comment]
Is this in R?

**Comment by marcelned** [comment]
Hi @hannesmuehleisen 

This is the Python SDK

Environment:
Python 3.9.6
OS: RHEL 8 on IBM PowerPC
DuckDB version : 0.2.7

**Comment by marcelned** [comment]
Also to mention, I'm not sure how the dates get converted after the fact, but it doesn't look right:

<img width="626" alt="Screenshot 2021-07-14 at 13 28 57" src="https://user-images.githubusercontent.com/82392567/125614872-68a032f4-4e74-4e5c-982a-0eb39983c6ef.png">

the datedif doesn't reflect the correct value. Perhaps this is because interval types aren't supported as yet?

**Comment by Mytherin** [comment]
> Is there a way to get the difference between two dates similar to T-SQL?


As a work-around for the missing interval support, you could add a cast to VARCHAR in the mean time:

```sql
D SELECT (TIMESTAMP '1992-09-20 11:30:00' - TIMESTAMP '1992-09-19 10:30:00')::VARCHAR;
┌────────────────────────────────────────────────────────────────────────────────────┐
│ CAST(CAST(1992-09-20 11:30:00 AS TIMESTAMP) - CAST(1992-09-19 10:30:00 AS TIMES... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 1 day 01:00:00                                                                     │
└────────────────────────────────────────────────────────────────────────────────────┘
```

Or extract a subset of the interval manually:
```sql
D SELECT extract(day from TIMESTAMP '1992-09-20 11:30:00' - TIMESTAMP '1992-09-19 11:30:00');
┌────────────────────────────────────────────────────────────────────────────────────┐
│ date_part(day, CAST(1992-09-20 11:30:00 AS TIMESTAMP) - CAST(1992-09-19 11:30:0... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 1                                                                                  │
└────────────────────────────────────────────────────────────────────────────────────┘
```

> The datediff column of type datetime64[ns] doesn't reflect the correct value. Perhaps this is because interval types aren't supported as yet?

This seems like a bug. It looks like a missing multiplication by 1000 to convert from microseconds to nanoseconds. Could you make a reproducible example in Python that exhibits this behavior?

**Comment by marcelned** [comment]
Pandas does exhibit the correct behaviour just doing 
```python
df["TRAN_DTE"] - df["AUTH_EFCT_DTE"]
``` 

I think it should be a bug in how DuckDB communicates with Pandas.

**Comment by Mytherin** [comment]
I think the problem is in the DuckDB - Pandas communication layer too - I meant could you post a reproducible example in Python using DuckDB that exhibits the behavior (i.e. including the necessary data, etc)? Without the data it is difficult to reproduce and fix the problem.

**Comment by marcelned** [comment]
```python
import duckdb
import numpy as np
import pandas as pd

print(duckdb.__name__, duckdb.__version__)
print(np.__name__, np.__version__)
print(pd.__name__, pd.__version__)

# set seed
np.random.seed(19)

# connect to an in-memory temporary database
conn = duckdb.connect()

# https://stackoverflow.com/questions/50559078/generating-random-dates-within-a-given-range-in-pandas


def random_dates(start, end, n=10):

    start_u = start.value // 10 ** 9
    end_u = end.value // 10 ** 9

    return pd.to_datetime(np.random.randint(start_u, end_u, n), unit="s")


start = pd.to_datetime("2020-01-01")
end = pd.to_datetime("2021-01-01")

data = {"dt1": random_dates(start, end, n=5),
        "dt2": random_dates(start, end, n=5)}
df = pd.DataFrame(data)

SQL = """
      SELECT
      dt1,
      dt2,
      dt2 - dt1 as duck_diff
      from df
      """

res = conn.execute(SQL).fetchdf()

res["duck_diff"] = abs(res["duck_diff"])
res["pd_diff"] = abs(res["dt1"] - res["dt2"])
print(res)

```

```console
duckdb 0.2.7
numpy 1.21.0
pandas 1.3.0
                  dt1                 dt2              duck_diff           pd_diff
0 2020-07-07 02:01:01 2020-08-05 07:51:47 0 days 06:32:31.600000  29 days 05:50:46
1 2020-02-08 19:26:38 2020-09-21 10:02:28 0 days 19:55:30.800000 225 days 14:35:50
2 2020-06-19 20:45:41 2020-01-04 05:44:42        0 days 18:58:35 167 days 15:00:59
3 2020-11-18 18:22:26 2020-06-14 02:46:55 0 days 19:17:16.600000 157 days 15:35:31
4 2020-08-24 03:31:52 2020-07-05 19:04:34 0 days 09:36:25.200000  49 days 08:27:18
```

**Comment by Mytherin** [comment]
Thanks, that's very helpful!

**Comment by hawkfish** [comment]
I believe the Pandas issue has been fixed; I now get:

```py
duckdb 0.2.9
numpy 1.21.2
pandas 1.3.3
                  dt1                 dt2         duck_diff           pd_diff
0 2020-07-07 02:01:01 2020-08-05 07:51:47  29 days 05:50:46  29 days 05:50:46
1 2020-02-08 19:26:38 2020-09-21 10:02:28 222 days 14:35:50 225 days 14:35:50
2 2020-06-19 20:45:41 2020-01-04 05:44:42 165 days 15:00:59 167 days 15:00:59
3 2020-11-18 18:22:26 2020-06-14 02:46:55 154 days 15:35:31 157 days 15:35:31
4 2020-08-24 03:31:52 2020-07-05 19:04:34  48 days 08:27:18  49 days 08:27:18
```

The differences are due to the way SQL defines `INTERVAL` as having 30 day months e.g., when  I run the straight SQL:

```sql
query I
SELECT '2020-08-24 03:31:52'::TIMESTAMP - '2020-07-05 19:04:34'::TIMESTAMP;
----
1 month 18 days 08:27:18
```

So when we convert the `INTERVAL` to a count of days we get `48` instead of `49`.

DuckDB now has [`DATEDIFF`](https://duckdb.org/docs/sql/functions/timestamp) (and `DATESUB`), so you can use that if it solves your problem. To get the full delta as a Pandas style interval, you unfortunately need to do your own `INTERVAL` construction:

```sql
CREATE FUNCTION INTERVAL_SECS(secs) AS INTERVAL (secs / 86400) DAYS + INTERVAL (secs % 86400) SECONDS;
CREATE FUNCTION EPOCH_DIFF(lhs, rhs) AS EPOCH(lhs::TIMESTAMP) - EPOCH(rhs::TIMESTAMP);
SELECT INTERVAL_SECS(EPOCH_DIFF(dt1, dt2)) from ts;
```

I'd just return the number of seconds and then have Pandas construct its interval type itself.

**Comment by marcelned** [comment]
Thank you @hawkfish . This works.

Will this be integrated into pandas more down the line? For data scientists like myself without procedural SQL training, this could be a stumbling block to use it with pandas easily

**Comment by hawkfish** [comment]
The problem is that the subtraction operator produces the `INTERVAL` so by the time it gets to the Pandas translation layer, the information has already been lost. 

I will look at whether we should change the semantics of `TIMESTAMP` subtraction to be exact (it bugs me that `TS1 + (TS2 - TS1) <> TS2` ) but it may depend on what Postgres does. Although in this case I think PG is wrong and we should Do The Right Thing...

**Comment by hawkfish** [comment]
Postgres actually agrees with Pandas, so this is officially a bug!

```sql
hawkfish=# SELECT '2020-08-24 03:31:52'::TIMESTAMP - '2020-07-05 19:04:34'::TIMESTAMP;
     ?column?     
------------------
 49 days 08:27:18
(1 row)
```

**Comment by hawkfish** [comment]
@marcelned Can you see if there is anything else?

**Comment by marcelned** [comment]
@hawkfish Didn't find any other issues, however there are some other things I'd like to inquire on.

Our team would like to use this framework to speed up pandas pipelines with quite large datasets (10GB dataframes).

The OLAP nature of the is very attractive, but the performance kind of isn't there as yet. Look at the same rolling average calc with pandas vs duckdb:

<img width="860" alt="Screenshot 2021-09-25 at 15 44 02" src="https://user-images.githubusercontent.com/82392567/134773747-df8a0d9a-a73a-433a-b6a4-2daf04950f6c.png">


Are we doing something wrong? I can repost this question in the discussions section if it belongs there. Otherwise this is probably a closed issue :)

**Comment by hawkfish** [comment]
This is more like a second bug report. I will move it to a new issue so we can close this one?

**Comment by marcelned** [comment]
@hawkfish  the DuckDB dev team incredibly helpful! Thank you for this gift to the data science community.
