### ISSUE TITLE
Segmentation fault on parquet_scan

### ISSUE THREAD

**Issue by jupiter** [duckdb/duckdb#2002]
**What does happen?**
With a specific parquet file generated by AWS Athena, we are getting a segmentation fault on multiple versions, including the current version of DuckDB, on different platforms.

**What should happen?**
Query should return results.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. `SELECT * FROM parquet_scan('./20210714_134306_02697_kupbs_1f656e7a-f505-4553-9f6d-5d1f4f6bae1b');`
`[1]    60636 segmentation fault  `

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Linux, MacOS
 - DuckDB Version [e.g. 22] v0.2.7 8bc050d05

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by jupiter** [comment]
I can provide the file by email.

**Comment by hannesmuehleisen** [comment]
Please send the file to hannes@cwi.nl . Can we check the file into our repo?

**Comment by hannesmuehleisen** [comment]
Confirmed, this crashes.

**Comment by hannesmuehleisen** [comment]
Seems related to a list column

**Comment by jupiter** [comment]
Yes, there are 2 list columns, one that is a list of string and the other a list of maps. Both of these columns have this problem. It also only seems to happen after a certain offset.

**Comment by hannesmuehleisen** [comment]
Are you part of the deepcrawl crowd by chance?

**Comment by jupiter** [comment]
I am. :)

**Comment by hannesmuehleisen** [comment]
Should be fixed
