### ISSUE TITLE
ODBC-client: "Select 42" is not working 

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb#2015]
When I'm testing an ODBC-client with SQL-command "SELECT 42" It isn't working.
Prepare, Execute and Describe are working but Fetch isn't. I will get the following error message:

```
[ODBC][20419][1626450456.653113][SQLSetStmtAttr.c][265]
		Entry:
			Statement = 0x556143962660
			Attribute = SQL_ATTR_ROW_BIND_TYPE
			Value = (nil)
			StrLen = 0
[ODBC][20419][1626450456.653130][SQLSetStmtAttr.c][928]
		Exit:[SQL_ERROR]
```
And the same is happening if I try to create a table. An execution is working and table is created, but Fetching fails.

And my setup is working with Clickhouse. I'm using unixODBC-2.3.9 with Kubuntu 21.04.

Describe for Clickhouse for `Select 42` gives
`s1  3 3 0 1  Select 42  50 ¯314238752  Select 42      42  4 0 0 ¯6 0 ¯6 3 0 0` 
And the same for DuckDB is
`s1  3 3 0 1  Select 42  50 ¯314068800  Select 42      42  4 0 0 4 0 4 0 0 0`

**Comment by hannesmuehleisen** [comment]
@tiagokepe

**Comment by tiagokepe** [comment]
@kimmolinna It appears that the problem is related to the SQLConnect and passing the serve_name parameter.

In your trace: https://github.com/duckdb/duckdb/pull/1896#issuecomment-881548722, the serve_name is as `Server Name = [DuckDB DSN]`, and the unix ODBC client could not find a corresponding DSN to that server_name.

I changed the server name to `Server Name = [DuckDB]` , such as:
```
SQLCHAR *server_name = (SQLCHAR *)"DuckDB";
ret = SQLConnect(CONN, server_name, SQL_NTS, NULL, 0, NULL, 0);`

```
That worked for me:

![image](https://user-images.githubusercontent.com/403295/126162269-e76619a4-8252-4fd2-99d0-1ab2bde74a19.png)

![image](https://user-images.githubusercontent.com/403295/126162420-d78f0146-7eba-4286-b43d-226ccbc2056a.png)

My odbc.ini file looks like:
```
[DuckDB]
Driver = DuckDB Driver
Database=:memory:
```

My odbcinst.ini file looks like:
```
[ODBC]
Trace = yes
TraceFile = /tmp/odbctrace

[DuckDB Driver]
Driver = [DuckDB ODBC driver path]/libduckdb_odbc.so
```

**Comment by kimmolinna** [comment]
This is strange. Because it doesn't change anything in my setup if I change a Server Name. And a connection was working previously because I was able to execute commands and those worked. And only thing which is not working is Fetch

Describe is working.
```
Describe c
0   Cursor DD.s1: Status=Executed, MaxRows=50     
                                                  
    Select 42                                     
                                                  
    Bind Vars: 0                                  
     Name  APL  DB  Prec.  Scale  Length    Buf   
                                                  
    Select vars: 1                                
     Name  APL  DB  Prec.  Scale  Length    Buf   
     42    ?    I       0      0       0 I  ?     
```
But Fetch isn't

```
[ODBC][2863][1626700702.530104][SQLDescribeCol.c][504]
		Exit:[SQL_SUCCESS]                
			Column Name = [42]                
			Data Type = 0x7ffd8d0e0e6c -> 4                
			Column Size = 0x7ffd8d0e0e60 -> 0 (64 bits)                
			Decimal Digits = 0x7ffd8d0e0e6a -> 0                
			Nullable = 0x7ffd8d0e0e68 -> 2
[ODBC][2863][1626700769.138724][SQLSetStmtAttr.c][265]
		Entry:
			Statement = 0x55c06c216920
			Attribute = SQL_ATTR_ROW_BIND_TYPE
			Value = (nil)
			StrLen = 0
[ODBC][2863][1626700769.138905][SQLSetStmtAttr.c][928]
		Exit:[SQL_ERROR]
[ODBC][2863][1626700769.138939][SQLGetDiagField.c][958]
		Entry:
			Statement = 0x55c06c216920
			Rec Number = 0
			Diag Ident = 2
			Diag Info Ptr = 0x7ffd8d0e1798
			Buffer Length = 4
			String Len Ptr = 0x7ffd8d0e178e
```
My version of unixODBC is 2.3.9 and as I mentioned earlier It's working at least with Clickhouse ODBC.

**Comment by kimmolinna** [comment]
The previous trace info was from DuckDB. I use unixODBC with tool which I have used with many different databases (MySQL, MariaDB, Clickhouse etc.) and It works quite nicely in Unix and Windows with the programming language which I'm used to use - DyalogAPL.

**Comment by kimmolinna** [comment]
I installed also PostgreSQL and built its ODBC-driver with unixODBC and output was equal to my previous post.

**Comment by tiagokepe** [comment]
Yeah, 

> @tiagokepe The previous trace info was from DuckDB. I use unixODBC with tool which I have used with many different databases (MySQL, MariaDB, Clickhouse etc.) and It works quite nicely in Unix and Windows with the programming language which I'm used to use - DyalogAPL.
> If I compare Clickhouse and DuckDB behaviour with unixODBC it's basically the same until ` SQL_ATTR_ROW_BIND_TYPE`-error. The response of Clickhouse is the following:
> 
> ```
> [ODBC][2863][1626719396.846197][SQLSetStmtAttr.c][928]
> 		Exit:[SQL_SUCCESS]
> [ODBC][2863][1626719396.846215][SQLSetStmtAttr.c][265]
> 		Entry:
> 			Statement = 0x55c06c2c69d0
> 			Attribute = SQL_ATTR_ROWS_FETCHED_PTR
> 			Value = 0x55c06bf25cf0
> 			StrLen = 0
> [ODBC][2863][1626719396.846231][SQLSetStmtAttr.c][928]
> 		Exit:[SQL_SUCCESS]
> [ODBC][2863][1626719396.846244][SQLSetStmtAttr.c][265]
> 		Entry:
> 			Statement = 0x55c06c2c69d0
> 			Attribute = SQL_ATTR_ROW_ARRAY_SIZE
> 			Value = 0x32
> 			StrLen = 0
> [ODBC][2863][1626719396.846262][SQLSetStmtAttr.c][928]
> 		Exit:[SQL_SUCCESS]
> [ODBC][2863][1626719396.846280][SQLBindCol.c][245]
> 		Entry:
> 			Statement = 0x55c06c2c69d0
> 			Column Number = 1
> 			Target Type = 4 SQL_INTEGER
> 			Target Value = 0x55c06c2c7550
> 			Buffer Length = 4
> 			StrLen Or Ind = 0x55c06c058900
> [ODBC][2863][1626719396.846315][SQLBindCol.c][353]
> 		Exit:[SQL_SUCCESS]
> [ODBC][2863][1626719396.846333][SQLFetchScroll.c][159]
> 		Entry:
> 			Statement = 0x55c06c2c69d0
> 			Fetch Orentation = 1
> 			Fetch Offset = 0
> [ODBC][2863][1626719396.846364][SQLFetchScroll.c][356]
> 		Exit:[SQL_SUCCESS]
> [ODBC][2863][1626719396.846380][SQLFreeStmt.c][144]
> 		Entry:
> 			Statement = 0x55c06c2c69d0
> 			Option = 0
> [ODBC][2863][1626719396.846506][SQLFreeStmt.c][266]
> 		Exit:[SQL_SUCCESS]
> [ODBC][2863][1626719396.846768][SQLFreeHandle.c][387]
> 		Entry:
> 			Handle Type = 3
> 			Input Handle = 0x55c06c2c69d0
> [ODBC][2863][1626719396.846803][SQLFreeHandle.c][490]
> 		Exit:[SQL_SUCCESS]
> ```
> 
> And you already have all other attributes in `statement.cpp `:)
> 
> ```
> 		case SQL_ATTR_ROW_ARRAY_SIZE: {
> 			// this should be 1 (for now!)
> 			// TODO allow fetch to put more rows in bound cols
> 			auto new_size = (SQLULEN)value_ptr;
> 			if (new_size != 1) {
> 				return SQL_ERROR;
> 			}
> 			return SQL_SUCCESS;
> 		}
> 		case SQL_ATTR_ROWS_FETCHED_PTR: {
> 			stmt->rows_fetched_ptr = (SQLULEN *)value_ptr;
> 			return SQL_SUCCESS;
> 		}
> ```

Yeah, we support a few ones, but there are others to support such as `SQL_ATTR_ROW_BIND_TYPE`.

**Comment by kimmolinna** [comment]
@tiagokepe Postgres seems to return default for `SQL_ATTR_ROW_BIND_TYPE`.
`pgapi30.c` lines 2012-2013
```
/* case SQL_ATTR_ROW_BIND_TYPE: ** == SQL_BIND_TYPE(ODBC2.0) */
default:
	return PGAPI_SetStmtOption(StatementHandle, (SQLUSMALLINT) Attribute, (SQLULEN) Value);
```

**Comment by tiagokepe** [comment]
I already changed our odbc driver to use the default (SQL_ATTR_ROW_BIND_TYPE) that is column-wise binding. It's working and the unixODBC could run the 'SELECT 42':

![image](https://user-images.githubusercontent.com/403295/126333641-cf0bf8a5-13eb-4e87-8270-661746d7d17d.png)

**Comment by kimmolinna** [comment]
Did you already commit the change? ;)

**Comment by tiagokepe** [comment]
Not yet, maybe later today or tomorrow.

**Comment by kimmolinna** [comment]
Great. It's almost there but SQLRowCount causes some problems. 
This is for isql PostgreSQL
```
SQL> CREATE TABLE people(id INTEGER, name VARCHAR);
SQLRowCount returns -1
SQL> INSERT INTO people VALUES (1, 'Mark'), (2, 'Hannes');
SQLRowCount returns 2
SQL> select * from people
+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id         | name                                                                                                                                                                                                                                                           |
+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1          | Mark                                                                                                                                                                                                                                                           |
| 2          | Hannes                                                                                                                                                                                                                                                         |
+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
SQLRowCount returns 2
2 rows fetched
```
And this is for DuckDB
```
SQL> CREATE TABLE people(id INTEGER, name VARCHAR);
+---------------------+
| Count               |
+---------------------+
+---------------------+
SQLRowCount returns -1
SQL> INSERT INTO people VALUES (1, 'Mark'), (2, 'Hannes');
+---------------------+
| Count               |
+---------------------+
| 2                   |
+---------------------+
SQLRowCount returns -1
1 rows fetched
SQL> select * from people
+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id         | name                                                                                                                                                                                                                                                                                                        |
+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1          | Mark                                                                                                                                                                                                                                                                                                        |
| 2          | Hannes                                                                                                                                                                                                                                                                                                      |
+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
SQLRowCount returns -1
2 rows fetched
```

**Comment by kimmolinna** [comment]
@tiagokepe Can you reproduce the SQLRowCount problem?

**Comment by tiagokepe** [comment]
@kimmolinna I reproduced that issue and tried to fix, but it worked partially only on select statements. I am finishing another feature, and then I will return to the SQLRowCount.

**Comment by tiagokepe** [comment]
> @tiagokepe Can you reproduce the SQLRowCount problem?

@kimmolinna take a look at commit https://github.com/tiagokepe/duckdb/commit/5060a10e1dac72b188ff6b43aab03f1138805eab

The SQLRowCount is slightly different than Postgres, but it has the same row count of the DuckDB C++ code: 
![image](https://user-images.githubusercontent.com/403295/126990871-3ce849c0-fc4b-4aea-a9e2-76a7fe5bd634.png)

**Comment by kimmolinna** [comment]
Still I have the same problem. Describe is working nicely.
```
0   Cursor DD.s1: Status=Executed, MaxRows=50     
                                                  
    select * from people                          
                                                  
    Bind Vars: 0                                  
     Name  APL  DB  Prec.  Scale  Length    Buf   
                                                  
    Select vars: 2                                
     Name  APL  DB  Prec.  Scale  Length    Buf   
     id    ?    I       0      0       0 I  ?     
     name  ?    V       0      0       0 V  ?     
```
But Fetch doesn't.
```
[ODBC][37109][1627329196.013573][SQLSetStmtAttr.c][265]
		Entry:
			Statement = 0x5635425b68a0
			Attribute = SQL_ATTR_ROW_BIND_TYPE
			Value = (nil)
			StrLen = 0
[ODBC][37109][1627329196.013679][SQLSetStmtAttr.c][928]
		Exit:[SQL_ERROR]
[ODBC][37109][1627329196.013700][SQLGetDiagField.c][958]
		Entry:
			Statement = 0x5635425b68a0
			Rec Number = 0
			Diag Ident = 2
			Diag Info Ptr = 0x7fffaa257e28
			Buffer Length = 4
			String Len Ptr = 0x7fffaa257e1e
[ODBC][37109][1627329196.013716][SQLGetDiagField.c][990]
		Exit:[SQL_SUCCESS]
[ODBC][37109][1627329196.013730][SQLError.c][424]
		Entry:
			Statement = 0x5635425b68a0
			SQLState = 0x7fffaa257c00
			Native = 0x7fffaa257e14
			Message Text = 0x7fffaa257a00
			Buffer Length = 512
			Text Len Ptr = 0x7fffaa257956
[ODBC][37109][1627329196.013743][SQLError.c][474]
		Exit:[SQL_NO_DATA]
```

**Comment by kimmolinna** [comment]
The situation is still same for me.
```
[ODBC][10147][1627930298.001614][SQLSetStmtAttr.c][928]
		Exit:[SQL_ERROR]
```

**Comment by tiagokepe** [comment]
@kimmolinnaI I could not reproduce your reported error. In the _odbctrace_ informed, the error is related to passing NULL values to the SQLSetStmtAttr, fixed in the commit https://github.com/duckdb/duckdb/pull/2082/commits/cec7b109d335a998a3b689c4bb19210677c396a3 

I tried it on my environment, and it was executed successfully:

```
[ODBC][12350][1628165504.003260][SQLSetStmtAttr.c][265]
                Entry:
                        Statement = 0x61c000007080
                        Attribute = SQL_ATTR_ROW_BIND_TYPE
                        Value = (nil)
                        StrLen = 0
[ODBC][12350][1628165504.003281][SQLSetStmtAttr.c][928]
                Exit:[SQL_SUCCESS]
```

I also tested the SQL queries you've tried to run with _isql_, and the results are the following:

![image](https://user-images.githubusercontent.com/403295/128353114-5747dcfe-3aee-4d75-a21e-9b20325d5836.png)


Could you provide the complete sequence of SQL queries you are trying to run?

**Comment by kimmolinna** [comment]
@tiagokepe Basically the problem has been the same all the time. Prepare, Execute and Describe are working but Fetch returns an error in my ODBC client. I don't know what is different between Postgresql and DuckDB. Even with `isql` the output is a bit different:
DuckDB
```
select 42;
+------------+
| 42         |
+------------+
| 42         |
+------------+
```
Postgresql
```
select 42;
+------------+
| ?column?   |
+------------+
| 42         |
+------------+
```
And my ODBC client doesn't have any problem fetch number 42 from Postgresql. Somehow I can't fetch all from DuckDB at once.
DuckDB
```
       SQA.Do 'DD' 'Select 42'
...
       1 Fetch cursor
4 9999  Unable to retrieve Errormessage  0
        1 Fetch cursor
0           6
        1 Fetch cursor
1 10043    0
```
compared to Postgresql
```
       SQA.Do 'PG' 'Select 42'
...
      1 Fetch cursor
0   42       6
       1 Fetch cursor
1 10043    0
```

**Comment by tiagokepe** [comment]
> @tiagokepe Basically the problem has been the same all the time. Prepare, Execute and Describe are working but Fetch returns an error in my ODBC client.

@kimmolinna  I suppose you were using only the _isql_ ODBC client. Which ODBC client are you using now, and SO?

**Comment by kimmolinna** [comment]
@tiagokepe I'm using SQAPL with unixODBC in DyalogAPL. I has been working nicely with all others which are functional also with isql.

**Comment by kimmolinna** [comment]
@tiagokepe I don't know what have you done. But now Select 42 is working. Thank you very much!

**Comment by hannesmuehleisen** [comment]
@kimmolinna given that this is a quite obscure setup, would you mind sharing some instructions how to run the now-infamous `SELECT 42` through SQAPL in DyalogAPL? Thanks!

**Comment by kimmolinna** [comment]
@hannesmuehleisen So basically SQAPL in DyalogAPL is like Excel. It's using ODBC-driver for a connection and in my setup It is using unixODBC on Kubuntu 21.04.

The connection is established and then the order is the following:
1. Get a cursor name
2. Prepare a statement
3. Execute it
4. Get a description
5. Fetch the data if there are Bind Vars.

The four first steps has been working all the time. There was some problems to fetch the data. And still the output is a bit different between PostgreSQL and DuckDB but it's working. I think that @tiagokepe can tell you what changes he had to make to get this working. If I noticed correctly he used nanodbc to test the connection.

**Comment by hannesmuehleisen** [comment]
Can you share a reproducible example please? Script?

**Comment by kimmolinna** [comment]
Of course I can. odbc is using Postgresql database driver. 
```
     ]boxing on
Was ON
    )load sqapl
/opt/mdyalog/18.0/64/unicode/ws/sqapl.dws saved Fri Dec 11 03:05:45 2020
    SQA.Init ''
┌─┬────────────────────────────────────────────────────────────────────────────
│0│SQAPL loaded from: cxdya63u64v.so Using default translation no aplunicd.ini 
└─┴────────────────────────────────────────────────────────────────────────────

      ───────┐
      present│
      ───────┘
    SQA.Connect 'DD' 'duckdb'
0
    SQA.Do 'DD' 'Select 42'
┌─┬─────┬────┬──┬─┐
│0│DD.s1│┌──┐│┌┐│6│
│ │     ││42│││││ │
│ │     │└──┘│└┘│ │
└─┴─────┴────┴──┴─┘
    SQA.Connect 'PG' 'odbc'
0
    SQA.Do 'PG' 'Select 42'
┌─┬─────┬────┬──┬─┐
│0│PG.s1│┌──┐│┌┐│6│
│ │     ││42│││││ │
│ │     │└──┘│└┘│ │
└─┴─────┴────┴──┴─┘
    SQA.Do 'DD' 'Create table people (id INTEGER, name VARCHAR)'
┌─┬─────┬───┬──┬─┐
│0│DD.s1│┌─┐│┌┐│6│
│ │     │└─┘││││ │
│ │     │   │└┘│ │
└─┴─────┴───┴──┴─┘
    SQA.Do 'PG' 'Create table people (id INTEGER, name VARCHAR)'
┌─┬─────┬┐
│0│PG.s1││
└─┴─────┴┘
      
```
