### ISSUE TITLE
Support RANGE in OVER clauses

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#2016]
Currently this is only supported for `CURRENT ROW`.

The approach I am considering is to make `RANGE` and `ROWS` orthogonal constructs but treat the computed start/end expressions differently. For `ROWS` the behaviour would. be unchanged (i.e., `BIGINT`), but for `RANGE`, the values would contain the result of adding/subtracting the expression from the order key. This would mean that we could support range framing for any type that could be ordered and has a corresponding distance type such as temporal types and intervals. 

For example:

```sql
SELECT h.date, 
MEDIAN(kwh) OVER (
    ORDER BY h.date 
    RANGE BETWEEN interval 7 days PRECEDING AND CURRENT ROW) mkwh
FROM generation_history h
```
computes a trailing 7-day moving median power generation graph that makes no assumptions about curtailed plants being missing and throwing off the window size.

**Comment by Alex-Monahan** [comment]
This would be super awesome for time series use cases, or for ML pre-processing steps!

**Comment by hawkfish** [comment]
Oracle has a [decent description](https://docs.oracle.com/cd/E17952_01/mysql-8.0-en/window-functions-frames.html) of the boundary conditions involving `NULL`s and `DESC`.

**Comment by hawkfish** [comment]
There is still some perf work to do, but that will be a separate issue.
