### ISSUE TITLE
Example multi-threaded query?

### ISSUE THREAD

**Issue by erikcw** [duckdb/duckdb#2019]
I've been benchmarking my queries with duckdb and I noticed that they all seem to only use 1 core (monitoring from htop).

I went through the docs and wasn't able to find an example of how to make queries leverage multiple cores (the copy on the homepage mentions "Parallel query processing".

Can you provide an example of a query that can leverage multiple cores?  Is there a setting that needs to be passed to the connection (or elsewhere) from the Python API?  Are there circumstances where duckdb is unable to run multi-threaded (types of queries perhaps)?

Thank you!

**Comment by Alex-Monahan** [comment]
Howdy!

Just execute Pragma threads=4 or similar!

[Pragma documentation](https://duckdb.org/docs/sql/pragmas)

**Comment by Alex-Monahan** [comment]
So, as a Python example (untested):
con = duckdb.connect(':memory:')
con.execute('PRAGMA threads=4')
... subsequent operations on the connection will use up to 4 threads!

Note, there aren't Python threads, they are C++ threads, so they are fully parallel (no Python GIL...)!

**Comment by erikcw** [comment]
I've tried that but it doesn't seem to make a difference:

```python
In [48]: cursor = duckdb.connect()

In [49]: %time cursor.execute(f"SELECT status, count(s), count(distinct m) FROM read_csv_auto('{path}') GROUP BY status").df()
CPU times: user 11.5 s, sys: 496 ms, total: 12 s
Wall time: 11.9 s
Out[49]:
    status  count(s)  count(m)
0      NaN                   3572026      1933742
1  New                     24584         1566
2  Updated                      3590         1536

In [50]: cursor.execute('PRAGMA threads=8')
Out[50]: <duckdb.DuckDBPyConnection at 0x7f2397c8c0f0>

In [51]: %time cursor.execute(f"SELECT status, count(s), count(distinct m) FROM read_csv_auto('{path}') GROUP BY status").df()
CPU times: user 12.3 s, sys: 825 ms, total: 13.1 s
Wall time: 13 s
Out[51]:
    status  count(s)  count(m)
0      NaN                   3572026      1933742
1   New                     24584         1566
2  Updated

```

I was watching htop while running this and both the threaded and non threaded version seem to just pin a single core to 100%.

Are there certain classes of queries that are able to leverage duckdb's parallelism better than others?

**Comment by Mytherin** [comment]
`count(distinct)` indeed disables parallelism right now. If accuracy is not extremely important here you can use `approx_count_distinct` instead, which uses HLL to calculate an approx distinct count and should support parallel computation.
