### ISSUE TITLE
Exception while reading csv

### ISSUE THREAD

**Issue by chilarai** [duckdb/duckdb#2023]
**What does happen?**
I downloaded the src of Duckdb v0.2.7 and compiled the code to obtain a dll and a lib file for my project using MSVC 2019. The code seems to break at the following line mostly when type checks are strict. It passes while debugging.

```
std::unique_ptr<duckdb::MaterializedQueryResult> res = con.Query("CREATE TABLE test AS SELECT * FROM read_csv_auto(test)");
```

It throws the following error. Seems like my system address has been hardcoded into the release binary

```
Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\execution\operator\persistent\buffered_csv_reader.cpp:1147

Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\common\vector_operations\vector_cast.cpp:27

Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\common\operator\cast_operators.cpp:622

Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\function\scalar\date\strftime.cpp:1118

Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\common\types\time.cpp:120

Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\common\types\timestamp.cpp:26

Exception at 0x7fffb4534ed9, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\ttt\Downloads\duckdb-0.2.7\duckdb-0.2.7\src\common\types\date.cpp:280
```

**Environment (please complete the following information):**
 - Windows 10 x64
 - DuckDB Version 0.2.7

**Comment by hannesmuehleisen** [comment]
Can you share the file please?

**Comment by chilarai** [comment]
Attached a sample csv file.
[Orders.zip](https://github.com/duckdb/duckdb/files/6839222/Orders.zip)

**Comment by Mytherin** [comment]
The CSV reader internally throws exceptions, however, these are caught and handled by the system. I suspect that your IDE/debugger is breaking on exceptions being thrown whether they are caught or not. This is not a bug in the system, and testing with your file it seems that the file is correctly read and no uncaught exception is thrown. Nevertheless this should be changed since using exceptions for control flow is rather dirty. See also issue #998.

**Comment by chilarai** [comment]
Indeed. QT doesn't accept exceptions in release mode
