### ISSUE TITLE
H2OAI Query 10 triggers an assertion when executed in debug mode.

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#2025]
Running test/db-benchmark/groupby.test_slow on debug mode should trigger this.

Query:
```sql
CREATE TABLE ans
AS SELECT id1, id2, id3, id4, id5, id6, sum(v3) AS v3, count(*) AS count 
FROM x 
GROUP BY id1, id2, id3, id4, id5, id6;
```

 RuntimeError: INTERNAL Error: Assertion triggered in file "/Users/holanda/Documents/Projects/duckdb/src/execution/aggregate_hashtable.cpp" on line 680: !is_finalized

**Comment by hawkfish** [comment]
Tried this on my laptop, but I think you need 16 real cores to reproduce.

**Comment by pdet** [comment]
So this is interesting, the reason that I came across this problem is that I execute this benchmark as a test for my arrow stuff.

In there I set the number of threads equal to four when testing parallelism.

You are right when running the test (test/db-benchmark/groupby.test_slow ) with the default 16 threads it executes properly, but it starts breaking when I change it to 4 threads.

**Comment by hawkfish** [comment]
Sigh I can't repro on any of my machines.

**Comment by pdet** [comment]
We were struck again about this issue when trying to run Arrow tests on the code cov:
https://github.com/Mytherin/duckdb/runs/3251525927?check_suite_focus=true

**Comment by hannes** [comment]
Does not trigger on my laptop, I guess its fixed. Feel free to reopen if not.
