### ISSUE TITLE
Python relational API: RuntimeError: INTERRUPT Error: Interrupted!

### ISSUE THREAD

**Issue by erikcw** [duckdb/duckdb#2027]
I'm trying to read in a CSV file to manipulate with the Python relational API.  Doing so yields an unfortunatly unhelpful exception.

```python
import duckdb
path = "/tmp/my.csv"


In [48]: rel = duckdb.from_query(f"SELECT * FROM read_csv_auto('{path}', ALL_VARCHAR=1)")

In [49]: rel.limit(10).fetchall()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-49-59d01e448486> in <module>
----> 1 rel.limit(10).fetchall()

RuntimeError: INTERRUPT Error: Interrupted!

In [50]: rel.limit(10).df()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-50-468b74519ff6> in <module>
----> 1 rel.limit(10).df()

RuntimeError: INTERRUPT Error: Interrupted!

```

The same also seems to happen if I try to access the same data from parquet:

```python
In [51]: rel = duckdb.from_parquet(str(parquet_path))

In [52]: rel.limit(10).df()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-468b74519ff6> in <module>
----> 1 rel.limit(10).df()

RuntimeError: INTERRUPT Error: Interrupted!
```

Reading in the CSV file using the SQL interface works fine, so I don't think there are any issues with my data (also confirmed that pandas can read it without trouble):

```python
cursor = duckdb.connect()
cursor.execute(f"SELECT * FROM read_csv_auto('{path}', ALL_VARCHAR=1) limit 10").df()
```

Side note -- I'm trying to use `duckdb.from_query` because `duckdb.from_csv_auto` only accepts the file name as an argument.  There does not seem to be a way to pass additional arguments such as `ALL_VARCHAR=1`.

```python
In [17]: duckdb.from_csv_auto?
Docstring:
from_csv_auto(file_name: str) -> duckdb.DuckDBPyRelation

Creates a relation object from the CSV file in file_name
Type:      builtin_function_or_method
```

**Comment by Mytherin** [comment]
Could you try running this on the master branch (using pip install duckdb - -pre, without the space in between the dashes)? This seems similar to an issue I fixed recently.

**Comment by erikcw** [comment]
@Mytherin -- yup, works fine on master.  Sorry for the duplicate issue.

Are there any plans to add arguments such as `ALL_VARCHAR=1` to `duckdb.from_csv_auto`?

**Comment by Mytherin** [comment]
> @Mytherin -- yup, works fine on master. Sorry for the duplicate issue.

Great!

> Are there any plans to add arguments such as `ALL_VARCHAR=1` to `duckdb.from_csv_auto`?

Not on the immediate agenda, but feel free to open an issue requesting it!

**Comment by Mytherin** [comment]
Closing this issue as it has been fixed. Feel free to open a new issue requesting for more options in the from_csv_auto.
