### ISSUE TITLE
`show tables` returns system tables after dropping user tables and reconnect the database file (starting from version 0.2.7)

### ISSUE THREAD

**Issue by ZhengRui** [duckdb/duckdb#2028]
**What does happen?**
before version 0.2.7, `show tables` is consistent and only return user tables, since version 0.2.7, it returns system tables if I reconnect the database file

**What should happen?**
only return user defined tables

**To Reproduce**
run this `test.py` file with any `test.parquet`:
```python
import duckdb

conn = duckdb.connect('./test.db')
cursor = conn.cursor()

print('empty: ', cursor.execute('show tables').fetchall())

cursor.execute("create table anno as select * from parquet_scan('./test.parquet')")

print('anno table created: ', cursor.execute('show tables').fetchall())

cursor.execute("drop table if exists anno")

print('anno table dropped: ', cursor.execute('show tables').fetchall())

cursor.close()
conn.close()


conn = duckdb.connect('./test.db')
cursor = conn.cursor()

print('tables empty ? ', cursor.execute('show tables').fetchall())

cursor.close()
conn.close()
``` 

for version 0.2.6, it prints:
```bash
empty:  []
anno table created:  [('anno',)]
anno table dropped:  []
tables empty ?  []
```

for version 0.2.7, it prints:
```bash
empty:  []
anno table created:  [('anno',)]
anno table dropped:  []
tables empty ?  [('columns',), ('duckdb_columns',), ('duckdb_constraints',), ('duckdb_indexes',), ('duckdb_schemas',), ('duckdb_tables',), ('duckdb_types',), ('duckdb_views',), ('pg_am',), ('pg_attrdef',), ('pg_attribute',), ('pg_class',), ('pg_constraint',), ('pg_depend',), ('pg_description',), ('pg_enum',), ('pg_index',), ('pg_indexes',), ('pg_namespace',), ('pg_sequence',), ('pg_sequences',), ('pg_tables',), ('pg_tablespace',), ('pg_type',), ('pg_views',), ('pragma_database_list',), ('schemata',), ('sqlite_master',), ('sqlite_schema',), ('sqlite_temp_master',), ('sqlite_temp_schema',), ('tables',)]
```

**Environment (please complete the following information):**
 - OS: OSX Catalina 10.15.4
 - DuckDB Version: 0.2.7 vs 0.2.6

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm this issue. I have pushed a fix in #2048 that should resolve the problem.
