### ISSUE TITLE
Add Support for Pandas Period data type

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#2030]
**What does happen?**
A pandas DataFrame containing columns of type "Period" cannot be registered as a View as the data type is not currently supported.  Any such columns must first be converted to timestamps.

**What should happen?**
Convert Period columns to timestamp value automatically.  

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
```
import pandas as pd
import duckdb

con = duckdb.connect()

# throws RuntimeError: unsupported python type period[D]
df = pd.DataFrame(pd.Series(pd.Period(freq='D', year=2021, month=1, day=1)))
try:
    con.register('test', df)
except Exception as e:
    print(e)

# resolves RuntimeError
df = pd.DataFrame(df[0].apply(pd.Period.to_timestamp))
con.register('test', df)
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - DuckDB Version: 0.2.7

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
We might just call to_timestamp internally as well

**Comment by hawkfish** [comment]
What does pandas mean by "Period" (the documentation is [singularly unhelpful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Period.html) )? My understanding of [temporal analytics terminology](https://www2.cs.arizona.edu/~rts/pubs/EDC.pdf) is that a period is a bounded temporal interval (usually half-open). There are no SQL-92 types that map to this, so it is not clear how we could import it - although maybe a `STRUCT` with canonical members `begin` and `end` could be used?
