### ISSUE TITLE
parquet_scan is not available in CLI OSX binaries for versions 0.26 and 0.27

### ISSUE THREAD

**Issue by rberenguel** [duckdb/duckdb#2033]
**What does happen?**
Can't select, create view or copy from Parquet file, with error 

```
Error: Catalog Error: Table Function with name parquet_scan does not exist!
Did you mean "arrow_scan"?
LINE 1: CREATE VIEW events AS SELECT * FROM parquet_scan('ev.parquet');
```

**What should happen?**
According to the documentation ([here](https://duckdb.org/docs/data/parquet)) I would expect a view to be created over this Parquet file (or copy, or insert, depending on command, none work obviously). This works correctly in at least 0.25 and 0.28 (master) locally.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. Install (or download and execute) duckdb versions 0.26 or 0.27 from GitHub, the MacOS CLI binary in particular.
2. Execute the above query (will fail before even reaching for the file so no problem about not having it)

**Environment (please complete the following information):**
 - OS: Mac OS Big Sur 11.4
 - DuckDB Version 0.26 and 0.27

**Before submitting**
- [*] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [*] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

This is working in 0.28 (master binary above) but failing in 0.26 and 0.27

**Comment by jfgreen** [comment]
Looks like I'm getting the same behaviour on 0.2.8 installed via homebrew on Big Sur 11.3.

**Comment by matthewmueller** [comment]
Also failing on 0.2.9 1776611ab installed via homebrew.

**Comment by domoritz** [comment]
I just ran into the same issue. 0.2.9 1776611ab installed via homebrew.

**Comment by hannesmuehleisen** [comment]
We don't maintain the homebrew formula. Maybe we should start to do so.

**Comment by rberenguel** [comment]
@hannesmuehleisen that may be unrelated (although it would be good to do). My original issue was with binaries downloaded from github, but certainly 0.2.8 had parquet working. If homebrew has 0.2.8 not working (haven't checked myself) it could be more of an issue in the formula.

**Comment by Aloisius** [comment]
Parquet is in fact disabled in the homebrew package. I've submitted PR Homebrew/homebrew-core#90852  that largely matches the binary release with the exception of leaving the JDBC driver out.

**Comment by hannes** [comment]
We now have installable extensions, so this should no longer be an issue.
