### ISSUE TITLE
Memory errors happening during a parquet query over a range of files

### ISSUE THREAD

**Issue by rostislavdeepcrawl** [duckdb/duckdb#2035]
**What does happen?**
A number of different errors happen during one particular query:
`duckdb::OutOfRangeException: what():  Out of Range Error: Not enough memory to complete operation: could not allocate block of 285751568 bytes`
`Error: IO Error: Could not write all bytes to file ".tmp/4611686018427424834.block": wanted=2687930368 wrote=2147479552`
`SegmentationFault`

Plus, a lot of memory being used (up to 30GB).

The query: `SELECT * FROM parquet_scan('<folder>/*.parquet') AS curr_crawl WHERE url <> '' AND ((css <> TRUE OR css IS NULL) AND (js <> TRUE OR js IS NULL) AND (is_image <> TRUE OR is_image IS NULL) AND internal = TRUE) ORDER BY deeprank DESC`.

The files total 777 mb in size.

**What should happen?**
The query should be executed successfully. 

**To Reproduce**
There are a couple of ways to reproduce.

Running the query with `PRAGMA threads=6;`:
1. `PRAGMA threads=6;`
2. `SELECT * FROM parquet_scan('<folder>/*.parquet') AS curr_crawl WHERE url <> '' AND ((css <> TRUE OR css IS NULL) AND (js <> TRUE OR js IS NULL) AND (is_image <> TRUE OR is_image IS NULL) AND internal = TRUE) ORDER BY deeprank DESC`
3.  One of the errors above happens, or execution takes 15+ mins and not ending and 30GB of memory being used or execution succeeding in adequate time but again with 30GB being used.

Not using `PRAGMA threads=6;`:
1. `SELECT * FROM parquet_scan('<folder>/*.parquet') AS curr_crawl WHERE url <> '' AND ((css <> TRUE OR css IS NULL) AND (js <> TRUE OR js IS NULL) AND (is_image <> TRUE OR is_image IS NULL) AND internal = TRUE) ORDER BY deeprank DESC`
2. The query might complete successfully or might get `Error: IO Error: Could not write all bytes to file ".tmp/4611686018427424834.block": wanted=2687930368 wrote=2147479552` or `SegmentationFault`

I'm sending the files to you guys.

**Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - DuckDB Version: latest master/0.0.27

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by lnkuiper** [comment]
This may have something to do with the ORDER BY clause. I found something similar last week, and was planning on investigating the problem this week. I will get right on it!

**Comment by hannesmuehleisen** [comment]
@rostislavdeepcrawl I would also appreciate attempts to minify the test case because otherwise we have to do this.

**Comment by rostislavdeepcrawl** [comment]
> @rostislavdeepcrawl I would also appreciate attempts to minify the test case because otherwise we have to do this.

```
PRAGMA threads=6;
SELECT * FROM parquet_scan('<directory>/*.parquet')  ORDER BY deeprank
```

**Comment by lnkuiper** [comment]
First of all, thank you for sharing the data. Parquet files have compression, and apparently, the data is very compressible, as it takes up somewhere between 5-10GB in memory (which is unsurprising with 2M rows and 317 columns), while on disk it takes 777MB as you said.

The `PhysicalOrder` operator underwent many changes lately, and now it puts the buffer manager under heavy load. I've changed a few things (in my branch), and I've got it to work when executed in a single thread. I will send a PR with these changes soon, hopefully before the next release.

I am currently trying to figure out how to get it to work with multiple threads. It seems that the buffer manager cannot handle the heavy load, but I am not sure why.

**Comment by lnkuiper** [comment]
We've tracked down the bug. There was an issue with the buffer manager when the same block was being pinned by multiple threads at the same time, causing the buffer manager to think that it was using tons of memory, when in fact it was not.

The query completed in 97s on my laptop with 6 threads. I will send a PR for this when the CI finishes in my own branch, hopefully just in time for the next release!

**Comment by rostislavdeepcrawl** [comment]
> We've tracked down the bug. There was an issue with the buffer manager when the same block was being pinned by multiple threads at the same time, causing the buffer manager to think that it was using tons of memory, when in fact it was not.
> 
> The query completed in 97s on my laptop with 6 threads. I will send a PR for this when the CI finishes in my own branch, hopefully just in time for the next release!

Awesome, thank you very much!
