### ISSUE TITLE
segfault in node.js on missing paths

### ISSUE THREAD

**Issue by bmschmidt** [duckdb/duckdb#2037]
**What does happen?**

Thanks for this excellent project. I have been trying the node.js version and it seems frequently to segfault on minor errors, including but perhaps not limited to when a db path is a nonexistent folder. (For the record, I find it remarkable that you've even worried about putting out a node.js version at all, and certainly don't mind if it's buggy in this way! Just thought you might like to know.)

**What should happen?**

Error should be raised instead of segfault.

**To Reproduce**

1. Save the following script at `tmp.cjs`.
2. Run `node tmp.cjs`.

```javascript
var duckdb = require('duckdb');
var db = new duckdb.Database('nonexistent_folder/db.duckdb');
db.all('SELECT 42 AS fortytwo', function(err, res) {
  if (err) {
    throw err;
  }
  console.log(res[0].fortytwo)
});
```

The segfault seems to happen inside the query, not on the db creation.

**Environment (please complete the following information):**
 - OS: OS X 10.15.7
 - DuckDB Version 0.2.8-dev744.0

**Before submitting**
- [Yes] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [0.2.8dev744.0--so like a week old?] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannes** [comment]
This should be fixed?
