### ISSUE TITLE
No error displayed after an INSERT violates a UNIQUE constraint

### ISSUE THREAD

**Issue by Ziink** [duckdb/duckdb#2040]
Creating a unique index then inserting duplicates doesn't show any error. See related #514

```CREATE TABLE t0(c0 INT);
CREATE UNIQUE INDEX i0 ON t0(c0);
INSERT INTO t0(c0) VALUES (1);
INSERT INTO t0(c0) VALUES (1); -- expected error, actual no error
SELECT * FROM t0 WHERE t0.c0 = 1; -- as expected : expected: {1}, actual: {1}
```
However, if we create the table with the unique constraints, then constraint error is printed as it should.

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2052.
