### ISSUE TITLE
Cannot open database when even one table gets corrupt

### ISSUE THREAD

**Issue by Ziink** [duckdb/duckdb#2045]
The problem I encountered is reported in #1976  and #1625. 

However, I'm creating a new bug report to highlight that a table related bug shouldn't trash the entire db. I don't see a way to recover the other tables in the database or to delete the problematic one. 

I think this should be a high priority fix. Even before implementing index storage or vacuuming.

**Comment by Mytherin** [comment]
Fair enough. I will have a look at this today.
