### ISSUE TITLE
Cleanup after execution of invalid SQL statement causes segmentation fault

### ISSUE THREAD

**Issue by kambo-1st** [duckdb/duckdb#2058]
**What does happen?**
After execution of invalid SQL statement any attempt to cleanup  "duckdb_result" structure with function `duckdb_destroy_result`  leads into segmentation fault. This happens only if we already perform any query returning data.

**What should happen?**
There should be no segmentation fault and execution of program should continue.

**To Reproduce**
Please compile and run following code snippet, during execution of line "duckdb_destroy_result(&result); // segmentation failure happens here"  segmentation fault occurs: 

```c
#include "duckdb.h"
#include <string.h>

int main() {
    duckdb_database db;
    duckdb_connection con;
    duckdb_result result;
    duckdb_result result_count;

    if (duckdb_open(NULL, &db) == DuckDBError) {
        // handle error
    }
    if (duckdb_connect(db, &con) == DuckDBError) {
        // handle error
    }

    // create a table
    if (duckdb_query(con, "CREATE TABLE integers(i INTEGER, j INTEGER);", NULL) == DuckDBError) {
        // handle error
    }

     // insert three rows into the table
    if (duckdb_query(con, "SELECT count(*) FROM integers;", &result_count) == DuckDBError) {
        // handle error
    }

    duckdb_destroy_result(&result_count);

    if (duckdb_query(con, "non valid SQL", &result) == DuckDBError) {
        duckdb_destroy_result(&result); // segmentation failure happens here
    }

    return 0;
}
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 20.4
 - DuckDB Version: 0.2.7, fails also on master (I used precompiled binaries)

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm this segfaults. I have pushed a fix in #2107.
