### ISSUE TITLE
Querying Relation causes downstream issues with show_tables PRAGMA

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#2067]
**What does happen?**
Querying a relation using a virtual table name interferes with other functionality.  

After creating a relation from a DataFrame and querying it using the ```.query()``` method, the ```show_tables``` PRAGMA throws the following error:

```RuntimeError: Not implemented Error: Cannot convert VIEW to SQL because it was not created with a SQL statement```

Note that even after closing the connection to the database and opening a new one, ```show_tables``` still throws an error.

**What should happen?**
Should simply show the tables as usual.  I don't see why Views would interfere with this anyways, as they are not returned by the show_tables pragma.  Even so, querying a relation shouldn't cause any downstream issues.

**To Reproduce**
```
# connect to database
con = duckdb.connect(database='sandbox')

# make some example dataframe
df = pd.DataFrame([1],columns=['id'])

# create relation from df and query it
rel = con.from_df(df)
rel.query('tmp', 'select * from tmp')

# show tables
con.execute('pragma show_tables')
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - DuckDB Version [0.2.7]

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Admolly** [comment]
Seems semi-related to ([https://github.com/duckdb/duckdb/issues/1189](1189))

**Comment by Mytherin** [comment]
I think this has been fixed in #1953. This seems to work for me in the master branch. Have you tried it on the latest master branch?

**Comment by Admolly** [comment]
I tried ```pip install duckdb --pre```, is that the wrong command?

**Comment by Mytherin** [comment]
That should be the correct command indeed. Perhaps it is still using the old version somehow? What does `duckdb.__version__` say?

**Comment by Admolly** [comment]
yeah so it appears to have been a problem w/my machine.  After uninstalling, then re-installing using --pre, I was able to get the correct result.  Sorry for the trouble I will close the issue.

**Comment by Mytherin** [comment]
No problem. Glad it was resolved.
