### ISSUE TITLE
DataFrame with native python float values causes problem with 'con.register'ed views

### ISSUE THREAD

**Issue by Ziink** [duckdb/duckdb#2072]
In version .27 on Windows 10.

Don't have a reproducible list of steps yet but it might not be needed.

IMPORTANT: The type of the value in a column should be native python float. I don't know how to create such a dataframe directly but I got it by creating a duckdb table with a column of type REAL. Whenever, I try to create a df directly with float values, it ends up with numpy.float32 or other numpy float values.

Whenever, you register a dataframe with such values and then read it back with a select statement, you get None or NaN depending on whether fetchall or fetchdf was used.

Please let me know if this info isn't enough and you want me to create a script that causes this problem.

Edit: There were other columns with type REAL that worked fine. Only the columns that had NaN values caused the problem.

Edit 2: Converting the df columns before setting up the view works fine - even with the NaN. So the following snippet worked. Without the first line, all values were being returned as NaN.

```
alldf[['open', 'high', 'low', 'close']] = alldf[['open', 'high', 'low', 'close']].astype('float32')

flat.con.register('view', alldf.view)

flat.con.execute('select * from view').fetchdf()
```

**Comment by Mytherin** [comment]
Could you make an example of what you mean here? This might actually be intended behavior.

DuckDB does not allow `NaN` values to exist inside the engine. Instead, `NaN` values are converted to `NULL` values when you try to import data into DuckDB. 

When a NULL value is fetched, it is converted into `None` using fetchall. In fetchdf, the data is converted into whatever Pandas wants a NULL value to be, which is type dependent. For float values, this is `NaN` again. 

Is this the behavior you are observing here?

**Comment by Ziink** [comment]
```import duckdb
import pandas as pd

con = duckdb.connect(database=':memory:', read_only=False)
x = pd.DataFrame([[1, 'a', 2],[1, None, 2], [1, 1.1, 2], [1, 1.1, 2], [1, 1.1, 2]])
x = x.iloc[2:].copy()       # middle col now entirely native float items
print(type(x.iloc[1,1]))   # output is: <class 'float'>
con.register('view2', x)
df = con.execute('select * from view2').fetchdf()
print(df)


Output is:
    0    1  2
 0  1  NaN  2
 1  1  NaN  2
 2  1  NaN  2
```

So I guess, con.register does not recognize python native floats. I think it should since I ended up with it while wrangling stock prices. They are stored as objects in the dataframe rather than numpy types.

**Comment by pdet** [comment]
That makes sense, object types are currently assumed to be strings. I'll have a look at this.

**Comment by pdet** [comment]
@Ziink Since the pandas column is an object type, there is no guarantee that the whole column will be from a certain native type before fully scanning it.

I've implemented a conversion step for these object types to strings. Then you could just cast it when querying it afterward for the desired data type.

**Comment by Ziink** [comment]
That sounds good enough. Thanks.
