### ISSUE TITLE
No Longer Convert Identifiers to Lower Case?

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#2075]
A remnant from the Postgres parser is that unquoted identifiers will be automatically converted into lower case, e.g. the following create statements are equivalent

```sql
CREATE TABLE MyTable(MyColumn INTEGER);
CREATE TABLE "mytable"("mycolumn" INTEGER);
```

We have added case insensitivity to many areas in the binder (and are adding more #2071), which makes this behavior a lot less annoying to deal with. However, when interfacing with other APIs this case folding might lead to surprising behavior.

For example, if we have a query such as this:

```sql
SELECT MyColumn + 1 AS MyAddition FROM MyTable
```

And then convert the result into e.g. a Pandas DataFrame, or write it to a Parquet file, the column name will be lowercased (to "myaddition"). This makes subsequent operations on these external structures rather confusing.

The work-around for this is to quote the values, which preserves the case. However, that is not obvious to beginners and probably not what we want to have in the first place.

Perhaps we should remove this automatic lowercasing of identifiers, as we already handle case-insensitivity at the binder level we don't need to handle it in the parser/transformer.

**Comment by Alex-Monahan** [comment]
If you end up going this route, I would probably mention it in the release notes! Since Pandas is case sensitive, this could break some scripts.

Personally I like the all lowercase lifestyle, but that's me! I understand why you might want to make the change, and that you are still in Beta after all.

**Comment by Mytherin** [comment]
> If you end up going this route, I would probably mention it in the release notes! Since Pandas is case sensitive, this could break some scripts.

Yes, for sure we will have to make this clear in the release notes. The fact that Pandas is case sensitive would actually be one of the main reasons for making this change!

Another would be better compatibility with SQLite, since SQLite does maintain the case as described in the query:

```py
>>> import sqlite3
>>> con = sqlite3.connect(":memory:")
>>> c = con.execute('select 42 as MyColumn')
>>> print(c.description)
(('MyColumn', None, None, None, None, None, None),)
>>> pd.read_sql("select 42 as MyColumn", con)
   MyColumn
0        42
```

> Personally I like the all lowercase lifestyle, but that's me! I understand why you might want to make the change, and that you are still in Beta after all.

Noted! We are still contemplating whether this change is worthwhile, hence opening this issue to gather some feedback.

**Comment by danz68** [comment]
A few random thoughts.
This issue made me remember that double quoted identifiers were introduced, not only to allow punctuation characters and spaces, but also to allow entities to have keywords identifiers “MONTH”, ”YEAR”… 
While is understandable to relax the searching rule for “myentity” and allow both “myentity” and myentity to match it, or even MyEntity, it might worth to mention that Firebird uses a different relaxation rule for case insensitivity match. “MYENTITY” (double quoted, uppercased) will be searched using case insensitive match only if is not a keyword, it doesn’t contain spaces or any other non accepted characters for identifiers ($ is accepted in Firebird).
If we agree that the purpose of `unquoted identifiers will be automatically converted into lower case` is in fact a description for the SQL language case insensitivity behavior “any keyword or entity registered with an unquoted label will be identified/looked up using case insensitive match" we separate the DuckDB SQL dialect particularities from any external interaction (import, export, libraries or languages). 
IMO, any case sensitivity relaxation matching rule you may want to adapt should affect only the DuckDB SQL dialect, it can be even different than SQLite, Postgres or Firebird (not advisable too revolutionary, though ☺). Any import/export should favor, where possible, the case sensitivity preservation, double quoting entity names where needed.

**Comment by swang1001** [comment]
I would support keeping the case with the parser, especially for interoperability with Pandas. To make it backward compatible, maybe this can be introduced as a PRAGMA statement, e.g. `PRAGMA preserve_identifier_case;`.

**Comment by Alex-Monahan** [comment]
As I think more about this, it may be a better default to carry the capitalization through. However a Pragma to revert to the old way may help!

**Comment by jameelalsalam** [comment]
I am a new user to DuckDB via R who was surprised by the lowercasing of column names, and found this issue mentioning gathering feedback, so I thought that I should throw in my half-cent of my experience. 

In my case I am trying to load a lot of data which was output as csv from a SQL server database. The providers gave a SQL server table creation script, so it was simple to adapt that and pass to DuckDB w/ dbExecute, and then use COPY ... FROM csv files w/ dbExecute. However, I was surprised after 2 hours loading my data that all the variables were lowercase, which was difficult to read as the original names were in CapitalCase.

Overall I've been amazed at how easy it is to get started with DuckDB, thank you! And after reading this issue I think I understand what I should have done (when adapting the SQL server script, I deleted brackets which I should have changed for ""). Thanks for your work.

**Comment by holdenmatt** [comment]
Just my 2c as a DuckDB user: I've been experimenting with moving an app from SQLite to DuckDB, and ran into this issue.

It's not hard to work around, but was surprising to me as a DuckDB beginner FWIW.

**Comment by Mytherin** [comment]
I’m going to work on implementing this, I think it makes sense to do this sooner rather than later.

**Comment by Alex-Monahan-Intel** [comment]
We just did an upgrade from 0.3.1 to 0.4.0 and this pragma absolutely saved us! Thanks for adding that in for backwards compatibility. Many hours were saved!
