### ISSUE TITLE
Type inference for parameterized queries

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2079]
**What does happen?**

``` r
library(DBI)

con <- dbConnect(duckdb::duckdb())
dbGetQuery(con, "SELECT ? + 1.0 AS a", params = list(2))
#> Error in .local(conn, statement, ...): duckdb_prepare_R: Failed to prepare query SELECT ? + 1.0 AS a
#> Error: INTERNAL Error: Could not convert type UNKNOWN to a decimal.
```

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Context: #1240.

**What should happen?**

Can we make this query work out of the box?

**To Reproduce**

See reprex above.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - DuckDB Version: R package 0.2.6

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2081.
