### ISSUE TITLE
Julia Interface

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#208]
Integrate DuckDB with Julia. Julia supports a stream interface for the CSV loader. It would be great if that could be used with DuckDB as well, defining something like a sink for DB data.

**Comment by hannesmuehleisen** [comment]
Not really an issue, so closing for now

**Comment by hannesmuehleisen** [comment]
See https://github.com/JuliaDatabases/DBInterface.jl

**Comment by hannesmuehleisen** [comment]
CC @waynelapierre

**Comment by phillc73** [comment]
I haven't looked into them, just found via searching, but I think @mdashti already made a start on a Julia interface:

https://github.com/RelationalAI-oss/duckdb-builder.jl
https://github.com/RelationalAI-oss/DuckDB.jl

**Comment by hannesmuehleisen** [comment]
Indeed this seems to exist, so closing for now.

**Comment by jfb-h** [comment]
Could this be opened again? I'd love to see julia support but the packages linked above seem to be abandoned and theres not really that much there. There is however pretty recent [ODBC support](https://github.com/JuliaDatabases/ODBC.jl) so maybe that could also help?

**Comment by kimmolinna** [comment]
I can confirm that an ODBC-connection is working. I'm using DuckDB over ODBC in Pluto.jl.

**Comment by kimmolinna** [comment]
I started to do a Julia wrapper for C-API. I doesn't support all types yet but It's a start. You will find it at [Julia-duckdb](https://github.com/kimmolinna/julia-duckdb). And I don't know how to do a Julia package yet but maybe somebody is helping me with that later on when It's time for that. ;)

**Comment by hannes** [comment]
This exists now
