### ISSUE TITLE
R: Support bigint argument in DBI::dbConnect()?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2080]
**What does happen?**

The DBI specs suggest supporting different ways of returning 64-bit integer data.

**What should happen?**

Add `bigint` argument to `dbConnect()` ?

**To Reproduce**

``` r
library(DBI)

con <- dbConnect(duckdb::duckdb(), bigint = "integer64")
class(dbGetQuery(con, "SELECT 10000000000 AS a")$a)
#> [1] "numeric"
```

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - DuckDB Version R package 0.2.6

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by krlmlr** [comment]
I'm leaning towards a fully ALTREP based solution, mimicking `AltrepString`.

**Comment by hannes** [comment]
I think the bit64 solution is fairly standard in R, we have used it before and I am fine with going this route again. I don't think ALTREP is necessary.

**Comment by Mytherin** [comment]
@krlmlr could you perhaps pick this up?
