### ISSUE TITLE
Solaris error on CRAN

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#2091]
I noticed that there's a Solaris error on CRAN for the Arrow-DuckDB integration tests.

One of the ways that we gate tests is by turning them on/off [if the features they use are available](https://github.com/apache/arrow/blob/master/r/tests/testthat/helper-skip.R#L18-L34)

Adding something like the following to the top of the arrow integration tests should accomplish this (after line 7 or so):

```
skip_if_not("dataset" %in% arrow::arrow_info()$capabilities)
```

Which will skip if dataset support has not been built for Arrow (which it almost certainly will not be on Solaris!). Datasets isn't the _only_ feature one could test, but since that is one of the big use-cases it might be a good one to turn these tests off with.

**Comment by hannesmuehleisen** [comment]
Thanks, indeed we already got an email from Prof. Ripley on the topic. Other tests have a version check, I guess something like that should also work there.
