### ISSUE TITLE
show_tables pragma does not specify schema or table/view designation

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#2093]
**What does happen?**
`PRAGMA show_tables` does not provide any information regarding which schema a table belongs to.  This can potentially create ambiguity in the event the same table name exists within multiple schemas.  Likewise, `show_tables` does not specify whether an entry is in fact a table or a view, despite cataloguing both.

**What should happen?**
In addition to a `name` column, it would be helpful if the output `show_tables` would also include a `schema` column and perhaps a specification of whether the entry is in fact a table or view

**To Reproduce**
```
import duckdb

# create schemas/tables/views

con = duckdb.connect()
con.execute('CREATE SCHEMA s1')
con.execute('CREATE TABLE s1.t1 (id INTEGER PRIMARY KEY)')
con.execute('CREATE SCHEMA s2')
con.execute('CREATE TABLE s2.t1 (id INTEGER PRIMARY KEY)')
con.execute('CREATE TABLE t1 (id INTEGER PRIMARY KEY)')
con.execute('CREATE VIEW v1 AS SELECT 0')

# show_tables
print(con.execute('pragma show_tables').fetchdf().to_markdown())

# outputs:

# |    | name   |
# |---:|:-------|
# |  0 | t1     |
# |  1 | t1     |
# |  2 | t1     |
# |  3 | v1     |
```
**Environment (please complete the following information):**
 - OS: Windows 10
 - DuckDB Version: 0.2.8-dev919

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
`SHOW TABLES` (and the underlying`PRAGMA show_tables`) is provided for compatibility with the equivalent [MySQL](https://dev.mysql.com/doc/refman/8.0/en/show-tables.html) syntax, and should therefore maintain the same behavior as MySQL. If you want to obtain additional information from tables, you can use one of the following queries:

```sql
SELECT * FROM information_schema.tables;
SELECT * FROM duckdb_tables;
```

**Comment by Admolly** [comment]
Thank you, that is very helpful information.  I don't recall seeing it in the docs however?

**Comment by Mytherin** [comment]
Indeed the documentation is rather outdated here. I will make a separate issue to address that.

**Comment by Trymzet** [comment]
Yup the only thing in the docs is `PRAGMA show_tables`, which doesn't show the schema.
