### ISSUE TITLE
Typo in C API header signatures for UInt binding functions causes error 

### ISSUE THREAD

**Issue by amauryt** [duckdb/duckdb#2105]
**What does happen?**

I'm working on DuckDB bindings for the Crystal language using the C API when I got the following error:

```
Undefined symbols for architecture x86_64:
  "_duckdb_bind_uint16", referenced from:
      _*DuckDB::Statement#bind_arg<Int32, UInt16>:Nil in D-uckD-B-5858S-tatement.o
  "_duckdb_bind_uint8", referenced from:
      _*DuckDB::Statement#bind_arg<Int32, UInt8>:Nil in D-uckD-B-5858S-tatement.o
```
After a while I finally noticed a small typo on the [C header file](https://github.com/duckdb/duckdb/blob/v0.2.8/src/include/duckdb.h), as the  binding functions for both [uint16](https://github.com/duckdb/duckdb/blob/a8fd73b37bfc249b76b2aaa488d52dfdb39bb3d9/src/include/duckdb.h#L254) and [uint8](https://github.com/duckdb/duckdb/blob/a8fd73b37bfc249b76b2aaa488d52dfdb39bb3d9/src/include/duckdb.h#L253) expect signed integers instead of unsigned ones as parameters.

**What should happen?**

The C API header binding functions should contain the expected signatures, i.e., `uint8_t` and `uint16_t` instead of `int8_t` and `int16_t`.

**Environment (please complete the following information):**
 - OS: MacOS 11.5 (Big Sur)
 - DuckDB Version 0.2.8

**Comment by Mytherin** [comment]
Thanks for the report! This indeed seems like a typo. I will push a fix.

**Comment by amauryt** [comment]
Thank you for the quick reply and fix!

BTW, I think that the new functions and structs for time-related datatypes are a nice improvement for the C API.

I just noticed another small but non-important typo. 😅  For the function `duckdb_value_date`, the [comment above](https://github.com/duckdb/duckdb/blob/1f1478e852d49b0061769c859703b36404d53bf7/src/include/duckdb.h#L236) should say "Converts the specified value to a date"; at the moment it says "[...] to an uint16_t".

I also just published the initial implementation of [Crystal bindings for DuckDB](https://github.com/amauryt/crystal-duckdb).

Looking forward for the next DuckDB release!

**Comment by Mytherin** [comment]
> Thank you for the quick reply and fix!
> 
> BTW, I think that the new functions and structs for time-related datatypes are a nice improvement for the C API.
> 
> I just noticed another small but non-important typo. 😅 For the function `duckdb_value_date`, the [comment above](https://github.com/duckdb/duckdb/blob/1f1478e852d49b0061769c859703b36404d53bf7/src/include/duckdb.h#L236) should say "Converts the specified value to a date"; at the moment it says "[...] to an uint16_t".

Thanks! I have fixed this locally, it will be part of my next PR on the C API.

> I also just published the initial implementation of [Crystal bindings for DuckDB](https://github.com/amauryt/crystal-duckdb).

Very exciting! Great stuff.
