### ISSUE TITLE
Duckdb-authored Parquet files might be slightly corrupt - and incompatible with BigQuery

### ISSUE THREAD

**Issue by JoshLipschultz** [duckdb/duckdb#2111]
Exporting files as Parquet using `COPY x TO 'x.parq' (FORAMT PARQUET)` yields files unreadable by BigQuery. This happens even with the tiniest table (one row, one column, an int value) and no compression (also happens with ZSTD and GZIP).

However, the Parquet files DuckDB writes *are* readable by DuckDB and Pandas (pd.read_parquet), so the difference between what we get with these steps and a valid file must be subtle (or, there's a bug in BigQuery's Parquet reader).

Reproduction steps: 

```
-- 1. Create a tiny table and export it
CREATE TABLE t AS SELECT 123 as id;
COPY t to 't.parq' (FORMAT PARQUET);

-- 2. Upload this to GCS somewhere
gsutil cp t.parq gs://..../t.parq

-- 3. Attempt to run this load command:
bq load \
    --replace \
    --source_format=PARQUET \
    some_dataset.some_tablename \
    gs://..../t.parq
```

You should see an error like:
> BigQuery error in load operation: Error processing job ....: An internal error occurred and the request could not be completed. Error: 80038528

**Environment (please complete the following information):**
 - OS: macOS & Debian
 - DuckDB Version 0.2.5 and 0.2.8 and v0.2.9-dev128 7e98323ab

**Comment by JoshLipschultz** [comment]
Update: the cause of this issue is that several parts of the Parquet file are blank, including the root `SchemaElement` and the `Creator` field. The BQ team is working on a fix (progress here: https://issuetracker.google.com/issues/195942851). They're separately working on not crashing when trying to load these malformed files, but it would be good if they were populated on DuckDB `COPY` statements.

**Comment by hannesmuehleisen** [comment]
I've opened a PR that adds the creator and schema name fields. Attached is a file created by the new version using your script. Perhaps you could check
 if this fixes the issue?

[t.parq.zip](https://github.com/duckdb/duckdb/files/6975164/t.parq.zip)

**Comment by JoshLipschultz** [comment]
It does indeed, thanks!
