### ISSUE TITLE
version 0.2.8 missing from maven

### ISSUE THREAD

**Issue by ParadoxShmaradox** [duckdb/duckdb#2116]
Hey,

Congratulation on version 0.2.8!

I noticed that the new version isn't on [maven central ](https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/)

Not sure if it just takes time or went missing on release.

Looking forward to test the new features, Thanks!

**Comment by hannesmuehleisen** [comment]
Indeed this is still missing due to a build failure on the release tag build (grrr). Will upload soon.

**Comment by hannesmuehleisen** [comment]
Should be fixed
