### ISSUE TITLE
R: Support deparse-parse of DBI driver object

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2118]
**What does happen?**

The dblog package currently uses a combination of `deparse()` and `parse()` to print a call that creates the driver object. This doesn't work with duckdb, because the driver object already contains a database reference.

**What should happen?**

Let's discuss, there are a few options:

- work around in dblog specifically for duckdb
- avoid storing the database ref in the duckdb driver object

**To Reproduce**

``` r
drv <- duckdb::duckdb()
deparse(drv)
#> [1] "new(\"duckdb_driver\", database_ref = <pointer: 0x126e40ff0>, dbdir = \":memory:\", "
#> [2] "    read_only = FALSE)"
parse(text = deparse(drv))
#> Error in parse(text = deparse(drv)): <text>:1:37: unexpected '<'
#> 1: new("duckdb_driver", database_ref = <
#>                                         ^
```

<sup>Created on 2021-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Environment (please complete the following information):**
 - OS: macOS
 - DuckDB Version: 0.2.9

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Not sure how we should deparse this. The pointer points to the C++ DuckDB database object, do you want to create a function that can recreate said object? It will not actually work, since we cannot keep for example contents of in-memory databases intact.

**Comment by krlmlr** [comment]
Yeah, deparsing won't work. Does a `duckdb_driver` object really need to store the database reference? Could this be stored in a map instead?

**Comment by hannesmuehleisen** [comment]
Sure, could do map. Why exactly should this be supported in the first place though? Seems like added complexity (and garbage collection issues) for unclear gains to me?

**Comment by krlmlr** [comment]
I don't understand why we're already instantiating the database in the driver object. I see the garbage collection problem and don't have a good solution.

dblog needs a way to instantiate the driver object. The current hack is deparse-parse, we could substitute it with something different, but this has heavy implications on multiple components.

**Comment by krlmlr** [comment]
This is no longer important. I still don't understand if the driver object is a singleton (if so, we could store the C++ pointer elsewhere) or not (and then what's the difference between driver and connection).
