### ISSUE TITLE
duckdb CLI: parquet_scan reading from '/dev/stdin'

### ISSUE THREAD

**Issue by mskyttner** [duckdb/duckdb#2127]
**What does happen?**

Is parquet_scan able to read from the '/dev/stdin' file? 

This seems to work:

`duckdb :memory: "select * from parquet_scan('bottomT_annuals_0p100.parquet') limit 10;"`

But this doesn't:

`cat bottomT_annuals_0p100.parquet | duckdb :memory: "select * from parquet_scan('/dev/stdin');"`

`Error: Invalid Input Error: File '/dev/stdin' too small to be a Parquet file`

**What should happen?**

The parquet_scan function should preferably read the parquet file sent to /dev/stdin, similarly to how it reads parquet files from S3 locations.

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

First make sure you have a locally stored .parquet file (for example generated by duckdb), named for example mydata.parquet.

1. `cat mydata.parquet | duckdb :memory: "select * from parquet_scan('/dev/stdin');"`

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version 0.2.8

**Comment by Mytherin** [comment]
Reading parquet files from stdin is far more difficult than reading CSV files since Parquet files by their very nature require jumping around within the file, which is not possible on a stream. Files over HTTP are much easier since we can jump around there using HTTP range requests. 

If we were to implement this by necessity the file would not be streamed in but the stream would instead be fully materialized in-memory and then read/searched. This would degrade performance over just reading the file from disk as-is. 

May I ask what the exact use case for this is? Are there programs that output raw Parquet files onto `stdout`?

**Comment by mskyttner** [comment]
Regarding the use case... for both parquet and CSV loading using duckdb CLI (through read_csv, read_csv_auto and parquet_scan), my use case involves loading data from files that take a while to load. The data may not always fit fully materialized in-memory. 

It is then great to have some kind of "chunkwise reading" or buffered mechanism for reading chunks (such as line buffered CSV or perhaps rowgroup buffered parquet(?)). Personally, I don't mind the chunks being large as long as they fit into memory (or, say, 70% of available RAM), but I understand also the need to be able to buffer streams in smaller chunks (at the cost I guess of more transactions being required during the load, since there would be more chunks). 

Ideally a long-running data loading step would provide some progress indication so that one could feel confident that the process has not hung. This would perhaps be possible to live without in the use case involving CSV loading, if one can get approximate progress through external utilities like [pv](https://ostechnix.com/monitor-progress-data-pipe-using-pv-command/) which are sometimes used on the CLI like in "pv sqlfile.sql | mysql -uxxx -pxxxx dbname". 

I'm not sure what widely used standard CLI tools for producing parquet onto stdout exist. For my part I like to use duckdb CLI for this after trying a few other commands, and no, it does not write to stdout (but it would be neat if it could), with a "copy 'mydata.csv.gz' to 'mydata.parquet' (FORMAT 'parquet');" statement :)

I found a write-up about two utilities: make-parquet and tabulate-parquet, based on the  parquet-cpp C++ Parquet library: <https://colinsblog.net/2018-06-23-notes-on-writing-and-reading-parquet-files-in-c-plus-plus/>. 

It mentions a RowGroupReader/Writer feature and comments: "The concept of row groups is important; if you’re memory constrained you may need to read in one row group worth of a column at a time (these are known as column chunks.) This way you can read in part of a column, deal with the data by performing some reduce operation and dispose of the memory before moving on to the next row group.".

**Comment by mskyttner** [comment]
Thanks for the explanations! I didn't know metadata was stored at the end of a parquet file... that would make it unsuitable for chunking/streaming it sounds like (but perhaps there is a good reason for doing this, which I don't understand, since the metadata would probably need to be known before writing starts anyways). So I agree, and I now feel that this feature request should be closed without action.

Also, it is very nice with the pragma that gives a progress bar. I was looking for something like that amongst the command line switches to duckdb and couldn't find it there. 

Regarding chunkwise reading (and writing), I just tried reading a 113 GB CSV file with progress bar using `duckdb myduck "pragma enable_progress_bar; create table ref as select * from read_csv_auto('ref.csv', ALL_VARCHAR=TRUE);"`

I got  
` 13% [|||||||                                                     ]Error: IO Error: Could not write all bytes to file "myduck.tmp/4611686018427434316.block": wanted=262144 wrote=86008`

Probably this is due to me running out of disk for temp files, is there a command line switch or pragma to set the location of the scratchdir/tempdir? 

I found a PRAGMA log_query_path='/tmp/duckdb_log/'; setting but this doesn't sound like the right one. 

I guess I would need about as much free disk space as the file I'm about to load?

**Comment by Mytherin** [comment]
> Thanks for the explanations! I didn't know metadata was stored at the end of a parquet file... that would make it unsuitable for chunking/streaming it sounds like (but perhaps there is a good reason for doing this, which I don't understand, since the metadata would probably need to be known before writing starts anyways). So I agree, and I now feel that this feature request should be closed without action.

The main reason for writing the metadata at the end is to support stream *writing* rather than stream *reading*. The schema itself is known at the start (e.g. the types of the columns and the names of the columns), but what is not known is the sizes of the individual columns. That is because the size of columns is not trivial to figure out as the Parquet data gets compressed internally, so the Parquet writer will first write the columns (after which it knows how many bytes have been written), and then write the metadata containing that information.

> Also, it is very nice with the pragma that gives a progress bar. I was looking for something like that amongst the command line switches to duckdb and couldn't find it there.

Yes, improved documentation for the pragmas (and in general) is on the short-term agenda, but great that it is useful to you.

> Probably this is due to me running out of disk for temp files, is there a command line switch or pragma to set the location of the scratchdir/tempdir?

Try `PRAGMA temp_directory='/tmp/'`.

**Comment by Mytherin** [comment]
No problem, happy to help, and let us know if you run into any more issues!
