### ISSUE TITLE
Optimize prepared statements

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#213]
As shown on https://www.duckdb.org/benchmarking/, prepared statements currently perform very poorly as there are many unnecessary overheads still present in their execution. Based on some experiments it should be possible to improve their performance by >10X

**Comment by omo** [comment]
Is this still the case? The [benchmarking page](https://duckdb.org/benchmarks/index.html) has changed a lot so I I'm not sure which one you are talking about.

Also I'd love to hear what kind of optimization you had in you mind, and which is already implemented and which hasn't.
Thanks!

(I'm looking at old bugs to see if there is anything interesting.)

**Comment by Mytherin** [comment]
Indeed the benchmarks page has changed somewhat. The benchmarks that I referred to are now [here](https://duckdb.org/benchmarks/append.html).

Prepared statements have been optimized somewhat since this issue was opened. They no longer rerun the planner and optimizer for every query which they used to do, which results in them being significantly faster than just running insert into statements.

As you can see in the benchmarks the performance of using prepared statements to insert large amounts of data is still significantly slower than using the appender or reading from a CSV file. I haven't done any profiling recently to figure out what is the main cause of this performance difference and if there are any easy optimizations left. It is unlikely prepared statements will be as fast the appender in any case since they are inherently more general and complex.

**Comment by omo** [comment]
Thanks for the clarification!
I see that it still as twice as slow, even though each prepared statement now has a computed physical plan.

**Comment by hannes** [comment]
Probably fixed by #3375
