### ISSUE TITLE
Python: register + viewing a DataFrame gives shifted values

### ISSUE THREAD

**Issue by jorisvandenbossche** [duckdb/duckdb#2132]
Given the following small example where I create a small pandas DataFrame, register it to duckdb, and then query the view:

```
In [1]: import duckdb

In [2]: duckdb.__version__
Out[2]: '0.2.8'

In [3]: df = pd.DataFrame(np.arange(20).reshape(5, 4), columns=["a", "b", "c", "d"])

In [4]: df
Out[4]: 
    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [5]: con = duckdb.connect(database='test_db.duckdb', read_only=False)

In [6]: con.register('df_view', df)
Out[6]: <duckdb.DuckDBPyConnection at 0x7f5994d60bf0>

In [7]: con.execute("SELECT * FROM df_view;").fetchdf()
Out[7]: 
   a  b  c  d
0  0  1  2  3
1  1  2  3  4
2  2  3  4  5
3  3  4  5  6
4  4  5  6  7
```

The resulting table has wrong values (the second row has partly the same values as the second row, shifted 1 place)

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu)
 - DuckDB Version: 0.2.8 (didn't yet try with master)

**Comment by jorisvandenbossche** [comment]
It might depend on how the DataFrame is created (which can influence the memory layout of the underlying data), because if I create a similar dataframe from a dict of columns, it works fine:

```
In [8]: df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'd': [9, 10, 11, 12]})

In [9]: con.register('df_view2', df)
Out[9]: <duckdb.DuckDBPyConnection at 0x7f5994d60bf0>

In [10]: con.execute("SELECT * FROM df_view2;").fetchdf()
Out[10]: 
   a  b   d
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [11]: df
Out[11]: 
   a  b   d
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12
```

**Comment by hannesmuehleisen** [comment]
Thanks for reporting this, maybe @pdet can have a look?

**Comment by Mytherin** [comment]
This should be fixed in the master now. Thanks again for the detailed report!

**Comment by jorisvandenbossche** [comment]
Thanks for the quick fix!
