### ISSUE TITLE
Filtering a datetime column of an arrow table relation works for < but not for >

### ISSUE THREAD

**Issue by legout** [duckdb/duckdb#2145]
**What does happen?**

I have created a duckdb relation from an arrow table of historical stock data.

Filtering for dates greater than  a given date (e.g. `'date > '2019-01-01'`) returns an empty table, althoug the given date is smaller than several dates in the table. 

Filtering for dates lower than a given date (e.g. `'date < '2019-01-01'`) works as expected.

It is working , when I create the relation from the parquet files.
 
**What should happen?**
Query should return expected results.

**To Reproduce**
```python

import numpy as np
import pandas as pd
import pyarrow.feather as pf
import pyarrow.parquet as pq
import pyarrow

date1 = pd.date_range("2018-01-01", "2018-12-31", freq="B")
df1 = pd.DataFrame(np.random.randn(date1.shape[0], 5), columns=list("ABCDE"))
df1["date"] = date1

date2 = pd.date_range("2019-01-01", "2019-12-31", freq="B")
df2 = pd.DataFrame(np.random.randn(date2.shape[0], 5), columns=list("ABCDE"))
df2["date"] = date2

pq.write_table(pa.table(df1), "data1.parquet")
pq.write_table(pa.table(df2), "data2.parquet")

table = pq.ParquetDataset(["data1.parquet", "data2.parquet"]).read()

# failed. returns an empty table
duckdb.arrow(table).filter("date > '2019-01-01'").df()

# works
duckdb.arrow(table).filter("date < '2019-01-01'").df()

# works
duckdb.from_parquet("data*.parquet").filter("date > '2019-01-01'").df()

```

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version 0.2.8

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by pdet** [comment]
I was able to reproduce it, but both these calls fail right
``` python

# failed. returns an empty table
duckdb.arrow(table).filter("date > '2019-01-01'").df()

# works
duckdb.arrow(table).filter("date > '2019-01-01'").df()
```

Will check whats going on now, thanks for the report :).

**Comment by legout** [comment]
I had an error in my code. Second query should contain "<" not ">". 
Try the code below. Second query should work.

```python
# failed. returns an empty table
duckdb.arrow(table).filter("date > '2019-01-01'").df()

# works
duckdb.arrow(table).filter("date < '2019-01-01'").df()
```
I´ve also edited my original post.

**Comment by pdet** [comment]
No Worries! Just double-checking :-)

I've already found the culprit and PR-ed it (#2149)
