### ISSUE TITLE
Reenable ccache

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2153]
https://github.com/duckdb/duckdb/pull/1774 disables `ccache` for the first job that must complete before all other jobs can even start. This leads to many accumulated hours of waiting time.

Should we keep `ccache` for the first job and move the build with `BUILD_ARROW_ABI_TEST=1` to another job?

**Comment by hannesmuehleisen** [comment]
I think that's a good idea, lets make use of ccache if we can. The CI time is starting to add up again.
