### ISSUE TITLE
Import csv failed from window command line

### ISSUE THREAD

**Issue by happydentist** [duckdb/duckdb#2161]
I use command line on window 10
If like this with sqlite3
---> sqlite3 test.db ".mode csv" ".import test.csv tb_test"
       it suscess.
But with duckdb
---> duckdb test.db ".mode csv" ".import test.csv tb_test"
      it fail, show massage
      Error: Catalog Error: Table with name tb_test does not exist!
      LINE 1: SELECT * FROM tb_test

**Comment by davidwales** [comment]
I've successfully imported a CSV using the following syntax:

```
duckdb.exe test.db "CREATE TABLE test AS SELECT * FROM 'test.csv';"
```
