### ISSUE TITLE
R client can not read from S3 or https sources

### ISSUE THREAD

**Issue by noamross** [duckdb/duckdb#2177]
**What does happen?**
When using the DuckDB R package, PARQUET_SCAN fails when trying to read from HTTP or S3 sources, giving the error

     Error: IO Error: No files found that match the pattern...

**What should happen?**
I expect to be able to run the same queries from `duckdb/test/sql/copy/parquet/test_parquet_remote.test ` using `DBI::dbGetQuery()` commands from R. 

**To Reproduce**
``` r
library(duckdb)
#> Loading required package: DBI
library(DBI)

conn <- DBI::dbConnect(duckdb::duckdb(), read_only = FALSE)
# Setting variables is fine
DBI::dbSendQuery(conn, "SET s3_region='eu-central-1'")
#> <duckdb_result fea60 connection=90a80 statement='SET s3_region='eu-central-1''>
DBI::dbSendQuery(conn, "SET s3_access_key_id='HAHA'")
#> <duckdb_result 089a0 connection=90a80 statement='SET s3_access_key_id='HAHA''>
DBI::dbSendQuery(conn, "SET s3_secret_access_key='NOPE'")
#> <duckdb_result 160a0 connection=90a80 statement='SET s3_secret_access_key='NOPE''>

# Get file IO errors when trying to scan non-disk files
DBI::dbGetQuery(conn, "SELECT id, first_name, last_name, email FROM PARQUET_SCAN('https://raw.githubusercontent.com/cwida/duckdb/master/test/sql/copy/parquet/data/userdata1.parquet') LIMIT 10;")
#> Error in .local(conn, statement, ...): duckdb_prepare_R: Failed to prepare query SELECT id, first_name, last_name, email FROM PARQUET_SCAN('https://raw.githubusercontent.com/cwida/duckdb/master/test/sql/copy/parquet/data/userdata1.parquet') LIMIT 10;
#> Error: IO Error: No files found that match the pattern "https://raw.githubusercontent.com/cwida/duckdb/master/test/sql/copy/parquet/data/userdata1.parquet"

#Skipping this test as to replicate you'd need real auth
#DBI::dbGetQuery(conn, "SELECT id, first_name, last_name, email FROM PARQUET_SCAN('s3://cost-report-hannes/userdata1.parquet') LIMIT 10;")

# But we can read local parquet files fine
DBI::dbWriteTable(conn, "mtcars", mtcars)
DBI::dbSendQuery(conn, "COPY mtcars TO 'mtcars.parquet' (FORMAT PARQUET)")
#> <duckdb_result 97460 connection=90a80 statement='COPY mtcars TO 'mtcars.parquet' (FORMAT PARQUET)'>
DBI::dbGetQuery(conn, "SELECT mpg, cyl from PARQUET_SCAN('mtcars.parquet') LIMIT 10")
#>     mpg cyl
#> 1  21.0   6
#> 2  21.0   6
#> 3  22.8   4
#> 4  21.4   6
#> 5  18.7   8
#> 6  18.1   6
#> 7  14.3   8
#> 8  24.4   4
#> 9  22.8   4
#> 10 19.2   6
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       macOS Big Sur 10.16         
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2021-08-24                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.1.0)
#>  cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
#>  DBI         * 1.1.1   2021-01-15 [1] CRAN (R 4.1.0)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
#>  duckdb      * 0.2.8   2021-08-02 [1] CRAN (R 4.1.0)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.1.0)
#>  knitr         1.33    2021-04-24 [1] CRAN (R 4.1.0)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
#>  pillar        1.6.2   2021-07-29 [1] CRAN (R 4.1.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
#>  rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
#>  rmarkdown     2.10    2021-08-06 [1] CRAN (R 4.1.0)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
#>  stringi       1.7.3   2021-07-16 [1] CRAN (R 4.1.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
#>  styler        1.5.1   2021-07-13 [1] CRAN (R 4.1.0)
#>  tibble        3.1.3   2021-07-23 [1] CRAN (R 4.1.0)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
#>  xfun          0.25    2021-08-06 [1] CRAN (R 4.1.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
#> 
#> [1] /Users/noamross/.renv-project-libraries/reprotemplate-f132e8eb/R-4.1/x86_64-apple-darwin17.0
#> [2] /private/var/folders/b4/xhg76n9n0pvfhj3dzgxry9zm0000gn/T/RtmpvZFGU4/renv-system-library
#> [3] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

</details>

**Environment (please complete the following information):**
 - OS: OSX
 - DuckDB R version 0.2.8 

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
Yes, we need to refactor the https into a loadable extension

**Comment by noamross** [comment]
In the meantime, should I be able to do this if I build from source with the right options? If I'm following this right, I want something like `BUILD_HTTPFS=1 BUILD_R=1 make`?

**Comment by noamross** [comment]
Ah, just found this.  Thanks @jonkeane!  https://github.com/duckdb/duckdb/commit/e288823cd9b043a882f75189b61d4bd4e7301d29#diff-49b3ea4b755de3ecb44d30a42112d609e0fc081d336e4487d00c99d9e6b71b1e

**Comment by Antauri** [comment]
> Yes, we need to refactor the https into a loadable extension

Any hints on how to do that? May be able to help ...

**Comment by cboettig** [comment]
Apologies if this is totally off the mark -- is it (or might it become) possible to do this using the duckdb arrow backend and arrow's existing support for remote/cloud filesystems? (https://arrow.apache.org/docs/r/articles/fs.html, https://arrow.apache.org/docs/python/filesystems.html)  

I have no grasp on the backend, but arrow's implementation looks like it already supports S3 with plans in the works to support azure, https://issues.apache.org/jira/browse/ARROW-2034.  Given that duckdb already integrates nicely with arrow, I'm curious if there's potential to piggyback of shared bindings, it seems that could be preferable to each application having to implement each API for remote sources manually....

Meanwhile, I too would be keen to see this feature enabled by default on the R client!

**Comment by cboettig** [comment]
@hannesmuehleisen any news on this?  It would be _really_ great to have this feature available out-of-the-box to R users

**Comment by Mytherin** [comment]
We have opted not to bundle the HTTPFS extension because many people experienced problems linking to OpenSSL as a result of the bundling. We are working to add [remotely installable extensions](https://github.com/duckdb/duckdb/pull/2569#issuecomment-981148964) to the next release, which adds support for the `INSTALL` and `LOAD` commands. The HTTPFS extension will be one of the installable extensions, so you could run e.g. the following comments to get HTTPFS working:

```sql
INSTALL httpfs;
LOAD httpfs;
```

> Apologies if this is totally off the mark -- is it (or might it become) possible to do this using the duckdb arrow backend and arrow's existing support for remote/cloud filesystems? (https://arrow.apache.org/docs/r/articles/fs.html, https://arrow.apache.org/docs/python/filesystems.html)

Yes, you can totally use arrow for this as well. DuckDB can read data from arrow sources directly. We actually published [a blog post about this today](https://duckdb.org/2021/12/03/duck-arrow.html).

**Comment by cboettig** [comment]
@Mytherin Nice, the remote extension mechanism looks awesome!  Let us know when you're ready to test.  R users might discover it better if the R bindings have a `install_extensions()` function or such that calls the install and and load on their behalf?

Excellent blog post!  I'd stumbled across `arrow::to_duckdb()` but hadn't realized it goes and creates the View and manages the cached connection handle in options and all, that's super slick.

**Comment by cboettig** [comment]
@hannes will the extensions trick you mentioned in https://github.com/duckdb/duckdb/issues/1414#issuecomment-1113926088 work here too?

I tried with the current release preview (v0.3.4):

```r
install.packages("https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_r_src.tar.gz", repos = NULL)
library(duckdb)
con = dbConnect(duckdb(), ":memory:")
DBI::dbExecute(con, "INSTALL httpfs")
DBI::dbExecute(con, "LOAD httpfs")
```

but I see:

```
 DBI::dbExecute(con, "LOAD httpfs")
Error: rapi_execute: Failed to run query
Error: IO Error: File "/home/cboettig/.duckdb/extensions/662041e2b/linux_amd64/httpfs.duckdb_extension" could not be loaded: /home/cboettig/.duckdb/extensions/662041e2b/linux_amd64/httpfs.duckdb_extension: undefined symbol: _ZTIN6duckdb9ExceptionE
```

**Comment by hannes** [comment]
There is an open pr for this #3416

**Comment by cboettig** [comment]
I think this can be closed now as it now works great! thanks!!
