### ISSUE TITLE
Duplicate Join Column Names with USING Statements

### ISSUE THREAD

**Issue by swang1001** [duckdb/duckdb#2180]
**What does happen?**
When a Pandas DataFrame or the case is preserved for column names, the join key columns with `USING` statement are duplicated in the result.

**What should happen?**
The join key columns with `USING` statement should not be duplicated in the result.

**To Reproduce**
See the code below with test_2 and test3
```python
import duckdb
import pandas as pd

QUERY = "select * from A join B using(X)"

def get_columns(conn):
    return [c[0] for c in conn.description]

def test_1():
    conn = duckdb.connect()
    conn.execute('create table A as select 1 as X, 2 as Y')
    conn.execute('create table B as select 1 as X, 3 as Z')
    conn.execute(QUERY)
    # print ['x', 'y', 'z'] as expected
    print(get_columns(conn))

def test_2():
    conn = duckdb.connect()
    conn.execute('create table A as select 1 as X, 2 as Y')
    conn.register('B', pd.DataFrame(data=[[1,3]], columns=["X", "Z"]))
    conn.execute(QUERY)
    # print ['x', 'y', 'X', 'Z']
    print(get_columns(conn))

def test_3():
    conn = duckdb.connect()
    conn.execute('create table A as select 1 as "X", 2 as "Y"')
    conn.execute('create table B as select 1 as "X", 3 as "Z"')
    conn.execute(QUERY)
    # print ["X", "Y", "X", "Z"]
    print(get_columns(conn))

test_1()
test_2()
test_3()
```

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version: 0.28

**Before submitting**
- [Y] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [N] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by swang1001** [comment]
If we quote the column in the join condition, the issue appears to go away in test 3:

```python
QUERY = 'select * from A join B using("X")'
```

**Comment by Mytherin** [comment]
Thanks for the additional information. I will have a look at this.
