### ISSUE TITLE
Support hive-style partitioning of parquet archives

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#2186]
This has been mentioned tangentially in other issues (#1420, #2046, #773) but not identified directly as a feature request so just thought it might help to establish a specific thread for this.  In particular, while the globbing support (#773) makes it possible to read in these files (with a bit of extra munging to handle the partition columns), proper treatment of hive partitioning should be able to dramatically reduce the time for many queries to run, as it already does in other implementations such as `arrow` (e.g. https://ursalabs.org/blog/2021-r-benchmarks-part-1/).  Thanks for considering!

**Comment by dforsber** [comment]
A side comment. If you consider implementing partitioning support, please also consider the case of hive bucketing. In essence only open parquet files that match with bucketed column filters (e.g. bucketed by timestamp column in day=/ partition/folder).

**Comment by cboettig** [comment]
@danieldjewell also interested in ncdf/hdf5, but I think array data models are distinct from SQL-based relational databases like duckdb; like you say, `xarray` and `zarr` already provide good options there, no?

**Comment by arnaud-feldmann** [comment]
It's awesome ! Thanks for your work. DuckDB + parquet is **the law**. If you could add this through the dbplyr interface with **tbl()** it would be the best thing ever.

**Comment by hannes** [comment]
> It's awesome ! Thanks for your work. DuckDB + parquet is **the law**. If you could add this through the dbplyr interface with **tbl()** (like for parquet) it would be the best thing ever. 

We literally just merged a PR from @rsund for this

**Comment by arnaud-feldmann** [comment]
Awesome ! Now that's the fastest feature request implementation ever !

**Comment by LuisMoralesAlonso** [comment]
Hi all

I've found an strange behaviour with duckdb and pyarrow.

I want to use duckdb through an arrow dataset (with data in parquet with hive partitioning and in an S3 like minio).

This would be the code:

#In arrow
...
minio_conn = fs.S3FileSystem(access_key='accessKey1', secret_key='verySecretKey1', endpoint_override="https://s3.scality.test:8000", scheme='https')
dataset = ds.dataset("dummydata", filesystem=minio_conn, partitioning="hive")

#In duckdb
duckdb_dataset = duckdb.arrow(dataset)

#Check pyarrow memory pool
for i in range(0,10):
    print(convert_size(pa.total_allocated_bytes()))
    time.sleep(1)


It seems that loads all the entire dataset in arrow memory and then deallocate it, just with the arrow() method, no query!!!!


Any comment?

**Comment by arnaud-feldmann** [comment]
Same happens for me with R @LuisMoralesAlonso . For now, i rather load datasets with the glob notation, which doesn't bring memory overflow. But no partitioning variables allowed

**Comment by sobayed** [comment]
I was running into the same issue when using duckdb=0.3.1 and calling `con.register_arrow()` on a partitioned dataset (huge memory spike after the function call had completed, as measured by @LuisMoralesAlonso's code). With duckdb=0.3.4 and `con.register()` the problem seems to have disappeared (I was using pyarrow=8.0.0 in both scenarios).

**Comment by samansmink** [comment]
Note that a basic hive partition parsing option was added. Will leave this issue open for a bit because I still want to implement an optimisation that essentially achieves what @dforsber described: where we can actually apply filters on the hive partitions before the files are even opened (currently the parquet metadata of all files is scanned, instead of only the ones matching the filter).
