### ISSUE TITLE
No JDBC drivers for version 0.2.9 on maven central

### ISSUE THREAD

**Issue by fs111** [duckdb/duckdb#2191]
**What does happen?**
I noticed that there are not drives for 0.2.8 on maven central. Also the release page no longer has mac comaptible jdbc drivers. 

**What should happen?**
I should be able to download the drivers

**To Reproduce**

**Environment (please complete the following information):**
 - OS: All
 - DuckDB Version 0.28

**Comment by fs111** [comment]
same goes for 0.2.9. Is there a chance to get the drivers into maven central again?

**Comment by hannesmuehleisen** [comment]
On it

**Comment by hannesmuehleisen** [comment]
Should be fixed

**Comment by fs111** [comment]
Not seeing anything here yet: https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/ could it be a sync problem?

**Comment by hannesmuehleisen** [comment]
Could take a little while to sync indeed
