### ISSUE TITLE
Document DISTINCT ON and maybe add windows in HAVING

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2197]
In many analytical scenarios, it can be useful to only return a single value per group. Right now, one has to write a  window query with rank or a complex filter that removes all values that are not the first. Postgres implements `DISTINCT ON(column)` to make this easier. In new Postgres versions, it's also the fastest of many alternatives. You can find more details in the second and third answers to https://stackoverflow.com/questions/3800551/select-first-row-in-each-group-by-group.

Another solution I could imagine is to support window queries in WHERE or HAVING so that one could write `HAVING rank() OVER(PARTITION BY col1 ORDER BY col2) = 1` but this may break some semantic constraints I miss.

For example, I may want the beers with the highest abv per style

Right now one has to write

```sql
WITH beer_rank AS (
  SELECT *, rank() OVER(PARTITION BY style ORDER BY abv DESC)
  FROM beer
)
SELECT style, name, abv, rank
FROM beer_rank
WHERE rank = 1
```

But I think these are easier to read

```sql
SELECT DISTINCT ON(style), name, abv
FROM beer
ORDER BY abv DESC
```

```sql
SELECT style, name, abv
FROM beer
HAVING rank() OVER(PARTITION BY style ORDER BY abv DESC) = 1
```

**Comment by domoritz** [comment]
My bad, it's implemented but I need to repeat `style`.

https://github.com/duckdb/duckdb/issues/162

Two questions. First, what does this mean?

```sql
SELECT DISTINCT(style), name, abv
FROM beer
ORDER BY abv DESC
```

Second, could you update the docs?

<img width="914" alt="Screen Shot 2021-08-28 at 22 36 58" src="https://user-images.githubusercontent.com/589034/131236369-a5dd8419-45c5-45da-afcf-46e66e2d8225.png">

**Comment by domoritz** [comment]
I just had another idea, which is to use argmax

```sql
SELECT argmax(style, abv), argmax(name, abv), max(abv)
FROM beer
GROUP BY style
```

I wonder what you think about supporting 

```sql
SELECT argmax(*, abv), max(abv)
FROM beer
GROUP BY style
```

Or as a shortcut for the working query (to show style and name for highest abv)

```
SELECT argmax(style, name, abv), max(abv)
FROM beer
GROUP BY style
```

**Comment by Mytherin** [comment]
> Two questions. First, what does this mean?

> SELECT DISTINCT(style), name, abv
FROM beer
ORDER BY abv DESC

Distinct on style, but don't select style, much like grouping columns do not need to be included in the result. It is equivalent to:

```sql
SELECT FIRST(name), FIRST(abv)
FROM beer
GROUP BY style
ORDER BY abv DESC
```

This is equivalent to Postgres' behavior here.

> Second, could you update the docs to add ON?

Sure, should be added now.

**Comment by domoritz** [comment]
> Distinct on style, but don't select style, much like grouping columns do not need to be included in the result.

Hmm, maybe not in my version?

<img width="928" alt="Screen Shot 2021-08-29 at 18 01 15" src="https://user-images.githubusercontent.com/589034/131266715-3f40aab8-23b2-4286-8043-801c525f71d3.png">
<img width="952" alt="Screen Shot 2021-08-29 at 18 02 20" src="https://user-images.githubusercontent.com/589034/131266738-423066fc-550a-43e8-b92d-1896ca4a9e22.png">

**Comment by ankoh** [comment]
The wasm version is still on v0.2.8-dev381 at the moment.
I'll update it tomorrow.

**Comment by Mytherin** [comment]
> > Distinct on style, but don't select style, much like grouping columns do not need to be included in the result.
> 
> Hmm, maybe not in my version?
> 

Ah, small oversight on my part, the `abv` in the ORDER BY also needs to be an aggregate or a grouping column:

```sql
SELECT FIRST(name), FIRST(abv)
FROM beer
GROUP BY style
ORDER BY FIRST(abv) DESC
```

**Comment by Mytherin** [comment]
> Is it possible to improve the error message to list the column that needs to be in the group by?

It is! In fact, I went back in time an hour and did just that :) #2205

**Comment by domoritz** [comment]
💟  you're awesome!

> Distinct on style, but don't select style

I'm still not getting unique styles when I just run `SELECT DISTINCT(style)`, though (and style is in the output as well).

<img width="1171" alt="Screen Shot 2021-08-30 at 09 15 19" src="https://user-images.githubusercontent.com/589034/131344889-9d1081df-c13b-4ed6-9624-fc38210d55a6.png">

**Comment by Mytherin** [comment]
> > Distinct on style, but don't select style
> 
> I'm still not getting unique styles when I just run `SELECT DISTINCT(style)`, though (and style is in the output as well).

Hm, actually looking at it again indeed ON is required, without the ON part it will just run a select distinct. This is more obvious if we format the query as follows:

```sql
SELECT DISTINCT
    (style), name, abv
FROM beer
ORDER BY style
```

Versus

```sql
SELECT DISTINCT ON(style)
    name, abv
FROM beer
ORDER BY style
```

Without the ON part you will just select style, with brackets around the column reference (`(style)`). I have updated the documentation to reflect that ON is required now.

**Comment by domoritz** [comment]
Then feel free to close this issue. I can make a separate one for supporting windows in having if that's something that sounds reasonable to you.
