### ISSUE TITLE
Add support for selecting all but some columns

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2199]
`SELECT *` is super convenient for analytical queries where I don't want to type all column names. However, sometimes I do want to exclude certain columns. I would love to have some syntax like `SELECT * EXCEPT foo` to get all but one (or some) column.

**Comment by Mytherin** [comment]
Thanks for the suggestion! I think this is a good idea but wonder what the syntax should be, do you know of any system that implements something similar?

As a side note, we also support #1, #2, #3, etc to select specific columns, which can also save some typing:

```sql
select #1, #3, #5, #7, #10 from lineitem limit 5;
┌────────────┬───────────┬────────────┬────────────┬──────────────┐
│ l_orderkey │ l_suppkey │ l_quantity │ l_discount │ l_linestatus │
├────────────┼───────────┼────────────┼────────────┼──────────────┤
│ 1          │ 93        │ 17         │ 0.04       │ O            │
│ 1          │ 75        │ 36         │ 0.09       │ O            │
│ 1          │ 38        │ 8          │ 0.10       │ O            │
│ 1          │ 48        │ 28         │ 0.09       │ O            │
│ 1          │ 23        │ 24         │ 0.10       │ O            │
└────────────┴───────────┴────────────┴────────────┴──────────────┘
```

**Comment by domoritz** [comment]
Thanks for showing me the trick. That could be useful but breaks when the table gets new columns. 

I'm not aware of any SQL system but Arquero supports it https://uwdata.github.io/arquero/api/verbs.html#select.

**Comment by Alex-Monahan** [comment]
I believe that ClickHouse supports it, as well as using regex to pick which columns to select:
[ClickHouse docs](https://www.google.com/amp/s/clickhouse.tech/docs/en/sql-reference/statements/select/amp/) 

Looks like BigQuery also allows it: [BigQuery docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select-modifiers)

**Comment by domoritz** [comment]
Oh great, BigQuery [uses `EXCEPT`](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_except). 

```sql
WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * EXCEPT (order_id)
FROM orders;

+-----------+----------+
| item_name | quantity |
+-----------+----------+
| sprocket  | 200      |
+-----------+----------+
```

They also have `REPLACE`, which makes sense in addition to `EXCEPT`. @Mytherin BigQuery could be a model for DuckDB's syntax then.

**Comment by mskyttner** [comment]
If considering adopting existing elsewhere used naming for various functions operating on column names and looking also outside of existing specific existing SQL "dialects" (since the ansi SQL standard doesn't offer much of this?), one could consider looking at the tidyverse data manipulation API. 

It makes use verbs named for example [`rename`](https://dplyr.tidyverse.org/reference/rename.html) for remapping column names and offers helpers for excepting certain columns and/or including columns that start with a certain pattern etc: https://dplyr.tidyverse.org/reference/select.html.

I think the same applies for some of the pivoting operations being discussed.

**Comment by hawkfish** [comment]
Give that both BigQuery and ClickHouse support `REPLACE` and `EXCEPT` I think we should go that direction. ClickHouse's `COLUMNS` looks nice too, so maybe we should follow their lead?

None of the 800# gorillas (Oracle, MySQL, Postgres, SparkQL) have this syntax, but I did see that `EXCEPT` is used as a filtering condition to connect two `SELECT`s where the second is all the rows that should be excluded.

The real problem with adopting ClickHouse's `REPLACE` syntax is that it is indistinguishable from the function of the same name - which ClickHouse [doesn't have](https://clickhouse.tech/docs/en/sql-reference/functions/string-functions/). I'd call it `RENAME` if we do this - it is a better description and it doesn't conflict with a function name.

**Comment by domoritz** [comment]
`RENAME` to me sounds like it would replace a whole string while `REPLACE` replaced a substring. Wouldn't we be able to distinguish the expression function because it's a function call (i.e., it would not appear after a *)?

**Comment by hawkfish** [comment]
I meant that the syntax for SELECT renaming should be `RENAME` instead of `REPLACE`.  The syntax for `REPLACE` in ClickHouse is `REPLACE( <expr> AS col_name) `, which looks like a function call.

**Comment by domoritz** [comment]
Ahh, we misunderstood each other. Then I am on board.

**Comment by domoritz** [comment]
I think this feature is super important for data wrangling. Imagine if you want to create a view that replaces a column for example when parsing a date. If you add the same column again, you end up with a view that throws `Error: Binder Error: table "X" has duplicate column name "X"`.

**Comment by Mytherin** [comment]
Will have a go at implementing this.

**Comment by domoritz** [comment]
Thank you for implementing this in https://github.com/duckdb/duckdb/pull/2276 @Mytherin!

**Comment by dberardo-com** [comment]
related to this point, can this work already?

select *, count(*) as extra_count_column from <table> ?

**Comment by Alex-Monahan** [comment]
> related to this point, can this work already?
> 
> select _, count(_) as extra_count_column from
> 
> ?

Hello! I don’t think these are related. Maybe try:
```sql
Select *, count(*) over () as my_count from my_table
```

**Comment by dberardo-com** [comment]
it does work indeed. cheers
