### ISSUE TITLE
Hello, can I modify the local parquet file under the insert and update statements?

### ISSUE THREAD

**Issue by fanyo190** [duckdb/duckdb#2238]
Hello, can I modify the local parquet file under the insert and update statements?

**Comment by hannesmuehleisen** [comment]
No. Parquet files are read-only and should be. You can create new ones.

**Comment by fanyo190** [comment]
ok.thank you.

**Comment by hawkfish** [comment]
@fanyo190 can you close this if it is dealt with? Thanks!
