### ISSUE TITLE
A question about the release of duckdb jdbc memory

### ISSUE THREAD

**Issue by fanyo190** [duckdb/duckdb#2239]
Hello, I encountered a problem when using duckdb jdbc: each time a jdbc query is executed, the number of queries is limited to 1, after which it will increase the memory of the JVM more than ten megabytes, and it will take a long time to release. May I ask Why does this increase so much and how can it be released manually?

**Comment by Mause** [comment]
Can you please test if this is still an issue? We've fixed a number of memory leaks in the JDBC bindings recently

**Comment by omo** [comment]
(Unsolicited triage). Not hearing back since.  Maybe you can close this @Mause
