### ISSUE TITLE
Complex query spinlocks unless it ends with an aggregation

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#2245]
**What does happen?**
A (moderately complex, join-heavy) query returns correctly when topped off with`SELECT count(*)` or `SELECT DISTINCT a.id`.
However, it spinlocks with `SELECT *` or `SELECT a.id`.

**What should happen?**
It should return the results.

**To Reproduce**

### Data set
Use the following data set:
```bash
wget https://surfdrive.surf.nl/files/index.php/s/tfTs1s03Zmff1P4/download -O ldbc-sf100.zip
unzip ldbc-sf100.zip
```

### Q1
```sql
PRAGMA enable_profiling;
PRAGMA enable_progress_bar;
PRAGMA threads=48;
SELECT count(*)
FROM person a
JOIN interest a1
  ON a1.id = a.id
 AND a1.tagId = 2811
JOIN knows_symm k1
  ON k1.person1id = a.id
JOIN person b
  ON k1.person2id = b.id
 AND b.cityid = a.cityid
JOIN knows_symm k2
  ON k2.person1id = b.id
JOIN person c
  ON k2.person2id = c.id
 AND c.cityid = a.cityid
JOIN knows_symm k3
  ON k3.person1id = c.id
 AND k3.person2id = a.id
WHERE true
  -- a
  AND 100*month(DATE '2015-04-09') + day(DATE '2015-04-09') <= 100*month(a.birthday) + day(a.birthday)
  AND 100*month(DATE '2015-05-09') + day(DATE '2015-05-09') >= 100*month(a.birthday) + day(a.birthday)
  -- b
  AND 100*month(DATE '2015-04-09') + day(DATE '2015-04-09') <= 100*month(b.birthday) + day(b.birthday)
  AND 100*month(DATE '2015-05-09') + day(DATE '2015-05-09') >= 100*month(b.birthday) + day(b.birthday)
  -- c
  AND 100*month(DATE '2015-04-09') + day(DATE '2015-04-09') <= 100*month(c.birthday) + day(c.birthday)
  AND 100*month(DATE '2015-05-09') + day(DATE '2015-05-09') >= 100*month(c.birthday) + day(c.birthday)
;
```

### Q2
```sql
PRAGMA enable_profiling;
PRAGMA enable_progress_bar;
PRAGMA threads=48;
SELECT a.id
FROM person a
JOIN interest a1
  ON a1.id = a.id
 AND a1.tagId = 2811
JOIN knows_symm k1
  ON k1.person1id = a.id
JOIN person b
  ON k1.person2id = b.id
 AND b.cityid = a.cityid
JOIN knows_symm k2
  ON k2.person1id = b.id
JOIN person c
  ON k2.person2id = c.id
 AND c.cityid = a.cityid
JOIN knows_symm k3
  ON k3.person1id = c.id
 AND k3.person2id = a.id
WHERE true
  -- a
  AND 100*month(DATE '2015-04-09') + day(DATE '2015-04-09') <= 100*month(a.birthday) + day(a.birthday)
  AND 100*month(DATE '2015-05-09') + day(DATE '2015-05-09') >= 100*month(a.birthday) + day(a.birthday)
  -- b
  AND 100*month(DATE '2015-04-09') + day(DATE '2015-04-09') <= 100*month(b.birthday) + day(b.birthday)
  AND 100*month(DATE '2015-05-09') + day(DATE '2015-05-09') >= 100*month(b.birthday) + day(b.birthday)
  -- c
  AND 100*month(DATE '2015-04-09') + day(DATE '2015-04-09') <= 100*month(c.birthday) + day(c.birthday)
  AND 100*month(DATE '2015-05-09') + day(DATE '2015-05-09') >= 100*month(c.birthday) + day(c.birthday)
;
```

My output: https://gist.github.com/szarnyasg/5426dcbfdd9bcd117480b97bee916c1a

An important thing to note is that the query plan shown when Q2 is interrupted has incorrect tuple counts (including the final tuple count), e.g. it suggests that there are 0 results (while there should be 28).

**Environment (please complete the following information):**
 - OS: Fedora 32
 - DuckDB Version: v0.2.9-dev661 7cd82b5a2

**Comment by hawkfish** [comment]
Thanks I have it up. It looks like for some strange reason that `ScanStructure::NextInnerJoin` is rescanning the same rows over and over again.

**Comment by Mytherin** [comment]
Thanks for the report! I have looked into this, and I don't think it is actually deadlocking. Currently removing the aggregation will prevent parallelism in the final pipeline, which causes the query to take a much longer time.

Essentially, this query involves several exploding joins (going upwards to >10 billion tuples), which creates tons of duplicate entries in the hash table. These duplicates will create huge linked lists with all the duplicate entries/collisions. The final pipeline of this query then involves probing all of these hash tables, which involves chasing all of these linked lists for every tuple on the hash probe (hence being "stuck" in `ScanStructure::NextInnerJoin`).  When adding the aggregate parallelism is enabled for the hash probes, and with 48 threads this will be ~48X faster.

I would recommend just trying to let it run as it seems to finish for me.

> An important thing to note is that the query plan shown when Q2 is interrupted has incorrect tuple counts (including the final tuple count), e.g. it suggests that there are 0 results (while there should be 28).

If you interrupt a query it will show you the counts gathered so far, which would be 0 at the time as no results have made it past all the joins to the output yet.

**Comment by hawkfish** [comment]
We should not have to give people arcane instructions just to make queries execute in parallel. In this particular case, the scan is much faster than the threads, but even it wasn't, so what? And if a query needs to have a deterministic output, that is what `ORDER BY` is for.

There may be a SQL education issue here in that many of the tools used in the languages we embed in are single threaded and have deterministic output orderings. What we need to ask ourselves is whether we will get more bug reports from non-deterministic output that can be solved with an (intuitive) `ORDER BY` clause or more reports like this that need non-obvious solutions?

**Comment by Mytherin** [comment]
> Thanks for looking into this further @Mytherin
> 
> Still, we should not have to give people arcane instructions just to make queries execute in parallel. In this particular case, the scan is much faster than the threads, but even it wasn't, so what? And if a query needs to have a deterministic output, that is what `ORDER BY` is for.
> 
> There may be a SQL education issue here in that many of the tools used in the languages we embed in are single threaded and have deterministic output orderings. What we need to ask ourselves is whether we will get more bug reports from non-deterministic output that can be solved with an (intuitive) `ORDER BY` clause or more reports like this that need non-obvious solutions?

I fully agree that this should be executed in parallel, but I fear it is not as easy as just needing to educate people about SQL. Non-SQL systems in the data science field that many of our users are familiar with (e.g. Pandas, R DataFrames, etc) do have an actual meaningful order of tuples that users frequently rely on. Breaking that order will also cause surprises, especially for more simple queries with only projections or filters.

My current idea is that for result sets that are fully materialized we can quite nicely maintain the original order by having the scans also output the current row group id that they are scanning. In the result set construction we can then materialize the result sets aligned along these block ids (e.g. in an `map<block_id_t, ChunkCollection>`). This could be done fully in parallel as long as the individual threads have distinct block ids (which is the case for scanning our internal data format and Parquet files). All we need to do then is to emit the chunks in order of block ids.

This would require some re-engineering of the table scans, but as I am currently working on the push-based model (which requires heavy re-engineering anyway!) I will try to work that in there, unless there are other/better suggestions for solving this problem.

**Comment by hannesmuehleisen** [comment]
cc @stefan-grafberger

**Comment by szarnyasg** [comment]
Regarding the original issue - I can confirm that this is not a spinlock and the query indeed finishes. With a count to top it off, it takes ~1 minute and without it, it takes 25 minutes.

**Comment by hawkfish** [comment]
> My current idea is that for result sets that are fully materialized we can quite nicely maintain the original order by having the scans also output the current row group id that they are scanning. In the result set construction we can then materialize the result sets aligned along these block ids (e.g. in a `map<block_id_t, ChunkCollection>`). This could be done fully in parallel as long as the individual threads have distinct block ids (which is the case for scanning our internal data format and Parquet files). All we need to do then is to emit the chunks in order of block ids.

How would this impact non-aggregate queries that might produce extra rows? I'm thinking of a join that produced two rows per probe row. Would that result in the same block id being reported twice? It's probably not worth worrying about, but I thought it worth asking.

**Comment by Mytherin** [comment]
> > My current idea is that for result sets that are fully materialized we can quite nicely maintain the original order by having the scans also output the current row group id that they are scanning. In the result set construction we can then materialize the result sets aligned along these block ids (e.g. in a `map<block_id_t, ChunkCollection>`). This could be done fully in parallel as long as the individual threads have distinct block ids (which is the case for scanning our internal data format and Parquet files). All we need to do then is to emit the chunks in order of block ids.
> 
> How would this impact non-aggregate queries that might produce extra rows? I'm thinking of a join that produced two rows per probe row. Would that result in the same block id being reported twice? It's probably not worth worrying about, but I thought it worth asking.

The same block id would be repeated many times regardless. The block ids are not unique per row but rather apply to a batch of rows. For example, all the rows in the same row group would have the same block id. This method relies on the fact that within a particular thread, the rows are produced in the "correct" order, so all we need to do is figure out which source batch the rows come from. We don't actually need to re-order rows within the same block id as we know they all originated from the same thread, and hence they are already in the correct order. All we need to do is figure out the order of blocks between the different threads.

**Comment by hawkfish** [comment]
Anything else or can we close this one?
