### ISSUE TITLE
Sorting ignoring Null Value Order for Floats

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#2252]
**What does happen?**
The unoptimized and optimized results don't match in the sort order.

**To Reproduce**
The following test case should result in the issue:

```sql
statement ok
PRAGMA enable_verification

statement ok
create table tbl_1 (a float, b float)

statement ok
insert into tbl_1 values (1,NULL),(2,3),(NULL,NULL)

statement ok
create table tbl_2 (b float)

statement ok
insert into tbl_2 values (1),(2),(NULL)

query II
select a,tbl_2.b from tbl_1 inner join tbl_2 on (a IS DISTINCT FROM tbl_2.b) order by a,tbl_2.b
----
NULL	1
NULL	2
1	NULL
1	2
2	NULL
2	1 
```

**Comment by pdet** [comment]
@lnkuiper

**Comment by lnkuiper** [comment]
Ha, I found this bug a few days ago, and fixed it in my branch. I will try to send the PR before I go on a short vacation!

**Comment by pdet** [comment]
There is no rush! I just logged here so we wouldn't miss it :-)

**Comment by lnkuiper** [comment]
This should be fixed when #2255 gets merged.

**Comment by Mytherin** [comment]
This is fixed now in the master.

**Comment by Alex-Monahan** [comment]
What was the scope of this (small!) bug? Any time you were sorting floats, or something more specific? Just thinking about our production environment...

Thanks!

**Comment by Mytherin** [comment]
> What was the scope of this (small!) bug? Any time you were sorting floats, or something more specific? Just thinking about our production environment...
> 
> Thanks!

I believe this bug would only happen if you ran with query verification enabled, which shouldn’t happen outside of our own test cases, so no danger there.
