### ISSUE TITLE
Refactoring Idea: Decouple FileSystem as an interface from FileSystem as the default local filesystem implementation.

### ISSUE THREAD

**Issue by omo** [duckdb/duckdb#2257]
Currently FileSystem class serves as a virtual FS backend interface and the default local FS backend implementation.
This creates problems like https://github.com/duckdb/duckdb/pull/2256.

We can extract FileSystem implementation into separate, say, LocalFileSystem class and make FileSystem class as an
abstract class.

**Comment by omo** [comment]
If there is no objection and there is no one else getting this done,
I'm happy to work on this once I finish up what I'm working on right now,

**Comment by Mytherin** [comment]
> We can extract FileSystem implementation into separate, say, LocalFileSystem class and make FileSystem class as an
abstract class.

That sounds like a good idea. The base method in FileSystem can throw an internal exception (e.g. `GetFileType not implemented for this file system type`, etc).

**Comment by Mytherin** [comment]
This has been implemented now. Thanks again for all the work!
