### ISSUE TITLE
TPC-H Q6 fails on Parquet input

### ISSUE THREAD

**Issue by wesm** [duckdb/duckdb#2261]
I ran the following query from Python:

```
WITH lineitem AS (SELECT * FROM "0.parquet")
SELECT
    sum(l_extendedprice * l_discount) AS revenue
FROM
    lineitem
WHERE
    l_shipdate >= CAST('1994-01-01' AS date)
    AND l_shipdate < CAST('1995-01-01' AS date)
    AND l_discount BETWEEN 0.05
    AND 0.07
    AND l_quantity < 24;
```

with the following Parquet file: https://drive.google.com/file/d/1kdsASWJ0KEdP8IDigHN-9ibVJBbHlVSP/view?usp=sharing

and got the following exception:

```
RuntimeError: Not implemented Error: Unsupported type for filter FLAT DECIMAL(15,2): (UNKNOWN COUNT) [ ]
```

The Parquet files were obtained by using `CALL dbgen(sf=1);` and then exporting each TPC-H table to Arrow format, which I then wrote to Parquet format (using `pyarrow.parquet` -- I know that DuckDB can also export Parquet files, but this gave me the control I was looking for). 

**Environment (please complete the following information):**
 - Linux gcc 9.3
 - git master

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2262. As suggested by the error the problem was missing support for filters on decimal columns within Parquet files.
