### ISSUE TITLE
How to build the R package with optional extensions?

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#2264]
I'm trying to build + install the R package with some of the optional extensions (specifically tpch, but could be any of the other extensions). Ideally, I would like to be able to do this with a combination of envvars + `remotes::install_github()` or `R CMD install .` rather than git clone + build from source.

I was able to get the package built with the extension by adding the extension that I wanted to [tools/rpkg/rconfigure.py](https://github.com/duckdb/duckdb/blob/master/tools/rpkg/rconfigure.py#L6) and everything works. Is there already a way to do this that isn't editing this file? 

I'm happy to send a PR that allows this (e.g. set an envvar that tools/rpkg/rconfigure.py looks for and appends to the extensions list before building), but wanted to make sure I'm not missing some other way to do this that already exists.

**Comment by Mytherin** [comment]
There is no way of doing this currently without changing that file. Happy to review the PR!
