### ISSUE TITLE
"Struct child row count mismatch" on parquet read

### ISSUE THREAD

**Issue by AlexanderVR** [duckdb/duckdb#2267]
```
>>> duckdb.query("select * from 'test.parquet'").fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Struct child row count mismatch
```

Expect duckdb to be able to read from the parquet file.

Minimal offending parquet file attached.

 - OS: MacOS 11.5
 - DuckDB Version: 0.2.9 and 0.2.10.dev247
[test.parquet.zip](https://github.com/duckdb/duckdb/files/7148879/test.parquet.zip)

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2267. Could you check if that solves the problem for you?

**Comment by AlexanderVR** [comment]
It does fix the issue, thank you!

**Comment by AlexanderVR** [comment]
Although, just noticed another bug with the array handling:
```
select array_extract(assignedLicenses,0) from 'test.parquet';
Error: Not implemented Error: Unimplemented type for LIST_EXTRACT
```

Happy to file another bug report if that helps

**Comment by Mytherin** [comment]
Yes, please do. I will close this one then. Thanks!
