### ISSUE TITLE
Support binning for histograms over numeric columns

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2268]
One of the first things to look at in EDA is the distribution of numeric fields. It would be great if DuckDB had good support for computing histograms or other distributions over numeric fields (binned aggregation). I think what would help is good support for binning. 

For simple equi-width histograms, we need to know the bin size and bin offset to bin data. Often, these can be inferred somewhat automatically from the extent of the data and the desired number of bins (here is how Vega does it: https://github.com/vega/vega/blob/master/packages/vega-statistics/src/bin.js). A reasonable number of bins can often also be inferred (https://en.wikipedia.org/wiki/Histogram#Number_of_bins_and_width). It would be great if DuckDB support the case where someone does or does not know the bin offset and size.

Right now, the way to do binning (given a bin size and offset) is to write a somewhat unwieldy expression with `floor`. A good starting point would be to add a binning expression function that takes a bin size and offset (default 0). Later, we could add support for determining the bin size given an extent (which could also be computed as a subquery). 

Relatedly, `numeric_histogram` remained unimplemented after https://github.com/duckdb/duckdb/issues/1125.

**Comment by mskyttner** [comment]
+1 For binned aggregation, algorithms similar to what [classIntervals](https://www.rdocumentation.org/packages/classInt/versions/0.4-3/topics/classIntervals)  provides with styles such as "equal", "fixed", "fisher" (natural breaks), "headtails" would provide a good starting point for creating numeric histograms?

**Comment by hamilton** [comment]
+1. for me as well – a fast numeric histogram aggregation function would be a total game-changer for duckdb.

**Comment by domoritz** [comment]
Yes, while it's quite cumbersome, it is possible to do binning in DuckDB. I think a convenient wrapper would be great. It would probably take the data and the number of bins as well as an optional range. I think the query can also be written without a join and just floor. 

However, one major limitation of the approach above is that the bin ranges may not be very friendly. I mentioned this issue in my original description above. 

See for example the dummy table in your example. 

```
duckdb> select * from dummy_bins;
┌────────┬────────────────────┬────────────────────┐
│ bin_id ┆ bin_min            ┆ bin_max            │
╞════════╪════════════════════╪════════════════════╡
│      0 ┆                  1 ┆ 11.777777777777777 │
│      1 ┆ 11.777777777777777 ┆ 22.555555555555554 │
│      2 ┆ 22.555555555555554 ┆  33.33333333333333 │
│      3 ┆  33.33333333333333 ┆  44.11111111111111 │
│      4 ┆  44.11111111111111 ┆  54.88888888888889 │
│      5 ┆  54.88888888888889 ┆  65.66666666666666 │
│      6 ┆  65.66666666666666 ┆  76.44444444444444 │
│      7 ┆  76.44444444444444 ┆  87.22222222222221 │
│      8 ┆  87.22222222222221 ┆                 98 │
└────────┴────────────────────┴────────────────────┘
```

It would be nice if the range of the overall histogram was [0, 100] so that the bins are [0,10], [10,20], etc. You could easily implement some logic in C++ for this but it's unclear how to write the right expression without loops in SQL.

**Comment by sgilligan** [comment]
+ for binning

**Comment by mariosasko** [comment]
Any updates on this? I think a good first step would be support for computing histograms on predefined bins (`bins` param in NumPy/Polars).

**Comment by StLeoX** [comment]
The `numeric_histogram` UDAF in `Hive` describes an `equi-height histogram`.
The detailed algorithm is [here](https://www.jmlr.org/papers/volume11/ben-haim10a/ben-haim10a.pdf).

**Comment by mgmorcos** [comment]
👍

**Comment by severo** [comment]
In case it helps, ObservableHQ's Plot library also provides [methods to infer the bins](https://observablehq.com/plot/transforms/bin#bin-options)

<img width="683" alt="Capture d’écran 2023-11-02 à 11 06 16" src="https://github.com/duckdb/duckdb/assets/1676121/09f43374-afb1-4d05-a188-e483e04b5519">

**Comment by domoritz** [comment]
The hardest part is to get nice bin boundaries in addition getting a reasonable number of bins (I found the default from Plot above works pretty well for that).

**Comment by hamilton** [comment]
+1 to @domoritz ~ the hardest part is setting nice bin boundaries. Porting over D3's [nice nudging](https://github.com/d3/d3-array/blob/main/src/nice.js) to C++ wouldn't actually be that difficult. I gave this a shot using recursive CTEs in pure SQL, but found that it's quite challenging to get nested recursive CTEs to work correctly.

WIth this in mind, you really need a way to go from `start`, `stop`, `bucket_count` to `nice_start`, `nice_stop`, `nice_bucket_count`. Then from there you can implement any method you want.

**Comment by domoritz** [comment]
I think starting with a helper function to compute bins as @hamilton suggested would be great.

**Comment by mhkeller** [comment]
This one may be beyond my abilities but if there is anywhere to pitch in or help with this, let me know.

**Comment by kevinschaich** [comment]
This is as close as I can get – it requires no temp tables so you can fire off a bunch at once (replace `table_name` and `column_name` with your desired values):

```SQL
WITH bin_counts AS (
	SELECT
		bins.bin_id,
		bins.bin_min,
		bins.bin_max,
		bins.bin_width,
		COUNT(column_name) AS count
	FROM (
		SELECT
			range AS bin_id,
			minv + (maxv - minv) * (range / n::DOUBLE) AS bin_min,
			minv + (maxv - minv) * ((range + 1) / n::DOUBLE) AS bin_max,
			(maxv - minv) / n AS bin_width
		FROM (
			SELECT
				*,
				max(range) over () + 1 AS n
			FROM
				range(0, 20),
				(
					SELECT
						min(column_name) AS minv,
						max(column_name) AS maxv
					FROM
						table_name
				) AS range_values
		) AS bin_definitions
	) AS bins
	LEFT JOIN table_name
	ON column_name >= bins.bin_min AND column_name < bins.bin_max
	GROUP BY bins.bin_id, bins.bin_min, bins.bin_max, bins.bin_width
),
max_count AS (
	SELECT MAX(count) AS max_count FROM bin_counts
)
SELECT
	bin_id,
	bin_min,
	bin_max,
	bin_width,
	count,
	LPAD(''::VARCHAR, CEIL((count / max_count.max_count) * 20)::INTEGER, '|'::VARCHAR) AS histogram_bar
FROM bin_counts, max_count
ORDER BY bin_id;
```

Output:

```
┌────────┬────────────────────┬────────────────────┬───────────┬───────┬──────────────────────┐
│ bin_id │      bin_min       │      bin_max       │ bin_width │ count │    histogram_bar     │
│ int64  │       double       │       double       │  double   │ int64 │       varchar        │
├────────┼────────────────────┼────────────────────┼───────────┼───────┼──────────────────────┤
│      0 │           121644.0 │           155555.2 │   33911.2 │  1652 │ ||||||||             │
│      1 │           155555.2 │ 189466.40000000002 │   33911.2 │  4374 │ |||||||||||||||||||| │
│      2 │ 189466.40000000002 │ 223377.59999999998 │   33911.2 │  1692 │ ||||||||             │
│      3 │ 223377.59999999998 │ 257288.80000000002 │   33911.2 │   118 │ |                    │
│      4 │ 257288.80000000002 │           291200.0 │   33911.2 │     0 │                      │
│      5 │           291200.0 │ 325111.19999999995 │   33911.2 │   122 │ |                    │
│      6 │ 325111.19999999995 │           359022.4 │   33911.2 │  1282 │ ||||||               │
│      7 │           359022.4 │ 392933.60000000003 │   33911.2 │     0 │                      │
│      8 │ 392933.60000000003 │           426844.8 │   33911.2 │   987 │ |||||                │
│      9 │           426844.8 │           460756.0 │   33911.2 │     0 │                      │
│     10 │           460756.0 │           494667.2 │   33911.2 │     0 │                      │
│     11 │           494667.2 │  528578.3999999999 │   33911.2 │   480 │ |||                  │
│     12 │  528578.3999999999 │  562489.6000000001 │   33911.2 │   987 │ |||||                │
│     13 │  562489.6000000001 │           596400.8 │   33911.2 │     0 │                      │
│     14 │           596400.8 │           630312.0 │   33911.2 │  1467 │ |||||||              │
│     15 │           630312.0 │  664223.2000000001 │   33911.2 │   987 │ |||||                │
│     16 │  664223.2000000001 │           698134.4 │   33911.2 │   987 │ |||||                │
│     17 │           698134.4 │           732045.6 │   33911.2 │     0 │                      │
│     18 │           732045.6 │  765956.7999999999 │   33911.2 │   987 │ |||||                │
│     19 │  765956.7999999999 │           799868.0 │   33911.2 │    95 │ |                    │
├────────┴────────────────────┴────────────────────┴───────────┴───────┴──────────────────────┤
│ 20 rows                                                                           6 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────┘
```

I tried making it into a prepared statement so you can call it like a function with `$table_name` and `$column_name`, but I was getting a syntax error. Welcome any feedback or improvements. I think it would be great to have this as a standard lib function as well (e.g. add an optional argument to the current function: `histogram(arg)` -> `histogram(arg, num_bins?)`.

<details><summary>Note: If you don't care about the visual bars it can be simplified a bit like this. </summary>

```sql
SELECT
	bins.bin_id,
	bins.bin_min,
	bins.bin_max,
	bins.bin_width,
	COUNT(column_name) AS count,
FROM (
	SELECT
		range AS bin_id,
		minv + (maxv - minv) * (range / n::DOUBLE) AS bin_min,
		minv + (maxv - minv) * ((range + 1) / n::DOUBLE) AS bin_max,
		(maxv - minv) / n AS bin_width
	FROM (
		SELECT
			*,
			max(range) over () + 1 AS n
		FROM
			range(0, 20),
			(
				SELECT
					min(column_name) AS minv,
					max(column_name) AS maxv
				FROM
					table_name
			) AS range_values
	) AS bin_definitions
) AS bins
LEFT JOIN table_name
ON column_name >= bins.bin_min AND column_name < bins.bin_max
GROUP BY bins.bin_id, bins.bin_min, bins.bin_max, bins.bin_width
ORDER BY bins.bin_id;
```

</details>

**Comment by domoritz** [comment]
Still active.

**Comment by Tishj** [comment]
@domoritz there was a PR linked: #12590 and #12548 

Does that not add the functionality requested here?

**Comment by hannes** [comment]
Indeed it did @domoritz I think you're going to like those PRs

**Comment by domoritz** [comment]
This is awesome. I played a bit with it and it's really nice to use. There are some tweaks to the implementation that could make the results even nicer but the APIs are nice and clean.
