### ISSUE TITLE
IO Error when ingesting arrow dataset with ORDER BY

### ISSUE THREAD

**Issue by bmschmidt** [duckdb/duckdb#2270]
Thanks again for this project. The new pyarrow dataset bindings look great.

**What does happen?**

When ingesting a large (500M row) pyarrow dataset with with an `ORDER BY` clause, duckdb errors after spending about a minute using ~100% CPU core and about 50% of system memory.

The code below results in an error like `RuntimeError: IO Error: Could not write file "tmpdo97xmeq/db.tmp/4611686018427496535.block": Invalid argument`

**What should happen?**

Ideally, create a sorted table. If ingesting from arrow with a sort this way is unreasonable or broken, throw an informative error instead. 

**To Reproduce**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] OS 10.15.7
 - DuckDB Version: 0.2.10-dev247 (and also 0.2.9) 
 - 64GB RAM: 500GB free on the disk where all operations should be taking place, although less space in the system's main tmp drive which shouldn't (?) be relevant.

```python
import tempfile
import duckdb
import pyarrow as pa
from pyarrow import dataset, feather
from pathlib import Path
from numpy.random import randint

with tempfile.TemporaryDirectory(dir = ".") as d:
    dir = Path(d)
    # feather directory.
    feathers = dir / "feather"
    feathers.mkdir()
    db = duckdb.connect(str(dir / "db"))
    # Write out 500 million rows across 100 different feather files 
    # and read it as an Arrow dataset
    for i in range(100):
        t = pa.table({"a": randint(0, 1_000, 5_000_000), "b": randint(0, 1_000, 5_000_000), "c": randint(0, 1_000, 5_000_000)})
        feather.write_feather(t, feathers / f"{i}.feather")
    ds = dataset.dataset(str(feathers), format = "arrow")
    db.register_arrow("dataset", ds)
    
    db.execute("CREATE TABLE sorted AS SELECT * FROM dataset ORDER BY a, b, c")
```

The code below, which uses a single parquet file instead of 100 separate feather files in a dataset, appears to run successfully.

```python
import tempfile
import duckdb
import pyarrow as pa
from pyarrow import dataset, parquet
from pathlib import Path
from numpy.random import randint

with tempfile.TemporaryDirectory(dir = ".") as d:
    dir = Path(d)
    # feather directory.
    writer = parquet.ParquetWriter(dir / "data.parquet", pa.schema({"a": pa.int64(), "b": pa.int64(), "c": pa.int64()}))
    db = duckdb.connect(str(dir / "db"))
    # Write a 500 million row parquet file in 100 steps.
    for i in range(100):
        t = pa.table({"a": randint(0, 1_000, 5_000_000), "b": randint(0, 1_000, 5_000_000), "c": randint(0, 1_000, 5_000_000)})
        writer.write_table(t)
    writer.close()
    loc = str(dir / "data.parquet")
    db.execute(f"CREATE TABLE sorted AS SELECT * FROM parquet_scan('{loc}') ORDER BY a, b, c")
    m = db.execute("SELECT COUNT(*) FROM sorted").df()
    
print(m)

```

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [Yes] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Thanks for the report!

I have spend some time investigating this:

The reason it works fine on the Parquet file is that the Parquet file exposes statistics to us, specifically the min and max value. Using the min and max value the `ORDER BY` can place the values in significantly less memory, which causes the operation to fit in memory and never have to go to disk. You would see similar behavior with the Parquet file if you increased the range of the randomly generated data from `[0, 1000]` to e.g. `[0, 2**50]`.

The Arrow scan does not expose such statistics to us, so we keep the values stored in an int64, which significantly increases the required memory footprint of the operator. Now because of the increased memory footprint, the system offloads data to disk. For some reason this seems to fail on your system (as indicated by the failure to write the file).

I tried to reproduce this failure, but it seems to work fine on my system, merely taking a lot longer since data has to be written to disk and read back. What operating system are you using? Are any temporary files written in the `db.tmp` directory, or does it fail immediately upon writing the first file? Can you yourself write files to this directory, or is your file system perhaps mounted as read-only?

The "Invalid argument" comes from [`write` returning `EINVAL`](https://man7.org/linux/man-pages/man2/write.2.html):
```
EINVAL fd is attached to an object which is unsuitable for
              writing; or the file was opened with the O_DIRECT flag,
              and either the address specified in buf, the value
              specified in count, or the file offset is not suitably
              aligned.
```

Since we don't use `O_DIRECT` for writing temporary files, this seems to indicate writing is not possible here for some reason.

**Comment by bmschmidt** [comment]
Thanks for the explanation and investigation.

The problem appears to be at (or before) the first temporary file write. I am able to manually write to a file within "db.tmp" before ingesting, so I don't think it's an entirely straightforward permissions issue. (Code run below--still breaks on the last line).

This is OS X 10.15.7. The drive I am writing to is an external RAID array--specifically a drobo-brand drive that uses some abstractions I don't really understand, but which generally works fine.

I would try it on the main system drive, but I have more RAM on the machine (64GB) than free disk space (35GB), so I don't know how to trigger it to abandon in-memory sorting. [The obvious mechanism for doing so appears not to work on OS X.](https://stackoverflow.com/questions/3274385/how-to-limit-memory-of-a-os-x-program-ulimit-v-neither-m-are-working)

Demo of permissions testing:

```python
with tempfile.TemporaryDirectory(dir = ".") as d:
    dir = Path(d)
    # feather directory.
    feathers = dir / "feather"
    feathers.mkdir()
    db = duckdb.connect(str(dir / "db"))
    # Write out 500 million rows across 100 different feather files 
    # and read it as an Arrow dataset
    (dir / "db.tmp").mkdir()
    with open(dir / "db.tmp" / "test_file.txt", "w") as fout:
        fout.write("test writing") ######################   <- Succeeds
    for i in range(100):
        t = pa.table({"a": randint(0, 1_000, 5_000_000), "b": randint(0, 1_000, 5_000_000), "c": randint(0, 1_000, 5_000_000)})
        feather.write_feather(t, feathers / f"{i}.feather")
    ds = dataset.dataset(str(feathers), format = "arrow")
    db.register_arrow("dataset", ds)
    
    db.execute("CREATE TABLE sorted AS SELECT * FROM dataset ORDER BY a, b, c") #### <- Fails

```

**Comment by Mytherin** [comment]
> This is OS X 10.15.7. The drive I am writing to is an external RAID array--specifically a drobo-brand drive that uses some abstractions I don't really understand, but which generally works fine.

Hm, it wouldn't surprise me if the system API calls we use are not correctly supported there. Can you store data inside the database file itself, e.g. using `CREATE TABLE tbl AS SELECT * FROM dataset`?

> I would try it on the main system drive, but I have more RAM on the machine (64GB) than free disk space (35GB), so I don't know how to trigger it to abandon in-memory sorting. The obvious mechanism for doing so appears not to work on OS X.

You could force the system not to offload blocks to disk by setting `PRAGMA memory_limit=-1`. Perhaps give that a shot?

**Comment by bmschmidt** [comment]
Yes, if I change the last line `db.execute("CREATE TABLE unsorted AS SELECT * FROM dataset")`, things behave properly (`db.wal` fills up first, and then a graceful exit.)
