### ISSUE TITLE
Jupyter kernel suddenly dies in version 0.2.9

### ISSUE THREAD

**Issue by FernandoRI** [duckdb/duckdb#2273]
**Issue**

When running queries in a Jupyter notebook (in a Sagemaker instance) the following error comes up even when querying relatively small amounts of data (8k rows):

`The kernel appears to have died. It will restart automatically.`

System memory is 32 Gb and plenty (70%) free; constantly monitoring it using the glances library.

I think I traced back the error to the change from version 0.2.8 to 0.2.9.   Queries that were previously running correctly now display the kernel error message, however if version 0.2.8 (`pip install 'duckdb==0.2.8'`) is installed, the problem never happens.

The query is run using the following code:
```
sql_statement = 'SELECT .....'
duckdb.query(sql_statement).to_df()
```

**Environment :**
 - OS: Linux 4.14.238-125.422.amzn1.x86_64 x86_64
 - DuckDB Version 0.2.9
 - Python:  3.6.13
 - Jupyter Notebook 

Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.7.11
The server is running on this version of Python:
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0]

Current Kernel Information:
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

**Comment by Mytherin** [comment]
Thanks for the report! Could you provide the queries + data set so we can try to reproduce this problem?

**Comment by catriona-reader** [comment]
Fyi I'm experiencing this as well - at first just when I ran a notebook in JupyterHub, but now on my local instance as well. 

Running simple queries on an individual table seems to be fine, but I get the error when I (a) register multiple tables to work on (more then 3), when I use larger data files, or when I try to do any type of more complex query, i.e. with a join. 

It produces the error  every time I run 0.2.9 in JupyterHub. It first occurred on my local instance after I'd downgraded to 0.2.8, then upgraded again to version 0.2.9. 

Here is an example set up: 
`con = duckdb.connect(database=':memory:', read_only=False)

# memory usage: 3.3+ MB
# dtypes: Int64(2), int64(2), object(10)
incident = pd.read_pickle('incident.pkl')
con.register('incident', incident)

# dtypes: Int64(2), datetime64[ns](1), int64(5), object(3)
# memory usage: 73.8+ MB
incident_activity = pd.read_pickle('incident_activity.pkl')
con.register('incident_activity', incident_activity)`

And an example of the query that would produce the error: 

```
con.execute("""SELECT * 
                FROM incident 
                JOIN incident_activity ON 
                incident.incident_number == incident_activity.incident""")
```

**Comment by Mytherin** [comment]
Could you share the dataset + code that causes the crash, either here or privately to my e-mail (m.raasveldt@cwi.nl)?

**Comment by vinson2233** [comment]
@Mytherin alright, I just sent the dataset + code to you.
