### ISSUE TITLE
Group-By on col with null value causes seg fault

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#2281]
A group-by query on a pandas df which contains empty values causes a seg fault.  This causes us to not be able to use duckdb. I'm using version 0.2.9.

The csv is:

    what,is_control,is_test
    ,0,0
    foo,1,0

The query is:

    select what, count(*) from c group by what

The python code is below. I don't know where in this the seg fault occurs:

    conn.register("c", df)
    conn.execute(sql)
    df_result = conn.fetchdf()

**Comment by hannesmuehleisen** [comment]
I have reverse engineered the script and indeed this crashes with 0.2.9:

````Python
import duckdb
import pandas
import io

csv = '''
what,is_control,is_test
,0,0
foo,1,0
'''
df = pandas.read_csv(io.StringIO(csv))

conn = duckdb.connect()
conn.register("c", df)
conn.execute('select what, count(*) from c group by what'
)
df_result = conn.fetchdf()
print(df_result)
````

**Comment by hannesmuehleisen** [comment]
This strangely looks like a crash in `pybind11`

**Comment by Alex-Monahan** [comment]
Do you know how widespread this bug is? Does it fail with all bills or just a certain type of NaN/null? Just trying to see if we can use 0.2.9 in prod!

**Comment by hannesmuehleisen** [comment]
This is specific to Pandas and some NULLs in string columns as far as I can tell

**Comment by scottee** [comment]
Is there an estimate of when this fix will be released? Or is there a way to pull the PR for this issue on top of 0.2.9? It's preventing us from using duckdb in prod.

**Comment by hannesmuehleisen** [comment]
@scottee if you install duckdb with `pip install duckdb --upgrade --pre` you should get a fixed version

**Comment by scottee** [comment]
I agree I could do that to test out the fix on other queries. However, deploying a pre-release version isn't stable, so I can't deploy that in production. Is it possible I could get a 0.2.10 with just bug fixes in it? Alternately, when will the next version be going out? 

I love what you've done with duckdb; I really want to be able to use it asap.
