### ISSUE TITLE
generate_series() and range() throwing catalogue_error in version 0.2.9

### ISSUE THREAD

**Issue by catriona-reader** [duckdb/duckdb#2283]
Both of the following throw catalogue_errors: 

`con.execute("SELECT range(TIMESTAMP '2001-04-10', TIMESTAMP '2001-04-11', INTERVAL 30 MINUTE)")
`
`con.execute("SELECT generate_series(TIMESTAMP '2001-04-10', TIMESTAMP '2001-04-11', INTERVAL 30 MINUTE)")
`
These are the example queries taken from https://duckdb.org/docs/sql/functions/timestamp, Timestamp Table Functions. 

Running in a jupyter notebook with: 
- duckdb 0.2.9
- pandas 1.2.5 
- python 3.7.4

Error displayed: 

RuntimeError: Catalog Error: Scalar Function with name generate_series does not exist!
Did you mean "greatest"?
LINE 1: SELECT GENERATE_SERIES(TIMESTAMP '2001-04-10',...

**Comment by Mytherin** [comment]
Thanks for the report!

They are table functions, so they should be used in the FROM clause, e.g.:

```sql
SELECT * FROM generate_series(TIMESTAMP '2001-04-10', TIMESTAMP '2001-04-11', INTERVAL 30 MINUTE);
```

**Comment by catriona-reader** [comment]
Got it, thanks Mark!

**Comment by catriona-reader** [comment]
Sorry to reopen but want to confirm that there is then no way to use generate_series() to mimic the following PostgreSQL behaviour? 

`SELECT incident_number, reported_time, resolved_time FROM incident LIMIT 10 
`
| incident_number | reported_time | resolved_time |
| ----------------- | -------------- | ------------- |
| INC13530374 | 2021-03-29 16:07:31+00 | 2021-03-29 16:08:20+00 | 
| INC13530597 | 2021-03-29 16:42:51+00 | 2021-03-29 16:46:27+00 |
| INC13536258 | 2021-03-30 07:22:03+00 | 2021-03-30 07:27:23+00 |
| INC13542758 | 2021-03-30 14:49:36+00 | 2021-03-30 14:52:22+00 |
| INC13549497 | 2021-03-31 08:48:19+00 | 2021-03-31 08:51:26+00 |
| INC13551921 | 2021-03-31 12:14:42+00 | 2021-03-31 12:21:08+00 |
| INC13530593 | 2021-03-29 16:41:14+00 | 2021-03-29 16:42:15+00 |
| INC13530476 | 2021-03-29 16:23:57+00 | 2021-03-29 16:26:34+00 |
| INC13535993 | 2021-03-30 07:06:49+00 | 2021-03-30 07:10:55+00 |

`SELECT incident_number, generate_series(reported_time, resolved_time, '15 mins') 
FROM incident 
LIMIT 10 `

| incident_number | generate_series | 
| ----------------- | -------------- | 
| INC13530674 | 2021-03-29 17:01:57+00 |
| INC13530674 | 2021-03-29 17:16:57+00 |
| INC13530674 | 2021-03-29 17:31:57+00 |
| INC13530674 | 2021-03-29 17:46:57+00 | 
| INC13530674 | 2021-03-29 18:01:57+00 |
| INC13530674 | 2021-03-29 18:16:57+00 |
| INC13530674 | 2021-03-29 18:31:57+00 |
| INC13530674 | 2021-03-29 18:46:57+00 |
| INC13530674 | 2021-03-29 19:01:57+00 |
| INC13530674 | 2021-03-29 19:16:57+00 |

**Comment by Mytherin** [comment]
You can use the numeric `generate_series` together with `datediff` to get a similar result:
```sql
D create table incident(reported_time TIMESTAMP, resolved_time TIMESTAMP);
D insert into incident values (timestamp '2021-03-29 16:07:31', timestamp '2021-03-29 17:26:20');
D select reported_time + unnest(generate_series(0, datediff('minute', reported_time, resolved_time) / 15)) * interval '15 minutes' from incident;
┌────────────────────────────────────────────────────────────────────────────────────┐
│ reported_time + unnest(generate_series(0, datediff(minute, reported_time, resol... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 2021-03-29 16:07:31                                                                │
│ 2021-03-29 16:22:31                                                                │
│ 2021-03-29 16:37:31                                                                │
│ 2021-03-29 16:52:31                                                                │
│ 2021-03-29 17:07:31                                                                │
│ 2021-03-29 17:22:31                                                                │
└────────────────────────────────────────────────────────────────────────────────────┘

**Comment by catriona-reader** [comment]
Great, thanks for this example Mark +1
