### ISSUE TITLE
Add std and quantiles to summarize

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2286]
https://github.com/duckdb/duckdb/pull/2189 introduces SUMMARIZE. For numbers, it computes (among other things) the min, max, and avg. I think it would be good to include quantiles between min and max (25%, 50% (aka median), 75%) and the spread of the data around the mean (std) by default as well. The reason is that the mean alone can be misleading for many distributions.

**Comment by hannesmuehleisen** [comment]
Would an approx quantile be acceptable here?

**Comment by domoritz** [comment]
I think so. To me, SUMMARIZE gives you an initial understanding of the table/query result and therefore approximation should be sufficient.

**Comment by hawkfish** [comment]
This would also be very useful for improved generation of synthetic data from bug reports.

**Comment by domoritz** [comment]
How would quantiles in summarize help with generating synthetic data from bug reports?

**Comment by hawkfish** [comment]
It would describe the distribution/skew better, which might be important for triggering the failure.

**Comment by Mytherin** [comment]
Implemented in #2356
