### ISSUE TITLE
Add `.max_rows` option to the CLI

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2288]
When using the DuckDB CLI, one rarely needs all rows in the output. To limit the number of rows, one can add `LIMIT` to the SQL query but that's cumbersome as it has to be repeated for every query. Moreover, it hides how many rows are in the result. 

I would like to propose `.max_rows` as an option to limit the displayed rows. A trimmed table would show some text like `...N more rows` or `...N of K rows hidden`

```
D .max_rows 3
D select * from weather;
┌───────────────┬─────────┬─────────┬──────┬────────────┐
│     city      │ temp_lo │ temp_hi │ prcp │    date    │
├───────────────┼─────────┼─────────┼──────┼────────────┤
│ San Francisco │ 46      │ 50      │ 0.25 │ 1994-11-27 │
│ Hayward       │ 37      │ 54      │      │ 1994-11-29 │
│ San Francisco │ 43      │ 57      │ 0.0  │ 1994-11-29 │
 ...20 of 23 rows hidden
```

**Comment by Lyonsclay** [comment]
There is a setting `.maxrows` that is exactly as described in this request. It must have been introduced after this issue was posted.

**Comment by Mytherin** [comment]
Yes, the new duckbox renderer (#5140) does exactly as proposed in this issue
