### ISSUE TITLE
Multiline prompt in CLI is misaligned

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2289]
**What does happen?**

```
$ duckdb
0.2.9 1776611ab
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select *
   ...> from foo;
```

Notice how the `select` and `from` are not aligned.

SQLite doesn't have this problem

```
$ sqlite3
SQLite version 3.32.3 2020-06-18 14:16:19
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select *
   ...> from foo;
```

**What should happen?**

```
$ duckdb
0.2.9 1776611ab
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select *
  from foo;
```

**Environment (please complete the following information):**
 - OS: macOS
 - DuckDB Version: 0.2.9 1776611ab

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2290.

Note that you can customize the prompt yourself as well:

```sql
.prompt "D " "> "
```
