### ISSUE TITLE
`AVG` result has low precision

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#2295]
Function `avg` computes an average that might not be precise if dealing with a large amount of numbers or with numbers in different scales. I am guessing it might be calculating a simple sum with `double` types and dividing by the number of elements, which can make the results inaccurace.

Example in R:
```r
library(DBI)
library(duckdb)
df = data.frame(col1 = c(2^53, 1, 1, 0))
conn = dbConnect(duckdb::duckdb(), dbdir=":memory:", read_only=FALSE)
duckdb_register(conn, "df", df)
res = dbGetQuery(conn, "SELECT avg(col1) from df")
sprintf("%.2f", res)
```
```
[1] "2251799813685248.00"
```

Correct result:
```r
sprintf("%.2f", mean(df$col1))
```
```
[1] "2251799813685248.50"
```

**Comment by jwills** [comment]
Ah, that's a fun one; you can obviously fix it by having the data frame sorted differently (i.e., smallest to largest) but there's got to be a good way to solve this in general; do other databases implement https://en.wikipedia.org/wiki/Kahan_summation_algorithm or some such thing, even at the cost of the extra additions? Or is this the sort of thing that Numpy/R get right and databases like Postgres don't?

**Comment by david-cortes** [comment]
I'm not so sure what other DBs use. From what I've read, at least some of them use pairwise summation (https://en.wikipedia.org/wiki/Pairwise_summation), which is less exact that compensated summation but more exact than a plain sum-and-divide.

According to that wikipedia article, numpy uses the same pairwise summation technique, but I find the codebase hard to navigate so cannot tell for sure it's still in use in 2021.

There's also other more precise methods that can be used - for example:
```c++
double calc_mean(double x[], size_t n)
{
    double out = 0;
    for (size_t ix = 0; ix < n; ix++)
        out += (x[ix] - out) / (double)(ix+1);
    return out;
}
```

Among popular software, I guess R is an outlier as it does it by a compensated summation in long double precision, plus adding the compensated error term divided by the number elements to the results, which is the most accurate method I know of but slower than others.

In any case, I think a compensated summation in regular double precision such as Kahan's or the other examples in wikipedia would be appropriate for `SUM` and `AVG`.

**Comment by hawkfish** [comment]
Pairwise summation would be difficult with our implementation (it essentially turns it into a holistic aggregate - where all data must be stored and read at once) but Kahan should be feasible. The question is simply whether it is worth the computational tradeoff.

The code also has a reference to [this paper](http://ic.ese.upenn.edu/pdf/parallel_fpaccum_tc2016.pdf) algorithm, but that seems like overkill for now.

**Comment by hawkfish** [comment]
I believe we are using Youngs-Cramer for `VAR(_P)`. Unlike PG, however, we do not use it for simple accumulation. Quite apart from the additional computation overhead, it looks to me like PG can fail with overflow of `Sxx` even when `Sx` is fine.

**Comment by orlp** [comment]
I know of a 'fairly expensive' technique that performs summation with perfect accuracy. It involves essentially keeping a separate integer counter for each exponent in the IEEE-754 floating point format. In Python-ish pseudocode:

```python
infinity = 0
aggregates = [0] * 1024  # 64-bit signed ints, 8 KiB aggregate state
for val in values:
    sign, exponent, mantissa = parse_double(val)

    bucket = exponent + EXPONENT_BIAS
    aggregates[bucket] += sign * mantissa

    # This branch is ~1/512.
    if UNLIKELY(abs(aggregates[bucket]) >= 2**62):
        if bucket == 1023:
            return infinity * sign(aggregates[bucket])
        else:
            next_bucket = min(1023, bucket + 62)
            aggregates[next_bucket] += 1

            reduction = 1 << (next_bucket - bucket)
            if aggregates[bucket] > 0:
                aggregates[bucket] -= reduction
            else:
                aggregates[bucket] += reduction


return sum(agg * 2**(exp - EXPONENT_BIAS)
           for exp, agg in enumerate(aggregates))
```

I actually think that in the grand scheme of things this really isn't all that expensive, and being able to guarantee aggregates with perfect accuracy is quite valuable for some applications.

**Comment by Mytherin** [comment]
> I know of a 'fairly expensive' technique that performs summation with perfect accuracy. It involves essentially keeping a separate integer counter for each exponent in the IEEE-754 floating point format. In Python-ish pseudocode:
> 
> ```python
> infinity = 0
> aggregates = [0] * 2048 # 11-bit exponent = 2048 possible exponents, 64-bit signed ints, 16 KiB aggregate state
> for val in values:
>     sign, exponent, mantissa = parse_double(val)
> 
>     bucket = exponent + EXPONENT_BIAS
>     aggregates[bucket] += sign * mantissa
> 
>     # This branch is ~1/512.
>     if UNLIKELY(abs(aggregates[bucket]) >= 2**62):
>         if bucket == 1023:
>             return infinity * sign(aggregates[1023])
>         else:
>             next_bucket = min(1023, bucket + 62)
>             aggregates[next_bucket] += 1
> 
>             reduction = 1 << (next_bucket - bucket)
>             if aggregates[bucket] > 0:
>                 aggregates[bucket] -= reduction
>             else:
>                 aggregates[bucket] += reduction
> 
> 
> return sum(agg * 2**(exp - EXPONENT_BIAS)
>            for exp, agg in enumerate(aggregates))
> ```
> 
> I actually think that in the grand scheme of things this really isn't all that expensive (at least in the number of instructions, 16KiB aggregate state might form cache pressure when doing many aggregates simultaneously), and being able to guarantee aggregates with perfect accuracy is quite valuable for some applications.

Looks quite good, but indeed very heavy on memory usage, which would make this impossible to use in scenarios where e.g. you have many groups (e.g. for 1M groups you are already looking at 15GB of memory usage). Perhaps we could provide this as an alternative aggregate (`accurate_fp_sum` or so).
