### ISSUE TITLE
including file name in the result

### ISSUE THREAD

**Issue by mishaker** [duckdb/duckdb#2303]
I am wondering if there is a way to include the name of the file in the sql query: 

in the following query SOURCE_FILE is the parquet file duckdb is reading.

``` 
SELECT
person_id,
count(*) as nb_events,
SOURCE_FILE
FROM parquet_scan('data/*/*_source.parquet')
GROUP BY person_id, SOURCE_FILE
ORDER BY nb_events DESC
``` 

Thanks

**Comment by samansmink** [comment]
Issue is closed by https://github.com/duckdb/duckdb/pull/4097
