### ISSUE TITLE
Are there any test cases involving `read_csv_auto(...., columns={....`?

### ISSUE THREAD

**Issue by travis-leith** [duckdb/duckdb#2305]
I can't find any, but maybe I am looking in the wrong place.

**Comment by Mytherin** [comment]
I believe there are none, but `COPY tbl FROM 'test.csv'` will do something similar since the columns will be fixed to the columns as specified in the catalog definition of `tbl`. May I ask why you are looking for these particular test cases? Any issues you are encountering here?

**Comment by travis-leith** [comment]
I was originally looking to see how `headers=False` is handled. 
I now know the columns are assigned names as `column0, column1, ....`.
In the process I noticed that there are no test cases covering the manual mapping of columns functionality.
I can probably submit a PR that adds a few this weekend if desired?

**Comment by Mytherin** [comment]
Yes, that would be great! More test cases are always welcome.
