### ISSUE TITLE
[Document] Benchmark not covered in README as well as Makefile

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [duckdb/duckdb#2309]
I see the following in the current `README.md`:
> For development, DuckDB requires [CMake](https://cmake.org), Python3 and a `C++11` compliant compiler. Run `make` in the root directory to compile the sources. For development, use `make debug` to build a non-optimized debug version. You should run `make unit` and `make allunit` to verify that your version works properly after making changes. To test performance, you can run several standard benchmarks from the root directory by executing `./build/release/benchmark/benchmark_runner`.

However, none of `make` + `make debug` + `make allunit` could generate the executable `./build/release/benchmark/benchmark_runner`.

After some random walk in the repo, I found `benchmark/README.md`, which teaches me to get the executable above: 
> BUILD_BENCHMARK=1 BUILD_TPCH=1 make

---

I have two questions:
- why not to add a `.PHONY` target with name `benchmark` in the `Makefile` to set `BUILD_BENCHMARK=1`? Then we can to `make benchmark` to build the benchmark executables.
- the main `README.md` seems updated frequently. The `benchmark/README.md` looks like another old-style without updates. Do we need to sync the writing & formatting style of the `README.md` in the subfolder with the main `README.md`?

**Comment by hannes** [comment]
Would you mind sending a PR that addresses those?
