### ISSUE TITLE
RuntimeError: Not implemented Error: DataType list not supported yet...

### ISSUE THREAD

**Issue by RAbraham** [duckdb/duckdb#2312]
Hi,
How do I use the `LIST` datatype for a column? As mentioned here: https://duckdb.org/docs/sql/data_types/nested.
I'm on `DuckDB 0.2.9`
I have something like this
```
query = """
CREATE TABLE mytable (

    serial_numbers LIST


);
"""

con = duckdb.connect(..)
con.execute(query)

```
I get an error like this:
```
RuntimeError: Not implemented Error: DataType list not supported yet...

```
It says not supported but is the documentation for nightly builds? I'm on the latest so far(0.2.9). So I just wanted to double check that my syntax is correct.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - DuckDB Version: 0.2.9

**Comment by Alex-Monahan** [comment]
I am not an expert, but in the tests I've seen examples of the format of: datatype [] Ex: INTEGER[]. I don't know if just declaring LIST without a datatype is supported.
Would that syntax work for your case?

**Comment by RAbraham** [comment]
That works! Thanks!
e.g `varchar[]`. 
```
D PRAGMA table_info('mytable')
   ...> ;
┌─────┬────────────────┬───────────────┬─────────┬────────────┬───────┐
│ cid │      name      │     type      │ notnull │ dflt_value │  pk   │
├─────┼────────────────┼───────────────┼─────────┼────────────┼───────┤
│ 0   │ serial_numbers │ LIST<VARCHAR> │ false   │            │ false │
└─────┴────────────────┴───────────────┴─────────┴────────────┴───────┘

```

**Comment by Alex-Monahan** [comment]
I have to say though, serial_numbers as a list of varchars is some naming trickery!! :-)

Happy analyzing!

**Comment by RAbraham** [comment]
haha, the everyday life of a programmer. We practice specs like the whispers game. We built an AI image classification with monitoring, ETL and metrics(i.e. duckdb) based on a verbal spec. The client was being mysterious and probably said that it was a serial_number and we found out later after the data came in that it wasn't :). Now we have `serial_number` over all our code :P

**Comment by Alex-Monahan** [comment]
We have all been there!!! I got a chuckle out of that story... Thanks for sharing!
