### ISSUE TITLE
Incorrect results for TPC-DS SF1

### ISSUE THREAD

**Issue by toschmidt** [duckdb/duckdb#2315]
**What does happen?**
DuckDB produces for some TPC-DS queries (3, 14b, 19, 42, 52, 55, 58, 98) an empty result.
We ran the queries also in PostgreSQL and the correct result should not be empty.

**What should happen?**
DuckDB should produce a (correct) non-empty result. 
We attached the expected result computed with PostgreSQL and the output computed by DuckDB:
[tpcdsSf1.postgrestest.txt](https://github.com/duckdb/duckdb/files/7209641/tpcdsSf1.postgrestest.txt)
[tpcdsSf1.ducktest.txt](https://github.com/duckdb/duckdb/files/7209642/tpcdsSf1.ducktest.txt)

**To Reproduce**
We used our own TPC-DS data generator and the standard queries (write me and I can give you access to them).
We ran DuckDB through the python interface with in-memory mode and loaded the data using copy.

**Environment (please complete the following information):**
 - OS: Ubuntu 21.04
 - DuckDB Version 0.2.10.dev337 (python api)

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Thanks for the report!

Could you provide a link to the TPC-DS data generator that you are using? We are getting the same results as Postgres on these queries using our own data generator (the reference answers we have are obtained from Postgres itself). This seems like a data-dependent issue.

**Comment by Mytherin** [comment]
I have pushed a fix in #2319. The issue was related to primary key constraints, which were not included in our schema but were included in the schema used by your data generator. Could you verify that this PR solves the problem for you?

**Comment by toschmidt** [comment]
Thanks, I will look into it tomorrow.

**Comment by toschmidt** [comment]
@Mytherin the issue is fixed, duckdb computes the correct result for the eight queries.
