### ISSUE TITLE
Left Join Query Doesn't Include All Rows

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#2327]
I have a main table of 10M+ rows which is left joined with four other tables (no where clause). The query result, however, only has 221 rows. Obviously, that is an incorrect result. I can only reproduce it on proprietary data so far. Any ideas what I should look at to trim it down to a smaller example? The sql has the form:

            select t1.*, ... t2.x, ... t3.y ... t4.z ... t5.w
            from table1 t1
            left join table2 t2 on t1.col1 = t2.col1
            left join table3 t3 on t1.col2 = t3.col2 and t1.col3 = t3.col3
            left join table4 t4 on t3.col4 = t4.col4
            left join table5 t5 on t4.col5 = t5.col5

I'm using the duckdb-0.2.10.dev362 pre-release. The input files are csvs, read in as pandas dfs.

**Comment by hawkfish** [comment]
Can you just include the table keys (`colN`) from your example?

**Comment by Mytherin** [comment]
Thanks for the report!

As @hawkfish mentioned, could you perhaps share the table definitions (e.g. by running `DESCRIBE table1`, `DESCRIBE table2`, etc) and the `EXPLAIN` output of the query (e.g. `EXPLAIN SELECT * FROM ...`)? Could you also run `PRAGMA enable_verification`, and then run the query again, to see if there is any error caused by the optimizers?

**Comment by hawkfish** [comment]
`SUMMARIZE` might help too - getting the distribution of column data could be key.

**Comment by scottee** [comment]
@hawkfish These are pandas dfs that I'm passing to duckdb. The index on the dfs is just the row#, so any keys aren't used in the query. If it might change the result, I could try it again after setting the index to the cols used in the joins.

I'll have to change some code to do the explain, pragma, and summarize. I'll post back in a bit...

**Comment by scottee** [comment]
One other item I noticed; don't know if it helps. It's at least a work-around... If I do the left-joins one at a time, the final results are correct.

**Comment by scottee** [comment]
I guess I spoke too soon. The first time I did it, doing the left-joins one at a time worked around the problem. However, I re-ran the work-around on the original dataset that showed the problem and got missing rows on one left join:

            select c.*, t3.colA,
                case when t3.colB is null then 1 else 0 end as colB,
                t3.colC as t3_colC
            from combined_data1 c
            left join table3 t3 on c.colD = t3.colD
                and c.colE = t3.colE

The combined_data1 table has 10M rows and 17 cols. And I double checked that the error is repeatable.

**Comment by hawkfish** [comment]
Can you `SUMMARIZE` `table3` and `combined_data1`? it might be possible to generate a reproducible set of random test data from that information.

**Comment by scottee** [comment]
I corrected the sql above. Below are the summaries:

      combined_data1 summarize:
      ====================
                column_name column_type  \
                       colA     VARCHAR
                       colB     VARCHAR
                       colD     VARCHAR
                       colE      BIGINT
                       colF     VARCHAR
                       colG     VARCHAR
                       colH      BIGINT
                       colI      BIGINT
                       colJ      DOUBLE
                       colK      DOUBLE
                       colL      BIGINT
                       colM      BIGINT
                       colN     VARCHAR
                  timestamp      BIGINT
                   yyyymmdd      BIGINT
                       colP      BIGINT
                       colQ      DOUBLE

                                      min  \
                         1fbl0gkfcue2d802
                         1fbl0gkfcue2d801
                      1000000202347220058
                                        0
        \t\t\t\t\t\tsome huge long string
                      blah blah blah yada
                                        0
                                        4
                                      0.0
                                      0.0
                                        0
                                        0
                                        0
                            1627424051692
                                535410106
                                        0
                                     15.0

                                     max  \
                        1fedclve8tg58800
                        1fedclve7tg58801
                      999999908358388801
                               588755658
                    xblah blah blah yada
                    xblah blah blah yada
                                98511792
                                   59417
                                     1.0
                                     1.0
                                       1
                                       1
                   some huge long string
                           1630389599688
                               536341227
                                       1
                                336680.0

      approx_unique                   avg     count null_percentage
           10210034                   NaN  10296550            0.0%
           10299281                   NaN  10296550            0.0%
           10244779                   NaN  10296550           0.72%
             177212    371929819.96801686  10296550            0.0%
            1125872                   NaN  10296550           0.81%
            1095665                   NaN  10296550           0.81%
             190333     39259.12823693373  10296550            0.0%
              11480     278.0547177452642  10296550            0.0%
                  2    0.1622581840593992  10296550           0.81%
                  2    0.4413479863378308  10296550           0.81%
                  2    0.5546714190675518  10296550            0.0%
                  2     0.438273887855641  10296550            0.0%
            7472054                   NaN  10296550           5.02%
           10178036     1629396288438.586  10296550            0.0%
              33947    536030808.04752874  10296550            0.0%
                  2  0.007187164632813904  10296550            0.0%
              14683    355.68018019384016  10296550           0.72%
      ====================

      table3 summarize
      ====================
             column_name column_type               min                  max  \
                    colA     VARCHAR  1fbl0gkdkuevi800     1fedclvdguaoq800
                    colD      BIGINT     1220347017063  9223370609951035496
                    colE      BIGINT                 0            588755658
                    colC      BIGINT                36               133616
               timestamp      BIGINT     1627424051636        1630389599664
                yyyymmdd      BIGINT          20210727             20210830

      approx_unique                     avg    count null_percentage
            9463409                     NaN  9443156            0.0%
            9446040  4.6102407801278725e+18  9443156            0.0%
             177212      405537498.17566985  9443156            0.0%
              16615       481.4576160766591  9443156            0.0%
            9373197        1629393325328.52  9443156            0.0%
                 35      20210816.591193665  9443156            0.0%
      ====================

**Comment by hawkfish** [comment]
Thanks - this is already helpful.

One interesting thing that might be an issue is that one of the left side join columns (`ColD`) has some `NULL` values but the other one (`ColE`) does not. We may be doing something wrong in that situation.

**Comment by hawkfish** [comment]
OK, I tried creating synthetic data with the same statistics, but it didn't reproduce the problem. Is it possible to get copies of the tables with just the join keys (`ColD` and `ColE`)?

**Comment by hawkfish** [comment]
@scottee After taking another look, I'm having trouble generating reasonable data for `combined_data1.ColD` because it is a `VARCHAR` for some reason and the min/max are not numeric min and max. Can you give me the output of

```sql
SELECT min(ColD::BIGINT), max(ColD::BIGINT), avg(ColD::BIGINT) FROM combined_data1
```
