### ISSUE TITLE
Support for Elixir

### ISSUE THREAD

**Issue by fire** [duckdb/duckdb#2333]
**What does happen?**
Wanted to check if anyone was working on an Elixir Ecto library for duckdb.

**What should happen?**
When I load the hexpm based ecto integration for duckdb it should function with no fuss.

**To Reproduce**
???

**Environment (please complete the following information):**
Thinking in my head. Targeting windows 10, Linux Ubuntu and Fedora and mac.

**Comment by fire** [comment]
I'm willing to do the work, but doing a shout before I do it.

**Comment by Mytherin** [comment]
I am not aware of anyone doing any work on an Elixir library. Contributions in this area would definitely be appreciated!

**Comment by fire** [comment]
I had troubles, so I'll pause this for now.
