### ISSUE TITLE
Failure importing parquet file with 40,000+ columns

### ISSUE THREAD

**Issue by sahuguet** [duckdb/duckdb#2336]
**What does happen?**
I have a parquet file with 1,032 columns and 44,000 rows (size = 80MB).
When I import it in DuckDB, everything is fine and fast.

My queries are better suited for the transposed data.
I load the data in pandas, apply `transpose` and save it as parquet (size = 208MB).
When I try to import the data in DuckDB, it keeps hanging (I usually stop after a few minutes).

```
BEGIN TRANSACTION;
CREATE TABLE my_table AS SELECT * FROM parquet_scan('parquet_files/my_table.parquet');
COMMIT;
```

**What should happen?**
The parquet file should be loaded.

**To Reproduce**
I cannot share the file, sorry.

**Environment (please complete the following information):**
v0.2.9 1776611ab
OSX 11.6

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
Currently DuckDB will allocate at least `256KB` of space per column during the table creation, which with 44K columns comes down to about 11GB of RAM. Perhaps you are running out of memory because of this?

**Comment by sahuguet** [comment]
I killed the process after 25min.
Looking at the memory usage on my MacBook Pro, it fluctuates around 100MB.
There is no complain from the OS regarding memory.

Is there a way of getting more info from DuckDB as the transaction gets executed?

**Comment by Mytherin** [comment]
The process might just be stuck on reading the Parquet metadata. How long does it take to run a SELECT * FROM … LIMIT 1 query?

**Comment by sahuguet** [comment]
`SELECT * FROM … LIMIT 1` does not return anything after 5min.
Is it because the metadata is incomplete? Is there a way to fix the parquet file?

The CREATE TABLE finally returned after 80+ min with the following error message.
Error: TransactionContext Error: Failed to commit: Out of Memory Error: failed to pin block of size 262144

**Comment by sahuguet** [comment]
`SELECT * FROM parquet_metadata('...')` works fine.
