### ISSUE TITLE
Support Bankers rounding

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2348]
DuckDB's rounding right now rounds tries up. While it's the common rounding method for programming languages, it is not as numerically stable as rounding ties to the next even: https://stackoverflow.com/questions/45223778/is-bankers-rounding-really-more-numerically-stable. It would be great if you could consider changing the default rounding algorithm or adding `round_to_even` as an expression function. Note that R's default rounding is rounding to even. It's also the IEC 60559 standard and [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754#Rounding_rules). https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Round

**Comment by hawkfish** [comment]
Unfortunately, this is not Postgres' behavior, so we would need a separate function here:

```sql
hawkfish=# select i, round(0.5 + i) from generate_series(-2,4) tbl(i);
 i  | round 
----+-------
 -2 |    -2
 -1 |    -1
  0 |     1
  1 |     2
  2 |     3
  3 |     4
  4 |     5
(7 rows)
```

**Comment by hawkfish** [comment]
I think you can create your own pretty easily:

```sql
create function round_even(x, n) AS
	case ((abs(x) * power(10, n+1)) % 10)
	when 5 then round(x/2, n) * 2
	else round(x, n)
	end
```

**Comment by domoritz** [comment]
Apparently, there is an easier version where you divide by two, round, and multiply by two. https://stackoverflow.com/questions/31464146/rounding-to-nearest-even-number-in-c

I think it would be great to have a native expression function in DuckDB.

**Comment by hawkfish** [comment]
That only works for exact values (e.g., `round(1 / 2) * 2 => 0`), which is incorrect.

**Comment by domoritz** [comment]
🤦 ignore me.

**Comment by hawkfish** [comment]
Because `n` has to be a constant, I think the vectorised execution should not be too bad because the `power` function will be subject to constant folding.

I confess I was puzzled that no database I checked has this functionality. After all, databases were originally developed to count money(!)

**Comment by domoritz** [comment]
yet another potential differentiator for DuckDB ;-)

**Comment by Mytherin** [comment]
I have taken the function as proposed by @hawkfish and moved it to the built-in macros (see #2360). If performance requires we could create a dedicated C++ function for this in the future.

**Comment by domoritz** [comment]
Fantastic, thank you!

**Comment by domoritz** [comment]
Injustice noticed that Python 3 defaults to bankers rounding as well. What's the argument for staying consistent with Postgres vs using a better default for analysis?
