### ISSUE TITLE
Low memory environments, `Out of Memory Error`

### ISSUE THREAD

**Issue by pstorozenko** [duckdb/duckdb#2349]
Hello,
I'm trying out your database as a replacement for SQLite in RShiny app.
I use SQLite when I have to work in a memory constrained environments.

While playing around with DuckDB I tried to work on the [wikipedia clickstream dataset](https://dumps.wikimedia.org/other/clickstream/readme.html).
The file I was working on had 1.5GB in tsv on disk, 2.2GB when inserted into DuckDB file on disk, dataframe of 4 columns and over 31 mln rows.

When running the following query:
```sql
SELECT coming_from, article, SUM(n) as count 
FROM clickstream 
WHERE referrer_type LIKE 'link' 
GROUP BY coming_from, article 
ORDER BY count 
DESC LIMIT 20
```
In configuration:
```R
conn <- dbConnect(duckdb::duckdb(), "wikipedia.db", config=list(threads='1', 'max_memory'='2GB'))
dbGetQuery(conn, q1)
```
I got:
```
> dbGetQuery(conn, q1)
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Out of Memory Error: could not allocate block of 262144 bytes
```

I'm curious what is the reason as this dataframe doesn't seem to be super big.
Is it possible to reliably work with DuckDB in environments with even lower amount of memory like around 256 MB max?

I know that the above query doesn't have much sense on this data, but it allowed me to find this case.

**Comment by thomasguo** [comment]
I am not sure, but maybe you could try set max_memory'='0.2GB' ?  That works in my case with similar size of dataset.

**Comment by Mytherin** [comment]
In general DuckDB should be usable under low memory conditions, but the queries you are able to perform might be limited. The system performs processing in a streaming fashion, so the base tables do not need to fit in memory. For simple queries such as ungrouped aggregates this should always work regardless of how much memory you have.

For more complex queries intermediate results might need to fit in memory. For example, if you perform a `GROUP BY` query that has many unique groups, the result might end up being very large, and if the result of the `GROUP BY` does not fit in memory the query might not be able to complete.

Out-of-memory computation is one of our focus points, so we are working on improving this. Happy to have a look at why your query is running out of memory. Which subset of the clickstream data are you using here exactly?

**Comment by pstorozenko** [comment]
Thank you for answering so quickly!

I've used [enwiki-2021-08](https://dumps.wikimedia.org/other/clickstream/2021-08/clickstream-enwiki-2021-08.tsv.gz) dataset and inserted it with:
```R
df <- fread(
  "data/clickstream-enwiki-2021-08.tsv.gz",
  col.names = c("coming_from", "article", "referrer_type", "n"),
)
df[, n:=as.numeric(n)]
conn <- dbConnect(duckdb::duckdb(), "wikipedia.db")
dbWriteTable(conn, "clickstream", df)
```

A similar, following query:
```sql
SELECT article, SUM(n) AS total 
FROM clickstream 
WHERE referrer_type LIKE 'link' 
GROUP BY article 
ORDER BY total DESC 
LIMIT 20
```
runs with 512MB RAM limit, but fails with 256MB.

Don't know if it's important but I've run those queries from python and results where the same.

I'm using:
Ubuntu 20.04.3 LTS x86_64
AMD Ryzen 7 PRO 4750U with Radeon Graphics (16) @ 1.700GHz
32 GB RAM

**Comment by lnkuiper** [comment]
If there are variable-sized types in the data it could be that the Local/GlobalSortState is keeping too many of these pinned in memory (I think these are not flushed at all in the TopN operator - I changed this behaviour in the sorting code a few weeks ago, which sped up the Order operator).

If this is the case, `PRAGMA force_external;` may provide a quick fix for your issue, but we should definitely look into this.

**Comment by groceryheist** [comment]
Seems like `force_external` doesn't exist in 3.3
