### ISSUE TITLE
HTTPFS Extension Not Correctly Built for Python

### ISSUE THREAD

**Issue by swang1001** [duckdb/duckdb#2350]
**What does happen?**
The httpfs extension is not included in the Python build with BUILD_HTTPFS environment specified.

**What should happen?**
The httpfs extension is included in the Python build with BUILD_HTTPFS environment specified.

The fix is very simple. We just need to move the code block from [this](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/setup.py#L105) before [this](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/setup.py#L88).

**Environment (please complete the following information):**
 - OS: Linux
 - DuckDB Version 0.29

**Before submitting**
- [ ] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannes** [comment]
This should be fixed by now
