### ISSUE TITLE
Feature: simdjson functions?

### ISSUE THREAD

**Issue by Antauri** [duckdb/duckdb#2352]
In one of our use-cases we have JSON stored as part of a `data` column in Parquet files. Since simdjson is in the same philosophy of DuckDb's "no dependency" way of doing things, how hard would it be to add a few filtering functions (eg. at_pointer supporting JSON Pointer) as an DuckDb extension/function? https://github.com/simdjson/simdjson

**Comment by hannesmuehleisen** [comment]
JSON support is on our roadmap, see #1939 . I don't think we are going to integrate simdjson though. Could you describe your use case a bit more, what are you doing with those JSON columns? How are they stored in parquet? Strings?

**Comment by Antauri** [comment]
We're using CloudEvents and storing those in Parquets based on the CloudEvents spec. 
The spec has a `data` column and there we store JSONs encoded as Smile (for which libsmile/[unsmile](https://github.com/pierre/libsmile/blob/master/tools/unsmile.c#L76).c could be useful).

Basically the intention is to do stuff similar to this:
`SELECT id, json_pointer (unsmile (data), 'expression') AS what FROM '/somewhere/in/data.parquet' WHERE what = 'something'`

We suggested simdjson.org because of the use of SIMD instructions which is inline with Duck's philosophy + JSONL features (the ::parse_many) + JSON Pointer features (see the docs).

**Comment by hannesmuehleisen** [comment]
Well the explicit SIMD part is not in line with our philosophy. We should probably write a FAQ entry on this.

**Comment by hannesmuehleisen** [comment]
And what is the `json_pointer` function suppose to do there?

**Comment by Antauri** [comment]
Call at_pointer from the simdjson library :) to apply the expression
argument.

**Comment by hannes** [comment]
See #2970
