### ISSUE TITLE
Unexpected error from R client using dbplyr::expand()

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#2362]
**What does happen?**

`dbplyr` expresses the function `tidyr::expand()` as a SQL query (combination of select and join), which executes as expected on an SQLite connection.  But the same query run against a `duckdb` connection throws an unexpected error, as documented here: https://stackoverflow.com/questions/69412085

**What should happen?**
the query on `duckdb` should execute without error, returning the same data frame we see in native `tidyr` or SQLite.

**To Reproduce**
See reprex https://stackoverflow.com/questions/69412085

**Environment (please complete the following information):**
 - OS: Ubuntu
 - DuckDB Version 0.2.9 (R version) and master branch of duckdb

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
So the problem is that this query breaks, correct?

```sql
SELECT type, size FROM (SELECT DISTINCT type FROM fruits) AS LHS LEFT JOIN (SELECT DISTINCT size FROM fruits) AS RHS;
```

It seems to me that this is actually an incorrect query, though. A `JOIN` expression always requires an `ON` clause, except if it is a `CROSS JOIN`. SQLite seems to accept this query and turn it into a `CROSS JOIN` but I'm not sure if that is desirable since it is probably a mistake by the user.

**Comment by cboettig** [comment]
Thanks @Mytherin !  @krlmlr I was wondering if maybe you could share any insights here?  Perhaps `dbplyr::expand()` ought to be explicitly calling a `CROSS JOIN` instead of a `JOIN` then?

**Comment by krlmlr** [comment]
@mgirlich might know better here.

**Comment by mgirlich** [comment]
> Thanks @Mytherin ! @krlmlr I was wondering if maybe you could share any insights here? Perhaps `dbplyr::expand()` ought to be explicitly calling a `CROSS JOIN` instead of a `JOIN` then?

Yes, the intention is actually a `CROSS JOIN`. Thanks for pointing this out and sorry for the confusion. I'll be fixing this in `dbplyr`.

**Comment by mgirlich** [comment]
I created a PR in `dbplyr` that should fix the issue.

**Comment by cboettig** [comment]
Wow, y'all are amazing! Nice teamwork in tracking this down to the right place and fixing it!
I feel very lucky to be part of such a friendly and responsive open source community :smiley_cat: 

(I can confirm that https://github.com/tidyverse/dbplyr/pull/713 fixes the issue for me too).
