### ISSUE TITLE
incomplete Parquet files should be noted

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#2370]
Right now, if I write a DuckDB file, if the program abruptly terminates there is no way for me to know if the file is complete.

I think the ideal behavior ought to be, say my file is output.parquet, it should be... something like the filename with an arbitrary wildcard. For example output.parquet.3424343654646o4590i6ijjngfdjnzxfv45.tmp

This is the only way to know if something is incomplete.

**Comment by hannesmuehleisen** [comment]
You can check if the file ends with `PAR1` which all valid parquet files need to end with. So in R for example, you could have the following function:
````R
is_valid_parquet <- function(f) {
	fh <- file(f, open="rb")
	seek(fh, file.size(f) - 4)
	rawToChar(readBin(fh, "raw", 4)) == "PAR1"
}
````
