### ISSUE TITLE
Version the docs

### ISSUE THREAD

**Issue by maclockard** [duckdb/duckdb#2373]
It appears that when looking at the [docs](https://duckdb.org/docs/) that only the latest version is viewable. It would be really handy to be able to select an older version and view the docs at that point of time!

**Comment by Mytherin** [comment]
The [docs are versioned now](https://duckdb.org/docs/) and include docs going back until 0.2.8. New versions will be added as they are released.

**Comment by maclockard** [comment]
Thank you very much for your work!
