### ISSUE TITLE
Feature: add QUALIFY clause

### ISSUE THREAD

**Issue by ecotner** [duckdb/duckdb#2383]
Hey, love `duckdb`; I use it all the time when data manipulations become too cumbersome for `pandas` and it works like a charm!

So, I recently started using snowflake as a data lake/warehouse/whatever at my job, and it has its own implementation of SQL of course, and one of the features that I have started using all the time is the [QUALIFY clause](https://docs.snowflake.com/en/sql-reference/constructs/qualify.html). It is extremely useful; just today I was able to use it to join two tables on the closest value of table A that didn't exceed a value from table B within a subgroup, e.g.

```sql
SELECT
  A.col1 col1
  ,A.col2 a_col2
  ,B.col2 b_col2
FROM A
INNER JOIN B
  ON A.col1 = B.col1
  AND A.col2 <= B.col2
QUALIFY RANK() OVER(PARTITION BY A.col1 ORDER BY A.col2 DESC) = 1
```

which I think would be equivalent to
```sql
SELECT col1, a_col2, b_col2
FROM (
SELECT
  A.col1
  ,A.col2 a_col2
  ,B.col2 b_col2
  ,RANK() OVER(PARTITION BY A.col1 ORDER BY A.col2 DESC) rank
FROM A
INNER JOIN B
  ON A.col1 = B.col1
  AND A.col2 <= B.col2
)
WHERE rank = 1
```

in this case it saves a small amount of code, but it is broadly applicable and reduces the need for some subqueries. do you think there is any way to add it to `duckdb`?

**Comment by Mytherin** [comment]
I think this is a nice feature, I had not seen it before. I think this is a good suggestion and adding it should definitely be feasible.

**Comment by Alex-Monahan** [comment]
This can be closed now! All we need to do is document it... :-)
