### ISSUE TITLE
How to view index information

### ISSUE THREAD

**Issue by ablack3** [duckdb/duckdb#2414]
Is there a way to view information about indexes in duckdb?

I have tried:
PRAGMA show_tables; 
PRAGMA table_info('tablename');
PRAGMA index_list('tablename');
PRAGMA index_info('tablename');
select * from information_schema.tables;
select * from information_schema.statistics;

Thanks!

**Comment by Mytherin** [comment]
`select * from duckdb_indexes;` should do the trick. It only reports explicitly created indexes right now though (i.e. those created through the `CREATE INDEX` statement, not those created for e.g. primary keys).

**Comment by ablack3** [comment]
Awesome! Thanks!
