### ISSUE TITLE
Feature: add GEO data type

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb#2429]
It seems DuckDB supports all the main data types with the exception of the `GEO` data type. A couple references:

- [Postgres GEO](https://www.postgresql.org/docs/9.5/datatype-geometric.html)
- [MySQL GEO](https://dev.mysql.com/doc/refman/8.0/en/spatial-type-overview.html)
- [MonetDB GEO](https://www.monetdb.org/Documentation/ServerProgramming/ExtendingSQL/GeoSpatial)

It would be great to add support for this data type either directly or through a plugin (though I'm guessing a plugin would need to have access to that data type in storage).

**Comment by david542542** [comment]
@lnkuiper @Mytherin oh cool is this related to this that was just pushed with the `CREATE TYPE` ? Just noticed that from the logs but haven't yet seen it in the docs.

https://github.com/duckdb/duckdb/commit/e1a1bc52a3c712d6dae7402a81d2caa1069234c2

**Comment by mattijn** [comment]
Related: https://github.com/duckdb/duckdb/issues/1149

**Comment by Mytherin** [comment]
The geo type is supported in the spatial extension now
