### ISSUE TITLE
Aggregate function architecture

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#243]
The current implementations of aggregate (and window) functions are all hard-coded using switch statements. This is not extensible and makes it hard to add new aggregates (e.g., `ARRAY_AGG`, `MEDIAN` or future user-defined aggregates).

An aggregate function infrastructure should provide a number of services:

* **Extensibility**. Adding a new aggregate should be similar to adding a new scalar function
* **Sharing**. Algebraic aggregates like `AVG` should be able to request component aggregates such as `SUM` to avoid duplication of effort. Other examples include `VAR` being able to request `FIRST` for numerical stability and holistic aggregates being able to reference `ARRAY_AGG`.
* **Distribution**. Distributive aggregates should be able to be computed in parallel. The code as of this writing seems to have a flag for future use, but there should also be support for holistic aggregates to indicate that they _cannot_ be computed in parallel.
* **Distinctness**. The current implementation had special case code for the `DISTINCT` modifier, when this should be applicable to any aggregate. For some (like `MIN` and `MAX`) this will be a nop and possibly subject to optimisation (probably through the function API) but the distinctness functionality (e.g. `VAR( DISTINCT`) should be made available orthogonally.

I would suggest starting by refactoring the existing switch statements into function objects and then adding functionality from there.  

I am interested in working on this project (and the corresponding work for windowing functions) but I wanted to submit this "manifesto" for discussions before starting work.

**Comment by Mytherin** [comment]
This sounds like a good idea and should lead to cleaner code in general here. The only problems I see is that the current hash-based grouping cannot properly deal with arbitrary aggregates (e.g. median) very well. In order to implement these we will need to implement a different method of computing aggregates, likely by gathering group numbers and counts for groups as a separate step from performing the actual aggregation.

**Comment by hawkfish** [comment]
My initial impression from looking at the code was that it could be adapted to include the existing functionality by replacing the `ExpressionType` arguments with pointers to the function bodies and moving the case bodies into the functions.  Reuse could then be added by ordering function evaluation and adding references to previous payloads. Once reuse is in place, implementing `ARRAY_AGG` and sharing it would provide efficient support for holistic aggregates.  

At least that's how it looked to my cursory first look...

**Comment by hannesmuehleisen** [comment]
This can be closed, yes?

**Comment by hawkfish** [comment]
I think we should break out the algebraic and holistic parts into separate issues?

**Comment by hannesmuehleisen** [comment]
Regarding the holistic aggregates, which functions are there that could potentially need to be supported? `QUANTILE` is one of them, but I would not be opposed to use an approximate online version to compute that. Others?

**Comment by hawkfish** [comment]
Other interesting holistic aggregates include `MODE` and `MAD` ([median absolute deviation](https://en.wikipedia.org/wiki/Median_absolute_deviation)).

**Comment by hannesmuehleisen** [comment]
So I came up with a possible extension for aggregate functions: We are working on supporting a `LIST` type. To construct LISTs, I think an aggregate is appropriate. However, that requires some additional state for the aggregate callbacks, e.g. similar to what exists for scalar function (ExpressionState/BindData). This could either be holistic or chunk-based, in the case of LIST it would only matter per chunk of input.

**Comment by hawkfish** [comment]
@hannesmuehleisen I'm going through my issues and looking for stuff to work on. Do you think this is in a good state to revisit?

**Comment by hannesmuehleisen** [comment]
@hawkfish closing this as I think the overall issue has been resolved
