### ISSUE TITLE
Duckdb segfaults when pandas dataframe contains "categorical" datatype (linux/ubuntu only?)

### ISSUE THREAD

**Issue by ecotner** [duckdb/duckdb#2433]
**What does happen?**
When using pandas dataframes with duckdb, if the dataframe contains a column with a "categorical" data type, duckdb segfaults. This only seems to happen on my linux machine though.

**What should happen?**
A categorical data type is really just an unordered integer (or you could think of it as a string type) with finite cardinality under the hood, so any query involving integers/strings should just work. My temporary workaround has been to cast categoricals to strings and work with them that way.

**To Reproduce**
Here's a minimal example that runs some simple query on a dataframe containing categorical data. But it is only in the final query that the data is actually coerced to the "categorical" data type, which causes it to segfault. The `time.sleep`s are there so you can see the `print()` output, because sometimes the script runs so fast the segfault occurs before the buffer can be flushed to `stdout`.
```python
import time
import pandas as pd
import numpy as np
import duckdb as ddb

n_rows = 10
cols = ["col1", "col2", "col3"]
df = pd.DataFrame(np.random.randint(0, 10, size=(n_rows, len(cols))), np.arange(n_rows), columns=cols)

print("try as integers")
time.sleep(0.1)
ddb.query("SELECT col1, MODE(col2) FROM df GROUP BY col1").to_df()

print("try as strings")
time.sleep(0.1)
for col in cols:
    df[col] = df[col].astype(str)
ddb.query("SELECT col1, MODE(col2) FROM df GROUP BY col1").to_df()
for col in cols:
    df[col] = df[col].astype("string")
ddb.query("SELECT col1, MODE(col2) FROM df GROUP BY col1").to_df()

print("try as objects")
time.sleep(0.1)
for col in cols:
    df[col] = df[col].astype(object)
ddb.query("SELECT col1, MODE(col2) FROM df GROUP BY col1").to_df()

print("try as categorical")
time.sleep(0.1)
for col in cols:
    df[col] = df[col].astype("category")
ddb.query("SELECT col1, MODE(col2) FROM df GROUP BY col1").to_df()

print("SUCCESS!!")
```
When I run this script on my ubuntu machine, it segfaults, but when I run it on my mac it completes just fine.

**Environment (please complete the following information):**
OS:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
DuckDB version: 0.3.0

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
This should be fixed now, feel free to re-open if the issue persists.
