### ISSUE TITLE
Properly Handle Object Types On Dataframes

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#2450]
Pandas df columns can be of Object Types, in those cases we generally treat them as strings and transform those that are not strings to strings during the scan (which requires a GIL lock).

It seems to be quite common that df columns are of object types even when the entirety of the underlying data is of one type (e.g., all date values as in issue #2273)

Besides losing efficiency due to possible data conversion, it also makes us unable to round-trip dataframes (#2443).

I think we should add an option for the user to set the types of object columns, and throw a warning that they will all be transformed to strings, which will cause loss of type info and that scans might not be fully parallelizable.

Regarding the scans not being fully parallel, another option would be to apply this conversion to string in the binding phase where we already hold the lock anyway, at the cost of possibly making it slow.

(Another possibility is to scan the data twice to try to determine the type, as arrow does.)

**Comment by akdor1154** [comment]
Maybe relevant: pd has its own infer_objects method. Maybe a warning and pointer for users to use that could go a long way?

**Comment by pdet** [comment]
@akdor1154 thanks for sharing it, I was not aware of that. So it basically guarantees all tuples are from the same data type? Does it also handle nested data structures? (e.g., lists of maps or something in that direction like in #2499). If yes, I think throwing a warning is a great solution.

**Comment by akdor1154** [comment]
No, nothing like that, I think the idea is more to normalize object types to pandas types where possible (e.g. column of numbers, or dates, or ints with NA, etc). So not exactly the same, but maybe a subset of what you're needing to do here?

**Comment by Mytherin** [comment]
@Tishj is working on implementing this now.

After some discussion we think the best course of action is to integrate this into the `DataFrame` scan by default, but limit the number of values sampled to determine the logical type to a low value (e.g. max 100 values or so). The number of values sampled would be a parameter that sits in the Python connection.

This way it will mostly work out-of-the-box without having a high single-threaded penalty in the general case, with users being able to configure the sampling amount in case they run into problems in rare edge-cases.

**Comment by Mause** [comment]
@Tishj this is implemented now right?

**Comment by Tishj** [comment]
> @Tishj this is implemented now right?

Yes that's implemented now :)

**Comment by refeed** [comment]
Hi there, is this fixed? I still can reproduce this [issue](https://github.com/duckdb/duckdb/issues/3393) -- the list is still converted to strings

**Comment by Mytherin** [comment]
Are you using the latest version of DuckDB? That issue does not reproduce for me anymore:

```py
>>> import pandas as pd
>>> import numpy as np
>>> import duckdb
>>> conn = duckdb.connect(database=':memory:', read_only=False)
>>> df = pd.DataFrame([{'w': 'two', 'a': np.array([1,2,3])}, {'w': 'four', 'a': np.array([4,5,6])}])
>>> df
      w          a
0   two  [1, 2, 3]
1  four  [4, 5, 6]
>>> df.iloc[0]['a']
array([1, 2, 3])
>>> conn.register('d', df)
<duckdb.duckdb.DuckDBPyConnection object at 0x105521430>
>>> conn.execute("select * from d where len(a)>0")
<duckdb.duckdb.DuckDBPyConnection object at 0x105521430>
>>> x = conn.fetchdf()
>>> x
      w          a
0   two  [1, 2, 3]
1  four  [4, 5, 6]
>>> x.iloc[0]['a']
array([1, 2, 3])

```
