### ISSUE TITLE
Should `Date` types roundtrip to parquet?

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#2454]
**What does happen?**
When saving a Date to parquet, it looks like it's being stored as a datetime instead of a Date. I looked through the documentation and didn't see anything that mentioned this was intentional, but it may be. 

**What should happen?**
Store Dates as Dates 

**To Reproduce**
```r
library(duckdb)
#> Loading required package: DBI

con <- dbConnect(duckdb())

df <- data.frame(date = Sys.Date())

dbWriteTable(con, "df", df)
dbExecute(con, "COPY (SELECT * FROM df) TO 'df.parquet' (FORMAT 'parquet');")
#> [1] 1

df_rt <- dbGetQuery(con, "SELECT * FROM parquet_scan('df.parquet')")

waldo::compare(df, df_rt)
#> `class(old$date)`: "Date"            
#> `class(new$date)`: "POSIXct" "POSIXt"
#> 
#> `attr(old$date, 'tzone')` is absent
#> `attr(new$date, 'tzone')` is a character vector ('UTC')
#> 
#> `old$date`:      18919
#> `new$date`: 1634601600
```

**Environment (please complete the following information):**
 - OS: macOS 11.6
 - DuckDB Version: install from `master` branch

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
The issue here is that the DuckDB Parquet writer does not yet emit Parquet logical types (https://github.com/apache/parquet-format/blob/master/LogicalTypes.md), but it should do that.
