### ISSUE TITLE
Java API to access parquet from AWS S3

### ISSUE THREAD

**Issue by VarunUmesh** [duckdb/duckdb#2464]
I was looking at the below example :
https://github.com/duckdb/duckdb/blob/6c7c9805fdf1604039ebed47d233ea55cabb4b2c/test/sql/copy/parquet/test_parquet_remote.test#L83

and I wanted to to do the same using the Java SDK. Could anyone let me know if this is possible? If so, could you please point me to an example code (or documentation) of how this can be achieved?

**Comment by novotmike** [comment]
Hi, is there any update on this? Would be nice to be able to query S3 directly from java. So far I have not found any way to do this.

**Comment by Mytherin** [comment]
You should be able to use the extensions interface to install and use the `HTTPFS` extension:

```sql
INSTALL 'httpfs';
LOAD 'httpfs';
```
