### ISSUE TITLE
Python: In-memory duckdb keep increasing indefinitely

### ISSUE THREAD

**Issue by lamkenn** [duckdb/duckdb#2471]
#### What happens?
I run a in-memory duckdb python (initialise it with a table of 200K records, memory~250MB after inserting those, id column as the primary key) and the process subscribe to a stream of update (pandas dataframe) which keep updating the table by **cursor.executemany("UPDATE TABLE set field1 = ?, field2= ? where id = ?", df.to_records())** for 500 records every second.

However, the memory of the python program keep increasing even there is no new records inserted ( I keep reusing the cursor for the updates)

If i comment out the **cursor.executemany** statement and just print out the dataframe. The memory doesn't increase while getting the update from the data stream.

Therefore, I am quite sure the memory increment is due to the update statement. I also set the memory limit by _PRAGMA memory_limit='1GB';_

Moreover, I got segmentation fault if i try to run a update-select (update a big table with 20k records from a table with 500 records) statement . If i just have say 5k records in that big table , then it runs fine.

#### To Reproduce
I will try to create a sample program later. But for now, wondering if I am doing anything wrong with the in-memory database.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: duckdb-0.3.0
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by lamkenn** [comment]
Hi. I found that there are different behavior for 

```
duckdb.connect(database=':memory', read_only=False)
```
vs
```
duckdb.connect()
```

the 1st one caused me segmentation fault during UPDATE executemany on a large table.

What is the difference between the two ?

Thanks

**Comment by Mytherin** [comment]
In the first one you are creating an on-disk database called `:memory`. There is a missing colon in the end. The correct syntax is `:memory:` for creating an in-memory database.

Could you create a reproducible example of the segmentation fault?

**Comment by lamkenn** [comment]
Here is the reproducible example:


```
import duckdb
import pandas as pd
# import pyarrow as pa

import faulthandler
faulthandler.enable()

print('Start')
conn: duckdb.DuckDBPyConnection = duckdb.connect()
cursor = conn.cursor()
data = pd.read_csv('data.csv')

conn.execute("create table test_table (isin VARCHAR(12), value VARCHAR(1))")
# arrow_table = pa.Table.from_pydict(data)
# cursor.register_arrow(f'test_table_view', arrow_table)

cursor.register('test_table_view', data)
cursor.execute("insert into test_table SELECT * FROM test_table_view")
cursor.execute("UPDATE test_table set value = tdv.value FROM test_table_view tdv where tdv.isin = test_table.isin")

# for i in range(1000):
#     cursor.execute("UPDATE test_table set value = tdv.value FROM test_table_view tdv where tdv.isin = test_table.isin")

# Not able to reach this statement
cursor.close()
conn.close()
print('End')

```


[data.csv](https://github.com/duckdb/duckdb/files/7504128/data.csv)

I noticed that the VARCHAR/TEXT column type is the cause of the segmentation fault. 
Eg. if you change the type to eg. INTEGER, it runs fine.

**Comment by Mytherin** [comment]
Thanks for the update! I can indeed reproduce the problem here. I will have a look.
