### ISSUE TITLE
View or Table Creation Runtime Error

### ISSUE THREAD

**Issue by shauryauppal** [duckdb/duckdb#2479]
#### What happens?
Facing runtime error: "RuntimeError: Parser Error: Expected a single SELECT statement"

It is clearly visible in the screenshot below that there is only one SELECT statement in the query then why is this error showing up. I am on duckdb 0.3.0

![Screenshot 2021-10-23 at 11 41 05 PM](https://user-images.githubusercontent.com/20338789/138567183-efeec2e3-da0e-4e0d-aa44-6b167cf83511.png)

#### To Reproduce
Create a Table view T1 then apply some operation on T1 then create a table view of processed_T1 to get the resultant T2 view. 
T2 view over-processed T1 view will fail. 

#### Environment (please complete the following information)
 - OS: Mac
 - DuckDB Version: 0.3.0
 - DuckDB Client: Python

**Comment by l1t1** [comment]
suggest add an ""open a feature request button"" in issue section
