### ISSUE TITLE
Select distinct for dataframe np-arrays of structs has unpredictable UTF-8 parsing issue

### ISSUE THREAD

**Issue by mengyazhu96** [duckdb/duckdb#2499]
#### What happens?
`select distinct` raises a `RuntimeError: String value is not valid UTF8` sometimes when run on a column created from np-arrays of dictionaries. It's very weird, I'm sorry....

#### To Reproduce
```
import duckdb
import pandas as pd
from numpy import array
import random

df = pd.DataFrame([[array([{'a': 0.881040697801939}, {'a': 0.9922600577751953},
               {'a': 0.1589674833259317}, {'a': 0.8928451262745073},
               {'a': 0.07022897889168278}], dtype=object)           ],
       [array([{'a': 0.8759413504156746}, {'a': 0.055784331256246156},
               {'a': 0.8605151517439655}, {'a': 0.40807139339337695},
               {'a': 0.8429048322459952}], dtype=object)              ],
       [array([{'a': 0.9697093934032401}, {'a': 0.9529257667149468},
               {'a': 0.21398182248591713}, {'a': 0.6328512122275955},
               {'a': 0.5146953214092728}], dtype=object)             ]], columns=['col'])

con = duckdb.connect(database=':memory:', read_only=False)
con.register('df', df)

con.execute('select distinct col from df').fetchall()
```

#### Environment (please complete the following information):
 - OS: macOS Big Sur 11.6
 - DuckDB Version: 0.3.1-dev440
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

cc @zenazn

**Comment by Mytherin** [comment]
This should be fixed now, feel free to re-open if the issue persists.
