### ISSUE TITLE
how to show explain query results in ascii mode?

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2507]
#### What happens?

when explain a sql.  
it printed a big table with strange characters. 

#### Environment (please complete the following information):
 - OS: windows 7 Chinese version. 
 - DuckDB Version: 0.30
 - DuckDB Client: CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by l1t1** [comment]
I tried to set . mode table, nothing changed
![2021-11-01_132624](https://user-images.githubusercontent.com/23301704/139625855-bf6449e8-28b7-48f7-8b18-f4a37a348380.png)

**Comment by Mytherin** [comment]
There is no option to change this currently, but indeed this should be added.

**Comment by l1t1** [comment]
I copy and paste the results of explain, convert its charset from UTF8 to ASCII, it shows the lines of box, but still has some '?' character.

**Comment by l1t1** [comment]
thanks.  it fixed the issue. 
```
D:\duckdb>duckdb1125
v0.3.2-dev173 a73d33c14
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select 1 a;
┌───┐
│ a │
├───┤
│ 1 │
└───┘
D explain select 1 a;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘
```
