### ISSUE TITLE
cannot compile under gcc 5.4 on Arm64 linux

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2509]
g++ duckdb.cpp -o ddb -std=c++11
returns error

https://github.com/duckdb/duckdb/releases/download/v0.3.0/libduckdb-src.zip
```
a@a:~/ddb$ g++ --version
g++ (Ubuntu/Linaro 5.4.0-6kord1~16.04.12) 5.4.0 20160609

a@a:~/ddb$  g++ duckdb.h duckdb.cpp -o ddb -std=c++11 -ldl -lm -lpthread
duckdb.h:10:9: warning: #pragma once in main file
 #pragma once
         ^
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/crt1.o：在函数‘_start’中：
(.text+0x30)：对‘main’未定义的引用
collect2: error: ld returned 1 exit status
```

**Comment by l1t1** [comment]
add -shared -fPIC ok.

**Comment by Mytherin** [comment]
The amalgamation contains a library, whereas you are compiling as a program. The compiler is complaining that you are missing a main function. Either add a file that contains a main function, e.g.:

`g++ test.cpp duckdb.cpp -ldl -lm -lpthread -std=c++11 `

test.cpp:
```cpp
int main() {
}
```

Or compile DuckDB as a (shared) library.

**Comment by l1t1** [comment]
I want to compile a CLI with lib under Arm64 Linux, what shall I do?

**Comment by l1t1** [comment]
/storage/emulated/0 $ cd Download/lib*
/storage/emulated/0/Download/libduckdb-src $ time clang duckdb.cpp -shared -fPIC -ldl -lm

real 124.831635
user 119.570282
sys 5.067477
