### ISSUE TITLE
Support for regexp_extract

### ISSUE THREAD

**Issue by asm0dey** [duckdb/duckdb#2523]
Sometimes I need to extract nth appearance of some regexp-matching value. For example, 2nd `\d{4}` in string. In spark I can do it with regexp_extract, but how will I do it in duckdb?

**Comment by Alex-Monahan** [comment]
I would recommend the string_split_regex function (which returns a list), and then just select the nth value of the list with the [n] syntax!

**Comment by asm0dey** [comment]
@Alex-Monahan I thoought about it, but still can,t understand how should I do it. For example, I have string `mycomplex1886string1663' and need to obtain 1663 here. Could you please write example SQL based on `string_split_regex` to perform this task?

**Comment by asm0dey** [comment]
@Alex-Monahan maybe I could, but strings are potentially very complex. We need to split by every non-number symbol and then take nth entrance, but TBH it looks almost unusable

**Comment by asm0dey** [comment]
But obviously, it won't solve the general problem , for example, if I need the second appearance of `[a-d]|[e-m]|[n-z]{11,14}`

**Comment by Alex-Monahan** [comment]
Hmm, well, I am not a regex expert, but maybe you could try another workaround. If you have another example that would help!

How about splitting on the inverse pattern, then grabbing the [n-1] list element, doing an INSTR to find the character position of it, and then a substring to grab what you want?
Select SUBSTR(text_col, INSTR(text_col, regex_list[2]),length(regex_list[2])) from (subquery that returns original text_col and regex_list)

**Comment by Alex-Monahan** [comment]
Ah, that's not quite right. You need to offset by the length and calculate the next length by finding the INSTR of the nth element. 

In any case, does that type of idea work as a workaround?

**Comment by asm0dey** [comment]
OK, let's take a simple example actually. We need to find 5th word in "Romeo and Juliet" longer than 7 symbols. Regexp is quite simple: `[A-Z][a-z]{6,}`. Given your idea with invert regexp we should start by breaking the text into tokens. It will be something like `string_split_regex(text, '[ \n\r.,;-—]')` and then we should somehow search In array, or unnest and filter by length. Both sound tricky and error-prone.

**Comment by Alex-Monahan** [comment]
I don't know C++, so I can't build the general solution for you - I'm just trying to help you in the meantime! Have you also had a look at the Python UDF capability? Maybe that would work well here.

https://github.com/duckdb/duckdb/pull/1569

**Comment by asm0dey** [comment]
@Alex-Monahan yeah, my issue was general feature request, thank yo very much for your help!

**Comment by lnkuiper** [comment]
I've been having a go at this, writing some tests now, hoping to send the PR soon.

**Comment by asm0dey** [comment]
@lnkuiper so cool, thank you!
