### ISSUE TITLE
Support for Parquet 2.0

### ISSUE THREAD

**Issue by gleec14** [duckdb/duckdb#2524]
I am using `parquet-hadoop 1.12.2` to write parquet files with writer version `PARQUET_2.0`. I am able to recover the data using `spark 3.2.0` but when I try to read in the data with `duckdb 0.3.0`, I get this error message: ```java.sql.SQLException: Unsupported page encoding```. This doesn't appear when using writer version `PARQUET_1.0`. Would be helpful to know why this error appears.

**Comment by hannesmuehleisen** [comment]
We have not implemented the new Parquet 2.0 encodings yet. Could you share a file that produces the issue please?
