### ISSUE TITLE
Incorrect WITH RECURSIVE query results in an infinite loop instead of a type error

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#2531]
#### What happens?
An incorrectly formulated `WITH RECURSIVE` query results in an infinite loop when the return values mismatch in the UNION of WITH RECURSIVE (NULL vs. string).

#### What should happen?
Postgres displays a type error with a hint to cast the result to the correct type ([SQL Fiddle](http://sqlfiddle.com/#!15/4e6f3/2)):
> ERROR: recursive query "tag_hierarchy" column 4 has type text in non-recursive term but type character varying overall
> Hint: Cast the output of the non-recursive term to the correct type. Position: 94

#### To Reproduce
Example data and queries are below. To avoid the infinite loop, change `NULL AS target` to `'' AS target` or `NULL::string AS target`.

```sql
CREATE TABLE tag(id int, name string, subclassof int);

INSERT INTO tag VALUES
  (7, 'Music',  9),
  (8, 'Movies', 9),
  (9, 'Art',    NULL)
;

WITH RECURSIVE tag_hierarchy(id, source, path, target) AS (
  SELECT id, name, name AS path, NULL AS target -- this should be '' for correct behaviour
  FROM tag
  WHERE subclassof IS NULL
 
  UNION ALL

  SELECT tag.id, tag.name, tag_hierarchy.path || ' <- ' || tag.name, tag.name AS target
  FROM tag, tag_hierarchy
  WHERE tag.subclassof = tag_hierarchy.id
)
SELECT source, path, target
FROM tag_hierarchy
;
```

The error occurs on `master` - note that DuckDB v0.2.9 works as expected and fails with:
```
Error: Conversion Error: Could not convert string 'Music' to INT32
```

#### Environment
 - OS: Fedora 35
 - DuckDB Version: `v0.3.1-dev511 c0d4ec2d7`
 - DuckDB Client: CLI

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2537.
