### ISSUE TITLE
Enhancement: support all parquet file metadata

### ISSUE THREAD

**Issue by llimllib** [duckdb/duckdb#2534]
Parquet metadata was added in #1905 (per #1899), but it does not seem to include all parquet file metadata.

Here's a python script to generate a parquet file, and then print out its schema metadata:

```python
from datetime import datetime
from pprint import pprint

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

d = {'col1': [1, 2]}
df = pd.DataFrame(data=d)
schema = pa.Schema.from_pandas(df).with_metadata(
    {"updated": datetime.utcnow().isoformat() + "Z"},
)
table = pa.Table.from_pandas(df, schema=schema)
pq.write_table(table, "test.parquet")

t = pq.read_table("test.parquet")
pprint(t.schema.metadata)
```

It outputs:

```
$ python write_parquet_test.py
{b'pandas': b'{"index_columns": [], "column_indexes": [{"name": null, "field_n'
            b'ame": null, "pandas_type": "unicode", "numpy_type": "object", "m'
            b'etadata": {"encoding": "UTF-8"}}], "columns": [{"name": "col1", '
            b'"field_name": "col1", "pandas_type": "int64", "numpy_type": "int'
            b'64", "metadata": null}], "creator": {"library": "pyarrow", "vers'
            b'ion": "6.0.0"}, "pandas_version": "1.3.4"}',
 b'updated': b'2021-11-04T02:58:27.536549Z'}
```

However, when we run `parquet_metadata` and `parquet_schema` against this file, most of that data isn't available:

```
D SELECT * FROM parquet_metadata('test.parquet');
┌──────────────┬──────────────┬────────────────────┬───────────────────────┬─────────────────┬───────────┬─────────────┬────────────┬────────────────┬───────┬───────────┬───────────┬──────────────────┬──────────────────────┬─────────────────┬─────────────────┬─────────────┬──────────────────────────────┬───────────────────┬────────────────────────┬──────────────────┬───────────────────────┬─────────────────────────┐
│  file_name   │ row_group_id │ row_group_num_rows │ row_group_num_columns │ row_group_bytes │ column_id │ file_offset │ num_values │ path_in_schema │ type  │ stats_min │ stats_max │ stats_null_count │ stats_distinct_count │ stats_min_value │ stats_max_value │ compression │          encodings           │ index_page_offset │ dictionary_page_offset │ data_page_offset │ total_compressed_size │ total_uncompressed_size │
├──────────────┼──────────────┼────────────────────┼───────────────────────┼─────────────────┼───────────┼─────────────┼────────────┼────────────────┼───────┼───────────┼───────────┼──────────────────┼──────────────────────┼─────────────────┼─────────────────┼─────────────┼──────────────────────────────┼───────────────────┼────────────────────────┼──────────────────┼───────────────────────┼─────────────────────────┤
│ test.parquet │ 0            │ 2                  │ 1                     │ 100             │ 0         │ 108         │ 2          │ col1           │ INT64 │ 1         │ 2         │ 0                │                      │ 1               │ 2               │ SNAPPY      │ PLAIN_DICTIONARY, PLAIN, RLE │ 0                 │ 4                      │ 36               │ 104                   │ 100                     │
└──────────────┴──────────────┴────────────────────┴───────────────────────┴─────────────────┴───────────┴─────────────┴────────────┴────────────────┴───────┴───────────┴───────────┴──────────────────┴──────────────────────┴─────────────────┴─────────────────┴─────────────┴──────────────────────────────┴───────────────────┴────────────────────────┴──────────────────┴───────────────────────┴─────────────────────────┘
D SELECT * FROM parquet_schema('test.parquet');
┌──────────────┬────────┬─────────┬─────────────┬─────────────────┬──────────────┬────────────────┬───────┬───────────┬──────────┬──────────────┐
│  file_name   │  name  │  type   │ type_length │ repetition_type │ num_children │ converted_type │ scale │ precision │ field_id │ logical_type │
├──────────────┼────────┼─────────┼─────────────┼─────────────────┼──────────────┼────────────────┼───────┼───────────┼──────────┼──────────────┤
│ test.parquet │ schema │ BOOLEAN │ 0           │ REQUIRED        │ 1            │ UTF8           │ 0     │ 0         │ 0        │              │
│ test.parquet │ col1   │ INT64   │ 0           │ OPTIONAL        │ 0            │ UTF8           │ 0     │ 0         │ 0        │              │
└──────────────┴────────┴─────────┴─────────────┴─────────────────┴──────────────┴────────────────┴───────┴───────────┴──────────┴──────────────┘
```

So my request for enhancement would be that all the information printed by pyarrow's `Table.schema.metadata` be available from within duckdb - it would be very convenient for out-of-band information like the file's creation date, a hash of the source file contents, or the git hash of the program that created the parquet file.

**Comment by inakianduaga** [comment]
This would be great, we are currently trying to add documentation of all fields into Apache Superset reading via DuckDB, and the current implementation prevents us from being able to do so

**Comment by greaka** [comment]
Still waiting for this feature and commenting to remove the stale tag.

**Comment by inakianduaga** [comment]
considering it's almost 2 years old, not holding my breath it will ever be implemented :(

**Comment by ejjune** [comment]
Hello,

Will there be any updates regarding this? :(

**Comment by Mytherin** [comment]
As per https://github.com/duckdb/duckdb/pull/9126, you can access the extra key/value information using the `parquet_kv_metadata` function:

```sql
D from parquet_kv_metadata('test.parquet');
┌──────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│     key      │                                                                           value                                                                           │
│     blob     │                                                                           blob                                                                            │
├──────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ updated      │ 2023-11-24T12:43:06.946974Z                                                                                                                               │
│ pandas       │ {\x22index_columns\x22: [], \x22column_indexes\x22: [{\x22name\x22: null, \x22field_name\x22: null, \x22pandas_type\x22: \x22unicode\x22, \x22numpy_typ…  │
│ ARROW:schema │ /////1gCAAAQAAAAAAAKAA4ABgAFAAgACgAAAAABBAAQAAAAAAAKAAwAAAAEAAgACgAAANwBAAAEAAAAAgAAAJgBAAAEAAAAeP7//3gBAAAEAAAAawEAAHsiaW5kZXhfY29sdW1ucyI6IFtdLCAiY29…  │
└──────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by llimllib** [comment]
Thank you so much @Mytherin !

Just to a note for anybody following the issue: the `parquet_kv_metadata` function isn't in 0.9.2, hopefully it will be in a released version soon

**Comment by OneCyrus** [comment]
i guess this covers only the key/value store on the FileMetaTable and not on the ColumnMetaData-Table? Or is there a way to return everything?

![image](https://github.com/duckdb/duckdb/assets/7747800/5f5829c5-92ad-4190-a9aa-897d9c231deb)

https://parquet.apache.org/docs/file-format/metadata/

**Comment by Dino-Burger** [comment]
Isn’t what you want covered by `parquet_metadata`? See [Duckdb metadata page](https://duckdb.org/docs/data/parquet/metadata.html).

**Comment by OneCyrus** [comment]
> Isn’t what you want covered by `parquet_metadata`? See [Duckdb metadata page](https://duckdb.org/docs/data/parquet/metadata.html).

unfortunately that doesn't include the keyvalue metadata

**Comment by Mytherin** [comment]
I've added the column key-value pairs to `parquet_metadata` in #9798

**Comment by OneCyrus** [comment]
Wow, thank you @Mytherin !

**Comment by Mytherin** [comment]
With the inclusion of #9793 and #9798 all Parquet meta-data should now be queryable using the following functions:

|       Function        |         Metadata         |
|-----------------------|--------------------------|
| parquet_file_metadata | Top-Level File Meta Data |
| parquet_metadata      | Row-Group Metadata       |
| parquet_schema        | Schema Metadata          |
| parquet_kv_metadata   | Optional Key-Value Pairs |

**Comment by cugarteblair** [comment]
I really need this feature

**Comment by llimllib** [comment]
@carlopi at least `parquet_kv_metadata` doesn't seem to be; it works for me locally but at https://shell.duckdb.org/, I get:

```
duckdb> select * from parquet_kv_stats('https://llimllib.github.io/nba_data/playerstats.parquet');
Catalog Error: Table Function with name parquet_kv_stats does not exist!
Did you mean "read_csv_auto"?
LINE 1: select * from parquet_kv_stats('https://llimllib.gith...
```

**Comment by cugarteblair** [comment]
It is! I was misinformed.

**Comment by carlopi** [comment]
Great!

**Comment by cugarteblair** [comment]
Although I am trying to read the key_value_metadata in javascript here and I don't see anything but the python below works?

// Method to dump metadata from a Parquet file and extract a specific key-value pair
  async dumpSpecificParquetMetadata(parquetFilePath: string, key: string) {
    const conn = await this._db!.connect();
    try {
        // Use parquet_metadata to get detailed metadata from the Parquet file
        const query = `SELECT key_value_metadata FROM parquet_metadata('${parquetFilePath}') WHERE key_value_metadata IS NOT NULL;`;
        const result = await conn.query(query);
        console.log("Parquet Metadata:", result);
        // Extract key-value metadata
        const metadataArray = result.toArray();
        let foundValue: string | null = null;

        // Iterate over the metadata entries to find the specified key
        for (const row of metadataArray) {
            const metadataMap = row.key_value_metadata;
            for (const [k, v] of Object.entries(metadataMap)) {
                if (k === key) {
                    foundValue = v as string; // Cast to string
                    break;
                }
            }
            if (foundValue) break;
        }

        if (foundValue) {
            console.log(`Metadata value for key "${key}":`, foundValue);
        } else {
            console.log(`Key "${key}" not found in the metadata.`);
        }

        return foundValue;
    } catch (error) {
        console.error('Error dumping Parquet metadata:', error);
        throw error;
    } finally {
        await conn.close();
    }
  }


>>>import pyarrow.parquet as pq
>>>f = pq.ParquetFile("~/Downloads/atl06p_303_2024-10-24_15_48_29_471.parquet")
>>>f.metadata.metadata[b'sliderule']
b'{ "server": { "rqst": {"endpoint": "atl06", "parms": {"region_mask":{"rows":0,"cols":0,"cellsize":0.000000,"latmin":0.000000,"geojson":"","lonmax":0.000000,"latmax":0.000000,"lonmin":0.000000},"read_timeout":600,"environment_version":"v4.8.3-0-g93fc823b","samples":{},"cluster_size_hint":0,"key_space":0,"sliderule_version":"v4.8.3","timeout":600,"rqst_timeout":600,"raster":{"rows":0,"cols":0,"cellsize":0.000000,"latmin":0.000000,"geojson":"","lonmax":0.000000,"latmax":0.000000,"lonmin":0.000000},"poly":[{"lon":-112.081464,"lat":33.470755},{"lon":-112.081464,"lat":33.397632},{"lon":-111.928080,"lat":33.397632},{"lon":-111.928080,"lat":33.470755},{"lon":-112.081464,"lat":33.470755}],"output":{"open_on_complete":false,"with_validation":false,"format":"parquet","with_checksum":false,"asset":"","region":"","path":"atl06p_303_SVR_TMP_2024-10-24_15_48_29_414.parquet","credentials":{},"as_geo":false,"ancillary":[]},"proj":"plate_carree","node_timeout":600,"build_information":"v4.8.3-0-g93fc823b","points_in_polygon":5}}, "environment":"v4.8.3-0-g93fc823b", "version":"v4.8.3", "duration":48267077, "packages":["core", "arrow", "aws", "cre", "geo", "h5", "streaming", "bathy", "gebco", "gedi", "icesat2", "landsat", "opendata", "pgc", "swot", "usgs3dep"], "commit":"v4.8.3-0-g93fc823b", "launch":"2024-10-24T02:24:17Z" }, "recordinfo": { "time": "time", "as_geo": false, "x": "longitude", "y": "latitude" } }'

**Comment by Mytherin** [comment]
You're likely looking for the `parquet_kv_metadata` function, which returns the top-level key-value metadata. `parquet_metadata` only contains row-group level metadata.

**Comment by cugarteblair** [comment]
@Mytherin 
Do you know if there is an example for parsing the results of querying of parquet_kv_metadata?
When I do this I can't see how to read the metadata I'm looking for. The python script works fine so I know it is in the file.

`  async dumpParquetMetadata(parquetFilePath: string) {
    const conn = await this._db!.connect();
    try {
        // Use parquet_metadata function to get detailed metadata from the Parquet file
        const query = `SELECT key,value FROM parquet_kv_metadata('${parquetFilePath}');`;
        const result = await conn.query(query);
        console.log("Parquet KV Metadata:", result);
        // Convert the result to a more readable format
        const metadata = result.toArray();
        console.log("Detailed Parquet Metadata:", metadata);

        return metadata;
    } catch (error) {
        console.error('Error dumping Parquet metadata:', error);
        throw error;
    } finally {
        await conn.close();
    }
  }
`

**Comment by cugarteblair** [comment]
This is what I wound up with:

``` Typescript
  async dumpParquetMetadata(parquetFilePath: string): Promise<string | undefined> {
    const conn = await this._db!.connect();
    try {
        const query = `SELECT key, value FROM parquet_kv_metadata('${parquetFilePath}')`;
        const result = await conn.query(query);

        if(result) {
          
          for (let i = 0; i < result.numRows; i++) {
              // Decode the key from byte array to string
              const kk = result.getChild("key");
              const kv = result.getChild("value");
              if(kk && kv){
                const keyArray = kk.get(i) as Uint8Array;
                const keyString = Array.from(keyArray).map(byte => String.fromCharCode(byte)).join('');
                
                if (keyString === 'sliderule') {
                    // Decode the BLOB value to JSON string
                    const valueArray = kv.get(i) as Uint8Array;
                    const valueString = new TextDecoder().decode(valueArray);
                    
                    console.log("Raw Sliderule Metadata:", valueString);
                    try {
                        const parsedMetadata = JSON.parse(valueString);
                        console.log("Parsed Sliderule Metadata:", parsedMetadata);
                        return valueString;
                    } catch (parseError) {
                        console.error("Error parsing JSON metadata:", parseError);
                        return undefined;
                    }
                } else {
                    console.log("Key is unexpected:", keyString);
                }
              } else {
                console.log("Key or Value is undefined");
              }
          }
        } else {
          console.log("No metadata found for the specified Parquet file.");
        }
        console.log("Sliderule metadata not found.");
        return undefined;
    } catch (error) {
        console.error('Error dumping Parquet metadata:', error);
        throw error;
    } finally {
        await conn.close();
    }
  }
```
