### ISSUE TITLE
how to reduce the memory occupied after big DML?

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2535]
create table t(I int,j int);
insert into the table 100M rows, it cost 2GB memory. 
update the table set a for all rows , the memory it cost doubled. 

if I export database and then import it, memory costs 2GB again.  anyway else to reduce the cost?

**Comment by Mytherin** [comment]
Are you using an in-memory database, or an on-disk database? In-memory databases are not yet checkpointed which means the updates will not be flushed down to the base tables.

**Comment by l1t1** [comment]
I am using an in-memory database. if I switch to on-disk, how to decrease the file size?
