### ISSUE TITLE
read CSV compressed with zstd

### ISSUE THREAD

**Issue by darked89** [duckdb/duckdb#2538]
Hello,

out of curiosity I have tried to read zstd compressed CSV file:

```
D CREATE TABLE test_zst AS SELECT * FROM read_csv('test.csv.zst', AUTO_DETECT=TRUE);
#
fish: “./duckdb” terminated by signal SIGSEGV (Address boundary error)
```

After checking read_csv.cpp I did:

```
CREATE TABLE test_zst AS SELECT * FROM read_csv('test.csv.zst', AUTO_DETECT=TRUE, compression='zstd');
Error: Binder Error: read_csv currently only supports 'gzip' compression.
```
Two enhancement suggestions:
1. checking if the provided input looks like CSV/gzipped CSV to prevent such crashes
2. adding zstd support for reading CSV files (not a high priority I guess)

Hope it helps

DK

**Comment by Mytherin** [comment]
Could you provide the zstd compressed file? In general a segfault should not happen, no matter what input you provide, so that is a bug for sure.

As for zstd support, we could consider adding this as we do ship zstd along with the Parquet reader.

**Comment by darked89** [comment]
Sorry for the delay. Sent by email with 744 bytes test.csv.zst as an attachment.

**Comment by Mytherin** [comment]
Thanks for the data! The crash should be fixed now. I will leave this open with the feature request of adding zstd support to csv files.

**Comment by Mytherin** [comment]
Had a go at implementing this in #2697. Feel free to have a look.
