### ISSUE TITLE
Deadlock when registering and/or selecting from Arrow Table from multiple Python threads

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#2540]
I am doing some testing in Python with inserting into DuckDB from Arrow across multiple threads (to benchmark DuckDB OLTP performance with a queue - my goal is to show that DuckDB can be used in hybrid OLTP/OLAP situations if you add in a queue!). However, registering an Arrow table across multiple threads is causing a deadlock. I am also seeing occasional deadlocks when inserting into a DuckDB table from a registered Arrow table.

I stripped down my benchmarking tester to a minimally reproducible example. Below I have a consistently deadlocking function, a halfway working function that adds a threading lock around the register_arrow function, and a (as far as I can tell) consistently working function with a lock around both the registration and select.  I am seeing similar behavior on 0.3.0 and the current master branch.

Thank you as always! This is non-urgent as I am just tinkering outside of work on this one.

```python
import duckdb
import pandas as pd
import pyarrow as pa
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
import threading


def main():
    queue_tester = QueueTester(2)
    queue_tester.begin_benchmark()
    print('Finished with main()')

class QueueTester:
    def __init__(self,duckdb_insert_thread_count=1):
        self.duckdb_insert_thread_count = duckdb_insert_thread_count
        self.threads = []
        
        self.local_data_dict = {}
        self.insert_lock = threading.Lock()
    
    def begin_benchmark(self):
        print('Begin Benchmark')
        filename = ':memory:'
        duckdb_conn = duckdb.connect(filename)
        duckdb_conn.execute('CREATE TABLE test(i integer)')

        for i in range(0,self.duckdb_insert_thread_count):
            self.threads.append(threading.Thread(target=self.DEADLOCK_register_arrow_and_select, args=(duckdb_conn,),name='duckdb_insert_'+str(i)))
            # self.threads.append(threading.Thread(target=self.HALF_WORKING_register_arrow_and_select, args=(duckdb_conn,),name='duckdb_insert_'+str(i)))
            # self.threads.append(threading.Thread(target=self.WORKING_register_arrow_and_select, args=(duckdb_conn,),name='duckdb_insert_'+str(i)))


        for i in range(0,len(self.threads)):
            self.threads[i].start()
        
        for i in range(0,len(self.threads)):
            self.threads[i].join()
        
        final_output = duckdb_conn.execute("SELECT * from test").fetchdf()

        print('Done with all threads\n',final_output)

    def DEADLOCK_register_arrow_and_select(self,duckdb_conn):
        thread_name = threading.current_thread().getName()
        print('\n'+thread_name+' In register_arrow_and_select')

        self.local_data_dict[thread_name] = pa.Table.from_pydict({'my_column':pa.array([1,2,3,4,5],type=pa.int64())})

        print('\n'+thread_name+' About to register Arrow table')
        duckdb_conn.register_arrow("arrow_table_"+thread_name,self.local_data_dict[thread_name])

        # We never reach this point in either thread
        print('\n'+thread_name+' About to select with DuckDB')
        insert_string = 'select my_column from arrow_table_'+thread_name
        output_df = duckdb_conn.execute(insert_string).fetchdf()
        print('\n'+thread_name+' Select statement completed with output of:\n'+output_df)
    
    def HALF_WORKING_register_arrow_and_select(self,duckdb_conn):
        thread_name = threading.current_thread().getName()
        print('\n'+thread_name+' In register_arrow_and_select')

        self.local_data_dict[thread_name] = pa.Table.from_pydict({'my_column':pa.array([1,2,3,4,5],type=pa.int64())})

        print('\n'+thread_name+' Acquire lock just to register Arrow table')
        with self.insert_lock:
            print('\n'+thread_name+' About to register Arrow table')
            duckdb_conn.register_arrow("arrow_table_"+thread_name,self.local_data_dict[thread_name])

        print('\n'+thread_name+' Release lock')        

        print('\n'+thread_name+' About to select with DuckDB')
        insert_string = 'insert into test select my_column from arrow_table_'+thread_name
        output_df = duckdb_conn.execute(insert_string).fetchdf()
        print('\n'+thread_name+' Select statement completed with output of:\n'+str(output_df))

    def WORKING_register_arrow_and_select(self,duckdb_conn):
        thread_name = threading.current_thread().getName()
        print('\n'+thread_name+' In register_arrow_and_select')

        self.local_data_dict[thread_name] = pa.Table.from_pydict({'my_column':pa.array([1,2,3,4,5],type=pa.int64())})

        print('\n'+thread_name+' Acquire lock just to register Arrow table')
        with self.insert_lock:
            print('\n'+thread_name+' About to register Arrow table')
            duckdb_conn.register_arrow("arrow_table_"+thread_name,self.local_data_dict[thread_name])

                

            print('\n'+thread_name+' About to select with DuckDB')
            insert_string = 'insert into test select my_column from arrow_table_'+thread_name
            output_df = duckdb_conn.execute(insert_string).fetchdf()
            print('\n'+thread_name+' Select statement completed with output of:\n'+str(output_df))  
        print('\n'+thread_name+' Release lock')      

if __name__ == '__main__':
    main()


```

**Comment by pdet** [comment]
Hi Alex! Thanks for the report! I'll have a look this week! :-)

**Comment by pdet** [comment]
Hi @Alex-Monahan can you send me the OS and the lib versions you are using?
I'm trying to reproduce this on my mac, the DEADLOCK_register_arrow_and_select just throws a numpy exception, the other two seem to work just fine.

These GIL-related issues are sometimes a nightmare to reproduce.

**Comment by Alex-Monahan** [comment]
Sorry that I didn't follow the correct format! I couldn't seem to find it.
I'm running Windows 10, Python 3.9.7, DuckDB 0.3.1.dev535 (and 0.3.0), Pandas 1.3.3, 
pyarrow 5.0.0, and numpy 1.20.3. 

Thanks for your help!

**Comment by pdet** [comment]
Hi @Alex-Monahan, thanks for this report, basically what happens is deadlocks caused by a lock in the internal client context of DuckDB and the GIL, so this actually affects a bunch of different python functions (My bad for not testing multithreading in the python side before).
I'm currently working on this, but might take a little while, since I have to check and test many functions.

One thing though, like SQLite we can't have multiple threads using the same connection, it gets messy to support different query results on the same connection, but I've already added an error for that. :-)

**Comment by Alex-Monahan** [comment]
No problem! Thanks for tackling  this - I bet many people will enjoy using multithreading!

One quick question- does this mean that I could create multiple connections to the same DB file? I know multiple connections aren't possible cross-process, but I was trying to push the envelope and use threads instead... 

If not, I can use separate DuckDB's and maybe in the future use an attach keyword or a DuckDB table scan to combine the data.

**Comment by pdet** [comment]
Yes, you should be able to open multiple connections to the same file.

**Comment by omo** [comment]
Unsolicited triage bot here: Apparently this can be closed @pdet .

**Comment by pdet** [comment]
Thanks!  :-)
