### ISSUE TITLE
the doc of CTE with didn't talk about recursive CTE

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2551]
https://duckdb.org/docs/sql/query_syntax/with

but we can do recursive queries indeed.

**Comment by l1t1** [comment]
I made a mistake.  it shows the Syntax. 
you'd better add an example. 
just like this https://sqlite.org/lang_with.html

**Comment by Mytherin** [comment]
Please file issues relating to the documentation [here](https://github.com/duckdb/duckdb-web).

We also accept pull requests. Please feel free to submit a pull request to correct the documentation with your suggestions.
