### ISSUE TITLE
the substr only accept integer, it cannot use instr as argument directly

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2553]
select substr('abc',instr('abc','b'));
Run Time: real 0.000 user 0.000000 sys 0.000000
Error: Binder Error: No function matches the given name and argument types 'substr(VARCHAR, BIGINT)'. You might need to
add explicit type casts.
        Candidate functions:
        substr(VARCHAR, INTEGER, INTEGER) -> VARCHAR
        substr(VARCHAR, INTEGER) -> VARCHAR

LINE 1: select substr('abc',instr('abc','b'));
               ^

**Comment by Alex-Monahan** [comment]
As a workaround  for now, casting the instr to an integer should work:
select substr('abc',instr('abc','b')::int)

**Comment by l1t1** [comment]
thank @Alex-Monahan , I wonder why instr return s bigint and what is the maximum length of a string?

**Comment by l1t1** [comment]
thank @Alex-Monahan , I wonder why instr return s bigint and what is the maximum length of a string?

**Comment by hawkfish** [comment]
Given that `LENGTH` and it's aliases all return `BIGINT` I'd say the problem is that `SUBSTR` only takes `INTEGER` arguments?
