### ISSUE TITLE
a recursive CTE SQL works in Sqlite reports a within error in duckdb

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2554]
WITH RECURSIVE
  input(sud) AS (
    VALUES('53..7....6..195....98....6.8...6...34..8.3..17...2...6.6....28....419..5....8..79')
  ),
  digits(z, lp) AS (
    VALUES('1', 1)
    UNION ALL SELECT
    CAST(lp+1 AS TEXT), lp+1 FROM digits WHERE lp<9
  ),
  x(s, ind) AS (
    SELECT sud, instr(sud, '.') FROM input
    UNION ALL
    SELECT
      substr(s, 1, ind::int-1) || z || substr(s, ind::int+1),
      instr( substr(s, 1, ind::int-1) || z || substr(s, ind::int+1), '.' )
     FROM x, digits AS z
    WHERE ind::int>0
      AND NOT EXISTS (
            SELECT 1
              FROM digits AS lp
             WHERE z.z = substr(s, ((ind::int-1)/9)*9 + lp, 1)
                OR z.z = substr(s, ((ind::int-1)%9) + (lp-1)*9 + 1, 1)
                OR z.z = substr(s, (((ind::int-1)/3) % 3) * 3
                        + ((ind::int-1)/27) * 27 + lp
                        + ((lp-1) / 3) * 6, 1)
         )
  )
SELECT s FROM x WHERE ind::int=0;

Run Time: real 0.000 user 0.000000 sys 0.000000
Error: INTERNAL Error: Recursive CTE detected WITHIN a recursive CTE node

btw: I add ::int to avoid type error.

**Comment by l1t1** [comment]
the Recursive CTE WITHIN a recursive CTE is digits. 
is it a limit of duckdb? 
I rewrite it with select range… of range(1,10), it works. 
the performance of this SQL is worse that of SQLite. (2 seconds vs 1 second).

**Comment by Mytherin** [comment]
Nested recursive CTEs are indeed not yet supported. Happy to review a PR that implements these!

**Comment by l1t1** [comment]
Is the performance question related to duckdb’s parallel execution mechanism?

**Comment by stonebig** [comment]
It works by using the "//" Python divisor 

```
 import duckdb

con = duckdb.connect()
# question is '53..7....6..195....98....6.8...6...34..8.3..17...2...6.6....28....419..5....8..79'
#answer is    '534678912672195348198342567859761423426853791713924856961537284287419635345286179'


sql="""WITH RECURSIVE input(sud) AS (VALUES('53..7....6..195....98....6.8...6...34..8.3..17...2...6.6....28....419..5....8..79'))
, digits(z, lp) AS (VALUES('1', 1) UNION ALL SELECT CAST(lp+1 AS TEXT), lp+1 FROM digits WHERE lp<9)
, x(s, ind) AS (SELECT sud, instr(sud, '.') FROM input
 UNION ALL
 SELECT substr(s, 1, ind-1) || z || substr(s, ind+1), instr( substr(s, 1, ind-1) || z || substr(s, ind+1), '.' ) FROM x
 , digits AS z WHERE ind>0 AND NOT EXISTS (SELECT 1 FROM digits AS lp
  WHERE z.z = substr(s, ((ind-1)//9)*9 + lp, 1) OR z.z = substr(s, ((ind-1)%9) + (lp-1)*9 + 1, 1)
  OR z.z = substr(s, (((ind-1)//3) % 3) * 3 + ((ind-1)//27) * 27 + lp + ((lp-1) // 3) * 6, 1))) SELECT s FROM x WHERE ind=0;
  """

results = duckdb.sql(sql).fetchall()

print(results)

```

**Comment by l1t1** [comment]
thanks.  // works in version 0.8 CLI  too.

**Comment by kryonix** [comment]
The initial issue has been resolved with pr https://github.com/duckdb/duckdb/pull/6838. So this issue should be closed.
