### ISSUE TITLE
Window Functions with Parquet Input Crash

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#2560]
#### What happens?
When I run a window function on a pandas df which was read from a parquet file, it crashes. When I run the same sql on a df read from a csv, it works just fine.

#### To Reproduce
This set of code crashes:
> df = pd.read_parquet("file.parquet")
> sql = """select *, 
>   lead(long1) over (partition by str1, str2, float1, str3, str4 order by long1 asc)
>      as prev_ts
> from df"""
> conn = duckdb.connect(database=':memory:', read_only=False)
> conn.register('df', df)
> conn.execute(sql, {})
> result = conn.fetchdf()

However if you change it to read the equivalent CSV, it doesn't crash:
> df = pd.read_csv("file.csv")

#### Environment (please complete the following information):
 - OS: Ubuntu 10.04
 - DuckDB Version: 0.3.0
 - DuckDB Client: python

#### Before Submitting

* Have you tried this on the latest `master` branch? No, can't get those on Linux.
* Have you tried the steps to reproduce? Yes. 
* Do they include all relevant data and configuration? I can't pass on the data, as it's proprietary.

**Comment by Mytherin** [comment]
Thanks for the report!

That might be related to the data types. Could you tell us what the data types of the data frames are in both scenarios, specifically if there are any differences in data types of the relevant columns? It is also possible that the read_csv reads null values in a different manner.

> Have you tried this on the latest master branch? No, can't get those on Linux.

This should be fixed now, could you check to see you can install the latest master again? There were a number of issues reading certain data types from data frames in 0.3 so it is possible this has been fixed already.

**Comment by scottee** [comment]
On the types, the CSV had diff types in just two cols (csv vs pqt: int32 vs int64 and object (str) vs int64), but neither was involved in the query conditions, just in the "select *".

It looks like it's working with duckdb-0.3.1.dev657. At least it's not crashing immediately like it was before. I'll report back if it crashes in a different place.

**Comment by Mytherin** [comment]
This was likely related to reading object types from the pandas dataframe, which had some issues before that have since been resolved. I will close this issue now, feel free to re-open if you encounter the same problem again.
