### ISSUE TITLE
Support for more intuitive nested field access

### ISSUE THREAD

**Issue by DavidSGK** [duckdb/duckdb#2568]
Hi, thank you for your work!

I have a question/request regarding field access of nested structs. Given a table created such as the following:
```sql
CREATE TABLE x(y ROW(z ROW(w INTEGER)))
```
I found that based on some experimentation, the following queries work:
```sql
[1] SELECT (x.y).z.w FROM x
[2] SELECT (y).z.w FROM x
[3] SELECT x.y['z'].w FROM x
```
While the following do not:
```sql
# Not implemented Error: ColumnRef not implemented!
[4] SELECT x.y.z.w FROM x
[5] SELECT x.y.z FROM x
[6] SELECT (x.y.z).w FROM x
[7] SELECT (x.y.z.w) FROM x
# Binder Error: Referenced table "y" not found!
# Candidate tables: "x"
[8] SELECT y.z FROM x
```
It seems like there are only specific ways of accessing these kinds of nested fields that are supported. From what I can tell, the root-level struct either has to be wrapped in parentheses or the second level field has to be accessed using the subscript operator. Would you be able to provide some background on why the more "intuitive" syntax of `x.y.z.w` is not supported? Are there plans to add support for this syntax in the future?

**Comment by Mytherin** [comment]
Thanks for the report!

> Are there plans to add support for this syntax in the future?

Yes, I have actually been working on adding this.

> Would you be able to provide some background on why the more "intuitive" syntax of x.y.z.w is not supported?

The reason for that is that the dot operator is already used in SQL to denote which table or schema a column comes from, e.g.:

```sql
SELECT table_name.column_name FROM table_name;
SELECT schema_name.table_name.column_name FROM schema_name.table_name;
```

There is a natural ambiguity there, e.g.:

```sql
CREATE SCHEMA t;
CREATE TABLE t.t(t ROW(t ROW(t INTEGER)));

-- what does this refer to, either:
-- schema.table.column
-- table.column.field1
-- column.field1.field2
SELECT t.t.t FROM t.t;
```

Resolving that ambiguity correctly requires some effort inside the binder since you need to figure out which way to resolve it based on the table/column/schema names that exist. Postgres also does not support this syntax for exactly this reason.

**Comment by DavidSGK** [comment]
Amazing, thank you for the clarification! I hadn't even considered the extra level of ambiguity that comes from schemas, only between tables/columns. It's great to know that there may be future support with a clear resolution order of the potential ambiguities. Looking forward to the changes!

**Comment by mbasmanova** [comment]
@Mytherin Do you have an idea about when this might be supported? Is there some other syntax we could use in the meantime?

**Comment by Alex-Monahan** [comment]
In case it's helpful, I think the generic function is STRUCT_EXTRACT(my_struct_column, 'my_key').
[Struct tests](https://github.com/duckdb/duckdb/blob/72c221293350141df5324a2fb59b8780097f01ab/test/sql/types/nested/struct/lineitem_struct.test_slow)

**Comment by Mytherin** [comment]
> @Mytherin Do you have an idea about when this might be supported? Is there some other syntax we could use in the meantime?

Very soon, see #2578.

Currently you could use either STRUCT_EXTRACT as Alex mentioned, square brackets (e.g. `my_struct['my_key']['my_other_key']`) or place every key access between parenthesis (e.g. `((my_struct).my_key).my_other_key`).
