### ISSUE TITLE
0- vs. 1-based indexing

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#2575]
#### What happens?
Arrays use a different index-base (0-based) than Postgres (1-based):

#### To Reproduce
DuckDB:
```sql
D select arr[1] as el from (select array[1,2,3] as arr) sub;
┌────┐
│ el │
├────┤
│ 2  │
└────┘
```

Postgres:
```sql
postgres=# select arr[1] as el from (select array[1,2,3] as arr) sub;
 el 
----
  1
(1 row)
```

We checked what other systems do:

* HyPer/Umbra: 1-based
* BigTable: 0-based
* MySQL: there are not arrays per se, the JSON extractor (`$[...]`) is [0-based](https://dev.mysql.com/doc/refman/5.7/en/json.html)
#### Environment (please complete the following information):
 - OS: n/a
 - DuckDB Version: 0.3.1
 - DuckDB Client: n/a

cc @lnkuiper

**Comment by Mytherin** [comment]
Apparently 1-based indexing is in [the SQL standard](https://crate.io/docs/sql-99/en/latest/chapters/10.html#collection-data-type-s), so we should probably adopt that.

**Comment by lnkuiper** [comment]
We like following Postgres for compatibility, but I have strong feelings about keeping 0-based indexing, because I prefer it.

Whichever we choose some people will dislike it. Python uses 0-based indexing, R uses 1-based. Many of our users will be using DuckDB from either of these languages. We cannot please both.

**Comment by arjenpdevries** [comment]
I agree there's always going to be discussion, but the SQL standard should probably guide the decision here...

**Comment by szarnyasg** [comment]
Note that the indexing of strings is also affected by this decision. In DuckDB, they currently use 0-based indexing like the rest of the arrays:

https://duckdb.org/docs/sql/functions/char

Postgres uses 1-based indexing for strings albeit with a quirky syntax (instead of `[...]`):

```sql
# select substring('hello' from 2 for 3);
 substring 
-----------
 ell
(1 row)
```

**Comment by Mytherin** [comment]
For substring we explicitly use 1-based indexing for compatibility with Postgres. That funky syntax also works in DuckDB :)

**Comment by ChanglinZhou** [comment]
> We like following Postgres for compatibility, but I have strong feelings about keeping 0-based indexing, because I prefer it.
> 
> Whichever we choose some people will dislike it. Python uses 0-based indexing, R uses 1-based. Many of our users will be using DuckDB from either of these languages. We cannot please both.

Although I'm a happy python user, I don't think 0-based sql semantic please me.

**Comment by vmgolovin** [comment]
You guys would be really unrivaled if it was possible to copy-and-paste any moderately complex query from Postgres to DuckDB.

**Comment by hannes** [comment]
> You guys would be really unrivaled if it was possible to copy-and-paste any moderately complex query from Postgres to DuckDB.

Can you give an example of where this breaks for you right now perhaps?

**Comment by vmgolovin** [comment]
There is not a particular query I'am struggling to translate now (obviously, great many ones involving arrays will break). Discarding the context, I personally like the 0-based indexing more too. But for SQL the 1-based is standard and seems to be prevalent.

**Comment by Mytherin** [comment]
We are planning to switch to 1-based indexing in the (near) future as indicated above. This issue is just tracking the problem until the switch happens.

**Comment by Mytherin** [comment]
Thanks to @taniabogatsch this has now been implemented, and DuckDB uses 1-based indexing for arrays as specified in the SQL standard.
