### ISSUE TITLE
DuckDB crash when preparing too long sql

### ISSUE THREAD

**Issue by yxmm-wxe** [duckdb/duckdb#2577]
#### What happens?
When the DuckDB executes a too-long SQL containing more than 3000 CASE WHEN statements, DuckDB will crash.
My Java program process is also finished.

```
Process finished with exit code -1073741571 (0xC00000FD)
```

According to my research, the error code represents that maximum recursion depth exceeded.
In debug mode, I found the issue happened in [DuckDBNative.duckdb_jdbc_prepare](https://github.com/duckdb/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBPreparedStatement.java#L73).

I also asked a question in Discusstions, please refer to [DuckDB crash when preparing too long sql](https://github.com/duckdb/duckdb/discussions/2571).

#### To Reproduce
Execute a too-long SQL containing more than 3000 CASE WHEN statements.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.0
 - DuckDB Client: Java

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by l1t1** [comment]
I represent the issue using following steps. 
create table t as select 10 a ;

create table t1 as select 'select count(case 'a union all select 'when a='||range||' then 1 ' from range(30) union all select 'end) from t';

COPY (SELECT * FROM t1) TO 'd:/csv_t1.csv' WITH (HEADER 0, DELIMITER '|');

.read d:/csv_t1.csv
		

if change 30 to 3000, program crashed

**Comment by l1t1** [comment]
I represent the issue using following steps. 
create table t as select 10 a ;

create table t1 as select 'select count(case 'a union all select 'when a='||range||' then 1 ' from range(30) union all select 'end) from t';

COPY (SELECT * FROM t1) TO 'd:/csv_t1.csv' WITH (HEADER 0, DELIMITER '|');

.read d:/csv_t1.csv
		

if change 30 to 3000, program crashed

**Comment by l1t1** [comment]
if change 30 to 1000, the sql costs 12 seconds.

**Comment by l1t1** [comment]
if change 30 to 1000, the sql costs 12 seconds. 

same 1000 case sql run in sqlite3.36，took 0.02 second.

**Comment by l1t1** [comment]
sqlite 3.36 can run 70000 case sql in 19 seconds.

**Comment by l1t1** [comment]
I tried v0.3.1-dev705
it only shows Error: near line 1: Parser Error
when running my .read d:/csv_t1.csv which has 130000 cases.
sqlite 3.36 can run it in 69s.

**Comment by l1t1** [comment]
I tried v0.3.1-dev705
it only shows Error: near line 1: Parser Error
when running my .read d:/csv_t1.csv which has 130000 cases.
sqlite 3.36 can run it in 69s.

**Comment by l1t1** [comment]
I tried v0.3.1-dev705
it only shows Error: near line 1: Parser Error
when running my .read d:/csv_t1.csv which has 130000 cases.
sqlite 3.36 can run it in 69s.

**Comment by Mytherin** [comment]
You are likely exceeding the maximum length of a SQL statement.

**Comment by l1t1** [comment]
the limit is about 600 KB.
