### ISSUE TITLE
Addition of PERCENT keyword in the LIMIT clause

### ISSUE THREAD

**Issue by chenxi8611** [duckdb/duckdb#2582]
Both Oracle and MsSQL have the ability to limit rows by either the count, or with the `PERCENT` keyword, by the percent of rows returned. 

The syntax for the [`LIMIT`](https://duckdb.org/docs/sql/query_syntax/limit) clause would change to allowing the optional `PERCENT` keyword directly after the count/expr:

LIMIT expr [{PERCENT|%}] OFFSET expr

@Mytherin -- is this something that I could work to implement, or something you want to review with the team?

**Comment by Mytherin** [comment]
I’m fine with you working on this, it seems like a useful feature. I suppose you would just materialize the entire dataset and then scan only the first X% of rows? I don’t see a way of doing this more efficiently in a generic manner at least.

**Comment by chenxi8611** [comment]
Great, I think this is very useful. I would  scan only the first X% of rows. 
Thanks!

**Comment by Mytherin** [comment]
> Great, I think this is very useful. I would scan only the first X% of rows.

Hm, but how would you do that for an arbitrary query? Perhaps you could limit by a COUNT(*) of the same query times the percentage. e.g. rewrite SELECT * FROM tbl LIMIT 5% to SELECT * FROM tbl LIMIT 0.05*(SELECT count(*) from tbl)

**Comment by chenxi8611** [comment]
Good, I would consider this way, but I am now looking to see if I can implement it in another way.
Thanks for your pointers.

**Comment by Mytherin** [comment]
I have given the implementation some more thought.

* The full materialization approach has the benefit that it avoids scanning part of the data source twice, which might be expensive (CSV files, HTTPFS files, etc)
* The subquery rewrite approach has the advantage that the COUNT(*) can often be computed very fast and in parallel, and the full materialization of all rows of all columns is not required. 

For now I think the full materialization approach is fine and should serve as a good base for this functionality.

In the future we might want to consider implementing the subquery rewrite as well, as it will be much more efficient when running on tables we can scan fast (e.g. our own tables, local parquet files). The `COUNT(*)` only needs to scan the metadata of the table to figure out the count and can then scan only the first `0.1%` of the rows, which avoids scanning and materializing the entire table.
