### ISSUE TITLE
Incorrect result with date conversion

### ISSUE THREAD

**Issue by proshkin** [duckdb/duckdb#2588]
#### What happens?
Timestamp field casted to date and varchar constant casted to date not equal in where clause.

#### To Reproduce
create table test as
select '2021-02-04 19:30:00'::timestamp t;

This query returns no result:
select *
from test
where (t::date) = '2021-02-04'::date;

But this one returns correct result:
select *
from test
where (t::date) = '2021-02-04';

#### Environment (please complete the following information):
 - Ubuntu 20.04.3 WSL 2
 - DuckDB Version: 0.3.1-dev623 source_id: cece36693
 - DuckDB Client: Python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2594.
