### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#2589]
It would be helpful to join on something like the following
`
select * from table1 inner join table2
 where table1.element in table2.nested_array

`

Is this currently possible in DuckDB? I don't think so. More broadly, more array manipulations in DuckDB would be amazing. Clickhouse provides a great roadmap for array functions, which are killer.

**Comment by Mytherin** [comment]
You can do this using the `ANY` operator:

```sql
create table tbl1(element integer);
create table tbl2(nested_array integer[]);
insert into tbl1 values (1);
insert into tbl2 values ([1, 2, 3]), ([4, 5]);
select * from tbl1 inner join tbl2 on (tbl1.element = ANY(tbl2.nested_array));
```

**Comment by alanpaulkwan** [comment]
Amazing, didn't notice your reply here.
