### ISSUE TITLE
option to delete overwrite file ONLY IF query completes

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#2590]
If I write the following query:

`
copy (select some_random_variable from table) to 'filethatexists' (format ...)
`

If the query errors out, 'filethatexists' is overwritten and useless, even though it may have had valid data before. I would think the better option is to keep the file, the current behavior of DuckDB is however to overwrite the file.

I imagine that renaming a file shouldn't induce a rewrite, if on the same disk? I don't know actually. Thus I don't see a downside, unless one lacks requisite disk space in which case a second copy would introduce a disk-full error. 

So perhaps it is best to have this behavior come in the form of a flag that can be switch off or on? It would be a great option to have though and I think serve people better.

**Comment by pdet** [comment]
Is this fixed already? I can't reproduce it on my machine.

``` sql
COPY (Select bla from test limit 1 ) to '/Users/holanda/Documents/Projects/duckdb/overwrite.csv';
```

e.g., This query fails and doesn't overwrite the original file.

**Comment by Mytherin** [comment]
This is not fixed no, the problem only occurs when the query errors out after writing has begun but before writing has finished, e.g. the following query will trigger this:

```sql
COPY (SELECT i FROM range(100000) tbl(i) UNION ALL SELECT concat('hello', i)::INT i FROM range(100000) tbl(i)) to 'overwrite.csv';
```
