### ISSUE TITLE
string_agg only returns final row if there is no Group By clause

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#2591]
#### What happens?
Hi folks! Found an odd one...
If a group by clause is not provided, the string_agg function returns only the last row of data rather than all rows concatenated together. 
This issue is not present in 0.3.0, only in 0.3.1-dev678. I have a workaround (just include a dummy column), but wanted to let you know about this one!

#### To Reproduce
This query does not return correctly (returns 'text3'):
```sql
WITH my_data as (
        SELECT 'text1'::varchar(1000) as my_column union all
        SELECT 'text2'::varchar(1000) as my_column union all
        SELECT 'text3'::varchar(1000) as my_column 
    )
        SELECT string_agg(my_column,', ') as my_string_agg 
        FROM my_data
```
This query returns correctly (returns 'text1, text2, text3'):
```sql
WITH my_data as (
        SELECT 1 as dummy,  'text1'::varchar(1000) as my_column union all
        SELECT 1 as dummy,  'text2'::varchar(1000) as my_column union all
        SELECT 1 as dummy,  'text3'::varchar(1000) as my_column 
    )
        SELECT string_agg(my_column,', ') as my_string_agg 
        FROM my_data
        GROUP BY
            dummy
```
#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1-dev678 (issue not present in 0.3.0)
 - DuckDB Client: Node.js

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2593.

**Comment by Alex-Monahan** [comment]
Thank you!! I figured it had something to do with the sweet new union all parallelism!! I will give this a whirl as soon as the Github actions finish!

**Comment by Alex-Monahan** [comment]
Works like a charm! Thank you!
