### ISSUE TITLE
how to set CLI output with following format?(decimal data right align)

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2596]
```
   city      | temp_lo | temp_hi | prcp |    date
---------------+---------+---------+------+------------
 San Francisco |      46 |      50 | 0.25 | 1994-11-27
 San Francisco |      41 |      55 |    0 | 1994-11-29
```
copied from
https://duckdb.org/docs/sql/introduction

**Comment by Mytherin** [comment]
The SQL introduction is adapted from the Postgres tutorial as mentioned in the first paragraph. The SQL output there is from the Postgres shell. DuckDB's shell is adopted from the SQLite shell. See [here](https://www.sqlite.org/cli.html#changing_output_formats) for a list of availble output formats.

**Comment by l1t1** [comment]
thanks.
