### ISSUE TITLE
union all disorders

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2599]
#### What happens?
use 2 union all to link 3 select, the 3rd sometimes come to in front of the 2nd.

#### To Reproduce
v0.3.0 46a0fc50a is right

```
D SELECT 'select count(case 'a union all select 'when a='||range||' then 1 ' from range(2) union all select 'end) from t';
┌────────────────────┐
│         a          │
├────────────────────┤
│ select count(case  │
│ when a=0 then 1    │
│ when a=1 then 1    │
│ end) from t        │
└────────────────────┘
D select * from(SELECT 'select count(case 'a union all select 'when a='||range||' then 1 ' from range(2000) union all select 'end) from t')limit 5;
┌────────────────────┐
│         a          │
├────────────────────┤
│ select count(case  │
│ when a=0 then 1    │
│ when a=1 then 1    │
│ when a=2 then 1    │
│ when a=3 then 1    │
└────────────────────┘
```

v0.3.1-dev705 b77704c86 is right when second select is from range(2)
wrong when range(2000)
```
D SELECT 'select count(case 'a union all select 'when a='||range||' then 1 ' from range(2) union all select 'end) from t';
┌────────────────────┐
│         a          │
├────────────────────┤
│ select count(case  │
│ when a=0 then 1    │
│ when a=1 then 1    │
│ end) from t        │
└────────────────────┘

D select * from(SELECT 'select count(case 'a union all select 'when a='||range||' then 1 ' from range(2000) union all select 'end) from t')limit 5;
┌────────────────────┐
│         a          │
├────────────────────┤
│ select count(case  │
│ end) from t        │
│ when a=0 then 1    │
│ when a=1 then 1    │
│ when a=2 then 1    │
└────────────────────┘
```
		

#### Environment (please complete the following information):
 - DuckDB Version: [e.g. 22]0.3.1-dev 705
 - DuckDB Client: [e.g. Python]

#### Before Submitting

- [x ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
Hello, thanks for your report. the result set order under parallelism is generally not defined. If you need a particular order,  try adding an `ORDER BY`. Does this fix the issue?

Also, we have seen a lot of activity from you in the last weeks. Would you mind telling us a little about yourself? Are you working with DuckDB for your employer, and if so, who do you work for? Keep in mind that this issue tracker is not meant to be a commercial support forum. Thanks!

**Comment by l1t1** [comment]
thanks, I wonder why v0.3 works and 0.3.1 changed the behavior. 
I study duckdb and other databases by myself.

**Comment by l1t1** [comment]
thanks @Mytherin
