### ISSUE TITLE
[Bug] FULL JOIN does produce correct result

### ISSUE THREAD

**Issue by goodwanghan** [duckdb/duckdb#2606]
#### What happens?
```python
import duckdb
import pandas as pd

df1 = pd.DataFrame([
    [0.0, "s7", 0.4],
], columns=["a","b","c"])

df2 = pd.DataFrame([
    [7.0, None, 0.7]
], columns=["a","b","d"])

conn = duckdb.connect()
conn.register("a", df1)
conn.register("b", df2)
result = conn.execute("SELECT a.*, d FROM a FULL JOIN b ON a.a=b.a AND a.b=b.b").fetchdf()
print(result)
```

```
     a    b    c    d
0  0.0   s7  0.4  NaN
1  NaN  NaN  NaN  0.7
```

For record 1, value `a` should be 7.0

#### Environment (please complete the following information):
 - OS: [e.g. iOS] Linux or MaxOS
 - DuckDB Version: 0.3.1.dev711
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Alex-Monahan** [comment]
Howdy!

I tested your query out at this site in Postgres mode, and I believe that DuckDB answer is correct. You are selecting just df1's column a by using a.*, so I believe there should be a null in column a in row 1.

https://sqliteonline.com/

![Screenshot_20211115-220318_Chrome](https://user-images.githubusercontent.com/52226177/141924047-8083f104-850f-4982-91e4-b5c17f7d007b.jpg)

**Comment by goodwanghan** [comment]
You are totally right, this is my silly mistake, this is the right query

```python
import duckdb
import pandas as pd

df1 = pd.DataFrame([
    [0.0, "s7", 0.4],
], columns=["a","b","c"])

df2 = pd.DataFrame([
    [7.0, None, 0.7]
], columns=["a","b","d"])

conn = duckdb.connect()
conn.register("a", df1)
conn.register("b", df2)
result = conn.execute("SELECT COALESCE(a.a,b.a) AS a, a.b, a.c, d FROM a FULL JOIN b ON a.a=b.a AND a.b=b.b").fetchdf()
print(result)
```

**Comment by Mytherin** [comment]
In scenarios where two tables have the same column names it might be more intuitive to join with the `USING` clause, e.g. the following two queries are identical:

```sql
create table df1 as select 0.0 a, 's7' b, 0.4 c;
create table df2 as select 7.0 a, NULL::varchar b, 0.7 d;
SELECT COALESCE(a.a,b.a) AS a, a.b, a.c, d FROM df1 a FULL JOIN df2 b ON a.a=b.a AND a.b=b.b;
┌─────┬──────┬──────┬──────┐
│  a  │  b   │  c   │  d   │
├─────┼──────┼──────┼──────┤
│ 0.0 │ s7   │ 0.4  │ NULL │
│ 7.0 │ NULL │ NULL │ 0.7  │
└─────┴──────┴──────┴──────┘
select * from df1 full join df2 using (a, b);
┌─────┬──────┬──────┬──────┐
│  a  │  b   │  c   │  d   │
├─────┼──────┼──────┼──────┤
│ 0.0 │ s7   │ 0.4  │ NULL │
│ 7.0 │ NULL │ NULL │ 0.7  │
└─────┴──────┴──────┴──────┘
```
