### ISSUE TITLE
Parquet: Out of buffer when querying string column

### ISSUE THREAD

**Issue by aclemmensen** [duckdb/duckdb#2608]
#### What happens?
A 1.7 MB parquet file with a single rowgroup with 90k rows, 9 columns.
When querying the `metric_name` column, which is a string, almost all queries fail with the error below:

```
select metric_name, count(*) from '8343.parquet' group by 1;
Error: Out of buffer
```

Queries that don't involve that column seem to do fine.
The column has many duplicate strings, so it likely compresses really well.
The parquet file was created with Parquet.Net 3.9.1.

#### To Reproduce
Run queries selecting or filtering on the `metric_name` column, such as the example above.
I need a way to provide you guys with the file, though.

#### Environment (please complete the following information):
 - OS: Windows 8 and Ubuntu 16.04
 - DuckDB Version: v0.3.0 46a0fc50a and v0.3.1 88aa81c6b
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

Can you read the file in other Parquet readers (e.g. the Pandas/Arrow Parquet reader)? If they also cannot read the file the file is likely corrupt. 

Otherwise, could you please send us the file so we can test and fix the problem, either here (publicly) or privately to my e-mail address (mark@duckdblabs.com)?

**Comment by Mytherin** [comment]
Trying to read this file in Pandas using pyarrow gives the same error:

```py
>>> import pandas
>>> pandas.read_parquet('issue2608.parquet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/io/parquet.py", line 495, in read_parquet
    return impl.read(
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/io/parquet.py", line 239, in read
    result = self.api.parquet.read_table(
  File "/opt/homebrew/lib/python3.9/site-packages/pyarrow/parquet.py", line 1895, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
  File "/opt/homebrew/lib/python3.9/site-packages/pyarrow/parquet.py", line 1744, in read
    table = self._dataset.to_table(
  File "pyarrow/_dataset.pyx", line 465, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3075, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: Received invalid number of bytes (corrupt data page?)
```

The file appears to be corrupt. Perhaps file an issue with the producer of the Parquet file (Parquet.Net.3.9.1) or try re-exporting the file.

**Comment by aclemmensen** [comment]
Thank you for investigating. I'll try to figure out what went wrong and I'll use Python to verify next time (I hadn't tried that as I'm not using Python on a daily basis). I'll close this issue now.

Thanks again for your help and sorry for the inconvenience.
