### ISSUE TITLE
[Question] I want to select nan in double float columns with duckdb  

### ISSUE THREAD

**Issue by mkrech** [duckdb/duckdb#2610]
#### What happens?
I want to select nan in double float columns with duckdb  
Is this possible and how?

I tried different in python 3.8 / Ubuntu:
df = duckdb.query("SELECT * FROM df_raw WHERE col_name=NaN limit 10").to_df()

**Comment by Mytherin** [comment]
NaN values are converted to NULL values on import, so you should use `col_name IS NULL` to check for equality, e.g.:

```py
import pandas
import math
import duckdb
df = pandas.DataFrame.from_dict({'a': [math.nan, 42], 'b': [1, 2]})

con = duckdb.connect()
print(con.execute('SELECT * FROM df WHERE a IS NULL').df())
#    a  b
#0 NaN  1
```

**Comment by mkrech** [comment]
Thank you it works :)
