### ISSUE TITLE
dbWriteTable cannot cast factor columns in 0.3.1

### ISSUE THREAD

**Issue by lentinj** [duckdb/duckdb#2627]
#### What happens?

Hot on the heels of #2622 (turns out they're more related than I initially thought). Version 0.3.1, trying to cast factor columns as part of ``dbWriteTable`` results in various errors.

This has been picked up by CRAN package checks on the downstream MFDB package: https://cran.r-project.org/web/checks/check_results_mfdb.html

#### To Reproduce

0) Converting character columns to INTEGER works fine:

```
> db <- DBI::dbConnect(duckdb::duckdb())
> DBI::dbWriteTable(db, basename(tempfile("temp_")), data.frame(year = rep("1998", 5)), field.types = c(year = "INTEGER"))
```

1) A factor column can't be cast to INTEGER:

```
> db <- DBI::dbConnect(duckdb::duckdb())
> DBI::dbWriteTable(db, basename(tempfile("temp_")), data.frame(year = as.factor(rep("1998", 5))), field.types = c(year = "INTEGER"))
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: INTERNAL Error: INTERNAL Error: Cast from Enum is not allowed
```

2) Trying to cast a factor to VARCHAR results in a segfault:

```
> db <- DBI::dbConnect(duckdb::duckdb())
> DBI::dbWriteTable(db, basename(tempfile("temp_")), data.frame(year = as.factor(rep("1998", 5))), field.types = c(year = "VARCHAR"))

 *** caught segfault ***
address 0x30, cause 'memory not mapped'
```

Inside dbWriteTable, the code is effectively doing the following:

```
> db <- DBI::dbConnect(duckdb::duckdb())
> cows <- data.frame(name = c('daisy', 'freda'), species = as.factor('Holstein Friesian'))
> duckdb::duckdb_register(db, 'cows', cows)
> DBI::dbSendQuery(db, "SELECT species::INTEGER FROM cows")
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: INTERNAL Error: Cast from Enum is not allowed
```

I'm not sure where to go next. Is ``duckdb_register`` being over-keen by registering the factor as an ENUM (which isn't particularly supported)?

As for MFDB, having a factor year column which is then cast to an integer as per (1) is admittedly asking for trouble. I'll see if I can isolate why it's trying to do that and stop it. And once this is fixed all the tests pass again so I'll stop pestering :)

OTOH, (2) seems like something that one would expect to work.

Cheers!

#### Environment (please complete the following information):
 - OS: ``Debian GNU/Linux 10 (buster)``
 - DuckDB Version: ``0.3.2``
 - DuckDB Client: ``R version 4.1.1 (2021-08-10)``

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
Thanks for reporting, we will look into it. Re 1, @pdet, would we possibly allow casting ENUM to INTEGER?

**Comment by pdet** [comment]
On it.

**Comment by pdet** [comment]
@hannesmuehleisen, I've added #2630 with the enum casts.

 Just to double-check, are you looking into the R segfault?

**Comment by hannesmuehleisen** [comment]
@pdet will have a look

**Comment by hannesmuehleisen** [comment]
We should have fixed the second issue, too. This should be all then?

**Comment by lentinj** [comment]
All looks good from here, once PR #2635 is merged the MFDB integration tests pass without any workarounds.

Thanks for all your help!

**Comment by hannesmuehleisen** [comment]
We just pushed 0.3.1-1 to CRAN which should contain all the fixes

**Comment by lentinj** [comment]
@hannesmuehleisen Everything seems to be passing here, thanks again!
