### ISSUE TITLE
COPY to parquet file with structs

### ISSUE THREAD

**Issue by darthf1** [duckdb/duckdb#2640]
Hi!

Is it possible to implement the export/copy of data with structs to a parquet file?

#### What happens?
When I run:

```
COPY (SELECT * FROM some_query_with_a_struct) TO 'my_parquet_file.parquet' WITH (FORMAT parquet)
```

I get:
```
RuntimeError: Not implemented Error: STRUCT<id: VARCHAR, otherField: VARCHAR, anotherField: VARCHAR>
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.0
 - DuckDB Client: Python

**Comment by OzySky** [comment]
I get that with simple LIST columns as well..
``` 
COPY (SELECT * FROM some_query_with_list) TO 'p.parquet' WITH (FORMAT parquet);
Not implemented Error: LIST<VARCHAR> 
```
Would be very useful for us if this could be implemented!

**Comment by hannesmuehleisen** [comment]
This is not supported yet, sorry. You can try to go through arrow for those types.

**Comment by OzySky** [comment]
Do the node.js bindings support arrow?
