### ISSUE TITLE
write CSV with tab delimiter outputs 'value1\tvalue2'

### ISSUE THREAD

**Issue by darked89** [duckdb/duckdb#2641]
#### What happens?

```
CREATE TABLE people(id INTEGER, name VARCHAR);
INSERT INTO people VALUES (1, 'Mark'), (2, 'Hannes');
COPY (SELECT * FROM people) TO 'test.csv' WITH (HEADER 1, DELIMITER '\t');
```

#### To Reproduce
see above
#### Environment (please complete the following information):
 - OS: Singularity container 
```
 sudo singularity build --sandbox duckdb_0.3.1_python/ docker://python:3.9
```
 - DuckDB Version: 0.3.1 (also 0.2.9)
 - DuckDB Client: CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?** NO

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Detected on  a real data, confirmed with using the code provided above.

**Comment by hmms117** [comment]
Hi,
I am having a similar issue when using the command line tool, when trying to output TSV: 
```
duckdb -csv -separator '\t' :memory: "select 'test1' as col1, 'test2' as col2"
```
Creates: 
```
col1\tcol2
test1\ttest2
```
`duckdb -csv -separator \t :memory: "select 'test1' as col1, 'test2' as col2"` doesnt work either.

Thanks

**Comment by Alex-Monahan** [comment]
Howdy! Which version of DuckDB and which OS are you using, etc?

**Comment by hmms117** [comment]
> Howdy! Which version of DuckDB and which OS are you using, etc?

Tried DuckDB 0.6.1 and 0.6.2dev on Ubuntu 18.04.

**Comment by jflucier** [comment]
For those facing same problem, you need to do this:
/home/def-subilan/programs/duckdb -csv -separator $'\t' :memory: "select 'test1' as col1, 'test2' as col2"
