### ISSUE TITLE
Feature Request: fetchdict

### ISSUE THREAD

**Issue by proshkin** [duckdb/duckdb#2649]
fetchall returns a list of tuples (even when the result set has a single field).
There is no way to return a list of dictionaries where the key is a field name, and value is the field value.
Would be nice to have a fetchdict method, or at least do not wrap the result into a tuple if the result has a single value (this way I can construct a dictionary myself in the query)

**Comment by hannesmuehleisen** [comment]
Happy to review a PR!

**Comment by proshkin** [comment]
Maybe instead of a separate method, even better, would be to add a parameter to fetchone(), and fetchall() that will allow to format the output differently, with the current format as defualt.

**Comment by Alex-Monahan** [comment]
Howdy! Thanks for reaching out!

The current methods follow Python's standard [DB API](https://www.python.org/dev/peps/pep-0249/) , so I don't think that we would want to deviate from that for the existing methods. I assume you're able to manipulate the results into the shape you need and that this feature request is "syntactic sugar" to streamline that process?

**Comment by proshkin** [comment]
Yes, for now, I have to construct a struct with field names/values and then apply a function to each element of the list, to take the first element of the tuple. My result set has complex data types (lists). fetchdf() doesn't allow to export list fields to DataFrame. But I can fetch data to dict using my method, and then convert the result to DataFrame
