### ISSUE TITLE
parquet struct fields with Uppercase chars can't be referenced

### ISSUE THREAD

**Issue by abotsis** [duckdb/duckdb#2652]
#### What happens?
A short, clear and concise description of what the bug is.

Seems like when a parquet file has a struct containing a field name with an uppercase letter, duckdb can't reference it.

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

>>> duckdb.__version__
'0.3.1'
>>> data={'one':[{'Three':3,'four':10}], 'Two':[{'Three':4,'four':10}]}
>>> t=pa.Table.from_pydict(data)
>>> pq.write_table(t, 'data.parquet')
>>> rel=duckdb.connect()
>>> rel.query("select one from 'data.parquet'")
---------------------
-- Expression Tree --
---------------------
Subquery [select one from 'data.parquet']

---------------------
-- Result Columns  --
---------------------
- one (STRUCT<Three: BIGINT, four: BIGINT>)

---------------------
-- Result Preview  --
---------------------
one
STRUCT<Three: BIGINT, four: BIGINT>
[ Rows: 1]
{'Three': 3, 'four': 10}

>>> rel.query("select one['Three'] from 'data.parquet'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not find key in struct
>>> rel.query("select one['Three'] from 'data.parquet'")

#### Environment (please complete the following information):
 - DuckDB Version: [e.g. 22]
 - DuckDB Client: [e.g. Python]

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed in #2659.
