### ISSUE TITLE
DuckDB hash join doesn't scale with number of threads

### ISSUE THREAD

**Issue by save-buffer** [duckdb/duckdb#2653]
#### What happens?
Hi, I wrote a small benchmark to try to see how join scales with number of threads. The results seem to not have any significant effect on speed. 

#### To Reproduce
Here is the source code to the benchmark:
```
import duckdb
import numpy as np
import pyarrow as pa
import time
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

con = duckdb.connect(database=':memory:', read_only=False)

min_i32 = np.iinfo(np.int32).min
max_i32 = np.iinfo(np.int32).max

build = np.random.randint(low=0, high=max_i32, size=32 * 1024, dtype=np.int32)
probe = np.random.randint(low=0, high=max_i32, size=320 * 1024, dtype=np.int32)

build_pa = pa.table({'a' : build})
probe_pa = pa.table({'a' : probe})

build_duck = con.register_arrow('build', build_pa, rows_per_thread=1024)
probe_duck = con.register_arrow('probe', probe_pa, rows_per_thread=1024)

def profile_threads(num_threads):
    con.execute('PRAGMA threads=%d' % num_threads)
    con.execute('select * from build join probe on build.a=probe.a')
    con.execute('select * from build join probe on build.a=probe.a')
 
    nrepeats = 10
    start = time.time_ns()
    for i in range(nrepeats):
        con.execute('select * from build join probe on build.a=probe.a')
    elapsed = time.time_ns() - start
    avg = elapsed / nrepeats
    return avg

avg_arr = []
for threads in range(16):
    avg = profile_threads(threads + 1)
    avg_arr.append(avg)

thread_arr = np.arange(1, 17)
fig, ax = plt.subplots(nrows=1, ncols=1)

ax.plot(thread_arr, avg_arr)
ax.set_title("DuckDB Thread Speed")
ax.set_xlabel("Threads")
ax.set_ylabel("Total ns")
ax.set_ylim(bottom=0)
plt.show()
```

#### Environment (please complete the following information):
 - OS: Void Linux 
 - DuckDB Version: 0.3.1
 - DuckDB Client: Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
- [ ] 
![duckdb_threads_clean](https://user-images.githubusercontent.com/5101039/142941480-cf3918f5-bd4d-4e73-a0ae-76089d93428e.png)

**Comment by Mytherin** [comment]
Result set materialization is not (yet) done in parallel, and in your example queries the bulk of the time will go towards the result set materialization (see #2260). Try pushing an aggregate over the result and you should see a performance speed-up with the number of threads.

**Comment by hannes** [comment]
This should be fixed
