### ISSUE TITLE
The Persistence of Memory

### ISSUE THREAD

**Issue by SartorialOffense** [duckdb/duckdb#2661]
#### What happens?
This is rather odd and I didn't believe it until I had reproduced a number of times.

Once an IO exception like this is thrown:

`Could not read all bytes from file "C:\somefile.duckdb": wanted=262144 read=0`

I get the same error repeatedly for queries against that database table name in that exact file in that exact folder. Makes sense because the file must be corrupted data - right? But that isn't the problem - the file is fine.  What I think are corrupted are the pages the system is keeping in memory or something wacky like that - this is beyond my ken. Here is what **will** fix the error:

1) Rebooting the machine
2) Copying the file to another location on the computer and querying that file.  I do a binary comparison between these files and they are byte for byte identical. Permissions on the locations are identical. This is done in the CLI.
3) `alter table bad_table rename to good_table;` Wow - that is very interesting.

Here is what **will not** fix the problem:

A) Closing the database and reconnecting
B) Exiting the CLI, closing the terminal, opening a new terminal, running a new CLI instance. Making sure there isn't a ghost duckdb.exe hanging around.

All the queries are read only, the data file is created on a separate system and then downloaded. The tables are ~large, 6 numeric columns and ~200E6 rows, there are 2-3 tables of this size per file. The application is in C# and uses DuckDB.NET with the DLL from a fairly recent build of duckdb. Once the table is temporarily corrupted, all additional queries are made using the cli (v0.3.1 88aa81c6b) which is the same rev as the DLL. I have seen this in the past with previous versions as well.

One thing that might be slightly unique: the UI can send queries to the DB before the previous queries have been returned. IOW, the user clicks buttons and the query lookup is done in a background thread and this is queued up every 100 ms. This is done over a single connection created with `duckdb_open` with each thread performing a `duckdb_connect` and `duckdb_disconnect` for the query.

Queries are in this form:
```sql
WITH DATA AS 
(
    SELECT * FROM BIG_DATA WHERE SOMETHING = 1 AND SOMETHING_ELSE >= 1022 AND ONE_MORE_THING IN (1,2,3)
    INTERSECT
    SELECT * FROM BIG_DATA WHERE SOMETHING = 2 AND SOMETHING_ELSE >= 1 AND ONE_MORE_THING IN (1,2,3)
    INTERSECT
    SELECT * FROM BIG_DATA WHERE SOMETHING = 3 AND SOMETHING_ELSE >= 99 AND ONE_MORE_THING IN (10,20,30)
)
SELECT COUNT(*) FROM DATA;
````

No indexes and no PRAGMA's for this read only activity.

I have also seen similar issues with the creation of these files.  This takes a lot longer to test and I am still narrowing it down.  It *might* be fixed by setting threads = 1. I did notice that there was a lot of paging because of the amount of data but fixing this by doing a `duckdb_open`  and `duckdb_close` for every ~10E6 rows didn't help the actual IO error.

#### To Reproduce
Happens sporadically.  I am working on a "hammer program" to reproduce more easily and see if there is anything I can do to keep it from happening.

#### Environment (please complete the following information):
 - OS: Windows 1904 Build 19041.1288 and some similar issues on Windows Server 2019 1809 Build 17763.2300
 - DuckDB Version: v0.3.1 88aa81c6b
 - DuckDB Client: DLL/C# and the CLI

**Comment by hannesmuehleisen** [comment]
This is on Windows, do you work with network drives on this? I know it says C: in your example, but making sure. Is there enough space on the drive?

**Comment by SartorialOffense** [comment]
Sorry, I should have been more specific. The read only errors are on a local SSD. When I see the same error on the system that generates the files, that is on an AWS EC2 instance that uses EBS storage.  While that is technically networked, I don't think that has the issues that a CIFS drive would.

Some more information from overnight testing:

- I setup a UI timer and had it bang on the system with random queries for ~16 hr and the problem didn't repeat. It might have something to do with switching between databases so I will add this to the tests as well as go back to manual testing.

- For the generation of the files if I set threads=1, I don't see the exception even after running it constantly overnight. That is a reasonable fix for me, but I am also going to play with setting the memory_limit instead.

- The generation of files is done by repeatedly inserting data from Parquet data in batches of ~10E6: `INSERT INTO TABLE1 (SELECT * FROM 'file.parquet');`  for a total of ~200E6 rows. I am reliably seeing the issue when inserting a table with a string and several numeric columns. I have seen it fail with all numeric columns but not since I added a second paging file on another disk.

- When the error occurs generating those files, the issue is permanent vs the transient issue with the read only queries.

- The error with file generation is found during a verification step which is just:

`SELECT AVG(NUMERIC_A), AVG(NUMERIC_B), MAX(STRING_A) FROM SOME_TABLE;`

**Comment by SartorialOffense** [comment]
Additional Info:

I cannot reproduce the exception with read only activity even after days of randomly generated queries and switching between data files.

But, I can generate the problem when creating the files (happens on an EC2 instance in AWS). This issue occurs when the available memory is low (should still be plenty of page file left and I don't see out of memory errors).  If I simply increase physical RAM from 32 to 128 GB I can generate files for days without errors. Previously I said that setting threads=1 fixed it but it only made it much less likely. I was able to generate the error after ~24 hr of creating files. Setting the memory_limit doesn't help.

I am wondering if the read only errors I saw were due to damaged files from low memory conditions on the server.

**Comment by Mytherin** [comment]
I think I fixed this in #2691. Could you verify that that fixes the problem?

**Comment by SartorialOffense** [comment]
Here is a CLI script that will show the problems on the 3.2 beta. This should be easier than sending you a 100 MB Parquet file that is inserted over and over again. I do see the error with a lower DB size when I use the DLL via C#, but the errors and behavior seem to be the same. The script mimics the parquet file structure.

[FailureScript.sql.txt](https://github.com/duckdb/duckdb/files/7637411/FailureScript.sql.txt)

If I run this on a machine with 8 GB of physical memory (EC2 c5a.xlarge), it will start throwing the `Could not read all bytes from file "C:\somefile.duckdb": wanted=262144 read=0` error.

These errors continue if I close and reopen the DB file.  Under certain conditions, the error will not propagate to a copy of the database. IOW, if I make a copy, there are no issues with that file and if I reboot the problems go away even with the original. Screenshot of this:

<img width="826" alt="No_Error_After_Copy" src="https://user-images.githubusercontent.com/11902650/144321451-ca891835-b861-4ebf-ab64-4e5c84b322e1.PNG">

Also, I have been able to duplicate the error with read only activity on another box and can confirm that the file isn't changed. The issue occurs when physical memory is on the low side.

**Comment by Mytherin** [comment]
Thanks for the reproducible script! I managed to get this crashing as well on my old Windows laptop, and have pushed a fix in #2725. Please have a look if that fixes the problem.

**Comment by SartorialOffense** [comment]
My CLI tests are all working now in constrained RAM, running overnight
stress testing of the real work.

The only problem I have seen is that the new DLL doesn't open up files
produced with the old one.  I know there was a breaking change from 3.1 =>
3.2 but I am pretty sure these files were created with the 3.2 branch. Same
issue with the CLI. I will double check Friday and see if I made a mistake
here.

**Comment by SartorialOffense** [comment]
Strike that, I think the reason those files don't open is that they are
corrupted by previous crashes in testing. This is the crazy related issue
where the file is unchanged and stays wonky even when replaced by a clean
copy - a reboot is needed to banish the ghost. Will test in the morning.
