### ISSUE TITLE
Epoch function does not return seconds since midnight, but merely seconds.

### ISSUE THREAD

**Issue by rustyconover** [duckdb/duckdb#2663]
#### What happens?

In the documentation on time functions it shows:

select epoch(TIME '14:21:13') returns 51673, but on my version its 13.

#### To Reproduce

select epoch(TIME '14:21:13')

#### Environment (please complete the following information):
 - OS: MacOSX
 - DuckDB Version: 0.3.1 88aa81c6b
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**: Yes
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2693.
