### ISSUE TITLE
Add support for algebraic aggregates

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#267]
The aggregate API rewrite had the unfortunate side-effect of eliminating shared computation for functions like `AVG`. In general, this is a desirable optimisation (Hyper has it!) and one approach would be to add an API to return an expression instead of a set of state management functions. For example:

```sql
AVG( $1 ) := SUM( $1 ) / COUNT( $1 )
```
This would have to be expanded (possibly recursively) at the time of binding using the parser and the parameters would have to be bound to the resulting `Expression`.

**Comment by hannesmuehleisen** [comment]
Could this be something for our macro feature #1129 ?

**Comment by hawkfish** [comment]
Could be. Now that I can do development again on a real machine, I'll have a look.

**Comment by hawkfish** [comment]
The low hanging fruit here looks like `CORR`. `AVG` seems to be complex because of the standard's rules around integer averages.

**Comment by hawkfish** [comment]
There are comments in the tests that look like:
> `# TODO: uncomment when macro parameters are pushed as a projection`
So it looks like there is still some work to do.
