### ISSUE TITLE
How to use java to define UDF?

### ISSUE THREAD

**Issue by bigfacewo** [duckdb/duckdb#2670]
Hello!
I'm a beginner of duckdb
I have a requirement that I can use java to define UDF. I know C + + can. But I'm still not sure how to use it. For example, I use c++ to define UDF separately, and then call it in Java?

Maybe there are other ways. I hope I can get help.
thank you.

**Comment by hannesmuehleisen** [comment]
There is no UDF support yet for Java. You could fork DuckDB, add the functions to the C++ codebase, recompile the JDBC driver and use that though.

**Comment by bigfacewo** [comment]
thank you!
I'll take the time to study how to do it.
In addition, I wonder if there are plans to support Java UDF in the future?

**Comment by hannesmuehleisen** [comment]
We will support this eventually but its not very high on the priority list at the moment. If this is for a commercial purpose we could contract to make this happen sooner.
