### ISSUE TITLE
Very edge case on sequences

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#2678]
#### What happens?
As promised, I will keep posting here the issues I find.
While testing a cleanup for sequences in MonetDB, I got an assertion about integer overflow in DuckDB. Basically I run over the int64 max value and it would be expectable to go back to the minimum value. I know this is an extreme case and you can close the issue if you don't find it relevant. If this should be fixed, we have to be careful to not introduce a new branch in the sequence values retrieval and possibly slow it down.

#### To Reproduce
create sequence ups7 INCREMENT BY 1 MINVALUE 9223372036854775800 MAXVALUE 9223372036854775807 CYCLE;
SELECT nextval('ups7') from generate_series(0,20);
src/function/scalar/sequence/nextval.cpp:47:17: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long int'

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: Tip of master branch
 - DuckDB Client: shell

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! Indeed this is an edge case but undefined behavior should always be fixed.
