### ISSUE TITLE
Create Table on Query having Subquery not possible

### ISSUE THREAD

**Issue by shauryauppal** [duckdb/duckdb#2683]
#### What happens?
Not Able to Create Table over a query that has sub-query
![Screenshot 2021-11-28 at 5 27 21 PM](https://user-images.githubusercontent.com/20338789/143766714-2e11faec-19ef-4940-b353-b2cc48c3e588.png)

**Comment by hannesmuehleisen** [comment]
try conn.execute

**Comment by shauryauppal** [comment]
Can we change the error message? Very confusing

**Comment by shauryauppal** [comment]
Also for understanding can you share when to use con.execute and when con.query?

**Comment by hannesmuehleisen** [comment]
con.query is a shorthand for con.from_query which creates a relational api object from a single sql query. For more traditional query execution you should use con.execute which is compliant with the python db api. I agree the error message could be improved though.
