### ISSUE TITLE
Timestamp Sequence Error Contradicts Documentation

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#2687]
#### What happens?
Contrary to what the documentation states, the `range` and `generate_series` functions do not appear to be compatible with the `TIMESTAMP` data type. 

[Documentation](https://duckdb.org/docs/sql/functions/timestamp):

<html>
<body>

Function | Description | Example
-- | -- | --
generate_series(timestamp, timestamp, interval) | Generate a table of timestamps in the closed range, stepping by the interval | generate_series(TIMESTAMP '2001-04-10', TIMESTAMP '2001-04-11', INTERVAL 30 MINUTE)
range(timestamp, timestamp, interval) | Generate a table of timestamps in the half open range, stepping by the interval | range(TIMESTAMP '2001-04-10', TIMESTAMP '2001-04-11', INTERVAL 30 MINUTE)

</body>
</html>

Result of query `SELECT generate_series(TIMESTAMP '2021-01-01', TIMESTAMP '2021-11-29', INTERVAL 1 DAY)`:

```
RuntimeError: Binder Error: No function matches the given name and argument types 'generate_series(TIMESTAMP, TIMESTAMP, INTERVAL)'. You might need to add explicit type casts.
	Candidate functions:
	generate_series(BIGINT) -> LIST<BIGINT>
	generate_series(BIGINT, BIGINT) -> LIST<BIGINT>
	generate_series(BIGINT, BIGINT, BIGINT) -> LIST<BIGINT>

LINE 1: SELECT generate_series(TIMESTAMP '2021-01-01 0...
```

#### To Reproduce
`SELECT generate_series(TIMESTAMP '2021-01-01', TIMESTAMP '2021-11-29', INTERVAL 1 DAY)`
`SELECT range(TIMESTAMP '2021-01-01', TIMESTAMP '2021-11-29', INTERVAL 1 DAY)`

#### Environment (please complete the following information):
 - OS: [Windows 10]
 - DuckDB Version: [0.3.2-dev273]
 - DuckDB Client: [Python]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
This is a bit confusing since the `range/generate_series` mentioned on that page relate to the table function, e.g.:

```sql
SELECT * FROM generate_series(TIMESTAMP '2021-01-01', TIMESTAMP '2021-11-29', INTERVAL 1 DAY);
```

But indeed the scalar and table functions should have the same semantics.

**Comment by Admolly** [comment]
Ahh now it makes sense.  Thanks for pointing that out!
