### ISSUE TITLE
Expected memory foot print building the R package?

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#2688]
Since the release of 0.3.1-1 to CRAN, we've been experiencing a number of OOMs in our CI when we build DuckDB from source.

One example we have is [one of our as-cran checks](https://github.com/ursacomputing/crossbow/runs/4350024580?check_suite_focus=true), it's a little bit hard to see, but we see that duckdb begins to be installed [`begin installing package ‘duckdb’`](https://github.com/ursacomputing/crossbow/runs/4350024580?check_suite_focus=true#step:6:2203), but it never finishes (there is no corresponding `* DONE (duckdb)`, and looking at other builds in that matrix, just after testthat is installed is when DuckDB gets compiled + installed) and the [build is killed because it has OOMed](https://github.com/ursacomputing/crossbow/runs/4350024580?check_suite_focus=true#step:6:2430). Frustratingly this does not _always_ happen, but it happens frequently enough that we get at least a handful of errors due to this on our set of nightly builds.

Is this expected? Is there anything we can set that would reduce this footprint? The runners have 8gb of RAM, and are set with -j2 for building (since that is the max that CRAN allows). We could try reducing that to -j1 and see if that reduces the memory footprint, though that will increase our build time.

**Comment by Mytherin** [comment]
Hey Jonathan, thanks for the report!

By default DuckDB uses a partial-amalgamation build for the R package, which combines several source files. This considerably speeds up compilation time, but this comes at the expense of additional memory usage for the compiler.

My guess on what happened here is that the new functionality we added pushed the memory usage very close to/over the limit which causes this issue to appear. Strangely enough this doesn't happen on our CI which is running with 7GB, but perhaps we are not running in parallel there.

I have pushed an initial fix [here](https://github.com/Mytherin/duckdb/commit/b611c4c2edcd91a3c7d7794f0fb98d852c36de7d) that should disable these unity builds by default unless the `DUCKDB_BUILD_UNITY` environment variable is set, which should reduce the memory usage of the build significantly.

We will push a new version to CRAN sometime this/next week so this can be included in there. Perhaps for now indeed limit the number of threads to 1 as a temporary work-around?

**Comment by jonkeane** [comment]
Aaaah, that would do it! We were just bit by that [as well and have disabled our unity builds for the same reason](https://github.com/apache/arrow/commit/799945c6d9fcaf73a87755643f3a4ec428060b53).

Thanks for the quick response. I'll try temporarily lowering our parallelism and if that doesn't work, I'll temporarily point to the github repo for installing duckdb.
