### ISSUE TITLE
List Type: RuntimeError: Conversion Error: Unimplemented type for cast (VARCHAR -> LIST<VARCHAR>)

### ISSUE THREAD

**Issue by RAbraham** [duckdb/duckdb#2698]
Hi,
I'm trying to insert into a column with a VARCHAR[] array type. I'm trying to use the dataframe ingest approach but it errors out.
```
duckdb: 0.3.1
OS: Ubuntu 20.04
client: Python

```
The same problem exists on 0.3.2.dev version 

I have a table like this:

```python
query = """
CREATE TABLE mytable (

    serial_numbers VARCHAR[]


);
"""

con = duckdb.connect(..)
con.execute(query)
```

I have a dataframe like this:
```python
   SERIAL_NUMBERS = "serial_numbers"
    r[SERIAL_NUMBERS] = ...
    from pprint import pprint
    pprint(f"SERIAL NUMBERS")
    print(r[SERIAL_NUMBERS].head())
    print(r[SERIAL_NUMBERS].map(lambda k: k[0] if k else "").head())
```
Output of the above numbers:

```shell
'SERIAL NUMBERS'
0    [LFD-1]
1    [LFD-2]
3    [LFD-3]
4    [LMP-4]
5    [LFD-5]
Name: serial_numbers, dtype: object

0    LFD-1
1    LFD-2
3    LFD-4
4    LMP-4
5    LFD-5
```
As you can see in the last print. It's an actual list and I can index into it.

I normally insert data into my tables using a dataframe approach.
```python
def insert_df(self, table, values: pd.DataFrame):
    if values.empty:
        return

    import_table = f"import_{table}"

    try:
        self.con.register(import_table, values)
        columns = values.columns
        query_str = _insert_query_str_df(table, import_table, columns)
        from pprint import pprint
        pprint(f"Insert DF")
        print(f"Query str:{query_str}")
        self.con.execute(query_str)
    except:
        raise
    finally:
        self.con.unregister(import_table)


```
The output of that print statement("Query str:") is:
```

Query str:insert into mytable (serial_numbers) select  serial_numbers from
import_mytable
```

The error I get is:
```shell

Traceback (most recent call last):
...
    db.insert_df(k, a_df)
  File "/home/rajiv/Documents/dev/bht/ml-evaluation/evaluation/services/db_service.py", line 97, in insert_df
    self.con.execute(query_str)

RuntimeError: Conversion Error: Conversion Error: Unimplemented type for cast (VARCHAR -> LIST<VARCHAR>)

**Comment by Mytherin** [comment]
This is related to #2450. The lists are converted to strings, and DuckDB does not support casting strings to complex types (yet).

**Comment by slederman** [comment]
I'm not able to load a CSV file with list objects. Is that the same issue? Is there a workaround? I have hundreds of millions of rows to load and doing that many inserts would be painful.

>>> con.execute("COPY mytable FROM 'output.csv' (HEADER, DELIMITER ',')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Invalid Input Error: Unimplemented type for cast (VARCHAR -> VARCHAR[]) between line 1 and 2 in column 1. Parser options: DELIMITER=',', QUOTE='"' (default), ESCAPE='"' (default), HEADER=1, SAMPLE_SIZE=10240, IGNORE_ERRORS=0, ALL_VARCHAR=0

**Comment by Mytherin** [comment]
That is the same issue indeed. As a work-around you could use `string_split` to convert a varchar to a list, e.g.:

```sql
SELECT string_split(l[2:-1], ',')::INT[] FROM VALUES ('[1,2,3]') t(l);
┌───────────────────────────────────────────────┐
│ CAST(string_split(l[2:-1], ',') AS INTEGER[]) │
├───────────────────────────────────────────────┤
│ [1, 2, 3]                                     │
└───────────────────────────────────────────────┘
```

**Comment by wpdonders** [comment]
Just wanted to drop in and let you know that I also encountered this problem when reading a CSV containing a list. This was from a Postgres dump. My workaround was similar: 

1. Read the column as a `VARCHAR`
2. Alter the table column and apply `string_split`, casting to the required data type

Here's a code snippet with a table called `mytable` and a column called `mycolumn` turned into a  list of `VARCHAR`:
```sql
ALTER TABLE mytable ALTER mycolumn SET DATA TYPE VARCHAR[] USING string_split(mycolumn[2:-1], ',');
```

**Comment by Mytherin** [comment]
This issue should actually be closed as casting from strings to complex types has been implemented:

```sql
D select '[1, 2, 3]'::INT[] AS l;
┌───────────┐
│     l     │
│  int32[]  │
├───────────┤
│ [1, 2, 3] │
└───────────┘
```

The issue you ran into might have been that DuckDB uses a different bracket for arrays than Postgres (`[]` vs `{}`). We could perhaps allow both options but that should be tracked in a separate issue.
