### ISSUE TITLE
Intervals type missing in docs?

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb#2699]
Does DuckDB support the [`INTERVAL`](https://github.com/duckdb/duckdb/blob/a825cb059084707f72026ad8256ef7e2d7fa5ed7/test/sql/types/interval/test_interval.test) type? If so, it seems it's missing from the [Data Types](https://duckdb.org/docs/sql/data_types/overview) documentation page.

**Comment by david542542** [comment]
![image](https://user-images.githubusercontent.com/909771/144165355-43682b35-172c-4fad-9d78-ee2bea5cbc34.png)

**Comment by Alex-Monahan** [comment]
Good catch! It is supported. Please open an issue or make a pull request in the github repo for our website! That helps us keep track of documentation issues a bit better.
[Website repo](https://github.com/duckdb/duckdb-web)

**Comment by hawkfish** [comment]
I believe this [has been resolved](https://duckdb.org/docs/sql/data_types/interval).
