### ISSUE TITLE
Should note that duckdb_settings() is not available for 0.3.1

### ISSUE THREAD

**Issue by ajfg93** [duckdb/duckdb#2700]
`duckdb_settings()` documented in https://duckdb.org/docs/sql/configuration is not available for `0.3.1`, which is the default installation on duckdb website. My colleague spent some time on that and I got to know that by comparing the release date.

**Comment by Mytherin** [comment]
Currently the documentation indeed reflects the latest state of the master. We need to start versioning our docs similar to Postgres.
