### ISSUE TITLE
Nested selecting max from column values gives dependent join internal error

### ISSUE THREAD

**Issue by orlp** [duckdb/duckdb#2701]
#### What happens?

The reproduction query results in an internal error.

```
Error: INTERNAL Error: Logical operator type "EXPRESSION_GET" for dependent join
```

#### To Reproduce

```sql
CREATE TABLE test AS SELECT (i % 100)::INTEGER AS i, ((i * 2) % 100)::INTEGER AS j FROM range(0, 100000) tbl(i);
SELECT i, j, (SELECT max(x) FROM (VALUES (i), (j)) AS X(x)) as maxn FROM test;
```

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Alex-Monahan** [comment]
Hello and thanks for using DuckDB!
I'm looking at your query and trying to understand your goal. Would this query work instead?
```sql
Select i, j,  max(x) as maxn 
From test
Group by i, j
```

**Comment by orlp** [comment]
@Alex-Monahan That query isn't valid, so no. The query is equivalent to this:

```sql
SELECT i, j, greatest(i, j) as maxn FROM test;
```

The point of this bug report is not to get a working query however, it's to eliminate the internal error.
