### ISSUE TITLE
  duckdb_prepare_R: Unknown column type for prepare: TIMESTAMP (NS)

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#2734]
#### What happens?

`arrow::to_duckdb()` fails to handle TIMESTAMP data in NS format in parquet files which duckdb created.  

#### To Reproduce

- I export data from duckdb to parquet; works as expected.
- I read the parquet with `arrow::open_dataset` from R, works as expected
- I try `arrow::to_duckb()` and get the error on any timestamp-type column

```
  duckdb_prepare_R: Unknown column type for prepare: TIMESTAMP (NS)
```

(Guessing this is a just a datatype that still needs to be implemented on the parquet reader, at least for the R client?  lemme know if a copy-paste example of R would help)

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: current
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
Copy paste example would be very appreciated its likely just a missing type somewhere

**Comment by cboettig** [comment]
Sure thing, I should have done so first!  This should do it: (in R):

``` r
library(duckdb)
library(arrow)
library(dplyr)
db <- dbConnect(duckdb())
df <- data.frame(date = Sys.Date())
dbWriteTable(db, "table", df)

dir <- "test"
query <- paste0("EXPORT DATABASE '", dir, "' (FORMAT PARQUET);")
dbExecute(db, query)
#> [1] 0
ds <- open_dataset("test")
to_duckdb(ds)
#> Error in .local(conn, statement, ...): duckdb_prepare_R: Unknown column type for prepare: TIMESTAMP (NS)
```

<sup>Created on 2021-12-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by james-atkins** [comment]
Also bumped into this with milliseconds. There are some case statements missing here: https://github.com/duckdb/duckdb/blob/0d3fee81ba83d69adf362d92482101a82a4a5de1/tools/rpkg/src/statement.cpp#L96-L98.

Aside from the missing case statements, there is the issue of what R type can handle these higher resolutions. POSIXct is a double with fractional seconds so it has enough accuracy to handle milliseconds. Adding this should be trivial.

Nanoseconds are trickier as POSIXct doesn't have enough bits. The [nanotime](https://cran.r-project.org/web/packages/nanotime/index.html) package can handle this but it would be another dependency.

**Comment by cboettig** [comment]
Thanks @james-atkins , that's a good point.  IMHO, in the case of nanosecond encoding, I think the default behavior of the R client should just round this to millisecond precision with a one-time warning about the precision loss.  In my experience, many data serializations merely encode data to the finest available precision of the software, often this precision is not only not necessary but not justified by the data collection mechanism (as illustrated in the reproducible example above!)

Of course that would still be problematic in cases where nanosecond precision is critical, but that edge case could be handled at a later point?
