### ISSUE TITLE
Question: Can one easily determine if a string value matches the label of an enum?

### ISSUE THREAD

**Issue by chrisfw** [duckdb/duckdb#2740]
Hello,

In Postgres one can apparently determine if a string value matches an enum label by using the **enum_range** function in combination with **any** and casting the returned array to **name[]**:   

SELECT enum_range(null::known_roles_list);
  enum_range
---------------
 {role1,role2}
 
SELECT current_user = **any**(enum_range(null::known_roles_list)::**name[]**)

source: https://stackoverflow.com/questions/51924066/postgresql-check-if-value-is-equal-to-an-enum-value

How can we check for a match in duckdb?  Is an attempted cast to the enum type the way to accomplish this? 

Regards,
Chris

**Comment by pdet** [comment]
Hi Chris,

You can do a try_cast
e.g.,
```sql 
select TRY_CAST(string_value AS enum_type)
```
If it returns Null, the string value is not part of the ENUM.

**Comment by chrisfw** [comment]
Thanks a lot for your prompt response Pedro.  Will do!

Regards,
Chris

**Comment by Mytherin** [comment]
@pdet we should probably add this `enum_range` function, as well as [these enum functions](https://www.postgresql.org/docs/8.3/functions-enum.html) at some point.
