### ISSUE TITLE
Add Enum Support Functions

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#2741]
Reference: https://www.postgresql.org/docs/14/functions-enum.html
```sql 
CREATE TYPE rainbow AS ENUM ('red', 'orange', 'yellow', 'green', 'blue', 'purple');
```

- [ ] enum_first ( anyenum ) → anyenum
Returns the first value of the input enum type.
e.g., enum_first(null::rainbow) → red

- [ ] enum_last ( anyenum ) → anyenum
Returns the last value of the input enum type.
e.g., enum_last(null::rainbow) → purple

- [ ] enum_range ( anyenum ) → anyarray
Returns all values of the input enum type in an ordered array.
e.g., enum_range(null::rainbow) → {red,orange,yellow,​green,blue,purple}

- [ ] enum_range ( anyenum, anyenum ) → anyarray
Returns the range between the two given enum values, as an ordered array. The values must be from the same enum type. If the first parameter is null, the result will start with the first value of the enum type. If the second parameter is null, the result will end with the last value of the enum type.
e.g., enum_range('orange'::rainbow, 'green'::rainbow) → {orange,yellow,green}
enum_range(NULL, 'green'::rainbow) → {red,orange,​yellow,green}
enum_range('orange'::rainbow, NULL) → {orange,yellow,green,​blue,purple}

**Comment by Mytherin** [comment]
@pdet could you add documentation for these functions to the website, under an "Enum Functions" header?
