### ISSUE TITLE
test_all_types function integration

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#2747]
The `test_all_types()` (see #2739) function needs to be integrated with all client connectors. This will ensure all client connectors support all types, and they continue to support all types.

We can use this issue to track progress:

- [x] Python Object Connector (`fetchall`) (@pdet)
- [x] Pandas Connector (`fetchdf`)
- [x] Arrow Connector (`fetcharrow`)
- [x] R Connector
- [x] C API
- [X] C++ API
- [x] Julia API
- [ ] ODBC (@tiagokepe)
- [x] JDBC
- [ ] node.js
- [x] Parquet reader/writer round-trip
- [ ] CSV reader/writer round-trip
- [X] Storage round-trip

**Comment by krlmlr** [comment]
For the R connector, the following columns need translations in 192e3cf8ab0a42a0cbaee69a639ebdaaaeee54dc:

- `timestamp_tz`
- `time_tz` (what is this?)
- `uuid` (to ALTREP string with class?)
- `interval` (to R's `difftime`)
- `map` (to R's named list)
- `json` (to ALTREP string with class?)

CC @nbenn.

**Comment by Mytherin** [comment]
Timestamp_tz and time_tz are exactly the same as timestamp and time internally, they just represent a UTC adjusted instance in time. Not sure about R’s timezone handling, but if it has none they can be converted the same way as regular timestamps/times as a fallback.

**Comment by krlmlr** [comment]
R is integrated now, minus bugs in R core which we have to work around for now.

**Comment by Mause** [comment]
JDBC now has this implemented 😁
