### ISSUE TITLE
Python enable_external_access config flag does not restrict csv/parquet access

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#2750]
#### What happens?
Hi Folks!

One of my coworkers was testing out the enable_external_access config parameter that you added for us (thank you!). Unfortunately, it does not work like we had expected. It does correctly restrict access to DataFrames in the global scope, but it does not restrict file system access for csv or parquet files. We are completely open to a separate flag that would restrict file system access, or for that capability to be added to this flag - whichever is easier! We have other protections in place to isolate users and prevent them from accessing things we want to protect so this is not urgent or gating a deployment, but this would be a really great security feature for us.

Related prior issue: #1773

Thanks!
-Alex

#### To Reproduce
```python
import duckdb
import pandas as pd

dftest = pd.DataFrame([{"This":1,"is":2,"a":3,"test":4},{"This":5,"is":6,"a":7,"test":8}])
dftest.to_csv('test.csv')
file_creation_conn = duckdb.connect(':memory:', config={'enable_external_access': True})
file_creation_conn.execute("COPY (select * from dftest) to 'test.parquet' WITH (FORMAT PARQUET)").fetchdf()
file_creation_conn.close()

# The goal is to disable dataframe as well as filesystem access for this connection
conn = duckdb.connect(':memory:', config={'enable_external_access': False})

#The following statements succeed when they should fail:
df = conn.execute("select * from parquet_scan('test.parquet')").fetchdf()
print('parquet_scan results:\n',df)
df = conn.execute('select * from "test.parquet"').fetchdf()
print('test.parquet results:\n',df)
df = conn.execute("select * from 'test.csv'").fetchdf()
print('test.csv results:\n',df)
df = conn.execute("select * from read_csv_auto('test.csv')").fetchdf()
print('read_csv_auto results:\n',df)

#This statement correctly fails 
df = conn.execute("select * from dftest").fetchdf()
print('select * from dftest results:\n',df)
```
#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.1 and 0.3.2.dev521
 - DuckDB Client: Python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! This looks like a small oversight, disabling external access should disable all external file system operations. Will have a look.

**Comment by Alex-Monahan** [comment]
Figured it was something small! Thanks as always Mark!
