### ISSUE TITLE
[Question] Does the parquet reader in duckdb support page level index skipping?

### ISSUE THREAD

**Issue by mingmwang** [duckdb/duckdb#2755]
https://github.com/apache/parquet-format/blob/master/PageIndex.md

**Comment by hannesmuehleisen** [comment]
No, this is not supported currently.

**Comment by hannesmuehleisen** [comment]
Do you have an example for a tool that actually writes those?

**Comment by mingmwang** [comment]
No, currently not. The parquet files could be generate by other engines like Spark. Do you have any plan to support the page level index in the near future ?

**Comment by hannesmuehleisen** [comment]
We don't have plans at this point since this mostly improves point queries which is not what DuckDB is focused on.

**Comment by lhoestq** [comment]
I feel like page skipping could accelerate queries like `SELECT * FROM ... LIMIT 5` ? Currently it has to load a full row group, which can be big sometimes.
