### ISSUE TITLE
utf8 char didn't show correctly when use `pragma enable_profiling`  in windows. 

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2761]
#### What happens?
utf8 char didn't show correctly when use `pragma enable_profiling` in windows 7 Chinese version . 
btw, explain command shows correct UTF8 char. 
#### To Reproduce
create table ints as select cast(random() * 99999999 as int) i from range(100000000);
pragma enable_profiling;
select last_value(i) over () from (select i from ints order by i) sq limit 1; -- same with first_value
Result:

#### Environment (please complete the following information):
 - OS: [e.g. iOS]windows7 x64
 - DuckDB Version: [e.g. 22]0.3.2 dev-479
 - DuckDB Client: [e.g. Python]CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #2773.
