### ISSUE TITLE
Duckdb crashes when accessing large parquet files (from R)

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#2768]
#### What happens?

R crashes (OOM) on `to_duckdb()` or when performing operations on large (~100GB) single parquet file.  
The same queries on the data if first partitioned seem to avoid the crash.

#### To Reproduce

Thanks to the awesome integration with `arrow` and it's out-of-the-box support for S3 access, we should be able to reproduce it this time around without you having to download (like we did for #2193...)

```r

library(arrow)
library(duckdb)
library(dplyr)
server <- arrow::s3_bucket("ebird",endpoint_override = "minio.cirrus.carlboettiger.info")

path <- server$path("Oct-2021/observations")
obs <- arrow::open_dataset(path)

path$ls() # observe -- 1 parquet file

## Boom, this will crash:
obs %>% to_duckdb() # crash
```

(If necessary, you should be able to download the file directly).  

However, here is an example where I break the dataset up into multiple parquet files.  After a quick hack to avoid #2734, this one seems to work:

```r

## Restart R, reload libs, try again with multi-parquet version of data
library(arrow)
library(duckdb)
library(dplyr)
server <- arrow::s3_bucket("ebird",endpoint_override = "minio.cirrus.carlboettiger.info")

path <- server$path("partitioned")
obs <- arrow::open_dataset(path)
obs$ls() # observe, multiple parquet shards

obs %>% to_duckdb() # does not recognize timestamp

## ick ick, hack around issue #2734
s <- schema(obs)
s[[2]] <- arrow::date64()
s[[29]] <- arrow::date64()

obs <- arrow::open_dataset(path, schema = s)
# tada no crash!
obs %>% to_duckdb() 

```

though  the memory use is still very large!  Trying to limit memory with PRAGMA is unsuccessful in this context too.  
It's possible of course this is really an `arrow` issue shown above, though I keep having RAM issues working directly with this parquet file from R with pure duckdb parquet drivers sans any `arrow` involvement (at least for more non-trivial queries).  

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: master branch
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
How many row groups are in the big file?

**Comment by cboettig** [comment]
I believe it's just over a billion rows:

```r
library(duckdb)
library(dplyr)
db <- DBI::dbConnect(duckdb())
tblname <- "obs"
parquet <- "/minio/ebird/Oct-2021/observations/part-0.parquet"
view_query <- paste0("CREATE VIEW '", tblname, 
                     "' AS SELECT * FROM parquet_scan('",
                     parquet, "');")
DBI::dbSendQuery(db, view_query)
DBI::dbExecute(conn = db, 
               paste0("PRAGMA memory_limit='", 10, "GB", "'"))

obs <-  tbl(db, tblname)
obs %>% count() %>% collect()
```


It works better with the native duckdb parquet reader as shown above (the same command with the arrow connection crashes, even without `to_duckdb()`, though I get memory errors.  e.g. having set the 10GB memory limit above, trying to run:

```r
> obs %>% count(scientific_name, country, sort=TRUE) %>% collect() -> test
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Out of Memory Error: could not allocate block of 262144 bytes
Database is launched in in-memory mode and no temporary directory is specified.
Unused blocks cannot be offloaded to disk.

Launch the database with a persistent storage back-end
Or set PRAGMA temp_directory='/path/to/tmp.tmp'
```

If I set tempdir PRAMGA as directed, it still fails (but no longer recommends using tmp):

```t
 obs %>% count(scientific_name, country, sort=TRUE) %>% collect() -> test
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Out of Memory Error: could not allocate block of 262144 bytes
```

**Comment by alexey-milovidov** [comment]
I see the same issue with Python: https://github.com/duckdb/duckdb/issues/3969

**Comment by alexey-milovidov** [comment]
?

**Comment by alexey-milovidov** [comment]
?

**Comment by WyattLiu** [comment]
I wrote a remote/disk-swap memory system for duckdb for reasons like this (virtually never OOM), but the tmp storage system is still a mystery to me. Sometimes they are more effective than my remote memory system, and sometimes will just die like this. I hope there is more documentation on this.
