### ISSUE TITLE
node bindings: `PRAGMA table_info(table_name)` throws `[Error: Data type is not supported BOOLEAN]`

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#2772]
#### What happens?

Thank you all for your incredible work with DuckDB! I'm simply blown away by all the possibilities in utilizing it for speedy drilldowns in applications and analysis environments.

I'm leveraging the node bindings provided, and ran into a potential bug. The duckdb node bindings unfortunately throw an error when using `PRAGMA table_info(table_name);` : `[Error: Data type is not supported BOOLEAN]`

#### To Reproduce

I ran the following minimal code example to re-create in a node script based on the duckdb node documentation (I'm using `type: module` but even in removing this the error occurs):

```javascript
import duckdb from 'duckdb';

const db = new duckdb.Database(':memory:');
var con = db.connect();
con.run('CREATE TABLE a (i INTEGER)');
const stmt = con.prepare('INSERT INTO a VALUES (?)');
for (var i = 0; i < 10; i++) {
	stmt.run(i);
}

con.prepare('PRAGMA table_info("a");').all(console.log);

```

One would expect a table resultset here like the one produced via `PRAGMA show(table_name);`. When I run the CLI tool the pragma produces a table, so it appears to be an issue specifically with the node bindings.

#### Environment (please complete the following information):
 - OS: Mac OS X 10.15.6 (Catalina)
 - DuckDB Version: `0.3.1` (reproduced on `0.3.2-dev586.0` as well)
 - DuckDB Client: Node

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?** yes, using `npm install duckdb@next` as described on the website.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?** Yes.

**Comment by Alex-Monahan** [comment]
Hello and thanks for checking out DuckDB!

Boolean support in NodeJS is a known gap (please see #1342). If you'd like to help contribute a fix that would be fantastic!

**Comment by hamilton** [comment]
Thanks for the reply ~ I know better than to create a new issue w/o searching for a pre-existing one first :) Will close in favor of that one.

**Comment by hamilton** [comment]
I filed a PR #2784 to address this.
