### ISSUE TITLE
Enforce LIMIT when querying a csv

### ISSUE THREAD

**Issue by edalfon** [duckdb/duckdb#2777]
#### What happens?
DuckDB does not strictly observe the LIMIT clause when querying a CSV. This can lead to errors, when the limit was precisely trying to avoid invalid rows.

I bumped into this the hard way. I have to deal with a bunch of csv files that, unfortunately, end with an indication of the number of rows, like this:
```
(493689741 row(s) affected)
```
I set LIMIT 493689741 in the query, so that it did not fail trying to parse that extra line. But it fails anyway, because it did try to parse the lines beyond the defined limit.
```
Error: Invalid Input Error: Error on line 493689744: expected 32 values per row, but got 1.
```
Notice the error is on a line beyond the limit: 493689744 > 493689741 

If you set the LIMIT to a small value (e.g. 10) it works. But if the limit is near the invalid line, it fails (it seems to me, if the invalid line is within STANDARD_VECTOR_SIZE=1024 rows of the limit).

What it seems to be going on, is that the csv reader parses only full chunks of 1024 rows. It will read the number of chunks so that 1024 * num_chunks >= limit. But then, the last chunk may try to parse beyond the limit and it would fail, if it contains an invalid line.

It would be great to enforce that the csv reader only parses the file up to the limit defined in the query.

#### To Reproduce (see also a full reprex in a public RStudio Cloud project [here](https://rstudio.cloud/project/3358482))

Let's just make a csv file, with an invalid line towards the end (here, using R)

```r
# write valid data
write.table(
  x = ggplot2::diamonds,
  file = "csv_file.csv",
  sep = ";",
  row.names = FALSE
)
# and then fake an invalid line towards the end of the file
write("", file = csv_file, append = TRUE, sep = "\n")
write("(493689741 row(s) affected)", file = csv_file, append = TRUE, sep = "\n")
```

And this is what I was aiming for: simply set the limit clause to the total number of valid lines (`nrow(ggplot2::diamonds)`)
```sql
SELECT * FROM read_csv_auto('csv_file.csv') LIMIT 53940;
```

But it fails
```
Error: Invalid Input Error: Error on line 53944: expected 10 values per row, but got 1. (DELIMITER=';' (auto detected), QUOTE='"' (auto detected), ESCAPE='' (auto detected), HEADER=1 (auto detected), SAMPLE_SIZE=10240, ALL_VARCHAR=0)
```

I tried, for example, using `read_csv` and changing SAMPLE_SIZE. But that's no solution.

Then after reading a few questions ([here](https://stackoverflow.com/questions/63235906/csv-reader-behavior), here, here), I figured the csv reader ingests chunks of a standard vector size (1024). Not sure how accurate is that, but it led me to try setting the limit using that logic, and it seems that's the issue.

Taking the total number of valid rows and 1024 lines per chunk, it would need to read 52.7 chunks (`53940 / 1024`). But if it reads only whole chunks, it will read all the rows in the 53th chunk, which includes the invalid line. But if you set the limit to exactly 51 chunks (`51 * 1024 = 52224`), voilà it works!  But if try to add one line +1 to that limit (52225), it fails again reading until the end of the file and stumbling with the invalid line.

EDIT: here I noticed a change between DuckDB `0.3` and `0.3.1`. I originally bumped into this running `0.3`, and the max limit that worked was `floor(53940 / 1024) * 1024 = 53248`. But in `0.3.1` that one fails too. Now you need to set limit to `(floor(53940 / 1024) - 1) * 1024 = 52224` as explained above.

I could not find any workaround to be able to read all lines of valid data, other than removing the invalid line from the file (which is a no go because it goes against the policy of not changing the raw data and also would not be fun at all, considering in the real use case we are talking about a bunch of files, each > 80GB).

#### Environment (please complete the following information):
 - OS: Windows 10 (also tried in Ubuntu 20.04.3 LTS, in an RStudio Cloud project with similar results)
 - DuckDB Version: 0.3.1-1
 - DuckDB Client: R

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source. 

Tried also on the latest `master` branch, only in R running on Windows, though. In Ubuntu the master branch failed to compile and I could not quickly debug/solve that. 

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yeap, take a look at the `duckdb_limit_csv.Rmd` file in this project https://rstudio.cloud/project/3358482

**Comment by Mytherin** [comment]
Thanks for the report!

I don't think the LIMIT is the correct way of going about this. As you have noticed, this kind of works since the limit pushdown allows the CSV reader to abort reading early, but this is a side-effect of the limit pushdown optimisation and not the main purpose. As you have noticed, as DuckDB processes data in chunks of 1024 rows at a time, this does not work as the CSV reader will read slightly beyond the actual limit.

A more robust solution to this problem seems to me to add an `nrows` parameter to the CSV reader, that will stop reading after the given number of rows has been read.

**Comment by edalfon** [comment]
Thx. Agree!, something like `nrows` parameter would be great. That was actually the first thing I looked for in `read_csv` and the `COPY ... FROM` statement. As those do not have it, I went to try the limit approach, which is actually a trick one can use to ingest such kind of files into Postgres, whose `COPY` command does not have an `nrows` as well (but you can create a foreign table using a foreign data wrapper, and then query the table using limit). So yeah, it would be great if you guys can add such parameter. 

Thanks and congrats for DuckDB!, it's awesome!
