### ISSUE TITLE
Error: IO Error: No files found that match the pattern

### ISSUE THREAD

**Issue by goldengrisha** [duckdb/duckdb#2804]
#### What happens?
When I call 
```sql
SELECT * FROM PARQUET_SCAN('https://github.com/KTH-Library/cordis-data/releases/download/0.0.1/projectPublications.parquet?raw=true') LIMIT 10;
```
I get all the time `Error: IO Error: No files found that match the pattern`

#### Environment (please complete the following information):
 - OS: MacOS
 - DuckDB Version: [e.g. duckdb-0.3.2.dev683]
 - DuckDB Client: [e.g. python]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by omo** [comment]
I believe this is due to the lack of `INSTALL 'httpfs';`
Maybe we can close this as work as intended.

**Comment by goldengrisha** [comment]
After update I could solve my issue, sorry for the late answer.
