### ISSUE TITLE
Feature Request: C++ 20 support

### ISSUE THREAD

**Issue by jwdeitch** [duckdb/duckdb#2805]
Hi there! 

It looks like only 2 changes need to happen to support C++ 20:

`std::uncaught_exception()` => `std::uncaught_exceptions()`

and deprecating `std::binary_function` which should be trivial.

Any reservations to making these changes? I'm happy to submit a PR.

Thank you!

**Comment by hannesmuehleisen** [comment]
Great, we should also add a CI run that tests compilation with the various newer C++ standards

**Comment by emmenlau** [comment]
I've just compiled duckdb in c++20 on Linux successfully. I've disabled most features so maybe thats why it works, or is this issue fixed already?

**Comment by jwdeitch** [comment]
I am compiling on windows/msvc:  `__cplusplus` macro doesn't expand correctly unless a flag is set.

**Comment by emmenlau** [comment]
> I am compiling on windows/msvc: `__cplusplus` macro doesn't expand correctly unless a flag is set.

Yes, I've also encountered this in some projects, seems https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170 is required.

**Comment by carlopi** [comment]
I think C++20 is properly supported, I checked on clang 14.0.0 on MacOS and the CI regularly runs it in various configurations on Linux (eg. builds by CRAN).

Please do reopen if you are experiencing any problem with C++20 support.

**Comment by ShravanSunder** [comment]
@carlopi  related https://github.com/duckdb/extension-ci-tools/issues/180
