### ISSUE TITLE
Failure on reading in text field when some control characters are mixed with text

### ISSUE THREAD

**Issue by msjgriffiths** [duckdb/duckdb#2811]
#### What happens?
When reading in a file with control characters embedded in a text field, DuckDB will fail to read the field -- actually, it will fail to read the entire file, and if there are multiple files DuckDB is reading in it will hard fail all of them. Other CSV readers either drop the line (e.g. `readr::read_csv`) or work fine (e..g Julia's `CSV.jl`). 

#### To Reproduce
Please see this file: [control-chars.csv](https://github.com/duckdb/duckdb/files/7736422/control-chars.csv)
```r
library(duckdb)
#> Loading required package: DBI

con = dbConnect(duckdb::duckdb(), dbdir=":memory:")

dbGetQuery(con, "select * from read_csv_auto('control-chars.csv', HEADER=TRUE, ESCAPE='\"')")
#> Error in .local(conn, statement, ...): duckdb_prepare_R: Failed to prepare query select * from read_csv_auto('control-chars.csv', HEADER=TRUE, ESCAPE='"')
#> Error: basic_string
```

#### Environment (please complete the following information):
 - OS: Mac OSX
 - DuckDB Version: R plugin `0.3.2`
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
When trying this in the CLI, I get `Error: Invalid Input Error: Error on line 39: expected 87 values per row, but got 1. (DELIMITER=',' (auto detected), QUOTE=''' (auto detected), ESCAPE='\"', HEADER=1, SAMPLE_SIZE=10240, ALL_VARCHAR=0)`. I think there is something going wrong when exporting the error to R...
