### ISSUE TITLE
[Docs] Do all data types support NULL?

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb#2812]
I tried to find out if the `date` type supports `NULL` and couldn't find it in the documentation.

The documentation in general seems to be very lean on the word `NULL` so I'm not sure...

It should either be mentioned in a section titled `NULL` or in each data types section like here: https://duckdb.org/docs/sql/data_types/date

**Comment by corneliusroemer** [comment]
I think I found the answer: all types can be `NULL`

But it's a bit hidden under insert...

![image](https://user-images.githubusercontent.com/25161793/146584921-20666f0d-90f4-478a-b6fa-760ef2ec6e7e.png)

https://duckdb.org/docs/sql/statements/insert

**Comment by Alex-Monahan** [comment]
Hello!

Thanks for trying out DuckDB!

NULLs are in general supported everywhere - they are core to how DuckDB is architected.

If you have questions or want to report changes to the docs, you have 2 other options that may work better!

The first is to use our new discord channel for questions:
[Discord](https://discord.gg/vukK4xp7Rd)

The second is to post issues or Pull Requests for our docs in its own repo:
[Duckdb-web](https://github.com/duckdb/duckdb-web)
