### ISSUE TITLE
[Docs/Feature] Combine SAMPLE with GROUP BY

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb#2813]
Is it possible to combine SAMPLE with GROUP BY? If not, it would be great if this could be implemented.

## Use case

When building phylogenetic trees for SARS-CoV-2, I need to select a subsample of all sequences. It can't just be a simple fractional subsampling because some countries are vastly overrepresented.

Group by sampling comes with difficult levels of sophistication:

- Level 1: Select up to a specified number of sequences per country
- Level 2: Select an equal number of sequences per country and month.
- Level 3: Specify the number of samples I want per group, e.g. `UK=10, USA=15,...`

Right now, I'm doing level 3 in pandas where it looks as follows:
```python
df.groupby('country').apply(
            lambda x: x.sample(
                n=df_weights.loc[x.name,'chosen'],
                replace=False
                )
            ).to_csv(output.metadata,sep="\t",index=False)
```

Where df_weights is a simple series of the form: `country; number to sample`

It'd be great if this was supported by duckdb, but I understand of course if this is not a priority.

**Comment by Alex-Monahan** [comment]
Thanks for the feedback!

If you'd like an initial solution in the meantime, you can use a window function to select a portion of rows per group. This is untested code from a phone, but should just about work!

```sql
Select 
  *
From (
Select
  Row_number() over (partition by grouping_column1, grouping_column2 order by random() ) as my_ranking
  ,*
From my_table

)
Where
  my_ranking < 10
```

**Comment by corneliusroemer** [comment]
Wow this is great! Thanks for your support. Makes me want to dig deeper for what duckdb can do for us - we're evaluating duckdb as a dependency for https://github.com/nextstrain/augur

**Comment by Alex-Monahan** [comment]
Feel free to toss any questions you run into on our [Discord Page](https://discord.gg/vukK4xp7Rd)!
