### ISSUE TITLE
Feature: support reading of zstd compressed csv files

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb#2814]
I'm trying to ETL a csv file into a parquet file. It works well with gz compressed files, but unfortunately you don't seem to support zst compression yet even though the documentation is somewhat unclear on which compression methods can be read (please be more precise):

![image](https://user-images.githubusercontent.com/25161793/146627135-93426ca5-5d05-4878-bb8d-7746610ea7b0.png)

https://duckdb.org/docs/data/csv

It would be great if this worked (zstd compress SARS-CoV-2 sequences about a factor of 10 better than gz and we're dealing with >100GB now 😬 )

```python
con = duckdb.connect("testdb",read_only=False)
con.execute("""
    COPY (SELECT * FROM read_csv_auto('test.tsv.zst') )
    TO 'duckseq.parquet' 
    (FORMAT 'PARQUET', CODEC 'ZSTD')
    """)
```

**Comment by Mytherin** [comment]
This is already supported in the master, see #2697. Indeed the documentation should be updated here.

**Comment by corneliusroemer** [comment]
Oh this is amazing. If it works, duckdb would be the first to allow streaming of zstd compressed file into parquet.

I'll try it out and close if it works.

**Comment by Mytherin** [comment]
Closing this, as this is implemented already.

**Comment by corneliusroemer** [comment]
Thanks, yes, great to know it's implemented! Hopefully this issue helps discoverability of the feature through Google etc.
