### ISSUE TITLE
Feature: Support large file csv->parquet conversion by not reading entire uncompressed file into memory

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb#2816]
I'm currently hunting for the best csv->parquet conversion tool and duckdb is one of the contenders.

The use case is:
Turn some `.csv` (100GB uncompressed) that I have lying around compressed as `.csv.gz` (1GB compressed) into `.parquet`.

duckdb can do this in principle, but the limit is that uncompressed size must be `<<` than memory (see #2815 for bug when this isn't the case).

It would be really nice if duckdb would support bigger file sizes too (not sure if this is easy to do, but maybe it is in which case this would surely be helpful for others too).

**Comment by hannesmuehleisen** [comment]
It should be possible to stream this with DuckDB, can you share the specific setup?

**Comment by corneliusroemer** [comment]
I'm using the exact command that causes the bug as in #2815 
```python
import duckdb
con = duckdb.connect("::memory::")
con.execute("""
    COPY (SELECT * FROM read_csv_auto('sequences.csv.gz', delim=',', header=True) )
    TO 'duckseq.parquet' 
    (FORMAT 'PARQUET', CODEC 'ZSTD');
    """)
```

Is that wrong?

**Comment by Mytherin** [comment]
No, that is correct and that indeed streams the file, but given that you are dealing with very large rows I am guessing your memory does not fit 100K rows, which is the default batch size in the Parquet writer. We should make this configurable.

**Comment by corneliusroemer** [comment]
That seems to be the problem then, yes. 170GB/6m rows -> 3GB/6m rows, if there's a bit of overhead it may be enough to crash. It might be just around the limit where it crashes sometimes, but not always.

In this case setting to something like 10k rows would be the solution. Thanks for working on a solution, much appreciated.

**Comment by Mytherin** [comment]
This is fixed now
