### ISSUE TITLE
`SELECT a,b FROM x.parquet WHERE a=y` seems to uncompress all of b not just the relevant row block

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb#2820]
#### What happens?
I have a very heterogeneous `parquet` file with 6m rows:
- Row `a` contains strain names which are strings of length ~20.
- Row `b` contains sequences that are 30kB long and compress very well with zstd (they are all very similar).

The parquet file seems to have a row block size of 1024 rows per block.

When I just query for the compact row `a`, the query executes very quickly:
```python
seq = con.query("""
SELECT a FROM 'seq.parquet'
WHERE a IN (
    'y1','y2'
)
""").fetchall()
```
finishes in 1.7 seconds

When I now add b into the mixture, suddenly the query becomes really slow:
```python
seq = con.query("""
SELECT a,len(b) FROM 'seq.parquet'
WHERE a IN (
   'y1', 'y2'
)
""").fetchall()
```
takes 3m30s, a whopping 100 times slower than the earlier query.

This seems unnecessary: after all, duckdb should first find out which row numbers should be extracted  - which shouldn't take longer than the fast query at the top, and then only run the `SELECT a, len(b)` part of the query.

This doesn't seem to happen though. The only way I can explain the slow querying, is that in fact duckdb does it all in one go, not using the fact that the where clause does not require b. This seems inefficient and not so great for use cases like described above.

#### Environment (please complete the following information):
 - OS: macOS 12.1
 - DuckDB Version: master 0.3.2
 - DuckDB Client: python-duckdb

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

I can create a sample dataset if this would help you debug. But I don't want to spend time on this if it's not required.

**Comment by corneliusroemer** [comment]
One way to speed up by factor 6 in my case is to use a trick: Add `ORDER BY`, that way the query is parallelised. I learned this from this issue: https://github.com/duckdb/duckdb/issues/773

```python
seq = con.query("""
    SELECT * FROM 'seq.parquet'
    WHERE strain IN (
        SELECT strain
        FROM 'meta.parquet'
        WHERE pango_lineage LIKE 'B.1.1.529'
    )
    ORDER BY strain
    """).fetchall()
```

Would be good if such magic was documented.

Using 10 processes sped up by factor 6 to 37s instead of 3m30.

**Comment by arjenpdevries** [comment]
One question: would column `b` not have to be decompressed before you could seek into it for locating the matching row numbers from `a`?

**Comment by corneliusroemer** [comment]
Yes, but only the row blocks with matching rows should have to be decompressed.

In the parquet file k. question, there are 6k row blocks with 1024 rows each.

Only 1-2 would have to be uncompressed. Yet it looks like all 6k are decompressed. Total waste of time.

Or is my understanding of decompression of parquet columns wrong and compression happens over the whole column and not just the row block of a column?

**Comment by hannesmuehleisen** [comment]
> Total waste of time.

Sorry to not live up to your standards

**Comment by hannesmuehleisen** [comment]
Also, can you share the file please? We do appreciate reproducible test cases and yes, it always helps to have a sample.

**Comment by corneliusroemer** [comment]
The data I'm testing this on is confidential so I will have to make an
equivalent just for you, but happy to do so if it's useful to you.

**Comment by Alex-Monahan** [comment]
If you could create an artificial example that would be excellent! You could even just do a 1 way hash on each cell of the data you have if that's easiest / secure enough. We often add these small examples to our test suite.

**Comment by corneliusroemer** [comment]
I created a similar dataset from open data.

Reproducible example:

Get dataset: `wget https://nextstrain-data.s3.amazonaws.com/files/ncov/open/seq.parquet`

Run the following two queries which should take very different amounts of time, since in the first case only one row block of `sequence` would have to be uncompressed. Whereas in the second up to 100.

```python
con = duckdb.connect(":memory:")
con.execute("PRAGMA threads=10;")

# Fast as expected, 0.8s
con.query("""
    SELECT strain
    FROM 'seq.parquet'
    WHERE strain IN
    (
        SELECT strain 
        FROM 'seq.parquet'
        USING SAMPLE 1000 ROWS
        ORDER BY strain
    )
    ORDER BY strain;
    """).fetchall()


# Should be almost as fast, but is much slower
# 17.5s
con.query("""
    SELECT strain, len(sequence) 
    FROM 'seq.parquet'
    WHERE strain IN
    (
        SELECT strain 
        FROM 'seq.parquet'
        USING SAMPLE 1 ROWS
        ORDER BY strain
    )
    ORDER BY strain;
    """).fetchall()


# Should be much slower than above but is just as slow
con.query("""
    SELECT strain, len(sequence) 
    FROM 'seq.parquet'
    WHERE strain IN
    (
        SELECT strain 
        FROM 'seq.parquet'
        USING SAMPLE 1000 ROWS
        ORDER BY strain
    )
    ORDER BY strain;
    """).fetchall()
```
