### ISSUE TITLE
JDBC Connection autocommit behavior appears wrong

### ISSUE THREAD

**Issue by cnuernber** [duckdb/duckdb#2824]
#### What happens?

Autocommit on JDBC Connection objects does not work like other systems.  Specifically setting passing the autocommit property in to the createConnection call does not result in a JDBC connection that has auto-commit set to false.  Furthermore attempting to set auto-commit to false on the actual transaction object fails and the object continues to have auto-commit set to true.

```clojure
tech.v3.dataset.sql-test> (def conn (sql-utils/connect :duckdb))
#'tech.v3.dataset.sql-test/conn
tech.v3.dataset.sql-test> conn
#object[org.duckdb.DuckDBConnection 0x489e5997 "org.duckdb.DuckDBConnection@489e5997"]
tech.v3.dataset.sql-test> (.getAutoCommit conn)
true
tech.v3.dataset.sql-test> (.setAutoCommit conn false)
nil
tech.v3.dataset.sql-test> (.getAutoCommit conn)
true
```

#### To Reproduce

Attempt to use the connection with auto-commit false.  Set to false, call executeUpdate! then commit as per the specification either either a normal statement or with a prepared statement results in exceptions due to transactions *not* being open.  This is inconsistent with respect to the behavior of other connections e.g. postgres or sql-server.

#### Environment (please complete the following information):
 - OS: linux
 - DuckDB Version: 0.3.1
 - DuckDB Client: JDBC

I did not try with master but I did review the code and it appears that auto-commit is a property of the transaction and this is inconsistent with the JDBC specification to my understanding.

I have a work-around in that I have [bindings to the c api](https://github.com/cnuernber/tmducken) that appear to work just fine so my interest in this issue is simply to report what happened when I tested the jdbc bindings against other database jdbc bindings.

**Comment by omo** [comment]
Unsolicited triage bot here: Seems to be fixed now?
