### ISSUE TITLE
Window function ignoring FILTER clause

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#2831]
#### What happens?
When a window function includes a FILTER clause, the query still runs, but the rows are not filtered prior to passing them into the window function.

#### To Reproduce
```python
import duckdb
import pandas as pd

conn = duckdb.connect(':memory:')
output_df = conn.execute("""
    create table testing as 
        select 
             x
            ,round(x * 0.333,0) % 3 as y 
            ,round(x * 0.333,0) % 3 as z
        from generate_series(0,10) tbl(x);
""").fetchdf()

# The x_filtered_window and z_filtered_window columns should return a different output than plain_window
output_df = conn.execute("""
    select 
         x
        ,y
        ,z
        ,avg(x) over (partition by y) as plain_window
        ,avg(x) FILTER (WHERE x = 0) over (partition by y) as x_filtered_window
        ,avg(x) FILTER (WHERE z = 0) over (partition by y) as z_filtered_window
    from testing 
    order by 
        y;
""").fetchdf()
print(output_df)
```
The x_filtered_window and z_filtered_window columns should return a different output than plain_window:
| x  |  y  |  z  | plain_window | x_filtered_window | z_filtered_window |
|----|-----|-----|--------------|-------------------|-------------------|
| 0  | 0.0 | 0.0 | 5.6          | 5.6               | 5.6               |
| 1  | 0.0 | 0.0 | 5.6          | 5.6               | 5.6               |
| 8  | 0.0 | 0.0 | 5.6          | 5.6               | 5.6               |
| 9  | 0.0 | 0.0 | 5.6          | 5.6               | 5.6               |
| 10 | 0.0 | 0.0 | 5.6          | 5.6               | 5.6               |
| 2  | 1.0 | 1.0 | 3.0          | 3.0               | 3.0               |
| 3  | 1.0 | 1.0 | 3.0          | 3.0               | 3.0               |
| 4  | 1.0 | 1.0 | 3.0          | 3.0               | 3.0               |
| 5  | 2.0 | 2.0 | 6.0          | 6.0               | 6.0               |
| 6  | 2.0 | 2.0 | 6.0          | 6.0               | 6.0               |
| 7  | 2.0 | 2.0 | 6.0          | 6.0               | 6.0               |

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: duckdb-0.3.1 and latest master (duckdb-0.3.2.dev633)
 - DuckDB Client: Python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
Have to think about this what with segment trees and all, but until it is implemented, we should disable it.
