### ISSUE TITLE
Implement Chatterjee correlation

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#2840]
See https://arxiv.org/abs/1909.10140 for a discussion and formula. It seems to be a quite nice (interpretable, robust, efficient) metric for estimating correlation.

https://twitter.com/adad8m/status/1474754752193830912 has an animation that shows the metric.

**Comment by hannesmuehleisen** [comment]
Looks to me like we might be able to define this from SQL directly?

**Comment by mskyttner** [comment]
It seems there are [some recent updates](https://twitter.com/johnleibniz/status/1427669733034188806) with [code](https://sites.stat.washington.edu/people/fanghan/XIMCOR.R) for a revised variant of Chatterjee rank correlation that "overcome the “only one disadvantage” of Chatterjee’s rank correlation" according to [this paper](https://arxiv.org/pdf/2108.06828.pdf).

The abstract states that this variant provably achieves "... near-parametric efficiency in testing against Gaussian rotation alternatives. This is possible via incorporating many right nearest neighbors in constructing the correlation coefficients." 

![image](https://user-images.githubusercontent.com/1715840/147596218-2267c080-0310-47e8-9942-e5a249d0ff10.png)
