### ISSUE TITLE
Does support persistent UDF in SQL?

### ISSUE THREAD

**Issue by chenxi8611** [duckdb/duckdb#2849]
In BigQuery, I can use persistent UDF in SQL. It can be found in [BigQuery's docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_function_statement).
I am wondering it is possible in DuckDB.
I am currently benchmarking the difference between a native function, a c++ udf, and a macro, so I need to create a persistent UDF function.

**Comment by chenxi8611** [comment]
@mytherin -- Please check how I can use the follow persistent UDF in SQL.

I made a UDF function in C++ code as follows.

	duckdb::DBConfig config;
	config.maximum_threads = 1;
	duckdb::DuckDB db(nullptr, &config);
	duckdb::Connection con(db);
        con.CreateScalarFunction<int64_t, int64_t>("even_udf", &even_udf);

Then I would like to use it in python script as follows.

       con = duckdb.connect(database=':memory:')
       con.execute("CREATE TABLE sometable AS SELECT even_udf(x) as e FROM generate_series(1,1000000)")
       con.execute("SELECT SUM(e) FROM sometable")

Is it possible? How I can use persistent UDF function in SQL?
Thank you!

**Comment by Alex-Monahan** [comment]
Hello! SQL macros are possible and are persistent! Do the links below meet your use case?

[SQL Macro docs](https://duckdb.org/docs/sql/statements/create_macro)

[Macro github issue](https://github.com/duckdb/duckdb/pull/1129)

**Comment by chenxi8611** [comment]
@Alex-Monahan  Thank you for your answer
However, I would like to use a C++ UDF written in C++ code, not a macro function.

**Comment by Alex-Monahan** [comment]
Thanks for the clarification! 
Would the approach described here work?
[C++ UDF's](https://github.com/duckdb/duckdb/pull/712)

**Comment by chenxi8611** [comment]
Okay, I've checked it already. I think it is only possible to use it at same connection before close that connection.
What I want is persistent C++ UDF that can use in SQL.

**Comment by Alex-Monahan** [comment]
In your example, you pointed to an in memory DuckDB in your Python code (using :memory: instead of path/to/file.duckdb). If you refer to the same file-based DuckDB in both your C++ and Python code, does that work? 
Thanks for experimenting!

**Comment by chenxi8611** [comment]
Great, let me check it!

**Comment by chenxi8611** [comment]
@Alex-Monahan I've tested with a file-based DuckDB, but I still can't use persistent UDF.
This is my C++ code.

	duckdb::DBConfig config;
	config.maximum_threads = 1;
	config.access_mode = AccessMode::READ_WRITE;
	duckdb::DuckDB db("udf.duckdb", &config);
	duckdb::Connection con(db);
	con.CreateScalarFunction<int64_t, int64_t>("even_udf", &even_udf);

And this is my python code.

	udf_con = duckdb.connect(database="udf.duckdb", read_only=True)
	cursor = udf_con.cursor()
	cursor.execute("CREATE TABLE udf_tb AS SELECT even_udf(x) as e FROM generate_series(1,1000000)")
	cursor.execute("SELECT sum(e) FROM udf_tb")

**Comment by chenxi8611** [comment]
This is my C++ function code.

int64_t even_udf(int64_t x) {
    double value;
    if (x >= 0) {
        value = std::ceil(x);
    } else {
        value = std::ceil(-x);
        value = -value;
    }
    if (std::floor(value / 2) * 2 != value) {
        if (x >= 0) {
            return value += 1;
        }
        return value -= 1;
    }
    return (int64_t)value;
}

@Alex-Monahan Once just run it exactly as-is, can you let me know what result you got?

**Comment by Mytherin** [comment]
You cannot create a persistent UDF using only the C++ UDF API. Since this API takes in a function pointer, there is no way of persisting the actual function, as no source code or any other context required for running the function is passed in. This API is similar to the sqlite UDF API.

If you want to create a persistent function have a look at the [loadable extension demo](https://github.com/duckdb/duckdb/blob/master/test/extension/loadable_extension_demo.cpp). This will create an extension file (`.duckdb_extension`) that you can load using the `LOAD` command.

We should create a separate repository that has this example plus more documentation on how to compile and run this.
