### ISSUE TITLE
C API : duckdb_value_date pass on exception instead of returning error state

### ISSUE THREAD

**Issue by tenko** [duckdb/duckdb#2853]
#### What happens?
The C API function duckdb_value_date triggers an unhandled exception instead of returning an error state when passed an index to a column which is not a DATE type:
```
DB.Prepare('SELECT 1,2,3,?,DATE ''1992-09-20'',TIMESTAMP ''1992-09-20 11:30:00'';');
DB.BindString(1, 'True');
DB.ExecPrepared;
writeln('Date :  ' + DateToStr(DB.ValueAsDate(1,0)));
```
Triggers an unhandled exception:
```
An unhandled exception occurred at $00007FFEF5964F69:
EExternalException: External exception E06D7363
  $00007FFEF5964F69
  $00007FFEED756480
  $00007FFE91FE45B2
  $00007FFE922EA174
  $00007FFE922E8907
  $00007FFE922EB487
  $000000010001D90E  VALUEASDATE,  line 383 of duckdb.pas
  $0000000100001CAB  main,  line 25 of duckdtest.lpr
  $0000000100001E66
  $000000010000FF60
  $0000000100001710
  $00007FFEF7207034
  $00007FFEF8062651
```

#### To Reproduce
Source is FreePascal code.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1
 - DuckDB Client: Custom FreePascal code using the C-API

I has not been successful in building the Trunk and therefore have not tested this.

**Comment by wangfenjin** [comment]
@Mytherin I can work on this

**Comment by wangfenjin** [comment]
Hi @Mytherin , I check the code. If we don't implement the [cast_operators](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb/common/operator/cast_operators.hpp), it may throws exception. 

So I plan to catch in [here](https://github.com/duckdb/duckdb/blob/master/src/main/capi/value-c.cpp#L145), which will prevent all duckdb_value_* function to throw.

What do you think?

**Comment by Mytherin** [comment]
That sounds good to me.
