### ISSUE TITLE
DuckDB C interface and decimal support

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#2858]
#### What happens?
When querying a table with the `decimal` column, the query fails with `DuckDBError` but without any error message.

#### To Reproduce
Using the C Api run the following statements:

```c
CREATE TABLE test (dec DECIMAL(18, 4) NULL, value FLOAT NULL);

INSERT INTO test (dec, value) SELECT NULL, 10

SELECT * FROM test
```

The last `duckdb_query` returns `DuckDBError` without any error message. The column type for the first column is `DUCKDB_TYPE_INVALID`

#### Environment
 - OS: Windows 10
 - DuckDB Version: 0.3.1
 - DuckDB Client: C Api

**Comment by wangfenjin** [comment]
@Mytherin I'd like to work on this issue

**Comment by tenko** [comment]
I believe the "NUMERIC" column type (not documented) is also a DECIMAL type?
Got a similar error with the C Api and a NUMERIC column.

**Comment by Mytherin** [comment]
`NUMERIC` is an alias for `DECIMAL(18,3)`, indeed.

**Comment by sdmcallister** [comment]
Would casting to double be an temp workaround?

**Comment by Giorgi** [comment]
@Mytherin Is there any release available with this change?

**Comment by Mytherin** [comment]
Not yet, the next release will have it. I am also working on [a big extension to the C API in the context of the Julia integration](https://github.com/Mytherin/duckdb/blob/julia/src/include/duckdb.h) which will allow for faster data access, faster data appending, as well as correctly supporting all data types that DuckDB supports. This will likely also make it into the next release.
