### ISSUE TITLE
Table is not created even though schema name is passed

### ISSUE THREAD

**Issue by renardeinside** [duckdb/duckdb#2872]
#### What happens?
I would like to create a new arrow table in a separate, existing schema. My code looks like this:

```

self._storage = duckdb.connect(database='/tmp/some-db', read_only=False)
schema = descriptor.path[0].decode("utf-8")
table_name = descriptor.path[1].decode("utf-8")

self._storage.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

table = reader.read_all()
relation = self._storage.from_arrow_table(table)
relation.create(f"{schema}.{table_name}") # I expect this one should write data into a table {table_name} from {schema}
```

However, the table is created in the "main" schema:

```
db.execute("select * from duckdb_tables()").fetchdf()
  schema_name  ...                                                sql
0        main  ...  CREATE TABLE "test_ns.test_asset"(s VARCHAR, i...
```

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

#### Environment (please complete the following information):
 - OS: [e.g. iOS] MaOS
 - DuckDB Version: [e.g. 22] 0.3.1
 - DuckDB Client: [e.g. Python] Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
The `schema.table` syntax is simply not supported yet. The relational API overall is subject to changes, and we are happy to include support for setting the schema there in the next iteration. CC @pdet
