### ISSUE TITLE
Parser Error: parser error : syntax error at or near "PRIMARY"

### ISSUE THREAD

**Issue by NilsDM** [duckdb/duckdb#2878]
#### What happens?
I think I found a similar issue to this one [#2622 ](https://github.com/duckdb/duckdb/issues/2622
)
When setting primary keys using dm, and then passing the table into duckdb, a parser error occurs which was not present in duckdb 0.2.7 but has been since at least 0.3.1
#### To Reproduce
Reprex:
``` r
my_cars <- mtcars
my_cars$make_model <- rownames(mtcars)
con <- DBI::dbConnect(duckdb::duckdb(), "my_test.duckdb")
dm <- dm::dm(my_cars)
dm_primary_key <- dm::dm_add_pk(dm, my_cars, make_model)
dm::dm_examine_constraints(dm_primary_key)
#> i All constraints satisfied.
db_dm <- dm::copy_dm_to(con, dm_primary_key,
                        temporary = FALSE,
                        set_key_constraints = TRUE)
#> Error in .local(conn, statement, ...): duckdb_prepare_R: Failed to prepare query CREATE  TABLE "my_cars" AS SELECT #1::DOUBLE "mpg",#2::DOUBLE "cyl",#3::DOUBLE "disp",#4::DOUBLE "hp",#5::DOUBLE "drat",#6::DOUBLE "wt",#7::DOUBLE "qsec",#8::DOUBLE "vs",#9::DOUBLE "am",#10::DOUBLE "gear",#11::DOUBLE "carb",#12::STRING NOT NULL,
#> PRIMARY KEY ("make_model") "make_model" FROM _duckdb_write_view_dtjzpiapjq
#> Error: Parser Error: parser error : syntax error at or near "PRIMARY"
#> LINE 2: PRIMARY KEY ("make_model") "make_model" FROM _duckdb_write_view_dtjzpiapjq...
#>         ^
```

<sup>Created on 2022-01-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1.1
 - DuckDB Client: R

**Comment by hannesmuehleisen** [comment]
The table definition seems to be broken. From the error message:
```SQL
CREATE  TABLE "my_cars" AS 
SELECT #1::DOUBLE "mpg"
-- [...]
#11::DOUBLE "carb",
#12::STRING NOT NULL,
PRIMARY KEY ("make_model") "make_model" FROM ...
```

I think there is an alias (`make_model`) missing after the last column (`#12`) and there cannot be a trailing comma. Can you check your query generation?

**Comment by NilsDM** [comment]
Hi Hannes, thanks for your quick response. I think this is what you're asking for:

I've modified the reprex to show that the column names are correct prior to the dm_copy_to() call. 
Setting set_key_constraints = FALSE, does not trigger the parser error, and maintains the correct alias for the last column but as you can see the values in that column are now Boolean's instead of strings. Let me know if this helps, if you need anything else, or if I've misinterpreted what you are asking for. All the best.


``` r
my_cars <- mtcars
my_cars$make_model <- rownames(mtcars)
con <- DBI::dbConnect(duckdb::duckdb(), "my_test.duckdb")
dm <- dm::dm(my_cars)
dm_primary_key <- dm::dm_add_pk(dm, my_cars, make_model)
dm::dm_examine_constraints(dm_primary_key) 
#> i All constraints satisfied.
head(dm_primary_key$my_cars, 5)
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#>                          make_model
#> Mazda RX4                 Mazda RX4
#> Mazda RX4 Wag         Mazda RX4 Wag
#> Datsun 710               Datsun 710
#> Hornet 4 Drive       Hornet 4 Drive
#> Hornet Sportabout Hornet Sportabout
db_dm <- dm::copy_dm_to(con, dm_primary_key,
                        temporary = FALSE,
                        set_key_constraints = FALSE)
DBI::dbGetQuery(con, "SELECT * from my_cars 
                      Limit 5")
#>    mpg cyl disp  hp drat    wt  qsec vs am gear carb make_model
#> 1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4       TRUE
#> 2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4       TRUE
#> 3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1       TRUE
#> 4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1       TRUE
#> 5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2       TRUE
```

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hannesmuehleisen** [comment]
What exactly is the failing query? It helps if I don't have to install R packages etc. to see what's going on.

**Comment by NilsDM** [comment]
It's not technically a query that's failing, it's the function call:

db_dm <- dm::copy_dm_to(con, dm_primary_key,
                        temporary = FALSE,
                        set_key_constraints = FALSE)

That's resulting in the parser error above in my original post. This error is occurring when trying to pass the initial data into the database. This issue was not present when I was initially working on my project in the summer under duckdb version 0.2.7, and when I change the database backend to sqlite in the code above, the error does not occur and the database is constructed correctly. 

I'm unable to simplify the code above any further. But you would be able to reconstruct the error with only the packages DBI and dm. the mtcars dataset is built into R. This was the most minimal reproducible example I could make.

**Comment by NilsDM** [comment]
Hi Hannes, just following up to see if you've had a chance to look into what's causing this error? Thanks.

**Comment by hannesmuehleisen** [comment]
One tip: When creating a DuckDB connection like so
`con <- DBI::dbConnect(duckdb::duckdb(), debug=TRUE)`
it dumps all the SQL that it gets sent. In this case I see that it tries to run the following query:

```SQL
CREATE  TABLE "my_cars" AS SELECT #1::DOUBLE "mpg",[...]
PRIMARY KEY ("make_model") "make_model" FROM _duckdb_write_view_nxkplzosgq
```
That syntax is unsupported, you can't set a primary key in a table creation from query result like that. 
Now to figure out who creates it. My guess would be DBI or dbplyr?
