### ISSUE TITLE
Install R package duckdb from GitHub fails

### ISSUE THREAD

**Issue by HanOostdijk** [duckdb/duckdb#2879]
#### What happens?
Install R package duckdb from GitHub fails: no DLL was created (details in attachment)

#### To Reproduce
install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)

#### Environment (please complete the following information):
 sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

#### Before Submitting

- [ X] **Have you tried this on the latest `master` branch?**
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`

- [ X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Today I tried to install the latest version. The previous versie 0.3.2-dev1 from 2021-11-16 installed from GitHub without problems.
Compiler/linker messages in attachment:
[install_R_package_duckdb_2022-01-07.txt](https://github.com/duckdb/duckdb/files/7828755/install_R_package_duckdb_2022-01-07.txt)

**Comment by hannesmuehleisen** [comment]
Looks like we are missing the winsock linking flags

**Comment by HanOostdijk** [comment]
This is not something that I can easily repair myself, I am afraid (?)

The [install page](https://duckdb.org/docs/installation/) calls installing the R package from GitHub the **Bleeding Edge**.
However file timestamps suggest that the code in the `tar.gz` file is from 04dec2021.
So when committing changes to 'core duckdb' there is no (automatic) build of the `tar.gz` file for the R package on GitHub?
Does the [Command Line Interface](https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_cli-windows-amd64.zip) always contains the latest changes?

**Comment by hannesmuehleisen** [comment]
Yes, sorry for that, we had to disable the bleeding edge upload because it caused too many build failures. Will update the website.

**Comment by HanOostdijk** [comment]
See that a new version has landed on CRAN. Thanks!

**Comment by alanpaulkwan** [comment]
Is it curerntly possible to install bleeding edge R? The below command definitely does not work. 

install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)

**Comment by rfhb** [comment]
@alanpaulkwan Yes, use this command in `R`: 

```
install.packages("https://github.com/duckdb/duckdb/releases/latest/download/duckdb_r_src.tar.gz", repos = NULL)
```

**Comment by hannes** [comment]
We currently recommend
`install.packages('duckdb', repos=c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))`
