### ISSUE TITLE
Expose python's register_arrow to C API

### ISSUE THREAD

**Issue by cnuernber** [duckdb/duckdb#2881]
#### What happens?
The python API for register arrow appears to be missing from the [C api](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb.h).  Would it be possible and perhaps not too much work to expose it?

**Comment by hannesmuehleisen** [comment]
I've hacked together a basic example for this using C++, something similar should be possible with the C API, too. Does this help?

https://github.com/hannesmuehleisen/duckdb/blob/cpparrowexample/examples/c%2B%2B-arrow/main.cpp

**Comment by hannesmuehleisen** [comment]
Maybe @pdet can add some more examples on this

**Comment by cnuernber** [comment]
All of this helps.  I am using the C api from Java so I would need to expose something without dropping into C++ but I can see how these would help.  I guess I am looking for a way to use an arrow file in streaming format as a datasource similar to how parquet works or perhaps directly passing arrow data via pointer but a file would be more ideal as the engine could mmap it.
