### ISSUE TITLE
bug: `parquet_schema` table function returns a blank `logical_type`

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#2883]
#### What happens?

Hey folks! When I run a query like `SELECT * FROM parquet_schema('file.parquet')` the field `logical_type` is empty for all fields. The `converted_type` is usually all `UTF8`, which does not give me the information I need.

I am sure DuckDB is aware of these logical types when querying parquet files since it correctly reads timestamp fields and displays them in the interface I'm building. So I suspect the fix might be straightforward.

#### To Reproduce

Utilizing the CLI, run

```sql
COPY(SELECT now() as ts, 10 as number, 'hello' as str) TO './test.parquet'  (FORMAT 'parquet');
SELECT name, logical_type FROM parquet_schema('./test.parquet');
```

You will likely see this result set:

```
┌───────────────┬──────────────┐
│     name      │ logical_type │
├───────────────┼──────────────┤
│ duckdb_schema │              │
│ ts            │              │
│ number        │              │
│ str           │              │
└───────────────┴──────────────┘
```

The `logical_type` column is empty.

#### Environment (please complete the following information):
 - OS: Mac 12.1
 - DuckDB Version: 0.3.1 & bleeding edge
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

Have you tried this on the latest master? This seems to work as intended on the latest master:

```sql
┌───────────────┬──────────────────┬────────────────────────────────────────────────────────────────────────────────────┐
│     name      │  converted_type  │                                    logical_type                                    │
├───────────────┼──────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ duckdb_schema │ UTF8             │ NULL                                                                               │
│ ts            │ TIMESTAMP_MICROS │ TimestampType(isAdjustedToUTC=1, unit=TimeUnit(MILLIS=<null>, MICROS=MicroSecon... │
│ number        │ INT_32           │ NULL                                                                               │
│ str           │ UTF8             │ NULL                                                                               │
└───────────────┴──────────────────┴────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by hamilton** [comment]
Last night, when I wrote the issue, I had tried it on `v0.3.2-dev479 8a0e93080`, which is the bleeding edge download from [the duckdb site](https://duckdb.org/docs/installation/). I'll try it on the latest master. Odd that it'd work on `master` but not on the bleeding edge download.

**Comment by hamilton** [comment]
Just built with `v0.3.2-dev950 27536134b` & tried it out, and it appears to work. Thanks for the suggestion ~ sometimes a single dev version increment is all it takes.

`dev479` was built Sat Dec 4, so I'm assuming that your PR #2869 might have somehow fixed this.

**Comment by makalaaneesh** [comment]
Hey @Mytherin, slightly related question about the parquet schema output: Why does the logical type of column "str" not indicate that it is of string type. I created this same table and wrote it as parquet using pyarrow, tried reading the parquet schema using duckdb, and got "StringType()" as the logical type for column "str" (which doesn't happen when you write parquet using duck db, i.e. https://github.com/duckdb/duckdb/issues/2883#issuecomment-1007972753).

```
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

df = pd.DataFrame({"ts" : [pd.Timestamp.now()], "number" :[10], "str": ['hello']})
pq.write_table(pa.Table.from_pandas(df), "test1.parquet")

SELECT name, type, converted_type, logical_type FROM parquet_schema('test1.parquet');

┌────────┬────────────┬──────────────────┬────────────────────────────────────────────────────────────────────────────────────┐
│  name  │    type    │  converted_type  │                                    logical_type                                    │
├────────┼────────────┼──────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ schema │ BOOLEAN    │ UTF8             │                                                                                    │
│ ts     │ INT64      │ TIMESTAMP_MICROS │ TimestampType(isAdjustedToUTC=0, unit=TimeUnit(MILLIS=<null>, MICROS=MicroSecon... │
│ number │ INT64      │ UTF8             │                                                                                    │
│ str    │ BYTE_ARRAY │ UTF8             │ StringType()                                                                       │
└────────┴────────────┴──────────────────┴────────────────────────────────────────────────────────────────────────────────────┘
```

From what I understand from [here](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#compatibility), `converted_type` is deprecated, and parquet writers are expected to write to `logical_type`, which duckdb is evidently doing (as seen with the ts column). So is this a bug that "StringType()" doesn't show up as the logical type for column str, or am I missing something?

**Comment by Mytherin** [comment]
We should probably write the StringType logical type there as well, although we haven’t yet found a reader for which this matters.

**Comment by makalaaneesh** [comment]
Ah, ok so I'm guessing readers still just use `type=BYTE_ARRAY and converted_type=UTF8` to interpret it as a String. 
Thanks, that makes sense!
