### ISSUE TITLE
Feature: Add support for Excel text format

### ISSUE THREAD

**Issue by chenxi8611** [duckdb/duckdb#2884]
Hi @Mytherin,

Excel provides a very compact way to render various numeric and date objects as strings via its `TEXT` function. 

| Raw    | Text Format                               | Result    | 
|--------|---------------------------------------|-----------|
| 123.4  |  $#,##0.00_);($#,##0.00)0 | $123.40   | 
| -123.4 | $#,##0.00_);($#,##0.00)0 | ($123.40) | 

I would like to add support for this string-formatting function, as I think it can be incredibly useful and a nice complement to the existing `format(format, parameters...)`, `printf(format, parameters...)`, and `strftime(date, format)` functions. Could you please let me know if this is something that I can go ahead and implement? I was thinking of using the function name of `TEXT(val, fmt)` or `EXCEL_TEXT(val, fmt)`. Do you have any feedback on the above?

**Comment by Mytherin** [comment]
Sure, that seems like a good idea. Happy to review a PR!
