### ISSUE TITLE
globbing unsupported for s3

### ISSUE THREAD

**Issue by seandatasci** [duckdb/duckdb#2887]
#### What happens?
When globbing s3 dirs no file matching pattern error

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
try to glob an s3 dir and load files into duckdb

#### Environment (please complete the following information):
 - linux
 - DuckDB Version: [e.g. 22]
 - 0.3.1
 - DuckDB Client: [e.g. Python]
 - Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
yes

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
yes

**Comment by arjenpdevries** [comment]
Possible workaround: globbing may work if you use the Python `s3fs` library?

https://stackoverflow.com/a/69568591/2127435

**Comment by Alex-Monahan** [comment]
You may also be able to use Apache Arrow to register your dataset, then query the Arrow file in DuckDB! 
[PyArrow S3 docs](https://arrow.apache.org/docs/python/filesystems.html)
[DuckDB and Arrow Blog](https://duckdb.org/2021/12/03/duck-arrow.html)

**Comment by hannesmuehleisen** [comment]
This is indeed currently unsupported.

**Comment by samansmink** [comment]
Would certainly be a nice feature to have, I think I'll have some time to look at it this week!

Shouldn't be too hard to make it work as the [ListObjectsV2](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) api call has a prefix parameter that allows filtering results

**Comment by samansmink** [comment]
PR currently open fixing this: https://github.com/duckdb/duckdb/pull/3225
