### ISSUE TITLE
how to set version number when compile the source

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2889]
#### What happens?
I got
```
~ $ duckdb
v0.0.1-dev0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D
```
#### To Reproduce
Termux team:
https://github.com/termux/termux-packages/pull/8322

windows7:
unzip the source
cmake -s D:\duckdb-master -b d:\duck 
cd d:\duck
make
duckdb
#### Environment (please complete the following information):
 - OS: [e.g. iOS] Android termux/windows
 - DuckDB Version: [e.g. 22] 0.31/master
 - DuckDB Client: [e.g. Python]CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
If you build from a git clone and not a zip file it should set the version correctly.
