### ISSUE TITLE
how to find the reserved words list

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2891]
I tried to name a column alias to including and failed. 
I want to know what words is not reserved. 
```
D select 'am',12345 including; 
Error: Parser Error: syntax error at or near "including"
LINE 1: select 'am',12345 including;
                          ^
D select 'am',12345 includin;
┌────┬──────────┐
│ am │ includin │
├────┼──────────┤
│ am │ 12345    │
└────┴──────────┘
```

**Comment by Alex-Monahan** [comment]
A workaround is to wrap your column name alias in double quotes.

**Comment by Alex-Monahan** [comment]
Also, here are the reserved keywords!
[Lists of keywords for parser](https://github.com/duckdb/duckdb/tree/ff7f24fd8e3128d94371827523dae85ebaf58713/third_party/libpg_query/grammar/keywords)

**Comment by l1t1** [comment]
thank you

> Also, here are the reserved keywords! [Lists of keywords for parser](https://github.com/duckdb/duckdb/tree/ff7f24fd8e3128d94371827523dae85ebaf58713/third_party/libpg_query/grammar/keywords)
I found word `including` in the unreserved_keywords.list, not in the column_name_keywords.
