### ISSUE TITLE
Misleading comment in tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp

### ISSUE THREAD

**Issue by zippond** [duckdb/duckdb#2897]
I see following comment for sqlite3_prepare_v2()
`/* In SQLite this function compiles the query into VDBE bytecode,
 * in the implementation it currently executes the query */
// TODO: prepare the statement instead of executing right away
int sqlite3_prepare_v2(sqlite3 *db,           /* Database handle */`

However, it seems this proc doesn't execute the query anymore. 
I checked the history, it looks like the "TODO" has been completed in PR #373. Maybe someone could fix the comment to avoid misleading.

**Comment by hannesmuehleisen** [comment]
You could send a Pull Request that fixes this, too?

**Comment by zippond** [comment]
Sure. Maybe I could include this in a real fix later :-).
