### ISSUE TITLE
Parquet reader creates ColumnReader objects that are never used

### ISSUE THREAD

**Issue by yingsu00** [duckdb/duckdb#2898]
When a query only reads a few columns in the table, only the output columns and columns with filters need to read. However DuckDB creates a ColumnReader for every column. This is not necessary and not good for performance for wide tables, since the readers need to be constructed for every split Prestissimo sends. For example, the following query just needs to read one column partkey:
```
select count(*) from lineitem where partkey <20000000;
```
But 16 ColumnReaders were constructed:

![Screen Shot 2022-01-09 at 11 15 13 PM](https://user-images.githubusercontent.com/33299678/148729659-a9ebb14a-e9df-4679-b7af-c68308c27a1a.png)

**Comment by hannesmuehleisen** [comment]
This is correct, we don't have to create those readers. Happy to review a PR!

**Comment by ccfelius** [comment]
I want to work on this issue :)
