### ISSUE TITLE
Query 9 and 21 slow when testing TCP-H-SF10 workload with parquet

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#2902]
first I am not sure if it is a bug or it is the expected performance

I am using duckdb 0.31 , Windows 10,  only parquet files, no import, I have tried TPCH queries with SF 10, here is the results

Query 9 and 21 seems a bit odd ? is this expected 

TPCH | DuckDB

'--Query01 | 5.393445
'--Query02 | 0.843777
'--Query03 | 3.492776
'--Query04 | 4.707213
'--Query05 | 3.883179
'--Query06 | 2.845355
'--Query07 | 6.794438
'--Query08 | 4.472477
'--Query09 | 27.101742
'--Query10 | 3.932361
'--Query11 | 0.613395
'--Query12 | 4.853902
'--Query13 | 3.271795
'--Query14 | 3.295735
'--Query15 | 6.634146
'--Query16 | 1.020363
'--Query17 | 5.412079
'--Query18 | 6.935358
'--Query19 | 4.846258
'--Query20 | 3.496862
'--Query21 | 12.389197
'--Query22 | 1.157418

here is the script for testing, sorry, I know it is very basic :)
https://github.com/djouallah/Testing_BI_Engine/blob/main/duckdb.py

and here is the parquet files
https://drive.google.com/drive/folders/1mZC3NuPBZC4mjP3_kH18c9fLrv8ME7RU?usp=sharing

thank you

**Comment by hannesmuehleisen** [comment]
This is expected, those two queries are also slower in our benchmarks.

**Comment by l1t1** [comment]
[my test result is similar](https://github.com/duckdb/duckdb/issues/2874)
