### ISSUE TITLE
UTF-8 with BOM not working properly

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb#2908]
When you  load a `test.csv` file with UTF-8 BOM into table
```
D CREATE TABLE test AS SELECT * FROM read_csv_auto('test.csv');
D SELECT * FROM test;
┌─────┬────────┐
│ ﻿id │  name  │
├─────┼────────┤
│ 1   │ Mark   │
│ 2   │ Hannes │
└─────┴────────┘
```
everything seems to fine until you want to select the first column:
```
D SELECT id FROM test;
Error: Binder Error: Referenced column "id" not found in FROM clause!
Candidate bindings: "test.﻿ id", "test.name"
```
and then you notice that there is one extra character in the name of the first column. The file is working without a problem if you change the encoding of the file to UTF-8.

**Comment by arjenpdevries** [comment]
For convenience:
https://unicode.org/faq/utf_bom.html#BOM

**Comment by hawkfish** [comment]
Related to #2968 and text encoding.  At some point we probably want to separate text scanning from the rest of the CSV parser.

**Comment by hawkfish** [comment]
State variables not being reset before use...
