### ISSUE TITLE
M1 Mac overall performance

### ISSUE THREAD

**Issue by alanpaulkwan** [duckdb/duckdb#2909]
**Edit: overall I think the basic issue is that the M1 performance is lower. I am surprised given the vignette about fast sorting via DuckDB and M1. Is there a scientific computing package I need to install like OpenMP or something **

The first is a query that takes forever, though it shouldn't. Over email @hannesmuehleisen noted that its probably the wrong join order. In Clickhouse it takes less than a second, here 92387 vs 100k rows takes 38 seconds on my M1 

@hannesmuehleisen UPDATE: This is an M1 and possibly more broadly an OS X issue(Python, R both x86 and arm64, command line all slow). Interestingly Docker x86 Rstudio outperforms Mac bare metal.

#### To Reproduce
Get an M1 Mac and run the following query, which is a baseline query for merging stocks with their identifiers. Possibly might replicate on OS X with Intel. 

### Files/code

Data : miniature and larger, are here.

https://www.dropbox.com/sh/ajsv1e7ksc7hivd/AADy9xZDOQNOm7utloJ3X6Iya?dl=0

```sql

  select a.permno,date,ret,a.hexcd,b.permno as b_permno 
       from 'crsp_msf_2020.parquet' as a
           left join 'crsp_dsenames.parquet' as b
              on a.permno=b.permno
            where a.date between namedt and nameendt

# bigger version
  select a.permno,date,ret,a.hexcd,b.permno as b_permno 
       from 'crsp_msf.parquet' as a
           left join 'crsp_dsenames.parquet' as b
              on a.permno=b.permno
            where a.date between namedt and nameendt

```
```

**Comment by hannesmuehleisen** [comment]
Maybe @lnkuiper can have a look?

**Comment by alanpaulkwan** [comment]
I presume this fixes it. https://github.com/duckdb/duckdb/issues/3595
