### ISSUE TITLE
Support pandas nullable boolean type

### ISSUE THREAD

**Issue by jlorince** [duckdb/duckdb#2910]
#### What happens?
Pandas dataframes containing any columns of the (experimental) [nullable boolean type ](https://pandas.pydata.org/pandas-docs/stable/user_guide/boolean.html) will fail to register with duckdb.

#### To Reproduce

```
In [3]: df1 = pandas.DataFrame({"foo": [True, None, False]})
   ...: df2 = pandas.DataFrame({"foo": [True, None, False]}, dtype="boolean")

In [4]: df1.dtypes
Out[4]:
foo    object
dtype: object

In [5]: df2.dtypes
Out[5]:
foo    boolean
dtype: object

In [6]: con = duckdb.connect(database=":memory:", read_only=False)

In [7]: con.register("df1", df1)
Out[7]: <duckdb.DuckDBPyConnection at 0x127c35530>

In [8]: con.register("df2", df2)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-e94dc73d8e5d> in <module>
----> 1 con.register("df2", df2)

RuntimeError: unsupported python type boolean
```

#### Environment (please complete the following information):
 - OS: [e.g. iOS]: Mac OS
 - DuckDB Version: [e.g. 22]: 0.3.1
 - DuckDB Client: [e.g. Python]: python

**Comment by chukarsten** [comment]
My team could really use this support, any idea where we can start out helping to get it done?

**Comment by Mytherin** [comment]
For preferential support on issues you can contact [DuckDB Labs](https://duckdblabs.com). If you want to provide a code contribution instead you could have a look at the Python package source code, happy to review a PR as well!
