### ISSUE TITLE
array_slice returns empty when the end index is greater than the length of array

### ISSUE THREAD

**Issue by makalaaneesh** [duckdb/duckdb#2916]
#### What happens?
`array_slice` returns empty when the end index is greater than the length of array. Other implementations of array slicing (like in python, postgres) just slice till the end of the array. 

#### To Reproduce
In duckdb, 
```
D SELECT array_slice([1,2,3],0,5);
┌────────────────────────────────────────┐
│ array_slice(list_value(1, 2, 3), 0, 5) │
├────────────────────────────────────────┤
│                                        │
└────────────────────────────────────────┘
```
In postgres, 
```
postgres=# SELECT (array[1,2,3])[0:5];
  array
---------
 {1,2,3}
(1 row)
```
Is this intentional? If not, I'd like to pick up the fix for this!

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: master v0.3.2-dev984 a218b623e
 - DuckDB Client: [e.g. Python]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
I can take this.

**Comment by makalaaneesh** [comment]
@hawkfish In case you haven't already started, is it ok if I pick this, instead? 
I was already reading through the relevant code, and think I know how to fix it 🙂

**Comment by hawkfish** [comment]
> @hawkfish In case you haven't already started, is it ok if I pick this, instead?
> I was already reading through the relevant code, and think I know how to fix it 🙂

Go for it - happy to review!  Just make sure it matches PG semantics.

**Comment by makalaaneesh** [comment]
@hawkfish So, I ran into some more discrepancies b/w postgres and duckdb wrt array slicing. Wanted your inputs on how these should be addressed!

1. The begin and end bounds in postgres are both inclusive, whereas the end bound in duckdb is exclusive. 
2. In [postgres](https://www.postgresql.org/docs/9.1/arrays.html), "An array slice expression likewise yields null if the array itself or any of the subscript expressions are null". In duckdb this doesn't happen. `SELECT array_slice([1,2,3], 1,NULL);` returns `[2,3]`. It looks like `NULL` is just interpreted as the min/max bound(depending upon if it's used in begin or end).
3. in [postgres](https://www.postgresql.org/docs/9.1/arrays.html), "If the requested slice partially overlaps the array bounds, then it is silently reduced to just the overlapping region instead of returning null". This github issue partially addresses this discrepancy, but there's another one: negative indexing. duckdb supports negative indexing (i.e. -2 means second from the last), but in postgres, the negative index is interpreted as is. So, in postgres, `SELECT (array[1,2,3])[-1:3];` returns [1,2,3] because [-1:3] is reduced to the overlapping region of [1:3].
4. postgres has 1-based indexing whereas duckdb has 0-based, but looks like there's a separate [issue](https://github.com/duckdb/duckdb/issues/2575) to discuss that aspect.

**Comment by makalaaneesh** [comment]
@hawkfish The main issue has been fixed. 
> I think we have to maintain our historical/Python semantics.

If you mean we don't have to address any of the other differences mentioned in https://github.com/duckdb/duckdb/issues/2916#issuecomment-1011393281, then yes, we're good to close!
