### ISSUE TITLE
Feature request: Flatten for nested arrays

### ISSUE THREAD

**Issue by pgabry** [duckdb/duckdb#2922]
In Big Query there is a function array_concat_agg that aggregates array fields by concatenating the arrays. In Snowflake there is a flatten function that can unnest nested arrays into single array. I am looking for similar functionality in duckdb. 

`select flatten([[1, 2], [2, 3], [4, 5]]` would return `[1, 2, 2, 3, 4, 5]`
I would also need a distinct option:
`select flatten(DISTINCT [[1, 2], [2, 3], [4, 5]]` would return `[1, 2, 3, 4, 5]`

Alternatively an equivalent to array_concat_agg from the Big Query would be sufficient.

**Comment by usurai** [comment]
Wanna ask a silly question. Does the function just flatten the nested array by one level or it flattens arbitrary levels of nested array into the one-dimensional array? 
E.g., what's does `SELECT flatten([[[1], [2, 3]],[[4,5], [6, 7, 8]]]);` returns? Thanks.

**Comment by hawkfish** [comment]
> Wanna ask a silly question. Does the function just flatten the nested array by one level or it flattens arbitrary levels of nested array into the one-dimensional array?
> E.g., what's does `SELECT flatten([[[1], [2, 3]],[[4,5], [6, 7, 8]]]);` returns? Thanks.

Good question. [The docs are silent](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_concat_agg)

**Comment by pgabry** [comment]
> Wanna ask a silly question. Does the function just flatten the nested array by one level or it flattens arbitrary levels of nested array into the one-dimensional array? 
> 
> E.g., what's does `SELECT flatten([[[1], [2, 3]],[[4,5], [6, 7, 8]]]);` returns? Thanks.

Traditionally it is one level.

**Comment by usurai** [comment]
Hi guys, I opened a PR trying to implement `flatten `(without `DISTINCT`).
Regarding `select flatten(DISTINCT [[1, 2], [2, 3], [4, 5]])`, I have two questions that need to discuss:
1. How to pass the `DISTINCT` to the function. 
Here `DISTINCT` is like a config argument. I haven't seen functions in DuckDB has argument used as config. If we do support this `flatten(DISTINCT, list)` style, the `DISTINCT` will be... a constant vector?
My thought on this is that we can just use another function name, e.g `flatten_distinct`, this might be easier.
Moreover, we can decouple them: Just add another list function `distinct`, and `distinct(flatten(list))`.

2. The implementation of `DISTINCT`
To implement, I want to maintain a hash table of elements that have been added to result, to deduplicate when concatenating the lists. This gives O(n) time complexity. But will limit the supported type as [Hash](https://github.com/duckdb/duckdb/blob/bd14023713cc7cd11bf7f865c7135e17397343b6/src/common/types/value.cpp#L1160) only supports part of the types.
Another approach is to compare the naively comparing the elements, which is O(n^2).

**Comment by aryann** [comment]
> Hi guys, I opened a PR trying to implement `flatten`(without `DISTINCT`). Regarding `select flatten(DISTINCT [[1, 2], [2, 3], [4, 5]])`, I have two questions that need to discuss:
> 
> 1. How to pass the `DISTINCT` to the function.
>    Here `DISTINCT` is like a config argument. I haven't seen functions in DuckDB has argument used as config. If we do support this `flatten(DISTINCT, list)` style, the `DISTINCT` will be... a constant vector?
>    My thought on this is that we can just use another function name, e.g `flatten_distinct`, this might be easier.
>    Moreover, we can decouple them: Just add another list function `distinct`, and `distinct(flatten(list))`.
> 2. The implementation of `DISTINCT`
>    To implement, I want to maintain a hash table of elements that have been added to result, to deduplicate when concatenating the lists. This gives O(n) time complexity. But will limit the supported type as [Hash](https://github.com/duckdb/duckdb/blob/bd14023713cc7cd11bf7f865c7135e17397343b6/src/common/types/value.cpp#L1160) only supports part of the types.
>    Another approach is to compare the naively comparing the elements, which is O(n^2).

I'll attempt to answer your first question. Disclaimer: I'm fairly new to the codebase, so please take what I say with a grain of salt.

I think you should support `flatten(DISTINCT list)` as that syntax is more conventional. The grammar already has support for the DISTINCT keyword on function calls: https://github.com/duckdb/duckdb/blob/e252305418ef420d3989a63afc9ec3f570db3980/third_party/libpg_query/grammar/statements/select.y#L2361

There should be an `agg_distinct` field in the data structure that represents the function call once the SQL text is parsed. Here's some code that references this field: https://github.com/duckdb/duckdb/blob/e252305418ef420d3989a63afc9ec3f570db3980/src/parser/transform/expression/transform_function.cpp#L114

**Comment by dmpetrov** [comment]
Based on my understanding, FLATTEN in Snowflake is similar to UNNEST in duckdb and not directly related to the problem described above.

If sizes of the array are known in advance, UNNEST might be enough with DISTINCT (unique id is required):
```sql
CREATE TABLE test (id INT, val INT[][])

INSERT INTO test VALUES (1, [[1, 2], [2, 3]])
INSERT INTO test VALUES (2, [[5, 6], [6, 5]])

SELECT id, list(DISTINCT v2)
FROM (
    SELECT *, UNNEST(v1) AS v2
    FROM (
        SELECT *, UNNEST(val) AS v1
        FROM test
    )
) 
GROUP BY id
```

```
Initial table:
1, [[1, 2], [2, 3]]
2, [[5, 6], [6, 5]]

Result:
1, [1, 2, 3]
2, [5, 6]
```

If the size of the table is unknown, yeah, ARRAY_CONCAT_AGG is needed. It might worth to rename the issue to FR for ARRAY_CONCAT_AGG.

**Comment by taniabogatsch** [comment]
Hey @pgabry. There has been some recent work to enhance the list function support in DuckDB. For example this now works.
```sql
CREATE TABLE test (id INT, val INT[][]);
INSERT INTO test VALUES (1, [[1, 2], [2, 3]]);
INSERT INTO test VALUES (2, [[5, 6], [6, 5], [5, 7], [13, 9]]);
INSERT INTO test VALUES (3, [1, 1, 1, 2, 3, 3]);
SELECT list_distinct(flatten(val)) FROM test;
┌─────────────────────────────┐
│ list_distinct(flatten(val)) │
├─────────────────────────────┤
│ [3, 2, 1]                   │
│ [9, 13, 7, 6, 5]            │
│ [3, 2, 1]                   │
└─────────────────────────────┘
```

There is also the `list_sort` function, which you might need (`list_distinct` is not order-preserving at the moment).
Here you can find an overview of the currently supported list functions (maybe also check out the list lambda and list aggregate stuff). 😄

The approach suggested by @dmpetrov provides some workaround using `UNNEST` and is related to other issues/lateral joins. I will close this issue because the originally requested feature now exists. Any progress on the `UNNEST` will be tracked in #4115.
