### ISSUE TITLE
Filtering on column when working with pyarrow reads more data than necessary

### ISSUE THREAD

**Issue by phbender** [duckdb/duckdb#2934]
I have a dummy dataset whith a couple of random colunms, but also `year`, `month` and `city`.

This dataset is stored on my disk, partitioned along the three columns mentiones before. This looks for example like this:

`synth/year=2020/month=4/city=Karlsruhe/6a260e3e455f4b05b0cf7b4c361de6be.parquet`

I query this dataset like this:

```python
import pyarrow.dataset as ds
import duckdb

data_set = ds.dataset(path, partitioning="hive")
quack = duckdb.arrow(data_set)
res = quack.query("tbl", "SELECT avg(col_55) as avg, count(*) as num_records, city FROM tbl WHERE col_55 > col_44 AND city='Karlsruhe' GROUP BY city")  
```

This query works and I think the result is correct.

However, I was wondering why especially with remote files (using `s3fs`) it takes really long although the query is only supposed to touch 10% or so of the files since I have `city` in the partitioning as well as in the `WHERE` clause of the query.

So I ran my query with `strace`:

`$ strace -f -t -e trace=file my-command`

The result was interesting:

* I had `stat` calls on all of the files (which I expect)
* But apart from that, I also had `openat` calls on more files than just the `city=Karlsruhe` ones, *but not on all of them*. From the 10 cities I have, only *Berlin* and *Braunschweig* have been read (and there, not all parquet files,  only half of them), plus *Karlsruhe*, of course.

I would be interested what the expectation is and if there is a way to really load (remote) data on demand, and the demand is determined by DuckDB based on the query.

In case this question is interesting I would be happy to share more material.

**Comment by hannesmuehleisen** [comment]
We push all filters to Arrow, if they read more files than required that's more an Arrow issue I would think?

**Comment by phbender** [comment]
@hannesmuehleisen yes that's absolutely possible. Due to [the blogpost](https://duckdb.org/2021/12/03/duck-arrow.html) I was unsure where to start digging.

Out of curiosity: Does DuckDB also specify the columns of interest, if known? In my example above `col_55` and `col_44`? Since S3 in theory could support fetching only a range of bytes and on the other hand columns are contiguous, it could be possible to even fetch files partially, what do you think?

For the other topic I'll try to open a similar issue at Arrow.
