### ISSUE TITLE
[R]: Polling thread started by duckdb::duckdb()?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2942]
#### What happens?

I'm observing small but noticeable CPU usage after running `duckdb::duckdb()`. The load is reduced after the duckdb connector is garbage-collected. Is this expected? Does duckdb start a polling thread of sorts?

#### To Reproduce

``` r
library(duckdb)
#> Loading required package: DBI

Sys.sleep(5)
system('ps -Ao "%cpu comm" | grep "/R$"', intern = TRUE)
#> [1] "  0.0 /Library/Frameworks/R.framework/Resources/bin/exec/R"

duck <- duckdb()
Sys.sleep(5)
system('ps -Ao "%cpu comm" | grep "/R$"', intern = TRUE)
#> [1] "  2.2 /Library/Frameworks/R.framework/Resources/bin/exec/R"

rm(duck)
gc()
#>           used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
#> Ncells  849164 45.4    1323022 70.7         NA  1323022 70.7
#> Vcells 1551623 11.9    8388608 64.0      16384  2927822 22.4
Sys.sleep(10)
system('ps -Ao "%cpu comm" | grep "/R$"', intern = TRUE)
#> [1] "  0.0 /Library/Frameworks/R.framework/Resources/bin/exec/R"
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: 1114055090353edd6a998150d6e6388d612cd689
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

CC @nbenn.

**Comment by Mytherin** [comment]
DuckDB starts some background threads that wait for work to appear. These shouldn’t be doing anything but waiting for tasks to be available, however. Perhaps something happening there?
