### ISSUE TITLE
Parquet reader does not implement TableFilterType::CONJUNCTION_OR correctly

### ISSUE THREAD

**Issue by majetideepak** [duckdb/duckdb#2955]
As reported here https://github.com/facebookincubator/velox/issues/895
Parquet reader seems to have a bug in its `TableFilterType::CONJUNCTION_OR` implementation
File: https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/tests/examples/nation.parquet
Reproducer:
```
int main(int argc, char** argv) {
    DuckDB db(nullptr);
    Connection con(db);
    auto result = con.Query("PRAGMA enable_profiling; SELECT * FROM 'nation.parquet' WHERE name='CANADA' OR NAME = 'UNITED KINGDOM'");
    result->Print();
}
```
```
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         nationkey         │
│            name           │
│         regionkey         │
│          comment          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             2             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│(name=CANADA OR name=UNITED│
│          KINGDOM)         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             2             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│        PARQUET_SCAN       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            name           │
│         nationkey         │
│         regionkey         │
│          comment          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│  Filters: name=CANADA OR  │
│     name=UNITED KINGDOM   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             25            │
│          (0.00s)          │
└───────────────────────────┘
 ```

**Comment by Mytherin** [comment]
Thanks for the report!

This looks to me like a problem with the recently introduced pushdown of the OR filter. The filter clause should not be there (since the filter is pushed down) and the filter should be correctly resolved inside the scan itself. @tiagokepe could you have a look?

**Comment by tiagokepe** [comment]
> Thanks for the report!
> 
> This looks to me like a problem with the recently introduced pushdown of the OR filter. The filter clause should not be there (since the filter is pushed down) and the filter should be correctly resolved inside the scan itself. @tiagokepe could you have a look?

This is already in my TODO list [(pruning filter operator).](https://github.com/duckdb/duckdb/pull/2731#:~:text=P.S.%3A%20It%27s,1), which is a needed optimization step to prune the filter operator when the entire predicate is pushed down to the scan.

**Comment by majetideepak** [comment]
There are two problems here.
1) As mentioned the filter clause should not be there.
2) The `TableFilterType::CONJUNCTION_OR` implementation also seems to be incorrect as PARQUET_SCAN step is returning all the rows with the pushdown.
https://github.com/duckdb/duckdb/blob/master/extension/parquet/parquet_reader.cpp#L631
The implementation should be
```
     case TableFilterType::CONJUNCTION_OR: {
		auto &conjunction = (ConjunctionOrFilter &)filter;
                parquet_filter_t or_mask;
		for (auto &child_filter : conjunction.child_filters) {
			parquet_filter_t child_mask = filter_mask;
			ApplyFilter(v, *child_filter, child_mask, count);
			or_mask |= child_mask;
		}
                filter_mask &= or_mask;
```
Velox needs only the fix (2). I can submit a patch with some guidance on how to add tests.

**Comment by hannesmuehleisen** [comment]
@tiagokepe maybe this can be fixed with higher priority?

**Comment by tiagokepe** [comment]
Sure, I will look at the fix for (2).

**Comment by hawkfish** [comment]
Can this be closed?

**Comment by tiagokepe** [comment]
> Can this be closed?

I think so. Perhaps we could open an issue for pruning the OR filter operator when the entire predicate is pushed down to the scan.
