### ISSUE TITLE
Multithreaded Unregister with Cursor Causes Segfault in Python

### ISSUE THREAD

**Issue by dave-c** [duckdb/duckdb#2959]
#### What happens?
I have a worker that does a query against a DuckDB connection.  Each worker creates a cursor and registers a Pandas DataFrame.  The worker executes a query, then unregisters the DataFrame.  DuckDB will segfault randomly on different workers.  If I don't unregister and simply close the cursor, it works as expected.

#### To Reproduce
I've attached a simpler reproducer.

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 29
 - DuckDB Client: Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
Yes, and it still segfaults.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Really simple to run and see the issue:

[duckdb_unregister_bug.zip](https://github.com/duckdb/duckdb/files/7906822/duckdb_unregister_bug.zip)

**Comment by dave-c** [comment]
Actually I take my comment back about removing the unregister and it working.  I can still reproduce a crash even with removing the unregister.

**Comment by dave-c** [comment]
Some more data:

Pandas 1.3.4

**Comment by hannesmuehleisen** [comment]
Maybe @pdet can have a look?

**Comment by pdet** [comment]
Hi @dave-c I just had a look at this.

Basically, DuckDB follows the same execution as SQLite regarding multithreading. In the sense that a connection can't be created by a thread and used by another thread to execute queries.
Since cursors are basically copies of a connection, they should also fail on this.

I've added proper checks now to error this correctly!

**Comment by SartorialOffense** [comment]
@pdet  Hi, I just wanted to clarify what you said about connections and threads.  Are you saying I shouldn't create a connection on thread 1 and then use on thread 2? Or that it isn't safe to use a connection on 2 threads at the same time? The former is common in async methods in .NET.

**Comment by pdet** [comment]
Hey @SartorialOffense,

I'm saying that you should not be able to use a connection in a thread that was not created by it. This should always throw an error. Which is the same behavior SQLite presents.

**Comment by Mytherin** [comment]
> Hey @SartorialOffense,
> 
> I'm saying that you should not be able to use a connection in a thread that was not created by it. This should always throw an error. Which is the same behavior SQLite presents.

To clarify: this is the behavior of the Python client of DuckDB, which mirrors the Python client of SQLite. The low-level C/C++ connection objects are safe to use across multiple threads, but will use mutexes to prevent actual concurrent usage. For actual concurrent usage by multiple threads multiple connections need to be constructed.

> Hm, in the case of register/unregister functions, they actually alter the database since they do create/delete views.

Perhaps I'm mistaken, but I thought these only created temporary views, which live only in the client scope and can also be used also with read-only connections?

**Comment by pdet** [comment]
> Perhaps I'm mistaken, but I thought these only created temporary views, which live only in the client scope and can also be used also with read-only connections?
Yes, you should be right.

**Comment by dave-c** [comment]
> > Perhaps I'm mistaken, but I thought these only created temporary views, which live only in the client scope and can also be used also with read-only connections?
> > Yes, you should be right.

Right, that's what I thought the expected behavior to be since they are temporary views as you said.  I use this often in read-only connections.

To expand on @Mytherin comment about having multiple connections for use across multiple threads... if I were to create a connection pool of multiple connections, would it be ok to use those connections to service queries for different threads?  Think of an arrangement where I have a server that is servicing multiple client requests.  I would just find an unused connection in the pool to service a request and return it to the pool when done.  I don't want to constantly be creating and destroying connections.  I don't know the overhead to creating/destroying connections, but to maintain a connection pool would seem to be the more efficient route if possible as I would lose any internal caching benefit or whatever else could be available as a performance benefit.  Just some thoughts.  I haven't dug into the DuckDB code in earnest so at the moment I'm speculating.  Thanks.

BTW, if I do create a new connection and not a cursor instance in the reproducer I provided it works just fine.  So that would be my solution for what I was trying to achieve.  But I thought the pool arrangement might also be appropriate.
