### ISSUE TITLE
blank screen issue while executing duckdb.query on winodws

### ISSUE THREAD

**Issue by git-kote** [duckdb/duckdb#2962]
#### What happens?
Blank screen issue when duckdb.query execution is happening on pandas dataframes 

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
I have 4 CSV files - and all of them i converted to pandas dataframes using pd.read_csv("CSV_NAME", header=5)
CSVs look like below
A.csv - 9.5MB, 10506 rows, 440 columns
C.csv - 1MB, rows - 8003, columns - 49
R.csv - 4.9MB, rows-211, column - 10503
CH.csv - 1.9MB, rows- 8003 ,columns- 110
ST.csv - 333MB, columns -144, rows - 910003
ANA.csv - 170MB, columns -176, rows - 420003

pandas dataframe has identified that few columns have mixed data types as a warning

here the query that i am trying on these dataframes
df1=duckdb.query("""SELECT A.record, A.name, C.hostname, R.count, CH.number from A, C,R, CH, ST, ANA""").to_df()

i understand that this query is not using all the dataframes given, but it is giving unexpected behaviour

with python idle - it is getting struck after creating all dataframes and an error related to TK-
with cmd - it is going blank screen while executing the query and it is not coming to normal state.

so I would like to understand why i am facing this issue
Also i would like to know, whether Duckdb cant work with this much bigger data (since duckdb is able to transfer queries to dataframes i felt its good but cant recommend to my client at this stage)

#### Environment (please complete the following information):
 - OS: windows 10 enterprise
 - DuckDB Version: 0.3.1
 - DuckDB Client: python
 - python version - 3.7.4
 - RAM - 14GB
#### Before Submitting

- [  ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
-------- No 

- [ . ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

> with python idle - it is getting struck after creating all dataframes and an error related to TK-

Could you post the exact error message you are receiving?

> with cmd - it is going blank screen while executing the query and it is not coming to normal state.

What exactly do you mean with "it is going blank screen and not coming to normal state"?

**Comment by git-kote** [comment]
> Thanks for the report!
> 
> > with python idle - it is getting struck after creating all dataframes and an error related to TK-
> 
> Python idle is stuck an another window of idle with TK- as title is showing (you can ignore the idle error for now as even error is not appearing clearly)
> 
> > with cmd - it is going blank screen while executing the query and it is not coming to normal state.
> 
> I am running this on my windows VM  - the moment it reaches query execution entire system is stuck and whole screen is going blank, the system has to be restarted manually

**Comment by Alex-Monahan** [comment]
Based on your query, it looks like you are doing a Cartesian join. That means the result will be as many rows as the product of the rows in each table (essentially an explosion of rows). 

You'll have to specify some join criteria for the query to complete (ex: column 1 in table A must match column 4 in table B, etc.). You can use an on clause for each join, a using clause, or you can specify the column mappings in your where clause.
