### ISSUE TITLE
Feature: Alternative Modulo and Integer division functions

### ISSUE THREAD

**Issue by rsund** [duckdb/duckdb#2981]
It is well known that modulo (and integer division) has several different [widely used](https://en.wikipedia.org/wiki/Modulo_operation#In_programming_languages) definitions. DuckDB seems to have implementations for INTEGERs, [HUGEINT](https://github.com/duckdb/duckdb/commit/67a1471c894c5842f1ce490d74378215f8776dd1) and also for floating points (#249) although [documentation says no](https://github.com/duckdb/duckdb-web/blob/1daf69f9452c047095f15b38da076c2568bd6d7a/docs/sql/functions/numeric.md?plain=1#L22).

These functions are (probably) following the [`Truncated` definition](https://en.wikipedia.org/wiki/Modulo_operation#Variants_of_the_definition). Of the other possible definitions (`Floored`, `Euclidean`, `Rounded`), e.g. **R** and **Python** are using Floored definition in their modulo operators.

This inconsistency is causing problems if the same tasks should give equivalent results with different "engines", such as in DuckDB dbplyr-backend for R (#2926) as well as in other similar backends (tidyverse/dbplyr#108). The inconsistency pops up in modulo only if there are negative numbers involved, so this may not be as big problem for typical modulo use cases as it is for [integer division](https://en.wikipedia.org/wiki/Division_(mathematics)#Of_integers) (see also also [division in Python](https://www.python.org/dev/peps/pep-0238/)). These are, however, closely connected as `x idiv m = (x - (x mod m)) / m`.

To circumvent the translation problems, and in order to widen the features of DuckDB, it would be excellent, if DuckDB would provide functions for alternative modulo definitions (and integer divisions). There are simple algorithms to [implement other modulo definitions using truncation](https://en.wikipedia.org/wiki/Modulo_operation#Implementing_other_modulo_definitions_using_truncation) available, so those should be rather easy to implement also in DuckDB.

**Comment by rsund** [comment]
Macros could work for these. For example, for the `Floored` [division](https://search.r-project.org/CRAN/refmans/numbers/html/div.html) and [modulo](https://search.r-project.org/CRAN/refmans/numbers/html/mod.html) these would become something like:
`CREATE MACRO FDIV(x, y) AS FLOOR(x/y)`
`CREATE MACRO FMOD(x, y) AS x-y*FLOOR(x/y)`

**Comment by Mytherin** [comment]
Perhaps you could send a PR that adds these macros [to the list of default macros](https://github.com/duckdb/duckdb/blob/7a1864144bc64465358cc9e4316025c8fcc419f2/src/catalog/default/default_functions.cpp#L86)?
