### ISSUE TITLE
regexp_extract syntac

### ISSUE THREAD

**Issue by martindut** [duckdb/duckdb#2984]
Hi
I'm trying to use regexp_extract to extract two colums from a string:
CI(**US1255091092**) CUSIP/ISIN CHANGE TO (**US1255231003**) (20181221002753CI, CIGNA CORP, 125509109)
In R I can use `stringr::str_extract(Description, "(?<=\\().*?(?=\\))")`, which gives me US1255091092, and `stringr::str_extract(Description, "(?<=CUSIP/ISIN CHANGE TO \\().*?(?=\\))")`, which gives me US1255231003.
How would I do this induckdb SQL using regexp_extract?
If I run `SELECT regexp_extract(Description, '(?<=\\().*?(?=\\))') AS from FROM ds_fil`, it returns an empty string

**Comment by lnkuiper** [comment]
It seems that our regex does not support `?<=`. I would suggest doing one of the following:
```sql
select regexp_extract(Description, '(\(.*?\))') from ds_fil;
-- (US1255091092)
select regexp_extract(Description, '.*?CUSIP/ISIN CHANGE TO (\(.*?\))', 1) from ds_fil;
-- (US1255231003)
```

Or use the index parameter, then you can use the same regex for both:
```sql
select regexp_extract(Description, '(\(.*?\)).*?(\(.*?\))', 1) from ds_fil;
-- (US1255091092)
select regexp_extract(Description, '(\(.*?\)).*?(\(.*?\))', 2) from ds_fil;
-- (US1255231003)
```

**Comment by martindut** [comment]
> It seems that our regex does not support `?<=`. I would suggest doing one of the following:
> 
> ```sql
> select regexp_extract(Description, '(\(.*?\))') from ds_fil;
> -- (US1255091092)
> select regexp_extract(Description, '.*?CUSIP/ISIN CHANGE TO (\(.*?\))', 1) from ds_fil;
> -- (US1255231003)
> ```
> 
> Or use the index parameter, then you can use the same regex for both:
> 
> ```sql
> select regexp_extract(Description, '(\(.*?\)).*?(\(.*?\))', 1) from ds_fil;
> -- (US1255091092)
> select regexp_extract(Description, '(\(.*?\)).*?(\(.*?\))', 2) from ds_fil;
> -- (US1255231003)
> ```

Thanks, it works perfectly!
