### ISSUE TITLE
Slowing down ingesting large-ish csv files

### ISSUE THREAD

**Issue by edalfon** [duckdb/duckdb#2993]
#### What happens?
DuckDB seems to slow down ingesting large-ish csv files, for an in-laptop analysis. 

Trying to compare DuckDB with Postgres, for a bunch of data wrangling steps, but, 
- involving largish-data (csv files, each with 400-900 million rows, uncompressed size 50-150GB each)
- to be run in a laptop (so, no fancy cloud solutions possible)

DuckDB ended up being >2x slower than Postgres ingesting the larger files, even though it was ~4x-5x faster in the somewhat smaller files. 

I have documented the comparison in a few blog posts. In this one https://edalfon.netlify.app/p/test-driving-duckdb-and-arrow/ originally observed the issue and then in this one https://edalfon.netlify.app/p/inspecting-closer-duckdb-s-data-import/ tried to find out what was going on.

After trying a bunch of things, I found that the total time to ingest the data as experienced from the client side, is almost 4 times longer than the time reported by DuckDB's profiling(`PRAGMA enable_profiling;`). So, my **uneducated**-guess is that the cleaning up work (e.g. removing temp files) is slowing things down.

And I wonder if there is any way to prevent such performance degradation. Perhaps something similar to Postgres' UNLOGGED tables, or an unlogged transaction could help? Did not find any exposed features for this in DuckDb, though.

Not claiming a bug here, just reporting an observation from an admittedly humble use case (super humble compared with [this](https://mobile.twitter.com/ghalimi/status/1484598468538630145) example, ingesting 263GB, 1.4B rows, under 5 seconds).

#### To Reproduce
Basically this.
```sql
  PRAGMA enable_profiling;
  CREATE TABLE year_data AS 
  SELECT * 
  FROM read_csv_auto('/year_data.txt')
  ;
```
But did also try using COPY, creating the table by hand and then
```sql
    COPY year_data FROM '/year_data.txt' ( AUTO_DETECT TRUE );
```

Also, not relying in auto-detect but setting optimal column types helps indeed, but the slowing down still occurs.

#### Environment (please complete the following information):
 - OS: Windows 10. I wonder actually if this is a Windows issue, because I suspect it has to do with the temp files. In one of the runs, the system restarted and killed DuckDB midway of the query. There were almost 1 million files (256k size) in the temp_directory and just deleting them takes quite some time. I guess Windows does not deal so good with so many tiny files.
 - DuckDB Version: 0.3 and 0.3.1
 - DuckDB Client: Originally ran all using the R client and interfacing with DuckDB via DBI. But then I also tried from Python and also the CLI, all showing similar times.

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

One test file I used has 486 million rows, 25 columns, 11 of them varchar, 2 (seemingly) timestamp, the rest numeric (integer and double). Unfortunately, I cannot share the data. But I'd be happy to share some more details if you want.

**Comment by hawkfish** [comment]
> I guess Windows does not deal so good with so many tiny files.

It doesn't in in my experience.

**Comment by rkennedy-mode** [comment]
For what it's worth, we don't ingest CSV directly into DuckDB but we similarly see slowdowns when ingesting large datasets into our DuckDB instances. We use the Appender class (from Java) to write data to a table. On smaller datasets DuckDB is significantly faster than our previous solution. However, somewhere between 250k and 750k rows we see the performance invert and DuckDB becomes **considerably** slower than our previous solution.

It's unclear if these are related or not, but it does seem a convenient coincidence.

**Comment by edalfon** [comment]
> 

which version of DuckDB did you use, when you detected this?

I originally experienced this with version 0.3, and still happened at least until ver. 0.4. But I noticed solid improvements in latest version 0.5.1 (haven't had time to properly test this again, though).

**Comment by rkennedy-mode** [comment]
We're on the latest release (either 0.5.1 or possibly a one-off build of the trunk branch…I forget what we're on these days).
