### ISSUE TITLE
Correlated group on ANY subquery

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#2999]
#### What happens?
While this subquery crashes on MonetDB, it gives error on DuckDB :) The dependent join unnesting is not available for the ANY operator. If you consider this as a feature, please close the issue.

#### To Reproduce
CREATE TABLE t0 (c0 INT);
CREATE TABLE t1 (c0 INT);
INSERT INTO t0 VALUES (1);
INSERT INTO t1 VALUES (1);

SELECT 1 = ANY(SELECT 1 FROM t1 JOIN (SELECT count(*) GROUP BY t0.c0) AS x(x) ON TRUE) FROM t0;
Error: INTERNAL Error: Logical operator type "ANY_JOIN" for dependent join

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: downloaded and compiled from the tip of master branch
 - DuckDB Client: Shell

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by PedroTadim** [comment]
I fixed the crash in MonetDB and now it runs there😇

**Comment by hannesmuehleisen** [comment]
It should not throw an internal error, so there is probably a bug here. Thanks for reporting.

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #3012.

**Comment by Mytherin** [comment]
> It should not throw an internal error, so there is probably a bug here. Thanks for reporting.

Indeed as Hannes mentioned any internal exception being thrown is considered a bug, so please file any you find :)
