### ISSUE TITLE
Inconsistent column names between DESCRIBE and SUMMARIZE

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#3020]
#### What happens?

<img width="1203" alt="Screen Shot 2022-02-02 at 09 07 03" src="https://user-images.githubusercontent.com/589034/152169304-46fcac1e-b748-465e-8123-e52515309050.png">

`column_name` and `Field` are the same. Same with `column_type` and `Type`. 

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: v0.3.2-dev973
 - DuckDB Client: WASM

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

**Comment by Mytherin** [comment]
Should be fixed by #3123
