### ISSUE TITLE
Union of selects with different field orders returns incorrect results

### ISSUE THREAD

**Issue by drorspei** [duckdb/duckdb#3022]
#### What happens?
Taking the union of two selects with different field orders returns incorrect results.

#### To Reproduce
```
select 'a' as a, 'b' as b
union all
select 'b' as b, 'a' as a
```
returns "[[a,b], [b,a]]" instead of "[[a,b], [a,b]]" or "[[b,a],[b,a]]"

#### Environment (please complete the following information):
 - OS: Ubuntu 18.04
 - DuckDB Version: 0.3.1
 - DuckDB Client: python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Alex-Monahan** [comment]
Would you mind providing the output in a table format instead of a list of lists? I'm not sure which dimension is rows vs columns.

As a note, SQL Unions are based on column order, not on names.

**Comment by drorspei** [comment]
What I wrote is invariant to transposition, but sure, the code gives:
```
a b
b a
```
but I expected a's in one column and b's in the other.

If this is simply a feature of SQL then it's my bad, I'll close the issue

**Comment by drorspei** [comment]
Thanks for the explanation, and for duckdb in general ^_^
