### ISSUE TITLE
Filter clause affects subsequent aggregate functions

### ISSUE THREAD

**Issue by james-atkins** [duckdb/duckdb#3023]
#### What happens?

A filter clause on an aggregate function is "remembered" and incorrectly affects subsequent aggregate functions without any filter clauses.

#### To Reproduce

Based on the example in the [documentation](https://duckdb.org/docs/sql/query_syntax/filter), when `total_rows` is first,

```sql
SELECT 
    count(*) as total_rows,
    count(*) FILTER (WHERE i <= 5) as lte_five,
    count(*) FILTER (WHERE i % 2 = 1) as odds
FROM generate_series(1,11) tbl(i)
```
we get the correct counts,

| total_rows | lte_five | odds |
|------------|----------|------|
| 11         | 5        | 6    |

but when the `total_rows` count is moved to the end
```sql
SELECT 
    count(*) FILTER (WHERE i <= 5) as lte_five,
    count(*) FILTER (WHERE i % 2 = 1) as odds,
    count(*) as total_rows
FROM generate_series(1,11) tbl(i)
```
the count is still filtered by the previous filter.

| lte_five | odds | total_rows |
|----------|------|------------|
| 5        | 6    | 6          |

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: release 0.3.1-1 and master build v0.3.2-dev479 8a0e93080
 - DuckDB Client: R / CLI

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
It picks up the most recent.

**Comment by hawkfish** [comment]
Happily this seems to just be a small problem with simple aggregation (no groups)
