### ISSUE TITLE
Python 3.10 wheels for Windows

### ISSUE THREAD

**Issue by pfmoore** [duckdb/duckdb#3031]
#### What happens?
Using Python 3.10, `pip install duckdb` builds the module from source. The build takes about 5 minutes, and then fails with a large C compiler error traceback, which I'm not able to interpret or fix.

I can't find anything that states clearly what versions of Python are supported. If Python 3.10 isn't supported yet, then it would be useful to document that somewhere.

#### To Reproduce
With Python 3.10, `pip install duckdb`

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1
 - DuckDB Client: Python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
Same issue

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Python 3.10 wheels [should be available on Windows](https://pypi.org/project/duckdb/#files), at least for the latest release. Perhaps try again with 0.3.2?

**Comment by pfmoore** [comment]
Thanks! 0.3.2 came out since I posted the issue, and I hadn't noticed.
