### ISSUE TITLE
max() of the arrays returns the array whose 1st element is the biggest?

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#3032]
is this behavior expecting?

**Comment by Alex-Monahan** [comment]
Can you please provide a reproducible example?

**Comment by l1t1** [comment]
```
SELECT max(arr),min(arr) FROM
(
  SELECT array[1,2,3,4,5,6]arr
    UNION ALL
  SELECT array[2,3,4,5,6]
  UNION ALL
  SELECT array[]
);
─────────────────┬──────────┐
    max(arr)     │ min(arr) │
─────────────────┼──────────┤
 [2, 3, 4, 5, 6] │ []       │
─────────────────┴──────────┘
```

**Comment by Mytherin** [comment]
That seems intended to me, what other behavior would you expect? If you compare min/max on strings, the min string would be the string with the first element which is the smallest (e.g. AZ < BB). This seems consistent with that.

**Comment by l1t1** [comment]
thanks.
