### ISSUE TITLE
JDBC Driver doesn't support Apple M1 architecture

### ISSUE THREAD

**Issue by julienflyr** [duckdb/duckdb#3033]
#### What happens?
Unable to use the JDBC driver in DBeaver on Apple M1 . It throws an error. 

```'java.nio.ByteBuffer org.duckdb.DuckDBNative.duckdb_jdbc_startup(byte[], boolean)'```

![image](https://user-images.githubusercontent.com/97091758/152529987-f3c1221b-9dfe-4651-89f4-cf984cac6737.png)

#### To Reproduce
Try to make a connection on an Apple M1 Pro chip architecture. 

#### Environment (please complete the following information):
 - OS: MacOS Monterey, Apple M1 Pro chip
 - DuckDB Client: duckdb_jdbc-0.3.1.jar

I think the new Apple M1 Architecture isn't supported. Also related to this (https://stackoverflow.com/questions/67912040/unsatisfiedlinkerror-for-duckdb-native-code-in-java).

**Comment by julienflyr** [comment]
It seems that the corresponding lib `libduckdb_java.so_osx_aarch64` isn't included in the `.jar` file. 

The 0.3.2 jar file does contain these files.
```
libduckdb_java.so_linux_amd64
libduckdb_java.so_osx_amd64
libduckdb_java.so_windows_amd64
```

I managed to get DuckDB working under DBeaver by using the Intel version of DBeaver (https://dbeaver.io/files/dbeaver-ce-latest-macos-x86_64.dmg). That sort of solved my problem for now.

**Comment by hozn** [comment]
I'd also love to have a version of this that works on my Mac M1!

**Comment by hannes** [comment]
This was fixed and will be in the next release, which should be out next week

**Comment by hozn** [comment]
Thanks! As a workaround, I compiled it locally:
```
BUILD_JDBC=1 make
```
And then manually added that`duckdb_jdbc.jar` file from `build/releases/tools/jdbc` as the driver file in DBeaver.
