### ISSUE TITLE
Lateral join issue?

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#3043]
#### What happens?
Hello Duckies! While fuzzing lateral joins in MonetDB, ie got some crashes there :) I see LATERAL join queries are not working how they should be despite being accepted by the parser. I guess this happens because DuckDB is using PostgreSQL parser.

Here's an example:
`CREATE TABLE rt0 (c0 INT);`
`INSERT INTO rt0 VALUES (1), (2), (3), (NULL);`
`SELECT rt0.c0 FROM rt0 JOIN LATERAL (select rt0.c0 from (select 1) y(y)) AS x(x) ON TRUE;`

It should output the rows 1,2,3,NULL

This query gives the error: Error: Binder Error: Referenced table "rt0" not found!
However because it's a lateral join, rt0.c0 can be seen in the joined query.

Either LATERAL should be disabled, or could be implemented. I guess it shouldn't be difficult. Sadly at the moment I don't have time to make a pull request :(

#### To Reproduce
Check the example in the description.

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: compiled from tip of master branch.
 - DuckDB Client: Shell

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Teggy** [comment]
If I could upvote the implementation of `LATERAL` twice, I would do it.  Availability of `LATERAL` would turn DuckDB into a *most-promising backend* for our work in the compilation of PL/SQL, recursive UDFs, etc.

Please consider it, Duckies!

**Comment by Mytherin** [comment]
LATERAL joins are indeed not yet supported, but definitely "on the menu" to be added in a later release. The issue here seems to be that the `LATERAL` flag is ignored rather than throwing an error in the parser as should be the case right now.
