### ISSUE TITLE
Multi-argument distinct aggregate binding error

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#3046]
#### What happens?
@bohaterowicz writes:
> I was working with duckdb and encountered a crash when testing the string_agg() function. Seems like the loops that initialize the type vectors (probe_types & distinct_group_types) in GroupedAggregateHashTable class use only payload_idx when iterating over children of an aggregate. Since payload_idx is updated only once per aggregate it ends up reusing same index for multiple children, and when children have different types, this leads to type mismatch and crash (assertion in debug)

#### To Reproduce
```sql
CREATE TABLE test_val(val INT);

INSERT INTO test_val VALUES(1), (2), (3), (3), (2)

SELECT STRING_AGG(DISTINCT val ORDER BY val DESC) from test_val;
 ----
 3,2,1
```

#### Environment (please complete the following information):
 - OS: OSX
 - DuckDB Version: 0.3.2
 - DuckDB Client: Test harness

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
This affects any multi-argument aggregate, but `SortedAggregateFunction` makes it very easy to trip over.

**Comment by Mytherin** [comment]
Should be fixed now.
