### ISSUE TITLE
Extension not found?

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#3048]
#### What happens?
Attempting to install the tpch extension with the new release. When I try the URL separately I get a Access Denied (though that could also happen if the URL is slightly off)

#### To Reproduce
```
> library(duckdb)
> con <- dbConnect(duckdb())
> dbExecute(con, "INSTALL tpch;")
Error: duckdb_execute_R: Failed to run query
Error: IO Error: Failed to download extension http://extensions.duckdb.org/82788760f/osx_amd64/tpch.duckdb_extension.gz
```

#### Environment (please complete the following information):
 - OS: macOS 12.2
 - DuckDB Version: 0.3.2
 - DuckDB Client: R

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
Ah. It appears my changes for CRAN did change the commit ID so the extensions cannot be found any more. Thanks for reporting. Copied the files, try again?

**Comment by jonkeane** [comment]
I can now successfully install the extensions (at least for macos, when I tried on linux, I'm still getting the failed to download message).

But, when I go to load the extension I now get an error that they cannot be loaded:

```
> dbExecute(con, "INSTALL tpch;")
[1] 0
> dbExecute(con, "LOAD tpch;")
Error: duckdb_execute_R: Failed to run query
Error: IO Error: File "/Users/jkeane/.duckdb/extensions/82788760f/osx_amd64/tpch.duckdb_extension" could not be loaded
```

And on linux, here's that download error in case it's helpful:
```
> dbExecute(con, "INSTALL tpch;")
Error: duckdb_execute_R: Failed to run query
Error: IO Error: Failed to download extension http://extensions.duckdb.org/82788760f/linux_amd64/tpch.duckdb_extension.gz
```

**Comment by samansmink** [comment]
This issue is partially resolved by the PR above. However, we still need 2 things to have this fixed i think: fixing the CI for master builds so that it is not canceled, and adding tests to the R (and maybe also python) CI to test the extension can actually be loaded.

**Comment by jonkeane** [comment]
This might be what #3416 is solving, but I did also just try this with the 0.3.3, and I'm seeing the following when loading extensions:

```
library(duckdb)
#> Loading required package: DBI

con <- dbConnect(duckdb())

dbSendStatement(con, "INSTALL tpch;")
#> <duckdb_result f9d80 connection=f9ce0 statement='INSTALL tpch;'>
dbSendStatement(con, "LOAD tpch;")
#> Error: rapi_execute: Failed to run query
#> Error: IO Error: File "/Users/jkeane/.duckdb/extensions/fe9ba8003/osx_amd64/tpch.duckdb_extension" could not be loaded: dlopen(/Users/jkeane/.duckdb/extensions/fe9ba8003/osx_amd64/tpch.duckdb_extension, 0x0005): symbol not found in flat namespace '__ZN6duckdb12FunctionData4CopyEv'
```

**Comment by Mytherin** [comment]
Ah indeed, somehow I missed that #3416 was not merged yet. This is likely related to the fixes there.
