### ISSUE TITLE
SQLAlchemy dialect 

### ISSUE THREAD

**Issue by xhochy** [duckdb/duckdb#305]
This is probably also useful for #302 when integrating with Ibis but also in general a feature people are using. The important part here is to have an SQLAlchemy dialect to render queries, connect to the database and get metadata about the tables. The acutal ORM that comes with SQLAlchemy is totally useless for data analytics (it's good when developing a blog) as it creates a lot of Python objects.

SQLAlchemy is often used as a more convinient access layer for databases in Python than the DB-API 2.0.

As duckdb is based off Postgres SQL-dialect wise, you probably can build upon that dialect.

**Comment by hannesmuehleisen** [comment]
I agree, its probably a good idea to support this. We need to look int result set construction performance though.

**Comment by xhochy** [comment]
> I agree, its probably a good idea to support this. We need to look int result set construction performance though.

That is too slow when you have large results. Dialect and metadata are the great wins. SQLAlchemy needs someone to write an extension in future so that the `sqlalchemy.Engine` can return pandas/numpy/.. but for now I always render the query to a string and use `raw_connection()` for the result heavy queries.

**Comment by antoinecarme** [comment]
Thanks to the team for this project.

It would be nice indeed to have an embedded in-process/in-memory version of one of the highest quality databases on the market. SQLAlchemy support is real added value and PostgreSQL SQLAlchemy is already an excellent one.

To be precise, I am interested in an equivalent of SQLite(":memory:") with full SQLAlchemy support and pandas input/output.

**Comment by hannesmuehleisen** [comment]
We already have pandas input output in DuckDB, check out the relational API

**Comment by totalhack** [comment]
I'm also interested in testing DuckDB out as an alternative datasource in an analytics/warehousing project I'm working on called [Zillion](https://github.com/totalhack/zillion). I'm using the SQLAlchemy core expression language to build datasource queries. There is also a "combined layer" database that is simply an in-memory SQLite DB right now; DuckDB would be interesting to test there too. The latter doesn't use SQLAlchemy now but I was planning on moving towards that to open up the list of supported combined layer DBs.

Has there been any further discussion on the timeline for a SQLAlchemy plugin?

Thanks, just heard about this project yesterday and it looks great!

**Comment by Mause** [comment]
Please be aware that that implementation is as basic as I have said in the readme

**Comment by hannes** [comment]
`duckdb-engine` seems to be doing well, no need to do this ourselves.

**Comment by valeriya-drachuk** [comment]
Hello @hannes! I am currently seeing this error message when I try to use duckdb with SQLAlchemy. Can you please explain how I would use duckdb-engine as a workaround?
<img width="472" alt="Screen Shot 2022-09-29 at 7 47 30 PM" src="https://user-images.githubusercontent.com/52944729/193161132-5e1e0625-8952-4081-aa35-1aa4a8525b1c.png">

**Comment by antoinecarme** [comment]
> Please be aware that that implementation is as basic as I have said in the readme

Thanks a lot @Mause. duckdb-engine rocks. This piece of code, as simple as it is,  puts sklearn2sql tests at the same level as postgresql , sqlite, and other databases. and that's more than OK for me.

https://github.com/Mause/duckdb_engine

**Comment by vindex10** [comment]
Hi! I just discovered a new package:
https://github.com/leonardovida/duckdb-sqlalchemy

it's been more active in the past ~6 months. @leonardovida is working for motherduckdb 
is https://github.com/Mause/duckdb_engine still recommended?
