### ISSUE TITLE
Packaging for Linux Distros?

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#3052]
As suggested by @eddelbuettel, we should look into releasing packaged versions of DuckDB for the various Linux distros out there.

**Comment by eddelbuettel** [comment]
I'll help, formally/informally. I had good luck too "personally speaking" dropping things onto Launchpad for Ubuntu builds, there is the entire [openSUSE Build Service build farm](https://build.opensuse.org/) for many distros too.  But someone with more time than you or me needs to get into the weeds and work the details out...

**Comment by hannes** [comment]
I find this outrageous that my issue is silently closed

**Comment by szarnyasg** [comment]
Thanks for voicing your concern. You may submit your complaint to `quack@duckdb.org`.
