### ISSUE TITLE
Crash in duckdb_appender_destroy.

### ISSUE THREAD

**Issue by mmzeeman** [duckdb/duckdb#3073]
#### Crash in duckdb_appender_destroy

When you free error messages with `duckdb_free` from `duckdb_appender_error` like is described in: https://duckdb.org/docs/api/c/appender, and later destroy the appender structure with `duckdb_appender_destroy`, the destroy call crashes your program. 

Is the documentation correct? Or should the error messages be handled similar to prepare_error, for which the documentation states it is not needed to free the error message.

#### To Reproduce

- Create an appender and cause an error. e.g by specifying an unknown table.
- Retrieve the error message with `duckdb_appender_error`
- Call `duckdb_free` on the error message.
- Destroy the appender with `duckdb_appender_destroy`
- Crash

It looks like this:

```
.destruct appender
destruct destroy
rebar3(88214,0x16d4f7000) malloc: *** error for object 0x12e6fda50: pointer being freed was not allocated
rebar3(88214,0x16d4f7000) malloc: *** set a breakpoint in malloc_error_break to debug
```

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: 0.3.1
 - DuckDB Client: Wip Erlang Client

**Comment by Mytherin** [comment]
Thanks for the report! I have fixed the docs to reflect that the error message indeed should not be freed.
