### ISSUE TITLE
SELECT FROM parquet file ignores timezone information

### ISSUE THREAD

**Issue by fgenoese** [duckdb/duckdb#3080]
The following example code creates a data frame with timezone information and exports it to a parquet file using `df.to_parquet()`. As you can see, the timezone information is ignored when duckdb reads the file. On the other hand, it seems to be present in the parquet file, considering that `df.read_parquet()` correctly restores the tzinfo.

```
start = pd.Timestamp('20220101 00:00', tz='Europe/Rome')
end = pd.Timestamp('20220101 06:00', tz='Europe/Rome')
index = pd.date_range(start,end,freq='H')[:-1]
df = pd.DataFrame( columns=["value"],  data=[0]*(len(index)), index=index ) 
print("original df:")
print(df)
df.to_parquet("test.parquet")

con = duckdb.connect(database=':memory:')
con.execute('CREATE VIEW test AS SELECT * FROM "test.parquet"');
df = con.execute("SELECT * FROM test").fetchdf()
print("duckdb reading parquet file:")
print(df)
con.close()

print("pandas reading parquet file:")
df = pd.read_parquet("test.parquet")
print(df)
```

This is the output:
```
original df:
                           value
2022-01-01 00:00:00+01:00      0
2022-01-01 01:00:00+01:00      0
2022-01-01 02:00:00+01:00      0
2022-01-01 03:00:00+01:00      0
2022-01-01 04:00:00+01:00      0
2022-01-01 05:00:00+01:00      0

duckdb reading parquet file:
   value   __index_level_0__
0      0 2021-12-31 23:00:00
1      0 2022-01-01 00:00:00
2      0 2022-01-01 01:00:00
3      0 2022-01-01 02:00:00
4      0 2022-01-01 03:00:00
5      0 2022-01-01 04:00:00

pandas reading parquet file:
                           value
2022-01-01 00:00:00+01:00      0
2022-01-01 01:00:00+01:00      0
2022-01-01 02:00:00+01:00      0
2022-01-01 03:00:00+01:00      0
2022-01-01 04:00:00+01:00      0
2022-01-01 05:00:00+01:00      0
```

**Comment by hannesmuehleisen** [comment]
Time zone support in DuckDB is not that old its likely we just don't map that metadata yet.

**Comment by hawkfish** [comment]
> Time zone support in DuckDB is not that old its likely we just don't map that metadata yet.

Hmm, the instants look correct to me? `2022-01-01 00:00:00+01:00` is the same as `2021-12-31 23:00:00+00:00` no?

The SQL standard does not actually store TZ information in the `TIMESTAMP WITH TIME ZONE` type.  But I think we are not mapping the Parquet type to `TIMESTAMPTZ`, which would at least trigger using a TZ extension.

**Comment by fgenoese** [comment]
The instant is correct, yes. 

However, reading the data in the correct timezone does make a difference in case I would like to aggregate the values by day.

**Comment by hawkfish** [comment]
Yes, the main bug here is that we don't import the data as `TIMESTAMPTZ`. But as of v0.3.2 you can do time zone aware analytics with the new TZ support in ICU by casting the `TIMESTAMP` column to `TIMESTAMPTZ` and setting the time zone: 

```sql
require icu;

SET TimeZone = 'Europe/Rome';

SELECT DAY(value::TIMEZONETZ);
```

Note that casting to `VARCHAR` is still not overridden so the command line will continue to display in GMT.

**Comment by fgenoese** [comment]
That blog post is a gold mine for everything related to time zones, thanks. 

The following code works, in the sense that it reports the correct _day_ (1-31) for all entries. As you said, casting to `VARCHAR` still reports the date in UTC:

```python
import duckdb as duckdb
import pandas as pd

start = pd.Timestamp('20220101 00:00', tz='Europe/Rome')
end = pd.Timestamp('20220101 06:00', tz='Europe/Rome')
index = pd.date_range(start,end,freq='H')[:-1]
df = pd.DataFrame( columns=["value"],  data=[0]*(len(index)), index=index ) 
print("original df:")
print(df)
df.to_parquet("test.parquet")

con = duckdb.connect(database=':memory:')
con.execute('SET TimeZone = "Europe/Rome"')
df = con.execute('SELECT DAY(__index_level_0__::TIMESTAMPTZ) as day,(__index_level_0__::TIMESTAMPTZ) as date_utc, value FROM "test.parquet"').fetchdf()
print("duckdb reading parquet file:")
print(df)
con.close()
```

Wonder what would be an efficient way to aggregate a set of annual data in hourly time resolution by _date_ (e.g. sum of all 24 hours, with the correct time zone)? Is that possible in the current version or should I wait for the next release?

**Comment by hawkfish** [comment]
All of the date binning functions have been defined for TSTZ, so if I understand your question I think what you are looking for would be something like this:

```sql
require icu

CREATE VIEW test AS 
    SELECT when::TIMESTAMPTZ AS when, measure 
    FROM "test.parquet";

SET TimeZone='Europe/Rome';

SELECT HOUR(when), SUM(measure) 
FROM test
GROUP BY 1
ORDER BY 1;
```

**Comment by fgenoese** [comment]
See below for what I have in mind (example with dummy data). It seems that I cannot group by the timezone-aware _date_, can I?

```python
import duckdb as duckdb
import pandas as pd
import numpy as np

start = pd.Timestamp('20220101 00:00', tz='Europe/Rome')
end = pd.Timestamp('20220101 06:00', tz='Europe/Rome')
index = pd.date_range(start,end,freq='H')[:-1]
data = np.arange(1, len(index)+1 )
df = pd.DataFrame( columns=["value"],  data=data, index=index ) 
print(df)
df.to_parquet("test.parquet")

con = duckdb.connect(database=':memory:')
con.execute('SET TimeZone = "Europe/Rome"')
df = con.execute('SELECT CAST((__index_level_0__::TIMESTAMPTZ) as DATE) as day, SUM(value) FROM "test.parquet" GROUP BY 1').fetchdf()
print(df)
con.close()

df = pd.read_parquet("test.parquet").groupby(pd.Grouper(freq = 'D')).sum()
print(df)
```

```
                           value
2022-01-01 00:00:00+01:00      1
2022-01-01 01:00:00+01:00      2
2022-01-01 02:00:00+01:00      3
2022-01-01 03:00:00+01:00      4
2022-01-01 04:00:00+01:00      5
2022-01-01 05:00:00+01:00      6

         day  sum(value)
0 2021-12-31         1.0
1 2022-01-01        20.0

                           value
2022-01-01 00:00:00+01:00     21
```

**Comment by hawkfish** [comment]
Ah, the problem is that casting to `DATE` just truncates the instance. This is the second time this has come up and I think I need to remove the `TIMESTAMPTZ` => `DATE` cast. Extending the cast system is future work unfortunately.

What you need to do instead is truncate to the `day` level:

```sql
SET TimeZone = 'Europe/Rome';

SELECT DATE_TRUNC('day', __index_level_0__::TIMESTAMPTZ) AS day, SUM(value) 
FROM "test.parquet" 
GROUP BY 1
```

If you really want to get fancy, you can extract and combine the date parts in a subquery:

```sql
SELECT MAKE_DATE(parts['year'], parts['month'], parts['day']) AS day, SUM(value)
FROM (
    SELECT DATE_PART(['year', 'month', 'day'], __index_level_0__::TIMESTAMPTZ) AS parts, value
    FROM "test.parquet"
) pv
GROUP BY 1
```

**Comment by hawkfish** [comment]
Sigh, looks like `MAKE_DATE` and friends are not documented - sorry about that.

**Comment by fgenoese** [comment]
`MAKE_DATE` works, thanks! I need the full date (not just day [1-31]), as the full data set covers years of hourly data (not just six hours). For a future release, it could be worth to implement a shorter way to move from DATETIME to DATE while fully taking into account the time zone information.

**Comment by hawkfish** [comment]
> For a future release, it could be worth to implement a shorter way to move from DATETIME to DATE while fully taking into account the time zone information.

Files as #3100. This bug should be correctly importing parquet `TSTZ` values.

**Comment by fgenoese** [comment]
Just wanted to confirm that the following code works in duckdb 0.33:
```python
df = con.execute('''
   SELECT MAKE_DATE(DATE_PART(['year', 'month', 'day'], __index_level_0__::TIMESTAMPTZ)) as day, SUM(value) 
   FROM "test.parquet" GROUP BY 1
''').fetchdf()
```

Thanks a bunch for your help @hawkfish! Closing this now, issue is fixed.

**Comment by fgenoese** [comment]
Related:

https://github.com/duckdb/duckdb/discussions/7147#discussion-5106401
