### ISSUE TITLE
“DuckCon” - First DuckDB User Group Meeting on April 14th

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#3086]
https://www.meetup.com/duckdb/events/283318615

**Comment by hannesmuehleisen** [comment]
@hamilton it is of course not. Did you want to add something? :)

**Comment by nojvek** [comment]
Will this be streamed online?

**Comment by hannes** [comment]
Its going to be on Zoom

**Comment by zsz00** [comment]
Is there a video of the meeting ?

**Comment by Mytherin** [comment]
The recording can be found [here](https://www.youtube.com/watch?v=8LuIbN1ZYWI)
