### ISSUE TITLE
Feature Request: way for `EXPLAIN ANALYZE` to return a JSON string instead of the ascii representation as a result set

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#3094]
# Problem Statement

Currently, `EXPLAIN ANALYZE` returns an ascii representation of the plan.

This is the perfect representation when someone is using duckdb in an _interactive environment_ such as a jupyter notebook. Usually the output you'd want from this kind of query is a flexible text-based representation that enables the data analyst to understand what the query is doing.

But for _programmatic_ use-cases, the ascii representation does not work. Instead of having a human in the loop analyzing the query, it's the _computer_ that needs an easy way to understand the query so that it can do things with the plan – for instance, do further analysis on the sources, analyze the scans and projections in different ways. Which likely means a JSON string is more appropriate.

There is a work-around we can employ. Setting these pragmas

```
PRAGMA enable_profiling=json;
PRAGMA profiling_output='./profile.json';
```

... and then reading back `profile.json` into one's application. But this is quite limited. Some of the assumptions of the work-around break down when my build target uses `duckdb-wasm` instead of the node client.

# Proposed Solution

A way to tell any client (WASM, Node, Python, R, etc.) that the output of an `EXPLAIN ANALYZE` query should return the same JSON returned by the `enable_profiling` pragma would be ideal. Defaulting to ascii seems like a great option to uphold the current expectation for interactive users.

A pragma-based approach would likely give maximum flexibility to users for myriad use-cases, including in the CLI. But I'm open to any solution that enables the computer to parse the JSON representation. It seems that `PRAGMA enable_profiling=json` could also apply to `EXPLAIN ANALYZE` but perhaps this breaks a mental model of interactive vs. programmatic in some way I haven't thought of.

**Comment by MhmdSaiid** [comment]
Sorry to re-open this, but this only works for `EXPLAIN ANALYZE` and not `EXPLAIN`. Would it be possible to add it?
