### ISSUE TITLE
Consider updating apache/thrift to 0.16.0

### ISSUE THREAD

**Issue by jeremiahpslewis** [duckdb/duckdb#3095]
#### What happens?
Versions of apache/thrift prior to 0.16.0 have capitalization issues in apache/thrift for windows and cause duckdb cross-compilation issue which require the following patch (even for the latest duckdb version) ([here](https://github.com/JuliaPackaging/Yggdrasil/blob/master/D/DuckDB/bundled/patches/0001-right-case-for-winsock2.h.patch).

#### To Reproduce
This build script: https://github.com/JuliaPackaging/Yggdrasil/blob/master/D/DuckDB/build_tarballs.jl

#### Environment (please complete the following information):
 - OS: Crosscompile Linux -> Windows
 - DuckDB Version: 0.3.2
 - DuckDB Client: Julia

**Comment by hannesmuehleisen** [comment]
Our thrift version is heavily patched/stripped, we might just be able to remove the winsock include altogether.

**Comment by jeremiahpslewis** [comment]
Ok, cool, sounds good. thought that some of the patches came from patching winsock and you might be able to return to 'upstream' :)

**Comment by jeremiahpslewis** [comment]
Think this PR should resolve the last issue: https://github.com/duckdb/duckdb/pull/3097
