### ISSUE TITLE
Documentation of compression options

### ISSUE THREAD

**Issue by trenta3** [duckdb/duckdb#3106]
Hi and thank you for this great project!
Looking into the issues I found out that there is the option to apply compression to single rows in a create table statement, but I'm having troubles into understanding what kind of option I should apply for my own data, and I have not found those formats documented somewhere.

From the command line I learned that the compression options can be `none`, `uncompressed`, `rle`, `dictionary`, `pfor`, `bitpacking` or `fsst`.
In my use case I have certain float and varchar fields which contain multiple repeated values in records inserted in the same batch. Which of the compression options should I choose for these columns?

**Comment by Mytherin** [comment]
The system itself will automatically choose the best compression option available. Overriding the automatic compression detection and choosing a compression option manually should really only be used for debugging/profiling purposes or in edge cases when the system makes one choice (e.g. best compression ratio) but you want another (e.g. best performance).

Note that the compression is still in active development and those options are mostly placeholders, e.g. dictionary, pfor and fsst have not been implemented yet. Expect the compression to improve as we develop it further (see e.g. #3109).

**Comment by trenta3** [comment]
Thank you for the reply, but I would really like to understand the different kinds of compression available, and especially if there is one that is able to efficiently compress repeated elements, which are however impossible to categorize as an enum because their size increases slowly with respect to the number of inserted elements, so they are not a fixed set but compressing them gives a huge compression factor.

**Comment by trenta3** [comment]
Sorry for double posting, but I read more carefully the linked PR and from what I understand that would suit my use case really well. So I think I would have to wait for it to get merged.

**Comment by trenta3** [comment]
I'm closing the issue since the PR got merged and the new release of duckdb seems to solve my use case. Thanks!
