### ISSUE TITLE
ILIKE and ~~ equivalents to LIKE do not support escape clause

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#3108]
#### What happens?
This is another one I ran into when doing documentation, so it's likely not widely used!

When using `ILIKE` or any of the (`~~, !~~, ~*, !~*` ) syntax instead of a `LIKE`-style expression, the escape clause is not supported. 

LIKE escape PR is #640.
 
#### To Reproduce
These queries run:
```sql
select 'a%c' like 'a$%c' escape '$';
select 'a%c' ilike 'a%C';
select 'a%c' ~~ 'a%c';
```
These queries do not run:
```sql
select 'a%c' ilike 'a$%C' escape '$';
Error: Binder Error: No function matches the given name and argument types 'like_escape(VARCHAR, VARCHAR)'. You might need to add explicit type casts.
        Candidate functions:
        like_escape(VARCHAR, VARCHAR, VARCHAR) -> BOOLEAN

LINE 1: select 'a%c' ilike 'a$%C' escape '$';
```
```sql
select 'a%c' ~~ 'a$%c' escape '$';
Error: Parser Error: parser error : syntax error at or near "escape"
LINE 1: select 'a%c' ~~ 'a$%c' escape '$';
```
#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.2
 - DuckDB Client: DuckDB CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! I have implemented ILIKE ESCAPE in #3121.

As for the operators not supporting escape - this is intended and Postgres exhibits the same behavior there. The operators are a shortcut for a non-escaped like, and are regular binary operators. As such they only support two arguments. For using an escape either the function `[i]like_escape` should be used directly, or the special `.. LIKE .. ESCAPE ..` syntax should be used as per the SQL standard.
