### ISSUE TITLE
STRFTIME crashes with non-string format argument

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#3118]
#### What happens?
DuckDB crashes when the `STRFTIME` format string is not a string. Ask me how I found this out.

#### To Reproduce
```SQL
SELECT STRFTIME('2019-01-23'::DATE, 42)
```
#### Environment (please complete the following information):
 - OS: OSX
 - DuckDB Version: latest master
 - DuckDB Client: CLI

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by arjenpdevries** [comment]
How did you discover this Hannes?

**Comment by hannesmuehleisen** [comment]
Well I was prototyping an ENUM-based method of representing strings from R and it started crashing on me. But takes a while to stop doubting your new stuff and start doubting the existing code. In this case it was the latter...

**Comment by Mytherin** [comment]
Should be fixed by #3343
