### ISSUE TITLE
Transactional `INSERT` + `ALTER TABLE ADD COLUMN` + `INSERT`  erases data values written to new column

### ISSUE THREAD

**Issue by aarashy** [duckdb/duckdb#3127]
#### What happens?
If, within the same transaction, you:
1. add a row
2. add a column without specifying a default
3. add another row, attempting to put a value in the new column

then no matter what you try to write to the new column, and no matter what its data type, the write will fail and you will always read back NULL. The only way to write a non-NULL value is to commit the transaction and start a new one.

According to the DuckDB documentation, adding a column should fully respect transactional semantics.
> ALTER TABLE changes the schema of an existing table. All the changes made by ALTER TABLE fully respect the transactional semantics - that is - they will not be visible to other transactions until committed, and can be fully reverted through a rollback.

#### To Reproduce
```
D create table test (c1 bigint);


D begin transaction;
D insert into test values (11);          -- For some reason, this step is necessary to trigger the bug.
D alter table test add column c2 bigint;  -- For some reason, it's crucial that we do not specify a DEFAULT value.
D insert into test (c1, c2) values (22, 666);
D select * from test;
┌────┬────┐
│ c1 │ c2 │
├────┼────┤
│ 11 │    │
│ 22 │    │
└────┴────┘
D rollback transaction;

-- But if we commit the transaction after adding the column, we will get the expected result. 

D begin transaction;
D insert into test values (11);
D alter table test add column c2 bigint;
D commit transaction;
D insert into test (c1, c2) values (22, 666);
D select * from test;
┌────┬─────┐
│ c1 │ c2  │
├────┼─────┤
│ 11 │     │
│ 22 │ 666 │
└────┴─────┘
```

#### Environment:
 - OS: Monterey 12.2
 - DuckDB Version: The bug is present in duckdb 0.3.1 and 0.3.2. This issue notably was NOT present in duckdb 0.2.9!
 - DuckDB Client: CLI (but I discovered it with a unit test against the Rust library duckdb-rs)

**Comment by aarashy** [comment]
Hi @Mytherin, thanks for self-assigning this. I put up a simple PR which adds this as a test case. https://github.com/duckdb/duckdb/pull/3131

Of course, it fails right now, but maybe you could merge it when you're done with your fix.

I was going to upgrade from DuckDB 0.2.9 to 0.3.2 but now I'll just wait until the version where this is patched 😸 
Thanks again!

**Comment by l1t1** [comment]
putting ddl operations in a transaction is not good.

**Comment by aarashy** [comment]
@l1t1 , could you elaborate? My app doesn't actually rely on interleaving row mutations and DDL, I just caught this in a unit test. Though, there are some situations where I want to do DDL and then row mutations in the same transaction.
My impression was that DuckDB offers fully transactional DDL.

**Comment by Mytherin** [comment]
> Hi @Mytherin, thanks for self-assigning this. I put up a simple PR which adds this as a test case. https://github.com/duckdb/duckdb/pull/3131

Thanks, I will integrate the test when I get this fixed.

> My impression was that DuckDB offers fully transactional DDL.

Yes, DDL should be fully transactional and this should indeed work.
