### ISSUE TITLE
[C++] Add BYTE_STREAM_SPLIT encoder and decoder for Parquet Files feature request

### ISSUE THREAD

**Issue by AldoMyrtaj** [duckdb/duckdb#3133]
Dear Community, 

First of all thank you for the great work you have done with duckdb. We are generating a large amount of data and we them on parquet files. It is very important for us that we could use the BYTE_STREAM_SPLIT as it really helps on float value type compressing. In the [apache/arrow](https://github.com/apache/arrow) community they have already introduced this [feature](https://github.com/apache/arrow/commit/25fd97b81a65df7aca5d5f3ce482a1126bb01b83) and I was wondering if you plan to or are already working in this feature?

**Comment by stackedsax** [comment]
@AldoMyrtaj we'd like to see this, too.  If this comment doesn't resurrect the ticket, perhaps you or I should create a new one?
