### ISSUE TITLE
Docs: missing docs for EXCLUDE, REPLACE

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#3135]
I was delighted to find #2199, which solved a problem I had! Unfortunately I only found out about it when a coworker told me what to google—this syntax is completely missing from the [documentation for SELECT](https://duckdb.org/docs/sql/statements/select), which I'd been dutifully relying on until that point.

Any chance of getting the docs updated to include these features? (I'm a bit curious what else might be missing!)

**Comment by Alex-Monahan** [comment]
Good suggestion! Thank you!

**Comment by tsengtammy** [comment]
+1 would love this to be in docs -- just found out about this from Carl!

**Comment by Alex-Monahan** [comment]
We have an upcoming blog post that includes it, but you are correct it should be documented!

**Comment by larryhengl** [comment]
The recent blog post
https://duckdb.org/2022/05/04/friendlier-sql.html

...nicely details the latest (super awesome) SQL features.  But in addition to missing in the docs the features are not available in the online demo page too. Any insights as to when those might be available there? No rush, just curious to play.  
Thanks!

https://duckdb.org/demo/

```
SELECT 
    r.* EXCLUDE r_regionkey, 
    n.* EXCLUDE n_regionkey
FROM region r,
     nation n
WHERE r.r_regionkey = n.n_regionkey
```

Query failed: Parser Error: syntax error at or near "EXCLUDE" LINE 1: select r.* EXCLUDE r_regionkey, ^

**Comment by Mytherin** [comment]
The live demo is indeed outdated and has been replaced with [the WASM shell](https://shell.duckdb.org). I have pushed an update that modifies the live demo links to there.
