### ISSUE TITLE
ALL_VARCHAR not supported in COPY

### ISSUE THREAD

**Issue by arjenpdevries** [duckdb/duckdb#3137]
#### What happens?

The documentation includes `ALL_VARCHAR` for `COPY` but it seems not implemented.

```
D COPY msmarco_doc FROM '/home/arjen/RU/quack/msmarco_doc_00_2' ( ALL_VARCHAR 1, DELIMITER '\\n' );
Error: Not implemented Error: Unrecognized option for CSV: ALL_VARCHAR
```
(The problem serviced in trying out the new JSON extension, where `ALL_VARCHAR` makes sense for reading JSONL source data.)

#### To Reproduce

Replace `/home/arjen/.bashrc` in any readable textfile on your system in:

```
CREATE TABLE doc (lines VARCHAR);
COPY doc FROM '/home/arjen/.bashrc' ( ALL_VARCHAR 1, DELIMITER '\\n' );
```

#### Workaround

The alternative using `read_csv_auto` works correctly:

```
CREATE TABLE doc AS 
  SELECT line FROM read_csv_auto('/home/arjen/.bashrc', columns={'line':'VARCHAR'}, delim='\\n', ALL_VARCHAR=1 );
```

Perhaps, `COPY` and `read_csv_auto` can be aligned - 
right now, they use different names for the same (semantically) parameters (e.g., `delim`)?

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: `v0.3.2`
 - DuckDB Client: `CLI`

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mickael-van-der-Beek** [comment]
This seems to still be a problem in v1.0.0
