### ISSUE TITLE
SUM of integer columns in query_df casts to float

### ISSUE THREAD

**Issue by alanhdu** [duckdb/duckdb#3143]
#### What happens?
If I use `query_df` to SUM across integers from a Pandas DataFrame, duckdb seems to cast these into floats instead.

#### To Reproduce

If you run this script
```python
import duckdb
import pandas as pd
df = pd.DataFrame({"count": [1, 2, 3]})
print(df.dtypes)   # Have int64 dtype
print()

# SUM(cont) as an float dtype!
print(duckdb.query_df(df, "df", "SELECT SUM(count) FROM df").fetchdf().dtypes)
```

You will see:

```
count    int64
dtype: object

sum(count)    float64
dtype: object
```

which shows that the SUM of integers is becoming a float somehow. Note that `MAX` and `MIN` aggregations preserves the integer dtype, so this seems to be a problem with the SUM.

#### Environment (please complete the following information):
 - OS: Linux (Fedora 34)
 - DuckDB Version: python-duckdb==0.3.2, pandas=1.4.1, numpy=1.22.2, and pyarrow=2.0.0 (all installed via conda).
 - DuckDB Client: Python 3.8

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
Yes -- I have tried against the latest prelease (0.3.3.dev432) and this still happens.

**Comment by Mytherin** [comment]
This is caused by `sum` returning an `int128` for numeric types as part of overflow prevention, which then gets cast into a double since Pandas does not support `int128` natively.

**Comment by hannes** [comment]
Could you maybe also say why this is a problem?

**Comment by alanhdu** [comment]
> Could you maybe also say why this is a problem?

The main problem we have here is the rounding -- we have a dataset + query summing many counts that don't overflow `int64` but can't be represented as a `float64`. Using `pd.DataFrame({"count": [999804707614896129, 1]})` in the above example would be an artificial way of doing this (I know that this is "close" to overflowing, but in this particular application it doesn't). 

> This is caused by sum returning an int128 for numeric types as part of overflow prevention, which then gets cast into a double since Pandas does not support int128 natively.

Hm... that makes sense. Would it be possible to cast to int64 and raise an error if we overflow int64? That feels more intuitive to me on the Python API side (technically I think Pandas wraps on overflow for integer sums, but an error would be nicer).

**Comment by Mytherin** [comment]
> Hm... that makes sense. Would it be possible to cast to int64 and raise an error if we overflow int64? That feels more intuitive to me on the Python API side (technically I think Pandas wraps on overflow for integer sums, but an error would be nicer).

You could add a cast after the sum, e.g. `SUM(val)::INT64`.
