### ISSUE TITLE
How does one quit the CLI "cleanly"

### ISSUE THREAD

**Issue by vegabook** [duckdb/duckdb#3168]
double ^C^C quite the Command Line Interface, but there are a bunch of `.wal` files and temp directories which then corrupt the database, or at the very least, mean it takes ages when re-opened as it seems to clean things up. 

As such, is there a way "cleanly" to exit the CLI so that it consolidates all its files? This does not seem to be [documented](https://duckdb.org/docs/api/cli.html).

**Comment by ragtux** [comment]
Perhaps I'm misunderstanding but maybe the dot command `.quit` ?

**Comment by arjenpdevries** [comment]
Try `^D` instead!

**Comment by hannes** [comment]
`.quit` or `CTRL-D` indeed.
