### ISSUE TITLE
PRAGMA database_size on read_only connection crash python

### ISSUE THREAD

**Issue by hcoohb** [duckdb/duckdb#3169]
#### What happens?
If trying to query pragma database_size  to know memory consumption on a connection to a db opened with read_only=True, 
It **crashes python**.

#### To Reproduce
```python
import duckdb

conn = duckdb.connect("db2.duckdb", read_only=False)
print("With read/write:")
df = conn.execute("PRAGMA database_size").fetchdf()
print(df)
conn.close()
conn = duckdb.connect("db2.duckdb", read_only=True)
print("With read only:")
df = conn.execute("PRAGMA database_size").fetchdf()
print(df)
conn.close()
```
results in:
```
With read/write:
  database_size  block_size  total_blocks  used_blocks  free_blocks wal_size memory_usage memory_limit
0       0 bytes      262144             0            0            0  0 bytes      0 bytes       13.7GB
With read only:
```
#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python 3.8.10

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
Good catch, also crashes on OSX
