### ISSUE TITLE
TPCH queries run significantly slower through python compared to benchmark runner

### ISSUE THREAD

**Issue by mericas** [duckdb/duckdb#3186]
#### What happens?
Running on an Epyc 7763, comparing benchmark results to those run through python, some queries are significantly slower on python (and a few are faster on python).  SF01, 1 thread
	         benchmark	Python
Query 01:	0.082	0.522
Query 02:	0.128	0.033
Query 03:	0.757	0.133
Query 04:	0.090	0.136
Query 05:	0.047	0.105
Query 06:	0.008	0.054
Query 07:	0.113	0.182
Query 08:	0.041	0.118
Query 09:	0.131	1.383
Query 10:	0.613	0.315
Query 11:	0.145	0.014
Query 12:	0.090	0.283
Query 13:	0.290	0.14
Query 14:	0.026	0.054
Query 15:	0.706	0.091
Query 16:	0.083	0.058
Query 17:	0.490	0.135
Query 18:	0.610	0.34
Query 19:	0.050	0.393
Query 20:	0.511	0.116
Query 21:	0.751	0.519
Query 22:	0.035	0.051

#### To Reproduce
benchmark_runner benchmark/tpch/sf1/q01.benchmark # for all queries

python script with
```
    con = duckdb.connect(database=':memory:', read_only=False)
    con.execute(f"CALL dbgen(sf=1)")
    con.execute("PRAGMA threads=1")
    for query in rage(1, 23)
       df = con.execute(open(f"{args.query_dir}/q{query:02d}.sql").read()).fetchdf()  
```

#### Environment (please complete the following information):
 - OS: [e.g. iOS] Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)
 - DuckDB Version: [e.g. 22]  0.3.3.dev528+g1d34cb43a
 - DuckDB Client: [e.g. Python] Python

#### Before Submitting

- [Y ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ Y] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
The benchmark runner by default uses all available threads. Are you running it with `--threads=1`?

**Comment by mericas** [comment]
I did not specify --threads.  That was the issue.  The results are now as expected:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">
In-memory | benchmark | Benchmark T=1 | Python
-- | -- | -- | --
Query 01: | 0.082 | 0.515 | 0.522
Query 02: | 0.128 | 0.036 | 0.033
Query 03: | 0.757 | 0.124 | 0.133
Query 04: | 0.090 | 0.148 | 0.136
Query 05: | 0.047 | 0.115 | 0.105
Query 06: | 0.008 | 0.054 | 0.054
Query 07: | 0.113 | 0.185 | 0.182
Query 08: | 0.041 | 0.124 | 0.118
Query 09: | 0.131 | 1.468 | 1.383
Query 10: | 0.613 | 0.336 | 0.315
Query 11: | 0.145 | 0.015 | 0.014
Query 12: | 0.090 | 0.291 | 0.283
Query 13: | 0.290 | 0.146 | 0.14
Query 14: | 0.026 | 0.064 | 0.054
Query 15: | 0.706 | 0.095 | 0.091
Query 16: | 0.083 | 0.054 | 0.058
Query 17: | 0.490 | 0.129 | 0.135
Query 18: | 0.610 | 0.349 | 0.34
Query 19: | 0.050 | 0.409 | 0.393
Query 20: | 0.511 | 0.118 | 0.116
Query 21: | 0.751 | 0.529 | 0.519
Query 22: | 0.035 | 0.054 | 0.051
</body>
</html>

**Comment by mericas** [comment]
with --threads=1 benchmark_runner and python are similar in performance

**Comment by Alex-Monahan** [comment]
Python's DuckDB client should already be parallelized - are you not seeing speedups with multithreaded DuckDB in Python?

**Comment by mericas** [comment]
I am seeing speedup for most queries as I increase threads.  And you can see in my results that some queries got a lot better.   But with SF01 and threads=256 I suspect the overhead of that many threads outweighs the benefit for some queries.  Higher scale factors see more benefit on most queries.  Some queries see no benefit (Q16, for example, gets worse with more than 1 thread).

**Comment by Alex-Monahan** [comment]
The optimal number of threads to specify for DuckDB should be the same as your CPU's hardware threads. If you have a multi-threaded CPU (most modern CPU's!), threads will equal CPU cores * 2. What system/processor are you running DuckDB on? 

Thanks for experimenting!

**Comment by mericas** [comment]
I disagree.  The optimal number of threads is not always the same as the CPU's hardware threads.  In my case I'm running on 2 x Epyc 7763 = 128C, 256T.  As my initial data shows, sometimes 1T outperforms 256T.  Even at lower thread levels I see some queries (16, for example) will not scale with more threads.  If I look at SF100 8T, for example (bound to the primary HW thread) I can see q16 CPU utilization is 26%.   Q22 is 40%  Q04 is 51%.  More threads is not always better.

**Comment by l1t1** [comment]
> Python's DuckDB client should already be parallelized - are you not seeing speedups with multithreaded DuckDB in Python?

how to set threads on python?

**Comment by mericas** [comment]
> how to set threads on python?

It is in the text of the issue
` con.execute("PRAGMA threads=1")`
