### ISSUE TITLE
Invalid Input Error on CSV

### ISSUE THREAD

**Issue by brdy1** [duckdb/duckdb#3193]
#### What happens?
Invalid Input Error on CSV ingestion

Invalid Input Error: Error on line 7456991: expected 150 values per row, but got 2. (DELIMITER=',' (auto detected), QUOTE='"' (auto detected), ESCAPE='' (auto detected), HEADER=1 (auto detected), SAMPLE_SIZE=10240, ALL_VARCHAR=1)

Table has 150 columns.

#### To Reproduce
Download CSV (17.8M rows) from Snowflake via query 'select * from table'.

con = duckdb.connect(':memory:')
con.execute("create table t1 as select * from read_csv_auto ('mycsv.csv', all_varchar=1)")

Error is triggered.

#### Environment (please complete the following information):
 - OS: Windows 10 Pro
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Have you looked at line 7456991 in the CSV file? My first suspicion would be that either the CSV is malformed, or the parameters are incorrect.

**Comment by rsund** [comment]
Some more things to try:
- Check that the encoding of CSV file is UTF-8. I have had some problems with this particular issue and there has been a lot of extra work to convert some 15GB+ CSV-files to other encoding manually even if the problem affects only a few lines. 
- Try to scan the whole file (for autoformatting) using `SAMPLE_SIZE=-1`. You had `ALL_VARCHAR=1`, so this probably won't change anything, but maybe you get a different error message during the format scan?
- Use `SKIP`-parameter to check are there more problems after the line 7456991.
- Check that there are no special cases of `QUOTE` and `ESCAPE` not seen before that line.
- Check that no extra delimiter characters are present in the proximity of the problematic line.
- Extract the smaller part of the CSV that contains the problematic line and try to send a minimal reproducible example here.

It would certainly be nice if:
- DuckDB would support ENCODING-parameter in CSV-reader
- A parameter that would SKIP/"CORRECT" (e.g. by putting `NULL`s to potentially missing columns) the erroneous lines could be given
- The erroneous line (or a few lines around it and maybe a header line if included) could be easily outputted

**Comment by asuagar** [comment]
I have a similar problem with a CSV of mine. It would be a good feature a parameter to define the parser behavior on bad lines (e.g. error, warn or skip).

**Comment by zerbfra** [comment]
I second the fact that a parameter that would SKIP the erroneous lines would be very appreciated. This way we will handle CSV with malformed rows.

**Comment by Mytherin** [comment]
We have the `IGNORE_ERRORS` option now that ignores all malformed rows. Perhaps give that a try?

**Comment by njaremko** [comment]
@Mytherin For the record, `IGNORE_ERRORS` doesn't seem to help if you encounter an invalid character sequence in a `latin-1` encoded file. It just blows up with `Invalid unicode (byte sequence mismatch) detected in CSV file`

**Comment by coolbq** [comment]
Actually, `IGNORE_ERRORS` option seems doesn't work for this case.
![image](https://github.com/duckdb/duckdb/assets/2296444/ea1ead8a-324b-4aba-9ee2-05cae1d0dc1d)


> We have the `IGNORE_ERRORS` option now that ignores all malformed rows. Perhaps give that a try?

**Comment by mikaelhg** [comment]
@coolbq, I happened to be reading FAO CSV files with duckdb as well, and as they are ISO-8859-1 encoded, the easy way to import them to duckdb was to read them with pandas, which does have an encoding parameter in the `pd.read_csv` function.

```python
import pandas as pd
import duckdb

csv_filename = "data/Production_Crops_Livestock_E_All_Data.csv"
df = pd.read_csv(csv_filename, encoding="ISO-8859-1")
duckdb.sql('CREATE TABLE production_all_data AS SELECT * FROM df')
```

**Comment by kaiwen-wang** [comment]
> @Mytherin For the record, `IGNORE_ERRORS` doesn't seem to help if you encounter an invalid character sequence in a `latin-1` encoded file. It just blows up with `Invalid unicode (byte sequence mismatch) detected in CSV file`

Ever fix this issue?

**Comment by kaiwen-wang** [comment]
Another issue is that I have a large dataset, and it doesn't return what the line number or invalid unicode is, so I can't delete it

**Comment by Mytherin** [comment]
These issues should be fixed yes - have you tried this with the latest version of DuckDB? If the issue persists please open a new reproducible issue and we can have a look.

**Comment by kaiwen-wang** [comment]
I tried the latest nightly version and it seems to work fine. But now I get errors when trying to create an index.

**Comment by Mytherin** [comment]
Feel free to open an issue if you think there is a bug. It’s hard to help with such limited information.

**Comment by kaiwen-wang** [comment]
Thank you for the follow-up

INTERNAL Error: Invalid node type for GetChildMutable.
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
D


I would attempt to debug it myself first if I knew how. Claude gave me `EXPLAIN` but that doesn't tell me much either. I think the problem is that to create an index, it has to be done in-memory, so I need like 100GB of RAM?

<img width="958" alt="image" src="https://github.com/user-attachments/assets/a5f96103-2af4-4486-9378-60ddc650444e">

**Comment by beausoleilmo** [comment]
I had this error and investigated. 

I pasted the error below (I was running the code in R, but the error message is almost the same as the output from CLI). 

In my case, the problem was that the 'read_csv_auto' function was assuming the CSV was separated by `|` because only ONE LINE (line 2566) had a `|`. But the data was separated by `,` (commas). 

```
CREATE OR REPLACE TABLE my_table as SELECT * from read_csv_auto('test.csv')

Error in `duckdb_result()`:
! Invalid Error: Invalid Input Error: CSV Error on Line: 2566
Original Line: id1,id2,id1-id2,id1-id2-id3,1,-2,text1 | text2,2025-01-01 08:47,27 ### This line has `|` 👎 
Expected Number of Columns: 1 Found: 2
Possible fixes:
* Disable the parser's strict mode (strict_mode=false) to allow reading rows that do not comply with the CSV standard.
* Enable null padding (null_padding=true) to replace missing values with NULL
* Enable ignore errors (ignore_errors=true) to skip this row

  file = test.csv
  delimiter = | (Auto-Detected) ### See how this line is NOT assuming the correct delimiter 👎 
  quote = (empty) (Auto-Detected)
  escape = (empty) (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Auto-Detected)
  skip_rows = 0 (Auto-Detected)
  comment = (empty) (Auto-Detected)
  strict_mode = true (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding = 0
  sample_size = 20480
  ignore_errors = false
  all_varchar = 0
```

Instead of letting the function *assume* the delimiter, I specified it : 

```
read_csv_auto('test.csv', delim = ',') ### See how this line specifies the delim, which now works 👍 
```

Quick question : Is the `|` preferentially set as delimiter with `read_csv_auto` even if the majority of the data is separated by `,`?

**Comment by Mytherin** [comment]
There is no order of preference for delimiters in `read_csv`. If you could share an (anonymized) version of the CSV file we could investigate why this is chosen as delimiter.
