### ISSUE TITLE
Parquet files with different/additional columns per (partitioned) folder

### ISSUE THREAD

**Issue by thinkORo** [duckdb/duckdb#3203]
My data is partitioned by year, month and day, for instance: /data/2022/02/22/file[1..2000].parquet

All files always have at least one fixed format (id, time, val1, val2, ...), where some can have additional columns (valX, valY, valZ).

These different columns result from the flattening of a structured JSON field, which can simply be filled differently per record (and thus creates different structures in the Parquet files).

Even if I select "only" using the always known fields (id or time or val1), I get the error message that the schema is not the same everywhere.

Unfortunately, there is also not this one file that contains all columns, so that unfortunately the solution from ticket #2877 does not work.

The only thing that would work would be a selection per file and a "connection" of all data via UNION ALL, like.

```sql
SELECT COUNT(a.id) FROM
(
SELECT id, time, val1 FROM parquet_scan('/data/2022/02/22/file1.parquet)
UNION ALL
SELECT id, time, val1 FROM parquet_scan('/data/2022/02/22/file2.parquet)
) a
```

However, since I have a different number of files due to the partitioning, this is not very practical.

Is there any best practice to handle such an, well, 'inconsistent' structure?

Many thanks in advance
Oliver

**Comment by thinkORo** [comment]
Hi Mark,

I have tried the change and can confirm that it works as described. Thank you for your support.

Do you know when a new release (0.33) is planned? I have compiled duckdb myself, but would also be happy about the inclusion in DBeaver and a new package on pip for my Python code.

**Comment by Mytherin** [comment]
The new release should be out next Monday.
