### ISSUE TITLE
Parquet extension for Apple silicon

### ISSUE THREAD

**Issue by lneves** [duckdb/duckdb#3204]
The Parquet extension is not currently available for Apple silicon

```
% uname -mrsv 
Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
```
Error loading the extension:
```
D Install parquet;
Error: IO Error: Failed to download extension http://extensions.duckdb.org/5aebf7dac/osx_arm64/parquet.duckdb_extension.gz
```

**Comment by hannes** [comment]
I've just added this in my PR #3201

**Comment by mmzeeman** [comment]
Ah, that is what is causing this:

IO Error: Failed to download extension http://extensions.duckdb.org/662041e2b/osx_arm64/parquet.duckdb_extension.gz

**Comment by carlopi** [comment]
Thanks for the report, I believe all extensions have been properly updated for the last few versions, and in particular for current release (0.7.1).
