### ISSUE TITLE
INTERNAL Error: Skip not implemented for StructColumnReader when filtering for uncommon events in a large dataset

### ISSUE THREAD

**Issue by ZaSkittles** [duckdb/duckdb#3205]
#### What happens?
When using an equals opertator for sparse elements in a sizable dataset that contains a map I notice an error:
```
RuntimeError: INTERNAL Error: Skip not implemented for StructColumnReader
```
Also worth noting, when the query is changed to instead use an `IN` clause (as opposed to equals) I no longer see the error. 

#### To Reproduce
This snippet doesn't seem to error if the data set is smaller ie, if you use a range of 1,000 instead of 10,000.

```
import pyarrow as pa
import pyarrow.parquet as pq
import duckdb 
maptype = pa.map_(pa.string(), pa.string())

elems = []
filter_vals = []
for i in range(10000):
    key_name = str(chr(i % 26 + 65))
    filter_vals.append(str(i))
    if i % 10 == 0:
        value = None
    else:
        value = 'foo'
    elems.append([(key_name,value)])

t = pa.Table.from_pydict({'my_map':elems, 'filter': filter_vals}, pa.schema([pa.field('my_map',maptype), pa.field('filter', pa.string())])) 
pq.write_table(t, 'test')
cursor = duckdb.connect()
cursor.execute("SELECT my_map['A'], * FROM parquet_scan('test') where filter == '0'").fetchall()
```

#### Environment (please complete the following information):
 - OS: iOS (and Ubuntu)
 - DuckDB Version: .3.2 (and latest master off of .3.3)
 - DuckDB Client: python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
This should probably be implemented, yes :) Thanks for providing a test case!

**Comment by ZaSkittles** [comment]
Awesome! Thanks for the super quick fix.
