### ISSUE TITLE
Progress Bar Rework

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#3227]
Looking at the progress code - it seems there are several problems with it that are likely caused by it not being updated correctly along with other changes to the system. The main ones that I can see being:

* Only the `TABLE_FUNCTION` is supported w.r.t. reporting progress, none of the other sources are supported.
* The progress is reported only from the last pipeline, rather than combining the progress of all the pipelines together.
* For the table function specifically, the API reads the progress from the `bind_data` which is incorrect. The `bind_data` should be read-only (as it is passed in as constant), which means by definition it should not be sufficient to report progress since it should never change.

As a solution, I propose the following (more involved) rework:

* Progress should be part of the `Source` API for the physical operators. There should be a new method `GetProgress()` that takes as parameter the global source state and returns the progress for that given source. This method can then be implemented locally for the various sources (including e.g. hash table scans).
* The progress of different pipelines should be combined. Ideally this would be done using a weighted combination based on e.g. max cardinality, rather than a straightforward combination. This way when we have e.g. a scan of orders and a scan of lineitem followed by a scan of a single-row aggregate the progress would not randomly jump around. A straightforward combination will still be better than the current state, however.
* The get_progress API for table functions needs to change so that it takes the parallel state and the operator state. It should read the progress from there, and any table functions that change the bind state need to be redesigned so they no longer do so and instead operate on the parallel state and operator state only as intended.

_Originally posted by @Mytherin in https://github.com/duckdb/duckdb/issues/3220#issuecomment-1067139519_

**Comment by leiysky** [comment]
I'd like to know how would the progress bar display?

**Comment by Mytherin** [comment]
Most of this has been implemented already
