### ISSUE TITLE
Arrow Flight RecordBatchReader and DuckDB 

### ISSUE THREAD

**Issue by Arttii** [duckdb/duckdb#3246]
I was playing with the idea of being able to fetch a table from an Arrow Flight endpoint in a streaming fashion and querying that table via duckdb. This works if the entire table gets materialized in memory on the client side, where duckdb is running. I was wondering if there is some way to feed an arrow `RecordBatchReader` into duckdb or connect the two?

I am quite new both to duckdb and arrow, so please let me know if this does not really make sense.

**Comment by pdet** [comment]
Hm, I think that currently, you can only feed ArrowTables and Datasets.

Extending the API to handle RecordBatchReaders shouldn't be too difficult, so if you are interested, I'm happy to review a PR :-).

**Comment by Arttii** [comment]
So my first try was to add the support  in `PythonTableArrowArrayStreamFactory::Produce` and  pass the reader through to `arrow_array_stream`, but it's not really working for aggregations as the reader is exhausted.

**Comment by pdet** [comment]
Can you open a draft?

**Comment by Arttii** [comment]
I added a very basic PR #3257.
