### ISSUE TITLE
Error: Binder Error: column must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by amirrajan** [duckdb/duckdb#3247]
#### What happens?
The following query works in Postgres, but not DuckDb.

```sql
  prepare example (int) as
  select ch p01,
         round(n + $1) p02
  from (
        values
          ('a', 1.1::real),
          ('a', 1.2::real),
          ('b', 2.3::real),
          ('c', 3.4::real)
        ) as T(ch, n)
  group by ch, round(n + $1)
  order by ch asc;
  
  execute example(1);
```

#### To Reproduce
This is the DuckDb equivalent to the query above:
```sql
  prepare example as
  select ch p01, round(n + ?) p02
  from (
        values
          ('a', 1.1::real),
          ('a', 1.2::real),
          ('b', 2.3::real),
          ('c', 3.4::real)
        ) as T(ch, n)
  group by ch, round(n + ?)
  order by ch asc;

  execute example(1);
```

This is the error I get:
```
Error: Binder Error: column "n" must appear in the GROUP BY clause or be used in an aggregate function
```

This variant however _does_ work:
```sql
  prepare example as
  select ch p01, round(n + ?) p02
  from (
        values
          ('a', 1.1::real),
          ('a', 1.2::real),
          ('b', 2.3::real),
          ('c', 3.4::real)
        ) as T(ch, n)
  group by ch, p02
  order by ch asc;

  execute example(1);
```

#### Environment (please complete the following information):
 - OS: MacOS
 - DuckDB Version: Compiling from `master`, git hash: `3111480a9ef146d89be8137e6fa960e51cc2`
 - DuckDB Client: Using the duckdb binary directly located at `./build/release/duckdb`.

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

The DuckDB equivalent is actually this:

```sql
  prepare example as
  select ch p01,
         round(n + $1::int) p02
  from (
        values
          ('a', 1.1::real),
          ('a', 1.2::real),
          ('b', 2.3::real),
          ('c', 3.4::real)
        ) as T(ch, n)
  group by ch, round(n + $1:: int)
  order by ch asc;
```

Question marks become separate parameters, so your example is equivalent to this:

```sql
  prepare example (int) as
  select ch p01,
         round(n + $1) p02
  from (
        values
          ('a', 1.1::real),
          ('a', 1.2::real),
          ('b', 2.3::real),
          ('c', 3.4::real)
        ) as T(ch, n)
  group by ch, round(n + $2)
  order by ch asc;
```

Which then fails because the `GROUP BY` and the column in the `SELECT` are different. The error message is therefore correctly reporting that a column (`n`) is being used that is not part of the `GROUP BY`.

I do notice a separate issue here, which is that an assertion is triggered on your second example, so I will leave the issue open for now.

**Comment by amirrajan** [comment]
For posterity (in case someone comes across this issue). Here is how you'd execute this via the npm package.

```typescript
      const db = new duckdb.Database(':memory:');
      const query = `
        select ch p01,
          round(n + $1::int) p02 -- @TEST
        from (
          values
            ('a', 1.1::real),
            ('a', 1.2::real),
            ('b', 2.3::real),
            ('c', 3.4::real)
          ) as T(ch, n)
        group by ch,
          round(n + $1::int) -- @TEST
        order by ch asc;
      `;
      const params = [0];
      db.all(query, ...params, function (err: Error | null, res: Response) {
        if (err) reject(err);
        else {
          resolve(res);
        }
      });
```
