### ISSUE TITLE
Incorrect join order with Hive-partitioned Arrow Datasets

### ISSUE THREAD

**Issue by edavisau** [duckdb/duckdb#3254]
#### What happens?
Arrow Datasets do not always join in a sensible way with the query optimiser. With large datasets this often causes out-of-memory exceptions if the order is incorrect. This was tested only with Hive-partitioned PyArrow Datasets but it could be more general than this.

I don't mind specifying the query plan myself, however without the optimiser I can't bring the filter pushdowns into Arrow scans.

My ideas for a solution to this
- Support using Arrow Scanners or RecordBatchReaders (#3246 ). That way arrow scan filters can be explicit in unoptimised queries.
- Improve cardinality estimation of PyArrow Datasets
- An arrow_scan function in the query.

Of course, it would be great if I was missing something here and there is a better way to do this.

#### To Reproduce

Apologies for the long snippet.

```python3
from pathlib import Path
import tempfile
from collections import Counter
import time

import duckdb
import pandas as pd
import numpy as np
import pyarrow.dataset as ds

# Generate dummy data and save to hive-partitioned parquet dataset
tmp_dir = Path(tempfile.mkdtemp(prefix="duckdb_example_"))
print(tmp_dir)

df_a = pd.DataFrame({
    "division": np.concatenate((np.full(shape=5_000_000, fill_value=1), np.full(shape=5_000_000, fill_value=2))),
    "level1": np.arange(10_000_000),
    "level2": np.arange(10_000_000, 20_000_000),
})
df_a = df_a.astype("int32")
df_a.to_parquet(tmp_dir / "table_a.parquet", index=False, partition_cols=["division"])

df_b = pd.DataFrame({
    "division": [4, 6, 7],
    "level1": [6, 100, 4],
})
df_b = df_b.astype("int32")
df_b.to_parquet(tmp_dir / "table_b.parquet", index=False, partition_cols=["division"])


# Counting occurrences of each query plan. Only one of these is sensible.
table_a = ds.dataset(tmp_dir / "table_a.parquet", partitioning="hive")
table_b = ds.dataset(tmp_dir / "table_b.parquet", partitioning="hive")

con = duckdb.connect()
query = """EXPLAIN
SELECT table_a.level2
FROM table_a
INNER JOIN table_b on table_a.level1 = table_b.level1
WHERE table_b.division = 7
"""

counter = Counter()
for _ in range(100):
    plan = con.execute(query).fetchone()[1]
    counter[plan] += 1

for plan, count in counter.items():
    print(f"Count: {count}\n{plan}\n")

con.close()


### TESTING THE QUERIES

# Testing the slow query. I created an intermediate table to allow arrow scans with filter pushdown
con = duckdb.connect()
con.execute("CREATE TABLE table_b_scanned AS SELECT * FROM table_b WHERE table_b.division = 7")
con.execute("PRAGMA disable_optimizer;")
con.execute("PRAGMA enable_profiling;")
con.execute(f"PRAGMA profiling_output='{tmp_dir / 'slow_query'}';")

start = time.time()
_ = con.execute("""SELECT *
FROM table_b_scanned
INNER JOIN table_a on table_a.level1 = table_b_scanned.level1
""").fetchall()
end = time.time()
print(end - start)

con.close()

# Testing the fast query
con = duckdb.connect()
con.execute("CREATE TABLE table_b_scanned AS SELECT * FROM table_b WHERE table_b.division = 7")
con.execute("PRAGMA disable_optimizer;")
con.execute("PRAGMA enable_profiling;")
con.execute(f"PRAGMA profiling_output='{tmp_dir / 'fast_query'}';")

start = time.time()
_ = con.execute("""SELECT *
FROM table_a
INNER JOIN table_b_scanned on table_a.level1 = table_b_scanned.level1
""").fetchall()
end = time.time()
print(end - start)

con.close()
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.3.dev585
 - DuckDB Client: Python

**Comment by edavisau** [comment]
@pdet Many thanks for the PR to support Record Batch Readers! Although the overarching issues still exists (updates below), I believe this gives me a full workaround to not use the optimizer but still achieve the intended performance. 

Update on join order: 
- I have reran my own snippet using the latest version and the join order now appears to be deterministic. Out of the 100 query plans I sample in the snippet, I used to get a 50/50 split between one join order and the other. It now consistently chooses one of those orders (all 100 plans). I am not sure which changes have causes this but at least the behavior is more consistent.
- In this example, the plan that it consistently chooses is the better one. However, I then tested it with my own datasets (100 million rows joined with 5 billion rows), and it always chooses the wrong order. The correct order takes 2.5 seconds to execute, the other one runs out of memory after about 30 seconds.

**Comment by pdet** [comment]
Hey @edavisau , this fix basically allows you to consume scanners and record batch readers directly, it does nothing in terms of the join order.

DuckDB's optimizer, in regards to the join order, is quite naive still, so it won't necessarily give you the best join order. However, we do have plans to improve it in future releases. I think you can hardcode the join order by disabling the optimizer though. In the query optimization section of the duckdb tutorial (https://github.com/pdet/duckdb-tutorial) you can see how to perform these manual optimizations.

One last thing, if I remember correctly, Arrow stream objects do not necessarily give good estimations on the cardinality of the object, which makes it even harder for the optimizer to select good join orders.
