### ISSUE TITLE
Crash when pulling datasets between Arrow and DuckDB

### ISSUE THREAD

**Issue by jonkeane** [duckdb/duckdb#3258]
#### What happens?
Since #3173 merged, we are seeing crashes + data corruption in our roundtrip tests between Arrow and DuckDB with datasets (including filter + mutates). The behavior of these is very similar to what we saw in #2912 (though those were resolved with that PR).

#### To Reproduce
We saw this error in our nightlies (where we test against DuckDB HEAD@default branch](https://github.com/ursacomputing/crossbow/runs/5596172598?check_suite_focus=true). There we're seeing invalid data being returned.

I've also reproduced this locally both with release Arrow and our current HEAD@default branch locally with the following, which variably segfaults, or returns data that does not match:

```
library(arrow)
library(dplyr)

example_data <- tibble::tibble(
  int = c(1:3, NA_integer_, 5:10),
  dbl = c(1:8, NA, 10) + .1,
  dbl2 = rep(5, 10),
  lgl = sample(c(TRUE, FALSE, NA), 10, replace = TRUE),
  false = logical(10),
  chr = letters[c(1:5, NA, 7:10)],
  fct = factor(letters[c(1:4, NA, NA, 7:10)])
)

tf <- tempfile()
new_ds <- rbind(
  cbind(example_data, part = 1),
  cbind(example_data, part = 2),
  cbind(mutate(example_data, dbl = dbl * 3, dbl2 = dbl2 * 3), part = 3),
  cbind(mutate(example_data, dbl = dbl * 4, dbl2 = dbl2 * 4), part = 4)
)
write_dataset(new_ds, tf, partitioning = "part")

ds <- open_dataset(tf)

duck <- ds %>%
    to_duckdb() %>%
    select(-fct) %>%
    mutate(dbl_plus = dbl + 1) %>%
    to_arrow() %>%
    filter(int > 5 & part > 1) %>%
    collect() %>%
    arrange(part, int) %>%
    as.data.frame()

arrow <- ds %>%
    select(-fct) %>%
    filter(int > 5 & part > 1) %>%
    mutate(dbl_plus = dbl + 1) %>%
    collect() %>%
    arrange(part, int)

all.equal(duck, arrow)
```

Steps to reproduce the behavior. Bonus points if those are only SQL queries.

#### Environment (please complete the following information):
 - OS: macOS + Ubuntu
 - DuckDB Version: HEAD@default branch
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by pdet** [comment]
Uf I thought I had added roundtrip tests on the duckdb side as well, sorry for that

**Comment by jonkeane** [comment]
No problem, there *are* roundtrip tests. Though the ones in Arrow include a few operations (so that might be the source!) or the data being slightly different is bumping into it? 

Anyway, no problem for us, I'm very glad I setup our test against duckdb dev so that this doesn't need to be a rush for either of us at release time 😄
