### ISSUE TITLE
Exported Enums Fail to Import

### ISSUE THREAD

**Issue by stevenschaefer** [duckdb/duckdb#3259]
#### What happens?
We export our db with a couple of enum types using EXPORT DATABASE 'export_folder' (FORMAT PARQUET);

Then import that to a new database using: IMPORT DATABASE 'export_folder'

Import failed with an exception, "column "1" in parquet file is of type VARCHAR, could not auto cast to expected type my_enum_type for this column\n'"

I did attempt to manually change the enum columns in the parquet file to category, hoping maybe the cast would work, but same exception (right down to VARCHAR type). I did double check my parquet file had the category types for the enum columns, but anyways would have thought strings would work

#### To Reproduce
Create an enum type w/ 2 values
Create a table using that enum type
Insert sample data, ~20 records for me
Export the database
Import the database

#### Environment (please complete the following information):
 - OS: Linux / Ubuntu 20.04
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
Yes

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
Yes, with master version

**Comment by pdet** [comment]
Hi @stevenschaefer,

I was not able to reproduce this problem on the master branch with the following test case:

```sql
# name: test/sql/types/enum/test_enum_import_parquet.test
# description: Test ENUM Types on Import/Export
# group: [enum]

statement ok
PRAGMA enable_verification

require parquet

statement ok
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

statement ok
CREATE TABLE person (
    name text,
    current_mood mood
);

statement ok
INSERT INTO person VALUES ('Moe', 'happy'), ('Diego', 'happy'), ('Pagliacci', 'sad');

# now export the db
statement ok
EXPORT DATABASE '__TEST_DIR__/enum_type'  (FORMAT PARQUET);

statement ok
DROP TABLE person;

statement ok
DROP TYPE mood;

statement ok
IMPORT DATABASE '__TEST_DIR__/enum_type'

query II
select * from person
----
Moe	happy
Diego	happy
Pagliacci	sad

query I
select typeof(current_mood) from person limit 1
----
mood

```

Can you try again using the master branch (pip install duckdb --pre),  or send the exact queries you are using?

**Comment by stevenschaefer** [comment]
I just tested yours and mine successfully with master. I did test this two weeks ago, so unless I messed up it failed then too on master. But anyways looks like 3.3 will have it working as expected, thanks
