### ISSUE TITLE
OFFSET -1  - Uncaught Exception

### ISSUE THREAD

**Issue by hmb1** [duckdb/duckdb#3271]
-1 offset causes duckdb to crash.
e.g 
~~~
CREATE  MACRO my_seq(srt, nlimit, noffset) as TABLE SELECT * FROM generate_series(srt) LIMIT nlimit OFFSET noffset;
SELECT  * FROM  my_seq(10,5,-1);
~~~

**Comment by Alex-Monahan** [comment]
Which DuckDB client are you using and what is your OS? Please follow the issue template in the future.

**Comment by hmb1** [comment]
Am using the latest code from master: 
Duckdb v0.3.2  
on
Ubuntu 20.04
