### ISSUE TITLE
HTTPFS undefined symbol exception on python dev build (linux)

### ISSUE THREAD

**Issue by IanCal** [duckdb/duckdb#3286]
#### What happens?

The HTTPFS extension can be installed, but when loading I get the error

    RuntimeError: IO Error: File "/home/ian/.duckdb/extensions/7c15866e7/linux_amd64/httpfs.duckdb_extension" could not be loaded: /home/ian/.duckdb/extensions/7c15866e7/linux_amd64/httpfs.duckdb_extension: undefined symbol: _ZTIN6duckdb9ExceptionE

This is on the latest master (duckdb-0.3.3.dev1140) as the main build does not support installing the extension (missing file on host).

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

One liner 

    python -c "import duckdb; con = duckdb.connect(':memory:'); con.execute('install httpfs').fetchall(); con.execute('load httpfs').fetchall()"

Python code

    import duckdb
    con = duckdb.connect(':memory:')
    con.execute('install httpfs').fetchall()
    con.execute('load httpfs').fetchall()

#### Environment (please complete the following information):

 - OS: Linux, ubuntu 20.04
 - DuckDB Version: 0.3.3-dev1140
 - DuckDB Client: Python
 
Python 3.9.7

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

Latest master, cannot use the cli binary unless there's a dev build of that available.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yes.

Is there another step required / something else that needs installing?

**Comment by samansmink** [comment]
Hi @IanCal thanks for reporting this, there does indeed seem to be an issue with the linking process for python. Since we're also covering this problem in issue https://github.com/duckdb/duckdb/issues/3243, i'll close this one.
