### ISSUE TITLE
IO Error when loading httpfs extension from Java

### ISSUE THREAD

**Issue by gokhanoner** [duckdb/duckdb#3288]
#### What happens?

Loading httpfs extension fails with error `Exception in thread "main" java.sql.SQLException: IO Error: File "/Users/user/.duckdb/extensions/5aebf7dac/osx_amd64/httpfs.duckdb_extension" could not be loaded`

Folder & file exists, which shows that install worked.

#### To Reproduce

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DuckDBHttpFSError {

    public static void main(String[] args) throws SQLException {
        try (Connection conn = DriverManager.getConnection("jdbc:duckdb:")) {
            try(Statement stmt = conn.createStatement()) {
                stmt.execute("INSTALL httpfs");
                stmt.execute("LOAD httpfs");
            }
        }
    }
}
```

#### Environment (please complete the following information):
 - OS: MacOS
 - DuckDB Version: 0.3.2
 - DuckDB Client: Java

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
This works fine with 0.4.0 for me on OSX. Feel free to reopen if the issue persists.
