### ISSUE TITLE
Histogram function incorrect for timestamp_s

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb#3290]
#### What happens?
The histogram aggregate function returns an incorrect result or throws an exception for `timestamp_s` input. 

I got an exception when running automated tests for my PR: https://github.com/taniabogatsch/duckdb/commit/5ea7f5d6a224978e5a5c402550e0e3df246584cb
On my system I simply get a wrong result.

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

This is the behaviour on my system.
```
D SELECT histogram(CAST('2021-08-20' AS timestamp_s));
┌──────────────────────────────────────────────┐
│ histogram(CAST('2021-08-20' AS TIMESTAMP_S)) │
├──────────────────────────────────────────────┤
│                                              │
└──────────────────────────────────────────────┘
```
This is not a even a `NULL` row.
```
D SELECT histogram(CAST('2021-08-20' AS timestamp_s)) IS NULL;
┌────────────────────────────────────────────────────────┐
│ (histogram(CAST('2021-08-20' AS TIMESTAMP_S)) IS NULL) │
├────────────────────────────────────────────────────────┤
│ false                                                  │
└────────────────────────────────────────────────────────┘
```
Here are other systems (https://github.com/taniabogatsch/duckdb/commit/5ea7f5d6a224978e5a5c402550e0e3df246584cb). These occur because I am using the histogram function for my implementation of `list_histogram(...)`.

#### Environment (please complete the following information):
 - OS: iOS
 - DuckDB Version: 22
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
Looks like missing bindings for the variant temporal types that then get promoted out of range. The error was actually happening in the output display code where it was getting an exception when it tried to render the out-of-range timestamp.

There is a general problem here with the custom binding code where it assumes that the argument types it is given will not change, but the binder immediately casts the arguments to match the declared input types. So if a function assume it will pass through the first argument (as `histogram` does) then hilarity ensues.

**Comment by Mytherin** [comment]
Should be fixed now
