### ISSUE TITLE
Should LIMIT have an effect on runtime?  TPC-H Q03

### ISSUE THREAD

**Issue by mericas** [duckdb/duckdb#3300]
#### What happens?
Looking a TPC-H Q03 @ SF100.  Remove LIMIT 10 statement at end of query and compare runtime.  They are the same.  Also ran perf to look at HW counters.  They are the same also.

#### To Reproduce
Modify q03.sql to remove LIMIT 10.  or change it to any other value.

#### Environment (please complete the following information):
 - OS: 20.04.1-Ubuntu
 - DuckDB Version: 3.3 (rebuilt from source)
 - DuckDB Client: Python

**Comment by Mytherin** [comment]
Q03 returns very few rows - on the order of 11K rows for SF1. The bulk of the time will be spent on performing the joins and aggregations. It seems plausible to me that returning those extra rows has almost no extra effect. Have you checked this on any other queries?

**Comment by mericas** [comment]
Here are my results running 20 iterations of each query with SF=100, discarding the 1st iteration.  Not exactly equal for q03 as originally reported but very small variance.  Also shows the number of rows returned.  Only q10 has a significant difference.  

If it matters, this is directly reading parquet files.

With LIMIT statement

Query 02:         0.844 s +/- 0.009 s        Rows: 100
Query 03:         3.649 s +/- 0.041 s        Rows: 10
Query 10:         4.594 s +/- 0.025 s        Rows: 20
Query 18:         9.132 s +/- 0.074 s        Rows: 100
Query 21:         14.892 s +/- 0.186 s        Rows: 100


Without LIMIT statement

Query 02:         0.888 s +/- 0.011 s        Rows: 47107
Query 03:         3.778 s +/- 0.048 s        Rows: 1131041
Query 10:         7.581 s +/- 0.056 s        Rows: 3884218
Query 18:         9.197 s +/- 0.063 s        Rows: 6398
Query 21:         14.949 s +/- 0.126 s        Rows: 39950

**Comment by Mytherin** [comment]
Thanks for the detailed report. Very interesting! I would say the only surprising observation there is that Q10 *does* get slower when removing the limit, despite the low number of rows returned. I would suspect that if you are working with hundreds of millions of rows in your tables the difference between returning 10 rows and 1 million rows from a query is negligible. I suspect there is something else going on making Q10 slower.

**Comment by Mytherin** [comment]
Closing this, as this behavior seems expected
