### ISSUE TITLE
Segmentation fault in UPDATE tbl SET clm=''

### ISSUE THREAD

**Issue by mbuechner** [duckdb/duckdb#3306]
#### What happens?
I'm getting segmentation fault error with any UPDATE. See [hs_err_pid11760.log](https://github.com/duckdb/duckdb/files/8360996/hs_err_pid11760.log)

#### To Reproduce
I would provide my database.

#### Environment (please complete the following information):
 - OS: Linux and WIndows
 - DuckDB Version: 0.3.2
 - DuckDB Client: CLI and Java

**Comment by hannes** [comment]
Could you try to make a reproducible example please?

**Comment by mbuechner** [comment]
I tried to, but the steps are probably too complex. I could provide my database if you like to?
Is there anything to check the integrity of the database?

**Comment by hannes** [comment]
Providing the database would definitely help

**Comment by mbuechner** [comment]
E-Mail?
