### ISSUE TITLE
Identical join keys are duplicated when using keyword "ON"

### ISSUE THREAD

**Issue by mayer79** [duckdb/duckdb#3317]
#### What happens?
Identical join keys are duplicated when using keyword "ON". There is a related issue in https://github.com/duckdb/duckdb/issues/2180 which does not solve the issue.

#### To Reproduce

```
import pandas as pd
import duckdb
from pyarrow import parquet as pq

# Create datasets
df1 = pd.DataFrame({"x": [0, 1, 2], "y": ["A", "B", "B"]})
df2 = pd.DataFrame({"x": [0, 1], "z": ["A", "B"]})

con = duckdb.connect()

df = con.execute("""
SELECT * 
FROM df1 A 
LEFT JOIN df2 B 
ON A.x = B.x 
AND A.y = B.z
""").fetchdf()

con.close()

df
```
The result is:
![image](https://user-images.githubusercontent.com/16206095/160560680-93c4e589-1789-4474-a9a0-3bad9cd64431.png)

The "USING" keyword does not have the problem but can be used only when all key fields are identical.

Note: I am working with tables with hundreds of columns, thus listing them all in the select statement is not feasible.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python

**Comment by Mytherin** [comment]
As far as I am aware this is how joins in SQL are supposed to work, and every database system that I have tested has exactly the same behavior. Could you name a system that has different semantics here?

Perhaps you could use `EXCLUDE` to get your desired behavior instead:

```sql
SELECT A.*, B.* EXCLUDE (x)
FROM A
LEFT JOIN B
ON A.x = B.x
AND A.y = B.z;
```

**Comment by mayer79** [comment]
@Mytherin Mark, you are right! 

The usual behavior of SQL is indeed to give columns x, y, x, z
