### ISSUE TITLE
Python executing prepared statement with parameter crashes kernel

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#3324]
#### What happens?
When executing a prepared statement using a parameter passed in as a second argument to the execute function, the Python kernel dies.

I initially ran into then when trying to pass in a list parameter to the prepared statement, but this appears to fail even on a text parameter input. If you could add a test with a list parameter as well that would be much appreciated!

Thanks as always folks!

#### To Reproduce
```python
import duckdb
duckdb_conn = duckdb.connect(':memory:')
create_output = duckdb_conn.execute("""
    create or replace table my_table as 
        select 'test1' as column1, 1 as column2, 'quack' as column3 
        union all
        select 'test2' as column1, 2 as column2, 'quacks' as column3 
        union all
        select 'test3' as column1, 3 as column2, 'quacking' as column3 
""").fetch_df()
prepare_output = duckdb_conn.execute("""
    prepare v1 as 
        select 
            column1
            , column2
            , column3 
        from my_table
        where 
            column1 = $1""").fetch_df()
```
This works:
```python
execute_output = duckdb_conn.execute("""execute v1('test1')""").fetch_df()
```
This fails:
```python
execute_output = duckdb_conn.execute("""execute v1(?)""",'test1').fetch_df()
```
This also fails:
```python
execute_output = duckdb_conn.execute("""execute v1(?)""",('test1',)).fetch_df()
```
#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.3-dev1374
 - DuckDB Client: Python 3.9 Jupyter Notebook in VS Code

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report! Any crash is surely a bug, but fyi the `PREPARE` and `EXECUTE` commands are not required to use prepared statements from within Python. You can append parameters to the `execute` call itself:

```py
con.execute('select 1 = ANY(?::int[])', ([1,2,3],)).df()
```

**Comment by TheRockStarDBA** [comment]
This will be very helpful and thanks to @Alex-Monahan for creating this based on our discussion at https://discord.com/channels/909674491309850675/921073327009853451/958490086348050462

**Comment by Alex-Monahan** [comment]
Awesome, I definitely prefer just using the Python execute method with parameters. Thanks!

**Comment by pdet** [comment]
I guess this should be closed @Mytherin ?
