### ISSUE TITLE
RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/5aebf7dac/osx_arm64/fts.duckdb_extension.gz

### ISSUE THREAD

**Issue by Raidus** [duckdb/duckdb#3326]
#### What happens?
Installation of extensions fails with duckdb python client.

#### Environment (please complete the following information):
 - OS: macOS Monterey (M1 MAX)
 - DuckDB Version: duckdb-0.3.3.dev1374
 - DuckDB Client: Python

#### To Reproduce
```python
import duckdb

q = duckdb.query("INSTALL 'fts'")
```

```python
RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/8264eea01/osx_arm64/fts.duckdb_extension.gz
```

Couldn't find a guide for using extension with the python client. I'll guess I have to manually install them?

Best
Wilhelm

**Comment by Mause** [comment]
Can you please test this with the latest release? Extensions aren't always going to be uploaded for dev builds in a timely manner
