### ISSUE TITLE
Node Library Error: Data type is not supported `TIME`

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#3344]
#### What happens?
When I attempt to select a `TIME`, duckdb throws the error:

```
Node Library Error: Data type is not supported TIME
```

Probably straightforward to add; just need to add a case statement for `duckdb:LogicalTypeId::TIME` to [this part of `statement.cpp`](https://github.com/duckdb/duckdb/blob/master/tools/nodejs/src/statement.cpp#L150-L208).

Any helpful hints on what the `TIME` value is under the hood would be much appreciated. I suspect its just microseconds. If so, I think it would probably make sense to just return an integer representing the microseconds since there isn't really anything comparable to `TIME` in ECMAscript.

#### To Reproduce

Grab the node library and write a query for `SELECT current_time;`  and you should receive an error:

```javascript
const duckdb = require('duckdb')
const db = new duckdb.Database(":memory:");
db.all('SELECT current_time', function(err, res) {
    if (err) {
      throw err;
    }
    console.log(res[0])
  });
```

#### Environment (please complete the following information):
 - OS: mac os 12.1 M1
 - DuckDB Version: 3.2 & 3.3-latest
 - DuckDB Client: Node.JS

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
Indeed we should probably get all the types supported for node. What would you like to get on the node side for a `TIME` type? A string?

**Comment by hamilton** [comment]
Good question. I think there are probably three options:
- **microseconds (number)** – provide microseconds to the user and have them handle it. In terms of ergonomics, this will be foreign to most JS developers since they almost always are dealing with ms, but in practice shouldn't be a problem. For the vast majority of times, it's likely to be well within [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), and if not could always be switched to a [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).
- **time string as "HH:MM:SS.dddddd"** – let the user parse / handle this string. The user handles the timestring.
- **object with { hours, minutes, seconds, fractional }** – this is the approach taken by the [BigQuery node API](https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html#.time). This saves the user from having to inevitably perform the next step of parsing a string or converting microseconds.

I went ahead and asked in a [Twitter poll](https://twitter.com/hamiltonulmer/status/1509887714585239558?s=20&t=YVDN4VYobz-5Z6aD1mCCQA) to get a sense of what the node.js / data tools community might expect.

I have no preference between these three choices. I already submitted a PR a few months ago to [convert `INTERVAL` to an object](https://github.com/duckdb/duckdb/pull/2819) so there's some precedence for duckdb to return objects.
