### ISSUE TITLE
Reading from Parquet file fails with error "java.sql.SQLException: IO Error: Unsupported converted type"

### ISSUE THREAD

**Issue by mansu** [duckdb/duckdb#3348]
#### What happens?
I created a parquet file using protobuf parquet library.

It seems it is related to #1200

#### To Reproduce
`SELECT * from read_parquet('" + tempLogFilePath.getLogFilePath() + "')` fails on the parquet file when queried by the JDBC api.

Stack trace is below:
```
java.sql.SQLException: IO Error: Unsupported converted type

	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:73)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:127)
	at com.slack.kaldb.logstore.columnar.io.impl.ProtobufParquetTest.readDuckDb(ProtobufParquetTest.java:153)
	at com.slack.kaldb.logstore.columnar.io.impl.ProtobufParquetTest.testSecorWriterDuckdbReader(ProtobufParquetTest.java:132)
```

Link to [unit test code](https://github.com/slackhq/kaldb/blob/playground_columnar/kaldb/src/test/java/com/slack/kaldb/logstore/columnar/io/impl/ProtobufParquetTest.java#L98)  and [probuf schema](https://github.com/slackhq/kaldb/blob/playground_columnar/kaldb/src/main/proto/trace.proto#L38). 

The parquet file is valid since I can read it via the secor reader and `parquet-tools`. 

I am not sure what causes this exception. I tried replacing bytes type as string and I still the same exception.

#### Environment (please complete the following information):
 - OS: macos
 - DuckDB Version: 0.3.2
 - DuckDB Client: Java 

#### Before Submitting

- [*] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ *] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by mansu** [comment]
Generated parquet file is also attached.
[0_1_00000000000000023232.log](https://github.com/duckdb/duckdb/files/8401790/0_1_00000000000000023232.log)

**Comment by hannes** [comment]
It looks like this is due to `ConvertedType::ENUM` being used in the file, learned something today.

**Comment by mansu** [comment]
Thanks for a quick response. 

In this proto file, the [tags](https://github.com/slackhq/kaldb/blob/master/kaldb/src/main/proto/trace.proto#L68) field is a mechanism to add arbitrary number of typed fields to the Span. Do you have any recommendations on an alternative way to achieve the same goal in DuckDB?

**Comment by Mytherin** [comment]
You could use a `MAP` type to store key-value pairs, e.g.:

```sql
D create table keyvalue(kv map(varchar, varchar));
D insert into keyvalue values (map(['key1', 'key2'], ['val1', 'val2']));
D select * from keyvalue;
┌────────────────────────┐
│           kv           │
├────────────────────────┤
│ {key1=val1, key2=val2} │
└────────────────────────┘
D 

```

**Comment by mansu** [comment]
Agree we can use the map type, but we didn't take that route since we would lose the benefits of columnar compression like dictionary encoding etc.. Further, joins would be very slow when joining across the MAP keys.

**Comment by hannes** [comment]
I think we can just decode that type as a string, cause its what the spec says it is.

**Comment by heuermh** [comment]
@Mytherin was this issue intended to be fixed/closed by your commit 4532ea3?  If so, what is the target release version for that fix (0.3.5?).  Thanks!

**Comment by Mytherin** [comment]
This should work in 0.3.4 now I believe

**Comment by heuermh** [comment]
> This should work in 0.3.4 now I believe

As mentioned elsewhere (#3683), 0.3.4 is not available on Maven Central
https://search.maven.org/artifact/org.duckdb/duckdb_jdbc

I tried building from git `master` and installed a snapshot version to my local repository using `mvn install:install-file` but that didn't get the shared library right (M1 mac)
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/15/qrc0v_5d3v90r31w29kb3q
_h0000gn/T/libduckdb_java1236567204398931775.so: dlopen(/private/var/folders/15/qrc0v_5d3v90r
31w29kb3q_h0000gn/T/libduckdb_java1236567204398931775.so, 0x0001): tried: '/private/var/folders
/15/qrc0v_5d3v90r31w29kb3q_h0000gn/T/libduckdb_java1236567204398931775.so' (mach-o file,
but is an incompatible architecture (have 'arm64', need 'x86_64'))
```
Will keep working on that

**Comment by heuermh** [comment]
Yes, that is correct, Parquet schema with enum fields fail with this exception under duckdb-jdbc version 0.3.3.
