### ISSUE TITLE
JoinOrderOptimizer Bug

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#339]
There is a problem in the JoinOrderOptimizer; however, the current test set does not trigger this. The problem can be found in the SQLite tests (select4.test, join255, line 38806) but is currently only triggered when the cardinality of all tables is 0 - in this case an incorrect plan is created that leads to the wrong result.

**Comment by Mytherin** [comment]
We may want to create some verification layer for the join order optimizer where we insert bogus cardinalities everywhere and verify that everything still runs as expected.

**Comment by Tmonster** [comment]
Currently in Switzerland right now, but will take a look once I'm back on wednesday

**Comment by Mytherin** [comment]
Absolutely no rush, enjoy your holiday :)
