### ISSUE TITLE
Query on parquet array column turns the column into a string

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#3393]
#### What happens?
I have a parquet file with one column that is an array of ints. When I read the parquet file, the column has np.ndarray values in it.
When I run a query to restrict the rows based on length of array, all the results for the column are now strings of the pretty-printed list values.

#### To Reproduce
```
$ python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import numpy as np
>>> import duckdb
>>> conn = duckdb.connect(database=':memory:', read_only=False)
>>> df = pd.DataFrame([{'w': 'two', 'a': np.array([1,2,3])}, {'w': 'four', 'a': np.array([4,5,6])}])
>>> df
      w          a
0   two  [1, 2, 3]
1  four  [4, 5, 6]
>>> df.iloc[0]['a']
array([1, 2, 3])
>>> conn.register('d', df)
>>> conn.execute("select * from d where len(a)>0")
>>> x = conn.fetchdf()
>>> x
      w        a
0   two  [1 2 3]
1  four  [4 5 6]
>>> x.iloc[0]['a']
'[1 2 3]'
```
#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.3.dev585
 - DuckDB Client: python

#### Before Submitting

- Have you tried this on the latest `master` branch? Yes. `pip install duckdb --upgrade --pre` said I'm on the latest version.
- Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there? Yes. yes. yes.

**Comment by Mytherin** [comment]
This seems related to #2450. It is related to the Pandas scan, not to the Parquet file.
