### ISSUE TITLE
[JDBC] "TransactionContext Error: cannot commit - no transaction is active" in Connection.commit()

### ISSUE THREAD

**Issue by jubax** [duckdb/duckdb#3395]
#### What happens?
In a simple startup scenario DuckDB throws an unexpected SQLException "TransactionContext Error: cannot commit - no transaction is active"

#### To Reproduce
The following code (unit test) triggers the exception:

```
	@Test
	public void testDuckDbCommit() throws Exception {
		try (Connection c1 = DriverManager.getConnection("jdbc:duckdb:")) {
			try (PreparedStatement statement = c1.prepareStatement("SELECT 1")) {
				statement.execute();
			}
			c1.setTransactionIsolation(Connection.TRANSACTION_REPEATABLE_READ);
			c1.setAutoCommit(false);
			c1.commit(); // Here the exception is thrown
		}
	}
```
Note that the same code works fine with SQLite and MS SQL Server.

#### Environment (please complete the following information):
 - OS: macOS Monterney (12.1)
 - DuckDB Version: JDBC driver 0.3.2 (as suggested on https://duckdb.org/docs/installation/?environment=java)
 - DuckDB Client: Java/JDBC

**Comment by Jens-H** [comment]
As there is no active transaction, the exception is correct. You can see the same behavior without JDBC on the CLI:

```
v0.3.3-dev1522 5079e8e7f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D commit;
Error: TransactionContext Error: cannot commit - no transaction is active
```

**Comment by jubax** [comment]
> As there is no active transaction, the exception is correct. You can see the same behavior without JDBC on the CLI:
> 
> ```
> v0.3.3-dev1522 5079e8e7f
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D commit;
> Error: TransactionContext Error: cannot commit - no transaction is active
> ```

This behavior is not correct according to the JDBC specification. JDBC does not have a `Connection.transactionBegin()` method. Executing a SQL statement (query or DDL) must start a transaction implicitly.

If autocommit=true then the JDBC driver must execute a commit after each SQL statement. After setting autocommit=false (like in the code above) an implicit commit must also be executed.

After we turned off autocommit the execution of a SQL statement must initiate a "transaction begin". The transaction remains open until the user executes `Connection.commit()`.

Note that DuckDB also fails with the same exception when changing the code to
```
@Test
public void testDuckDbCommit() throws Exception {
    try (Connection c1 = DriverManager.getConnection("jdbc:duckdb:")) {
        // The following code implicitly starts a transaction
        try (PreparedStatement statement = c1.prepareStatement("SELECT 1")) {
            statement.execute();
        }
        c1.setTransactionIsolation(Connection.TRANSACTION_REPEATABLE_READ);

        // We now set the autocommit to "false". This means any SQL statements
        // will implicitly start a new transaction.
        c1.setAutoCommit(false);
        // Now an implicit commit is executed

        // The following statement must start a transaction
        try (PreparedStatement statement = c1.prepareStatement("SELECT 1")) {
            statement.execute();
        }
        // We are still in the transaction and the next line should commit it.
        c1.commit();
    }
}
```

So maybe `Connection.setAutoCommit(false)` does not work or is not implemented yet?

**Comment by Jens-H** [comment]
I can see two separate issues here:
1. The error after a commit
2. The behavior of setAutoCommit

No. 1 is what I wrote above: DuckDB decided to throw an exception if you call commit without a running transaction. From my point of view this would be in line with the spec/Javadoc, though other DBs decided to have a different behavior.

The actual behavior of setAutoCommit is different to what is described in the spec. #2824 reported this already. The auto-commit flag is reset to true after every transaction. This makes it basically unusable.

JDBC expects the flag to stay unchanged for a Connection object and this is clearly violated.

However, the issues are not completely independent. If you never get to the auto-commit off mode, the commit has to throw an Exception anyway.

**Comment by jubax** [comment]
FYI: The test shown in the description works at least since DuckDB version 0.6.1 => The bug has been fixed. Thanks 👍
