### ISSUE TITLE
Unnest() doesn't seem to work on column with np.ndarray and null values

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#3396]
#### What happens?
I'm trying to use unnest() on an array column, but I get the exception "duckdb RuntimeError: Binder Error: Unnest() can only be applied to lists and NULL". The column only contains np.ndarray values and null. The df was read in from a parquet file. This seems like a bug, but maybe I'm missing something. If I am, please tell me how to get around the exception.

Here's the value types for the column:
```
(Pdb) df['ids'].apply(lambda y: type(y)).value_counts()
<class 'numpy.ndarray'>    12996752
<class 'NoneType'>           349286
Name: resultAccountIds, dtype: int64
```
#### To Reproduce
I'll see if I can reproduce on a small df.

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.3.dev585
 - DuckDB Client: python

#### Before Submitting
* Have you tried this on the latest master branch? Yes. pip install duckdb --upgrade --pre said I'm on the latest version.
* Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there? Yes. yes. yes.

**Comment by scottee** [comment]
Here's a simple case illustrating the bug. It also shows that if a column is a list, versus np.ndarray, the exception stilll happens.
```
$ python
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 20:58:55)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import numpy as np
>>> import duckdb
>>> conn = duckdb.connect(database=':memory:', read_only=False)
>>> df = pd.DataFrame([{'w': 'two', 'a': np.array([1,2,3])}, {'w': 'four', 'a': np.array([4,5,6])}])
>>> conn.register('d', df)
<duckdb.DuckDBPyConnection object at 0x7fe85001a670>
>>> conn.execute("select w, unnest(a) as a from d")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Binder Error: Unnest() can only be applied to lists
LINE 1: select w, unnest(a) as a from d
                  ^
>>> df2 = pd.DataFrame([{'w': 'two', 'a': [1,2,3]}, {'w': 'four', 'a': [4,5,6]}])
>>> conn.register('d2', df2)
>>> conn.execute("select w, unnest(a) as a from d2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Binder Error: Unnest() can only be applied to lists
LINE 1: select w, unnest(a) as a from d2
                  ^
```

**Comment by Mytherin** [comment]
Is this not the same issue that you have reported in #3393? It seems to me that the column is converted to a string, so `UNNEST` would not work.

**Comment by scottee** [comment]
In #3393 I was guessing it was the where-clause check that caused the conversion to string. If arrays are always converted to string, then maybe it is.

**Comment by Mytherin** [comment]
Closing as duplicate
