### ISSUE TITLE
INTERNAL Error: A CTE needs a SELECT

### ISSUE THREAD

**Issue by mharmer** [duckdb/duckdb#3417]
#### What happens?
I'm attempting to perform an INSERT within a CTE and receive "INTERNAL Error: A CTE needs a SELECT".

In Postgres it appears that this works:
```
CREATE TABLE table1 (id INTEGER, a INTEGER);
CREATE TABLE table2 (table1_id INTEGER);

WITH cte AS (
    INSERT INTO table1
    SELECT 1, 2
    RETURNING id
)
INSERT INTO table2
SELECT
  id
FROM cte
;
```

#### To Reproduce
Note: The syntax for the `INSERT INTO` below had to be moved below the `WITH` (which I found from the syntax described here: https://github.com/duckdb/duckdb/issues/160#issuecomment-1030698425), otherwise DuckDB complains of a missing table (this may be a separate issue, I'm not a SQL expert)

When running the following in duckdb I receive the reported error:
```
CREATE TABLE table1 (id INTEGER, a INTEGER);
CREATE TABLE table2 (table1_id INTEGER);

INSERT INTO table2
WITH cte AS (
    INSERT INTO table1
    SELECT 1, 2
    RETURNING id
)
SELECT
  id
FROM cte
;
```

I don't believe this is a regression, but I was testing it since the RETURNING support had been recently added.

#### Environment (please complete the following information):
 - OS: Ubuntu 21.10
 - DuckDB Version: 0.3.3
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by PedroTadim** [comment]
This won't be supported for a while, the issue can be closed.
