### ISSUE TITLE
strptime function: lpad format can't parse

### ISSUE THREAD

**Issue by zhanglong2005** [duckdb/duckdb#3418]
#### What happens?
bcp from sybase or sql server datetime can't parse by strptime

#### To Reproduce
#--one blank between 2003 and 12
SELECT strptime('Jun 30 2003 12:03:10AM', '%b %d %Y %I:%M:%S%p');

#change 12 with 02,or just 2,it's ok
SELECT strptime('Jun 30 2003 02:03:10AM', '%b %d %Y %I:%M:%S%p');

#change 12 with " 2",blank+2
D SELECT strptime('Jun 30 2003  2:03:10AM', '%b %d %Y %-I:%M:%S%p');
Error: Invalid Input Error: Could not parse string "Jun 30 2003  2:03:10AM" according to format specifier "%b %d %Y %-I:%M:%S%p"
Jun 30 2003  2:03:10AM
            ^
Error: Expected a number

bcp leftpad with blank and not zero. current can't parse this part

bcp  sample like this: 
"Jun 30 2003 02:03:10AM"
"Jun   3 2003   3:03:10AM"
"Jun 30 2003 12:03:10AM"

#### Environment (please complete the following information):
 - OS: [liunix]
 - DuckDB Version: [0.33-dev]
 - DuckDB Client: [shell]

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
Hmm, I just tried this on the current master and it works?

```sql
#--one blank between 2003 and 12
query I
SELECT strptime('Jun 30 2003 12:03:10AM', '%b %d %Y %I:%M:%S%p');
----
2003-06-30 00:03:10

#change 12 with 02,or just 2,it's ok
query I
SELECT strptime('Jun 30 2003 02:03:10AM', '%b %d %Y %I:%M:%S%p');
----
2003-06-30 02:03:10

#change 12 with " 2",blank+2
query I
SELECT strptime('Jun 30 2003 2:03:10AM', '%b %d %Y %-I:%M:%S%p');
----
2003-06-30 02:03:10
```

I believe I copied your repro from the report, but can you please check the space counts?

**Comment by Mytherin** [comment]
The problem here is the extra spaces, I suppose?

We might want to allow extra spaces similar to Python:

```py
>>> import datetime
>>> datetime.datetime.strptime('Jun   30    2003      2:03:10AM', '%b %d %Y %I:%M:%S%p')
datetime.datetime(2003, 6, 30, 2, 3, 10)
```

Python seems to have a special rule where it treats any whitespace in the format string as "as much whitespace as you want".

**Comment by madewoshizhu** [comment]
yes,the problem is the extra spaces.  
```
SELECT strptime('Jun 30 2003 2:03:10AM', '%b %d %Y %-I:%M:%S%p');
SELECT strptime('Jun 30 2003  2:03:10AM', '%b %d %Y %-I:%M:%S%p');
```
