### ISSUE TITLE
Unable to update to 0.3.3 python

### ISSUE THREAD

**Issue by darthf1** [duckdb/duckdb#3425]
Hi!

Im trying to update from `0.3.2` to `0.3.3` in python (`Python 3.9.2`) but installation fails with a lengthy error. I guess the most important message is:

```
ModuleNotFoundError: No module named 'numpy'
```

I tried an explicit install of `numpy`, as i did not require it before, but it doesnt help unfortunately.

Full log can be found: https://controlc.com/38a2940c

**Comment by samansmink** [comment]
hi @darthf1 thanks for reporting this issue. The error you are seeing seems to indicate some issue when building the python module from source. We've had some issues with the 0.3.3 release where not all binaries were uploaded to PyPi. As soon as we fix that, the python update should work!

**Comment by darthf1** [comment]
Ok thanks! I'll wait until then :)

**Comment by samansmink** [comment]
@darthf1 the wheel have now been uploaded for the 0.3.4 release! So you now should be able to upgrade to 0.3.4 without issues. I'lll leave this issue open for now while I check out why the source install failed as that should also just work

**Comment by darthf1** [comment]
Works like a charm, thanks!
