### ISSUE TITLE
install httpfs > RuntimeError: IO Error: Failed to download extension

### ISSUE THREAD

**Issue by EralpB** [duckdb/duckdb#3431]
#### What happens?
con = duckdb.connect()
con.execute("install httpfs")
gives a runtime error. I've experienced this with a couple of latest releases.

#### To Reproduce
python3
> import duckdb
> con = duckdb.connect()
> con.execute("install httpfs")

#### Environment (please complete the following information):
 - OS: ubuntu as well as macosx
 - DuckDB Version: latest dev (yeah I did --upgrade --pre) as well as 0.3.3
 - DuckDB Client: python

**Comment by EralpB** [comment]
I'm having the same error with duckdb==0.3.4.dev62 on macosx as well as linux, can I somehow pre-package this extension?

installing is also problematic time to time.

**Comment by Mytherin** [comment]
I can't reproduce this on neither macos nor linux, what is the exact error that is being thrown, and what is your exact OS version?

You can modify the `setup.py` script to include additional packages by default.

**Comment by EralpB** [comment]
thank you. good to know it's not reproducable, so it's probably not a fault with the library itself.

```python3 ./main.py 
3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
0.3.4-dev62
Traceback (most recent call last):
  File "/Users/eralpb/./main.py", line 6, in <module>
    con.execute("install httpfs")
RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/8d7ee4a1b/osx_amd64/httpfs.duckdb_extension.gz```

my main.py

```
import sys
import duckdb
print(sys.version)
print(duckdb.__version__)
con = duckdb.connect()
con.execute("install httpfs")
```

```
curl http://extensions.duckdb.org/8d7ee4a1b/osx_amd64/httpfs.duckdb_extension.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>DD0GAG3JB5S99DWX</RequestId><HostId>124Q7Q7B3eQhHEIUnkAKZL2y7IZY+2OwRx3n+tK8YDALsrTFrn4Pc3AMizI/RoapNFgfsSi/Bw8=</HostId></Error>%     
```

can it be that I'm IP-blocked? is this URL correct? I'm connecting from a german IP. but same issue happens with our build servers which are on gcp.

**Comment by Mytherin** [comment]
Remote extension installation is not (always) supported on dev builds because certain extensions might not get uploaded or might delay to get uploaded. Does it not work on the actual release for you (commit hash `fe9ba80039e4a0f20eb8d7fb7d6d9a4984156cbd`)?

**Comment by EralpB** [comment]
thank you again, yes
```
[Clang 10.0.0 ]
0.3.3
```
worked!

I switched to master builds because "load httpfs" was failing previously, but I can't reproduce it anymore. currently 0.3.3 seems okay :)
