### ISSUE TITLE
ODBC on Windows don't show column headers 

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#3439]
I manage to use DuckDB with PowerBI leveraging the ODBC driver, it works very well, but I have an issue it does not return the column headers ?
![image](https://user-images.githubusercontent.com/12554469/163713670-712cebc4-0293-4d1e-8459-2443b72c56d5.png)

and here is the results
![image](https://user-images.githubusercontent.com/12554469/163713691-1c8c89a8-5c8b-4f33-8795-f9eb383edbd1.png)

**Comment by tiagokepe** [comment]
The issue was related to the filling of the IRD descriptor.
PR #3467 fixes that as can be seen below:

![image](https://user-images.githubusercontent.com/403295/164300475-525278a8-1fbc-4ae0-8cb2-08ab81987c4a.png)

**Comment by djouallah** [comment]
thank you very much, do you how I can download the updated ODBC driver ?

**Comment by tiagokepe** [comment]
> thank you very much, do you how I can download the updated ODBC driver ?

You can grab the updated ODBC driver from the [Windows artifacts](https://github.com/duckdb/duckdb/actions/runs/2202313065) generated in the action runs of the PR #3467.
Link for [duckdb-binaries-windows](https://github.com/duckdb/duckdb/suites/6206829364/artifacts/219166193).

**Comment by djouallah** [comment]
hahaha, you are a star it works now, thank you very much
