### ISSUE TITLE
Segmentation fault on linux/arm64 architecture in combination with `google.cloud.storage`

### ISSUE THREAD

**Issue by JakobGM** [duckdb/duckdb#3443]
I'm getting segmentation faults after upgrading to DuckDB version 0.3.3. After a lot of debugging I have managed to create a minimal reproducible script which triggers the segmentation fault:

```py
# Run "pip install duckdb=0.3.3 google-cloud-storage" and run this script
import duckdb
from google.cloud import storage
```

If I remove any one of these lines, the segmentation fault disappears. If I _reorder_ the lines, the segmentation fault disappears. The problem only occurs within my linux/arm64 docker container, not outside in the MacOS ARM M1 host environment. I have tested it on a minimal docker image:

```sh
docker run -it python:3.9 bash
pip install duckdb==0.3.3 google-cloud-storage
echo "import duckdb" > test.py
echo "from google.cloud import storage" >> test.py
python test.py
# Segmentation fault
```

If I run python -v test.py I can get a detailed log trace up until the segmentation fault, it can be found in a gist [here](https://gist.github.com/JakobGM/830d838d97c0cb4acb12171f12cb773a).  I also tried to get some more detailed stack traces for the segmentation fault by running the following script:

```py
import faulthandler
faulthandler.enable()
import duckdb
from google.cloud import storage
```

The output can be found [here](https://gist.github.com/JakobGM/43fc10c43f75092975d24e7fca66f82b). Any ideas what is at fault here?

**Comment by Mytherin** [comment]
Thanks for the report! I suspect this might be related to the inlining of protobuf into the Python extension, together with the recent changes we made to `RTLD_GLOBAL`. Unfortunately I cannot seem to reproduce this myself.

Could you perhaps try compiling [my branch here](https://github.com/Mytherin/duckdb/tree/dontinlinesubstrait) from source (by running `cd tools/pythonpkg; python setup.py install`) and checking if that fixes the problem?

**Comment by JakobGM** [comment]
Thanks for taking a look, @Mytherin!

I created the following `Dockerfile`:

```Dockerfile
FROM python:3.9
RUN mkdir /duckdb
COPY . /duckdb
WORKDIR /duckdb/tools/pythonpkg
RUN python -m pip install numpy
RUN python setup.py install
RUN python -m pip install google-cloud-storage
```

And then executed:

```py
import duckdb
from google.cloud import storage
```

On `duckdb/duckdb`'s main branch it caused a Segmentation Fault, while on your branch it did not. So it seems that you have managed to fix it 🎉 I should mention that I got the following warning, though, when importing `google.cloud.storage`:

```
/usr/local/lib/python3.9/site-packages/google/rpc/__init__.py:18: UserWarning: Module _duckdb_extension was already imported from /usr/local/lib/python3.9/site-packages/duckdb-0.3.6.dev48+g31dad368d-py3.9-linux-aarch64.egg/_duckdb_extension.cpython-39-aarch64-linux-gnu.so, but /duckdb/tools/pythonpkg is being added to sys.path
  import pkg_resources
```

Thanks a lot!

**Comment by hannes** [comment]
Should be fixed by not shipping substrait by default
