### ISSUE TITLE
Docs and examples still specify 0-based indexing

### ISSUE THREAD

**Issue by orlp** [duckdb/duckdb#3447]
Recently duckdb adopted 1-based indexing for compatibility with the SQL standard: https://github.com/duckdb/duckdb/issues/2575

Unfortunately the docs and examples still specify and show 1-based indexing: https://duckdb.org/docs/archive/0.3.3/sql/functions/char

**Comment by Mytherin** [comment]
Thanks for the report! Should be resolved by duckdb/duckdb-web#202. In the future please post issues relating to the website on the [website repository](https://github.com/duckdb/duckdb-web/issues).
