### ISSUE TITLE
list_contains doesn't handle prior selections correctly

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#3450]
#### What happens?
When `list_contains` is not the first predicate, it doesn't handle the previous selection correctly.

#### To Reproduce
```sql
SELECT function_name, return_type, parameter_types
FROM duckdb_functions()
WHERE function_type = 'scalar' AND list_has(parameter_types, 'TIMESTAMP')
```

#### Environment (please complete the following information):
 - OS: OSX
 - DuckDB Version: 0.3.3.-dev
 - DuckDB Client: Shell

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by taniabogatsch** [comment]
Ah yes, I believe this happens because elements are accessed using a (incremented) index added to the source index of the list (first element). Instead, each child should be accessed through the selection vector.
