### ISSUE TITLE
Duckdb Python Client seems inconsistent with non-pandas types

### ISSUE THREAD

**Issue by TNonet** [duckdb/duckdb#3459]
#### What happens?

Inconsistent behavior happens when moving decimal data out of a duckdb view/table.

#### To Reproduce

Create a decimal and float dataframe and register it with duckdb.
```python
import decimal
import pandas
import duckdb

con = duckdb.connect(database=":memory:", read_only=False)
df = pandas.DataFrame({"col1": [decimal.Decimal("0.1"), decimal.Decimal("0.2")],
                       "col2": [0.1, 0.2]})
pandas.concat([df.dtypes,
               df.iloc[0].apply(lambda x: type(x)),
               df.iloc[0].apply(lambda x: repr(x))], axis=1)
con.register('df', df)
```
We see DuckDB took the decimal (object) column to a sting. 
```python
df2 = con.execute("SELECT * FROM df").fetch_df()
pandas.concat([df2.dtypes,
               df2.iloc[0].apply(lambda x: type(x)),
               df2.iloc[0].apply(lambda x: repr(x))], axis=1)

```
Create a duckdb table and cast `col1` back to a decimal. Duckdb decides to convert the decimal to a float when returned as a df!
```python
con.execute('CREATE TABLE table1 AS SELECT col1::decimal as col1, col2 from df')
df3 = con.execute('SELECT * FROM table1').fetch_df()
pandas.concat([df3.dtypes,
               df3.iloc[0].apply(lambda x: type(x)),
               df3.iloc[0].apply(lambda x: repr(x))], axis=1)
```

However, when returned as individual python objects Duckdb returns items as decimals
```python
list1 = con.execute('SELECT * FROM table1').fetchall()
print(list1)
```

Is this intended behavior? Lossy casting from decimal to float is always tricky. Could a flag/parameter be available to specify this behavior or could a pandas columns of objects (strings or decimals) be returned?

#### Environment (please complete the following information):
 - OS: Linux-5.4.181-99.354.amzn2.x86_64-x86_64-with-glibc2.28 
 - DuckDB Version: 0.3.1
 - DuckDB Client: Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
This seems related to #2450, the general problem is that Pandas does not handle anything that is not an integer or a float well. We could cast decimals to an object column of decimals, but that will come at a large performance penalty.
