### ISSUE TITLE
PyPI wheels for 0.3.3 (missing MacOS and python versions)

### ISSUE THREAD

**Issue by luke321321** [duckdb/duckdb#3462]
For [0.3.3](https://pypi.org/project/duckdb/0.3.3/#files) there aren't many wheels built. In particular there are only wheels for python 3.7 & 3.10 and for windows and linux.  There aren't any wheels built for Mac `macosx` or for python versions 3.8 or 3.9.  This makes installation harder as user's machines will have to build from source themselves

Comparison:
[0.3.3](https://pypi.org/project/duckdb/0.3.3/#files)
[0.3.2](https://pypi.org/project/duckdb/0.3.2/#files)

**Comment by Mytherin** [comment]
Thanks for the report, this is a known issue. See #3425

**Comment by samansmink** [comment]
@luke321321 the new 0.3.4 release includes all wheels again! I'll close this issue.
