### ISSUE TITLE
DPhyp will enumerate some CSG many times

### ISSUE THREAD

**Issue by LYKZZzz** [duckdb/duckdb#3475]
In the current implementation of DPhyp, there are some points that cause redundant 
Csg&Cmp enumeration:

  1. GetNeighbors(S1, X) function might return some vertex that belongs to S1.

  2. exclusion_set only union current neighbor in EnumCsg(Cmp)Rec, for
     example: the neighbors of V1 is V2 and V4, when we try to call
     EnumCsgRec({V1, V2}, {V2}),  we will enum {V1, V2, V4}, but then
     when we call EnumCsgRec({v1, v4}, {v4}), we will enum {V1, V2, V4}
     again.
 
 3. if S1.count == relations.size(), EmitCsg can return immediately
     because there isn't any available Cmp to connect.

I code a [draft](https://github.com/LYKZZzz/duckdb/commit/9deacc1d9312980774a8dcf6020179647d05f340) to explain the optimization of the current implementation. For a 4-table cycle join test case, these optimizations reduce the number of EmitCSG calls from 43 to 14.

**Comment by hannes** [comment]
Are you sure this is in the right repo?

**Comment by LYKZZzz** [comment]
> Are you sure this is in the right repo?

I mean that the DPhyp implementation of DuckDB(join_order_optimizer.cpp) has some opportunities to optimize.

**Comment by Mytherin** [comment]
Thanks for the comments, those improvements make sense. Could you perhaps turn this into a PR?

**Comment by LYKZZzz** [comment]
> Thanks for the comments, those improvements make sense. Could you perhaps turn this into a PR?

I will create a PR after adding some unit tests.

**Comment by Mytherin** [comment]
Should be fixed now
