### ISSUE TITLE
Possibility of disabling coercion of unknown values to NULL in enum inserts

### ISSUE THREAD

**Issue by frankier** [duckdb/duckdb#3479]
I think it might be nice to have a strict mode for ENUM inserts which raises an exception when unknown values are inserted rather than coercing them to NULL. I suppose in many cases, having NOT NULL will suffice, but there could be cases when None === NaN === NULL is wanted, but dropping of values is not:

To be clear, the suggestion is to have e.g. a pragma that enables as mode where an exception is thrown in the following code:

```
import os
import duckdb
import pandas

try:
    os.remove("db.duckdb")
except OSError:
    pass

conn = duckdb.connect("db.duckdb")

conn.execute(
"""
create type cat as enum ('marie', 'duchess', 'toulouse');
create table tab (
    cat cat,
    amt int
);
"""
)

print("Case: Should be able to avoid data loss here")
df = pandas.DataFrame({"cat": pandas.Series(['duchess', 'toulouse', 'marie', None, "berlioz", "o_malley"], dtype="category"), "amt": [1, 2, 3, 4, 5, 6]})
print("Before")
print(df)
conn.register('df', df)
conn.execute(f"INSERT INTO tab SELECT * FROM df;")
conn.unregister('df')

df = conn.query(f"SELECT * FROM tab;").to_df()
print("After")
print(df)
```

**Comment by hannes** [comment]
@pdet any opinions?

**Comment by frankier** [comment]
Thinking about it again, I'm not really sure if a pragma is best, or would it be better to have strict specifiers on columns or enums or perhaps some other way (strict by default?) so I have changed the title to reflect that.

**Comment by pdet** [comment]
I think this should always throw an error. Since that's the std in our SQL API and in Postgres.
