### ISSUE TITLE
feature request: parquet modular encryption

### ISSUE THREAD

**Issue by vlushn** [duckdb/duckdb#3484]
The parquet format supports encrypting specific sensitive columns (with differing keys if so desired): https://github.com/apache/parquet-format/blob/master/Encryption.md . Data analytics tools such as Spark also support querying this data by specifying encryption keys for each column (though this appears to be specific to spark distribution) e.g. https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=scripts-parquet-encryption 

It would be nice to extend `read_parquet()` with parameters for keys and be able to read those. The underlying C++ library (https://github.com/apache/parquet-cpp) hasn't implemented support yet though it seems..

**Comment by hannes** [comment]
Which underlying C++ library?

**Comment by vlushn** [comment]
> Which underlying C++ library?

When I had a look at parquet-cpp they seemed to have encryption code in there, but I've had another look and it's not linked with anything (updated description). Oops. Which would make this enhancement a much bigger task.

**Comment by hannes** [comment]
You could try to use the Arrow parquet reader that supports this and pass the reader over to DuckDB. It's unlikely we will add this in the short term.

**Comment by tmct** [comment]
Was added in #34616 byt @tolleybot
