### ISSUE TITLE
Testing IS NULL on join key runs exceptionally long

### ISSUE THREAD

**Issue by zachary62** [duckdb/duckdb#3487]
#### What happens?
When the where clause has "IS NULL" for the join key, the query takes exceptionally long.

#### To Reproduce

import pandas as pd
import duckdb
R = pd.DataFrame()
S = pd.DataFrame()

R["A"] = range(100000)
R["B"] = range(100000)
S["B"] = range(100000)
S["C"] = range(100000)

# this takes 10 ms
print(duckdb.query("SELECT COUNT(*) FROM R,S WHERE R.B = S.B;"))

# this takes 4 ms
print(duckdb.query("SELECT COUNT(*) FROM R,S WHERE R.B IS NULL;"))

# this takes half a minute!!
print(duckdb.query("SELECT COUNT(*) FROM R,S WHERE R.B = S.B OR R.B IS NULL;"))

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.3
 - DuckDB Client: python

**Comment by Mytherin** [comment]
Thanks for the report!

The OR clause forces a nested loop join to be used, which is very slow when run on two large tables.

Is this join actually what you want to execute? The current join condition will duplicate the entirety of S for every row that is NULL in R.

Are you perhaps looking to join on R.B IS NOT DISTINCT FROM S.B?

**Comment by zachary62** [comment]
Hi Mark, I want to join also on "NULL" and R.B IS NOT DISTINCT FROM S.B works well! Thank you!

As a side note, is the OR clause you plan to optimize? I run the same query on other databases, and they seem to optimize it well.

**Comment by Mytherin** [comment]
We can probably do some more optimizations here indeed. Also happy to review a PR :)

**Comment by Mytherin** [comment]
Closing this and replacing with a more descriptive issue
