### ISSUE TITLE
arrow for java

### ISSUE THREAD

**Issue by laopeng2021** [duckdb/duckdb#3489]
https://duckdb.org/2021/12/03/duck-arrow.html

This blog only talks about Python and R to interoperate with arrow.

Do these APIs also support Java?

Can the arrow table be registered in duckdb in Java?

thank you.

thank you.

**Comment by pdet** [comment]
Hey @laopeng2021, there is currently no DuckDB-Arrow support for Java.
Only for Python/R and Cpp (If you link the libraries yourself).
