### ISSUE TITLE
java for BeginTransaction?

### ISSUE THREAD

**Issue by laopeng2021** [duckdb/duckdb#3494]
Mytherin gives an example of beginthransaction as follows:

conn.BeginTransaction();
  .....
  ::duckdb::Appender appender(conn, "tablename");
  for ( .....loop .... ) {
    appender.BeginRow();
    appender.Append<int64_t>(record->id());
    appender.Append<double>(record->price());
    appender.Append<int64_t>( GetHash( record->category() ));
    .... 
    appender.EndRow();
  }
  appender.Close();
  .....
  conn.Commit();

Begintransaction exists in C + + language, but there is no begintransaction in Java code.

Because the autocommit of the appender is 1024 lines by default. I want to change it to 1024*1000 lines for a transaction commit. This can significantly improve performance.

But there is no begintransaction in Java, so what should I do? Is it necessary to use C + +?

**Comment by Mytherin** [comment]
You can run “BEGIN TRANSACTION” as a SQL query

**Comment by laopeng2021** [comment]
> You can run “BEGIN TRANSACTION” as a SQL query

thanks ！
