### ISSUE TITLE
Casting to integer truncates instead of rounding

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#3497]
#### What happens?

Casting a float value to an integer truncates the value, whereas the same in Postgres rounds it.

#### To Reproduce

In DuckDB:
```
v0.3.3-dev1399 7c5ba6c0e
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select cast(0.55 as integer) as x;
┌───┐
│ x │
├───┤
│ 0 │
└───┘
```

In Postgres:
```console
psql (14.2 (Debian 14.2-1.pgdg110+1))
Type "help" for help.

ldbcsnb=# select cast(0.55 as integer) as x;
 x 
---
 1
(1 row)
```

#### Environment (please complete the following information):
 - OS: Fedora 35
 - DuckDB Version: 0.3.2, 7c5ba6c0e
 - DuckDB Client: CLI

**Comment by hawkfish** [comment]
This is PG behavior as well.

**Comment by hawkfish** [comment]
Moreover, PG uses statistical rounding for `FLOAT` => `INTEGER`, which we do not. But they don't seem to do this for `DECIMAL`.

**Comment by kimmolinna** [comment]
Is this a problem if you know the behaviour? Cast works like this and it's fast and if you want to use `round(
double/float,0)` if you want to round according to statistical rules.

**Comment by hawkfish** [comment]
Well we try to match the behaviour of PG. For integers (this issue), we just have to add half of a number we have already looked up. For statistical rounding, the plan is to use [nearbyint](https://www.cplusplus.com/reference/cmath/nearbyint/).

**Comment by kimmolinna** [comment]
That's true. I have used that logic quite much in DyalogAPL.

**Comment by Mytherin** [comment]
@hawkfish this should be fixed now, correct? Can this be closed?

**Comment by hawkfish** [comment]
> @hawkfish this should be fixed now, correct? Can this be closed?

I believe so. There is a related issue around floating point rounding, but that is still in process.
