### ISSUE TITLE
Failed to download extension http://extensions.duckdb.org/662041e2b/linux_amd64_gcc4/fts.duckdb_extension.gz

### ISSUE THREAD

**Issue by Raidus** [duckdb/duckdb#3501]
#### What happens?
Wanted to deploy on a remote server my application which is using DuckDB but installation of extensions fails with duckdb python client.

Had the same issue with my Mac M1 environment (https://github.com/duckdb/duckdb/issues/3326) which is already fixed.

#### Environment:
 - OS: Ubuntu 18.04.6 LTS (Bionic Beaver)
 - DuckDB Version: duckdb-0.3.4
 - DuckDB Client: Python (Python 3.9)

#### To Reproduce
```python
import duckdb

q = duckdb.query("INSTALL 'fts'")
```

```python
RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/662041e2b/linux_amd64_gcc4/fts.duckdb_extension.gz
```

Best
Wilhelm

**Comment by evgenygr** [comment]
I still see this kind of error while trying to install extensions (like fts or json) the way Radius outlined on the following env:
 - OS: Ubuntu 20.04.4 LTS (Focal Fossa) on amd64
 - DuckDB Version: 0.3.2, 0.3.4 and 0.3.5.dev617 (on this version - after running `pip install duckdb --upgrade --pre`)
 - DuckDB Client: Python
 
I am trying to load JSON extension, but it fails with `RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/662041e2b/linux_amd64_gcc4/JSON.duckdb_extension.gz`.
