### ISSUE TITLE
Segfault when creating table with foreign key constraint

### ISSUE THREAD

**Issue by six-transit** [duckdb/duckdb#3505]
#### What happens?

When creating a table with a `FOREIGN KEY` constraint, DuckDB segfaults ~~if the constraint references a nonexistent table.~~ see followup comment -- even in a minimal case where the referenced table exists I'm getting a segfault.

#### To Reproduce

given an `init.sql` file containing the following:

```sql
CREATE TABLE routes (
	route_id TEXT PRIMARY KEY,
	agency_id TEXT,
	FOREIGN KEY (agency_id) REFERENCES agency,
);
```

running

```sh
duckdb < init.sql
```

outputs

```
Segmentation fault (core dumped)
```

instead of a segfault, as a user I would expect an informative error message that would allow me to diagnose the issue.

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.4
 - DuckDB Client: CLI

#### Before Submitting

- **Have you tried this on the latest `master` branch?**

* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

  :warning: fyi, the link in the above "other platforms" point seems to just point to a four-year-old source tarball: https://github.com/duckdb/duckdb/releases/tag/master-builds

  the [link to download binaries built off master on the duckdb website](https://duckdb.org/docs/installation/) also fails with a 404 for me: https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_cli-linux-amd64.zip

  given these points, I don't know how to test against master, sorry. I'm not going to attempt to build it myself -- we're just evaluating whether DuckDB is in a usable state for our company (I would love for it to be but have to admit landing on this issue in the first few minutes and then hitting broken downloads on the website is not a promising start).

- **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by six-transit** [comment]
Uh... actually, this also causes a segfault:

```sql
CREATE TABLE agency (
	agency_id TEXT PRIMARY KEY,
	agency_name TEXT NOT NULL,
);

CREATE TABLE routes (
	route_id TEXT PRIMARY KEY,
	agency_id TEXT,
	FOREIGN KEY (agency_id) REFERENCES agency,
);
```

So clearly it's not about the constraint referencing a valid table. Maybe I'm missing something obvious here -- are foreign key constraints supported?

**Comment by Mytherin** [comment]
Thanks for the report! Foreign key support is very new so some rough edges are to be expected. This particular syntax was not considered, you need to explicitly specify the column names for now:

```sql
CREATE TABLE agency (
	agency_id TEXT PRIMARY KEY,
	agency_name TEXT NOT NULL
);

CREATE TABLE routes (
	route_id TEXT PRIMARY KEY,
	agency_id TEXT,
	FOREIGN KEY (agency_id) REFERENCES agency(agency_id)
);
```

**Comment by six-transit** [comment]
That works! Thank you for the quick response (and for the fix that's already in review!)
