### ISSUE TITLE
Add additional rewrite rules for OR clause

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#3509]
* Rewrite `a=b OR (a IS NULL AND b IS NULL)` to `a IS NOT DISTINCT FROM b`
* Prune `OR` in statistics propagation (`propagate_conjunction`)

See #3487

**Comment by PedroTadim** [comment]
As I have free time this week I can look at this. It's a great C++ exercise opportunity. I already added this rewrite for MonetDB, so I can make it for the Duck :)

**Comment by omo** [comment]
Looks like this is fixed? @Mytherin
