### ISSUE TITLE
Can't use duckdb con in different threads in Python

### ISSUE THREAD

**Issue by zachary62** [duckdb/duckdb#3517]
#### What happens?
In the documentation of dcukdb (https://duckdb.org/docs/api/python), it says: "If you want to create a second connection to an existing database, you can use the cursor() method. This might be useful for example to allow parallel threads running queries independently." However, it seems that each connection can be used in only one thread.

#### To Reproduce
```
import duckdb
import threading
con = duckdb.connect(database='myduckdb', read_only=True)

def f1():
    con.cursor().execute("""
    SELECT * FROM R;
    ;""")
    return 1

# creating thread
t1 = threading.Thread(target=f1, args=())
t2 = threading.Thread(target=f1, args=())

# starting thread 1
t1.start()
# starting thread 2
t2.start()

# wait until thread 1 is completely executed
t1.join()
# wait until thread 2 is completely executed
t2.join()

# both threads completely executed
print("Done!")
```

This will result in the following error:

```
RuntimeError: DuckDB objects created in a thread can only be used in that same thread. The object was created in thread id 6289745148710612373 and this is thread id 248149677167971290
RuntimeError: DuckDB objects created in a thread can only be used in that same thread. The object was created in thread id 6289745148710612373 and this is thread id 6267641313725463650
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.3
 - DuckDB Client: python

**Comment by pdet** [comment]
Hey @zachary62, if you want to use the same connection on different threads you must set ```check_same_thread=false```   when creating the connection. But it should only be used if you can guarantee sequential access to the database from different threads. Otherwise, you should create a connection per thread.
