### ISSUE TITLE
Incorrect Join Ordering Due To Incorrect Join Node Cost Calculation

### ISSUE THREAD

**Issue by tapansriv** [duckdb/duckdb#3525]
The join order chosen by DuckDB's optimizer can put large tables at the bottom of join trees, resulting in very large intermediate results. This can have significant impacts on query performance. 

This is perhaps related to issues #75, #2329, and #3254, although inaccuracy in cardinality estimation could be playing a factor in some of those issues as well.

I am a Ph.D. student at the University of Chicago with Raul Castro Fernandez, and I found this while working on a research project. I am using TPC-DS at SF1000, with tables stored in parquet files (the queries read directly from them). I can provide the parquet files if needed. I reproduced this in a number of queries, but I’ll provide text for query 37 since it’s a simple example that illustrates the issue. The query text is: 
```
SELECT i_item_id,
       i_item_desc,
       i_current_price
FROM 'item.parquet' AS item,
     'inventory.parquet' AS inventory,
     'date_dim.parquet' AS date_dim,
     'catalog_sales.parquet' AS catalog_sales
WHERE i_current_price BETWEEN 68 AND 68 + 30
  AND inv_item_sk = i_item_sk
  AND d_date_sk=inv_date_sk
  AND d_date BETWEEN cast('2000-02-01' AS date) AND cast('2000-04-01' AS date)
  AND i_manufact_id IN (677,
                        940,
                        694,
                        808)
  AND inv_quantity_on_hand BETWEEN 100 AND 500
  AND cs_item_sk = i_item_sk
GROUP BY i_item_id,
         i_item_desc,
         i_current_price
ORDER BY i_item_id
LIMIT 100;
```

The issue seems to stem from `join_order_optimizer.cpp:214`. This line sets the cost of the new join node as simply the max cardinality of the left and right relation. However, this fails to consider that the previous joins already had to run, as the comment above line 214 notes. As a result, the cost of any ordering of these joins is simply the same: it will be the cardinality of the largest relation. So the join order chosen for the entire tree will be whatever is emitted first. However the relations are initially ordered will have a major impact on query performance. If the emitted pair that joins all relations happens to have the largest table at the bottom, that will be the plan that's chosen, as any subsequent join ordering that puts the largest table further at the top will have an identical cost to the first emitted plan, since the cost of every tree is simply the max cardinality of all its relations.

I believe the fix here is straightforward: have the cost be the max cardinality of left and right child, plus the costs of the left and right child. This ensures that if a large intermediate is generated, that cost is passed up and reflected in the cost of the entire plan; furthermore it matches what the existing documentation indicates should be happening.  The commit linked makes that change. 

The line used to read: `idx_t cost = expected_cardinality;`
It now reads               : `idx_t cost = expected_cardinality + left->cost + right->cost`

I am running on Ubuntu. In my setup I have TPC-DS at SF1000, with tables stored as Parquet files. The TPC-DS queries have been rewritten for DuckDB to read from Parquet files. Currently, query 37 results in a join order where the largest table of the 4 being joined is at the bottom of the join tree in DuckDB's normal join order output. With this setup it takes about 1.5 hours to complete. Manually reordering the joins can speed this up to ~5 minutes. I have verified that this is the case by looking at query plans produced. I have reproduced this on the latest master branch by building from source, as well as through the Java and Python clients. The commit linked changing the calculation of cost for join nodes fixes this particular join ordering problem. I verified that this commit results in a different query plan for query 37, moving the large table (catalog_sales) to the top of the join tree. 

I'm unsure if a unit test makes sense to add here: maybe something which uses query 37 and checks the query plan, although this might be impacted by changes to other parts of the optimizer. If anyone has suggestions I'll be glad to add one, I just couldn't come up with an idea which would test this in isolation.

**Comment by Mytherin** [comment]
Thanks for the detailed report, this fix makes sense to me. Perhaps @Tmonster can have a look as well as he is currently working on the join order optimizer?

**Comment by Tmonster** [comment]
Hi @tapansriv,

I found this same issue about the same time you did I think, and had a similar idea for the fix. The fix also improves the result of query 9 in the tpch benchmark at scale factor 1, however, it considerably hurts the performance of query 5.

I'm working on implementing better cardinality estimation and join ordering, but don't imagine my results will be committed anytime soon. As for a way to automatically test the fix, I can't imagine what works best. I think @Mytherin might have some good ideas. Mark, should I just go ahead and make a PR for this?

**Comment by tapansriv** [comment]
Hi @Tmonster, 

So it seems that this PR was causing a performance regression in a different, commonly run query in the duckdb test suite, so I believe that the decision was to not pull in this fix until the cardinality estimation/join ordering estimation was improved. I'm happy to help/contribute both in the interim on the cardinality estimation and also when that improves to a point that the join ordering structure can be revisited.

In the meantime though I think that the discussion on the PR  (#3526) indicates that we'll delay pulling that fix in.
