### ISSUE TITLE
Python crash with list_has

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#3527]
#### What happens?
Process crashes running

import duckdb
duckdb.connect(':memory:').execute("SELECT 't' WHERE list_has(?, 1)", [[1,2,3]]).df()

#### Environment (please complete the following information):
 - OS: Windows, OSX
 - DuckDB Version: 0.3.4, 0.3.5.dev184
 - DuckDB Client: Python

#### Before Submitting

- [X ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
This is possibly already fixed in the master by #3375

**Comment by Mytherin** [comment]
Closing this, appears to work for me in the latest master. Feel free to re-open if you can reproduce this there.
