### ISSUE TITLE
Unexpected query result of histogram aggregation

### ISSUE THREAD

**Issue by kagamiori** [duckdb/duckdb#3529]
Hi, I ran a query with DuckDB that uses the `histogram()` aggregation function, but the query result was different from what I expected. I'm wondering whether this issue can be reproduced at your side as well?

#### What happens?
I ran a query `SELECT c0, histogram(c1) FROM tmp GROUP BY c0` with the following data in the `tmp` table:
| c0 | c1 |
|----|----|
| 0  | 0  |
| 1  | 1  |
| 2  | 0  |
| 0  | 1  |
| 1  | 0  |
| 2  | 1  |
| 0  | 0  |
| 1  | 1  |
| 2  | 0  |
| 0  | 1  |

The result I got from DuckDB was the following:
	0 | [{"key":0,"value":2},{"key":1,"value":2}]
	1 | [{"key":0,"value":1},{"key":1,"value":2}]
	2 | [{"key":0,"value":1},{"key":1,"value":2}]

The result I expected was the following:
	0 | [{"key":0,"value":2},{"key":1,"value":2}]
	1 | [{"key":0,"value":1},{"key":1,"value":2}]
	2 | [{"key":0,"value":2},{"key":1,"value":1}]

#### Environment (please complete the following information):
 - OS: macOS 12.3.1
 - DuckDB Version: v0.3.5-dev230

CC: @[mbasmanova](https://github.com/facebookincubator/velox/commits?author=mbasmanova)

**Comment by hannes** [comment]
Something's off here, I get 

```
┌────┬──────────────────────┐
│ c0 │    histogram(c1)     │
├────┼──────────────────────┤
│ 0  │ {0=2, 1=2}           │
│ 1  │ {0=1, 1=2}           │
│ 2  │ {0=1, 1=2, 0=2, 1=1} │
└────┴──────────────────────┘
```

Also, please make sure tests cases are directly reproducible. Here is the data creation commands I used:

```SQL
create table tmp (c0 integer, c1 integer);
insert into tmp values 
(0,	0),
(1,	1),
(2,	0),
(0,	1),
(1,	0),
(2,	1),
(0,	0),
(1,	1),
(2,	0),
(0,	1);
```

**Comment by hannes** [comment]
maybe @pdet can have a look?

**Comment by kagamiori** [comment]
#3531 works for me. Thank you very much for the quick fix!

**Comment by pdet** [comment]
@kagamiori thank you for the bug report :-) !
