### ISSUE TITLE
Casting TIMESTAMPTZ to DATE should not be allowed

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#3534]
#### What happens?
The current implementation of this cast truncates to UTC.

#### To Reproduce
This should fail:

```sql
SELECT '2021-04-29 10:50:09-05'::TIMESTAMPTZ::DATE
```

`TIME` should be disallowed too.

#### Environment (please complete the following information):
 - OS: OSX
 - DuckDB Version: 0.3.4
 - DuckDB Client: Test harness

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by kimmolinna** [comment]
How do you get a date or a time from timetatampdz field?

**Comment by hawkfish** [comment]
You mean in a given time zone?

```sql
require icu

Set TimeZone='...';

SELECT MAKE_DATE(DATE_PART(['year', 'month', 'day'], tstz)), ... 
FROM ...;

-- Less elegant, but we could make a similar API
SELECT MAKE_TIME(parts['hour'], parts['minute'], parts['ms'] / 1000000.0), *
FROM (SELECT DATE_PART(['hour', 'minute', 'ms'], tstz) AS parts, ...
    FROM ...
)
```

**Comment by kimmolinna** [comment]
Exactly, in a given time zone and because this is possible why casting should not be allowed? Your code is quite complicated so I think the casting SHOULD be allowed. :)

**Comment by hawkfish** [comment]
The real problem is that at the moment we can't add casting operations in extensions. This is planned, but for now truncating does not Do The Right Thing (it just truncates the instant in GMT). If that is really what you want, then you can just say:

```sql
SELECT tstz::TIMESTAMPTZ::DATE, ...
```

which at least has the benefit of making what you are doing explicit.
