### ISSUE TITLE
The `.save` command isn't working in CLI

### ISSUE THREAD

**Issue by amjith** [duckdb/duckdb#3536]
#### What happens?
I'm trying to create a persistent duckdb using the .save file.db command. But I get this error when I try to do that: 
```
D .save accessible.duckdb
sqlite3_backup_init: unsupported.
Error:
```

#### Environment (please complete the following information):
 - OS: MacOS Monterey (Mac M1)
 - DuckDB Version: v0.3.3 fe9ba8003
 - DuckDB Client: CLI

**Comment by hannes** [comment]
This is unsupported at the moment.
