### ISSUE TITLE
FTS index not updated after INSERT

### ISSUE THREAD

**Issue by patrickpang** [duckdb/duckdb#3543]
#### What happens?

I believe this is more of a limitation than a bug: DuckDB is meant to be used in OLAP scenarios where your dataset is mostly static.
However, given that we do provide an INSERT statement, which is also used in the example, it might be better if this is stated explicitly in the documentation.
Otherwise, people coming from OLTP world like SQLite would expect the index to be updated automatically.
Would actually be nice to have this feature as well going forward.

#### To Reproduce

Steps to reproduce the behavior. Bonus points if those are only SQL queries.

Adapted from FTS documentation: https://duckdb.org/docs/extensions/full_text_search
When we create the table and index, then insert data, the FTS index is not updated.

```sql
-- create a table
CREATE TABLE documents(document_identifier VARCHAR, text_content VARCHAR, author VARCHAR, doc_version INTEGER);
-- build the index (make both the 'text_content' and 'author' columns searchable)
PRAGMA create_fts_index('documents', 'document_identifier', 'text_content', 'author');
-- fill it with text data
INSERT INTO documents
VALUES ('doc1', 'The mallard is a dabbling duck that breeds throughout the temperate.','Hannes Mühleisen', 3),
       ('doc2', 'The cat is a domestic species of small carnivorous mammal.', 'Laurens Kuiper', 2);
-- search the 'author' field index for documents that are written by Hannes - this returns empty
SELECT text_content, score
FROM (SELECT *, fts_main_documents.match_bm25(document_identifier, 'Muhleisen', fields := 'author') AS score
      FROM documents) sq
WHERE score IS NOT NULL
  AND doc_version > 2
ORDER BY score DESC;
-- search for documents about 'small cats' - this returns empty
SELECT text_content, score
FROM (SELECT *, fts_main_documents.match_bm25(document_identifier, 'small cats') AS score
      FROM documents) sq
WHERE score IS NOT NULL
ORDER BY score DESC;
```

#### Environment (please complete the following information):
 - OS: WSL 2 Ubuntu
 - DuckDB Version: 0.3.4
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
This is expected behaviour. We might be able to make the full text index updatable eventually @lnkuiper

**Comment by patrickpang** [comment]
Thanks @hannes. Meanwhile shall we update the documentation to state this explicitly?

**Comment by hannes** [comment]
Sure, can you send a PR to the duckdb-web repo perhaps?

**Comment by patrickpang** [comment]
@hannes here we go: https://github.com/duckdb/duckdb-web/pull/207

**Comment by jez9999** [comment]
There are also discussion about this [here](https://github.com/duckdb/duckdb/discussions/5352) and [here](https://github.com/duckdb/duckdb/discussions/15094).  Boy, how I wish DuckDB would implement this.  I could finally stop using the painful SQLite.
