### ISSUE TITLE
`struct` type not supported in node.js

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#3544]
#### What happens?

We've known this for a while, but figured I'd add this issue to the backlog. Node.js does not currently convert structs to javascript objects, so as a consequence users will get an error when selecting a struct. [We're starting to get bug reports about this on our end](https://github.com/rilldata/rill-developer/issues/184).

Ideally, the struct should convert to a javascript object.

#### To Reproduce

```
SELECT {'x': 1, 'y': 2, 'z': 3};
```

#### Environment (please complete the following information):
 - DuckDB Version: [e.g. 22]
 - DuckDB Client: [e.g. Python]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
@ankoh has been working on this for the WASM client and I heard he might have a go at the node.js API too regarding this ^^
