### ISSUE TITLE
`INSERT` with `RETURNING` performs no insertion.

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [duckdb/duckdb#3548]
#### What happens?

`INSERT` with `RETURNING` performs no insertion.

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

```sql
 CREATE TABLE table1 (a INTEGER DEFAULT -1, b INTEGER DEFAULT -2, c INTEGER DEFAULT -3);
 INSERT INTO table1 VALUES (1, 2, 3) RETURNING *;
 SELECT COUNT(*) FROM table1;
```
The last SQL query should return 1.

![image](https://user-images.githubusercontent.com/28505034/166136304-f548a8d2-23d1-4b25-8aac-f5a34a7e3bae.png)

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.4
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
@Tmonster maybe you can have a look here?

**Comment by Tmonster** [comment]
yup! will take a look this week

**Comment by Tmonster** [comment]
Just had a chat with @lnkuiper and we have a strong feeling that this issue is because of the SQLite shell. The issue isn't reproducible using duckdb in python, or when creating a unit test with the exact same sql. The sqlite shell code is pretty complex so going to wait for @Mytherin to come back from vacation before investigating further
