### ISSUE TITLE
Segmentation Fault When Reading a CSV and explicitly typing a column as a Decimal

### ISSUE THREAD

**Issue by niger-prequel** [duckdb/duckdb#3562]
#### What happens?
When reading a CSV file using `read_csv()`, one can provide a column struct with types via the `columns` argument. Typing a column as decimal (with precision and scale) leads to a segmentation fault. 

#### To Reproduce
- Download a[ simple CSV](https://data.cityofnewyork.us/Transportation/Subway-Entrances/drex-xx56) like this one found here
- Open DuckDB via the CLI or something like Python
- Run a query like `SELECT * FROM read_csv('DOITT_SUBWAY_ENTRANCE_01_13SEPT2010.csv', header=TRUE, columns={'OBJECTID': 'DECIMAL(18,3)', 'URL': 'TEXT', 'NAME': 'TEXT', 'the_geom':'TEXT', 'LINE': 'TEXT'})`
- Segementation fault should occur immediately.

One thing to note is that if no precision is provided, the error is `Error: INTERNAL Error: INTERNAL Error: Invalid PhysicalType for GetTypeIdSize`

#### Environment (please complete the following information):
 - OS: Tested on an M1 Mac Running OSX 12.2.1 Monterrey and Docker on Linux (GCP)
 - DuckDB Version: 0.3.3
 - DuckDB Client: CLI, ODBC, and Golang drivers

**Comment by hannes** [comment]
I can confirm that this crashes.

**Comment by hannes** [comment]
See #3564

**Comment by hannes** [comment]
Guys, looks like you are using DuckDB at Prequel. If there is serious usage, may I suggest you join the DuckDB Foundation https://duckdb.org/foundation/ ? Let me know if you have any questions.
