### ISSUE TITLE
duckdb cli cannot recognize reading from parquet functions

### ISSUE THREAD

**Issue by Jimexist** [duckdb/duckdb#3570]
#### What happens?
A short, clear and concise description of what the bug is.

with `duckdb` installed from homebrew (M1 macOS) the reading from parquet function is broken (per docs).

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

```
❯ duckdb
v0.3.4 662041e2b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT * FROM 'test.parquet';
Error: Catalog Error: Table with name test.parquet does not exist!
LINE 1: SELECT * FROM 'test.parquet';
                      ^
D SELECT * FROM parquet_metadata('test.parquet');
Error: Catalog Error: Table Function with name parquet_metadata does not exist!
Did you mean "repeat"?
LINE 1: SELECT * FROM parquet_metadata('test.parquet');
                      ^
D select * from './aggregate_test_100.parquet';
Error: Catalog Error: Table with name ./aggregate_test_100.parquet does not exist!
LINE 1: select * from './aggregate_test_100.parquet';
                      ^
```

#### Environment (please complete the following information):
 - OS: [e.g. iOS] macOS 12.3.1 (21E258)
 - DuckDB Version: [e.g. 22] v0.3.4 662041e2b
 - DuckDB Client: [e.g. Python] CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Jimexist** [comment]
For reference the homebrew formula is https://github.com/Homebrew/homebrew-core/blob/master/Formula/duckdb.rb

**Comment by hannes** [comment]
Try `INSTALL 'parquet';` (once) followed by `LOAD 'parquet'`?

**Comment by Jimexist** [comment]
i guess [adding to instructions][1] about the loading is also helpful

[1]: https://github.com/duckdb/duckdb-web/pull/209

**Comment by maxcountryman** [comment]
Any fix for this? I'm encountering the same issue trying to install the parquet extension on macOS:

```
D install parquet;
Error: IO Error: Failed to download extension http://extensions.duckdb.org/662041e2b/osx_amd64/parquet.duckdb_extension.gz
```

**Comment by Jimexist** [comment]
see https://github.com/duckdb/duckdb/issues/3680

**Comment by dimasfazio** [comment]
I have had the same issue with Windows. I use duckdb to read parquet files on R. Solution so far has been to revert to an older version, but it would be nice if this problem was solved soon. Thanks

**Comment by samansmink** [comment]
will close this issue as the parquet extension is now built for macos allowing install/load
