### ISSUE TITLE
Connection does not work when using "with duckdb.connection(...) as con:" Python Error: AttributeError: __enter__

### ISSUE THREAD

**Issue by diegomestre2** [duckdb/duckdb#3573]
When using the following structure to create a connection in the python api
the script breaks:
```{python}
    with duckdb.connect(database=dbname, read_only=False) as con:
        block
```
 - OS: [MacOS]
 - DuckDB Version: [v0.3.4]
 - DuckDB Client: [Python]

One  idea to support this would be following the code below:
```{python}
@contextmanager
def connect(database=dbname, read_only=False):
    con = duckdb.connect(database=dbname, read_only=False)
    try:
        yield con
    finally:
        con.close()
```

**Comment by Alex-Monahan** [comment]
Thanks for having a look at this! A context manager would be a really nice user experience, especially while I'm tinkering around in Jupyter. Thanks @pdet!
