### ISSUE TITLE
The CLI link on the website is broken

### ISSUE THREAD

**Issue by jsteelz** [duckdb/duckdb#3581]
#### What happens?

Upon going to the website, navigating to the Installation section, and selecting CLI, the arm-64 link seems broken. It leads to a GH generic Not Found page.

#### To Reproduce
Go to the website on an ARM mac. It appears that the issues is because the latest CLI version is not listed for ARM.

#### Environment (please complete the following information):
 - OS: mac OS on M1
 - DuckDB Version: -
 - DuckDB Client: -

**Comment by hannes** [comment]
Indeed we need to fix this

**Comment by hannes** [comment]
This seems fixed
