### ISSUE TITLE
Feature request:  Allow aliases and wildcards in the ROW() function.

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#3582]
allow wild cards and aliases in the `ROW()` function.  This is particularly useful in building map/reduce queries.  You want to transform an orders table into a table by user/date and have all the orders nested beneath.  

```
  select 
    date(event_time) as event_date,
    user_id,
    list(ROW(orders)) as orders
  from orders
  group by 1,2
```

Another form of this is: 

   `ROW( * except (user_id) )` 

Both Postgres and BigQuery support some form of this.
   https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_except

**Comment by hannes** [comment]
See also #3569

**Comment by mikekap** [comment]
I think in bigquery-land if you wanted to do except for a struct, you'd have to do something like:

```sql
with orders as (
select 1 as user_id, TIMESTAMP "2022-01-01" as event_time, 'hello' as other_field
)

select
date(event_time) as event_date,
user_id,
array_agg((select as struct orders.* except(user_id))) as all_orders
from orders
group by 1, 2
```
