### ISSUE TITLE
Tpch queries doesn't run on M1

### ISSUE THREAD

**Issue by sughosh360** [duckdb/duckdb#3584]
I'm trying to run tpch queries on M1 but unable to do so. Not hitting the query engine
<img width="1512" alt="Screen Shot 2022-05-05 at 8 24 56 PM" src="https://user-images.githubusercontent.com/7828244/167047388-be7a14d3-7ace-4da9-b985-f66cd6572248.png">
.

**Comment by hannes** [comment]
try adding `-DBUILD_TPCH_EXTENSION=1` to the build flags, I don't think that's M1 related
