### ISSUE TITLE
BETWEEN with subquery and column results in unexpected error

### ISSUE THREAD

**Issue by kokrui** [duckdb/duckdb#3588]
#### What happens + To Reproduce
Consider the following test case:
```sql
CREATE TABLE t0(c0 INT);
SELECT * FROM t0 WHERE (SELECT 0) BETWEEN 0 AND t0.c0; 
-- Error: INTERNAL Error: Attempting to initialize state of expression of unknown type!
```
My understanding is that I'd expect no error being raised since all the expressions in the `BETWEEN` comparison are resolved to integer types?

It seems like this only triggers when both the subquery and the column used in the BETWEEN operator are present. That is to say that:
```sql
SELECT * FROM t0 WHERE 0 BETWEEN 0 AND t0.c0;
```
as well as
```sql
SELECT * FROM t0 WHERE (SELECT 0) BETWEEN 0 AND 5;
```
result in expected behaviour.

Found on DuckDB v0.3.4 while working with @mrigger on experimental SQLancer features.

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.4
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
Indeed its a bug, an INTERNAL error should never bubble up

**Comment by hawkfish** [comment]
Looks like there is an `||` instead of an `&&` in `FilterCombiner::AddFilter`
