### ISSUE TITLE
Include Linux ARM shared library in duckdb_jdbc.jar

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#3590]
I would like to request the inclusion, and use of, a Linux ARM shared library in the duckdb_jdbc jar. At Mode we have a use case where we want to run DuckDB in Linux ARM containers. Without the inclusion of this shared library we cannot run DuckDB.

**Comment by hannes** [comment]
Happy to. Which exact ARM architecture do you use? The AWS one?

**Comment by michaeljohnalbers** [comment]
Apple M1 Silicon. We run our code in a Linux container on Apple M1 laptops in development.

**Comment by hannes** [comment]
The last version should already include this, no?

**Comment by hannes** [comment]
that's a bit exotic, what's the output of `uname -a` on that container?

**Comment by michaeljohnalbers** [comment]
`Linux e41e2e4e0675 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by hannes** [comment]
Ok, `aarch64` should work then.

**Comment by michaeljohnalbers** [comment]
@hannes It doesn't appear that this will be part of 0.4.0. Is there a plan to get it included in the next release?

**Comment by rkennedy-mode** [comment]
@divyar1101 https://github.com/duckdb/foundation-discussions/discussions/5#discussioncomment-3099137

> I've looked into this issue a bit and will work on getting the aarch64 binaries built in CI in the coming week. This should then be available on Maven Central in the next release of DuckDB which is scheduled around the 20th of August.

**Comment by hannes** [comment]
See also #941

**Comment by hannes** [comment]
There is now a PR for this, #4511
