### ISSUE TITLE
Feature Request: CREATE TEMPORARY MACRO

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#3591]
Creating temporary functions are really useful when generating dynamic SQL.  It would be awesome if this was supported (available in Postgres and Bigquery).

CREATE TEMPORARY MACRO some_func() ... ;

SELECT some_func(..) FROM ..

**Comment by lnkuiper** [comment]
Hi @lloydtabb , I might be missing something here, but on the latest master I can do:
```
$ ./build/debug/duckdb temp.db
-- Loading resources from /Users/laurens/.duckdbrc
v0.1.2-dev12766 0a96249d0
Enter ".help" for usage hints.
D create temporary macro test() as (select 42);
D select test();
┌────────┐
│ test() │
├────────┤
│ 42     │
└────────┘
D .quit
[laurens@mac] ~/git/duckdb
$ ./build/debug/duckdb temp.db
-- Loading resources from /Users/laurens/.duckdbrc
v0.1.2-dev12766 0a96249d0
Enter ".help" for usage hints.
D select test();
Error: Catalog Error: Scalar Function with name test does not exist!
Did you mean "text"?
LINE 1: select test();
               ^
```
The macro is temporary: it is no longer there after restarting the DB.

**Comment by lloydtabb** [comment]
Sorry, I was running an old version.  Just verified this is working for me.
