### ISSUE TITLE
Joining on arrow tables on `float64` types is ~5x slower on M1 `arm64`

### ISSUE THREAD

**Issue by hussainsultan** [duckdb/duckdb#3595]
#### What happens?
Joining on arrow tables on `float64` types is ~5x slower on M1 `arm64` vs `x86`. The code below produced nearly identical times when run on an `x86` machine. 

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
### Joining on `float64`
```python
import pyarrow as pa
import duckdb
import numpy as np

conn = duckdb.connect()
arr1 = pa.array(np.arange(1000), type=pa.float64())
arr2 = pa.array(np.arange(1000), type=pa.float64())
t1_f = pa.table([arr1], names=["id"])
t2_f = pa.table([arr2], names=["id"])
```
```py
 %timeit -n 10 -r 3 conn.execute("select * from t1_f, t2_f where t1_f.id = t2_f.id").fetchall()
4.99 ms ± 1.51 ms per loop (mean ± std. dev. of 3 runs, 10 loops each)
```

### Joining on `int64`
```py
arr1 = pa.array(np.arange(1000), type=pa.int64())
arr2 = pa.array(np.arange(1000), type=pa.int64())
t1_int = pa.table([arr1], names=["id"])
t2_int = pa.table([arr2], names=["id"])
```

```py
In [20]: %timeit -n 10 -r 3 conn.execute("select * from t1_int, t2_int where t1_int.id = t2_int.id").fetchall()
869 µs ± 131 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)
```
### Platform Specs
```json
{"machine": "arm64", "platform": "macOS-12.1-arm64-arm-64bit", "system": "Darwin", "cpu_count": 8}
```
#### Environment (please complete the following information):
 - OS: iOS (arm64)
 - DuckDB Version: 0.3.4
 - DuckDB Client:  Python

#### Before Submitting

- [x ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hussainsultan** [comment]
cc: @cpcloud

**Comment by pdet** [comment]
Can you also share the specs of the x86 machine?

**Comment by hussainsultan** [comment]
Here you go:
```
{"machine": "x86_64",  "platform": "Linux-5.17.5-76051705-generic-x86_64-with-glibc2.35", "system": "Linux", "cpu_count": 48}
```

and here are the %timit:
```python
In [22]: %timeit -n 10 -r 3 conn.execute("select * from t1_f, t2_f where t1_f.id = t2_f.id").fetchdf()
1.64 ms ± 96.3 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)
In [23]: %timeit -n 10 -r 3 conn.execute("select * from t1_int, t2_int where t1_int.id = t2_int.id").fetchdf()
1.62 ms ± 217 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)
```

**Comment by alanpaulkwan** [comment]
I wonder if this is related to a bug I filed awhile ago.. https://github.com/duckdb/duckdb/issues/2909

**Comment by alanpaulkwan** [comment]
Upon further testing, I think they are related. In my query, the join on doubles takes forever, but the join on integers happens very fast.

**Comment by hannes** [comment]
Since we use the same code on both architectures, I think this may be compiler/hardware related.

**Comment by alanpaulkwan** [comment]
I'm really glad at least the integer / string comparisons are sufficiently fast.  It is just a bit annoying that R tends to turn integers into numeric but that is easy to work around.

Absent discovering this, it makes DuckDB unusable on my M1 Mac.

**Comment by pj-ml** [comment]
Using a M1 Max 
I had a terrible experience joining on float (which took 10min) vs casting to integer and then joining (which took 240ms)
2500x difference
