### ISSUE TITLE
Memory leak when making multiple queries using same JDBC Statement

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#3610]
#### What happens?
When using the Java client, there is a memory leak when executing multiple queries using the same `Statement` object. This may exist without using the Java client; I only tested this using the Java client.

An easy workaround is to simply create a new `Statement` object for each query.

#### To Reproduce
See https://github.com/rkennedy-mode/duckdb-leak-reproduction. The repo contains source code and instructions on how to reproduce the issue. The README also includes a chart showing the leak and the allocation graph from jemalloc. (This same repo was used previously for a memory leak we reported. It has been updated for this new issue.)

#### Environment (please complete the following information):
 - OS: Ubuntu Linux 22.04
 - DuckDB Version: 0.3.3
 - DuckDB Client: Java

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.
Yes, mostly. To gather the debug information for jemalloc, I build a custom DuckDB JAR file. It was built off commit `9462bc22393515984b0df1924146540ee85f13b9`. I built that with Java 8, GCC 11.2.0.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
Yes, see the aforementioned repo for reproduction information.

**Comment by Jens-H** [comment]
Maybe the ResultHolder struct is never deleted.
https://github.com/duckdb/duckdb/blob/d57a75443506a489656d008132cf127a88e7890b/tools/jdbc/src/jni/duckdb_java.cpp#L378

**Comment by Jens-H** [comment]
Can you try to close the ResultSet before reusing it?

**Comment by michaeljohnalbers** [comment]
Each use of `ResultSet` is wrapped in a try-with-resources block. So they should be closed automatically.
https://github.com/rkennedy-mode/duckdb-leak-reproduction/blob/master/src/main/java/com/mode/ryankennedy/duckdbleak/Main.java#L54-L64

**Comment by Jens-H** [comment]
Ok, that's great. Then there is the StatementHolder struct that is created for each query, but only deleted in the Statement.close() method.

https://github.com/duckdb/duckdb/blob/ca395eda2944a7c69cb4353041799cd92903e663/tools/jdbc/src/jni/duckdb_java.cpp#L264

**Comment by Jens-H** [comment]
I created a branch that should delete the StatementHolder properly. Maybe you can run your test against it.

https://github.com/Jens-H/duckdb/tree/3610-mem-leak

**Comment by michaeljohnalbers** [comment]
@Jens-H Looks like your fix worked. Thanks!

**Comment by Cinzq4615** [comment]
I tried this on the latest master branch,When using the Java client, there is still a memory leak when executing multiple queries using the Statement object.

**Comment by Jens-H** [comment]
> I tried this on the latest master branch,When using the Java client, there is still a memory leak when executing multiple queries using the Statement object.

@Cinzq4615 
After  #3894, could you please retry if this is also solved?

**Comment by Cinzq4615** [comment]
@Jens-H 
Thanks,I think this issue was fixed .
