### ISSUE TITLE
RuntimeError when running with flask app in debug.

### ISSUE THREAD

**Issue by AshCam1988** [duckdb/duckdb#3617]
#### What happens?
When I run my code, I get the following error when attempting to connect to a file in python.
```
RuntimeError: IO Error: Cannot open file "duck.db": The process cannot access the file because it is being used by another process.
```
#### To Reproduce
1. Create a python file
2. Add the following:
  - Create a flask app
  - (start ``if __name__ == "__main__" block``)
  - Use ``os.chdir()`` to set working directory to file's directory
  - Load config from .env using ``python-dotenv``
  - Connect to database (file parameter using a .env entry)
  - Run the flask app
3. Create a .env file
4. Add the following:
  - ``DB`` variable (to store database filename)
  - ``FLASK_ENV`` variable with value of ``development``
  - ``FLASK_DEBUG`` variable with a value of ``True``, ``true`` or ``1``
5. Run the python file

EXAMPLE:
main.py (name doesn't matter)
```py
from dotenv import load_dotenv
import os
import duckdb as db
import flask

app = flask.Flask(__name__)

if __name__ == '__main__':
    os.chdir(os.path.dirname(os.path.realpath(__file__)))
    load_dotenv()
    con = db.connect(os.getenv("DB"))
    app.run(port=80)
```

.env
```
DB=duck.db
FLASK_ENV=development
FLASK_DEBUG=1
```

#### Environment (please complete the following information):
 - OS: Windows 10 on x86_64
 - DuckDB Version: 0.3.4 (assuming you mean the pip package version) AND 0.3.5-dev
 - DuckDB Client: Python 3.10.4

#### Before Submitting

- [✓ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`

- [ ✓] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mause** [comment]
The full stack trace would be helpful here?
The reason is probably that you're connecting to the database from multiple threads in your app

**Comment by Alex-Monahan** [comment]
@Mause is spot on! I would also add that even if you only have 1 thread connecting to the database, you likely want to disconnect when you are done using it / upon the shutdown of your flask app.

**Comment by hannes** [comment]
To add to this, its better to connect in the main thread and use `.cursor()` to create a new connection for each thread. Not sure how to do this with Flask though, but in general it works as designed.
