### ISSUE TITLE
DuckDB 0.3.4 fetch_arrow_table() is over 20x slower vs 0.3.2

### ISSUE THREAD

**Issue by CedricYauLBD** [duckdb/duckdb#3621]
#### What happens?

fetch_arrow_table() appears to be significantly slower in 0.3.4 vs 0.3.2 (124 seconds vs 5.55 seconds)

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

!aws s3 cp s3://ursa-labs-taxi-data/2015/06/data.parquet /tmp

# using pyarrow==7 and duckdb 0.3.2

[ins] In [1]: import duckdb
[ins] In [2]: c = duckdb.connect()
[ins] In [5]: duckdb.__version__
Out[5]: '0.3.2'

[ins] In [6]: %time r = c.execute("select * from parquet_scan('/tmp/data.parquet')")
CPU times: user 17.7 ms, sys: 4.39 ms, total: 22.1 ms
Wall time: 26.4 ms

[ins] In [7]: %time t = r.fetch_arrow_table()
CPU times: user 5.55 s

------
# using pyarrow==7 and duckdb 0.3.4
# pyarrow==8 is also slow

[ins] In [1]: import duckdb
[nav] In [2]: c = duckdb.connect()

[ins] In [3]: duckdb.__version__
Out[3]: '0.3.4'

[ins] In [4]: %time r = c.execute("select * from parquet_scan('/tmp/data.parquet')")
CPU times: user 5.36 ms, sys: 7.14 ms, total: 12.5 ms
Wall time: 12 ms

[ins] In [5]: %time t = r.fetch_arrow_table()
CPU times: user 1min 46s, sys: 20 s, total: 2min 6s
Wall time: 2min 4s

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04
 - DuckDB Version: 0.3.4
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
'0.3.5-dev359'

[ins] In [5]: %time t = r.fetch_arrow_table()
CPU times: user 1min 29s, sys: 12.5 s, total: 1min 41s
Wall time: 1min 40s

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yes.  Created separate conda and docker environments.

**Comment by Alex-Monahan** [comment]
Hello!

Could you try a few different values for the new chunk size parameter? That might be the difference...
https://github.com/duckdb/duckdb/pull/3173

**Comment by pdet** [comment]
I think is probably fair (and a good idea) to add regression tests on the Python API, especially on the Pandas and Arrow integrations.

But as Alex pointed out, this issue can be related to chunk sizes. The previous code would always gerenate an arrow table with one chunk, so if you set the chunk_size parameter to whatever is the table size, that should generate something similar to the prior duckdb version.

**Comment by CedricYauLBD** [comment]
> Hello!
> 
> Could you try a few different values for the new chunk size parameter? That might be the difference... #3173

Ok.  Definitely works faster with chunks being small like 1K.   I do not understand why larger chunk size is slower.  

[ins] In [9]: %time t = r.fetch_arrow_table(100000)                                      CPU times: user 8.8 s, sys: 1.39 s, total: 10.2 s                                        Wall time: 10.2 s                                                                                                                                                                 [ins] In [10]: %time r = c.execute("select * from parquet_scan('/tmp/data.parquet')")    CPU times: user 8.71 ms, sys: 181 µs, total: 8.89 ms                                     Wall time: 8.51 ms                                                                                                                                                                [ins] In [11]: %time t = r.fetch_arrow_table(10000)                                      CPU times: user 2.89 s, sys: 609 ms, total: 3.5 s                                        Wall time: 3.49 s                                                                                                                                                                 [ins] In [12]: t.num_rows                                                                Out[12]: 12324935                                                                                                                                                                 [ins] In [13]: %time r = c.execute("select * from parquet_scan('/tmp/data.parquet')")    CPU times: user 10.9 ms, sys: 0 ns, total: 10.9 ms                                       Wall time: 10.6 ms                                                                                                                                                                [ins] In [14]: %time t = r.fetch_arrow_table(1000)                                       CPU times: user 2.53 s, sys: 141 ms, total: 2.67 s                                       Wall time: 2.67 s                                                                                                                                                                 [ins] In [15]: t.num_rows                                                                Out[15]: 12324935
