### ISSUE TITLE
[Format] Arrow CData Interface canonical guard

### ISSUE THREAD

**Issue by drabastomek** [duckdb/duckdb#3625]
I am building a FlightSQL example with DuckDB backend and using the `ArrowArray` construct. However, when I `#include <arrow/c/bridge.h>` the compiler complains that the `ArrowArray` is defined in multiple places: in `duckdb/common/arrow.hpp` and in `arrow/c/bridge.h`. 

There's work being done in Arrow to put canonical guards around the CData interface: https://github.com/apache/arrow/pull/13115. I think it'd be great to add similar in the `duckdb/common/arrow.hpp`.

**Comment by hannes** [comment]
Sure, can you send a PR please?

**Comment by drabastomek** [comment]
I'm assuming this can now be closed. I tested locally with the intended changes coming from Arrow and the imports work as intended. Thanks @hannes!
