### ISSUE TITLE
Unexpected result of current_schemas function

### ISSUE THREAD

**Issue by sergeykaul** [duckdb/duckdb#3631]
#### What happens?
Unexpected result of current_schemas

#### To Reproduce

$ ./duckdb
v0.3.4 662041e2b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE SCHEMA td;
D select current_schemas(true);
┌───────────────────────────────────────┐
│ current_schemas(CAST('t' AS BOOLEAN)) │
├───────────────────────────────────────┤
│ [temp, main, pg_catalog]              │
└───────────────────────────────────────┘
D CREATE SCHEMA td;
Error: Catalog Error: Schema with name td already exists!
D 

---
I expected to see 'td' in the return value of the function current_schemas

#### Environment (please complete the following information):
 - OS: [Fedora]
 - DuckDB Version: [0.3.4]
 - DuckDB Client: [CLI]

#### Before Submitting
Yes, I have tried this on the latest version

**Comment by Mytherin** [comment]
Thanks for the report!

This behavior is correct, `current_schemas` is supposed to return the list of *active* schemas, i..e the current schema search path, e.g.:

```sql
create schema td;
set search_path to td;
select current_schemas(true);
┌───────────────────────────────────────┐
│ current_schemas(CAST('t' AS BOOLEAN)) │
├───────────────────────────────────────┤
│ [temp, td, main, pg_catalog]          │
└───────────────────────────────────────┘
```


 If you want a list of all schemas try running `SELECT * FROM duckdb_schemas()`.

**Comment by sergeykaul** [comment]
Thanks for the clarification. I was inattentive when reading the documentation
