### ISSUE TITLE
[R] Crash when registering table with high-cardinality factor variable

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#3639]
This will produce a whole-process crash when ran on macOS (ARM variety):
```r
library(DBI)
library(duckdb)

conn <- dbConnect(duckdb::duckdb(), dbdir=":memory:", read_only=FALSE)
set.seed(123)
df <- data.frame(
    col1 = factor(sample(5000, 10^6, replace=TRUE))
)
duckdb_register(conn, "df", df)
```

~It works correctly on linux however.~ When ran on linux, it doesn't produce an instant crash, but will end up crashing the process a bit later. It displays an error message as follows:
```
Unexpected exception: basic_string::_M_create
Fatal error: Unexpected exception: basic_string::_M_create
```

Decreasing the cardinality of the factor variable to something like 10 will make it work without problems. Not sure at which specific threshold the crash happens though.

The crash occurs with the current release version from CRAN (0.3.2-2) and with the 0.3.4 version from the github releases page.

**Comment by hannes** [comment]
I can confirm this crashes

**Comment by hannes** [comment]
I opened a PR that fixes the issue on my machine at least. Thanks for reporting!
