### ISSUE TITLE
Uniqueness in keys is not ensured by MAP function like PrestoDB does

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#3640]
#### What happens?
Uniqueness in keys is not ensured by MAP function

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

Expected:
```sql
presto> select MAP(ARRAY[1, 1, 3, 4],ARRAY[10, 9, 8, 7]);
----
Query 20220513_121640_00001_hhhs4 failed: Duplicate map keys (1) are not allowed
```
Observed:
```sql
select MAP(LIST_VALUE(1, 1, 3, 4),LIST_VALUE(10, 9, 8, 7))
----
{1=10, 1=9, 3=8, 4=7}
```
Also NULL as a map key has this behavior on PrestoDB:
```sql
presto> select MAP(ARRAY[1, 1, 3, NULL],ARRAY[10, 9, 8, 7]);
----
Query 20220607_141513_00003_qpq6n failed: map key cannot be null
```
Arrow errors on this as well:
```py
pyarrow.lib.ArrowInvalid: Invalid Map: key field can not contain null values
```

#### Environment (please complete the following information):
 - OS: MacOS
 - DuckDB Version: [latest](https://github.com/duckdb/duckdb/tree/8008cf64a55bc159966eda7408f1d3520c12b7ef)
 - DuckDB Client: unittest

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Alex-Monahan** [comment]
Hello! Our map type deliberately supports duplicate values, so this is expected!

https://duckdb.org/docs/sql/data_types/map

"MAPs may also have duplicate keys. This is possible and useful because maps are ordered. "

**Comment by lnkuiper** [comment]
I didn't know that the duplicate keys were deliberate! However, our maps are not ordered (yet), so I think we should implement that

**Comment by Alex-Monahan** [comment]
Oh, well I defer to your expertise on whether or not it is intentional! :-) 

Thanks @lnkuiper!

**Comment by pdet** [comment]
Hm, The reason I implemented Map types was to be able to do round-trip Arrow data.

Arrow does allow for duplicates and does have an optional sorted-ness flag. I think we should keep it this way to ensure compatibility with the Arrow format.

**Comment by Tishj** [comment]
> Hm, The reason I implemented Map types was to be able to do round-trip Arrow data.
> 
> Arrow does allow for duplicates and does have an optional sorted-ness flag. I think we should keep it this way to ensure compatibility with the Arrow format.
> 
> Making it sorted is a different story. We can of course enforce this, at the cost of not having zero-copy for arrow maps. Or, like arrow, by having an extra option on the map type.

Ah that makes a lot more sense then, I thought it was an oversight at first.

Then the question becomes, which of the two has priority; support with Arrow maps or PrestoDB map function behavior

Or how could we support both?
Have a separate type for duplicate/unique keys?

**Comment by lnkuiper** [comment]
I think compatibility with Arrow data format has priority over matching Presto's behaviour. Adding a sortedness flag seems very reasonable, and we could think about adding a uniqueness flag at some point too

**Comment by pdet** [comment]
We just had a chat with our friends from Arrow, and it turns out that their map is also assuming uniqueness, but since there is no verification or constraint in that, they accept duplicates.
I guess we can then change to be unique.

**Comment by Tishj** [comment]
I have started work on this, feels like this should be fixed before I continue on the map_from_entries function, or any other map function

**Comment by Tishj** [comment]
Closing this as completed 😄
