### ISSUE TITLE
[R and Python] Cannot run query that has values not present in factor/Categorical column

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#3641]
This will throw an error:
```r
library(DBI)
library(duckdb)

df <- data.frame(
    col1 = factor(c("a", "b", "c"))
)
q <- "select * from df where col1 != ''"
conn <- dbConnect(duckdb::duckdb(), dbdir=":memory:", read_only=FALSE)
duckdb_register(conn, "df", df)
dbGetQuery(conn, q)
```
```
Error: duckdb_prepare_R: Failed to prepare query select * from df where col1 != ''
Error: Conversion Error: Could not convert string '' to UINT8
```

I guess it is trying to convert `''` to its underlying integer representation in the factor variable, but there is no mapping for it. It shouldn't require values passed in the query to already be a part of the factor encoding.

The same thing happens if I try something like this:
```sql
select col1
from df
    union all
select 'd' as col1
```
```
Error: duckdb_execute_R: Failed to run query
Error: Conversion Error: Could not convert string 'd' to UINT8
```

The problem also occurs in the Python interface:
```python
import pandas as pd
import duckdb

df = pd.DataFrame({
    "col1" : pd.Categorical(pd.Series(["a", "b", "c"]))
})
duckdb.query(
    "select * from df where col1 != ''"
).to_df()
```
```
RuntimeError: Conversion Error: Could not convert string '' to UINT8
```

**Comment by david-cortes** [comment]
@pdet But after the PR it produces incorrect results. This returns an empty data frame:
```python
import pandas as pd
import duckdb

df = pd.DataFrame({
    "col1" : pd.Categorical(pd.Series(["a", "b", "c"]))
})
duckdb.query(
    "select * from df where col1 != ''"
).to_df()
```

**Comment by Tishj** [comment]
Hmm this issue is weird, not even `physical_table_scan` is hit, so it looks like the query doesn't get recognized, because no plan is build that actually scans the dataframe

**Comment by Tmonster** [comment]
@david-cortes can you verify if this is still an issue? Running this on 0.8.1 doesn't produce any errors

**Comment by david-cortes** [comment]
> @david-cortes can you verify if this is still an issue? Running this on 0.8.1 doesn't produce any errors

From a quick experiment, seems to be working correctly with the latest duckdb.
