### ISSUE TITLE
different query results with optimizer on vs. off

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#3659]
#### What happens?
Working with @tiagokepe on ODBC driver in Windows. After running SQLite SqlLogicTests found a few queries that produced incorrect results:

```
SELECT pk FROM tab0 WHERE (col0 BETWEEN 67 AND 0 OR col0 > 17 AND (col0 > 3));
SELECT pk FROM tab0 WHERE 84 > col0 OR 8 > col0 ;
```

Disabling the optimizer gives the correct result. Also changing the order of the elements in the where clause can produce the correct result. See the attached sql script files for more details. 

#### To Reproduce
Attached are two SQL query script files. Open a CMD window and feed them to duckdb and each will generate an output txt file which are also attached.

```
duckdb < duckdb_issues_between.sql
duckdb < duckdb_issues_between.sql
```

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version:
```
┌─────────────────┬───────────┐
│ library_version │ source_id │
├─────────────────┼───────────┤
│ v0.3.5-dev164   │ e4ba94a4f │
└─────────────────┴───────────┘
```
 - DuckDB Client: command line

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
Yes.
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
Yes see attached .sql files. Note that I had to add .txt extension to upload to github. 

[duckdb_issues_between.sql.txt](https://github.com/duckdb/duckdb/files/8705268/duckdb_issues_between.sql.txt)
[duckdb_issues_comparison.sql.txt](https://github.com/duckdb/duckdb/files/8705269/duckdb_issues_comparison.sql.txt)
[between_issue.txt](https://github.com/duckdb/duckdb/files/8705283/between_issue.txt)
[comparison.txt](https://github.com/duckdb/duckdb/files/8705284/comparison.txt)

**Comment by lnkuiper** [comment]
Thanks for the detailed bug report.

I think this is an error with statistics propagation. In most cases we verify statistics in our tests, but in `column_binding_resolver.cpp:78`, we create a `BoundReferenceExpression`, without copying the `verification_stats` from the `BoundColumnRefExpression` over to it. This can let bugs with statistics propagation slip through.

**Comment by Mytherin** [comment]
Thanks for the report!

The statistics propagation here actually seems correct. The problem appears to be in the `OR` filter pushdown. I will have a look to see if I can fix it.
