### ISSUE TITLE
Binder Error: No function matches the given name and argument types '+(VARCHAR)'. 

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#3674]
#### What happens?
Been running subset of SQLite SqlLogicTests with DuckDB via ODBC and ran into the following. The .test file in particular can be found [here](https://www.sqlite.org/sqllogictest/file?name=test/index/random/100/slt_good_0.test&ci=tip). It is not an ODBC issue as it can be reproduced in the DuckDB command line (see below). 

I can't speak for if the SQL is a legit use case or not...only that other SQL engines (assuming at least SQLite, mySQL, Postgresql) handle it and produce a result. 

#### To Reproduce
I removed the `D` DuckDB prompt in the example below to make it easier to copy and paste into command line. 
```
v0.3.5-dev164 e4ba94a4f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
CREATE TABLE tab0(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
INSERT INTO tab0 VALUES(0,6315,4591.25,'bphbr',5710,9969.54,'ntqly');
SELECT ALL * FROM tab0 WHERE NOT + + col2 IS NOT NULL;
Error: Binder Error: No function matches the given name and argument types '+(VARCHAR)'. You might need to add explicit type casts.
        Candidate functions:
        +(TINYINT) -> TINYINT
        +(TINYINT, TINYINT) -> TINYINT
        +(SMALLINT) -> SMALLINT
        +(SMALLINT, SMALLINT) -> SMALLINT
        +(INTEGER) -> INTEGER
        +(INTEGER, INTEGER) -> INTEGER
        +(BIGINT) -> BIGINT
        +(BIGINT, BIGINT) -> BIGINT
        +(HUGEINT) -> HUGEINT
        +(HUGEINT, HUGEINT) -> HUGEINT
        +(FLOAT) -> FLOAT
        +(FLOAT, FLOAT) -> FLOAT
        +(DOUBLE) -> DOUBLE
        +(DOUBLE, DOUBLE) -> DOUBLE
        +(DECIMAL) -> DECIMAL
        +(DECIMAL, DECIMAL) -> DECIMAL
        +(UTINYINT) -> UTINYINT
        +(UTINYINT, UTINYINT) -> UTINYINT
        +(USMALLINT) -> USMALLINT
        +(USMALLINT, USMALLINT) -> USMALLINT
        +(UINTEGER) -> UINTEGER
        +(UINTEGER, UINTEGER) -> UINTEGER
        +(UBIGINT) -> UBIGINT
        +(UBIGINT, UBIGINT) -> UBIGINT
        +(DATE, INTEGER) -> DATE
        +(INTEGER, DATE) -> DATE
        +(INTERVAL, INTERVAL) -> INTERVAL
        +(DATE, INTERVAL) -> DATE
        +(INTERVAL, DATE) -> DATE
        +(TIME, INTERVAL) -> TIME
        +(INTERVAL, TIME) -> TIME
        +(TIMESTAMP, INTERVAL) -> TIMESTAMP
        +(INTERVAL, TIMESTAMP) -> TIMESTAMP
        +(TIME, DATE) -> TIMESTAMP
        +(DATE, TIME) -> TIMESTAMP
        +(ANY[], ANY[]) -> ANY[]
```
#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: v0.3.5-dev164 e4ba94a4f
 - DuckDB Client: commnand line app

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

I have been having a second look at the SQLLogicTests and encountered this as well. The problem is that the query is trying to do arithmetic on a string column.

It is not a bug - and it does not work in Postgres either:

```sql
CREATE TABLE tab0(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
INSERT INTO tab0 VALUES(0,6315,4591.25,'bphbr',5710,9969.54,'ntqly');
SELECT ALL * FROM tab0 WHERE NOT + + col2 IS NOT NULL;
-- ERROR:  operator does not exist: + text
-- LINE 1: SELECT ALL * FROM tab0 WHERE NOT + + col2 IS NOT NULL;
                                           ^
-- HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast.
```

It works in SQLite because columns are weakly typed and columns can be coerced into numerics. This is not desirable behavior for us to copy, so we will follow Postgres here and ignore the tests that trigger this behavior.

**Comment by bucweat** [comment]
Copy all and thanks for the explanation :-) Interestingly SQLite has recently added column typing I believe, but I haven't tried that out yet to see what the impact might be.
