### ISSUE TITLE
OR-Clause Pushdown Rework

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#3678]
#3675 has temporarily disabled the OR-clause pushdown because there were a number of issues with it. After inspecting the code there appears to be a lot of code duplication between the OR clause pushdown and the regular pushdown, which was the cause of this bug. The OR-clause pushdown should be reworked and cleaned up to unify the two code paths, and re-enabled.

**Comment by Mytherin** [comment]
This should still be implemented

**Comment by StLeoX** [comment]
watching
