### ISSUE TITLE
Latest release don't have OSX version

### ISSUE THREAD

**Issue by sahuguet** [duckdb/duckdb#3680]
#### What happens?
https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_cli-osx-universal.zip
lead to not found.

#### To Reproduce
See above.

#### Environment (please complete the following information):
v0.3.4

**Comment by Mytherin** [comment]
Thanks! Note that 0.3.3 and 0.3.4 are almost functionally identical, 0.3.4 was released only as a minor bug-fix release to fix missing Python builds. For now I would recommend just using [0.3.3](https://github.com/duckdb/duckdb/releases/download/v0.3.3/duckdb_cli-osx-universal.zip).

**Comment by maxcountryman** [comment]
@Mytherin since this was installed with Brew, there's no obvious way to downgrade to 0.3.3.

Without a new release or the existing release being fixed, this will be broken for the installation method.

**Comment by domoritz** [comment]
What's the reason that the parquet extension is not available? It also doesn't work in 0.4.

**Comment by carlopi** [comment]
Thanks for the report, I think this can be closed since CI has been improved since and latest version should have been correctly deployed.
