### ISSUE TITLE
CLI .import of CSV requires table to exist

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#3713]
#### What happens?
The CLI `.import` command will fail if the destination table does not already exist. This is different than the SQLite behavior which will create the table automatically. My assumption is that this is because DuckDB requires column typing while SQLite does not.

This is another issue I encountered during documentation for the CLI. There are definitely other (better!) ways to do imports, but there may be folks that prefer the CLI's import. If this is not easily fixed, I can certainly document it as is!

#### To Reproduce
```command
.mode csv
.output import_example.csv
SELECT 1 AS col_1, 2 AS col_2 UNION ALL SELECT 10 AS col1, 20 AS col_2;
.import import_example.csv test_table
Error: Catalog Error: Table with name test_table does not exist!
LINE 1: SELECT * FROM test_table
```
However, this will work. The `--skip 1` is needed to ignore column headers.:
```command
.mode csv
.output
create table test_table (col_1 int, col_2 int);
.import --skip 1 import_example.csv test_table
```

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.4
 - DuckDB Client: CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
The reason this doesn't work is because of one line in `shell.c`, line 17856
```c
 if( rc && sqlite3_strglob("no such table: *", sqlite3_errmsg(p->db))==0 ){
 ```
 
 It's looking for an error message containing "no such table: " while the received error message is
 "Error: Catalog Error: Table with name test_table does not exist!"

I've written a fix for this, changing this line to:
```c
    if( rc && sqlite3_strglob("Catalog Error: Table with name *", sqlite3_errmsg(p->db))==0 ){
```

But as you can see, that's still pretty hardcoded, which might break in the future
