### ISSUE TITLE
Compressed GZIP generated from a read_csv with an order by not matching original CSV

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#3714]
``` sql
statement ok
PRAGMA enable_verification

statement ok
CREATE TABLE csv_data AS (SELECT * FROM 'test/sql/copy/csv/data/real/voter.tsv' order by 1,37,64);

statement ok
COPY csv_data TO '__TEST_DIR__/voter.tsv.gz' (COMPRESSION GZIP);

statement ok
CREATE TABLE csv_data_gz AS (SELECT * FROM '__TEST_DIR__/voter.tsv.gz');

query I
SELECT COUNT(*) FROM (SELECT * FROM csv_data_gz EXCEPT SELECT * FROM csv_data)
----
0

statement ok
DROP TABLE csv_data;

statement ok
DROP TABLE csv_data_gz;
```

**Comment by Tishj** [comment]
The amount of columns in the order by clause doesn't seem to have anything to do with it  

the issue also triggers with:
`13,64`
`37,64`
the order of appearance does not matter either: `64,13` and 37,64` make no difference
The type of the columns doesn't seem to matter either  
looking at PRAGMA information about the table  

` cid │           name           │  type   │ notnull │ dflt_value │  pk   `  

13:  
`│ 12  │ name_sufx_cd             │ VARCHAR │ false   │            │ false │`  
37:  
`│ 36  │ area_cd                  │ INTEGER │ false   │            │ false │`

Other ranges around 64 also break (in combination with 13)
13 breaks with columns [52<->67]
order by 37 always breaks
