### ISSUE TITLE
Incorrect distinct with grouping sets

### ISSUE THREAD

**Issue by natehaze** [duckdb/duckdb#3722]
Love the idea of DuckDB, and how I can run queries against anything I have in memory easily.  Having a couple issues though.

I get different results between Postgres (fully believe to be correct) and DuckDB.  I've boiled it down to a relatively simple query.  I haven't gone through all permutations, but seems to be related to the `grouping sets` plus `count(distinct())`.

```
with df as (
    select * from (
        values
            (1, 1, 1),
            (1, 1, 1),
            (2, 3, 2)
        ) as a (iah_id, in_id, si_id)
    )
    select iah_id, si_id, count(distinct(iah_id)) as count
        from df
    	group by grouping sets (
    	    iah_id, si_id
    	);
```

Run above in Dbeaver or Python.

postgres results:
```
|iah_id|si_id |count|
|------|------|-----|
|1     |[NULL]|1    |
|2     |[NULL]|1    |
|[NULL]|1     |1    |
|[NULL]|2     |1    |
```

DuckDB results:
```
|iah_id|si_id |count|
|------|------|-----|
|1     |[NULL]|1    |
|2     |[NULL]|1    |
|[NULL]|1     |2    |
|[NULL]|2     |1    |
```

**Comment by Mytherin** [comment]
Thanks for the report!

This appears to be related to #3730, #3738 seems to fix the issue for me.

**Comment by Mytherin** [comment]
Should be fixed in the master now
