### ISSUE TITLE
Binder error raised when selecting fully-qualified column names in a view

### ISSUE THREAD

**Issue by AlexanderVR** [duckdb/duckdb#3724]
#### What happens?
A SELECT query that uses fully-qualified (with schema) column names when referencing a view will fail with a Binder Error.
The same SELECT query will succeed when referencing a table.

#### To Reproduce
```bash
> duckdb
v0.3.4 662041e2b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create schema s;
D create table s.a as select 'hello' as col1;
D create view s.b as select * from s.a;
D select s.a.col1 from s.a;
┌───────┐
│ col1  │
├───────┤
│ hello │
└───────┘
D select s.b.col1 from s.b;
Error: Binder Error: Referenced table "s" not found!
Candidate tables: "b"
LINE 1: select s.b.col1 from s.b;
               ^
D select b.col1 from s.b;
┌───────┐
│ col1  │
├───────┤
│ hello │
└───────┘
```

#### Environment (please complete the following information):
 - Mac OS 12.3.1
 - DuckDB Version: 0.3.4 and 0.3.5.dev617
 - DuckDB Client: CLI and Python

#### Before Submitting

- [X ] **Have you tried this on the latest `master` branch?**
Tested with python master
- [X ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
Hmm the issue is centralized in `binder.cpp:328`, the binding is found, but GetTableEntry returns nullptr because the View is bound as a Binding, not as a TableBinding.

So the first part does not get recognized as a schema, then after that it tries to see if the first part is a table instead, and there it throws the exception
