### ISSUE TITLE
Seeming network error when downloading a large file and converting it to parquet.

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#3731]
This fails pretty consistently for me almost always at different places in the stream.  I have no problem with the same file over 'wget'. I'm building a script that loads the imdb data set and converts it to parquet files. Makes for a nice example.
```
  install "httpfs";
  load "httpfs";
  copy (
    SELECT *
      REPLACE (
        str_split(primaryProfession,',') as primaryProfession,
        str_split(knownForTitles,',') as knownForTitles,
        case WHEN regexp_matches(deathYear,'[0-9]+') THEN CAST(deathYear as integer) END as deathYear,
        case WHEN regexp_matches(birthYear,'[0-9]+') THEN CAST(birthYear as integer) END as birthYear
      )
    FROM read_csv_auto('https://datasets.imdbws.com/name.basics.tsv.gz', delim='\t', quote='',header=True)
  ) to 'name_basics.parquet' (FORMAT 'parquet', CODEC 'ZSTD')
  ```

![image](https://user-images.githubusercontent.com/1093458/170786397-035d8eb4-ff95-4b6a-acea-9074bea7e2d5.png)

**Comment by hannes** [comment]
Entirely possible something's off there. We use httplib to read from https, which is a rather minimal client implementation. Maybe wget can retry something automatically? How big is the file?

**Comment by lloydtabb** [comment]
> How big is the file?

217 Megabytes.  It may be as simple as making the timeout value longer.  It seems to fail pretty quickly.

**Comment by hannes** [comment]
Maybe @samansmink can have a look?
