### ISSUE TITLE
Node: List aggregate function producing "Data type is not supported INTEGER[]"

### ISSUE THREAD

**Issue by jcuenod** [duckdb/duckdb#3735]
#### What happens?
I'm getting `Data type is not supported INTEGER[]` when I do a `list()` aggregate function from node.

#### To Reproduce
Create a db and fill with data:
```
CREATE TABLE test_table (
    int_col INTEGER,
    group_col TEXT
)
INSERT INTO test_table VALUES (1, 'a'), (2, 'a'), (3, 'b'), (4, 'b'), (5, 'c'), (6, 'c')
```

Query with `list`:
```
SELECT
    list(int_col) int_col_list
FROM
    test_table
GROUP BY
    group_col
```

Output is
> [Error: Data type is not supported INTEGER[]]

#### Environment (please complete the following information):
 - OS: Arch
 - DuckDB Version: 0.3.4
 - DuckDB Client: Node

#### Before Submitting
I have only tested using the node client.

**Comment by hannes** [comment]
There is an open PR #3618 that should resolve this

**Comment by omo** [comment]
(Unsolicited triage) Maybe we can close this as #3618 was merged a while back.
