### ISSUE TITLE
Should this query be utilizing parallel threads?

### ISSUE THREAD

**Issue by ljmartin** [duckdb/duckdb#3737]
#### What happens?
Hi DuckDB,
I'm fetching about a million rows from a database of a few billion, which is chunked into many parquet files. The desired 1 million rows have a unique identifier (`idnum`) so I ran an inner join operation, which appears to be running single-threaded according to htop. Other operations appear to run in parallel threads - I guess parallelizing over the chunks. Can join operations like this be parallel? 

Thanks

#### To Reproduce
```python
import duckdb 
con = duckdb.connect()
#create view into 1 million desired idnums:
cursor.execute(f"create view v1 as select * from read_parquet('./desired_idnums/*')")
#inner join with the big table of billions, using idnum as the key:
rows = cursor.execute(f"select * from read_parquet('./big_db/chunks/*'), v1 where read_parquet.idnum = v1.idnum").fetchall()
```

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04.2 LTS
 - DuckDB Version: 0.3.4
 - DuckDB Client: Python

**Comment by Mytherin** [comment]
Yes, this query can be executed in parallel. See #2260 and #3700, this should already work as-is on the master branch. You can force parallelism on the current release by pushing an `ORDER BY ALL` after the query.

**Comment by ljmartin** [comment]
@Mytherin thanks mate, that works - it went from about 30 minutes to <5 seconds with 96 cpus.
