### ISSUE TITLE
Node bindings crash when accessing nonexistent parquet file over httpfs

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#3743]
#### What happens?
The node duckdb bindings (v0.3.4) crash the node process when you try to access a nonexistent parquet file using httpfs. No exception is thrown in javascript—the process just crashes outright. I expect an exception I can deal with in my code.

This outcome is especially bad for node's evented model, because the process is almost certainly doing something for another user—crashing the process causes errors for *every* request being processed concurrently.

#### To Reproduce
Here's a minimal test case:

``` javascript
const duckdb = require('duckdb');
var db = new duckdb.Database(':memory:');

db.exec(`INSTALL httpfs`)
db.exec(`LOAD httpfs`)
try {
  db.exec(`CREATE VIEW foo AS SELECT * FROM parquet_scan('https://duckdb.org/404.parquet')`)
} catch (e) {
  console.log('caught!', e)
}
```

```
$ node index.js
libc++abi: terminating with uncaught exception of type duckdb::InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Unable to connect to URL "https://duckdb.org/404.parquet": 404 (Not Found)
zsh: abort      node index.js
```

#### Environment (please complete the following information):
 - OS: Mac OS 12.4
 - DuckDB Version: 0.3.4
 - DuckDB Client: node

**Comment by hannes** [comment]
We are probably missing a try/catch somewhere in C++ code, thanks for the bug report

**Comment by zenazn** [comment]
Perhaps you can include an example of that on https://duckdb.org/docs/api/nodejs? I've had to source-dive the NAPI code to write our internal typescript definitions for duckdb, and I apparently got it wrong! 😬 

(as an aside, we've found the node bindings really difficult to use. if you're interested, I can send you a doc with some feedback on them!)

**Comment by Mause** [comment]
@zenazn that would be really great to see, as we're looking to focus on improving our client libraries
