### ISSUE TITLE
Node.js: When using `each()`, how to know when all rows have been read?

### ISSUE THREAD

**Issue by davidtheclark** [duckdb/duckdb#3754]
I'm using the Node.js SDK v0.3.3.

I need to know when `each()` has finished processing all the result rows. Right now, as far as I can tell, there is no indication: the callback just stops being called. This severely limits the usefulness of `each()`, because I can't tell my program to do something *after* `each()` is finished.

Looking at `statement.cpp` it seems like I'm supposed to be able to provide a `complete` callback. But I can't figure out how. If I pass a function as a third argument to `each()`, it never seems to get called.

Can you give an example of how to use `each()` and know when iteration is complete? If not, this is a feature request for that functionality.

**Comment by davidtheclark** [comment]
I tried looking in the tests, and I see [the test for the `complete` comment is commented out](https://github.com/duckdb/duckdb/blob/360aedc4f35d9d0cb09caba5961bfc493d8f7fb1/tools/nodejs/test/each.test.js#L25-L38), so maybe the intended functionality doesn't currently work.

**Comment by Mause** [comment]
@davidtheclark are you able to confirm if https://github.com/duckdb/duckdb/pull/4179 fulfils this requirement?

**Comment by davidtheclark** [comment]
Yes! Excited for the release.
