### ISSUE TITLE
Node.js: Unhandled "data type not supported" exception on `SELECT` with `TIMESTAMPTZ` column

### ISSUE THREAD

**Issue by davidtheclark** [duckdb/duckdb#3759]
#### What happens?
If I create a table with a `TIMESTAMPTZ` column, then try to `SELECT` that column, an exception occurs that seems to be unhandled by Node.js so is probably direct from the native code.

This seems like two bugs in one:
- The error isn't handled correctly.
- `TIMESTAMPTZ` isn't usable right now.

#### To Reproduce

```js
duckdb.all('CREATE TABLE test(dt TIMESTAMPTZ)', (err, result) => {
  if (err) {
    console.error('create: ' + err);
    return;
  }
  duckdb.all(`INSERT INTO test VALUES ('2021-01-01T00:00:00Z')`, (err, result) => {
    if (err) {
      console.error('insert: ' + err);
      return;
    }
    duckdb.all('SELECT dt FROM test', (err, result) => {
      if (err) {
        console.error('select: ' + err);
        return;
      }
      console.log(result);
    });
  });
});
```

I get the following output:

```
undefined:0


[Error: Data type is not supported TIMESTAMP WITH TIME ZONE]
```

So none of the callbacks provided an `err` argument.

If I change the type from `TIMESTAMPTZ` to `TIMESTAMP`, the code works and the result is logged (`[ { dt: 2021-01-01T00:00:00.000Z } ]`).

#### Environment (please complete the following information):
 - OS: macOS 12.4
 - DuckDB Version: 0.3.3
 - DuckDB Client: Node.js

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed by #3765. Feel free to re-open if the issue persists.
