### ISSUE TITLE
DBeaver: Serialization Error: Attempting to read a required field, but field is missing

### ISSUE THREAD

**Issue by 8513421** [duckdb/duckdb#3762]
I recently discovered DuckDB. I installed the latest version etc. I installed the latest DBeaver because I wanted to generate an ER diagram. 

Following the tutorial, I created a simple database (mybase.duckdb) and stored the "items" table in it. 

I started DBeaver, followed the instructions to connect to the database DuckDB, installed the driver (version 0.3.3). Unfortunately when I click on "test connection" I get an error: Serialization Error: Attempting to read a required field, but field is missing. 

Is this a driver error or am I doing something wrong? 

Thanks.

**Comment by 8513421** [comment]
Sorry, I forgot to write! I use python api. 

import duckdb

# to use a database file (shared between processes)
con = duckdb.connect(database="db.duckdb", read_only=False)
# create a table
con.execute("CREATE TABLE items(item VARCHAR, value DECIMAL(10,2), count INTEGER)")
# insert two items into the table
con.execute("INSERT INTO items VALUES ('jeans', 20.0, 1), ('hammer', 42.2, 2)")
con.close()

**Comment by Alex-Monahan** [comment]
Thanks! And which version of the Python client? The versions used by Python and DBeaver should match (although 0.3.4 and 0.3.3 should be compatible)

**Comment by Mytherin** [comment]
This error generally means you are trying to open a DuckDB file created with an older version (<0.3.3) using a newer DuckDB version (>=0.3.3)

**Comment by 8513421** [comment]
That's strange. I have installed the latest version... How to solve it?

**Comment by Mause** [comment]
@8513421 which version of the jdbc driver are you using? It's probably the 0.4.0 version if you just installed it from Maven Central

**Comment by 8513421** [comment]
> 

I don't know how to check the versions of this driver.

**Comment by Mause** [comment]
@8513421 are you able to retest this with the latest version (0.5.1) from Maven central?

**Comment by Mause** [comment]
Given we haven't had a response, I'm going to assume this has been resolved
