### ISSUE TITLE
Unable to install duckdb: package ‘duckdb’ is not available (for R version 3.3.3)

### ISSUE THREAD

**Issue by psomdeb25** [duckdb/duckdb#3766]
#### What happens?
I need to install the starwarsdb on R.  Duckdb is a missing dependency, according to the message.  I attempted to install duckdb using the command, but received the following error:

`install.packages("duckdb")`

> Warning in install.packages: 
package ‘duckdb’ is not available (for R version 3.3.3)

Therefore, I updated my RStudio. My current version of Rstudio is
> RStudio
2022.02.3 Build 492

However, duckdb still does not install and I am presented with the same warning message as above.

#### Environment (please complete the following information):
 - OS: macOS 12.0.1 
 - DuckDB Version: N.A
 - DuckDB Client: N.A

#### Before Submitting

- [X ] **Have you tried this on the latest `master` branch?**
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`

I tried the above step. But I am presented with the error as below:

downloaded 0 bytes
Warning in install.packages : 
downloaded` length 0 != reported length 9
Warning in install.packages : 
URL 'https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz': status was '404 Not Found'
Error in download.file(p, destfile, method, mode = "wb", ...) : 
cannot download all files

Edit: I saw another post by an user @david-cortes. Their issue was as follows:
Installation instructions for the R master branch point to a non-existing file

**Comment by rsund** [comment]
Your R version (0.3.3) is really old as the current version seems to be 4.2.0. Try updating R - note that updating RStudio GUI won't update actual R. After that install.packages("duckdb") will work. If you need newer (development) version of DuckDB, check [https://rsund.r-universe.dev/ui#package:duckdb](https://rsund.r-universe.dev/ui#package:duckdb)

**Comment by psomdeb25** [comment]
Thank you @rsund the problem was resolved!!! I assumed that when I upgraded RStudio, R would be updated as well. However, I downloaded a fresh version of R from the CRAN database and reinstalled it. Now the duckdb is installed perfectly!
