### ISSUE TITLE
memory limit on Windows 10 at 2.1Gb?

### ISSUE THREAD

**Issue by enningb** [duckdb/duckdb#3773]
I have a bunch of parquet-files which I import a duckdb. Everything goes smooth until the duckdb file reaches a size of a little less than 2.1Gb. Then I get an error:

    Catalog Error: Table with name <name of table> does not exist!

I'm on Windows 10, NTFS filesystem, 16Gb RAM. The duckdb_settings says max_memory is at 13.8 Gb.

On my Mac this size limit does not seem to exist. Does anyone have a suggestion on what might be wrong?

**Comment by hannes** [comment]
Is this a 32 bit system?

**Comment by enningb** [comment]
It says 'x64-based PC'

**Comment by hannes** [comment]
Okay, can you then please try to make a reproducible example? Is there a reason you ignored the issue template?

**Comment by djouallah** [comment]
I think it is the same issue as mine
https://github.com/duckdb/duckdb/issues/3438

**Comment by enningb** [comment]
Yes I think you're right. Closing this issue (if I can)
