### ISSUE TITLE
Specialize LIST aggregate function implementation

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#3788]
Currently the `LIST` aggregate function only has a generic implementation that uses a `Vector` to aggregate data. While this works in all cases, there is an opportunity to optimize this for lists of primitive types (e.g. numerics or strings). As the Vector itself holds a lot of extra data (`VectorType`, `LogicalType`, several buffers, a pointer to the data) which could be replaced with a simpler/more minimal structure. This is particularly relevant in the case of many very small lists.

We could even envision inlining simpler primitives into the actual hash table, instead of requiring a separate allocated storage area, e.g. for int32 you could envision a structure like this which would allow inlining up to 2 entries in the hash table:

```cpp
struct list_data_t {
  uint32_t length;
  union {
    struct {
      uint32_t capacity;
      data_ptr_t pointer;
    } pointer;
    struct {
      bool is_null[2];
      int32_t entries[2];
    } inlined;
  } value;
}
```

**Comment by Mytherin** [comment]
While working on the `ColumnDataCollection` I have been thinking about how to apply it to the `LIST` aggregate. After consideration, I feel that we cannot re-use the ColumnDataCollection as-is here, since it is again not optimized for holding extremely small chunks of data. But we can use several of the implementation ideas I used there for this aggregate as well.

Here is my idea for how this aggregate could be structured.

## Data Structures

The data that is in the hash table looks like this (16 bytes):

```cpp
struct linked_list_t {
  list_vector_data_t *first_segment;
  list_vector_data_t *last_segment;
};

struct list_ht_data_t {
  linked_list_t data;
};
```

The segments point to structs of the following shape:

```cpp
struct list_vector_data_t {
  uint16_t count;
  uint16_t capacity;
  list_vector_data_t *next;
  bool is_null[capacity];
  union {
    struct {
      T values[capacity];
    } primitive_data;
    struct {
      linked_list_t child;
      T list_offsets[capacity];
    } list_data;
    struct {
      list_vector_data_t *children[child_count];
    } struct_data;
  }
};
```

The `list_vector_data_t` functions as a linked list of structures. On the top-level we have both a pointer to the first and last segments of the linked list. The last segment is used for appending (construction). The first segment is used for traversing the list in the final scan.

The `list_vector_data_t` has a child-element that is itself a linked list (in case of a LIST type), and child elements that are `list_vector_data_t` (in case of a STRUCT type). This allows for the recursive behavior that is required to model arbitrarily complex nested types in an efficient manner (1) without over-allocating in the case of many small lists, (2) without requiring a full copy when appended past the capacity, and (3) while allowing a Combine method that does not require a copy of the internals of the lists. This should make the structure efficient for both small and large lists. 


## Appending

While appending, `list_vector_data_t` entries are allocated in contiguous regions of an extra heap in the hash table. I would start off by allocating this using e.g. the StringHeap class, but we can move to using buffer managed blocks and off-loading the blocks by turning the pointers into block_id + offset combinations later on.

The overhead of the structure itself is 12 bytes (2x uint16 + next pointer) per vector. At the root-level, we can start off by allocating a `list_vector_data_t` structure of capacity 4, then 8, then 16, etc.

Appending works row-by-row, but should be templated on a **per-type** basis. What that means is if we have a complex structure (e.g. `STRUCT(VARCHAR, INT[])`) we should first insert the `STRUCT`, then the `VARCHAR`, then the `LIST`, then the `INT`. This way we can avoid per-value function-call overhead.

## Example
Let's say we have the following structure and values:

```sql
STRUCT(INT[], VARCHAR, STRUCT(DOUBLE, DOUBLE))

{'a': [1, 2, 3], 'b': 'hello'}
{'a': [4, 5], 'b': NULL}
NULL
{'a': [6, NULL, 8, 9], 'b': 'world'}
```

The root-level entry will be a struct:

```cpp
// root: struct
#0 -> {
  uint16_t count = 4;
  uint16_t capacity = 4;
  list_vector_data_t *next = NULL;
  bool is_null[4] = { false, false, true, false };
  list_vector_data_t *children[2] = { #1, #2 };
};

// child 1: list
#1 -> {
  uint16_t count = 4;
  uint16_t capacity = 4;
  list_vector_data_t *next = NULL;
  bool is_null[4] = { false, false, true, false };
  linked_list_t child { first = #3, last = #4 };
  list_entry_t list_offsets[4] = { {0, 3}, {3, 2}, _, {5, 4} };  
}

// child 2: varchar
#2 -> {
  uint16_t count = 4;
  uint16_t capacity = 4;
  list_vector_data_t *next = NULL;
  bool is_null[4] = { false, true, true, false };
  string_t values[4] = { "hello", _, _, "world" };  
}

// child of list: int (1/2)
#3 -> {
  uint16_t count = 4;
  uint16_t capacity = 4;
  list_vector_data_t *next = #4;
  bool is_null[4] = { false, false, false, false };
  int32_t values[4] = { 1, 2, 3, 4 }
}

// child of list: int (2/2)
#4 -> {
  uint16_t count = 4;
  uint16_t capacity = 8;
  list_vector_data_t *next = NULL;
  bool is_null[8] = { false, false, true, false, false, _, _, _ };
  int32_t values[8] = { 5, 6, _, 8, 9, _, _, _ }
}

```

**Comment by taniabogatsch** [comment]
There are two more things that I want to do here before closing the issue, mainly because I am currently profiling other queries and see some potential for performance.

- [ ] Only copy the linked list in the states for windows, move it otherwise (`ListCombineFunction`).
- [ ] Possibly use arena allocation for LIST aggregates. Hash table can own the data, if think that I started looking into this, there is a stale branch (arena-allocator) on my fork.
