### ISSUE TITLE
Undefined type for Appender::Append!

### ISSUE THREAD

**Issue by liulover5** [duckdb/duckdb#3793]
#### What happens?
When I run c++ code by Appender, throw duckdb::Exception:  Undefined type for Appender::Append!

#### To Reproduce

source:

```cpp

#include "duckdb.hpp"

#include <iostream>
#include <ctime>
#include<iomanip>

using namespace duckdb;

int main() {
    DuckDB db(nullptr);
    Connection con(db);

    std::cout << "LibraryVersion:" << db.LibraryVersion() << std::endl;
    std::cout << "NumberOfThreads:" << db.NumberOfThreads() << std::endl;
    std::cout << "SourceID:" << db.SourceID() << std::endl;
//    std::cout << "temporary_directory:" << db.config.temporary_directory << std::endl;
//    std::cout << "maximum_memory:" << db.config.maximum_memory << std::endl;

    con.Query("CREATE TABLE people(id INTEGER, name VARCHAR)");
// initialize the appender
    Appender appender(con, "people");

    appender.AppendRow(1, "Mark");
    appender.Flush();

}
```

building and linking with libduckdb 0.3.4 release bin.

output:

```
terminate called after throwing an instance of 'duckdb::Exception'
  what():  Undefined type for Appender::Append!

进程已结束，退出代码 134 (interrupted by signal 6: SIGABRT)
```

I find this source code in duckdb.h:

```

class Appender : public BaseAppender {
...
}

class BaseAppender {
...
	// Append functions
	template <class T>
	void Append(T value) {
		throw Exception("Undefined type for Appender::Append!");
	}
}

```

#### Environment (please complete the following information):
 - OS: linux mint 19.3
 - DuckDB Version: 0.3.4 release
 - DuckDB Client: NA

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
I can not seem to reproduce your issue, I've recreated your test as a testcase in `test_appender_api.cpp` and ran it with the unittest (so the environments aren't entirely the same)

```cpp
TEST_CASE("Test appending a row with multiple columns", "[api]") {
	DuckDB db(nullptr);
	Connection con(db);
	unique_ptr<QueryResult> result;
	// create the table
	REQUIRE_NO_FAIL(con.Query("CREATE TABLE people(id INTEGER, name VARCHAR)"));
	Appender appender(con, "people");

	appender.AppendRow(1, "Mark");
	appender.Flush();

	result = con.Query("SELECT * FROM people");
	REQUIRE(CHECK_COLUMN(result, 0, {1}));
	REQUIRE(CHECK_COLUMN(result, 1, {"Mark"}));

	appender.AppendRow(2, "Hannes");
	appender.Flush();

	result = con.Query("SELECT * FROM people");
	REQUIRE(CHECK_COLUMN(result, 0, {1, 2}));
	REQUIRE(CHECK_COLUMN(result, 1, {"Mark", "Hannes"}));
}
```
This test passes, I'll try to have a go at running this through the same environment as you

**Comment by Tishj** [comment]
I've compiled libduckdb from source (existing binary is not compatible with my machine)

Downloaded it from: https://github.com/duckdb/duckdb/releases/download/v0.3.2/libduckdb-src.zip
(I've used 0.3.2 because that's the last working binary download)
compiled it using:
`g++ -fPIC duckdb.cpp -std=c++11 -c && g++ -std=c++11 duckdb.o -dynamiclib -o libduckdb.dylib`

Copied your code and compiled it against the binary:
`g++ -I . tests/appendrow_bug.cpp -std=c++11 -lduckdb -L. -o appender_bug_test`

./appender_bug_test produces no errors, and completes successfully

**Comment by Tishj** [comment]
Any update on this?
