### ISSUE TITLE
Installation problem for macOS CLI binary v0.3.4

### ISSUE THREAD

**Issue by nsgrantham** [duckdb/duckdb#3794]
The installation instructions at https://duckdb.org/docs/installation/?environment=cli for macOS suggest https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_cli-osx-universal.zip but this file is not found.

**Comment by Alex-Monahan** [comment]
Please use version 0.3.3 - it is essentially identical!

https://github.com/duckdb/duckdb/releases/download/v0.3.3/duckdb_cli-osx-universal.zip

**Comment by hannes** [comment]
I also uploaded 0.3.4 binaries

**Comment by nsgrantham** [comment]
Thanks @Alex-Monahan and @hannes, the link is working now that you've uploaded the 0.3.4 binaries. 🦆
