### ISSUE TITLE
Complex data types used by extensions not supported in ODBC

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#3801]
#### What happens?
Now that extension loading has been fixed in ODBC (thanks to folks who did that), I've been playing around with extensions again. Basic setup is Windows 11 using VBScript/ADO to talk to DuckDB via ODBC. 

ICU (as described [[here](https://duckdb.org/2022/01/06/time-zones.html)](https://duckdb.org/2022/01/06/time-zones.html)) works as described on that page. JSON (as described [[here](https://duckdb.org/docs/extensions/json)](https://duckdb.org/docs/extensions/json)) loads, but some of the queries from the examples on the website do not work. Specifically, these do not work:

```
SELECT json(j) FROM example;
SELECT json_type(j) FROM example;
SELECT json_structure(j) FROM example;
SELECT json_structure('["duck",{"family":"anatidae"}]');
```
Looks like the extension creates a new datatype 'JSON' which it appears ODBC doesn't know about. From ODBC trace (attached), SQLDescribeCol returns all 0's. Looking at FindRelatedSQLType() method which determines the datatype, it turns out types are hard coded to known DuckDB datatypes only. Talking with @tiagokepe, he mentioned that complex data types (like JSON, struct, list) are not currently supported by the ODBC driver. He asked me to submit an issue so that it is documented and can be further discussed.

#### To Reproduce
Reproduce the examples from the JSON webpage mentioned above using ODBC.

#### Environment (please complete the following information):
 - OS: Windows 11
 - DuckDB Version: v0.3.5-dev971 dbb043b11
 - DuckDB Client: VBScript/ADO via ODBC 

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
Yes built locally with VS2019.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

[odbc.txt](https://github.com/duckdb/duckdb/files/8861632/odbc.txt)

**Comment by Mytherin** [comment]
If there is no support in ODBC for these types then returning and converting to `VARCHAR` sounds good to me.

**Comment by bucweat** [comment]
I just gave sqlite_scanner a  try via ODBC in Windows 11 via ADO/VBScript, and I ran into an issue that I've seen before that was mentioned in this github issue. Here is the SQL code I ran, which should be very easy to reproduce:
```
INSTALL 'sqlite_scanner';
LOAD 'sqlite_scanner';
select * From duckdb_extensions();
DROP VIEW IF EXISTS customer;
CALL sqlite_attach('sakila.db');
select type, name from sqlite_master;
select * from customer;
```
The above fails when it gets to `select * From duckdb_extensions();`. The schema for the table returned by `duckdb_extensions()` includes a field `aliases` which is of type LIST (see '...\duckdb\src\include\duckdb\common\types.hpp'). LIST is not currently supported in the ODBC driver code, however, minimal support can be added by adding the following to `FindRelatedSQLType()` method located in [`...\duckdb\tools\odbc\api_info.cpp`](https://github.com/duckdb/duckdb/blob/master/tools/odbc/api_info.cpp#L246) before the `default:`:
```
	case LogicalTypeId::LIST:
		return SQL_VARCHAR;
```
Once that change is added, then the query works and returns (this is the csv formatted output from my script):
```
extension_name(adVarChar 200 ),loaded(adChar 129 ),installed(adChar 129 ),install_path(adVarChar 200 ),description(adVarChar 200 ),aliases(adVarChar 200 )
excel,t,NULL,,,[]
fts,t,t,(BUILT-IN),Adds support for Full-Text Search Indexes,[]
httpfs,f,f,,Adds support for reading and writing files over a HTTP(S) connection,[http, https, s3]
icu,t,t,(BUILT-IN),Adds support for time zones and collations using the ICU library,[]
inet,f,f,,Adds support for IP-related data types and functions,[]
jemalloc,f,f,,Overwrites system allocator with JEMalloc,[]
json,t,t,(BUILT-IN),Adds support for JSON operations,[]
parquet,t,t,(BUILT-IN),Adds support for reading and writing parquet files,[]
postgres_scanner,f,f,,Adds support for reading from a Postgres database,[postgres]
sqlite_scanner,t,t,C:\Users\charlie\.duckdb\extensions\v0.6.0\windows_amd64\sqlite_scanner.duckdb_extension,Adds support for reading SQLite database files,[sqlite, sqlite3]
tpcds,t,t,(BUILT-IN),Adds TPC-DS data generation and query support,[]
tpch,t,t,(BUILT-IN),Adds TPC-H data generation and query support,[]
```
Note the `aliases` column is returned now as `varchar` and uses brackets `[]` to describe the list values. The rest of the SQL mentioned above also works just fine.

The reason I bring this up is, in previous comment above from @tiagokepe, he mentioned returning `SQL_VARCHAR` for complex types, which at least in this case works perfectly.  However, it seems that change never made it into the ODBC driver code, and maybe explains why this issue is still open. Is a `varchar` solution something that would be considered? 

Also related is #4887 which describes missing support for DECIMAL...
