### ISSUE TITLE
Insert lists from dataframe

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#3808]
#### What happens?

Feature request, It would be convenient to insert lists into tables directly from Pandas dataframes. This yields a `RuntimeError: Conversion Error: Conversion Error: Unimplemented type for cast (VARCHAR -> VARCHAR[])` right now, but is can be worked around by converting the list to a delimited string in python and splitting with string_split in duckdb (suggested by Alex on discord), or by creating a temporary table from the dataframe and inserting from that.

#### To Reproduce

```python
import pandas as pd
import duckdb; 
df = pd.DataFrame.from_dict({'xs':[["foo","bar"], ["baz"]]})
con = duckdb.connect(':memory:')
con.execute("CREATE TABLE test (xs TEXT[])")
con.execute("INSERT INTO test SELECT * FROM df").df()
```
#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.5.dev992
 - DuckDB Client: Python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
I might be way off, but are you sure this is inserting the df, and not just the text "df" ?

I thought the query needed a `fetch/fetchall()` to get access to the variable `df` this way?

**Comment by Alex-Monahan** [comment]
> I might be way off, but are you sure this is inserting the df, and not just the text "df" ?
> 
> I thought the query needed a `fetchone/fetchall()` to get access to the variable `df` this way?

Hello!

Their query is correct!

.fetchall() or .df() are just changing the types of objects (Python objects vs. a Pandas df) that are returned from the query and don't impact the query itself.

**Comment by Tishj** [comment]
Ah I learned something, and I stand corrected :)

**Comment by eaubin** [comment]
Duplicate of https://github.com/duckdb/duckdb/issues/2450
