### ISSUE TITLE
Timestamp parquet roundtrip issue

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#3816]
#### What happens?
When roundtripping from duckdb<-parquet->pandas the timestamp information gets messed up

#### To Reproduce
The `tools/pythonpkg/tests/fast/arrow/parquet_write_roundtrip.py` test `test_roundtrip_timestamp` fails on line 74
`(date_time_list, 'datetime64[ns]', 'TIMESTAMP_NS')`

This type comes into pandas as `datetime64[ns]`, then gets send to duckdb, where we write it to parquet
but when it comes back into pandas the dtype is `datetime64[ns, UTC]`.

This causes this difference:
Input:
```
                  val
0 2018-03-10 11:17:54
1 1900-12-12 23:48:42
2                 NaT
3 1992-07-09 07:05:33
```

Output:
```
                        val
0 2018-03-10 11:17:54+00:00
1 1900-12-12 23:48:42+00:00
2                       NaT
3 1992-07-09 07:05:33+00:00
```

I've narrowed the issue down to line 165 in `parquet_writer.cpp`
`schema_ele.logicalType.TIMESTAMP.isAdjustedToUTC = true;`
Setting this to false fixes this issue, but I don't understand the intricacies of timestamps well enough to know what effect this change will have.

#### Environment (please complete the following information):
 - OS: [MacOS]
 - DuckDB Version: [master:latest]
 - DuckDB Client: [pytest/python]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
That wounds correct but I don't think I was building and testing correctly.  I think the line should probably read

```cpp
		schema_ele.logicalType.TIMESTAMP.isAdjustedToUTC = (duckdb_type.id() == LogicalTypeId::TIMESTAMP_TZ);
```
