### ISSUE TITLE
install parquet; not working -> 404

### ISSUE THREAD

**Issue by bmmeijers** [duckdb/duckdb#3819]
#### What happens?

When trying to install parquet support on a freshly compiled duckdb instance (either git master or tag v.0.3.4)

install parquet;

It does not work:
Error: IO Error: Failed to download extension http://extensions.duckdb.org/662041e2b/linux_amd64/parquet.duckdb_extension.gz
Visiting the page with a web browser leads to a 404 error.

#### To Reproduce
Clone repository, compile, start ./duckdb, type "install parquet;"

#### Environment (please complete the following information):
 - OS: Linux x86_64
 - DuckDB Version: master / v0.3.4
 - DuckDB Client: cli

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by bmmeijers** [comment]
I am trying to access a local parquet file from SQL, but it says: 

D select count(*) from 'test.parquet';
Error: Catalog Error: Table with name test.parquet does not exist!

**Comment by Mytherin** [comment]
Did you run `make` to compile DuckDB, or did you manually run `cmake` without specifying `-DBUILD_PARQUET_EXTENSION=true`?

**Comment by bmmeijers** [comment]
the latter :-( sorry for the noise

**Comment by Mytherin** [comment]
No worries. Perhaps we should consider distributing the parquet extension as an installable extension after all.
