### ISSUE TITLE
Setting default_collation=NOCASE modifies values of GROUP BY queries

### ISSUE THREAD

**Issue by holdenmatt** [duckdb/duckdb#3821]
#### What happens?
Changing the default collation to "NOCASE" unexpectedly lowercases all values when a query includes a "GROUP BY" clause.

Mytherin suggested in Discord this was not intentional and asked me to file a bug.

#### To Reproduce

```sql
PRAGMA default_collation=NOCASE
CREATE TABLE t AS (SELECT 'hello' AS x UNION ALL SELECT 'WORLD' AS x);
SELECT x FROM t GROUP BY 1;
```

```text
┌─────────┐
│    x    │
│ varchar │
├─────────┤
│ world   │
│ hello   │
└─────────┘
```
Result: all values are lowercased.
Expected: casing of values returned is unchanged.

I ran into this because I want to use case-insensitive string sorting. default_collation=NOCASE would do what I want, but can't be used since it modifies values (seemingly only when a query includes a GROUP BY).

For now, I'm using `ORDER BY lower($column)` as a workaround, but that's undesirable as it needs to be included with every ORDER BY query vs just setting a global PRAGMA.

#### Environment (please complete the following information):
 - OS: OS X or browser Wasm
 - DuckDB Version: @duckdb/duckdb-wasm 1.14.4
 - DuckDB Client: duckdb-wasm

**Comment by meitham** [comment]
I see the same issue with ``duckdb==0.7.1`` in python.

**Comment by meitham** [comment]
This issue still exists as of version 0.8.1 so please don't close

**Comment by szarnyasg** [comment]
@meitham good point, thanks for bringing this to our attention. I edited @holdenmatt 's original script for slightly easier reproduction. We'll take a look.
