### ISSUE TITLE
Path name for OSX CLI install is incorrect

### ISSUE THREAD

**Issue by tdunning** [duckdb/duckdb#3823]
#### What happens?
The path name on the web site for the OSX CLI version is incorrect. It refers to an `amd64` architecture whereas the actual artifact has `universal` architecture

#### To Reproduce
Try to download the specified link:
```
https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_cli-osx-amd64.zip
```
You get a 404.

Try this instead:
```
https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_cli-osx-universal.zip
```
Works

#### Environment (please complete the following information):
 - OS: OSX
 - DuckDB Version: 3.4
 - DuckDB Client: CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

Doesn't really apply

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yes. Exactly.

**Comment by tdunning** [comment]
This is related to #3680

**Comment by hannes** [comment]
Thanks for spotting, should be fixed
