### ISSUE TITLE
brew formula doesn't support parquet

### ISSUE THREAD

**Issue by tdunning** [duckdb/duckdb#3825]
#### What happens?
When I install duckdb using brew, parquet support seems to be missing.

#### To Reproduce
```
$ brew install duckdb
$ duckdb
v0.3.4 662041e2b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D PRAGMA version;
┌─────────────────┬───────────┐
│ library_version │ source_id │
├─────────────────┼───────────┤
│ v0.3.4          │ 662041e2b │
└─────────────────┴───────────┘
D select count(1) from './t3-zstd.parquet';
Error: Catalog Error: Table with name ./t3-zstd.parquet does not exist!
LINE 1: select count(1) from './t3-zstd.parquet';
                             ^
D select count(*) from 'xy.csv';
┌──────────────┐
│ count_star() │
├──────────────┤
│ 2500         │
└──────────────┘
D 
```

#### Environment (please complete the following information):
macOS 11.6.2 
 - DuckDB Version: [e.g. 22]
0.3.4 (and likely others, but it doesn't appear possible to load old versions from brew)
 - DuckDB Client: [e.g. Python]
CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.
This is specific the brew installation of the CLI version

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

I have repeated this. It might conceivably be related to the problem that we saw in the Julia package:
https://github.com/kimmolinna/DuckDB.jl/issues/6

That is why I included the PRAGMA output.

**Comment by hannes** [comment]
The parquet reader will be an installable extension from the next version. Also we don't maintain that formula.

**Comment by carlopi** [comment]
Recents homebrew packages comes with parquet extension. Thanks for the report.
