### ISSUE TITLE
s3fs decodes key urls incorrectly

### ISSUE THREAD

**Issue by drorspei** [duckdb/duckdb#3830]
#### What happens?
Sometimes keys returned from s3 api need decoding, for example spaces are encoded as '+', so '+' must be decoded as space.
Since they are not decoded correctly, we get a 404 when trying to read the undecoded path .

#### To Reproduce
Parquet scan for a file on s3 with a space in its prefix.

#### Environment (please complete the following information):
All environments.

**Comment by hannes** [comment]
Can you try to make a reproducible example please?

**Comment by drorspei** [comment]
Hej, yes of course!
Here is a failing query:
`select count(*) from parquet_scan('s3://nyc-tlc/trip data/yellow_tripdata_2021-1*.parquet`

There is a matching file in the open access nyc-tlc bucket, but "trip data" becomes "trip+data" in the s3 api response.
There are also 2 added test cases in #3831 .

**Comment by hannes** [comment]
This should be fixed now, right?

**Comment by drorspei** [comment]
Yes! Thanks ^_^
