### ISSUE TITLE
http_proxy and https_proxy env vars are ignored when installing extensions. 

### ISSUE THREAD

**Issue by JorgeGarciaIrazabal** [duckdb/duckdb#3836]
#### What happens?
I am trying to install the httpfs extension executing `INSTALL 'httpfs';` using a proxy, but setting the environment variables do not work.

Note: Using python request library to download the extension works for me:
```
 r=requests.get("http://extensions.duckdb.org/662041e2b/linux_amd64/httpfs.duckdb_extension.gz",
     headers={"User-Agent":"DuckDB 0.3.4 662041e2b linux_amd64"},
     proxies={'http': '{my http proxy', 'https': 'my https proxy'},
     timeout)
```
Is there any other way to define what proxy to use when downloading extensions?

#### To Reproduce
1. set then environment variables http_proxy and https_proxy
2. Execute `INSTALL 'httpfs'`
3. duckdb does not use the proxy to download the extension 

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.4
 - DuckDB Client: Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by anovember** [comment]
I'm also seeing this issue. Perhaps there is a way to install from a downloaded `httpfs.duckdb_extension.gz`? My attempts to do this in python `master` have resulted in `Segmentation fault`.

**Comment by Mause** [comment]
> I'm also seeing this issue. Perhaps there is a way to install from a downloaded `httpfs.duckdb_extension.gz`? My attempts to do this in python `master` have resulted in `Segmentation fault`. 

If you decompress the file first (assuming you downloaded the correct build for your build of duckdb) you should be able to load it

**Comment by anovember** [comment]
When I try to remote install, I see the following error:

``` IO Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/0d2d7930d/linux_amd64_gcc4/httpfs.duckdb_extension.gz" ```

so I run: 
```
wget http://extensions.duckdb.org/0d2d7930d/linux_amd64_gcc4/httpfs.duckdb_extension.gz
gzip -d httpfs.duckdb_extension.gz 
```

then in python: 
```
In [1]: import duckdb                                                                                                                                                                                 

In [2]: duckdb.__version__                                                                                                                                                                            
Out[2]: '0.4.1-dev2374'

In [3]: con = duckdb.connect()                                                                                                                                                                        

In [4]: con.install_extension("./httpfs.duckdb_extension")                                                                                                                                            

In [5]: con.execute("select * from duckdb_extensions()").df() 
   ...:                                                                                                                                                                                               
Out[5]: 
      extension_name  loaded installed                                       install_path                                        description
0              excel    True       NaN                                                                                                      
1                fts    True      True                                         (BUILT-IN)          Adds support for Full-Text Search Indexes
2             httpfs   False      True  /home/ec2-user/.duckdb/extensions/0d2d7930d/li...  Adds support for reading and writing files ove...
3                icu    True      True                                         (BUILT-IN)  Adds support for time zones and collations usi...
4               json    True      True                                         (BUILT-IN)                   Adds support for JSON operations
5            parquet    True      True                                         (BUILT-IN)  Adds support for reading and writing parquet f...
6   postgres_scanner   False     False                                                     Adds support for reading from a Postgres database
7     sqlite_scanner   False     False                                                        Adds support for reading SQLite database files
8              tpcds    True      True                                         (BUILT-IN)      Adds TPC-DS data generation and query support
9               tpch    True      True                                         (BUILT-IN)       Adds TPC-H data generation and query support
10        visualizer    True       NaN                                                                                                      
In [6]: con.load_extension("httpfs")                                                                                                                                                                  
Segmentation fault
>
```

FYI this is on an AWS EC2 machine,  x86_64 architechture.

``` 
!uname -m                                                                                                                                                                                     
x86_64
```

Thanks!

**Comment by Mause** [comment]
Please make sure the git hash of the extension you download matches `duckdb.__git_revision__` as well

**Comment by anovember** [comment]
Confirmed - `0d2d7930d`. Thanks for your help.

**Comment by Mause** [comment]
> Confirmed the same - `0d2d7930d`. Thanks for your help in debugging.

Hmm okay, can you please raise a separate issue with all that information so we can track it separately from this one?

**Comment by Alex-Monahan** [comment]
The Url appears in the error message! Then you can just un-gzip it and use it!

**Comment by JorgeGarciaIrazabal** [comment]
@Mause Thank you very much for implementing a fix for this issue. I see the PR hasn't had activity in the last 19 days, are you planning on discarding it? I'll be happy to contribute if that helps.

**Comment by Mause** [comment]
> @Mause Thank you very much for implementing a fix for this issue. I see the PR hasn't had activity in the last 19 days, are you planning on discarding it? I'll be happy to contribute if that helps.

Hi, I still plan on finishing and merging it, I've just been having issues with some of the tests

**Comment by JorgeGarciaIrazabal** [comment]
Thank you for the update Mause.

**Comment by include** [comment]
Hi there, 

I think this wasn't fixed. I still get errors when I try to INSTALL <extension> from behind a proxy.

```
D install spatial;
Error: IO Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.8.1/linux_amd64/spatial.duckdb_extension.gz"
Extension "spatial" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded. (ERROR Connection)
```

Help. kthxbye,
F

**Comment by benoitdr** [comment]
I confirm this bug is still not fixed

duckdb.IOException: IO Error: Failed to download extension "json" at URL "http://extensions.duckdb.org/v0.8.1/linux_amd64_gcc4/json.duckdb_extension.gz"

**Comment by wrb2** [comment]
We hit the same issue. It makes it basically impossible to use duckdb while connected to company network.

**Comment by ilyanoskov** [comment]
Bumping this issue, it's still very much needed

**Comment by gabrielcnr** [comment]
I'm also having this problem. 👍

**Comment by davidia** [comment]
Seeing this too

**Comment by alexparunov** [comment]
I am having the same issue.

**Comment by e-kotov** [comment]
this is not just about the extensions, it is also impossible to query s3 connections :(

**Comment by MarcusWenzel-Bayer** [comment]
I'm encountering the same issue. I was able to install httpfs locally but I still can't query any online datasources (like S3), which is a pity...

**Comment by pvaezi** [comment]
Same here, behind proxy httpfs is failing due to SSL error. The query performance is impressive, but we can't use it in our production setup due to the same issue reported above.

**Comment by MarcusWenzel-Bayer** [comment]
@hannes & @Mause : is there a timeline for implementing this feature? I saw that @Mause already did some work on this and I even tried compiling the httpfs extension from [here](https://github.com/Mause/duckdb/tree/feature/test-proxy-with-sql) but it does not seem to work yet (I'm no expert on CPP unfortunately, so I can't really contribute myself). I just want to stress how crucial this is for DuckDB to permeate business use cases in the future. I really love it and I would have already implemented it in some use cases but currently I can only do off-line analyses with it since connections to web-resources are not possible without proxy support. I hope there's some resolution to this on the horizon. I'm happy to test things for you!

**Comment by szarnyasg** [comment]
Hi @MarcusWenzel-Bayer, thanks for chiming in. I agree that this feature is an important one. That said, we do not have a publicly available roadmap and cannot promise an ETA on any specific feature request.

To allow customers to facilitate the development of certain features, DuckDB Labs offers [flexible support and consulting options](https://duckdblabs.com/support/), which can cover feature request.

**Comment by e-kotov** [comment]
bump

**Comment by MarcusWenzel-Bayer** [comment]
I don't know what has changed but suddenly I can install httpfs and query S3 resources :) Maybe I changed some settings on my machine or there were some changes from duckdb 0.8 to 1.0 that have resolved the issue for me. @e-kotov : have you tried again with duckdb 1.0 in the meantime?

**Comment by e-kotov** [comment]
wow, I just did not see that (perhaps I missed it) in the release notes. It actually works now with R package version 1.0.0!

There was a PR #10830, but it became stale. So I was not expecting that this would suddenly work.

**Comment by carlopi** [comment]
There have been improvements in allowing extensions to be installed from https / through the filesystem, but I am not sure what you are seeing exactly.

Could you possibly paste the result of:
```
SELECT extension_name,install_mode,installed_from FROM duckdb_extensions();
```
?
That should give some insights / allow explanations.

**Comment by e-kotov** [comment]
@carlopi , oh wait... yep, it does not work.

I already had "spatial" extension installed from local file, so it seemed like installation worked.

But in fact, when I try to install some new extension:

```r
dbSendStatement(con, "INSTALL jemalloc")
#> Error: rapi_execute: Failed to run query
#> Error: HTTP Error: Failed to download extension "jemalloc" at URL "http://extensions.duckdb.org/v1.0.0/linux_amd64/jemalloc.duckdb_extension.gz"
#> Extension "jemalloc" is an existing extension.
```

However, this (which is not directly related the package installation issue, but it did not work before) works:

```r
dbSendStatement(con, "CREATE VIEW ov_places_online AS SELECT * FROM read_parquet('s3://overturemaps-us-west-2/release/2024-06-13-beta.1/theme=places/type=*/*')")
#> <duckdb_result edfc0 connection=7aae0 statement='CREATE VIEW ov_places_online AS SELECT * FROM read_parquet('s3://overturemaps-us-west-2/release/2024-06-13-beta.1/theme=places/type=*/*')'>
minx = -4.4231
miny = 39.8188
maxx = -2.7892
maxy = 41.0616  
x1 <- dbGetQuery(con, "SELECT id, categories, bbox, geometry FROM ov_places_online LIMIT 10")
x1
```


@MarcusWenzel-Bayer perhaps you should also check if you are dealing with cached installations of extensions in your environment.

**Comment by carlopi** [comment]
@e-kotov: just for more clarity, could you still paste the result of `SELECT extension_name,install_mode,installed_from FROM duckdb_extensions();` after `FORCE  INSTALL vss` or such has succeeded?

**Comment by e-kotov** [comment]
@carlopi 
```r
dbSendStatement(con, "FORCE  INSTALL vss")
#> <duckdb_result bdcc0 connection=14390 statement='FORCE  INSTALL vss'>
dbSendStatement(con, "FORCE  INSTALL spatial")
#> <duckdb_result 85970 connection=14390 statement='FORCE  INSTALL spatial'>
dbGetQuery(con, "SELECT extension_name,install_mode,installed_from FROM duckdb_extensions();")
#>      extension_name      install_mode installed_from
#> 1             arrow        REPOSITORY           core
#> 2      autocomplete              <NA>               
#> 3               aws              <NA>               
#> 4             azure              <NA>               
#> 5             delta              <NA>               
#> 6             excel              <NA>               
#> 7               fts        REPOSITORY           core
#> 8            httpfs        REPOSITORY           core
#> 9           iceberg              <NA>               
#> 10              icu              <NA>               
#> 11             inet              <NA>               
#> 12         jemalloc              <NA>               
#> 13             json              <NA>               
#> 14       motherduck              <NA>               
#> 15    mysql_scanner              <NA>               
#> 16          parquet STATICALLY_LINKED               
#> 17 postgres_scanner              <NA>               
#> 18          spatial        REPOSITORY           core
#> 19   sqlite_scanner              <NA>               
#> 20        substrait              <NA>               
#> 21            tpcds        REPOSITORY           core
#> 22             tpch        REPOSITORY           core
#> 23              vss        REPOSITORY           core
```

**Comment by mghen** [comment]
After calling ...
```python
con = duckdb.connect(':memory:')
con.execute("FORCE INSTALL aws;")
```

I still get these errors in python on v1.0.0 and v1.0.1.dev3196 (respectively) when operating behind a corporate proxy:
```
duckdb.duckdb.IOException: IO Error: Failed to download extension "aws" at URL "http://extensions.duckdb.org/v1.0.0/windows_amd64/aws.duckdb_extension.gz"
```
```
duckdb.duckdb.IOException: IO Error: Failed to download extension "aws" at URL "http://extensions.duckdb.org/6f5ec94251/windows_amd64/aws.duckdb_extension.gz"
```

Calling `con.execute("SELECT extension_name,install_mode,installed_from FROM duckdb_extensions();").df()` after the above attempts results in the following:

Index | Extension Name   | Install Mode       | Installed From
------|------------------|--------------------|----------------
0     | arrow            | None               | 
1     | autocomplete     | None               | 
2     | aws              | None               | 
3     | azure            | None               | 
4     | delta            | None               | 
5     | excel            | None               | 
6     | fts              | STATICALLY_LINKED  | 
7     | httpfs           | None               | 
8     | iceberg          | None               | 
9     | icu              | STATICALLY_LINKED  | 
10    | inet             | None               | 
11    | jemalloc         | None               | 
12    | json             | STATICALLY_LINKED  | 
13    | motherduck       | None               | 
14    | mysql_scanner    | None               | 
15    | parquet          | STATICALLY_LINKED  | 
16    | postgres_scanner | None               | 
17    | spatial          | None               | 
18    | sqlite_scanner   | None               | 
20    | tpcds            | None               | 
21    | tpch             | STATICALLY_LINKED  | 
22    | vss              | None               |

**Comment by mghen** [comment]
To add to this further, a manual installation of the extensions (downloaded from the duckdb website) is possible:

```python
import duckdb
import gzip
import shutil

# unpack and install the extensions
with gzip.open("./downloads/httpfs.duckdb_extension.gz", 'rb') as f_in:
    with open("./downloads/httpfs.duckdb_extension", 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)
duckdb.install_extension("./httpfs.duckdb_extension")

with gzip.open("./downloadsaws.duckdb_extension.gz", 'rb') as f_in:
    with open("./downloads/aws.duckdb_extension", 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)
duckdb.install_extension("./aws.duckdb_extension")
```

However as soon as you attempt to query your S3 bucket, you run into the same problem again, which is also described in #6064.

So really just noting here that a manual installation of the extensions is not a viable work-around and that the non-use of the HTTP_PROXY and HTTPS_PROXY environment variables has broader implications.

**Comment by e-kotov** [comment]
> a manual installation of the extensions (downloaded from the duckdb website) is possible

That was exactly my experience too. I spend some time figuring out how to install the extensions manually only to find out that I cannot access outside world using these extensions because of the proxy in the HPC.

**Comment by curio77** [comment]
Same issue here, this is severely hampering a potential use for us.  Proper proxy support in network operations should be a given.

**Comment by mghen** [comment]
See [this comment](https://github.com/duckdb/duckdb/issues/6064#issuecomment-2259613789) for a temporary work-around.

**Comment by Mytherin** [comment]
This should be implemented now in https://github.com/duckdb/duckdb/pull/13368

**Comment by sa1** [comment]
Are the env vars being read or do I have to set it from inside duckdb?

**Comment by mghen** [comment]
@sa1 I believe they should be set from within duckdb. See examples on [this pull request](https://github.com/duckdb/duckdb/pull/13368).
