### ISSUE TITLE
Generated column parse error

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#3838]
#### What happens?

The generated column syntax in [the documentation](https://duckdb.org/docs/sql/statements/create_table#generated-columns) gives a parse error

#### To Reproduce

```sql
CREATE TABLE t1(x FLOAT, two_x AS (2 * x));
```
```
Error: Parser Error: syntax error at or near "AS"
LINE 1: CREATE TABLE t1(x FLOAT, two_x AS (2 * x));
```

```sql
CREATE TABLE t1(x FLOAT, two_x FLOAT GENERATED ALWAYS AS (2 * x) VIRTUAL);
```

```
Error: Parser Error: syntax error at or near "("
LINE 1: ...FLOAT, two_x FLOAT GENERATED ALWAYS AS (2 * x) VIRTUAL);
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: v0.3.4 662041e2b, 0.3.5.dev1206
 - DuckDB Client: cli, python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
Hi, first of all love to see that the feature I worked on is already waiting to be used :D!

It appears that the version you describe doesn't have generated columns yet though, as the commit you referenced in the Environment section was merged on the 25th of April, and generated columns were merged on the 7th of June :)

For reference, this is the commit that merges generated columns into master:
https://github.com/duckdb/duckdb/commit/5287a381fe796e2bf6c38d89b5ad6bdd5cd7e8fc
