### ISSUE TITLE
Export database does not export macros

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#3839]
#### What happens?

Macros are not exported with 'EXPORT DATABASE'. This might be expected as MACROs are omitted from the list of exported things in the [documentation](https://duckdb.org/docs/sql/statements/export#syntax).

#### To Reproduce

```sql
CREATE MACRO ADD(x,y) AS x+y;
EXPORT DATABASE '/tmp/test';
```

will produce an /tmp/test empty directory (though adding a table will produce the expected load.sql, schema.sql files).

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: v0.3.4, 0.3.5.dev1206
 - DuckDB Client: cli,python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by lnkuiper** [comment]
Sure, I can have a go at this
