### ISSUE TITLE
JDBC Appender for Decimal Type inserts incorrect value.

### ISSUE THREAD

**Issue by jonathanswenson** [duckdb/duckdb#3841]
#### What happens?

When using an appender to insert a decimal type with the method, an incorrect value is always (for all values I've tried) inserted. 

Values inserted with an insert statement are inserted and returned correctly, so the issue appears to be during ingestion rather than processing / return. 

As discovered in the [comment](https://github.com/duckdb/duckdb/issues/3841#issuecomment-1154444505) below, it appears as though the conversion logic is using the X -> integer conversion rather than X -> decimal conversions and then applying the appropriate scale to the value. 

#### To Reproduce

```java
    DuckDBConnection connection = getConnection();

    Statement createStatement = connection.createStatement();
    createStatement.execute("CREATE TABLE decimal_test(dec_value DECIMAL(4,2))");
    createStatement.close();

    try (DuckDBAppender appender = connection.createAppender("main", "decimal_test")) {
      appender.beginRow();
      appender.append(12.34);
      // appender.append("12.34"); also produces same result
      // appender.append(12.34F); also produces same result
      appender.endRow();
    }

    Statement insertStatement = connection.createStatement();
    int updateCount = insertStatement.executeUpdate("INSERT INTO decimal_test VALUES (12.34)");
    assertEquals(1, updateCount);
    insertStatement.close();

    Statement resultStatement = connection.createStatement();
    ResultSet resultSet = resultStatement.executeQuery("SELECT dec_value from decimal_test");

    resultSet.next();

    BigDecimal appendedDecimalValue = resultSet.getBigDecimal(1);
    assertEquals(BigDecimal.valueOf(1234, 2), appendedDecimalValue); // fails (actual value is 0.12)
    assertEquals(2, appendedDecimalValue.scale()); // correct

    resultSet.next();

    // to showcase how insert works correctly.
    BigDecimal insertedDecimalValue = resultSet.getBigDecimal(1);
    assertEquals(BigDecimal.valueOf(1234, 2), insertedDecimalValue); // correct
    assertEquals(2, insertedDecimalValue.scale()); // correct

    resultSet.close();
    resultStatement.close();
    connection.close();
```

#### Environment (please complete the following information):
 - OS: MacOS 12.3.1 (Monterey -- Apple Silicon)
 - DuckDB Version: JDBC 0.3.3
 - DuckDB Client: JDBC

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?** (built from source)
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by jonathanswenson** [comment]
It appears that this may be due to the conversion code [here](https://github.com/jonathanswenson/duckdb/blob/3714e4fecc861333711525fa4ecdfc3f11daa802/src/main/appender.cpp#L133-L147) 

The String, Double, Float, etc -> numeric conversion is trying to re-interpret the value as an integer using the string, double, float -> integer cast logic defined in [cast_operators.cpp](https://github.com/jonathanswenson/duckdb/blob/3714e4fecc861333711525fa4ecdfc3f11daa802/src/common/operator/cast_operators.cpp#L794-L794)

That appears to do things like truncation at the decimal point (`12.34` -> `12`). Then with an application of a scale of 2, this would be interpreted as `0.12` (which appear to be what is currently returned). 

After trying a few other values this appears consistent with the actual return values. 

`101.59` => `1.01`
`1203.932` => `12.03` 
`12250.93234` => `122.50`
`24252.93223` => `242.52`

Also it appears to do some rounding for strings, but not for doubles: 
`'9992.93223'` => `99.93` vs `9992.93223` => `99.92` 

Potentially worth noting that this is NOT the case with the direct cast in the dialect in a SQL query:
`SELECT CAST('12.34' as DECIMAL(4,2))` => `12.34`
`SELECT CAST('9992.93223' as DECIMAL(4,2))` => error (expected) due to being out of range due to being larger than 10^2

**Comment by Mytherin** [comment]
Thanks for the report! I agree this should be fixed - it is not intuitive right now.
