### ISSUE TITLE
Segment stats shows "has null" as false in pragma_storage_info

### ISSUE THREAD

**Issue by zippond** [duckdb/duckdb#3844]
Hi,

I created a int column and insert some null values, but the pragma_storage_info() always says "has null" is false for INTEGER segment type. Is it expected?

D create table t(i int);
D insert into t values(null),(1);
D select column_id,column_path,segment_type,stats from pragma_storage_info('t');
┌───────────┬─────────────┬──────────────┬───────────────────────────────────┐
│ column_id │ column_path │ segment_type │ stats │
├───────────┼─────────────┼──────────────┼───────────────────────────────────┤
│ 0 │ [0] │ INTEGER │ [Min: 1, Max: 1][Has Null: false] │
│ 0 │ [0, 0] │ VALIDITY │ [Has Null: true] │
└───────────┴─────────────┴──────────────┴───────────────────────────────────┘
D

**Comment by hannes** [comment]
I answered this there no? https://github.com/duckdb/duckdb-web/issues/242

**Comment by zippond** [comment]
Oh sorry actually I have further questions. It's related to #3772 .
The has_null info for data segment is misleading. And if I manually construct a IsNullFilter for a table scan, the whole segment is skipped due to the segment zone map check:
`FilterPropagateResult IsNullFilter::CheckStatistics(BaseStatistics &stats) {
	if (!stats.CanHaveNull()) {
		// no null values are possible: always false
		return FilterPropagateResult::FILTER_ALWAYS_FALSE;
	}
	if (!stats.CanHaveNoNull()) {
		// no non-null values are possible: always true
		return FilterPropagateResult::FILTER_ALWAYS_TRUE;
	}
	return FilterPropagateResult::NO_PRUNING_POSSIBLE;
}`
I'm not sure if the IsNullFilter can be used here, did I make some mistake here?
