### ISSUE TITLE
Exported database does not include generated column function

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#3851]
#### What happens?

The schema.sql of an exported database includes the name and type of generated columns but not the function itself.

Generated columns are brand new (thanks @Tishj!) and not an official release yet, so feel free to close if this issue is premature.

#### To Reproduce

```sql
CREATE TABLE t1(x FLOAT, two_x AS (2 * x));
EXPORT DATABASE 'exporttest';
```

`exportest/schema.sql`
```sql
CREATE TABLE t1(x FLOAT, two_x FLOAT);
```

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.5.dev1239
 - DuckDB Client: python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
Hey! Thanks for making me aware of this issue, definitely not premature, just an oversight on my part 👍
