### ISSUE TITLE
HTTPFS - INTERNAL Error: Can't find the home directory at "" when $HOME is unset/empty

### ISSUE THREAD

**Issue by woozyking** [duckdb/duckdb#3855]
#### What happens?
In certain runtime environments (such as AWS Lambda), where the `$HOME` is deliberately unset (or set to an empty string), bootstrapping an in-memory DuckDB would result in the title-mentioned error.

#### To Reproduce
The original steps were created using SQLAlchemy (through [`duckdb-engine`](https://github.com/Mause/duckdb_engine)), raised at https://github.com/Mause/duckdb_engine/issues/258 (also includes a workaround, particular to AWS Lambda runtime, is to set `HOME=/tmp` prior to invocation of `install httpfs`)

The minimal step to reproduce through DuckDB CLI is as such:

```shell
% env HOME='' duckdb
v0.3.4 662041e2b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install httpfs;
Error: INTERNAL Error: Can't find the home directory at 
```

#### Environment (please complete the following information):
 - OS: macOS 12.4 (and AWS Lambda official Python 3.9 runtime, which should be Linux)
 - DuckDB Version: v0.3.4 662041e2b
 - DuckDB Client: Python (`duckdb-engine`) and the official CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
From https://github.com/duckdb/duckdb/actions/runs/2495776338 (v0.3.5-dev1253 cdfb9f92f)

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
Yes, the issue is still there with the ^ mentioned CI artifact

```shell
% env HOME='' ./duckdb 
v0.3.5-dev1253 cdfb9f92f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install httpfs;
Error: INTERNAL Error: Can't find the home directory at 
```

**Comment by hannes** [comment]
You could download the extension manually and LOAD from wherever you installed it

**Comment by hannes** [comment]
@samansmink

**Comment by woozyking** [comment]
> You could download the extension manually and LOAD from wherever you installed it, we should eventually add configuration parameter to set the extension installation path

Makes sense. The current work around works well for us, which is conceptually `env HOME=/tmp <run process>` in the given container environment that doesn't have a `$HOME` set.

Along the line, but perhaps worthy of another issue, is that the HTTPFS extension (or DuckDB itself, sorry not very familiar with the implementation itself yet) can default to environment variables for AWS-related configs so that users do not need to relay explicitly such as:

```python
# snippet of Python code
init_query = f"""
    INSTALL httpfs;

    LOAD httpfs;

    SET s3_region='us-east-1';
    SET s3_access_key_id='{os.getenv("AWS_ACCESS_KEY_ID")}';
    SET s3_secret_access_key='{os.getenv("AWS_SECRET_ACCESS_KEY")}';
"""
```

could be omitted to simply be

```python
init_query = f"""
    INSTALL httpfs;

    LOAD httpfs;

    SET s3_region='us-east-1'; -- maybe even this can be omitted if region env var is set
"""
```

**Comment by kamaljit-1991** [comment]
Hey duckDB team I have the same issue. So I am using the java library of duckDB from maven. I am trying to read/write directly in s3 but it fails in this step with the same exception as here people are getting : 
```
            Class.forName("org.duckdb.DuckDBDriver");
            Properties prop = new Properties();
            prop.setProperty("s3_region", creds.region);
            prop.setProperty("s3_session_token", Utils.sessionToken(creds.fivetranRoleArn, creds.externalId));
            Connection conn = DriverManager.getConnection("jdbc:duckdb:", prop);
            try (Statement stmt = conn.createStatement()) {
                stmt.execute("INSTALL httpfs");
                stmt.execute("LOAD httpfs");
            }
```
I am getting the exception while installing httpfs `java.sql.SQLException: INTERNAL Error: Can't find the home directory at `. To resolve this I tried setting `HOME` env variable using System.setProperty() and also directly I tried to set in System.getenv(). But no result. It still failed. What do I have to do to make it work ?

**Comment by Mause** [comment]
> 



> Hey duckDB team I have the same issue. So I am using the java library of duckDB from maven. I am trying to read/write directly in s3 but it fails in this step with the same exception as here people are getting :
> 
> ```
>             Class.forName("org.duckdb.DuckDBDriver");
>             Properties prop = new Properties();
>             prop.setProperty("s3_region", creds.region);
>             prop.setProperty("s3_session_token", Utils.sessionToken(creds.fivetranRoleArn, creds.externalId));
>             Connection conn = DriverManager.getConnection("jdbc:duckdb:", prop);
>             try (Statement stmt = conn.createStatement()) {
>                 stmt.execute("INSTALL httpfs");
>                 stmt.execute("LOAD httpfs");
>             }
> ```
> 
> I am getting the exception while installing httpfs `java.sql.SQLException: INTERNAL Error: Can't find the home directory at `. To resolve this I tried setting `HOME` env variable using System.setProperty() and also directly I tried to set in System.getenv() using hackfix provied [here](https://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java) . But no result. It still failed. What do I have to do to make it work ?

Try setting it externally to the java application instead?

**Comment by Mause** [comment]
> 



> 



> > You could download the extension manually and LOAD from wherever you installed it, we should eventually add configuration parameter to set the extension installation path
> 
> Makes sense. The current work around works well for us, which is conceptually `env HOME=/tmp <run process>` in the given container environment that doesn't have a `$HOME` set.
> 
> Along the line, but perhaps worthy of another issue, is that it'd be more user-friendly if the `httpfs` extension (or DuckDB itself, sorry not very familiar with the implementation itself yet) can default to environment variables for AWS-related configs so that users do not need to relay explicitly such as:
> 
> ```python
> # snippet of Python code
> init_query = f"""
>     INSTALL httpfs;
> 
>     LOAD httpfs;
> 
>     SET s3_region='us-east-1';
>     SET s3_access_key_id='{os.getenv("AWS_ACCESS_KEY_ID")}';
>     SET s3_secret_access_key='{os.getenv("AWS_SECRET_ACCESS_KEY")}';
> """
> ```
> 
> could be omitted to simply be
> 
> ```python
> init_query = f"""
>     INSTALL httpfs;
> 
>     LOAD httpfs;
> 
>     SET s3_region='us-east-1'; -- maybe even this can be omitted if region env var is set
> """
> ```

I think that would be more complicated than it first seems, due to the possibility of multiple configuration sets (I forget what aws calls them) on a single machine.

**Comment by woozyking** [comment]
> I think that would be more complicated than it first seems, due to the possibility of multiple configuration sets (I forget what aws calls them) on a single machine.

Agree. We're perfectly content with the workaround approach. Though a tiered fallback strategy where the explicit in-query `SET <key>=<value>` gets the highest precedence could be reasonable. For instance, it's either the `SET` command or the exposed environment variables in-process.

> I forget what aws calls them

They're called Named Profiles, I believe, which can be directed using the environment variable `AWS_CONFIG_FILE` too to specify.

**Comment by Mause** [comment]
> > I think that would be more complicated than it first seems, due to the possibility of multiple configuration sets (I forget what aws calls them) on a single machine.
> 
> Agree. We're perfectly content with the workaround approach. Though a tiered fallback strategy where the explicit in-query `SET <key>=<value>` gets the highest precedence could be reasonable. For instance, it's either the `SET` command or the exposed environment variables in-process.
> 
> > I forget what aws calls them
> 
> They're called Named Profiles, I believe, which can be directed using the environment variable `AWS_CONFIG_FILE` too to specify.

That's definitely workable yes, but should probably be raised in another issue
