### ISSUE TITLE
Incorrect HAS_NULL stats for integer column

### ISSUE THREAD

**Issue by zippond** [duckdb/duckdb#3873]
#### What happens?
pragma_storage_info('t') shows incorrect "Has Null" for column segments.
As the "standard column" has a seperate Validity segment, there're 2 issues here. 
1. The INTEGER segment stats always shows "Has Null: false" even if there's null values.
2. If update column with null values, even the VALIDITY segment shows incorrect "Has Null" stats.

Sorry I don't know how to construct a test case to trigger this issue. 
I hit this issue when working on #3772. I tried to push an IsNullFilter to a DataTable::Scan(), and expect to get the Null values. But the IsNullFilter::CheckStatistics() called by StandardColumnData::CheckZonemap() seem just check the has_null stats of data segment which is always false, hence the segment was skipped incorrectly.

#### To Reproduce
create table t(i int);
insert into t values(1);
#insert not_null value, stats shows correctly
select column_path path, segment_type tp ,count c,stats from pragma_storage_info('t');
┌────────┬──────────┬───┬──────────────────────────────────────────────────────┐
│  path  │    tp    │ c │                        stats                         │
├────────┼──────────┼───┼──────────────────────────────────────────────────────┤
│ [0]    │ INTEGER  │ 1 │ [Min: 1, Max: 1][**Has Null: false**, Has No Null: true] │
│ [0, 0] │ VALIDITY │ 1 │ [**Has Null: false**, Has No Null: true]                 │
└────────┴──────────┴───┴──────────────────────────────────────────────────────┘
update t set i = null;
#update null value, both VALIDITY anINTEGER segments shows incorrect stats
select column_path path, segment_type tp ,count c,stats from pragma_storage_info('t');
┌────────┬──────────┬───┬──────────────────────────────────────────────────────┐
│  path  │    tp    │ c │                        stats                         │
├────────┼──────────┼───┼──────────────────────────────────────────────────────┤
│ [0]    │ INTEGER  │ 1 │ [Min: 1, Max: 1][**Has Null: false**, Has No Null: true] │
│ [0, 0] │ VALIDITY │ 1 │ [**Has Null: false**, Has No Null: true]                 │
└────────┴──────────┴───┴──────────────────────────────────────────────────────┘
insert into t values(null);
#insert null value, VALIDITY correct, INTEGER still wrong. It's not only misleading, but will confuse the Segment ZoneMap check for IsNullFilter.
select column_path path, segment_type tp ,count c,stats from pragma_storage_info('t');
┌────────┬──────────┬───┬──────────────────────────────────────────────────────┐
│  path  │    tp    │ c │                        stats                         │
├────────┼──────────┼───┼──────────────────────────────────────────────────────┤
│ [0]    │ INTEGER  │ 2 │ [Min: 1, Max: 1][**Has Null: false**, Has No Null: true] │
│ [0, 0] │ VALIDITY │ 2 │ [**Has Null: true**, Has No Null: true]                  │
└────────┴──────────┴───┴──────────────────────────────────────────────────────┘

#### Environment (please complete the following information):
 - OS:  Suse12.5
 - DuckDB Version: v0.3.5-dev1297 d4c437597
 - DuckDB Client:  CLI

#### Before Submitting

- [Y] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [Y] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannes** [comment]
This is not a problem but a misconception on how to interpret the storage information I think.

**Comment by zippond** [comment]
Hi @hannes, @Mytherin. Sorry I'm still confusing about this issue and hope you can help me out. 
1. This time even the validity segment doesn't show correct info. Is it expected?
2. Is there any document about how to interpret the storage information? 
3. How should is_null be used for data segment? I find the StandardColumnData::CheckZonemap() used the nullness info as a constraint to skip segments which shouldn't have...

**Comment by hannes** [comment]
There is no need to @ anyone, please refrain from doing so
