### ISSUE TITLE
Parser too picky about newlines and trailing semicolons?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#3874]
#### What happens?

Unexpected behavior depending on the presence of newlines and a terminal semicolon with the CLI.

- Multiline queries work as expected, terminal semicolon is requred, last terminal semicolon optional
- With two specific queries on a single line without trailing semicolon, the second query loses column names (?)
- With two specific queries on a single line with trailing semicolon, the second query errors (???)

#### To Reproduce

```sh
➜  duckdb git:(d4c437597) ✗ echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a));
INSERT INTO x VALUES (1) RETURNING (a);
" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘
➜  duckdb git:(d4c437597) ✗ echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a));
INSERT INTO x VALUES (1) RETURNING (a)
" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘
➜  duckdb git:(d4c437597) ✗ echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a)); INSERT INTO x VALUES (1) RETURNING (a)" | build/debug/duckdb
┌───┐
│   │
├───┤
│ 1 │
└───┘
➜  duckdb git:(d4c437597) ✗ echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a)); INSERT INTO x VALUES (1) RETURNING (a);" | build/debug/duckdb
Error: near line 1: Parser Error: syntax error at or near " "
LINE 1: ...INSERT INTO x VALUES (1) RETURNING (a);
                                                  ^
```

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: d4c437597
 - DuckDB Client: Shell

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
All of this seems to work as expected for me:

```sql
duckdb-bugfix > echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a));
INSERT INTO x VALUES (1) RETURNING (a);
" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘
duckdb-bugfix > echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a));
INSERT INTO x VALUES (1) RETURNING (a)
" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘
duckdb-bugfix > echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a)); INSERT INTO x VALUES (1) RETURNING (a)" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘
duckdb-bugfix > echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a)); INSERT INTO x VALUES (1) RETURNING (a);" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘

```

Only when I copy from the source of your comment do I see the problem (top is from the source of your comment, bottom is from the actual comment):

![Screenshot 2022-06-16 at 06 48 53](https://user-images.githubusercontent.com/3978469/173993507-8fc3a4c7-1097-48e4-a263-fd41bb28a1db.png)

It looks like you are inserting and copying invisible control characters into the shell which is causing these issues.

I would say this is not a bug in DuckDB.

**Comment by krlmlr** [comment]
Thanks, confirmed:

```
✗ echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a)); INSERT INTO x VALUES (1) RETURNING (a);\u00a0" | build/debug/duckdb
Error: near line 1: Parser Error: syntax error at or near " "
LINE 1: ...INSERT INTO x VALUES (1) RETURNING (a);
                                                  ^
```

Should this output escape any non-ASCII characters to make the error more apparent?

**Comment by Mytherin** [comment]
I would say not, I would prefer not to escape unicode characters in error messages as using unicode characters might well be very common depending on e.g. the language being used. We could consider detecting certain unicode characters or throwing an error if the query is not valid UTF-8, but for now I would consider this low priority.
