### ISSUE TITLE
Small create table issues

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#3878]
#### What happens?
Creating a table with constraints and no columns gives an internal error. I am going to make a pull request to fix it (very simple).
I also noticed the foreign key construct on a column declaration is not yet implemented, but it's easy to add:

`create table x(x int primary key);
create table y(y int references x(x));`

#### To Reproduce
`create table ups (primary key(x));`
Error: INTERNAL Error: Assertion triggered in file "...src/planner/binder/statement/bind_create_table.cpp" on line 51: !info.name_map.empty()

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: latest from development branch.
 - DuckDB Client: Shell

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by PedroTadim** [comment]
Pull request has been merged.

**Comment by Mytherin** [comment]
Fyi if you include “fixes #3878” in the PR it automatically links the PR with the issue and will auto-close the issue upon merge
