### ISSUE TITLE
Error reading parquet file: Struct child row count mismatch

### ISSUE THREAD

**Issue by LarsStegemanGT** [duckdb/duckdb#3896]
#### What happens?
When reading a parquet file through the CLI, I get the error "Struct child row count mismatch". It only occurs on a specific column other columns work fine.

#### To Reproduce
The original parquet file contains more columns but i tried to create a minimal example.
```sql
COPY
(SELECT map([1],[{'key1': map([1,2], [1,2]), 'key2':2}]) 
UNION ALL SELECT map([2], [{'key1': map([3,4],[1,2]), 'key2':2}])) 
TO 'test.parquet' (FORMAT 'parquet');
SELECT * FROM 'test.parquet';
Error: Struct child row count mismatch
```

Using SELECT it gives the correct result:
```sql
SELECT map([1],[{'key1': map([1,2], [1,2]), 'key2':2}]) 
UNION ALL SELECT map([2], [{'key1': map([3,4],[1,2]), 'key2':2}])
┌────────────────────────────────────────────────────────────────────────────────────┐
│ map(main.list_value(1), main.list_value(main.struct_pack(map(main.list_value(1,... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ {1={'key1': {1=1, 2=2}, 'key2': 2}}                                                │
│ {2={'key1': {3=1, 4=2}, 'key2': 2}}                                                │
└────────────────────────────────────────────────────────────────────────────────────┘
```

Using only one row, a different error occurs:
```sql
COPY
(SELECT map([1],[{'key1': map([1,2], [1,2]), 'key2':2}])) TO 'test.parquet' (FORMAT 'parquet');
SELECT * FROM 'test.parquet';
Error: TProtocolException: Invalid data
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.4
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Could you share the Parquet file?

**Comment by Mytherin** [comment]
> Could you share the Parquet file?

Nevermind, I missed that you had included the generation of the Parquet file. I have managed to solve the issue in #3904. Could you perhaps verify that this solves the problem also for your original Parquet file?

Thanks!

**Comment by LarsStegemanGT** [comment]
Thanks for the quick fix!
I tested it on my original parquet files and it solves the problem.
