### ISSUE TITLE
DuckDb Jdbc driver limitations

### ISSUE THREAD

**Issue by pjain1** [duckdb/duckdb#3906]
#### What happens?
We have a use case for doing custom sql things in our app for which we are using calcite before sending the query to duckdb. I am using DuckDb's jdbc driver but so far ran into following limitations -
1. Duckdb's DuckDBConnection.java class does not support `getSchema()` which `Retrieves this {@code Connection} object's current schema name.` so cannot directly using JDBC catalog schema from calcite which automatically discovers db schemas as it uses this method [here](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcCatalogSchema.java#L112)
```
public String getSchema() throws SQLException {
		throw new SQLFeatureNotSupportedException();
	}
```
2. Was thinking of using [CachedRowSet](https://docs.oracle.com/javase/7/docs/api/javax/sql/rowset/CachedRowSet.html) for serializing query responses but it uses ResultSetMetaData's `getColumnDisplaySize` method, which is not implemented (DuckDBResultSetMetaData.java)
```
public int getColumnDisplaySize(int column) throws SQLException {
		throw new SQLFeatureNotSupportedException();
	}
```

Any particular reason why these methods are not implemented yet ?

#### To Reproduce
Methods are not implemented 

#### Environment (please complete the following information):
 - duckdb_jdbc - 0.3.3

#### Identity Disclosure:
 - Full Name: Parag Jain
 - Affiliation: Rill Data

**Comment by Mytherin** [comment]
`getSchema` has been implemented in #3988

**Comment by Mause** [comment]
I'll be looking to implement the remaining required methods for CachedResultSet over the coming days as well

**Comment by pjain1** [comment]
Thanks a lot @Mause @Mytherin for suck a quick turnaround. When can we expect a release with these features ?

**Comment by Mause** [comment]
> Thanks a lot @Mause @Mytherin for suck a quick turnaround. When can we expect a release with these features ?

We don't presently do snapshot releases unfortunately (something to look into @hannes?) so if you want to try it out right now you'll have to download it from the artifacts on the master build. Otherwise you'll have to wait for the next full release, though I'm not sure when that will be
