### ISSUE TITLE
Semi join relation produced by the substrait extension includes column references from the right table 

### ISSUE THREAD

**Issue by gaohao95** [duckdb/duckdb#3922]
#### What happens?

Semi join should include columns from the left table only. However, the substrait extension will produce a join relation and a projection relation for semi join and the projection relation contains column references to the right table.

#### To Reproduce

Here's a SQL query slightly modified from TPC-DS Q6
```
SELECT state, cnt FROM (
 SELECT a.ca_state state, count(*) cnt
 FROM
    customer_address a, customer c, store_sales s, date_dim d, item i
 WHERE a.ca_address_sk = c.c_current_addr_sk
   AND c.c_customer_sk = s.ss_customer_sk
   AND s.ss_sold_date_sk = d.d_date_sk
   AND s.ss_item_sk = i.i_item_sk
   AND d.d_month_seq IN
      (SELECT d_month_seq FROM date_dim
        WHERE d_year = 2001 AND d_moy = 1)
   AND i.i_current_price > 1.2 *
             (SELECT avg(j.i_current_price) FROM item j
               WHERE j.i_category = i.i_category)
 GROUP BY a.ca_state
) x
WHERE cnt >= 10
ORDER BY cnt LIMIT 100
```
But I think we should observe this behavior for any query using semi join.

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: current master branch compiled from source
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

#### Comments

Perhaps we should add right table columns only if it's not semi join here? https://github.com/duckdb/duckdb/blob/8e602ba1d81911ed70724a57356fb6714a9a8ecf/extension/substrait/to_substrait.cpp#L631-L635

**Comment by hannes** [comment]
Could you please also disclose your affiliation as indicated in the issue template?

**Comment by pdet** [comment]
Moving this issue to:
https://github.com/duckdblabs/substrait/issues/2
