### ISSUE TITLE
ODBC error when connecting to Tableau

### ISSUE THREAD

**Issue by ilcaa72** [duckdb/duckdb#3932]
Tried to connect to Tableau using the ODBC driver, received an error (see screenshot)

Is connecting to Tableau as a data source possible?   if so whats best method/resolve this issue?  thanks

![tableau_ODBC driver](https://user-images.githubusercontent.com/63480773/174897557-ebfb3dfb-fa9b-44b0-87da-c51fcf0114bb.jpg)

**Comment by tiagokepe** [comment]
@ilcaa72 Could you enable the ODBC trace using the `ODBC Data Source Administrator`?

Then you could run Tableau again and atach the ODBC trace file here.

**Comment by ilcaa72** [comment]
here is the Trace log. I started the Trace, opened tableau, tried to connect to 'other odbc' by selecting 'duckdb driver', error was generated and i closed it down. hopefully that was enough.  
**side note, when I try to use the jdbc on DBeaver, i get this error (using both .40 driver and .3.3) see screenshot.

[SQL_trace_Tableau_duckdbODBC.LOG](https://github.com/duckdb/duckdb/files/8957166/SQL_trace_Tableau_duckdbODBC.LOG)


![dbeaver_Jdbc driver](https://user-images.githubusercontent.com/63480773/175021010-46dd3f7c-96a5-47aa-8981-4b90ec4dcff0.jpg)

**Comment by hawkfish** [comment]
You can connect to Tableau with the JDBC driver. I have made a [connector](https://github.com/hawkfish/duckdb-taco) ("taco") using it, which you are welcome to try. It has been through the full test suite, but I recommend using the most recent JDBC driver from `master`.
