### ISSUE TITLE
IMDB data not available

### ISSUE THREAD

**Issue by remysucre** [duckdb/duckdb#3933]
Running `make imdb` returns the following: 

```
wget: unable to resolve host address ‘download.duckdb.org’
No URLs found in http://download.duckdb.org/imdb/list.txt.
```

Looks like the site is down? Maybe just put the "list.txt" in the repository?

**Comment by hannes** [comment]
We lost those files regrettably.

**Comment by remysucre** [comment]
I usually get the data from this link: http://homepages.cwi.nl/~boncz/job/imdb.tgz The single tgz file expands to all the csv files.

**Comment by hannes** [comment]
Yes we had greatly minified the dataset though to speed up the benchmark. We could indeed just use the full set.

**Comment by carlopi** [comment]
Thanks for noticing, https://github.com/duckdb/duckdb/commit/1891d7c709e043fef4aa414152f50f08caab4113 removed the imdb target from the Makefile, I think it can be closed.
