### ISSUE TITLE
profile flag does nothing in IMDB benchmark

### ISSUE THREAD

**Issue by remysucre** [duckdb/duckdb#3934]
Running `./build/release/benchmark/benchmark_runner --profile IMDBQ007` only prints the time but not the query plan.

**Comment by remysucre** [comment]
It prints the query plan on `benchmark/micro/nulls/no_nulls_addition.benchmark` correctly, so maybe this is a problem with the IMDB benchmark setup?

**Comment by Mytherin** [comment]
`--profile` only works with interpreted benchmarks (i.e. the `.benchmark` files), not with compiled benchmarks, so this is expected. The IMDB benchmarks should be converted to interpreted benchmarks as well.

**Comment by remysucre** [comment]
Makes sense. Here's a workaround: https://github.com/duckdb/duckdb/commit/730e56b1f87813e7fa825a996cfa2780559f3e1f

**Comment by Mytherin** [comment]
As this is expected behavior I will close this issue
