### ISSUE TITLE
Signed integer overflow while converting Infinity to time type

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#3937]
#### What happens?
While setting a fuzzer for DuckDB, I found a signed integer overflow with the undefined behavior sanitizer.

#### To Reproduce
`select 'infinity'::TIME;`
src/common/types/timestamp.cpp:167:55: runtime error: signed integer overflow: 2147483647 * 86400000000 cannot be represented in type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/common/types/timestamp.cpp:167:55

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: latest from development sources
 - DuckDB Client: Shell

#### Identity Disclosure:
 - Full Name: Pedro Ferreira
 - Affiliation: Huawei

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Should be fixed now
