### ISSUE TITLE
`httpfs` extension failing to parse URL with `+`

### ISSUE THREAD

**Issue by gforsyth** [duckdb/duckdb#3938]
#### What happens?
After installing and loading `httpfs`, I can directly load a parquet file from a URL but not if that URL contains a `+` in it (or possibly another symbol that's messing with the parser?)

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

```
./duckdb
v0.4.1-dev54 d4c18532b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D load 'extension/httpfs/httpfs.duckdb_extension';
D SELECT * FROM parquet_scan('https://raw.githubusercontent.com/cwida/duckdb/master/data/parquet-testing/bug1554.parquet') limit 5;
┌────────────────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────┬──────────────────┐
│                                         id                                         │ is_self_canonical │ backlink_count │ http_status_code │
├────────────────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────┼──────────────────┤
│ 1584883:SSuWRbZnFmIqCUBQYxk9+48fdIwywjfQUyfcKP+pbJhaqWS+UZh0Sua8VNJKlQpIlRzyWr5... │ false             │                │ 200              │
│ 1584883:VduFa/R/CL7CbbEUmdFKysh80R38hXdrfuDlFhsa5mU3G3vfUDiQdTR0H0LzJzWojUDGgUr... │ false             │                │ 200              │
│ 1584883:NWflFlh0KoHKTGAQ6G1GM3cs6HiRkJuWX+GAmgI0TSo6zxjXB9YuidjQfJNP8dNi5fuHf6g... │ true              │                │ 200              │
│ 1584883:Hi9EQ0dC7sFD8uphsqx96y/QCPmVyHpE+0EhMfgIBpsWzinDKam6zdEw7rnV8IgI0DYAZZa... │ false             │                │ 200              │
│ 1584883:n/Bpv+w2E1VG36/a6fwm2zsLEAIHwsRmfW33wuSfwbrvOXCzMInLeNKpR+mioFw3W1smXcZ... │ true              │                │ 200              │
└────────────────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────┴──────────────────┘
D SELECT * FROM parquet_scan('https://nyc-tlc.s3.amazonaws.com/trip+data/yellow_tripdata_2022-01.parquet') limit 5;
Error: Unable to connect to URL "https://nyc-tlc.s3.amazonaws.com/trip+data/yellow_tripdata_2022-01.parquet": 404 (Not Found)
```

#### Environment (please complete the following information):
 - OS: Arch Linux
 - DuckDB Version: 0.4.1-dev54 d4c18532b
 - DuckDB Client: CLI

#### Identity Disclosure:
 - Full Name: Gil Forsyth
 - Affiliation: Voltron Data

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
I have pushed a fix in #3965 which fixes this issue for certain files containing + characters, but upon verification it seems the example you mentioned here still does not work.

@samansmink could you perhaps have a look?
