### ISSUE TITLE
Write CSV with timestamp columns in ISO 8601 strings

### ISSUE THREAD

**Issue by davidtheclark** [duckdb/duckdb#3942]
Right now, if I write a CSV with either `COPY` or `EXPORT DATABASE` statements, the only format I can get for timestamp columns is not ISO-8601 compliant, e.g. `2021-02-01 13:00:00`.  I'd like to be able to tell DuckDB to write the ISO-8601 format `2021-02-01T13:00:00Z`, instead.

Documentation for both `COPY` AND `EXPORT DATABASE` suggest I might be able to set a `TIMESTAMPFORMAT` option. But when I try this, I'm told that it is not yet implemented: `Not implemented Error: Unrecognized option for CSV: TIMESTAMPFORMAT`.

I [chatted with `__Alex__` about this in Discord](https://discord.com/channels/909674491309850675/921073327009853451/989378834828767313), and he suggested I file this issue. Thanks!

**Comment by hannes** [comment]
We should probably use the T there by default

**Comment by Mytherin** [comment]
`TIMESTAMPFORMAT` is only supported for reading CSVs, we should implement this for writing as well.

> We should probably use the T there by default

Postgres does not, and I would follow them here, but we could certainly make a short-cut (e.g. `TIMESTAMPFORMAT 'iso').

**Comment by davidtheclark** [comment]
I think that both the middle `T` and the final `Z` are important for a fully valid ISO string.
