### ISSUE TITLE
Extensions not installed atomically

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#3947]
#### What happens?
When installing a duckdb extension from local disk, the installation does not occur atomically with respect to other processes on the host. If another duckdb process attempts to use the extension prior to the file copy succeeding, it will fail to load the extension. In our environment, that results in an error message like this: `Unexpected error value: "IO Error: File \"/opt/render/.duckdb/extensions/da9ee49/linux_amd64/json.duckdb_extension\" could not be loaded: /opt/render/.duckdb/extensions/da9ee49/linux_amd64/json.duckdb_extension: file too short"` (`/opt/render` is `$HOME` in this environment)

I believe the issue is with the following code:

https://github.com/duckdb/duckdb/blob/cdb786d7ed0067d03371d4cd599fc5ac2bade2ea/src/main/extension/extension_install.cpp#L53-L64

A more typical way to do an install like this is to copy it to a temporary file in that same directory (perhaps with a few random characters as a suffix), and then to move the temporary file into place (I've found https://rcrowley.org/2010/01/06/things-unix-can-do-atomically.html helpful in the past, in case you haven't seen it!)

#### To Reproduce
It's a race condition on a file copy, so it's pretty tricky!

#### Environment (please complete the following information):
 - OS: Debian buster
 - DuckDB Version: 0.4.0
 - DuckDB Client: nodejs

**Comment by hannes** [comment]
Indeed that's a good idea, even though move is less atomic than people think :)

**Comment by Mytherin** [comment]
Will have a go at this

**Comment by zenazn** [comment]
Thanks folks! Left a follow-up on the attached PR
