### ISSUE TITLE
[R] Tables brought to DuckDB do not show up in connection

### ISSUE THREAD

**Issue by zauster** [duckdb/duckdb#3948]
#### What happens?
I am trying to use `to_duckdb` to bring data from R to duckdb. I know that `to_duckdb` is actually a function from {arrow}, but it uses duckdb functions there, so I thought the bug report is better placed here.

I would have expected test 1-5 below to show the created (probably virtual) table at one of the connections, but no. There is also no warning or error message that something went wrong. (In tests 1-3, the object is a data.frame, does duckdb expect something arrow-ish there? In tests 4-5 the object is created from arrow, but registering the table still does not work.)
Is this a bug or am I missing something?

#### To Reproduce
```r
library(data.table)
library(dplyr)
## install.packages("https://github.com/duckdb/duckdb/releases/download/v0.4.0/duckdb_r_src.tar.gz", repos = NULL)
library(duckdb)
library(arrow)

N <- 1000
dt <- data.table(a = rnorm(N),
                 b = sample(letters, size = N, replace = TRUE))


## 1.
## `to_duckdb` creates a connection and stores the table there
test1 <- dt |>
  to_duckdb()
created_con <- options("arrow_duck_con")$arrow_duck_con
dbListTables(conn = created_con) ## no table here
dbListTables(conn = test1$src$con) ## or here (but is anyway the same connection)

## 2.
## store the table at a pre-created connection
duckdbcon = dbConnect(duckdb::duckdb(), dbdir=":memory:")
test2 <- dt |>
  to_duckdb(con = duckdbcon)
dbListTables(duckdbcon) ## no table here

## 3.
## test if duckdb register function works
duckdb::duckdb_register_arrow(duckdbcon, "dt_01", dt)
dbListTables(duckdbcon) ## no table here

## 4.
## test if it works if the object is an Arrow Dataset
write_dataset(dt, path = ".")
db <- open_dataset(sources = "./part-0.parquet")
test5 <- db |>
  to_duckdb(con = duckdbcon)
dbListTables(duckdbcon) ## no table here

## 5.
## try to register the db at the connection
duckdb::duckdb_register_arrow(duckdbcon, "dt_01", db)
dbListTables(duckdbcon) ## no table here

## X.
## register the table "explicitly"
duckdb_register(duckdbcon, "dt_test_01", dt)
dbListTables(duckdbcon) ## Success: table present
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Client: R package {duckdb}

#### Identity Disclosure:
 - Full Name: Oliver Reiter

I installed the latest version of the R package with:
`install.packages("https://github.com/duckdb/duckdb/releases/download/v0.4.0/duckdb_r_src.tar.gz", repos = NULL)`

```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_zenp-r0.3.20.so

locale:
 [1] LC_CTYPE=de_AT.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_AT.UTF-8        LC_COLLATE=de_AT.UTF-8    
 [5] LC_MONETARY=de_AT.UTF-8    LC_MESSAGES=de_AT.UTF-8   
 [7] LC_PAPER=de_AT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_AT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arrow_8.0.0       duckdb_0.4.0      DBI_1.1.3         dplyr_1.0.9      
[5] data.table_1.14.2

loaded via a namespace (and not attached):
 [1] fansi_1.0.3      assertthat_0.2.1 utf8_1.2.2       crayon_1.5.1    
 [5] R6_2.5.1         lifecycle_1.0.1  magrittr_2.0.3   pillar_1.7.0    
 [9] rlang_1.0.2      cli_3.3.0        vctrs_0.4.1      generics_0.1.2  
[13] ellipsis_0.3.2   tools_4.2.0      bit64_4.0.5      glue_1.6.2      
[17] bit_4.0.4        purrr_0.3.4      compiler_4.2.0   pkgconfig_2.0.3 
[21] tidyselect_1.1.2 tibble_3.1.7    
```

**Comment by zauster** [comment]
Including that option does not change anything: the results remain the same. (Also I am running R in Emacs+ESS and not Rstudio, does this option change anything then?)

**Comment by zauster** [comment]
Just a wild guess:

In tests 1-5, it always seems to use `duckdb_register_arrow`, which uses `rapi_register_arrow`. There the values are registered like this:
```
	cpp11::writable::list state_list = {export_funs, valuesexp, factorysexp};
	static_cast<cpp11::sexp>(conn->db_eptr).attr("_registered_arrow_" + name) = state_list;
```

`duckdb_register` (the only case where is succeeds), uses `rapi_register_df`, which registers the df like this:
```
		conn->conn->TableFunction("r_dataframe_scan", {Value::POINTER((uintptr_t)value.data())})
		    ->CreateView(name, true, true);
		static_cast<cpp11::sexp>(conn).attr("_registered_df_" + name) = value;
```
So maybe the difference lies in the connection `conn` and how it is used there?

**Comment by rsund** [comment]
This is indeed a bit confusing situation even though everything is actually working as expected.

By using `arrow::to_duckdb()` an Arrow object is handled in a special way so that DuckDB engine is used to query it with a replacement scan, i.e. no actual table (or view) is generated to the DuckDB catalog. If you want to list the registered Arrow objects, use (in test 1):
`duckdb::duckdb_list_arrow(created_con)` 

Your test3 is not working currently. So if you want to use that, change it to following:
`duckdb::duckdb_register_arrow(duckdbcon, "dt_01", arrow:::as_adq(dt))`

Replacement scan means that you can query Arrow objects even if those cannot be seen in the catalog. So for e.g. test 5, you could use `DBI::dbGetQuery(duckdbcon,"SELECT * FROM dt_01")`  and it will work even though the table is not in the DuckDB catalog.

If you want to get Arrow object also to DuckDB catalog, one way is to create a view for it (continuing test 5):
`DBI::dbExecute(duckdbcon,"CREATE VIEW dt_01_catalog AS SELECT * FROM dt_01")`
and then `DBI::dbListTables(duckdbcon)` is not empty anymore.

So I would say that this issue can be closed. Maybe some documentation or examples/guides could be added for the R client.

**Comment by zauster** [comment]
Thanks for the explanation and the pointer to the `duckdb_list_arrow` function, that cleared it up for me.

But I agree, a mention of this feature (that tables are not shown in the catalog but still already available) in the documentation would be good.

**Comment by hannes** [comment]
@pdet why did we use the replacement scans there in the first place? Seems odd.

**Comment by pdet** [comment]
The ‘’’duckdb_register_arrow’’’ shouldn't use replacement scans imo. 
Also, in python land we replaced specific object registration functions to a general one. I think we should do the same here and drop the ‘’’duckdb_register_arrow’’’ and not use replacement scans.

**Comment by hannes** [comment]
looks like it https://github.com/duckdb/duckdb/blob/master/tools/rpkg/src/database.cpp#L52
