### ISSUE TITLE
Auto-Reform JSON on type conversion

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#3962]
#### What happens?
Say I have a dataframe column of dictionaries with single-quoted strings.  If I create a table from this and convert the column to a JSON type it will not be well-formed.  Back in pandas, this can be easily resolved doing something like df.col.apply(json.dumps), but it would be nice if, when converting to the JSON type, DuckDB would try and handle this internally.

#### To Reproduce
```
import duckdb
dct = "{ \'family\': \'anatidae\', \'species': [ \'duck\', \'goose\', \'swan\', null ] }"
df = pd.DataFrame([dct], columns=['j'])
con = duckdb.connect()
con.register('df', df)
con.execute("DROP TABLE IF EXISTS example;")
con.execute("CREATE TABLE IF NOT EXISTS example AS SELECT * FROM df")
con.execute("ALTER TABLE example ALTER j SET DATA TYPE JSON")
con.execute("SELECT json(j) FROM example;").fetchdf()
```
This will throw error: `RuntimeError: Invalid Input Error: malformed JSON`

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.4.1-dev87
 - DuckDB Client: python

#### Identity Disclosure:
 - Full Name: Vincent Munos
 - Affiliation: Admolly

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by lnkuiper** [comment]
DuckDB uses the yyjson library to parse JSON, so if you get the error `malformed JSON` back, that means that yyjson is not able to parse your JSON input. If we unescape the escaped characters, the JSON you are inserting into DuckDB is this:
```json
{ 'family': 'anatidae', 'species': [ 'duck', 'goose', 'swan', null ] }
```
Which is not valid, because JSON requires double quotes for strings rather than single quotes. DuckDB will not support reading invalid JSON, so I suggest finding a different workaround.

I'd like to add that casting to the JSON type does not change the data physically, it just changes the logical type from `VARCHAR` to `JSON`. This can be useful because some functions can behave differently when interpreting a string as either `VARCHAR` or `JSON`.

**Comment by Admolly** [comment]
Hey @lnkuiper thanks for your response.  You are correct, in this case the JSON is not valid, and can be fixed quite easily using a combination of python and pandas.  I was merely suggesting, in cases where passing a dictionary through `json.loads` would be enough to make something valid JSON, it would be helpful or convenient if DuckDB could handle this internally.  Obviously, not a need-to-have feature by any stretch of the imagination, but potentially helpful.

**Comment by Alex-Monahan** [comment]
Hi @Admolly ! A work in progress PR (#3985 ) will take a Python dict and convert it to a DuckDB struct, so that may work instead!

**Comment by Admolly** [comment]
Hey @Alex-Monahan, thanks for the heads up.  That could indeed work I think.  Also wanted to get your thoughts on another proposal I made [here](https://github.com/duckdb/duckdb/discussions/3983).  Thought it might be a good candidate for "Friendlier SQL".

**Comment by Alex-Monahan** [comment]
> Hey @Alex-Monahan, thanks for the heads up. That could indeed work I think. Also wanted to get your thoughts on another proposal I made [here](https://github.com/duckdb/duckdb/discussions/3983). Thought it might be a good candidate for "Friendlier SQL".

Thank you for that suggestion! Unfortunately I am just the docs guy, so I can't comment on how feasible it would be to add that feature to CTE's. From my very limited understanding, that portion of the code is made pretty complex to handle recursive CTEs.

**Comment by Admolly** [comment]
Understood.  Well, it was worth a try!  Thanks for the quick response.
