### ISSUE TITLE
Using of `random()` in CTE pipeline results in unexpected/incorrect results

### ISSUE THREAD

**Issue by RobinL** [duckdb/duckdb#3974]
#### What happens?

If you use `random()` as part of a CTE pipeline, this can result in unexpected, perhaps incorrect, results. 

Specifically, where use of `random()` should result in deterministic results, it does not.  (Though I'm totally willing to accept that this is intended behaviour, or at least unavoidable in parallelised workflows!).

#### To Reproduce

The printed number is different every time, but it should always be `sum(list(range(100)))`

```
import pandas as pd 
import duckdb
con = duckdb.connect(":memory:")

con.register("df", pd.DataFrame({"col1": range(100)}))

sql = """
with a as (
    select col1, ceiling(random()*2) ran_col 
    from df
),
b as (
    select sum(col1) as partial_sum
    from a 
    where ran_col = 1
    union all
    select sum(col1) as partial_sum
    from a 
    where ran_col = 2
)
select sum(partial_sum) as sum_col
from b

"""
for i in range(10):
    df = con.execute(sql).fetch_df()
    print(df.iloc[0,0])
```

#### Environment (please complete the following information):
 - OS: iOS
 - DuckDB Version: 0.4.0
 - DuckDB Client:  Python

#### Identity Disclosure:
 - Full Name: Robin Linacre
 - Affiliation: Ministry of Justice/Open source maintainer of [Splink](https://github.com/moj-analytical-services/splink/)

**Comment by RobinL** [comment]
For what it's worth, I note the same code on Spark results in the same answer (of `4950 = sum(list(range(100)))`) every time:
```
from pyspark.context import SparkContext
from pyspark.sql import SparkSession
import pandas as pd 
sc = SparkContext.getOrCreate()
spark = SparkSession(sc)

pd_df = pd.DataFrame({"col1": list(range(100))})
df = spark.createDataFrame(pd_df)
df.createOrReplaceTempView("df")

sql = """
with a as (
    select col1, ceiling(random()*2) ran_col 
    from df
),
b as (
    select sum(col1) as partial_sum
    from a 
    where ran_col = 1
    union all
    select sum(col1) as partial_sum
    from a 
    where ran_col = 2
)
select sum(partial_sum) as sum_col
from b

"""
for i in range(10):
    df = spark.sql(sql).toPandas()
    print(df.iloc[0,0])
```

**Comment by omo** [comment]
I think this is because the view is inlined (vs materialized) in duckdb so the random is evaluated separately for each select in b.
Probably the random has some shared seed for each scope.

**Comment by dwreeves** [comment]
For anyone who stumbles upon this in the future:

Here is a minimally reproducible example of how DuckDB handles multiple references to a CTE involving randomness:

```sql
with r as (select random() as n)
select * from r
union all
select * from r
```

^ Here, it recalculates `random()` twice, so you get two different numbers.

Many db engines (e.g. Snowflake) do not behave this way, e.g. run the same query in Snowflake and it will output the same number twice.

**However, there is a very simple fix:** adding `materialized` to the CTE ensures the CTE gets calculated exactly once:

```sql
with r as materialized (select random() as n)
select * from r
union all
select * from r
```

And so the above query will output the same number twice, in line with the behavior of other SQL engines.

More information in the DuckDB docs on CTEs: https://duckdb.org/docs/sql/query_syntax/with.html
