### ISSUE TITLE
Error Handling in Expression Execution

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#398]
Error handling

- Errors can potentially be ignored, e.g. error OR true
- Errors are rare, it is fine if error handling is slow
- unordered_map<sel_t, string> errors (or similar)
- Errors return NULL?
- Normal functions just propagate errors downward for tuples
- Errors that make it to the bottom result in an exception or so (as that means we were not able to get a "correct" value for that tuple) -> there can be a flag to not do that, e.g. if we perform CAST('x' as INTEGER) the result will just be NULL
- In AND/OR, we continue execution of errors in other branches, if we have ERROR AND FALSE, we know the result is false and can remove the error for that tuple
- Have to consider nested AND/OR expressions

**Comment by hannesmuehleisen** [comment]
We might also consider setting the result of failing expressions to `NULL` everywhere. This simplifies error bubbling.

**Comment by hannes** [comment]
These are less issues but future features. Closing here.
