### ISSUE TITLE
Cursor() unable to find Pandas df registered in parent connection

### ISSUE THREAD

**Issue by wenboz1122** [duckdb/duckdb#3980]
#### What happens?
Same issue to https://github.com/duckdb/duckdb/issues/1736 The cursor used to work well with v0.3.4 but the issue happens again with v0.4.0. Seems a regression due to recent changes. We have to use cursor() instead of the connection object itself because our generic interface also supports other database APIs and cursor() is a common practice that follows https://peps.python.org/pep-0249/, which is also useful for parallized queries. 

#### To Reproduce
See https://github.com/duckdb/duckdb/issues/1736

#### Environment (please complete the following information):
 - OS: (e.g. iOS)
 - DuckDB Version: [0.4.0]
 - DuckDB Client: [Python 3.9]

#### Identity Disclosure:
 - Full Name: [Wenbo Zhang]

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

**Comment by pdet** [comment]
Hmm, cursors now acquire a new connection to allow for multithreading in the Python API, it's possible they are not inheriting the registered objects properly. Will have a look in a bit.

**Comment by Mytherin** [comment]
I think cursors need to stay as separate connections. Perhaps an alternative solution would be to add support for creating "global" temporary objects in the catalog. This way when registering a data frame it could be created as a global temporary view, rather than as a connection-local temporary view.

**Comment by pdet** [comment]
> I think cursors need to stay as separate connections. Perhaps an alternative solution would be to add support for creating "global" temporary objects in the catalog. This way when registering a data frame it could be created as a global temporary view, rather than as a connection-local temporary view.

I think this can be problematic in all sorts of ways with the object registration still. For example:

```python
con = duckdb.connect()
con.register(df_1, 'df_1')
cur = con.cursor() # cur should be able to see df_1
cur.register(df_2, 'df_2') # Now both con and cur can see df_2, but cur holds the reference to df_2
cur.close()
del df_2
# at this point con still has a view of df_2 but df_2 has been properly deleted since its duckdb reference died with cur
con.query("select * from df_2") # woopsie
```

With my cursor suggestion, underneath they could still have a different duckdb connection. The main difference is that we don't output PyConnections from cursor calls and that PyCursors don't have registration, unregistration, and cursor methods.
