### ISSUE TITLE
httpfs does not treat HTTP headers as case-insensitive

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#3991]
[HTTP header names are case-insensitive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers).

Unfortunately, it seems like httpfs treats headers as case-sensitive. In particular, httpfs requires the [content length header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) to be exactly spelled `Content-Length`, and not e.g., `content-length`. This header is used to determine the length of an httpfs file, I believe using this piece of code:

https://github.com/duckdb/duckdb/blob/da9ee490df829a96bfbcfcd737f95f8dbc707d0a/extension/httpfs/httpfs.cpp#L356

If a `content-length` (lowercase) header is returned by the server, I get the following error from duckdb:

`Invalid Input Error: File 'http://localhost:1988/cache/c7832f09d76489e8' too small to be a Parquet file`

I believe this specific error is because duckdb thinks the file has length 0 (because it is looking at the wrong header) here:
https://github.com/duckdb/duckdb/blob/da9ee490df829a96bfbcfcd737f95f8dbc707d0a/extension/parquet/parquet_reader.cpp#L62-L64

This is affecting me in a way that's very difficult to work around, because it's common practice for HTTP server libraries (in my case, in the nodejs ecosystem) to normalize header names by lower-casing them.

Duckdb 0.4.0, Mac 12.4. Reproduces in the duckdb CLI

**Comment by hannes** [comment]
that `headers[` access there into the multi-map is incorrect, I have opened a PR that should fix it. Can you maybe give it a try in the branch?

**Comment by zenazn** [comment]
Looks like that PR fails to build, but it definitely looks plausible to me!
