### ISSUE TITLE
PhysicalType::TIME64 unused

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#4013]
When working on timestamp/time/date conversion related functionality, I came across the PhysicalType::TIME64, introduced 2 years ago:
```c++
	/// Time as signed 64-bit integer, representing either microseconds or
	/// nanoseconds since midnight
	TIME64 = 20,
```
Doing a search for `PhysicalType::TIME64` came up with no results of it being set or returned anywhere, but as far as I know we do properly support microseconds in TIME values.  
So should this type be removed or is there functionality that might be broken as a result of not using this type anywhere?

**Comment by Tishj** [comment]
It actually seems like PhysicalType::TIME32 is also not used

It's returned by this function
```c++
template <class T>
PhysicalType GetTypeId() {
	if (std::is_same<T, bool>()) {
		return PhysicalType::BOOL;
	} else if (std::is_same<T, int8_t>()) {
		return PhysicalType::INT8;
	} else if (std::is_same<T, int16_t>()) {
		return PhysicalType::INT16;
	} else if (std::is_same<T, int32_t>()) {
		return PhysicalType::INT32;
	} else if (std::is_same<T, int64_t>()) {
		return PhysicalType::INT64;
	} else if (std::is_same<T, uint8_t>()) {
		return PhysicalType::UINT8;
	} else if (std::is_same<T, uint16_t>()) {
		return PhysicalType::UINT16;
	} else if (std::is_same<T, uint32_t>()) {
		return PhysicalType::UINT32;
	} else if (std::is_same<T, uint64_t>()) {
		return PhysicalType::UINT64;
	} else if (std::is_same<T, hugeint_t>()) {
		return PhysicalType::INT128;
	} else if (std::is_same<T, date_t>()) {
		return PhysicalType::DATE32;
	} else if (std::is_same<T, dtime_t>()) {
		return PhysicalType::TIME32;
	} else if (std::is_same<T, timestamp_t>()) {
		return PhysicalType::TIMESTAMP;
	} else if (std::is_same<T, float>()) {
		return PhysicalType::FLOAT;
	} else if (std::is_same<T, double>()) {
		return PhysicalType::DOUBLE;
	} else if (std::is_same<T, const char *>() || std::is_same<T, char *>() || std::is_same<T, string_t>()) {
		return PhysicalType::VARCHAR;
	} else if (std::is_same<T, interval_t>()) {
		return PhysicalType::INTERVAL;
	} else {
		return PhysicalType::INVALID;
	}
}
```
but it's not part of the function used to set the physical type of a `Value` - GetInternalType()
```c++
	case LogicalTypeId::TIME:
	case LogicalTypeId::TIMESTAMP:
	case LogicalTypeId::TIMESTAMP_SEC:
	case LogicalTypeId::TIMESTAMP_NS:
	case LogicalTypeId::TIMESTAMP_MS:
	case LogicalTypeId::TIME_TZ:
	case LogicalTypeId::TIMESTAMP_TZ:
		return PhysicalType::INT64;
```

**Comment by Mytherin** [comment]
The `PhysicalType` array was copied from Arrow at some point. We only use base numeric physical types (`INT8-...INT64, UINT8...UINT64, FLOAT, DOUBLE`) along with `VARCHAR`, the composite types (`STRUCT`, `LIST`, `MAP`) and `INTERVAL`. For anything else logical types are used instead that define logical types on top of physical types. Arrow instead uses physical types for anything since they do not make the distinction between logical and physical types, so there are a lot of types in there that we do not use.

Perhaps we should comment them out to indicate this, @pdet what do you think?

**Comment by pdet** [comment]
Im fine with that, maybe comment them out with a little note on the reasoning about it?

**Comment by Tishj** [comment]
Ah okay, that explains why TIME64 is unused
But the other types are "used" in that they are returned by GetTypeId()
But those aren't returned by GetInternalType()

For context:
```c++
	} else if (std::is_same<T, date_t>()) {
		return PhysicalType::DATE32;
	} else if (std::is_same<T, dtime_t>()) {
		return PhysicalType::TIME32;
	} else if (std::is_same<T, timestamp_t>()) {
		return PhysicalType::TIMESTAMP;
```
all of these are actually covered by INT64:
```
	case LogicalTypeId::TIME:
	case LogicalTypeId::TIMESTAMP:
	case LogicalTypeId::TIMESTAMP_SEC:
	case LogicalTypeId::TIMESTAMP_NS:
	case LogicalTypeId::TIMESTAMP_MS:
	case LogicalTypeId::TIME_TZ:
	case LogicalTypeId::TIMESTAMP_TZ:
		return PhysicalType::INT64;
```

**Comment by Mytherin** [comment]
They are probably there by accident and should be removed from there.

**Comment by Tishj** [comment]
> The `PhysicalType` array was copied from Arrow at some point. We only use base numeric physical types (`INT8-...INT64, UINT8...UINT64, FLOAT, DOUBLE`) along with `VARCHAR`, the composite types (`STRUCT`, `LIST`, `MAP`) and `INTERVAL`. For anything else logical types are used instead that define logical types on top of physical types. Arrow instead uses physical types for anything since they do not make the distinction between logical and physical types, so there are a lot of types in there that we do not use.
> 
> Perhaps we should comment them out to indicate this, @pdet what do you think?

To add to this list, when looking at `GetInternalType`, we also use the following:
- BOOL
- BIT
- INVALID
- UNKNOWN
