### ISSUE TITLE
jdbc setFetchSize not work

### ISSUE THREAD

**Issue by xiongshihui** [duckdb/duckdb#4020]
#### What happens?
jdbc,setFetchSize() do not work.  
I want to read parquet file  in batches.

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.

#### Environment (please complete the following information):
 - OS: windows 10
 - DuckDB Version: 0.4.0
 - DuckDB Client: 0.4.0
#### Identity Disclosure:
 - Full Name: [e.g. John Doe]
 - Affiliation: [e.g. Oracle]

**Comment by hannes** [comment]
DuckDB internally uses a fetch size of STANDARD_VECTOR_SIZE (currently 1024). There is no point in changing that in the JDBC client. Rest assured the transformation will happen in batches already.
