### ISSUE TITLE
Presence of foreign key triggers primary key error on UPDATE statement

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#4023]
#### What happens?

`UPDATE ... SET ... FROM ... WHERE ...` fails with an error message referencing primary keys if a foreign key is defined in the table.

#### To Reproduce

```sql
CREATE TEMPORARY TABLE tf_1 (
  a integer,
  PRIMARY KEY (a)
);
CREATE TEMPORARY TABLE tf_2 (
  c integer, d integer,
  PRIMARY KEY (c),
  FOREIGN KEY (d) REFERENCES tf_1 (a)
);
INSERT INTO tf_1 VALUES (2);
INSERT INTO tf_1 VALUES (3);
INSERT INTO tf_2 VALUES (1, 2);

CREATE TEMPORARY TABLE tf_2x (c varchar(1), d integer);
INSERT INTO tf_2x VALUES (1, 3);

UPDATE "tf_2"
SET "d" = "...y"."d"
FROM "tf_2x" AS "...y"
WHERE ("...y"."c" = "tf_2"."c");

SELECT * FROM tf_2;
```

```
Error: near line 17: Constraint Error: Constraint Error: duplicate key "c: 1" violates primary key constraint
┌───┬───┐
│ c │ d │
├───┼───┤
│ 1 │ 2 │
└───┴───┘
```

Successful example, same but without the foreign key:

```sql
CREATE TEMPORARY TABLE tf_2 (
  c integer, d integer,
  PRIMARY KEY (c)
);
INSERT INTO tf_2 VALUES (1, 2);

CREATE TEMPORARY TABLE tf_2x (c varchar(1), d integer);
INSERT INTO tf_2x VALUES (1, 3);

UPDATE "tf_2"
SET "d" = "...y"."d"
FROM "tf_2x" AS "...y"
WHERE ("...y"."c" = "tf_2"."c");

SELECT * FROM tf_2;
```

```
┌───┬───┐
│ c │ d │
├───┼───┤
│ 1 │ 3 │
└───┴───┘
```

#### Environment (please complete the following information):

 - OS: macOS
 - DuckDB Version: 4d39f040c115177d7d00b5dd26b3306193f90149
 - DuckDB Client: CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Related to #1631, any update to a column with an index becomes a delete + insert, which then causes the primary key constraint to be violated.

**Comment by krlmlr** [comment]
Thanks. The `d` column doesn't have an index, though. Did you mean "any update to a column with a table"?

**Comment by Mytherin** [comment]
It does have an index. Foreign key constraints result in index creation implicitly, as the index is required to check that the foreign key is valid.

**Comment by krlmlr** [comment]
Thanks for the clarification.
