### ISSUE TITLE
Segmentation fault when querying from a view based on a deallocated relation

### ISSUE THREAD

**Issue by JakobGM** [duckdb/duckdb#4025]
#### What happens?

This bug is a bit intricate. Under certain conditions, where a view has been created from a dataframe relation that has gone out of scope, a query can result in a segmentation fault. This bug is best described in form of examples:

#### To Reproduce

The following code will segfault on the last line:

```python
import duckdb
import pandas as pd

df = pd.DataFrame({"column_name": [1, 2]})

db = duckdb.connect()
db.from_df(df).project("column_name").create_view("view_name")
db.query("select * from view_name")
```

While the following change will make it _not_ crash:

```diff
 df = pd.DataFrame({"column_name": [1, 2]})
 
 db = duckdb.connect()
-db.from_df(df).project("column_name").create_view("view_name")
+relation = db.from_df(df)
+relation.project("column_name").create_view("view_name")
 db.query("select * from view_name")
```

That is, the only difference being that `db.from_df(df)` has been assigned to a variable `relation`, before `.project(...).create_view(...)` is invoked. This makes me think that assigning `db.from_df(df)` to a variable makes the relation not go out of scope, the deallocation method is therefore not invoked, and we therefore "fix" the issue.

This hypothesis is made more clear by changing the last working code example again in order to make it break:

```diff
 db = duckdb.connect()
 relation = db.from_df(df)
 relation.project("column_name").create_view("view_name")
+del relation
 db.query("select * from view_name")
```

#### Environment (please complete the following information):
 - OS: Linux (tested on ARM and x86)
 - DuckDB Version: 0.4.0 + 0.4.1.dev223
 - DuckDB Client: Python

#### Identity Disclosure:
 - Full Name: Jakob Gerhard Martinussen
 - Affiliation: Oda

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?** Yes
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?** Yes

**Comment by Tishj** [comment]
The description is spot on, that is exactly what was happening.
The PR I made should fix this, so we can close this issue.
