### ISSUE TITLE
TIME Value result -> Pandas Dataframe does not return datetime.time

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#4026]
#### What happens?  

When the result is of type TIME, exporting this result to a dataframe converts the value to a string, instead of an object of type `datetime.time`  
```py
time = duckdb.query("SELECT make_time(23, 1, 34.234345) AS '0'").df()
----
'23:01:34.234345'
```
Whereas exporting it as a tuple through `fetchone()` does create the expected result:
```py
time = duckdb.query("SELECT make_time(23, 1, 34.234345) AS '0'").fetchone()
----
(datetime.time(23, 1, 34, 234345),)
```
#### Environment (please complete the following information):
 - OS: (e.g. iOS)
 - DuckDB Version: [master:latest]
 - DuckDB Client: [Python]

#### Identity Disclosure:
 - Full Name: [Thijs Bruineman]
 - Affiliation: [DuckDBLabs]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by alemartinello** [comment]
Re-upping this with respect to dates out of bounds for pandas datetimens[64] format (i.e. https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-oob)

Shortly, one gets different output from queries depending on the output method, .fetchall() or .fetchdf()/df(). 
With out of bounds values, e.g. '9999-12-31', .fetchdf()/df() return wrong values due to datetime conversion.

Tested on 
Windows
duckdb-0.6.2.dev1934
python client

```
>>> import duckdb
>>> c = duckdb.connect(':memory:')
>>> c.execute("create table test (date DATE)")
<duckdb.DuckDBPyConnection object at 0x000002293E4816B0>
>>> c.execute("INSERT INTO TEST VALUES ('9999-12-31')")
<duckdb.DuckDBPyConnection object at 0x000002293E4816B0>

>>> c.execute("select * from test").fetchall()
[(datetime.date(9999, 12, 31),)]

>>> c.execute("select * from test").df(date_as_object=True)
         date
0  1816-03-29

>>> c.execute("select * from test").df()
                           date
0 1816-03-29 05:56:08.066277376
```

**Comment by Tishj** [comment]
I'm looking into this now, but I'm not sure what the best action to take is

We use the same logic for both NumPy and Pandas here currently.
Pandas has a way to deal with this with the Period type, though that would likely be an `object`, which requires sampling the column before conversion to detect which physical type in the array to use.

But Numpy has no way of dealing with this, so maybe we just want to throw here in the case of `fetchnumpy`

**Comment by Mytherin** [comment]
Either throwing or returning a correct datetime seems fine to me. Supporting these date ranges is likely not particularly important but we should at the very least catch the overflow.

**Comment by alemartinello** [comment]
Hi both, 

I understand that at least the error is catched atm, but I'd still like to raise the issue of how to work on these date ranges - which are not uncommon in e.g. credit databases to signal annuities/credit in perpetuity.

As the issue now returns a `ConversionError`, it means even exploring tables with these date ranges is impossible through the python client, unless one works around it using `fetchall`.

Is there no plan to support these date ranges, e.g. through pandas `Period` type?

Thanks

**Comment by suchanlee** [comment]
Is this actually fixed? I still get `str` as the column type for time:

```python
time = duckdb.query("SELECT make_time(23, 1, 34.234345) AS '0'").df()
print(type(time.get('0')[0]))

# outputs: <class 'str'>
```

tested on v0.10.1

**Comment by szarnyasg** [comment]
@suchanlee thanks for letting us know, we'll take a look.

**Comment by suchanlee** [comment]
Thanks for the quick response @szarnyasg
