### ISSUE TITLE
DuckDB freezes when creating a view with a `column IS NULL` filter

### ISSUE THREAD

**Issue by JakobGM** [duckdb/duckdb#4030]
#### What happens?

When using the Python relational API, the python interpreter will create a deadlock when creating a view using `DuckDBPyRelation.filter("column_name is null")`.

#### To Reproduce

The following code will freeze on the last line:

```py
import duckdb

db = duckdb.connect()
relation = db.query("select 1 as a")
filtered_relation = relation.filter("a is null")
filtered_relation.create_view("view_name")
```

#### Environment (please complete the following information):
 - OS: Linux / MacOS
 - DuckDB Version: `0.4.0` or later (including `duckdb-0.4.1.dev223`)
 - DuckDB Client: Python

#### Identity Disclosure:
 - Full Name: Jakob Gerhard Martinussen
 - Affiliation: Oda

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Tishj** [comment]
It's an infinite loop inside of `Relation::GetAllDependencies()`
caused by a circular `ChildRelation()`

**Comment by Tishj** [comment]
Ah, it was a simple fix, GetAllDependencies was not following the child pointer
