### ISSUE TITLE
duckdb_result_error invalid pointer

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#4034]
#### What happens?
The pointer returned by duckdb_result_error is invalid and doesn't point to the error message

#### To Reproduce
Execute a query that fails and try to get an error message

#### Environment (please complete the following information):
 - OS: Only Linux and Mac
 - 0.4.0
 - DuckDB Client: .Net

#### Identity Disclosure:
 - Full Name: Giorgi Dalakishvili
 - Affiliation: NA

I'm building a .Net wrapper for DuckDB and I have an [issue reading error message ](https://github.com/Giorgi/DuckDB.NET/issues/37) only on Linux and Mac.

I don't know if the issue is in DuckDB or in my C# code but I double-checked the code and it looks correct. I also create a simple Linux shared library and I could read the string returned by it: [Native text to C# ](https://gist.github.com/Giorgi/3027908367e4d939f09e9bf8cd86478d)

I saw in git that the error message was cloned with `strdup` in the past so maybe that is needed to keep the pointer valid?

**Comment by Tishj** [comment]
If I found the correct function, there's some inline documentation about it
```c++
/*!
Returns the error message contained within the result. The error is only set if `duckdb_query` returns `DuckDBError`.

The result of this function must not be freed. It will be cleaned up when `duckdb_destroy_result` is called.

* result: The result object to fetch the nullmask from.
* returns: The error of the result.
*/
DUCKDB_API const char *duckdb_result_error(duckdb_result *result);
```

**Comment by Mytherin** [comment]
Thanks for the report! Could you perhaps try to construct a minimal C example that showcases the issue?

**Comment by Tishj** [comment]
Hmm and you call the function before calling `duckdb_destroy_result` ?

**Comment by Tishj** [comment]
```c++
duckdb_state duckdb_translate_result(unique_ptr<QueryResult> result_p, duckdb_result *out) {
	auto &result = *result_p;
	D_ASSERT(result_p);
	if (!out) {
		// no result to write to, only return the status
		return result.success ? DuckDBSuccess : DuckDBError;
	}

	memset(out, 0, sizeof(duckdb_result));

	// initialize the result_data object
	auto result_data = new DuckDBResultData();
	result_data->result = move(result_p);
	result_data->result_set_type = CAPIResultSetType::CAPI_RESULT_TYPE_NONE;
	out->internal_data = result_data;

	if (!result.success) {
		// write the error message
		out->__deprecated_error_message = (char *)result.error.c_str();
		return DuckDBError;
	}
	// copy the data
	// first write the meta data
	out->__deprecated_column_count = result.ColumnCount();
	out->__deprecated_rows_changed = 0;
	return DuckDBSuccess;
}
```
Since `result` is a unique pointer, it will get destroyed at the end of this function right?
we take the `.c_str()` of a string that is owned by the QueryResult, which is not an owning pointer, this will also be destroyed together with QueryResult at the end of this function

So we return unallocated memory, no?

**Comment by Giorgi** [comment]
@Tishj I think you are looking at the wrong code. The code for this function is:

```
const char *duckdb_result_error(duckdb_result *result) {
	if (!result) {
		return nullptr;
	}
	auto &result_data = *((duckdb::DuckDBResultData *)result->internal_data);
	return result_data.result->success ? nullptr : result_data.result->error.c_str();
}
```

**Comment by Tishj** [comment]
Yea that's retrieving the error, the code I was looking at was setting the result, and thus the error if there was one

**Comment by Giorgi** [comment]
Also, if I read the error message from `__deprecated_error_message` pointer, it works fine.

**Comment by Giorgi** [comment]
The error turned out to be in mapping in DuckDBResult. Fixed in https://github.com/Giorgi/DuckDB.NET/commit/5031ef5c0a7b0095a9a995206053e0247ec361c5
