### ISSUE TITLE
File used by another process on Tableau (cannot open file)

### ISSUE THREAD

**Issue by simonaubertbd** [duckdb/duckdb#4037]
#### What happens?
Error message on Tableau when I try to read a duckdb database with ODBC. The only process that uses it seems to be Tableau itself !

#### To Reproduce
1/Create an odbc connection to a duckdb file
![image](https://user-images.githubusercontent.com/46959192/177494021-ec49472a-e4e0-4637-8f18-b7f51f11187f.png)
![image](https://user-images.githubusercontent.com/46959192/177494048-cf1d1905-85d2-42cd-8ded-fd74f3cfab64.png)

2/Try to connect to it on Tableau
![image](https://user-images.githubusercontent.com/46959192/177494299-11001904-3632-4493-89a3-c9269890eabf.png)
![image](https://user-images.githubusercontent.com/46959192/177494501-3d8317eb-ed83-499f-a254-1d3b86bf9026.png)

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.4.0
 - DuckDB Client: ODBC

#### Identity Disclosure:
 - Full Name: Simon AUBERT
 - Affiliation: B&D

**Comment by Mytherin** [comment]
@tiagokepe could you have a look?

**Comment by simonaubertbd** [comment]
Sure.

Please note I have the same issue with Alteryx : if I try to use the odbc connection with Alteryx, I have to totally close Alteryx to free the file.
[SQL.LOG](https://github.com/duckdb/duckdb/files/9067189/SQL.LOG)

Best regards,

Simon

**Comment by djouallah** [comment]
same problem here, tried it with Tableau

**Comment by simonaubertbd** [comment]
@tiagokepe Hello. Could you have a look again please?

**Comment by Mytherin** [comment]
Could you confirm the issue is still a problem with the latest version of DuckDB (v0.8.1)?

**Comment by simonaubertbd** [comment]
Hello @Mytherin 

Yes, I can confirm that ! 
![image](https://github.com/duckdb/duckdb/assets/46959192/7a90a948-d58f-4bf0-a411-89d03aae4cf2)

Does someone managed to use it ?
Best regards,

Simon

**Comment by simonaubertbd** [comment]
Hello @Mytherin  sorry to bother you with that again. Any news?

**Comment by Mause** [comment]
What's the most recent version you've tried with?

**Comment by simonaubertbd** [comment]
@Mause Ok, I made some progress :
I thought the error message comes from the fact that it is a folder that's linked to my onedrive. I copy/paste on my c:/ outside of my onedrive repository and I still have the message. here are my odbc trace logs
[SQL.LOG](https://github.com/duckdb/duckdb/files/13988964/SQL.LOG)

**Comment by maiadegraaf** [comment]
The ODBC driver now accepts config arguments, including setting the database to `READ_ONLY` mode, as of https://github.com/duckdb/duckdb/pull/10692.  This could potentially be a solution here.
