### ISSUE TITLE
LogicalJoin::left_projection_map seems unused

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#405]
LogicalJoin::GetColumnBindings() uses left_projection_map and right_projection_map to return the vector of used ColumnBinding.

After experimenting a bit with LogicalComparisonJoins e.g. the following query:
```
CREATE TABLE test1 (a int, b varchar);
CREATE TABLE test2 (c int, d varchar);
CREATE TABLE test3 (e int, f varchar);
CREATE TABLE test4 (g int, h varchar);
SELECT t1.b, t4.h
FROM test1 AS t1, test2 AS t2, test3 AS t3, test4 AS t4
WHERE t1.a = t2.c AND t2.d = t3.f AND t3.e = t4.g;
```

And printing the contents of the left and right projection maps, I found that the left projection map is always empty - causing it to always project all columns.
The columns are removed later by RemoveUnusedColumns in the Optimizer.
Is there a reason for this?

Having a real left projection map would be very helpful with my ReOptimization approach!

**Comment by Mytherin** [comment]
Thanks for the issue! The `left_projection_map` is not actually implemented in the physical join operators yet, and hence is currently never used. Indeed this issue should be fixed.

**Comment by hannesmuehleisen** [comment]
@lnkuiper can this be closed?

**Comment by lnkuiper** [comment]
@hannesmuehleisen yeah, this was something I needed for my master thesis, which is long done. We have a comment about this at `join_order_optimizer.cpp:105`, no need for this to be an issue.
