### ISSUE TITLE
strptime uses wrong timezone

### ISSUE THREAD

**Issue by kiliconsult** [duckdb/duckdb#4055]
#### What happens?
I am converting a user input to a epoch value like this:

SELECT date_part('epoch', strptime('2022-06-06 00:00 +0200', '%Y-%m-%d %H:%M  %z'))*1000;

I would expect +0200 to be the offset from UTC and return:

GMT: Sunday 5. June 2022 22:00:00
6. june 2022 kl. 00:00:00 [GMT+02:00]DST

But it returns:

GMT: Monday 6. June 2022 00:00:00
Which is
6. june 2022 kl. 02:00:00 [GMT+02:00]DST

This is not an issue in 0.3.2 and 0.3.3. Only in 0.4.0.

#### To Reproduce
Just use SELECT date_part('epoch', strptime('2022-06-06 00:00 +0400', '%Y-%m-%d %H:%M  %z'))*1000;

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.4.0
 - DuckDB Client: DBeaver and java jdbc

#### Identity Disclosure:
 - Full Name: Kim Madsen
 - Affiliation: Ramboll

**Comment by hawkfish** [comment]
Hi @kiliconsult - I'm a bit confused here. `DATE_PART('epoch', ...)` returns a number not a timestamp?

**Comment by hawkfish** [comment]
When I try this query on head:

```sql
select strptime('2022-06-06 00:00 +0200', '%Y-%m-%d %H:%M %z');
```
I get `2022-06-05 22:00:00+00`, which is what I would expect (an instant at the corresponding time in GMT).

**Comment by kiliconsult** [comment]
Hi @hawkfish 

> Hi @kiliconsult - I'm a bit confused here. `DATE_PART('epoch', ...)` returns a number not a timestamp?
Yeah. I converted the epoch to something readable

DBeaver actully gives me an exception when I run a select on strptime directly.

![image](https://user-images.githubusercontent.com/46249372/177936505-e1e5e4b6-18fb-4d02-8104-1e2aedea2996.png)


But it allows me run it when wrapped in date_part.
![image](https://user-images.githubusercontent.com/46249372/177936691-ac5b8dd3-d5a9-4618-8bbf-754661295bf6.png)

**Comment by hawkfish** [comment]
Sounds like DBeaver isn't binding to our `TIMESTAMP` type correctly. If you are returning the epoch, be aware that it is an integral number of seconds and will lose fractional parts.  And it will be seconds since `1970-01-01 00:00:00+00`.

**Comment by hawkfish** [comment]
When you wrap the call in `date_part`, the result of `strptime` is now handled internally by DuckDB and the result is an integer, which DBeaver seems to handle. I would say this is a DBeaver bug.
