### ISSUE TITLE
Missing values returned as float NaN in non-numeric columns

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#4066]
If I try to query a parquet file having columns that are for example list of strings, missing values in those columns are outputted as float NaNs instead of the corresponding nullable type (`None` or `pd.NA` in the case of python).

Example:
```python
import numpy as np, pandas as pd, duckdb
pd.DataFrame({
    "col1" : [["a"], ["a","b"], ["a","b","c"], None]
}).to_parquet("df.parquet")
duckdb.query("select * from read_parquet('df.parquet')").to_df()
```
![Screenshot_20220709_110532](https://user-images.githubusercontent.com/11860098/178099363-c27065d7-5775-4146-8ebb-c35c2ccbee9b.png)

**Comment by Tishj** [comment]
This should be fixed once #3985 gets merged :)

**Comment by david-cortes** [comment]
In the parquet file, they are lists of strings, thus reading them should not yield float NaN.

**Comment by Tishj** [comment]
Ah I see, you're right, the PR I mentioned has nothing to do with it.

**Comment by Tishj** [comment]
On further inspection, I don't think there is any bug here.

NaN is what Pandas uses to represent NULL inside a dataframe, if you don't export this to a dataframe the value will be NULL like you expect, but since the output is to a dataframe, this is the expected result.

**Comment by david-cortes** [comment]
> On further inspection, I don't think there is any bug here.
> 
> NaN is what Pandas uses to represent NULL inside a dataframe, if you don't export this to a dataframe the value will be NULL like you expect, but since the output is to a dataframe, this is the expected result.

That is not correct - columns of `object` dtype can have any arbitrary value such as `None`, `np.nan`, or `pd.NA`, all of which would evaluate to `True` under `pd.isnull`, and internally, pandas uses bitmasks for missingness in their nullable dtypes.

Picture:
![Screenshot_20220709_131439](https://user-images.githubusercontent.com/11860098/178103314-aa902ccb-3cf3-4bb1-bba5-ac6ce48f8b77.png)

Among the alternatives (`None`, `pd.NA`, `np.nan`), I'd say float NaN would be the least correct option to represent missing values.

**Comment by Tishj** [comment]
I realized that and that's why I deleted my comment, I apologize.

So what you're asking in this issue is to change the type of value used to indicate "missing" based on the type of the surrounding data?

One problem I see with this in particular is pd.NA, as it is currently still marked as an experimental feature, and I have seen cases where it could cause existing code to break. Not to mention that the implementation of the feature could still change at any time.

Could you explain why you think this change is important?
Like you said all of them behave the same under `pd.isnull` and isn't there benefit to having one specific value used to indicate "missing", rather than multiple?

**Comment by david-cortes** [comment]
Among other reasons, because (a) series and dataframes returned by pandas operations would have `None` or `pd.NA` values for this kind of column, but not `np.nan`, (b) code that is made to work with python object types (such as lists of strings) typically uses base python types (`None` in this case), (c) NaN is typically the result of some incorrect mathematical operation such as division by zero, but in this case there is no mathematical operation involved.

Having duckdb return `None` in this case would make it a lot easier to switch an existing codebase from e.g. polars to duckdb.

**Comment by alexander-beedie** [comment]
Been getting to grips with `duckdb` over the last few days, and I confess that I gently cried over my coffee when I saw float NaN values coming back in string columns (in my case via the `duckdb-engine` wrapper for python's sqlalchemy lib) ;) 

Would be _great_ if we got back `None` in this case. Float values turning up in what should nominally be string data can cause quite a few issues, and often will result in client code having to check every single returned value for NaN, which is a bit painful. 

(This issue is most noticeable when you are querying a pandas frame, but don't necessarily want the data to _stay_ as a pandas frame). Thanks!

**Comment by Alex-Monahan** [comment]
Does this still occur on the latest master branch? Some improvements have been made recently!

**Comment by alexander-beedie** [comment]
> Does this still occur on the latest master branch? Some improvements have been made recently!

Compiling it now to find out... ;)

**Comment by alexander-beedie** [comment]
**Update:** compiled duckdb from latest `master` (version shows in python as 'v..1-dev') and I can confirm I'm still seeing NaN values instead of None in string cols. 

Simple repro/example:

```python
import duckdb as dd
import pandas as pd

# create test data
df = pd.DataFrame( 
    data = [['abc',123],[None,345],['xyz',567]], 
    columns = ['strcol','intcol'],
)
df
#   strcol  intcol
# 0    abc     123
# 1   None     345         # << value in DataFrame is <None>
# 2    xyz     567

db = dd.from_df( df )
db.types
# ['VARCHAR', 'BIGINT']    # << duckdb knows it's a string col

db.df()
#   strcol  intcol
# 0    abc     123
# 1    NaN     345         # << returns a float <NaN> in the string col
# 2    xyz     567

**Comment by david-cortes** [comment]
> Hey, just curious if there was ever a fix for this. I'm seeing the same thing -- I have a string column with empty values that return nan, and then the .df() gives me an object dtype on the other side (instead of string).

Although it's not actually fixed, it's possible to get the intended results in a rather inefficient route by first outputting as polars and converting that to pandas (e.g. `duckdb.query(<>).pl().to_pandas()`).

**Comment by nsthorat** [comment]
Makes sense, I ended up doing this which should be a bit faster, but obviously is funky since np.nan shouldn't be in a string / object column.

```py
if is_object_dtype(df[column]):
  df[column].replace(np.nan, None, inplace=True)
```

**Comment by Mytherin** [comment]
I had a look at this, and this issue appears to come from Pandas itself. DuckDB converts to Pandas by creating masked numpy arrays, and then calling `pd.DataFrame.from_dict`, e.g.:

```sql
import duckdb
np = duckdb.query("SELECT 'hello' AS str UNION ALL SELECT NULL").fetchnumpy()
print(np)
# {'str': masked_array(data=['hello', --],
#              mask=[False,  True],
#        fill_value='?',
#             dtype=object)}
print(pd.DataFrame.from_dict(np))
#      str
# 0  hello
# 1    NaN
```

To fix this we might need to construct the DataFrame in a different manner - but we should also consider reporting this to Pandas as this seems like odd behavior.

**Comment by nsthorat** [comment]
I filed an issue on pandas: https://github.com/pandas-dev/pandas/issues/51872
