### ISSUE TITLE
Python insert array with first value of `None` fails

### ISSUE THREAD

**Issue by saulpw** [duckdb/duckdb#4073]
#### What happens?

Python insert array with first (but not only) value of `None` fails.

#### To Reproduce

```
import duckdb
con = duckdb.connect()
con.execute('CREATE TABLE t (x INT[])')
con.execute('INSERT INTO t VALUES (?)', ([None, 1, 2],))
```

Error message is:
```
RuntimeError: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Invalid Input Error: Failed to cast value: Unimplemented type for cast (BIGINT -> NULL)
```

Note that these similar statements work just fine:

```
con.execute('INSERT INTO t VALUES ([NULL, 1, 2])')  # pure SQL
con.execute('INSERT INTO t VALUES (?)', ([0, None, 2],))  # None as second value
con.execute('INSERT INTO t VALUES (?)', ([None],))  # None as only value
con.execute('INSERT INTO t VALUES (?)', ([],))  # no values
```

#### Environment (please complete the following information):

 - OS: Linux
 - DuckDB Version: 0.4.0
 - DuckDB Client: Python

#### Identity Disclosure:

 - Full Name: Saul Pwanson
 - Affiliation: Voltron Data

**Comment by Tishj** [comment]
Hi there,

Looks like this issue is caused by a bug in TransformPythonValue.

In my most recent PR (#3985) I have made some changed to TransformPythonValue to better handle nested types.
Running your query on my branch produces this result:
```py
import duckdb
con = duckdb.connect()
con.execute('CREATE TABLE t (x INT[])')
con.execute('INSERT INTO t VALUES (?)', ([None, 1, 2],))

res = con.query('SELECT * FROM t').fetchall()
print(res)
```
```
[([None, 1, 2],)]
```

**Comment by saulpw** [comment]
Thanks @Tishj, glad to see it's already in progress!  Looking forward to seeing it merged.

**Comment by Mause** [comment]
@saulpw are you able to retest on the latest master?

**Comment by hannes** [comment]
This is working fine on master
