### ISSUE TITLE
ORDER BY <x> ASC now defaults to NULLS FIRST

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#4081]
In the bleeding edge there is a new regression.

```
  SELECT 
      a.v
    FROM (select UNNEST([1,2,NULL]) v ) a 

┌───┐
│ v │
├───┤
│ 1 │
│ 2 │
│   │
└───┘
```

```
  SELECT 
      a.v
    FROM (select UNNEST([1,2,NULL]) v ) a 
    ORDER BY 1 ASC

┌───┐
│ v │
├───┤
│   │
│ 1 │
│ 2 │
└───┘
```

**Comment by Mytherin** [comment]
Thanks for the report!

DuckDB has always defaulted to `NULLS FIRST` to mimic SQLite's behavior. Are you sure this is a regression?

You can change the default null ordering as follows:

```sql
SET default_null_order='NULLS LAST';
 SELECT 
      a.v
    FROM (select UNNEST([1,2,NULL]) v ) a 
    ORDER BY 1 ASC;
┌──────┐
│  v   │
├──────┤
│ 1    │
│ 2    │
│ NULL │
└──────┘
```

**Comment by lloydtabb** [comment]
I'm really sorry.  Pilot error.  I  could have sworn I saw a difference between versions but retesting now I don't see it.  I should just continue my vacation.

**Comment by Mytherin** [comment]
No worries, happens to all of us :) Enjoy your vacation
