### ISSUE TITLE
SIGSEGV when attempting to query R2 from CLI

### ISSUE THREAD

**Issue by maxcountryman** [duckdb/duckdb#4082]
#### What happens?

SIGSEGV when attempting to query R2 from CLI.

#### To Reproduce
```
v0.4.0 da9ee490d

D load httpfs;
D set s3_region='auto';
D set s3_access_key_id='[redacted]';
D set s3_secret_access_key='[redacted]';
D set s3_endpoint='[redacted].r2.cloudflarestorage.com';
D select count(*) from read_parquet('s3://my-bucket/some/path/to/my.snappy.parquet');
fish: Job 1, 'duckdb' terminated by signal SIGSEGV (Address boundary error)
```

(Apologies, this is probably not reproducible without a Cloudflare account with an appropriately configured R2 bucket.)

#### Environment (please complete the following information):
 - OS: macOs
 - DuckDB Version: v0.4.0 da9ee490d
 - DuckDB Client: CLI

**Comment by hannes** [comment]
Could you please make this reproducible by e.g. hosting a file on R2 for this issue? Right now this issue is not actionable.

**Comment by maxcountryman** [comment]
> Could you please make this reproducible by e.g. hosting a file on R2 for this issue? Right now this issue is not actionable.

I wish I could but that would require me sharing my credentials.

While I can't do that, R2 is in open beta, and it's not at all difficult to get setup. I'd be happy to walkthrough the setup process with anyone wishing to investigate further.

**Comment by djouallah** [comment]
same problem with the current master code

**Comment by djouallah** [comment]
making the bucket public, we get this errors but at least there is no segfault

?encoding-type=url&list-type=2&prefix=lineitem_1%2F' (HTTP 400)

**Comment by hannes** [comment]
Again, can someone commenting here try to make a publicly accessible file available that we can test with?

**Comment by Mause** [comment]
@hannes I've been able to replicate this, looks like it might be related to the signing of the request - I'll send you the details

**Comment by hannes** [comment]
I've added a public file to R2 for testing, `https://pub-fc7e47bd584441e695dca1d09ce75ed8.r2.dev/lineitem-top10000.gzip.parquet`

**Comment by hannes** [comment]
I think this is caused by the cloud flare keys being slightly longer than the AWS ones

**Comment by hannes** [comment]
This is actually a bug in picohash ^^

**Comment by hannes** [comment]
I filed a bug report here https://github.com/kazuho/picohash/issues/10
