### ISSUE TITLE
Filter is case sensitive 

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#4084]
#### What happens?
Filter is case sensitive, I expected to be case insensitive 

#### To Reproduce
CREATE TABLE lineitem(l_returnflag string, l_quantity numeric);
INSERT INTO lineitem VALUES ('A',150), ('b',300), ('c',200) ;
CREATE function Total_Quantity() as (select sum (l_quantity ) from lineitem );
CREATE function Quantity_A()  as (select sum(l_quantity) filter ( l_returnflag = 'a') from lineitem) ;

select   l_returnflag
        , sum(l_quantity)
        ,  Quantity_A() 
        , Total_Quantity() as Total
        , sum(l_quantity)/Total_Quantity() as Percentage 
        from lineitem group by all ;
 the function function Quantity_A() return Null, it works with 'A'
#### Environment (please complete the following information):
 - OS:  Windows 
 - DuckDB Version: Bleeding edge
 - DuckDB Client: windows 

#### Identity Disclosure:
 - Full Name: Mimoune 

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

This is expected behavior, as DuckDB uses case sensitive comparisons by default. You can change this behavior by setting the default collation:

```sql
SET default_collation='nocase';
CREATE TABLE lineitem(l_returnflag string, l_quantity numeric);
INSERT INTO lineitem VALUES ('A',150), ('b',300), ('c',200) ;
CREATE function Total_Quantity() as (select sum (l_quantity ) from lineitem );
CREATE function Quantity_A() as (select sum(l_quantity) filter (WHERE l_returnflag = 'a') from lineitem) ;

select l_returnflag
, sum(l_quantity)
, Quantity_A()
, Total_Quantity() as Total
, sum(l_quantity)/Total_Quantity() as Percentage
from lineitem group by all ;
┌──────────────┬─────────────────┬──────────────┬─────────┬─────────────────────┐
│ l_returnflag │ sum(l_quantity) │ quantity_a() │  Total  │     Percentage      │
├──────────────┼─────────────────┼──────────────┼─────────┼─────────────────────┤
│ A            │ 150.000         │ 150.000      │ 650.000 │ 0.23076923076923078 │
│ b            │ 300.000         │ 150.000      │ 650.000 │ 0.46153846153846156 │
│ c            │ 200.000         │ 150.000      │ 650.000 │ 0.3076923076923077  │
└──────────────┴─────────────────┴──────────────┴─────────┴─────────────────────┘
```

**Comment by djouallah** [comment]
sorry, it should have being a Question :)
