### ISSUE TITLE
DECIMAL Value result -> Pandas Dataframe does not return decimal.Decimal

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#4102]
#### What happens?
This falls in the same category as #4026
When the result is of type DECIMAL, exporting this result to a dataframe converts the value to a float64, instead of an object of type decimal.Decimal

#### To Reproduce
```py
duckdb_col = duckdb.query("select 2423432::DECIMAL(12,4)").df()
----
2423432.0
```

Whereas exporting it as a tuple through fetchone() does create the expected result:
```py
duckdb_col = duckdb.query("select 2423432::DECIMAL(12,4)").fetchone()
----
(Decimal('2423432.0000'),)
```

**Comment by hannes** [comment]
One problem here is that returning as Decimal object is going to be abysmally slow. Not sure what's best here...

**Comment by Alex-Monahan** [comment]
I would prefer aligning to numpy/pandas and keeping float64, especially if it's much faster. That's what most folks will be using I think. It's fine to leave the fetchone as pulling the Python decimal type if you want,  but I wouldn't do that for fetch_df.

**Comment by Tishj** [comment]
That makes sense, sounds like the current behavior is actually preferable and probably intended to be that way 😅 .
Thanks for enlightening me, closing this issue :)

**Comment by nicodv** [comment]
There is an easy way around this currently, by going via arrow:

```result.arrow().to_pandas()```
