### ISSUE TITLE
size of INTEGER does not properly upgrade DECIMAL type

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#4106]
#### What happens?
When creating a column or list that contains values of both INTEGER and DECIMAL, the INTEGER type does not upgrade the type of the collection when it should. 

This causes the DECIMAL type to be too small to contain the INTEGER, resulting in a ConversionError.

In this example, `10.0000000005` is of type DECIMAL(12,10).  
`1000000` does not fit in that type (the amount of digits available before the decimal point (2) is too small).

So the type should be "upgraded" to DECIMAL(17, 10) to fit both of the values in the collection.
This operation should still fail if the new width would exceed the allowed maximum (38).
Or possibly even "upgrade" further to DOUBLE in this case.

#### To Reproduce
```sql
CREATE TABLE tbl AS SELECT [1000000, 10.0000000005];
```
```
Conversion Error: Could not cast value 1000000 to DECIMAL(12,10)
```

#### Environment (please complete the following information):
 - OS: (e.g. iOS)
 - DuckDB Version: [e.g. 22]
 - DuckDB Client: [Shell]

#### Identity Disclosure:
 - Full Name: [Thijs Bruineman]
 - Affiliation: [DuckDBLabs]

**Comment by Tishj** [comment]
This is kind of an annoying issue, because these type "upgrades" happen in MaxLogicalType, where we only know the LogicalType of the values.

Since DECIMAL has a higher LogicalTypeId, it gets priority over INTEGER.
And since we only have the logicaltype, we cant make any constructive observations about the INTEGER, because we dont know the actual value of it.

**Comment by Mytherin** [comment]
A while ago I had a pass at improving the `MaxLogicalTypes` for numerics since there were other issues there, perhaps [have a look](https://github.com/duckdb/duckdb/compare/master...Mytherin:duckdb:maxlogicaltypesnumerics). Maybe you could pick this up?

**Comment by Tishj** [comment]
Ah will do, I just "fixed" this issue. GetDecimalProperties exists, to get the max width of an integer type, and I'm using that now in MaxLogicalType.
A little wasteful but I don't think we can do better since we don't have access to the actual integer values.
