### ISSUE TITLE
Adding Custom Type Part 3

### ISSUE THREAD

**Issue by handstuyennn** [duckdb/duckdb#4118]
Hi @Mytherin 

Continuing from [this thread](https://github.com/duckdb/duckdb/pull/3490).
Part 1 ("Provide a way of creating a (named) alias to an existing type (e.g. a struct)") have been done.
Part 2 ("Provide a way of binding the type in functions, so functions can be created that take the type as input or output the type.")  have been done.

I want to continue on Part 3: Provide cast operators to and from this type

In my understanding, We will define functions for input and output for custom type when we define new custom type. Eg:
`CREATE TYPE alias AS VARCHAR (in: alias_in, out: alias_out);`

Please give me advise for this.

Thanks

**Comment by handstuyennn** [comment]
Hi @Mytherin 

I really want to finish adding type feature.

> In my understanding, We will define functions for input and output for custom type when we define new custom type. Eg:
> `CREATE TYPE alias AS VARCHAR (in: alias_in, out: alias_out);`

I think this is the goal of cast operators. Please give me suggestion.

Thank

**Comment by handstuyennn** [comment]
Hi @Mytherin,
Sorry to keep bugging but I wanted to know if you had any feedback on the above?
Thanks for your time.

**Comment by Mytherin** [comment]
I'm going to pick this part up myself - this requires a relatively fundamental rework of how casting functions are implemented that is out of scope for an external contributor.

**Comment by handstuyennn** [comment]
Hi @Mytherin,

I really want to implement `Geometry` and other types. Could you let me know when you finish implemented `Custom type`.

Thanks
