### ISSUE TITLE
INTERVAL type missing in ListVector::Search

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#4121]
#### What happens?
Attempting to do a look up in a MAP using an INTERVAL value causes an exception to be thrown.
(within ListVector::Search there is no case to handle PhysicalType::INTERVAL)

#### To Reproduce
```sql
statement ok
create table interval_key as select MAP_FROM_ENTRIES(ARRAY[(('2022-01-02 01:00:00'::TIMESTAMP - '2022-01-01'::TIMESTAMP), 'x'), (('2022-01-02 01:00:00'::TIMESTAMP - '2021-01-01'::TIMESTAMP), 'y')]) col;

query I
select * from interval_key;
----
{1 day 01:00:00=x, 366 days 01:00:00=y}

query I
select col[('2022-01-02 01:00:00'::TIMESTAMP - '2022-01-01'::TIMESTAMP)] from interval_key;
----
[x]
```

The last query causes the error:
```
Actual result:
Invalid type Error: Invalid Type [LIST]: Invalid type for List Vector Search
```

**Comment by Mytherin** [comment]
Thanks for the report!

I think it would make sense to rework the interval type to remove the interval physical type entirely, and instead store it as `STRUCT(months INTEGER, days INTEGER, micros BIGINT)`. This should clean up the code and would allow us to eat our own dog food w.r.t. adding type aliases with function overloading, etc. @hawkfish thoughts?

**Comment by hawkfish** [comment]
> Thanks for the report!
> 
> I think it would make sense to rework the interval type to remove the interval physical type entirely, and instead store it as `STRUCT(months INTEGER, days INTEGER, micros BIGINT)`. This should clean up the code and would allow us to eat our own dog food w.r.t. adding type aliases with function overloading, etc. @hawkfish thoughts?

I think this is a good long term goal - and is similar to the idea I have been flogging for a `TIMESTAMP` that contains a time zone: `STRUCT(ts TIMESTAMP, tz VARCHAR)`.  My one concern here is that the standard's rules for `INTERVAL` are fairly complex so if we want to experiment with complex types like this, we should start with this locale-aware timestamp to flesh out the major issues?

**Comment by hawkfish** [comment]
`INTERVAL` now has an `operator==` method so we can just add a case.
