### ISSUE TITLE
Offset Error when using http extension

### ISSUE THREAD

**Issue by halvorlinder** [duckdb/duckdb#4122]
#### What happens?
When querying a python web server running on localhost for a parquet file, I get the following error:

> Error: offset error

The server does receive the request and returns a 200

> 127.0.0.1 - - [14/Jul/2022 14:42:43] "GET /parquets/nation.parquet HTTP/1.1" 200 -

Also, downloading the same file using wget and then executing the query works as expected.

#### To Reproduce

Start a web server on localhost
`python3 -m http.server`
 
Start DuckDB and load the HTTP extension
`duckdb`
`LOAD httpfs;`

Query a file from the server
`SELECT * FROM read_parquet('localhost:8000/parquets/orders.parquet');`

#### Environment:
 - OS: Ubuntu 20.04.4 LTS
 - DuckDB Version: v0.4.0 da9ee490d
 - DuckDB Client: CLI

#### Identity Disclosure:
 - Full Name: Halvor Linder Henriksen 
 - Affiliation: Huawei

**Comment by samansmink** [comment]
Hi @halvorlinder, thanks for reporting this. I did manage to reproduce this, It most likely has to do with the recent httpfs specific optimisations to the parquet reader.

**Comment by halvorlinder** [comment]
@samansmink do you know which version this was introduced in? I am experiencing the same issues in v0.3.4. 
Also, and this may be correlated, when querying of large files (The one I am trying is 281MB) another error seems to occur where I believe DuckDB closes it's connection socket before the entire file is transferred (See https://stackoverflow.com/a/11866962). The error on the server is:

> Exception happened during processing of request from ('127.0.0.1', 47580)
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.8/http/server.py", line 647, in __init__
>     super().__init__(*args, **kwargs)
>   File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
>     self.handle()
>   File "/usr/lib/python3.8/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
>     method()
>   File "/usr/lib/python3.8/http/server.py", line 654, in do_GET
>     self.copyfile(f, self.wfile)
>   File "/usr/lib/python3.8/http/server.py", line 853, in copyfile
>     shutil.copyfileobj(source, outputfile)
>   File "/usr/lib/python3.8/shutil.py", line 208, in copyfileobj
>     fdst_write(buf)
>   File "/usr/lib/python3.8/socketserver.py", line 826, in write
>     self._sock.sendall(b)
> BrokenPipeError: [Errno 32] Broken pipe
> 
The error on the client is the same

**Comment by samansmink** [comment]
@halvorlinder ah thats interesting, the changes i thought were related to this were introduced in v0.4.0, so maybe i'm wrong there. I will find some time to look into this further next week.
