### ISSUE TITLE
large table created on windows in R with dbWriteTable disappears

### ISSUE THREAD

**Issue by ajdamico** [duckdb/duckdb#4127]
#### What happens?
large table created on windows in R with dbWriteTable disappears as shown in this screenshot --

<img width="1280" alt="duckdb dbWriteTable failure" src="https://user-images.githubusercontent.com/216807/179066417-050c61ac-81b2-4449-83e7-8ba877b9c212.png">

#### To Reproduce

	set.seed(2022)

	db_path <- 'R:/temp/temp.db' 
	# num_recs <- 3200000	# no issue at 3.2 million
	num_recs <- 32000000	# problem at 32 million
	library(DBI)

	paste_ <- function(...)paste(...,sep='-')

	mystrings <-
		function( n ) do.call(paste_, replicate(20, paste0(sample(LETTERS, n, TRUE), sample(9999, n, TRUE)), FALSE))

	w <-
		data.frame(
			form_type = sample( c( 'P' , 'I' ) , num_recs , replace = TRUE ) ,
			bill_type = sample( c( NA , 100:999 ) , num_recs , prob = c( .2 , rep(0.0008888889,900) ) , replace = TRUE ) ,
			diag_cds = mystrings( num_recs )
		)
		

	con = dbConnect( duckdb::duckdb() , dbdir = db_path , read_only = FALSE )
	dbWriteTable(con , "w" , w )
	dbListTables(con)
	dbGetQuery(con, "SELECT COUNT(*) FROM w" )
	dbDisconnect(con, shutdown=TRUE)
	q('no')

	#########################################
	# after lefthand session has fully quit #
	#########################################

	db_path <- 'R:/temp/temp.db' 
	library(DBI)
	con = dbConnect( duckdb::duckdb() , dbdir = db_path , read_only = FALSE )
	dbListTables(con)
	sessionInfo()

#### Environment (please complete the following information):
 - OS: windows
 - DuckDB Version: R duckdb library 0.4.0
 - DuckDB Client: R

#### Identity Disclosure:
 - Full Name: Anthony Damico
 - Affiliation: Independent Consultant

**Comment by Mytherin** [comment]
Hey Anthony :) Thanks for the report!

Could this be related to #3952? Could you try this with the latest dev build?

**Comment by ajdamico** [comment]
hey hey!  you are ahead of the curve as usual  :-)  yes, for sure this is fixed in dev (screenshot).  appreciate you pointing me to that

<img width="689" alt="Untitled" src="https://user-images.githubusercontent.com/216807/179262566-9b0a6c01-5e0f-4c38-a4d3-4cf820e4f92b.png">
