### ISSUE TITLE
Error when reading categorical data with `pd.read_feather`

### ISSUE THREAD

**Issue by Marigold** [duckdb/duckdb#4130]
#### What happens?

When I load categorical variable from DuckDB in feather format and then try to convert it into dataframe with `pd.read_feather` I get an error
```
pyarrow.lib.ArrowTypeError: Converting unsigned dictionary indices to pandas not yet supported, index type: uint8
```

Loading that variable with `fetch_df` works well, but I can't use it as I'm trying to send feather format in response and let user use `pd.read_feather`.

#### To Reproduce

```python
import pandas as pd
import duckdb
import pyarrow as pa
import io

con = duckdb.connect("playground.db")

df = pd.DataFrame(
    {
        "a": [1, 2, 3],
        "b": ["x", "x", "y"],
    }
).astype({"b": "category"})

con.register("t", df)
con.execute("CREATE OR REPLACE TABLE tab AS SELECT * FROM t")


def _read_sql_bytes(con, sql: str, parameters) -> io.BytesIO:
    sink = io.BytesIO()

    batch_iterator = con.execute(sql, parameters=parameters).fetch_record_batch(
        chunk_size=1000
    )
    with pa.ipc.new_file(sink, batch_iterator.schema) as writer:
        for rb in batch_iterator:
            writer.write_batch(rb)
    sink.seek(0)

    return sink


q = """
select
    b
from tab
"""

bytes_io = _read_sql_bytes(con, q, parameters=[])
pd.read_feather(bytes_io)
```

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: v0.3.4
 - DuckDB Client: python

#### Identity Disclosure:
 - Full Name: Mojmir Vinkler
 - Affiliation: ourworldindata.org

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by pdet** [comment]
Hi Marigold, I would say the error you see is between Arrow and Pandas, and unrelated to DuckDB

Basically, when transforming from DuckDB to Arrow, the dictionary indices are exported as unsigned. (which is supported by both systems).

When DuckDB exports to Pandas, we perform the conversion of unsigned to signed internally.

When Pandas try to read the Arrow file, they don't perform the necessary conversion.

**Comment by Marigold** [comment]
> When DuckDB exports to Pandas, we perform the conversion of unsigned to signed internally.

Thanks! This was the missing piece. I'm gonna check out the codebase how you do it.
