### ISSUE TITLE
JDBC client incorrectly handles Unicode characters in prepared statement parameters

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#4136]
#### What happens?
When a Unicode character is used as a prepared statement parameter, the query results contain incorrect bytes for the character. Maybe related to https://github.com/duckdb/duckdb/issues/3956?

#### To Reproduce
Reproduction case can be found at https://github.com/michaeljohnalbers/duckdb-issue-reproduction/releases/tag/unicode-chars-prepared-stmt-params

#### Environment (please complete the following information):
 - OS: Ubuntu Linux
 - DuckDB Version: 0.4.0
 - DuckDB Client: JDBC

#### Identity Disclosure:
 - Full Name: Michael Albers
 - Affiliation: Mode Analytics

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Jens-H** [comment]
The Java Character class says [1]:

> The methods that only accept a char value cannot support supplementary characters

So I would expect that values outside the "Basic Multilingual Plane" are not supported by GetStringUTFChars.

[1] https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Character.html#unicode

**Comment by rkennedy-mode** [comment]
Be careful with GetStringUTFChars, we've had to get other things fixed that use it without realizing that it's not returning UTF-8 bytes but **modified** UTF-8, instead: #3956.

**Comment by hannes** [comment]
Yeah that's a fun one
