### ISSUE TITLE
Memory leak in NodeJS bindings

### ISSUE THREAD

**Issue by danielchiu** [duckdb/duckdb#4164]
#### What happens?

When using the default connection (rather than self-managing connections) databases seem to never get garbage collected, even if closed. This includes the connection as well as any residual tables.

https://github.com/duckdb/duckdb/blob/195b7b47b43f875b0ade249eaf456f7909a447bc/tools/nodejs/lib/duckdb.js#L140-L145

We believe this is due to a circular reference which the V8 engine cannot break due to one originating in C++, where the Database contains a reference to the `default_connection`, while the C++ Connection contains a reference to the Database. 

https://github.com/duckdb/duckdb/blob/195b7b47b43f875b0ade249eaf456f7909a447bc/tools/nodejs/src/connection.cpp#L47-L48

When we stop using the default connection and manually create our own, we don't see the same memory leaks.

#### To Reproduce

Using the NodeJS bindings, repeatedly create databases and tables. For example, run this gist: https://gist.github.com/danielchiu/0f3f9df48c1bfafd8b56417d76bd152e.

When run on my system, Activity Monitor shows this balloon in memory usage, thread count, and port count until it crashes.

#### Environment:
 - OS: MacOS
 - DuckDB Version: 0.4.0
 - DuckDB Client: NodeJS

cc @zenazn

**Comment by hadoan** [comment]
Hey folks — ran into a similar memory issue recently.

I’m working on a free tool that helps analyze heap snapshots (Node, Python, .NET, etc.) and spot leaks like this one.

Just wanted to share in case it’s helpful for others debugging similar problems.

Happy to chat or give early access if anyone’s interested!
