### ISSUE TITLE
Provide ODBC backend for DuckDB

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#417]
See here for documentation: https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/odbc-api-reference
There seems to be an (automated?) verification program for ODBC from Microsoft: https://docs.microsoft.com/en-us/sql/odbc/odbc-test
Maybe this can be used as a basis: http://www.ch-werner.de/sqliteodbc/

**Comment by hannesmuehleisen** [comment]
the `odbc` branch contains a first iteration of this using sqlite's odbc driver

**Comment by hannesmuehleisen** [comment]
Closing for now, will reopen when there is serious interest.

**Comment by alanpaulkwan** [comment]
I would +1 this.

It would be an interesting hook-in for SAS + Stata users. I wish these platforms just had native Parquet readers, SAS users need to use Spark to convert at the moment. Stata has a parquet reader for Linux shoehorning Arrow bindings.  Matlab has native support I believe.

**Comment by alanpaulkwan** [comment]
Actually, upon second thought: is it possible just to use the JDBC connector for DuckDB across platforms? I think that would solve it. For large record imports, is JDBC faster? MAybe this would be better w/o much extra effort.

**Comment by tate-bowman** [comment]
@hannesmuehleisen +1 here, too. Having a native ODBC driver for DuckDB would be my dream scenario and would add significant value in being able to build a custom connector for DirectQuery models on top of DuckDB databases in Power BI (would make for some really awesome modeling/analytical capabilities). I already have one for SQLite, but as you would know, this does not scale well with larger datasets. Right now, this is not possible without some JDBC to ODBC bridge, which is not easy to configure.

**Comment by tyluRp** [comment]
+1

**Comment by bigtooth81** [comment]
+1 Having the ability to work with zip, gzip, and Stata will be hugely useful

**Comment by iagovar** [comment]
+1 I really want to snap duckdb everywhere.

**Comment by moheikal79** [comment]
Its really important to have a native ODBC for duckdb.

**Comment by hannesmuehleisen** [comment]
@moheikal79 could you please elaborate a bit? Why do you think that, what tools would you like to use?

**Comment by alanpaulkwan** [comment]
@hannesmuehleisen as much as I hate STATA/SAS/MATLAB and prefer open-source R/Python, these guys are big users of data and would get brought into the fold. STATA is for academics in social science (and is awful in general, though STATA now has Python integration), SAS and MATLAB are enterprise.

**Comment by alanpaulkwan** [comment]
Here's another thought. Currently, when I use DuckDB, I have my Parquet files in a mounted Dropbox / Google Drive / GCS bucket, and I use DuckDB to read from them into whatever computer I'm working from at that point. This is really convenient b/c I get the DuckDB workflow without having to lug around all my files.

Imagine that DuckDB could do a scan on an ODBC data source. In theory, I could have DuckDB read from any ODBC-compliant back-end. I'm sure this is much faster and more fluid than reading into R / Python and inserting.

**Comment by moheikal79** [comment]
> @moheikal79 could you please elaborate a bit? Why do you think that, what tools would you like to use?

Hi,
I would be great to use duckdb with power bi and excel if ODBC if available to enhance the user experience in data analysis.

**Comment by alanpaulkwan** [comment]
Feature request related to ODBC: if DuckDB can stream in ODBC connections from other applications (like MySQL, Postgres, Clickhouse) it would simplify centralizing data into DuckDB.

**Comment by hannes** [comment]
An ODBC driver now exists. Closing this issue

**Comment by alanpaulkwan** [comment]
Amazing - is there a guide?

**Comment by hannes** [comment]
No guide yet regrettably. @tiagokepe could you get a documentation entry started please?

**Comment by alanpaulkwan** [comment]
Would it be possible to read another ODBC data source (MySQL, Clickhouse, Postgres, etc) via the connector?

**Comment by davlee1972** [comment]
Would it be possible to add a direct query support to the powerbi stack?

PowerBI can use the odbc connection to import a dataset (using ONE sql query), but it won't use the duckdb engine to do any dynamic sorts, filter, joins, etc..

DirectQuery needs to be supported..

https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-use-directquery

**Comment by Alex-Monahan** [comment]
Well, Power BI doesn't support direct query with ODBC. Maybe Microsoft
could fix that instead?
https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources#data-sources-m-o

What would be required to enable this? Using ODBC may not work - and we are
not likely to build a native driver unless it is really easy...

**Comment by davlee1972** [comment]
Actually it looks like you can contribute a product specific odbc driver. I see Dremio as an option and PowerBI doensn't support JDBC so it must also be using the Dremio ODBC Driver..

https://learn.microsoft.com/en-us/power-query/odbc

Using M's built-in [Odbc.DataSource](https://learn.microsoft.com/en-us/powerquery-m/odbc-datasource) function is the recommended way to create custom connectors for data sources that have an existing ODBC driver and/or support a SQL query syntax. Wrapping the [Odbc.DataSource](https://learn.microsoft.com/en-us/powerquery-m/odbc-datasource) function allows your connector to inherit default query folding behavior based on the capabilities reported by your driver. This will enable the M engine to generate SQL statements based on filters and other transformations defined by the user within the Power Query experience, without having to provide this logic within the connector itself.

**Comment by davlee1972** [comment]
https://github.com/microsoft/DataConnectors

**Comment by abubelinha** [comment]
I think @alanpaulkwan [above comment](https://github.com/duckdb/duckdb/issues/417#issuecomment-1167020481) was not answered: 
> Would it be possible to read another ODBC data source (MySQL, Clickhouse, Postgres, etc) via the connector?

I am trying to figure out if I can connect to tables in Microsoft Access .mdb file , right away from python-duckdb (avoiding usage of sqlalchemy-pandas between Access and duckdb, which I described [here](https://github.com/duckdb/duckdb/discussions/13141)).

I already looked at duckdb documentation ([ODBC API on Windows](https://duckdb.org/docs/api/odbc/windows), [ODBC guide](https://duckdb.org/docs/guides/odbc/general)) and some other issues (https://github.com/duckdb/duckdb/issues/11380).
But I think all of them are about using ODBC to connect duckdb databases FROM other applications (to use duckdb as data source). And not the other way round:

Is it possible to connect other ODBC data sources FROM duckdb?

Thanks
@abubelinha
