### ISSUE TITLE
rows_update() gives incorrect results

### ISSUE THREAD

**Issue by markpayneatwork** [duckdb/duckdb#4173]
#### What happens?
When trying to update one table to another using `rows_update()`, the resulting changes to the database are incorrect.

#### To Reproduce
See reprex below. Generally, this has been difficult to reproduce in a synthetic setting, but by stripping out most of the contents of the database where it happens, I have been able to create the reprex below - alternatively, see the zipped file here. 

[Zipped_example.zip](https://github.com/duckdb/duckdb/files/9148887/Zipped_example.zip)

#### Environment (please complete the following information):
 - OS: Ubuntu, Windows
 - DuckDB Version: 0.3.5-dev1410
 - DuckDB Client: R DuckDB package 0.4.0, installed from CRAN (on both Windows and Ubuntu)

#### Identity Disclosure:
 - Full Name: Mark Payne
 - Affiliation: Danish Meterological Institute

#### Before Submitting

- [ x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

Checked on latest version on CRAN.

- [x ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yes.

#### Reprex

``` r
library(duckdb)
#> Loading required package: DBI
library(tidyverse)
library(dbplyr)

#Connect to database
this.db <- dbConnect(duckdb(),"MPI-ESM.duckdb")
time.tb <- tbl(this.db,"time")
doy.tb <- tbl(this.db,"doy")

#Check contents of doy and time tables. Note in particular the doy column, which is what we're interested in
time.tb
#> # Source:   table<time> [?? x 8]
#> # Database: DuckDB 0.3.5-dev1410 [mapa@Linux 5.15.0-40-generic:R 4.1.2/MPI-ESM.duckdb]
#>    tpKey timeID file                               year month   day season   doy
#>    <dbl>  <dbl> <chr>                             <int> <int> <int> <fct>  <int>
#>  1     0    0.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     1 DJF       NA
#>  2     1    1.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     2 DJF       NA
#>  3     2    2.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     3 DJF       NA
#>  4     3    3.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     4 DJF       NA
#>  5     4    4.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     5 DJF       NA
#>  6     5    5.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     6 DJF       NA
#>  7     6    6.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     7 DJF       NA
#>  8     7    7.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     8 DJF       NA
#>  9     8    8.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1     9 DJF       NA
#> 10     9    9.5 /dmidata/projects/klimaatlas/mapâ¦  1850     1    10 DJF       NA
#> # â¦ with more rows
doy.tb
#> # Source:   table<doy> [?? x 3]
#> # Database: DuckDB 0.3.5-dev1410 [mapa@Linux 5.15.0-40-generic:R 4.1.2/MPI-ESM.duckdb]
#>    month   day   doy
#>    <int> <int> <dbl>
#>  1     1     1     1
#>  2     1     2     2
#>  3     1     3     3
#>  4     1     4     4
#>  5     1     5     5
#>  6     1     6     6
#>  7     1     7     7
#>  8     1     8     8
#>  9     1     9     9
#> 10     1    10    10
#> # â¦ with more rows

#But doing the modification leads to problems
rows_update(time.tb,
            doy.tb,
            by=c("month","day"),
            unmatched="ignore",
            in_place = TRUE) #NB: in_place=FALSE gives the correct result, but doesn't modify the database

#Sometimes the problem is apparent at the head of the table
time.tb
#> # Source:   table<time> [?? x 8]
#> # Database: DuckDB 0.3.5-dev1410 [mapa@Linux 5.15.0-40-generic:R 4.1.2/MPI-ESM.duckdb]
#>    tpKey timeID file                             year month   day season     doy
#>    <dbl>  <dbl> <chr>                           <int> <int> <int> <fct>    <int>
#>  1     0    0.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     1 DJF    -3.38e8
#>  2     1    1.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     2 DJF     2.2 e4
#>  3     2    2.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     3 DJF    -3.37e8
#>  4     3    3.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     4 DJF     2.2 e4
#>  5     4    4.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     5 DJF     0     
#>  6     5    5.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     6 DJF     0     
#>  7     6    6.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     7 DJF     0     
#>  8     7    7.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     8 DJF     0     
#>  9     8    8.5 /dmidata/projects/klimaatlas/mâ¦  1850     1     9 DJF     0     
#> 10     9    9.5 /dmidata/projects/klimaatlas/mâ¦  1850     1    10 DJF     0     
#> # â¦ with more rows

#But it really becomes apparent if we look across the entire table
time.tb%>% 
  summarise(min=min(doy,na.rm=TRUE),
            max=max(doy,na.rm=TRUE)) 
#> # Source:   SQL [1 x 2]
#> # Database: DuckDB 0.3.5-dev1410 [mapa@Linux 5.15.0-40-generic:R 4.1.2/MPI-ESM.duckdb]
#>           min        max
#>         <int>      <int>
#> 1 -2147221504 2063663104
```

<sup>Created on 2022-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] forcats_0.5.1   stringr_1.4.0   dplyr_1.0.9     purrr_0.3.4    
#>  [5] readr_2.1.2     tidyr_1.2.0     tibble_3.1.7    ggplot2_3.3.6  
#>  [9] tidyverse_1.3.1 duckdb_0.4.0    DBI_1.1.3      
#> 
#> loaded via a namespace (and not attached):
#>  [1] tidyselect_1.1.2 xfun_0.31        haven_2.5.0      colorspace_2.0-3
#>  [5] vctrs_0.4.1      generics_0.1.2   htmltools_0.5.2  yaml_2.3.5      
#>  [9] blob_1.2.3       utf8_1.2.2       rlang_1.0.3      pillar_1.7.0    
#> [13] glue_1.6.2       withr_2.5.0      dbplyr_2.2.1     readxl_1.4.0    
#> [17] modelr_0.1.8     lifecycle_1.0.1  cellranger_1.1.0 munsell_0.5.0   
#> [21] gtable_0.3.0     rvest_1.0.2      evaluate_0.15    knitr_1.39      
#> [25] tzdb_0.3.0       fastmap_1.1.0    fansi_1.0.3      highr_0.9       
#> [29] broom_1.0.0      backports_1.4.1  scales_1.2.0     jsonlite_1.8.0  
#> [33] fs_1.5.2         hms_1.1.1        digest_0.6.29    stringi_1.7.6   
#> [37] grid_4.1.2       cli_3.3.0        tools_4.1.2      magrittr_2.0.3  
#> [41] crayon_1.5.1     pkgconfig_2.0.3  ellipsis_0.3.2   xml2_1.3.3      
#> [45] reprex_2.0.1     lubridate_1.8.0  assertthat_0.2.1 rmarkdown_2.14  
#> [49] httr_1.4.3       rstudioapi_0.13  R6_2.5.1         compiler_4.1.2
```

</details>

**Comment by markpayneatwork** [comment]
Some further exploring reveals even more wierdness - after disconnecting from the database and reconnecting again, the correct values in the table are correct. Verified on both Ubuntu and Windows. See updated reprex below, with the files in the zip:

[Reprex2.zip](https://github.com/duckdb/duckdb/files/9149314/Reprex2.zip)

 ``` r
library(duckdb)
#> Loading required package: DBI
library(tidyverse)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

#Start by making a copy of the database to work on
file.copy("MPI-ESM.duckdb.bak.doy","MPI-ESM.duckdb",overwrite=TRUE)
#> [1] TRUE

#Connect to database
this.db <- dbConnect(duckdb(),"MPI-ESM.duckdb")
time.tb <- tbl(this.db,"time")
doy.tb <- tbl(this.db,"doy")

#But doing the modification leads to problems
rows_update(time.tb,
            doy.tb,
            by=c("month","day"),
            unmatched="ignore",
            in_place = TRUE) #NB: in_place=FALSE gives the correct result, but doesn't modify the database

time.tb%>% 
  summarise(min=min(doy,na.rm=TRUE),
            max=max(doy,na.rm=TRUE)) 
#> # Source:   SQL [1 x 2]
#> # Database: DuckDB 0.3.5-dev1410 [mapa@Linux 5.15.0-40-generic:R 4.1.2/MPI-ESM.duckdb]
#>          min   max
#>        <int> <int>
#> 1 -704274336 32523

#It gets wierder. Shutting down the duckdb connection and reestablishing it makes
#everthing look good again
dbDisconnect(this.db,shutdown=TRUE)
this.db2 <- dbConnect(duckdb(),"MPI-ESM.duckdb")
time.tb2 <- tbl(this.db2,"time")
time.tb2%>% 
  summarise(min=min(doy,na.rm=TRUE),
            max=max(doy,na.rm=TRUE)) 
#> # Source:   SQL [1 x 2]
#> # Database: DuckDB 0.3.5-dev1410 [mapa@Linux 5.15.0-40-generic:R 4.1.2/MPI-ESM.duckdb]
#>     min   max
#>   <int> <int>
#> 1     1   366
```

<sup>Created on 2022-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] dbplyr_2.2.1    forcats_0.5.1   stringr_1.4.0   dplyr_1.0.9    
#>  [5] purrr_0.3.4     readr_2.1.2     tidyr_1.2.0     tibble_3.1.7   
#>  [9] ggplot2_3.3.6   tidyverse_1.3.1 duckdb_0.4.0    DBI_1.1.3      
#> 
#> loaded via a namespace (and not attached):
#>  [1] tidyselect_1.1.2 xfun_0.31        haven_2.5.0      colorspace_2.0-3
#>  [5] vctrs_0.4.1      generics_0.1.2   htmltools_0.5.2  yaml_2.3.5      
#>  [9] blob_1.2.3       utf8_1.2.2       rlang_1.0.3      pillar_1.7.0    
#> [13] glue_1.6.2       withr_2.5.0      readxl_1.4.0     modelr_0.1.8    
#> [17] lifecycle_1.0.1  cellranger_1.1.0 munsell_0.5.0    gtable_0.3.0    
#> [21] rvest_1.0.2      evaluate_0.15    knitr_1.39       tzdb_0.3.0      
#> [25] fastmap_1.1.0    fansi_1.0.3      highr_0.9        broom_1.0.0     
#> [29] backports_1.4.1  scales_1.2.0     jsonlite_1.8.0   fs_1.5.2        
#> [33] hms_1.1.1        digest_0.6.29    stringi_1.7.6    grid_4.1.2      
#> [37] cli_3.3.0        tools_4.1.2      magrittr_2.0.3   crayon_1.5.1    
#> [41] pkgconfig_2.0.3  ellipsis_0.3.2   xml2_1.3.3       reprex_2.0.1    
#> [45] lubridate_1.8.0  assertthat_0.2.1 rmarkdown_2.14   httr_1.4.3      
#> [49] rstudioapi_0.13  R6_2.5.1         compiler_4.1.2
```

</details>

**Comment by rsund** [comment]
Thanks for the reprex. Can't test it right now, but could you please also show the produced SQL by piping to `show_query()`. If the problem could then be repeated by using `DBI::dbGetQuery(con, <extractedquery>)` It would show is it actually an R/dbplyr specific or more general DuckDB issue.

You could also try to `filter()` invalid values even before `summarise()` to keep the query simpler. Maybe also test to use `left_join()` and `mutate()` "manually" instead of `update_rows()`.

And could you also try to pipe to `compute()` right after `rows_update()`.

**Comment by markpayneatwork** [comment]
Thanks for the reply. I'm afraid you may have misunderstood my concerns though - it's the changes at the database level that appear to be the problem, rather than what's happening with the `time.tb %>% summarise()` command. 

Anything that I do with the database after running `rows_update()` seems to have values for doy that are incorrect - including `summarise()`of course, but also downstream calculations using the `time.doy` column and even simply printing (see first reprex).

Unfortunately the SQL in `rows_update()` is not visible - its gets executed and a `tbl_lazy` object showing the results returned. This means that the suggestions about `compute()` and `show_query()` won't work, as the "damage" has already happened.

**Comment by rsund** [comment]
Well, I suspect that this may be related more to `tbl_lazy()` mechanism than be an actual problem in the database. Therefore it is essential to see what `rows_update()` is doing "behind the scenes". If `show_query()` is not showing SQL, it is possible to enable debug mode in DuckDB with debug=TRUE parameter in driver call that shows all SQL going to DuckDB.

**Comment by markpayneatwork** [comment]
Thanks for the tip! Setting `debug=TRUE`, here is the SQL that is being run by `rows_update()`: 
```
UPDATE "time"
SET "doy" = "...y"."doy"
FROM "doy" AS "...y"
WHERE ("...y"."month" = "time"."month") AND ("...y"."day" = "time"."day")
```
Taking this out and running it separately via `dbExecute()` gives the same behaviour as seen in the reprex's when running the command via `rows_update()`, including the correct results when I disconnect / reconnect to the database.

I'm not proficient enough with SQL to say whether this command is 100% correct, but it looks reasonable to me.

**Comment by rsund** [comment]
OK, so it is permanently updating the original table in the database (instead of making changes only to temporary tables). That may not be desirable behaviour in many user cases, but certainly it should work.

Could you please test can you see the invalid values directly with SQL (using `DBI::dbGetQuery()` with e.g. similar simple GROUP BY query than what your summarise will produce). If yes, then this is probably more general DuckDB issue and you have provided reprex also in SQL.

Could you also try to run `time.tb <- tbl(this.db, "time")` again after `rows_update()` (i.e. without disconnect/reconnect); maybe "mapping" to the table must be revised after update. Unlikely, but should be checked especially if error cannot be reproduced with pure SQL.

**Comment by rsund** [comment]
I was able to reproduce the bug. It seems to be a DuckDB issue as it happens even with pure SQL.

I tried to minimize the reprex and it can be seen with smaller data. From the table "doy" only one row is required. From the table "time" only variables month, day and doy are required for 1024 or more observations.

My guess is that something is not working correctly when updating the data that is larger than one "chunk" (1024 rows) and updates are done conditionally for a column containing missing values.

Actually the generation mechanism for NULLs may have a role here as I was able to mimimize the .duckdb data in the reprex2.zip within R, but with DATABASE EXPORT/IMPORT (to CSV) the problem vanished, i.e. it may be related to this data and especially to the doy-column in table "time" that contains only missing values before update.

In this sense, it could be useful to know how did you construct the .duckdb file in your reprex?

**Comment by Mytherin** [comment]
Could you share the SQL queries? I’m happy to have a look at that.

**Comment by rsund** [comment]
OK, here is the reduced data and R script using only SQL queries. It is essential to start with a "fresh" copy of the data every time as the data are updated and after the .wal is written to .duckdb the problem vanishes. Sometimes the problem cannot be seen in the first or second run, but it will appear sooner or later, i.e. min or max is something else than 1 (even thought there should be only 1 or NULL values and nothing can be seen with the filtering (WHERE) query). 

[issue.zip](https://github.com/duckdb/duckdb/files/9156777/issue.zip)

```r
file.copy("issue.duckdb","test.duckdb",overwrite=TRUE)
con <- DBI::dbConnect(duckdb::duckdb(), "test.duckdb")

DBI::dbExecute(con, "UPDATE time SET doy = doy.doy FROM doy WHERE (doy.month = time.month) AND (doy.day = time.day)")
DBI::dbGetQuery(con, "SELECT * FROM time WHERE doy<1 OR doy>1")    # Nothing here ever 
DBI::dbGetQuery(con, "SELECT MIN(doy), MAX(doy) FROM time")        # Invalid values can be seen

DBI::dbDisconnect(con,shutdown=TRUE)
unlink("test.duckdb")
```

**Comment by markpayneatwork** [comment]
Great to hear that it's not just me then! :-)

The creation process is
1. Create database from scratch: `dbConnect(duckdb::duckdb(),"my_database.ddb")`
2. Create blank "time" table and other tables via SQL using dbExecute() from R
3. Ingest data into database, populating, amongst others, "time" table. Note, however, that we don't populate the "doy" column in time 
4. Calculate day-of-year indices based on "time" table, writing the outputs into "doy" table
5. Use "doy" table to update the "doy" column in "time".

Let me know if you need the SQL.

**Comment by Mytherin** [comment]
> 

A SQL script for the creation would be great, then I can check if this is still reproducible on the latest master as well.

**Comment by rsund** [comment]
Steps 1, 2 and 3 would be enough, especially the step 3 would be interesting as (the R script for) it is where the conditions for the problem are potentially "created".

Btw, there are also other (potentially easier, faster and genetally more efficient) ways to create the doy variable, but that is certainly irrelevant here now as the goal is to find the bug.

**Comment by markpayneatwork** [comment]
After a bit of hacking around, I was able to get a reprex working without the need for a database i.e. following my general workflow. See below. This reproduces the error (most of the time) on both Windows and ubuntu.

A little aside: there is actually method to the madness of calculating the doy myself - I'm working with outputs from climate models, which don't always run on your standard gregorian calendar: variants include gregorian, 366 day (every year), 365 day (every year), and 360 day (12 months x 30 days). Most "normal" code baulks when you as it for the day-of-year of 30th February :-)

```r
library(duckdb)
library(tidyverse)

fname <- tempfile()
#Create table
if(file.exists(fname)){
  unlink(fname)
  unlink(sprintf("%.wal",fname))
} 

this.db <- dbConnect(duckdb(),fname)
dbExecute(this.db,
          "CREATE TYPE season AS ENUM ('DJF', 'MAM', 'JJA', 'SON');")
dbExecute(this.db,
          "CREATE TABLE time(tpKey UINTEGER PRIMARY KEY, 
          timeID DOUBLE UNIQUE,
          file TEXT,
          year INTEGER, 
          month INTEGER, 
          day INTEGER,
          season SEASON,
          doy INTEGER, 
          UNIQUE (year, month, day))")

#Populate
expand_grid(file="a rather long file path, one for each file",
            year=1850:2100,
            month=1:12,
            day=1:30) %>% 
  mutate(tpKey=1:n(),
         timeID=1:n(),
         season="DJF") %>% 
  dbAppendTable(this.db,"time",.)

#Reconnect. This mirrors the way my processing chain works, with a break in the middle.
#This appears to be important to get the bug to show itself...
dbDisconnect(this.db,shutdown=TRUE)
rm(this.db)
this.db2 <- dbConnect(duckdb(),fname)
time.tb <- tbl(this.db2,"time")

#Calculate DOY table manually
doy.dat <-
  time.tb %>% 
  distinct(month,day) %>% 
  dbplyr::window_order(month,day) %>% #Handles strangeness with ORDER BY in SQL
  mutate(doy=row_number()) %>% 
  compute(name="doy",temporary=FALSE)
doy.tb <- tbl(this.db2,"doy")

#Put it back into time
rows_update(time.tb,
            doy.tb,
            by=c("month","day"),
            unmatched="ignore",
            in_place=TRUE)
            
#Check results
time.tb %>% 
  summarise(min(doy),max(doy))

```

**Comment by rsund** [comment]
Thanks for the data generation script. I was able to reduce it further to the following one (that still results in the bug most of the time on the latest master (R-package installed from the [R-universe](https://duckdb.r-universe.dev/ui#package:duckdb))):
``` r
fname <- tempfile()
unlink(fname)

con <- DBI::dbConnect(duckdb::duckdb(), fname)

DBI::dbExecute(con, "CREATE TABLE time(month INTEGER, day INTEGER, doy INTEGER, UNIQUE (month, day))")
#> [1] 0
DBI::dbExecute(con, "INSERT INTO time SELECT i AS month, i AS day, NULL AS doy FROM range(1025) tbl(i)")
#> [1] 1025
DBI::dbExecute(con, "CREATE TABLE doy AS SELECT 1 AS month, 1 AS day, 1.0 AS doy")
#> [1] 1
DBI::dbExecute(con, "CHECKPOINT")
#> [1] 0
DBI::dbExecute(con, "UPDATE time SET doy = doy.doy FROM doy WHERE (doy.month = time.month) AND (doy.day = time.day)")
#> [1] 1
DBI::dbGetQuery(con, "SELECT * FROM time WHERE doy<1 OR doy>1")
#> [1] month day   doy  
#> <0 rows> (or 0-length row.names)
DBI::dbGetQuery(con, "SELECT MIN(doy), MAX(doy) FROM time")
#>   min(doy) max(doy)
#> 1      501      501

DBI::dbDisconnect(con,shutdown=TRUE)
```

<sup>Created on 2022-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


So, @Mytherin here is the pure SQL script that reproduces the bug if database is in file instead of `:memory:`:
```sql
CREATE TABLE time(month INTEGER, day INTEGER, doy INTEGER, UNIQUE (month, day));
INSERT INTO time SELECT i AS month, i AS day, NULL AS doy FROM range(1025) tbl(i);
CREATE TABLE doy AS SELECT 1 AS month, 1 AS day, 1.0 AS doy;
CHECKPOINT;
UPDATE time SET doy = doy.doy FROM doy WHERE (doy.month = time.month) AND (doy.day = time.day);
SELECT * FROM time WHERE doy<1 OR doy>1;
SELECT MIN(doy), MAX(doy) FROM time;
```

So in the end for those two SELECT-queries there should not be any other values for _doy_ than 1 (and NULL), but with MIN/MAX invalid values (i.e. not equal to 1) can be seen.

**Comment by zippond** [comment]
It looks like for in-file database, the updates after a checkpoint are lost.
```sql
CREATE TABLE t(i int, j int);
# Insert >= 1024 NULLs
INSERT INTO t SELECT ii, NULL FROM range(1024) tbl(ii);
# checkpoint to trigger the issue
CHECKPOINT;
UPDATE t SET j = 1;
select * from t;
# Full of invalid values
#┌──────┬─────────────┐
#│  i   │      j      │
#├──────┼─────────────┤
#│ 0    │ -1094795586 │
#│ 1    │ -1094795586 │
#│ 2    │ -1094795586 │
# ...
```

**Comment by Mytherin** [comment]
I cannot reproduce either of these problems on the latest master using only the provided SQL scripts. Are you running this on an older version? This works fine for me:

```sql
D CREATE TABLE t(i int, j int);
D # Insert >= 1024 NULLs
D INSERT INTO t SELECT ii, NULL FROM range(2000) tbl(ii);
D # checkpoint to trigger the issue
D CHECKPOINT;
D UPDATE t SET j = 1;
D select * from t;
┌──────┬───┐
│  i   │ j │
├──────┼───┤
│ 0    │ 1 │
│ 1    │ 1 │
...
```
