### ISSUE TITLE
Load entire database into memory?

### ISSUE THREAD

**Issue by vedantroy** [duckdb/duckdb#4180]
I have a pretty small database: it's about 27 megs of data. It's just a 2 column database with column 1 being a key, and column 2 being some value.

The database feels sufficiently small such that I should be able to just load the entire thing into memory, which should be much faster than querying on disk.

Using the Python API, I can open the database on disk. But I was wondering if there was a way to copy the entire database into memory. I figured this might make resulting queries faster.

**Comment by Alex-Monahan** [comment]
Howdy!
Temporary tables are stored in memory (unless they exceed RAM, then they buffer to disk). So, you could just do:
```sql
Create temp table in_memory as
Select * from physical_table
``` 
and then query in_memory!
