### ISSUE TITLE
Suspect behavior when comparing dates and timestamps

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#4202]
### What happens?

When comparing dates and timestamps in a `where` clause the returned results don't match expectations. I'm not entirely sure this is a bug or if certain parts of this are behaving as expected.

### To Reproduce

```sql
create table t1 (date timestamp);
insert into t1 values ('2016-12-16T00:00:00.000Z');
insert into t1 values ('2020-02-17T23:59:59.998Z');
insert into t1 values ('2020-02-17T23:59:59.999Z');
insert into t1 values ('2020-02-18T00:00:00.000Z');
```

Compare a date and a timestamp
```sql
select * from t1 WHERE (date_trunc('DAY', T1.date) < ('2020-02-17T23:59:59.999Z'::timestamp));
```
Output
```
┌─────────────────────┐
│        date         │
├─────────────────────┤
│ 2016-12-16 00:00:00 │
└─────────────────────┘
```
For this part, I'm not sure this is a bug. However, my intuition (for whatever that's worth) says that the `.998` timestamp should also be included in the results here.

Compare a date (casted to a timestamp) and a timestamp.
```sql
select * from t1 WHERE (date_trunc('DAY', T1.date)::timestamp) < ('2020-02-17T23:59:59.999Z'::timestamp);
```
Output
```
┌─────────────────────┐
│        date         │
├─────────────────────┤
│ 2016-12-16 00:00:00 │
└─────────────────────┘
```
This does appear to be a bug.

However, if I'm totally off-base with these, please close this bug report.

### OS:

MacOS, Linux

### DuckDB Version:

0.4.0

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

Mode Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #4206.

**Comment by michaeljohnalbers** [comment]
@Mytherin For the first case where a date is compared against a timestamp, is it correct that the timestamp is essentially truncated to a date?

**Comment by Mytherin** [comment]
Both are bugs and both should be fixed by the PR.
