### ISSUE TITLE
Feature request -- Jaro/Jaro-Winkler string distance

### ISSUE THREAD

**Issue by ericmanning** [duckdb/duckdb#4217]
### Discussed in https://github.com/duckdb/duckdb/discussions/4194

<div type='discussions-op-text'>

<sup>Originally posted by **ericmanning** July 23, 2022</sup>
Text function feature request: Jaro-Winkler string distance metric with option for prefix weight. This metric is commonly used for fuzzy string matching. It can perform better than alternative string distance metrics (e.g., Levenshtein and Jaccard, which are already implemented in duckdb) for probabilistic record linkage with names and addresses.

Example implementation in C++ at [maxbachmann/JaroWinkler](https://github.com/maxbachmann/JaroWinkler).</div>

**Comment by lnkuiper** [comment]
Going to have a go at this while waiting for the CI in my other branch :)

**Comment by Mytherin** [comment]
Implemented now
