### ISSUE TITLE
.open :memory:, Error: unable to open database ":memory:": IO Error: Could not fetch available system memory!

### ISSUE THREAD

**Issue by PolywickStudio** [duckdb/duckdb#4221]
### What happens?

1. Downloaded duckdb_cli-windows-amd64.zip
2. Unzipped.
3. Attempted to run duckdb.exe

Got error:
D .open :memory:
Error: unable to open database ":memory:": IO Error: Could not fetch available system memory!

### To Reproduce

D .open :memory:
Error: unable to open database ":memory:": IO Error: Could not fetch available system memory!

### OS:

Windows

### DuckDB Version:

v0.4.0 da9ee490d

### DuckDB Client:

v0.4.0 da9ee490d

### Full Name:

SallyP

### Affiliation:

Polywick Graphics, PH, Corp.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by PolywickStudio** [comment]
D CREATE TABLE swimmers AS SELECT 'duck' as animal;
Error: unable to open database ":memory:": IO Error: Could not fetch available system memory!

**Comment by Mause** [comment]
This looks like a duplicate of https://github.com/duckdb/duckdb/issues/3079, which is fixed in master, can you test that the master build works as expected?

**Comment by PolywickStudio** [comment]
Confirmed fixed in master.
