### ISSUE TITLE
.save filename sqlite3_backup_init: unsupported.

### ISSUE THREAD

**Issue by PolywickStudio** [duckdb/duckdb#4222]
### What happens?

On master (as of 27th July 2022), duckdb.exe gave error message on saving the database:

D .save filename
sqlite3_backup_init: unsupported.

### To Reproduce

1. Get the build from Github CI Actions/Windows.
2. Download Windows Build Artifacts
3. Extract duckdb.exe from ZIP file. 
4. Run a few queries.
5. enter:  .save filename.

An error message pops up
:sqlite3_backup_init: unsupported.

### OS:

Windows

### DuckDB Version:

master 346bd2b

### DuckDB Client:

master 346bd2b

### Full Name:

SallyP

### Affiliation:

Polywick Graphics, PH, Corp.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by iagovar** [comment]
Same, tried with the last linux version. I didn't install it but used through the binary in Xubuntu.

**Comment by Alex-Monahan** [comment]
Today, this is expected as it has not been implemented. The best practice is to connect to a persistent db at the start rather than start in memory and save later!

**Comment by iagovar** [comment]
> 

Hm, how exactly?, it starts as in-memory. Do you mean to connect an SQLite db file or something?

I'm not using it in python (for now), as I'm learning SQL, I'm interested in OLAP particularly, and I was wondering if I could use DuckDB for later projects.

**Comment by PolywickStudio** [comment]
I can close this... I'm not using DuckDB and I wish it's authors well in it's future endevours...
