### ISSUE TITLE
Not able to use DuckDB on AWS Glue

### ISSUE THREAD

**Issue by santanuhaldar** [duckdb/duckdb#4231]
am using AWS Glue 2.0 (python 3.8). 
However I am not able to import duckdb into my program.

I tried adding extra python parameters but always fails with the numpy dependency. Are you able to advise. Need a sample AWS Glue code with one liner "import duckdb" and the settings.

**Comment by Mause** [comment]
Can you please provide all the information requested in the bug report template?

**Comment by santanuhaldar** [comment]
Sure, where can I find the template ?

**Comment by Mause** [comment]
@santanuhaldar https://github.com/duckdb/duckdb/issues/new?assignees=&labels=&template=bug_report.yml

**Comment by santanuhaldar** [comment]
What happens?

import duckdb
on Python module fails when using AWS glue service. Gives below error:
No matching distribution found for numpy>=1.14

Added whl packages for both numpy and duckdb on extra-Python-files and file locations

To Reproduce
Run
Import duckdb in AWS glue Python code

environment:AWS
Service Glue, version 2


reporter : Santanu Haldar

**Comment by santanuhaldar** [comment]
Thanks, created issue #4232
