### ISSUE TITLE
Not able to use DuckDB on AWS Glue

### ISSUE THREAD

**Issue by santanuhaldar** [duckdb/duckdb#4232]
### What happens?

import duckdb
on Python module fails when using AWS glue service. Gives below error:
No matching distribution found for numpy>=1.14

Added whl packages for both numpy and duckdb on extra-Python-files and file locations

### To Reproduce

Run
Import duckdb in AWS glue Python code

environment:AWS
Service Glue, version 2

### OS:

Linux

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Santanu Haldar

### Affiliation:

Fannie Mae

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
You should probably be using pip to install the libraries, rather than downloading the wheels yourself - try following the instructions here https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#addl-python-modules-support

**Comment by santanuhaldar** [comment]
Thanks @Mause : I tried Installing additional Python modules in AWS Glue 2.0 with pip (as you suggested), but it fails . Error: module not found: duckdb
Can you please help. Thanks so much for all your assistance

**Comment by Mause** [comment]
So you did

```
"--additional-python-modules", "duckdb"
```

and you got "module not found: duckdb"?

**Comment by santanuhaldar** [comment]
Yes.
Tried that and a couple of other options.
> 
> "--additional-python-modules", "duckdb-0.4.0”
Also tried with placing the whl in s3 and then referencing it in the additional Python modules


Thanks,
Santanu Haldar

**Comment by Mause** [comment]
I'll be honest, I'm not sure if this is related to duckdb specifically, it seems to be an issue with the platform you're using, and you're probably better off seeking support for the platform itself

**Comment by RobinL** [comment]
We use duckdb successfully in AWS glue using version 3.0:

![image](https://user-images.githubusercontent.com/2608005/182606325-8ce79d2b-cc8e-4443-acea-ffac8338dace.png)

**Comment by santanuhaldar** [comment]
Thanks, i am able to do so now with your help :) Please help close out the issue. Thanks again so much for all your help.

**Comment by benymahajan** [comment]
Hi @RobinL and @hannes : I am trying to add this as --additional-python-modules == 0.5.1 and not able to make it work,  Is that a Python shell job or Glue Spark job?
Would this work in glue epythonshell job?

**Comment by sandipsinha** [comment]
Hi @RobinL   we are trying to use DuckDB for reading a parquet folder on s3 using this syntax 
df = cursor.execute(f"""INSTALL httpfs;LOAD httpfs;SET s3_region='us-west-2';SET s3_access_key_id='<xxxx>';SET s3_secret_access_key='<YYYY'>;SELECT * FROM read_parquet('https://<bucket-name>.s3.us-west-2.amazonaws.com/client/merative/bronze_raw_facility_header_claims/');""").df() and it giving me this error
RuntimeError: Unable to connect to URL "https://<bucketname>.s3.us-west-2.amazonaws.com/client/merative/bronze_raw_facility_header_claims/": 403 (Forbidden). Any insight would be really appreciated

**Comment by RobinL** [comment]
The . after https:// doesn't look right to me?

**Comment by sandipsinha** [comment]
I think it was while copying and pasting here in this page. Here I tried it again 
df = cursor.execute(f"""INSTALL httpfs;LOAD httpfs;SET s3_region='us-west-2';SET s3_access_key_id='xxxxxx';SET s3_secret_access_key='yyyyy';SELECT * FROM read_parquet('https://sandbox-mededatalake-source.s3.us-west-2.amazonaws.com/client/merative/bronze_raw_facility_header_claims/');""").df() and got this error
RuntimeError: Unable to connect to URL "https://sandbox-mededatalake-source.s3.us-west-2.amazonaws.com/client/merative/bronze_raw_facility_header_claims/": 403 (Forbidden)

**Comment by Mause** [comment]
Your URL doesn't look like it refers to a single parquet file, are you sure it's correct?

Also please make sure you're using a recent version of DuckDB

**Comment by sandipsinha** [comment]
Yes, I am trying to read the entire folder. Its a big file and it is grouped into smaller chunks. I have the latest version of DuckDB which is 0.9 I believe ?

**Comment by Mause** [comment]
> Yes, I am trying to read the entire folder. Its a big file and it is grouped into smaller chunks. I have the latest version of DuckDB which is 0.9 I believe ? 

It may just be the fact that you're not formatting the code in your comment correctly then
