### ISSUE TITLE
duckdb_append_blob error without error message

### ISSUE THREAD

**Issue by calvin2021y** [duckdb/duckdb#4249]
### What happens?

The blob data is 

```sh
[ 10,2,51,57,82,10,158,8,185,41,165,3,180,61,184,18,88,232,132,1,104,251,1,] 
```

### To Reproduce

call with `duckdb_append_blob(pConn.order_appender, ptr, size);` return 1,  

but `duckdb_appender_error(pConn.order_appender),` return null

### OS:

linux

### DuckDB Version:

v0.4.0

### DuckDB Client:

c api

### Full Name:

calvin

### Affiliation:

self

### Have you tried this on the latest `master` branch?

not yet, can not build it

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by calvin2021y** [comment]
since I can not user appender, then I try insert query.  it take 12ms to finish for insert one record.  this is far more too slow compare to sqlite.

Is there a way to improve insert speed ?

**Comment by Mytherin** [comment]
Thanks, I have pushed a fix in #4250.

In the future could you try to build the master release and provide a complete reproducible example? It is not particularly difficult to build DuckDB, and if you do not make a minimum effort towards the maintainers when submitting issues we might close them without addressing them.

**Comment by Mytherin** [comment]
> since I can not use appender, then I try insert query. it take 12ms to finish for insert one record. this is far more too slow compare to sqlite.
> 
> Is there a way to improve insert speed ?

You might consider reading [the documentation](https://duckdb.org/docs/data/overview).

**Comment by calvin2021y** [comment]
> Thanks, I have pushed a fix in #4250.
> 
> In the future could you try to build the master release and provide a complete reproducible example? It is not particularly difficult to build DuckDB, and if you do not make a minimum effort towards the maintainers when submitting issues we might close them without addressing them.

Thanks for the tips, I am try build it now.

can you give a tips about give call cpp api to append int4[] list ? I will try build with this function to provide a c api to append list|array.

I plan use duckdb_append_list(appender, base_ptr, size,  size_of_element);

**Comment by Mytherin** [comment]
The way I would go about building this function is using the `duckdb_value` class, which can then be constructed programmatically through functions such as e.g.:

```cpp
// create an int64 value (this exists)
duckdb_value duckdb_create_int64(int64_t val);

// create a list value (this will need to be created)
duckdb_value duckdb_create_list(duckdb_value *values, idx_t size);
```

Then you could create a `duckdb_append_value` function, e.g.:

```cpp
// append a duckdb_value (this will need to be created)
duckdb_state duckdb_append_value(duckdb_appender appender, duckdb_value value);
```

This will not be the fastest way of inserting lists, but the API would be relatively easy/straightforward to use.

**Comment by calvin2021y** [comment]
Is there a way to disable duckdb_mbedtls ? the size is too bigger.

**Comment by calvin2021y** [comment]
If I build lto release, I get asan symbol not find error. (even I disable all Cmake san option)
for libduckdb.so, thre is cxx symbol but not c symbol exported.

**Comment by changloong** [comment]
I made the master debug append blob work, take 14ms for insert one record. still very slow.  

I must do the batch insert to speed it up?

**Comment by calvin2021y** [comment]
```cc
duckdb_state duckdb_append_int32_array(duckdb_appender appender, const int *data, idx_t length) {
    if( length == 0 ) {
        auto empty_list_value = duckdb::Value::EMPTYLIST(duckdb::LogicalType::LIST(duckdb::LogicalType::INTEGER));
        return duckdb_append_internal<duckdb::Value>(appender, empty_list_value);
    }
    duckdb::vector<int> values;
    for(int i = 0; i < length; i++) {
        values.push_back(data[i]);
    }
    auto list_value = duckdb::Value::LIST(duckdb::LogicalType::LIST(duckdb::LogicalType::INTEGER), move(values));
    return duckdb_append_internal<duckdb::Value>(appender, list_value);
}
```

any tips to fix this error:
```sh
In file included from src/main/capi/ub_duckdb_main_capi.cpp:2:
src/main/capi/appender-c.cpp:204:20: error: no matching function for call to 'LIST'
        auto list_value = duckdb::Value::LIST(duckdb::LogicalType::LIST(duckdb::LogicalType::INTEGER), values);
                          ^~~~~~~~~~~~~~~~~~~
src/include/duckdb/common/types/value.hpp:147:26: note: candidate function not viable: no known conversion from 'vector<int>' to 'vector<duckdb::Value>' for 2nd argument
        DUCKDB_API static Value LIST(LogicalType child_type, vector<Value> values);
                                ^
src/include/duckdb/common/types/value.hpp:145:26: note: candidate function not viable: requires single argument 'values', but 2 arguments were provided
        DUCKDB_API static Value LIST(vector<Value> values);
```

**Comment by calvin2021y** [comment]
after I insert into database, I can not find a way to get the list data from duckdb_result with c api, there is no function like duckdb_value_list

**Comment by calvin2021y** [comment]
assert error from this line: ` return result->__deprecated_columns[col].__deprecated_nullmask[row];`, with list object

column is `INT1[] NOT NULL`

```c
bool duckdb_value_is_null(duckdb_result *result, idx_t col, idx_t row) {
    if (!CanUseDeprecatedFetch(result, col, row)) {
        return false;
    }
    return result->__deprecated_columns[col].__deprecated_nullmask[row];
}
```

**Comment by calvin2021y** [comment]
GetInternalCValue has no list type, please give some tips, I will try add to it.
