### ISSUE TITLE
Inconsistent handling of pandas.NA values/dtypes - frame registration fails on Linux (only)

### ISSUE THREAD

**Issue by alexander-beedie** [duckdb/duckdb#4261]
### What happens?

I realize that [pandas.NA values](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data) aren't _entirely_ canonical at this point, but would be great if they could work - and, in fact, it seems like they _do_ partially work already, just not consistently across platforms or dtypes.

Specifically, I am able to register a dataframe containing `Float64Dtype` cols (introduced in pandas v1.2.0 at the end of 2020) on both Mac and Windows platforms, but _not_ on Linux where I get `RuntimeError: unsupported python type Float64`. Note that registering frames containing `Int64Dtype` (which also supports `NA` values) succeeds on all three platforms.

On the platforms where frame registration succeeds, the `NA` values get reinterpreted as `NaN` when exporting back out (for both `Int64Dtype` and `Float64Dtype`).

### To Reproduce

```python
import pandas as pd
import duckdb as dd

df = pd.DataFrame({
    "x":[None,5.5,10.0],
    "y":[0.0,None,5.0],
}).astype( 
    pd.Float64Dtype(),
)

#       x     y
# 0  <NA>   0.0
# 1   5.5  <NA>
# 2  10.0   5.0

conn = dd.connect()
conn.register( "df",df )  # << succeeds on mac & windows, fails on linux with...

# ----------------------------------------------------------------------------
# Traceback (most recent call last)
# RuntimeError                              
#   conn = dd.connect()
# ---> conn.register( "df",df )
# 
# RuntimeError: unsupported python type Float64
```
Subsequently, on the platforms where frame registration succeeds (eg: Mac), the `NA` values are not preserved when querying; they get reinterpreted as `NaN`, eg:

```python
conn.execute("SELECT * FROM df").df()

#       x    y
# 0   NaN  0.0     << pandas.NA reinterpreted as NaN
# 1   5.5  NaN
# 2  10.0  5.0
```

Would be great if frame registration succeeded on Linux (and even better if the `NA` values could be preserved, though I can handle that locally if necessary  ;).

### OS:

Linux (fails), Windows & Mac (succeeds)

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Alexander Beedie

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
@Tishj will take this over

**Comment by Tishj** [comment]
Hmm if I recall correctly, I added support for Float32 and Float64 type in #3985. Could you try to reproduce this issue with the latest version of master?

Apologies if you already did that, but it says 0.4.0 in the "DuckDB Version" section so I wanted to make sure.

As for the conversion to NaN, I believe that is currently intended behavior.

**Comment by alexander-beedie** [comment]
> Hmm if I recall correctly, I added support for Float32 and Float64 type in #3985. Could you try to reproduce this issue with the latest version of master? You can do so by running `pip install duckdb --upgrade --pre`

Ahhh so I compiled `master` on my local/build machine while testing, but as that's a Mac rather than a Linux box it unfortunately doesn't exhibit the behavior seen on the AWS/Linux box running tests. I don't think I can create a build/compile environment there, so I tried the suggested `pip install duckdb --upgrade --pre` route and it appeared to just reinstall 0.4.0. I did see a `0.4.1.dev1911` package listed (via PyCharm funnily enough), but it doesn't appear to be installable, so not sure how the listing appeared.

```python
pip install duckdb==0.4.1.dev1191 --no-cache-dir --pre
# ERROR: Could not find a version that satisfies the requirement duckdb==0.4.1.dev1191 
#  (from versions: ... 0.3.5.dev1406, 0.3.5.dev1408, 0.3.5.dev1410, 0.4.0)
```
If you can think of a way to pip install `master` any other way will be more than happy to try it out and confirm.

(With the locally-compiled package I see that a semi-related issue -about to raise separately- _is_ still present, which is the slightly surprising conversion of float(+/-inf) values to NaN).

**Comment by Tishj** [comment]
Hmm I don't, other than building it manually..
If you're interested in trying that, you can build duckdb by cloning the repo, calling `make release BUILD_PYTHON=1` from the root repository.
(You might want to uninstall the pip-installed version first)

To verify that it is installed properly, you can open up python3 `import duckdb` and look at the `duckdb.__file__` return value.
Mine currently looks something like `... site-packages/duckdb-0.4.1.dev1158 ...`

**Comment by alexander-beedie** [comment]
> If you're interested in trying that, you can build duckdb by cloning the repo, calling `make release BUILD_PYTHON=1` from the root repository. (You might want to uninstall the pip-installed version first)

Bit the bullet; got enough permissions to download and start compiling CMake from source on the relevant linux box, so that I can subsequently compile duckdb, heh. Will see how it goes ;)

> I'll have a look at the +/inf -> NaN issue in the meantime :)

Fantastic - much appreciated.

**Comment by Mause** [comment]
> > Hmm if I recall correctly, I added support for Float32 and Float64 type in #3985. Could you try to reproduce this issue with the latest version of master? You can do so by running `pip install duckdb --upgrade --pre`
> 
> Ahhh so I compiled `master` on my local/build machine while testing, but as that's a Mac rather than a Linux box it unfortunately doesn't exhibit the behavior seen on the AWS/Linux box running tests. I don't think I can create a build/compile environment there, so I tried the suggested `pip install duckdb --upgrade --pre` route (on that remote box) and it appeared to just reinstall 0.4.0. I did see a `0.4.1.dev1911` package listed (via PyCharm funnily enough), but it doesn't appear to be installable, so not sure how the listing appeared.
> 
> ```python
> pip install duckdb==0.4.1.dev1191 --no-cache-dir --pre
> # ERROR: Could not find a version that satisfies the requirement duckdb==0.4.1.dev1191 
> #  (from versions: ... 0.3.5.dev1406, 0.3.5.dev1408, 0.3.5.dev1410, 0.4.0)
> ```
> If you can think of a way to pip install `master` any other way I am more than happy to try it out and confirm!
> 
> With my locally-compiled library I see that a (maybe?) semi-related issue _is_ still present, which is the unexpected conversion of float(+/-inf) values to NaN. (Update: raised https://github.com/duckdb/duckdb/issues/4287 for this one).

Try installing a version back or so? Unfortunately due to the duration of the CI builds, some architectures/OSs are uploaded an hour or two later than the source distributions

**Comment by alexander-beedie** [comment]
> > > Hmm if I recall correctly, I added support for Float32 and Float64 type in #3985. Could you try to reproduce this issue with the latest version of master? You can do so by running `pip install duckdb --upgrade --pre`
> > 
> > 
> > Ahhh so I compiled `master` on my local/build machine while testing, but as that's a Mac rather than a Linux box it unfortunately doesn't exhibit the behavior seen on the AWS/Linux box running tests. I don't think I can create a build/compile environment there, so I tried the suggested `pip install duckdb --upgrade --pre` route (on that remote box) and it appeared to just reinstall 0.4.0. I did see a `0.4.1.dev1911` package listed (via PyCharm funnily enough), but it doesn't appear to be installable, so not sure how the listing appeared.
> > ```python
> > pip install duckdb==0.4.1.dev1191 --no-cache-dir --pre
> > # ERROR: Could not find a version that satisfies the requirement duckdb==0.4.1.dev1191 
> > #  (from versions: ... 0.3.5.dev1406, 0.3.5.dev1408, 0.3.5.dev1410, 0.4.0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you can think of a way to pip install `master` any other way I am more than happy to try it out and confirm!
> > With my locally-compiled library I see that a (maybe?) semi-related issue _is_ still present, which is the unexpected conversion of float(+/-inf) values to NaN. (Update: raised #4287 for this one).
> 
> Try installing a version back or so? Unfortunately due to the duration of the CI builds, some architectures/OSs are uploaded an hour or two later than the source distributions

It's ok - I've now got cmake bootstrapped and successfully compiled on the target box, and the latest `duckdb` is compiling from master as we speak. Should be able to test shortly  ;)

**Comment by alexander-beedie** [comment]
@Tishj / @Mause: good news - `make` compiled, `duckdb` compiled and, even better, I can confirm that the issue **is** actually fixed on Linux in the latest master branch! Closing this issue, with thanks for the various suggestions.

(Any -rough- idea when the latest code will make it out as a new release?)

**Comment by Mause** [comment]
> @Tishj / @Mause: good news - `make` compiled, `duckdb` compiled and, even better, I can confirm that the issue _is_ actually fixed on Linux in the latest master branch! Closing this issue, with thanks for the various suggestions.
> 
> (Any -rough- idea when the latest code will make it out as a new release?)

Woo! 

I believe the next full release is scheduled for September?

**Comment by alexander-beedie** [comment]
> I believe the next full release is scheduled for September?

I'll keep my eyes peeled  ;)
