### ISSUE TITLE
duckdb to/from pandas does not preserve timezone awareness

### ISSUE THREAD

**Issue by erinov1** [duckdb/duckdb#4267]
### What happens?

duckdb preserves timezone-awareness during to/from arrow conversion, but the same information is lost when converting to/from pandas.

### To Reproduce

```python
# Create pandas DataFrame with timezone-aware timestamp column and corresponding arrow table:
import duckdb
import pandas as pd
import pyarrow as pa

df = pd.DataFrame(
    {"timestamp": [pd.Timestamp("2022-01-01", tz="America/New_York")]}
)
arrow_table = pa.Table.from_pandas(df)

con = duckdb.connect()

# duckdb to/from arrow preserves timezone awareness:
con.execute("DESCRIBE (SELECT * FROM arrow_table)").fetchall()
# Output:
# [('timestamp', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None)]
con.execute("SELECT * from arrow_table").fetch_arrow_table()
# Output:
# pyarrow.Table
# timestamp: timestamp[us, tz=UTC]
# ----
# timestamp: [[2022-01-01 05:00:00.000000]]

# duckdb to/from pandas drops timezone awareness:
con.execute("DESCRIBE (SELECT * FROM df)").fetchall()
# Output:
# [('timestamp', 'TIMESTAMP', 'YES', None, None, None)]
con.execute("SELECT * from arrow_table").df().dtypes
# Output:
# timestamp    datetime64[ns]
# dtype: object
```

### OS:

OSX

### DuckDB Version:

0.4.1.dev1115 (and 0.4.0)

### DuckDB Client:

Python

### Full Name:

Erin Ovechkin

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
Hey @Tishj 

I'm going to work on this soon, so just checking you haven't started on this yet (given your previous comment I'm not sure)

**Comment by Tishj** [comment]
@pdet Ah no worries, I just saw pandas + timezone so I wanted to verify that it wasn't caused by me, figured I'd post my findings.

**Comment by pdet** [comment]
alright
