### ISSUE TITLE
arrow dictionary does not get converted to duckdb ENUM

### ISSUE THREAD

**Issue by erinov1** [duckdb/duckdb#4268]
### What happens?

I'm not sure if this is by design at the moment, but creating a duckdb table from an arrow table with a dictionary-encoded column behaves differently than a pandas dataframe with a categorical column. When creating from pandas, duckdb is aware of the categorical nature, but not when creating from arrow. This affects the roundtrip
```
arrow with dictionary ==> duckdb ==> arrow with dictionary
```

On the other hand, the trip

```
pandas with category ==> duckdb ==> (pandas with category) OR (arrow with dictionary)
```
works correctly.

### To Reproduce

```python
# Create pandas DataFrame with categorical column and corresponding arrow table
# with dictionary-encoded column
import duckdb
import pandas as pd
import pyarrow as pa

df = pd.DataFrame(
    {"categorical_col": ["A"]}, dtype="category"
)
arrow_table = pa.Table.from_pandas(df)
arrow_table.schema[0]
# Output: pyarrow.Field<categorical_col: dictionary<values=string, indices=int8, ordered=0>>

con = duckdb.connect()

# duckdb from pandas is aware of the categorical, and outputs correctly
# using both fetch_df() and fetch_arrow_table():
con.execute("INFO (SELECT * FROM df)").fetchall()
# Output: [('categorical_col', 'categorical_col', 'YES', None, None, None)]
con.execute("SELECT * from df").fetch_df().dtypes
# Output:
# categorical_col    category
# dtype: object
con.execute("SELECT * from df").fetch_arrow_table().schema
# Output:
# categorical_col: dictionary<values=string, indices=uint8, ordered=0>

# duckdb from arrow ignores the dictionary encoding:
con.execute("DESCRIBE (SELECT * FROM arrow_table)").fetchall()
# Output: [('categorical_col', 'VARCHAR', 'YES', None, None, None)]
con.execute("SELECT * from arrow_table").fetch_df().dtypes
# Output:
# categorical_col    object
# dtype: object


```

### OS:

OSX

### DuckDB Version:

0.4.1.dev1115 (and 0.4.0)

### DuckDB Client:

Python

### Full Name:

Erin Ovechkin

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
The Arrow Dictionary is not the same as an Enum Type, but rather similar to an internal vector representation type of DuckDB.

The main difference is that the keys are local to batches and not global to the whole column. Hence when consumed, the dictionary type is consumed as a vector with a selection vector, and not as an Enum type.

On the other hand, ENUMs can be exported as dictionary vectors.

**Comment by erinov1** [comment]
Thanks @pdet 
Does this mean that the failure of the roundtrip `arrow with dictionary ==> duckdb ==> arrow with dictionary` is likely to persist in future versions of duckdb?

**Comment by pdet** [comment]
Precisely.
