### ISSUE TITLE
"having" is not working: python binding

### ISSUE THREAD

**Issue by AdarshNamala** [duckdb/duckdb#4269]
### What happens?

I have been using duckdb for the last few months and love it.
Thank you for your work on this.

Using 'having' after 'group by' raises the following error:
"Binder Error: column df.grp must appear in the GROUP BY clause or be used in an aggregate function"

**#session_info.show():**
duckdb              0.4.1-dev1115
numpy               1.22.4
pandas              1.4.2
session_info        1.0.0

Click to view modules imported as dependencies

IPython             8.4.0
jupyter_client      7.3.4
jupyter_core        4.10.0

Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
Linux-5.15.0-1015-aws-x86_64-with-glibc2.35

Session information updated at 2022-08-01 16:28

### To Reproduce

import pandas as pd
import numpy as np
import duckdb 

con = duckdb.connect()

**#generate sample data**
n_rows=1000
data = {
'val':range(n_rows),
'grp':np.random.choice(['a','b','c'],n_rows)
}
df=pd.DataFrame(data)

**#query to reproduce the error**
_qry=f"""
```sql 
SELECT 
    grp,SUM(val) AS val
FROM df
GROUP BY ALL
HAVING grp=='a'
```
"""

con.execute(_qry).df()

### OS:

mac Monterey 12.4

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Adarsh

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Are you sure you don't mean

```sql
SELECT 
    grp,SUM(val) AS val
FROM df
GROUP BY a
HAVING grp=='a'
```
?

**Comment by Alex-Monahan** [comment]
Does it work with only 1 equals, and/or if you explicitly say `group by grp`?

**Comment by AdarshNamala** [comment]
> Does it work with only 1 equals, and/or if you explicitly say `group by grp`?

It does work with 'group by grp'. Thanks. 
It does not work when I use 'ALL' in the group by. 
using '='  instead of '==' does not change the outcome.
