### ISSUE TITLE
[substrait] missing type information in `base_schema` struct

### ISSUE THREAD

**Issue by gforsyth** [duckdb/duckdb#4276]
### What happens?

`get_substrait_json` is producing invalid substrait for simple queries.

for `SELECT * from lineitem` the `base_schema` should read
```
{
            base_schema {
              names: "l_orderkey"
              names: "l_partkey"
              names: "l_suppkey"
              names: "l_linenumber"
              names: "l_quantity"
              names: "l_extendedprice"
              names: "l_discount"
              names: "l_tax"
              names: "l_returnflag"
              names: "l_linestatus"
              names: "l_shipdate"
              names: "l_commitdate"
              names: "l_receiptdate"
              names: "l_shipinstruct"
              names: "l_shipmode"
              names: "l_comment"
              struct {
                types {
                  i64 {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  i64 {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  i64 {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  i64 {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  decimal {
                    scale: 2
                    precision: 15
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  decimal {
                    scale: 2
                    precision: 15
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  decimal {
                    scale: 2
                    precision: 15
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  decimal {
                    scale: 2
                    precision: 15
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  string {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  string {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  date {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  date {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  date {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  string {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  string {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                types {
                  string {
                    nullability: NULLABILITY_NULLABLE
                  }
                }
                nullability: NULLABILITY_REQUIRED
              }
            }
            named_table {
              names: "lineitem"
            }
          }
```

However the stringified proto from `get_substrait_json` reads

```
{
                    base_schema {
                      names: "l_orderkey"
                      names: "l_partkey"
                      names: "l_suppkey"
                      names: "l_linenumber"
                      names: "l_quantity"
                      names: "l_extendedprice"
                      names: "l_discount"
                      names: "l_tax"
                      names: "l_returnflag"
                      names: "l_linestatus"
                      names: "l_shipdate"
                      names: "l_commitdate"
                      names: "l_receiptdate"
                      names: "l_shipinstruct"
                      names: "l_shipmode"
                      names: "l_comment"
                    }
                    named_table {
                      names: "lineitem"
                    }
                  }
```

### To Reproduce

```
install 'substrait';
load 'substrait';
CALL dbgen(sf=0.1);
CALL get_substrait_json('SELECT * FROM lineitem LIMIT 10');
```

```python
In [1]: import duckdb

In [2]: con = duckdb.connect()

In [3]: con.execute("CALL dbgen(sf=0.1)")
Out[3]: <duckdb.DuckDBPyConnection at 0x7f28181def70>

In [4]: con.install_extension("substrait")

In [5]: con.load_extension("substrait")

In [6]: con.get_substrait("select * from lineitem limit 10;")
<elided>
In [7]: duckdb.__version__
Out[7]: '0.4.1-dev1155'
```

### OS:

Arch Linux

### DuckDB Version:

0.4.1-dev1155

### DuckDB Client:

Python

### Full Name:

Gil Forsyth

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
Hey Gil, I'm almost done implementing this,

just a couple of questions,

1) What's the actual difference between these bad boys?
```cpp
enum Type_Nullability : int {
  Type_Nullability_NULLABILITY_UNSPECIFIED = 0,
  Type_Nullability_NULLABILITY_NULLABLE = 1,
  Type_Nullability_NULLABILITY_REQUIRED = 2,
  Type_Nullability_Type_Nullability_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Type_Nullability_Type_Nullability_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
```

I take that ```NULLABILITY_NULLABLE``` means that field might present null values and ```NULLABILITY_REQUIRED``` does not? Not sure about the latter.

2) The Nullability refers to the table definition ( e.g., ```CREATE TABLE Persons ( ID int NOT NULL) ``` or if the actual data does not contain null values? I'm currently doing the latter since that will allow us to theoretically use this outside the table context (e.g., from when reading a parquet file, arrow objects, ...)

3) Should Varchar types also contain the max length field? In your example, it seems that strings do not contain them, but since I'm already accessing statistics, I'm outputting them. 
e.g., 
```json
types {
  varchar {
    length: 43
    nullability: NULLABILITY_NULLABLE
    }
  }
```

4) It seems that in your example the struct that holds the info about the columns, also has a nullability set, what does it mean and where does it come from?

**Comment by gforsyth** [comment]
> Hey Gil, I'm almost done implementing this,

:tada: awesome

> I take that `NULLABILITY_NULLABLE` means that field might present null values and `NULLABILITY_REQUIRED` does not? Not sure about the latter.

That's correct -- the naming generated by protobuf is insane, but yeah, it's effectively either "nullable" or "not nullable"



> 2\. The Nullability refers to the table definition ( e.g., `CREATE TABLE Persons ( ID int NOT NULL) ` or if the actual data does not contain null values?

It's the table definition

> 3\. Should Varchar types also contain the max length field? In your example, it seems that strings do not contain them, but since I'm already accessing statistics, I'm outputting them.

Yes, they should.  I'm not certain if it's _required_ but it's definitely a field that _can_ be specified (and might as well if you are looking it up already)


> It seems that in your example the struct that holds the info about the columns, also has a nullability set, what does it mean and where does it come from?

This also confused me.  But the definition is here: https://github.com/substrait-io/substrait/blob/main/proto/substrait/type.proto#L162-L166 and the nullability field is required.  In the context of specifying the column types, I don't think it makes sense for it to be anything besides `NULLABILITY_REQUIRED`

**Comment by pdet** [comment]
Aha, thanks for the quick answers!
