### ISSUE TITLE
Unexpected conversion of `float(+/-inf)` to `NaN`

### ISSUE THREAD

**Issue by alexander-beedie** [duckdb/duckdb#4287]
### What happens?

Floating point values `+/- inf` (typically valid for pandas/postgres/arrow/etc) are being unexpectedly converted to NaN when loaded (and then queried) from a pandas DataFrame.

### To Reproduce

```python
import pandas as pd
import duckdb as dd

df = pd.DataFrame( 
    {"to_infinity_and_beyond":[float('inf'),0,float('-inf')]}
)
#    to_infinity_and_beyond
# 0                     inf
# 1                     0.0
# 2                    -inf

conn = dd.connect()
conn.register( "df",df )
conn.execute("SELECT * FROM df").df()
#
#    to_infinity_and_beyond
# 0                     NaN     << +inf unexpectedly became NaN
# 1                     0.0
# 2                     NaN     << -inf unexpectedly became NaN

conn.execute( "SELECT * FROM df" ).arrow()
#
# pyarrow.Table
# to_infinity_and_beyond: double
# ----
# to_infinity_and_beyond: [[null,0,null]]   << +/- inf unexpectedly became null
```

### OS:

Tested on `macOS 12.5` & `Ubuntu Linux (5.13.0-1021-aws)`

### DuckDB Version:

`0.4.0` (and latest compiled `master` branch)

### DuckDB Client:

Python

### Full Name:

Alexander Beedie

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Here is a relevant prior PR!
https://github.com/duckdb/duckdb/pull/3292

**Comment by alexander-beedie** [comment]
> Here is a relevant prior PR!
> #3292

Nice find; narrowing down, it looks like the issue probably occurs when reading the original `inf` values from the DataFrame, as the query/export code is able to handle both values:

```python
conn.execute("SELECT *, 'Inf'::double as inf_pos, '-Inf'::double as inf_neg FROM df").df()

#    to_infinity_and_beyond  inf_pos  inf_neg
# 0                     NaN      inf       -inf
# 1                     0.0      inf       -inf
# 2                     NaN      inf       -inf
```

**Comment by Tishj** [comment]
Aha, it's because this is used when checking if the value is Null
```
   83   template <>
   84   bool ValueIsNull(double value) {
-> 85           return !Value::DoubleIsFinite(value);
   86   }
   ```
   
   And of course, it's not finite

**Comment by alexander-beedie** [comment]
> ... after changing this check to use std::isnan() instead:
> 
> ```python
> ➜  duckdb git:(pandas_inf_fix) ✗ python3 panda_inf.py             
> to_infinity_and_beyond
> 0                     inf
> 1                     0.0
> 2                    -inf
> ```

Nice one - thanks very much for taking a look  :)
