### ISSUE TITLE
PyArrow integration raises OSError's

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#4291]
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow\ipc.pxi", line 682, in pyarrow.lib.RecordBatchReader.read_next_batch
  File "pyarrow\error.pxi", line 115, in pyarrow.lib.check_status
OSError: Query Failed
```

_Originally posted by @eeroel in https://github.com/duckdb/duckdb/pull/4283#discussion_r936499938_

**Comment by pdet** [comment]
Is it a DuckDB problem that PyArrow raises OSEerrors?

**Comment by Mause** [comment]
It's not very friendly for application code that consumes the duckdb api, as it means doing string matching to figure out/categorise the issue

**Comment by pdet** [comment]
Hm, so in this case we have to map whatever it comes to an runtime error of sorts? and just pass on the message?

**Comment by Mause** [comment]
If you mean `RuntimeError`, no, that's worse. Ideally it would throw an arrow or duckdb exception
