### ISSUE TITLE
Set operations on big dataframes in R: query failure

### ISSUE THREAD

**Issue by irenenuevo** [duckdb/duckdb#4292]
I’ve started using DuckDB to perform set operations (union, intersection, difference) on big dataframes in R (8 columns, 150.000.000 to 500.000.000 rows).

I started with 100.000.000, then gradually increased the number of rows and everything goes fine until I reach a sort of upper limit, that unfortunately doesn’t meet my goal.

Below, I reproduced the issue with some simple dummy data, looking for any suggestion on how to overcome the problem.

**My Environment:**
Win10 Pro 21H2 x64
RAM 32,0 GB
Intel(R) Core(TM) i9-10900F CPU @ 2.80GHz   2.81 GHz
R version 4.1.2 x64
RStudio 2022.07.1 Build 554  [Environment 32764 MiB]
duckdb 0.5.0

**To reproduce**
```
library(RcppAlgos)
library(arrow)
library(duckdb)`
con = dbConnect(duckdb(),dbdir="~/my-duckdb.duckdb",config = list("memory_limit = '20GB'"))
dummydata1<-comboGeneral(sample.int(100,42),8,TRUE)
dim(dummydata1)
```
[1] 450978066         8
```
dummydata1<-as.data.frame(dummydata1)
gc()
object.size(dummydata1)
```
14431299680 bytes
```
dbWriteTable(con, "dummydata1", dummydata1, overwrite = TRUE)
>Error: rapi_execute: Failed to run query
>Error: std::bad_alloc
```
To overcome this error I register the data instead of writing them on the database

```
duckdb_register(con, "dummydata1", dummydata1)
gc()
dummydata2<-comboGeneral(sample.int(100,38),8,TRUE)
dim(dummydata2)
```
[1] 215553195         8
```
dummydata2<-as.data.frame(dummydata2)
gc()
object.size(dummydata2)
```
6897703840 bytes
```
duckdb_register(con, "dummydata2", dummydata2)
rm(dummydata1,dummydata2)
gc()

>union
test<-dbGetQuery(con, "SELECT * FROM dummydata1 UNION SELECT * FROM dummydata2")
>Error: rapi_execute: Failed to run query
>Error: std::bad_alloc

>intersection
test2<-dbGetQuery(con, "SELECT * FROM dummydata1 INTERSECT SELECT * FROM dummydata2")
>Error: rapi_execute: Failed to run query
>Error: std::bad_alloc

>difference
test3<-dbGetQuery(con, "SELECT * FROM dummydata1 EXCEPT SELECT * FROM dummydata2")
>Error: rapi_execute: Failed to run query
>Error: std::bad_alloc
```
SECOND TRY, QUERYING DIRECTLY FROM PARQUET FILES
```
dummydata1<-comboGeneral(sample.int(100,42),8,TRUE)
dummydata1<-as.data.frame(dummydata1)
gc()
parquet <- file.path("~/dummydata1.parquet")
write_parquet(dummydata1, sink = parquet)
rm(dummydata1)
gc()
dummydata2<-comboGeneral(sample.int(100,38),8,TRUE)
dummydata2<-as.data.frame(dummydata2)
gc()
parquet <- file.path("~/dummydata2.parquet")
write_parquet(dummydata2, sink = parquet)
rm(dummydata2)
gc()
```
dummydata1.parquet = 39683 KB on disk
dummydata2.parquet = 19300 KB on disk
```
>union
test<-dbGetQuery(con, "SELECT * FROM '~/dummydata1.parquet' UNION SELECT * FROM '~/dummydata2.parquet'")
>Error: rapi_prepare: Failed to prepare query SELECT * FROM '~/dummydata1.parquet' UNION SELECT * FROM '~/dummydata2.parquet'
>Error: IO Error: No files found that match the pattern "~/dummydata1.parquet"

>intersection
test2<-dbGetQuery(con, "SELECT * FROM '~/dummydata1.parquet' INTERSECT SELECT * FROM '~/dummydata2.parquet'")
>Error: rapi_prepare: Failed to prepare query SELECT * FROM '~/dummydata1.parquet' INTERSECT SELECT * FROM '~/dummydata2.parquet'
>Error: IO Error: No files found that match the pattern "~/dummydata1.parquet"

#difference
test3<-dbGetQuery(con, "SELECT * FROM '~/dummydata1.parquet' EXCEPT SELECT * FROM '~/dummydata2.parquet'")
>Error: rapi_prepare: Failed to prepare query SELECT * FROM '~/dummydata1.parquet' EXCEPT SELECT * FROM '~/dummydata2.parquet'
>Error: IO Error: No files found that match the pattern "~/dummydata1.parquet"
```
It seems that the parquet file doesn’t exist but it does!

**Comment by Mytherin** [comment]
Thanks for the report! Set operations internally use joins, and joins currently require one of the two sides to fit in memory. It seems that you are doing set operations between two large tables, which might cause problems. Perhaps @lnkuiper can have a look at the queries, as he is working on the out-of-core join (#4189).

With regards to the Parquet file not existing, perhaps replace `~` with the expanded path with your actual home directory?

**Comment by irenenuevo** [comment]
Thanks @Mytherin!
 
> With regards to the Parquet file not existing, perhaps replace `~` with the expanded path with your actual home directory?

With the expanded path it actually finds the file! Unfortunately the query doesn't work,

```
>Error: rapi_execute: Failed to run query
>Error: Out of Memory Error: could not allocate block of 262144 bytes (26843528659/26843545600 used)
```
even if when I launch the query, the memory is almost empty 

![Immagine](https://user-images.githubusercontent.com/108572664/183056429-c97beb6e-94a6-41a8-a25c-8e98ff30422c.jpg)

**Comment by irenenuevo** [comment]
> Thanks for the report! Set operations internally use joins, and joins currently require one of the two sides to fit in memory. It seems that you are doing set operations between two large tables, which might cause problems. Perhaps @lnkuiper can have a look at the queries, as he is working on the out-of-core join (#4189).

I had a look at #4189
@lnkuiper do you think your job could fix my issue?

**Comment by lnkuiper** [comment]
@irenenuevo I've looked into this, and the union uses `HASH_GROUP_BY`, not `HASH_JOIN`, and therefore does not support out-of-core (larger-than-memory) functionality (yet).

The intersection uses `HASH_JOIN`, which should now work (in the recent DuckDB 0.5.0 that includes my PR).

The difference also uses `HASH_JOIN`, but it's an `ANTI` join, which does not work with larger-than-memory hash tables (yet).

In the coming months, I will continue developing the hash join. In the future, we will also support out-of-core functionality for group by.

**Comment by irenenuevo** [comment]
@lnkuiper thank you, I'll update my duckdb version and try again with intersection

**Comment by omo** [comment]
(Unsolicited triage) A fix is made and no more problem is reported. Maybe time to close this. @lnkuiper
