### ISSUE TITLE
Support Tagged UNION Type

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#4302]
We want to add support for tagged union types to DuckDB. The tagged union would allow multiple types to co-exist within the same column, similar to the way a C-style union would work. Example syntax might be:

```sql
CREATE TABLE tbl(u UNION(i INTEGER, v VARCHAR));
INSERT INTO tbl VALUES (1);
INSERT INTO tbl VALUES ('hello');
SELECT * FROM tbl;
```

Internally union vectors should be represented as two vectors:

* A `tag` vector, which is a `uint8_t` (or `uint16_t`) vector
* A `data` vector, that holds the primary data of the elements union'd together in a C-like manner (i.e. each row in the data array has the maximum length of the child union elements, so in the union above the size of each row will be 16-bytes, the size of `string_t`).

There should be operations that access the individual union elements similar to a struct. The entries that have a different tag should return `NULL` instead. We should also be able to query the tag of the union, e.g.:

```sql
SELECT * FROM tbl;
-- 1, hello
SELECT u.i FROM tbl;
-- 1, NULL
SELECT u.v FROM tbl;
-- NULL, v
SELECT u.tag FROM tbl;
-- 0, 1
```

Unions of nested types are more challenging. In this case, we would want to store child vectors for each of the nested types. For example:

```sql
CREATE TABLE tbl(u UNION(l INTEGER[], s STRUCT(x INT, y INT)));
INSERT INTO tbl VALUES ([1, 2, 3, 4]);
INSERT INTO tbl VALUES ({'x': 42, 'y': 84});
-- union vector has three child vectors, one for the list and two for the struct
```

We can choose to either (1) leave empty spots for the child vectors for which the tag does not apply, or (2) [likely more efficient] only add elements to the union vectors for which the tag applies. Option two saves on storage, particularly if only a single tag is used, but complicates retrieval of individual tagged elements somewhat.

Optimizations should be applied that optimize unions for which only a single tag is used, both in storage and in vectors themselves. Ideally the performance of a union that only uses one of its types should be the same as using that type directly.

CC @Maxxen

**Comment by Tishj** [comment]
Could this not be achieved by ExtraTypeInfo?

Similar to how the ENUM type stores which strings are valid for this enum type, wouldnt it be possible to store a vector of LogicalTypes in an ExtraTypeInfo subclass?

And let the regular LogicalType+PhysicalType be the type that has the biggest PhysicalType?

**Comment by Maxxen** [comment]
> Could this not be achieved by ExtraTypeInfo?
> 
> Similar to how the ENUM type stores which strings are valid for this enum type, wouldnt it be possible to store a vector of LogicalTypes in an ExtraTypeInfo subclass?
> 
> And let the PhysicalType be that of the one that has the biggest PhysicalType?

I am not familiar with ExtraTypeInfo yet, but would it work for nested types as well (even other nested unions)? It seems to me like you would have to encode the entire nested schema then, and flattening the biggest physical type could end up with unfeasibly wide entries.

**Comment by Maxxen** [comment]
Im still processing all the implications of Marks design, but in my head I'm envisioning the internals to look somewhat like a combination of ListVector and StructVector, each "member" has its own child vector (like structs), and the data vector itself carries "entries" (like lists), except instead of offsets and lengths like `list_entry_t`, a `union_entry_t` has a tag/reference/index corresponding to the respective member vector.

**Comment by Tishj** [comment]
Hmm right, I was thinking more about a plain union and only at the Value level.
I hadn't considered how that would work in combination with tagging and within vectors..

But is there a use case for using a union as multiple different types within a single list?

**Comment by djouallah** [comment]
not sure if we are talking about the same thing, but union of tables with different number of columns is extremely common in data transformation, it will be great if DuckDB support it

**Comment by Mytherin** [comment]
That is unrelated to this issue, this is about a UNION type. DuckDB can union tables with a different number of columns as long as you yourself add NULLs where required, e.g.:

```sql
D create table integers(i integer, j integer);
D create table strings(j integer, k varchar);
D insert into integers values (1, 10);
D insert into strings values (20, 'hello world');
D SELECT i, j, NULL AS k FROM integers UNION ALL SELECT NULL as i, j, k FROM strings;
┌──────┬────┬─────────────┐
│  i   │ j  │      k      │
├──────┼────┼─────────────┤
│ 1    │ 10 │ NULL        │
│ NULL │ 20 │ hello world │
└──────┴────┴─────────────┘
```

If you think a different/special syntax for this would be better, then feel free to open up a discussion and we can talk about it in more detail.

**Comment by Maxxen** [comment]
Started implementation in #4426

**Comment by Mytherin** [comment]
Implemented now
