### ISSUE TITLE
pg_get_constraintdef overload - second parameter should be optional

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#4318]
### What happens?

`pg_get_constraintdef` should optionally accept the second parameter, `pretty_bool`, instead of enforcing it.

Looking into how it's defined in https://github.com/duckdb/duckdb/blob/ca395eda2944a7c69cb4353041799cd92903e663/src/catalog/default/default_functions.cpp, it looks like changes are required in https://github.com/duckdb/duckdb/blob/02e395fd33dcd62fa8afcb7a1e60866451948e62/src/planner/binder/expression/bind_columnref_expression.cpp, and I'm happy to make those changes, I just require guidance on the exact changes

### To Reproduce

Enable https://github.com/duckdb/duckdb/blob/master/test/sql/pg_catalog/sqlalchemy.test#L324-L337 on master build

### OS:

Linux

### DuckDB Version:

0.4.1.dev1300

### DuckDB Client:

Python

### Full Name:

Elliana May

### Affiliation:

DuckDB Engine

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
FWIW this blocks https://github.com/Mause/duckdb_engine/issues/330

**Comment by Mytherin** [comment]
We should be able to define default macros with default values, e.g. by replacing the input parameter with `pretty_bool=0` (or similar). Ideally this is done in the macro construction code there. 

@lnkuiper do macros support default positional parameters? If not we might have to add support for that as well as part of this fix.

**Comment by lnkuiper** [comment]
Macro's expect positionals (without default value), followed by parameters with a default value. Parameters with a default value cannot be used positionally, and must be named:
```sql
D create macro add_default(x, a := 1) as x + a;
D select add_default(41);
┌─────────────────┐
│ add_default(41) │
├─────────────────┤
│ 42              │
└─────────────────┘
D select add_default(40, a := 2);
┌─────────────────────────┐
│ add_default(40, a := 2) │
├─────────────────────────┤
│ 42                      │
└─────────────────────────┘
D select add_default(40, 2);
Error: Binder Error: Macro function 'add_default(x)' requires a single positional argument, but 2 positional arguments were provided.
LINE 1: select add_default(40, 2);
```

**Comment by Mytherin** [comment]
Thanks for the explanation - I think the best way forward here is to add support for default positional parameters to macro functions, and then expose this functionality in the `default_functions.cpp`.

**Comment by Mytherin** [comment]
Implemented in https://github.com/duckdb/duckdb/pull/13258
