### ISSUE TITLE
Support UNION BY NAME

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#4320]
See #4308

We should support the `UNION BY NAME` operator to union together tables with re-ordered and potentially new columns. This operator is useful for unifying data from an evolving schema, where new columns have been added over time.

Example usage:

```sql
create table integers(i integer, j integer);
create table strings(j integer, k varchar);
insert into integers values (1, 10);
insert into strings values (20, 'hello world');
SELECT i, j FROM integers UNION BY NAME SELECT j, k FROM strings;
┌──────┬────┬─────────────┐
│  i   │ j  │      k      │
├──────┼────┼─────────────┤
│ 1    │ 10 │ NULL        │
│ NULL │ 20 │ hello world │
└──────┴────┴─────────────┘

-- equivalent to 
SELECT i, j, NULL AS k FROM integers UNION ALL SELECT NULL as i, j, k FROM strings;
```

Internally this should be a simple rewrite in `bind_setop_node.cpp` that pushes a projection to re-order columns, together with inserting constant `NULLs` were required with the appropriate names.

See also [here](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.unionByName.html) for how Spark supports this operation.

**Comment by Alex-Monahan** [comment]
This would be one more situation where I can replace Pandas in my workflows! Good stuff.

**Comment by lokax** [comment]
let me try 🦅

**Comment by PedroTadim** [comment]
This sounds like the `CORRESPONDING BY` clause, which is part of the SQL standard for set operators I believe.

**Comment by Mytherin** [comment]
Interesting, I have looked around a bit but could not find any good reference on this. Do you have any more info you could provide about the `CORRESPONDING BY` clause?

**Comment by PedroTadim** [comment]
Not much really. A few websites mention it: https://blog.jooq.org/a-rarely-seen-but-useful-sql-feature-corresponding/

**Comment by Alex-Monahan** [comment]
Hmm. Interesting! It looks like corresponding will not include column names that don't match. The SAS docs mention an "outer union" that can be used in combination with it to do that.
https://v8doc.sas.com/sashtml/proc/zueryexp.htm

It seems rare enough that we could use the keyword, but include all columns in the output. Or go our own path!

**Comment by hannes** [comment]
This is done
