### ISSUE TITLE
64 bit UBIGINTs in the Python API

### ISSUE THREAD

**Issue by rxm** [duckdb/duckdb#4329]
When I try to insert 2^63 into a column using the Python API, I get a `RuntimeError: Unable to cast Python instance to C++ type`.  If instead I use 2^63 -1, the limit for signed integers, it works.

A short piece of code that reproduces the issue in Python is:

``` python
import duckdb

con = duckdb.connect(database=':memory:')

con.execute("CREATE TABLE stuff(x UBIGINT)")

# DuckDB is ok with 2^63
con.execute("INSERT INTO stuff(x) VALUES (9223372036854775808)")
con.execute("SELECT x FROM stuff")
print(f'Inserted {con.fetchall()[0][0]} into the table')

# ... but from Python it will raise an error
con.execute("INSERT INTO stuff(x) VALUES (?)", (9223372036854775808,))

con.close()
```

This wouldn't work in Postgres or Sqlite3, as they do not have unsigned integers.

Not sure if this is expected behavior (to match some PEP or some other library), as I am a few hours old in using DuckDB.

I'm on macOS BigSur using DuckDB v0.4.0 da9ee490d (installed via pip install) on Python 3.8.9

**Comment by Tishj** [comment]
Hey thanks for the report, I do believe this is already fixed on master though.

Could you verify that the issue still happens there?

I recently added conversion to unsigned numerics, apart from HUGEINT all of them should work.

**Comment by rxm** [comment]
Thanks @Mytherin for looking into this.  Yes, when I use master, 2^64-1 works perfectly.
