### ISSUE TITLE
Hive partition pruning does not work with filter in ( )

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#4330]
### What happens?

hive partition works as expected when you use the where clause with equality in my case I partitioned the table lineitem using l_shipmode 

when I run the Query using where l_shipmode = 'air' it works fine, but when I use  l_shipmode in ( 'air' ) it return null values 

### To Reproduce

```
import duckdb 
con = duckdb.connect()
con.execute("PRAGMA default_collation='nocase'")

df =con.execute('''
PRAGMA enable_profiling ;
 select  distinct l_shipmode from read_parquet('C:/lineitem/*/*.parquet', HIVE_PARTITIONING=1) 
 where l_shipmode  in ( 'air' )
''').df()
print(df)
```

### OS:

windows 10

### DuckDB Version:

latest

### DuckDB Client:

Python

### Full Name:

mimoune djouallah 

### Affiliation:

personal 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by djouallah** [comment]
I think the issue is elsewhere, it seems con.execute("PRAGMA default_collation='nocase'")  does not apply when using in ( )

**Comment by Mytherin** [comment]
Related to #604

**Comment by hannes** [comment]
Maybe @samansmink can have a look? The main issue with `IN` lists is that they can be very large...

**Comment by djouallah** [comment]
it is still pretty annoying :)

**Comment by djouallah** [comment]
closed as duplicate
