### ISSUE TITLE
[Substrait] Full TPC-H support

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#4333]
I'm mainly creating this issue to keep track of where we are in the substrait TPC- Support.
There are 2 main goals here, 

1) Roundtripping Queries in DuckDB (i.e., Producing and Consuming Substrait proto queries only in DuckDB). 

2) Roundtripping Queries in DuckDB and Ibis (i.e., Ibis consuming queries produced by DuckDB, and DuckDB consuming queries produced by Ibis).

This issue will keep track of which queries are currently working and not-working.

**DuckDB Roundtrip [20/22]**

- [x] Q01
- [x] Q02
- [x] Q03
- [x] Q04
- [x] Q05
- [x] Q06
- [x] Q07
- [x] Q08
- [x] Q09
- [x] Q10
- [x] Q11
- [x] Q12
- [x] Q13
- [x] Q14
- [x] Q15
- [ ] Q16 (Substrait not supporting basic subquery flattening op: Chunk Get)
- [x] Q17
- [x] Q18
- [x] Q19
- [x] Q20
- [ ] Q21 (Substrait not supporting basic subquery flattening op: Delim Join)
- [ ] Q22 (Substrait not supporting basic subquery flattening op: Mark Join)

**Ibis (Producing) -> DuckDB (Consuming) [04/22]**
- [x] Q01
- [ ] Q02 (Ibis Compilation: 'TableArrayView)
- [ ] Q03 (Borked after Ibis/DuckDB upgrade to substrait v0.8)
- [ ] Q04 (Ibis Compilation: 'ExistsSubquery')
- [ ] Q05 (Borked after Ibis/DuckDB upgrade to substrait v0.8)
- [x] Q06
- [ ] Q07 (Ibis Compilation: (SelfReference(table=UnboundTable: nation)
- [ ] Q08 ( Ibis Compilation: (SelfReference(table=UnboundTable: nation) 
- [ ] Q09 (DuckDB Consumption: Unsupported expression type 10) 
- [ ] Q10 (Borked after Ibis/DuckDB upgrade to substrait v0.8)
- [ ] Q11 (Wrong results)
- [x] Q12
- [ ] Q13 (DuckDB Consumption: Catalog Error: Scalar Function with name not does not exist!)
- [ ] Q14 (Ibis Compilation: Parameter to MergeFrom() must be instance of same class: expected substrait.Expression got substrait) 
- [ ] Q15 (Ibis Compilation: non-empty child_rel_field_offsets passed in to selection translation rule) 
- [ ] Q16 (Ibis Compilation: 'IntegerColumn' object is not iterable) 
- [ ] Q17 (Ibis Compilation: <class 'ibis.expr.operations.relations.Aggregation'>) 
- [ ] Q18 (Ibis Compilation: 'IntegerColumn' object is not iterable) 
- [x] Q19
- [ ] Q20 (Ibis Compilation: 'IntegerColumn' object is not iterable) 
- [ ] Q21 (Ibis Compilation: 'ExistsSubquery')
- [ ] Q22 (Ibis Compilation: 'NotExistsSubquery')

**DuckDB (Producing) -> Ibis (Consuming)** (WIP) [0/22]
- [ ] Q01 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q02 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q03 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q04 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q05 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q06 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q07 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q08 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q09 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q10 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q11 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q12 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q13 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q14 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q15 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q16 (Substrait not supporting basic subquery flattening op: Chunk Get)
- [ ] Q17 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q18 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q19 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q20 (Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'>)
- [ ] Q21 (Substrait not supporting basic subquery flattening op: Delim Join)
- [ ] Q22 (Substrait not supporting basic subquery flattening op: Chunk Get)

**Comment by pdet** [comment]
@gforsyth I've created this issue as a tracker for myself.

I think we should have a look at queries 03/05/10 that stopped working after we both updated to the latest (at least last week latest? :-)) substrait version.

I did some digging on Q03, and it seems to me that the positional values of the join conditions are coming slightly off from ibis, not sure if that's the same reason for 05 and 10 yet.

**Comment by gforsyth** [comment]
This is great!  Thanks @pdet -- Looking at query 03 right now -- that looks like an issue on the Ibis side -- I can't round-trip that one and I'm getting a similar error to the one from duckdb, which is that we're attempting to cast a string to an int32

**Comment by gforsyth** [comment]
> I did some digging on Q03, and it seems to me that the positional values of the join conditions are coming slightly off from ibis, not sure if that's the same reason for 05 and 10 yet.

Yep, I can confirm this.  Trying to figure out when this started going sideways

**Comment by pdet** [comment]
@gforsyth "quick" questions,

I'm trying to build tests for Ibis consuming DuckDB plans, is there a quick (non-dirty) way to turn the bytes from 
``` python
proto = duck_con.get_substrait(query).fetchone()[0]
```
to
``` python
from ibis_substrait.compiler.decompile import decompile
(result,) = decompile(proto)
```
?

Also, do I need to do anything to load TPC-H on ibis? How that works?

**Comment by gforsyth** [comment]
Sure, so from `proto` which is the raw byte-string, you can do the following:

```python
from ibis_substrait.proto.substrait import plan_pb2

plan = plan_pb2.Plan()
plan.ParseFromString(proto)

from ibis_substrait.compiler.decompile import decompile
(result,) = decompile(plan)
```


> Also, do I need to do anything to load TPC-H on ibis? How that works?

ibis-substrait will give you back an ibis expression with unbound tables, so you shouldn't have to do anything since there isn't any data to "load"

**Comment by pdet** [comment]
> Sure, so from `proto` which is the raw byte-string, you can do the following:
> 
> ```python
> from ibis_substrait.proto.substrait import plan_pb2
> 
> plan = plan_pb2.Plan()
> plan.ParseFromString(proto)
> 
> from ibis_substrait.compiler.decompile import decompile
> (result,) = decompile(plan)
> ```
> 
> > Also, do I need to do anything to load TPC-H on ibis? How that works?
> 
> ibis-substrait will give you back an ibis expression with unbound tables, so you shouldn't have to do anything since there isn't any data to "load"

I see, that worked out, thanks! it seems that they are all failing due to varchar not being supported yet or substrait not supporting query flattening ops. 
```Ibis Consumption: unknown field type when decompiling: <class 'substrait.type_pb2.VarChar'> ```

**Comment by gforsyth** [comment]
Yeah, I just found that missing dispatch rule -- just got merged in.

**Comment by gforsyth** [comment]
ok, yeah, you can update to 2.9.6 now and it will handle the varchar dispatch

**Comment by pdet** [comment]
I did, now they break for different reasons.
```
AILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_01 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_02 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_03 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_04 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_05 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_06 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_07 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_08 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_09 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_10 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_11 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_12 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_13 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_14 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_15 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_17 - ValueError: Ibis Consumption: pop from an empty deque
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_18 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_19 - ValueError: Ibis Consumption: getattr(): attribute name must be string
FAILED test_duckdb_ibis_tpch.py::test_query_substrait_ibis_to_duck_20 - ValueError: Ibis Consumption: pop from an empty deque
```

**Comment by gforsyth** [comment]
> I did, now they break for different reasons.

that's progress!

I ran into this yesterday trying to deserialize messages from `duckdb`.  I think the `duckdb` substrait plans are missing some `output_type` fields.  Those are getting passed in as `None` in Python and then we are doing a `getattr` on a `None` and it's raising that error.

The `pop from` error is, I think, due to missing column names in the nested projections.

**Comment by pdet** [comment]
Hey @gforsyth, just a heads up, I spent the whole day today integrating the Substrait Validator and fixing issues with it, so wait for that before checking related to Ibis consuming DuckDB plans. I think we are getting pretty close (i.e., queries are now failing due to function name mismatching ValueError: Ibis Consumption: '*') :-).

Also, shout-out to @jvanstraten for creating/maintaining this tool, is making this process much easier.

**Comment by pdet** [comment]
Moving this issue to: https://github.com/duckdblabs/substrait/issues/4
