### ISSUE TITLE
Hive-Partitioning Filter Pushdown Slow?

### ISSUE THREAD

**Issue by spren9er** [duckdb/duckdb#4339]
### What happens?

This issue refers to #4211.

I have hive-partitioned data with partition keys `date` and `country` on my local machine.
There are 112 `date`-folders and within each `date`-folder 30 `country`-folders.
In each subfolder there is a single parquet file called `data.parquet`.

When I run a query like this 

```sql
SELECT COUNT(*) AS total
FROM parquet_scan('./*/*/data.parquet', HIVE_PARTITIONING=1)
WHERE date='2022-08-08' AND country='Germany'
```

it will take over 500ms[^1] in total.

Running following query directly on specific parquet file

```sql
SELECT COUNT(*) AS total
FROM parquet_scan('./date=2022-08-08/country=Germany/data.parquet')
```

takes under 10ms.

I expected the filter pushdown to be an order of magnitude faster.
Is there an optimization possible?

[^1]: _MacBook Pro 13'', 2020, 2.3GHz Quad-Core Intel Core i7, 32 GB_

### OS:

macOS 12.5

### DuckDB Version:

0.4.1.dev1533

### DuckDB Client:

Python

### Have you tried this on the latest `master` branch?

- [X] I agree

**Comment by SartorialOffense** [comment]
My understanding is that the the filter pushdown doesn't work yet for combinations of "Hived" and "non-Hived" predicates. #4211

> Note that when a filter expression contains a combination of filename/hive columns and actual columns, we currently can not fully remove these filters, for example see the two test cases at the end of test/sql/copy/parquet/parquet_hive.test.

**Comment by samansmink** [comment]
Hi @spren9er, I'm not sure whats happening here. Could you post the query plan? You can make duckdb print it by running:
```
EXPLAIN SELECT COUNT(*) AS total
FROM parquet_scan('./*/*/data.parquet', HIVE_PARTITIONING=1)
WHERE date='2022-08-08' AND country='Germany'
```

**Comment by spren9er** [comment]
```
logical_plan
   ┌───────────────────────────┐
   │         PROJECTION        │
   │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
   │           total           │
   └─────────────┬─────────────┘                             
   ┌─────────────┴─────────────┐
   │         AGGREGATE         │
   │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
   │        count_star()       │
   └─────────────┬─────────────┘                             
   ┌─────────────┴─────────────┐
   │           FILTER          │
   │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
   │    date = '2022-08-08'    │
   │  country = 'Germany'      │
   └─────────────┬─────────────┘                             
   ┌─────────────┴─────────────┐
   │        PARQUET_SCAN       │
   └───────────────────────────┘                             
 logical_opt
   ┌───────────────────────────┐
   │         PROJECTION        │
   │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
   │           total           │
   └─────────────┬─────────────┘                             
   ┌─────────────┴─────────────┐
   │         AGGREGATE         │
   │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
   │        count_star()       │
   └─────────────┬─────────────┘                             
   ┌─────────────┴─────────────┐
   │        PARQUET_SCAN       │
   └───────────────────────────┘                             
 physical_plan
   ┌───────────────────────────┐
   │    UNGROUPED_AGGREGATE    │
   │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
   │        count_star()       │
   └─────────────┬─────────────┘                             
   ┌─────────────┴─────────────┐
   │        PARQUET_SCAN       │
   └───────────────────────────┘
```

**Comment by spren9er** [comment]
Using DuckDB 0.5.1 above query takes now ~90ms.
Great improvement!
