### ISSUE TITLE
[Python] Use protocols to identify Pyarrow/Pandas container types.

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#4341]
When identifying a mutable python object (e.g., , lists, dicts, custom classes) we should use [protocols](https://mypy.readthedocs.io/en/stable/protocols.html) instead of ```py::instance``` to the direct class  or by getting the ```py_object_type = string(py::str(python_object.get_type().attr("__name__")));``` and performing a string comparison later on.

One example of that is when checking for 

- [ ] Arrow Container (i.e., #4242)
- [ ] Pandas Container
- [ ] Lists
- [ ] Dictionaries

The basic plan is to define a class that implements the functions we look for when interacting with said object
```python
from typing import Protocol, runtime_chekable
class ArrowObject(Protocol):
    def equals(self,obj):
        pass
    def field(self,i):
        pass
```
This is then included in our C++/Pybind API, and we check if an object matched our Protocol definition with ```py::isinstance```.

**Comment by Tishj** [comment]
_in_memory_dataset() just calls InMemoryDataset constructor, which we can call directly as well, but I'm not sure if it's a good idea to directly do this, in case the inner workings change ..

**Comment by Mause** [comment]
Lists and dictionaries are a lot less important than checking for arrow and pandas datatypes, I think

**Comment by Mause** [comment]
The protocol classes can just be defined in normal python and imported like `py::module::import("duckdb.protocols").attr("ArrowTableLike")`, though that will require some slight reorganisation of the package

**Comment by Tishj** [comment]
Still could not get much closer to successfully importing the protocols in pybind. Also thinking about what a Protocol really accomplishes is similar to what we do at the moment, just bundled into one call
Which we could also just create a function for in C++, which just checks that an instance has the attributes we're looking for?
Or are there more sophisticated checks that we can only accomplish with Protocol?

**Comment by Mause** [comment]
I mean, if we can't do protocols, a good start would be using the proper isinstance checks? Protocols can always be an additional layer on top of that

I'd be curious to see what the issues you're having address though
