### ISSUE TITLE
Feature request: Please populate additional information_schema tables related to referential constraints

### ISSUE THREAD

**Issue by prmoore77** [duckdb/duckdb#4343]
Please add Table constraint (Primary Key, Unique Key, NOT NULL) as well as Referential constraint (Foreign Key) metadata to the "information_schema" data dictionary.

I believe these tables would need to be populated (from https://www.postgresql.org/docs/current/information-schema.html):
"table_constraints": https://www.postgresql.org/docs/current/infoschema-table-constraints.html
"referential_constraints": https://www.postgresql.org/docs/current/infoschema-referential-constraints.html
"constraint_column_usage": https://www.postgresql.org/docs/current/infoschema-constraint-column-usage.html
"constraint_table_usage": https://www.postgresql.org/docs/current/infoschema-constraint-table-usage.html
"check_constraints": https://www.postgresql.org/docs/current/infoschema-check-constraints.html
... and possibly more...

Thank you!

**Comment by krlmlr** [comment]
Thanks. For now there's `duckdb_constraints()` that should have all the information you're looking for (with #4346).

**Comment by prmoore77** [comment]
> Thanks. For now there's `duckdb_constraints()` that should have all the information you're looking for (with #4346).

Thanks @krlmlr ! - my reason for requesting the additional information_schema dictionary tables is to allow tools which generate Entity Relationship Diagrams (ERD) - such as PyCharm to glean table relationships.  I was able to generate an ERD with table / column (data type) information from DuckDB, but PK/FK relationships didn't render.  After exporting the DDL SQL and running in PostgreSQL - the ERD generated with all relationships, etc. reflected in the diagram.

It would just be nice to have "one-stop-shopping" to generate ERD's without the overhead of PostgreSQL...

**Comment by dhirschfeld** [comment]
Ugh, a stale bot :(

I think this is a valid feature request. I've ended up here because my ERD in PyCharm is missing all the relationship information, which makes it useless.

**Comment by prmoore77** [comment]
@dhirschfeld - FWIW - I've added PK/FK metadata end-points to the [Flight SQL server example](https://github.com/voltrondata/flight-sql-server-example) (running DuckDB under the covers).  Using the Flight SQL JDBC driver with PyCharm does show PK/FK information...

**Comment by dhirschfeld** [comment]
> FWIW - I've added PK/FK metadata end-points to the [Flight SQL server example](https://github.com/voltrondata/flight-sql-server-example) (running DuckDB under the covers). Using the Flight SQL JDBC driver with PyCharm does show PK/FK information...

Thanks @prmoore77! That seems a round-a-bout way to get there, but whatever works! 😄

**Comment by dhirschfeld** [comment]
ACK

**Comment by Mytherin** [comment]
`table_constraints`,  `referential_constraints` and `key_column_usage` exist now - so this is at least partially implemented

**Comment by prmoore77** [comment]
Hi @Mytherin - I've opened a PR for this: https://github.com/duckdb/duckdb/pull/12942
