### ISSUE TITLE
nodejs duckdb data not persisting

### ISSUE THREAD

**Issue by cookiejest** [duckdb/duckdb#4349]
Hi,

I am trying to create a persistant database and then write some data to it from nodejs. However it does not seem to save the data state.

When i run the below code, and then try to connect to the database with duckdb cli, there is no data in the database. I must be missing something very simple please help!

```
      const mem_duckdb = new duckdb.Database('test1');
      mem_duckdb.all(`CREATE TABLE t3 AS SELECT 42 AS i, 84 AS j;`, (err, responseObject) => {
        if (err) {
          //handle/report error
          console.log(err);
        }
        console.log(responseObject);
      });
```

**Comment by Mause** [comment]
Are you closing the database afterwards?

**Comment by cookiejest** [comment]
no, i thought maybe its something to do with it being read only? I tried like this still doesnt seem to work:

    const mem_duckdb1 = new duckdb.Database(`test1`, duckdb.OPEN_READWRITE);

**Comment by cookiejest** [comment]
how do i close the connection in nodejs?

**Comment by Mause** [comment]
> how do i close the connection in nodejs?

```js
mem_duckdb.close();
```

**Comment by cookiejest** [comment]
hmm doesnt seem to have any impact. Not sure why is there any more examples somewhere?

**Comment by cookiejest** [comment]
As far as I can see this doesn’t work with nodejs right now to use a non in memory database

**Comment by Mause** [comment]
It does, I'm using it fine in this repo: https://github.com/Mause/duckdb_website_search/blob/main/src/build_index.ts

**Comment by hamilton** [comment]
hmm, I just tied out your code snippet as such:

```
import duckdb from "duckdb";
const mem_duckdb = new duckdb.Database('test1');
mem_duckdb.all(`CREATE TABLE t3 AS SELECT 42 AS i, 84 AS j;`, (err, responseObject) => {
  if (err) {
    //handle/report error
    console.log(err);
  }
  console.log(responseObject);
});
```

And it both persists the db and also runs. Using the `module` type here. Could you share more information about your code?

**Comment by cookiejest** [comment]
im using v16.14.0 on mac with duckdb version ^0.4.0

I can see a .wal file is being added that is roughly corresponding to the db size but the actual .db file i am specifying does not get any bigger and seems to stay empty.
![Screenshot 2022-08-13 at 00 23 05](https://user-images.githubusercontent.com/397270/184456380-67fabe86-3ed7-4395-b825-ee6a8c9bc125.png)

**Comment by Mytherin** [comment]
The WAL is how DuckDB stores small changes to the database. If you insert more data, shut down the database or run CHECKPOINT the WAL will be flushed to the database file.

**Comment by Alex-Monahan** [comment]
It looks like we don't have a doc on the checkpoint statement just yet. I'll add an issue in the web repo just to track it for a future todo list item (maybe for me!).

**Comment by cookiejest** [comment]
is there some example of how to force a checkpoint to save to disk? Im still not 100% sure why mine is not saving.

I cant see a use of a checkpoint statement in @Mause nodejs example above.

**Comment by Alex-Monahan** [comment]
Howdy!
Just execute this line of SQL:
```sql
checkpoint;
```

**Comment by cookiejest** [comment]
this raises another question - at what point does duckdb start to push data from RAM onto disk, does it just use up whatever is available or is there a way to set a RAM limit?

**Comment by cookiejest** [comment]
the reason i ask is i am potentially using multiple duckdb at same time on different processes. So I guess I would want to enforce a max RAM for duckdb, or I could do it in the node process itself.

**Comment by Alex-Monahan** [comment]
Typically with separate questions we would recommend either a new issue if you think it is a bug, or you can hop on our Discord to chat a bit!

You can set a memory limit for DuckDB. Today, it is not always respected since not every operation can be done outside of RAM. That is changing rapidly though! 

https://duckdb.org/docs/sql/pragmas

**Comment by Mytherin** [comment]
This issue can be closed now, correct?

**Comment by cookiejest** [comment]
im still having some trouble saving. i will test the checkpoint suggestion above and see if that works.
