### ISSUE TITLE
[Export] Generated columns aren't properly exported with `EXPORT DATABASE`

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#4356]
### What happens?

When exporting a database containing tables with generated column(s), attempting to reimport the database fails.

### To Reproduce

```sql
create table y(id1 int not null, id2 int generated always as (id1 / 2), id3 text);
insert into y values(10, 'abc');
export database 'test';
drop table y;
import database 'test';
```

### OS:

MacOS

### DuckDB Version:

4.0.1

### DuckDB Client:

CLI

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taofengliu** [comment]
I will try to fix this.
