### ISSUE TITLE
AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'autocommit'

### ISSUE THREAD

**Issue by Mageswaran1989** [duckdb/duckdb#4358]
### What happens?

With the latest version of **Sqlalchemy**, **duckdb** and [duckdb-engine](https://github.com/Mause/duckdb_engine/), following error is thrown while trying for ping test.

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in ping
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 867, in do_ping
    before_autocommit = dbapi_connection.autocommit
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1086, in __getattr__
    return getattr(self.dbapi_connection, key)
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/duckdb_engine/__init__.py", line 66, in __getattr__
    return getattr(self.c, name)
AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'autocommit'
```

Verion Details:

- **duckdb-0.4.0** 
- **duckdb-engine-0.3.3** 
- **sqlalchemy-1.4.40**

### To Reproduce

Pip:

```bash
conda create --name duckdb python=3.8
spurce activate duckdb
pip install duckdb-engine==0.3.3

...
Successfully installed duckdb-0.4.0 duckdb-engine-0.3.3 numpy-1.23.1 sqlalchemy-1.4.40
```

Python code:

```python
from contextlib import closing
from sqlalchemy.engine import Engine
import sqlalchemy as sa

def get_engine():
    return sa.create_engine("duckdb:///:memory:")

def ping(engine: Engine) -> bool:
    with closing(engine.raw_connection()) as conn:
        return engine.dialect.do_ping(conn)

ping(get_engine())
```

### OS:

MacOS Monterey

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Mageswaran

### Affiliation:

Symmetry Systems

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mageswaran1989** [comment]
Same code works by downgrading the **sqlalchemy** to **1.3.24**

```
pip install duckdb-engine==0.3.3  sqlalchemy==1.3.24
```

**Comment by Mause** [comment]
This is something that should be fixed in https://github.com/duckdb/duckdb/issues/4342 (cc @pdet) but for now, can you raise an issue in duckdb-engine and I can fix it there

**Comment by Mause** [comment]
Fixed in duckdb-engine
