### ISSUE TITLE
Question : how to retrieve map data in R (e.g. from histogram function)

### ISSUE THREAD

**Issue by HanOostdijk** [duckdb/duckdb#4367]
I would like to know how to handle map data.
For this particular case (the histogram function) I have seen in this repository a solution,
but I would like to know how to handle map data in general

In the code below I show how I use R to access DuckDB data.
I started with an R data.frame and made it available in DuckDB.

The first lines of code are to show that access to the df1 table works as expected.
After that I generate the histogram data and no error message appears.

However when I try to retrieve the data an error message appears:
**#> Error: rapi_prepare: Unknown column type for prepare: MAP(VARCHAR, UBIGINT)**

Because the histogram function is created, I expect that it can be used.
Please let me know if and how this can be done.

===R code===

suppressPackageStartupMessages(
  {
    library(DBI) ;library(duckdb)
  }
)
con <- dbConnect(duckdb())
dbGetInfo(con)$db.version
#> [1] "0.4.1-dev1289"
countries <- c("China", "Vietnam", "France", "England")
set.seed(2021)
df1R <- data.frame(country = sample(countries, 10, replace = T))
duckdb_register(con, "df1", df1R)
#duckdb view df1 now exists
mysql1 <-  "Select count(\"country\")  FROM df1"
cat(mysql1)
#> Select count("country")  FROM df1
dbGetQuery(con, mysql1)
#>   count(country)
#> 1             10
mysql2 <-   **"Create table h1 as Select histogram(\"country\")  as m1  FROM df1"**
dbExecute(con, mysql2)
#> [1] 1
#duckdb table h1 now exists
mysql2a <-   **"Select m1  FROM h1"**
dbGetQuery(con, mysql2a) 
**#> Error: rapi_prepare: Unknown column type for prepare: MAP(VARCHAR, UBIGINT)**
schemas <- DBI::dbGetQuery(con, "select * from sqlite_master")
print(schemas)
#>    type name tbl_name rootpage                                        sql
#> 1 table   h1       h1        0 CREATE TABLE h1(m1 MAP(VARCHAR, UBIGINT));
#> 2  view  df1      df1        0
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.utf8 
#> [2] LC_CTYPE=English_United States.utf8   
#> [3] LC_MONETARY=English_United States.utf8
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] duckdb_0.5.0 DBI_1.1.3   
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.29   withr_2.5.0     magrittr_2.0.3  reprex_2.0.1   
#>  [5] evaluate_0.15   highr_0.9       stringi_1.7.8   rlang_1.0.4    
#>  [9] cli_3.3.0       rstudioapi_0.13 fs_1.5.2        rmarkdown_2.14 
#> [13] tools_4.2.1     stringr_1.4.0   glue_1.6.2      xfun_0.31      
#> [17] yaml_2.3.5      fastmap_1.1.0   compiler_4.2.1  htmltools_0.5.3
#> [21] knitr_1.39
Created on 2022-08-12 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)

**Comment by hannes** [comment]
My guess is that the R client does not yet support the MAP type. @krlmlr maybe something for you?

**Comment by grantmcdermott** [comment]
Ran into this today. A two step workaround is: 1) use `MAP_ENTRIES` to convert the dictionary mapping created by `HISTOGRAM` into a list and 2) then `UNNEST`. This let's you pull in a regular 2D data frame object that R understands.

(As an aside, there may be a technical reason why unnesting of `MAP` types is not directly supported. but it would be nice if it was...) 

From your example:

```r
dbGetQuery(
    con,
    "
    SELECT UNNEST(MAP_ENTRIES(HISTOGRAM(country)), recursive := TRUE)
    FROM df1
    "
)
      key value
1 England     3
2  France     2
3 Vietnam     5
```

P.S. This approach also works for numeric columns, but requires some additional post-processing if you want bins. See https://github.com/duckdb/duckdb/issues/2268
