### ISSUE TITLE
Improve documentation for BLOB literals

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#4379]
### What happens?

#4378 was triggered by an ambiguity in https://duckdb.org/docs/sql/data_types/blob: it was unclear to me how to create a BLOB with two or three bytes from hex literals.

### To Reproduce

Review https://duckdb.org/docs/sql/data_types/blob, add one or two examples for creating longer BLOBs of length > 1 from hex literals.

Are the sources for the documentation available publicly?

### OS:

Web browser

### DuckDB Version:

ebe45abbb552d184dff9173c3412f63c173a0918

### DuckDB Client:

agnostic

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
They are available here: https://github.com/duckdb/duckdb-web/blob/master/docs/sql/data_types/blob.md
