### ISSUE TITLE
List licenses for third-party code

### ISSUE THREAD

**Issue by hannesmuehleisen** [duckdb/duckdb#438]
We should have a list somewhere that describes which license individuals components are under. Right now `sqlsmith` is the only GPL one afaik

**Comment by charlesmccarthyirl** [comment]
I had a bit of a look, and what I could find at least: (might be incorrect)

- catch
  - License: Boost Software License, Version 1.0
  - Link: https://github.com/cwida/duckdb/blob/master/third_party/catch/catch.hpp
- dbgen
  - License: Unknown
  - Link: Unknown
- dsdgen
  - License: Unknown
  - Link: Unknown
- hyperloglog
  - License: Custom? Though lists as BSD-3-Clause on github. 
  - Link: Seems to be taken from https://github.com/antirez/redis/blob/unstable/src/hyperloglog.c
- imdb 
  - (seems to download stuff only but seems to be duckdb code)
- libpg_query
  - License: Custom? Might be https://github.com/postgres/postgres/blob/master/COPYRIGHT but don't know.
  - Link: Unknown
- miniz 
  - License: MIT
  - Link:  https://github.com/richgel999/miniz
  - Usage: in gzip_stream.cpp
- re2
  - License: Custom
  - Link https://github.com/cwida/duckdb/blob/master/third_party/re2/LICENSE / https://github.com/google/re2/blob/master/LICENSE
- sqlite
  - License: Custom disclaims copyright / Public Domain
  - Link: https://www.sqlite.org/copyright.html
- sqlsmith:
  - License GPL-3.0
  - Link: https://github.com/anse1/sqlsmith
  - Usage: not used in normal build at all, but for query fuzzing

**Comment by hannesmuehleisen** [comment]
We extend the amalgamation with license files, and have added those files in the repo where they were missing
