### ISSUE TITLE
[JDBC] unsupported timestamp types: timestamp_ms, timestamp_ns, timestamp_s

### ISSUE THREAD

**Issue by jonathanswenson** [duckdb/duckdb#4389]
### What happens?

JDBC driver fails to deserialize timestamp in any non-microsecond form. 

the sql query: `select CAST(now() AS TIMESTAMP_MS)`

Fails with the error: 
```
No enum constant org.duckdb.DuckDBColumnType.TIMESTAMP_MS
java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.TIMESTAMP_MS
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:51)
	at org.duckdb.DuckDBResultSetMetaData.<init>(DuckDBResultSetMetaData.java:29)
	at org.duckdb.DuckDBNative.duckdb_jdbc_meta(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:97)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:174)
```

Similarly, it fails with `TIMESTAMP_S` and `TIMESTAMP_NS` as well.

Ran into this while trying to reproduce #4388 using the JDBC driver as well as the work to support arrow with jdbc (https://github.com/duckdb/duckdb/pull/4071#issuecomment-1179460128)

I have an implementation here that could be extracted and pulled into its own PR:
https://github.com/jonathanswenson/duckdb/commit/77ec47eb367755e3412aa5a3f2b3fb0b354d84f9#diff-66fcba33d6157d817b0cc8127a9a67e50cee82e51797d4463a580df4be00ca6fR492

### To Reproduce

```
Connection connection = getConnection(); // implement this somehow 
Statement statement = connection.createStatement();
String sql = "select CAST(now() AS TIMESTAMP_MS)";
ResultSet resultSet = statement.executeQuery(sql);
resultSet.next();
resultSet.getString(1);
```

```
select CAST(now() AS TIMESTAMP_MS)
select CAST(now() AS TIMESTAMP_NS)
select CAST(now() AS TIMESTAMP_S)
```

### OS:

OSX

### DuckDB Version:

0.4.0

### DuckDB Client:

JAVA

### Full Name:

Jonathan Swenson

### Affiliation:

Omni

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
@jonathanswenson it looks like you already have a pretty well tested implementation on your branch, feel free to extract it and create a pr? If you don't have the time, I'm happy to extract it and attribute the commits to you

**Comment by jonathanswenson** [comment]
@Mause I've extracted it here: https://github.com/duckdb/duckdb/pull/4404

May need to add support for getLocalDateTime as well, but this just extracts the work I had already done.
