### ISSUE TITLE
Fix Python dependency versions of libraries used in the CI

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#4396]
In the CI we have several dependencies that we are not fixing to a specific version and just installing with pip, e.g.:

```shell
pip install --prefer-binary "pandas>=1.2.4" "requests>=2.26" "pyarrow==8.0" "psutil>=5.9.0" pytest
```

Perhaps we could clean this up and organize it in a separate file (`requirements-ci.txt` or so, or just use `requirements-dev.txt`). That way we can avoid randomly breaking our CI when a downstream library breaks things in a new version. Particularly for libraries like pytest, psutil, etc we don't really care about testing with the latest version as we are just using them, rather than building anything around them.

@pdet @Mause thoughts?

**Comment by pdet** [comment]
Looking at the CIBW file (which I think is where we centralized the dependencies for testing, right?) I think we should probably: 

Always run with the latest:
* Pandas
* Pyarrow
* ibis-framekwork
* ibis-substrait

Fixate whatever is best: 
* Pytest
* psutil
* google-cloud-storage
* requests
* mypy

We can also remove it from the cibw, and unify a requirement for both CI and dev.
