### ISSUE TITLE
Missing dictionary for enum column when retrieving empty table as arrow

### ISSUE THREAD

**Issue by c-meier** [duckdb/duckdb#4397]
### What happens?

When retrieving an empty table with an enum column as an arrow table, the dictionary of the dictionary type is missing. However the dictionary is present as soon as there is at least one row in the table.

This is a problem for me because [`polars.from_arrow()`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_arrow.html?highlight=from_arrow#polars.from_arrow) requires having the dictionary array.

I created the issue here instead of at Polars because when I manually create an empty arrow table, it shows an empty dictionary array.

### To Reproduce

```python
import duckdb
import pyarrow as pa

if __name__ == "__main__":
    con = duckdb.connect()
    con.execute("""
        CREATE TYPE myEnum AS ENUM('first', 'second')        
    """)
    con.execute("""
        CREATE TABLE example(
            name varchar NOT NULL,
            e myEnum
        )        
    """)

    # Arrow table with dict when empty
    print("\nEmpty table\n==============")
    arrow_df = con.execute("""SELECT * FROM example""").arrow()
    print(arrow_df)

    # Arrow table with dict when at least one row
    print("\nOne row table\n==============")
    con.execute("""
        INSERT INTO example VALUES ('hello', 'first')       
    """)
    arrow_df = con.execute("""SELECT * FROM example""").arrow()
    print(arrow_df)

    # Manualy create arrow table with dict
    print("\nManual arrow\n==============")
    arrow_df = pa.table(
        {"name": [], "e": []}, 
        schema=pa.schema([
            ('name', pa.string()),
            ('e', pa.dictionary(pa.uint8(), pa.string()))
        ])
    )
    print(arrow_df)
```

Output:
```
Empty table
==============
pyarrow.Table
name: string
e: dictionary<values=string, indices=uint8, ordered=0>
----
name: []
e: []

One row table
==============
pyarrow.Table
name: string
e: dictionary<values=string, indices=uint8, ordered=0>
----
name: [["hello"]]
e: [  -- dictionary:
["first","second"]  -- indices:
[0]]

Manual arrow
==============
pyarrow.Table
name: string
e: dictionary<values=string, indices=uint8, ordered=0>
----
name: [[]]
e: [  -- dictionary:
[]  -- indices:
[]]
```

Using pyarrow 9.0.0

### OS:

Archlinux - 5.18.14-arch1-1

### DuckDB Version:

0.4.0 and 0.4.1.dev1570

### DuckDB Client:

Python

### Full Name:

Christopher Meier

### Affiliation:

HEIG-VD

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by c-meier** [comment]
Temporary work arround:
```python
for i, col in enumerate(arrow_df.schema):
    t = col.type
    if pa.types.is_dictionary(t):
        arrow_df = arrow_df.set_column(i, col, 
            pa.DictionaryArray.from_arrays(
                pa.array([], t.index_type), 
                pa.array([], t.value_type))
        )
```

**Comment by lidavidm** [comment]
FWIW, I think this would be a Polars issue. You can get PyArrow to generate the same table as DuckDB:

```python
>>> pa.Table.from_batches([], schema=arrow_df.schema)
pyarrow.Table
name: string
e: dictionary<values=string, indices=uint8, ordered=0>
----
name: []
e: []
```
What `pyarrow.table` is doing by default is generating a table with a single empty chunk, vs a table with no chunks (what DuckDB and `Table.from_batches` do). The dictionary is attached to the arrays (in the C Data/C Stream interface), so if there are 0 rows/chunks, there's no dictionary. (This is different from IPC, where schemas, dictionaries, and batches are transported separately.)

**Comment by pdet** [comment]
Closing this issue after @lidavidm comment.
