### ISSUE TITLE
Segmentation fault on UPDATE statement

### ISSUE THREAD

**Issue by poundifdef** [duckdb/duckdb#4401]
### What happens?

On a large table (1M+ rows), an UPDATE statement causes the duckdb CLI to segfault.

#### 1. Table Schema

```
CREATE TABLE t (
  id INTEGER,
  date DATE,
  amount DOUBLE,
  category VARCHAR,
  subcategory VARCHAR,
  sku VARCHAR,
  order_id VARCHAR,
  "order" VARCHAR,
  invoice VARCHAR
);
```

#### 2. Insert Data

In my case, I can consistently reproduce the error with 1M rows. I also see this error with fewer rows (in the 100k range) but the bug is not as reliable.

Thus, by using the attached CSV file, you may import data like so:

[segfault.csv.gz](https://github.com/duckdb/duckdb/files/9338823/segfault.csv.gz)

```
 COPY t from 'segfault.csv.gz' (AUTO_DETECT TRUE);
```

#### 3. UPDATE query

```
UPDATE t SET sku = 'x';
```

This will result in a `Segmentation fault`.

### OS:

Linux

### DuckDB Version:

v0.4.1-dev1556 540eab3cc

### DuckDB Client:

CLI

### Full Name:

Jay Goel

### Affiliation:

Journalize.io

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by poundifdef** [comment]
After more experiments, I think I have narrowed the scope of the bug and simplified the test case.

This bug seems to occur when a column has NULL values. Here is a simpler example to demonstrate the issue:

```
[ec2-user@ip-1.1.1.1 ~]$ ./duckdb bug.duckdb
v0.4.1-dev1556 540eab3cc
Enter ".help" for usage hints.
D create table t (id int, col varchar);
D insert into t (id) select range as id from range(0, 10000000);
D update t set col = 'x';
Segmentation fault
```

However, if you create a table with a default value for the strings, then I do not see this issue. The following create table does _not_ trigger this issue: `create table t (id int, col varchar default '');

**Comment by zippond** [comment]
Might be related with #4173 ?
