### ISSUE TITLE
DuckDB crash: uncaught `TransactionException: Cannot create index with outstanding updates`

### ISSUE THREAD

**Issue by aarashy** [duckdb/duckdb#4406]
### What happens?

Reopening the following issue because I found a consistent repro on the latest DuckDB version: https://github.com/duckdb/duckdb/issues/3666

I found a series of SQL statements which consistently causes DuckDB files to go into a corrupted state. Committing the transaction crashes the process. Any attempt to open a DB file after running these commands also crashes the process.

### To Reproduce

```
D create table test (id bigint primary key, c1 text);
D insert into test (id, c1) values (1, 'foo');
D insert into test (id, c1) values (2, 'bar');
D begin transaction;
D delete from test where id = 1;
D update test set c1='baz' where id=2;
D commit;
libc++abi: terminating with uncaught exception of type duckdb::TransactionException: TransactionContext Error: Cannot create index with outstanding updates
Abort trap: 6
logout
```

### OS:

iOS / docker

### DuckDB Version:

0.4.0

### DuckDB Client:

Rust + CLI

### Full Name:

Aarash Heydari

### Affiliation:

Dataland

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by aarashy** [comment]
The error is clearly coming from this line:
https://github.com/duckdb/duckdb/blob/master/src/storage/table/column_data.cpp#L96-L103 

But it's not obvious to me what upstream code path is calling it with `ALLOW_UPDATES = false` at the moment that the connection is opened.

**Comment by Mytherin** [comment]
It would be very helpful if you could try and make a small reproducible example using SQL queries. 

> What is unique about my data (specifically it seems like the the state of my DB + the staged edits in my WAL file) that is triggering this?

It seems to me like you are using DuckDB in a rather non-traditional manner - namely doing a lot of table modifications (updates, adding columns, dropping columns) with indexes present. While that should definitely work it is not a very common use case and hence not as well tested.

**Comment by aarashy** [comment]
Hi Mark, thanks for the response. I'll work on making a reproducible example with just SQL queries. For now, I sent my database files to your email (`mark.raasveldt@gmail.com` and `m.raasveldt@cwi.nl`). I wonder if you have debugger tools that could help us understand what's happening when we try to open the file.

**Comment by aarashy** [comment]
Ok good news @Mytherin ! The following small set of SQL queries reproduces the crash from a blank slate! 

```
D create table test (id bigint primary key, c1 text);
D insert into test (id, c1) values (1, 'foo');
D insert into test (id, c1) values (2, 'bar');
D begin transaction;
D delete from test where id = 1;
D update test set c1='baz' where id=2;
D commit;
libc++abi: terminating with uncaught exception of type duckdb::TransactionException: TransactionContext Error: Cannot create index with outstanding updates
Abort trap: 6
logout
```

**Comment by Mytherin** [comment]
Thanks, that's very helpful. I think I have figured it out and will push a fix shortly.

**Comment by aarashy** [comment]
It seems like as a workaround before I pick up this change in `v0.4.1`, I can avoid this bug by moving any DELETE statements in a transaction to the end of the transaction. Based on your understanding of the code, is that accurate?

**Comment by Mytherin** [comment]
That might circumvent the issue yes, the problem is that there are updates while the system is cleaning up entries from the indexes, which (incorrectly) causes this exception to be thrown. This only happens if you delete an entry from a table with an index, and have both a delete and an update in the same transaction, and the update occurs after the delete (as the clean-up happens in reverse order).
