### ISSUE TITLE
Python binary wheel for aarch64 (ARM64)

### ISSUE THREAD

**Issue by lesniewski** [duckdb/duckdb#4407]
I'm having trouble installing duckdb on a Chromebook because of the build's memory usage - the pip install build gets OOM killed.
Could you add `aarch64` (ARM64) to the list of architectures with binary wheels for linux?
Thanks for your consideration.

**Comment by Phil-T1** [comment]
Hi, I think I have the same issue. When I run pip install duckdb, it gets stuck perpetually building the wheels on a Raspberry Pi 4 B 8GB. It's a very minimal build in Docker with just the latest Python, numpy and DuckDB. On Windows 10 it installed immediately, so I think this is a lack of AARCH64 compatibility. Please could we get the install via pip?! I've had excellent results using this in Windows. Thanks!

**Comment by Mause** [comment]
From my comment on https://github.com/duckdb/duckdb/issues/4637

> Unfortunately it's somewhat difficult to compile these wheels without running the build on an aarch64 machine or fast enough vm. Emulating aarch64 on Github actions is simply far too slow (6+ hours), and it's difficult to cross compile wheels which comply with the manylinux wheel specifications
> Our best bets are probably
> * wait until GitHub actions provides aarch64 Linux runners
> * use another CI service for these jobs
> * figure out how to get the cross compilation working properly
> * or host our own aarch64 Linux runners

**Comment by zcfrank1st** [comment]
same question,  please release a arm64 version of python. There is something wrong to build.

**Comment by Mause** [comment]
> same question,  please release a arm64 version of python. There is something wrong to build.

Can you expand on what you mean by "there is something wrong to build"?

**Comment by zcfrank1st** [comment]
> > same question,  please release a arm64 version of python. There is something wrong to build.
> 
> Can you expand on what you mean by "there is something wrong to build"?

have no fast enough machine to build.  I own a pda which has a Helio P70 chip...

**Comment by zcfrank1st** [comment]
> > > same question,  please release a arm64 version of python. There is something wrong to build.
> > 
> > 
> > Can you expand on what you mean by "there is something wrong to build"?
> 
> have no fast enough machine to build. I own a pda which has a Helio P70 chip...

I use an arm64 docker container to build the wheels of python3.9 and python3.10. Maybe it is better to release official versions.

**Comment by rvanlaak** [comment]
Also looking forward to have an ARM Python wheel for this.

**Comment by frankier** [comment]
Looks like there are free ARM builders for open source on Cirrus CI and Circle CI. The former has the more generous free offering.

**Comment by frankier** [comment]
https://cibuildwheel.readthedocs.io/en/stable/setup/#cirrus-ci

**Comment by Mause** [comment]
@frankier that would require us to port our CI config to their format though, right?

**Comment by kapilt** [comment]
its possible to build aarch64 wheels in GitHub actions using qemu (cibuildwheel does a lot of the heavy lifting), but given the emulation and the amount of source, its likely going to take hours or days if it works. another option, if the project is willing to host an arm64 server is to integrate that it into GitHub actions via actuated (firecracker vms that spin up on your hardware via GitHub actions) https://docs.actuated.dev

**Comment by Gil-Frenkel** [comment]
Hi guys,

Pinging - Is there any wheel for Linux Arm64 yet?

Thanks!

**Comment by Mause** [comment]
This will probably be possible once Mac M1 build machines are available, and we don't need to build via emulation

See the note at the end of https://github.blog/2023-03-01-github-actions-introducing-faster-github-hosted-x64-macos-runners/#apple-silicon-is-on-the-way

**Comment by kapilt** [comment]
in terms of compute offerings, GitHub does have more powerful action runners in beta, but requires converting the org to a commercial one (team/enterprise level) aka pay per seat pricing to even sign up for the beta to pay additional for compute, afaict none of these offerings have aarch64 atm (no roadmap on linux, windows). also afaics the primary pain point being referenced here is against linux aarch64 wheels, not Mac, albeit same architecture might make a linux build in a container viable.

there are other options third party compute options that integrate natively with GitHub actions (aka one line change to extant workflow yawls) with simpler payment forms (no per seat costs),  one I came recently came across https://buildjet.com (hosted compute, pay per build time, supports linux arm64 natively), in addition to previously mentioned actuated.dev (provide your own compute). Noting both of these offerings are linux only.

**Comment by rvanlaak** [comment]
[CircleCI seems free for open-source](https://circleci.com/open-source/), also seems to have ARM support: https://circleci.com/docs/using-arm/

**Comment by frankier** [comment]
I think the problem is migrating the yaml definition for the workflows. Apparently the yamls are quite large. It's not impossible of course: https://circleci.com/docs/migrating-from-github/ but it might be quite a pain keeping things in sync.

**Comment by wearpants** [comment]
As a short term hack to using another build platform without converting all the YAML, maybe could use https://github.com/nektos/act (it's a local implementation of GHA)?
