### ISSUE TITLE
Hash function seems to have uneven distribution

### ISSUE THREAD

**Issue by prmoore77** [duckdb/duckdb#4417]
The new 0.4.1-dev1598 hash function seems to generate a lot of even/odd skew.  For example - when I attempt to break up the TPC-H "orders" table into 10 even buckets - I get a tremendous amount of skew for odd/even bucket numbers:

```
D select version();
┌────────────────┐
│   version()    │
├────────────────┤
│ v0.4.1-dev1598 │
└────────────────┘

D select mod (hash (o_custkey), 10) as bucket, count(*) from orders group by all order by bucket;
┌────────┬──────────────┐
│ bucket │ count_star() │
├────────┼──────────────┤
│ 0.0    │ 2991917      │
│ 1.0    │ 770          │
│ 2.0    │ 3002642      │
│ 3.0    │ 640          │
│ 4.0    │ 3008707      │
│ 5.0    │ 846          │
│ 6.0    │ 2990751      │
│ 7.0    │ 473          │
│ 8.0    │ 3002499      │
│ 9.0    │ 755          │
└────────┴──────────────┘
```

This may not be a bug, but a feature - if so - could you suggest a workaround to get even distribution?

Thank you!

**Comment by prmoore77** [comment]
Interestingly - using an odd number of buckets for the modulus generates even distribution:

```
D select hash (o_custkey) % 11 as bucket, count(*) from orders group by all order by bucket;
┌────────┬──────────────┐
│ bucket │ count_star() │
├────────┼──────────────┤
│ 0.0    │ 1360455      │
│ 1.0    │ 1365245      │
│ 2.0    │ 1360440      │
│ 3.0    │ 1363030      │
│ 4.0    │ 1363749      │
│ 5.0    │ 1358718      │
│ 6.0    │ 1361327      │
│ 7.0    │ 1370196      │
│ 8.0    │ 1369621      │
│ 9.0    │ 1364798      │
│ 10.0   │ 1362421      │
└────────┴──────────────┘
```

**Comment by Mytherin** [comment]
Thanks - that is very interesting. We should do some more experimenting with this.

**Comment by lnkuiper** [comment]
I thought this would be a problem that can lead to skew in hash tables and radix partitioning, but it seems like there's no problem here, because we do a bit-wise AND, rather than a modulo:
```sql
D select hash(i) & 7::UBIGINT as bucket, count(*) from test group by all order by bucket;
┌────────┬──────────────┐
│ bucket │ count_star() │
├────────┼──────────────┤
│ 0      │ 12490        │
│ 1      │ 12287        │
│ 2      │ 12434        │
│ 3      │ 12597        │
│ 4      │ 12501        │
│ 5      │ 12603        │
│ 6      │ 12529        │
│ 7      │ 12559        │
└────────┴──────────────┘
D select hash(i) & 15::UBIGINT as bucket, count(*) from test group by all order by bucket;
┌────────┬──────────────┐
│ bucket │ count_star() │
├────────┼──────────────┤
│ 0      │ 6238         │
│ 1      │ 6152         │
│ 2      │ 6269         │
│ 3      │ 6348         │
│ 4      │ 6231         │
│ 5      │ 6250         │
│ 6      │ 6314         │
│ 7      │ 6275         │
│ 8      │ 6252         │
│ 9      │ 6135         │
│ 10     │ 6165         │
│ 11     │ 6249         │
│ 12     │ 6270         │
│ 13     │ 6353         │
│ 14     │ 6215         │
│ 15     │ 6284         │
└────────┴──────────────┘
```

I've chosen to do 7 and 15 here because that's `00...00111` and `00...001111` respectively. In general we do bitwise AND with `2^n - 1`.

I've tried several fast non-cryptographic hash functions, and all of them have skew when doing modulo on an even number, and no skew when doing modulo with an uneven number.

All of them are fine when we do a bit-wise AND. Is there a reason why you'd like to create groups based on the modulo of a hash rather than a bit-wise AND?

**Comment by prmoore77** [comment]
hi @lnkuiper - I had never heard of a BITAND approach - thanks for sharing!  I had always used the "MOD" approach with other database engines (such as Snowflake and Oracle) - where I didn't seem to get skew.  I will try the approach you mention... thanks!

**Comment by prmoore77** [comment]
There is a good workaround - so I am closing...
