### ISSUE TITLE
select * from parquet file with fixedlenbytearray column raises Error: Out of buffer

### ISSUE THREAD

**Issue by bmmeijers** [duckdb/duckdb#4424]
### What happens?

Selecting from a parquet file with 44995 records, after 1 record the duckdb cli raises an error:
```
D select * from 'small_fixedlenbytearray.parquet';
┌────────────────────────────────────┬────────────────────┬───────────┬───────────────┬───────────────────┬────────────────┐
│              sfc_key               │      gps_time      │ intensity │ return_number │ number_of_returns │ classification │
├────────────────────────────────────┼────────────────────┼───────────┼───────────────┼───────────────────┼────────────────┤
│ !\xA0A\xB2jZ}\xEA\x80)\xA8\xC2\x00 │ 206027414.54690954 │ 321       │ 1             │ 1                 │ 2              │
└────────────────────────────────────┴────────────────────┴───────────┴───────────────┴───────────────────┴────────────────┘
Error: Out of buffer
```

### To Reproduce

See above

### OS:

Linux

### DuckDB Version:

v0.4.1-dev1547 f432dc646 (compiled in release mode)

### DuckDB Client:

CLI

### Full Name:

Martijn Meijers

### Affiliation:

TU Delft

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by bmmeijers** [comment]
A zip with the parquet file in-situ: [small_fixedlenbytearray.parquet.zip](https://github.com/duckdb/duckdb/files/9359352/small_fixedlenbytearray.parquet.zip)

**Comment by bmmeijers** [comment]
Ok, same data, but different encoding for some columns (no dictionary encoding for columns sfc_key and gps_time).
This shaves off some bytes, but unfortunately duckdb does also not like it when fixedlenbytearray column is inside the query:

```
D select * from '/scratch/small_fixedlenbytearray_nodict.parquet';
Error: Unsupported page encoding
D select sfc_key from '/scratch/small_fixedlenbytearray_nodict.parquet' limit 1;
Error: Unsupported page encoding
D select gps_time from '/scratch/small_fixedlenbytearray_nodict.parquet' limit 1;
┌────────────────────┐
│      gps_time      │
├────────────────────┤
│ 206027414.54690954 │
└────────────────────┘
```

[small_fixedlenbytearray_nodict.zip](https://github.com/duckdb/duckdb/files/9362955/small_fixedlenbytearray_nodict.zip)

**Comment by hannes** [comment]
Which tool do you use to create this file? DuckDB fails to read this because there is a dictionary page for `sfc_key` with uncompressed length 539.928 bytes supposedly containing 44.994 values. The schema states that the column indeed contained a `FIXED_LEN_BYTE_ARRAY` of value size 13. Now if we do the math the page should have 584.922 bytes run it but only has 539.928, a difference of exactly 44.994, which means it would be the correct length if the byte array had value size 12 and not 13. The parquet thrift schema (https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L357) says that (typo is in the file)

```
  /** If type is FIXED_LEN_BYTE_ARRAY, this is the byte length of the vales.
   * Otherwise, if specified, this is the maximum bit length to store any of the values.
   * (e.g. a low cardinality INT col could have this set to 3).  Note that this is
   * in the schema, and therefore fixed for the entire file.
   */
  2: optional i32 type_length;
```

So not a lot of leeway to interpret a 13 as a 12 here. Indeed pyarrow also fails to read that file.

**Comment by bmmeijers** [comment]
parquet-rs version 20.0.0 was used to write it. If I understand you correctly, there is not sufficient bytes for the values written?

**Comment by hannes** [comment]
Yes, I'm fairly sure its a bug in the parquet-rs writer setting the wrong value size or not writing enough data.
