### ISSUE TITLE
Too many process created on windows 

### ISSUE THREAD

**Issue by yjonckhe** [duckdb/duckdb#4425]
Hi guys,

executing twice the same query generates an exception : java.sql.SQLException: IO Error: Cannot open file "c:/yjo/jo7": The process cannot access the file because it is being used by another process.

Looks like a process is created at each query ? Please note : reusing the same connection gives the same exception.

Here is the jdbc java code on windows:

        try {
            Connection c = DriverManager.getConnection("jdbc:duckdb:c:/yjo/jo7");
            Statement stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("select doc_type, doc_state, redaction_place_code from data order by 1,2,3");
            rs.close();
            stmt.close();
            c.close();
        } catch(Exception ex) {
            ex.printStackTrace();
        }

A workaround is to use a read_only connection. Like so : 

Properties ro_prop = new Properties();
            ro_prop.setProperty("duckdb.read_only", "true");
            Connection c = DriverManager.getConnection("jdbc:duckdb:c:/yjo/jo7",ro_prop);

I also tried to use a connection pool but the problem occurs also unless all created connections are read-only.

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed by #4414, after that gets ported to the JDBC client.

**Comment by yjonckhe** [comment]
Thank you. Could someone explain me how to download windows build artefacts from the windows CI runs ?

**Comment by yjonckhe** [comment]
Is it fixed ?

**Comment by Mause** [comment]
This should be fixed by https://github.com/duckdb/duckdb/pull/5004

**Comment by omo** [comment]
(Unsolicited triage) @Mause Not hearing back any extra complaints. Maybe you can close this now.
