### ISSUE TITLE
Parquet reader converts timestamp to i64 *sometimes*

### ISSUE THREAD

**Issue by sigxcpu76** [duckdb/duckdb#4442]
### What happens?

I have a parquet file that is correctly read by both `pandas` and `polars`.
The `call_date` of that file is of type `datetime[ns,UTC]`.

Reading it with DuckDB converts the `call_date` field to an `int64` for no apparent reason.

### To Reproduce

`SELECT * FROM 'b.parquet'`

[b.parquet.zip](https://github.com/duckdb/duckdb/files/9378104/b.parquet.zip)

Reading with `pandas` and `polars` in Jupyter notebook (or any other Python env).

```python
import pandas as pd
import polars as pl
import duckdb

df_pandas = pd.read_parquet("b.parquet")
display(df_pandas)
df_polars = pl.read_parquet("b.parquet")
display(df_polars)

con = duckdb.connect()
df = con.execute("SELECT * FROM 'b.parquet'").df()
df
```

Also, reading the schema yields `INT64` for that column type.

```python
import duckdb

con = duckdb.connect()
df = con.execute("SELECT * FROM parquet_metadata('b.parquet')").df()
df[df['path_in_schema'] == 'call_date'][["path_in_schema", "type"]]
```

```
path_in_schema	type
4	call_date	INT64
```

Converting the initial `SELECT` to `arrow` also gives `int64`

```python
import duckdb

con = duckdb.connect()
df = con.execute("SELECT * FROM 'b.parquet'").arrow()
df
```

```
pyarrow.Table
linkback_length: int64
agent_call_sid: int64
client_sid: int64
agent_sid: int64
call_date: int64
call_type: string
call_sid: int64
skills: string
result: int64
call_wait_duration: int64
transfer_duration: int64
wrap_up_duration: int64
talk_duration: int64
hold_duration: int64
call_month_epoch: int64
call_date_epoch: int64
_version: int32
```

### OS:

Linux

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Alexandru Pirvulescu

### Affiliation:

TCN

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #4714.
