### ISSUE TITLE
Recursive CTE + UNION + RIGHT JOIN = SIGSEGV

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#4445]
### What happens?

This is a blocker for my external hash join PR #4189

External hash join schedules an additional child source pipeline, exactly like RIGHT JOIN. Now, `test/issues/fuzz/recursive_view_expression_assertion.test` is failing. I thought it was due to my changes at first, but it also fails on master (when I change the equality join to a RIGHT JOIN).

The crash is due to a null pointer in `Executor::ScheduleChildPipeline`. The `parent_entry` is a nullptr.

Just documenting this here, will try to fix the bug myself.

### To Reproduce

```sql
-- Create a view with UNION in a recursive CTE 
create view strings as (
    with recursive t(a) as (
        select 1 union select a+1 from t where a < 3
    ) select * from t order by a
);
-- Query with RIGHT JOIN
SELECT a, (SELECT a
           FROM strings i2
           RIGHT JOIN (SELECT SUM(a) sum_a
                       FROM strings i2
                       WHERE i2.a>i1.a) sq
           ON i2.a = sq.sum_a)
FROM strings i1
ORDER BY 1;
-- SIGSEGV
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

unittest

### Full Name:

Laurens Kuiper

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
I have pushed a fix for this in my #4189 PR, should be fixed when it gets merged.

**Comment by l1t1** [comment]
it runs on termux 0.118
```
Report issues at https://termux.org/issues

~ $ duckdb
v0.4.0 da9ee49
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create view strings as (
> with recursive t(a) as (
> select 1 union select a+1 from t where a < 3
> ) select * from t order by a
> );
D SELECT a, (SELECT a
> FROM strings i2
> RIGHT JOIN (SELECT SUM(a) sum_a
> FROM strings i2
> WHERE i2.a>i1.a) sq
> ON i2.a = sq.sum_a)
> FROM strings i1
> ORDER BY 1;
┌───┬────────────────────────────────────────────────────────────────────────────────────┐
│ a │ (SELECT a FROM strings AS i2 RIGHT JOIN (SELECT sum(a) AS sum_a FROM strings AS... │
├───┼────────────────────────────────────────────────────────────────────────────────────┤
│ 1 │                                                                                    │
│ 2 │ 3                                                                                  │
│ 3 │                                                                                    │
└───┴────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by lnkuiper** [comment]
@l1t1 You are using an older version of DuckDB where the bug did not exist yet. Try using DuckDB master, it will crash regardless of OS.

**Comment by Mytherin** [comment]
Looks like this is fixed
