### ISSUE TITLE
Inconsistent and erroneous IF/CASE behavior on date equality

### ISSUE THREAD

**Issue by tobymao** [duckdb/duckdb#4454]
### What happens?

When casting a string timestamp to a date and checking equality in an if, it evaluates to false when it should be true. What's strange is that if the if else values are literals, it works as expected but not when there's a column reference.

Happens on 0.4.0 and 0.4.1-dev1777

### To Reproduce
```python
import pandas as pd
import duckdb

df = pd.DataFrame([{"x": "2021-01-01 12:00:00", "y": 1}])

duckdb.connect().execute("""
select 
CAST(x as DATE) = '2021-01-01' a,
IF(CAST(x as DATE) = '2021-01-01', y, 0) b,
CASE WHEN CAST(x as DATE) = '2021-01-01' THEN y ELSE 0 END c,
IF(CAST(x as DATE) = '2021-01-01', 1, 0) d
from df
""").fetch_df()
```

result:
| a      | b | c | d |
| ------ | - | -  | - |
| True | 0 | 0 | 1 |

### OS:

linux

### DuckDB Version:

0.4.0

### DuckDB Client:

0.4.0

### Full Name:

Toby Mao

### Affiliation:

Airbnb

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
I just tried this on master in the test harness and it doesn't break:

```sql
statement ok
CREATE TABLE df (x VARCHAR, y INTEGER);

statement ok
INSERT INTO df VALUES ('2021-01-01 12:00:00', 1);

query IIII
select
	CAST(x as DATE) = '2021-01-01' a,
	IF(CAST(x as DATE) = '2021-01-01', y, 0) b,
	CASE WHEN CAST(x as DATE) = '2021-01-01' THEN y ELSE 0 END c,
	IF(CAST(x as DATE) = '2021-01-01', 1, 0) d
from df
----
True	1	1	1
```

So it looks like a Python binding issue?  Do I have the data types of `df` correct?

**Comment by Tishj** [comment]
@hawkfish it might be related to #4236 - where we changed the upgrading rules for numeric types

**Comment by hawkfish** [comment]
OK, who is happening is that the `BIGINT` triggers the `ConstantFoldingRule` for the constant arguments (to make the return types match), which (unlike the `ComparisonSimplificationRule`) signals that it changed the root node. This seems to cause all rule applications for previous arguments to be lost.

**Comment by hawkfish** [comment]
No, the problem is that we have labelled `VARCHAR` => `DATE` casts as reversible when they are not (as this example shows...), so we get into this strange situation where the casts ping-pong back and forth.  The fix is to add a check to see if the constant cast is _actually_ reversible and allow the cast simplification in one direction but not the other.

**Comment by Alex-Monahan** [comment]
Any insight into which DuckDB version first had the issue?
