### ISSUE TITLE
UUID column data could not be retrieved

### ISSUE THREAD

**Issue by IvaYan** [duckdb/duckdb#4457]
### What happens?

We are working on a C# bindings for DuckDB ([here](https://github.com/Giorgi/DuckDB.NET)). Trying to provide support for UUID columns we've faced a strange behaviour of UUID columns in DuckDB.

We have a value of UUID type (`SELECT uuid();`). DuckDB identifies the value as UUID. [The docs indicate](https://github.com/duckdb/duckdb/blob/c0a4ab96c626426961c207f49c19aa81448e91da/src/include/duckdb.h#L121) that UUID is actually a `duckdb_hugeint`, but when we try getting this value as a huge int (with a call to `duckdb_value_hugeint`), we get 0 (both for lower and higher parts). When we try getting the same value as a string, we get NULL. 

Conversion higeint->double and vice versa works fine. If we have a real hugeint (`SELECT 125::HUGEINT;`) it also works fine (we get a value with the lower part set to 125), so apparently the problem is in UUID handling.

We tried calling the API from a c++ code, to ensure the problem originates from DuckDB and not our bindings. 

At appears, that the problem is in DuckDB. How can we get a value of the UUID type?

### To Reproduce

```C++
#include "duckdb.hpp"

int main() {
    duckdb_database db;
    duckdb_connection con;

    assert(duckdb_open(nullptr, &db) == DuckDBSuccess);
    assert(duckdb_connect(db, &con) == DuckDBSuccess);

    duckdb_result result;

    // === query a higeint ===
    assert(duckdb_query(con, "SELECT 125::HUGEINT;", &result) == DuckDBSuccess);
    auto hugeint = duckdb_value_hugeint(&result, 0, 0);
    assert(hugeint.lower == 125);
    duckdb_destroy_result(&result);

    // === conversion ===

    hugeint = duckdb_double_to_hugeint(125);
    assert(hugeint.lower == 125);

    auto double_value = duckdb_hugeint_to_double(hugeint);
    assert(double_value == 125);

    // === query a uuid ===
    assert(duckdb_query(con, "SELECT uuid();", &result) == DuckDBSuccess);
    auto type = duckdb_column_type(&result, 0);
    assert(type == DUCKDB_TYPE::DUCKDB_TYPE_UUID);

    hugeint = duckdb_value_hugeint(&result, 0, 0); // <-- both fields are 0
    auto str = duckdb_value_varchar(&result, 0, 0); // <-- NULL

    return 0;
}
```

These two lines

```C++
hugeint = duckdb_value_hugeint(&result, 0, 0); // <-- both fields are 0
auto str = duckdb_value_varchar(&result, 0, 0); // <-- NULL
```

is where the magic happens. `hugeint` has both of its fields set to 0, and `str` is NULL.

### OS:

macOS 12.5.1

### DuckDB Version:

v0.4.0, da9ee490d

### DuckDB Client:

C++

### Full Name:

Ivan Drozdov

### Affiliation:

SMTU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by nodakai** [comment]
It appears several types are missing from the big `switch` in `GetInternalCValue`

**Comment by Mytherin** [comment]
For clients we are recommending a switch to the [C data_chunk API](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb.h#L521). This API operates directly on DuckDB’s internal format, and is therefore significantly faster when consuming data. The data chunk API also supports all types that DuckDB supports, including nested types (arrays and structs). The Julia client uses this to [support all DuckDB types at high speed](https://github.com/duckdb/duckdb/blob/master/tools/juliapkg/test/test_all_types.jl).

This issue should certainly be fixed but perhaps consider switching away from duckdb_value entirely.

**Comment by nodakai** [comment]
The data chunk API returns an array of hugeints with their MSB flipped https://github.com/duckdb/duckdb/blob/master/src/common/types/uuid.cpp#L52
That seems like a large footgun to me... Should there be a special wrapper or something that un-flips the MSB?

Another concern of mine is possible inconsistency in the MSB between text-to-UUID casting and `duckdb_append_hugeint()` or `duckdb_append_data_chunk()`. In general, I feel the need for a systematic effort to make UUID a true first-class citizen for DuckDB.

**Comment by Mytherin** [comment]
The bitflip is necessary because the value is stored as an int128, instead of a uint128. We might add a uint128 type in the future and UUID could be migrated to that, but I see no reason to have a dedicated UUID storage type. This will only add unnecessary bloat and complexity to the engine, as UUIDs can be perfectly modeled using numbers.

We could add a few helper functions to the C API similar to what we have in the C++ API, such as a function for converting UUIDs to strings. Beyond that I do not see sufficient reason to change the current setup.

**Comment by igitur** [comment]
Before I log another issue, is this discussion above also applicable to TIMESTAMP instead of UUID? Thansk
