### ISSUE TITLE
Process exits/crashes with no info or error for join query on windows (but not other OSes)

### ISSUE THREAD

**Issue by chrisbrain** [duckdb/duckdb#4466]
I am using:
```
npm: 7.10.0
node: 16.0.0
OS: Windows 10
duckdb npm package: 0.4.0
```

The process seems to exit/crash when I try to use a SQL join, _but only on Windows_. Same query works fine on Linux VM (tested via a Github Action) and Mac (tested by another developer).

Initially I was seeing this issue manifest as the following error and thought it might be related to Jest:

```
    Jest worker encountered 4 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:170
```

But then I found that when running the same query via an Express route the process just seems to exit without any additional information given.

The simplest repo example I can come up with is to run the following, e.g. with:
`node src/duck-err.js`

```src/duck-err.js 
// Place in src/duck-err.js
const duckdb = require('duckdb');
const db = new duckdb.Database(':memory:');

const SQL_CREATE_DB = `
create table person (
	id INT,
	first_name VARCHAR(50)
);
insert into person (id, first_name) values (1, 'Emalia');

create table car_model (
    id INT,
    car_model VARCHAR(50)
);

insert into car_model (id, car_model) values (1, 'Subaru');
`

db.exec(SQL_CREATE_DB,(err, res) => {

    if(err) {
        console.log(JSON.stringify(err));
        return;
    }

    // This works fine...
    // db.all(`select * from person`, (err, res) => {
    //
    // This works fine...
    // db.all(`select * from car_model`, (err, res) => {
    // 
    // But on Windows, this seems to just exit on the first line of the following duckdb.js function:
    // Connection.prototype.all = function(sql) {
    //      var statement = new Statement(this,sql);
    //      return statement.all.apply(statement, arguments);
    // }}
    db.all(`select person.id, car_model from person inner join car_model on person.id=car_model.id`, (err, res) => {

        if(err) {
            console.log(`Error performing join - ${JSON.stringify(err)}`);
            return;
        }
    
        console.log(`Query result -> ${JSON.stringify(res)}`);

        console.log(`finished`);
    });
   
})
```
As noted above, on Windows, this seems to just exit on the first line of the following duckdb.js code:

```
Connection.prototype.all = function(sql) {

        var statement = new Statement(this,sql);

        return statement.all.apply(statement, arguments);

 }}
```

When I run this on Linux I see the following (as expected) output:
```
Query result -> [{"id":1,"car_model":"Subaru"}]
```

I have also tested this in DBeaver on Windows and it runs fine.

**Comment by chrisbrain** [comment]
UPDATE: I also just tested this in the duckdb cli (duckdb_cli-windows-amd64) and it also works OK there. 

So this seems to be sometihng to do with the nodejs client on Windows.

**Comment by carlopi** [comment]
I just tried to reproduce this, Windows node.js client, and returns as expected.

Marking as closed, but please do run a check on your side and reopen if that's the case.
