### ISSUE TITLE
order by not work in distinct on()

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#4478]
### What happens?

CREATE temp table t(a int,b int,c int);
insert into t values(1,2,3),(1,3,2),(2,4,3),(2,4,1);
select * from t;
1	2	3
1	3	2
2	4	3
2	4	1
select distinct on (a) a,b,c 
from t order by a,b;
1	2	3
2	4	3
select distinct on (a) a,b,c 
from t order by a,b desc;
1	3	2
2	4	3
order by a,b desc or asc is different in postgre, but in duckdb all return :
1	2	3
2	4	3

### To Reproduce

same to up!

### OS:

win10

### DuckDB Version:

0.4.0

### DuckDB Client:

0.4.0

### Full Name:

wang.cz

### Affiliation:

linezone.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by wonb168** [comment]
but use first() like this is ok:
```
SELECT a,FIRST(b ORDER BY b DESC), FIRST(c ORDER BY b DESC)
FROM t
GROUP BY a
```

**Comment by lnkuiper** [comment]
What happens here is that the `distinct on` happens before the `order by`, and I don't think that `distinct on` is required to preserve insertion order, so I believe this is working as intended.

**Comment by wonb168** [comment]
> What happens here is that the `distinct on` happens before the `order by`, and I don't think that `distinct on` is required to preserve insertion order, so I believe this is working as intended.

but the same sql(order by asc and desc) in postgre got different result, why?
I think it's a bug in duckdb.

**Comment by lnkuiper** [comment]
I don't know how Postgres's `distinct on` works internally, but it could be that they use a sort-based distinct, giving more consistent results.

We use a hash-based approach, and have a different parallelism framework than postgres, both of which could explain the inconsistent results.

The `distinct on` is not required to preserve order. Also, while Postgres has an excellent SQL implementation, their behaviour does not define the SQL standard.

This is working as intended.
