### ISSUE TITLE
[Request] ODBC Drivers Compiled for OSX

### ISSUE THREAD

**Issue by niger-prequel** [duckdb/duckdb#4487]
Hey Team, we're using DuckDB in our product but would love stop using docker for our builds. We use ODBC for a host of reasons but the drivers released are only available for Ubuntu and Windows. Is there a way you could either release a version compiled for OSX or give us instructions so we could compile one ourselves?

**Comment by hannes** [comment]
What ODBC environment are you using? unixodbc?

**Comment by niger-prequel** [comment]
yes

**Comment by niger-prequel** [comment]
Not working for me yet because my M1 mac doesn't have an x86 openssl on it. Any thoughts?

**Comment by hannes** [comment]
See #4495

**Comment by hannes** [comment]
This is added now, the next release will publish a universal binary OSX ODBC driver, too. In the meantime you can try the CI artefacts, e.g. https://github.com/duckdb/duckdb/suites/7999422546/artifacts/343124769

**Comment by niger-prequel** [comment]
Thanks a ton this is working great for us! Also noticed you enabled Parquet on the universal CLI which is awesome because idk if it was before
