### ISSUE TITLE
DuckDB strips Pandas tzinfo

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#4490]
### What happens?

When querying a Pandas DataFrame with the Python client, DuckDB seems to be removing timezone/offset information.

To add a little more background since it may be relevant to the underlying cause, [via the Pandas docs](https://pandas.pydata.org/docs/reference/arrays.html#datetime-data):

> NumPy cannot natively represent timezone-aware datetimes. pandas supports this with the [arrays.DatetimeArray](https://pandas.pydata.org/docs/reference/api/pandas.arrays.DatetimeArray.html#pandas.arrays.DatetimeArray) extension array, which can hold timezone-naive or timezone-aware values.

DuckDB will convert timezone-aware datetime columns into timezone-naive ones, even when the query should not transform the column (e.g. "select *")

### To Reproduce

We will need some Python code to reproduce. First we construct a Pandas DataFrame with one naive and one aware timestamp column:

```python
import pandas as pd
from datetime import date, time, datetime, timezone, timedelta

tz = timezone(timedelta(hours=-7))
today_midnight = datetime.combine(date.today(), time.min)

ts_df = pd.DataFrame({
    "naive": [pd.Timestamp(today_midnight)],
    "aware": [pd.Timestamp(today_midnight, tzinfo=tz)]
})
```

If you run `print(ts_df.dtypes)` you will get

```
naive               datetime64[ns]
aware    datetime64[ns, UTC-07:00]
dtype: object
```

As you can see the "aware" column stores a column-level tz offset (assuming that all values in the column are in the same tz, otherwise you get back an "object" column).

Doing a "select *" over this in DuckDB:

```python
import duckdb

conn = duckdb.connect(database= ":memory", read_only=False)
conn.register("ts_df", ts_df)

conn.execute("select * from ts_df")
duck_df = conn.df()
print(duck_df.dtypes)
```

```
naive    datetime64[ns]
aware    datetime64[ns]
dtype: object
```

If you look at the contents of `duck_df` it hasn't completely ignored the tz offset. The aware column contains the value `2022-08-24 07:00:00` i.e. the date+time it was in UTC at the input instant, but the output column is tz-naive. Ideally it would preserve the column as `datetime64[ns, UTC-07:00]` though even `datetime64[ns, UTC]` (still converted to UTC, but tz-aware) would be preferable.

I think DuckDB is treating these tz-aware columns at `timestamp`s rather than `timestamp with time zone`s. As evidence we can try converting the results first to arrow then to Pandas similar to in an issue I filed last week (#4428). If we change the `conn.df()` call to `conn.arrow().to_pandas()` we initially won't see any difference which is what makes me think it's treating the input column as `timestamp`, because if we then cast the column to `timestamptz` we do get a different result:

```python
conn.execute("select cast(aware as timestamptz) as aware from ts_df")
duck_tz_df = conn.arrow().to_pandas()
print(duck_tz_df.dtypes)
```

```
aware    datetime64[ns, UTC]
dtype: object
```

This only works if you do the arrow -> pandas conversion, going directly to pandas still yields `datetime64[ns]`. And the tz you get on the output here is determined by DuckDB's `TimeZone` setting.

### OS:

macOS, Linux

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hi, thanks for raising this issue!

This has actually already been fixed in the master build in https://github.com/duckdb/duckdb/pull/4284, albeit by shifting the timezone to UTC (and hencing losing the timezone, but the time itself is still correct)

Can you please verify with the latest build with `pip install duckdb --pre -U`?

**Comment by dylanscott** [comment]
Thanks @Mause! I can confirm I get back a `datetime64[ns, UTC]` for the aware column on the latest build 👍
