### ISSUE TITLE
RuntimeError by read_csv_auto for specific value

### ISSUE THREAD

**Issue by nickmishustin** [duckdb/duckdb#4503]
### What happens?

I try process the csv file. It has only one column now for example.

```
test
8cb123cb8
34fd321
fg5391jn4
```
I used simple query for selectig all row/columns:
```
improt duckdb
con = duckdb.connect()
query = "SELECT *  FROM read_csv_auto('test.csv')"
con.execute(query)
```
Then got a error:  
```
RuntimeError: basic_string::replace: __pos (which is 18446744073709496293) > this->size() (which is 9)
```

After some tries I undestand that script failed when trying process `8cb123cb8` value. It'is ok when I remove it.

### To Reproduce

1. Save csv file  as test.csv
2.  Run
````
improt duckdb
con = duckdb.connect()
query = "SELECT *  FROM read_csv_auto('test.csv')"
con.execute(query)
````

### OS:

Linux, Ubuntu 22.04, 5.15.0-46-generic

### DuckDB Version:

0.4.0

### DuckDB Client:

0.4.0

### Full Name:

Nick Mishustin

### Affiliation:

personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Sorry, I can't reproduce this with your example.

**Comment by Tishj** [comment]
I also can't reproduce this
Are you sure you didn't accidentally insert an invisible symbol in there accidentally? Those do exist sadly

**Comment by nickmishustin** [comment]
@Tishj @hannes 
Hello, thanks for yorr answers. 
I reproduce it on [google colab ](https://colab.research.google.com/drive/1LjSJTHjHbT5Wvr9ckYV-RraHSkO_iUSV?usp=sharing)
I attach my file here. It has only visible symbols.
[test.csv](https://github.com/duckdb/duckdb/files/9434048/test.csv)

**Comment by hannes** [comment]
Looks like a Linux/gcc-specific issue, we were able to reproduce there, too

**Comment by Tishj** [comment]
```c++
   456          for (auto pos = std::find(format_specifier.begin(), format_specifier.end(), '-'); pos != format_specifier.end();
-> 457               pos = std::find(pos + separator.size(), format_specifier.end(), '-')) {
   458                  format_specifier.replace(pos, pos + 1, separator);
   459          }
   ```
   crash happens here
