### ISSUE TITLE
Invalid float-point literal handling in statements like 'SELECT -0.5;'

### ISSUE THREAD

**Issue by IvaYan** [duckdb/duckdb#4506]
### What happens?

Hi!

I've spotted something that seems to be a HUGE bug in number handling. 

### To Reproduce

Try the following code:

```c++
duckdb_database db;
duckdb_connection con;

assert(duckdb_open(nullptr, &db) == DuckDBSuccess);
assert(duckdb_connect(db, &con) == DuckDBSuccess);

duckdb_result result;
assert(duckdb_query(con, "SELECT -0.5;", &result) == DuckDBSuccess);

auto type = duckdb_column_type(&result, 0);
auto ff = duckdb_value_double(&result, 0, 0); // 1.8446744073709552E+19
auto str = duckdb_value_varchar(&result, 0, 0); // "18446744073709551611"
```

If we execute a simple query `SELECT -0.5;` the value is treated as a DECIMAL. If I try getting this value as a double, I get a very strange value of 1.8446744073709552E+19. If I try getting this value as a VARCHAR, I get "18446744073709551611". 

If I try to explicitly specify the value type (i.e. `SELECT -0.5::DOUBLE;`), I get the correct value for all of the calls. If I try `SELECT 0.5;` query, I get just `5` for a double and `"5"` for a VARCHAR.

### OS:

macOS

### DuckDB Version:

v0.4.0, da9ee49

### DuckDB Client:

C++

### Full Name:

Ivan Drozdov

### Affiliation:

SMTU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think the issue here is this:
```c++
	case DUCKDB_TYPE_DECIMAL:
		return TryCastCInternal<hugeint_t, RESULT_TYPE, OP>(result, col, row);
```
DECIMAL can have different underlying physical types, here it is always assumed to be `hugeint_t`

**Comment by Tishj** [comment]
Attempting to change it to:
```c++
	case DUCKDB_TYPE_DECIMAL: {
		D_ASSERT(result && result->internal_data);
		auto result_data = (duckdb::DuckDBResultData*)result->internal_data;
		D_ASSERT(result_data->result);
		auto& query_result = *result_data->result;
		switch (query_result.types[col].InternalType()) {
			case duckdb::PhysicalType::INT16:
				return TryCastCInternal<int16_t, RESULT_TYPE, OP>(result, col, row);
			case duckdb::PhysicalType::INT32:
				return TryCastCInternal<int32_t, RESULT_TYPE, OP>(result, col, row);
			case duckdb::PhysicalType::INT64:
				return TryCastCInternal<int64_t, RESULT_TYPE, OP>(result, col, row);
			case duckdb::PhysicalType::INT128:
				return TryCastCInternal<hugeint_t, RESULT_TYPE, OP>(result, col, row);
			default:
				throw duckdb::NotImplementedException("Internal type not implemented for Decimal");
		}
	}
```
But now it's triggering `D_ASSERT(allocation_count == 0);` in the Allocator :thinking:

**Comment by lokax** [comment]
@Tishj It seems that TryCast::Operation doesn't handle scale like TryCastFromDecimal/StringCastFromDecimal does, which results in 
```cpp
query("SELECT 0.5::DECIMAL(18, 1)");
duckdb_value_double(...) // get value 5
```

**Comment by Tishj** [comment]
> @Tishj It seems that TryCast::Operation doesn't handle scale like TryCastFromDecimal/StringCastFromDecimal does, which results in
> 
> ```c++
> query("SELECT 0.5::DECIMAL(18, 1)");
> duckdb_value_double(...) // get value 5
> ```

Yes I'm currently working on a fix ;)

**Comment by Tishj** [comment]
Eureka!
```
(lldb) p str
(char *) $0 = 0x0000000104f1bff0 "-0.5"
(lldb) p ff
(double) $1 = -0.5
```
still hitting the Allocator assertion though, so I'm not sure what's happening
