### ISSUE TITLE
Improve NodeJS JSDoc's

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#4518]
Right now there are a bunch of TODO's in the NodeJS docs - can you fill these out before 0.5.0 @hannes ?

https://github.com/duckdb/duckdb/blob/76a8cbc383646ee4cbf5fa981fbbd7b4de6b218c/tools/nodejs/lib/duckdb.js#L317-L351

**Comment by hannes** [comment]
I will try to remember :)

**Comment by hannes** [comment]
I've added a bunch of comments
