### ISSUE TITLE
globbing multiple parquet files fails on httpfs filesystem [R]

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#4530]
### What happens?

The [documented syntax](https://duckdb.org/docs/data/parquet) for working with multiple parquet files seems only to work with local files.  I can use the httpfs extension to successfully access a single parquet file (:tada: :tada: ), but not multiple files, let alone hive-partitioned files.  (Note this works just fine if we use arrow backend, e.g. with S3 resources, since arrow doesn't support generic https), this issues is just referring to the duckdb native approach.

### To Reproduce

This works:

```r
library(DBI)
library(duckdb)
conn <- DBI::dbConnect(duckdb(),
                       ":memory:",
                       config=list("memory_limit"="12GB",
                                   "temp_directory" = "/tmp"))
DBI::dbExecute(conn, "INSTALL 'httpfs';")
DBI::dbExecute(conn, "LOAD 'httpfs';")

query <- glue::glue("SELECT * FROM parquet_scan('",
                    "https://data.ecoforecast.org/neon4cast-scores/parquet/",
                    "aquatics/2022/aquatics-2022-08-29-persistenceRW.parquet",
                    "') LIMIT 10")
df <- DBI::dbGetQuery(conn, query)
df
```

Amazing!!  But ideally I'd like to get the full (hive-partitioned) dataset.  The documentation I've been able to find is a bit thin here, but from #4211 it seemed something like this might work, but no luck:

```r
query <- glue::glue("SELECT * FROM parquet_scan('",
                    "https://data.ecoforecast.org/neon4cast-scores/parquet/",
                    "*/*/*.parquet'", ", HIVE_PARTITIONING=1",
                    ") LIMIT 10")
df <- DBI::dbGetQuery(conn, query)
df
```

In fact, I can't even stack two parquet files together with the usual syntax:

```r
query <- glue::glue("SELECT * FROM parquet_scan('[",
                    "https://data.ecoforecast.org/neon4cast-scores/parquet/",
                    "aquatics/2022/aquatics-2022-08-29-persistenceRW.parquet",
                    ", ",
                    "https://data.ecoforecast.org/neon4cast-scores/parquet/",
                    "aquatics/2022/aquatics-2022-08-28-persistenceRW.parquet",
                    "]') LIMIT 10")
df <- DBI::dbGetQuery(conn, query)
df
```

### OS:

Linux (ubuntu 20.04)

### DuckDB Version:

github version

### DuckDB Client:

R

### Full Name:

Carl Boettiger

### Affiliation:

UC Berkeley

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
There is no (standard, reliable) way to list files on a HTTP server, hence we cannot glob there

**Comment by Mause** [comment]
> There is no (standard, reliable) way to list files on a HTTP server, hence we cannot glob there

Shouldn't we still support accepting a list of urls?

**Comment by hannes** [comment]
Probably

**Comment by cboettig** [comment]
Thanks for clarifying!  Yes, supporting a list of URLs would still be great. 

In this case, this is also a public S3 bucket.  I think duckdb has support for s3:// based URLs(?) (which would provide the mechanism to list contents), but I'm struggling to find documentation of the appropriate syntax (especially for alternative hosts -- e.g. this is a MINIO server, so we would need an `endpoint_override` / `AWS_DEFAULT_ENDPOINT` option.)

**Comment by hannes** [comment]
@samansmink can comment on this once he's back from vacation

**Comment by Mause** [comment]
> Thanks for clarifying! Yes, supporting a list of URLs would still be great.
> 
> In this case, this is also a public S3 bucket. I think duckdb has support for s3:// based URLs(?) (which would provide the mechanism to list contents), but I'm struggling to find documentation of the appropriate syntax (especially for alternative hosts -- e.g. this is a MINIO server, so we would need an `endpoint_override` / `AWS_DEFAULT_ENDPOINT` option.)

We do support alternative hosts! The configuration parameters are documented in the [config docs](https://duckdb.org/docs/sql/configuration#configuration-reference), but the following is basic usage example from one of our tests:

```sql
SET s3_secret_access_key='minio_duckdb_user_password';
SET s3_access_key_id='minio_duckdb_user';
SET s3_region='eu-west-1';
SET s3_endpoint='duckdb-minio.com:9000';
SET s3_use_ssl=false;

COPY lineitem TO 's3://test-bucket/multipart/export_large.parquet' (FORMAT 'parquet');
```

**Comment by cboettig** [comment]
Thanks @Mause ! this is so so cool. looking forward to testing this out.  (cool example, looks like you can also write to remote parquet! Can `EXPORT database` also take an S3 URL as a target??)

I'll play around with this, but pointers to any further documentation or examples with S3-hosted data would be awesome too.  In particular, I'm curious if it's possible to point duckdb at a collection of (potentially hive-partitioned) parquet files on S3 and execute tasks like filtering queries selecting a subset of rows and columns in a way that avoids having to first transfer over the network or import (onto local disk) the entirety of a parquet file?  Can duckdb perform that kind of remote range request operation?

**Comment by cboettig** [comment]
@Mause minor comment here, the config settings you link don't seem to contain a variable for allowing anonymous access (e.g. to public buckets).  That's a standard option in most AWS interfaces, would it be possible to support it in duckdb too?

**Comment by Mause** [comment]
> Thanks @Mause ! this is so so cool. looking forward to testing this out.  (cool example, looks like you can also write to remote parquet! Can `EXPORT database` also take an S3 URL as a target??)
I don't know this one off the hand, but definitely worth trying 


> I'll play around with this, but pointers to any further documentation or examples with S3-hosted data would be awesome too.  In particular, I'm curious if it's possible to point duckdb at a collection of (potentially hive-partitioned) parquet files on S3 and execute tasks like filtering queries selecting a subset of rows and columns in a way that avoids having to first transfer over the network or import (onto local disk) the entirety of a parquet file?  Can duckdb perform that kind of remote range request operation?
I think our docs on this are a bit lacking as yet unfortunately - I believe any filesystem interactions can also be s3 interactions.

Yep, DuckDB uses Range requests when it interacts with remote files

**Comment by Mause** [comment]
> @Mause minor comment here, the config settings you link don't seem to contain a variable for allowing anonymous access (e.g. to public buckets).  That's a standard option in most AWS interfaces, would it be possible to support it in duckdb too?  

Hmm, that's a very good point. I'll have a poke at the implementation to see if it supports simply not setting the creds

**Comment by hannes** [comment]
Yes you can COPY to s3, too

**Comment by samansmink** [comment]
@cboettig I thought public access without an access key did work? We test for this in `test/sql/copy/s3/download_config.test`:

```
# Test public access through s3 url
statement ok
SET s3_secret_access_key='';SET s3_access_key_id='';

query I
SELECT i FROM "s3://test-bucket-public/root-dir/test_${url_style}_url_style.parquet" LIMIT 3
----
0
1
2
```

Did you try this out?

**Comment by Mause** [comment]
> @cboettig I thought public access without an access key did work? We test for this in `test/sql/copy/s3/download_config.test`:
> 
> ```
> # Test public access through s3 url
> statement ok
> SET s3_secret_access_key='';SET s3_access_key_id='';
> 
> query I
> SELECT i FROM "s3://test-bucket-public/root-dir/test_${url_style}_url_style.parquet" LIMIT 3
> ----
> 0
> 1
> 2
> ```
> 
> Did you try this out?

Hmm, blank strings are a bit counterintuitive - given how many questions we get about s3 we should probably just document it properly

**Comment by samansmink** [comment]
@Mause The default value for these is a blank string, so I would expect public bucket access to work by only setting the `s3_region` and `s3_endpoint` which I thought was pretty intuitive. I completely agree with the remark on the documentation of httpfs. I'll look into improving the httpfs docs soon and will make sure to add this!

**Comment by cboettig** [comment]
thanks, good call!  Yes, I confirm this works well on a public S3 bucket with globbing (https://gist.github.com/cboettig/b1840f20996139d422ab497613dfdbde).  :tada: wonderful.  (Though I'm also still super happy about the pure HTTP access -- it would be great if that could be extended to the list format... should I open a separate issue for that?)

(As an aside I've noticed that duckdb is stricter about schema matching across parquet blobs than arrow is on the same data -- looks like arrow will permit some parquet files to be missing a given column and will treat those rows as NA, but duckdb will throw an error)

**Comment by hannes** [comment]
The issue with the missing columns is that either you first have to read *all* metadata to figure out the union of all columns to create the overall schema *or* the schema suddenly depends on whichever file you read first.

**Comment by samansmink** [comment]
@cboettig about the list format, this should already work, or am i misunderstanding?
```
select * from parquet_scan(['https://domain.com/file1.parquet', 'https://domain.com/file2.parquet']);
```

**Comment by cboettig** [comment]
@samansmink , that's the syntax I tried (see 3rd code block in my reprex up top), but it throws an error for me (using the GitHub master branch and the R syntax).  Here's my reprex again:

```{r}
library(DBI)
library(duckdb)
conn <- DBI::dbConnect(duckdb(),
                       ":memory:",
                       config=list("memory_limit"="12GB",
                                   "temp_directory" = "/tmp"))
DBI::dbExecute(conn, "INSTALL 'httpfs';")
#> [1] 0
DBI::dbExecute(conn, "LOAD 'httpfs';")
#> [1] 0

query <- glue::glue("SELECT * FROM parquet_scan('[",
                    "https://data.ecoforecast.org/neon4cast-scores/parquet/",
                    "aquatics/2022/aquatics-2022-08-29-persistenceRW.parquet",
                    ", ",
                    "https://data.ecoforecast.org/neon4cast-scores/parquet/",
                    "aquatics/2022/aquatics-2022-08-28-persistenceRW.parquet",
                    "]') LIMIT 10")
df <- DBI::dbGetQuery(conn, query)
#> Error: rapi_prepare: Failed to prepare query SELECT * FROM parquet_scan('[https://data.ecoforecast.org/neon4cast-scores/parquet/aquatics/2022/aquatics-2022-08-29-persistenceRW.parquet, https://data.ecoforecast.org/neon4cast-scores/parquet/aquatics/2022/aquatics-2022-08-28-persistenceRW.parquet]') LIMIT 10
#> Error: IO Error: Cannot open file "[https:/data.ecoforecast.org/neon4cast-scores/parquet/aquatics/2022/aquatics-2022-08-29-persistenceRW.parquet, https:/data.ecoforecast.org/neon4cast-scores/parquet/aquatics/2022/aquatics-2022-08-28-persistenceRW.parquet]": No such file or directory
df

```

**Comment by samansmink** [comment]
@cboettig haha yes was just typing this 😁
