### ISSUE TITLE
SET memory_limit command is not working as expected

### ISSUE THREAD

**Issue by kamaljit-1991** [duckdb/duckdb#4535]
### What happens?

For our usecase we are trying out duckdb. We have the requirement to run a few queries on parquet files and write the result to a new parquet files. These queries are simple sql queries. We have memory constraint. So I want to limit it and also we need performance too. We use java as our language.
Before using the connection object I set the below parameters: 
```
Connection conn = DriverManager.getConnection("jdbc:duckdb:");
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("SET memory_limit='6GB'");
            stmt.execute("SET threads TO 10");
        }
        return conn;
```
This connection we are using a single thread. But this memory limit doesn't work. We saw it **consuming almost 30 GB RAM** for some of the instances. There are millions of rows which we are trying to process. But I expect it to may be work slowly but it shouldn't cross the max_memory_allowed.

Is it because SET command doesn't work and I have to use PRAGMA command ?
Or is it because of the number of threads set to 10 and duckdb assumes that memory as 10 * 6 = 60 GB ? It should't be.

### To Reproduce

I could provide the set of files I am using. Those are some test data. But basically I was trying to merge 2 sets of parquet files using queries. 1 set contains around 77 number of 500 MB files and another set contains may be 10 number of 500 MB files or lesser. 

### OS:

linux

### DuckDB Version:

duckdb_jdbc:0.4.0

### DuckDB Client:

Jdbc

### Full Name:

Kamaljit Pati

### Affiliation:

Fivetran data pipelining company

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Try setting a temporary storage directory, make sure you use the latest version. We have made some changes recently.

**Comment by kamaljit-1991** [comment]
Thanks for fast reply @hannes . We are using 0.4.0 version of duckdb which is available here https://mvnrepository.com/artifact/org.duckdb/duckdb_jdbc. This is the latest one I feel. 

Will set the temp_directory and see if it helps. I will update here after that.

**Comment by hannes** [comment]
This is not the latest version, this is the latest published JDBC binary.

**Comment by kamaljit-1991** [comment]
How can I use the latest version of duckdb @hannes ?

**Comment by Mause** [comment]
> How can I use the latest version of duckdb jdbc @hannes ?

There are links to the builds here https://duckdb.org/docs/installation/

**Comment by kamaljit-1991** [comment]
@Mause / @hannes we are using the latest stable version available on maven. But it feels like you indicate to build your master code and use that. Is that correct ? I don't think that's a good idea because any change you do it will impact our production. 

Also I wanted to inform you that setting of temp_directory also didn't work. Means after setting it to proper temp directory and memory_limit to 6 GB and thread count to 10, still duckdb is using around 30 GB RAM. Now I am trying to make the thread count to 1 and see if it works. Could you please let me know if this limit really works and if it does then what do I have to do here ?

**Comment by kamaljit-1991** [comment]
@Mause / @hannes even making the threads to 1 didn't work. Still it consumed > 20 GB RAM. Could you tell me if this issue you are also facing and if yes is this going to be fixed and when ?

**Comment by Alex-Monahan** [comment]
We understand not deploying a development version to production, but could you please do some tests with our latest build as described above? This issue may already be fixed with some of the work done after 0.4.0 was released. Our next release is planned for September 5th, so you don't have too long to wait!

**Comment by kamaljit-1991** [comment]
@Alex-Monahan that's very good news. Sure. Today I planned to test with your latest build. I will update you guys about the result. Thanks.

**Comment by kamaljit-1991** [comment]
Hey @Alex-Monahan / @Mause / @hannes I tried to create the jar out of master branch. But the make commands are not generating the duckdb_jdbc jar. I generated the makefiles using `cmake` command and then I ran `BUILD_JDBC=1 make` command to generate the jar following this [link](https://github.com/duckdb/duckdb/blob/master/CONTRIBUTING.md) . Still the jar is not getting generated. Could you please help me out here?

**Comment by Mause** [comment]
@kamaljit-1991 we've actually released 0.5.0 since you created this issue, so can you try with that version instead?

**Comment by kamaljit-1991** [comment]
@Mause / @Alex-Monahan I tested the 0.5.0 version and again 0.4.0. Before I was actually measuring the buffer memory used by os too(which is included in container memory) along with process memory which gave wrong memory consumption. Then I tested again and again in linux container and every time 0.4.0 version's memory consumption is way better than 0.5.0. I mean 0.4.0 consumes less memory than 0.5.0 for the same dataset. So we decided to use 0.4.0 version for now. **But could you check from your end too and verify our findings ?** 

I will share the git branch with you on Monday where we reproduced this issue.

**Comment by Mytherin** [comment]
It's hard to verify why this is happening without knowing your exact workload, but this might be related to the issues we found in [glibc's standard allocator](https://github.com/duckdb/duckdb/issues/3969#issuecomment-1177424908). Are you running on Linux?

We are planning to include jemalloc with the next release. It is also possible to force DuckDB to use jemalloc using e.g. [LD_PRELOAD](https://github.com/jemalloc/jemalloc/wiki/Getting-Started) which might be useful as a temporary work-around.

**Comment by kamaljit-1991** [comment]
Yes @Mytherin we run on linux actually Ubuntu 18.04 LTS to be exact. 

So could you tell me when you are going to fix this and when the fixed version would come ? Actually when we tested on 0.4.0 the memory consumption was not increasing that much but with while continuously executing the duckdb queries we saw slight increase(may be some memory leak) but that seems to be fine for now. 

This is the link https://github.com/ravisharda/duckdb-jdbc-merge-performance which contains the code which we tested. But this doesn't contain the parquet files which we tested on because those files are of 500 MB and github doesn't allow it. But you can see the queries and understand. Please check out this method https://github.com/ravisharda/duckdb-jdbc-merge-performance/blob/a8fef869fb7618112400695f7270af37993ec2c3/src/main/java/org/example/duckdb/RecordsProcessor.java#L103 which actually we run. But if you want the files that also possible if you have any s3 bucket or anything where I could upload.

**Comment by kamaljit-1991** [comment]
Hey @Mytherin / @Alex-Monahan / @Mause I found 1 more thing and wanted to verify with you. When I was using a single connection and run all the queries(In the query I was just writing the result of reading from multiple parquet files to a new one) there was almost no memory leak. But when I tested something like : 
1. create a new connection
2. run a few queries 
3. close the connection
4. Open a new connection
5. and same cycle continues ...

Like this I did for at least 10 connections and the memory consumption was steadily increasing. It's like doing **connection.close()** is not releasing all the memory. I also verified that using just a single connection for all the queries is not creating this memory leak. Also the more memory 1 duckdb connection uses the memory leak is also more.

**Also as per duckdb docs :** 
The connection to duckdb database should be disconnected and it should be closed too [link](https://duckdb.org/docs/api/c/api#duckdb_close). But when I see the code for jdbc when we close the connection : 
https://github.com/duckdb/duckdb/blob/a0fc1e9cd0c9b03020b4ed9c7ba61fcd67d54681/tools/jdbc/src/main/java/org/duckdb/DuckDBConnection.java#L98
It just disconnects but it doesn't do [duckdb_close](https://duckdb.org/docs/api/c/api#duckdb_close). So May be that's the reason. But I am clearly able to see there is memory leak while doing multiple open and close of duckdb connection.

Could you please check this out and let us know.

**Comment by kamaljit-1991** [comment]
I again tested with setting LD_PRELOAD env variable. With this I don't see any memory leak with connection closing and opening a new one. I think this is the one which I was missing. I am still testing. I will update if I see any irregularities here.

**Comment by kamaljit-1991** [comment]
Hey team I again tested by setting LD_PRELOAD and it actually works. There is no doubt about it. So in [this comment](https://github.com/duckdb/duckdb/issues/4535#issuecomment-1248981596) it's written that it's a temporary workaround. Could you tell me whats your plan ? I mean what could be the permanent fix for this ?

**Comment by Mytherin** [comment]
@lnkuiper is working on integrating `jemalloc` into an extension and distributing that by default with (at least) all Linux builds.

**Comment by kamaljit-1991** [comment]
@Mytherin could you give us some timeline ? We can plan our work accordingly. 
Also if it's a simple change we could also do the same and build the jar for our usecase until your release comes. That would also work for us. Last time I checked I couldn't build the jdbc jar properly from your code base. If you could just forward me to the docs it would be helpful.

**Comment by Mause** [comment]
> @Mytherin could you give us some timeline ? We can plan our work accordingly. Also if it's a simple change we could also do the same and build the jar for our usecase until your release comes. That would also work for us. Last time I checked I couldn't build the jdbc jar properly from your code base. If you could just forward me to the docs it would be helpful. really appreciate your continuous replies. Thanks.

If you join our Discord, we can probably help you with any compilation issues you're having? https://discord.com/invite/tcvwpjfnZx

**Comment by Mause** [comment]
@kamaljit-1991 are you able to test it works as expected with the 0.6.0 release?
