### ISSUE TITLE
ImportError: /usr/local/lib/python3.8/site-packages/duckdb.cpython-38-x86_64-linux-gnu.so: cannot map zero-fill pages

### ISSUE THREAD

**Issue by abdobim** [duckdb/duckdb#4536]
### What happens?

The celery worker crushes randomly when importing the duckdb library.

The error returned is : 
`ImportError: /usr/local/lib/python3.8/site-packages/duckdb.cpython-38-x86_64-linux-gnu.so: cannot map zero-fill pages`

The error does not reoccur all the time, it is random, and once celery worker crush, we find in the logs that it is because of the import of the duckdb library!

duckdb==0.4.0
pandas==1.2.2
celery==4.3
python==3.8.12

### To Reproduce

The error is triggered at import time, so no reproduction steps to provide.

### OS:

Linux

### DuckDB Version:

0.4.0

### DuckDB Client:

python 3.8.12

### Full Name:

ABDEL

### Affiliation:

Axi

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you still make a reproducible example please? My guess would be some incompatibility with celery indeed.

**Comment by abdobim** [comment]
Doing more research on the internet, I noticed that other python libraries have the same problem / bug (cannot map zero-fill pages), and they were talking about memory saturation as the origin of these worries. 

I think that the memory problem could be the origin of this error for our environment too since the environment machine does not have enough memory resources.

The monitoring tools of our environment show a peak in memory usage on the machine when the bug was triggered, which confirms that it was indeed the memory problem that caused the bug.

![image](https://user-images.githubusercontent.com/6716002/187647894-050795ec-628e-406d-b5a7-ef70ad20495c.png)

To reproduce the bug, I think you have to try to import the library when the memory of the machine is full.

The solution we have chosen to solve this problem is to monitor the import of duckdb with a `try/except ImportError`

**Comment by hannes** [comment]
Well if there is not enough memory to load the library in the first place you're in trouble already.
