### ISSUE TITLE
Code Reformat (Again)

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#454]
### Adopt Facebook clang-tidy and [clang-format]( https://github.com/facebook/facebook-clang-plugins/blob/master/.clang-format)

This seems to be relatively sane and industry-standard. We should also enforce these conventions in one of the travis builds to make sure we don't violate them again later on.

### Expression Rename

* Rename BoundExpressions to regular Expressions (e.g. BoundComparisonExpression -> ComparisonExpression)
* Prefix the current parsed expressions with Parsed (e.g. current ComparisonExpression -> ParsedComparisonExpression)

The reason for this change is that the bound expressions are used throughout a much larger part of the codebase, and constantly prefixing them with Bound is annoying/very verbose.

### Rename PhysicalOperators
* Rename PhysicalOperator to Operator (e.g. PhysicalHashJoin -> HashJoin)

The reason for this is that logical operators are already prefixed by Logical, physical operators don't need to be, and this prefix leads to very long names (PhysicalNestedLoopJoin, PhysicalNestedLoopJoinState).

### Other
* Rename VectorBuffer to VectorData

**Comment by hannesmuehleisen** [comment]
The file structure is also something that could potentially be standardised, see for example https://github.com/facebook/folly/tree/master/folly/compression, where headers are named `.h` and are placed next to the implementation files.

**Comment by hannesmuehleisen** [comment]
We have both clang-tidy and format now
