### ISSUE TITLE
DISTINCT is not implemented for window functions

### ISSUE THREAD

**Issue by drorspei** [duckdb/duckdb#4545]
### What happens?

Count distinct over windows is not currently supported. For example:

```
select count(distinct a) over(partition by b) from c
```
Prints the error "DISTINCT is not implemented for window functions." 

The lack of support starts in the parser and is inherited from the pg code.

If I wanted to work on this, where would I start?
Do you think this is a reasonable thing to try to implement? (given your knowledge and preferences, as well as the fact that postgres never did (and as far as I can tell neither did presto, Spark or mssql)) 

### To Reproduce

select count(distinct a) over(partition by b) from c

### OS:

Linux

### DuckDB Version:

0.4.1.dev2358

### DuckDB Client:

Python

### Full Name:

Dror Speiser

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Thanks for the report!  This is a [big can of worms](https://dl.acm.org/doi/pdf/10.1145/3514221.3526184) that is on my radar for later this year. I wouldn't recommend wading in because the architecture will changing underneath you for out of core operations, but hey, its open source!

**Comment by hawkfish** [comment]
A lot of the necessary refactoring has been done, so we are getting closer.

**Comment by hawkfish** [comment]
I think I have a working merge sort tree now (which was less work than I feared) so progress continues to be made.
