### ISSUE TITLE
[Fuzzer] Correlated offset subquery

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4563]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
SELECT (SELECT 1 OFFSET c0) FROM (VALUES(1)) c0;
```

Actual:
src/execution/column_binding_resolver.cpp:74: virtual unique_ptrduckdb::Expression duckdb::ColumnBindingResolver::VisitReplace(duckdb::BoundColumnRefExpression &, unique_ptrduckdb::Expression *): Assertion `expr.depth == 0' failed.

Expected:
The query should output NULL.

**Comment by PedroTadim** [comment]
The same assertion happened today on the LIMIT clause:
```
SELECT 0 FROM (SELECT 8 c0) WHERE (SELECT 1 LIMIT c0);
```
