### ISSUE TITLE
[Fuzzer] C-API IN query row index out chunk size

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4564]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("SELECT(SELECT DATE '3764356-1-1' IN(1)) HAVING 0;");
```

Actual:
src/common/types/column_data_collection.cpp:98: duckdb::Value duckdb::ColumnDataRow::GetValue(duckdb::idx_t) const: Assertion `row_index < chunk.size()' failed.

Expected:
I would expect an unimplemented type for cast error.

**Comment by Tishj** [comment]
```
[0/1] (0%): C-API IN query row index out chunk size
Query failed with message: Invalid Error: Unoptimized statement differs from original result!
Original Result:
(SELECT (CAST('3764356-1-1' AS DATE) IN (1)))
BOOLEAN
[ Rows: 0]

Unoptimized:
Conversion Error: Unimplemented type for cast (INTEGER -> DATE)
```

**Comment by PedroTadim** [comment]
This issue maybe was been fixed by another one. We can close it.
