### ISSUE TITLE
[Fuzzer] Statistics propagation mistmatch

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4565]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
PRAGMA enable_verification;
SELECT CAST("sum"(1) AS BIGINT) FROM (SELECT CAST((SELECT EXISTS(SELECT 1)) AS BIGINT));
```

Actual:
Error: INTERNAL Error: Statistics mismatch: value is smaller than min.
Statistics: [Min: 42, Max: 42][Has Null: false, Has No Null: true][Approx Unique: 1]
Vector: CONSTANT BIGINT: 1 = [ 1]

Expected:
?

**Comment by PedroTadim** [comment]
This one has been fixed, we can close it.
