### ISSUE TITLE
[Fuzzer] IS DISTINCT FROM validation

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4566]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("SELECT (0 IS DISTINCT FROM 2) = 0;");
con.SendQuery("SELECT CASE 8 WHEN(0 IS DISTINCT FROM 0) THEN 2 END;");
```

Actual:
src/main/client_context.cpp:931: std::string duckdb::ClientContext::VerifyQuery(duckdb::ClientContextLock &, const std::string &, unique_ptrduckdb::SQLStatement): Assertion `orig_expr_list[i]->Equals(verify_statements[v_idx].select_list[i].get())' failed

Expected:
Another validation issue. A single false and NULL value is expected.

**Comment by PedroTadim** [comment]
This is now fixed.
