### ISSUE TITLE
[Fuzzer] UndefinedBehaviorSanitizer on downcast from correlated subquery

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4568]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
CREATE TABLE t0(c0 INT);
SELECT count(*) OVER() = ANY(SELECT * FROM t0 t1 WHERE(c0 = t0.c0)) FROM t0;
```

Actual:
src/optimizer/deliminator.cpp:38:19: runtime error: downcast of address 0x608000009120 which does not point to an object of type 'duckdb::BoundColumnRefExpression'
0x608000009120: note: object is of type 'duckdb::BoundCastExpression'
00 00 00 00 50 d0 ea 09 20 56 00 00 0c 1b be be be be be be 40 91 00 00 80 60 00 00 00 00 00 00
^~~~~~~~~~~~~~~~~~~~~~~
vptr for 'duckdb::BoundCastExpression'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/optimizer/deliminator.cpp:38:19 in

Expected:
An empty result set is expected.

**Comment by PedroTadim** [comment]
I am still able to reproduce this issue

**Comment by PedroTadim** [comment]
You need to compile with the undefined behavior sanitizer

**Comment by Mytherin** [comment]
Somehow this does not seem to trigger on Linux, but I can confirm it indeed does trigger on MacOS. Will have another look at it.
