### ISSUE TITLE
[Fuzzer] Assertion error on correlated cube

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4569]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152
```
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES(NULL);
SELECT (SELECT count(*) OVER() GROUP BY CUBE(c0)) FROM t0;
```

Actual:
duckdb: src/execution/expression_executor.cpp:146: void duckdb::ExpressionExecutor::Execute(const duckdb::Expression &, duckdb::ExpressionState *, const duckdb::SelectionVector *, duckdb::idx_t, duckdb::Vector &): Assertion `FlatVector::Validity(result).CheckAllValid(count)' failed.

Expected:
Because the cube returns more than one row, here the result may not be deterministic.

**Comment by PedroTadim** [comment]
This one has been fixed, we can close it.
