### ISSUE TITLE
[Fuzzer] Order by ALL with UNION query

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4572]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
(SELECT 2 ORDER BY(SELECT 2)) UNION SELECT 1 ORDER BY ALL;
```

Actual:
src/planner/binder/query_node/bind_select_node.cpp:241: void duckdb::Binder::BindModifierTypes(duckdb::BoundQueryNode &, const vectorduckdb::LogicalType &, duckdb::idx_t): Assertion `bound_colref.binding.column_index < sql_types.size()' failed

Expected:
The query should output the rows with values 1 and 2.

**Comment by lokax** [comment]
This issue appears to have been fixed by #4390.
I have added that test case on new pr

**Comment by Maxxen** [comment]
Cool, thanks for the heads up!
