### ISSUE TITLE
[Fuzzer] OFFSET query taking too long

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4576]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
CREATE TABLE t0 (c0 INT, c1 INT);
INSERT INTO t0 (VALUES (1, 1),(2, 2),(3, 3));
SELECT c0 FROM t0 OFFSET 42949672960;
```

Actual:
The SELECT query runs for a very long time. I would expect it to end very shortly.

Expected:
While running this on the shell and sending the interrupt signal to it, I get:
src/common/allocator.cpp:144: duckdb::AllocatorDebugInfo::~AllocatorDebugInfo(): Assertion `allocation_count == 0' failed

Thijs comments:

> This is not related to the query at all.
> The assertion is triggered because the database is abruptly interrupted, while allocations were still made, if that allocation is not deallocated before the destructor of the Allocator is called, this assertion is triggered.

**Comment by Mytherin** [comment]
Looks like this is already fixed as well
