### ISSUE TITLE
[Fuzzer] Lag window function issue

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4577]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
SELECT lag(1) OVER (ORDER BY 0 RANGE BETWEEN CURRENT ROW AND 1 FOLLOWING);
```

Actual:
src/include/duckdb/common/types/vector.hpp:298: static bool duckdb::FlatVector::IsNull(const duckdb::Vector &, duckdb::idx_t): Assertion `vector.GetVectorType() == VectorType::FLAT_VECTOR' failed

Expected:
A single NULL value is expected.

**Comment by PedroTadim** [comment]
This is now fixed, shall it be closed?
