### ISSUE TITLE
[Fuzzer] Database collation not reloaded?

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4578]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

On a persisted database create this table:
`CREATE TABLE t0 (c0 VARCHAR(0) COLLATE AF);`
Then after the restart, will give the error:
```
Error: unable to open database "<name>": Catalog Error: Collation with name af does not exist!
```

> I think I have the ICU extension enabled somehow. That's because AF shows on the collations list at PRAGMA collations;.

**Comment by Tishj** [comment]
I have attempted to push a fix for this in #4497 but as mentioned there, this requires a broader change to properly address the issue
