### ISSUE TITLE
[Fuzzer] Capi error assertion

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4579]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("SELECT 2 UNION(SELECT 2) ORDER BY 1;");
```

Actual:
src/main/query_result.cpp:23: void duckdb::BaseQueryResult::ThrowError(const std::string &) const: Assertion `HasError()' failed.

Expected:
The query should output a single 2.

**Comment by Tishj** [comment]
```
[0/1] (0%): Capi error assertion                                                
2
INTEGER
[ Rows: 1]
2
```
This is fixed on 0.5.0 master
