### ISSUE TITLE
[Fuzzer] Analyze rowid column

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4582]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
CREATE TABLE t0(c0 INT);
ANALYZE t0(rowid);
```

Actual:
src/storage/data_table.cpp:1319: void duckdb::DataTable::SetStatistics(duckdb::column_t, const std::function<void (BaseStatistics &)> &): Assertion `column_id != COLUMN_IDENTIFIER_ROW_ID' failed

Expected:
A proper error should be thrown.

**Comment by PedroTadim** [comment]
This is now fixed. Should we close it?

**Comment by Maxxen** [comment]
Good catch!
