### ISSUE TITLE
[Fuzzer] C-API invalid query

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb#4583]
Originally discovered in https://github.com/duckdb/duckdb/issues/4152

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("INSERT INTO t0(VALUES(0 = (OVER = 2)));");
```

Actual:
Terminates the process while throwing the error.

Expected:
A proper error should be thrown.

**Comment by Tishj** [comment]
```
[0/1] (0%): C-API Invalid query                                                 Query failed with message: Catalog Error: Table with name t0 does not exist!
```
This doesn't crash, the error is explicit, `t0` doesn't exist

**Comment by Tishj** [comment]
@PedroTadim is this example missing steps? I've also ran this after creating a t0 table, those results are more interesting
```
[0/1] (0%): C-API Invalid query                                                 Query failed with message: Binder Error: Referenced column "over" not found in FROM clause!
LINE 1: INSERT INTO t0 (VALUES ((0) = (("over") = (2))))
```

**Comment by PedroTadim** [comment]
Maybe it was fixed recently. If you can no longer reproduce it, close it for now and I will reopen it if I reproduce it again

**Comment by PedroTadim** [comment]
I just reproduced it with this. Can you test it?

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("INSERT INTO t0(VALUES('\\x15\\x00\\x00\\x00\\x00@\\x01\\x0A\\x27:!\\x0A\\x00\\x00x12e\"\\x00'::BLOB));");
```
