### ISSUE TITLE
array_sort will change the origin ARRAY value

### ISSUE THREAD

**Issue by digoal** [duckdb/duckdb#4591]
### What happens?

array_sort will change the origin ARRAY value:

It's may not be good for common use case.

### To Reproduce

```
D select k,v,map(k,v), map(k,v)[(array_sort(k,'DESC'))[1]] from (values ([1,2,3,4],[2,3,4,5])) as t(k,v);
┌──────────────┬──────────────┬──────────────────────┬─────────────────────────────────────┐
│      k       │      v       │      map(k, v)       │ map(k, v)[array_sort(k, 'DESC')[1]] │
├──────────────┼──────────────┼──────────────────────┼─────────────────────────────────────┤
│ [4, 3, 2, 1] │ [2, 3, 4, 5] │ {4=2, 3=3, 2=4, 1=5} │ [2]                                 │
└──────────────┴──────────────┴──────────────────────┴─────────────────────────────────────┘


D select k, array_sort(k,'DESC') from (values ([1,2,3,4])) as t(k);
┌──────────────┬───────────────────────┐
│      k       │ array_sort(k, 'DESC') │
├──────────────┼───────────────────────┤
│ [4, 3, 2, 1] │ [4, 3, 2, 1]          │
└──────────────┴───────────────────────┘
```

### OS:

MacOS

### DuckDB Version:

4.0.1-dev commit: 0d2d7930d2789405a0d07a15e37485fe70faee3e

### DuckDB Client:

CLI

### Full Name:

Digoal Zhou

### Affiliation:

Alibaba

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Maybe @taniabogatsch can have a look?
