### ISSUE TITLE
ERR_DLOPEN_FAILED when adding require('duckdb') in nodejs worker for Linux/Mac (Windows OK)

### ISSUE THREAD

**Issue by chrisbrain** [duckdb/duckdb#4596]
This was initially showing up - I believe - as a 'Segmentation fault' but now I have boiled down the following very simple example:

server.js
```
const express = require("express");
const { Worker } = require('worker_threads');

const app = express();

let respCount = 0;

app.get("/", async function (req, res) {

    const worker = new Worker('./worker.js', { workerData: 'test' });

    worker.on('message', msg => {
        respCount++;
        res.send(respCount + ": " + msg);
    });
    worker.on('error', err => {
        res.send(err);
    });
    worker.on('exit', (code) => {
        if(code !== 0) {
            console.log(new Error(`Worker stopped with exit code ${code}`));
        }
    })

});

console.log('listening on localhost:3000/')
app.listen(3000);
```

worker.js
```
const { parentPort, workerData } = require('worker_threads');
const duckdb = require('duckdb'); // The presence of this line alone causes the issue

parentPort.postMessage("Received - " + workerData);
```

The first request to http://localhost:3000/ works but subsequent ones error with **ERR_DLOPEN_FAILED**  and the following:

`'Error: Module did not self-register: '/mnt/d/repos/DuckDBTest2/node_modules/duckdb/lib/binding/duckdb.node'.\n    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Module.require (node:internal/modules/cjs/loader:1028:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/mnt/d/repos/DuckDBTest2/node_modules/duckdb/lib/duckdb-binding.js:4:15)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)'`

Just adding the line `const duckdb = require('duckdb');` causes this issue even without using duckdb.

I am running on Windows 10 but using WSL so the code is running on Ubuntu 20.04 Linux, nodejs v16.17.0. I have tried duckdb 0.4.0 and I believe the latest master (0.4.1-dev2403.0).

**Comment by chrisbrain** [comment]
To add to this, I have discovered I **do not** get this running in nodejs on Windows, only in Linux.

**Comment by hannes** [comment]
Does this also happen when you don't load `express` or `worker_threads`?

**Comment by chrisbrain** [comment]
@hannes Yes I am seeing the same when I remove express from server.js (and just run the worker a couple of times directly) and remove the worker_threads require from worker.js.

**Comment by hannes** [comment]
Does it also happen when you run the native windows binary and not through WSL?

**Comment by chrisbrain** [comment]
@hannes I have been using the windows CLI a lot if that answers the question?

But just to clarify, this problem only seems to appear on Linux (and Mac actually, as a fellow dev has confirmed this morning). It seems OK to use DuckDB in nodejs worker threads on Windows.

**Comment by ntapsrigowri** [comment]
Hi, I'm running in to similar issues on mac
node : v18.11.0
npm : 8.19.2.

```
 Error: Module did not self-register: '/node_modules/duckdb/lib/binding/duckdb.node'.

  › Object.<anonymous> (node_modules/duckdb/lib/duckdb-binding.js:4:15)
  › Object.<anonymous> (node_modules/duckdb/lib/duckdb.js:6:14)

```
Any solution or workaround?

**Comment by Mause** [comment]
I think I've figured out the issue here, and the probable solution. I'll look at fixing it now

See https://stackoverflow.com/questions/68598248/is-there-a-way-to-run-native-code-modules-using-worker-threads and https://github.com/nodejs/node-addon-api/issues/1190

**Comment by chrisbrain** [comment]
Hi @Mause Did you manage to look into this or know whether it's been fixed? It looks like we will need to be able to use DuckDB in a worker process.
