### ISSUE TITLE
Support for FOREIGN KEY

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#46]

**Comment by Mytherin** [comment]
Battle plan for this, use similar restrictions to SQLite: https://sqlite.org/foreignkeys.html

Foreign key constraints consist of two parts, `x REFERENCES t1(y)`

The column(s) `y` must either have a PRIMARY KEY or a UNIQUE constraint specified on them, otherwise the foreign key constraint cannot be specified. On insert to `x` the index on `t1(y)` is probed to check for matches. If no matches exist, an error is thrown.

Meanwhile, a non-unique index is constructed on top of `x`. On an update or a delete to `t1(y)`, this non-unique index is probed to verify that no reference to the previous column exists. If a reference, exists, we throw an exception as well.

The foreign key constraint also introduces a dependency between the two tables. In order to drop `t1`, the table containing `x` must first be dropped (or `CASCADE` must be specified). The same applies to dropping the column(s) `y`.

**Comment by travis-leith** [comment]
Do you have any plans to support this yet? Would be nice for the DB to guarantee its own consistency.

**Comment by Clonkk** [comment]
Any news on this issue ? 

I wanted to give a go to DuckDb but lack of foreign key makes it hard to port stuff from SQLite.

**Comment by chenxi8611** [comment]
I would like to add support for this feature, as I think it is great feature. Could you please let me know if this is something that I can go ahead and implement? 
@Mytherin  -- Do you have any feedback on the above?

**Comment by Mytherin** [comment]
> I would like to add support for this feature, as I think it is great feature. Could you please let me know if this is something that I can go ahead and implement?
> @Mytherin -- Do you have any feedback on the above?

Hey Chen, if you want to have a go at implementing it that would be great! Happy to review a PR.

Some pointers:

* The REFERENCES should point to a primary key of another table (or at least a row with a UNIQUE constraint)
* Foreign key relations require an index on both sides (one on the PRIMARY KEY side in t1, and one on the FOREIGN KEY side in t2).
* Foreign key constraints add a dependency between the table, so that the table with the primary key cannot be dropped
* Any row that is inserted into the table with the foreign key must exist in the table with the primary key (constraint)
* Any row that is deleted from the table with the primary key must not exist in the table with the foreign key (constraint)

Particularly a lot of care should be taken w.r.t. testing this in the presence of multiple transactions and rollbacks and such. For example, what happens if we insert a row in one transaction, then try to create a FK reference to that row in another transaction, but roll back the original? etc.

**Comment by chenxi8611** [comment]
Hi Mytherin, thanks for your pointers.
Implementing Foreign key, I will turn my attention to your pointers.
I think I will learn a lot as I implement Foreign Key in DuckDB. If I make a PR, please review it.

**Comment by Mytherin** [comment]
Thanks to @chenxi8611 this has now been implemented

**Comment by jdf-id-au** [comment]
Thank you, this is amazing. Are `on delete` actions planned, à la [sqlite](https://www.sqlite.org/foreignkeys.html)? I know this isn't the main point of duckdb, but it would be useful for purging bad loads:

```sql
create table upload (
  id integer primary key,
  source text,
  performed timestamp default get_current_timestamp(),
  other_metadata...
);
create table actual_data1 (
  upload_id integer references upload(id),  -- `on delete cascade` would be helpful here 
  ...
);
create table actual_data2 (
  upload_id integer references upload(id), -- and here
  ...
);
-- then use appender or sql to upload data including upload_id
delete from upload where id = 9; -- when accidentally uploaded something bad
```

**Comment by Crypto-Spartan** [comment]
+1 for a clause such as `ON DELETE CASCADE`, would be helpful
