### ISSUE TITLE
pyarrow same to my postgre‘s column type, but pandas can not

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#4604]
I need duckdb to speed some situation for my postgre tables, and this tables have array or json column, if use pandas.read_sql to df, it can't query directly in duckdb sql. 
for array column arr[1] will get '[' ,
but, if I convert df to pyarrow, it'll all OK, for example:
```
data_df=pd.read_sql("select * from tenant_baosheng_dm.dim_feature_define",conn)
data_ar = pa.Table.from_pandas(data_df)
dd.query("select feature_dim[1].column from data_ar").df()
```
feature_dim column is a json array like [{"column": "dim_skc.virtual_suit", "data_type": "text"}, ...]

**Comment by hannes** [comment]
Please use the issue template

**Comment by Tishj** [comment]
As far as I can see, this doesn't have nearly enough information to determine what the issue is
@wonb168 feel free to recreate this issue with additional information, following the issue template
