### ISSUE TITLE
Error: Invalid Error: Unsupported compression codec "ZSTD". Supported options are uncompressed, gzip or snappy

### ISSUE THREAD

**Issue by vbmithr** [duckdb/duckdb#4606]
### What happens?

Can't read a ZSTD compressed parquet file.

### To Reproduce

```D select * from read_parquet('/home/vb/code/dm/FTX/2022-04-29_08-26-33.146732/2022-04-29_08-26-33.146732/BTC_USD.trade.parquet') limit 10;
Error: Invalid Error: Unsupported compression codec "ZSTD". Supported options are uncompressed, gzip or snappy
```
[BTC_USD.trade.parquet.gz](https://github.com/duckdb/duckdb/files/9487821/BTC_USD.trade.parquet.gz)

### OS:

Linux

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Vincent Bernardoff

### Affiliation:

Deepmarker

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
This is indeed not supported yet. As such it's expected behaviour.

**Comment by vbmithr** [comment]
Other zstd compressed parquet file read fine, so I was wondering.

**Comment by hannes** [comment]
Ah never mind I was thinking of LZ4. ZSTD is indeed supported but not yet for v2 data pages. Will have a look.

**Comment by vbmithr** [comment]
Ha, this must be it, then! You can consider this issue as a feature request ;-)

**Comment by hannes** [comment]
Happy to review a PR. There is some complexity around name spacing, amalgamations and the fact that we usually strip down those dependencies.

**Comment by sundy-li** [comment]
lz4 is widely used, vote to add it.

**Comment by vbmithr** [comment]
I think this is fixed now. I can read zstd compressed parquet files OK. Closing.

**Comment by l1t1** [comment]
@sundy-li could you add lz4 for duckdb?

**Comment by l1t1** [comment]
clickhouse output parquet use lz4 by default.

**Comment by NekoApocalypse** [comment]
I second this. Polars also uses lz4 by default.
