### ISSUE TITLE
Prepared statements with PRAGMA not working with parameters

### ISSUE THREAD

**Issue by ant1j** [duckdb/duckdb#4609]
### What happens?

It seems that prepared statements with parameters are not working with some PRAGMA functions, especially the ones related to table info.
It returns a `Runtime Error` for `pragma table_info` and `pragma show`, 

```
Traceback (most recent call last):
  File "c:\Users\[...]\test_pragma_duckdb.py", line 8, in <module>
    print(con.execute("pragma table_info(?)", 'test').fetchdf())
RuntimeError: Catalog Error: Table with name $1 does not exist!
Did you mean "test"?
```

and a `Binder Error` for the SQL function `pragma_table_info`

```
Traceback (most recent call last):
  File "c:\Users\[...]\test_pragma_duckdb.py", line 12, in <module>
    print(con.execute("SELECT * FROM pragma_table_info(?)", 'test').fetchdf())
RuntimeError: Binder Error: Table function requires a constant parameter
LINE 1: SELECT * FROM pragma_table_info(?)
```

### To Reproduce

```python

import duckdb

con = duckdb.connect(database=':memory:')

con.execute("CREATE TABLE test (i INTEGER);")

# OK
print(con.execute("pragma table_info('test')").fetchdf())

# KO
print(con.execute("pragma table_info(?)", 'test').fetchdf())
print(con.execute("SELECT * FROM pragma_table_info(?)", 'test').fetchdf())
print(con.execute("pragma show(?)", 'test').fetchdf())
```

### OS:

windows 11

### DuckDB Version:

0.4.0

### DuckDB Client:

python

### Full Name:

Antoine Jouanjean

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Have you tried this on v0.5.0? At least `SELECT * FROM pragma_table_info(?)` should work now.

**Comment by ant1j** [comment]
On v0.5.0, even `SELECT * FROM pragma_table_info(?)` is not working, though the error message has changed:

`con.execute("SELECT * FROM pragma_table_info(?)", 'test').fetchdf()`

```python
Traceback (most recent call last):
  File "c:\Users\...\test_pragma_duckdb.py", line 13, in <module>
    print(con.execute("SELECT * FROM pragma_table_info(?)", 'test').fetchdf())
duckdb.InvalidInputException: Invalid Input Error: Prepared statement needs 1 parameters, 4 given
```
... but with `con.execute("SELECT * FROM pragma_table_info(?)", ['test']).fetchdf()` it works (notice the parameter is now in a list):
```
   cid name     type  notnull dflt_value     pk
0    0    i  INTEGER    False        NaN  False
```

I also confirm it does not work with the `PRAGMA` statements, as string or as a 1-item list - same error as for 0.40.

**Comment by Mytherin** [comment]
You need to submit a tuple, e.g.:

```sql
print(con.execute("SELECT * FROM pragma_table_info(?)", ('test',)).fetchdf())
```

Otherwise each character of the string is used as a different prepared statement parameter. The DB API is weird in this manner unfortunately.

**Comment by ant1j** [comment]
OK thanks for the clarification. 
That leaves the issue only for PRAGMA with prepared statement parameter. 
But there is a workaround for this specific case (table_info).
