### ISSUE TITLE
Can't select by blob field

### ISSUE THREAD

**Issue by wangfenjin** [duckdb/duckdb#4612]
### What happens?

After insert into table, select by equal seems not work

### To Reproduce

```shell
D CREATE TABLE blobs (b BYTEA);
D INSERT INTO blobs VALUES('\xaa\xff\xaa'), ('\xAA\xFF\xAA\xAA\xFF\xAA'), ('\xAA\xFF\xAA\xAA\xFF\xAA\xAA\xFF\xAA');
D SELECT * FROM blobs;
┌──────────────────────────────────────┐
│                  b                   │
├──────────────────────────────────────┤
│ \xAA\xFF\xAA                         │
│ \xAA\xFF\xAA\xAA\xFF\xAA             │
│ \xAA\xFF\xAA\xAA\xFF\xAA\xAA\xFF\xAA │
└──────────────────────────────────────┘
D SELECT * FROM blobs where b = '\xaa\xff\xaa';
D SELECT * FROM blobs where b = '\xAA\xFF\xAA';
D
```

### OS:

macOS

### DuckDB Version:

0.5.0

### DuckDB Client:

capi

### Full Name:

WANG FENJIN

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by wangfenjin** [comment]
I tried the 0.4.0 binary, the command line also not work. 

But the test code do works for 0.4.0

**Comment by lokax** [comment]
This problem is caused by changing the '\xAA'(one byte) into ('\\', 'x', 'A', 'A')(4 byte) form when checking the zonemap. I will try to fix it

**Comment by wangfenjin** [comment]
Thanks!

Not sure we will prepare a hot-fix release for this, or will wait for next version?
