### ISSUE TITLE
[Fuzzer] Invalid decimal definition

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4626]
### What happens?

```
CREATE TABLE x(x DECIMAL(38763269, 77914819));
```

Triggers assertion error: src/common/types.cpp:881: duckdb::DecimalTypeInfo::DecimalTypeInfo(uint8_t, uint8_t): Assertion `width_p >= scale_p' failed.

An error about either too large precision or scale values, or scale larger than precision should be thrown.

### To Reproduce

Run the statement above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Euhm, it would, if you didn't overflow the width/scale values
```c++
			if (scale > width) {
				throw ParserException("Scale cannot be bigger than width");
			}
```
`		int8_t width, scale;`

**Comment by PedroTadim** [comment]
Nice point ;)

**Comment by Tishj** [comment]
I guess it might be worth changing it to int64_t, just so we can handle cases like these ;)
