### ISSUE TITLE
ArrowArrayStream: non-nullable fields are scanned as nullable

### ISSUE THREAD

**Issue by FlorianUekermann** [duckdb/duckdb#4629]
### What happens?

We use the arrow C stream interface with duckdb in C++ and noticed that all fields seem to be nullable on the duckdb side, regardless of how the underlying schema. Below is a python reproducer (can't build `BUILD_ARROW_ABI_TEST=1 make debug` on my machine).

### To Reproduce

```
import duckdb
import pyarrow as pa

print(duckdb.__version__)

con = duckdb.connect()

field = pa.field("a", pa.int32(), nullable=False)
schema = pa.schema([pa.field("a", pa.int32(), nullable=False)])
array = pa.array([1,2,3])
recordbatch = pa.RecordBatch.from_arrays([array], schema=schema)

print(recordbatch.schema)

reader = pa.ipc.RecordBatchReader.from_batches(recordbatch.schema, [recordbatch])

print(con.execute("explain SELECT * FROM reader WHERE a = 2").arrow())
```
Output:
```
0.5.0
a: int32 not null
pyarrow.Table
explain_key: string
explain_value: string
----
explain_key: [["physical_plan"]]
explain_value: [["┌───────────────────────────┐
│         ARROW_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: a=2 AND a IS NOT │
│            NULL           │
│            EC=1           │
└───────────────────────────┘                             
"]]
```
Note: I would have preferred to use `describe reader`, but that doesn't seem to be supported in python.

### OS:

Linux

### DuckDB Version:

0.5.0

### DuckDB Client:

Python

### Full Name:

-

### Affiliation:

-

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Could you please tell us who "we" is? We have this field in the issue template but you did not fill it out. Thanks!
