### ISSUE TITLE
`to_days` & `to_months` functions throw error with `BIGINT` type argument

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#4631]
### What happens?

Very minor thing, if it's even an issue. Utilizing the interval function `to_days` or `to_months` expects an `INTEGER`, but interval functions like `extract` return`BIGINT`s, which – if fed into one of these functions – throws an error.

It does not throw for other functions like `to_seconds` or `to_milliseconds`, which makes sense since there are likely to be larger values put into these.

Just wondering if there was a design reason for this.

### To Reproduce

in the CLI:

```
SELECT to_days(1043::bigint);
```

### OS:

Mac

### DuckDB Version:

`0.4.0` and `0.5.0`

### DuckDB Client:

CLI, Node

### Full Name:

Hamilton Ulmer

### Affiliation:

Rill Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Intervals have `months` and `days` fields that are `INTEGER`s and a `micros` field that is a`BIGINT`, so it actually makes sense to force the user to cast.

**Comment by hamilton** [comment]
Makes sense, thanks for the explanation.
