### ISSUE TITLE
DuckDB/PyArrow support for query on Arrow UnionDataset

### ISSUE THREAD

**Issue by ak2k** [duckdb/duckdb#4632]
### What happens?

When attempting any query/scan operation on an [Arrow UnionDataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.UnionDataset.html), this error is generated: 

> duckdb.InvalidInputException: Invalid Input Error: Python Object UnionDataset not suitable for replacement scans

(ref https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L579)

I wondered whether it's something that's not supportable without meaningful effort or just doesn't happen to be currently designated as supported and could easily be.

Thank you,

### To Reproduce

Please let me know whether a repro script would be helpful. In this instance, I'm rather more intending to ask a question regarding intent to support than to report a bug.

Thank you!

### OS:

macos

### DuckDB Version:

0.5.0

### DuckDB Client:

Pyhon

### Full Name:

Adam Kirby

### Affiliation:

Individual

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ak2k** [comment]
In particular, [IsAcceptedArrowObject(...)](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L707) seems to list only certain types, which does not currently include UnionDataset, hence the question.

**Comment by ak2k** [comment]
I have confirmed that wrapping the UnionDataset in a Scanner (for no other purpose than to work around it not being in [IsAcceptedArrowObject](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L707)) seems to work fine in my use case.

**Comment by pdet** [comment]
Hi @ak2k, we do have a goal of using protocols to detect these types, There is already a PR for that #4435 but I think it hasn't been merged due to the feature freeze for the recent release :-)

**Comment by ak2k** [comment]
Hi @pdet, Thank you, that's very helpful!
