### ISSUE TITLE
Possible `DATE_DIFF` inaccuracy because of integer division?

### ISSUE THREAD

**Issue by amirrajan** [duckdb/duckdb#4635]
### What happens?

It looks like `date_diff` returns an incorrect value because of how epoch is extracted and divided by seconds intervals.

`date_diff('week', '2015-10-06 04:22:11'::timestamp, '2016-11-25 23:19:37'::timestamp)` returns `60` instead of `59`.

### To Reproduce

```sql
SELECT EXTRACT(EPOCH FROM TIMESTAMP '2015-10-06 04:22:11') as start_date,

       EXTRACT(EPOCH FROM TIMESTAMP '2016-11-25 23:19:37') as end_date,

       EXTRACT(EPOCH FROM TIMESTAMP '2016-11-25 23:19:37') -
       EXTRACT(EPOCH FROM TIMESTAMP '2015-10-06 04:22:11') as seconds_between,

       (EXTRACT(EPOCH FROM TIMESTAMP '2016-11-25 23:19:37') -
        EXTRACT(EPOCH FROM TIMESTAMP '2015-10-06 04:22:11')) / (60 * 60 * 24 * 7) as date_diff_week_manual,

       (EXTRACT(EPOCH FROM TIMESTAMP '2016-11-25 23:19:37') / (60 * 60 * 24 * 7)) -
       (EXTRACT(EPOCH FROM TIMESTAMP '2015-10-06 04:22:11') / (60 * 60 * 24 * 7)) as date_diff_week_manual_2,

       (EXTRACT(EPOCH FROM TIMESTAMP '2016-11-25 23:19:37') / (60 * 60 * 24 * 7)::float) -
       (EXTRACT(EPOCH FROM TIMESTAMP '2015-10-06 04:22:11') / (60 * 60 * 24 * 7)::float) as date_diff_week_manual_3,

       date_diff('week', '2015-10-06 04:22:11'::timestamp, '2016-11-25 23:19:37'::timestamp) as date_diff_week_fn
```
yields
```
┌────────────┬────────────┬─────────────────┬───────────────────────┬─────────────────────────┬─────────────────────────┬───────────────────┐
│ start_date │  end_date  │ seconds_between │ date_diff_week_manual │ date_diff_week_manual_2 │ date_diff_week_manual_3 │ date_diff_week_fn │
├────────────┼────────────┼─────────────────┼───────────────────────┼─────────────────────────┼─────────────────────────┼───────────────────┤
│ 1444105331 │ 1480115977 │ 36010646        │ 59                    │ 60                      │ 59.541504               │ 60                │
└────────────┴────────────┴─────────────────┴───────────────────────┴─────────────────────────┴─────────────────────────┴───────────────────┘
```

- `date_diff_week_manual` divides the difference of start and end date by seconds in week (integer division).
- `date_diff_week_manual_2` divides each epoch by seconds in week _first_ (integer division), then takes the difference.
- `date_diff_week_manual_3` divides each epoch by seconds in week _first_ (floating point division), then takes the difference.

### OS:

MacOS

### DuckDB Version:

v0.3.3-dev918 3111480a9

### DuckDB Client:

CLI Interface

### Full Name:

Amir Rajan

### Affiliation:

Mode

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Thanks for your interest in DuckDB! 

I know this may seem confusing, but this is actually [the definition from T-SQL](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver16):

> This function returns the count (as a signed integer value) of the specified datepart **boundaries crossed** between the specified _startdate_ and _enddate_.

All of the `DATE_DIFF` functions do this: align to the part boundary and then count the crossings. The documentation actually says this, although I agree it might not be immediately obvious:

> The number of [partition](https://duckdb.org/docs/sql/functions/datepart) boundaries between the dates

**Comment by amirrajan** [comment]
I may be mistaken, but MSSQL and Snowflake both return `59`.

**Comment by hawkfish** [comment]
Hmm I wonder if this is just specific to the week?

**Comment by amirrajan** [comment]
@hawkfish I think so. From what I reviewed on line, it depends on how many Sundays are crossed

**Comment by hawkfish** [comment]
Thanks - that's what I was wondering. I'm not sure I have access to an MS-SQL server for testing so I might make up a small test case and post it.

**Comment by rkennedy-mode** [comment]
The days in question, `2015-10-06 04:22:11` and `2016-11-25 23:19:37`, are a Tuesday and a Friday respectively. January 1, 1970 (start of the UNIX epoch) was a Thursday. The fact that Thursday falls between Tuesday and Friday is where DuckDB's extra week is coming from. DuckDB is assuming that Thursday is the start of every week.

We had to address this in our implementation of DATEDIFF for VoltDB by adjusting the start and end date back to the prior start of the week day. So in the above case we'd adjust the start back to the prior Sunday (`2015-10-04`) and the end day back to the prior Sunday (`2016-11-20`). Then we'd convert those dates to epoch seconds (1443975731 and 1479683977) and floor divide them by the number of seconds in a week (604800) to get the "epoch week" for each (2387 and 2446) and then subtract those to determine the Sunday-based week boundaries between them (59).

So the only time DuckDB is correct with `date_diff('week', start, end)` is when you treat Thursday as the start of the week, which almost nobody does. 😆

**Comment by hawkfish** [comment]
Yes, the non-ICU version was not aligning correctly. FWIW, ICU aligns using ISO start of week (Monday) and was correct.

**Comment by hawkfish** [comment]
Small difference with MS-SQL: We truncate weeks to Monday, so `DATE_DIFF` should count those crossings for consistency.

**Comment by amirrajan** [comment]
@hawkfish thanks for re-opening the tick. Glad I was able to contribute by finding this really subtle edge case.
