### ISSUE TITLE
[Fuzzer] Incomplete checkpoints issue

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4644]
### What happens?

On a clean persisted database do:
```
CREATE SCHEMA s1;
CHECKPOINT;
DROP SCHEMA s1;
CHECKPOINT;
PRAGMA DEBUG_CHECKPOINT_ABORT = 'after_free_list_write';
CREATE SCHEMA s3;
CHECKPOINT; --error IO Error: Checkpoint aborted after free list write because of PRAGMA checkpoint_abort flag
CHECKPOINT; --error IO Error: Checkpoint aborted after free list write because of PRAGMA checkpoint_abort flag
```
After restart, a WAL error is thrown: Exception in WAL playback: Catalog Error: Schema with name s3 already exists!

It seems the schema s3 was "checkpointed", ie written to persistent storage twice when it shouldn't.

If another `CHECKPOINT` is performed before the restart, an assertion error is thrown:
src/storage/single_file_block_manager.cpp:238: virtual void duckdb::SingleFileBlockManager::MarkBlockAsModified(duckdb::block_id_t): Assertion `block_id >= 0' failed.

### To Reproduce

Run the statements above. I may be wrong on some points, but I think there is an issue for sure.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

The `debug_checkpoint_abort` pragma is intended to simulate a crash happening at a specific point during the checkpoint process. As such, running multiple statements with this pragma enabled is not particularly interesting when it comes to modeling actual workloads. After all - a crash means the database has gone down entirely - so logically there would be no further statements after the crash.

I have pushed a fix that makes the checkpoint abort pragma throw fatal exceptions instead - which disable using the entire database system after they are thrown. That should better model the intention of the debug pragma.
