### ISSUE TITLE
DuckDB Unaware of Pandas Indexes

### ISSUE THREAD

**Issue by fny** [duckdb/duckdb#4645]
### What happens?

Alas, DuckDB is unaware of Pandas indexes. You can't group by them or select them.

### To Reproduce

```python
import duckdb
import pandas as pd
import numpy as np

df = pd.DataFrame({
  'i1': np.arange(0, 100),
  'i2': np.arange(0, 100),
  'c': np.random.randint(0 , 10, 100)
}).set_index(['i1', 'i2'])

>>> duckdb.query('select sum(c) from df group by i1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Binder Error: Referenced column "i1" not found in FROM clause!
Candidate bindings: "df.c"
```

### OS:

macOS 12.5.1

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Faraz Yashar

### Affiliation:

Duke University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you please ensure you're using the most recent python version? Your error message looks like it's from an older version
