### ISSUE TITLE
[Fuzzer] Failed alter table statement and later analyze error

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4647]
### What happens?

Run the following statements:

```
CREATE TABLE t0 (c0 INT);
CREATE UNIQUE INDEX i1 ON t0 (c0);
ALTER TABLE t0 RENAME TO t3; -- Catalog Error: Cannot alter entry "t0" because there are entries that depend on it
DROP TABLE t0;
ANALYZE t3;
```

The undefined error sanitizer finds an issue: src/catalog/catalog_set.cpp:363:18: runtime error: member access within null pointer of type 'duckdb::CatalogEntry'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/catalog/catalog_set.cpp:363:18 in

The analyze should throw an error about an inexisting table "t3".

I guess I should stop this for a while. Sorry for the many issues :)

### To Reproduce

Run the steps above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
@PedroTadim thanks for filing all those issues. Maybe you could spend some time sending PRs for fixes? Thanks

**Comment by PedroTadim** [comment]
Yes I could, but I have to learn the codebase first

**Comment by taofengliu** [comment]
I will try to fix this.
