### ISSUE TITLE
R client fails to recognize connections and some compression algorithms

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#4649]
### What happens?

We cannot use `duckdb_read_csv()` to import files compressed with common algorithms like bz2, though gz works. Further,  R natively supports compressed connections of type gz, bz2, and xz, however, if we pass a compressed connection (e.g. created by `gzfile()`, `duckdb_read_csv()` errors telling us that this is not a connection.  See reprex below

### To Reproduce

```r
library(duckdb)
db <- DBI::dbConnect(duckdb::duckdb())


readr::write_tsv(mtcars, "mtcars.tsv.gz")
## Works
duckdb::duckdb_read_csv(db, name = "mtcars", files = "mtcars.tsv.gz", delim="\t")

## Fails
duckdb::duckdb_read_csv(db, name = "mtcars", files = gzfile("mtcars.tsv.gz"), delim="\t")

## Fails
readr::write_tsv(mtcars, "mtcars.tsv.bz2")
duckdb::duckdb_read_csv(db, name = "mtcars", files ="mtcars.tsv.bz2", delim="\t")
duckdb::duckdb_read_csv(db, name = "mtcars", files = bzfile("mtcars.tsv.bz2"), delim="\t")
```

### OS:

Linux (ubuntu 20.04)

### DuckDB Version:

0.5.0

### DuckDB Client:

R

### Full Name:

Carl Boettiger

### Affiliation:

UC Berkeley

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
We don't use the R connection for the CSV reader or elsewhere so this is expected.

**Comment by cboettig** [comment]
Sorry, I should have included the error message:

```
> duckdb::duckdb_read_csv(db, name = "mtcars", files = gzfile("mtcars.tsv.gz"), delim="\t")
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  'file' must be a character string or connection
 ```

This confused me, since the error says that is should be a connection (I see the error is coming from `read.table()`, which does take connections.  

I also don't see a list of which compression types are supported and which aren't in the R function documentation. It's awesome that .gz works but might be good to mention it in the R documentation?
