### ISSUE TITLE
timestamp is incorrect, 8 hours different

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#4651]
### What happens?

select current_timestamp ; 2022-09-08 04:09:30.485
the right time is 12:09:30

### To Reproduce

select current_timestamp ;
┌──────────────────────────────┐
│ main.get_current_timestamp() │
├──────────────────────────────┤
│ 2022-09-08 04:09:30.485

SELECT current_setting('TimeZone');
┌─────────────────────────────┐
│ current_setting('TimeZone') │
├─────────────────────────────┤
│ Asia/Shanghai

### OS:

win10

### DuckDB Version:

0.4.0

### DuckDB Client:

0.4.0

### Full Name:

wang.cz

### Affiliation:

linezone.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Could you retest in version 0.5.0 please?
Also, which client are you using refers to Python vs. the command line tool vs R, etc. Which client are you using?

**Comment by Mause** [comment]
This is a current limitation of our timezone support unfortunately - you'll find that the time is correct, it's just in UTC instead of `Asia/Shanghai`

**Comment by wonb168** [comment]
> Could you retest in version 0.5.0 please? Also, which client are you using refers to Python vs. the command line tool vs R, etc. Which client are you using?

python or command all wrong, v0.5.0
import duckdb as dd
dd.query("select current_timestamp").df()

**Comment by wonb168** [comment]
> 

but I need current_timestamp to write csv or db, it'll output wrong time, how to correct it?

**Comment by hawkfish** [comment]
Unfortunately we deviate a bit from the standard in two ways:
1. We return a `TIMESTAMP` from `current_timestamp` instead of `TIMESTAMP WITH TIME ZONE`
2. We do not format the latter using the current time zone, but in GMT (with an offset of +00)

If you need to write the value to a CSV in the current time zone, then you need to cast it to a `TIMESTAMPTZ` and explicitly format it as a `VARCHAR` using `strftime`:

```sql
-- Z for time zone name
select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %Z');
2022-09-08 19:18:25.554000 Australia/Sydney

-- z for GMT offset
select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %Z');
2022-09-08 19:19:43.566000 +10
```
Fixing this is on the TODO list as #3188.

**Comment by wonb168** [comment]
> Unfortunately we deviate a bit from the standard in two ways:
> 
> 1. We return a `TIMESTAMP` from `current_timestamp` instead of `TIMESTAMP WITH TIME ZONE`
> 2. We do not format the latter using the current time zone, but in GMT (with an offset of +00)
> 
> If you need to write the value to a CSV in the current time zone, then you need to cast it to a `TIMESTAMPTZ` and explicitly format it as a `VARCHAR` using `strftime`:
> 
> ```sql
> -- Z for time zone name
> select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %Z');
> 2022-09-08 19:18:25.554000 Australia/Sydney
> 
> -- z for GMT offset
> select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %z');
> 2022-09-08 19:19:43.566000 +10
> ```
> 
> Fixing this is on the TODO list as #3188.
why? year is wrong, 4659?

D select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %Z');
┌────────────────────────────────────────────────────────────────────────────────────┐
│ strftime(CAST(main.get_current_timestamp() AS TIMESTAMP WITH TIME ZONE), '%Y-%m... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 4659-08-14 01:08:32.118000 UTC                                                     │
└────────────────────────────────────────────────────────────────────────────────────┘
D select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %z');
┌────────────────────────────────────────────────────────────────────────────────────┐
│ strftime(CAST(main.get_current_timestamp() AS TIMESTAMP WITH TIME ZONE), '%Y-%m... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 4659-08-14 01:08:48.486000 +00

**Comment by hawkfish** [comment]
You appear to be using the `chinese` calendar (it looks like ICU defaults to that in your locale):

```sql
D set Calendar='chinese';
D select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %z');
┌────────────────────────────────────────────────────────────────────────────────────┐
│ strftime(CAST(main.get_current_timestamp() AS TIMESTAMP WITH TIME ZONE), '%Y-%m... │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 4659-08-14 13:43:38.376000 +10                                                     │
└────────────────────────────────────────────────────────────────────────────────────┘
```

You need to set it to `gregorian`.  Here are all the calendars we support:

```sql
D select * from icu_calendar_names();
┌─────────────────────┐
│        name         │
├─────────────────────┤
│ gregorian           │
│ japanese            │
│ buddhist            │
│ roc                 │
│ persian             │
│ islamic-civil       │
│ islamic             │
│ hebrew              │
│ chinese             │
│ indian              │
│ coptic              │
│ ethiopic            │
│ ethiopic-amete-alem │
│ iso8601             │
│ dangi               │
│ islamic-umalqura    │
│ islamic-tbla        │
│ islamic-rgsa        │
└─────────────────────┘
```

**Comment by wonb168** [comment]
Yes, I changed it to chinese ,
but, why not use Timezone to get the right time?
select strftime(current_timestamp::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %z');
this is too long vs select current_timestamp.
and almost dbs are using timezone rather than strftime.

**Comment by hawkfish** [comment]
> why not use Timezone to get the right time?

It is "the right time" but it is not [binned](https://duckdb.org/2022/01/06/time-zones.html) for your locale.

As I mentioned above, we deviate from the standard in two ways for reasons that I hope will be temporary. 

1. We do not return `TIMESTAMPTZ` from `current_timestamp` because our support for `TIMESTAMPTZ` is via the ICU plugin and we want it to work for the case when ICU is not available/loaded. We may change this.
2. We do not currently support casting `TIMESTAMPTZ` to `VARCHAR` because of an architectural limitation tracked by #3188, and we hope to fix this in the not to distant future.

In the meantime, you can write a SQL macro to simplify your code:

```sql
CREATE MACRO tzv(ts) AS strftime(ts::TIMESTAMPTZ, '%Y-%m-%d %H:%M:%S.%f %z');
```

Then you can just write `tsv(current_timestamp)`.

**Comment by hawkfish** [comment]
> but I need current_timestamp to write csv or db, it'll output wrong time, how to correct it?

I would strongly suggest that you not use a locale-specific format for storing data (either in a CSV or a database). Store an instant (UTC) and use ICU for binning (e.g., `date-part`) and display (`strftime`) operations. Anything else will likely cause you a lot of pain down the road.
