### ISSUE TITLE
Aggregate Query Produces Error After Upgrading to Version 0.5.0

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#4652]
### What happens?

I recently upgraded from version 0.4.0 to 0.5.0.  There is an aggregation we do daily that uses data from the past 6 months.  Previously, there were never any issues with this, but now I get the following error:  `Error: Invalid Error: String value is not valid UTF8`

When I take a divide-and-conquer approach to doing the query then the problem does not persist.  What I mean by this is doing the same query but considering only 1 month of data at a time, and combining all the results together at the end.  The query itself is quite complex so I won't bother posting it here, but could someone please give me some pointers as to what might be happening?

### To Reproduce

I don't have a reproducible version of this yet.  When I have one I will post it here.

### OS:

Windows 10

### DuckDB Version:

0.5.0

### DuckDB Client:

Python

### Full Name:

Vincent Munos

### Affiliation:

Admolly

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Could you please provide a reproducible example? As it is your bug report is not actionable.

**Comment by Admolly** [comment]
I think something may have gone wrong during the EXPORT/IMPORT step, as I'm also encountering some issues with timestamp columns.  Are there any options I can specify when copying tables from parquet format that might be helpful here?

**Comment by Admolly** [comment]
For instance, I found the following from this query, the date and date parts don't match up:

```
select 
  id, 
  database, 
  birthdate::date birthdate,
  extract(day from birthdate),
  extract(month from birthdate),
  extract(year from birthdate),
from users 
where id = 1082117 and database = 'united_kingdom'
```

|    |      id | database       | birthdate                     |   main.date_part('day', birthdate) |   main.date_part('month', birthdate) |   main.date_part('year', birthdate) |
|---:|--------:|:---------------|:------------------------------|-----------------------------------:|-------------------------------------:|------------------------------------:|
|  0 | 1082117 | united_kingdom | 2115-11-10 23:34:33.709551616 |                                 23 |                                    4 |                                1531 |

**Comment by Admolly** [comment]
OK, so apparently duckdb throws an error if you query a timestamp prior to 1677-09-22.  If you try to coerce that timestamp to a date, it will tell you that it's from sometime far in the future:

`con.execute("select '1677-09-21'::timestamp").fetchdf()`:

`ConversionException: Conversion Error: Could not convert Timestamp(US) to Timestamp(NS)`

`con.execute("select '1677-09-21'::timestamp::date").fetchdf()`:

|    |   CAST(CAST('1677-09-21' AS TIMESTAMP) AS DATE) |
|---:|------------------------------------------------:|
|  0 |                                     2262-04-11 23:34:33.709551616|

**Comment by hawkfish** [comment]
This looks like a Python binding problem - it works fine in the CLI:

```sql
D select CAST(CAST('1677-09-21' AS TIMESTAMP) AS DATE);
┌───────────────────────────────────────────────┐
│ CAST(CAST('1677-09-21' AS TIMESTAMP) AS DATE) │
├───────────────────────────────────────────────┤
│ 1677-09-21                                    │
└───────────────────────────────────────────────┘
```

**Comment by Tishj** [comment]
Probably another result of my changes to TransformPythonObject, I'll have a look tomorrow (later today that is ;))

**Comment by Admolly** [comment]
Can anyone suggest a way to find the strings which are not valid UTF8?  I'm not sure how they made their way into the database but it would be really nice to find them so I can try and fix them.

**Comment by hannes** [comment]
Thanks for sharing your query, but this is still not reproducible I'm afraid. Can you maybe try to create a synthetic dataset that demonstrates the issue?

**Comment by Admolly** [comment]
Hi Hannes,  thank you for your response.  I am indeed working on creating a reproducible example, but please bare in mind that, without a better understanding of the bug, this will not be straightforward.  I will do my best to create something in the coming week, but I suspect this will require much trial & error.  I can confirm however that, after downgrading to verion 0.3.2, the query does execute cleanly on the same dataset.  I was unable to test with versions 0.3.3, 0.3.4, and 0.4.0 because of issues related to [3438](https://github.com/duckdb/duckdb/issues/3438) and [3949](https://github.com/duckdb/duckdb/issues/3949), but I do recall that it worked on the previous development version we were running which I believe was 0.4.1-dev102.  I did try the query on another development version, 0.4.1.dev2401, which is not longer available, and the query produced the same error as above.  On a side note, is it possible you could make this dev version (102) temporarily available?  It includes the JSON extension, upon which we currently rely quite heavily at the moment.  Will do my best to get you guys a dataset to troubleshoot this with.

**Comment by Admolly** [comment]
Hi @hannes I have an anonymized dataset ready that illustrates the bug.  Can you suggest a secure way for us to transfer you the files?

**Comment by hannes** [comment]
@Admolly As discussed, please reconsider supporting the DuckDG Foundation given your commercial use case. As a perk, foundation donors can share datasets with us privately.
