### ISSUE TITLE
Inconsistent semantics of type identifiers

### ISSUE THREAD

**Issue by lokax** [duckdb/duckdb#4658]
### What happens?

INT8 can represent either 8 bits or 8 bytes (Although INT8 represents BIGINT in duckdb.). And UINT8 can only represent 8 bits in duckdb. 
I think only one usage should be allowed.
for example,
INT1, INT2, INT4, INT8
or
INT8, INT16, INT32, INT64

### To Reproduce

```SQL
SELECT typeof(8::INT1);
────────────────────────────┐
│ typeof(CAST(8 AS TINYINT)) │
├────────────────────────────┤
│ TINYINT                    │
└────────────────────────────┘

SELECT typeof(8::INT8);
┌───────────────────────────┐
│ typeof(CAST(8 AS BIGINT)) │
├───────────────────────────┤
│ BIGINT                    │
└───────────────────────────┘
SELECT typeof(8::INT16);
┌─────────────────────────────┐
│ typeof(CAST(8 AS SMALLINT)) │
├─────────────────────────────┤
│ SMALLINT                    │
└─────────────────────────────┘
SELECT typeof(8::UINT8);
┌─────────────────────────────┐
│ typeof(CAST(8 AS UTINYINT)) │
├─────────────────────────────┤
│ UTINYINT                    │
└─────────────────────────────┘
SELECT typeof(8::UINT1);
Error: Catalog Error: Type with name UINT1 does not exist!
Did you mean "uint8"?
```

### OS:

linux

### DuckDB Version:

master

### DuckDB Client:

shell

### Full Name:

lokax

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I wholeheartedly agree, but this is inherited from Postgre and if I recall correctly we want to keep this for compatibility reasons

**Comment by Tishj** [comment]
INT8 being a BIGINT is inherited from PSQL and intentionally kept for compatibility reasons.

I personally hate this, as we have INT16, INT32 and INT64 being SMALLINT, INTEGER, BIGINT respectively.
I would vote to get rid of INT8 being a BIGINT, and instead make it a TINYINT. But for the reason I mentioned, this is very unlikely to happen.

I agree the inconsistencies between INT and UINT are not ideal, but I prefer much less to subject UINT to the same semantics as the INT type
