### ISSUE TITLE
Updated DuckDB Release Changes STR_SPLIT from Zero Indexed to One Indexed

### ISSUE THREAD

**Issue by KeeonTabrizi** [duckdb/duckdb#4665]
### What happens?

Previously [str_split(string, separator)](https://duckdb.org/docs/sql/functions/char) operated with zero based indexing.

Possibly recent DuckDB releases (+0.4.0?) has changed this to one-based indexing breaking prior existing code/functions dependent on zero-based indexing. 

**NOTE: I am utilizing DuckDB through Hex.tech which is using 0.4.0 currently.**

Looking at the recent release and the diff I see a change to the underlying string_split.cpp file:

![image](https://user-images.githubusercontent.com/3408390/189404386-5c914192-15b4-4229-a397-866bd1389c15.png)

Base on these docs here: https://duckdb.org/docs/sql/data_types/list it appears 0 based indexing is still intended.

### To Reproduce

This previously would return `1`, now returns `NaN`. Changing to [1] will now return `1`.

```sql
SELECT STR_SPLIT('1, 2', ',')[0]
```

### OS:

macOS 12.2.1

### DuckDB Version:

0.4.0

### DuckDB Client:

Python (Hex.Tech)

### Full Name:

Keeon Tabrizi

### Affiliation:

- 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello! Sorry that the docs are out of date! 1 indexed is what DuckDB now supports (to align with how instr and substr work, etc).
This change happened before 0.4.0 though: version 0.3.3!

**Comment by hannes** [comment]
Yes indeed this was changed to be more compatible with other SQL systems like Postgres.
