### ISSUE TITLE
ODBC SQLColumns Function returns rows for all tables in the database

### ISSUE THREAD

**Issue by faridzidan** [duckdb/duckdb#4666]
DuckDB 0.50
Windows 10 x64

I have a database with 97 tables.
I execute ODBC SQLColumns function on one table
I get the columns for all tables in the database.

**Comment by Mause** [comment]
Looks like we're missing a ! on https://github.com/duckdb/duckdb/blob/0d3368c18cb77aaa4c581ff2c71d7b45d88be7d9/tools/odbc/odbc_utils.cpp#L171
