### ISSUE TITLE
[Fuzzer] heap-buffer-overflow on ALTER statement

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4677]
### What happens?

Run the following statements:
```
CREATE TABLE t0(c0 AS (1), c1 INT);
ALTER TABLE t0 ALTER c1 SET NOT NULL;
```
The address sanitizer will report a heap-buffer-overflow.

The alter statement should succeed.

### To Reproduce

Run the statement above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by zippond** [comment]
oh sorry, just noticed you've self-assigned @Mytherin , would you mind checking my fix?

**Comment by Mytherin** [comment]
Ah, no worries. Your fix looks good to me. Happy to go with that.
