### ISSUE TITLE
[Fuzzer] Update default SEGV

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4678]
### What happens?

Run the statements:
```
CREATE TABLE t0(c0 VARCHAR, c2 AS(1), c3 INT, UNIQUE(c0));
UPDATE t0 SET c0 = DEFAULT;
```
It will generate a SEGV at src/storage/data_table.cpp:1392

Should the update succeed? I am not sure about the semantics for DEFAULT values when is not set by the user.

### To Reproduce

Run the statements above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by PedroTadim** [comment]
I just got an assertion error that may be related to this issue:
```
CREATE TABLE t1(c4 UUID, c0 REAL AS(0));
ALTER TABLE t1 ALTER c0 SET DEFAULT 0;
```
src/catalog/catalog_entry/table_catalog_entry.cpp:458: unique_ptr<duckdb::CatalogEntry> duckdb::TableCatalogEntry::SetDefault(duckdb::ClientContext &, duckdb::SetDefaultInfo &): Assertion `!copy.Generated()' failed.

**Comment by Mytherin** [comment]
> Should the update succeed? I am not sure about the semantics for DEFAULT values when is not set by the user.

Default defaults (hah) to NULL, so this should succeed. See e.g. Postgres behavior:

```sql
> CREATE TABLE t0(c0 VARCHAR);
> INSERT INTO t0 VALUES ('hello');
> UPDATE t0 SET c0=DEFAULT;
> SELECT * FROM t0;

 c0 
----
 

```
