### ISSUE TITLE
Regression in Decimal handling in 0.5.0

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#4688]
### What happens?

We are encountering a regression with the handling of dataframes with Python `Decimal` values in them with the 0.5.0 release. It appears to be an issue with how the width and scale parameters are inferred. I have checked our minimal repro and 0.4.0 is not affected, but 0.5.0 and the latest master branch builds are.

### To Reproduce

First we construct a dataframe with some Decimal values in it:

```python
import pandas as pd
from decimal import Decimal

decimals = pd.DataFrame(
    data={
        "decimals": [
            Decimal("0.00"),
            Decimal("125.90"),
            Decimal("0.00"),
            Decimal("2502.63"),
            Decimal("0.00"),
            Decimal("0.00"),
            Decimal("321.00"),
        ]
    }
)
```

Then we try to query it:

```python
import duckdb

conn = duckdb.connect(database= ":memory", read_only=False)
conn.register("decimals", decimals)

conn.execute("select * from decimals")
result = conn.df()
```

This yields the error:

```
InvalidInputException: Invalid Input Error: Failed to cast value: Casting value "125.90" to type DECIMAL(38,39) failed: value is out of range!
```

### OS:

macOS, Linux

### DuckDB Version:

0.5.0

### DuckDB Client:

Python

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
To elaborate, the issue is caused by one or more of these (**but not all**) conversions not being recognized as a valid decimal, falling back to double/float - And casting this to the final type of the column (DECIMAL) causes this error to be thrown

**Comment by dylanscott** [comment]
Appreciate the quick investigation @Tishj !
