### ISSUE TITLE
Port test cases from Python sqlite module

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#469]
> I was thinking it could be a good idea to reuse the test suite for the sqlite module included in CPython if possible :
> 
> https://github.com/python/cpython/tree/master/Lib/sqlite3/test
> 
> The test suite is quite extensive and tests many corner cases. This would ensure the bindings are a drop in for the python sqlite module.
> 

CC @tenko

**Comment by hannesmuehleisen** [comment]
CC @jwills

**Comment by thesketh** [comment]
@hannesmuehleisen I've been having a quick look at this ticket and it looks like it could be a good first issue, I'll try to pick it up this week.

Some of the tests will need to be changed to work with DuckDB's Python wrapper in its current form (e.g. specific error types vs `RuntimeError`s in DuckDB), so I'll document where I alter them and why.

**Comment by hannes** [comment]
Not that much of a priority. Feel free to comment if you'd like to pick this up.
