### ISSUE TITLE
Error: IO Error: No files found that match the pattern "[Avalon]_daily-avg.csv"

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#4699]
### What happens?

I am trying to load a CSV file named `[Avalon]_daily-avg.csv` with `SELECT * FROM '[Avalon]_daily-avg.csv';` but get the error `Error: IO Error: No files found that match the pattern "[Avalon]_daily-avg.csv"`. 

### To Reproduce

Run `duckdb` and then the query above. 

### OS:

macOS

### DuckDB Version:

v0.5.0 109f932c4

### DuckDB Client:

CLI

### Full Name:

Domini Moritz

### Affiliation:

CMU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Could be that it's interpreted as a regex pattern, in which case you might need to escape the `[` and `]` characters
```sql
SELECT * FROM '\[Avalon\]_daily-avg.csv';
```

**Comment by domoritz** [comment]
I tried that but I don't see to find the right escaping yet. 

<img width="683" alt="Screenshot 2022-09-13 at 14 45 23" src="https://user-images.githubusercontent.com/589034/189984722-3c19e5fc-b960-47fc-aca9-aa613f6e2953.png">

**Comment by Alex-Monahan** [comment]
I think wrapping it in another set of brackets should work?
[[Avalon]]_daily-avg.csv

**Comment by domoritz** [comment]
Unfortunately not

<img width="702" alt="Screenshot 2022-09-13 at 16 58 51" src="https://user-images.githubusercontent.com/589034/190007988-3862ccc1-2a99-4ef1-a690-d02fe17366ed.png">

**Comment by Mytherin** [comment]
The CSV reader use [glob syntax](https://duckdb.org/docs/sql/functions/patternmatching) - brackets signify "use any character within these brackets". The correct pattern is:

```sql
select * from '[[]avalon[]]_daily-avg.csv';
```

Perhaps we should add a fallback where if we no matches are found we try a literal pattern instead to avoid this problem in the future?

**Comment by domoritz** [comment]
That would be a great UX improvement. Great idea! 

What happens if the glob matches multiple files? Do we get a union?

**Comment by Mytherin** [comment]
Yes, the CSV files will be unioned together provided they all share the same schema. You can use most standard globbing features including `*` to match multiple files.

I would say for the fallback this only happens in case the glob matches no files.

**Comment by domoritz** [comment]
That's perfect. Thanks for the fix!

I actually have multiple files so what I should do is `*.csv';` Unfortunately my schemas are compatible but not the same (not all tables have all the columns). Is there an easy way to generate the COLUMNS JSON from an existing table? Something like `DESCRIBE AS JSON xxx`?

**Comment by Mytherin** [comment]
Perhaps you could try the latest `UNION BY NAME` syntax, e.g.:

```sql
D SELECT 1 a, 2 b UNION BY NAME SELECT 100 a, 101 c;
┌─────┬──────┬──────┐
│  a  │  b   │  c   │
├─────┼──────┼──────┤
│ 1   │ 2    │ NULL │
│ 100 │ NULL │ 101  │
└─────┴──────┴──────┘
```

**Comment by domoritz** [comment]
Uhh, that's exactly what I was thinking I would want but it seemed tricky so I didn't propose it. How difficult would it be to make `UNION BY NAME` the default for CSV imports (I got more than two files)? 

Otherwise what I am hearing is that I should load each file into a table and then union them all (which works well but negates the benefit of the glob):
 
```sql
SELECT * FROM '[[]Avalon[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]Liberty (SAHS)[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]Parkway East (Near Road)[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]Glassport High Street[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]Manchester[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]USA-Pennsylvania-Pittsburgh[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]Lawrenceville[]]_daily-avg.csv' UNION BY NAME
SELECT * FROM '[[]North Braddock[]]_daily-avg.csv'
```

**Comment by Mytherin** [comment]
We could perhaps add a flag to the `read_csv_auto` and `read_parquet` functions, e.g. `read_csv_auto('*.csv', union_by_name=True)`. I would say that should be in a separate issue, though.

**Comment by domoritz** [comment]
> I would say that should be in a separate issue, though.

https://github.com/duckdb/duckdb/issues/4720
