### ISSUE TITLE
Add UNION BY NAME to CSV and Parquet import

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#4720]
As noted in https://github.com/duckdb/duckdb/issues/4699#issuecomment-1246816390, it would be great to have the option to union files with different (but compatible) columns. @Mytherin proposed `read_csv_auto('*.csv', union_by_name=True)`.

**Comment by danthegoodman1** [comment]
+1 on the Parquet support side!

**Comment by domoritz** [comment]
Is this done @Mytherin?

**Comment by Mytherin** [comment]
Yes this has been done for a while
