### ISSUE TITLE
Python register doesn't support schema

### ISSUE THREAD

**Issue by luke321321** [duckdb/duckdb#4723]
### What happens?

When registering a dataframe the schema isn't interpreted but the table is registered in the `temp` schema.  Instead I'd like to be able to register tables in any schema.

### To Reproduce

```python
import pandas as pd
import duckdb
con = duckdb.connect()
df = pd.DataFrame(range(10))

con.execute("create schema stage")
con.register("stage.test_table", df)
```

When I try to access the table I get the following error
```python
>>> con.execute('select * from stage.test_table').df()
Traceback (most recent call last):
     ...
    con.execute('select * from stage.test_table').df()
RuntimeError: Catalog Error: Table with name test_table does not exist!
Did you mean "pg_catalog.pg_tables"?
LINE 1: select * from stage.test_table
```

Inspecting the `information_schema` the table isn't saved in my `stage` schema but in the `temp` schema
```python
>>> con.execute("select * from information_schema.tables").df()[["table_schema", "table_name"]]
  table_schema        table_name
0         temp  stage.test_table
```

Accessing the table using quote identifiers works because of this but isn't the expected behaviour
```python
>>> con.execute('select * from "stage.test_table"').df()
....
```

If the table is created instead of registered as a view the it works as expected
```python
con.execute(f"create table stage.test_table as select * from test_table")
```

I've tried this on `master` (15/9/22) and the issue is still there

### OS:

MacOS

### DuckDB Version:

0.4.0

### DuckDB Client:

Python

### Full Name:

Luke Dyer

### Affiliation:

Peak AI

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
We don't currently support creating a view in a specific schema as far as I can see.
What we could do for now is add a schema layer to the temporary views we store in the connection object.

This way the object would still be stored in the temp schema, but when using the DuckDBPyConnection API that would be hidden from you, and querying 'a.view', 'b.view' would not result in the same view.

**Comment by lukedyer-peak** [comment]
Currently
```sql
select * from "stage.test_table"
```
does work (with schema=`temp` and table_name=`stage.test_table`) as this is equivalent to 
```sql
select * from temp."stage.test_table"
```

Just to help me understand, is this what you're suggesting to do (under the hood)?

**Comment by lukedyer-peak** [comment]
It looks from the `create view` [syntax in the docs](https://duckdb.org/docs/sql/statements/create_view) 'normal' views can be created for a specific schema.  I'm guessing this is a unusual view being created.

**Comment by Tishj** [comment]
> It looks from the `create view` [syntax in the docs](https://duckdb.org/docs/sql/statements/create_view) 'normal' views can be created for a specific schema. I'm guessing this is a unusual view being created.

Correct, I believe they fall under the temporary views
>  Temporary views exist in a special schema, so a schema name cannot be given when creating a temporary view.

**Comment by omo** [comment]
Kind of related to #1736, #1848, and #3980.
