### ISSUE TITLE
Add a set of metacolumns for parquet files when reading multiple objects

### ISSUE THREAD

**Issue by vgrimaldi848** [duckdb/duckdb#4739]
### What happens?

At the moment (0.5.0) is not possible to get the file name of the parquet file that contains the row you are looking at.

For example:

select *
from read_parquet('\path\to\files\*.parquet') a

won't return any column containing one of the following:
1. Filename (test.parquet)
2. Path (\path\to\file\)
3. Full path (\path\to\file\test.parquet))

This will be really useful when reading multiple files that are containing potential issues with data duplication.

### To Reproduce

For any parquet file just run:

select * from read_parquet('\path\to\files\*.parquet') a

there is no metacolumn avaialble.

### OS:

Windows

### DuckDB Version:

0.5.0

### DuckDB Client:

DBEaver

### Full Name:

Vincenzo Grimaldi

### Affiliation:

IKEA Supply AG

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by vgrimaldi848** [comment]
Hi, 

just realized there is the FILENAME option also working for Parquet even if not currently documented in:

https://duckdb.org/docs/data/parquet

Will be a nice to have indeed.

Regards

**Comment by Mytherin** [comment]
The `filename` option exists but indeed is apparently still missing from the documentation:

```sql
select * from read_parquet('test.parquet', filename=True) t(c) limit 1;
┌───────┬──────────────┐
│   c   │   filename   │
├───────┼──────────────┤
│ hello │ test.parquet │
└───────┴──────────────┘
```

**Comment by hannes** [comment]
This was added to the docs
