### ISSUE TITLE
Not so ambiguous reference to column name

### ISSUE THREAD

**Issue by fny** [duckdb/duckdb#4744]
### What happens?

This is more of a feature request than a bug report... but its something I find absolutely infuriating about all SQL engines I've ever worked with.

Say I have the following two tables:

```python
a = pd.DataFrame({
  'id': [1,2,3],
  'name': ['one', 'two', 'three']
})

b = pd.DataFrame({
  'id': [1, 2],
  'score': [1, 4]
})
```

I want to run the following stupidly simple query...

```sql
SELECT id, name, score
FROM a, b
WHERE a.id = b.id
```

...but it is guaranteed to blow up:

```
Binder Error: Ambiguous reference to column name "id" (use: "b.id" or "a.id")
```

In this case, it is absolutely unambiguous: either column satisfies the query. In other circumstances, I've been performing analysis where ahead of time I know the columns are exactly the same.

For example, for a certain project every table has the following four columns: partition_id > patient_id > encounter_id > case_id. I ever aggregate by any of these values, I know ahead of time there is no ambiguity, so it would be immensely convenient for the engine to return any of the corresponding columns. This could easily be resolved by introducing new syntax into the select statement. Here is a very rough sketch:

```
 select _any.id from a, b where a.id = b.id
 select _leftmost.id from a, b where a.id = b.id
```

`select _leftmost.id` could also be the default behavior while issuing an ambiguous query warning instead of an outright failure.

### To Reproduce

```
a = pd.DataFrame({
  'id': [1,2,3],
  'name': ['one', 'two', 'three']
})

b = pd.DataFrame({
  'id': [1, 2],
  'score': [1, 4]
})

duckdb.query("""
select id, name, score
from a, b
where a.id  b.id
""")
```

### OS:

Linux

### DuckDB Version:

0.5

### DuckDB Client:

python

### Full Name:

Faraz Yashar

### Affiliation:

Duke University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Wouldn't the `USING` clause resolve this ambiguity more elegantly?

For example:

```sql
SELECT id, name, score FROM a JOIN b USING (id)
--    id name  score
-- 0   1  one      1
-- 1   2  two      4
```

**Comment by orzom411** [comment]
I would differ from this request.  The referential check is appropriate and in many ways I'd humbly rather see all references properly addressed, e.g. it would make maintaining the code far less ambiguous.

Example, lax coding such as that offered assumes "name", "score", or some other field, has only one source.  Suppose the very common example where someone adds "name" to one of the other tables (data frames in this case) involved, well, the assumptive code breaks and management of the lazily authored consumes time to correct.  Now if the initial coder simply and properly aliased there authoring ambiguity, such as this, down stream steps would be addressed hence any future modifications wouldn't also have to visit the lazily authored code.

Simple defensive coding is an easy task, try not to imbed potholes by being lazy.  Bugs are often mitigated by the simplest techniques particularly when the framework provides means by which one can indeed prevent errors down the road.

**Comment by fny** [comment]
@orzom411 I appreciate your wisdom, but what exactly is being protected against when someone writes the following:

```
SELECT id, name, score
FROM a, b
WHERE a.id = b.id
```

**Comment by orzom411** [comment]
> @orzom411 I appreciate your wisdom, but what exactly is being protected against when someone writes the following:
> 
> ```
> SELECT id, name, score
> FROM a, b
> WHERE a.id = b.id
> ```

The flaw is in a, b.  There will always be less drama down the road if you state: 

``` SQL
SELECT a.id, a.name, b.score
FROM a as a, b as b
WHERE a.id = b.id
```

That way there is no ambiguity and when one redefines b to contain "name" or a to contain "score" the query many lines of code later doesn't break.  It simply keeps working... my humble goal in life is to avoid revisiting code... ;)
