### ISSUE TITLE
Unexpected behavior from `chunk_size` in pyarrow record batches

### ISSUE THREAD

**Issue by gforsyth** [duckdb/duckdb#4755]
### What happens?

Hi all!  As usual, DuckDB is awesome and thanks for all of the amazing work on it!

Using the Python client, there is a `fetch_record_batch` method on a query result that takes a `chunk_size` argument -- the default value is `1_000_000`, there are a few oddities here.

First, the behavior:
```python
In [1]: import duckdb

In [2]: con = duckdb.connect()

In [3]: con.execute("CALL dbgen(sf=0.5)")
Out[3]: <duckdb.DuckDBPyConnection at 0x7f91a8024530>

In [4]: batches = con.execute("SELECT * FROM lineitem").fetch_record_batch(chunk_size=1024)

In [5]: batches.read_next_batch().to_pandas().shape
Out[5]: (1024, 16)

In [6]: batches = con.execute("SELECT * FROM lineitem").fetch_record_batch(chunk_size=1025)

In [7]: batches.read_next_batch().to_pandas().shape
Out[7]: (2048, 16)

In [8]: batches = con.execute("SELECT * FROM partsupp").fetch_record_batch(chunk_size=1024)

In [9]: batches.read_next_batch().to_pandas().shape
Out[9]: (1024, 5)

In [10]: batches = con.execute("SELECT * FROM partsupp").fetch_record_batch(chunk_size=25)

In [11]: batches.read_next_batch().to_pandas().shape
Out[11]: (1024, 5)
```

First, to my reading, "chunk size" implies a chunk of bytes, so it's a bit unexpected that it seems to correspond to the number of rows returned (irrespective of number of columns) -- that's not a huge deal, but should be mentioned in the docstring.

Second, these row chunks can only be returned in multiples of 1024, which seems odd given that they are groups of rows and not a specific number of bytes (note also that the default value of `1_000_000` is technically invalid and returns 1000448 rows instead).

Given that the batches seem not to be grouped by data size but by row number, the restriction to multiples of 1024 seems unnecessary -- and maybe `batch_size` or `group_size` would be a better argument name?  

I'm happy to contribute improvements to the documentation, but wanted to nail down expected behavior here first (and to see if we can remove the 1024 row thing).

### To Reproduce

Reproducer above.

### OS:

Arch Linux

### DuckDB Version:

0.5.0

### DuckDB Client:

Python

### Full Name:

Gil Forsyth

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
The 1024 size comes from DuckDB's internal vector chunk length. I believe using a multiple of 1024 is likely to be fastest for that reason. Here is the original PR I believe in case it helps to explain it!
https://github.com/duckdb/duckdb/commit/b36732a57e5c956e5a2d08768e9139425dc2aff6

**Comment by Mause** [comment]
Definitely sounds like it would be worth adding those details to the docs or docstrings

**Comment by gforsyth** [comment]
Thanks all -- this makes a bunch of sense and obviously not worth kneecapping performance, but yeah, I think more information in the docstrings / docs.  
I'm thinking about parameter names and maybe something that indicates that the argument is going to impact the number of rows returned?  `rows_per_batch`, maybe?  And then with caveats in the docstring that it'll only be approximate since the output will be a multiple of 1024

**Comment by Mytherin** [comment]
Maybe call it `approx_rows_per_batch` for clarity then?
