### ISSUE TITLE
[Fuzzer] C/C++ API missing backslash interpretation

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4756]
### What happens?

In the C++ API run the following:

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("SELECT BLOB '\x27';");
```
It will give the error: Parser Error: unterminated quoted string at or near "'''::BLOB". 

If I do this on the shell or without query verification, the statement is successful. I think there's something in the C/C++ API.

### To Reproduce

Run the statements above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

C/C++ API

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
This seems to be related to the query verification, the `Blob -> ToString` conversion does not correctly round-trip with the parser.

**Comment by PedroTadim** [comment]
Here's another query with the same issue, but different syntax:
```
SELECT 1 FROM ((SELECT 2) t0(c0) JOIN (SELECT 3) t1(c0) ON TRUE), ((SELECT 4) t2(c0) JOIN ((SELECT 5) t3(c0) CROSS JOIN (SELECT 6) t4(c0)) ON TRUE);
```
Parser Error: syntax error at or near ","
LINE 1: ... t2(c0) INNER JOIN (SELECT 5) AS t3(c0), (SELECT 6) AS t4(c0) ON (CAST('t' AS ...

**Comment by PedroTadim** [comment]
And another one:
```
SELECT 1 WHERE (1 IS DISTINCT FROM 1) IS NULL;
```

**Comment by PedroTadim** [comment]
And one more :)
```
SELECT CAST('1' COLLATE "as" AS INT);
```
Parser Error: syntax error at or near "as"
LINE 1: SELECT CAST('1' COLLATE as AS INTEGER)

**Comment by PedroTadim** [comment]
More :)
```
UPDATE t0 SET c0 = (~1);
```
Parser Error: syntax error at or near "=~"
LINE 1: UPDATE t0 SET c0=~(1)

Let me check this issue.

**Comment by PedroTadim** [comment]
Again with the C-API and enable verification:
```
SELECT 1 WHERE "decode"('\xDD\x90\xD0\x80\x7F\x27,g\x27'::BLOB) <= ALL((SELECT 2) INTERSECT (SELECT 2) ORDER BY ALL);
```
Invalid Error: Parsed statement differs from original result!
Original Result:
1
INTEGER
[ Rows: 0]

Parsed:
Catalog Error: Type with name g does not exist!
Did you mean "long"?

**Comment by PedroTadim** [comment]
This issue continues on #4978
