### ISSUE TITLE
SendQuery/StreamQueryResult parallelization problem

### ISSUE THREAD

**Issue by jonerikr** [duckdb/duckdb#4762]
### What happens?

When using the C++ API for querying parquet files, there seems to be a problem with how the parallelization works when trying to utilize SendQuery/StreamQueryResult as opposed to MaterializedResult.

When doing a simple SELECT like so (returning about 600 records): 
SELECT * FROM read_parquet('/home/tmp/file.parquet') where field like '60116383%'
16 threads are being spun up, however all but one thread is idle, resulting in slow queries.

time build/example
real    1m12.531s
user    1m10.794s

Adding an ORDER BY or LIMIT clause seems to 'fix' it.
SELECT * FROM read_parquet('/home/tmp/file.parquet') where field like '60116383%' ORDER BY date
SELECT * FROM read_parquet('/home/tmp/file.parquet') where field like '60116383%' LIMIT 100000

time build/example
real    0m10.320s
user    2m20.252s

These two on the other hand are quite fast and perform about the same. They run on 16 threads with around 80% load per thread, and complete in the same amount of time regardless of whether order by or limit is used. It seems unaffected by what the actual value for limit is, just as long as it's there. 

The result appears to be the same whether querying one or multiple files. The data set contains some 40 columns, around 140 million records in a 5gb file. I can't share the parquet file itself, but I've verified the results to be the same for other files too, so any file should do.

DuckDB compiled from source, v0.5.0, v0.5.1 and latest with same result. Compiled with "make release"
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1

### To Reproduce

Modified code of examples/embedded-c++/main.cpp

```
#include "duckdb.hpp"
#include <iostream>

using namespace duckdb;

int main() {
        DuckDB db(nullptr);

        Connection con(db);
        auto result = con.SendQuery("SELECT * FROM read_parquet('/tmp/tmp.parquet') where field like '60116383%'");

        while(auto f = result->Fetch());
}
```
The above query is quite slow one

Replacing the query with one of the below one causes significant improvement in speed
auto result = con.SendQuery("SELECT * FROM read_parquet('/tmp/tmp.parquet') where field like '60116383%' limit 10000000");
auto result = con.SendQuery("SELECT * FROM read_parquet('/tmp/tmp.parquet') where field like '60116383%' order by date");

### OS:

CentOS 7

### DuckDB Version:

v0.5.1

### DuckDB Client:

C++ API

### Full Name:

Jon Erik Ramsland

### Affiliation:

Utel

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Stream query results do not execute the final pipeline in parallel as the final pipeline is handed over to the client to consume results from, so currently this is expected behavior. Solving this is possible but would require adding a cache to the final pipeline and adding support for resumable pipelines.

**Comment by jonerikr** [comment]
Seems there's something I don't quite get here then...
All of these queries return QueryResultType:STREAM_RESULT (i.e., I've tested on result->type and it's 1 in all cases)

1. auto result = con.SendQuery("SELECT * FROM read_parquet('/tmp/tmp.parquet') where field like '60116383%'");
2. auto result = con.SendQuery("SELECT * FROM read_parquet('/tmp/tmp.parquet') where field like '60116383%' order by date");
3. auto result = con.SendQuery("SELECT * FROM read_parquet('/tmp/tmp.parquet') where field like '60116383%' limit 100000");

The only difference between the them is #1 is plain, #2 has "order by", #3 has limit.
And #1 takes 8-10 times as long to execute as the two others.

It seems #1 in theory is a limit of infinity, or order by the default column.

**Comment by Mytherin** [comment]
That has to do with pipelines. In #1 the result streams directly to the client, whereas in #2 and #3 the limit and order by must first be resolved, which forces materialization. All pipelines except the last one are run in parallel when streaming results are used. In fact, the first query only has a single pipeline, so nothing is run in parallel when a streaming result is used.

**Comment by jonerikr** [comment]
Thanks, I guess that actually makes a lot of sense. 
Would the return from SendQuery be more accurate if it actually returned a MaterializedResult in the cases a materalization was forced? 

Would be awesome to have some sort of caching for actual stream results, because as it works today it's so slow, that I would assume in a lot of cases you'd be far better off querying for a "small" materialized dataset multiple times instead.
