### ISSUE TITLE
Inconsistent result in `LAST_VALUE` against window

### ISSUE THREAD

**Issue by hughcameron** [duckdb/duckdb#4764]
### What happens?

I've noticed different results to the query below in recent duckdb versions:
- in version 0.4 the query returns last value results as expected
- in version 0.5 the query encounters a `139` error
- in version 0.5.1 the query returns partial last value results, i.e. nulls are not entirely ignored

### To Reproduce

Here's a test query to create and window values.

```sql
WITH gen AS (
    SELECT *,
        random() AS rnd
    FROM generate_series(1, 10000) tbl(id)
),
lvl AS (
    SELECT id,
        rnd,
        CASE
            WHEN rnd <= 0.1 THEN 'shallow'
            WHEN rnd >= 0.9 THEN 'high'
        END AS water_level
    FROM gen
)
SELECT *,
    LAST_VALUE(water_level IGNORE NULLS) OVER (
        ORDER BY id
    ) AS grade
FROM lvl;
```

### OS:

macOS

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Hugh Cameron

### Affiliation:

Zitcha (Australia)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This crashes in debug.

**Comment by Mytherin** [comment]
Should be fixed by https://github.com/duckdb/duckdb/pull/4773
