### ISSUE TITLE
duckdb R API can't handle NA values in numeric columns

### ISSUE THREAD

**Issue by cjc77** [duckdb/duckdb#4768]
### What happens?

Loading in a dataframe with NA values present in a numeric column yields the following error:

`Error: Invalid Input Error: Could not convert string 'NA' to DOUBLE`

### To Reproduce

Load in csv/tsv file with NA values present in a column that otherwise contains only doubles.

### OS:

macOS Monterey

### DuckDB Version:

0.4.0

### DuckDB Client:

R

### Full Name:

Carson Cook

### Affiliation:

NWEA

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello! Could you provide a full example? How are you using both csvs and dataframes in this case?
Reading csvs directly has a parameter that allows you to specify a string that equates to Null (NULLSTR)
https://duckdb.org/docs/data/csv

**Comment by cjc77** [comment]
> Hello! Could you provide a full example? How are you using both csvs and dataframes in this case? Reading csvs directly has a parameter that allows you to specify a string that equates to Null (NULLSTR) https://duckdb.org/docs/data/csv

Thanks for your super speedy reply, @Alex-Monahan. I must have missed that parameter when I was reading the API. I tried calling `duckdb::duckdb_read_csv()` again with `na.string = "NA"` and the issue was resolved. Thanks for your suggestion!
