### ISSUE TITLE
[Fuzzer] Cardinality estimator assertion error

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4775]
### What happens?

The following statement:
```
SELECT 1 FROM (SELECT 2) t0, (SELECT 3) t1 WHERE INTERVAL '1' DAYS USING SAMPLE (1 ROWS) REPEATABLE (1);
```
Triggers: src/optimizer/cardinality_estimator.cpp:35: bool duckdb::CardinalityEstimator::SingleColumnFilter(duckdb::FilterInfo *): Assertion `filter_info->set->count >= 1' failed

It should succeed.

### To Reproduce

Run the statement above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by PedroTadim** [comment]
The assertion hit again today with a prepared statement:

```
PREPARE p0 AS SELECT 1 FROM (SELECT 2), range(1) WHERE $0 USING SAMPLE BERNOULLI (1 ROWS) LIMIT 1;
```

**Comment by Mytherin** [comment]
@Tmonster perhaps you can pick these up when you have time (no rush)

**Comment by PedroTadim** [comment]
This issue continues on https://github.com/duckdb/duckdb/issues/4978
