### ISSUE TITLE
Cursor garbage collection and RecordBatchReader in Python

### ISSUE THREAD

**Issue by gforsyth** [duckdb/duckdb#4782]
### What happens?

I ran into this when working on ibis-project/ibis#4454

If I run a query in the DuckDB python client and scope all instances of `cursor` to a single function, `cursor`, nevertheless survives garbage collection at function exit and so the contents of the `RecordBatchReader` are accessible.  But I'm not sure that there _should_ be a reference remaining (however convenient) and it might point to a memory leak?  I believe the code in question is here: https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyresult.cpp#L426-L437

Conversely, if I access the duckdb Python client _via_ `duckdb_engine`, the `duckdb_engine` cursor only has the single refcount (+ the additional refcount from calling `getrefcount`).  This is the behavior I expect, even though it is less convenient as a downstream user.

Aside from whether there is a memory leak and the extra reference is accidental, I'm not sure what the right thing to do here is.  Clearly memory leaks are bad (if there is one), but also returning a lazy iterator of `RecordBatches` but deleting the data that feeds into it seems problematic.

cc @Mause 

### To Reproduce

```
import sys

from sqlalchemy import create_engine


def duckdb_python():
    import duckdb

    con = duckdb.connect()
    con.execute("CALL dbgen(sf=0.01)")
    cursor = con.execute("SELECT * FROM lineitem LIMIT 10;")

    batchreader = cursor.fetch_record_batch()
    print(f"DuckDB Python cursor refcount: {sys.getrefcount(cursor)}")
    return batchreader


def duckdb_engine():
    con = create_engine("duckdb:///:memory:")
    con.execute("CALL dbgen(sf=0.01)")
    cursor = con.execute("SELECT * FROM lineitem LIMIT 10;")

    batchreader = cursor.cursor.c.fetch_record_batch()
    print(f"DuckDB Engine cursor refcount: {sys.getrefcount(cursor)}")
    return batchreader


def main():
    print(f"{'DuckDB Python':=^50}")
    batchreader = duckdb_python()
    print(batchreader.read_next_batch())  # Works
    print(f"{'DuckDB Engine':=^50}")
    batchreader = duckdb_engine()
    print(batchreader.read_next_batch())  # StopIteration


if __name__ == "__main__":
    main()
```

### OS:

Arch Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python / duckdb_engine

### Full Name:

Gil Forsyth

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I doubt that there's a memory leak but it could be that we keep a reference to the cursor in the Connection.
It might be worth investigating if this also happens when you create a new connection scoped to that single function as well.

**Comment by pdet** [comment]
Hi @gforsyth,

This is not Arrow or Python related, the thing is this query is a stream query, which currently holds a shared pointer to the database context, so the connection only dies when the result dies.

I'm not exactly sure why we have a `shared_ptr` and not a `weak_ptr` there, maybe @Mytherin has a particular reason for that?

I would expect this behavior to be the same on the `duckdb_engine`, since this does not happen on the python level. Not sure why it properly errors it out there.

Finally, the different values in the ref_count you see there is because `cursor = con.execute("SELECT * FROM lineitem LIMIT 10;")` returns the same connection. If you run 
```python
    con = duckdb.connect()
    print(f"DuckDB Python cursor refcount: {sys.getrefcount(con)}")
    con.execute("CALL dbgen(sf=0.01)")
    print(f"DuckDB Python cursor refcount: {sys.getrefcount(con)}")
    batchreader = con.execute("SELECT * FROM lineitem;").fetch_record_batch(1)
    print(f"DuckDB Python cursor refcount: {sys.getrefcount(con)}")
    return batchreader
```

The refcount doesn't change.
