### ISSUE TITLE
When using GDB attach DuckDB, input can not be performed

### ISSUE THREAD

**Issue by xianglli** [duckdb/duckdb#4784]
### What happens?

When using GDB attach DuckDB, input can not be performed.

### To Reproduce

build/debug/duckdb
(grep the process id for duckdb)
gdb -p (pid)

### OS:

OSX 10.16

### DuckDB Version:

master

### DuckDB Client:

cli

### Full Name:

Xiang Li

### Affiliation:

the Ohio State University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
I don't think that is an issue with DuckDB,  try directly launching perhaps, e.g. `lldb -- ./build/debug/duckdb ...`
