### ISSUE TITLE
LOAD httpfs crashes R

### ISSUE THREAD

**Issue by StevenHibble** [duckdb/duckdb#4792]
### What happens?

When loading the httpfs extension, the R process crashes. This does not happen with the CLI or Python. There is no message before the process crashes.

### To Reproduce

Using R.exe in the terminal or R Studio, these were my steps:

```
library(duckdb)

con <- dbConnect(duckdb())
dbSendStatement(con, "INSTALL httpfs;")
dbSendStatement(con, "LOAD httpfs;")
```

### OS:

Windows 10

### DuckDB Version:

0.5.0

### DuckDB Client:

R 4.2.1

### Full Name:

Steven Hibble

### Affiliation:

MarketCast

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jllipatz** [comment]
Hello, 

I have the same problem, running R too, but with any extension.

**Comment by IanGray22795** [comment]
I am running into the same issue The only message I have received is:The terminal process terminated with exit code: 3221225477.

**Comment by AjayKMehta** [comment]
I am experiencing the same problem.

**Comment by AjayKMehta** [comment]
Here is the code I ran in a brand-new R session:

``` r
library(duckdb)
#> Loading required package: DBI
con <- dbConnect(duckdb::duckdb(), dbdir = "D:/duckdb/test.duckdb", read_only = FALSE)
dbGetQuery(con, "SELECT * FROM duckdb_extensions() where installed = true")
#>   extension_name loaded installed
#> 1            fts  FALSE      TRUE
#> 2         httpfs  FALSE      TRUE
#> 3        parquet   TRUE      TRUE
#>                                                                           install_path
#> 1    C:\\Users\\Ajay\\.duckdb\\extensions\\v0.6.1\\windows_amd64\\fts.duckdb_extension
#> 2 C:\\Users\\Ajay\\.duckdb\\extensions\\v0.6.1\\windows_amd64\\httpfs.duckdb_extension
#> 3                                                                           (BUILT-IN)
#>                                                            description
#> 1                            Adds support for Full-Text Search Indexes
#> 2 Adds support for reading and writing files over a HTTP(S) connection
#> 3                   Adds support for reading and writing parquet files
#>           aliases
#> 1                
#> 2 http, https, s3
#> 3
```

<sup>Created on 2022-12-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If I now try to load FTS, it will crash my R session:

```r
dbExecute(con, "LOAD fts;")
```

**Comment by Mytherin** [comment]
This should be fixed in the latest release
