### ISSUE TITLE
"INSERT INTO" ignores pandas column names

### ISSUE THREAD

**Issue by ihopethiswillfi** [duckdb/duckdb#4793]
### What happens?

"INSERT INTO" seems to ignore pandas column names, and will silently insert wrong values into a table if the column order is different than the one of the existing table.  This leads to corrupted data in the table.

It seems that when inserting, there is no data validation going on.

### To Reproduce

```
import duckdb
import pandas as pd
import numpy as np

a = pd.DataFrame({'floats': np.random.random(5), 'ints': np.random.randint(0, 100, 5)})
b = pd.DataFrame({'floats': np.random.random(5), 'ints': np.random.randint(0, 100, 5)})

# make column order different
a = a[['ints', 'floats']]
b = b[['floats', 'ints']]

print(a)
print(b)

#    ints    floats
# 0    61  0.698122
# 1    69  0.262557
# 2     6  0.125759
# 3    27  0.253404
# 4    33  0.705026

#      floats  ints
# 0  0.796355    93
# 1  0.906573    11
# 2  0.154474     0
# 3  0.903768    56
# 4  0.568102    12

# ------

db_path = 'db.duckdb'
db_output_table = f'bugreport1'

con = duckdb.connect(db_path, read_only=False)
con.execute(f"CREATE TABLE {db_output_table} AS SELECT * FROM a")
con.execute(f"INSERT INTO {db_output_table} SELECT * FROM b")
```

When checking the table after these statements it looks like the below screenshot.
- Dataframe `b` has been inserted in the wrong columns.
- Note also that the `floats` from `b` have been converted to `int`.

![image](https://user-images.githubusercontent.com/17611570/192087763-ef9aa11b-045e-49d0-b6aa-25544540348a.png)

### OS:

linux mint 19.3

### DuckDB Version:

0.5.2.dev64

### DuckDB Client:

Python

### Full Name:

John Doe

### Affiliation:

Personal use

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by koenvo** [comment]
Are you sure this only happens with pandas dataframe or with all ‘insert into … select * from b’ ?

**Comment by Mytherin** [comment]
`INSERT INTO` inserts based on column position, not based on column names. That is how `INSERT INTO` functions as per the SQL standard and how it works in every database system. If you want to insert column names in a different order then you need to specify them yourself as part of the `INSERT INTO` clause:

```sql
D create table integers(a integer, b integer);
D insert into integers (b, a) select 42 b, 84 a;
D select * from integers;
┌────┬────┐
│ a  │ b  │
├────┼────┤
│ 84 │ 42 │
└────┴────┘
```

**Comment by davetapley** [comment]
For future people:

I just discovered you can workaround with [`BY NAME`](https://duckdb.org/docs/sql/statements/insert.html#insert-into--by-name)
(maybe that wasn't available when this issue was created?).

e.g.:

```py
con.execute(f"INSERT INTO {db_output_table} BY NAME SELECT * FROM b")
```
