### ISSUE TITLE
[Fuzzer] Returning clause with rowid internal error

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4805]
### What happens?

Run the statements:
```
CREATE TABLE t0 (c0 INT);
INSERT INTO t0 VALUES (1) RETURNING rowid c2;
```
Gives an internal error: Failed to bind column reference "c2" [9.1] (bindings: [9.0])

### To Reproduce

Run the statements above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
A smaller repro of this issue can be made by leaving off the aliasing as C2, returning `rowid` is the issue
Though the extra alias does make it obvious that a simple check for the "rowid" alias is not the fix.

In the context where the issue happens the only thing we know about the reference is the table_index and column_index

Maybe the bindings should always contain a `rowid`, but I'm not a fan of that fix, so I'll look higher up

**Comment by PedroTadim** [comment]
This issue continues on https://github.com/duckdb/duckdb/issues/4978
