### ISSUE TITLE
duckdb shell does not support `editing-mode vi`

### ISSUE THREAD

**Issue by markwaddle** [duckdb/duckdb#4811]
### What happens?

i'm not an expert in how `.inputrc` is processed, but with a line of `set editing-mode vi`, sqlite3 will use vim mode for editing. the duckdb shell, which appears to be based on the sqlite3 shell, does not appear to do the same. it appears to always use emacs mode.

### To Reproduce

* add `set editing-mode vi` to `~/.inputrc`
* start duckdb
* edit mode is emacs

### OS:

MacOS 12.6

### DuckDB Version:

0.5.1 7c111322d

### DuckDB Client:

shell

### Full Name:

Mark Waddle

### Affiliation:

Microsoft

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
At a guess, this is probably simply because we use `linenoise` instead of `readline`, so it simply isn't supported

See https://github.com/duckdb/duckdb/pull/393

**Comment by markwaddle** [comment]
that is unfortunate. that change negatively affects the usability of the shell.

**Comment by davetapley** [comment]
And there goes the last chance 😞 

- https://github.com/antirez/linenoise/pull/92#event-8367977184

**Comment by davetapley** [comment]
Here's the workaround I settled on:

1. Open e.g. `scratch.sql` in vim
2. in another terminal: `duckdb my.db < scratch.sql`

**Comment by Mytherin** [comment]
> And there goes the last chance 😞
> 
> * [vi bindings antirez/linenoise#92 (comment)](https://github.com/antirez/linenoise/pull/92#event-8367977184)

We have [our own fork of linenoise](https://github.com/duckdb/duckdb/blob/master/tools/shell/linenoise.cpp). Happy to review a PR if anyone wants to implement support for vi mode in our fork.

**Comment by bnm3k** [comment]
As a stopgap, would you consider adding an edit command similar to the `\e` for Postgres' psql: it creates a temporary file, then opens the configured editor with that file (could be vim, nano, vscode). Once closed, it runs the contents.

**Comment by joelostblom** [comment]
Although I can't find it in the docs, `\e` and `.edit` can be used to open the default editor, e.g. vim, to edit a command since https://github.com/duckdb/duckdb/pull/11447.
