### ISSUE TITLE
Nested dictionary in Arrow integration

### ISSUE THREAD

**Issue by changhiskhan** [duckdb/duckdb#4812]
### What happens?

I have a computer vision dataset where each row corresponds to an image. One of the columns a list of detected object labels (arrow type: list<dict<int, str>>). If I run a label distribution query on it, the output are the integer indices rather than the str values. This is different from duckdb's output if the dict column is not nested.

### To Reproduce

```python
import pyarrow as pa
import duckdb
import pandas as pd

values = pa.DictionaryArray.from_pandas(pd.Categorical(['dog', 'cat', 'horse'], categories=['cat', 'dog', 'horse']))
arr = pa.ListArray.from_arrays([0,1], values)
tbl = pa.Table.from_arrays([arr], names=["list_of_dict"])

duckdb.query("""\
SELECT label, COUNT(1) FROM (
    SELECT UNNEST(list_of_dict) as label FROM tbl
) GROUP BY 1
""").to_df()
```

Output:
```
Out[31]: 
   label  count(1)
0      1         1
```

### OS:

ubuntu 22.04

### DuckDB Version:

0.5

### DuckDB Client:

python

### Full Name:

Chang She

### Affiliation:

Lance project

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by changhiskhan** [comment]
If you create a non-nested dictionary column then it works as expected:

```
In [33]: tbl = pa.Table.from_arrays([values], names=["plain_dict"])

In [34]: tbl
Out[34]: 
pyarrow.Table
plain_dict: dictionary<values=string, indices=int8, ordered=0>
----
plain_dict: [  -- dictionary:
["cat","dog","horse"]  -- indices:
[1,0,2]]

In [35]: duckdb.query("""\
    ...: SELECT plain_dict, COUNT(1) FROM tbl GROUP BY 1
    ...: """).to_df()
Out[35]: 
  plain_dict  count(1)
0        dog         1
1        cat         1
2      horse         1
```

**Comment by changhiskhan** [comment]
The main impact of the problem is that you can't filter it using the string value

**Comment by matt-allan** [comment]
I just ran into this too. I am going to attempt to fix it. I _think_ the issue is the [check for dictionaries here](https://github.com/duckdb/duckdb/blob/e413e0b40dd788622f17d8223c4fea931bccd6cc/src/function/table/arrow.cpp#L207) does not get run when [recursing for nested types](https://github.com/duckdb/duckdb/blob/e413e0b40dd788622f17d8223c4fea931bccd6cc/src/function/table/arrow.cpp#L113)?

**Comment by Tishj** [comment]
This is still an issue
```
(lldb) p *schema.children[0]
(ArrowSchema) $4 = {
  format = 0x0000029220040380 "c"
  name = 0x0000029220040398 "item"
  metadata = 0x0000000000000000
  flags = 2
  n_children = 0
  children = nullptr
  dictionary = 0x00000292200403c8
  release = 0x0000000110bd0f90 (libarrow.1200.dylib`arrow::(anonymous namespace)::ReleaseExportedSchema(ArrowSchema*))
  private_data = 0x0000029220040380
```

This is what the schema of the child of the list looks like
we ignore the dictionary currently.
