### ISSUE TITLE
Performance problem when using arrow::to_duckdb() function

### ISSUE THREAD

**Issue by nareal** [duckdb/duckdb#4814]
### What happens?

Using DuckDB through the arrow function `to_duckdb()` degrades the performance significantly, when using a dataset of parquet files. 

The sample dataset consists of 251 parquet files (from about 65 to 75MB each), totalling about 2.5 billion rows.

A simple count can be about 40x slower than in arrow, or when using DuckDB through DBI or dplyr.

Other operations like aggregations are also slower, however the overhead is not as severe.

### To Reproduce

```r
library(tidyverse) # v 1.3.2
library(arrow) #v 9.0.0.1
library(duckdb) #v 0.5.1

ds <- open_dataset("sample_data/",
                   format = "parquet")
```

A simple count using arrow:
```r
system.time({
  ds |> 
    count() |> 
    collect()
})
```
user  system elapsed 
  0.498   0.102   0.267 

The same operation using `to_duckdb()`:
```r
system.time({
  ds |> 
    to_duckdb() |> 
    count() |> 
    collect()
})
```
   user  system elapsed 
  32.75   13.28   10.63 

When using DuckDB from DBI the results are as fast as expected:
```r
con <- dbConnect(duckdb::duckdb())

system.time({
  dbGetQuery(con,
             "SELECT COUNT(*) AS n FROM read_parquet('sample_data/*.parquet')")
})
```
  user  system elapsed 
  1.345   0.028   0.201 

There is no overhead when using the dbplyr interface:
```r
test_sample <- tbl(con, "read_parquet('sample_data/*.parquet')")

system.time({
  test_sample |> 
    count() |> 
    collect()
})
```
   user  system elapsed 
  1.399   0.014   0.197 

The problem seem to be the result of calling the function `duckdb::duckdb_register_arrow()`, that is used by `arrow::to_duckdb()`:
```r
table_name <- "test"
duckdb::duckdb_register_arrow(con, table_name, ds)
tbl <- dplyr::tbl(con, table_name)

system.time({
  tbl |> 
    count() |> 
    collect()
})
```
   user  system elapsed 
 33.739  13.200  10.757 

A similar overhead occurs when doing aggregations. It is faster to use the DBI or dbplyr interface:
```r
system.time({
  test_sample |> 
    count(rep_date) |> 
    collect()
})
```
   user  system elapsed 
 29.284   0.107   4.115 

than using the function `to_duckdb()`
```r
system.time({
  ds |> 
    to_duckdb() |> 
    count(rep_date) |> 
    collect()
})
```
   user  system elapsed 
 36.443   3.223   5.325 

```r
dbDisconnect(con)
```

The sample dataset can be re-created, to reproduce the problem, using the code below:
```r
library(purrr)
dir.create("sample_data")

create_sample_files <-
  function(date) {
    nobs <- round(rnorm(1, mean = 1e7, sd = 500000),
                  1)
    
    tibble(rep_date =
             rep(date,
                 nobs),
           t = runif(nobs)) |>
      write_parquet(sink =
                      paste0("sample_data/",
                             date, ".parquet"))
    
    gc()
  }

dates <- seq.Date(as.Date("2021-01-01"),
                  by = 1,
                  length.out = 251)

set.seed(2022)
walk(dates, create_sample_files)
```

### OS:

macOS 12.6 - Apple M1 (RAM: 16GB)

### DuckDB Version:

0.5.1

### DuckDB Client:

R

### Full Name:

Nelson Areal

### Affiliation:

University of Minho

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pankajp** [comment]
I don't have much experience with R, but is it possible that the arrow dataset to duckdb conversion reads the parquet files in memory to register it as a view in duckdb, whereas other query methods work off the parquet files directly?

**Comment by nareal** [comment]
The issue remains in the current versions of the packages: arrow (13.0.0) and duckdb (0.8.1-3).

**Comment by nareal** [comment]
The issue remains in the current versions of the packages: arrow (15.0.1) and duckdb (0.10.0).
