### ISSUE TITLE
Inconsistent results in DISTINCT queries

### ISSUE THREAD

**Issue by Rockbag** [duckdb/duckdb#4815]
### What happens?

Hello!

Unfortunately, we are running into a bit of a complex problem, because it's not something we can reproduce locally, but can reliably reproduce it in our cloud environment.

## Description

After upgrading to version `0.5.1`, we started seeing inconsistent results being returned by our queries that use `count(distinct {field})`. This issue is not present in `0.4.0` at all and is only affecting queries that use `count(distinct)` aggregations.

## Our setup

We have a distributed service with 8 instances, all of them running queries directly against parquet files in a multi-threaded manner. These are all read-only queries. The workload is running in AWS, the setup is basically the following:
 - ECS service with 8 nodes
 - Each node executes multiple requests in parallel (4 threads), sometimes against the same file residing in EFS
 - Each thread always instantiates a fresh in-memory `duckdb` process through `duckdb.connect()`
 - Avg requests per second is around 90 at the moment

I _think_ the issue was potentially introduced https://github.com/duckdb/duckdb/pull/4327/files (if this is considered an issue at all).

## What have we tried

Given the multi-layered facet of our service, we made sure to pinpoint the issue down to DuckDb. We debugged each layer within the application and ended up seeing the same queries returning different results. Following is an image of a debug log that demonstrates this:

<img width="1188" alt="same_query_diff_results" src="https://user-images.githubusercontent.com/11939634/192524651-57b37dd9-e6df-4d31-abf4-938a13ec1d9c.png">

### To Reproduce

Here's an example query that returns inconsistent results:

```
with fct_filter as ( 
  select  count(distinct  fct_table.customer_key) as customer_key 
  from  read_parquet('/opt/ocarina/411/ocarina__unload_fct_order_lineitem.parquet') as fct_table
  where  fct_table.order_timestamp between '2022-09-19 00:00:00+00:00' and '2022-09-19 00:00:00+00:00'  
  and fct_table.customer_order_number = (1))

select * from fct_filter
```

The file in question has `98138` items in it, so nothing major there.

I was trying to use the following snippet to approximate our cloud environment, but so far I have not been able to reproduce this on a single machine:

```
def _execute_query():
  conn = duckdb.connect()
  res =conn.execute(sql_query)
  return res.fetchall()

results = []
query_results = []

with ThreadPoolExecutor(8) as executor:
    for i in range(1000):
      query_results.append(executor.submit(_execute_query))

    for query_result in concurrent.futures.as_completed(query_results):
      results.append(query_result.result())
```

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Balint Biro

### Affiliation:

Conjura

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Thanks for the report, but could you maybe try to generate some data that demonstrates the issue? Its hard to look into this when it's not locally reproducible. CC @Tishj any idea?

**Comment by Rockbag** [comment]
Thanks, @hannes, I'll see what I can do - I understand it's extremely hard to investigate this without proper repro steps.

**Comment by Tishj** [comment]
It's definitely caused by my change, I'm pretty certain of that.
Only thing I can think of real quick is that this might be expected behavior without an order by.
Previously the result would get created in a single thread, and as a side-effect, the order would always be guaranteed, but with multiple threads the order is not guaranteed as one thread might be finished faster than another.

Could be that I'm way off on that, but have you tried putting an order by on these queries and seeing if the results are the same?

**Comment by Rockbag** [comment]
Just an update, I still haven't been able to reproduce this locally with my arbitrary test scripts running on a single machine. I'll keep trying to see what triggers the issue.
I also started to familiarize myself with the DuckDb code to try and suss out where things go awry.
