### ISSUE TITLE
[capi] How to register arrow data and query on it?

### ISSUE THREAD

**Issue by wangfenjin** [duckdb/duckdb#4826]
Hi, seems we don't have API to register arrow data as table, similar to the [python example](https://github.com/duckdb/duckdb/blob/0d13deb759dd993ce037d37d79cc419c725553cd/tools/pythonpkg/tests/fast/arrow/test_dataset.py#L73)

```python
       conn.register("pqdata",pqdata)
```

May I know do we have any plan on that? thanks.

related to https://github.com/wangfenjin/duckdb-rs/issues/79

**Comment by hannes** [comment]
Which API do you want to use? C++?

**Comment by wangfenjin** [comment]
C API, as titled, which we can bind in rust

**Comment by hannes** [comment]
Ah, I see the tag now. This is currently not supported but I heard @pdet is working on an extension that may allow it.

**Comment by kesavkolla** [comment]
Does extension API has register function?

**Comment by kesavkolla** [comment]
Do we have register API available to use from rust?

**Comment by dignifiedquire** [comment]
Any chance this could be reopened? Or is there a different way to achieve this with the `C` api now? I am trying to build a custom loader similar to httpfs, in Rust, and need to be able to register things to make it work.
