### ISSUE TITLE
More in-depth and step-by-step contributing guidelines

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#484]
Would be nice to have something like [Peloton's contributing guidelines](https://github.com/cmu-db/peloton/wiki/Coding-Guidelines) for newcomers, that include simple step by step instructions on how to run debug mode, how to add tests, how to run benchmarks, etc. We could post this on our Github wiki.

**Comment by pdet** [comment]
When you start it I can do a tut on how to use clion + ninja. Maybe we should also somehow integrate the tutorial we did for SBBD on the wiki?

**Comment by taniabogatsch** [comment]
I just found this issue and was wondering if I should get started on it? How up-to-date is this? 

I could do this as a small side thing. I took notes for myself the last two months, while getting started on contributing to DuckDB, so maybe these could be a good start.

**Comment by Alex-Monahan** [comment]
That would be great! I'm trying to get compilation working on my Windows desktop to document that as well. I think there may be a couple of places we can put this info!
