### ISSUE TITLE
Specify schema of a parquet during Parquet export

### ISSUE THREAD

**Issue by ntapsrigowri** [duckdb/duckdb#4840]
### What happens?

COPY (SELECT * FROM tbl) TO 'output.parquet' (FORMAT PARQUET); generated parquet file based on the table definition. 
Is there a way to specify the schema for the parquet file generated? 
Lets say the parquet file thus generated should be uploaded to some 3rd party tool which mandates the schema to be a specific type. For example, some fields are not nullable, some fields have to be of a specific datatype.

### To Reproduce

1. Create a table.
2. Generate parquet file based on the data in the table, COPY (SELECT * FROM tbl) TO 'output.parquet' (FORMAT PARQUET);
3. There is currently no clear way documented to specify the schema.

### OS:

mac

### DuckDB Version:

0.5.1

### DuckDB Client:

Nodejs

### Full Name:

SG

### Affiliation:

NTAP

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Absolutely, you can put any query you want in the `SELECT ` part of the copy, thereby controlling the schema of the generated Parquet file.

**Comment by ntapsrigowri** [comment]
Can you please help me with an example? I have tried using IFNULL and COALESCE function, but no luck

In the example below, i'd like to have uniqueId, file ,extension and owner as required fields.

import duckdb from 'duckdb';

const changesTable = 'CREATE TABLE IF NOT EXISTS changes(file VARCHAR, extension VARCHAR, owner BIGINT);'

await runQuery(changesTable);

const insertChanges = "COPY changes FROM 'changes.csv' (AUTO_DETECT TRUE);"
await runQuery(insertChanges);

const parquetFile = `COPY (SELECT ${Date.now()} as uniqueId, **COALESCE**(file,'') AS file, **COALESCE**(extension,'') AS extension, **COALESCE**(owner,0) AS owner FROM changes) TO 'changesschema.parquet' (FORMAT 'PARQUET');`
await runQuery(parquetFile);

const parquetFileSchema = "select * from parquet_schema('changesschema.parquet');"
await runQuery(parquetFileSchema);

async function runQuery(query) {
    const db = new duckdb.Database("changesDuck");
    const response = await new Promise(resolve => {
        db.all(query, (err, queryResponse) => {
            if (err) {
                console.log('Failed to run duck db query', query, err);
            }
            resolve(queryResponse);
        });

    });

    console.log("Query RESPONS", query, response);
}

Response:
Query RESPONS CREATE TABLE IF NOT EXISTS changes(file VARCHAR, extension VARCHAR, owner BIGINT); []
Query RESPONS COPY changes FROM 'changes.csv' (AUTO_DETECT TRUE); [ { Count: 3 } ]
Query RESPONS COPY (SELECT COALESCE(file,''), COALESCE(extension,''), COALESCE(owner,0) FROM changes) TO 'changesschema.parquet' (FORMAT 'PARQUET'); [ { Count: 12 } ]
Query RESPONS select * from parquet_schema('changesschema.parquet'); [
  {
    file_name: 'changesschema.parquet',
    name: 'duckdb_schema',
    type: 'BOOLEAN',
    type_length: '0',
    **repetition_type: 'REQUIRED',**
    num_children: 3,
    converted_type: 'UTF8',
    scale: 0,
    precision: 0,
    field_id: 0,
    logical_type: null
  },
  {
    file_name: 'changesschema.parquet',
    name: "COALESCE(file, '')",
    type: 'BYTE_ARRAY',
    type_length: '0',
    **repetition_type: 'OPTIONAL',**
    num_children: 0,
    converted_type: 'UTF8',
    scale: 0,
    precision: 0,
    field_id: 0,
    logical_type: null
  },
  {
    file_name: 'changesschema.parquet',
    name: `COALESCE("extension", '')`,
    type: 'BYTE_ARRAY',
    type_length: '0',
    **repetition_type: 'OPTIONAL',**
    num_children: 0,
    converted_type: 'UTF8',
    scale: 0,
    precision: 0,
    field_id: 0,
    logical_type: null
  },
  {
    file_name: 'changesschema.parquet',
    name: 'COALESCE("owner", 0)',
    type: 'INT64',
    type_length: '0',
    **repetition_type: 'OPTIONAL',**
    num_children: 0,
    converted_type: 'INT_64',
    scale: 0,
    precision: 0,
    field_id: 0,
    logical_type: null
  }
]
