### ISSUE TITLE
DuckDB create table errors out when column name is 'group'

### ISSUE THREAD

**Issue by ntapsrigowri** [duckdb/duckdb#4841]
### What happens?

Failed to run duck db query CREATE TABLE IF NOT EXISTS changes( group BIGINT); [Error: Parser Error: syntax error at or near "group"
LINE 1: CREATE TABLE IF NOT EXISTS changes( group BIGINT);
                                            ^] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR'
}

### To Reproduce

import duckdb from 'duckdb';
db.all("CREATE TABLE IF NOT EXISTS changes( group BIGINT);");

### OS:

mac

### DuckDB Version:

0.5.1

### DuckDB Client:

Nodejs

### Full Name:

SG

### Affiliation:

NTAP

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Try quoting the column name, e.g. `db.all('CREATE TABLE IF NOT EXISTS changes("group" BIGINT);');
