### ISSUE TITLE
JSON not working as expected using DataGrip and JDBC driver 0.5.1

### ISSUE THREAD

**Issue by francescomucio** [duckdb/duckdb#4842]
### What happens?

Testing how to extract information from JSON strings, I got some unexpected errors.

For more details, you can see [the discussion in the DuckDB Discord](https://discord.com/channels/909674491309850675/921073327009853451/1025148079533477908).

### To Reproduce

You can try with a query like this:

```sql
    with data as (select '{"key": "value"}' tags)
  select json_transform(tags, '{"key": "VARCHAR"}') t
    from data;
```
It returns to me `No enum constant org.duckdb.DuckDBColumnType.STRUCT(key VARCHAR)`.

I could make it work using:
```sql
    with data as (select '{"key": "value"}' tags)
  select json_transform(tags, '{"key": "VARCHAR"}')::VARCHAR t
    from data;
```
Which returns a string.

But not using:
```sql
    with data as (select '{"key": "value"}' tags)
  select json_transform(tags, '{"key": "VARCHAR"}')::JSON t
    from data;
```
Even after running
```
install 'json';
load 'json';
```

Additional information:
- This works:
```sql
    with data as (select '{"key": "value"}' tags)
  select tags ->>'key' t
    from data;
```
But this fails:
```sql
    with data as (select '{"key": "value"}' tags)
  select tags ->'key' t
    from data;
```
With error:
```<failed to load>
java.sql.SQLException: Unsupported type JSON
	at org.duckdb.DuckDBResultSetMetaData.type_to_int(DuckDBResultSetMetaData.java:125)
	at org.duckdb.DuckDBResultSetMetaData.getColumnType(DuckDBResultSetMetaData.java:133)
	in RemoteResultSetMetaDataImpl.getFixedColumnType(RemoteResultSetMetaDataImpl.java:105)
```

### OS:

iOS

### DuckDB Version:

0.5.1

### DuckDB Client:

JDBC - DataGrip

### Full Name:

Francesco Mucio

### Affiliation:

Picsart

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
As mentioned on Discord, the STRUCT error is expected for now, until the JDBC client supports "nested" types. The other issue you've raised, I've submitted a pr to fix it (and tested it in DataGrip this time too)

**Comment by francescomucio** [comment]
Thanks a lot :)
