### ISSUE TITLE
 Unsupported compression codec "GZIP". Supported options are [...], gzip or [...]

### ISSUE THREAD

**Issue by darked89** [duckdb/duckdb#4853]
### What happens?

Hello,

I bumped into a rather unexpected problem:
```
CREATE TABLE express AS SELECT *  FROM read_parquet('express_data_float32.gzip6.parquet') LIMIT 5;
Error: Invalid Error: Unsupported compression codec "GZIP". Supported options are uncompressed, gzip or snappy
```

version: 
system: Linux ```5.14.0-4mx-amd64 #1 SMP Debian 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux```

The parquet was created using Python polars:

```
df_trans.write_parquet("express_data_float32.gzip6.parquet", compression="gzip", compression_level=6)
```

and I can read it back in polars without problems:
```
import polars as pl
df = pl.read_parquet("express_data_float32.gzip6.parquet")
df
Out[3]: 
shape: (48803, 1981)
```

**EDIT**
Also works in R with arrow:
```
library(arrow)
df <- read_parquet("express_data_float32.gzip6.parquet")
```

I am sorry but I have not compiled the main branch from source to exclude that it has been fixed already. There is a chance that Polars is doing something unortodox. 

Many thanks for your help

Darek Kedra

### To Reproduce

```
CREATE TABLE express AS SELECT *  FROM read_parquet('express_data_float32.gzip6.parquet') LIMIT 5;
Error: Invalid Error: Unsupported compression codec "GZIP". Supported options are uncompressed, gzip or snappy
```

### OS:

Linux 

### DuckDB Version:

v0.5.1 7c111322d

### DuckDB Client:

CLI

### Full Name:

Darek Kedra

### Affiliation:

U.Salamanca

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you please complete the example so the issue is reproducible? To start, what is `df_trans`?

**Comment by darked89** [comment]
Hello,

sorry, I was traveling and wanted to report the issue ASAP.  The minimal example to reproduce:

* Polars:
```(python)
import polars as pl

df = pl.DataFrame( {"col_a": [1.11, 2.2, 3.3], "col_b": [6.0, 7.0, 8.0], "col_c": ["a", "b", "c"],  } )
df.write_parquet("test.gzip.parquet", compression="gzip")
print(pl.__version__)
#0.14.9
```

* DuckDB
```
./duckdb
v0.5.1 7c111322d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE express AS SELECT *  FROM read_parquet('test.gzip.parquet');
Error: Invalid Error: Unsupported compression codec "GZIP". Supported options are uncompressed, gzip or snappy
```

Upgrading to the latest Python Polars v0.14.16 did not fix it. 

DK
PS trans_df was just a regular polars dataframe after transposing rows and columns and fixing the column names.

**Comment by wisp3rwind** [comment]
I suspect (didn't tes) that polars writes v2 data pages, which didn't support all compression algorithms in duckdb 0.5.1 (the error message is inaccurate in that case). Should work with the current dev version (cf. https://github.com/duckdb/duckdb/pull/4628).

**Comment by darked89** [comment]
Hello,

re parquet format info used by Polars:

```
parquet-tools inspect test.gzip.parquet

############ file meta data ############
created_by: Arrow2 - Native Rust implementation of Arrow
num_columns: 3
num_rows: 3
num_row_groups: 1
format_version: 2.6
serialized_size: 588


############ Columns ############
col_a
col_b
col_c

############ Column(col_a) ############
name: col_a
path: col_a
max_definition_level: 1
max_repetition_level: 0
physical_type: DOUBLE
logical_type: None
converted_type (legacy): NONE
compression: GZIP (space_saved: -29%)

############ Column(col_b) ############
name: col_b
path: col_b
max_definition_level: 1
max_repetition_level: 0
physical_type: DOUBLE
logical_type: None
converted_type (legacy): NONE
compression: GZIP (space_saved: -17%)

############ Column(col_c) ############
name: col_c
path: col_c
max_definition_level: 1
max_repetition_level: 0
physical_type: BYTE_ARRAY
logical_type: String
converted_type (legacy): UTF8
compression: GZIP (space_saved: -41%)
``` 

Hope it helps,

DK

**Comment by hannes** [comment]
we have had issues with arrow-rs before

**Comment by wisp3rwind** [comment]
> Hello,
> 
> re parquet format info used by Polars:
> [...]
> DK

Unfortunately, parquet-tools doesn't print the required information (`format_version` is not the same as the data page version). I've had a look at a file generated using your polars example above. At least for the package versions that I had installed, that indeed ends up generating v2 data pages.

duckdb `master` should work. `polars.DataFrame.write_parquet(..., use_pyarrow=True)` is probably a workaround, too, since that has different defaults format written.

**Comment by Mytherin** [comment]
I can confirm this code snippet works for me on the latest pre-release (run `pip3 install duckdb --pre --upgrade` to install):


```py
import polars as pl
import duckdb
df = pl.DataFrame( {"col_a": [1.11, 2.2, 3.3], "col_b": [6.0, 7.0, 8.0], "col_c": ["a", "b", "c"],  } )
df.write_parquet("test.gzip.parquet", compression="gzip")
duckdb.query("select * from 'test.gzip.parquet'").df()
#    col_a  col_b col_c
# 0   1.11    6.0     a
# 1   2.20    7.0     b
# 2   3.30    8.0     c

```

Thanks @wisp3rwind, this seems to have been fixed.
