### ISSUE TITLE
Postgres scanner full push down when explain plan 

### ISSUE THREAD

**Issue by parisni** [duckdb/duckdb#4863]
### What happens?

Just read the blogpost https://duckdb.org/2022/09/30/postgres-scanner.html

### To Reproduce

What about first explain  the query plan and then decide to push down the whole query to pg based on 
a configurable query time estimation threshold; within the pg_scanner ?

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Parisnj

### Affiliation:

Notging

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
I don't think there is a bug here?
