### ISSUE TITLE
[Fuzzer] Unimplemented quantile aggregate

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4867]
### What happens?

Run the following statement:
```
SUMMARIZE VALUES (1.0),(6754950520);
```
Gives an internal error: Unimplemented quantile aggregate

### To Reproduce

Run the query above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Looks like INT128 is not implemented.
