### ISSUE TITLE
ODBC driver lacks support for LogicalTypeId::DECIMAL

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#4887]
### What happens?

When using ODBC to query a table that includes a field of type DECIMAL(), it returns a type value of 0 which is an invalid type and interpreted (at least by ADO) as `adEmpty`. Digging through the ODBC driver code, the method [FindRelatedSQLType()](https://github.com/duckdb/duckdb/blob/master/tools/odbc/api_info.cpp#L209) does not include the data type `LogicalTypeId::DECIMAL` and so returns `SQL_UNKNOWN_TYPE ` (==0). 

I added `LogicalTypeId::DECIMAL` like so (with a few lines for context): 

```
.
.
.
	case LogicalTypeId::INTERVAL:
		return SQL_INTERVAL;
	case LogicalTypeId::DECIMAL:
		return SQL_DOUBLE;
	default:
		return SQL_UNKNOWN_TYPE;
.
.
.
```

and now the query via ODBC of the table containing DECIMAL returns expected result. 

I'm not saying that this is a complete and tested solution...hopefully someone more familiar with the ODBC driver will be able to speak to that. 

### To Reproduce

I'm using the compiled and signed version of sqlite_scanner extension downloaded from the network (I can't currently figure out how to use locally compiled unsigned version with ODBC). DuckDB ODBC driver is locally compiled from master that is in sync with repository (v0.5.2-dev466 84b2449fa). I'm querying `sakila.db` contained in the sqlite_scanner repository. A simplified query that shows the issue is `select amount from payment limit 1;`. The datatype of amount is `DECIMAL(5,2)`.

I'm using a windows script file and ADO to execute the query via ODBC, but any ODBC application I think would illustrate the issue. The error is `DIAG [S1003] [Microsoft][ODBC Driver Manager] Program type out of range (0)`.

### OS:

windows 11

### DuckDB Version:

v0.5.2-dev466 84b2449fa

### DuckDB Client:

ODBC

### Full Name:

charlie

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by omo** [comment]
(Unsolicited triage) It seems this is fixed by #6875? @Mytherin
