### ISSUE TITLE
Empty ListOf<String> returned as struct dicts instead of lists

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#4889]
### What happens?

Some parquet files with columns having dtype `ListOf<String>` with empty elements will sometimes (depending on how the file was produced) get returned as dicts of structs instead of empty lists.

### To Reproduce

```python
import numpy as np, pandas as pd, pyarrow.parquet as pq, polars as pl, duckdb
import os, tempfile

nrows = 5
empty_col = np.empty(nrows, dtype="O")
for ix in range(nrows):
    empty_col[ix] = np.empty(0, dtype=str)
empty_col = pl.Series(pd.Series(empty_col)).cast(pl.List(pl.Utf8))
df = pl.DataFrame({"lst_col" : empty_col})
fname = os.path.join(tempfile.gettempdir(), "temp.parquet")
df.write_parquet(fname, compression="snappy")
duckdb.query(f"select * from read_parquet('{fname}')").to_df()
```
![ddb_struct1](https://user-images.githubusercontent.com/11860098/194100815-ebaeca2c-6502-49f3-9d11-19d9fdf475ee.png)

One can verify that the file actually contains `ListOf<String>` and not something else:
```python
pq.read_schema(fname)
```
![ddb_struct2](https://user-images.githubusercontent.com/11860098/194101067-d7c21f5d-1c3f-440b-8c9c-e608498982a0.png)

But somehow, if the file is saved differently (don't know what exactly changes even though the schema looks the same), it will return the elements correctly as empty lists:
```python
pq.write_table(df.to_arrow(), fname)
duckdb.query(f"select * from read_parquet('{fname}')").to_df()
```
![ddb_struct3](https://user-images.githubusercontent.com/11860098/194101350-c472b0ff-bc74-4d90-8358-28a23d3446d3.png)

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taniabogatsch** [comment]
I am closing this as it seems fixed. I tried to reproduce it in a Colab notebook, and the dataframe no longer contains dicts of structs.

<img width="738" alt="Screenshot 2023-08-24 at 10 23 36" src="https://github.com/duckdb/duckdb/assets/44262898/1ad3d396-d8b5-44df-8b7a-acaa09b96573">

<img width="598" alt="Screenshot 2023-08-24 at 10 23 42" src="https://github.com/duckdb/duckdb/assets/44262898/bee9cf79-f104-47d1-9933-1d1b261d7654">
