### ISSUE TITLE
Using .open disables unsigned mode for extensions

### ISSUE THREAD

**Issue by kouta-kun** [duckdb/duckdb#4894]
### What happens?

When a persistent database file is opened using '.open filename', unsigned mode is disabled and unsigned extensions can no longer be loaded.

### To Reproduce

Working:
```
kouta@DESKTOP-0LBAANB:~/duckdb-hexhammdist$ duckdb -unsigned
v0.5.1 7c111322d
Enter ".help" for usage hints.
D load 'build/release/extension/duckdb-hexhammdist/hexhammdist_extension.duckdb_extension';
D select hexhammdist('abc','def');
┌───────────────────────────┐
│ hexhammdist('abc', 'def') │
├───────────────────────────┤
│ 7                         │
└───────────────────────────┘
D
```
Not working:
```
kouta@DESKTOP-0LBAANB:~/duckdb-hexhammdist$ duckdb -unsigned
v0.5.1 7c111322d
Enter ".help" for usage hints.
D .open test.db
D load 'build/release/extension/duckdb-hexhammdist/hexhammdist_extension.duckdb_extension';
Error: IO Error: Extension "build/release/extension/duckdb-hexhammdist/hexhammdist_extension.duckdb_extension" could not be loaded because its signature is either missing or invalid and unsigned extensions are disabled by configuration (allow_unsigned_extensions)
D
```

### OS:

Ubuntu 20.04

### DuckDB Version:

0.5.1

### DuckDB Client:

Shell

### Full Name:

Salvador Pardiñas

### Affiliation:

Freelancing for Candybox

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by kouta-kun** [comment]
I think I found the culprit, the following code overwrites the command line options when the database is loaded:

https://github.com/duckdb/duckdb/blob/master/tools/shell/shell.c#L18329

It might be a good idea to not overwrite to 0 or at least mask for the expected arguments and not overwrite the other ones.

**Comment by Mytherin** [comment]
Fixed in https://github.com/duckdb/duckdb/pull/4895
