### ISSUE TITLE
DuckDB WASM takes 3 minutes for something that runs instantly on DuckDB

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#4896]
### What happens?

The query below is blazing on DuckDB but becomes unusable in on DuckDB WASM.  My guess is that it is using a memory allocator that is too expensive.

### To Reproduce

Run Locally or in shell.duckdb.org.

```
with lineitem as (
   select * from (
      select*, row_number() over () as id from 
    -- 'https://shell.duckdb.org/data/tpch/0_01/parquet/lineitem.parquet'
    'lineitem.parquet'
   )
)
select
  sum(l_quantity) as t, 
  (COALESCE((
        SELECT sum(a.val) as value
        FROM (
          SELECT UNNEST(list(distinct {key:id, val:l_quantity})) a
        )
      ),0)) as "nested_size",
from lineitem
```

### OS:

linux

### DuckDB Version:

current

### DuckDB Client:

duckdb wasm

### Full Name:

lloyd tabb

### Affiliation:

google

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This appears to be caused by the WASM client being based on an older version of DuckDB, as the issue appears to be very similar to #3593. Similarly running the queries from that issue in the WASM shell results in very slow non-linear behavior, as was the case prior to the issue being fixed.

**Comment by Mytherin** [comment]
The latest version is also published [on npm now](https://www.npmjs.com/package/@duckdb/duckdb-wasm).

**Comment by lloydtabb** [comment]
You so totally rock.  Thank you!
