### ISSUE TITLE
Python `Decimal` value in pandas `DataFrame` cannot be casted under specific condition

### ISSUE THREAD

**Issue by papparapa** [duckdb/duckdb#4897]
### What happens?

In the following, `Decimal` refers to Python's Decimal class and `DECIMAL` refers to DuckDB's DECIMAL data type.

When a larger precision `Decimal` (`10` in the following example) appeares after smaller precision `Decimal`s (`1`s in the following example) in `DataFrame`, larger precision `Decimal` cannot be casted and SQL on `DataFrame` fails.
It seems duckdb prepares smaller precision `DECIMAL` for casting.

```
Traceback (most recent call last):
  File "/workspaces/DuckDB/duckdb-decimal-test.py", line 18, in <module>
    ).fetch_df()
duckdb.InvalidInputException: Invalid Input Error: Failed to cast value: Casting value "10" to type DECIMAL(1,0) failed: value is out of range!
```

As far as I tested, ~~`None` needs to be somewhere before the larger precision `Decimal` and~~ `DataFrame`'s length needs to be more than 2001 to reproduce this error.

### To Reproduce

Python is 3.10.7, pandas is 1.5.0 and duckdb is 0.5.1 or 0.5.2.dev492.
```Python
from decimal import Decimal
import pandas as pd
import duckdb

df = pd.DataFrame(
    [
        [Decimal(1)] for _ in range(2001)
    ] + [
        [Decimal(10)],
    ]
)

con = duckdb.connect()
con.execute(
    '''
        select * from df
    '''
).fetch_df()
```

### OS:

Debian 11 on WSL2 of Windows 11 Home

### DuckDB Version:

0.5.1 and 0.5.2.dev492

### DuckDB Client:

Python

### Full Name:

Koki Ueha

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Good chance this is related to the `pandas_analyze_sample` config option.
~~It's described here:~~
I thought I added it to the docs, but it seems I messed something up there, so I've made a new PR adding it to the proper place now.

Essentially when importing object columns from pandas, we go through an analyze step to figure out which type the column should have in duckdb, and for that we take a sample of the column.

If this sample is too small / misses an object that should change the type of the column, an error like this one is thrown.

We expose a way to increase/change the size of this sample through the `pandas_analyze_sample`  config option.

**Comment by papparapa** [comment]
Adding
```Python
con.execute('set global pandas_analyze_sample=10000')
```
worked well.
Thanks!

**Comment by drpeterallan** [comment]
Is it possible upon creation of the table from a df to set con.execute('set global pandas_analyze_sample=0') and explicity cast the types when you create a table? I'm having this issue and setting pandas_analyze_sample to a large number causing performance issues for me

**Comment by robmcd** [comment]
> Is it possible upon creation of the table from a df to set con.execute('set global pandas_analyze_sample=0') and explicity cast the types when you create a table? I'm having this issue and setting pandas_analyze_sample to a large number causing performance issues for me

You could make sure your dataframe doesn't have any columns of "object" type. The docs here mention that it's only object type columns that depend on sample analysis: https://duckdb.org/docs/api/python/data_ingestion.html
