### ISSUE TITLE
Python 3.11 wheels

### ISSUE THREAD

**Issue by edgarrmondragon** [duckdb/duckdb#4898]
Python 3.11 will be [released in the coming weeks](https://peps.python.org/pep-0664/), but duckdb doesn't currently publish wheels for it. It would be nice to test duckdb on Python 3.11, and also have binary wheels to start testing other projects that depend on it without needing to build from source.

I see you're using `cibuildwheel`, so I think it'd be relatively easy to implement this. I can start a PR if there's interest 🙂.

**Comment by Mause** [comment]
By all means go ahead! Should be fairly straightforward
