### ISSUE TITLE
Segfault on reading parquet file

### ISSUE THREAD

**Issue by exyi** [duckdb/duckdb#4903]
### What happens?

I read a parquet file I created using parquet-dotnet and DuckDB segfaults

```
D select * from 'symbol_signature.parquet' limit 10 ;
fish: Job 1, 'duckdb' terminated by signal SIGSEGV (Address boundary error)
```

Maybe the file is somehow invalid, but I guess it shouldn't segfault anyway. [pqrs](https://github.com/manojkarthick/pqrs) opens the file just fine. It only fails about 50% of the time.

### To Reproduce

[symbol_signature.parquet.gz](https://github.com/duckdb/duckdb/files/9728412/symbol_signature.parquet.gz) (gzipped because github does not like parquet. Contains only 2 rows, 5KB uncompressed. For some reason, it doesn't crash with only one of the rows)

```
exyi@NaN ...> duckdb
D select * from 'symbol_signature.parquet' limit 10 ;
fish: Job 1, 'duckdb' terminated by signal SIGSEGV (Address boundary error)
```

### OS:

Arch Linux | 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux

### DuckDB Version:

v0.5.1 7c111322de

### DuckDB Client:

CLI

### Full Name:

Stanislav Lukeš

### Affiliation:

Definitely no oracle

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Indeed that's a bug, it triggers an internal assert 
`INTERNAL Error: Assertion triggered in file "/Users/hannes/source/duckdb/src/common/types/vector.cpp" on line 1193: le.offset + le.length <= child_size`

**Comment by hannes** [comment]
The file is definitely corrupted, pyarrow says `pyarrow.lib.ArrowInvalid: Length spanned by list offsets (1) larger than values array (length 0)`
