### ISSUE TITLE
Kudos to DuckDB for streamlining our genomics efforts (Why_DuckDB outlink request)

### ISSUE THREAD

**Issue by catlyst** [duckdb/duckdb#4908]
Greetings DuckDB team -- I'd just like to convey our deepest appreciation for your brilliant package which I only discovered less than a month ago while seeking to convert our bioinformatics app [StabilitySort](http://stabilitysort.org/) to be usable without requiring a live DB server. We had been using ClickHouse which was fast enough, but unsuited to massive parallel jobs on our supercomputing cluster (Australia's NCI gadi).

DuckDB blew our socks off, because we were willing to settle for slow SQLite-like performance figures, but it ended up being even better than ClickHouse and didn't have any locking/scaling issues, so we just made the switch on our project's [gitlab](https://gitlab.com/baaron/StabilitySort) (committed today), and I thought it would be nice to let the [community](https://duckdb.org/why_duckdb) know that DuckDB is helping efforts in discovering potential disease-causing variants in human genomes.

Kudos & have an awesome weekend, team!

**Comment by hannes** [comment]
Thanks, great to hear its working out well for you! For the link, can you send a PR to the `duckdb-web` repo please?

**Comment by omo** [comment]
(Unsolicited triage) Sounds like this can be closed, as a link was added? @hannes

**Comment by hannes** [comment]
Indeed thanks
