### ISSUE TITLE
NOW should return TIMESTAMPTZ

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#4912]
On a related note, would it perhaps also make sense for `NOW` to return a `TIMESTAMPTZ`?

_Originally posted by @Mytherin in https://github.com/duckdb/duckdb/pull/4904#pullrequestreview-1133680073_

**Comment by hawkfish** [comment]
This is what the SQL spec ([and Postgres](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE)) do.

**Comment by hawkfish** [comment]
Also adding some other missing aliases.

**Comment by hawkfish** [comment]
Feature quote:

> I never look back darling, it distracts from the Now.
> -- Enda Mole, _The Incredibles_

**Comment by Mytherin** [comment]
Implemented now
