### ISSUE TITLE
Can not set allow_unsigned_extensions in Python API

### ISSUE THREAD

**Issue by eddyxu** [duckdb/duckdb#4913]
### What happens?

Attempt loading an unsigned extension from Python `duckdb` SDK.

### To Reproduce

Using python duckdb SDK (0.5.1)

```python
>>> import duckdb
>>> db = duckdb.connect()
>>> db.install_extension("/opt/lance.duckdb_extension", force_install=True)
>>> db.load_extension("lance")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.IOException: IO Error: Extension "/root/.duckdb/extensions/v0.5.1/linux_amd64_gcc4/lance.duckdb_extension" could not be loaded because its signature is either missing or invalid and unsigned extensions are disabled by configuration (allow_unsigned_extensions)
```

```python
>>> duckdb.query("PRAGMA allow_unsigned_extensions=TRUE;")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: Cannot change allow_unsigned_extensions setting while database is running
>>> duckdb.query("SET allow_unsigned_extensions=TRUE;")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: Cannot change allow_unsigned_extensions setting while database is running
```

### OS:

Ubuntu 

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Lei Xu

### Affiliation:

Eto Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
`allow_unsigned_extensions` must be set when launching the database connection:

```py
con = duckdb.connect(":memory:", config={"allow_unsigned_extensions": True})
con.execute('...')
```

It indeed cannot be used with the default database (which is used when running `duckdb.query`) as that is created outside of the users' direct control. We could perhaps extend the interface there to allow the flag to be set in the default connection (as long as it is set prior to running any queries).

**Comment by eddyxu** [comment]
That makes sense @Mytherin . 

Would appreciate having such example on the website/doc. I will close this issue then.

**Comment by wonb168** [comment]
> `allow_unsigned_extensions` must be set when launching the database connection:
> 
> ```python
> con = duckdb.connect(":memory:", config={"allow_unsigned_extensions": True})
> con.execute('...')
> ```
> 
> It indeed cannot be used with the default database (which is used when running `duckdb.query`) as that is created outside of the users' direct control. We could perhaps extend the interface there to allow the flag to be set in the default connection (as long as it is set prior to running any queries).

I tried this way, but got an error:
>>> import duckdb as dd
>>> con = dd.connect(":memory:", config={"allow_unsigned_extensions": True})
>>> con.execute("LOAD postgres_scanner;")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.IOException: IO Error: Extension "/root/.duckdb/extensions/v0.5.1/linux_amd64_gcc4/postgres_scanner.duckdb_extension" could not be loaded: /root/.duckdb/extensions/v0.5.1/linux_amd64_gcc4/postgres_scanner.duckdb_extension: undefined symbol: _ZTIN6duckdb9ExceptionE
>>>

**Comment by Mause** [comment]
@wonb168 at a guess, you're trying to use a build of the postgres scanner that was compiled against a difference duckdb version. Though further discussion should probably happen over in the postgres scanner repo: https://github.com/duckdblabs/postgres_scanner

**Comment by wonb168** [comment]
> @wonb168 at a guess, you're trying to use a build of the postgres scanner that was compiled against a difference duckdb version. Though further discussion should probably happen over in the postgres scanner repo: https://github.com/duckdblabs/postgres_scanner

Yes，I edit the code from v0.5.2，but I don't know how to build 0.5.2's pip package,
and I used 0.5.1 pip package , but replaced the postgres_scanner.duckdb_extension ,
then how to resolve it? thanks!

**Comment by wonb168** [comment]
and I change to v0.5.2, also this error:
```
>>> import duckdb as dd
>>> con = dd.connect(":memory:", config={"allow_unsigned_extensions": True})
>>> con.install_extension("/home/etl_yuege_prod/postgres_scanner.duckdb_extension", force_install=True)
>>> con.load_extension("postgres_scanner")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.IOException: IO Error: Extension "/home/etl_yuege_prod/.duckdb/extensions/596c5fe1e/linux_amd64_gcc4/postgres_scanner.duckdb_extension" could not be loaded: /home/etl_yuege_prod/.duckdb/extensions/596c5fe1e/linux_amd64_gcc4/postgres_scanner.duckdb_extension: undefined symbol: _ZTIN6duckdb9ExceptionE
>>> dd.__version__
'0.5.2-dev1149'
>>>
```

**Comment by Mause** [comment]
> and I change to v0.5.2, also this error:
> 
> ```
> >>> import duckdb as dd
> >>> con = dd.connect(":memory:", config={"allow_unsigned_extensions": True})
> >>> con.install_extension("/home/etl_yuege_prod/postgres_scanner.duckdb_extension", force_install=True)
> >>> con.load_extension("postgres_scanner")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> duckdb.IOException: IO Error: Extension "/home/etl_yuege_prod/.duckdb/extensions/596c5fe1e/linux_amd64_gcc4/postgres_scanner.duckdb_extension" could not be loaded: /home/etl_yuege_prod/.duckdb/extensions/596c5fe1e/linux_amd64_gcc4/postgres_scanner.duckdb_extension: undefined symbol: _ZTIN6duckdb9ExceptionE
> >>> dd.__version__
> '0.5.2-dev1203'
> >>>
> ```

As you're on linux, you'll need the `EXTENSION_STATIC_BUILD` option - https://github.com/duckdb/duckdb/blob/9913e0e80bba57ece3ad4275798d134d2bfef0aa/CMakeLists.txt#L246-L248

**Comment by wonb168** [comment]
I checked my git, [duckdb/CMakeLists.txt] have these rows 246-248, need change FALSE to TRUE?

**Comment by Mause** [comment]
> I checked my git, [duckdb/CMakeLists.txt] have these rows 246-248, need change FALSE to TRUE?

Generally speaking you set them externally via an environment variable or `-DEXTENSION_STATIC_BUILD=1` parameter to CMake

**Comment by wonb168** [comment]
> EXTENSION_STATIC_BUILD

if I `BUILD_PYTHON=1 EXTENSION_STATIC_BUILD=1 make debug`, error:
```
gmake[2]: Leaving directory '/root/postgres_scanner/build/debug'
gmake[1]: *** [Makefile:130: all] Error 2
gmake[1]: Leaving directory '/root/postgres_scanner/build/debug'
make: *** [Makefile:23: debug] Error 2
```

**Comment by wonb168** [comment]
> > I checked my git, [duckdb/CMakeLists.txt] have these rows 246-248, need change FALSE to TRUE?
> 
> Generally speaking you set them externally via an environment variable or `-DEXTENSION_STATIC_BUILD=1` parameter to CMake

if I BUILD_PYTHON=1 EXTENSION_STATIC_BUILD=1 make debug, error:

gmake[2]: Leaving directory '/root/postgres_scanner/build/debug'
gmake[1]: *** [Makefile:130: all] Error 2
gmake[1]: Leaving directory '/root/postgres_scanner/build/debug'
make: *** [Makefile:23: debug] Error 2
