### ISSUE TITLE
Show HTTPFS error message in addition to http code

### ISSUE THREAD

**Issue by chrisbrain** [duckdb/duckdb#4925]
Would it be possible for duckdb to show the error message (maybe truncated to a certain number of characters) if there is an issue?

For example for the following:

```
create view v1 as select * from 'http://myserver/data.parquet';
```

If my server returns code 512 and a more helpful message in the body of the response I only see the 512.

```
Error: Invalid Error: Unable to connect to URL "http://myserver/data.parquet": 512 (status code 512)
```

**Comment by Mause** [comment]
> Would it be possible for duckdb to show the error message (maybe truncated to a certain number of characters) if there is an issue?
> 
> For example for the following:
> 
> ```
> create view v1 as select * from 'http://myserver/data.parquet';
> ```
> 
> If my server returns code 512 and a more helpful message in the body of the response I only see the 512.
> 
> ```
> Error: Invalid Error: Unable to connect to URL "http://myserver/data.parquet": 512 (status code 512)
> ```

Which duckdb binding are you using? It would probably be fairly easy to include the error body in the description itself

**Comment by chrisbrain** [comment]
This was actually for the duck CLI @Mause.

But I would be interested in the Node.js bindings (and also interested in using duckdb in golang).

**Comment by chrisbrain** [comment]
FWIW this could also help with issues like this I think:
https://github.com/duckdb/duckdb/issues/5310

As if there's a problem s3 seems to return a fairly helpful XML report on why it's not happy.

**Comment by jeffling** [comment]
Ran into an issue where I put in a slightly malformed region and just got a 400 (Bad Request). Drove me crazy!

**Comment by Tishj** [comment]
@Mause I think you fixed this at some point, right?
Can this be closed?

**Comment by Mause** [comment]
> @Mause I think you fixed this at some point, right?
> Can this be closed?


I thought I had yeah, but I looked closer the other day while I was looking at the scaleway (s3 implementation) and I'm not sure the body in the http exception is being correctly populated in all circumstances. Perhaps that should be a new issue though
