### ISSUE TITLE
Positive User Feedback

### ISSUE THREAD

**Issue by antoinecarme** [duckdb/duckdb#4931]
### What happens?

Hi all,

First of all, I want to thank you a lot for this project.

In my dev tasks, I use a lot of Jupyter notebooks in which I play with in-memory SQLite databases for prototyping purposes. Duckdb does the same with the power of a high-level PostgreSQL database.

I am currently playing with duckdb (in python, through the excellent sqlalchemy and duckdb_engine) for deploying machine learning models inside databases. A lot of my tests are ok and the database shows an acceptance level similar to PostgreSQL, oracle or mssql.

You can see some examples here for some classification/regression models for duckdb, PostgreSQL, and SQLite:

https://github.com/antoinecarme/sklearn2sql-demo/tree/master/DuckDB_Support_2022-10-08

I have had some issues, need some time to analyze these. Will create separate issues later. Nothing critical nor blocking for the moment.

Again, thanks a lot guys for the good work.

Antoine

PS: I know, this is not really an issue, but good things, when they happen, need to be mentioned. SQLite is good, but is no longer alone in the developer toolkit.

### To Reproduce

Use duckdb !!!!

### OS:

Debian GNU Linux

### DuckDB Version:

'0.5.1', '7c111322d'

### DuckDB Client:

Python

### Full Name:

Antoine CARME

### Affiliation:

AC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Thanks, glad to hear DuckDB is working for you and we appreciate positive feedback on this channel. Looking at issues 24/7 can sometimes give a skewed view on things :)
