### ISSUE TITLE
Segmentation fault with select-from-where on a small database

### ISSUE THREAD

**Issue by amakelov** [duckdb/duckdb#4935]
### What happens?

Running the following with the Python client results in a segfault:
```python
import duckdb
con = duckdb.connect(database=':memory:')
query = """
CREATE TABLE t1(a int);
CREATE TABLE t2(x int, y int, z int, w int);

SELECT v1.a, v2.a, v3.a, v4.a, v5.a, v6.a, v7.a, v8.a
FROM t1 AS v1, t1 AS v2, t1 AS v3, t1 AS v4, t1 AS v5, t1 AS v6, t1 AS v7, t1 AS v8,
     t2 AS f1, t2 as f2
WHERE
f1.x = v1.a AND f1.y = v3 AND f1.z = v4 AND f1.w = v5 AND
f2.x = v2.a AND f2.y = v6 AND f2.z = v7 AND f2.w = v8;
"""
con.execute(query)
```
I believe this is a fairly minimal example of the problem. In particular, the analogous query where `t2` has only 2 or 3 columns works fine. 

### To Reproduce

```sql
CREATE TABLE t1(a int);
CREATE TABLE t2(x int, y int, z int, w int);

SELECT v1.a, v2.a, v3.a, v4.a, v5.a, v6.a, v7.a, v8.a
FROM t1 AS v1, t1 AS v2, t1 AS v3, t1 AS v4, t1 AS v5, t1 AS v6, t1 AS v7, t1 AS v8,
     t2 AS f1, t2 as f2
WHERE
f1.x = v1.a AND f1.y = v3 AND f1.z = v4 AND f1.w = v5 AND
f2.x = v2.a AND f2.y = v6 AND f2.z = v7 AND f2.w = v8;
```

### OS:

Ubuntu

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Aleksandar Makelov

### Affiliation:

MIT

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This seems to be an issue with the join order optimizer. I have pushed a work-around in #4940 that turns this into an internal exception for now.

@Tmonster could you pick this up after you are back from holiday?

**Comment by Tmonster** [comment]
Spent some time on it today.

I see already that there are entries in the DP table that don't store pointer references that describe the join plan. This shouldn't happen. I thought it might be because the query has equality conditions between a column and a table alias, which wasn't in the initial testing, but that wasn't the case. 

I'll keep digging and provide another update tomorrow

**Comment by Mytherin** [comment]
This has been fixed for a while
