### ISSUE TITLE
SQL UPDATE with JOIN, documentation?

### ISSUE THREAD

**Issue by jllipatz** [duckdb/duckdb#4939]
Hello,

First of all : Duckdb is really great!

Il read in one your papers that duckdb was optimized for massive updates. This is really a need because most of our work is to alter  the coding of columns in our input files. About UPDATE with JOIN I guessed on PostgreSQL syntax and found that the following syntax seems to work, but it is not documented. 
Is it a bit of the magic of duckdb?

`UPDATE t 
  SET REG_CODE=REGION
  FROM dep2017
  WHERE DEP_CODE=DEP`

I am trying to replace REG_CODE with the value REGION coming from another table, obtained from a join over DEP_CODE. DEP and REGION are in dep2017, DEP_CODE and REG_CODE are in t.

Best regards

JL.LIPATZ
Institut National de la Statistique et des Etudes Economiques - FRANCE

**Comment by Mytherin** [comment]
Thanks for the report! Could you file this issue on [the documentation repo](https://github.com/duckdb/duckdb-web/issues) instead?

**Comment by omo** [comment]
(Unsolicited triage) Copied this to https://github.com/duckdb/duckdb-web/issues/746, let's close. @Mytherin
