### ISSUE TITLE
[Fuzzer] Ordered aggregate with "regular" aggregate

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4942]
### What happens?

The following query:
```
SELECT percentile_disc(sum(1)) WITHIN GROUP (ORDER BY 1 DESC);
```
Gives the assertion error: src/planner/binder/expression/bind_aggregate_expression.cpp:19: void duckdb::InvertPercentileFractions(unique_ptr<duckdb::ParsedExpression> &): Assertion `fractions->expression_class == ExpressionClass::BOUND_EXPRESSION' failed

I think the nested aggregates error message is missing.

### To Reproduce

Run the statement above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This is what PG does too:

```sql
hawkfish=# SELECT percentile_disc(sum(1)) WITHIN GROUP (ORDER BY 1 DESC);
ERROR:  aggregate function calls cannot be nested
LINE 1: SELECT percentile_disc(sum(1)) WITHIN GROUP (ORDER BY 1 DESC...
                               ^
```
