### ISSUE TITLE
[Fuzzer] Group query verification error

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#4952]
### What happens?

In the C-API run

```
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();
con.SendQuery("SELECT DISTINCT 1 c0 GROUP BY CUBE (1), c0;");
```

It will report a row count mismatch between the parsed statement and the original result.

### To Reproduce

Run the statement above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

C/C++ API

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
my test on CLI
```
v0.5.1 7c111322d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT DISTINCT 1 c0 GROUP BY CUBE (1), c0;
┌────┐
│ c0 │
├────┤
│    │
│ 1  │
└────┘
```

**Comment by PedroTadim** [comment]
> my test on CLI
> 
> ```
> v0.5.1 7c111322d
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D SELECT DISTINCT 1 c0 GROUP BY CUBE (1), c0;
> ┌────┐
> │ c0 │
> ├────┤
> │    │
> │ 1  │
> └────┘
> ```

Run on the C client with verification enabled.

**Comment by Mytherin** [comment]
I have updated the title for clarity. The system produces the correct result, but there is a problem related to the verification of the query.

**Comment by PedroTadim** [comment]
This issue continues on https://github.com/duckdb/duckdb/issues/4978
