### ISSUE TITLE
catalog exception when trying to run read_json_objects after loading json module

### ISSUE THREAD

**Issue by raam86** [duckdb/duckdb#4954]
### What happens?

running 
```
con = duckdb.connect(database=':memory:')
con.execute("INSTALL json; LOAD json;select read_json_objects('./testjson.json')").fetchall()
```

results in 
>  CatalogException: Catalog Error: Function with name read_ndjson_objects is not on the catalog, but it exists in the json extension. To Install and Load the extension, run: INSTALL json; LOAD json;

### To Reproduce

install latest duckdb and run the above command.

on master json extension isn't available. 

### OS:

ios

### DuckDB Version:

5.0.1

### DuckDB Client:

Python

### Full Name:

Raam Roch Hai

### Affiliation:

etixoo 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
`read_json_objects` is a table function, as such it needs to be used in the FROM clause:

```sql
select * from read_json_objects('./testjson.json')
```

The error message is confusing, we should probably store the function type alongside the function name so we can improve the error message.

**Comment by Tishj** [comment]
@lnkuiper is this still a problem?

**Comment by lnkuiper** [comment]
This is no longer a problem, we now throw a descriptive error:
```sql
D select read_json('');
-- Error: Binder Error: Function "read_json" is a table function but it was used as a scalar function. This function has to be called in a FROM clause (similar to a table).
-- LINE 1: select read_json('');
```
