### ISSUE TITLE
Rich duckdb's postgres_scanner features have a promising future

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#4955]
The duckdb postgres_scanner will greatly expand the application scenario, which can enhance the OLTP calculation of gp, so that gp is called a better HTAP database. At the same time, it can also separate part of the OLAP calculation, realize the separation of gp memory, and temporarily expand the peak calculation to achieve flexible computing.
Now，have following weaks:
1. only support 1 schema, but sql may join different schemas tables, eg. `select * from sch1.table1 join sch2.table2 on ...`
2. not support uuid、array、json/jsonb columns
3. not support nemeric if not have with
sample data:
```
create table test_scanner(id uuid,code text,sizes int[],skc jsonb,number numeric)
;
insert into test_scanner values(gen_random_uuid(),'test', array[1,2,3],'{"a":1,"b":2}'::jsonb,1234.5000);
```
we use greenplum as HTAP, and night is busy time, but greenplum not support expand temporary，
if postgres_scanner is fully functional, the separation of memory and calculation can be realized，
and duckdb will be a very powerful tool, just like a spark for hive, and Duckdb+Greenplum will be surpass Spark+Hive in many situations.

**Comment by Mause** [comment]
Hi, can you please raise this in the [postgres_scanner repo](https://github.com/duckdblabs/postgres_scanner) instead?
