### ISSUE TITLE
Index sizes do not appear to be accounted for in pragma database_size

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#4967]
### What happens?

According to [this comment](https://github.com/duckdb/duckdb/issues/1546#issuecomment-1263525113) indexes should be managed by the buffer manager and thus contribute to the memory size listed when running `pragma database_size`. However, in some experiments with the CLI this doesn't appear to be the case.

I'm not sure if this is an actual bug or if I'm interpreting things incorrectly.

### To Reproduce

Below are some screenshots illustrating what I'm seeing. I was running duckdb built from commit 91a9fc49a5. So while not the absolute latest & greatest, it's pretty close.

The data being used is 100k rows of an integer and 10 varchars. It's contrived data, here's the first few rows
```csv
id,A0,A1,A2,A3,A4,A5,A6,A7,A8,A9,
0,"ccccccccccccccc00","ccccccccccccccc01","ccccccccccccccc02","ccccccccccccccc03","ccccccccccccccc04","ccccccccccccccc05","ccccccccccccccc06","ccccccccccccccc07","ccccccccccccccc08","ccccccccccccccc09",
1,"ccccccccccccccc10","ccccccccccccccc11","ccccccccccccccc12","ccccccccccccccc13","ccccccccccccccc14","ccccccccccccccc15","ccccccccccccccc16","ccccccccccccccc17","ccccccccccccccc18","ccccccccccccccc19",
2,"ccccccccccccccc20","ccccccccccccccc21","ccccccccccccccc22","ccccccccccccccc23","ccccccccccccccc24","ccccccccccccccc25","ccccccccccccccc26","ccccccccccccccc27","ccccccccccccccc28","ccccccccccccccc29",
```

In the first set of screenshots I've created a table with a primary key on the ID which will also create an index on that column. They show a discrepancy between what DuckDB is reporting versus what the OS is reporting.

![image](https://user-images.githubusercontent.com/8935186/195381451-4b6cd5a1-6310-4ad2-8eec-eed242a93874.png)
![image](https://user-images.githubusercontent.com/8935186/195381526-c2f09aeb-d674-49c8-9174-070e666f25fa.png)

(The 0.4.0 and 0.5.1 instances of duckdb are running with the same table created from the same data set.)

The next set of screenshots show the same table loaded with the same data, except now the `id` column is not a primary key.

![image](https://user-images.githubusercontent.com/8935186/195381905-ffafb403-9582-473e-8ef1-63857ea78cd8.png)
![image](https://user-images.githubusercontent.com/8935186/195381935-11b67b99-ccf3-44ea-b92b-e35ebe401fbf.png)

While I don't have a screenshot for it, if I manually create an index, `create index id_idx on t(id);` the OS-reported memory usage goes back up to about 41.0MB.

### OS:

MacOS

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

Mode

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
@pdet or @taniabogatsch can one of you have a look at this issue?
