### ISSUE TITLE
Doing HASH_JOIN instead of SEQ_SCAN even when driving table has single record

### ISSUE THREAD

**Issue by SartorialOffense** [duckdb/duckdb#4974]
### What happens?

When joining 2 single column tables A and B, the optimizer is picking a HASH_JOIN even when it knows the cardinality of the driving table is as low as 1 (it does short circuit if it is zero). Is there anyway to prevent this and use a more targeted plan for cases like this?

 And thanks again for this fantastic tool!

### To Reproduce

create table data as select cast(i as integer) a from range(1, 50000000, 1) t(i);

pragma enable_profiling;

--does a SEQ_SCAN of data in <1 ms
select * from data where a = 1;

pragma disable_profiling;

create table query as select a from data where false;

insert into query values(1);

pragma enable_profiling;

--does a HASH_JOIN in 170ms
select data.* from query join data on query.a = data.a;

--does a HASH_JOIN in 300ms?
select data.* from (VALUES (1)) AS query(A) join data on query.a = data.a;

### OS:

Windows 10

### DuckDB Version:

0.5.2-dev742

### DuckDB Client:

CLI

### Full Name:

Jonathan Trumbull

### Affiliation:

AbbVie

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Our hash join is the most efficient way to do an equality join between two tables. When the build-side is small (which it is, in your query), we do something that we call a "perfect hash join", which is already a lot faster than a regular hash join.

What kind of query plan would you expect?

This could be rewritten to a filtered table scan instead, but this is an edge case that the optimizer does not cover yet.

**Comment by Mytherin** [comment]
I think the query plan is not the problem here. The reason the scan + filter is so fast is because the scan can use zone maps to skip most of the scan. What would solve this query is if we would gather min/max statistics during the HT build and push them into the scan on the probe side on the corresponding column. That way zone maps can be used with the hash join as well and the hash join should have similar performance.

**Comment by lnkuiper** [comment]
We could already apply the min/max statistics of the build side to the probe side, even without gathering on-the-fly min/max statistics. Should be a pretty simple improvement

**Comment by SartorialOffense** [comment]
@lnkuiper Your hash join is indeed fantastic!  Thanks for taking a look at this.

The actual use case is more complicated with 4 integer identity columns and a string sorted on insertion.

```sql
CREATE TABLE DATA AS	
(
	SELECT 
	  CAST((RANDOM() * 100) + 2 AS INTEGER) A,
	  CAST((RANDOM() * 1000) + 2 AS INTEGER) B,
	  CAST((RANDOM() * 1000) + 2 AS INTEGER) C,
	  CAST((RANDOM() * 1000) + 2 AS INTEGER) D,
	  TRY_CAST(RANDOM() AS VARCHAR) || TRY_CAST(RANDOM() AS VARCHAR) E
	FROM 
		range(0, 5000000, 1)
	ORDER BY A,B,C,D
);

CREATE TABLE QUERY AS SELECT A,B,C,D FROM DATA WHERE FALSE;

INSERT INTO DATA VALUES(1,1,1,1,'Junk');
INSERT INTO QUERY VALUES(1,1,1,1);

PRAGMA enable_profiling;

SELECT * FROM QUERY WHERE A = 1 AND B = 1 AND C = 1 AND D = 1;

SELECT 
	DATA.* 
FROM DATA JOIN QUERY ON
	DATA.A = QUERY.A AND
	DATA.B = QUERY.B AND
	DATA.C = QUERY.C AND
	DATA.D = QUERY.D;
```

**Comment by lnkuiper** [comment]
@SartorialOffense I have been thinking about this a bit, and while I think that creating a filter when a join is highly selective is useful, we would have to implement that first. For now, could you perhaps use an index instead?

```sql
create table data (i integer primary key);
insert into data select range::int from range(1, 50000000, 1);
create table query (i integer references data(i));
insert into query values (1);
select data.* from query join data using (i);
```

Also completes in < 1ms.

**Comment by lnkuiper** [comment]
Also, as a side note: filter conditions propagate across equality joins.

```sql
D create table t1 as select range i from range(10);
D create table t2 as select range i from range(10);
D explain select t1.* from t1 join t2 using (i) where i = 3;
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐                             
│         PROJECTION        │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│             i             │                             
└─────────────┬─────────────┘                                                          
┌─────────────┴─────────────┐                             
│         HASH_JOIN         │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│           INNER           ├──────────────┐              
│           i = i           │              │              
└─────────────┬─────────────┘              │                                           
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t1            ││             t2            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             i             ││             i             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: i=3 AND i IS NOT ││ Filters: i=3 AND i IS NOT │
│            NULL           ││            NULL           │
└───────────────────────────┘└───────────────────────────┘   
```

The filter is applied to both t1 and t2. Maybe that helps?

**Comment by SartorialOffense** [comment]
@lnkuiper For a workaround, adding in a filter condition on the leading column (A = 1) will work in my particular case.

I had tried the index approach, but it doesn't seem to work with a composite index. Here is what I am doing:

```sql
create table data (a integer, b integer, c integer, d integer, primary key (a,b,c,d));

insert into data 
(
	select 
		cast((random() * 100) + 2 as integer) a,
		cast((random() * 1000) + 2 as integer) b,
		cast((random() * 1000) + 2 as integer) c,
		cast((random() * 1000) + 2 as integer) d
	from range(0, 5000000, 1)
	group by a,b,c,d
	order by a,b,c,d
);

create table query as select a,b,c,d from data where false;

insert into data values(1,1,1,1);
insert into query values(1,1,1,1);

pragma enable_profiling;

--neither of these use the index
select * from query where a = 1 and b = 1 and c = 1 and d = 1;
select data.* from data join query using (a,b,c,d);
```
Also, since the indices aren't compressed yet, they increase the file size by >10X at least in this example because your table compression works so well.  BTW, love the new FSST. It is actually the reason I am having these problems because before I needed to store some string data in Parquet for the compression and now I am bringing that workload into tables. Previously I partitioned those files by the leading column and manually created the UNION when searching them.

Thanks again!

**Comment by SartorialOffense** [comment]
@lnkuiper I did a lousy job with my last comment.  Even though I made a copy/paste error with the initial example, the results still hold. When the "query" table has a low row count (or 1), the resulting resulting execution plan is much slower (700X in the last test) than a sequential scan with filtering just using the literals.

And for some reason a unique composite index on a,b,c,d, doesn't seem to get used either with the join to the query table or just specifying the filter with literals.

Using the same setup as the last comment:

```sql
select * from data where a = 1 and b = 1 and c = 1 and d = 1;
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0007s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            data           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
│             b             │
│             c             │
│             d             │
│             e             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ Filters: a=1 AND a IS NOT │
│            NULL           │
│   b=1 AND b IS NOT NULL   │
│   c=1 AND c IS NOT NULL   │
│   d=1 AND d IS NOT NULL   │
│         EC=4999873        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             1             │
│          (0.00s)          │
└───────────────────────────┘

select data.* from data join query using (a,b,c,d);
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 0.504s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
│             b             │
│             c             │
│             d             │
│             e             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             1             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         HASH_JOIN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           INNER           │
│           a = a           │
│           b = b           │
│           c = c           │
│           d = d           ├──────────────┐
│      EC = 4940.585968     │              │
│     COST = 4940.585968    │              │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │              │
│             1             │              │
│          (0.06s)          │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            data           ││           query           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             ││             a             │
│             b             ││             b             │
│             c             ││             c             │
│             d             ││             d             │
│             e             ││            EC=1           │
│         EC=4999873        ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││             1             │
│          4999873          ││          (0.00s)          │
│          (0.43s)          ││                           │
└───────────────────────────┘└───────────────────────────┘


```

**Comment by SartorialOffense** [comment]
Ahh, I think I understand.  Your hash join is so blazingly fast that it doesn't make sense to do anything else given the general use cases for duckdb. And you are just going to trim down the data going into the join by looking at the zone maps with a filter instead of a full scan if this makes sense given the statistics.

**Comment by omo** [comment]
(Unsolicited triage) So the original point seems like WAI although there are some other discussions on the thread?
Maybe we can close this one and open more scoped bugs if needed. @lnkuiper
