### ISSUE TITLE
HTTP 403 (Access Denied) when using read_parquet() with glob matching >1000 S3 objects

### ISSUE THREAD

**Issue by ngould** [duckdb/duckdb#4975]
### What happens?

DuckDB throws an error when I do a glob-style query that matches over 1000 S3 objects.

Here's the query I'm using:

```
SELECT *
FROM read_parquet('s3://prod-ingestion-github-repositories/2022-09_*');
```

And here is the error message I'm getting:

```
Invalid Error: HTTP GET error on 'https://prod-ingestion-github-repositories.s3.amazonaws.com/?continuation-token=1ZU0D5N%2Bv2Dm9hhTi2JQvSAphFHiPRSnPegvosjQD3klo92WJYFwF8yrnJdtFhDHfsIka/QOCYNdQQTHC6f/3H8mudjEJscJydhNUTBJevcvcZlqgunsNdyhSHXsAZLbc&encoding-type=url&list-type=2&prefix=2022-09_' (HTTP 403)
```

I confirmed that the same query works if the glob pattern is modified to match fewer objects. E.g., the following returns the expected result:

```
SELECT *
FROM read_parquet('s3://prod-ingestion-github-repositories/2022-09_06-*');
```

### To Reproduce

Tough for me to provide the exact dataset, but the general gist is:

1) Create N parquet files in S3 with the same prefix, where N is some number >1000
2) Query them with `read_parquet('your-prefix-*')`

### OS:

OSX

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Nathan Gould

### Affiliation:

Endeavor Labs LLC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by dacort** [comment]
Ran into this as well using the [NOAA GSOD](https://registry.opendata.aws/noaa-gsod/) dataset. 

This is a public dataset, so you can easily repro:

```sql
SELECT * FROM read_csv_auto('s3://noaa-gsod-pds/2021/*.csv', header=True) LIMIT 10;
```

**Comment by calebmadrigal** [comment]
This is probably the same error I am getting with this one: https://github.com/duckdb/duckdb/issues/5190. I noticed that it does _sometimes_ work... perhaps related the order in which the pagination happens?

**Comment by samansmink** [comment]
I've been meaning to look into this, expect to have time for this next week
