### ISSUE TITLE
Crash When Creating Index

### ISSUE THREAD

**Issue by bajinsheng** [duckdb/duckdb#4976]
### What happens?

Crash.

### To Reproduce

```sql
CREATE TABLE t0(c0 DOUBLE, c1 TIMESTAMP DEFAULT(TIMESTAMP '1970-01-04 12:58:32'));
INSERT INTO t0(c1, c0) VALUES (TIMESTAMP '1969-12-28 23:02:08', 1);
INSERT INTO t0(c0) VALUES (DEFAULT);
CREATE INDEX i2 ON t0(c1, c0); -- segment fault
```

### OS:

Ubuntu 20:04

### DuckDB Version:

v0.5.2-dev737 9913e0e80

### DuckDB Client:

CLI

### Full Name:

Jinsheng Ba

### Affiliation:

National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taniabogatsch** [comment]
This crash should no longer occur once the current `CREATE INDEX` PR gets merged (#4960).
