### ISSUE TITLE
Please add ExtractStatements to C API

### ISSUE THREAD

**Issue by marcboeker** [duckdb/duckdb#4977]
Hi,

we're using the C API in the Go DuckDB driver. All statements are processed using the `duckdb_prepare` function. If someone provides multiple statements to our `Exec` function, DuckDB throws an error, complaining about multiple statements in a prepare, which makes absolutely sense. See https://github.com/marcboeker/go-duckdb/issues/46

The Python driver uses the [`ExtractStatements` method](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L145) on the provided input and then prepares each extracted statement on its own.

Would it be possible to add the [`ExtractStatements` method](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb/main/connection.hpp#L103) to the C API, so that we can also accept multiple statements in one call to our `Exec` function.

Thank you!

**Comment by marcboeker** [comment]
Hi @LindsayWray, do you have an ETA on this? Thanks!

**Comment by LindsayWray** [comment]
> Hi @LindsayWray, do you have an ETA on this? Thanks!

Thanks for the reminder, my apologies for taking so long! I will send out a pr today!

**Comment by LindsayWray** [comment]
The PR is merged, so I'm closing this issue!

**Comment by marcboeker** [comment]
Awesome, thank you!

**Comment by aszenz** [comment]
> The Python driver uses the [ExtractStatements method](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L145) on the provided input and then prepares each extracted statement on its own.

I think the odbc driver needs to do the same thing, i'm getting the same error: 

```
Cannot prepare multiple statements at once!
```
