### ISSUE TITLE
S3 Access from Sagemaker: DuckDB never uses more than 2 threads when accessing S3

### ISSUE THREAD

**Issue by CerebralMastication** [duckdb/duckdb#4981]
All my testing seems to indicate that when reading from S3, DuckDB never uses more than 2 threads, regardless of number of processors available. Others have confirmed that this behavior is not expected. So escalating this discussion into an issue. 

### Discussed in https://github.com/duckdb/duckdb/discussions/4780

<div type='discussions-op-text'>

<sup>Originally posted by **CerebralMastication** September 22, 2022</sup>
Hey all, I've been playing around with DuckDB on Sagemaker reading parquet files on S3. I expected it to be considerably slower than a local file system, of course. However the performance has been really surprisingly slow. Slow enough that I'm wondering if I'm doing something wrong or if possibly DuckDB isn't reading from S3 in parallel threads the way it does on a local file system. 

I have a bucket in S3 with a ~7000 parquet files. I'm using only the first 101 of these for my testing. The script that generates the test data can be found [here](https://github.com/CerebralMastication/DataToolTesting/blob/main/simulate_imbalanced_data.ipynb). 

my test of reading from S3 with duckdb is in [this notebook](https://github.com/CerebralMastication/DataToolTesting/blob/main/query_s3.ipynb). 

The crux of the test is this simple summation:

```
df = con.execute(f"select sum(value) from parquet_scan({my_parquet_list[0:100]}) ;").df()
```

I'm passing `parquet_scan` a list of 101 files which represent approx 165MB and 11.5m records. What's unexpected is I ran this test using 4 different Sagemaker instance sizes with 2, 4, 8, and 16 VCPU. They all ran the query in ~12 seconds. (I used `%%timeit` cell magic so ran 7 loops and I reran each test 3 times. I found some variation around run time, but it was not related to number of CPUs which I found unexpected as I would have expected read speed to decrease with increasing number of vCPUs. 

I'm also a bit surprised that this read took 12 seconds even on a single thread. With my data and compute both located in `eu-west-1 ` I would have expected to get 100 Gbps throughput. 

It feels like maybe I'm doing this wrong. Any suggestions you all have would be greatly appreciated. 

Update:
I wanted to compare DuckDB timing above with simply slurping all the parquet files into Pandas and filtering them. I realize that this is RAM constrained but I know that the `awswrangler` is single threaded so that will give me some notion of how fast simply reading the data from S3 on one thread is. So I ran the following:

```
df = wr.s3.read_parquet(path=my_parquet_list[0:100], boto3_session=my_session)
df.value.sum()
```
which should move all those same parquet files out of S3 and read them into ram then filter. 

it runs in 8.5 seconds on a worker with 4 vCPU and 16GiB RAM (ml.g4dn.xlarge)

</div>

**Comment by arjenpdevries** [comment]
I don't know the answer but would suggest to try the same with one large parquet file instead of a list of 100 smaller ones, to rule out that this opening of 100 files might affect your timings?

**Comment by IanCal** [comment]
Github seems to have eaten my reply, but here's a quick overview so I hope it's useful.

I regenerated the data, and it came to ~670M, with some files a few kb and some 200M+. 

Querying took about 10-15s, so around 350-500Mbps on a c3.2xl. Cutting it down to a single file improved that to ~4s when selecting all columns (less selecting just one), which is around 1Gbps. My suspicion is that maxed out the speed my instance could pull / single S3 file access.

My expectation is that this comes down to having to do more than one request per file when querying remotely. First to get the metadata and plan, second to pull the contents of the rowgroups actually required.

> I would have expected to get 100 Gbps throughput.

Throughput on a single instance maxes at 100 Gbps, but that's only for some instances. Other instances have lower networking performance.

**Comment by CerebralMastication** [comment]
> I don't know the answer but would suggest to try the same with one large parquet file instead of a list of 100 smaller ones, to rule out that this opening of 100 files might affect your timings?

This raises some questions in my mind... I think I have a misunderstanding of DuckDB. Would you expect parallel read from DuckDB on a single large parquet file (assume disk, not S3)?

I had the (possibly false) mental model that with a single parquet file parallel read was not possible. I thought that they had to be partitioned in some way to get parallelization. I may have come into DuckDB with some assumptions I brought from Spark.

**Comment by Alex-Monahan** [comment]
DuckDB can read parquet rowgroups in parallel, but I've only used it locally.

**Comment by IanCal** [comment]
> I had the (possibly false) mental model that with a single parquet file parallel read was not possible. I thought the files had to be partitioned in some way to get parallelization. I may have come into DuckDB with some assumptions I brought from Spark.

Parquet files are partitioned internally. They're split into row groups, then within each of those it's columnar (then another split into pages within that I think). There's metadata in the footer of the file that should list all row groups, and statistics for them (vital for planning), as well as their offset - so readers can parallelise processing the files as long as you can seek efficiently (s3 supports range requests which are important for that).

**Comment by samansmink** [comment]
I think this may be related to the fact that we currently don't scan parquet metadata in parallel. especially when scanning many small parquet files (or even worse, metadata-only queries such as `select count(*) from 's3://bucket/*.parquet'`).

I'm working on a fix for this that will allow scanning metadata in parallel too.

**Comment by samansmink** [comment]
fixed by: https://github.com/duckdb/duckdb/pull/5405
