### ISSUE TITLE
Python source distribution doesn't pull build requirements

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#4984]
### What happens?

The source distribution of `duckdb` that is uploaded to PyPI requires NumPy, but if one tries to `pip install duckdb` directly without having NumPy already installed, it will not pull it and will error out instead. I guess the requirements file would beed to be renamed to `requirements.txt` for this to work but I am not 100% sure.

### To Reproduce

* Assuming you are running it in an architecture without prebuilt wheels:
```
pip install duckdb
```

* Assuming you are running it in an architecture with prebuilt wheels:
```
pip install https://files.pythonhosted.org/packages/9b/b3/6794582d52767b668eb92cf04b587f9804155435d11f3c22fa0c468189ef/duckdb-0.5.1.tar.gz
```

(in both cases, be sure to uninstall NumPy before attempting to install DuckDB)

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hi, thanks for raising this issue - we have however already fixed it in the dev version, see https://github.com/duckdb/duckdb/pull/4893
