### ISSUE TITLE
Faulty `Binder Error: recursive CTE` under certain conditions

### ISSUE THREAD

**Issue by aarashy** [duckdb/duckdb#4987]
### What happens?

The error `Binder Error: Circular reference to CTE "table1", use WITH RECURSIVE to use recursive CTEs` is being thrown too aggressively.

For example, the following queries succeed, as they should:
```
WITH table1 AS (SELECT c1 FROM table1) SELECT * FROM table1
WITH table1 AS (SELECT c1 FROM myschema.table1) SELECT * FROM table1
```

And the following query succeeds (Notice the addition of a second CTE which references the alias of the first CTE):
```
WITH renamed_table AS (SELECT c1 FROM myschema.table1), foo AS (SELECT * FROM renamed_table) SELECT * FROM foo
```

But the queries below fail.

### To Reproduce

First example: in the presence of multiple CTEs, a faulty Recursive CTE error is thrown.
This is the same as the last successful example above, except the CTE alias is equal to the physical table name minus the schema.
```
create schema myschema;
create table myschema.table1 (c1 bigint);
insert into table1 values (1);

WITH table1 AS (SELECT c1 FROM myschema.table1), foo AS (SELECT * FROM table1) SELECT * FROM foo;
>>> Error: Binder Error: Circular reference to CTE "table1", use WITH RECURSIVE to use recursive CTEs
```

Second example: in the presence of a JOIN, a faulty Recursive CTE error is thrown.
```
create schema myschema;
create table myschema.table1 (c1 bigint);
insert into myschema.table1 values (1);

create table myschema.table2 (c2 bigint);
insert into myschema.table2 values (2);

WITH table2 AS 
  (SELECT c2 FROM myschema.table2), 
table1 AS 
  (SELECT c1 FROM myschema.table1) 
SELECT * FROM table1 LEFT JOIN table2 
  ON table1.c1 + 1 = table2.c2;
>>> Error: Binder Error: Circular reference to CTE "table1", use WITH RECURSIVE to use recursive CTEs
```
In these examples, if the alias is renamed to be unequal to the physical table name, then the query succeeds.
For example, the last query succeeds if rewritten to the following:
```
WITH table2_rename AS 
  (SELECT c2 FROM myschema.table2), 
table1_rename AS 
  (SELECT c1 FROM myschema.table1) 
SELECT * FROM table1_rename LEFT JOIN table2_rename 
  ON table1_rename.c1 + 1 = table2_rename.c2;
┌────┬────┐
│ c1 │ c2 │
├────┼────┤
│ 1  │ 2  │
└────┴────┘
```

As a final example that has no schema names involved: the following query is allowed in Postgres but hits the same error as above in DuckDB:
```
with tmp as (select * from tmp), foo as (select * from tmp) select * from foo;
>>> Error: Binder Error: Circular reference to CTE "tmp", use WITH RECURSIVE to use recursive CTEs
```

### OS:

Monterey

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI / Rust

### Full Name:

Aarash Heydari

### Affiliation:

Dataland

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by aarashy** [comment]
At first glance, it seems like the problem is that the binder is checking only the table name and not the schema name.
https://github.com/duckdb/duckdb/blob/e322d56ff9ff4005f728073fda541b1bc3ab6c81/src/planner/binder/tableref/bind_basetableref.cpp#L26

```

unique_ptr<BoundTableRef> Binder::Bind(BaseTableRef &ref) {
	QueryErrorContext error_context(root_statement, ref.query_location);
	// CTEs and views are also referred to using BaseTableRefs, hence need to distinguish here
	// check if the table name refers to a CTE
	auto cte = FindCTE(ref.table_name, ref.table_name == alias);
	if (cte) {
		// Check if there is a CTE binding in the BindContext
		auto ctebinding = bind_context.GetCTEBinding(ref.table_name);
		if (!ctebinding) {
			if (CTEIsAlreadyBound(cte)) {
				throw BinderException("Circular reference to CTE \"%s\", use WITH RECURSIVE to use recursive CTEs",
				                      ref.table_name);
			}
	
```
Perhaps this should be checking whether `ref.schema_name` is non-empty, and concatenating it to the `ref.table_name` - either in the call to `FindCTE` or in the call to `GetCTEBinding` (probably the former?).

I hesitate to put up the PR myself, but I'm hopeful it should be a relatively easy fix.

**Comment by aarashy** [comment]
I just edited the issue to add a case where we hit this error without having any Schema name at all. 
The following succeeds in Postgres but fails in DuckDB
```
create table tmp (c1 bigint);
with tmp as (select * from tmp), foo as (select * from tmp) select * from foo;
>>> Error: Binder Error: Circular reference to CTE "tmp", use WITH RECURSIVE to use recursive CTEs
```

**Comment by l1t1** [comment]
`with RECURSIVE` is ok
```
with RECURSIVE tmp as (select 1 a union all select a+1 from tmp where a<3), foo as (select * from tmp) select * from foo;
┌───┐
│ a │
├───┤
│ 1 │
│ 2 │
│ 3 │
└───┘
```

**Comment by aarashy** [comment]
It's true that when `with RECURSIVE` is used, this check becomes relaxed and doesn't throw the spurious error.

But the issue here is failures when using valid non-recursive CTEs which happen to shadow the name of physical tables in the query.
