### ISSUE TITLE
Extensions fail to load in Python dev build but not in CLI

### ISSUE THREAD

**Issue by jcrist** [duckdb/duckdb#4989]
### What happens?

When building duckdb and the Python library from source, I'm able to load extensions in the built CLI, but not in the Python library. When loading with the Python library, I see "undefined symbol" errors, as described below.

This appears to be one of the issues that #3381 was intended to resolve, but I'm still seeing the error here.

### To Reproduce

**Build**

I built the latest commit on `master` (e322d56ff9ff4005f728073fda541b1bc3ab6c81). I ran this in a new conda environment containing Python 3.10, `cmake`, and `ninja`, as well as the python build dependencies installed with `pip install -r requirements-dev.txt` as per https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/README.md.

```
$ GEN=ninja BUILD_PYTHON=1 make
```

The build completed successfully, and both the package and CLI import and execute SQL as expected. It's only when trying to load the extensions that things fail.

**Try to load an extension in the Python shell**

```python
In [1]: import duckdb

In [2]: duckdb.__version__
Out[2]: 'v0.5.2-dev754'

In [3]: con = duckdb.connect(config={"allow_unsigned_extensions": "true"})

In [4]: con.execute("LOAD '/home/jcristharif/Code/duckdb/build/release/extension/json/json.duc
   ...: kdb_extension'")
---------------------------------------------------------------------------
IOException                               Traceback (most recent call last)
Cell In [4], line 1
----> 1 con.execute("LOAD '/home/jcristharif/Code/duckdb/build/release/extension/json/json.duckdb_extension'")

IOException: IO Error: Extension "/home/jcristharif/Code/duckdb/build/release/extension/json/json.duckdb_extension" could not be loaded: /home/jcristharif/Code/duckdb/build/release/extension/json/json.duckdb_extension: undefined symbol: _ZTIN6duckdb18BaseScalarFunctionE
```

**Successfully load the same extension in the duckdb shell**

```
$ ./build/release/duckdb -unsigned
v0.5.2-dev754 e322d56ff
Enter ".help" for usage hints.
D LOAD 'build/release/extension/json/json.duckdb_extension';
D 
```

### OS:

Linux

### DuckDB Version:

dev master branch

### DuckDB Client:

Python

### Full Name:

Jim Crist-Harif

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jcrist** [comment]
I tried calling `setdlopen` manually as suggested in https://github.com/duckdb/duckdb/issues/3243#issuecomment-1080500983, and that does seem to resolve the problem (at least on my machine).

```python
In [1]: import sys, os

In [2]: sys.setdlopenflags(os.RTLD_GLOBAL | os.RTLD_NOW)
```

**Comment by hannes** [comment]
Try adding `EXTENSION_STATIC_BUILD=1` to your `make` line

**Comment by wonb168** [comment]
> I tried calling `setdlopen` manually as suggested in [#3243 (comment)](https://github.com/duckdb/duckdb/issues/3243#issuecomment-1080500983), and that does seem to resolve the problem (at least on my machine).
> 
> ```python
> In [1]: import sys, os
> 
> In [2]: sys.setdlopenflags(os.RTLD_GLOBAL | os.RTLD_NOW)
> ```

this WORK, I tried lots of methods, all not WORK!
util find this way, `sys.setdlopenflags(os.RTLD_GLOBAL | os.RTLD_NOW)`

**Comment by Mytherin** [comment]
Closing as this issue has been resolved
