### ISSUE TITLE
use odbc to connect, the returned Chinese characters are garbled under Windows

### ISSUE THREAD

**Issue by wozaitianwai** [duckdb/duckdb#4997]
### What happens?

Use ODBC driver to query in PowerBI and python, and Chinese characters are garbled.
 it is right to use the dackdb  and duckdb-engine.

How do I set

### To Reproduce

```
import pyodbc

conn = pyodbc.connect('Driver={DuckDB Driver};dataset=:memory:;dsn=DuckDB;')
cursor = conn.cursor()

SQL = r"""WITH record AS (SELECT * FROM  read_csv_auto('C:\Users\wozai\Desktop\pay_record_info2.csv') )
SELECT 
	OrderType_Name ,
	Parking_Name,
	strftime(PayOrder_PayedTime , '%Y-%m-%d'),
    SUM(PayOrder_PayedMoney) 
FROM
   record
GROUP BY OrderType_Name,
         Parking_Name,
         strftime(PayOrder_PayedTime , '%Y-%m-%d')
 ORDER BY
 	strftime(PayOrder_PayedTime , '%Y-%m-%d') DESC;"""
for row in cursor.execute(SQL):
    print(row)
cursor.close()
```

![微信截图_20221014222229](https://user-images.githubusercontent.com/22335540/195870585-fea7069a-cb5d-4bb1-883d-ddc9d562bc92.png)

Chinese column name is normal

![微信截图_20221014222229](https://user-images.githubusercontent.com/22335540/195871200-072a747a-bf42-46ea-b924-5d692e97f6f9.png)

### OS:

windows11

### DuckDB Version:

0.5.1

### DuckDB Client:

ODBC

### Full Name:

Zen NanRin

### Affiliation:

wozaitianwai@gmail.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by alitrack** [comment]
I tried  ODBC directly , same issue.

btw, maybe you can use duckdb-engine, here is an example,

```PYTHON
from sqlalchemy import create_engine

eng = create_engine("duckdb://")

import pandas as pd 
# pandas
province_pd = pd.read_csv('f:/duckdb/province.csv',encoding='UTF-8').head()
# csv 
province = pd.read_sql("select * from 'f:/duckdb/province.csv'  limit 10",con=eng)
print(province)
#duckdb table 
# msft = pd.read_sql("select * from msft",con=eng)
#parquet
customer = pd.read_sql("select * from 'f:/duckdb/customer.parquet' limit 10",con=eng)

```

**Comment by wozaitianwai** [comment]
> 我直接尝试了 ODBC，同样的问题。
> 
> 顺便说一句，也许你可以使用duckdb-engine，这是一个例子，
> 
> ```python
> from sqlalchemy import create_engine
> 
> eng = create_engine("duckdb://")
> 
> import pandas as pd 
> # pandas
> province_pd = pd.read_csv('f:/duckdb/province.csv',encoding='UTF-8').head()
> # csv 
> province = pd.read_sql("select * from 'f:/duckdb/province.csv'  limit 10",con=eng)
> print(province)
> #duckdb table 
> # msft = pd.read_sql("select * from msft",con=eng)
> #parquet
> customer = pd.read_sql("select * from 'f:/duckdb/customer.parquet' limit 10",con=eng)
> ```
I want to use it in PowerBi.
There is no problem using duckdb and duckdb-engine in python.
PowerBi uses python to link duckdb, and the problem is temporarily solved.
But I still hope to solve the problem of ODBC's support for Chinese.

**Comment by ClausCohl** [comment]
I tried with v0.6.2-dev1772 d25a77fff4

It's still an issue, not only for Chinese letters but other languages, too.
My use-case handles some German Umlaut e.g. Ä-Ö-Ü.
They all get scrambled when using the plain duckdb odbc driver.

Expected result: ÄäÖöÜüß
But got: Ã„Ã¤Ã–Ã¶ÃœÃ¼ÃŸ

As far as I can see the Datatype from the odbc driver returns 'VARCHAR', which should be actually WVARCHAR ?

I can do some testing if that will help, C++ coding only limited.

Unfortunately, I cannot use python as a workaround.

**Comment by ClausCohl** [comment]
I tried with v0.8.1 https://github.com/duckdb/duckdb/tree/v0.8.1

Still the same issue:

They all get scrambled when using the plain duckdb odbc driver.

Expected result: ÄäÖöÜüß
But got: Ã„Ã¤Ã–Ã¶ÃœÃ¼ÃŸ

Unfortunately, I cannot use python as a workaround.
