### ISSUE TITLE
How to unset an already SET configuration?

### ISSUE THREAD

**Issue by chamini2** [duckdb/duckdb#4998]
### What happens?

I am doing a wrapper around a duckdb client and I need to overwrite a setting and then putting it back to what the original client had.

pseudo code:
```py
try:
  old_s3_region = execute("SELECT current_setting('s3_region')")
raise:
  # if it was not set originally
  old_s3_region = None

execute("SET s3_region = 'my_temp_value'")

# reset it back
if old_s3_region:
  execute(f"SET s3_region = '{old_s3_region}'")
else:
  # *** I don't know what to do here ***
  execute("???")
```

I tried

```
D set s3_region=null;
Error: Parser Error: syntax error at or near "null"
LINE 1: set s3_region=null;
```

```
D set s3_region=;
Error: Parser Error: syntax error at or near ";"
LINE 1: set s3_region=;
```

```
D unset s3_region;
Error: Parser Error: syntax error at or near "unset"
LINE 1: unset s3_region;
``` 

### To Reproduce

I have not installed master because this feature is not documented at all, so I guess it is not there.
I know this is a bug report form, but I did not find where to add feature requests in [CONTRIBUTING](https://github.com/duckdb/duckdb/blob/master/CONTRIBUTING.md).

### OS:

macos: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:07 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8110 arm64

### DuckDB Version:

v0.5.1 7c111322d

### DuckDB Client:

Python

### Full Name:

Matteo Ferrando

### Affiliation:

fal.ai

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello! Installing from master is documented here:
https://duckdb.org/docs/installation/

**Comment by chamini2** [comment]
> Hello! Installing from master is documented here: https://duckdb.org/docs/installation/

I meant that the feature to `unset` is not documented at all, so I did not try on master because I did not think it would be there.

Edited to reflect that.
