### ISSUE TITLE
Add support for compressed storage

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#50]

**Comment by diegomestre2** [comment]
Notes from the last Madam:
1. Include version number
2. Include structured free blocks list
3. Table Information should store one blockId that points to a list of blocks
4. BlockId should be in the buffer manager
5. Free blocks should write the header information before they are reused.
6. Support bigger than memory situations.

**Comment by diegomestre2** [comment]
Design for compression:
BaseEncoder : Virtual de/encoder
DictionaryEncoder, RunLengthEncoder, FrameOfReferenceEncoder, ...
The encoder should get a data chunk and return an EncodedSegment.
EncodedSegment is a virtual representation of a compressed chunk.
We will have multiple types of encoded segments, one per compression technique.

**Comment by diegomestre2** [comment]
In order to define the best compression scheme and the parameters, we first get a sample from the column which can be around 10K values per block. After that, a sorting step is performed and we build a histogram to analyze the occurrence of the values. The Dictionary can be built with a simple hash table. Compression is performed during the appending operation and decompression is performed as part of the scan operation. The dictionary points to a vector of pointers. A pointer can point to a compressed entry or an exception entry.

**Comment by diegomestre2** [comment]
There are two cases where compression will be performed:
1- During bulk loading
2- During SQL INSERT statements.
In both cases, the compression optimizer will use a sample of the data, thus it is necessary to define a threshold on the number of tuples to define when the compression optimizer will be called.

**Comment by evansd** [comment]
Just a note to make sure to consider [blosc](https://blosc.org/pages/blosc-in-depth/) when looking at options for compression libraries.

**Comment by hawkfish** [comment]
I've had success with [dynamically changing the encoding](https://research.tableau.com/sites/default/files/SIGMOD%202014.pdf). From §3.2:

>To accomplish this, we continually track statistics for a column as values are inserted. These statistics are simple to gather, consisting mostly of the value range and delta range. At any given point, we can quickly determine the best of the available choices of encoding for the column. We dynamically encode the columns one block at a time, using the block values for a column to update the column’s statistics before inserting the data block into the column’s encoding stream. If the column insert fails (e.g. due to representation limitations), we can consult the column’s statistics and choose a new encoding. When all rows have been processed, we can also compare the current encoding with the optimal one and convert to this optimal format if desired. In practice, we found that the encoding stabilizes quite quickly: Encoding the TPC-H [TPCH] lineitem table at SF 1 made only two encoding changes and the rewrites still performed less disk IO than writing the unencoded column.

**Comment by Mytherin** [comment]
Implemented in #2099
