### ISSUE TITLE
Incorrect handling of null (0x00) byte in CSV parser

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#5013]
### What happens?

When reading in a CSV using the `COPY...FROM` syntax, DuckDB threw an error saying
> Invalid Input Error: Error in file "bad.txt" between line 0 and 15 in column ""column10"": file is not valid UTF8.

This is due to a single null (0x00 byte) in column 10.

I believe that null bytes should be allowed in UTF-8. From [Wikipedia](https://en.wikipedia.org/wiki/UTF-8#Comparison_with_other_encodings)
> Backward compatibility: Backward compatibility with ASCII and the enormous amount of software designed to process ASCII-encoded text was the main driving force behind the design of UTF-8. In UTF-8, single bytes with values in the range of 0 to 127 map directly to Unicode code points in the ASCII range. Single bytes in this range represent characters, as they do in ASCII.

Running `isutf8` on the attached file in the "To Reproduce" section indicates it is valid UTF-8.

Potentially related to https://github.com/duckdb/duckdb/issues/3193

### To Reproduce

Download the attached file and place it in your current directory. In the CLI run
`select * from read_csv_auto('bad.csv');`

You should see the following error:
> Error: Invalid Error: String value is not valid UTF8

The null byte is after "year" and before the double quote after "year".

[bad.csv](https://github.com/duckdb/duckdb/files/9804702/bad.csv)

### OS:

MacOS

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

Mode

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hey thanks for raising the issue :)

I agree that the nullbyte is part of UTF-8, I'm just wondering what in your eyes the correct behavior would be when it's encountered here, since we're parsing strings.
Do we just skip the nullbyte and pretend it's not there? Or do you suggest we keep it in the resulting string?

**Comment by Mytherin** [comment]
DuckDB does not allow null bytes in strings, so all we can do here is change the error message (from `Invalid UTF8` to `Illegal null-byte encountered in string`). That seems like a good idea for more clarity, but I assume it won't fix the issue you are running into.

We could add a flag to ignore invalid unicode symbols and null-bytes when they are encountered in a CSV file.

**Comment by michaeljohnalbers** [comment]
@Mytherin A better error message and the ability to configure the ability to skip/ignore invalid bytes would be good.
