### ISSUE TITLE
CLI cannot load unsigned extension after open an existing db file (with -unsigned flag)

### ISSUE THREAD

**Issue by wangxiaoying** [duckdb/duckdb#5022]
### What happens?

The following error raises when start the client with on an existing db file.

```
Error: IO Error: Extension "build/release/extension/postgres_scanner/postgres_scanner.duckdb_extension" could not be loaded because its signature is either missing or invalid and unsigned extensions are disabled by configuration (allow_unsigned_extensions)
```

In-memory mode and opening a new db file will not raise this issue.

### To Reproduce

Can use [postgres extension](https://github.com/duckdblabs/postgres_scanner) to reproduce the issue. After building duckdb and postgres extension:

```bash
# Error if `test.db` exists, success if not
./duckdb/build/release/duckdb -unsigned test.db
D LOAD 'build/release/extension/postgres_scanner/postgres_scanner.duckdb_extension';

# No error
./duckdb/build/release/duckdb -unsigned
D LOAD 'build/release/extension/postgres_scanner/postgres_scanner.duckdb_extension';
```

### OS:

OSX (m1)

### DuckDB Version:

master branch (c2ca23eef98ca91fdf73ff29129bc7816bd73ff3)

### DuckDB Client:

CLI

### Full Name:

Xiaoying Wang

### Affiliation:

Simon Fraser University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Have you tried this on the latest master? This seems very similar to #4895.

**Comment by wangxiaoying** [comment]
Thanks for the quick reply! Yeah, I found that issue and tried on latest master. It works on `.open` mode after start the client with command `duckdb -unsigned`. But it still raise the error if I start the client with `duckdb -unsigned existing.db`.

**Comment by mskyttner** [comment]
Similar also to https://github.com/duckdb/duckdb/discussions/4959#discussioncomment-3859646
