### ISSUE TITLE
duckdb not returning all the rows rather it returns the distinct values

### ISSUE THREAD

**Issue by ushnak-tech** [duckdb/duckdb#5029]
Hi, I have been working on a problem and wrote the following SQL query to get all the values from the `price_string `column which are not null and do not start with the `$` sign.

```
query_str='''
      Select price_string 
      from df
      where price_string not like '$%'
      and price_string is not null  
      '''
duckdb.query(query_str)

```

output-
![Screenshot (613)](https://user-images.githubusercontent.com/77790509/196647785-73af3329-4f94-4bfc-81ba-cf0ea8b55679.png)

However, in the result, it only returns 10 rows(the distinct values) and when I tweak the code and convert the output to df, it returns all the 210000 rows.

```
query_str='''
      Select price_string 
      from df
      where price_string not like '$%'
      and price_string is not null  
      '''
duckdb.query(query_str).to_df()

```

output-
![Screenshot (614)](https://user-images.githubusercontent.com/77790509/196648071-b795bf10-db3f-4e84-a0fb-71b3033715df.png)

**Comment by Tishj** [comment]
Hmm, the Result Preview is not the same as the result, can you verify that you also get this problem when you add `.fetchall()` to the end of your first query?

```py
query_str='''
      Select price_string 
      from df
      where price_string not like '$%'
      and price_string is not null  
      '''
duckdb.query(query_str).fetchall()
```

**Comment by Mytherin** [comment]
As indicated by others this is a feature, not a bug. Use one of the fetch methods to obtain the results.

**Comment by ushnak-tech** [comment]
oh okay got it, thanks!!
