### ISSUE TITLE
Why the data display is incomplete?when i read from the parquet file.

### ISSUE THREAD

**Issue by kamylee** [duckdb/duckdb#5036]
### What happens?

I am using nanoodbc to connect to the odbc of duckdb. I found that when the data length is greater than 257, the display is incomplete. What should I do?

### To Reproduce

 auto const connection_string = NANODBC_TEXT("DRIVER={DuckDB Driver};Database=:memory:;");
connection conn(connection_string);
char* strSql_gb2312 = "SELECT msg_id,src_msg,length(src_msg)  FROM read_parquet('20221014_150000_160000.parquet') limit 3;";
result row = execute(conn,/*strSql_utf8*/ strSql_gb2312);
 for (int i = 1; row.next(); ++i)
{
       cout << i << " :"
       << convert(row.get<nanodbc::string>(0))
       << "  "
       << row.get<nanodbc::string>(1)
       << "  "
       << row.get<nanodbc::string>(2)    
       << endl;
}

run result:

1 :ZMServer20220921110624650a5b5  {
  "msgid": "ZMServer20220921110624650a5b5",
  "msg": {
    "tracecode": "03759710000N9210289",
    "cmdid": "20220921110624478b215",
    "friststep": "0",
    "laststep": "0",
    "gb_code": "APSS_STD_JSJ_DY_MXDYXBQ",
    "gylj_id": "FSB06_1",    <------------------------ end here. But the actual length is 384. How to show all strings.
   384
2 :ZMServer202209211106254768ad9  {
  "msgid": "ZMServer202209211106254768ad9",
  "msg": {
    "tracecode": "03980144003N9210001",
    "cmdid": "202209211106250518fae",
    "friststep": "0",
    "laststep": "0",
    "gb_code": "STD_JSJ_ZPDY_MXZDDYXBQ",
    "gylj_id": "FSB07_1",
    372
3 :ZMServer202209211106266429793  {
  "msgid": "ZMServer202209211106266429793",
  "msg": {
    "tracecode": "229143322092131010142",
    "cmdid": "20220921110626100a141",
    "friststep": "0",
    "laststep": "0",
    "gb_code": "YZ_JSJ_DY_HJSCTMDY",
    "gylj_id": "AWM24-A_1",
    374
![QQ浏览器截图20221020135652](https://user-images.githubusercontent.com/16358994/196867607-cace0662-76e5-4815-ace2-ecbc5de29903.png)

### OS:

windows 10

### DuckDB Version:

0.5.1

### DuckDB Client:

ODBC

### Full Name:

mingkun lee

### Affiliation:

kamylee744@gmail.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Thanks for the report, but we cannot reproduce this with the information given. For example, we don't have the `20221014_150000_160000.parquet` file. Can you try making this a minimal reproducible example please? See here for an explanation: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kamylee** [comment]
This is all the source code, just a few lines. It was modified using the northwind example in the nanodbc library.
source code:
`auto const connection_string = NANODBC_TEXT("DRIVER={DuckDB Driver};Database=:memory:;");
connection conn(connection_string);
char* strSql_gb2312 = "SELECT msg_id,src_msg,length(src_msg) FROM read_parquet('20221014_150000_160000.parquet') limit 3;";
result row = execute(conn,/strSql_utf8/ strSql_gb2312);
for (int i = 1; row.next(); ++i)
{
cout << i << " :"
<< convert(row.getnanodbc::string(0))
<< " "
<< row.getnanodbc::string(1)
<< " "
<< row.getnanodbc::string(2)
<< endl;
}`

nanodbc home:https://github.com/nanodbc/nanodbc/tree/main/example

**Comment by kamylee** [comment]
This is a complete nanodbc library.
[nanodbc-main.zip](https://github.com/duckdb/duckdb/files/9835757/nanodbc-main.zip)
