### ISSUE TITLE
BETWEEN and comparison do not behave equivalently

### ISSUE THREAD

**Issue by sankalpgambhir** [duckdb/duckdb#5039]
### What happens?

Per the duckdb documentation, the `BETWEEN` operator is equivalent to the conjunction of two comparisons. However, for certain inputs, this is not the case. Consider the following table and queries:

```sql
    create table t0 (c0 TIMESTAMP);
    insert into t0 values ('2022-11-09 09:08:17');
    insert into t0 values ('2022-11-09 09:08:07');
    -- insert into t0 values ('1980-11-09 09:09:07');

    -- query
    select * from t0 where (t0.rowid between t0.c0 and 'a');        -- query 1
    select * from t0 where (t0.rowid >= t0.c0 and t0.rowid <= 'a'); -- query 2
```

As expected, both queries return empty. However, on a slight modification of the input data:

```sql
    create table t0 (c0 TIMESTAMP);
    insert into t0 values ('2022-11-09');
    insert into t0 values ('2022-11-09');
    insert into t0 values ('1980-11-09');
```

The first query (`BETWEEN`) outputs a non-empty result set:

```
    v0.5.1 7c111322d
    Enter ".help" for usage hints.
    Connected to a transient in-memory database.
    Use ".open FILENAME" to reopen on a persistent database.
    D .read query
    ┌─────────────────────┐
    │         c0          │
    ├─────────────────────┤
    │ 1980-11-09 00:00:00 │
    └─────────────────────┘
```

This set does not produce the erronous result:

```sql
    create table t0 (c0 TIMESTAMP);
    insert into t0 values ('2022-11-09');
    insert into t0 values ('2022-11-09');
    insert into t0 values ('2022-11-09');

    -- output

    v0.5.1 7c111322d
    Enter ".help" for usage hints.
    Connected to a transient in-memory database.
    Use ".open FILENAME" to reopen on a persistent database.
    D .read query
    D
```

while this does:

```sql
    create table t0 (c0 TIMESTAMP);
    insert into t0 values ('2022-11-09');
    insert into t0 values ('2022-11-09');
    insert into t0 values ('2022-11-09');
    insert into t0 values ('2022-11-09');

    -- output

    v0.5.1 7c111322d
    Enter ".help" for usage hints.
    Connected to a transient in-memory database.
    Use ".open FILENAME" to reopen on a persistent database.
    D .read query
    ┌─────────────────────┐
    │         c0          │
    ├─────────────────────┤
    │ 2022-11-09 00:00:00 │
    └─────────────────────┘
    D
```

The queries were tested on the latest release as of 20 Oct 2022, `v0.5.1 7c111322d`, as well as on `https://shell.duckdb.org/`.

### To Reproduce

```sql
create table t0 (c0 TIMESTAMP);
insert into t0 values ('2022-11-09');
insert into t0 values ('2022-11-09');
insert into t0 values ('2022-11-09');
insert into t0 values ('2022-11-09');

-- query
select * from t0 where (t0.rowid between t0.c0 and 'a');          -- non empty result
select * from t0 where (t0.rowid >= t0.c0 and t0.rowid <= 'a');   -- empty result
```

### OS:

Linux

### DuckDB Version:

v0.5.1 7c111322d (latest release)

### DuckDB Client:

CLI

### Full Name:

Sankalp Gambhir

### Affiliation:

École Polytechnique Fédérale de Lausanne

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by sankalpgambhir** [comment]
The desired result is an equivalence of behaviour between the `BETWEEN` and the comparison per the documentation.  The types and query format were found via randomized testing using a modified version of [sqlancer](https://github.com/sqlancer/sqlancer), so they are not particularly relevant to an actively used database. 

The same queries return empty results on MySQL and SQLite (dbfiddle), so it is likely an issue with the implementation of `BETWEEN` in duckdb. I suspected a type error as well, but it seems weird that it occurs for certain inputs and not others, and after some varied testing, I have not been able to identify the root cause of the issue.

**Comment by Tishj** [comment]
So the BETWEEN and the COMPARISON do behave the same, unoptimized
But for the COMPARISON query we can strip out the entire evaluation, and for BETWEEN the optimizer isn't smart enough to do that

physical plan of the BETWEEN query:
```
(
	(
		CAST(rowid AS VARCHAR) <= 'a'
	) AND
	(
		CAST(rowid AS VARCHAR)
		>=
		CAST(c0 AS VARCHAR)
	)
)
```

As a side note, both of these queries in their unoptimized form have the issue that you try to cast a BIGINT -> TIMESTAMP, which is not a supported cast, so an exception is thrown

unoptimized comparison query:
```
(
	(
		CAST(rowid AS TIMESTAMP)
		>= c0
	) AND
	(
		rowid <= CAST('a' AS BIGINT)
	)
)

```
