### ISSUE TITLE
JSON extract (`->`) sometimes doesn't work if path is parametrized

### ISSUE THREAD

**Issue by jcrist** [duckdb/duckdb#5063]
### What happens?

The behavior of the JSON extract operator (`->`) varies if the path is parametrized or a literal.

### To Reproduce

This script reproduces the issue. I've run it on both 5.1 and dev.

```python
import duckdb

con = duckdb.connect()

con.execute("CREATE TABLE test(js JSON);")
con.execute('INSERT INTO test VALUES (\'{"a": 1, "b": 2}\')')

# Literal: OK
res = con.execute("SELECT js->'a' FROM test").fetchall()
print(res)

# Literal with cast: OK
res = con.execute("SELECT js->CAST('a' AS STRING) FROM test").fetchall()
print(res)

# Parameter: OK
res = con.execute("SELECT js->? FROM test", ("a",)).fetchall()
print(res)

# Parameter with Cast: Broken
res = con.execute("SELECT js->CAST(? AS STRING) FROM test", ("a",)).fetchall()
print(res)

# Parameter with Cast and 2nd parameter: OK
res = con.execute("SELECT js->CAST(? AS STRING), ? FROM test", ("a", 2)).fetchall()
print(res)
```

Output:

```
[('1',)]
[('1',)]
[('1',)]
[('{"a":1,"b":2}',)]
[('1', 2)]
```

### OS:

linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Jim Crist-Harif

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Thanks for the report. I will look into this when I get the time.
