### ISSUE TITLE
CARDINALITY on NULL map results in non-deterministic result

### ISSUE THREAD

**Issue by t-yuki** [duckdb/duckdb#5072]
### What happens?

When I use CARDINALITY function on NULL map (such as `CARDINALITY(CAST(NULL AS MAP(VARCHAR, INT)))`), it returns non-NULL and non-deterministic integer value.

Applying `HISTOGRAM` function on NULL data easily causes this case.

### To Reproduce

Example case:

```
WITH src AS ( VALUES (1, NULL) )
SELECT CARDINALITY(HISTOGRAM(val)) FROM src AS t(k, val)
```

More simple case:

```
SELECT CARDINALITY(CAST(NULL AS MAP(VARCHAR, INT)))
```

Expected Results:

`NULL` (I'm not sure whether it should be NULL or 0 but Presto returns NULL for this query)

Actual Results:

Non-deterministic integer value such as `9223372037609320895`, depending DuckDB running history. (100% for the first query)

Description:

It seems to be use of uninitialized value as the result.

### OS:

Windows 10 AMD64

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Yukinari Toyota

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lokax** [comment]
Maybe forgot to do special handling for NULL values

**Comment by carlopi** [comment]
It works as expected both in development or latest master, I think the linked PR (https://github.com/duckdb/duckdb/pull/5073) solved this problem.

Thanks @lokax.
