### ISSUE TITLE
Support hexadecimal integer notation

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#5074]
We should add support for hexadecimal integer notation. For example, this is how Postgres does it:

```sql
select x'FF'::int;
-- 255
```

**Comment by lokax** [comment]
It looks like only hexadecimal string to numerical type conversion needs to be implemented, or the parser needs to be modified?

**Comment by IanCal** [comment]
A hex string -> numerical type conversion alone without any parser improvements would be extremely useful to me as that's how a lot of my data is encoded. My current implementation is to either pull data out, convert and then process again in duckdb or use sql and list transforms (which works but is definitely not nice).

Either as a utility function or having the casting of varchar -> numeric understand the prefix 0x and read the number as hex.

**Comment by Mytherin** [comment]
Implemented now
