### ISSUE TITLE
Issue with GROUP BY + list() function, or incorrect error message

### ISSUE THREAD

**Issue by beaugunderson** [duckdb/duckdb#5078]
### What happens?

Hi there--I have a query where I'd like to get a `list` of person IDs for each contest ID, like this, and I'd like the list of person IDs to be ordered:

```sql
select
  contestId,
  count(personId),
  list(personId)
from entries
group by contestId
order by
  contestId,
  personId;
```

This is the error I get:

```
Error: near line 1: Binder Error: column "personId" must appear in the GROUP BY clause or be used in an aggregate function
```

This error does not make sense to me because `list()` is an aggregate function.

I did try to use a macOS CLI master build but the URL just returns a 404: https://github.com/duckdb/duckdb/suites/8933078189/artifacts/410086026

### To Reproduce

Execute a query like this:

```sql
select
  contestId,
  count(personId),
  list(personId)
from entries
group by contestId
order by
  contestId,
  personId;
```

### OS:

macOS

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Beau Gunderson

### Affiliation:

Individual

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by beaugunderson** [comment]
Noting that I have worked around the issue with a `WITH` statement, e.g. something like:

```sql
with sortedEntries as (
  select
    contestId,
    personId
  from entries
  order by
    contestId,
    personId
)
select
  count(personId),
  list(personId) as personList
from sortedEntries
group by contestId
```

**Comment by lokax** [comment]
`Order-By` happens after `Aggregation`. Aggregation operator returns result of grouping column and aggregate function, but there is no `personId` in the grouping column. So an exception is thrown.

**Comment by beaugunderson** [comment]
Ah, so the error message is incorrect?

**Comment by Alex-Monahan** [comment]
> `Order-By` happens after `Aggregation`. Aggregation operator returns result of grouping column and aggregate function, but there is no `personId` in the grouping column. So an exception is thrown.

Correct! I would just remove personid from your order by and your original query should work!

**Comment by beaugunderson** [comment]
The issue is that I need the lists ordered by personId though (because in the next stage I use them in a GROUP BY to find contests where the same exact people entered)--but the workaround above (the `WITH` statement) solved that and is performant 👍

**Comment by lokax** [comment]
Maybe you can try using
```SQL
-- returns a list of all regions in order of the "amount" column
SELECT LIST(region ORDER BY amount DESC) FROM sales;
```

**Comment by l1t1** [comment]
or

select a,array_agg(d order by b,c)d from t group by a

**Comment by l1t1** [comment]
```sql
select a,array_agg(d order by b,c)d  from (values(1,2,3,4),(1,3,2,1))t(a,b,c,d) group by a;
┌───┬────────┐
│ a │   d    │
├───┼────────┤
│ 1 │ [4, 1] │
└───┴────────┘
```

**Comment by Mytherin** [comment]
The error is correct, you are trying to order by `personId` which is not a GROUP BY or AGGREGATE column. `ORDER BY` happens after the aggregation, and thus no longer has access to the `personId` column.

As mentioned by others here what you are likely looking for is an ordered aggregation.
