### ISSUE TITLE
Feature request: Create enums from values in tables

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#5080]
### Discussed in https://github.com/duckdb/duckdb/discussions/5037

<div type='discussions-op-text'>

<sup>Originally posted by **ajfriend** October 20, 2022</sup>
It would be nice if there were some syntax to allow users to create enums from string values found in tables. For example, maybe something like:

```sql
CREATE TYPE node_enum AS ENUM (select node_name from tbl_graph);
```

This would allow me to get much of the way towards the "Automatic Storage Encoding" idea described in this blog post: https://duckdb.org/2021/11/26/duck-enum.html#what-about-the-sequels. I would just be doing some of the work manually, rather than it happening invisibly to the user.</div>

**Comment by lokax** [comment]
Is anyone working on this? If not, I am pleased to implement it.

**Comment by Mytherin** [comment]
Not yet, feel free!

**Comment by ajfriend** [comment]
Would this syntax be able to handle duplicated entries in the query result? Or would the user need to deduplicate ahead of time?

**Comment by Tishj** [comment]
I'd say this function should probably deduplicate
Otherwise it would need to verify that the input is distinct anyways and that would be doing half the work to deduplicate anyways
