### ISSUE TITLE
Various Issues with Null Characters in Query Parameters

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#5091]
### What happens?

When a null character is part of a query parameter bad things happen. Different behavior appears to happen depending on the client.

With the CLI it appears that the input string is terminated as though you were missing a `;` on a statement. Here's an example. While it doesn't get copied across, there is a NULL character between the two "r"s in the query parameter value.
```
$ ./build/release/duckdb 
v0.5.2-dev1203 575117f6be
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table T1(id integer, name varchar, value integer);
D copy T1 from '/Users/michaelalbers/issues/15511_duckdb-uncaught-exception/data.csv' (HEADER true, DELIMETER ',');
D select * from T1;
┌────┬───────┬───────┐
│ id │ name  │ value │
├────┼───────┼───────┤
│ 1  │ Bob   │ 22    │
│ 2  │ Debra │ 23    │
└────┴───────┴───────┘
D PREPARE S1 AS SELECT * from T1 where name = $1;
D execute S1('yearr');
> 
> ;
> ;
> );
> 
> 
> 
> ');
D 
```

With the JDBC things are much worse. An uncaught exception is thrown which calls `std::terminate` and causes the JVM to terminate. On MacOS this looks like
```
libc++abi: terminating with uncaught exception of type duckdb::Exception: String value is not valid UTF8
```

### To Reproduce

The CLI example is shown above. To reproduce the JDBC issues, clone https://github.com/michaeljohnalbers/duckdb-issue-reproduction and checkout commit 2667e23 (HEAD as of this writing). Follow the instruction in the README file.

### OS:

MacOS, Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

JDBC

### Full Name:

Michael Albers

### Affiliation:

Mode

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Should be fixed now
