### ISSUE TITLE
Using "with duckdb.connect" causes silent crashes on invalid SQL (and perhaps other kinds of errors)

### ISSUE THREAD

**Issue by cebaa** [duckdb/duckdb#5104]
### What happens?

Using `with duckdb.connect` causes silent crashes on invalid SQL (and perhaps other kinds of errors).

### To Reproduce

This:

```
import ducckdb

print(duckdb.__version__)

with duckdb.connect() as con:
  print('before')
  con.execute('select 1')
  print('after')

with duckdb.connect() as con:
  print('before')
  con.execute('invalid')
  print('after')
```

produces this output:

```
0.5.1
before
after
before
```

There's a missing `after` for the second `with` block and there are no exceptions shown, it fails silently.

### OS:

linux

### DuckDB Version:

0.5.1

### DuckDB Client:

python

### Full Name:

Cebaa

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Pretty sure that's just being caused by not rethrowing errors in this function: https://github.com/duckdb/duckdb/blob/efa7dfa643290010cca95b93b71f7a87a2772f59/tools/pythonpkg/src/pyconnection.cpp#L717-L721
