### ISSUE TITLE
Feature request: creating an ENUM from a query result

### ISSUE THREAD

**Issue by ajfriend** [duckdb/duckdb#5106]
Creating this as recommended by @pdet in https://github.com/duckdb/duckdb/discussions/5037#discussioncomment-3948548_

Would it be possible to have some syntax for creating an ENUM from a query result? Maybe something like:

```sql
CREATE TYPE node_enum AS ENUM (select node_name from tbl_graph);
```

**Comment by Mytherin** [comment]
The issue was already created here: #5080

**Comment by ajfriend** [comment]
OK, awesome. I missed that. I'll close this one. Thanks!
