### ISSUE TITLE
`row_number` in `read_parquet` sometimes doesn't match with order in file

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#5118]
### What happens?

This bug is quite hard to describe and very hard to reproduce deterministically. When using `row_number` in a  `from read_parquet(...)` in a `with` clause, the order of the results might depend on subsequent `with`s that happen afterwards and use `from` the first `with`.

I am not sure this could be considered a bug, since I guess SQL tables aren't strictly required to have an underlying order, and something like `order by row_number() over()` is I guess also not guaranteed to preserve the storage order of the table if it had any, but with `read_parquet`, I think it'd be quite expected that the order of results from `select` should correspond with the order in the `parquet` file - doing the same operation with `polars` or `pandas` for example would preserve the order.

This only happens when:
* There's more than one subsequent `with` doing aggregations on the first `with` and a final `select` taking the exact same rows from the first `with`.
* The amount of rows is very large.
* The columns have missing values and varchar types.

### To Reproduce

I am unable to produce a minimally reproducible example, but a full example would go as follows:
```sql
with tbl0 as (
    select
        ...
        , coalesce(...)
        , row_number() over() as row_num
    from read_parquet(...)
    where ...
)
,  tbl1 as (
    select
        ...
    from tbl0
    group by ...
)
,  tbl2 as (
    select
        ...
    from tbl0
    group by ...
)
...
select
    tbl0...
    , case when tbl1... /*optional*/
    , case when tbl2... /*optional*/
from tbl0
join tbl1 ... /*optional*/
join tbl2 ... /*optional*/
...
order by tbl0.row_num
```

(Assuming that the last select returns the exact same rows that are present in `tbl0`)

Then, the resulting order would be different depending on whether the `with tbl1..n`are included in the query or not, regardless of whether the `join` and `select` from `tbl1..n` are present.

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Probably has to do with parallel reading of the parquet file. We just added a new flag to the parquet reader, #5084. Perhaps try `read_parquet('some-file.parquet', file_row_number=true)`?

**Comment by Mytherin** [comment]
What is in the `WHERE` clause of `tbl0` exactly? Certain conditions such as `IN` clauses with subqueries can be translated to joins which will re-order rows.

**Comment by david-cortes** [comment]
Thanks, gave a try to the latest commit using `file_row_number` and it worked correctly.

The query for `tbl0` was BTW just doing filters like `is not null`, `not isnan(...)`, `col >= ...`, etc.
