### ISSUE TITLE
Installation instructions for bleeding edge are incomplete

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#5119]
### What happens?

The DuckDB webpage has [instructions for installing the latest bleeding edge version](https://duckdb.org/docs/installation/), which for Python, amount to something like this:
```
pip install duckdb --pre --upgrade
```

However, the PyPI files that are uploaded for the latest commit at the time of writing (a) do not include linux wheels, (b) do not include a source distribution; thus one doesn't get the latest version when trying to follow the instruction on a linux system.

One can lurk into the github actions yaml file to see what are the right cmake options that one needs to pass to build the python package after cloning the github repository, but would be nice if those were mentioned in the webpage.

### To Reproduce

```shell
pip install duckdb --pre --upgrade
```
```shell
python -c "import duckdb; print(duckdb.__version__)"
```
(will not get the latest version if ran on linux)

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hiya, the issue here is that the DuckDB build takes several hours, and so all the various artifacts are not uploaded simultaneously - if you look at the second or third latest build, you'll see that it contains all the expected artifacts

**Comment by david-cortes** [comment]
I still think it'd be very helpful to have instructions to build from the GH repository in the docs, since commits are constantly being pushed and only a few past development versions are kept in PyPI. It'd be especially helpful when testing whether some issue is solved by a new commit, as it can take a very long time before the CI pipelines push an artifact for the right platform or before they push the source version.

**Comment by david-cortes** [comment]
Reframed as feature request: https://github.com/duckdb/duckdb/discussions/6890
