### ISSUE TITLE
Can't query files over HTTP if there is a redirect

### ISSUE THREAD

**Issue by freddyaboulton** [duckdb/duckdb#5121]
### What happens?

Cross posting from discord at the suggestion of one of the moderators:

I'm trying to query parquet files on the huggingface hub with duckdb. This is the [file](https://huggingface.co/datasets/deepmind/code_contests/blob/main/data/test-00000-of-00001-9c49eeff30aacaa8.parquet).

When I first try to do it with duckdb, I get a 403 error, even though a get request with the requests package is successful. 

It returns a 302 status code (noting a redirect). 

I then tried to connect duckdb to the redirected url but I'm getting a CatalogError. 

After speaking with the huggingface engineers, they said the redirect url is 180 characters long and it it could be something about httpfs not supporting http headers that long or truncating them.

Any help would be appreciated!

### To Reproduce

Use this colab notebook: https://colab.research.google.com/drive/1S_sw-QZjnmQ1ta6O7NpN47Ik3luVdYbX#scrollTo=-yI9vECsc3he

### OS:

linux

### DuckDB Version:

0.5.1

### DuckDB Client:

python

### Full Name:

Freddy Boulton

### Affiliation:

Hugging Face

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
probably related to https://github.com/duckdb/duckdb/issues/4964

**Comment by samansmink** [comment]
See also update on previously linked issue. I also think the server from your example file does not support range requests:
```
D select * from "https://huggingface.co/datasets/deepmind/code_contests/blob/main/data/test-00000-of-00001-9c49eeff30aacaa8.parquet";
Error: Invalid Error: HTTP GET error: Content-Length from server mismatches requested range, server may not support range requests.
```

**Comment by lhoestq** [comment]
You should use this URL instead ;)
https://huggingface.co/datasets/deepmind/code_contests/resolve/main/data/test-00000-of-00001-9c49eeff30aacaa8.parquet

**Comment by samansmink** [comment]
Okay its actually not sure that this is related to the other issue. The above url does consistently fail and seems related to the way httplib decodes values from the response headers

**Comment by freddyaboulton** [comment]
Thank you for the fix!
