### ISSUE TITLE
duckdb segfaults when reading from pyarrow recordbatchreader

### ISSUE THREAD

**Issue by f3zhead** [duckdb/duckdb#5143]
### What happens?

when i use duckdb to `select *` from a pyarrow RecordBatchReader (created from a pyarrow.csv.CSVStreamingReader that reads a 371 MB csv file), i get a segmentation fault

### To Reproduce

link to gzipped data: https://github.com/f3zhead/crap/blob/main/indiv.txt.gz
(i apologize in advance, but it's better than downloading an 8gb csv file with a bunch of other stuff)

to create the table
```sql
CREATE TABLE indiv (
	committee_id VARCHAR NOT NULL, 
	amendment_indicator VARCHAR, 
	report_type VARCHAR, 
	transaction_pgi VARCHAR, 
	image_num VARCHAR, 
	transaction_type VARCHAR, 
	entity_type VARCHAR, 
	name VARCHAR, 
	city VARCHAR, 
	state VARCHAR, 
	zip_code VARCHAR, 
	employer VARCHAR, 
	occupation VARCHAR, 
	transaction_date date, 
	transaction_amount INTEGER, 
	other_id VARCHAR, 
	transaction_id VARCHAR, 
	file_num INTEGER, 
	memo_cd VARCHAR, 
	memo_text VARCHAR, 
	sub_id VARCHAR NOT NULL, 
);
```
to get the segfault
```python
import duckdb
import pyarrow
import pyarrow.csv as pv

data_file = "indiv.txt"

schema = {
    "committee_id": pyarrow.string(),
    "amendment_indicator": pyarrow.string(),
    "report_type": pyarrow.string(),
    "transaction_pgi": pyarrow.string(),
    "image_num": pyarrow.string(),
    "transaction_type": pyarrow.string(),
    "entity_type": pyarrow.string(),
    "name": pyarrow.string(),
    "city": pyarrow.string(),
    "state": pyarrow.string(),
    "zip_code": pyarrow.string(),
    "employer": pyarrow.string(),
    "occupation": pyarrow.string(),
    "transaction_date": pyarrow.timestamp("s"),
    "transaction_amount": pyarrow.int32(),
    "other_id": pyarrow.string(),
    "transaction_id": pyarrow.string(),
    "file_num": pyarrow.int32(),
    "memo_cd": pyarrow.string(),
    "memo_text": pyarrow.string(),
    "sub_id": pyarrow.string(),
}
csv_read_options = pv.ReadOptions(column_names=list(schema.keys()))
csv_parse_options = pv.ParseOptions(
    delimiter="|",
    invalid_row_handler=(lambda invalid_row: "skip"),
    quote_char=False,
)
csv_convert_options = pv.ConvertOptions(
    column_types=schema,
    timestamp_parsers=["%m%d%Y", "%-m%d%Y", "-%m/%d/%Y"],
)
quack = pv.open_csv(
    data_file,
    read_options=csv_read_options,
    parse_options=csv_parse_options,
    convert_options=csv_convert_options,
)
record_batch = pyarrow.RecordBatchReader(schema, quack)

conn = duckdb.connect("test.db")
conn.execute("insert into indiv select * from record_batch")
```
it also segfaults if you do 'create table indiv as select * from record_batch' instead of using the create table statement above.

### OS:

Arch Linux

### DuckDB Version:

v0.5.1 7c111322d

### DuckDB Client:

Python

### Full Name:

Franklin Liu

### Affiliation:

none :)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by f3zhead** [comment]
I was able to reproduce this on nixos with duckdb version 0.5.1

**Comment by lupko** [comment]
@f3zhead please be aware that you should not be creating new instances of RecordBatchReader using its constructor. This is explicitly highlighted in PyArrow docs. The open_csv() method seems to return CSVStreamingReader which already implement RBR. 

Have you tried using the `quack` directly instead of wrapping in RBR?

**Comment by f3zhead** [comment]
Oh I didn't know that, sorry! (I didn't really read the docs, will make sure to do that next time.) The reason I wrapped `quack` in a RecordBatchReader was that when I tried selecting from it I got a `duckdb.InvalidInputException: Invalid Input Error: Python Object CSVStreamingReader not suitable for replacement scans` and thought I wasn't supposed to do that.

**Comment by f3zhead** [comment]
Just tested creating the reader with `pyarrow.RecordBatchReader.from_batches(schema, quack)`, it still segfaults

**Comment by hannes** [comment]
@pdet?

**Comment by lupko** [comment]
@f3zhead the problem is in the `pyarrow.RecordBatchReader.from_batches(schema, quack)`. The `schema` that you pass to it is not a valid Arrow schema (it is a python dict). I have tried your example with:

```
# notice the use of quack.schema here
record_batch = pyarrow.RecordBatchReader.from_batches(quack.schema, quack)

conn = duckdb.connect("test.db")
conn.execute("create table indiv as select * from record_batch")
print(conn.execute("select distinct city from indiv").fetchall())
```

No more segfaults. 

Note: I have modified the initial load to use CTAS to avoid fiddling with the table DDL. This was also segfaulting when the RBR was not created correctly (e.g. wrong schema object or RBR created using constructor call with correct schema).

**Comment by lupko** [comment]
btw what I find as a somewhat surprising behavior of DuckDB is that the CSVStreamingReader - a subtype of RecordBatchReader - cannot be used directly.

**Comment by Mause** [comment]
@lupko the previous type checking implementation was quite basic (literally checking the `__name__` of the `__class__`), and it has been improved since in the latest dev versions

**Comment by lupko** [comment]
@Mause thank you for the info, that's great news.

**Comment by pdet** [comment]
As pointed out before, the segfault happens on the arrow side when trying to actually create the data.
You can force that by trying to convert the recordbatchreader to a table 
` tbl = pa.Table.from_batches(record_batch)`

I think they probably want to error that instead of segfaulting. @f3zhead maybe open an issue on their issue tracker?

**Comment by lidavidm** [comment]
On the Arrow side, please see https://issues.apache.org/jira/browse/ARROW-18229

**Comment by f3zhead** [comment]
> @f3zhead the problem is in the `pyarrow.RecordBatchReader.from_batches(schema, quack)`. The `schema` that you pass to it is not a valid Arrow schema (it is a python dict). I have tried your example with:
> 
> ```
> # notice the use of quack.schema here
> # alternativelly, you can create proper Schema from your dict via pyarrow.schema(schema) and use that instead
> record_batch = pyarrow.RecordBatchReader.from_batches(quack.schema, quack)
> 
> conn = duckdb.connect("test.db")
> conn.execute("create table indiv as select * from record_batch")
> print(conn.execute("select distinct city from indiv").fetchall())
> ```
> 
> No more segfaults.
> 
> Note: I have modified the initial load to use CTAS to avoid fiddling with the table DDL. The CTAS approach was segfaulting same as your original approach when the RBR was not created correctly (e.g. wrong schema object or RBR created using constructor call with correct schema).
I see, thank you! Also thanks @lidavidm for filing the issue on pyarrow!
