### ISSUE TITLE
Bug in current_memory calculation of buffer manager

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb#5145]
### What happens?

When running a query involving sort code, then the current_memory size increases by 24 bytes, even though it should not change.

### To Reproduce

```c++
TEST_CASE("Test buffer manager", "[art][.]") {
	auto storage_database = TestCreatePath("storage_test");
	auto config = GetTestConfig();
	// make sure the database does not exist
	DeleteDatabase(storage_database);
	DuckDB db(storage_database, config.get());
	Connection con(db);

	idx_t current_memory = 0;
	auto &buffer_manager = BufferManager::GetBufferManager(*con.context);
	D_ASSERT(buffer_manager.GetUsedMemory() == current_memory);

	REQUIRE_NO_FAIL(con.Query("CREATE TABLE leaf AS SELECT 42 AS id FROM range(42);"));
	current_memory = buffer_manager.GetUsedMemory();

	REQUIRE_NO_FAIL(con.Query("SELECT * FROM leaf ORDER BY 1;"));
	D_ASSERT(buffer_manager.GetUsedMemory() == current_memory);
}
```

### OS:

iOS

### DuckDB Version:

Master

### DuckDB Client:

CLI/ test runner

### Full Name:

Tania Bogatsch

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Is it possible that the sort (temporarily) requires extra memory, and that's the footprint we're seeing?
