### ISSUE TITLE
add translate function 

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5156]
### What happens?

duckdb needs add the funciton that postgresql 15 
it replace parameter1 each char in parameter 2 with that postision in parameter 3

### To Reproduce

```
D select translate('12','2','a')x;
Error: Catalog Error: Scalar Function with name translate does not exist!
Did you mean "replace"?
LINE 1: select translate('12','2','a')x;
```
postgresql 15
```
postgres=# select translate('12','2','a')x;
 x
----
 1a
```

### OS:

windows 7

### DuckDB Version:

0.51

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Is this just an alias for the existing “replace” function?

**Comment by l1t1** [comment]
translate ( string text, from text, to text ) → text

Replaces each character in string that matches a character in the from set with the corresponding character in the to set. If from is longer than to, occurrences of the extra characters in from are deleted.

translate('12345', '143', 'ax') → a2x5

https://www.postgresql.org/docs/15/functions-string.html

**Comment by l1t1** [comment]
```
D select translate('12345', '143', 'ax');
Error: Catalog Error: Scalar Function with name translate does not exist!
Did you mean "replace"?
LINE 1: select translate('12345', '143', 'ax');
               ^
D select replace('12345', '143', 'ax');
┌───────────────────────────────┐
│ replace('12345', '143', 'ax') │
├───────────────────────────────┤
│ 12345                         │
└───────────────────────────────┘
```

**Comment by Tishj** [comment]
Ah sounds like a nice little function to implement, probably a "good first issue"

**Comment by zhouliqi** [comment]
hey, i would like to work on this issue but im new to this. I think that I should
1. add a `TranslateFun` struct in `string_function.hpp`
2. add `Register` in `string_function.cpp`
3. implemention translate function in  `translate.cpp` which will be created in `src/function/scalar/string`
4. write test case in `test_translate.test`

Am I right?

**Comment by lokax** [comment]
@zhouliqi you are right:bowtie:

**Comment by zhouliqi** [comment]
Okay!

**Comment by l1t1** [comment]
https://github.com/duckdb/duckdb/discussions/5179

**Comment by zhouliqi** [comment]
Maybe I'm in trouble. How can I process unicode character, can someone give me a hint?

**Comment by Tishj** [comment]
> Maybe I'm in trouble. How can I process unicode character, can someone give me a hint?

I don't think a first implementation should support unicode (and just support ASCII for now) and that would be better left for a follow up PR, I'm not sure how much more work that would be though, just that the performance would be worse. So maybe it should even be a separate variant.

Regardless, to answer your question, Mytherin recently made a change to `len` to support unicode, here's the PR <https://github.com/duckdb/duckdb/pull/5028>
In the changed files you can find a lot utility functions that will help :)

**Comment by Mytherin** [comment]
> Regardless, to answer your question, Mytherin recently made a change to len to support unicode, here's the PR https://github.com/duckdb/duckdb/pull/5028

Actually that PR removes support for a more advanced unicode feature (grapheme clusters), I don't think we ever had a length that did not support unicode :)

**Comment by zhouliqi** [comment]
It seems that it can't pass CI [locally on my fork](https://github.com/zhouliqi/duckdb/actions).

**Comment by Mytherin** [comment]
You should work in a branch (not on master), and fetch tags from upstream into your fork.

**Comment by jjerphan** [comment]
Has https://github.com/duckdb/duckdb/pull/5212 resolved this issue?

**Comment by Mytherin** [comment]
Yes, this is supported in the feature branch now
