### ISSUE TITLE
Arrow type check too strict

### ISSUE THREAD

**Issue by changhiskhan** [duckdb/duckdb#5163]
### What happens?

This commit on master:
https://github.com/duckdb/duckdb/commit/b689caf4e9e934de5808cfeba4b5d980906d4f1b
changes DuckDB behavior to accept only Arrow InMemoryDataset and FileSystemDataset interfaces.

`FileSystemDataset` is not strictly speaking  "public API". E.g., it it not part of the pxd in Arrow: https://github.com/apache/arrow/blob/master/python/pyarrow/_dataset.pxd

The problem is that we're creating subclasses of Dataset that would now be broken by this change when released. Would it be possible to relax this to subclasses of `Dataset` instead?

### To Reproduce

on master:

setup:
```shell
pip install duckdb pylance
```

```python
import duckdb
import lance

uri = "s3://eto-public/datasets/oxford_pet/oxford_pet.lance"
pet = lance.dataset(pet)
duckdb.query("SELECT split, count(1) FROM pet GROUP BY 1")
```

This breaks on master but works in current release.

### OS:

ubuntu

### DuckDB Version:

master

### DuckDB Client:

python

### Full Name:

Chang She

### Affiliation:

Eto Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Sure that would be possible, the aim of the PR this is part of was initially to make it easier to duck-type existing datatypes we already accept.
So it's far from the goal to make it harder to duck-type / extend support.

For my understanding, that would be <https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html> that we're talking about right?

One problem I remember from that PR is that Arrow itself is pretty strict on what it accepts as a valid type to some of the functions we're using from them.
That's partly what inhibited me from making the Protocol work.

**Comment by changhiskhan** [comment]
thanks @Tishj . 

Yes, https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html is the interface I was referring to.

> One problem I remember from that PR is that Arrow itself is pretty strict on what it accepts as a valid type to some of the functions we're using from them.

yeah, there's some rough edges there for sure. For this case, I think we don't need to try to make it work with the Protocol, just change the instanceof check from InMemoryDataset and FileSystemDataset => Dataset?


Thanks again for being open to discussion here.
