### ISSUE TITLE
`epoch` is not documented

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#5167]
### What happens?

The docs list timestamp functions:
https://duckdb.org/docs/sql/functions/timestamp

Searching in the issue tracker, there is a function `epoch` which is the inverse of `epoch_ms`: https://github.com/duckdb/duckdb/issues/1920#issuecomment-871978142

But this function is not listed in the docs above.

### To Reproduce

https://duckdb.org/docs/sql/functions/timestamp

### OS:

Linux

### DuckDB Version:

0.5.1

### DuckDB Client:

-

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Would you mind raising an issue over in https://github.com/duckdb/duckdb-web/ ? Since this is purely documentation related, we prefer to have issues related to the documentation there instead

**Comment by david-cortes** [comment]
Moved to the other repository: https://github.com/duckdb/duckdb-web/issues/360
