### ISSUE TITLE
No way to disable or configure colours in the CLI

### ISSUE THREAD

**Issue by arp242** [duckdb/duckdb#5175]
There doesn't seem to be any way to configure or disable colours in the CLI. This is a bit of an issue because the bright colours don't work well on lighter backgrounds, and are pretty hard to read and distracting. To give an impression:

![cap-2022-11-02T21:24:29_border](https://user-images.githubusercontent.com/1032692/199597875-f6bd821e-49b3-41c9-bb09-009c2ffff9d2.png)

I looked for an option to just disable the colours in the documentation and a bit of grepping in the source, but I can't really find anything other than the `-batch` option, but this also disables a lot of other stuff.

Something like a `-no-color` flag would be enough; don't necessarily need to be able to configure colours.

---

I downloaded the latest version of the CLI from GitHub:

    D pragma version;
    ┌─────────────────┬───────────┐
    │ library_version │ source_id │
    ├─────────────────┼───────────┤
    │ v0.5.1          │ 7c111322d │
    └─────────────────┴───────────┘

**Comment by Mytherin** [comment]
`.highlight off` should turn off the syntax highlighter. You can configure the colors as well:

```sql
D .constant
Error: Expected usage: .constant [red|green|yellow|blue|magenta|cyan|white|brightblack|brightred|brightgreen|brightyellow|brightblue|brightmagenta|brightcyan|brightwhite]
D .keyword
Error: Expected usage: .keyword [red|green|yellow|blue|magenta|cyan|white|brightblack|brightred|brightgreen|brightyellow|brightblue|brightmagenta|brightcyan|brightwhite]
```

These don't seem to be part of the `.help` - we should add them there.

The shell reads `~/.duckdbrc` for commands on start-up which is where you can put any customizations you want to always have enabled.

**Comment by arp242** [comment]
Ah cheers!
