### ISSUE TITLE
Support binary integer notation

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#5196]
In the same trend as #5074 

We should also support :
```sql
select b'01010100'::int;
-- 84
```

Or as a first step, similar to #5160 we can add a casting rule for it first
```sql
select '0b01010100'::int;
-- 84
```

For no reason whatsoever I made this cursed (probably not very efficient) sql query to do this conversion for anyone looking for this functionality before it's implemented into the system:
```sql
with binary_string as (select '011010110101' as str)
select list_sum([ (CASE WHEN str[i+1] = '0' THEN 0 ELSE 1 END) * (2 ** (len(str)-(i+1))) for i in range(len(str))]) from binary_string
-- 1717.0
```

**Comment by jardayn** [comment]
A general bit type would also be great
