### ISSUE TITLE
`select factorial(45)a` reports `Error: Out of Range Error: Overflow in HUGEINT multiplication!`

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5201]
### What happens?

`select factorial(45)a` reports `Error: Out of Range Error: Overflow in HUGEINT multiplication!`

### To Reproduce

```
select factorial(45)a;

Error: Out of Range Error: Overflow in HUGEINT multiplication
```
if run it in  postgresql 15
```
postgres=# select factorial(45)a;
                             a
-----------------------------------------------------------
 119622220865480194561963161495657715064383733760000000000
(1 行记录)

```

### OS:

Windows 7

### DuckDB Version:

0.51

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
This is expected behavior, not a bug. We have no immediate intention to support arbitrarily large numbers.
