### ISSUE TITLE
`describe` ignores quoted names

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#5203]
### What happens?

`DESCRIBE` appears to ignore quoted names and assumes dots are levels in a schema hierarchy.

I have not tried this on master yet.

### To Reproduce

```
❯ duckdb
v0.0.1-dev0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table "a.b.c" (x int);
D select count(*) from "a.b.c";
┌──────────────┐
│ count_star() │
├──────────────┤
│ 0            │
└──────────────┘
D describe "a.b.c";
Error: Parser Error: Expected schema.entry or entry: too many entries found
```

### OS:

NixOS x86_64

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I had a quick look on friday, we use QualifiedName::Parse here after the quotes have already been removed
