### ISSUE TITLE
total_uncompressed_size field is not set in Parquet metadata

### ISSUE THREAD

**Issue by chumbert2** [duckdb/duckdb#5209]
### What happens?

In the generated Parquet files, the metadata field `total_uncompressed_size` is not set (always 0).

### To Reproduce

```
cat <<EOF > test.csv
FlightDate|UniqueCarrier|OriginCityName|DestCityName
1988-01-01|AA|New York, NY|Los Angeles, CA
1988-01-02|AA|New York, NY|Los Angeles, CA
1988-01-03|AA|New York, NY|Los Angeles, CA
EOF
```

```
cat <<EOF > test.sql
CREATE TABLE tbl AS SELECT * FROM 'test.csv';
COPY tbl TO 'output.parquet' (FORMAT PARQUET);
SELECT total_compressed_size,total_uncompressed_size FROM parquet_metadata('output.parquet');
EOF
```

```
duckdb -markdown < test.sql
```

| total_compressed_size | total_uncompressed_size |
|-----------------------|-------------------------|
| 37                    | 0                       |
| 49                    | 0                       |
| 59                    | 0                       |
| 62                    | 0                       |

### OS:

Linux x86

### DuckDB Version:

v0.5.2-dev1616 2da7bf4489

### DuckDB Client:

CLI

### Full Name:

Cyril Humbert

### Affiliation:

Air Liquide

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Indeed this field seems to be required. Does it being 0 cause issues for you?

https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L737

**Comment by chumbert2** [comment]
No, not really. I don't know how this field is required (R with arrow package seems to set it).
Actually I notice it because it caused an error with `parquet-tools` utility (https://pypi.org/project/parquet-tools/).

```
parquet-tools inspect output.parquet
# ...
#col_compression_space_saving_ratio = 1 - (col_meta.total_compressed_size / col_meta.total_uncompressed_size)
#ZeroDivisionError: division by zero
```

But this would be easy to present the metadata differently to handle this case.
