### ISSUE TITLE
In operator doesn't respect collation

### ISSUE THREAD

**Issue by aaron-meyers** [duckdb/duckdb#5215]
### What happens?

The IN operator doesn't appear to respect the collation for string values.

### To Reproduce

I have a table that includes a 'title' column with a value 'EDENS ZERO' in one of the rows.

This query returns that row:
```SQL
select title from netflix_ja_titles where title ='edens zero';
```

But this query returns nothing:
```SQL
select title from netflix_ja_titles where title in('edens zero');
```

I would expect these to behave identically.

### OS:

Windows 11 22621.674 x64

### DuckDB Version:

v0.5.1 7c111322d

### DuckDB Client:

duckdb cli

### Full Name:

Aaron Meyers

### Affiliation:

Microsoft (although my current use of duckdb is for a personal project)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by aaron-meyers** [comment]
I forgot to mention the collation I'm using - I started my session with this:

```SQL
PRAGMA default_collation='NOCASE.NOACCENT';
```

**Comment by lokax** [comment]
This is because `PushCollation` is not called when binding `ExpressionType::CompareIn` for VARCHAR

**Comment by djouallah** [comment]
related to https://github.com/duckdb/duckdb/issues/4330

**Comment by omo** [comment]
Also linking #604 for the reference.

**Comment by djouallah** [comment]
This is a clear limitation!!!

**Comment by aaron-meyers** [comment]
#604 was reopened, looks like this should get fixed as part of that issue. So I think this can remain closed.
