### ISSUE TITLE
calling read_csv_auto with a parquet file segfaults

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#5233]
### What happens?

When calling `read_csv_auto` with a parquet file duckdb segfaults.

On master there's no segfault, but I couldn't find any PR addressing this issue specifically.

Feel free to close if this can be considered fixed.

### To Reproduce

Generate some data using pandas and numpy:

```
In [1]: import numpy as np

In [2]: import pandas as pd

In [3]: df = pd.DataFrame({"a": np.random.randn(100)})

In [4]: df.to_parquet("df.parquet")
```

Fire up duckdb and try to read the `df.parquet` with `read_csv_auto`:

```
❯ duckdb <<< "select * from read_csv_auto('df.parquet')"
zsh: segmentation fault (core dumped)  duckdb <<< "select * from read_csv_auto('df.parquet')"
```

### OS:

NixOS x86_64

### DuckDB Version:

0.5.1

### DuckDB Client:

CLI

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
We had a crash in the CSV reader auto-detection that was fixed this release related to carriage returns (see #5083). It is likely that that was the issue and that this has been fixed as a result of that. Good idea to throw random binary files into the CSV reader for testing purposes, though!

**Comment by cpcloud** [comment]
Awesome! Thanks everyone. I'll close this out and if it pops up again I'll open a new issue.
