### ISSUE TITLE
Surprising Behavior Regarding NOT NULL Query on Pandas Dataframe With pd.NA values

### ISSUE THREAD

**Issue by sbadithe** [duckdb/duckdb#5238]
### What happens?

Querying a dataframe with a `pd.NA` value for NOT NULL values does not exclude the `pd.NA` value.

### To Reproduce

Here is a script to reproduce the issue. The pandas version is `1.4.4`. The numpy version is `1.22.4`. 

```
import duckdb 
import pandas as pd 
import numpy as np 

df = pd.DataFrame()
df['a'] = [pd.NA, np.nan, None, "text", "text"] 
df['idx'] = [0, 1, 2, 3, 4]

print(df['a'].dtype)

con = duckdb.connect()
results = con.execute("SELECT * FROM df WHERE a IS NOT NULL").df()

print(f"{results}")
```

Here are the results: 

<img width="189" alt="Screen Shot 2022-11-07 at 12 46 30 PM" src="https://user-images.githubusercontent.com/60528327/200412033-e8c83048-9c77-4012-a227-2028a1f4dfcf.png">

Thanks!

### OS:

macOS 12.6, aarch64

### DuckDB Version:

1.5.1

### DuckDB Client:

Python

### Full Name:

Shripad Badithe

### Affiliation:

Alteryx

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hi thanks for raising the issue.

I only just realized this concerns the experimental NA value in pandas.
We don't support that yet, so this likely gets transformed to string when inserted currently
