### ISSUE TITLE
exit code 139 (interrupted by signal 11: SIGSEGV) when increasing inputdata

### ISSUE THREAD

**Issue by bkersbergen** [duckdb/duckdb#5247]
### What happens?

The duckdb query crashes with a 'exit code 139 (interrupted by signal 11: SIGSEGV)' when using larger input datasets.
Line 124 controls the amount of 'sessions'. It fails with its current value of 1.000.000 which generates about 10M input rows for duckdb. When reducing this value to 100.000 the query executes successful.

I was not able to reduce the length of the query and still produce the error message.

Memory usage increases to 12GB+ when running this query.

Reproduced with duckdb 0.5.1 and duckdb-0.5.2.dev1844

### To Reproduce

[preprocess_duckdb.py.zip](https://github.com/duckdb/duckdb/files/9960104/preprocess_duckdb.py.zip)

`python preprocess_duckdb.py`

### OS:

iOS

### DuckDB Version:

duckdb-0.5.2.dev1844

### DuckDB Client:

python

### Full Name:

barrie kersbergen

### Affiliation:

bolcom

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I had a look and could not reproduce the crash on my machine. We recently performed a number of fixes for problems that would occur when running queries close to the memory limit (see #5263). Could you verify that the issue still happens for you on the recently released v0.6.0?

**Comment by bkersbergen** [comment]
I can confirm that this issue is fixed by version v0.6.0.
Thank you!
