### ISSUE TITLE
Segfault with prepared statement (unittest --force-reload --force-storage)

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#5252]
### What happens?

Running a unittest with a specific prepared statement and force reload and force storage segfaults. Just documenting it here - not sure how to fix it myself

### To Reproduce

```
statement ok
create table test as select 42 i

statement ok
prepare q1 as SELECT cast(? AS VARCHAR) FROM test

query T
execute q1('oops')
----
oops
```

UBSAN output:
```
/Users/laurens/git/duckdb/master-duckdb/src/function/table/table_scan.cpp:394:35: runtime error: member access within address 0x00010ab0a680 which does not point to an object of type 'duckdb::CatalogEntry'
```

### OS:

MacOS 13 (Ventura)

### DuckDB Version:

master

### DuckDB Client:

unittest

### Full Name:

Laurens Kuiper

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Related to #5132 ?

**Comment by lnkuiper** [comment]
@Tishj Ah sorry, had not seen that. It is indeed the same issue
