### ISSUE TITLE
Creating table from pandas dataframe produces incorrect results

### ISSUE THREAD

**Issue by tbenthompson** [duckdb/duckdb#5253]
### What happens?

I create a table from a pandas DataFrame. When I select the data back out, the data is different from the input.

### To Reproduce

I've attached the `example.pkl` file inside a zip. 

[example.pkl.zip](https://github.com/duckdb/duckdb/files/9962969/example.pkl.zip)

```
import duckdb
import pyarrow as pa
import pandas as pd
import pickle

con = duckdb.connect()
with open('example.pkl', 'rb') as f:
    in_df = pickle.load(f)
# Replacing the load from pandas with a load from pyarrow produces correct results.
# in_tbl = pa.Table.from_pandas(in_df)
# con.execute('create table tiles as select * from in_tbl')
con.execute('create table tiles as select * from in_df')
out = con.execute('select * from tiles limit 10000').fetch_df()
print(in_df['alpha0'])
print(out['alpha0'])
```

Output:
```
0    0.011102
1    0.011101
2    0.011111
3    0.011123
4    0.011102
5    0.011101
6    0.011111
7    0.011123
8    0.011139
9    0.011137
Name: alpha0, dtype: float32
0    0.011102
1    0.102584
2    0.114941
3    0.104812
4    0.099318
5    0.104231
6    0.099771
7    0.106665
8    0.103630
9    0.100998
Name: alpha0, dtype: float32
```

Also note that saving the dataframe to CSV and then reloading it also fixes the issue. So, I'm guessing this is an edge case where the pandas data is stored 

Thank you!!

### OS:

Mac OS Ventura, M1

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Ben Thompson

### Affiliation:

Confirm Solutions

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
The issue originates in `vector_conversion.cpp:454`
```c++
			} else {
				// Otherwise we have to get it through 'to_numpy()'
				bind_data.numpy_col = py::array(column.attr("to_numpy")());
			}
```
this is equivalent to `df['alpha0'].array.to_numpy()` but somehow this results (when taking the data with `pybind11::array::data()`) in:
(result of that is stored in `numpy_col_data`)
```
(lldb) p ((float*)numpy_col_data)[0]
(float) $1 = 0.0111023095
(lldb) p ((float*)numpy_col_data)[1]
(float) $2 = 0.102584355
(lldb) p ((float*)numpy_col_data)[2]
(float) $3 = 0.114940837
```

**Comment by Tishj** [comment]
Oh.. the shape is skewed, this is a row-major order array, we expect a column-major array
Maybe we need to add a detection for the order of a numpy array, and either convert it to column-major order or create a separate conversion path for row-major ordered dataframes

**Comment by tbenthompson** [comment]
Awesome debugging! Thanks @Tishj

**Comment by Tishj** [comment]
You're welcome, it was very low hanging fruit tbh :)
