### ISSUE TITLE
Release v0.5.1 wheel for Python 3.11

### ISSUE THREAD

**Issue by frankier** [duckdb/duckdb#5268]
There is currently no wheel for Python 3.11. It looks like it will be available in the next release, but I was wondering if a wheel could be released for Python 3.11 already. The reason is that source builds are not working correctly for me due to https://github.com/duckdb/duckdb/issues/4986 . Thanks!

**Comment by Mytherin** [comment]
Our next release is next Monday. In the meantime perhaps you can use the pre-release (`pip install duckdb --pre`)?

**Comment by frankier** [comment]
Looks like prerelease wheels are just for windows and osx. The new release is pretty soon though so I can probably hold on.

**Comment by Mytherin** [comment]
We should have pre-release binaries for Linux as well, but because of the nature of pre-releases they do not all get uploaded at the same time (and sometimes certain binaries might be missing). Does it work if you run `pip install duckdb --pre --prefer-binary`?

**Comment by frankier** [comment]
Great -- thanks!
