### ISSUE TITLE
jdbc time data type does not support sub second 

### ISSUE THREAD

**Issue by dorianjones** [duckdb/duckdb#5278]
### What happens?

When selecting a time with a sub second component the JDBC driver throws an exception when creating the result set, which then returns null from the catch statement block.

The JDBC driver DuckDbResultSet class uses the java.sql.Time class. In 

```java
    public Time getTime(int var1) throws SQLException {
        String var2 = this.getLazyString(var1);
        if (var2 == null) {
            return null;
        } else {
            try {
                return Time.valueOf(this.getLazyString(var1));
            } catch (Exception var4) {
                return null;
            }
        }
    }
```

The `Time.valueOf(...)` call passes a String to be parsed into a Time value. As the java.sql.Time javadoc states:
```
public static [Time] valueOf([String  s)
Converts a string in JDBC time escape format to a Time value.
Parameters:
s - time in format "hh:mm:ss"
Returns:
a corresponding Time object
```

Passing a time value with a milli/nano second component with the form 'hh:mm:ss.SSS' results in an exception which causes a null to be returned.

### To Reproduce
From DBeaver execute the SQL
```sql
select current_time
```
Returns null.

Executing 
```sql
select cast(current_time as VARCHAR(30))
```
Returns '22:39:01.348'

Executing directly from a java program, (although more complicated to reproduce here) results in the same problem.

OS:
Windows

DuckDB Version:
0.51.0

DuckDB Client:
DBeaver and Java JDBC

Full Name:
Dorian Jones

Affiliation:
None

Have you tried this on the latest master branch?
Yes
Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
Yes

**Comment by Mause** [comment]
I guess the most straightforward fix here is to truncate the returned value, right?

**Comment by dorianjones** [comment]
Would it be possible to use Local time in place of Time?

I think this would have the advantage of 

a) Keeping the resolution of nano/milliseconds. This is especially important when processing a time column since truncating the value will result in never being able to reconcile back to the originating table column.

b) In line with the use of LocalDateTime (for timestamps) and OffsetTime (zoned.)

c) Increasingly data processing libraries seem to use LocalTime in preference to java.SQL and Joda based classes.

d) Matches the resolution from data stored in Parquet files.

**Comment by Mause** [comment]
We can't change what the `getTime` method returns no, as that method is part of the JDBC standard. We do have the `getOffsetDateTime`, `getLocalDateTime`, and `getTimestamp` methods however - so they suite your usecase?

**Comment by dorianjones** [comment]
I am using the jdbc getObject method since the code is required to possibly use any JDBC driver.

Would using the Java instant class within the getTime method work? For example, `Instance.parse(var2).toEpochMilli()' and then use the long value to create the Time object with setTime()

**Comment by dorianjones** [comment]
Just realized that the Time object can be constructed directly from the long value returned by toEpochMilli()

**Comment by dorianjones** [comment]
Sorry, Instant.parse requires a timestamp with zone. Parsing to LocalTime and converting to Instant is required. For example,

```java
OffsetDateTime.of(LocalDate.EPOCH, LocalTime.parse(var2), Zone offset.UTC).toInstant().toEpochMilli()
```
LocalDate.EPOCH is only available from Java 9, Java 8 requires the static `LocalDate.ofEpochDay(0)`

**Comment by Jens-H** [comment]
Maybe using the more flexible LocalTime.parse() method can help here. This example should be working:
`Time.valueOf(LocalTime.parse("21:49:00.042"));`

**Comment by Jens-H** [comment]
To get a better resolution than sq.Time it should be rather easy to add an if branch in the `getObject(int columnIndex, Class<T> type)` for LocalTime.

**Comment by dorianjones** [comment]
Thanks, Yes, I didn't realise that Java 9 Time has a constructor from LocalTime. `Time.valueOf(LocalTime.parse("21:49:00.042"));` is a simple and elegant solution.

The addition of LocalTime to getObject would be very useful and being able to access the original microsecond resolution solves the problem of being able to reconcile back.

**Comment by dorianjones** [comment]
Looking at java.sql.Time in adopt-openjdk-11, the Time constructor from LocalTime ignores the nanosecond field.

```java
    /**
     * Obtains an instance of {@code Time} from a {@link LocalTime} object
     * with the same hour, minute and second time value as the given
     * {@code LocalTime}. The nanosecond field from {@code LocalTime} is
     * not part of the newly created {@code Time} object.
     *
     * @param time a {@code LocalTime} to convert
     * @return a {@code Time} object
     * @exception NullPointerException if {@code time} is null
     * @since 1.8
     */
    @SuppressWarnings("deprecation")
    public static Time valueOf(LocalTime time) {
        return new Time(time.getHour(), time.getMinute(), time.getSecond());
    }

```

The millisecond constructor using 'OffsetDateTime.of(LocalDate.EPOCH, LocalTime.parse(var2), Zone offset.UTC).toInstant().toEpochMilli()' seems to be the only way I can find to include a sub second component. 

The getObject method returning a LocalTime is still therefore important to get access to the original column value.

**Comment by Mause** [comment]
I've (hopefully) fixed this by returning `LocalTime`'s for `Types.TIME`, if someone is able to check the snapshot build and confirm it behaves as expected that would be great 😁
