### ISSUE TITLE
Type casting saving to parquet file

### ISSUE THREAD

**Issue by wanchoi211** [duckdb/duckdb#5294]
### What happens?

I noticed INTEGER type changes to DOUBLE when applying `SUM` and saving to parquet file. 

### To Reproduce

```
duckdb> CREATE TABLE t (i INTEGER);
duckdb> INSERT INTO t VALUES (1);
duckdb> INSERT INTO t VALUES (1);
duckdb> COPY (SELECT SUM(i) as s FROM t) TO 'result.parquet' (FORMAT 'parquet'); 
duckdb> SELECT type FROM parquet_schema('result.parquet') WHERE name = 's';
=> DOUBLE
duckdb> CREATE TABLE r AS (SELECT SUM(i) as s FROM t);
duckdb> DESCRIBE r;
=> column_type == HUGEINT
```

### OS:

x86_64

### DuckDB Version:

https://shell.duckdb.org/

### DuckDB Client:

https://shell.duckdb.org/

### Full Name:

Alex Choi

### Affiliation:

Ladder Insurance

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
I use CLI
```sql
~ $ duckdb
v0.4.0 da9ee49
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE t (i INTEGER);
D INSERT INTO t VALUES (1);
D INSERT INTO t VALUES (1);
D COPY (SELECT SUM(i) as s FROM t) TO 'result.parquet' (FORMAT 'parquet');
Error: Catalog Error: Copy Function with name parquet does not exist!
Did you mean "csv"?
D CREATE TABLE r AS (SELECT SUM(i) as s FROM t);
D DESCRIBE r;
┌─────────────┬─────────────┬──────┬─────┬─────────┬───────┐
│ column_name │ column_type │ null │ key │ default │ extra │
├─────────────┼─────────────┼──────┼─────┼─────────┼───────┤
│ s           │ HUGEINT     │ YES  │     │         │       │
└─────────────┴─────────────┴──────┴─────┴─────────┴───────┘
```

**Comment by Alex-Monahan** [comment]
> I use CLI
> 
> ```sql
> ~ $ duckdb
> v0.4.0 da9ee49
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D CREATE TABLE t (i INTEGER);
> D INSERT INTO t VALUES (1);
> D INSERT INTO t VALUES (1);
> D COPY (SELECT SUM(i) as s FROM t) TO 'result.parquet' (FORMAT 'parquet');
> Error: Catalog Error: Copy Function with name parquet does not exist!
> Did you mean "csv"?
> D CREATE TABLE r AS (SELECT SUM(i) as s FROM t);
> D DESCRIBE r;
> ┌─────────────┬─────────────┬──────┬─────┬─────────┬───────┐
> │ column_name │ column_type │ null │ key │ default │ extra │
> ├─────────────┼─────────────┼──────┼─────┼─────────┼───────┤
> │ s           │ HUGEINT     │ YES  │     │         │       │
> └─────────────┴─────────────┴──────┴─────┴─────────┴───────┘
> ```

Did you load the parquet extension? Do other parquet operations work as expected?

**Comment by l1t1** [comment]
may be because I used termux version
in windows, v0.4.0 shows as you wrote, but 0.3.1 rose a HUGEINT error
```
D:\duckdb>duckdb
v0.3.1 88aa81c6b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D CREATE TABLE t (i INTEGER);
D INSERT INTO t VALUES (1);
D INSERT INTO t VALUES (1);
D COPY (SELECT SUM(i) as s FROM t) TO 'result.parquet' (FORMAT 'parquet');
Error: Not implemented Error: HUGEINT
D .exit

D:\duckdb>duckdb04
v0.4.0 da9ee490d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D CREATE TABLE t (i INTEGER);
D INSERT INTO t VALUES (1);
D INSERT INTO t VALUES (1);
D COPY (SELECT SUM(i) as s FROM t) TO 'result.parquet' (FORMAT 'parquet');
D SELECT type FROM parquet_schema('result.parquet') WHERE name = 's';
┌────────┐
│  type  │
├────────┤
│ DOUBLE │
└────────┘
```

**Comment by Mytherin** [comment]
As mentioned, DuckDB returns a 128 bit integer (HUGEINT) from a SUM calculation to avoid potential overflows. This type is not supported by Parquet so the result is converted to double. You could cast the sum to INT64 to work around this issue.

**Comment by l1t1** [comment]
> As mentioned, DuckDB returns a 128 bit integer (HUGEINT) from a SUM calculation to avoid potential overflows. This type is not supported by Parquet so the result is converted to double. You could cast the sum to INT64 to work around this issue.

thanks.
maybe duckdb can save a sum as int96 type
https://drill.apache.org/docs/parquet-format/

**Comment by Mytherin** [comment]
The `INT96` type in Parquet is almost exclusively used to store legacy timestamps - I would venture that many systems will incorrectly interpret this and create worse problems.
