### ISSUE TITLE
Error occurs when two connections are created at the same time

### ISSUE THREAD

**Issue by ethink** [duckdb/duckdb#5298]
The code is as follows:
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import org.duckdb.DuckDBConnection;

public class Test {

	public static void main(String[] args) throws ClassNotFoundException, SQLException {
		String filePath="F:\\rdh\\duckdb\\test_10_1000w.db";
		DuckDBConnection conn1=getConn(filePath);
		System.out.println(conn1);
		DuckDBConnection conn2=getConn(filePath);
		System.out.println(conn2);
		
	}
	
	public static DuckDBConnection getConn(String file) throws ClassNotFoundException, SQLException {
		DuckDBConnection conn=null;
		Properties ro_prop = new Properties();
		ro_prop.setProperty("duckdb.read_only", "False");
		String path="jdbc:duckdb:"+file;
		Class.forName("org.duckdb.DuckDBDriver");
		conn = (DuckDBConnection) DriverManager.getConnection(path,ro_prop);
			
		return conn;
	}
}
**I want to operate the duckdb file in both services at the same time**
**How can I operate the same duckdb file in two different services？**

**Comment by Mause** [comment]
Please recreate this issue using the issue template, and provide version and error information

**Comment by Mytherin** [comment]
Please follow the issue template as mentioned
