### ISSUE TITLE
Regression with DECIMAL type in 0.5+

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#5306]
### What happens?

We are encountering a regression with handling of `DECIMAL` columns in versions of DuckDB after release 0.4. I have tested and encounter the issue both on 0.5.1 and on the current master branch (so presumably the forthcoming 0.6 release).

The issue appears to be something like a combination of two previous regressions we filed. Like #4688 it concerns a precision and scale being inferred for a decimal column which does not actually fit all the values in the column, but like #4689 the repro requires a larger dataset so it seems like maybe it's an issue with only the first batch of values being examined when inferring the precision/scale.

### To Reproduce

186,000 seems to be the batch size in question here, so the issue is reproduced by constructing a DataFrame with a decimal column where the first 186k values fit into a smaller decimal size, and with a subsequent value exceeding that size:

```python
import duckdb
import pandas as pd
import numpy as np
from decimal import Decimal


dec = Decimal("10.00")
dec_arr = np.repeat(dec, 186001)
dec_arr = np.append(dec_arr, Decimal("1000.00"))

decimals_df = pd.DataFrame(
    data={
        "decimals": dec_arr
    }
)

conn = duckdb.connect(database= ":memory", read_only=False)
conn.register("decimals", decimals_df)

conn.execute("select * from decimals")
result = conn.df()
```

Expected: We should get back a copy of `decimals_df`.

Actual:
```
duckdb.InvalidInputException: Invalid Input Error: Failed to cast value: Casting value "1000.00" to type DECIMAL(4,2) failed: value is out of range!
```

### OS:

macOS

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Have you tried adjusting the pandas_sample_size?

**Comment by dylanscott** [comment]
@Tishj I have not - is there a place that setting is documented? Is there a way to configure it to sample all values? We are embedding DuckDB and let users run SQL against arbitrary data sets so we would like to avoid these kinds of sampling issues even if it means paying a performance penalty

**Comment by Alex-Monahan** [comment]
> @Tishj I have not - is there a place that setting is documented? Is there a way to configure it to sample all values? We are embedding DuckDB and let users run SQL against arbitrary data sets so we would like to avoid these kinds of sampling issues even if it means paying a performance penalty

I believe you can set it to a really high number to sample everything! I think the config is:
`SET GLOBAL pandas_analyze_sample=2`

https://github.com/duckdb/duckdb/blob/942d917145ae4a562b5e3d3649fdabe5ae202305/tools/pythonpkg/tests/fast/pandas/test_df_analyze.py

**Comment by Tishj** [comment]
@dylanscott Yes, it's documented here
https://duckdb.org/docs/guides/python/import_pandas 👍

**Comment by dylanscott** [comment]
Thank you! Confirmed that cranking this parameter up fixes things 👍
