### ISSUE TITLE
Add starts_with function and operator ^@

### ISSUE THREAD

**Issue by papparapa** [duckdb/duckdb#5311]
### What happens?

I would like duckdb to add the `starts_with` function and the equivalent operator `^@`.

They are available in PostgreSQL.

`starts_with(sring, prefix)` returns `true` if `string` starts with `prefix` and `false` otherwise.
The same applies to `sring ^@ prefix`.

- PostgreSQL `starts_with` function documentation: https://www.postgresql.org/docs/15/functions-string.html#id-1.5.8.10.7.2.2.38.1.1.1
- PostgreSQL `^@` operator documentation: https://www.postgresql.org/docs/15/functions-string.html#id-1.5.8.10.7.2.2.1.1.1.1

### To Reproduce

In PostgreSQL 15
```psql
postgres=# select starts_with('Hello', 'H');
 starts_with 
-------------
 t
(1 row)

postgres=# select starts_with('Hello', 'e');
 starts_with 
-------------
 f
(1 row)

postgres=# select 'Hello' ^@ 'H';
 ?column? 
----------
 t
(1 row)

postgres=# select 'Hello' ^@ 'e';
 ?column? 
----------
 f
(1 row)
```

Just to be sure, they are not yet implemented in DuckDB.

```
duckdb> select starts_with('Hello', 'H');
Catalog Error: Scalar Function with name starts_with does not exist!
Did you mean "str_split"?
LINE 1: select starts_with('Hello', 'H');
               ^

duckdb> select 'Hello' ^@ 'H';
Catalog Error: Scalar Function with name ^@ does not exist!
Did you mean "@"?
LINE 1: select 'Hello' ^@ 'H';
                       ^
```

### OS:

Windows 11 Home

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Koki Ueha

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by papparapa** [comment]
I am going to implement it myself because this looks like a Good First Issue.

Perhaps I can divert some of the already existing source code for the `contains` function.

**Comment by Tishj** [comment]
Perhaps the parser change not so much, but creating the function should be a "good first issue"

**Comment by Mytherin** [comment]
This shouldn’t require a parser change, operators are just functions with special names (i.e. containing symbols like @^)
