### ISSUE TITLE
[C-API] Appending decimal values doesn't work as expected

### ISSUE THREAD

**Issue by ak-coram** [duckdb/duckdb#5312]
### What happens?

While extending my Common Lisp bindings for DuckDB with support for appenders I've [noticed](https://github.com/ak-coram/cl-duckdb/pull/7) that appending decimal values works differently from binding them as parameter values for a statement.

None of the append functions (varchar, floating point, integer) seem to fully work for decimals as expected, but appending as varchar seems to be in the worst shape as it appends garbage values which can be different even for the same input.

### To Reproduce

``` C
#include <stdio.h>
#include <duckdb.h>

int main () {

  duckdb_database db;
  duckdb_connection con;

  duckdb_open("/home/ak/bug.ddb", &db);
  duckdb_connect(db, &con);

  duckdb_query(con, "DROP TABLE IF EXISTS bug", NULL);
  duckdb_query(con, "CREATE TABLE bug(i INTEGER, x DECIMAL(38,38), y DECIMAL(10,5))", NULL);
  
  duckdb_appender appender;
  duckdb_appender_create(con, NULL, "bug", &appender);

  // Append decimal as varchar
  duckdb_append_int32(appender, 1);
  duckdb_append_varchar(appender, "0.33333333333333333333333333333333333333");
  duckdb_append_null(appender);
  duckdb_appender_end_row(appender);

  // Append decimal as float
  duckdb_append_int32(appender, 2);
  duckdb_append_null(appender);
  duckdb_append_float(appender, 123.123);
  duckdb_appender_end_row(appender);

  // Append decimal as double
  duckdb_append_int32(appender, 3);
  duckdb_append_null(appender);
  duckdb_append_double(appender, 123.123);
  duckdb_appender_end_row(appender);

  // Append decimal as integer
  duckdb_append_int32(appender, 3);
  duckdb_append_null(appender);
  duckdb_append_uint64(appender, 12345);
  duckdb_appender_end_row(appender);

  duckdb_appender_destroy(&appender);

  duckdb_disconnect(&con);
  duckdb_close(&db);
}
```

Adjust the database path in the above source, save as bug.c & compile and run via:
```
gcc -o bug -lduckdb bug.c
./bug
```

Check the results via the DuckDB CLI:
```
$ duckdb ~/bug.ddb                                                                 
v0.5.1 7c111322de
Enter ".help" for usage hints.
D SELECT * FROM bug;
┌───┬─────────────────────────────────────────┬─────────┐
│ i │                    x                    │    y    │
├───┼─────────────────────────────────────────┼─────────┤
│ 1 │ .00001743639545229628325703332847943680 │         │
│ 2 │                                         │ 0.00123 │
│ 3 │                                         │ 0.00123 │
│ 3 │                                         │ 0.12345 │
└───┴─────────────────────────────────────────┴─────────┘
```

### OS:

Linux

### DuckDB Version:

0.5.1 (also tested with current master)

### DuckDB Client:

C API / Common Lisp

### Full Name:

Ákos Kiss

### Affiliation:

Third-party DuckDB binding maintainer (Common Lisp)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the very extensive reproducable test! 👍 

I'll look into fixing this soon :)

**Comment by Tishj** [comment]
It's not C-API specific I think, it's related to the CPP-API
