### ISSUE TITLE
An error is reported when the duckdb file is operated in two services at the same time

### ISSUE THREAD

**Issue by ethink** [duckdb/duckdb#5317]
### What happens?

I want to create a connection to the same duckdb file in two services at the same time, but an error is reported

**The code is as follows:**
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import org.duckdb.DuckDBConnection;

public class Test {

	public static void main(String[] args) throws ClassNotFoundException, SQLException {
		String filePath="F:\\rdh\\duckdb\\test_10_1000w.db";
		DuckDBConnection conn1=getConn(filePath);
		System.out.println(conn1);
		DuckDBConnection conn2=getConn(filePath);
		System.out.println(conn2);
		
	}
	
	public static DuckDBConnection getConn(String file) throws ClassNotFoundException, SQLException {
		DuckDBConnection conn=null;
		Properties ro_prop = new Properties();
		ro_prop.setProperty("duckdb.read_only", "False");
		String path="jdbc:duckdb:"+file;
		Class.forName("org.duckdb.DuckDBDriver");
		conn = (DuckDBConnection) DriverManager.getConnection(path,ro_prop);
			
		return conn;
	}
}

**The error is reported as follows:**
org.duckdb.DuckDBConnection@548a102f
Exception in thread "main" java.sql.SQLException: IO Error: Cannot open file "F:\rdh\duckdb\test_10_1000w.db": Áíһ¸ö³ÌÐòÕýÔÚʹÓôËÎļþ£¬½ø³ÌÎ
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at com.dla.db2duckdb_exec_plug.util.Test.getConn(Test.java:26)
	at com.dla.db2duckdb_exec_plug.util.Test.main(Test.java:15)

**I want to establish a connection to the duckdb file in two microservices at the same time**

### To Reproduce

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import org.duckdb.DuckDBConnection;

public class Test {

	public static void main(String[] args) throws ClassNotFoundException, SQLException {
		String filePath="F:\\rdh\\duckdb\\test_10_1000w.db";
		DuckDBConnection conn1=getConn(filePath);
		System.out.println(conn1);
		DuckDBConnection conn2=getConn(filePath);
		System.out.println(conn2);
		
	}
	
	public static DuckDBConnection getConn(String file) throws ClassNotFoundException, SQLException {
		DuckDBConnection conn=null;
		Properties ro_prop = new Properties();
		ro_prop.setProperty("duckdb.read_only", "False");
		String path="jdbc:duckdb:"+file;
		Class.forName("org.duckdb.DuckDBDriver");
		conn = (DuckDBConnection) DriverManager.getConnection(path,ro_prop);
			
		return conn;
	}
}

### OS:

Windows x64

### DuckDB Version:

0.5.1

### DuckDB Client:

java

### Full Name:

dhren

### Affiliation:

mysql

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you please try using a more recent version of DuckDB, eg, 0.5.1?

**Comment by ethink** [comment]
> Can you please try using a more recent version of DuckDB, eg, 0.5.1?

I still report the same error after changing to version 0.5.1 
**I want to establish a database connection to the same duckdb file in two different microservices at the same time. Can I do that? How can I do it?**

**Comment by Mause** [comment]
Can you please try using a DuckDB file that is **not** on a shared network drive? `F:` is generally a network drive, rather than a drive physically attached to your computer

**Comment by ethink** [comment]
> Can you please try using a DuckDB file that is **not** on a shared network drive? `F:` is generally a network drive, rather than a drive physically attached to your computer

**This is a local file. There is no problem with a single connection. I want to establish a connection between two microservices at the same time. Do you have a specific code sample?**

**Comment by Alex-Monahan** [comment]
In DuckDB, you have 2 options for concurrency!

1. A single read/write process
2. Multiple Read Only processes

You cant have both of those at once though. You would have to lock the DB so only one process writes at a time and close it before the other process opens it. 

That help?

**Comment by ethink** [comment]
> In DuckDB, you have 2 options for concurrency!
> 
> 1. A single read/write process
> 2. Multiple Read Only processes
> 
> You cant have both of those at once though. You would have to lock the DB so only one process writes at a time and close it before the other process opens it.
> 
> That help?

I have created many tables in one database, and they are all generated into the same file in the background. Is there any way to generate multiple files, such as one table and one independent file

> In DuckDB, you have 2 options for concurrency!
> 
> 1. A single read/write process
> 2. Multiple Read Only processes
> 
> You cant have both of those at once though. You would have to lock the DB so only one process writes at a time and close it before the other process opens it.
> 
> That help?

I have created many tables in one database, and they are all generated into the same file in the background. Is there any way to generate multiple files, such as one table and one independent file

**Comment by Mause** [comment]
You can create many parquet files and query across them, but you can only query one DuckDB database at a time at present

**Comment by Mytherin** [comment]
As stated, multiple processes connecting to the same database file is only possible if they are *all* read-only connections. It is not possible to have a read-write connection and a read-only connection connected to the same database file *across multiple processes*. We have no immediate plans to implement this. If you want multiple connections to work on the same file while writing, the read-write connection must be closed prior to opening a read-only connection.

See #77 for more background.
