### ISSUE TITLE
OSX CI failed

### ISSUE THREAD

**Issue by papparapa** [duckdb/duckdb#5321]
### What happens?

I got in trouble while working on the issue [#5311](https://github.com/duckdb/duckdb/issues/5311).

OSX CI on my fork failed.

https://github.com/papparapa/duckdb/actions/runs/3454987323/jobs/5766683197#step:5:306

```sh
[292/1989]: test/fuzzer/afl/limit_out_of_range.test
FAILURE IN RUNNING TEST
--------------------
RETURNCODE
--------------------

-6
--------------------
STDOUT
--------------------

Filters: test/fuzzer/afl/limit_out_of_range.test

[0/1] (0%): test/fuzzer/afl/limit_out_of_range.test                             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/fuzzer/afl/limit_out_of_range.test
-------------------------------------------------------------------------------
/Users/runner/work/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:178
...............................................................................

/Users/runner/work/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:178: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases: 1 | 1 failed
assertions: 4 | 3 passed | 1 failed


--------------------
STDERR
--------------------

/Users/runner/work/duckdb/duckdb/src/planner/operator/logical_limit_percent.cpp:26:15: runtime error: nan is outside the range of representable values of type 'unsigned long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/runner/work/duckdb/duckdb/src/planner/operator/logical_limit_percent.cpp:26:15 in 

make: *** [unittestci] Error 1
Error: Process completed with exit code 2.
```

### To Reproduce

Run GitHub Actions.

### OS:

OSX

### DuckDB Version:

my working branch (duckdb master branch should the same because I touched only sql function files)

### DuckDB Client:

-

### Full Name:

Koki Ueha

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by papparapa** [comment]
The error log indicates that the following `idx_t(child_cardinality * (limit_percent / 100.0))` caused the error.

https://github.com/duckdb/duckdb/blob/f0ec7187be65a5b401a234b56520aab89307c964/src/planner/operator/logical_limit_percent.cpp#L26

Maybe at least one of `limit_percent` or `child_cardinality` is `nan`.
When that is the case, `LogicalLimitPercent::EstimateCardinality` has to return some other value instead of calculating `idx_t(child_cardinality * (limit_percent / 100.0))`, but I'm not sure what it is.

**Comment by papparapa** [comment]
[#5322](https://github.com/duckdb/duckdb/pull/5322)

**Comment by Mytherin** [comment]
This is now fixed
