### ISSUE TITLE
Create relation from a parquet_scan()

### ISSUE THREAD

**Issue by craustin** [duckdb/duckdb#5323]
It would be nice to create a relation from a `httpfs` `parquet_scan()` source. We currently have `DuckDBPyRelation::from_parquet()` for a single file but no `from_parquet_scan()`. Would it make sense to add one? Or- is the best way forward here to start with `from_query("SELECT col_1, col_2 FROM parquet_scan(...)")` and compose a relation from there?

**Comment by Alex-Monahan** [comment]
Would another option be to adjust that function to accept a list of filenames or a string? That's how the SQL equivalent works!

**Comment by craustin** [comment]
Yes, that'd work. Should support the `filename` option too.

**Comment by omo** [comment]
(Unsolicited triage) Looks like this can be closed? @Mause
