### ISSUE TITLE
Strange error with make_date/date_part on large dataset

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#5342]
### What happens?

We've encountered a strange bug on a specific query over a large sample dataset. With a certain set of filters we are encountering an error evaluating `make_date(date_part(['year', 'month', 'day'], "timestamtz_column"))`, which we use as a workaround to convert `timestamptz` columns to `date`s while respecting the configured `TimeZone`.

I don't have a very good sense for what specifically might be triggering the issue. We ran into it accidentally and the repro presented here is isolated from that test case but isn't particularly minimal (exported as a ~2m row parquet file). But I don't believe it is a case of bad/corrupt input data because as shown in the repro steps we can successfully execute a couple of similar queries that seemingly should hit the same case if it were down to a bad row.

### To Reproduce

To make things easier I have created a [little git repo](https://github.com/dylanscott/duckdb-repro) containing the parquet file and code to repro, as well as a couple of scripts to setup a virtualenv with the required dependencies and run the repro in it. I've tested this case with DuckDB 0.5.1, the new 0.6 release, and the latest master branch for good measure. The `repro.py` case contains the following:

First we read the contents of the parquet file with pandas and register it with DuckDB:

```python
import duckdb
import pandas

conn = duckdb.connect(database=':memory:')

repro_df = pandas.read_parquet('repro.parquet', engine='fastparquet')
conn.register('repro', repro_df)
```

Then we run a couple of queries that intend to show that this is a bug and not an issue with the input data. First we show that we can successfully run that `timestamptz` -> `date` conversion code for all rows in the dataset:

```python
all_converted_df = conn.execute("""
select make_date(date_part(['year', 'month', 'day'], "ACTUAL_DATE")) as "ACTUAL_DATE" from repro
""").df()
```

The 2nd query gets closer to the erroring query - moving the date conversion into the where clause and filtering by the `FLAG` column, but this one still succeeds:

```python
less_filtered_df = conn.execute("""
select * from repro
where "FLAG" = true
      AND make_date(date_part(['year', 'month', 'day'], "ACTUAL_DATE")) >= '2021-01-01'
""").df()
```

Finally we add a filter on the `HASH` column, which should run on a subset of the rows from the previous query but for some reason now hits an error:

```python
erroring_df = conn.execute("""
select * from repro
where "FLAG" = true
      AND "HASH" = 'be763d263e00fe8a7c1e37ef441c5519'
      AND make_date(date_part(['year', 'month', 'day'], "ACTUAL_DATE")) >= '2021-01-01'
""").df()
```

```
duckdb.ConversionException: Conversion Error: Date out of range: 0-0-0
```

From grepping the DuckDB codebase it seems like that error is coming from the `make_date` call and indicates that it's getting zeros for year/month/day, even though it doesn't seem to be in the other queries. Weird!

Also this may or may not be useful but here are a few things I encountered while isolating this repro that seemed interesting:

- Selecting directly from the parquet file rather than reading with Pandas and registering doesn't repro the issue.
  - The main difference I could see is I think `ACTUAL_DATE` ends up as a `timestamp` (without time zone) when reading directly from the parquet file whereas Pandas reads it into a `datetime64[ns, UTC]` column which should map to `timestamptz` 
- I get the `Date out of range: 0-0-0` error when reproing on my M1 Mac, but I get different values in the error when we initially encountered the error in our app where the Python process is running in an x86-64 Linux VM. Specifically: `Date out of range: 1514828672-1514828656-1514828656`
- The only existing issue I could find that seemed like it might be related was #2860 which also concerns a weird date conversion error manifesting on large datasets.
  - Though the only comment said it looks like an issue with the optimizer and I tested with `pragma disable_optimizer;` and still hit the issue.

### OS:

macOS, Linux

### DuckDB Version:

0.6, 0.5.1

### DuckDB Client:

Python

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Thanks for making the reproducible example. I am getting the same error here. To me this looks like this is going wrong in date_part. I was able to remove Python from the example using the Parquet file you provided:

```SQL
CREATE TABLE test5342 as from 'repro.parquet';
SELECT ACTUAL_DATE, date_part(['year', 'month', 'day'], ACTUAL_DATE) date_part from test5342
where HASH = 'be763d263e00fe8a7c1e37ef441c5519' limit 10;
```

```
┌─────────────────────┬───────────────────────────────────────────────┐
│     ACTUAL_DATE     │                   date_part                   │
│      timestamp      │ struct(year bigint, month bigint, day bigint) │
├─────────────────────┼───────────────────────────────────────────────┤
│ 2020-12-13 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-14 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-15 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-16 00:00:00 │ {'year': 226, 'month': 226, 'day': 226}       │
│ 2020-12-17 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-18 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-19 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-20 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-21 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
│ 2020-12-22 00:00:00 │ {'year': 0, 'month': 0, 'day': 0}             │
├─────────────────────┴───────────────────────────────────────────────┤
│ 10 rows                                                   2 columns │
└─────────────────────────────────────────────────────────────────────┘
```

**Comment by hannes** [comment]
This looks related to the list parameter/struct out feature of `date_part`

**Comment by hannes** [comment]
Maybe @hawkfish can have a look?

**Comment by hawkfish** [comment]
Hmm doesn't repro if I just create a table with the TS values.

**Comment by hawkfish** [comment]
Looks like a constant vs flat size 1 issue. The filter usually produces only 1 value in a block.

**Comment by hawkfish** [comment]
Also busted in ICU.

**Comment by series-of-sign** [comment]
Same issue on duckdb 1.2.2

**Comment by Mytherin** [comment]
DuckDB v1.2.2 is not supported anymore - if you can reproduce the issue in DuckDB v1.4.1 feel free to open an issue.
