### ISSUE TITLE
Inner join query doesn't work in node js

### ISSUE THREAD

**Issue by Alucard17** [duckdb/duckdb#5344]
### What happens?

Node js gives following error whenever there is inner join used in query
```error Command failed with exit code 3221226505.```
I've test left and right join works as expected.

### To Reproduce

```js
import duckdb from "duckdb";

const db = new duckdb.Database(":memory:");
db.run("create table t1 (c1 int)", () => {
  db.run("create table t2 (c2 int)", () => {
    db.run("insert into t1 values (1), (2)", () => {
      db.run("insert into t2 values (1), (2)", () => {
          console.log("was here");
        db.all("select * from t1 inner join t2 on c1 = c2", (err, data) => {
            
          if (err) {
            console.log(err);
          } else {
            console.log(data);
          }
        });
      });
    });
  });
});
```

### OS:

Windows

### DuckDB Version:

0.6.0

### DuckDB Client:

Node js

### Full Name:

Karan Yadav

### Affiliation:

NA

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hi, can you please provide your operating system version, architecture, and NodeJS version?

**Comment by Alucard17** [comment]
OS: Windows 11 Pro
Arch: x86
Node JS version:  18.12.1

**Comment by mazito** [comment]
I am having the same problem. 
For example the following query using `db.all()`:
~~~
select * FROM MUESTRA mu, PIVTARMUE piv where mu.IDMUE=piv.IDMUEPIV;
~~~
sistematically aborts the Node process with the reported error.

The same query runs in the `duckdb.exe`.

Creating a view and querying the view gives the same error.

Running on: `Node v19.1.0`, `Windows Server 2012 R2 Standard (x64)`, `Duckdb 0.6.1`.
Best regards.
Mario

**Comment by carlopi** [comment]
@Mause: thanks for the follow up, I had not tried Windows, but now I have and can confirm that it works both on 0.7.1 and on nightly!
