### ISSUE TITLE
Progress Bar show 100% too early

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5349]
### What happens?

I run create table t as select * from read_csv_auto('/title.basics.tsv.gz' ,NULLSTR='\N',QUOTE='');
it shows 100% almost immediately, then it return to CLI prompt about few seconds.

### To Reproduce

wget https://datasets.imdbws.com/title.basics.tsv.gz
duckdb
create table t as select * from read_csv_auto('/title.basics.tsv.gz' ,NULLSTR='\N',QUOTE='');

### OS:

windows 7

### DuckDB Version:

0.6.0

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
I tried a bigger data, it reached 100% at about 8 second. then the same question
```
wget https://datasets.imdbws.com/title.principals.tsv.gz
417,177,011 title.principals.tsv.gz
D create table tp as select * from read_csv_auto('/title.principals.tsv.gz' ,NULLSTR='\N',QUOTE='');
100% ▕████████████████████████████████████████████████████████████▏
Run Time (s): real 37.636 user 34.866223 sys 2.308815
```

**Comment by lnkuiper** [comment]
This is due to the gzip compression, we do not know the uncompressed size, therefore the progress is off. Perhaps it is possible to be more accurate, though

**Comment by pdet** [comment]
Yes, I think we can probably take a more reasonable guess after reading the first buffer
