### ISSUE TITLE
support for `-unsigned` option in the ODBC driver

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#5355]
Currently I cannot find a way to load locally compiled out of tree extensions when using ODBC driver. For example, if I wanted to load a locally compiled version of sqlitescanner. For the command line utility one can include the `-unsigned` argument that then allows loading of locally compiled (and hence unsigned) extensions.

**Comment by Mytherin** [comment]
This is caused by the ODBC driver not having support (yet) for passing configuration parameters. We should add support for that.

**Comment by blackrez** [comment]
Hello, any plan about this issue ?

(it is for the geo extension)

**Comment by blackrez** [comment]
Hello, I'm trying to add DBConfig by myself but I don't find where to do it correctly. Any idea on how to do it ?

**Comment by bucweat** [comment]
> Hello, I'm trying to add DBConfig by myself but I don't find where to do it correctly. Any idea on how to do it ?

Based on #6710 I think you are in the right area of the code that parses the connection string...need something like  `OdbcUtils::SetValueFromConnStr(conn_str, "unsigned", unsigned_value);` to parse out unsigned setting. Problem is what to do with `unsigned` once you have it. Could probably figure it out by looking at the console code to see how `--unsigned` is used there. Its something I've thought about looking at but just haven't had the time recently. Also my C++ is ok but my git-fu is not up to anything beyond the most basic of PR...and neither of those is my daily driver :-( 

@blackrez Happy to help though if you have or cycles and have questions...find me on Discord...

**Comment by blackrez** [comment]
I succeed to add unsigned support but when I wanted to add it in odbc.ini, this is where I found there is some issue in parsing the options with the odbc client librairie. I know quite well git but my C++ is very limited (debug is very hard). Also I only have linux/MacOS environment I can't test for windows.

**Comment by bucweat** [comment]
> odbc.ini

Goes to show you how much I know...I didn't realize there was such an animal...probably my windows goggles blinding me...

Funny I run MacOS but develop on Windows via Parallels so I have Windows 11 and Visual Studio 2019/2022. Debugging ODBC is not easy. For SQLite ODBC I could add reference to SQLiteODBC.dll and debug via the app and driver in Visual Studio. I had zero luck doing that with DuckDB ODBC .dll so I had to resort to inserting Console.WriteLine() in DuckDB code and running my app that uses DuckDB via ODBC in VS debugger....amazingly the Console.WriteLine statements for ODBC driver output in the VS console...yeah it is old fashioned but it works and helps some....

**Comment by blackrez** [comment]
I'm an *nix guys, my goal is to use DuckDB with erlang/elixir and there is no client actually but the support of ODBC is great in erlang.
Console.WriteLine() works ? Because my app run in terminal, maybe I could have some. Old fashion or not, if it works it works.

**Comment by maiadegraaf** [comment]
Hey @blackrez, have you made any progress on adding unsigned extensions? I'm working on ODBC connection right now and would be interested to see what you've come up with.

**Comment by maiadegraaf** [comment]
The ODBC driver now accepts config arguments (including unsigned extensions) as of https://github.com/duckdb/duckdb/pull/10692.
