### ISSUE TITLE
support for profiling of plans after serialization/deserialization

### ISSUE THREAD

**Issue by ila** [duckdb/duckdb#5357]
Hi,
I am trying to enable profiling for query plans getting deserialized. This is a quick example modified from the test cases:
```
static void GenerateQueryPlan(string &query, string &path, string &dbname) {

	DuckDB db(path + dbname);
	Connection con(db);

	BufferedFileWriter serializer(db.GetFileSystem(), path + "example_serialized_plan.binary");

	con.Query("PRAGMA enable_profiling");

	con.BeginTransaction();
	Parser p;
	p.ParseQuery(query);

	Planner planner(*con.context);

	planner.CreatePlan(move(p.statements[0]));
	auto plan = move(planner.plan);

	Optimizer optimizer(*planner.binder, *con.context);
	plan = optimizer.Optimize(move(plan));

	plan->Serialize(serializer);
	con.Rollback();
	serializer.Sync();

}

static void DeserializeQueryPlan(string &path, string &dbname) {

	// reading the file...

	DuckDB db(path + dbname);
	Connection con(db);

	con.Query("PRAGMA enable_profiling");

	BufferedDeserializer deserializer((data_ptr_t)buffer, len);
	PlanDeserializationState state(*con.context);
	auto plan = LogicalOperator::Deserialize(deserializer, state);

	plan->Print();
	plan->ResolveOperatorTypes();

	auto statement = make_unique<LogicalPlanStatement>(move(plan));
	auto result = con.Query(move(statement));
	result->Print(); 

}
```
The previous code does execute the query, but the profiler result is empty no matter what I do, or where I enable pragmas, or if I use `con.EnableProfiling()` instead, or which lines of code I wrap in a transaction block. I am guessing the profiler needs the query? Am I doing anything wrong here?

**Comment by lnkuiper** [comment]
Can you try `PRAGMA profiling_output='my_cool_file_name'`? This saves the profiling output in a file. Which should (hopefully) not be empty!

**Comment by ila** [comment]
I already did - both in ASCII art and JSON. File is indeed empty!

**Comment by lnkuiper** [comment]
I'm looking through the code path and it should definitely hit `profiler.StartQuery(...)` with the way you are using it. Could you perhaps set a breakpoint there (`QueryProfiler::StartQuery`) to figure out what is going on?

**Comment by ila** [comment]
`is_explain_analyze` is set to false
Enabled is set to true
`start_at_optimizer` is set to false
`running` is set to false
![image](https://user-images.githubusercontent.com/29451823/202198365-893ddf14-6f00-47df-9c11-03183ebe76ee.png)
![image](https://user-images.githubusercontent.com/29451823/202198429-63950935-4f79-4ce8-acb7-2d92536d1a5d.png)
![image](https://user-images.githubusercontent.com/29451823/202198513-2866378b-e6af-4e2d-b91a-e9dcd59998b0.png)

**Comment by Mytherin** [comment]
What does your physical plan look like? The profiling tree is set up in `QueryProfiler::Initialize`. Is that passed the correct physical plan?

**Comment by Tishj** [comment]
I think you are missing some code to create a physical plan out of your logical plan
```c++
	profiler.StartPhase("physical_planner");
	// now convert logical query plan into a physical query plan
	PhysicalPlanGenerator physical_planner(*this);
	auto physical_plan = physical_planner.CreatePlan(move(plan));
	profiler.EndPhase();

#ifdef DEBUG
	D_ASSERT(!physical_plan->ToString().empty());
#endif
	result->plan = move(physical_plan);
	return result;
```
This is taken from `client_context.cpp:346`

**Comment by ila** [comment]
the snippet of code you pasted is from prepared statements, which may always not be the case - how would I have to proceed executing a `PhysicalOperator` plan through the C++ API when I do not know in advance my data chunks but rather have tables?

**Comment by ila** [comment]
update - Laurens helped me diving into the stack calls and apparently the profiler does not start if the query string is empty. in my case, obviously the query is empty because only the logical plan is passed, and this can just be fixed with something as simple as `statement->query = "dummy` before calling `con.Query(...)` in the last lines of code of the example (does not even need to be valid SQL syntax). now this might also be trivial to fix in the source code, should I go ahead and give it a try? @Mytherin what do you think?

**Comment by Mytherin** [comment]
Sure, go ahead

**Comment by omo** [comment]
(Unsolicited triage): It seems like this is fixed by https://github.com/duckdb/duckdb/pull/5448 ?
