### ISSUE TITLE
[ART] RowID Leaf node specialization

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#5365]
We would like to add a special type of Leaf node to the ART.

This leaf node only consists of a single rowid, and therefore fits in the size of a pointer.
That allows us to not need to occupy a page with this data, but instead store it directly in the child list of another node. (saving us a trip to disk that we would otherwise need to do the first time the node is visited)

Since this specialization only contains a rowid and nothing more, this node can only be used in places where a prefix is not required.

The implementation requires adding a super class to the `Node` class that consists of nothing other than virtual functions, and all the variables of Node therefore also need to be private with getters/setters.
This also adds an extra option to the SwizzleablePointer, as a child pointer can now either be:
- Unswizzled (regular pointer)
- Swizzled (blockid + offset)
- Rowid (rowid_t)

**Comment by Mytherin** [comment]
I think this is a great idea - I wonder about using `virtual` methods, though. There are already a number of methods in the `Node` class that instead do a switch on the node type. Perhaps moving away from virtual methods for nodes entirely is a better idea? It is not like the `Node` class needs to be extended with logic outside of the few node types.
