### ISSUE TITLE
Database Export Using FORCE_QUOTE Can't Be Imported

### ISSUE THREAD

**Issue by GurpreetKang** [duckdb/duckdb#5367]
### What happens?

Exported database using the following command:
`EXPORT DATABASE '20221115' (FORMAT CSV, HEADER TRUE, FORCE_QUOTE *);`

Attempting to import the database gives the following error:
`Error: Binder Error: Unrecognized option for CSV reader "force_quote"`

If I edit load.sql and remove `FORCE_QUOTE '*'` from the COPY statements then the import completes successfully. 

### To Reproduce

Export database using the following command:
`EXPORT DATABASE '20221115' (FORMAT CSV, HEADER TRUE, FORCE_QUOTE *);`

Attempt to import the export into a new database (file or in-memory) using:
`IMPORT DATABASE '20221115';`

### OS:

WIndows 11 21H2 (22000.1219 x64)

### DuckDB Version:

v0.6.0 2213f9c946

### DuckDB Client:

CLI

### Full Name:

Gurpreet Kang

### Affiliation:

N/A

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
With the assumption this is database specific:
can you please post the database file? Or provide some way to recreate a database that has this same issue
Or perhaps post the content of the `load.sql`?

I have a hunch this is caused by the export option producing sql that we can't consume when "force_quote" is set, but if that's not the case, that's as far as the intel goes :)

**Comment by GurpreetKang** [comment]
load.sql:
`COPY "APPLICATION_DATES" FROM '20221115\application_dates.csv' (FORMAT 'csv', delimiter ',', header 'true', FORCE_QUOTE '*', quote '"');`

Removing `, FORCE_QUOTE '*'` results in a working IMPORT DATABASE command.

**Comment by Mytherin** [comment]
Thanks for the report!

I can reproduce this with the following commands:

```sql
create table integers(i int);
insert into integers values (42);
export database 'test_export' (force_quote *);
drop table integers;
import database 'test_export';
```

**Comment by Tishj** [comment]
I was about to post the same haha
