### ISSUE TITLE
DuckDB 0.6.0 on Windows (MSVC) Compile Error 

### ISSUE THREAD

**Issue by Dimpstone** [duckdb/duckdb#5368]
DuckDB 0.6.0 on Windows (MSVC) Compile Error:
.../test/sql/storage/test_buffer_manager.cpp(263): error C2660: 'std::align': function does not take 1 arguments

Here is 0.6.0 version of test_buffer_manager.cpp (error):
D_ASSERT(buffer_manager.GetUsedMemory() == align(requested_size + Storage::BLOCK_HEADER_SIZE));

Here is 0.5.1 version of test_buffer_manager.cpp (without error):
D_ASSERT(buffer_manager.GetUsedMemory() == requested_size + Storage::BLOCK_HEADER_SIZE);

BTW: DuckDB not available via VCPKG...

**Comment by Dimpstone** [comment]
One more issue on Windows while trying to compile C++ app...

Error	C2589	'(': illegal token on right side of '::' on:
...\src\include\duckdb\common\types.hpp
	static inline date_t infinity() {return date_t(std::numeric_limits<int32_t>::max()); } // NOLINT
	static inline date_t ninfinity() {return date_t(-std::numeric_limits<int32_t>::max()); } // NOLINT

Problem is caused by the <Windows.h> header file that includes macro definition max:
#define max(a,b) (((a) > (b)) ? (a) : (b))

Workaround:
#define NOMINMAX

**Comment by hannes** [comment]
Could you please make this a reproducible example instead of just posting compiler errors, for example, how is your project setup, which version of msvc are you using on which version of windows etc.

**Comment by Tishj** [comment]
As much as this is definitely not the way issue submission works, there is a point to be made here
We use `using namespace std;` in `test_buffer_manager.cpp` and then we also define a `align` function, which conflicts with `std::align`

**Comment by Tishj** [comment]
> One more issue on Windows while trying to compile C++ app...
> 
> Error C2589 '(': illegal token on right side of '::' on: ...\src\include\duckdb\common\types.hpp static inline date_t infinity() {return date_t(std::numeric_limits<int32_t>::max()); } // NOLINT static inline date_t ninfinity() {return date_t(-std::numeric_limits<int32_t>::max()); } // NOLINT
> 
> Problem is caused by the <Windows.h> header file that includes macro definition max: #define max(a,b) (((a) > (b)) ? (a) : (b))
> 
> Workaround: #define NOMINMAX

This second one makes no sense though, that just sounds like MSVC has a broken compiler, it explicitly uses `std::numeric_limits<int32_t>::max()` how that collides with something named `max` is just horrible design

If I didn't already heavily dislike windows developer environment, this would be a good reason to start <https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max>

I guess we can add NOMINMAX to the place where we include `windows.h` - not a "workaround" but definitely just a fix for a very broken and stupid decision made by windows 👍

**Comment by Mytherin** [comment]
The min/max thing is a known issue with windows, which is why we have the [windows undefs](https://github.com/duckdb/duckdb/blob/0f0461113f3341135471805c9928c4d71d1f5874/src/include/duckdb/common/windows_undefs.hpp#L4), our own [NumericLimits class](https://github.com/duckdb/duckdb/blob/0f0461113f3341135471805c9928c4d71d1f5874/src/include/duckdb/common/limits.hpp#L4) and our own implementations of [min/max](https://github.com/duckdb/duckdb/blob/0f0461113f3341135471805c9928c4d71d1f5874/src/include/duckdb/common/helper.hpp#L71). I wonder why this wasn't caught by the CI?

**Comment by Tishj** [comment]
> The min/max thing is a known issue with windows, which is why we have the [windows undefs](https://github.com/duckdb/duckdb/blob/0f0461113f3341135471805c9928c4d71d1f5874/src/include/duckdb/common/windows_undefs.hpp#L4), our own [NumericLimits class](https://github.com/duckdb/duckdb/blob/0f0461113f3341135471805c9928c4d71d1f5874/src/include/duckdb/common/limits.hpp#L4) and our own implementations of [min/max](https://github.com/duckdb/duckdb/blob/0f0461113f3341135471805c9928c4d71d1f5874/src/include/duckdb/common/helper.hpp#L71). I wonder why this wasn't caught by the CI? Or perhaps the issue is not with compiling DuckDB but including the duckdb headers in a project that also includes Windows.h?

Yea that was my idea just now as well:

> git commit -m "include windows.hpp, to avoid collision with 'max' defined by windows if NOMINMAX
 is not set - though I doubt this fixes it if windows.h is already included by the user before including duckdb"
[test_buffer_manager_no_using_std 38346fd894] include windows.hpp, to avoid collision with 'max' defined by windows if NOMINMAX is not set - though I doubt this fixes it if windows.h is already included by the user before including duckdb
