### ISSUE TITLE
Python API no longer allows "COPY" statements in v0.6

### ISSUE THREAD

**Issue by erikcw** [duckdb/duckdb#5380]
### What happens?

Prior to version 0.6, `DuckDBPyRelation.query` supported the `COPY` statement.  I used this to perform some ETL work on parquet files in a data pipeline (parquet input, transform, parquet and csv output).  After upgrading to `0.6`, this now produces an `InvalidInputException`.

### To Reproduce

My own usecase is far more complicated, but here is the minimum needed to reproduce.

```python
import duckdb
from pathlib import Path

local_path = Path("/tmp/test.parq")

rel = duckdb.from_parquet(str(local_path))

# Select subset of columns and write output to new parquet file.
rel.project("col_a, col_b, col_c").query(
    "tmp_table", 
    """
    COPY (SELECT * FROM tmp_table)
    TO '/tmp/out.parq' (FORMAT 'PARQUET', CODEC 'SNAPPY')
    """
)



InvalidInputException                     Traceback (most recent call last)
Cell In [19], line 1
----> 1 rel.project("first_name, last_name").query(
      2     "tmp_table",
      3     """
      4     COPY (SELECT * FROM tmp_table)
      5     TO '/tmp/out.parq' (FORMAT 'PARQUET', CODEC 'SNAPPY')
      6     """
      7 )

InvalidInputException: Invalid Input Error: 'DuckDBPyRelation.query' does not accept statements of type COPY



```

### OS:

MacOS and Linux (arm)

### DuckDB Version:

0.6.0

### DuckDB Client:

Python

### Full Name:

Erik Wickstrom

### Affiliation:

LiftCertain

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hi, thanks for the report.

I can see that this is an issue.. I thought we had another type of method to perform generic queries, the idea is that this does not produce another relation. And `query` returns a DuckDBPyRelation, so in that regard it makes sense to not support these types of queries here.

But now there is not a nice way to finalize your chain with a consumption of the relation
As a workaround currently, you can do this:
```py
view = rel.project("i").create_view("tmp_table")
duckdb.default_connection.execute(
	"""
    COPY (SELECT * FROM tmp_table)
    TO 'tmp/out.parq' (FORMAT 'PARQUET', CODEC 'SNAPPY')
	"""
)
```

**Comment by Tishj** [comment]
We have a `write_csv` method on a relation, maybe a good way to support this is a `write_parquet` function.
Though that's only a very targeted fix, not a replacement for the functionality we lost here
