### ISSUE TITLE
how to json_each_text in duckdb

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#5384]
I use duckdb to rewrite pg sql,:
`SELECT * FROM json_each_text('{"a": 1, "b": 2, "c":3}')`
```
key	value
a	1
b	2
c	3
```
how to do same affect in duckdb? thanks!

**Comment by lnkuiper** [comment]
Duplicate of #3578

**Comment by omo** [comment]
(Unsolicited triage) Let's close this since it is a duplicate. @lnkuiper
