### ISSUE TITLE
[Dev] Update the constants in the codebase to reflect the new STANDARD_VECTOR_SIZE (1024 -> 2048)

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#5391]
I've been seeing a couple places (like ROWGROUP_SIZE) where `STANDARD_VECTOR_SIZE * X` is used logically should that not be changed now that the vector size is twice as big?

(This might be more of a discussion, not an issue..)

**Comment by Mytherin** [comment]
Yes, those should be updated
