### ISSUE TITLE
Resource temporarily unavailable during JDBC database creation

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#5394]
### What happens?

Ever since we upgraded to 0.6.0 yesterday we've seen a few instances of DuckDB throwing an exception during database creation. We simply get `java.sql.SQLException: Resource temporarily unavailable`. Unfortunately this immediately causes the JVM to receive a SEGV and crash.

Here's a relevant stack trace.
```
java.sql.SQLException: Resource temporarily unavailable
at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:28)
at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:36)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
```

### To Reproduce

No known means to reproduce at this time.

### OS:

Linux

### DuckDB Version:

0.6.0

### DuckDB Client:

JDBC

### Full Name:

Michael Albers

### Affiliation:

Mode Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
At the risk of linking information that's already known:
https://stackoverflow.com/a/14370767
https://stackoverflow.com/a/14374796

These seem to suggest that too much data is sent at once, which would result in the send being a block operation, but the socket is set to non-blocking?

**Comment by michaeljohnalbers** [comment]
Closing this as we've not come across this error again since this was written.
