### ISSUE TITLE
Prepared insert statement executes several times slower after inserting null-value

### ISSUE THREAD

**Issue by olegel** [duckdb/duckdb#5396]
Prepared insert statements execute several times slower after inserting null-value or value of different type.
See C++ code below to reproduce.
Insert 10000 numbers into table using prepared insert statement.
Repeat this twice.
Result:
stage 1 **522.051 ms**
stage 2 **461.381 ms**
Both batches executing time is almost equal.

Insert null between batches. (uncoment line -> **prepared->Execute( Value() );** )

Result:
stage 1 **569.16 ms**
stage 2 **1618.51 ms**

Second batch executes almost 3 times slower!
**DuckDb v0.4 is not affected
DuckDb v0.6 is affected**
```cpp
		DuckDB db( nullptr );
		Connection con( db );

		con.SetAutoCommit( true );
		con.Query( "CREATE TABLE integers(Id INTEGER)" );

		unique_ptr<PreparedStatement> prepared = con.Prepare( "INSERT INTO integers VALUES (?)" );

		auto iteration_count = 10000;

		// client_context.cpp(693):
		// if (prepared->RequireRebind(*this, *parameters.parameters)) 
		// does not hit on every insert

		auto start1 = std::chrono::high_resolution_clock::now();
		{
			con.BeginTransaction();

			for ( int i = 0; i < iteration_count; ++i )
				prepared->Execute( i );

			con.Commit();
		}
		std::chrono::duration<double, std::milli> elapsed1 = std::chrono::high_resolution_clock::now() - start1;

		{
			con.BeginTransaction();

			// if uncomment 

			// prepared->Execute( Value() ); // or prepared->Execute( "0" ); // it can be any covertible value

			// then
			// client_context.cpp(693):
			// if (prepared->RequireRebind(*this, *parameters.parameters)) 
			// hit on every insert
			// following inserts are slower than previous

			con.Commit();
		}

		auto start2 = std::chrono::high_resolution_clock::now();
		{
			con.BeginTransaction();

			for ( int i = 0; i < iteration_count; ++i )
				prepared->Execute( i );

		}
		std::chrono::duration<double, std::milli> elapsed2 = std::chrono::high_resolution_clock::now() - start2;

		std::cout << "stage 1 " << elapsed1.count() << " ms\n";
		std::cout << "stage 2 " << elapsed2.count() << " ms\n";

```

**Comment by Alex-Monahan** [comment]
Could this be caused by the improved compression? Is the behavior the same when turning that off?
`pragma force_compression='uncompressed'`

**Comment by olegel** [comment]
> Could this be caused by the improved compression? Is the behavior the same when turning that off? `pragma force_compression='uncompressed'`

No, it always tries to re-prepare statement after null value processed

**Comment by Mytherin** [comment]
This is caused by the new prepared statement rebinding code - we could fix this by keeping a cache of the query plans for each of the input types.

As a side note - if you want to append data from within C++ then prepared statements are the wrong way to do it. The Appender interface will be significantly faster.

**Comment by olegel** [comment]
> This is caused by the new prepared statement rebinding code - we could fix this by keeping a cache of the query plans for each of the input types.

If it helps, any inserts after NUL is slow, event with the same value type as field(INT in this case):
Prepared Insert(1) - fast
Prepared Insert(2) - fast
Prepared Insert(NUL) - slow
Prepared Insert("0") - slow
Prepared Insert(3) - slow
Prepared Insert(4) - still slow

> As a side note - if you want to append data from within C++ then prepared statements are the wrong way to do it. The Appender interface will be significantly faster.

I'd like to use appenders, but unfortunately they don't work with temporary tables (It can't find table).
But I've checked appenders too. Appending of NUL is very slow, about 20 times.
**0.6552 ms** - add 10000 rows with numbers then Flush
**12.1868 ms** - - add 10000 rows with  NULs then Flush

**Comment by Mytherin** [comment]
> I'd like to use appenders, but unfortunately they don't work with temporary tables (It can't find table).

Could you file a bug report for that? That is not intentional.

> But I've checked appenders too. Appending of NUL is very slow, about 20 times.

Are you appending a Value or a nullptr? That takes a very different codepath. Anything involving Values is slow generally.
