### ISSUE TITLE
ODBC read only connection

### ISSUE THREAD

**Issue by j4david** [duckdb/duckdb#5421]
Please,

consider enabling a read-only connection via odbc.

I am using the odbc driver provided by you with Power BI, but I am having problems adding more than one table from a DuckDB database. I think the problem is that when I try to connect to a second table, it opens a new connection and both are blocked, giving error. For now I have solved it, disabling concurrent loading in Power BI, but it would be nice to allow read-only connections via ODBC.

I have tried adding read mode as a database parameter, the way it is done in sqlite, but it doesn't work:

database=file:///path/to/database.duckdb?mode=ro; dsn=DuckDB; uri=True;

Thank you very much for all your work and for giving us this great software.

Best regards.

**Comment by Mause** [comment]
Hi, you can already set an ODBC connection as read only via the `SQL_ATTR_ACCESS_MODE` attribute (setting it to `SQL_MODE_READ_ONLY`)

**Comment by j4david** [comment]
Hello,

I don't know how to do it.
What option I have to pass to the connection string for read_only?

Thanks

**Comment by derrickturk** [comment]
Hi everyone - I found this issue perhaps for a similar reason as @j4david opened it, namely that a lot of the Microsoft analytics stack (Excel/PowerQuery/PowerBI) only provides end users with the ability to configure ODBC connections via connection string.

I've written a trivial patch which allows connection strings to specify "ReadOnly=True" to enable the mode mentioned by @Mause on the connection. If there's interest (I need this to allow multiple Excel workbooks to concurrently query the same DuckDB file in read-only mode), I'm happy to open a PR, add any requested tests, etc. Please let me know!

See https://github.com/derrickturk/duckdb/tree/odbc-readonly.

**Comment by derrickturk** [comment]
@SeungHuLee if I get a chance later this week or next, I'll try to rebase myself up-to-date and see if the patch still makes sense, and possibly create a PR.
