### ISSUE TITLE
Binder Error when using read_csv_auto()

### ISSUE THREAD

**Issue by Imaclean74** [duckdb/duckdb#5423]
when using the read_csv_auto function to import data I'm getting the following error.

Command
```sql
 select * from read_csv_auto( "test.csv" );
```
```
Error: Binder Error: TABLE FUNCTION parameter cannot contain column names```

where test.csv looks like :

```csv
A,B,C
1,2,3
5,6,7
```
the content of the file doesn't seem to matter. And a simple ```select * from read "test.csv"; ```  *does* work. However with a larger file I'm working with it fails to detect the first line as the header. Which is why I'm wanting to use the function.

This is using DuckDB v0.6.0 2213f9c94 on RHEL8

I'm pretty sure This wasn't happening with the previous version. I upgraded last Friday.

**Comment by Mause** [comment]
Hi, in DuckDB SQL, table names are quoted using double quotes (`"`), and strings/varchars are quoted using single quotes (`'`). Hope this helps!

**Comment by Imaclean74** [comment]
aah ok. Yes - that works now. However the error message doesn't give much indication of what the real issue is. Any way that can be improved ?

**Comment by Imaclean74** [comment]
oh and thanks for the super quick turnaround !
