### ISSUE TITLE
explain result shown by python is hard to read

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5428]
### What happens?

it prints \n instead of new line

### To Reproduce

```python
>>> import duckdb
>>> con = duckdb.connect()>>> con.execute("select version()");
<duckdb.DuckDBPyConnection object at 0x00000000040F5270>
>>> print(con.fetchall())
[('0.5.1',)]
>>> con.execute("explain select version()");
<duckdb.DuckDBPyConnection object at 0x00000000040F5270>
>>> print(con.fetchall())
[('physical_plan', "┌───────────────────────────┐\n│         PROJECTION        │\n│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
   │\n│          '0.5.1'          │\n└─────────────┬─────────────┘                             \n┌─────────
────┴─────────────┐\n│         DUMMY_SCAN        │\n└───────────────────────────┘
          \n")]
```

### OS:

windows 7

### DuckDB Version:

0.5.1

### DuckDB Client:

python

### Full Name:

luato

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
more readable by following code
```python
>>> con.execute("explain select version()");
<duckdb.DuckDBPyConnection object at 0x00000000040F5270>
>>> x=con.fetchall()
>>> for i in x[0][1].split('\n'):print(i)
...
...
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          '0.5.1'          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘
```

**Comment by Tishj** [comment]
We're looking at printing results differently based on the environment it's executed in, this is a good example of a place where this should be done, as newlines don't get interpreted properly in interactive mode :)

**Comment by Mause** [comment]
The newlines being escaped are a feature of repr vs str - if you `print(x[0][1])` you shouldn't need the loop or split

**Comment by l1t1** [comment]
@Mause you are right
