### ISSUE TITLE
Python crashes with struct_insert

### ISSUE THREAD

**Issue by Dino-Burger** [duckdb/duckdb#5437]
### What happens?

Adding values to a struct crashes my python.

### To Reproduce

```py
import duckdb

sql= """
with data as (
    Select * from (VALUES ('Amsterdam', {'x': 1, 'y': 2, 'z': 3}), ('London', {'x': 4, 'y': 5, 'z': 6})) Cities(Name, Id)
)

Select
    *,
    struct_insert(Id, d := 4)
from data
"""

duckdb.query(sql).df()
```

### OS:

Windows 10 Enterprise 21H2

### DuckDB Version:

0.6.0, 0.5.1, 0.6.1-dev32

### DuckDB Client:

Python

### Full Name:

Dino Burger

### Affiliation:

Crif AG

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Dino-Burger** [comment]
Hi All
This is my first bug report on github, so if I missed something let me know.

Regards

Dino

**Comment by Tishj** [comment]
Hey, thanks for raising the issue!

The bug report is fine, the steps you provided reproduce the issue in a small amount of steps, that's the most important thing 👍 

One thing, you can use:
\`\`\`py
code
\`\`\`

in the future, to produce something like:
```py
import duckdb

sql= """
with data as (
Select * from (VALUES ('Amsterdam', {'x': 1, 'y': 2, 'z': 3}), ('London', {'x': 4, 'y': 5, 'z': 6})) Cities(Name, Id)
)

Select
*,
struct_insert(Id, d := 4)
from data
"""

duckdb.query(sql).df()
```

**Comment by Tishj** [comment]
Also crashes in the cli (unit tester)
```sql
statement ok
pragma enable_verification;

statement ok
with data as (
select * from (VALUES ('Amsterdam', {'x': 1, 'y': 2, 'z': 3}), ('London', {'x': 4, 'y': 5, 'z': 6})) Cities(Name, Id)
)
select *, struct_insert(Id, d := 4)
from data
```

**Comment by Dino-Burger** [comment]
Hi Tishj

Cool, thanks! I updated the report as you suggested, and will install the cli for the future.

Regards

**Comment by Tishj** [comment]
Oh that's not necessary, just noting down findings :)
