### ISSUE TITLE
Null bytes cause string termination for python bytearray

### ISSUE THREAD

**Issue by camdencheek** [duckdb/duckdb#5443]
### What happens?

When inserting a python `bytearray` that contains null bytes, the value is truncated to the first null byte. Note that this does not happen for the python `bytes` type. 

### To Reproduce

```python
import duckdb

con = duckdb.connect(database=':memory:')
con.execute("CREATE TABLE test (content BLOB)")
want = bytearray([1, 2, 0, 3, 4])
con.execute("INSERT INTO test VALUES (?)", [want])
con.execute("SELECT * from test")
got = bytearray(con.fetchall()[0][0])
print(want, got) # bytearray(b'\x01\x02\x00\x03\x04') bytearray(b'\x01\x02')
assert want == bytearray(got)
```

### OS:

MacOS Ventura, arm64

### DuckDB Version:

v0.6.0

### DuckDB Client:

Python

### Full Name:

Camden Cheek

### Affiliation:

Sourcegraph

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Ah I see the issue
```c++
	case PythonObjectType::ByteArray: {
		auto byte_array = ele.ptr();
		auto bytes = PyByteArray_AsString(byte_array);
		return Value::BLOB_RAW(bytes);
	}
```
we get the byte array as a string, but the BLOB_RAW(const char*) constructor checks for a nullbyte, we need to get the length and then use a different constructor that takes a length 👍
