### ISSUE TITLE
`IDate` class (an experimental class within R's data.table package) crashes duckdb's dbWriteTable method

### ISSUE THREAD

**Issue by ajdamico** [duckdb/duckdb#5450]
### What happens?

https://youtu.be/tfQs7WbVse8?t=84

### To Reproduce

	library(DBI)
	x <- data.frame(data.table::as.IDate("2001-01-01"))
	con <- dbConnect( duckdb::duckdb() , dbdir = tempfile() )
	dbWriteTable( con , "x" , x )

### OS:

windows 10 x64

### DuckDB Version:

0.5.1

### DuckDB Client:

R

### Full Name:

Anthony Damico

### Affiliation:

independent consultant

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
At the very least it should not crash, thanks for the report, going to have a look.

**Comment by hannes** [comment]
Should be fixed
