### ISSUE TITLE
Memory Cost Increase Too Fast When Frequently Insert and Delete Rows (compared with 0.5.1)

### ISSUE THREAD

**Issue by foTok** [duckdb/duckdb#5455]
### What happens?

When there exist many insertions/deletes/updates, memory increase visibly even the number of rows does not change.

Is there any inner mechanism change from 0.5.1 to 0.6.0?

### To Reproduce

1. create a database in file mode.
2. create a table and load some data into the table.
3. randomly select some data insert into the table, and then delete them (the randomly inserted rows), to keep the row number a constant.
4. If insert and delete 500 rows per second， the memory will increase greater than 1G in 1 hour.

In 0.5.1, memory increasing is slow, and the increasing is even invisible if perserve_insertion_order = false.
However, in 0.6.0, the memory increases too fast.

### OS:

centos 7

### DuckDB Version:

0.6.0

### DuckDB Client:

C++

### Full Name:

wenfeng

### Affiliation:

--

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Have you tried setting a memory limit with `pragma memory_limit='Xgb';`? DuckDB's buffer manager will keep blocks around in memory for later, even if they are not needed right now. By setting the memory limit you force DuckDB to get rid of these blocks, which might help.

Insertions have indeed changed in 0.6.0. We have improved our bulk updates. Adding to that: inserting/deleting 500 rows per second is not DuckDB's intended use case, so we have not optimized for this. See "When to not use DuckDB" on [duckdb.org](https://duckdb.org)

**Comment by foTok** [comment]
> 

Hi, I found an interesting thing.

V0.6.0
-->After run a long, I found the memory managed by DB is 1.6GB
(got by "con->Query("PRAGMA database_size")->Print(); // get db information")
2022-11-22 16:58:17
database_size	block_size	total_blocks	used_blocks	free_blocks	wal_size	memory_usage	memory_limit	
VARCHAR	BIGINT	BIGINT	BIGINT	BIGINT	VARCHAR	VARCHAR	VARCHAR	
[ Rows: 1]
107.7MB	262144	411	379	32	952.1MB	1.6GB	13.3GB

-->However, the memory cost by the program in the system is over 8GB
2022-11-22 16:58:57
DuckDBVerification VSZmem: 8533204 VmRSS: 8225728 kB CPU: 264
![image](https://user-images.githubusercontent.com/4091925/203487005-8b934542-fc54-4a3e-87b3-22ca4b7f0fde.png)




-->V0.5.1 with the same code
2022-11-15 08:54:04
database_size	block_size	total_blocks	used_blocks	free_blocks	wal_size	memory_usage	memory_limit	
VARCHAR	BIGINT	BIGINT	BIGINT	BIGINT	VARCHAR	VARCHAR	VARCHAR	
[ Rows: 1]
2.6GB	262144	10239	9948	291	844.9MB	4.5GB	13.3GB

-->The memory cost in the system is less than 8GB with 4.5GB for DB.
2022-11-15 08:53:02
DuckDBVerification VSZmem: 9004996 VmRSS: 7286000 kB CPU: 247.
![image](https://user-images.githubusercontent.com/4091925/203487120-637b407e-fc19-47ac-a72b-4bbec5ec55ea.png)

**Comment by foTok** [comment]
Hi, I re-tested for several times and found the following phenomenon:
The memory increasing seems to be caused by temporary table.

Test Step:
1. Create a DB in file mode.
2. Load Some data.
3. Build a connection ~ **con**.
4. Build several temporary tables with **con** by "CREATE TEMP TABLE XXXX".
5. Run several queries within **con**, which insert data into the temporary tables above.
6. Repeat step 3 ~ 5 in a loop. 

Every time 5 back to 3, **con** is destructed and all temporary data are drop theoretically.
However, the stable memory cost increased from 0.5GB to 0.8GB in half an hour.

**Comment by foTok** [comment]
> Have you tried setting a memory limit with `pragma memory_limit='Xgb';`? DuckDB's buffer manager will keep blocks around in memory for later, even if they are not needed right now. By setting the memory limit you force DuckDB to get rid of these blocks, which might help.
> 
> Insertions have indeed changed in 0.6.0. We have improved our bulk updates. Adding to that: inserting/deleting 500 rows per second is not DuckDB's intended use case, so we have not optimized for this. See "When to not use DuckDB" on [duckdb.org](https://duckdb.org)

**Comment by foTok** [comment]
> Have you tried setting a memory limit with `pragma memory_limit='Xgb';`? DuckDB's buffer manager will keep blocks around in memory for later, even if they are not needed right now. By setting the memory limit you force DuckDB to get rid of these blocks, which might help.
> 
> Insertions have indeed changed in 0.6.0. We have improved our bulk updates. Adding to that: inserting/deleting 500 rows per second is not DuckDB's intended use case, so we have not optimized for this. See "When to not use DuckDB" on [duckdb.org](https://duckdb.org)

Hi, I re-tested for several times and found the following phenomenon:
The memory increasing seems to be caused by temporary table.

Test Step:

Create a DB in file mode.
Load Some data.
Build a connection ~ con.
Build several temporary tables with con by "CREATE TEMP TABLE XXXX".
Run several queries within con, which insert data into the temporary tables above.
Repeat step 3 ~ 5 in a loop.
Every time 5 back to 3, con is destructed and all temporary data are drop theoretically.
However, the stable memory cost increased from 0.5GB to 0.8GB in half an hour.

**Comment by lij55** [comment]
I hit a similar issue. I'm trying to import big csv files, which lead to about 100G used memory now. does duckdb keep all text in  memory even after writing to disk?
<img width="915" alt="Screen Shot 2022-11-29 at 12 07 38" src="https://user-images.githubusercontent.com/12248266/204436883-5b5a1771-798c-4292-8549-358532dfaaa5.png">

**Comment by Mytherin** [comment]
DuckDB keeps data cached in memory until the memory limit is reached. If your memory limit is set higher than 100GB it is expected that memory usage can reach 100GB as DuckDB will keep the entire table cached in memory to speed up subsequent queries.

**Comment by foTok** [comment]
> 

Hi, I noticed # 5501 has been fixed. So, I retested.
In static situation, where no data are updated in the DB, temporary resources are released correctly, and the memory keeps stable.

**However, when the DB are updated dynamically, the memory increases rapidly. **
Duck told me the DB used 1.1GB, as follows:

2022-12-05 10:11:37
database_size	block_size	total_blocks	used_blocks	free_blocks	wal_size	memory_usage	memory_limit	
VARCHAR	BIGINT	BIGINT	BIGINT	BIGINT	VARCHAR	VARCHAR	VARCHAR	
[ Rows: 1]
107.4MB	262144	410	332	78	259.1MB	1.1GB	13.3GB


While the process cost more than 4GB!!!
2022-12-05 10:11:37
DuckDBVerification VSZmem: 4036612 VmRSS: 1692488 kB CPU: 264

**Comment by foTok** [comment]
> DuckDB keeps data cached in memory until the memory limit is reached. If your memory limit is set higher than 100GB it is expected that memory usage can reach 100GB as DuckDB will keep the entire table cached in memory to speed up subsequent queries.

Hi, I noticed # 5501 has been fixed. So, I retested.
In static situation, where no data are updated in the DB, temporary resources are released correctly, and the memory keeps stable.

**However, when the DB are updated dynamically, the memory increases rapidly. **
Duck told me the DB used 1.1GB, as follows:

2022-12-05 10:11:37
database_size block_size total_blocks used_blocks free_blocks wal_size memory_usage memory_limit
VARCHAR BIGINT BIGINT BIGINT BIGINT VARCHAR VARCHAR VARCHAR
[ Rows: 1]
107.4MB 262144 410 332 78 259.1MB 1.1GB 13.3GB

While the process cost more than 4GB!!!
2022-12-05 10:11:37
DuckDBVerification VSZmem: 4036612 VmRSS: 1692488 kB CPU: 264

**Comment by foTok** [comment]
The case happens especially WAL file >= 300MB.

**Comment by foTok** [comment]
> DuckDB keeps data cached in memory until the memory limit is reached. If your memory limit is set higher than 100GB it is expected that memory usage can reach 100GB as DuckDB will keep the entire table cached in memory to speed up subsequent queries.

Seems solved by #5698.
