### ISSUE TITLE
Access to parquet files in GCS raise error 403 when they are in a folder

### ISSUE THREAD

**Issue by XWilddogX** [duckdb/duckdb#5464]
### What happens?

I'm trying to query parquet files inside a folder in a bucket in hive partitioning, but when i try to access any of that files in a folder client raises 403.

In the other hand, when i try to query a parquet file outside a folder works fine.

There is no bucket folder level security

### To Reproduce

Query a folder in gcs like this:
INSTALL httpfs;
LOAD httpfs;
SET s3_endpoint='storage.googleapis.com';
SET s3_access_key_id='HMAC access key';
SET s3_secret_access_key='HMAC secret key';
SET s3_url_style='path';

SELECT * FROM read_parquet('s3://gcs-bucket/folder/file.parquet')

### OS:

Ubuntu 18.10

### DuckDB Version:

0.6.0

### DuckDB Client:

JDBC/Dbeaver

**Comment by hannes** [comment]
Can you try to create a publicly available file on GCS to demonstrate the issue?

**Comment by XWilddogX** [comment]
![image](https://user-images.githubusercontent.com/33205829/203724539-13547675-d07b-4b8a-81e0-839447fdcb06.png)
works fine
in folder
![image](https://user-images.githubusercontent.com/33205829/203725090-854e994c-3eab-4318-927d-11b579285e3e.png)

**Comment by XWilddogX** [comment]
Images reproducing the issue is enough?

**Comment by hannes** [comment]
I'm afraid not

**Comment by hannes** [comment]
Also, any reason you only filled out part of the issue template?

**Comment by baon1010** [comment]
Is there a work-around for this. Having same problem

**Comment by XWilddogX** [comment]
Well there is not, you can use GCS Fuse (https://cloud.google.com/storage/docs/gcs-fuse) to sync on your on premise machine, in a serverless solution (my case) i'm uploading a CR container with the parquet files in it. also i want to test use GCS fuse mounted on a CR :https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse 
cheers

**Comment by baon1010** [comment]
This issue is closed... I'm having the same problem as reported here. Is there any way we can re-open this? Thank you!
