### ISSUE TITLE
CSV load: cli error if I specify COMPRESSION parameter

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb#5473]
### What happens?

I have a gzipped csv.

If I set COMPRESSION parameter I have import error.

### To Reproduce

If I run

```
duckdb --csv  -c "SELECT * FROM read_csv_auto('input.csv.gz', delim='|', header=True,COMPRESSION=gzip)"
```

I have

```
Error: Binder Error: TABLE FUNCTION parameter cannot contain column names
```

If I remove `COMPRESSION=gzip` I have the output

```
a,b
3,ciao
4,bau
```

### OS:

debian 11

### DuckDB Version:

v0.4.0 da9ee490d

### DuckDB Client:

CLI

### Full Name:

Andrea Borruso

### Affiliation:

onData

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Can you try putting either single or double quotes around `gzip` ? (I think it's single quotes)
I think it's reading `gzip` as a column reference, not a string literal

**Comment by aborruso** [comment]
I'm very sorry @Tishj thank you

**Comment by Tishj** [comment]
No problem :)
Maybe we should improve the docs, it also doesn't mention that the options have to be provided as string literals

**Comment by Mytherin** [comment]
I have decided to allow this in #5483 as this has been confusing several people already

**Comment by aborruso** [comment]
> I have decided to allow this in #5483 as this has been confusing several people already and allowing it does not cause any issues with regards to ambiguity

Thank you
