### ISSUE TITLE
R: the process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by ggpinto** [duckdb/duckdb#5481]
### What happens?

When using DuckDB R client to write a table, right after closing the connection it is not possible to connect again to read the data.

The error is

```
#> Error: rapi_startup: Failed to open database: IO Error: Cannot open file "C:\Users\user\AppData\Local\Temp\RtmpCcJ3O7\file3d4c72b44eb9.duckdb": The process cannot access the file because it is being used by another process.
```

### To Reproduce

``` r
copy_table <- function(table) {
  
  tempdb <- base::tempfile(fileext = ".duckdb")
  
  conn <- DBI::dbConnect(
    duckdb::duckdb(),
    dbdir = tempdb,
    read_only = FALSE
  )
  
  dplyr::copy_to(
    conn,
    table
  )
  
  return(tempdb)
  
  on.exit(DBI::dbDisconnect(conn))
}

tempdb <- copy_table(mtcars)

conn <- DBI::dbConnect(
  duckdb::duckdb(),
  dbdir = tempdb,
  read_only = FALSE
)
#> Error: rapi_startup: Failed to open database: IO Error: Cannot open file "C:\Users\user\AppData\Local\Temp\RtmpCcJ3O7\file3d4c72b44eb9.duckdb": The process cannot access the file because it is being used by another process.
```

<sup>Created on 2022-11-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

Windows 10

### DuckDB Version:

0.6.0

### DuckDB Client:

R

### Full Name:

Guilherme Pinto

### Affiliation:

ASMPT SMT Solutions

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Windows is pretty notorious in being slow to clear file locks.

**Comment by ggpinto** [comment]
> Windows is pretty notorious in being slow to clear file locks.

On Linux it works like a charm.

**Comment by rsund** [comment]
Maybe this is not relevant in your use case, but what if you move `on.exit(DBI::dbDisconnect(conn))` to be before `return` and change it to `DBI::dbDisconnect(conn, shutdown=TRUE)`, i.e. without `on.exit` and `shutdown=TRUE` added?

**Comment by ggpinto** [comment]
With `shutdown = TRUE` it works:

``` r
copy_table <- function(table) {
  
  tempdb <- base::tempfile(fileext = ".duckdb")
  
  conn <- DBI::dbConnect(
    duckdb::duckdb(),
    dbdir = tempdb,
    read_only = FALSE
  )
  
  dplyr::copy_to(
    conn,
    table
  )
  
  on.exit(DBI::dbDisconnect(conn, shutdown = TRUE))
  
  return(tempdb)
  
}

tempdb <- copy_table(mtcars)

conn <- DBI::dbConnect(
  duckdb::duckdb(),
  dbdir = tempdb,
  read_only = FALSE
)
```

<sup>Created on 2022-11-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks!
