### ISSUE TITLE
Homebrew duckdb package missing Zstd support?

### ISSUE THREAD

**Issue by jaens** [duckdb/duckdb#5486]
### What happens?

Looks like the default version in Homebrew does not have Zstd compression built in, making it a bit crippled as-is...

Would probably be useful to bundle it.

cc @hannes #446

### To Reproduce

```
$ brew info duckdb
==> duckdb: stable 0.6.0 (bottled)
Embeddable SQL OLAP Database Management System
https://www.duckdb.org
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/duckdb.rb
License: MIT
==> Dependencies
Build: cmake ✘, python@3.11 ✘
$ brew install duckdb
$ duckdb test.db
D create table test_csv as select * from read_csv('test.csv.zst');
Error: Not implemented Error: Attempting to open a compressed file, but the compression type is not supported
D create table test_csv as select * from read_csv('test.csv.zst',  compression='zstd');
Error: Not implemented Error: Attempting to open a compressed file, but the compression type is not supported
```

### OS:

Linux x64

### DuckDB Version:

0.6.0

### DuckDB Client:

Homebrew

### Full Name:

Jaen

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jaens** [comment]
Thank you for the workaround! (in the end I installed it from Nix instead, which does have it built-in)

**Comment by carlopi** [comment]
I think this is currently (as of 0.6.1) solved, could you possibly give a try to verify?
```
brew install duckdb
```
