### ISSUE TITLE
DuckCon 2023 - 2nd edition

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#5494]
We are excited to invite you all for our second "DuckCon" user group meeting. It will take place the day before @fosdem in Brussels on Friday Feb 3rd, 2023. In-person pandemic permitting. 

Agenda and registration: https://duckdb.org/2022/11/25/duckcon.html

**Comment by voberoi** [comment]
Hi!

You mention two items on the duckcon page that I don't see available in a recent release (0.6.0). 
Those two things are:

* A JSON scanner: "... DuckDB supports various data scanners (e.g., parquet, CSV, arrow, JSON) ..."
* An extension scaffold.

Are you releasing these things at/after Duckcon? Are they currently undocumented items?

**Comment by Alex-Monahan** [comment]
Hello! These capabilities exist today! The JSON extension is documented here:
https://duckdb.org/docs/extensions/json

The extension scaffold isn't as well socumented yet, but an example is here:
https://github.com/duckdb/duckdb/tree/master/extension/inet

**Comment by voberoi** [comment]
Thank you!

**Comment by voberoi** [comment]
@Alex-Monahan -- is there a JSON scanner though? A way to, e.g. read directly from line-delimited JSON objects?

I'm aware of the JSON extension but the scanner is what caught my eye.

**Comment by Alex-Monahan** [comment]
Yes! The ability to scan non-newline delimited JSON is coming soon too!
The function is `read_json_objects(filename)`
https://duckdb.org/docs/extensions/json

**Comment by voberoi** [comment]
D'oh! Missed that.

Thanks for the tip!

**Comment by michaeljohnalbers** [comment]
Will there be a remote option to attend?

**Comment by hannes** [comment]
@michaeljohnalbers we will most likely record the presentations, and possibly livestream the event.

**Comment by pgzmnk** [comment]
Congrats on the event! Looking forward to the recordings.

**Comment by hannes** [comment]
We will start posting the recordings over the next couple of days, starting with "State of the Duck" by @Mytherin and me: https://www.youtube.com/watch?v=rdnPkLSkoyU
