### ISSUE TITLE
JDBC Squirrel connection asking for password in .6 Was working in .5.9

### ISSUE THREAD

**Issue by bhalatest** [duckdb/duckdb#5498]
### What happens?

Using squirrel client with jdbc driver give this error. "Catalog error. Unrecognized configuration Parameter Password". 
This was working in .5.9 
I am leaving userid/password blank like I did in .5.9
 DBeaver connects but Squrrel is not. 
I dowloaded latest version of squirrel too 4.5.1 but issue is with older versions too.

### To Reproduce

Download squirrel from :
https://squirrel-sql.sourceforge.io/
In driver manegr add two drivers.
One for .5.9 other for .6.0
Create two aliases to some sample db.
.5.9 will connect but .6.0 will give the above errow.

### OS:

Windows

### DuckDB Version:

.6

### DuckDB Client:

JDBC 

### Full Name:

Bhala Ghatate

### Affiliation:

Daman

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
It looks like SQuirrel doesn't fully support databases that don't have a username and password? There's an open issue in the repo from 2007 (!!) https://sourceforge.net/p/squirrel-sql/bugs/556/

**Comment by bhalatest** [comment]
Thx, I have put in a comment on that issue. Since it is so old hope somoen responds. Let me find if we have any other approved software at out company to connect to duckdb with .6. We don't have DBeaver.
Till then we will need to fall back to .5.9

**Comment by hannes** [comment]
We could take the parameter and just ignore it?

**Comment by bhalatest** [comment]
Thx. Is there a built version of the jdbc driver I can download and try out.
