### ISSUE TITLE
Windows Python connect method is requiring drive name in .6. Was working without drive name in .5.9

### ISSUE THREAD

**Issue by bhalatest** [duckdb/duckdb#5499]
### What happens?

On windows when connecting via Python in the connect method I have to pass in the drive name in .60. 
In .5.9 drivename was not nessecary. 
E.g.. if dbfile is here f:\temp\sample.db  
I can't pass in \\temp\\sample.db or /temp/sample.db.  It prepends current path. 
e.g. if my current path is f:/myprogram it tries to open f:/myprogram/temp/sample.db  and fails.
This behavior is different from .5.9 

### To Reproduce

Create a db in a directory (f:\temp\sample.db). I acutally didn't check C drive but in my F drive.

IN a diffrent directory e.g.
f:/myprogram create a python program that just does a connect and passes in  \\temp\\sample.db or /temp/sample.db.
It will fail with cannot open in .6 but will work in .5.9

Now do a connect with
f:\\temp\\sample.db or f:/temp/sample.db.
It will work with .6

### OS:

windows 10 64

### DuckDB Version:

.6

### DuckDB Client:

Python

### Full Name:

Bhala Ghatate

### Affiliation:

Daman

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I'm having trouble understanding what you're trying to do, and what the issue/difference in behavior is you're experiencing

Are you saying that the `connect` method does not accept an absolute path i.e. `/temp/sample.db`
and instead treats this as a relative path?

Previously `/temp/sample.db` was treated as an absolute path, and now it requires the drive to also be part of the path in order for this to qualify as an absolute path.

Is that correct?

**Comment by bhalatest** [comment]
Yes. That is correct.
E.g. in python os.listdir() or reading a file it doesn't require the drive letter.
I.e if I am in f:\testdir as my current directory I can list a different directory on the same drive by using leading "\"
Was expecting similar behavior 

#listing current directory.
os.getcwd()
'f:\\testdir'
os.listdir()
['curdirtest.db', 'currdirreadme.txt']

#Now listing a different diretcory using leading "/"
os.listdir("/temp2")
['readme.txt', 'test.db']
os.listdir("f:/temp2")
['readme.txt', 'test.db']
os.listdir("\\temp2")
['readme.txt', 'test.db']

**Comment by Tishj** [comment]
Likely caused by this change:
https://github.com/Tishj/duckdb/commit/a9879b1094d23ff1aa44079815ae29d2f7a8f7a4

**Comment by Tishj** [comment]
We probably want to just rewrite PathIsRelative, no?
<https://www.pinvoke.net/default.aspx/shlwapi/PathIsRelative.html>

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed now in #7503.
