### ISSUE TITLE
How to connect to duckdb in PDI 8.3

### ISSUE THREAD

**Issue by hengaini2055** [duckdb/duckdb#5500]
![image](https://user-images.githubusercontent.com/20587475/204077056-d22049c7-d77f-42e6-a87c-511f544fc715.png)
I copy jar to data-integration/lib directory, and set as aboves. When I test the connection, as folllows：

![image](https://user-images.githubusercontent.com/20587475/204077109-8ecbae41-211b-4881-8046-0d2ea1acb5c0.png)

I don't know what's wrong?
![image](https://user-images.githubusercontent.com/20587475/204077153-b15103f4-dee2-468a-92b1-1e0a30d1dfc6.png)

**Comment by hengaini2055** [comment]
According to dbeaver connection url, **Custom Connection URL** should be "jdbc:duckdb:G:\temp\duckdb.db", So **Custom Driver Class Name** may ber wrong!

**Comment by hengaini2055** [comment]
**Custom Driver Class Name** is "org.duckdb.DuckDBDriver".

**Comment by Mause** [comment]
Yes, the driver class is called `org.duckdb.DuckDBDriver`.

You'll probably also want to use a more recent version of DuckDB, the latest is 0.6.0

**Comment by hengaini2055** [comment]
Yes, Thanks you. I will update to the latest version.
