### ISSUE TITLE
Segfault in NodeJS bindings when creating a table with an absolute path

### ISSUE THREAD

**Issue by ahwitz** [duckdb/duckdb#5507]
### What happens?

See repro steps, this is a weird one:

### To Reproduce

Create an `index.js` file:
```js
const path = require('path');

const {query, initDB} = require(path.join(__dirname, 'src', 'db.js'));

(async function () {
  await initDB();
})().catch((err) => console.error(err));
```

Create a `src/db.js` file:
```js
const path = require('path');

const duckdb = require('duckdb');

const dbFile = path.join(__dirname, 'data', 'database.db');
const db = new duckdb.Database(dbFile);

async function query(sql) {
  return new Promise((resolve, reject) => {
    db.run(sql, function (err, res) {
      if (err) return reject(err);
      resolve(res);
    });
  });
}

async function initDB() {
  await query('CREATE TABLE a(i integer);');
}

module.exports = {initDB, query};

```

As it is, that reliably segfaults. If you:
- Move everything except the `module.exports` line to `index.js`, it works fine
- Replace `dbFile` with `./data/database.db` (removing the absolute path), it works fine

I'm not sure what could be causing this, but reliably, if you `require` that module, and there's an absolute path in the `new duckdb.Database` constructor, it segfaults.

### OS:

Ubuntu 22.04 x64

### DuckDB Version:

Version included with npm 0.6.0

### DuckDB Client:

NodeJS

### Full Name:

Andrew Horwitz

### Affiliation:

independent work

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
For now, I believe you can get a proper error message and avoid the segfault using the error callback in the `Database` constructor

Or use https://www.npmjs.com/package/duckdb-async, which I think we're going to try to get included in the main duckdb package

**Comment by ahwitz** [comment]
Got around it by just using a hardcoded relative path, so this definitely isn't a hindrance at the moment. Good to know about the async lib though, thanks!

**Comment by omo** [comment]
(Unsolicited triage) Seems like WAI and the workaround is suggested. Maybe you can close this? @Mause
If there is any tracking bug for duckdb-async adoption, having the link here would be handy.
