### ISSUE TITLE
DBeaver Windows long paths do not work

### ISSUE THREAD

**Issue by ttomasz** [duckdb/duckdb#5508]
### What happens?

When file path is very long there is error that file doesn't exist.
The error appears only in DBeaver for me in python it works with either path.

Simple queries such as `select * from '<path>'`

I noticed that for those paths Windows Explorer shows them in full form but when viewing properties of file/folder the paths are shortened e.g.:
- regular path: `C:\folder_name\some_file.parquet`
- shortened path: `C:\FOLD~1\some_file.parquet`

Workaround:
1. Check shortened path in properties dialog for given file/folder (right click -> Properties)
2. Use shortened folder path

### To Reproduce

Create some very long folder name until you see that it is shortened in properties dialog.

### OS:

Windows

### DuckDB Version:

0.6.0

### DuckDB Client:

DBeaver

### Full Name:

Tomasz Taraś

### Affiliation:

DXC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by omo** [comment]
You might file a bug on https://github.com/dbeaver/dbeaver too. They'll be better at triaging the problem.
