### ISSUE TITLE
QUALIFY can evaluate in a misleading way

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#5510]
### What happens?

If you reuse a column name for the AS alias of a SELECT with a WINDOW function,
then reference that alias in a QUALIFY statement,
the QUALIFY will behave as a WHERE on the column,
and not on the WINDOW function defined in the SELECT clause.

It's especially perplexing to reproduce, because the QUALIFY appears to behave erratically unless you understand that it is actually behaving as a WHERE.

### To Reproduce

```sql
WITH data (ts, val) AS (
  VALUES
   ('2022-01-01', 2), -- should be omitted
   ('2022-01-02', 3),
   ('2022-01-03', 1), -- should be omitted
   ('2022-01-04', 2),
   ('2022-01-05', 3),
)

SELECT
  ts,
  val - lag(val, 1) OVER (ORDER BY ts) AS val,
FROM data
QUALIFY val > 0;
```

Yields:
```
┌────────────┬───────┐
│     ts     │  val  │
│  varchar   │ int32 │
├────────────┼───────┤
│ 2022-01-01 │       │
│ 2022-01-02 │     1 │
│ 2022-01-03 │    -2 │
│ 2022-01-04 │     1 │
│ 2022-01-05 │     1 │
```

Change: `AS val` and `QUALIFY val > 0` to: `AS val1` and `QUALIFY val1 > 0` and you get the desired behavior:
```
┌────────────┬───────┐
│     ts     │ val1  │
│  varchar   │ int32 │
├────────────┼───────┤
│ 2022-01-02 │     1 │
│ 2022-01-04 │     1 │
│ 2022-01-05 │     1 │
```

Additionally if the data happen to be:
```sql
   ('2022-01-03', 0), -- should be omitted
```
then it will _appear_ to work as desired (since `0 > 0` is false):

```
┌────────────┬───────┐
│     ts     │  val  │
│  varchar   │ int32 │
├────────────┼───────┤
│ 2022-01-01 │       │
│ 2022-01-02 │     1 │
│ 2022-01-04 │     2 │
│ 2022-01-05 │     1 │
└────────────┴───────┘
```

but this is just a coincidence, hiding the underlying issue.

### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

v0.6.1-dev83 dfae126ebb

### DuckDB Client:

cli

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is standard practice for `WHERE` and `HAVING`, since the `SELECT` clause is executed at the very end of the query. For example, this is what SQLite does:

```sql
sqlite> create table integers(i integer);
sqlite> insert into integers values (1);
sqlite> select 42 as i from integers where i=1;
i 
--
42
sqlite> select 42 as i from integers group by i having i=1;
i 
--
42
```

I agree that it is confusing. If I would have designed this from scratch I would throw an ambiguity exception in this case because the other way around is ALSO confusing - but since other systems support this behavior that would mean breaking compatibility with queries other systems run.

We could treat `QUALIFY` differently as IIRC only Snowflake supports it. I will check to see what they do in this situation.

**Comment by Mytherin** [comment]
Looks like Snowflake behaves in the exact same way:

![Screenshot 2022-11-28 at 14 38 59](https://user-images.githubusercontent.com/3978469/204291607-0defcdd6-ab9d-427a-9096-cc5ef2714898.png)

Perhaps `QUALIFY` should just throw an exception if it does not contain a window function - as it does not make sense to use `QUALIFY` without one.
