### ISSUE TITLE
Incorrect benchmark results

### ISSUE THREAD

**Issue by Dtenwolde** [duckdb/duckdb#5518]
### What happens?

Running the following benchmark causes a crash: 
```
benchmark/micro/string/contains_integers.benchmark
libc++abi: terminating with uncaught exception of type duckdb::OutOfRangeException: Out of Range Error: Overflow in multiplication of INT64 (933825 * 9876983769044)!
```

When running all benchmarks using `build/release/benchmark/benchmark_runner` the following benchmarks provide incorrect results (I am not sure if the fault lies inside DuckDB or in the benchmark queries themselves):

```
benchmark/micro/cast/strptime.benchmark 1       INCORRECT
INCORRECT RESULT: Invalid Input Error: Could not parse string "10066/06/01" according to format specifier "%Y/%m/%d"
10066/06/01
``` 

```
benchmark/micro/limit/parquet_parallel_limit_glob.benchmark     1       INCORRECT
INCORRECT RESULT: Error in result on row 3 column 1: expected value "17797934" but got value "99999998"
Obtained result:
i       
BIGINT  
[ Rows: 4]
337
948247
99999998
99999999
```

```
benchmark/micro/join/iejoin_events.benchmark    1       INCORRECT
INCORRECT RESULT: Error in result on row 1 column 1: expected value "3772" but got value "3702"
Obtained result:
count_star()    
BIGINT  
[ Rows: 1]
3702
```

```
benchmark/micro/join/right_outer_join_left_big.benchmark        1       INCORRECT
INCORRECT RESULT: Error in result on row 1 column 1: expected value "100000000" but got value "99994962"
Obtained result:
count_star()    
BIGINT  
[ Rows: 1]
99994962
```

```
benchmark/micro/join/iejoin_employees.benchmark 1       INCORRECT
INCORRECT RESULT: Error in result on row 1 column 1: expected value "99296" but got value "98805"
Obtained result:
count_star()    
BIGINT  
[ Rows: 1]
98805
```

```
benchmark/micro/join/left_outer_join_right_big.benchmark        1       INCORRECT
INCORRECT RESULT: Error in result on row 1 column 1: expected value "100000000" but got value "99994945"
Obtained result:
count_star()    
BIGINT  
[ Rows: 1]
99994945
```

### To Reproduce

Compile DuckDB with the following flags:
`BUILD_BENCHMARK=1 BUILD_TPCH=1 BUILD_ICU=1 BUILD_HTTPFS=1 make GEN=ninja`

Unfortunately, you can only specify to run a single benchmark or all of them so you have to do the following: 

## For crash: 
Run: 
`build/release/benchmark/benchmark_runner benchmark/micro/string/contains_integers.benchmark`

## For incorrect results 
Run: 
`build/release/benchmark/benchmark_runner benchmark/micro/limit/parquet_parallel_limit_glob.benchmark`
`build/release/benchmark/benchmark_runner benchmark/micro/cast/strptime.benchmark`
`build/release/benchmark/benchmark_runner benchmark/micro/join/iejoin_events.benchmark` 
`build/release/benchmark/benchmark_runner benchmark/micro/join/right_outer_join_left_big.benchmark` 
`build/release/benchmark/benchmark_runner benchmark/micro/join/iejoin_employees.benchmark` 
`build/release/benchmark/benchmark_runner benchmark/micro/join/left_outer_join_right_big.benchmark`

### OS:

macOs 13 - Apple M1 Pro

### DuckDB Version:

6.0.1

### DuckDB Client:

CLI

### Full Name:

Daniel ten Wolde

### Affiliation:

Centrum Wiskunde & Informatica

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Thanks for the report! I have checked these benchmarks, and found the following:
1. `benchmark/micro/limit/parquet_parallel_limit_glob.benchmark`
    * Incorrect results because the hash join does not preserve order. I have changed many benchmarks to reflect this, but seems like I forgot this one. The fix is just not to check results (like in `parallel_limit.benchmark`
2. `build/release/benchmark/benchmark_runner benchmark/micro/cast/strptime.benchmark`
    * I don't know much about `strptime`, so no comment here

The `OutOfRangeException` in `benchmark/micro/string/contains_integers.benchmark` should be handled, not sure if it's a bug in the test, or a bug in the code.

For these tests:
```
build/release/benchmark/benchmark_runner benchmark/micro/join/iejoin_events.benchmark
build/release/benchmark/benchmark_runner benchmark/micro/join/right_outer_join_left_big.benchmark
build/release/benchmark/benchmark_runner benchmark/micro/join/iejoin_employees.benchmark
build/release/benchmark/benchmark_runner benchmark/micro/join/left_outer_join_right_big.benchmark
```

The checked result relies on a specific random seed. I have changed the way the random seed of local states is set, because I found a race condition when I reworked pipeline construction. This has most likely affected these tests, making the tests invalid, not the actual result given back by DuckDB. Given a fixed random seed, the result is always the same.

**Comment by Dtenwolde** [comment]
Thanks for the reply! I have removed the check for `benchmark/micro/limit/parquet_parallel_limit_glob.benchmark`, added `SETSEED` for the tests that did not have them, and corrected the results for the other tests. 

I have found another benchmark with incorrect results. I suppose it is correct what DuckDB returns, it's just that the output it is compared to is outdated.

```
build/release/benchmark/benchmark_runner benchmark/tpch/union/ungrouped_aggregate_union.benchmark
name    run     timing
benchmark/tpch/union/ungrouped_aggregate_union.benchmark        1       INCORRECT
INCORRECT RESULT: Error in result on row 2 column 1: expected value "5916591.0" but got value "226343830189.75"
Obtained result:
sum
DOUBLE
[ Rows: 7]
150921317.0
226343830189.75
215030862295.13
223635377438.35
25.50815444231315
38255.78448632836
5916591.0
```

Additionally, I have added a flag `--ignore-errors` that will continue to the next test when an error is thrown instead of stopping the execution. I found it somewhat annoying to run all benchmarks, only to find that 60% through a single test would throw an error and you have to run all benchmarks again. I also added that extensions that are required for the benchmarks are built when using the `BUILD_BENCHMARK=1` (or `-DBUILD_BENCHMARK=1`) build flag, instead of having to add them explicitly. Should I create a PR for this?
