### ISSUE TITLE
Build error with cmake version 3.5.2

### ISSUE THREAD

**Issue by zippond** [duckdb/duckdb#5528]
### What happens?

"Unknown arguments specified" error reported when build with cmake 3.5.2.
The required version is >= 2.8.12
`cmake_minimum_required(VERSION 2.8.12)`
But from cmake [doc](https://cmake.org/cmake/help/latest/command/if.html#greater-equal), GREATER_EQUAL is added in 3.7.

A compatible syntax might be used instead of GREATER_EQUAL.

### To Reproduce

%make debug
mkdir -p build/debug && \
cd build/debug && \
cmake        -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Debug ../.. && \
cmake --build . --config Debug
-- git hash c98221dce7, version v0.3.2-dev9492
CMake Error at CMakeLists.txt:747 (if):
  if given arguments:

    "-1" "GREATER_EQUAL" "0"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:821 (build_loadable_extension_directory)
  extension/parquet/CMakeLists.txt:56 (build_loadable_extension)

-- Configuring incomplete, errors occurred!
See also "/data/zdong/git/work/duckdb/build/debug/CMakeFiles/CMakeOutput.log".
See also "/data/zdong/git/work/duckdb/build/debug/CMakeFiles/CMakeError.log".
make: *** [Makefile:158: debug] Error 1

### OS:

sles12.5

### DuckDB Version:

master

### DuckDB Client:

none.

### Full Name:

Dong Zhi-peng

### Affiliation:

XJTU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by CreRecombinase** [comment]
I just ran into this as well

**Comment by carlopi** [comment]
Thanks for the report, the linked PR should fix this, and works also as a 1-line workaround.
