### ISSUE TITLE
Parquet stats_min_value/stats_max_value do not respect timestamp configuration

### ISSUE THREAD

**Issue by greaka** [duckdb/duckdb#5533]
### What happens?

When reading parquet files and/or their metadata, timestamp column metadata statistics `stats_min_value` and `stats_max_value` seem to not respect the timestamps configuration of `ms`, resulting in `where` filters ignoring entire chunks.

### To Reproduce

Example file using `ms` precision in stats:
[2022-11-27T17 42 35.480941703Z.parquet.txt](https://github.com/duckdb/duckdb/files/10112975/2022-11-27T17.42.35.480941703Z.parquet.txt)
`select path_in_schema, stats_min_value, stats_max_value from 'file.parquet';`
`select * from 'file.parquet';`
`select * from 'file.parquet' where timestamp < '2022-01-01 00:00:00.000';`
`select * from 'file.parquet' where timestamp > '2022-01-01 00:00:00.000';`
I've verified the raw values in the parquet file before filing this issue.

### OS:

Linux-x64 & shell.duckdb.org

### DuckDB Version:

0.6.0

### DuckDB Client:

rust & wasm

### Full Name:

Michl Steglich

### Affiliation:

drf.rs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #5540
