### ISSUE TITLE
`install parquet` error on termux

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5535]
### What happens?

`install parquet` error on termux

### To Reproduce

```
D copy ( select * FROM (values(1,2,3),(1,3,4))t(a,b,c)) to'a.parquet';
Error: Catalog Error: Copy Function with name parquet does not exist!
Did you mean "csv"?
D load parquet
> ;
Error: IO Error: Extension "/data/data/com.termux/files/home/.duckdb/extensions/v0.6.0/linux_arm64_gcc4/parquet.duckdb_extension" not found
D install parquet;
Error: IO Error: Failed to download extension "parquet" at URL "http://extensions.duckdb.org/v0.6.0/linux_arm64_gcc4/parquet.duckdb_extension.gz"
Extension "parquet" is an existing extension.
Are you using a development build? In this case, extensions might not (yet) be uploaded.
D
```

### OS:

termux

### DuckDB Version:

0.6.9

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

home

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
Hey @l1t1 thanks for reporting this. Did you compile duckdb yourself or did you use the pre-built binary? For some reason your duckdb seems built without the _GLIBCXX_USE_CXX11_ABI=1 flag which makes that it tries to go for our `_gcc4` binaries. We use these for binary compatibility with our python wheels, but this should not happen in any cli binaries.

This did lead me to an issues with the arm linux binaries. (PR https://github.com/duckdb/duckdb/pull/5556) Now when i try to load an extension from an ARM linux machine it works fine. But in your case it will not (yet).

**Comment by l1t1** [comment]
I use `pkg install duckdb`. it should be compiled by termux

**Comment by chrisirhc** [comment]
I'm seeing a similar issue on go-duckdb: https://github.com/marcboeker/go-duckdb/issues/59

**Comment by Mause** [comment]
Solved by https://github.com/termux/termux-packages/pull/15433#event-8670218932

**Comment by l1t1** [comment]
install sqlite_scanner error yet. 
~ $ sqlite3 sqlite3.db
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> create table t(a int);
sqlite> insert into t values(2),(5);

sqlite> .exit
~ $ duckdb
v0.7.1 b00b93f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 'sqlite3.db' AS sqlite (TYPE sqlite);
Error: IO Error: Extension "/data/data/com.termux/files/home/.duckdb/extensions/v0.7.1/linux_arm64/sqlite_scanner.duckdb_extension" not found.
Extension "sqlite_scanner" is an existing extension.

Install it first using "INSTALL sqlite_scanner".
D INSTALL sqlite_scanner;
D ATTACH 'sqlite3.db' AS sqlite (TYPE sqlite);
Error: IO Error: Extension "/data/data/com.termux/files/home/.duckdb/extensions/v0.7.1/linux_arm64/sqlite_scanner.duckdb_extension" could not be loaded: dlopen failed: library "libdl.so.2" not found

**Comment by Mause** [comment]
> install sqlite_scanner error yet. 
> ~ $ sqlite3 sqlite3.db
> SQLite version 3.40.1 2022-12-28 14:03:47
> Enter ".help" for usage hints.
> sqlite> create table t(a int);
> sqlite> insert into t values(2),(5);
> 
> sqlite> .exit
> ~ $ duckdb
> v0.7.1 b00b93f
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D ATTACH 'sqlite3.db' AS sqlite (TYPE sqlite);
> Error: IO Error: Extension "/data/data/com.termux/files/home/.duckdb/extensions/v0.7.1/linux_arm64/sqlite_scanner.duckdb_extension" not found.
> Extension "sqlite_scanner" is an existing extension.
> 
> Install it first using "INSTALL sqlite_scanner".
> D INSTALL sqlite_scanner;
> D ATTACH 'sqlite3.db' AS sqlite (TYPE sqlite);
> Error: IO Error: Extension "/data/data/com.termux/files/home/.duckdb/extensions/v0.7.1/linux_arm64/sqlite_scanner.duckdb_extension" could not be loaded: dlopen failed: library "libdl.so.2" not found

Out of tree extensions, such as substrait, SQLite, and postgres, you'll still need to compile yourself, as it's not presently possible to compile them into the DuckDB core
