### ISSUE TITLE
Table function stopped working in v0.6.

### ISSUE THREAD

**Issue by erikcw** [duckdb/duckdb#5546]
### What happens?

Prior to v0.6, I had been using the following query inside of a CTE to generate a calendar (basically a workaround to using `generate_series()` in postgres to create a table of days in the month for an analytical query).

It now fails with the following error:

```sql
    SELECT to_timestamp(range) as entry
    FROM range(
      epoch(date_trunc('month', current_date)),
      epoch(date_trunc('month', current_date) + interval '1 month' - interval '1 day'),
      epoch(interval '1 day')
    )
-- Error: Binder Error: Table function requires a constant parameter
-- LINE 2:     FROM range(
```

### To Reproduce

```sql
    SELECT to_timestamp(range) as entry
    FROM range(
      epoch(date_trunc('month', current_date)),
      epoch(date_trunc('month', current_date) + interval '1 month' - interval '1 day'),
      epoch(interval '1 day')
    )
```

### OS:

MacOS and Linux (arm)

### DuckDB Version:

0.6.0

### DuckDB Client:

Python and duckdb-cli

### Full Name:

Erik Wickstrom

### Affiliation:

LiftCertain

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #5550.
