### ISSUE TITLE
Can call cursor() on closed connection in Python (and segmentation fault if you use it)

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#5560]
### What happens?

With Python client:
`execute(..)` on a closed connection raises `Connection Error: Connection has already been closed`, but:
`cursor()` doesn't raise an exception, and:
when you `execute(..)` on the cursor you get `Segmentation fault (core dumped)`.

### To Reproduce

```py
import duckdb

con = duckdb.connect()
con.close()

try:
    con.execute('select 1;')
except duckdb.ConnectionException as e:
    print(e)  # this is helpful

con_ = con.cursor()
con_.execute('select 1;')  # this is not
```

### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

v0.6.1-dev83 dfae126ebba9d4d8658b003a08d5c41a185dccb6

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by davetapley** [comment]
Maybe as simple as copying:
https://github.com/duckdb/duckdb/blob/45d857191be915d3a38c83b75a42a945ba04fe9d/tools/pythonpkg/src/pyconnection.cpp#L140-L142

to:
https://github.com/duckdb/duckdb/blob/45d857191be915d3a38c83b75a42a945ba04fe9d/tools/pythonpkg/src/pyconnection.cpp#L497-L500

?

**Comment by Tishj** [comment]
Ah yes, nice find, I think that will indeed fix it 👍
