### ISSUE TITLE
Parallel CSV reader bugs

### ISSUE THREAD

**Issue by eeroel** [duckdb/duckdb#5566]
### What happens?

Hi,

I was trying out the parallel CSV reader, really impressed with the performance! I encountered some bugs:
Query 1: A table with a single column is empty when reading with parallel CSV reader
Query 2: Serial and parallel CSV readers give different results. Sorry, this is probably not the most minimal example (I think `select count(1)` would also do). I was trying to reproduce a bug I encountered with a real life dataset I can't share, where grouped counts by one column would be slightly different using the different readers.

### To Reproduce

Query 1
```
import pandas as pd
bar=pd.DataFrame().assign(foo=[1,2,3,4,5])
bar.to_csv("/tmp/test_single_column.csv",index=False)
import duckdb as db
conn=db.connect(":memory:")
print(conn.execute("select count(1) from read_csv_auto('/tmp/test_single_column.csv')").fetchall())
conn.execute("set experimental_parallel_csv=true;")
print(conn.execute("select count(1) from read_csv_auto('/tmp/test_single_column.csv')").fetchall())
conn.close()
```

Query 2 (note randomness in generating data, but behavior is consistent)
```
import pandas as pd
bar=pd.DataFrame().assign(foo=[1,2,3], a=1,b=2,c=3,d=4,e=5,f=6,g=7,h=8,i=9,j=10,k=11,l=12).sample(300,replace=True)
bar.to_csv("/tmp/test_more_columns.csv",index=False)
import duckdb as db
conn=db.connect(":memory:")
conn.execute("set experimental_parallel_csv=false;")
print(conn.execute("select foo, count(1) cnt from read_csv_auto('/tmp/test_more_columns.csv', buffer_size=24) group by foo order by cnt desc").fetchall())
conn.execute("set experimental_parallel_csv=true;")
print(conn.execute("select foo, count(1) cnt from read_csv_auto('/tmp/test_more_columns.csv', buffer_size=24) group by foo order by cnt desc").fetchall())
```

### OS:

MacOS

### DuckDB Version:

0.6.0

### DuckDB Client:

Python

### Full Name:

Eero Lihavainen

### Affiliation:

In profile

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
Hi @eeroel , many thanks for testing this experimental feature! I just added the fixes for the issues you found to a PR! :-)
