### ISSUE TITLE
Behavior change in 0.6.0 when value consists of only quotes

### ISSUE THREAD

**Issue by darthf1** [duckdb/duckdb#5573]
### What happens?

Hi!

I have a python scripts which reads a CSV, "cleans" it via a SQL query, and writes the result to a new CSV file. The query:
- Removes all non readable characters
- Converts all columns which only consists of quotes to an empty column.

When upgrading from `0.5.1` to `0.6.0` one of my tests started to fails on the second point.

### To Reproduce

When I have a CSV with:
```csv
header1,header2,header3
"",value,""
```

And I have this python script:
```python
import click
import duckdb
import os
import pandas as pd
from pathlib import Path


@click.command()
@click.option('-f', '--uploaded-file-path', type=click.Path(exists=True), help='Absolute filepath of the uploaded file which will be converted')
@click.option('-r', '--converted-file-path', type=click.STRING, help='Absolute filepath where the converted file must be stored')
def cli(uploaded_file_path, converted_file_path):
    """Convert an uploaded CSV file"""

    Path(os.path.dirname(converted_file_path)).mkdir(parents=True, exist_ok=True)

    statements = []
    columns = pd.read_csv(uploaded_file_path, nrows=0).columns.tolist()
    for column in columns:
        statements.append('regexp_replace(trim({}), \'[^ -~]\', \'\') AS "{}"'.format(column, column))

    con = duckdb.connect()
    con.execute("PRAGMA threads=1;")
    con.execute("COPY (SELECT {} FROM read_csv_auto('{}', HEADER=TRUE, QUOTE='\"', SAMPLE_SIZE=1, ALL_VARCHAR=TRUE)) TO '{}' WITH (HEADER 1)".format(', '.join(statements), uploaded_file_path, converted_file_path))


if __name__ == '__main__':
    cli()

```

On `0.5.1` the written CSV contains:
```csv
header1,header2,header3
,value,
```

On `0.6.0` (and `0.6.1.dev240`) the written CSV contains:
```csv
header1,header2,header3
"",value,""
```

### OS:

Debian Bullseye

### DuckDB Version:

0.6.0

### DuckDB Client:

Python

### Full Name:

Frank

### Affiliation:

1GL

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

Perhaps I am missing something but that looks like a bug was fixed to me. An empty string is read in and an empty string is written out in the current version - which seems correct. The original version seems incorrect to me - where it would write out a NULL value after reading in an empty string.

Are you not missing code to convert empty strings to NULL values if that is the desired behavior?

**Comment by darthf1** [comment]
> Are you not missing code to convert empty strings to NULL values if that is the desired behavior?

I thought I had  😅 . Well, at least, I was reading the [documentation](https://duckdb.org/docs/data/csv#parameters), specifically the parameter `NULLSTR`. 
> Specifies the string that represents a NULL value. The default is an empty string.

My understanding of this, is that an empty string (which I thought was `""` as well since `"` is my `QUOTE` sign), would be converted to `null` automatically.

**Comment by darthf1** [comment]
Ah, you're right. So, I'm ofcourse not just reading, but also writing a CSV with `COPY ... TO`. Reading the [documentation](https://duckdb.org/docs/sql/statements/copy#parameters) regarding the `NULL` parameter; if I add `NULL '\"\"'` to the query it works.
