### ISSUE TITLE
Duckdb-authored Parquet files not readable to Databricks Warehouse

### ISSUE THREAD

**Issue by niger-prequel** [duckdb/duckdb#5575]
### What happens?

When attempting to read the Parquet file (generated from DuckDB), I encounter a trace from Databricks

```
Error while reading file s3://REDACTED_CREDENTIALS(0568655b)@redacted-bucket-name/staging/545223269.parquet. Only one of num_children and type should be set in SchemaElement
```

Raising it here because it feels like it might be related to this [issue](https://github.com/duckdb/duckdb/issues/2111). Are there additional metadata fields that other readers expect that still aren't being filled in?

### To Reproduce

The data is from our integration test suite, so it is not sensitive. You can [download the generated Parquet file here. ](https://drive.google.com/file/d/1t9eoWedeLY8Ir24T4-Qc6ITawec6dl4y/view?usp=sharing)

The queries we ran on databricks:

```sql
CREATE TABLE IF NOT EXISTS destination_schema_rds_enterprise.logs_temp (
        log_id string, log string, _updated_at timestamp
    )
    
 USING PARQUET LOCATION 's3://REDACTED_CREDENTIALS(0568655b)@redacted-bucket-name/staging/';

SELECT * FROM destination_schema_rds_enterprise.logs_temp;
```

### OS:

Debian amd64

### DuckDB Version:

v0.5.1

### DuckDB Client:

ODBC

### Full Name:

Niger Little-Poole

### Affiliation:

Prequel.co

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
According to https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L353
````Thrift
  /** Data type for this field. Not set if the current element is a non-leaf node */
  1: optional Type type;
````
and
````Thrift
 * This field is not set when the element is a primitive type
   */
  5: optional i32 num_children;
````
so indeed they should not be set together.

**Comment by niger-prequel** [comment]
You rock 🙏
