### ISSUE TITLE
duckdb python module has an implicit dependency on pandas

### ISSUE THREAD

**Issue by jwills** [duckdb/duckdb#5577]
### What happens?

If you use the `duckdb` python module and try to use a Python `datetime` value as a bound parameter to an `execute` call, the call will fail with the error `No module named 'pandas'` unless you have `pandas` installed as well. 

The offending line is here: https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/python_conversion.cpp#L277

...and there is another implicit pandas dependency in the same file:
https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/python_conversion.cpp#L209

...although that isn't the one I tripped over.

### To Reproduce

From a Python venv that has `duckdb` installed but _does not_ have `pandas` installed:

```
import duckdb
import datetime
conn = duckdb.connect()
conn.execute("CREATE TABLE foo (t timestamp)")
conn.execute("INSERT INTO foo VALUES (?)", (datetime.datetime.now(),))
```

...should be enough to trigger the `No module named 'pandas'` error.

### OS:

OS X

### DuckDB Version:

0.6.0

### DuckDB Client:

Python

### Full Name:

Josh Wills

### Affiliation:

WeaveGrid

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the find!

I do want to note that 209 is not causing an issue, the import cache marks pandas as optional, IsInstance will just return false if it's not imported
