### ISSUE TITLE
the node `.stream` method returns a 404 when querying a GCS bucket

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#5586]
### What happens?

When I run a query using `.all` which targets a parquet file in a GCS bucket, I'm able to fetch my results. But if I use `.stream` I get a 404 error. It's possible I haven't set things up quite right to stream data from GCS in some way, but I would expect `.all` to also fail in that case.

The error message:

```
[Error: Invalid Error: Unable to connect to URL "s3://pkg.rilldata.com/example-data/sf311.parquet": 404 (Not Found)] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR'
}

Node.js v17.2.0
```

### To Reproduce

Run the following program in Node (the bucket listed below is public ~ feel free to find me on the #node channel on the duckdb Discord if the script doesn't work & I can set up access for you)

```javascript
import duckdb from "duckdb";

const db = new duckdb.Database(":memory:");

async function main() {
  let r;
  const promise = new Promise((resolve => {
    r = resolve;
  }))
  db.exec(`
    load httpfs;
    SET s3_endpoint = 'storage.googleapis.com';
    `, () => {
      // this works as expected
      db.all(`SELECT * from 's3://pkg.rilldata.com/example-data/sf311.parquet' LIMIT 5`, (__, res) => {
        console.log(`fetched ${res.length} rows successfully`);
        r();
      })
  })
  await promise;
  const con = db.connect();
  // this does not
  const s = con.stream(`SELECT * from 's3://pkg.rilldata.com/example-data/sf311.parquet' LIMIT 5`);

  for await (let row of s) {
    console.log(row);
  }
  
}

await main();
```

### OS:

Mac M1

### DuckDB Version:

0.6.0

### DuckDB Client:

Node

### Full Name:

Hamilton Ulmer

### Affiliation:

Rill Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
The issue here is that you're creating a new connection (`const con = db.connect()`) after using the default one to set the `s3_endpoint`. If you set the `s3_endpoint` on the connection you create manually, or set `s3_endpoint` globally, the issue shouldn't occur

**Comment by hamilton** [comment]
Correct, I hadn't considered that the connection doesn't inherit what was set by `db`. Thank you for looking into, and apologies for missing this in hindsight.
