### ISSUE TITLE
Implement TIME_BUCKET Function

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#5589]
`time_bucket` allows for truncation/bucketing by an arbitrary interval, instead of only by whole minutes, whole hours, etc. See e.g. the [Timescale docs](https://docs.timescale.com/api/latest/hyperfunctions/time_bucket/) or [Singlestore docs](https://docs.singlestore.com/managed-service/en/reference/sql-reference/time-series-functions/time_bucket.html).

**Comment by papparapa** [comment]
I would like to work on this.

**Comment by Mytherin** [comment]
Go ahead
