### ISSUE TITLE
Error when using duckdb with hikari

### ISSUE THREAD

**Issue by quangr** [duckdb/duckdb#5593]
### What happens?

When trying to use hikari to connect duckdb, hikari will use repealy use same driverProperties to get connection as following code
```
  @Override
   public Connection getConnection() throws SQLException
   {
      return driver.connect(jdbcUrl, driverProperties);
   }
```
but in https://github.com/duckdb/duckdb/blob/c81d35f5a45429b806119061dfdf12799df07e8c/tools/jdbc/src/main/java/org/duckdb/DuckDBDriver.java#L31
the connect function will remove readonly property from info, which makes the hikari can not reuse driverProperties, and can only maintain one connection.

One Solution is make a copy of info like this
```
if (info == null) {
	info = new Properties();
}else{
	info = (Properties) info.clone();
}
```
BTW, I realy enjoy using duckdb, its an amazing database.

### To Reproduce

use flowing application.properties
```
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=org.duckdb.DuckDBDriver
spring.datasource.url=jdbc:duckdb:
spring.datasource.hikari.data-source-properties.duckdb.read_only=true
spring.datasource.hikari.read-only=true
spring.datasource.hikari.maximum-pool-size=500
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG 
logging.level.com.zaxxer.hikari=TRACE
```

### OS:

linux

### DuckDB Version:

0.6.0

### DuckDB Client:

java

### Full Name:

Quan Guorui

### Affiliation:

NA

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
That's a fair point we should make a copy
