### ISSUE TITLE
Segfaults doing simple select where on small tables

### ISSUE THREAD

**Issue by Samrose-Ahmed** [duckdb/duckdb#5604]
[enrichment.duckdb.zip](https://github.com/duckdb/duckdb/files/10158647/enrichment.duckdb.zip)
### What happens?

I am running simple `select * where` queries on very small tables using the Python DuckDB library (version 0.6.0). I am seeing segmentation faults alongside errors:

```
Not implemented Error: Unsupported type: "INVALID"
Not implemented Error: Unsupported type: "UNDEFINED 
```

### To Reproduce

I am attaching the .duckdb database being used. I cannot reproduce it consistently. It often works then crashes.

It is being run in a loop with many iterations. It is also running in AWS Lambda. 

I am using the following code to run the query:

```python
conn = duckdb.connect(database=duckpath, read_only=True)

def get_record_by_key(self, table_name: str, key: str):
    pk_col = "oil"
    return self._duckdb.execute(f"select * from aws_conf where {pk_col} = '{key}'").fetchone()
```

### OS:

Linux (AWS Lambda x86)

### DuckDB Version:

python 0.6.0

### DuckDB Client:

Python

### Full Name:

Samrose

### Affiliation:

https://github.com/matanolabs/matano

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by omo** [comment]
If you have some code to generate the db (like reading a json and writing it to a new db), it'd be helpful
because the database file format isn't stable and it is possible that the attached db file cannot be read from the latest/in-development code.
