### ISSUE TITLE
Fatal error: database invalidated after "Failed to bind column" error.

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#5614]
### What happens?

When running the following query:

```
select row_number() over () as line_number
, column0 as text
, length(coalesce(column0, '')) as text_length
from read_csv(
  'https://www.gutenberg.org/cache/epub/10/pg10.txt'
, delim='|'
, AUTO_DETECT=TRUE
)
where 'LORD' in (select * from unnest(str_split(text, ' ')));
```
I get the following error:

`Error: INTERNAL Error: Failed to bind column reference "column0" [7.0] (bindings: [22.0])`

I understand the column reference may be invalid, but I believe it should result in an error message like "unknown column" or somethine like that - the binding error sounds like something is wrong internally (I may be wrong about that?)

But after this, the database becomes unusable. Any following query results in:

```
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "INTERNAL Error: Failed to bind column reference "column0" [7.0] (bindings: [22.0])"
```

### To Reproduce

Make sure the http extension is installed:

```
install 'http';
load 'http';
```

then run:

```
select row_number() over () as line_number
, column0 as text
, length(coalesce(column0, '')) as text_length
from read_csv(
  'https://www.gutenberg.org/cache/epub/10/pg10.txt'
, delim='|'
, AUTO_DETECT=TRUE
)
where 'LORD' in (select * from unnest(str_split(text, ' ')));
```

### OS:

Windows 10 Pro both CLI and WASM

### DuckDB Version:

v0.6.0 2213f9c946

### DuckDB Client:

CLI, WASM

### Full Name:

Roland Bouman

### Affiliation:

Just-BI / EPAM

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rpbouman** [comment]
Thanks @Mytherin , all clear now!

**Comment by alexboks** [comment]
Another example of this happening:
```
CREATE or replace TABLE brands (category VARCHAR, brand_name VARCHAR);
INSERT INTO brands (category, brand_name) VALUES ('chocolates', '5-star'), (Null, 'diary milk'), (Null, 'perk'), (Null, 'eclair'), ('Biscuits', 'britannia'), (Null, 'good day'), (Null, 'boost');
with cte as (
select 
  *, 
  row_number() over () as t,
  count(category) over (order by t) as tmp
from brands
)
select
  max(category) over (partition by tmp) as category,
  brand_name
from cte;

**Comment by Mytherin** [comment]
Looks like this is still a problem

**Comment by gka** [comment]
jep, this still happens with v0.9.0 (0d84ccf478)

**Comment by Mytherin** [comment]
Both of these issues have now been fixed
