### ISSUE TITLE
Incorrect parsing of parentheses in strptime function

### ISSUE THREAD

**Issue by matthanley** [duckdb/duckdb#5622]
### What happens?

Parsing a date from a date string using `strptime` requires dropping a literal parenthesis from the format string for it to work correctly, otherwise DuckDB throws an error:

```
Invalid Input Error: Could not parse string "Tue Oct 18 2022 10:12:32 GMT+0000 (GMT)" according to format specifier "%a %b %d %Y %X %Z (%Z)"
Tue Oct 18 2022 10:12:32 GMT+0000 (GMT)
                                       ^
Error: Literal does not match, expected )
```

Dropping the closing parenthesis from the format string allows parsing to complete successfully:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/3798302/206141058-7eb7ce67-add8-4ec6-bdc8-d05561d27ee8.png">

### To Reproduce

```
SELECT strptime('Mon Oct 17 2022 22:00:00 GMT+0000 (GMT)', '%a %b %d %Y %X %Z (%Z)') as broken;
SELECT strptime('Mon Oct 17 2022 22:00:00 GMT+0000 (GMT)', '%a %b %d %Y %X %Z (%Z') as working;
```

Note the missing closing parenthesis in the format string in the second line.

### OS:

https://shell.duckdb.org

### DuckDB Version:

@duckdb/duckdb-wasm@1.20.1-dev14.0

### DuckDB Client:

DuckDB Web Shell

### Full Name:

Matt Hanley

### Affiliation:

Deepnote

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This is probably my fault.

**Comment by hawkfish** [comment]
@matthanley Is this working for you now?
