### ISSUE TITLE
Force compression error message missing compression options

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#5624]
### What happens?

When using `pragma force_compression=...`, the error message does not contains all options, we need to update this.

### To Reproduce

```sql
PRAGMA force_compression='non_existing_option';
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
added them in my pr for delta compression: https://github.com/duckdb/duckdb/pull/5491/files#diff-38977b9d934cc207626abd3a0b82d9fe13edbe4fc538235aac070ef221aa4043R417

**Comment by Tishj** [comment]
Oh @samansmink I also added them as part of #5603
