### ISSUE TITLE
Binder error on tstz + INTERVAL 1 SECOND 

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [duckdb/duckdb#5631]
### What happens?

```SQL
SELECT ANY_TSTZ + INTERVAL ANYNUM ANYINTERVAL
```

Breaks in 0.6.1, worked in 0.5.1

### To Reproduce

```SQL
SELECT now() + INTERVAL 1 SECOND
```

In 0.5.1 produces
```
┌───────────────────────────────────────────┐
│ (now()) + (to_seconds(CAST(1 AS BIGINT))) │
├───────────────────────────────────────────┤
│ 2022-12-07 21:37:18.387                   │
└───────────────────────────────────────────┘
```

In 0.6.1

```
Error: Binder Error: No function matches the given name and argument types '+(TIMESTAMP WITH TIME ZONE, INTERVAL)'. You might need to add explicit type casts.
	Candidate functions:
	+(TINYINT) -> TINYINT
	+(TINYINT, TINYINT) -> TINYINT
	+(SMALLINT) -> SMALLINT
	+(SMALLINT, SMALLINT) -> SMALLINT
	+(INTEGER) -> INTEGER
	+(INTEGER, INTEGER) -> INTEGER
	+(BIGINT) -> BIGINT
	+(BIGINT, BIGINT) -> BIGINT
	+(HUGEINT) -> HUGEINT
	+(HUGEINT, HUGEINT) -> HUGEINT
	+(FLOAT) -> FLOAT
	+(FLOAT, FLOAT) -> FLOAT
	+(DOUBLE) -> DOUBLE
	+(DOUBLE, DOUBLE) -> DOUBLE
	+(DECIMAL) -> DECIMAL
	+(DECIMAL, DECIMAL) -> DECIMAL
	+(UTINYINT) -> UTINYINT
	+(UTINYINT, UTINYINT) -> UTINYINT
	+(USMALLINT) -> USMALLINT
	+(USMALLINT, USMALLINT) -> USMALLINT
	+(UINTEGER) -> UINTEGER
	+(UINTEGER, UINTEGER) -> UINTEGER
	+(UBIGINT) -> UBIGINT
	+(UBIGINT, UBIGINT) -> UBIGINT
	+(DATE, INTEGER) -> DATE
	+(INTEGER, DATE) -> DATE
	+(INTERVAL, INTERVAL) -> INTERVAL
	+(DATE, INTERVAL) -> DATE
	+(INTERVAL, DATE) -> DATE
	+(TIME, INTERVAL) -> TIME
	+(INTERVAL, TIME) -> TIME
	+(TIMESTAMP, INTERVAL) -> TIMESTAMP
	+(INTERVAL, TIMESTAMP) -> TIMESTAMP
	+(TIME, DATE) -> TIMESTAMP
	+(DATE, TIME) -> TIMESTAMP
	+(ANY[], ANY[]) -> ANY[]

LINE 1: select now() + interval 1 second;
```

### OS:

13.0.1

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

Michael Toy

### Affiliation:

Google

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is likely caused by us switching `NOW` to a `TIMESTAMPTZ`, which requires the `icu` extension to be loaded to perform any operations on. We might want to consider having `NOW` return a `TIMESTAMP` instead when the `icu` extension is not loaded.

Or perhaps we might want to treat `TIMESTAMPTZ` as a `TIMESTAMP` if the `icu` extension is not loaded.

@hawkfish any thoughts?

**Comment by Mytherin** [comment]
As a work-around you can manually cast `NOW` to a `TIMESTAMP`:

```sql
select now()::timestamp + interval (1) second;
```

**Comment by mtoy-googly-moogly** [comment]
I actually NEED to use `+ INTERVAL ...` with TSTZ values, `now()` is just one of the examples

**Comment by Mytherin** [comment]
It already works - but you need to build the `icu` extension for it to work (or most operations on `TIMESTAMPTZ` - that is where our timezone support comes from).

**Comment by mtoy-googly-moogly** [comment]
ok, this is not a bug then. sorry. thanks.

**Comment by hawkfish** [comment]
> This is likely caused by us switching `NOW` to a `TIMESTAMPTZ`, which requires the `icu` extension to be loaded to perform any operations on. We might want to consider having `NOW` return a `TIMESTAMP` instead when the `icu` extension is not loaded.
> 
> Or perhaps we might want to treat `TIMESTAMPTZ` as a `TIMESTAMP` if the `icu` extension is not loaded.
> 
> @hawkfish any thoughts?

Right now extensions can add new functions, but perhaps adding functionality to replace implementations would be a good idea. Then yes, we could do this. 

I do worry a bit about the semantics, though: The answer could change if you load an extension, which seems a bit dangerous. Its the difference between failing early and hiding a problem.

**Comment by hawkfish** [comment]
> maybe `CURRENT_TIMESTAMP` should return a TIMESTAMP though.

From the [PG docs](https://www.postgresql.org/docs/15/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT):

> CURRENT_TIME and CURRENT_TIMESTAMP deliver values with time zone; LOCALTIME and LOCALTIMESTAMP deliver values without time zone.

So maybe what we need is `LOCALTIME` and `LOCALTIMESTAMP`. Although I think those are supposed to be non-instant values (which will create further confusion...)

**Comment by mtoy-googly-moogly** [comment]
@hawkfish I should have looked at the PG docs.

I think `CURRENT_TIMESTAMP::TIMESTAMP` is a fine workaround.The longterm fix for me is for Malloy to always include the ICU extension, which I will do when I finally get to making Malloy reason well about timezones also.
