### ISSUE TITLE
insert into a table with int[] field from generate_series() raise `Error: Invalid Error: bad allocation`

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5633]
### What happens?

insert into a table with int[] field from generate_series() raise `Error: Invalid Error: bad allocation`

BTW my old computer has 2G RAM. you can increase the value to reproduce the issue.

### To Reproduce

```
D create table a(a int[]);
Run Time (s): real 0.000 user 0.000000 sys 0.000000
D insert into a select list(i) from generate_series(1,50000000)t(i);
Run Time (s): real 12.152 user 11.107271 sys 1.045207
Error: Invalid Error: bad allocation
```
If first create an other int field from generate_series(), then insert into the int[] table from the new table, it works.

```
D create table t(i int);
Run Time (s): real 0.000 user 0.000000 sys 0.000000
D insert into t select i from generate_series(1,50000000)t(i);
Run Time (s): real 2.948 user 2.761218 sys 0.156001
D insert into a select list(i) from t;
 99% ▕███████████████████████████████████████████████████████████▍▏ 
Run Time (s): real 7.613 user 14.180491 sys 0.873606
```

### OS:

windows 7

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Individual list entries must fit in RAM. Creating giant list entries on machines with not enough RAM to handle them might cause out-of-memory exceptions. That is expected behavior.

**Comment by Mytherin** [comment]
The system probably runs out of memory when trying to convert the list to a string for display purposes.

**Comment by l1t1** [comment]
selec len() is ok, select a[:] exits
```
D select len(a) from a;
┌──────────┐
│  len(a)  │
│  int64   │
├──────────┤
│ 50000000 │
└──────────┘
D select a[1:10] from a;
D:\duckdb>
```

**Comment by l1t1** [comment]
I try to use a local table, duckdb also exits, but  the harddisk bb.duck file is only 163 MB.
```
D:\duckdb>duckdb061 c:\bb.duck
v0.6.1 919cad22e8
Enter ".help" for usage hints.
D create table a(a int[]);
D create table t(i int);
D insert into t select i from generate_series(1,50000000)t(i);
D insert into a select list(i) from t;
 99% ▕███████████████████████████████████████████████████████████▍▏ D
D select a[1:10] from a;

D:\duckdb>
```

**Comment by Mytherin** [comment]
DuckDB is able to compress the list when writing to disk - but the entire list must fit uncompressed in RAM for this to work. Reading the list causes it to be uncompressed which then causes your machine to run out of memory.
