### ISSUE TITLE
insert into a select list(i) from t order by i; reports `Error: Binder Error: column "i" must appear in the GROUP BY clause or must be part of an aggregate function.`

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#5636]
### What happens?

use  `insert into a select list(i) from t` insert a  list field table cause items not in order.
try to use `insert into a select list(i) from t order by i` raise the error.

### To Reproduce

```
create table a(a int[]);
create table t(i int);
insert into t select i from generate_series(1,5000000)t(i);
insert into a select list(i) from t;
select a[1:10] from a;
┌──────────────────────────────────────────────────────────────────────────────┐
│                                   a[1:10]                                    │
│                                   int32[]                                    │
├──────────────────────────────────────────────────────────────────────────────┤
│ [122881, 122882, 122883, 122884, 122885, 122886, 122887, 122888, 122889, 1…  │
└──────────────────────────────────────────────────────────────────────────────┘
drop table a;
create table a(a int[]);
insert into a select list(i) from t order by i;
Error: Binder Error: column "i" must appear in the GROUP BY clause or must be part of an aggregate function.
Either adit to the GROUP BY list, or use "ANY_VALUE(i)" if the exact value of "i" is not important.
```

### OS:

windows 7

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
`LIST` is an aggregate function, the error is correctly reporting that the column `i` cannot be part of an `ORDER BY` clause on the result of the aggregate computation.

You're probably looking for an ordered aggregate:

```sql
insert into a select list(i order by i) from t;
```

**Comment by l1t1** [comment]
thanks
