### ISSUE TITLE
Segfault on linux aarch64 with kernel large pages 

### ISSUE THREAD

**Issue by psanford** [duckdb/duckdb#5640]
### What happens?

Starting with v0.6.0, the DuckDB cli segfaults as soon as I attempt to do many actions, including tab completion or trying to read a file from disk. The segfaults do not happen on v0.5.x.  

### To Reproduce

This occurs on a linux/aarch64 system with 16k pages. The specific hardware I'm testing on is a MacBook Air M2 running Asahi linux.

This seems to have been introduced when the jemalloc dependency was added. 

But, you might say, jemalloc supports large pages! Indeed it does, however this patch seems to disable that behavior on linux:   https://github.com/duckdb/duckdb/pull/4971/commits/3b67618ac98e49aaa33163c48eb18ba5f69880f7

Reverting that patch fixes the segfaults on my system.

### OS:

linux/aarch64

### DuckDB Version:

v0.6.1

### DuckDB Client:

cli

### Full Name:

Peter Sanford

### Affiliation:

none 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by foTok** [comment]
I hit a similar issue. I removed the FSST compression support and recompiled the lib, then no crash happened. You can try it.

**Comment by psanford** [comment]
@foTok were you experiencing your issue on a system with large page tables? It sounds like your issue is unrelated to the issue I am describing.

**Comment by psanford** [comment]
Like I said in the initial post, my system requires large pages in the kernel (its not an x86 based cpu). The patched linked in my initial report shows that `LG_PAGE` is being set to 12 which is incorrect for a system with 16k pages. Reverting that patch fixes the issue. I don't think our issues are connected.

**Comment by foTok** [comment]
> Like I said in the initial post, my system requires large pages in the kernel (its not an x86 based cpu). The patched linked in my initial report shows that `LG_PAGE` is being set to 12 which is incorrect for a system with 16k pages. Reverting that patch fixes the issue. I don't think our issues are connected.

Thanks. I probably connected them by mistake.

**Comment by lnkuiper** [comment]
@psanford Detecting `LG_PAGE` at compile-time is a bit tricky. I also don't have access to all kinds of hardware to test this out, so I have to rely on our CI. Could you test if this works for you?

**Comment by psanford** [comment]
That patch does fix the issue for me on my Asahi system. 

Thanks!
