### ISSUE TITLE
Unable to transform python value of type '<class 'numpy.datetime64'>' to DuckDB LogicalType

### ISSUE THREAD

**Issue by MarcSkovMadsen** [duckdb/duckdb#5655]
### What happens?

I'm trying to add support for ibis+duckdb to hvplot/ HoloViews. See https://github.com/holoviz/holoviews/issues/5557#issuecomment-1345157033. When testing crossfiltering between plots I get `duckdb.NotImplementedException: Not implemented Error: Unable to transform python value of type '<class 'numpy.datetime64'>' to DuckDB LogicalType` error.

### To Reproduce

```python
from pathlib import Path

import duckdb
import ibis
import numpy as np
import pandas as pd
import requests

TRIP_DATA_PATH = "yellow_tripdata_2022-02.parquet"

if not Path(TRIP_DATA_PATH).exists():
    url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet"
    response = requests.get(url, verify=False)
    with open(TRIP_DATA_PATH, "wb") as f:
        f.write(response.content)

DUCKDB_PATH = "DuckDB.db"

if not Path(DUCKDB_PATH).exists():
    duckdb_con = duckdb.connect(DUCKDB_PATH)
    duckdb_con.execute(f"CREATE TABLE big_df AS SELECT * FROM '{TRIP_DATA_PATH}'")
else:
    duckdb_con = duckdb.connect(DUCKDB_PATH)

duckdb_con.execute("select * from big_df where big_df.tpep_pickup_datetime >= CAST(? AS TIMESTAMP WITHOUT TIME ZONE)", parameters=[np.datetime64('2022-02-08T06:01:38.761310')]).execute()
```

### OS:

windows

### DuckDB Version:

0.6.0 (and  0.6.2.dev13)

### DuckDB Client:

python

### Full Name:

Marc Skov Madsen

### Affiliation:

datamodelsanalytics.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### Additional Context

As I am originally using duckdb via Ibis, I've also added the issue to the Ibis issues https://github.com/ibis-project/ibis/issues/4997.

I don't know if this is as expected (it is not for me), if Ibis should handle the numpy conversion or if DuckDb should.

**Comment by Tishj** [comment]
I'll look into this issue, sounds like the column is of type `object` and contains a numpy value, which was probably overlooked as a conversion option

**Comment by Tishj** [comment]
![image](https://user-images.githubusercontent.com/17162323/206872441-103a6adc-23ed-4319-9bf1-bec2a8e06d46.png)

**Comment by Tishj** [comment]
Hmm if the precision of the numpy.datetime64 becomes too big it switches to an int as internal type, that's probably why they wrapped `datetime.datetime`, so they can scale out when it gets too big to be represented by a datetime.datetime
