### ISSUE TITLE
CSV Reader does not throw error on invalid csv file, but rows are missing

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#5663]
### What happens?

When reading from an invalid csv file, the query succeeds, but the output is missing rows.

### To Reproduce

test.csv
```csv
a, b, c, d
1, 2, 3, 4
WEIRD BEHAVIOR
1, 2, 3, 4
```

The behavior is different depending on `header` option being present or not (though both are wrong)

With header:
```sql
select * from read_csv_auto('test.csv', header=True);
```
```
D select * from read_csv_auto('test.csv', header=True);
┌───────┬───────┬───────┬───────┐
│   1   │   2   │   3   │   4   │
│ int32 │ int32 │ int32 │ int32 │
├───────────────────────────────┤
│            0 rows             │
└───────────────────────────────┘
```

Without header:
```sql
select * from read_csv_auto('test.csv');
```
```
┌─────────┬─────────┬─────────┬─────────┐
│ column0 │ column1 │ column2 │ column3 │
│  int32  │  int32  │  int32  │  int32  │
├─────────┼─────────┼─────────┼─────────┤
│       1 │       2 │       3 │       4 │
└─────────┴─────────┴─────────┴─────────┘
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Unrelated to this, but I just discovered that `auto_detect` is forced to true on `read_csv_auto` even when `auto_detect=false` is set explicitly.

Also the types set by `columns` are completely ignored when `auto_detect` is set, which also sounds like unexpected behavior

**Comment by mark15217** [comment]
Hi,
I think this is because **inconsistent lines are treated as comment and therefore are skipped**.
For example,
```
a, b, c, d
1, 2, 3, 4
WEIRD BEHAVIOR
1, 2, 3, 4
```
line 2 can be parsed into 2 column and is inconsistent with line 0 and line 1, so everything is treated as comment and line 3 becomes the header line.

To prove this,
We can give a new test.csv
```
a, b, c, d
1, 1, 1, 1
WEIRD BEHAVIOR
MAYBE TREATED AS
COMMENT
a, b, c, d
1, 2, 3, 4
1, 2, 3, 4
```
and we'll get this result
```
D select * from read_csv_auto('test.csv', header=True);
┌───────┬───────┬───────┬───────┐
│   a   │   b   │   c   │   d   │
│ int32 │ int32 │ int32 │ int32 │
├───────┼───────┼───────┼───────┤
│     1 │     2 │     3 │     4 │
│     1 │     2 │     3 │     4 │
└───────┴───────┴───────┴───────┘
```

I'm happy to solve this issue but I wonder what is the expectation
Should we just ignore the inconsistent row or return error to the user, or any other recommendation?

**Comment by mark15217** [comment]
> Unrelated to this, but I just discovered that `auto_detect` is forced to true on `read_csv_auto` even when `auto_detect=false` is set explicitly.
> 
> Also the types set by `columns` are completely ignored when `auto_detect` is set, which also sounds like unexpected behavior when that `auto_detect` is set implicitly by `read_csv_auto`

I find that in this function `ReadCSVAutoBind`, auto_detect is set to true explicitly, which nullifies the user setup.

**Comment by Alex-Monahan** [comment]
> > Unrelated to this, but I just discovered that `auto_detect` is forced to true on `read_csv_auto` even when `auto_detect=false` is set explicitly.
> > Also the types set by `columns` are completely ignored when `auto_detect` is set, which also sounds like unexpected behavior when that `auto_detect` is set implicitly by `read_csv_auto`
> 
> I find that in this function `ReadCSVAutoBind`, auto_detect is set to true explicitly, which nullifies the user setup.

Yes, this is because we have a separate function for `read_csv` if you don’t want the auto behavior.
