### ISSUE TITLE
LATERAL JOIN and Window Functions issue

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#5669]
### What happens?

Combining lateral joins with window functions leads to a crash

### To Reproduce

Example file: https://github.com/malloydata/malloy/blob/ltabb/index-with-stages/test/data/duckdb/ga_sample.parquet

```sql
SELECT
       hits_0
    FROM  'ga_sample.parquet' ga_sessions
    , (SELECT
      row_number() over() as __row_id,
      x.access
      FROM
        (SELECT UNNEST(ga_sessions.hits)) as x(access)
    ) as hits_0
  GROUP BY 1
```

Without the window function the query behaves as expected:

```sql
  SELECT
       hits_0
    FROM  'ga_sample.parquet' ga_sessions
    , (SELECT
      x.access
      FROM
        (SELECT UNNEST(ga_sessions.hits)) as x(access)
    ) as hits_0
  GROUP BY 1
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Mark Raasveldt

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Something got confused and the test for `OVER()` is failing so this is my fault. But I have completely rewritten this stuff and was getting ready to push it, so I may just test it on the new code next week.

**Comment by hawkfish** [comment]
It looks like the lateral join rewrite added some partitioning? In which case this looks like a bug in the sort code so I will pass it to @lnkuiper

**Comment by hawkfish** [comment]
I think this is a bug in the comparison logic. It looks like `Comparators::CompareStructAndAdvance` does not advance the pointers when either of two non-constant columns is `NULL`.

**Comment by hawkfish** [comment]
I have a fix (and window was just an innocent bystander!) I may push before I figure out how to make a test case just so @lnkuiper can have a look at the code.
