### ISSUE TITLE
'Invalid unicode (byte sequence mismatch) detected in value construction' for JS UDF returning more than 12 characters

### ISSUE THREAD

**Issue by chrisbrain** [duckdb/duckdb#5670]
### What happens?

Getting `Invalid unicode (byte sequence mismatch) detected in value construction' when our UDF returns more than 12 characters.

I assume this is a bug, have not seen anywhere in docs or code where we can specify the UDF should return more.

### To Reproduce

Try running this test:
```
const duckdb = require('duckdb');
const assert = require('node:assert/strict');

it('0ary string > 12 characters', function(done) {

    db = new duckdb.Database(':memory:');

    // Works if string is 12 characters or less 
    const str = '0123456789123';

    db.register_udf("udf", "varchar", () => str);
    db.all("select udf() v", function(err, rows) {
        if (err) throw err;
        assert.equal(rows[0].v, str);
        done();
    });
    
});
```

### OS:

Ubuntu running on WSL on Windows x64

### DuckDB Version:

0.6.1

### DuckDB Client:

nodejs

### Full Name:

Chris Brain

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the report!

12 is the max length for an inlined string, so if I had to guess this is probably an issue related to allocations, if the memory contains random garbage

**Comment by chrisbrain** [comment]
Thanks for the quick response @Tishj!  - So this is a 'bug' and we should be able to return much longer text in these UDFs right?

**Comment by Tishj** [comment]
I haven't looked at or worked on this client code, so I cant say for sure
But I'd imagine this is not intended behavior

**Comment by chrisbrain** [comment]
Just a note that it's now be [confirmed ](https://github.com/duckdb/duckdb/pull/5697#issuecomment-1380707412)that the above 5697 doesn't actually fix this yet.
