### ISSUE TITLE
Referring to an object inside a CTE with the same name mistakenly thinks you're being recursive

### ISSUE THREAD

**Issue by gwenwindflower** [duckdb/duckdb#5673]
### What happens?

```sql
with

orders as (

    select * from analytics.orders

),
```

this will complain to me that i need to use `with recursive`, even though one of these is a database object and the other is a CTE, and it should probably be able to sort out which is which. i could understand if it was purely 'orders' in both places but that's not the case.

### To Reproduce

Try something like the below in a query, substituting orders for anything available, just make sure the CTE name and the db object have the same name.

```sql
with

orders as (

    select * from analytics.orders

),
```

### OS:

Intel macOS 13

### DuckDB Version:

0.6.1

### DuckDB Client:

SQL via duckdbt adapter

### Full Name:

Gwen Windflower

### Affiliation:

dbt Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

Unfortunately I can't seem to reproduce this.

```sql
create schema analytics;
create table analytics.orders(i int);
-- works
with orders as (
    select * from analytics.orders
) select * from orders;
set schema='analytics';
-- also works
with orders as (
    select * from orders
) select * from orders;
```

Could you perhaps provide a more complete and reproducible example of what goes wrong?

**Comment by gwenwindflower** [comment]
whoops! sorry about that, i made an assumption about what was happening and presented a simpler example based on that, but looks like i was wrong! my apologies!

i went back and narrowed my specific example down to the least amount of code that triggers the error, i _think_ this will reproduce:

```
with

orders as (

    select * from "main"."main"."stg_orders"

    where ordered_at >= (select max(ordered_at) from "main"."main"."orders")
    

),

some_more_logic as (

    select *

    from orders

)

select * from some_more_logic
```

Missing pieces from my earlier example: it seems you have to have the subquery and the downstream CTE to get it to throw the error. I won't try to guess what the issue is this time. 🙈 ☺️

**Comment by Mytherin** [comment]
Thanks! I can confirm this leads to a circular reference error, when it should not:

```sql
create table orders(ordered_at int);
create table stg_orders(ordered_at int);
with
orders as (
    select * from main.stg_orders
    where ordered_at >= (select max(ordered_at) from main.orders)
),
some_more_logic as (
    select *
    from orders
)
select * from some_more_logic;
```

**Comment by omo** [comment]
Seems to be a dup of #4987.
