### ISSUE TITLE
Node.js package is unnecessarily large

### ISSUE THREAD

**Issue by tobilg** [duckdb/duckdb#5696]
### What happens?

After an installation of the DuckDB Node.js client package, the directory structure under `node_modules/duckdb` looks like the following:

```bash
├── Makefile
├── README.md
├── binding.gyp
├── configure
├── duckdb.js
├── lib
│   ├── binding
│   │   └── duckdb.node
│   ├── duckdb-binding.js
│   ├── duckdb.d.ts
│   ├── duckdb.js
│   └── index.js
├── package.json
├── src
│   ├── connection.cpp
│   ├── data_chunk.cpp
│   ├── database.cpp
│   ├── duckdb.cpp
│   ├── duckdb.hpp
│   ├── duckdb_node.cpp
│   ├── duckdb_node.hpp
│   ├── parquet-amalgamation.cpp
│   ├── parquet-amalgamation.hpp
│   ├── statement.cpp
│   └── utils.cpp
├── test
│   ├── affected.test.js
│   ├── arrow.test.js
│   ├── data_type_support.test.js
│   ├── database_fail.test.js
│   ├── each.test.js
│   ├── exec.test.js
│   ├── extension.test.js
│   ├── interrupt.test.js
│   ├── jsdoc.test.js
│   ├── named_columns.test.js
│   ├── null_error.test.js
│   ├── open_close.test.js
│   ├── parallel_insert.test.js
│   ├── parquet.js
│   ├── pathnames.test.js
│   ├── prepare.test.js
│   ├── query_result.test.js
│   ├── serialization.test.js
│   ├── support
│   │   ├── createdb.js
│   │   ├── elmo.png
│   │   ├── helper.js
│   │   ├── prepare.csv
│   │   └── script.sql
│   ├── syntax_error.test.js
│   ├── typescript_decls.test.ts
│   ├── udf.test.js
│   └── unicode.test.js
└── tsconfig.json
```

In my opinion, there are a lot of files present in the package that don't really belong there, like the C++ source in `src/` and the tests in `test`. This uses more than 16,5mb space:

```bash
$ du -sh test src
528K	test
 16M	src
```

My suggestion is to add a `.npmignore` to the `tools/nodejs` folder similar to this:

```bash
.mocharc.json
Makefile
binding.gyp
configure
src/*.cpp
src/*.hpp
test/*.js
tsconfig.json
```

### To Reproduce

Install the DuckDB Node.js package via `npm i --save duckdb`, and then do a `cd node_modules/duckdb && tree`.

### OS:

Mac OS (but this is the same for all OS)

### DuckDB Version:

0.6.1

### DuckDB Client:

Node.js

### Full Name:

TobiLG

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
We do need the c++ files to compile on systems that we don't supply prebuilds for, but we could definitely exclude the tests.

We'd be happy to accept a pr with a npmignore 😊
