### ISSUE TITLE
Unexpected comparison of JSON arrays

### ISSUE THREAD

**Issue by Teggy** [duckdb/duckdb#5704]
### What happens?

The evaluation of a _less than_ `<` (or _greater than_`>`) comparison of two JSON arrays yields an unexpected outcome.  This is puzzling since the comparison of the contained JSON array _elements_ behaves like expected.

### To Reproduce

~~~
SELECT to_json(1) < to_json(10);         -- yields true (expected)

SELECT to_json([1]) < to_json([10]);     -- yields false (⚠️ unexpected)
~~~

Note that PostgreSQL (v14.1 in this case) yields the expected outcome for both expressions (`jsonb` is PostgreSQL's parsed JSON data type):

~~~
SELECT to_jsonb(1) < to_jsonb(10);                 -- yields true (expected)

SELECT to_jsonb(array[1]) < to_jsonb(array[10]);   -- yields true (expected)
~~~

### OS:

macOS Monterey

### DuckDB Version:

0.6.0

### DuckDB Client:

DuckDB CLI

### Full Name:

Torsten Grust

### Affiliation:

U Tübingen, Germany

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This appears to be because the physical type of JSON is a string and in ASCII `[` sorts after `0`.

**Comment by Teggy** [comment]
> This appears to be because the physical type of JSON is a string and in ASCII `[` sorts after `0`.

Yes, looks like it.  This appears to be in disagreement with DuckDB's documentation saying that _"The JSON logical type is interpreted as JSON, i.e., parsed, in JSON functions rather than interpreted as VARCHAR, i.e., a regular string."_

Thank you for looking into this.

**Comment by lnkuiper** [comment]
The comparison operator `<` is not a JSON function; therefore, the input will be treated as a string, which is the intended behavior. This behavior will not be changed in the future. Our JSON type is similar to Postgres' JSON type in that it is stored as a string. In Postgres, we cannot even compare this type:
```sql
postgres=# select '[1]'::JSON < '[10]'::JSON;
ERROR:  operator does not exist: json < json
LINE 1: select '[1]'::JSON < '[10]'::JSON;
                           ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
However, we are planning on adding a "parsed" (or, rather, decomposed) JSON type that will store JSON objects as our nested types. The comparison for this type should behave similarly to Postgres' JSONB.

**Comment by Teggy** [comment]
Thanks for the clarification.  `<` not being a JSON(-aware) function resolves this particular issue (which can be closed).

When you say _[o]ur JSON type is similar to Postgres' JSON type in that it is stored as a string_, does this contradict the DuckDB docs stating that _[t]he JSON logical type is interpreted as JSON, i.e., parsed, in JSON functions rather than interpreted as `VARCHAR`, i.e., a regular string_?   Do true JSON functions like `json_extract` re-parse the internal stored string on (every) invocation?

**Comment by lnkuiper** [comment]
The similarity is that it is stored as a string. We also interpret it as `JSON`, rather than a regular `VARCHAR`. I don't see the contradiction.

The `JSON` and `VARCHAR` types are interpreted differently in JSON functions:
```sql
D select json_object('duck', '{"goose": 42}');
┌──────────────────────────────────────┐
│ json_object('duck', '{"goose": 42}') │
│                 json                 │
├──────────────────────────────────────┤
│ {"duck":"{\"goose\": 42}"}           │
└──────────────────────────────────────┘
D select json_object('duck', '{"goose": 42}'::JSON);
┌────────────────────────────────────────────────────┐
│ json_object('duck', CAST('{"goose": 42}' AS JSON)) │
│                        json                        │
├────────────────────────────────────────────────────┤
│ {"duck":{"goose":42}}                              │
└────────────────────────────────────────────────────┘
```
In the first example, the value is treated as a`VARCHAR`, and therefore the quotes are escaped. In the second example, it is treated as `JSON`, and the quotes are not escaped.

The following will cause the JSON to be parsed twice:
```sql
select '{"duck": {"goose": 42}}'->'duck'->'goose';
```
This is, of course, not great for performance. However, we have a lot of ideas to improve our JSON extension. We plan on implementing a fully decomposed JSON type as mentioned. The fully decomposed JSON type will not have this issue of re-parsing.

I don't have a timeline for when this will be implemented.
