### ISSUE TITLE
ODBC driver: input bind parameters does not support timestamp

### ISSUE THREAD

**Issue by xumaofeng-jn** [duckdb/duckdb#5717]
### What happens?

1、execute sql like ： update test_table set timestamp_column = strptime('20221215101010','%Y%m%d%H%M%S') where ... 
2、bind parameter type is SQL_TYPE_TIMESTAMP
3、sql execute error

in tools/odbc/parameter_descriptor.cpp function ParameterDescriptor::SetValue
switch sql_desc_type not support SQL_TYPE_TIMESTAMP
I add this code then test was passed

`case SQL_TYPE_TIMESTAMP: {
    auto timestamp_struct = Load<SQL_TIMESTAMP_STRUCT>(dataptr);
    value = Value::TIMESTAMP(timestamp_struct.year, timestamp_struct.month, timestamp_struct.day,
                             timestamp_struct.hour, timestamp_struct.minute, timestamp_struct.second, 0);
    break;
}`

### To Reproduce

1、execute sql like ： update test_table set timestamp_column = strptime('20221215101010','%Y%m%d%H%M%S') where ... 
2、bind parameter type is SQL_TYPE_TIMESTAMP

### OS:

linux

### DuckDB Version:

0.6.1

### DuckDB Client:

odbc

### Full Name:

xumaofeng

### Affiliation:

huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Thanks for the report! This looks reasonable to me - can you submit a PR?

**Comment by xumaofeng-jn** [comment]
@hawkfish Sorry, I'm on the company intranet, for some  security reason，i can not submit a PR.

**Comment by hawkfish** [comment]
@xumaofeng-jn I've added your code and pushed it to my repository, but I don't have a box to test it on. Can you check?

**Comment by xumaofeng-jn** [comment]
> 

I have tested my added code. It is works for me.
