### ISSUE TITLE
ODBC driver: select result column mismatch

### ISSUE THREAD

**Issue by xumaofeng-jn** [duckdb/duckdb#5718]
### What happens?

1.  call SQLBindCol bind select result column, A column type is timestamp, size is 16 byte， B column type is timestamp, size is 16 byte
2. when fetch result, in tools/odbc/odbc_fetch.cpp line 358 ，use pointer_size=8 byte not bound_col.len=16 byte to calculate bind buffer address offset, this cause the B column result write to A column bind buffer，and B column bind buffer is null

### To Reproduce

1、select A, B from test_table
2、call SQLBindCol bind select result column, A column type is timestamp, size is 16 byte， B column type is timestamp, size is 16 byte
3、fetch result column mismatch，B column result write to A column bind buffer

### OS:

linux

### DuckDB Version:

0.6.1

### DuckDB Client:

odbc

### Full Name:

xumaofeng

### Affiliation:

huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you please try to make this a more complete, minimal, reproducible example?

**Comment by xumaofeng-jn** [comment]
@hannes 
This is a simple code  

`TIMESTAMP_STRUCT column_a {};
TIMESTAMP_STRUCT column_b {};
SQLLEN strlen_or_Ind_ptr = 0;


res = SQLBindCol(my_statement, 1, SQL_TYPE_TIMESTAMP, &column_a, sizeof(TIMESTAMP_STRUCT), &strlen_or_Ind_ptr);
res = SQLBindCol(my_statement, 2, SQL_TYPE_TIMESTAMP, &column_b, sizeof(TIMESTAMP_STRUCT), &strlen_or_Ind_ptr);

for (int i = 0;; i++)
{
    res = SQLFetch(my_statement);
    if (res == SQL_SUCCESS || res == SQL_SUCCESS_WITH_INFO)
        printf("column_a %d %d %d %d %d %d\n", column_a.year, column_a.month, column_a.day, column_a.hour, column_a.minute, column_a.second);
        printf("column_b %d %d %d %d %d %d\n", column_b.year, column_b.month, column_b.day, column_b.hour, column_b.minute, column_b.second); // this code print 0 0 0 0 0 0
    else
        break;
}
`
