### ISSUE TITLE
httpfs throws "parquet_scan has duplicate column name" when reading data exported by Snowflake

### ISSUE THREAD

**Issue by bigluck** [duckdb/duckdb#5735]
### What happens?

Duckdb is failing to load data when querying an S3 bucket with `parquet_scan()` using `HIVE_PARTITIONING = 1` when the final parquet files contain the column/columns used for partitioning the table.

```sql
INSTALL httpfs;
LOAD httpfs;

INSTALL parquet;
LOAD parquet;

SET s3_region='<my_s3_region>';
SET s3_access_key_id='<my_s3_access_key_id>';
SET s3_secret_access_key='<my_s3_secret_access_key>';

SELECT * FROM parquet_scan('s3://<my_s3_bucket>/<my_table_name>/*/*.parquet', HIVE_PARTITIONING = 1) LIMIT 1;
Error: Binder Error: table "parquet_scan" has duplicate column name "event_date"
```

This bug prevents Duckdb from reading tables exported from Snowflake.

### To Reproduce

Snowflake support exporting data on [external storage integrations](https://docs.snowflake.com/en/user-guide/data-load-s3-config-storage-integration.html) (like an S3 bucket) using PARQUET; however, hive partitions [are not supported in a standard way](https://docs.snowflake.com/en/sql-reference/sql/copy-into-location.html#partitioning-unloaded-rows-to-parquet-files), Snowflake simply regroups all the data into different folders following the manual-defined `PARTITION KEY` string:

```sql
COPY INTO 's3://<my_s3_bucket>/<my_table_name>'
FROM (
    SELECT *
    FROM <my_table>
    WHERE "event_date" = '2022-12-19'
)
PARTITION BY (
     'event_date=' || to_varchar("event_date")
  || '/column_2=' || to_varchar("column_2")
  || '/column_3=' || to_varchar("column_3")
)
STORAGE_INTEGRATION = <my_s3_integration>
MAX_FILE_SIZE = 32000000
HEADER = TRUE
FILE_FORMAT = ( TYPE = PARQUET COMPRESSION = SNAPPY );
```

In this example, even if `event_date` has been used to partition data into different folders:

```
s3://<my_s3_bucket>/<my_table_name>/event_date=2022-12-19/column_2=value_2/column_3=value_3/data_<UUID>_<N>.snappy.parquet
```

the final parquet file created by Snowflake still contains the column `event_date ` and its value:

```sql
DESCRIBE parquet_scan('s3://<my_s3_bucket>/<my_table_name>/event_date=2022-12-19/column_2=value_2/column_3=value_3/*.parquet', HIVE_PARTITIONING = 0) LIMIT 1;
┌──────────────────────────────────────────┬───────────────┬─────────┬─────────┬─────────┬─────────┐
│               column_name                │  column_type  │  null   │   key   │ default │  extra  │
│                 varchar                  │    varchar    │ varchar │ varchar │ varchar │ varchar │
├──────────────────────────────────────────┼───────────────┼─────────┼─────────┼─────────┼─────────┤
│ event_date                               │ DATE          │ YES     │         │         │         │
│        ·                                 │    ·          │  ·      │    ·    │    ·    │    ·    │
│        ·                                 │    ·          │  ·      │    ·    │    ·    │    ·    │
│        ·                                 │    ·          │  ·      │    ·    │    ·    │    ·    │
├──────────────────────────────────────────┴───────────────┴─────────┴─────────┴─────────┴─────────┤
│ 165 rows (20 shown)                                                                    6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
```

However, this behavior prevents Duckdb from scanning and automatically loading all the files using the `HIVE_PARTITIONING=1` flag. Indeed it fails and throws a `Binder Error: table "parquet_scan" has duplicate column name "event_date"` error.

Is it possible to implement the support for this use case?

### OS:

MacOS 13.1 (22C65) aarch64

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

duckdb_cli via homebrew

### Full Name:

Luca Bigon

### Affiliation:

Freelancer

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

@samansmink perhaps you can have a look at this after the holidays? Perhaps we should ignore columns in the file that match the hive partitioning keys if hive partitioning is enabled?

**Comment by Mytherin** [comment]
Can you try the latest version of DuckDB (v1.2.2)? If that still fails could you file an issue with a reproducible example so we can investigate?
