### ISSUE TITLE
ParserException error with recursive keywords

### ISSUE THREAD

**Issue by alexandre-szomonyak** [duckdb/duckdb#5742]
### What happens?

Whenever I try to use a recursive keyword in my query I get a ParserException error. Whether it is "WHILE", "REPEAT", or a recursive CTE. I get the same error every time. 

I wrote a very basic query to portray my problem. 

My error:
duckdb.ParserException: Parser Error: syntax error at or near "WHILE"

### To Reproduce

import duckdb

con = duckdb.connect(database='DBPL.duckdb', read_only=False)

print(con.execute("""
CREATE TEMP TABLE distances (
    author VARCHAR, 
    distance INTEGER
);

INSERT INTO distances (author, distance)
VALUES ('%Jack%', 0);
    
WHILE (distances.author NOT IN ('%Paul Erdos%')) DO
    INSERT INTO distances (author, distance)
    VALUES ('%Paul Erdos%', 0);
END WHILE;
    
SELECT d.author 
FROM distances d 
WHERE d.author = 'Billy' 
""").fetchall())

con.close()

### OS:

Windows 10

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Alexandre Szomonyak

### Affiliation:

unaffiliated

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello!

I don't believe that we support the `WHILE` keyword. However, `WITH RECURSIVE` should work! Can you post the recursive CTE that is not working for you? 

https://duckdb.org/docs/sql/query_syntax/with

**Comment by Mytherin** [comment]
`WHILE`, `REPEAT` and other such constructs are not currently supported, so this is expected to not work. Feel free to open a [discussion requesting this feature](https://github.com/duckdb/duckdb/discussions).
