### ISSUE TITLE
Fail to import .parquet file created with parquet-go

### ISSUE THREAD

**Issue by vedantroy** [duckdb/duckdb#5744]
### What happens?

When trying to import a column which uses snappy compression, duckdb throws the error:

```
Error: Invalid Error: Snappy decompression failure: Uncompressed data size mismatch
```

even though this column can be loaded by both `pandas` and `parquet-tools`.

### To Reproduce

I've attached the .parquet file to this issue, if you want to skip the Golang step.

1. Create the parquet file using the following code:

```
package main

import (
[out.zip](https://github.com/duckdb/duckdb/files/10268874/out.zip)

	"fmt"
	"os"

	"github.com/segmentio/parquet-go"
)

type RowType struct {
	// Need dict encoding for all fields
	// Snappy compression for FirstName
	FirstName string `parquet:"FirstName,dict,snappy"`
	Data      []byte `parquet:"Data,dict"`
}

func main() {
	// create 5 rows, with random data & FirstName "John"
	rows := make([]RowType, 5)
	for i := 0; i < 5; i++ {
		row := RowType{
			FirstName: "Baz",
			Data:      []byte("Hello World"),
		}
		rows[i] = row
	}
	fmt.Println("# of rows:", len(rows))

	// Check if file exists
	name := "test.parquet"
	if _, err := os.Stat(name); err == nil {
		fmt.Println("File exists, deleting...")
		os.Remove(name)
	}

	// Open a file for writing
	f, err := os.Create(name)
	if err != nil {
		panic(err)
	}

	wtr := parquet.NewGenericWriter[RowType](f)
	_, err = wtr.Write(rows)
	if err != nil {
		panic(err)
	}
	if err := wtr.Close(); err != nil {
		panic(err)
	}
}
```

2.

Run the following SQL:
```
select FirstName from "wherever-you-put-the-file";
```

it should give the error:
```
Error: Invalid Error: Snappy decompression failure: Uncompressed data size mismatch
```

### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

CLI

### Full Name:

Vedant Roy

### Affiliation:

Myself

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by vedantroy** [comment]
Not sure if the file got uploaded, so attaching it again to this comment.
[out.zip](https://github.com/duckdb/duckdb/files/10268886/out.zip)

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #5767. The issue was that parquet-go was using a new flag in the Parquet V2 format called `compressed` that allows a specific chunk to be written in uncompressed format, despite a compression method being defined. We should now correctly check for this flag.

**Comment by vedantroy** [comment]
@Mytherin  -- thanks for the prompt fix. If I want to use duckdb with this fix enabled, is there a prebuilt release for a given commit--or do I need to build from source?

**Comment by Mytherin** [comment]
There are pre-release builds available for some platforms, see the [installation page](https://duckdb.org/docs/installation/).
