### ISSUE TITLE
 RLE Compression

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#575]
Goal: Implement RLE Compression and support the execution of RLE Vectors.

RLE Execution:
Use the Orrify methods, give a vector and produce a pointer and a list of offsets to that pointer to get the vectors. For that just need to set the data pointer and the selection vector of the VectorData. 
This is nice for RLE because I can abuse it without actually decompressing it (i.e., use the pointer + offset instead of actually copying the data).
```cpp
struct VectorData {
	const SelectionVector *sel;
	data_ptr_t data;
	nullmask_t *nullmask;
}; 

int *idata = (int*) vdata.data;
```

One example of how this would look like is:
Actual Data : [1][1][1][7][7][7][7][10]
RLE Compressed: RUNS:   [3][4][1]
                              VALUES: [1][7][10]
Sel Vector:  [0][0][0][1][1][1][2]

3-Phase Plan:
1) - Construct the RLE Segments (A compressed variant of UncompressedSegment). Start with flag to use the Compressed segments during testing.
- Switcheroo between RLESegment/UncompressedSegment

2) Construct RLE vectors, should also emit constant vectors (Implement Orrify/Normalify)

3) Profit

**Comment by hawkfish** [comment]
There are opportunities here for operating on the compressed data without expansion. For example, consider `extract`ing the month of a `date` column. Columns of type `date` are often naturally sorted and will RLE compress. The month calculation is computationally complex, but by computing it only on the compressed instances - and emitting another RLE compressed column - we could make it tens to hundreds of times faster.  This optimisation generalises to any single  RLE column combined with one or more constant columns.

**Comment by danz68** [comment]
In fact, this idea can be further enhanced. Based on column(s) cardinality (if available) complex expressions evaluation can be improved using [chunks sort, RLE estimate, restore order] operations or better.

**Comment by hannes** [comment]
Added in #2099
