### ISSUE TITLE
Type error with CROSS JOIN and range()

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#5762]
### What happens?

I would expect this query to produce three rows, one per month between 2022-01-01 and 2022-04-01. Instead, it produces an error that does not make sense to me:

```sql
D select * from (VALUES (date '2022-01-01', date '2022-04-01')) t(a, b) cross join range(a, b, interval '1' month);
Error: Binder Error: No function matches the given name and argument types 'range(VARCHAR, VARCHAR, INTERVAL)'. You might need to add explicit type casts.
	Candidate functions:
	range(BIGINT)
	range(BIGINT, BIGINT)
	range(BIGINT, BIGINT, BIGINT)
	range(TIMESTAMP, TIMESTAMP, INTERVAL)
```

I tried some other stuff:
``` sql
D select * from (VALUES (date '2022-01-01', date '2022-04-01')) t(a, b) cross join range(a::date, b::date, interval '1' month);
Error: Conversion Error: date field value out of range: "a", expected format is (YYYY-MM-DD)
D select * from (VALUES (date '2022-01-01', date '2022-04-01')) t(a, b) cross join range(a::datetime, b::datetime, interval '1' month);
Error: Conversion Error: timestamp field value out of range: "a", expected format is (YYYY-MM-DD HH:MM:SS[.US][±HH:MM| ZONE])
D select * from (VALUES (date '2022-01-01', date '2022-04-01')) t(a, b) cross join range(a::timestamp, b::timestamp, interval '1' month);
Error: Conversion Error: timestamp field value out of range: "a", expected format is (YYYY-MM-DD HH:MM:SS[.US][±HH:MM| ZONE])
```

The following query works just fine in Postgres (though `generate_series` treats its second endpoint as inclusive):

```sql
select * from (VALUES (date '2022-01-01', date '2022-04-01')) t(a, b) cross join generate_series(a, b, interval '1' month)
```

### To Reproduce

See above! I'm using the duckdb 0.6.1 shell

### OS:

Mac 13.1, Apple Silicon

### DuckDB Version:

0.6.1

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

What you are trying to do is use a [LATERAL join](https://github.com/duckdb/duckdb/pull/5393) - which allows you to use arguments from one part of the FROM clause in another part of the FROM clause. We have only recently added support for this in master. In your example, `a` and `b` are converted to string literals instead because `range` is implemented as a standard table function that does not support non-constant parameters - which is why the given error is thrown. See [here](https://github.com/duckdb/duckdb/pull/5485) for more information.

This works in the latest master with a minor rewrite after the implementation of LATERAL joins:

```sql
D select * from (VALUES (date '2022-01-01', date '2022-04-01')) t(a, b) cross join (select unnest(range(a, b, interval '1' month)));
┌────────────┬────────────┬──────────────────────────────────────────────────────┐
│     a      │     b      │ unnest(range(a, b, to_months(CAST('1' AS INTEGER)))) │
│    date    │    date    │                      timestamp                       │
├────────────┼────────────┼──────────────────────────────────────────────────────┤
│ 2022-01-01 │ 2022-04-01 │ 2022-03-01 00:00:00                                  │
│ 2022-01-01 │ 2022-04-01 │ 2022-02-01 00:00:00                                  │
│ 2022-01-01 │ 2022-04-01 │ 2022-01-01 00:00:00                                  │
└────────────┴────────────┴──────────────────────────────────────────────────────┘

```

**Comment by zenazn** [comment]
Oh, nice! Looking forward to the next duckdb release :)

Happy holidays!
