### ISSUE TITLE
Glob syntax not working in combination with fully qualified s3url

### ISSUE THREAD

**Issue by cohenj-else** [duckdb/duckdb#5766]
### What happens?

Using the fully qualified s3url to provide credentials (https://github.com/duckdb/duckdb/pull/4786), querying multiple files in s3 using glob syntax fails with error:
```
Error: Invalid Error: HTTP GET error on 'https://bucketname.s3.amazonaws.com/?encoding-type=url&list-type=2&prefix=directory' (HTTP 403)
```

### To Reproduce

SELECT * FROM "s3://bucket/directory/*.parquet?s3_access_key_id=accessKey&s3_secret_access_key=secretKey"

### OS:

macOS

### DuckDB Version:

0.6.1 & latest master

### DuckDB Client:

CLI

### Full Name:

J Cohen

### Affiliation:

Elsevier

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by LindsayWray** [comment]
The PR #5774 got merged into master, so I will be closing this issue. Thanks for reporting!

**Comment by cohenj-else** [comment]
Thanks very much!
