### ISSUE TITLE
"INTERNAL Error: Writes are not correctly aligned!?" when copying parquet

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#5779]
### What happens?

When running the following query in a `duckdb` shell, it exits with an error:
``` sql
COPY (SELECT * FROM '/path/to/a.parquet') TO '/path/to/b.parquet' (FORMAT 'parquet', CODEC 'zstd')
```
Error: `Error: INTERNAL Error: Writes are not correctly aligned!?`

### To Reproduce

There is something about `/path/to/a.parquet` in particular that is causing this issue. It is a 1,800,000-row, 34-column dataset with a mixture of column types, that was itself generated as the result of a DuckDB query of the same general format (`COPY (...) TO '/path/to/a.parquet' (FORMAT 'parquet', CODEC 'zstd')`)

I have been unable to find a short reproducer. Fortunately the file (~18MB) is only mildly sensitive (as in, I'd rather it not be floating around the internet, but it does not contain customer data), so I'm happy sharing it with folks who want to take a whack at debugging it. 

### OS:

Mac 13.1, M1

### DuckDB Version:

0.6.1

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by zenazn** [comment]
FWIW, the error in the Node bindings was `Assertion failed: (write_count > 0), function Write, file parquet-amalgamation.cpp, line 5257.`

**Comment by Mytherin** [comment]
Thanks for the report! Could you send the file to my email (mark@duckdblabs.com)? Happy to take a stab at it.
