### ISSUE TITLE
Error when trying to join to alias

### ISSUE THREAD

**Issue by georgewfraser** [duckdb/duckdb#5788]
### What happens?

This query fails with `Serialization Error: Cannot copy BoundSubqueryExpression`

### To Reproduce

```sql
create table orders as
select 
    cast(random()*100 as integer) + 1 as customer_id, 
    date '2020-01-01' + interval (cast(random()*365*10 as integer)) days as order_date,
    cast(random()*1000 as integer) as order_amount,
from range(0, 1000)
order by order_date;

select 
    (select distinct date_trunc('month', order_date) from orders) as month,
    (select sum(order_amount) from orders where date_trunc('month', order_date) = month) as revenue;
```

### OS:

macOS

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

CLI

### Full Name:

George Fraser

### Affiliation:

Fivetran

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by georgewfraser** [comment]
(I filled out the affiliation but this is not actually Fivetran-related)

**Comment by l1t1** [comment]
```sql
with t(month) as
    (select distinct date_trunc('month', order_date) from orders) 
select    (select sum(order_amount) from orders where date_trunc('month', order_date) = month) as revenue
from t;
```

**Comment by Alex-Monahan** [comment]
Howdy!
Do you know if this query succeeds in other SQL engines? 
My best guess is that DuckDB is interpreting these as tables instead of columns. Could you try:
```sql
select 
*
FROM
    (select distinct date_trunc('month', order_date) from orders) as month,
    (select sum(order_amount) from orders where date_trunc('month', order_date) = month) as revenue;
```

**Comment by l1t1** [comment]
or
```sql
select date_trunc('month', order_date)as month, sum(order_amount) as revenue
from orders
group by month;
```

**Comment by georgewfraser** [comment]
I'm not looking for help with my sql query. The issue here is that duckdb fails with a bad error message.

**Comment by Mytherin** [comment]
Thanks for the report! I have improved the error message in #5855. In the future we should be able to actually run this query but for now this is not yet supported.
