### ISSUE TITLE
Casting timestamp to timestamptz changes the time in local time

### ISSUE THREAD

**Issue by paulrosenzweig** [duckdb/duckdb#5791]
### What happens?

Setting the session timezone as non-UTC and converting a `timestamp` to a `timestamptz` changes which instant is represented. 

For example, casting `'2023-01-01 00:00:00'::timestamp` to `timestamptz` while timezone is set to US/Eastern results in `2022-12-31 19:00:00-05`. I believe it should be `2023-01-01 00:00:00-05`, which is what Postgres returns.

Stated differently, if I have a `timestamp` showing midnight in local time, converting to a `timestamptz` should still be midnight in local time. Currently, it switches to midnight in UTC.

### To Reproduce

I think the third `select` is the wrong behavior. 
```
D set timezone='US/Eastern';
D select '2023-01-01 00:00:00'::timestamp;
┌──────────────────────────────────────────┐
│ CAST('2023-01-01 00:00:00' AS TIMESTAMP) │
│                timestamp                 │
├──────────────────────────────────────────┤
│ 2023-01-01 00:00:00                      │
└──────────────────────────────────────────┘
D select '2023-01-01 00:00:00'::timestamptz;
┌─────────────────────────────────────────────────────────┐
│ CAST('2023-01-01 00:00:00' AS TIMESTAMP WITH TIME ZONE) │
│                timestamp with time zone                 │
├─────────────────────────────────────────────────────────┤
│ 2023-01-01 00:00:00-05                                  │
└─────────────────────────────────────────────────────────┘
D select '2023-01-01 00:00:00'::timestamp::timestamptz;
┌────────────────────────────────────────────────────────────────────────────┐
│ CAST(CAST('2023-01-01 00:00:00' AS TIMESTAMP) AS TIMESTAMP WITH TIME ZONE) │
│                          timestamp with time zone                          │
├────────────────────────────────────────────────────────────────────────────┤
│ 2022-12-31 19:00:00-05                                                     │
└────────────────────────────────────────────────────────────────────────────┘
```

I agree with Postgresql's behavior:

```
db=# set timezone='US/Eastern';
SET
db=# select '2023-01-01 00:00:00'::timestamp;
      timestamp      
---------------------
 2023-01-01 00:00:00
(1 row)

db=# select '2023-01-01 00:00:00'::timestamptz;
      timestamptz       
------------------------
 2023-01-01 00:00:00-05
(1 row)

db=# select '2023-01-01 00:00:00'::timestamp::timestamptz;
      timestamptz       
------------------------
 2023-01-01 00:00:00-05
(1 row)

```

### OS:

macOS 11.6.8 Intel

### DuckDB Version:

v0.6.2-dev772 ec4a46083e

### DuckDB Client:

DuckDB CLI

### Full Name:

Paul Rosenzweig

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Actually it doesn't change the instant because `2022-12-31 19:00:00-05 == 2023-01-01 00:00:00+00` (we just copy the value under the hood). The issue is that in the cast PG assumes that the `TS` is a naïve (local) timestamp and extracts the parts in UTC and uses them to construct a `TSTZ` in the current time zone. We will have to patch the cast in ICU somehow.

**Comment by hawkfish** [comment]
The inverse cast is also supposed to use naive timestamps and I will fix that too.
