### ISSUE TITLE
Validate JSON before hitting storage layer?

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb#5798]
### What happens?

It seems for the `JSON` extension it doesn't check that it's valid before saving the value. For example:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/909771/209902291-d52e4900-1e8b-4e74-af65-fe8f850e78bd.png">

Is there a way to make sure that the `JSON` value is valid when using that type? For example, what Postgres does vs DuckDB:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/909771/209902391-66b16886-7b7e-402c-b2c9-dfd75355b57f.png">

### To Reproduce

```
SELECT JSON '{';
```

### OS:

OSX

### DuckDB Version:

v0.6.0 2213f9c946

### DuckDB Client:

Shell

### Full Name:

David Litwin

### Affiliation:

N/A

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Perhaps @lnkuiper can have a look at this when he is back? I would say we should validate when converting strings to JSON in e.g. the cast from varchar -> JSON.

**Comment by lnkuiper** [comment]
Closed via #5544
