### ISSUE TITLE
INSERT with RETURNING doesn't return values on tables with INTEGER or FLOAT datatypes in parameterized query

### ISSUE THREAD

**Issue by moonhouse** [duckdb/duckdb#5800]
### What happens?

When using an `INSERT` statement with `RETURNING` from Python 3.11.1 and duckdb 0.6.1 I don't get any values back when the table has columns with INTEGER or FLOAT datatypes. When I try the same statements in the duckdb CLI I get the expected behavior.

### To Reproduce

Running this code
````python
import duckdb

con = duckdb.connect()

print(con.execute("SELECT * FROM  pragma_version()").fetchall())
con.execute("CREATE TABLE fruits(id INTEGER PRIMARY KEY, name TEXT)")
con.execute("CREATE SEQUENCE seq_fruitid start 1")
results = con.execute("INSERT INTO fruits VALUES (nextval('seq_fruitid'), ?) RETURNING *", ['apple']).fetchall()
print(results)
results = con.execute("SELECT * FROM fruits").fetchall()
print(results)

con.execute("CREATE TABLE flowers(id INTEGER PRIMARY KEY, name TEXT, petals INTEGER)")
con.execute("CREATE SEQUENCE seq_flowerid start 1")
results = con.execute("INSERT INTO flowers VALUES (nextval('seq_flowerid'), ?, ?) RETURNING *", ['rose', 1]).fetchall()
print(results)
results = con.execute("SELECT * FROM flowers").fetchall()
print(results)

````
returns 
```
[('0.6.1', '919cad22e8')]
[(1, 'apple')]
[(1, 'apple')]
[(1,)]
[(1, 'rose', 1)]
```
I expected the fourth line to be the same as the fifth one. (I have also tested this with the latest available 0.6.2-dev895 with the same, unwanted, result.)

### OS:

MacOS Monterey 12.5.1 (aarch64)

### DuckDB Version:

v0.6.1

### DuckDB Client:

Python

### Full Name:

David Hall

### Affiliation:

Mynewsdesk

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the report, that seems like a bug we should fix :)

I'm confused by this though:
> When I try the same statements in the duckdb CLI I get the expected behavior.

As far as I understand, the way to reproduce this in the CLI is:
```sql
create table flowers(id integer primary key, name text, petals integer);
create sequence seq_flowerid start 1;
prepare v1 as insert into flowers values (nextval('seq_flowerid'), ?, ?) returning *;
execute v1('rose', 1);
```

That last `execute` does not return anything, and I can't combine this with a select either

**Comment by moonhouse** [comment]
> Thanks for the report, that seems like a bug we should fix :)
> 
> I'm confused by this though:
> 
> > When I try the same statements in the duckdb CLI I get the expected behavior.
> 
> As far as I understand, the way to reproduce this in the CLI is:
> 
> ```sql
> create table flowers(id integer primary key, name text, petals integer);
> create sequence seq_flowerid start 1;
> prepare v1 as insert into flowers values (nextval('seq_flowerid'), ?, ?) returning *;
> execute v1('rose', 1);
> ```
> 
> That last `execute` does not return anything, and I can't combine this with a select either

Yes, you are correct. I did miss the detail that I had a prepared statement in the Python case but not in the CLI case. So they were not directly comparable. 

Can confirm that when sending inserted values in the query string and not separate as parameters it does return the inserted values.
````python
results = con.execute("INSERT INTO flowers VALUES (nextval('seq_fruitid'), 'rose', 1) RETURNING *").fetchall()
````
did return `[(3, 'rose', 1)]`. So the behavior I reported is limited to RETURNING on INSERT when one of the parameters sent to a prepared statement is numeric. (Or at least INTEGER or FLOAT. I haven't exhaustively tested the different data types, just those two plus TEXT.) I updated the issue title about being on parameterized queries.
