### ISSUE TITLE
timezone('America/Denver', TIMESTAMPTZ '2001-02-16 20:38:40-05') not working on 0.6.1

### ISSUE THREAD

**Issue by rhofland** [duckdb/duckdb#5802]
### What happens?

Tried an example on the documentation site: [at-time-zone](https://duckdb.org/docs/sql/functions/timestamptz#at-time-zone). I tried both the function and the  syntactic sugar for the (two argument) timezone. Both resulted in error, see below.

### To Reproduce

```

D select version();
┌───────────┐
│ version() │
│  varchar  │
├───────────┤
│ v0.6.1    │
└───────────┘
D select timezone('America/Denver', TIMESTAMPTZ '2001-02-16 20:38:40-05');
Error: Binder Error: No function matches the given name and argument types 'timezone(VARCHAR, TIMESTAMP WITH TIME ZONE)'. You might need to add explicit type casts.
	Candidate functions:
	timezone(TIMESTAMP WITH TIME ZONE) -> BIGINT
	timezone(DATE) -> BIGINT
	timezone(TIMESTAMP) -> BIGINT
	timezone(INTERVAL) -> BIGINT

LINE 1: select timezone('America/Denver', TIMESTAMPTZ ...
               ^
D select timestamp with time zone '2001-02-16 20:38:40-05' AT TIME ZONE 'America/Denver';
Error: Binder Error: No function matches the given name and argument types 'timezone(VARCHAR, TIMESTAMP WITH TIME ZONE)'. You might need to add explicit type casts.
	Candidate functions:
	timezone(TIMESTAMP WITH TIME ZONE) -> BIGINT
	timezone(DATE) -> BIGINT
	timezone(TIMESTAMP) -> BIGINT
	timezone(INTERVAL) -> BIGINT

LINE 1: ...ith time zone '2001-02-16 20:38:40-05' AT TIME ZONE 'America/Denver';
```

### OS:

Debian 11 x86_64

### DuckDB Version:

0.6.1

### DuckDB Client:

cli

### Full Name:

Rudolf Hofland

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This is working for me on master. I suspect it didn't make the 0.6.1 release.
