### ISSUE TITLE
Python + PyArrow table + Map function = InvalidInputException

### ISSUE THREAD

**Issue by ahemon** [duckdb/duckdb#5803]
### What happens?

Hello, thanks a lot for all the work, I'm trying to run a UDF function in python from an arrow table but for some reason, I'm unable to. Even with a simple lambda that returns the argument, I get InvalidInputException. (see reproduce code) Is this because I use an Arrow table or is this a bug?
Thanks again.

### To Reproduce

Run following code:
```
import pyarrow as pa
import duckdb

if __name__ == '__main__':
    schema = pa.schema([
        pa.field("content", pa.string()),
    ])

    arrow_table = pa.table([
        [
            "Line 1",
            "Line 2",
            "Line 3",
            "Line 4",
        ]
    ], schema=schema)

    my_table = duckdb.arrow(arrow_table)
    print(my_table.filter("content LIKE '%Line%'").fetchall())
    print(my_table.filter("content LIKE '%Line%'").map(lambda my_df: my_df).fetchall())
```

Output:
```
[('Line 1',), ('Line 2',), ('Line 3',), ('Line 4',)]
Traceback (most recent call last):
  File "/Users/arthurh/PycharmProjects/test_db/main.py", line 35, in <module>
    print(my_table.filter("content LIKE '%Line%'").map(lambda my_df: my_df).fetchall())
duckdb.InvalidInputException: Invalid Input Error: UDF column type mismatch, expected [NULL], got [VARCHAR]

Process finished with exit code 1

```

### OS:

macOS

### DuckDB Version:

latest

### DuckDB Client:

Python

### Full Name:

Arthur Hemon

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Howdy! I think the map functions are designed to work with Pandas dataframes. Could you try using Pandas instead as a workaround?

**Comment by Tishj** [comment]
Alex is mostly right, I just looked into this a little, the return type of the function should be a Pandas Dataframe, which it is.
But the output chunk it's getting seems borked

When I go up a little to pipeline executor, it's fed two chunks, one looks good, and the other is NULL
```
(lldb) p intermediate_chunks[0]->Print()
Chunk - [1 Columns]
- FLAT VARCHAR: 4 = [ Line 1, Line 2, Line 3, Line 4]

(lldb) p intermediate_chunks[1]->Print()
Chunk - [1 Columns]
- FLAT NULL: 0 = [ ]
```

**Comment by waltersf** [comment]
I wrote a simple code to test `map()`, but if even using Pandas dataframe, if it contains a column of type `object` (VARCHAR), `map()` raises the error `duckdb.InvalidInputException: Invalid Input Error: UDF column type mismatch, expected [NULL], got [VARCHAR]`. 

Code:
```
df = pd.DataFrame.from_dict({'a': ['test', 'test', 'test']})
conn = duckdb.connect()
testrel = conn.query('select * from df')
newdf1 = testrel.map(lambda df : df)
print(newdf1.df())
```
Code works OK if the column type is INTEGER or DOUBLE and even DATETIME, but not for VARCHAR.

I'm using duckdb version 0.6.1.

**Comment by Tishj** [comment]
This has since been fixed, the reproduction file outputs:
```
[('Line 1',), ('Line 2',), ('Line 3',), ('Line 4',)]
[('Line 1',), ('Line 2',), ('Line 3',), ('Line 4',)]
```
