### ISSUE TITLE
Relational API orders NAs first, how can we order them last?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#5831]
### What happens?

In the relational API, `rel_order()` does the same as `ORDER BY` in SQL -- `NULL`s are ordered first. How can we make them appear last, for compatibility with data frames?

### To Reproduce

``` r
library(duckdb)
#> Loading required package: DBI

df <- data.frame(a = c(1:2, NA))

dplyr::arrange(df, a)
#>    a
#> 1  1
#> 2  2
#> 3 NA

con <- dbConnect(duckdb())

rel <- duckdb:::rel_from_df(con, df)

exprs <- list(duckdb:::expr_reference("a"))

out <- duckdb:::rel_order(rel, exprs)
out
#> DuckDB Relation: 
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Order [a ASC]
#>   r_dataframe_scan(0x1104eb860)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - a (INTEGER)

duckdb:::rapi_rel_to_df(out)
#> # A tibble: 3 × 1
#>       a
#>   <int>
#> 1    NA
#> 2     1
#> 3     2
```

<sup>Created on 2023-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOs aarch64

### DuckDB Version:

2dcdc245566bb9a0fc717bc9d2c3867f911abc6d

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rsund** [comment]
NULLS_LAST instead NULLS_FIRST [here](https://github.com/duckdb/duckdb/blob/2dcdc245566bb9a0fc717bc9d2c3867f911abc6d/tools/rpkg/src/relational.cpp#L165) ?

**Comment by Tmonster** [comment]
It should also be possible to specific that  with `PRAGMA default_null_order='NULLS LAST';`
Something like
`DBI::dbExecute(con, "PRAGMA default_null_order='NULLS LAST'")`
But I imagine it may get overridden by the code that @rsund pointed out

**Comment by krlmlr** [comment]
Thanks. The `PRAGMA` doesn't work, changing the code does.

**Comment by Mytherin** [comment]
Great - can this be closed?

**Comment by krlmlr** [comment]
We need a mainline fix that changes https://github.com/duckdb/duckdb/blob/2dcdc245566bb9a0fc717bc9d2c3867f911abc6d/tools/rpkg/src/relational.cpp#L165 .
