### ISSUE TITLE
Relational API thinks that `SUM(<empty>)` is `NULL`, how to change it to 0?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#5832]
### What happens?

For the corner case of an empty input, `SUM()` over a column returns `NULL` . This is perhaps consistent with SQL, but not with the data frame behavior.

### To Reproduce

``` r
library(duckdb)
#> Loading required package: DBI

df <- data.frame(a = integer())

dplyr::summarise(df, sum(a))
#>   sum(a)
#> 1      0

con <- dbConnect(duckdb())

rel <- duckdb:::rel_from_df(con, df)

ref <- duckdb:::expr_reference("a")
fn <- duckdb:::expr_function("sum", list(ref))
exprs <- list(fn)

out <- duckdb:::rel_aggregate(rel, list(), exprs)
out
#> DuckDB Relation: 
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Limit 1
#>   Aggregate [sum(a)]
#>     r_dataframe_scan(0x10f686698)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - sum(a) (HUGEINT)

duckdb:::rapi_rel_to_df(out)
#> # A tibble: 1 × 1
#>   `sum(a)`
#>      <dbl>
#> 1       NA
```

<sup>Created on 2023-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

2dcdc245566bb9a0fc717bc9d2c3867f911abc6d

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Can this be solved generating a case statement over the sum, e.g. `CASE WHEN SUM(x) IS NULL THEN 0 ELSE SUM(x) END`?

**Comment by krlmlr** [comment]
Perhaps. How can I create a macro `"sum"` that expands to this expression?

```sh
cat <<EOF | build/debug/duckdb
CREATE MACRO "sum"(x) AS (CASE WHEN SUM(x) IS NULL THEN 0 ELSE SUM(x) END);
SELECT sum(1);
EOF
# [1]    14483 done                cat <<<'' |
#        14484 segmentation fault  build/debug/duckdb
```

**Comment by hannes** [comment]
Can you file a bug on the please?

**Comment by krlmlr** [comment]
Done: #5853.

**Comment by krlmlr** [comment]
The wrapper macro works for me. I wonder if we can also add R's default `na.rm = FALSE` behavior to such a macro.

**Comment by Mytherin** [comment]
We could use a case statement for that as well, e.g.:

```sql
CREATE MACRO min_no_na_rm(x) AS
(CASE WHEN COUNT(x)<COUNT(*) THEN NULL ELSE MIN(x) END);

create table integers(i int);
insert into integers values (NULL), (1), (2);
select min(i), min_no_na_rm(i) FROM integers;
```

**Comment by krlmlr** [comment]
Thanks, I'll try it out when this becomes relevant.
