### ISSUE TITLE
SAMPLE clause not working when using PERCENT (or even %)

### ISSUE THREAD

**Issue by waltersf** [duckdb/duckdb#5839]
### What happens?

A very basic query, executed using the Python library, fails to return the correct result:

```sql 
select * from range(100) using sample 10% (system, 250)
```

For some percentages, it returns 0 records, for other, it returns 100% of records (even percentage being different from 100%). Expected result: 10% of the rows.

### To Reproduce

Code used:

```py
import duckdb
conn = duckdb.connect()
conn.execute('select * from range(100) using sample 10% (system, 250)').df()
```
Result:
```py
Empty DataFrame
Columns: [range]
Index: []
```

Changing `%` to `PERCENT` also does not work.

### OS:

Windows 11, with WSL 2/Ubuntu 20.04

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Walter Santos

### Affiliation:

UFMG (Brazil)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is expected behavior, see the [documentation on system sampling](https://duckdb.org/docs/sql/samples.html#system). 

> System sampling is a variant of bernoulli sampling with one crucial difference: every vector is included with a chance equal to the sampling percentage. This is a form of cluster sampling. System sampling is more efficient than bernoulli sampling, as no per-tuple selections have to be performed. There is almost no extra overhead for using system sampling, whereas bernoulli sampling can add additional cost as it has to perform random number generation for every single tuple.

> System sampling is not suitable for smaller data sets as the granularity of the sampling is on the order of ~1000 tuples. That means that if system sampling is used for small data sets (e.g. 100 rows) either all the data will be filtered out, or all the data will be included.

Use `bernoulli` sampling if you want per-row random sampling.
