### ISSUE TITLE
Export-import of database (CSV) with VARCHAR[] that includes a string with a single quote fails

### ISSUE THREAD

**Issue by paulewog** [duckdb/duckdb#5840]
### What happens?

When attempting to import a CSV file (including after the native database export/import functionality) that has a VARCHAR[] column, if the value of that column is a string that includes a quote, it fails with a the VARCHAR -> LIST cast error.

Example:
```
D import database 'stuff.csv';
Error: Invalid Input Error: Type VARCHAR with value '[kirk's]' can't be cast to the destination type LIST at line 2 in column 0. Parser options:
```

Or:
```
D CREATE TABLE things (list VARCHAR[]);
D INSERT INTO things SELECT * FROM 'things.csv';
Error: Conversion Error: Type VARCHAR with value '[kirk's]' can't be cast to the destination type LIST
```

However, it does work when there's no quote involved:
```
D INSERT INTO things SELECT * FROM 'things-noquote.csv';
D select * from things;
┌───────────┐
│   list    │
│ varchar[] │
├───────────┤
│ [kirks]   │
└───────────┘
```

### To Reproduce

Using [things.csv](https://github.com/duckdb/duckdb/files/10361867/things.csv):
```
D CREATE TABLE things (list VARCHAR[]);
D INSERT INTO things SELECT * FROM 'things.csv';
```

### OS:

Mac OSX AMD64

### DuckDB Version:

0.6.1, and latest master

### DuckDB Client:

CLI

### Full Name:

Paul Ellsworth

### Affiliation:

Tenable, Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
copy to the csv results a no QUOTE file, even setting the `with(QUOTE '"')`
```
D select * from things;
┌───────────┐
│   list    │
│ varchar[] │
├───────────┤
│ [kirk's]  │
└───────────┘
copy ( select * from things) to '/ki.csv';
copy ( select * from things) to '/ki2.csv' with(QUOTE '"');
```
all csv files have same content:
[kirk's]

**Comment by l1t1** [comment]
copy to the csv results a no QUOTE file, even setting the `with(QUOTE '"')`
```
D select * from things;
┌───────────┐
│   list    │
│ varchar[] │
├───────────┤
│ [kirk's]  │
└───────────┘
copy ( select * from things) to '/ki.csv';
copy ( select * from things) to '/ki2.csv' with(QUOTE '"');
```
all csv files have same content:
[kirk's]

**Comment by paulewog** [comment]
> copy to the csv results a no QUOTE file, even setting the `with(QUOTE '"')` [...]
The issue isn't generating the CSV; that works fine.  The issue is trying to load that CSV back into a table. :) (either manually or via EXPORT DATABASE and IMPORT DATABASE).

For now, I switched to exporting in parquet format.

**Comment by Mytherin** [comment]
Perhaps @LindsayWray could have a look at this?

**Comment by l1t1** [comment]
use `read_csv` also failed
```
D insert into things select * from read_csv('/things.csv',columns= {'list': ' VARCHAR[]'}, QUOTE= '"');
Error: Invalid Input Error: Type VARCHAR with value '[kirk's]' can't be cast to the destination type LIST at line 1 in column 0. Parser options: DELIMITER=',' (default), QUOTE='"', ESC
' (default), HEADER=0' (default), SAMPLE_SIZE=20480, IGNORE_ERRORS=0, ALL_VARCHAR=0
```
