### ISSUE TITLE
Update from other table not working

### ISSUE THREAD

**Issue by zerbfra** [duckdb/duckdb#5849]
### What happens?

I tried the existing documented example and it works correctly: https://duckdb.org/docs/sql/statements/update.html#update-from-other-table

Anyway, with my data and the following example, with `olda` and `newa` as the original table and `newa` the new table: 

`SELECT COUNT(*) FROM olda;` -> 92226
`SELECT COUNT(*) FROM newa;` -> 1657

```
UPDATE olda SET salesRank = newa.salesRank WHERE olda.asin = newa.asin;
Error: Binder Error: Referenced table "newa" not found!
Candidate tables: "olda"
LINE 1: ...ank = newa.salesRank WHERE olda.asin = newa.asin;
```

`asin` col is a `VARCHAR` and `salesRank` col is `INT`

### To Reproduce

UPDATE olda SET salesRank = newa.salesRank WHERE olda.asin = newa.asin;
Error: Binder Error: Referenced table "newa" not found!
Candidate tables: "olda"
LINE 1: ...ank = newa.salesRank WHERE olda.asin = newa.asin;

### OS:

MacOs

### DuckDB Version:

0.6.1

### DuckDB Client:

NodeJS + Shell

### Full Name:

Francesco Zerbinati

### Affiliation:

Indie developer

### Have you tried this on the latest `master` branch?

- [X] I agree - yes, tested also on master, same issue

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
You need to include the other table in the `FROM` clause:

```sql
UPDATE olda
SET salesRank = newa.salesRank
FROM newa
WHERE olda.asin = newa.asin;
```

**Comment by zerbfra** [comment]
Thanks, missed that!

**Comment by zerbfra** [comment]
Thanks, missed that!
