### ISSUE TITLE
Segmentation fault when creating a macro that references a function with the same name

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#5853]
### What happens?

When issuing a `CREATE MACRO` for a macro named identically to a function it uses, a segmentation fault occurs.

Is there a workaround?

### To Reproduce

```sh
cat <<EOF | build/debug/duckdb
CREATE MACRO "sum"(x) AS (CASE WHEN SUM(x) IS NULL THEN 0 ELSE SUM(x) END);
SELECT sum(1);
EOF
# [1]    14483 done                cat <<<'' |
#        14484 segmentation fault  build/debug/duckdb
```

### OS:

macOS aarch64

### DuckDB Version:

b056090a0cc009a55a9b3b9efdc4ef07235f2f13

### DuckDB Client:

duckdb

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #5856.

A work-around is to fully qualify the function call in the macro definition:

```sql
CREATE MACRO "sum"(x) AS (CASE WHEN system.main.SUM(x) IS NULL THEN 0 ELSE system.main.SUM(x) END);

```
