### ISSUE TITLE
Absolute paths in EXPORT DATABASE load.sql

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#5868]
### What happens?

If you `EXPORT DATABASE 'mypath' (FORMAT PARQUET);` the **absolute paths** to `mypath` are written in to `load.sql`.

This means you can't copy the exported files to another location and  `IMPORT DATABASE 'mypath'` because you'll get:
```
duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: IO Error: No files found that match the pattern "/original/path/table.parquet"
```

### To Reproduce

1. `EXPORT DATABASE 'test' (FORMAT PARQUET);`

1. Open `test/load.sql`

1. Observe full paths in `test` directory, e.g.: `/home/dave/backup/test/table.parquet`

1. Copy `test` to another location e.g. `test2`

1. `IMPORT DATABASE 'test2'`

1. Observe `IO Error`

### OS:

Ubuntu 20.04.5 LTS

### DuckDB Version:

v0.6.1-dev83 dfae126

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by davetapley** [comment]
Here's my workaround in Python:

To export:
```py
con.execute(f"EXPORT DATABASE '{path}' (FORMAT PARQUET);")

loadSqlPath = path / 'load.sql'
for line in fileinput.input(loadSqlPath, inplace=True):
    print(line.replace(str(path), 'ROOT'))
```

To import:
```py
loadSqlPath = path / 'load.sql'
for line in fileinput.input(loadSqlPath, inplace=True):
    print(line.replace('ROOT', str(path)))

con.execute(f"IMPORT DATABASE '{str(path)}';")
```

**Comment by Mytherin** [comment]
Thanks for the report!

The problem with writing relative paths is that the `IMPORT` then only works from the same relative directory, e.g. this would fail:

```sql
EXPORT DATABASE 'mydir' (FORMAT PARQUET);
cd ..
IMPORT DATABASE 'root/mydir';
```

We could make this a configuration option - or perhaps more cleanly would be to have the `IMPORT` modify the path automatically if it is different.

**Comment by Tishj** [comment]
Yea I think so too, all the files that get written when we do an export database will be local to that created folder
It's probably nicest to just have IMPORT figure out what path the relevant files are at, it should have enough context

**Comment by Tishj** [comment]
Hmm, since this is a pragma, all it does is directly interpret the schema.sql and load.sql files
Once the new query is finally bound the context that it came from a pragma is long forgotten.

So the easiest(hackiest) way to fix this is by doing a find and replace on the string representation.
Either just looking for `FROM '%s'` or prefixing all paths with something like `DUCKDB_RELATIVE_PATH_IDENTIFIER` so we can find and replace that with the path given to us at IMPORT
