### ISSUE TITLE
`INTERNAL Error: Logical column index 2 out of range` on query

### ISSUE THREAD

**Issue by sankalpgambhir** [duckdb/duckdb#5880]
### What happens?

On the following set of tables:

```sql
CREATE TABLE t0(c0 FLOAT4, c1 DOUBLE UNIQUE, PRIMARY KEY(c0));
CREATE TABLE t1(c0 INT4, c1 INT1 DEFAULT(0), c2 INT4);
CREATE VIEW v0(c0) AS SELECT 1 FROM t1, t0;
```

(regardless of whether there has been data added to the tables), on running the following query, an `INTERNAL Error` is raised, invalidating the database:

```sql
SELECT * 
    FROM v0, 
        t0 NATURAL LEFT JOIN t1 
        WHERE 
            (
                ((DATE '2023-01-10' 
                    BETWEEN 
                        0
                    AND 
                        (
                            CASE t0.c0 
                                -- WHEN 0 THEN t1.c0
                                -- WHEN 0 THEN t1.c1
                                WHEN 0 THEN t1.c2
                                END ))) 
                IS NULL);
```

```sql
-- output
 $ logs/ ../duckdb-bin/duckdb-0.6.1-919cad2                                                                                                                                                     v0.6.1 919cad22e8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .read ./error/database0.log
Error: near line 7: INTERNAL Error: Logical column index 2 out of range
```

As per the commented lines in the query, when the reference to `t1.c2` is replaced with a different column, the error does not show up, and an unimplemented type cast error is shown instead. The error persists even if the column types for `t1.c0` and `t1.c2` are changed.

The error has been tested on Python (pre), release 0.6.1 919cad2, release 0.5.1 7c11132 on Linux, and the online duckdb shell as of the day of posting.

### To Reproduce

1. Obtain the duckdb binary (0.6.1 919cad2) or other client.
2. Run the following query file:

```sql
CREATE TABLE t0(c0 FLOAT4, c1 DOUBLE UNIQUE, PRIMARY KEY(c0));
CREATE TABLE t1(c0 INT4, c1 INT1 DEFAULT(0), c2 DOUBLE);
CREATE VIEW v0(c0) AS SELECT 1 FROM t1, t0;

SELECT * 
    FROM v0, 
        t0 NATURAL LEFT JOIN t1 
        WHERE 
            (
                ((DATE '2023-01-10' 
                    BETWEEN 
                        0
                    AND 
                        (
                            CASE t0.c0 
                                -- WHEN 0 THEN t1.c0
                                -- WHEN 0 THEN t1.c1
                                WHEN 0 THEN t1.c2
                                END ))) 
                IS NULL);
```

### OS:

Linux

### DuckDB Version:

v0.6.1 919cad2 (latest release) / v 0.6.2 dev1040 pip

### DuckDB Client:

Linux CLI / Python

### Full Name:

Sankalp Gambhir

### Affiliation:

École Polytechnique Fédérale de Lausanne

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I remember an open issue related to BETWEEN that this reminds me of.
It was about BETWEEN behavior not being equivalent to the operations it's a shorthand for.

I wonder if this suffers from similar problems, first thought would be to rewrite the BETWEEN to the more verbose version

**Comment by sankalpgambhir** [comment]
> I remember an open issue related to BETWEEN that this reminds me of. It was about BETWEEN behavior not being equivalent to the operations it's a shorthand for.
> 
> I wonder if this suffers from similar problems, first thought would be to rewrite the BETWEEN to the more verbose version

Thanks for the suggestion @Tishj ! Here is the modified query, it does still seem to produce the error for me (binary release as well as python). And that helps in reducing it down to a single comparison, actually. I tried removing the `CASE` as well, to simply leave a reference to `t1.c2` but that doesn't cause an error. Removing the `NULL` check removes the error as well, but replacing it with another comparison (`IS NOT NULL`, `== 0`, `> 0`) still causes an error.

Quite interestingly, I noticed the error does not occur if I use a `NATURAL RIGHT JOIN` or a `NATURAL JOIN` ! 

```sql
CREATE TABLE t0(c0 FLOAT4, c1 DOUBLE UNIQUE, PRIMARY KEY(c0));
CREATE TABLE t1(c0 INT4, c1 INT1 DEFAULT(0), c2 DOUBLE);
CREATE VIEW v0(c0) AS SELECT 1 FROM t1, t0;

-- SELECT * 
--     FROM v0, 
--         t0 NATURAL LEFT JOIN t1 
--         WHERE 
--             (
--                 ((DATE '2023-01-10' 
--                     BETWEEN 
--                         0
--                     AND 
--                         (
--                             CASE t0.c0 
--                                 -- WHEN 0 THEN t1.c0
--                                 -- WHEN 0 THEN t1.c1
--                                 WHEN 0 THEN t1.c2
--                                 END ))) 
--                 IS NULL);
SELECT * 
    FROM v0, 
        t0 NATURAL LEFT JOIN t1 
        WHERE 
            (
                (
                    DATE '2023-01-10' <= (CASE t0.c0 WHEN 0 THEN t1.c2 END)
                ) 
            IS NULL
            );
```

Outputs for modified joins (line 23 is the query itself):
```sql
-- NATURAL LEFT JOIN (original)
Error: near line 23: INTERNAL Error: Logical column index 2 out of range

-- NATURAL RIGHT JOIN
Error: near line 23: Conversion Error: Unimplemented type for cast (DATE -> DOUBLE)

-- NATURAL JOIN
┌───────┬───────┬────────┬────────┐
│  c0   │  c0   │   c1   │   c2   │
│ int32 │ float │ double │ double │
├─────────────────────────────────┤
│             0 rows              │
└─────────────────────────────────┘
```

**Comment by Tishj** [comment]
Yea so it's definitely similar to that other issue
Like you discovered, the heart of the issue is that this just cant be cast, date -> double is not an existing conversion

The Internal error is thrown by the cardinality estimator though, for some reason.

Either way this would throw the Conversion error when we fix the internal error

**Comment by sankalpgambhir** [comment]
It would be fine if it threw a cast error, which it does if you change some of the column references. However, as you see from the test cases reported above, even for two column references of the same type (c0 and c2), only c2 raised the error. 

A type error would be okay, but the internal error is fatal and invalidates the db state.
