### ISSUE TITLE
INTERNAL Error while querying from Parquet

### ISSUE THREAD

**Issue by rsund** [duckdb/duckdb#5882]
### What happens?

While trying to query from the enclosed Parquet-file ([invalid.zip](https://github.com/duckdb/duckdb/files/10382907/invalid.zip)), DuckDB throws an `INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update`. This is obviously due to invalid unicode in the parquet-file, but I would have expected it to result in `Invalid Input Error: Invalid string encoding found in Parquet file: value "TREL\xC3" is not valid UTF8!` instead of INTERNAL Error leading to database invalidation and need for restarting database.

### To Reproduce

Unzip the [invalid.zip](https://github.com/duckdb/duckdb/files/10389803/invalid.zip) and execute query `SELECT * FROM 'invalid.parquet';`.

### OS:

Windows 10

### DuckDB Version:

0.6.1 latest master

### DuckDB Client:

R, but probably occurs in any client

### Full Name:

Reijo Sund

### Affiliation:

University of Eastern Finland

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Indeed it should not be INTERNAL

**Comment by ccfelius** [comment]
I want to work in this issue
