### ISSUE TITLE
Unclear error message if httpfs not installed

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#5886]
### What happens?

If a user tries to query a file over http without httpfs, the error message does not suggest that they install or load the extension. The error message seems to suggest that the file was not found (which is true!), but does not offer a good solution.

### To Reproduce

Many thanks to @RobinL!
https://gist.github.com/RobinL/7ee88b31a8f26739df0c7a5375a6518d

R version:
```R
library("DBI")
con = dbConnect(duckdb::duckdb(), ":memory:")
dbWriteTable(con, "iris", iris)
sql <- r"(SELECT * FROM read_parquet('https://raw.githubusercontent.com/RobinL/iris_parquet/main/iris.parquet'))
dbGetQuery(con, sql)   


Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT * FROM read_parquet('https://raw.githubusercontent.com/RobinL/iris_parquet/main/iris.parquet')
Error: IO Error: No files found that match the pattern "https://raw.githubusercontent.com/RobinL/iris_parquet/main/iris.parquet"

```

Python:
```python
import duckdb
con = duckdb.connect()
sql = """
SELECT * FROM read_parquet('https://raw.githubusercontent.com/RobinL/iris_parquet/main/iris.parquet')
"""
con.execute(sql).df()


IOException                               Traceback (most recent call last)
/tmp/ipykernel_60/3227792095.py in <module>
      1 import duckdb
      2 con = duckdb.connect()
----> 3 con.execute(sql).df()

IOException: IO Error: No files found that match the pattern "https://raw.githubusercontent.com/RobinL/iris_parquet/main/iris.parquet"
```

### OS:

Windows 10, Intel x64

### DuckDB Version:

0.6.1 and latest master

### DuckDB Client:

R, Python, others?

### Full Name:

Alex Monahan

### Affiliation:

Intel and DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
solved by @lverdoes in https://github.com/duckdb/duckdb/pull/6294
