### ISSUE TITLE
Client aborts on sqlite_scan attempt

### ISSUE THREAD

**Issue by uwegeercken** [duckdb/duckdb#5889]
### What happens?

In the duckdb client, when trying to call sqlite_scan with an existing sqlite database and table, the duckdb client aborts.

### To Reproduce

- start the client with a non exisitng database (so its empty and has no tables) or start the client without a database
- run: install sqllite; (first time only)
- run: load sqllite;
- run: select * from sqlite_scan('/home/user1/data/sqlite/test1.db','testtable1'); (an existing database and table)
- result: client aborts

### OS:

Fedora 37, 16GB Ram, 64 bit

### DuckDB Version:

0.6.1

### DuckDB Client:

console client

### Full Name:

Uwe Geercken

### Affiliation:

-

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

Unfortunately this issue is not actionable. Could you provide an example of how to create such a SQLite database or provide it as an attachment? Does it not work with any SQLite database?

**Comment by jorisvdstraten** [comment]
Looks like I've got the same kind of error here on MacOS Ventura 13.1 (M1):"Invalid Input Error: Initialization function "sqlite_scanner_init" from file "/Users/***/.duckdb/extensions/v0.6.1/osx_arm64/sqlite_scanner.duckdb_extension" threw an exception: "Catalog Error: Table Function with name "sqlite_scan" already exists!""

**Comment by Mytherin** [comment]
How are you loading the SQLite scanner extension? Could you provide a full reproducible example of how to trigger the issue?
