### ISSUE TITLE
json_group_array() does not respect filter clauses

### ISSUE THREAD

**Issue by brendanyounger** [duckdb/duckdb#5896]
### What happens?

Filter clauses do not seem to be applied to json_group_array().

### To Reproduce

I would expect this to return an empty array (or null):

```
D select json_group_array(generate_series) filter (where generate_series > 1) from generate_series(1, 1);
┌────────────────────────────────────────────────────────────────────────┐
│ json_group_array(generate_series) FILTER (WHERE (generate_series > 1)) │
│                                  json                                  │
├────────────────────────────────────────────────────────────────────────┤
│ [1]                                                                    │
└────────────────────────────────────────────────────────────────────────┘
```

It works correctly with list():

```
D select list(generate_series) filter (where generate_series > 1) from generate_series(1, 1);
┌────────────────────────────────────────────────────────────┐
│ list(generate_series) FILTER (WHERE (generate_series > 1)) │
│                          int64[]                           │
├────────────────────────────────────────────────────────────┤
│                                                            │
└────────────────────────────────────────────────────────────┘
```

and the current workaround seems to be:

```
D select to_json(list(generate_series) filter (where generate_series > 1)) from generate_series(1, 1);
┌─────────────────────────────────────────────────────────────────────┐
│ to_json(list(generate_series) FILTER (WHERE (generate_series > 1))) │
│                                json                                 │
├─────────────────────────────────────────────────────────────────────┤
│                                                                     │
└─────────────────────────────────────────────────────────────────────┘
```

### OS:

OS X, arm64

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

Brendan Younger

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
@lnkuiper could you perhaps have a look at this issue?

**Comment by lnkuiper** [comment]
Currently, `json_group_array` is implemented as a macro `to_json(list(x))`, so this does not work. For this to work, it should be reimplemented.

**Comment by Mytherin** [comment]
That makes sense - perhaps the problem here is then that the filter is silently ignored when an exception should be thrown instead that the filter clause is not supported for macros?

**Comment by lnkuiper** [comment]
The problem is not macro's specifically: the `FILTER` clause for aggregate functions is silently ignored for all scalar functions:
```sql
select string_split('aba', 'b') filter (where (range > 3)) ss from range(5);
┌───────────┐
│    ss     │
│ varchar[] │
├───────────┤
│ [a, a]    │
│ [a, a]    │
│ [a, a]    │
│ [a, a]    │
│ [a, a]    │
└───────────┘
```

Looking for a fix now
