### ISSUE TITLE
Query optimizer is exponential

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#5899]
### What happens?

EDIT: see my first comment—it's actually exponential in the number of joins!

The query optimizer takes time exponential in the "depth" of a set of chained CTEs, i.e., 

```sql
with stage0 as (
  select 1 as value
),
stage1 as (
  select a.*
  from stage0 a
  left join stage0 b on a.value = b.value
),
stage2 as (
  select a.*
  from stage1 a
  left join stage0 b on a.value = b.value
)
select * from stage2
```

On my computer it takes 0.29s to run a query with 18 stages, 0.58s to run a query with 19 stages, 1.12s to run a query with 20 stages, etc. (more numbers in the gist below). I don't expect chained CTEs to be especially fast, but I was hoping it would be a little bit harder to DOS duckdb!

(Yes, believe it or not this is a minimal test case extracted from an actual production workload!)

### To Reproduce

Here is a Ruby script that produces output chains similar to the sample query above:

https://gist.github.com/zenazn/a6e98f69d4b56592650c8777649d7a57

Included in that gist are the times it took for various chain lengths on my computer

### OS:

OSX, M1

### DuckDB Version:

0.6.1

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by zenazn** [comment]
Actually, it turns out CTEs were a bit of a red herring. DuckDB's query optimizer is actually exponential in the number of joins! Here's a query that takes 21.55s to run on my computer:

```sql
with data as (
  select 1 as value
)
select a.* from data a
left join data j1 on j1.value = a.value
left join data j2 on j2.value = a.value
left join data j3 on j3.value = a.value
left join data j4 on j4.value = a.value
left join data j5 on j5.value = a.value
left join data j6 on j6.value = a.value
left join data j7 on j7.value = a.value
left join data j8 on j8.value = a.value
left join data j9 on j9.value = a.value
left join data j10 on j10.value = a.value
left join data j11 on j11.value = a.value
left join data j12 on j12.value = a.value
left join data j13 on j13.value = a.value
left join data j14 on j14.value = a.value
left join data j15 on j15.value = a.value
left join data j16 on j16.value = a.value
left join data j17 on j17.value = a.value
left join data j18 on j18.value = a.value
left join data j19 on j19.value = a.value
left join data j20 on j20.value = a.value
left join data j21 on j21.value = a.value
left join data j22 on j22.value = a.value
left join data j23 on j23.value = a.value
left join data j24 on j24.value = a.value
```

FWIW, it takes a negligible amount of time in both postgres and sqlite.

**Comment by Mytherin** [comment]
Thanks for the report!

Have you verified that this is also the case in the latest master? This seems related to #5097 and #5630.

**Comment by zenazn** [comment]
Oh ho! Yup—looks like this is fixed in the latest master. Sorry for the duplicate report!

**Comment by zenazn** [comment]
@Mytherin fwiw, I'm seeing the current performance of the `left join` example as being roughly `x^2.6`:
- 0.05s for 50 joins
- 0.29s for 100 joins (5.8x base)
- 1.8s for 200 joins (36x base)
- 13.48s for 400 joins (269x base)

This is fine for my use cases for now, but let me know if you'd like me to file a separate ticket for this

``` ruby
#!/usr/bin/env ruby

stages=ARGV[0].to_i

puts <<EOF
with data as (select 1 as value)
select a.* from data a
EOF

stages.times do |i|
  puts <<EOF
left join data j#{i} on j#{i}.value = a.value
EOF
end
```
