### ISSUE TITLE
Pandas: Data type `float16` not recognized

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#5923]
Originally submitted by @marcdelabarrera, see #5922

> 
> duckdb can't create a table from a pandas dataframe if it contains a float16 column. It would be nice that float16 were parsed to float32 and avoid this error.
>  
> ```
> import pandas as pd
> import duckdb
> 
> df = pd.DataFrame({'col': [1,2,3]})
> df = df.astype({'col':'float16'})
> con = duckdb.connect()
> con.execute('CREATE TABLE tbl AS SELECT * FROM df')
> ```
> 
> ```
> Traceback (most recent call last):
>   File "c:\Users\MBBar\Downloads\example_duckdb.py", line 7, in <module>
>     con.execute('CREATE TABLE tbl AS SELECT * FROM df')
> duckdb.NotImplementedException: Not implemented Error: Data type 'float16' not recognized
> ```
> Changing the type to `float32` then it does not. In those cases, it would be nice that `duckdb` identified this issue and converted all `float16` columns into `float32` columns.

**Comment by Tishj** [comment]
Actually, this probably works as a "good first issue" I think

**Comment by wordhardqi** [comment]
does it mean that we cast the 'float16' column to 'float32' column when doing `VectorConversion::BindPandas`?

**Comment by leniartek** [comment]
@Mytherin I think this can be closed according to https://github.com/duckdb/duckdb/pull/6028

**Comment by Mytherin** [comment]
Indeed it can, thanks
