### ISSUE TITLE
Mem usage by con.execute over parquet files

### ISSUE THREAD

**Issue by a-agmon** [duckdb/duckdb#5925]
### What happens?

I'm trying to re-create the benchmark results reported at https://duckdb.org/2021/12/03/duck-arrow.html 
which shows the improved memory usage using arrow streaming with `fetch_record_batch()` .
Reading local parquet files it seems that the `execute` function uses much of the memory regardless of the fetch method. Does this mean that the execute reads the file as a whole to mem anyways?

![image](https://user-images.githubusercontent.com/54080741/213008657-b22554fb-4c52-4916-b3f3-5da5dfee10b6.png)

### To Reproduce

``` python
import duckdb
import pyarrow as pa
import pyarrow.dataset as ds
from pyarrow import RecordBatch
from memory_profiler import profile


s3_location = "*****/prq_data_sample/"


@profile
def get_dataset(location):
    dataset = ds.dataset(location)
    return dataset


@profile
def stream_table_ddb(location):
    dataset = get_dataset(location)
    con = duckdb.connect()
    query = con.execute("SELECT app_id, acc_id FROM dataset")
    record_batch_reader = query.fetch_record_batch()
    batch = record_batch_reader.read_next_batch()
    while len(batch) > 0:
        try:
            batch = record_batch_reader.read_next_batch()
        except StopIteration:
            break


@profile()
def get_direct(location):
    dataset = get_dataset(location)
    con = duckdb.connect()
    con.execute("SELECT app_id, acc_id  FROM dataset").fetch_arrow_table()



@profile()
def run():
    get_direct(s3_location)
    stream_table_ddb(s3_location)


if __name__ == '__main__':
    run()

```

### OS:

MACOSX

### DuckDB Version:

latest

### DuckDB Client:

Python

### Full Name:

Alon Agmon

### Affiliation:

Private

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

There is an open discussion on this issue here - #4941

Currently the results are always materialized as parallel streaming results are not yet supported - so we essentially need to choose between parallel execution or streaming results. We have some ideas on how to resolve that in the future.

**Comment by a-agmon** [comment]
Thanks, @Mytherin
I will keep an eye on this.
