### ISSUE TITLE
How to implement R semantics for arithmetics for relational?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#5928]
### What happens?

I can use a data frame with `NaN` values in duckdb, but when I try to perform arithmetics, a hard error is raised. Is there a way to implement R semantics that would gobble such errors?

In the example below, the error happens too late. Ideally, no error would happen.

I can work around by scanning the values for `NaN`, but this is less than ideal. Also, those values might occur from computations in duckdb.

### To Reproduce

``` r
library(duckdb)
#> Loading required package: DBI

df <- data.frame(x = NaN)
df
#>     x
#> 1 NaN

con <- dbConnect(duckdb())

rel <- duckdb:::rel_from_df(con, df)

ref <- duckdb:::expr_function("+", list(duckdb:::expr_reference("x"), duckdb:::expr_constant(1)))
exprs <- list(ref)

proj <- duckdb:::rel_project(rel, exprs)

duckdb:::rapi_rel_to_df(proj)
#> Error: Out of Range Error: Overflow in addition of double!
```

<sup>Created on 2023-01-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

7067a9ae3833b00b3ad8614ec3c8e8f0b8cfea4e

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
I think `NaN + 1` should also be `NaN`, like in R and Postgres for example

**Comment by Mytherin** [comment]
> I think `NaN + 1` should also be `NaN`, like in R and Postgres for example

I think that is a good ideal - currently we check for `NaN` in the result to detect overflows, but we could skip this test if either of the input is `NaN`.

This seems to be what Postgres does:

```sql
postgres=# select 1e308::float+1e308::float;
ERROR:  value out of range: overflow
postgres=# select 'NaN'::float+1e308::float;
 ?column? 
----------
      NaN
(1 row)

```

**Comment by Tmonster** [comment]
@krlmlr  should have a PR up for this next week. This week is bug fixing week

**Comment by krlmlr** [comment]
Still seeing the same behavior with recent-ish duckdb.

**Comment by krlmlr** [comment]
Hannes runs successfully with 544ca6d, I'll retry when I have a functioning system again.
