### ISSUE TITLE
DuckDB-wasm is always reading metadata for all fields in parquet

### ISSUE THREAD

**Issue by Marigold** [duckdb/duckdb#5931]
### What happens?

We have a 14400 x 1453 table in parquet format (~35mb) where every column has some **custom metadata**. Metadata alone adds ~5mb to the total size. Querying just a single column unnecessarily reads metadata of all fields. That means single-column queries that would use <1mb use >5mb now.

### To Reproduce

Files are public, you can use https://shell.duckdb.org/ to run queries below:

Query parquet file with metadata that uses ~6mb

```sql
select
    ag_agr_trac_no
from read_parquet('https://pub-68394b89698747f2ad3b205a2010b3e7.r2.dev/grapher/worldbank_wdi/2022-05-26/wdi/wdi_with_metadata.parquet')
where ag_agr_trac_no is not null limit 10;
```

the same parquet file **without metadata** uses <1mb

```sql
select
    ag_agr_trac_no
from read_parquet('https://pub-68394b89698747f2ad3b205a2010b3e7.r2.dev/grapher/worldbank_wdi/2022-05-26/wdi/wdi_without_metadata.parquet')
where ag_agr_trac_no is not null limit 10;
```

### OS:

browser

### DuckDB Version:

@duckdb/duckdb-wasm@1.20.1-dev34.0

### DuckDB Client:

duckdb-wasm

### Full Name:

Mojmir Vinkler

### Affiliation:

ourworldindata.org

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Where do you store your custom meta data? In the overall parquet metadata stored as thrift?

**Comment by hannes** [comment]
The first file has 5 893 699 Bytes of metadata in in. Due to the nature of Thrift it's impossible to partially read this. Is there any other parquet reader that is capable of this?

**Comment by Marigold** [comment]
Thanks @hannes. I'm not as familiar with other parquet readers, but I'd be surprised if this was possible. I was curious whether reading custom metadata is necessary given that SQL only returns data.

**Comment by hannes** [comment]
The thing is that we have to read the parquet metadata to figure out the schema and data layout of the parquet file. Otherwise, we cannot read it at all. So if you increase the metadata structure with custom stuff you are always going to be forced to read it even if you're not interested. I would advise to not blow up the metadata unnecessarily.
