### ISSUE TITLE
Confusing "column does not exist" error when using column named "document" with full text search

### ISSUE THREAD

**Issue by crclark** [duckdb/duckdb#5936]
### What happens?

```python
import pandas as pd
import duckdb

df = pd.DataFrame(
        {
            "document": ["hello world", "foobar"],
            "url": ["https://example.com", "https://google.com"],
        }
    )

db = duckdb.connect(database="/tmp/db3.duckdb")
db.execute("CREATE TABLE documents AS (SELECT document AS document, url AS url FROM df);")
db.execute("PRAGMA create_fts_index(documents, url, document);")
```

throws `CatalogException: Catalog Error: Table 'main.documents' does not have a column named '"document"'!`

Changing the name of the column to `doc` resolves the issue.

### To Reproduce

See above

### OS:

Linux x64

### DuckDB Version:

duckdb==0.6.1

### DuckDB Client:

Python

### Full Name:

Connor Clark

### Affiliation:

Shopify

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #5939. This was related to `document` being a keyword triggering different behavior in our parser.
