### ISSUE TITLE
In v0.6.1, C++ API can't use `::duckdb::Appender`

### ISSUE THREAD

**Issue by Shylock-Hg** [duckdb/duckdb#5941]
### What happens?

As shown:
```
➜  include git:(919cad22e8) rg 'appender.hpp'
duckdb/main/appender.hpp
4:// duckdb/main/appender.hpp

duckdb/main/capi/capi_internal.hpp
15:#include "duckdb/main/appender.hpp"

duckdb/common/arrow/arrow_appender.hpp
4:// duckdb/common/arrow/arrow_appender.hpp
```
`appender.hpp` isn't exposed to C++ API headers. Is it bug or deprecated? If deprecated, how can I do it now?

### To Reproduce

Using duckdb as library in C++, and just include `duckdb.hpp`.

### OS:

ubuntu, x64

### DuckDB Version:

v0.6.1

### DuckDB Client:

C++ API

### Full Name:

Shylock Hg

### Affiliation:

Vesoft Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

The Appender is still supported. It should indeed be included in `duckdb.hpp`.
