### ISSUE TITLE
ODBC: unsupported column type 0

### ISSUE THREAD

**Issue by niger-prequel** [duckdb/duckdb#5947]
### What happens?

Run a select data from a parquet file with the ODBC driver and get `unsupported column type 0`. The same query seems to work on OSX with the same file. `parquet_metadata()` seems to work fine on the file though with the ODBC driver. 

### To Reproduce

```sql
SELECT a, b, c, ... z FROM read_parquet('some_file.parquet')
```

There are no aliases or type annotations in the column expressions. Just selecting each column name.

### OS:

Debian

### DuckDB Version:

0.6.1

### DuckDB Client:

ODBC

### Full Name:

Niger Little-Poole

### Affiliation:

Prequel

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Would you be open to providing the parquet file for debugging purposes? You could email it to a member of the DuckDB labs team if the data can't be public

**Comment by niger-prequel** [comment]
[source_schema_buynlarge_prequel_transactions_ohrwd_snapshot_000000000000.parquet.zip](https://github.com/duckdb/duckdb/files/10467188/source_schema_buynlarge_prequel_transactions_ohrwd_snapshot_000000000000.parquet.zip)
It happens to be test data so its alright to share

**Comment by niger-prequel** [comment]
@Alex-Monahan I can confirm that the issue goes away if I remove the `Decimal` type column from the Parquet file.

**Comment by Mytherin** [comment]
Thanks for the report! This seems to be related to missing type support in the ODBC client.

**Comment by Mytherin** [comment]
@maiadegraaf can you double check if this is still an issue?
