### ISSUE TITLE
R crashes after installing and loading json extension under MS Windows

### ISSUE THREAD

**Issue by rfhb** [duckdb/duckdb#5956]
### What happens?

The `R` (version 4.2) session (in a terminal or in a GUI, e.g. RStudio) always crashes right after the command to load the `json` extension (SQL: `LOAD json;`) of `duckdb` under MS Windows (10 and 11). 

This happens if the extension had been installed with SQL `INSTALL json;` under MS Windows. 

It happens irrespective of the `duckdb` package having been installed from CRAN (`install.packages("duckdb")`) or as recommended on the `duckdb` website (`install.packages('duckdb', repos = c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))`) or from R Universe (`install.packages('duckdb', repos = c('https://duckdb.r-universe.dev')`), respectively. 

(The R Universe `duckdb` package has the `json` extension as BUILT-IN installed and loaded, and it works as expected, yet `R` still crashes when a user anyway tries to install and load the extension.)

Unfortunately I cannot debug / use gdb or similar under MS Windows to provide more information but the extension file seems the culprit. 

### To Reproduce

Under MS Windows (only, not macOS or Linux)

```
### example 1, R 4.2
unlink("~/../.duckdb", recursive = TRUE) # clean extensions folder
install.packages('duckdb') # version 0.6.2 as of 2023-01-21
library(duckdb)
drv <- duckdb()
con <- dbConnect(drv)
dbGetQuery(con, "SELECT * FROM duckdb_extensions();") # json not installed, not loaded
dbGetQuery(con, "SELECT json_valid('{\"a\": [\"b\"]}');") # returns error
dbExecute(con, 'INSTALL json;') # returns 0
dbExecute(con, 'LOAD json;') # R session aborts
```
```
### example 2, R4.2
unlink("~/../.duckdb", recursive = TRUE) # clean extensions folder
install.packages('duckdb', repos = c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))  # version 0.6.2 as of 2023-01-21
library(duckdb)
drv <- duckdb()
con <- dbConnect(drv)
dbGetQuery(con, "SELECT * FROM duckdb_extensions();") # json not installed, not loaded
dbGetQuery(con, "SELECT json_valid('{\"a\": [\"b\"]}');") # returns error
dbExecute(con, 'INSTALL json;') # returns 0
dbExecute(con, 'LOAD json;') # R session aborts
```

```
### example 3, R 4.2
unlink("~/../.duckdb", recursive = TRUE) # clean extensions folder
install.packages('duckdb', repos = 'https://duckdb.r-universe.dev') # version 0.6.0 as of 2023-01-21
library(duckdb)
drv <- duckdb()
con <- dbConnect(drv)
dbGetQuery(con, "SELECT * FROM duckdb_extensions();") # json installed and loaded, working
dbGetQuery(con, "SELECT json_valid('{\"a\": [\"b\"]}');") # returns TRUE
dbExecute(con, 'INSTALL json;') # returns 0
dbExecute(con, 'LOAD json;') # R session aborts
```

### OS:

MS Windows 10

### DuckDB Version:

0.6.2, 0.6.0

### DuckDB Client:

R

### Full Name:

Ralf HEROLD

### Affiliation:

Private

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
This seems related to #4792, perhaps @samansmink can have a look? It is likely related to R for Windows using MinGW instead of the regular Windows MSVC toolchain.

**Comment by Mytherin** [comment]
This should be fixed in the latest release
