### ISSUE TITLE
It is not clear if a Map can have duplicate keys

### ISSUE THREAD

**Issue by AlexR2D2** [duckdb/duckdb#5966]
### What happens?

The `map` docs [says](https://duckdb.org/docs/sql/data_types/map): `MAPs may also have duplicate keys.` 

But executing the prepared statement of query `select map([1, 1, 1], ['a', 'b', 'c']);` returns the error: `Invalid Input Error: Map keys have to be unique`. It happens then passings `allow_stream_result = false` flag into PreparedStatement->Execute method.

If you pass `allow_stream_result = true` flag into PreparedStatement->Execute method, then result of query is `empty`

### To Reproduce

1. Amalgamation C++ release.

2. Create prepared statement with query "select map([1, 1, 1], ['a', 'b', 'c']);"

3. Execute prepared statement with `allow_stream_result = false` flag.

4. Check the error of prepared statement

### OS:

macOS

### DuckDB Version:

2fd5e0d925

### DuckDB Client:

C++ Amalgation

### Full Name:

Alex

### Affiliation:

dev

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
To follow PrestoDB behavior, map keys have to be unique
The docs should be updated, thanks for letting us know :)

We will likely add a MultiMap type, which will allow duplicate keys (<https://github.com/duckdb/duckdb/issues/1466>)

**Comment by LindsayWray** [comment]
I've sent out a PR https://github.com/duckdb/duckdb-web/pull/512 to update the documentation regarding MAP type. Hopefully it will be more clear and accurate now!
