### ISSUE TITLE
Restore support for BUILD_ARROW_ABI_TEST

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb#5973]
### What happens?

Building duckdb while enabling BUILD_ARROW_ABI_TEST seems to fail at build time (seemingly independently of what other components are enabled).

Potentially once support is restored, it could be nice to have it tested by CI (at least say building while enabling everything).

### To Reproduce

```bash
mkdir buildArrow && cd buildArrow && cmake .. -DBUILD_ARROW_ABI_TEST=1 && make -j8
```
```bash
[ 99%] Completed 'arrow_ep'
[ 99%] Built target arrow_ep
[ 99%] Building CXX object test/arrow/CMakeFiles/test_arrow.dir/ub_test_arrow.cpp.o
[ 99%] Built target test_arrow
make[2]: *** No rule to make target `third_party/arrow/src/arrow_ep-build/zstd_ep-install/lib/libzstd.a', needed by `test/unittest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object test/CMakeFiles/unittest.dir/unittest.cpp.o
make[1]: *** [test/CMakeFiles/unittest.dir/all] Error 2
make: *** [all] Error 2
```

### OS:

MacOS, m1

### DuckDB Version:

v0.6.2-dev1339 09f803d3ad (current master)

### DuckDB Client:

- (build time problem)

### Full Name:

Carlo Piovesan

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
We used to build these in the past. I don't know if they are really that interesting anymore, perhaps we should just remove them. @pdet any thoughts?

**Comment by pdet** [comment]
I'm not sure when this was removed from the CI. I think the most interesting tests out there are the ones that round-trip all our parquet files, but these could be moved to the Python API.
