### ISSUE TITLE
Enums functionality fails when memory limit is low

### ISSUE THREAD

**Issue by Tmonster** [duckdb/duckdb#5983]
### What happens?

Converting a table with varchar columns to a table with enum columns increases the size of a duckdb database by more than double. The operation does not complete either. This happens when the size of the database is close to the memory limit of the duckdb persistent session.
### To Reproduce

```bash
./build/debug/duckdb mem_limit_enum.duckdb
```

```SQL
set memory_limit='2GB';
load tpch;
call dbgen(sf=2);
SELECT count(distinct(l_comment)) from lineitem;
CREATE TYPE l_comment_enum as ENUM(select l_comment from lineitem); # statement 1
CREATE TABLE lineitem2 (comment l_comment_enum); # statement 2
```
After statement 2, the creation of the table increases the size of the database by over 50%.
You can keep creating tables to show this
```
INSERT INTO lineitem2 (select l_comment from lineitem);
```
Observe as the size of mem_limit_enum.duckdb increases to over 5GB and the insert statement does not complete.

### OS:

MacOs Monterey

### DuckDB Version:

v0.6.2-dev1218

### DuckDB Client:

CLI

### Full Name:

Tom Ebergen

### Affiliation:

DuckDB labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
I suspect this has to do with the size of the enum and it being serialized in separate places. The `l_comment` enum must be at least 1GB by itself. I think exceeding the memory limit is not that much of a problem though - perhaps we should hard-limit enums to some reasonable value like 10MB of string data?

**Comment by pdet** [comment]
I agree with Mark that managing the memory of an ENUM can be challenging. 

Implementing a hard limit may prevent users from creating an ENUM, but perhaps we should consider making it a configurable option.

One potential solution for making ENUM memory management easier is to use an ART in place of an unordered map. However, this might have nasty consequences for the OG memory footprint. (:

**Comment by Tmonster** [comment]
So the specific case where this is causing issues for me is a enum type with 1000000 (1 mil) values in a table with 1,000,000,000 (1 billion) rows.

Each enum has a length of 3 - 8 characters. I'll see if I can reproduce an example using a tpch dataset

**Comment by Mytherin** [comment]
I wonder if we might be serializing types in too many places in general - which wouldn't be a problem for regular types but becomes a problem with larger enums.

**Comment by Tmonster** [comment]
@pdet Here are steps to reproduce where only 750,001 enums are created for a table that will have 11mil rows eventually. I also did not need to change my memory limit (16GB by default).

```
call dbgen(sf=2);
select distinct(l_orderkey/4) from lineitem; -- shows the amount of values we will have in our enum
create type orderkey_enum as enum (Select (l_orderkey/4)::VARCHAR from lineitem);
create table t2 (c1 orderkey_enum);
insert into t2 (select (l_orderkey/4)::VARCHAR from lineitem); -- this blows up the size of the database
```

**Comment by pdet** [comment]
I had a long go at this today. Unfortunately, I did not succeed in reproducing the issue on my machine.

I did ensure that nothing was being copied out of the enum type (by making all members private and explicitly deleting the copy constructor/assignment). I've also removed the many scans over the data in constructing the enum type from queries *, which is most likely unrelated to this issue*.

@Tmonster, maybe you can do a quick build and run of https://github.com/pdet/duckdb/tree/enum_test ? If that does not help, we can sit together tomorrow and have a go at this.

**Comment by Tmonster** [comment]
@pdet the issue isn't as bad now, but the size of the database still increases from 492M to 3.5GB as a result of running 

`insert into t2 (select (l_orderkey/4)::VARCHAR from lineitem); `

It seems to me there is still an issue.

**Comment by pdet** [comment]
Ah, sorry, I understood that the problem was a memory blow-up, I guess I mixed information from the meetings and this issue (:. Indeed, Mytherin analyzed this correctly. 

The issue with the disk blowup is that the type is reserialized on the catalog and at every column that defined the enum, we should probably serialize just the one in the catalog and properly consume it back from the catalog on a load. Will work on that tomorrow.

**Comment by Tmonster** [comment]
Would the type reserialization result in a 3GB expansion on disk when one enum column is populated? I would expect the size of the DB to increase according to the number of rows inserted, and 750001 rows in a one column table doesn't sound like 3GB, especially since tpch at sf=2 is only 500MB.

**Comment by Mytherin** [comment]
Figured out the issue - the `NumericStatistics` class serializes a `Value` as the `min/max`, which includes re-serializing the type. This causes the enum to be re-serialized for every row group.

There is still the issue of duplicating the enum for every column that uses it but that does not scale with the size of the data so that is less of an issue.
