### ISSUE TITLE
Date Functions

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#600]
We should consider adding support for common date manipulation operations:

- `DATE_ADD(part, count, date)`: Offset `date` by  `count` bins of type `part`. _Example:_ `DATE_ADD('month', 2, #2020-04-28#)` => `#2020-06-28#`.
- `DATE_DIFF(part, date1, date2)`: Count the number of bin boundaries of type `part` between `date1` and `date2`.  _Example:_ `DATE_DIFF('year', #2020-01-15#, #2019-12-05#)` => `1`.
- `DATE_SUB(part, date1, date2)`: Count the number of complete bins of type `part` between `date1` and `date2`. _Example:_ `DATE_SUB('year', #2020-01-15#, #2019-12-05#)` => `0`.
- `DATE_NAME(part, date)`: Return the text representation of the bin of type `part` for `date`. _Example:_ `DATE_NAME('month', #2020-04-28#)` => `'April'`.
- `DATE_PARSE(format, string)`: Convert `string` to a timestamp using `format`. 

Date arithmetic can also be implemented using `interval` types, but it could be helpful to have function implementations in the short term if the implementation of interval types is going to be some time.

We have a choice of parsing syntax here, including the [Postgres](https://www.postgresql.org/docs/11/functions-formatting.html#FUNCTIONS-FORMATTING-DATETIME-TABLE) and [ICU](http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax) formats. The Postgres format is more complete in some ways as it supports ordinal dates (e.g. `July 14th`), but it would require cloning or importing the [formatting code](https://doxygen.postgresql.org/formatting_8c_source.html#l04410). The ICU format is slightly more limited, but can support non-Gregorian calendars and we have already committed to using some parts of the the ICU library for collation, and discussions have started around using ICU Time Zone support, so we could get the functionality "for free".

Converting scalars to text via functions like `DATE_NAME` or the Postgres `to_str` is not usually a good idea as it can lead to performance degradation and non-portability of queries when employed by naïve users, but such functions have been traditionally provided by database systems since the 1970s (when the output of the query _was_ the report instead of just the data _for_ the report) so we probably need to support them.

**Comment by hawkfish** [comment]
These kinds of calendar-oriented functions are closely related to time zone support (see #561).

**Comment by Mytherin** [comment]
The `DATE_ADD`, `DATE_DIFF` and `DATE_SUB` functions seem reasonable to me but indeed have a lot of overlap with the interval type. Perhaps it is better to just implement the interval type, as I think that is not *too* much extra effort, and then implement those functions on top of the interval type implementation. 

For the date parsing it depends on how crucial we consider this; for now we plan on keeping ICU as an optional extension. If we use the ICU parser that means that you can only use the `DATE_PARSE` function if you have loaded the ICU extension. Depending on how "vital" we consider this function to be perhaps we want it to be part of the base library, but that then means we would need to take the PostgreSQL code.

**Comment by hawkfish** [comment]
`DATE_NAME` functionality has been implemented by the `MONTHNAME` and `DAYNAME` functions in #193.

**Comment by hawkfish** [comment]
`DATE_SUB` is probably the same as `AGE` but `DATE_DIFF` cannot be implemented with the `INTERVAL` type because temporal subtraction only produces `INTERVAL`s with `DAY` fields.

**Comment by hawkfish** [comment]
`DATEPARSE` has been implemented as `strptime`.

**Comment by hawkfish** [comment]
`DATE_ADD` is covered by `INTERVAL` addition.

**Comment by hawkfish** [comment]
`DATE_NAME` is covered by 'MONTHNAME` and `DAYNAME`.

**Comment by hawkfish** [comment]
`DATE_SUB(part, ldate, date)` maps to `DATE_PART(part, AGE(ldate, rdate))`

**Comment by hawkfish** [comment]
That just leaves [`DATE_DIFF`](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver15). It may be possible to implement this in terms of `DATE_TRUNC`.

**Comment by hawkfish** [comment]
`DATE_DIFF(part, ldate, rdate)` maps to `DATE_PART(part, AGE(DATE_TRUNC(part, ldate), DATE_TRUNC(part, rdate)))`

**Comment by phasath** [comment]
@hawkfish regarding the `DATE_DIFF`, that mapping doesn't work, as it will only return the months from the date generated on AGE, instead of the correct number of months. 

If AGE is something like 2 years and 5 months, it will only return 5 months instead of 29 months.

**Comment by hawkfish** [comment]
@phasath I think you are right. Intervals are lossy and we may need these to be implemented separately.

**Comment by phasath** [comment]
@hawkfish Sorry, I commented that but then I realized that the mapping you gave is a "path" but we would need to make some manipulation over it. 

`DATE_DIFF` would return those values directly for the part we want, either `years`, `months`, `days` and so on. To be able to do that using `DATE_PART` require some effort. 

So, I would say:

Part is Year:
`DATE_PART(year, AGE(DATE_TRUNC(year, ldate), DATE_TRUNC(year, rdate)))`

Part is Month:
`DATE_PART(year, AGE(DATE_TRUNC(year, ldate), DATE_TRUNC(year, rdate)))*12 + DATE_PART(part, AGE(DATE_TRUNC(part, ldate), DATE_TRUNC(part, rdate)))`

Path is Day requires more effort because it will depend on the months (28,29,30 or 31 days).

Also, note that you don't need to use `DATE_TRUNC` all times.

**Comment by hawkfish** [comment]
I'm trying to implement some of these as macros. Here is `DATEADD`:

```sql
CREATE MACRO DATEADD(datepart, number, dt) AS
CASE
	WHEN datepart IN ('year', 'yy', 'yyyy') THEN dt::DATETIME + INTERVAL (number) YEAR
	WHEN datepart IN ('quarter', 'qq', 'q') THEN dt::DATETIME + INTERVAL (number * 3) MONTH
	WHEN datepart IN ('month', 'mm', 'm') THEN dt::DATETIME + INTERVAL (number) MONTH
	WHEN datepart IN ('day', 'dd', 'd') THEN dt::DATETIME + INTERVAL (number) DAY
	WHEN datepart IN ('hour', 'hh') THEN dt::DATETIME + INTERVAL (number) HOUR
	WHEN datepart IN ('minute', 'mi', 'n') THEN dt::DATETIME + INTERVAL (number) MINUTE
	WHEN datepart IN ('second', 'ss', 's') THEN dt::DATETIME + INTERVAL (number) SECOND
	WHEN datepart IN ('millisecond', 'ms') THEN dt::DATETIME + INTERVAL (number) MILLISECOND
	WHEN datepart IN ('microsecond', 'mcs') THEN dt::DATETIME + INTERVAL (number) MICROSECOND
	WHEN datepart IN ('nanosecond') THEN dt::DATETIME + INTERVAL (number / 1000) MICROSECOND
	WHEN datepart IN ('week', 'wk', 'ww') THEN dt::DATETIME + INTERVAL (number * 7) DAY
	WHEN datepart IN ('dayofyear', 'dy', 'y') THEN dt::DATETIME + INTERVAL (number) DAY
	WHEN datepart IN ('weekday', 'dw', 'w') THEN dt::DATETIME + INTERVAL (number) DAY
ELSE dt
END
```

**Comment by Mytherin** [comment]
> I'm trying to implement some of these as macros. Here is `DATEADD`:
> 
> ```sql
> CREATE MACRO DATEADD(datepart, number, dt) AS
> CASE
> 	WHEN datepart IN ('year', 'yy', 'yyyy') THEN dt::DATETIME + INTERVAL (number) YEAR
> 	WHEN datepart IN ('quarter', 'qq', 'q') THEN dt::DATETIME + INTERVAL (number * 3) MONTH
> 	WHEN datepart IN ('month', 'mm', 'm') THEN dt::DATETIME + INTERVAL (number) MONTH
> 	WHEN datepart IN ('day', 'dd', 'd') THEN dt::DATETIME + INTERVAL (number) DAY
> 	WHEN datepart IN ('hour', 'hh') THEN dt::DATETIME + INTERVAL (number) HOUR
> 	WHEN datepart IN ('minute', 'mi', 'n') THEN dt::DATETIME + INTERVAL (number) MINUTE
> 	WHEN datepart IN ('second', 'ss', 's') THEN dt::DATETIME + INTERVAL (number) SECOND
> 	WHEN datepart IN ('millisecond', 'ms') THEN dt::DATETIME + INTERVAL (number) MILLISECOND
> 	WHEN datepart IN ('microsecond', 'mcs') THEN dt::DATETIME + INTERVAL (number) MICROSECOND
> 	WHEN datepart IN ('nanosecond') THEN dt::DATETIME + INTERVAL (number / 1000) MICROSECOND
> 	WHEN datepart IN ('week', 'wk', 'ww') THEN dt::DATETIME + INTERVAL (number * 7) DAY
> 	WHEN datepart IN ('dayofyear', 'dy', 'y') THEN dt::DATETIME + INTERVAL (number) DAY
> 	WHEN datepart IN ('weekday', 'dw', 'w') THEN dt::DATETIME + INTERVAL (number) DAY
> ELSE dt
> END
> ```

Cool stuff! You can add these to `src/catalog/default/default_functions.cpp`.

Perhaps it would simplify these macros if we made a `date_part_to_interval` function that uses our internal `TryGetDatePartSpecifier`? That would prevent us from duplicating the logic w.r.t. string -> datepart mapping.

**Comment by hawkfish** [comment]
That's a good call. I must admit I was just copying and pasting from the T-SQL documentation and didn't check to see if the part codes were compatible! I'm doing `DATEDIFF` now, so maybe we should wait until I've done them all and have a look at what we need.

**Comment by hawkfish** [comment]
Our `millisecond` and `microsecond` functions include the seconds, which is somewhat unobvious... 

```sql
# From https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver15
statement ok
CREATE MACRO DATEDIFF(datepart, startdate, enddate) AS
CASE
	WHEN datepart IN ('year', 'yy', 'yyyy')
	THEN YEAR(enddate::DATETIME) - YEAR(startdate::DATETIME)
	WHEN datepart IN ('quarter', 'qq', 'q')
	THEN (YEAR(enddate::DATETIME) * 4 + QUARTER(enddate::DATETIME)) -
	     (YEAR(startdate::DATETIME) * 4 + QUARTER(startdate::DATETIME))
	WHEN datepart IN ('month', 'mm', 'm')
	THEN (YEAR(enddate::DATETIME) * 12 + MONTH(enddate::DATETIME)) -
	     (YEAR(startdate::DATETIME) * 12 + MONTH(startdate::DATETIME))
	WHEN datepart IN ('day', 'dd', 'd', 'dayofyear', 'dy', 'y', 'weekday', 'dw', 'w')
	THEN EPOCH(enddate::DATETIME)::BIGINT / 86400 - EPOCH(startdate::DATETIME)::BIGINT / 86400
	WHEN datepart IN ('hour', 'hh')
	THEN EPOCH(enddate::DATETIME)::BIGINT / 3600 - EPOCH(startdate::DATETIME)::BIGINT / 3600
	WHEN datepart IN ('minute', 'mi', 'n')
	THEN EPOCH(enddate::DATETIME)::BIGINT / 60 - EPOCH(startdate::DATETIME)::BIGINT / 60
	WHEN datepart IN ('second', 'ss', 's')
	THEN EPOCH(enddate::DATETIME)::BIGINT - EPOCH(startdate::DATETIME)::BIGINT
	WHEN datepart IN ('millisecond', 'ms')
	THEN ((EPOCH(enddate::DATETIME) - second(enddate::DATETIME)) * 1000 + millisecond(enddate::DATETIME)) -
		 ((EPOCH(startdate::DATETIME) - second(startdate::DATETIME)) * 1000 + millisecond(startdate::DATETIME))
	WHEN datepart IN ('microsecond', 'mcs')
	THEN ((EPOCH(enddate::DATETIME) - second(enddate::DATETIME)) * 1000 * 1000 + microsecond(enddate::DATETIME)) -
	     ((EPOCH(startdate::DATETIME) - second(startdate::DATETIME)) * 1000 * 1000 + microsecond(startdate::DATETIME))
	WHEN datepart IN ('nanosecond')
	THEN ((EPOCH(enddate::DATETIME) - second(enddate::DATETIME)) * 1000 * 1000 + microsecond(enddate::DATETIME)) * 1000 -
	     ((EPOCH(startdate::DATETIME) - second(startdate::DATETIME)) * 1000 * 1000 + microsecond(startdate::DATETIME)) * 1000
	WHEN datepart IN ('week', 'wk', 'ww')
	THEN EPOCH(DATE_TRUNC('week', enddate::DATETIME + interval 1 day))::BIGINT / (7 * 86400) -
	     EPOCH(DATE_TRUNC('week', startdate::DATETIME + interval 1 day))::BIGINT / (7 * 86400)
	ELSE 0
END
```

**Comment by hawkfish** [comment]
It might make sense to use `MOD` to truncate instead of calling Yet Another Date Function.

While I like the idea of putting them in the catalog macros, they are pretty massive, and I was wondering if it made more sense to implement them directly?

**Comment by Mytherin** [comment]
Yes, if the functions are too big/complex perhaps implementing them normally would be a good idea. Up to you.

**Comment by hawkfish** [comment]
I think the big issue here is that `INTERVAL` uses multiple bins and does not round trip values. That is fine for addition, and the `DATEADD` macro is just syntactic sugar for `INTERVAL` addition. But the subtraction functions are different because they use a single bin/part. So if you use `Interval::GetDifference` with a day difference of more than 28 days, it gets turned into months, which is lossy.

**Comment by Mytherin** [comment]
Yes that is correct, perhaps it is better to implement this separately in C++ after all?

**Comment by hawkfish** [comment]
That's what I'm thinking. I can probably just hack up `DATE_PART`.

**Comment by hawkfish** [comment]
I think we have everything now.

**Comment by egor-ryashin** [comment]
`INTERVAL datediff(...) seconds` won't work, only `dateadd` can help here.

**Comment by egor-ryashin** [comment]
Actually, `INTERVAL (datediff(...)) seconds` works

**Comment by hawkfish** [comment]
Yes, you need to include `INTERVAL` expressions in parentheses.
