### ISSUE TITLE
Segmentation fault when joining a table with a list column and converting to arrow

### ISSUE THREAD

**Issue by vanpelt** [duckdb/duckdb#6004]
### What happens?

Consider the following query: `SELECT t1.i, struct_pack(c0 := t2.i, c1 := j) FROM t1 FULL OUTER JOIN t2 ON t1.i = t2.i`

Calling `.arrow()` seg faults but `.df()` does not.  If I tweak the total number of rows or the length of the array's in `j`. I can get past the seg fault.  If `j` is just a string instead of a list of strings the seg fault goes away.

### To Reproduce

```python
import pyarrow as pa
q = "SELECT t1.i, struct_pack(c0 := t2.i, c1 := j) FROM t1 FULL OUTER JOIN t2 ON t1.i = t2.i"
t1 = pa.Table.from_pydict(
    {
        "i": [i for i in range(5000)],
        "j": [["foo"] * 10 for i in range(5000)],
    }
)
t2 = pa.Table.from_pydict({"i": [i for i in range(5000)]})
db = duckdb.connect()
db.register("t1", t1)
db.register("t2", t2)
test = db.execute(q)
# seg fault
test.arrow()
# ok
test.df()
```

### OS:

aarch64

### DuckDB Version:

latest

### DuckDB Client:

0.6.1 / 0.6.2.dev1675

### Full Name:

Chris Van Pelt

### Affiliation:

Weights & Biases

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
This seems fixed as I can't reproduce it on master, please feel free to re-open if you still run into this issue on latest master.
