### ISSUE TITLE
Using INSERT with RETURNING doesn't insert rows in Python client

### ISSUE THREAD

**Issue by bhch** [duckdb/duckdb#6008]
### What happens?

When using `INSERT ... RETURNING ...` statement call, new rows are not created.

This only happens with the Python client. Doing this in CLI works as expected.

### To Reproduce

```python
import duckdb

con = duckdb.connect()

con.execute("CREATE TABLE items (id INT, name VARCHAR);")

print(con.execute("INSERT INTO items VALUES (1, 'One') RETURNING (id);").fetchone())
# -> (1,)
# value is returned correctly

print(con.execute("SELECT * from items;").fetchall())
# -> []
# but table is empty
```

### OS:

Linux AMD 64

### DuckDB Version:

0.6.1

### DuckDB Client:

Python (v3.8.5 and v3.10.8)

### Full Name:

Bharat Chauhan

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by bhch** [comment]
Interestingly, using `fetchall()` instead of `fetchone()` seems to work properly.

```diff
- print(con.execute("INSERT INTO items VALUES (1, 'One') RETURNING (id);").fetchone())
+ print(con.execute("INSERT INTO items VALUES (1, 'One') RETURNING (id);").fetchall())
# -> [(1,)]

print(con.execute("SELECT * from items;").fetchall())
# -> [(1, 'One',)]
# row was inserted
```

**Comment by cofin** [comment]
Any update on this?  I've also recently encountered this one.  For now, I've used the same `fetchall` workaround.

**Comment by Mause** [comment]
Looks like this might be more related to fully consuming the result than fetchone vs fetchall, as calling fetchone twice also works
