### ISSUE TITLE
Export/Import issue regarding parquet and ROW_GROUP_SIZE

### ISSUE THREAD

**Issue by BertTijhuis** [duckdb/duckdb#6027]
### What happens?

When try to export with the next command:

EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
the 
IMPORT is not working.

This is a very minor issue
I only want to point out this

See reproduce section:

### To Reproduce

> EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);

The import is not working

> import database 'target_directory';
Error: Not implemented Error: Unsupported option for COPY FROM parquet: ROW_GROUP_SIZE

A workaround is to edit the 'load.sql'  command and remove the ROW_GROUP_SIZE

### OS:

Ubuntu 22.04

### DuckDB Version:

0.61

### DuckDB Client:

duckdb client

### Full Name:

Bert Tijhuis

### Affiliation:

Private interest in this project

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by arjenpdevries** [comment]
I had the exact same problem trying to import my (exported) 0.7.2 database after updating to 0.8.0.
