### ISSUE TITLE
Tab completion works in a strange way in CLI

### ISSUE THREAD

**Issue by alexey-milovidov** [duckdb/duckdb#6030]
### What happens?

```
SELECT ca FROM read_parquet('output.parquet') LIMIT 1;
```

When my cursor is near "ca" and I'm pressing Tab, I get the following result:
```
SELECT ca FROM read_parquet('output.parquet') LIMIT INSERT
SELECT ca FROM read_parquet('output.parquet') LIMIT DELETE
SELECT ca FROM read_parquet('output.parquet') LIMIT UPDATE
```

which does not make any sense.

### To Reproduce

Download and run CLI, type the query above, press Tab.

### OS:

Ubuntu 22.04.

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

CLI

### Full Name:

Alexey Milovidov

### Affiliation:

ClickHouse

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by kimmolinna** [comment]
The problem seems to be that auto-complete doesn't recognize `1;` properly. Because `SELECT ca FROM read_parquet('output.parquet');` and tab over ca gives you `select ca FROM read_parquet('output.parquet');SELECT`

**Comment by alexey-milovidov** [comment]
Not stale.

**Comment by alexey-milovidov** [comment]
Not stale.

**Comment by Tishj** [comment]
I think it just doesn't take the cursor position into account

**Comment by alexey-milovidov** [comment]
?
