### ISSUE TITLE
Order-preserving joins in relational API

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#6054]
### What happens?

Joins in the relational API don't seem to be order-preserving by default, but should be.

### To Reproduce

``` r
con <- DBI::dbConnect(duckdb::duckdb())

DBI::dbExecute(con, "CREATE OR REPLACE MACRO eq(a, b) AS a = b")
#> [1] 0

left <- duckdb:::rel_from_df(con, data.frame(a = 1:3))
right <- duckdb:::rel_from_df(con, data.frame(a = 4:1, right_c = 5:8))
cond <- list(duckdb:::expr_function("eq", list(
  duckdb:::expr_reference("a", left),
  duckdb:::expr_reference("a", right)
)))
rel2 <- duckdb:::rel_join(left, right, cond, "inner")
duckdb:::rapi_rel_to_df(rel2)
#>   a a right_c
#> 1 3 3       6
#> 2 2 2       7
#> 3 1 1       8
```

<sup>Created on 2023-01-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

514ba34dec680bcf9de7b64a59e6354ae6ebacef

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Joins are explicitly not order preserving in DuckDB because preserving order enforces a specific join order (namely left-to-right). We could disable join re-ordering for the R integration when a join is materialized as an R DataFrame result but I don’t think we should enable this by default as it seriously restricts what optimizations can be performed.

**Comment by krlmlr** [comment]
Thanks. I don't argue we should enable it for all connections, just for the relational API.

**Comment by krlmlr** [comment]
On the client.
