### ISSUE TITLE
regexp_extract requires "as" before alias if the column name is "year"

### ISSUE THREAD

**Issue by ttomasz** [duckdb/duckdb#6059]
### What happens?

```sql
select upper('a') year; -- works
select upper('a') as year; -- works

select regexp_extract('a', '[a-z]') year; -- doesn't work
select regexp_extract('a', '[a-z]') as year; -- works

select upper('a') a; -- works
select upper('a') as a; -- works

select regexp_extract('a', '[a-z]') a; -- works
select regexp_extract('a', '[a-z]') as a; -- works
```
Tested in shell, dbeaver, and python prerelease package.

### To Reproduce

see above

### OS:

Linux

### DuckDB Version:

0.6.1

### DuckDB Client:

Shell, DBeaver, Python

### Full Name:

Tomasz Taraś

### Affiliation:

DXC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Year is a somewhat reserved keyword, because of https://duckdb.org/docs/sql/functions/interval

Likely there's no getting around this without causing parsing ambiguity, unless you quote `year`

**Comment by Mytherin** [comment]
This is indeed an expected limitation of the Postgres parser - Postgres itself runs into the same issue:

```sql
myth=# select upper('a') year;
ERROR:  syntax error at or near "year"
LINE 1: select upper('a') year;
                          ^

myth=# select upper('a') AS year;
 year 
------
 A
(1 row)
```

We might be able to fix this limitation if we rewrite the parser, but for now that is out of scope.

**Comment by ttomasz** [comment]
I would not have been surprised if it didn't work at all i.e. required double quotes always for `year`. What surprised me was that `as` changed whether this worked or not since in SQL `as` is pretty much an ornamental statement :smile:

If this is consistent with behaviour of Postgres then we can close this.
