### ISSUE TITLE
Correlated subquery does not error when there are multiple join partners

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#6060]
### What happens?

The following query works in DuckDB, but fails in Postgres. I expect this query to fail, because the subquery produces two join partners for the value `1`:

``` sql
select y, (select x from (values (1), (1), (2)) t(x) where x = y) from (values (1), (2), (3)) t(y);
```

In postgres, I get this error in particular:
```
Query 1 ERROR: ERROR:  more than one row returned by a subquery used as an expression
```

### To Reproduce

Run the query above in DuckDB (e.g., in the shell) and Postgres

### OS:

Apple Silicon OS X

### DuckDB Version:

0.6.2-dev*

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by zenazn** [comment]
Inspired by this discussion: https://github.com/duckdb/duckdb/discussions/6045

**Comment by Mytherin** [comment]
Thanks for the report! This is intended behavior to mimic what SQLite does - see https://github.com/duckdb/duckdb/issues/4113#issuecomment-1183057908. We could consider making throwing an error an option, however.

**Comment by zenazn** [comment]
Ah interesting! I'd be excited to have that option—sqlite's semantics here (and elsewhere!) have always been a little too loose for my preferences! (actually, this is a big reason why we originally migrated from sqlite to DuckDB in the first place!)
