### ISSUE TITLE
httpfs support for HTTP[S] proxy and custom SSL cert bundle

### ISSUE THREAD

**Issue by oxlade39** [duckdb/duckdb#6064]
### What happens?

_As suggested, moved from #5944_ 

I'm currently trying to use DuckDB in a corporate environment where our AWS access goes via an HTTP[s] proxy.
This means the proxy intercepts the HTTPS traffic and requires that we use a custom SSL certificate bundle.
In the case of tools such boto, it requires us setting the `AWS_CA_BUNDLE`.

There doesn't appear to be a way to configure the httpfs to support a custom CA bundle and I think it also might not honor the `HTTP_PROXY`, `HTTPS_PROXY` and `no_proxy` environment variables.

I will attach a notebook that demonstrates the error I see, which is:
```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[7], line 1
----> 1 result = con.execute("select * from 's3://fiaim-all-trp-dev-shared/portfolio/AIALPHAGGB|9888/2018-05-18/results.parquet'")

Error: Invalid Error: HTTP HEAD error on '[https://s3.amazonaws.com/fiaim-all-trp-dev-shared/portfolio/AIALPHAGGB|9888/2018-05-18/results.parquet](https://s3.amazonaws.com/fiaim-all-trp-dev-shared/portfolio/AIALPHAGGB%7C9888/2018-05-18/results.parquet)' (Error code 8)
```

### To Reproduce

- Install httpfs
- Behind a corporate firewall:
  - execute a `con.execute(f"select * from 's3://{bucket}/{key}'")`

### OS:

x64

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Dan Oxlade

### Affiliation:

N/A

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by JorgeGarciaIrazabal** [comment]
I think this is related to #3836

**Comment by oxlade39** [comment]
> I think this is related to #3836

I don't think so. Unless the code to download and install extensions is the same code as httpfs itself?

**Comment by JorgeGarciaIrazabal** [comment]
> > I think this is related to #3836
> 
> I don't think so. Unless the code to download and install extensions is the same code as httpfs itself?

yeah, maybe not exactly the same, but in both cases it doesn't honor the HTTP_PROXY, HTTPS_PROXY env vars.

**Comment by oxlade39** [comment]
I'd be willing to take a stab as fixing this if someone could give me a pointer. I think it might be a case of adding support for custom certificate bundles for the HTTPS connections made via httpfs. 

I had a very brief look at the httfs code but wasn't sure how this could be achieved.

**Comment by janjagusch** [comment]
@Mytherin, can we reopen this?

I'm having the same problem. I must access data from a self-hosted [Apache Ozone](https://ozone.apache.org/docs/1.0.0/interface/s3.html) instance with self-signed certificates via the S3 protocol. I can use Python's boto3 library to provide the trusted certificates through the `verify` argument.

The httpfs extension seems to be built around [cpp-httplib](https://github.com/yhirose/cpp-httplib). Looking at the [documentation](https://github.com/yhirose/cpp-httplib), it seems possible to speficy your own CA bundle:

``` 
// Use your CA bundle
cli.set_ca_cert_path("./ca-bundle.crt");
```

**Comment by janjagusch** [comment]
@Mause, could we add a new option to the `httpfs` extension called `http_ssl_ca_cert_path` (of type VARCHAR with default `''`) that, if not empty, calls `set_ca_cert_path(config.options.http_ssl_ca_cert_path)`? Unfortunately, I'm not proficient in C++. Otherwise, I'd do it myself.

**Comment by ilyanoskov** [comment]
bumping this, it's still very much needed

**Comment by janjagusch** [comment]
Just wanted to flag that this was a red hering for me. My actual problem turned out to be https://github.com/duckdb/duckdb/issues/9778.

**Comment by tmontes** [comment]
> However, so far, by the experiment with the Debian 12 container, it does seem that duckdb (or the httpfs extension?) do not validate the HTTP server's certificate against a list of trusted roots.
> 
> Can anyone confirm similar observations?

(adding to my question as kind of a reply)

This [very specific line](https://github.com/duckdb/duckdb/blob/2d0af03492ed9f5718e150af0b162599c731b534/extension/httpfs/httpfs.cpp#L190) in `httpfs.cpp` seems to indicate that no validation is in place (but I didn't even look at the rest of the code and -- important -- my C++ experience is way in the past nowadays...).

**Comment by keltia** [comment]
Up from here as well, I really really need HTTP proxy, preferably authenticated, support.  I can not use DuckDB otherwise as I will need  `httpfs`and the even more important `spatial` extensions.

**Comment by ilyanoskov** [comment]
@rj-atw @rjatwal @Mytherin 

(sorry for tagging you, I just saw that you are also working on MotherDuck).

Just want to highlight that this issue here is a major blocker for anyone working in a corporate environment behind a proxy. I think there is a much bigger chance someone would look at MotherDuck as a corporate customer if they got a chance to first try DuckDB with a working proxy. 

This issue is a complete non-starter for any corporate DuckDB user

**Comment by keltia** [comment]
Here I cheated by installing on my personal laptop and copying `$HOME/.duckdb/extensions` over but it is obviously a hack, not a solution.

**Comment by mrendi29** [comment]
+1 for needing duckDB to work with a proxy in  a corporate environment

**Comment by pvaezi** [comment]
My C++ is a bit rusty, but I'm trying to take a stab at this issue here: https://github.com/duckdb/duckdb/pull/10704

Please let me know of your feedback and comments. Hopefully it helps many corporate users to expand duckdb usage for those who are using their own custom certificates.

**Comment by nicornk** [comment]
+1 from my side as well. Also very helpful to intercept and debug the requests duckdb makes.

**Comment by ilyanoskov** [comment]
This issue is not stale, still very relevant 👍

**Comment by jgrg** [comment]
+1
When remote working I tunnel to my institute's HTTP proxy over `ssh` to access internal servers, and I just discovered that DuckDB can't use this mechanism.

**Comment by mghen** [comment]
I note that @Mause was working on a fix for the proxy aspect of this but ran into issues with the tests as described in #4741 and so they put that work aside. Sharing here in case someone who has the necessary know how to finish their work reads this thread.

**Comment by mghen** [comment]
Okay so [polars](https://docs.pola.rs/) to the rescue! The use of proxy environment variables is implemented within this package it would seem. So for those behind a proxy, here's a low-effort work-around that you can try that still keeps duckdb in the mix in case you want to be able to switch back later and remove the polars dependency when someone cleverer than me implements the proxy fix in duckdb.

Credit to @JohnMyers1 for coming up with this hack.

Assuming you have your `http_proxy` and `https_proxy` environment variables set and replace the _XXXXX_ values ...

```python
import polars as pl
import duckdb

source = "s3://XXXXX/*.parquet"

storage_options = {
    "aws_access_key_id": "XXXXX",
    "aws_secret_access_key": "XXXXX",
    "aws_session_token": "XXXXX",
    "aws_region": "XXXXX"
}

polars_scan = pl.scan_parquet(source, storage_options=storage_options).lazy()

con = duckdb.connect(':memory:')

df = con.execute("SELECT * FROM polars_scan;").df()

print(df)
```

May also be of interest to those watching #3836 and #4741
