### ISSUE TITLE
Parquet writer allows duplicate columns

### ISSUE THREAD

**Issue by ttomasz** [duckdb/duckdb#6067]
### What happens?

When writing to Parquet there is no error if there are duplicate column names.

This causes exception when Parquet file is read. It would be better if exception was thrown before writing the file instead of producing broken file.

### To Reproduce

```sql
COPY (SELECT 1 as a, 2 as a) TO '/tmp/duckdb-test/bad.parquet';
SELECT * FROM '/tmp/duckdb-test/bad.parquet';
```

### OS:

Linux

### DuckDB Version:

0.6.2-dev1770

### DuckDB Client:

Python

### Full Name:

Tomasz Taraś

### Affiliation:

DXC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I have written a fix for this, adding a postfix behind the duplicate column names:
```sql
require parquet

statement ok
COPY (SELECT 1 as a, 2 as a) TO '__TEST_DIR__/dupe_cols.parquet';

query II
SELECT a, a_1 FROM '__TEST_DIR__/dupe_cols.parquet';
----
1	2
```

**Comment by carlopi** [comment]
One problem of this approach of making up names is that things gets easily out of hand, say that `a_1` already exists at a subsequent place in the database.
One minor tweak to the algorithm could be first iterate to the column names populating the set, and on a second iteration settling on replacement names, but probably would be cleaner to at least log that the renaming has been done.

**Comment by Tishj** [comment]
I agree, but we don't have (or want) a "warning" system, as that also gets out of hand quickly.

Yea I thought about this, the original `a_1` would get renamed to `a_1_1` if it comes after the duplicate a
otherwise it's kept as `a_1` and the duplicate a would be named `a_2`.

Which I agree isn't consistent

**Comment by Mytherin** [comment]
We have existing logic for renaming columns when creating a table from a query with duplicate names - I suggest we re-use that method so we are at least internally consistent.

**Comment by Tishj** [comment]
@Mytherin Are you referring to
```c++
void ColumnList::AddToNameMap(ColumnDefinition &col) {
	if (allow_duplicate_names) {
		idx_t index = 1;
		string base_name = col.Name();
		while (name_map.find(col.Name()) != name_map.end()) {
			col.SetName(base_name + ":" + to_string(index++));
		}
	} else {
		if (name_map.find(col.Name()) != name_map.end()) {
			throw CatalogException("Column with name %s already exists!", col.Name());
		}
	}
	name_map[col.Name()] = col.Oid();
}
```
?
