### ISSUE TITLE
TestDuckDBJDBC::test_lots_of_decimals is broken

### ISSUE THREAD

**Issue by SuriZhang** [duckdb/duckdb#6073]
### What happens?

```
test_lots_of_decimals terminate called after throwing an instance of 'duckdb::InternalException'

  what():  INTERNAL Error: Assertion triggered in file "/home/anxing/Documents/duckdb/src/common/types.cpp" on line 964: width >= scale

Aborted (core dumped)
```
test_lots_of_decimals seems broken when i run `TestDuckDBJDBC` class. I assume core dumped is not the expected behaviour here, I did not touch any code, so I'm not sure what's happening here.

### To Reproduce

Build DuckDB: 
`DISABLE_SANITIZER=1 BUILD_JDBC=1 BUILD_JSON=1 make debug -I/usr/lib/jvm/java-8-openjdk-amd64/include`
`/usr/lib/jvm/java-8-openjdk-amd64/include` is my `JAVA_INCLUDE_DIR`

Run TestDuckDBJDBC:
 `java -cp build/debug/tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC`

### OS:

Ubuntu amd64

### DuckDB Version:

latest github code

### DuckDB Client:

JDBC

### Full Name:

Suri Zhang

### Affiliation:

National University of Singapore, School of Computing

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
The scale and width of the decimal that is attempted to be created is:
```
(lldb) p width
p (int) $0 = 3
(lldb) p scale 
(int) $1 = 4
```
These originate from
```c++
                jint precision = env->CallIntMethod(param, J_Decimal_precision);
                jint scale = env->CallIntMethod(param, J_Decimal_scale);
```
In `duckdb_java.cpp:490`

**Comment by Jens-H** [comment]
Java's BigDecimal allows precision < scale ("The precision is the number of digits in the unscaled value."). In DuckDB's decimal type we have WIDTH. They are not equal. I think your fix is therefore correct.

Looking at this I imagine that the scale could be a problem, too. BigDecimal may have negative values and DuckDB want's uint_8. Not sure how to handle this case - maybe throw an J_SQLException is the way to go here.

**Comment by SuriZhang** [comment]
> that the scale could be a problem, too. BigDecimal may have negative values and Duc

@Jens-H do you think this is a bug in the logic, or just the test setting?

**Comment by Tishj** [comment]
@Jens-H Thanks for investigating, the fix looked very dumb to me so I appreciate the validation 👍 
Also you make a good point, negative scale is not handled, looking at the docs, negative scale is equivalent to an exponent.
```
public int scale()
Returns the scale of this BigDecimal. If zero or positive, the scale is the number of digits to the right of the decimal point. If negative, the unscaled value of the number is multiplied by ten to the power of the negation of the scale. For example, a scale of -3 means the unscaled value is multiplied by 1000.
Returns:
the scale of this BigDecimal.
```
