### ISSUE TITLE
"Malformed JSON" error when directly concatenating multiple results of `->>`

### ISSUE THREAD

**Issue by jaypeedevlin** [duckdb/duckdb#6079]
### What happens?

When using the `-->` selector to extract strings from a JSON object, concatenating the results in a single operation, a malformed JSON error is returned.

### To Reproduce

```sql
with raw as (
select
    json('{"path": "/foo/bar/thumbnail", "extension": "png"}') as thumbnail
)

select
    thumbnail,
    thumbnail->>'$.path' as thumbnail_path,
    thumbnail->>'$.extension' as thumbnail_extension,
    thumbnail_path || '.' || thumbnail_extension as this_will_not_error,
    thumbnail->>'$.path' || '.' as this_will_also_not_error,
    thumbnail->>'$.path' || '.' || thumbnail->>'$.extension' as this_will_error
from raw
```

```
Invalid Input Error: malformed JSON
```

### OS:

MacOS

### DuckDB Version:

0.6.1

### DuckDB Client:

Python via dbt-duckdb

### Full Name:

Josh Devlin

### Affiliation:

Personal Project

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
The problem here is the order of operations. This works:
```sql
with raw as (
select
    json('{"path": "/foo/bar/thumbnail", "extension": "png"}') as thumbnail
)
select
    (thumbnail->>'$.path') || '.' || (thumbnail->>'$.extension') as this_will_error
from raw;
┌────────────────────────┐
│    this_will_error     │
│        varchar         │
├────────────────────────┤
│ /foo/bar/thumbnail.png │
└────────────────────────┘
```
I will check if I can fix this in the parser tomorrow.

**Comment by lnkuiper** [comment]
The minimal working example is this:
```sql
D select '.' || '{"path": "/foo/bar/thumbnail", "extension": "png"}'::JSON->>'path';
Error: Invalid Input Error: Malformed JSON at byte 0 of input: unexpected character.  Input: .{"path": "/foo/bar/thumbnail", "extension": "p...
```

Which also fails due to operator precedence in PostgreSQL:
```sql
postgres=# select '.' || '{"path": "/foo/bar/thumbnail", "extension": "png"}'::JSON->>'path';
ERROR:  operator does not exist: text ->> unknown
LINE 1: ...: "/foo/bar/thumbnail", "extension": "png"}'::JSON->>'path';
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

The error in Postgres is different because we allow implicit type casts between `VARCHAR` and `JSON`, but the cause of the error is the same.

I also tried SQLite, and it also fails:
```sql
sqlite> select '.' || '{"path": "/foo/bar/thumbnail", "extension": "png"}'->>'$.path';
Runtime error: malformed JSON
sqlite> with raw as (
select
    json('{"path": "/foo/bar/thumbnail", "extension": "png"}') as thumbnail
)
select
    thumbnail->>'$.path' || '.' || thumbnail->>'$.extension' as this_will_error
from raw;
Runtime error: malformed JSON
```

It would be possible to fix this by giving `->` and `->>` a higher operator precedence (they need to have the same precedence), but this breaks our list lambda functionality:
```sql
```
