### ISSUE TITLE
duckdb.Error: Invalid Error: IO Error: Unsupported Postgres type ltree

### ISSUE THREAD

**Issue by jerryheir** [duckdb/duckdb#6086]
### What happens?

 This throws an error `duckdb.Error: Invalid Error: IO Error: Unsupported Postgres type ltree`
 
 DuckDB - v0.6.1
 Python  - v3.9

### To Reproduce

```python
    conn = duckdb.connect(database=':memory:')

    conn.execute(f"""
    INSTALL postgres;
    LOAD postgres;
    CALL postgres_attach('host={db_host} dbname={db_name} user={db_user} password={db_pwd}');
    """)
 ```
 OR 
 
 If I use the postgres_scanner
 
 This throws an error `duckdb.Error: Invalid Error: IO Error: Unsupported Postgres type ltree`
 
 Seems like there is something I am not doing right.
 
 DuckDB - v0.6.1
 Python  - v3.9

### OS:

iOS

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Jerry Nwaeze

### Affiliation:

Affixdot

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! Please file issues related to the postgres extension in the [appropriate repository](https://github.com/duckdblabs/postgres_scanner), however.
