### ISSUE TITLE
update /ignore clause not supported

### ISSUE THREAD

**Issue by sunank200** [duckdb/duckdb#6087]
### What happens?

When i try to run this as per the example in https://duckdb.org/docs/sql/statements/insert.html#on-conflict-clause

```
-- insert the values (1), (2), (3) into "tbl"
INSERT INTO tbl VALUES (1), (2), (3);
-- insert the result of a query into a table
INSERT INTO tbl SELECT * FROM other_tbl;
-- insert values into the "i" column, inserting the default value into other columns
INSERT INTO tbl(i) VALUES (1), (2), (3);
-- explicitly insert the default value into a column
INSERT INTO tbl(i) VALUES (1), (DEFAULT), (3);
-- assuming tbl has a primary key/unique constraint, do nothing on conflict
INSERT OR IGNORE tbl(i) VALUES(1);
```

It throws the following error:
```
(duckdb.ParserException) Parser Error: ON CONFLICT IGNORE/UPDATE clauses are not supported
```

### To Reproduce

When i try to run this as per the example in https://duckdb.org/docs/sql/statements/insert.html#on-conflict-clause

```
-- insert the values (1), (2), (3) into "tbl"
INSERT INTO tbl VALUES (1), (2), (3);
-- insert the result of a query into a table
INSERT INTO tbl SELECT * FROM other_tbl;
-- insert values into the "i" column, inserting the default value into other columns
INSERT INTO tbl(i) VALUES (1), (2), (3);
-- explicitly insert the default value into a column
INSERT INTO tbl(i) VALUES (1), (DEFAULT), (3);
-- assuming tbl has a primary key/unique constraint, do nothing on conflict
INSERT OR IGNORE tbl(i) VALUES(1);
```

It throws the following error:
```
(duckdb.ParserException) Parser Error: ON CONFLICT IGNORE/UPDATE clauses are not supported
```

### OS:

mac OS

### DuckDB Version:

duckdb==0.6.1

### DuckDB Client:

duckdb==0.6.1

### Full Name:

Ankit Chaurasia

### Affiliation:

Astronomer

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This has been added since the last release, please try with the latest dev version


See https://github.com/duckdb/duckdb/pull/5866 for now info

**Comment by Mytherin** [comment]
As mentioned the documentation linked is for the development version. The on-conflict clause [is not supported in 0.6.1](https://duckdb.org/docs/archive/0.6.1/sql/statements/insert) - it will be part of the next release. I do notice however that the railroad diagrams are not versioned correctly - perhaps we should version those as well.

**Comment by sunank200** [comment]
Shouldn't these docs be called `development` rather than the current in that case? I went to that link directly as the website for the DuckDB home page takes to that. Users like myself would generally get confused.

**Comment by Mytherin** [comment]
Yes, that is fair. I have opened an issue for this in the web repo (duckdb/duckdb-web#523)
