### ISSUE TITLE
Memory overhead and slow startup with large files

### ISSUE THREAD

**Issue by nicku33** [duckdb/duckdb#6090]
### What happens?

After opening a large DuckDB 0.6.1 file (750GB, 1.8B rows, 200 columns) in python we noticed memory usage of 5.2 GB before any scans. This did not seem to count toward the `max_memory` usage, because once we started scanning data, the memory capped at the`max_memory` setting + 5.2GB.

It would also be nice to know the nature of this overhead as it grows with the file size on disk, but the inability to constrain memory usage is the bigger problem since it makes it always possible for the process to be killed by OOMKiller, kubernetes limits etc.

As well it can take a long time to open up a file. On a 750GB file, it's about 220 seconds. This seems to be one core spending most of its time in a CheckSum function with occasional bursts of I/O. 

### To Reproduce

The original 750GB file can be found [here](https://motherduck-demo.s3.amazonaws.com/gaia.ddb). However, if that's too big, you can also see the effect on a smaller file, say 130GB. I attached a script to generate similar data to the original. It takes about 80 min to generate on an EC2 core.

`python3 gen.py 200f_x_150M.ddb 200 150000000`

I couldn't figure out how to reproduce fully in SQL because setting max_memory doesn't carry through to new files after an `.open`. However you can pass in config with python, so I made the script `open.py` to demonstrate.  

The script opens a file with max_memory of 1GB set during the connect(), 
It then prints the output of `top` at that point. Note RES is 720MB at that point. 
Then we run a query and RES goes to 1.7GB. 
It appears the 720MB does not count toward the 1GB limit, but is just overhead. 
And not it takes about 22 seconds to open.

I also attached the SQL these scripts generate. The issue was first observed with the C++ client as well.

```

[ec2-user@ip-172-31-31-254 gen_big_data]$ python3 open.py 200f_x_150M.ddb big_table 1gb
PID: 5593
Press enter to continue
Opening 200f_x_150M.ddb size: 133031538688


Time taken: 22.55 (!!)
top - 16:36:40 up 5 days, 16:30,  1 user,  load average: 0.36, 0.13, 0.04
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 13040196+total,  1928060 free,  1049936 used, 12742397+buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12811400+avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5593 ec2-user  20   0 2681548 719612  34360 S   0.0  0.6   0:24.78 python3
                                 ^^^^
[('max_memory', '1.0GB', 'The maximum memory of the system (e.g. 1GB)', 'VARCHAR')]
Running a sum query over some of the columns
top - 16:36:42 up 5 days, 16:30,  1 user,  load average: 0.36, 0.13, 0.04
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie


%Cpu(s):  0.2 us,  0.0 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 13040196+total,   924368 free,  2053448 used, 12742416+buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12711052+avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5593 ec2-user  20   0 5815428   1.7g  35880 S   0.0  1.3   1:19.38 python3
                                 ^^^^
Time taken: 1.79
```
[repro_v1.zip](https://github.com/duckdb/duckdb/files/10580854/repro_v1.zip)
[repro_sql_v1.zip](https://github.com/duckdb/duckdb/files/10581076/repro_sql_v1.zip)

### OS:

 GNU/Linux x86_64

### DuckDB Version:

0.6.1

### DuckDB Client:

python

### Full Name:

Nicholas Ursa

### Affiliation:

Motherduck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by nicku33** [comment]
@hannes I think @bleskes mentioned this to you.

**Comment by Mytherin** [comment]
The start-up time issue should be entirely fixed now. PRs #5699 and #6560 have reduced start-up time in general, and lazy loading has been added with #6715 and #6841. In the current dev version table/column metadata is loaded when required, and loaded during query execution (so the load is interleaved with other threads processing data). Below are some timings on the generated dataset (124GB) of loading the database, running the query and shutting down, i.e. running the following command:

```bash
time duckdb giantdb.db -c "<query>"
```

```sql
|              col0              | col1  |
|--------------------------------|-------|
| SELECT 42                      | 0.04s |
| FROM big_table LIMIT 10        | 0.09s |
| SELECT COUNT(*) FROM big_table | 0.04s |
| SELECT MIN(f_0) FROM big_table | 0.16s |
```

**Comment by bleskes** [comment]
🎉 nice, @Mytherin . impressive!

Small question re:
>version table/column metadata is loaded when required

My understanding is that catalog metadata is loaded on open and that row groups stats/metadata are loaded lazily. Can you clarify wether the table entries (including top level stats and column type info) in the catalog are lazy loaded?

**Comment by Mytherin** [comment]
Yes, your understanding is correct. For our own storage/catalog all metadata, including table/column names, global table stats, etc is loaded eagerly **except** for row group/column data. The idea is that row group/column data grow with the data size, so it is important not to load them unless absolutely required. Table data, column data, etc do not grow with data size, and hence loading those eagerly is not a big problem.

Our pluggable catalog system does allow for lazy column loading, see e.g. the [SQLite catalog](https://github.com/duckdblabs/sqlite_scanner/blob/main/src/storage/sqlite_transaction.cpp#L50).

```cpp
CatalogEntry *SQLiteTransaction::GetCatalogEntry(const string &entry_name) {
	auto entry = catalog_entries.find(entry_name);
	if (entry != catalog_entries.end()) {
		return entry->second.get();
	}
	// catalog entry not found - look up table in main SQLite database
	auto type = db->GetEntryType(entry_name);
	if (type == CatalogType::INVALID) {
		// no table or view found
		return nullptr;
	}
        ...
}
```

What happens there is that we only load the table definition from the SQLite file when the actual table is requested by the user, and keep a cache of already loaded entries around (`catalog_entries`).
