### ISSUE TITLE
Unreserved keywords used as column names don't retain their casing

### ISSUE THREAD

**Issue by tekumara** [duckdb/duckdb#6092]
### What happens?

Unreserved keywords used as column names don't retain their casing and are automatically lower-cased.

### To Reproduce

`name` is an unreserved keyword:
```
D select * from duckdb_keywords() where keyword_name = 'name';
┌──────────────┬──────────────────┐
│ keyword_name │ keyword_category │
│   varchar    │     varchar      │
├──────────────┼──────────────────┤
│ name         │ unreserved       │
└──────────────┴──────────────────┘
```

When using `name` in a `create table` statement it is automatically lower-cased:
```
D CREATE TABLE people(Name VARCHAR, STATE VARCHAR, Country VARCHAR);
D .schema people
CREATE TABLE people("name" VARCHAR, "STATE" VARCHAR, "Country" VARCHAR);;
```

I was expecting `name` to keep its casing (like the other column names do) as per [this PR](https://github.com/duckdb/duckdb/pull/2919) and [these docs](https://duckdb.org/2022/05/04/friendlier-sql.html):
> DuckDB allows queries to be case insensitive, while maintaining the specified case as data flows into and out of the system.

### OS:

macos arm64

### DuckDB Version:

v0.6.0 2213f9c946

### DuckDB Client:

CLI

### Full Name:

Oliver Mannion

### Affiliation:

Xero

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #6112
