### ISSUE TITLE
import duckdb fails on freebsd

### ISSUE THREAD

**Issue by Huskers2020** [duckdb/duckdb#6093]
### What happens?

Importing duckdb fails with error message missing pyarrow.dataset module.

pip install dataset did not help.

============================================
Python 3.9.16 (main, Dec 18 2022, 01:15:32)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

-> In [1]: import duckdb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [1], line 1
----> 1 import duckdb

ImportError: Invalid Input Error: Required module 'pyarrow.dataset' failed to import

### To Reproduce

import duckdb 

### OS:

FreeBSD

### DuckDB Version:

0.6.1

### DuckDB Client:

python

### Full Name:

Huskers

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Odd that this would be required! Maybe `pip install pyarrow` would be a workaround for now?

**Comment by Mause** [comment]
Sounds like your copy of pyarrow doesn't include the optional dataset module, which is unfortunate. Depending on how you installed it, you may need to uninstall it and reinstall it after setting some environment variables

See here for more details: https://arrow.apache.org/docs/developers/python.html#build-and-test

**Comment by Huskers2020** [comment]
I installed pre-compiled package from FreeBSD repo. As this did not work I tried installing using PIP both did not work.

**Comment by Mytherin** [comment]
`pyarrow` should not be required for DuckDB - it seems like an oversight that this is getting non-optionally imported. @Tishj could you have a look?

**Comment by Mause** [comment]
I think it is optional already - the issue is that we expect pyarrow to always have the dataset module as well? While it's technically optional

**Comment by Tishj** [comment]
Yea I think Elliana is right
```c++
protected:
	bool IsRequired() const override final {
		return false;
	}
};
```
I believe I added support for making individual import cache items optional as well, so this should be relatively easy to fix.
Depending on how easing this requirement reflects on the rest of the code

**Comment by Huskers2020** [comment]
I'm not a savvy C developer or various OS are being dealt so for clarity - I presume pip install in FreeBSD should automatically bring in your recommendations.  Do I need to also raise this issue with the maintainers on FreeBSD side ?

**Comment by Tishj** [comment]
You could, but like Elliana said, the `dataset` module of pyarrow is optional, so the fault is definitely on our side.
We should only require it when you do a replacement scan (as showcased in the test I added in the linked PR) :)

**Comment by Huskers2020** [comment]
After trying other options uninstalled and re-installed pyarrow which pushed a new version and initiate its wheel build.

Re-installed duckdb (0.6) and it worked.
