### ISSUE TITLE
PostgreSQL array dimension detection fails for empty arrays

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [duckdb/duckdb#6103]
### What happens?

Hello DuckDB team,

I'm trying out queries from DuckDB CLI to a PostgreSQL database using the `POSTGRES_SCAN()` function.

The table I'm querying has a column that is an integer array (`INTEGER[]`) data type.

This column prevents `POSTGRES_SCAN()` from working when DuckDB CLI hits a row for which the integer array column is empty (not null).

I'm guessing that this is simply a question of handling empty arrays in this check: https://github.com/duckdblabs/postgres_scanner/blob/main/postgres_scanner.cpp#L783

### To Reproduce

In PostgreSQL:

```
CREATE TABLE
  duckdb_arr_test
  (
    id      INTEGER     NOT NULL,
    my_ints INTEGER[]   NOT NULL
  );

INSERT INTO
  duckdb_arr_test
  (
    id,
    my_ints
  )
VALUES
  (
    123,
    ARRAY[11, 22, 33]
  )
;
```

Then using the DuckDB CLI run:

```
INSTALL postgres;

LOAD postgres;

SELECT id, my_ints FROM POSTGRES_SCAN('', 'public', 'duckdb_arr_test');
```

This will work correctly and return the previously inserted row with id `123`.

Back in PostgreSQL, insert the problematic row:

```
INSERT INTO
  duckdb_arr_test
  (
    id,
    my_nums
  )
VALUES
  (
    234,
    ARRAY[]::INTEGER[]
  )
;
```

Followed by running the DuckDB query again:

```
SELECT id, my_ints FROM POSTGRES_SCAN('', 'public', 'duckdb_arr_test');
```

Which will throw the following error: **`Error: Invalid Error: Not implemented Error: Only one-dimensional Postgres arrays are supported`**.

### OS:

OSX ARM M1

### DuckDB Version:

N/A

### DuckDB Client:

DuckDB CLI v0.6.1

### Full Name:

Mickael van der Beek

### Affiliation:

Alliance Gravity

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Closing this here
