### ISSUE TITLE
export database - create macro after view

### ISSUE THREAD

**Issue by alessio-zamparelli** [duckdb/duckdb#6120]
### What happens?

export database generate the ddl of every macros after the views.
if a view use the macro the import command will not work.

Suggestion: order the ddl generation of macro before the view 

### To Reproduce

EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD);
IMPORT DATABASE 'target_directory';

### OS:

windows

### DuckDB Version:

6.1

### DuckDB Client:

dbeaver (JDBC)

### Full Name:

alessio

### Affiliation:

myself

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue, I don't think the steps you provided fully reproduce the issue though.
Could you please add extra steps to it?

**Comment by alessio-zamparelli** [comment]
surely

```sql
EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD);

--in the folder, file schema.sql
CREATE MACRO main.parse_ts (timestamp_text) AS (
  CASE
    WHEN ((main.trim (timestamp_text) IN ('--', ''))) THEN (NULL)
    ELSE CAST(((((((SUBSTR(timestamp_text, 7, 4) || '-') || SUBSTR(timestamp_text, 4, 2)
              ) || '-'
            ) || SUBSTR(timestamp_text, 1, 2)
          ) || ' '
        ) || SUBSTR(timestamp_text, 12, 8)
      ) AS TIMESTAMP
    )
  END
)

CREATE OR REPLACE VIEW
  v_p AS
    SELECT pp, parse_ts (opened_at) opened_at
    FROM my_p p;

IMPORT DATABASE 'target_directory';
```

**Comment by Tishj** [comment]
Thanks for the additional information, but I'm still not entirely following.

Without any prior steps, running export will not produce a `schema.sql` file that looks like what you described.
I'd appreciate a set of steps that produce the issue.

That being said, the issue is clear, the order of creation is not swapped. We already do something like this for foreign key relations, we should extend it to macros
