### ISSUE TITLE
Python Relational API - describe function statistics (dataframe / table)

### ISSUE THREAD

**Issue by earlev4** [duckdb/duckdb#6133]
### What happens?

Hi. **Huge thanks to the DuckDB creators and contributors!**

Not sure if this is an issue or intended behavior. **_Please forgive the issue report, if the behavior is intended or I am not using the function correctly._**

When working with a Python relation (i.e. `DuckDBPyRelation`) the `.describe` function provides no statistics if the relation is created from a `pandas dataframe`. However, if the relation is created from a `DuckDB table` the statistics are returned.

Reference:  
[https://duckdb.org/docs/api/python/reference/#duckdb.DuckDBPyRelation.describe](https://duckdb.org/docs/api/python/reference/#duckdb.DuckDBPyRelation.describe)

Tested on `0.6.1.` and `0.6.2.dev2085`.

Thanks so much!

### To Reproduce

To reproduce the issue:

```python
# Create pandas dataframe and a DuckDB connection
import pandas as pd
import duckdb

df = pd.DataFrame({"col1": [1, 2, 3], "col2": [4, 5, 6]})
con = duckdb.connect(database=':memory:')
```

```python
# Create a Python relation from the pandas dataframe
df_rel = con.from_df(df)
# Give basic statistics and if null exists for each column of the relation
df_rel.describe().df()
```

Results:  
stats(col1) | stats(col2)
-- | --
No statistics | No statistics

However, if the Python relation is created from a DuckDB table the statistics are returned as expected.

```python
con.execute("CREATE OR REPLACE TABLE my_table AS SELECT * FROM df;")
qry_rel = con.from_query("SELECT * FROM my_table;")
qry_rel.describe().df()
```

Results:  
stats(col1) | stats(col2)
-- | --
[Min: 1, Max: 3][Has Null: false, Has No Null:... | [Min: 4, Max: 6][Has Null: false, Has No Null:...  

Again, my apologies, if the behavior is intended or I am not using the function correctly.

Thanks again!

### OS:

Windows 11 x64

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Earle Lyons

### Affiliation:

Regis University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! No worries.

The statistics that are displayed there are the statistics derived from the metadata of the file (and the ones used for query planning). Pandas DataFrames do not keep track of statistics - and hence without reading the data we don't know the min/max of the DataFrame or the amount of NULL values.

I think the `describe` function as it is currently implemented is actually a bit confusing and should be replaced with a function more similar to what Pandas has (that does involve a scan of the data). @pdet any strong opinions?

**Comment by earlev4** [comment]
Hi @Mytherin! Thanks for the response and detailed information. I sincerely appreciate it.  

That makes sense about the statistics not being available from the Pandas DataFrame due to the lack of metadata available. I guess this partially ties back to my [discussion ](https://github.com/duckdb/duckdb/issues/2000#issuecomment-1402452322) with @pdet on [Issue #2000](https://github.com/duckdb/duckdb/issues/2000).  

I do not know if it is possible, but perhaps the statistics can be derived and calculated directly on the relation for a combined set of statistics? Pandas offers the following statistics on a DataFrame when using `df.describe(include='all')`:
`count`  
`unique`  
`top`  
`freq`  
`mean`  
`std`  
`min`  
`25%`  
`50%`  
`75%`  
`max`  

From the documentation and some testing I performed, the DuckDBPyRelation seems to have the following functions that could be leveraged.
`.count(col)` for `count`  
`.mean(col)` for `mean`  
`.std(col)` for `std` - Pandas std differs from DuckDB (e.g. 2.380476 versus 2.061553)  
`.min(col)` for `min`  
`.quantile('0.25', 'col')` for `25%` -Pandas 25% differs from DuckDB (e.g. 2.000000 versus 2)  
`.quantile('0.50', 'col')` for `50%` - Pandas 50% differs from DuckDB (e.g. 2.500000 versus 2)  
`.quantile('0.75', 'col')` for `75%` - Pandas 75% differs from DuckDB (e.g. 4.000000 versus 3)  
`.max(col)` for `max`  

Could these functions be combined to provide a comprehensive statistics report for all columns?

Perhaps, these could be leveraged too?  
`.aggregate("count(distinct col)")` for `unique`  
`.mode(col)` instead of `top`  
Not sure about `freq`  

Looking forward to your feedback and feedback from @pdet.

Thanks so much! I appreciate the help!

**Comment by pdet** [comment]
> Thanks for the report! No worries.
> 
> The statistics that are displayed there are the statistics derived from the metadata of the file (and the ones used for query planning). Pandas DataFrames do not keep track of statistics - and hence without reading the data we don't know the min/max of the DataFrame or the amount of NULL values.
> 
> I think the `describe` function as it is currently implemented is actually a bit confusing and should be replaced with a function more similar to what Pandas has (that does involve a scan of the data). @pdet any strong opinions?

I agree that the current describe function is confusing. I also agree we should mimic what pandas does, I guess if Pandas already scans the data to sum up it's aggregations users are probably already used to (maybe) the downside of actual query execution.

Thanks for doing the research there @earlev4. I think we can follow that path.

**Comment by Mytherin** [comment]
The differences in `quantile` are likely because of which type of quantile is used by default (discrete or continuous). DuckDB offers both `quantile` (discrete) and `quantile_cont` (contiguous). Pandas likely defaults to the other one.

**Comment by earlev4** [comment]
> The differences in `quantile` are likely because of which type of quantile is used by default (discrete or continuous). DuckDB offers both `quantile` (discrete) and `quantile_cont` (contiguous). Pandas likely defaults to the other one.

Thanks for the clarification, @Mytherin! That's helpful. I appreciate it.
