### ISSUE TITLE
table_info pragma does not work for pandas tables

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#6135]
### What happens?

I need to get the schema of a dataframe in DuckDB. `table_info` doesn't work for data frames. Neither does `DESCRIBE`.  

### To Reproduce

```python
df = pd.DataFrame({"foo": [1,2,3]})
duckdb.query("PRAGMA table_info('df')")
```

results in this error

```
---------------------------------------------------------------------------
CatalogException                          Traceback (most recent call last)
<ipython-input-54-f2f9e0281c2b> in <module>
      1 df = pd.DataFrame({"foo": [1,2,3]})
----> 2 duckdb.query("PRAGMA table_info('df')")

CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "pg_am"?
```

### OS:

macOS

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Dominik Moritz

### Affiliation:

CMU

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by domoritz** [comment]
Possibly related to #5799

**Comment by Tishj** [comment]
replacement scans are not done at this level, using `register` works though

```python
>>> import duckdb
>>> import pandas as pd
>>> df = pd.DataFrame({"foo": [1,2,3]})
>>> duckdb.register('df', df)
>>> duckdb.query("PRAGMA table_info('df')")
┌───────┬─────────┬─────────┬─────────┬────────────┬─────────┐
│  cid  │  name   │  type   │ notnull │ dflt_value │   pk    │
│ int32 │ varchar │ varchar │ boolean │  varchar   │ boolean │
├───────┼─────────┼─────────┼─────────┼────────────┼─────────┤
│     0 │ foo     │ BIGINT  │ false   │ NULL       │ false   │
└───────┴─────────┴─────────┴─────────┴────────────┴─────────┘
```

**Comment by domoritz** [comment]
It's an issue

**Comment by szarnyasg** [comment]
As @Tishj wrote this is happens because the Python API uses replacement scans, so it's expected that `table_info` will not work on them. It's recommended to use his workaround with `register`.
