### ISSUE TITLE
Segfault when running query with correlated subqueries

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#6136]
### What happens?

When running the queries below in the DuckDB shell, the DuckDB shell occasionally segfaults. I expect DuckDB to not segfault!

### To Reproduce

Setup—run this once in a DuckDB shell:
```sql
create table r as select * from values (1, 1, 'a', 'A'), (1, null, 'b', 'B'), (1, 2, 'c', 'C'), (2, null, 'd', 'D') t(ra, rb, x, y);
create table b as select * from values (1, 1, 1), (2, 1, 2), (3, 1, 3), (4, 1, null), (5, 2, 1), (6, 2, null), (7, 99, 99) t(id, ba, bb);
```

Repeatedly (for me, it happens on the 8th time; I have another query that seems to consistently error the second time it is run)—run this in the DuckDB shell:
```sql
select
  id,
  ba,
  bb,
  coalesce((select {'x': first(x), 'y': first(y), '__matches': count(*)} from r where ba = ra and bb = rb group by ra, rb), {'x': null, 'y': null, '__matches': 0}) as ref1,
  coalesce((select {'x': first(x), 'y': first(y), '__matches': count(*)} from r where ba = ra and (bb = rb or rb is null) group by ra, rb order by bb = rb), {'x': null, 'y': null, '__matches': 0}) as ref2,
  coalesce((select {'x': first(x), 'y': first(y), '__matches': count(*)} from r where (ba = ra or ra is null) and (bb = rb or rb is null) group by ra, rb order by ba = ra, bb = rb), {'x': null, 'y': null, '__matches': 0}) as ref3,
  coalesce((select {'x': first(x), 'y': first(y), '__matches': count(*)} from r where (ba = ra or ra is null) group by ra order by ba = ra), {'x': null, 'y': null, '__matches': 0}) as ref4,
from b;
```

### OS:

OS X, M1

### DuckDB Version:

0.6.1 and master (84fb676e)

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #6148

**Comment by kemiller** [comment]
I can write this up as a separate bug if that's what you think it is, but possibly related:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/6359/217596391-7466029b-b775-407c-90da-edffe4207c52.png">

Struct reference fails if the source of the struct was a subquery.

**Comment by Mytherin** [comment]
That's an unrelated bug and has already been addressed in the release, albeit by disallowing it explicitly:

```sql
D select (select {'x': 1, 'y': 2}) as ref1, ref1;
Error: Binder Error: Alias "ref1" referenced in a SELECT clause - but the expression has a subquery. This is not yet supported.
```
