### ISSUE TITLE
DESCRIBE in CLI should support autocompleting with table name

### ISSUE THREAD

**Issue by ryguyrg** [duckdb/duckdb#6182]
### What happens?

Autocomplete in the CLI doesn't autocomplete on table names when trying to do `DESCRIBE <tablename>`

### To Reproduce

I have a single table.

```
D SHOW TABLES;
┌─────────────────┐
│      name       │
│     varchar     │
├─────────────────┤
│ cloudfront_logs │
└─────────────────┘
```

In the CLI, autocomplete works for FROM clause.  ie, type `FROM cl<tab>` results in `FROM cloudfront_logs`.

However, when typing `DESCRIBE cl<tab>`, i get `DESCRIBE CALL/COPY/ALTER/CREATE` and other top-level commands instead of seeing table names.

### OS:

aarch64

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

Ryan Boyd

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks! I have pushed a fix in #6206
