### ISSUE TITLE
`CREATE INDEX` not persisted?

### ISSUE THREAD

**Issue by multimeric** [duckdb/duckdb#6185]
### What happens?

When I `CREATE INDEX` successfully, followed by closing the database, the index is not saved.

### To Reproduce

1. Open an existing database via CLI with `duckdb database.duckdb`
2. Create an index with `CREATE INDEX idx_column on table(column);`
3. Close the client using Ctrl+D
4. Re-open the database with `duckdb database.duckdb`
5. Verify that no indices are present using `.indices`

### OS:

Linux

### DuckDB Version:

v0.6.1 919cad22e8, also tried on v0.6.2-dev2303 f75b768

### DuckDB Client:

CLI

### Full Name:

Michael Milton

### Affiliation:

Walter and Eliza Hall Institute

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This is likely the same issue as #4891. If you run `CHECKPOINT` after the `CREATE INDEX` (or insert enough data so that a checkpoint will be run) the index should be persisted.

**Comment by multimeric** [comment]
Sounds like it! Thanks for the workaround as well.

**Comment by Mytherin** [comment]
No worries, thanks for the report :)
