### ISSUE TITLE
Header is ignored in CSV with one column

### ISSUE THREAD

**Issue by matuspavliscak** [duckdb/duckdb#6192]
### What happens?

I have this csv which only contains one column: [continents.csv](https://github.com/duckdb/duckdb/files/10706360/continents.csv)

When querying it using SQL, the header (first row) is ignored and replaced by column0. I would expect the first row of the first column to be interpreted as the header in this case.

![image](https://user-images.githubusercontent.com/9285430/218070293-2c625edd-c80e-4408-b396-a505bd2649eb.png)

### To Reproduce

File:  [continents.csv](https://github.com/duckdb/duckdb/files/10706360/continents.csv)

```
import duckdb
con = duckdb.connect()
con.execute("SELECT * FROM 'continents.csv'").df()
```

### OS:

Linux-5.4.209

### DuckDB Version:

master branch

### DuckDB Client:

Python

### Full Name:

Matus Pavliscak

### Affiliation:

Deepnote

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by matuspavliscak** [comment]
I found out that there is a possible workaround:
`SELECT * FROM read_csv_auto('continents.csv', header=True)`

In this case first row as header is accepted:

![image](https://user-images.githubusercontent.com/9285430/218078524-ade311f3-97ad-4a98-af8f-3b905955f073.png)

**Comment by Tishj** [comment]
I'm not really sure this qualifies as a bug, `select * from "continents.csv"` uses `read_csv_auto`, which will try to infer whether a header is supplied, sometimes it doesn't have enough context to determine if a header is provided or not, such as this case.

**Comment by Mytherin** [comment]
Indeed the auto-detection of a header row does not work if all columns in the file are strings.
