### ISSUE TITLE
Nodejs client: Import fails with "Cannot prepare multiple statements" 

### ISSUE THREAD

**Issue by Rohland** [duckdb/duckdb#6198]
### What happens?

Using the node client, exporting a database with multiple tables works fine. Importing it fails with:

>  Invalid Error: Cannot prepare multiple statements at once!

```javascript
{
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR'
}
```

### To Reproduce

**Current OS and Node Version**

OS: MacOS Ventura 13.2 (22D49)
Device: M1 Max
Node: v18.13.0

**Steps**

```javascript
import duckdb from 'duckdb';

async function getConnection(file) {
    console.log(`creating new connection for: ${ file }`);
    return new Promise((resolve, reject) => {
        const db = new duckdb.Database(file, duckdb.OPEN_READWRITE, () => {
            resolve(db);
        });
    });
}

async function timeAsync(block) {
    const start = process.hrtime();
    await block();
    const end = process.hrtime(start);
    const elapsedMs = (end[0] * 1000000000 + end[1]) / 1000000;
    return elapsedMs;
}

async function runQuery(connection, func, sql, args) {
    args ||= [];
    func = func.bind(connection);
    return new Promise((resolve, reject) => {
        func(sql, ...args, (err, res) => {
            if (err) {
                reject(err);
                return;
            }
            resolve(res);
        });
    });
}

async function executeQuery(con, query) {
    let data = null;
    let error = null;
    const time = await timeAsync(async () => {
        try {
            data = await runQuery(con, con.all, query);
        } catch (err) {
            error = err;
        }
    });
    if (error) {
        console.log(`query failed with error`, error);
        console.log(`query executed was: ${ query }\n`);
        return;
    }
    console.log(`query executed was: ${ query }\n`);
    console.log(`query executed in ${time}ms`, data);
}

const bugCon = await getConnection("bug.db");
await executeQuery(
    bugCon,
    'create table test (id int);'
);
await executeQuery(
    bugCon,
    'create table test2 (id int);'
);
await executeQuery(
    bugCon,
    "export database './tmp' (format csv, compression zstd)"
);
console.log("creating new database to import from");
const bug2Con = await getConnection("bug2.db");

// ---------------------------------
// 🐞🐞🐞🐞THIS SHOULD WORK BUT DOESN'T
// --------------------------------

await executeQuery(
    bug2Con,
    "import database './tmp'"
);
```

### OS:

MacOS

### DuckDB Version:

0.6.1

### DuckDB Client:

Node (18.13.0)

### Full Name:

Rohland de Charmoy

### Affiliation:

Codeo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Can you provide the resulting `load.sql` and `schema.sql` files produced at `EXPORT`?

**Comment by Rohland** [comment]
@Tishj 

load.sql

```sql
COPY test2 FROM './tmp/test_.csv' (FORMAT 'csv', delimiter ',', header 0, quote '"', compression 'zstd');
COPY test FROM './tmp/test.csv' (FORMAT 'csv', delimiter ',', header 0, quote '"', compression 'zstd');
```
schema.sql

```sql
CREATE TABLE test2(id INTEGER);
CREATE TABLE test(id INTEGER);
```

**Comment by Tishj** [comment]
are there any other files in that folder?
`test_.csv` and `test.csv` should be the only other ones
(Though I think those also shouldn't be present, as we did not populate the table at all)

**Comment by Rohland** [comment]
@Tishj - yeah, there are two files (attached)

[test_.csv](https://github.com/duckdb/duckdb/files/10712956/test_.csv)
[test.csv](https://github.com/duckdb/duckdb/files/10712957/test.csv)

They are the only two files in the folder: 

<img width="433" alt="Screenshot_WebStorm_20230211_102729@2x" src="https://user-images.githubusercontent.com/231471/218248390-26058aa8-8ad2-43c5-811c-46bd0745daf0.png">

**Comment by Tishj** [comment]
I'm looking into this now, and this error is thrown when ClientContext::Prepare is called with a string containing multiple queries.

I'm still not sure how that happens here, as your example looks correct

**Comment by Tishj** [comment]
Ah the bug is starting to make sense (but it is definitely a bug)

In Prepare we call ParseStatementsInternal, which resolves pragmas
`import` is a pragma, and resolves to an amalgamation of all the queries contained in the folder.

And as stated above, Prepare throws an error when the query to prepare contains multiple statements, which it does.
```
(lldb) p statements[2]->ToString()
(std::string) $2 = "COPY test FROM './tmp/test.csv' ( FORMAT csv, delimiter \",\", header 0, quote \"\"\"\", compression zstd )"
(lldb) p statements[3]->ToString()
(std::string) $3 = "COPY test2 FROM './tmp/test_.csv' ( FORMAT csv, delimiter \",\", header 0, quote \"\"\"\", compression zstd )"
```

Likely we should change the `Statement` class in `duckdb_node.hpp` from containing a single `unique_ptr<PreparedStatement>` into a vector of them, and then call ExtractStatements, Prepare'ing them separately afterwards.
