### ISSUE TITLE
DBeaver (JDBC) unable to view tables/views metadata

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#6247]
### What happens?

When using DBeaver (with the JDBC driver), trying to view table or view metadata in the "Database Navigator" side panel is not working. Interestingly, the "procedures" works correctly, but not the tables or views. The error message is:

```
SQL Error: Actual catalog argument is not supported, got memory
  Actual catalog argument is not supported, got memory
```

I updated DBeaver to the latest and updated the DuckDB driver to 0.7.0 and still encountered the error. Another user reported the issue as well on both a physical file and an in memory DB. 

### To Reproduce

Open DBeaver, create a new DuckDB connection (with the updated 0.7.0 driver), then try to access the Database Navigator tree menu in the "tables" or "views" sections.

![image](https://user-images.githubusercontent.com/52226177/218510160-f4b34212-308a-40fa-ab0a-7f1b6ad8be39.png)

### OS:

Windows 10

### DuckDB Version:

0.7.0

### DuckDB Client:

JDBC

### Full Name:

Alex Monahan

### Affiliation:

Intel and DuckDB

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
This likely related to the multi-database support - the catalog is now no longer empty/NULL: https://github.com/duckdb/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java#L676

**Comment by rpbouman** [comment]
There is a PR for this. https://github.com/duckdb/duckdb/pull/6230

**Comment by Mause** [comment]
Fixed by #6230

**Comment by alexboks** [comment]
On  v0.7.1-dev273 the error message is gone and I can see tables, but not views

**Comment by rpbouman** [comment]
I think that might be related to a separate issue (which is not related to the driver but to the information schema) https://github.com/duckdb/duckdb/issues/6235
