### ISSUE TITLE
Core dump on Linux running concurrent SELECT queries

### ISSUE THREAD

**Issue by massung** [duckdb/duckdb#6248]
### What happens?

Core dump.

### To Reproduce

Using the Python API, the following code core dumps:

```python
def select_query(conn, params):
    return conn.execute("SELECT * FROM table WHERE x=?", params).fetchall()

conn = duckdb.connect(db_filename, read_only=True)
executor = concurrent.futures.ThreadPoolExecutor(max_workers=5)
jobs = []

for params in xs:
    job = executor.submit(select_query, conn.cursor(), params)
    jobs.append(job)

results = [row for job in jobs for row in job.result()]
```

Changing the executor to `max_workers=1` the program runs just fine. The above program also works fine with `max_workers >= 2` on MacOS.

### OS:

Linux

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Jeffrey Massung

### Affiliation:

Prometheus Biosciences

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have not managed to get it to crash using a separate cursor per connection - but I can confirm it crashes when using the same connection over multiple threads:

### Data Load
```py
import duckdb
con = duckdb.connect('test.db')
con.execute("create or replace table tbl as select x from range(1000000) t(x)")
```
### Execution
```py
import duckdb
import concurrent
import concurrent.futures
db_filename = 'test.db'

def select_query(conn, params):
    return conn.execute("SELECT * FROM tbl WHERE x=?", params).fetchall()

conn = duckdb.connect(db_filename, read_only=True)
executor = concurrent.futures.ThreadPoolExecutor(max_workers=10)
jobs = []

xs = [(2500 * x,) for x in range(10)]

for params in xs:
    job = executor.submit(select_query, conn, params)
    jobs.append(job)

results = [row for job in jobs for row in job.result()]
print(results)
```

**Comment by massung** [comment]
In the version that works for you, how are you creating the cursor? If I pass it to `submit` (my example) it core dumps. But is also crashes if I create it before submitting or if I create it in the thread:

```python
# in params loop
cursor = conn.cursor()
job = executor.submit(query, cursor, params)
```

or

```python
def query(conn, params):
    cursor = conn.cursor()
    cursor.execute(...)
    return cursor.fetchall()
```

Not sure if the query makes a difference or the size of the database. My database is ~7 GB in size and the actual query looks like:

```sql
select * from variants where chrom=? and pos between ? and ?
```

If there's something more I can do to help here (or if I'm doing something wrong) let me know.

**Comment by Mytherin** [comment]
Thanks - I think the query was indeed important. This makes it crash:

### Data Load
```py
import duckdb
con = duckdb.connect('test.db')
con.execute("create or replace table tbl as select repeat('A', 10) AS chrom, 1 AS pos")
```

### Execution
```py
import duckdb
import concurrent
import concurrent.futures
db_filename = 'test.db'

def select_query(conn, params):
    return conn.execute("select * from tbl where chrom=? and pos between ? and ?", params).fetchall()

conn = duckdb.connect(db_filename, read_only=True)
executor = concurrent.futures.ThreadPoolExecutor(max_workers=5)
jobs = []

xs = [('A' * 10, 2500 * x, 2500 * (x + 1)) for x in range(10)]

for params in xs:
    job = executor.submit(select_query, conn.cursor(), params)
    jobs.append(job)

results = [row for job in jobs for row in job.result()]
print(results)
```

**Comment by Tishj** [comment]
I can no longer reproduce this, feel free to make a new issue with a clear reproduction.

This issue is kind of muddied by the various variations in the thread, which makes it very unclear what we're discussing here 👍
