### ISSUE TITLE
install sqlite3 extension fail

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#6257]
### What happens?

I want to try the new feature (https://github.com/duckdb/duckdb/pull/5764) to atttach a sqlite3 db file.
and following the steps in the document.
it reports  IO Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/v0.7.0/windows_amd64/sqlite_scanner.duckdb_extensi
on.gz"

### To Reproduce

```
D:\duckdb>duckdb070
v0.7.0 f7827396d7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE);
Error: IO Error: Extension "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\SQLITE.duckdb_extension" not found.

Candidate extensions: "sqlite", "sqlite3", "sqlite_scanner", "s3", "icu"
D install sqlite3
> ;
Error: IO Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/v0.7.0/windows_amd64/sqlite_scanner.duckdb_extensi
on.gz"
Extension "sqlite_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```

### OS:

windows7

### DuckDB Version:

0.7.0

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
but I can use wget to download 
wget http://extensions.duckdb.org/v0.7.0/windows_amd64/sqlite_scanner.duckdb_extension.gz
isn't duckdb support proxy server?

**Comment by l1t1** [comment]
if i gunzip the gz file to C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\, load sqlite no error reports, load sqlite3 reports error
```
D:\duckdb>duckdb070
v0.7.0 f7827396d7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D load sqlite
> ;
D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE);
Error: IO Error: Extension "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\SQLITE.duckdb_extension" not found.

Candidate extensions: "sqlite", "sqlite3", "sqlite_scanner", "s3", "icu"
D load sqlite;
D load sqlite3;
Error: Invalid Input Error: Initialization function "sqlite_scanner_init" from file "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\sqlite_scanne
r.duckdb_extension" threw an exception: "Catalog Error: Table Function with name "sqlite_scan" already exists!"
```

**Comment by l1t1** [comment]
I try do as https://github.com/duckdblabs/sqlite_scanner said,
also failed
```
D load 'C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\sqlite_scanner.duckdb_extension';
Error: Invalid Input Error: Initialization function "sqlite_scanner_init" from file "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\sqlite_scanne
r.duckdb_extension" threw an exception: "Catalog Error: Table Function with name "sqlite_scan" already exists!"
```

**Comment by Mause** [comment]
> but I can use wget to download wget http://extensions.duckdb.org/v0.7.0/windows_amd64/sqlite_scanner.duckdb_extension.gz isn't duckdb support proxy server?

DuckDB doesn't have support for proxies no

**Comment by Mause** [comment]
> if i gunzip the gz file to C:\Users\LD.duckdb\extensions\v0.7.0\windows_amd64, load sqlite no error reports, load sqlite3 reports error
> 
> ```
> D:\duckdb>duckdb070
> v0.7.0 f7827396d7
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D load sqlite
> > ;
> D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE);
> Error: IO Error: Extension "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\SQLITE.duckdb_extension" not found.
> 
> Candidate extensions: "sqlite", "sqlite3", "sqlite_scanner", "s3", "icu"
> D load sqlite;
> D load sqlite3;
> Error: Invalid Input Error: Initialization function "sqlite_scanner_init" from file "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\sqlite_scanne
> r.duckdb_extension" threw an exception: "Catalog Error: Table Function with name "sqlite_scan" already exists!"
> ```

Does it work if you don't load the extension first?

**Comment by l1t1** [comment]
it 

> > if i gunzip the gz file to C:\Users\LD.duckdb\extensions\v0.7.0\windows_amd64, load sqlite no error reports, load sqlite3 reports error
> > ```
> > D:\duckdb>duckdb070
> > v0.7.0 f7827396d7
> > Enter ".help" for usage hints.
> > Connected to a transient in-memory database.
> > Use ".open FILENAME" to reopen on a persistent database.
> > D load sqlite
> > > ;
> > D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE);
> > Error: IO Error: Extension "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\SQLITE.duckdb_extension" not found.
> > 
> > Candidate extensions: "sqlite", "sqlite3", "sqlite_scanner", "s3", "icu"
> > D load sqlite;
> > D load sqlite3;
> > Error: Invalid Input Error: Initialization function "sqlite_scanner_init" from file "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\sqlite_scanne
> > r.duckdb_extension" threw an exception: "Catalog Error: Table Function with name "sqlite_scan" already exists!"
> > ```
> 
> Does it work if you don't load the extension first?
no, it does not work and reports error
```
D:\duckdb>duckdb070
v0.7.0 f7827396d7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE);
Error: IO Error: Extension "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\SQLITE.duckdb_extension" not found.

Candidate extensions: "sqlite", "sqlite3", "sqlite_scanner", "s3", "icu"
```

**Comment by Mytherin** [comment]
It should be `TYPE sqlite` in lower-case, it is not case sensitive (it should be, but it isn't). You also shouldn't be able to load an extension twice - something is going wrong there throwing an error the second time.

**Comment by l1t1** [comment]
D load sqlite
> ;
D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE);
Error: IO Error: Extension "C:\Users\LD\.duckdb\extensions\v0.7.0\windows_amd64\SQLITE.duckdb_extension" not found.

**Comment by l1t1** [comment]
you mean
ATTACH 'd:/sqlite3.db' AS sqlite (TYPE SQLITE)
should be
ATTACH 'd:/sqlite3.db' AS sqlite (TYPE sqlite)?

**Comment by Mytherin** [comment]
Yes

**Comment by l1t1** [comment]
as for 0.6.1 on termux,  `install sqlite` reports none. `load sqlite` reports error as following
```
~ $ duckdb
v0.6.1 919cad2
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install sqlite
> ;
D load sqlite;
Error: IO Error: Extension "/data/data/com.termux/files/home/.duckdb/extensions/v0.6.1/linux_arm64/sqlite_scanner.duckdb_extension" could not be loaded: dlopen failed: library "libdl.so.2" not found
```

**Comment by Mause** [comment]
The prebuilt aarch64 Linux extensions we publish aren't built for Android, so won't work there

If you want to use them there, you'll have to build them yourself

**Comment by l1t1** [comment]
> It should be `TYPE sqlite` in lower-case, it is not case sensitive (it should be, but it isn't). You also shouldn't be able to load an extension twice - something is going wrong there throwing an error the second time.

it works without 'load sqlite'
```
D:\duckdb>duckdb070
v0.7.0 f7827396d7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH 'd:/sqlite3.db' AS sqlite (TYPE sqlite);
D CREATE TABLE sqlite.tbl(i INTEGER);
D INSERT INTO sqlite.tbl VALUES (1), (2), (3);
D SELECT * FROM sqlite.tbl;
┌───────┐
│   i   │
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
D .exit

D:\duckdb>cd\sqlite

D:\sqlite>sqlite3401 d:/sqlite3.db
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> select * from tbl;
1
2
3
```

**Comment by l1t1** [comment]
the query on sqlite is faster than sqlite 3.40.1, but slower than duckdb 0.60.
```
D create table t(id int,dq int,nl int,xb int,mz int);
D --sqlite
D insert into t(id,dq,nl,xb,mz) select value,abs(random()%30),abs(random()%20),abs(random()%2),abs(random()%60) from generate_series(1,1000000);
D --duckdb
D insert into t(id,dq,nl,xb,mz) select value,abs(random()*1000)::int%30,abs(random()*1000)::int%20,abs(random()*1000)::int%2,abs(random()*1000)::int%60 from generate_series(1,1000000)a(value);
with t1 as
(select count(*)cnt,dq,nl,xb from t group by dq,nl,xb)
select dq,
sum(case when nl=0 then cnt end)nl0,
sum(case when nl=1 then cnt end)nl1,
sum(case when nl=2 then cnt end)nl2,
sum(case when nl=3 then cnt end)nl3,
sum(case when nl=4 then cnt end)nl4,
sum(case when nl=5 then cnt end)nl5,
sum(case when nl=6 then cnt end)nl6,
sum(case when nl=7 then cnt end)nl7,
sum(case when nl=8 then cnt end)nl8,
sum(case when nl=9 then cnt end)nl9,
sum(case when nl=10 then cnt end)nl10,
sum(case when nl=11 then cnt end)nl11,
sum(case when nl=12 then cnt end)nl12,
sum(case when nl=13 then cnt end)nl13,
sum(case when nl=14 then cnt end)nl14,
sum(case when nl=15 then cnt end)nl15,
sum(case when nl=16 then cnt end)nl16,
sum(case when nl=17 then cnt end)nl17,
sum(case when nl=18 then cnt end)nl18,
sum(case when nl=19 then cnt end)nl19
from t1
group by dq;

│ 30 rows                                             21 columns (8 shown) │
duckdb070 on sqlite.db: Run Time (s): real 1.415 user 1.185608 sys 0.234002
duckdb060: Run Time (s): real 0.423 user 0.015600 sys 0.000000
sqlite3401: Run Time: real 3.864 user 3.166820 sys 0.078001
```

**Comment by l1t1** [comment]
> The prebuilt aarch64 Linux extensions we publish aren't built for Android, so won't work there
> 
> If you want to use them there, you'll have to build them yourself

how to build the extensions on termux?
