### ISSUE TITLE
regexp_split_to_array can't work in jar

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#6262]
### What happens?

regexp_split_to_array raise error in jar
```
select regexp_split_to_array('hello␣world; 42', ';?␣')
```
SQL 错误: Unsupported result column type VARCHAR[]
  Unsupported result column type VARCHAR[]

but, this work in cli, output:
`[hello, world; 42] `

### To Reproduce

```
select regexp_split_to_array('hello␣world; 42', ';?␣')
```

### OS:

windows

### DuckDB Version:

0.7.0

### DuckDB Client:

java

### Full Name:

wang cz

### Affiliation:

Linezone

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Array types are not yet supported in the JDBC driver
