### ISSUE TITLE
Dates and timestamps should be converted to Pandas dataframe using microsecond resolution (instead of nanosecond)

### ISSUE THREAD

**Issue by chumbert2** [duckdb/duckdb#6270]
### What happens?

When date and timestamps are converted to Pandas dataframe, a nanosecond resolution is used whereas DuckDB internally uses a microsecond resolution. This causes overflow issues with dummy dates like '9999-12-31'. Keeping a microsecond resolution during the conversion would solve this issue without precision loss. 

 

### To Reproduce

```
duckdb.__version__
'0.7.0'
```

Overflow example with dates:

```
duckdb.sql("select '9999-12-31'::date").df()
duckdb.ConversionException: Conversion Error: Could not convert DATE (9999-12-31) to nanoseconds
```

Overflow example with timestamps:
```
duckdb.sql("select '9999-12-31T00:00:00Z'::timestamp").df()
duckdb.ConversionException: Conversion Error: Could not convert Timestamp(US) to Timestamp(NS)
```

From https://duckdb.org/docs/sql/data_types/timestamp,
DuckDB represents instants as the number of microseconds (µs) since 1970-01-01 00:00:00+00.

### OS:

Debian GNU/Linux

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Cyril Humbert

### Affiliation:

Air Liquide

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by chumbert2** [comment]
**NOTE.** There is maybe a constraint due to Pandas internal representation for timestamps https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timestamp-limitations

**Comment by Mytherin** [comment]
Thanks for the report! Indeed, it seems we cannot convert to microsecond precision in the normal case. We should be able to make this work with `date_as_object`, though. i.e. this should work:

```sql
duckdb.sql("select '9999-12-31'::date").df(date_as_object=True)
```

**Comment by chumbert2** [comment]
Actually I tried but this does not seem to work as expected:

```
duckdb.sql("select '9999-12-31'::date").df(date_as_object=True)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.ConversionException: Conversion Error: Could not convert DATE (9999-12-31) to nanoseconds
```

```
>>> duckdb.__version__
'0.7.0'
```

**Comment by Mytherin** [comment]
Yes, what I meant to say is that this will never work/this error is expected:

```py
duckdb.sql("select '9999-12-31'::date").df()
# duckdb.ConversionException: Conversion Error: Could not convert DATE (9999-12-31) to nanoseconds
```

But, while it does not work yet, we **can/should** make this work:

```py
duckdb.sql("select '9999-12-31'::date").df(date_as_object=True)
```

**Comment by chumbert2** [comment]
:+1: Sorry, I misunderstood your initial comment. Yes it would be nice to make `.df(date_as_object=True)` work.

**Comment by Tishj** [comment]
Ah I seem to have completely forgotten this issue was made, here is the issue I made
#6298 

It's not a very straight forward fix, because pandas has limited support for controlling result dtypes
