### ISSUE TITLE
DuckDB CLI v0.7.0: Segmentation fault on "INSERT OR IGNORE" 

### ISSUE THREAD

**Issue by korpa** [duckdb/duckdb#6271]
### What happens?

Following SQL statement kills DuckDB CLI with a "Segmentation fault"
```sql
INSERT OR IGNORE INTO test_table
SELECT
  DISTINCT(id) as id,
  name
FROM test_table_raw;
```

### To Reproduce

Just run this script

```shell
#!/bin/bash

cat << EOF | duckdb ./test.db
--Create raw data table
CREATE TABLE test_table_raw(id VARCHAR, name VARCHAR);

--Insert raw data
INSERT INTO test_table_raw VALUES('abc001','foo'),('abc002','bar'),('abc001','foo2'),('abc002','bar2');

--Create aggregated data table
CREATE TABLE test_table(id VARCHAR PRIMARY KEY, name VARCHAR);


--Insert aggregated data
INSERT INTO test_table
SELECT
  DISTINCT(id) as id,
  name
FROM test_table_raw;

--Insert aggregated data second time with "INSERT OR IGNORE" => Segmentation fault
INSERT OR IGNORE INTO test_table
SELECT
  DISTINCT(id) as id,
  name
FROM test_table_raw;


SELECT * FROM test_table_raw;

EOF
```

### OS:

Linux

### DuckDB Version:

v0.7.0

### DuckDB Client:

CLI

### Full Name:

Korbinian Pauli

### Affiliation:

private

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hey! Thanks for the bug report

I'll look into it :)

**Comment by Tishj** [comment]
I can make this not segfault, but I can't make this work the way you want this to work.
We can detect conflicts between inserted rows and existing rows.

In this case the conflicts are within the inserted rows
```sql
SELECT
  DISTINCT(id) as id,
  name
FROM test_table_raw;
```
```
abc001  foo
abc002  bar
abc001  foo2
abc002  bar2
```

To get this to insert, you have to make sure that the rows you're inserting don't have conflicts between eachother
Likely you want this:
```sql
SELECT DISTINCT ON (id)
  id,
  name
FROM test_table_raw;
```
```
abc001  foo
abc002  bar
```

**Comment by korpa** [comment]
@Tishj, @Mytherin: Thank you very much. Are you planning a bugfix release in the next 2 weeks or so?
