### ISSUE TITLE
percent_rank bugs

### ISSUE THREAD

**Issue by rydeng** [duckdb/duckdb#6272]
### What happens?

percent_rank sometimes generate duplicate rows

### To Reproduce
```python
import pandas as pd
import numpy as np
ids = range(0, 3000)
dates = pd.date_range("2017-01-01", "2020-12-31").date
df = pd.concat([pd.DataFrame(
    {
        "id": [i] * len(dates),
        "date": dates,
        "v1": np.random.random(len(dates)),
        "v2": np.random.random(len(dates)),
        "v3": np.random.random(len(dates)),
    }) for i in ids])
import duckdb
for i in range(0, 10000):
    con = duckdb.connect()
    test = con.query("select date, id, v1, v2, percent_rank() over (partition by date order by v1) as rank_v1, v3 from df order by id, date;").df()
    if len(test) != len(df):
        print(f"{len(test)} is not {len(df)}")
        print(f"drop duplicate rows {len(test.drop_duplicates())}")
```
### OS:

linux, x64

### DuckDB Version:

0.7.0

### DuckDB Client:

python

### Full Name:

Roy Dennis

### Affiliation:

bq

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Thanks for reporting, maybe this is something for @hawkfish to look at

**Comment by Mytherin** [comment]
I have done some more investigation into the issue and it seems to be related to the new parallel partitioning code. The problem still occurs sporadically if we remove the `ORDER BY`:

```sql
select count(*) from (select percent_rank() over (partition by date) as rank_v1 from df);
```

Limiting the amount of threads during merging or scanning does not affect the result. In particular, it also seems to depend on the number of partitions. If we reduce the number of unique values in the `date` column the query works as intended.

**Comment by rydeng** [comment]
Yeah, if I use version 0.6.1, there is not this problem.

**Comment by hawkfish** [comment]
In the repro case the partition count is resized twice. The first time is just when the operator is starting out and we don't have a good cardinality estimate (0). The second time is when the code is in flight and one thread decides to resize the partitioning. It locks the global partition and copies the data to the new global partitioner in `ResizeGroupingData` but unfortunately the other threads are still appending to their own shared state from the old global partition. Next time they wake up, they call `SyncLocalPartition` but some of their data has already been copied, so it gets copied twice.

When the number of threads or groups is small, this second resizing doesn't happen, so nothing goes wrong.

**Comment by hawkfish** [comment]
To fix this, the threads all need to synchronise when a resize is needed and wait for one of them to finish the data copy before grabbing a new shared grouping.

**Comment by hawkfish** [comment]
Turned out to be simpler - we  could resize after we started combining and Bad Things would happen.
