### ISSUE TITLE
Spurious additional parameter required in prepared statement

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#6276]
### What happens?

DuckDB claims there's an additional parameter needed for a prepared statement (7) when there are only 6 parameter placeholders present.

### To Reproduce

```
In [6]: import duckdb

In [7]: s = "SELECT CASE ? WHEN ? THEN ? WHEN ? THEN ? ELSE ? END AS x"

In [8]: con = duckdb.connect()

In [9]: params = ('foo', 'f', 'F', 'o', 'O', 'foo')

In [10]: con.execute(s, params)
---------------------------------------------------------------------------
InvalidInputException                     Traceback (most recent call last)
Cell In[10], line 1
----> 1 con.execute(s, params)

InvalidInputException: Invalid Input Error: Prepared statement needs 7 parameters, 6 given

In [11]: len(params)
Out[11]: 6

In [12]: s.count("?")
Out[12]: 6
```

### OS:

NixOS

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
I think the issue may be the ? immediately behind the CASE that's probably duplicated in the binder?
