### ISSUE TITLE
[Python] Date -> NumPy/Pandas uses nanosecond precision

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6298]
### What happens?

Currently our conversion for a date-like type column from DuckDB -> NumPy array/Pandas column uses `datetime64[ns]`
```c++
	case LogicalTypeId::TIMESTAMP:
	case LogicalTypeId::TIMESTAMP_TZ:
	case LogicalTypeId::TIMESTAMP_NS:
	case LogicalTypeId::TIMESTAMP_MS:
	case LogicalTypeId::TIMESTAMP_SEC:
	case LogicalTypeId::DATE:
		dtype = "datetime64[ns]";
		break;
```

Internally we use microsecond precision for `TIMESTAMP[_*]` and days for `DATE`, so it makes much more sense to use `datetime64[us]` - which uses microsecond precision instead.

### To Reproduce

```py
>>> import duckdb
>>> df = duckdb.sql("select '2019-06-05'::DATE").df()
>>> print(df.dtypes)
CAST('2019-06-05' AS DATE)    datetime64[ns]
dtype: object
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I made this issue mostly to document what the hurdles are in making this change:

To create the dataframe, we use `from_dict`, which we pass a `Dict[str, numpy.ndarray]`.
Pandas for the most part ignores the `dtype` of these arrays and "infers" the dtypes instead.

Even when we change the previously mentioned dtype to `datetime64[us]`, Pandas converts this back to `datetime64[ns]` on construction of the dataframe.

`from_dict` has a `dtype` option, which seems promising, but isn't.
This option takes a single dtype, and force converts every column to that dtype, it can't be provided with a dictionary of dtypes.

`astype()` is a method on the DataFrame that allows changing the dtypes of the columns of the DataFrame, again this seems promising, but this also doesn't solve the issue.
It's slightly more useful than the `dtype` constructor option, because this does actually take a `Dict[str, dtype]` - but this does not support masked arrays, when the column contains missing values - the conversion fails.

**Comment by alemartinello** [comment]
Hi @Tishj do I understand correctly that a possible solution is being tested?

If so, ought that to be able to solve #8837 as well?

**Comment by Tishj** [comment]
> Hi @Tishj do I understand correctly that a possible solution is being tested?
> 
> If so, ought that to be able to solve #8837 as well?

Hey :)

This issue is caused by pandas < 2.0.0 converting any datetime into nanosecond precision.

Since 2.0.0 they actually support timestamp precisions other than nanoseconds, so we can emit microsecond precision now.
The other issue you mentioned is also fixed by this 👍
