### ISSUE TITLE
Segmentation error with json extension and values clause

### ISSUE THREAD

**Issue by jpmmcneill** [duckdb/duckdb#6305]
### What happens?

The python client crashes out with a segmentation fault when combining the `values` clause and the json extension.

### To Reproduce

/// python

```python
import duckdb

con = duckdb.connect()

con.execute("install json")
con.execute("load json")

con.execute("""
    copy (
        select * from values
        (uuid(), 10),
        (uuid(), 10),
        (uuid(), 15),
        (uuid(), 5)
        v (order_id, revenue)
    ) to 'query.json' (format json)
""")
```

In the above query, swapping the format to CSV / parquet yields a query that executes without a problem.

I'm not able to validate this on the prerelease (master branch) version because the `json` extension.

I also ran into a buffer error a while ago related to this that I was unable to find again.

### OS:

Mac OS

### DuckDB Version:

0.7.0

### DuckDB Client:

Python (3.11)

### Full Name:

James McNeill

### Affiliation:

Conjura

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jpmmcneill** [comment]
I'm definitely happy to have a go at fixing this but I am a cpp noob :(

**Comment by Tishj** [comment]
Shot in the dark, but does this work if you change to using `sql` instead of `execute` ?

**Comment by jpmmcneill** [comment]
@Tishj on your comment - unfortunately `con.sql` returns the same error 😢

**Comment by jpmmcneill** [comment]
In fact, basically nothing seems to export into `format json` for me. it's possible that it's just something weird on my machine 😅.

I've tried all permutations of:
1. exporting the result of a table
2. both in memory and "with path" db connections

**Comment by lnkuiper** [comment]
@jpmmcneill Thank you for the bug report! The issue was that I had only tested `COPY` with `FORMAT JSON` by specifically selecting columns or copying a table, i.e., `COPY my_table TO 'my_file.json'`, but not with a `SELECT *`.

For now, the workaround is to explicitly select the columns:
```py
import duckdb

con = duckdb.connect()

con.execute("install json")
con.execute("load json")

con.execute("""
    copy (
        select order_id, revenue from values
        (uuid(), 10),
        (uuid(), 10),
        (uuid(), 15),
        (uuid(), 5)
        v (order_id, revenue)
    ) to 'query.json' (format json)
""")
```

I've pushed a fix in #6319

**Comment by jpmmcneill** [comment]
Amazing, thank you @lnkuiper! Happy to help, even if it is just generating some work 🙈

**Comment by jpmmcneill** [comment]
I left a comment over in the PR!

https://github.com/duckdb/duckdb/pull/6319#issuecomment-1432951779
