### ISSUE TITLE
Writing parquet file to s3 fails for duckdb 0.7.0

### ISSUE THREAD

**Issue by nclaeys** [duckdb/duckdb#6309]
### What happens?

When trying to upgrade from duckdb 0.6.1 to 0.7.0 writing parquet data to s3 fails.

The error I get with duckdb 0.7.0 is: `Error: IO Error: Unexpected response during S3 multipart upload finalization`
When looking at the s3 bucket, I see that do see that parts were uploaded like this one: `https://s3.console.aws.amazon.com/s3/object/<bucket>?region=eu-west-1&prefix=dbt-duckdb/bla.parquet%3FpartNumber%3D1%26uploadId%3DNP.RqjQ0jvCSMAHopPGjaxPkqhd_u2FkQB5ori6AeO_gBpAU5OTngXfOrOizOLD4FEH.CXsyh5.0R23nBp6BpslebfPppNS6TK6ZRE0KtYjPDHH40YuAR9_MpYWPqE3TchzhAK.OE6Zqnnmf_6g3tjY6prr_vQ1rZ7pM9vnc_18-`

If I try the same thing on 0.6.1 it does succeed.

It is not related to permissions as I have administrator access on the account and have full access to the s3 bucket.

### To Reproduce

The test I did was running the following statements with duckdb 0.6.1 (919cad22e8) and 0.7.0 (f7827396d7):
```
install httpfs;
load httpfs;
<set credentials>

create table bla(id varchar primary key, name varchar);
insert into bla values('1','niels');
copy bla to 's3://...parquet';

```

### OS:

x64

### DuckDB Version:

0.7.0

### DuckDB Client:

shell

### Full Name:

Niels Claeys

### Affiliation:

Data Minded

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by djouallah** [comment]
I think, it is a duplicate of this  https://github.com/duckdb/duckdb/issues/5685

**Comment by nclaeys** [comment]
True missed that ticket

**Comment by nclaeys** [comment]
Duplicate of #5685
