### ISSUE TITLE
Segmentation fault when joining on timestamp with BETWEEN

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#6314]
### What happens?

I can reliably get a `Segmentation fault` from CLI and Python when joining on timestamp with `BETWEEN`.

It only seems to happen with some data:
This is a duckdb file, but I used `.txt` suffix to get it uploaded to GitHub:
[bad.duckb](https://github.com/duckdb/duckdb/files/10751514/bad.txt)

Even more strange: 
Whilst investigating for this issue I discovered it can be worked around by doing a sub-`SELECT` with an `ORDER BY` on the timestamp column.

### To Reproduce

Using attached duckdb file this causes seg fault:

```sql
SELECT ota.*, flags.desc as flag
FROM ota
LEFT JOIN flags ON ota.ts BETWEEN flags.start AND flags.end
ORDER BY ts;
```

But with this sub-`SELECT` it works:

```sql
SELECT ota2.*, flags.desc as flag
FROM (SELECT * FROM ota ORDER BY ts) ota2
LEFT JOIN flags ON ota2.ts BETWEEN flags.start AND flags.end
ORDER BY ts;
```

### OS:

Linux

### DuckDB Version:

v0.7.1-dev57 8da10c8e33

### DuckDB Client:

CLI & Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #6323. This was an issue in the `IEJoin's` handling of LEFT and RIGHT outer joins with many unmatched tuples.
