### ISSUE TITLE
PARTITION_BY is not yet supported for fsspec filesystems. 

### ISSUE THREAD

**Issue by legout** [duckdb/duckdb#6316]
### What happens?

`COPY`a Table with `PARTITION_BY` or `EXPORT DATABASE`  is not yet supported for fsspec filesystems. 

In python I get this error: `NotImplementedException: Not implemented Error: s3: DirectoryExists is not implemented!`

### To Reproduce

```sql
COPY data TO 's3://test_dir' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000, PARTITION_BY A);
```

```sql
EXPORT DATABASE  's3://test_dir' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000,);
```

### OS:

Linux

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Volker L.

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/6395

If you're able to retest with the latest dev version that would be great!

**Comment by djouallah** [comment]
@Mause i had this issue before and now it is working, thank you very much
