### ISSUE TITLE
CLI `.parameter init` doesn't work

### ISSUE THREAD

**Issue by buckett** [duckdb/duckdb#6325]
### What happens?

The DuckDB CLI says (.help output) it supports the SQLite style parameters: https://sqlite.org/cli.html#sql_parameters however when attempting to initialise the parameter store and then set a parameter it fails and complains that the syntax isn't recognised.

### To Reproduce

Try to initialise the parameters:

```
v0.6.1 919cad22e8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .parameter init
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
```

Try to set a parameter in the CLI:

```
❯ duckdb
v0.6.1 919cad22e8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .parameter set param value
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
Error: Parser Error: syntax error at or near "REPLACE"
LINE 1: REPLACE INTO temp.sqlite_parameters(key...
```
and on a later version.

```
v0.7.1-dev53 fc7f6f288d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .parameter set param value
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
sqlite3_db_config: unsupported.
Error: Parser Error: syntax error at or near "REPLACE"
LINE 1: REPLACE INTO temp.sqlite_parameters(key...
        ^
```

### OS:

Mac

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

Matthew Buckett

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the report, DuckDB does not support parameters in the way that SQLite does yet.
Likely we should update the CLI `.help` output to remove that claim 👍
