### ISSUE TITLE
Prepared statements fail when substituting into `COLUMNS`

### ISSUE THREAD

**Issue by nbhargava** [duckdb/duckdb#6332]
### What happens?

When trying to create a prepared statement that uses the `SELECT COLUMNS(<regex>) FROM table` format, specifying any sort of substitution in place of the regex string causes an error. In other words, trying to prepare something like:
```
SELECT COLUMNS(?) FROM my_table;
```
results in an error.

### To Reproduce

In python, run:
```
import duckdb

duckdb_conn = duckdb.connect(":memory:")
duckdb_conn.execute(
    """
    create or replace table my_table as
        select 'test1' as column1, 1 as column2, 'quack' as column3
        union all
        select 'test2' as column1, 2 as column2, 'quacks' as column3
        union all
        select 'test3' as column1, 3 as column2, 'quacking' as column3
"""
)
duckdb_conn.execute(
    """
    prepare v1 as
        select
            COLUMNS(?)
        from my_table"""
)
```

### OS:

macOS 13.2, M2-architecture

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Nikhil Bhargava

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Seems we're missing support in the grammar for prepared parameters in this place.
`third_party/libpg_query/grammar/statements/select.y` line 2223
