### ISSUE TITLE
`COALESCE()` should downcast factors to strings, but attempts the reverse

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#6356]
### What happens?

In the relational API, combining a factor and a character column with `COALESCE()` seems to try to convert the result to a factor/enum type. This can lead to errors.

### To Reproduce

``` r
con <- DBI::dbConnect(duckdb::duckdb())

DBI::dbExecute(con, 'CREATE MACRO "___coalesce"(a, b) AS COALESCE(a, b)')
#> [1] 0

df <- data.frame(x = letters[1:3], y = factor(letters[c(4:5, NA)]))
df
#>   x    y
#> 1 a    d
#> 2 b    e
#> 3 c <NA>

rel <- duckdb:::rel_from_df(con, df)

res <- duckdb:::expr_function("___coalesce", list(
  duckdb:::expr_reference("x"),
  duckdb:::expr_reference("y")
))

out <- duckdb:::rel_project(rel, list(res))
duckdb:::rapi_rel_to_df(out)
#> Error: Conversion Error: Could not convert string 'a' to UINT8


res <- duckdb:::expr_function("___coalesce", list(
  duckdb:::expr_reference("y"),
  duckdb:::expr_reference("x")
))

out <- duckdb:::rel_project(rel, list(res))
duckdb:::rapi_rel_to_df(out)
#> Error: Conversion Error: Could not convert string 'c' to UINT8
```

<sup>Created on 2023-02-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

88290f2c1c4fdd109c70a83353a157b89b2e0b4b

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
@pdet can you have a look please, here is a sort-of-minimal SQL example
```SQL
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
create table a (a string, b mood);
insert into a values ('moo', 'sad');
select coalesce(a, b) from a;
```
also throws the same error
