### ISSUE TITLE
DuckDB exits unexpectedly on large JSON import

### ISSUE THREAD

**Issue by shah** [duckdb/duckdb#6359]
### What happens?

I have a 43mb JSON file and I tried to read it like this:

```bash
duckdb -c "select count(*) from read_json_auto('test_json2.json', maximum_object_size=64388587);"
```

The output looks like this:

```bash
malloc(): corrupted top size
```

### To Reproduce

The file is private so I cannot upload it here, but I was curious if there are any known limits to how large a JSON file can be. If the core team has some large JSON files that have been tested I could look at those versus mine to see what might be different and share that instead.

### OS:

Linux Constitution 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux

### DuckDB Version:

v0.7.0 f7827396d7

### DuckDB Client:

CLI

### Full Name:

Shahid Shah

### Affiliation:

Netspective

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you please try to make this reproducible, ie by creating a non-private JSON file that triggers the issue? Would help us tremendously in tracking this down.

**Comment by shah** [comment]
Sure @hannes I'll try to deidentify it and put up a copy as soon as I can. Meanwhile, could you point me to the largest JSON test fixtures the DuckDB team used for unit testing the `read_json` functions? Thanks!

**Comment by lnkuiper** [comment]
@shah I have stress-tested using the data over at https://www.gharchive.org

Increasing `maximum_object_size` directly increases the memory usage, so this could be the issue as well. I have made improvements in a very recent PR that should reduce memory usage slightly, maybe you could try again on the latest master?

**Comment by shah** [comment]
Sure @lnkuiper I'm happy to try out master -- will need to setup my environment to build from source as the most current version (0.70.0) is what tested (via binary).

**Comment by lnkuiper** [comment]
@shah great! If you prefer, you can also wait for the 0.7.1 bugfix release. I hope it fixes the problem

**Comment by shah** [comment]
Agreed @lnkuiper that would be easier - we'll wait for 0.7.1 and then report back. Thanks for the awesome work!

**Comment by lnkuiper** [comment]
@shah If your input contains a large array (> 2048) of strings, then #6437 will fix your issue

**Comment by shah** [comment]
Excellent news @lnkuiper - we'll try the import again once the next version with #6437 is released. Thanks!

**Comment by shah** [comment]
@lnkuiper we can confirm that 0.7.1 no longer crashes when fed our large 43mb JSON file. Great work!
