### ISSUE TITLE
Unable to set S3 configuration parameters

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#6365]
### What happens?

Attempting to set the S3 parameters, such as region, fails. The commands appear to be unrecognized.

### To Reproduce

Run `SET s3_region='us-east-1';`, exactly as written in the docs.

Example output
```
$ ./build/release/duckdb
v0.7.1-dev187 79e5243ba0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET s3_region='us-east-1';
Error: Catalog Error: unrecognized configuration parameter "s3_region"

Did you mean: "schema"
D SET s3_url_style='path';
Error: Catalog Error: unrecognized configuration parameter "s3_url_style"

Did you mean: "null_order"
D 
```

### OS:

MacOS

### DuckDB Version:

0.7.0

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

Mode Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by michaeljohnalbers** [comment]
User error. I forgot to load the httpfs extension.

**Comment by Mytherin** [comment]
Thanks for the report! This happens if the `httpfs` extension is not loaded. Perhaps try `INSTALL httpfs; LOAD httpfs` first?

We should definitely improve the error reporting for when extension settings are set without the extension being loaded, however.
