### ISSUE TITLE
R: union-all followed by distinct is not order-preserving

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#6369]
### What happens?

For the relational API, "distinct" should be order-preserving. The order seems to have a random component.

### To Reproduce

``` r
con <- DBI::dbConnect(duckdb::duckdb())

df1 <- data.frame(x = c(1, 1, 2))
df2 <- data.frame(x = 2)

out <- duckdb:::rel_distinct(
  duckdb:::rel_union_all(
    duckdb:::rel_from_df(con, df1),
    duckdb:::rel_from_df(con, df2)
  )
)
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 1
#> 2 2
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
duckdb:::rapi_rel_to_df(out)
#>   x
#> 1 2
#> 2 1
```

<sup>Created on 2023-02-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

79e5243ba03f2c86d265d2746dee8ae29aead8aa

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
This is expected behaviour

**Comment by lnkuiper** [comment]
Distinct is done by a parallel hash aggregation. We cannot guarantee order there

**Comment by carlopi** [comment]
Potentially one things out of this could be for this (or others) observation to ending on a (short?) list of conventions where duckdb deviates from R-devs expectancy / 'gotcha', like https://duckdb.org/docs/api/r or somewhere else.

**Comment by krlmlr** [comment]
Sure, I can push an order on the client side too. This has worked to stabilize join order already.

**Comment by krlmlr** [comment]
Doing it on the client.
