### ISSUE TITLE
Exporting a database to parquet with tables+enum writes too much data

### ISSUE THREAD

**Issue by Tmonster** [duckdb/duckdb#6372]
### What happens?

When creating a persistent database, if I create an enum column, then export the whole database to parquet, the size of the tables with enum values is suspiciously large. I'm not sure if this is because parquet cannot handle enums well, or if maybe we are writing min-max values multiple times the same way we did in https://github.com/duckdb/duckdb/issues/5983.

If this is expected behavior feel free to close.

See steps to reproduce using tpch.

### To Reproduce

```
$ duckdb parquet-with-enum-export
load tpch;
call dbgen(sf=3);
select count(distinct(l_orderkey/4)) from lineitem; -- shows the amount of values we will have in our enum
create type orderkey_enum as enum (Select (l_orderkey/4)::VARCHAR from lineitem);
create table t2 (c1 orderkey_enum);
insert into t2 (select (l_orderkey/4)::VARCHAR from lineitem);
export database 'export_test' (FORMAT PARQUET);
export database 'export_test_csv' (FORMAT CSV);
```
In your shell, now you can inspect the sizes.
```
$ ls -lah parquet-with-enum-export
......   794M Feb 19 17:15. ....... parquet-with-enum-export
$ ls -lah export_test
total 4013784
.......   416B Feb 19 17:17 .
.......   1.5K Feb 19 17:16 ..
.......    36M Feb 19 17:16 customer.parquet
.......   775M Feb 19 17:17 lineitem.parquet
.......   598B Feb 19 17:17 load.sql
.......   2.3K Feb 19 17:16 nation.parquet
.......   176M Feb 19 17:16 orders.parquet
.......    20M Feb 19 17:16 part.parquet
.......   130M Feb 19 17:16 partsupp.parquet
.......   1.0K Feb 19 17:16 region.parquet
.......    12M Feb 19 17:17 schema.sql
.......   2.3M Feb 19 17:16 supplier.parquet
.......   774M Feb 19 17:17 t_.parquet
ls -lah export_test_csv
total 6800648
......   416B Feb 19 17:31 .
......   1.5K Feb 19 17:31 ..
......    70M Feb 19 17:31 customer.csv
......   2.1G Feb 19 17:31 lineitem.csv
......   886B Feb 19 17:31 load.sql
......   2.2K Feb 19 17:31 nation.csv
......   494M Feb 19 17:31 orders.csv
......    69M Feb 19 17:31 part.csv
......   342M Feb 19 17:31 partsupp.csv
......   386B Feb 19 17:31 region.csv
......    12M Feb 19 17:31 schema.sql
......   4.1M Feb 19 17:31 supplier.csv
......   133M Feb 19 17:31 t_.csv
```
Notice that the table t2 in parquet (or `t_` when exported) has a size equal to that of lineitem. The t2 table has 1,125,001 distinct vales and 17,996,609 total tuples. So 6% of the table is distinct. Also, while number of tuples/rows for lineitem and t2 are the same, lineitem has 16 columns while t2 has only 1. In addition, the size of `t2.csv` is 133mb while the size `t2.parquet` is 744mb, making the parquet file more than 5x as big as csv.

### OS:

MacOs monterey 12.1

### DuckDB Version:

v0.7.1-dev187

### DuckDB Client:

CLI

### Full Name:

Tom Ebergen

### Affiliation:

Duckdb Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tmonster** [comment]
This is still an issue with the fix in https://github.com/duckdb/duckdb/pull/6040

**Comment by Mytherin** [comment]
Parquet does not support enums - so enums should be stored in the same amount of bytes as VARCHAR columns. Is that not the case here? If so - that is a bug/problem we could fix. If it is the same - then that is expected.

**Comment by Tmonster** [comment]
That's what I was thinking as well. But I just ran the following commands to verify 
I thought, if I create the same table but one is enum and the other varchar, the exported parquet sizes should be almost the same.

```
-- t2 stores enums
create table t2 (c1 orderkey_enum);
insert into t2 (select (l_orderkey/4)::VARCHAR from lineitem);
-- t3 stores varchars
create table t3 (c2 VARCHAR);
insert into t3 (select (l_orderkey/4)::VARCHAR from lineitem);
copy (from t2) to 't2.parquet' (FORMAT parquet);
copy (from t3) to 't3.parquet' (FORMAT parquet);
```
then check the size 
```
$ ls -lah t2.parquet t3.parquet
-rw-r--r--  1 tomebergen  staff   774M Feb 19 23:38 t2.parquet
-rw-r--r--  1 tomebergen  staff   7.8M Feb 19 23:38 t3.parquet
```
Exporting enums is almost 100x exporting just raw varchars. 
tomorrow I will test a case with less enum values

**Comment by Mytherin** [comment]
My guess as to why this happens is that for enums we write the entire enum dictionary for each row group, whereas for strings we explicitly check which strings are present and generate a dictionary for only the values that are present in that row group. For `l_orderkey` specifically the enum values per row-group are entirely unique (as the first row group will have `0, 0, 0, 0, 1, 1, 1, 2, 2, 2`, the second one will have `25K, 25K+1, ...` etc).

It is an issue but it is a bit of a fringe edge case as well.
