### ISSUE TITLE
httpfs Error: Catalog Error: Table with name https://www... does not exist!

### ISSUE THREAD

**Issue by rferraton** [duckdb/duckdb#6388]
### What happens?

SELECT from http url that return a csv failed on windows (not try on linux)

SELECT count(*) from 'https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c';
Error: Catalog Error: Table with name https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c does not exist!
Did you mean "pragma_database_list"?
LINE 1: SELECT count(*) from 'https://www.data.gouv.fr/fr/datasets/r...

### To Reproduce

Launch Duckdb.exe cli on cmd or powershell

```SQL
install 'httpfs';
load 'httpfs';
SELECT count(*) from 'https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c';
```

The url should be stable a be tested as is

### OS:

Windows 10

### DuckDB Version:

0.7.0

### DuckDB Client:

Windows CLI

### Full Name:

Romain Ferraton

### Affiliation:

Architecture & Performance

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
If the file does not end in `.csv` you need to specify that it is a CSV file, e.g.:

```sql
SELECT count(*) from read_csv_auto('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c');
```

**Comment by rferraton** [comment]
Still failling 

D SELECT count(*) from read_csv_auto('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c');
Error: IO Error: No files found that match the pattern "https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c"

even with :
D SELECT count(*) from read_csv('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c',DELIM=';',HEADER=TRUE,ALL_VARCHAR=TRUE,Columns={'annee_de_reference':'VARCHAR','pays':'VARCHAR','label_en':'VARCHAR','part_du_gaz_naturel_dans_la_consommation_finale_d_energie0':'VARCHAR','consommation_finale_de_gaz_naturel_mtep':'VARCHAR','consommation_finale_d_energie_totale_mtep':'VARCHAR'});
Error: IO Error: No files found that match the pattern "https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c"

**Comment by rferraton** [comment]
when i look to the url header i see that 
Content-Type = application/csv; charset=utf-8
but
Content-Encoding = gzip
does gzip can be the source of the issue ?

**Comment by rferraton** [comment]
Update : 
This time no faillure but no data >

```
PS D:\Sources\DuckDB\duckdb_cli-windows-amd64_070> .\duckdb.exe D:\OpenData\data.gouv.fr\energie2.duckdb
v0.7.0 f7827396d7
Enter ".help" for usage hints.
D install 'httpfs';
D load 'httpfs';
D SELECT * from read_csv('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c',DELIM=';',HEADER=TRUE,Columns={'annee_de_reference':'VARCHAR','pays':'VARCHAR','label_en':'VARCHAR','part_du_gaz_naturel_dans_la_consommation_finale_d_energie0':'VARCHAR','consommation_finale_de_gaz_naturel_mtep':'VARCHAR','consommation_finale_d_energie_totale_mtep':'VARCHAR'});
┌────────────────────┬─────────┬───┬──────────────────────┐
│ annee_de_reference │  pays   │ . │ consommation_final.  │
│      varchar       │ varchar │   │       varchar        │
├─────────────────────────────────────────────────────────┤
│                         0 rows                          │
└─────────────────────────────────────────────────────────┘
```

**Comment by rferraton** [comment]
Update : 
After downloading manually the file from the origin url and putting it on a S3 bucket + granting public access to the uploaded file, it's work

It work even if I delete the .csv extension

```
SELECT * from read_csv_auto('https://apshare1.s3-eu-west-1.amazonaws.com/data/part-du-gaz-naturel-dans-la-consommation-finale-denergie-en-europe');
┌────────────────────┬────────────────────┬───┬──────────────────────┐
│ annee_de_reference │        pays        │ . │ consommation_final.  │
│       int64        │      varchar       │   │        double        │
├────────────────────┼────────────────────┼───┼──────────────────────┤
│               2020 │ Chypre             │ . │               1627.6 │
│               2020 │ Danemark           │ . │              13601.4 │
│               2020 │ Finlande           │ . │              24674.4 │
│               2020 │ Grèce              │ . │              15401.9 │
│               2020 │ Italie             │ . │           113119.475 │
│               2020 │ Malte              │ . │                547.5 │
│               2020 │ Slovénie           │ . │             4861.315 │
│               2021 │ Chypre             │ . │             1528.558 │
│               2021 │ Estonie            │ . │             2726.818 │
│               2021 │ Irlande            │ . │            10840.191 │
│               2021 │ Italie             │ . │           103057.147 │
│               2021 │ Lettonie           │ . │             3798.185 │
│               2021 │ Lituanie           │ . │             5284.212 │
│               2020 │ Hongrie            │ . │              17872.4 │
│               2020 │ Lituanie           │ . │             5457.728 │
│               2020 │ Pays-Bas           │ . │            44682.656 │
│               2020 │ Pologne            │ . │            69135.018 │
│               2020 │ Portugal           │ . │            16354.725 │
│               2020 │ République tchèque │ . │            24263.896 │
│               2020 │ Royaume-Uni        │ . │           121414.483 │
│                 ·  │    ·               │ · │                ·     │
│                 ·  │    ·               │ · │                ·     │
│                 ·  │    ·               │ · │                ·     │
│               2021 │ Pays-Bas           │ . │            42261.788 │
│               2021 │ Roumanie           │ . │             23472.38 │
│               2020 │ Autriche           │ . │              26215.8 │
│               2020 │ Belgique           │ . │              32553.0 │
│               2020 │ Bulgarie           │ . │               9698.7 │
│               2020 │ Irlande            │ . │            11296.601 │
│               2020 │ Lettonie           │ . │             3926.131 │
│               2021 │ Autriche           │ . │            24817.272 │
│               2021 │ Danemark           │ . │            13130.771 │
│               2021 │ Finlande           │ . │            23191.074 │
│               2021 │ Pologne            │ . │            70250.647 │
│               2020 │ Allemagne          │ . │             200601.2 │
│               2020 │ Espagne            │ . │              81512.9 │
│               2020 │ France             │ . │             139375.8 │
│               2020 │ Luxembourg         │ . │             3786.785 │
│               2020 │ Suède              │ . │            31311.413 │
│               2021 │ Belgique           │ . │            31039.168 │
│               2021 │ Croatie            │ . │             6431.987 │
│               2021 │ Hongrie            │ . │             17601.52 │
│               2021 │ Luxembourg         │ . │             3265.475 │
├────────────────────┴────────────────────┴───┴──────────────────────┤
│ 57 rows (40 shown)                             6 columns (3 shown) │
└────────────────────────────────────────────────────────────────────┘

```

So I suppose that there is a kind of **redirection** (301) with the initial url that is not acceptable by duckDB httpfs ?

**Comment by pdet** [comment]
> Update : This time no faillure but no data >
> 
> ```
> PS D:\Sources\DuckDB\duckdb_cli-windows-amd64_070> .\duckdb.exe D:\OpenData\data.gouv.fr\energie2.duckdb
> v0.7.0 f7827396d7
> Enter ".help" for usage hints.
> D install 'httpfs';
> D load 'httpfs';
> D SELECT * from read_csv('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c',DELIM=';',HEADER=TRUE,Columns={'annee_de_reference':'VARCHAR','pays':'VARCHAR','label_en':'VARCHAR','part_du_gaz_naturel_dans_la_consommation_finale_d_energie0':'VARCHAR','consommation_finale_de_gaz_naturel_mtep':'VARCHAR','consommation_finale_d_energie_totale_mtep':'VARCHAR'});
> ┌────────────────────┬─────────┬───┬──────────────────────┐
> │ annee_de_reference │  pays   │ . │ consommation_final.  │
> │      varchar       │ varchar │   │       varchar        │
> ├─────────────────────────────────────────────────────────┤
> │                         0 rows                          │
> └─────────────────────────────────────────────────────────┘
> ```

I've recently encountered a similar issue to this.

In my case, the problem was that the request header with the file length would come set with 0 (the server probably had to generate the file still and just submitted 0). The length is currently necessary, so we know when to stop reading the file.

I guess a fix to that is to try to fully download the file first id the length returned by the request is 0.

**Comment by Mytherin** [comment]
The master gives a more descriptive error message:

```sql
D SELECT count(*) from read_csv_auto('https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c');
Error: IO Error: Server did not send Content-Length header, can not read from this file.
```

**Comment by rferraton** [comment]
Thanks for the analysis @Mytherin and @pdet.

Indeed, the master have more descriptive error message since last week.

The tested url ( https://www.data.gouv.fr/fr/datasets/r/6d186965-f41b-41f3-9b23-88241cc6890c ) is a stable url from a gouv.fr api, and as you said @pdet , the csv is generated on the fly and the Content-Length is 0. 
I suppose this is quite common.

Why the Content-Length should be mandatory ? would it not be possible to catch and 'end-of-data' event of something like that when Content-Length =0 or empty ?
I also see the Content-Length is used to confirm the file is present but the Content-Type could also be used ?

**Comment by Mytherin** [comment]
Not knowing the length limits us from doing certain types of operations (e.g. partitioning the file over multiple threads). We will likely add support for this in the future, but it essentially forces us to download the entire file before operating on it, limiting potential optimizations.

**Comment by rferraton** [comment]
> Not knowing the length limits us from doing certain types of operations (e.g. partitioning the file over multiple threads). We will likely add support for this in the future, but it essentially forces us to download the entire file before operating on it, limiting potential optimizations.

I totally understand but unfortunately, this kind of lack is frequent with API/CSV. Hope this will change in the future !
Great new for the future support of 0-length http response with CSV !
