### ISSUE TITLE
Reading certain JSON from stdin fails randomly

### ISSUE THREAD

**Issue by eeroel** [duckdb/duckdb#6400]
### What happens?

Piping data from an API provided by https://stedolan.github.io/jq/tutorial/ to duckdb CLI with a `read_json_auto` query fails randomly (sometimes works, sometimes doesn't).

### To Reproduce

`curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | ./duckdb -c "select record.sha from (select unnest(json) as record from read_json_auto('/dev/stdin'))"` 

The error I get when the query fails: `
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19313  100 19313    0     0  66701      0 --:--:-- --:--:-- --:--:-- 70485
Error: Invalid Input Error: Malformed JSON in file "/dev/stdin", at byte 16383 in object 2: invalid literal.`

### OS:

Mac OS X 12.5.1 aarch64

### DuckDB Version:

0.7.0

### DuckDB Client:

CLI

### Full Name:

Eero Lihavainen

### Affiliation:

In profile

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by eeroel** [comment]
Lied a bit in the submit form, I couldn't get the latest master build to run on my system so didn't test on that.

**Comment by Tishj** [comment]
I have had to rewrite the query a bit, because it was invalid: `select * from read_json_auto('/dev/stdin')`
But I can't reproduce the issue on latest master

**Comment by Tishj** [comment]
Actually, I wanted to verify that this was actually fixed, so I ran a bit of a stress-test, and github rate-limited me
Which did cause a failure

```
Error: Binder Error: Referenced column "parents" not found in FROM clause!
Candidate bindings: "read_json_auto.message"
```

That could be what is happening to you?

**Comment by eeroel** [comment]
Hmm, the original query worked for me. I also got rate limited eventually but that's unrelated to the issue (curl shows same amount of data downloaded for correct and failed runs). With the original query I would get both the error and the correct result depending on the run.

**Comment by Tishj** [comment]
Hmm that's rather strange, because there is no object/column named `json` in the input
Maybe some aliasing behavior that was removed recently?

**Comment by eeroel** [comment]
Managed to get the latest build to work, looks like I can't reproduce this anymore so issue can be closed. My query worked on 0.7.0 but not on latest master because `read_json_auto` now reads the JSON array directly as a table.
