### ISSUE TITLE
Nodejs  : arrow extension for windows_amd64 not available ?

### ISSUE THREAD

**Issue by jpv** [duckdb/duckdb#6404]
### What happens?

Env : NodeJS 19.6.1
Version     "duckdb": "^0.7.0",
OS :  Windows 10 Professionnel 22H2 

"INSTALL arrow;" => [Error: IO Error: Failed to download extension "arrow" at URL "http://extensions.duckdb.org/v0.7.0/windows_amd64/arrow.duckdb_extension.gz"

Issue from my env ? or feature not available for WIn ?     

### To Reproduce

import duckdb from 'duckdb'

const db = new duckdb.Database(':memory:')

const conn =  db.connect();
conn.run("INSTALL arrow", (err, d) => {
            if (err) {
                console.error(err) 

                /*  =>  [Error: IO Error: Failed to download extension "arrow" at URL 
"http://extensions.duckdb.org/v0.7.0/windows_amd64/arrow.duckdb_extension.gz" */

            }
}
        

### OS:

Win10

### DuckDB Version:

0.7.0

### DuckDB Client:

nodejs

### Full Name:

jphvay (github)

### Affiliation:

github

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! The extension is indeed currently not available on Windows.

**Comment by jpv** [comment]
So sad. I'll wait. I have a work around (csv -> arrow)
BTW thank for your excellent job.
I close this no issue.
