### ISSUE TITLE
Large joins in persistent databases have left over temporary directory

### ISSUE THREAD

**Issue by Tmonster** [duckdb/duckdb#6420]
### What happens?

When joining two large tables on primary keys (or very unique keys), the temporary directory doesn't get cleaned up when the query finishes. A number of `.tmp` files are left over, each about 1gb large.

### To Reproduce

Make sure to start a persistent database
```
$ ./build/release/duckdb join-storage.duckdb
```
Setup
```SQL
call dbgen(sf=10);
alter table lineitem rename to lineitem1;
-- remove tables not needed for the test
drop table customer; drop table nation; drop table orders; drop table part; drop table partsupp; drop table region;
call dbgen(sf=10);
alter table lineitem rename to lineitem2;
-- remove tables not needed for the test
drop table customer; drop table nation; drop table orders; drop table part; drop table partsupp; drop table region;
-- copy the line item table and create a nice pk for joining.
CREATE TABLE lineitem_1_with_pk
(
    l_orderkey    BIGINT not null,
    l_partkey     BIGINT not null,
    l_suppkey     BIGINT not null,
    l_linenumber  BIGINT not null,
    l_quantity    DOUBLE PRECISION not null,
    l_extendedprice  DOUBLE PRECISION not null,
    l_discount    DOUBLE PRECISION not null,
    l_tax         DOUBLE PRECISION not null,
    l_returnflag  CHAR(1) not null,
    l_linestatus  CHAR(1) not null,
    l_shipdate    DATE not null,
    l_commitdate  DATE not null,
    l_receiptdate DATE not null,
    l_shipinstruct CHAR(25) not null,
    l_shipmode     CHAR(10) not null,
    l_comment      VARCHAR(44) not null,
    l_tmp_primary_key BIGINT
);
CREATE SEQUENCE l1_pk START 1;
INSERT INTO lineitem_1_with_pk SELECT l1.*, nextval('l1_pk') FROM lineitem1 l1;
CREATE TABLE lineitem_2_with_pk
(
    l_orderkey    BIGINT not null,
    l_partkey     BIGINT not null,
    l_suppkey     BIGINT not null,
    l_linenumber  BIGINT not null,
    l_quantity    DOUBLE PRECISION not null,
    l_extendedprice  DOUBLE PRECISION not null,
    l_discount    DOUBLE PRECISION not null,
    l_tax         DOUBLE PRECISION not null,
    l_returnflag  CHAR(1) not null,
    l_linestatus  CHAR(1) not null,
    l_shipdate    DATE not null,
    l_commitdate  DATE not null,
    l_receiptdate DATE not null,
    l_shipinstruct CHAR(25) not null,
    l_shipmode     CHAR(10) not null,
    l_comment      VARCHAR(44) not null,
    l_tmp_primary_key BIGINT,
);
CREATE SEQUENCE l2_pk START 1;
INSERT INTO lineitem_2_with_pk SELECT l2.*, nextval('l2_pk') FROM lineitem2 l2;
DROP TABLE lineitem1;
DROP TABLE lineitem2;
```
The following join query should trigger the bug. The query will succeed, but the data won't be cleaned up.
```
CREATE TABLE ans as select l1.*, l2.* from lineitem1 l1, lineitem2 l2 WHERE l1.l_tmp_primary_key = l2.l_tmp_primary_key;
```
Inspect the tmp directory
```
$ ls -lah join-storage.duckdb.tmp
```

### OS:

MacOS M1

### DuckDB Version:

v0.7.1-dev229

### DuckDB Client:

CLI

### Full Name:

Tom Ebergen

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Just to clarify, the `.block` files are cleaned up, but the `.tmp` files created by `TemporaryFileHandle` aren't. This is definitely a bug, but the bug is probably not in `PhysicalHashJoin`, because the hash join just creates blocks through the `BufferManager` API.

**Comment by Tmonster** [comment]
> Just to clarify, the `.block` files are cleaned up, but the `.tmp` files created by `TemporaryFileHandle` aren't. This is definitely a bug, but the bug is probably not in `PhysicalHashJoin`, because the hash join just creates blocks through the `BufferManager` API.

Yes this is true. Just `.tmp` files are leftover. I also just noticed, that if I exit the duckdb shell after the query completes, the `.tmp` files are cleaned up.
