### ISSUE TITLE
Select user from parquet 

### ISSUE THREAD

**Issue by JohnCoene** [duckdb/duckdb#6429]
### What happens?

Getting unexpected results from selecting `user` from parquet file.

### To Reproduce

```r
df <- data.frame(
  user = c("Me", "You"),
  x = 1L
)

arrow::write_parquet(df, "test.parquet")

con <- DBI::dbConnect(duckdb(), ":memory:")

DBI::dbGetQuery(con, "SELECT user FROM read_parquet('test.parquet');")

DBI::dbDisconnect(con)
```

```
  main.user()
1      duckdb
2      duckdb
```

### OS:

Linux

### DuckDB Version:

0.7.0

### DuckDB Client:

R

### Full Name:

John Coene

### Affiliation:

Opifex

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
This works: `DBI::dbGetQuery(con, "SELECT \"user\"  FROM read_parquet('test.parquet');")`

**Comment by rsund** [comment]
If you don't like escaping quotes (in order to separate reserved word from column name), you can also use raw strings. You can also write parquet files using DuckDB. And remember to use `shutdown=TRUE` while closing the connection.

``` r
df <- data.frame(
  user = c("Me", "You"),
  x = 1L
)

con <- DBI::dbConnect(duckdb::duckdb())
duckdb::duckdb_register(con,"df",df)
DBI::dbExecute(con, "COPY df TO 'test.parquet'")
#> [1] 2
DBI::dbGetQuery(con, r"{SELECT "user" FROM read_parquet('test.parquet');}")
#>   user
#> 1   Me
#> 2  You
DBI::dbDisconnect(con, shutdown=TRUE)
```

<sup>Created on 2023-02-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by JohnCoene** [comment]
Thanks!
