### ISSUE TITLE
[Python] `read_csv` only accepts a filepath

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6442]
### What happens?

The `read_csv` method in DuckDB is meant to be a replica of `pandas.read_csv`, so it should also accept different types of `filepath_or_buffer`, like it's counter part does

### To Reproduce

```py
import duckdb
from io import StringIO

string = StringIO("c1,c2,c3\na,b,c")
duckdb.read_csv(string, header=True)
```
```
┌─────────┬─────────┬─────────┐
│   c0    │   c1    │   c2    │
│ varchar │ varchar │ varchar │
├─────────┼─────────┼─────────┤
│ a       │ b       │ c       │
└─────────┴─────────┴─────────┘
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Might be able to reuse some of the fsspec code for this? As it already does some work to wrap python file objects

**Comment by Tishj** [comment]
I have a message from Mark suggesting something just like this ;)

**Comment by Tishj** [comment]
Likely we will need to register a subsystem with an internal protocol ("duckdb_string_io_" or something similar)
Then add the file with a generated name, forward this file with the attached protocol: "duckdb_string_io_://{random_name}"

Then through the VirtualFileSystem it will be matched by its protocol, and from there the FileSystem will do its job

**Comment by Tishj** [comment]
Actually it's not that straight forward,
I think I have to write a fsspec implementation that contains the StringIO object(s), and forwards the `read` call to the object.

I would have thought there would exist a fsspec filesystem implementation that does this already?

**Comment by Mytherin** [comment]
It might be worthwhile to create our own string-backed file system class instead of relying on fsspec, as this might have other use cases in other languages as well. Perhaps it could be used for #6448, for instance.

**Comment by Mause** [comment]
just speaking to Thijs, StringIO is just an example - we should accept anything that implements IOBase
