### ISSUE TITLE
string_agg with order by does not consider separator

### ISSUE THREAD

**Issue by nsiicm0** [duckdb/duckdb#6452]
### What happens?

When trying to use string_agg in conjunction with a ORDER BY within the string_agg aggregate function, the sep parameter of the function is not considered and will revert back to the default sep (which appears to be ","). Obviously one could use a replace afterwards, but this is cumbersome if you have the default separator in your data.

Input:
| var1   | var2   |
|:-------|:-------|
| A      | X      |
| A      | Y      |
| B      | X      |
| B      | Y      |
| B      | X      |

Output:
| var1   | agg_var2_1   | agg_var2_2   | agg_var2_3   | agg_var2_4   |
|:-------|:-------------|:-------------|:-------------|:-------------|
| A      | X+Y          | X,Y          | X+Y          | X,Y          |
| B      | X+Y+X        | X,X,Y        | X+Y          | X,Y          |

### To Reproduce
(output see table above)
```sql
WITH SAMPLE_DATA AS (
    SELECT 'A' as var1, 'X' as var2
    UNION ALL
    SELECT 'A' as var1, 'Y' as var2
    UNION ALL
    SELECT 'B' as var1, 'X' as var2
    UNION ALL
    SELECT 'B' as var1, 'Y' as var2
    UNION ALL
    SELECT 'B' as var1, 'X' as var2
)
SELECT
    var1
    , string_agg(var2, '+') as agg_var2_1
    , string_agg(var2 ORDER BY var2, '+') as agg_var2_2
    , string_agg(DISTINCT var2, '+') as agg_var2_3
    , string_agg(DISTINCT var2 ORDER BY var2, '+') as agg_var2_4
FROM SAMPLE_DATA
GROUP BY ALL
ORDER BY var1
```

### OS:

Windows x86_64

### DuckDB Version:

0.7.1-dev341

### DuckDB Client:

Python (3.8)

### Full Name:

Niclas Simmler

### Affiliation:

Personal use

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lokax** [comment]
Maybe you should try 
`string_agg(var2, '+' ORDER BY var2)`
?

string_agg(var2 ORDER BY var2, '+') will sort by both var2 and '+'

**Comment by hawkfish** [comment]
That is indeed the problem:

```sql
WITH SAMPLE_DATA AS (
    SELECT 'A' as var1, 'X' as var2
    UNION ALL
    SELECT 'A' as var1, 'Y' as var2
    UNION ALL
    SELECT 'B' as var1, 'X' as var2
    UNION ALL
    SELECT 'B' as var1, 'Y' as var2
    UNION ALL
    SELECT 'B' as var1, 'X' as var2
)
SELECT
    var1
    , string_agg(var2 ORDER BY var2, '+') as agg_var2_2
    , string_agg(var2, '+' ORDER BY var2) as agg_var2_5
FROM SAMPLE_DATA
GROUP BY ALL
ORDER BY var1
```

| var1 | agg_var2_2 | agg_var2_5 |
|---|---|---|
| A | X,Y | X+Y |
| B | X,X,Y | X+X+Y |
