### ISSUE TITLE
Remove lock on a DuckDB file?

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb#6477]
### What happens?

I lost an SSH connection to a server running a DuckDB SQL command. When I reconnected, I couldn't connect to the database for write operations. I made sure every process using the DuckDB file was no longer running but it looks like the DuckDB file itself contains a lock that I'm unable to remove. Without that removal, I can't use the database in write mode.

Is there any command I can issue to remove the write lock?

### To Reproduce

```bash
$ sudo lsof -OnP | grep water.duckdb # Nothing returned
$ ~/duckdb ./water.duckdb
```

```
Error: unable to open database "./water.duckdb": IO Error: Could not set lock on file "./water.duckdb": Resource temporarily unavailable
```

```bash
$ sudo strace ~/duckdb ./water.duckdb
```

```
access("./water.duckdb", F_OK)          = 0
stat("./water.duckdb", {st_mode=S_IFREG|0664, st_size=123897131008, ...}) = 0
openat(AT_FDCWD, "./water.duckdb", O_RDWR|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=123897131008, ...}) = 0
fcntl(3, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2b22b80, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "Error: unable to open database \""..., 137Error: unable to open database "./water.duckdb": IO Error: Could not set lock on file "./water.duckdb": Resource temporarily unavailable
) = 137
exit_group(1)                           = ?
```

### OS:

Ubuntu

### DuckDB Version:

20 LTS

### DuckDB Client:

v0.7.0 f7827396d7

### Full Name:

Mark Litwintschik

### Affiliation:

Open5G

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ClaytonSmith** [comment]
Bump on this issue. Is there any documented way to release the locks?

**Comment by poojanilangekar** [comment]
I am facing the same issue on MacOS, how can we release locks on a duckdb file?

**Comment by erikhuck** [comment]
+1

**Comment by erikhuck** [comment]
@poojanilangekar but how do you actually do it? Is there a command line option?

**Comment by erikhuck** [comment]
@poojanilangekar Is there a command line command for duckdb to accomplish forcing a database file to unlock?

**Comment by poojanilangekar** [comment]
You need to update the DuckDb version.

**Comment by VonsName** [comment]
i met the issus. 
os: Debian GNU/Linux 11 (bullseye)

**Comment by marklit** [comment]
This is still an issue.

**Comment by erikhuck** [comment]
@marklit it sure is. A while ago I had to just copy all the tables I had to a new database file. But that was on a previous version. Have you updated to version 1.0 yet?

**Comment by marklit** [comment]
I'm using 1.0, yeah. I walk on eggshells to avoid getting data stuck inside one of these locked databases.

**Comment by ClaytonSmith** [comment]
comment

**Comment by marklit** [comment]
I found that if I killed the process with the DuckDB file open, it unlocked. This might not work in all scenarios though.

```bash
$ ~/duckdb test.duckdb
```

```sql
.quit
```

```bash
$ cp test.duckdb unlocked.duckdb
~/duckdb test.duckdb
```

```
CTRL-Z
```

```bash
$ diff test.duckdb unlocked.duckdb # Identical

$ ~/duckdb test.duckdb
```

```
Error: unable to open database "test.duckdb": IO Error: Could not set lock on file "test.duckdb": Conflicting lock is held in /home/mark/duckdb (PID 263743). See also https://duckdb.org/docs/connect/concurrency
```

```bash
$ sudo lsof -OnP | grep test.duckdb
```

```
duckdb    263743                             mark    3uW     REG               8,32     12288            707841 /home/mark/test.duckdb
duckdb    263743 263744 duckdb               mark    3uW     REG               8,32     12288            707841 /home/mark/test.duckdb
...
```

```bash
$ sudo kill -9 263743
```

```
[1]+  Killed                  ~/duckdb test.duckdb
```

```bash
$ ~/duckdb test.duckdb
```

```sql
-- Loading resources from /home/mark/.duckdbrc
v1.1.3 19864453f7
Enter ".help" for usage hints.
D
```

**Comment by ClaytonSmith** [comment]
I think this should stay open IMO. The CLI or something should be able to gracefully mange lock files. 
>  I walk on eggshells to avoid getting data stuck 

and 

> This might not work in all scenarios though

Doesn't inspire enough confidence in this solution for the issue to be marked as completed.
