### ISSUE TITLE
Problems reading gzipped files from s3 (Filehandle API)

### ISSUE THREAD

**Issue by nicosuave** [duckdb/duckdb#6497]
### What happens?

I see the following when attempting to read from s3 when object metadata k/v`Content-Encoding` is set to `gzip`

```
Error: Invalid Error: IO Error: Read error for HTTP GET Range to ...
```

### To Reproduce

1. Upload file to s3 with `Content-Encoding` set to `gzip`
2. Read file
3. Removing the above encoding allows the file to be read

### OS:

aarch64

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Nico Ritschel

### Affiliation:

Ant Money

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by peralmq** [comment]
I'm having the same issue.

**Comment by Tishj** [comment]
This issue sounds related to https://github.com/duckdb/duckdb/pull/6448
Could you have a look at that or test again after it's merged?

Let us know if they're not related or your issue is still not fixed after testing with that branch/PR

**Comment by nicosuave** [comment]
@Tishj I am still seeing similar (`RuntimeError: IO Error: Read error for HTTP GET Range to [...]`), testing with 0.7.2-dev982

**Comment by carlopi** [comment]
Hi @nicosuave, could you potentially set up a reachable bucket that we can be used to reproduce this?

**Comment by nicosuave** [comment]
@carlopi 

```sql
install httpfs;
load httpfs;

-- working example
-- ┌─────────┬─────────┐
-- │ column0 │ column1 │
-- │ varchar │ varchar │
-- ├─────────┼─────────┤
-- │ 'foo'   │ 'bar'   │
-- │ foo     │ bar     │
-- └─────────┴─────────┘
from read_csv_auto("https://duckdb-public-gzip-test.s3.us-east-2.amazonaws.com/test.csv");

-- broken example, same file with Content-Encoding object metadata set to gzip
-- Error: Invalid Error: IO Error: Read error for HTTP GET Range to 'https://duckdb-public-gzip-test.s3.us-east-2.amazonaws.com/test.csv.gz'
from read_csv_auto("https://duckdb-public-gzip-test.s3.us-east-2.amazonaws.com/test.csv.gz");
```

**Comment by nicosuave** [comment]
Whoops, I provided the public HTTP URL; here's an updated example with S3 URI (but the same HTTP request occurs under the hood regardless).

```
install httpfs;
load httpfs;

set s3_region="us-east-2";

-- working example
-- ┌─────────┬─────────┐
-- │ column0 │ column1 │
-- │ varchar │ varchar │
-- ├─────────┼─────────┤
-- │ 'foo'   │ 'bar'   │
-- │ foo     │ bar     │
-- └─────────┴─────────┘
from read_csv_auto("s3://duckdb-public-gzip-test/test.csv");

-- broken example, same file with Content-Encoding object metadata set to gzip
-- Error: Invalid Error: IO Error: Read error for HTTP GET Range to 'https://duckdb-public-gzip-test.s3.us-east-2.amazonaws.com/test.csv.gz'
from read_csv_auto("s3://duckdb-public-gzip-test/test.csv.gz");
```

**Comment by carlopi** [comment]
I believe that the setup in your side is not completely conform with DuckDB expectations, that are that if the Accept-Encoding header is not present, Content-Encoding should not be sent from the server, but this is something that should further check on our side, could you keep the test setup unchanged for a few days?

Also:
```
curl --compressed https://duckdb-public-gzip-test.s3.us-east-2.amazonaws.com/test.csv.gz --output test
```
will return basically the uncompressed test.csv, while I believe we sort of expect to get the same file back.

**Comment by nicosuave** [comment]
Sure, I can leave as is for now. AWS Kinesis Firehose (and I'm sure other AWS services) write to s3 in this manner: updating Content-Encoding.

As a result, my understanding is the files are served uncompressed over HTTP/s3, but they are indeed stored as compressed in s3. Seemingly some peculiarity of how that http server behaves; wish I had more detail.

**Comment by nicosuave** [comment]
> > @Tishj I am still seeing similar (`RuntimeError: IO Error: Read error for HTTP GET Range to [...]`), testing with 0.7.2-dev982
> 
> Can you reconfirm which duckdb version you're using? We haven't raised RuntimeErrors in python since before 0.5.0

Forgive me; I must have copy pasta'd into an open CLI instance when confirming. I am now using `0.7.2-dev1188`

**Comment by nicosuave** [comment]
If there is anything I can do to facilitate testing and uncovering the underlying issue, I am happy to help, just let me know, y'all!
