### ISSUE TITLE
COPY to S3 from Windows with Hive partitions uses windows slash instead of unix slash

### ISSUE THREAD

**Issue by jesseginsberg** [duckdb/duckdb#6502]
### What happens?

On Windows, when using the COPY command to export data to S3 using parquet with Hive partitions, the files are exported with the Windows `\` slash instead of the Linux/S3 `/` slash.  

### To Reproduce

```
INSTALL httpfs; 
LOAD httpfs;

CREATE TABLE cities (
    name            VARCHAR,
    country         VARCHAR
);

INSERT INTO cities VALUES ('San Francisco', 'USA');
INSERT INTO cities VALUES ('New York', 'USA');
INSERT INTO cities VALUES ('Vancouver', 'Canada');
INSERT INTO cities VALUES ('Sydney', 'Australia');

COPY cities TO 's3://my-bucket/test_folder/cities_export_test' 
(FORMAT PARQUET, PARTITION_BY (country));
```

The resulting files in the S3 bucket look like the below.  After "cities_export_test", the wrong `\` is used.
```
s3://my-bucket/test_folder/cities_export_test/cities_export_test\country=Australia\data_0.parquet
s3://my-bucket/test_folder/cities_export_test/cities_export_test\country=Canada\data_0.parquet
s3://my-bucket/test_folder/cities_export_test/cities_export_test\country=USA\data_0.parquet
```

### OS:

Windows 10

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI and Python

### Full Name:

Jesse Ginsberg

### Affiliation:

Horizon Media

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This is something I noticed in one of my recent fsspec pr's as well - I think the path separators need to be filesystem local: https://github.com/duckdb/duckdb/blob/c1ee858e4a4b3454165ea41c34e514676b594335/tools/pythonpkg/tests/fast/test_filesystem.py#L194-L196

**Comment by samansmink** [comment]
issue should be solved now https://github.com/duckdb/duckdb/pull/8345

**Comment by jesseginsberg** [comment]
thanks @samansmink!
