### ISSUE TITLE
BLOCK_SIZE C Macro collision

### ISSUE THREAD

**Issue by pedroerp** [duckdb/duckdb#6504]
### What happens?

Not a bug in duckdb, but we recently bumped into a collision issue in one internal system which ends up including a kernel header (fs.h) that defines BLOCK_SIZE as a C macro, and that ends up conflicting and rewriting `Storage::BLOCK_SIZE` in duckdb, and thus failing compilation. 

I know there are hacky ways to around this (like undefining this macro before including duckdb), but considering BLOCK_SIZE is a fairly general name, any chance you would be willing to accept a PR that renames Storage::BLOCK_SIZE to something like `Storage::DUCKDB_BLOCK_SIZE` or maybe `Storage::block_size`?

### To Reproduce

Include any library that has a C-style define `BLOCK_SIZE` before including duckdb.hpp. 

### OS:

Ubuntu, but reproduces on any. 

### DuckDB Version:

Any

### DuckDB Client:

Any

### Full Name:

Pedro Pedreira

### Affiliation:

Meta Platforms Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
Hi @pedroerp! I took a look at the issue, and I think I have an alternative solution that might require less changes: move declaration of struct Storage to an 'inner' header, that should not be included from `duckdb.hpp`.

Could you potentially check if this is of some use, doing something like:
```
cd duckdb
git remote add carlopi https://github.com/carlopi/duckdb.git
git fetch carlopi
git checkout carlopi/includeStorage
```
?

**Comment by pedroerp** [comment]
Hi @carlopi thanks for the quick reply. Looks like this solved the issue. Any chance you could get it merged?
