### ISSUE TITLE
R: Wrong thread calling 'Rf_protect'

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#6508]
### What happens?

When running package tests tests with R configured with `--enable-strict-barrier`, the following errors appear sporadically, followed by a segmentation fault:

```
Fatal error: Wrong thread calling 'Rf_protect'
Fatal error: Wrong thread calling 'RunFinalizers'
Fatal error: Wrong thread calling 'RunFinalizers'
Fatal error: Wrong thread calling 'RunFinalizers'
...
```

### To Reproduce

With a suitable `R-sb` executable, instructions TBD:

```sh
R-sb -q -e 'testthat::test_local()'
```

### OS:

Ubuntu

### DuckDB Version:

c817201fa84f8d01289d0c327e07db4a2cc8894e

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by krlmlr** [comment]
Managed to boil it down to inner joins with strings.

The code below crashes on R built with `--enable-strict-barrier` . @hannes: can you replicate?

``` r
partsupp <- data.frame(
  ps_partkey = c(1L, 1L, 1L),
  ps_suppkey = c(2L, 27L, 52L),
  ps_availqty = c(3325L, 8076L, 3956L),
  ps_supplycost = c(771.64, 993.49, 337.09),
  ps_comment = c(
    ", even theodolites. regular, final theodolites eat after the carefully pending foxes. furiously regular deposits sleep slyly. carefully bold realms above the ironic dependencies haggle careful",
    "ven ideas. quickly even packages print. pending multipliers must have to are fluff",
    "after the fluffily ironic deposits? blithely special dependencies integrate furiously even excuses. blithely silent theodolites could have to haggle pending, express requests; fu"
  )
)

part <- data.frame(
  p_partkey = c(1110L, 9L, 1761L, 1222L, 1030L, 933L, 1713L, 1585L, 120L, 355L),
  p_mfgr = c(
    "Manufacturer#4", "Manufacturer#4", "Manufacturer#4", "Manufacturer#2",
    "Manufacturer#2", "Manufacturer#3", "Manufacturer#2", "Manufacturer#4",
    "Manufacturer#1", "Manufacturer#5"
  )
)

con <- DBI::dbConnect(duckdb::duckdb())
DBI::dbExecute(con, 'CREATE MACRO "=="(a, b) AS a = b')
#> [1] 0

rel_partsupp <- duckdb:::rel_from_df(con, partsupp)
rel_part <- duckdb:::rel_from_df(con, part)

expr <- duckdb:::expr_function("==", list(
  duckdb:::expr_reference("ps_partkey"),
  duckdb:::expr_reference("p_partkey")
))

rel <- duckdb:::rel_join(rel_partsupp, rel_part, list(expr))
duckdb:::rel_to_altrep(rel)
#> [1] ps_partkey    ps_suppkey    ps_availqty   ps_supplycost ps_comment   
#> [6] p_partkey     p_mfgr       
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2023-03-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Thanks. Do you get crashes with

```r
R-sb -q -e 'testthat::test_local()'
```

?

I can still replicate on Ubuntu (with R 4.2.3).

On macOS I can configure with

```sh
./configure  --without-recommended-packages --enable-R-shlib --with-blas --with-lapack --disable-java --enable-strict-barrier --with-x=no --with-tcltk=no --with-cairo=no --with-aqua=no 'LDFLAGS=-L/opt/homebrew/lib' 'CPPFLAGS=-I/opt/homebrew/include' 'PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig'
```

but then loading any package with a shared library fails with a segmentation fault. Trying building R without strict barrier now.

**Comment by krlmlr** [comment]
I can repro on macOS. Instructions:

1. Install deps with Homebrew
2. Configure R 4.2.3 with `./configure  'CC=clang -arch arm64' 'CXX=clang++ -arch arm64' 'OBJC=clang -arch arm64' 'FC=/opt/homebrew/bin/gfortran -mtune=native' 'CFLAGS=-falign-functions=64 -Wall -g -O0' 'CXXFLAGS=-falign-functions=64 -Wall -g -O0' 'OBJCFLAGS=-falign-functions=64 -Wall -g -O0' 'FCFLAGS=-Wall -g -O0' 'F77FLAGS=-Wall -g -O0' '--enable-memory-profiling' --without-recommended-packages --enable-R-shlib --with-blas --with-lapack --disable-java --enable-strict-barrier --with-x=no --with-tcltk=no --with-cairo=no --with-aqua=no 'LDFLAGS=-L/opt/homebrew/lib' 'CPPFLAGS=-I/opt/homebrew/include' 'PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig'`
3. Compile with `R_NO_BASE_COMPILE=true make -j8` (with `R_NO_BASE_COMPILE` compilation is a tad faster at the expense of run time)
4. Install dependencies from source with `bin/R -q -e 'install.packages("DBI", type = "source")`
5. Run the example from https://github.com/duckdb/duckdb/issues/6508#issuecomment-1451376033: `bin/R -q -f example.R`

Now testing the same with R-devel.

**Comment by krlmlr** [comment]
Can't repro the crashes with R-devel yet.

Going back to square one, testing with `testthat::test_local()` .

**Comment by krlmlr** [comment]
No need to, I can repro reliably if I put the join + print in a loop. Can you confirm?

```r
partsupp <- data.frame(
  ps_partkey = c(1L, 1L, 1L),
  ps_suppkey = c(2L, 27L, 52L),
  ps_availqty = c(3325L, 8076L, 3956L),
  ps_supplycost = c(771.64, 993.49, 337.09),
  ps_comment = c(
    ", even theodolites. regular, final theodolites eat after the carefully pending foxes. furiously regular deposits sleep slyly. carefully bold realms above the ironic dependencies haggle careful",
    "ven ideas. quickly even packages print. pending multipliers must have to are fluff",
    "after the fluffily ironic deposits? blithely special dependencies integrate furiously even excuses. blithely silent theodolites could have to haggle pending, express requests; fu"
  )
)

part <- data.frame(
  p_partkey = c(1110L, 9L, 1761L, 1222L, 1030L, 933L, 1713L, 1585L, 120L, 355L),
  p_mfgr = c(
    "Manufacturer#4", "Manufacturer#4", "Manufacturer#4", "Manufacturer#2",
    "Manufacturer#2", "Manufacturer#3", "Manufacturer#2", "Manufacturer#4",
    "Manufacturer#1", "Manufacturer#5"
  )
)

con <- DBI::dbConnect(duckdb::duckdb())
DBI::dbExecute(con, 'CREATE MACRO "=="(a, b) AS a = b')

rel_partsupp <- duckdb:::rel_from_df(con, partsupp)
rel_part <- duckdb:::rel_from_df(con, part)

expr <- duckdb:::expr_function("==", list(
  duckdb:::expr_reference("ps_partkey"),
  duckdb:::expr_reference("p_partkey")
))

repeat {
  rel <- duckdb:::rel_join(rel_partsupp, rel_part, list(expr))
  print(duckdb:::rel_to_altrep(rel))
}
```

**Comment by krlmlr** [comment]
```
R Under development (unstable) (2023-03-25 r84062) -- "Unsuffered Consequences"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin22.3.0 (64-bit)
```

**Comment by hannes** [comment]
Yup, with the loop getting

```
Fatal error: Wrong thread calling 'Rf_protect'
Fatal error: Wrong thread calling 'RunFinalizers'
...
[1]    98181 illegal hardware instruction  ~/source/r-source/build/bin/R -f Desktop/bad.R
```

**Comment by hannes** [comment]
Need different test case if this is still an issue, this passes now

**Comment by krlmlr** [comment]
Test case still failing last time I checked: https://github.com/duckdb/duckdb/pull/6974#issuecomment-1500897528

**Comment by krlmlr** [comment]
Now seeing, on 6f543cb464d94c7b6adbc40d49e9209678a92515, with R-devel compiled with strict barrier:

```r
...

dbGetQuery(con, "SELECT a FROM df")
#> Error in rapi_execute(res@stmt_lst$ref, res@arrow, res@connection@driver@bigint ==  :
#>   STDVEC_DATAPTR can only be applied to a vector, not a 'char'
#> Calls: dbGetQuery ... .local -> duckdb_result -> duckdb_execute -> rapi_execute
```

**Comment by hannes** [comment]
@Tmonster can you have a look?

**Comment by Tmonster** [comment]
After compiling R from source according to step 2&3 [here](https://github.com/duckdb/duckdb/issues/6508#issuecomment-1483991725), the following example still throws the same error 

```R
library(duckdb)

con <- dbConnect(duckdb())
on.exit(dbDisconnect(con, shutdown = TRUE))
df <- data.frame(a=c(NA, as.character(1:30)))

duckdb_register(con, "df", df, experimental=TRUE)

dbGetQuery(con, "SELECT a FROM df")
#> Error in rapi_execute(res@stmt_lst$ref, res@arrow, res@connection@driver@bigint ==  :
#>   STDVEC_DATAPTR can only be applied to a vector, not a 'char'
#> Calls: dbGetQuery ... .local -> duckdb_result -> duckdb_execute -> rapi_execute
```

However, if `experiment=FALSE`, then no error is thrown. If I'm not mistaken, our priority is to make sure everything works with the default `experimental=FALSE`, so I think we can close this issue, and potentially file another one when we circle back to the experimental functionality

**Comment by krlmlr** [comment]
Sure, works for me! Thanks.
