### ISSUE TITLE
Add generic table function -> list-producing scalar function wrapper

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6513]
The idea is that table-producing functions that produce a single column could also be useful as a list-producing scalar function.

Take for example `glob` (shamelessly stolen from [this discussion](https://github.com/duckdb/duckdb/discussions/6370))

As a table function:
```sql
select * from glob('ducktales/*')
```
Produces:
```
┌─────────────────────┐
│        file         │
│       varchar       │
├─────────────────────┤
│ ducktales/life      │
│ ducktales/is        │
│ ducktales/like      │
│ ducktales/a         │
│ ducktales/hurricane │
└─────────────────────┘
```

As a scalar function:
```sql
select glob('ducktales/*')
```
Would produce:
```
┌──────────────────────────────────────────────────────────────────────────────────┐
│                            select glob('ducktales/*')                            │
│                                    varchar[]                                     │
├──────────────────────────────────────────────────────────────────────────────────┤
│ [ducktales/life, ducktales/is, ducktales/like, ducktales/a, ducktales/hurricane] │
└──────────────────────────────────────────────────────────────────────────────────┘
```

Because DuckDB's internal representation of a column (`Vector`) and a list (`ListVector`) are very compatible, this should be relatively straight forward to implement.

**Comment by Tishj** [comment]
Likely a good starting place would be to look at `src/planner/binder/expression/bind_table_function_expression` line 30

```c++
	if (!func) {
		// function was not found - check if we this is a table function
		auto table_func = Catalog::GetEntry(context, CatalogType::TABLE_FUNCTION_ENTRY, function.catalog,
		                                    function.schema, function.function_name, true, error_context);
		if (table_func) {
			throw BinderException(binder.FormatError(
			    function,
			    StringUtil::Format("Function \"%s\" is a table function but it was used as a scalar function. This "
			                       "function has to be called in a FROM clause (similar to a table).",
			                       function.function_name)));
		}
		// not a table function - search again without if_exists to throw the error
		Catalog::GetEntry(context, CatalogType::SCALAR_FUNCTION_ENTRY, function.catalog, function.schema,
		                  function.function_name, false, error_context);
		throw InternalException("Catalog::GetEntry for scalar function did not throw a second time");
	}
```
Instead of throwing, we could check if the function produces a single column first - then add specialized code to wrap the execution of this table function and transform the resulting column to a list

**Comment by Mytherin** [comment]
Thanks for opening the issue - this is a good idea. It is worth noting that there are two types of table functions - regular table functions (that use `function`) and table-in-out functions (that use `in_out_function`). I describe the differences some more here (#5485). This really only works/makes sense for table-in-out functions.

**Comment by Tishj** [comment]
Hmm so this would actually not work for `glob`, because it makes use of `function`

**Comment by Mytherin** [comment]
`glob` can (and should) be rewritten to a table-in-out function. But only functions that have fixed return types can be rewritten. `read_csv` for example has to stay as a regular table function.

**Comment by Tishj** [comment]
Yea that much I understand, but I figured at bind time we have to know what columns+types the function returns, so when we bind the table function, we can determine if it meets our criteria - regardless of the type of table function it is?

**Comment by Mytherin** [comment]
We can't bind a standard table function with non-constant parameters. For example `SELECT read_csv(col) FROM tbl` could never really work since the return types for `read_csv` depend on the input types.

**Comment by Tishj** [comment]
Right, I hadn't considered that, I was only thinking about constants.
Makes sense that the return types have to be fixed 👍
