### ISSUE TITLE
Argument order of CLI: `-json` has no effect after `-c COMMAND`

### ISSUE THREAD

**Issue by phbender** [duckdb/duckdb#6514]
### What happens?

Specifying `-json` after `-c COMMAND` is without effect. The documentation (`--help`) does not give a hint in this regard.

### To Reproduce

```bash
$ duckdb -json -c "SELECT * FROM range(4)"
[{"range":0},
{"range":1},
{"range":2},
{"range":3}]

 $ duckdb -c "SELECT * FROM range(4)" -json
┌───────┐
│ range │
│ int64 │
├───────┤
│     0 │
│     1 │
│     2 │
│     3 │
└───────┘
```

### OS:

Linux

### DuckDB Version:

0.7.0

### DuckDB Client:

CLI

### Full Name:

Private Person

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This seems to be consistent with SQLite's shell:

```bash
$ > sqlite3 -json -cmd "select 42"              
[{"42":42}]
$ > sqlite3 -cmd "select 42" -json
42
--
42
```

I would say this is expected - the parameters on the command line are processed in-order, which includes setting the output mode.
