### ISSUE TITLE
Exceptions from MacOS extensions not caught properly

### ISSUE THREAD

**Issue by samansmink** [duckdb/duckdb#6521]
### What happens?

Thanks to @ywelsch for reporting this in detail. What's happening is as follows: when an extension that is built with EXTENSION_STATIC_BUILD=1 is loaded by duckdb, there's now basically two DuckDB's in the application. The reason for this is to avoid the need for RTLD_GLOBAL which is problematic in various clients.

Problems arise however when the extension c ode throws a duckdb::Exception (or one of its derived classes). To be able to catch these from the main DuckDB code the typeinfo of the exceptions is checked. On linux this is all fine, as explained here: [click](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/libsupc%2B%2B/typeinfo#L52). tldr: strcmp will be used to catch exceptions by their symbol name.

However on MacOS no strcmp happens, but only pointer comparison is executed causing duckdb to not be able to catch the specific exception and will end up catching them as std::exceptions instead, losing the ability to do specific handling.

### To Reproduce

build json extension + duckdb binary without extensions:
```
EXTENSION_STATIC_BUILD=1 DISABLE_BUILTIN_EXTENSIONS=1 BUILD_JSON=1 make
```
then with a `test.json` that contains invalid json, run:
```
D LOAD 'build/release/extension/json/json.duckdb_extension';
D SELECT * FROM read_json_objects('test.json');
Error: Invalid Error: Invalid Input Error: Malformed JSON in file "test.json", at byte 1 in object 3: unexpected character.
```
Note the Invalid Error indicates that DuckDB was not able to catch the exception properly.

### OS:

MacOS

### DuckDB Version:

v0.7.1

### DuckDB Client:

CLI

### Full Name:

Sam Ansmink

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
That's interesting - perhaps we should switch to looking at the error type as part of the string message of the exception instead of relying on RTTI for this? i.e. we could check that the string starts with `Invalid Input Error` - then determine it is an InvalidInputException.

**Comment by ywelsch** [comment]
While #9286 is providing some relief for certain situations, I don't think it is fixing the issue at large here (and not for the cases that I care about).

If we can't rely on RTTI, all the places in the code that rely on a DuckDB exception type to be caught (e.g. `catch (FatalException &ex)` in  ClientContext to invalidate the DB, or `catch (const Exception &ex)` in `Planner::CreatePlan` would need to be rewritten so that catching std::exception is equivalent. The PRQL extension for DuckDB e.g. [cares about this](https://github.com/ywelsch/duckdb-prql/blob/5c2cccfdbc828d0c3a5e920dcb48770e408b8989/src/prql_extension.cpp#L96-L101).

Can we reopen the issue please?

**Comment by isaacbrodsky** [comment]
This appears to be breaking type checks and assertions in extensions, too, which makes it impractical to use debug with assertion extension builds on MacOS. For example, this PR: https://github.com/isaacbrodsky/h3-duckdb/pull/66/files crashes in tests with this stack trace: https://gist.github.com/isaacbrodsky/50fb5257e5456a278459df7cbb2e69ba (`INTERNAL Error: Assertion triggered in file ".../duckdb/src/include/duckdb/common/types/vector_buffer.hpp" on line 128: dynamic_cast<TARGET *>(this)`) but there is nothing I can find wrong with the function under test.
