### ISSUE TITLE
Unable to to connect to local .duckdb file using PowerBI ODBC

### ISSUE THREAD

**Issue by acarter24** [duckdb/duckdb#6528]
### What happens?

When setting up an ODBC connection in PowerBI using the DuckDB Driver and a local .duckdb file, I receive a non-descriptive error message and no tables are shown for selection.

![image](https://user-images.githubusercontent.com/126154605/222375592-c5865aa2-9e1a-4a51-811f-ea21eb9f96d3.png)

![image](https://user-images.githubusercontent.com/126154605/222375259-228f771f-6ef6-4592-83c8-2b9ae9eea279.png)

Expected outcome:

See list of tables and columns to select from in PowerBI.

Here is the duckdb file open in dbeaver for comparison:

![image](https://user-images.githubusercontent.com/126154605/222375884-c8ca0c89-2e7e-43ec-b26b-a9bdd803d673.png)

### To Reproduce

ODBC connection string:

`database=C:\Users\***\meltano.duckdb`

### OS:

Window 11

### DuckDB Version:

7.0.1

### DuckDB Client:

ODBC

### Full Name:

Andy Carter

### Affiliation:

Powershop

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rdataforge** [comment]
same issue here. There is a workaround if you want to try:

1. export data tables to parquet file]
2. connect using CTE (see link to website)

https://datamonkeysite.com/2022/04/17/using-duckdb-with-powerbi/

**Comment by guenp** [comment]
I've created a DuckDB Power Query Custom Connector that let you import your data from a `duckdb` database directly: https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector
It's still in beta so bug reports/contributions are encouraged!
