### ISSUE TITLE
Compression not yet implemented for INT128 

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#6531]
This results in much larger databases when hugeint or large decimals are used, e.g.:

```sql
create table lineitem as
select *
from 'lineitem.parquet';
-- 160MB database
```

```sql
create table lineitem as
select * replace (l_orderkey::decimal(38,0) as l_orderkey, l_partkey::decimal(38,0) as l_partkey, l_suppkey::decimal(38,0) as l_suppkey)
from 'lineitem.parquet';
-- 343MB
```

**Comment by Tishj** [comment]
Likely we just want to compress the int64's separately right?
Or do you want to write something specialized for int128?

**Comment by Mytherin** [comment]
We should compress the entire hugeint value similar to what we do for bitpacking.

As a simpler implementation we could also only compress if the values are small (e.g fits in a `uint64_t`) - and then we can compress the values as a uint64_t
