### ISSUE TITLE
FTS does not tokenize CJK text correctly.

### ISSUE THREAD

**Issue by rxm** [duckdb/duckdb#6544]
### What happens?

The full text search does not work when CJK characters are used.  The bug is in the regular expression used. 

As part of the preparation of the text in FTS, a tokenization macro splits on space after modifying the text to be searched.  The macro replaces anything that matches `(\.|[^a-z])+` with a space.  That regular expression under Google's Re2 library will replace all CJK characters by spaces.  As a side effect, the resulting empty strings seems to confuse the calculation of the score.  

### To Reproduce

To reproduce the issue, compare the results of the commands below with and without documents 4 and 5:

``` sql
DROP SCHEMA IF EXISTS fts_main_corpus CASCADE;
DROP TABLE IF EXISTS corpus;

CREATE TABLE corpus(id INTEGER, content TEXT);
INSERT INTO corpus
VALUES 
    (1, 'Hello, World!'),
    (2, 'hello earthlings'),
    (3, 'Alô, Mundo')
     ,
    (4, '你好，世界！'),
    (5, 'こんにちは 地球人')
;

-- build the index 
PRAGMA create_fts_index('corpus', 'id', 'content');

-- tokenize
SELECT id, fts_main_corpus.tokenize(content) FROM corpus;

-- score 
SELECT id, fts_main_corpus.match_bm25(id, 'world') FROM corpus;
```

Notice that document with id 1 does not have a score when documents 4 and 5 are part of the corpus.

I could not match the code in my version of Duckdb with what is on GitHub, so I not sure where my mistake is.  `ducked --version` returns `v0.7.0 f7827396d7`, but the macro for `match_bm25` returned by `SELECT macro_definition FROM duckdb_functions() WHERE function_name = 'match_bm25'` does not match what could be derived from `git show f7827396d7:extension/fts/indexing.sql`.

One possible solution is to use `[^\p{L}]`, if the input is in the NFC, instead of `[^a-z]`, but not having built duckdb I am not sure if that is correct.

### OS:

macOS 12.6.3

### DuckDB Version:

0.7.0

### DuckDB Client:

CLI

### Full Name:

Ronnie Mainieri

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
The `create_fts_index` function actually allows you to override the `ignore` string:

```sql


DROP SCHEMA IF EXISTS fts_main_corpus CASCADE;
DROP TABLE IF EXISTS corpus;

CREATE TABLE corpus(id INTEGER, content TEXT);
INSERT INTO corpus
VALUES 
    (1, 'Hello, World!'),
    (2, 'hello earthlings'),
    (3, 'Alô, Mundo'),
    (4, '你好，世界！'),
    (5, 'こんにちは 地球人')
;

-- build the index 
PRAGMA create_fts_index('corpus', 'id', 'content', ignore='[^\p{L}]');

-- tokenize
SELECT id, fts_main_corpus.tokenize(content) FROM corpus;

-- score 
D SELECT id, fts_main_corpus.match_bm25(id, 'world') AS score FROM corpus;
┌───────┬─────────────────────┐
│  id   │        score        │
│ int32 │       double        │
├───────┼─────────────────────┤
│     1 │ 0.47712125471966244 │
│     2 │                NULL │
│     3 │                NULL │
│     4 │                NULL │
│     5 │                NULL │
└───────┴─────────────────────┘
```

Perhaps we should specify `[^\p{L}]` as the default. @lnkuiper thoughts?

**Comment by rxm** [comment]
I did not know `create_fts_index` did that  🙈.  Yes, thank you, that resolves it.

Maybe a safer default is to tokenize by splitting on U+0020 (ASCII space).
