### ISSUE TITLE
Is the 7813eea926 version of httpfs going to be uploaded soon?

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb#6548]
### What happens?

Up until this morning, I was able to run the following bash command below on the c817201 commit of DuckDB which the geo extension is currently pinned to. But when I built and ran the following again this morning on a fresh system I was greeted with:

```
Error: near line 1: IO Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/7813eea926/linux_amd64/httpfs.duckdb_extension.gz"
Extension "httpfs" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.

Error: near line 2: IO Error: Extension "/home/mark/.duckdb/extensions/7813eea926/linux_amd64/httpfs.duckdb_extension" not found.
Extension "httpfs" is an existing extension.

Install it first using "INSTALL httpfs".
```

### To Reproduce

```
$ echo "INSTALL httpfs;
        CREATE TABLE mobile_perf AS
        SELECT *
        FROM parquet_scan('s3://ookla-open-data/parquet/performance/type=mobile/year=2022/*/*.parquet',
                          FILENAME=1);" \
      | duckdb ~/ookla.duckdb
```

### OS:

Ubuntu

### DuckDB Version:

0.7.0 c817201

### DuckDB Client:

CLI

### Full Name:

Mark Litwintschik

### Affiliation:

Open5G

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you try installing again? I was able to access that file just now

Also, read the warning in the error message: 
> Are you using a development build? In this case, extensions might not (yet) be uploaded.

**Comment by marklit** [comment]
It's working now, thank you.
