### ISSUE TITLE
hive-partitioned parquet directory requires explicit glob level 

### ISSUE THREAD

**Issue by gforsyth** [duckdb/duckdb#6558]
### What happens?

I have a hive-partitioned parquet directory that looks like this:
```
🐚  tree outhive.parquet/
outhive.parquet
├── yearID=1877
│  └── part-0.parquet
├── yearID=1878
│  └── part-0.parquet
├── yearID=1884
│  └── part-0.parquet
```

`read_parquet` doesn't support recursive globs, so I need to specify the level of `/*/*` to match the directory structure.  That's a fair trade-off when I'm passing in random lists of files, but if I specify `hive_partitioning=true`, I think that the top-level directory should be sufficient (and in that case, specifically, duckdb should recursively glob for the parts)

### To Reproduce

```
D CREATE OR REPLACE VIEW awards_players AS
> SELECT * FROM read_parquet("outhive.parquet/*/*", hive_partitioning=true);
D DESCRIBE awards_players;
┌─────────────┬─────────────┬─────────┬───────┬─────────┬───────┐
│ column_name │ column_type │  null   │  key  │ default │ extra │
│   varchar   │   varchar   │ varchar │ int32 │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼───────┼─────────┼───────┤
│ playerID    │ VARCHAR     │ YES     │       │         │       │
│ awardID     │ VARCHAR     │ YES     │       │         │       │
│ lgID        │ VARCHAR     │ YES     │       │         │       │
│ tie         │ VARCHAR     │ YES     │       │         │       │
│ notes       │ VARCHAR     │ YES     │       │         │       │
│ yearID      │ VARCHAR     │ YES     │       │         │       │
└─────────────┴─────────────┴─────────┴───────┴─────────┴───────┘
D CREATE OR REPLACE VIEW awards_players AS SELECT * FROM read_parquet("outhive.parquet/", hive_partitioning=true);
Error: IO Error: No files found that match the pattern "outhive.parquet/"
```

### OS:

ubuntu

### DuckDB Version:

x86_64

### DuckDB Client:

command line

### Full Name:

Gil Forsyth

### Affiliation:

gil@voltrondata.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
We are working on adding support for recursive globbing in general (see #5897) - that should also address your issue I think?

**Comment by gforsyth** [comment]
That's a fine middle-ground.  There might be some cases where we want to auto-glob when a directory is passed, but that behavior tends to elicit strong opinions.  I'm happy with recursive globbing.
