### ISSUE TITLE
HTTPFS gets 400 Error Bad Request when reading s3 in 0.7.1 release

### ISSUE THREAD

**Issue by czabriskie** [duckdb/duckdb#6563]
### What happens?

In a prior version I used, 0.6.1, I was able to pull data from my s3 bucket with the following code.

```
s3_region = 'us-west-2'
access_key_id = os.getenv('AWS_ACCESS_KEY_ID')
secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY')
session_token = os.getenv('AWS_SESSION_TOKEN')

cursor = duckdb.connect()

df = cursor.execute(f"""
                        INSTALL httpfs;
                        LOAD httpfs;
                        SET s3_region='{s3_region}';
                        SET s3_access_key_id='{access_key_id}';
                        SET s3_secret_access_key='{secret_access_key}';
                        SET s3_session_token='{session_token}';

                        SELECT *
                            FROM parquet_scan('s3:path.parquet');
                        """).df()

print(df)
```

However, when updating to 0.7.1, this code no longer runs. Instead I get an error.

```
duckdb.Error: Invalid Error: IO Error: Unable to connect to URL "s3:path.parquet": 400 (Bad Request)
```

### To Reproduce

Run code with 0.7.1

```
s3_region = 'us-west-2'
access_key_id = os.getenv('AWS_ACCESS_KEY_ID')
secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY')
session_token = os.getenv('AWS_SESSION_TOKEN')

cursor = duckdb.connect()

df = cursor.execute(f"""
                        INSTALL httpfs;
                        LOAD httpfs;
                        SET s3_region='{s3_region}';
                        SET s3_access_key_id='{access_key_id}';
                        SET s3_secret_access_key='{secret_access_key}';
                        SET s3_session_token='{session_token}';

                        SELECT *
                            FROM parquet_scan('s3:path*.parquet');
                        """).df()

print(df)
```

### OS:

arm64

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Cameron Zabriskie

### Affiliation:

Biolexis Therapuetics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by kamilcglr** [comment]
Hello, as reported in issue #6786 , there is an issue with s3 and parquet_scan with all paths containing one or more wildcards.

**Comment by samansmink** [comment]
Could you retry this on current master or a recent dev release with the region set to auto as specified in https://blog.cloudflare.com/r2-ga/ ?
Trying this on my machine on r2 works fine!

**Comment by kamilcglr** [comment]
> 

Thank you for your response, I answered [here](https://github.com/duckdb/duckdb/issues/6786#issuecomment-1543529278)

**Comment by xerial** [comment]
I'm also experiencing the same issue (400 Bad Request) even for accessing a public S3 bucket, which requires no AWS access key configurations. It worked in 0.6.1, but stops working in 0.7.x, 0.8.0.

**Comment by Mause** [comment]
> I'm also experiencing the same issue (400 Bad Request with duckdb cli and read_parquet command) even for accessing parquet files in a public S3 bucket, which requires no AWS access key configurations. It worked in 0.6.1, but stops working in 0.7.x, 0.8.0.
> 
> If changing `read_parquet('s3://(bucket name)/(path)')` to S3 https URLs `read_parquet('https://(bucket name).s3.amazonaws.com/(path)')`, duckdb can read parquet files on S3.

Can you run `select * from duckdb_settings() where name like 's3%'` and ensure the values you see there are the one you expected?

One of the changes introduced in 0.7.x was reading S3 settings from environment variables. While convenient, this can be surprising if you're not expecting it. (See https://github.com/duckdb/duckdb/pull/5419)

@czabriskie this is likely your issue as well, if it broke in 0.7.x

**Comment by Mause** [comment]
> @Mause Thanks! You are right. After resetting irrelevant s3 settings, public s3://(...) access worked. My account and access tokens set in the environment variables need AWS profile-based authentication, which is not yet supported according to the discussion in #5419, so that's part of the failure reason. It would be great if duckdb can support AWS profile authentication as well. 

Yeah we're hoping to add that as part of https://github.com/duckdb/duckdb/issues/4021, feel free to add your support there

@czabriskie are you able to confirm if that fixes your issue as well?
