### ISSUE TITLE
Optional NumPy dependency

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#657]
We could make the NumPy/Pandas dependency in the Python client optional, and drop the features associated with them (fetchnumpy, fetchpandas, scanning df) if the libraries are not there. Thoughts?

**Comment by hannesmuehleisen** [comment]
We could remove for sure but right now Pandas/Numpy are the only ways to get larger amounts of data out of DuckDB. I guess NumPy alone is enough to do that though, so pandas could be optional indeed. Otherwise we could work around with raw byte arrays? What triggered this proposal?

**Comment by Mytherin** [comment]
[This guy on HackerNews asked for it](https://news.ycombinator.com/item?id=23290840). Not all workloads require large result import/export, and for a drop-in SQLite replacement it is sufficient to only use the standard DB protocol for which we need no dependencies. I would say it depends on how easy it is to drop the required dependency or how ugly it would end up being.

If we can make it so the dependency is only checked when an actual method is called (i.e. calling fetchnumpy will fail if numpy is not installed) then that could be quite an elegant solution.

**Comment by dustalov** [comment]
Is it possible to avoid NumPy/Pandas dependencies by adding a method `fetchdict() -> Dict[str, List]` that outputs virtually the same data structure as returned by `fetchnumpy()`, but using the built-in Python types only? I see that masks are used, but cannot they be replaced by `Optional[T]` values?

**Comment by hannesmuehleisen** [comment]
Yes, certainly. However, constructing and consuming very large Python lists is very slow and we should probably avoid it. I think its either use the Python DB API (`fetchone` and friends) or use the bulk api with `fetchnumpy` and `fetchdf`

**Comment by dustalov** [comment]
Although I have never dived deeply into the CPython's code, [they say](https://docs.python.org/3.8/faq/design.html#how-are-lists-implemented-in-cpython) that the lists are contiguous arrays of references to other objects. As far as I understand, this is technically equivalent to NumPy's `dtype=object`. The numeric values can be handled with the built-in [array](https://docs.python.org/3/library/array.html) type that has a smaller overhead. A small wrapper container class can provide enough abstraction for read-only purposes. Also, pybind11 can expose STL containers as native Python objects, which can be even cheaper than NumPy.

**Comment by hannesmuehleisen** [comment]
Thats just the thing, arrays of objects are pretty horrible performance-wise. This is why NumPy uses arrays of native types (e.g. integer) instead of them for most types (except strings, notably). So I don't think that will make a great difference to `fetch()` and friends.

**Comment by tenko** [comment]
Python has the buffer protocol [link](https://docs.python.org/3/c-api/buffer.html) this leads to Python support multidimensional heterogeneous arrays out of the box without any dependencies. 

Numpy will access any object supporting the buffer protocol without overhead.
It is also support in other libraries like PIL/Pillow and therfore  will be more general solution
to access the data.

It seems pybind11 support this also [link](https://pybind11-rtdtest.readthedocs.io/en/stable/advanced.html#buffer-protocol)

As for the import of numpy/pandas. Can this be done lazily inside the functions/method when invoked?

**Comment by hannesmuehleisen** [comment]
Indeed I was not aware of this Buffer protocol. That seems like a good compromise. Happy to review a PR!

**Comment by tenko** [comment]
I could give it a try, but my skills in C++ is not very great and therefore no promises.

**Comment by dustalov** [comment]
The last time I wrote a C++ code was a home task more than ten years ago. While writing a wrapper could be a fun exercise, I cannot estimate how much time I would need for this.

**Comment by hannesmuehleisen** [comment]
PR #720 will partially address this by removing the fixed Pandas dependency
