### ISSUE TITLE
accent in file path causing IOException

### ISSUE THREAD

**Issue by ClementSreeves** [duckdb/duckdb#6573]
### What happens?

duckdb.connect() causes an IOException when the full filepath contains an "é" character, but a relative path is provided. If the section of the path containing the "é" character is provided, it works fine.

### To Reproduce

![image](https://user-images.githubusercontent.com/12448250/222928596-e9a66e69-790c-45c8-a442-20fdbf57ee19.png)

### OS:

Windows10 x64

### DuckDB Version:

0.7.1, duckdb-0.7.2.dev225

### DuckDB Client:

Python

### Full Name:

Clement Sreeves

### Affiliation:

Personal Project

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed now in #7503.
