### ISSUE TITLE
Unable to Change Column Type After Deleting Offending Rows

### ISSUE THREAD

**Issue by HiramTheHero** [duckdb/duckdb#6577]
### What happens?

If a column is of type VARCHAR, and items are deleted which would make it eligible to be cast into an INT; altering the column type throws an error and states that the item that was deleted cannot be cast into an INT.

See the reproduction steps for more info.

### To Reproduce

```
CREATE TABLE iris("Sepal.Length" VARCHAR, "Sepal.Width" INTEGER);
INSERT INTO "iris"("Sepal.Length","Sepal.Width") VALUES('5.1',3.5);
INSERT INTO "iris"("Sepal.Length","Sepal.Width") VALUES('4.9',3.0);
INSERT INTO "iris"("Sepal.Length","Sepal.Width") VALUES('""',3.2000000000000001776);
DELETE FROM iris WHERE "Sepal.Length" = '""';
ALTER TABLE iris ALTER "Sepal.Length" TYPE INTEGER;
```

### OS:

MacOS M1

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Hiram H.

### Affiliation:

Self (Just someone who loves DuckDB.)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by HiramTheHero** [comment]
Any idea why this occurs? The work around is to create a new column with the proper type, delete the old column, then rename the new column to the old one's name.

If I am using DuckDB incorrectly I apologize, any explanation from the documentation would also be helpful.

Thanks for making a great piece of software!

**Comment by HiramTheHero** [comment]
Looks like this issue is related to this https://github.com/duckdb/duckdb/issues/109?

If so, I apologize for the noise.

**Comment by Mytherin** [comment]
Thanks for the report! It is indeed related to that issue - but not exactly. The reason this happens is that when you delete data in DuckDB the tuples are only marked as deleted. That has several reasons. One is performance (re-organizing data when only a few tuples are deleted is expensive). The other is transactionality/MVCC (we can only physically remove tuples when no other transaction needs it).

We should extend the `ALTER TYPE` separately to correctly handle deleted tuples so feel free to leave this issue.
