### ISSUE TITLE
REGEXP_MATCHES returns wrong results.

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#6581]
### What happens?

Weirdly, REGEXP_MATCH for '[A]' fails to match for a single character.

The first where clause emits no results, the second emits (correctly) two results.

### To Reproduce

```
SELECT word
FROM (SELECT UNNEST(['FLASH','TOAST','BELL' ]) as word)
WHERE REGEXP_MATCHES(word, '[A]')
-- WHERE REGEXP_MATCHES(word, '[AS]')
```

### OS:

linux

### DuckDB Version:

0.7.1

### DuckDB Client:

cli

### Full Name:

lloyd tabb

### Affiliation:

google

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Ah it gets wrongly optimized to use `contains`:
```
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #1            │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   contains(word, '[A]')   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 1           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           UNNEST          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘ 
```

**Comment by Tishj** [comment]
I've looked into the RE2 library but couldn't find any difference in the produced pattern from `[A]` and `A` - so we can't use that to differentiate between the two cases.
We can just check if it's 3 characters and start with `[` and ends with `]`, but that feels a little too hardcoded?
Though I'm pretty sure that will work

**Comment by Mytherin** [comment]
> I've looked into the RE2 library but couldn't find any difference in the produced pattern from `[A]` and `A` - so we can't use that to differentiate between the two cases.
> We can just check if it's 3 characters and start with `[` and ends with `]`, but that feels a little too hardcoded?
> Though I'm pretty sure that will work

I don't think this will work - any brackets with three entries will lead to RE2 returning a literal/literal string. For example, this also has the same problem:

```sql
SELECT word
FROM (SELECT UNNEST(['FLASH','TOAST','BELL' ]) as word)
WHERE REGEXP_MATCHES(word, '[A][S]');
```

I would instead use `PossibleMatchRange` to extract the literal. That should return the `min/max` values for the regex (which should be equivalent for a literal expression)

**Comment by Mytherin** [comment]
Some more test cases:

```sql
SELECT word
FROM (SELECT UNNEST(['FLASH','TOAST','BELL' ]) as word)
WHERE REGEXP_MATCHES(word, '[AAAA]')
```

```sql
SELECT word
FROM (SELECT UNNEST(['FLASH','TOAST','BELL' ]) as word)
WHERE REGEXP_MATCHES(word, '[A-A]')
```
