### ISSUE TITLE
[Nodejs] Considerable memory usage above memory_limit

### ISSUE THREAD

**Issue by vimota** [duckdb/duckdb#6607]
### What happens?

Node.js Duckdb bindings use much more memory than expected (compared to the same queries in DuckDB CLI) despite setting memory_limit. It also seems to grow during the queries but then not get brought back down (memory leak?). This makes it hard to control how much a service running embedded duckdb will use of resources.

In the reproduction below, I generate a sample dataset, set the memory limit to 1GB and then query against it. Obviously, this is a forced example (I'm trying to do a clean reproduction of the production service I implemented that ends up using even more memory), but in this case I see memory go up to 2GB and sometimes beyond. 

### To Reproduce

Run `NODE_ENV=production yarn run tsc -p tsconfig.build.json && node dist/server_repro.js` using this typescript file : 
https://gist.github.com/vimota/0d00e59703bae1cc62cc0d4d16a5d32b (as server_repro.ts)
with these node configs: https://gist.github.com/vimota/5eb6e93e065b6ac972e8fe4932377412 

Then make a few GET requests to `localhost:8080/repro/test` while monitory htop.

### OS:

Debian Bullseye (but also tested on MacOS 13.2)

### DuckDB Version:

0.7.1

### DuckDB Client:

Nodejs

### Full Name:

Victor Mota

### Affiliation:

Pinchedio

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by goober** [comment]
I have seen possible memory leaks in the golang library as well when we parse parquet files. I have created a reproducible build that shows a python implementation and a golang implementation side-by-side that can be found here: https://github.com/goober/duckdb-memory-leak

I post it here if they could be related.

**Comment by vimota** [comment]
I was able to reproduce this difference between the Python and Nodejs bindings:

[Nodejs + duckdb bindings](https://gist.github.com/vimota/23f40bca01593a3731c37779dc00cb9c) and  [Nodejs + duckdb-async](https://gist.github.com/vimota/67c145c1ce0bdec756a289c1f38cb4ed)  - both peak and stabilize at around 3.7GB on my M1 Pro 16GB ram
[Python + duckdb](https://gist.github.com/vimota/1735ed29bcce83695f170192501bac75) - peaks at around 2.6GB on my M1 Pro 16GB ram

**Comment by renatocron** [comment]
[nodejs binding, duckdb@0.8.1]

I'm also seeing numbers above the limit, but what is weird to me is that is not possible to make the memory go away, after they are allocated, they stay allocated, even if the usage decrease (according to `PRAGMA database_size`)

After calling `db.close()` and setting the duckdb object undefined and calling the GC, the nodejs continues with the memory allocated.

The memory when the process start is 100MB, after running duckdb query, it goes to 1.1GB, then down to 1.0GB after GC, but not get lower than that. This is ~ 4x what the duckdb reports the usage.

```
After creating pulling some data using POSTGRES_SCAN_PUSHDOWN [
  {
    database_name: 'baseduck1689169631454',
    database_size: '0 bytes',
    block_size: 262144,
    total_blocks: 0,
    used_blocks: 0,
    free_blocks: 0,
    wal_size: '19KB',
    memory_usage: '36KB',
    memory_limit: '26.8GB'
  }
]
Import CSV with 1_570_456 rows, 127MB [
  {
    database_name: 'baseduck1689169631454',
    database_size: '18.0MB',
    block_size: 262144,
    total_blocks: 69,
    used_blocks: 69,
    free_blocks: 0,
    wal_size: '0 bytes',
    memory_usage: '17.3MB',
    memory_limit: '26.8GB'
  }
]
[ { 'count(DISTINCT bigint_column)': 12180 } ]
Just running a count distinct to check if the memory increase [
  {
    database_name: 'baseduck1689169631454',
    database_size: '18.0MB',
    block_size: 262144,
    total_blocks: 69,
    used_blocks: 69,
    free_blocks: 0,
    wal_size: '0 bytes',
    memory_usage: '17.8MB',
    memory_limit: '1.0GB'
  }
]
After create creating a temporary table with intermediate results (could be a CTE, but increases the mem-usage) [
  {
    database_name: 'baseduck1689169631454',
    database_size: '33.2MB',
    block_size: 262144,
    total_blocks: 127,
    used_blocks: 124,
    free_blocks: 3,
    wal_size: '0 bytes',
    memory_usage: '141.3MB',
    memory_limit: '1.0GB'
  }
]
after query with some CTE and group-by (removed OVER() because it would use much more ram) [
  {
    database_name: 'baseduck1689169631454',
    database_size: '33.2MB',
    block_size: 262144,
    total_blocks: 127,
    used_blocks: 124,
    free_blocks: 3,
    wal_size: '0 bytes',
    memory_usage: '222.0MB',
    memory_limit: '1.0GB'
  }
]
after drop the table [
  {
    database_name: 'baseduck1689169631454',
    database_size: '33.2MB',
    block_size: 262144,
    total_blocks: 127,
    used_blocks: 124,
    free_blocks: 3,
    wal_size: '27 bytes',
    memory_usage: '204.9MB',
    memory_limit: '1.0GB'
  }
]
```



For far, my is is to call process.exit(0) after processing each task when the system is idle.

I also managed to reduce the chances to uncontrolled OOM by splitting the rows into smaller batches, slower but safer

```
Save CSV imported [
  {
    database_name: 'baseduck1689170133811',
    database_size: '18.0MB',
    block_size: 262144,
    total_blocks: 69,
    used_blocks: 69,
    free_blocks: 0,
    wal_size: '0 bytes',
    memory_usage: '17.3MB',
    memory_limit: '26.8GB'
  }
]

[ { Count: 12180 } ]
After Count distinct [
  {
    database_name: 'baseduck1689170133811',
    database_size: '18.0MB',
    block_size: 262144,
    total_blocks: 69,
    used_blocks: 69,
    free_blocks: 0,
    wal_size: '195KB',
    memory_usage: '22.6MB',
    memory_limit: '1.0GB'
  }
]

after creating a new table preparing the batches [
  {
    database_name: 'baseduck1689170133811',
    database_size: '18.0MB',
    block_size: 262144,
    total_blocks: 69,
    used_blocks: 69,
    free_blocks: 0,
    wal_size: '195KB',
    memory_usage: '22.8MB',
    memory_limit: '1.0GB'
  }
]

{ group_number: 0 }
after running the group by query [
  {
    database_name: 'baseduck1689170133811',
    database_size: '22.2MB',
    block_size: 262144,
    total_blocks: 85,
    used_blocks: 82,
    free_blocks: 3,
    wal_size: '0 bytes',
    memory_usage: '53.4MB',
    memory_limit: '1.0GB'
  }
]

after drop:

    memory_usage: '54.7MB',
    memory_limit: '1.0GB'

{ group_number: 1 }

after create my result [
    memory_usage: '66.8MB',
    memory_limit: '1.0GB'
after query, before drop [
    memory_usage: '41.6MB',
    memory_limit: '1.0GB'

{ group_number: 2 }

    memory_usage: '60.4MB',
    memory_limit: '1.0GB'

    memory_usage: '42.4MB',
    memory_limit: '1.0GB'

{ group_number: 3 }

    memory_usage: '69.0MB',
    memory_limit: '1.0GB'

    memory_usage: '82.5MB',
    memory_limit: '1.0GB'

{ group_number: 4 }

    memory_usage: '94.4MB',
    memory_limit: '1.0GB'

    memory_usage: '41.6MB',
    memory_limit: '1.0GB'

{ group_number: 5 }

    memory_usage: '55.3MB',
    memory_limit: '1.0GB'

    memory_usage: '41.6MB',
    memory_limit: '1.0GB'

...

{ group_number: 12 }

    memory_usage: '52.6MB',
    memory_limit: '1.0GB'

    memory_usage: '54.7MB',
    memory_limit: '1.0GB'

After all batches and drop the main table [
  {
    database_name: 'baseduck1689170133811',
    database_size: '25.6MB',
    block_size: 262144,
    total_blocks: 98,
    used_blocks: 73,
    free_blocks: 25,
    wal_size: '10.6MB',
    memory_usage: '34.8MB',
    memory_limit: '1.0GB'
  }
]
```

Node still peak at 800MB, then goes to 792MB, and stay, but at least the duckdb engine has more room to work
