### ISSUE TITLE
unexpected result in window function with IGNORE NULLS

### ISSUE THREAD

**Issue by xayjin** [duckdb/duckdb#6635]
### What happens?

While using window function with IGNORE NULLS, I get unexpected result in duckdb-python and duckdb-CLI. 
I want to get first not-Nullable value in the following rows, using the window function `first` with `IGNORE NULLS`. I have NULL in the final row, so the result should be NULL in the last few rows. The executed result is 0 but not NULL.

### To Reproduce

```
import duckdb
con=duckdb.connect()
con.execute("CREATE TABLE IF NOT EXISTS t1(index INTEGER, data INTEGER);")
con.execute("insert into t1 values (1,1),(2,2),(3,NULL),(4,NULL),(5,5),(6,NULL),(7,NULL);")
con.execute("select *,(first(data IGNORE NULLS)  over(order by index rows between 1 FOLLOWING and UNBOUNDED FOLLOWING)) as data_next_not_null from t1").df()
```
execute and get result:
```
   index  data  data_next_not_null
0      1   1.0                 2.0
1      2   2.0                 5.0
2      3   NaN                 5.0
3      4   NaN                 5.0
4      5   5.0                 0.0
5      6   NaN                 0.0
6      7   NaN                 NaN
```
but the row 5-7 (by index) should to be NaN, expected result supposed to be:
```
   index  data  data_next_not_null
0      1   1.0                 2.0
1      2   2.0                 5.0
2      3   NaN                 5.0
3      4   NaN                 5.0
4      5   5.0                 NaN
5      6   NaN                 NaN
6      7   NaN                 NaN
```

### OS:

Debian x64

### DuckDB Version:

duckdb-0.7.1-cp39-cp39-manylinux_2_17_x86_64 and duckdb-0.7.2.dev457-cp39-cp39-manylinux_2_17_x86_64

### DuckDB Client:

Python

### Full Name:

alex yang

### Affiliation:

free occupation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Interestingly PG does not support `IGNORE NULLS`.

**Comment by hawkfish** [comment]
`FIRST_VALUE` and `LAST_VALUE` were not handing boundary cases the same way as `NTH_VALUE` (which was correct.)
