### ISSUE TITLE
Crash When Altering Schema

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#6640]
### What happens?

Crash.

### To Reproduce

```sql
ALTER SCHEMA a RENAME TO b; -- segmentation fault
```

### OS:

WSL2-ubuntu22.04 and macOS13.2.1

### DuckDB Version:

duckdb-v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! Altering schema names is not yet supported - but it obviously shouldn't crash. Pushed a fix in #6643
