### ISSUE TITLE
Java使用DuckDB，经常报libc++abi: Attempting to execute an unsuccessful or closed pending query result

### ISSUE THREAD

**Issue by 373260656** [duckdb/duckdb#6652]
### What happens?

jdk: 1.8.0_271
duckdb依赖：
        <dependency>
            <groupId>org.duckdb</groupId>
            <artifactId>duckdb_jdbc</artifactId>
            <version>0.7.1</version>
        </dependency>

问题描述：
     大部分情况下是能正常的，偶尔会报下面的错误，然后java服务的进程会也自动被杀死。
     libc++abi: terminating with uncaught exception of type duckdb::InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result

![Uploading image.png…]()

### To Reproduce

package com.proinnova.accounting.component;

import com.proinnova.accounting.exception.AccountingEnginesException;
import com.proinnova.util.StringUtils;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.sql.*;
import java.util.List;

@Component
@Slf4j
public class DuckDbComponent {

    private static Connection duckdbConn;

    /**
     * 获取 duckdb的连接，只存于内存中经
     * @return
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    public static Connection getDuckDbConnection() throws SQLException, ClassNotFoundException {
        if (duckdbConn == null){
            Class.forName("org.duckdb.DuckDBDriver");
            log.info("=== 初始化 DuckDB 连接 ===");
            duckdbConn = DriverManager.getConnection("jdbc:duckdb:");
        }
        return duckdbConn;
    }

    public static ResultSet getDuckDbResultSet(Statement stmt, String sql) {
        try {
            if (stmt.isClosed()) {
                stmt = duckdbConn.createStatement();
            }
            log.debug("===== DuckDB执行sql：{}", sql);
            if (StringUtils.isNotEmpty(sql)){
                return stmt.executeQuery(sql);
            }
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            log.error("===== DuckDB执行sql：{}", sql);
            throw new AccountingEnginesException(99L, e.getMessage());
        }
    }

    public static void executeSql(Statement stmt, String sql){
        try {
            if (stmt == null || stmt.isClosed()) {
                stmt = duckdbConn.createStatement();
            }
            if (StringUtils.isNotEmpty(sql)){
                stmt.execute(sql);
            }
            log.debug("===== DuckDB执行sql：{}", sql);
        } catch (Exception e) {
            e.printStackTrace();
            log.error("===== DuckDB执行sql：{}", sql);
            throw new AccountingEnginesException(99L, e.getMessage());
        }
    }
}

代码中调用如：

    @Async("threadPoolExecutor")
    public void synGetDuckDBSequenceToMapByElementId(String app, String elementId, String batchNumber) throws SQLException {
        Statement stmtDuck = null;
        ResultSet rs2 = null;
        try {
            log.info("=== 异步 开始查询当前会计引擎 已经创建的 所有 索引 ===");
            // 开始锁
            List<String> dbSequenceList = Lists.newArrayList();
            stmtDuck = DuckDbComponent.getDuckDbConnection().createStatement();
            String sql = "select sequence_name from duckDb_sequences() where sequence_name like '" + elementId + "%'";
            rs2 = DuckDbComponent.getDuckDbResultSet(stmtDuck, sql);
            while (rs2.next()) {
                dbSequenceList.add(rs2.getString("sequence_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (rs2 != null) rs2.close();
        }

大部分情况下是能正常的，偶尔会报下面的错误（10次大概会有2-3次报错），然后java服务的进程会也自动被杀死。
     libc++abi: terminating with uncaught exception of type duckdb::InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result

### OS:

mac OS

### DuckDB Version:

0.7.1

### DuckDB Client:

Java

### Full Name:

Dicky

### Affiliation:

zhang

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hi, thanks for raising an issue! Unfortunately I had to use Google translate to understand it, we'd appreciate it if you could submit issues in English in the future

I've had a go at attempting to reproduce the issue, but so far haven't had any luck on the development DuckDB version. Are you able to try using the dev version in your code, and if you still experience the issue, submit a short single file reproduction?

Thanks!

**Comment by babokim** [comment]
I had same problem too.  m1 MacBook environment is suspected.

**Comment by Mause** [comment]
> I had same problem too. m1 MacBook environment is suspected.

Are you able to provide a self-contained reproduction if you're experiencing the same issue?

**Comment by babokim** [comment]
### Dev OS: 
Apple M1 Max, 13.0.1 (22A400), 32GB

### Production OS:
AWS EKS(k8s)
openjdk:17.0.2-slim image

### DuckDB Version:
0.6.9, 0.7.0, 0.7.1 & master (4a6205db951dea26803532f14e9593f6b29a9b2e)

### DuckDB Client: Java JDBC

### Full Name: 
Hyoungjun Kim

I am making daemon server with duckdb that can run analytic query to S3 parquet file. Here is my development env and production env. While I am developing or testing on my M1 mac, same poblem occurs more than 10 times a day.
There is no problem in the production environment.

**Comment by babokim** [comment]
Here is error trace file
[hs_err.log](https://github.com/duckdb/duckdb/files/10985762/hs_err.log)

**Comment by 373260656** [comment]
Linux system also had same problem , here is system info and error trace file :

Spring Boot ::     v2.2.13.RELEASE
openjdk version "1.8.0_362"
Linux version 4.19.12-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Fri Dec 21 11:06:36 EST 2018
CPU：8
Memory：18G

[accounting-engines-6bc586fbbd-6rbjc_accounting-engines.log](https://github.com/duckdb/duckdb/files/11047949/accounting-engines-6bc586fbbd-6rbjc_accounting-engines.log)

**Comment by 373260656** [comment]
@Mause

**Comment by Stongtong** [comment]
I have similar problem，the operation process is droping origin table firstly, creating table secondly and importing data（the record size is 25 million and 15GB on disk） by parquet file, importing data may trigger linux system kill java process by abrt signal

**Comment by Stongtong** [comment]
> 

duck db version is 0.6.1,  recently plan to upgrade to 0.7.1

**Comment by nsthorat** [comment]
I have the same issue in python when upgrading to 0.7.0 or 0.7.1. I suspect this PR but I don't know duckdb well enough :) 
https://github.com/duckdb/duckdb/pull/5635

**Comment by Mause** [comment]
This should now be resolved

**Comment by O-OF-N** [comment]
Hi I have the exact same issue in 0.10.0 as well. I am using JDBC driver.

**Comment by Mause** [comment]
> Hi I have the exact same issue in 0.10.0 as well. I am using JDBC driver. @Mause 

Please open a new issue with reproduction, this one was resolved

**Comment by jaymmodi** [comment]
Any updates on how to fix this issue with java?
