### ISSUE TITLE
Inconsistencies Found When Comparing Null Values within Rows

### ISSUE THREAD

**Issue by suyZhong** [duckdb/duckdb#6664]
### What happens?

Consider the test case below:

```sql
SELECT (null, 0) > (0, 0);
```
The result value of DuckDB is `true`, whereas other DBMSs (SQLite, MySQL, PostgreSQL) return `null`. 
I notice in the documentation https://duckdb.org/docs/sql/data_types/list#ordering, it is mentioned, 

> NULL values compare greater than all other values and are considered equal to each other.

But in this case, it is not a list. Is this a bug or a deliberate deviation from how other database systems behave?

### To Reproduce

```sql
SELECT (null, 0) > (0, 0); -- expected: null, actual: true
```

### OS:

WSL2-ubuntu22.04

### DuckDB Version:

duckdb-v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
All nested types share the same ordering rules, so I would say this is expected behavior. @hawkfish thoughts?

**Comment by hawkfish** [comment]
There is a conceptual difference between sorting and comparison, and we do not match the PG semantics. So I'd have to agree this is incorrect.

**Comment by hawkfish** [comment]
I take that back - PG appears inconsistent here between anonymous records and defined types:

```sql
hawkfish=# create type type6664 as (v1 integer, v2 integer);
CREATE TYPE
hawkfish=# create table issue6664 (a type6664);
CREATE TABLE
hawkfish=# insert into issue6664 values (row(NULL, 0));
INSERT 0 1
hawkfish=# insert into issue6664 values (row(0, 0));
INSERT 0 1
hawkfish=# select t1.a, t2.a, t1.a > t2.a from issue6664 t1, issue6664 t2;
   a   |   a   | gt 
-------+-------+----
 (,0)  | (,0)  | f
 (,0)  | (0,0) | t
 (0,0) | (,0)  | f
 (0,0) | (0,0) | f
```

which matches our output:

```sql
D create table issue6664 AS  (select * from values ((NULL,0)), ((0,0)) AS t(a));

D select t1.a, t2.a, t1.a > t2.a AS gt from issue6664 t1, issue6664 t2;
|           a           |           a           |  gt   |
|-----------------------|-----------------------|-------|
| {'v1': NULL, 'v2': 0} | {'v1': NULL, 'v2': 0} | false |
| {'v1': 0, 'v2': 0}    | {'v1': NULL, 'v2': 0} | false |
| {'v1': NULL, 'v2': 0} | {'v1': 0, 'v2': 0}    | true  |
| {'v1': 0, 'v2': 0}    | {'v1': 0, 'v2': 0}    | false |
```

Given that there are complaints about PG's treatment of anonymous records as second class types, I think we are good here.
