### ISSUE TITLE
List extract on union type does not return element

### ISSUE THREAD

**Issue by tekumara** [duckdb/duckdb#6678]
### What happens?

List extract from a union type containing a list does not return the whole element.

### To Reproduce

```
D create table t (a json[], u union(arr json[], obj json));
D insert into t(a,u) select [1,2], [3,4];
D select union_tag(u) from t;
┌──────────────┐
│ union_tag(u) │
│              │
├──────────────┤
│ arr          │
└──────────────┘
D select a[1], u[1] from t;
┌──────┬─────────┐
│ a[1] │  u[1]   │
│ json │ varchar │
├──────┼─────────┤
│ 1    │ [       │
└──────┴─────────┘
```
I was expecting `u[1]` to return `3`.

### OS:

macos

### DuckDB Version:

v0.7.1 b00b93f

### DuckDB Client:

duckdb_cli-osx-universal

### Full Name:

Oliver Mannion

### Affiliation:

Xero

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Maxxen** [comment]
Hi! Very happy to see union types being used, but I don't think this is a bug.
So you can't generally apply a function on a union that expects a type that is contained within the union, even if it is the currently active member. What's happening here is that the union gets implicitly converted into a VARCHAR and then indexed.

From the docs:
> UNION types can’t be implicitly cast to any of their member types in general, since the information in the other members not matching the target type would be “lost”. If you want to coerce a UNION into one of its members, you should use the union_extract function explicitly instead.

> The only exception to this is when casting a UNION to VARCHAR, in which case the members will all use their corresponding VARCHAR casts. Since everything can be cast to VARCHAR, this is “safe” in a sense.

What would happen if you did `u[1]` if say one of the member types were an `INTEGER`? You have to explicitly "unwrap" the member you want to access with `array_extract` or dot syntax. 

We've been thinking about adding some way to apply a function on a union in the case where there is an available overload for every member type, but for now you can use the SQL `CASE` expression to handle the different members yourself.

```sql
SELECT CASE 
    WHEN union_tag(u) = 'arr' THEN u.arr[1] 
    WHEN union_tag(u) = 'obj' THEN u.obj -- or whatever you want to in this case? 
    ELSE NULL END AS v 
FROM t;
```
or
```sql
SELECT 
    union_tag(u) AS tag, 
    CASE 
        WHEN tag = 'arr' THEN u.arr[1] 
        WHEN tag) = 'obj' THEN u.obj
        ELSE NULL 
    END AS value 
FROM t;
```

**Comment by tekumara** [comment]
Thank you for the explanation, that makes sense!
