### ISSUE TITLE
export/import downgrading database not working as per docs

### ISSUE THREAD

**Issue by littlegreenbean33** [duckdb/duckdb#6680]
### What happens?

I have pip installed the lasted version of duckdb.
While  trying to use Dbeaver the driver complains that the version of the database is too modern, and incompatible with, in my case 0.7.1.

Following instructions and docs I export the database into a directory. pip uninstall the --pre release and install the lates stable version 0.7.1

I can't import the database anymore as it complains that the single table in the databse already exists.

### To Reproduce

in --pre release

import duckdb
cond = duckdb.connect("duckdb")
cond.execute("export database 'exp")

cond.close()

-------------------------- different session after uninstalling release version
import duckdb
cond=duckdb.connect()
cond.execute("import database 'exp'")
--> CatalogException: Catalog Error: Table with name logs already exists!

### OS:

ubunto 20.04 #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2

### DuckDB Version:

0.7.1

### DuckDB Client:

python/ipython  Python 3.10.6

### Full Name:

Julian Colomina

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by littlegreenbean33** [comment]
actually I just realized the load.sql has 2 identical lines. How this comes to happen is unknown to me

CREATE TABLE logs(id INTEGER, host VARCHAR, ip VARCHAR, fac VARCHAR, prio VARCHAR, llevel VARCHAR, tag VARCHAR, utcsec INTEGER, r_utcsec INTEGER, tzoffset VARCHAR, ldate DATE, ltime VARCHAR, prog VARCHAR, msg VA
RCHAR);
CREATE TABLE logs(id INTEGER, host VARCHAR, ip VARCHAR, fac VARCHAR, prio VARCHAR, llevel VARCHAR, tag VARCHAR, utcsec INTEGER, r_utcsec INTEGER, tzoffset VARCHAR, ldate DATE, ltime VARCHAR, prog VARCHAR, msg VA
RCHAR);

**Comment by Mytherin** [comment]
Thanks for the report! I can't reproduce this on the latest release - from which version of DuckDB where you migrating? It is possible the bug in `EXPORT` has been fixed already.

**Comment by littlegreenbean33** [comment]
I can't reproduce.  This was trying to save a aqlite format database into duck db format  after  some data wrangling.

Because the time format is incompatible I need to load/attach it with all_varchar = true so I cna do a select *......

It was painful to actually make it happen. 

As of now I can't even reproduce the steps I did in order to be able to access the database. I just copied pasted the instructions from the web and not sure what I am doing wrong.


`
(venv) julian@portatilU:~/tmp/syslog/logs$ duckdb test.db
v0.7.1 b00b93f0b1
Enter ".help" for usage hints.
D INSTALL sqlite;
D LOAD sqlite;
D SET GLOBAL sqlite_all_varchar=true;
D attach 'SYNOSYSLOGDB__ARCH.DB' as sys_db;
Error: Invalid Input Error: Initialization function "sqlite_scanner_init" from file "/home/julian/.duckdb/extensions/v0.7.1/linux_amd64/sqlite_scanner.duckdb_extension" threw an exception: "Catalog Error: Table Function with name "sqlite_scan" already exists!"


(venv) julian@portatilU:~/tmp/syslog/logs$ duckdb test.db
v0.7.1 b00b93f0b1
Enter ".help" for usage hints.
D install sqlite_scanner;
D load sqlite_scanner;
D SET GLOBAL sqlite_all_varchar=true;
D attach 'SYNOSYSLOGDB__ARCH.DB' as sys_db;
D select * from sys_db.logs limit 2;
Error: Conversion Error: timestamp field value out of range: "17:44:46", expected format is (YYYY-MM-DD HH:MM:SS[.US][±HH:MM| ZONE])
D 

`

**Comment by littlegreenbean33** [comment]
I've spent an hour trying to repeat my steps but I have not been able to end up with duplicates lines in load.sql and schema.sql

I've gone from 0.7.1 (cli) to/backwards  exporting / importing to

 (python)  duckdb-0.7.2.dev654-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.3 MB)       

which was essentially the setup I was using.    

I will close and eventually reopen if I find myself in the same situation.
