### ISSUE TITLE
Segfault when querying a registered pyarrow table with all null column

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#6682]
### What happens?

This is a tough one.

When I execute an ibis expression that contains a pyarrow table with all null columns, the execution *sometimes* segfaults using the reproduction script:

```
❯ python ~/tmp/segfault.py 10000
<module 'duckdb' from '/home/cloud/src/duckdb/tools/pythonpkg/build/lib.linux-x86_64-cpython-311/duckdb.cpython-311-x86_64-linux-gnu.so'>
 37%|████████████████████████████████████████████████████████████████████                                                                                                                   | 3720/10000 [00:27<00:50, 124.29it/s]
zsh: segmentation fault (core dumped)  python ~/tmp/segfault.py 10000
```

Unfortunately, after many hours of trying I wasn't able to reproduce the problem with only pyarrow and duckdb 😞.

However, I spent a bunch of time digging around why this might be happening and there are perhaps some useful pieces of information here:

### Segfaults always happen in the same place

- When the segfault does happen, it's always on [this line](https://github.com/duckdb/duckdb/blob/master/src/function/table/arrow_conversion.cpp#L33) in `GetValidityMask`.

This led me to wonder whether the bug is data dependent and indeed, I was only able to reproduce this issue with a pyarrow table that has columns that are `null` typed.

### Null typed arrow arrays do not have any buffers allocated

According to [the arrow spec for null column layout](https://arrow.apache.org/docs/format/Columnar.html#null-layout), **there are no buffers allocated**.

Notably, `GetValidityMask` seems to ignore this fact and on [the line that reproduces the problem](https://github.com/duckdb/duckdb/blob/master/src/function/table/arrow_conversion.cpp#L33) there are reads of ostensibly unallocated (perhaps just uninitialized?) memory. Such reads I believe are undefined behavior, and if that's true it's not surprising that the crash is not reproducible.

Additionally, the value of the `n_buffers` field of the incoming `ArrowArray` is `0`. This is consistent with the arrow spec, though the C data interface docs aren't explicit about the meaning of the value in the null case.

### Solution

If all this is true I realize that I could perhaps open a pull request. I didn't do that because I'm not sure what the right solution is.

Should DuckDB simply ignore calls to `GetValidityMask` if the arrow type is `null`? Should that be a check of `n_buffers` (to avoid having to thread type information around) or should DuckDB check the type?

Anyway, I will happily open a PR to fix this if someone can provide guidance on an appropriate solution!

### To Reproduce

First, install ibis:

- `pip install ibis-framework[duckdb]`

Then download the `ibis_testing4.ddb` database, which was generated with duckdb master:

https://storage.googleapis.com/ibis-testing-data/ibis_testing4.ddb

Then run this script with an argument value of at least 10000, possibly more. The segfault is hard to predict, but it is reliable over time.

```
#!/usr/bin/env python3

import argparse
import ibis
import pandas as pd
from tqdm import tqdm


def main(ntimes):
    con = ibis.connect("duckdb://ibis_testing4.ddb")

    batting = con.tables.batting[lambda t: t.yearID < 1900][["yearID"]]
    df = pd.DataFrame(
        {
            "notes": [None] * 9,
            "yearID": [1877, 1878, 1879, 1881, 1880, 1882, 1885, 1890, 1899],
        }
    )

    for _ in tqdm(range(ntimes)):
        con.execute(batting.join(ibis.memtable(df), "yearID"))


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("ntimes", type=int)
    args = p.parse_args()

    main(args.ntimes)
```

Run this script on the command line:

```
$ python segfault.py 10000 # perhaps even larger
```

### OS:

NixOS

### DuckDB Version:

0.7.1 is where I discovered the bug, reproduces on master

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by cpcloud** [comment]
Simplified the example a bit.

**Comment by pdet** [comment]
Hi Phillip, thanks for the very detailed investigation.
You are absolutely correct. We should identify these buffers do not exist for the Null Type.
If you want, I'm more than happy to review your PR for that.

The only thing I wonder is how to properly add a test for this. I've tried checking if Python built with the address sanitizer would flag this, but it does not :-(.

I've also tried some different scenarios and was also unsuccessful in segfaulting it.

**Comment by cpcloud** [comment]
I'm not sure about a test either.

I suspect that because the buffers array is being `resize`d, that the memory that used to exist where there are now `nullptr`s still appears valid. Something analogous to this C++ snippet:

```c++
#include <iostream>
#include <vector>

int main(int argc, const char* argv[]) {
  uint8_t x = 42; // ascii for the * character

  // initialize a 2 element vector
  std::vector<uint8_t*> v(3, &x);

  // resize to one element, filling with nullptr
  v.resize(1, nullptr);

  // claims to be size 1
  std::cout << "size: " << v.size() << std::endl;

  // access the third element, should be out of bounds (?)
  auto el = v[2];
  std::cout << std::boolalpha << "el is nullptr: " << (el == nullptr) << std::endl;
  std::cout << "v[2]: " << *el << std::endl;
}
```

Which gives the output:

```
size: 1
el is nullptr: false
v[2]: *
```
