### ISSUE TITLE
Select from fsspec built-in implementation not working

### ISSUE THREAD

**Issue by pdutta777** [duckdb/duckdb#6692]
### What happens?

Using a simple fsspec built-in implementation such as local results in duckdb.IOException (No files found that match the pattern)

### To Reproduce

```python
from fsspec import filesystem
import duckdb

if __name__ == "__main__":
    duckdb.register_filesystem(filesystem("file"))
    sql = "select * from read_csv('file:///Users/pdutta/vscode/duckdb/abc.csv', AUTO_DETECT=True)"
    conn = duckdb.connect(":memory:")
    print(conn.sql(sql).fetchall())
    conn.close()
```

```
Traceback (most recent call last):
  File "/Users/pdutta/vscode/duckdb/abc2.py", line 8, in <module>
    print(conn.sql(sql).fetchall())
duckdb.IOException: IO Error: No files found that match the pattern "file:///Users/pdutta/vscode/duckdb/abc.csv"
```

### OS:

Darwin 22.3.0 arm64

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Partha Dutta

### Affiliation:

Adobe, Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hi, thanks for raising an issue!

Your issue here is that you've registered the filesystem with the default duckdb connection (via duckdb.register_filesystem) instead of on the connection you opened (conn.register_filesystem)

**Comment by pdutta777** [comment]
Ah, thank you. I did not realize that. it is specific to a connection an/or at a global level.
