### ISSUE TITLE
Pandas 2.0.0: Data type 'int64[pyarrow]' not recognized

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#6695]
### What happens?

--- Edit Based on 2.0.0 Release ---

Options changed in the final 2.0.0 release, so the new minimal reproducing code is:
```
import pandas as pd
import numpy as np
import duckdb

DataFrame(np.random.randn(10,20)).to_csv("test6695.csv")
df_pyarrow_backend = pd.read_csv("test6695.csv", dtype_backend="pyarrow")
duckdb.sql("select * from df_pyarrow_backend")
```
> NotImplementedException: Not implemented Error: Data type 'int64[pyarrow]' not recognized

--------- Original ------------------
Receiving the following when using PyArrow storage backend, as described here: https://pandas.pydata.org/pandas-docs/version/2.0/user_guide/pyarrow.html

Error Message: 

> 
> ---------------------------------------------------------------------------
> NotImplementedException                   Traceback (most recent call last)
> Cell In[19], line 30
>      28 with pd.option_context("mode.dtype_backend", "pyarrow"):
>      29     df_2 = pd.read_csv(outputfile, use_nullable_dtypes=True)
> ---> 30     duckdb.execute("select * from df_2").df().head(3)
> 
> NotImplementedException: Not implemented Error: Data type 'int64[pyarrow]' not recognized

### To Reproduce

```
import duckdb
import pandas as pd

print(pd.__version__)
print(duckdb.execute("pragma version").df())

outputfile = "/tmp/data_1.csv"

numrows = 1000
c = 0
data = []
for i in range(numrows):
    data.append({"col": c})
    c+=1

pd.DataFrame(data).to_csv(outputfile)

print("Default Pandas read_csv")
df_1 = pd.read_csv(outputfile)
duckdb.execute("select * from df_1").df().head(3)

print("PyArrow backend, but dtype numpy")
with pd.option_context("mode.dtype_backend", "pyarrow"):
    df_2 = pd.read_csv(outputfile)
    duckdb.execute("select * from df_2").df().head(3)


print("PyArrow backend / dtype pyarrow")
with pd.option_context("mode.dtype_backend", "pyarrow"):
    df_3 = pd.read_csv(outputfile, use_nullable_dtypes=True)
    duckdb.execute("select * from df_3").df().head(3)

```

 
Output in my environment: 
> 2.0.0rc0
>   library_version   source_id
> 0    0.7.2-dev654  6525767cf1
> Default Pandas read_csv
> PyArrow backend, but dtype numpy
> PyArrow backend / dtype pyarrow
> ---------------------------------------------------------------------------
> NotImplementedException                   Traceback (most recent call last)
> Cell In[2], line 31
>      29 with pd.option_context("mode.dtype_backend", "pyarrow"):
>      30     df_2 = pd.read_csv(outputfile, use_nullable_dtypes=True)
> ---> 31     duckdb.execute("select * from df_2").df().head(3)
> 
> NotImplementedException: Not implemented Error: Data type 'int64[pyarrow]' not recognized

### OS:

Windows

### DuckDB Version:

0.7.1 (and duckdb-0.7.2.dev654)

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
I'll leave this here if it helps!

There is a 1 line flag to use pyarrow as a backend, so maybe we can re-run all our tests with/without it?

```python
pandas.options.mode.dtype_backend = 'pyarrow'
```

**Comment by paul-iqmo** [comment]
According to the link above, you need two settings, you also need: `set pd.options.mode.nullable_dtypes = True`

**Comment by 10hith** [comment]
In the same boat here.
Cannot run sql on Pandas dataframe with pyarrow dtypes. 
Which is surprising as I can run sql on a Polars DF without issues. 
I know several of engineers in my team swiftly moving to Pandas 2.0 and would love duckdb release to cover Pandas 2.0 soon.

**Comment by paultiq** [comment]
> In the same boat here. Cannot run sql on Pandas dataframe with pyarrow dtypes. 

My workaround right now is to convert back to a pyarrow Table before querying in Duckdb:

```
data = [{"col": c for c in range(1000000)}]
with pd.option_context("mode.dtype_backend", "pyarrow"):
    df_4 = pd.read_csv(outputfile, use_nullable_dtypes=True)
    # this would fail: 
    # duckdb.execute("select * from df_3").df()

    pa_4 = pa.Table.from_pandas(df_4)
    duckdb.execute("select * from pa_4").df()
```

**Comment by paultiq** [comment]
As a heads up, looks like pandas 2.0 is scheduled for release soon: 
> We are pleased to announce the second release candidate for pandas 2.0.0. If all goes well, we'll release pandas 2.0.0 in about two weeks.
https://github.com/pandas-dev/pandas/releases

**Comment by paultiq** [comment]
[Pandas 2.0.0](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html) released today. They didn't ship the global mode.dtype_backend, but did add engine=pyarrow in various readers. 

I can't reproduce this issue on 2.0.0. 

```
df = pd.read_csv(outputfile, engine="pyarrow")
```

**Comment by paultiq** [comment]
Reopening: the issue still persists, Pandas changed the options in the final release. The new syntax to reproduce the error is: ` pd.read_csv("simpledf.csv", dtype_backend="pyarrow")`. They removed the global mode.dtype_backend mentioned earlier, so to test this, you need to modify each read_xyz call. See 2.0.0 release notes. 

Reproducing code. showing that `engine="pyarrow"` is fine, but `dtype_backend="pyarrow"` results in an error. 

```
# Fast Create using Numpy
import pandas as pd
from pandas import DataFrame
import numpy as np

import duckdb

num_rows = 1000

simpledf = DataFrame(np.random.randn(num_rows,20))

simpledf.to_csv("simpledf.csv")

print(pd.__version__)
print(duckdb.sql("pragma VERSION"))
try:
    print("Testing df_pyarrow_backend")
    df_pyarrow_backend = pd.read_csv("simpledf.csv", dtype_backend="pyarrow")
    #print(df_pyarrow_backend.dtypes)
    duckdb.sql("select * from df_pyarrow_backend")
    print("Passed")

except Exception as e:
    print(f"Error {e} with df_pyarrow_backend")

try:
    print("Testing df_pyarrow_engine")
    df_pyarrow_engine = pd.read_csv("simpledf.csv", engine="pyarrow")
    #print(df_pyarrow_engine.dtypes)
    duckdb.sql("select * from df_pyarrow_engine")
    print("Passed")
except Exception as e:
    print(f"Error {e} with df_pyarrow_engine")
    

try:
    print("Testing df_pyarrow_engine_backend")
    df_pyarrow_engine_backend = pd.read_csv("simpledf.csv", engine="pyarrow", dtype_backend="pyarrow")
    #print(df_pyarrow_engine_backend.dtypes)
    duckdb.sql("select * from df_pyarrow_engine_backend")
    print("Passed")

except Exception as e:
    print(f"Error {e} with df_pyarrow_engine_backend")
```
> Error Not implemented Error: Data type 'int64[pyarrow]' not recognized with df_pyarrow_backend

**Comment by Tishj** [comment]
Yea I'm aware of the lack of pyarrow support, it's being worked on 👍 

If all columns are backed by pyarrow I have a working solution, but Pandas Dataframes can, in some situations, now contain both pyarrow backed as well as numpy backed columns - which is a more difficult case.

Another option would be to convert the pyarrow arrays into numpy arrays when scanning.
If you're in a hurry to have "support" for pyarrow backed dataframes in DuckDB.

But likely you want us to take advantage of the fact that they are pyarrow arrays, so the implementation is going to take a little more time :)

**Comment by paultiq** [comment]
@tishj Tx. I updated only due to changed Pandas 2.0.0 syntax. 

I'm not blocked... my near term solution is to convert any dataframes with pyarrow types to pyarrow tables. I haven't noticed a performance penalty, but I didn't test mixed dtypes, it's just a little added complexity. * I recall something Mytherin mentioned on another thread about pandas forcing single-threading or something like that, so it had me thinking there's a broader benefit here anyway. 

Perhaps DuckDB could do something similar: instead of supporting yet another format, just use the zero-copy `pyarrow.Table.read_pandas()` format, which works?
