### ISSUE TITLE
Unoptimized query / crashing when execution functionally equivalent SQL using BY instead of DISTINCT

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#6709]
### What happens?

In two functionally equivalent SQL queries, one works really nicely while the other is really slow and consumes all available RAM.

Apparently some databases are better optimized to use DISTINCT while others do better with a group BY operation, leading some SQL-generating tools (PRQL in this case) to generate the latter in cases where others might write the former https://github.com/PRQL/prql/issues/292#issuecomment-1086685010.  PRQL does the latter whenever the columns are not all the available columns: https://prql-lang.org/book/language-features/distinct.html.  This results in somewhat more verbose SQL (ick but ok), but also results in remarkably worse execution in duckdb (as detailed in https://github.com/PRQL/prql/issues/2169).  

(The PRQL devs are super nice and had obviously thought a bunch about this too, and may be able share more insight than my limited knowledge of SQL here)

### To Reproduce

see reproducible example in https://github.com/PRQL/prql/issues/2169.  A more minimal, pure SQL query showing this construction instead of the use of `DISTINCT` might be:

```
WITH table_1 AS (
  SELECT
    class,
    ROW_NUMBER() OVER (PARTITION BY class, begins) AS _expr_0
  FROM
    x
)
SELECT
  class,
  COUNT(*) AS n
FROM
  table_1 AS table_0
WHERE
  _expr_0 <= 1
GROUP BY
  class
  ```

### OS:

Linux

### DuckDB Version:

latest

### DuckDB Client:

Python

### Full Name:

Carl Boettiger

### Affiliation:

UC Berkeley

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by max-sixty** [comment]
Thanks a lot @Mytherin — opened https://github.com/PRQL/prql/issues/2182. We had used `ROW_NUMBER` for compatibility but `DISTINCT ON` is nicer as well as faster. And actually `DISTINCT ON` is now #1 on the [SO question](https://stackoverflow.com/questions/3800551/select-first-row-in-each-group-by-group)...

**Comment by Mytherin** [comment]
Closing this as we wont fix this in DuckDB (for now at least)
