### ISSUE TITLE
ODBC client never parsed ini files or take parameters from ODBC DSN

### ISSUE THREAD

**Issue by blackrez** [duckdb/duckdb#6710]
### What happens?

During the implementation of #5355, I found that the config is never passed  (https://github.com/duckdb/duckdb/blob/master/tools/odbc/driver.cpp#L214) when I removed the condition in line https://github.com/duckdb/duckdb/blob/master/tools/odbc/driver.cpp#L177 everything works better. I don't understand why yet but I will continue to investigate.

### To Reproduce

#6486 or #6528 and on my laptop with 

### OS:

*

### DuckDB Version:

*

### DuckDB Client:

odbc

### Full Name:

Nabil Servais

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by blackrez** [comment]
So actually the client just works in memory mode and doesn't support disk file.

**Comment by Mytherin** [comment]
Thanks for looking into it! That indeed looks like a problem. Happy to review a PR.

**Comment by blackrez** [comment]
I will be happy to push a PR but I'm a total newbie in C++. Debugging is very hard for me 😅.

**Comment by Mytherin** [comment]
@maiadegraaf can you double check if this is still an issue?

**Comment by maiadegraaf** [comment]
Yes, will take a look.

**Comment by maiadegraaf** [comment]
Hi @blackrez can you check if this is still an issue with current version of DuckDB?
