### ISSUE TITLE
read_json_auto and read_json(auto_detect=true) fail to handle property name case sensitivities

### ISSUE THREAD

**Issue by jakthom** [duckdb/duckdb#6722]
### What happens?

I am receiving json log files that occasionally have payloads in which both `id` and `Id` properties are represented, like this:

```
{
	"Status": "🦆🦆🦆🦆🦆🦆🦆🦆",
	"event_simpleName": "🦆🦆🦆🦆🦆🦆🦆🦆",
	"ErrorText": "🦆",
	"ConfigStateHash": "🦆🦆🦆🦆🦆🦆🦆",
	"aip": "🦆🦆🦆🦆🦆🦆🦆🦆",
	"SHA256HashData": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆",
	"ConfigBuild": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆",
	"event_platform": "🦆🦆🦆",
	"Entitlements": "🦆",
	"name": "🦆🦆🦆🦆🦆🦆🦆🦆🦆",
	"id": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆",
	"Id": "🦆",
	"EffectiveTransmissionClass": "🦆",
	"aid": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆",
	"CloudErrorCode": "🦆",
	"timestamp": "🦆🦆🦆🦆🦆🦆🦆🦆",
	"cid": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆",
	"TargetFileName": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆"
}
```

This is technically valid json, but when duckdb tries to auto-discover the schema via `read_json_auto` or `read_json(auto_detect=true)` it 💀 ☠️  the 🦆:

```
select * from read_json('sample.json', auto_detect=true);
Error: Binder Error: table "read_json" has duplicate column name "Id"
```

It is completely understandable why this is happening (and my workaround is manually declaring the columns), but it would be awesome if the json extension could retain case sensitivities.

### To Reproduce

Drop this payload into a `sample.json` file:

```
{"Status": "🦆🦆🦆🦆🦆🦆🦆🦆","event_simpleName": "🦆🦆🦆🦆🦆🦆🦆🦆","ErrorText": "🦆","ConfigStateHash": "🦆🦆🦆🦆🦆🦆🦆","aip": "🦆🦆🦆🦆🦆🦆🦆🦆","SHA256HashData": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆","ConfigBuild": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆","event_platform": "🦆🦆🦆","Entitlements": "🦆","name": "🦆🦆🦆🦆🦆🦆🦆🦆🦆","id": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆","Id": "🦆","EffectiveTransmissionClass": "🦆","aid": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆","CloudErrorCode": "🦆","timestamp": "🦆🦆🦆🦆🦆🦆🦆🦆","cid": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆","TargetFileName": "🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆"}
```

And execute:

```
select * from read_json_auto('sample.json');
```

or

```
select * from read_json('sample.json', auto_detect=true)
```

### OS:

macos

### DuckDB Version:

0.7.2

### DuckDB Client:

Using the cli, but would assume all of them

### Full Name:

Jake Thomas

### Affiliation:

Okta

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Hi @jakthom, thanks for the bug report! I don't think the issue here is specific to the JSON reader but is a design choice in DuckDB: Our column names are case-insensitive, so this does not work:
```sql
create table test("id" int, "Id" int);
Error: Catalog Error: Column with name Id already exists!
```

Our JSON reader can disambiguate between the two because it is not case-insensitive, but the resulting column would have to be renamed to `"id2"` for it to be valid in DuckDB.

**Comment by frafra** [comment]
Indeed, I have the same issue with `postgres_attach`.

**Comment by frafra** [comment]
Still valid.
