### ISSUE TITLE
CREATE TABLE ... AS SELECT * FROM ... makes non-nullable fields nullable

### ISSUE THREAD

**Issue by dmoklaf** [duckdb/duckdb#6724]
### What happens?

When copying a table into another, new, table with CREATE TABLE ... AS SELECT * FROM ...,
the non-nullable fields from the source table are converted by DuckDB into nullable fields

### To Reproduce

D CREATE TABLE customer (id INTEGER, name VARCHAR NOT NULL, age REAL NOT NULL);
D DESCRIBE customer;
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ id          │ INTEGER     │ YES     │         │         │       │
│ name        │ VARCHAR     │ NO      │         │         │       │
│ age         │ FLOAT       │ NO      │         │         │       │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘
D CREATE TABLE customer2 AS SELECT * FROM customer LIMIT 0;
D DESCRIBE customer2;
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ id          │ INTEGER     │ YES     │         │         │       │
│ name        │ VARCHAR     │ YES     │         │         │       │
│ age         │ FLOAT       │ YES     │         │         │       │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘

### OS:

MacOS ventura 13.2.1

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

Shell binary client

### Full Name:

Raphael Geronimi

### Affiliation:

Independant

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This is intentional. `CREATE TABLE AS` always creates a table without any constraints. If you want to create a table with constraints then run `CREATE TABLE` first, and then `INSERT INTO` from a query.

**Comment by dmoklaf** [comment]
Thx I understand the logic of this
