### ISSUE TITLE
optimize 'over (partition by x)' performance

### ISSUE THREAD

**Issue by rydeng** [duckdb/duckdb#6728]
### What happens?

I found 'over (partition by x)' is very slow compare with 'group by'. I think only one aggregation calculation is needed in the same partition, since the result of the aggregation calculation in one partition is the same.

### To Reproduce

```python
import pandas as pd
import numpy as np
import time
# generate data
ids = range(0, 3000)
dates = pd.date_range("2017-01-01", "2020-12-31").date
df = pd.concat([pd.DataFrame(
    {
        "id": [i] * len(dates),
        "date": dates,
        "v1": np.random.random(len(dates)),
        "v2": np.random.random(len(dates)),
        "v3": np.random.random(len(dates)),
    }) for i in ids])

import duckdb
con = duckdb.connect()
start = time.time()
test1 = con.query("select date, id, v1, v2, v3, quantile(v1, 0.7) over (partition by id) as sum_v1 from df order by id, date;").df()
print("over time: ", time.time() - start)

start = time.time()
test2 = con.query("""
with cte as
(select id, quantile(v1, 0.7) as sum_v1 from df group by id)

select df.date, df.id, v1, v2, v3, cte.sum_v1
from df join cte
on df.id = cte.id
order by df.id, df.date;""").df()
print("group time: ", time.time() - start)
```

### OS:

linux, x64

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Roy Dennis

### Affiliation:

bq

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This is a degenerate use where each group (`id`) has only one element so creating a window will be a lot slower than hash aggregation. If we knew that this was the case (`id` was unique or something) I suppose we could rewrite the window  query but it's really an edge case with an obvious workaround.

**Comment by rydeng** [comment]
@hawkfish Thanks for your reply. But the id is not unique, and each id has more than one element. This is a case that the window has only one partition by statement, we do not need to calculate once for each row in this partition. We just need to calculate once for each partition. I think this case is common.

**Comment by rydeng** [comment]
If the window has no statement like ```sum(v1) over()``` , it is also slow. In this case, each row actually has the same sum value.

**Comment by Mytherin** [comment]
That can be rewritten to a subquery (`(SELECT SUM(v1) FROM ...)`) - at least if the scan is a simple table scan this should be more efficient.

**Comment by hawkfish** [comment]
> If the window has no statement like `sum(v1) over()`, it is also slow. In this case, each row actually has the same sum value.

This is just a degenerate case equivalent to partitioning by a constant. But it does illustrate the dangers of using `LIST` on a large table!

We have decided that for now we will add the constant frame optimisation to windowed aggregation because this covers more cases (e.g., mixing non-aggregates) and avoids other issues (e.g., choosing optimal hashing algorithms and scalability of the `LIST` aggregate.) There is a larger problem here

**Comment by hawkfish** [comment]
My first pass at this is about 15x faster (0.28s vs 4.2s)

**Comment by dioptre** [comment]
This is still very broken for us. A query what took 1 second in 0.7.1 hangs forever.

The portion of the query that is still broken in 0.8.0 is:
```
,sum(adjusted_amount) over (partition by account_id, class_id order by transaction_date, account_id, class_id rows unbounded preceding) as running_balance
```

**Comment by hawkfish** [comment]
Hi @dioptre  - 

I'm sorry this query has regressed for you. It is a very different query from what we were discussing here (you have an `ORDER BY` clause) so can you file a separate issue?  Please include the scale of the data and the statistics for the fields. Fake data would be very helpful!
