### ISSUE TITLE
Query 21 cause an OOM in DuckDB

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#6733]
### What happens?

using SF30, Query 21 crash DuckDB, it works fine using SF20, I expect the worst case scenario to be a spill to disk, not crash the system

### To Reproduce

I attached a notebook that reproduce the issue

https://github.com/djouallah/Testing_BI_Engine/blob/main/Database/TPCH_DuckDB_30_2_cores.ipynb

### OS:

Linux

### DuckDB Version:

0.7.2.dev832

### DuckDB Client:

Python

### Full Name:

Mimoune Djouallah

### Affiliation:

Personal 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by djouallah** [comment]
using the latest update, at least now, it does not crash colab notebook, instead I get this error

Out of Memory Error: failed to pin block of size 262144

**Comment by djouallah** [comment]
i feel, it maybe something else, the query spill to disk, write two temporary files then stop working ?

**Comment by lnkuiper** [comment]
It is not something else. What happens is that query 21 has a pipeline with more than one join hashtable, which both need to spill to disk. The join hashtables try not to take up all available memory, but are not aware of each others memory usage, and therefore take up more memory than there is available, causing the OOM exception.

**Comment by djouallah** [comment]
@lnkuiper it will be really nice if duckdb don't segfault and just generate an error and move on to the next query :)

**Comment by djouallah** [comment]
I notice a better performance recently, but strangely Query 21 works fine when running from parquet but not from the native storage
see example here
https://colab.research.google.com/drive/1ybdfVJdZq5HVRwm7J9OjbLXxYwyaqOdc#scrollTo=IH5Py0H65HXg

**Comment by djouallah** [comment]
not too dad now :) SF30 using Parquet, good work
