### ISSUE TITLE
Cannot add columns to table with indices. 

### ISSUE THREAD

**Issue by stepan-anokhin** [duckdb/duckdb#6737]
### What happens?

It is impossible to add a **new** column to a table if indexes are defined for that table.

### To Reproduce

```sql
CREATE TABLE test (a VARCHAR PRIMARY KEY, b INTEGER);
CREATE INDEX test_b on test(b);
ALTER TABLE test ADD COLUMN c VARCHAR;
```
```
Error: Dependency Error: Cannot alter entry "test" because there are entries that depend on it.
```

### OS:

Linux

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Stepan Anokhin

### Affiliation:

Atlan

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by stepan-anokhin** [comment]
@Tishj thanks for suggestion! Unfortunately, not all of the columns of interest should have `UNIQUE` constraint. So this workaround won't work for us.

**Comment by Tishj** [comment]
Not all of the columns have to be coveres by a constraint, the constraints just need to be presebt at table creation

**Comment by Tishj** [comment]
> I'm not sure if this is the same issue, but this also produces the error message:
> 
> ```sql
> create table a (i int primary key, j int);
> create index i on a (j);
> create table b (i int references a (i)); -- This can't be done due to the index i on a
> ```
> 
> Let me know if you prefer I create a new issue.

Can confirm it's an issue on master as well, I think bundling it with this issue sounds fine
```
D create table a (i int primary key, j int);
D create index i on a (j);
D create table b (i int references a (i));
Error: Dependency Error: Cannot alter entry "a" because there are entries that depend on it.
```

**Comment by lukaseder** [comment]
Here's another case that makes this problem quite annoying:

```sql
create table a (i int primary key, j int);
create table b (i int references a (i));
create index i on a(j);
drop table b;
```

I cannot drop the table `b` now because of this error:

> SQL Error: Dependency Error: Cannot alter entry "a" because there are entries that depend on it.

**Comment by edarin** [comment]
A current workaround I'm using: delete the index, create the column, recreate the index.

**Comment by ml31415** [comment]
I'd like to add: This issue currently kills any straight forward use of `sqlalchemy`s `metadata.create_all()`, as the indices for a table are created right after the table. So any subsequent table creation with a foreign key in one of the previously created tables fails.

**Comment by ml31415** [comment]
I just checked with 1.0. Seems to be working now. Good to close I guess.

**Comment by Tishj** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/12226
