### ISSUE TITLE
CSV parser regression

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#6742]
### What happens?

https://github.com/duckdb/duckdb/pull/5757 introduced changes to the default types the CSV parser considers so the parsed files are a lot larger than they used to be.

To overcome these issues, DuckDB should consider implementing https://github.com/duckdb/duckdb/discussions/6556 or https://github.com/duckdb/duckdb/discussions/6555. 

### To Reproduce

Create a table from a CSV file. 

### OS:

macOS

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Dominik Moritz

### Affiliation:

CMU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Yes, #6555 sounds good

**Comment by domoritz** [comment]
Sweet. I think both are great features and could coexist but this one addresses the issue in the CSV parser more directly.
