### ISSUE TITLE
TypeError: stream is not async iterable

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#6743]
### What happens?

When trying to iterate over the result of `arrowIPCStream`, I get an `TypeError: stream is not async iterable`.

CC @Mause

### To Reproduce

```js
s = con.arrowIPCStream('SELECT * FROM penguins')

const chunks = [];
for await (const chunk of stream) {
    chunks.push(chunk);
}
```

### OS:

macOS

### DuckDB Version:

0.7.1

### DuckDB Client:

Node

### Full Name:

Dominik Moritz

### Affiliation:

CMU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you confirm that you loaded the arrow extension first?

If you did, could you provide a complete code reproduction, including if you're using typescript and which node version

**Comment by Mause** [comment]
Okay, had a quick look myself - you're correct with the PR you submitted, the method returns a promise that should be first resolved before you can iterate.

Thanks for raising this!
