### ISSUE TITLE
Copy To Parquet performance 0.6.1 vs 0.7.1

### ISSUE THREAD

**Issue by alltonp** [duckdb/duckdb#6753]
### What happens?

Firstly, thank you for amazing DuckDb!

I've just upgraded to 0.7.1 and noticed that when doing a COPY TO parquet, I'm seeing significantly different performance vs 0.6.1

I am unfortunately not able to share the source files, but if I'm doing something stupid or/and there are some diagnostics I can run, please let me know.

Many thanks
Paul

### To Reproduce

Given a 10GB file (10,000,000 rows) and executing the statement:

```
COPY (SELECT * FROM sometable) TO 'some.parquet' (FORMAT 'parquet');
```

```
0.6.1 ->   677,261 ms
0.7.1 -> 8,603,791 ms
```

With a smaller file 350Mb file (700,000 rows)

```
0.6.1 ->  16,932 ms
0.7.1 -> 284,764 ms
```

### OS:

Windows

### DuckDB Version:

0.7.1

### DuckDB Client:

Java

### Full Name:

Paul Allton

### Affiliation:

Independent Consultant

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I can indeed see a difference in performance, albeit much smaller (4.5s vs 7s for writing 6M rows). We will investigate.

**Comment by Admolly** [comment]
After doing some testing, it looks like write performance between versions varies alot depending on the data types that are being written.  For 0.5.1/0.6.1/0.7.1 I notice practically no difference for writing INTs, the performance degrades dramatically for 0.7.1 when the table consists purely of VARCHARs.  Have not tested any other data types yet.

**Comment by alltonp** [comment]
Thank you for looking into this Admolly & Mytherin

That's very interesting. 

In the examples given above, both files contained 130 columns, all of which are VARCHAR.

**Comment by alltonp** [comment]
Awesome, thank you for fixing this
