### ISSUE TITLE
JDBC adapter does not handle Date-typed parameters

### ISSUE THREAD

**Issue by cannstandard** [duckdb/duckdb#6761]
### What happens?

Trying to pass a DATE type parameter to a query results in "Unknown target type 91"

``` :stacktrace
 ["org.duckdb.DuckDBPreparedStatement.setObject(DuckDBPreparedStatement.java:687)"
  ...
 :card_id nil,
 :context :ad-hoc,
 :error "Unknown target type 91",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}
```

It looks like `Types.DATE` is not handled by this switch statement, only `Types.TIMESTAMP`

### To Reproduce

Execute `SELECT ? as test` with a `Types.DATE` parameter.

Sorry I cannot give a code snippet, I am encountering this issue indirectly via the Metabase-DuckDB adapter: https://github.com/AlexR2D2/metabase_duckdb_driver/issues/8

### OS:

Linux

### DuckDB Version:

0.6.1

### DuckDB Client:

JDBC

### Full Name:

Mike Ravkine

### Affiliation:

CannStandard

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This was implemented in https://github.com/duckdb/duckdb/pull/10408
