### ISSUE TITLE
CSV loader has problems when some rows have fewer columns than the header row

### ISSUE THREAD

**Issue by shreeve** [duckdb/duckdb#6764]
### What happens?

Suppose I have this CSV file:

```csv
one,two,three,four
1,a,alice
2,b,bob
```

And I import it with the following command:

```
select * from read_csv_auto('tables/foo.csv', all_varchar=true, header=true);
```

I'll get the following result:

```
┌─────────┬─────────┬─────────┐
│    1    │    a    │  alice  │
│ varchar │ varchar │ varchar │
├─────────┼─────────┼─────────┤
│ 2       │ b       │ bob     │
└─────────┴─────────┴─────────┘
```

Notice that this didn't produce what was expected. It didn't read the header properly and the rows are messed up.

The reason is that one or more rows had fewer columns than the header row.

If I add a comma to the rows, so they have the same number of columns as the header, then I have this:

```csv
one,two,three,four
1,a,alice,
2,b,bob,
```

Now, this produces the correct output:

```
┌─────────┬─────────┬─────────┬─────────┐
│   one   │   two   │  three  │  four   │
│ varchar │ varchar │ varchar │ varchar │
├─────────┼─────────┼─────────┼─────────┤
│ 1       │ a       │ alice   │         │
│ 2       │ b       │ bob     │         │
└─────────┴─────────┴─────────┴─────────┘
```

By adding these extra commas, so each row has the same number of columns, everything works fine.

However, it would be convenient if the CSV loader were able to detect that there are too few columns on any given row and could add `null` columns to fill in the missing ones.

### To Reproduce

See the main body of the issue, above.

### OS:

macOS

### DuckDB Version:

0.71

### DuckDB Client:

duckdb_cli

### Full Name:

Steve Shreeve

### Affiliation:

Trust Health

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

The issue here is that the file is an invalid CSV file, but has a valid CSV file inside of it. Namely, this is a valid CSV file:

```csv
1,a,alice
2,b,bob
```

DuckDB's CSV reader supports skipping rows from the top using the `skip` option, and the auto-detect feature of DuckDB automatically sets the `skip` option if there are rows at the top of the file that do not conform to the rest of the CSV. In this case, only the valid subset of the CSV file is parsed.

If we parse the file with `read_csv` then an invalid input error is thrown instead:

```sql
select * from read_csv('test.csv', all_varchar=true, header=true, columns={'one': 'varchar', 'two': varchar, 'three': varchar, 'four': varchar}, sep=',');
-- Error: Invalid Input Error: Error in file "test.csv" on line 3: expected 4 values per row, but got 3.
```

The main issue I found here is that the user cannot override the `skip` option of the auto-detector currently, which I have pushed a fix for in #6765.

We could consider adding a flag for allowing extra columns and padding with NULLs in the CSV reader as well, which would provide the desired behavior when parsing this file.

**Comment by shreeve** [comment]
Wow, thank you @Mytherin for the quick and thorough reply!

Your fix for overriding the `skip` option looks great.

For the additional flag, it would be helpful to have the ability to pad with NULLs if some rows are missing columns on the right end (pad=true maybe?, or pad=NULL, or pad=''). In this case, it would be nice to request to pad to the same number of columns as the header row, instead of having to explicitly specify the number of columns to pad. In the case when there are *extra* columns, those seem like an error because they would have no header column, although you already have the option to load CSV data without headers anyway, so not sure how to handle that case.

Regarding data with these missing columns on the far right, they come up frequently when we are dumping values from a spreadsheet (even Google Sheets) to a CSV file. If the user doesn't populate the rightmost cells, they won't be present in the CSV export for those rows.

Here's some code I added to pad the data itself, if you add the padding, then this type of fix won't be needed:

https://github.com/shreeve/googlesheets/blob/fee00f21fcb0f8b12cab7359614ebc566d387e8e/bin/shat#L35-L42

The name of the file expresses the concept of "dumping a sheet", which "shat" seemed to be a potential past tense for... ;-)

**Comment by shreeve** [comment]
@Mytherin - On a related note, since `duckdb` is insanely amazing at pulling in data from many sources, and given that Google Sheets is extremely widespread as a way for many non-technical people to store their data, what do you think about the possibility of adding support for reading data from Google Sheets, directly? The code I mentioned above is from a Ruby library I wrote called, creatively, `googlesheets`. Assuming the authentication were already handled, then data could be loaded directly via something like: `SELECT * FROM read_parquet('https://docs.google.com/spreadsheets/d/PU68MMYauxYnbeo9pv7HdL1oDApTgT6mcEiiPZI9ZRuQ/edit#gid=625299712!B6:H');`. This would pull the data from that spreadsheet directly in as if it were exported to CSV first. Notice that the URL refers to a spreadsheet (the base url) as well as the specific worksheet (the 625299712) and a rectangular area from which to extract the data (the "B6:H" for the rectangle from cell B6 through the end of column H).

This could make it a breeze to interop with all of the people that have data for us to process, but it's quite tedious to "pull it out" and export, convert, import, etc. This would be a one-stop shop, and Google already has robust API's for doing this (see the ruby gem). Anyway, just an idea... thank you for duckdb, it's AMAZING!

**Comment by shreeve** [comment]
@Mytherin - Regarding google sheets, I just saw this extension for SQLite that does something similar, https://github.com/0x6b/libgsqlite

**Comment by Alex-Monahan** [comment]
> @Mytherin - Regarding google sheets, I just saw this extension for SQLite that does something similar, https://github.com/0x6b/libgsqlite

Ah, neat!

You could also do a double hop today: google sheets to SQLite, then attach SQLite to DuckDB and query!

**Comment by Mytherin** [comment]
After looking into this some more I made a number of modifications to https://github.com/duckdb/duckdb/pull/6765 so that we have a dedicated `null_padding` option which defaults to true. That should fully solve the issue.

> what do you think about the possibility of adding support for reading data from Google Sheets, directly?

That is definitely an interesting idea for an extension. While it is still the early days we do allow people to create their own extensions as well - although the languages in which you can do this are currently limited. See [e.g. here](https://github.com/duckdb/extension-template).
