### ISSUE TITLE
DuckDB JDBC Driver doesn't seem to support column name/label for PreparedStatemetns

### ISSUE THREAD

**Issue by jexp** [duckdb/duckdb#6767]
### What happens?

jbang run duck
[jbang] Building jar...
// stmt.execute("select 42 as result");
label: result name: result
Got: 42
// psmt.executeQuery("SELECT ? AS result");
label: unknown name: unknown
Exception in thread "main" java.sql.SQLException: Could not find column with label result
	at org.duckdb.DuckDBResultSet.findColumn(DuckDBResultSet.java:445)
	at org.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:481)
	at duck.handleResult(duck.java:31)
	at duck.main(duck.java:22)

### To Reproduce

///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.duckdb:duckdb_jdbc:0.7.1

import static java.lang.System.*;
import java.sql.*;

public class duck {

    private static String QUERY = """
        SELECT ? as result
    """;
    public static void main(String... args) throws Exception {
        try (var conn = DriverManager.getConnection("jdbc:duckdb:")) {
            try (var stmt = conn.createStatement()) {
                try (var rs = stmt.executeQuery("SELECT 42 AS result")) {
                    handleResult(rs);
                 }
            }
            try (var stmt = conn.prepareStatement(QUERY)) {
                stmt.setString(1, args.length > 0 ? args[0] : "Quack");
                try (var rs = stmt.executeQuery()) {
                    handleResult(rs);
                 }
            }
        }
    }
    private static void handleResult(ResultSet rs) throws Exception {
        var md = rs.getMetaData();
            out.println("label: "+md.getColumnLabel(1)+ " name: "+ md.getColumnName(1));
            while (rs.next()) {
                var result = rs.getObject("result");
                out.println("Got: "+result);
            }
    }
}

### OS:

OSX

### DuckDB Version:

0.7.1

### DuckDB Client:

Java

### Full Name:

Michael Hunger

### Affiliation:

Neo4j, Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by chengjie0929** [comment]
I think you should develop a sql editor for duckdb. As far as I know, there is one called rill developer, which unfortunately does not support the windows platform. Best wishes!

**Comment by chengjie0929** [comment]
> 我认为你应该为duckdb开发一个sql编辑器。据我所知，有一个叫做 rill developer，不幸的是它不支持 Windows 平台。愿你安好！

I just heard back from the rill development team. They will provide stable, maintainable binary versions of windows in the near future. I wish you all the best, come on!
