### ISSUE TITLE
JSON reader internal error

### ISSUE THREAD

**Issue by tcldr** [duckdb/duckdb#6768]
### What happens?

When attempting to import data from a local JSON file with contents from the Exoplanet Archive API DuckDB raises an internal error: `INTERNAL Error: Unexpected yyjson tag in ValTypeToString`

### To Reproduce

1. Download the json file [here](https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name+,+hostname+,+sy_snum+,+disc_year+,+disc_facility+,+st_mass+,+st_rad+,+st_age+from+PSCompPars&format=json)
2. Execute query `CREATE TABLE exoplanets AS SELECT * FROM read_json_auto('local_file_path');`

### OS:

macOS, Apple Silicon

### DuckDB Version:

master

### DuckDB Client:

Swift

### Full Name:

Tristan Celder

### Affiliation:

DuckDB

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Closed via #7478
