### ISSUE TITLE
INTERNAL Error: Failed to bind column reference when joining tables.

### ISSUE THREAD

**Issue by pstorozenko** [duckdb/duckdb#6778]
### What happens?

Duckdb has `Error: INTERNAL Error: Failed to bind column reference [...]` error on join with larger tables (whole database file - 12GB).

### To Reproduce

In CLI `./duckdb instagram.duckdb`, executing command 
```sql
WITH top_posts AS (
    SELECT *
    FROM posts 
    WHERE numbr_likes IS NOT NULL
    ORDER BY numbr_likes DESC
    LIMIT 20
)
SELECT 
    profiles.firstname_lastname,
    top_posts.post_id,
    numbr_likes,
    top_posts.description AS post_description,
FROM top_posts JOIN profiles
ON top_posts.profile_id=profiles.profile_id
ORDER BY numbr_likes DESC;
```

Results (immediately) in 
```
Error: INTERNAL Error: Failed to bind column reference "numbr_likes" [7.8] (bindings: [15.0 15.1 7.0 7.2 7.3])
```

However if I first create a new table and then use it, all works, i.e.

```sql
CREATE TABLE top_posts AS (
    SELECT *
    FROM posts 
    WHERE numbr_likes IS NOT NULL
    ORDER BY numbr_likes DESC
    LIMIT 20
);
SELECT 
    profiles.firstname_lastname,
    top_posts.post_id,
    numbr_likes,
    top_posts.description AS post_description,
FROM top_posts JOIN profiles
ON top_posts.profile_id=profiles.profile_id
ORDER BY numbr_likes DESC;
```

Works without a problem. I tried creating a `VIEW` and it also raised `INTERNAL Error`.

[I uploaded duckdb database used to google drive to reproduce.](https://drive.google.com/file/d/15sRxXCf6Xgax-jr3uLiS-3c93G3tKVoL/)

If I drop all the unnecessary columns and table:
```sql
DROP TABLE locations;

ALTER TABLE profiles DROP COLUMN sid;
ALTER TABLE profiles DROP COLUMN profile_name;
ALTER TABLE profiles DROP COLUMN description;
ALTER TABLE profiles DROP COLUMN following;
ALTER TABLE profiles DROP COLUMN followers;
ALTER TABLE profiles DROP COLUMN n_posts;
ALTER TABLE profiles DROP COLUMN url;
ALTER TABLE profiles DROP COLUMN cts;
ALTER TABLE profiles DROP COLUMN is_business_account;

ALTER TABLE posts DROP COLUMN sid;
ALTER TABLE posts DROP COLUMN sid_profile;
ALTER TABLE posts DROP COLUMN location_id;
ALTER TABLE posts DROP COLUMN cts;
ALTER TABLE posts DROP COLUMN post_type;
ALTER TABLE posts DROP COLUMN number_comments;
```
query **executes without any problem**.

### Context
This database is based on [the instagram dataset from Kaggle](https://www.kaggle.com/datasets/shmalex/instagram-dataset).
I created tables by running in `duckdb` CLI commands:
```
CREATE TABLE posts AS SELECT * FROM read_csv_auto('data/instagram_posts.csv', delim='\t');
CREATE TABLE locations AS SELECT * FROM read_csv_auto('data/instagram_locations.csv', delim='\t');
CREATE TABLE profiles AS SELECT * FROM read_csv_auto('data/instagram_profiles.csv', delim='\t');
```

Unfortunately I wasn't able to prepare a smaller example as after trimming unused columns everything worked.

Machine with:
```
CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics (16)
RAM: 32GB 
```

### OS:

Ubuntu 22.04.2 LTS x86_64

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Piotr Pasza Storożenko

### Affiliation:

[Appsilon](https://appsilon.com/)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ywelsch** [comment]
I've encountered a very similar (and likely the same) issue on the same DuckDB version (0.7.1). I have a simpler script to reproduce in case that helps debug the issue:

```
INSTALL httpfs;
LOAD httpfs;
CREATE TABLE invoices AS SELECT * FROM
  read_csv_auto('https://raw.githubusercontent.com/PRQL/prql/main/prql-compiler/tests/integration/data/chinook/invoices.csv');
CREATE TABLE customers AS SELECT * FROM
  read_csv_auto('https://raw.githubusercontent.com/PRQL/prql/main/prql-compiler/tests/integration/data/chinook/customers.csv');

WITH e1 AS (from invoices select customer_id, avg(total), sum(total) AS sum_total group by customer_id ORDER BY sum_total DESC LIMIT 10),
     e2 AS (from e1 JOIN customers ON e1.customer_id = customers.customer_id),
     e3 AS (from e2 SELECT customer_id, sum_total)
FROM e3;
```

which returns `Error: INTERNAL Error: Failed to bind column reference "sum_total" [21.2] (bindings: [29.0 21.1])`
