### ISSUE TITLE
JDBC: predicates in DuckDBDatabaseMetaData should not throw

### ISSUE THREAD

**Issue by pjarra** [duckdb/duckdb#6781]
### What happens?

When using the Java bindings and calling a predicate of the meta class, like DuckDBDatabaseMetaData.supportsBatchUpdates():
When the requested feature is not supported, the method currently throws an exception of type SQLFeatureNotSupportedException.
I consider this a bug, as the contract of the interface says that such a method returns true or false and throws only in case of database error - e.g. see https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#supportsBatchUpdates--

I think it's ok to throw in methods which return other than boolean, like getSQLKeywords -> String, when these methods are not implemented yet, and a default return value (in this case empty string?) would suggest a valid result. 
When batch updates are not supported however, then the corresponding predicate can/should simply and correctly return false. This applies to every predicate method of that class (supports*-methods).

### To Reproduce

Call a predicate method in DuckDBDatabaseMetaData, e.g. supportsBatchUpdates().

### OS:

any

### DuckDB Version:

any

### DuckDB Client:

Java

### Full Name:

PJ

### Affiliation:

no affiliation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This seems to be resolved now by yourself @pjarra, feel free to close it if you agree

**Comment by pjarra** [comment]
> This seems to be resolved now by yourself @pjarra, feel free to close it if you agree 

Oops, I wasn't aware I have permissions to close
