### ISSUE TITLE
400 (Bad Request) when SELECTing from Cloudflare R2

### ISSUE THREAD

**Issue by acowlikeobject** [duckdb/duckdb#6786]
### What happens?

`duckdb.IOException: IO Error: Unable to connect to URL "https://<account-id>.r2.cloudflarestorage.com/root/tmp/foo.parquet": 400 (Bad Request)` when trying to `select` from a Clouldflare R2 object.

### To Reproduce

Running the following to select from a Clouldflare R2 object:

```
statements = """
INSTALL httpfs;
LOAD httpfs;
SET s3_region = 'us-east1';
SET s3_access_key_id = '<key-id>';
SET s3_secret_access_key = '<access-key>';
SET s3_endpoint = '<account-id>.r2.cloudflarestorage.com/root';
SET s3_url_style = 'path';
SELECT * FROM 's3://tmp/foo.parquet';
""")
duckdb.sql(statements).to_df()
```

Produces this error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/src/load.py", line 28, in load
    return duckdb.sql(statements).to_df()
duckdb.IOException: IO Error: Unable to connect to URL "https://<account-id>.r2.cloudflarestorage.com/root/tmp/foo.parquet": 400 (Bad Request)
```

The url reported in the error is _exactly_ the url that the Cloudflare R2 UI shows for this object.

Meanwhile, `rclone` works fine with the same configuration:

```
[<config-name>]
    type = s3
    provider = Cloudflare
    access_key_id = <key-id>
    secret_access_key = <access-key>
    endpoint = https://<account-id>.r2.cloudflarestorage.com/root/
    acl = private
```

`rclone copyto <config-name>:tmp/foo.parquet /some/local/path.parquet`

This is my first time using `duckdb` for Cloudflare.  Do I need to do something differently?

### OS:

Debian Bullseye

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Tim Serte

### Affiliation:

Private

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by acowlikeobject** [comment]
I see #6563 from 2 weeks ago that may be the same issue (all S3 HTTPFS selects on `0.7.1` returning `400 (Bad Request)`, and not just Cloudflare).

**Comment by Mause** [comment]
@acowlikeobject can you please test with the latest dev version?

**Comment by acowlikeobject** [comment]
@Mause Tried it on `duckdb-0.7.2.dev899`.  Same error.

Since then, I've also tried reading the partitions with the same settings using `pyarrow.parquet.ParquetDataset`, and that works fine.  So it feels like it's duckdb-specific.  (Plus that other issue saying the same thing.)

**Comment by kamilcglr** [comment]
Hi, I confirm that this issue is not only related to R2. Same problem with S3 from Scaleway and OVH provider.

**Comment by samansmink** [comment]
After some experimentation here, I'm pretty sure this is caused by the misconfigured region:
For R2 the region should be 'auto' always, see https://blog.cloudflare.com/r2-ga/

@acowlikeobject @kamilcglr could you try this out on a recent dev release or current master with the correct region and see if that solves the problem?

Trying this on my machine on r2 it works

**Comment by kamilcglr** [comment]
Hello, @samansmink, thanks for your reply. 

I'm not using Cloudflare R2, but Scaleway S3 and OVH S3. Am I doing something wrong? 

This is what I do:
```sql
INSTALL httpfs;
LOAD httpfs;
SET s3_region='fr-par';
SET s3_access_key_id='my-access-key';
SET s3_secret_access_key='my-secret-key';
SET s3_endpoint='s3.fr-par.scw.cloud';
```

The following command works:
```sql
SELECT * FROM read_parquet('s3://my-archive/day=2023-01-18/sensor_id=1/data_0.parquet');
```

However, this command doesn't work:
```sql
SELECT * FROM parquet_scan('s3://my-archive/day=2023-01-18/sensor_id=1/*.parquet');
```
I get the following error:
`Forbidden
Error: Invalid Error: IO Error: HTTP GET error on 'https://my-archive.s3.fr-par.scw.cloud/?encoding-type=url&list-type=2&prefix=day%3D2023-01-18%2Fsensor_id%3D1%2F' (HTTP 403)`

I also tried with this parameter:
```sql
SET s3_url_style='path';
```

The first request still works, but the second one fails with another error:
`Bad Request
Error: Invalid Error: IO Error: HTTP GET error on 'https://s3.fr-par.scw.cloud/my-archive/?encoding-type=url&list-type=2&prefix=day%3D2023-01-18%2Fsensor_id%3D1%2F' (HTTP 400)`

It also doesn't work with Hive partitioning (I copied my folder with Duck DB copy command).
```sql
SELECT *
FROM parquet_scan('s3://my-archive/*/*/*.parquet', hive_partitioning = 1);
```

The same error occurs.

**Comment by Mause** [comment]
> Hello, @samansmink, thanks for your reply. 
> 
> I'm not using Cloudflare R2, but Scaleway S3 and OVH S3. Am I doing something wrong? 
> 
> This is what I do:
> ```sql
> INSTALL httpfs;
> LOAD httpfs;
> SET s3_region='fr-par';
> SET s3_access_key_id='my-access-key';
> SET s3_secret_access_key='my-secret-key';
> SET s3_endpoint='s3.fr-par.scw.cloud';
> ```
> 
> The following command works:
> ```sql
> SELECT * FROM read_parquet('s3://my-archive/day=2023-01-18/sensor_id=1/data_0.parquet');
> ```
> 
> However, this command doesn't work:
> ```sql
> SELECT * FROM parquet_scan('s3://my-archive/day=2023-01-18/sensor_id=1/*.parquet');
> ```
> I get the following error:
> `Forbidden
> Error: Invalid Error: IO Error: HTTP GET error on 'https://my-archive.s3.fr-par.scw.cloud/?encoding-type=url&list-type=2&prefix=day%3D2023-01-18%2Fsensor_id%3D1%2F' (HTTP 403)`
> 
> I also tried with this parameter:
> ```sql
> SET s3_url_style='path';
> ```
> 
> The first request still works, but the second one fails with another error:
> `Bad Request
> Error: Invalid Error: IO Error: HTTP GET error on 'https://s3.fr-par.scw.cloud/my-archive/?encoding-type=url&list-type=2&prefix=day%3D2023-01-18%2Fsensor_id%3D1%2F' (HTTP 400)`
> 
> It also doesn't work with Hive partitioning (I copied my folder with Duck DB copy command).
> ```sql
> SELECT *
> FROM parquet_scan('s3://my-archive/*/*/*.parquet', hive_partitioning = 1);
> ```
> 
> The same error occurs.

Would you be able to open a new issue for that? R2 now works as expected with its implementation quirks, a new provider will need to be investigated for it's own implementation quirks

**Comment by Mause** [comment]
I think this is solved now - for people coming across this issue in the future, check the output of `select * from duckdb_settings() where name like 's3%'` and make sure the values are what you expect. If they're not, check your environment variables
