### ISSUE TITLE
Casting blob to bit hangs

### ISSUE THREAD

**Issue by brendanyounger** [duckdb/duckdb#6798]
### What happens?

I cannot seem to convert a blob into a bitvector via the SQL interface.

### To Reproduce

Calling `select 'abc'::blob::bit;` appears to hang the duckdb process with CPU pegged to 100%.

### OS:

OS X x64

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Brendan Younger

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Closing as this has already been fixed
