### ISSUE TITLE
"SELECT x FROM table1 JOIN table2(x)" sometimes returns results that aren't in table2

### ISSUE THREAD

**Issue by tmaxwell-anthropic** [duckdb/duckdb#6799]
### What happens?

`SELECT x FROM table1 JOIN table2(x)` sometimes returns results that aren't in `table2`.

Specifically, I can reproduce this when:
1. The optimizer decides to do an INDEX_JOIN on `x`
2. `x` is the only column being selected from the RHS table (`table2`)
3. There are a significant number of results (e.g. tens of thousands)

### To Reproduce

This Python script reproduces the issue for me:

```python
import random

import duckdb
db = duckdb.connect(":memory:")
db.execute("PRAGMA force_index_join")

# Create a table with key-value pairs from 0...100k, but randomly omit 50% of them

random.seed(42)
key_value_pairs = {
    f"key_{i}": f"value_{i}"
    for i in range(100000)
    if random.random() < 0.5
}

db.execute("CREATE TABLE key_value_pairs (key VARCHAR PRIMARY KEY, value VARCHAR)")
db.execute(
    "INSERT INTO key_value_pairs VALUES "
    + ", ".join(f"('{k}', '{v}')" for k, v in key_value_pairs.items())
)

# Create a table with keys from 0...10k

keys_to_lookup = [
    f"key_{i}"
    for i in range(10000)
]

db.execute("CREATE TABLE keys_to_lookup (key VARCHAR PRIMARY KEY)")
db.execute(
    "INSERT INTO keys_to_lookup VALUES "
    + ", ".join(f"('{k}')" for k in keys_to_lookup)
)

# When we join these tables, we expect to find approximately half of the keys in the range 0...9999

expected_results = [
    key
    for key in keys_to_lookup
    if key in key_value_pairs
]
print(f"{len(expected_results)=}")

# A join that returns the "value" column works as expected
    
results_1 = db.execute(
    """
    SELECT key, value
    FROM
        keys_to_lookup
        JOIN key_value_pairs USING(key)
    """
).fetchall()

# This works as expected; len(results_1) == len(expected_results)
print(f"{len(results_1)=}")
for (key, value) in results_1:
    assert key in key_value_pairs

# But a join that omits "value" returns keys that aren't present in key_value_pairs!

results_2 = db.execute(
    """
    SELECT key
    FROM
        keys_to_lookup
        JOIN key_value_pairs USING(key)
    """
).fetchall()

# This does _not_ work as expected; len(results_2) > len(expected_results), and the assertion fails
print(f"{len(results_2)=}")
for (key,) in results_2:
    assert key in key_value_pairs
```

I looked at the DuckDB implementation, and I _think_ I might see what the bug is. DuckDB takes a different code path depending on whether any non-index columns are being fetched from the RHS table or not: https://github.com/duckdb/duckdb/blob/v0.6.1/src/execution/operator/join/physical_index_join.cpp#L167 Specifically, in the "no non-index columns" case, we call `SearchEqualJoinNoFetch`. But if no leaf is found, `SearchEqualJoinNoFetch` returns without modifying `result_size`. And AFAICT, `physical_index_join.cpp` is re-using the `result_sizes` array from batch to batch, without zeroing it between batches. So we'll carry over the value of `result_size` from the last batch. If the last batch found a match at this index, then the current batch will act as though it found at match, even if it didn't.

(Admittedly, I'm very unfamiliar with the DuckDB codebase, and I could have easily misunderstood something!)

### OS:

MacOS 13.2.1 (M1 Pro)

### DuckDB Version:

0.7.2-dev899

### DuckDB Client:

Python

### Full Name:

Tim Maxwell

### Affiliation:

Anthropic

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Interesting behavior:
- Without primary keys, everything indeed runs perfectly as expected: results_1 and results_2 contain only the expected values.
- With only a primary key on keys_to_lookup, but not key_value_pairs, results_1 and results_2 are both invalid... they contain all the values from key_value_pairs. 
- And, with primary keys on both keys_to_lookup and key_value_pairs, only results_2 is invalid

Incidentally, it doesn't matter if you rewrite to a JOIN ON syntax vs JOIN USING, or use an "int" key type.
