### ISSUE TITLE
constant expression in OVER clause ORDER BY causes poor performance

### ISSUE THREAD

**Issue by mhseiden** [duckdb/duckdb#6802]
### What happens?

The query `select row_number() over (order by 1) from lineitem` runs indefinitely at SF1. When the constant order by expression is removed it runs in ~20ms -- `select row_number() over () from lineitem`. While the manual fix is trivial, it seems like a case that DuckDB could detect and eliminate during optimization rewrites.

### To Reproduce

Run `select row_number() over (order by 1) from lineitem` and wait indefinitely.

### OS:

Amazon Linux -- ARM Gravitron3 -- c7g.large

### DuckDB Version:

built from source

### DuckDB Client:

CLI

### Full Name:

Max Seiden

### Affiliation:

Sigma Computing

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Interesting... big differences:

# over (order by columnname)
> 262 ms ± 68.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
import duckdb
with duckdb.connect() as con:
    con.execute("""drop table if exists lineitem;create temp table lineitem as select * from range(1000000) t(x)""")
    %timeit con.execute("""select row_number() over (order by x) from lineitem""").df()
```
# over ()
> 14.5 ms ± 323 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
import duckdb
with duckdb.connect() as con:
    con.execute("""drop table if exists lineitem;create temp table lineitem as select * from range(1000000) t(x)""")
    %timeit con.execute("""select row_number() over () from lineitem""").df()
```
# over (order by 1)
> **18.8 s** ± 527 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
import duckdb
with duckdb.connect() as con:
    con.execute("""drop table if exists lineitem;create temp table lineitem as select * from range(1000000) t(x)""")
    %timeit con.execute("""select row_number() over (order by 1) from lineitem""").df()
```

**Comment by pankajp** [comment]
While this is indeed strange to be so expensive for a constant "literal" value where we intuitively return the same array, I think duckdb's code doesn't have that intuitive optimization. The problem would still occur if the `order by` has a column with constant values. If you add `x` value to the select statement you will see that the order by constant reorders the rows.

Duckdb's implementation seems problematic with many `order by` key collisions, and is quadratic from the timings I obtained.

```
import duckdb
from timeit import default_timer as timer
ns = []
times = []
for i in range(8):
    n = 10000*2**i
    duckdb.sql(f'''drop table if exists lineitem;create temp table lineitem as select x, 1 as y from range({n}) t(x)''')
    t = timer()
    duckdb.sql('''
        select x, row_number() over (order by y) from lineitem
    ''').arrow()
    t = timer() - t
    ns.append(n)
    times.append(t)
    print(n, t)
df = pd.DataFrame({'N':ns, 'T': times})
df.plot.line(x='N', y='T', backend='plotly', log_y=True, log_x=True, markers='lines+points')
```

> 10000 0.005868345499038696
> 20000 0.014532923698425293
> 40000 0.039681874215602875
> 80000 0.13995344936847687
> 160000 0.5528560280799866
> 320000 2.068949267268181
> 640000 8.109156154096127
> 1280000 32.06101816147566

![image](https://user-images.githubusercontent.com/776111/233685557-5eb9a2c6-fdef-4e2c-a69d-00e479968192.png)
