### ISSUE TITLE
On abnormal results of the not operator

### ISSUE THREAD

**Issue by ChenglinTian** [duckdb/duckdb#6804]
### What happens?

When using duck db, we found a problem that was inconsistent with the expected result. When there was only one piece of data in the table, we used the specific values represented by t0. c0 and t0. c0 to query and returned inconsistent data.

### To Reproduce

CREATE TABLE t0(c0 SMALLINT DEFAULT(831652365), c1 BOOL DEFAULT('yxDVG*?'), PRIMARY KEY(c1));
INSERT INTO t0(c1, c0) VALUES (-1486607961, 0.9263986431982463);
ANALYZE;
SELECT t0.c0 FROM t0; --[1]

Statement that triggers a bug：
SELECT t0.c0 FROM t0 WHERE (NOT ((2060771621)=(((t0.c0)+(-2134619525))))); 
expected：[1]
actual:  []

### OS:

Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-144-generic x86_64)

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Chenglin Tian

### Affiliation:

Tianjin University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Slightly simpler reproduction: 

Notes:
- Changing c0 to bigint eliminates the issue
- Casting c0 to bigint also eliminates the issue
- Couldn't reproduce in Postgres 15.0.

```

import duckdb 
with duckdb.connect() as con:
    con.execute("""
    CREATE TABLE t0(c0 SMALLINT);
    INSERT INTO t0(c0) values(1);""")

    df=con.execute("""
        SELECT c0, -- 1                                    
                c0 = 1 as c0_is_one,  -- True
                2=((c0)+(-2147483646)) as two_check, -- False
          not(2=((c0)+(-2147483646))) as not_two_check, -- False ?????
                1=((c0)+(-2147483646)) as one_check,  -- False
         not(1=((c0)+(-2147483646))) as not_one_check -- True
        FROM t0""").df()
    display(df)
    assert df["one_check"].iat[0] == False and df["not_one_check"].iat[0] == True
    assert df["two_check"].iat[0] == False and df["not_two_check"].iat[0] == True
```

**Comment by ChenglinTian** [comment]
Thank you for your suggestion. We solved this problem after converting the data type, so is this a bug

**Comment by Tishj** [comment]
The optimizer is at fault here, when I run this with `pragma enable_verification;` I get:
```
Actual result:
Invalid Error: Unoptimized statement differs from original result!
Original Result:
i
SMALLINT
[ Rows: 0]

Unoptimized:
i
SMALLINT
[ Rows: 1]
1
```
