### ISSUE TITLE
Missing timestamp components for EXTRACT

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6805]
The EXTRACT method on timestamps (and date, time, timestamp_tz) are missing fields:

TIME:
- subsecond

DATE:
- iso_year
- us_year
- day_of_year
- monday_day_of_week
- sunday_day_of_week
- monday_week
- sunday_week
- iso_week
- us_week
- unix_time

TIMESTAMP_TZ:
- timezone_offset

all the fields missing from time or date are also missing from:
TIMESTAMP_SEC
TIMESTAMP_MS
TIMESTAMP_US
TIMESTAMP_NS

Descriptions that provide some more context for these fields/components:
```yml
* SUBSECOND Return number of microseconds since the last full second of the given timestamp.

* ISO_YEAR Return the ISO 8601 week-numbering year. First week of an ISO year has the majority (4 or more) of its
  days in January.
* US_YEAR Return US epidemiological year. First week of US epidemiological year has the majority (4 or more) of
  its days in January. Last week of US epidemiological year has the year's last Wednesday in it.
  US epidemiological week starts on Sunday.
* DAY_OF_YEAR Return the day of year (1 to 366). January 1st maps to day number 1, February 1st to 32, etc.
* MONDAY_DAY_OF_WEEK Return the day of week from Monday (1) to Sunday (7).
* SUNDAY_DAY_OF_WEEK Return the day of week from Sunday (1) to Saturday (7).
* MONDAY_WEEK Return week of year number (1-53). First week starts on first Monday of January.
* SUNDAY_WEEK Return week of year number (1-53). First week starts on first Sunday of January.
* ISO_WEEK Return ISO week of year number (1-53). First ISO calendar week has the majority (4 or more) of its
  days in January. ISO week starts on Monday.
* US_WEEK Return ISO-like week of year number (1-53). First US calendar week has the majority (4 or more) of its days in January. US week starts on Sunday.
* UNIX_TIME Return number of seconds that have elapsed since 1970-01-01 00:00:00 UTC, ignoring leap seconds.

* TIMEZONE_OFFSET Return number of seconds of timezone offset to UTC.
```

**Comment by hawkfish** [comment]
Hmm a lot of this functionality is [already there](https://duckdb.org/docs/sql/functions/datepart) just with slightly different names (we use the [Postgres part names](https://www.postgresql.org/docs/15/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT)). But adding some aliases is not difficult. Others are trivial arithmetic (e.g., `MONDAY_DAY_OF_WEEK` is `SUNDAY_DAY_OF_WEEK` plus some modular arithmetic) and should probably be addressed as built in macros.

Where did this list come from?

**Comment by rok** [comment]
The list is from [here](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml) and was influenced by [work on Arrow](https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/kernels/scalar_temporal_unary.cc) which in turn was influenced by Pandas and lubridate.

**Comment by hawkfish** [comment]
> The list is from [here](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml) and was influenced by [work on Arrow](https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/kernels/scalar_temporal_unary.cc) which in turn was influenced by Pandas and lubridate.

Thanks. I now have to ask whether this is a DuckDB issue or a Substrait issue (as it seems to me that Postgres would have the same problem?)

**Comment by rok** [comment]
That's for @Tishj to say :)
I don't know that DuckDB (or Postgres) wants to support all of these but Arrow probably would.

**Comment by hawkfish** [comment]
New functionality is great of course 😸 I'm just asking whether we need to do anything for the existing functionality that doesn't use exactly the same syntax?

**Comment by rok** [comment]
I don't expect expect so.
Does DuckDB extract components in local time if the timestamp has a timezone?
Another thing to think about would be [`round_temporal`](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml#L481) and [`round_calendar`](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml#LL546C11-L546C25), but that's out of scope here I suppose.

**Comment by hawkfish** [comment]
> I don't expect expect so.
> Does DuckDB extract components in local time if the timestamp has a timezone?

Yes, but we only support TSTZ binning when ICU (or some other extension) is loaded.

> Another thing to think about would be [`round_temporal`](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml#L481) and [`round_calendar`](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml#LL546C11-L546C25), but that's out of scope here I suppose.

Hmm so rounding instead of truncation (which we do have)? That sounds useful. Not sure if ICU has it.

**Comment by rok** [comment]
> > Another thing to think about would be [`round_temporal`](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml#L481) and [`round_calendar`](https://github.com/substrait-io/substrait/blob/main/extensions/functions_datetime.yaml#LL546C11-L546C25), but that's out of scope here I suppose.
> 
> Hmm so rounding instead of truncation (which we do have)? That sounds useful. Not sure if ICU has it.

It supports these modes:
```
options: [ FLOOR, CEIL, ROUND_TIE_DOWN, ROUND_TIE_UP ]
```

[`time_bucket`](https://duckdb.org/docs/sql/functions/timestamptz) looks to me like the floor mode?

**Comment by Tishj** [comment]
Hey yes, this is related to substrait integration, I couldn't find the functionality, but it's good to know that we support it, just under a different name, that's no problem and that glue should be provided by the `substrait` extension

**Comment by Tishj** [comment]
@rok now that I have you here, I actually have a question about substrait that you might be able to answer
`sunday_day_of_week` says it returns 1-indexed days, ours is 0-indexed (result for sunday is 0)

Which means we have to transform this to `dayofweek(x)+1` to comply to the substrait spec.
Because of this, the result will be different between the substrait compiled query, and our original query.
If I was a user of this I would expect that to not be the case, that I only have to compile it to substrait to run my query on another dbms.

But now I need to compile it to substrait even before I want to run it on another dbms, if I want the guarantee that the results will be the same.
Is that expected behavior?

**Comment by rok** [comment]
1-indexed encoding was chosen because that's [ISO8601 encoding](https://en.cppreference.com/w/cpp/chrono/weekday/encoding).  If you can argue that most systems are 0-indexed, then spec could still be changed (it's early enough it wouldn't be too disrupting). Or you could propose to add 0-indexed variants which would not be a breaking change.

As per my understanding Substrait doesn't aim to model SQL exactly, but rather to provide enough primitives to express all of it's dialects. That unfortunately means glue layers (`dayofweek(x)+1`). I also don't think substrait is intended for end users, just dbms devs, so your users would ideally not be exposed to tho this discrepancy :). So if I understood correctly it is expected behavior.

**Comment by hawkfish** [comment]
> 1-indexed encoding was chosen because that's [ISO8601 encoding](https://en.cppreference.com/w/cpp/chrono/weekday/encoding). If you can argue that most systems are 0-indexed, then spec could still be changed (it's early enough it wouldn't be too disrupting). Or you could propose to add 0-indexed variants which would not be a breaking change.

Postgres, [MS-SQL](https://learn.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql?view=sql-server-ver16#week-and-weekday-datepart-arguments), [DB2](https://www.ibm.com/docs/en/db2-for-zos/12?topic=functions-dayofweek), [Snowflake](https://docs.snowflake.com/en/sql-reference/functions-date-time#label-supported-date-time-parts), and [Clickhouse](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#todayofweek) all return 1-based weekdays (although some of them have an option to use 0).

[SQLite](https://www.sqlite.org/lang_datefunc.html) is 0-based, but it has to use `strftime(%w)`.

[Oracle](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/EXTRACT-datetime.html#GUID-36E52BF8-945D-437D-9A3C-6860CABD210E) doesn't support weekday extraction.

There is also the issue of what the start of the week is set to (we use ICU, and it is configurable, but we only use it for ISO week arithmetic). It is worth mentioning that [ICU is 1-based](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucal_8h.html#a62d9fe551bd48e4141fce52b917119a4)

**Comment by hawkfish** [comment]
> [`time_bucket`](https://duckdb.org/docs/sql/functions/timestamptz) looks to me like the floor mode?

`date_trunc` too.

**Comment by rok** [comment]
Sorry, I can't find if ISO defines indexing for weeks starting on Sunday. We could change to:
```
* MONDAY_DAY_OF_WEEK Return the day of week from Monday (1) to Sunday (7).
* SUNDAY_DAY_OF_WEEK Return the day of week from Sunday (0) to Saturday (6).
```
Which then always makes Monday-Saturday 1-6 and Sunday index would change depending on the mode.

**Comment by hawkfish** [comment]
ICU says it is locale-based and their constants start with 1 (`UCAL_SUNDAY`). So there is a difference between the first day of the week and the numbering scheme. 

What you suggested is actually what we do!

```cpp
	struct DayOfWeekOperator {
		template <class TR>
		static inline TR DayOfWeekFromISO(TR isodow) {
			// day of the week (Sunday = 0, Saturday = 6)
			// turn sunday into 0 by doing mod 7
			return isodow % 7;
		}

		template <class TA, class TR>
		static inline TR Operation(TA input) {
			return DayOfWeekFromISO(Date::ExtractISODayOfTheWeek(input));
		}
```

**Comment by rok** [comment]
> 			return isodow % 7;

Isn't modulo more expensive that a `x+1`? :)

Maximal set of functions would be:
```
* MONDAY_1_DAY_OF_WEEK Return the day of week from Monday (1) to Sunday (7).
* MONDAY_0_DAY_OF_WEEK Return the day of week from Monday (0) to Sunday (6).
* SUNDAY_0_DAY_OF_WEEK Return the day of week from Sunday (0) to Saturday (6).
* SUNDAY_1_DAY_OF_WEEK Return the day of week from Sunday (1) to Saturday (7).
```
Options are:
1. Propose a change to the maximal set
2. Propose a change to a subset (e.g. https://github.com/duckdb/duckdb/issues/6805#issuecomment-1479746294)
3. Keep things as they are

I don't feel strongly about any of the options, we'd want a good argument for the change.

**Comment by ianmcook** [comment]
I think the simplest and safest solution is to add an additional option to the `extract` 

> Maximal set of functions would be:
> 
> ```
> * MONDAY_1_DAY_OF_WEEK Return the day of week from Monday (1) to Sunday (7).
> * MONDAY_0_DAY_OF_WEEK Return the day of week from Monday (0) to Sunday (6).
> * SUNDAY_0_DAY_OF_WEEK Return the day of week from Sunday (0) to Saturday (6).
> * SUNDAY_1_DAY_OF_WEEK Return the day of week from Sunday (1) to Saturday (7).
> ```

I think we could do this in a cleaner and more general way by simply adding a new option to `extract` to specify whether returned integer values should be 0-indexed or 1-indexed. This could pertain not just to days but also weeks, months, and quarters. Let's discuss this in https://github.com/substrait-io/substrait/issues/477.

**Comment by hawkfish** [comment]
This stuff is usually handled in databases by sessions settings, which add another wrinkle to the substrait design: The same query can produce different results based on the user's session settings. One common example is the default ordering of `NULL`s, which a number of RDBMSes - inducing DuckDB - implement. Weekday settings are another.

**Comment by rok** [comment]
I think Substrait is stateless so these parameters will need to be passed at runtime.

**Comment by rok** [comment]
I've opened a PR https://github.com/substrait-io/substrait/pull/479 to control indexing.

**Comment by westonpace** [comment]
> This stuff is usually handled in databases by sessions settings, which add another wrinkle to the substrait design: The same query can produce different results based on the user's session settings. One common example is the default ordering of NULLs, which a number of RDBMSes - inducing DuckDB - implement. Weekday settings are another.

No existing function yet has been described to depend on session settings.  However, there was some discussion about it at some point (I think in the proposal for `random` which didn't make it through) so I won't rule it out entirely.

However, in this case, session settings should not be a wrinkle.  Once we clarify in Substrait whether these indices are 0-based or 1-based then there should be one answer that does not depend on session settings.

> To me making this change at the Subtrait consumer/producer level makes the most sense. The DuckDB substrait consumer/producer knows DuckDB’s and Substrait’s semantics, and can add a +1 or -1 as required as part of the translation. Or is there a requirement that a function maps 1:1 at that level?

If DuckDb is the only consumer that uses 1-based indexing, given that DuckDb can already consume and produce Substrait, I think it would be fine to handle it within DuckDb.  However, if there are other producers / consumers, then I think there is value in expressing the option.  There's pros & cons to both approaches.

* If you keep Substrait's option set limited then it is harder for consumers to adopt Substrait because they have to map everything to a single alternative dialect.
* If you make Substrait's option set very flexible then it is harder for producers to create plans that successfully run against consumers because the likelihood of incompatible options is high.

However, I think the goal of Substrait (and this is certainly open for discussion) is to lean towards a flexible option set with the hopes that translators eventually emerge which centralize all of these +1/-1 translations in a single point.

**Comment by ianmcook** [comment]
As of release 0.30.0 (2023-05-14), the Substrait date/time-part extract function now has an option controlling whether to use 0-based or 1-based indexing for ordinal outputs: https://github.com/substrait-io/substrait/blob/51765cccd92fa0014e9cf077cc8cc952731f33d0/extensions/functions_datetime.yaml#L39-L62
