### ISSUE TITLE
Missing functionality for ROUND

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6806]
Our ROUND method does not have the option to provide a "rounding option".
Also we're missing some function overloads for certain types, currently it's implemented only for FLOAT, DOUBLE and DECIMAL, that means we're missing:
- `ROUND(x TINYINT, s INTEGER) -> TINYINT`
- `ROUND(x SMALLINT, s INTEGER) -> SMALLINT`
- `ROUND(x INTEGER, s INTEGER) -> INTEGER`
- `ROUND(x BIGINT, s INTEGER) -> BIGINT`

The following behavior applies to all these missing overloads:
> When `s` is positive, nothing happens, when `s` is negative however, the rounding is performed to the nearest multiple of `10^(-s)`

The options and descriptions for the "rounding options" are the following:
- TIE_TO_EVEN: round to nearest value; if exactly halfway, tie to the even option.
- TIE_AWAY_FROM_ZERO: round to nearest value; if exactly halfway, tie away from zero.
- TRUNCATE: always round toward zero.
- CEILING: always round toward positive infinity.
- FLOOR: always round toward negative infinity.
- AWAY_FROM_ZERO: round negative values with FLOOR rule, round positive values with CEILING rule
- TIE_DOWN: round ties with FLOOR rule
- TIE_UP: round ties with CEILING rule
- TIE_TOWARDS_ZERO: round ties with TRUNCATE rule
- TIE_TO_ODD: round to nearest value; if exactly halfway, tie to the odd option.

The reason we want to add this is to be compatible with substrait: <https://substrait.io/extensions/functions_rounding/#round>

**Comment by ozdemircs** [comment]
Hi, I would like to work on this.

@Mytherin 

Can you please advise how these option parameter should look like?

I am not super familiar with the duckdb conventions, do we usually present them with named parameters, typical string or is it possible to get as enum as input?

Thanks!

**Comment by ozdemircs** [comment]
@Mytherin I made some progress on this.

What I did so far.

1. Created a operator struct for most of the options. Each option is implemented with mathematical expressions in  https://en.wikipedia.org/wiki/Rounding
2. For round, round precision and float, double types created generic binding functions, and reused the operator based on the option.

What is left is decimal type, implementing some of the options such as to tie_to_odd, tie_to_even, cleaning the code a bit and test cases.

Please let me know if the API change as an additional string parameter is not ideal, or if I am already doing something very wrong.

https://github.com/duckdb/duckdb/compare/master...ozdemircs:duckdb:new_round_functions?expand=1

Thanks!
