### ISSUE TITLE
Rendering profiling json doesn't work

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#6814]
### What happens?

I am following https://duckdb.org/dev/profiling.html. Profiling using EXPLAIN ANALYZE works fine. Writing the profile to json using `PRAGMA enable_profiling='json';` also works.

But, if I try to generate a plot of the plan using `python scripts/generate_querygraph.py /path/to/file.json` as the guide suggests, the html shows nothing. If I open up dev tools in chrome, there is a bug at https://github.com/duckdb/duckdb/blob/227bd4bddc85d30fa8b851c3a2d30e93271996d9/tools/pythonpkg/duckdb_query_graph/parse_profiling_output.js#L185

`timings[key]` used to be a number, but now it is an object. We should be calling `timing_to_str(timings[key].timing)`. But if I monkey patch that fix in, the HTML still doesn't render correctly. I didn't bother exploring further to see if I could fix it.

This begs the question of if this profiling visualization is even worth it, since no one seems to be using it. I see a few options:
1. fix the bugs so the viz works
2. remove the documentation on this, so internal people can still use it but with no guarantees
3. remove everything related to generating vizzes from json

### To Reproduce

Follow the examples in the linked guide above.

### OS:

macOS 12.6

### DuckDB Version:

0.7.1

### DuckDB Client:

N/A

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think I recently saw some issues from the `tools/pythonpkg/duckdb_query_graph/__init__.py` file, though I've never seen what this is used for until now, it's probably related

**Comment by NickCrews** [comment]
Oops, yes this is related/dupe of https://github.com/duckdb/duckdb/issues/3062
