### ISSUE TITLE
PIVOT does not work

### ISSUE THREAD

**Issue by LeoYao** [duckdb/duckdb#6826]
### What happens?

I tried to use `PIVOT` command but it keeps failing with error like `syntax error at or near "PIVOT"` even when I just followed example code in https://duckdb.org/docs/sql/statements/pivot.

Is `PIVOT` actually supported right now? 

### To Reproduce

1. Download duckdb cli from https://github.com/duckdb/duckdb/releases/download/v0.7.1/duckdb_cli-osx-universal.zip
2. run the duckdb cli
3. run the below commands to prepare the data (the same example as show in https://duckdb.org/docs/sql/statements/pivot)

```
CREATE TABLE Cities(Country VARCHAR, Name VARCHAR, Year INT, Population INT);
INSERT INTO Cities VALUES ('NL', 'Amsterdam', 2000, 1005);
INSERT INTO Cities VALUES ('NL', 'Amsterdam', 2010, 1065);
INSERT INTO Cities VALUES ('NL', 'Amsterdam', 2020, 1158);
INSERT INTO Cities VALUES ('US', 'Seattle', 2000, 564);
INSERT INTO Cities VALUES ('US', 'Seattle', 2010, 608);
INSERT INTO Cities VALUES ('US', 'Seattle', 2020, 738);
INSERT INTO Cities VALUES ('US', 'New York City', 2000, 8015);
INSERT INTO Cities VALUES ('US', 'New York City', 2010, 8175);
INSERT INTO Cities VALUES ('US', 'New York City', 2020, 8772);
```

4. run `PIVOT Cities ON Year USING SUM(Population)` and the below error will be reported
```
Error: Parser Error: syntax error at or near "PIVOT"
LINE 1: PIVOT Cities ON Year USING SUM(Populati...
        ^
```

### OS:

macOS

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Leo

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Those docs are for the development version. PIVOT was very recently introduced (#6387) and is currently only supported in the development version. If you want to use PIVOT then either download the development build, compile DuckDB from source or wait until the next release (which will include the new functionality).

**Comment by LeoYao** [comment]
Thanks @Mytherin for the clarification.

No rush, but is there any timeline for the next release?

**Comment by Mytherin** [comment]
The next release is scheduled for May.
