### ISSUE TITLE
DuckDB returns incorrect results in AVG(decimal) for very large decimal values

### ISSUE THREAD

**Issue by isadikov** [duckdb/duckdb#6829]
### What happens?

DuckDB returns incorrect results when running `select avg(column) from table` where `column` is a decimal column of a large precision. This is due to the fact that average aggregate functions in DuckDB are implemented to keep state and results of double type for decimals instead of decimal type. 

This is inconsistent with `sum` aggregate function which returns the correct result of decimal type.

To be fair, it is the same issue in SQLite so maybe it is sort of an "expected" behaviour.

I am curious if this is a known issue and whether there are plans to refactor `avg` function to work with decimals. Thanks!

### To Reproduce

```sql
create table test (a decimal(38,2));
insert into test values (9223372036854775807.12);
insert into test values (9223372036854775807.24);

create table test2 as select avg(a) from test;
select * from test2;
```

DuckDB would return (depending on the machine configuration): `9223372036854775808` which is incorrect. I ran it on another machine which returned `9223372036854776000`. This appears to be due to the limited double precision that can only hold up to 15 decimal digits before introducing an error.

Other engines do return correct results, e.g. Presto: `9223372036854775807.18`.

### OS:

macOS m1 arm64 

### DuckDB Version:

0.7.1

### DuckDB Client:

C++

### Full Name:

Ivan

### Affiliation:

Ahana

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Howdy!
Try out `favg`! It is a more accurate average function.
https://duckdb.org/docs/sql/aggregates

**Comment by isadikov** [comment]
Thanks for the suggestion. I tried the queries with `favg` but I am still getting the same wrong value: `9223372036854775808`. I checked the code https://github.com/duckdb/duckdb/blob/master/src/function/aggregate/algebraic/avg.cpp and it seems `favg` suffers from the same issue. 

I think average aggregation functions need to keep state as a decimal value or int128 instead of double to avoid precision loss.

**Comment by l1t1** [comment]
maybe it's the root of https://github.com/duckdb/duckdb/discussions/6828

**Comment by paultiq** [comment]
Same issue using HUGEINTs: 
```
import duckdb
with duckdb.connect() as con:
    con.execute("""
        create table test (a hugeint);
        insert into test values (922337203685477580712);
        insert into test values (922337203685477580724);
        create table test2 as select avg(a) avg, favg(a) favg from test;
        select avg, favg from test2;""")
        
    r=con.fetchone()
    print("DuckDB avg : {:.2f}".format(r[0]))
    print("DuckDB favg: {:.2f}".format(r[1]))
```
> DuckDB avg : 922337203685477580800.00
> DuckDB favg: 922337203685477580800.00
