### ISSUE TITLE
Compiler version

### ISSUE THREAD

**Issue by kreuzerkrieg** [duckdb/duckdb#683]
Just curious. According to your CMakeLists.txt file
```
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU"
     AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 8.0)
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${CXX_EXTRA_DEBUG}")
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang"
         AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 9.0)
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${CXX_EXTRA_DEBUG}")
  else()
    message(WARNING "Please use a recent compiler for debug builds")
  endif()
```
Isnt clang 9.0 recent enough??? Like, clang 10.0 was released less than 3 month ago.

**Comment by hannesmuehleisen** [comment]
I think its because we develop a lot on OSX and there the clang version is 
`Apple clang version 11.0.3 (clang-1103.0.32.62)`

**Comment by kreuzerkrieg** [comment]
but Apple clang is a fork of llvm clang and has different versioning scheme. AFAIK, of course

**Comment by hannesmuehleisen** [comment]
Yes, certainly. What would you suggest we should require there? The check is mostly so we can use the address sanitisers.

**Comment by kreuzerkrieg** [comment]
not sure... if you just want to make sure the compiler is modern enough, and now when you know that Apple clang and llvm clang use different versioning scheme, maybe it is enough just to expand the `if` to include the check for different OSes? like Darwin clang > 9.0 and Linux clang > say, 7.0? 8.0? I guess we can check since where the required sanitizer is available and then decide. WDYT?

**Comment by hannesmuehleisen** [comment]
The battle plan here is to simply test the flags we would like to add as `CXX_EXTRA_DEBUG` using `check_cxx_compiler_flag`. Then we do not care about the version at all.

**Comment by kreuzerkrieg** [comment]
great idea! it is a better solution, indeed! just ping me when it is done so I can grab the latest changes. Thanks for cooperation!
