### ISSUE TITLE
duckdb returns IO Error connection error for a local port

### ISSUE THREAD

**Issue by chrisirhc** [duckdb/duckdb#6832]
### What happens?

I'm using go-duckdb via a Go service. After the service runs for a while, the DuckDB gets into a "stuck" state where every request to a particular port fails with:
```IO Error: Connection error for HTTP HEAD to 'http://localhost:18839/some-path?xyz=something'```

What I find unusual is that I can do a `curl -I <same url>` on that same machine and get a success, so I'm not sure why the connection error is even occuring.
Restarting the service seems to resolve the issue (connectivity works again). Is there some kind of "sticky" caching of the http client?

I initially hit this issue in 0.6.1 (go-duckdb 1.0.7), and I saw that http retries were revamped in 0.7 so I upgraded to it. However, I'm still seeing this issue.

### To Reproduce

I'm unable to create a reliable reproduction at this point.
Current clues:
* It seems to occur after a successful request is made from DuckDB, then ~24 hours later, the same request fails.
* Restarting the service gets makes requests successful again. (Resets state?)
* `curl` on the machine works so the address is reachable. However, DuckDB's httplib is reporting Error::Connection

### OS:

x64

### DuckDB Version:

0.7.0

### DuckDB Client:

go-duckdb

### Full Name:

Chris Chua

### Affiliation:

Uber

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lev112** [comment]
I'm getting the same issue when reading parquet files from S3.
it can run for a couple of hours, and then fail with the same error
```
IO Error: Connection error for HTTP HEAD to 'https://my-bucket.s3.amazonaws.com/...
```

I've had this issue with both 0.7.1 and 0.8.0
