### ISSUE TITLE
Error in R duckdb date_trunc on column with timestamp with time zone

### ISSUE THREAD

**Issue by elysabethpc** [duckdb/duckdb#6834]
### What happens?

Hello,

I get an error when I try to do a date_trunc on a column with type timestamp with time zone.

If the column type doesn't have time zone, it works ok.
This happens on R Windows 11 and R Linux (fedorada 37). Duckdb version 0.7.1.

Only fails in R duckdb.

The code in section "To Reproduce" fails with this error:

```
Error: rapi_prepare: Failed to prepare query select *, date_trunc('hour',dt) as m from s1
Error: Binder Error: No function matches the given name and argument types 'date_trunc(VARCHAR, TIMESTAMP WITH TIME ZONE)'. You might need to add explicit type casts.
	Candidate functions:
	date_trunc(VARCHAR, TIMESTAMP) -> TIMESTAMP
	date_trunc(VARCHAR, DATE) -> TIMESTAMP
	date_trunc(VARCHAR, INTERVAL) -> INTERVAL

LINE 1: select *, date_trunc('hour',dt) as m from s1
```

Work ok on CLI duckdb:

```
duckdb <<EOT
create table s1 (dt timestamp with time zone);
describe s1;
create or replace table s1 as select timestamptz '2023-03-23 08:01:02.345 UTC' as dt;
select *, date_trunc('hour',dt) as m from s1;

EOT
```

Python version works ok:

```
import pandas as pd
import duckdb
import polars as pl


con = duckdb.connect()

con.execute("create table s1 (dt timestamp with time zone)")
con.sql("describe s1")
con.sql("create or replace table s1 as select timestamptz '2023-03-23 08:01:02.345 UTC' as dt")
con.sql("select *, date_trunc('hour', dt) as m from s1")
con.sql("select * from s1").pl().select(pl.col("dt").dt.truncate("1h"))
```

Thank you

### To Reproduce

```
library(tidyverse)
library(DBI)

con <- dbConnect(duckdb::duckdb())

dbExecute(con,"create table s1 (dt timestamp with time zone)")
dbGetQuery(con,"describe s1")
dbExecute(con,"create or replace table s1 as select timestamptz '2023-03-23 08:01:02.345 UTC' as dt")
dbExecute(con,"select *, date_trunc('hour',dt) as m from s1")

# floor_date with dbplyr also fails
tbl(con,"s1") |> 
  mutate(
    trunc = floor_date(dt,"hour")
  )

dbGetQuery(con,"select *, date_trunc('hour',dt::timestamp) as m from s1")
```

### OS:

Windows (10) and Linux (fedora 37) x64

### DuckDB Version:

0.7.1

### DuckDB Client:

R

### Full Name:

Elysabethpc

### Affiliation:

Particular

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
The ICU extension is required to operate on timestamps with time zones. It is bundled with most clients, but the R client does not bundle it currently. Perhaps try `LOAD icu`.
