### ISSUE TITLE
Pandas DataFrames created with `data` arg are queried incorrectly. 

### ISSUE THREAD

**Issue by TNonet** [duckdb/duckdb#6845]
### What happens?

Pandas allows you to construct DataFrames in somewhat strange ways. For example,
```python
import pandas
import numpy
data = numpy.array([["a", "b", "c"], [1,2,3], [1, 2, 3], [11, 22, 33]])
print(data)
[['a' 'b' 'c']
 ['1' '2' '3']
 ['1' '2' '3']
 ['11' '22' '33']]
```
```python
df = pandas.DataFrame(data=data[1:,], columns=data[0])
df
    a   b   c
0   1   2   3
1   1   2   3
2  11  22  33
```
We can see here that `data` is contiguous:
```python
data.flags
Out[3]:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```
However, individual columns of `df` are not.
```python
df["a"].values.flags
Out[11]:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

This causes DuckDB to query the data incorrectly:
```python
duckdb.query("select * from df").to_df()
Out[8]:
   a  b  c
0  1  2  3
1  2  3  1
2  3  1  2
```

### To Reproduce

```python
import pandas
import numpy
import duckdb

data = numpy.array([["a", "b", "c"], [1,2,3], [1, 2, 3], [11, 22, 33]])
df = pandas.DataFrame(data=data[1:,], columns=data[0])
df_shuffled = duckdb.query("select * from df").to_df()
```

### OS:

iOS 13.2.1 (22D68)

### DuckDB Version(s):

0.7.1
0.7.2-dev982

### DuckDB Client:

Python

### Full Name:

Tim N

### Affiliation:

Hex

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by TNonet** [comment]
This may be classified as undefined behavior as the DuckDB Python client may "require" contiguous arrays to function correctly. 

However, this is still strange/undesirable behavior as the default for DuckDB to scan python `locals()` to "automatically" enable querying of pandas DataFrames makes this seem more like a bug than user error.

**Comment by paultiq** [comment]
I see same issue with any numpy array of strings, such as: 

```
import pandas
import numpy
import duckdb


data1 = numpy.array([["a", "b", "c"], ["d", "e", "f"]])
df1 = pandas.DataFrame(data=data1)
df1_ddb = duckdb.query("select * from df1").to_df()

display(df1)
display(df1_ddb)
```
df1 = 
0	1	2
a	b	c
d	e	f

df1_ddb = 
0	1	2
a	b	c
b	c	d

**Comment by TNonet** [comment]
@paultiq Interesting. It seems this is just for string (maybe other dtypes too?) DataFrames constructed with the `data` arg, and the non-contiguous numpy array was a red herring.

If you `copy(deep=True)` either example, the issue disappears.
```
data1 = numpy.array([["a", "b", "c"], ["d", "e", "f"]])
df1 = pandas.DataFrame(data=data1).copy(deep=True)
df1_ddb = duckdb.query("select * from df1").to_df()
assert str(df1) == str(df1_ddb)

data = numpy.array([["a", "b", "c"], [1,2,3], [1, 2, 3], [11, 22, 33]])
df = pandas.DataFrame(data=data[1:,], columns=data[0]).copy(deep=True)
df_shuffled = duckdb.query("select * from df").to_df()
assert str(df) == str(df_shuffled)
```

**Comment by paultiq** [comment]
Going a little further: reproduces on anything with dtype='<U11'.

```
import pandas
import numpy
import duckdb
data1 = numpy.array([[1,2,3], [5,6, 7]], dtype="<U11")
print(data1.dtype)
df1 = pandas.DataFrame(data=data1)
df1_ddb = duckdb.query("select * from df1").to_df()
print(df1)
print(df1_ddb)
```

**Comment by Tishj** [comment]
This issue is related to scanning pandas object columns, I'll have a look 👍
