### ISSUE TITLE
[Python] Add scalar UDF

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6862]
We want to add the ability to register UDFs in the python client.

Proposed syntax:
```py
import duckdb

from duckdb.typing import *

def add_one(x):
    return x + 1

duckdb.register_scalar("plus_one", add_one, [BIGINT], BIGINT)
# duckdb.register_scalar("plus_one", lambda x: x + 1, [BIGINT], BIGINT)

res = duckdb.sql('select plus_one(5)')
```

**Comment by Tishj** [comment]
@gforsyth what do you think of this syntax?

**Comment by Alex-Monahan** [comment]
Here is sqlite3's syntax as another reference point! I have not used it though...
https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function

**Comment by Tishj** [comment]
Yea I need to look at the binding code for varargs, we support it for other scalar functions, just not familiar with the internals so I can't envision it. But we can probably support varargs.

I also had some ideas for extra options, null-handling is one, and exception handling (return null or rethrow?)

**Comment by cpcloud** [comment]
> For efficiency reasons, I'd prefer the latter (probably with pyarrow things) if possible.

+1 from me on that too. I'd strongly prefer pyarrow objects, since they can easily be converted to pandas DataFrames with a single method call.

**Comment by Tishj** [comment]
This first implementation will not be, the idea here is that when you need a UDF, you likely don't need to do operations that can efficiently be done on pyarrow/pandas/numpy, as those are all database operations - which could just as easily be done with SQL.
The aim here is to support arbitrary transformations

**Comment by jcrist** [comment]
> you likely don't need to do operations that can efficiently be done on pyarrow/pandas/numpy, as those are all database operations

I disagree with this. For our use case, we'd often want to be hooking in functionality that's already inherently vectorized, but not expressible using duckdb native operations. For example, calling `model.predict` on a column using a scikit-learn model. If a user needs scalar level calls, those can always be constructed out of vectorized/batched calls, but going the other way isn't possible.
