### ISSUE TITLE
Silent crash with longer SQL query

### ISSUE THREAD

**Issue by jakobstanford** [duckdb/duckdb#6883]
### What happens?

DuckDB crashes without error message when I run a rather lengthy SQL query.
I have tried the CLI, the C++ version and the JDBC version. This happens both with v0.7.1 and the latest (todays?) development version. I also tried v0.6.1, but this version doesnt have `split_part()` that my query uses.
I doubt that duckdb runs out of memory. The whole DB in-memory occupies just 4GB and the crash also happens on a machine with 128GB of RAM. 

The query itself might be long and the dataset might be large (~2M rows), but query itself isnt that complex. The query also runs fine on redshift.

### To Reproduce

1. Clone the testdata from https://github.com/jakobstanford/duckdb-testdata
2. Extract the duckdb database file `v3.duckdb`  from the archive `v3.7z`. (uncompressed file is 600MB, too large for github, sorry)
3. Launch console with `duckdb-071.exe v3.duckdb'.
4. Run the  rather length SQL query: `.read v4.sql`
5. Observe, how the CLI quits after a few seconds.

(This example uses v0.7.1 for file-format compatibility reasons, but the same behavior occurs with latest git version)

### OS:

Windows 64bit (tested on win10 and windows server 2012R2

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Jakob Stanford

### Affiliation:

Arup

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
your data is strange, very small rows, very slow reads
```
D select  count(1) from beam_list;
┌──────────┐
│ count(1) │
│  int64   │
├──────────┤
│      815 │
└──────────┘
D .timer on
D from beam_list limit 1;
┌───────────┬─────────────
──────┬───┬───────────────
│ beam_name │        doc_id        │      model_n

│   int64   │       varchar        │       varcha
├───────────┼─────────────
──────┼───┼───────────────
│       601 │ 009651fb-6a0d-4934…  │ CSC-v23.103
 │
├───────────┴─────────────
──────┴───┴───────────────
│ 1 rows
└─────────────────────────
──────────────────────────
Run Time (s): real 3.708 user 4.383628 sys 0.078001
```

**Comment by jakobstanford** [comment]
exported and imported all tables via parquet files, but the query crashes nevertheless. admittedly, it crashes faster though ;)

**Comment by l1t1** [comment]
could you analysis the execute plan?

**Comment by paultiq** [comment]
I poked around at this for a little bit. The query completes in about a minute after changing m_initial to a fixed value. 

I changed:
```
CASE

  WHEN member_type LIKE '%-diag' THEN 2.0

  WHEN member_type LIKE '%-vert' AND db.prop_name NOT IN ('W14X90','W14X109') THEN 1.5
  WHEN member_type LIKE '%-vert' AND db.prop_name IN     ('W14X90','W14X109') THEN
    CASE WHEN Puf_Pye < 0.2 THEN 1.25 ELSE 1.0  END

  WHEN member_type LIKE '%-horiz' AND db.prop_name NOT IN ('W14X26','W14X30','W14X34','W14X43','W14X90','W14X109','W18X35','W18X76') THEN 2.0
  WHEN member_type LIKE '%-horiz' AND db.prop_name IN     ('W14X26','W14X30','W14X34','W14X43','W14X90','W14X109','W18X35','W18X76') THEN
    CASE WHEN Puf_Pye < 0.2 THEN 1.25 ELSE 1.0  END

  WHEN member_type LIKE '%-rod' THEN 2.0
END
```
to 
```
1 as m_initial
```
