### ISSUE TITLE
Add option for array notation to support postgres array

### ISSUE THREAD

**Issue by wpdonders** [duckdb/duckdb#6887]
As in the referenced issue, `duckdb` uses `[]` for array notation whereas postgres uses `{}`. When I tried to read data from a postgres dump that contained arrays, `duckdb` was unable to load the arrays correctly due to the mismatch in array notation. For now, I used a workaround to first load the array columns as `VARCHAR` and then converting. 

An option used in CSV reading such as `ARRAY_CHARACTER '{'` (default `[`) would prevent the need for the workaround. 

_Originally posted by @wpdonders in https://github.com/duckdb/duckdb/issues/2698#issuecomment-1486554201_

**Comment by vg-vaibhav** [comment]
Hey @wpdonders ,
Were you able to find a work around for the array notion issue?

**Comment by wpdonders** [comment]
@vg-vaibhav 

Yes, a workaround was already proposed in the linked issue, i.e. read the array as a `VARCHAR` and then apply `string_split` and cast the resulting array elements to the correct data type. See [this comment](https://github.com/duckdb/duckdb/issues/2698#issuecomment-1181769039).

```sql
SELECT string_split(l[2:-1], ',')::INT[] FROM VALUES ('[1,2,3]') t(l);
```
