### ISSUE TITLE
CTE having `read_parquet` from multiple files + `row_number` + OOM leads to excessive disk spilling

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#6893]
### What happens?

I am seeing a very unreasonable amount of disk spilling when I try to execute a query in which all of the following conditions are met:
* It creates a CTE (`with <>`) which has a few `where` conditions involving missingness of values.
* Which reads from multiple parquet files (merging the same data into a single file makes the problem go away).
* And has a window function like `row_number() over (order by ...)` in the `select` section **inside** the CTE (putting it outside would produce the exact same result in this example, but without triggering the inefficiency. Removing it also solves the issue).
* Then has other CTEs which do aggregations SELECTing from the first CTE.
* Then selects a subset of columns from the original CTE and left-joins to the others (one-to-one mapping).
* The amount of data needs to be large enough to trigger disk spilling.

When **all** of the conditions above are met in conjuction, it causes excessive disk spilling (>30GB for input files which sum to 2GB as snappy parquets) and very long running times by more than an order of magnitude (much longer than reading everything into memory and then saving into a new parquet file, or than creating a single parquet or a database through a different query and then running the original query on that result), which leads me to suspect that the first CTE might be dumping the whole thing to disk even though not every column or value will end up being selected, but I don't know how to verify this. I am thinking it could _perhaps_ be related to a memory error in the query optimizer (see https://github.com/duckdb/duckdb/issues/6892).

### To Reproduce

I've been trying but have been unable to create a reliable reproducer. The amount of data needs to be rather large, and have different types of columns.

But basically, should be a query like the following:
```sql
with tbl0 as (
    select
        * -- many columns which won't end up used
        , row_number() over(order by filename, file_row_number) as row_num
        -- ^^^ that function above triggers all the inefficiency
    from read_parquet(
        'many/files/*.parquet'
        , filename=true
        , file_row_number=true
        , union_by_name=true --might as well pass false, no difference
    )
where
    <conditions about non-null>
    <plus a >= condition on a timestamp>
)
, tbl_join1 as (
    select
        <some varchar column>
        , favg(<some float column>)
        , count(*) as num2_cnt
    from tbl0
    where
        <float column above is not null>
    group by
        <the varchar column>
),
<1-2 other similar queries as the above>
select
    <a subset of columns from tbl0>
    , <the favg and count calculated from the other expressions>
    , row_num
from tbl0
join tbl_join1 on ...
where
    ...
order by row_num
```

### OS:

Linux

### DuckDB Version:

0.7.2.dev1188

### DuckDB Client:

Python and R

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by david-cortes** [comment]
> Window functions have to materialize their input in order to sort and partition the data. In this case that could be avoided if the system would recognize that the `file_row_number` column is naturally sorted, but no such optimization is performed currently (see #2548).
> 
> Generally the system will recognize the columns in the `*` are not required and strips them out, drastically reducing the amount of data that needs to be materialized, but it is possible an edge case is triggered that prevents the unused columns from being removed. It is hard to tell without a reproducible example, however. In that case I would not be surprised there is such a large amount of data materialized. 2GB of compressed data can easily expand to 10GB of uncompressed data, and it looks like you are executing multiple window functions on that 10GB of data at the same time.

Thanks for the answer. But in this case, joining all the .parquet files into a single file that uses the same format and compression algorithm before executing the query, doesn't lead to the same amount of disk spilling, and reduces the running time by at least 1 order of magnitute (didn't manage to execute the full query as it runs out of space).

Is there perhaps some way of enabling a sort of verbose mode of what's happening that I might not be aware of?

**Comment by hannes** [comment]
Hey @david-cortes could you please drop me a me an email at hannes@duckdblabs.com ? Thanks!
