### ISSUE TITLE
Inconsistent handling of bytes columns with Pandas dataframes.

### ISSUE THREAD

**Issue by nsthorat** [duckdb/duckdb#6907]
### What happens?

If I have a DataFrame with a bytes column, select all the values, and convert back to a DataFrame the bytes column shows up as an array of integers.

### To Reproduce

```
>>> import duckdb, pandas as pd
>>> con = duckdb.connect(database=':memory:')
>>> in_df = pd.DataFrame.from_records([{'key': b'1'}])
>>> in_df
    key
0  b'1'
>>> con.query("SELECT * FROM in_df").to_df()
    key
0  [49]
```

Ideally we get a bytes column on the other side.

### OS:

MacOS 13.2 (22D49)

### DuckDB Version:

0.6.1

### DuckDB Client:

python

### Full Name:

Nikhil Thorat

### Affiliation:

Startup

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Was curious if there was a casting issue, but nothing here surprised me (* I'm unaffiliated with project, just my two cents):

Python bytes literals [PEP 3112](https://peps.python.org/pep-3112/) are syntactic sugar around encoding a string as an array of bytes.

These three lines are therefore equivalent: 
```
# Original
in_df = pd.DataFrame.from_records([{'key': b'1'}])
# Encode
in_df = pd.DataFrame.from_records([{'key': '1'.encode()}])
# Bytes([])
in_df = pd.DataFrame.from_records([{'key': bytes([49])}])
```

Once it's in the dataframe, it's just a byte array, and DuckDB is mapping it to an appropriate database type for a ByteArray: a [BLOB](https://duckdb.org/docs/sql/data_types/overview.html).

The only difference in the result is that the original data was a "bytes" object, and the result is a "". More info on the differences in [PEP3137](https://peps.python.org/pep-3137/#:~:text=Both%20bytes%20and%20bytearray%20implement,'%20(i.e.%20unsigned%20byte).) 


To demonstrate that the only difference in the result is "bytes" vs "bytearrays":
```
import pandas as pd
import duckdb
in_df = pd.DataFrame.from_records([{'key': bytes([49,49])}])

print(type(in_df['key'].values[0]))

with duckdb.connect() as con:
    rdf = con.sql("""select key, decode(key), key::varchar from in_df""").to_df()
    print(rdf)
    print(type(rdf['key'].values[0]))
```
>     key
> 0  b'1'
>
> <class 'bytes'>
>
>     key decode("key") CAST("key" AS VARCHAR)
> 0  [49]             1                      1
>
> <class 'bytearray'>

** If you want the original decoded value back, you can use decode(key) or cast or key::varchar.

**Comment by Tishj** [comment]
Yea I thought you meant there was a bytes dtype, so we can differentiate properly.
But that doesn't appear to be the case:
```py
in_df = pd.DataFrame.from_records([{'key': b'1'}])
print(in_df.dtypes)
#key    object
#dtype: object
```
Which means we have to analyze the column to determine what the type actually is, and that means there could be ambiguity issues.
