### ISSUE TITLE
Some rows go missing while joining 2 tables

### ISSUE THREAD

**Issue by Nachiket94** [duckdb/duckdb#6909]
### What happens?

I am using [duckdb.read_csv](https://duckdb.org/docs/api/python/overview#data-input) to read 2 ".csv" files and store the data in variables db1 and db2. While querying, "SELECT * FROM db1 JOIN db2 ON db1.user_ID = db2.user_ID" the output is missing some rows. I could not find any relation between the missing rows. If I query only on one of the tables, output is correct.

### To Reproduce

`import duckdb
db = duckdb.connect()
db1 = duckdb.read_csv('User Attributes.csv')
db2 = duckdb.read_csv('User Events.csv')

data = db.sql("""SELECT *
                    FROM db1 
                    JOIN db2 
                    ON db1.user_ID = db2.user_ID 
                    LIMIT 30;""").fetchall()
print(data)`

### OS:

Ubuntu 18.04

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Nachiket Somani

### Affiliation:

Student

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Nachiket94** [comment]
Please use any random data generator. I generated mine from [Mockaroo](https://www.mockaroo.com/)

**Comment by Mytherin** [comment]
Thanks for the report!

An inner join is expected to filter out rows for which the predicate does not match, for example:

```sql
CREATE TABLE user_attributes(user_ID INTEGER, attribute_name VARCHAR);
INSERT INTO user_attributes VALUES (1, 'Attribute 1'), (2, 'Attribute 2');
CREATE TABLE user_events(user_ID integer, user_event VARCHAR);
INSERT INTO user_events VALUES (1, 'Event 1'), (3, 'Event 2');
FROM user_attributes;
┌─────────┬────────────────┐
│ user_ID │ attribute_name │
│  int32  │    varchar     │
├─────────┼────────────────┤
│       1 │ Attribute 1    │
│       2 │ Attribute 2    │
└─────────┴────────────────┘
FROM user_events;
┌─────────┬────────────┐
│ user_ID │ user_event │
│  int32  │  varchar   │
├─────────┼────────────┤
│       1 │ Event 1    │
│       3 │ Event 2    │
└─────────┴────────────┘
SELECT *
FROM user_attributes
JOIN user_events
ON user_attributes.user_ID = user_events.user_ID; 
┌─────────┬────────────────┬─────────┬────────────┐
│ user_ID │ attribute_name │ user_ID │ user_event │
│  int32  │    varchar     │  int32  │  varchar   │
├─────────┼────────────────┼─────────┼────────────┤
│       1 │ Attribute 1    │       1 │ Event 1    │
└─────────┴────────────────┴─────────┴────────────┘
```

Perhaps you are looking for a `FULL OUTER JOIN` instead?

```sql
SELECT *
FROM user_attributes
FULL OUTER JOIN user_events
ON user_attributes.user_ID = user_events.user_ID; 
┌─────────┬────────────────┬─────────┬────────────┐
│ user_ID │ attribute_name │ user_ID │ user_event │
│  int32  │    varchar     │  int32  │  varchar   │
├─────────┼────────────────┼─────────┼────────────┤
│       1 │ Attribute 1    │       1 │ Event 1    │
│       2 │ Attribute 2    │    NULL │ NULL       │
│    NULL │ NULL           │       3 │ Event 2    │
└─────────┴────────────────┴─────────┴────────────┘
```

**Comment by Nachiket94** [comment]
Even using FULL OUTER JOIN, the error still persists.
Update: On outputing the full table (consisting of 1000 rows), I found that rows went missing randomly for the whole table. But after the 1000th row, the missing rows are shown in random order.

For example,
1...
2...
4...
6...
.
.
1000...
5...
3...

**Comment by Mytherin** [comment]
The result of a join is not guaranteed to be ordered in any particular way. If you want to order the result of a join you need to add an `ORDER BY` afterwards. Perhaps that is the confusion here?

**Comment by Nachiket94** [comment]
Using 'ORDER BY' solved the issue. I guess sometimes it is necessary to make such small mistakes. It helps to learn that we should never make that mistake again. Thank you Mytherin for helping me solve this issue.
