### ISSUE TITLE
Optimize Top N Implementation

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#691]
The current Top N implementation materializes the full input, which is not necessary and very costly especially with low N (which is the most common scenario). Ideally we would only keep the actual Top N values during the run. This should improve performance and greatly reduce memory consumption.

**Comment by hawkfish** [comment]
Love to look at this one too.

**Comment by Mytherin** [comment]
@hawkfish that would be great! The Top-N we have right now has several deficiencies:

* It fully buffers the input before doing the heap-based top-n extraction
* The heap-based top-n extraction uses the value API (very slow)
* It is not properly parallelism enabled

The implementation we have right now is in `physical_top_n.cpp`. Ideally we would move to a model where every thread would keep the top `N` values separately (allowing for parallel execution), and then in the combine we can do a merge of those N values. Since the Top-N is only an optimization it is safe to assume N will be very small (if N is large, e.g. >50K) we can fallback to using a sort + limit or a different implementation.

**Comment by hawkfish** [comment]
OK, I have reduced the per-thread memory to the rows and the ordering values of the top N for that thread. The parallelism looked OK (there was a `mutex`) but I have made the `Combine` operation just some pointer manipulation.  Then `Finalize` recomputes the heap for the pipeline.  

I'm not sure what to do about the value API problem. Are there similar solutions anywhere?

**Comment by Mytherin** [comment]
Excellent! Very nice work. 

The value API problem can be solved separately; generally this is solved by moving towards per-type templated functions that perform the operation, rather than using the generic API that does multiple type-switches and expensive memory allocation per-tuple. Ideally you would only have a single type switch per vector, followed by a tight compiled loop that performs the actual operation.

**Comment by hawkfish** [comment]
Yeah I did something like that in the Tableau Data Engine (another column store). Sorting was done one column at a a time using type-specific code for the column type and then sub-sorting within ranges. It seems like something that should done in a reusable fashion for heap sorting.

On an unrelated note, I am unable to submit because I can't get the `cmake-format` tool to run. I've installed it with `pip` but `make format-fix` dies with ```FileNotFoundError: [Errno 2] No such file or directory: 'cmake-format': 'cmake-format'```. No idea how to fix that.

**Comment by hawkfish** [comment]
This is on various Macs.

**Comment by Mytherin** [comment]
> Yeah I did something like that in the Tableau Data Engine (another column store). Sorting was done one column at a a time using type-specific code for the column type and then sub-sorting within ranges. It seems like something that should done in a reusable fashion for heap sorting.

Yes, indeed. @lnkuiper is working on doing just that for the main sort. That can be merged with the top-n implementation when he is done.

> On an unrelated note, I am unable to submit because I can't get the cmake-format tool to run. I've installed it with pip but make format-fix dies with FileNotFoundError: [Errno 2] No such file or directory: 'cmake-format': 'cmake-format'. No idea how to fix that.

`pip install` might install things outside of your path; perhaps run `find / -name "cmake-format" 2>/dev/null` to see where cmake-format is installed and adding that to your PATH.

**Comment by hawkfish** [comment]
Thanks - it was stupider than that. It added the correct path to my `PATH` but didn't update my shell.  `source ~/.zprofile` fixed it.

**Comment by hawkfish** [comment]
A hybrid approach might be pretty fast most of the time. Suppose there is only one ordering key: then you could just use a single template and avoid the code bloat. That is probably the most common scenario anyway.
