### ISSUE TITLE
Error: Not implemented Error: Expr of type 134 not implemented

### ISSUE THREAD

**Issue by LeonidChistov** [duckdb/duckdb#6916]
### What happens?

DuckDB emits cryptic error message for "IS TRUE" expressions like

```
SELECT ws_sold_date_sk <= 30 IS TRUE FROM web_sales
```

Since documentation doesn't describe this expression as supported, expected behavior would be to emit user-friendly error message.

### To Reproduce

In Python:

```
import duckdb

duckdb.sql('SELECT 42 IS TRUE').show()
```

### OS:

Linux

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Leonid Chistov

### Affiliation:

Querify Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the issue report :)

I believe this is happening because the postgres parser (which we forked our parser from) can parse it, but we have not implemented this type of expression.

So the parse succeeds, but transform fails, and there probably isn't an implemented Postgres parse expression to string method, so we resort to reporting the enum number.
We should double check if there really is no postgres parse expression -> string conversion method we can use to make this message a little friendlier and more helpful

**Comment by hannes** [comment]
Going to have a go at implementing this

**Comment by LeonidChistov** [comment]
@Tishj 

AFAIK, "IS TRUE" is needed if you want your expression to be guaranteed to have boolean result and don't have NULL as a value.

So, in my example with "SELECT ws_sold_date_sk <= 30 IS TRUE FROM web_sales", such statement would emit FALSE for rows where `ws_sold_date_sk`, while "SELECT ws_sold_date_sk <= 30 FROM web_sales" would emit NULL for such rows.

See Postgres specification: https://www.postgresql.org/docs/current/functions-comparison.html.

**Comment by Tishj** [comment]
Ah I had not considered NULL behavior, you're right 👍

**Comment by Mytherin** [comment]
> @Tishj
> 
> AFAIK, "IS TRUE" is needed if you want your expression to be guaranteed to have boolean result and don't have NULL as an output value.
> 
> So, in my example with "SELECT ws_sold_date_sk <= 30 IS TRUE FROM web_sales", such statement would emit FALSE for rows where `ws_sold_date_sk` is NULL, while "SELECT ws_sold_date_sk <= 30 FROM web_sales" would emit NULL for such rows.
> 
> See Postgres specification: https://www.postgresql.org/docs/current/functions-comparison.html.

That sounds like it is equivalent to IS NOT DISTINCT FROM, which we already support but is more general/verbose
