### ISSUE TITLE
`range`/`generate_series` misinterpret types of correlated columns

### ISSUE THREAD

**Issue by timfi** [duckdb/duckdb#6917]
### What happens?

When using `range` or `generate_series` in a correlated position—i.e., their arguments access columns/rows to the left in the same `FROM`-clause—they seem to misinterpret the types of said variables as `varchar`s.

### To Reproduce

```sql
SELECT x FROM (SELECT 32 AS a) AS _, LATERAL range(a) AS __(x);
```

### OS:

mac OS (aarch64)

### DuckDB Version:

dev (cef3bdc)

### DuckDB Client:

cli

### Full Name:

Tim Fischer

### Affiliation:

Database Research Group Tübingen

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is the same issue as #5762, and occurs because `range` is not implemented as a table-in-out function. Work is in progress to fix that, but currently `range` is not supported as a lateral function.

**Comment by timfi** [comment]
Thanks for the quick response! It seems my GitHub-Fu is not as good as I thought! I'll close this issue then. 👋

**Comment by timfi** [comment]
Duplicate of #5762
