### ISSUE TITLE
Failure while loading and processing Parquet file via Arrow

### ISSUE THREAD

**Issue by ravisharda** [duckdb/duckdb#6925]
### What happens?

I'm trying to use Arrow reader to load and process a Parquet file into DuckDB, as described in DuckDB docs [here](https://duckdb.org/docs/api/java#arrow-import). 

When I run the program, it fails with the following error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001606d50d4, pid=48149, tid=9987
#
# JRE version: OpenJDK Runtime Environment Zulu11.45+27-CA (11.0.10+9) (build 11.0.10+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.45+27-CA (11.0.10+9-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [libduckdb_java13713280745932694833.so+0x6d50d4]  duckdb::ArrowTableFunction::ArrowScanBind(duckdb::ClientContext&, duckdb::TableFunctionBindInput&, std::__1::vector<duckdb::LogicalType, std::__1::allocator<duckdb::LogicalType> >&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)+0x114
#
# ...
```

### To Reproduce

```java

String parquetFilePath = "/path/to/sample.parquet";

try (BufferAllocator allocator = new RootAllocator();
       FileInputStream is = new FileInputStream(parquetFilePath);
       ArrowStreamReader reader = new ArrowStreamReader(is, allocator);
       ArrowArrayStream stream = ArrowArrayStream.allocateNew(allocator)) {
    Data.exportArrayStream(allocator, reader, stream);

    Class.forName("org.duckdb.DuckDBDriver");
       
    try (DuckDBConnection conn = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:")) {
        conn.registerArrowStream("testStream", stream);

        try (Statement stmt = conn.createStatement();
               ResultSet rs = stmt.executeQuery("SELECT count(*) FROM testStream")) {
             while (rs.next()) {
                 System.out.println(rs.getInt(1));
            }
         }
     }
}
```

### OS:

macOS - 12.6.3 - arm64e

### DuckDB Version:

0.7.1

### DuckDB Client:

duckdb_jdbc

### Full Name:

Ravi Sharda

### Affiliation:

Fivetran

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
The issue is you're trying to read a parquet file using a class intended for reading arrow ipc messages

Have a look here for information on reading parquet files using arrow java: https://arrow.apache.org/cookbook/java/dataset.html#query-data-content-for-file

**Comment by ravisharda** [comment]
Do you know how I can create an `ArrowArrayStream` for a  Parquet file in Java? I'm unable to find any documentation anywhere.

**Comment by ravisharda** [comment]
Well, figured it out: 

```java
ScanOptions options = new ScanOptions(/*batchSize*/ 32768);
try (BufferAllocator allocator = new RootAllocator();
     ArrowArrayStream stream = ArrowArrayStream.allocateNew(allocator);
     DatasetFactory datasetFactory = new FileSystemDatasetFactory(allocator,
                     NativeMemoryPool.getDefault(), FileFormat.PARQUET, uri.toString());
     Dataset dataset = datasetFactory.finish();
     Scanner scanner = dataset.newScan(options);
     ArrowReader reader = scanner.scanBatches();) {

     Data.exportArrayStream(allocator, reader, stream);
...
```

**Comment by Mause** [comment]
DuckDB also has built in support for parquet files as well, see https://duckdb.org/docs/guides/import/parquet_import

**Comment by ravisharda** [comment]
@Mause my understanding is that DuckDB `read_parquet()` doesn't support reading encrypted Parquet files. I've raised a feature request at https://github.com/duckdb/duckdb/discussions/6923. 

So, I'm exploring if I can take the  following routes for reading from and writing to Parquet files encrypted using Parquet encryption: 
* Input: `Parquet (encrypted)` -> `Arrow` -> `DuckDB`
* Output: `DuckDB` -> `Arrow` -> `Parquet(encrypted)`
