### ISSUE TITLE
Segfault when using `enable_object_cache` alongside `union_by_name` for parquet files

### ISSUE THREAD

**Issue by thehabbos007** [duckdb/duckdb#6933]
### What happens?

When using `read_parquet(union_by_name=True)` while the `PRAGMA enable_object_cache` has been set, the database segfaults. This behaviour is reproducible in the Python client as well as the CLI.

### To Reproduce

The steps I took to reproduce was to create two parquet files (I used DuckDB to do this)

`create.sql`:
```sql
CREATE TABLE table1 (
    name VARCHAR,
);

INSERT INTO table1 VALUES ('Test value 1!');
INSERT INTO table1 VALUES ('Test value 2!');
COPY table1 TO 'output1.parquet' (FORMAT PARQUET);

CREATE TABLE table2 (
    name VARCHAR,
    number INTEGER,
);

INSERT INTO table2 VALUES ('Other test value', 1);
INSERT INTO table2 VALUES ('Other test value', 2);
COPY table2 TO 'output2.parquet' (FORMAT PARQUET);
```
Create the test data with `duckdb -init create.sql -no-stdin`

---
Reproduction in DuckDB:

`crash.sql`:

```sql
PRAGMA enable_object_cache;

SELECT * FROM read_parquet(['output*.parquet'], union_by_name=True)
```

Run with `duckdb -init crash.sql -no-stdin`
This segfaults

---
Reproduction in Python:
you can use the same `output1` and `output2` parquet files and execute:
```python
import duckdb

con = duckdb.connect(database=":memory:")
con.execute("PRAGMA enable_object_cache;")
con.read_parquet("output*.parquet", union_by_name=True)
```
---
This seems to only happen when `enable_object_cache` is enabled when using `union_by_name=True`

### OS:

Linux 6.2.7-2, x86

### DuckDB Version:

v0.7.2-dev1256 cef3bdcb8c

### DuckDB Client:

CLI & Python

### Full Name:

Ahmad Sattar

### Affiliation:

HASH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have actually been working on the `union_by_name` and this has been fixed as part of #6912. I have added your test case to the PR.
