### ISSUE TITLE
CLI shows wrong version number on start up message

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#6941]
### What happens?

At the time of writing, the latest available pre-release version for DuckDB for R shows as 0.8.0, while for Python it shows as 0.7.2-dev<large number>.

But for the CLI interface, if I compile the project from source through the cmake system and execute the generated binary, upon start up, it shows the version as being 0.3.1-dev<larger number than in python> + <commit hash>.

### To Reproduce

```shell
./duckdb
```

### OS:

Linux

### DuckDB Version:

dev14589 4161f39ca1

### DuckDB Client:

CLI

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
If you're building from your own fork, you'll need to make sure you pull the git tags from the main repo to get the up-to-date version

**Comment by david-cortes** [comment]
> If you're building from your own fork, you'll need to make sure you pull the git tags from the main repo to get the up-to-date version

Also happens if I clone the master branch here as indicated in the instructions for installation.

**Comment by Mytherin** [comment]
Works fine for me:

```bash
git clone git clone https://github.com/duckdb/duckdb
cd duckdb
make
build/release/duckdb
# -- Loading resources from /Users/myth/.duckdbrc
# v0.7.2-dev1322 4161f39ca1
# Enter ".help" for usage hints.
# Connected to a transient in-memory database.
# Use ".open FILENAME" to reopen on a persistent database.
```

Either way, this is not a core DuckDB issue but a documentation issue, so please [file it in the documentation repo](https://github.com/duckdb/duckdb-web).
