### ISSUE TITLE
nullstr is not working for quoted NULL values

### ISSUE THREAD

**Issue by lijose** [duckdb/duckdb#6943]
### What happens?

While trying to read a csv using read_csv_auto where NULL is stored as "null". table still holds "null" as string

### To Reproduce

data.csv 
"a","b"
"1",null
null,"2"

in duckdb 
create table tt as select * from read_csv_auto("data.csv", nullstr="null")
select * from tt where b is null  << retuns no record in Mac, but same is working fine in ubuntu

### OS:

Mac

### DuckDB Version:

0.7.1

### DuckDB Client:

cli

### Full Name:

Lijo Jose

### Affiliation:

self employed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

I cannot reproduce this using the provided example:

```csv
"a","b"
"1",null
null,"2"
```

```sql
create table tt as select * from read_csv_auto(test.csv, nullstr="null");
select * from tt where b is null;
┌───────┬───────┐
│   a   │   b   │
│ int64 │ int64 │
├───────┼───────┤
│     1 │  NULL │
└───────┴───────┘
```

is the null value perhaps quoted in the original CSV file?

**Comment by lijose** [comment]
yes,

```
"a","b"
"1","null"
"null","2"
```
