### ISSUE TITLE
IOException error with no further information

### ISSUE THREAD

**Issue by labanca** [duckdb/duckdb#6956]
### What happens?

I'm starting to learn DuckDB (on Windows 10) and I'm having some problems and I don't find much information about it on the internet.

I'm following the following tutorial for beginners: https://marclamberti.com/blog/duckdb-getting-started-for-beginners/

When I tried to convert csv files to parquet I'm getting the following error:

```
IOException                               Traceback (most recent call last)
Cell In[14], line 6
      4 for filename in glob.iglob(f'{PATH}/csv/*.csv'):
      5     dest = f'{PATH}/parquet/{filename.split("/")[-1][:-4]}.parquet'
----> 6     conn.execute(f"""COPY (SELECT * 
      7         FROM read_csv('{filename}', 
      8         header=True, 
      9         dateformat='%d-%m-%Y', 
     10         columns={{'Date': 'DATE', 
     11             'Low': 'DOUBLE', 
     12             'Open': 'DOUBLE', 
     13             'Volume': 'BIGINT', 
     14             'High': 'DOUBLE', 
     15             'Close': 'DOUBLE', 
     16             'AdjustedClose': 'DOUBLE'}}, 
     17         filename=True)) 
     18         TO '{dest}' (FORMAT 'parquet')""")

IOException: 
```

The error is just "IOException" and no further information is given.

I tried looking up the IOException error regarding DuckDB and found nothing even here on the project's git page. Could someone help me or give me a direction of what this error could be?

### To Reproduce

Right at the beginning of the tutorial, I tried converting csv files to parquet with the following code:

```python
import duckdb
import polars as pl
import sqlalchemy
import glob

conn = duckdb.connect()

PATH = 'stock_market_data/nasdaq'
for filename in glob.iglob(f'{PATH}/csv/*.csv'):
dest = f'{PATH}/parquet/{filename.split("/")[-1][:-4]}.parquet'
conn.execute(f"""
COPY (SELECT * FROM read_csv('{filename}', header=True, dateformat='%d-%m-%Y', columns={{'Date': 'DATE', 'Low': 'DOUBLE', 'Open': 'DOUBLE', 'Volume': 'BIGINT', 'High': 'DOUBLE', 'Close': 'DOUBLE', 'AdjustedClose': 'DOUBLE'}}, filename=True)) 
TO '{dest}' (FORMAT 'parquet')""")
```

The database used in this example is the following: https://www.kaggle.com/datasets/paultimothymooney/stock-market-data

### OS:

Windows

### DuckDB Version:

0.6.0

### DuckDB Client:

Python

### Full Name:

Andrey Morais Labanca

### Affiliation:

State Government of Brazil

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Duplicate of #6931 - but this does start to confirm my suspicion that it's a windows only related issue

**Comment by Mytherin** [comment]
Could you perhaps upgrade to the latest DuckDB version?

**Comment by Mytherin** [comment]
Also if this is an OS specific problem could you perhaps share the exact OS version you are using?

**Comment by labanca** [comment]
Sorry for not specifying, I'm using Windows 10. 

I updated to the latest version of DuckDB and the error persisted.

**Comment by paultiq** [comment]
Code runs fine if you change the path delimiters to backslashes from forward slashes. Duckdb isn't friendly about mixed paths, unlike Python (an annoyance of mine with duckdb, but I recognized the problem since I've made this mistake enough times). 

Make sure 'mydir\parquet' exists.

```
import duckdb
import polars as pl
import sqlalchemy
import glob

conn = duckdb.connect()

delim = "\\"
PATH = '\\mydir\\kaggle_stock_market_data\\stock_market_data\\nasdaq'
for filename in glob.iglob(f'{PATH}\\csv\\*.csv'):
      name = filename.split(delim)[-1]
      dest = f'\\mydir\parquet\\{name}.parquet'
      print(f"{filename} -> {dest}")
      conn.execute(f"""
      COPY (SELECT * FROM read_csv('{filename}', header=True, dateformat='%d-%m-%Y', columns={{'Date': 'DATE', 'Low': 'DOUBLE', 'Open': 'DOUBLE', 'Volume': 'BIGINT', 'High': 'DOUBLE', 'Close': 'DOUBLE', 'AdjustedClose': 'DOUBLE'}}, filename=True)) 
      TO '{dest}' (FORMAT 'parquet')""")
```
FYI: The exception message also was more informative for me, you should probably use a logging/logger to get a little more control here

**Comment by mosegui** [comment]
@labanca I am experiencing a very similar issue, also on Windows 10. Could you please try to reproduce the issue in https://github.com/duckdb/duckdb/issues/6931 and share your exact Windows build number? You can find it in the header of a fresh opened CMD:
![windows_version](https://user-images.githubusercontent.com/38162445/230010893-700710f3-e1a1-4f00-99fc-fc3adc5f3fd5.png)

**Comment by labanca** [comment]
> Code runs fine if you change the path delimiters to backslashes from forward slashes. Duckdb isn't friendly about mixed paths, unlike Python (an annoyance of mine with duckdb, but I recognized the problem since I've made this mistake enough times).
> 
> Make sure 'mydir\parquet' exists.
> 
> ```
> import duckdb
> import polars as pl
> import sqlalchemy
> import glob
> 
> conn = duckdb.connect()
> 
> delim = "\\"
> PATH = '\\mydir\\kaggle_stock_market_data\\stock_market_data\\nasdaq'
> for filename in glob.iglob(f'{PATH}\\csv\\*.csv'):
>       name = filename.split(delim)[-1]
>       dest = f'\\mydir\\parquet\\{name}.parquet'
>       print(f"{filename} -> {dest}")
>       conn.execute(f"""
>       COPY (SELECT * FROM read_csv('{filename}', header=True, dateformat='%d-%m-%Y', columns={{'Date': 'DATE', 'Low': 'DOUBLE', 'Open': 'DOUBLE', 'Volume': 'BIGINT', 'High': 'DOUBLE', 'Close': 'DOUBLE', 'AdjustedClose': 'DOUBLE'}}, filename=True)) 
>       TO '{dest}' (FORMAT 'parquet')""")
> ```
> 
> FYI: The exception message also was more informative for me, you should probably use a logging/logger to get a little more control here
> 
> edit: The exception I saw (0.7.2.dev1256) is:
> 
> > IOException                               Traceback (most recent call last)
> > Cell In[30], line 11
> > 9 for filename in glob.iglob(f'{PATH}/csv/*.csv'):
> > 10       dest = f'{PATH}/parquet/{filename.split("/")[-1][:-4]}.parquet'
> > ---> 11       conn.execute(f"""
> > 12       COPY (SELECT * FROM read_csv('{filename}', header=True, dateformat='%d-%m-%Y', columns={{'Date': 'DATE', 'Low': 'DOUBLE', 'Open': 'DOUBLE', 'Volume': 'BIGINT', 'High': 'DOUBLE', 'Close': 'DOUBLE', 'AdjustedClose': 'DOUBLE'}}, filename=True))
> > 13       TO '{dest}' (FORMAT 'parquet')""")
> > IOException: IO Error: Cannot open file "/mydir/kaggle_stock_market_data/stock_market_data/nasdaq/parquet/csv\AAL.parquet": The system cannot find the path specified.

This solved my problem. The script is working now. It looks like this error is usually a path or disk space issue.
