### ISSUE TITLE
CLI escaping of BLOB values does not properly escape \x7f (DEL)

### ISSUE THREAD

**Issue by brendanyounger** [duckdb/duckdb#6970]
### What happens?

The CLI does not always escape non-printing characters. This makes it difficult to copy/paste BLOB values as the string representation is not always correct.  Perhaps it would be easier to support `x'HEXVALUE'` the way sqlite3 does it?

### To Reproduce

```sql
select '\x7f'::blob as a;
    a = 
```
where one would reasonably expect '\x7f'.

### OS:

OS X

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Brendan Younger

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This is already fixed in the latest master as part of #6654. Feel free to open a separate discussion if you would like to see support added for different blob strings.
