### ISSUE TITLE
`httpfs` extension doesn't work on musl libc systems like Alpine.

### ISSUE THREAD

**Issue by tadpol** [duckdb/duckdb#7002]
### What happens?

It appears that the extension `httpfs` doesn't support [musl](https://musl.libc.org) based systems like [Alpine](https://alpinelinux.org).

```
duckdb.IOException: IO Error: Extension "/root/.duckdb/extensions/v0.7.1/linux_arm64/httpfs.duckdb_extension" could not be loaded: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /root/.duckdb/extensions/v0.7.1/linux_arm64/httpfs.duckdb_extension)
```

### To Reproduce

Dockerfile:
```
FROM python:3.11-alpine

RUN apk add build-base 
RUN pip install duckdb
```

Build that: `docker build -t duck_test:latest .`

Run it: `docker run --rm -it duck_test:latest`

In that shell, now do:
```python
>>> import duckdb
>>> con = duckdb.connect(':memory:')
>>> con.install_extension('httpfs')
>>> con.load_extension('httpfs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.IOException: IO Error: Extension "/root/.duckdb/extensions/v0.7.1/linux_arm64/httpfs.duckdb_extension" could not be loaded: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /root/.duckdb/extensions/v0.7.1/linux_arm64/httpfs.duckdb_extension)
>>> 
```

I tried with `RUN pip install duckdb --upgrade --pre` and got the same results.

Using a Debian or Ubuntu base image loading the extension works as expected.

### OS:

Alpine Linux (both aarch64 and x64)

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

michael conrad tadpol tilstra

### Affiliation:

Exosite

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
Adding libc6-compat moves it a bit further:
```
FROM python:3.11-alpine

RUN apk add build-base libc6-compat
RUN pip install duckdb
```
But then it fails on a __res_init missing, and I am not sure anymore how to proceed.

**Comment by shreyasGit** [comment]
i have same kind of issue, i am trying to use java client API's on a alpine-zulu13-jre docker image. it gives me errors like -  Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libduckdb_java4480084372361105472.so).
Any pointers will be helpful i am kind of stuck here

**Comment by juzeppe9000** [comment]
Same here with nodeJS env
using node:18-alpine image in docker and app fails with an error: 

```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /opt/node_modules/duckdb/lib/binding/duckdb.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/node_modules/duckdb/lib/duckdb-binding.js:4:15)
node:internal/modules/cjs/loader:1203
```

**Comment by fgrehm** [comment]
Hey peeps, not sure if helps but I've recently created https://github.com/fgrehm/libduckdb-docker to support a Ruby app under alpine and the [httpfs ext works fine there](https://github.com/fgrehm/libduckdb-docker/blob/main/tests/test.rb).

**Comment by juzeppe9000** [comment]
In my case helped install gcompat inside the container with alpine and then manua install of duckdb (usage of bullseye image also needs internal install). Copying as for all other npm installed packages doesn't work. yarn install duckdb inside the container works 700+ seconds. But after that everything is ok.

**Comment by iagovar** [comment]
> Same here with nodeJS env using node:18-alpine image in docker and app fails with an error:
> 
> ```
> Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /opt/node_modules/duckdb/lib/binding/duckdb.node)
>     at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
>     at Module.load (node:internal/modules/cjs/loader:997:32)
>     at Module._load (node:internal/modules/cjs/loader:838:12)
>     at Module.require (node:internal/modules/cjs/loader:1021:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (/opt/node_modules/duckdb/lib/duckdb-binding.js:4:15)
> node:internal/modules/cjs/loader:1203
> ```

Same here, with Alpine 3.17 and Node 18+, installing via npm. I've installed gcompat as suggested by the Alpine wiki and I just get a `segmentation fault` when running my script: https://wiki.alpinelinux.org/wiki/Running_glibc_programs

**Comment by csgui** [comment]
For nodejs based projects.

```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /opt/node_modules/duckdb/lib/binding/duckdb.node)
```
I had the same issue above while using `node:16-alpine` as a base image.

My workaraound was rebuild `duckdb/tools/nodejs` inside the alpine image and re-run a `$ npm install <path_to_duckdb/tools/nodejs>`.

Happy to share more details if anyone else is facing the same issue.
