### ISSUE TITLE
duckdb.connect is adding the working directory

### ISSUE THREAD

**Issue by peterchap** [duckdb/duckdb#7003]
### What happens?

I am using duckdb 0.71 on python in windows 11 using VS Code

My script is:

import duckdb

directory = "E:/rapid7/"
db = "domain2.ddb"

con = duckdb.connect(directory + db)

I am getting the following error:

duckdb.IOException: IO Error: Cannot open file "C:\Code\E:/rapid7/domain2.ddb": The filename, directory name, or volume label syntax is incorrect.

My working directory in VS code is C:\Code.  Based on the above code I would expect E:/rapid7/domain2.ddb and would not expect duckdb to add C:\Code

### To Reproduce

See code above

### OS:

Windows 11 x64

### DuckDB Version:

0.71

### DuckDB Client:

python 10.8

### Full Name:

Peter Chaplin

### Affiliation:

ESB Connect ltd

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue :)

I believe the issue here is that your path separator isn't correct, so we don't recognize this as an absolute path on Windows.
Also we've taken a stab at fixing this in the past, but Windows is always tricky <https://github.com/duckdb/duckdb/pull/5852>
