### ISSUE TITLE
date_sub() inconsistency with timestamps and 'week' 

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [duckdb/duckdb#7004]
### What happens?

Came across this working on the tests for Malloy's interval measurement.

If I use `date_sub()` to measure an interval one second shorter than a week, it returns zero weeks. If I use it to measure an interval one second shorter than a year, it returns 52 weeks. I expected it to return 51. Time is complicated and maybe my expectation is wrong?

### To Reproduce

```SQL
SELECT
  DATE_SUB('week', TIMESTAMP '2001-01-01 12:00:00', TIMESTAMP '2001-01-08 12:00:00') as oneWeek,
  DATE_SUB('week', TIMESTAMP '2001-01-01 12:00:00', TIMESTAMP '2001-01-08 11:59:59') as almostWeek,
  DATE_SUB('week', TIMESTAMP '2001-01-01 12:00:00', TIMESTAMP '2002-01-01 12:00:00') as yearWeeks,
  DATE_SUB('week', TIMESTAMP '2001-01-01 12:00:00', TIMESTAMP '2002-01-01 11:59:59') as almostYear
  ```
 
  
  ```
  ┌─────────┬────────────┬───────────┬────────────┐
│ oneWeek │ almostWeek │ yearWeeks │ almostYear │
│  int64  │   int64    │   int64   │   int64    │
├─────────┼────────────┼───────────┼────────────┤
│       1 │          0 │        52 │         52 │
└─────────┴────────────┴───────────┴────────────┘
```

### OS:

MacOs

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Michael Toy

### Affiliation:

Google

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
A (Gregorian) year is not 52 weeks - it is 52 weeks and one day. So I think this is expected.

**Comment by mtoy-googly-moogly** [comment]
Yup, it was a bad test. I suspected it was something obvious and the test was just wrong, but I stared at it for a long time and couldn't come up with the answer. Sorry to bug you. Thanks!
