### ISSUE TITLE
[bug?] `UNION` operation with different datatypes doesn't fail.

### ISSUE THREAD

**Issue by wtfzambo** [duckdb/duckdb#7011]
### What happens?

I'm not sure if this is actually a bug or a feature, but I noticed that when `UNION`ing two tables with same columns that may have different data types, duckdb successfully completes the union and re-casts the incompatible columns to a compatible data type if there is one.

To be fair I'm not complaining, I actually find this quite convenient for what I'm doing, but I thought it was right to report.

### To Reproduce

```python
data = [
    [None, 1, 'a', None],
    ['foo', 2, 'b', None],
    ['bar', 3.0, 42, {'foo': 'bar'}]
]

cols = ['col1', 'col2', 'col3', 'col4']

df = pd.DataFrame(data, columns=cols)
head = df.head(0)
duckdb.sql('SELECT * FROM head UNION SELECT * FROM df')
```

<img src="https://user-images.githubusercontent.com/47462792/230796849-a70600a7-f497-4796-a8ad-c93cad77322b.png" width=50%>

### OS:

Windows 11 Home x64

### DuckDB Version:

0.7.1

### DuckDB Client:

Python 3.10

### Full Name:

Federico Zambelli

### Affiliation:

Vinhood

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! This is indeed not a bug but intended behavior - if the types of a union do not match casts are added to compatible types if possible according to the implicit cast rules in the system, see [here](https://duckdb.org/docs/sql/expressions/cast.html#implicit-casting) for more information.

**Comment by wtfzambo** [comment]
Fantastic, thanks for the explanation! I missed that in the docs as I was looking in the "set operations" part.
