### ISSUE TITLE
DuckDB JDBC doesnt seem to work with timestamps in Tableau

### ISSUE THREAD

**Issue by ryanrozich** [duckdb/duckdb#7013]
### What happens?

I've connected tableau desktop (Mac) to duckdb via 'Other Database (JDBC)' as described here
https://brocktibert.medium.com/use-tableau-to-connect-to-duckdb-e92daad6e7b4

The connection works, and I can see the schema. However when I preview the data I get this error:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/3526287/230909660-42ed32a9-8cd2-47e8-bcbf-5fc3d419410b.png">

In tableau workbook I can work with the varchar fields as dimensions, however whenever I try to use the timestamp fields (truncated to some lower granularity like hour or year) I get the following error
<img width="501" alt="image" src="https://user-images.githubusercontent.com/3526287/230910147-71a6d186-0a69-45a5-8c62-beab6de1d9d4.png">

Are there any known issues with working with timestamps in tableau using the jdbc connector? I am using the ~`SQL92`~  `Postgres` dialect in the JDBC datasource setup wizard in tableau. I have also tried setting it up using the ~`Postgres`~ `SQL92` dialect, and got a different error in the worksheet when trying to work with the timestamp field.

My duckdb database reads from parquet files stored locally
I am on 
* MacOS 13.3.1
*  duckdb v0.7.1 b00b93f0b1
* tableau desktop 2023.1

### To Reproduce

> duckdb database.duckdb
CREATE TABLE f_cj_events_v2 AS SELECT * FROM read_parquet('/path/to/*.parquet');
CHECKPOINT;

(the database needs to include a timestamp field)

(copy duckdb_jdbc-0.7.1 to ~/Library/Tableau/Drivers) MacOS

(in tableau desktop)
Create datasource -> other JDBC -> jdbc:duckdb:///path_to/database.duckdb
Drag the timestamp field to a column, set the granularity to 'Hour'

### OS:

MacOS 13.3.1

### DuckDB Version:

0.7.1

### DuckDB Client:

Tableau (JDBC)

### Full Name:

Ryan Rozich

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Are you able to provide the error you get when you use the postgres dialect? We generally try to provide postgres compatibility

**Comment by ryanrozich** [comment]
Absolutely.. I've posted both the error messages as well as the screenshots for SQL92 and Postgres below. Looks like I actually did paste the error from the postgres dialect above

### POSTGRES DIALECT
```
An error occurred while communicating with the Other Databases (JDBC) data source 'f_cj_events_v2 (main)'
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
java.sql.SQLException: Catalog Error: Scalar Function with name trunc does not exist!
Did you mean "tan"?
LINE 2:   CAST(TRUNC(EXTRACT(YEAR FROM "f_cj_events_v2"."view_received_at")) AS INTEGER) AS "yr:view_received_at:ok"
FROM "main"."f_cj_events_v2" "f_cj_events_v2"
GROUP BY 2...
               ^
SELECT SUM(1) AS "cnt:f_cj_events_v2_0A2AC4C294B143D686A2602064539CC4:ok",
  CAST(TRUNC(EXTRACT(YEAR FROM "f_cj_events_v2"."view_received_at")) AS INTEGER) AS "yr:view_received_at:ok"
FROM "main"."f_cj_events_v2" "f_cj_events_v2"
GROUP BY 2
```

<img width="502" alt="image" src="https://user-images.githubusercontent.com/3526287/230923559-3dc413da-795d-404c-afe3-3dc0a9527fee.png">


### SQL92 DIALECT

```
An error occurred while communicating with the Other Databases (JDBC) data source 'f_cj_events_v2 (main)'
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
java.sql.SQLException: Parser Error: syntax error at or near "TIMESTAMPADD"
LINE 2:   {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM "f_cj_events_v2"."view_received_at"),CAST("f_cj_events_v2"."view_received_at" AS DATE))} AS "thr_view_received_at_ok"
FROM "main"."f_cj_events_v2" "f_cj_events_v2"
GROUP BY 2...
              ^
SELECT SUM(1) AS "cnt_f_cj_events_v2_0A2AC4C294B143D686A2602064539CC4_ok",
  {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM "f_cj_events_v2"."view_received_at"),CAST("f_cj_events_v2"."view_received_at" AS DATE))} AS "thr_view_received_at_ok"
FROM "main"."f_cj_events_v2" "f_cj_events_v2"
GROUP BY 2
```

<img width="713" alt="image" src="https://user-images.githubusercontent.com/3526287/230923778-5f8d1ef5-36bd-4672-b053-2a090f06de12.png">

**Comment by hawkfish** [comment]
When you set the granularity to hour, do you mean you are truncating or extracting the part? Because the generated code looks like it is using Tableau's `DATE_PART` function rather than `DATE_TRUNC` (that's what the `yr:<field name>:ok` pseudo-column name means). In the date pill menu, the first group of date functions create discrete categorical bins; the second group (outlined in red) use continuous truncation.

<img width="237" alt="Date Menu" src="https://user-images.githubusercontent.com/13156216/230924179-d3a0a01f-3b5c-4a8e-9cac-6d58ed2b90a5.png">

But either way, Tableau should have no trouble generating the correct function equivalents for Postgres (it's one of the first SQL dialects I implemented when I was there.) What was the error you got when you used the Postgres dialect?

**Comment by hawkfish** [comment]
(Sorry, simultaneous posts)

Ah it looks like we don't have the Postrgres `TRUNC` function. That's annoying but not too hard to add.

**Comment by hawkfish** [comment]
What's going on here is that Tableau expects `DATE_PART` to always return an integer but PG will return decimals in some cases (e.g., `SECONDS`) so it wraps the part extraction in a `TRUNC` to remove the decimals and then casts it to an `INTEGER`.

**Comment by ryanrozich** [comment]
Thank you @hawkfish - there was a suggestion on discord to implement a function like this in my local duckdb as a workaround

```SQL
CREATE MACRO trunc(x) as cast(x as integer)
```

And this worked when I was extracting the "hour" part in tableau in the pill at the top; however when I try to "truncate" to the hour I get this error:

(Using Postgres dialect for JDBC driver)

<img width="502" alt="image" src="https://user-images.githubusercontent.com/3526287/231264614-3d6df883-7f83-4d29-8b2e-4421b1ae27cf.png">

Error Message
```
An error occurred while communicating with the Other Databases (JDBC) data source 'f_cj_events_v2 (main)'
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
getTimestamp
SELECT DATE_TRUNC( 'HOUR', CAST("f_cj_events_v2"."view_received_at" AS TIMESTAMP) ) AS "thr:view_received_at:ok"
FROM "main"."f_cj_events_v2" "f_cj_events_v2"
GROUP BY 1
```

In fact, it seems with this `TRUNC` macro workaround, all of the "extract" functions work on the timestamp in tableau, but the "truncate" operations do not:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/3526287/231265266-7b94d319-77b3-4332-bb77-6dfdf3f17f53.png">

**Comment by ryanrozich** [comment]
When I run the sql that is listed in the error message below `getTimestamp` from the duckdb CLI I dont get an error:

```SQL
SELECT DATE_TRUNC( 'HOUR', CAST("f_cj_events_v2"."view_received_at" AS TIMESTAMP) ) AS "thr:view_received_at:ok"
FROM "main"."f_cj_events_v2" "f_cj_events_v2"
GROUP BY 1
```

Below is a screenshot running this in my CLI

<img width="819" alt="image" src="https://user-images.githubusercontent.com/3526287/231267447-8bb394e9-0174-4c6c-afc0-ed62aadc3d68.png">

**Comment by hawkfish** [comment]
Hmm the functions all exist (e.g., `DATe_TRUNC`), but there may be a related issue with reading timestamps in JDBC that IIRC is in process.

**Comment by hawkfish** [comment]
This is looking like a JDBC bug now.

**Comment by hawkfish** [comment]
Can you try the [most recent nightly build](https://github.com/duckdb/duckdb/actions/runs/4663150532)?

**Comment by hawkfish** [comment]
I've been working on a proper [Tableau connector](https://github.com/hawkfish/duckdb-taco) and as part of that work I managed to figure out that those strange error messages were an exception being thrown for calls to `getTimestamp(column, Calendar)`. I have a pending fix for that, but it hasn't been well tested yet.

**Comment by ryanrozich** [comment]
@hawkfish  A proper Tableau connector would be 🔥 if you need any help testing it out I'd be happy to. 

Some of the errors and limitations in using the JDBC data source are frustrating, but its pretty awesome to be able to shred through 100s of GBs of parquet files locally in tableau. Beats waiting in query queues for snowflake or redshift serverless :)  It would make a pretty awesome demo for duckdb

Feel free to msg me on discord @GladiatorPoeta

**Comment by hawkfish** [comment]
> @hawkfish A proper Tableau connector would be 🔥 if you need any help testing it out I'd be happy to.
> 
> Some of the errors and limitations in using the JDBC data source are frustrating, but its pretty awesome to be able to shred through 100s of GBs of parquet files locally in tableau. Beats waiting in query queues for snowflake or redshift serverless :) It would make a pretty awesome demo for duckdb

That's exactly the use case I have in mind. There are two other hive partitioning issues I am looking at:

1. Missing files in a deep tree should not be an error
2. Only files actually being scanned should be open (otherwise you can hit too many files open errors).

**Comment by ryanrozich** [comment]
@hawkfish I saw your comment above on trying a nightly build. I'm happy to try it out, how does one switch to a nightly build? I used brew to install duck previously

```shell
(base) ryan@RYANs-MBP ~ % brew info duckdb
==> duckdb: stable 0.7.1 (bottled)
Embeddable SQL OLAP Database Management System
https://www.duckdb.org
/opt/homebrew/Cellar/duckdb/0.7.1 (884 files, 106.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-04-01 at 07:57:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/duckdb.rb
License: MIT
==> Dependencies
Build: cmake ✘
==> Analytics
install: 16 (30 days), 387 (90 days), 3,441 (365 days)
install-on-request: 16 (30 days), 388 (90 days), 3,443 (365 days)
build-error: 0 (30 days)

(base) ryan@RYANs-MBP ~ % duckdb --version
v0.7.1 b00b93f0b1
```

Is there a way to switch to a nightly build using brew, or do I need to download and install separately?

**Comment by hawkfish** [comment]
I don't think you actually need the latest build of the Cl tool because it is embedded in the JDBC driver. The build with the fix is [here](https://github.com/duckdb/duckdb/suites/12533134284/artifacts/669365026).

**Comment by hawkfish** [comment]
Also, if you want the bleeding edge build from master, just go to the installation page and choose macOS/Github master. It will download the binaries that you can directly execute.

**Comment by ryanrozich** [comment]
Should we expect to see the 'truncate aggregation on datetime filed' error resolved with the JDBC driver update? I believe Im still seeing it, but its possible that I didnt install the JDBC driver, here are the steps and the outcomes

1. I downloaded the JDBC jar from the link you pasted abov
2. I moved ducjkdc_jdbc.jar to ~/Library/JDBC/ (macos) as described in the [Tableau documentation] (https://help.tableau.com/current/pro/desktop/en-us/jdbc_tableau.htm).
3. I made the jdbc jar readable by all (777)
4.  I restarted tableau, created a new jdbc data source
5. Opened a worksheet, dragged a timestamp field to the columsn canvas - which worked, the default aggregation is to extract the year
6. I changed the aggregation for the timestamp field to truncate by day and I get the error below

![image](https://github.com/duckdb/duckdb/assets/3526287/c5a3e967-abda-4705-9e34-9cf6be40988b)

Im not sure how to verify that Tableau is in fact reading and using the updated jar that I dropped though.

**Comment by ryanrozich** [comment]
I got the latest nightly JDBC installed and also CLI, and looks like the errors I was seeing with the truncation timestamp aggregation are fixed!

![image](https://github.com/duckdb/duckdb/assets/3526287/1644d17d-a2ca-4506-a9de-e635d985f123)

quick note if anyone else wants to run from the latest: you will likely need to rebuild your database files from the same nightly build as the JDBC driver.

**Comment by hawkfish** [comment]
You should post this in show and tell!

**Comment by Mause** [comment]
Sounds like this is fixed, so I'll close this issue
