### ISSUE TITLE
Registering arrow-backed pandas dataframe with string nulls causes segfault

### ISSUE THREAD

**Issue by gforsyth** [duckdb/duckdb#7019]
### What happens?

Using the new Pandas 2.0 with arrow-backed dtypes raises a segfault on register if the dataframe in question has any string nulls.

This doesn't seem to happen with any other dtypes that I checked (`int`, `uint`, `boolean`)

### To Reproduce

```python
[ins] In [1]: import duckdb

[ins] In [2]: duckdb.__version__
Out[2]: '0.7.2-dev1637'

[ins] In [3]: import pandas as pd

[ins] In [4]: pd.__version__
Out[4]: '2.0.0'

[ins] In [5]: df = pd.DataFrame({"a": pd.Series([None, None], dtype="string[pyarrow]")})

[ins] In [6]: df.dtypes
Out[6]: 
a    string[pyarrow]
dtype: object

[ins] In [7]: con = duckdb.connect()

[ins] In [8]: con.register("t", df)

Segmentation fault (core dumped)
```

### OS:

ubuntu 22.04 x64

### DuckDB Version:

0.7.2-dev1637

### DuckDB Client:

Python

### Full Name:

Gil Forsyth

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Can you reproduce this with #7005 ?
Because on master this is expected currently

**Comment by gforsyth** [comment]
Oops, sorry @Tishj -- building that PR and I'll report back.

**Comment by Tishj** [comment]
No problem, hope it also fixes this issue :)
Also I'm not sure this actually produces pyarrow-backed columns, using the DataFrame constructor I believe it only creates numpy-backed columns

**Comment by gforsyth** [comment]
yep, can confirm.  I'll close this out.  Thanks @Tishj !
