### ISSUE TITLE
timestampformat option for csv copy does not work with timestamptz

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#7060]
### What happens?

The `timestampformat` argument described [here](https://duckdb.org/docs/sql/statements/copy#csv-options) allows you to customize the formatting of timestamps when converting to CSV, but it does not work with the `timestamp with time zone` type.

### To Reproduce

Here's a simple reproduction using the Python client

```python
import duckdb

conn = duckdb.connect(database=':memory:')

conn.execute("""
copy (
select current_timestamp::timestamp as ts, current_timestamp as tstz
) to 'timestamps.csv' (header 1, timestampformat '%A');
""")

with open('timestamps.csv') as csv:
    print(csv.read())
```

Which produces the output

```
ts,tstz
Wednesday,2023-04-12 15:36:18.726-07
```

### OS:

macOS, Linux

### DuckDB Version:

0.7.1, 0.7.2.dev1684

### DuckDB Client:

Python, NodeJS

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by dylanscott** [comment]
This is particularly annoying because the default format for `timestamptz` is not recognized by either Excel or Google Sheets as a timestamp.

**Comment by Mytherin** [comment]
Thanks for the report!

@pdet could you perhaps pick this up after your CSV reader changes have been merged?
