### ISSUE TITLE
Inconsistent Regexp Behavior with Inline (?i) Modifier

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#7068]
### What happens?

Using an inline modifier for case insensitive matches (?i), and a varchar value from a table containing a single value 'abc', the following expression returns false: `select regexp_matches(col1, '(?i)ABC')`

Yet, it returns True with a literal 'abc':  `select regexp_matches('abc', '(?i)ABC')`

Also returns True with other similar/equivalent formulations, like: `select regexp_matches(col1, '(?i)AB[C]')`

### To Reproduce

The first two regexp_matches expressions evaluate to False, yet the equivalent expressions written with literals evaluates to True. 

`regexp_matches(col1, '(?i)ABC'),` should evaluate to True, since "col1" contains a single value: abc
The equivalent version with literal 'abc' evaluates to True: `regexp_matches('abc', '(?i)ABC')`

```
CREATE OR REPLACE TABLE datatest as SELECT 'abc' as col1; 

SELECT 
    col1, 
    regexp_matches(col1, '(?i)ABC'), -- False??
    regexp_matches(col1, '(?i)AB[C]'), -- False??
    regexp_matches(col1, '(?i)abc') as t1_lower, -- False??

    -- Below this line everything evaluates to True, yet are more or less equivalent 
    -- to the first version
    regexp_matches(col1, 'ABC', 'i'), -- This should be same as #1
    regexp_matches(col1, '(?i)ABC$'), -- $ = end of input
    regexp_matches(col1, '(?i)AB[C]+'), 
    regexp_matches(col1, '(?i)AB[C]?'), 

    -- Using literal 'abc' works as expected
    regexp_matches('abc', '(?i)ABC'), 
    regexp_matches('abc', '(?i)AB[C]'), 
    regexp_matches('abc', '(?i)ABC$'), 
    regexp_matches('abc', '(?i)AB[C]+'), 
    regexp_matches('abc', '(?i)AB[C]?') 
FROM 
    datatest
```

### OS:

Windows

### DuckDB Version:

0.7.2-dev1734	

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hmm first thing that comes to mind is the optimizer might be at fault?
can you try it again after running `pragma disable_optimizer;` ?

**Comment by paultiq** [comment]
Yes, that fixes it.
