### ISSUE TITLE
Pandas gets TEXT as object (not string)

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#7084]
### What happens?

If you have a `VARCHAR` then `.df()` gives you an `object`, not `string`.

### To Reproduce

This extends https://github.com/duckdb/duckdb/issues/1401#issuecomment-779687083:

```py
import duckdb
import pandas as pd

df = pd.DataFrame({'a': pd.Series(['x', 'y', 'z'], dtype='string')})
con = duckdb.connect(database=':memory:', read_only=False)
con.register('df', df)
print("DESCRIBE")
print(con.sql('DESCRIBE df;').fetchall())

df = con.execute('SELECT a FROM df;').df()
print("SELECT")
print(df.dtypes)
```

```
DESCRIBE
[('a', 'VARCHAR', 'YES', None, None, None)]
SELECT
a    object
dtype: object
```

### OS:

x64

### DuckDB Version:

0.7.2.dev1734

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I'm a little confused, is there actually a `string` dtype? Does it not just use `object`?

**Comment by paultiq** [comment]
Yah, it's just rarely seen because strings default to objects.

```
df = pd.DataFrame({"col1": ["a"]})
print(df.dtypes)
# col1    object
# dtype: object

df = pd.DataFrame({"col1": ["a"]}, dtype="string")
print(df.dtypes)
# col1    string[python]
# dtype: object
```

**Comment by Tishj** [comment]
We can't support this very easily, because we first create numpy arrays, and create a dataframe from the numpy arrays.
`string` is an ExtensionDtype, added by Pandas, it's not a basic numpy dtype

**Comment by Alex-Monahan** [comment]
What about the pyarrow backed version? Would that be easier?
https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html

**Comment by Tishj** [comment]
> What about the pyarrow backed version? Would that be easier? https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html

We cant directly create pyarrow backed dataframes yet, pandas simply doesnt have the option to do so
`convert_dtypes` is the only way to create a pyarrow backed df, but for that we first need to construct a dataframe.
So that would cause the creation to essentially be numpy -> pandas(numpy) -> pandas(pyarrow)

**Comment by paultiq** [comment]
An alternate approach to original question is using arrow() w/ a types_mapper. In the original case: 
```
t = duckdb.sql("select 'a string'").arrow()
df = t.to_pandas(types_mapper={pa.string(): pd.StringDtype()}.get)

print(df.dtypes)
# 'a string'    string[python]
# dtype: object
```

> Using df.convert_dtypes is the only way to convert an existing df into a pyarrow backed df

Alternatively: you can use the pd.ArrowDtype types_mapper. This is what I do: I use arrow() as my intermediate format from duckdb, and defer the datatype decision... I don't use any custom types_mappers tho. 
- numpy backed df: 
`duckdb.sql("...").arrow().to_pandas()`
- pyarrow backed df [pd.ArrowDtype](https://pandas.pydata.org/docs/reference/api/pandas.ArrowDtype.html): 
`duckdb.sql("...").arrow().to_pandas(types_mapper=pd.ArrowDtype)`
- polars, etc...

_This approach of using arrow() instead of df() was motivated by something @Mytherin said about parallelism being determined by the entire pipeline_

**Comment by Tishj** [comment]
@paultiq I definitely need to look into that, haven't experimented with that method of creation yet.
That might be an easy way of enabling creating a pyarrow backed dataframe as result from duckdb.
(essentially just wrapping the code you used in `relation.df('pyarrow')`

**Comment by paultiq** [comment]
> @paultiq I definitely need to look into that, haven't experimented with that method of creation yet. That might be an easy way of enabling creating a pyarrow backed dataframe as result from duckdb. (essentially just wrapping the code you used in `relation.df('pyarrow')`)

Two footnotes from my testing, fyi: 
1. Duplicate column names need to be dealt with, as this will throw an ValueError: Found non-unique column index: 
`con.execute("select 'a' as col1, 'b' as col1").arrow().df() `
2. In a few simple export throughput tests (just moving lots of rows through duckdb, with no computation), what I saw was arrow -> a pyarrow typed df  is about 2x faster than duckdb.df()... it's just arrow() with an extremely quick zero-copy creation of the dataframe. I was hoping duckdb.arrow().to_pandas() /numpy backed would be better, but duckdb.df() is about 3x faster than duckdb.sql("...").arrow().to_pandas().

**Comment by Tishj** [comment]
> > @paultiq I definitely need to look into that, haven't experimented with that method of creation yet. That might be an easy way of enabling creating a pyarrow backed dataframe as result from duckdb. (essentially just wrapping the code you used in `relation.df('pyarrow')`)
> 
> Two footnotes from my testing, fyi:
> 
> 1. Duplicate column names need to be dealt with, as this will throw an ValueError: Found non-unique column index:
>    `con.execute("select 'a' as col1, 'b' as col1").arrow().to_pandas() `
> 2. In a few simple export throughput tests (just moving lots of rows through duckdb, with no computation), what I saw was arrow -> a pyarrow typed df  is about 2x faster than duckdb.df()... it's just arrow() with an extremely quick zero-copy creation of the dataframe. I was hoping duckdb.arrow().to_pandas() /numpy backed would be better, but duckdb.df() is about 3x faster than duckdb.sql("...").arrow().to_pandas().

PyArrow -> NumPy is probably not zero-copy, so you still end up paying a lot for conversion

**Comment by paultiq** [comment]
> PyArrow -> NumPy is probably not zero-copy, so you still end up paying a lot for conversion

For sure. 

My surprise was the performance difference between duckdb.df() and arrow().to_pandas() [both numpy backed]. Both should be comparable in terms of performance, as they both need to create new numpy series. duckdb's df() was significantly faster. Kudos to you/duckdb for that.
