### ISSUE TITLE
Duckdb crashes kernel

### ISSUE THREAD

**Issue by dominijk** [duckdb/duckdb#7087]
### What happens?

On reading a large parquet file in duckdb 0.7.0 +  kernel crashes. File can be read to dataframe by pandas and by duckdb in verions 0.6.0 and 0.6.1 I'm unable to share the file but if theres a large parquet test file i can see if that reproduces the error. I spend a while debugging having initially thought the error was from another package or jupyter 

 

### To Reproduce

Load large file (~8gb, 16m rows, 70 cols) into duckdb with 

```python
%%sql 
create table 
big_table 
as 
select
* 
from 
dataframe_of_big_parquet_file
```

Connect is using ipython-sql and duckdb-engine in VS Code as

```python
import os
import glob
import pandas as pd
import pyarrow as pa
import duckdb
import gc
%reload_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
````

Running in a virtual environment created by `pdm` with config as:

```bash
dependencies = [
    "pandas>=2.0.0",
    "pyarrow>=10.0.1",
    "duckdb>=0.6.1",
    "duckdb-engine>=7.0.0",
    "ipython-sql==0.4.1",
    "pip>=23.0.1",
    "ipykernel>=6.22.0",
]
requires-python = ">=3.9,<=3.10"
```

### OS:

iOS

### DuckDB Version:

0.7 and higher

### DuckDB Client:

Python in notebook

### Full Name:

Dom H

### Affiliation:

academic

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Does the crash still occur if you disable autopandas?

**Comment by Mause** [comment]
Also, can you please confirm your OS? You're running a Notebook on iOS?

**Comment by dominijk** [comment]
thanks @Mause , i did test with autopandas disabled (same crash) . I'm on iOS 12.6.5 (monterey). This is what the jupyter log looks like for reference:

````bash
info 11:16:21.791: Dispose Kernel process 26158.
error 11:16:21.791: Raw kernel process exited code: undefined
error 11:16:21.792: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:32419)
	at /Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:51471
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:51456)
	at y.dispose (/Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:44938)
	at /Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:96826
	at ee (/Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1589492)
	at jh.dispose (/Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:96802)
	at Lh.dispose (/Users/username/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:104079)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 11:16:21.792: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 11:16:21.792: Cancel all remaining cells true || Error || undefined
```

With autopandas enabled there's additional errors:

```bash
info 11:20:40.747: Process Execution: > ~/Documents/GitRepo/reponame/.venv/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"fe488ca7-e2fc-438c-9a4b-4b325478b0ad" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/username/Library/Jupyter/runtime/kernel-v2-26457gOCQnLlM2w4g.json
> ~/Documents/GitRepo/reponame/.venv/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"fe488ca7-e2fc-438c-9a4b-4b325478b0ad" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/username/Library/Jupyter/runtime/kernel-v2-26457gOCQnLlM2w4g.json
````

**Comment by Mytherin** [comment]
Is this an actual crash or is the process being killed by the OOM killer after running out of memory? I'm guessing everything exists in memory here (the Pandas file, the DuckDB database, etc). How much RAM does your machine have? Perhaps try connecting to an on-disk database instead so the data can be written to disk?

**Comment by dominijk** [comment]
This occurs with an on-disk db the machine has 64gb RAM

**Comment by Mytherin** [comment]
Could you perhaps try setting `SET preserve_insertion_order=false` to check if that resolves the issue?

**Comment by dominijk** [comment]
> Could you perhaps try setting `SET preserve_insertion_order=false` to check if that resolves the issue?

I can do that and will reply here

**Comment by dominijk** [comment]
That didn't resolve, if you have a specfic virtual envionronment i could run on mac with vs code with a named python version i can try running that

**Comment by dominijk** [comment]
The same data will load ok from a parquet file but not from a pandas dataframe 

Runs ok, takes 31 seconds compared to 5 to load using `pd.read_parquet`
```python
%%sql 
create table test_run_parquet_read 
as select * from 'df_processed.parquet'
````

Running
```python
%%sql 
create table test_run_df_read 
as select * from df_processed
```
Crashes kernel

**Comment by Mytherin** [comment]
Are you sure the issue is not that the Pandas DataFrame is taking up tons of memory which leaves too little memory for DuckDB? Could you try reducing DuckDB's memory limit (`SET memory_limit='XGB'`) when the Pandas DataFrame is there?

**Comment by dominijk** [comment]
Switching to a new virtual environment as below. This allows the dataframe to load but the data won't persist on the disk. It shows during a session but if you close that or restart the kernel it's not there, the connection is showing as the file path to a permanent copy. Going to try another connection method.  

````bash
dependencies = [
    "duckdb>=0.7.1",
    "duckdb-engine>=0.7.0",
    "jupysql>=0.7.1",
    "pandas>=2.0.0",
    "jupyter>=1.0.0",
    "pyarrow>=11.0.0",
    "seaborn>=0.12.2",
]
requires-python = ">=3.10,<=3.11"
````

**Comment by dominijk** [comment]
For me this is now closed by moving to a setup of:

- VS Code
- Mac OS
- Virtual environment managed by `pdm` package with packages below

````bash
dependencies = [
    "duckdb>=0.7.1",
    "duckdb-engine>=0.7.0",
    "pandas>=2.0.0",
    "jupyter>=1.0.0",
    "pyarrow>=11.0.0",
    "seaborn>=0.12.2",
    "magic-duckdb>=0.1.25",
]
requires-python = ">=3.10,<=3.11"
````
Big thanks to @Mytherin  for responding and @paultiq for building magic-duck

**Comment by dominijk** [comment]
I got this again with a dataset that is open access, once i'm past a deadline i'll post the example. The resolution for me was in datatype handling. The crashed occured on a large dataframe where python had set many columns to object type. Setting those to a string / defined type prevented the crash, so perhaps something to do with memory use as duckdb tries to infer datatype on pandas / python object types?
