### ISSUE TITLE
Multiple Schema Mismatch Error Needs Original File

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#7091]
### What happens?

When there is a schema mismatch, the error message reports the conflicting file, but not the "original file".

### To Reproduce

Put two parquet files next to each other with different schemas and glob them. It will only report the second one as an error, even though in practice the error might be in the first one.

### OS:

OSX

### DuckDB Version:

0.7.2-dev1803

### DuckDB Client:

CLI

### Full Name:

Richard Wesley

### Affiliation:

Effervescence Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
Maybe @lverdoes can check this one out?

**Comment by lverdoes** [comment]
Looks like it was the previous behaviour to output the original filename
