### ISSUE TITLE
Syntax error on vacuum with column names

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#7096]
### What happens?

When running a vacuum on a column in a table a parser error is thrown. This doesn't happen if there is an analyze associated with the vacuum, or if no columns are specified.

### To Reproduce

```sql
create table t1(id int, val int);
vacuum t1(id, val);
vacuum memory.main.t1(id, val);
```

Output
```
D create table t1(id int, val int);
D vacuum t1(id, val);
Error: Parser Error: syntax error at or near "("
LINE 1: vacuum t1(id, val);
                 ^
D vacuum memory.main.t1(id, val);
Error: Parser Error: syntax error at or near "("
LINE 1: vacuum memory.main.t1(id, val);
                             ^
D vacuum analyze memory.main.t1(id, val);
D 
```

### OS:

Ubuntu Linux 22.10

### DuckDB Version:

v0.7.2-dev1898 eaf507009f

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

Mode Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #7110.
