### ISSUE TITLE
Misleading error message when omitting column list in foreign key REFERENCES clause

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7118]
### What happens?

In most SQL dialects, it's possible to omit the referenced column list in a `REFERENCES` clause. This means that the `PRIMARY KEY` should be chosen automatically.

In DuckDB, there's a misleading error message about column arity, when there should be a parser error rejecting the syntax.

Alternatively, the feature could be implemented correctly, as in most dialects.

### To Reproduce

Run this:

```sql
create table a (i int primary key);
create table b (i int references a);
```

There's an error:

> Parser Error: The number of referencing and referenced columns for foreign keys must be the same

But the syntax is valid, see ISO/IEC 9075-2:2016(E) 11.8 &lt;referential constraint definition> Format of `<referenced table and columns>` and Syntax Rules 4) b)

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.1

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! We already supported this syntax for the stand-alone `FOREIGN KEY` syntax - I have pushed support for the single-column variant in #7237

**Comment by Mytherin** [comment]
This is fixed
