### ISSUE TITLE
Foreign key REFERENCES column list is case sensitive when looking up primary keys

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7119]
### What happens?

It seems that DuckDB doesn't really have case sensitive identifiers. But there's an exception when declaring a `PRIMARY KEY` column list, then the `REFERENCING` column lists must have matching cases, which I think is a bug.

Probably related: 

- https://github.com/duckdb/duckdb/issues/2075
- https://github.com/duckdb/duckdb/issues/7120

### To Reproduce

This doesn't work:

```sql
create table a (a int not null, constraint pk_a primary key (A));
create table b (a int references a (a));
```

There's an error:

> Binder Error: Failed to create foreign key: referenced table "a" does not have a primary key or unique constraint on the columns a

To fix this error, either declare the column list of the `PRIMARY KEY` in lower case:

```sql
create table a (a int not null, constraint pk_a primary key (a));
create table b (a int references a (a));
```

Or use matching upper case in both `PRIMARY KEY` and `REFERENCES` list:

```sql
create table a (a int not null, constraint pk_a primary key (A));
create table b (a int references a (A));
```

This took me a while to pinpoint, very subtle, especially since the error message is quite misleading :)

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.1

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report and investigative work! I have pushed a fix in #7236 for both this and #7120
