### ISSUE TITLE
Julia: version of lib_DuckDB uploaded for DuckDB_jll is prerelease

### ISSUE THREAD

**Issue by frankier** [duckdb/duckdb#7127]
### What happens?

The version of DuckDB used by the Julia package is a prerelease. As well as meaning the release version is misleading and could have inconsistencies with the same version obtained through other channels, it has the unfortunate consequence that extension fetching does not work.

### To Reproduce

You can demonstrate it is a prerelease like so

Go to https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/tag/DuckDB-v0.7.1%2B0

Download a version (linux/glibc/x64 for me)

Extract and run duckdb

```
$ ./bin/duckdb
v0.7.2-dev1987 ae9bcc347c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D 
```

Trying to remote install an extension

`DBInterface.execute(con, "INSTALL 'json'")`

```
ERROR: LoadError: Execute of query "INSTALL 'json'" failed: HTTP Error: Failed to download extension "json" at URL "http://extensions.duckdb.org/ae9bcc347c/linux_amd64/json.duckdb_extension.gz"
Extension "json" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```

### OS:

Linux

### DuckDB Version:

0.7.1

### DuckDB Client:

Julia

### Full Name:

Frankie Robertson

### Affiliation:

University of Jyväskylä

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Should be fixed now
