### ISSUE TITLE
Performance of querying arrow tables depends (heavily) on number of batches

### ISSUE THREAD

**Issue by legout** [duckdb/duckdb#7133]
### What happens?

The amount of time needed to perform queries on arrow tables heavily depends of the number of batches, the table consists of.

### To Reproduce

Here is some example code for the observed behavior.

```python
import pyarrow.parquet as pq
import duckdb

# 484 batches
table_arrow_org = pq.read_table("path/to/data")
print(table_arrow_org.shape)
# (5574972, 64)

%timeit res=duckdb.sql("SELECT group, count(date), max(date), min(date), mean(colA) FROM table_arrow_org GROUP BY group").arrow()
# 144 ms ± 5.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 1 batch
table_arrow_combined = table_arrow_org.combine_chunks()

%timeit res=duckdb.sql("SELECT group, count(date), max(date), min(date), mean(colA) FROM table_arrow_combined GROUP BY group").arrow()
# 11.2 ms ± 40.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# ~ 5 batches
table_arrow_5_chunks = pa.Table.from_batches(table_arrow_combined.to_baches(max_chunksize=1_000_000)

%timeit res=duckdb.sql("SELECT group, count(date), max(date), min(date), mean(colA) FROM table_arrow_5_chunks GROUP BY group").arrow()
# 17.8 ms ± 52.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### OS:

Ubuntu-22.04  on x86

### DuckDB Version:

0.7.2-dev2144

### DuckDB Client:

python

### Full Name:

Volker Lorrmann

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Just a quick clarification, your LinkedIn says you work for Siemens as Senior Data Scientist, this question is in a purely private capacity I take it?

**Comment by legout** [comment]
> Just a quick clarification, your LinkedIn says you work for Siemens as Senior Data Scientist, this question is in a purely private capacity I take it?

Yes. I found this while working on my own python lib, which (https://github.com/legout/pydala).

**Comment by hannes** [comment]
The behaviour you observe is pretty much expected, each batch will cause some management overhead. So try to balance batch size with memory usage to try to keep them on the large-ish side. As a rule of thumb, batch size should be in the tens of thousands of row (depending a bit of course on column count).

**Comment by legout** [comment]
Thanks. 

The shape of my example dataset was  (5574972, 64). At least for this table the query runs fastest for the table with only one batch. 

Originally, I found this, while comparing the time running a query on a arrow table compared to running the same query on a polars dataframe (derived from the same arrow table with `pl.from_arrow(arrow_table)`. The latter was 10x faster.
