### ISSUE TITLE
Casted JSON is always truncated 

### ISSUE THREAD

**Issue by niger-prequel** [duckdb/duckdb#7134]
### What happens?

When generating a nested `JSON` type using `json_build` and casting it to a string on SELECT we experience the resulting string to be truncated to 255 characters. That means the resultant json string is not only frequently invalid, it doesn't represent the data. 

### To Reproduce

```sql
	CREATE VIEW test AS
	SELECT 
		md5(CAST(range AS TEXT)) as id, 
		to_timestamp(range) updated_at,
		CAST(range % 32767 AS SMALLINT) as test_smallint,
		CAST(range AS INTEGER) as test_integer,
		CAST(range AS BIGINT) as test_bigint,
		CAST(range / 3.0 AS REAL) as test_real,
		CAST(range / 3.0 AS DOUBLE) as test_double,
		CAST(range AS DECIMAL) as test_decimal,
		CASE WHEN range % 2 = 0 THEN TRUE ELSE FALSE END AS test_boolean,
		DATE '2022-02-24' - TO_DAYS(CAST(range % 3650 AS INTEGER)) as test_date,
		json_object('number', range) as test_json,
		CASE range % 6 WHEN 0 THEN 'madison' WHEN 1 THEN 'boston' WHEN 2 THEN 'redmond' WHEN 3 THEN 'sacramento' WHEN 4 THEN 'anchorage' WHEN 5 THEN 'reno' END as test_enum 
	FROM range(10000)
```

Then

```sql
SELECT
  CAST(json_object(
	        'id', id,
                'updated_at', updated_at,
                'test_smallint', test_smallint,
                'test_integer', test_integer, 
                'test_bigint', test_bigint,
		'test_bigint', test_bigint,
		'test_real', test_real,
		'test_double', test_double,
		'test_decimal', test_decimal,
		'test_boolean', test_boolean,
		'test_date', test_date,
		'test_json', test_json,
		'test_enum', test_enum) AS VARCHAR) as blob_data
) FROM test

```

All the resulting JSON values will then be truncated to 255 characters.

### OS:

Linux

### DuckDB Version:

0.7.0

### DuckDB Client:

ODBC

### Full Name:

Niger Little-Poole

### Affiliation:

Prequel

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Thanks for the bug report. Just tested this in the CLI and cannot reproduce it. I suspect it is an issue with the ODBC

**Comment by lnkuiper** [comment]
Sorry for the late reply. I meant that I cannot reproduce this in the DuckDB CLI, so it's not an issue with DuckDB internals, but rather an issue with DuckDB + ODBC
