### ISSUE TITLE
ODBC: unsupported column type 0 (not Decimal)

### ISSUE THREAD

**Issue by niger-prequel** [duckdb/duckdb#7135]
### What happens?

Receive a `unsupported column type 0` error. However this does not occur with the same file (generated from Clickhouse) in DuckDB ODBC 0.6.0. This has only started occurring in 0.7.0. We were forced to revert back due to this. 

### To Reproduce

```sql
-- exclude test_decimal as that is known to not have ODBC support
SELECT id, amount, ... FROM read_parquet('based1.parquet');
```

[based1.parquet.zip](https://github.com/duckdb/duckdb/files/11262880/based1.parquet.zip)

### OS:

Linux amd64

### DuckDB Version:

0.7.0

### DuckDB Client:

ODBC

### Full Name:

Niger Little-Poole

### Affiliation:

Prequel

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think related to #7128
If not, can you please provide what the type is, suspecting it converts to BIT

**Comment by Tishj** [comment]
Out of the columns, `test_bytea` sounds like it would convert to BIT, which is what the linked issue is about

**Comment by niger-prequel** [comment]
Would that error happen even if `test_bytea` isn't in the SELECT clause? Because we're seeing that error even without `test_bytea` included. I can manually try every column but I was hoping not to have to do that.

**Comment by niger-prequel** [comment]
Been narrowing it down manually and it seems like its either `test_text` or `test_timestamp`

**Comment by niger-prequel** [comment]
[test_logs7.parquet.zip](https://github.com/duckdb/duckdb/files/11265057/test_logs7.parquet.zip)
[test_logs_metadata.csv](https://github.com/duckdb/duckdb/files/11265073/test_logs_metadata.csv)

Here is a more narrow parquet file where we are seeing the same issue. The only types in here are `timestamp` and `string`. I've attached the results of `SELECT * FROM parquet_metdata(...)` as well

**Comment by Tishj** [comment]
Went on a search for the exception, but I can't find anything like
`unsupported column type *`

Can you post the full error?

**Comment by niger-prequel** [comment]
Just `unsupported column type 0`, nothing else. I raised[ this issue](https://github.com/duckdb/duckdb/issues/5947) before and the cause is that the Decimal type wasn't implemented for ODBC as far as I can tell. I imagine something changed from 0.6.1 to 0.7.0 that broke serialization between DuckDB and another ODBC type.

**Comment by Tishj** [comment]
@maiadegraaf maybe you could have a look at this

**Comment by maiadegraaf** [comment]
How do you access the driver and execute the query? Here is the snippet in CPP that successfully reads from the parquet file, but I would be interested to know if your method is different. 

```cpp
// Read from parquet file
SQLRETURN ret = SQLExecDirect(hstmt, (SQLCHAR*)"SELECT * FROM parquet_scan('source_schema_buynlarge_prequel_transactions_ohrwd_snapshot_000000000000.parquet')", SQL_NTS);
if (ret == SQL_ERROR) {
	std::cout << "FAILURE" << std::endl;
}

// Get column number
SQLSMALLINT num_cols;
SQLNumResultCols(hstmt, &num_cols);

// Fetch and print all rows
while(SQLFetch(hstmt) != SQL_NO_DATA) {
	for (int i = 0; i < num_cols; i++) {
		SQLLEN len;
		SQLCHAR buf[1024];
		SQLGetData(hstmt, i + 1, SQL_C_CHAR, buf, sizeof(buf), &len);
		std::cout << buf << " ";
	}
	std::cout << std::endl;
}
```

**Comment by niger-prequel** [comment]
@maiadegraaf sorry for the delayed response we're heads down on some other things. We switched a while ago to the Golang Driver but at the time we were encountering this we were using the `github.com/duneanalytics/odbc` to interact with the ODBC driver. We've had no problems on decimal types with other ODBC drivers (Simba, Snowflake, etc)

**Comment by maiadegraaf** [comment]
Hi @niger-prequel since I haven't been able to confirm if this issue is persistent, I'm going to close this issue for now.  Feel free to open another issue if you rencounter it.
