### ISSUE TITLE
json_keys() returns `Unsupported result column type VARCHAR[]' with DuckDB JDBC driver.

### ISSUE THREAD

**Issue by ashiner** [duckdb/duckdb#7139]
### What happens?

The json_keys() method returned an error when using the DuckDB in PyCharm with the duckdb_jdbc-0.7.1.jar  driver.

### To Reproduce

INSERT INTO example VALUES
  (' { "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }');
select json_keys(j) from example;

Returns the error `Unsupported result column type VARCHAR[]'

Note that the json_keys() example in the documentation at:
https://duckdb.org/docs/extensions/json.html

Is missing the argument in the code example:
SELECT json_keys FROM example;

### OS:

Mac OS 13.2.1 (22D68)

### DuckDB Version:

duckdb_jdbc-0.7.1.jar 

### DuckDB Client:

Pycharm IDE

### Full Name:

Andrew Shiner

### Affiliation:

Ciena

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hiya, this has been fixed on the latest master branch build as of #7000, can you confirm that you tried it on that version?

**Comment by ashiner** [comment]
I am testing with version 0.7.1 from the mvn repository:
https://mvnrepository.com/artifact/org.duckdb/duckdb_jdbc/0.7.1

Is there another place that I should be pulling the jar file form?

**Comment by Mause** [comment]
The link is in the issue template you filled out: https://duckdb.org/docs/installation/

If you click the master build tab, there snapshot repo details are listed
