### ISSUE TITLE
ADBC Integration

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#7141]
This issue keeps track of missing features in the [ADBC integration](https://arrow.apache.org/adbc/0.3.0/cpp/api/adbc.html).

##  **Core**
- [x] Support Windows Build
- [x] ConnectionCommit 
- [x] ConnectionGetTableSchema (@pdet)
- [ ] ConnectionGetInfo (@Tishj)
- [x] ConnectionReadPartition (Added proper unsupported error messages on the DuckDB side)
- [x] ConnectionRollback 
- [ ] StatementBind  (@Tishj)
- [x] StatementExecutePartitions (Added proper unsupported error messages on the DuckDB side)
- [ ] StatementGetParameterSchema  (@Tishj)
- [x] StatementSetSubstraitPlan (@pdet)

##  **Testing**
- [x] Windows CI
- [x] Unhappy Paths (Null DB, Double-Release, etc...)

cc @lidavidm please let me know if something else is missing or if there is a preferred order for these to be tackled/implemented.

**Comment by lidavidm** [comment]
Thanks!

The two Partition calls probably don't make sense for DuckDB and can be ignored.

If there's something in DuckDB you think isn't adequately reflected in ADBC, we are working towards a 1.1 revision of the API, too.

**Comment by szarnyasg** [comment]
@pdet can you please review this issue to see whether it still has any relevant (unsupported) parts?
