### ISSUE TITLE
Hang on `SELECT` query

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#7143]
### What happens?

The following program will cause DuckDB hang and occupy all CPUs:
```
CREATE TABLE t0(c0 BOOL);
CREATE TABLE t1(c0 DATE);

INSERT INTO t0(c0) VALUES ((true));
INSERT INTO t1(c0) VALUES (DEFAULT);

CREATE VIEW v93(c0, c1, c2) AS SELECT true, true, true FROM t0, t1 WHERE t0.c0 OFFSET (624262942); 

SELECT (t0.c0), (t0.rowid) FROM t0, v93 NATURAL FULL JOIN t1 WHERE ((t0.rowid) ::BOOL);
```

### To Reproduce

I build DuckDB from the last commit version https://github.com/duckdb/duckdb/commit/5f6c51b0c295bf4edf7b3f8497d557c433f8b928

### OS:

ubuntu 22.04

### DuckDB Version:

https://github.com/duckdb/duckdb/commit/5f6c51b0c295bf4edf7b3f8497d557c433f8b928

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
I do reproduce against https://github.com/duckdb/duckdb/commit/5f6c51b0c295bf4edf7b3f8497d557c433f8b928 but not anymore against latest master (https://github.com/duckdb/duckdb/commit/a777a19fff), so I believe this is solved.

Thanks for raising this though!
