### ISSUE TITLE
[C-API] `string_t` definition is missing from `duckdb.h`

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#7154]
### What happens?

When using the data chunk API, to access the data of the Vectors, we need to cast the data pointer into a type that has the same memory layout as `duckdb::string_t`, which is defined in the C++ API, and currently not exposed to the C-API

This should also be added to the docs once it's added, since it's not super obvious what the internal representation of our VARCHAR columns is.

### To Reproduce

-

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

C-API

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Agreed we should add this, the `duckdb_string` that is in there is legacy used for the materialized format.

**Comment by Tishj** [comment]
> Agreed we should add this, the `duckdb_string` that is in there is legacy used for the materialized format.

Not really sure what it should be called then, as `duckdb_string_t` is a little too close 😅

**Comment by Mytherin** [comment]
I think `duckdb_string_t` is better to keep the consistency with the internal code-base.
