### ISSUE TITLE
Internal error on read_json_auto if file is large with no newlines

### ISSUE THREAD

**Issue by marhar** [duckdb/duckdb#7155]
### What happens?

A large json no-newline file causes:

```
D create table t2 as select * from read_json_auto('error1.json',maximum_object_size=999999999);
Error: INTERNAL Error: Unexpected yyjson tag in ValTypeToString
```

Reformatting the file with jq fixes the problem.
```
D create table t as select * from read_json_auto('error2.json',maximum_object_size=999999999);
D .tables
t
```

verified same problem in development version.

### To Reproduce

Two json files, contents are logically identical, but first file has no newlines.

```
% jq <error1.json >error2.json

% diff <(jq --sort-keys . error1.json) <(jq --sort-keys . error2.json)
%

% wc error*.json
       1       1 36811899 error1.json
  323546  609026 38638972 error2.json
  323547  609027 75450871 total
```

The jq-formatted files reads correctly, the non-formatted file receives internal error.

```
% duckdb
v0.7.1 b00b93f0b1
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D create table t as select * from read_json_auto('error2.json',maximum_object_size=999999999);
D .tables
t

D create table t2 as select * from read_json_auto('error1.json',maximum_object_size=999999999);
Error: INTERNAL Error: Unexpected yyjson tag in ValTypeToString
```

### OS:

MacOS

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Mark Harrison

### Affiliation:

TigerEye

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Closed via #7478
