### ISSUE TITLE
AttributeError: module 'duckdb' has no attribute 'sql'

### ISSUE THREAD

**Issue by avnav88** [duckdb/duckdb#7157]
### What happens?

trying to follow https://duckdb.org/docs/guides/python/polars.html

i get an attribute error, saying it's not possible to load the polars df because there is no attribute `sql`.

### To Reproduce

```
import duckdb
import polars as pl

df = pl.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "fruits": ["banana", "banana", "apple", "apple", "banana"],
        "B": [5, 4, 3, 2, 1],
        "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
    }
)
duckdb.sql('SELECT * FROM df').show()
```

i get:

```

PyDev console: starting.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
runfile('L:\\wk\\DE\\_ETL_JOBS\\E2E\\test\\job_code\\testathena.py', wdir='L:\\wk\\DE\\_ETL_JOBS\\E2E\\test\\job_code')
Traceback (most recent call last):
  File "C:\Data\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Data\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Data\JetBrains\PyCharm 2022.2.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "L:\wk\DE\_ETL_JOBS\E2E\test\job_code\testathena.py", line 26, in <module>
    duckdb.sql('SELECT * FROM df').show()
AttributeError: module 'duckdb' has no attribute 'sql'
```

### OS:

x86

### DuckDB Version:

duckdb==0.6.1

### DuckDB Client:

python

### Full Name:

avnav

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello! Would you mind trying on a later version of DuckDB? `.sql` is relatively new.

You can use this instead on your version:
```python
conn = duckdb.connect()
conn.execute("select * from df").pl()
```

**Comment by Mause** [comment]
`pl` was only added at the same time as `.sql(...)`, but the `.sql(...)` method should be equivalent to the `.query(...)` method

**Comment by Mytherin** [comment]
As mentioned, either upgrade to the latest version or use the docs for the version you are currently using
