### ISSUE TITLE
python client append, insert_into, and INSERT INTO ... FROM dataframe commands don't respect column order and don't fill NULLs for missing columns

### ISSUE THREAD

**Issue by NSchrading** [duckdb/duckdb#7176]
### What happens?

The python client functions `append` and `insert_into`, and the SQL `INSERT INTO ... FROM <dataframe>`  command will naively insert data from the dataframe not accounting for the order of the columns.

To get around this, I must use the SQL `INSERT INTO <columns> VALUES (?, ...), <values list>` row-by-row. As long as the column string aligns with the values list, the values are placed into the correct column in the table, regardless of the order in which the columns are specified.

### To Reproduce

```python
import duckdb
from pandas import DataFrame

connection = duckdb.connect()
connection.execute("CREATE TABLE data(a INTEGER, b INTEGER, c INTEGER)")

df = DataFrame.from_records({'a': [1], 'b': [2], 'c': [3]})

# nominal insert, everything is as expected
connection.append('data', df)
connection.sql("SELECT * FROM data")
┌───────┬───────┬───────┐
│   a   │   b   │   c   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     2 │     3 │
└───────┴───────┴───────┘

# make some data that just has columns out of the expected order
df_out_of_order = df[['b', 'c', 'a']]
df_out_of_order
   b  c  a
0  2  3  1

# append, expect that we'll get the value 1 for 'a', 2 for 'b' and 3 for 'c'
connection.append('data', df_out_of_order)
connection.sql("SELECT * FROM data")

# oh no! It naively just placed the data in the order left to right, not respecting the column names
┌───────┬───────┬───────┐
│   a   │   b   │   c   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     2 │     3 │
│     2 │     3 │     1 │
└───────┴───────┴───────┘

# the same behavior is seen in `insert_into`
connection.sql("SELECT * FROM df_out_of_order").insert_into("data")
connection.sql("SELECT * FROM data")
┌───────┬───────┬───────┐
│   a   │   b   │   c   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     2 │     3 │
│     2 │     3 │     1 │
│     2 │     3 │     1 │
└───────┴───────┴───────┘

# the same behavior is seen in INSERT FROM <dataframe>
connection.sql("INSERT INTO data SELECT * FROM df_out_of_order")
connection.sql("SELECT * FROM data")
┌───────┬───────┬───────┐
│   a   │   b   │   c   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     2 │     3 │
│     2 │     3 │     1 │
│     2 │     3 │     1 │
│     2 │     3 │     1 │
└───────┴───────┴───────┘

# Ideally, these functions would insert NULLs for unspecified columns, but instead we get an error.
df = DataFrame.from_records({'a': [1], 'b': [2]})
connection.append('data', df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.BinderException: Binder Error: table data has 3 columns but 2 values were supplied
```

### OS:

Windows

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

J Nicolas Schrading

### Affiliation:

personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
If you don't explicitly provide columns for the insert, the columns are assumed to be the creation order of the columns.
To specify column order, here is an example:
```sql
D create table tbl (a integer, b varchar, c boolean);
D insert into tbl(c, b, a) select NULL, 'c', 3;
D select * from tbl;
┌───────┬─────────┬─────────┐
│   a   │    b    │    c    │
│ int32 │ varchar │ boolean │
├───────┼─────────┼─────────┤
│     3 │ c       │         │
└───────┴─────────┴─────────┘
```

**Comment by Tishj** [comment]
I do agree that when the columns are specified explicitly, it might be better to insert NULLs in the trailing columns that don't have a matching expression, instead of the current behavior:
```sql
D insert into tbl(c, b, a) select False, 'd';
Error: Binder Error: Column name/value mismatch for insert on tbl: expected 3 columns but 2 values were supplied
```

**Comment by NSchrading** [comment]
Thanks for the additional info. I agree with the above, but at least you can do this and it will both insert all rows in the correct order and add NULLs for the missing columns

```python
connection.sql("INSERT INTO data(a, b) SELECT a,b FROM df_out_of_order")

┌───────┬───────┬───────┐
│   a   │   b   │   c   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     3 │  NULL │
│     2 │     4 │  NULL │
└───────┴───────┴───────┘
```

I think at least for the `append` function, it would be a great usability improvement to operate in the way I'd expect, where column names are respected even if the columns are out of order in the dataframe / table, and by default add NULLs for missing columns. Perhaps an optional could be added to raise an error on missing columns.

**Comment by Tishj** [comment]
We could maybe extend the `append` function to take a `by_name` boolean, when set to true it inserts using the names

**Comment by NSchrading** [comment]
Yes, that would work perfectly as long as it also had the behavior, either via kwarg option or by default that it fills in NULLs for missing columns too.
