### ISSUE TITLE
JDBC driver doesn't correctly implement the Statement.execute() / Statement.getUpdateCount() protocol

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7188]
### What happens?

When using the generic `Statement::execute` API (which is used when the SQL query type is unknown), then there's a complicated protocol to be followed as specified by the JDBC API in order to determine the order of results / update counts / exceptions.

This is currently not implemented correctly by the DuckDB JDBC driver

### To Reproduce

```java
try (Statement s = connection.createStatement()) {
    try {
        s.executeUpdate("create table t (i int)");
        println(s.executeUpdate("insert into t values (1)"));
        println(s.execute("insert into t values (1)"));
        println(s.getUpdateCount());
    }
    finally {
        s.executeUpdate("drop table t");
    }
}
```

This prints:

```
1
false
-1
```

But that's incorrect. After printing `false`, the program should print `1` to produce the update countA subsequent call to `getMoreResults()` should produce `false` again, and only then would the `getUpdateCount()` call produce `-1`

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.1

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lukaseder** [comment]
You can see that this produces misleading results also in third party tools, like Dbeaver:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/734593/233697074-c8fc90d1-e3a5-4816-97d9-7f0a77b28a98.png">

**Comment by hannes** [comment]
@Mause can you have a look please?
