### ISSUE TITLE
No enum constant org.duckdb.DuckDBColumnType.TIME WITH TIME ZONE when querying DatabaseMetaData::getColumns

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7189]
### What happens?

The `TIME WITH TIME ZONE` data type isn't supported by the JDBC driver's `DatabaseMetaData` implementation.

### To Reproduce

```java
try (Statement s = connection.createStatement()) {
    try {
        s.executeUpdate("create table t (i time with time zone)");
        connection.getMetaData().getColumns(null, "%", "t", "i");
    }
    finally {
        s.executeUpdate("drop table t");
    }
}
```

This produces:

```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.TIME WITH TIME ZONE
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:58)
	at org.duckdb.DuckDBDatabaseMetaData.getColumns(DuckDBDatabaseMetaData.java:827)
	at org.jooq.testscripts.JDBC.main(JDBC.java:46)
```

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.1

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
I would guess this is probably due to the underscores instead of spaces in the enum lookup?

**Comment by lukaseder** [comment]
There's no enum value for the type:
https://github.com/duckdb/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBColumnType.java

And `DuckDBResultSetMetaData::TypeNameToType` doesn't map it either:
https://github.com/duckdb/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBResultSetMetaData.java#L46

It does correctly handle `TIMESTAMP WITH TIME ZONE`

I just realised that

1. The version on `master` will intercept the exception and return `UNKNOWN`
2. The type isn't documented: https://duckdb.org/docs/sql/data_types/timestamp, yet it's not being rejected by the `CREATE TABLE` statement either.

This shows that it seems to be accepted by the database:

```sql
create table t (i time with time zone);

select *
from duckdb_columns()
where table_name = 't';
```

Possibly some lacking documentation?

**Comment by Mause** [comment]
Yeah I just noticed that as well, I guess it isn't commonly used, so this hasn't come up before
