### ISSUE TITLE
Can't refer to alias in function chaining syntax

### ISSUE THREAD

**Issue by Alex-Monahan-Intel** [duckdb/duckdb#7190]
### What happens?

When using an alias of a calculated column defined previously in the same select statement, I am unable to use the new function chaining / dot syntax.

### To Reproduce

```python
import duckdb
import pandas as pd

duckdb.sql("""
    select
        'test' || ' more testing' as added,
        added.substr(5) as my_substr
""").df()

---------------------------------------------------------------------------
CatalogException                          Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_67352/3026736190.py in <module>
----> 1 duckdb.sql("""
      2     select
      3         'test' || ' more testing' as added,
      4         added.substr(5) as my_substr
      5 """).df()

CatalogException: Catalog Error: Scalar Function with name substr does not exist!
Did you mean "main.substr"?

```

### OS:

Windows

### DuckDB Version:

0.7.2-dev2366

### DuckDB Client:

Python

### Full Name:

Alex Monahan

### Affiliation:

Intel and DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by douenergy** [comment]
I have a fix for this
