### ISSUE TITLE
CSV header is ignored when there is a trainling comma

### ISSUE THREAD

**Issue by ml31415** [duckdb/duckdb#7196]
### What happens?

I got external CSV files to parse, that unfortunately feature a trailing comma on the header, like that:
```
a,b,c,
1,2,3
```
```
>>> duckdb.from_csv_auto("test.csv").show()
┌─────────┬─────────┬─────────┐
│ column0 │ column1 │ column2 │
│  int64  │  int64  │  int64  │
├─────────┼─────────┼─────────┤
│       1 │       2 │       3 │
└─────────┴─────────┴─────────┘
```
For 0.7.1, it looks like the header is completely ignored when parsing, likely [treated as a comment](https://github.com/duckdb/duckdb/issues/5663). Now of course the trailing comma is unfortunate, but imho it's clear enough, so that either there should be just an empty column in the end, or the comma be silently ignored in auto mode. Forcing `headers=True` makes this even worse and treats the first numeric data row as header. Probably, the heuristic that picks comments should ignore the first line completely?
```
>>> duckdb.from_csv_auto("test.csv", header=True).show()
┌───────┬───────┬───────┐
│   1   │   2   │   3   │
│ int64 │ int64 │ int64 │
├───────────────────────┤
│        0 rows         │
└───────────────────────┘
```

The behaviour seems to have changed in master. Unfortunately, it's not much better, it all get's treated as a single column now, and if it's only integers as above, tries to treat them as a date:

```
>>> duckdb.from_csv_auto("test.csv").show()
┌────────────┐
│   a,b,c,   │
│    date    │
├────────────┤
│ 2001-02-03 │
└────────────┘

>>> Path("test.csv").write_text("a,b,c,\n1.3,233,3\n")
>>> duckdb.from_csv_auto("test.csv").show()
┌───────────┐
│  column0  │
│  varchar  │
├───────────┤
│ a,b,c,    │
│ 1.3,233,3 │
└───────────┘
```
Expected behaviour should imho be this:
```
┌───────┬───────┬───────┬─────────┐
│   a   │   b   │   c   │ column3 │
│ int64 │ int64 │ int64 │ varchar │
├───────┼───────┼───────┼─────────┤
│     1 │     2 │     3 │ NULL    │
└───────┴───────┴───────┴─────────┘
```
This is also in line with what pandas does:
```
>>> import pandas as pd
>>> pd.read_csv("test.csv")
   a  b  c  Unnamed: 3
0  1  2  3         NaN
```

### To Reproduce

```python
from pathlib import Path
import duckdb
Path("test.csv").write_text("a,b,c,\n1,2,3\n")
duckdb.from_csv_auto("test.csv").show()
```

### OS:

ubuntu x86

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Michael Löffler

### Affiliation:

OCCAM

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ml31415** [comment]
Hi @pdet Thanks for having a look into this! Yes, that works for me the same way. Looks like I overlooked that option and that's actually good enough as a quick fix. Shouldn't this be the default then?

**Comment by pdet** [comment]
Excellent, I'll close this issue then :-).

The reason is not a default. It's because it is not supported in the Parallel CSV Reader, then the Parallel CSV Reader wouldn't be the default option.

**Comment by ml31415** [comment]
@pdet last remark. Shouldn't `duckdb.from_csv_auto` also have `null_padding` as a keyword argument then? So far at least this fails.

**Comment by pdet** [comment]
Yes, 100%
