### ISSUE TITLE
Node.js crashes on zero-row Arrow results

### ISSUE THREAD

**Issue by jheer** [duckdb/duckdb#7200]
### What happens?

When calling `arrowIPCAll` on the DuckDB node.js client, zero-row results cause a crash. I've seen this behavior in both the 0.6.1 and 0.7.1 releases.

The crash arises due to a failed assertion:
`> Assertion failed: (out_idx == materialized_result->RowCount() + 1), function Callback, file statement.cpp, line 397.`

In the current repository the assertion appears to be on this line:
https://github.com/duckdb/duckdb/blob/master/tools/nodejs/src/statement.cpp#L401

I haven't tested more carefully, but it looks like the error may be due to the `out_idx` variable being initialized to 1 and then erroneously incremented beyond the assertion target value here:
https://github.com/duckdb/duckdb/blob/master/tools/nodejs/src/statement.cpp#L398

### To Reproduce

Install the node.js client, install and load arrow extension, then query for an empty (zero row) table result.

```js
const duckdb = require('duckdb');
const db = new duckdb.Database(':memory:');
const con = db.connect();
con.exec('INSTALL arrow; LOAD arrow;', (err) => {
  if (err) { console.log(err); return; }
  con.arrowIPCAll('SELECT 1 AS v WHERE v > 1', () => {});
});
```

### OS:

MacOS

### DuckDB Version:

0.7.1

### DuckDB Client:

nodejs

### Full Name:

Jeffrey Heer

### Affiliation:

University of Washington

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! Maybe @samansmink can have a look?

**Comment by jheer** [comment]
Thanks @Mytherin and @samansmink. I can confirm that empty tables lead to a `materialized_result` with zero rows, thus causing `out_idx` to be incremented too high and violate that assertion. In case it helps I was able to get a local version working by rewriting the `ARROW_ALL` case within `RunPreparedTask` in `statement.cpp` (code included below).

Meanwhile (though much less pressing for me), there are other aspects that might be worth revising. Including `D_ASSERT` statements that cause a complete crash of node seems less than ideal. If these assertion violation errors might arise in production, I figure the code should instead report errors to JavaScript via the callback. (And note there are assertions in the `arrowIPCStream` handler, too.)

With my edits below, empty tables result in Arrow buffers consisting of 4 zero bytes only. Arrow libraries parse this as an empty table with no schema. This works great for our use cases, but some clients might expect to get the schema of the empty table as part of the response.

This bug is a significant blocker for us, so if possible it would be great to know in what time frame we might be able to expect a fix. I only ask because if it's a long time we can publish our own fork in the interim. No pressure, though, I know first hand how taxing open source development can be! DuckDB is awesome and I really appreciate the work the team has done.

```c++
case RunType::ARROW_ALL: {
	auto materialized_result = (duckdb::MaterializedQueryResult *)result.get();
	// +1 is for null bytes at end of stream
	Napi::Array result_arr(Napi::Array::New(env, materialized_result->RowCount() + 1));

	auto deleter = [](Napi::Env, void *finalizeData, void *hint) {
		delete static_cast<std::shared_ptr<duckdb::QueryResult> *>(hint);
	};

	std::shared_ptr<duckdb::QueryResult> result_ptr = std::move(result);

	duckdb::idx_t out_idx = 1;
	duckdb::idx_t num_chunks = 0;
	while (true) {
		auto chunk = result_ptr->Fetch();

		if (!chunk || chunk->size() == 0) {
			break;
		}

		num_chunks++;
		// D_ASSERT(chunk->ColumnCount() == 2);
		// D_ASSERT(chunk->data[0].GetType() == duckdb::LogicalType::BLOB);
		// D_ASSERT(chunk->data[1].GetType() == duckdb::LogicalType::BOOLEAN);

		for (duckdb::idx_t row_idx = 0; row_idx < chunk->size(); row_idx++) {
			duckdb::string_t blob = ((duckdb::string_t *)(chunk->data[0].GetData()))[row_idx];
			bool is_header = chunk->data[1].GetData()[row_idx];

			// Create shared pointer to give (shared) ownership to ArrayBuffer, not that for these materialized
			// query results, the string data is owned by the QueryResult
			auto result_ref_ptr = new std::shared_ptr<duckdb::QueryResult>(result_ptr);

			auto array_buffer = Napi::ArrayBuffer::New(env, (void *)blob.GetDataUnsafe(), blob.GetSize(),
																									deleter, result_ref_ptr);

			auto typed_array = Napi::Uint8Array::New(env, blob.GetSize(), array_buffer, 0);

			// TODO we should handle this in duckdb probably
			if (is_header) {
				result_arr.Set((uint32_t)0, typed_array);
			} else {
				// D_ASSERT(out_idx < materialized_result->RowCount());
				result_arr.Set(out_idx++, typed_array);
			}
		}
	}

	if (num_chunks == 0) {
		out_idx = 0;
	}

	// TODO we should handle this in duckdb probably
	auto null_arr = Napi::Uint8Array::New(env, 4);
	memset(null_arr.Data(), '\0', 4);
	result_arr.Set(out_idx++, null_arr);

	// Confirm all rows are set
	// D_ASSERT(out_idx == materialized_result->RowCount() + 1);

	cb.MakeCallback(statement.Value(), {env.Null(), result_arr});
} break;
```

Final note: with the patch above I could only get a working version when modifying code from the 0.7.1 tag. Separate from this issue, the most recent code in GitHub resulted in seemingly corrupted output that Arrow libraries fail to parse. I did not investigate more deeply.

**Comment by carlopi** [comment]
@jheer: I gave this a try with nightly build, works as intended after @samansmink work!

One minor thing is that the result of the call to arrowIPCAll for above queries is:
```
[ <1 empty item>, Uint8Array(4) [ 0, 0, 0, 0 ] ]
┌─────────┐
│ (index) │
├─────────┤
└─────────┘
```
unsure if it should have been: 
```
[ Uint8Array(4) [ 0, 0, 0, 0 ] ]
┌─────────┐
│ (index) │
├─────────┤
└─────────┘
```
(both rendered in the same way after being read by arrow-apache JS library like)
```js
const table = arrow.tableFromIPC(b);
console.table(table.toArray());
```
