### ISSUE TITLE
Temporary AWS credentials broken

### ISSUE THREAD

**Issue by samansmink** [duckdb/duckdb#7211]
### What happens?

When using [temporary aws credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html), the requests fail with a 400 error.  Also, the [duckdb docs](https://duckdb.org/docs/guides/import/s3_import.html) incorrectly state that you should provide either a session token or credentials: it should be both.

We need to figure out why our requests seem malformed. While we're at it, we should probably also switch to https://github.com/aws-samples/sigv4a-signing-examples as this seems to remove the need to set the region for signing

### To Reproduce

```
require httpfs
require parquet

statement ok
set s3_access_key_id="<nope>";

statement ok
set s3_secret_access_key="<very_nope>";

statement ok
set s3_session_token="<also_nope>";

statement ok
set s3_region="eu-west-1";

statement ok
select count(*) from 's3://test-bucket/tpch/lineitem_sf1.parquet';
```

### OS:

MacOS

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Sam Ansmink

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by BigRedAye** [comment]
Not sure if this is helpful, but I get the credentials from an EC2 instance with an IAM Role enabling it to generate its own temp credentials and don't see any issues with 7.1. 

`TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/Name-Of-The-IAM-Role`

Or in python using boto3
`
import botocore.credentials
import duckdb
​
fetcher = botocore.credentials.InstanceMetadataFetcher()
provider = botocore.credentials.InstanceMetadataProvider(iam_role_fetcher=fetcher)
credentials = provider.load()
 
access_key = credentials.access_key
secret_key = credentials.secret_key
session_token = credentials.token
expiration = credentials._expiry_time
​
print("Access Key:", access_key)
print("Secret Key:", secret_key)
print("Session Token:", session_token)
print("Expiration:", expiration)
​
with duckdb.connect(database=':memory:', read_only=False) as con:
​
    # Setup the plug-in for httpfs and the credentials
    con.execute(f"""
    INSTALL httpfs;
    LOAD httpfs;
​
    SET s3_region='us-east-1';
    SET s3_access_key_id='{access_key}';
    SET s3_secret_access_key='{secret_key}';
    SET s3_session_token='{session_token}';
    """)
    ...
`

**Comment by dude0001** [comment]
I do not think temporary AWS credentials are broken. At least in the latest release. I can affirm using DuckDB-WASM v1.25.0 works using access key, secret access key and session token. As stated in the original issue description and by @BigRedAye 's code example above.

The [docs](https://duckdb.org/docs/guides/import/s3_import) are a little misleading to lead the reader wanting to use temporary credentials that you can use only a session token or maybe access key and session token without the secret access key. All 3 are needed when using temporary credentials.

This is general knowledge [documented](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) by AWS. The way the documentation is written I can see how it would trip up someone that is novice to using temporary credentials.

I can give a swing at updating the docs if this seems like the appropriate resolution for this issue. Using AWS signature 4 signing as mentioned in the issue description seems like a separate code change.
