### ISSUE TITLE
Wrong result set produced by JDBC driver when passing LIMIT and OFFSET as Long bind values

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7212]
### What happens?

When passing both `LIMIT` and `OFFSET` as `Long` bind values, it seems the values are ignored

### To Reproduce

```java
try (Statement s = connection.createStatement()) {
    try {
        s.executeUpdate("create table t (i int not null)");
        s.executeUpdate("insert into t values (1), (1), (2), (3), (3), (3)");

        try (PreparedStatement ps = connection.prepareStatement("select t.i from t order by t.i limit ? offset ?")) {
            ps.setLong(1, 2);
            ps.setLong(2, 1);

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    System.out.println(rs.getInt(1));
                }
            }
        }
    }
    finally {
        s.executeUpdate("drop table t");
    }
}
```

This produces:

```
1
1
2
3
3
3
```

When it should produce

```
1
2
```

The workaround is to pass the `OFFSET` value  as `int`:

```java
ps.setInt(2, 1);
```

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.2-dev2430

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Looks like this might be an issue with the `TopN` optimizer and `LogicalTypeId::BIGINT` (which is what long is translated to in the JDBC bindings). If you disable that optimizer is seems to work fine, or if you use `setInteger` instead
