### ISSUE TITLE
UPDATE .. RETURNING doesn't work if there's a PRIMARY KEY or UNIQUE constraint on the table

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7215]
### What happens?

I can't use `UPDATE .. RETURNING` on a table with `PRIMARY KEY`

### To Reproduce

```sql
create table t (i int primary key, j int);
insert into t values (1, 1);
update t set j = 2 where i = 1 returning *;
```

This produces:

> Constraint Error: Duplicate key "i: 1" violates primary key constraint

This works, as a workaround:

```sql
create table t (i int primary key, j int);
insert into t values (1, 1);
update t set j = 2 where i = 1;
select * from t where i = 1;
``` 

Removing the `PRIMARY KEY` also solves the problem

```sql
create table t (i int, j int);
insert into t values (1, 1);
update t set j = 2 where i = 1 returning *;
```

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.2-dev2430

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taniabogatsch** [comment]
This should be resolved by this PR: https://github.com/duckdb/duckdb/pull/15092.

```sql
(venv) tania@motorbook duckdb % build/release/duckdb
v1.1.4-dev3731 f9c7a7c266
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table t (i int primary key, j int);
D insert into t values (1, 1);
D update t set j = 2 where i = 1 returning *;
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│   1   │   2   │
└───────┴───────┘
```
