### ISSUE TITLE
Can't use PreparedStatement::executeUpdate on an INSERT .. SELECT query

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7216]
### What happens?

When running an `INSERT .. SELECT` query, it seems that DuckDB thinks the query will return a `ResultSet`, when it really won't.

### To Reproduce

```java
try (Statement s = connection.createStatement()) {
    s.executeUpdate("drop table if exists t");
    s.executeUpdate("create table t (i int)");

    try (PreparedStatement p = connection.prepareStatement("insert into t (i) select ?")) {
        p.setInt(1, 1);
        p.executeUpdate();
    }
}
```

This produces:

```
Exception in thread "main" java.sql.SQLException: executeUpdate() can only be used with queries that return nothing (eg, a DDL statement), or update rows
	at org.duckdb.DuckDBPreparedStatement.executeUpdate(DuckDBPreparedStatement.java:169)
	at org.jooq.testscripts.JDBC.main(JDBC.java:51)
```

One workaround would be to call `p.execute()`, but I have to avoid that because of another bug: https://github.com/duckdb/duckdb/issues/7188

The problem appears only with prepared statements, not with static statements.

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.2-dev2430

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Looks like this one isn't actually a JDBC issue - when we go to bind the select node in the query, we throw a Parameter Not Resolved Error, and by doing so skip setting the return_type field to CHANGED_ROWS, so it's left as the QUERY_RESULT default.

CC @Mytherin

**Comment by Mytherin** [comment]
> Looks like this one isn't actually a JDBC issue - when we go to bind the select node in the query, we throw a Parameter Not Resolved Error, and by doing so skip setting the return_type field to CHANGED_ROWS, so it's left as the QUERY_RESULT default.
> 
> CC @Mytherin

When the `ParameterNotResolved` exception is thrown that means binding could not be performed without knowing the values of the parameters. As such, no properties of the prepared statement can (or should) be read until the values of the parameters are supplied. That includes the `names`, `types` and statement properties of the statement. As such, the `StatementReturnType` should be considered uninitialized in this case.

Perhaps we should initialize it to `StatementReturnType::INVALID` instead to make this more clear.
