### ISSUE TITLE
NullPointerException when reading ResultSet.getInt() from GENERATE_SERIES query

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7218]
### What happens?

A query that reads `ResultSet.getInt()` from `GENERATE_SERIES()` with bind variable arguments fails with a `NullPointerException`

### To Reproduce

```java
try (Statement s = connection.createStatement()) {
    s.executeUpdate("drop table if exists t");
    s.executeUpdate("create table t (i int)");

    try (PreparedStatement p = connection.prepareStatement("select generate_series.generate_series from generate_series(?, ?) order by 1")) {
        p.setInt(1, 0);
        p.setInt(2, 1);

        try (ResultSet rs = p.executeQuery()) {
            while (rs.next())
                println(rs.getInt(1));
        }
    }
}
```

This produces:

```
Exception in thread "main" java.lang.NullPointerException: Cannot load from object array because "this.current_chunk[...].varlen_data" is null
	at org.duckdb.DuckDBResultSet.getLazyString(DuckDBResultSet.java:248)
	at org.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:213)
	at org.duckdb.DuckDBResultSet.getInt(DuckDBResultSet.java:325)
	at org.jooq.testscripts.JDBC.main(JDBC.java:55)
```

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.2-dev2430

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
I've (hopefully) fixed this by returning using the type of the column in the result vector, rather than the calculated type in the prepared statement 🤞
