### ISSUE TITLE
PRAGMA synchronous_commit=off

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#722]
This is an option from Postgres that essentially disables calling fsync on the WAL ([here](https://www.postgresql.org/docs/current/wal-async-commit.html)). The result is that in case of a crash recent changes made to the database can be lost, but the database will never be in an inconsistent state (as the WAL will simply only be replayed until the last full commit that was written in there). 

This option is easy to implement and speeds up some workflows with many small transactions, and is a pretty sane option for many people ("I don't care if I lose the latest commits - just don't corrupt my database").

**Comment by hannesmuehleisen** [comment]
"NoSQL feature" :)

**Comment by Mytherin** [comment]
I said "don't corrupt my database", not "randomly corrupt my database" ;)
