### ISSUE TITLE
Parser Error: DEFAULT VALUES clause is not supported

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7220]
### What happens?

The documentation states that `DEFAULT VALUES` is supported, but this isn't true:
https://duckdb.org/docs/sql/statements/insert

<img width="562" alt="image" src="https://user-images.githubusercontent.com/734593/234080883-6637d6fc-a66e-4c22-8bb3-8c218c7a346e.png">

### To Reproduce

```sql
create table x (i int default 1)
insert into x default values;
```

This results in:

> Parser Error: DEFAULT VALUES clause is not supported!

The workaround is

```sql
insert into x values (default);
```

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.2-dev2430

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Implemented by #7240
