### ISSUE TITLE
TPC-DS extension writes GMT Offset values incorrectly.

### ISSUE THREAD

**Issue by DanCory** [duckdb/duckdb#7222]
### What happens?

The GMT offset columns contain values like "-0.05" instead of "-5".

It appears that append_decimal in append_info-c.cpp does not handle scale correctly.

### To Reproduce

1. Start CLI with TPC-DS extension installed.
2. .open sf1
3. CALL dsdgen(sf=1);
4. select ca_gmt_offset from customer_address group by 1;
5. This query should return the values -5, -6, -7, -8, -9, -10
6. select s_gmt_offset from store group by 1;
7. This query should return the value -5

### OS:

Windows amd64

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Dan Cory

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Might be related (or similar) to https://github.com/duckdb/duckdb/pull/7099 ?

**Comment by Mytherin** [comment]
Thanks for the reports! I have pushed a fix for all the issues in #7247
