### ISSUE TITLE
`Binder Error: Circular reference to CTE` for recursive definition

### ISSUE THREAD

**Issue by amirsh** [duckdb/duckdb#7227]
### What happens?

While trying to encode the MST prim's algorithm, I've faced with the following error:

```
Binder Error: Circular reference to CTE "tree_edge", use WITH RECURSIVE to use recursive CTEs
```

The weird thing is that the definition is already recursive.

### To Reproduce

Note that this is a simplified query just to demonstrate the issue.

```sql
CREATE TABLE "edge"("x" INTEGER, "y" INTEGER, "w" DOUBLE, PRIMARY KEY("x", "y"));

WITH RECURSIVE tree_edge(t, x, y) AS (
	SELECT t+1, x, y FROM min_edge
UNION ALL
	SELECT tree_edge.t + 1, x, y 
	FROM tree_edge
	WHERE tree_edge.t < 10
), min_edge(t, x, y) AS (
	SELECT tn1.t, edge.x, edge.y
	FROM tree_node tn1, edge
	WHERE tn1.s = edge.x
), tree_node(t, s) AS (
	SELECT 0, edge.x FROM edge
UNION ALL
	SELECT te.t, te.x FROM tree_edge te
	WHERE te.t > 0
)
SELECT * FROM tree_edge;
```

Just to make everything simpler, here's a simpler query:

```sql
CREATE table t("id" INTEGER);
WITH RECURSIVE
x (id) AS (SELECT y.id+1 FROM y UNION ALL SELECT x.id+1 FROM x WHERE x.id < 5),
y (id) AS (SELECT z.id FROM z, t WHERE z.id = t.id AND z.id < 5),
z (id) AS (SELECT 0 UNION ALL SELECT x.id FROM x WHERE x.id < 5)
SELECT * FROM x;
```
### OS:

macos x86_64

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Amir Shaikhha

### Affiliation:

The University of Edinburgh

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
(just speaking as another end user)

I think the recursive warning here is not the first query by itself, but from its reference to the later defined min_edge which in turn, relies on the earlier tree_edge.

You can verify this is the case by changing the first reference to min_edge...  although this isn't logically correct for an MST. 
```
WITH RECURSIVE tree_edge(t, x, y) AS (
	**SELECT w+1, x, y FROM edge**
UNION ALL
	SELECT tree_edge.t + 1, x,
...
```

**Comment by amirsh** [comment]
The relation that handles the base case is `tree_node`.

**Comment by kryonix** [comment]
Hi @amirsh, your query uses mutual recursion of multiple CTEs. That is not supported by any DMBS (as far as I am aware) except MariaDB (please correct me if I'm wrong!).

After discussing this issue a bit over on Discord, I've implemented two versions of Prim's algorithm using a recursive CTE, but no mutual recursion:

```
CREATE or REPLACE TABLE edge("x" INTEGER, "y" INTEGER, edge_id int, "w" DOUBLE, PRIMARY KEY("x", "y"));
insert into edge (values
-- standard example from https://algorithms.discrete.ma.tum.de/graph-algorithms/mst-prim/index_en.html
(2,4,0,33),
(3,5,1,2),
(5,3,1,2),

(3,4,2,20),
(4,5,3,1),
(2,3,4,20),
(1,4,5,10),
(1,3,6,50),
(0,2,7,20),
(0,1,9,10)
);

-- Typical variant with v being an array to check already seen nodes/edges.
WITH RECURSIVE prim(x, y, v) AS
(
  (SELECT x, y, [x, y]
  FROM   edge
  ORDER BY w
  LIMIT    1)
    UNION ALL
  (SELECT x, y, v || [p.x, p.y]
   FROM (SELECT e.x, e.y, e.w, p.v
         FROM   prim AS p, edge AS e
         WHERE (p.x = e.x OR p.y = e.y OR p.x = e.y OR p.y = e.x)
           AND (   NOT ARRAY_CONTAINS(v, e.x)
                OR NOT ARRAY_CONTAINS(v, e.y))) AS p
   ORDER BY w
   LIMIT 1)
)
SELECT * FROM prim;
```

---

```
-- Variant that emulates non-semi-naive variant of WITH RECURSIVE.
WITH RECURSIVE prim(x, y, wt) AS
(
  (SELECT x, y, true
  FROM   edge
  ORDER BY w
  LIMIT    1)
    UNION ALL
  (WITH
    wt1(x, y, wt) AS (
      (SELECT x, y, true
       FROM (SELECT e.x, e.y, e.w
             FROM   prim AS p, edge AS e
             WHERE (p.x = e.x OR p.y = e.y OR p.x = e.y OR p.y = e.x)           -- make sure one part of the edge is part of the MST
               AND (   e.x NOT IN (SELECT x FROM prim UNION SELECT y FROM prim) -- make sure one part of the edge is NOT part of the MST
                    OR e.y NOT IN (SELECT x FROM prim UNION SELECT y FROM prim))) AS p
       ORDER BY w -- add exactly one edge to the MST, use the one with lowest weight
       LIMIT 1)

        UNION ALL

      -- Re-inject all rows previously seen to emulate non-semi-naive evaluation
      -- Set wt-flag to false, however. We need this to have a termination check
      SELECT x, y, false
      FROM   prim
    )
    -- This part implements the termination of this query.
    -- We have to use UNION ALL semantics, which would result in an endless loop.
    -- This query checks if any row is new, aka, if any row has the wt flag set.
    -- Otherwise, no row passes the filter. Thus the working table is empty, and
    -- iteration stops.
    SELECT * FROM wt1
    WHERE (SELECT bool_or(wt) FROM wt1)
  )
)
SELECT * FROM prim WHERE wt;
```

Hope that helps.

**Comment by amirsh** [comment]
Hi @kryonix 
Many thanks for your response, I really appreciate it.
First, I found that DuckDB had the support for mutual recursion, to some degree. An example supported is as follows:
```sql
CREATE table t("id" INTEGER);
INSERT INTO t
  ( id )
VALUES
  ( 0 ), ( 1 ), ( 2 ), ( 3 );
WITH RECURSIVE
x (id) AS (SELECT 0 UNION ALL SELECT x.id+1 FROM x,y WHERE x.id=y.id AND x.id < 5),
y (id) AS (SELECT z.id FROM z, t WHERE z.id = t.id AND z.id < 5),
z (id) AS (SELECT x.id FROM x, t WHERE x.id = t.id AND x.id < 5)
SELECT * FROM x;
```

Second, your second variant gave me an error on DuckDB 0.7.1:
`Not implemented Error: UNIONS are not supported in recursive CTEs yet`

Which version of DuckDB did you test it on?

**Comment by paultiq** [comment]
FWIW, I do think it's the circular base case in the first query:

This modification to your latest query fails with the same problem as the first query. The only change is the `select 1,1,1 from y`.

```
WITH RECURSIVE
x (id) AS (SELECT 1,1,1 from y, 'base' UNION ALL SELECT x.id+1, y.src FROM x,y WHERE x.id=y.id AND x.id < 5),
y (id, src) AS (SELECT z.id, z.src FROM z, t WHERE z.id = t.id AND z.id < 5),
z (id, src) AS (select 0, 'zfake' union all SELECT x.id, concat(x.id, 'z') FROM x, t WHERE x.id = t.id AND x.id < 5)
SELECT * FROM x;
```

Looking at the AST's... your unmodified version was rewritten to have a single recursive query:
![new_query](https://user-images.githubusercontent.com/104510378/234632029-c3d33ba7-ad21-46a3-8cb9-e08de3b06e4f.svg)


But, with the modification, you end up with multiple recursives:
![modified_to_fail](https://user-images.githubusercontent.com/104510378/234632000-17898082-c350-4ba7-bfca-93734ec78d6a.svg)

** plug: generated with [magic_duckdb](https://github.com/iqmo-org/magic_duckdb) using graphviz behind the scenes: `%%dql -e ast_draw`

**Comment by kryonix** [comment]
> Which version of DuckDB did you test it on?

The next release won't have this exception anymore. I did compile DuckDB myself, so it's the `master` branch version.

> First, I found that DuckDB had the support for mutual recursion, to some degree. An example supported is as follows:

DuckDB performs inlining of these CTEs behind the scenes. So what acually gets executed looks more like this:

```
SELECT * FROM (WITH RECURSIVE x (id) AS
                (SELECT 0
                    UNION ALL
                 SELECT x.id+1
                 FROM x, (SELECT z.id
                          FROM (SELECT x.id
                                FROM x, t
                                WHERE x.id = t.id AND x.id < 5) AS z, t
                          WHERE z.id = t.id AND z.id < 5) AS y
                 WHERE x.id=y.id AND x.id < 5);
```

Your three CTEs are combined into one. That's why it works.

**Comment by amirsh** [comment]
Many thanks to both. I really appreciate your help.

Not handling mutual recursive (and magically handling it in some cases by inlining) is not clear to the user at all.

**Comment by amirsh** [comment]
@kryonix there was a tiny bug in the first version of your implementation. One fix is this:

```sql
WITH RECURSIVE prim(x, y, v) AS
(
  (SELECT x, y, [x, y]
  FROM   edge
  ORDER BY w
  LIMIT    1)
    UNION ALL
  (SELECT x, y, v || [p.x, p.y]
   FROM (SELECT e.x, e.y, e.w, p.v
         FROM   prim AS p, edge AS e
         WHERE
           (   ARRAY_CONTAINS(v, e.x)
                AND NOT ARRAY_CONTAINS(v, e.y))
           OR (   NOT ARRAY_CONTAINS(v, e.x)
                AND ARRAY_CONTAINS(v, e.y))) AS p
   ORDER BY w
   LIMIT 1)
)
SELECT * FROM prim;
```

The point is that the next minimum edge is not necessarily connected to the previously found edge.
