### ISSUE TITLE
Duckdb: COPY sql command doesn't preserve or give any option to set field_id information for parquet files

### ISSUE THREAD

**Issue by kamaljit-1991** [duckdb/duckdb#7229]
### What happens?

We have been using duckdb for a quite a few months now. 1 issue we noticed is : while writing the data from 1 parquet file to another parquet file using copy command it doesn't take **field_id** input. Even if the source parquet file contains the **field_id** values after writing the data to a new file all the field_ids are resetting to 0.

For example : I have this source parquet file where the schema is : 
```
message table {
  optional int64 _fivetran_synced (TIMESTAMP(MICROS,true)) = 1;
  optional int32 id = 2;
  optional binary attr (STRING) = 3;
}
```

After I run this command to write all the data to a new file : 
copy(select id, attr, _fivetran_synced from '<source_file_name>') to '<new_file_name>' (FORMAT 'parquet');
The schema of the new file becomes : 
```
message duckdb_schema {
  optional int32 id (INTEGER(32,true));
  optional binary attr (STRING);
  optional int64 _fivetran_synced (TIMESTAMP(MICROS,false));
}
```

When I queried the parquet_schema of the file that shows field_ids as only 0s. This is causing issues in our iceberg table. 
I tried to search duckdb doc. No where I found any option to set **field_id** while writing to a parquet file. 

 **ASK :** 
1. Did I miss anything ? Means is there any option available to set field_ids for parquet schema ?
2. Do you consider this as bug or it's as per design ? Do you plan to support this anytime soon ?

### To Reproduce

[iceberg_source.parquet.gz](https://github.com/duckdb/duckdb/files/11318906/iceberg_source.parquet.gz)

I attached a parquet file containing the field_ids. You can use the same one to write to another parquet file and see the result.

### OS:

mac os ventura 13.0.1

### DuckDB Version:

0.6.1

### DuckDB Client:

Dbeaver

### Full Name:

Kamaljit Pati

### Affiliation:

Fivetran pvt.ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by kamaljit-1991** [comment]
Thank you @Mytherin for your quick reply. 

This field_id is required for iceberg table format. Iceberg uses it internally for it's APIs and because of that anyone which uses iceberg read API is causing issues. I agree that if they could fix that it would also work. But at the same time if duckdb could provide some way of setting it then also it would work. 

In the sql query where we are able to add **format, filename etc** for parquet file if there you could provide the facility to add another field such as **field_id='1, 2, 3'** which could assign the field_ids to the columns for the parquet file then it would be awesome. 

But please let me know about your thoughts on this and could I create a feature request for you guys ?

**Comment by whenamanlies** [comment]
@Mytherin could we get a comment on parquet vs [iceberg spec](https://iceberg.apache.org/spec/#parquet) standards?

> Values should be stored in Parquet using the types and logical type annotations in the table below. **Column IDs are required**.

**Comment by Mytherin** [comment]
This is already supported in #7696
