### ISSUE TITLE
Stack smashing detected?!

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#7235]
### What happens?

Using DuckDB v0.7.1 b00b93f0b1:

```sql
create table test as select * from '/tmp/test_14173554586610753268.parquet';
```

returns:
```text
*** stack smashing detected ***: terminated
```

on 
are@archlinux ~> uname -a
Linux archlinux 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux

I wrote the Parquet File by myself, based on a H2 database table via [JDBCResultWrite](https://github.com/manticore-projects/JDBCParquetWriter).

For tests, you can [download the Parquet File](http://manticore-projects.com/download/test_14173554586610753268.parquet) (68 MByte).

### To Reproduce

```sql
create table test as select * from '/tmp/test_14173554586610753268.parquet';
```

With  [Parquet File](http://manticore-projects.com/download/test_14173554586610753268.parquet) (68 MByte).

### OS:

Arch Linux

### DuckDB Version:

0.7.1 b00b93f0b1

### DuckDB Client:

Shell and JDBC

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects Co. Ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by manticore-projects** [comment]
I am pretty sure that the Parquet File is valid, since I can read it with Python FastParquet:
```python
from fastparquet import ParquetFile
pf = ParquetFile('/tmp/test_14173554586610753268.parquet')
df = pf.to_pandas()
```

**Comment by Mytherin** [comment]
Thanks for the report! The Parquet file has statistics are incorrectly encoded. Rather than being encoded as the decimal data type itself, they are encoded as a string instead. As per the spec [statistics should be encoded using the plain encoding of the data type](https://github.com/apache/parquet-format/blob/c185faf0c4fc0c7d3075d1abd4ed0985cdbe5d87/src/main/thrift/parquet.thrift#L202).

It is likely that fastparquet does not read the statistics and therefore does not run into this issue.

I have pushed a fix to correctly detect the invalid statistics for the decimal type in #7238.

**Comment by manticore-projects** [comment]
Greetings!

This was probably the fastest response I have ever gotten on GitHub! Thank you!

However, I am not sure what to make out of the response (beside having triggered a smaller bug in `DuckDB`).
What I do understand: Statistics of the Parquet File are wrong. However, I do not write those but instead use Apache Hadoop and Parquet to write `Groups` into a `Schema`.

I assume my Schema is correct?
If so, what would be wrong with this approach:
```java
        MessageType schema = getParquetSchemaFromResultSet(tableName, metaData);

        Configuration configuration = new Configuration();
        GroupWriteSupport.setSchema(schema, configuration);

        ExampleParquetWriter.Builder builder = ExampleParquetWriter.builder(outputPath)
                .withConf(configuration)
                .withType(schema)
                .withCompressionCodec(compressionCodecName)
                .withDictionaryEncoding(false)
                .withValidation(false)
                .withWriteMode(ParquetFileWriter.Mode.OVERWRITE);
```

Apologies for dragging this a bit out of the scope. However, in my book a Parquet File should be ok when Apache Parquet can verify it, no?

**Comment by manticore-projects** [comment]
Sorry to be a burden, I made another Test of JDBC --> Parquet --> DuckDB, again via JDBCResultsetWriter and it works including Decimals:

```text
D create table test1 as select * from '/tmp/execution_ref18304413819703605400.parquet';
D select * from test1;
┌──────────────────┬────────────┬────────────────────────────┬─────────────────┐
│ ID_EXECUTION_REF │ VALUE_DATE │        POSTING_DATE        │     AMOUNT      │
│      int64       │    date    │  timestamp with time zone  │  decimal(12,2)  │
├──────────────────┼────────────┼────────────────────────────┼─────────────────┤
│                1 │ 2021-01-06 │ 2021-01-15 07:48:40.851+07 │ 540830365251.06 │
│                2 │ 2021-01-12 │ 2021-01-13 06:55:10.329+07 │   2371154214.88 │
│                3 │ 2021-01-13 │ 2021-01-14 05:00:41.136+07 │                 │
│                4 │ 2021-01-14 │ 2021-01-15 01:03:56.375+07 │ 563036017257.44 │
│                5 │ 2021-01-15 │ 2021-01-16 00:19:20.212+07 │      9257741.33 │
└──────────────────┴────────────┴────────────────────────────┴─────────────────┘
```

[execution_ref18304413819703605400.parquet.zip](https://github.com/duckdb/duckdb/files/11324166/execution_ref18304413819703605400.parquet.zip)


Similar data, same code and approach. So what is different? (Forgive me my ignorance, I am quite new here.)

**Comment by manticore-projects** [comment]
I think you were right and the problem was on my end: Writing DECIMAL or NUMERIC as BINARY technically works sometimes(!), but does not transport the correct value.  

So, for any DECIMAL/NUMERIC with precision<=18 this seems to be correct and the Parquet File will be read by DuckDB:
```java
if (scale > 0 && precision<=18) {
    group.add(columnName, decimal.unscaledValue().longValue());
}
```

Apologies for stretching my luck: any idea what to do for precision > 18 (e. g. amounts in JPY, IDR -- not to speak about Simbabwe). The following  seems to be wrong and was the root cause for exposing the small DuckDB issue:
```java
if (scale > 0 && precision>18) {
    group.add(columnName, Binary.fromString( decimal.toPlainString()) );
}
```

**Comment by manticore-projects** [comment]
Thank you for your patience, I eventually got it right.  Large Decimals need to be typed as `Types.required(PrimitiveType.PrimitiveTypeName.BINARY) .as(LogicalTypeAnnotation.decimalType(scale, precision))` in order to be written as:

```java
byte[] bytes = decimal.unscaledValue().toByteArray();
group.add(columnName, Binary.fromConstantByteArray(bytes) );
```

So technically, it was all my fault and we can close this issue.
Thank you again for helping and patience.

**Comment by Mytherin** [comment]
No worries! Great that you could resolve it.
