### ISSUE TITLE
Glob function with subquery parameter crashes CLI

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#7239]
### What happens?

When (incorrectly!) trying to use a subquery as an input parameter to the `glob` function, the CLI crashes. @Mytherin noted that to support that case, the glob function would need to be refactored into a table-in-out function. @Tishj mentioned that this is on his todo list!

### To Reproduce

```sql
select * from glob((select ['any_file.csv'] as test_col));
```

### OS:

Windows

### DuckDB Version:

v0.7.2-dev2430

### DuckDB Client:

CLI

### Full Name:

Alex Monahan

### Affiliation:

DuckDB Labs and Intel

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
This is fixed on a branch of my fork:
```sql
D select * from glob((select ['any_file.csv'] as test_col));
Error: Binder Error: This table function is not a table in-out function, it can't take a subquery
LINE 1: select * from glob((select ['any_file.csv'] as test_c...
```
