### ISSUE TITLE
Segmentation Fault when Invoking a Table Function that accepts Varargs

### ISSUE THREAD

**Issue by MarkRoddy** [duckdb/duckdb#7244]
### What happens?

When invoking a table function that accepts varargs, a segmentation fault occurs.

The segmentation faults occurs on [this line](https://github.com/duckdb/duckdb/blob/master/src/planner/binder/tableref/bind_table_function.cpp#L260) where there is for loop over the vector supplied arguments with the goal of casting them to their expected types.  The current index of the loop is then used to index into the function's vector of defined arguments. Because of the use of varargs, this vector will be smaller, resulting in an out of bounds access.

### To Reproduce

I am working on an extension which includes a table function that allows passing arguments via varargs. I attempted to produce a minimal reproduction using an existing table function. However, I have not been able to find another table function that supports varargs argument calling semantics. I acknowledge that "use my table function" is not as succinct instruction as would be desired. Happy to work with folks on how best to provide minimal reproduction steps if this is not sufficient.

### OS:

Linux

### DuckDB Version:

HEAD

### DuckDB Client:

CLI

### Full Name:

Mark Roddy

### Affiliation:

launchit.ai

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by MarkRoddy** [comment]
Note I've created [PR-7245](https://github.com/duckdb/duckdb/pull/7245) which fixes this issue. I can confirm that it stops the segmentation fault from occurring in the extension I'm working on.

**Comment by Tishj** [comment]
I think this is related to #7239, could you add a reproduction example so we can properly judge if that's the case?

**Comment by MarkRoddy** [comment]
@Tishj Happy to! Do you have any guidance on what you'd be looking for? The only way I've been able to reproduce is with an extension I'm working on that includes a table function. Reproducing seems to require a Table Function that uses the `varargs` feature, and I have been able to find another Table Function that does so.

The only thing I could think of would be to make a new extension that doesn't really do anything but does use the `varargs` feature. Is there anything simpler you might have in mind?
