### ISSUE TITLE
`INTERNAL Error: Logical column index 1 out of range`

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#7250]
### What happens?

The following program triggers this internal error:
```
CREATE TABLE t21(c0 INT64);
CREATE TABLE t0(c0 INT64, c1 INT64);

CREATE VIEW v0(c0) AS SELECT t0.c1 FROM t21, t0;

WITH temp_table1 AS(SELECT (t21.c0) AS c0 FROM t21) SELECT (t0.rowid) AS c0 FROM v0, t0, temp_table1 WHERE ((temp_table1.c0)<(( t0.rowid)));
```

I notice there are two issues also related to this https://github.com/duckdb/duckdb/issues/5880 and https://github.com/duckdb/duckdb/issues/5039, I read your discussion and found the core of these two report is the type cast. But in this report, I use the same type `INT64` and do not use any type cast. So I report this issue.

For this query, although `temp_table1` is just an alias of `t21`, but its equivalent query `SELECT (t0.rowid) AS c0 FROM v0, t0, t21 WHERE ((t21.c0)<(( t0.rowid)));` can not trigger this internal error.

### To Reproduce

I build duckdb from the latest commit version https://github.com/duckdb/duckdb/commit/98590facb85dec9607f40c1dc5a6cf642783eb7f

### OS:

ubuntu 22.04

### DuckDB Version:

https://github.com/duckdb/duckdb/commit/98590facb85dec9607f40c1dc5a6cf642783eb7f

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tmonster** [comment]
Can confirm this happens in the join order optimiser. I'll look into this
