### ISSUE TITLE
Remove unused left outer join

### ISSUE THREAD

**Issue by code1704** [duckdb/duckdb#7251]
### What happens?

Remove unused left outer join

### To Reproduce

```
import pandas as pd
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
df2 = pd.DataFrame({"a": [1, 2, 3], "c": [4, 5, 6]})
df3 = pd.DataFrame({"a": [1, 2, 3], "d": [4, 5, 6]})
```

query: expect no scan for df3
```
EXPLAIN SELECT b from df1 left outer join df2 on df1.a = df2.a left outer join df3 on df1.a = df3.a
```

![image](https://user-images.githubusercontent.com/110730540/234477887-ff3433c8-4878-4fdd-950a-319e2ca7ae25.png)

### OS:

all

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Jack

### Affiliation:

PKU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Just thinking out loud (as another end user):

I don't think the db can ignore the join, since the cardinality of the result depends on df3. For example: 

```
import pandas as pd
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
df2 = pd.DataFrame({"a": [1, 2, 3], "c": [4, 5, 6]})
df3a = pd.DataFrame({"a": [1, 2, 3]})
df3b = pd.DataFrame({"a": [1, 2, 3, 1, 2, 3]})

with duckdb.connect() as con:
    dfa = con.execute("SELECT b from df1 left outer join df2 on df1.a = df2.a left outer join df3a on df1.a = df3a.a").df()
    print(len(dfa))
    dfb = con.execute("SELECT b from df1 left outer join df2 on df1.a = df2.a left outer join df3b on df1.a = df3b.a").df()
    print(len(dfb))
```
> 3
> 6

**Comment by code1704** [comment]
> Just thinking out loud (as another end user):
> 
> I don't think the db can ignore the join, since the cardinality of the result depends on df3. For example:
> 
> ```
> import pandas as pd
> df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
> df2 = pd.DataFrame({"a": [1, 2, 3], "c": [4, 5, 6]})
> df3a = pd.DataFrame({"a": [1, 2, 3]})
> df3b = pd.DataFrame({"a": [1, 2, 3, 1, 2, 3]})
> 
> with duckdb.connect() as con:
>     dfa = con.execute("SELECT b from df1 left outer join df2 on df1.a = df2.a left outer join df3a on df1.a = df3a.a").df()
>     print(len(dfa))
>     dfb = con.execute("SELECT b from df1 left outer join df2 on df1.a = df2.a left outer join df3b on df1.a = df3b.a").df()
>     print(len(dfb))
> ```
> 
> > 3
> > 6

Thanks, is there any join to avoid  cartesian product?
We created a template sql to join 1000+ tables, and we know there will be no need to use cartesian product.
```
WITH A as (select * from a join b join c join d ....)
select x from A
```

**Comment by Mytherin** [comment]
> Thanks, is there any join to avoid cartesian product?

There is a debug setting for this.

```sql
SET debug_force_no_cross_product=true;
SELECT * FROM (select 42) t1, (select 84) t2;
Error: Invalid Input Error: Query requires a cross-product, but 'force_no_cross_product' PRAGMA is enabled
```

**Comment by Mytherin** [comment]
As mentioned by @paultiq joins cannot be removed without guarantees that each tuple in the join has exactly one match. This is generally only possible if foreign key constraints are defined, which is not the case here. See some more discussion in #6464.

**Comment by code1704** [comment]
> #6464

Thanks. Seems it does not work for primary key.

```
create table t1 (a int, PRIMARY KEY (a));
insert into t1 values(1);
insert into t1 values(2);
create table t2 (a int, b int, PRIMARY KEY (a));
insert into t2 values(1, 2);
insert into t2 values(2, 4);
explain select t1.a from t1 JOIN t2 on t1.a = t2.a;
```
