### ISSUE TITLE
Linux archpi64 - cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by 373260656** [duckdb/duckdb#7255]
### What happens?

-bash: ./duckdb: cannot execute binary file: Exec format error

### To Reproduce

I use Linux ecs-c4ea 4.19.90-17.5.ky10.aarch64  GNU/Linux, and when I try to use the CLI build, I get this error:

-bash: ./duckdb: cannot execute binary file: Exec format error

Here are the reproduction steps：
  Download duckdb_cli-linux-amd64.zip and unzip it , exec ./duckdb and then error:
-bash: ./duckdb: cannot execute binary file: Exec format error

use duckdb_cli-linux-rpi.zip or duckdb_cli-linux-i386.zip  , also same errors

so , How can I fix this problem ?  Thanks.

[puser@ecs-c4ea ~]$ strings /lib64/libc.so.6 |grep GLIBC_
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28

[puser@ecs-c4ea ~]$ ldd --version

ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

### OS:

Linux version 4.19.90-17.5.ky10.aarch64

### DuckDB Version:

0.7.1

### DuckDB Client:

Java

### Full Name:

Dicky 

### Affiliation:

zhang

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
You're trying to use a build made for AMD64 with a AARCH64 architecture, I believe that's expected to not work
