### ISSUE TITLE
[julia] compile error when using DBInterface.prepare with StreamResult

### ISSUE THREAD

**Issue by whatsthecraic** [duckdb/duckdb#7260]
### What happens?

There is a small compile error in the Julia package when trying to pass StreamResult to DBInterface.prepare, e.g. 

```
connection = DBInterface.connect(DuckDB.DB)
statement = DBInterface.prepare(connection, "SELECT 1" ) # this works
statement = DBInterface.prepare(connection, "SELECT 1", DuckDB.StreamResult) # error

ERROR: MethodError: no method matching prepare(::DuckDB.DB, ::String, ::Type{DuckDB.StreamResult})
Closest candidates are:
  prepare(::DuckDB.DB, ::AbstractString) at ~/.julia/packages/DuckDB/PMwHV/src/result.jl:818
  prepare(::DuckDB.Connection, ::AbstractString, ::Type) at ~/.julia/packages/DuckDB/PMwHV/src/result.jl:816
  prepare(::Function, ::AbstractString) at ~/.julia/packages/DBInterface/1Gmxx/src/DBInterface.jl:60
  ...


# This works as well
statement = DuckDB.Stmt(connection, "SELECT 1", DuckDB.StreamResult)

``` 

Admittedly I haven't validated the latest master for the julia package, the issue is present in v0.7.1

### To Reproduce

See description above

### OS:

Linux

### DuckDB Version:

0.7.1

### DuckDB Client:

Julia 

### Full Name:

Dean De Leo

### Affiliation:

RelationalAI

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! It seems like an overload is indeed missing. Does this work?

```julia
statement = DBInterface.prepare(connection.main_connection, "SELECT 1", DuckDB.StreamResult)
```

**Comment by whatsthecraic** [comment]
yes, that works! thx for the quick reply!
