### ISSUE TITLE
[R] ASOF join do not match fractional seconds properly

### ISSUE THREAD

**Issue by rdavis120** [duckdb/duckdb#7272]
### What happens?

When trying to benchmark the latest development version of ASOF join, I found two issues through the R API.  https://github.com/duckdb/duckdb/discussions/3207#discussioncomment-5736942

First, there seems to be an issue with the asof join and fractional seconds in timestamps.  It will round the date and not interpret the fractional seconds properly, causing it to join with rows after the date.

Also, I got an exception when trying to use an arrow virtual table.

### To Reproduce

```r
set.seed(1)
end <- as.POSIXct("2020-06-20")
start <- as.POSIXct("2020-1-1")
# Every minute
calendar <- data.frame(date = seq(from = start, to = end, by = "+1 min"))
N <- 5e6
data <- data.frame(date = end - runif(N) * as.integer(difftime(end, start, units = "secs")), value = runif(N))
data <- data[order(data[["date"]]),]

> # The fractional seconds on the first row of data is after first row of calendar 
> # Therefore the asof join result should be NA for first row

> print(format(head(calendar), format = '%Y-%m-%d %H:%M:%OS4'), row.names=F)
                     date
 2020-01-01 00:00:00.0000
 2020-01-01 00:01:00.0000
 2020-01-01 00:02:00.0000
 2020-01-01 00:03:00.0000
 2020-01-01 00:04:00.0000
 2020-01-01 00:05:00.0000
> print(format(head(data), format = '%Y-%m-%d %H:%M:%OS4'), row.names=F)
                     date      value
 2020-01-01 00:00:00.5605 0.03036744
 2020-01-01 00:00:02.9301 0.13016820
 2020-01-01 00:00:05.4268 0.69509474
 2020-01-01 00:00:06.4173 0.90071963
 2020-01-01 00:00:07.7826 0.15166126
 2020-01-01 00:00:14.4407 0.17950791

# data.table ( the correct results for fractional seconds with an NA in the first row )
data.dt <- data.table::data.table(data , key = 'date')
calendar.dt = data.table::data.table(calendar, key = 'date')
data.dt[calendar.dt, on = "date", roll = TRUE]
>                        date      value
>      1: 2020-01-01 00:00:00         NA
>      2: 2020-01-01 00:01:00 0.41639909
>      3: 2020-01-01 00:02:00 0.23235543
>      4: 2020-01-01 00:03:00 0.67948438
>      5: 2020-01-01 00:04:00 0.43368901

     
# duckdb
conn <- DBI::dbConnect(duckdb::duckdb( ))
# virtual tables
duckdb::duckdb_register( conn, "data_v", data)
duckdb::duckdb_register( conn, "calendar_v", calendar)
DBI::dbGetQuery(conn, "SELECT * FROM calendar_v ASOF JOIN data_v USING(date)") |> data.table::data.table()
>                        date      value
>      1: 2020-01-01 05:00:00 0.03036744
>      2: 2020-01-01 05:01:00 0.41639909
>      3: 2020-01-01 05:02:00 0.59852317
>      4: 2020-01-01 05:03:00 0.67948438
>      5: 2020-01-01 05:04:00 0.43368901

# arrow
data.path = tempfile()
arrow::write_dataset(data, path = data.path, format = 'feather')
duckdb::duckdb_register_arrow( conn, "data_a", data.path)
calendar.path = tempfile()
arrow::write_dataset(calendar, path = calendar.path, format = 'feather')
duckdb::duckdb_register_arrow( conn, "calendar_a", calendar.path)
DBI::dbGetQuery(conn, "SELECT * FROM calendar_a ASOF JOIN data_a USING(date)") |> data.table::data.table()
> Error in arrow_scannable$schema :
> $ operator is invalid for atomic vectors
> Error: rapi_prepare: Failed to prepare query SELECT * FROM calendar_a ASOF JOIN data_a USING(date)
> Error: Invalid Error: std::exception
```

### OS:

macOS

### DuckDB Version:

0.8.0

### DuckDB Client:

R 4.2.2

### Full Name:

Roger Davis

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Thanks for the report!  

Can you describe what the two data sets look like? (I'm not an R user.) And the arrow issue is probably separate.

**Comment by hawkfish** [comment]
By that I mean you have shown what the data looks like to R for the calendar table, but not the data table.

**Comment by rdavis120** [comment]
Sure, I updated the original post.

**Comment by hawkfish** [comment]
One small thing - it looks like the R code generates an outer join but the query you used is an inner join.

Another thing that might be causing problems is that you didn't order your results. The calendar table is large enough that it is scanned in parallel, so the results may not be deterministic depending on threading.

Also, you have not specified which `date` column will be returned by the query and it seems to be choosing the calendar date. That seems like a binder issue of some kind, but it explains why you are not seeing fractional times.

Fixing these issues and translating to SQL, I get this:

```sql
SELECT SETSEED(0.8675309);

CREATE VIEW calendar_v AS 
	SELECT date
	FROM range('2020-01-01'::TIMESTAMP, '2020-06-20'::TIMESTAMP, INTERVAL 1 MINUTE) tbl(date)
;

CREATE TABLE data_v AS
	SELECT 
		'2020-06-20'::TIMESTAMP - INTERVAL (random() * date_diff('us', '2020-01-01'::TIMESTAMP, '2020-06-20'::TIMESTAMP)) MICROSECONDS AS date,
		random() AS value
	FROM range(5000000)
;

SELECT date FROM calendar_v LIMIT 1;
-- 2020-01-01 00:00:00

SELECT date FROM data_v LIMIT 1;
-- 2020-05-10 21:36:36.202067

SELECT calendar_v.date AS cdate, data_v.date AS ddate, value
FROM calendar_v ASOF LEFT JOIN data_v USING(date)
ORDER BY ALL
LIMIT 5;
```

| cdate | ddate | value |
| -- | -- | -- |
| 2020-01-01 00:00:00 | NULL | NULL |
| 2020-01-01 00:01:00 | 2020-01-01 00:00:58.08327 | 0.8025422510231245 |
| 2020-01-01 00:02:00 | 2020-01-01 00:01:58.908166 | 0.1910701583118807 |
| 2020-01-01 00:03:00 | 2020-01-01 00:02:59.585145 | 0.7246391118328643 |
| 2020-01-01 00:04:00 | 2020-01-01 00:03:44.121959 | 0.5160406244723221 |

**Comment by hawkfish** [comment]
Aha - I know what the bug is:  it's the `USING` construct. In the past this has referred to equality conditions, so it didn't matter which side you picked. But for the inequality condition you want to return *both* sides. I wonder if this is also a problem for regular outer joins too (which can also differ).

**Comment by hawkfish** [comment]
@rdavis120 I'll look into this, but can you file the arrow issue separately?

**Comment by hawkfish** [comment]
Oddly this is what ClickHouse does for `USING` clauses. I think this is confusing, so I'm going to change it. There will still only be one column returned, but it will be from the probe (left) side, not the build (right) side.

**Comment by hawkfish** [comment]
We have decided that the current behaviour is correct: We return the probe side inequality key with `USING`, and the probes in your example do not have fractional seconds. If you list the columns explicitly, you can get both of them.

**Comment by hawkfish** [comment]
I will update the docs, though, as this was not obvious even to me!
