### ISSUE TITLE
Large runtime difference between two ways of writing the same left join

### ISSUE THREAD

**Issue by BorgeJorge** [duckdb/duckdb#7273]
### What happens?

Greetings,

I'm not sure this qualifies as a bug, but I've noticed a large runtime difference between two ways of writing the same outer join.

I often do left joins where the LHS table has IDs and program enrollment dates for a relatively small patient cohort (1K-10K), and the RHS table can have up to 100M claims for a much larger patient population, each with cost and service date.

Traditionally I've written the query like this:

```sql
select l.id
      ,sum(coalesce(r.cost,0))
from patients l left join claims r
on l.id = r.id
and date_diff('month',l.enroll_date,r.claim_date) between -12 and -1
group by l.id
```

Which produces the total medical cost for each patient in the pre-program year (including records for patients with no claims and thus zero costs).

Obviously, with a small cohort and a large claims table, most of the claims are irrelevant, and I find that using a nested inner join that pre-selects only claims for patients in the cohort and for each patient's pre-program year speeds up the query considerably:

```sql
with claims_subset as (
select l.id
      ,r.cost
from patients l join claims r
on l.id = r.id 
and date_diff('month',l.enroll_date,r.claim_date) between -12 and -1)
select l.id
      ,sum(coalesce(r.cost,0))
from patients l left join claims_subset r
on l.id = r.id
group by l.id
```

With ~10K patients and ~3M claims, the first query takes 44 seconds and the second takes .08 seconds, making it 550 times faster. This discrepancy increases when I scale up to larger files and more grouping criteria (like also grouping by category of service). In fact, at scale, I stopped the first query after several hours, whereas the second query took 15 seconds. I usually use DuckDB in R, but I've also replicated this in Python.

### To Reproduce

This is a simplified example but you can get a feel for the discrepancy with this:

```sql
# create a small LHS table and a large RHS table where some ids match and most do not:
create table ids as select unnest(range(1,40000,5)) as id;
create table claims as select unnest(range(1,1000000000,3)) as id;

# traditional left join:
select ids.id, count(*)
from ids left join claims
on ids.id = claims.id
group by ids.id;

# faster left join producing the same results (about 4 time faster):
with claims_subset as (select claims.id from ids join claims using(id))
select ids.id, count(*)
from ids left join claims_subset
on ids.id = claims_subset.id
group by ids.id;
```

### OS:

Windows 10 x64

### DuckDB Version:

0.8.0

### DuckDB Client:

R and Python

### Full Name:

Tod Mijanovich

### Affiliation:

New York University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Just glancing at this, I think the difference is just the left join vs inner join. I can't comment on whether this is good or bad, just pointing out the narrower reproduction of the timing results. 

```
import duckdb

with duckdb.connect() as con:
    con.execute("create table ids as select id from range(1,40000,5) t(id);")
    con.execute("create table claims as select id from range(1,1000000000,3) as t(id);")

    # Slow query
    %timeit con.execute("select ids.id, count(*) from claims left join ids on ids.id = claims.id group by ids.id")

    # Second query performs equivalently to the fast query 
    %timeit con.execute("select ids.id, count(*) from claims join ids on ids.id = claims.id group by ids.id")
```
> 1.88 s ± 163 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 160 ms ± 8.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Visually, you can see the difference in cardinality from explain analyze:

# Fast
![fast](https://user-images.githubusercontent.com/104510378/234835775-430b8b87-9a6d-4daa-9612-9386851e2418.svg)

# Slow
![slow](https://user-images.githubusercontent.com/104510378/234835777-f7760a25-ae2d-4164-9c51-d604836fcb63.svg)

**Comment by BorgeJorge** [comment]
Thanks Tom. If it's useful, below is a reproducible example that more closely mirrors my usual join, which is to aggregate medical costs in the rhs table within time periods relative to patient enrollment dates in the lhs table. This example shows an 800x speedup (16 seconds vs. .02 seconds), which is much closer to the speedup I get using real data.

```
-- create lhs table with 10K sequential ids and random enrollment dates
create table lhs as select * from range(10000) lhs(id);
alter table lhs add column enroll_date date;
update lhs set enroll_date = date '2000-01-01' + cast(round(random()*3000) as integer);

-- create rhs table with 1M random ids, claim dates, and costs
create table rhs as select * from range(1000000) rhs(id);
update rhs set id = random() * 1000000;
alter table rhs add column claim_date date;
update rhs set claim_date = date '2000-01-01' + cast(random()*3000 as integer);
alter table rhs add column claim_cost double;
update rhs set claim_cost = random() * 10000;

-- traditional left join, to calculate costs in the 12 months after each patient's enrollment date
select lhs.id, sum(coalesce(claim_cost,0))
from lhs left join rhs on lhs.id = rhs.id
and datediff('month',enroll_date,claim_date) between 1 and 12
group by lhs.id;

-- left join after subsetting cte
with rhs_subset as
(select rhs.id, claim_cost from lhs join rhs on lhs.id = rhs.id
and datediff('month',enroll_date,claim_date) between 1 and 12)
select lhs.id, sum(coalesce(claim_cost,0))
from lhs left join rhs_subset on lhs.id = rhs_subset.id
group by lhs.id;
```

For comparison, I ran the above using SAS PROC SQL (using a view rather than a CTE, which SAS doesn't have), and the runtimes were .25 seconds and .15 seconds.

Thanks again.

**Comment by Tmonster** [comment]
> So unfortunately, I had the ordering of our build side and probe side wrong. In your first example the hash and probe sides of the join are correct.

That isn't to say there isn't a fix for this, @lnkuiper believes that the scan for unmatched entries may be broken/not properly parallelized.

**Comment by BorgeJorge** [comment]
Thanks for letting me know, Tom. Fingers crossed for making it into 0.8.0!

**Comment by BorgeJorge** [comment]
Thanks again Tom. Just FYI: Using 0.8.0 under R, the traditional left join syntax above now runs in 4.25 seconds (about 4 times faster than 0.7.1) vs. .05 seconds for the syntax with the CTE. So the traditional syntax now takes 85 times longer to run than the CTE syntax, whereas under 0.7.1 it took 800 times longer.
