### ISSUE TITLE
Cannot copy data to SQLite table due to internal bug IsSource

### ISSUE THREAD

**Issue by bladko-tom** [duckdb/duckdb#7277]
### What happens?

When trying to save data to SQLite table when reading from other sources or files. It is possible to write data manually using values() but not from other sources. It was possible in the past and not sure if its not not possible or its a bug. 

If extension supposed to be scanner, reader only then i would love to see some notes either in error handler or in docs (sorry if i could not find it so far).

"INTERNAL Error: Source of pipeline does not have IsSource set"

### To Reproduce

```
DB = duckdb.connect()
DB.execute(f"ATTACH 'sql_lite_path' AS A (TYPE SQLITE, READ_ONLY FALSE);")
DB.execute(f"DROP TABLE IF EXISTS A.t1;")
DB.execute(f"CREATE TABLE A.t1 AS (SELECT * FROM 'parquet_file_path');")
DB.execute("DETACH A")
```

### OS:

Windows 10, x64

### DuckDB Version:

v0.7.2-dev2675 688b2f1f8c

### DuckDB Client:

Python & CLI

### Full Name:

Tom Bladko

### Affiliation:

Independent 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! Could you please move this to the [correct repository](https://github.com/duckdblabs/sqlite_scanner)?
