### ISSUE TITLE
GROUP_CONCAT neglects passed in separator with ORDER BY.

### ISSUE THREAD

**Issue by MatteoLacki** [duckdb/duckdb#7281]
### What happens?

The GROUP_CONCAT neglects the passed in separator in the following case:

```python
import duckdb
import pandas as pd


TEST = pd.DataFrame({
    "A": ['a','a','a','b','b'],
    "B": [3, 2, 1, 4, 6],
})

duckdb.query("""
SELECT
GROUP_CONCAT(
    B,
    '+'
) AS unordered_concat,
GROUP_CONCAT(
    B ORDER BY B,
    '+'
) AS ordered_concat,
FROM 'TEST'
GROUP BY A
""")
```

```
---------------------
--- Relation Tree ---
---------------------
Subquery

---------------------
-- Result Columns  --
---------------------
- unordered_concat (VARCHAR)
- ordered_concat (VARCHAR)

---------------------
-- Result Preview  --
---------------------
unordered_concat        ordered_concat
VARCHAR VARCHAR
[ Rows: 2]
3+2+1   1,2,3
4+6     4,6
```

### To Reproduce
```
import duckdb
import pandas as pd


TEST = pd.DataFrame({
    "A": ['a','a','a','b','b'],
    "B": [3, 2, 1, 4, 6],
})

duckdb.query("""
SELECT
GROUP_CONCAT(
    B,
    '+'
) AS unordered_concat,
GROUP_CONCAT(
    B ORDER BY B,
    '+'
) AS ordered_concat,
FROM 'TEST'
GROUP BY A
""")
```

### OS:

Fedora36

### DuckDB Version:

duckdb==0.5.0

### DuckDB Client:

Python

### Full Name:

Mateusz Łącki

### Affiliation:

University Medical Center Johannes Gutenberg, Mainz

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

The `ORDER BY` clause should be the last clause in the function:

```sql
D SELECT A, GROUP_CONCAT(B, '+' ORDER BY B) AS ordered_concat FROM 'TEST' GROUP BY A;;
┌─────────┬────────────────┐
│    a    │ ordered_concat │
│ varchar │    varchar     │
├─────────┼────────────────┤
│ a       │ 1+2+3          │
│ b       │ 4+6            │
└─────────┴────────────────┘
```

The system should throw an error in the case where the `ORDER BY` is misplaced - I will have a look.

**Comment by Mytherin** [comment]
Actually unfortunately both are valid SQL. In the case where `ORDER BY` is placed after the second argument we are ordering by two arguments (`B` and the constant `'+'`).

```sql
SELECT A, GROUP_CONCAT(B ORDER BY B, '+') AS ordered_concat FROM 'TEST' GROUP BY A;
```

So there is no easy path to throwing a descriptive error here.

**Comment by MatteoLacki** [comment]
Hi! 

Thanks for looking into it.
I can already get the effect I wanted to have.

Nevertheless, what should then be the outcome of 
```sql
SELECT A, GROUP_CONCAT(B ORDER BY B, '+') AS ordered_concat FROM 'TEST' GROUP BY A;
```
as you mention it is a valid statement?

Sorry for bugging you.
And thanks a lot for all of your work: you are making my code so much better!


Best wishes!

**Comment by Mytherin** [comment]
An `ORDER BY` clause can have multiple predicates, e.g.:

```sql
SELECT *
FROM tbl
ORDER BY a, b, c, ...
```

 `GROUP_CONCAT` takes an optional second parameter - if none is provided a comma is used.

In this case the aggregate is `GROUP_CONCAT(b)` with an `ORDER BY B, '+'`. While ordering by a string literal is obviously not very useful - it is valid SQL nevertheless.
