### ISSUE TITLE
Type casting from JSON input raises conversion error

### ISSUE THREAD

**Issue by rgoubet** [duckdb/duckdb#7285]
### What happens?

When the value of a record is loaded from JSON, string results from JSON queries cannot be cast to other data types.

### To Reproduce

```sql
D create or replace table weather as select * from read_json_objects('https://worldweather.wmo.int/en/json/278_en.json');
D select json->'city'->'climate'->'climateMonth'->>0->'climateFromMemDate' from weather;
+---------------------------------------------------------------------------------+
¦ ("json" -> 'city' -> 'climate' -> 'climateMonth' ->> 0) -> 'climateFromMemDate' ¦
¦                                      json                                       ¦
+---------------------------------------------------------------------------------¦
¦ "2014-01-06"                                                                    ¦
+---------------------------------------------------------------------------------+
D select json->'city'->'climate'->'climateMonth'->>0->'climateFromMemDate'::date from weather;
Error: Conversion Error: date field value out of range: "climateFromMemDate", expected format is (YYYY-MM-DD)
D select json->'city'->'climate'->'climateMonth'->>0->'maxTemp' from weather;
+----------------------------------------------------------------------+
¦ ("json" -> 'city' -> 'climate' -> 'climateMonth' ->> 0) -> 'maxTemp' ¦
¦                                 json                                 ¦
+----------------------------------------------------------------------¦
¦ "3.5"                                                                ¦
+----------------------------------------------------------------------+
D select json->'city'->'climate'->'climateMonth'->>0->'maxTemp'::float from weather;
Error: Conversion Error: Could not convert string 'maxTemp' to FLOAT
```

### OS:

Windows 10, x64

### DuckDB Version:

SQLite v0.7.1 b00b93f0b1 msvc-1934

### DuckDB Client:

CLI

### Full Name:

Raphaël Goubet

### Affiliation:

private

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rgoubet** [comment]
No, `'maxTemp'` is not a string literal as shown in the code:

```sql
D select json->'city'->'climate'->'climateMonth'->>0->'maxTemp' from weather;
┌──────────────────────────────────────────────────────────────────────┐
│ ("json" -> 'city' -> 'climate' -> 'climateMonth' ->> 0) -> 'maxTemp' │
│                                 json                                 │
├──────────────────────────────────────────────────────────────────────┤
│ "3.5"                                                                │
└──────────────────────────────────────────────────────────────────────┘
```

Hence the parentheses notation doesn't work either.

**Comment by Mytherin** [comment]
maxTemp is a string literal. String literals in SQL are constants surrounded with `'`, e.g.:

```sql
SELECT 'maxTemp';
┌───────────┐
│ 'maxTemp' │
│  varchar  │
├───────────┤
│ maxTemp   │
└───────────┘
```

The JSON access methods use string literals that contain the JSON access paths.

> If there was, this would have returned 3.5 instead of an empty string.

You can see in your example that the cast is only applied to the string literal `3.5` at the end of the expression, showing that it is an operator precedence issue:

```sql
("json" -> 'city' -> 'climate' -> 'climateMonth' ->> 0) -> 'maxTemp' -> CAST('3.5' AS FLOAT)
```

The empty string comes from trying to find the named entry `3.5` in the JSON which does not exist.

**Comment by rgoubet** [comment]
Maybe I misunderstood you. Did you mean to point out that the expression (`json->'city'->'climate'->'climateMonth'->>0->'maxTemp'`) is incorrectly parsed by duckdb, so that it assumes it should cast `'maxTemp'` instead of the expression's output? Then I defer to your expertise, but that would indeed make sense.

**Comment by Mytherin** [comment]
Whenever you have multiple operators without brackets, there is a question of operator precedence. Often this is done left-to-right, but certain operators take precedence to simplify writing expressions. The classic example from basic arithmetic is `*` and `+`, but all operators need to deal with this to some extend. Type casts have a very high precedence because that is usually what you want. For example:

```sql
SELECT 42/2::DOUBLE;
```

This is parsed as:

```sql
SELECT 42/(2::DOUBLE)
```

i.e. the cast is executed before the division.

Now applying this to your expression, this results in the following operator precedence (in this case less intuitive):

```sql
select json->'city'->'climate'->'climateMonth'->>0->('maxTemp'::float) from weather;
```

As you can see the constant `maxTemp` is cast to float, instead of the result of the left-hand expression. That is what results in the conversion error (as the string literal `maxTemp` can indeed not be cast to a float).

**Comment by rgoubet** [comment]
Yes, that's it! I had misunderstood the `->>` operator. Thanks!
