### ISSUE TITLE
Bug in explain analyze with semi joins

### ISSUE THREAD

**Issue by marsupialtail** [duckdb/duckdb#7308]
### What happens?

In semi joins, the explain analyze graph produced will include a condition like 
X is not distinct from X. 

However often times it should be X is not distinct from Y, i.e. the column names should be different coming from both sides of the join. For example if you look at TPC-DS query 10, the semi join almost certainly should say c_customer_sk is not distinct from ss_customer_sk. Instead, it says c_customer_sk is not distinct from c_customer_sk.

### To Reproduce

Run explain analyze on TPC-DS query 10, I did with Parquet files on disk but problem should persist with other file formats (Im guessing)

### OS:

Ubuntu

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Ziheng Wang

### Affiliation:

Stanford

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Oh interesting, is this what you're referring to? 

```
create or replace table x as select * from range(10) t(id1);
create or replace table y as select * from range(10) t(id2);
select * from x where exists (select * from y where x.id1 = y.id2)
```
![image](https://user-images.githubusercontent.com/104510378/235402287-506c5fdd-f5ab-4249-b62f-3aff93bbd493.png)

**Comment by l1t1** [comment]
the result is right though the plan shown is wrong.
```
D update y set id2=id2*2;
D select * from x where exists (select * from y where x.id1 =id2);
┌───────┐
│  id1  │
│ int64 │
├───────┤
│     0 │
│     2 │
│     4 │
│     6 │
│     8 │
└───────┘
```
