### ISSUE TITLE
Internal issue in join order optimizer with query with bad join pattern.

### ISSUE THREAD

**Issue by DanCory** [duckdb/duckdb#7314]
### What happens?

Run the query in the repro steps and get error:
Error: INTERNAL Error: Internal error in join order optimizer

Further queries will be blocked by:
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.

I made a mistake when creating this query and it is oddly structured. However, it should not invalidate the database.

### To Reproduce

Make sure the TPCDS extension is installed.
Create a TPCDS database with CALL dsdgen(sf=1);
Run the query:
select count(*)
FROM store_sales
,store_returns
,date_dim d1
,date_dim d2
,store
,customer
,customer_address ad1
,customer_address ad2
,item
WHERE  ss_store_sk = s_store_sk AND
ss_sold_date_sk = d1.d_date_sk AND
ss_customer_sk = c_customer_sk AND
ss_addr_sk = ad1.ca_address_sk and
ss_item_sk = 94922 and
ss_item_sk = sr_item_sk and
ss_ticket_number = sr_ticket_number and
c_current_addr_sk = ad2.ca_address_sk and
c_first_sales_date_sk = d2.d_date_sk  
;

### OS:

Windows amd64

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Dan Cory

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tmonster** [comment]
Thank you for the bug report! 

This is indeed a bug. Happens when we solve the join order approximately. We attempt to create a cross-product at one point and we don't initialise the statistics of the two disjoints sets appropriately. I will provide a fix for this next week

**Comment by Tmonster** [comment]
fixed in https://github.com/Tmonster/duckdb/pull/52

**Comment by Tmonster** [comment]
Sorry, fixed in https://github.com/duckdb/duckdb/pull/7438
