### ISSUE TITLE
LocalFileSystem::Glob can return non-existent files

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#7315]
### What happens?

A pattern like `root/*/*/schema.parquet` can return files that don't exist. 

### To Reproduce

Added to the test suite:

```sql
select id, value, part, date 
from parquet_scan('data/parquet-testing/hive-partitioning/missing/*/*/test.parquet', HIVE_PARTITIONING=1) 
order by id
```

### OS:

OSX

### DuckDB Version:

v0.7.2-dev2740

### DuckDB Client:

CLI

### Full Name:

Richard Wesley

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
The example is from the fix I'm about to submit.

**Comment by Mytherin** [comment]
Should be fixed now
