### ISSUE TITLE
JDBC ResultSet consumes unlimited memory

### ISSUE THREAD

**Issue by LeoWoerteler** [duckdb/duckdb#7327]
### What happens?

When processing a large CSV file (multiple GB, TPC-H Lineitem in this example) via JDBC, the `memory_limit` is obeyed during query execution but not while iterating over the result using the JDBC bindings. The memory consumption stays constant until the first output row is returned, and then skyrockets to approximately 2x the size of the result (again multiple GB). On Linux the whole Java process is killed by the OOM killer for sufficiently large results, Mac just swaps heavily.

```java
ResultSet rs = stmt.executeQuery("""
     SET memory_limit='512MB';
     SET temp_directory='./temp';
     SELECT * FROM 'lineitem-sf10.csv'
     ORDER BY l_orderkey DESC
""");
```
Memory consumption increases immediately before the first output line `0` is printed, the full result seems to be in memory at that point.
```java
while (rs.next()) {
    if (numRows % 1_000_000 == 0) {
        System.out.println(numRows);
    }
    numRows++;
}
```

### To Reproduce

See (very small) Gist: https://gist.github.com/LeoWoerteler/569ed4f3dc1c3570e7aaf17acbe4bb12

### OS:

Linux, Mac

### DuckDB Version:

0.8.0 nightly

### DuckDB Client:

JDBC

### Full Name:

Leonard Wörteler

### Affiliation:

KNIME

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by LeoWoerteler** [comment]
Using streaming for the JDBC result as proposed in #2459 seems to solve the problem by the way, memory consumption stays constant.

**Comment by Tishj** [comment]
I believe that is expected behavior, as the memory limit applies to the execution of the query.
When retrieving the result, and not using a streaming query result, the entire result has to be materialized.

**Comment by LeoWoerteler** [comment]
@Tishj I had to modify the source code to enable streaming, and I don't know all the side-effects this change has. Is there either a supported way to enable streaming execution via JDBC or alternatively some way for the materialized result to use the buffer pool so that large results are possible to work with?

**Comment by myselfmohdsameer** [comment]
I am facing exact same issue @LeoWoerteler, were you able to find out a fix for it?
cc @Mause

**Comment by LeoWoerteler** [comment]
@myselfmohdsameer No, we had to shelve the whole DuckDB integration for the time being. It's too much of a stability risk. If and when result streaming is supported, we can pick it back up (there's not much missing). We are very much still interested in this ticket.
