### ISSUE TITLE
DuckDB INTERNAL Error: Interleaved appends: this should no longer happen

### ISSUE THREAD

**Issue by fuboat** [duckdb/duckdb#7349]
### What happens?

The DuckDB binary (`/usr/local/bin/duckdb`) throws `INTERNAL Error: Interleaved appends: this should no longer happen`.

### To Reproduce

```sql
CREATE TABLE td(tz VARCHAR(30) NOT NULL);
CREATE UNIQUE INDEX sqlsim0 ON td(tz);
CREATE TABLE tab0(c2 DATE NOT NULL);
INSERT INTO td VALUES (date '2008-02-29');
START TRANSACTION;
INSERT INTO td VALUES('2006-12-25');
INSERT INTO tab0 VALUES('2006-12-25');
INSERT INTO td VALUES (date '2008-02-29');
COMMIT TRANSACTION;
```

### OS:

Ubuntu 20.04 64bit

### DuckDB Version:

v0.7.2-dev2867 aa20f17

### DuckDB Client:

Binary (/usr/local/bin/duckdb)

### Full Name:

Jingzhou Fu

### Affiliation:

Wingtecher Lab of Tsinghua University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
```sql
# Create the primary table
statement ok
CREATE TABLE td(tz VARCHAR(30) NOT NULL);

# Create the constraint we'll be violating
statement ok
CREATE UNIQUE INDEX sqlsim0 ON td(tz);

# Create second table to insert into before causing a constraint exception
statement ok
CREATE TABLE tab0(c2 DATE NOT NULL);

# Add the unique value
statement ok
INSERT INTO td VALUES (date '2008-02-29');

statement ok
START TRANSACTION;

# Valid insertion into primary table
statement ok
INSERT INTO td VALUES('2006-12-25');

# Valid insertion into secondary table
statement ok
INSERT INTO tab0 VALUES('2006-12-25');

# Constraint exception, that we won't be aware off until we commit
statement ok
INSERT INTO td VALUES (date '2008-02-29');

statement ok
COMMIT TRANSACTION;
```

**Comment by Tishj** [comment]
`total_rows` = 0, `start_row` = 0, `count` = 1
If I would have to guess, I'd say the append doesn't get made to the row group collection because of the constraint violation.

**Comment by taniabogatsch** [comment]
Yes, it might be related to that. But also, it only happens for any order in the transaction that interleaves the appends into the two different tables. If we append into one table first and then the other, it correctly throws the constraint violation... Will have a look.
