### ISSUE TITLE
(latest 270) Maven Snapshot does not exist

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#7390]
### What happens?

testImplementation 'org.duckdb:duckdb_jdbc:0.8.0-SNAPSHOT'

Could not find duckdb_jdbc-0.8.0-SNAPSHOT.jar (org.duckdb:duckdb_jdbc:0.8.0-SNAPSHOT:20230506.051624-270).
Searched in the following locations:
    https://oss.sonatype.org/content/groups/public/org/duckdb/duckdb_jdbc/0.8.0-SNAPSHOT/duckdb_jdbc-0.8.0-20230506.051624-270.jar

### To Reproduce

270 is missing.
268 is there.

https://oss.sonatype.org/content/groups/public/org/duckdb/duckdb_jdbc/0.8.0-SNAPSHOT/ shows

duckdb_jdbc-0.8.0-20230506.051608-268.jar | Sat May 06 05:16:13 UTC 2023 | 57937876 |  
-- | -- | -- | --
duckdb_jdbc-0.8.0-20230506.051608-268.jar.md5 | Sat May 06 05:16:15 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-20230506.051608-268.jar.sha1 | Sat May 06 05:16:15 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-20230506.051608-268.pom | Sat May 06 05:16:15 UTC 2023 | 1774 |  
duckdb_jdbc-0.8.0-20230506.051608-268.pom.md5 | Sat May 06 05:16:16 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-20230506.051608-268.pom.sha1 | Sat May 06 05:16:16 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-20230506.051618-269-sources.jar | Sat May 06 05:16:20 UTC 2023 | 28632 |  
duckdb_jdbc-0.8.0-20230506.051618-269-sources.jar.md5 | Sat May 06 05:16:20 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-20230506.051618-269-sources.jar.sha1 | Sat May 06 05:16:20 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-20230506.051618-269.pom | Sat May 06 05:16:20 UTC 2023 | 1774 |  
duckdb_jdbc-0.8.0-20230506.051618-269.pom.md5 | Sat May 06 05:16:21 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-20230506.051618-269.pom.sha1 | Sat May 06 05:16:21 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-20230506.051624-270-javadoc.jar | Sat May 06 05:16:25 UTC 2023 | 386253 |  
duckdb_jdbc-0.8.0-20230506.051624-270-javadoc.jar.md5 | Sat May 06 05:16:26 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-20230506.051624-270-javadoc.jar.sha1 | Sat May 06 05:16:25 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-20230506.051624-270.pom | Sat May 06 05:16:26 UTC 2023 | 1774 |  
duckdb_jdbc-0.8.0-20230506.051624-270.pom.md5 | Sat May 06 05:16:26 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-20230506.051624-270.pom.sha1 | Sat May 06 05:16:26 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-SNAPSHOT-javadoc.jar.asc | Sat May 06 05:16:27 UTC 2023 | 228 |  
duckdb_jdbc-0.8.0-SNAPSHOT-javadoc.jar.asc.md5 | Sat May 06 05:16:27 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-SNAPSHOT-javadoc.jar.asc.sha1 | Sat May 06 05:16:27 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-SNAPSHOT-sources.jar.asc | Sat May 06 05:16:22 UTC 2023 | 228 |  
duckdb_jdbc-0.8.0-SNAPSHOT-sources.jar.asc.md5 | Sat May 06 05:16:22 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-SNAPSHOT-sources.jar.asc.sha1 | Sat May 06 05:16:22 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-SNAPSHOT.jar.asc | Sat May 06 05:16:17 UTC 2023 | 228 |  
duckdb_jdbc-0.8.0-SNAPSHOT.jar.asc.md5 | Sat May 06 05:16:17 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-SNAPSHOT.jar.asc.sha1 | Sat May 06 05:16:17 UTC 2023 | 40 |  
duckdb_jdbc-0.8.0-SNAPSHOT.pom.asc | Sat May 06 05:16:27 UTC 2023 | 228 |  
duckdb_jdbc-0.8.0-SNAPSHOT.pom.asc.md5 | Sat May 06 05:16:28 UTC 2023 | 32 |  
duckdb_jdbc-0.8.0-SNAPSHOT.pom.asc.sha1 | Sat May 06 05:16:27 UTC 2023 | 40 |  
maven-metadata.xml | Sat May 06 05:16:26 UTC 2023 | 1209 |  
maven-metadata.xml.md5 | Sat May 06 15:25:34 UTC 2023 | 33 |  
maven-metadata.xml.sha1 | Sat May 06 15:25:34 UTC 2023 | 41 |  
maven-metadata.xml.sha256 | Sat May 06 15:25:34 UTC 2023 | 65 |  
maven-metadata.xml.sha512 | Sat May 06 15:25:34 UTC 2023 | 129 |  

### OS:

Linux archlinux 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux

### DuckDB Version:

0.8.0-SNAPSHOT

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects Co. Ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Is there a reason you need this exact snapshot? Those are provided more for convenience in testing latest features than to actually depend upon...

**Comment by manticore-projects** [comment]
Greetings!

No, not at all!
However, when testing performance then of course I always want to try the latest Snapshot and the latest Release.

Now, in Java/Gradle you can depend on the "Latest Snapshot" easily with something like
```gradle
testImplementation 'org.duckdb:duckdb_jdbc:+'
```

It will always pull the latest Snapshot and this did not work since 270 and 269 were missing and only 268 were there.
So I wondered, if there is an issue with the deployment and wanted to point this out.
