### ISSUE TITLE
LEFT JOIN UNNEST() requires an ON clause

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#7391]
### What happens?

Sometimes you want to UNNEST with a LEFT JOIN.  Currently you have to provide an ON clause in order to do this.  I have a hacky workaround that I would like to remove.

### To Reproduce

```
with t as (
  select 
    1 as r, 
    [
      {n:1},
      {n:2}
    ] as s
  union   select 
    2 as r, 
    [
      {n:3},
      {n:4}
    ] as s
     
)
select r, s1.s.n from t
LEFT JOIN UNNEST(s) as s1(s)
```

### OS:

linux

### DuckDB Version:

current

### DuckDB Client:

web shell

### Full Name:

lloyd tabb

### Affiliation:

google

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lloydtabb** [comment]
Here are the basic permutation I think are interesting.  Assume a table with two columns, a scalar and an array.

```
with t as (
  SELECT 1 as r, ARRAY[1,2,3] as a
  UNION SELECT 2 as r, ARRAY[4] as a
  UNION SELECT 3 as r, NULL as a
)
SELECT r, a.value
FROM t 
, UNNEST(a) as a(value)
```
Returns no results.  UNNEST(NULL) basically eats everything.  Maybe this is should be an error.  (I think it is in BigQuery).

The Query below is  an inner join and eliminates row where r=4.
```
with t as (
  SELECT 1 as r, ARRAY[1,2,3] as a
  UNION SELECT 2 as r, ARRAY[4] as a
  UNION SELECT 4 as r, [] as a
)
SELECT r, a.value
FROM t 
, UNNEST(a) as a(value)
```

```
{"r":1,"value":3}
{"r":2,"value":4}
{"r":1,"value":2}
{"r":1,"value":1}
```

We get an error without an ON clause but the behaviour is a left join (the r=4 is retained) 
```
with t as (
  SELECT 1 as r, ARRAY[1,2,3] as a
  UNION SELECT 2 as r, ARRAY[4] as a
  UNION SELECT 4 as r, [] as a
)
SELECT r, a.value
FROM t 
LEFT JOIN UNNEST(a) as a(value) 
   ON a.value is NULL or a.value IS NOT NULL
```

r | value
-- | --
2 | 4
1 | 3
1 | 2
1 | 1
4 | NULL

**Comment by taniabogatsch** [comment]
https://github.com/duckdb/duckdb/pull/7821 adds support for `ON TRUE` in left outer joins.

I am currently also fixing the `UNNEST(NULL)` example because this is a bug. Will have a PR open soon, so that we get this into the next bug fix release.
```sql
# this should return four rows
with t as (
  SELECT 1 as r, ARRAY[1,2,3] as a
  UNION SELECT 2 as r, ARRAY[4] as a
  UNION SELECT 3 as r, NULL as a
)
SELECT r, a.value
FROM t 
, UNNEST(a) as a(value)
----
1	1
1	2
1	3
2	4
```
