### ISSUE TITLE
Loading a large Parquet File via JDBC exhausts memory (unless explicitly limited)

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#7394]
### What happens?

Loading a very large Parquet File into a file backed DB
```java
conn = DriverManager.getConnection("jdbc:duckdb:test.duckdb");
conn.execute("INSERT INTO targetTable SELECT * FROM read_parquet(\"parquetFile.parquet\");");

```

will result in memory exception when the parquet file is large enough.

Unless you define `memory_limit` explicitly:
```java

conn.execute("SET memory_limit='2GB'; INSERT INTO targetTable SELECT * FROM read_parquet(\"parquetFile.parquet\");");
```

I don't think this should happen or that I should care about that memory limit. (I am programming on Java after all and avoid C for a reason :-P )

### To Reproduce

Load a large Parquet File (10GB plus) on a 4GB memory computer:

```java
conn = DriverManager.getConnection("jdbc:duckdb:test.duckdb");
conn.execute("INSERT INTO targetTable SELECT * FROM read_parquet(\"parquetFile.parquet\");");
```

### OS:

Linux archlinux 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux

### DuckDB Version:

0.7.1 b00b93f0b1

### DuckDB Client:

JDBC

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects Co. Ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by arjenpdevries** [comment]
Programming in java cannot shield you from all detail, and in this case you answered your question already: on a 4G machine you should put a memory limit below that (and your jvm and operating system) if you want to avoid using more memory than available (by loading a 10G dataset). You may even need to consider the number of cores you will use when you run your program to determine the memory capacity for DuckDB.

Of course, you can also opt to use a database or library that is safely agnostic to these core system characteristics; but then you'll pay in terms of higher execution times to complete your jobs.

DuckDB will need a little help, but in return gives you better runtime performance, completing your tasks in as large batches at a time as possible.

**Comment by manticore-projects** [comment]
Thank you for replying @arjenpdevries.

So does that means, the `DuckDB` does not care about any memory constraints of the system and just assumes there was endless memory available -- until I tell DuckDB, that there was a limit?

I am actually very ok with that approach, but it should be documented somewhere, e. g. "DuckDB expects you to set a Memory Limit and will not detect the available memory by itself."

I would have expected that at least when file-backed, DuckDb would constrain itself to the available free memory (like a JVM). To me it looked like an issue, while it actually is a feature.
