### ISSUE TITLE
`INSERT INTO ... ON CONFLICT` doesn't work within transaction block.

### ISSUE THREAD

**Issue by RaczeQ** [duckdb/duckdb#7396]
### What happens?

After opening a transaction block and adding rows one by one, an error appears whenever `ON CONFLICT` clause is triggered.

### To Reproduce

Running this set of commands in CLI:
```SQL
BEGIN TRANSACTION;

CREATE TABLE tbl (a SHORT PRIMARY KEY, b SHORT);

INSERT INTO tbl VALUES (1, 2) ON CONFLICT (a) DO UPDATE SET b = excluded.b;
INSERT INTO tbl VALUES (1, 3) ON CONFLICT (a) DO UPDATE SET b = excluded.b;

COMMIT;
```

or Python:
```python
import duckdb

cursor = duckdb.connect()
cursor.execute("""
BEGIN TRANSACTION;

CREATE TABLE tbl (a SHORT PRIMARY KEY, b SHORT);

INSERT INTO tbl VALUES (1, 2) ON CONFLICT (a) DO UPDATE SET b = excluded.b;
INSERT INTO tbl VALUES (1, 3) ON CONFLICT (a) DO UPDATE SET b = excluded.b;

COMMIT;
""")
```

Result:
```log
---------------------------------------------------------------------------
ConstraintException                       Traceback (most recent call last)
/mnt/c/Development/Python/Jupyter/test_osm_duckdb/duckdb.ipynb Cell 2 in 4
      1 import duckdb
      3 cursor = duckdb.connect()
----> 4 cursor.execute("""
      5 BEGIN TRANSACTION;
      6 
      7 CREATE TABLE tbl (a SHORT PRIMARY KEY, b SHORT);
      8 
      9 INSERT INTO tbl VALUES (1, 2) ON CONFLICT (a) DO UPDATE SET b = excluded.b;
     10 INSERT INTO tbl VALUES (1, 3) ON CONFLICT (a) DO UPDATE SET b = excluded.b;
     11 
     12 COMMIT;
     13 """)

ConstraintException: Constraint Error: PRIMARY KEY or UNIQUE constraint violated: duplicate key "1"
```

### OS:

WSL2, Ubuntu 20.04, x64

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Kamil Raczycki

### Affiliation:

Open Source Python Contributor

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising this issue, this is something that I completely forgot when implementing the functionality.

The issue here is that we create a transaction-local ART for the primary key Index, currently in the "on conflict do update .. | do nothing" handling code we only check the global ART, which does not detect a conflict yet.

Then, because the conflicting tuple(s) are not filtered out, the constraint check done for the insert into the storage causes the exception you're seeing.
