### ISSUE TITLE
Binder Error with LIST(): column "xy" must appear in the GROUP BY clause or must be part of an aggregate function.

### ISSUE THREAD

**Issue by Rainer-Kempkes** [duckdb/duckdb#7408]
### What happens?

list() is declared as an aggregate function, so I would expect the SQL:

    select groupID, list(xy) over(partition by groupID order by rank desc) listitems
    from table
    group by groupID;

to work properly. But it does not. Error:
duckdb.BinderException: Binder Error: column "xy" must appear in the GROUP BY clause or must be part of an aggregate function. Either add it to the GROUP BY list, or use "ANY_VALUE(hi)" if the exact value of "xy" is not important.

### To Reproduce

select Name, list(Id) over (partition by Name order by Id asc) rankedIdList
from (VALUES ('A', 1), ('A', 2), ('A',3), ('B',1),('B', 2)) Cities(Name, Id)
group by 1

### OS:

Linux Mint

### DuckDB Version:

0.7.2.dev3154

### DuckDB Client:

Python 3.10

### Full Name:

Rainer Kempkes

### Affiliation:

Haufe

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

I understand the confusion - but the system is correct here. `LIST` is not used as an aggregate function here but as a window function because of the `OVER` clause. Window functions have different semantics than aggregate functions as they can be used alongside regular `SELECT` elements.

Rewriting the query and running it in Postgres results in exactly the same error:

```sql
postgres=# create table tbl(groupId int, xy int, rank int);
CREATE TABLE
postgres=# select groupID, array_agg(xy) over(partition by groupID order by rank desc) listitems from tbl group by groupID;
ERROR:  column "tbl.xy" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select groupID, array_agg(xy) over(partition by groupID orde...

```

**Comment by Rainer-Kempkes** [comment]
ok, perhaps the confusion originated in the fact that the list function is listed in the aggregations tab https://duckdb.org/docs/archive/0.4.0/sql/aggregates and not in the window functions tab https://duckdb.org/docs/archive/0.4.0/sql/window_functions

**Comment by Rainer-Kempkes** [comment]
how would I retrieve the desired result (from above reproduce-SQL):
   A, [1,2,3]
   B, [1,2]
   without group by I get:
   A,1
   A,1,2
   A,1,2,3
   ...
   Not I have to do an additional subselect where I create a tmp-table with A and max(Id) to select the lines with the most list entries per group

**Comment by Mytherin** [comment]
> ok, perhaps the confusion originated in the fact that the list function is listed in the aggregations tab https://duckdb.org/docs/archive/0.4.0/sql/aggregates and not in the window functions tab https://duckdb.org/docs/archive/0.4.0/sql/window_functions

[All aggregate functions are also valid window functions](https://duckdb.org/docs/archive/0.4.0/sql/window_functions#aggregate-window-functions). List is an aggregate function, but a window function when used with the `OVER` clause.

**Comment by Rainer-Kempkes** [comment]
Thank you, @Alex-Monahan, you made my day!
