### ISSUE TITLE
Implement more crypto functions

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#7412]
Currently DuckDB implements only the `md5` function - we should implement more crypto functions such as those found in [pgcrypto](https://www.postgresql.org/docs/current/pgcrypto.html) or [presto](https://prestodb.io/docs/current/functions/binary.html). These functions could either use mbedtls and live in core DuckDB, or be implemented as part of e.g. the `httpfs` extension (as that links to OpenSSL).

- [ ] sha1
- [ ] sha256
- [ ] sha512

**Comment by YiKaiLiao** [comment]
Hi, I'm excited to contribute to DuckDB for the first time, and I'd like to start by implementing the sha-1 function. 
Before starting, I wanted to check if anyone else is already working on this. 
Looking forward to your feedback and suggestions!

**Comment by jmcastagnetto** [comment]
FYI, I was testing duckdb (v0.7.1 b00b93f0b1) under Win10 (not my usual OS), and found that there seems to be an implementation of `sha3()`

```
D select distinct on(function_name) function_name, function_type, return_type, parameters, parameter_types, function_oid from duckdb_functions() where function_name like 'sha%' limit 10;
┌───────────────┬───────────────┬─────────────┬──────────────┬─────────────────┬──────────────┐
│ function_name │ function_type │ return_type │  parameters  │ parameter_types │ function_oid │
│    varchar    │    varchar    │   varchar   │  varchar[]   │    varchar[]    │    int64     │
├───────────────┼───────────────┼─────────────┼──────────────┼─────────────────┼──────────────┤
│ sha3_query    │ scalar        │ VARCHAR     │ [col0, col1] │ [ANY, ANY]      │         1335 │
│ sha3          │ scalar        │ VARCHAR     │ [col0, col1] │ [ANY, ANY]      │         1331 │
└───────────────┴───────────────┴─────────────┴──────────────┴─────────────────┴──────────────┘
```

Did not find documentation, and when trying to use it, it just dumps duckdb to the prompt:

```
PS C:\Users\jesus\Documents\duckdb> .\duckdb.exe
D select sha3('abcdef', 256);
PS C:\Users\xyz\Documents\duckdb>
```

**Comment by Mytherin** [comment]
Thanks for the report - indeed it appears that the SQLite shell ships its own `sha3` function as a SQLite UDF which our wrapper does not seem to handle correctly. I have stripped it out in #7511 for now.

**Comment by Reminiscent** [comment]
I want to try the`sha256`.

**Comment by rickif** [comment]
https://github.com/duckdb/duckdb/pull/7592
PTAL. @Mytherin

**Comment by jdnvn** [comment]
could I take a crack at the sha256 function? I see @rickif 's open PR for 512, wondering if it would be wise to branch off of his feature branch?

**Comment by jdnvn** [comment]
@Mytherin sha256 function is ready for a review! https://github.com/duckdb/duckdb/pull/8723

**Comment by euiko** [comment]
Hi @Mytherin, I've made PR for implementing `sha512`, seems the last PR is closed due to inactivity so I opened a new one. Following suggestion to use class based segmented API in #8636 mentioned in previous PR.

**Comment by jmcastagnetto** [comment]
Commenting to keep this issue fresh

**Comment by MacOS** [comment]
I would be interested to contribute, however what would be the time window within which I have to make a PR?

**Comment by scoobhidu** [comment]
Hi everyone,
I am thinking of implementing the AES encryption but what should be the preferred approach according to you all? Should we allow the user to create a table value for storing table-wide AES encryption key or should we store column specific value for column exclusive encryption/decryption?

**Comment by jmcastagnetto** [comment]
> Hi everyone, I am thinking of implementing the AES encryption but what should be the preferred approach according to you all? Should we allow the user to create a table value for storing table-wide AES encryption key or should we store column specific value for column exclusive encryption/decryption?

IIRC the main issue was to create functions that implement crypto algos, and what you mention is a use case for those functions. Perhaps what you are asking about how to store the key, can be handled by the existing functionality of "CREATE SECRET"(https://duckdb.org/docs/sql/statements/create_secret) 

Just my 0.02 monetary units :-)

**Comment by carlopi** [comment]
`sha1` AND `sha256` have been implemented and are available (unsure for how long it has been the case, for sure in 1.1.0+)
See:
```sql
SELECT sha1('quack'), sha256('quack');
```
```
┌──────────────────────────────────────────┬──────────────────────────────────────────────────────────────────┐
│              sha1('quack')               │                         sha256('quack')                          │
│                 varchar                  │                             varchar                              │
├──────────────────────────────────────────┼──────────────────────────────────────────────────────────────────┤
│ a524ca3d36aafe68e5be51f10f00ff0dae1186ce │ 82d928273d067d774889d5df4249aaf73c0b04c64f04d6ed001441ce87a0853c │
└──────────────────────────────────────────┴──────────────────────────────────────────────────────────────────┘

```

Infrastructure is there and it's fairly easy to add `sha512`, either in core or as an extension.
