### ISSUE TITLE
RAM filling up when querying `read_parquet('*.parquet')`, but query should return small amount of data

### ISSUE THREAD

**Issue by ljmartin** [duckdb/duckdb#7415]
### What happens?

Hi all, 
I'm querying a data base, with 5.5 billion rows, which is spread across several thousand chunks and stored in `.parquet` files. Performing a query that returns a fraction of the data - 280 million rows - fills up the available 185gb RAM. I happen to know that the output of this query is <5GB (compressed in parquet), so this leads me to believe the whole database, including both rows and columns that should be filtered out, is being loaded in RAM before saving the queried data. 

The actual behaviour is: 
```
$ duckdb < queryScript.sql
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows  │
└─────────┘
  7% ▕████▏                                                       ▏ Error: near line 11: Out of Memory Error: could not allocate block of 262144 bytes (158647785472/158647989043 used)
Database is launched in in-memory mode and no temporary directory is specified.
Unused blocks cannot be offloaded to disk.

Launch the database with a persistent storage back-end
Or set PRAGMA temp_directory='/path/to/tmp.tmp'
```

What have I tried? 
- using a disk .db file: running `duckdb output.db < queryScript.sql` instead leads to a very large `.tmp` folder being created. I think this folder contains nearly the entire database (~600GB), since it grows to hundreds of GBs in size before the RAM also runs out and the query ends. That behaviour looks like https://github.com/duckdb/duckdb/issues/6893, but the conversation for that topic went elsewhere. 
- lowering nthreads with e.g. `SET threads TO 10`; - I thought just the transient opening of 96 parquet files (96 CPUs) could overload the memory, but no - the RAM still blows up no matter how many CPUs are running at one time

### To Reproduce

The source parquets contain a column of lists of tokens, to which I'm applying logistic regression and then filtering out low-probability instances. I can perform this query with a python script (using pandas and sklearn - not duckdb) in parallel and the size of the output data is 5GB - much smaller than the observed occupied RAM. 

The LogReg algorithm makes the query look complicated, but it boils down to this: requesting three columns of data, where one of those columns is calculated on the fly and is also used as a filter, on the fly, to filter out low-probability instances (`proba>0.05`). 

`queryScript.sql` is:
```
PRAGMA enable_progress_bar;

-- Load up a single-row file containing the LogReg coefficients, as a list, and intercept, as a float:
DROP TABLE IF EXISTS logreg;
CREATE TABLE logreg(coefs DOUBLE[], intercept DOUBLE);
INSERT INTO logreg SELECT * from read_parquet('./myTrainedModel.parquet');

--This table 'filtered_results' will store only the higher-probability instances 
DROP TABLE IF EXISTS filtered_results;
CREATE TABLE filtered_results(idnumber VARCHAR, actualDataStrings VARCHAR, proba FLOAT);

insert into filtered_results
   select idnumber, actualDataStrings, 1/(1+ pow(2.71828, -list_aggregate([coefs[i+1] for i in tokens], 'sum') - intercept)) as proba from logreg, read_parquet('*.parquet') where proba>0.05;
```

### OS:

AWS, 20.04.1-Ubuntu x86_64

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Lewis Martin

### Affiliation:

OpenBench - chemistry discovery 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! Could you run an `EXPLAIN` on the `INSERT INTO` statement so we can see the query plan?

**Comment by Mytherin** [comment]
Also have you already tried running this with the latest master/pre-release?

**Comment by ljmartin** [comment]
thanks for engaging @Mytherin. I am using the latest master version: `v0.7.2-dev2740 bb37f3fd06`. 

Here's the output of `EXPLAIN`, using `SET explain_output='all'; `. Note the column names changed - I simplified them in the original question be self-explanatory, but they are:
- `actualDataStrings`: `smiles` (a chemistry code, varchar)
- `tokens`: `fpBit` (result from a chemistry tokenizer, `INT[]`) 
 
```

┌─────────────────────────────┐
│┌───────────────────────────┐│
││ Unoptimized Logical Plan  ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           INSERT          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          idnumber         │
│           smiles          │
│           proba           │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│((CAST(1 AS DOUBLE) / (CAST│
│ (1 AS DOUBLE) + pow(CAST(2│
│   .71828 AS DOUBLE), (-   │
│(list_aggregate(list_a...  │
│    coefs, 1), 'sum')) -   │
│ intercept)))) > CAST(...  │
│          DOUBLE))         │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│       CROSS_PRODUCT       ├──────────────┐
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││        PARQUET_SCAN       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││                           │
│           logreg          ││                           │
└───────────────────────────┘└───────────────────────────┘

┌─────────────────────────────┐
│┌───────────────────────────┐│
││  Optimized Logical Plan   ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           INSERT          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          idnumber         │
│           smiles          │
│           proba           │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│          ANY_JOIN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│((1.0 / (1.0 + pow(2.71828,│
│      (-(list_aggregate    ├──────────────┐
│(list_apply(fpBit, coe...  │              │
│ ) - intercept)))) > 0.05) │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││        PARQUET_SCAN       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││                           │
│           logreg          ││                           │
└───────────────────────────┘└───────────────────────────┘

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│        BATCH_INSERT       │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          idnumber         │
│           smiles          │
│           proba           │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│     BLOCKWISE_NL_JOIN     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           INNER           │
│((1.0 / (1.0 + pow(2.71828,├──────────────┐
│      (-(list_aggregate    │              │
│(list_apply(fpBit, coe...  │              │
│ ) - intercept)))) > 0.05) │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│         SEQ_SCAN          ││       PARQUET_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           logreg          ││           fpBit           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││          idnumber         │
│           coefs           ││           smiles          │
│         intercept         ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││           EC: 0           │
│           EC: 0           ││                           │
└───────────────────────────┘└───────────────────────────┘
```

**Comment by Mytherin** [comment]
Thanks, that is very helpful. This issue seems to be related to the optimizer - in particular no cardinality estimates appear to be available. Because no statistics are available the system doesn't know which side is larger - and incorrectly places the `filtered_results` on the right-hand side of the generated join, causing it to be fully materialized (instead of the single row table).

The query will likely complete if you either enable the metadata cache, or disable the optimizer (`PRAGMA enable_optimizer=false`) and re-arrange the tables in the query so `logreg` is the second table.

I can reproduce the issue as follows:

```sql
CALL dbgen(sf=1);
COPY lineitem TO 'lineitem.parquet';
COPY (SELECT 42) TO 'singlerow.parquet';
explain analyze FROM 'singlerow.parquet','lineitem.parquet';
explain analyze FROM 'lineitem.parquet','singlerow.parquet';
```

@Tmonster could you have a look at this?

**Comment by Tmonster** [comment]
Will take a look. I was working on a similar issue today (https://github.com/duckdb/duckdb/issues/7273) where blockwise NL joins don't swap children at all even if statistics are available. I believe the two are very closely related

**Comment by ljmartin** [comment]
Thank you so much - the query does indeed complete (without filling up RAM) if I swap the order of the tables. 

This solves my immediate problem, so feel free to close this unless you're still tracking an issue.  

For reference, the query that worked: 
```
DROP TABLE IF EXISTS logreg;
CREATE TABLE logreg(coefs DOUBLE[], intercept DOUBLE);
INSERT INTO logreg SELECT * from read_parquet('./supa_ring-acceptors.parquet');

--This table 'filtered_results' will store only the higher-probability instances
DROP TABLE IF EXISTS filtered_results;
CREATE TABLE filtered_results(idnumber VARCHAR, smiles VARCHAR, proba FLOAT);

insert into filtered_results
   select idnumber, smiles, 1/(1+ pow(2.71828, -list_aggregate([coefs[i+1] for i in fpBit], 'sum') - intercept)) as proba from read_parquet('/home/ubuntu/enamine_2022q1-2/chunks_pyarrow/*.parquet'), logreg where proba>0.05;
```

**Comment by Mytherin** [comment]
Thanks - I will keep this open as I think this is something we can/should fix
