### ISSUE TITLE
Can not use collate in Over clause

### ISSUE THREAD

**Issue by jingmhua** [duckdb/duckdb#7418]
### What happens?

Can not get the correct row number in over clause

### To Reproduce

Steps:
1,  Create table test(name text)
2,  insert into test values('华中'),('华东'),('华北'),('华南')
3,  select name, ROW_NUMBER() over(order by name COLLATE zh) from test

Actual:
![image](https://user-images.githubusercontent.com/48235764/237043350-d97f9874-ba9f-4b42-b4e5-2ea6319285fd.png)

Expected:
![image](https://user-images.githubusercontent.com/48235764/237043845-a7a6e081-db74-4f38-9d2c-55d58d004219.png)

### OS:

windows 10

### DuckDB Version:

0.7.1

### DuckDB Client:

case1: dbeaver 22.3.5, dirver: duckdb_jdbc-0.7.1.jar   case2: duckdb.exe v0.7.1 b00b93f0b1

### Full Name:

William Jing

### Affiliation:

other

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Should be fixed now
