### ISSUE TITLE
on conflict / do nothing with pandas DataFrame raises TransactionException

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#7434]
### What happens?

When I try to `insert` / `on conflict` / `do nothing`
on a table created with [`AUTO-DETECT`](https://duckdb.org/docs/sql/statements/create_table#examples)
with a subsequent`create unique index` I get:
```
TransactionContext Error: Failed to commit: Constraint Error: PRIMARY KEY or UNIQUE constraint violated: duplicate key
```

Even though I specified `do nothing`.

---

Note: I want the `do nothing` semantics so I don't have duplicate rows,
and I'm only doing the `create unique index` because otherwise I get:
```
The specified columns as conflict target are not referenced by a UNIQUE/PRIMARY KEY CONSTRAINT
```

### To Reproduce

```py
import pandas as pd
import duckdb

d = {'x': [1, 2], 'y': [3, 4]}
df = pd.DataFrame(data=d)

con = duckdb.connect()
con.sql('create table df as select * from df')
con.sql('create unique index df_x ON df (x)')

con.sql('insert into df select * from df on conflict (x) do nothing')
```

https://replit.com/@davetapley/duckdb-pandas-conflict#main.py

### OS:

Linux

### DuckDB Version:

0.7.2.dev3353

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
This should be covered by https://github.com/duckdb/duckdb/pull/7407
Or more specifically #7050 which this includes.
