### ISSUE TITLE
Compilation error on latest sources

### ISSUE THREAD

**Issue by PedroTadim** [duckdb/duckdb#7439]
### What happens?

Hello again everyone! Just a compilation error from gcc 11.3.0 from the latest sources I got in the json extension:

```
In file included from compile/extension/json/json_functions/ub_duckdb_json_functions.cpp:10:
src/extension/json/json_functions/json_create.cpp: In member function ‘virtual duckdb::unique_ptr<duckdb::BoundCastData> duckdb::NestedToJSONCastData::Copy() const’:
src/extension/json/json_functions/json_create.cpp:642:24: error: could not convert ‘result’ from ‘unique_ptr<duckdb::NestedToJSONCastData,default_delete<duckdb::NestedToJSONCastData>>’ to ‘unique_ptr<duckdb::BoundCastData,default_delete<duckdb::BoundCastData>>’
  642 |                 return result;
      |                        ^~~~~~
      |                        |
      |                        unique_ptr<duckdb::NestedToJSONCastData,default_delete<duckdb::NestedToJSONCastData>>
```

### To Reproduce

Compile the json extension (-DBUILD_JSON_EXTENSION=ON) with gcc 11.3.0 on debug build type.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

None

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Maybe missing an include?
Or needs explicit `unique_ptr_cast<.., ..>` applied

**Comment by Mytherin** [comment]
Thanks for the report! Looks like a missing `std::move` to me. We should probably enable building the various extensions on older versions of GCC to catch this in the CI.

**Comment by carlopi** [comment]
Somehow reassuring: it was eventually picked up by nightly build here: https://github.com/duckdb/duckdb/actions/runs/4943246017/jobs/8837534755#step:9:2129
