### ISSUE TITLE
read_json JSON transform error (related to sampling?)

### ISSUE THREAD

**Issue by liquidcarbon** [duckdb/duckdb#7448]
### What happens?

I have a large, nested JSON where one of the fields is mostly `null`, except for a handful of lines.

```
cat metadata.json_part2 | grep ResultFlags | sort | uniq -c

      1             "ResultFlags": "MicrofluidicsRegulatedVacuumError",
      7             "ResultFlags": "PressureError",
     18             "ResultFlags": "TemperatureError",
  47973             "ResultFlags": null,
```

An error is thrown when the duckdb parser encounters this field.  I can bypass it using `ignore_errors=1` but then I don't know what else could be wrong.

Would you consider this appropriate behavior or a bug?
Why does it say in the error message that it's trying to cast to numerical?

```
SELECT
...
FROM read_json_auto('metadata.json_part2', ignore_errors=0)
```

```
InvalidInputException                     Traceback (most recent call last)
File <timed exec>:7

InvalidInputException: Invalid Input Error: JSON transform error in file "E:/output\metadata.json_part2", in object 2286: Failed to cast value to numerical: "MicrofluidicsRegulatedVacuumError"
Try increasing 'sample_size', reducing 'maximum_depth', specifying 'columns' manually, specifying 'lines' or 'json_format' manually, or setting 'ignore_errors' to true.
```

### To Reproduce

It doesn't reproduce with a small file:
```
{"Results": {"ResultFlags": null}}
{"Results": {"ResultFlags": "notnull"}}
{"Results": {"ResultFlags": null}}
```

```
SELECT Results.ResultFlags
FROM read_json_auto('test_null_then_filled.json', ignore_errors=0)
```
returns expected result.

So I'm not sure how to proceed here.

### OS:

Windows (pyenv-win) and Ubuntu (WSL, pyenv)

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Alex Kislukhin

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by liquidcarbon** [comment]
Thanks for the suggestion!  Indeed, `sample_size=2285` gave an error, `sample_size=2286` did not! (rather, gave a different one far down the file).

As I don't always know how large my files might be, what's appropriate `sample_size`?  If it's 1 million, will there be a performance hit?

**Comment by uwegeercken** [comment]
What you can also do:
- Define a part of the json structure as  type "JSON" in which case you can parse the relevant field on-read
- Define just part of the schema, in which case duckdb will ignore the rest
- you can also try to use json_group_structure to find the structure over multiple fields. the duckdb blog shows how: https://duckdb.org/2023/03/03/json.html

**Comment by Alex-Monahan** [comment]
The larger your sample size, the more of your data that you will need to read twice. So there is a performance hit, likely around 2x if you sample the entire dataset.

**Comment by lnkuiper** [comment]
We now resort to the `JSON` type when we encounter only `NULL`: #7478
