### ISSUE TITLE
`COALESCE()` with two enums

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#7451]
### What happens?

Should `COALESCE()` with two enums create a composite enum with the distinct union of all values in the original enums?

In the example below, the desired output would be a column with an enum type with "a" and "b".

Follow-up to #6356.

### To Reproduce

``` r
con <- DBI::dbConnect(duckdb::duckdb())
invisible(DBI::dbExecute(con, "CREATE MACRO \"___coalesce\"(a, b) AS COALESCE(a, b)"))
df1 <- tibble::tibble(a = factor("a"), b = factor("b"))

rel1 <- duckdb:::rel_from_df(con, df1)
rel2 <- duckdb:::rel_project(
  rel1,
  list(
    duckdb:::expr_reference("a"),
    duckdb:::expr_reference("b"),
    duckdb:::expr_function(
      "___coalesce",
      list(duckdb:::expr_reference("a"), duckdb:::expr_reference("b"))
    )
  )
)
rel2
#> DuckDB Relation: 
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Projection [a as a, b as b, ___coalesce(a, b) as ___coalesce(a, b)]
#>   r_dataframe_scan(0x121211fc8)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - a (a)
#> - b (b)
#> - ___coalesce(a, b) (VARCHAR)
duckdb:::rel_to_altrep(rel2)
#>   a b ___coalesce(a, b)
#> 1 a b                 a
```

<sup>Created on 2023-05-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

6f543cb464d94c7b6adbc40d49e9209678a92515

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tmonster** [comment]
If I'm not mistaken, the SQL standard is to return the first non-NULL value for string types. I don't have the SQL standard on my but maybe @hannes you can check this?  Might be on of those edge cases

**Comment by Mytherin** [comment]
I think the issue here is the implicit type casting of the coalesce function when enums are present, similar to the issue we had before with `IN`. I would say this should just upcast to `VARCHAR` in case there are two different enums.

**Comment by Tmonster** [comment]
I still don't quite understand. The coalesce function already implicitly casts enums to strings if I'm not mistaken https://github.com/duckdb/duckdb/pull/7114 . 

The descired behavior from Kirill is to have every enum value present from both enums in the `coalesce` column. So something like 
```
duckdb:::rel_to_altrep(rel2)
#>   a b ___coalesce(a, b)
#> 1 a b                 ("a", "b")
```
Am I interpreting this correct @krlmlr ?

**Comment by krlmlr** [comment]
Yes. I expect the value `"a"`, but the type should be an enum with both levels.

**Comment by hannes** [comment]
Cast to VARCHAR is fine
