### ISSUE TITLE
DuckDB JDBC throws `Resource temporarily unavailable`

### ISSUE THREAD

**Issue by SuriZhang** [duckdb/duckdb#7462]
### What happens?

I'm running some code using duckdb JDBC, unexpected error `Resource Temporarily Unavailable` is thrown.
Resource temporarily unavailable
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:46)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:38)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)

### To Reproduce

Run this code

    public static void main(String[] args) throws SQLException {
        for ( int i = 0 ; i< 600; i++) {
            System.out.println("i = " + i);
            Connection connection = DriverManager.getConnection(DB_FILE_PATH);
            Statement stmt1 = connection.createStatement();
            stmt1.executeUpdate("CREATE TABLE table_0 (column_30 DOUBLE)");
            Statement stmt2 = connection.createStatement();
            stmt2.executeUpdate("CREATE TABLE table_1 (column_0 BIT, column_11 INT, column_1 INT)");
            Statement stmt3 = connection.createStatement();
            stmt3.executeUpdate("CREATE TABLE table_2 (column_0 TEXT)");
            Statement stmt4 = connection.createStatement();
            stmt4.executeUpdate("CREATE TABLE table_3 (column_0 DECIMAL)");
            Statement stmt5 = connection.createStatement();
            stmt5.executeUpdate("CREATE TABLE table_4 (column_0 DOUBLE)");
            connection.close();
            // shutdown...
            connection.close();
            Connection connection1 = DriverManager.getConnection(DB_FILE_PATH);
            connection1.getMetaData();
            Statement stmt6 = connection1.createStatement();
            stmt6.execute("DROP TABLE IF EXISTS table_0");
            Statement stmt7 = connection1.createStatement();
            stmt7.execute("DROP TABLE IF EXISTS table_1");
            Statement stmt8 = connection1.createStatement();
            stmt8.execute("DROP TABLE IF EXISTS table_2");
            Statement stmt9 = connection1.createStatement();
            stmt9.execute("DROP TABLE IF EXISTS table_3");
            Statement stmt10 = connection1.createStatement();
            stmt10.execute("DROP TABLE IF EXISTS table_4");
            connection1.close();
        }
    }

This should throw the bug at ~514th iteration.
    

### OS:

Ubuntu amd64

### DuckDB Version:

duckdb_jdbc-0.8.0-20230510.034448-280.jar

### DuckDB Client:

JDBC

### Full Name:

Suri Zhang

### Affiliation:

National University of Singapore, School of Computing

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
I've been able to consistently reproduce this, it looks related to the `Statement`'s not being closed (either with try-with-resources or an explicit close). Keeping track of statements and then closing them ourselves when the connection is closed seems to fix the issue.

Under the hood, it appears that the file descriptors held by the process grow without bound, specifically those for the WAL and .db file, which eventually triggers the Resource Temporarily Unavailable message
