### ISSUE TITLE
Lightweight Buffer Manager

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#748]
I propose that we implement a light-weight decentralized buffer manager, similar to [LeanStore](https://db.in.tum.de/~leis/papers/leanstore.pdf), but simplified to cater to analytical workloads. 

My initial thoughts are that for us the important cases are that we need to support (1) efficient pinning when pages are already pinned, without any global locks; (2) parallel loading (i.e. we need to be able to read multiple pages at the same time), (3) async I/O/prefetching support (i.e. in a sequential scan we know exactly which blocks will be read -> we should take advantage).

To achieve (1) we need to have local locks. The LeanStore solution of storing the locks next to the pointers seems sensible to me, although I would avoid using pointer swizzling/tagging for portability reasons. Rather I would change the buffer pointers to a struct that looks e.g. like:

```
struct BufferPointer {
        // state, 0 = unloaded, 1 = loaded but unused, 2 = read-locked, 3 = write-locked, 4=being loaded
	int8_t state;
        // amount of concurrent readers
	int32_t readers;
        // pointer to data OR block id
	union {
		data_ptr_t dataptr;
		block_id_t block_id;
	};
};
```

The disadvantage of this local state is that you can only have a single pointer to a block. This can be a problem when we have pages that have multiple pointers to them, e.g. when we put data from multiple sparse columns on the same page. This restriction can be relaxed by using another layer of indirection, e.g. by using a shared_ptr<BufferPointer>. 

We need to have a list of these buffer pointers somewhere as well to handle unloading when required. Having some centralized structure handle loading/unloading seems fine to me, as long as parallel loading is supported. We have an advantage in that our pages are much bigger than traditional pages (256K vs 4~16K), and loaded/unloaded a lot less randomly because we are not dealing with point queries. 

Our eviction strategy should also take into account the access patterns of analytical queries. LRU works well in a B-tree scenario, but not really for table scans of larger-than-memory tables. 

Another point is that LeanStore uses a background thread for eviction; we do not want any background threads working in DuckDB to avoid surprising behavior for the user. Hence the threads doing the loading will also need to do potential unloading. 

Anyway those are some initial thoughts, more brainstorming required.

**Comment by jtommaney-alibaba** [comment]
It looks like both of these are related to this issue, probably can consolidate. 

**Significant spin lock on query dominated by scan operation #875
Performance opportunity with BufferManager Pin/UnPin #1018**

```
Simplest use case:
create temporary table d as select mod(range, 100000) g, 42 p from range(1000000000);
pragma threads=16;
select count(*) from d where g = 50000;
```


These have an impact on a number of TPCH queries at scaling starting with threads=2, and dominating workloads at threads=4 or above.  There are some separate issues with some HT finalize and hash join I am working on detailing.  

<img width="547" alt="Screen Shot 2020-10-23 at 5 28 02 PM" src="https://user-images.githubusercontent.com/41884051/97063537-290c2f80-1555-11eb-9c1d-ea6a7099a27b.png">

Above metrics are with merged paragght3 branch.

Curiously, Q6 at sf100 showed better linear scaling last week (~ Oct 15th) .   I apologize, I don't think I have the commit version captured.
            | threads=1; | threads=2; | threads=4; | threads=8; | threads=16; | threads=32;
Q6       |     3.031      |      1.814      |        1.469   |      1.12        |       1.192       |       1.266
