### ISSUE TITLE
Extensions not installable in Julia

### ISSUE THREAD

**Issue by tbeason** [duckdb/duckdb#7485]
### What happens?

Extensions fail to download when using the Julia client.

### To Reproduce

```julia
julia> using DuckDB

julia> con = DBInterface.connect(DuckDB.DB, ":memory:")
DuckDB.DB(":memory:")

julia> DBInterface.execute(con, "INSTALL httpfs;")
ERROR: Execute of query "INSTALL httpfs;" failed: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/ae9bcc347c/windows_amd64_mingw/httpfs.duckdb_extension.gz"
Extension "httpfs" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
Stacktrace:
 [1] execute(stmt::DuckDB.Stmt, params::NamedTuple{(), Tuple{}})
   @ DuckDB C:\Users\beasont\.julia\packages\DuckDB\PMwHV\src\result.jl:733
 [2] execute
   @ C:\Users\beasont\.julia\packages\DuckDB\PMwHV\src\result.jl:834 [inlined]
 [3] execute
   @ C:\Users\beasont\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:130 [inlined]
 [4] #execute#2
   @ C:\Users\beasont\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:152 [inlined]
 [5] execute(conn::DuckDB.DB, sql::String)
   @ DBInterface C:\Users\beasont\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:152
 [6] top-level scope
   @ REPL[6]:1

julia> DBInterface.execute(con, "INSTALL postgres_scanner;")
ERROR: Execute of query "INSTALL postgres_scanner;" failed: HTTP Error: Failed to download extension "postgres_scanner" at URL "http://extensions.duckdb.org/ae9bcc347c/windows_amd64_mingw/postgres_scanner.duckdb_extension.gz"
Extension "postgres_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
Stacktrace:
 [1] execute(stmt::DuckDB.Stmt, params::NamedTuple{(), Tuple{}})
   @ DuckDB C:\Users\beasont\.julia\packages\DuckDB\PMwHV\src\result.jl:733
 [2] execute
   @ C:\Users\beasont\.julia\packages\DuckDB\PMwHV\src\result.jl:834 [inlined]
 [3] execute
   @ C:\Users\beasont\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:130 [inlined]
 [4] #execute#2
   @ C:\Users\beasont\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:152 [inlined]
 [5] execute(conn::DuckDB.DB, sql::String)
   @ DBInterface C:\Users\beasont\.julia\packages\DBInterface\1Gmxx\src\DBInterface.jl:152
 [6] top-level scope
   @ REPL[7]:1
```

### OS:

Windows

### DuckDB Version:

0.7.1

### DuckDB Client:

Julia

### Full Name:

Tyler Beason

### Affiliation:

Virginia Tech

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
Current stable release: v1.9.0 (May 7, 2023)?

**Comment by darnocian** [comment]
I noticed something similar with the json extension. Attempting to access http://extensions.duckdb.org/v0.7.1/windows_i686/json.duckdb_extension.gz  in the browser gives an S3 'AccessDenied' error.

**Comment by Mause** [comment]
> I noticed something similar with the json extension. Attempting to access http://extensions.duckdb.org/v0.7.1/windows_i686/json.duckdb_extension.gz in the browser gives an S3 'AccessDenied' error.

It's possible we don't publish extension builds for Windows 32 bit systems, as they're so rare these days - can you confirm that's the case with your system?

**Comment by darnocian** [comment]
I think that is the case - 32bit extension for json might not be there. I tested 64bit and it worked. Although, would be nice to have 32bit extensions if the libduckdb is being deployed.  it is a nicer experience if they are via the official site,  worst case it can be built manually.

**Comment by Mytherin** [comment]
Should be fixed now
