### ISSUE TITLE
Feature: Add support for regex pattern in `EXCLUDE`

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#7494]
### What happens?

Recently we added support for regex in the `SELECT COLUMNS(..)`, which essentially acts like a whitelist.
The reverse however, a blacklist using `EXCLUDE` does not have support for a regex yet.

I propose that we add `SELECT * EXCLUDE(<regex>)`

**Comment by Mytherin** [comment]
Can't you already do this with #6621 in a relatively straightforward manner, e.g.:

```sql
create table integers(i1 int, i2 int, i3 int, j1 int, j2 int);
insert into integers values (1, 2, 3, 4, 5);
select columns(col -> col NOT SIMILAR TO '.*i\d') from integers;
┌───────┬───────┐
│  j1   │  j2   │
│ int32 │ int32 │
├───────┼───────┤
│     4 │     5 │
└───────┴───────┘
```

I'm not such a huge fan of adding more specific functionality - it is kind of a never-ending battle as people will come up with more and more use cases (see e.g. #6374). The purpose of the lambda function is to allow for the user to implement these things themselves using simple expressions.
