### ISSUE TITLE
Glob ** not matching none

### ISSUE THREAD

**Issue by kmatt** [duckdb/duckdb#7495]
### What happens?

From https://duckdb.org/docs/data/multiple_files/overview:

    Wildcard | Description
    * | matches any number of any characters (including none)
    ** | matches any number of subdirectories (including none)

Given local directories partitioned as:

    /a/b/c/**
    /a/b/d/DT=YYYYMMDD/*.parquet

The goal is to automate reads or imports based on the first 3 directory levels, but the `**` pattern does not seem to consider "none" at the fourth level, requiring conditional logic if a directory is date partitioned or not.

Is this expected?

### To Reproduce

`SELECT * FROM read_parquet('/a/b/c/**')` returns expected rows

`SELECT * FROM read_parquet('/a/b/d/**')` returns "Error: IO Error: No files found that match the pattern"

`SELECT * FROM read_parquet('/a/b/d/**/*.parquet')` returns expected rows, but
`SELECT * FROM read_parquet('/a/b/c/**/*.parquet')` returns the IO Error

### OS:

Ubuntu 22.04

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Matt K

### Affiliation:

Independent

### Have you tried this on the latest `master` branch?

- [] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Please test on master, as there has been significant work done recently to support crawl expressions (`**`)
<https://github.com/duckdb/duckdb/pull/6627>

**Comment by kmatt** [comment]
Built CLI `v0.7.2-dev3515 12638bd156` and `/**/*.parquet` is working in both cases.
