### ISSUE TITLE
Unexpected error `Invalid Error: Argument index "0" out of range`

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#7498]
### What happens?

The following program triggers this error:

```
CREATE TABLE t0(c0 INT);
SELECT (t0.c0) FROM t0 WHERE (1 IN (2, PRINTF(('S%m'))));
```

### To Reproduce

I run this program on latest commit version https://github.com/duckdb/duckdb/commit/12638bd15623508cdc7fb3f670b291b51f92ee43

### OS:

ubuntu 22.04

### DuckDB Version:

https://github.com/duckdb/duckdb/commit/12638bd15623508cdc7fb3f670b291b51f92ee43

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
0.7.1, it's not a bug I think. 
```
D select PRINTF(('S%m'));
Error: Invalid Error: argument index out of range
D select PRINTF(('S%m',2));
Error: Invalid Error: argument index out of range
D select PRINTF('S%m',2);
Error: Invalid Error: invalid type specifier
D select PRINTF('S%d',2);
┌──────────────────┐
│ printf('S%d', 2) │
│     varchar      │
├──────────────────┤
│ S2               │
└──────────────────┘
```

**Comment by DerZc** [comment]
Hi @l1t1 I got it, thank you for your explanation! So sorry for this false report, I close it.
