### ISSUE TITLE
Triggers and Generated Columns

### ISSUE THREAD

**Issue by prashantharaonr** [duckdb/duckdb#750]
As soon as I perform bulk uploads to a table with this event I want to run a trigger that performs some calculations and update the same table or another table. Is this doable?

Also, is it possible to define a generated column?

**Comment by Mytherin** [comment]
Triggers are currently not supported, and likely will not be supported for quite some time. They are rather low priority at the moment.

Generated columns are not yet supported either, but adding them is a higher priority. For now, you could simulate generated columns by defining a view.

**Comment by hannes** [comment]
See discussion in #1187
