### ISSUE TITLE
String split benchmark wrong result

### ISSUE THREAD

**Issue by xuke-hat** [duckdb/duckdb#7504]
### What happens?

In the latest commit, string split benchmark result is incorrect, including `benchmark/micro/list/string_split.benchmark`,  `benchmark/micro/list/string_split_regexp.benchmark`, `benchmark/micro/list/string_split_unicode.benchmark`

### To Reproduce

```
./benchmark/benchmark_runner benchmark/micro/list/string_split.benchmark
name    run     timing
benchmark/micro/list/string_split.benchmark     1       INCORRECT
INCORRECT RESULT: Error in result on row 1 column 1: expected value "27124176" but got value "27116609"
Obtained result:
sum(length(str_split(l_comment, ' ')))
HUGEINT
[ Rows: 1]
27116609
```

### OS:

ubuntu 20.04

### DuckDB Version:

v0.7.2-dev3561

### DuckDB Client:

binary

### Full Name:

Ke Xu

### Affiliation:

Southeast University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by xuke-hat** [comment]
Thanks for your fix! It seems most benchmark that contains `l_comment` is broken, I can make a PR for this.

**Comment by carlopi** [comment]
In #7515 (not yet merged) I tried to fix a few other that I saw, but please do take a look and open a PR if something is missing.
