### ISSUE TITLE
union all wrong result with pandas DataFrame

### ISSUE THREAD

**Issue by git20190108** [duckdb/duckdb#7513]
### What happens?

The sql syntax union all fails to query the dataframe's table. The results of only one query are displayed

### To Reproduce

tst_df = pd.DataFrame({'a':[1,23,3,5]})

duckdb.sql('''
select *
from tst_df
union all 
select *
from tst_df
''')

### OS:

centos 

### DuckDB Version:

'0.7.1'

### DuckDB Client:

python

### Full Name:

lotus 

### Affiliation:

xxx

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I'm getting:
```
┌───────┐
│   a   │
│ int64 │
├───────┤
│     1 │
│    23 │
│     3 │
│     5 │
│     1 │
│    23 │
│     3 │
│     5 │
└───────┘
```
What are you expecting the results to be?

**Comment by Tishj** [comment]
If you're looking for something like this:
```sql
D with tst_df as (select 1,23,3,5)
> select * from tst_df union all select * from tst_df;
┌───────┬───────┬───────┬───────┐
│   1   │  23   │   3   │   5   │
│ int32 │ int32 │ int32 │ int32 │
├───────┼───────┼───────┼───────┤
│     1 │    23 │     3 │     5 │
│     1 │    23 │     3 │     5 │
└───────┴───────┴───────┴───────┘
```
Then you need multiple columns

**Comment by git20190108** [comment]
> I'm getting:
> 
> ```
> ┌───────┐
> │   a   │
> │ int64 │
> ├───────┤
> │     1 │
> │    23 │
> │     3 │
> │     5 │
> │     1 │
> │    23 │
> │     3 │
> │     5 │
> └───────┘
> ```
> 
> What are you expecting the results to be?

You got the right result, but that's all I got

Python == 3.7.13
pandas ==1.3.5

┌───────┐
│   a   │
│ int64 │
├───────┤
│     1 │
│    23 │
│     3 │
│     5 │
└───────┘

**Comment by paultiq** [comment]
Yah, I can reproduce on pandas 2.0.1 and 0.7.2-dev3666	

```import pandas as pd

import duckdb 

tst_df = pd.DataFrame({'a':[1,23,3,5]})

duckdb.sql('''
set timezone = 'UTC';
select *
from tst_df
union all
select *
from tst_df
''')
```

![image](https://github.com/duckdb/duckdb/assets/104510378/d842a18a-c5d5-4165-a674-6de617d90d72)

#### without the timezone:
```
import pandas as pd
import duckdb 
tst_df = pd.DataFrame({'a':[1,23,3,5]})
duckdb.sql('''
select *
from tst_df
union all
select *
from tst_df
''')
```
![image](https://github.com/duckdb/duckdb/assets/104510378/ffaadba5-14de-4900-9322-02705a48d876)

**Comment by Mytherin** [comment]
Thanks! I can reproduce this - it looks like it is related to executing multiple statements inside a `.sql` block - e.g.:

```python
import duckdb
import pandas as pd 

tst_df = pd.DataFrame({'a':[1,23,3,5]})

duckdb.sql('''
select 42;
select *
from tst_df
union all
select *
from tst_df;
''').show()
# ┌───────┐
# │   a   │
# │ int64 │
# ├───────┤
# │     1 │
# │    23 │
# │     3 │
# │     5 │
# └───────┘
```

@Tishj could you have a look?

**Comment by Tishj** [comment]
```
      success = false
      error = {
        initialized = true
        type = INVALID_INPUT
        raw_message = "PandasScan called but GIL was already held!"
        final_message = ""
        exception_instance = std::__1::shared_ptr<duckdb::Exception>::element_type @ 0x00006000026591b8 strong=1 weak=1 {
          __ptr_ = 0x00006000026591b8
        }
      }
```
We silently ignored the error
