### ISSUE TITLE
CSV reader http state management causes a SEGFAULT when running under a prepared statement

### ISSUE THREAD

**Issue by bleskes** [duckdb/duckdb#7520]
### What happens?

When reading a CSV file from http, a [state pointer is stored under the file handle](https://github.com/duckdb/duckdb/blob/12638bd15623508cdc7fb3f670b291b51f92ee43/extension/httpfs/include/httpfs.hpp#L76) to [the http state in the client context](https://github.com/duckdb/duckdb/blob/12638bd15623508cdc7fb3f670b291b51f92ee43/src/include/duckdb/common/http_state.hpp#L54) , which is reset on each query execution.

Prepared statement are create under a transaction which completes and are then executed under another transaction (if I read things correctly), which causes that pointer to be invalid. 

### To Reproduce

This test will fail with a segfault.

```
TEST_CASE("csv and prepared statements", "[csv]") {
	DuckDB db;
	duckdb::Connection con(db);
	auto statement =
	    con.Prepare("from read_csv_auto('https://github.com/duckdb/duckdb/raw/master/data/csv/customer.csv')");
	REQUIRE_NO_FAIL(statement->Execute());
}
```

### OS:

MacOS

### DuckDB Version:

Dev version

### DuckDB Client:

cpp

### Full Name:

Boaz Leskes

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
@pdet I think the solution here is to make `HTTPState` a shared pointer

**Comment by pdet** [comment]
> @pdet I think the solution here is to make `HTTPState` a shared pointer

Ha just saw this message, but it was exactly what I did.
