### ISSUE TITLE
FLOOR uses trunc for negative numbers

### ISSUE THREAD

**Issue by jkew** [duckdb/duckdb#7527]
### What happens?

Most libraries, snowflake, bigquery, etc use truncation division for modulo, because it is cheap and fast and OK for positive numbers. Other libraries like pandas will use floor division. Floor itself is typically implemented using floor division, so if I want to have a modulo using floor division I'll often rewrite it using floor. Unfortunately this doesn't work for DuckDB because floor is essentially trunc.

*Python*:
`In [10]: math.floor(4800128 / -23)
Out[10]: -208702

In [11]: math.trunc(4800128 / -23)
Out[11]: -208701`

*DuckDB*
```
D SELECT FLOOR(4800128 / -23) AS FLOOR_DIV,(4800128 / -23)::int AS TRUNC;
┌───────────┬─────────┐
 │ FLOOR_DIV                      │  TRUNC                     │
 │  double                             │  int32                         │
├───────────┼─────────┤
 │ -208701.0                        │ -208701                     │
└───────────┴─────────┘
`
*In context w/ modulo*
`D SELECT MOD(4800128, -23) AS DEFAULT_MOD,
> 4800128 - -23 * FLOOR(4800128 / -23) AS FLOOR_DIV_MOD,
> 4800128 - -23 * (4800128 / -23)::int AS TRUNC_MOD;
┌─────────────┬───────────────┬───────────┐
│ DEFAULT_MOD │ FLOOR_DIV_MOD │ TRUNC_MOD │
│    int32    │    double     │   int32   │
├─────────────┼───────────────┼───────────┤
│           5 │           5.0 │         5 │`

### To Reproduce

`SELECT FLOOR(4800128 / -23) AS FLOOR_DIV,(4800128 / -23)::int AS TRUNC;`

### OS:

OSX

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

cli

### Full Name:

John Kew

### Affiliation:

Ponder Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jkew** [comment]
I figured this out; the truncation is occurring before and it is cast to INT. The solution to make sure floor is handed a double. Just a minor syntactic difference between databases.

**Comment by rsund** [comment]
Maybe you could also try FDIV or FMOD? Or if those are not what you are looking for, just define DuckDB macro (CREATE MACRO) for the syntax you found working.

**Comment by jkew** [comment]
@rsund Yeah, ultimately this is resolved by this pull request which was merged earlier this month: https://github.com/duckdb/duckdb/pull/7082

It's just a funny point of confusion for me, and I'm primarily working w/ Snowflake/GBQ now so I'm used to that behavior.
