### ISSUE TITLE
ConversionException on simple Recursive SQL

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#7529]
### What happens?

With a simple recursive query with a decimal base case, the result is a conversion exception. when the value exceeds the type of the base cases type. 

When I change the type to "int" base case, the results are all rounded, yielding a perhaps questionable result. 

Interestingly, comparing to postgres:
- The decimal base case works fine - https://dbfiddle.uk/NykI_Dg8
- But, postgres throws an error for the int base case: "ERROR:  recursive query "test" column 1 has type integer in non-recursive term but type numeric overall" - https://dbfiddle.uk/oBTek9Vo

### decimal base case
```
WITH RECURSIVE test AS (
    SELECT 1.0 AS value
    UNION ALL
    SELECT value*2
    FROM test
    WHERE value < 10
)
SELECT value FROM test;
```
> ConversionException: Conversion Error: Casting value "16.0" to type DECIMAL(2,1) failed: value is out of range!

### int base case:
```
WITH RECURSIVE test AS (
    SELECT 1 AS value
    UNION ALL
    SELECT value*1.8
    FROM test
    WHERE value < 10
)
SELECT value FROM test;
```
![image](https://github.com/duckdb/duckdb/assets/104510378/d6db07a3-86d1-4217-9582-98e74768209d)

### OS:

Windows

### DuckDB Version:

0.7.2-dev3666	

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Still reproduces on `│ 0.8.2-dev3092   │ 1f17e1cec6 │`

**Comment by khanetor** [comment]
I am having the same issue.
