### ISSUE TITLE
Parser Error at `ASOF` when using duckdb-cli

### ISSUE THREAD

**Issue by macrostring** [duckdb/duckdb#7531]
### What happens?

I was following the [guide](https://duckdb.org/docs/guides/sql_features/asof_join) to try `ASOF JOIN`, but got the error as shown below.
```
Error: Parser Error: syntax error at or near "ASOF"
LINE 2:   FROM sales s ASOF LEFT JOIN prices p
```

### To Reproduce

```sql
CREATE TABLE prices AS (
    SELECT '2001-01-01 00:16:00'::TIMESTAMP + INTERVAL (v) MINUTE AS ticker_time,
        v AS unit_price
    FROM range(0,5) vals(v)
);

create table sales(item text, sale_time timestamp, quantity int);
insert into sales values('a', '2001-01-01 00:18:00', 10);
insert into sales values('b', '2001-01-01 00:18:30', 20);
insert into sales values('c', '2001-01-01 00:19:00', 30);

SELECT s.*, p.unit_price, s.quantity * p.unit_price AS total_cost
  FROM sales s ASOF LEFT JOIN prices p
    ON s.sale_time >= p.ticker_time;
```

### OS:

macOS Monterey Version 12.5

### DuckDB Version:

Homebrew v0.7.1

### DuckDB Client:

CLI

### Full Name:

Jun Zhou

### Affiliation:

Northeastern University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This feature is available only in the dev versions, and the soon to be released 0.8.0 version
