### ISSUE TITLE
`min` and `max` handle `NaN` differently

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#7541]
### What happens?

When calling function `min` on a `float`-typed column, the result will be calculated with the NaN entries ignored (same as if they were `null`), whereas the function `max` will instead return `nan`:

### To Reproduce

```sql
with tbl as (
    select 0. as c1
    union all
    select 'nan'::float as c1
)
select min(c1), max(c1)
from tbl
```
```
┌─────────┬─────────┐
│ min(c1) │ max(c1) │
│  float  │  float  │
├─────────┼─────────┤
│     0.0 │     nan │
└─────────┴─────────┘
```

Not _entirely_ sure if this is a bug or if the SQL standard specifies them to work like this, as it seems postgres suffers from the same behavior.

### OS:

Linux

### DuckDB Version:

0.7.2-dev3710

### DuckDB Client:

Any

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is not a bug but intended behavior - both Postgres and DuckDB explicitly specify NaN as being *larger than all other values*. See [here](https://github.com/duckdb/duckdb/pull/3292). As such having `min` not return `NaN`, and having `max` return `NaN` is expected.
