### ISSUE TITLE
MODE() WITHIN GROUP Incorrect Output

### ISSUE THREAD

**Issue by Zirescu** [duckdb/duckdb#7543]
### What happens?

MODE() WITHIN GROUP when provided with an ORDER BY value DESC doesn't produce the correct output.

### To Reproduce

```
SELECT MODE() WITHIN GROUP (ORDER BY order_occurrences DESC) FROM (
VALUES
	(500, 1),
	(1000, 2),
	(800, 3),
	(1000, 4),
	(500, 5),
	(550, 6),
	(400, 7),
	(200, 8),
	(10, 9)
)items_per_order(order_occurrences, item_count);
```
Should output 1000, but gives 500. 

Tested in the DuckDB shell with v.0.7.2-dev2931 as well as within a Workspace running 0.7.0. 

### OS:

Web

### DuckDB Version:

DuckDB Web Shell Database: v0.7.2-dev2931

### DuckDB Client:

Web

### Full Name:

Dwayne McMurchy

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm the ties are indeed not correctly resolved according to the `ORDER BY` predicate for `MODE`.

Perhaps related - ordered aggregates do not seem to work together with `MODE` either:

```sql
SELECT MODE(order_occurrences ORDER BY order_occurrences DESC) FROM (
VALUES
	(500, 1),
	(1000, 2),
	(800, 3),
	(1000, 4),
	(500, 5),
	(550, 6),
	(400, 7),
	(200, 8),
	(10, 9)
)items_per_order(order_occurrences, item_count);
-- Error: Binder Error: No function matches the given name and argument types 'mode(INTEGER, INTEGER)'. You might need to add explicit type casts.
```

**Comment by hawkfish** [comment]
Ah, we are not tracking the actual ordering, which could be a problem for all of them. From the [PG docs](https://www.postgresql.org/docs/current/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE):

> Each of the “hypothetical-set” aggregates listed in [Table 9.61](https://www.postgresql.org/docs/current/functions-aggregate.html#FUNCTIONS-HYPOTHETICAL-TABLE) is associated with a window function of the same name defined in [Section 9.22](https://www.postgresql.org/docs/current/functions-window.html). In each case, the aggregate's result is the value that the associated window function would have returned for the “hypothetical” row constructed from args, if such a row had been added to the sorted group of rows represented by the sorted_args.

So we should be producing the same result as

```sql
SELECT DISTINCT MODE(order_occurrences) OVER (ORDER BY order_occurrences DESC) FROM ...
```

This may be tricky to retrofit.

**Comment by hawkfish** [comment]
Possible fix:

1. Mark `MODE` as an order-sensitive aggregate
2. Tie-break based on hash table insert ordering
