### ISSUE TITLE
Segmentation fault on `SELECT`

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#7551]
### What happens?

The following program triggers a segmentation fault:
```
CREATE TABLE t0(c0 VARCHAR);
CREATE TABLE t1(c0 DATE);

INSERT INTO t1(c0) VALUES ((TIMESTAMP '1970-01-25 15:59:18'));

INSERT INTO t0(c0) VALUES ((DATE '1969-12-20')), ((TIMESTAMP '1970-01-11 21:25:45')), (DEFAULT), (('1')), (('')), ((TIMESTAMP '1969-12-15 21:35:22'));

CREATE VIEW v0(c0) AS SELECT t1.c0 FROM t1, t0;

SELECT t0.rowid FROM t0, t1 LEFT JOIN v0 ON (1) WHERE t0.c0 >= v0.c0 AND t0.c0 <= v0.c0;
```
If I remove any value of `t0.c0`, then can not reproduce this segmentation fault.
And the `BETWEEN` can also trigger this bug like `SELECT t0.rowid FROM t0, t1 LEFT  JOIN v0 ON (1) WHERE (t0.c0 BETWEEN v0.c0 AND v0.c0);`

### To Reproduce

I can reproduce this on the latest commit version https://github.com/duckdb/duckdb/commit/6e908cfc55a42d27e2dcbdaf84ce99d8cd6fe2fd

### OS:

ubuntu 22.04

### DuckDB Version:

https://github.com/duckdb/duckdb/commit/6e908cfc55a42d27e2dcbdaf84ce99d8cd6fe2fd

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This is a type mismatch in the internals of `IEJoin` so I'll deal with it.

**Comment by hawkfish** [comment]
After looking into it, it's a compilation error. IEJoin is being told to compare strings, but the appropriate casts have not been injected.

**Comment by Mytherin** [comment]
I have looked into this as well and pushed a partial fix to report an `InternalException` instead of crashing in case of such a type mismatch (#7587). It does appear to be an issue in the `IEJoin`, however. The casts are present in the join condition - but he incorrect expressions are executed in `PhysicalRangeJoin::LocalSortedTable::LocalSortedTable`. It seems that the `child` parameter is not set up correctly.

**Comment by hawkfish** [comment]
There is something strange going on here. It looks like the right pipeline is executing first, even though the left one is supposed to go first (`PhysicalIEJoin::BuildPipelines`). Moreover, the right pipeline explicitly depends on the left one, so I don't know how this could have happened.

**Comment by hawkfish** [comment]
The pipeline scheduling appears to be specific to the reported query because this test gives the correct result:

```sql
WITH lhs AS (
	SELECT * FROM (VALUES
		(1, 10, 20, 30),
		(2, 30, 20, 10)
	) t(id, a, b, c)
), rhs AS (
	SELECT * FROM (VALUES
		(1, 30, 20, 10),
		(2, 10, 20, 30)
	) t(id, a, b, c)
)
SELECT lhs.id, rhs.id
FROM lhs, rhs
WHERE lhs.a < rhs.b AND lhs.c > rhs.c
----
1	1
```

If the inputs were being reversed, it would output `2, 2`.

**Comment by hawkfish** [comment]
I believe the pipeline issue has been fixed.
