### ISSUE TITLE
Unable to create TEMP table with TYPE ENUM column

### ISSUE THREAD

**Issue by 2-5** [duckdb/duckdb#7552]
### What happens?

Can't create a TEMP table with TYPE ENUM columns.

### To Reproduce

```sql
CREATE TYPE direction AS ENUM ('up', 'down');
CREATE TEMP TABLE tbl_temp (id INTEGER, dir direction);
-- duckdb.CatalogException: Catalog Error: Type with name direction does not exist!
```

OR

```sql
CREATE TYPE direction AS ENUM ('up', 'down');
CREATE TEMP TABLE tbl_temp (id INTEGER, dir test_db.direction);
-- duckdb.ParserException: Parser Error: syntax error at or near "."
```

OR

```sql
USE temp;
CREATE TYPE direction AS ENUM ('up', 'down');
-- duckdb.ParserException: Parser Error: Only TEMPORARY table names can use the "temp" catalog
```

### OS:

Windows

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

2-5

### Affiliation:

private

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by omo** [comment]
```
USE temp;
CREATE TYPE direction AS ENUM ('up', 'down');
-- duckdb.ParserException: Parser Error: Only TEMPORARY table names can use the "temp" catalog
```

I guess there are two solutions here:
1. Support CREATE TEMP TYPE syntax.
2. Make the "temp" schemed table creation implicitly TEMPORARY (vs showing the error).

...

2. feels like a big hammer to me 1.  probably aligns with other parts of the language better.

Slightly related bug; #3076

**Comment by 2-5** [comment]
My use case was this: create a regular table (backed by a .duckdb file) and a temporary memory table with the same columns. Some of them begin TYPE ENUMs. And then copy rows from one to the other. It seems this is impossible, because the TYPE ENUMs will not be compatible anyway, due to them being in different catalogs, so some form of casting would be required.
