### ISSUE TITLE
DB called "temp.db" causes Parser Error

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#7554]
### What happens?

Getting this error:
Error: Parser Error: Only TEMPORARY table names can use the "temp" catalog

With a db named `temp.db`

Not sure if this is intended behavior, but the error is confusing.

### To Reproduce

Create a db named `temp.db` first
```sh
./build/debug/duckdb temp.db
```
Then create something in the catalog
```sql
create table test (i int);
-- Error: Parser Error: Only TEMPORARY table names can use the "temp" catalog
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Laurens

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by mingodad** [comment]
It works with sqlite3, but it seems to clash with the PostgreSQL dialect that is used by duckdb.
See ["src/planner/binder/statement/bind_create.cpp:93" :](https://github.com/duckdb/duckdb/blob/1d304769a4451e69f2cf4c376dad498226615c2c/src/planner/binder/statement/bind_create.cpp#L93)

**Comment by mingodad** [comment]
Also see here where TEMP_CATALOG is defined https://github.com/duckdb/duckdb/blob/1d304769a4451e69f2cf4c376dad498226615c2c/src/include/duckdb/common/constants.hpp#L31 .

**Comment by mingodad** [comment]
Searching the documentation I only found a reference here https://duckdb.org/docs/sql/information_schema#catalog-functions that mention "temp" as an active schema maybe a mention to "temp" as reserved database name could be added there or in other place.

**Comment by mingodad** [comment]
Testing with `main.db` and `pg_catalog.db` and `create table test (i int);` works, but maybe some other combination of `DDL` or `DML` could fail with then too.
