### ISSUE TITLE
:bug: No more autocomplete on v0.8.0

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#7564]
### What happens?

After having upgraded to [`v0.8.0`](https://github.com/duckdb/duckdb/releases/tag/v0.8.0), no more autocomplete on:

- keywords (select,...)
- table names

### To Reproduce

Just type `SEL` then `TAB` and see that the autocomplete is broken, same for database objects

### OS:

5.15.0-72-generic #79-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### DuckDB Version:

v0.8.0

### DuckDB Client:

cli

### Full Name:

Adrien SALES

### Affiliation:

Independant

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Thanks for raising this issue, looks like something went wrong when I pulled the autocomplete extension out into it's own extension.

```
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select * from duckdb_extensions();
┌───────────────────┬─────────┬───────────┬──────────────┬─────────────────────────────────────────┬───────────────────┐
│  extension_name   │ loaded  │ installed │ install_path │               description               │      aliases      │
│      varchar      │ boolean │  boolean  │   varchar    │                 varchar                 │     varchar[]     │
├───────────────────┼─────────┼───────────┼──────────────┼─────────────────────────────────────────┼───────────────────┤
│ autocomplete      │ false   │ true      │ (BUILT-IN)   │ Add supports for autocomplete in the .  │ []                │
│ excel             │ true    │           │              │                                         │ []                │
│ fts               │ true    │ true      │ (BUILT-IN)   │ Adds support for Full-Text Search Ind.  │ []                │
│ httpfs            │ false   │ false     │              │ Adds support for reading and writing .  │ [http, https, s3] │
│ icu               │ true    │ true      │ (BUILT-IN)   │ Adds support for time zones and colla.  │ []                │
│ inet              │ false   │ false     │              │ Adds support for IP-related data type.  │ []                │
│ jemalloc          │ false   │ false     │              │ Overwrites system allocator with JEMa.  │ []                │
│ json              │ true    │ true      │ (BUILT-IN)   │ Adds support for JSON operations        │ []                │
│ motherduck        │ false   │ false     │              │ Enables motherduck integration with t.  │ [md]              │
│ parquet           │ true    │ true      │ (BUILT-IN)   │ Adds support for reading and writing .  │ []                │
│ postgres_scanner  │ false   │ false     │              │ Adds support for reading from a Postg.  │ [postgres]        │
│ spatial           │ false   │ false     │              │ Geospatial extension that adds suppor.  │ []                │
│ sql_auto_complete │ true    │           │              │                                         │ []                │
│ sqlite_scanner    │ false   │ false     │              │ Adds support for reading SQLite datab.  │ [sqlite, sqlite3] │
│ tpcds             │ true    │ true      │ (BUILT-IN)   │ Adds TPC-DS data generation and query.  │ []                │
│ tpch              │ true    │ true      │ (BUILT-IN)   │ Adds TPC-H data generation and query .  │ []                │
│ visualizer        │ true    │           │              │                                         │ []                │
├───────────────────┴─────────┴───────────┴──────────────┴─────────────────────────────────────────┴───────────────────┤
│ 17 rows                                                                                                    6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
One entry is loaded, the other is installed.

The extension is invokable though:

```
D select * from sql_auto_complete('select * from duckdb');
┌────────────────┬──────────────────┐
│   suggestion   │ suggestion_start │
│    varchar     │      int32       │
├────────────────┼──────────────────┤
│ duckdb_types   │               14 │
```
so I'm not sure what went wrong

**Comment by adriens** [comment]
Yup, exactly same beahvior here : 

<pre><font color="#5FD700">❯</font> duckdb
v0.8.0 e8e4cea5ec
Enter &quot;.help&quot; for usage hints.
Connected to a <b>transient in-memory database</b>.
Use &quot;.open FILENAME&quot; to reopen on a persistent database.
D  <font color="#8AE234"><b>select </b></font>* <font color="#8AE234"><b>from </b></font>duckdb_extensions();
┌──────────────────┬─────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────┬───────────────────┐
│  extension_name  │ loaded  │ installed │ install_path │                                    description                                     │      aliases      │
│     varchar      │ boolean │  boolean  │   varchar    │                                      varchar                                       │     varchar[]     │
├──────────────────┼─────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────┼───────────────────┤
│ autocomplete     │ false   │ false     │              │ Add supports for autocomplete in the shell                                         │ []                │
│ fts              │ false   │ false     │              │ Adds support for Full-Text Search Indexes                                          │ []                │
│ httpfs           │ false   │ false     │              │ Adds support for reading and writing files over a HTTP(S) connection               │ [http, https, s3] │
│ icu              │ true    │ true      │ (BUILT-IN)   │ Adds support for time zones and collations using the ICU library                   │ []                │
│ inet             │ false   │ false     │              │ Adds support for IP-related data types and functions                               │ []                │
│ jemalloc         │ true    │ true      │ (BUILT-IN)   │ Overwrites system allocator with JEMalloc                                          │ []                │
│ json             │ true    │ true      │ (BUILT-IN)   │ Adds support for JSON operations                                                   │ []                │
│ motherduck       │ false   │ false     │              │ Enables motherduck integration with the system                                     │ [md]              │
│ parquet          │ true    │ true      │ (BUILT-IN)   │ Adds support for reading and writing parquet files                                 │ []                │
│ postgres_scanner │ false   │ false     │              │ Adds support for reading from a Postgres database                                  │ [postgres]        │
│ spatial          │ false   │ false     │              │ Geospatial extension that adds support for working with spatial data and functions │ []                │
│ sqlite_scanner   │ false   │ false     │              │ Adds support for reading SQLite database files                                     │ [sqlite, sqlite3] │
│ tpcds            │ false   │ false     │              │ Adds TPC-DS data generation and query support                                      │ []                │
│ tpch             │ false   │ false     │              │ Adds TPC-H data generation and query support                                       │ []                │
├──────────────────┴─────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────┴───────────────────┤
│ 14 rows                                                                                                                                              6 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
D 
</pre>

**Comment by Mytherin** [comment]
Thanks for the report! The issue here is that we used to enable auto-complete by default for the shell, and now it needs to be manually enabled in the build through `BUILD_AUTOCOMPLETE`. It also seems like this has gone wrong in the homebrew client. I have pushed a fix in https://github.com/duckdb/duckdb/pull/7621 that inlines auto-complete into the shell if the extension itself is disabled.

**Comment by adriens** [comment]
Great, thanks a lot for the great feedback.
I really love the autocomplete as it makes me awesomely produtive on :duck: :muscle:

**Comment by adriens** [comment]
@michael-simons 

> You are everywhere too, aren't you?

Everywhere on the tools that boost my productivity (and my team's one) 🤓

**Comment by adriens** [comment]
Will it be fixed in [v0.8.1](https://github.com/duckdb/duckdb/releases/tag/v0.8.1) :grey_question:

**Comment by Mytherin** [comment]
It should be fixed in v0.8.1 yes

**Comment by adriens** [comment]
i'll let you know once this done

- https://github.com/duckdb/duckdb/discussions/7929

**Comment by adriens** [comment]
- https://github.com/Homebrew/homebrew-core/pull/133489

**Comment by adriens** [comment]
Fixed :clap: 
![image](https://github.com/duckdb/duckdb/assets/5235127/1e539782-fe45-421d-992e-a3fcfb450d6c)

**Comment by michael-simons** [comment]
Sadly, it's missing on 0.9.0 again (macOS Arm64, v0.9.0 0d84ccf478).

**Comment by Mytherin** [comment]
I've already pushed a fix that is pending approval - https://github.com/Homebrew/homebrew-core/pull/146197

**Comment by michael-simons** [comment]
Excellent, thank you!

**Comment by Mytherin** [comment]
This is fixed now, you can run `brew reinstall duckdb` to reinstall the fixed version
