### ISSUE TITLE
Question, C++: how to S3FileSystem to check if remote .parquet file exists before query

### ISSUE THREAD

**Issue by juwalter** [duckdb/duckdb#7572]
### What happens?

not a bug, question:

we are using duckdb in our C++ application for querying Parquet files located in a S3 bucket. We dynamically build the list of needed Parquet files and then construct a VIEW first, then query this VIEW; however, if one of the Parquet files specified in the VIEW does not exist, the entire query fails. We wanted to mitigate this by first checking for existence of the Parquet file using HTTPFS/S3FileSystem (instead of adding another S3 library to our project)

### To Reproduce

```sql
CREATE OR REPLACE VIEW sensors AS
  SELECT 
    uuid, epoch_ms(systime / 1000000) AS systime, value_numeric, value_string
  FROM read_parquet([
          's3://engine-1/2023/04/06/14/0dc4f62a-b36e-43e3-9957-a6e9b2825fb0.parquet',
          's3://engine-1/2023/04/06/15/0dc4f62a-b36e-43e3-9957-a6e9b2825fb0.parquet'
        ]);
```

then

```sql
INSTALL httpfs;
LOAD httpfs;

SET s3_region='us-east-1';
SET s3_endpoint='111.222.123.123:9000';
SET s3_use_ssl=false;
SET s3_url_style='path';
SET s3_access_key_id='minio';
SET s3_secret_access_key='minio8877665544';
```

finally the query

```sql
SELECT uuid, epoch_ms(systime / 1000000) AS systime, value_numeric, value_string FROM sensors WHERE ...
```

Our first idea was to use 

```c++

auto &fs = db.GetFileSystem();
fs.FileExists(my_file);
```

but that does not work. when I do `fs.GetName();` it tells me `VirtualFileSystem`

---

how can we check for existence of remote files in S3 leveraging HTTPFS/S3 configuration in duckdb without resorting to an external S3 library? 

thank you!

### OS:

Linux

### DuckDB Version:

0.7.1

### DuckDB Client:

C++

### Full Name:

Jürgen Walter

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by BigRedAye** [comment]
It would also be nice to have an option to not throw an exception with missing files.

**Comment by juwalter** [comment]
using `duckdb::ClientData::Get(*connection.context).file_opener` we were able to make it work like so

```c++
		auto &fs = db.GetFileSystem();
		auto &file_opener = duckdb::ClientData::Get(*connection.context).file_opener;
		auto is_not_exists = [&fs, &file_opener](const auto &a) {
			try
			{
				auto handle = fs.OpenFile(
					a,
					duckdb::FileFlags::FILE_FLAGS_READ,
					duckdb::FileLockType::NO_LOCK,
					duckdb::FileCompressionType::UNCOMPRESSED,
					file_opener.get()
				);
				LOG_DEBUG() << "File found: " << a;
				return false;
			}
			catch (const std::exception &e)
			{
				LOG_WARNING() << "File does not exist: " << a << ", " << e.what();
				return true;
			};
		};

```
