### ISSUE TITLE
Doc Comment: Scalar UDF examples are broken

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#7573]
### What happens?

The [0.8.0 Announcement](https://duckdb.org/2023/05/17/announcing-duckdb-080.html) links to [User-Defined Scalar Functions for Python](https://github.com/duckdb/duckdb/pull/7171) - PR 7171.

But, the syntax changed in a later [commit](https://github.com/duckdb/duckdb/pull/7171/commits/df63e94125a789989e4ca0c0c0c7fc397ab64518), rendering the text examples unusable 

Specifically, the change not reflected in PR7171 text is the change from `register_scalar_udf` to `create_function`, and from `unregister_udf` to `remove_function`. Also: I think "vectorized" changed to "type='arrow'". May have other changes, haven't gone through all options.

Recommend either linking to a better doc, or updating PR7171 to reflect the updated syntax. 

### To Reproduce

Here's a few working examples on 0.8.0.

```
import duckdb
from duckdb import CatalogException
import pyarrow as pa
import pyarrow.compute as pc

from duckdb.typing import *

con=duckdb.connect()

def plus_method_native(x, y):    
    return x+y

def plus_method_arrow(x, y):    
    return pc.add(x, y)

def plus_method_pandas(x, y):    
    table = pa.Table.from_arrays([x,y], ["x", "y"])
    df = table.to_pandas()
    return df["x"] + df["y"]

con.create_function('plus_lambda', lambda x,y: pc.add(x, y), [BIGINT, BIGINT], BIGINT, type='arrow')
con.create_function('plus_method_native', plus_method_native, [BIGINT, BIGINT], BIGINT, type='native')
con.create_function('plus_method_arrow', plus_method_arrow, [BIGINT, BIGINT], BIGINT, type='arrow')
con.create_function('plus_method_pandas', plus_method_pandas, [BIGINT, BIGINT], BIGINT, type='arrow')

res = con.sql('select plus_method_arrow(i, 3) from range(11) tbl(i)').fetchall()
print(res)

res = con.sql('select plus_method_native(i, 4) from range(11) tbl(i)').fetchall()
print(res)

res = con.sql('select plus_lambda(i, 5) from range(11) tbl(i)').fetchall()
print(res)

res = con.sql('select plus_method_pandas(i, 6) from range(11) tbl(i)').fetchall()
print(res)

con.remove_function('plus_method_arrow')

# exception_handling='return_null': Returns null on exception
# null_handling='special': bypasses to return null on null input

try:
    res = con.sql('select plus_method_arrow(i, 3) from range(11) tbl(i)').fetchall()
    print(res)
except CatalogException as e:
    print("Success: CatalogException because we removed the function")
```

### OS:

Windows

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! I have updated the PR message and linked to the [docs](https://duckdb.org/docs/api/python/function).
