### ISSUE TITLE
Rows not counted for read_csv + parallel=true

### ISSUE THREAD

**Issue by poundifdef** [duckdb/duckdb#7578]
### What happens?

When calling `read_csv(..., parallel=true)` on a relatively large file, not all rows are returned. However, when `parallel=false` then all rows are returned as expected.

Tested on Linux and OSX.

### To Reproduce

Consider the attached `sample.csv` file. It has 1,000 lines including the header: [sample.csv](https://github.com/duckdb/duckdb/files/11510784/sample.csv)

Then run:

``` sql
select count(*) 
from  read_csv('sample.csv', delim='\t', header=true, columns={
  'transaction_id': 'VARCHAR', 
  'team_id': 'INT', 
  'direction': 'INT',
  'amount':'DOUBLE',
  'account_id':'INT',
  'transaction_date':'DATE',
  'recorded_date':'DATE',
  'tags.transaction_id':'VARCHAR',
  'tags.team_id':'INT',
  'tags':'varchar'
},
parallel=true)
```

Output:

```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│          500 │
└──────────────┘
```

The expected result is `999` (1000 lines - 1 header line) When I pass `parallel=false` then I do get the correct result.

### OS:

Ubuntu 22.04.1 LTS (amd64)

### DuckDB Version:

v0.8.0 e8e4cea5ec

### DuckDB Client:

CLI

### Full Name:

Jay Goel

### Affiliation:

Journalize.io

### Have you tried this on the latest `master` branch?

Tested on OSX + CLI `v0.8.0 e8e4cea5ec`

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
Hi @poundifdef the issue here is that you also must set the quote option, by default the quote option is `"` which is not the correct option for your dataset and causes the Parallel CSV Reader to incorrectly skip lines.

Regardless of that, the Parallel CSV Reader should throw an error instead when not able to fully read the file, I'll patch that.
