### ISSUE TITLE
ipywidgets is required to set progress bar setting

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#7590]
### What happens?

In ibis, we're trying to support duckdb 0.8.0 but one of the default settings we have is to turn off progress bars because they cause Jupyter to crash (perhaps worth a separate bug report).

As of 0.8.0 though, we can't set this setting unless `ipywidgets` is installed.

Here's a CI run where this fails (it's building our docs which run notebooks): https://github.com/ibis-project/ibis/actions/runs/5023424100/jobs/9007997235?pr=6241

This is a bit odd since that means to set a setting I now have to install a package that may never be used, instead of the previous behavior which was to set the the setting and use it when ipywidgets is installed and the appropriate widget is used in the notebook.

### To Reproduce

Try to turn off the progress bar in a notebook without ipywidgets installed.

### OS:

Linux x86_64

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by cpcloud** [comment]
I have not tried this on the latest `master` branch.

**Comment by Tishj** [comment]
You shouldn't have to disable progress bars anymore to stop the jupyter crash, that's exactly what this requirement is for.

We can only support progress bars on Jupyter with ipywidgets installed, if it's not found we won't enable progress bars

**Comment by cpcloud** [comment]
Ah, that makes sense. Thanks for the speedy reply.

**Comment by cpcloud** [comment]
The remaining issue with the more strict setting is that it's not backwards compatible, which isn't a huge deal since we can work around this in ibis.
