### ISSUE TITLE
`list` aggregate function distinct order by combination breaking

### ISSUE THREAD

**Issue by jpmmcneill** [duckdb/duckdb#7614]
### What happens?

The `list` aggregate function throws an error when distinct and order by are combined:
```
Invalid Input Error: Function "list_sort" is a Scalar Function. "DISTINCT", "FILTER", and "ORDER BY" are only applicable to aggregate functions.
```

This only seems to happen when the `order by` hits the same column as the `distinct`. See the bottom two examples below.

### To Reproduce

```sql
-- WORKS
select id, list(distinct foo) from (
  values (1, '10'), (1, '15'), (2, '10')
) v (id, foo)
group by all;
```

```sql
-- WORKS
select id, list(foo order by foo) from (
  values (1, '10'), (1, '15'), (2, '10')
) v (id, foo)
group by all;
```

```sql
-- BREAKS
select id, list(distinct foo order by foo) from (
  values (1, '10'), (1, '15'), (2, '10')
) v (id, foo)
group by all;
```

```sql
-- WORKS
select id, list(distinct foo order by bar) from (
  values (1, '10', 1), (1, '15', 2), (2, '10', 1)
) v (id, foo, bar)
group by all;
```

### OS:

Mac

### DuckDB Version:

0.8 (also master)

### DuckDB Client:

Python

### Full Name:

James McNeill

### Affiliation:

Conjura

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jpmmcneill** [comment]
As usual, I'm happy to submit a PR rather than an issue if someone points me in the right direction!

**Comment by taniabogatsch** [comment]
I will have a look at this. :)
