### ISSUE TITLE
[Extension] Debug build throws InternalException on dynamic extension load.

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#7617]
### What happens?

When loading an extension that was not statically linked, symbols appear to be missing as `dynamic_cast` (incorrectly) fails even when the object is of the right type.

This causes an assertion to fail and results in an InternalException.

Some notes from Mytherin on the issue:
> The issue is essentially that dynamic_cast doesn't recognize the types are correct because the type is duplicated (once in the extension, and once in the main DuckDB)
> It's an issue with how we build and distribute extensions and how they interact with the linker

### DuckDB Version:

master

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Most likely related to #6521

**Comment by Tishj** [comment]
fixed by #10925
