### ISSUE TITLE
Add a function to retrieve/compute the storage space used by a single table

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#7622]
As a work-around, the current SQL query can be used:

```sql
SELECT format_bytes(COUNT(DISTINCT block_id) * 256000) AS storage_space
FROM pragma_storage_info('table_name');
```

But it would be a lot easier if there was a `table_size` pragma that could be used for this purpose. Postgres offers the `pg_table_size `, `pg_indexes_size `, `pg_total_relation_size` functions for this purpose.

**Comment by 29swastik** [comment]
@Mytherin getting below error for the above query

```py
duckdb.CatalogException: Catalog Error: Scalar Function with name format_bytes does not exist!
Did you mean "format_type"?
LINE 1: SELECT format_bytes(COUNT(DISTINCT block_id) *...
```

**Comment by Mause** [comment]
@29swastik `format_bytes` was added in 0.8.0, which version are you using?

**Comment by Mytherin** [comment]
Are you using the latest DuckDB version?

**Comment by 29swastik** [comment]
cool, I'm using `0.7.1`. Will update and check
