### ISSUE TITLE
Expected Error when Referencing Col0.something when Col0 is a null field

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#7625]
### What happens?

I expected an error when selecting "column.value" when column is a null type. 

I'm assuming this is because it's assumed to be a struct or something similar, and am a unclear on whether this is by design or not. 

### To Reproduce

I was surprised to receive a null result from the following query, rather than an error: 
```
WITH mytable as (select null as col0)
   select col0.something from mytable 
```
![image](https://github.com/duckdb/duckdb/assets/104510378/e548fbc5-d834-472b-90ba-6871c4bc9d38)

Postgres returns an error for this case: https://dbfiddle.uk/AHkWrS28

The case that caused me to notice this was something like the following, where I was selecting a column that didn't exist: 
```
WITH mytable as (select null as mytable)
   select mytable.something from mytable 
```

### OS:

Windows

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think expressions like `col0.something` get turned into a struct extract if it fails to bind as a qualified column reference, and NULL can be cast to anything, so no error is thrown

**Comment by paultiq** [comment]
I would've expected it to error. I don't really feel strongly, just seemed erroneous to treat a null as a struct, but I can see why it's ambiguous and fine.

(so, totally agree with closing this)
