### ISSUE TITLE
Query results changed in latest release (0.8.0)

### ISSUE THREAD

**Issue by neelasha23** [duckdb/duckdb#7634]
### What happens?

Ordering of tuples changed in version 0.8.0 as compared to version 0.7.1. In a particular case the result on Mac is different than in Linux / Windows.

### To Reproduce

Let's consider a simple data containing null values. The csv looks like: `"name,age\nDan,33\nBob,19\nSheri,"`. The below query returns different results in the latest release.

Version 0.7.1 result : [(None, 1), (18.76, 1), (32.760000000000005, 1)]
Version 0.8.0 result: [(18.76, 1), (32.760000000000005, 1), (None, 1)]

```
select
floor("age"/0.28)*0.28 as bin,
count(*) as count
from "data.csv"
group by bin
order by bin;
```

One particular query is returning different results on Mac vs Linux/Windows. Dataset : https://raw.githubusercontent.com/tidyverse/ggplot2/main/data-raw/diamonds.csv
Query is something like this:
```

        SELECT color,
        SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 0.0                  THEN 1 ELSE 0 END) AS "0.0", 
        SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 1849.7                  THEN 1 ELSE 0 END) AS "1849.7", 
        SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 3699.4                  THEN 1 ELSE 0 END) AS "3699.4", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 5549.1                  THEN 1 ELSE 0 END) AS "5549.1", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 7398.8                  THEN 1 ELSE 0 END) AS "7398.8", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 9248.5                  THEN 1 ELSE 0 END) AS "9248.5", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 11098.2                  THEN 1 ELSE 0 END) AS "11098.2", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 12947.9                  THEN 1 ELSE 0 END) AS "12947.9", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 14797.6                  THEN 1 ELSE 0 END) AS "14797.6", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 16647.3                  THEN 1 ELSE 0 END) AS "16647.3", SUM(CASE WHEN FLOOR(price/1849.7)*1849.7 = 18497.0                  THEN 1 ELSE 0 END) AS "18497.0",
        FROM "diamonds.csv"
        GROUP BY color;
```

Previously it was returning `     [('E', 5180, 1974, 1205, 505, 252, 219, 176, 109, 96, 76, 5), ('I', 1675, 1017, 931, 481, 290, 320, 161, 162, 209, 164, 12), ('J', 697, 528, 574, 250, 271, 93, 138, 127, 74, 46, 10), ('H', 2974, 1305, 1657, 855, 394, 304, 304, 176, 140, 175, 20), ('F', 4130, 2031, 1340, 666, 431, 313, 223, 165, 110, 112, 21), ('G', 4997, 1978, 1242, 1079, 714, 408, 280, 247, 179, 138, 30), ('D', 3425, 1366, 921, 392, 197, 156, 120, 77, 63, 53, 5)]`.

With latest master branch it returns :  `    [('H', 2974, 1305, 1657, 855, 394, 304, 304, 176, 140, 175, 20), ('G', 4997, 1978, 1242, 1079, 714, 408, 280, 247, 179, 138, 30), ('D', 3425, 1366, 921, 392, 197, 156, 120, 77, 63, 53, 5), ('F', 4130, 2031, 1340, 666, 431, 313, 223, 165, 110, 112, 21), ('I', 1675, 1017, 931, 481, 290, 320, 161, 162, 209, 164, 12), ('E', 5180, 1974, 1205, 505, 252, 219, 176, 109, 96, 76, 5), ('J', 697, 528, 574, 250, 271, 93, 138, 127, 74, 46, 10)]`.

Please refer to this CI fail: https://github.com/ploomber/jupysql/actions/runs/5031922452/jobs/9025272836

### OS:

Mac

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

Neelasha Sen

### Affiliation:

Ploomber

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rsund** [comment]
It seems that you may have a query with both [two breaking changes in DuckDB 0.8.0](https://duckdb.org/2023/05/17/announcing-duckdb-080.html).

You could try to:
```sql
SET integer_division=true;
SET default_null_order='nulls_first';
```

No idea why query results would be different in Mac vs. Linux/Windows.

**Comment by Mytherin** [comment]
Thanks for the report! As mentioned in the blog post and release notes - the different query results here seem to be the result of an intentional change to the SQL dialect. You can revert the dialect back using the options provided.
