### ISSUE TITLE
Add cast from `INT` (numeric) types to `BIT` type

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#7640]
First suggested in #7598 

Add casts to [BIT](https://duckdb.org/docs/sql/data_types/bitstring) from:
- SMALLINT
- USMALLINT
- TINYINT
- UTINYINT
- INTEGER
- UINTEGER
- BIGINT
- UBIGINT
- HUGEINT
- BLOB

Example of a query that should work:

`SELECT 42::BIT;`

**Comment by l1t1** [comment]
and from the bit to int
```
D select '1'::bit;
┌──────────────────┐
│ CAST('1' AS BIT) │
│       bit        │
├──────────────────┤
│ 1                │
└──────────────────┘
D select '1'::bit::int;
Error: Conversion Error: Unimplemented type for cast (BIT -> INTEGER)
``
