### ISSUE TITLE
Cannot query from RecordBatchStreamReader - InvalidInputException

### ISSUE THREAD

**Issue by gerrymanoim** [duckdb/duckdb#7647]
### What happens?

https://duckdb.org/docs/guides/python/sql_on_arrow#apache-arrow-recordbatchreaders links to https://arrow.apache.org/docs/python/generated/pyarrow.ipc.RecordBatchStreamReader.html which makes me think I should be able to query from a `RecordBatchStreamReader`. 

However, when I attempt to do so I get an `InvalidInputException`. 

```
InvalidInputException: Invalid Input Error: Python Object "reader" of type "RecordBatchStreamReader" found on line ".../ipykernel_935072/599824371.py:1" not suitable for replacement scans.
Make sure that "reader" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format
```

I'm not sure if this is a bug or just my misreading of the documentation. 

### To Reproduce

A contrived example

```python
import pyarrow as pa
import duckdb 
import pandas as pd
import numpy as np

table = pa.table({"a": range(10), "b": np.random.randn(10), "c": [1, 2] * 5})

sink = pa.BufferOutputStream()
writer = pa.ipc.new_stream(sink, table.schema)

for batch in table.to_batches():
    writer.write_batch(batch)

writer.close()

buff = sink.getvalue()

reader = pa.ipc.RecordBatchStreamReader(buff)

duckdb.execute("select * from reader")
```

### OS:

x86

### DuckDB Version:

8.0.0

### DuckDB Client:

8.0.0

### Full Name:

Gerry Manoim

### Affiliation:

Two Sigma

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
This issue is already fixed in the latest release.
