### ISSUE TITLE
Undocumented IF folds to CASE WHEN

### ISSUE THREAD

**Issue by jkew** [duckdb/duckdb#7655]
### What happens?

IF(cond, x, y) works in DuckDB and it is implemented [here](https://github.com/duckdb/duckdb/blob/a81a31a0af24a6ecbfd402c88cd1fb671f8cd3c8/src/parser/transform/expression/transform_function.cpp#L275). 

It was implemented in https://github.com/duckdb/duckdb/issues/156

Maybe this can be documented?

### To Reproduce

SELECT IF(FALSE, 1, 0);

### OS:

OSX

### DuckDB Version:

0.8

### DuckDB Client:

cli

### Full Name:

John Victor Kew II

### Affiliation:

Ponder Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue, but since it relates to docs, I think it belongs in https://github.com/duckdb/duckdb-web instead :)

**Comment by jkew** [comment]
Ahh thanks. I will raise it there.
