### ISSUE TITLE
WAL Replay fails when attach alias changes

### ISSUE THREAD

**Issue by bleskes** [duckdb/duckdb#7659]
### What happens?

It seems that the current WAL reply logic is dependent on the catalog name that used when the WAL record were entered. That is a problem,  as the name can change when the file is open. If that happens, you will get the following output:
```
Exception in WAL playback: Binder Error: Catalog "test" does not exist!
```

Also, the opening command won't fail, but the data would be lost. I think this type of issues should result in an error. 

### To Reproduce

Run the following in the CLI:
```
./duckdb_0.8.0 test.db
D create table tbl1 as select 1 as a;
```
kill the process, so the wal will stick around.

Start again and run:
```
» ./duckdb_0.8.0
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D attach 'test.db' as another_name;
Exception in WAL playback: Binder Error: Catalog "test" does not exist!
D select * from another_name.tbl1;
Error: Catalog Error: Table with name tbl1 does not exist!
Did you mean "system.information_schema.tables"?
LINE 1: select * from another_name.tbl1;
                      ^
```

### OS:

MacOS

### DuckDB Version:

0.8.0

### DuckDB Client:

cli

### Full Name:

Boaz Leskes

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Vegetable26** [comment]
Just a heads up it seems that this issue generally happens with any WAL replay with attach. 

I've attached a screenshot of another recent repro. 

<img width="1642" alt="Screen Shot 2023-05-24 at 11 25 44 AM" src="https://github.com/duckdb/duckdb/assets/8812233/bb4f9b3e-ff7d-4437-8bf8-0df9d4cb8abb">
