### ISSUE TITLE
Cannot cast `TIMESTAMP_NS` to `date` using `::` syntax

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#7672]
### What happens?

A cast of the form `<TIMESTAMP_NS>::date` will result in an error, whereas `<TIMESTAMP>::date` works, as does `date_trunc('day', <TIMESTAMP_NS>)`.

### To Reproduce

Works:
```sql
with tbl as (
    select
        '2023-01-01 00:00:00'::TIMESTAMP
        as c1
)
select c1::date
from tbl
```

Also works:
```sql
with tbl as (
    select
        '2023-01-01 00:00:00'::TIMESTAMP_NS
        as c1
)
select date_trunc('day', c1)
from tbl
```

But this doesn't work:
```sql
with tbl as (
    select
        '2023-01-01 00:00:00'::TIMESTAMP_NS
        as c1
)
select c1::date
from tbl
```
```
Conversion Error: Unimplemented type for cast (TIMESTAMP_NS -> DATE)
```

### OS:

Linux

### DuckDB Version:

0.8.1.dev96

### DuckDB Client:

Any

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by tobymao** [comment]
i'm getting this issue as well

```python
import duckdb
import pandas as pd

df = pd.DataFrame({"ds": ["2022-01-01"]})
df["ds"] = pd.to_datetime(df["ds"])

curr = duckdb.connect()

curr.execute("select cast(ds as date) from df").fetchdf()
```

ConversionException: Conversion Error: Unimplemented type for cast (TIMESTAMP_NS -> DATE)

**Comment by markbaydoun** [comment]
I am getting this error as well, using SQLAlchemy core's casts: `sa.cast(<col>, sa.DATE)`  results in `CAST(<col> AS DATE)`. Is there a current workaround while this is not implemented?

**Comment by hawkfish** [comment]
These types are supported for interoperability with Python and R, so there are some rough edges and oversights.
