### ISSUE TITLE
duckdb.Error: Argument index "0" out of range

### ISSUE THREAD

**Issue by tekumara** [duckdb/duckdb#7677]
### What happens?

duckdb.Error: Argument index "0" out of range

### To Reproduce

```
import duckdb

conn = duckdb.connect()
conn.execute("INSTALL httpfs;")
conn.execute("SELECT * FROM read_parquet('s3://foo/bar/*');")
```

or

```
❯ duckdb
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D INSTALL httpfs;
D SELECT * FROM read_parquet('s3://foo/bar/*');
Error: Invalid Error: Argument index "0" out of range
```

### OS:

Linux

### DuckDB Version:

0.8.0

### DuckDB Client:

Python / CLI

### Full Name:

Oliver Mannion

### Affiliation:

Xero

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by tekumara** [comment]
This doesn't occur if I have the `AWS_*` environment variables set. So possibly related to #5419 ?

**Comment by Mytherin** [comment]
Thanks for the report! The error `Argument index "0" out of range` comes from formatting an exception incorrectly internally - so this is likely hiding another exception that is being thrown.

**Comment by carlopi** [comment]
Here there are 2 separate issues, one that the dev oriented error should not mask the real one (that is `HTTP GET error on 'https://foo.s3.amazonaws.com/?encoding-type=url&list-type=2&prefix=bar%2F' (HTTP 403)`), and the second that the out-of-range error (while building the exception, so triggered only in the exceptional case) should not happen in the first place.

Thanks a lot for raising this, I think I have the fixes, will file them in a bit.
