### ISSUE TITLE
`duckdb.register` on aarch64: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb#7699]
### What happens?

In the Python interface, if I try to register a polars object having a column with categorical type in an aarch64 platform, DuckDB will throw an error about attempting to dereference a null pointer.

Swapping the call from `duckdb.register` to `duckdb.query` with "create view" doesn't error out immediately, but produces an error later on once a selection query is executed on the view.

Executing the same code on an amd64 platform doesn't produce any error, but I'm not sure if it's because the prebuilt wheels disable safety macros or because there is no error.

### To Reproduce

Code to reproduce:
```python
import polars as pl, duckdb, string
pl_tbl = pl.DataFrame({
    "col1" : pl.Series([
        string.ascii_uppercase[ix+10] for ix in list(range(2)) + list(range(3))
    ]).cast(pl.Categorical),
})

nickname = "df1234"
duckdb.register(nickname, pl_tbl)
```

In case it helps, a Dockerfile to execute it on amd64 through qemu (assuming the file is saved as `crasher.py`):
```
FROM arm64v8/debian:bullseye
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install python3 python3-pip gcc g++
RUN python3 -m pip install polars pyarrow
RUN python3 -m pip install --pre duckdb
COPY crasher.py /crasher.py
ENTRYPOINT ["python3", "/crasher.py"]
```

### OS:

Linux

### DuckDB Version:

0.8.1.dev96

### DuckDB Client:

Python

### Full Name:

David Cortes

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
> Executing the same code on an amd64 platform doesn't produce any error, but I'm not sure if it's because the prebuilt wheels disable safety macros or because there is no error.

Since 0.8.0 we enable all safety macros in release builds, so that shouldn't be the case.

**Comment by Tishj** [comment]
I can reproduce it 👍 
```
root@7335eb990cba:/app/duckdb# python3 tmp/register_crash.py 
Traceback (most recent call last):
  File "/app/duckdb/tmp/register_crash.py", line 10, in <module>
    duckdb.register(nickname, pl_tbl)
duckdb.InternalException: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!
```
