### ISSUE TITLE
simple "explain" does not generate json

### ISSUE THREAD

**Issue by marhar** [duckdb/duckdb#7703]
### What happens?

"explain select ..." does not show json output if `PRAGMA enable_profiling='json'` is set.

"explain analyze select ..." does produce json output.

```
% duckdb
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.


D PRAGMA enable_profiling='json';
D explain select 1 as a;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             a             │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘                             
```

### To Reproduce

```
PRAGMA enable_profiling='json';
-- does not generate json output.  (explain select does generate json output)
explain select 1 as a;
```

### OS:

MacOS

### DuckDB Version:

0.8.0

### DuckDB Client:

CLI

### Full Name:

Mark Harrison

### Affiliation:

TigerEye

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

As indicated by the setting name - `enable_profiling` only concerns profiling information, not explain output. We do not support emitting explain output in JSON currently. Feel free to open a feature request.
