### ISSUE TITLE
PRAGMA profile_output= does not redirect profile output

### ISSUE THREAD

**Issue by marhar** [duckdb/duckdb#7704]
### What happens?

Setting `PRAGMA profile_output` does not send the profiling output to the specified file.
Regardless of this setting, profiling output is sent to stdout.

```
% duckdb
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.


D PRAGMA enable_profiling='json';
D PRAGMA profile_output='explain-output.json';
D explain analyze select 1 as a;

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
{
   "name":  "Query", 
   "result": 0.000034,
   "timing": 0.000036,
   "cardinality": 0,
   "extra-info": "explain analyze select 1 as a;", 
   "timings": [
...
}D 

ls *.json
zsh: no matches found: *.json
```

### To Reproduce

```
PRAGMA enable_profiling='json';
PRAGMA profile_output='explain-output.json';
explain analyze select 1 as a;
```

### OS:

MacOS

### DuckDB Version:

0.8.0

### DuckDB Client:

CLI

### Full Name:

Mark Harrison

### Affiliation:

TigerEye

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This seems like a documentation issue - as this is expected behavior. `EXPLAIN ANALYZE` returns the results as a query result. `PRAGMA enable_profiling` writes the profiling result to stdout/a file *in addition to providing the normal query result*. You cannot use both at the same time.

What you are likely looking for is this:

```sql
PRAGMA enable_profiling='json';
PRAGMA profile_output='explain-output.json';
select 1 as a;
```
