### ISSUE TITLE
CSV parsing fails when a properly-quoted field has a terminal newline

### ISSUE THREAD

**Issue by kemiller** [duckdb/duckdb#7706]
### What happens?

We were getting parse errors loading a CSV file despite it being generated by well-tested library, and looking right.  Here it is:

```
month,bart_row_id,emissions_model_evaluation_id,bart_instance_id,emissions_model_namespaced_variable_name,emissions_calculation_description,emissions_business_activity_data,emissions_reference_data,ef_source,ef_name,kg_co2e,converted_quantity,converted_quantity_unit,ef_kg_co2e,ef_kg_co2e_unit,location_kg_co2e,location_converted_quantity,location_converted_quantity_unit,location_ef_kg_co2e,location_ef_kg_co2e_unit,location_emissions_calculation_description,location_ef_source,location_ef_name
1640995200000,1,eme_2mQ4eQ1v5rtTWyvNLhFH,bart_2gs4ePygxSEpdDvZvzZh,emissions@capital_expenditure,((56 [spend] * 0.7911079466793245 USD) [exchange_rate]) * 2 kgco2e/USD) [emissions_factor]),"quantity = 56

month = Sat Jan 01 2022 00:00:00 GMT+0000 (GMT)","value of forex = 1
",,,88.60409002808434,44.30204501404217,USD,2,kgco2e/USD,,,,,,,,
```

Note the line `"value of forex = 1` which has a newline and then a double-quote terminator following the newline.  This, as far as I'm aware, should be valid CSV.  Removing the newline makes it work.  Adding a space right after the newline also makes it work. 
 

### To Reproduce

Simply save the text above as a CSV file and try to scan it in the db.  Should give you an error like this:

<img width="1036" alt="image" src="https://github.com/duckdb/duckdb/assets/6359/7a3a5147-243d-4d27-b3c7-5c05906b1b3c">

### OS:

macOS

### DuckDB Version:

0.7.1 + 0.8.0

### DuckDB Client:

command line and typescript

### Full Name:

Ken Miller

### Affiliation:

Watershed (Silver sponsor)

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [ ] I agree

**Comment by paultiq** [comment]
Don't have much to add, but I see that there's a quoted newline test case / file, and it returns what I expect:

`duckdb.execute("select * from 'mypath\\duckdb\\test\\sql\\copy\\csv\\data\\test\\quoted_newline.csv'").df()`

**Comment by kemiller** [comment]
No, that month is part of the line two up — that field has multiple newlines.

**Comment by paultiq** [comment]
Ah, I didn't read the error message carefully: it's detecting the wrong delimiter:
> delimiter = '|'

Try this: 
`duckdb.execute("select * from read_csv_auto('yourfile.csv', delim=',')").df()`

**Comment by Tishj** [comment]
For reference, this is the same reproduction without needing to make a file
```py
import duckdb
from io import StringIO
text = StringIO("""
a,"b
",c
""")

print("Trying comma delim")
print(duckdb.read_csv(text, header=False, sep=",").df())
print("Able to read with delim=,")
print("Trying auto")
print(duckdb.read_csv(text, header=False).df())
```
