### ISSUE TITLE
The table disappears after 30 minutes of work

### ISSUE THREAD

**Issue by DipDeepCode** [duckdb/duckdb#7708]
### What happens?

I'm trying to use DuckDB to read parquet files in Spring Boot application using jdbcTemplate.  
I am creating a table from a parquet file using the command:  
```
CREATE TABLE test AS SELECT * FROM 'test.parquet';
```
After 30 minutes of stable operation, the test table disappears and I get an error:  
```
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [SELECT "ЭКСГАУСТЕР 4. ТОК СТАТОРА" FROM test WHERE DT BETWEEN '2023-01-10 00:20:13' AND '2023-01-10 08:50:13';]; SQL state [null]; error code [0]; java.sql.SQLException: Catalog Error: Table with name test does not exist!
Did you mean "system.information_schema.tables"?
```

### To Reproduce

Create Spring Boot project (version 2.7.12, java 17 with JDBC API dependency) that  
Execute the command using JdbcTemplate:  
```
CREATE TABLE test AS SELECT * FROM 'test.parquet';
```
After 30 minutes, run the command using JdbcTemplate
```
SELECT ... FROM test WHERE ...;
```
And get an error

### OS:

windows 10, windows 11

### DuckDB Version:

0.8.0

### DuckDB Client:

spring boot jdbc

### Full Name:

Sergey Kovalev

### Affiliation:

SkillFactory

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
I only dabble nowadays with Java, but this sounds like a connection pool issue: If you're using default config, and an in memory db, spring boot uses a connection pool by default. My setup used hikari, not sure if that's always the default. In this case, the connection pool may be timing out: and if it's an in memory database, that's essentially dropping your db and starting fresh. You could either bypass the cp or set the appropriate timeout to infinite, or not use a cp, or use duckdb with a file based target?

**Comment by DipDeepCode** [comment]
@paultiq Yes! Thank you very much! I used duckdb with a file based target. Now everything works without problems.
I think I can close this question.
