### ISSUE TITLE
Database Invalidated (previous fatal error) when loading multiple json into table

### ISSUE THREAD

**Issue by meghfossa** [duckdb/duckdb#7710]
### What happens?

Running into following error consistently;

```
Error: INTERNAL Error: Could not find node in column segment tree!
```

### To Reproduce

1. Create directory called sample (`mkdir sample`)
```
>> mkdir sample

# line-delim jsons
>> echo '{"name": "a", "ts": 100}\n{"name": "b", "ts": 10}\n' > sample/1.json
>> echo '{"name": "a", "ts": 100}\n{"name": "b", "ts": 10}\n' > sample/2.json
```

2. Start duck db: `duckdb`

```sql
create table if not exists sample(name STRING PRIMARY KEY, ts INTEGER);
insert or replace into sample (select * from 'sample/*.json');
```

This produces error:
```
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table if not exists sample(name STRING PRIMARY KEY, ts INTEGER);
D insert or replace into sample(select * from 'sample/*.json');
Error: INTERNAL Error: Could not find node in column segment tree!
Attempting to find row number "4611686018427388000" in 1 nodes
Node 0: Start 4611686018427388000, Count 0
```

This breaks the database, and I can't perform any more actions. 

My usecase for this action is to, load bunch of dataset, into single table, while dropping duplicates based 
on the key.

For example,
```
- fileA.json
- fileB.json
- ...
- ....
```

and only preserve unique rows (by key of 'name'), and when conflict does arise, it should prefer row with larger ts. Is an alternative way to achieve this without using defective `insert or replace into sample (select * from 'sample/*.json')`?

### OS:

macOS

### DuckDB Version:

v0.8.0 e8e4cea5ec

### DuckDB Client:

duckdb terminal

### Full Name:

Megh

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by meghfossa** [comment]
Update, doing insert sequentially works!

```sql
INSERT or replace INTO sample SELECT * FROM read_json_auto('sample/1.json');
INSERT or replace INTO sample SELECT * FROM read_json_auto('sample/2.json');
select * from sample;
```

**Comment by Mause** [comment]
This looks like a duplicate of https://github.com/duckdb/duckdb/issues/3789
