### ISSUE TITLE
bogus error about parquet compression format

### ISSUE THREAD

**Issue by pkit** [duckdb/duckdb#7719]
### What happens?

```
D SELECT * FROM read_parquet('/tmp/data.parquet') ;
Error: Invalid Error: Unsupported compression codec "7". Supported options are uncompressed, gzip, snappy or zstd
D 
```
Yes, `lz4` seems to be not supported but that's compression codec "5" and not "7".
Compression codec "7" doesn't even exist in the actual parquet format, see [here](https://github.com/apache/parquet-format/blob/54e6133e887a6ea90501ddd72fff5312b7038a7c/src/main/thrift/parquet.thrift#L461).

Just FYI, how that file looks in `pyarrow`
```ipython
>>> import pyarrow.parquet as pq
>>> parquet_file = pq.ParquetFile('/tmp/data.parquet')
>>> parquet_file.metadata.row_group(0).column(0)
<pyarrow._parquet.ColumnChunkMetaData object at 0x7fea0ebd2a40>
  file_offset: 60
  file_path: 
  physical_type: INT32
  num_values: 1
  path_in_schema: 1
  is_stats_set: True
  statistics:
    <pyarrow._parquet.Statistics object at 0x7fea0e995ae0>
      has_min_max: True
      min: 1
      max: 1
      null_count: 0
      distinct_count: 0
      num_values: 1
      physical_type: INT32
      logical_type: Int(bitWidth=8, isSigned=false)
      converted_type (legacy): UINT_8
  compression: LZ4
  encodings: ('RLE_DICTIONARY', 'PLAIN', 'RLE')
  has_dictionary_page: True
  dictionary_page_offset: 4
  data_page_offset: 23
  total_compressed_size: 56
  total_uncompressed_size: 54
>>> pq.read_table('/tmp/data.parquet')
pyarrow.Table
1: uint8 not null
'aaa': binary not null
3.14: double not null
----
1: [[1]]
'aaa': [[616161]]
3.14: [[3.14]]

```

### To Reproduce

1. Create a parquet file with `lz4` compression format.
2. Try to load it into `duckdb`

### OS:

Linux 5.15.0-71-generic #78-Ubuntu SMP x86_64

### DuckDB Version:

v0.8.0 e8e4cea5ec

### DuckDB Client:

CLI

### Full Name:

Constantine Peresypkin

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
LZ4_RAW is 7, see master: https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L498

**Comment by pkit** [comment]
Nice! Thanks.
