### ISSUE TITLE
Pivot not working with prepared statements with C API

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#7720]
### What happens?

Trying to run a query that uses PIVOT error I get an error from Duckdb.

The statement looks like this: `PIVOT Cities ON Year USING SUM(Population);` taken from [Pivot Statement page](https://duckdb.org/docs/sql/statements/pivot#pivot-on-and-using)

If I call `duckdb_prepare` I get this error: `Invalid Error: Cannot prepare multiple statements at once!`

If I call `duckdb_extract_statements` it returns two, `duckdb_prepare_extracted_statement` succeeds for the first statement but for the second one it fails with the following error:

`Catalog Error: Type with name __pivot_enum_0_0 does not exist!
Did you mean "enum"?
`

### To Reproduce

Use C API to create the following table `CREATE TABLE Cities(Country VARCHAR, Name VARCHAR, Year INT, Population INT)` and run `PIVOT Cities ON Year USING SUM(Population);` query

### OS:

Windows

### DuckDB Version:

0.8.0, tried with v0.8.1-dev152 too

### DuckDB Client:

C# client via C API

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Giorgi** [comment]
Reading the [Internals](https://duckdb.org/docs/sql/statements/pivot#internals) behind Pivot I think I know what's going on. The query with Pivot is rewritten as

```sql
CREATE TEMPORARY TYPE __pivot_enum_0_0 AS ENUM (
    SELECT DISTINCT 
        Year::VARCHAR 
    FROM Cities 
    ORDER BY 
        Year
    );
PIVOT Cities ON Year IN __pivot_enum_0_0 USING SUM(Population);
```

so that's why `duckdb_prepare` complains about preparing multiple statements and `duckdb_prepare_extracted_statement` fails for preparing the second statement because, in the C# library implementation, I prepare all extracted statements first and then execute them if all of them succeed.

On the other hand, as translating the Pivot statement into another representation is an implementation detail, I wouldn't expect the internals to be exposed by the C Api. I think `duckdb_prepare` should be able to prepare Pivot queries and `duckdb_extract_statements` to return 1 instead of 2

**Comment by Giorgi** [comment]
I already call `duckdb_extract_statements` and prepare the statements that it extracts, the thing is that in the current implementation, I first prepare all the extracted statements and then I execute if `duckdb_prepare_extracted_statement` succeeded for all of the extracted statements. Because of this `duckdb_prepare_extracted_statement` fails for the statement because it cannot find `__pivot_enum_0_0` because I have prepared but not executed

```
CREATE TEMPORARY TYPE __pivot_enum_0_0 AS ENUM (
    SELECT DISTINCT 
        Year::VARCHAR 
    FROM Cities 
    ORDER BY 
        Year
    );
```

**Comment by Mytherin** [comment]
There's not really any way around that since the second statement refers to the first - the first statement has to be executed before the second one is prepared.

**Comment by Giorgi** [comment]
Can you extend `duckdb_extract_statements` to return information about the number of statements it extracted because of translating the given query to multiple statements versus the original query containing multiple statements from the start?

**Comment by Giorgi** [comment]
I changed the implementation in the .Net library and it now calls `duckdb_prepare_extracted_statement` followed by `duckdb_execute_prepared` for all statements extracted by `duckdb_extract_statements` But because of this change, it's now not possible anymore to prepare a statement once and execute it multiple times with different parameter values.

Previously you could do it like this:

```cs
var command = connection.CreateCommand();
command.CommandText = "SELECT * from integers where foo > ?;";
command.Prepare();

command.Parameters.Add(new new DuckDBParameter(4));
var reader = command.ExecuteReader();

command.Parameters.Clear();
command.Parameters.Add(new new DuckDBParameter(24));
reader = command.ExecuteReader();
```

The command would be prepared once but executed multiple times for different values of parameters. With the change, I can no longer prepare but not execute because if the statement is a Pivot statement it requires executing all statements. Maybe there is some way to allow preparing the second statement in Pivot without executing the previous one? I know that the second statement depends on the Enum created by the previous statement but, for example in Oracle, you can create a view without creating underlying tables (the tables need to exist when you select from view). Maybe you could do something like that when preparing Pivot statements?

From [CREATE VIEW:](https://docs.oracle.com/cd/B13789_01/server.101/b10759/statements_8004.htm)

> Specify FORCE if you want to create the view regardless of whether the base tables of the view or the referenced object types exist or the owner of the schema containing the view has privileges on them.

**Comment by Giorgi** [comment]
@Mytherin There is also another problem with this approach. As I'm building a library, I have no idea to know if the current statement being executed is a PIVOT statement that results in two statements or two queries in a single statement: `Select * from Foo; Select * from Bar` In both cases I get two `duckdb_result`-s but in case of PIVOT I don't really need the first one and should only expose the second one to the user. Currently, there is no way for me to know whether both results are needed or not, and have to return both to the caller in both cases even though the user obviously expects one result when issuing a PIVOT statement.

**Comment by Giorgi** [comment]
It's not resolved but will be resolved when https://github.com/duckdb/duckdb/discussions/8786 is added

**Comment by Giorgi** [comment]
Now that https://github.com/duckdb/duckdb/pull/9430 is merged I can determine which statement is create enum and which one is an actual query.
