### ISSUE TITLE
Index on union breaks database with `Invalid Type [UNION(...)]: Invalid type for index key` after it was created

### ISSUE THREAD

**Issue by rkusa** [duckdb/duckdb#7725]
### What happens?

Background: I have a union I'd like to create an index on. This, however, is not possible and the following example is rejected.

```sql
CREATE TABLE attributes (
    value UNION(
        "string" VARCHAR,
        "bool"   BOOLEAN
    ) NOT NULL
);

CREATE INDEX attributes__value ON attributes (value);
```

Error: `Error: near line 8: Invalid type Error: Invalid Type [UNION(string VARCHAR, bool BOOLEAN)]: Invalid type for index key.`

So instead, I thought I simply create an index per alternative value:

```sql
CREATE TABLE attributes (
    value UNION(
        "string" VARCHAR,
        "bool"   BOOLEAN
    ) NOT NULL
);

CREATE INDEX attributes__value_string ON attributes ((value.string::VARCHAR));
CREATE INDEX attributes__value_bool ON attributes ((value.bool::BOOL));
```

This works, until it doesn't. When I use this table (insert and select) from my program (which uses the [Rust bindings for DuckDB](https://github.com/wangfenjin/duckdb-rs); so basically the C bindings), it works fine. However, as soon as there is data in the table and I open the database once with the `duckdb` CLI, it breaks. After that, the database cannot be opened anymore. Neither from the CLI, nor using the C bindings.

I'd have expected to either:
- not be able to create the index in the first place,
- or that the CLI isn't breaking the database after the database and index were already successfully created.

### To Reproduce

With the following `init.sql`:

```sql
CREATE TABLE attributes (
    value UNION(
        "string" VARCHAR,
        "bool"   BOOLEAN
    ) NOT NULL
);

CREATE INDEX attributes__value_string ON attributes ((value.string::VARCHAR));
CREATE INDEX attributes__value_bool ON attributes ((value.bool::BOOL));
```

run in your console:

```bash
1) duckdb db.duckdb < init.sql

2) duckdb db.duckdb
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
CTRL+D

3) duckdb db.duckdb
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
D INSERT INTO attributes VALUES (true);
CTRL+D

4) duckdb db.duckdb
Error: unable to open database "db.duckdb": Invalid type Error: Invalid Type [UNION(string VARCHAR, bool BOOLEAN)]: Invalid type for index key.
```

1. Create the table and index
2. Open the database once to confirm that it works for now. Then close it.
3. Open the database again and insert some data. You can also select the data afterwards no problem (as long as you keep the same CLI session open). Then close it.
4. Trying to open the database again will now always fail with `Invalid Type [UNION(string VARCHAR, bool BOOLEAN)]: Invalid type for index key.`.

Again, this problem doesn't happen if the data is inserted by a program using the C bindings. In this case, it can close and open the database again and again no issue. Just as soon as the database is opened once with the CLI, it breaks.

### OS:

macOS arm64

### DuckDB Version:

v0.8.0 e8e4cea5ec (issue happens at least since v0.6.0)

### DuckDB Client:

CLI

### Full Name:

Markus Ast

### Affiliation:

-

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taniabogatsch** [comment]
I can reproduce the issue and I agree with this:
> I'd have expected to either:
> - not be able to create the index in the first place,

We currently don't support indexes on nested types, and we should also disable them for `UNION` (as they aren't tested/correctly working for these, either).

```sql
tania@motorbook duckdb % build/release/duckdb my.db  
v0.8.2-dev3190 3196df79ce
Enter ".help" for usage hints.
D CREATE TABLE attributes (
>     value UNION(
>         "string" VARCHAR,
>         "bool"   BOOLEAN
>     ) NOT NULL
> );
D 
D CREATE INDEX attributes__value_string ON attributes ((value.string::VARCHAR));
D CREATE INDEX attributes__value_bool ON attributes ((value.bool::BOOL));
D .q
tania@motorbook duckdb % build/release/duckdb my.db
v0.8.2-dev3190 3196df79ce
Enter ".help" for usage hints.
D INSERT INTO attributes VALUES (true);
D .q
tania@motorbook duckdb % build/release/duckdb my.db
Error: unable to open database "my.db": Invalid type Error: Invalid Type [UNION(string VARCHAR, bool BOOLEAN)]: Invalid type for index key.
```

Taken from `art.cpp`.
```cpp
	// validate the types of the key columns
	for (idx_t i = 0; i < types.size(); i++) {
		switch (types[i]) {
		case PhysicalType::BOOL:
		case PhysicalType::INT8:
		case PhysicalType::INT16:
		case PhysicalType::INT32:
		case PhysicalType::INT64:
		case PhysicalType::INT128:
		case PhysicalType::UINT8:
		case PhysicalType::UINT16:
		case PhysicalType::UINT32:
		case PhysicalType::UINT64:
		case PhysicalType::FLOAT:
		case PhysicalType::DOUBLE:
		case PhysicalType::VARCHAR:
			break;
		default:
			throw InvalidTypeException(logical_types[i], "Invalid type for index key.");
		}
	}
```
