### ISSUE TITLE
"duckdb.TypeMismatchException: Mismatch Type Error" using dicts with different set of keys in python

### ISSUE THREAD

**Issue by ea-rus** [duckdb/duckdb#7734]
### What happens?

In python duckdb module raises exception if  different sets of keys are using on 3rd level of dict.

The error exists on pip duckdb versions: 0.6.0, 0.7.0, 0.8.0
Version 0.5.0 raises Segmentation fault
Version 0.4.0 works fine 

### To Reproduce

This code 
```python
import duckdb
import pandas as pd
con = duckdb.connect(database=':memory:')

d = [
    {'a': 
       {'b': {
          'x': 'A', 
          'y': 'B'}}},
    {'a': 
       {'b': {
          'x': 'A'}}}
]

con.register('tbl', pd.DataFrame(d))
con.execute("SELECT * FROM tbl").fetchdf()
```
raises exception: 
`duckdb.TypeMismatchException: Mismatch Type Error: Type STRUCT(x VARCHAR) does not match with STRUCT(x VARCHAR, y VARCHAR). Cannot cast STRUCTs of different size`

### OS:

Ubuntu 22.04

### DuckDB Version:

0.8.0

### DuckDB Client:

python

### Full Name:

Andrey Elkin

### Affiliation:

Mindsdb

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
I assume 0.4.0 works fine because we didn't yet have `struct` support in DuckDB, so your data was probably stored as a varchar. I'd have to find a copy of 0.4.0 to confirm that. Once we had we started validating the input types, you started getting that error.

I guess we need to infer the column as a union now @Tishj?

**Comment by Mause** [comment]
Yep, in 0.4.0:
```python
>>> con.execute("DESCRIBE SELECT * FROM tbl").fetchall()
[('a', 'VARCHAR', 'YES', None, None, None)]
```

**Comment by ea-rus** [comment]
Strange, for me result is different...
```
>>> con.execute("SELECT * FROM tbl").fetchdf()
a
0  {'b': {'x': 'A', 'y': 'B'}}
1            {'b': {'x': 'A'}}
>>> con.execute("SELECT * FROM tbl").fetchall()
[("{'b': {'x': 'A', 'y': 'B'}}",), ("{'b': {'x': 'A'}}",)]
>>> duckdb.__version__
'0.4.0'
```

**Comment by Tishj** [comment]
I was thinking we might need to accept casting struct A to struct B if the children of A are a subset of B, and populate the other children with NULL.

**Comment by Tishj** [comment]
> I assume 0.4.0 works fine because we didn't yet have `struct` support in DuckDB, so your data was probably stored as a varchar. I'd have to find a copy of 0.4.0 to confirm that. Once we had we started validating the input types, you started getting that error.
> 
> I guess we need to infer the column as a union now @Tishj?

I'm not sure I follow entirely, what would the inferred type be in this case?

**Comment by Mause** [comment]
> Strange, for me result is different...
> 
> ```
> >>> con.execute("SELECT * FROM tbl").fetchdf()
> a
> 0  {'b': {'x': 'A', 'y': 'B'}}
> 1            {'b': {'x': 'A'}}
> >>> con.execute("SELECT * FROM tbl").fetchall()
> [("{'b': {'x': 'A', 'y': 'B'}}",), ("{'b': {'x': 'A'}}",)]
> >>> duckdb.__version__
> '0.4.0'
> ```

It isn't different, you ran a different SQL query, and missing the `DESCRIBE`

**Comment by Mause** [comment]
> > I assume 0.4.0 works fine because we didn't yet have `struct` support in DuckDB, so your data was probably stored as a varchar. I'd have to find a copy of 0.4.0 to confirm that. Once we had we started validating the input types, you started getting that error.
> > I guess we need to infer the column as a union now @Tishj?
> 
> I'm not sure I follow entirely, what would the inferred type be in this case?

A union of the two struct types perhaps? Depends on whether that's preferable to simply combining the keys of both and leaving the missing ones null?

**Comment by ea-rus** [comment]
Maybe this example is also related to this problem and can help somehow:
```
d=[
    {'a': {'b': {'xxxx': 'A'}}},
    {'a': {'b': {'yyyy': 'B'}}},
]
con.register('tbl', pd.DataFrame(d))
con.execute("SELECT * FROM tbl").fetchdf()
```
different keys (xxxx, yyyy) on input become the same key on output
```
a
0  {'b': {'xxxx': 'A'}}
1  {'b': {'xxxx': 'B'}}
```

**Comment by Mause** [comment]
> Maybe this example is also related to this problem and can help somehow:
> 
> ```
> d=[
>     {'a': {'b': {'xxxx': 'A'}}},
>     {'a': {'b': {'yyyy': 'B'}}},
> ]
> con.register('tbl', pd.DataFrame(d))
> con.execute("SELECT * FROM tbl").fetchdf()
> ```
> 
> different keys (xxxx, yyyy) on input become the same key on output
> 
> ```
> a
> 0  {'b': {'xxxx': 'A'}}
> 1  {'b': {'xxxx': 'B'}}
> ```

This sounds more like https://github.com/duckdb/duckdb/issues/7303

**Comment by Mause** [comment]
> @Mause The union idea would cover more cases than my idea, but I'm not sure if implicitly creating a union is the most user friendly.
> I might be wrong but working with a union is still not as easy as a regular struct

Fair point - I'm not sure what the alternative solution would be though? Aside from not fixing this

**Comment by Tishj** [comment]
Mytherin had a good idea, maybe we can turn this into a `MAP(VARCHAR, <combination_of_struct_child_types>)` if not all the structs children types can be combined into one, we might fall back to a `MAP(VARCHAR, UNION(..))` but I think I'll start of with just throwing in this case.
