### ISSUE TITLE
Error with Node.js in cluster mode

### ISSUE THREAD

**Issue by ataft** [duckdb/duckdb#7743]
### What happens?

DuckDB on nodejs fails to with "Connection was never established or has been closed already" when running in nodejs cluster mode

### To Reproduce

https://gist.github.com/ataft/42b7cc3d4055cf6b5a62a5f1f57da4b2

### OS:

Windows 11 x64

### DuckDB Version:

0.8.0

### DuckDB Client:

Node.js

### Full Name:

Andrew Taft

### Affiliation:

Flex Analytics, Inc

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
While the error message here isn't ideal (the real error message is probably being swallowed in the Database constructor callback),  the underlying issue is likely that you're trying to open multiple read/write connections to a single database file, which is not supported.

From https://duckdb.org/faq#how-does-duckdb-handle-concurrency

> DuckDB has 2 configurable options for concurrency. 1. One process can both read and write to the database. 2. Multiple processes can read from the database, but no processes can write ([access_mode = 'READ_ONLY'](https://duckdb.org/docs/sql/configuration#configuration-reference)).

When I add a log to the missing callback I get:
```
[Error: IO Error: Could not set lock on file "disk.db": Resource temporarily unavailable] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'IO'
}
```

But it works as expected when I pass the `duckdb.OPEN_READONLY` `accessMode` flag

**Comment by ataft** [comment]
Got it, thanks so much!

I updated the Gist to account for this: https://gist.github.com/ataft/42b7cc3d4055cf6b5a62a5f1f57da4b2

**Comment by rahilsondhi** [comment]
I ran @ataft 's gist and I'm still running into the same issue weirdly enough 🤔 

```
➜  duckdb-gist node cluster.js
Forked child
Forked child
Forked child
Forked child
dbPath mydb.db
accessMode READ_ONLY
dbPath mydb.db
accessMode READ_ONLY
Child done
Child done
dbPath mydb.db
accessMode READ_ONLY
Child done
dbPath mydb.db
accessMode READ_ONLY
Child done
undefined:0


[Error: Connection Error: Connection was never established or has been closed already] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'Connection'
}

Node.js v19.5.0
undefined:0


[Error: Connection Error: Connection was never established or has been closed already] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'Connection'
}

Node.js v19.5.0
undefined:0


[Error: Connection Error: Connection was never established or has been closed already] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'Connection'
}

Node.js v19.5.0
undefined:0


[Error: Connection Error: Connection was never established or has been closed already] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'Connection'
}

Node.js v19.5.0
➜  duckdb-gist
```

**Comment by loucadufault** [comment]
Just adding that I observe this same behaviour, but in my case changing to `access_mode: 'READ_ONLY'` was the cause of the problem. With `'AUTOMATIC'` mode there is no error. This is with the deprecated nodejs API so won't bother with an issue.
