### ISSUE TITLE
Querying is fast, printing result very slow

### ISSUE THREAD

**Issue by Tom-E** [duckdb/duckdb#7744]
### What happens?

Query is very fast (0.01sec), but printing the results of the query is slow (many seconds) no matter what I do.

How do I debug this? Is this expected? I can't find any information about this online, but given what I'm seeing I'm doubting that the query is running at all, as serializing a single row shouldn't take multiple seconds in comparison.

This is query a table created against a ~5GB parquet file on a very capable server file with:

`CREATE VIEW my_table AS SELECT * FROM '{my_data}/my_table.parquet'`

### To Reproduce

```
start = time.time()
result = duckdb.query(f"""select * from my_table where key = '123' and date = '2023-01-01';""")
print(f"took {time.time() - start:.2f} seconds")
start = time.time()
print(result)
print(f"took {time.time() - start:.2f} seconds")
```

Results:
```
took 0.01 seconds
<1 row printed>
took 5.43 seconds
```

### OS:

osx

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Tom-E

### Affiliation:

n/a

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tom-E** [comment]
I suspected this was somehow the case, but then how can I actual profile what's going on?

If i do `duckdb.query(f"""EXPLAIN ANALYZE select * from my_table where key = '123' and date = '2023-01-01';""")` I only get information about the 0.01sec of time, and I want to profile what's taking 5seconds and how to improve it.

**Comment by Tom-E** [comment]
my mistake, looks like I am now seeing the full 5sec+ duration in `Query Profiling Information `

**Comment by wilful** [comment]
> my mistake, looks like I am now seeing the full 5sec+ duration in `Query Profiling Information `

Hi, I've been learning RUST recently and I'm facing the same difficulty. In my case, the request via Rusqlite (sqlite for rust) is executed instantly, and for Duck (duck-rs), even on 100 lines, it takes about a minute. Describe in more detail how did you figure out the situation?
