### ISSUE TITLE
Matching columns does not work on large tables

### ISSUE THREAD

**Issue by mitchdevenport** [duckdb/duckdb#7746]
### What happens?

I am trying to write the following query:

`select * from table_x where col_x in (SELECT col_y from table_y)`

In my case `table_y` has about 50,000 rows. This query always returns 0 rows (and no error) as it is written. However, if I add a limit to the subquery it then works and we get rows back. For example:

`select * from table_x where col_x in (SELECT col_y from table_y limit 10)`

However, if the limit is larger than ~12000 then the query returns no rows but no error again.

`select * from table_x where col_x in (SELECT col_y from table_y limit 13000)`

The exact size of the subquery where no rows are returned seems to vary between instances of duckdb, but is usually around 12000.

We have also observed similar limitations when trying to get similar behavior using a join.

`select * from table_x where col_x join table_y on col_x = col_y`
`select * from table_x where col_x join table_y on col_x = col_y limit 10`

Is there some sort of limit here on the number of rows that a value can be matched agains that DuckDB is silently failing on?

### To Reproduce

1. Create 2 tables of size >~12,000 with a column that can be matched
2. Run the query `select * from table_x where col_x in (SELECT col_y from table_y)`
3. Run the query `select * from table_x where col_x in (SELECT col_y from table_y limit 10)`

### OS:

Go Docker Image (https://hub.docker.com/_/golang/)

### DuckDB Version:

0.8.0

### DuckDB Client:

Golang

### Full Name:

Mitch Devenport

### Affiliation:

Spice.xyz

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by mitchdevenport** [comment]
This appears to work (with no limit) if we order both tables on the column that is being matched.

**Comment by mitchdevenport** [comment]
It appears to also work if we just order the first table.

**Comment by paultiq** [comment]
For what it's worth, couldn't reproduce with:

```
with data as (select * from range(100000) t(x) order by random())
select * from data where x in (select y from range(1,200000,7) t(y) order by random())
```

**Comment by mitchdevenport** [comment]
Hey @paultiq, thanks for checking!

Could you try wrapping that in a copy:

`COPY(query) TO 'output.parquet' (FORMAT PARQUET);`

I think copy may be the culprit here. If I first create a temporary table and then copy then I don't have the issue:

```
CREATE TEMP TABLE t1 AS SELECT * FROM(query);
COPY t1 TO 'output.parquet';
```

**Comment by paultiq** [comment]
Worked for me, on  both 0.8.0 and 0.8.1-dev180:
```

COPY(
with data as (select * from range(100000) t(x) order by random())
select * from data where x in (select y from range(1,200000,7) t(y) order by random())
) TO 'output.parquet' (FORMAT PARQUET);
select * from 'output.parquet'
```
![image](https://github.com/duckdb/duckdb/assets/104510378/65c74b78-4a3c-4378-9bce-e20e3bcb751b)

**Comment by l1t1** [comment]
fine in CLI 
```
D create table t1 as from range(13000)t(i);
D create table t2 as from range(1,26000,2)t(i);
D .maxrows 10
D select * from t1 where t1.i in(select i from t2);
┌────────────┐
│     i      │
│   int64    │
├────────────┤
│          1 │
│          3 │
│          5 │
│          7 │
│          9 │
│          · │
│          · │
│          · │
│      12991 │
│      12993 │
│      12995 │
│      12997 │
│      12999 │
├────────────┤
│ 6500 rows  │
│ (10 shown) │
└────────────┘
```

**Comment by l1t1** [comment]
130000 rows also ok
```
D drop table t1;
D drop table t2;
D create table t1 as from range(130000)t(i);
D create table t2 as from range(1,260000,2)t(i);
D select * from t1 where t1.i in(select i from t2);
┌────────────┐
│     i      │
│   int64    │
├────────────┤
│     122881 │
│     122883 │
│     122885 │
│     122887 │
│     122889 │
│        ·   │
│        ·   │
│        ·   │
│     122871 │
│     122873 │
│     122875 │
│     122877 │
│     122879 │
├────────────┤
│ 65000 rows │
│ (10 shown) │
└────────────┘
```

**Comment by Mytherin** [comment]
Thanks for the report! Could you try to make a reproducible example that we can execute or provide data for the issue? As indicated this does not seem to be reproducible given the currently provided information.
