### ISSUE TITLE
UPDATE TABLE FROM TABLE2 WHERE ... BUG

### ISSUE THREAD

**Issue by diversoft** [duckdb/duckdb#7749]
### What happens?

UPDATE TABLE FROM TABLE2 WHERE ... BUG
 

### To Reproduce

points table1 with x,y,val columns has 30000 records, and table2 with columns (minx,miny,maxx,maxy,value) has 7,000,000 records, i will update table1 from table2.
when excute SQL like this: 
UPDATE TABLE1 SET VAL=TABLE2.VALUE FROM TABLE2 
WHERE X>TABLE2.MINX AND X<TABLE2.MAXX AND Y>TABLE2.MINY AND Y<TABLE2.MAXY
although some  points(x,y) is in range( minx miny maxx maxy ), but get error value or null .
error has regular like:
![image](https://github.com/duckdb/duckdb/assets/2303685/57f0bbce-781b-40e0-b7d3-21ed9f5f0b7b)

### OS:

windows 11 x64 

### DuckDB Version:

0.8

### DuckDB Client:

Python

### Full Name:

yang

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you please try to make this a reproducible example? Thanks
