### ISSUE TITLE
[Dev / Docs] Hidden dependencies for running test

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb#7750]
### What happens?

Cloning fresh duckdb repo it's not immediately obvious (to me!) how to get the unittest to run (while I believe it used to work, but I am unsure).

There seems to be some hidden state, running `make sqlite` apparently makes the problem go away, but then it's not used by the CI, so I am puzzled.

Even just documenting what's the expected workflow would solve the issue.

### To Reproduce

```
git clone https://github.com/duckdb/duckdb.git
cd duckdb
make -j8
./build/release/test/unittest
```
There are few errors raised like `Could not find test script 'test/sql/table_function/duckdb_keywords.test'.`

### OS:

MacOS, m1

### DuckDB Version:

master

### DuckDB Client:

-

### Full Name:

Carlo Piovesan

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
That file should be part of the repo, are you sure you cloned it correctly?

**Comment by carlopi** [comment]
Actually, I can't reproduce, unsure what I did wrong, but seems to just work. Closing.

**Comment by carlopi** [comment]
Thanks @Tishj for double checking though.
