### ISSUE TITLE
Scalar UDFs assume Idempotency?

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb#7773]
### What happens?

When using the Scalar Functions [PR7171](https://github.com/duckdb/duckdb/pull/7171), the same values are returned for the same inputs. 

If by design, then this should be clearly documented, but it seems more like a bug or unintended consequence of another optimization. 

### To Reproduce

```
import duckdb
from duckdb.typing import *
from faker import Faker
def random_date():
	fake = Faker()
	return fake.date_between()
duckdb.create_function('random_date', random_date, [], DATE)
res = duckdb.sql('select random_date() from range(10)').fetchall()
print(res)
```
returns the same date, repeated 10 times: 
> [(datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),)]

#### Using a parameter to ensure different results for each pass:

Modifying the function to take an incrementing int returns the expected result:
```
import duckdb
from duckdb.typing import *
from faker import Faker
def random_date(x):
	fake = Faker()
	return fake.date_between()
duckdb.create_function('random_date2', random_date, [BIGINT], DATE)
res = duckdb.sql('select random_date2(x) from range(10) t(x)').fetchall()
print(res)
```
> [(datetime.date(2012, 3, 21),), (datetime.date(2009, 2, 28),), (datetime.date(2021, 11, 16),), (datetime.date(2008, 12, 17),), (datetime.date(2011, 11, 26),), (datetime.date(2017, 7, 24),), (datetime.date(2014, 12, 7),), (datetime.date(1994, 2, 8),), (datetime.date(2014, 1, 17),), (datetime.date(1999, 6, 23),)]

### OS:

Windows

### DuckDB Version:

0.8.1-dev194

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Yea I also ran into this, it's because of constant folding.

We likely need another option to indicate side-effects for the function so it doesn't get optimized into a single constant

**Comment by Tishj** [comment]
I looked into it a little bit, but even with FunctionSideEffects::HAS_SIDE_EFFECTS and disable_optimizer it still gets folded somehow.
So this requires some fixing in core

**Comment by paultiq** [comment]
FYI, for what other dbs do:

MySQL uses Deterministic/Not Deterministic flags in their declarations: https://dev.mysql.com/doc/refman/8.0/en/create-procedure.html

Postgres uses volatile: https://www.postgresql.org/docs/current/xfunc-volatility.html
