### ISSUE TITLE
Fail to combine 1,000 small csv files completely 

### ISSUE THREAD

**Issue by hkpeaks** [duckdb/duckdb#7776]
### What happens?

D:\Benchmark>python duckdbcombinefile.py
Traceback (most recent call last):
  File "D:\Benchmark\duckdbcombinefile.py", line 9, in <module>
    con.execute("copy (SELECT * from 'Input/1000SmallFiles/**/*.csv') to 'output/DuckGroupBy.csv' (format csv, header true);")
duckdb.InvalidInputException: Invalid Input Error: Error in file "Input\1000SmallFiles\10\959.csv" on line 9999: expected 14 values per row, but got 1.
Parser options:
  file=Input\1000SmallFiles\10\959.csv
  delimiter=',' (default)
  quote='"' (default)
  escape='' (default)
  header=1' (default)
  sample_size=20480
  ignore_errors=0
  all_varchar=0

### To Reproduce

import duckdb

import time

s = time.time()

con = duckdb.connect()

con.execute("copy (SELECT * from 'Input/1000SmallFiles/**/*.csv') to 'output/DuckGroupBy.csv' (format csv, header true);")

e = time.time()

print("DuckDB GroupBy Time = {}".format(round(e-s,3)))

You can see my written app can produce the combine result https://youtu.be/wL1fbY3JZ1Y

### OS:

Windows 11

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

Max Yu

### Affiliation:

Peaks Consolidation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report - but this issue is not reproducible by us. Could you include the data required to reproduce the problem? Are you sure the CSV files are not just malformed?

**Comment by hkpeaks** [comment]
You are right, I noticed the affected file has one more byte after the end of file 0D 0A (34)
But this file can be read by open office and my app.
https://github.com/hkpeaks/peaks-consolidation/tree/main/Input/1000SmallFiles

**Comment by Mytherin** [comment]
The CSV file is malformed so DuckDB is correctly complaining about the malformed CSV file. If you want to parse files that are malformed you could pass `ignore_errors=True` to the CSV reader.

**Comment by hkpeaks** [comment]
Then I copy one of normal csv to 10000 copy and then run test again.

D:\Benchmark>do combinefile
ReadFile{D:\Benchmark\Input\Copy10000\*.csv ~ Table}
1000 2000 3000 4000 5000 6000 7000 8000 9000 10000 10000   Table(14 x 100000000)

WriteFile{Table ~ PeaksCombineFile.csv}
  PeaksCombineFile.csv(14 x 100000000)

Duration: 15.789 seconds

D:\Benchmark>python DuckDBCombineFile.py
DuckDB GroupBy Time = 30.676

Now success, but my app run faster.

I plan to support Parquet format, consider to this this library which connect to duckdb, https://github.com/marcboeker/go-duckdb

**Comment by Mytherin** [comment]
Alright, so then there is no issue here

**Comment by hkpeaks** [comment]
con.execute("copy (SELECT * from 'Input/10K-Files/*.csv') to 'output/DuckGroupBy.csv' (format csv, header true), ignore_errors=True;")

I try several scenarios, not knowing where to put the ignore_errors=True correctly

**Comment by Mause** [comment]
Give this a go:

```sql
copy (SELECT * from read_csv_auto('Input/10K-Files/*.csv', ignore_errors=True) to 'output/DuckGroupBy.csv' (format csv, header true);
```

**Comment by hkpeaks** [comment]
D:\Benchmark>python DuckDBCombineFile.py
Traceback (most recent call last):
  File "D:\Benchmark\DuckDBCombineFile.py", line 9, in <module>
    con.execute("copy (SELECT * read_csv_auto('Input/10K-Files/*.csv', ignore_errors=True)) to 'output/DuckGroupBy.csv' (format csv, header true);")
duckdb.ParserException: Parser Error: syntax error at or near "("
LINE 1: copy (SELECT * read_csv_auto('Input/10K-Files/*.csv', ignore_errors...

**Comment by Mause** [comment]
> D:\Benchmark>python DuckDBCombineFile.py Traceback (most recent call last): File "D:\Benchmark\DuckDBCombineFile.py", line 9, in con.execute("copy (SELECT * read_csv_auto('Input/10K-Files/* .csv', ignore_errors=True)) to 'output/DuckGroupBy.csv' (format csv, header true);") duckdb.ParserException: Parser Error: syntax error at or near "(" LINE 1: copy (SELECT * read_csv_auto('Input/10K-Files/*.csv', ignore_errors...

You forgot the `FROM`

**Comment by hkpeaks** [comment]
I want to use my Go app to read parquet. I try several Parquet-go library but fail. Is DuckDB provides API allows to get selected columns of particular row group of a Parquet file and return as a csv bytestream or file?

**Comment by Mause** [comment]
> I want to use my Go app to read parquet. I try several Parquet-go libraries but fail. Is DuckDB provides API allows to get selected columns of particular row group of a Parquet file and return as a csv bytestream or file? I have do some test for DuckDB using big billion-row parquet file, it is really fast. For csv, my app achieve hyper fast performance, but lacking of Parquet.

Can you create a discussion for this instead? It's not really related to your original issue here

**Comment by hkpeaks** [comment]
Discussion for parquet was created here.
https://github.com/duckdb/duckdb/discussions/7796
