### ISSUE TITLE
Cannot read from ZSTD compressed json files

### ISSUE THREAD

**Issue by goober** [duckdb/duckdb#7780]
### What happens?

Slow performance or possible hanging(?) when reading zstd compressed, newline delimited json files.

### To Reproduce

1. Download a dataset from https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
2. Transform it to json with:`COPY (SELECT * from read_parquet('yellow_tripdata_2022-01.parquet')) TO 'output.json.zst' (FORMAT JSON, COMPRESSION 'ZSTD');`
3. `SELECT COUNT(*) FROM read_json('output.json.zst', auto_detect=true, format=newline_delimited);`

The select command never completes.

## Comparison to non compressed dataset:
1. `COPY (SELECT * FROM read_parquet('yellow_tripdata_2022-01.parquet')) TO 'output.json';`
2. `EXPLAIN ANALYZE SELECT COUNT(*) FROM read_json('output.json', auto_detect=true, format=newline_delimited);`

```
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 0.259s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│    UNGROUPED_AGGREGATE    │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        count_star()       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             1             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         READ_JSON         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2463931          │
│          (2.00s)          │
└───────────────────────────┘
```

### OS:

OSX

### DuckDB Version:

0.8.0

### DuckDB Client:

duckdb binary

### Full Name:

Mathias Åhsberg

### Affiliation:

Independent

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by goober** [comment]
For further information, I have now tested against https://github.com/duckdb/duckdb/pull/7762 and it seems that the issue is resolved by that. But it would be great if that can be confirmed by @lnkuiper as well before this issue is closed.

**Comment by lnkuiper** [comment]
Hi @goober, thanks for the bug report. I have tried your example and can confirm that this no longer hangs. Apologies for the inconvenience!
