### ISSUE TITLE
Importing from large CSV triggers OutOfMemoryException in v0.8.0 but not 0.7.1, breaking db version migrations with EXPORT/IMPORT

### ISSUE THREAD

**Issue by NSchrading** [duckdb/duckdb#7793]
### What happens?

Running

```
CREATE TABLE data as SELECT * FROM read_csv_auto('path_to_csv')
```

on my machine with a large CSV (~20GB) fails after a while with a `duckdb.OutOfMemoryException`. Unfortunately this also affects the recommended approach to update db versions with `"IMPORT DATABASE 'tmp'"`.

Using `parallel=False` works around the issue.

For the purposes of db version updates, I couldn't figure out how to set `parallel=False` in the `IMPORT` command, so I worked around it by running the `CREATE TABLE` command generated in `schema.sql` followed by a custom `INSERT INTO data SELECT * FROM read_csv_auto('tmp\data.csv'), parallel=False)`.

Using duckdb v0.7.1 does not have this issue, everything works as expected on the same CSV.

Perhaps related to other CSV issues with `parallel=True`, e.g. https://github.com/duckdb/duckdb/issues/7702 and https://github.com/duckdb/duckdb/issues/7755

### To Reproduce

Run 

```
CREATE TABLE data as SELECT * FROM read_csv_auto('path_to_csv')
```

on a large CSV file.

### OS:

Windows x64

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

J Nicolas Schrading

### Affiliation:

personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hkpeaks** [comment]
Few days ago, I use DuckDB v0.8.0 to process 20GB, my machine do not encounter any issue.
https://youtu.be/zVR77B2bDR0

**Comment by pdet** [comment]
Hi @NSchrading, thanks for the report. Could you share more information about this issue? 
A sample of the CSV FIle, the specs of the machine, and the number of threads DuckDB is using would be a good start.

**Comment by NSchrading** [comment]
My machine has 16GB of RAM but it typically only has about 5GB available. The rest is used by the system, chrome, vscode, etc.

Here's a db file (in a zip) with fake data that can be used to generate a large CSV that triggers the issue on my machine: 
[fake_data.zip](https://github.com/duckdb/duckdb/files/11639592/fake_data.zip)

To generate the CSV, unzip the db file and run:
```
with duckdb.connect("fake_data.db") as conn:
    conn.sql("SELECT * FROM data").write_csv("fake_data.csv", header=True)
```

This should generate a CSV that is approximately 3.91GB. Then to trigger the `duckdb.OutOfMemoryException` run:

```
with duckdb.connect("fake_from_csv.db") as conn:
    conn.execute("CREATE TABLE data as SELECT * FROM read_csv_auto('fake_data.csv')")
```

The exact stack trace I see is:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
duckdb.OutOfMemoryException: Out of Memory Error: could not allocate block of size 16KB (13.4GB/13.4GB used)
```

In testing on my machine, I can trigger this with CSVs of this form that are 3-5GB, which I guess makes sense given the amount of free RAM I have. Anything smaller avoids the issue. Another piece of information that might be helpful is that when the issue occurs, I notice that duckdb creates a directory called `<name of db>.tmp` that contains tmp files called `duckdb_temp_storage-0.tmp`. It's like it is realizing it's running out of RAM and attempting to use disk to do work but then failing?

Using parallel=False on this CSV works fine, uses a lot less memory, and I also notice that the progress bar progresses much more smoothly vs the default behavior where it seems to get stuck at a certain percentage, hang, and then eventually fail:
```
with duckdb.connect("fake_from_csv.db") as conn:
    conn.execute("CREATE TABLE data as SELECT * FROM read_csv_auto('fake_data.csv', parallel=False)")
```

Using duckdb v0.7.1 defaults (no need to pass parallel=False) works as well.

**Comment by SarthakJariwala** [comment]
I ran into this same issue on my Windows machine (running duckdb 0.8.0 and Python client) that @NSchrading reported.

Setting `parallel=False` worked

**Comment by hkpeaks** [comment]
Suggest DuckDB to consider this logic:-

if total_byte > 100000000 {
		rule.thread = 10
	} else {
		rule.thread = 1
	}

Base on my Peaks dev experience, small file (particular for file has many columns and long string), it may trigger indentify wrong partition. You can download csv file from Kaggle for testing.
