### ISSUE TITLE
Invalid `NaN` statistics when reading from Parquet

### ISSUE THREAD

**Issue by angadn** [duckdb/duckdb#7803]
### What happens?

When reading Parquet files containing `nan` values, `NULLIF(value, 'nan'::DOUBLE)` doesn't work as expected, and one still sees `nan` values instead of `NULL`.

@Mytherin [explains this issue on Discord](https://discord.com/channels/909674491309850675/1032659480539824208/1113064295270469713) as follows:
- `NULLIF` expands to a case statement
- It's optimised away if the Parquet statistics say there's no `nan` values present

**Workaround 1** _(not ideal)_
The issue disappears if one disables the optimiser with `PRAGMA disable_optimizer`

**Workaround 2**
Use validity flags while generating the Parquet output to treat `nan` as `NULL` beforehand. This is not feasible in cases where the user isn't generating the Parquet file/scrubbing the file is expensive. Moreover, the user may want to preserve `nan`s as they are distinct to `NULL`

**Solution**
Wait for a resolution on https://github.com/apache/parquet-format/pull/196 (or strip min/max statistics support for float/double columns from the Parquet reader).

### To Reproduce

```
SELECT NULLIF(value, 'nan'::DOUBLE) FROM read_parquet('foo.parquet');
```

You'll still see `nan` values in the output.

### OS:

all

### DuckDB Version:

≤ 0.8.0 (current)

### DuckDB Client:

all

### Full Name:

Angad Nadkarni

### Affiliation:

Causal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
This is still an issue

**Comment by Mytherin** [comment]
I've picked this up again and pushed a fix in https://github.com/duckdb/duckdb/pull/16962
