### ISSUE TITLE
Memory spikes beyond limit on wide SELECTs, causes OOMs on JOINs

### ISSUE THREAD

**Issue by droher** [duckdb/duckdb#7819]
### What happens?

Memory spikes well beyond `memory_limit` (20GB peak footprint on a 6.8GB limit) when selecting a large number of VARCHAR columns, even when all values of those columns are NULL. On simple select statements, the memory footprint grows linearly with the size of the SELECT, but it doesn't appear to cause associated slowdowns. On the other hand, when the wide select is part of a query with a join, the problem seems to scale heavily with the number of tables joined, causing slowdowns and OOMs/segfaults, even when the total size of the SELECT doesn't grow as much.

### To Reproduce

To generate the data (10 mil rows, 1.3GB peak footprint on create, physical table size 3.2 MB)
```
CREATE TABLE t AS (
    SELECT 
        UNNEST(GENERATE_SERIES(1, 10000000))::INT AS i,
        NULL::VARCHAR AS c0,
        NULL::VARCHAR AS c1,
        NULL::VARCHAR AS c2,
        NULL::VARCHAR AS c3,
        NULL::VARCHAR AS c4,
        NULL::VARCHAR AS c5,
        NULL::VARCHAR AS c6,
        NULL::VARCHAR AS c7,
        NULL::VARCHAR AS c8,
        NULL::VARCHAR AS c9,
        NULL::VARCHAR AS c10,
        NULL::VARCHAR AS c11,
        NULL::VARCHAR AS c12,
        NULL::VARCHAR AS c13,
        NULL::VARCHAR AS c14,
        NULL::VARCHAR AS c15,
        NULL::VARCHAR AS c16,
        NULL::VARCHAR AS c17,
        NULL::VARCHAR AS c18,
        NULL::VARCHAR AS c19,
        NULL::VARCHAR AS c20,
        NULL::VARCHAR AS c21,
        NULL::VARCHAR AS c22,
        NULL::VARCHAR AS c23,
        NULL::VARCHAR AS c24,
        NULL::VARCHAR AS c25,
        NULL::VARCHAR AS c26,
        NULL::VARCHAR AS c27,
        NULL::VARCHAR AS c28,
        NULL::VARCHAR AS c29,
        NULL::VARCHAR AS c30,
);
```
Then on different queries:
```
-- Peak footprint: 2.5 GB, total time 0.769s
SELECT * FROM t;

-- Peak footprint: 20.0 GB, total time 3.81s
SELECT *, *, *, *, *, *, *, * FROM t;

-- Peak footprint 450 MB, total time 0.197s (0.75s during hash join)
SELECT COUNT(*) FROM t JOIN t AS t2 USING (i);

-- Peak footprint: 10.0 GB, total time 12.81 s (78.4s during hash join)
SELECT * FROM t JOIN t AS t2 USING (i);

-- Peak footprint: 7.0 GB, OOM (failed to pin block of size 262KB (6.8GB/6.8GB used))
SELECT * FROM t JOIN t AS t2 USING (i) JOIN t AS t3 USING (i);

-- Now try same query without memory limit
-- Peak footprint: 18.5 GB, total time 47.17s, ~300s combined on hash joins)
SET memory_limit=-1;
SELECT * FROM t JOIN t AS t2 USING (i) JOIN t AS t3 USING (i);

-- Peak footprint: 26.5GB, segfault
SELECT * FROM t JOIN t AS t2 USING (i) JOIN t AS t3 USING (i) JOIN t AS t4 USING(i);
```

### OS:

MacOS Ventura 13.4 (aarch64, M1 Macbook Air 8GB)

### DuckDB Version:

0.8.0

### DuckDB Client:

CLI

### Full Name:

David Roher

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by zenazn** [comment]
I think this one is biting us too—we have some use cases where we're joining some very wide tables, and memory usage is... exciting 📈
