### ISSUE TITLE
WHERE clause: lateral reference to column names yields questionable results in the presence of side effects

### ISSUE THREAD

**Issue by Teggy** [duckdb/duckdb#7828]
### What happens?

A lateral reference to a column alias `x` inside a `WHERE` clause may yield unexpected/questionable results if the defining expression of `x` relies on side effects.  Referential transparency is violated.

### To Reproduce

~~~
D SELECT setseed(0.42); 
D SELECT random() AS x WHERE x < 0.5;
┌────────────────────┐
│         x          │
│       double       │
├────────────────────┤
│ 0.6215802642101376 │   ⚠️ x ⩾ 0.5 — oops!
└────────────────────┘
~~~

### Thoughts

- The treatment of the `WHERE` clause currently differs from that of the `SELECT` clause (the latter yields an error message that acknowledges the problematic side effect):

   ~~~
   D SELECT random() AS x, x AS y;
  Error: Binder Error: Alias "x" referenced in a SELECT clause - but the expression has side effects. This is not yet supported.   
   ~~~
   
   For now, this error should probably be raised for the `WHERE` clause as well.
   
- The real fix™ would be to avoid expression re-evaluation on a lateral column reference.

### OS:

macOS

### DuckDB Version:

v0.8.1-dev525 e8bcc0f50d

### DuckDB Client:

CLI

### Full Name:

Torsten Grust

### Affiliation:

U Tübingen, Germany

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
CTE has the issue too
```
D with t as(SELECT random() AS x)select x from t WHERE x < 0.5;
┌────────────────────┐
│         x          │
│       double       │
├────────────────────┤
│ 0.9409376408301614 │
└────────────────────┘
```

**Comment by paultiq** [comment]
FWIW, this is observed in other databases: 
 
- Mysql: https://dbfiddle.uk/uzlAHCUN
- Sqlite: https://dbfiddle.uk/xqRgiFoA
