### ISSUE TITLE
Duckdb JDBC Driver in SAS does not return varchar columns (version 8.0)

### ISSUE THREAD

**Issue by rfmeraz** [duckdb/duckdb#7847]
### What happens?

when using the duckdb jdbc driver in SAS (Base SAS  version 9.04.01M8P011823) no data is returned with columns of type varchar.

Using another JDBC driver, and the same example code (see below and attached) I confirmed that varchar is returned from the DB correctly (sqlite jdbc driver from here https://github.com/xerial/sqlite-jdbc)

[duckdb_issue.pdf](https://github.com/duckdb/duckdb/files/11666018/duckdb_issue.pdf)

### To Reproduce

libname duckdb jdbc classpath="./duckdb_jdbc_v8.jar"
class="org.duckdb.DuckDBDriver"
URL="jdbc:duckdb:";

proc sql;
connect using duckdb;

execute (
     create table test as 
         select 1 as intcol, 'abc' as varcol, 2.0 as floatcol
) by duckdb;

create table test as select * from connection to duckdb (select * from test);

proc print data=test;
run;
quit;

### OS:

Linux 3.10.0-1160.90.1.el7.x86_64 #1 SMP Fri Mar 17 08:39:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### DuckDB Version:

0.8.0

### DuckDB Client:

jdbc

### Full Name:

Richard F. Meraz

### Affiliation:

Indiana University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rfmeraz** [comment]
Just some context: I handle data engineering for a health science research group and we work in a "multilingual" environment where we switch between python, R, SAS, SQL etc depending on the needs of the problem to be solved.  Our stack makes heavy use of duckdb via the python client.  I'm certainly able to get data between duckdb and SAS via python, but I was looking to see if I might be able to go a more direct route from duckdb to SAS using the JDBC library.

Regardless of how this issue turns out, let me take a moment to thank you again for duckdb--it has become an incredible tool in our research analytic stack due to the facility of expressing computations in your SQL dialect, it's speed, the ease of data transformation out of parquet files, etc; really an integral part of our daily work.  Thank you so much!!

**Comment by Tishj** [comment]
Thanks for the bug report!

It's definitely expected for every client to have the same behavior at the SQL level, there is likely some glue missing that we need to add :)

**Comment by Mause** [comment]
I've sent an email to SAS to request a trial license for BASE SAS, as without it, we're probably not going to be able to debug this. I'll report back if they do
