### ISSUE TITLE
Runaway memory usage with PyArrow Dataset and duckdb.from_arrow

### ISSUE THREAD

**Issue by amoeba** [duckdb/duckdb#7856]
### What happens?

Under certain situations when feeding data into DuckDB from a PyArrow [Dataset](https://arrow.apache.org/docs/python/dataset.html) made up of a single Parquet file, memory usage increases every time DuckDB performs a query against the Dataset and converts it to an Arrow table. This is a semi-contrived example, I realize.

### To Reproduce

Download https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2009-01.parquet, install latest PyArrow and duckdb 0.8.0, and run this:

```python
import duckdb
import pyarrow.dataset as ds
from pyarrow import fs

conn = duckdb.connect(database=":memory:")
table_ds = ds.dataset(["./yellow_tripdata_2009-01.parquet"], filesystem=fs.LocalFileSystem())

for _ in range(20):
    table = conn.from_arrow(table_ds).limit(100_000).arrow()
```

You should see memory usage increase in multi-GB steps (corresponding to each iteration) and eventually get somewhere near 37GB, at least on my system. The issue occurs with other Parquet files I've tested, including files that are smaller or split into more than one row group. The size of the jump with each iteration seems to correlate with row group size which I think is due to the fact that PyArrow's Parquet+Datasets integration has to read in an entire row group at once.

To _not_ reproduce, remove the `limit(100_000)`:

```python
import duckdb
import pyarrow.dataset as ds
from pyarrow import fs

conn = duckdb.connect(database=":memory:")
table_ds = ds.dataset(["./yellow_tripdata_2009-01.parquet"], filesystem=fs.LocalFileSystem())

for _ in range(20):
    table = conn.from_arrow(table_ds).arrow()
```

It's not clear to me whether this is a PyArrow issue or DuckDB issue so any help tracking this down would be great.

### OS:

macOS 13.4, aarch64

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

Bryce Mecum

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by amoeba** [comment]
Thanks for running all those stats @paultiq! We looked at this more today and it looks like the issue lies on the PyArrow side and not DuckDB so I'm going to close this.

**Comment by paultiq** [comment]
@amoeba Could you explain more? I'm curious what you found, as I use pyarrow a lot and curious how / what you found. Thanks!

**Comment by amoeba** [comment]
There are basically two things going on here:

1. The Datasets API needs to read an entire row group at once so this explains the size of the jumps in memory usage and why splitting a Parquet file into more row groups helps
2. This code uses PyArrow's Scanner API and the presence of the `limit()` call triggers a cancel/abort of scan, at which point PyArrow fails to clean up after itself. So the issue is in that cancel/abort code. Work to do scans with ExecNodes is in the works over on https://github.com/apache/arrow/issues/31486.

**Comment by akotlar** [comment]
I'm having a similar issue, except that I don't think pyarrow / dataset api is to blame here. When running in a standard python thread, there is no issue, it is only when the handler function is executed inside of a ray worker.

Ray 2.31, pyarrow 16.1.0

This single line causes memory usage to go from a max of 8GB, to > 30GB: https://github.com/bystrogenomics/bystro/pull/537/files#diff-fd08d14b4d8f604ad1176f8fbef449c1860a90c4e2154f1ee7ec079b14b8a832R197
