### ISSUE TITLE
0.8 Joins working?

### ISSUE THREAD

**Issue by dioptre** [duckdb/duckdb#7869]
### What happens?

On a mac m2 pro:

I download a 45M parquet file and save as yellow.parquet:
https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet
Then I try something trivial:
```
CREATE TABLE blue AS SELECT * FROM 'yellow.parquet';
CREATE TABLE yellow AS SELECT * FROM 'yellow.parquet';
select sum(yellow.tip_amount) from yellow inner join blue on yellow.tip_amount=blue.tip_amount group by yellow.tip_amount, blue.tip_amount ;
```

After many minutes, no output. Stable memory @ 162M.

Each group by should produce 4k rows on each side. Seems like the joins have a bit of work to do? Otherwise I'm missing something huge!

Let me know how I can help.

PS. I also ran the query:
```
select * from yellow inner join blue on yellow.tip_amount=blue.tip_amount;
```
Which I would assume would not kill the instance. (Join would work first on 3Mx2=6M column and project the rows in a result - being yellow+blue memory? instead of yellow*blue memory)

### To Reproduce

See above

### OS:

Mac 12.4

### DuckDB Version:

0.8

### DuckDB Client:

cli

### Full Name:

Andrew Grosser

### Affiliation:

Sourcetable

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Are you sure that joining on tip amount is trivial? If tip amounts are frequently repeated, this query could result in many many times more rows than the raw data. Maybe try joining on the primary key as a better test?

**Comment by dioptre** [comment]
There are 4000 records for each group-by tip_amount?

**Comment by paultiq** [comment]
Is this related to https://github.com/duckdb/duckdb/issues/7856?

Both are memory issues with the **same dataset**, although the queries differ.

**Comment by dioptre** [comment]
@paultiq I just tried with two parquet files and no dice
```
D CREATE TABLE yellow AS SELECT * FROM 'yellow.parquet';
D CREATE TABLE blue AS SELECT * FROM 'blue.parquet';
D explain select * from yellow inner join blue on yellow.tip_amount=blue.tip_amount;
```
This is the second part of the issue, and while slow, I feel shouldn't be crashing the app:
```
select * from yellow inner join blue on yellow.tip_amount=blue.tip_amount;
```
This seems wrong?
<img width="367" alt="Screen Shot 2023-06-07 at 3 41 11 PM" src="https://github.com/duckdb/duckdb/assets/760216/8bb7f3d3-effe-49e5-9ccd-8d28fc314903">

**Comment by dioptre** [comment]
Think looks off too?
<img width="748" alt="Screen Shot 2023-06-07 at 3 44 19 PM" src="https://github.com/duckdb/duckdb/assets/760216/4de3bd0f-af63-40e8-9b37-2cd6a95197d8">

**Comment by paultiq** [comment]
No idea on the plans, but:

I already had the dcata from #7856 locally, and thinking about @Alex-Monahan's question: 80% of the rows are 0.00, making this nearly a cartesian product (all the 0.00's x all the 0.xx's) of several million rows with themselves. 

If you check your data, I assume you'll see the same:
`select tip_amount, count(*) c from yellow group by tip_amount order by c desc`

**Comment by dioptre** [comment]
Ah I see I think I was after a result more like this:

```
with b as (
  select sum(tip_amount) as tip_amount from blue group by tip_amount
),
y as (
  select sum(tip_amount) as tip_amount from yellow group by tip_amount
)
select sum(y.tip_amount) from b inner join y on b.tip_amount=y.tip_amount
```

Probably my bad?

**Comment by dioptre** [comment]
Yep def my bad!

**Comment by paultiq** [comment]
Gotcha. So you want to compare the distribution of too amounts from Yellow vs tips from Blue? 

If so, makes sense; but you'd also want to use a full outer join since values might be in either yellow or blue or both. You may want to bin or compare histograms.
