### ISSUE TITLE
Convert Column Type Failed

### ISSUE THREAD

**Issue by coloraven** [duckdb/duckdb#7870]
### What happens?

The `phone` column in the `test` table contains the following data: ["123949", "sdkkd", "ppd23f", "56565652"]. I'm trying to delete the records that are not purely numeric and then convert the column to the `BIGINT` type. Here are the steps I followed:

1.  First, I used `DELETE FROM test WHERE NOT regexp_matches(phone, '^\d{1,}$');` to delete the non-numeric records.
2.  Then I used `SELECT * FROM test;` to check the results after the deletion, and I can only see only the numbers remaining.
3.  Finally, I used `ALTER TABLE test ALTER phone TYPE BIGINT;` try to convert the column type to `BIGINT`. However, I received an error message: `Conversion Error: Could not convert string 'sdkkd' to INT64.`

At first, I thought the DELETE operation didn't fully take effect, but even after disconnecting and reconnecting the data, the same error still occurred.

I'm not sure what the problem is.

### To Reproduce
```sql
CREATE TABLE test (
  phone VARCHAR(10)
);

INSERT INTO test (phone) VALUES
  ('123949'),
  ('sdkkd'),
  ('ppd23f'),
  ('56565652');

-- To delete the non-numeric records
DELETE FROM test WHERE NOT regexp_matches(phone, '^\d{1,}$');

-- To check the results
SELECT * FROM test;

-- Try to convert the column type to `BIGINT`
ALTER TABLE test ALTER phone TYPE BIGINT;
```
### OS:

X64

### DuckDB Version:

0.8

### DuckDB Client:

dbeaver

### Full Name:

ignore

### Affiliation:

ignore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] I agree

**Comment by iacore** [comment]
Stale read
