### ISSUE TITLE
DATE_TRUNC in Tableau returns previous month

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#7879]
Hi, when using the JDBC driver for DuckDB 0.8 i get a weird error when using `date_trunc('month')` in tableau.

Running the query in a sql client works fine, but the results in tableau shows one month off. It actually returns the last day of the previous month, instead of the first day in the current month. The syntax in the tableau generated query is: 

`DATE_TRUNC( 'MONTH', CAST("utilization"."ts_from" AS TIMESTAMP) )`

(`ts_from` is a timestamp column)

_Originally posted by @andreas-eviny in https://github.com/duckdb/duckdb/issues/7013#issuecomment-1582455602_

**Comment by hawkfish** [comment]
Hi @andreas-eviny - That sounds like a time zone issue of some sort. Are you using my [duckdb-taco](https://github.com/hawkfish/duckdb-taco) or a straight JDBC connection with the Postgres dialect? I'm not sure what the latter does but its probably not great.

**Comment by andreas-eviny** [comment]
I agree it sounds time-zone related, but I have a same issue with date-columns, very weird. I was using the straight JDBC connection, will try the "taco" now

**Comment by andreas-eviny** [comment]
Unfortunately, I see the same issue with duckdb-taco:

![image](https://github.com/duckdb/duckdb/assets/119599745/cbd78edb-f4e2-4a52-ae35-5ac880cc91de)

**Comment by andreas-eviny** [comment]
If I do the date_trunc in pre-processing into a seperate date column, tableau still shows the wrong month 🤔

**Comment by hawkfish** [comment]
What if you cast it to a `DATE` in the pre-processing?

Can you attach a short repro case with data?

**Comment by hawkfish** [comment]
Oh and it looks like you are not showing the truncated date but the `MONTH` function applied to it? There may just be a simple problem with January being 0 or 1.

**Comment by andreas-eviny** [comment]
Hi, there is no MONTH function, that is just the Tableau default formatting when you use the DATE_TRUNC('month', [ts_from]) function. For a repro case you can just create two years of hourly data like this:

`create or replace table repro_table as  
-- create two years of hourly data
select date_trunc('hour', now()) - (interval 1 hour * unnest(range(0, 24*365*2))) as ts_from`

![image](https://github.com/duckdb/duckdb/assets/119599745/7e7ce151-4fd2-4696-9eec-f2c1eefeb5d4)

As you can see, everything is one day (and consequently one month) off. I also tried converting to DATE in preprocessing with same result.

After experimenting some more, it turns out DATETRUNC('week') and DATE('ts_from') is also one day off. And adding a copy of the column in preprocessing with DATE datatype also gives wrong results. So basically it looks like all dates are reported one day off :/

**Comment by hawkfish** [comment]
One thing I noticed is that you are using `now()` to generate the data, which means you are getting `TIMESTAMP WITH TIME ZONE` values. I'm not clear on what Tableau does with them, but you can try using initial SQL in the Taco connection dialogue to set the calendar a time zone. I think that example is in the taco documentation.

**Comment by hawkfish** [comment]
This is strange - I can't reproduce it:

<img width="1028" alt="image" src="https://github.com/duckdb/duckdb/assets/13156216/08ee2e7f-e5da-4e3d-9d9e-95f5c1f73ed0">

I changed the cast to `DATETIME` so that I could see the fractions.

**Comment by hawkfish** [comment]
The query generation is fine but the driver is not handling `TSTZ` correctly in some places so if you try to look at exact values for such columns you will get a strange error. Probably not your issue but it might be if you are using older versions.

**Comment by andreas-eviny** [comment]
I get the same result as you if i cast to datetime after doing the datetrunc(). So DATETIME(DATETRUNC()) works, but DATE(DATETIME(DATETRUNC())) does not...

**Comment by hawkfish** [comment]
What versions of the code (driver, DuckDB) are you using? Because I had to fix a bug in the driver to have it return exact TSTZ values.

**Comment by hawkfish** [comment]
I'm afraid I can't reproduce this even when I change the TZ to ahead of Greenwich.

**Comment by andreas-eviny** [comment]
A simple workaround is to change the datatype in tableau from date to datetime for all date fields.

**Comment by hawkfish** [comment]
What time zone are you in?

**Comment by andreas-eviny** [comment]
I'm in CET (Europe/Oslo)

**Comment by hawkfish** [comment]
OK I managed to reproduce this by setting my laptop TZ to CET.

**Comment by hawkfish** [comment]
Figured it out. DuckDB rebinds the return type for day-level truncations to `DATE`, but Tableau expects the return type to always be `DATETIME`, so it butchers the return type back to date time and messes it up depending on the system TZ. This is why adding the cast fixes the problem - the values are returned with the type Tableau expects and it leaves them alone.

This is not a DuckDB bug, but it _is_ something I can fix in the duckdb-taco. if you are using PG dialect, then you will need to add the cast manually.
