### ISSUE TITLE
Insert into table fails with `INTERNAL Error: Cannot perform IO in in-memory database - CreateBlock!`

### ISSUE THREAD

**Issue by k-anshul** [duckdb/duckdb#7887]
### What happens?

1. I opened duckdb cli and opened it on a persistent database. 
2. I created a table with a parquet file. 
`create or replace table test as select * from read_parquet('2023_06_07_1686176284392_0.parquet');`
3. I added more data into the table from some more parquet files using 
`insert into  test select * from read_parquet('*.parquet');`
4. The insert command fails with error :
`Error: TransactionContext Error: Failed to commit: INTERNAL Error: Cannot perform IO in in-memory database - CreateBlock!`

Ingesting all files in one table with `create or replace table test as select * from read_parquet('*.parquet');` succeeds as well ingesting all the files individually.

### To Reproduce

Running following commands should reproduce the issue:

```sql
.open file.db
CREATE OR REPLACE TABLE test AS SELECT * FROM read_parquet('2023_06_07_1686176284392_0.parquet');
INSERT INTO test SELECT * FROM read_parquet('*.parquet');
```
```console
Error: TransactionContext Error: Failed to commit: INTERNAL Error: Cannot perform IO in in-memory database - CreateBlock!
```
Attaching parquet files as well : 
[data.zip](https://github.com/duckdb/duckdb/files/11704459/data.zip)

### OS:

macOS 13.4

### DuckDB Version:

v0.8 and latest as well

### DuckDB Client:

CLI

### Full Name:

Anshul Khandelwal

### Affiliation:

Rill data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
how about exit CLI and reload database, then do insert?
I found even open a persistent database, it's content is loaded into memory.
```sql
~ $ duckdb db1
v0.7.1 b00b93f
Enter ".help" for usage hints.
D PRAGMA show_tables;
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ 0 rows  │
└─────────┘
D .exit
~ $ ls db1
db1
~ $ duckdb
v0.7.1 b00b93f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .open db1
D create or replace table test as select * from range(10)t(i);
D insert into test select * from range(3)t(i);
D from test;
┌───────┐
│   i   │
│ int64 │
├───────┤
│     0 │
│     1 │
│     2 │
│     3 │
│     4 │
│     5 │
│     6 │
│     7 │
│     8 │
│     9 │
│     0 │
│     1 │
│     2 │
└───────┘
D PRAGMA show_tables;
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ test    │
└─────────┘
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬───┬───────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ … │ wal_size  │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │   │  varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼───┼───────────┼──────────────┼──────────────┤
│ db1           │ 0 bytes       │     262144 │ … │ 278 bytes │ 18KB         │ 6.4GB        │
├───────────────┴───────────────┴────────────┴───┴───────────┴──────────────┴──────────────┤
│ 1 rows                                                               9 columns (6 shown) │
└──────────────────────────────────────────────────────────────────────────────────────────┘
D .exit
~ $ duckdb db1
v0.7.1 b00b93f
Enter ".help" for usage hints.
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬───┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ … │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │   │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼───┼──────────┼──────────────┼──────────────┤
│ db1           │ 786KB         │     262144 │ … │ 0 bytes  │ 0 bytes      │ 6.4GB        │
├───────────────┴───────────────┴────────────┴───┴──────────┴──────────────┴──────────────┤
│ 1 rows                                                              9 columns (6 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────┘
D insert into test select * from range(3)t(i);
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬───┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ … │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │   │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼───┼──────────┼──────────────┼──────────────┤
│ db1           │ 786KB         │     262144 │ … │ 74 bytes │ 786KB        │ 6.4GB        │
├───────────────┴───────────────┴────────────┴───┴──────────┴──────────────┴──────────────┤
│ 1 rows                                                              9 columns (6 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by b-per** [comment]
I have the same issue with `read_json_auto()` in DuckDB 0.8.1.

Calling `insert into test select * from read_json_auto('myfile.json.gz');` fails for some of the json.gz files with the error:
```duckdb.TransactionException: TransactionContext Error: Failed to commit: INTERNAL Error: Cannot perform IO in in-memory database - CreateBlock!```

But creating a temp table to load the data first works without any error, doing a 
- `create or replace temp table load_before as select * from read_json_auto('myfile.json.gz');` 
- followed by a `insert into test select * from load_before`

**Comment by jascoul** [comment]
I had the same issue when running COPY table FROM 'file.json'. 
I am using transactions so the error showed up when running 'commit'.

The error went away for me when I upgraded the server to have more RAM. 
So I think this might be duckdb's way of telling: I ran out of memory.

Additionally if I re-run my code, It throws a different error:

duckdb.TransactionException: TransactionContext Error: Failed to commit: INTERNAL Error: Failed to cast chunk info to type - query result type mismatch

This second error is persistent. If I manually add a single row to the table (INSERT INTO table ('id', 'name') VALUES ('foo', 'bar'); It throws the same error. Other tables in the db are not affected.

**Comment by szarnyasg** [comment]
I managed to reproduce this issue with the latest `main` build.

**Comment by jascoul** [comment]
I still encounter the issue.  
The import always fails on the same files. 
There is a large text column in the files, If I remove that, then it works fine. 
I also tried using csv instead of json, but that does not solve it.

**Comment by Mytherin** [comment]
Thanks for the report!

I have investigated and resolved the issue [here](https://github.com/Mytherin/duckdb/commit/495f6da1a8dec411efea99929fd263a280489c5d) and will merge it into main in the coming days.

The issue is triggered when inserting a low amount of large strings/blobs into a table that already has rows in it - in particular when using insertion-order preservation. As a work-around, you can disable preservation of insertion order using the following setting that should prevent it from triggering:

```sql
SET preserve_insertion_order=false;
```

The cause of the issue is that the large (overflow) strings are written to the file on disk, but because only a few rows are written the strings are shuffled around internally. This causes the pointer to the string to still point to the on-disk file, even though the string currently resides only in-memory after the shuffling, causing the exception.

**Comment by Mytherin** [comment]
This should be solved now in #8943 - would be great if you could verify that the problem is solved in the latest main

**Comment by k-anshul** [comment]
> This should be solved now in #8943 - would be great if you could verify that the problem is solved in the latest main

I can still see the same issue in the latest nightly. Are the changes not available in the nightly build yet ?

**Comment by Mytherin** [comment]
Which client are you using? Could you build from source to ensure you are using the latest sources?

**Comment by k-anshul** [comment]
Yeah works fine on main. Thanks.
