### ISSUE TITLE
R: Cannot install Postgres Scanner

### ISSUE THREAD

**Issue by christophscheuch** [duckdb/duckdb#7892]
### What happens?

I want to install the Postgres Scanner by sending queries from R, but get the following error message:
```
Error: rapi_execute: Failed to run query
Error: HTTP Error: Failed to download extension "postgres_scanner" at URL "http://extensions.duckdb.org/v0.8.0/windows_amd64_rtools/postgres_scanner.duckdb_extension.gz"
Extension "postgres_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```
Session info:
```
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_Austria.utf8  LC_CTYPE=English_Austria.utf8    LC_MONETARY=English_Austria.utf8
[4] LC_NUMERIC=C                     LC_TIME=English_Austria.utf8    

time zone: Europe/Vienna
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] duckdb_0.8.0 DBI_1.1.3   

loaded via a namespace (and not attached):
[1] compiler_4.3.0  tools_4.3.0     rstudioapi_0.14
```

### To Reproduce

library(DBI)
library(duckdb)

con <- dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb", read_only = FALSE)

dbExecute(con, "INSTALL postgres")

### OS:

Windows 10 x64 (build 19045)

### DuckDB Version:

0.8.0

### DuckDB Client:

R

### Full Name:

Christoph Scheuch

### Affiliation:

Tidy Finance

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by mattsams89** [comment]
To add a bit to the issue, I've been trying to diagnose the same issue with the spatial extension not installing on v0.8.0 the last two days (in the meantime, I'm going R -> Python via {reticulate} -> R to get around it). I downloaded the r-test-extensions.zip from the most recent [nightly build](https://github.com/duckdb/duckdb/actions/runs/5216993054) (sorry, not sure how to directly reference an action) and decided to check each one's direct download link (e.g. `https://extensions.duckdb.org/v0.8.0/windows_amd64_rtools/json.duckdb_extension.gz`). From what I can tell, the extensions in the .zip suffixed with *_clone all throw installation errors in R, and using their direct download link in a browser results in an "Access Denied" page being shown. Hopefully that helps home in on the cause!

**Comment by lgaborini** [comment]
`sqlite_scanner` has the same issue: no `v0.8.1`, `v0.8.0`, `v0.7.1` releases

**Comment by Mause** [comment]
This is expected for the moment I believe - R on Windows uses an esoteric compiler/ABI that we'd have to compile all our extensions specially for

**Comment by stefanfritsch** [comment]
Is it really fair to call gcc12 on MinGW-w64 "esoteric"?

Would it be possible to get a non-hacky source-download so the RTools could simply compile the extension as needed?

**Comment by iangow** [comment]
@christophscheuch Does 0.9.1 help? See [here](https://github.com/duckdb/duckdb/pull/9302).

**Comment by christophscheuch** [comment]
@iangow unfortunately, no. I just installed version 0.9.1 from source and still get the error:
```
Error: rapi_execute: Failed to run query
Error: HTTP Error: Failed to download extension "postgres_scanner" at URL "http://extensions.duckdb.org/v0.9.1/windows_amd64_rtools/postgres_scanner.duckdb_extension.gz"
Extension "postgres_scanner" is an existing extension.
```

**Comment by iangow** [comment]
@christophscheuch 

What happens if you just do the following?

(This skips the `INSTALL` step, which seems unnecessary on MacOS with the R package. I wonder if the extension is already installed.)

```r
library(DBI)
library(duckdb)

con <- dbConnect(duckdb::duckdb())

dbExecute(con, "LOAD postgres")
```

**Comment by iangow** [comment]
``` r
remove.packages("duckdb")
#> Removing package from '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library'
#> (as 'lib' is unspecified)
install.packages("duckdb")
#> 
#> The downloaded binary packages are in
#>  /var/folders/nx/q9ytjhs52_z1pnspvfh_9n180000gn/T//Rtmp5TIhbF/downloaded_packages
library(DBI)
library(dplyr, warn.conflicts = FALSE)
library(duckdb)

con <- dbConnect(duckdb::duckdb())

dbExecute(con, "LOAD postgres")
#> [1] 0

dsf <- tbl(con, "postgres_scan_pushdown('', 'crsp', 'dsf')")
#> ℹ Using `ident_q()` for a table identifier is intended as fallback in case of
#>   bugs.
#> ℹ If you need it to work around a bug please open an issue
#>   <https://github.com/tidyverse/dbplyr/issues>.
#> This message is displayed once every 8 hours.
dsf
#> # Source:   SQL [?? x 20]
#> # Database: DuckDB v0.9.1 [root@Darwin 23.2.0:R 4.3.2/:memory:]
#>    cusip    permno permco issuno hexcd hsiccd date       bidlo askhi   prc   vol
#>    <chr>     <int>  <int>  <dbl> <dbl>  <dbl> <date>     <dbl> <dbl> <dbl> <dbl>
#>  1 68391610  10000   7952  10396     3   3990 1986-01-07  2.38  2.75 -2.56  1000
#>  2 68391610  10000   7952  10396     3   3990 1986-01-08  2.38  2.62 -2.5  12800
#>  3 68391610  10000   7952  10396     3   3990 1986-01-09  2.38  2.62 -2.5   1400
#>  4 68391610  10000   7952  10396     3   3990 1986-01-10  2.38  2.62 -2.5   8500
#>  5 68391610  10000   7952  10396     3   3990 1986-01-13  2.5   2.75 -2.62  5450
#>  6 68391610  10000   7952  10396     3   3990 1986-01-14  2.62  2.88 -2.75  2075
#>  7 68391610  10000   7952  10396     3   3990 1986-01-15  2.75  3    -2.88 22490
#>  8 68391610  10000   7952  10396     3   3990 1986-01-16  2.88  3.12 -3    10900
#>  9 68391610  10000   7952  10396     3   3990 1986-01-17  2.88  3.12 -3     8470
#> 10 68391610  10000   7952  10396     3   3990 1986-01-20  2.88  3.12 -3     1000
#> # ℹ more rows
#> # ℹ 9 more variables: ret <dbl>, bid <dbl>, ask <dbl>, shrout <dbl>,
#> #   cfacpr <dbl>, cfacshr <dbl>, openprc <dbl>, numtrd <dbl>, retx <dbl>
```

<sup>Created on 2023-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by christophscheuch** [comment]
@iangow I just tried again, but the problem persists in Windows. I guess for Mac the extension is already installed or can be installed smoothly.

**Comment by iangow** [comment]
> @iangow I just tried again, but the problem persists in Windows. I guess for Mac the extension is already installed or can be installed smoothly.

Yes, the MacOS version installs `postgres_scanner` by default. I have re-written the draft blog post I made on Tidy Finance to remove the dependence on `postgres_scanner`. Performance is a little worse, but not too different (still much better than using SQLite, etc.).
