### ISSUE TITLE
Thousand separators are not supported for floating point numbers

### ISSUE THREAD

**Issue by michaelwexler** [duckdb/duckdb#7903]
### What happens?

Tested the following SQL statements:
```
select format('{:,}', 123345);
select format('{:,}', 123345.678);

```
The first one worked as expected, but the second one returned 

> SQL Error: Invalid Error: Thousand separators are not supported for floating point numbers

Is this a limitation of DuckDB, or the underlying library?  Or is this just not supported with the `fmt` syntax?

### To Reproduce

```
select format('{:,}', 123345);
select format('{:,}', 123345.678);

```
First one works, next gives the error. 

### OS:

Mac OS Monterey 12.6.1, Apple Silicon 

### DuckDB Version:

v0.8.0 e8e4cea5ec

### DuckDB Client:

DBeaver

### Full Name:

Michael Wexler

### Affiliation:

Interested User, between jobs.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
I commented similar request here
https://github.com/duckdb/duckdb/issues/7320

**Comment by liveuser123** [comment]
Facing the same issue

**Comment by sprestridge** [comment]
Same issue if `printf()` is used:

```sql
SELECT printf('%,.2f', 123345.678);
```
DuckDB error: 

> Invalid Input Error: Thousand separators are not supported for floating point numbers
