### ISSUE TITLE
DuckDB fails with `INTERNAL Error: Logical column index 11 out of range`

### ISSUE THREAD

**Issue by begelundmuller** [duckdb/duckdb#7905]
### What happens?

As discussed [on Discord](https://discord.com/channels/909674491309850675/921100573732909107/1116652752286797955), we are getting the following error when running certain kinds of queries on a dataset:
```
INTERNAL Error: Logical column index 11 out of range
```

### To Reproduce

I have managed to reproduce the error by running just the following queries:
```sql
CREATE TABLE a(
    a1 VARCHAR,
);

CREATE TABLE b(
    b1 VARCHAR,
    b2 TIMESTAMP,
    b3 TIMESTAMP,
    b4 VARCHAR,
    b5 VARCHAR,
    b6 VARCHAR,
    b7 TIMESTAMP,
    b8 TIMESTAMP,
    b9 VARCHAR,
    b10 VARCHAR,
    b11 VARCHAR,
    b12 VARCHAR,
    b13 VARCHAR,
    b14 VARCHAR,
);

INSERT INTO b VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

CREATE TABLE c(
    c1 VARCHAR,
);

CREATE TABLE d(
    d1 VARCHAR,
    d2 VARCHAR,
);

SELECT *
FROM a
LEFT JOIN b ON b.b14 = a.a1 
LEFT JOIN c ON b.b13 = c.c1
LEFT JOIN d ON b.b12 = d.d1
WHERE d.d2 IN ('');
```

### OS:

aarch64, x64

### DuckDB Version:

v0.8.1-dev416 9d5158ccd2

### DuckDB Client:

DuckDB CLI

### Full Name:

Benjamin Egelund-Müller

### Affiliation:

Rill Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
Hi @begelundmuller, thanks for following through and the simple reproduction you provided.

Triage: it seems that this has something to do with JoinOrderOptimizer logic for fetching statistics when a given table is empty, this is the stack trace I get:
```
0   duckdb 0x0000000106b96c00 _ZN6duckdb9Exception13GetStackTraceEi + 304
1   duckdb 0x0000000106b94cf8 _ZN6duckdb20DuckDBAssertInternalEbPKcS1_i + 436
2   duckdb 0x00000001050cd2fc _ZNK6duckdb10ColumnList9GetColumnENS_12LogicalIndexE + 468
3   duckdb 0x00000001064c5a68 _ZN6duckdb14DuckTableEntry13GetStatisticsERNS_13ClientContextEy + 232
4   duckdb 0x0000000104b2dbd8 _ZN6duckdb20CardinalityEstimator18UpdateTotalDomainsERNS_8JoinNodeERNS_15LogicalOperatorE + 1828
5   duckdb 0x0000000104b298c4 _ZN6duckdb20CardinalityEstimator29InitCardinalityEstimatorPropsERNS_6vectorINS_6NodeOpELb1EEERNS1_INS_10unique_ptrINS_10FilterInfoENSt3__114default_deleteIS6_EELb1EEELb1EEE + 824
6   duckdb 0x0000000104b177f0 _ZN6duckdb18JoinOrderOptimizer8OptimizeENS_10unique_ptrINS_15LogicalOperatorENSt3__114default_deleteIS2_EELb1EEE + 5448
7   duckdb 0x0000000104b14618 _ZN6duckdb18JoinOrderOptimizer20ExtractJoinRelationsERNS_15LogicalOperatorERNS_6vectorINSt3__117reference_wrapperIS1_EELb1EEENS_12optional_ptrIS1_EE + 7328
8   duckdb 0x0000000104b16548 _ZN6duckdb18JoinOrderOptimizer8OptimizeENS_10unique_ptrINS_15LogicalOperatorENSt3__114default_deleteIS2_EELb1EEE + 672
9   duckdb 0x0000000104c53ae0 _ZNSt3__110__function6__funcIZN6duckdb9Optimizer8OptimizeENS2_10unique_ptrINS2_15LogicalOperatorENS_14default_deleteIS5_EELb1EEEE4$_11NS_9allocatorIS9_EEFvvEEclEv + 500
10  duckdb 0x0000000104bf9c20 _ZN6duckdb9Optimizer12RunOptimizerENS_13OptimizerTypeERKNSt3__18functionIFvvEEE + 444
11  duckdb 0x0000000104bfa20c _ZN6duckdb9Optimizer8OptimizeENS_10unique_ptrINS_15LogicalOperatorENSt3__114default_deleteIS2_EELb1EEE + 1000
12  duckdb 0x00000001076266f0 _ZN6duckdb13ClientContext23CreatePreparedStatementERNS_17ClientContextLockERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS_10unique_ptrINS_12SQLStatementENS3_14default_deleteISD_EELb1EEEPNS_6vectorINS_5ValueELb1EEE + 2024
13  duckdb 0x00000001077ad784 _ZNSt3__110__function6__funcIZN6duckdb13ClientContext15PrepareInternalERNS2_17ClientContextLockENS2_10unique_ptrINS2_12SQLStatementENS_14default_deleteIS7_EELb1EEEE3$_1NS_9allocatorISB_EEFvvEEclEv + 480
14  duckdb 0x000000010762cbf4 _ZN6duckdb13ClientContext32RunFunctionInTransactionInternalERNS_17ClientContextLockERKNSt3__18functionIFvvEEEb + 540
15  duckdb 0x000000010762d5c8 _ZN6duckdb13ClientContext15PrepareInternalERNS_17ClientContextLockENS_10unique_ptrINS_12SQLStatementENSt3__114default_deleteIS4_EELb1EEE + 1156
16  duckdb 0x000000010762e0b8 _ZN6duckdb13ClientContext7PrepareENS_10unique_ptrINS_12SQLStatementENSt3__114default_deleteIS2_EELb1EEE + 512
17  duckdb 0x000000010764a714 _ZN6duckdb10Connection7PrepareENS_10unique_ptrINS_12SQLStatementENSt3__114default_deleteIS2_EELb1EEE + 288
```
Unsure whether here it's JoinOrderOptimizer responsibility to be robust to this situation or it's the downstream logic in GetColumn that should be communicate failure without throwing, tentatively moving this onto @Tmonster that is the more knowledgeable in this area of the code base.

User side either ensuring table `a` is non-empty OR disabling the specific optimization (`SET disabled_optimizers TO 'join_order'`) allows to move further.

**Comment by Tmonster** [comment]
I believe this is the same issue as https://github.com/duckdb/duckdb/issues/7250. I am already working on a fix. I imagine it will land in 0.9.0

**Comment by begelundmuller** [comment]
@carlopi Thank you, we'll try to workaround the issue for now

> User side either ensuring table a is non-empty 

Just to clarify – in the original failing query and dataset I derived this from, all tables are non-empty. Though it is possible the join or where conditions filter out all rows in some of them.

**Comment by Tmonster** [comment]
Even if the table is empty, this error should not be thrown. The error is a result of attempting to grab column statistics from a column that doesn't exist. 

The presence of the left joins is most likely the culprit. If you can find a way to remove them then the query should run, if not, then Carlo's suggestion to turn off the join order optimizer should work.

**Comment by begelundmuller** [comment]
Thank you. Sadly we can't alter the query (it's partially user-provided) and turning off join order optimization unfortunately kills performance on some other queries (we're serving dashboards). For now, we're working on containing the error (since it's internal, it invalidates the whole DB for the duration of the handle), but looking forward to the fix :)
