### ISSUE TITLE
reading from gzip file is painfully slow

### ISSUE THREAD

**Issue by sudssf** [duckdb/duckdb#7906]
### What happens?

following takes really long time .... 
```
%%time
import duckdb

con = duckdb.connect(database=':memory:')
con.execute("SET memory_limit='4096MB'")
con.execute(f"CREATE TABLE data AS SELECT * FROM read_json_auto('/tmp/data.json.gz', ignore_errors=true)")
result = con.execute("SELECT COUNT(*) FROM data")
print(f"Number of rows in data: {result.fetchone()[0]}")
print(f"execute done")

```
when I unzip and read it takes ~ 5 seconds
```
import gzip
import shutil
with gzip.open('/tmp/data.json.gz', 'rb') as f_in:
    with open('/tmp/data.json', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)
```

following takes 5 seconds
```
%%time
import duckdb

con = duckdb.connect(database=':memory:')
con.execute("SET memory_limit='4096MB'")
con.execute(f"CREATE TABLE data AS SELECT * FROM read_json_auto('/tmp/data.json', ignore_errors=true)")
result = con.execute("SELECT COUNT(*) FROM data")
print(f"Number of rows in data: {result.fetchone()[0]}")
print(f"execute done")

```
-rw-r--r-- 1 747M  data.json
-rw-r--r-- 1 68M data.json.gz

```

```

### To Reproduce

```
%%time
import duckdb

con = duckdb.connect(database=':memory:')
con.execute("SET memory_limit='4096MB'")
con.execute(f"CREATE TABLE data AS SELECT * FROM read_json_auto('/tmp/data.json.gz', ignore_errors=true)")
result = con.execute("SELECT COUNT(*) FROM data")
print(f"Number of rows in data: {result.fetchone()[0]}")
print(f"execute done")

```

### OS:

Ubuntu 22.04 (wsl)

### DuckDB Version:

duckdb 0.8.0

### DuckDB Client:

python

### Full Name:

Suds

### Affiliation:

developer

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
I tried to reproduce, but didn't see a significant diff between json.gz and .json.

#### Data Creation
Creates a 156MB file from https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json

```
dir = "\\mydir\\7906"

import duckdb
import gzip
import json
import requests
import json

inputjson = "https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json"
numcopies = 5
largefile=f"{dir}huge.json"
gzfile = f"{largefile}.gz"
response = requests.get(inputjson)
inputjson = response.json()
outputjson = inputjson*numcopies
with open(largefile, 'w') as f:
    json.dump(outputjson, f, indent=1)
with open(largefile, 'rb') as inf:
    with gzip.open(gzfile, 'wb') as gzf:
        gzf.writelines(inf)
```

#### Execution
```
print(f"Testing with {largefile}")
with duckdb.connect(':memory:') as con:
    con.execute("SET memory_limit='4096MB'")
    %time d1 = con.execute(f"CREATE TABLE data AS SELECT * FROM read_json_auto('{largefile}', ignore_errors=true);select count(*) from data").df()
    print("Num Rows", d1)

print(f"Testing with {gzfile}")
with duckdb.connect(':memory:') as con:
    con.execute("SET memory_limit='4096MB'")
    %time d2 = con.execute(f"CREATE TABLE data AS SELECT * FROM read_json_auto('{gzfile}', ignore_errors=true);select count(*) from data").df()
    print("Num Rows", d2)
```

#### Result

> Testing with \devstuff\7906\huge.json
> CPU times: total: 4.03 s
> Wall time: 2.43 s
> Num Rows    count_star()
> 0         56755
> Testing with \devstuff\7906\huge.json.gz
> CPU times: total: 2.67 s
> Wall time: 2.69 s
> Num Rows    count_star()
> 0         56755

**Comment by Mytherin** [comment]
As mentioned this issue has already been fixed on the latest development version/master branch.

In the future please fill in the issue form correctly or we will close your issues without addressing them.

**Comment by sudssf** [comment]
apologies , I will make sure to include test data for future reports. I did test it with latest dev version ( as per instructions, it is possible that kernel was not restarted and new version did not take effect , apologies if that is the case)
I will test some more and get back if issue persists.

**Comment by sudssf** [comment]
Thank you again @Mytherin and @paultiq . I am looking for some help and could not find email to dev mailing list and posting it here instead.

I am trying to merge bunch of json files to parquet on s3 , I think slowness in reading gzip is fixed in lastest build , but I keep getting OOM after setting memory_limit.
I get OOM even while running EXPLAIN ANALYZE SELECT COUNT(*) FROM read_json_auto('s3://<LOCATION>/*', format='newline_delimited', union_by_name=True) 

I think it should be possible to read json line by line and flush to parquet ( stream copy operation without much memory overhead)

I am looking for some pointers on how I can debug this locally , I am happy to spend some time and submit MR for this enhancement.
