### ISSUE TITLE
Sequence value query error？

### ISSUE THREAD

**Issue by ccodod** [duckdb/duckdb#7913]
### What happens?

I have created a sequence, but when using both the next value and the current value of the sequence in a SQL query, the result does not match the expected outcome.
![image](https://github.com/duckdb/duckdb/assets/83813940/e93c2d97-3275-4be3-89d3-e83c8feefd13)

**The result I expect is：**
```
TEST111AAA00001|TEST111AAA00001
TEST111AAA00002|TEST111AAA00002
TEST111AAA00003|TEST111AAA00003
```
I don't know if this is a feature or a bug?

**_I  test this case in oracle,and the result is correct,so I think this is a bug:_**
<img width="1214" alt="image" src="https://github.com/duckdb/duckdb/assets/83813940/9f90b823-8474-41c9-b5f8-70ec513b33eb">

### To Reproduce

SQL as example:
```
create sequence sss;

create table seq_test(aa varchar,bb varchar)

insert into seq_test values('111AAA','111BBB');
insert into seq_test values('222AAA','222BBB');
insert into seq_test values('333AAA','333BBB');

select concat('TEST', aa, lpad(nextval('sss'), 5, 0)) a1,
       concat('AAA', bb, lpad(currval('sss'), 5, 0))
from seq_test
```

### OS:

macOS 13.4

### DuckDB Version:

0.7.1

### DuckDB Client:

DataGrip

### Full Name:

xx.xie

### Affiliation:

DeepFin

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

Expressions in DuckDB are executed on a per-vector basis, which means `nextval` is executed in its entirety before `currval` is executed. As such, I would say this is expected behavior given DuckDB's current execution engine.

**Comment by ccodod** [comment]
> Thanks for the report!
> 
> Expressions in DuckDB are executed on a per-vector basis, which means `nextval` is executed in its entirety before `currval` is executed. As such, I would say this is expected behavior given DuckDB's current execution engine.

I understand now. It was my oversight, and from the perspective of vector calculations, it does make sense. This cannot be considered a bug.
Thanks.
