### ISSUE TITLE
ODBC: Crash calling SQLSetStmtAttr(SQL_ATTR_ROW_BIND_TYPE)

### ISSUE THREAD

**Issue by cwdehart** [duckdb/duckdb#7918]
### What happens?

We're seeing a SEGV trying to call SQLSetStmtAttr(SQL_ATTR_ROW_BIND_TYPE, <non-zero size>) in the DuckDB ODBC driver.
I've traced the issue to SQLSetStmtAttr in duckdb-master\tools\odbc\statement.cpp. This line:

`stmt->row_desc->ard->header.sql_desc_bind_type = *(SQLULEN *)value_ptr;`

is trying to dereference the passed-in value_ptr, but for this attribute the value in value_ptr is the actual SQLULEN value, NOT a pointer. This value should be stored as-is instead of being dereferenced.

### To Reproduce

rc = SQLSetStmtAttr(hstmt, SQL_ATTR_ROW_BIND_TYPE, 256, SQL_IS_UINTEGER);

### OS:

RHEL 8.4 x64

### DuckDB Version:

v0.8.0

### DuckDB Client:

ODBC 03.00.0000

### Full Name:

Chris DeHart

### Affiliation:

SAS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by maiadegraaf** [comment]
Hey, I am picking up some work on our ODBC driver. 

When using the code you provided we cannot get it to compile using C++ as 256 is an integer which cannot be converted to SQLPOINTER (aka void *). Can you maybe provide a bit more context/code on reproducing the segfault? This will also help us to permanently add this to our tests and prevent breaking in the future.

Thank you for tracing the issue to tools\odbc\statement.cpp, you are correct that the value_ptr is being cast to a SQLULEN * and is then deferenced. We are going to see if we can change that without breaking anything. As per API, it indeed expects a value, not a pointer.

**Comment by cwdehart** [comment]
Thanks for taking a look at this one.

In our production code, we just add a cast:

uint64_t  rowLen;
rowLen = 256;
rc = SQLSetStmtAttr(hstmt, SQL_ATTR_ROW_BIND_TYPE, **(SQLPOINTER)rowLen**, SQL_IS_UINTEGER);

**Comment by cwdehart** [comment]
That's not quite how SQLSetStmtAttr works.  From the API doc [here](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetstmtattr-function), the ValuePtr argument is:

```
Value to be associated with Attribute. Depending on the value of Attribute, ValuePtr will be one of the following:

- An ODBC descriptor handle.
- A SQLUINTEGER value.
- A SQLULEN value.
- A pointer to one of the following:
    -     A null-terminated character string.
    -     A binary buffer.
    -     A value or array of type SQLLEN, SQLULEN, or SQLUSMALLINT.
    -     A driver-defined value.
```
Later, in the description for SQL_ATTR_ROW_BIND_TYPE, there's this:

`An SQLULEN value that sets the binding orientation to be used when...`

This means it's passed as a value rather than a pointer.
There's also an example in the doc for row-wise binding that shows setting it [here](https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/row-wise-binding).

**Comment by maiadegraaf** [comment]
Yes, I think you are correct.  I will have a closer look and alter the code accordingly.
