### ISSUE TITLE
Crash running external hash join 

### ISSUE THREAD

**Issue by csruiliu** [duckdb/duckdb#7923]
### What happens?

I tried to run a 3-way join over `customer`, `orders`, `lineitem` of TPC-H SF-30 on a machine which has 8GB memory. The three tables are in `parquet` format which is converted from the original `tbl` using duckdb.

1. It seems that the regular hash join works but the external hash join didn't. I turned `force_external` to `true` to trigger the external hash join and tested it on v0.7.1, v0.8.0. and master branch. 

2. It seem that the new-added functions `ht.RequiresExternalJoin` and `ht.RequiresPartitioning` in v0.8.0 and master branch didn't figure out that external hash join and partitioning are required.

3. I ran the same query using TPC-H SF10 on the same machine, both regular and external works.  

Not sure if I miss anything important to lead this crash, but any investigation would be helpful.

### To Reproduce

Query: 
SELECT  C_CUSTKEY, O_ORDERKEY, L_LINENUMBER, L_QUANTITY, C_ACCTBAL, O_TOTALPRICE
FROM  	customer, orders, lineitem
WHERE	C_CUSTKEY = O_CUSTKEY
        AND	L_ORDERKEY = O_ORDERKEY
        AND CAST(O_ORDERDATE AS DATE) >= '1994-01-01'
        AND C_ACCTBAL > 100
        AND L_QUANTITY > 5

Dataset: 
I use the original TPC-H toolkit to generate the tables and convert them to parquet format using duckdb.

### OS:

Ubuntu 22.04 LTS

### DuckDB Version:

0.7.1, 0.8.0

### DuckDB Client:

Python

### Full Name:

Rui Liu

### Affiliation:

UChicago

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
We've seen issues before where DuckDB's memory count stays within the set limit, but the physical memory footprint is higher due to jemalloc. It could be that the jemalloc changes in #7697 (in the feature branch) now make DuckDB stay closer to the set memory limit. Some OOM killers are very strict (macOS is not), so maybe that's why Mark cannot reproduce.

If it was not a crash but simply an `OutOfMemoryException`, then it could be that the double-join pipeline takes more memory than we can handle (operators are currently not aware of the memory usage of other operators in a pipeline), but I doubt that since Mark can't reproduce.

Finally, did you set a temp directory using this?
```sql
PRAGMA temp_directory='/tmp/duckdb';
```

**Comment by csruiliu** [comment]
Thanks @Mytherin @lnkuiper for your prompt response. I also suspect that the issue is relevant to memory allocation or killing policy (very close to what @lnkuiper mentioned, but not 100% sure). I provide more details here in case I messed up or misunderstood anything.

1. Yes, I think "crash" refers to OOM killer is triggered (`Killed`), I should have mentioned this in the initial post.
2. I didn't set a temp directory since I assume DuckDB would do it by default. But I just tried by calling Python API `db_conn.execute("PRAGMA temp_directory='/tmp/duckdb'")`, still got the issue.
3. When I ran the query using v0.8.0 and master branch (with `force_external=false`), DuckDB didn't trigger the external and partition--both `ht.RequiresExternalJoin` and `ht.RequiresPartitioning` return `false`. However, I assume both should be `true` since the machine has only 8GB memory in total but overall size of `customer.parquet`, `orders.parquet`, and `lineitem.parquet` of SF-30 is more than 10GB. I could be wrong if DuckDB has a very efficient and aggressive memory management strategy.  
4. I set `row_group_size` as 30,000 when converting `tbl` to `parquet` using DuckDB. All the tables have been persisted in a `duck.db` so the database is opened and connected by invoking `duckdb.connect(database="duck.db")`.

**Comment by Mytherin** [comment]
> When I ran the query using v0.8.0 and master branch (with force_external=false), DuckDB didn't trigger the external and partition--both ht.RequiresExternalJoin and ht.RequiresPartitioning return false. However, I assume both should be true since the machine has only 8GB memory in total but overall size of customer.parquet, orders.parquet, and lineitem.parquet of SF-30 is more than 10GB. I could be wrong if DuckDB has a very efficient and aggressive memory management strategy.

The external hash join is only necessary when the hash tables do not fit in memory. In this query, a hash table is built on `customer` and `orders` only. Moreover, it is only built on a *subset* of these tables as not all columns are required. As such, it is very likely the hash tables comfortably fit in 8GB memory and the strategy of not using an out-of-core hash join is correct.

As for the issue, I would consider this addressed. Running out of memory when using verification settings that explicitly stress test the system is not an actual problem in my view.
