### ISSUE TITLE
Python API - cursor does not have a 'rowcount' attribute

### ISSUE THREAD

**Issue by rdnielsen** [duckdb/duckdb#7924]
### What happens?

When attempting to retrieve the 'rowcount' attribute from the cursor after executing a SELECT statement, the following error is reported:

AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'rowcount'.

The Python DB-API specifies 'rowcount' to be a read-only attribute of the cursor.

The absence of this attribute breaks code that relies on conformance to the DB-API.

### To Reproduce

import duckdb
conn = duckdb.connect("some_file.duckdb")
curs = conn.cursor()
ret = curs.execute("select something from some_table;")
curs.rowcount

### OS:

Linux (Pop! OS) X64

### DuckDB Version:

0.8.0

### DuckDB Client:

Python 3.10.6

### Full Name:

Dreas Nielsen

### Affiliation:

Integral Consulting Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Since we do not know the row count in the general case, we can just add the -1 there as permitted by the spec:

> The attribute is -1 in case no [.execute*()](https://peps.python.org/pep-0249/#id19) has been performed on the cursor or the rowcount of the last operation is cannot be determined by the interface. [[7]](https://peps.python.org/pep-0249/#id55)

**Comment by hannes** [comment]
See #8911

**Comment by hannes** [comment]
This was added
