### ISSUE TITLE
Problems with unnest?

### ISSUE THREAD

**Issue by davidjbrennan** [duckdb/duckdb#7927]
### What happens?

In writing some SQL code to find the list intersection of two columns, depending on which style of query I use, DuckDB fails with an "INTERNAL Error".

Running the same queries on Postgresql produces the correct results.

### To Reproduce

Firstly we will create the data to be used by all three queries.

```
create temp table if not exists tbl as 
	select * 
		from (values 
			('a', array[4,5,5], array[5,7]), 
			('b', array[2,3], array[1,2,3,4]),
			('c', array[2,3], array[4]) 
		) t(k,a,b);
```
```
┌─────────┬───────────┬──────────────┐
│    k    │     a     │      b       │
│ varchar │  int32[]  │   int32[]    │
├─────────┼───────────┼──────────────┤
│ a       │ [4, 5, 5] │ [5, 7]       │
│ b       │ [2, 3]    │ [1, 2, 3, 4] │
│ c       │ [2, 3]    │ [4]          │
└─────────┴───────────┴──────────────┘
```
The first query unnests the arrays in columns 'a' and 'b' and makes use of the standard SQL INTERSECT operator to find the intersecting values.
```
select k, a, b, 
	array(
		select unnest(a) intersect select unnest(b)
	) ab_intersect 
	from tbl;
```
This query works without error and produces the following result.
```
┌─────────┬───────────┬──────────────┬──────────────┐
│    k    │     a     │      b       │ ab_intersect │
│ varchar │  int32[]  │   int32[]    │   int32[]    │
├─────────┼───────────┼──────────────┼──────────────┤
│ a       │ [4, 5, 5] │ [5, 7]       │ [5]          │
│ b       │ [2, 3]    │ [1, 2, 3, 4] │ [2, 3]       │
│ c       │ [2, 3]    │ [4]          │ []           │
└─────────┴───────────┴──────────────┴──────────────┘

```
The second query unnests column 'a' and tests the values against column 'b' using the WHERE = ANY construct.
```
select k, a, b, 
	array(
		select distinct ax 
			from unnest(a) ta(ax) 
			where ax = any(b)
	) ab_intersect 
	from tbl;

```
Running this query produces the following error:

`Error: INTERNAL Error: Failed to bind column reference "b" [8.3] (bindings: [14.0 8.1])
`

Due to the error, I had to quit and restart DuckDB and then create the data table.

The third query is very similar to the second but instead uses the WHERE IN (SELECT FROM) construct.
```
select k, a, b, 
	array(
		select distinct ax 
			from unnest(a) ta(ax) 
			where ax in (select bx from unnest(b) tb(bx))
	) ab_intersect from tbl;

```
Running this query produces a different error:
`Error: INTERNAL Error: Expression with depth > 1 detected in non-lateral join`

### OS:

macOS Ventura 13.4 (M1)

### DuckDB Version:

v0.8.1-dev425

### DuckDB Client:

CLI

### Full Name:

David Brennan

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taniabogatsch** [comment]
Hi @davidjbrennan, thanks for the bug report! I can reproduce this, and there is a bug in the binder.

For now, you can rewrite your query to this, which is semantically identical to yours, and might yield better performance.
```sql
SELECT k, a, b,
	ARRAY (
		SELECT DISTINCT ax
		FROM (SELECT UNNEST(a)) AS ta(ax)
		WHERE ax = ANY(b)
	) ab_intersect
FROM tbl;
----
┌─────────┬───────────┬──────────────┬──────────────┐
│    k    │     a     │      b       │ ab_intersect │
│ varchar │  int32[]  │   int32[]    │   int32[]    │
├─────────┼───────────┼──────────────┼──────────────┤
│ a       │ [4, 5, 5] │ [5, 7]       │ [5]          │
│ b       │ [2, 3]    │ [1, 2, 3, 4] │ [2, 3]       │
│ c       │ [2, 3]    │ [4]          │ []           │
└─────────┴───────────┴──────────────┴──────────────┘
```

**Comment by davidjbrennan** [comment]
Thanks for the quick reply @taniabogatsch.

Any thoughts on why the third of my queries produced the "Error: INTERNAL Error: Expression with depth > 1 detected in non-lateral join" error?

**Comment by taniabogatsch** [comment]
We throw `INTERNAL` exceptions for code paths that should not happen, i.e., that indicate a bug. I think this one is related to the previous `INTERNAL` exception; the binding probably goes wrong somewhere, which causes this later down the line.

For now, if you replace all `UNNEST(...)` with `(SELECT UNNEST(...))`, it should be semantically the same query and fix/omit the bug.

```sql
SELECT k, a, b,
	array (
		SELECT DISTINCT ax
		FROM (	SELECT UNNEST(a)) ta(ax)
				WHERE ax IN (SELECT bx FROM (SELECT UNNEST(b)) tb(bx))
	) ab_intersect 
FROM tbl;
```

**Comment by davidjbrennan** [comment]
Thanks @taniabogatsch for the advice on the work-around.

**Comment by l1t1** [comment]
it's better if duckdb support instersect operation on lists.

**Comment by l1t1** [comment]
it's better if duckdb support instersect operation on lists.

**Comment by taniabogatsch** [comment]
We support rewrites for `list_intersect`: https://github.com/duckdb/duckdb/pull/7518.

**Comment by davidjbrennan** [comment]
All the issues originally raised are no longer present in v1.0.1-dev2164.
