### ISSUE TITLE
list_intersect doesn't exist.

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#7936]
### What happens?

from https://duckdb.org/docs/sql/functions/nested, 
<html>
<body>

list_intersect(list1, list2) | Returns a list of all the elements that exist in both l1 and l2, without duplicates. | list_intersect([1,2,3], [2,3,4]) | [2, 3]
-- | -- | -- | --

</body>
</html>

but  it shows in CLI as following

```
D select list_intersect([1,2,3], [2,3,4]);
Error: Catalog Error: Scalar Function with name list_intersect does not exist!
Did you mean "list_first"?
LINE 1: select list_intersect([1,2,3], [2,3,4]);
               ^
D select version();
┌───────────┐
│ version() │
│  varchar  │
├───────────┤
│ v0.8.1    │
└───────────┘
```

### To Reproduce

input `select list_intersect([1,2,3], [2,3,4]);` at CLI

### OS:

windows7 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
The PR adding list_intersect (https://github.com/duckdb/duckdb/pull/7518) has been merged on feature branch, that imply will be included in the next release.

If you want to try it out, you will have to build from source (selecting feature as branch).

Here the documentation has gone live before time, thanks for noticing, it will be reverted.

**Comment by taniabogatsch** [comment]
This works as a workaround until the next release: `list_filter(l1, (x) -> list_contains(l2, x))`
