### ISSUE TITLE
Correctness issues reading unconsolidated Pandas DataFrames

### ISSUE THREAD

**Issue by dylanscott** [duckdb/duckdb#7937]
### What happens?

When querying a Pandas DataFrame whose internal BlockManager has not "consolidated" its blocks, you get garbled results where values for columns within a block may be interleaved.

This was kind of elusive to track down because it depends on Pandas internals that I don't really understand, but it was encountered by one of our end users using duckdb against a manually constructed DataFrame. It's particularly tricky because the concept of "blocks" and "consolidation" doesn't appear to be part of the public API and consolidation can be triggered easily by a variety of operations - for example taking a shallow `.copy()` will consolidate and fix the issue (even merely accessing the `_values` property on a DataFrame triggers an in-place consolidation and stops the issue).

### To Reproduce

Here's a minimal reproduction I was able to isolate. I can't say I endorse this code - it's kind of a weird way to build a DataFrame, but it seems to be valid Pandas and it results in a value that duckdb is unable to read correctly.

```python
import pandas as pd

df = pd.DataFrame(columns=["idx", "evens", "zeros"])

df["idx"] = list(range(10))
for col in df.columns[1:]:
    df[col].values[:] = 0

counter = 0
for i in range(10):
    df.loc[df["idx"] == i, "evens"] += counter
    counter += 2
```

Printing this value looks as you would expect:

```
> print(df)
   idx evens zeros
0    0     0     0
1    1     2     0
2    2     4     0
3    3     6     0
4    4     8     0
5    5    10     0
6    6    12     0
7    7    14     0
8    8    16     0
9    9    18     0
```

But - ~~and this seems critical somehow~~ EDIT: actually see below - if you inspect the value of `df._mgr._is_consolidated` you will see that it is `False`. And querying the DataFrame with duckdb seems to interleave values of the `evens` and `zeros` columns:

```python
import duckdb

with duckdb.connect(database=':memory:') as conn:
    print(conn.execute("select * from df").df())
```

which prints

```
   idx  evens  zeros
0    0      0      0
1    1      0      2
2    2      2      0
3    3      0      4
4    4      4      0
5    5      0      6
6    6      6      0
7    7      0      8
8    8      8      0
9    9      0     10
```

~~As I said anything that triggers "consolidation" stops the issue, e.g.~~

EDIT: Actually see the comment below - I'm not sure consolidation is what if fixing per se. It turns out `.copy()` is deep by default and doing a shallow copy with `deep=False` produces a similarly broken DataFrame and even calling `df2._mgr._consolidate_inplace()` doesn't fix it - you get `df2._mgr._is_consolidated=True` after but the output of querying with duckdb is still mangled so the block consolidation stuff may be a red herring

```python
df2 = df.copy()
print(df2._mgr._is_consolidated)
with duckdb.connect(database=':memory:') as conn:
    print(conn.execute("select * from df2").df())
```

➡️ 

```
True
   idx  evens  zeros
0    0      0      0
1    1      2      0
2    2      4      0
3    3      6      0
4    4      8      0
5    5     10      0
6    6     12      0
7    7     14      0
8    8     16      0
9    9     18      0
```

### OS:

macOS, Linux

### DuckDB Version:

0.7.1, 0.8.1

### DuckDB Client:

Python

### Full Name:

Dylan Scott

### Affiliation:

Hex Technologies

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the detailed info, I'll look into it soon 👍
