### ISSUE TITLE
Out of Memory Error: failed to allocate data of size 67.1MB (13.4GB/13.4GB used)

### ISSUE THREAD

**Issue by sirliu** [duckdb/duckdb#7958]
### What happens?

I was trying to calculate the hierarchical relationship of a table with `7733217` records(lots of hierarchical relationship) using the following code. However, after running for a while, I received an error stating that the memory was exhausted. I thought that when the memory usage reaches the set limit, it would automatically enable the use of cache files to compensate for the insufficient memory. BTW,My laptop has 16GB of memory.
```sql
WITH RECURSIVE datas_cte AS (
  SELECT id, 
         pid, 
         ARRAY[id] as path, 
         0 as level,
         id as rootid
  FROM datas
  WHERE pid IS NULL
  UNION ALL
  SELECT d.id, 
         d.pid, 
         c.path || ARRAY[d.id], 
         c.level + 1,
         c.rootid
  FROM datas d
  JOIN datas_cte c ON d.pid = c.id
)
UPDATE datas
SET path = datas_cte.path, 
    level = datas_cte.level, 
    rootid = datas_cte.rootid
FROM datas_cte
WHERE datas.id = datas_cte.id;
```

### To Reproduce

ignore it......

### OS:

WIN

### DuckDB Version:

0.8

### DuckDB Client:

dbeaver

### Full Name:

ignore

### Affiliation:

ignore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Please fill out the issue template completely or we will not help you.
