### ISSUE TITLE
`read_parquet` does not work when credentials are passed in for public files

### ISSUE THREAD

**Issue by pyrito** [duckdb/duckdb#7970]
### What happens?

`read_parquet` doesn't seem to work for public files when AWS credentials are passed in via environment variables. Typically we can get around this by passing in `{'anon':True}` in pandas, but it doesn't look like we have the option here? In the reproducer we pass in invalid credentials to show the error, but we get the same issue when we pass in valid credentials as well. 

### To Reproduce

You'll need to try these in two separate sessions:
```python
import os
import duckdb

os.environ["AWS_DEFAULT_REGION"] = "us-west-2"
os.environ["AWS_CONFIG_FILE"] = "invalid"
os.environ["AWS_SHARED_CREDENTIALS_FILE"] = "invalid"

os.environ["AWS_ACCESS_KEY_ID"] = "invalid"
os.environ["AWS_SECRET_ACCESS_KEY"] = "invalid"

duckdb.sql("INSTALL httpfs; LOAD httpfs;")

# Fails with error
duckdb.sql("SELECT * FROM read_parquet(\"s3://modin-datasets/testing/test_data.parquet\")")
```

But this works without any environment variables set
```python
import os
import duckdb

duckdb.sql("INSTALL httpfs; LOAD httpfs;")

# Works as expected
duckdb.sql("SELECT * FROM read_parquet(\"s3://modin-datasets/testing/test_data.parquet\")")
```

### OS:

macOS 12.2.1 arm64

### DuckDB Version:

0.8.2.dev11

### DuckDB Client:

Python

### Full Name:

Karthik Velayutham

### Affiliation:

Ponder

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by mvashishtha** [comment]
Could someone familiar with this repo please take a look? @Mytherin

**Comment by mvashishtha** [comment]
Anyone there? @Mause  @pdet

**Comment by Mause** [comment]
This looks like a feature request, not a bug report?

**Comment by mvashishtha** [comment]
> This looks like a feature request, not a bug report?

I think so.

**Comment by mvashishtha** [comment]
I don't like that this issue was closed automatically. Here is some content explaining why:

- https://github.com/godotengine/godot-proposals/issues/3481#issuecomment-954992006
- https://drewdevault.com/2021/10/26/stalebot.html
- https://news.ycombinator.com/item?id=28998374

**Comment by Mause** [comment]
@mvashishtha this was incorrectly filed as a bug report, when it should have been a feature request. We don't auto close feature requests

**Comment by mradamcox** [comment]
I recently encountered this as well... I am trying to query a public S3 bucket, but I also have `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` set for use elsewhere in my application and because of that my query fails.

When I run:

```
import duckdb

duckdb.sql("INSTALL httpfs; LOAD httpfs;")
duckdb.sql("SELECT COUNT(1) FROM read_parquet('s3://overturemaps-us-west-2/release/2023-11-14-alpha.0/theme=places/type=*/*', filename=true, hive_partitioning=1);")
```

I get the following error:

```
duckdb.duckdb.HTTPException: HTTP Error: HTTP GET error on '/?encoding-type=url&list-type=2&prefix=release%2F2023-11-14-alpha.0%2Ftheme%3Dplaces%2Ftype%3D' (HTTP 400)
```

If I unset these environment variables before making the connection, then the query completes as expected.

```
import os
import duckdb

os.unsetenv("AWS_ACCESS_KEY_ID")
os.unsetenv("AWS_SECRET_ACCESS_KEY")

duckdb.sql("INSTALL httpfs; LOAD httpfs;")
duckdb.sql("SELECT COUNT(1) FROM read_parquet('s3://overturemaps-us-west-2/release/2023-11-14-alpha.0/theme=places/type=*/*', filename=true, hive_partitioning=1);")
```

Is there somewhere else I should file this? The HTML error message wasn't especially helpful in this case so it took a while to track this down.

**Comment by am2222** [comment]
I found that there is some issue with `aws` extenstion. As If I run this sql
```

INSTALL aws;
INSTALL httpfs;
LOAD aws;
LOAD httpfs;

CALL load_aws_credentials();

SELECT COUNT(1) FROM read_parquet('s3://overturemaps-us-west-2/release/2023-11-14-alpha.0/theme=places/type=*/*', filename=true, hive_partitioning=1);

```

it raises `400` error and if I remove `CALL load_aws_credentials();` it works with no issues

**Comment by cvargas-xbrein** [comment]
same issue im trying to attach a .duckdb file from a s3  or read a parquet
![image](https://github.com/user-attachments/assets/b3405d95-76af-4bb8-ad09-025edf71c5a1)

**Comment by hadjali417** [comment]
I'm getting the same error (HTTP 400)!
versions:
     dbt-core: 1.9.2
     plugins:
        -duckdb. 1.9.2

Any news on this topic?
