### ISSUE TITLE
Unable to use decimal values in table functions

### ISSUE THREAD

**Issue by ak-coram** [duckdb/duckdb#7979]
### What happens?

When I try to use decimal columns in a table function and copy values according to the `duckdb_decimal` struct, I get the following error: `Unsupported type for ColumnDataCollection::GetCopyFunction`

### To Reproduce

See above.

### OS:

Linux 6.3.6_1 on x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Common Lisp

### Full Name:

Ákos Kiss

### Affiliation:

Third-party binding dev.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ak-coram** [comment]
Is this not supported? Am I missing something?

**Comment by Tishj** [comment]
I'm sorry but this really isn't helpful:
```
To Reproduce
See above.
```

You're needlessly making it harder to investigate the issue when you likely have a working reproduction lying around, otherwise you wouldn't run into this issue.

**Comment by ak-coram** [comment]
@Tishj: I only have code to reproduce this in Common Lisp, if you can work with that I'll gladly provide an example.

**Comment by Mause** [comment]
An idea of what you're calling, with which values, would be helpful at the very least. A snippet of C code would be best though

**Comment by ak-coram** [comment]
@Mause I'm copying the same structs I get when querying via the data chunks API and none of them work:
https://github.com/ak-coram/cl-duckdb/blob/main/duckdb-static-table.lisp#L225 

I can try to come up with a C example, but it may take a while since I'm not well-versed in C. If this was a bug I would have expected invalid values, but the error message lead me to believe this doesn't work at all, that's why I submitted this issue.

**Comment by Mause** [comment]
The issue is it's not clear at all where and how you're triggering the error message - it should definitely be supported, but we need to know which C API methods you're calling to get this error. Even pseudocode with the methods you're calling would be helpful

**Comment by ak-coram** [comment]
I guess the easiest way to reproduce is to build upon https://github.com/duckdb/duckdb/blob/main/test/api/capi/capi_table_functions.cpp and add more result types instead of just `BIGINT`. Most types (all integer types, booleans, floats, strings, UUIDs and even date & time values) work just fine in my [tests](https://github.com/ak-coram/cl-duckdb/blob/main/duckdb-test.lisp#L495) except for decimals.

I'm not familiar with other language bindings, but does any other binding support this via the C API?

**Comment by Mause** [comment]
To answer your question about usage examples, here's the Julia one, where the support was originally added: https://github.com/duckdb/duckdb/commit/eb8541355b01e42d4eea648a3fc48cf4f9b0133e

**Comment by ak-coram** [comment]
I'll try to reproduce based on the Julia example, I'm guessing the issue is that instead of using `duckdb_create_decimal_type`, I call `duckdb-create-logical-type` with type `DUCKDB_TYPE_DECIMAL`
