### ISSUE TITLE
arrowIPCAll crashes with some queries

### ISSUE THREAD

**Issue by jheer** [duckdb/duckdb#7988]
### What happens?

When querying for an Arrow buffer in the Node.js API, I'm seeing some queries fail with a complete DuckDB crash. This error appears to be new as of DuckDB v0.8.1.

The resulting error is:

```
[Error: INTERNAL Error: BatchedDataCollection::Merge error - batch index 9223372036854775807 is present in both collections. This occurs when batch indexes are not uniquely distributed over threads] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR',
  errorType: 'INTERNAL'
}
```

### To Reproduce

The following JavaScript code should reproduce the error. Note that the error does not occur when calling `con.all` instead of `con.arrowIPCAll`.

```js
import duckdb from 'duckdb';

const db = new duckdb.Database(':memory:');
const con = db.connect();

// load extensions and base data table
const initSQL = `
  INSTALL arrow; INSTALL httpfs; LOAD arrow; LOAD httpfs;
  CREATE TABLE stocks AS (
    SELECT
      row_number() OVER (PARTITION BY Symbol ORDER BY Date) AS Index,
      Close,
      Symbol
    FROM 'https://uwdata.github.io/mosaic-datasets/data/stocks.csv'
  );
`;

// query for time series with AM4 optimization (simplified for bug report)
const querySQL = `
 SELECT MIN(Index) AS Index, ARG_MIN(Close, Index) AS Close, Symbol FROM stocks GROUP BY Index, Symbol
 UNION
  SELECT MAX(Index) AS Index, ARG_MAX(Close, Index) AS Close, Symbol FROM stocks GROUP BY Index, Symbol
 UNION
  SELECT ARG_MIN(Index, Close) AS Index, MIN(Close) AS Close, Symbol FROM stocks GROUP BY Index, Symbol
 UNION
  SELECT ARG_MAX(Index, Close) AS Index, MAX(Close) AS Close, Symbol FROM stocks GROUP BY Index, Symbol
 ORDER BY Symbol, Index
`;

// issue queries
con.exec(initSQL, (err) => {
  if (err) {
    console.error(err);
  } else {
    con.arrowIPCAll(querySQL, (err, result) => {
      if (err) {
        console.error(err);
      } else {
        console.log('SUCCESS!', result);
      }
    });
  }
});
```

### OS:

MacOS

### DuckDB Version:

0.8.1

### DuckDB Client:

nodejs

### Full Name:

Jeffrey Heer

### Affiliation:

University of Washington

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jheer** [comment]
Update: I found that this simpler query also replicates the issue, so a `UNION` does not seem to be part of the issue. **If you remove the `ORDER BY` clause, the query completes successfully.**

``` js
const querySQL = `
 SELECT MIN(Index) as Index, MAX(Close), Symbol FROM stocks
 GROUP BY Symbol, Index / 4.0
 ORDER BY Symbol, Index
`;
```

**Comment by pmm-motif** [comment]
I run into another occurrence of this problem on UNION ALL statement: https://github.com/duckdb/duckdb/issues/8944
