### ISSUE TITLE
:lady_beetle:  v0.8.1 > HTTPFS >  "httpfs.duckdb_extension" could not be loaded because its signature is either missing

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#8002]
### What happens?

1. :heavy_check_mark:  Open a transient duckdb (`v0.8.1 6536a77232`) session
2.  :heavy_check_mark: `INSTALL httpfs;`
3. :-1: `LOAD httpfs;`

lead to:

```
Error: IO Error: Extension "/home/adriens/.duckdb/extensions/v0.8.1/linux_amd64/httpfs.duckdb_extension"
could not be loaded because its signature is either missing or invalid and unsigned extensions are disabled
by configuration.
Start the shell with the -unsigned parameter to allow this (e.g. duckdb -unsigned).
```

### To Reproduce

1. :heavy_check_mark:  Open a transient duckdb (`v0.8.1 6536a77232`) session
2.  :heavy_check_mark: `INSTALL httpfs;`
3. :-1: `LOAD httpfs;`

lead to:

```
Error: IO Error: Extension "/home/adriens/.duckdb/extensions/v0.8.1/linux_amd64/httpfs.duckdb_extension"
could not be loaded because its signature is either missing or invalid and unsigned extensions are disabled
by configuration.
Start the shell with the -unsigned parameter to allow this (e.g. duckdb -unsigned).
```
... then switch to `-unsigned` but : 

![image](https://github.com/duckdb/duckdb/assets/5235127/a12e7444-f01f-44a4-87cb-3aa0b75a7870)

### OS:

Linux Mint 21.1 Vera

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

duckdb cli

### Full Name:

Adrien SALES

### Affiliation:

https://dev.to/adriens

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This sounds like the original installation failed somehow and left an empty or corrupted file. If you delete the httpfs extension file in question and try installing it again, does it work?

**Comment by adriens** [comment]
Hi @Mause , I have : 

1.  manually deleted the extension
2. uninstalled my `brew` install
3. installer with [`tea`](https://tea.xyz/+duckdb.org/)

Then I got back the `v0.7.1 b00b93f0b1` and it worked. (same bahivio on killercoda Ubuntu plaground)

Finally reinstalled (with empty extensions dir) **and it worked** : don't know why this happend :thought_balloon: 

Hopefully I'll be the only one.

Thank you for your help.
