### ISSUE TITLE
Memory leak when using single thread or 2 threads, 3 or more the issue goes away

### ISSUE THREAD

**Issue by WyattLiu** [duckdb/duckdb#8004]
### What happens?

I am running a TPCH 10G size that typically uses about 13.5GB in 0.8.1. However, when I configure the DB to run with one thread or two threads, the ram RSS shoots to more than 20GB. I guessed the memory leak is that I dropped a counter for RSS as global var and confirmed when it duckdb tears down, calling the destructor, parsing the RSS (/proc/self/statm [1]) is still at about 7.3GB. The Peak RSS confirmed with HTOP too.

### To Reproduce

TPCH, running with SET threads TO 1; More memory is needed. Same as 2.

### OS:

Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Zongxin Liu

### Affiliation:

University of Toronto

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] I agree

**Comment by Mytherin** [comment]
Thanks for the report - could you verify the issue is there on the `feature` branch as well? This is most likely not a memory leak but related to jemalloc not releasing the memory eagerly enough (see #7697).

**Comment by WyattLiu** [comment]
I wrote a general-purpose memory allocator and plugged in duckdb for testing. What I see is that 1 or 2 thread setting indeed asks for more memory for no good reason, I was wondering if there is something wrong on my code, and then I double-check what happens with the native duckdb jemalloc build, watching at htop and it behaves the same.

Plugin any memory allocation is changed code inside src/common/allocator and Cmakelists, thank you guys for making it so convenient.

Yes, I am a bit faster than jemalloc with a similar RAM foot-print, I guess jemalloc is pretty aggressive in giving back memory thus making it slower (off-topic).

I have no good suspicion why this is the case, 1 or 2 threads RAM footprint is vastly different from 3 threads or more.

**Comment by WyattLiu** [comment]
Bug still exists, but like no one use it for single thread
