### ISSUE TITLE
Convert dsdgen into extensions

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#801]
Then add the functionality they provide as a stored procedure, e.g.

```sql
CALL dsdgen(1);
```

We also need to add Windows support for them.

**Comment by jtommaney-alibaba** [comment]
as a stored proc is good idea.  

Maybe consider modifying dbgen to emit based on ascending date as an additional option.  TPCH standard is fully random, but load by "generally" ascending date reflects more real-world use cases.

**Comment by Mytherin** [comment]
That's a good idea indeed, thanks for the feedback.

**Comment by Mytherin** [comment]
Done for TPC-H now
