### ISSUE TITLE
Java JDBC Stability Suggestion

### ISSUE THREAD

**Issue by ryanhamilton** [duckdb/duckdb#8025]
### What happens?

Your code for loading a .dll/.so from temp, unpacks a temporary .so/.dll and then loads it:
https://github.com/duckdb/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBNative.java#L45

On some systems, this will cause permissions issues. 
I've seen users complain about this with more popular java libraries, e.g.:
https://github.com/JFormDesigner/FlatLaf/issues/624
It causes the progam not to work.

I have not recreated this issue myself as I do not run in a protected environment, I just happened to read your code and knew about this issue from elsewhere.

### To Reproduce

Load JDBC in environment "with proper Application Whitelisting enabled"

### OS:

Windows

### DuckDB Version:

Current

### DuckDB Client:

Java

### Full Name:

Ryan Hamilton

### Affiliation:

TimeStored.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
I've read through that thread, it looks like there are no great alternatives here, or do you have a specific suggestion?

**Comment by benjaminyin01** [comment]
read dll/so into memory, and then load it from memory

**Comment by Mause** [comment]
> read dll/so into memory, and then load it from memory

That isn't possible in native java

**Comment by ryanhamilton** [comment]
@hannes  

Allow picking up the .dll/.so from a default or configured location and then fallback to the unzipping.
I currently provide software that users can download and run themselves. 
I create a setup.exe for windows.
To prevent this problem, during java build I remove the .dll from the .jar. I move it to be bundled in the directory that gets installed and it gets picked up there.

**Comment by ryanhamilton** [comment]
I tried to find similar instances and recommendations but there isn't mcu information. I found sqlite and others suffered some issues with signing: https://github.com/xerial/sqlite-jdbc/issues/383

**Comment by hannes** [comment]
I'm fine with reading a system property that points to an alternative binary location for the load. Happy to look at a PR.
