### ISSUE TITLE
Memory leak during chunked cursor iteration

### ISSUE THREAD

**Issue by 2-5** [duckdb/duckdb#8033]
### What happens?

I'm reading from a result set using chunks, and the memory used by DuckDB keeps increasing.

### To Reproduce

You need to replace the db path in the code with the location of a large database so that the leak is noticeable in memory monitors.

```python
import duckdb

conn = duckdb.connect("large.duckdb")

query = "SELECT * FROM table"
chunk_size = 1_000_000

# fetch_df_chunk
cursor = conn.execute(query)
while True:
    chunk_df = cursor.fetch_df_chunk(chunk_size // 2048)
    print(len(chunk_df))

# fetch_record_batch
batch_iter = conn.execute(query).fetch_record_batch(chunk_size)
for batch in batch_iter:
    print(batch.num_rows)
```

### OS:

Windows 10 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python 3.11

### Full Name:

2-5

### Affiliation:

2-5

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
I wonder if this is related to #7856, although that was arrow and this is df.

**Comment by 2-5** [comment]
It happens when using arrow too, see second part with `fetch_record_batch` which returns a `pyarrow.ipc.RecordBatchStreamReader`
