### ISSUE TITLE
SIGSEGV when openning RocksDB after DuckDB in Java

### ISSUE THREAD

**Issue by keimoon** [duckdb/duckdb#8054]
### What happens?

I tried a very simple Java program that open a DuckDb database, then RocksDb database but it crashed every time. The weird part is the program runs fine if I open only DuckDb or RocksDb; or I open RocksDb before DuckDb.

It may involve something strange with my system setup so I tried to reproduce it inside a clean Fedora docker image (from Docker hub). The result is:

Fedora 38 (libstdc++ 6.0.32): Crash every time
Fedora 37 (libstdc++ 6.0.30): Crash every time
Fedora 36 (libstdc++ 6.0.30): Success
Ubuntu 23.04 (libstdc++ 6.0.31): Success

The root cause of this bug is perhaps DuckDB's JNI library includes libstdc++ inside the .so file, so it crashes with the JNI library of RocksDB (and possibly other JNI libraries too).

### To Reproduce

Create a simple Java program that open a DuckDb database, then a RocksDb database.
For example:
```
package test.duckrock;

import org.rocksdb.RocksDB;

import java.sql.DriverManager;

public class DuckRock {
    public static void main(String[] args) throws Exception {
        DriverManager.getConnection(
                "jdbc:duckdb:/tmp/test.duck"
        );
        RocksDB.open("/tmp/test.rock");
    }
}
```

### OS:

Fedora 38

### DuckDB Version:

0.8.1

### DuckDB Client:

0.8.1

### Full Name:

Tam Nguyen

### Affiliation:

Anduin Transactions

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you please test with the latest master build? We've just changed to not statically linking libc++

Java master builds are available in the sonatype snapshots repository, which can be accessed with the following:

```xml
<dependency>
	<groupId>org.duckdb</groupId>
	<artifactId>duckdb_jdbc</artifactId>
	<version>0.9.0-SNAPSHOT</version>
</dependency>

...

<repositories>
	<repository>
		<id>oss-sonatype</id>
		<name>oss-sonatype</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
```

**Comment by keimoon** [comment]
Retested and confirm it was fixed with the latest snapshot, thanks!

**Comment by Mause** [comment]
> Retested and confirm it was fixed with the latest snapshot, thanks!

Great, thanks for testing it!

**Comment by wdroste** [comment]
Saw the same issue, but its crashing with 0.9.0/0.9.1/0.9.2 for Ubuntu 22.04.3 LTS, it works fine w/ 0.8.1
