### ISSUE TITLE
Cannot insert JSON values into TEMPORARY tables (Conversion Error)

### ISSUE THREAD

**Issue by jwills** [duckdb/duckdb#8062]
### What happens?

Inserting a string value into a _temporary_ table that has a JSON-typed column fails with a conversion error. (Non-temporary tables work fine.)

### To Reproduce

```
CREATE TEMP TABLE foo (c_array json);
INSERT INTO foo VALUES ('[1, 2, 3]');
```

The insert statement will throw the error: ```Error: Conversion Error: Could not convert string '[1, 2, 3]' to UINT8```

### OS:

OS X

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI and Python

### Full Name:

Josh Wills

### Affiliation:

Unaffiliated

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jwills** [comment]
FYI I'm going to try to fix this one myself as it has been a long time since I've fixed anything in here ❤️ 

(if it's very obvious to one of you what's going on here, lmk and I will stop myself)

**Comment by zenazn** [comment]
I'm running into this too, where it's blocking an 0.8.1 upgrade

**Comment by jwills** [comment]
Noting that I wrote a test like this to try to repro the error:

```
# name: test/sql/json/test_json_temp_table.test
# description: Test JSON fields in temporary tables
# group: [json]

require json

statement ok
CREATE TEMP TABLE j1(x json);

statement ok
INSERT INTO j1(x) VALUES ('[1, 2, 3]');

statement ok
SELECT * FROM j1;
```

...but it passes instead of failing b/c it seems like somehow the `require json` makes the operation work, much to my confusion.

**Comment by jwills** [comment]
So it has to be that when the json extension registers its type info with the system catalog via `ExtensionUtil::RegisterType`, that information isn't getting propagated to the `TEMP_CATALOG` anymore, whereas it used to (somehow)

**Comment by jwills** [comment]
confirms that it must be something like this b/c I see the same problem with `spatial` types:

```
D INSTALL spatial;
D LOAD spatial;
D create table foo (g geometry);
D DESCRIBE foo;
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ g           │ GEOMETRY    │ YES     │         │         │       │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘
D CREATE temp table bar (g geometry);
Error: Invalid Error: std::bad_alloc
```

**Comment by jwills** [comment]
I'm suspicious of https://github.com/duckdb/duckdb/pull/7641 and am hacking on stuff in that general area of the code

**Comment by jwills** [comment]
okay yeah, #7641 needs to be updated (somehow, not immediately obvious to me b/c it looks kind of complicated) to handle non-enum user-defined types, I think? When I just do a debug build with the json extension enabled and try to run my test queries, I get:

```
jwills@Joshs-MBP duckdb % build/debug/duckdb
v0.3.3-dev15642 da69aeaad7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D load json;
D CREATE TABLE foo (c1 json);
D CREATE TEMP TABLE bar (c1 json);
Error: INTERNAL Error: Assertion triggered in file "/Users/jwills/dev/duckdb/src/common/types.cpp" on line 1527: type.id() == LogicalTypeId::ENUM
```

...and when I hack this line to be `if (true) {` then everything works as expected for the json fields in temp tables: https://github.com/duckdb/duckdb/blob/master/src/planner/binder/statement/bind_create_table.cpp#L300
