### ISSUE TITLE
fts extension: BOOLEAN params for create_fts_index only accepts INTEGERs

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb#8067]
### What happens?

The documentation for the `create_fts_index` PRAGMA statement indicates that its parameters `strip_accents`, `lower`, and `overwrite` take `BOOLEAN` values, however in practice, they currently only accept `INTEGER`s.

### To Reproduce

This works ok:

    PRAGMA create_fts_index('my_table', 'col_id', 'col', overwrite=1);

Whereas this does not:

    PRAGMA create_fts_index('my_table', 'col_id', 'col', overwrite=true);

Resulting in this error: `Error: Parser Error: Named parameter requires a constant on the RHS`

### OS:

Ubuntu

### DuckDB Version:

v0.8.2-dev87 8a17511028

### DuckDB Client:

CLI

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Closed via #8090
