### ISSUE TITLE
"INTERNAL Error: Missing batch index on Parallel CSV Reader GetLine" is sometimes triggered

### ISSUE THREAD

**Issue by chumbert2** [duckdb/duckdb#8072]
### What happens?

Hello! 

When reading multiple large CSV files in the CLI client, the internal error `Missing batch index on Parallel CSV Reader GetLine` is sometimes triggered.

### To Reproduce

Two large CSV files (2.5M lines, 101 columns):
```
[linux] $ ls -lh
-rw------- 1 user user 85M 24 juin  09:35  dummy-data-1.csv.zst       
-rw------- 1 user user 85M 23 juin  23:07  dummy-data-2.csv.zst      # actually a copy of the first file to simulate multiple files
```

`dummy-data-1.csv.zst`  -> <https://f003.backblazeb2.com/file/vertigo-stopwatch-eu-central/dummy-data-1.csv.zst?Authorization=3_20230624075740_b68f4f9ee54f2cc872b4f261_c0da1b61adb4ae364c7a841992b211b7720073b9_003_20230701075740_0020_dnld>

```
[linux] $ duckdb
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select * from 'dummy-data-*.csv.zst';
Error: INTERNAL Error: Missing batch index on Parallel CSV Reader GetLine
D
```

This is probably somehow related to the automatic column type detection because the following works as expected:

```
-- works as expected:
select * from read_csv_auto('dummy-data-1.csv.zst', all_varchar = 1);
select * from read_csv_auto('dummy-data-*.csv.zst', types={"col75": "char"});
```

### OS:

Linux

### DuckDB Version:

v0.8.1

### DuckDB Client:

CLI

### Full Name:

Cyril Humbert

### Affiliation:

Air Liquide

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
@chumbert2 

The data doesn't seem available anymore, could you send it again? Thanks!

**Comment by chumbert2** [comment]
Hello,

Here is an updated download link: <https://f003.backblazeb2.com/file/vertigo-stopwatch-eu-central/dummy-data-1.csv.zst?Authorization=3_20231023192829_25c0093adb803e3b9933162f_300c4214b320af8fb01f7fcb535198accab02449_003_20231030192829_0020_dnld> .

```bash
cp dummy-data-1.csv.zst dummy-data-2.csv.zst
```

With the current DuckDB version, I can't anymore reproduce the reported internal error and I get a very informative error message instead.

```
$ duckdb 
v0.9.1 401c8061c6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT * from 'dummy-data-*.csv.zst';
Error: Invalid Input Error: Could not convert string 'x' to INT64 in column "col75", at line 58120.

Parser options:
  file=dummy-data-2.csv.zst
  delimiter=';' (auto detected)
  quote='"' (auto detected)
  escape='"' (auto detected)
  header=1
  sample_size=20480
  ignore_errors=0
  all_varchar=0.

Consider either increasing the sample size (SAMPLE_SIZE=X [X rows] or SAMPLE_SIZE=-1 [all rows]), or skipping column conversion (ALL_VARCHAR=1)
D 
```
 :)

Thanks!
