### ISSUE TITLE
Compilation fails with "error: use of undeclared identifier 'max_value'" when including the generated duckdb-internal.hpp

### ISSUE THREAD

**Issue by isadikov** [duckdb/duckdb#8078]
### What happens?

I am trying to use DuckDB 0.8.0 in Velox. After running the amalgamation script, when I import "duckdb-internal.hpp" file (in addition to the existing `duckdb.hpp`, in the [QueryPlanner.cpp](https://github.com/facebookincubator/velox/blob/main/velox/parse/QueryPlanner.cpp#L18), I get the following errors: 
```
./velox/external/duckdb/duckdb-internal.hpp:12278:20: error: use of undeclared identifier 'max_value'; did you mean 'detail::max_value'?
    unsigned max = max_value<int>();
                   ^~~~~~~~~
                   detail::max_value
/usr/local/include/fmt/format.h:303:38: note: 'detail::max_value' declared here
template <typename T> constexpr auto max_value() -> T {
                                     ^
In file included from velox/parse/QueryPlanner.cpp:19:
./velox/external/duckdb/duckdb-internal.hpp:12278:20: error: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 extension [-Werror,-Wc++20-extensions]
    unsigned max = max_value<int>();
                   ^
./velox/external/duckdb/duckdb-internal.hpp:12287:21: error: use of undeclared identifier 'max_value'; did you mean 'detail::max_value'?
           value <= max_value<int>();
                    ^~~~~~~~~
                    detail::max_value

```

The duckdb files were generated using `python3 scripts/amalgamation.py --extended --splits=8`. 

The problem seems to be related to `#endif  // FMT_OSTREAM_H_` directive around L12261, if I move it lower to include the above error lines, those particular lines are no longer reported as errors. Appears to be an issue of inlining dependencies in DuckDB using the amalgamation script.

Do you know if this is a known issue in DuckDB amalgamation or is there a way to work around or patch up the error to make the code compile? 

### To Reproduce

The steps are outlined in the readme: https://github.com/facebookincubator/velox/blob/main/velox/duckdb/README.md. Once they are completed, run `make debug`.

### OS:

macOS m1 arm64 

### DuckDB Version:

0.8.0

### DuckDB Client:

C++

### Full Name:

Ivan

### Affiliation:

Ahana

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! The amalgamation splits and use of `duckdb-internal.hpp` are no longer actively supported as part of the open source version (i.e. use at your own risk). Feel free to contact [DuckDB Labs](https://duckdblabs.com/contact/) to request extended support.
