### ISSUE TITLE
using httpfs extension the COPY to statement is adding columns like day/month/year/hour to combined file written to s3

### ISSUE THREAD

**Issue by shreyasGit** [duckdb/duckdb#8079]
### What happens?

I am using httpfs extension to combine parquet files. i am installing the extension, providing required s3 auth stuff and then running following queries.
` CREATE TABLE test AS SELECT * EXCLUDE(service) from parquet_scan(['s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/day=09/hour=05/*.parquet','s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/day=09/hour=07/*.parquet','s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/day=21/hour=09/*.parquet','s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/day=22/hour=11/*.parquet']);
                            SELECT * from test;
                            COPY test TO 's3://ci-360-datahub-transfers-dev-us-east-1/audit_transfers/eiffel/consolidated.parquet';`
the files on which i am running parquet_scan is partitioned, but i have not provided any partition_by configuration to COPY TO query.
Still when data is combined and written to destination file, the destination has year,month,day,hour as columns. i dont want them in combined file.

### To Reproduce

use httpfs extension to read files from any partitioned bucket and combine the data write to some another bucket which is not partitioned.

### OS:

AWS Lambda

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Shreyas Deshpande

### Affiliation:

SAS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! [Partitioning support is automatically enabled when the data is partitioned by looking at the file path](https://duckdb.org/docs/data/partitioning/hive_partitioning#autodetection), this is an intended feature. If this is undesirable you can manually disable partitioning support by passing `hive_partitioning=0` as a parameter.

**Comment by shreyasGit** [comment]
Thanks a lot for the reply , this parameter needs to be set for copy to function?

**Comment by Mytherin** [comment]
The parameter is to `parquet_scan`, not for `COPY`. It is not required to function - it is required if you desire to disable the automatic inference of the partitioning columns.
