### ISSUE TITLE
Getting Duck Db Storage Error due to version upgrade

### ISSUE THREAD

**Issue by akash-goel** [duckdb/duckdb#8096]
### What happens?

Hi Team ,

We have persisted the data in Duck db database file and after doing the duck db versio upgrade we are getting error.

<img width="698" alt="duckdb" src="https://github.com/duckdb/duckdb/assets/5937612/1c006cc7-80f0-4fce-bc86-a1a7a0d574e5">

In Duck db documentation its written that storage is not final and change till version 1.00. ( https://duckdb.org/internals/storage )

Is there any month or date finalized by Duck db team when they are planning to finalize the duckdb storage .

Regards,
Akash

### To Reproduce

Persisted the data in Duck db database file and after doing the duck db version upgrade we are getting error.

### OS:

Windows

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

akash

### Affiliation:

Company

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
There is no fixed date yet for the storage stabilisation.
