### ISSUE TITLE
 Enhance duckdb_query_graph for parallel query

### ISSUE THREAD

**Issue by jtommaney1** [duckdb/duckdb#810]
Enhance duckdb_query_graph to allow for thread level utilization.
   - Normalize percentages
   - Display some measure of per-thread utilization (cycles, rows, or vectors) to understand if skew impacted timings.  

Phase	Time	Percentage
Total Time	0.206s	
Execution	1.1s	532.9%
SEQ_SCAN	1.050s	508.6%
SIMPLE_AGGREGATE	0.050s	24.2%
EXECUTE	0.0s	0%
PROJECTION	0.0s	0%
Optimizer	0.0s	0%
> Column Lifetime	0.0s	0%
> Expression Rewriter	0.0s	0%
> Filter Pushdown	0.0s	0%
> In Clause	0.0s	0%
> Index Scan	0.0s	0%
> Join Order	0.0s	0%
> Regex Range	0.0s	0%
> Reorder Filter Expressions	0.0s	0%
> Top N	0.0s	0%
> Unused Columns	0.0s	0%
Physical Planner	0.0s	0%
> Column Binding	0.0s	0%
> Create Plan	0.0s	0%
> Resolve Types	0.0s	0%
Planner	0.0s	0%
> Binder	0.0s	0%

**Comment by Mytherin** [comment]
Agreed, I think it is a good idea to normalize this percentage. We should normalize the time per operator in the same way, and display both the total CPU time and the total time spent for that operator.
