### ISSUE TITLE
ImportError: DLL load failed while importing duckdb: The specified module could not be found.

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#8101]
⚠️ See https://github.com/duckdb/duckdb/issues/8101#issuecomment-1614001280 for solution ⚠️ 

---

### What happens?

I reliably get ⬇️  when I `import duckdb` on a Windows 10 Pro.
```
ImportError: DLL load failed while importing duckdb: The specified module could not be found.
```

### To Reproduce

Be on this specific computer:

```
PS C:\ng\latest> Get-ComputerInfo

WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
```

Install Python `3.10.9` with [`pyenv-win`](https://github.com/pyenv-win/pyenv-win) and `pyenv local 3.10.9`.

```
python -m pip install duckdb
python
import duckdb
```

### OS:

Windows 1

### DuckDB Version:

0.8.0 and duckdb-0.8.2.dev157

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by davetapley** [comment]
Also seeing it on:
```
WindowsBuildLabEx                                       : 17763.1.amd64fre.rs5_release.180914-1434
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenter
WindowsInstallationType                                 : Server
WindowsProductName                                      : Windows Server 2019 Datacenter
```

**Comment by davetapley** [comment]
Got it! Took some digging, but the root cause was `Visual C++ Redistributable` **not** being installed.

You can download at:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

I'm surprised more haven't run in to this.
If it gets a few 👍🏻 then might be worth adding to https://duckdb.org/docs/installation/?environment=python ?

I'll leave open for now, but welcome to close.

---

For my own record:

```
dumpbin /dependents venv/Lib/site-packages/duckdb.cp310-win_amd64.pyd
Microsoft (R) COFF/PE Dumper Version 14.36.32535.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file venv\Lib\site-packages\duckdb.cp310-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    MSVCP140.dll
    WS2_32.dll
    python310.dll
    KERNEL32.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
```

**Comment by szarnyasg** [comment]
@davetapley thanks for opening this issue, these comments were very insightful. I also experimented with installing DuckDB in Windows and added my findings to the documentation: https://github.com/duckdb/duckdb-web/pull/1572

**Comment by narekmalk** [comment]
Had the same issue, and installing the `Microsoft Visual C++ Redistributable` resolved it

**Comment by Arkam-X** [comment]
Getting the same DDL issue!! and reinstalling the Microsoft Visual C++ Redistributable didn't resolved it. Any suggestions :)
