### ISSUE TITLE
Drift between docs, stubs and current implementation for Python UDFs

### ISSUE THREAD

**Issue by bnm3k** [duckdb/duckdb#8103]
### What happens?

There's a drift between the docs, stubs and current implementation with regards to typing and argument names (for python UDFs). I've raised the issue here instead of duckdb-web since the API references docs are autogenerated, however, if it's better raised there, I'll shift.

Here's what works:
```python
def my_double(n):
    return n * 2

duckdb.create_function(
    "my_double", my_double, parameters=INTEGER, return_type=[INTEGER]
)
```
In the [API reference docs](https://duckdb.org/docs/api/python/reference/), the `return_type`'s  type is set to `object` (should be `Optional[List[DuckDBPyType]]`):
```python
create_function(
  self: duckdb.DuckDBPyConnection,
  name: str,
  function: function,
  return_type: object = None,
  parameters: duckdb.typing.DuckDBPyType = None ... )
```

And in `duckdb-stubs/__init__.pyi`:
- instead of `parameters`, we've got `args`
- the `return_type` is set to `Optional[DuckDBPyType]` instead of `Optional[List[DuckDBPyType]]`:
```python
def create_function(
    name: str,
    func: Callable,
    args: Optional[List[DuckDBPyType]],
    return_type: Optional[DuckDBPyType],
    vectorized: Optional[bool] = False,
    null_handling: Optional[FunctionNullHandling] = FunctionNullHandling.DEFAULT,
    exception_handling: Optional[PythonExceptionHandling] = PythonExceptionHandling.DEFAULT,
    side_effects: Optional[bool] = False,
    connection: DuckDBPyConnection = ...) -> DuckDBPyConnection: ...
```

### To Reproduce

To reproduce:
Let's define the function
```python
def my_double(n):
    return n * 2
```
Following the signature from the docs, we should get a typing error since `return_type` is not an `object`
```python
duckdb.create_function(
    "my_double", my_double, parameters=INTEGER, return_type=[INTEGER]
)
```
Following the signature from the typing hints, we get an error since there's no args parameter. We also get a typing error since `return_type` should be a list:
```python
duckdb.create_function(
    "my_double", my_double, args=INTEGER, return_type=INTEGER
```

### OS:

Ubuntu 20.04.6  x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Brandon Mochama

### Affiliation:

None currently

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Here is fine, we should just fix the `__init__.py` stub for `create_function`.

What I'm confused about is this:
> We also get a typing error since return_type should be a list

The stubs are correct here, it should be `return_type: Optional[DuckDBPyType]`

return type shouldn't be a list of types, that makes no sense for a scalar function

**Comment by bnm3k** [comment]
If I set return type to a scalar:
```python
duckdb.create_function(
    "my_double", my_double, parameters=INTEGER, return_type=INTEGER
)
```
I get this error:
```
duckdb.InvalidInputException: Invalid Input Error: Either leave 'parameters' empty, or provide a list of DuckDBPyType objects

```

**Comment by bnm3k** [comment]
Got it

**Comment by Tishj** [comment]
Actually I understand the confusion @bnm3k, the stubs have `return_type` and `parameters` in the wrong order, my apologies.

**Comment by Mause** [comment]
While we're fixing this, might be worth extending the docstring to include docs for the individual parameters using the Sphinx/RST syntax so it appears in the auto-generated docs

**Comment by ned2** [comment]
Would be great to get this fixed, as I definitely want to invoke `create_function` with named parameters to improve the readability of my code, however that is not possible currently. eg this throws a `TypeError`:

```python
def add_one(val):
    return val + 1

duckdb.create_function(
    name="add_one",
    func=add_one,
    parameters=[duckdb.typing.INTEGER],
    return_type=duckdb.typing.INTEGER,
)
```

Currently we have to invoke like this:

```python
duckdb.create_function(
    "add_one",
    add_one,
    [duckdb.typing.INTEGER],
    duckdb.typing.INTEGER,
)
```

**Comment by ned2** [comment]
This is still an issue. Bumping to keep from being closed.
