### ISSUE TITLE
Duckdb not working in DBeaver with JDBC in Ubuntu 22.04.2 on WSL2

### ISSUE THREAD

**Issue by persep** [duckdb/duckdb#8105]
### What happens?

Working setup:
`duckdb v0.7.1 b00b93f0b1`
Running in
`Ubuntu 22.04.2 LTS`
Installed in wsl2 in windows 10
```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3086
```
I access any duckdb database from 
`DBeaver Version 23.1.1.202306251800`
installed in windows with the 
`duckdb_jdbc-windows-amd64.jar version 0.7.1`

Without any problem I can make queries to any dbduck database from DBeaver

But if a install the latest version of `duckdb 0.8.1` with the `duckdb_jdbc-windows-amd64.jar version 0.8.1` dbeaver can't open the duckdb database giving an error:
`IO Error: Cannot open file "c:\users\persep\appdata\local\dbeaver\\\wsl.localhost\ubuntu\home\persep\products.duck": The system cannot find the path specified.`

If i try with `duckdb_jdbc-windows-amd64.jar version 0.8.0` i get the same error but if I try with the `0.7.1` it looks like it does open the duckdb database file because I get the error "That the file version are too old" (I haven't got the exact words it uses).

The duckfile I'm trying to open on DBeaver is:
`\\wsl.localhost\Ubuntu\home\persep\products.duck`
Has there been any changes in the jdbc driver that can't open network drives wich is the system that wsl2 uses?

### To Reproduce

Install 
duckdb 0.8.1 and access it from DBeaver 23.1.1 with `duckdb_jdbc-windows-amd64.jar version 0.8.1` and it can't open duckdb datafiles

### OS:

Ubuntu 22.04.2 LTS

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

PerseP

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
This issue sounds related to #7623 
Which is not specific to JDBC, but paths on Windows in general

I can't immediately tell if this issue would be fixed by the mentioned PR

**Comment by bill-ash** [comment]
I was able to get this working by mapping wsl2 to a local drive on windows. 

Literally just right click the Ubuntu directory and choose to map the directory.

**Comment by persep** [comment]
Yes that works, I didn't think in mapping the drive. But it works because you convert, ie: you map a network driver to a local one.
By mapping the network drive with JDBC Dbeaver uses the path
`Z:\home\persep\products.duck` and works ok with version 0.8.1
But with the network explorer the drive path DBeaver uses is:
`\\wsl.localhost\Ubuntu\home\persep\products.duck` and it gives this error with the JDBC 0.8.1
`IO Error: Cannot open file "c:\users\persep\appdata\local\dbeaver\\\wsl.localhost\ubuntu\home\persep\products.duck": The system cannot find the path specified.`

The path in that error message is wrong: it's like a local path concatenated with the network path so it can't find the database.

The path that DBeaver uses with the  JDBC 0.7.1 driver that works ok is:
`\\wsl$\Ubuntu\home\persep\products.duck`
it works because its a properly form network path.

I'm assuming in all this that DBeaver gets the path from the JDBC  driver and that this is at fault but I can't be sure as i don0t know how that works.

**Comment by wtfzambo** [comment]
I'm having same issure here with driver 0.8.1. Previous version was working properly 🤔

**Comment by ptitjano** [comment]
I can still reproduce the issue with duckdb 0.9.1 and windows 11.
It works fine with duckdb 0.7.1. 

The database is stored in a samba share: 
```py
import duckdb

my_database = r"\\ptitjano\partage\\duckdb\base_test.db"
conn = duckdb.connect(my_database, read_only=True)
```
