### ISSUE TITLE
DuckDB Fails to Read All Rows from Multiple JSON Files

### ISSUE THREAD

**Issue by ericyaang** [duckdb/duckdb#8106]
### What happens?

I am experiencing an issue with DuckDB where it is not reading all rows from multiple JSON files. I have a total of 6436 JSON files following the naming pattern "NAME_YYYYMMDD_HHMMSS". When I load these files using pandas, I get a total of 595,431 rows. However, when I use DuckDB to load the same files, it only retrieves 151,231 rows, which accounts for approximately 30% of the total rows.

ps.  The read_json() and read_json_auto() methods in DuckDB didn't work.

### To Reproduce

Example JSON data:

```json
[
  {
    "date": "23-06-2023",
    "aisle_name": "Sorvetes e picolés",
    "product_name": "Sorvete de flocos tradicional",
    "brand": "Nestlé",
    "price": 20.39,
    "package": "1,5l",
    "store_name": "Carrefour Hiper",
    "store_city": "FLN",
    "search_term": "Sorvete de Flocos"
  },
  {
    "date": "23-06-2023",
    "aisle_name": "Sorvetes e picolés",
    "product_name": "Sorvete sabor flocos",
    "brand": "Kibon",
    "price": 29.99,
    "package": "1,5l",
    "store_name": "Carrefour Hiper",
    "store_city": "FLN",
    "search_term": "Sorvete de Flocos"
  },
 ]

```

**Steps to Reproduce:**
```python
import duckdb
con = duckdb.connect()
con.execute(f"SELECT COUNT(*) FROM 'data/*.json'").df()
```

**Expected Result:**
The expected result is to retrieve a count of 595,431 rows, which matches the number of rows obtained when loading the same files using pandas.

### OS:

Windows 11 Pro

### DuckDB Version:

0.8.1

### DuckDB Client:

Python 3.10  & CLI

### Full Name:

Eric

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paniterka** [comment]
I had a similar problem using `read_ndjson_objects` in 0.8.1 and can confirm that 0.9.0 seems to be working correctly now.
