### ISSUE TITLE
Param Count mismatch 

### ISSUE THREAD

**Issue by ruchirj** [duckdb/duckdb#8109]
### What happens?

```
java.sql.SQLException: Parameter count mismatch
	at org.duckdb.DuckDBNative.duckdb_jdbc_execute(Native Method) ~[duckdb_jdbc-0.8.1.jar!/:?]
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:138) ~[duckdb_jdbc-0.8.1.jar!/:?]
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:170) ~[duckdb_jdbc-0.8.1.jar!/:?]
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:192) ~[duckdb_jdbc-0.8.1.jar!/:?]
```

### To Reproduce

`SELECT regexp_extract(message, ?, [?, ?, ?, ?, ?, ?, ?, ?]) FROM {tableName}`

`message` is a column in {tableName}. This does work on MacOS, just fails with the ^^ exception on Linux. 

### OS:

Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Java

### Full Name:

Ruchir Jha

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This message is expected if you don't provide the parameters required for the query, which you declare using the `?` character. Are you providing these and still seeing the error?

**Comment by ruchirj** [comment]
@Mause yes I am using it as a prepared statement and setting the 9 params, but it throws this exception only on Linux. Please note that this works on MacOS just fine.

**Comment by Mause** [comment]
Unfortunately I'm unable to replicate this on my own Linux machine, I wrote a small attempted repro using the example you gave in Discord:

```java
import java.sql.DriverManager;

public class DuckdbDemoApplication {
    public static void main(String[] args) throws Exception {
        var conn = DriverManager.getConnection("jdbc:duckdb:");

        try (var statement = conn.prepareStatement("SELECT regexp_extract('Hello World 123', ?, [?, ?, ?])")) {
            statement.setString(1, "(\\S+) (\\S+) (\\d+)");
            statement.setString(2, "word1");
            statement.setString(3, "word2");
            statement.setString(4, "number");

            var resultSet = statement.executeQuery();

            while (resultSet.next()) {
                System.out.println(resultSet.getObject(1));
            }
        }
    }
}
```

**Comment by ruchirj** [comment]
I was passing the sql string into the `executeQuery` method that was causing this issue. Closing.
