### ISSUE TITLE
DuckDb returns only the first column

### ISSUE THREAD

**Issue by ruchirj** [duckdb/duckdb#8115]
### What happens?

While using PreparedStatements and selecting 2 columns, where one is a struct only the first column is returned

### To Reproduce

This code snippet below only prints the timestamp, but not the value of struct['word1']

```
import java.sql.DriverManager;
import java.util.Arrays;

public class DuckdbDemoApplication {
    public static void main(String[] args) throws Exception {
        var conn = DriverManager.getConnection("jdbc:duckdb:");

        var createStatement = conn.createStatement();
        createStatement.execute("CREATE TABLE foo(timestamp BIGINT, message VARCHAR)");
        createStatement.execute("INSERT INTO foo VALUES(1, 'Hello world 123')");
        createStatement.execute("INSERT INTO foo VALUES(2, 'Hello world 456')");
        createStatement.execute("INSERT INTO foo VALUES(3, 'Hello world 789')");

        var sql = "SELECT timestamp, struct['word1'] FROM (SELECT timestamp, regexp_extract(message, ?, [?, ?, ?]) as struct FROM foo)";
        var pstmt = conn.prepareStatement(sql);
        var params = Arrays.asList("(\\S+) (\\S+) (\\d+)",
                "word1",
                "word2",
                "number");

        for (int index=0; index<params.size(); index++) {
            var param = params.get(index);
            System.out.printf("Setting param = %s at index = %d%n", param, index);
            pstmt.setString(index + 1, param);
        }

        var resultSet = pstmt.executeQuery();
        var metadata = resultSet.getMetaData();
        while (resultSet.next()) {
            for (int i=0; i<metadata.getColumnCount(); i++) {
                System.out.println(resultSet.getObject(i + 1));
            }
        }
    }
}
```

### OS:

any

### DuckDB Version:

0.8.1

### DuckDB Client:

Java

### Full Name:

Ruchir Jha

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ruchirj** [comment]
Somewhat related, not only the below SQL prints only the first column as noted above, but the column header is "unknown"

`
SELECT struct['word1'] as word1, struct['word2'] as word2 FROM (SELECT regexp_extract(message, ?, [?, ?, ?]) as struct FROM foo)`

**Comment by Mause** [comment]
This is likely related to https://github.com/duckdb/duckdb/issues/7216, where binding bails out early and returns bad metadata. If I use reflection to override the `column_count` field in the JDBC driver, I can retrieve both columns (but there's still only one column name, "unknown")

**Comment by ruchirj** [comment]
@Mause would you be able to post the reflection code snippet here?

**Comment by Mause** [comment]
Something along the lines of 

```java
    private static void setColumnCount(ResultSet resultSet) throws SQLException {
        try {
            var currentChunkField = DuckDBResultSet.class.getDeclaredField("current_chunk");
            currentChunkField.setAccessible(true);
            var columns = (Object[]) currentChunkField.get(resultSet);
            int columnCount = columns.length;
            if (columnCount == 0) {
                throw new SQLException("ResultSet not initialized");
            }

            var columnCountField = DuckDBResultSetMetaData.class.getDeclaredField("column_count");
            columnCountField.setAccessible(true);
            columnCountField.set(resultSet.getMetaData(), columnCount);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
```

Should work. I wouldn't really recommend this in production code though

**Comment by solita-kattelus** [comment]
This is quite bad and I see same problem. I was using aliases to define column names of results and have generic mapper from result set to target data and now resulting mapper result as single "unknown" named column name. This happens as soon as I include any binding variable there.

**Comment by solita-kattelus** [comment]
E.g.
SELECT 1 AS foo, 2 AS bar WHERE :param IS NOT NULL -> [{unknown=1}]
SELECT 1 AS foo, 2 AS bar WHERE 1 IS NOT NULL -> [{foo=1, bar=2}]

**Comment by solita-kattelus** [comment]
Is this same than #6767?
