### ISSUE TITLE
DuckDB giving false premise of converting epoch to timezone - not following the same standards as e.g postgresql.

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb#8119]
### What happens?

(I file this is a bug while some people may argue that its a mistake on my part, I argue it is partly a bug/antipattern, partly a request for a new feature - and in the mean time a lack of documentation).

When converting unixtime to timestamp. and wanting to add time zone information to the resulting timestamp using `to_timestamp(1503533692)::timestamptz` - this is seemingly done, but not at all - making you end up with a wrong timestamp. The epoch is converted to a GMT timestamp, then your local timezone is added to the end of it without converting the timestamp in itself. In reality there should be a fool proof (yes I concede that people might think I am a fool) way of converting unixtime to timestamp with timezone. (Trying to think of a reason - can it be that to_timestamps retrieves my local timezone from one place, while ::timestamptz is more of a cli/output field that reads the timezone of my shell, or something like that)

I have compared this with postgresql, showing that they interpret standards in two different ways (postgres shows the timestamp in your timezone in addition to add timezone information, duckdb just add timezone information).

I realize this is in part due to (I guess) duckdb first converting to GMT timestamp, then adding timestamp information through timestamptz. At the very least this should be clarified in the docs (I can make an issue in the correct repo in that case) but I think this should be considered a bug as well - as there is not a way of turning an epoch to timestamp with time zone information ending up with the right data. 

My timezone is CET (UTC+1) however currently it is also CEST(summer time, so UTC+2). So that part is correct at least, but doesn't help when the timestamp itself is in UTC. The most important for me at least is to get any timestamp with a correct timezone, getting just UTC, not considering my time zone at all would be fine as well.

### To Reproduce
 
**Duckdb:**
```sql
SELECT to_timestamp(1503533692), to_timestamp(1503533692)::timestamptz;
│ to_timestamp(1503533692) │ CAST(to_timestamp(1503533692) AS TIMESTAMP WITH TIME ZONE) │
│        timestamp         │                  timestamp with time zone 
│ 2017-08-24 00:14:52      │ 2017-08-24 00:14:52+02     
```

**Postgresql:**
```sql
SELECT to_timestamp(1503533692), to_timestamp(1503533692)::timestamptz;
 
| to_timestamp           | to_timestamp        
| 2017-08-24 02:14:52+02 | 2017-08-24 02:14:52+02 |
```

Using Postgresql to read the timestamp with timezone that Duckdb gives back, ending up with a different unixtime:
```sql
SELECT extract(epoch from TIMESTAMP WITH TIME ZONE '2017-08-24 00:14:52+02');
1503526492.000000 
```

Using duckdb to do the same:

```sql
SELECT extract( epoch from timestamptz '2017-08-24 00:14:52+02');
main.date_part('epoch', CAST('2017-08-24 00:14:52+02' AS TIMESTAMP WITH TIME ZONE))
1503533692
```

I end up with the original timestamp so duckdb is consistent, but if we shall believe postgresql, also wrong?

Thinking this was an issue with not loading icu:

```sql
>LOAD 'icu';
>SELECT to_timestamp(1503533692)::timestamptz;
┌────────────────────────────────────────────────────────────┐
│ CAST(to_timestamp(1503533692) AS TIMESTAMP WITH TIME ZONE) │
│                  timestamp with time zone                  │
├────────────────────────────────────────────────────────────┤
| 2017-08-24 00:14:52+02                                     │
└────────────────────────────────────────────────────────────┘
Run Time (s): real 0.001 user 0.000830 sys 0.000372

```

Still wrong.

If there is something I am missing here I apologize for that, but I imagine there must be others who have done the same mistakes in that case.

### OS:

Ubuntu

### DuckDB Version:

v0.8.0 e8e4cea5ec

### DuckDB Client:

DuckDB CLI 

### Full Name:

Bjørnar Brende Smestad

### Affiliation:

NTNU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
One issue appears to be that our `to_timestamp` function returns TS not TSTZ. We really need a `to_timestamptz` function.

I'm afraid I will be off the net for the next 10 days, but in general the TSTZ types does not "attach a time zone" What it do is say that all [binning operations](https://duckdb.org/2022/01/06/time-zones.html) (including presentation/casting to string) should use the current Calendar and TimeZone settings. The standard also says that casting between the two types should treat plain TZ types as naïve timestamps, which I strongly recommend you avoid for your own sanity. Our model is that both columns store instants (which you call "GMT", but the proleptic Gregorian calendar in GMT is really just a convenient way to describe unambiguous, dense, human-readable instants). After that, we attempt to follow the standard, but the standard is such a terrible model that we keep finding problems like this.

**Comment by hawkfish** [comment]
(When reporting bugs like this, it is helpful to know your TZ. Looks like CET?)

**Comment by bjornasm** [comment]
Thank you @hawkfish - I agree, i also posted a feature request regarding to timestamptz
 The whole ordeal is such a headache when you take in summer time etc. But sadly I need the timestamp here or else I would stick to unixtime/epoch. 

Since it seems like the timestamptz functions only changes the output and not the underlying timestamp with it, should these be presented more like CLI output options rather than databasefunctions? (I realize that a fix to this would not change how things are saved, but right now this seems more like a string formatter - like adding currency symbol to a monitary value rather than threating the saved timestamp as something with a time zone that can be changed). It was just by sheer luck that I felt iffy about the conversion so I kept the original unixtime values to control it.

**Comment by hawkfish** [comment]
> Since it seems like the timestamptz functions only changes the output and not the underlying timestamp with it, should these be presented more like CLI output options rather than databasefunctions? (I realize that a fix to this would not change how things are saved, but right now this seems more like a string formatter - like adding currency symbol to a monitary value rather than threating the saved timestamp as something with a time zone that can be changed). It was just by sheer luck that I felt iffy about the conversion so I kept the original unixtime values to control it.

It's not just formatting - it's also how you do analytics. For example, if you are doing financial reporting for a company whose bylaws say that the data is binned by quarter in America/Los_Angeles, then you actually do need to know that Q1 is 1 hour longer. So I have found that the best way to deal with these issues is to always store instants and set the TZ based on the task at hand. Then the data never changes, only the calculations. And if performance becomes an issue, you can either use our bin-list variants (`DATE_PART(['year', 'month', 'day'], tstz)`) or create a calendar table with the bin values you want and join to it. Or both(!)

(Incidentally, naïve timestamps can fail in DuckDB if you are using a calendar with 13 months like Hebrew or Ethiopian: There is no way to create a "local timestamp" in that situation because Gregorian has only 12 months!)

**Comment by bjornasm** [comment]
@hawkfish  thank you for your thoughts around this! It isn't an easy topic to say the least. Just to elaborate my use case/how this "failed" for me: 

I am pre-processing some data with unixtime values that is going to be loaded into a postgresql table with a timestamp column (don't worry, DuckDB will be used for the analytical part! ). As I need to store it as timestamp in the postgresql table, my thought was to use duckdb to convert/bin it to timestamp with time zone before outputting to csv files that is to be ingested. I wanted to add time zone because Postgresql is assuming you are using your local time zone if you load timestamp without adding time zone - so just using to_timestamp() would give a problem in the other end. With this in mind I think it is even more important to be explicit with the timestamps (or use unixtime) - being explicit to avoid any other system converting or assuming time zones. 

On remedy could be to set the duckdb time zone to be f.ex utc, but one of the (many) great things about duckdb is the portability/utilization, so while I am doing this on my server, the next time could be on a notebook on my laptop etc where I forget to change the duckdb time zone.   

Interestingly enough if I do this:

```
SELECT strftime(to_timestamp(1503533692),'%c%z');
2017-08-24 00:14:52+00  
```

It seems like Duckdb agrees that the timestamp that is created from unixtime with to_timestamp() is in the time zone UTC.

When I try to utilize this to create a to_timestamptz function (just to check):

```
SELECT strptime(strftime(to_timestamp(1503533692),'%c%z'), '%c%z');
2017-08-24 02:14:52+02      
```
Looks good! But can I finish the roundtrip?

```
SELECT epoch(strptime(strftime(to_timestamp(1503533692),'%c %z'), '%c %z'));
1503540892

```
The last one is a bit unfair as epoch only works with timestamp (so I guess it strips away the z part), but its a bit iffy that there is unexpected behaviour when converting time representations. Maybe epoch(timestamp) at least should take the eventual (timestampz) and convert it to a timestamp, eg: timestamp+Z -> timestamp+0 rather than just do a string manipulation? Or throw a warning about what its assuming and doing?

If I try the following I also get two different results regarding time zone:

```
SELECT to_timestamp(1503533692)::timetz;
00:14:52+00      

SELECT to_timestamp(1503533692)::timestamptz;
2017-08-24 00:14:52+02     
```

If `timetz` correctly assuming that the timestamp converted from unixtime should be UTC and `strftime(to_timestamp(1503533692),'%c%z')` does the same - maybe `timestamptz` should adhere to that as well?


As you have pointed out - there is so many use cases and behaviours here that I don't think there is an easy solve for this, but I think there at least should be some consistency - or the docs should be updated so people are warned about this behaviour.

**Comment by bjornasm** [comment]
Edit: 
Sorry if this is a bit overload, just wanted to add one more example where it seems like duckdb is correctly handling conversion between timestampsz and from timestampz to timestamp. If I have a `my.csv` with the following:

```
| timecolumn |
|-----------------|
|2018-01-05 00:00:00+01|

```
And open up duckdb and do the following:

```
D SELECT * FROM 'my.csv' limit;
timecolumn
timestamp
2018-01-04 23:00:00
```

**Comment by hawkfish** [comment]
We need to match the PG semantics, so I have submitted a fix.  The other issue was that the function signature for PG was actually `to_timestamp(DOUBLE): TIMESTAMPTZ` but we had `to_timestamp(BIGINT): TIMESTAMP`.

**Comment by hawkfish** [comment]
@bjornasm This should be fixed on master now.

**Comment by ashington** [comment]
You can use this to convert a epoch to timestamp --> SELECT strftime(to_timestamp(extract(epoch from started_at)),'%Y-%m-%d')
from orders;
