### ISSUE TITLE
Python create_function() getting stuck after fetchone()

### ISSUE THREAD

**Issue by loneguardian** [duckdb/duckdb#8124]
### What happens?

This is within the context of using `create_function()` in a Jupyter Notebook / Interactive Python window. Honestly I am not sure whether this is intended behaviour but here goes:

When the main module imports another module that runs duckdb's `fetchone` within its scope, the main module's `duckdb.create_function` will become stuck when one attempts to create a function. The function is never really created (?), which can be confirmed in `duckdb_functions()` + it cannot be deleted - says scalar function not found. At the same time, when you run `create_function` within the same session it says the function has already been created. Hence, stuck.

### To Reproduce

1. `main.py`
```python
import duckdb
import some_module

def some_function() -> bool:
    return True

duckdb.create_function("some_function", some_function)
duckdb.sql("SELECT some_function()").show()
```

2. `some_module.py`
```python
import duckdb

duckdb.sql("SELECT 123").fetchone()[0]
```

3. run `main.py` (both terminal and interactive window result in error)

First error will be:
```
InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Catalog Error: Scalar Function with name some_function does not exist!
Did you mean "second"?
```

Within the same session, running `duckdb.sql("SELECT some_function()").show()` again or trying to remove the function will result in:
```
CatalogException: Catalog Error: Scalar Function with name some_function does not exist!
Did you mean "second"?
```

Within the same session, trying to create the function again using `duckdb.create_function("some_function", some_function)` results in:
```
NotImplementedException: Not implemented Error: A function by the name of 'some_function' is already created, creating multiple functions with the same name is not supported yet, please remove it first
```

### OS:

Windows 10 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Ting Teck Pei

### Affiliation:

Hobbyist coder

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I would be interested to know what happens when you create different connections in the two modules.

Currently these are using the same (the default) connection.

**Comment by Tishj** [comment]
`fetchone` does not consume the full result, leaving a transaction open.

When you call `create_function`, we use RunFunctionInTransaction, which will create a new transaction, run the function that registers the function in the catalog, and then commit this.

If another query gets executed before the first one has been fully consumed, we need to close the transaction, which means aborting it.

When we abort the transaction, all the transactions made while that transaction was open are also aborted.
This causes the function to not be registered in the catalog anymore.

To top that off, we use a map to cheaply determine whether a function was already registered and needs to be removed, which is the other error you have shown:
> A function by the name of 'some_function' is already created, creating multiple functions with the same name is not supported yet, please remove it first

My solution to fix this would probably be to disallow using `create_function` when another transaction is already active.

**Comment by loneguardian** [comment]
Is there a reason why `fetchone` has to keep the transaction open from the point of view of a user? Wondering if I am using `fetchone` wrongly here.

It seems like disallowing `create_function` during a transaction will still lead to error for my repro case.

**Comment by Tishj** [comment]
Yes that's correct, you would run into the error when trying to use `create_function` before finishing fetching the result from the previous query.

`fetchone()` takes one row.
Even if the result consists of only 1 row, we are not aware of that yet, only when you fetch again will we know that the result is depleted and then we'll close it.

**Comment by loneguardian** [comment]
In that case I guess it is a user error on top of the lack of failsafe from duckdb's side.

Beside the fix, I would like to propose extra documentation on `fetchone` behaviour. I was thinking it is like `head()` from `pandas`. Maybe even have a page with a list of functions that possess the same transaction holding behaviour (if there is any).

**Comment by Tishj** [comment]
> In that case I guess it is a user error on top of the lack of failsafe from duckdb's side.
> 
> Beside the fix, I would like to propose extra documentation on `fetchone` behaviour. I was thinking it is like `head()` from `pandas`. Maybe even have a page with a list of functions that possess the same transaction holding behaviour (if there is any).

`fetchone` is not specific to duckdb, we're just implementing the DBAPI interface, https://peps.python.org/pep-0249/#fetchone
