### ISSUE TITLE
check if the return value of unloadAndTakeBlock is nullptr before resetting

### ISSUE THREAD

**Issue by tang-hi** [duckdb/duckdb#8128]
### What happens?

I discovered that we neglected to verify whether the return value of BlockHandle is nullptr before resetting it. [code](https://github.com/duckdb/duckdb/blob/563662b093934bf9b20cbc985835c7b7762562bb/src/storage/buffer/block_handle.cpp#L89C1-L109C2)
```C++
unique_ptr<FileBuffer> BlockHandle::UnloadAndTakeBlock() {
	if (state == BlockState::BLOCK_UNLOADED) {
		// already unloaded: nothing to do
		return nullptr;                                   // it could return nullptr
	}
	D_ASSERT(!unswizzled);
	D_ASSERT(CanUnload());

	if (block_id >= MAXIMUM_BLOCK && !can_destroy) {
		// temporary block that cannot be destroyed: write to temporary file
		block_manager.buffer_manager.WriteTemporaryBuffer(block_id, *buffer);
	}
	memory_charge.Resize(0);
	state = BlockState::BLOCK_UNLOADED;
	return std::move(buffer);
}

void BlockHandle::Unload() {
	auto block = UnloadAndTakeBlock();    // should check if it's nullptr
	block.reset();
}
```
This can potentially cause issues. If necessary, I can create a pull request to address this problem.

### To Reproduce

I didn't found corresponding test in codebase

### OS:

Linux

### DuckDB Version:

22

### DuckDB Client:

Python

### Full Name:

tang donghai

### Affiliation:

Meituan

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I believe `reset` on an empty unique_ptr is defined behavior and causes no problems

**Comment by tang-hi** [comment]
> 

Oh, my bad. Sorry. :smile:
