### ISSUE TITLE
Python DB API using join() on sql() relation causes BinderException - duplicate alias "query_relation" in query

### ISSUE THREAD

**Issue by loneguardian** [duckdb/duckdb#8134]
### What happens?

Using the `join()` relation API in python gives me this error.

### To Reproduce

1. Run this python script
```python
import duckdb

rel1 = duckdb.sql("SELECT 1 AS col1, 2 AS col2")
rel2 = duckdb.sql("SELECT 1 AS col1, 3 AS col3")

rel = rel1.join(rel2, "col1")
```

2. Error message:
```
BinderException: Binder Error: Duplicate alias "query_relation" in query!
```

### OS:

Windows 10 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Ting Teck Pei

### Affiliation:

Hobbyist coder

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
When using `sql()` you can provide an alias
The default is `query_relation` which causes this issue.

Try setting aliases for the relations

**Comment by Tishj** [comment]
> ```python
> import duckdb
> 
> rel1 = duckdb.sql("SELECT 1 AS col1, 2 AS col2", 'rel1')
> rel2 = duckdb.sql("SELECT 1 AS col1, 3 AS col3", 'rel2')
> 
> rel = rel1.join(rel2, "col1")
> rel.show()
> ```

You're thinking of this:
```py
import duckdb

rel1 = duckdb.sql("SELECT 1 AS col1, 2 AS col2")
rel2 = duckdb.sql("SELECT 1 AS col1, 3 AS col3")

rel = duckdb.sql('select * from rel1 JOIN rel2 USING (col1)')
rel.show()
```

**Comment by Tishj** [comment]
We could probably create two new relations aliased to `a` and `b` to perform the join, I don't immediately see how that would be a problem

**Comment by loneguardian** [comment]
> You're thinking of this:
> 
> ```python
> import duckdb
> 
> rel1 = duckdb.sql("SELECT 1 AS col1, 2 AS col2")
> rel2 = duckdb.sql("SELECT 1 AS col1, 3 AS col3")
> 
> rel = duckdb.sql('select * from rel1 JOIN rel2 USING (col1)')
> rel.show()
> ```

Yes, I assumed `join()` is like a shorthand for the `sql()` part you mentioned. Apparently the assumption is wrong? Since `join()` only supports `inner` or `left`.

If devs do not think this is an issue then I guess it is more of a feature request then.

**Comment by Tishj** [comment]
I've written in a safeguard that checks if the aliases are equal and throws a helpful error message, suggesting the use of `set_alias`
