### ISSUE TITLE
string_agg(arg, sep) ignores value of sep when arg contains an 'order by' clause

### ISSUE THREAD

**Issue by vlieven** [duckdb/duckdb#8149]
### What happens?

When using the `string_agg` aggregate function on an expression that contains an `order by` clause, the value filled in for `sep` is ignored, and always defaults to ",". This does not happen when omitting `order by`.

`string_agg("my_column" order by "my_column", '|')` generates rows like `A,B,C` instead of `A|B|C`.

### To Reproduce

```
CREATE TABLE tbl(i VARCHAR);
INSERT INTO tbl VALUES ('A'), ('B'), ('C');
SELECT string_agg(i order by i, '|') FROM tbl;
```

Results in:
```
┌───────────────────────────────┐
│ string_agg(i ORDER BY i, '|') │
│            varchar            │
├───────────────────────────────┤
│ A,B,C                         │
└───────────────────────────────┘
```

### OS:

MacOS

### DuckDB Version:

0.8.2.dev1182

### DuckDB Client:

Python

### Full Name:

Lieven Verswyvel

### Affiliation:

Data Minded

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is working as intended. `ORDER BY` has to come after all arguments:

```sql
CREATE TABLE tbl(i VARCHAR);
INSERT INTO tbl VALUES ('A'), ('B'), ('C');
SELECT string_agg(i, '|' order by i) FROM tbl;
┌───────────────────────────────┐
│ string_agg(i, '|' ORDER BY i) │
│            varchar            │
├───────────────────────────────┤
│ A|B|C                         │
└───────────────────────────────┘
```

What is happening in your example is that the system is executing `string_agg(i)` ordered by two columns (`i, '|'`). `string_agg` defaults to the comma separator when no separator is provided - hence the behavior.
