### ISSUE TITLE
Allow EXPLAIN to be used as a subquery

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#8150]
We want to allow EXPLAIN to be used as a subquery so that these statements can be turned into tables or queried again.

For example:

```sql
CREATE TABLE explain_output AS EXPLAIN SELECT 42;
```

**Comment by jexp** [comment]
Would love to see this too!

**Comment by Benoss** [comment]
Yes please!

**Comment by Mytherin** [comment]
`DESCRIBE/SUMMARIZE` are now supported as subqueries in #10210

**Comment by Mytherin** [comment]
Closing as `DESCRIBE/SUMMARIZE` is now implemented. `EXPLAIN` is not but unless there is a compelling use case I think it is fine like this
