### ISSUE TITLE
macros do not appear in cli .schema output

### ISSUE THREAD

**Issue by marhar** [duckdb/duckdb#8159]
### What happens?

`.schema` does not include macros in the output.

### To Reproduce

```
.echo on
create table foo(x int);
create view  fooview       as select * from foo;
create macro foo_scalar(x) as x+1;
create macro foo_table(x)  as table select * from foo;

-- properly lists everything but macros
.schema
-- works properly for views
.schema fooview
-- empty output
.schema foo_scalar
-- empty output
.schema foo_table
select * from duckdb_functions() where function_name like 'foo%';
```

### OS:

MacOS

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Mark Harrison

### Affiliation:

TigerEye

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by kswoll** [comment]
Is there any way to get a list of the macros in the database at all?
