### ISSUE TITLE
[Python] read_parquet and read_json do not accept file paths as pathlib.Path values

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb#8182]
### What happens?

When calling both `read_json` and `read_parquet` with path values of type `pathlib.Path`, an error is thrown: `TypeError: read_parquet(): incompatible function arguments.`

Whereas `read_csv` is able to handle `pathlib.Path` ok.

### To Reproduce

These both throw errors:
    
    duckdb.read_parquet(Path("blah.parquet"))

    duckdb.read_json(Path("blah.json"))

Whereas this works:

    duckdb.read_csv(Path("blah.csv"))

### OS:

Ubuntu 23.04

### DuckDB Version:

0.8.2.dev1435

### DuckDB Client:

Python

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by cdeil** [comment]
Could you please also support [pathlib.Path](https://docs.python.org/3/library/pathlib.html) also in `duckdb.connect`?

```
$ python
>>> from pathlib import Path
>>> import duckdb
>>> path = Path("spam.duckdb")
>>> duckdb.connect(path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: connect(): incompatible function arguments. The following argument types are supported:
    1. (database: str = ':memory:', read_only: bool = False, config: dict = None) -> duckdb.DuckDBPyConnection

Invoked with: PosixPath('spam.duckdb')
```

pathlib.Path has become standard in Python since it was introduced 10 years ago, it's widely used now and I'm not aware of another common package doing I/O that doesn't support it by now. :-)

It should be as easy as putting this at the start of your functions:
```python
def connect(database: str | pathlib.Path, ...):
    if isinstance(database, pathlib.Path):
        database = str(database)
```

Thank you!

**Comment by szarnyasg** [comment]
@cdeil please open a feature request at https://github.com/duckdb/duckdb/discussions/new/choose

**Comment by cdeil** [comment]
@szarnyasg - ok, here: https://github.com/duckdb/duckdb/discussions/8878

**Comment by bolkedebruin** [comment]
It would be nicer if duck db supports the `pathlib.Path.open()` interface rather than doing `str(database)` as was suggested above. Pathlike interfaces might support non local files residing somewhere else.

**Comment by Mause** [comment]
> It would be nicer if duck db supports the `pathlib.Path.open()` interface rather than doing `str(database)` as was suggested above. Pathlike interfaces might support non local files residing somewhere else.

Given we already support fsspec, I'm not sure that's really needed?

**Comment by bolkedebruin** [comment]
oh you do? I missed that! If so, then that would be indeed be sufficient
