### ISSUE TITLE
DuckDB ODBC driver crashed at odbc/parameter_descriptor.cpp:245

### ISSUE THREAD

**Issue by fuboat** [duckdb/duckdb#8190]
### What happens?

DuckDB ODBC driver crashed at odbc/parameter_descriptor.cpp:245.
The isql command of unixodbc reports "'isql duckdb -v -e' terminated by signal SIGSEGV (Address boundary error)".

### To Reproduce

```sql
SELECT $x;
SELECT $x;
```

### OS:

ubuntu 20.04 x64

### DuckDB Version:

v0.8.2-dev1293 f2dc7d8bce

### DuckDB Client:

unixodbc with ODBC driver

### Full Name:

Jingzhou Fu

### Affiliation:

Wingtecher Lab of Tsinghua University and Shuimuyulin ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by maiadegraaf** [comment]
Thanks for your issue, a fix for it has been merged
