### ISSUE TITLE
Segfault while inserting Polars dataframe into an existing DuckDB table.

### ISSUE THREAD

**Issue by rkimoakbioinformatics** [duckdb/duckdb#8201]
### What happens?

Segfault occurs when Polars dataframe is inserted to an existing DuckDB database.

### To Reproduce

Below is an example.
```python
import polars as pl
import duckdb

conn = duckdb.connect("test.duckdb")
conn.execute("drop table if exists test")
conn.execute("create table test (col_2 string[])")
df = pl.DataFrame([pl.Series("col_1", [["value"]], dtype=pl.List(pl.Utf8))])
for i in range(10000):
    print(i)
    conn.execute("insert into test select * from df")
```
On my machine, most of the time the seg fault occurs exactly at i=2048 and sometimes at i=2050. `col_2` in DuckDB and `col_1` in Polars are intentional. The seg fault occurs whether the column names match or not.

### OS:

Mac aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Rick Kim

### Affiliation:

Oak Bioinformatics, LLC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I can not reproduce the issue with the example you provided when building on latest master.

**Comment by rkimoakbioinformatics** [comment]
Actually, somehow it works on my machine as well. Also, the original problem went away. I don't know what happened, but thanks for looking into it. Closing the issue.
