### ISSUE TITLE
[Python] relation.types and relation.columns values incorrect after creating relation with read_csv()

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb#8209]
### What happens?

When using `duckdb.read_csv` to load a CSV file that has a date column in a format that uses an explicit date parsing template for, the value of the `types` property of the resulting relation is showing that the date column has type `VARCHAR`, even though inspecting the relation shows the parsing to have worked and produced a `DATE`.

### To Reproduce

```python
with open("test.csv", "w") as f:
    f.write("date,greeting\n")
    f.write("July 11 2023,quack\n")

rel = duckdb.read_csv(
    "test.csv", dtype={"date": duckdb.typing.DATE}, date_format="%B %d %Y"
)
print(rel)
rel.types
```

Resulting output:
```
┌────────────┬──────────┐
│    date    │ greeting │
│    date    │ varchar  │
├────────────┼──────────┤
│ 2023-07-11 │ quack    │
└────────────┴──────────┘

[VARCHAR, VARCHAR]
```

### OS:

Ubuntu 23.04

### DuckDB Version:

0.8.2.dev1435

### DuckDB Client:

Python

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ned2** [comment]
Ahh, and I just realised that there's an issue with the column names of the relation produced from `read_csv`. They are set to `column0` and `column1`.

Once this relation is queried from, both the types and columns properties are set correctly in the subsequently created relation:

```python
duckdb.sql("FROM test")
print(rel.types)
print(rel.columns)
```

**Comment by Tishj** [comment]
This is caused by Relations getting both bound on creation and at execution.
There seems to be some discrepancy between the two bind passes as well.

I looked into this a little and making the creation bind pass aware of the dtypes fixes the issue (as this binding is responsible for determining the types/names of the relation), but it does require passing in `header=True` in this case.

**Comment by ned2** [comment]
ahh so without making any under the hood changes, just adding `header=True` fixes the column names issue (but not the types).

**Comment by ned2** [comment]
hey @Tishj and @Mytherin, is there anything else I can do to help triage this?

**Comment by ned2** [comment]
Amazing! Thanks so much :D
