### ISSUE TITLE
LEFT JOIN and equivalent subquery SQLs return different results 

### ISSUE THREAD

**Issue by zsvoboda** [duckdb/duckdb#8216]
### What happens?

I believe that the 2 SQL queries below should return the same number. Can you explain why this isn't the case?

```sql
SELECT
        COUNT(DISTINCT array_id)
    FROM ps_filesystem
    WHERE array_id NOT IN (SELECT DISTINCT array_id FROM ps_sfdc_asset);

-- Result: 0

SELECT
        COUNT(DISTINCT f.array_id)
    FROM ps_filesystem f
    LEFT JOIN ps_sfdc_asset a ON a.array_id = f.array_id
    WHERE a.array_id IS NULL;

-- Result: 109
```

### To Reproduce

See the SQL above.

### OS:

Mac OSX 13.4.1

### DuckDB Version:

0.8.1

### DuckDB Client:

JDBC driver

### Full Name:

Zdenek Svoboda

### Affiliation:

Purs Storage

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by davidjbrennan** [comment]
Those queries won't produce the same result  when nulls are involved.  I suspect in your data that one or more of the array_id values are null in the ps_sfdc_asset table.  

Have a read of (https://explainextended.com/2009/09/15/not-in-vs-not-exists-vs-left-join-is-null-sql-server/) to understand why.

**Comment by l1t1** [comment]
please post a reproductive example

**Comment by Mytherin** [comment]
As mentioned, the system is likely correct here. `NOT IN` **cannot** return true when there are NULL values in the subquery. `NULL` values logically mean `I don't know what this value is`. When there are values in the subquery for which we do not know what the value is, the logical result of `is this value in the subquery` is either (1) it is certainly in there or (2) I don't know if it is in there (i.e. `NULL`). `NOT IN` flips this and can either return `false` or `NULL`, and hence the provided query will never provide any rows if there are`NULL` values in the subquery.

See this example:

```sql
CREATE TABLE filter(i INTEGER);
INSERT INTO filter VALUES (1), (3), (NULL);
CREATE TABLE main(i INTEGER);
INSERT INTO main VALUES (1), (2), (3), (4), (5);
SELECT i, i NOT IN (SELECT DISTINCT i FROM filter) AS subq FROM main;
┌───────┬─────────┐
│   i   │  subq   │
│ int32 │ boolean │
├───────┼─────────┤
│     1 │ false   │
│     2 │ NULL    │
│     3 │ false   │
│     4 │ NULL    │
│     5 │ NULL    │
└───────┴─────────┘
```

And these queries returning different rows:

```sql
SELECT COUNT(DISTINCT i) AS distinct
FROM main
WHERE i NOT IN (SELECT DISTINCT i FROM filter);
┌──────────┐
│ distinct │
│  int64   │
├──────────┤
│        0 │
└──────────┘
SELECT COUNT(DISTINCT f.i) AS distinct
FROM main f
LEFT JOIN filter a ON a.i = f.i
WHERE a.i IS NULL;
┌──────────┐
│ distinct │
│  int64   │
├──────────┤
│        3 │
└──────────┘
```
