### ISSUE TITLE
Window function 'lead' should return valid results for rows with empty frames

### ISSUE THREAD

**Issue by aditi-pandit** [duckdb/duckdb#8217]
### What happens?

Window function lead should ignore frame boundaries during evaluation. It works within the scope of a partition. DuckDB however, seems to generate null results for empty frames.

### To Reproduce

In the following SQL window function lead is invoked with frame clause rows between 2 preceding and 4 preceding. This frame matches 0 rows. So DuckDB returns results as follows:

```sql
select c1, lead(c1, 2) over (order by c0 rows between 2 preceding and 4 preceding) as b from (values (1, 2), (2, 3), (3,4), (4,5)) a(c0, c1) ;
┌───────┬───────┐
│  c1   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     2 │       │
│     3 │       │
│     4 │       │
│     5 │       │
└───────┴───────┘
```

But lead window function works over a partition and not individual frames. So the results should always be those from the default frame.

```sql
D select c1, lead(c1, 2) over (order by c0) as b from (values (1, 2), (2, 3), (3, 4), (4, 5)) a(c0, c1) ;
┌───────┬───────┐
│  c1   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     2 │     4 │
│     3 │     5 │
│     4 │       │
│     5 │       │
└───────┴───────┘
```
### OS:

MacOS

### DuckDB Version:

latest

### DuckDB Client:

command line

### Full Name:

Aditi Pandit

### Affiliation:

IBM

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This appears to be working on `master`.  It probably got fixed as part of the vectorisation work when I broke the functions apart. We used to check the frame on every function, but now only aggregations check it. its a good test to have, though.

**Comment by hawkfish** [comment]
Actually it appears to be working in 0.8.1:

```sql
(.venv) hawkfish@Richards-MacBook-Pro-2 duckdb % ~/bin/duckdb-0.8.1 
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select c1, lead(c1, 2) over (order by c0) as b 
> from (values 
> (1, 2), 
> (2, 3), 
> (3, 4), 
> (4, 5)
> ) a(c0, c1);
┌───────┬───────┐
│  c1   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     2 │     4 │
│     3 │     5 │
│     4 │       │
│     5 │       │
└───────┴───────┘
```
