### ISSUE TITLE
`Assertion failed` when trying to load the spatial extension in Nodejs

### ISSUE THREAD

**Issue by jutiss** [duckdb/duckdb#8228]
### What happens?

I'm getting an error when trying to load the spatial extension in Nodejs:

`Assertion failed: (dynamic_cast<Assertion failed: (dynamic_cast<TARGET *>(this)), function Cast,TARGET *>(this)), function Cast, file parse_info.hpp, line 22.
 file parse_info.hpp, line 22.`

CLI and Python don't have this problem.

### To Reproduce

```javascript
const db = new duckdb.Database(path);
const connection = db.connect();
connection.exec("INSTALL spatial; LOAD spatial");
``` 

### OS:

macOS 13.4.1 (aarch64)

### DuckDB Version:

0.8.1

### DuckDB Client:

NodeJs

### Full Name:

Dima Edikhanov

### Affiliation:

NDA

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think we're aware of this issue, and as far as I understand it it's related to #6521

**Comment by prasunsultania** [comment]
I am getting the exact same error in Node.js v18.16.0 on OSX 13.4.1 M1 mac when trying to load FTS extension

```js
const duckdb = require("duckdb");
const db = new duckdb.Database(":memory:");
const connection = db.connect();
connection.exec("LOAD 'fts'");
```

it works for me in a different Node.js folder where I installed FTS first, but, does not work on the another folder.

**Comment by carlopi** [comment]
I did reproduce using duckdb version 0.8.1 (latest release), but I can't anymore in development version.

You can get that doing `npm install duckdb@next`.

**Comment by aditya-nambiar** [comment]
I am seeing this error in using the Rust Client, duckdb-rs v 0.9.1

running 1 test
Assertion failed: (dynamic_cast<TARGET *>(this)), function Cast, file duckdb/src/include/duckdb/parser/parsed_data/parse_info.hpp, line 41.


Code - https://github.com/duckdb/duckdb-rs/blob/main/examples/parquet.rs

**Comment by Mause** [comment]
> I am seeing this error in using the Rust Client, duckdb-rs v 0.9.1
> 
> running 1 test
> Assertion failed: (dynamic_cast<TARGET *>(this)), function Cast, file duckdb/src/include/duckdb/parser/parsed_data/parse_info.hpp, line 41.
> 
> 
> Code - https://github.com/duckdb/duckdb-rs/blob/main/examples/parquet.rs

Please raise an issue in the rust repo

**Comment by aditya-nambiar** [comment]
Hey @carlopi , yes thats right MacOS. I was able to get it work by directly linking the library by using - DUCKDB_INCLUDE_DIR, its the bundled version that doesn't seem to work

**Comment by aditya-nambiar** [comment]
@Mause makes sense will file an issue there
