### ISSUE TITLE
Performance test and discussion about Vector::GetValue (VARCHAR)

### ISSUE THREAD

**Issue by longwallstreet** [duckdb/duckdb#8239]
### What happens?

We used duckdb/0.8.1 c++ api to do a performance test for reading parquet.

We found that when the LogicalType of a column in parquet is string (the length is small), the reading time will increase a lot.

Through the cpuprofile of gperftools, we found that malloc and free took a lot of time.

By reading the source code, we found that it is caused by Value(str.GetString()) in the following code
![Screenshot from 2023-07-13 22-16-40](https://github.com/duckdb/duckdb/assets/34297812/6fdf2b0e-03e2-4b49-b989-9b5b09496b9e)

string_t is a very good data structure. For short strings, use inlined buffer to avoid dynamic memory allocation and improve performance.

But str.GetString() will use string_t to construct std::string, which will generate dynamic memory allocation. At the same time, why is StringValueInfo defined in Value instead of using string_t directly?

Using string_t will bring a very significant performance improvement. We wrote the following test code to use GetViewForVarChar to replace GetValue, and found that the reading time was reduced by 50% in some scenarios.

![Screenshot from 2023-07-13 22-50-52](https://github.com/duckdb/duckdb/assets/34297812/ded9f3cf-0539-4ef3-a1bc-ef7f5f3d086e)

PS: The environment of the machine is Centos7.9, intel 10980k, gcc10, but the macro GLIBCXX_USE_CXX11_ABI is disabled

The tested parquet has 80 million rows and 11 columns. There are three columns whose LogicType is String and whose lengths are 6, 1, 1 respectively. The remaining eight columns are all of LogicType int64

### To Reproduce

Calling Vector::GetValue(VARCHAR) in c++ takes a long time

### OS:

Oracle7.9 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

C++

### Full Name:

Jun Xu

### Affiliation:

Beijing Zhuoshi Private Equity Fund Management Co., Ltd.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
GetValue is by no means fast as the Value API is not designed for speed.

There is a much more efficient way to get data from a Vector, you might want to have a look at internals, or the docs

**Comment by longwallstreet** [comment]
@Tishj Can we add a validity getter method in duckdb/common/types/vector.hpp? 
In this way, even if we use c++ api, we can externally wrap an efficient interface to obtain string_t data. 


![GetValidity](https://github.com/duckdb/duckdb/assets/34297812/45bd96e2-5bc1-4d7b-9bb4-6aaf1e903bd6)

In this way, even if we use c++ api, we can externally wrap an efficient interface to obtain string_t

**Comment by Tishj** [comment]
The helper classes for Vector already contain methods that retrieve the validity, namely things like:
`FlatVector::Validity(vec)` and `ConstantVector::Validity(vec)`

**Comment by longwallstreet** [comment]
@Tishj thank you.
