### ISSUE TITLE
REE - RLE Integration on Execution

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#8249]
The idea is to implement RLE Vectors in DuckDB and integrate with the [REE](https://arrow.apache.org/docs/format/Columnar.html) representation of Arrow.

Battle Plan:

- [ ] Decompress REE to Flat Vector.
       In this initial phase, we will support the consumption of REE to flat vectors.
- [ ] Change storage of RLE from segment to vector.
       Currently, our RLE runs within segments. To better support RLE vectors, we will change our storage to run on vectors instead.
As an example of the representation:
```
VECTOR_SIZE=4
FLAT_VECTOR=[0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,4,5,5,5,5]

Runs    | 3 1 | 2 2 | 1 3 | 4 | 4 | 
Data     | 0 1 | 1 2 | 2 3 | 4 | 5 |  
Vector  | 0   | 2    | 4    | 5 |  6 | 
```
- [ ] Implement RLE Vectors.
       At this point, we should decompress RLE vectors to flat vectors when using them.
- [ ] Change REE Integration to convert to RLE (Round-Trip it).
- [ ] [Specialized code](https://15721.courses.cs.cmu.edu/spring2017/papers/11-compression/abadi-sigmod2006.pdf) for RLE for operators that can benefit from them

**Comment by Tishj** [comment]
We're currently blocked by this issue:
https://github.com/apache/arrow/issues/34701#issuecomment-1579030034

Since we use `_export_to_c` internally to get the arrow arrays and schemas, we run into this not implemented error:
```
pyarrow.lib.ArrowNotImplementedError: Exporting run_end_encoded<run_ends: int32, values: int64> array not supported
```

**Comment by felipecrv** [comment]
#34701 is about converting to Pandas. This is about exporting to C which I expect to be easier.

**Comment by felipecrv** [comment]
I opened a PR to fix this https://github.com/apache/arrow/pull/37174

**Comment by SChakravorti21** [comment]
Hey @pdet @Tishj! Curious to hear if or how this integration is coming along. I was trying to query Arrow tables containing REE arrays through DuckDB 0.9.0 and it seems some of this integration is yet to be implemented. I'd be very happy to help out with this if bandwidth is the main limitation 😄.

**Comment by pdet** [comment]
This as recently merged with https://github.com/duckdb/duckdb/pull/9836

It will come along on the next DuckDB release in the next few weeks :-)
