### ISSUE TITLE
COPY not respecting memory_limit when threads > 1

### ISSUE THREAD

**Issue by lucmartinon** [duckdb/duckdb#8270]
### What happens?

When exporting CSVs or parquet files using the COPY command, if the threads param is not set to 1, the memory_limit param seems to be ignored, leading to threads getting killed. 

I have a table with over 10M rows, 68 columns, that I need to export to a parquet file and to a csv file. I simply use the COPY function. To give an idea, the resulting parquet file is 1.6 GB, the zipped csv file as well. On my machine (mac M1 with 16 GB ram) it runs, no matter the value I set for memory_limit and for the number of threads to use. If needed, the data is available [here](http://vps-f4624767.vps.ovh.net/download/ts_declaration.parquet).

When running on my server (8GB Ram, 4 vCores) however, it often fails, the python process is killed by the system, as it runs out of memory. I tested different values of threads and memory_limit and have the following results:
![image](https://github.com/duckdb/duckdb/assets/48994518/227d1acf-8b13-427e-9c47-bd42e1b85a38)
table as text:
https://docs.google.com/spreadsheets/d/1m8DgvUXLYNhMdNdhhkdaCTGG1Dn4SFD0c561x0mxbOo/edit#gid=0

I made all these tests without anything else running on the server, so there are around 7,12 GB of Ram free. 

From what I see, setting the threads to anything but 1 makes the param memory_limit not respected at all. 

### To Reproduce

I made this python file to test

```python
import click
import duckdb
import os
import logging
from src.constants.directories import CLEANED_DATA_DIR
from src.settings import DUCKDB_FP

CSV_FP = os.path.join(CLEANED_DATA_DIR, 'declarations.csv.gz')
PARQUET_FP = os.path.join(CLEANED_DATA_DIR, 'declarations.parquet')


def get_con(threads=None, max_mem=None):
    con = duckdb.connect(DUCKDB_FP)
    if max_mem:
        con.execute(f"SET memory_limit='{max_mem}';")
    if threads:
        con.execute(f"SET threads to {threads};")

    m = con.execute(f"select current_setting('memory_limit');").fetchone()[0]
    logging.info(f"DuckDB memory limit: {m}")
    t = con.execute(f"select current_setting('threads');").fetchone()[0]
    logging.info(f"DuckDB threads: {t}")
    con.execute("PRAGMA enable_progress_bar")
    return con


@click.group()
def cli():
    pass

@cli.command('csv')
@click.option('-t', 't')
@click.option('-m',  'm')
def export_csv(t=None, m=None):
    con = get_con(t, m)
    query = f"COPY ts_declaration TO '{CSV_FP}' (FORMAT CSV, HEADER) ;"
    con.execute(query)
    logging.info('success')


@cli.command('parquet')
@click.option('-t', 't')
@click.option('-m',  'm')
def export_parquet(t=None, m=None):
    con = get_con(t, m)
    query = f"COPY ts_declaration TO '{PARQUET_FP}' (FORMAT PARQUET) ;"
    con.execute(query)
    logging.info('success')


if __name__ == '__main__':
    cli()

```

then called it with different params, like 
```
python test_mem.py parquet -t 4 -m 1G
```

 (see result table above)

### OS:

Debian 11

### DuckDB Version:

8.1

### DuckDB Client:

python

### Full Name:

Luc Martinon

### Affiliation:

Euros For Docs (french NGO)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by catwang01** [comment]
Run into the same problem when using chroma which uses duckdb internally.
