### ISSUE TITLE
SQLite attach breaks information_schema queries

### ISSUE THREAD

**Issue by eeroel** [duckdb/duckdb#8271]
### What happens?

After attaching an sqlite database with `ATTACH ... (TYPE sqlite)`, queries to `information_schema.tables` fail with errors like this: `Failed to prepare query "PRAGMA table_info('global-power-plants_fts')": no such module: FTS5`. In contrast, when using `CALL sqlite_attach`, this error is raised only once when executing the call, but it doesn't seem to affect further queries. And in both cases the table actually gets created.

### To Reproduce

Using this ~15MB file from the Datasette example: https://global-power-plants.datasettes.com/global-power-plants.db
This query succeeds (Python code):

```python
import duckdb
db=duckdb.connect(":memory:");
db.execute("INSTALL sqlite; LOAD sqlite; SET GLOBAL sqlite_all_varchar=true; ATTACH 'global-power-plants.db' (TYPE sqlite);").fetchall();
```
```text
[]
```

But querying information_schema.tables fails:

```python
db.query('''select * from information_schema.tables''')
```
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Invalid Error: Failed to prepare query "PRAGMA table_info('global-power-plants_fts')": no such module: FTS5
```

Same error when trying to query a non-existent table:
```python3
db.query('''select * from foobar''')
```
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Failed to prepare query "PRAGMA table_info('global-power-plants_fts')": no such module: FTS5
```
### OS:

Mac OS X

### DuckDB Version:

0.8.2-dev1764

### DuckDB Client:

Python

### Full Name:

Eero Lihavainen

### Affiliation:

https://github.com/NitorCreations

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This looks like two issues

One, our copy of SQLite in the extension doesn't have the "FTS5" SQLite extension included.

Two, if an SQLite table can't be read (because of issues with extensions, for example), it breaks the information_schema, as you've noted. I imagine it works fine if the SQLite file doesn't contain any tables using extensions.

We should probably fix it so that we don't register tables we can't read (and log something for those)

**Comment by eeroel** [comment]
Yes, that sounds about right.

> We should probably fix it so that we don't register tables we can't read (and log something for those)
I should clarify that the sqlite table seems to read fine despite the errors. I'm not too familiar with sqlite and FTS5, but seems like having the extension is not essential at least for this database, so maybe a warning would do? Although I guess things would be different if the attached db contained views using the extension.

**Comment by Mause** [comment]
@eeroel can you read the `global-power-plants_fts` table using the function attach?

**Comment by eeroel** [comment]
> @eeroel can you read the `global-power-plants_fts` table using the function attach?

No, sorry, I checked now with sqlite in Python and only the `global-power-plants` table is readable in duckdb, these are the objects in the sqlite database:

```
[print(x) for x in foo.execute("select type, name from sqlite_master").fetchall()]

('table', 'global-power-plants')
('index', '"global-power-plants_country_long"')
('index', '"global-power-plants_owner"')
('table', 'global-power-plants_fts')
('table', 'global-power-plants_fts_data')
('table', 'global-power-plants_fts_idx')
('table', 'global-power-plants_fts_docsize')
('table', 'global-power-plants_fts_config')
```

**Comment by Mytherin** [comment]
This should be fixed with https://github.com/duckdb/sqlite_scanner/pull/70 - we compile FTS into the SQLite extension now
