### ISSUE TITLE
Date ranges starting from end-of-month are wrong

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#8284]
### What happens?

`range` and `generate_series` return the wrong values for end-of-month dates. In particular, each returned value is one interval greater than the previous value; and not N intervals greater than the first value.

### To Reproduce

```
D select unnest(generate_series(date '2022-01-31', date '2022-07-31', interval '1' month)) as month;
┌─────────────────────┐
│        month        │
│      timestamp      │
├─────────────────────┤
│ 2022-01-31 00:00:00 │
│ 2022-02-28 00:00:00 │
│ 2022-03-28 00:00:00 │
│ 2022-04-28 00:00:00 │
│ 2022-05-28 00:00:00 │
│ 2022-06-28 00:00:00 │
│ 2022-07-28 00:00:00 │
└─────────────────────┘
```

I'd expect this to behave like Pandas:
``` python
>>> import pandas as pd;
>>> pd.date_range('2022-01-31', '2022-07-31', freq='M')
DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31'],
              dtype='datetime64[ns]', freq='M')
```

FWIW, Postgres returns the same thing as DuckDB.

### OS:

OSX

### DuckDB Version:

0.8.1

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
Unfortunately, this is what Postgres does, so I think we will have to leave it:

```sql
hawkfish=# select * from generate_series(date '2022-01-31', date '2022-07-31', interval '1' month);
    generate_series     
------------------------
 2022-01-31 00:00:00-08
 2022-02-28 00:00:00-08
 2022-03-28 00:00:00-07
 2022-04-28 00:00:00-07
 2022-05-28 00:00:00-07
 2022-06-28 00:00:00-07
 2022-07-28 00:00:00-07
```

I think it is probably safer (and more explicit) to just subtract one day from a series that generates the first of the month:

```sql
SELECT d - INTERVAL 1 DAY AS month 
FROM generate_series(date '2022-02-01', date '2022-08-01', INTERVAL '1' MONTH) tbl(d);
┌─────────────────────┐
│        month        │
│      timestamp      │
├─────────────────────┤
│ 2022-01-31 00:00:00 │
│ 2022-02-28 00:00:00 │
│ 2022-03-31 00:00:00 │
│ 2022-04-30 00:00:00 │
│ 2022-05-31 00:00:00 │
│ 2022-06-30 00:00:00 │
│ 2022-07-31 00:00:00 │
└─────────────────────┘
```

This should work even in strange calendars or if you forget you are in a leap year (e.g., one of the bounds is `2020-02-28`!)
