### ISSUE TITLE
ARRAY_CONCAT() on array<struct> gives incorrect result when struct fields are in different orders

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#8301]
### What happens?

Note that the two source structs are exactly the same except the fields are a,b in one, and b,a in the other
 ```SQL
CREATE OR REPLACE TABLE T AS SELECT [{'a': 'A', 'b':'B'}] as x, [{'b':'BB','a':'AA'}] as y;
SELECT x, y, ARRAY_CONCAT(x, y) FROM T;
```
Gives (note the "a": "BB" and "b": "AA" in the second element of the result)

```
┌────────────────────────┬──────────────────────────┬────────────────────────────────────────────────┐
│ x                      ┆ y                        ┆ array_concat(x, y)                             │
╞════════════════════════╪══════════════════════════╪════════════════════════════════════════════════╡
│ [{"a": "A", "b": "B"}] ┆ [{"b": "BB", "a": "AA"}] ┆ [{"a": "A", "b": "B"}, {"a": "BB", "b": "AA"}] │
└────────────────────────┴──────────────────────────┴────────────────────────────────────────────────┘
```

### To Reproduce

See above

### OS:

https://shell.duckdb.org/

### DuckDB Version:

v0.8.2-dev1781

### DuckDB Client:

https://shell.duckdb.org/

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think this is related to #7303 and I think that makes it intended behavior for now, though as mentioned in that issue, that might be subject to change in the future

**Comment by Mytherin** [comment]
Indeed this is not a bug but rather a confusing implicit cast being inserted by the system. Struct casts work based on column **position**, not column **name**, so e.g. this is expected behavior:

```sql
D select {'b': 10, 'a': 1}::STRUCT(a INT, b INT) AS s;
┌──────────────────────────────┐
│              s               │
│ struct(a integer, b integer) │
├──────────────────────────────┤
│ {'a': 10, 'b': 1}            │
└──────────────────────────────┘
```

The problem here is that such a cast is automatically inserted which causes confusing behavior. We should remove the implicit casting here.

**Comment by NickCrews** [comment]
My two cents is that it would be more ergonomic if structs ignored field position, and only cared about field names. [The description of structs](https://duckdb.org/docs/sql/data_types/overview.html#nested--composite-types) even calls structs "A dictionary", which for me has strong connotations of meaning unordered and named. I'm sure there are ergonomic and implementation reasons why it would be bad to switch at this point. I can open a separate issue for this, or a discussion, or something else? I think somewhere with all the pros/cons laid out would be useful.

**Comment by Tishj** [comment]
@NickCrews In the issue I linked, Mytherin has commented on this: https://github.com/duckdb/duckdb/issues/7303#issuecomment-1529784302
