### ISSUE TITLE
The download of extension is by default on http

### ISSUE THREAD

**Issue by alexisdondon** [duckdb/duckdb#8304]
### What happens?

The download of extension is by default on http https://github.com/duckdb/duckdb/discussions/8238 is there a reason not to be in https by default?

### To Reproduce

Juste make a an extension download

### OS:

linux

### DuckDB Version:

latest

### DuckDB Client:

Python

### Full Name:

Alexis D.

### Affiliation:

Insee

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
The downloading of extensions is always done using http to prevent having to ship a HTTP library that supports HTTPS with every installation of DuckDB. Instead the extensions themselves are cryptographically signed which prevents man-in-the-middle attacks. See #4089 for more info.
