### ISSUE TITLE
Incorrect results for window functions with different NULLS FIRST / NULLS LAST ordering

### ISSUE THREAD

**Issue by NMAC427** [duckdb/duckdb#8315]
### What happens?

When running a querie that contains two window functions that use the same `ORDER BY` part in the `OVER` clause, but that have a different ordering of nulls (one has `NULLS LAST`, the other has `NULLS FIRST`), then both window functions get run with whatever `OVER` clause got defined first.

Consequently, the query produces incorrect results.

### To Reproduce

```python
import duckdb
import pandas as pd

df = pd.DataFrame({"x": [1, 1, 1, None]})

duckdb.sql("""
    SELECT 
        *, 
        RANK() OVER (ORDER BY x NULLS FIRST) rank_nulls_first,
        RANK() OVER (ORDER BY x NULLS LAST) rank_nulls_last,
    FROM df
    ORDER BY x
""")
```

This returns:

```
┌────────┬──────────────────┬─────────────────┐
│   x    │ rank_nulls_first │ rank_nulls_last │
│ double │      int64       │      int64      │
├────────┼──────────────────┼─────────────────┤
│    1.0 │                2 │               2 │
│    1.0 │                2 │               2 │
│    1.0 │                2 │               2 │
│   NULL │                1 │               1 │
└────────┴──────────────────┴─────────────────┘
```

But we would expect:

```
┌────────┬──────────────────┬─────────────────┐
│   x    │ rank_nulls_first │ rank_nulls_last │
│ double │      int64       │      int64      │
├────────┼──────────────────┼─────────────────┤
│    1.0 │                2 │               1 │
│    1.0 │                2 │               1 │
│    1.0 │                2 │               1 │
│   NULL │                1 │               4 │
└────────┴──────────────────┴─────────────────┘
```

Interestingly, when you modify one of the `ORDER BY` clauses, so that they contain different expressions that evaluate to the same value, then it works as expected:

```python
duckdb.sql("""
    SELECT 
        *, 
        RANK() OVER (ORDER BY  x NULLS FIRST) rank_nulls_first,
        RANK() OVER (ORDER BY +x NULLS LAST) rank_nulls_last,
    FROM df
    ORDER BY x
""")
```

### OS:

macOS aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Nicolas Camenisch

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
The code in the planner compares sort orders but must not be checking this.

**Comment by hawkfish** [comment]
The window planner combines window functions with identical sorts and the existing code was not checking the null ordering, so it thought the sorts were the same. The order comparison also compares expressions and by adding the `+` you convert it to a "different" expression so the two functions were evaluated in different window operators.
