### ISSUE TITLE
Incorrect results when using time datatypes in where clause

### ISSUE THREAD

**Issue by javivallejo** [duckdb/duckdb#8316]
### What happens?

Running a query that should give some results but doesnt. 
If the same query is run on another table that is a subset of the first table, it does run good.
Seems that the problem is that the query checks the first day available and if there is not a match, it doesn't look in the rest of days.

### To Reproduce

Create a 'sample' table from the CSV [temp55.csv](https://github.com/duckdb/duckdb/files/12551906/temp55.csv).

```python
CREATE TABLE sample AS
SELECT * FROM read_csv_auto('temp55.csv');
``` 

Trying to get rows matching the time filter, no results (which is incorrect).
```python
SELECT *
FROM sample
WHERE CAST(dt as TIME) = CAST('10:04:25' as TIME);
``` 

Creating another table from a subset of the table above:
```python
CREATE OR REPLACE TABLE sample2 AS
SELECT * 
FROM sample
WHERE dt >= DATE '2016-02-15';
``` 

Running the same query as before from this new table (subset of the original) does return values.
```python
SELECT *
FROM sample2
WHERE CAST(dt as TIME) = CAST('10:04:25' as TIME);
``` 

### OS:

macos

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

Python and homebrew

### Full Name:

JaviV

### Affiliation:

Personal - no affiliation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by javivallejo** [comment]
Just tested in Motherduck, it works fine there.

**Comment by szarnyasg** [comment]
@javivallejo please make the CSV available.

**Comment by szarnyasg** [comment]
CSV: [temp55.csv](https://github.com/duckdb/duckdb/files/12551906/temp55.csv)

**Comment by szarnyasg** [comment]
Thanks for the CSV, I could reproduce the issue.

**Comment by hawkfish** [comment]
This looks like an optimiser issue:

```sql
D explain SELECT *
> FROM sample
> WHERE CAST(dt as TIME) = CAST('10:04:25' as TIME);

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│        EMPTY_RESULT       │
└───────────────────────────┘                             
```

**Comment by hawkfish** [comment]
The query works if the table is not materialised, which suggests a statistics issue.

**Comment by hawkfish** [comment]
`StatisticsNumericCastSwitch` assumes that casting between numeric types is simply a loss of precision. This is not true for `TIMESTAMP` => `TIME` (which is a masking operation).
