### ISSUE TITLE
NodeJS - Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by melihcaliskanhnc** [duckdb/duckdb#8319]
### What happens?

I'm trying to deploy the example server to Kubernetes. 

Getting 
```
build-dv-dataserver-1  | node:internal/modules/cjs/loader:1282
build-dv-dataserver-1  |   return process.dlopen(module, path.toNamespacedPath(filename));
build-dv-dataserver-1  |                  ^
build-dv-dataserver-1  | 
build-dv-dataserver-1  | Error: /usr/src/app/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory
build-dv-dataserver-1  |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
build-dv-dataserver-1  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
build-dv-dataserver-1  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
build-dv-dataserver-1  |     at Module.require (node:internal/modules/cjs/loader:1100:19)
build-dv-dataserver-1  |     at require (node:internal/modules/cjs/helpers:108:18)
build-dv-dataserver-1  |     at Object.<anonymous> (/usr/src/app/node_modules/duckdb/lib/duckdb-binding.js:4:15)
build-dv-dataserver-1  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
build-dv-dataserver-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
build-dv-dataserver-1  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
build-dv-dataserver-1  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
build-dv-dataserver-1  |   code: 'ERR_DLOPEN_FAILED'
build-dv-dataserver-1  | }
``` 
error while running the Docker image

### To Reproduce

My Dockerfile:

```
FROM node:16
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . 
EXPOSE 3000
CMD ["node", "bin/run-server.js"]
``` 

My package.json:
```javascript
  "dependencies": {
    "duckdb": "~0.8.1",
    "ws": "^8.13.0"
  },
``` 

### OS:

x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Node

### Full Name:

-

### Affiliation:

-

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by melihcaliskanhnc** [comment]
Hey @Mause, thanks for your response, I'm sorry for the late reply.
I've created a project from scratch and got the same error. 
Please see my repo: https://github.com/melihcaliskanhnc/duckdb-node-example

```
➜  duckdb-node-example git:(main) ✗ docker run 16dc08c87aed
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/src/app/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/src/app/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.17.0
```

**Comment by Mause** [comment]
Unfortunately I'm not able to reproduce with that repo either, the container builds and starts fine

**Comment by melihcaliskanhnc** [comment]
Hey again @Mause, after your response I investigated it a bit more and found adding `--platform=linux/amd64` while creating the image resolved my issue. Thanks a lot.

**Comment by xxk59** [comment]
@melihcaliskanhnc I am stuck in the same situation, and can reproduce the case you provided above. Can you tell me where to add the --platform=linux/amd64 exactly? I'm using apple M1 pro and new to all this.

**Comment by melihcaliskanhnc** [comment]
@xxk59 To build your container you can use `docker build -f <your docker file> . --platform=linux/amd64`
then you can list images with `docker images` to get the container id,
and finally, you can type `docker run <id>` to run it.

**Comment by xxk59** [comment]
THANKS @melihcaliskanhnc！This saves a lot time of digging.

**Comment by kriscarle** [comment]
A note for anyone else that ends up here, I got this error when installing `duckdb@0.8.1` in docker using `linux/arm64`. Upgrading to a newer version 0.9.1+ resolves it. 

To reproduce it 

```sh
docker run --rm -it node:18 bash
mkdir app
cd app
npm init -y
npm install duckdb@0.8.1
cd node_modules/duckdb
npm install
npm test
# outputs: /app/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory
cd ../../
npm remove duckdb
npm install duckdb@0.9.1
cd node_modules/duckdb
npm install
npm test
# it works!
```

**Comment by yashsoni369** [comment]
it is breaking for me as well.. only works on windows development env, not in vercel / azure / dockerized, all fails 

```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /node_modules/duckdb/lib/binding/duckdb.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)       
    at Object.<anonymous> (/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12) {
  code: 'ERR_DLOPEN_FAILED'
}

```

**Comment by carlopi** [comment]
@yashsoni369: what kind of distribution? It's alpine by any chance?

**Comment by yashsoni369** [comment]
So I have tried following things so far. (my dev machine is windows and deployment is on Linux servers

1. used the nodejs neo npm version in nextjs and tried to deploy on vercel. Vercel always threw this error : `cannot find @duckdb/node-bindings-linux-x64`

2. moved from nextjs fullstack to nextjs (FE) and Nestjs (BE) : 
     2.1 building and running nestjs on local fails
     2.2 tried deploying to Azure App Service , same issue

3. moved from node-js neo package to the classic duckdb package in nestjs
new error : ERR_DLOPEN_FAILED

**Comment by Mause** [comment]
How are you deploying to vercel? Using the cli, or pushing to git and letting vercel build your app?

**Comment by yashsoni369** [comment]
I went with the default vercel -> github integration with steps -> npm i && npm run build && then start
