### ISSUE TITLE
Error when using datediff() in a macro definition

### ISSUE THREAD

**Issue by BorgeJorge** [duckdb/duckdb#8329]
### What happens?

DuckDB will accept a macro definition that contains the datediff function when either the second or third argument to the datediff() function is an argument passed to the macro definition, but not when both datediff() arguments are also macro arguments.

### To Reproduce

```
-- DuckDB accepts these macro definitions:
create or replace macro datedifftest(dt) as datediff('month', date '1999-12-01', dt);
create or replace macro datedifftest(dt) as datediff('month', dt, date '1999-12-01');

-- But not these:
create or replace macro datedifftest(dt) as datediff('month', dt, dt);
create or replace macro datedifftest(dt1, dt2) as datediff('month', dt1, dt2);
```

### OS:

Windows 10, x64

### DuckDB Version:

8.1

### DuckDB Client:

R

### Full Name:

Tod Mijanovich

### Affiliation:

NYU

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hawkfish** [comment]
This is the error:

```sql
D create or replace macro datedifftest(dt) as datediff('month', dt, dt);
Error: Binder Error: Could not choose a best candidate function for the function call "datediff(VARCHAR, NULL, NULL)". In order to select one, please add explicit type casts.
	Candidate functions:
	datediff(VARCHAR, TIME, TIME) -> BIGINT
	datediff(VARCHAR, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) -> BIGINT
	datediff(VARCHAR, DATE, DATE) -> BIGINT
```

Looks like you need casts:

```sql
D create or replace macro datedifftest(dt) as datediff('month', dt::TIMESTAMP, dt);
D create or replace macro datedifftest(dt1, dt2) as datediff('month', dt1::TIMESTAMP, dt2);
D
```

**Comment by BorgeJorge** [comment]
Thank you so much @hawkfish!
