### ISSUE TITLE
[Python] incorrect parameter types in docstrings for a number of Python methods

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb#8332]
### What happens?

A number of Python API methods have doc strings featuring the type annotation `param: object = None` when they should be a specific type.

* `DuckDBPyConnection.read_csv` and `DuckDBPyConnection.read_csv_auto`: all keyword args affected
* `DuckDBPyConnection.from_parquet` and `DuckDBPyConnection.read_parquet`: `compression` keyword arg should be of type string
* `DuckDBPyRelation.write_csv` and `DuckDBPyRelation.to_csv`: all keyword args affected
* `DuckDBPyRelation.write_parquet` and `DuckDBPyRelation.to_parquet`:  `compression` keyword arg should be of type string
* `DuckDBPyConnection.execute` and `DuckDBPyConnection.executemany`: `parameters` can accept either a dictionary or a sequence, would be good to indicate this more explicitly

Also noticed that `DuckDBPyConnection.create_function` has a couple of issues:
- `return_type` param should be `duckdb.typing.DuckDBPyType = None`
- also looks like the order of `return_type` and `parameters` params should be swapped as covered by #8103 

### To Reproduce

Run `help` on any of the above methods. eg

    help(DuckDBPyConnection.read_csv)
    help(DuckDBPyRelation.write_parquet)

### OS:

Ubuntu 23.04

### DuckDB Version:

0.8.2-dev1968

### DuckDB Client:

Python

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This was my response in Discord:

> Yeah, the pybind11 type signatures are a bit annoying 
> We can specify the correct types in the signature, but then if you get one parameter type wrong, pybind throws an error without telling you which parameter is the issue
> ldeally we'd note the correct types in the docstring part that we define

**Comment by ned2** [comment]
Just checked that all the items I reported above are still issues. Bumping to keep from being closed.
