### ISSUE TITLE
unable to compile on mac m1 MacOs Monterey

### ISSUE THREAD

**Issue by jaihind213** [duckdb/duckdb#8339]
### What happens?

unable to compile duckdb rust example from [](https://docs.rs/duckdb/latest/duckdb/)

### To Reproduce

code:
```
  use duckdb::{params, Connection, Result};
  use duckdb::arrow::record_batch::RecordBatch;
  use duckdb::arrow::util::pretty::print_batches;
  
  #[derive(Debug)]
  struct Groupby {
      customer_id: f64,
      sum_total: i64
  }
  
  fn main() -> Result<()> {
      let path = "./file.db";
      let conn = Connection::open(&path)?;
  
      let mut stmt = conn.prepare("SELECT customer_id, sum(total_amount) FROM hits group by customer_id")?;
      let result_iter = stmt.query_map([], |row| {
          Ok(Groupby {
              customer_id: row.get(0)?,
              sum_total: row.get(1)?
          })
      })?;
  
      for res in result_iter {
          println!("Found result {:?}", res.unwrap());
      }
  
      // query table by arrow
      let rbs: Vec<RecordBatch> = stmt.query_arrow([])?.collect();
      print_batches(&rbs);
      Ok(())
  }
```

------Cargo.toml
```
[package]
name = "usingrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb = "0.8.1"
libduckdb-sys = "0.8.1"
```
------

cargo build 

------ gives  the following error

  = note: ld: library not found for -lduckdb
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

warning: `usingrust` (bin "usingrust") generated 3 warnings

### OS:

macOS Monterey M1

### DuckDB Version:

0.8.1

### DuckDB Client:

rust

### Full Name:

vishnu rao

### Affiliation:

cuezen

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
We don't provide support for the duckdb-rs bindings, please raise an issue here instead: https://github.com/wangfenjin/duckdb-rs
