### ISSUE TITLE
Cannot install duckdb v0.6.1 with npm

### ISSUE THREAD

**Issue by AlexanderJernstrom** [duckdb/duckdb#8346]
### What happens?

When running npm install in a node project with duckdb 0.6.1 as a dependency it crashes because it cannot find  the file in S3.
`
334.5 node-pre-gyp info it worked if it ends with ok
334.5 node-pre-gyp info using node-pre-gyp@1.0.10
334.5 node-pre-gyp info using node@18.17.0 | linux | arm64
334.5 node-pre-gyp info check checked for "/home/procuro/app/node_modules/duckdb/lib/binding/duckdb.node" (not found)
334.5 node-pre-gyp http GET https://duckdb-node.s3.amazonaws.com/duckdb-v0.6.1-node-v108-linux-arm64.tar.gz
334.5 node-pre-gyp ERR! install response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.6.1-node-v108-linux-arm64.tar.gz
334.5 node-pre-gyp WARN Pre-built binaries not installable for duckdb@0.6.1 and node@18.17.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp)`

### To Reproduce

Use version 0.6.1 in a node application

### OS:

Linux
### DuckDB Version:

0.6.1

### DuckDB Client:

Node

### Full Name:

Alexander Vivas

### Affiliation:
Freelance

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This is probably because it was prior to us starting to ship MacOS prebuilds for M1/aarch64. Later builds should be okay though, or you can build it yourself

**Comment by AlexanderJernstrom** [comment]
@Mause Thanks for the answer! However I forgot to mention that I was running it inside a docker container. And it has worked before like 3-4 weeks ago so it is weird that it stopped working now.

**Comment by Mause** [comment]
@AlexanderJernstrom Linux aarch64 nodejs builds are equally recent. Maybe check your old Docker build logs to see if you were previously emulating, or building it yourself inside the container without realizing?

**Comment by AlexanderJernstrom** [comment]
@Mause Thank you, I solved it by turning on Rosetta 2 and setting the platform option in the docker-compose file to linux/amd64 which worked.

**Comment by Mause** [comment]
Great to hear, in that case I'll close this issue
