### ISSUE TITLE
In Alter column statement, cannot set data type to JSON

### ISSUE THREAD

**Issue by bnm3k** [duckdb/duckdb#8351]
### What happens?

When using `alter` to set a column's type to JSON as follows:

```sql
alter table events
     alter column repo set data type JSON using json(repo);
```

 I get the following error:

```
Error: near line 7: Catalog Error: Type with name JSON does not exist!
Did you mean "main.JSON"?
```
All the VARCHAR values are valid json:
```sql
select count(*) as invalid
from events where json_valid(repo) <> True;
```
This gives:
```
┌─────────┐
│ invalid │
│  int64  │
├─────────┤
│       0 │
└─────────┘

```
Also, I did a `INSTALL` and `LOAD` for the JSON extension.

Current workaround seems to be:
```sql
begin;

alter table t1 add column temp JSON;
update t1 set temp = json(v);
alter table t1 drop v;
alter table t1 rename temp to v;

commit;
```

### To Reproduce

```sql
begin;

create table t1(
    v varchar
);

insert into t1(v) values
    ('{"name": "Alice"}'),
    ('{"name": "Bob"}');

alter table t1
    alter column v set data type JSON using json(v);

commit;
```

### OS:

Ubuntu 20.04.6  x64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

CLI

### Full Name:

Brandon Mochama

### Affiliation:

NA

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by szarnyasg** [comment]
This works on the latest `main`.
