### ISSUE TITLE
Catalog Errors do not result in transactions getting cancelled/rolled back

### ISSUE THREAD

**Issue by bnm3k** [duckdb/duckdb#8352]
### What happens?

When a Catalog Error occurs, the error is reported but the transaction still continues and side effects are persisted. For example:  
Let's create a table:
```sql
create table t1 (n int);
```
If we trigger a 'general' error within a transaction, it's aborted:
```sql
begin;

insert into t1 values(1);
select json(''); -- invalid input error
insert into t1 values(2);

commit;
```
With the error message:
```
Error: near line 13: Invalid Input Error: Malformed JSON at byte 0 of input: input length is 0.  Input:
Error: near line 14: Invalid Error: Current transaction is aborted (please ROLLBACK)
```
However, if there's a catalog error, it's reported but the transaction continues and changes are persisted:
```sql
begin;

insert into t1 values(1);
select count(*) from t2; -- catalog error
insert into t1 values(2);

commit;
```

The error message:
```
Error: near line 13: Catalog Error: Table with name t2 does not exist!
Did you mean "t1"?
LINE 1: select count(*) from t2;
```

The changes are persisted:
```
D select * from t1;
┌───────┐
│   n   │
│ int32 │
├───────┤
│     1 │
│     2 │
└───────┘

```

### To Reproduce

```sql
create table t1 (n int);

begin;

insert into t1 values(1);
select count(*) from t2;
insert into t1 values(2);

commit;
```

### OS:

Ubuntu 20.04.6  x64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

CLI

### Full Name:

Brandon Mochama

### Affiliation:

No current affiliation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is an intentional design decision made in DuckDB. Parser exceptions and binder exceptions do not invalidate transactions. That is because these types of exceptions are generally caused by typos, which are usually made in interactive mode. Invalidating a transaction because of a typo while in interactive mode is unnecessary and not user friendly, as such we opted to not invalidate the transaction when this happens.

**Comment by bnm3k** [comment]
Got it, thanks :-)
