### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by getorca** [duckdb/duckdb#8353]
### What happens?

calling `.torch() ` on a `duckdb.DuckDBPyRelation` object throws a `ModuleNotFoundError` exception.

### To Reproduce

```Python
import duckdb

rel = duckdb.sql('SELECT * FROM range(100)')

rel.torch()
```

### OS:

Ubuntu 20.04.6 LTS

### DuckDB Version:

duckdb-0.8.2.dev2044

### DuckDB Client:

Python 3.10.12

### Full Name:

Lawrence Stewart

### Affiliation:

Self Employed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
PyTorch is an optional dependency, you need to install it yourself with `pip install torch`

**Comment by getorca** [comment]
Yea, just realised that, thanks, close this. Cheers.
