### ISSUE TITLE
Prepared statement causing "Out of Range Error"

### ISSUE THREAD

**Issue by NMAC427** [duckdb/duckdb#8359]
### What happens?

When executing a prepared statement using the Python API leads to a "Out of Range Error" when the following conditions are met:
- The expression contains only literals
- The precision of the result is larger than the precision of the inputs.

### To Reproduce

```python
import duckdb
con = duckdb.connect(":default:")
con.execute("SELECT ? + ?", [100, 100]).fetchall()
```

```
---------------------------------------------------------------------------
OutOfRangeException                       Traceback (most recent call last)
      1 import duckdb
      2 con = duckdb.connect(":default:")
----> 3 con.execute("SELECT ? + ?", [100, 100]).fetchall()

OutOfRangeException: Out of Range Error: Overflow in addition of INT8 (100 + 100)!
```

However, running the prepared statement via CLI works fine:
```sql
PREPARE S1 AS SELECT ? + ?;
EXECUTE S1(100, 100);
┌───────────┐
│ ($1 + $2) │
╞═══════════╡
│       200 │
└───────────┘
```

### OS:

MacOS aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Nicolas Camenisch

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue, I also encountered this somewhere else, it should be fixed by #8469
