### ISSUE TITLE
Cannot install FTS extension (Julia/Windows)

### ISSUE THREAD

**Issue by Seitzal** [duckdb/duckdb#8363]
### What happens?

I'm using DuckDB via the Julia package on a Windows 11 machine. 
When I try to install the FTS extension, I get the following error:

```
ERROR: Execute of query "INSTALL 'fts';" failed: HTTP Error: Failed to download extension "fts" at URL "http://extensions.duckdb.org/v0.8.1/windows_amd64_mingw/fts.duckdb_extension.gz"
Extension "fts" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```

Copy-pasting the URL from the error message into a browser results in an "Access Denied" response.

### To Reproduce

- Open Julia REPL
- `using DuckDB`
- `db = DBInterface.connect(DuckDB.DB, "duck.db")`
- `DBInterface.execute(db, "INSTALL 'fts';")`

### OS:

Windows 11 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Julia

### Full Name:

Alex Seitz

### Affiliation:

University of Heidelberg

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by TimG1964** [comment]
Can I revive this issue? I am suffering from the exact same problem today.
