### ISSUE TITLE
Error applying "last" function on window

### ISSUE THREAD

**Issue by temphiza** [duckdb/duckdb#8370]
### What happens?

Applying `last` function on a simple window only returns a copy of the expression

### To Reproduce

1. Write the following sql query:
`
with data as (
    select
        unnest(['x', 'x', 'x', 'y', 'y', 'y']) as variable,
        unnest([1, 2, 3, 4, 5, 6]) as time,
        unnest([1, 0, 1, 2, 0, 2]) as value
)
select last(value) over (partition by variable order by time) as last from data
`

Actual column:
`[1, 0, 1, 2, 0, 2]`

Expected column:
`[1, 1, 1, 2, 2, 2]`

The actual column is a copy of the expression, using `first` instead of `last`; the result column is the expected.

### OS:

arm64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Faustino Neri

### Affiliation:

Emerald Digital

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for reporting the issue, that indeed looks like a bug.
Since we have only two distinct values in `variable`, I would expect the two partitions to contain `[1,2,3]` and `[4,5,6]` of the `time` column, and `[1,0,1]`, `[2,0,2]` for the `value` column.

So the `last(value)` should be `1` for the first partition and `2` for the second partition.

**Comment by Tishj** [comment]
Ah, it looks like you were looking to use a *frame*, so the rows don't get evaluated one at a time.
```sql
with data as (select unnest(['x', 'x', 'x', 'y', 'y', 'y']) as variable, unnest([1,2,3,4,5,6]) as time, unnest([1,0,1,2,0,2]) as value) select last(value) over (partition by variable order by "time" range between 2 preceding and 2 following) as last from data;
```

This gets the result you were looking for:
```
┌───────┐
│ last  │
│ int32 │
├───────┤
│     1 │
│     1 │
│     1 │
│     2 │
│     2 │
│     2 │
└───────┘
```

**Comment by temphiza** [comment]
Thanks, @Tishj for your help, my idea is just find the latest values for each partition, I was ignoring window documentation, last is evaluated at the row that is the last row of the window frame, in the original query frame size is one, to get last value for each partition an unbounded frame is expected:

```sql
with data as (
    select
        unnest(['x', 'x', 'x', 'y', 'y', 'y']) as variable,
        unnest([1, 2, 3, 4, 5, 6]) as time,
        unnest([1, 0, 1, 2, 0, 2]) as value
)
select 
    last(value) over (partition by variable order by time range between unbounded  preceding and unbounded following) as last 
from data;
```

Again, thanks a lot for your help.
