### ISSUE TITLE
multistatement error with UNNEST

### ISSUE THREAD

**Issue by git20190108** [duckdb/duckdb#8374]
### What happens?

UNNEST get wrong result in multistatement

### To Reproduce

```
import duckdb
duckdb.sql('''
set timezone = 'UTC';
SELECT UNNEST([[1, 2, 3], [4, 5]], recursive := True) result
''')

duckdb.sql('''
-- set timezone = 'UTC';
SELECT UNNEST([[1, 2, 3], [4, 5]], recursive := True) result
''')
```

### OS:

centos 

### DuckDB Version:

'0.8.1'

### DuckDB Client:

python

### Full Name:

lotus 

### Affiliation:

xxx

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue

updated reproduction and result differences:
```py
import duckdb

rel = duckdb.sql('''
set timezone = 'UTC';
SELECT UNNEST([[1, 2, 3], [4, 5]], recursive := True) result
''')
rel.show()

rel = duckdb.sql('''
-- set timezone = 'UTC';
SELECT UNNEST([[1, 2, 3], [4, 5]], recursive := True) result
''')
rel.show()
```

```
┌────────┐
│ result │
│ int32  │
├────────┤
│      1 │
│      2 │
│      3 │
└────────┘

┌────────┐
│ result │
│ int32  │
├────────┤
│      1 │
│      2 │
│      3 │
│      4 │
│      5 │
└────────┘
```

**Comment by taniabogatsch** [comment]
I just looked at this issue, which seems to be fixed in the latest DuckDB release. I used a [Google collab notebook](https://colab.google).

![Screenshot 2024-03-18 at 13 19 50](https://github.com/duckdb/duckdb/assets/44262898/73ddeea0-6823-4a25-9f93-5f4e039e45bb)
