### ISSUE TITLE
 json_deserialize_sql could not round-trip parsed results from json_serialize_sql

### ISSUE THREAD

**Issue by min-mwei** [duckdb/duckdb#8381]
### What happens?

json_deserialize_sql seems could not handle certain parsed node types 
==
```
v0.8.2-dev2133 726b6d1566
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D  select json_deserialize_sql(json_serialize_sql('
> SELECT
>     DATE_TRUNC(''month'', p.time) AS cohort_month,
>     COUNT(DISTINCT p.company_id) AS active_users,
>     SUM(p.amount) AS total_purchase_amount
> FROM
>     Purchase p
> JOIN
>     (SELECT
>         user_id,
>         MIN(time) AS first_purchase_time
>      FROM
>         Purchase
>      GROUP BY
>         user_id) fp
> ON
>     p.user_id = fp.user_id
>     AND DATE_TRUNC(''month'', p.time) = DATE_TRUNC(''month'', fp.first_purchase_time)
> GROUP BY
>     DATE_TRUNC(''month'', p.time)
> ORDER BY
>     cohort_month;
> '));
Error: Not implemented Error: Enum value: 'JOIN' not implemented
```

### To Reproduce
1. Start Duckdb CLI
2. Cut-n-paste 
```
 select json_deserialize_sql(json_serialize_sql('
SELECT
    DATE_TRUNC(''month'', p.time) AS cohort_month,
    COUNT(DISTINCT p.company_id) AS active_users,
    SUM(p.amount) AS total_purchase_amount
FROM
    Purchase p
JOIN
    (SELECT
        user_id,
        MIN(time) AS first_purchase_time
     FROM
        Purchase
     GROUP BY
        user_id) fp
ON
    p.user_id = fp.user_id
    AND DATE_TRUNC(''month'', p.time) = DATE_TRUNC(''month'', fp.first_purchase_time)
GROUP BY
    DATE_TRUNC(''month'', p.time)
ORDER BY
    cohort_month;
'));
```

### OS:

Mac OS

### DuckDB Version:

v0.8.2-dev2133 726b6d1566 (private build from source)

### DuckDB Client:

DuckDB CLI

### Full Name:

Min Wei

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by szarnyasg** [comment]
@min-mwei thanks for opening this issue! Could you please turn the query that reproduces the issue into a minimal working example and [format it as code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)?

**Comment by Maxxen** [comment]
This is a regression from 0.8.1, the new generated serialization code produces two fields with tag "type" for JoinRefs, since a JoinRef is both a subclass of TableRef (with a type field) and a base class itself (with a type field). This is probably not the only inheritance chain where this problem occurs and we should add a check for it in the serialization generation code.
