### ISSUE TITLE
epoch(TIMESTAMPTZ) adds in TimeZone offset seconds to result.

### ISSUE THREAD

**Issue by robert-manchester** [duckdb/duckdb#8399]
### What happens?

recent builds as of `v0.8.2-dev2207 accdd3edb9` are adding the timezone offset into the result of `extract('epoch' from xxx)`. For example, `select extract('epoch' from to_timestamp(0));` returns -28800 when `TimeZone = 'US/Pacific'` but should return 0 as it did in v0.8.1 and does in PostgreSQL 15.3.

```
D select extract('epoch' from to_timestamp(0));
┌──────────────────────────────────────────┐
│ main.date_part('epoch', to_timestamp(0)) │
│                  int64                   │
├──────────────────────────────────────────┤
│                                   -28800 │
└──────────────────────────────────────────┘
```

Interestingly, the newly added `epoch_ms(TIMESTAMPTZ)` returns 0 which i believe to be the correct behavior.

```
D select epoch_ms(to_timestamp(0));
┌───────────────────────────┐
│ epoch_ms(to_timestamp(0)) │
│           int64           │
├───────────────────────────┤
│                         0 │
└───────────────────────────┘
```

### To Reproduce

```sql
load icu;
set TimeZone = 'US/Pacific';
select extract('epoch' from to_timestamp(0));
select epoch(to_timestamp(0));
```

### OS:

x86_64 GNU/Linux

### DuckDB Version:

v0.8.2-dev2207

### DuckDB Client:

cli

### Full Name:

robert manchester

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by robert-manchester** [comment]
> ### What happens?
[...]
>  should return 0 as it did in v0.8.1 and does in PostgreSQL 15.3.

v0.8.1 to_timestamp(0) seems to return a TIMESTAMP not a TIMESTAMPTZ as v0.8.2-dev which perhaps why it returns 0 for the epoch. modifying the statement for v0.8.1 so that extract gets a TIMESTAMPTZ eg: `select extract('epoch' from to_timestamp(0) at time zone 'UTC');` returns -28800 in v0.8.1. Thus, v0.8.1 seems to have the same problem extracting the epoch from TIMESTAMPTZ objects when TimeZone is set to anything other than UTC.

**Comment by hawkfish** [comment]
Wow - the code deliberately adds this in. Not sure why. Easy to remove.
