### ISSUE TITLE
ints are converted to strings by GROUP BY if default_collation=NOCASE

### ISSUE THREAD

**Issue by marhar** [duckdb/duckdb#8413]
### What happens?

- Integer values are unexpected  converted to varchar in GROUP BY if default_collation=NOCASE.
- ORDER BY does not convert

Expected Result:
integer values are not converted to varchar by GROUP BY.

Observed Result:
integer values are converted to varchar by GROUP BY.

```
PRAGMA default_collation=NOCASE;
select 1 as x group by x;
┌─────────┐
│    x    │
│ varchar │
├─────────┤
│ 1       │
└─────────┘
```

### To Reproduce

```
.echo on
PRAGMA default_collation=BINARY;
select 1 as x;
select 1 as x order by x;
select 1 as x group by x;
                   
PRAGMA default_collation=NOCASE;
select 1 as x;
select 1 as x order by x;
select 1 as x group by x;   -- x becomes a varchar only on this query
```

### OS:

MacOS

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Mark Harrison

### Affiliation:

TigerEye

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by dioptre** [comment]
This is the same bug for timestamp types and probably others

**Comment by dioptre** [comment]
@marhar did you ever get to the bottom of this?
