### ISSUE TITLE
various timestamp casts and strings are off by 48 hours or more compared to Postgres

### ISSUE THREAD

**Issue by robert-manchester** [duckdb/duckdb#8416]
### What happens?

`'0044-03-13 (BC) 10:33:41+01'::TIMESTAMPTZ` copied out of the unit test file `test_icu_datepart.test`, sans fractional seconds, does not seem to be processed correctly. While the unit test passes, the source of truth disagrees with Postgres outputs. 

The query below should return 0, as it does in Postgres, but the cast adds an additional 48 hours to the timestamp in duckdb. Running the same query using `now()` rather than the BC time string gives the correct result of 0.

```sql
D SELECT date_part('epoch', ts::timestamp) - (date_part('epoch', ts) + date_part('timezone', ts))
> FROM  (select '0044-03-13 (BC) 10:33:41+01'::TIMESTAMPTZ as ts) tbl;
┌────────┐
│  ...   │
│ int64  │
├────────┤
│ 172800 │
└────────┘
```

Additionally, output strings for timestamp(tz) are both off by two days. The input and expected date is 03-13 but the output is 03-15. The output from Postgres shows a string with the correct date. The time part is the same for duckdb and Postgres.
```sql
D SELECT ts::timestamp, ts
> FROM  (select '0044-03-13 (BC) 10:33:41+01'::TIMESTAMPTZ as ts) tbl;
┌──────────────────────────┬────────────────────────────────┐
│  CAST(ts AS TIMESTAMP)   │               ts               │
│        timestamp         │    timestamp with time zone    │
├──────────────────────────┼────────────────────────────────┤
│ 0044-03-15 (BC) 01:40:43 │ 0044-03-15 (BC) 01:40:43-07:52 │
└──────────────────────────┴────────────────────────────────┘
```

As expected, the epoch from the timestamp is off by 48 hours when compared to the Posgres result of -63517990757. However, the epoch from the timestamptz matches the output of Postgres.
```sql
D SELECT date_part('epoch', ts::timestamp), date_part('epoch', ts)
> FROM  (select '0044-03-13 (BC) 10:33:41+01'::TIMESTAMPTZ as ts) tbl;
┌───────────────────────────────────────────┬────────────────────────┐
│ date_part('epoch', CAST(ts AS TIMESTAMP)) │ date_part('epoch', ts) │
│                   int64                   │         int64          │
├───────────────────────────────────────────┼────────────────────────┤
│                              -63517817957 │           -63517962379 │
└───────────────────────────────────────────┴────────────────────────┘
```

Note! The results from the above queries expect a build with PR #8415 which fixes issue #8399 `date_part('epoch', timestamptz) adds tz offset`. I noticed this when looking to fix #8399 earlier and running the unit tests on postgres.

### To Reproduce

The results from the below queries expect a build with PR #8415 which fixes issue #8399 `date_part('epoch', timestamptz) adds tz offset`.

1. duckdb result is 172800 (48 hours), should be 0.
```sql
select date_part('epoch', ts::timestamp) - (date_part('epoch', ts) + date_part('timezone', ts))
from  (select '0044-03-13 (BC) 10:33:41+01'::timestamptz as ts) tbl;
```
2. date for both is `0044-03-15` in duckdb, Postgres and input string are `0044-03-13`.
```sql
select ts::timestamp, ts
from  (select '0044-03-13 (BC) 10:33:41+01'::timestamptz as ts) tbl;
```
3. result for casted timestamp is -63517817957, Postgres is -63517990757. timestamptz values match in Postgres and duckdb.
```sql
select date_part('epoch', ts::timestamp), date_part('epoch', ts)
from  (select '0044-03-13 (BC) 10:33:41+01'::timestamptz as ts) tbl;
```

### OS:

x86_64 GNU/Linux

### DuckDB Version:

v0.8.2-dev

### DuckDB Client:

cli

### Full Name:

robert manchester

### Affiliation:

unaffiliated

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by robert-manchester** [comment]
this doesn't seem restricted to old timestamps. various old timestamps seem to be getting the day wrong.

```sql
select ts from (select '1582-01-01 10:33:41+01'::timestamptz as ts) tbl;
```
```
┌───────────────────────────┐
│            ts             │
│ timestamp with time zone  │
├───────────────────────────┤
│ 1581-12-22 01:40:43-07:52 │
└───────────────────────────┘
```
That should be 1582-01-01 01:40:43

However, one year later is fine.
```sql
select ts from (select '1583-01-01 10:33:41+01'::timestamptz as ts) tbl;
```
```
┌───────────────────────────┐
│            ts             │
│ timestamp with time zone  │
├───────────────────────────┤
│ 1583-01-01 01:40:43-07:52 │
└───────────────────────────┘
```
that looks fine.

Tried various dates below year 1582 and i believe that my sample all were off by some number of days given the input and comparing with postgres.

**Comment by hawkfish** [comment]
Yes, this is because [ICU uses floating point for date representations](https://duckdb.org/2022/01/06/time-zones.html#caveats), and far from the epoch it become rather inaccurate. Given that time zones are only about 100 years old, this is not an issue we intend to deal with. 

We did design the TSTZ support to be implemented via an extension, however, so if you have another library that has the accuracy you need, you could always [build out an alternative implementation](https://duckdb.org/2022/01/06/time-zones.html#separation-of-concerns).

**Comment by robert-manchester** [comment]
I don't think the issue i am seeing relates to floating point.  The [link provided](https://duckdb.org/2022/01/06/time-zones.html#caveats) states that the calendar changes at 1582-10-15 and it is around this date and earlier that I see gaps other than the timezone offset between the naive and original instant. I am not clear why the calendar is required to convert to a naive instant other than to extract the timezone offset.
 My somewhat layperson implementation of icu-timezone.cpp:ICUToNaiveTimestamp::Operation would look as follows:
```c++
struct ICUToNaiveTimestamp : public ICUDateFunc {
        static inline timestamp_t Operation(icu::Calendar *calendar, timestamp_t instant) {
                if (!Timestamp::IsFinite(instant)) {
                        return instant;
                }
                auto micros = SetTime(calendar, instant);
                auto millis = ExtractField(calendar, UCAL_ZONE_OFFSET);
                millis += ExtractField(calendar, UCAL_DST_OFFSET);
                return timestamp_t(instant.value + millis * Interval::MICROS_PER_MSEC);
        }
[...]
}
```
This keeps the naive and original instances within timezone offset seconds and matches what I get from Postgres when extracting the epoch from the naive instance over a wide range of dates. This change brakes some of the unit tests in test_icu_datepart.test but these are all fixed by replacing the failing expected output with the output from Postgres.

**Comment by hawkfish** [comment]
OK sorry if I misunderstood, I'll have another look.  

One thing to bear in mind is that the Gregorian switch is in October 1582, so when you go across it, the built in calendar and ICU will start to differ. The built in binning uses the proleptic Gregorian calendar in UTC (as it is really a way to create human-readable instants), but IIRC ICU changes to the Julian calendar at the switch. (They even have settings to change the switch date if you want to look at later times from non-Catholic countries...)

**Comment by hawkfish** [comment]
(Also, when you report this stuff, please include your time zone? You appear to be GMT+01 right now but I am in `America/Los_Angeles`, and I'm not sure which GMT+01 you are in...)

**Comment by robert-manchester** [comment]
> (Also, when you report this stuff, please include your time zone? You appear to be GMT+01 right now but I am in `America/Los_Angeles`, and I'm not sure which GMT+01 you are in...)

I am also in `America/Los_Angeles`.

**Comment by robert-manchester** [comment]
> (Also, when you report this stuff, please include your time zone? You appear to be GMT+01 right now but I am in `America/Los_Angeles`, and I'm not sure which GMT+01 you are in...)

oh -- your output might differ as i am using a build with your patch from PR #8415

**Comment by hawkfish** [comment]
No I'm working off that. I was just confused by your input strings.

I think the problem is that we parse the date at proleptic Gregorian and don't fix it if we are before the switch. We do this for performance (as they ought to be the same) but I can check I suppose.

**Comment by robert-manchester** [comment]
> No I'm working off that. I was just confused by your input strings.

the input string is from line 19 of test_icu_datepart.test. I just chopped off the fractional second so when running in postgres date_part('epoch', xxx) would return whole numbers.

**Comment by robert-manchester** [comment]
> I think the problem is that we parse the date as proleptic Gregorian and don't fix it if we are before the switch. We do this for performance (as they ought to be the same) but I can check I suppose.

The parsing seemed ok to me. as for the full timestamptz when extracting the epoch it matches what postgres gives. Maybe you're saying given the ICU implementation the date parsing should match and thus the epochs in Postgres and duckdb would then differ and both be correct. Still, regardless of calendar I'd still expect the naive and non-naive(?) instants to differ by timezone offset seconds.

**Comment by hawkfish** [comment]
OK I have the pre-Gregorian parsing working, and quite frankly I think it is now more correct than PG in these extreme cases:

```sql
hawkfish=# select ts::timestamp, ts
hawkfish-# from  (select '0044-03-13 (BC) 10:33:41+01'::timestamptz as ts) tbl;
           ts           |               ts                
------------------------+---------------------------------
 0044-03-13 01:40:43 BC | 0044-03-13 01:40:43-07:52:58 BC
```

Note that PG is off by 7 minutes for some reason, but DuckDB is now round tripping correctly:

```sql
select ts::timestamp, ts
from  (select '0044-03-13 (BC) 10:33:41+01'::timestamptz as ts) tbl;
----
0044-03-13 (BC) 01:33:41	0044-03-13 (BC) 01:33:41-07:52
```

**Comment by hawkfish** [comment]
That took a lot longer than expected, but it seems to have fixed all the strange anomalies. I'm just sad that the test data was supposed to be the Ides of March and is now two days earlier!

I'm wondering if the 2 days was due to the early misunderstandings about leap years. 0044-03-15 (BC) is so close to the Julian epoch that it should have agreed with the proleptic Gregorian calendar again, and two days is a strange delta. A few years of incorrect leap years would explain it.

**Comment by robert-manchester** [comment]
random Q:
would calling [setGregorianChange](https://unicode-org.github.io/icu/userguide/datetime/calendar/)(U_DATE_MIN, ...) allow use of the proleptic gregorian over the date range?

**Comment by hawkfish** [comment]
That's interesting, but honestly this is the sort of issue I only dig into to make sure there isn't a deeper problem. I think the question here is just what PG/the standard expects the calendar system to be in these somewhat pedantic cases. 

Naïve timestamps are problematic for many reasons, one of which is we support non-Gregorian calendars, two of which have 13 months, so it is not possible to encode their date parts as a string written in the Gregorian calendar. The most reliable way to enter arbitrary dates is to use `make_timestamptz`, which just passes the values straight into the setters.

**Comment by robert-manchester** [comment]
i see. the concept of multiple calendars with identical syntax had me pretty confused but i think i've gotten a handle on it...

anyway. I ran your change. looks good for the round trip, the input matches the output, that's great. The 7 min difference you saw with PG goes away when removing the +01 from the end of the string.

My original reason for creating this issue is not resolved. I believe the result of the below query should be zero and not 172800.
```sql
select date_part('epoch', ts::timestamp) - (date_part('epoch', ts) + date_part('timezone', ts))
from  (select '0044-03-13 (BC) 10:33:41+01'::timestamptz as ts) tbl;
```

Additionally, epoch_ms(bigint) doesn't seem to be importing the timestamp correctly.
```sql
select ts::timestamp, ts
from (select epoch_ms(-63518135601 * 1000) at time zone 'UTC' as ts) tbl;
┌──────────────────────────┬────────────────────────────────┐
│  CAST(ts AS TIMESTAMP)   │               ts               │
│        timestamp         │    timestamp with time zone    │
├──────────────────────────┼────────────────────────────────┤
│ 0044-03-11 (BC) 01:33:41 │ 0044-03-11 (BC) 01:33:41-07:52 │
└──────────────────────────┴────────────────────────────────┘
```

it should be
```sql
select ts::timestamp, ts
from (select to_timestamp(-63518135601) as ts) tbl;
┌──────────────────────────┬────────────────────────────────┐
│  CAST(ts AS TIMESTAMP)   │               ts               │
│        timestamp         │    timestamp with time zone    │
├──────────────────────────┼────────────────────────────────┤
│ 0044-03-13 (BC) 01:33:41 │ 0044-03-13 (BC) 01:33:41-07:52 │
└──────────────────────────┴────────────────────────────────┘
```

**Comment by hawkfish** [comment]
Your comment about setting the Gregorian change got me thinking, and I think the real issue is that PG uses the proleptic Gregorian calendar for _all_ dates:

```sql
hawkfish=# select '1582-10-10'::timestamptz;
         timestamptz          
------------------------------
 1582-10-10 00:00:00-07:52:58
(1 row)

hawkfish=# select '1582-10-10'::timestamp;
      timestamp      
---------------------
 1582-10-10 00:00:00
(1 row)
```

The fact that we use different calendars for the two data types is not simply confusing but wrong:

```sql
D select '1582-10-10'::timestamptz;
┌────────────────────────────────────────────────┐
│ CAST('1582-10-10' AS TIMESTAMP WITH TIME ZONE) │
│            timestamp with time zone            │
├────────────────────────────────────────────────┤
│ 1582-10-20 00:00:00-07:52                      │
└────────────────────────────────────────────────┘
D select '1582-10-10'::timestamp;
┌─────────────────────────────────┐
│ CAST('1582-10-10' AS TIMESTAMP) │
│            timestamp            │
├─────────────────────────────────┤
│ 1582-10-10 00:00:00             │
└─────────────────────────────────┘
```

I think your test shows this would account for the 2 day discrepancy? It looks like `ucal_setGregorianChange` will make the check for us and just return an error, which we would ignore.

**Comment by robert-manchester** [comment]
> I think your test shows this would account for the 2 day discrepancy?

yes, the types will only differ by timezone offset seconds.

```sql
D select '1582-10-10'::timestamptz;
┌────────────────────────────────────────────────┐
│ CAST('1582-10-10' AS TIMESTAMP WITH TIME ZONE) │
│            timestamp with time zone            │
├────────────────────────────────────────────────┤
│ 1582-10-10 00:00:00-07:52                      │
└────────────────────────────────────────────────┘
D select '1582-10-10'::timestamp;
┌─────────────────────────────────┐
│ CAST('1582-10-10' AS TIMESTAMP) │
│            timestamp            │
├─────────────────────────────────┤
│ 1582-10-10 00:00:00             │
└─────────────────────────────────┘
```
