### ISSUE TITLE
JSON extension on `rpi` (`armhf`) arch is not loaded

### ISSUE THREAD

**Issue by nfx** [duckdb/duckdb#8419]
### What happens?

extension install apparently picks the wrong architecture for the zip file.

### To Reproduce

- install cli with `wget https://github.com/duckdb/duckdb/releases/download/v0.8.1/duckdb_cli-linux-rpi.zip`, unzip it
- `./duckdb`
- `INSTALL json;` fails with

```
D INSTALL json;
Error: HTTP Error: Failed to download extension "json" at URL "http://extensions.duckdb.org/v0.8.1/linux_i686_gcc4/json.duckdb_extension.gz"
Extension "json" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```

e.g. `i686` instead of `rpi`. the following URLs are not accessible either:

-  http://extensions.duckdb.org/v0.8.1/linux_rpi_gcc4/json.duckdb_extension.gz
-  http://extensions.duckdb.org/v0.8.1/linux_rpi/json.duckdb_extension.gz

### OS:

Raspbian GNU/Linux 11 (bullseye)

### DuckDB Version:

0.8.1

### DuckDB Client:

cli

### Full Name:

Serge Smertin

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by nfx** [comment]
compiling it from sources is always involved :) 
https://github.com/duckdb/duckdb/issues/5279

**Comment by szarnyasg** [comment]
We do not ship extensions built for Raspberry Pi at the moment, so this is expected behaviour.
