### ISSUE TITLE
Incorrect counts with COUNT(distinct) FILTER

### ISSUE THREAD

**Issue by orf** [duckdb/duckdb#8424]
### What happens?

I have the following query:

```sql
select count(distinct project_name) FILTER (where suffix(path, '.pyi') OR suffix(path, 'py.typed')) AS has_any_type,
    count(distinct project_name) FILTER (where suffix(path, 'py.typed')) AS typed,
    count(distinct project_name) FILTER (where suffix(path, '.pyi')) AS py_i,
from 'dataset/*.parquet';
```

This returns:

```csv
has_any_type,typed,py_i
15986,14618,3926
```

This cannot be correct, as `has_any_type` should be equal to `typed + py_i`

Removing `DISTINCT ` from the query results in the correct outputs that sum together:

```sql
has_any_type,typed,py_i
16477553,1250709,15226844
```

### To Reproduce

It's 4am in the morning and it appears all my numbers are incorrect, so I'll investigate more tomorrow and try to create a reproduction then. I wanted to add this now in case it was obvious what the mistake was to anyone else.

### OS:

MacOS (also repo on Linux)

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

CLI

### Full Name:

Tom Forbes

### Affiliation:

Myself?

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by StLeoX** [comment]
might be related with #3678

**Comment by orf** [comment]
I'm a sleep deprived idiot. The query above is fine because there may be projects where _both_ suffixes match, so the distinct count should always be equal to or lower than the two other distinct counts.

Apologies for wasting your time!
