### ISSUE TITLE
filtering on predictate involving RANDOM() yields unexpected results

### ISSUE THREAD

**Issue by shuggiefisher** [duckdb/duckdb#8441]
### What happens?

Filtering on a predicate derived from the RANDOM() function occasionally yields results where the value is == false.

I'm seeing this behaviour in python library and OS X CLI.  I was implementing weighted random sampling, so am not using the built in SAMPLE functionality.

### To Reproduce

Reproducing on the terminal.

It involves the RANDOM() function, so you may need to run it a couple of times, but for me in most cases this yields results where the column `random_sampled` == false
```
echo "
WITH samples AS (
        SELECT
                n,
                CAST(FLOOR(RANDOM()*n) AS INT) AS n_sample
        FROM (
                VALUES (1), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (2), (20), (100)) AS t(n)
),

test AS (
        SELECT
                n,
                n_sample,
                n_sample >= 1 AS random_sampled
        FROM samples
)

SELECT
        *
FROM test
WHERE random_sampled
" | ./duckdb
┌───────┬──────────┬────────────────┐
│   n   │ n_sample │ random_sampled │
│ int32 │  int32   │    boolean     │
├───────┼──────────┼────────────────┤
│     2 │        1 │ true           │
│     2 │        0 │ false          │
│     2 │        1 │ true           │
│     2 │        0 │ false          │
│     2 │        0 │ false          │
│     2 │        0 │ false          │
│     2 │        1 │ true           │
│     2 │        1 │ true           │
│     2 │        1 │ true           │
│     2 │        0 │ false          │
│    20 │       15 │ true           │
│   100 │       62 │ true           │
├───────┴──────────┴────────────────┤
│ 12 rows                 3 columns │
└───────────────────────────────────┘

### OS:

os x arm64

### DuckDB Version:

0.8.1

### DuckDB Client:

python, CLI

### Full Name:

Robert Kyle

### Affiliation:

Personal - no affiliation

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
The problem is that random() should return a number between 0 and 1, max 0.9999999999..

Throwing a floor on this becomes 0.
Only when random would return 1 or higher would the expression `n_sample >= 1`

Which shouldnt happen

**Comment by shuggiefisher** [comment]
The last step in the query is filtering on `WHERE random_sampled`, yet the
results contain rows where `random_sampled == false`.

**Comment by robert-manchester** [comment]
to a layperson, it looks like duckdb treats random() as idempotent when it is not. Here's a test that reproduces the issue:

```sql
select setseed(0.27746);
select rnd, rnd < 0.5 from (select random()) as t(rnd) where rnd < 0.5;
```
|        rnd         | (rnd < 0.5) |
|--------------------|-------------|
| 0.9843676064629108 | false       |


so that doesn't look correct. rnd is larger than 0.5 so the test fails but for some reason it is evaluated as true in the where clause.

lets take a look at the first two random numbers returned after setseeed(0.27746)
```sql
select setseed(0.27746);
select random(), random();
```
|      random()      |      random()      |
|--------------------|--------------------|
| 0.3864976782351732 | 0.9843676064629108 |

So the first call to random() is 0.386... which is less than < 0.5, and the second call gives us 0.984... which is larger. In the output of the 1st test appears to use 0.984... and the where clause is using 0.386...


the query plan below shows two calls to random()
```sql
explain select rnd, rnd < 0.5 from (select random()) as t(rnd) where rnd < 0.5;
```
```
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            rnd            │
│        (rnd < 0.5)        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          random()         │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│      (random() < 0.5)     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         DUMMY_SCAN        │
└───────────────────────────┘                             
```

**Comment by Reminiscent** [comment]
Hi, I want to fix this problem.
