### ISSUE TITLE
Force install does not overwrite file on windows

### ISSUE THREAD

**Issue by jeffmotherduck** [duckdb/duckdb#8451]
### What happens?

Force installing an extension (for example postgres) on windows does overwrite the existing copy of the extension with error: "IO Error: Could not move file: cannot create a file when that file already exists".

### To Reproduce

```
force install postgres;
force install postgres;
```

### OS:

Windows

### DuckDB Version:

v0.8.1

### DuckDB Client:

CLI

### Full Name:

Jeff Huang

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
This has been fixed in https://github.com/duckdb/duckdb/pull/8732
