### ISSUE TITLE
Compiling requires C++17

### ISSUE THREAD

**Issue by teaguesterling** [duckdb/duckdb#8486]
### What happens?

Trying to compile the R package for duckdb v0.8.1 fails with "Error: C++17 standard requested but CXX17 is not defined" yet it's stated on the duckdb.org homepage that "For building, all that is required to build DuckDB is a working C++11 compiler."

In my particular case, I have access to a newer compiler that I've used to compiler R and the duckdb package but cannot use it because the json extension fails to load in that version due to another unrelated issue (due to libm version issues) and cannot get the duckdb package to build with json built-in (another unrelated issue).

### To Reproduce

Attempt to install via install.packages('duckdb') in an R installation without CXX17 defined in ``R CMD config CXX17`. In this case I'm using R 4.2.1 compiled with gcc 6.3.0 which only supports C++14.

### OS:

CentOS 7

### DuckDB Version:

0.8.1

### DuckDB Client:

R

### Full Name:

Teague Sterling

### Affiliation:

23andMe

### Have you tried this on the latest `master` branch?

I have tested with a release build (and could not test with a master build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Could you share your build logs?
I'm very curious what causes this error because we build DuckDB with c++11 and I've never seen this problem.

**Comment by teaguesterling** [comment]
This file seems to be the cause: https://github.com/duckdb/duckdb/blob/master/tools/rpkg/src/Makevars.in

**Comment by carlopi** [comment]
git says I am to blame for introducing c++17 as requirement in https://github.com/duckdb/duckdb/pull/6022.
I think code should compile fine with c++11, you can try changing it there and see whether it works, most probably it will.

Open to better solutions.

**Comment by teaguesterling** [comment]
Thanks! I will give this a shot over the weekend when I can build the repo instead of cran. If it works I'll open a pull request.

**Comment by teaguesterling** [comment]
The change that @carlopi mentioned appears to work, or at least gets around the specific issue that was arising. I am still unable to get the package to compile. That seems to be from a different issue related to duplicate definitions of zstd functions. Because of that I have been unable to confirm the fix, however.

**Comment by teaguesterling** [comment]
This did resolve the issue of C++17 requirements. Iwas able to build with multiple extensions by default. 

However, the R package build instructions appear to be incorrect (this should be a separate issue,  which I will open). I was receiving an error about duplicate definitions for zstd functions and noticed it was attempting to compile with imports in the R package destination directory from .libPaths(). It worked fine by having it install to a custom temporary library destination not in .libPaths(), but that does not seem to be the intended behavior.

**Comment by carlopi** [comment]
I think I would solve both issue on the tools/rpkg/README.md side, if you want to contribute a change it's welcome.

**Comment by hannes** [comment]
C++17 is now the default for R packages and CRAN actually asked us to remove the previous C++11 definition. So this is not really a DuckDB issue.

**Comment by teaguesterling** [comment]
I'm happy to update the Readme.

It looks like CRAN provides guidance for continuing to support C++11 here: https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/#note-regarding-systemrequirements-c11

If there's desire to continue C++11 support, easiest path may be to remove the specification and suggest specifing it as an environmental variable at build time. I'm happy to continue exploring this since multi user systems commonly have older build systems and backwards compatibility is (sadly) necessary.
