### ISSUE TITLE
export database can save views out of order breaking import.

### ISSUE THREAD

**Issue by ghost** [duckdb/duckdb#8496]
### What happens?

views which reference other views can be saved out of order when the database is exported which prevents import database from succeeding as seen in the testcase below.

```sh
duckdb t.ddb -c 'create view b as select 1; create view a as select * from b;'
duckdb t.ddb -c "export database 'test'"
duckdb -c "import database 'test'"
```
```
Error: Catalog Error: Table with name b does not exist!
Did you mean "temp.information_schema.tables"?
```

looking at the generated schema.sql can see the views were reordered.
```sh
cat test/schema.sql
```
```
create view a as select * from b;
;
create view b as select 1
;
```

### To Reproduce

```sh
duckdb t.ddb -c 'create view b as select 1; create view a as select * from b;'
duckdb t.ddb -c "export database 'test'"
duckdb -c "import database 'test'"
```

### OS:

Ubuntu 22.04.3 LTS

### DuckDB Version:

v0.8.2-dev2495

### DuckDB Client:

cli

### Full Name:

robert manchester

### Affiliation:

unaffiliated

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This was tricky to reproduce. It seems it only occurs in version 0.8.2-dev and on Ubuntu (but it can be both Arm64 and x86).

I could not reproduce it on MacOS (with Apple Silicon) with versions 0.8.1 and 0.8.2-dev, and it also did not occur on Ubuntu / Intel with DuckDB version 0.8.1.

It can be reproduced on MacOS with an Ubuntu 22.04 Docker container:

```
$ docker run -it ubuntu:22.04 /bin/bash
```
```
% apt update && apt install -y git ninja-build cmake g++
% https://github.com/duckdb/duckdb
% cd duckdb
% GEN=ninja make
% cd build/release
# run the reproduction script
```

**Comment by robert-manchester** [comment]
FWIW: `v0.8.1 6536a77232` on `Raspbian GNU/Linux 11 (bullseye)` reproduced for me using binary from duckdb.org.
also able to reproduce `v0.8.1` on `Ubuntu 22.04.3 LTS` using the binary from nix -- downloaded the amd64 binary from duckdb.org and was unable to reproduce for `v0.8.1 6536a77232`.

**Comment by szarnyasg** [comment]
Interesting. Maybe this has something to do with the Arm64 architecture's more relaxed memory model?

**Comment by robert-manchester** [comment]
> Interesting. Maybe this has something to do with the Arm64 architecture's more relaxed memory model?

i am not sure it is that nefarious. if i am reading the code correctly it looks like the underling data structure is an unordered_map and looking various builds they use different compilers and stl implementations. eg:
```console
rdevm@chatterbox> for bin in duckdb_amd64_official duckdb_ras_pi_official duckdb_nix; readelf -p .comment $bin
String dump of section '.comment':
  [     0]  GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609


String dump of section '.comment':
  [     0]  GCC: (crosstool-NG crosstool-ng-1.22.0-88-g8460611) 4.9.3


String dump of section '.comment':
  [     0]  GCC: (GNU) 12.3.0
```

also. i am able to reproduce using the amd64 official by just using a slightly different set of steps.
```sh
duckdb <<<"create view b as select 1;create view a as select * from b; export database 'out'"
duckdb <<<"import database 'out'"
```
```
Error: near line 1: Catalog Error: Table with name b does not exist!
Did you mean "temp.information_schema.tables"?
```

however, those steps will not reproduce with the rasp-pi official or the nix build.


the code to write schema.sql is here:
physical_export.cpp:SourceResultType PhysicalExport::GetData
and there is already code which orders macros by timestamp, according to the comment. doing the same for views would fix the bug but perhaps is not correct either.

the current duckdb implementation I can create a view with a dependency on another view, view_A, then delete view_A, create another view named view_A and everything seems to work just fine after that. ordering by timestamps would break that.

**Comment by carlopi** [comment]
unordered_maps are not stable, so insertion order (or any order for that matter) is likely not preserved, and at best implementation dependent.

**Comment by michael-simons** [comment]
Reproducible with the schema [here](https://github.com/michael-simons/biking3/tree/main/schema).

Also 0.8.1, on macOS Arm.

**Comment by kmatt** [comment]
Still an issue on v0.9.1 Ubuntu 22.06 x64:

```sql
CREATE OR REPLACE VIEW three AS
SELECT ... 
FROM b
JOIN a ON ... ;

CREATE OR REPLACE VIEW two ... ;

CREATE OR REPLACE VIEW one ... ;
```

**Comment by kwando** [comment]
I've encountered this on my M1 MacBook a few times, it does _not_ happen all the time though which is a bit strange.

**Comment by suiluj** [comment]
same problem with macbook air m2

**Comment by carlopi** [comment]
> same problem with macbook air m2

@suiluj: Could you share (in a separate issue) a reproducer using duckdb stable (1.1.3) or a somewhat recent nightly build ?

Thanks!

**Comment by suiluj** [comment]
@carlopi I created a reproducer example and by doing that found the reason for this bug I guess:

The `export database` creates sql instructions in `schema.sql` which are sorted alphabetically instead of original creation order.

Here you can find my reproducer bug issue:

https://github.com/duckdb/duckdb/issues/15353
