### ISSUE TITLE
st_read will read the first row as data for some excel

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#8509]
### What happens?

yesterday, I tested a 4 rows excel for test, it's OK.
but today, I read a 100,000rows excel, it read the first row as data, like this:
<img width="1004" alt="image" src="https://github.com/duckdb/duckdb/assets/25274931/bc6802db-ebd0-4101-acc2-c5cb0de5fd31">

### To Reproduce

```
SELECT * FROM st_read('/Users/mac/Downloads/records6.30.xlsx',  layer='product', open_options=['OGR_XLSX_HEADERS=FORCE'])
```

### OS:

mac13

### DuckDB Version:

0.8.1

### DuckDB Client:

cli

### Full Name:

wang cz

### Affiliation:

Linezone

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
do you load the extension?
```
SELECT * FROM st_read();
Run Time (s): real 0.004 user 0.000000 sys 0.001624
Error: Catalog Error: Table Function with name st_read does not exist!
Did you mean "read_csv"?
LINE 1: SELECT * FROM st_read();
                      ^
```
