### ISSUE TITLE
cli feature request: enable saving in duckdb format, even when you have not specified the filename

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb#8518]
Sometimes I open the cli, and do some test operations, without specifying a filename, because they are done without a defined goal.

Some of these times interesting and unexpected things come up though, and I would like to save in duckdb format in one command.

Currently I can export to SQL format and then import back to a duckdb file. I wish it were possible to have the duckdb format in the "EXPORT" command.

Thank you

_Originally posted by @aborruso in https://github.com/duckdb/duckdb/discussions/8508_

**Comment by szarnyasg** [comment]
We do not plan to support this as of now.
