### ISSUE TITLE
Inconsistent Date Partition Handling Between DuckDB and PostgreSQL Affecting Dagster Rematerialization

### ISSUE THREAD

**Issue by Neil2893** [duckdb/duckdb#8529]
### What happens?

When using Dagster in conjunction with DuckDB, a bug has been identified that leads to inconsistent partition handling in DuckDB compared to PostgreSQL. This issue affects the proper rematerialization of partitions within Dagster workflows.

### To Reproduce

The bug is observed in the way DuckDB handles date partitions in comparison to PostgreSQL. Consider the following scenario with a sample table structure:

**DuckDB Table**:

```sql
CREATE TABLE duckdb.main.test (
    "date" DATE,
    value VARCHAR
);
```
**PostgreSQL Table**:
```sql
CREATE TABLE public.test (
    "date" date NULL,
    value varchar NULL
);
```

**Sample Data**:
|    date    | value |
|------------|-------|
| 2023-08-01 |   1   |
| 2023-08-02 |   2   |
| 2023-08-03 |   3   |
| 2023-08-04 |   4   |
| 2023-08-05 |   5   |
| 2023-08-06 |   6   |
| 2023-08-07 |   7   |

For the same query that retrieves records within a specific date range:

**Query**:
```sql
SELECT * FROM test WHERE date >= '2023-08-05 00:00:00' AND date < '2023-08-06 00:00:00';
```

**PostgreSQL Result(Expected)**:

|    date    | value |
|------------|-------|
| 2023-08-05 |   5   |

**DuckDB Result(Undesired)**:

|    date    | value |
|------------|-------|
| 2023-08-06 |   6   |

**Impact**:

This inconsistency in date partition handling between DuckDB and PostgreSQL has a direct impact on the ability of Dagster to properly rematerialize partitions. As a result, when attempting to rematerialize partitions within Dagster workflows that involve DuckDB, incorrect data may be deleted or retained, leading to data integrity issues and incorrect analytical results.

**Additional Info:**

Interestingly, when creating a similar table structure in PostgreSQL with a datestr column of type varchar, the same query returns the following result:

PostgreSQL Table:
```sql
CREATE TABLE public.test2 (
    datestr varchar NULL,
    value varchar NULL
);
```

**Query:**
```sql
SELECT * FROM test2 WHERE datestr >= '2023-08-05 00:00:00' AND datestr < '2023-08-06 00:00:00';
```

**Result**:
|    datestr    | value |
|--------------|-------|
|  2023-08-06  |   6   |

In the above scenario where `datestr` column is of type `varchar`, the comparison is being done as string comparison, which makes sense.

### OS:

x64

### DuckDB Version:

0.81

### DuckDB Client:

Python/JDBC(Dbeaver)

### Full Name:

Neil

### Affiliation:

None

### Have you tried this on the latest `master` branch?

I have tested with a release build (and could not test with a master build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] Yes, I have

**Comment by hawkfish** [comment]
I suspect the `BETWEEN` operator got messed up. IIRC there was a change to it recently.

**Comment by hawkfish** [comment]
Looks like it is a casting problem, not a date problem. The plan shows a string compare.

```
┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   (CAST(date AS VARCHAR)  │
│ BETWEEN '2023-08-05 0...  │
│ AND '2023-08-06 00:00:00')│
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         issue8529         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            date           │
│           value           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└───────────────────────────┘                             
```

**Comment by hawkfish** [comment]
Adding casts produces the correct result:

```sql
SELECT * 
FROM issue8529 
WHERE date >= '2023-08-05 00:00:00'::TIMESTAMP 
  AND date < '2023-08-06 00:00:00'::TIMESTAMP;
```

**Comment by hawkfish** [comment]
It's not `BETWEEN` - ordinary comparisons are not cast either:

```sql
SELECT * 
FROM issue8529 
WHERE date >= '2023-08-05 00:00:00';
```

produces

|    date    | value |
|------------|-------|
| 2023-08-06 | 6     |
| 2023-08-07 | 7     |

with a plan of

```
┌───────────────────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ (CAST(date AS VARCHAR) >= │
│   '2023-08-05 00:00:00')  │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         issue8529         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            date           │
│           value           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
└───────────────────────────┘                             
```

**Comment by hawkfish** [comment]
In fact the real problem is that we type strings to early:

Postgres:
```sql
hawkfish=# select pg_typeof('2023-08-05 00:00:00') as d;
    d    
---------
 unknown
(1 row)

hawkfish=# select pg_typeof('fnord') as d;
    d    
---------
 unknown
(1 row)
```

DuckDB:
```sql
D select pg_typeof('2023-08-05 00:00:00') as d;
```

|    d    |
|---------|
| varchar |
