### ISSUE TITLE
st_read excel the first row as data 

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#8531]
### What happens?

I have two excel, use st_read, one is OK, another read the first row as data rather than header.
Even I copy these sheets to 1 excel, also one is OK, another wrong like this:
```
SELECT * FROM st_read('/Users/mac/Downloads/output.xlsx',  layer='output2', open_options=ARRAY['OGR_XLSX_HEADERS=FORCE']);
SELECT * FROM st_read('/Users/mac/Downloads/output.xlsx',  layer='output3', open_options=ARRAY['OGR_XLSX_HEADERS=FORCE'])

```
sheet2:
<img width="701" alt="image" src="https://github.com/duckdb/duckdb/assets/25274931/0ed53247-e156-4db5-9f90-81497916783a">

sheet3:
<img width="708" alt="image" src="https://github.com/duckdb/duckdb/assets/25274931/14ecaaca-dbe0-40f4-9d78-53ccf5cef01f">

### To Reproduce

[output.xlsx](https://github.com/duckdb/duckdb/files/12311394/output.xlsx)

### OS:

mac13

### DuckDB Version:

0.8.1

### DuckDB Client:

java

### Full Name:

wang cz

### Affiliation:

Linezone

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
https://duckdb.org/docs/guides/import/excel_import

**Comment by Tishj** [comment]
^
> Set those options in an environment variable prior to executing the DuckDB SQL statement

**Comment by wonb168** [comment]
> ^
> 
> > Set those options in an environment variable prior to executing the DuckDB SQL statement

but，how to set in mac m1？
I tested ` export OGR_XLSX_HEADERS=FORCE`
but no effect！

**Comment by l1t1** [comment]
if change output2 cell B2 with 123, it is read right as expect

**Comment by davidjbrennan** [comment]
Start duckdb by entering

`OGR_XLSX_HEADERS=FORCE duckdb`

on the command line and you'll find the environment variable will then be in effect.

**Comment by wonb168** [comment]
> Start duckdb by entering
> 
> `OGR_XLSX_HEADERS=FORCE duckdb`
> 
> on the command line and you'll find the environment variable will then be in effect.

but，I not the cli mode，I used it in dbeaver directly，how to set？

**Comment by davidjbrennan** [comment]
Try launching dbeaver from the command line:

`OGR_XLSX_HEADERS=FORCE /Applications/DBeaver.app/Contents/MacOS/dbeaver`

You could also write a little shell script which has the above command and then double-click it from Finder.

It's far from ideal to rely on environment variables to set these options for st_read().  I would love to be able to set them via the "open_options" of the st_read() function.

**Comment by l1t1** [comment]
[wonb168](https://github.com/wonb168) you can post an issue here https://github.com/duckdblabs/duckdb_spatial

**Comment by wonb168** [comment]
> if change output2 cell B2 with 123, it is read right as expect

yes, but why? where differrent in cell B2?

**Comment by wonb168** [comment]
> SELECT * FROM st_read('output.xlsx',  layer='output2', open_options=ARRAY['OGR_XLSX_HEADERS=FORCE']);

SELECT * FROM st_read('output.xlsx',  layer='output2', open_options=ARRAY['OGR_XLSX_HEADERS=FORCE']);

> Try launching dbeaver from the command line:
> 
> `OGR_XLSX_HEADERS=FORCE /Applications/DBeaver.app/Contents/MacOS/dbeaver`
> 
> You could also write a little shell script which has the above command and then double-click it from Finder.
> 
> It's far from ideal to rely on environment variables to set these options for st_read(). I would love to be able to set them via the "open_options" of the st_read() function.

I used open_options, but no effect, how you to use?

```
SELECT * FROM st_read('output.xlsx',  layer='output2', open_options=ARRAY['OGR_XLSX_HEADERS=FORCE']);
```

**Comment by l1t1** [comment]
if data are all varchar type, then the header line will be treat as  the first data row

**Comment by wonb168** [comment]
> if data are all varchar type, then the header line will be treat as the first data row

I think this is a bug, either treat the first row as header default, or can set header by user

**Comment by Maxxen** [comment]
I've made fix in https://github.com/duckdblabs/duckdb_spatial/pull/114 so that you can choose to force reading the first row as header or not by passing an option from within duckdb. This works with the excel file provided.

![image](https://github.com/duckdb/duckdb/assets/1337636/bd86050b-d915-4358-95ac-599f547d933a)

Note that while this is now merged it is __not part of the nightly builds distributed by duckdb__ yet. We may do an update in a week or so, otherwise it will be present in duckdb 0.9.0 which is scheduled for September.

**Comment by wonb168** [comment]
> I've made fix in https://github.com/duckdblabs/duckdb_spatial/pull/114 so that you can choose to force reading the first row as header or not by passing an option from within duckdb. This works with the excel file provided.
> 
> ![image](https://github.com/duckdb/duckdb/assets/1337636/bd86050b-d915-4358-95ac-599f547d933a)
> 
> Note that while this is now merged it is __not part of the nightly builds distributed by duckdb__ yet. We may do an update in a week or so, otherwise it will be present in duckdb 0.9.0 which is scheduled for September.

first sheet is Ok, problem is the second sheet, please test sheet output1,openoptions not Work!

**Comment by Maxxen** [comment]
<img width="910" alt="image" src="https://github.com/duckdb/duckdb/assets/1337636/3cc28679-01d7-4533-8b82-e8f3038fbef1">

Both sheets in the file uploaded in this thread works. But to clarify, this is not released yet, unless you build the spatial extension from source on the latest commit you won't see these changes yet.

**Comment by wonb168** [comment]
> <img width="910" alt="image" src="https://github.com/duckdb/duckdb/assets/1337636/3cc28679-01d7-4533-8b82-e8f3038fbef1">
> 
> Both sheets in the file uploaded in this thread works. But to clarify, this is not released yet, unless you build the spatial extension from source on the latest commit you won't see these changes yet.

You are wrong,first image is error. Can not read ID for header, and all title became Field1...4

**Comment by l1t1** [comment]
maybe we should navigate to the source code of st_read()

**Comment by Maxxen** [comment]
I don't understand what the behaviour you want is. By default, it will guess, but as I showed above you explicitly disable reading headers by passing `open_options=['HEADERS=DISABLE']);`, or also explicitly force reading headers by passing `open_options=['HEADERS=FORCE'];` like below.

<img width="916" alt="image" src="https://github.com/duckdb/duckdb/assets/1337636/6ab34c4d-5352-4f83-9967-80df00b4877a">

**Comment by l1t1** [comment]
this 4 sql are all right.

**Comment by wonb168** [comment]
> this 4 sql are all right. 

![1691888088720.jpg](https://github.com/duckdb/duckdb/assets/25274931/7aea96af-4233-4df8-ab61-3be4ae838ebf)

but，even I set force, output is also wrong.

**Comment by l1t1** [comment]
Maxxen says But to clarify, this is not released yet, unless you build the spatial extension from source on the latest commit you won't see these changes yet. 
I think you can except it works in version 0.9

**Comment by pramod-janardhana** [comment]
Hi, I'm trying the "**Excel import**" and I'm facing the same issue. 
The scenario is "if the sheet contains only string type values, and the sheet is not the first sheet of the Excel" then **st_read()** is not treating the first row as the column header even though "**HEADERS=FORCE**" is provided in the **open_options**

Excel:
![image](https://github.com/duckdb/duckdb/assets/43513968/3a49d332-ee98-4eb4-957c-d5aab7173fb6)

DuckDB output:
![image](https://github.com/duckdb/duckdb/assets/43513968/a714b395-45f1-4749-af17-552c2ed3b4f9)

My environment:
OS - macOS 13
Chip: M2
DuckDB version: v0.10.0

**Comment by joegood** [comment]
I'm getting the same issue in v0.10.0.  I have 4 sheets in my XLSX file.  On the first three sheets, the headers are detected just fine using HEADERS=FORCE.  On the fourth sheet, it resorts to "Field1" and includes the header as a data row.  Nothing is different between the calls other than changing the sheet name.

**Comment by ThomasRolfsnes-EP** [comment]
Hi! Experiencing the exact same issue. Tried to read the 5th sheet in an xlsx file, HEADERS=FORCE had no effect. Moved the exact same sheet to the second position, and it worked.

So there seems to be some weird dependency on sheet order here.

**Comment by vellotis** [comment]
### FYI: this feature (HEADERS=[AUTO/FORCE/DISABLE]) has been non-existent since v0.9.2

I found out this feature was considered a hack and was removed by https://github.com/Maxxen/duckdb_spatial/commit/5f425a29cb1f642bb7b08f75720da600c58d24ef#diff-6031d5f3ae874a560e3ed8640150117d71185c0de022a8ad2314be57ce3fd78aL190

**Comment by iligid** [comment]
This error is still reproducible with duckdb==1.1.3 and a simple excel sheet with two sheets.
On the first sheet st_read correctly interprets the first row as column names, for the second one it ignores open_options=['HEADERS=FORCE'] and interprets all rows as data.

**Comment by ChandruRangan** [comment]
empty row handle or skip empty rows in st_read duckdb  i got errrorduckdb: Error occurred while executing query CREATE TABLE CT_ImportTempTable_8626339410070326339 AS SELECT * FROM ST_READ('\temp\06eb5374-36e4-4675-8069-7b1a8b49ab16_1.6Lakh_rows\1.6Lakh_rows.xlsx', layer='1.5L',
          open_options=["FIELD_TYPES=STRING ", "HEADERS=FORCE"], allowed_drivers=["XLSX"])

**Comment by DarkTHor55** [comment]
Anyone find any solution for it 
i am facing same issue
