### ISSUE TITLE
Node.js binding on Windows doesn't seem to release a file handle

### ISSUE THREAD

**Issue by kuriyosh** [duckdb/duckdb#8541]
### What happens?

I connect to a same duckDB file multiple times with Node.js binding on Windows. 
The second connection always fails due to the following error. It can be reproduced even if I connect in READONLY mode.

```
[Error: IO Error: Cannot open file "test.db": The process cannot access the file because it is being used by another process.
] {
   errno: -1,
   code: 'DUCKDB_NODEJS_ERROR',
   errorType: 'IO'
}
```

I know a similar issue has been found in DuckDB R package. `Database.close()` method of Node.js binding has no option which equivalent to the `SHUTDOWN=true` option and cannot be resolved by the solution of this issue.

https://github.com/duckdb/duckdb/issues/5481

### To Reproduce

It occurs when the following program is executed with Node.js on windows.

```js
var duckdb = require("duckdb");

const create = (dbPath) =>
  new Promise((resolve, reject) => {
    const db = new duckdb.Database(dbPath, 2, (err) => {
      if (err) reject(err);
      resolve(db);
    });
  });

const close = (db) =>
  new Promise((resolve, reject) => {
    db.close((err) => {
      if (err) reject(err);
      resolve();
    });
  });

(async () => {
  // first connection
  var db1 = await create("test.db");
  var con1 = db1.connect();
  console.log(con1);
  await close(db1);

  // second connection
  var db2 = await create("test.db");
  var con2 = db2.connect();
  console.log(con2);
  await close(db2);
})();
```

### OS:

Windows Server 2019 (Version 1809 OS Build 17763.3046) AMD64

### DuckDB Version:

v0.8.1, v0.8.2-dev2700

### DuckDB Client:

Node.js binding

### Full Name:

Yoshiki Kurihara

### Affiliation:

Yuimedi. inc

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by kuriyosh** [comment]
I misunderstood the AccessMode argument. There is actually no problem if I specify `OPEN_READONLY`.

```js
const create = (dbPath) =>
  new Promise((resolve, reject) => {
    const db = new duckdb.Database(dbPath, duckdb.OPEN_READONLY, (err) => {
      if (err) reject(err);
      resolve(db);
    });
  });
```

However, the problem still occurs when `OPEN_READWRITE` is specified.

Currently, I avoid this problem by passing the processing using DuckDB Node.js binding to child_process and killing child_process as soon as the read/write connection is disconnected. But this workaround is complicated because it always needs to go through the child process when accessing DuckDB.

**Comment by eskrm** [comment]
Hi @kuriyosh. I see the same behavior on my mac, as well as linux containers running on my mac and in AWS. I created a similar program that reproduces it here: https://github.com/eskrm/troubleshoot-duckdb (note that it assumes lsof is on the path). The file handles remains open for ~7 seconds after close on my machine, though, in more complex programs I've seen it take 30+ minutes. Adding an explicit gc after close does resolve the issue in my example program, but not the more complex programs.
