### ISSUE TITLE
read_csv can't load chinese

### ISSUE THREAD

**Issue by Lee7goal** [duckdb/duckdb#8544]
### What happens?

I use 
duckdb.read_csv('sz000002')
to load csv file, but except with:
    df = duckdb.read_csv('sz000002.csv', encoding='gbk')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.InvalidInputException: Invalid Input Error: Error in file "sz000002.csv" at line 1 in column "0": Invalid unicode (byte sequence mismatch) detected in CSV file. Parser options:
  file=sz000002.csv
  delimiter=',' (auto detected)
  quote='"' (auto detected)
  escape='' (auto detected)
  header=0 (auto detected)
  sample_size=20480
  ignore_errors=0
  all_varchar=0

Process finished with exit code 1
i use the encoding='gbk' and encoding='utf-8', every encoding is wrong
so why?

### To Reproduce

just no load, the query is ok

### OS:

x64

### DuckDB Version:

0.8.1

### DuckDB Client:

python

### Full Name:

Qigao Li

### Affiliation:

csv

### Have you tried this on the latest `master` branch?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
DuckDB only supports files written using utf-8, which encoding is your file in?

**Comment by Lee7goal** [comment]
gbk

**Comment by Mause** [comment]
Then this is expected behavior. You'll need to convert your file to utf-8 before DuckDB will read it
