### ISSUE TITLE
POSITIONAL JOIN behaves slower than expected for sequential table scans

### ISSUE THREAD

**Issue by danz68** [duckdb/duckdb#8553]
### What happens?

POSITIONAL JOIN behaves slower than expected for sequential table scans, a singleton select joining on rowid being a way faster alternative.

### To Reproduce

I have a 6 mil table (22 columns) imported in a duckdb database. I made another table which contains only one column from the original table, just to check the positional join functionality.

The following two statements will retrieve the same result:

--statement1
select TABLE1.\*, TABLE2.\* from TABLE1 positional join TABLE2;
--alternative
select * from TABLE1 positional join TABLE2;

--statement2
select TABLE1.\*, select (COLUMN_X from TABLE2 where TABLE1.rowid=TABLE2.rowid) from TABLE1;
--alternative
select TABLE1.\*, TABLE2 .COLUMN_X from TABLE1 JOIN TABLE2 on TABLE2.rowid=TABLE1.rowid;

but statement2 is way faster than statement 1.

profiling them
statement1: 1.67s, statement2: 0.62s (2.69x)

For some kind of reason I thought that the difference would come from fetching top/bottom data so I decided to change a bit the statements, to force a full scan of the results as following:

select distinct * from (select TABLE1.\*, TABLE2.\* from TABLE1 positional join TABLE2);
select distinct * from (select TABLE1.\*, select (COLUMN_X from TABLE2 where TABLE1.rowid=TABLE2.rowid) from TABLE1);

profiling them
statement1: 11.30s, statement2: 4.86s (2.32x)

========================
Is this behavior expected? Am I not properly using the POSITIONAL JOIN syntax to reach maximum speed for table scans?
(using v0.8.2-dev2673 fd683b9)

If somehow matters (it shouldn't, but who knows), ColumnX is a bigint and the original table was altered adding a new column with values updated along the process. No other update was performed on the original data. 

### OS:

x64

### DuckDB Version:

v0.8.2-dev2673

### DuckDB Client:

duckdb_cli-windows-amd64

### Full Name:

Daniel Zvinca 

### Affiliation:

LogBis

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Thanks for the report! Using `rowid` was my original plan, but `rowid` can change with inserts and deletes, so it is probably not what you want. I'll have a look but I strongly suspect that there is also the lack parallelism.

**Comment by hawkfish** [comment]
Can you give a description of the table columns? A Faker script would be ideal for this sort of test.

**Comment by danz68** [comment]
Even better, I've sent an email (at)duckdblabs with the CSV I used for this test. Just let me know if you received it.

I was aware of the rowid purpose (it can change with inserts and deletes) but is not a serious issue for testing purposes. Eventually positional join goal is to achieve a similar retrieval speed as all columns would belong to a single table, which is not the case for current implementation.

**Comment by Tmonster** [comment]
After a chat with Hawkfish, I think the reason for the slowdown is that positional joins are not parallelisable while hash joins are. Statement 2 uses a hash join while statement 1 uses a positional join. You can run `pragma threads=1` to see what kind of effect that has on the timings.

While hash joins can parallelize well, they still need to materialize the intermediates, which means at lower thread counts it may not be as fast as the positional join since a positional join can just stream both sides. 

Beyond this information I don't think there is much of an issue here. @danz68 if you want more info just let me know, otherwise I will close the issue later this week

**Comment by danz68** [comment]
For testing my point above, I manually split each data in two tables:

create table1_1 as select * from table1 where rowid<3000000;
create table1_2 as select * from table1 where rowid>=3000000;
create table2_1 as select * from table2 where rowid<3000000;
create table2_2 as select * from table2 where rowid>=3000000;

As expected, 

**explain analyze 
with 
a1 as (select * from table1_1 positional join table2_1), 
a2 as (select * from table1_2 positional join table2_2) 
select * from a1 union all select * from a2;**

timings are roughly half now, due multithreading.

**Comment by hawkfish** [comment]
Thanks for looking at this in more detail. I think the problem would be that each "window" has to be scanned from the start, so after a while it would start to get ugly. Pushing down the filter is effectively the same as random access scans (and would use the same machinery) so I think we know which way to go.
