### ISSUE TITLE
Can't install httpfs extension | version: duckdb==0.8.2.dev2809

### ISSUE THREAD

**Issue by kevinknights29** [duckdb/duckdb#8562]
### What happens?

Can't install httpfs extension to load parquets from s3 into duckdb.

I also tried to run this code with version 0.8.1 and got the exact same error message.

Code:
```error
duckdb.duckdb.HTTPException: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/a8ce02cc2e/linux_arm64_gcc4/httpfs.duckdb_extension.gz"
Extension "httpfs" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```

### To Reproduce

```python
import duckdb

db = duckdb.connect(":memory:")
duckdb.install_extension(connection=db, extension="httpfs")
duckdb.load_extension(connection=db, extension="httpfs")
```

### OS:

aarch64

### DuckDB Version:

0.8.2.dev2809

### DuckDB Client:

Python

### Full Name:

Kevin Knights

### Affiliation:

Dell

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
> Are you using a development build? In this case, extensions might not (yet) be uploaded.
You are using "0.8.2.dev2809", which is a development build

**Comment by kevinknights29** [comment]
> > Are you using a development build? In this case, extensions might not (yet) be uploaded.
> 
> You are using "0.8.2.dev2809", which is a development build

Yeah, but before that, I was running version 0.8.1 and still didn't work.

**Comment by kevinknights29** [comment]
For the record, I downgraded to version 0.8.0 and it worked fine.

**Comment by samansmink** [comment]
This is a duplicate issue of https://github.com/duckdb/duckdb/issues/8035. 

The problem is that integrating the arm64 manylinux build into our GH actions based CI is quite tricky without arm based runners. We don't distribute these extensions currently.

The reason it works for 0.8.0 is that that will do a install from source afaik. In your case that will be able to use the regular arm extensions (not the gcc4 variant where _GLIBCXX_USE_CXX11_ABI == 0).

You could try to install duckdb from source on arm python

**Comment by kevinknights29** [comment]
> This is a duplicate issue of #8035.
> 
> The problem is that integrating the arm64 manylinux build into our GH actions based CI is quite tricky without arm based runners. We don't distribute these extensions currently.
> 
> The reason it works for 0.8.0 is that that will do a install from source afaik. In your case that will be able to use the regular arm extensions (not the gcc4 variant where _GLIBCXX_USE_CXX11_ABI == 0).
> 
> You could try to install duckdb from source on arm python, this should should in your case build a version that will be able to use the arm binaries we do distribute.

Understood, thanks @samansmink.
