### ISSUE TITLE
How to set timeout on query execution?

### ISSUE THREAD

**Issue by grantjenks** [duckdb/duckdb#8564]
### What happens?

I want to set a timeout on DuckDB query execution. Specifically, there's a "SELECT ..." statement executing and if it doesn't finish after 25 seconds then I want to abort the query and get back to the user.

I've read through the docs but found nothing quite like it. There's a timeout for reading files over http but that's not what I need.

In SQLite, there's a "progress handler" API which supports aborting the query: https://www.sqlite.org/c3ref/progress_handler.html and see https://github.com/simonw/datasette/blob/00e59ec461dc0150772b999c7cc15fcb9b507d58/datasette/utils/__init__.py#L182 for an example in Python.

### To Reproduce

Desired functionality is something like:
```
con = duckdb.connect()
try:
    df = con.execute('SELECT ...', timeout=25).df()
except duckdb.TimeoutError:
    df = None
```

### OS:

Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Grant Jenks

### Affiliation:

LinkedIn

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by grantjenks** [comment]
See also https://github.com/duckdb/duckdb/discussions/8229

**Comment by grantjenks** [comment]
I hadn't seen this before: https://duckdb.org/docs/api/c/connect.html#duckdb_interrupt Could this be exposed in the Python interface?

**Comment by Mause** [comment]
> I hadn't seen this before: https://duckdb.org/docs/api/c/connect.html#duckdb_interrupt Could this be exposed in the Python interface?

It's already there in the dev version: https://duckdb.org/docs/api/python/reference/#duckdb.DuckDBPyConnection.interrupt

**Comment by grantjenks** [comment]
Can that be called from a different thread than the one executing the query?

**Comment by szarnyasg** [comment]
@grantjenks yes, it can be called from a different thread.

Supporting query timeout with a built-in function is currently not on our roadmap, so I'm closing this issue for now.
