### ISSUE TITLE
ray read_sql from duckdb failed

### ISSUE THREAD

**Issue by 982945902** [duckdb/duckdb#8565]
### What happens?

this is my dockdb factory code:
```    
def create_connection(self):
        def connection():
            db = duckdb.connect(database=':memory:')
            if self.config.source_type == pb.FileType.CSV:
                db.read_csv(self.config.source)
            else:
                raise Exception("TBD")

            return db
        return connection
```
this is ray read from duckdb code:
```
r = ray.data.read_sql(sql, db.create_connection())
```

this is error msg:
```
(ReadSQL->SplitBlocks(200) pid=7348)   File "/usr/local/lib/python3.10/dist-packages/ray/data/datasource/sql_datasource.py", line 98, in fallback_read_fn
(ReadSQL->SplitBlocks(200) pid=7348)     with _connect(self.connection_factory) as cursor:
(ReadSQL->SplitBlocks(200) pid=7348)   File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
(ReadSQL->SplitBlocks(200) pid=7348)     next(self.gen)
(ReadSQL->SplitBlocks(200) pid=7348)   File "/usr/local/lib/python3.10/dist-packages/ray/data/datasource/sql_datasource.py", line 78, in _connect
(ReadSQL->SplitBlocks(200) pid=7348)     raise e from None
(ReadSQL->SplitBlocks(200) pid=7348)   File "/usr/local/lib/python3.10/dist-packages/ray/data/datasource/sql_datasource.py", line 70, in _connect
(ReadSQL->SplitBlocks(200) pid=7348)     connection.rollback()
(ReadSQL->SplitBlocks(200) pid=7348) duckdb.TransactionException: TransactionContext Error: cannot rollback - no transaction is active
```

### To Reproduce

appear inevitably

### OS:

Linux 2c92a943e7cc 6.1.29-0-virt #1-Alpine SMP PREEMPT_DYNAMIC Wed, 17 May 2023 14:22:15 +0000 x86_64 x86_64 x86_64 GNU/Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux

### Full Name:

lishuo

### Affiliation:

JD.inc

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @982945902, thanks for reporting this. Could you please make your example self-contained (with imports, variable declarations), so it can be run in Python interpreter to reproduce the error?

**Comment by 982945902** [comment]
> Hi @982945902, thanks for reporting this. Could you please make your example self-contained (with imports, variable declarations), so it can be run in Python interpreter to reproduce the error?

```
import ray
import duckdb


def db_factory():
    # wget https://github.com/VowpalWabbit/vowpal_wabbit/files/9203605/iris.csv
    db = duckdb.connect(database=':memory:')
    db.read_csv('iris.csv')

    return db


conn = db_factory()
print(conn.sql("SELECT * FROM 'iris.csv'").df())

r = ray.data.read_sql("SELECT * FROM 'iris.csv'", db_factory)
r.take()

```

**Comment by hannes** [comment]
Thanks for reporting this, is it possible that Ray is doing something wrong there? From the error message, it seems like it's trying to rollback when no transaction is active. It might be some lack of clarity of the Python DB API, but it would be great to try to boil. this down a little more to something that ideally runs without requiring Ray, which is a big black box here.
