### ISSUE TITLE
Pragma "create_fts_index" fails when called from Julia client

### ISSUE THREAD

**Issue by Seitzal** [duckdb/duckdb#8578]
### What happens?

Trying to execute the "create_fts_index" pragma via the Julia connector fails, with the following error message:

```
ERROR: Invalid Error: Cannot prepare multiple statements at once!
Stacktrace:
 [1] DuckDB.Stmt(con::DuckDB.Connection, sql::String, result_type::Type)
   @ DuckDB ~/.julia/packages/DuckDB/I8oJ8/src/statement.jl:12
 [2] prepare
   @ ~/.julia/packages/DuckDB/I8oJ8/src/result.jl:828 [inlined]
 [3] prepare
   @ ~/.julia/packages/DuckDB/I8oJ8/src/result.jl:829 [inlined]
 [4] prepare
   @ ~/.julia/packages/DuckDB/I8oJ8/src/result.jl:830 [inlined]
 [5] execute
   @ ~/.julia/packages/DBInterface/1Gmxx/src/DBInterface.jl:130 [inlined]
 [6] #execute#2
   @ ~/.julia/packages/DBInterface/1Gmxx/src/DBInterface.jl:152 [inlined]
 [7] execute(conn::DuckDB.DB, sql::String)
   @ DBInterface ~/.julia/packages/DBInterface/1Gmxx/src/DBInterface.jl:152
 [8] top-level scope
   @ ~/path_omitted_for_privacy_reasons/test.jl:11
```

I suspect this might be due to the pragma itself resulting in multiple SQL statements, which the connector cannot execute in sequence for some reason (similar to the issue with the Import pragma in the NodeJS client in #6198).

This makes it impossible to use the FTS extension programmatically from Julia, without manually creating the index through another client.

It is unfortunately beyond my ability to provide a fix for this, since I am still relatively new to both Julia and DuckDB, but maybe someone else can.

### To Reproduce

Minimal Julia example that will produce this error:

```julia
using DuckDB
db = DBInterface.connect(DuckDB.DB, "duck.db")
DBInterface.execute(db, "CREATE TABLE table1 (id UBIGINT, text VARCHAR);")
DBInterface.execute(db, "INSERT INTO table1 VALUES (1, 'Lorem ipsum dolor sit amet');")
DBInterface.execute(db, "INSTALL 'fts';")
DBInterface.execute(db, "LOAD 'fts';")
DBInterface.execute(db, "PRAGMA create_fts_index('table1', 'id', 'text');")
```

### OS:

Linux 5.15.125-1 (Manjaro), x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Julia

### Full Name:

Alex Seitz

### Affiliation:

University of Heidelberg

### Have you tried this on the latest `master` branch?

I have tested with a release build (and could not test with a master build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hmm I think we've had a similar issue before.

The pragma resolves to multiple statements and internally we likely use prepare, which exects only a single statement

**Comment by szarnyasg** [comment]
Closing this as a wontfix for now.
