### ISSUE TITLE
Some of the export database options are unnecessarily copied in the created load.sql file

### ISSUE THREAD

**Issue by danz68** [duckdb/duckdb#8586]
### What happens?

Some of the export database options, like 'ROW_GROUP_SIZE 100000'  are unnecessarily copied in the load.sql statements. They are not understood when trying to load the database, in the COPY .. FROM statement .

### To Reproduce

1. Create or open any database with some data in it;
2. EXPORT DATABASE 'backup' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
3. create a new database
4. IMPORT DATABASE 'backup';

**Not implemented Error: Unsupported option for COPY FROM parquet: ROW_GROUP_SIZE**

the load.sql file contains statements like
COPY TABLE FROM 'target_directory\TABLE.parquet' (FORMAT 'parquet', **ROW_GROUP_SIZE 100000,** COMPRESSION 'ZSTD');
which has unrecognized (and unnecessary) options.

### OS:

x64

### DuckDB Version:

v0.8.2-dev2673

### DuckDB Client:

duckdb_cli-windows-amd64

### Full Name:

Daniel Zvinca

### Affiliation:

LogBis

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/8559
