### ISSUE TITLE
Specifying columns as custom ENUM types does not work in read_csv

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb#8587]
### What happens?

Using a custom ENUM type in `read_csv` to configure the CSV reader with either the `types` or `columns` parameters fails.   

### To Reproduce

Using the DuckDB CLI, given this custom ENUM:

    D CREATE TYPE response AS ENUM ('Y', 'N');

And an empty file `data.csv`  for passing the file-existence check (shell command):

    $ touch data.csv

The following two attempts to use the new `response` type for parsing the CSV fail:

    D FROM read_csv('data.csv', types={'response': 'response'});
    Error: Binder Error: Unrecognized type "response" for read_csv_auto types definition

    D FROM read_csv('data.csv', columns={'response': 'response'});
    Error: Catalog Error: Type with name response does not exist!
    Did you mean "memory.response"?

### OS:

Ubuntu 23.04

### DuckDB Version:

0.8.2-dev2842

### DuckDB Client:

CLI

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ned2** [comment]
hey @Tishj I tried the following change you suggested on discord, to use the version `TransformStringToLogicalType` with the client context passed in:

```
diff --git a/src/function/table/read_csv.cpp b/src/function/table/read_csv.cpp
index 0bb276477b..e1f1521a84 100644
--- a/src/function/table/read_csv.cpp
+++ b/src/function/table/read_csv.cpp
@@ -207,7 +207,7 @@ static unique_ptr<FunctionData> ReadCSVBind(ClientContext &context, TableFunctio
                        }
                        options.sql_type_list.reserve(sql_type_names.size());
                        for (auto &sql_type : sql_type_names) {
-                               auto def_type = TransformStringToLogicalType(sql_type);
+                               auto def_type = TransformStringToLogicalType(sql_type, context);
                                if (def_type.id() == LogicalTypeId::USER) {
                                        throw BinderException("Unrecognized type \"%s\" for read_csv_auto %s definition", sql_type,
                                                              kv.first);
```
They both still don't work, however it looks like we might have made some progress with one of the errors:

```
D CREATE TYPE response AS ENUM ('Y', 'N');

D FROM read_csv('data.csv', types={'response': 'response'});
Error: Catalog Error: Type with name response does not exist!
Did you mean "memory.response"?

D FROM read_csv('data.csv', columns={'response': 'response'});
Error: Catalog Error: Type with name response does not exist!
Did you mean "memory.response"?
```

**Comment by Tishj** [comment]
Hmm I really thought that would be the only change required.

I might have a look at a later date, I'm a little hesitant to touch the csv reading code right now because pedros PR is close to landing

**Comment by ned2** [comment]
Ahhh yes true. That makes sense to wait until the CSV refactor is in and we can check if still reproduces .

**Comment by ned2** [comment]
Heya @Tishj, now that Pedro's CSV refactor has landed, I tried this out again the same issues still reproduces for me.

**Comment by ned2** [comment]
Just checked with the CSV I was trying to load and yes it works! Awesome stuff; thanks heaps!
