### ISSUE TITLE
[WAL Replay] Handle partial writes to WAL

### ISSUE THREAD

**Issue by Vegetable26** [duckdb/duckdb#8592]
### What happens?

We are running DuckDB on NAS. One failure mode we were playing with was with partial writes to the WAL. ex: where the filesystem only writes 90 bytes out of the 100 bytes and then something disastrous happens to the host. 

Here DuckDB acts correctly in that it never ack's the commit. But when I try to restart DuckDB on that db and wal file - I see an error: "Exception in WAL playback during initial read: Serialization Error: not enough data in file to deserialize result"

I guess my assumption would be that we can omit any partially written entries in the WAL as they were not ack'd to the user? 

### To Reproduce

Hacky repro:
1. Start up DuckDB
2. Write a table A. Track the WAL size : size_a
3. Write a table B. Track the WAL size: size_b 
4. kill -9 DuckDB
5. Manually truncate the WAL to  size_a < len < size_b (simulate a partial write failure to the WAL)
6. Start a new DuckDB on that file. 

At step 6 - I see the above error and table A has disappeared. 

### OS:

any

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Joseph Hwang

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed in #8982
