### ISSUE TITLE
libduckdb-windows-amd64.zip content

### ISSUE THREAD

**Issue by mrayva** [duckdb/duckdb#860]
Shouldn't it  include  import library (.lib)?
Any sample VS/Windows project available for reference?

**Comment by mrayva** [comment]
fyi: My experiences building from amalgamated sources using latest VS2019:

1. Needed to use /Zc:externC-   switch ( as per https://developercommunity.visualstudio.com/content/problem/756694/including-windowsh-and-boostinterprocess-headers-l.html ) due to 

extern "C" {
struct _SECURITY_ATTRIBUTES;
	__declspec(dllimport) void* __stdcall CreateSemaphoreW(_SECURITY_ATTRIBUTES* lpSemaphoreAttributes, long lInitialCount, long lMaximumCount, const wchar_t* lpName);
	__declspec(dllimport) int __stdcall CloseHandle(void* hObject);
	__declspec(dllimport) unsigned long __stdcall WaitForSingleObject(void* hHandle, unsigned long dwMilliseconds);
	__declspec(dllimport) int __stdcall ReleaseSemaphore(void* hSemaphore, long lReleaseCount, long* lpPreviousCount);
}

2. SDL must be off since even with _CRT_SECURE_NO_WARNINGS, I'd get 
duckdb.cpp(36650,32): error C4146: unary minus operator applied to unsigned type, result still unsigned
 - are you sure this makes sense/no bug:

      source->seekg(-bytes_in_chunk, source->end);
?

3. Character set - no UNICODE, 
   Warnings - /w0, /w1, /w2 -  otherwise get swamped

**Comment by Mytherin** [comment]
Thanks for sharing!

> Needed to use /Zc:externC- switch ( as per https://developercommunity.visualstudio.com/content/problem/756694/including-windowsh-and-boostinterprocess-headers-l.html ) ...

Interesting; I will look into replacing this by `#include windows.h` to avoid this problem.

> source->seekg(-bytes_in_chunk, source->end);

That indeed looks like a bug; nice find :) I have added a cast to a signed type.

> Warnings - /w0, /w1, /w2 - otherwise get swamped

Indeed at some point we should look at fixing all Windows warnings. This will likely lead to us finding some bugs.The problem is, as you said, there are so many of them :)

**Comment by mrayva** [comment]
Few more observations/issues from building, now using  cmake+VS2019 - encountering Linking /dependency problems:

Error	LNK1181	cannot open input file '..\..\src\Release\duckdb.lib'	sqlite3_api_wrapper	E:\code\duckdb\tools\sqlite3_api_wrapper\LINK	1	
Error	LNK1181	cannot open input file 'Release\sqlite3_api_wrapper.lib'	test_sqlite3_api_wrapper	E:\code\duckdb\tools\sqlite3_api_wrapper\LINK	1	
Error	LNK1181	cannot open input file 'dbgen.lib'	duckdb_dbgen	E:\code\duckdb\tools\rest\LINK	1

**Comment by hannes** [comment]
This is likely outdated
