### ISSUE TITLE
Comparing strings to numbers tries to convert the strings to numbers?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#8603]
### What happens?

When comparing a string to a number, duckdb seems to try to convert the string to a number, not the other way round. This is surprising and inconsistent with many other weakly-typed languages including R and Python.

The `IN` operator downcasts to strings in this case, too.

### To Reproduce

```sh
✗ echo "select ('a' = 1) AS x" | build/debug/duckdb
Error: near line 1: Conversion Error: Could not convert string 'a' to INT32
✗ echo "select ('a' = 1.0) AS x" | build/debug/duckdb
Error: near line 1: Conversion Error: Could not convert string "a" to DECIMAL(2,1)
✗ echo "select ('a' = 1.0::double) AS x" | build/debug/duckdb
Error: near line 1: Conversion Error: Could not convert string 'a' to DOUBLE
✗ echo "select ('1' IN (1)) AS x" | build/debug/duckdb
┌─────────┐
│    x    │
│ boolean │
├─────────┤
│ true    │
└─────────┘
✗ echo "select (1 IN ('1')) AS x" | build/debug/duckdb
┌─────────┐
│    x    │
│ boolean │
├─────────┤
│ true    │
└─────────┘
```

### OS:

macOS aarch64

### DuckDB Version:

dd7f0c0870d89ae152a53191f87490052579d40e

### DuckDB Client:

CLI

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hmm that is unexpected, does this issue also happen when the integer values are negative?

It might be related to this:
```c++
	VARCHAR = 25,
	BLOB = 26,
	INTERVAL = 27,
	UTINYINT = 28,
	USMALLINT = 29,
	UINTEGER = 30,
	UBIGINT = 31,
```

In MaxLogicalType we use these numbers to determine cast-ability

**Comment by krlmlr** [comment]
It affects `INT32`, `DECIMAL` and `DOUBLE`, as seen in the reproducible example.

**Comment by Tishj** [comment]
Right, I missed that, apologies.

**Comment by Tishj** [comment]
This looks to be intended, judging by this PR:
https://github.com/duckdb/duckdb/pull/1596

**Comment by krlmlr** [comment]
@Mytherin: What's the intention behind https://github.com/Mytherin/duckdb/commit/353ac727804912759097d1ded199ae09c321e5ee#diff-6d534bb3faba1b2e6c06780804e6f07d5a45fe40c4ffda03af5b87967bd44944R85 (line 85, highlighted)?

**Comment by renevdzee** [comment]
I just ran into which i think is the same issue. A join over 2 csv files, which worked perfect before, returned a "Cannot convert string to INT32' error. It worked until someone added a alphanumeric value in the "Article" column in one of the files. (I did used the automatic column type detection of the csv reader).

I quickly discovered that duckdb does the same thing as microsoft sql server, doing narrowing conversions at query execution. I have never encountered this in Oracle or Postgres.

a small example (in duckdb cli) which describes the problem I had in sql server.
```sql
-- table
CREATE TABLE articles(
  article VARCHAR(12) PRIMARY KEY NOT NULL,
  description VARCHAR(30)
);
INSERT INTO articles VALUES ('1100','Laptop'),('1200','PC Keyboard'),('3000','Chair');
-- and a view
CREATE VIEW vw_itstuff AS SELECT * FROM articles WHERE article between 1000 and 2000;

-- test view, no issues, ship the product
SELECT * FROM vw_itstuff;
+-----------------------+
¦ article ¦ description ¦
¦ varchar ¦   varchar   ¦
+---------+-------------¦
¦ 1100    ¦ Laptop      ¦
¦ 1200    ¦ PC Keyboard ¦
+-----------------------+

-- half a year later some adds a alphanumeric value
INSERT INTO articles VALUES('P012', 'Pencil red');

-- and crash... 
SELECT * FROM vw_itstuff;
Error: Conversion Error: Could not convert string 'PNC1' to INT32

-- ==> :-( angry customer
```
It was my mistake I forgot the quotes around the values in the view, but I did not catch that during testing because the database allowed it. In my opinion if this is allowed by the database, the conversion should not be done in a narrowing way during execution.

**Comment by Tmonster** [comment]
I think it's because duckdb prefers comparing integer types over comparing varcher types since integer types are faster to compare. If you want archer comparison you have to cast the integer type to varcher, otherwise you get a conversion error

**Comment by krlmlr** [comment]
We can work around using custom duckdb functions.
