### ISSUE TITLE
High memory usage when reading boolean list column from parquet

### ISSUE THREAD

**Issue by PaulCherian** [duckdb/duckdb#8623]
### What happens?

Memory usage explodes when I try to materialize a 100k row BOOL[] column(ie each row value is [ False, True....1000 elements]) as a pandas dataframe from parquet files. 
At same time, if I try to materialize the column as a arrow table first and then convert it to a pandas dataframe, memory usage doesn't spike.

### To Reproduce

```
 parquet_path = '<path>'

 query = "select \"boolean_list_column\" from read_parquet('{}/*.parquet')".format(parquet_path)
#memory usage explodes to like 30GB
 column = duckdb.sql(query).df()

#memory usage stays level around 2GB
 column = duckdb.sql(query).arrow().to_pandas()
```

### OS:

mac

### DuckDB Version:

0.8.1

### DuckDB Client:

python

### Full Name:

Paul Cherian

### Affiliation:

qualtrics

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @PaulCherian, thanks for reporting this. Could you please provide a script that generates a Parquet file that reproduces this issue?

**Comment by PaulCherian** [comment]
You can use the snippet below to generate the parquet files
```
parquet_file_path = '/tmp/parquet_test/test.parquet'

rows = 1000000
width = 1000
column = np.random.choice([False, True], size=(rows, width))
df = pd.DataFrame({'bool_list_column': np.zeros(rows, dtype=object)})
for i in range(rows):
    df.iloc[i, 0] = column[i]
df.to_parquet(parquet_file_path)
```

**Comment by PaulCherian** [comment]
Here is the memory usage graph I generated using `memray` when running 
```
print('reading parquet using duckdb')
start = time.time()
query = "select bool_list_column from read_parquet('{}')".format(
    parquet_file_path)
checkbox = duckdb.sql(query).df()
print('took {} seconds'.format(time.time() - start))
```
The whole process took ~200s to run
![newplot (16)](https://github.com/duckdb/duckdb/assets/13074900/f5efe72f-61d2-4344-a806-313bf259ae45)

**Comment by PaulCherian** [comment]
Here is the memory usage graph I generated using memray when running
```
print('reading parquet using duckdb')
start = time.time()
query = "select bool_list_column from read_parquet('{}')".format(
    parquet_file_path)
checkbox = duckdb.sql(query).arrow.to_pandas()
print('took {} seconds'.format(time.time() - start))
```
The whole process took only ~20s(significantly faster than .df())
![newplot (15)](https://github.com/duckdb/duckdb/assets/13074900/a354dbba-7012-47d8-b66e-cbeeafb845d8)
