### ISSUE TITLE
db.sql returns None when I query with pivot statement on empty table

### ISSUE THREAD

**Issue by heury** [duckdb/duckdb#8627]
### What happens?

When I query with pivot statement on empty table, it returns "NoneType"
It only occurs with "sql" function. 

### To Reproduce

```python
db.sql("CREATE TABLE Cities(Country VARCHAR, Name VARCHAR, Year INT, Population INT);")

db.sql("From Cities").pl()
Country	Name	Year	Population
str	str	i32	i32

db.sql("PIVOT Cities ON Year USING SUM(Population);").pl()
AttributeError: 'NoneType' object has no attribute 'pl'

db.execute("PIVOT Cities ON Year USING SUM(Population);").pl()
Country	Name
str	str

```

### OS:

linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

YJ

### Affiliation:

SEC

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
As stated in the issue template, please verify that this occurs on master, by installing the latest dev build, there are even instructions on how to do so

Your fixed example would be:
```py
import duckdb
db = duckdb.connect()

res = db.sql("CREATE TABLE Cities(Country VARCHAR, Name VARCHAR, Year INT, Population INT);")
print(res)

res = db.sql("From Cities").pl()
print(res)

res = db.sql("PIVOT Cities ON Year USING SUM(Population);").pl()
print(res)

res = db.execute("PIVOT Cities ON Year USING SUM(Population);").pl()
print(res)
```

And the results I get on master are:
```
None
shape: (0, 4)
┌─────────┬──────┬──────┬────────────┐
│ Country ┆ Name ┆ Year ┆ Population │
│ ---     ┆ ---  ┆ ---  ┆ ---        │
│ str     ┆ str  ┆ i32  ┆ i32        │
╞═════════╪══════╪══════╪════════════╡
└─────────┴──────┴──────┴────────────┘
shape: (0, 2)
┌─────────┬──────┐
│ Country ┆ Name │
│ ---     ┆ ---  │
│ str     ┆ str  │
╞═════════╪══════╡
└─────────┴──────┘
shape: (0, 2)
┌─────────┬──────┐
│ Country ┆ Name │
│ ---     ┆ ---  │
│ str     ┆ str  │
╞═════════╪══════╡
└─────────┴──────┘
```

This is fixed by #https://github.com/duckdb/duckdb/pull/7967

**Comment by carlopi** [comment]
I think this can be closed right?

`pip install duckdb --pre --upgrade` should install latest duckdb

**Comment by heury** [comment]
I checked it with latest source codes and it works normally. Thanks.
