### ISSUE TITLE
Using read_csv to read some csv.gz files triggers "IO Error: Input is not a GZIP stream"

### ISSUE THREAD

**Issue by Pegorari** [duckdb/duckdb#8630]
### What happens?

When I try to query some specific files in a folder using read_csv it triggers the error "IO Error: Input is not a GZIP stream". The files are not corrupted, happens always with some files that are not corrupted. 

### To Reproduce

1. Add the attached files 0791979.csv.gz and 0791980.csv.gz to a folder.
2. try to query the folder like: "SELECT COUNT(*) FROM read_csv_auto('S:/data/transactions/*.csv.gz'
3. When 0791979.csv.gz is inside the folder, the error happens, but the file is not corrupted.

Code in node.js I´m using:

```
const db = new duckdb.Database(':memory:')
await db.all("SELECT COUNT(*) FROM read_csv_auto('S:/data/transactions/*.csv.gz') LIMIT 1", function (err, res) {
    if (err) {
        throw err;
    }
    console.log(res)
});

```
[0791980.csv.gz](https://github.com/duckdb/duckdb/files/12386596/0791980.csv.gz)
[0791979.csv.gz](https://github.com/duckdb/duckdb/files/12386597/0791979.csv.gz)

### OS:

Windows 10 x64

### DuckDB Version:

v0.8.1

### DuckDB Client:

NodeJS

### Full Name:

Rodrigo Pegorari

### Affiliation:

hobby

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by StLeoX** [comment]
https://duckdb.org/docs/data/csv/overview#read_csv_auto-function

It doesn't say you can use the `*` macther.
Try one file each time.

**Comment by Tishj** [comment]
I've downloaded your test files, and ran this test case:
```sql
D select DISTINCT tbl.filename FROM read_csv_auto('tmp/*.csv.gz', filename=True) tbl;
┌────────────────────┐
│      filename      │
│      varchar       │
├────────────────────┤
│ tmp/0791979.csv.gz │
│ tmp/0791980.csv.gz │
└────────────────────┘
```
Seems to work on master

Likely fixed by https://github.com/duckdb/duckdb/pull/8386

**Comment by l1t1** [comment]
230820 nightly build
```
D:\duckdb>duckdb082c
v0.8.2-dev3055 b105af71bb
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select DISTINCT tbl.filename FROM read_csv_auto('/tmp/*.csv.gz', filename=True) tbl;
┌─────────────────────┐
│      filename       │
│       varchar       │
├─────────────────────┤
│ /tmp\0791979.csv.gz │
│ /tmp\0791980.csv.gz │
└─────────────────────┘

D select tbl.filename,count(*) FROM read_csv_auto('/tmp/*.csv.gz', filename=True) tbl group by filename;
┌─────────────────────┬──────────────┐
│      filename       │ count_star() │
│       varchar       │    int64     │
├─────────────────────┼──────────────┤
│ /tmp\0791979.csv.gz │         3919 │
│ /tmp\0791980.csv.gz │         3323 │
└─────────────────────┴──────────────┘
```

**Comment by Pegorari** [comment]
> 230820 nightly build
> 
> ```
> D:\duckdb>duckdb082c
> v0.8.2-dev3055 b105af71bb
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D select DISTINCT tbl.filename FROM read_csv_auto('/tmp/*.csv.gz', filename=True) tbl;
> ┌─────────────────────┐
> │      filename       │
> │       varchar       │
> ├─────────────────────┤
> │ /tmp\0791979.csv.gz │
> │ /tmp\0791980.csv.gz │
> └─────────────────────┘
> 
> D select tbl.filename,count(*) FROM read_csv_auto('/tmp/*.csv.gz', filename=True) tbl group by filename;
> ┌─────────────────────┬──────────────┐
> │      filename       │ count_star() │
> │       varchar       │    int64     │
> ├─────────────────────┼──────────────┤
> │ /tmp\0791979.csv.gz │         3919 │
> │ /tmp\0791980.csv.gz │         3323 │
> └─────────────────────┴──────────────┘
> ```

Tested with nightly build and it's fixed, thanks!
The error happens only in the last build version you download from the website, and node installed version 0.8.1.
