### ISSUE TITLE
Github Pages 404 on duckdb.org

### ISSUE THREAD

**Issue by jghjgfgh** [duckdb/duckdb#8641]
### What happens?

Github Pages 404 when going to duckdb.org

### To Reproduce

Go to duckdb.org

### OS:

Linux

### DuckDB Version:

N/A

### DuckDB Client:

N/A

### Full Name:

W

### Affiliation:

None

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by mdu-adam-williamson** [comment]
Still down

**Comment by mdu-adam-williamson** [comment]
Hosted here I believe https://github.com/duckdb/duckdb-web

**Comment by Mause** [comment]
Should be fixed now!
