### ISSUE TITLE
Issue comparing timestamp str with time when optimizer enabled

### ISSUE THREAD

**Issue by TomBurch** [duckdb/duckdb#8659]
### What happens?

If you cast a timestamp str like `2023-08-17T23:00:08.539Z` to time and try to compare it with a regular time the comparison doesn't work as expected.

This can be fixed by:
- Converting the str to a timestamp first
- Or disabling the optimizer

### To Reproduce

```sql
WITH results AS (
    SELECT '2023-08-17T23:00:08.539Z' as timestamp
)
SELECT * FROM results WHERE timestamp::TIME BETWEEN '22:00:00'::TIME AND '23:59:59'::TIME

┌───────────┐
│ timestamp │
│  varchar  │
├───────────┤
│  0 rows   │
└───────────┘
```
```sql
pragma disable_optimizer;

WITH results AS (
    SELECT '2023-08-17T23:00:08.539Z' as timestamp
)
SELECT * FROM results WHERE timestamp::TIME BETWEEN '22:00:00'::TIME AND '23:59:59'::TIME

┌──────────────────────────┐
│        timestamp         │
│         varchar          │
├──────────────────────────┤
│ 2023-08-17T23:00:08.539Z │
└──────────────────────────┘
```

### OS:

Ubuntu 20

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Tom Burch

### Affiliation:

Ocado Technology

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
The optimiser somehow appears to be evaluating the expression incorrectly. When I ask for the query plan, it just says empty result.

**Comment by hawkfish** [comment]
`ComparisonSimplificationRule::Apply` assumes that if all the inputs are casts from the same type that the comparison rules work for the base type. Which is clearly not true here.

**Comment by TomBurch** [comment]
Not sure if this is helpful but the query does seem to work if you replace `BETWEEN '22:00:00'` with `'19:00:00'` or earlier

**Comment by hawkfish** [comment]
The optimiser is comparing the strings. And since the year of the string being cast is `2023`, any time string that collates before 202 will work.

**Comment by hawkfish** [comment]
`BoundCastExpression::CastIsInvertible` things that string casts to time are invertible. But since we allow casting from full timestamp strings, that is not true.
