### ISSUE TITLE
Support all Arrow timestamp types

### ISSUE THREAD

**Issue by hannesmuehleisen** [duckdb/duckdb#868]

**Comment by lawrencealexander10** [comment]
I see this issue is still open- I'm encountering a "RuntimeError: Not implemented Error: Unsupported type tsm" for parquet field type timestamp[ms] when using from_arrow_table using the python API. Is this expected?

**Comment by hannesmuehleisen** [comment]
Its certainly something we should fix.

**Comment by pdet** [comment]
This can be closed.
