### ISSUE TITLE
undefined symbol: duckdb_adbc_init

### ISSUE THREAD

**Issue by rydeng** [duckdb/duckdb#8702]
### What happens?

When use the commit 6421a36e941b54e3fba94863d95f611570a69829 to build and test adbc:
```sh
DUCKDEBUG=1 PYTHON_USER_SPACE=1 BUILD_PYTHON=1 make debug
```
got error:
```python
duckdb-0.8.2.dev2842+g6421a36e94-py3.10-linux-aarch64.egg/duckdb/duckdb.cpython-310-aarch64-linux-gnu.so: undefined symbol: duckdb_adbc_init
```

### To Reproduce

```python
import pyarrow
import sys
import datetime
import os
import duckdb
from adbc_driver_manager import dbapi

driver_parh = duckdb.duckdb.__file__

con = dbapi.connect(driver=driver_parh, entrypoint="duckdb_adbc_init", db_kwargs={"path": ":memory:"})

with con.cursor() as cursor:
     cursor.execute("SELECT 1")
     cursor.fetch_arrow_table()

```

### OS:

linux, aarch64

### DuckDB Version:

duckdb-0.8.2.dev2842+g6421a36e94

### DuckDB Client:

python

### Full Name:

Roy Dennis

### Affiliation:

bq

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
How are you building?

Building through `BUILD_PYTHON=1 make debug` will not include this symbol

only through:
```
cd tools/pythonpkg
python3 setup.py install
```

**Comment by rydeng** [comment]
@Tishj Thanks for you reply, I'll try ```python3 setup.py install```
