### ISSUE TITLE
Unable to Open Parquet File - "Not a Valid DuckDB Database File" Error

### ISSUE THREAD

**Issue by youen** [duckdb/duckdb#8704]
### What happens?

I am experiencing an issue when trying to open a Parquet file using DuckDB. The Parquet file in question is sourced from the "TLC Trip Record Data" dataset (available [here](https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-05.parquet)), containing taxi trip records for NYC.

The error message I'm encountering is as follows:
```
Error: unable to open database "data/yellow_tripdata_2023-05.parquet": IO Error: The file "data/yellow_tripdata_2023-05.parquet" exists, but it is not a valid DuckDB database file!
```
I have confirmed that the Parquet file is valid and readable using other tools such as dsq and online viewers like [parquetreader.com](https://parquetreader.com/) and [tablab.app](https://www.tablab.app/view/parquet?dataset-source=local). This issue seems to be specific to DuckDB.

### To Reproduce

download https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-05.parquet and launch duckdb
```
$ duckdb data/yellow_tripdata_2023-05.parquet 
Error: unable to open database "data/yellow_tripdata_2023-05.parquet": IO Error: The file "data/yellow_tripdata_2023-05.parquet" exists, but it is not a valid DuckDB database file!
```

### OS:

x64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

cli

### Full Name:

Youen Péron

### Affiliation:

CGI

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
This is expected, parquet files are not DuckDB database files - DuckDB files are a file format specific to DuckDB

**Comment by youen** [comment]
Apologies for the hasty conclusion in my initial message. I appreciate your clarification that Parquet files are not intended to be opened as DuckDB database files. Thank you for your guidance in addressing the issue and for your patience in explaining the correct approach to work with the file. Your assistance is greatly valued.
