### ISSUE TITLE
Getting Error when a expression could be convert

### ISSUE THREAD

**Issue by Lordworms** [duckdb/duckdb#8713]
### What happens?

When I was trying this SQL, the Error was raised. 
<img width="916" alt="image" src="https://github.com/duckdb/duckdb/assets/48054792/13251f5b-e4d6-44dd-a1ec-084f87df9d24">

### To Reproduce

Create table like this 
```SQL
create table tt(i INTEGER);
```
Then try this SQL, and error happens
```SQL
select max(i) from tt where ((select min(i) from tt) < 4);
```

### OS:

MACOS

### DuckDB Version:

main

### DuckDB Client:

shell

### Full Name:

LordWorms

### Affiliation:

N/A

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Lordworms** [comment]
and it says we must restart the DB to process another query
<img width="923" alt="image" src="https://github.com/duckdb/duckdb/assets/48054792/b0d950f8-5465-4c9b-8975-c0c5d6d60a6c">

**Comment by Tishj** [comment]
> and it says we must restart the DB to process another query <img alt="image" width="923" src="https://user-images.githubusercontent.com/48054792/263969652-b0d950f8-5465-4c9b-8975-c0c5d6d60a6c.png">

That's expected behavior when you encounter an internal exception

But the internal exception should be fixed, users shouldn't run into that 👍

**Comment by Lordworms** [comment]
I am pretty sure the where condition could be converted into a bool expr. Although not that familiar with duckDB source code. But in mysql, the subselect item in a condition_item could be resolve into a constant in such SQLs

**Comment by l1t1** [comment]
in aarch64 Linux, no question
```
v0.8.2-dev3007 dd7f0c0870
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table tt(i INTEGER);
D select max(i) from tt where ((select min(i) from tt) < 4);
┌────────┐
│ max(i) │
│ int32  │
├────────┤
│        │
└────────┘
```

**Comment by l1t1** [comment]
everything is right
```
D insert into tt select 3;
D select max(i) from tt where (select min(i) from tt) < 4;
┌────────┐
│ max(i) │
│ int32  │
├────────┤
│      3 │
└────────┘
D insert into tt select 5;
D select max(i) from tt where (select min(i) from tt) < 4;
┌────────┐
│ max(i) │
│ int32  │
├────────┤
│      5 │
└────────┘
```

**Comment by l1t1** [comment]
I got the binary from actions such as https://github.com/duckdb/duckdb/actions/runs/6006433673

**Comment by l1t1** [comment]
> in aarch64 Linux, no question
> 
> ```
> v0.8.2-dev3007 dd7f0c0870
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> D create table tt(i INTEGER);
> D select max(i) from tt where ((select min(i) from tt) < 4);
> ┌────────┐
> │ max(i) │
> │ int32  │
> ├────────┤
> │        │
> └────────┘
> ```

windows x64 version also works fine

**Comment by Lordworms** [comment]
I built it under macOS and CMake version is  3.26.4

**Comment by szarnyasg** [comment]
@Lordworms can you please try with the latest `main` branch?

I built it on MacOS and it works fine:
```sql
D create table tt(i INTEGER);
D select max(i) from tt where ((select min(i) from tt) < 4);
┌────────┐
│ max(i) │
│ int32  │
├────────┤
│        │
└────────┘
```
It also works with data inserted to `tt`:
```sql
D insert into tt values (3);
D select max(i) from tt where ((select min(i) from tt) < 4);
┌────────┐
│ max(i) │
│ int32  │
├────────┤
│      3 │
└────────┘
```
