### ISSUE TITLE
`strptime` unable to parse format `%Y-%-m-%-d`

### ISSUE THREAD

**Issue by allenwangs** [duckdb/duckdb#8722]
### What happens?

`strptime` function unable to parse string using format `%Y-%-m-%-d`

### To Reproduce

Parse a string in format `%Y%-m%-d` (for example `202381`). Please note that both month and day are decimal numbers. 

```python
duckdb.__version__
'0.8.1'
```

```sql
SELECT strptime('202381', '%Y%-m%-d');
```

```
InvalidInputException: Invalid Input Error: Could not parse string "202381" according to format specifier "%Y%-m%-d"
202381
    ^
Error: Month out of range, expected a value between 1 and 12
```

### OS:

iOS arm64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Allen Wang

### Affiliation:

Zitara

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
you can insert space in the string and format string
```
D SELECT strptime('2023 8 1', '%Y %-m %-d');
┌────────────────────────────────────┐
│ strptime('2023 8 1', '%Y %-m %-d') │
│             timestamp              │
├────────────────────────────────────┤
│ 2023-08-01 00:00:00                │
└────────────────────────────────────┘
```

**Comment by l1t1** [comment]
if no spaces, eg `111` makes confuse. 11 Jan  or 1 Nov?

**Comment by allenwangs** [comment]
Oh. Thanks for pointing out.
Closing this ticket.
