### ISSUE TITLE
select count(distinct ..) very slow

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#8724]
### What happens?

run a count(distinct ) on a table with 100000000 took 30s.

### To Reproduce

```
select count(distinct a) from (select generate_series a from generate_series(1,100000000))a;
```

```
┌───────────────────┐
│ count(DISTINCT a) │
│       int64       │
├───────────────────┤
│         100000000 │
└───────────────────┘
Run Time (s): real 30.920 user 27.424976 sys 3.478822
```

### OS:

windows7 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

home

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
if query a table instead of a sub query, `set theads=num` speeds up, but still slow
```
D create table a as select generate_series a from generate_series(1,100000000);
Run Time (s): real 1.426 user 1.232408 sys 0.202801

D select count(distinct a) from a;
100% ▕████████████████████████████████████████████████████████████▏
┌───────────────────┐
│ count(DISTINCT a) │
│       int64       │
├───────────────────┤
│         100000000 │
└───────────────────┘
Run Time (s): real 31.258 user 28.189381 sys 2.589617
D set threads=20;
Run Time (s): real 0.003 user 0.000000 sys 0.000000
D select count(distinct a) from a;
100% ▕████████████████████████████████████████████████████████████▏
┌───────────────────┐
│ count(DISTINCT a) │
│       int64       │
├───────────────────┤
│         100000000 │
└───────────────────┘
Run Time (s): real 10.579 user 120.510773 sys 15.397299
```

**Comment by szarnyasg** [comment]
@l1t1 could you please reach out to me via email to gabor@duckdblabs.com? Thanks.

**Comment by szarnyasg** [comment]
This is expected behaviour. Ensuring the uniqueness of 100M integers is in general slow. A specialized algorithm could detect that this column encoved a list t where t[i] = i but this is currently not supported.

Also, sorting 100M integers is expected to be slow:

```sql
select count(b.a) from (select s.a from generate_series(1, 100000000) s(a) order by a) b;
┌────────────┐
│ count(b.a) │
│   int64    │
├────────────┤
│  100000000 │
└────────────┘
Run Time (s): real 5.284 user 4.927923 sys 1.589845
```
