### ISSUE TITLE
pivot performance 

### ISSUE THREAD

**Issue by douenergy** [duckdb/duckdb#8733]
### What happens?

Duckdb pivot is 10x slower than Pandas pivot (still prefer the duck one 😍)

seems like too many distinct group ? 

### To Reproduce

```py
import pandas as pd
import numpy as np
import duckdb

ROWS = 10000
dates = pd.date_range(start='2023-01-01', periods=ROWS, freq='D')
ids = np.arange(1, ROWS+1)
tags = np.random.choice(['TagA', 'TagB', 'TagC'], size=(ROWS, 3))

metric_names = np.random.choice(['MetricA', 'MetricB', 'MetricC'], size=ROWS)
metric_values = np.random.randint(1, ROWS+1, size=ROWS)

data = {
    'DATE': dates,
    'ID': ids,
    'TAG_1': tags[:, 0],
    'TAG_2': tags[:, 1],
    'TAG_3': tags[:, 2],
    'METRIC_NAME': metric_names,
    'METRIC_VALUE': metric_values
}
```

### Pandas 1.5.3 (24.7 ms)
```py
df_pandas  = pd.DataFrame(data)
df_pandas= df_pandas.pivot(columns='METRIC_NAME',
              index=('DATE', 'ID', 'TAG_1', 'TAG_2', 'TAG_3'),
              values='METRIC_VALUE')
df_pandas = df_pandas.rename_axis(None, axis='columns')
df_pandas = df_pandas.reset_index()
df_pandas = df_pandas.sort_values(['DATE', 'ID'])
```

### DuckDB 0.8.1 (486 ms)
```py
df_duckin = pd.DataFrame(data)

df_duckout = duckdb.sql('''
    pivot df_duckin
    on METRIC_NAME
    using sum(METRIC_VALUE)
    order by DATE, ID
''').df()
```

[google colab reproduce](https://colab.research.google.com/drive/1-fNZgziYScYySpMc2nLt48ElW0SVLi7V?usp=sharing)

### OS:

MacOS Ventura

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Alex Tsieh 

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by maver1ck** [comment]
I think this is related to https://github.com/duckdb/duckdb/issues/13552

**Comment by Mytherin** [comment]
This seems solved - I get 21ms for Pandas and 28ms for DuckDB in the latest release.
