### ISSUE TITLE
Assertion `new_block->state == BlockState::BLOCK_UNLOADED' failed.

### ISSUE THREAD

**Issue by rongcuid** [duckdb/duckdb#8737]
### What happens?

In my Rust application using duckdb, I get this error on some input:

```
m5states: duckdb/src/storage/buffer/block_manager.cpp:47: std::shared_ptr<duckdb::BlockHandle> duckdb::BlockManager::ConvertToPersistent(duckdb::block_id_t, std::shared_ptr<duckdb::BlockHandle>): Assertion `new_block->state == BlockState::BLOCK_UNLOADED' failed.
Aborted (core dumped)
```

### To Reproduce

To the best of my attempt, I am unable to shrink down the application to make a reproducible sample. However, the flow is as such:

1. I have a database with very large tables
2. I query and sort everything in a table `SELECT * FROM table_1 ORDER BY tick, id`
3. The query is turned into an iterator via `stmt.query_map`
4. I create an appender on a new table (`table_2`) of the same database with a foreign key reference to `table_1`
5. I stream read the iterator, perform processing, and append result via appender

On some input, I get the assertion error. However, this error doesn't always occur even on the same input.

### OS:

Ubuntu 22.04.3 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

duckdb-rs

### Full Name:

Rongcui Dong

### Affiliation:

University of Rochester

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by gbrian** [comment]
Same case here, my API performs inserts and selects and randomly this error is thrown crashing the app.

```
node: ../src/duckdb/src/storage/buffer/block_manager.cpp:47: std::shared_ptr<duckdb::BlockHandle> duckdb::BlockManager::ConvertToPersistent(duckdb::block_id_t, std::shared_ptr<duckdb::BlockHandle>): Assertion `new_block->state == BlockState::BLOCK_UNLOADED' failed.
```

**Comment by jerrypayerset** [comment]
I am also encountering this issue using Node.js DuckDB v0.81

Here is the error:
```node: ../src/duckdb/src/storage/buffer/block_manager.cpp:47: std::shared_ptr<duckdb::BlockHandle> duckdb::BlockManager::ConvertToPersistent(duckdb::block_id_t, std::shared_ptr<duckdb::BlockHandle>): Assertion `new_block->state == BlockState::BLOCK_UNLOADED' failed.```

This happens intermittently when loading from multiple S3 files at the same time with a `select * from read_parquet(['File1','File2','File3'...]` but it is difficult to reliably reproduce.

**Comment by carlopi** [comment]
We saw similar problems in CI, but they have gone away after a recent storage rework that made it into v0.9.0.

Could you update and check whether you are able to reproduce anymore?

**Comment by jerrypayerset** [comment]
Thanks for the update, I'd like to try it with v0.9.0 but I'm currently blocked from using it because of this issue https://github.com/duckdb/duckdb/issues/9113, which is making it impossible for me to npm install duckdb@0.9.0.
Any idea on when that issue will be fixed?

**Comment by carlopi** [comment]
A way forward is using nightly builds at `npm install duckdb@next`, on the proper node.js package, I hope we will be able to share updates on Monday.
