### ISSUE TITLE
Error when not using fully qualified field name on select AND group by

### ISSUE THREAD

**Issue by alejandrofm** [duckdb/duckdb#8740]
### What happens?

I have a view pointing to parquet file(s).
The SELECT statement has the field prd.ad_stats_v.platform, and is grouped by platform (that only exists on that table)
There I get the error:
```
duckdb.BinderException: Binder Error: column "platform" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(platform)" if the exact value of "platform" is not important.
LINE 6:                 prd.ad_stats_v.platform
```

### To Reproduce

```
conn = duckdb.connect(database='stats.db', read_only=False)
conn.execute("INSTALL httpfs;")
conn.execute("LOAD httpfs;")
#setting credentials here
conn.execute("CREATE SCHEMA IF NOT EXISTS prd;")
conn.execute("CREATE VIEW bds.aux_country_info AS SELECT * FROM read_parquet('s3://data-testing/prd/gamestats/aux_country_info/*');")
conn.execute("CREATE VIEW prd.ad_stats_v AS SELECT * FROM read_parquet('s3://data-testing/prd/gamestats/ad_stats_v/*');")
```
Query:
```
select
		event_date,
		app,
		prd.ad_stats_v.country,
		prd.ad_stats_v.platform
	from
		prd.ad_stats_v
	inner join bds.aux_country_info 
                 on
		lower(bds.aux_country_info.country) = lower(prd.ad_stats_v.country)
	where
		true
	group by
		event_date,
		app,
		prd.ad_stats_v.country,
		platform
```
It works on Redshift/Postgres:
It throws error on duckdb, I have to change the group by
platform to prd.ad_stats_v.platform
to make it work

### OS:

MACOS and Linux x64

### DuckDB Version:

0.81

### DuckDB Client:

python

### Full Name:

Alejandro Martínez

### Affiliation:

Etermax

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, would it be possible to make this reproducible without using S3 authentication? You can e.g. drag and drop a CSV here to the issue / turn it into a GitHub Gist / upload it somewhere else.

**Comment by alejandrofm** [comment]
Hi! have some confidential data there, will try to create a custom file to test. If someone can test it before me please let me know.
Thanks!

**Comment by alejandrofm** [comment]
Hi, here goes the code that throws this error:

```
duckdb.BinderException: Binder Error: column "country" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(country)" if the exact value of "country" is not important.
LINE 1: select event_date, country
                           ^
```

Code:
```
import duckdb

conn = duckdb.connect(database='test.db', read_only=False)

conn.execute("CREATE SCHEMA IF NOT EXISTS prd;")

conn.execute("CREATE VIEW IF NOT EXISTS prd.ad_stats_v AS SELECT * FROM read_csv('test.csv', delim=',', header=True, columns={'event_date': 'DATE', 'app': 'VARCHAR', 'country': 'VARCHAR', 'platform': 'VARCHAR'});")

conn.execute("""select event_date, country
             FROM prd.ad_stats_v
             GROUP by event_date, prd.ad_stats_v.country
             """)
```
file attached
[test.csv](https://github.com/duckdb/duckdb/files/12487074/test.csv)

the full qualified field should be optional, it's ugly to read but should work. On simple queries is easy to find and fix, when queries turn complex it's a not so straightforward issue to debug and the error isn't helping.

**Comment by alejandrofm** [comment]
Add another error, more cryptic this time, any help will be very appreciated. Same CSV/connection as last

Query:

```
SELECT CAST(prd.ad_stats_v.event_date - CAST(datediff('Day', DATE'1990-01-01', prd.ad_stats_v.event_date) % 7 AS INTEGER) AS DATE) AS datefield, max(country) AS value 
   FROM  prd.ad_stats_v 
               WHERE prd.ad_stats_v.event_date >= '2000-01-01' 
               AND prd.ad_stats_v.event_date <= '2025-02-01' 
               GROUP BY strftime(CAST(prd.ad_stats_v.event_date AS DATE), '%Y-%m'), 
                         EXTRACT(year FROM CAST(prd.ad_stats_v.event_date AS DATE)),
                         EXTRACT(month FROM CAST(prd.ad_stats_v.event_date AS DATE)) 
```
I have the same error here:

```
conn.execute("""SELECT CAST(prd.ad_stats_v.event_date - CAST(datediff('Day', DATE'1990-01-01', prd.ad_stats_v.event_date) % 7 AS INTEGER) AS DATE) AS datefield, max(country) AS value 
duckdb.BinderException: Binder Error: column "event_date" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(event_date)" if the exact value of "event_date" is not important.
LINE 1: SELECT CAST(prd.ad_stats_v.event_date - CAST(datedi...

**Comment by alejandrofm** [comment]
It works on other engines (postgres/redshift), but it helps me if we concentrate on this first:
https://github.com/duckdb/duckdb/issues/8740#issuecomment-1701155098
Thanks

**Comment by alejandrofm** [comment]
No resolution for this?

**Comment by Mytherin** [comment]
Thanks for reporting! This is fixed now in https://github.com/duckdb/duckdb/pull/14017
