### ISSUE TITLE
Arrow extension is not available on Windows

### ISSUE THREAD

**Issue by paulrutter** [duckdb/duckdb#8758]
### What happens?

I'm trying to get a JSON import working in Node.js, using Apache Arrow.
When using the following snippet, on Windows:

```
    const duckdb = require('duckdb');
    const arrow = require('apache-arrow');

    const table = arrow.tableFromJSON([
      { 'a': 1, 'b': 4 },
      { 'a': 2, 'b': 5 },
      { 'a': 3, 'b': 6 }
    ]);

    db.exec(`INSTALL arrow; LOAD arrow;`, (err) => {
      if (err) {
        console.error(err);
      }
      db.register_buffer("my_table", [arrow.tableToIPC(table)], true, (err2, res) => {
        if (err2) {
          console.error(err2);
        }
        console.info(res);
      });
    });
```

This fails on loading the `ARROW` extension.

`Failed to download extension "arrow" at URL "http://extensions.duckdb.org/v0.8.1/windows_amd64/arrow.duckdb_extension.gz"`

When executing the same on a unix based system, it works as expected.

### To Reproduce

* When on a Windows based machine: execute the following
* execute `INSTALL arrow; LOAD arrow;`

### OS:

Windows 11

### DuckDB Version:

0.8.1

### DuckDB Client:

Node.js

### Full Name:

Paul Rütter

### Affiliation:

BlueConic

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by paulrutter** [comment]
Related feature request: https://github.com/duckdb/duckdb/discussions/8466

**Comment by carlopi** [comment]
Hi @paulrutter, currently status is that arrow extension do not support Windows builds, so this is expected.

As you saw, there is an open PR (https://github.com/duckdblabs/arrow/pull/18) that aims to fix this that my colleagues that are working in that area will have to review.

In the meantime you can potentially build it yourself and check whether it would work for your needs, it would be valuable feedback.

**Comment by paulrutter** [comment]
@carlopi I tried building it myself, but no luck so far (i'm probably missing some build tools or configuration).
If you (or your colleague) could supply the built extension for Windows, i will try it out on my machine and let you know if it works properly.
