### ISSUE TITLE
Using read_json_auto on a web API triggers "IO Error: HTTP GET error: Content-Length from server mismatches requested range, server may not support range requests."

### ISSUE THREAD

**Issue by ericemc3** [duckdb/duckdb#8761]
### What happens?

Error on a simple read_json_auto call 

### To Reproduce

SELECT * FROM read_json_auto('https://geo.api.gouv.fr/departements/972/communes?fields=nom,code');

### OS:

Win10

### DuckDB Version:

8.1

### DuckDB Client:

DuckDB cli

### Full Name:

eric mauviere

### Affiliation:

icem7

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ericemc3** [comment]
Thank you for the explanation. A dedicated setting to deal with that case would be greatly welcomed, as this geographic API is a govnermental one, and very useful for developping live apps.

**Comment by ericemc3** [comment]
The manager of that API has just updated the server config, upon my request. So the issue is solved. Thank you for the HEAD request hint!

**Comment by carlopi** [comment]
Great, very responsive, amazing.

We might still want to improve handling in this corner case, we will eventually get to it.
