### ISSUE TITLE
Unexpected Constraint Error on UPDATE Query Without Changing Primary Key

### ISSUE THREAD

**Issue by ZhangZiFei** [duckdb/duckdb#8764]
### What happens?

Executing an UPDATE query on a table with both an index and a primary key constraint results in a `Constraint Error`. The error message is: `Duplicate key 'key: key1, name: name1' violates primary key constraint`.

### To Reproduce

```python
import duckdb

# Create an in-memory DuckDB database
con = duckdb.connect(database=':memory:', read_only=False)

# Create table schema
con.execute("""
CREATE TABLE Tag (
  key VARCHAR(65535) NOT NULL,
  name VARCHAR(65535) NOT NULL,
  value VARCHAR(65535) NULL,
  PRIMARY KEY (key, name)
);
CREATE INDEX idx_name ON Tag(name);
CREATE INDEX idx_value ON Tag(value);
""")

# Insert data
con.execute(
    "INSERT INTO Tag (key, name, value) VALUES ('key1', 'name1', 'value1');")

# Update data and catch any exceptions
try:
    con.execute(
        "UPDATE Tag SET value = 'new_value' WHERE key = 'key1' AND name = 'name1';")
    result = "Update successful"
except Exception as e:
    result = str(e)

print(result) # Constraint Error: Duplicate key "key: key1, name: name1" violates primary key constraint.
```

#### Expected Behavior:
The UPDATE query should successfully update the row without any constraint errors.

#### Actual Behavior:
Throws a Constraint Error: `Duplicate key "key: key1, name: name1" violates primary key constraint`.

#### Additional Notes:
The error disappears when the index `idx_value` is removed.

### OS:

Windows x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Zi Fei Zhang

### Affiliation:

Independent Developer

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] Yes, I have

**Comment by ruomad** [comment]
Hello, I have the same issue (using python 0.8.2.dev3092). 
Updating a column with an index fails.
I have to drop the index, update column, recreate the index.
Seems like a bug ?

**Comment by Tishj** [comment]
I think this is a result of behavior described here:
https://duckdb.org/docs/sql/indexes#over-eager-unique-constraint-checking

**Comment by ZhangZiFei** [comment]
> I think this is a result of behavior described here: https://duckdb.org/docs/sql/indexes#over-eager-unique-constraint-checking

It should be like this, I understand.
