### ISSUE TITLE
Error "rowid not found in FROM clause" when cloning database

### ISSUE THREAD

**Issue by ruomad** [duckdb/duckdb#8772]
### What happens?

I tried to clone my database via CLI (.clone)
The process seems to complete but I got this error message 
```
D .clone sm.duckdb
data... done
Error: (0) Binder Error: Referenced column "rowid" not found in FROM clause!
Candidate bindings: "sqlite_schema.sql"
LINE 1: ...ite_schema WHERE type='table' ORDER BY rowid DESC
                                                  ^ on [SELECT name, sql FROM sqlite_schema WHERE type='table' ORDER BY rowid DESC]
```
Indexes are copied after this error.

Also, the cloned db is much (2x) larger than the original (is this expected ?)

### To Reproduce

create database
try to clone it from CLI

### OS:

windows 10 x86_64

### DuckDB Version:

v0.8.2-dev3190

### DuckDB Client:

CLI

### Full Name:

Bruno Damour

### Affiliation:

independent

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
data isn't copied. 
```
~ $ duckdb
v0.7.1 b00b93f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table b as select i,10+i j from range(3)t(i);
D .clone clone
b... Error 0: Binder Error: There are no UNIQUE/PRIMARY KEY Indexes that refer to this table, ON CONFLICT is a no-op on [SELECT * FROM "b"]
done
Error: (0) Binder Error: Referenced column "rowid" not found in FROM clause!
Candidate bindings: "sqlite_schema.sql"
LINE 1: ...ite_schema WHERE type='table' ORDER BY rowid DESC
                                                  ^ on [SELECT name, sql FROM sqlite_schema WHERE type='table' ORDER BY rowid DESC]
D .exit
~ $ duckdb clone
v0.7.1 b00b93f
Enter ".help" for usage hints.
D from b;
┌───────┬───────┐
│   i   │   j   │
│ int64 │ int64 │
├───────────────┤
│    0 rows     │
└───────────────┘
```

**Comment by l1t1** [comment]
https://duckdb.org/docs/api/cli hasn't example of `.clone`
