### ISSUE TITLE
Segmentation fault when importing an exported database.

### ISSUE THREAD

**Issue by mima-hlavacek** [duckdb/duckdb#8797]
### What happens?

When importing exported database containing a `[null, '', null]` entry of type `text[]` (and others, but this is the smallest example), segmentation fault occurs.

### To Reproduce

```
o> begin;
o> create table foo(bar text[]);
o> insert into foo values ([null, '', null]);
o> export database 'foo';
o> rollback;
o> import database 'foo';
Segmentation fault
```

### OS:

Ubuntu x64 in WSL on Windows 11

### DuckDB Version:

0.8.1 and main

### DuckDB Client:

cli and python

### Full Name:

Míma Hlaváček

### Affiliation:

Blindspot.ai

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! I have pushed a fix in #8799.
