### ISSUE TITLE
fetchone transaction issue

### ISSUE THREAD

**Issue by dacosnguyen** [duckdb/duckdb#8801]
### What happens?

Creating a transaction after calling the `fetchone()` causes 
```
duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: TransactionContext Error: cannot start a transaction within a transaction
```
However, it doesn't look like a normal transaction to me because:
- This _can_ be fixed by just adding `begin()` before the `fetchone()`.
- This _cannot_ be fixed by adding `commit()` after the `fetchone()`.

### To Reproduce

```
conn = duckdb.connect()
conn.sql("create table t (a int)")
rel = conn.sql("select 1;")
# conn.begin()  # can be fixed by just adding this line (without commit()), but this would confuse developers even more.
res = rel.fetchone()
# conn.commit() # doesn't work
conn.sql("truncate t; insert into t values (1)")
```

### OS:

MacOS ARM64

### DuckDB Version:

v0.8.1

### DuckDB Client:

Python

### Full Name:

Nguyen

### Affiliation:

Dacos

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
It's caused by the use of `PendingQuery` internally when you have multiple statements inside a single query.

Changing it to separate queries works around the issue
```py
import duckdb

conn = duckdb.connect()
conn.sql("create table t (a int)")
rel = conn.sql("select 1;")
# conn.begin()  # can be fixed by just adding this line (without commit()), but this would confuse developers even more.
res = rel.fetchone()
# conn.commit() # doesn't work
conn.sql("truncate t")
conn.sql("insert into t values (1)")
rel = conn.sql("select * from t")
res = rel.fetchall()
print(res)
```

But I agree, this shouldn't happen
