### ISSUE TITLE
from_df() throws `No module named 'pandas.core.arrays.arrow.dtype'` for pandas 2.1.0.

### ISSUE THREAD

**Issue by nsthorat** [duckdb/duckdb#8802]
### What happens?

Pandas 2.1.0 throws an exception, where 2.0.3 does not:

```
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

### To Reproduce

In a clean virtual env:
`pip install duckdb pandas`

```
>>> import duckdb
>>> import pandas as pd
>>> df = pd.DataFrame.from_dict([{'a': 2}])
>>> con = duckdb.connect(database=':memory:').cursor()
>>> con.from_df(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
>>> pd.__version__
'2.1.0'
>>>
```

However, in version 2.0.3 there is no issue:

`pip install duckdb pandas==2.0.3`

```
Python 3.9.6 (default, May  7 2023, 23:32:44)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> import pandas as pd
>>> df = pd.DataFrame.from_dict([{'a': 2}])
>>> con = duckdb.connect(database=':memory:').cursor()
>>> con.from_df(df)
┌───────┐
│   a   │
│ int64 │
├───────┤
│     2 │
└───────┘

>>> pd.__version__
'2.0.3'
>>>
```

### OS:

Mac OS

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Nikhil Thorat

### Affiliation:

Lilac

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
https://github.com/duckdb/duckdb/pull/8738

**Comment by nsthorat** [comment]
Thanks!

**Comment by Tishj** [comment]
https://duckdb.org/dev/release-dates.html 👍

**Comment by machow** [comment]
How do the release dates work? I see 0.9.0, but there are several 0.8.2 dev releases on PyPI. Does that mean the next release will be 0.9.0 (and just skip a 0.8.2 non-dev release)?

**Comment by Mause** [comment]
> How do the release dates work? I see 0.9.0, but there are several 0.8.2 dev releases on PyPI. Does that mean the next release will be 0.9.0 (and just skip a 0.8.2 non-dev release)?

That's correct yes
