### ISSUE TITLE
Projection of unique columns returns columns with names that don't exist

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#8803]
### What happens?

Selecting columns from a projection whose names are equivalent up to but not including case results in the introduction of columns that don't exist.

### To Reproduce

Using the DuckDB CLI:

```
D select 1 as "A", 2 as "a";
┌───────┬───────┐
│   A   │   a   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     2 │
└───────┴───────┘
D select * from (select 1 as "A", 2 as "a");
┌───────┬───────┐
│   A   │  a:1  │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     2 │
└───────┴───────┘
```

### OS:

NixOS Linux, x86_64, kernel version 6.1.51

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
https://github.com/duckdb/duckdb/pull/8806 solves (or allows to move further) the packaging of extensions.

CI non-deterministic failures not yet

**Comment by Mytherin** [comment]
Thanks for the report! This is intentional behavior.

DuckDB treats all identifiers as case insensitive but maintains the original case, that is to say, `a` and `A` are considered equivalent in the system. 

Query results can contain the same column name multiple times, hence the following query works fine: 

```sql
D select 1 as "A", 2 as "a";
┌───────┬───────┐
│   A   │   a   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     2 │
└───────┴───────┘
```

Subqueries however require all column names to be unique. The numbers are added to disambiguate duplicate column names in the same manner that SQLite does:

```sql
sqlite> select * from (select 1 as "A", 2 as "a");
A  a:1
-  ---
1  2  
```

We could consider introducing a strict mode that instead throws an exception if duplicate column names are encountered if that is helpful.

**Comment by cpcloud** [comment]
Interesting!

This is quite a notable break from postgres, which does support this without renaming. Does this need to be documented somewhere?

**Comment by cpcloud** [comment]
Preferable would be to support the use case without renaming, but I'll take a strict mode option if that's all that's possible!

**Comment by Mytherin** [comment]
> Interesting!
> 
> This is quite a notable break from postgres, which does support this without renaming. Does this need to be documented somewhere?

Postgres has different case-sensitivity rules than DuckDB. Postgres is not case insensitive (i.e. `"a"` and `"A"` are different identifiers) but in SQL it lower-cases all identifiers that are not quoted, so (so `A` is transformed into `a`). We initially used this system as well - but the automatic lower-casing of unquoted identifiers caused a lot of problems for many users when interacting with systems that are not case insensitive (like Pandas) so we modified our case-sensitivity rules to what we have now (see #2075).

**Comment by cpcloud** [comment]
I see. I guess this is a case of "you can't please everybody" 😂

**Comment by cpcloud** [comment]
@Mytherin If you can bear with me for a moment, I am having some trouble understanding the behavior here.

> DuckDB treats all identifiers as case insensitive but maintains the original case, that is to say, a and A are considered equivalent in the system.

Does this mean that quoting has no effect when identifiers are case-insensitively equal, but has as an effect when they are not case-insensitively equal?

**Comment by Mytherin** [comment]
Quoting has no effect outside of allowing you to enter identifier that are e.g. keywords or contain spaces/other special characters, i.e. these are all the same identifier: `identifier` = `IDENTIFIER` = `"IdEnTiFieR"`
