### ISSUE TITLE
Import from /dev/stdin

### ISSUE THREAD

**Issue by mrayva** [duckdb/duckdb#8808]
### What happens?

Import from /dev/stdin does not appear to be working

### To Reproduce

c:\temp\duckdb>cat TEST.csv | duckdb -c "SELECT * FROM read_csv_auto('/dev/stdin')"
Error: IO Error: No files found that match the pattern "/dev/stdin"

c:\temp\duckdb>cat TEST.json | duckdb -c "SELECT * FROM read_json_auto('/dev/stdin')"
Error: IO Error: No files found that match the pattern "/dev/stdin"

### OS:

Windows 10

### DuckDB Version:

0.8.1

### DuckDB Client:

cli

### Full Name:

Michael Ryava

### Affiliation:

none

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
I have not been able to reproduce on MacOS using either v0.8.1 or main, might be a Windows specific issue.

One thing to note is that there are appropriate tests here https://github.com/duckdb/duckdb/blob/main/tools/shell/shell-test.py that are run as part of every build, and they should perform a very similar work.

---
One question:
If if run copy the file from here: https://raw.githubusercontent.com/duckdb/duckdb/main/tools/shell/shell-test.py, and run it like
```
python3 shell-test.py duckdb.exe
```
does it work for you?

**Comment by mrayva** [comment]
main/tools/shell/shell-test.py  worked fine.
it even worked fine under WSL2.... but not under Windows cmd.exe !  Tried two different windows boxes:
type <some-json-file.json> | duckdb -c "SELECT * FROM read_json_auto('/dev/stdin')"

**Comment by Mause** [comment]
This is somewhat expected on windows, as the special `/dev/stdin` file is specific to Linux/MacOS. The equivalent on windows is apparently "named pipes", but you have to create them manually using a weird API, and they have a special prefix `\\.\pipe\`

**Comment by hannes** [comment]
Indeed this is expected behaviour.

**Comment by mrayva** [comment]
A follow up question, if I may...

Piping from static json files clearly works, but what about piping from another binary that is continuously writing json record to STDOUT ? I don't observe any of such records being persisted by duckdb. What am I misisng?

**Comment by kpym** [comment]
It would be nice if there were a special filename for stdin that is platform-independent. This feature would make it easier on all platforms to read data from stdin into DuckDB without requiring platform-specific workarounds.

For example, the following command should work seamlessly across different operating systems (Windows included):
```bash
cat mydata.csv | duckdb mydb "create table mytable as select * from read_csv_auto(stdin, HEADER=TRUE);" 
```

**Comment by carlopi** [comment]
There is a [community extension](https://duckdb.org/2024/07/05/community-extensions.html) that might help with this: [shellfs](https://community-extensions.duckdb.org/extensions/shellfs.html)
```
carlo@ScroogeMcDuck duckdb % duckdb
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
FORCE INSTALL shellfs;
LOAD shellfs;
SUMMARIZE FROM read_csv('cat data/csv/weather.csv |');
┌─────────────────────┬─────────────┬────────────┬────────────┬───┬─────────┬───────┬─────────────────┐
│     column_name     │ column_type │    min     │    max     │ … │   q75   │ count │ null_percentage │
│       varchar       │   varchar   │  varchar   │  varchar   │   │ varchar │ int64 │  decimal(9,2)   │
├─────────────────────┼─────────────┼────────────┼────────────┼───┼─────────┼───────┼─────────────────┤
│ date                │ DATE        │ 2016-01-01 │ 2016-12-31 │ … │         │   366 │            0.00 │
│ maximum_temperature │ BIGINT      │ 15         │ 96         │ … │ 81      │   366 │            0.00 │
│ minimum_temperature │ BIGINT      │ -1         │ 81         │ … │ 65      │   366 │            0.00 │
│ average_temperature │ DOUBLE      │ 7.0        │ 88.5       │ … │ 73.6875 │   366 │            0.00 │
│ precipitation       │ VARCHAR     │ 0          │ T          │ … │         │   366 │            0.00 │
│ snow_fall           │ VARCHAR     │ 0          │ T          │ … │         │   366 │            0.00 │
│ snow_depth          │ VARCHAR     │ 0          │ T          │ … │         │   366 │            0.00 │
├─────────────────────┴─────────────┴────────────┴────────────┴───┴─────────┴───────┴─────────────────┤
│ 7 rows                                                                         12 columns (7 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by kpym** [comment]
> SUMMARIZE FROM read_csv('cat data/csv/weather.csv |');

The problem with this approach is that I have to specify the filename inside the SQL script, which is what I want to avoid.
Thanks in any case for your suggestion.

**Comment by graphixillusion** [comment]
So is this still not supported under Windows ?

cat mydata.csv | duckdb mydb "create table mytable as select * from read_csv_auto(stdin, HEADER=TRUE);"
