### ISSUE TITLE
Always error when using CSV Auto Detection

### ISSUE THREAD

**Issue by florentfgrs** [duckdb/duckdb#8815]
### What happens?

I systematically get this error when I use read_csv_auto : 
`Error: IO Error: No files found that match the pattern "~/flights.csv"`

I have the same problem with the ten or so csvs I have tested  and even with the documentation's demonstration csv.

### To Reproduce

1. Create csv file with [example](https://duckdb.org/docs/data/csv/auto_detection.html) 

flights.csv
```
FlightDate|UniqueCarrier|OriginCityName|DestCityName
1988-01-01|AA|New York, NY|Los Angeles, CA
1988-01-02|AA|New York, NY|Los Angeles, CA
1988-01-03|AA|New York, NY|Los Angeles, CA
```

2. Launch duckdb cli

```
./duckdb
```

4. Open database 

```
D .open ~/test.db
```

5. Run import with read_csv_auto
```
D CREATE TABLE flights AS FROM read_csv_auto('~/flights.csv', HEADER=True, DELIM='|');  
```

6. Log error 

```
Error: IO Error: No files found that match the pattern "~/flights.csv"
```

### OS:

Linux Kubuntu 22.04

### DuckDB Version:

0.8.2

### DuckDB Client:

CLI

### Full Name:

Florent

### Affiliation:

Oslandia

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Can you please specify which exact DuckDB version you tried with?

**Comment by florentfgrs** [comment]
@Mause I installed duckdb via github main bleeding edge so I "m using the most recent version, v0.8.2-dev3989.

**Comment by Mause** [comment]
> @Mause I installed duckdb with github main bleeding edge so I'm using the most recent version, v0.8.2-dev3989.

Can you try if you see the issue with a path that doesn't contain Téléchargements?

**Comment by szarnyasg** [comment]
I ran the MWE instructions on Ubuntu 22.04 in Docker and it worked fine:

```bash
root@d7ec845a943e:/duckdb# build/release/duckdb
v0.8.2-dev4018 6eddf2c74a
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .open ~/test.db
D CREATE TABLE flights AS FROM read_csv_auto('~/flights.csv', HEADER=True, DELIM='|');
D
```

**Comment by szarnyasg** [comment]
@florentfgrs I don't see any commands in your latest comment - are they missing by accident?
I just build the latest `main` branch, so my version is likely slightly newer. Can you try with the latest `main` branch?

**Comment by florentfgrs** [comment]
I've just found the problem, it's not the duckdb version that's the problem (I had the problem even with the build from main). 
For this to work, I need to launch duckdb in super user mode with sudo. It's surprising, but it works like this

**Comment by florentfgrs** [comment]
Same file, same commands.. 

**Without sudo**

![image](https://github.com/duckdb/duckdb/assets/36446612/978bfc85-4eb2-47f8-a9a2-5e63a5b4dc15)


**With sudo**

![image](https://github.com/duckdb/duckdb/assets/36446612/a4d792f9-3a40-44d5-a72c-ecb84dfac30b)

**Comment by florentfgrs** [comment]
So I thought it was a problem with the rights to the flights.csv file, but after checking, that's not it.

**Comment by szarnyasg** [comment]
Are the permissions for `the_db.db` good, i.e. can your user write it? The command
```
sudo chown forent:florent `~/Téléchargements/the_db.db ~/flights.csv
```
should ensure that it can.

**Comment by florentfgrs** [comment]
Yes, I do have the rights to do a simple `CREATE TABLE`

**Comment by szarnyasg** [comment]
This is strange. Do you have SELinux or a similar security module turned on? Can your DuckDB read other files?
E.g. if you create `~/hello.sql` whose content is:
```bash
SELECT 42 AS x
```

Does the following command work?
```bash
.read ~/hello.sql
```

**Comment by florentfgrs** [comment]
I don't have SELinux or anything like that. 

Can't work : 

`Error: cannot open "~/hello.sql"`

But I don't understand why my user owns the hello.sql file.

```
-rw-rw-r--  1 florent florent     16 sept.  6 16:23 hello.sql
```

**Comment by szarnyasg** [comment]
This points towards a permission issue in your setup.

> But I don't understand why my user owns the hello.sql file.

What other user do you expect to own this file instead of your user?

**Comment by szarnyasg** [comment]
No problem, good luck debugging this!
