### ISSUE TITLE
Can not create scalar function in a C++ program

### ISSUE THREAD

**Issue by mozz3** [duckdb/duckdb#8850]
### What happens?

On my MacBook Pro, I wrote a C++ program that links against duckdb dylib version 0.8.1. Everything is working well but when I called CreateScalarFunction method of duckdb::Connection class, I am getting following linking error 

Undefined symbols for architecture x86_64:
  "duckdb::UDFWrapper::RegisterFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<duckdb::LogicalType, std::__1::allocator<duckdb::LogicalType> >, duckdb::LogicalType, std::__1::function<void (duckdb::DataChunk&, duckdb::ExpressionState&, duckdb::Vector&)>, duckdb::ClientContext&, duckdb::LogicalType)", referenced from:
      void duckdb::UDFWrapper::RegisterFunction<bool, int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (duckdb::DataChunk&, duckdb::ExpressionState&, duckdb::Vector&)>, duckdb::ClientContext&, duckdb::LogicalType) in main.o

### To Reproduce

1. Write a C/C++ console program
2. Define a function as defined below (above the C++ main function)
      `bool bigger_than_four(int value) {
    return value > 4;
}`
3. Inside C++ main function, Create DuckDB connection class object and create scalar UDF as in the below code

`duckdb::DBConfig dbConfig;

dbConfig.SetOptionByName("max_memory", strMaxMemory);
duckdb::DuckDB db(dbFilePath, &dbConfig);
duckdb::Connection con(db);
//Define scalar UDF and register with duckdb
con.CreateScalarFunction<bool, int>("bigger_than_four", &bigger_than_four);
std::cout<<"Connection to DB created successfully"<<std::endl;`

5. Compile the program, it will give linking error: Undefined symbols for architecture x86_64:
  "duckdb::UDFWrapper::RegisterFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<duckdb::LogicalType, std::__1::allocator<duckdb::LogicalType> >, duckdb::LogicalType, std::__1::function<void (duckdb::DataChunk&, duckdb::ExpressionState&, duckdb::Vector&)>, duckdb::ClientContext&, duckdb::LogicalType)", referenced from:
      void duckdb::UDFWrapper::RegisterFunction<bool, int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (duckdb::DataChunk&, duckdb::ExpressionState&, duckdb::Vector&)>, duckdb::ClientContext&, duckdb::LogicalType) in main.o

Please note that I used XCODE IDE to create C++ console app

### OS:

Mac OS 13.1

### DuckDB Version:

0.8.1

### DuckDB Client:

C++ Console app

### Full Name:

Mozz

### Affiliation:

Self

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
How are you linking the two, and are you using the right header for the version of DuckDB that you're using?

PS. Can you please format your code using the correct Github syntax? See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by mozz3** [comment]
Issue is resolved, code was pointing to the wrong header files

**Comment by yiivon** [comment]
> Issue is resolved, code was pointing to the wrong header files

Hi, would you like to show me how to resolved this problem? i meet it as well.
