### ISSUE TITLE
querying empty and non-empty unnested lists over multiple json  files fails but succeeds when files concatenated together (or reordered)

### ISSUE THREAD

**Issue by robert-manchester** [duckdb/duckdb#8865]
### What happens?

this example is trimmed down from the gcov json output. When querying a list of json files, if a file containing an empty list is at the beginning of the list of files this query fails.

```sql
with
files as (
  select
    unnest(files, recursive := true)
  from
    '*.json'
),
lines as (
  select
    unnest(lines, recursive := true),
    file
  from
    files
)
select
  file,
  sum(count)
from
  lines
group by
  file
order by
  sum(count) desc
```
```
Error: near line 1: Binder Error: Referenced column "count" not found in FROM clause!
Candidate bindings: "lines.file"
LINE 17:   sum(count)
```

where
```sh
cat a.json
```
```json
{
  "files": [
    {
      "lines": [],
      "file": "exception.hpp"
    }
  ]
}
```
```sh
cat b.json
```
```json
{
  "files": [
    {
      "lines": [
        {
          "count": 4,
          "line_number": 6
        }
      ],
      "file": "copied_statement_verifier.cpp"
    }
  ]
}
```

however, can workaround the problem by concatenating the json files (or reordering).
```sh
#!/bin/bash

cat a.json b.json > c.json
duckdb <<SQL
with
files as (
  select
    unnest(files, recursive := true)
  from
    'c.json'
),
lines as (
  select
    unnest(lines, recursive := true),
    file
  from
    files
)
select
  file,
  sum(count)
from
  lines
group by
  file
order by
  sum(count) desc
SQL
```
|             file              | sum(count) |
|-------------------------------|------------|
| copied_statement_verifier.cpp | 4          |

### To Reproduce

```bash
#!/bin/bash

cd $(mktemp -d) || exit $?
echo using $PWD

cat > a.json <<JSON
{
  "files": [
    {
      "lines": [],
      "file": "exception.hpp"
    }
  ]
}
JSON

cat > b.json <<JSON
{
  "files": [
    {
      "lines": [
        {
          "count": 4,
          "line_number": 6
        }
      ],
      "file": "copied_statement_verifier.cpp"
    }
  ]
}
JSON

duckdb <<SQL
with
files as (
  select
    unnest(files, recursive := true)
  from
    '*.json'
),
lines as (
  select
    unnest(lines, recursive := true),
    file
  from
    files
)
select
  file,
  sum(count)
from
  lines
group by
  file
order by
  sum(count) desc
SQL
```

### OS:

Ubuntu 22.04.3 LTS x64

### DuckDB Version:

v0.8.2-dev4142 d5c4422f72

### DuckDB Client:

cli

### Full Name:

rob m

### Affiliation:

unaffiliated

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Beautiful reproduction script, thanks!

**Comment by lnkuiper** [comment]
Hi @robert-manchester, thanks for the bug report. This is expected behavior, however. If you query multiple JSON files, DuckDB will sample the first file to detect the schema and then assume the other files have the same schema.

DuckDB samples `a.json` here first, which does not contain `count`, so DuckDB cannot use it as a column in the query plan. You can sample all files in your query by using our [`union_by_name`](https://duckdb.org/docs/data/multiple_files/combining_schemas.html) parameter.

Your query will then be:
```sql
with files as (
  select
    unnest(files, recursive := true)
  from
    read_json_auto('*.json', union_by_name=true)
),
lines as (
  select
    unnest(lines, recursive := true),
    file
  from
    files
)
select
  file,
  sum(count)
from
  lines
group by
  file
order by
  sum(count) desc;
```

**Comment by robert-manchester** [comment]
thanks @lnkuiper. defaulting to union_by_name is slightly (1.4x) faster than just concatenating the files together, but globbing is 5.5x faster than defaulting to union_by_name if the first file doesn't contain an empty list.

my preference would be the json parser sample at least x lines, possibly across files if necessary, rather than just using the first file.

the problem for me is that the smallest file is likely going to be the first file written to the directory. there are many processes working in parallel to write out the json data and the process with the least amount of work to do will likely be the first to write out the file. Thus the first file in the list is not going to be a representative sample of the whole.

anyway, i'm pretty happy with how easy it is to query these json files. it's super handy.

**Comment by lnkuiper** [comment]
I've thought about this a bit @robert-manchester, and I agree that our default sampling strategy (that we also use for CSV/Parquet) does not work as well for JSON, since it is common to have many small JSON files. I've changed our sampling strategy in #8891, which makes your query work with our default settings, i.e., just querying `'*.json'`.

**Comment by robert-manchester** [comment]
thanks @lnkuiper! tried it out and it works great! thank you!

i am not sure how representative the dataset i am looking at is -- it is the [gcov](https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html) output [gcov.tar.gz](https://github.com/duckdb/duckdb/files/12584683/gcov.tar.gz) of one test from a duckdb coverage run -- but each file only contains 1 row but many nested rows. So a sample_size using bytes would work better than rows. using the default sample_size the behavior / performance is identical to using the union_by_name flag as all files will be searched. If the sample size was something like 1MB that would work better in this case.

**Comment by lnkuiper** [comment]
I think it is more intuitive for our users to figure out "How many rows do I need to figure out the schema" vs. "How many bytes do I need to figure out the schema", when configuring the `sample_size` parameter. If you have many files containing one large row this is not the best, but in the cases where there are multiple rows per file, this will be good. In your case, you can set, e.g., `sample_size=100`.

**Comment by robert-manchester** [comment]
having the default in bytes and only using sample_size, if set, as rows perhaps. though the trade off in code complexity might not be worth it.

other than my use case, folks using column-oriented json also have one row per file, i think.

anyway, sample_size=4 i think works for the 2.5k gcov outputs and saves something like 25 minutes over the default setting though is not quite as robust.
