### ISSUE TITLE
Undocumented dependency of zstd compression on Parquet extension

### ISSUE THREAD

**Issue by Taepper** [duckdb/duckdb#8895]
### What happens?

Neither the documentation of e.g. [CSV Loading](https://duckdb.org/docs/data/csv/overview) and [JSON Loading](https://duckdb.org/docs/data/json/overview), nor the produced error message ["Attempting to open a compressed file, but the compression type is not supported"](https://github.com/duckdb/duckdb/blob/312b9954507386305544a42c4f43c2bd410a64cb/src/common/virtual_file_system.cpp#L38) mention the dependency on the parquet extension.

This issue is probably uncommon, as parquet is often built-in for many installations.

This could be handled similar to other extension as [suggested by carlop](https://discord.com/channels/909674491309850675/921100573732909107/1151133561399808051)

### To Reproduce

```

    duckdb::DuckDB db(nullptr);
    duckdb::Connection connection(db);
    auto result = connection.Query("SELECT * FROM read_csv_auto('test.csv.zst', HEADER=TRUE);");
    std::cout << result->ToString() << std::endl;
    result = connection.Query("SELECT * FROM read_csv_auto('test.csv.zst', HEADER=TRUE, COMPRESSION='zstd');");
    std::cout << result->ToString() << std::endl;
```

Output:
`Not implemented Error: Attempting to open a compressed file, but the compression type is not supported`
`Not implemented Error: Attempting to open a compressed file, but the compression type is not supported`

### OS:

iOS

### DuckDB Version:

0.8.1

### DuckDB Client:

C++ API

### Full Name:

Alexander Taepper

### Affiliation:

ETH Zurich

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] Yes, I have

**Comment by carlopi** [comment]
For completeness, my suggestion on Discord was:
> We should probably handle this case similarly to others treated in [extension_entries.hpp](https://github.com/duckdb/duckdb/blob/312b9954507386305544a42c4f43c2bd410a64cb/src/include/duckdb/main/extension_entries.hpp#L223)
So that when parquet is not packaged the error message will point to the extension (and with autoloading enabled it will try to load it on first use)
