### ISSUE TITLE
Calling duckdb_rows_changed causes data chunk to return invalid data

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb#8905]
### What happens?

If you have a `duckdb_result` instance and call `duckdb_rows_changed` with it, subsequent calls to `duckdb_result_get_chunk` return an empty pointer. If I reorder calls everything works as expected. I would expect order not to have affect on the return value of `duckdb_result_get_chunk`

![image](https://github.com/duckdb/duckdb/assets/580749/5d359202-7fea-4eb7-a830-d73f2b195874)

Works fine if I change the order
![image](https://github.com/duckdb/duckdb/assets/580749/92e980d5-7e68-4dec-9340-9afc7c9b9e49)

### To Reproduce

Obtain `duckdb_result` instance and call `duckdb_rows_changed` followed by a call to `duckdb_result_get_chunk`

### OS:

Windows 11 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

C# client via C API

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
They are not part of the same API
`rows_changed` will call:
```
        if (!duckdb::deprecated_materialize_result(result)) {
```
otherwise it can't give you an answer, the result could be streaming

**Comment by Giorgi** [comment]
In that case, how do I get the number of `rows_changed` without using a deprecated API?

**Comment by Tishj** [comment]
Looks like you need `duckdb_row_count`
And yes I agree this is extremely confusing

**Comment by Giorgi** [comment]
If I have an `Update` statement how do I get the number of changed rows? `duckdb_row_count` returns 1.

**Comment by Tishj** [comment]
For an update statement that's the data that's returned, it returns 1 because it produces 1 tuple/row - that tuple is a BIGINT of the number of changed rows.

For RETURNING the output of `duckdb_row_count` would be what you're looking for because for every affected row you get one tuple/row

**Comment by Giorgi** [comment]
So if previously I could use `duckdb_rows_changed` to find the number of changed rows, now I have to read the first item of the first row to get it right?

**Comment by Giorgi** [comment]
I checked the source code and the two other functions that call `deprecated_materialize_result` are `duckdb_column_data` and `duckdb_nullmask_data`. Both of them [are documented](https://duckdb.org/docs/api/c/query) as **DEPRECATED** but `duckdb_rows_changed` isn't. I would send a PR to mark it as DEPRECATED but I don't know what to suggest as an alternative.
