### ISSUE TITLE
Select column name with double quote (")

### ISSUE THREAD

**Issue by handstuyennn** [duckdb/duckdb#8926]
### What happens?

I couldn't run query with double quote `"` character.

### To Reproduce

I ran following queries

1. CREATE VIEW duckdb_optimized__14 AS SELECT {name: 1};

2. SELECT column_name, data_type FROM information_schema.columns WHERE table_name='duckdb_optimized__14';

<img width="410" alt="Screen Shot 2023-09-14 at 10 24 12" src="https://github.com/duckdb/duckdb/assets/49063786/c6349e95-6502-4359-bc5c-809568f0cb49">

I couldn't run select query with column name `main.struct_pack("name" := 1)` because they have `"` character

3. SELECT "main.struct_pack("name" := 1)" from duckdb_optimized__14;

<img width="533" alt="Screen Shot 2023-09-14 at 10 25 53" src="https://github.com/duckdb/duckdb/assets/49063786/32708b03-b699-4140-b16b-da7a2974c0dc">

### OS:

MacOS

### DuckDB Version:

0.8.1

### DuckDB Client:

duckdb-shell

### Full Name:

Tuyen Nguyen Ngoc

### Affiliation:

IHands

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Can you try

```sql
SELECT "main.struct_pack(""name"" := 1)" from duckdb_optimized__14;
```

Doubling up the quotes is how you escape them, same as you do for strings with single quotes

**Comment by l1t1** [comment]
both works
```sql
D SELECT "main.struct_pack(""name"" := 1)" from duckdb_optimized__14;
┌───────────────────────────────┐
│ main.struct_pack("name" := 1) │
│    struct("name" integer)     │
├───────────────────────────────┤
│ {'name': 1}                   │
└───────────────────────────────┘
D SELECT main.struct_pack("name" := 1) from duckdb_optimized__14;
┌───────────────────────────────┐
│ main.struct_pack("name" := 1) │
│    struct("name" integer)     │
├───────────────────────────────┤
│ {'name': 1}                   │
└───────────────────────────────┘
```

**Comment by l1t1** [comment]
you should give a name/alias to the column

**Comment by Mause** [comment]
> both works
> ```sql
> D SELECT "main.struct_pack(""name"" := 1)" from duckdb_optimized__14;
> ┌───────────────────────────────┐
> │ main.struct_pack("name" := 1) │
> │    struct("name" integer)     │
> ├───────────────────────────────┤
> │ {'name': 1}                   │
> └───────────────────────────────┘
> D SELECT main.struct_pack("name" := 1) from duckdb_optimized__14;
> ┌───────────────────────────────┐
> │ main.struct_pack("name" := 1) │
> │    struct("name" integer)     │
> ├───────────────────────────────┤
> │ {'name': 1}                   │
> └───────────────────────────────┘
> ```

The second one here is actually just calling struct_pack again, not referencing the column

**Comment by handstuyennn** [comment]
> Can you try
> 
> ```sql
> SELECT "main.struct_pack(""name"" := 1)" from duckdb_optimized__14;
> ```
> 
> Doubling up the quotes is how you escape them, same as you do for strings with single quotes

Thanks for your help
