### ISSUE TITLE
Week Function is Givig Incorrect week of the year

### ISSUE THREAD

**Issue by arunksoman** [duckdb/duckdb#8934]
### What happens?

Duckdb week function is giving incorrect week of the year.

### To Reproduce

```sql
SELECT week(DATE '2024-12-31');
```
I expect here result of query should be 51 to 53. But it is giving 1 which is incorrect

![image](https://github.com/duckdb/duckdb/assets/42168602/5413dc00-c458-40cc-9ea5-bd4718b73211)

### OS:

Windows

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Arun K Soman

### Affiliation:

Nothing

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ned2** [comment]
Weeks don't divide up neatly into days of the year, so there's always going to be some weirdness with week numbers around the start/end  of years. I'm guessing that DuckDB uses the ISO week date to manage the weirdness. 

> If 1 January is on a Monday, Tuesday, Wednesday or Thursday, it is in W01. If it is on a Friday, it is part of W53 of the previous year. If it is on a Saturday, it is part of the last week of the previous year which is numbered W52 in a common year and W53 in a leap year. If it is on a Sunday, it is part of W52 of the previous year.
https://en.wikipedia.org/wiki/ISO_week_date

**Comment by hawkfish** [comment]
This is correct because we return ISO week numbers. This is the same behaviour as Postgres:

```sql
hawkfish=# SELECT EXTRACT('week' FROM DATE '2024-12-31');
 extract 
---------
       1
(1 row)
```

(The `week` function is just a synonym for `DATE_PART` and `EXTRACT`).
