### ISSUE TITLE
[nodejs] arrowIPCAll crashes on a query with UNION ALL and ORDER BY

### ISSUE THREAD

**Issue by pmm-motif** [duckdb/duckdb#8944]
### What happens?

When Node.js API is used via `arrowIPCAll` on a query which includes ORDER BY and UNION ALL, the library crashes. This seems to be related to #7988, which fixed some occurrences of the problem. However it seems to still happen on build `0.8.2-dev4474`

### To Reproduce

Example test which showcases the problem

```typescript
import { tableFromIPC, tableFromJSON, tableToIPC } from 'apache-arrow';
import { Database } from 'duckdb';

const db = new Database(':memory:');

const tableAsJson = [
  {
    col: 'A',
  },
];

const q = `
WITH data_union AS (
    SELECT * FROM data
    UNION ALL
    SELECT * FROM data
)

SELECT * FROM data_union ORDER BY col
`;

describe('duckdb', () => {
  it('does not get killed', () => {
    const arrowTable = tableFromJSON(tableAsJson);
    db.exec(`INSTALL arrow; LOAD arrow;`, (err, _res) => {
      if (err) {
        throw err;
      }
      db.register_buffer(
        'data',
        [tableToIPC(arrowTable)],
        true,
        (err, _res) => {
          if (err) {
            throw err;
          }
          db.arrowIPCAll(q, (err, res) => {
            if (err) {
              throw err;
            }
            console.error(tableFromIPC(res).toString());
          });
        }
      );
    });
  });
});
```

### OS:

macOS

### DuckDB Version:

0.8.2-dev4474

### DuckDB Client:

Node.js

### Full Name:

Przemek Maciolek

### Affiliation:

Motif Analytics

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by srschandan** [comment]
Issue exists in 0.9.0 as well (and 0.9.1-dev95.0 - last I checked). Here's a gist for reproducing this using an actual data with a simple-ish query: https://gist.github.com/srschandan/ed759f6414e0afd481dc40d685622f0e
