### ISSUE TITLE
WHERE does not filter RANDOM() correctly

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#8948]
### What happens?

```SQL
SELECT
  t0.x
FROM (
  SELECT
    RANDOM() AS x
) AS t0
WHERE
  t0.x > .5
```
occasionally (about 1/4 the time...) returns results that are less than .5.

Perhaps this is just me misunderstanding the semantics of SQL though. SQlite exhibits the same behavior, which makes me think that I must have this wrong, as this seems so basic. But I find this very very surprising! If it is a bug, I expect it that the RANDOM is getting evaluated at two different places, once for the filter, and then again to actually compute the value.

### To Reproduce

See above.

### OS:

https://shell.duckdb.org/

### DuckDB Version:

Database: v0.8.2-dev1781 Package:  @duckdb/duckdb-wasm@1.27.1-dev59.0

### DuckDB Client:

https://shell.duckdb.org/

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by robert-manchester** [comment]
see also #8441

**Comment by NickCrews** [comment]
Ah, thank you. I saw the -dev suffix in the web shell version so I assumed this was present main. But is this actually present on main? Or did that PR fix it?

**Comment by robert-manchester** [comment]
`pragma version;` at shell.duckdb.org returns 3cba1b0da8 and thus doesn't have the fix yet. it is fixed on main with #8532
disclaimer: i am not involved in the project.

**Comment by NickCrews** [comment]
Thank you for doing that diligence for me. I will close this out then!

**Comment by carlopi** [comment]
Deployment at shell.duckdb.org has been broken and that mean no updates.

I restored the CI that deploys the live DuckDB Wasm shell, and now should be only a week or so behind.

Thanks for raising this, sorry for the issue.
