### ISSUE TITLE
`EXCLUDE` does not yet support fully-qualified field name

### ISSUE THREAD

**Issue by yoonghm** [duckdb/duckdb#8952]
### What happens?

`EXCLUDE` modifier inside a `SELECT` statement does not support `.` specifier.

### To Reproduce

I have the following tables and records:

```SQL
CREATE TABLE weather (
    city    VARCHAR,
    temp_lo INTEGER, -- minimum temperature on a day
    temp_hi INTEGER, -- maximum temperature on a day
    prcp    REAL,
    date    DATE
);

CREATE TABLE cities (
    city VARCHAR,
    lat  DECIMAL,
    lon  DECIMAL
);

INSERT INTO weather VALUES ('San Francisco', 46, 50, 0.25, '1994-11-27'); 
INSERT INTO weather VALUES ('San Francisco', 43, 57, 0.0 , '1994-11-29');
INSERT INTO weather VALUES ('Hayward'      , 54, 37, null, '1994-11-29');

INSERT INTO cities VALUES ('San Francisco', -194.0, 53.0);
```

This SQL query works:

```SQL
SELECT * EXCLUDE (date) FROM weather, cities WHERE weather.city = cities.city;
```

```TEXT
┌───────────────┬─────────┬─────────┬───────┬───────────────┬───────────────┬───────────────┐
│     city      │ temp_lo │ temp_hi │ prcp  │     city      │      lat      │      lon      │
│    varchar    │  int32  │  int32  │ float │    varchar    │ decimal(18,3) │ decimal(18,3) │
├───────────────┼─────────┼─────────┼───────┼───────────────┼───────────────┼───────────────┤
│ San Francisco │      46 │      50 │  0.25 │ San Francisco │      -194.000 │        53.000 │
│ San Francisco │      43 │      57 │   0.0 │ San Francisco │      -194.000 │        53.000 │
└───────────────┴─────────┴─────────┴───────┴───────────────┴───────────────┴───────────────┘
```

However, the following SQL query does not work:

```SQL
SELECT * EXCLUDE (cities.city) FROM weather, cities WHERE weather.city = cities.city;
```

The error is

```TEXT
Error: Parser Error: syntax error at or near "."
LINE 1: SELECT * EXCLUDE (cities.city) FROM weather, cities WHERE weath...
```

### OS:

Windows

### DuckDB Version:

0.8.1

### DuckDB Client:

DuckDB CLI

### Full Name:

Yoong Hor Meng

### Affiliation:

Ngee Ann Polytechnic

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
```sql
D SELECT * EXCLUDE (date) FROM weather join  cities using (city);
┌───────────────┬─────────┬─────────┬───────┬───────────────┬───────────────┐
│     city      │ temp_lo │ temp_hi │ prcp  │      lat      │      lon      │
│    varchar    │  int32  │  int32  │ float │ decimal(18,3) │ decimal(18,3) │
├───────────────┼─────────┼─────────┼───────┼───────────────┼───────────────┤
│ San Francisco │      46 │      50 │  0.25 │      -194.000 │        53.000 │
│ San Francisco │      43 │      57 │   0.0 │      -194.000 │        53.000 │
└───────────────┴─────────┴─────────┴───────┴───────────────┴───────────────┘
```

**Comment by szarnyasg** [comment]
Hi, this is expected behavior at the moment. A possible workaround is the following:

```sql
SELECT weather.*, cities.* EXCLUDE (city) FROM weather, cities WHERE weather.city = cities.city;
```

**Comment by rob-teeuwen** [comment]
Hey guys, just wanted to mention here that this also creates conflicts with the Sqlfluff [references.qualification rule](https://docs.sqlfluff.com/en/stable/rules.html#rule-RF02). According to that rule all references should be qualified when selecting from more than 1 table. Not sure if there's another option for dealing with this, but it's kind of disappointing having to disable the entire rule.

**Comment by mdtino** [comment]
From a UX perspective, seems unexpected that this dialect would fail. What happens if "date" is duplicate across the two tables?

**Comment by szarnyasg** [comment]
There are not plans internally to fix this for the next release, but PRs are welcome.

**Comment by scoobhidu** [comment]
hi everyone
what is the expected behaviour when exclude is used on cities as given in the issue description? should the entire cities column be excluded because subset of cities.city will be the resultant column

**Comment by Tishj** [comment]
> hi everyone what is the expected behaviour when exclude is used on cities as given in the issue description? should the entire cities column be excluded because subset of cities.city will be the resultant column

When we're talking about `EXCLUDE` the `FROM weather, cities WHERE weather.city = cities.city` portion doesn't really matter, that's just the FROM clause that is producing the column references we are projecting.

The problem that is being discussed here is that 2 `city` column references are created:
```
city    temp_lo temp_hi prcp    city    lat     lon
VARCHAR INTEGER INTEGER FLOAT   VARCHAR DECIMAL(18,3)   DECIMAL(18,3)
[ Rows: 2]
San Francisco   46      50      0.25    San Francisco   -194.000        53.000
San Francisco   43      57      0.0     San Francisco   -194.000        53.000
```

One of them originates from `cities` and the other from `weather`:
```
D SELECT * EXCLUDE (date) FROM weather, cities WHERE weather.city = cities.city;
┌───────────────┬─────────┬─────────┬───────┬───────────────┬───────────────┬───────────────┐
│     city      │ temp_lo │ temp_hi │ prcp  │     city      │      lat      │      lon      │
│    varchar    │  int32  │  int32  │ float │    varchar    │ decimal(18,3) │ decimal(18,3) │
├───────────────┼─────────┼─────────┼───────┼───────────────┼───────────────┼───────────────┤
│ San Francisco │      46 │      50 │  0.25 │ San Francisco │      -194.000 │        53.000 │
│ San Francisco │      43 │      57 │   0.0 │ San Francisco │      -194.000 │        53.000 │
└───────────────┴─────────┴─────────┴───────┴───────────────┴───────────────┴───────────────┘
```

The request is to be able to differentiate between the two, if we use `EXCLUDE(city)` both of the columns are excluded.
`EXCLUDE(cities.city)` should only exclude the column that originates from the `cities` table
