### ISSUE TITLE
Issue building with ODBC using WSL running Ubuntu 20.04

### ISSUE THREAD

**Issue by mspruc** [duckdb/duckdb#8976]
### What happens?

I get a build error, while following the guide for ODBC on WSL using ubuntu.

Found a temporary fix in installing unixodbc-dev version instead.

### To Reproduce

Using: 
```
BUILD_ODBC=1 make -j16
```

I get:
```
-- Could NOT find ODBC (missing: ODBC_LIBRARY ODBC_INCLUDE_DIR)
CMake Error at tools/odbc/CMakeLists.txt:6 (message):
  NoODBCfound
```

While: 
Following the ODBC guide https://duckdb.org/docs/api/odbc/windows

### OS:

windows 10, x64

### DuckDB Version:

0.8.1 as on installation page

### DuckDB Client:

C++

### Full Name:

Mads

### Affiliation:

Student @ITU copenhagen

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by maiadegraaf** [comment]
That error occurs when the compiler cannot find an ODBC library (i.e. unixODBC), so installing `unixodbc-dev` is correct. Although I admit a more detailed error message could be useful here.
