### ISSUE TITLE
`partition_by` is slow and goes OOM, but writing partitions manually works

### ISSUE THREAD

**Issue by jonashaag** [duckdb/duckdb#8981]
### What happens?

If I use something like

```sql
COPY tbl TO '...' (FORMAT PARQUET, PARTITION_BY col)
```

with 10 partitions, it goes OOM after 1 h.

If I manually set the partitions with

```sql
COPY (SELECT * FROM tbl WHERE col = v1) TO '...' (FORMAT PARQUET, PARTITION_BY col, OVERWRITE_OR_IGNORE)
COPY (SELECT * FROM tbl WHERE col = v2) TO '...' (FORMAT PARQUET, PARTITION_BY col, OVERWRITE_OR_IGNORE)
...
COPY (SELECT * FROM tbl WHERE col = v10) TO '...' (FORMAT PARQUET, PARTITION_BY col, OVERWRITE_OR_IGNORE)
```

it takes 5 minutes in total and does not go OOM.

I used `SET MEMORY_LIMIT` in both cases.

### To Reproduce

I don't have a reproducer yet, sorry.

### OS:

Linux x64

### DuckDB Version:

0.8.2-dev4514 38c6e8ccce

### DuckDB Client:

CLI

### Full Name:

Jonas Haag

### Affiliation:

QuantCo

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
how many rows does the tbl table have? please post the result of 
`select count(1)from tbl group by col`

**Comment by l1t1** [comment]
D SET MEMORY_LIMIT='100M';
D PRAGMA temp_directory='tmp.tmp';
D create table tbl as select i%10 col,i from range(10000000)t(i);
D .timer on
D COPY tbl TO 'tbl.parquet' (FORMAT PARQUET, PARTITION_BY col);
100% ▕████████████████████████████████████████████████████████████▏
Run Time (s): real 2.605 user 3.141877 sys 1.752219
D .system ls -l tbl*
total 0
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=0'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=1'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=2'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=3'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=4'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=5'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=6'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=7'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=8'
drwxr-xr-x 2 root root 3488 Sep 18 22:21 'col=9'

**Comment by l1t1** [comment]
root@localhost:/data/data/com.termux/files/home/b# cd tbl.parquet/col=0
root@localhost:/data/data/com.termux/files/home/b/tbl.parquet/col=0# ls -l
total 0
-rw-r--r-- 1 root root 542969 Sep 18 22:21 data_0.parquet
-rw-r--r-- 1 root root 706068 Sep 18 22:21 data_1.parquet
-rw-r--r-- 1 root root 509404 Sep 18 22:21 data_2.parquet
-rw-r--r-- 1 root root 651774 Sep 18 22:21 data_3.parquet
-rw-r--r-- 1 root root 651879 Sep 18 22:21 data_4.parquet
-rw-r--r-- 1 root root 488740 Sep 18 22:21 data_5.parquet
-rw-r--r-- 1 root root 434458 Sep 18 22:21 data_6.parquet
-rw-r--r-- 1 root root 434514 Sep 18 22:21 data_7.parquet

**Comment by min-mwei** [comment]
I run into a similar situation. The data file is quite small (9MB) and the cardinality of 'Underlying' is ~5300. I was a bit surprised that is OOM. 

But after setting the temp directory as suggested in the OOM error message, the partitioned write do finish.  [one nit, the word "PRAGMA" should be removed from the error or help message]

==
```
v0.8.2-dev4871 5a29c99891
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

COPY './2023.parquet' TO 'options' (FORMAT PARQUET, PARTITION_BY (Underlying));
Error: Out of Memory Error: could not allocate block of size 262KB (13.7GB/13.7GB used)
Database is launched in in-memory mode and no temporary directory is specified.
Unused blocks cannot be offloaded to disk.

Launch the database with a persistent storage back-end
Or set PRAGMA temp_directory='/path/to/tmp.tmp'
```

**Comment by l1t1** [comment]
> I run into a similar situation. The data file is quite small (9MB) and the cardinality of 'Underlying' is ~5300. I was a bit surprised that this partitioned write is OOM.
> 
> But after setting the temp directory as suggested in the OOM error message, the partitioned write does finish. [one nit, the word "PRAGMA" should be removed from the error or help message]
> 
> ==
> 
> ```
> v0.8.2-dev4871 5a29c99891
> Enter ".help" for usage hints.
> Connected to a transient in-memory database.
> Use ".open FILENAME" to reopen on a persistent database.
> 
> COPY './2023.parquet' TO 'options' (FORMAT PARQUET, PARTITION_BY (Underlying));
> Error: Out of Memory Error: could not allocate block of size 262KB (13.7GB/13.7GB used)
> Database is launched in in-memory mode and no temporary directory is specified.
> Unused blocks cannot be offloaded to disk.
> 
> Launch the database with a persistent storage back-end
> Or set PRAGMA temp_directory='/path/to/tmp.tmp'
> ```

could you share the file that results oom?

**Comment by l1t1** [comment]
2023.parquet PARTITION_BY (Underlying) very slow and finally failed.
```
v0.8.2-dev5154 78bea4f92a
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D set temp_directory='d:/tmp';
D .timer on

D COPY 'd:/2023.parquet' TO 'options' (FORMAT PARQUET, PARTITION_BY (Underlying)
);
Run Time (s): real 217.021 user 323.702075 sys 114.083531
Error: IO Error: Could not create directory: 'options\Underlying=BIL'

D select count(distinct Underlying) from 'd:/2023.parquet';
┌────────────────────────────┐
│ count(DISTINCT Underlying) │
│           int64            │
├────────────────────────────┤
│                       5286 │
└────────────────────────────┘
Run Time (s): real 0.365 user 2.402415 sys 0.015600
```
there are 5825 directories in options, only create Underlying=BIL failed

**Comment by l1t1** [comment]
set threads=1 sloved the question and quick,  and query on the directory created by one thead also quick
```
D set threads=1;
Run Time (s): real 0.011 user 0.015600 sys 0.000000
D COPY 'd:/2023.parquet' TO 'option1' (FORMAT PARQUET, PARTITION_BY (Underlying));
Run Time (s): real 25.603 user 13.182085 sys 7.020045

D select count(distinct Underlying) from read_parquet('option1/*/*');
┌────────────────────────────┐
│ count(DISTINCT Underlying) │
│           int64            │
├────────────────────────────┤
│                       5286 │
└────────────────────────────┘
Run Time (s): real 3.067 user 2.059213 sys 0.920406
```

**Comment by l1t1** [comment]
duckdb should set a thredhold of filesize, only when bigger than that, it use multi-threads create parquet

**Comment by l1t1** [comment]
the document says
Partitioned Writes
When the partition_by clause is specified for the COPY statement, the files are written in a hive
partitioned folder hierarchy. The target is the name of the root directory (in the example above: or￾ders). The files are written in‑order in the file hierarchy. Currently, one file is written per thread to
each directory.
orders
├── year=2021
│ ├── month=1
│ │ ├── data_1.parquet
│ │ └── data_2.parquet
│ └── month=2
│ └── data_1.parquet
└── year=2022
├── month=11
│ ├── data_1.parquet
│ └── data_2.parquet
└── month=12
└── data_1.parquet
The values of the partitions are automatically extracted from the data. Note that it can be very expen‑
sive to write many partitions as many files will be created. The ideal partition count depends on how
large your data set is.
Note. Writing data into many small partitions is expensive. It is generally recommended to
have at least 100MB of data per partition.
Overwriting By default the partitioned write will not allow overwriting existing directories

**Comment by szarnyasg** [comment]
Unfortunately, we cannot fix this in the absence of a reproducible example.

**Comment by jonashaag** [comment]
I'll try to come up with a reproducer. Other people in this thread provided examples. Did you try any of them by any chance?

**Comment by mozarik** [comment]
Can we reopen this issue @szarnyasg  ? it still happening 

cc: @jonashaag
