### ISSUE TITLE
COPY FROM does not recognize json.gz files and treats it as CSV 

### ISSUE THREAD

**Issue by jascoul** [duckdb/duckdb#8989]
### What happens?

Duckdb does not recognize files with a .json.gz extension and treats it as CSV. 
This happens when using the COPY FROM syntax. 

### To Reproduce

echo '{"id": 234, "name": "Test"}' > test.json
gzip test.json

duckdb
create table test (id integer, name varchar);
copy test from 'test.json.gz';

Error: Invalid Input Error: Could not convert string '{"id": 234' to INT32 at line 1 in column "id". Parser options:
  file=test.json.gz
  delimiter=',' (default)
  quote='"' (default)
  escape='"' (default)
  header=0' (default)
  sample_size=20480
  ignore_errors=0
  all_varchar=0 

### OS:

x86_64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

cli

### Full Name:

Jasper Op de Coul

### Affiliation:

Erasmus University Rotterdam

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
insert into works
```
~ $ echo '{"id": 234, "name": "Test"}' > test.json
gzip test.json
~ $

~ $ duckdb
v0.7.1 b00b93f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D from'test.json.gz';
┌────────┬─────────┐
│   id   │  name   │
│ uint64 │ varchar │
├────────┼─────────┤
│    234 │ Test    │
└────────┴─────────┘
D create table test (id integer, name varchar);
D insert into test from'test.json.gz';
D from test;
┌───────┬─────────┐
│  id   │  name   │
│ int32 │ varchar │
├───────┼─────────┤
│   234 │ Test    │
└───────┴─────────┘
```

**Comment by Ge6ben** [comment]
This article helped me: https://konbert.com/blog/import-json-into-postgres-using-copy
