### ISSUE TITLE
the map() returns wrong value

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#9002]
### What happens?

map(list1,list2)[item of list1] return empty or wrong value of list2

### To Reproduce

see https://github.com/duckdb/duckdb/discussions/8986

### OS:

windows7 x64

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
a  more small example, none of the rows are right.
```
D select ltp[1],lov[1],map(ltp,lov)['2013-01'] v from '/bop_h.parquet'where lov[1]=2662.3 or lov[1]=10896.4 or lov[1]=11057.0;
┌─────────┬─────────┬────────────┐
│ ltp[1]  │ lov[1]  │     v      │
│ varchar │ double  │  double[]  │
├─────────┼─────────┼────────────┤
│ 2013-01 │  2662.3 │ [10896.4]  │
│ 2013-01 │ 10896.4 │ [8718.0]   │
│ 2013-01 │ 11057.0 │ [268153.0] │
└─────────┴─────────┴────────────┘
```
[bop_h.zip](https://github.com/duckdb/duckdb/files/12670319/bop_h.zip)

**Comment by l1t1** [comment]
the steps of making the example data
```
wget "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/BOP_EU6_M?format=SDMX-CSV&compressed=true" -O bop.csv.gz

copy (select * from read_csv_auto('/bop.csv.gz', Header=true)) to '/bop.parquet';
duckdb
copy (select columns(* exclude(time_period,obs_value)),list(time_period)ltp,list(obs_value)lov from '/bop.parquet'group by all) to '/bop_h.parquet';
```

**Comment by l1t1** [comment]
the result of above SQL is following in Linux
```
┌─────────┬─────────┬────────────┐
│ ltp[1]  │ lov[1]  │     v      │
│ varchar │ double  │  double[]  │
├─────────┼─────────┼────────────┤
│ 2013-01 │  2662.3 │ [11136.0]  │
│ 2013-01 │ 10896.4 │ [235382.8] │
│ 2013-01 │ 11057.0 │ []         │
└─────────┴─────────┴────────────┘
```

**Comment by robert-manchester** [comment]
here is a minimal example. the first two selects are fine, the last one should return zero rows but with extra `r[1] > 5` we get a mismatched row.
```sql
create table data as from (
  values
  ([0], [3]),
  ([0], [9])
) as t(l, r);
-- this works.
select r[1], map(l, r)[l[1]] as v from data where v[1] = r[1]; 
-- this works
select r[1], map(l, r)[l[1]] as v from data where v[1] != r[1];
-- this fails
select r[1], map(l, r)[l[1]] as v from data where v[1] != r[1] and r[1] > 5;
```

```
┌───────┬─────────┐
│ r[1]  │    v    │
│ int32 │ int32[] │
├───────┼─────────┤
│     3 │ [3]     │
│     9 │ [9]     │
└───────┴─────────┘
┌───────┬─────────┐
│ r[1]  │    v    │
│ int32 │ int32[] │
├─────────────────┤
│     0 rows      │
└─────────────────┘
┌───────┬─────────┐
│ r[1]  │    v    │
│ int32 │ int32[] │
├───────┼─────────┤
│     9 │ [3]     │
└───────┴─────────┘
```

**Comment by Tishj** [comment]
As always with issues like this:
```
pragma disable_optimizer
```

Makes it work, so I'm going to have to have a look at the optimizers that affect this

**Comment by robert-manchester** [comment]
> As always with issues like this:
> 
> ```
> pragma disable_optimizer
> ```
> 
> Makes it work, so I'm going to have to have a look at the optimizers that affect this
> 
> Hmm it's the reordering that causes it, but that means that `select r[1], map(l, r)[l[1]] as v from data where r[1] > 5 and v[1] != r[1]` will fail even when optimizer is disabled That shouldn't happen 😅

i should've had a case with out the not equals clause.
`select r[1], map(l, r)[l[1]] as v from data r[1] > 5` is sufficient to cause the bug. or
`select r[1], map(l, r)[l[1]] as v from data r[1] != 3`.

the output in the map column, regardless of the where clause, is always what would appear in the first n rows without the where clause.

eg:
```sql
create table data as from (
  values
  ([1], [3]),
  ([2], [9]),
  ([3], [15]),
  ([4], [21]),
) as t(l, r);
-- this works
select l[1], r[1], map(l, r) from data;
-- map output shifted by 1 row
select l[1], r[1], map(l, r) from data where r[1] != 3;
```
```
┌───────┬───────┬───────────────────────┐
│ l[1]  │ r[1]  │       map(l, r)       │
│ int32 │ int32 │ map(integer, integer) │
├───────┼───────┼───────────────────────┤
│     1 │     3 │ {1=3}                 │
│     2 │     9 │ {2=9}                 │
│     3 │    15 │ {3=15}                │
│     4 │    21 │ {4=21}                │
└───────┴───────┴───────────────────────┘
┌───────┬───────┬───────────────────────┐
│ l[1]  │ r[1]  │       map(l, r)       │
│ int32 │ int32 │ map(integer, integer) │
├───────┼───────┼───────────────────────┤
│     2 │     9 │ {1=3}                 │
│     3 │    15 │ {2=9}                 │
│     4 │    21 │ {3=15}                │
└───────┴───────┴───────────────────────┘
```

**Comment by Tishj** [comment]
Ah thanks, that's a good example
To explain:
When we create a filter, we also create a dictionary vector to mask out the results that are filtered out
`map` did not respect this and that's why the first tuple that shows up is always the first tuple from the total result.
