### ISSUE TITLE
Copying multiple CSVs to Parquet ignores memory_limit iff threads>1

### ISSUE THREAD

**Issue by jmoy** [duckdb/duckdb#9027]
### What happens?

I'm trying to copy multiple compressed CSV files into a single Parquet file. The total uncompressed size of the CSV files exceeds my system's RAM which is 16GB. I also have 16GB of swap.

I set memory limit to 4GB. I set a temporary directory.

When I set threads=1 the process completes sucessfully and RAM usage throughout remains well below the memory limit.

When I set threads=2 the process continues consuming RAM and swap until it is killed by the OS.

Since the memory limit is one-eighth of my RAM+Swap this doesn't look like inaccuracy in memory accounting to me. Something is bypassing memory accounting altogether as soon as there is more than one thread.

### To Reproduce

I cannot provide the files to reproduce as they are multiple GB's compressed. The successful set of commands were

```sql
set memory_limit="4GB";
set temp_directory="/home/jmoy/junk";
set threads=1;
copy (select * from 
               read_csv_auto('original/ip_mem/*',
                                          compression='zstd',
                                          ignore_errors=TRUE,
                                          union_by_name=TRUE)) 
        to '/home/jmoy/junk/trial.parquet' (format parquet, compression 'zstd');
```
For the unsuccessful case the just the third line is changed to to

`set threads=2;`

### OS:

Debian 12 x64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

CLI

### Full Name:

Jyotirmoy Bhattacharya

### Affiliation:

Dr. B. R. Ambedkar University Delhi

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! Could you also try running this with `SET preserve_insertion_order=false` to see if that influences the memory consumption?

**Comment by jmoy** [comment]
This makes things much better. With `SET preserve_insertion_order=false` and `memory_limit` set to 4GB and threads not set, duckdb chooses 8 threads, uses a max resident memory of 6 GB (according to `top`) and completes the task successfully.

**Comment by jmoy** [comment]
With `SET preserve_insertion_order=false` and `set threads=2` it stays just under the memory limit throughout.

**Comment by jmoy** [comment]
The bug no longer exists  as of  commit `0d84ccf478`. `memory_limit` is now respected regardless of the value of `preserve_insertion_order` and the number of threads.

**Comment by szarnyasg** [comment]
@jmoy, great, thanks for coming back to report this!
