### ISSUE TITLE
Using DuckDB :memory: connection, deleting a table does not reduce memory usage

### ISSUE THREAD

**Issue by pablodcar** [duckdb/duckdb#9033]
### What happens?

Using a :memory: connection, a process inserts data in a cycle for a given day using `execute`. When done, data is deleted, and the cycle starts again for the following day, inserting new data.

During the execution, memory usage increases and when data is deleted the memory usage does not go down.

### To Reproduce

The following script runs 500k inserts, then deletes the content of the table and then there is a second cycle to do the same. Every 10k rows, it prints some stats.

What is observed:
After the first cycle (of 500k), the memory usage is ~264.08Mb
When the second cycle starts after a delete of the full table, the memory usage is the same and keeps increasing.

Expected behaviour:
When there is a deletion of thousands of records, the memory usage should go down or remain constant (reused).

Using `PRAGMA memory_limit` (and increasing the number of rows per cycle) didn't work for me. 

Reproduced with this script:

```python
import os, textwrap, random, string
from datetime import datetime, timedelta
from time import perf_counter, sleep

import psutil
import duckdb

PID = os.getpid()

CREATE_RATES_TABLE = textwrap.dedent(
    """CREATE TABLE IF NOT EXISTS rates
    (
        ts TIMESTAMP NOT NULL,
        ccy1 VARCHAR NOT NULL,
        ccy2 VARCHAR NOT NULL,
        bid DOUBLE NOT NULL,
        ask DOUBLE NOT NULL
        -- UNIQUE (ts, ccy1, ccy2)
    );"""
)

INSERT_RATES = textwrap.dedent(
    """INSERT INTO rates (ts, ccy1, ccy2, bid, ask)
    VALUES (?, ?, ?, ?, ?);"""
)

ROWS_PER_CYCLE = 500_000

def generate_random_strings():
    while True:
        random_string = ''.join(random.choices(string.ascii_uppercase, k=3))
        yield random_string

def generate_next_timestamp():
    ts = datetime.utcnow()
    while True:
        yield ts
        ts += timedelta(milliseconds=100)

def generate_random_float():
    while True:
        yield round(random.uniform(0.8, 1.2), 4)


def print_stats(db: duckdb.DuckDBPyConnection, elapsed: float) -> None:
    memory_info = psutil.Process(PID).memory_info()
    memory_usage_mb = memory_info.rss / (1024**2)
    with db.cursor() as cur:
        (rows,) = cur.execute("SELECT count(*) FROM rates;").fetchone()

    print(
        f"Process Memory usage: {memory_usage_mb:.2f}Mb "
        f"(N = {rows}) in {elapsed:.2f}s"
    )


con = duckdb.connect(":memory:")
con.execute(CREATE_RATES_TABLE)

print(f"inserting {ROWS_PER_CYCLE} rows")

def add_rows_cycle(n: int):
    t0 = perf_counter()
    ts = generate_next_timestamp()
    ccy = generate_random_strings()
    rate = generate_random_float()
    prev_ts = perf_counter()
    for i in range(1, n + 1):
        row = (next(ts), next(ccy), next(ccy), next(rate), next(rate))
        with con.cursor() as cur, cur.begin() as txn:
            txn.execute(INSERT_RATES, row)
            txn.commit()

        if i % 10000 == 0:
            print_stats(con, perf_counter() - prev_ts)
            prev_ts = perf_counter()

    print(f"cycle finished in {perf_counter() - t0}s")

print("starting first cycle")
add_rows_cycle(ROWS_PER_CYCLE)

print("deleting all records")

with con.cursor() as cur, cur.begin() as txn:
    txn.execute("DELETE FROM rates;")
    txn.commit()

sleep(10)
print("starting second cycle")
add_rows_cycle(ROWS_PER_CYCLE * 2)

print("done")
```

### OS:

iOS, x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Pablo Carballo

### Affiliation:

Revolut

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by tc-git-1** [comment]
Any update about this?

**Comment by szarnyasg** [comment]
Hi @ppietruszka, there are not updates on this at the moment. [Checkpointing](https://duckdb.org/docs/sql/statements/checkpoint) helps but only for on-disk databases, not for in-memory ones.

**Comment by ppietruszka** [comment]
I could switch my implementation to on disk, project is still in early stages. Much appreciated

**Comment by jicuss** [comment]
is there progress on this? appears to still be an ongoing issue
