### ISSUE TITLE
COPY FROM JSON over http fails, autoloading of httpfs not working

### ISSUE THREAD

**Issue by fundef1** [duckdb/duckdb#9069]
### What happens?

Cannot load json files over http with copy from, unless extension is loaded beforehand. 
autoloading not triggered?

### To Reproduce

create a simple rules table and json file with a single row.
copy from will fail, with an unhelpfull err msg.

triggering autoload of httpfs with copy from via read_json_auto works.
after which regular copy from also works.

```
D .read ./rules/schema.sql
D select extension_name,loaded,installed FROM duckdb_extensions() where extension_name = 'httpfs';
┌────────────────┬─────────┬───────────┐
│ extension_name │ loaded  │ installed │
│    varchar     │ boolean │  boolean  │
├────────────────┼─────────┼───────────┤
│ httpfs         │ false   │ true      │
└────────────────┴─────────┴───────────┘
D COPY rules FROM 'http://127.0.0.1:5500/data/rules.ndjson' (FORMAT JSON);
Error: IO Error: Cannot open file "http://127.0.0.1:5500/data/rules.ndjson": No such file or directory
D select extension_name,loaded,installed FROM duckdb_extensions() where extension_name = 'httpfs';
┌────────────────┬─────────┬───────────┐
│ extension_name │ loaded  │ installed │
│    varchar     │ boolean │  boolean  │
├────────────────┼─────────┼───────────┤
│ httpfs         │ false   │ true      │
└────────────────┴─────────┴───────────┘
D INSERT INTO rules SELECT * FROM read_json_auto('http://127.0.0.1:5500/data/rules.ndjson');
D select count(*) from rules;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            1 │
└──────────────┘
D select extension_name,loaded,installed FROM duckdb_extensions() where extension_name = 'httpfs';
┌────────────────┬─────────┬───────────┐
│ extension_name │ loaded  │ installed │
│    varchar     │ boolean │  boolean  │
├────────────────┼─────────┼───────────┤
│ httpfs         │ true    │ true      │
└────────────────┴─────────┴───────────┘
D COPY rules FROM 'http://127.0.0.1:5500/data/rules.ndjson' (FORMAT JSON);
D select count(*) from rules;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            2 │
└──────────────┘
```

### OS:

x86 Debian GNU/Linux 11 (bullseye) 

### DuckDB Version:

 v0.8.1          │ 6536a77232

### DuckDB Client:

cli

### Full Name:

Jo Degraef

### Affiliation:

none

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Heya @fundef1, which dev/main branch version did you test out? Autoloading of extensions is only available on our Dev builds at the moment

**Comment by fundef1** [comment]
DuckDB version is the 'Latest Release' 0.8.1 build from the install page - see version in the report.
So, autoloading shouldn't be available... but Interestingly enough, the extension is autoloaded with read_json?

Anyway, if the issue known and is already/will be fixed in an upcoming release I'll close this one.
(But you might want to give a more helpful error message)

**Comment by Tishj** [comment]
@Mause I think the issue is that COPY doesn't trigger autoloading, but read_json_auto does

**Comment by carlopi** [comment]
Just in case, I took a look at this, and autoloading seems to work as indented here on main.
