### ISSUE TITLE
Crash on re-reading of Arrow tables

### ISSUE THREAD

**Issue by ananis25** [duckdb/duckdb#908]
When using a relation backed by an Arrow table, doing multiple aggregation queries results in a segmentation fault. It isn't entirely deterministic - the first operation always succeeds while trying to do more than 2 generally faults. 

System information:
```
duckdb - version 0.2.1
pyarrow - version 1.0.1
python - version 3.7.6
Operating system - CentOS Linux release 7.8.2003 (Core)
```

Creating the Arrow dataset
```py
import numpy as np
import pyarrow as pa
import pyarrow.feather as pafeather

x = np.arange(0, 100_000_000)
y = np.arange(100_000_000, 200_000_000)

table = pa.table(
    [x,y,x,y,x,y,x,y,x,y,x,y], 
    names=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"]
)

pafeather.write_feather(
    table, 
    "/tmp/test.feather", 
    compression="uncompressed", 
    chunksize=1000_000
)
```

Loading the Arrow dataset and querying with Duckdb
```py
source = pa.memory_map("/tmp/test.feather", 'r')
reader = pa.RecordBatchFileReader(source)
table = reader.read_all()


import duckdb

rel = duckdb.from_arrow_table(table)
print(rel.aggregate("avg(b)"))
print(rel.aggregate("avg(c)"))
```

The top entry of the GDB backtrace indicates this routine. Would the full backtrace be helpful?
```
#1  0x00007fffb5f9c3dc in duckdb::arrow_scan_bind(duckdb::ClientContext&, std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, std::unordered_map<std::string, duckdb::Value, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, duckdb::Value> > >&, std::vector<duckdb::LogicalType, std::allocator<duckdb::LogicalType> >&, std::vector<std::string, std::allocator<std::string> >&) ()
```

Thank you for the work on this.

**Comment by hannesmuehleisen** [comment]
Thanks for reporting this, this should indeed not happen. Will have a look.

**Comment by hannesmuehleisen** [comment]
The workaround for now is to always use `duckdb.from_arrow_table(table)` instead of keeping it in a relation variable.

**Comment by ananis25** [comment]
Thank you for getting back so quick, this is a useful workaround. 

I have an unrelated question, apologies if this isn't the place to ask. From short usage and the helpful relational API, it really seems that - `DuckDb + memory mapped Arrow files` = `out-of-core pandas` (without the mutation methods I guess). 
Do you think this is a reasonable characterisation, in that all duckdb functionality will be usable with an Arrow backed virtual table?

**Comment by hannesmuehleisen** [comment]
Yes, you can certainly use all of SQL on arrow-backed virtual tables. Out-of-core pandas is I think also a fair comparison.

**Comment by nmichaud** [comment]
Is there any difference between using an arrow-backed virtual table or duckdb's standard file-based db?

**Comment by Mytherin** [comment]
In principle no. Arrow-backed virtual tables currently don't support projection/filter pushdown or parallel execution, but they will be extended to support this. In DuckDB external tables are first-class citizens that use the same infrastructure as scanning of the base tables.

Another current limit (which is the reason for this issue) is that arrow-backed tables can only be scanned once. That means that after scanning the table once it is "expired" and a new view needs to be created. AFAIK this is a current API limitation.

**Comment by hannesmuehleisen** [comment]
@pdet this needs to be addressed, at the very least by not crashing. In general we should distinguish between streaming and non-streaming sources here. To allow re-reading of static sources, we should pass a factory callback instead of the actual stream pointer, which can construct the stream, either once or many times.

**Comment by pdet** [comment]
@hannesmuehleisen I don't seem to be able to assign this to myself, maybe because you are already assigned?
Can you do, so its in my stack and I don't forget it after finishing the tasks I'm currently working on.

**Comment by pdet** [comment]
This can be closed.
