### ISSUE TITLE
CREATE TABLE my_table AS query -- query is not saved anywhere

### ISSUE THREAD

**Issue by ila** [duckdb/duckdb#9105]
### What happens?

If I run a CREATE statement dependent on a SELECT statement, the latter gets lost. I imagine this can cause problems when importing/exporting the DDL, and serialization. I am not sure if there is a workaround to this but I am opening a issue just in case (please let me know if I am wrong and this is the intended behaviour instead)

### To Reproduce

```
create table a(id1 int, id2 int);
create table b as (select id1, sum(id2) from a group by id1);
select sql from duckdb_tables; 
```

output:
```
CREATE TABLE b(id1 INTEGER, "sum(id2)" HUGEINT);                
CREATE TABLE a(id1 INTEGER, id2 INTEGER); 
```

### OS:

Ubuntu 23.04

### DuckDB Version:

0.6.2

### DuckDB Client:

Shell

### Full Name:

Ilaria Battiston

### Affiliation:

CWI

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
For EXPORT DATABASE we create a `schema.sql` and `load.sql`
the `schema.sql` will contain the schema of the table, `load.sql` contains the data of the table

That's why the query is not saved.
Imagine you create a table from another table, then delete the original table.
The creation of the new table would fail because the referenced table does not exist anymore if we replayed the query exactly.

**Comment by ila** [comment]
So you never plan to save this query anywhere? I am trying to implement materialized views in DuckDB - I can find a workaround if you don't think this is anything you will ever need :)

**Comment by Tishj** [comment]
Views save the query directly if I'm not mistaken

**Comment by ila** [comment]
I don't want to use views; I want to use tables. Materialized views are tables under the hood :)

**Comment by Tishj** [comment]
> I don't want to use views; I want to use tables. Materialized views are tables under the hood :)

That makes sense, in any case the `create.info->sql` should contain the raw query

**Comment by l1t1** [comment]
you can save the sql scripts by yourself. 

. dump also output one insert statement for every row. 
it ensure the STEPS can recreate all tables and their rows. 
```
D insert into a select i,i+1 from range(3)t(i);

D .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE a(id1 INTEGER, id2 INTEGER);;
INSERT INTO a VALUES(0,1);
INSERT INTO a VALUES(1,2);
INSERT INTO a VALUES(2,3);
CREATE TABLE b(id1 INTEGER, "sum(id2)" HUGEINT);;
COMMIT;
```
