### ISSUE TITLE
Clang / Cross-Compilation Build Error (Mac platforms)

### ISSUE THREAD

**Issue by jeremiahpslewis** [duckdb/duckdb#9106]
### What happens?

When building DuckDB v0.9 for Yggdrasil / DuckDB.jl Julia package for Mac, I get the following error:

In file included from /workspace/srcdir/duckdb/build/src/execution/operator/csv_scanner/ub_duckdb_operator_csv_scanner.cpp:2:
In file included from /workspace/srcdir/duckdb/src/execution/operator/csv_scanner/base_csv_reader.cpp:1:
In file included from /workspace/srcdir/duckdb/src/include/duckdb/execution/operator/scan/csv/base_csv_reader.hpp:11:
In file included from /workspace/srcdir/duckdb/src/include/duckdb/execution/physical_operator.hpp:11:
In file included from /workspace/srcdir/duckdb/src/include/duckdb/catalog/catalog.hpp:11:
In file included from /workspace/srcdir/duckdb/src/include/duckdb/catalog/catalog_entry.hpp:11:
In file included from /workspace/srcdir/duckdb/src/include/duckdb/common/common.hpp:11:
In file included from /workspace/srcdir/duckdb/src/include/duckdb/common/constants.hpp:11:
In file included from /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/memory:653:
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/type_traits:3730:47: error: array types cannot be value-initialized
    : public integral_constant<bool, noexcept(_Tp(declval<_Args>()...))>
                                              ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/type_traits:3757:7: note: in instantiation of template class 'std::__libcpp_is_nothrow_constructible<true, false, unsigned char [256]>' requested here
    : __libcpp_is_nothrow_constructible<is_constructible<_Tp>::value, is_reference<_Tp>::value, _Tp>
      ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/utility:510:21: note: in instantiation of template class 'std::is_nothrow_constructible<unsigned char [9][256]>' requested here
                    is_nothrow_constructible<second_type, _Args2...>::value))
                    ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/memory:1826:31: note: in instantiation of exception specification for 'pair<const duckdb::CSVStateMachineOptions &>' requested here
            ::new((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                              ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/memory:1718:18: note: in instantiation of function template specialization 'std::allocator<std::__hash_node<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, void *>>::construct<std::pair<const duckdb::CSVStateMachineOptions, unsigned char [9][256]>, const std::piecewise_construct_t &, std::tuple<const duckdb::CSVStateMachineOptions &>, std::tuple<>>' requested here
            {__a.construct(__p, _VSTD::forward<_Args>(__args)...);}
                 ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/memory:1561:14: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::__hash_node<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, void *>>>::__construct<std::pair<const duckdb::CSVStateMachineOptions, unsigned char [9][256]>, const std::piecewise_construct_t &, std::tuple<const duckdb::CSVStateMachineOptions &>, std::tuple<>>' requested here
            {__construct(__has_construct<allocator_type, _Tp*, _Args...>(),
             ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/__hash_table:2542:20: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::__hash_node<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, void *>>>::construct<std::pair<const duckdb::CSVStateMachineOptions, unsigned char [9][256]>, const std::piecewise_construct_t &, std::tuple<const duckdb::CSVStateMachineOptions &>, std::tuple<>>' requested here
    __node_traits::construct(__na, _NodeTypes::__get_ptr(__h->__value_),
                   ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/__hash_table:2126:29: note: in instantiation of function template specialization 'std::__hash_table<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, std::__unordered_map_hasher<duckdb::CSVStateMachineOptions, std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, duckdb::HashCSVStateMachineConfig, true>, std::__unordered_map_equal<duckdb::CSVStateMachineOptions, std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, std::equal_to<duckdb::CSVStateMachineOptions>, true>, std::allocator<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>>>::__construct_node_hash<const std::piecewise_construct_t &, std::tuple<const duckdb::CSVStateMachineOptions &>, std::tuple<>>' requested here
        __node_holder __h = __construct_node_hash(__hash, _VSTD::forward<_Args>(__args)...);
                            ^
/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/unordered_map:1558:21: note: in instantiation of function template specialization 'std::__hash_table<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, std::__unordered_map_hasher<duckdb::CSVStateMachineOptions, std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, duckdb::HashCSVStateMachineConfig, true>, std::__unordered_map_equal<duckdb::CSVStateMachineOptions, std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>, std::equal_to<duckdb::CSVStateMachineOptions>, true>, std::allocator<std::__hash_value_type<duckdb::CSVStateMachineOptions, unsigned char [9][256]>>>::__emplace_unique_key_args<duckdb::CSVStateMachineOptions, const std::piecewise_construct_t &, std::tuple<const duckdb::CSVStateMachineOptions &>, std::tuple<>>' requested here
    return __table_.__emplace_unique_key_args(__k,
                    ^
/workspace/srcdir/duckdb/src/execution/operator/csv_scanner/csv_state_machine_cache.cpp:15:46: note: in instantiation of member function 'std::unordered_map<duckdb::CSVStateMachineOptions, unsigned char [9][256], duckdb::HashCSVStateMachineConfig>::operator[]' requested here
        auto &transition_array = state_machine_cache[state_machine_options];
                                                    ^
1 error generated.

### To Reproduce

See https://github.com/JuliaPackaging/Yggdrasil/pull/7426

### OS:

Mac OS aarch64 & x86

### DuckDB Version:

0.9

### DuckDB Client:

Julia

### Full Name:

Jeremiah Lewis

### Affiliation:

HU Berlin

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! A fix is in progress in #9131

**Comment by giordano** [comment]
@Mytherin I'm glad you could reproduce the error, but could you please elaborate on what you believe is the problem and how #9131 fixes it?

**Comment by Mytherin** [comment]
I haven't actually managed to reproduce the problem - but it looks like that specific compiler doesn't like storing arrays in an `unordered_map`. This code simply wraps the array in an object instead which should fix the issue.

**Comment by jeremiahpslewis** [comment]
I can confirm that the fix resolves the issue: https://buildkite.com/julialang/yggdrasil/builds/5565

**Comment by arjenpdevries** [comment]
"predictive bug fixing", awesome @Mytherin.
