### ISSUE TITLE
v0.9.0 release missing JSON extension for Windows

### ISSUE THREAD

**Issue by davidmezzetti** [duckdb/duckdb#9107]
### What happens?

Receiving the following error.

```
duckdb.duckdb.Error: Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'json':
Failed to download extension "json" at URL "http://extensions.duckdb.org/v0.9.0/windows_amd64/json.duckdb_extension.gz"
Extension "json" is an existing extension.
```

Are you using a development build? In this case, extensions might not (yet) be uploaded.

### To Reproduce

Install duckdb with json extension on Windows

### OS:

Windows

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

David Mezzetti

### Affiliation:

NeuML

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Please be patient. Builds are still running: https://github.com/duckdb/duckdb/actions/runs/6311043761

**Comment by davidmezzetti** [comment]
Just realized that the release happened only an hour again and that the build is still running. My apologies. Thank you for the quick response.
