### ISSUE TITLE
read_csv: inconsistent cells per row provokes InternalException instead of InvalidInputException

### ISSUE THREAD

**Issue by tboddyspargo** [duckdb/duckdb#9111]
### What happens?

In previous versions of duckdb, CSV files that are formatted poorly caused an `InvalidInputException` exception to be raised in python. In version 0.9.0, there is an `InternalException` that is raised instead with a more opaque (to me) message.

```
duckdb.duckdb.InternalException: INTERNAL Error: 'back' called on an empty vector!
```

### To Reproduce

```python
import io
import duckdb


conn = duckdb.connect(':memory:')
file = io.StringIO(('\n' 'One,two,three\n' '1,2,3,4\n' '1,2,3\n' '\n' '1,2,3,4,5\n' '1,2,3,4,5\n'))
rel = conn.read_csv(file)
rel.show()
```

### OS:

macOS 13.5.1 x86_64

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Tyler BoddySpargo

### Affiliation:

DataChat

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by tboddyspargo** [comment]
Correction: the previously raised exception was `InvalidInputException` (with relevant explanation message) when CSVs had inconsistent delimiter counts.

**Comment by Mause** [comment]
End users should never see internal errors, so this is definitely a bug yeah

**Comment by tboddyspargo** [comment]
@Mytherin, @Mause - On v0.9.1, this test case no longer raises any exception, which was unexpected for me. Instead, it detected a column count of 5 and found no header, so it created default column names. It's definitely a gray area, but my prior assumption was that this case was ambiguous enough to deserve to raised an exception. It also made me question whether the test introduced in #9132 was running successfully... I thought it would be failing based on my observed changes.

I notice that the CSV sniffer implementation has changed significantly recently, so I'm working on wrapping my head around the new behaviors. I'm a little concerned that it seems to be raising fewer `InvalidInputExceptions` and making more aggressive "guesses" in situations with a high degree of ambiguity.

**Comment by tboddyspargo** [comment]
Oh, I see that the test case was modified to no longer consider this file invalid: https://github.com/pdet/duckdb/commit/11e85cfc818240694cb4ba74bd794ae2c81187b0.

I'll opened up https://github.com/duckdb/duckdb/issues/9343 to clarify my questions/concerns.
