### ISSUE TITLE
Python: duckdb rel.to_df() raises ConversionException with date: 2500-01-01

### ISSUE THREAD

**Issue by tboddyspargo** [duckdb/duckdb#9116]
### What happens?

DuckDB python API fails to convert a date value to nanoseconds.

```
duckdb.duckdb.ConversionException: Conversion Error: Could not convert DATE (2500-01-01) to nanoseconds
```

I'm a little unsure of some of the implementation details here. Is this an expected failure because the value in nanoseconds would exceed some limit of the bytes allocated to store it or something along those lines?

### To Reproduce

```python
import io
import duckdb


conn = duckdb.connect(":memory:")
file = io.StringIO(
    (
        "date\n"
        "2000-01-01\n"
        "2000-01-02\n"
        "2500-01-01\n"
        "2500-01-01\n"
        "2500-01-01\n"
        "2500-01-01\n"
        "2500-01-01\n"
    )
)
rel = conn.read_csv(file)
rel.show()
print(rel.to_df())

```

### OS:

macOS x86_64

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Tyler BoddySpargo

### Affiliation:

DataChat

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Your assumption is correct, the max date for a timestamp in nanoseconds in DuckDB is `2262-04-11 23:47:16.854775`

**Comment by tboddyspargo** [comment]
Thank you for confirming, @Mause !
