### ISSUE TITLE
read excel can't handle the title row

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#9118]
### What happens?

First row in excel is title row, but duckdb read it as data row
<img width="931" alt="image" src="https://github.com/duckdb/duckdb/assets/25274931/13a4f4e6-991f-4e57-a13e-f63178dac476">

### To Reproduce

```
load spatial;
SELECT * FROM st_read('/Users/mac/Downloads/output.xlsx',  layer='output1');
SELECT * FROM st_read('/Users/mac/Downloads/output.xlsx',  layer='output1', open_options=ARRAY['OGR_XLSX_HEADERS=FORCE']);

```
and the test data in attachment:
[output.xlsx](https://github.com/duckdb/duckdb/files/12735181/output.xlsx)

### OS:

mac13

### DuckDB Version:

0.9.0

### DuckDB Client:

java

### Full Name:

wang cz

### Affiliation:

Linezone

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Maxxen** [comment]
Hi! This works for me:
```sql
D load spatial;
D FROM ST_read('/vsicurl/https://github.com/duckdblabs/duckdb_spatial/files/12318296/output.xlsx', open_options=['HEADERS=DISABLE']);

┌──────────────────┬─────────┬─────────┬──────────────┬───────────────────────────────┬─────────┬─────────┬──────────────┬────────────┬─────────┐
│      Field1      │ Field2  │ Field3  │    Field4    │            Field5             │ Field6  │ Field7  │    Field8    │   Field9   │ Field10 │
│     varchar      │ varchar │ varchar │   varchar    │            varchar            │ varchar │ varchar │   varchar    │  varchar   │ varchar │
├──────────────────┼─────────┼─────────┼──────────────┼───────────────────────────────┼─────────┼─────────┼──────────────┼────────────┼─────────┤
│ 状态             │ 行号    │ 类型    │ 物料         │ 物料描述                      │ 数量    │ 单位    │ 是否为净水码 │ 是否为瓶子 │ 备注    │
│ 批准用于一般情况 │ 1       │ 配料    │ 113502010008 │ 硅藻土粗土.（纸袋、托盘包装） │ 0.2     │ KG      │              │            │         │
└──────────────────┴─────────┴─────────┴──────────────┴───────────────────────────────┴─────────┴─────────┴──────────────┴────────────┴─────────┘
```

**Comment by wonb168** [comment]
> Hi! This works for me:
> 
> ```sql
> D load spatial;
> D FROM ST_read('/vsicurl/https://github.com/duckdblabs/duckdb_spatial/files/12318296/output.xlsx', open_options=['HEADERS=DISABLE']);
> 
> ┌──────────────────┬─────────┬─────────┬──────────────┬───────────────────────────────┬─────────┬─────────┬──────────────┬────────────┬─────────┐
> │      Field1      │ Field2  │ Field3  │    Field4    │            Field5             │ Field6  │ Field7  │    Field8    │   Field9   │ Field10 │
> │     varchar      │ varchar │ varchar │   varchar    │            varchar            │ varchar │ varchar │   varchar    │  varchar   │ varchar │
> ├──────────────────┼─────────┼─────────┼──────────────┼───────────────────────────────┼─────────┼─────────┼──────────────┼────────────┼─────────┤
> │ 状态             │ 行号    │ 类型    │ 物料         │ 物料描述                      │ 数量    │ 单位    │ 是否为净水码 │ 是否为瓶子 │ 备注    │
> │ 批准用于一般情况 │ 1       │ 配料    │ 113502010008 │ 硅藻土粗土.（纸袋、托盘包装） │ 0.2     │ KG      │              │            │         │
> └──────────────────┴─────────┴─────────┴──────────────┴───────────────────────────────┴─────────┴─────────┴──────────────┴────────────┴─────────┘
> ```

this is not work！！！
the first row is title，but read it as data，and title became to Field1.2...etc.

**Comment by davidjbrennan** [comment]
Hi @wonb168.  If you change your open_options from 'HEADERS=DISABLE' to 'HEADERS=FORCE', it should work.

```
LOAD spatial;
FROM ST_read('/vsicurl/https://github.com/duckdblabs/duckdb_spatial/files/12318296/output.xlsx', open_options=['HEADERS=FORCE']);

┌──────────────────┬───────┬─────────┬──────────────┬───────────────────────────────┬────────┬─────────┬──────────────┬────────────┬─────────┐
│       状态       │ 行号  │  类型   │     物料     │           物料描述            │  数量  │  单位   │ 是否为净水码 │ 是否为瓶子 │  备注   │
│     varchar      │ int32 │ varchar │   varchar    │            varchar            │ double │ varchar │   varchar    │  varchar   │ varchar │
├──────────────────┼───────┼─────────┼──────────────┼───────────────────────────────┼────────┼─────────┼──────────────┼────────────┼─────────┤
│ 批准用于一般情况 │     1 │ 配料    │ 113502010008 │ 硅藻土粗土.（纸袋、托盘包装） │    0.2 │ KG      │              │            │         │
└──────────────────┴───────┴─────────┴──────────────┴───────────────────────────────┴────────┴─────────┴──────────────┴────────────┴─────────┘
```

**Comment by szarnyasg** [comment]
I reproduced the issue. As @davidjbrennan, the option `open_options=['HEADERS=FORCE']` indeed works.
