### ISSUE TITLE
pivot consume a lot of memory

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#9119]
### What happens?

I need a test table of 15 cols and 30M rows as https://duckdb.org/2023/09/26/announcing-duckdb-090.html says
I try to build it with pivot to simplify the sql
to minimize the memory usage , I set threads=1 and set PRAGMA temp_directory='d:/tmp', I still get OOM.

### To Reproduce

```
set threads=1;
PRAGMA temp_directory='d:/tmp';
```
```
create table t15x30M as
pivot
(
select i::int32 i,(i%15)::int8 j,(i//15)::int32 k from range(15*30000000)t(i)
)
on j using first(i)group by k;
```

### OS:

windows7 x64

### DuckDB Version:

0.9.0

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
btw,
I build it with cross join, it fast and the table consumes 4.6GB memory only

create table t15x30M_2 as
select i::int32 i,(i*15+j)::int32 "0","0"+1 "1","1"+1 "2","2"+1 "3","3"+1 "4","4"+1 "5","5"+1 "6","6"+1 "7","7"+1 "8",
"8"+1 "9","9"+1 "10","10"+1 "11","11"+1 "12","12"+1 "13","13"+1 "14"
from range(3000000)t(i),range(15)s(j);

**Comment by l1t1** [comment]
I made a wrong as I compute the memory occupied by the table
4 bytes * 15 *30M =18 GB, duckdb may save other data. it will overflow my 32GB memory.

**Comment by szarnyasg** [comment]
Your `PIVOT` query is indeed memory-intensive. `PIVOT` uses the `LIST` aggregate function that does not go out-of-core yet, so this failure is currently expected.
This table in the blog post was used for another operation (there's a related ongoing discussion under #9121).
