### ISSUE TITLE
cmake flags BUILD_{extension} aren't accepted by cmake

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#9125]
### What happens?

The [build instructions](https://duckdb.org/dev/building.html) say that ```BUILD_TPCE```, ```BUILD_JSON```, etc are valid cmake flags.

But cmake fails to accept them:
```
  Manually-specified variables were not used by the project:

    BUILD_EXCEL
    BUILD_FTS
    BUILD_HTTPFS
    BUILD_ICU
    BUILD_INET
    BUILD_JEMALLOC
    BUILD_JSON
    BUILD_PARQUET
    BUILD_SQLSMITH
    BUILD_TPCDS
    BUILD_TPCE
    BUILD_TPCH
    BUILD_VISUALIZER
```

Version: 0.9.0
FreeBSD 13.2

### To Reproduce

n/a

### OS:

FreeBSD 13.2

### DuckDB Version:

0.9.0

### DuckDB Client:

n/a

### Full Name:

YV

### Affiliation:

FreeBSD

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I think you're mixing up CMake and Make

**Comment by carlopi** [comment]
To CMake you can pass a list of extensions like: `-DBUILD_EXTENSIONS='autocomplete;icu;parquet;json'`, and that should build the relevant extensions.

**Comment by Mytherin** [comment]
As mentioned these are Make parameters, not CMake parameters
