### ISSUE TITLE
SSL certificate error with azure extension

### ISSUE THREAD

**Issue by know-jon** [duckdb/duckdb#9133]
### What happens?

I am trying to use the new azure extension but running into an error that I was asked to post here.

Let me know if I am missing something.

### To Reproduce

duckdb cli
 v0.9.0 0d84ccf478
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install azure; load azure;
D SET azure_storage_connection_string='DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=redacted;EndpointSuffix=core.windows.net';
D SELECT count(*) FROM 'azure://development/testing_of_duckdb/file.snappy.parquet';
Error: Invalid Error: Fail to get a new connection for: https://xxx.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)

### OS:

5.15.90.1-microsoft-standard-WSL2 Ubuntu 22.04.3 LTS x86_64

### DuckDB Version:

v0.9.0 0d84ccf478

### DuckDB Client:

cli

### Full Name:

Jon Erik Kemi Warghed

### Affiliation:

Knowit

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for reporting this. It seems there's a similar issue in the `duckdb_azure` repository at https://github.com/duckdblabs/duckdb_azure/issues/8. Can you please comment your finding there?
