### ISSUE TITLE
CSV export without `HEADER` specified still exports headers

### ISSUE THREAD

**Issue by njaremko** [duckdb/duckdb#9135]
### What happens?

Upon upgrading to 0.9.0 we hit a bug where CSV exports were including headers, despite the [documented default behaviour](https://duckdb.org/docs/archive/0.9.0/sql/statements/copy#csv-options) (and what we've seen historically) being that they shouldn't be.

### To Reproduce

Export a table as a CSV without specifying `HEADER`, and it will include the headers

[Edit:]
```sql
create table t(x int);
copy t to 't.csv';
```
$ cat t.csv
```csv
x
```
### OS:

aarch64 and x64

### DuckDB Version:

0.9.0

### DuckDB Client:

https://github.com/suketa/ruby-duckdb

### Full Name:

Nathan Jaremko

### Affiliation:

Census

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @njaremko

In this release, we decided to default the header export to true. 

Mainly because it is compliant with what a lot of other systems do.

However, our docs must reflect that still!

**Comment by njaremko** [comment]
Ah, yes. That breaking change caused an incident, so definitely needs to be documented 😅

**Comment by szarnyasg** [comment]
Thanks, I updated our documentation to reflect this change. It should be deployed in ~15 minutes.
