### ISSUE TITLE
Unordered SELECT statements provide different orderings

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#9138]
### What happens?

With 0.9.0, when running the same `SELECT` statement, without an `ORDER BY` clause, against static data in a table, the order of the results is not always the same.

I understand that if I'm not explicitly ordering the results I should probably not expect consistent ordering in the results. However, this does appear to deviate from the behavior of 0.7.1 and 0.8.1 where the result ordering was the same for every SELECT. I didn't see anything explicitly mentioning this in the release notes. Though I very well could have missed something.

### To Reproduce

```sql
create table T1(name varchar, shipping_region varchar, price float);
insert into T1 values ('item1', 'Northeast', 11.10);
insert into T1 values ('item2', 'West', 1.23);
insert into T1 values ('item3', 'South', 1.33);
insert into T1 values ('item4', 'Midwest', 1.55);
insert into T1 values ('item5', 'Northeast', 13.00);
insert into T1 values ('item6', 'Midwest', 3.00);
insert into T1 values ('item7', 'South', 7.00);
insert into T1 values ('item8', 'West', 79.00);
```

Then run `select shipping_region,sum(price) from T1 group by 1;` repeatedly. Most of the time the order of the results is the same. But on occasion, seemingly non-deterministically, the order will change. For instance
```
D select shipping_region,sum(price) from T1 group by 1;
┌─────────────────┬────────────────────┐
│ shipping_region │     sum(price)     │
│     varchar     │       double       │
├─────────────────┼────────────────────┤
│ Northeast       │ 24.100000381469727 │
│ West            │  80.23000001907349 │
│ South           │  8.330000042915344 │
│ Midwest         │  4.549999952316284 │
└─────────────────┴────────────────────┘
D select shipping_region,sum(price) from T1 group by 1;
┌─────────────────┬────────────────────┐
│ shipping_region │     sum(price)     │
│     varchar     │       double       │
├─────────────────┼────────────────────┤
│ South           │  8.330000042915344 │
│ Midwest         │  4.549999952316284 │
│ Northeast       │ 24.100000381469727 │
│ West            │  80.23000001907349 │
└─────────────────┴────────────────────┘
```

### OS:

MacOS 13.6, M1

### DuckDB Version:

0.9.0

### DuckDB Client:

CLI

### Full Name:

Michael Albers

### Affiliation:

ThoughtSpot

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by arjenpdevries** [comment]
This is expected, the relational model does not specify an order. Adding `order by` is the only way to get a guaranteed order of the result tables.

This gives the DB freedom to choose an efficient query plan; that may clearly vary per release (and even in a given release).

**Comment by Tishj** [comment]
Yes we've had to adjust some of our own tests too that were relying on this undefined behavior.
But that is what it is, undefined.
So as was already said, you have to provide an `order by` to get defined order behavior.

**Comment by michaeljohnalbers** [comment]
@Tishj We thought that was probably the case, but wanted to get confirmation this was indeed intentional. Thanks.
