### ISSUE TITLE
Error using JDBC Driver with DBeaver

### ISSUE THREAD

**Issue by mattgiles** [duckdb/duckdb#9141]
### What happens?

When connecting to a DuckDB database using DBeaver, upon "Test Connection..." I get the following error:

```
Invalid Error: TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported catalog type for ToSQL()
```

### To Reproduce

1. Create a db file using duckdb 0.9.0
2. Create a connection to the file in DBeaver, and test the connection

### OS:

macOS 13.3.1 (x86)

### DuckDB Version:

0.9.0

### DuckDB Client:

DBeaver (JDBC Driver 0.9.0)

### Full Name:

Matt Giles

### Affiliation:

Myself

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by mattgiles** [comment]
Note: I can fix by reverting to 0.8.1 (and pinning pandas to 2.0.3). But would love to work with unpinned duckdb and pandas.

**Comment by Mause** [comment]
Heya @mattgiles, are you able to give some more details? DBeaver version would be helpful (I'm unable to replicate with the versions I have to hand), and if the driver works otherwise beyond clicking the "test connection button"

**Comment by sharddith** [comment]
I'm also getting this issue on duckdb 0.9.0
DBeaver : 23.2.2

**Comment by Mause** [comment]
> I'm also getting this issue on duckdb 0.9.0
> DBeaver : 23.2.2
> 

Does the connection with otherwise?

**Comment by robhawkes** [comment]
Experiencing the same issue after upgrading to DuckDB 0.9.1 (previously things worked with DuckDB 0.8)

- MacOS 13.5.2 (M1 Pro)
- DBeaver 23.2.2.202310081633
- DuckDB 0.9.1

After clicking "Test Connection":
```
TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported catalog type for ToSQL()
```

When trying to connect to the database (otherwise I can't run any queries):
```
TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported catalog type for ToSQL()
```

**Comment by Mause** [comment]
> Experiencing the same issue after upgrading to DuckDB 0.9.1 (previously things worked with DuckDB 0.8)
> 
> - MacOS 13.5.2 (M1 Pro)
> - DBeaver 23.2.2.202310081633
> - DuckDB 0.9.1
> 
> After clicking "Test Connection":
> ```
> TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported catalog type for ToSQL()
> ```
> 
> When trying to connect to the database (otherwise I can't run any queries):
> ```
> TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported catalog type for ToSQL()
> ```

Heya Rob, do you have any settings set on the connection? If so, what are they set to?

**Comment by chriszrc** [comment]
It's working for me now with dbeaver Version 23.2.4.202311051706, huzzah!

**Comment by NatElkins** [comment]
Want to chime in that this issue was also resolved for me after upgrading to the latest version of DBeaver (now at 23.3.3).

**Comment by mattgiles** [comment]
🥳

**Comment by YuriyGavrilov** [comment]
v 24.1.3.202407211303

Same bug

<img width="490" alt="Снимок экрана 2024-08-01 в 20 18 51" src="https://github.com/user-attachments/assets/d58a1657-2b5e-43e8-b5a7-2cd74aa26d34">
<img width="532" alt="Снимок экрана 2024-08-01 в 20 19 09" src="https://github.com/user-attachments/assets/11595d67-a08d-4126-99eb-12d4d7e748c0">
