### ISSUE TITLE
Error mapping from python pyarrow/numpy uint64 to duckdb LogicalType

### ISSUE THREAD

**Issue by bretttully** [duckdb/duckdb#9144]
### What happens?

If I have a pandas dataframe with a `uint64` column, I am able to use a `uint64` in a prepared statement. However, if that same dataframe is a pyarrow table, then it stops working.

### To Reproduce

```python
import pandas as pd
import pyarrow as pa
import numpy as np
import duckdb

val = np.iinfo(np.uint64).max
df = pd.DataFrame({"a": np.array([val], dtype=np.uint64)})

try:
    with duckdb.connect(database=":memory:", read_only=False) as con:
        _ = con.execute("select * from df where a = $1", (val,)).df()
except Exception as e:
    print("Attempt 1:", e)
else:
    print("Attempt 1: Success!")

t = pa.Table.from_pandas(df)
try:
    with duckdb.connect(database=":memory:", read_only=False) as con:
        _ = con.execute("select * from t where a = $1", (val,)).df()
except Exception as e:
    print("Attempt 2:", e)
else:
    print("Attempt 2: Success!")

try:
    with duckdb.connect(database=":memory:", read_only=False) as con:
        _ = con.execute("select * from t where a = $1", pa.array([val], type=pa.uint64())).df()
except Exception as e:
    print("Attempt 3:", e)
else:
    print("Attempt 3: Success!")

try:
    with duckdb.connect(database=":memory:", read_only=False) as con:
        _ = con.execute("select * from t where a = $1", np.array([val], dtype=np.uint64)).df()
except Exception as e:
    print("Attempt 4:", e)
else:
    print("Attempt 4: Success!")
```

gives

```
Attempt 1: Success!
Attempt 2: Invalid Error: OverflowError: Python int too large to convert to C long

At:
  pyarrow/error.pxi(144): pyarrow.lib.pyarrow_internal_check_status

Attempt 3: Not implemented Error: Unable to transform python value of type '<class 'pyarrow.lib.UInt64Scalar'>' to DuckDB LogicalType
Attempt 4: Not implemented Error: Unable to transform python value of type '<class 'numpy.uint64'>' to DuckDB LogicalType
```

### OS:

docker -- ubuntu 22.04

### DuckDB Version:

python-duckdb 0.8.1 from conda-forge

### DuckDB Client:

Python

### Full Name:

Brett Tully

### Affiliation:

Nearmap

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by bretttully** [comment]
The prepared statement element might be a red herring. If I simplify completely I get an error that suggests duckdb isn't getting the scheme correctly from the pyarrow table?

```python
try:
    with duckdb.connect(database=":memory:", read_only=False) as con:
        _ = con.execute(f"select * from t where a > 0").df()
except Exception as e:
    print("Attempt 5:", e)
else:
    print("Attempt 5: Success!")
```

Gives
```
Attempt 5: Invalid Input Error: arrow_scan: get_next failed(): Invalid: Integer value 18446744073709551615 not in range: 0 to 9223372036854775807
```

**Comment by bretttully** [comment]
```python
with duckdb.connect(database=":memory:", read_only=False) as con:
    display(con.execute(f"describe select * from t").df())
```
Gives the expected result
![image](https://github.com/duckdb/duckdb/assets/5830269/b55ba368-8134-48ad-ae0c-ebf092906793)

**Comment by bretttully** [comment]
Continuing the theme of something strange
```python
try:
    _ = duckdb.arrow(t).filter("a > 0").df()
except Exception as e:
    print("Attempt 6:", e)
else:
    print("Attempt 6: Success!")
```
gives
```
Attempt 6: Invalid Input Error: arrow_scan: get_next failed(): Invalid: Integer value 18446744073709551615 not in range: 0 to 9223372036854775807
```

**Comment by bretttully** [comment]
Finally got something to work, but it's ugly...

```python
import pyarrow.compute as pc

arrow_scanner = ds.Scanner.from_dataset(ds.dataset(t), filter=pc.greater(pc.field("a"), pa.scalar(0, type=pa.uint64())))
with duckdb.connect(database=":memory:", read_only=False) as con:
    df = con.execute("SELECT * FROM arrow_scanner").df()
    print(df)
```

**Comment by Tishj** [comment]
Hey, thanks for raising the issue!

These are in fact two separate issues though, and I would categorize one as a feature request rather than a bug.

I think this highlights a bug in our pyarrow filter pushdown logic, we had something similar with timestamps recently.
Not accepting pyarrow/numpy scalars is expected though, happy to add it but that would not make it into 0.9.1

**Comment by bretttully** [comment]
Interesting, thanks @Tishj. For my own understanding, which cases fall into each bucket?

**Comment by Tishj** [comment]
feature:
```
Attempt 3: Not implemented Error: Unable to transform python value of type '<class 'pyarrow.lib.UInt64Scalar'>' to DuckDB LogicalType
Attempt 4: Not implemented Error: Unable to transform python value of type '<class 'numpy.uint64'>' to DuckDB LogicalType
```

(most likely) bug:
```
InvalidInputException: Invalid Input Error: arrow_scan: get_next failed(): ...
```
What likely happens is that when we scan the arrow batch we convert to a narrowing integer type, we create a filter set based on `(a > 0)`, then realize this is scanning an arrow batch reader so we convert the filter set to pyarrow and push it down to the scan.
The conversion of the filter set to pyarrow is likely where the bug is

**Comment by Tishj** [comment]
Actually, I'm not sure what's supposed to happen here
You're providing a value that's out of range for `uint64`, so I'd say the error message is entirely expected

**Comment by bretttully** [comment]
Makes sense, thanks.

With the type conversion feature request, I was wondering how that relates to the numpy types here: https://duckdb.org/docs/api/python/types.html#numpy-dtypes

**Comment by Tishj** [comment]
I have a fix 👍 

We were creating `pyarrow.dataset.scalar(value)` directly, without specifying a type explicitly
Since the constant is `0`, this narrows to smaller than uint64.

That sounds like a bug in pyarrow to be honest, uint64 > int32 shouldn't narrow the schema to int32
But never the less it's fixed

**Comment by Tishj** [comment]
> Makes sense, thanks.
> 
> With the type conversion feature request, I was wondering how that relates to the numpy types here: https://duckdb.org/docs/api/python/types.html#numpy-dtypes

They're not unrelated, but value conversion is a little more involved than type conversion
