### ISSUE TITLE
[Python] Exception when reading a csv file using the Spark API

### ISSUE THREAD

**Issue by guillemborrell** [duckdb/duckdb#9145]
### What happens?

Reading any csv file using the new Spark API causes a `NameError` because `DataFrame` is not defined.

```python
import duckdb
from duckdb.experimental.spark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

spark.read.csv("diabetes.csv")
```

```
   (...)
    172     timestamp_format=timestampFormat,
    173 )
--> 174 df = DataFrame(rel, self.session)
    175 if names:
    176     df = df.toDF(*names)

NameError: name 'DataFrame' is not defined
```

The line importing the `DataFrame` class is within a block that depends on the value of the constant TYPE_CHECKING, that is `False` in duckdb 0.9.0

Importing the DataFrame class within the `csv` method of the `DataFrameReader` class fixes the issue and avoids the circular import, but it's not a very clean solution. That's what kept me from submitting a PR.

### To Reproduce

Read any csv file with the spark csv reader

```python
import duckdb
from duckdb.experimental.spark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

spark.read.csv("diabetes.csv")
```

### OS:

x86

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Guillem Borrell

### Affiliation:

BCG X

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This was fixed via https://github.com/duckdb/duckdb/pull/9276
