### ISSUE TITLE
Setting allow_unsigned_extensions via ODBC driver

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#9157]
### What happens?

In #4089I mentioned that it is not possible to set `allow_unsigned_extensions` and hence you cannot use locally compiled extensions. I don't see any way to do this in the current code. I see the ODBC code has been getting some love lately...wondering if this is on anyones TODO list? 

I'm assuming that it would need to go in the connection string so that it happens before DB is opened. I noticed that Python does it this way...might have a look at how that is done and see how easy it might be to add to ODBC. 

### To Reproduce

When using ODBC, unsigned extensions install (e.g. local compiled version is copied to the correct folder) but cannot be loaded.

### OS:

all

### DuckDB Version:

current

### DuckDB Client:

ODBC

### Full Name:

charlie

### Affiliation:

myself

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I wonder if we can use environment variables for this or if it could somehow be added to the `odbcinst.ini` file ?

**Comment by carlsunderman** [comment]
How do you load extensions in the ODBC connection to begin with? Is this even possible without them being compiled into the ODBC code?

**Comment by bucweat** [comment]
Sorry I didn't respond earlier been busy with packout in prep for a move.

Assuming you have installed a tagged "Release" version of ODBC from [https://github.com/duckdb/duckdb/releases](https://github.com/duckdb/duckdb/releases) and you have internet access, then you should be able to INSTALL/LOAD as described in the [docs](https://duckdb.org/docs/archive/0.9.2/extensions/overview). This will download the official "signed" version of extension to your user .duckdb folder locally, and as long as you don't change duckdb versions, the local extension versions will continue to work. However, if you download a newer version of duckdb then a compatible version will need to be fetched again.  

Where things get tricky is if you build your own version of the driver. If you build using tagged release, then the hash should match the online extensions and they will still work. However, if you build from "main" and main is not currently pointing to a tagged release then the hash matching used to compare your local version to the online extensions version will fail and the extension will not load. 

Helpful references
https://duckdb.org/docs/archive/0.9.2/extensions/overview#installation-location-and-sharing-extensions-between-clients
https://duckdb.org/docs/archive/0.9.2/extensions/working_with_extensions

I know @maiadegraaf is working on adding the capability to allow unsigned extension load in ODBC which should allow for loading of locally built unsigned extensions.
