### ISSUE TITLE
The AS clause does not work when a combination of cross join and the unnest function is used

### ISSUE THREAD

**Issue by ihvol-freenome** [duckdb/duckdb#9162]
### What happens?

The 'AS' clause does not work when a combination of 'cross join' and the 'unnest' function is utilized. When I tried to execute the below SQL
```
with t1 as (
  select split('a,b,c,d', ',') as SPL1, 'hello' as hello
), 
t2 as (
  select * from t1 cross join unnest(SPL1) AS SPL2
) 
select SPL2 from t2;
```
I'm getting this error:
```
Error: Binder Error: Referenced column "SPL2" not found in FROM clause!
Candidate bindings: "t2.SPL1", "t2.SPL1:1"
LINE 1: ...ross join unnest(SPL1) AS SPL2) select SPL2 from t2;
```

### To Reproduce

Open the `duckdb` shell and execute the following SQL:

```
with t1 as (
  select 
    split('a,b,c,d', ',') as SPL1, 
    'hello' as hello
), 
t2 as (
  select  * 
  from  t1 cross 
    join unnest(SPL1) AS SPL2
) 
select  SPL2 from  t2;
```

### OS:

iOS

### DuckDB Version:

v0.9.0 0d84ccf478

### DuckDB Client:

Python

### Full Name:

Ihvol

### Affiliation:

Freenome

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report!

`AS` aliases the name of the table (function), not the name of the columns contained within the table. You can add aliases for column names using the bracket syntax, e.g.:

```sql
unnest(SPL1) AS t2(SPL2)
```

Full query:

```sql
with t1 as (
  select 
    split('a,b,c,d', ',') as SPL1, 
    'hello' as hello
), 
t2 as (
  select  * 
  from  t1 cross 
    join unnest(SPL1) AS t2(SPL2)
) 
select  SPL2 from  t2;
```

**Comment by ihvol-freenome** [comment]
that works. thank you for the explanation.
