### ISSUE TITLE
Iterating arrowIPCStream crashes electron

### ISSUE THREAD

**Issue by murrayju** [duckdb/duckdb#9172]
### What happens?

When attempting to iterate an `arrowIPCStream` in an electron main process, the application crashes with this output:

```bash
libc++abi: terminating due to uncaught exception of type Napi::Error: External buffers are not allowed
/path/to/Electron exited with signal SIGABRT
```

### To Reproduce

I've created [this repository](https://github.com/murrayju/electron-duckdb) to make it easy to reproduce this. The README there explains how to run the test.

In short, you can reproduce via:

```js
const db = new duckdb.Database(':memory:');
const con = db.connect();
const stream = await con.arrowIPCStream('select 1');
const rawBuffer = await stream.stream_result.nextIpcBuffer();
```

### OS:

macOS 14.0 arm64

### DuckDB Version:

0.9.0

### DuckDB Client:

node

### Full Name:

Justin Murray

### Affiliation:

PopSQL

### Have you tried this on the latest `main` branch?

I have tested with a release build, as well as the latest nightly build `0.9.1-dev43.0`

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Looks like we need to switch from `Napi::ArrayBuffer::New` to `Napi::Buffer::NewOrCopy` (https://github.com/nodejs/node-addon-api/blob/main/doc/buffer.md#neworcopy-1) which automatically handles this error

**Comment by murrayju** [comment]
Thanks for the quick fix! Will this show up in the next nightly, end up in 0.9.1?

**Comment by Mause** [comment]
> Thanks for the quick fix! Will this show up in the next nightly, end up in 0.9.1?

That's the plan yes!
