### ISSUE TITLE
TableFunctionData::column_ids does not contain column_ids

### ISSUE THREAD

**Issue by ziereis** [duckdb/duckdb#9178]
### What happens?

In the scan Implementation of my table function i receive a TableFunctionInput object that contains a TableFunctionData object which is as far as i understand supposed to hold by projected column_ids, when the table function is created with projection_pushdown = true. 

i fixed it for me by adding the following line:

```
    bind_data->Cast<TableFunctionData>().column_ids = column_ids;

```

to:
```
SourceResultType PhysicalTableScan::GetData(ExecutionContext &context, DataChunk &chunk,
                                            OperatorSourceInput &input) const {
	D_ASSERT(!column_ids.empty());
	auto &gstate = input.global_state.Cast<TableScanGlobalSourceState>();
	auto &state = input.local_state.Cast<TableScanLocalSourceState>();

        bind_data->Cast<TableFunctionData>().column_ids = column_ids;

	TableFunctionInput data(bind_data.get(), state.local_state.get(), gstate.global_state.get());
	function.function(context.client, data, chunk);

	return chunk.size() == 0 ? SourceResultType::FINISHED : SourceResultType::HAVE_MORE_OUTPUT;
}
```

but i guess this wouldn't be the right place to fill the column_ids.

### To Reproduce

you can check ParquetScanFunction::ParquetScanImplementation the TableFunctionInput, also doesnt hold the column_ids. the reader gets the column_ids from somewhere else so it works, but i still think they should be there. 

### OS:

Kubuntu 22.04

### DuckDB Version:

0.9

### DuckDB Client:

SQL

### Full Name:

Thomas Ziereis

### Affiliation:

LMU

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Seems to be completely unused, we should probably just remove the `column_ids` variable from it.

`TableFunctionInitInput` has the data you're looking for
