### ISSUE TITLE
Unexpected LEFT ASOF JOIN behaviour with "OR"

### ISSUE THREAD

**Issue by dafydds** [duckdb/duckdb#9183]
### What happens?

When performing a "LEFT ASOF JOIN", OR logic when joining tables does not work as expected.

It reduces the number of rows returned when in my opinion it should not (if you change the LEFT ASOF JOIN to a LEFT JOIN, it does not reduce the number of rows returned).

### To Reproduce

```python
import duckdb

con = duckdb.connect(database=':memory:')

# These tables prices and sales are from the "as of" duckdb example
con.execute("""
   CREATE TABLE prices AS (
    SELECT '2001-01-01 00:16:00'::TIMESTAMP + INTERVAL (v) MINUTE AS ticker_time,
        v AS unit_price
    FROM range(0, 5) vals(v)
);""")

con.execute("CREATE TABLE sales(item TEXT, sale_time TIMESTAMP, quantity INT);")
con.execute("INSERT INTO sales VALUES('a', '2001-01-01 00:18:00', 10);")
con.execute("INSERT INTO sales VALUES('b', '2001-01-01 00:18:30', 20);")
con.execute("INSERT INTO sales VALUES('c', '2001-01-01 00:19:00', 30);")

# returns 5 rows as expected
con.sql("""
       select * from prices 
        ASOF LEFT JOIN sales on sales.sale_time < prices.ticker_time 
                                and (sales.item = 'd')
        """).show()

## Returns 0 rows - unexpected (an OR here should not decrease the number of rows?)
con.sql("""
        select * from prices 
        ASOF LEFT JOIN sales on sales.sale_time < prices.ticker_time 
                                and (sales.item = 'd' or prices.ticker_time is null)
        """).show()


## Try a left join instead of asof join - works as expected, returns 5 rows
con.sql("""select * from prices 
        LEFT JOIN sales on sales.sale_time < prices.ticker_time 
                                and (sales.item = 'd' or prices.ticker_time is null)
        """).show()
```

### OS:

WSL on Linux (x64)

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Dafydd Steele

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Ah the bug here is that the `OR` clause is not allowed (it has to be an equality) but we are not checking.

**Comment by hawkfish** [comment]
No the problem is how the second clause gets split up and moved around.

**Comment by dafydds** [comment]
Thanks for looking into this. My workaround for anyone with a similar issue was to use a `CASE WHEN` inside the join instead which worked anyway.

**Comment by hawkfish** [comment]
I recommend using `infinity` instead of `NULL` for future unbounded `TIMESTAMP` values as described [here](https://duckdb.org/2023/09/15/asof-joins-fuzzy-temporal-lookups.html)
