### ISSUE TITLE
Dropping enum type has no effect on existing tables

### ISSUE THREAD

**Issue by droher** [duckdb/duckdb#9190]
### What happens?

The [doc](https://duckdb.org/docs/sql/data_types/enum#enum-removal) says that it should be impossible to drop a type if a table depends on it. However, dropping a user-defined type has no effect on any existing tables - the drop succeeds and the table stays the same, regardless of whether `CASCADE` is used.

I'm not sure whether the bug is specific to this behavior, or whether it's a larger problem that ENUM types seem to exist independently once they're bound to a table. 

### To Reproduce

```
CREATE TYPE e AS ENUM('x', 'y');
CREATE TABLE t (col e);
-- This should fail, but it doesn't
DROP TYPE e;
SELECT * FROM t;
```
```
┌────────────────┐
│ CAST('x' AS e) │
│ enum('x', 'y') │
├────────────────┤
│ x              │
└────────────────┘
```

### OS:

MacOS 14.0 (M1)

### DuckDB Version:

9.0

### DuckDB Client:

CLI

### Full Name:

David Roher

### Affiliation:

Self

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hmm it's interesting that this is documented this way, because I was under the impression this was intended.

My understanding is that CREATE TYPE only establishes an alias for a type.

When we query the table, the full definition of the type is used in the result set.

I'd be curious to hear @Mytherin 's thoughts on this.
I assume we need to change the docs, not the current behavior.

**Comment by Tishj** [comment]
That being said, your example could be made stronger by not using `create table tbl as select ..` and instead defining the schema directly.

Even with the old behavior, I doubt we would create a dependency when you are creating the table from a query result-set.

Just as no dependency on `tbl1` is established here:
```sql
CREATE TABLE tbl2 as select * from tbl2
```

**Comment by droher** [comment]
I updated the example accordingly. 

I'm sure there are plenty of other considerations, but from an end-user perspective I see a couple issues with the current behavior:
- State changes to the enum type (e.g. adding another variant) could get difficult to manage, with each column having barely noticeable differences between their types.
- I've noticed a significant DB-wide slowdown that gets worse each time I add a new column with the same enum (a uint16 with around 40K unique values). It seems to affect the speed of most DDL operations, even the creation of views that don't have that enum as a type. After this issue, I'm wondering if that has something to do with a new type effectively getting created for each column.

**Comment by pdet** [comment]
We can create tables with ENUMs even if they do not exist in the catalog. This is possible because ENUMs were initially designed to support the integration of factors and categorical types from R and Python. 

However, I agree that for ENUMs created via SQL, Tables should have a  drop dependency on them, hence failing on a `drop type` command.

**Comment by Mause** [comment]
Maintaining a dependency on the original type would probably also help solve https://github.com/duckdb/duckdb/issues/8838

**Comment by Mytherin** [comment]
I think this is a good idea, and shouldn't be applied only to enums but to all catalog types, but it needs to be implemented carefully. I had an idea of adding an alternative type (`CatalogType`) that contains a `schema + name` of a type stored in the catalog, which can then be resolved to the actual type during the binding process. That together with dependencies should allow for a clean implementation of this - but it will be quite invasive and touch a lot of places in the code.
