### ISSUE TITLE
Tag v0.9.1 with Yggdrasil fix

### ISSUE THREAD

**Issue by jeremiahpslewis** [duckdb/duckdb#9198]
### What happens?

Can't merge Yggdrasil / Julia binary PR until we have a tagged release, would it be possible to tag a version v0.9.1 with the bug fix (which resolves the problem)?

### Full Name:

Jeremiah Lewis

### Affiliation:

HU Berlin

**Comment by Mause** [comment]
Version 0.9.1 is expected to be released in the next fortnight
