### ISSUE TITLE
pyarrow decimal256 values are being lost

### ISSUE THREAD

**Issue by jeet-parekh** [duckdb/duckdb#9201]
### What happens?

When using duckdb to query pyarrow tables, pyarrow decimal256 type values are lost and zero value is returned instead. But the same values inside pyarrow decimal128 type are not affected.

### To Reproduce

```python
from decimal import Decimal

import duckdb
import pyarrow as pa

print(duckdb.__version__)
print(pa.__version__)

# DECIMAL256 VALUES ARE BEING LOST

pa_decimal256 = pa.Table.from_pylist(
    [{"data": Decimal("100.00")} for _ in range(4)],
    pa.schema([("data", pa.decimal256(12, 4))]),
)
print(pa_decimal256.to_pylist())
with duckdb.connect() as conn:
    print(conn.execute("select * from pa_decimal256;").arrow().to_pylist())

# DECIMAL128 VALUES ARE CORRECT

pa_decimal128 = pa.Table.from_pylist(
    [{"data": Decimal("100.00")} for _ in range(4)],
    pa.schema([("data", pa.decimal128(12, 4))]),
)
print(pa_decimal128.to_pylist())
with duckdb.connect() as conn:
    print(conn.execute("select * from pa_decimal128;").arrow().to_pylist())
```

Output, for me:

```text
0.9.0
13.0.0
[{'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}]
[{'data': Decimal('100.0000')}, {'data': Decimal('0.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('0.0000')}]
[{'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}]
[{'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}, {'data': Decimal('100.0000')}]
```

### OS:

x86_64 GNU/Linux

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Jeet Parekh

### Affiliation:

self

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by pdet** [comment]
Decimal 256 is currently unsupported by DuckDB, however, this should throw a `Not Implemented Exception`

**Comment by nethalo** [comment]
Any plans to re open this or considering supporting decimal256 overall?
