### ISSUE TITLE
ROW_NUMBER () Window function

### ISSUE THREAD

**Issue by hohenstrater** [duckdb/duckdb#9206]
### What happens?

It seems to only honour the 1st attribute order by attributes order

### To Reproduce

Using the snippet SQL below
```sql
	ROW_NUMBER () OVER (PARTITION BY SerialNumber,	ReadingTime,
ORDER BY
	ReadingTime ASC, '_offset' desc 
                                 ) as GroupID
```

```
GroupID, ReadingTime,SerialNumber,_offset
1	2023-09-16 18:25:00.000 +0000	219584794	2009373432
2	2023-09-16 18:25:00.000 +0000	219584794	2009673430
```

I was expecting 
```
1	2023-09-16 18:25:00.000 +0000	219584794	2009673430
2	2023-09-16 18:25:00.000 +0000	219584794	2009373432
```

### OS:

Windows

### DuckDB Version:

0.9

### DuckDB Client:

DBBeaver

### Full Name:

Thorsten

### Affiliation:

 Hobby

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hi, thanks for raising the issue

Can you please provide a full reproduction using SQL, data can also be provided as a dataset if necessarry.

It's quite difficult to determine if this is a bug from just the result

**Comment by robert-manchester** [comment]
change `'_offset'` -> `"_offset"` or just `_offset`

**Comment by Tishj** [comment]
> in the order by clause change `'_offset'` -> `"_offset"` or just `_offset`

Hmm you suspect it becomes a constant expression on the string literal `'_offset'` ?
I would think when used in this place we assume it's a column reference, but you might be right 👍

**Comment by robert-manchester** [comment]
I made some [test.csv](https://github.com/duckdb/duckdb/files/12802631/test.csv) data, then tried with `'_offset'`
```sql
select
  ROW_NUMBER () OVER (PARTITION BY SerialNumber, ReadingTime ORDER BY ReadingTime ASC, '_offset' DESC) as GroupID,
  *
from 'test.csv';
```
```
┌─────────┬─────────────────────┬──────────────┬────────────┐
│ GroupID │     ReadingTime     │ SerialNumber │  _offset   │
│  int64  │      timestamp      │    int64     │   int64    │
├─────────┼─────────────────────┼──────────────┼────────────┤
│       1 │ 2023-09-16 18:25:00 │    219584794 │ 2009373432 │
│       2 │ 2023-09-16 18:25:00 │    219584794 │ 2009673430 │
└─────────┴─────────────────────┴──────────────┴────────────┘
```
and then with just `_offset`
```sql
select
  ROW_NUMBER () OVER (PARTITION BY SerialNumber, ReadingTime ORDER BY ReadingTime ASC, _offset DESC) as GroupID,
  *
from 'test.csv';
```
```
┌─────────┬─────────────────────┬──────────────┬────────────┐
│ GroupID │     ReadingTime     │ SerialNumber │  _offset   │
│  int64  │      timestamp      │    int64     │   int64    │
├─────────┼─────────────────────┼──────────────┼────────────┤
│       1 │ 2023-09-16 18:25:00 │    219584794 │ 2009673430 │
│       2 │ 2023-09-16 18:25:00 │    219584794 │ 2009373432 │
└─────────┴─────────────────────┴──────────────┴────────────┘
```

though if i use a url and `'_offset'` the order seems nondeterministic.
```sql
select
  ROW_NUMBER () OVER (PARTITION BY SerialNumber, ReadingTime ORDER BY ReadingTime ASC, '_offset' DESC) as GroupID,
  *
from 'https://github.com/duckdb/duckdb/files/12802631/test.csv';
```

**Comment by robert-manchester** [comment]
> > in the order by clause change `'_offset'` -> `"_offset"` or just `_offset`
> 
> Hmm you suspect it becomes a constant expression on the string literal `'_offset'` ? I would think when used in this place we assume it's a column reference, but you might be right 👍

seems like string literal -- can replace `'_offset'` with any string eg: `'foo'` and there is no reported error, but use `foo` or `"foo"` generates a `referenced column "foo" not found in FROM clause` error.

**Comment by hohenstrater** [comment]
Thank you very much guys for the hint on '_offset' -> "_offset" . That works well for my situation
