### ISSUE TITLE
date_trunc() function returns the an unexpected result

### ISSUE THREAD

**Issue by hohenstrater** [duckdb/duckdb#9223]
### What happens?

Reading a Parquet file and using the date_trunc() on a Timestamp filed (TIMESTAMP WITH TIME ZONE) sometimes returns the next day when using date_trunc('day', ReadingTime). I have narrowed it down to this example. I tried with a CSV file and works as expected.

[output.zip](https://github.com/duckdb/duckdb/files/12812590/output.zip)

ReadingTime                  |time_bucket                  |date_trunc|
-----------------------------+-----------------------------+----------+
2023-09-20 17:40:00.000 +0000|2023-09-20 00:00:00.000 +0000|2023-09-21|

### To Reproduce

select ReadingTime, time_bucket(INTERVAL '1 day', ReadingTime) as time_bucket,date_trunc('day', ReadingTime)::DATE as date_trunc, from 'output.parquet'

### OS:

Windows

### DuckDB Version:

0.9

### DuckDB Client:

DBBeaver

### Full Name:

Thorsten

### Affiliation:

 Hobby

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
It depends what time zone you are in. You have given a time in GMT, but that may be tomorrow in the the current TZ. So for example, if you are in New Zealand, that instant will already be the following day, but if you are in Europe or America, it will be what you expect.

```sql
set timezone='America/Los_Angeles';
select '2023-09-20 17:40:00.000 +0000'::TIMESTAMPTZ ts;
-- 2023-09-20 10:40:00-07
select date_trunc('day', '2023-09-20 17:40:00.000 +0000'::TIMESTAMPTZ) d;
-- 2023-09-20 00:00:00-07

set timezone='Europe/Amsterdam';
select '2023-09-20 17:40:00.000 +0000'::TIMESTAMPTZ ts;
-- 2023-09-20 19:40:00+02
select date_trunc('day', '2023-09-20 17:40:00.000 +0000'::TIMESTAMPTZ) d;
-- 2023-09-20 00:00:00+02

set timezone='Pacific/Auckland';
select '2023-09-20 17:40:00.000 +0000'::TIMESTAMPTZ ts;
-- 2023-09-21 05:40:00+12
select date_trunc('day', '2023-09-20 17:40:00.000 +0000'::TIMESTAMPTZ) d;
-- 2023-09-21 00:00:00+12
```

**Comment by hohenstrater** [comment]
so how come the csv version has a different response to Parquet data source?

**Comment by hawkfish** [comment]
When reporting time zone issues, please include your current time zone, which you can either set explicitly or query for using:

```sql
SELECT * FROM duckdb_settings() WHERE name = 'TimeZone';
```

The CSV file has a GMT offset of +10, so I'm presuming you are in Australia or somewhere else on the western Pacific rim? 

The time in the CSV file is `2023-09-21 03:40:00+10`, (which is `2023-09-20 17:40:00.000+00`), so assuming your TZ is +10, then `data_trunc` is behaving as expected.

The parquet file is similar:

```sql
set timezone='Australia/Melbourne';
create or replace view test as from read_parquet('~/Downloads/output/output.parquet');
from test;
┌──────────────────────────┐
│       ReadingTime        │
│ timestamp with time zone │
├──────────────────────────┤
│ 2023-09-21 03:40:00+10   │
└──────────────────────────┘
```

You are in a TZ where the instant in the file is on the 21st, not the 20th, so again, `date_trunc` is behaving correctly.

Not sure about `time_bucket` but IIRC it has a default anchor date and that might be messing you up. Again, it is hard to tell without knowing what TZ you are in.

Time can be very confusing, and I recommend [my time zone blog post](https://duckdb.org/2022/01/06/time-zones.html) to help you think about it.

**Comment by hohenstrater** [comment]
@hawkfish, I am in TZ Brisbane (ie +10). Is there a bug with `time_bucket` where it behaves differently from the other time functions? I was expecting the same answer. I was also expecting that the export (copy) function not change the data.   I will keep experimenting with time. Thank you for your assistance :)
