### ISSUE TITLE
Database filename is converted to lowercase on Windows

### ISSUE THREAD

**Issue by 2-5** [duckdb/duckdb#9228]
### What happens?

When creating a new DuckDB database, the filename is converted to lowercase.

### To Reproduce

```python
import duckdb

db = duckdb.connect("Test_CASE.duckdb")
db.close()
```

Creates `test_case.duckdb`

### OS:

Windows 11

### DuckDB Version:

0.9.0

### DuckDB Client:

Python 3.11

### Full Name:

2-5

### Affiliation:

2-5

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by zippond** [comment]
Windows file name is case-insensitive, isn't it?

**Comment by szarnyasg** [comment]
> Windows file name is case-insensitive, isn't it?

It is. Still, we should keep the cases provided in the user's input. We will look into it but it is not a high priority issue.

**Comment by fabienval** [comment]
This issue is still present.
It is very confusing to get a db file name different than what we asked for.

**Comment by chris-dailey** [comment]
I normally use uppercase database names and this issue is very frustrating

**Comment by dmcmurchy** [comment]
Still present in 1.2.1 on Windows. I thought I was doing something silly in my code but nope.
