### ISSUE TITLE
Python ADBC driver not working (Windows 11)

### ISSUE THREAD

**Issue by glacial-ai** [duckdb/duckdb#9239]
### What happens?

I'm trying to run the example code provided at [https://duckdb.org/docs/api/adbc] (under the Python section), but I'm getting errors:
`Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import adbc_driver_duckdb.dbapi
>>>
>>> with adbc_driver_duckdb.dbapi.connect("test.db"
...   ) as conn, conn.cursor() as cur:
...   cur.execute("SELECT 42")
...   # fetch a pyarrow table
...   tbl = cur.fetch_arrow_table()
...   print(tbl)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\travi\Desktop\Projects\glacialdb\py-glacialdb\Lib\site-packages\adbc_driver_duckdb\dbapi.py", line 101, in connect
    db = adbc_driver_duckdb.connect(path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\travi\Desktop\Projects\glacialdb\py-glacialdb\Lib\site-packages\adbc_driver_duckdb\__init__.py", line 40, in connect
    return adbc_driver_manager.AdbcDatabase(driver=_driver_path(), entrypoint="duckdb_adbc_init", path=path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "adbc_driver_manager\\_lib.pyx", line 404, in adbc_driver_manager._lib.AdbcDatabase.__init__
  File "adbc_driver_manager\\_lib.pyx", line 227, in adbc_driver_manager._lib.check_error
adbc_driver_manager.InternalError: INTERNAL: GetProcAddress(duckdb_adbc_init) failed: (127) The specified procedure could not be found.`

### To Reproduce

First pip install the libraries:
`duckdb==0.9.0
adbc-driver-manager==0.7.0
pyarrow==13.0.0`

Then run the code:
`import adbc_driver_duckdb.dbapi

with adbc_driver_duckdb.dbapi.connect("test.db"
  ) as conn, conn.cursor() as cur:
  cur.execute("SELECT 42")
  # fetch a pyarrow table
  tbl = cur.fetch_arrow_table()
  print(tbl)`

### OS:

Windows 11 Home

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Travis Loebs

### Affiliation:

Glacial AI

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Can you please try with the 0.6.0 version of the driver? Unfortunately the spec is not yet stable

**Comment by Mause** [comment]
It looks like this may only work on macOS at the moment, we're following up

**Comment by pdet** [comment]
Indeed, we do not support Windows yet. I'll update the docs to reflect that.

**Comment by glacial-ai** [comment]
> Can you please try with the 0.5.1 version of the adbc driver manager? Unfortunately the spec is not yet stable

@Mause  I'm getting the same error with this version.


> Indeed, we do not support Windows yet. I'll update the docs to reflect that.

@pdet Ok, I'll have to wait. If I can figure out how to install DuckDB to Ubuntu on WSL2, then I'll try that.

**Comment by mehmety888** [comment]
I get the same error with same script. 

I have windows10.

duckdb:0.9.2
adbc_driver_manager:0.5.1
pyarrow:14.0.2

**Comment by Mause** [comment]
Does it work with a nightly build of DuckDB?

**Comment by martinseifertprojuventute** [comment]
Just tried it, too, using the example from https://duckdb.org/docs/stable/clients/adbc#python 
Result: The .db file is created, but no table persisted in the .db on Windows 11

```import adbc_driver_duckdb.dbapi
import pyarrow

data = pyarrow.record_batch(
    [[1, 2, 3, 4], ["a", "b", "c", "d"]],
    names = ["ints", "strs"],
)

with adbc_driver_duckdb.dbapi.connect("test.db") as conn, conn.cursor() as cur:
    cur.adbc_ingest("AnswerToEverything", data)
```
