### ISSUE TITLE
DISTINCT ON in a subquery + filter produces wrong results

### ISSUE THREAD

**Issue by ankrgyl** [duckdb/duckdb#9241]
### What happens?

`DISTINCT ON` relies on the `ORDER BY` clause to figure out which rows to return from a select statement. If you write a filter outside of a subquery with `DISTINCT ON`, it should apply the filter on the result, not push it into a subquery. However, DuckDB appears to push the filter into the subquery, producing wrong results.

### To Reproduce

```
D create table foo (a int, b int);
D
D insert into foo values (1, 1), (2, 1), (2, 2);
D select * from (select distinct on (a) a, b from foo order by a, b desc) sub;
┌───────┬───────┐
│   a   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     1 │
│     2 │     2 │
└───────┴───────┘
D
D select * from (select distinct on (a) a, b from foo order by a, b desc) sub where b <> 2;
┌───────┬───────┐
│   a   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     1 │
│     2 │     1 │
└───────┴───────┘
D
```

I've verified that Postgres produces a single row (`(1, 1)`) in this case.

### OS:

mac os x

### DuckDB Version:

v0.9.0 0d84ccf478

### DuckDB Client:

cli

### Full Name:

Ankur Goyal

### Affiliation:

Braintrust Data

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I would need to test on release, but from just reading it this sounds like a problem.

Thanks for the clear and concise reproduction, we appreciate it a lot!

**Comment by Tishj** [comment]
```
D select * from (select distinct on (a) a, b from tbl order by a, b desc);
┌───────┬───────┐
│   a   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     1 │
│     2 │     2 │
└───────┴───────┘
D select * from (select distinct on (a) a, b from tbl order by a, b desc) where b != 2;
┌───────┬───────┐
│   a   │   b   │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     1 │
│     2 │     1 │
└───────┴───────┘
D pragma version;
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.9.1-dev165   │ c3aa7594ab │
└─────────────────┴────────────┘
```

I can reproduce your results, we'll have a look 👍
Can't guarantee a timeframe however

**Comment by ankrgyl** [comment]
Thank you! We are working around it for now by just using a window function.

**Comment by ankrgyl** [comment]
🙏🏽
