### ISSUE TITLE
CSV to parquet failing 

### ISSUE THREAD

**Issue by mrendi29** [duckdb/duckdb#9253]
### What happens?

Converting large CSV(10gb gzipped, ~35GB deflated) to parquet using duckdb 0.9.0 is extremely slow, eating a ton of resources and failing because of not enough ram.

This also fails when i use PER_THREAD_OUTPUT 1 and use default row_group size.

Only when I set set PRAGMA temp_directory='/path/to/tmp.tmp' command succeeds, however takes a long time to finish. (Memory usage still high compared to 0.8.1 where it was 1/10 of current memory usage) 

### To Reproduce
```

D COPY (SELECT * FROM read_csv('largecsvfile.gz', delim=' ', header=False,timestampformat='%Y/%m/%d:%H:%M:%S' ,columns={
>     'col0': 'UTINYINT',
>     'col1': 'TIMESTAMP',
>     'col2': 'UINTEGER',
>     'col3': 'USMALLINT',
>     'col4': 'USMALLINT',
>     'col5': 'VARCHAR(64)',
>     'col6': 'UTINYINT',
>     'col7': 'UINT16',
>     'col8': 'UTINYINT',
>     'col9': 'UBIGINT',
>     'col10': 'UBIGINT'
>      }))
>      TO 'output.parquet' (FORMAT 'PARQUET',COMPRESSION 'snappy',ROW_GROUP_SIZE 1280000);
100% ▕████████████████████████████████████████████████████████████▏ Error: Out of Memory Error: could not allocate block of size 32.0MB (26.8GB/26.8GB used)
Database is launched in in-memory mode and no temporary directory is specified.
Unused blocks cannot be offloaded to disk.

Launch the database with a persistent storage back-end
Or set PRAGMA temp_directory='/path/to/tmp.tmp'
D
```

### OS:

ubuntu 20

### DuckDB Version:

0.9.0

### DuckDB Client:

cli

### Full Name:

Endi Caushi

### Affiliation:

Akamai

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
duckdb v0.9 cannot limit the memory used by now. 
split the csv into small files, then covert each one into a parquet file. 
see https://github.com/duckdb/duckdb/discussions/9215#discussioncomment-7192823

https://github.com/duckdb/duckdb/discussions/9264

**Comment by mrbrianevans** [comment]
I was having an issue converting large files with duckdb, it got about 20% of the way and then said "Killed" and exited without completing.
I was running duckdb in wsl 2 ubuntu. I solved the problem by running directly in Windows instead.

**Comment by szarnyasg** [comment]
@mrendi29 did you try issuing `SET preserve_insertion_order=false;` before running your `COPY` command?

**Comment by szarnyasg** [comment]
Closing this for now, feel free to reopen if the issue occurs with `preserve_insertion_order=false`.
