### ISSUE TITLE
Statically linking duckdb in `C++` using `duckdb_static.lib` causes errors in `MSVC 2022 Windows`

### ISSUE THREAD

**Issue by arnabadas** [duckdb/duckdb#9257]
### What happens?

Building application using duckdb_static causes error. I am using `duckdb_static.lib` while building instead of `duckdb.lib`. Building using `duckdb.lib` works fine but I want a statically linked binary which doesn't require `duckdb.dll`.

### To Reproduce

Run `make` in the following repo: [duckdb_example](https://github.com/arnabadas/duckdb_example)
**Note:** Change the library directory in `CMakeLists.txt` to the appropriate directory. I built the library from the main branch.

[error.txt](https://github.com/duckdb/duckdb/files/12835859/error.txt)

### OS:

Windows 11 Pro 22H2 x64

### DuckDB Version:

main branch (dated 7th October 2023)

### DuckDB Client:

C++

### Full Name:

Arnab Animesh Das

### Affiliation:

NA

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Unfortunately this issue falls out of scope from our [support policy](https://duckdblabs.com/news/2023/10/02/support-policy.html).
