### ISSUE TITLE
[Python] read_csv method does not support custom enum types in dtype param

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb#9258]
### What happens?

When using `duckdb.read_csv` to load a CSV and providing a custom enum type to the `dtype` param, a `ValueError` is thrown: _The types provided to 'dtype' have to be DuckDBPyType_.

### To Reproduce

Given the following in-memory CSV and a custom enum `yesno`:

```python
import io
import duckdb

csv = io.StringIO(
"""
col1, col2
1,Y
2,N
"""
)
duckdb.sql("CREATE TYPE yesno AS ENUM ('Y', 'N')")
```

Using `read_csv` to read the CSV with `col2` as the `yesno` type fails:

```python
duckdb.read_csv(csv, dtype={"col2": "yesno"})
```

Whereas using SQL directly (over the same CSV written to disk) works fine:

```python
with open("test.csv", "w") as f:
    csv.seek(0)
    f.write(csv.read())

duckdb.sql("FROM read_csv_auto('test.csv', dtypes={col2: yesno})")
```

### OS:

Ubuntu 23.04

### DuckDB Version:

0.9.1-dev143

### DuckDB Client:

Python

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
We perform an implicit cast from the provided string dtype to DuckDBPyType, without a connection this can't do the catalog lookups to find the custom type.
That being said, the read_csv method requires a connection anyways, so this should be a one-line fix

**Comment by ned2** [comment]
Confirming that this is still an issue in DuckDB 0.9.3.dev2254.
