### ISSUE TITLE
duckdb.ConversionException: Conversion Error: Could not convert string 'sfe00000000000000001694189946367' to INT32

### ISSUE THREAD

**Issue by ChaoKing2020** [duckdb/duckdb#9259]
### What happens?

duckdb.ConversionException: Conversion Error: Could not convert string 'sfe00000000000000001694189946367' to INT32### 

### To Reproduce

```python
import duckdb
import pandas as pd

new_all_vehicles = [v.__dict__ for v in glob_data['all_vehicles']]
con = duckdb.connect(database=':memory:')
all_vehicles = pd.DataFrame(new_all_vehicles)
con.execute(f'create table all_vehicles as select * from all_vehicles')

sql = f"update all_vehicles set next_idx = {v1_next_idx} where v_id = '{v1_v_id}'"
con.execute(sql)
```

First of all, v1_next_idx is a list of string. It will arise a error that could not convert string "sfe00000000000000001694189946367" to INT32 when I update it.

How to do solve it? Please help me and I am grateful to you very much.

### OS:

x64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Chao Wang

### Affiliation:

HNUST

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I think we need a more complete reproduction to say anything about this

**Comment by ChaoKing2020** [comment]
~~~python
import duckdb
import pandas as pd

new_all_vehicles = [v.__dict__ for v in glob_data['all_vehicles']]
con = duckdb.connect(database=':memory:')
all_vehicles = pd.DataFrame(new_all_vehicles)
con.execute(f'create table all_vehicles as select * from all_vehicles')

sql = f"update all_vehicles set next_idx = {v1_next_idx} where v_id = '{v1_v_id}'"
con.execute(sql)
~~~

This is relevant details abot code. I want to update next_idx from all_vehicles table and think that next_idx field shoud be a list of string. Unfortunately, the default value from next_idx field is a list of int32. I don't know how to change it now.

**Comment by Mause** [comment]
> ~~~python
> import duckdb
> import pandas as pd
> 
> new_all_vehicles = [v.__dict__ for v in glob_data['all_vehicles']]
> con = duckdb.connect(database=':memory:')
> all_vehicles = pd.DataFrame(new_all_vehicles)
> con.execute(f'create table all_vehicles as select * from all_vehicles')
> 
> sql = f"update all_vehicles set next_idx = {v1_next_idx} where v_id = '{v1_v_id}'"
> con.execute(sql)
> ~~~
> 
> This is relevant details abot code. I want to update next_idx from all_vehicles table and think that next_idx field shoud be a list of string. Unfortunately, the default value from next_idx field is a list of int32. I don't know how to change it now. 

Can you please provide the data? This isn't yet enough to replicate the issue

**Comment by ChaoKing2020** [comment]
I am very sorry for my unclear response. Here are some sample data:
~~~
all_vehicles = [ { "v_id": "sfe00000000000000001695486896639", "next_idx": [] } ]
next_idx = ["sfe00000000000000001695486894423", "sfe00000000000000001695486897721"]
~~~
I need to update it now.

**Comment by l1t1** [comment]
because the empty list is a list of integers by default. 
```
D create table t as select [] a;
D describe t;
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ a           │ INTEGER[]   │ YES     │         │         │       │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘
D insert into t values(['a']);
Error: Conversion Error: Could not convert string 'a' to INT32
D create table t2 as select []::varchar[] a;
D describe t2;
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ a           │ VARCHAR[]   │ YES     │         │         │       │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘
D insert into t2 values(['a']);
```

**Comment by ChaoKing2020** [comment]
Thanks you for your clear reply, but I think that declaring a array of string is not easy for me. Maybe, I need to learn step by step.

**Comment by Tishj** [comment]
> Thanks you for your clear reply, but I think that declaring a array of string is not easy for me. Maybe, I need to learn step by step.

Instead of create table as `select *` you probably need to the columns explicitly and for the empty list provide a cast: `next_idx::VARCHAR[]`

**Comment by ChaoKing2020** [comment]
@szarnyasg the glob_data varible is dict rather than list.

**Comment by szarnyasg** [comment]
@ChaoKing2020 we were unable to reproduce this issue. Please reopen if you have a complete Python script that is able to reproduce the issue.
