### ISSUE TITLE
Memory usage never decreases after DELETE FROM

### ISSUE THREAD

**Issue by dufferzafar** [duckdb/duckdb#9263]
### What happens?

I'm using an in-memory and have a workload that updates a table using the C++ Appender interface. When left running, memory usage continues to rise until the application needs to be killed.

### To Reproduce

```cpp
#include "vendor/duckdb/duckdb.hpp"

#include <iostream>
#include <memory>
#include <random>
#include <string>
#include <unordered_map>

using namespace duckdb;

int main()
{
    std::unordered_map<std::string, std::string> options = {{"threads", "2"}};
    auto config = DBConfig(options, false);

    DuckDB     db(nullptr, &config);
    Connection con(db);

    // Setup
    auto res = con.Query(R"(
        CREATE TABLE main(
            k1 VARCHAR, k2 VARCHAR, k3 UINTEGER, k4 VARCHAR,
            f1 DOUBLE, f2 DOUBLE, f3 DOUBLE, f4 DOUBLE, f5 DOUBLE, f6 DOUBLE,
            PRIMARY KEY(k1, k2, k3)
        );

        CREATE TABLE updates(
            id UINTEGER, k1 VARCHAR, k2 VARCHAR, k3 UINTEGER, k4 VARCHAR,
            f1 DOUBLE, f2 DOUBLE, f3 DOUBLE, f4 DOUBLE, f5 DOUBLE, f6 DOUBLE
        );
    )");

    auto update = R"(
        INSERT INTO main
        (
            SELECT * EXCLUDE (rnk, id) FROM (
                SELECT *, RANK() OVER
                    (PARTITION BY k1, k2, k3 ORDER BY id DESC) AS rnk
                FROM updates
                QUALIFY rnk = 1
            )
        )
        ON CONFLICT (k1, k2, k3)
        DO UPDATE SET 
            f1 = excluded.f1, f2 = excluded.f2, f3 = excluded.f3,
            f4 = excluded.f4, f5 = excluded.f5, f6 = excluded.f6
        ;
    )";

    std::default_random_engine generator;
    std::uniform_int_distribution<int> random_key(1, 1'000'000);

    long m_updateCnt{0};
    duckdb::Appender appender(con, "updates");
    while (true)
    {
        for (size_t i = 1; i < 500'000; i++)
        {
            appender.BeginRow();
            appender.Append<uint32_t>(++m_updateCnt);
            appender.Append<duckdb::string_t>("Group");
            appender.Append<duckdb::string_t>("Case");
            appender.Append<uint32_t>(random_key(generator));
            appender.Append<duckdb::string_t>("Record");
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.EndRow();
        }
        appender.Flush();
        
        res = con.Query(update);
        std::cout << " upsert=" << res->GetValue(0, 0).ToString();
        res = con.Query("DELETE FROM updates;");
        std::cout << " delete=" << res->GetValue(0, 0).ToString();
        std::cout << " count=" << con.Query("SELECT count(*) FROM main;")->GetValue(0, 0).ToString();

        m_updateCnt = 0;

        std::cout << std::endl;
    }

    return 0;
}
```

### OS:

Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

C++

### Full Name:

Shadab Zafar

### Affiliation:

Tower Research Capital

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by dufferzafar** [comment]
To further reduce the above code, and highlight that the problem is in the Appender somewhere, this inserts 1M rows per loop and then empties the table. Memory rises very quickly, ~800MB per loop!

Am I doing something wrong here?

```cpp
#include "/vendor/duckdb/duckdb.hpp"

#include <iostream>
#include <memory>
#include <random>
#include <string>
#include <unordered_map>

using namespace duckdb;

int main()
{
    std::unordered_map<std::string, std::string> options = {{"threads", "2"}};
    auto config = DBConfig(options, false);

    DuckDB     db(nullptr, &config);
    Connection m_con(db);

    auto res = m_con.Query(R"(
        CREATE TABLE updates(
            id UINTEGER, k1 VARCHAR, k2 VARCHAR, k3 UINTEGER, k4 VARCHAR,
            f1 DOUBLE, f2 DOUBLE, f3 DOUBLE, f4 DOUBLE, f5 DOUBLE, f6 DOUBLE,
        );
    )");

    long m_updateCnt{0};

    while (true)
    {
        Connection m_con(db);
        duckdb::Appender appender(m_con, "updates");
        for (size_t i = 1; i < 1'000'000; i++)
        {
            appender.BeginRow();
            appender.Append<uint32_t>(++m_updateCnt);
            appender.Append<duckdb::string_t>("Group");
            appender.Append<duckdb::string_t>("Case");
            appender.Append<uint32_t>(i);
            appender.Append<duckdb::string_t>("Record");
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.Append<double>(i);
            appender.EndRow();
        }
        appender.Close();

        // Empty the updates table
        res = m_con.Query("DELETE FROM updates;");
        std::cout << " delete=" << res->GetValue(0, 0).ToString();

        m_updateCnt = 0;
        std::cout << std::endl;
    }

    return 0;
}
```

**Comment by Mause** [comment]
I think your main issues here are that you're using an in-memory database, and are never running a `vacuum`/cleanup. Try correcting those?

**Comment by dufferzafar** [comment]
The docs state that VACCUM does nothing! https://duckdb.org/docs/sql/statements/vacuum

But yeah, using `DROP TABLE updates` instead of `DELETE FROM updates` keeps the memory stable!

**Comment by Mytherin** [comment]
Thanks for the report - currently row groups are vacuumed during checkpointing which will never happen for in-memory databases, so it makes sense that the memory is not freed up in this scenario.

**Comment by dufferzafar** [comment]
@Mytherin I read somewhere that `UPDATE` are implemented as delete & insert. So does that mean if we're using an in-memory DB and make heavy usage of `UPDATE` or `INSERT ON CONFLICT SET` queries, we'll see increasing memory usage?

Are there any plans to add vacuum for in-memory DBs as well?

**Comment by Mytherin** [comment]
> @Mytherin I read somewhere that `UPDATE` are implemented as delete & insert. So does that mean if we're using an in-memory DB and make heavy usage of `UPDATE` or `INSERT ON CONFLICT SET` queries, we'll see increasing memory usage?

Update is only implemented as a delete & insert in specific cases (when there is an index on the column that is updated, or if you are updating an `ARRAY` or other composite type). In general updating is a separate operation. 

> Are there any plans to add vacuum for in-memory DBs as well?

Yes this is planned in the future.

**Comment by ngrj93** [comment]
Can we please expedite the implementation of this? We would really like to use duckdb in-memory with deletes freeing memory as expected.

**Comment by Mause** [comment]
> Can we please expedite the implementation of this? We would really like to use duckdb in-memory with deletes freeing memory as expected. 

Please have a read of our [support policy](https://duckdblabs.com/news/2023/10/02/support-policy.html), specifically:

> There is no guarantee w.r.t. response time to the reports nor is there any guarantee that issues will be resolved (e.g., fixed) within any time frame.

**Comment by 2-5** [comment]
`VACUUM` doesn't seem to help:

```python
import os
from datetime import datetime, timedelta

import duckdb
import psutil
import polars as pl

COUNT = 1_000_000

start_date = datetime(2020, 1, 1)
end_date   = start_date + timedelta(minutes=COUNT)

df = pl.DataFrame(dict(a=pl.int_range(0, COUNT, eager=True)))

conn = duckdb.connect()
conn.execute("CREATE TABLE tbl (a INTEGER)")

process = psutil.Process(os.getpid())

while True:
    used_memory_gb = process.memory_info().rss / (1024*1024*1024)
    print(f"{used_memory_gb:.2f} GB")

    conn.execute("DELETE FROM tbl")
    conn.execute("INSERT INTO tbl SELECT * FROM df")
    conn.execute("VACUUM tbl")
```

**Comment by atodekangae** [comment]
Hello, I'm also encountering this issue. I run a query server backed by DuckDB, which reloads tables into memory periodically to provide clients with up-to-date data. I noticed that using CREATE OR REPLACE doesn't free the memory allocated for the old tables. To address this, I implemented a workaround: I recreate a DuckDB connection and replace the variable holding the old connection with the new one. It's a bit clunky, but it appears to be effective.

**Comment by szarnyasg** [comment]
PR #9931 implements vacuuming partial deletes during CHECKPOINT

**Comment by nervmor** [comment]
> Hello, I'm also encountering this issue. I run a query server backed by DuckDB, which reloads tables into memory periodically to provide clients with up-to-date data. I noticed that using CREATE OR REPLACE doesn't free the memory allocated for the old tables. To address this, I implemented a workaround: I recreate a DuckDB connection and replace the variable holding the old connection with the new one. It's a bit clunky, but it appears to be effective.

I use appender to write data to a file base duckdb version v0.9.2 by go-duckdb. The same problem happened, the memory do not free after append Flush and Close.  
Now I could fix it as you do, hope it works.
