### ISSUE TITLE
array slicing changed after upgrade to 0.9

### ISSUE THREAD

**Issue by svherrma** [duckdb/duckdb#9267]
### What happens?

the behavior of slicing changed. on version 0.8 the result of 'stringtoslice'[:-1]  was 'stringtoslic'.
now the same command returns  'stringtoslice'.

### To Reproduce

run the same query on 0.8 and then on 0.9 to get different results

import duckdb as db

qry= """
SELECT
    'stringtoslice'[:-1] 
from
    information_schema.schemata
GROUP BY 1
"""
print(db.query(qry))

### OS:

Ubuntu x86_64

### DuckDB Version:

0.9

### DuckDB Client:

Python

### Full Name:

Sven Herrmannsdörfer

### Affiliation:

BAUR Versand

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I believe this stems from <https://github.com/duckdb/duckdb/pull/8087>

If I remember correctly the reason for this change is that DuckDB follows the SQL convention of being 1-indexed.
In that context it makes more sense that `-1` becomes the last index of the list/string, and the range syntax is inclusive so this results in returning the entire string/list when using like `<string/list>[:-1]`

**Comment by svherrma** [comment]
@Tishj thanks for the explanation. 👍  This makes sense for me.
so the indexing by 1 will be now the standard for coming versions, so i can adjust our scripts to this?

thanks in advange

**Comment by maiadegraaf** [comment]
Yes, indexing by 1 will stay the standard for forward and backward slicing. Hope that answers your question :)
