### ISSUE TITLE
Issue reading time with timezone comparing with 0.8 version

### ISSUE THREAD

**Issue by skeept** [duckdb/duckdb#9280]
### What happens?

When reading a parquet file in version 0.8 for a column of type 'time with timezone' the output is

   ```
D select * from 'test.parquet';
┌─────────────────────┐
│         tt          │
│ time with time zone │
├─────────────────────┤
│ 14:30:00+00         │
│ 11:35:00+00         │
│ 01:59:00+00         │
└─────────────────────┘
```

With new version this is what I get:
```
D select * from 'test.parquet';
┌────────────────────────────┐
│             tt             │
│    time with time zone     │
├────────────────────────────┤
│ 00:00:00.003111+130:10:24  │
│ 00:00:00.002485+834:57:20  │
│ 00:00:00.000425+1130:46:40 │


└────────────────────────────┘
```

I also read the same table with pandas and polars and got the same result as with duckdb 0.8.
The attached file can reproduce these issues

[test.zip](https://github.com/duckdb/duckdb/files/12848562/test.zip)

### To Reproduce

run with version 0.9:

`select * from 'test.parquet';`

### OS:

linux

### DuckDB Version:

0.9

### DuckDB Client:

command line 

### Full Name:

Jorge Rodrigues

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Sorry we changed the internal representation to be compatible with PG, but there are some loose ends.

**Comment by skeept** [comment]
Sure hopefully this can be fixed in a future release, for now I guess I have to stick with 0.8 version as I cannot analyze data correctly.

Thank you!

**Comment by hawkfish** [comment]
Looks like I tried to track this and failed...Simple fix.

**Comment by hawkfish** [comment]
@skeept Thanks for catching this - its not a common type. Should be in 0.9.1.

**Comment by skeept** [comment]
Thank you @hawkfish. Awaiting for 0.9.1 release. Regards
