### ISSUE TITLE
Failed `LIKE` expression on parquet file

### ISSUE THREAD

**Issue by ethack** [duckdb/duckdb#9297]
### What happens?

I have two parquet files containing essentially the same content. One works and the other gives an error when trying to use `LIKE` .

```
D select * from 'working.parquet';
┌────────────────┐
│  server_name   │
│    varchar     │
├────────────────┤
│ www.google.com │
└────────────────┘

D select * from 'non-working.parquet';
┌────────────────┐
│  server_name   │
│      blob      │
├────────────────┤
│ www.google.com │
└────────────────┘

D select * from 'working.parquet' where server_name like '%.google.com';
┌────────────────┐
│  server_name   │
│    varchar     │
├────────────────┤
│ www.google.com │
└────────────────┘

D select * from 'non-working.parquet' where server_name like '%.google.com';
Error: Binder Error: No function matches the given name and argument types '~~(BLOB, VARCHAR)'. You might need to add explicit type casts.
        Candidate functions:
        ~~(VARCHAR, VARCHAR) -> BOOLEAN

LINE 1: ...non-working.parquet' where server_name like '%.google.com';
```

I noted the `BLOB` in the output above and thought to check for schema differences, but I can't spot any.

```json
D .mode json

D select * from parquet_schema('working.parquet');
[{"file_name":"working.parquet","name":"duckdb_schema","type":null,"type_length":null,"repetition_type":"REQUIRED","num_children":1,"converted_type":null,"scale":null,"precision":null,"field_id":null,"logical_type":null},
{"file_name":"working.parquet","name":"server_name","type":"BYTE_ARRAY","type_length":null,"repetition_type":"OPTIONAL","num_children":null,"converted_type":"UTF8","scale":null,"precision":null,"field_id":null,"logical_type":null}]

D select * from parquet_schema('non-working.parquet');
[{"file_name":"non-working.parquet","name":"duckdb_schema","type":null,"type_length":null,"repetition_type":"REQUIRED","num_children":1,"converted_type":null,"scale":null,"precision":null,"field_id":null,"logical_type":null},
{"file_name":"non-working.parquet","name":"server_name","type":"BYTE_ARRAY","type_length":null,"repetition_type":"OPTIONAL","num_children":null,"converted_type":null,"scale":null,"precision":null,"field_id":null,"logical_type":null}]
```

### To Reproduce

I have produced minimal parquet files, though my originals were larger and generated using different programs. Both were passed through duckdb with a `select sever_name from ... limit 1` to create the minimal versions here. They are gzipped to allow uploading to Github so you must unzip them first.

[working.parquet.gz](https://github.com/duckdb/duckdb/files/12860676/working.parquet.gz)
[non-working.parquet.gz](https://github.com/duckdb/duckdb/files/12860677/non-working.parquet.gz)

```
feae070af908a16315f32dda9714eeda  non-working.parquet
91e6517a7621bba04e3e3ac930a99bba  working.parquet
```

### Steps
1. Download the two attached parquet files.
2. Run `gunzip *.parquet.gz` to extract both of them.
3. Using the duckdb cli run the following commands.

```bash
duckdb -s "select * from 'working.parquet' where server_name like '%.google.com'"
duckdb -s "select * from 'non-working.parquet' where server_name like '%.google.com'"
```

The first will output
```
┌────────────────┐
│  server_name   │
│    varchar     │
├────────────────┤
│ www.google.com │
└────────────────┘
```

The second will output
```
Error: Binder Error: No function matches the given name and argument types '~~(BLOB, VARCHAR)'. You might need to add explicit type casts.
        Candidate functions:
        ~~(VARCHAR, VARCHAR) -> BOOLEAN

LINE 1: ...non-working.parquet' where server_name like '%.google.com'
```

### OS:

Ubuntu 22.10

### DuckDB Version:

v0.9.0 0d84ccf478

### DuckDB Client:

CLI

### Full Name:

Ethan Robish

### Affiliation:

Black Hills Info Sec

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I'm pretty sure this is just expected behavior
If the column is a BLOB then it doesn't support `LIKE` as the error states.

You might be able to cast it to VARCHAR if it's valid utf8 and then perform the LIKE

**Comment by ethack** [comment]
I missed the `blob` in the ascii table right below the `server_name`. 🤦

You're right that casting it works.

```
$ duckdb -s "select * from 'non-working.parquet' where cast(server_name as varchar) like '%.google.com'"
┌────────────────┐
│  server_name   │
│      blob      │
├────────────────┤
│ www.google.com │
└────────────────┘
```

Also interesting is that there seems to be implicit casting when they are queried together. Just by changing the order of the files it changes the implicit cast.

```
D select * from parquet_scan(['working.parquet', 'non-working.parquet']);
┌────────────────┐
│  server_name   │
│    varchar     │
├────────────────┤
│ www.google.com │
│ www.google.com │
└────────────────┘

D select * from parquet_scan(['non-working.parquet', 'working.parquet']);
┌────────────────┐
│  server_name   │
│      blob      │
├────────────────┤
│ www.google.com │
│ www.google.com │
└────────────────┘
```

I just noticed that the working `varchar` file has `"converted_type":"UTF8"` in the schema output while the non-working `blob` file has `"converted_type":null`. That must be the difference and what I need to fix.

Thank you.

**Comment by douenergy** [comment]
@Tishj  What do you think about extending the "LIKE" operator to the blob type? ? 
https://github.com/duckdb/duckdb/discussions/2114  (seems like a nice feature ) 

Mabye i can try extend the LIKE operator 😊
