### ISSUE TITLE
wrong result: NOT EXISTS predicate with correlated non-equality comparison

### ISSUE THREAD

**Issue by stevenpelley** [duckdb/duckdb#9308]
### What happens?

A query with a correlated non-equality comparison in WHERE NOT EXISTS is not returned by the outer SELECT despite matching no rows in the correlated subquery.  See reproduction.

### To Reproduce

```
create or replace table t1(c1 int64);
insert into t1 values (1);
create or replace table t2(c1 int64);
-- shows that the "not exists" expression evaluates to true
select c1, not exists (select 1 from t2 where t1.c1 <= t2.c1) from t1; 
-- 0 rows appear in the output
select c1 from t1 where not exists (select 1 from t2 where t1.c1 <= t2.c1);
```

The first SELECT produces:
```
┌───────┬───────────────────────────────────────────────────────┐
│  c1   │ (NOT EXISTS(SELECT 1 FROM t2 WHERE (t1.c1 <= t2.c1))) │
│ int64 │                        boolean                        │
├───────┼───────────────────────────────────────────────────────┤
│     1 │ true                                                  │
└───────┴───────────────────────────────────────────────────────┘
```
showing that the NOT EXISTS evaluates to true

The 2nd select results in:
```
┌────────┐
│   c1   │
│ int64  │
├────────┤
│ 0 rows │
└────────┘
```

I believe this should return the 1 row.

### OS:

aarch64

### DuckDB Version:

0.9.1, main branch (downloaded Oct 11, 2023)

### DuckDB Client:

CLI

### Full Name:

Steven Pelley

### Affiliation:

independent

### Have you tried this on the latest `main` branch?

I have tested on the latest `main` branch

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for reporting it and especially thanks for making it easy to reproduce.

**Comment by kunalnabar** [comment]
It may also be worth noting that this issue only manifests when the table that's queried by the inner SELECT is empty. The behavior in this case is correct: 

```
create or replace table t1(c1 int64);
insert into t1 values (1);
create or replace table t2(c1 int64);
insert into t2 values (0);
-- shows that the "not exists" expression evaluates to true
select c1, not exists (select 1 from t2 where t1.c1 <= t2.c1) from t1; 
-- 1 row appears in the output as long as t2 is not empty
select c1 from t1 where not exists (select 1 from t2 where t1.c1 <= t2.c1);
```

The 1st result is the same: 

```
┌───────┬───────────────────────────────────────────────────────┐
│  c1   │ (NOT EXISTS(SELECT 1 FROM t2 WHERE (t1.c1 <= t2.c1))) │
│ int64 │                        boolean                        │
├───────┼───────────────────────────────────────────────────────┤
│     1 │ true                                                  │
└───────┴───────────────────────────────────────────────────────┘
```

The 2nd result is correct:
```
┌───────┐
│  c1   │
│ int64 │
├───────┤
│     1 │
└───────┘
```

I also tested this with multiple rows in t1—if t2 is empty the WHERE NOT EXISTS query will always result in 0 rows.
