### ISSUE TITLE
Row function appears to lose column names

### ISSUE THREAD

**Issue by jonathanswenson** [duckdb/duckdb#9317]
### What happens?

In previous versions the row function appeared to extract the specified columns as a struct where the "columns" in the struct appear to be referencable by name. 

on 0.8.1
```
D with users as (select 1 as id, 'foo' as name, 37 as age union all select 2, 'bar', 30 union all select 3, 'baz', 29)
select row(id, name, age) FROM users;
┌─────────────────────────────────────────────────┐
│            main.row(id, "name", age)            │
│ struct(id integer, "name" varchar, age integer) │
├─────────────────────────────────────────────────┤
│ {'id': 1, 'name': foo, 'age': 37}               │
│ {'id': 2, 'name': bar, 'age': 30}               │
│ {'id': 3, 'name': baz, 'age': 29}               │
└─────────────────────────────────────────────────┘
```

Now the struct appears to be returned with all of the struct column (member?) names set to the empty string/ 

on 0.9.1 (and 0.9.0 and most recent main build from https://duckdb.org/docs/installation/ - Bleeding Edge)
```
D with users as (select 1 as id, 'foo' as name, 37 as age union all select 2, 'bar', 30 union all select 3, 'baz', 29)
> select row(id, name, age) FROM users;
┌──────────────────────────────────────┐
│      main.row(id, "name", age)       │
│ struct( integer,  varchar,  integer) │
├──────────────────────────────────────┤
│ {'': 1, '': foo, '': 37}             │
│ {'': 2, '': bar, '': 30}             │
│ {'': 3, '': baz, '': 29}             │
└──────────────────────────────────────┘
```

### To Reproduce

Sql: 
```
with users as (
  select 1 as id, 'foo' as name, 37 as age union all 
  select 2, 'bar', 30 union all 
  select 3, 'baz', 29
)
select row(id, name, age) FROM users;
```

### OS:

Mac 13.4.1 aarch64

### DuckDB Version:

0.9.1, 0.9.0

### DuckDB Client:

cli, java, shell

### Full Name:

Jonathan Swenson

### Affiliation:

Omni

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by jonathanswenson** [comment]
Was able to workaround with `struct_pack`, but haven't found a way to make `row` do what it used to. 

```
with users as (
  select 1 as id, 'foo' as name, 37 as age union all select 2, 'bar', 30 union all select 3, 'baz', 29
) select struct_pack(id := id, name := name, age := age) FROM users
```

**Comment by Tishj** [comment]
This is intended, we recently made structs a more strict type when it comes to casting logic, now the names need to match.
To still keep the ROW behavior the same though, this now produces an unnamed struct, so it can still be inserted into any struct without the need to specify the struct names.

https://github.com/duckdb/duckdb/pull/8942

struct_pack is currently the only way to achieve this, though we'll likely add additional syntax that makes this easier in the future

**Comment by szarnyasg** [comment]
Currently this is intended behavior, the row function returns unnamed structs similar to what Postgres does, use `struct_pack` to create named structs.
