### ISSUE TITLE
Incorrect use of Pivot causes FATAL Error

### ISSUE THREAD

**Issue by hohenstrater** [duckdb/duckdb#9325]
### What happens?

If i use the following PIVOT SQL

`PIVOT '250606354' on row_number using SUM(CurrInstE1),SUM(CurrInstE1) order by 1,2,3 `

it causes this error

`SQL Error: java.sql.SQLException: INTERNAL Error: Pivot aggregate count mismatch (expected 2, found 1)`

which is fine as i am trying to sum two values. However, if I correct the mistake in the same session to 

`PIVOT '250606354' on row_number using SUM(CurrInstE1) order by 1,2,3`

```
SQL Error: java.sql.SQLException: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "INTERNAL Error: Pivot aggregate count mismatch (expected 2, found 1)"
```

### To Reproduce

`PIVOT '250606354' on row_number using SUM(CurrInstE1),SUM(CurrInstE1) order by 1,2,3 `

`PIVOT '250606354' on row_number using SUM(CurrInstE1) order by 1,2,3`

### OS:

Windows

### DuckDB Version:

0.9

### DuckDB Client:

DBBeaver

### Full Name:

Thorsten

### Affiliation:

 Hobby

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for raising this issue. Could you please produce a reproducible example with some sample data?

**Comment by hohenstrater** [comment]
[#9325.csv](https://github.com/duckdb/duckdb/files/12880686/9325.csv)

PIVOT '#9325.csv' on day using SUM(Random_values),SUM(Random_values) order by 1,2,3;
PIVOT '#9325.csv' on day using SUM(Random_values) order by 1,2,3;

**Comment by szarnyasg** [comment]
Thanks!
