### ISSUE TITLE
No space required between sample and limit

### ISSUE THREAD

**Issue by Dtenwolde** [duckdb/duckdb#9332]
### What happens?

The following query contains a typo but provides the correct result nonetheless: 
```sql
SELECT * FROM foo using sample 10limit 5; 
```
The expected result should be a ParserException I think. 
It provides the same result as: 
```sql
SELECT * FROM foo using sample 10 limit 5; 
```

### To Reproduce

`./build/release/duckdb`

```sql
create or replace table foo as from generate_series(1,10);

select * from foo using sample 5limit 5;
```

### OS:

Linux

### DuckDB Version:

v0.9.2-dev14 0ef2a6faa2

### DuckDB Client:

CLI

### Full Name:

Daniel ten Wolde

### Affiliation:

CWI

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
Expected behaviour and other SQL engines also are flexible there
