### ISSUE TITLE
read_csv_auto doesn't respect nullstr

### ISSUE THREAD

**Issue by dandelion12345** [duckdb/duckdb#9333]
### What happens?

if you have a csv file with column containing "true", "false", and "\N" values, when you use read_csv_auto() it defines the column type as VARCHAR _despite passing in the nullstr parameter_ (as specified in the docs).

expected behavior would be that it would define the column type as BOOLEAN.

the reason this is problematic is that we're using duckdb to convert csv to parquet, and we would like the data type of the parquet file to be BOOLEAN for these scenarios.

### To Reproduce

see above

### OS:

x86

### DuckDB Version:

latest?

### DuckDB Client:

cli

### Full Name:

Daniel Ro

### Affiliation:

Uber

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @dandelion12345 can you provide more information:
1. A sample of the problematic data-set 
2. The exact query
3. Which OS

```
Booleans, Numbers
False, 1
True, 2
\N, 3
True, 2
```

```
query II
select typeof(#1), typeof(#2) from read_csv_auto('data/csv/null_str.csv', nullstr='\N') limit 1
----
BOOLEAN	BIGINT

query II
select * from read_csv_auto('data/csv/null_str.csv', nullstr='\N')
----
false	1
true	2
NULL	3
true	2
```

The example above executes fine.

In any case, you can always define a `types={'column_name': 'column_type'}` to force the replacement of types found by the sniffer.

**Comment by dandelion12345** [comment]
hi @pdet you're absolutely right. I just now realized we made a mistake where I had misdefined the nullstr as "\\N" when it should've been "\N". I feel really dumb haha.

Thank you so much for your prompt reply, its much appreciated!

**Comment by pdet** [comment]
> hi @pdet you're absolutely right. I just now realized we made a mistake where I had misdefined the nullstr as "\N" when it should've been "\N". I feel really dumb haha.
> 
> Thank you so much for your prompt reply, its much appreciated!

No worries! Glad it worked out! :)
