### ISSUE TITLE
When two application try to update a table in one duckdb file, one application will get a error, Read permission issue

### ISSUE THREAD

**Issue by nagarajmmu** [duckdb/duckdb#9334]
### What happens?

Hi Team

We are using a duckdb in our application, our application have three apps.
If APP1 is writing/updating a table called XYZ in **category.duckdb** DuckDB file, at the same time APP2 is reading a same table, but while reading file APP2 is getting a below error.

Error: (duckdb.IOException) IO Error: Could not read from file \"/xyz.duckdb\": Permission denied\n(Background on this error at: https://sqlalche.me/e/14/e3q8)

Please let us know how to resolve this error.

Thanks in advance
 Nagaraj M M

### To Reproduce

Reproduce:
If APP1 is writing/updating a table called XYZ in **category.duckdb** DuckDB file, at the same time APP2 is reading a same table, but while reading file APP2 is getting a below error.

Error: (duckdb.IOException) IO Error: Could not read from file \"/xyz.duckdb\": Permission denied\n(Background on this error at: https://sqlalche.me/e/14/e3q8)

### OS:

Ubuntu

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

Nagaraja Mallikarjuna Majjagi

### Affiliation:

ABC

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hi,

I think this should help explain the issue:
https://duckdb.org/faq#how-does-duckdb-handle-concurrency

To summarize: only when both processes open a read-only connection is this type concurrency supported.
When a read-write connection is opened, no other connection (not even read-only) can be opened on that database
