### ISSUE TITLE
order by to parquet with memory limit runs out of memory in v0.9.1 (not v0.8.1) 

### ISSUE THREAD

**Issue by egillax** [duckdb/duckdb#9348]
### What happens?

When using order by with a memory limit of 1GB (and up to 5GB) and copying the results to a parquet file I get an out of memory error:

```D set memory_limit="1GB";
D copy (select * from condition_occurrence order by condition_concept_id, condition_end_date) to './results.parquet';
 49% ▕█████████████████████████████▍                              ▏ Error: Out of Memory Error: failed to allocate data of size 2.8MB (1.0GB/1.0GB used)
```
This does not happen in version 0.8.1 with the same code.

### To Reproduce

Download the `condition_occurrence` csvs from the following s3 bucket:

```
aws s3 cp --no-sign-request s3://synthea-omop/synthea23m/condition_occurrence.csv.0.lzo .
aws s3 cp --no-sign-request s3://synthea-omop/synthea23m/condition_occurrence.csv.1.lzo .
aws s3 cp --no-sign-request s3://synthea-omop/synthea23m/condition_occurrence.csv.2.lzo .
aws s3 cp --no-sign-request s3://synthea-omop/synthea23m/condition_occurrence.csv.3.lzo .
```
decompress and load into duckdb as `condition_occurrence`. Then execute:

```
set memory_limit="1GB";
COPY (SELECT * FROM condition_occurrence ORDER BY condition_concept_id, condition_end_date) TO './results.parquet';
```
Using latest release version`v0.9.1 401c8061c6`  and github 'v0.9.2-dev14 0ef2a6faa2` I run out of memory but not with version `v0.8.1 6536a77232`

It works fine if I don't copy the results to parquet. It's not dependent on  this data since I initially got this error in the R client using a different non-public dataset.

### OS:

Ubuntu 23.10

### DuckDB Version:

v0.9.1 401c8061c6 and v0.9.2-dev14 0ef2a6faa2

### DuckDB Client:

CLI and R

### Full Name:

Egill Fridgeirsson

### Affiliation:

Erasmus MC 

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
a small reproductable example
v0.9.1 raises error
```
D:\duckdb>duckdb091 test091
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D set memory_limit="100MB";
D create table t100m as select i::int32 i from range(25000000)t(i);
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬──────────────┬─────────────┬─────
────────┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │    int64     │    int64    │    int64    │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼──────────────┼─────────────┼─────
────────┼──────────┼──────────────┼──────────────┤
│ test091       │ 524KB         │     262144 │            2 │           2 │           0 │ 0 bytes  │ 524KB        │ 100.0MB      │
└───────────────┴───────────────┴────────────┴──────────────┴─────────────┴─────
────────┴──────────┴──────────────┴──────────────┘
D COPY (SELECT * FROM t100m ORDER BY i) TO './t100m.parquet';
 49% ▕█████████████████████████████▍                              ▏ Error: Out of Memory Error: failed to allocate data of size
16KB (100.2MB/100.0MB used)
D .exit
```
v0.8.1 is ok
```
D:\duckdb>duckdb081 test081
v0.8.1 6536a77232
Enter ".help" for usage hints.
D set memory_limit="100MB";
D create table t100m as select i::int32 i from range(25000000)t(i);
D PRAGMA database_size;
┌───────────────┬───────────────┬────────────┬──────────────┬─────────────┬─────
────────┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │    int64     │    int64    │    int64    │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼──────────────┼─────────────┼─────
────────┼──────────┼──────────────┼──────────────┤
│ test081       │ 1.0MB         │     262144 │            4 │           4 │           0 │ 0 bytes  │ 262KB        │ 100.0MB      │
└───────────────┴───────────────┴────────────┴──────────────┴─────────────┴─────
────────┴──────────┴──────────────┴──────────────┘
D COPY (SELECT * FROM t100m ORDER BY i) TO './t100m081.parquet';
100% ▕████████████████████████████████████████████████████████████▏
```
result files
```
D .system dir t100m*parquet

2023/10/16  09:41        36,868,096 t100m.parquet
2023/10/16  09:43       100,027,161 t100m081.parquet
```

**Comment by l1t1** [comment]
why the table created but seems not saved in the database files? the full parquet is 100MB, but the data files are very small (512K or 1MB)
```
D .system dir duck091 duck081

2023/10/17  15:12           536,576 duck091

2023/10/17  15:13         1,060,864 duck081
```

**Comment by szarnyasg** [comment]
@l1t1 thanks for the small reproducible example.

> why the table created but seems not saved in the database files? the full parquet is 100MB, but the data files are very small (512K or 1MB)

The data is compressed and DuckDB picks up a close to ideal compression method for the continuous range of numbers.

**Comment by Mytherin** [comment]
Thanks for the report! This is not actually a bug, but a bug-fix. In v0.8.1 the memory of the `COPY` to parquet was not correctly tracked, so while the statement succeeds with a memory limit of `100MB`, the actual memory usage is significantly higher. In v0.9.1 we added correct tracking of the memory usage to the Parquet writer which now causes this to correctly run out-of-memory instead of silently exceeding the allocated memory limit.
