### ISSUE TITLE
[Python] Spark API requires loading httpfs extension manually

### ISSUE THREAD

**Issue by dacort** [duckdb/duckdb#9349]
### What happens?

When using the Spark API with an S3 URI, a RuntimeError exception is raised unless the httpfs extension is manually loaded.

```
Traceback (most recent call last):
  File "/private/tmp/emr-serverless-samples/examples/pyspark/repro.py", line 13, in <module>
    df = spark.read.csv(f"s3://noaa-gsod-pds/2023/01001099999.csv", header=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/emr-serverless-samples/.venv/lib/python3.11/site-packages/duckdb/experimental/spark/sql/readwriter.py", line 164, in csv
    rel = self.session.conn.read_csv(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: INTERNAL Error: State was not defined in this HTTP File Handle
```

### To Reproduce

You must have AWS credentials configured already. For my test, I exported them as environment credentials using `$(aws configure export-credentials --format env)`

```python
from duckdb.experimental.spark.sql import SparkSession
from duckdb.experimental.spark.sql import functions as F

spark = SparkSession.builder.appName("Weather").getOrCreate()


def load_ext():
    spark.conn.execute(
        f"""
        INSTALL httpfs;
        LOAD httpfs;
    """
    )


# Without httpfs installed, the spark.read fails with the "State was not defined" error.
# With httpfs installed, the query succeeds.
try:
    df = spark.read.csv(f"s3://noaa-gsod-pds/2023/01001099999.csv", header=True)
    print("Load 1", df.count())
except Exception as e:
    print("Load 1 failed: ", e)
    load_ext()
    df = spark.read.csv(f"s3://noaa-gsod-pds/2023/01001099999.csv", header=True)
    print("Load 2", df.count())
```

### OS:

macOS Ventura 13.5.2 osx-arm64

### DuckDB Version:

v0.9.1

### DuckDB Client:

Python

### Full Name:

Damon Cortesi

### Affiliation:

AWS

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Thanks for raising this, this is some problem at the intersection between autoloading of httpfs extension and Python specific wrappers that we are aware of.

Workaround is for now explicitly loading the httpfs extension.
