### ISSUE TITLE
ON CONFLICT clause

### ISSUE THREAD

**Issue by wstucco** [duckdb/duckdb#935]
is there a way to replicate how `INSERT OR IGNORE` works in SQLite wih Duckdb?

**Comment by Mytherin** [comment]
This is not yet implemented, see also issue #61. It is on the agenda but currently not an immediate priority.

As a work-around you could do this switch in the client, by doing a `SELECT`, then issuing either an INSERT only if the row does not exist.

**Comment by wstucco** [comment]
thanks

**Comment by hannes** [comment]
Related to #61
