### ISSUE TITLE
Cannot index `BLOB`s with null bytes anywhere in them.

### ISSUE THREAD

**Issue by mima-hlavacek** [duckdb/duckdb#9369]
### What happens?

When you try to create an index on a BLOB column, you get an error if any value contains a null byte anywhere. The error states that BLOB indexes cannot contain null-terminated values. But the values are not null-terminated, there is just a byte that is legitimately zero.

```
Error: TransactionContext Error: Failed to commit: Not implemented Error: Indexes cannot contain BLOBs that contain null-terminated bytes.
```

### To Reproduce

```sql
create table indexed_table(indexed_field blob);
create index blob_index on indexed_table(indexed_field);
insert into indexed_table values ('\x11\x00\x11'::blob);
```

### OS:

Ubuntu x64 in WSL on Windows 11

### DuckDB Version:

v0.9.2-dev51 2646836f6f

### DuckDB Client:

cli

### Full Name:

Míma Hlaváček

### Affiliation:

Blindspot.ai

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by taniabogatsch** [comment]
Hey @mima-hlavacek, thanks for the report. You are right; the error message is misleading here. Indeed, duckdb does not support indexing `BLOBs` with null bytes. We commented on this [here](https://github.com/duckdb/duckdb/issues/5865#issuecomment-1420845237), but I eventually closed the issue and split it into smaller internal backlog entries. One of them concerns solutions to allow zero bytes in the ART. But as of now, we have not addressed it; therefore, the `not implemented` error.

I will open a small PR to improve the error message!

**Comment by yifanwu** [comment]
Curious why this was not a limitation for version 0.6? --- The doc for 0.6 has ART index https://duckdb.org/docs/archive/0.6.1/sql/indexes.

Context: we currently store a python pickle as a primary key and hits this error message for newer versions, but not 0.6

**Comment by taniabogatsch** [comment]
@yifanwu, if I remember correctly, we did not catch this behavior in 0.6. Indexes were a much newer feature back then. I think I introduced the `NotImplementedException` as a response to a bug where the ART returned incorrect results because it silently failed on the null bytes.
