### ISSUE TITLE
Compressed CSV COPY TO S3 Fails Silently - Never Completes Multipart Upload

### ISSUE THREAD

**Issue by brianwyka** [duckdb/duckdb#9376]
### What happens?

When performing an S3 `COPY TO` for a compressed CSV export, the command succeeds in interactive cli session, however, no object is uploaded to S3 bucket.  I verified that the AWS cli that the multipart upload is "hanging" and never completed.  

I did a test with no compression and the command succeeds, as well as the upload to S3.

**Extensions Being Used**
- `httpfs`
- `aws`

### To Reproduce

See attached [ducks.csv](https://github.com/duckdb/duckdb/files/12929577/ducks.csv) for usage.

### DuckDB CLI
```sql
LOAD httpfs;
LOAD aws;
CALL load_aws_credentials('duckdb');
CREATE TABLE ducks AS FROM read_csv_auto('ducks.csv', header=true);
COPY ducks TO 's3://<bucket>/ducks.csv.gz' (COMPRESSION GZIP);
```

### AWS CLI:
```sh
aws --profile duckdb s3api list-multipart-uploads --bucket <bucket> | jq
```

### AWS CLI Output (redacted):
```json
{
  "Uploads": [
    {
      "UploadId": "...",
      "Key": "ducks.csv.gz",
      "Initiated": "2023-10-17T13:38:51+00:00",
      "StorageClass": "STANDARD",
      "Owner": {
        "DisplayName": "...",
        "ID": "..."
      },
      "Initiator": {
        "ID": "...",
        "DisplayName": "..."
      }
    }
  ],
  "RequestCharged": null
}
```

### OS:

mac - Darwin Kernel Version 22.4.0: x86_64 

### DuckDB Version:

0.9.1

### DuckDB Client:

cli

### Full Name:

Brian Wyka

### Affiliation:

LogicMonitor

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
I am not sure how it can be related, but we happened to have just solved an s3/httpfs issue, so maybe it's worth checking if they happen to be related:

Can you try:
```
FORCE INSTALL httpfs FROM 'http://nightly-extensions.duckdb.org';
```
This will install the new official signed version of the httpfs extension from the secondary extension repository.
After that, just try to run your reproduction:
```
LOAD httpfs;
LOAD aws;
CALL load_aws_credentials('duckdb');
CREATE TABLE ducks AS FROM read_csv_auto('ducks.csv', header=true);
COPY ducks TO 's3://<bucket>/ducks.csv.gz' (COMPRESSION GZIP);
```

Can you report back whether this happens to have an impact? It's a long shot but worth trying.

**Comment by brianwyka** [comment]
@carlopi , just tried this and it did not resolve the issue.

**Comment by brianwyka** [comment]
Same thing with `parquet` works, so perhaps something specific to the `CSV` handling.

**Comment by melloflavio** [comment]
I have the same issue. Exporting plain CSV works, while exporting a compressed csv fails silently.
I am using the python sdk and tested with the following scenarios:

Auto
```
relation.to_csv(file_name="s3://<bucket>/filename.csv.gz", header=True, sep=",") 
```

Explicit - .csv.gz
```
relation.to_csv(file_name="s3://<bucket>/filename.csv.gz", header=True, sep=",", compression="gzip")
```

Explicit - .csv
```
relation.to_csv(file_name="s3://<bucket>/filename.csv.gz", header=True, sep=",", compression="gzip")
```

**Comment by samansmink** [comment]
Thanks for reporting everyone! I just confirmed this fix https://github.com/duckdb/duckdb/pull/9758 also solves this issue
