### ISSUE TITLE
Exception failure in read_parquet when multiple files are in the used in the query

### ISSUE THREAD

**Issue by tlw1876** [duckdb/duckdb#9379]
### What happens?

```python
import duckdb
queryString = 'SELECT part_num, model_num, test_level, computer_name, dev_start_datetime, traveler, locator, system_id, lot_num, serial_num, mfg_lot_num, emp_id, test_site_num, test_mode, pf_stat, ff_bin, rwk_flag, swo_num, fixtures, ui, "3.2000" FROM read_parquet([\'\\\\stpnas05\\test_data\\583131\\prod\\data\\202303\\582315-205-A\\data\\ANAASIC_E2,400210-105.parquet\', \'\\\\stpnas05\\test_data\\583131\\prod\\data\\202304\\582315-205-A\\data\\ANAASIC_E2,400210-105.parquet\', \'\\\\stpnas05\\test_data\\583131\\prod\\data\\202305\\582315-205-A\\data\\ANAASIC_E2,400210-105.parquet\']) where dev_start_datetime >= 1677628800.000000 and dev_start_datetime < 1682985600.000000'
duckdb.query(queryString).df()
```
This results in the exception string: Conversion Error: Could not convert string '`' to INT32
NOTE: If I separate the parquet reads by individual parquet file read, duckdb works fine.
NOTE: This is a manufacturing process and the parquet files are arranged by part number and manufacturing month, so discrete file names are used for loading.
NOTE: This error is data dependent and works fine for some parts and month ranges up to 12.

### To Reproduce

This will be difficult to reproduce at another site.  I've tried individual reads of the parquet files without problem using duckdb and direct from pandas without problems.
```python
parquetNameStr = "'\\\\stpnas05\\test_data\\583131\\prod\\data\\202303\\582315-205-A\\data\\ANAASIC_E2,400210-105.parquet', '\\\\stpnas05\\test_data\\583131\\prod\\data\\202304\\582315-205-A\\data\\ANAASIC_E2,400210-105.parquet', '\\\\stpnas05\\test_data\\583131\\prod\\data\\202305\\582315-205-A\\data\\ANAASIC_E2,400210-105.parquet'"
query = 'dev_start_datetime >= 1677628800.000000 and dev_start_datetime < 1682985600.000000'
colNameStr = 'part_num, model_num, test_level, computer_name, dev_start_datetime, traveler, locator, system_id, lot_num, serial_num, mfg_lot_num, emp_id, test_site_num, test_mode, pf_stat, ff_bin, rwk_flag, swo_num, fixtures, ui, "3.2000"'
 duckQ = f"SELECT {colNameStr} FROM read_parquet([{parquetFileNameStr}]) where {query}"
df = duckdb.query(duckQ).df()
# Above code causes an exception.
# If I bust up the query into single parquet files, all is well.
```

### OS:

x86

### DuckDB Version:

090.1

### DuckDB Client:

python 3.8

### Full Name:

Tom Williams

### Affiliation:

Boston Scientific

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by tlw1876** [comment]
My workaround right now is to manage this as problem as an exception.  If the exception is hit, I put the parquet read operations into a loop and concat the pandas databases.  That's working fine

**Comment by szarnyasg** [comment]
Hi @tlw1876 there's little we can do without the data set. Can you please drop me an email ( gabor@duckdblabs.com )?

**Comment by cassova** [comment]
I ran into this issue as well. It would be nice to have a flag (when passing in a list of parquet) to ignore faulty files.
