### ISSUE TITLE
"Could not choose a best candidate function for the function call" after upgrading to 0.9

### ISSUE THREAD

**Issue by eitsupi** [duckdb/duckdb#9380]
### What happens?

After upgrading DuckDB from 0.8 to 0.9, I noticed that the definition of the following macro fails.

https://github.com/eitsupi/querying-with-prql/blob/3c9d53d32c487b869db17999aad88b9ed8169ebe/docs/method_chaining.qmd#L163-L169

```
v0.9.2-dev48 7127284469
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE MACRO time_to_datetime(date, string) AS
>   date::TIMESTAMP +
>   TRY_CAST(regexp_replace(string, '^2400$', '0000').substr(1, 2).concat(' hours') AS INTERVAL) +
>   TRY_CAST(regexp_replace(string, '^2400$', '0000').substr(3, 2).concat(' minutes') AS INTERVAL);
Error: Binder Error: Could not choose a best candidate function for the function call "+(NULL, INTERVAL)". In order to select one, please add explicit type casts.
        Candidate functions:
        +(DATE, INTERVAL) -> DATE
        +(TIME, INTERVAL) -> TIME
        +(TIMESTAMP WITH TIME ZONE, INTERVAL) -> TIMESTAMP WITH TIME ZONE
        +(INTERVAL, INTERVAL) -> INTERVAL
```

It was working fine in 0.8, so I think maybe something is going wrong with 0.9.

```
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE MACRO time_to_datetime(date, string) AS
>   date::TIMESTAMP +
>   TRY_CAST(regexp_replace(string, '^2400$', '0000').substr(1, 2).concat(' hours') AS INTERVAL) +
>   TRY_CAST(regexp_replace(string, '^2400$', '0000').substr(3, 2).concat(' minutes') AS INTERVAL);
D
```

### To Reproduce

Execute this SQL

```sql
CREATE MACRO time_to_datetime(date, string) AS
  date::TIMESTAMP +
  TRY_CAST(regexp_replace(string, '^2400$', '0000').substr(1, 2).concat(' hours') AS INTERVAL) +
  TRY_CAST(regexp_replace(string, '^2400$', '0000').substr(3, 2).concat(' minutes') AS INTERVAL);
```

### OS:

Windows, Linux

### DuckDB Version:

0.9

### DuckDB Client:

CLI, R

### Full Name:

SHIMA Tatsuya

### Affiliation:

Personal use

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hmm I agree this behavior is a little strange, and probably a consequence of another change

When binding the expressions for the table macro `string` is of type SQLNULL, because it could be anything.
That in turns probably causes `regexp_replace` to be SQLNULL.

Turning the reference of `string` into `string::VARCHAR` makes the statement succeed for me, is that a valid workaround for your issue?

**Comment by eitsupi** [comment]
> Turning the reference of `string` into `string::VARCHAR` makes the statement succeed for me, is that a valid workaround for your issue?

Thank you for finding this. For me this is a nice workaround at the moment.
