### ISSUE TITLE
Assertion errors when inserting data using read_json()

### ISSUE THREAD

**Issue by rafael-telles** [duckdb/duckdb#9389]
### What happens?

I have an application that inserts lots of data by creating a temporary table than inserting data using a select:

```sql
CREATE TEMPORARY TABLE temp_table AS SELECT * FROM read_json('data.json', columns=...);
INSERT INTO xxx SELECT * FROM temp_table;
```

I did this to avoid calling many `INSERT` statements in a loop and it looked great, however I created a test that loops something like this:

```ts
for (let i = 0; i < 50; i++) {
  const db = await loadDb(path) // opens DuckDB using the default options

  await writeRandomData('data.json')
  await db.exec("CREATE TEMPORARY TABLE temp_table AS SELECT * FROM read_json('data.json', columns=...);")
  await db.exec("INSERT INTO xxx SELECT * FROM temp_table;'")

  await db.exec('CHECKPOINT')
  await db.close()
}
```

(Not the real code, but it's basically opening the database, writing data and closing it in a loop)

On 0.9.1 I get a few different errors that crashes NodeJS:

```
node: ../src/duckdb/src/storage/single_file_block_manager.cpp:370: virtual void duckdb::SingleFileBlockManager::Read(duckdb::Block&): Assertion `std::find(free_list.begin(), free_list.end(), block.id) == free_list.end()' failed.
```

```
Connection Error: Connection was never established or has been closed already
```

```
IO Error: Could not read enough bytes from file "/tmp/persistency_1.db": attempted to read 262144 bytes from location 2371584
```

On 0.8.1 I get this:

```
node: ../src/duckdb/src/execution/index/art/prefix.cpp:351: uint32_t duckdb::Prefix::MismatchPosition(const duckdb::ART&, const duckdb::Prefix&) const: Assertion `other_ptr.IsSet()' failed.
```

### To Reproduce

(I will try to write a separate script that reproduce this)

### OS:

Linux

### DuckDB Version:

0.9.1

### DuckDB Client:

NodeJS

### Full Name:

Rafael Telles

### Affiliation:

Layers Education

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by rafael-telles** [comment]
I figured this out:

Assertion errors occur when I delete this .json files right after creating the tables using read_json(). If I keep the files until I need to delete the table it works!

**Comment by Mytherin** [comment]
Thanks for the report! I've tried to reproduce this but have failed. It would be great if you could provide a reproducible example.

**Comment by rafael-telles** [comment]
I figured this out!

The problem was that I was deleting the .json file right after `CREATE TEMPORARY TABLE`. It looks like the statement returns before loading the whole file.
