### ISSUE TITLE
EXTRACT(EPOCH FROM timetamp) return int, or double?

### ISSUE THREAD

**Issue by longxiaofei** [duckdb/duckdb#9391]
### What happens?

```sql
SELECT EXTRACT(EPOCH FROM '2022-10-10'::timestamp)
```

in duckdb 0.8.1, it will return int value: `1665360000`

in duckdb>=0.9.0, it will return double value: `1665360000.0`

### To Reproduce

```python
import duckdb

duckdb.query("""
SELECT EXTRACT(EPOCH FROM '2022-10-10'::timestamp)
""")
```

### OS:

os M2 

### DuckDB Version:

0.9.1

### DuckDB Client:

python

### Full Name:

Douding

### Affiliation:

Kanaries

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Yes this was changed not too long ago, I believe in the pursuit of posgres compatibility
<https://github.com/duckdb/duckdb/pull/8963>

**Comment by longxiaofei** [comment]
I got it, thanks.
