### ISSUE TITLE
DuckDB 0.9.0 not respecting temp_directory property during query execution

### ISSUE THREAD

**Issue by mozz3** [duckdb/duckdb#9401]
### What happens?

As per DuckDB 0.9.0 release notes, DuckDB support queries where intermediate results do not fit into memory by using disk-spilling techniques. In release 0.9.0, hash tables constructed during GROUP BY queries or DISTINCT operations that do not fit in memory due to a large number of unique groups will spill data to disk instead of throwing an out-of-memory exception.

But this is not happening when I am writing C++ code that is connecting to a duckdb file persisted on local disk & executing a group by queries that require relatively high amount of memory. I am getting below error on executing group by query

Invalid Input Error: Attempting to fetch from an unsuccessful query result
Error: Out of Memory Error: failed to allocate data of size 8.3MB (1.8MB/10.0MB used)

### To Reproduce

1. In C++ code, Create a `duckdb::DBConfig` object
2. Set `max_memory` to some limit lets say 10 MB
3. Set `access_mode` to READ_ONLY
4. Set `threads` to 1
5. Create `duckdb::Connection` object using above `duckdb::DBConfig` object and path to duckdb data base file (duckdb native format)
6. Run a group by query that needs higher than 10 MB of memory

Expected Result:
DuckDB should create temp directory and file to spill data which is larger than memory (in our case 10 MB)

Actual Result:
DuckDB is throwing out of memory exception. Exact error message is: Invalid Input Error: Attempting to fetch from an unsuccessful query result
Error: Out of Memory Error: failed to allocate data of size 8.3MB (1.8MB/10.0MB used)

### OS:

MACOS

### DuckDB Version:

0.9.0

### DuckDB Client:

C++

### Full Name:

Mozz

### Affiliation:

Self

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Are you not missing the step where you set the temp directory in your reproduction?

**Comment by Tishj** [comment]
Admittedly the docs are hard to find (searching for `temp_directory` yielded no results)
This is the page you're looking for: https://duckdb.org/docs/sql/configuration

**Comment by mozz3** [comment]
I am setting temp directory in DBConfig object. Below is my code snippet that creates duckdb connection and executes query over it

`std::string dbLocation = "/Users/moz/duckdb/0.9.1/lineorder_flat.db";`
`std::string tblName = "lineorder";`
`duckdb::DBConfig dbConfig;`
`dbConfig.SetOptionByName("max_memory", "10MB");`
`dbConfig.SetOptionByName("access_mode", "READ_ONLY");`
`dbConfig.SetOptionByName("threads", "1");`
`dbConfig.SetOptionByName("temp_directory", "/Users/moz/duckdb/0.9.1");`
`duckdb::DuckDB db(dbLocation, &dbConfig);`
`duckdb::Connection dbConnection(db);`

`std::string q1 = "SELECT SUM(lo_revenue), c_name, p_brand, p_category from " + tblName + " WHERE (lo_quantity>4 OR lo_quantity<2) AND s_region='ASIA' AND lo_orderdate > 19960101 GROUP BY c_name, p_brand, p_category";`

`//Create Prepared Statement object`
`std::unique_ptr<duckdb::PreparedStatement> stmt = dbConnection.Prepare(query);`

`//Execute query on statement, get the materialised resultset`
`duckdb::vector<duckdb::Value> values;`
 `std::unique_ptr<duckdb::QueryResult> queryResultSet = stmt->Execute(values, true);`

`//Iterate over result set and calculate number of rows in the resultset`
  `duckdb::unique_ptr<duckdb::DataChunk> dataChunk;`
  `int counter = 0;`
   `while(true) {`

`            dataChunk = queryResultSet->Fetch();`
`            if(dataChunk.get() == nullptr) {`
`                   break;`
`            }`
`            counter += dataChunk->size();`
`        }`

**Comment by mozz3** [comment]
Please note that I took the code from tag 0.9.0. Do you want me to try from the main branch?

**Comment by Tishj** [comment]
I'm just now reading that you set the max memory as 10mb, that's quite low

You might want to limit threads, and possibly also disable the preservation of insertion order

It's entirely possible that the intermediates are too big to spill to disk with that limit

**Comment by mozz3** [comment]
I intentionally kept it to that low to understand the disk spilling behaviour.
Is there any guideline on how should I decide the max memory to be set for my database connection?
I want to understand when the intermediates will be spilled to disk (Does the max memory have to be in some proportion of available RAM?) because of if I increase the memory to lets say 20/30 MB then query executes successfully but even then everything happens in memory and nothing is spilled over to disk.

**Comment by Mytherin** [comment]
Thanks for the report! I would say this is not an issue. While disk spilling is supported, it is not supported for arbitrarily low memory limits. There is still a minimum amount of memory that is required for operators to function. Particularly for memory limits <100MB you can still expect to run into out of memory issues when processing large memory sets.

**Comment by mozz3** [comment]
So I did this to understand disk spilling concept better.
In the actual code, I have kept memory limit as 100 MB for a duck db connection object. The problem I am facing is that in a concurrent environment, when multiple requests come to be served from a single duck db file, we are creating multiple connection objects but because of the way DuckDB is designed, all connection objects to the same DB file share same memory (buffer managers and pools), the query sometime returns out of memory exception when number of connection objects to the duck DB file are 5-6. 
The problem is, other queries work really well even with 10 concurrent connection objects on the same duck db file. 
Now I do not know, what memory limit should I set for the connection object and on what basis, I should throttle number of concurrent connection objects to the same DB file.

**Comment by fall14123** [comment]
> I'm just now reading that you set the max memory as 10mb, that's quite low
> 
> You might want to limit threads, and possibly also disable the preservation of insertion order
> 
> It's entirely possible that the intermediates are too big to spill to disk with that limit

@Tishj is there recommendation/best practice for `threads` (or `threads/memory_limit`)? what's the symptom if `threads` is under provisioned? thanks
