### ISSUE TITLE
UNNEST on a list not working correctly when a filtering condition is added

### ISSUE THREAD

**Issue by bgedik** [duckdb/duckdb#9407]
### What happens?

```sql
WITH
  Sequences AS (
    SELECT 1 AS id, [0, 1, 1, 2, 3, 5] AS some_numbers
    UNION ALL
    SELECT 2 AS id, [2, 4, 8, 16, 32] AS some_numbers
    UNION ALL
    SELECT 3 AS id, [5, 10] AS some_numbers
  )
SELECT id AS matching_rows
FROM Sequences
WHERE EXISTS(SELECT * FROM UNNEST(some_numbers) AS x WHERE x > 5);
```

Returns empty set, where the correct answer is `[2, 3]`.

### To Reproduce

Just run the query

### OS:

Not sure

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Bugra Gedik

### Affiliation:

Cruise

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by wa008** [comment]
I think that `UNNEST` can't used in filter condition directly and I don't know if that should be it in theroy.
 you can use it in condition after creating new table using previous result.

The below code works
```
create table data as from (
  values
  (1, [0, 1, 1, 2, 3, 5]),
  (2, [2, 4, 8, 16, 32]),
  (3, [5, 10]),
) as t(id, some_numbers);

SELECT id, x from 
(
    SELECT id, UNNEST(some_numbers) AS x
    FROM data
)
WHERE x > 5
```
output:
```
┌───────┬───────┐
│  id   │   x   │
│ int32 │ int32 │
├───────┼───────┤
│     2 │     8 │
│     2 │    16 │
│     2 │    32 │
│     3 │    10 │
└───────┴───────┘
```

**Comment by bgedik** [comment]
Changing `AS x` into `AS tbl(x)` or `AS _t(x)` solves it, so perhaps this is more of an issue of flagging the incorrect query.
