### ISSUE TITLE
Using recursive CTE more than once produces binder error

### ISSUE THREAD

**Issue by solomspd** [duckdb/duckdb#9458]
### What happens?

When using a recursive CTEs, calling it more than once results in an error when it's expected to be have like the first CTE. This is useful for finding graph components in a directed graph.

### To Reproduce

This example is based on the hierarchical data in the [WITH duckdb docs](https://duckdb.org/docs/sql/query_syntax/with.html).
The example is extended to work on both directional edges where the query searches for both parents and children instead of parents only. Infinite recursion is stopped by checking the whether a newly visited node is in the path.

```sql
CREATE TABLE tag(id int, name varchar, subclassof int);
INSERT INTO tag
VALUES (1, 'U2', 5),
	(2, 'Blur', 5),
	(3, 'Oasis', 5),
	(4, '2Pac', 6),
	(5, 'Rock', 7),
	(6, 'Rap', 7),
	(7, 'Music', 9),
	(8, 'Movies', 9),
	(9, 'Art', NULL);
```

```sql
WITH RECURSIVE tag_hierarchy(id, source, subclassof, path) AS (
	SELECT id,
		name,
		subclassof,
		[name] AS path
	FROM tag
	WHERE subclassof IS NULL
	UNION ALL
	-- Retrieve children
	SELECT tag.id,
		tag.name,
		tag.subclassof,
		list_prepend(tag.name, tag_hierarchy.path)
	FROM tag,
		tag_hierarchy
	WHERE tag.subclassof = tag_hierarchy.id
		AND NOT list_contains(tag_hierarchy.subclassof, tag.name)
	UNION ALL
	-- Retrieve parents
	SELECT tag.id,
		tag.name,
		tag.subclassof,
		list_prepend(tag.name, tag_hierarchy.path)
	FROM tag,
		tag_hierarchy
	WHERE tag.id = tag_hierarchy.subclassof
		AND NOT list_contains(tag_hierarchy.path, tag.name)
)
SELECT path
FROM tag_hierarchy
WHERE source = 'Oasis';
```

Running the above two queries, produces the following error:
```
Error: Binder Error: Circular reference to CTE "tag_hierarchy", There are two possible solutions.
1. use WITH RECURSIVE to use recursive CTEs.
2. If you want to use the TABLE name "tag_hierarchy" the same as the CTE name, please explicitly add "SCHEMA" before table name. You can try "main.tag_hierarchy" (main is the duckdb default schema)
```
The error is also misleading since neither solutions are applicable. 1. The CTE is already recursive 2. there is no other table we want to refer to.

### OS:

Arch Linux, x64

### DuckDB Version:

0.9.1, 0.9.2-dev115

### DuckDB Client:

CLI, Python

### Full Name:

Abdelsalam ElTamawy

### Affiliation:

the American University in Cairo

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
recursrive CTE only permits one `union all`
in postgresql
```
postgres=# WITH RECURSIVE t(x,y)
postgres-# as
postgres-# (select 0,2
postgres(# union all
postgres(# select x+1,x+2 from t where x%3=0 and x<10
postgres(# union all
postgres(# select x*2,x*4 from t where x%3=1 and x<10
postgres(# )
postgres-# select * from t
postgres-# ;
ERROR:  recursive reference to query "t" must not appear within its non-recursive term
第5行select x+1,x+2 from t where x%3=0 and x<10
                         ^
postgres=# WITH RECURSIVE t(x,y)
postgres-# as
postgres-# (select 0,2
postgres(# union all
postgres(# select x+1,x+2 from t where x%3=0 and x<10
postgres(# /*union all
postgres*# select x*2,x*4 from t where x%3=1 and x<10*/
postgres(# )
postgres-# select * from t
postgres-# ;
 x | y
---+---
 0 | 2
 1 | 2
```

**Comment by kryonix** [comment]
This is a parser 'issue'—or rather, expected behavior. If you do not use explicit parentheses, `UNION [ALL]` is parsed left-associative. Therefore your query does not work as intended.

Adding some parentheses around the intended recursive part of your CTE fixes the problem.

```
WITH RECURSIVE tag_hierarchy(id, source, subclassof, path) AS (
	SELECT id,
		name,
		subclassof,
		[name] AS path
	FROM tag
	WHERE subclassof IS NULL
	UNION ALL
	-- Retrieve children
	(SELECT tag.id,
		tag.name,
		tag.subclassof,
		list_prepend(tag.name, tag_hierarchy.path)
	FROM tag,
		tag_hierarchy
	WHERE tag.subclassof = tag_hierarchy.id
		AND NOT list_contains(tag_hierarchy.subclassof, tag.name)
	UNION ALL
	-- Retrieve parents
	SELECT tag.id,
		tag.name,
		tag.subclassof,
		list_prepend(tag.name, tag_hierarchy.path)
	FROM tag,
		tag_hierarchy
	WHERE tag.id = tag_hierarchy.subclassof
		AND NOT list_contains(tag_hierarchy.path, tag.name))
)
SELECT path
FROM tag_hierarchy
WHERE source = 'Oasis';
```

However, the query logic seems a bit broken. I'm sure you can figure that out.

```
Error: Binder Error: No function matches the given name and argument types 'list_contains(INTEGER, VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	list_contains(ANY[], ANY) -> BOOLEAN
```

---

@l1t1 that's correct _for PostgreSQL_. But you can work around this. You just have to be a bit more creative in PostgreSQL.
DuckDB does **not** have this restriction.

```
WITH RECURSIVE t(x,y) as
(select 0,2
union all
(WITH t(x,y) AS (SELECT * FROM t)
select x+1,x+2 from t where x%3=0 and x<10
union all
select x*2,x*4 from t where x%3=1 and x<10
))
select * from t;

 x | y
---+---
 0 | 2
 1 | 2
 2 | 4
(3 rows
```

**Comment by szarnyasg** [comment]
As @kryonix said this is a quirk in the Postgres parser.
