### ISSUE TITLE
Misleading error message with misspelt column names in subquery

### ISSUE THREAD

**Issue by jmoy** [duckdb/duckdb#9463]
### What happens?

Consider the following 

```sql
create table t(i integer);
insert into t values (1),(3),(4);
select * from t as t1 where exists (select * from t where i=t1.j+1);
```

Here in the subquery `t1.j` is an error, it should have been `t1.i`. On executing this I get the error message

```
Error: Binder Error: Referenced table "t1" not found!
Candidate tables: "t"
```

which is misleading since the problem is not with an incorrect table name but with an incorrect column name.

### To Reproduce

Code to reproduce is given in  'What happens'

### OS:

Debian 12 x64

### DuckDB Version:

v0.9.2-dev86 39820ba734

### DuckDB Client:

CLI

### Full Name:

Jyotirmoy Bhattacharya

### Affiliation:

Dr. B. R. Ambedkar University Delhi

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@jmoy Thanks for raising this issue. In general, these error messages are only there for quick guidance and cannot be fully relied on. So we are unlikely to tackle this in the near future.
