### ISSUE TITLE
Not implemented Error: Unrecognized option for PARQUET: PER_THREAD_OUTPUT

### ISSUE THREAD

**Issue by idantene** [duckdb/duckdb#9470]
### What happens?

Trying to execute a COPY TO statement with the PER_THREAD_OUTPUT in the Python API, results in the above exception.

Are there plans to implement this option in the Python API?

### To Reproduce

```python
cursor.execute(
"""
COPY (
    SELECT ...
    FROM '...'
    WHERE ...
) TO '...' (FORMAT PARQUET, PER_THREAD_OUTPUT TRUE);
"""
)
```

### OS:

x86, x64

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Idan Tene

### Affiliation:

?

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report!

I cannot reproduce this,  are you sure you are using a recent DuckDB version?

```py
import duckdb
duckdb.sql("COPY (SELECT 42) TO  'file.parquet' (FORMAT PARQUET, PER_THREAD_OUTPUT TRUE)")
```

**Comment by idantene** [comment]
Hey @Mytherin, thanks for the reply.
I _was_ sure I was using a recent DuckDB version, but you made me doubt myself.

I'll peer closer still into our k8s setup and docker images and verify.

**Comment by idantene** [comment]
@Mytherin Sorry for the false issue. Our docker image had used 0.61 internally. Works fine with 0.91 :)
