### ISSUE TITLE
read_parquet on S3 takes a long while to prepare when it should be lazy

### ISSUE THREAD

**Issue by igofunke** [duckdb/duckdb#9474]
### What happens?

I have a simple query that reads parquets from a S3 location with hive partitioning (in the below `id` belongs to the partition)

`conn.sql("SELECT * FROM read_parquet('s3://bucket/path/*/*/*.parquet', filename=true, hive_partitioning=true) WHERE id = '55f622a3'")`

I was under the impresion that this should execute lazily (I am planning to chain it with other operations). However that does not seem to be the case. The statement itself takes a long while, and Google Cloud Storage registers a good amount of requets.

These are the stats from the bucket.

![imagen](https://github.com/duckdb/duckdb/assets/11059580/050c7964-6baf-4c2d-9035-4f1c5ffeebe5)
![imagen](https://github.com/duckdb/duckdb/assets/11059580/13d0ca1a-c3c5-4c18-b679-d8099a686ec4)

This is the query profiling information. As you can see, it does quite some reading.

```
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘

┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││            HTTP Stats:            ││
││                                   ││
││             in: 2.4MB             ││
││            out: 0 bytes           ││
││             #HEAD: 216            ││
││             #GET: 649             ││
││              #PUT: 0              ││
││              #POST: 0             ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 351.14s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      RESULT_COLLECTOR     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           LIMIT           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (3.77s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│       READ_PARQUET        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         id        │
│       ...      │
│          filename         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         EC: 263213        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           10000           │
│         (308.84s)         │
└───────────────────────────┘               

```

For completion, here is the result of the query profiling with `explain` prefixed.

<img width="287" alt="imagen" src="https://github.com/duckdb/duckdb/assets/11059580/27f8908b-2e6c-4e19-874a-873fddc242bb">

### To Reproduce

1. Set up a Google Cloud Storage bucket and create a sample hive (the top level of our hive has 20k entries; the second level an average of 200 entries; there is one parquet per subset with 20KB average)
2. Execute the statement above with profiling enabled.

Note that this also happens when the hive has only one level with around 200 entries; one parquet per entry. In this case it takes less time (30s vs 308s) but still significant.

### OS:

Linux 5.15.107+ x86_64, Darwin arm64

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Ignacio Funke

### Affiliation:

Capchase

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report!

The execution is done lazily - but binding is done when the statement is executed. In this case that means (1) resolving the glob and gathering a list of files to scan, and (2) reading the metadata of a Parquet file to figure out the names and types that exist in the file. 

I'm guessing that in this case these steps take a significant amount of time, likely because there are many files present as part of the glob.

**Comment by igofunke** [comment]
> Thanks for the report!
> 
> The execution is done lazily - but binding is done immediately. In this case that means (1) resolving the glob and gathering a list of files to scan, and (2) reading the metadata of a Parquet file to figure out the names and types that exist in the file.
> 
> I'm guessing that in this case these steps take a significant amount of time, likely because there are many files present as part of the glob.

Hey Mytherin,

Thanks a lot for the quick reply. That makes sense. However, the amount of time it takes is prohibitive to us. Is there something we could do to accelerate it?

My expectations were that
* If there is a filter targeting the hive partition, then you only scan the corresponding subset of the hive. But I think it is not the case because when I hardcode the filter in the glob, the statement is 10 times faster, though still slow.
* If the union-by-name is not enabled, then you would only need to get one file in the hive to infer the names and types.

**Comment by igofunke** [comment]
Update: for now we will push for smaller partitions and bigger parquet files, according to [Arrow's recommendation](https://arrow.apache.org/docs/python/dataset.html#partitioning-performance-considerations).
* Avoid files smaller than 20MB and larger than 2GB.
* Avoid partitioning layouts with more than 10,000 distinct partitions.

**Comment by frittentheke** [comment]
I am using DuckDB to read AWS CloudFront access logs (https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-cloudfront-log-formats-destinations-access/).
Access logs are written to S3 as individual objects every few minutes and also per different CloudFront locations, this cannot be changed.
I also use `AWSLogs/{account-id}/CloudFront/{DistributionId}/{yyyy}/{MM}/{dd}/{HH}` as partitioning schema, so I am selecting per hour.

I am open to suggestions to improve the structure to suit DuckDB, but likely this is the same underlying issue with excessive amount of objects which need to be fetched. Are multiple threads / connections used to fetch them all? Anyway to turn on debugging to see more about the S3 requests ?

To me it seems the network utilization is VERY low even during the actual download ...

 @szarnyasg Do you mind reopening this issue maybe?
