### ISSUE TITLE
Bundling third_party and other dependencies needed in libduckdb_static.a

### ISSUE THREAD

**Issue by edyu** [duckdb/duckdb#9475]
### What happens?

`libduckdb_static.a` is not part of the release but it's not usable because it doesn't include the various dependencies needed (for example the ones in the `third_party` folder).
For anyone writing a program to access duckdb programmatically, currently they cannot statically link to the provided `libduckdb_static.a` because of those missing references.

I first opened a discussion https://github.com/duckdb/duckdb/discussions/9451 and was told to file this issue.

### To Reproduce

Write a program using the C api such as `db_connect`, `db_disconnect`, and etc and try to link the program using the provided `libduckdb_static.a`. 

https://github.com/duckdb/duckdb/discussions/9451

### OS:

Ubuntu 22.04 LTS

### DuckDB Version:

0.9.1

### DuckDB Client:

C

### Full Name:

Ed Yu

### Affiliation:

Beachglass Labs

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
#10507 partially address this problem, idea is allowing developers to run make bundle library to have a static library bundle all third party AND all build extensions in a single bundle.

Currently this is not going to be packaged as part of releases on GitHub.
