### ISSUE TITLE
DuckDB Python client hanging occasionally on close when reading from HDFS

### ISSUE THREAD

**Issue by steffengr** [duckdb/duckdb#9479]
### What happens?

The Python DuckDB will occasionally start hanging indefinably when creating a temporary table based on parquet files on HDFS and closing the connection. I reproduced this bug on a clean HDFS cluster based on Google Cloud Dataproc to make sure it has nothing to do with our setup.

I was able to reproduce this by building DuckDB from the main branch. Strangely, the bug does no appear when building for debugging with make debug. 

I'm not sure how to troubleshoot this further from here. Are there any ways to enable logs or traces from DuckDB?

### To Reproduce

Upload a parquet file to HDFS, I used Google Cloud Dataproc to have a clean environment, and then run the following Python script on a node with access to HDFS. It will start hanging after a few iterations.

```
import duckdb
import fsspec.implementations.arrow as pfs

fs = pfs.HadoopFileSystem("default")
i = 0
while True:
    print(i)
    i+=1
    print("Connecting to DuckDB")
    with duckdb.connect(
            database=":memory:",
            read_only=False
    ) as duckdb_con:
        duckdb_con.register_filesystem(fs)
        print("Creating temp table")
        query = f'create or replace temp table "test_table" as (select "col_1" from read_parquet(["hdfs:///test.parquet"]))'
        duckdb_con.sql(query)
        print("Closing connection")
```

### OS:

x64

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Steffen Grohsschmiedt

### Affiliation:

Hopsworks

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hannes** [comment]
Hey, is there a way for us to make this reproducible without going through cloud vendors or Hadoop setup?

**Comment by steffengr** [comment]
You might be able to use the [MiniCluser](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/CLIMiniCluster.html) to reproduce this. If that doesn't help then I should be able to give you access to my debug cluster if you want.

**Comment by Mause** [comment]
With a lot of blood, swears, and (especially) tears I was able to get Hadoop running locally on my machine and PyArrow connecting to it. It's been running in a loop for a while now, I'll let you know if I see the issue you described

**Comment by steffengr** [comment]
Glad to hear you got it running. I understand the pain of getting this running all to well. It seems strange to me that it didn't get stuck right away for you. I just tried again and it happened. You don't have the DuckDB binaries compiled for debugging by any chance? That makes the issue not appear for whatever reason.

**Comment by Mause** [comment]
> Glad to hear you got it running. I understand the pain of getting this running all to well. It seems strange to me that it didn't get stuck right away for you. I just tried again and it happened. You don't have the DuckDB binaries compiled for debugging by any chance? That makes the issue not appear for whatever reason.

Nope, I'm running on Ubuntu x64 with the 0.9.2 release build

**Comment by steffengr** [comment]
Just tried with 0.9.2 and it got stuck as well. Maybe related to some Python dependencies that I have installed. I have the following in my debug setup:

```
(venv) steffen@cluster-6200-m:~$ pip freeze
duckdb==0.9.2
fsspec==2023.10.0
numpy==1.25.0
prometheus-client==0.16.0
psutil==5.9.4
py4j==0.10.9.7
pyarrow==13.0.0
```

**Comment by Mause** [comment]
How many iterations do you need before it locks up?

**Comment by steffengr** [comment]
Not many. Last attempt took 6.

**Comment by steffengr** [comment]
Have you had any success reproducing this issue?

**Comment by steffengr** [comment]
I also tried upgrading my dependencies and that appears to have made a difference in terms of number of iterations. Before it was getting stuck after 5 to 15 iterations and with the upgraded dependencies it manages to do a couple of thousands but eventually gets stuck anyways.
```
duckdb==0.9.2
fsspec==2023.10.0
numpy==1.26.2
pyarrow==14.0.1
```

**Comment by steffengr** [comment]
Did one more test to ensure it's not caused by something outside of DuckDB and this is not getting stuck:

```
import fsspec.implementations.arrow as pfs
import pandas as pd

fs = pfs.HadoopFileSystem("default")
i = 0
while True:
    print(i)
    i+=1
    f = fs.open("hdfs:///Titanic.parquet", "rb")
    df = pd.read_parquet(f)
    print(df.head())
    f.close()
```

**Comment by szarnyasg** [comment]
Thanks for the detailed instructions! I edited them a bit to separate the parts where a user input (like pressing <kbd>Y</kbd> is required).

I could reproduce the problem with the latest nightly build. Trying to build from source now...

**Comment by szarnyasg** [comment]
Two things I've learned so far:

1) When it hung, it returned the following error:

```
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2829:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
```

2) If the line `fs = pfs.HadoopFileSystem("default")` fails with the error `libhdfs.so: cannot open shared object file: No such file or directory`, that's a path problem. Running `export PATH=$PATH:/home/${USER}/hadoop-3.3.6/bin` resolves it.

**Comment by szarnyasg** [comment]
I could reproduce this quite reliably with <1200 iterations on both 0.9.2, nightly, and `main`.

**Comment by robzor92** [comment]
Did you guys find out anything more on this?

**Comment by aversey** [comment]
I have reproduced the problem with duckdb v0.9.2, but it doesn't occur with duckdb v1.0.0.
