### ISSUE TITLE
Overflow exception in date/time -> timestamp conversion

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#9487]
### What happens?

I get `Overflow exception` error when passing a non-UTC time zone aware Python `datetime` to `execute`.

Surprised this hasn't been reported before 🤯 

I discovered it while doing some testing for changes between 0.8 and 0.9 as related to ⬇️, but it is present on 0.8 as well.
- https://github.com/duckdb/duckdb/issues/6466
- https://github.com/duckdb/duckdb/pull/7024

### To Reproduce

```py
import duckdb
from datetime import datetime, UTC
from zoneinfo import ZoneInfo

con = duckdb.connect()
con.execute('CREATE TABLE IF NOT EXISTS t (ts TIMESTAMP WITH TIME ZONE NOT NULL)')

now_naive = datetime.now()
con.execute('INSERT INTO t (ts) VALUES (?)', (now_naive,))  # works

now_utc = datetime.now(UTC)
con.execute('INSERT INTO t (ts) VALUES (?)', (now_utc,))  # works

ny = ZoneInfo('America/New_York')
now_ny = datetime.now(ny)

con.execute('INSERT INTO t (ts) VALUES (?)', (now_ny,))
# duckdb.duckdb.Error: Overflow exception in date/time -> timestamp conversion

# Cast to string and it works:
# con.execute('INSERT INTO t (ts) VALUES (?)', (str(now),))
```

### OS:

Windows

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
I cannot reproduce this on macOS

**Comment by Tishj** [comment]
@davetapley Thanks for raising the issue, as this concerns timezones this is not a reproducable example unless you explicitly set a timezone or provide the timezone set (`select current_setting('timezone')`)

**Comment by davetapley** [comment]
@szarnyasg good catch, same here ✅ 

---

@Tishj repro ⬇️  w/o anything but snippet I posted, unless I'm missing something 🤔 
https://replit.com/@davetapley/duckdb-timezome-overflow#main.py

...well, I had to `datetime.timezone.utc` because repl.it is Python 3.10, but basically same.

---

Also figured I'd test on Windows, and see it there too:
```
PS C:\Users\dave> python bug.py  
Traceback (most recent call last):
  File "C:\Users\dave\bug.py", line 17, in <module>
    con.execute('INSERT INTO t (ts) VALUES (?)', (now_ny,))
duckdb.duckdb.Error: Overflow exception in date/time -> timestamp conversion

PS C:\Users\dave> python -V      
Python 3.11.4

PS C:\Users\dave> pip show duckdb
Name: duckdb
Version: 0.9.1
Summary: DuckDB embedded database
Home-page: https://www.duckdb.org
Author: 
Author-email: 
License: MIT
Location: C:\Users\dave\.pyenv\pyenv-win\versions\3.11.4\Lib\site-packages
```

**Comment by Tishj** [comment]
Yea on the replit I run into your issue, on `main` I don't.
So I presume it's fixed 👍
