### ISSUE TITLE
ArrowIndexError: buffer slice would exceed buffer length when export to arrow batch

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#9494]
### What happens?

trying to copy data from duckdb to delta table writer using fetch_arrow_reader, it works fine except the table orders which generate this erros
ArrowIndexError: buffer slice would exceed buffer length

### To Reproduce

the source data is parquet files for tpch100 generated by duckdb

```
import duckdb
from deltalake.writer import write_deltalake
from trident_token_library_wrapper import PyTridentTokenLibrary
aadToken = PyTridentTokenLibrary.get_access_token("storage")
con=duckdb.connect()
duckdb.sql('PRAGMA disable_progress_bar; set arrow_large_buffer_size=True')

for tbl in ['orders','nation','lineitem','region','customer','supplier','partsupp','part'] :
     print(tbl)
     results=con.sql(f" SELECT * FROM parquet_scan('/lakehouse/default/Files/{sf}/{tbl}/*.parquet') ").fetch_arrow_reader(80000000)
     while True:
      try:
        write_deltalake(f"abfss://xxxxx@onelake.dfs.fabric.microsoft.com/pure_duckdb.Lakehouse/Tables/{tbl}",\
        results.read_next_batch(),mode='append',overwrite_schema=True\
        ,max_rows_per_file =80000000,min_rows_per_group=8000000,max_rows_per_group=8000000\
        ,storage_options={"bearer_token": aadToken, "use_fabric_endpoint": "true"})
      except StopIteration:
        print('done')
        break
     con.close()
```

### OS:

Linux

### DuckDB Version:

0.9.2.dev178

### DuckDB Client:

Python

### Full Name:

Mim

### Affiliation:

Personal

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Can you please provide the entire stack trace?

**Comment by djouallah** [comment]
reducing the size of the batches fixed the issue for me, thanks
