### ISSUE TITLE
COPY does not accept double-quote character for target filename

### ISSUE THREAD

**Issue by colinbreame** [duckdb/duckdb#9497]
### What happens?

Using double-quotes on the TO `file-name`  of the COPY command errors with a syntax error:

> duckdb.duckdb.ParserException: Parser Error: syntax error at or near ""hello_world.parquet""
> LINE 1: COPY (SELECT 42) TO "hello_world.parquet"

### To Reproduce

```python
import duckdb

duckdb.sql("SELECT 43").write_parquet("42.parquet")

# This works
duckdb.sql(r'''COPY "42.parquet" TO 'hello_world.parquet' ''')

# This errors
duckdb.sql(r'''COPY "42.parquet" TO "hello_world.parquet" ''')
```

### OS:

Windows

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Colin Breame

### Affiliation:

Statkraft Germany GmBH

### Have you tried this on the latest `main` branch?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@colinbreame this is intended behaviour, strings should be formatted with single quotes (https://duckdb.org/docs/sql/data_types/text#formatting-strings), double quotes are reserved for column names.

**Comment by colinbreame** [comment]
@szarnyasg thanks for the explanation but I'm still a little confused because it seems that double-quotes are not exclusively reserved for column names.

For example:

```
# "42.parquet" has double-quotes in both the working examples below
duckdb.sql('''COPY "42.parquet" TO 'hello_world.parquet' ''')
duckdb.sql('SELECT * FROM "42.parquet"')
```

To me, it seems that the COPY command is inconsistent.
