### ISSUE TITLE
Amalgamation C++ header defines version as "vvX.Y.Z"

### ISSUE THREAD

**Issue by elefeint** [duckdb/duckdb#9498]
### What happens?

`duckdb.hpp` from [v0.9.1 libduckdb-src.zip](https://github.com/duckdb/duckdb/releases/download/v0.9.1/libduckdb-src.zip) defines DuckDB version as:
```
#define DUCKDB_VERSION "vv0.9.1"
```

Ideally, the version should be "v0.9.1" with only one "v".

This is related to version standardization efforts in #9050 and #9095.

### To Reproduce

Extract `duckdb.hpp` from [v0.9.1 libduckdb-src.zip](https://github.com/duckdb/duckdb/releases/download/v0.9.1/libduckdb-src.zip) ; observe `DUCKDB_VERSION` definition.

### OS:

Ubuntu 22.04

### DuckDB Version:

0.9.1

### DuckDB Client:

Amalgamation C++ sources

### Full Name:

Elena Felder

### Affiliation:

MotherDuck

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Thanks for raising this. It's not great this made it in, thanks past me!
