### ISSUE TITLE
Bad types in Python relational API

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#9501]
### What happens?

`count('*')` (and I'm sure others) from:

- https://github.com/duckdb/duckdb/issues/2000

fail to type check with:
```
Arguments missing for parameters "groups", "window_spec", "projected_columns"

Pylance[reportGeneralTypeIssues]

(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

### To Reproduce

```py
import duckdb
con = duckdb.connect()
con.sql('select 1').count('*')
```

You can also manually verify no defaults in method signature:

https://github.com/duckdb/duckdb/blob/6545a55cfe4a09af251826d4dd72980c424d9215/tools/pythonpkg/duckdb-stubs/__init__.pyi#L353

### OS:

Windows

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by davetapley** [comment]
Can use `.aggregate('count(*)')` as a workaround.

**Comment by Tishj** [comment]
Thanks, this change was made by an outside contributor, dealing with this is tricky because it needs to be changed in 4 places, so things like this slip through the cracks
