### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by arnabadas** [duckdb/duckdb#9502]
### What happens?

Error while building: 
[error.txt](https://github.com/duckdb/duckdb/files/13194540/error.txt)
Error lies in lines 8344-8355

### To Reproduce

Build in Windows 10 22H2 Pro x64 using Visual Studio Community 17.7.6 with the following cmake configuration:

```cmd
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DENABLE_EXTENSION_AUTOLOADING=1 -DENABLE_EXTENSION_AUTOINSTALL=1 -DDUCKDB_EXTENSION_CONFIG="D:/Arnab/dev/duckdb/.github/config/bundled_extensions.cmake" -DBUILD_ODBC_DRIVER=0 -DDISABLE_UNITY=1  -DEXTENSION_STATIC_BUILD=1 -DBUILD_PYTHON=0
```

### OS:

Windows 11 Pro 22H2 x64

### DuckDB Version:

main branch (dated 28th October 2023)

### DuckDB Client:

C++

### Full Name:

Arnab Animesh Das

### Affiliation:

NA

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
today's nightly build of windows is also failed

**Comment by Mause** [comment]
> today's nightly build of windows is also failed

That failure is unrelated

**Comment by Mause** [comment]
@arnabadas which git hash did you try with? And had you made any local changes?

Also, is there a reason you're not using nightly builds instead?

**Comment by arnabadas** [comment]
Git Hash `6545a55cfe`. No local changes made. The dlls and libs were built in the Release even with this error. 🤷‍♂️ But I thought I should point it out nonetheless.

Earlier (maybe 2-3 months back) where even with nightly builds C++ API was not working properly (`Parser Error`), so I built it on my system and it worked fine. It was the first time I built in my system and never looked back since. I guessed maybe it was due to some CPU architecture mismatches, but I maybe wrong.

Footnote: There is a very small chance that I used a stable 0.8 build instead back then. But nonetheless building my own gives me assurance.

**Comment by hannes** [comment]
The BUILD_PYTHON flag is mainly used for development, it's entirely possible there are some cases where this does not work in a particular setup. Why can't you use the pre-release python binaries? Cheers

**Comment by arnabadas** [comment]
`BUILD_PYTHON` flag is `0` though. It should not build Python at all.

**Comment by hannes** [comment]
Pardon, missed the `=0` here
