### ISSUE TITLE
[Python] Unexpected data transformation if column contains `dict`

### ISSUE THREAD

**Issue by StpMax** [duckdb/duckdb#9510]
### What happens?

Issue that arises when making a query to a DataFrame (df) using the DuckDB Python library. 

When the DataFrame contains only a single row with a dictionary inside, the returned data aligns with the expectations. However, if the DataFrame has more than one row with a dictionary, the result gets transformed in the following ways:
- dictionary changes its structure to `{'key': [...], 'value': [...]}`
- types of the values change (for instance, in the example below, 1 (int) has been converted to '1' (str))

I apologize if this is a known feature. Couldn't find anything about it in the documentation or closed issues.

### To Reproduce

```python
import pandas as pd
import duckdb

df_1 = pd.DataFrame([
    [{'x': '', 'y': 1}]
], columns=['DATA'])

df_2 = pd.DataFrame([
    [{'x': '', 'y': 1}],
    [{'x': ''}]
], columns=['DATA'])

con = duckdb.connect(database=':memory:')
print(con.execute('SELECT * FROM df_1').fetchdf())
print(con.execute('SELECT * FROM df_2').fetchdf())
```

result is:
```bash
    DATA
0  {'x': '', 'y': 1}

    DATA
0  {'key': ['x', 'y'], 'value': ['', '1']}
1  {'key': ['x'], 'value': ['']}
```

### OS:

ubuntu

### DuckDB Version:

0.9.1

### DuckDB Client:

python

### Full Name:

Max Stepanov

### Affiliation:

MindsDB

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hey, thanks for the report!

I think this is the PR that describes the behavior: <https://github.com/duckdb/duckdb/pull/3985>
But I agree, this should have been documented

**Comment by StpMax** [comment]
@Tishj thank you, that make sense. Would be good to have any command to control that behavior (may be via `set`? `set global cast_dict_to=map|str|something_else;`).

**Comment by Tishj** [comment]
We've updated the docs to disclose this behaviour
