### ISSUE TITLE
Incorrect aggregation result with union all of multiple db files. 

### ISSUE THREAD

**Issue by pmg1991** [duckdb/duckdb#9515]
### What happens?

Attach multiple db files.  Incorrect aggregation result with union all of all the db files. 

### To Reproduce

SET THREADS TO 8;
ATTACH '1.db' as db1 ( READ_ONLY)
ATTACH '2.db' as db2 ( READ_ONLY)

Query : select colA, colB, sum(colC) from ( select colA, colB, colC from db1.table UNION ALL  select colA, colB, colC from db2.table  )  group by ALL

Sum of colC is incorrect.

2.db is copy of 1.db , no. of rows in 1.db are 288204.

### OS:

Ubuntu x64

### DuckDB Version:

0.9.1

### DuckDB Client:

Java

### Full Name:

PM Grey

### Affiliation:

NA

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
my test is ok
```
root@localhost:/data/data/com.termux/files/home/091# ./duckdb 1.db
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D create table t as select 1 a,2 b,3 c;
D .exit
root@localhost:/data/data/com.termux/files/home/091# ./duckdb 2.db
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D create table t as select 1 a,4 b,5 c;
D .exit
root@localhost:/data/data/com.termux/files/home/091# ./duckdb
v0.9.1 401c8061c6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH '1.db' as db1 ( READ_ONLY);
D ATTACH '2.db' as db2 ( READ_ONLY);
D select a,b,sum(c)from(select a,b,c from db1.t union all select a,b,c from db2.t)group by all;
┌───────┬───────┬────────┐
│   a   │   b   │ sum(c) │
│ int32 │ int32 │ int128 │
├───────┼───────┼────────┤
│     1 │     2 │      3 │
│     1 │     4 │      5 │
└───────┴───────┴────────┘
```
