### ISSUE TITLE
confusing index behaviour and null values

### ISSUE THREAD

**Issue by OrangieLou** [duckdb/duckdb#9517]
### What happens?

It doesn't seem sensible that indexing sometimes starts with 0 (json) and sometimes with 1 (lists and varchars). Access for elements that are out of bounds sometimes yield NULL (lists, json) and sometimes something other (varchars). There are several examples showcasing these differences:

The implicit conversion from json to varchar (due to access operator confusion) despite explicit cast is quite a pitfall for users.
```sql 
SELECT CAST(to_json([1, 2, 3]) AS json)[1] AS a;
-- ┌─────────┐
-- │    a    │
-- │ varchar │
-- ├─────────┤
-- │ [       │
-- └─────────┘
```
 Furthermore varchar indexing starts at 1, while json indexing starts at 0.
```sql 
SELECT to_json([1, 2, 3])->1 AS a;
-- ┌──────┐
-- │  a   │
-- │ json │
-- ├──────┤
-- │ 2    │
-- └──────┘
```

Two other cases of curious behaviour were found when working with casts to date and json. We can see why this happens but the behaviour does not feel intentional.

1. addition of quotes
```sql 
SELECT ('2013-11-10'::date)[1] AS b;
-- ┌─────────┐
-- │    b    │
-- │ varchar │
-- ├─────────┤
-- │ 2       │
-- └─────────┘

SELECT ('2013-11-10'::date::json)[1] AS b;
-- ┌─────────┐
-- │    b    │
-- │ varchar │
-- ├─────────┤
-- │ "       │
-- └─────────┘

SELECT ('2013-11-10'::json)[1] AS b;
-- Error: Conversion Error: Malformed JSON at byte 4 of input: unexpected content after document.  Input: 2013-11-10
```

2. Access out of bounds on varchar also seems to yield something other than NULL (tests with LIKE on whitespace or tabs also fail). Access out of bounds on lists yield null. Indexing starts with 1 in both cases.
```sql 
.nullvalue "null"
SELECT NULL;
-- ┌───────┐
-- │ NULL  │
-- │ int32 │
-- ├───────┤
-- │  null │
-- └───────┘

SELECT ('2013-11-10')[i] AS c FROM generate_series(0,12) as _(i);
-- ┌─────────┐
-- │    c    │
-- │ varchar │
-- ├─────────┤
-- │         │
-- │ 2       │
-- │ 0       │
-- │ 1       │
-- │ 3       │
-- │ -       │
-- │ 1       │
-- │ 1       │
-- │ -       │
-- │ 1       │
-- │ 0       │
-- │         │
-- │         │
-- ├─────────┤
-- │ 13 rows │
-- └─────────┘

SELECT ([1, 2, 3, 4])[0] AS c;
-- ┌───────┐
-- │   c   │
-- │ int32 │
-- ├───────┤
-- │  null │
-- └───────┘

SELECT ([1,2,3,4])[1] AS c;
-- ┌───────┐
-- │   c   │
-- │ int32 │
-- ├───────┤
-- │     1 │
-- └───────┘

```

### To Reproduce

```sql 
INSTALL json;
LOAD json;
.nullvalue "null"
SELECT NULL;

SELECT CAST(to_json([1, 2, 3]) AS json)[1] AS a;
SELECT to_json([1, 2, 3])->1 AS a;

SELECT ('2013-11-10'::date)[1] AS b;
SELECT ('2013-11-10'::date::json)[1] AS b;
SELECT ('2013-11-10'::json)[1] AS b;

SELECT ('2013-11-10')[i] AS c FROM generate_series(0,12) as _(i);
SELECT ([1, 2, 3, 4])[0] AS c;
SELECT ([1,2,3,4])[1] AS c;
```

### OS:

MacOS 13.3.1: aarch64 (Apple M1 Pro)

### DuckDB Version:

current master branch

### DuckDB Client:

binary

### Full Name:

Louisa Lambrecht

### Affiliation:

University of Tübingen

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by maiadegraaf** [comment]
Thanks for bringing up the issue. I'm currently reviewing it, and I've noticed that the first problem no longer returns a [.

```sql
SELECT CAST(to_json([1, 2, 3]) AS json)[1] AS a;
---┌──────┐
---|  a   │
---│ json │
---├──────┤
---│ 2    │
---└──────┘
```

Furthermore, while I agree that using 0-based indexing in JSON can be confusing, we have chosen, in this instance, to follow the conventions of PostgreSQL and SQLite.

I will continue to examine the other issues that have been raised.

**Comment by taniabogatsch** [comment]
I just had a look at this issue. In each case, the 0-vs.-1-based-indexing was a conscious choice to follow conventions, as said by @maiadegraaf in a previous comment.

```sql
SELECT CAST(to_json([1, 2, 3]) AS json)[1] AS a;
┌──────┐
│  a   │
│ json │
├──────┤
│ 2    │
└──────┘
```
✅ Fixed.

> Furthermore varchar indexing starts at 1, while json indexing starts at 0.

✅ Expected behavior.

```sql
.nullvalue "null"

SELECT NULL;
-- ┌───────┐
-- │ NULL  │
-- │ int32 │
-- ├───────┤
-- │  null │
-- └───────┘

SELECT ([1, 2, 3, 4])[0] AS c;
-- ┌───────┐
-- │   c   │
-- │ int32 │
-- ├───────┤
-- │  null │
-- └───────┘

SELECT ([1,2,3,4])[1] AS c;
-- ┌───────┐
-- │   c   │
-- │ int32 │
-- ├───────┤
-- │     1 │
-- └───────┘
```
✅ Expected behavior, indexing `VARCHAR` out of bounds returns `NULL`.

```sql
SELECT ('2013-11-10'::date)[1] AS b;
Binder Error: No function matches the given name and argument types 'array_extract(DATE, INTEGER_LITERAL)'. You might need to add explicit type casts.
	Candidate functions:
	array_extract(ANY[], BIGINT) -> ANY
	array_extract(VARCHAR, BIGINT) -> VARCHAR
	array_extract(STRUCT, VARCHAR) -> ANY
	array_extract(STRUCT, BIGINT) -> ANY
```
✅ We have disabled (confusing) implicit string conversions in duckdb with the latest changes.

```sql
D SELECT ('2013-11-10'::json)[1] AS b;
Conversion Error: Malformed JSON at byte 4 of input: unexpected content after document.  Input: 2013-11-10
LINE 1: SELECT ('2013-11-10'::json)[1] AS b;
```
✅ Expected, as `'2013-11-10'` is not valid JSON.

### Open issues
These still need to be resolved. We'll add these to our issue tracker as separate issues.

```sql
# should be NULL, not ''
SELECT ('2013-11-10')[i] = '' FROM generate_series(0,12) as _(i);
┌────────────────────────┐
│ ('2013-11-10'[i] = '') │
│        boolean         │
├────────────────────────┤
│ true                   │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ false                  │
│ true                   │
│ true                   │
├────────────────────────┤
│        13 rows         │
└────────────────────────┘
```

Investigate the expected behavior here.
```sql
D SELECT ('2013-11-10'::date::json)[1] AS b;
┌──────┐
│  b   │
│ json │
├──────┤
│ null │
└──────┘
```

**Note**: I'll close this issue as we'll split the remaining ones up into smaller tasks.

**Comment by OrangieLou** [comment]
Thanks @taniabogatsch! This is great. :)

**Comment by maiadegraaf** [comment]
Hi @OrangieLou, we consulted with our resident JSON expert @lnkuiper regarding the expected JSON behaviour and this is what he said:

> Both are expected behavior.
> 
> The first one casts the `VARCHAR` to `JSON`, and then uses the convenient list extract syntax to do a `json_extract`. This would be equivalent:
> ```sql
> D SELECT '2013-11-10'::date::json b;
> ┌──────────────┐
> │      b       │
> │     json     │
> ├──────────────┤
> │ "2013-11-10" │
> └──────────────┘
> SELECT json_extract('2013-11-10'::date::json, '$[1]') AS b;
> ┌──────┐
> │  b   │
> │ json │
> ├──────┤
> │      │
> └──────┘
> ```
> Which returns `NULL` because the JSON path `$[1]` does not exist in the JSON.
> 
> The second casts the VARCHAR immediately to JSON, but the VARCHAR is not valid JSON, so we have throw an error.
> ```
> D SELECT '2013-11-10'::json;
> Conversion Error: Malformed JSON at byte 4 of input: unexpected content after document.  Input: 2013-11-10
> LINE 1: SELECT '2013-11-10'::json;
> ```
> The confusion comes from the fact that _casting `VARCHAR` to `JSON` is a special case cast_. Whereas casting any other data type to `JSON` causes it to be converted to valid JSON, i.e., it is the same as doing `to_json(...)`, casting `VARCHAR` to `JSON` causes it to be parsed. We need this special case, otherwise we would get this behavior when casting `VARCHAR` to `JSON`:
> ```sql
> SELECT '{"duck":42}'::JSON;
> -- "{\"duck\":42}" quoted and escaped JSON instead of parsed and validated JSON
> ```

So currently the only outstanding issue is the one regarding the `null`/whitespace.

**Comment by OrangieLou** [comment]
Thank you for the clarification @maiadegraaf @lnkuiper. I can see now that the first two cases I posted were actually the same problem with the `[1]` operator. Cool that this is fixed now! :) 
I'm curious what the mysterious non-null-whitespace thingy is. Please keep me updated here or throw me a pointer to the new issue.
