### ISSUE TITLE
Row function returns struct with empty keys

### ISSUE THREAD

**Issue by pyalex** [duckdb/duckdb#9556]
### What happens?

This seems like a regression introduced in 0.9.0
```
In [1]: duckdb.sql("""select row(i) from generate_series(10) tbl(i)""")
Out[1]:
┌─────────────────┐
│   main.row(i)   │
│ struct( bigint) │
├─────────────────┤
│ {'': 0}         │
│ {'': 1}         │
│ {'': 2}         │
│ {'': 3}         │
│ {'': 4}         │
│ {'': 5}         │
│ {'': 6}         │
│ {'': 7}         │
│ {'': 8}         │
│ {'': 9}         │
│ {'': 10}        │
├─────────────────┤
│     11 rows     │
└─────────────────┘
```

This contradicts the [documentation](https://duckdb.org/docs/archive/0.9.1/sql/data_types/struct#creating-structs-with-the-row-function):
```
The row function can be used to automatically convert multiple columns to a single struct column. The name of each input column is used as a key, and the value of each column becomes the struct’s value at that key.
```

For reference same code in 0.8.1 would return
```
┌──────────────────────────┐
│ main.struct_pack(i := i) │
│     struct(i bigint)     │
├──────────────────────────┤
│ {'i': 0}                 │
│ {'i': 1}                 │
│ {'i': 2}                 │
│ {'i': 3}                 │
│ {'i': 4}                 │
│ {'i': 5}                 │
│ {'i': 6}                 │
│ {'i': 7}                 │
│ {'i': 8}                 │
│ {'i': 9}                 │
│ {'i': 10}                │
├──────────────────────────┤
│         11 rows          │
└──────────────────────────┘
```

### To Reproduce

duckdb.sql("""select row(i) from generate_series(10) tbl(i)""")

### OS:

aarch64

### DuckDB Version:

0.9.x

### DuckDB Client:

Python

### Full Name:

Oleksii Moskalenko

### Affiliation:

Tecton

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
<https://github.com/duckdb/duckdb/pull/8942>

We should definitely update the docs however, thanks for raising the issue 👍

**Comment by Tishj** [comment]
Fixed by <https://github.com/duckdb/duckdb-web/pull/1490>
