### ISSUE TITLE
Missing column does not throw error when used in subquery within a join

### ISSUE THREAD

**Issue by kku1993** [duckdb/duckdb#9557]
### What happens?

When using a subquery in a join, the subquery may reference missing columns without an error being thrown.

### To Reproduce

Run the following query. Expectation is to throw an error because `join_key` does not exist on `table_a`. But what happens is that a row is returned.

```sql
WITH
    table_a as (
        select 1 as my_value
    ),
    table_b as (
        select 1 as join_key
    )

select * from table_b 
JOIN (
    select distinct join_key, my_value from table_a
) USING (join_key)
```

### OS:

macOS 13.6.1 (22G313) Apple M1

### DuckDB Version:

v0.9.0 0d84ccf478

### DuckDB Client:

CLI

### Full Name:

Kevin Ku

### Affiliation:

Watershed

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the PR!

What happens here is that the query is automatically transformed into a `LATERAL` join, so `join_key` in the right-side actually refers to `join_key` in the left side. In Postgres this requires the explicit `LATERAL` keyword, but DuckDB automatically infers that a join is a lateral join by trying to bind columns on the right-hand side with values from the left-hand side.

The query in Postgres would look as follows:

```sql
WITH
    table_a as (
        select 1 as my_value
    ),
    table_b as (
        select 1 as join_key
    )
select * from table_b 
JOIN LATERAL (
    select join_key, my_value from table_a
) t USING (join_key)
 join_key | my_value 
----------+----------
        1 |        1
(1 row)

```
