### ISSUE TITLE
Nonspecific JDBC type reported for HUGEINT query result columns

### ISSUE THREAD

**Issue by rkennedy-mode** [duckdb/duckdb#9585]
### What happens?

When executing a query via the DuckDB JDBC driver where the results include a `HUGEINT` column, the driver reports the column type as [java.sql.Types.JAVA_OBJECT](https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html#JAVA_OBJECT) (integer value 2000).

This is due to a "fall through" condition in the `switch` block in [DuckDBResultsSetMetaData.type_to_int(DuckDBColumnType)](https://github.com/duckdb/duckdb/blob/60ddc316ca0c1585f14d55aa73f9db59d8fc05d1/tools/jdbc/src/main/java/org/duckdb/DuckDBResultSetMetaData.java#L97-L135). There's no `case` statement for `HUGEINT` to provide a more precise match than `JAVA_OBJECT`.

`HUGEINT` being a 128bit type in DuckDB means that `Types.BIGINT` may not entirely be suitable for this. `Types.DECIMAL`…perhaps? 🤷‍♂️ This could potentially work in conjunction with [ResultSetMetaData.getPrecision(int column)](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getPrecision-int-) and [ResultSetMetaData.getScale(int column)](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getScale-int-) to allow callers to ascertain the proper shape of the column values. I don't actually know what's considered "proper" in JDBC here. JDBC is a bit too ambiguous for my liking.

### To Reproduce

This code:

```java
import java.sql.DriverManager;

class DuckDBHugeintTypeProblem {
    public static void main(String[] args) throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:duckdb:");
             var statement = connection.createStatement();
             var results = statement.executeQuery("SELECT CAST(1 AS HUGEINT) AS HUGE_ONE")) {
            System.out.println("results.getMetaData().getColumnType(1) = " + results.getMetaData().getColumnType(1));
            System.out.println("results.getMetaData().getColumnTypeName(1) = " + results.getMetaData().getColumnTypeName(1));
        }
    }
}
```

…produces the following output:

```
results.getMetaData().getColumnType(1) = 2000
results.getMetaData().getColumnTypeName(1) = HUGEINT
```

### OS:

macOS aarch64

### DuckDB Version:

0.9.1

### DuckDB Client:

JDBC

### Full Name:

Ryan Kennedy

### Affiliation:

Mode Analytics/ThoughtSpot

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
I'd prefer to not deviate from the JDBC spec here if possible - can you give some context here to what your use case is?
Would a DuckDB-specific method work better here perhaps?

**Comment by rkennedy-mode** [comment]
Here's the specifics of what we're doing. We're exposing a DuckDB via Arrow Flight SQL using portions of the Flight SQL Java implementation to generate schema information from the ResultSetMetaData. That mapping code utilizes the JDBC type to determine how to perform the mapping: https://github.com/apache/arrow/blob/e62ec62e40b04b0bfce76d58369845d3aa96a419/java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowUtils.java#L148-L213

This is where the processing falls through, ultimately triggering an UnsupportedOperationException because the Arrow mapping code doesn't know well enough what to do with a `JAVA_OBJECT` type. I have, for the moment, added an explicit type override for our `HUGEINT` results columns to map them to a BIGINT, which seems to make the Arrow code happy enough to do the right thing. At the same time, BIGINT on a number of databases can cap out at 64bit. So I worry about just having DuckDB HUGEINTs map to JDBC BIGINT, not knowing what it may do to other tools.

I've tested the queries that generate a HUGEINT in other JDBC query tools that don't know anything specifically about DuckDB or Arrow Flight SQL and they seem to work fine with JAVA_OBJECT, leading me to believe they probably call ResultSet.getObject(int) and then do some introspection of the Java type returned to decide what to do with it.

That won't work for my use case because I get a ResultSetMetaData object from a PreparedStatement **prior** to that statement being executed (i.e. I don't have a ResultSet yet). This is part of the Arrow Flight SQL protocol allowing the method to prepare a statement to return the schema details for any subsequently executed statement. So without more detailed JDBC types available in the ResultSetMetaData returned by PreparedStatement.getMetaData(), I end up using ResultSetMetaData.getColumnTypeName(int) to see if it's a HUGEINT and key off that for generating the Arrow Flight SQL schema details to return.

Apologies if the above is a bit ramble-y. I haven't had my caffeine yet today.

**Comment by Mause** [comment]
Ah, so the actual issue is that arrow doesn't properly support JAVA_OBJECT here. Have you investigated using [`setJdbcToArrowTypeConverter`](https://github.com/apache/arrow/blob/75a04030996261333e843a93f4981156372fa7f8/java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrowConfigBuilder.java#L220) to fix this instead? It seems like it was added for this exact issue

**Comment by rkennedy-mode** [comment]
That's actually exactly what I'm doing as a workaround right now. The only way that works, however, is to pull the value from `ResultSetMetaData.getColumnTypeName(int)`, which returns `HUGEINT` today. So it depends very strongly on DuckDB never changing that String return value, introducing new values, etc. It definitely works, I'm just worried about how brittle that may be in the longer run.

Anyway, as you've pointed out I have a workaround. Maybe I can utilize the [DuckDBColumnType](https://github.com/duckdb/duckdb/blob/main/tools/jdbc/src/main/java/org/duckdb/DuckDBColumnType.java) enum to generate a test case to ensure we test with all know types during our continuous integration and raise a failure if a new type is introduced, which we may not have added a mapping for.

So maybe we can close this as a bug and I can raise an enhancement request if DuckDBColumnType is insufficient to ensure we find out at build time if we're going to have any issues.

**Comment by Mause** [comment]
> So maybe we can close this as a bug and I can raise an enhancement request if DuckDBColumnType is insufficient to ensure we find out at build time if we're going to have any issues.

Sounds reasonable, I'll go ahead and close this bug report then

**Comment by ryanhamilton** [comment]
FYI seems this changed to OTHER rather than JAVA_OBJECT in 1.3.0.0 .
