### ISSUE TITLE
Response issue for columns of type BIGINT as well as those resulting from `read_csv_auto` (v0.9.1 Node)

### ISSUE THREAD

**Issue by thomascmurphy** [duckdb/duckdb#9586]
### What happens?

Howdy! We are trying to upgrade the duckdb Node package from 0.8.0 to 0.9.1 and are trying to figure out how to deal with a breaking change that popped up. We are doing some pretty simple queries on parquet files, and for columns of type BIGINT we are seeing the result being an actual `bigint` JS type whereas previously there were just type `number`. I could see this being intentional (though definitely a breaking change), but the behavior is the same for any table we create by using `read_csv_auto` with columns that are integers (no matter the size). I don't see anything listed in the migration guide that would indicate a change resulting in this behavior, is it a known thing?

### To Reproduce

```
import { Database } from 'duckdb';
import path from 'path';

async function testResponse() {
  const db = new Database(':memory:');
    await new Promise((resolve, reject) => {
      db.run(
        `CREATE TABLE IF NOT EXISTS data ("col1" INTEGER,"col2" BIGINT,"col3" HUGEINT)`,
        (error: any, result: any) => {
          if (error) {
            db.close(() => {});
            return reject(error);
          }
          return resolve(result);
        }
      );
    });
    const insert = db.prepare(`INSERT INTO data VALUES(?,?,?)`);
    insert.run(1, 2, 3);
    insert.finalize();
    const results = await new Promise((resolve: (val: TRows) => void, reject) => {
      db.all('SELECT * FROM data', (err: any, rows: TableData) => {
        db.close(() => {
          if (err) {
            return reject(err);
          }
          return resolve(Array.isArray(rows) ? rows : [rows]);
        });
      });
    });
    return results;
}

public async testCsvResponse() {
    const db = new Database(':memory:');
    const csvLocation = path.resolve(__dirname, `./test-csv.csv`);
    await new Promise((resolve, reject) => {
      db.run(
        `CREATE VIEW data AS SELECT * FROM read_csv_auto('${csvLocation}', HEADER=TRUE)`,
        (error: any, result: any) => {
          if (error) {
            db.close(() => {});
            return reject(error);
          }
          return resolve(result);
        }
      );
    });
    const results = await new Promise((resolve: (val: TRows) => void, reject) => {
      db.all('SELECT * FROM data', (err: any, rows: TableData) => {
        db.close(() => {
          if (err) {
            return reject(err);
          }
          return resolve(Array.isArray(rows) ? rows : [rows]);
        });
      });
    });
    return results;
  }

```
(test-csv.csv contents)
```
col1,col2,col3
11,12,13
21,22,23
31,32,33
```
If you run`testResponse()` you can see the results show that col1 is of type `number` but col2 and col3 are of type `bigint` (if you use v 0.8.0 they are of type `number`).
If you run `testCsvResponse()` you can see the columns are all of type `bigint` (again, previously being of type `number`)

### OS:

macOS 12.5 Apple M1 Pro

### DuckDB Version:

0.9.1

### DuckDB Client:

Node

### Full Name:

Thomas Murphy

### Affiliation:

Alteryx

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
This change was intentional yes, it was made here: https://github.com/duckdb/duckdb/pull/7740/files#diff-8fc6aaae51697d734db39aa4d1a46e81493bbdfef81726246d04dbddb1fb3ce1 (back in June). It should only have affected UBIGINT, BIGINT, and HUGEINT types returned by DuckDB.

If you want to change the types inferred by the read_csv_auto function, you can provide a columns parameter, as it defaults to BIGINT. You can use the `DESCRIBE` statement to inspect the types returned by a `SELECT` query as well.

Does that help?

**Comment by thomascmurphy** [comment]
So the first change makes sense (you explicitly define bigint columns, not weird to get bigint type response). But the read_csv_auto swapping the default to bigint is odd to me, previously we didn't even need to know about the headers/fields when reading it but now we'll have to explicitly set the column types to INTEGER if needed (seems to defeat the purpose of the auto-read, but maybe I'm missing something). Another thing that I noticed is that if I do something like a `SELECT COUNT(*)` the result there is automatically a bigint type. None of this would be a huge deal if it weren't for serialization issues with bigint types.

**Comment by Mause** [comment]
I think you misunderstand - the default type for numbers from CSV has been BIGINT since 0.7.1. The only change has been changing the type mapping to more accurately reflect types.

As far as serializing bigint goes, you can specify a "replacer" function to `JSON.stringify`:
```js
JSON.stringify(5n, (key, value) => typeof value === 'bigint' ? value.toString() : value)
```

**Comment by thomascmurphy** [comment]
Ahhh I see, my apologies, that makes more sense. The serialization thing is mostly a pain because of the spread-out nature of it. The snippet you listed would be great in many places where we're doing direct serialization (like logs), but when we do something like pass back a bit of paginated data via a message queue (which does the serialization internally) it's trickier. Each of these spots probably has a fix, there are just a lot of them and each slightly different. There's no way to configure the type mapping on the duckdb side is there (I couldn't see anything in the docs, but didn't dig too deep)? The discrepancy between value ranges of the JS number type vs bigint type are just so different from their sql counterparts, I could see wanting a bit of control there, though I'm sure my use-case is skewing my opinion of what others might find useful 😆

**Comment by Mause** [comment]
I did consider adding some configuration here (so the old behaviour was opt-inable), but I figured I'd wait to see if anyone actually wanted it.

For now, you can do something like this, though obviously perf will suffer a smidge
```js
const object = JSON.parse(
    JSON.stringify(5n, (key, value) => typeof value === 'bigint' ? value.toString() : value)
);
```

or some other method of traversing what DuckDB returns to convert the types

**Comment by thomascmurphy** [comment]
That makes sense as well (and aligns with why we defaulted to BIGINT sql types just to ensure we didn't have that same out-of-bounds issue). The `auto_type_candidates` sounds like it'd be a great stopgap for us, but I don't see that listed in the docs, I'm assuming it's just another option on `read_csv_auto`?

**Comment by pdet** [comment]
> That makes sense as well (and aligns with why we defaulted to BIGINT sql types just to ensure we didn't have that same out-of-bounds issue). The `auto_type_candidates` sounds like it'd be a great stopgap for us, but I don't see that listed in the docs, I'm assuming it's just another option on `read_csv_auto`?

Indeed, it is missing from the docs, I'll adjust that in a bit, you just need to send a list of types that will be used in the sniffer

e.g.,

```sql
SELECT * FROM read_csv_auto ('csv_file.csv', auto_type_candidates=['BIGINT','VARCHAR']);
```

**Comment by szarnyasg** [comment]
`auto_type_candidates` was added to the docs, see https://github.com/duckdb/duckdb-web/pull/1515
