### ISSUE TITLE
JDBC: WSL paths get relativized instead of being used as is

### ISSUE THREAD

**Issue by ShadelessFox** [duckdb/duckdb#9597]
### What happens?

When passing a path to a database file located in WSL, DuckDB tries to relativize it instead of using it as is but fails to open that file under the new path because now it points to a completely different location.

The problematic code:
https://github.com/duckdb/duckdb/blob/493905d55b266db0961bfe6492da2a2c6a3f4202/src/main/db_instance_cache.cpp#L19-L22

### To Reproduce

You will need to install WSL first (I'm using `Ubuntu`):
https://learn.microsoft.com/en-us/windows/wsl/install

The following snippet can be used to reproduce the issue:
```java
final Path localPath = Path.of("duck.db").toAbsolutePath();

try (Connection ignored = DriverManager.getConnection("jdbc:duckdb:" + localPath)) {
    // Create a new database file
}

// You might need to replace the `Ubuntu` directory with whatever distribution you have
final Path wslPath = Path.of("\\\\wsl.localhost\\Ubuntu\\tmp\\duck.db");

// This also used to demonstrate that NIO can handle such paths
Files.move(localPath, wslPath, StandardCopyOption.REPLACE_EXISTING);

try (Connection ignored = DriverManager.getConnection("jdbc:duckdb:" + wslPath)) {
    // Try opening the same database but located in WSL.
    // Observe that it will be relativized to the current working directory
}
```

### OS:

Windows 11 x64

### DuckDB Version:

0.9.1

### DuckDB Client:

Java JDBC / DBeaver 23.2.4

### Full Name:

Ian Vinogradov

### Affiliation:

DBeaver

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Just to clarify, are you running this code under WSL, or just trying to access files in the WSL filesystem?

**Comment by ShadelessFox** [comment]
My bad, sorry. Just trying to access files there while running on Windows.

**Comment by ShadelessFox** [comment]
Thanks!
