### ISSUE TITLE
DuckDB isn't correctly parsing headers with quotes

### ISSUE THREAD

**Issue by njaremko** [duckdb/duckdb#9602]
### What happens?

The column names should be `foo "bar`, and `name`, but instead it becomes `foo bar` and ` name` (note the leading whitespace)

<img width="785" alt="Screenshot 2023-11-07 at 5 07 38 PM" src="https://github.com/duckdb/duckdb/assets/3753178/8aa9818e-9a0c-4054-b85a-79e0e322dc82">

### To Reproduce

Create the following file (`q.csv`):
```csv
"foo ""bar",name
1,rob
2,sally
```

Then run 
```sql
SELECT * FROM read_csv_auto('q.csv', HEADER=TRUE, ALL_VARCHAR=TRUE, normalize_names=false);
SELECT * FROM read_csv_auto('q.csv', HEADER=TRUE, ALL_VARCHAR=TRUE, normalize_names=true);
```

### OS:

MacOS 14 aarch64

### DuckDB Version:

0.9.1

### DuckDB Client:

Ruby SDK

### Full Name:

Nathan Jaremko

### Affiliation:

Census

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by njaremko** [comment]
If it helps, I think this last worked correctly in 0.7.1

**Comment by szarnyasg** [comment]
Sure, it helps, thanks!
