### ISSUE TITLE
Wrong dtypes when read an empty parquet with str column type.

### ISSUE THREAD

**Issue by AcMikoto** [duckdb/duckdb#9608]
### What happens?

I have a batch of parquet files with str column type, and  some of the files are empty, when I read them together with duckdb, I will get a Conversion Error: Could not convert string 'xxx' to INT32.    
After debuging, it was found that duckdb has a problem with the str column of an empty parquet. it will be considered as the INT32 type.

### To Reproduce

```
import duckdb    
import pandas as pd    
df = pd.DataFrame(pd.Series(name="a", dtype=str))    
df.to_parquet("test.parquet")    
duckdb.sql('SELECT * FROM "test.parquet"').df().dtypes    
```

### OS:

ubuntu 22.04

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Peng Zhu

### Affiliation:

Tsinghua University

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hello, please include a parquet file (or instructions for creating one) that triggers the error.

**Comment by AcMikoto** [comment]
I have already add these instructions, plz refer to the part "To Reproduce"

**Comment by Mytherin** [comment]
Thanks for the report!

Looks to me like this is a problem in Pandas, not in DuckDB. The Parquet file does not contain any mention of the string data-type, instead it is converted to INT32/NULL:

```sql
D FROM parquet_schema('test.parquet');
┌──────────────┬─────────┬─────────┬─────────────┬─────────────────┬──────────────┬────────────────┬───────┬───────────┬──────────┬──────────────┐
│  file_name   │  name   │  type   │ type_length │ repetition_type │ num_children │ converted_type │ scale │ precision │ field_id │ logical_type │
│   varchar    │ varchar │ varchar │   varchar   │     varchar     │    int64     │    varchar     │ int64 │   int64   │  int64   │   varchar    │
├──────────────┼─────────┼─────────┼─────────────┼─────────────────┼──────────────┼────────────────┼───────┼───────────┼──────────┼──────────────┤
│ test.parquet │ schema  │ NULL    │ NULL        │ REQUIRED        │            1 │ NULL           │  NULL │      NULL │     NULL │ NULL         │
│ test.parquet │ a       │ INT32   │ NULL        │ OPTIONAL        │         NULL │ NULL           │  NULL │      NULL │     NULL │ NullType()   │
└──────────────┴─────────┴─────────┴─────────────┴─────────────────┴──────────────┴────────────────┴───────┴───────────┴──────────┴──────────────┘
```

I would recommend filing a bug report with Pandas instead.

**Comment by Mytherin** [comment]
As a solution to your original problem - if you want to read a batch of Parquet files where the columns have different types you can use the `union_by_name` flag in the `read_parquet` function, which will correctly unify the schema.
