### ISSUE TITLE
duckDB crashes while reading a larger json file using httpfs

### ISSUE THREAD

**Issue by vivien-crayon** [duckdb/duckdb#9609]
### What happens?

Hello, I'm running into a very similar issue : when querying a (bigger : 90Mo) json file on an object storage, duckDB gets stuck at 99% and eventually crashes my terminal / python / VScode

- Object storage : tried GCS and AWS S3 with the same results 
- duckDB versions : 0.8.1 (got a segfault error), 0.9.0, 0.9.1 and 0.9.2dev (silent crashes)

On a 60 MB file with 6000 lines, it is working fine but on the larger (90MB with 50K lines) it crashes; importing the latter file stored locally works like a charm

(The AWS settings are stored as env variables that's why they don't appear here ) 
I can privately share the data or temporary access keys to it if needed 

Thanks in advance for the help !

### To Reproduce

Before starting duckDB, create the necessary en variables

export AWS_REGION="europe-west3"
export AWS_ACCESS_KEY_ID="GOOG**********"
export AWS_SECRET_ACCESS_KEY="******************"
export DUCKDB_S3_ENDPOINT="storage.googleapis.com"

```
v0.9.1 401c8061c6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D FORCE INSTALL httpfs;
D LOAD httpfs;
D SELECT count(*) from read_json_auto('s3://vivien-crayon-test-bucket/raw/github/pull_requests/2023-11-03-pull_requests.jsonl');
```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│         6026 │
└──────────────┘
`D SELECT count(*) from read_json_auto('s3://vivien-crayon-test-bucket/raw/github/commits/2023-11-03-commits.jsonl');`
 99% ▕███████████████████████████████████████████████████████████▍▏ 

### OS:

MacOS sonoma + linux/amd64 (docker)

### DuckDB Version:

0.8.1 - 0.9.2dev

### DuckDB Client:

Python, CLI

### Full Name:

Vivien Roussez

### Affiliation:

Crayon

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
Hey @vivien-crayon thanks for reporting this one, would you be open to share the data either through a public bucket or by sharing a key with us privately? You can reach out at sam@duckdblabs.com
