### ISSUE TITLE
Missing C/C++ headers in homebrew installs

### ISSUE THREAD

**Issue by mnovelo** [duckdb/duckdb#9611]
### What happens?

Previously installing duckdb via homebrew would also add duckdb.h to /opt/homebrew/include

This has been an expectation for https://github.com/suketa/ruby-duckdb

### To Reproduce

Now installing duckdb, v0.9.1, via homebrew does not include the headers, which causes installs of the ruby-duckdb gem to fail unless we add the headers manually.

Previously, I could find /opt/homebrew/include/duckdb, /opt/homebrew/include/duckdb.h, and /opt/homebrew/include/duckdb.hpp All of which were aliases to the files for the currently installed version of duckdb. Installing via homebrew now does not add these files or aliases.

### OS:

arm64_sonoma

### DuckDB Version:

0.9.1

### DuckDB Client:

Ruby

### Full Name:

Mauricio Novelo

### Affiliation:

CampusESP

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Headers and libraries for DuckDB were installed in a previous versions of homebrew package, but I did file a PR for removing them that just got merged.
Rationale was that that shipping libraries, while potentially useful like in this case, was not deemed to be of general utility enough to warrant any user of brew-installed duckdb to have those files on their system (and to have to wait for them to be downloaded).

Would it be possible for users to rely on building duckdb from sources on the fly? (even just as a temporary workaround?)

**Comment by carlopi** [comment]
Connected issue that will also need addressing: https://github.com/duckdb/duckdb/issues/9475

**Comment by Maxxen** [comment]
Could we not ship a separate development package with headers and libs? E.g. `duckdb-devel` or equivalent brew convention.

**Comment by Mytherin** [comment]
I would say shipping `duckdb.h` would make sense - we can skip the C++ headers. That should still have the same effect of reducing the size of the hombrew installation drastically.

**Comment by mnovelo** [comment]
@Mytherin, my concern with only including the `duckdb.h` file is that https://github.com/suketa/ruby-duckdb is that, I believe, dependent on the C++ headers, so a `duckdb-devel` like @Maxxen suggested, that includes those, would be greatly appreciated!

As a temporary workaround, we can download those files and link them manually with something like this

```shell
LIBDUCKDB_PATH=$(pwd)/lib/duckdb/libduckdb-osx-universal
bundle config set --local build.duckdb --with-duckdb-include=$LIBDUCKDB_PATH --with-duckdb-lib=$LIBDUCKDB_PATH
bundle install --redownload
sudo ln -s $LIBDUCKDB_PATH/libduckdb.dylib /usr/local/lib/libduckdb.dylib
xattr -w com.apple.quarantine "$(xattr -p com.apple.quarantine $LIBDUCKDB_PATH/libduckdb.dylib | sed 's/^.\{4\}/00c1/')" $LIBDUCKDB_PATH/libduckdb.dylib
```

**Comment by mnovelo** [comment]
Actually what I had above doesn't work now. It's what I had done previously to use a nightly build, but I've not been successful in using [v0.9.1/libduckdb-osx-universal.zip](https://github.com/duckdb/duckdb/releases/download/v0.9.1/libduckdb-osx-universal.zip) to get ruby-duckdb to run successful

**Comment by Mytherin** [comment]
I'm not opposed to shipping a `duckdb-devel` - but perhaps the correct fix for duckdb-ruby is to ship DuckDB as part of the installation (which is what other clients do as well). I'm not familiar with Ruby's installation process but it seems that [sqlite3-ruby](https://github.com/sparklemotion/sqlite3-ruby) ships SQLite as well. This should make the installation process a lot simpler.

**Comment by mnovelo** [comment]
I'll look into creating a PR for duckdb-ruby that includes the requisite headers as part of it like sqlite3-ruby does. Thanks for the advice!

If you'd like to close this issue for now, I'm fine with that, unless you'd like to leave it open to track shipping of `duckdb-devel` for other purposes

**Comment by carlopi** [comment]
@mnovelo: update, we though more about this, and uses cases like yours, and I just filed a PR (https://github.com/Homebrew/homebrew-core/pull/154240) that adds back headers and libraries to the homebrew's duckdb package.

I would expect this to be considered for merging in the next day or so.

**Comment by carlopi** [comment]
[Homebrew PR has been merged](https://github.com/Homebrew/homebrew-core/pull/154240#event-10954157389), closing this as solved.

**Comment by mnovelo** [comment]
thank you so much! With v0.9.2, ruby-duckdb installs as expected
