### ISSUE TITLE
Incorrect behaviour when using ORDER BY in a CTE and using LAST() alongside GROUP BY referencing the sorted CTE.

### ISSUE THREAD

**Issue by zhasan49** [duckdb/duckdb#9612]
### What happens?

The data consists of a customer_id (int), a feature value (int) and a timestamp. Each row represents a customer interaction. The desired output is identifying the most recent interaction for each customer alongside the feature value. 

The approach taken to solve this involved ordering by the data by customer_id and timestamp (default ordering is ascending so data is ordered such that the most recent timestamp is last). Then we group by the customer_id and take the LAST timestamp and feature_value for each customer_id.

This works for the majority of records but there are random instances where the record returned is NOT the most recent and is instead a random interaction. I have reproduced this in Google Colab although there's a bit of randomness to it as it's not always reproduced. On my M1 MacBook the problem is reliably reproduced with 4-5 incorrect records.

### To Reproduce

Google colab notebook demonstrating issue with dummy data:

https://colab.research.google.com/drive/1kKqMQStgHOA41xk9WEKcB_apGlm0YarX?usp=sharing

Note I have also reproduced this local using the main build (on MacOS Venutra 13.5.1 on a M1 Pro MacBook, it appears to be more reliably reproduced in this context).

Code to reproduce

```
import pandas as pd
import duckdb
from textwrap import dedent
import numpy as np

def execute_query(
    query: str,
    **register: pd.DataFrame,
) -> pd.DataFrame:
    conn = duckdb.connect()
    for k, v in register.items():
        conn.register(k, v)

    return conn.execute(query).fetch_df()


rows = 100000
interactions = pd.DataFrame()
interactions['customer_id'] = np.random.randint(0, 10000, size=rows)
interactions['value'] = np.random.randint(0, 500, size=rows)
interactions['timestamp'] = pd.to_datetime(
    np.random.randint(
        int(pd.Timestamp.today().timestamp()) - 2592000,
        int(pd.Timestamp.today().timestamp()),
        size=rows,
    ),
    unit='s',
)

interactions.sort_values(by=['customer_id', 'timestamp'], inplace=True)

test_query = dedent(
        f"""
        WITH base AS (
            SELECT
                interactions.customer_id,
                interactions.value,
                interactions.timestamp,
                MAX(interactions.timestamp) OVER (PARTITION BY interactions.customer_id) AS max_timestamp,
            FROM interactions

            ORDER BY interactions.customer_id, interactions.timestamp, interactions.value
        ),
        latest_value AS (
            SELECT
                customer_id,
                LAST(value) AS value,
                LAST(timestamp) AS timestamp,
                MAX(timestamp) AS max_timestamp,
            FROM base
            GROUP BY customer_id
        )
        SELECT
            value AS feature_value,
            latest_value.timestamp AS feature_timestamp,
            max_timestamp AS feature_max_timestamp,
        FROM latest_value
        ORDER BY latest_value.customer_id
    """)

output_data_synthetic = execute_query(test_query, interactions=interactions)

print(output_data_synthetic[output_data_synthetic['feature_timestamp'] != output_data_synthetic['feature_max_timestamp']].dropna())
```

### OS:

Ventura 13.5.1 (M1 Pro Macbook), Google Colab (Probably ubuntu linux)

### DuckDB Version:

0.9.1 (and earlier)

### DuckDB Client:

Python

### Full Name:

Zobair Hasan

### Affiliation:

Marks & Spencer

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi, thanks for reporting this. I looked at your Python code and it's just a few edits away from being self-contained - could you please turn it into a standalone script that reproduces the error in one go?

**Comment by zhasan49** [comment]
@szarnyasg  Updated with a standalone script. Output will be a DataFrame with entries with unexpected records.

**Comment by szarnyasg** [comment]
Thank you!

**Comment by kryonix** [comment]
Hi all! I think this is expected behavior and not a bug/issue. CTEs do not (necessarily) preserve the row order you expect. But more importantly, aggregates may ignore the ordering anyways. I think your query should look as follows:

```
import pandas as pd
import duckdb
from textwrap import dedent
import numpy as np

def execute_query(
    query: str,
    **register: pd.DataFrame,
) -> pd.DataFrame:
    conn = duckdb.connect()
    for k, v in register.items():
        conn.register(k, v)

    return conn.execute(query).fetch_df()


rows = 100000
interactions = pd.DataFrame()
interactions['customer_id'] = np.random.randint(0, 10000, size=rows)
interactions['value'] = np.random.randint(0, 500, size=rows)
interactions['timestamp'] = pd.to_datetime(
    np.random.randint(
        int(pd.Timestamp.today().timestamp()) - 2592000,
        int(pd.Timestamp.today().timestamp()),
        size=rows,
    ),
    unit='s',
)

interactions.sort_values(by=['customer_id', 'timestamp'], inplace=True)

test_query = dedent(
        f"""
        WITH base AS (
            SELECT
                interactions.customer_id,
                interactions.value,
                interactions.timestamp,
                MAX(interactions.timestamp) OVER (PARTITION BY interactions.customer_id) AS max_timestamp,
            FROM interactions
        ),
        latest_value AS (
            SELECT
                customer_id,
                LAST(value ORDER BY base.customer_id, base.timestamp, base.value) AS value,
                LAST(timestamp ORDER BY base.customer_id, base.timestamp, base.value) AS timestamp,
                MAX(timestamp ORDER BY base.customer_id, base.timestamp, base.value) AS max_timestamp
            FROM base
            GROUP BY customer_id
        )
        SELECT
            value AS feature_value,
            latest_value.timestamp AS feature_timestamp,
            max_timestamp AS feature_max_timestamp,
        FROM latest_value
        ORDER BY latest_value.customer_id
    """)

output_data_synthetic = execute_query(test_query, interactions=interactions)

print(output_data_synthetic[output_data_synthetic['feature_timestamp'] != output_data_synthetic['feature_max_timestamp']].dropna())
```

**Comment by zhasan49** [comment]
Thanks, this makes sense. I'm happy to close.
