### ISSUE TITLE
Update CSV AUTO_DETECT Documentation

### ISSUE THREAD

**Issue by buckett** [duckdb/duckdb#962]
On version 0.21 when attempting to import a CSV as specified in the documentation on https://duckdb.org/docs/data/csv I tried:

    sqlite> COPY request FROM '/Volumes/Space/dataFiles/requests/999-requests-00000-b16671eb.gz' ( FORMAT CSV_AUTO );
    Error: Catalog: Copy Function with name csv_auto does not exist!

So instead I used `INSERT INTO`:

    INSERT INTO request SELECT * FROM read_csv_auto('/Volumes/Space/dataFiles/requests/997-requests-00000-9a4ae116.gz');

**Comment by tdoehmen** [comment]
Sorry, the docu still needs to be updated. See https://github.com/cwida/duckdb/pull/832 for new commands, i.e.:

`COPY FROM (AUTO_DETECT TRUE)`

**Comment by tdoehmen** [comment]
PR for updated docs: https://github.com/cwida/duckdb-web/pull/4
