### ISSUE TITLE
Cannot convert timestrings greater than 24 hours to Interval

### ISSUE THREAD

**Issue by candux** [duckdb/duckdb#9631]
### What happens?

It's currently not possible to convert timestrings in the format HH:MM:SS to an interval if they are larger than 24 hours. I don't know if this is intentional but it's possible in Postgresql and would be very useful to parse Dates in GTFS which can be bigger than 24 hours.

### To Reproduce

```
D SELECT ('35:10:00'::interval);
Error: Conversion Error: Could not convert string '35:10:00' to INTERVAL
```

### OS:

Linux

### DuckDB Version:

0.9.1

### DuckDB Client:

Shell

### Full Name:

David Weber

### Affiliation:

geOps

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
There is a closely related issue here that `'24:00:00'::TIME` should be valid as well (it is in PG).
