### ISSUE TITLE
DISTINCT clause on a column still returns duplicate(s)

### ISSUE THREAD

**Issue by jbaranski** [duckdb/duckdb#9641]
### What happens?

`DISTINCT` clause on a column still returns duplicate(s)

### To Reproduce

Download and connect this database: https://github.com/jbaranski/duck-db-bug-report/blob/main/data2.db

Run this query, which returns 2 results:
```
SELECT player.id, player.name, player.height
FROM players 
WHERE player.nationality = 'USA'
AND player.id = 51144
ORDER BY player.age;
```

Run this query with a `DISTINCT` clause on `player.id`, which does not return duplicates when `player.height` not part of the `SELECT` statement:
```
SELECT DISTINCT(player.id), player.name
FROM players 
WHERE player.nationality = 'USA'
AND player.id = 51144
ORDER BY player.age;
```

Run this query with a `DISTINCT` clause on `player.id`, which **DOES** return duplicates when `player.height` part of the `SELECT` statement, **which is a bug?**:
```
SELECT DISTINCT(player.id), player.name, player.height
FROM players 
WHERE player.nationality = 'USA'
AND player.id = 51144
ORDER BY player.age;
```

### OS:

MacOS - Ventura 13.4.1

### DuckDB Version:

0.9.1

### DuckDB Client:

Java/DBeaver

### Full Name:

Jeff Baranski

### Affiliation:

Hobby Project / No Affiliation

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
cannot run
```
root@localhost:/data/data/com.termux/files/home/091# ./duckdb /storage/emulated/0/Download/Browser/data2.db
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D SELECT player.id, player.name, player.height
> FROM "data".main.players
> WHERE player.nationality = 'USA'
> AND player.id = 51144
> ORDER BY player.age;
Error: Binder Error: Catalog "data" does not exist!
```

**Comment by save-my-heart** [comment]
No, it is not a bug.
Actually, this query
 ```sql
SELECT DISTINCT(player.id), player.name, player.height
FROM "data".main.players 
WHERE player.nationality = 'USA'
AND player.id = 51144
ORDER BY player.age
```
is same as
```sql
SELECT player.id, player.name, player.height
FROM "data".main.players 
WHERE player.nationality = 'USA'
AND player.id = 51144
GROUP BY player, player.id, player.name, player.height
ORDER BY player.age
```

**Comment by l1t1** [comment]
delete "data".  it can run, and no problem. 
distinct is a clause, not a function, so it effects all selected columns, not the one in the (  )
```
D SELECT player.id, player.name, player.height
> FROM main.players
> WHERE player.nationality = 'USA'
> AND player.id = 51144
> ORDER BY player.age;
┌───────┬─────────────┬─────────┐
│  id   │    name     │ height  │
│ int64 │   varchar   │ varchar │
├───────┼─────────────┼─────────┤
│ 51144 │ B. Reynolds │ 191 cm  │
│ 51144 │ B. Reynolds │ 185 cm  │
└───────┴─────────────┴─────────┘
D SELECT DISTINCT(player.id), player.name
> FROM main.players
> WHERE player.nationality = 'USA'
> AND player.id = 51144
> ORDER BY player.age;
┌───────┬─────────────┐
│  id   │    name     │
│ int64 │   varchar   │
├───────┼─────────────┤
│ 51144 │ B. Reynolds │
└───────┴─────────────┘
D SELECT DISTINCT(player.id), player.name, player.height
> FROM main.players
> WHERE player.nationality = 'USA'
> AND player.id = 51144
> ORDER BY player.age;
┌───────┬─────────────┬─────────┐
│  id   │    name     │ height  │
│ int64 │   varchar   │ varchar │
├───────┼─────────────┼─────────┤
│ 51144 │ B. Reynolds │ 191 cm  │
│ 51144 │ B. Reynolds │ 185 cm  │
└───────┴─────────────┴─────────┘
```

**Comment by szarnyasg** [comment]
@jbaranski in the `SELECT DISTINCT(player.id), player.name, ...` statement, surrounding the attribute `player.id` in parentheses does not make a difference. Are you maybe looking for the [`DISTINCT ON()`](https://duckdb.org/docs/sql/query_syntax/select#distinct-on-clause)?
