### ISSUE TITLE
wrong behaviour of CASE statements with NULL field values

### ISSUE THREAD

**Issue by michael-behrendt** [duckdb/duckdb#9657]
### What happens?

Duckdb mixes true and false branch for CASE statements, when a NULL field value is checked.

Example below expects (NULL,1) as result set and not (NULL,2).

### To Reproduce

```
duckdb -nullvalue NULL
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D SELECT NULL AS 'a', CASE WHEN 'a' IS NULL THEN '1' ELSE '2' END AS 'b';
┌───────┬─────────┐
│   a   │    b    │
│ int32 │ varchar │
├───────┼─────────┤
│  NULL │ 2       │
└───────┴─────────┘
D SELECT NULL AS 'a', CASE WHEN 'a' IS NOT NULL THEN '1' ELSE '2' END AS 'b';
┌───────┬─────────┐
│   a   │    b    │
│ int32 │ varchar │
├───────┼─────────┤
│  NULL │ 1       │
└───────┴─────────┘
```

### OS:

aarch64

### DuckDB Version:

v0.9.1 401c8061c6

### DuckDB Client:

v0.9.1 401c8061c6

### Full Name:

Michael Behrendt

### Affiliation:

T-Systems GmbH

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@michael-behrendt thanks for opening this issue.
I think the problem stems from your queries using single quotes for denoting the column name `a` instead of [double quotes](https://duckdb.org/docs/sql/data_types/text.html#double-quote-characters). So it's interpreted as a string, which is `NOT NULL`.

**Comment by michael-behrendt** [comment]
> @michael-behrendt thanks for opening this issue. I think the problem stems from your queries using single quotes for denoting the column name `a` instead of [double quotes](https://duckdb.org/docs/sql/data_types/text.html#double-quote-characters). So it's interpreted as a string, which is `NOT NULL`.

Good point! Thanks a lot for the hint!

```
D SELECT NULL AS 'a', CASE WHEN a IS NULL THEN '1' ELSE '2' END AS 'b', CASE WHEN "a" IS NULL THEN '1' ELSE '2' END AS 'c', CASE WHEN 'a' IS NULL THEN '1' ELSE '2' END AS 'd';
┌───────┬─────────┬─────────┬─────────┐
│   a   │    b    │    c    │    d    │
│ int32 │ varchar │ varchar │ varchar │
├───────┼─────────┼─────────┼─────────┤
│  NULL │ 1       │ 1       │ 2       │
└───────┴─────────┴─────────┴─────────┘
```

**Comment by michael-behrendt** [comment]
Could be closed.
