### ISSUE TITLE
Unable to alias subquery in expression

### ISSUE THREAD

**Issue by ergodiclife** [duckdb/duckdb#9663]
### What happens?

Unable to alias a subquery within a `SELECT` query.

### To Reproduce

```{sql}
-- Create table to store dummy data
CREATE OR REPLACE TABLE dummy (
    id INT,
    val DOUBLE,
    month_end DATE
);

-- Set seed for reproducibility
SELECT
    setseed(0.5);

-- Generate dummy data
WITH RECURSIVE sim_data AS (
    SELECT 
        1 AS id,
        random() AS val,
        last_day(DATE '2023-01-01') AS month_end
    UNION ALL
    SELECT 
        id + 1,
        random(),
        last_day(month_end + INTERVAL 1 MONTH)
    FROM 
        sim_data 
    WHERE 
        month_end < DATE '2023-12-31'
)

-- Populate table with generated dummy data
INSERT INTO dummy
SELECT
    id,
    round(val, 4),
    month_end
FROM
    sim_data;

-- Run query attempting to alias a subquery
SELECT
    quarter(month_end) quarter,
    SUM(val) quarter_sum,
    (SELECT SUM(val) OVER () FROM dummy) total_sum,
    quarter_sum / total_sum * 100 quarter_perc
FROM
    dummy
GROUP BY 
    1;
 ```

Running the above should throw:
```
Error: Binder Error: Alias "total_sum" referenced in a SELECT clause - but the expression has a subquery. This is not yet supported.
```

### OS:

Windows 10 x64

### DuckDB Version:

v0.9.2-dev385

### DuckDB Client:

Both CLI and Python

### Full Name:

Jim Blake

### Affiliation:

N/A

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @ergodiclife, this is expected behaviour. Fortunately, it is easy to work around by pushing the subquery to the `FROM` clause, e.g.:

```sql
SELECT
    quarter,
    quarter_sum,
    total_sum,
    quarter_sum / total_sum * 100 quarter_perc
FROM (
    SELECT
        quarter(month_end) quarter,
        SUM(val) quarter_sum,
        (SELECT SUM(val) OVER () FROM dummy) AS total_sum,
    FROM
        dummy
    GROUP BY 
        1
    )
;
```

**Comment by ergodiclife** [comment]
Thanks for your help Gabor - that makes sense.

**Comment by georgewfraser** [comment]
It would be really nice to resolve this limitation. Subqueries are extremely convenient, especially in combination with macros, because they force a single join. A simple example:

```sql
create macro old_rate(account_plan, account_quantity) as (
  select <pricing formula>
  from old_pricing_table
  where account_plan = plan
);

create macro new_rate(account_plan, account_quantity) as (
  select <pricing formula>
  from new_pricing_table
  where account_plan = plan
);

select 
  account_plan,
  account_quantity,
  old_rate(account_plan, account_quantity) as old_rate,
  new_rate(account_plan, account_quantity) as new_rate,
  account_quantity * old_rate as old_price,
  account_quantity * new_rate as new_price
from accounts
```

This query is easier to get right than the version that uses joins. For example, if one of the pricing tables is missing a plan, the result set will have a bunch of nulls, instead of the account getting dropped from the result set.

**Comment by polvoazul** [comment]
Is there a reason for this to be closed? Do you plan on never implementing it? Is there a reason why, seems like an unexpected limitation to me as a user @szarnyasg 

`...referenced in a SELECT clause - but the expression has a subquery. This is not yet supported.`

Even the error message suggests that it will eventually be supported
