### ISSUE TITLE
TPCH Query 2 timeout but only when using 64 cores

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#9664]
### What happens?

TPCH_SF100 benchmarks works fine using 8,16,32 cores but get stuck using 64, I understand it is probably a join order issue, but why it is triggered only with 64 cores ?

### To Reproduce

just running typical TPCH benchmarks using Parquet generated by Spark,  notice row group is very large around 12 Millions,  it works fine with Smaller row group

### OS:

Fabric Notebook (Linux)

### DuckDB Version:

v0.9.2-dev385

### DuckDB Client:

Python

### Full Name:

mimoune djouallah

### Affiliation:

personal

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi Mimoune,

Thanks for reporting this.

> just running typical TPCH benchmarks using Parquet generated by Spark, notice row group is very large around 12 Millions, it works fine with Smaller row group

Could you please point me to a repository with this code, a script to generate this, or an openly available data set?

**Comment by djouallah** [comment]
i will try to get a reproducible example
