### ISSUE TITLE
[MySql Scanner] Error in attack

### ISSUE THREAD

**Issue by Cricle** [duckdb/duckdb#9681]
### What happens?

```
D ATTACH 'host=192.168.1.101 user=root port=3306 database=test-2' AS mysqlscanner (TYPE mysql_scanner);
Error: HTTP Error: Failed to download extension "mysql_scanner" at URL "http://extensions.duckdb.org/v0.9.2/windows_amd64/mysql_scanner.duckdb_extension.gz"
Extension "mysql_scanner" is an existing extension.
```

![image](https://github.com/duckdb/duckdb/assets/26201412/ad412074-22f6-4605-bb3b-31a4200a089f)

### To Reproduce

```
ATTACH 'host=192.168.1.101 user=root port=3306 database=test-2' AS mysqlscanner (TYPE mysql_scanner);
```

### OS:

win x64

### DuckDB Version:

0.9.2

### DuckDB Client:

cli

### Full Name:

HCricle

### Affiliation:

No

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
The MySQL extension is not yet available precompiled, if you wish to try it out, instructions for compiling it yourself are available here: https://github.com/duckdb/duckdb_mysql#building--loading-the-extension
