### ISSUE TITLE
Surprising behavior of `UNNEST` when called inside `row`

### ISSUE THREAD

**Issue by CreRecombinase** [duckdb/duckdb#9694]
### What happens?

I would think that `SELECT row(UNNEST([1,2,3]))` would give the same result as `SELECT row(1,2,3)`, but that's not the case. `SELECT row(UNNEST([1,2,3]))` yields:
```
 ────────────────────────────────────────────┐
│ main.row(unnest(main.list_value(1, 2, 3))) │
│              struct( integer)              │
├────────────────────────────────────────────┤
│ {'': 1}                                    │
│ {'': 2}                                    │
│ {'': 3}                                    │
└────────────────────────────────────────────┘
```

### To Reproduce

`SELECT row(UNNEST([1,2,3]));`

### OS:

OSx aarch64

### DuckDB Version:

v0.9.0 0d84ccf478

### DuckDB Client:

CLI

### Full Name:

Nick Knoblauch

### Affiliation:

BioMarin Pharmaceutical

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Have a look at the dev version of the docs on the row method, it produces an unnamed struct since 0.9.0

This is also described in the 0.9.0 blogpost

**Comment by CreRecombinase** [comment]
The fact that the struct is unnamed is not surprising, what's surprising is that `SELECT row(UNNEST([1,2,3]))` returns 3 single element structs rather than a single 3 element struct.

**Comment by l1t1** [comment]
I aslo did some test
```
D select row(1,2,3);
┌──────────────────────────────────────┐
│          main.row(1, 2, 3)           │
│ struct( integer,  integer,  integer) │
├──────────────────────────────────────┤
│ {'': 1, '': 2, '': 3}                │
└──────────────────────────────────────┘
D select row([1,2,3]);
┌────────────────────────────────────┐
│ main.row(main.list_value(1, 2, 3)) │
│         struct( integer[])         │
├────────────────────────────────────┤
│ {'': [1, 2, 3]}                    │
└────────────────────────────────────┘

D select unnest(row([1,2,3]));
Error: Binder Error: Key name for struct_extract needs to be neither NULL nor empty
D select row(values(1),(2),(3));
Error: Parser Error: syntax error at or near "("
LINE 1: select row(values(1),(2),(3));
                         ^
D select row((values(1),(2),(3)));
┌────────────────────────────────────────────────────────────────┐
│ main.row((SELECT * FROM (VALUES (1), (2), (3)) AS valueslist)) │
│                        struct( integer)                        │
├────────────────────────────────────────────────────────────────┤
│ {'': 1}                                                        │
└────────────────────────────────────────────────────────────────┘
```

**Comment by szarnyasg** [comment]
Hi @CreRecombinase
Thanks for opening this issue.

> The fact that the struct is unnamed is not surprising, what's surprising is that `SELECT row(UNNEST([1,2,3]))` returns 3 single element structs rather than a single 3 element struct.

I don't think this behaviour is surprising. Without `row`, `unnest` produces the following result:

```sql
SELECT unnest([1,2,3]) AS x;
```
```
┌───────┐
│   x   │
│ int32 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
```

**Comment by CreRecombinase** [comment]
The problem is that the way this works now violates the [principle of compositionality](https://en.wikipedia.org/wiki/Principle_of_compositionality). In general if I see an expression of the form `foo(bar(x))` the influence of `bar` on the 'shape' & type of the overall expression should only come from how it changes the input to `foo`. Put another way, if the result of `bar(x)` is some value `y`, `foo(y)` should be equivalent to `foo(bar(x))`.

**Comment by Mytherin** [comment]
Given that `UNNEST([1, 2, 3])` produces 3 rows with values `1`, `2`, `3`, it makes logical sense that `row(UNNEST([1, 2, 3]))` produces three unnamed structs containing the values `1`, `2`, `3` respectively. This also matches the behavior of Postgres:

```sql
postgres=# select row(unnest(array[1,2,3]));
 row 
-----
 (1)
 (2)
 (3)
```

As for why `UNNEST([1, 2, 3])` produces three rows - `UNNEST` is defined as a "special" function that expands lists into multiple rows. While that is somewhat strange in `SELECT` - it is similar to how aggregates work and can change the cardinality of a result set.

All-in-all this is expected behavior.
