### ISSUE TITLE
Date-type named parameters error in range functions (Python connector) 

### ISSUE THREAD

**Issue by dunnkevin** [duckdb/duckdb#9697]
### What happens?

Using a named parameter in a range function throws a ParserException for date types:

duckdb.duckdb.ParserException: Parser Error: syntax error at or near "$"

This does not appear to happen for integer types, and dates work outside of range functions (e.g., `select $param`)

### To Reproduce

This can be minimally reproduced by trying to use a variable when generating a date range:

```
import duckdb


query = """
select * from range(date $start_date, current_date, interval 1 day)
"""

with duckdb.connect(database=':memory:') as conn:
    duckdb_df = conn.execute(query, {'start_date': '2023-11-01'}).df()
print(duckdb_df)
```

Which outputs:

```
Traceback (most recent call last):
  File "/Users/kevin/duckdb_testing/test.py", line 9, in <module>
    duckdb_df = conn.execute(query, {'start_date': '2023-11-01'}).df()
  File "/Users/kevin/duckdb_testing/test.py", line 9, in <module>
    duckdb_df = conn.execute(query, {'start_date': '2023-11-01'}).df()
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "$"
LINE 2: select * from range(date $start_date, current_date, interval 1 ...
```

### OS:

macOS 13.6.1 (22G313) (M1)

### DuckDB Version:

0.8.1, 0.9.2, 0.9.3.dev6

### DuckDB Client:

Python

### Full Name:

Kevin Dunn

### Affiliation:

Hex Technologies

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @dunnkevin the issue is unrelated to range functions. Running the following simple `select` statement will also fail:

```py
import duckdb

print(duckdb.execute("select date $start_date", {'start_date': '2023-11-01'}).df())
```
```
Traceback (most recent call last):
    ...
    print(duckdb.execute("select date $start_date as d", {'start_date': '2023-11-01'}).df())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "$"
LINE 1: select date $start_date as d
```

The workaround is to create the parameter as a Python `date` and pass that to DuckDB:
```py
import duckdb
from datetime import date

print(duckdb.execute("select $start_date" as d, {'start_date': date(2023, 11, 1)}).df())
```
```
           d
0 2023-11-01
```

**Comment by dunnkevin** [comment]
> Hi @dunnkevin the issue is unrelated to range functions. Running the following simple `select` statement will also fail:

Thanks @szarnyasg - not sure how I missed that 🤦 - Appreciate the clarification and the workaround.
