### ISSUE TITLE
'INSTALL sqlite;' fails: HTTP Error: Failed to download extension "sqlite_scanner" at URL

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#9699]
### What happens?

```
D INSTALL sqlite;
Error: HTTP Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org//linux_amd64_gcc4/sqlite_scanner.duckdb_extension.gz"
Extension "sqlite_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
D
```

'sqlite' isn't under the 'extensions' folder.

### To Reproduce

see above

### OS:

FreeBSD 13.2

### DuckDB Version:

0.9.2

### DuckDB Client:

n/a

### Full Name:

Yuri Victorovich

### Affiliation:

n/a

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Can you please confirm which architecture you're on?

The file http://extensions.duckdb.org/v0.9.2/linux_amd64_gcc4/sqlite_scanner.duckdb_extension.gz does exist

**Comment by yurivict** [comment]
I am on FreeBSD 13.2 amd64.

**Comment by Mause** [comment]
Can you double check the error message then? The file does exist, as I stated. The message you gave is missing some information

**Comment by yurivict** [comment]
It tries a different URL: http://extensions.duckdb.org//linux_amd64_gcc4/sqlite_scanner.duckdb_extension.gz
Please note the "//" in it.

**Comment by Mause** [comment]
Which DuckDB client are you using? You didn't include that in your issue.

Is this something you built yourself?

And what is the output from:

```sql
pragma version;
pragma platform;
```

**Comment by yurivict** [comment]
I use the ```duckdb``` executable that is installed by the FreeBSD port.

```
D pragma version;
┌─────────────────┬───────────┐
│ library_version │ source_id │
│     varchar     │  varchar  │
├─────────────────┼───────────┤
│ v0.0.1-dev0     │           │
└─────────────────┴───────────┘
D pragma platform;
┌──────────────────┐
│     platform     │
│     varchar      │
├──────────────────┤
│ linux_amd64_gcc4 │
└──────────────────┘
D 
```


Both values are incorrect. The version value should be 0.9.2. The platform value should be freebsd_amd64_clang.

**Comment by Mause** [comment]
Yep, looks like the issue is upstream with the FreeBSD port not pulling the git tags. Luckily enough, you seem to be a FreeBSD committer 😉

**Comment by yurivict** [comment]
@Mause 
But why does it think that this is linux and why does it think that gcc4 is used?

**Comment by Mause** [comment]
Linux is the default OS (and for BSD this is probably fine). gcc4 is the default abi on linux, unless otherwise specified.

See https://github.com/duckdb/duckdb/blob/c92602b864a09717b56843ae0811d85914509a9a/src/function/table/version/pragma_version.cpp#L60-L103 for more information about this inference

**Comment by yurivict** [comment]
Then the "LOAD" operator attempts to load binaries for Linux on non-Linux systems where such binaries can't work.

I've creates a separate issue for this: https://github.com/duckdb/duckdb/issues/9700

**Comment by Mause** [comment]
Worth noting the following:

> We can only support the following platforms: Windows 10+ on x86_64, Mac OS latest, Linux x86_64 & aarch64, mainstream distros under support by distributor (Ubuntu LTS is a safe bet).

From https://duckdblabs.com/news/2023/10/02/support-policy.html
