### ISSUE TITLE
'pragma platform;' assumes that OS is linux on non-linux systems, and assumes gcc4 where clang is actually used

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#9700]
### What happens?

On FreeBSD 13.2 amd64 that uses clang-16 wrong platform is printed:
```
D pragma platform;
┌──────────────────┐
│     platform     │
│     varchar      │
├──────────────────┤
│ linux_amd64_gcc4 │
└──────────────────┘
D
```

### To Reproduce

see above

### OS:

FreeBSD 13.2

### DuckDB Version:

0.9.2

### DuckDB Client:

duckdb executable

### Full Name:

Yuri Victorovich

### Affiliation:

n/a

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by yurivict** [comment]
Based on the false "linux" system identifier the "LOAD" operator attempts to load binaries for Linux on non-Linux systems where such binaries can't work.

**Comment by Mause** [comment]
Worth noting the following:

> We can only support the following platforms: Windows 10+ on x86_64, Mac OS latest, Linux x86_64 & aarch64, mainstream distros under support by distributor (Ubuntu LTS is a safe bet).

From https://duckdblabs.com/news/2023/10/02/support-policy.html

Copied from https://github.com/duckdb/duckdb/issues/9699#issuecomment-1813819213

**Comment by carlopi** [comment]
Also for context: platform is tied to the extension ABI that is compatible with a given build of DuckDB.

The actual string is just a handle used to decide which extension to load from remote repositories, to make sure they have compatible settings, and it's not meant to be descriptive. This might need more explicit documentation.

Note that not all platform combinations are currently distributed by the official https://extensions.duckdb.org repository, and more combinations can and will be added over time.

You can check the code here: https://github.com/duckdb/duckdb/blob/main/src/function/table/version/pragma_version.cpp#L60C23-L60C23.

There is an in-flight [PR to add a DUCKDB_DISTRIBUTION](https://github.com/duckdb/duckdb/pull/9634) compile time define that can be overridden to allow some form of tracing back from how a given program has been compiled (idea is for this to be useful in scoping issues), contributions there are welcome.

**Comment by carlopi** [comment]
Also, in the linked issue: https://github.com/duckdb/duckdb/issues/9699 there is already plenty of context from @Mause.

**Comment by szarnyasg** [comment]
@yurivict this should indeed be fixed. I'm happy to take a look but I could not yet build DuckDB on FreeBSD, I get:

```bash
make: "/usr/home/ec2-user/duckdb/Makefile" line 8: Need an operator
```
Could you please share build instructions?

Of course, a PR fixing this issue is also very welcome.

**Comment by szarnyasg** [comment]
Okay, I figured it out. Use FreeBSD 14+ and:

```bash
git clone https://github.com/freebsd/freebsd-ports`
cd freebsd-ports/databases/duckdb
make
```
