### ISSUE TITLE
[security problem] Unsecured extension file downloads can be easily compromised through man-in-the-middle attacks

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#9709]
### What happens?

The command "LOAD {extension};" downloads the file from the URL like this: http://extensions.duckdb.org/v0.9.2/linux_amd64_gcc4/sqlite_scanner.duckdb_{extension}.gz

This file contains the gzipped ELF binary of the extension.

Malicious third parties who might control the network or the DNS server can substitute this gzipped file with a malicious file which may compromise the system of the client.

The user data can be stolen or deleted.

**The secure way of downloading extension files:**
DuckDB should maintain the signed database of all available extension files available for download, including their cryptographic fingerprints.
Such database should be signed with the DuckDB private key, and it should be made available through a dedicated URL along with its signature.
DuckDB client applications should contain the DuckDB public key. DuckDB clients should first download the extension database. Then, every time when the extension file is downloaded, its cryptographic fingerprint should be verified. In case if there is a cryptographic signature mismatch the downloaded the downloaded file should be discarded, and the user should be notified.

Simple unsecured downloads, like DuckDB is currently doing, can not be secure and have to be fixed.

### To Reproduce

n/a

### OS:

all

### DuckDB Version:

all

### DuckDB Client:

all

### Full Name:

Yuri Victorovich

### Affiliation:

n/a

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Proper channel to report security issues is https://github.com/duckdb/duckdb/security.

Note that DuckDB does include it's public keys as part of the binary and checks (and reports in care of failure) on every LOAD that the files are signed.

**Comment by carlopi** [comment]
I have closed the issue since it's not the proper place where to discuss this.

We will review the raised issue thoroughly, and we should make more explicit what the channel and policies are to present such problems.

Thanks

**Comment by hannes** [comment]
Just to reiterate, DuckDB extensions contain a RSA signature at the end. The DuckDB binary contains a list of public keys that are an allowed to sign extensions. At load time, this is checked. It is possible to disable the check through configuration. @szarnyasg , we should probably document this somewhere.

**Comment by szarnyasg** [comment]
This is explained in the documentation:

> Extensions are signed with a cryptographic key, which also simplifies distribution (this is why they are served over HTTP and not HTTPS). By default, DuckDB uses its built-in public keys to verify the integrity of extension before loading them. All extensions provided by the DuckDB core team are signed.
