### ISSUE TITLE
Cannot alter entry on valid(?) syntax

### ISSUE THREAD

**Issue by igitur** [duckdb/duckdb#9713]
### What happens?

My apologies if this isn't a bug, but I'm fairly sure that this SQL syntax should be valid.

The SQL statements mentioned below yields the error:
```
SQL Error: Dependency Error: Cannot alter entry "articles" because there are entries that depend on it.
```

### To Reproduce

This is the typical pattern a schema generation script would follow, dropping entities if they exist and then recreating. Parent entities are handled first.

Removing the INDEX statements solves the error, but the index is required.

```sql
DROP TABLE IF EXISTS articles CASCADE;
CREATE TABLE articles (
    id              INTEGER PRIMARY KEY,
    uuid uuid       NOT NULL UNIQUE,
    title           TEXT NOT NULL UNIQUE,
    body            TEXT NOT NULL,
);

DROP INDEX IF EXISTS idx_articles_title; CREATE UNIQUE INDEX idx_articles_title ON articles(LOWER(title));

DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments (
    article_id         INTEGER REFERENCES articles(id) ,
    comment            TEXT NOT NULL,
);
```

### OS:

x64

### DuckDB Version:

64

### DuckDB Client:

DuckDB CLI

### Full Name:

Francois Botha

### Affiliation:

Personal capacity - trying to add support for an embedded database to listmonk

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks, we're aware of the issue

The foreign key creates an Alter on the referenced table, the Alter fails because the entry has dependencies
We are working to relieve this constraint

**Comment by igitur** [comment]
@Tishj 
Thanks, is there perhaps an issue that I can track? Then I'll close this one as a dup.

And do you perhaps have a workaround? Admittedly I haven't tried reordering the statements yet.

**Comment by Tishj** [comment]
Not exactly, we have an internal issue, and this public issue is related to it
<https://github.com/duckdb/duckdb/issues/9137>

**Comment by jarib** [comment]
> Not exactly, we have an internal issue, and this public issue is related to it #9137

#9137 issue is now closed, but the problem mentioned here remains (using v0.10.2 1601d94f94).
