### ISSUE TITLE
Custom Aggregate Functions fail to produce the same result as the built-in count function

### ISSUE THREAD

**Issue by hkulyc** [duckdb/duckdb#9719]
### What happens?

I tried to implement my own count aggregate. It works well for simple queries, generating the same result as the built-in count. However, all 0s in count's output becomes NULL if used in subqueries, when replacing count with this custom aggregation. Note that I have already set the `SPECIAL_HANDLING` flag when defining the custom aggregate.

### To Reproduce

This is the C++ code for the custom aggregate.
```
struct AggState13
{
	bool isInitialized;
	int32_t count;
};

struct CustomAggOperation13
{

	template <class STATE>
	static void Initialize(STATE &state)
	{
		state.isInitialized = false;
		state.count = 0;
	}

	template <class INPUT_TYPE, class STATE, class OP>
	static void ConstantOperation(STATE &state, const INPUT_TYPE &input, AggregateUnaryInput &unary_input, idx_t count)
	{
		for (idx_t i = 0; i < count; i++)
		{
			Operation<INPUT_TYPE, STATE, OP>(state, input, unary_input);
		}
	}

	template <class INPUT_TYPE, class STATE, class OP>
	static void Operation(STATE &state, const INPUT_TYPE &input, AggregateUnaryInput &unary_input)
	{
		if(state.isInitialized == false){
			state.isInitialized = true;
		}
		state.count++;
	}

	template <class STATE, class OP>
	static void Combine(const STATE &source, STATE &target, AggregateInputData &) {
		if (source.isInitialized == false) {
			return;
		}
		else{
			target.isInitialized = true;
			target.count += source.count;
		}
	}

	template <class TARGET_TYPE, class STATE>
	static void Finalize(STATE &state, TARGET_TYPE &target, AggregateFinalizeData &finalize_data)
	{
		target = state.count;
	}

	static bool IgnoreNull()
	{
		return false; // I also tested true, not working
	}
};

auto ordersbycustomeraggregate = AggregateFunction::UnaryAggregate<AggState13, int32_t, int32_t, CustomAggOperation13>(LogicalType::INTEGER, LogicalType::INTEGER, FunctionNullHandling::SPECIAL_HANDLING);
ordersbycustomeraggregate.name = "ordersbycustomeraggregate";
ExtensionUtil::RegisterFunction(instance, ordersbycustomeraggregate);
```
After registering this custom aggregate, this is the sql I run. (The dataset I use is TPCH.)
```
// using our aggregate
CREATE MACRO OrdersByCustomerWithCustomAgg(cust_key) AS 
(SELECT "val_1" AS "result" FROM 
    LATERAL 
    (SELECT
        (SELECT ordersbycustomeraggregate("orders"."o_orderkey") AS "count" FROM 
            orders AS "orders" WHERE "orders"."o_custkey" = "cust_key") AS "val_1") AS "let0"("val_1"));

// using count
CREATE MACRO OrdersByCustomerWithCount(cust_key) AS 
(SELECT "val_1" AS "result" FROM 
    LATERAL 
    (SELECT
        (SELECT count("orders"."o_orderkey") AS "count" FROM 
            orders AS "orders" WHERE "orders"."o_custkey" = "cust_key") AS "val_1") AS "let0"("val_1"));

// query
SELECT c_custkey, OrdersByCustomerWithCustomAgg(c_custkey) FROM customer order by *;
SELECT c_custkey, OrdersByCustomerWithCount(c_custkey) FROM customer order by *;
```
Theoretically, the two queries should give the same result, but I am not sure why it is not.

### OS:

MacOS, arm

### DuckDB Version:

development

### DuckDB Client:

C++

### Full Name:

Yuchen Liu

### Affiliation:

Carnegie Mellon University

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! It is not clear to me what exactly the issue is here. I don't believe we have any special code related to `COUNT` in our subquery handling. Could you be more specific on what the expected outcome is and what the actual outcome is?

You have re-implemented `COUNT` and say that the result is different from the built-in count function - but is that also true if you use the exact same code as our internal `CountFunction` instead of re-implementing it (and perhaps not setting up flags correctly)?
