### ISSUE TITLE
Internal binding error when using lateral query in finding greatest n row per group

### ISSUE THREAD

**Issue by euiko** [duckdb/duckdb#9720]
### What happens?

I'm using lateral query to find greatest n row per group in DuckDB, and since v0.9.0 it is now produce error :
```
Error: INTERNAL Error: Failed to bind column reference "limit_rownum" [34.0] (bindings: [1.0])
```

Using the same query in v0.8.1 and PostgreSQL it produce the correct result.

When analyzing query in v0.8.1, it produces attached [analyze.txt](https://github.com/duckdb/duckdb/files/13400980/analyze.txt) that shows it uses `row_number` window function and `limit_rownum` as the column name, which is then used in the next filter pipeline.

The workaround is using the `row_number` windowing function directly.

### To Reproduce

This query is trying to find two greatest s2 per s1.

```sql
with s1 as (
    select s1
    from generate_series(1, 10) s1(s1)
),
s2 as (
    select s1,
        s2,
        random() as value
    from s1,
        generate_series(1, 10) s2(s2)
)
select l2.*
from s1,
    lateral(
        select s2.*
        from s2
        where s2.s1 = s1.s1
        order by s2 desc
        limit 2
    ) l2
order by l2.s1, l2.s2 desc;
```

Usually I find this query helpful when I have time-series data and wanna find last two data for each certain key/group. 

### OS:

Linux x64

### DuckDB Version:

v0.9.3-dev42

### DuckDB Client:

CLI

### Full Name:

Candra Kharista

### Affiliation:

WJA

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! This issue seems to be fixed in v0.10.0:

```sql
D with s1 as (
      select s1
      from generate_series(1, 10) s1(s1)
  ),
  s2 as (
      select s1,
          s2,
          random() as value
      from s1,
          generate_series(1, 10) s2(s2)
  )
  select l2.*
  from s1,
      lateral(
          select s2.*
          from s2
          where s2.s1 = s1.s1
          order by s2 desc
          limit 2
      ) l2
  order by l2.s1, l2.s2 desc;
┌───────┬───────┬──────────────────────┐
│  s1   │  s2   │        value         │
│ int64 │ int64 │        double        │
├───────┼───────┼──────────────────────┤
│     1 │    10 │   0.4863620123360306 │
│     1 │     9 │  0.33940994064323604 │
│     2 │    10 │   0.9357704871799797 │
│     2 │     9 │ 0.018773534800857306 │
│     3 │    10 │   0.7058802298270166 │
│     3 │     9 │  0.28725521406158805 │
│     4 │    10 │   0.3434698679484427 │
│     4 │     9 │   0.5186691023409367 │
│     5 │    10 │  0.20281103067100048 │
│     5 │     9 │   0.6335595482960343 │
│     6 │    10 │  0.20051525859162211 │
│     6 │     9 │  0.33069120324216783 │
│     7 │    10 │  0.14456899417564273 │
│     7 │     9 │    0.530945488717407 │
│     8 │    10 │   0.5576984416693449 │
│     8 │     9 │   0.2739060688763857 │
│     9 │    10 │ 0.013432085048407316 │
│     9 │     9 │   0.5025253272615373 │
│    10 │    10 │   0.5542441674042493 │
│    10 │     9 │   0.8020419953390956 │
├───────┴───────┴──────────────────────┤
│ 20 rows                    3 columns │
└──────────────────────────────────────┘

```
