### ISSUE TITLE
Is the checkpoint size parameter a lie?

### ISSUE THREAD

**Issue by mattsta** [duckdb/duckdb#9721]
### What happens?

We're opening a DB in python like:

```python
db = duckdb.connect("newdb.db", config=dict(wal_autocheckpoint="12 GB"))
```

Normally, under sqlite at least, if you set a large wal checkpoint size and have `autocommit` disabled and never call `COMMIT`, then _all writes_ go into the WAL and only on commit (or process exit) does the WAL get reconciled into DB pages (which is then potentially a huge multi-GB update).

But when moving our sqlite processing to duckdb, everything is 10x to 100x slower writing because we're writing a million rows, but the WAL isn't growing to 5GB. It appears there's some autocommit feature we either don't see or can't access?

In sqlite, running logic like this only writes to the DB once:

```
db.begin()
db.executemany(query, rows)
db.commit()
```

But we're seeing duckdb write pages to the DB with multiple `executemany` calls wrapped in a single transaction (or other just `sql()` too) and the WAL isn't growing forever (what we want, because we're bulk importing transformed files in-memory).

The official docs seem to imply "never write into duckdb from python, only use native load-from-external-files mechanisms," but if the wal checkpoint pragma worked and if we can confirm `autocommit` isn't happening everywhere behind our backs, it should be fine?

If the advice of "never insert a million rows from python" is the one true way, that means we need to read source data files -> transform in memory -> write files in target format -> read files back using duckdb command logic -> ... and it's just a lot messier.

### To Reproduce

Logic is simple to reproduce and it shows the wal isn't even being written to:

```python
import duckdb
c = duckdb.connect("testme.db", config=dict(wal_autocheckpoint="12 GB"))
c.sql("CREATE TABLE loadtest (pk int, etc text)")
c.begin()

for i in range(300_000):
    c.executemany("INSERT INTO loadtest VALUES (?, ?)", [(j, j) for j in range(10_000)])
```

Under sqlite, running there will grow the WAL and it's very fast because it's just sequential appending. Under duckdb, it's slow and the WAL is never accessed but the DB file grows even with the large `wal_autocheckpoint` setting and _no commits_ (`executemany` does not autocommit if a transaction is open... or at least it shouldn't).

I couldn't find an easily discoverable explanation in the documentation about why the WAL isn't getting writes.

If you CTRL-C the `executemany` loop (from ipython), the data shows up inside the current transaction, but after we exit the session without a `COMMIT` the data is dropped from the database (but the WAL is not used for any of this, which is the entire point of the WAL in the first place?)

```
RuntimeError: Query interrupted

In [2]: c.sql("select * from loadtest")
Out[2]: 
┌──────────────┬─────────┐
│      pk      │   etc   │
│    int32     │ varchar │
├──────────────┼─────────┤
│            0 │ 0       │
│            1 │ 1       │
│            2 │ 2       │
│            3 │ 3       │
│            4 │ 4       │
│            5 │ 5       │
│            6 │ 6       │
│            7 │ 7       │
│            8 │ 8       │
│            9 │ 9       │
│            · │ ·       │
│            · │ ·       │
│            · │ ·       │
│         9990 │ 9990    │
│         9991 │ 9991    │
│         9992 │ 9992    │
│         9993 │ 9993    │
│         9994 │ 9994    │
│         9995 │ 9995    │
│         9996 │ 9996    │
│         9997 │ 9997    │
│         9998 │ 9998    │
│         9999 │ 9999    │
├──────────────┴─────────┤
│ ? rows       2 columns │
└────────────────────────┘
```

### OS:

Linux, macOS

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

Python, CLI, etc

### Full Name:

What why

### Affiliation:

Huh go away

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
https://berthub.eu/articles/posts/anonymous-help

And to answer your question, no
```c++
bool SingleFileStorageManager::AutomaticCheckpoint(idx_t estimated_wal_bytes) {
	auto log = GetWriteAheadLog();
	if (!log) {
		return false;
	}

	auto &config = DBConfig::Get(db);
	auto initial_size = log->GetWALSize();
	idx_t expected_wal_size = initial_size + estimated_wal_bytes;
	return expected_wal_size > config.options.checkpoint_wal_size;
}
```

`checkpoint_wal_size` is set by the `wal_autocheckpoint` setting

**Comment by mattsta** [comment]
> https://berthub.eu/articles/posts/anonymous-help

big disagree. if projects want to enforce a REAL NAME AND AFFILIATION POLICY then go run support on facebook forums instead? but if it helps, i'm currently unemployed and being evicted from my apartment because the corporate landlords are increasing the rent by $500 per month and i have no income to pay the increased rent. so what should I put as "Affiliation" there? "unwanted, untalented, homeless piece of garbage?"

and the setting is clearly set correctly because it's defined in the config. The problem appears to be the logic of how the inserts aren't actually using the WAL? Under this pattern, we would expect on the WAL to grow and nothing to be written to the database file at all because the transaction isn't committed.

**Comment by Tishj** [comment]
Sorry to hear that, it wasn't my intention to be hurtful, just explaining why we have this policy.
