### ISSUE TITLE
export database doesn't create sql files when exporting to s3 parquet

### ISSUE THREAD

**Issue by mgaunard** [duckdb/duckdb#9727]
### What happens?

when exporting a database as parquet to the filesystem, one obtains one parquet file per table, together with a schema.sql and a load.sql file.

when exporting a database as parquet to a s3 location, only the parquet files are written out, meaning that any subsequent import database fails.

### To Reproduce

```sql
CREATE TABLE test(i INTEGER, j INTEGER);
EXPORT DATABASE 's3://some_bucket/some_directory' (format PARQUET);
EXPORT DATABASE 'some_directory' (format PARQUET);
```

first export only contains `test.parquet`, second one also has `load.sql` and `schema.sql`.

### OS:

Linux

### DuckDB Version:

v0.9.3-dev42 958f189880

### DuckDB Client:

CLI

### Full Name:

Mathias Gaunard

### Affiliation:

Portofino Technologies

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
> first export only contains `test.parquet`

Locally or in the bucket?

**Comment by mgaunard** [comment]
In that example, "the first export", refers to the export to s3. It does write the parquet file to s3, but not the associated SQL files.
