### ISSUE TITLE
Pivot slower than polars when reading parquet - looks like it reads more bytes.

### ISSUE THREAD

**Issue by LeonBamRazor** [duckdb/duckdb#9729]
### What happens?

I run 2 scenarios, one with read and pivot with duckdb, and other that reads with duckdb and pivot with Polars.
The performance with duckdb + polars were much better than the one with only duckdb.
For profiling, I run nettop for the process and notice that there were more bytes_in for the only duckdb process.  

### To Reproduce

```python
import duckdb
import polars as pl
import datetime as dt
from polars.testing import assert_frame_equal


def pivot_duck(path: str) -> pl.DataFrame:
    query = f"""
    PIVOT (
            SELECT 
                vendor_name,
                list(total_amount ORDER BY pickup_datetime) as rides,
                month as month
            FROM read_parquet('{path}', hive_partitioning=true)
            WHERE vendor_name is not null
            GROUP BY 
                vendor_name, 
                month
        ) ON vendor_name USING first(rides) group by month 
    """
    return duckdb.sql(query).pl()


def pivot_duck_polars(path: str) -> pl.DataFrame:
    query = f"""
        SELECT 
            vendor_name,
            list(total_amount ORDER BY pickup_datetime) as rides,
            month as month
        FROM 
            read_parquet('{path}', hive_partitioning=true)
        WHERE 
            vendor_name is not null
        GROUP BY 
            vendor_name, 
            month
    """
    return duckdb.sql(query).pl().pivot(
        index="month",
        columns="vendor_name",
        values="rides",
    )


if __name__ == '__main__':
    path = "s3://voltrondata-labs-datasets/nyc-taxi-tiny/year=*/month=*/*.parquet"
    now = dt.datetime.now()
    df_duck = pivot_duck(path).sort("month")
    end = dt.datetime.now()
    print(f"duckdb: {end - now}")
    now = dt.datetime.now()
    df = pivot_duck_polars(path).sort("month")
    end = dt.datetime.now()
    print(f"duckdb_polars: {end - now}")

    assert_frame_equal(
        df_duck,
        df,
        check_column_order=False,
    )
```
for checking the bytes_in 
```
nettop -p <PROCESS_ID>
```
### OS:

iOS

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Leon Bam

### Affiliation:

razor

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Polars materializes everything, prior to the `PIVOT`, which results in a single scan of the data. In DuckDB, the data is read twice, once to determine the pivot keys and once to perform the actual pivot. You could use a [MATERIALIZED CTE](https://duckdb.org/docs/sql/query_syntax/with.html#materialized-ctes) to avoid the double read, which would be a fair comparison.
