### ISSUE TITLE
Can not find JDBC driver class when adding new connection on DBeaver in v0.9.2

### ISSUE THREAD

**Issue by jeffryang24** [duckdb/duckdb#9741]
### What happens?

Previously, I can update the JDBC driver and connect to the DB successfully without any issue on pre-0.9.2 version. Somehow, the JDBC driver class is missing in v0.9.2. Is it a regression or not?

## Reproduction Environment

DBeaver: 23.2.5.202311191730
DuckDB: 0.9.2
Client: Java JDBC Driver

## Step to Reproduce

1. Follow the [create new in-memory database connection](https://duckdb.org/docs/guides/sql_editors/dbeaver) guide for DBeaver.
2. Use the current latest JDBC driver version, which is at 0.9.2.
3. Test the database connection from DBeaver IDE.

## Expected Behavior

DBeaver should be able to connect the DB successfully using the JDBC driver v0.9.2.

## Actual Behavior

DBeaver failed to connect the DB with the following error message.

```
Can't create driver instance
  Error creating driver 'DuckDB' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.duckdb.DuckDBDriver'
  Error creating driver 'DuckDB' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.duckdb.DuckDBDriver'
    org.duckdb.DuckDBDriver
```

![empty_driver_class](https://github.com/duckdb/duckdb/assets/8284757/3b581c6f-889f-4364-9e11-4f7bd5108d17)

### OS:

Ubuntu 22.04.3

### DuckDB Version:

0.9.2

### DuckDB Client:

Java JDBC Driver

### Full Name:

Jeffry Angtoni

### Affiliation:

Personal Usage

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Given the error message:

> Most likely required jar files are missing.
> You should configure jars in driver settings.

Can you confirm you actually downloaded/installed the 0.9.2 jars? Click the Download/Update button in the driver manager screenshot you provided

**Comment by jeffryang24** [comment]
> Given the error message:
> 
> > Most likely required jar files are missing.
> > You should configure jars in driver settings.
> 
> Can you confirm you actually downloaded/installed the 0.9.2 jars? Click the Download/Update button in the driver manager screenshot you provided

Ok, I will provide the screenshot.

1. Currently on v0.9.1 after I reverted the driver setting to v0.9.1.
![v0.9.1](https://github.com/duckdb/duckdb/assets/8284757/729ff09e-c066-41c5-a031-a52d222623db)

2. Upgrade to v0.9.2
![upgrade](https://github.com/duckdb/duckdb/assets/8284757/0e4d1ce3-01c1-43e5-9432-dbc64d21c1c3)

3. Verify the JDBC driver already at v0.9.2, and the driver class dropdown is empty (can't find the driver class).

![v0.9.2](https://github.com/duckdb/duckdb/assets/8284757/a00ccc00-212a-4ca8-a8c0-4e5bc11aa32b)

4. Got error when testing connection because the driver class is unavailable.

![error](https://github.com/duckdb/duckdb/assets/8284757/8bfc7400-c495-464e-9026-f488cc4a45dc)

**Comment by jeffryang24** [comment]
Ok, I think this issue has been solved by forcing DBeaver to force download / overwrite existing driver and voila DBeaver can successfully resolve the jdbc driver name again. :tada: Probably, this issue is from DBeaver side, sorry for the false alarm. :bow: 

![force_download](https://github.com/duckdb/duckdb/assets/8284757/6eb4522c-a63f-4cd5-8be4-6ad9ecc22276)
![classname_found](https://github.com/duckdb/duckdb/assets/8284757/4cbdea40-0423-4079-bd00-7c0d9fd0a2b0)
![success](https://github.com/duckdb/duckdb/assets/8284757/67aa1dd8-7685-4ef3-9fbc-0631214a43ac)

**Comment by Mause** [comment]
@jeffryang24 thanks for reporting back! Perhaps the file was corrupted somehow?

**Comment by jeffryang24** [comment]
> @jeffryang24 thanks for reporting back! Perhaps the file was corrupted somehow?

Yeah, probably because of that, sorry for the false alarm :bow:
