### ISSUE TITLE
Getting Segmentation fault (core dumped) while loading Extension

### ISSUE THREAD

**Issue by amplifinn-admin** [duckdb/duckdb#9743]
### What happens?

Getting Segmentation fault (core dumped) while loading Extension

### To Reproduce

```
import duckdb

con = duckdb.connect(database=':memory:')
con.load_extension('excel')
```

### OS:

Linux Ubuntu 20.04 aarch64

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

Santosh Kumar

### Affiliation:

Exosite

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I can not reproduce this on a build on `main` with your reproduction.
Sounds like it's already fixed or there are additional details that are missing here to reproduce the issue.

**Comment by carlopi** [comment]
Can you share a few more details like:
* the result of `PRAGMA platform`
* the result of `FROM duckdb_exceptions()`
* what happens if you do `con.load_extension('aaarrgh')` (same behaviour of different)

**Comment by szarnyasg** [comment]
@carlopi - I spun up an aarch64 ubuntu instance:
```python
con.load_extension('aaarrgh')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.IOException: IO Error: Extension "/home/ubuntu/.duckdb/extensions/v0.9.2/linux_arm64_gcc4/aaarrgh.duckdb_extension" not found.

Candidate extensions: "arrow"
```

**Comment by Tishj** [comment]
> @carlopi - I spun up an aarch64 ubuntu instance:
> 
> ```python
> con.load_extension('aaarrgh')
> ```
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> duckdb.duckdb.IOException: IO Error: Extension "/home/ubuntu/.duckdb/extensions/v0.9.2/linux_arm64_gcc4/aaarrgh.duckdb_extension" not found.
> 
> Candidate extensions: "arrow"
> ```

`excel` is the name of the extension they're loading, not `aaargh`

**Comment by amplifinn-admin** [comment]
> @amplifinn-admin can you share the commands you used to build the `excel` extension for `linux_arm64_gcc4`?

I have downloaded manually excel.duckdb_extension.gz with this link: http://extensions.duckdb.org/v0.9.2/linux_arm64/excel.duckdb_extension.gz

import gzip
import shutil
import duckdb

with gzip.open('excel.duckdb_extension.gz','rb') as f_in:
   with open('excel.duckdb_extension', 'wb') as f_out:
     shutil.copyfileobj(f_in, f_out)


con = duckdb.connect()
con.install_extension('excel.duckdb_extension')

**Comment by amplifinn-admin** [comment]
> ```python
> con.load_extension('aaarrgh')
> ```

Result for above mentioned code:
>>> import duckdb
>>> con = duckdb.connect(database=':memory:')
>>> con.load_extension('excel')
Segmentation fault (core dumped)

**Comment by Mause** [comment]
> > @amplifinn-admin can you share the commands you used to build the `excel` extension for `linux_arm64_gcc4`?
> 
> I have downloaded manually excel.duckdb_extension.gz with this link: http://extensions.duckdb.org/v0.9.2/linux_arm64/excel.duckdb_extension.gz
> 
> import gzip
> import shutil
> import duckdb
> 
> with gzip.open('excel.duckdb_extension.gz','rb') as f_in:
>    with open('excel.duckdb_extension', 'wb') as f_out:
>      shutil.copyfileobj(f_in, f_out)
> 
> 
> con = duckdb.connect()
> con.install_extension('excel.duckdb_extension')

The abi in that download isn't compatible with the python DuckDB binding, so a segfault here, while not ideal, isn't surprising

**Comment by carlopi** [comment]
Thanks for reporting this. We already have in the roadmap implementing (some) checks before INSTALL and LOAD of extensions, that would have prevented this from happening but allow, on LOAD of a non compatible file, some error informing users that the file do not look like a compatible extensions.

I will close this for now, most relevant issue here is https://github.com/duckdb/duckdb/issues/8035, that is currently not planned.

**Comment by szarnyasg** [comment]
@amplifinn-admin the platforms `linux_arm64_gcc` and `linux_arm64` are different ones, see the [list of our platforms](https://duckdb.org/docs/extensions/working_with_extensions#platforms). This causes the error.
