### ISSUE TITLE
Lag function with row() function returns error

### ISSUE THREAD

**Issue by ErikJansenIRefact** [duckdb/duckdb#9748]
### What happens?

Query returns the following error: `Error: Invalid Error: Can't pack nothing into a struct.`
Preferably a null value for previous_row should have been returned for the first row in the set which is the default value for the lag function.

### To Reproduce

```
with data as
(
  select *
  from   (values (1, 1, 1), (2,2,2,)) as t(a,b,c)
)
, previous_row as 
(
  select data.*
       , lag(row(data.*)) over (order by a) as previous_row
  from   data
)
select * from previous_row
;
```

### OS:

osx x86-64

### DuckDB Version:

0.9.1

### DuckDB Client:

cli

### Full Name:

Erik Jansen

### Affiliation:

I-Refact BV

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
As mentioned in 0.9.0 we introduced a breaking change to `row`, use `struct_pack` instead 👍

**Comment by ErikJansenIRefact** [comment]
But struct_pack requires explicit naming? Or is it possible to refer to data.* in struct_pack? Otherwise it will be very cumbersome to get the complete previous row as a struct (you have to name each and every column).

**Comment by szarnyasg** [comment]
`struct_pack` requires explicit naming at this time.
