### ISSUE TITLE
Interval fractional second precision is discarded/fails to be parsed

### ISSUE THREAD

**Issue by LeonidChistov** [duckdb/duckdb#9762]
### What happens?

Consider following options to create interval value with milliseconds precision

```sql
select interval 10.123 second;
select interval '10.123' second;
select '47.210'::interval second;
select '00:00:47.210'::interval second;
```

Only the last option works, however for three first options we get following issues:
- `Parser Error: syntax error at or near "10.123"`
- `00:00:10` (**Value is truncated**)
- `Error: Conversion Error: extract specifier "" not recognized`

Second option is especially desirable to work since this a standard syntax supported by many databsases (and Postgres in particular).

### To Reproduce

Run queries listed above using DuckDB CLI.

### OS:

Linux

### DuckDB Version:

0.9.2

### DuckDB Client:

cli

### Full Name:

Leonid Chistov

### Affiliation:

Querify Labs

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Trying these in Postgres:

```sql
hawkfish=# select interval 10.123 second;
ERROR:  syntax error at or near "10.123"
LINE 1: select interval 10.123 second;

hawkfish=# select interval '10.123' second;
   interval   
--------------
 00:00:10.123

hawkfish=# select '47.210'::interval second;
  interval   
-------------
 00:00:47.21

hawkfish=# select '00:00:47.210'::interval second;
  interval   
-------------
 00:00:47.21
```

So the first one simply isn't valid, but we need to deal with the others. Probably something dumb.

**Comment by hawkfish** [comment]
Note that in the last two, the final "second" is actually parsed as a column name in both systems.

**Comment by hawkfish** [comment]
The issue in the first problem is that our built in functions for converting hours/minutes/.seconds/ms to intervals take integers instead of doubles. This will require a documentation update.

**Comment by szarnyasg** [comment]
> The issue in the first problem is that our built in functions for converting hours/minutes/.seconds/ms to intervals take integers instead of doubles. This will require a documentation update.

@hawkfish given that you're PR fixed this issue, the documentation update (https://github.com/duckdb/duckdb-web/issues/1583) is no longer required. Right?

**Comment by hawkfish** [comment]
Sigh looks like this is still not quite right.

**Comment by hawkfish** [comment]
Some code seems to have gotten lost here. There was some parsing and truncation logic in `TransformInterval` that is no longer there.
