### ISSUE TITLE
Error when a parquet partition key contains numbers and alphabetics characters

### ISSUE THREAD

**Issue by nbc** [duckdb/duckdb#9763]
### What happens?

When a parquet partition key mixes numbers and alphabetic characters, duckdb fails on reading with error :

```
Error: Invalid Input Error: Unable to cast 'a' (from hive partition column 'KEY') to: 'BIGINT'
```

### To Reproduce

```
CREATE TABLE tbl(key VARCHAR, name VARCHAR);
INSERT INTO tbl VALUES ('a', 'Mark'), ('1', 'Hannes');
COPY (SELECT * FROM tbl) TO 'ds_pqt' (FORMAT PARQUET, PARTITION_BY (key));
SELECT * FROM 'ds_pqt/**/*.parquet';
```

### OS:

linux

### DuckDB Version:

0.9.2 and bleeding edge

### DuckDB Client:

cli

### Full Name:

Nicolas Chuche

### Affiliation:

MTES : https://github.com/MTES-MCT/

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for reporting this. I can indeed reproduce this on Linux but it does not occur on macOS, so this is a platform-specific bug.

**Comment by nbc** [comment]
Forgot to said that a work around is is passing hive_types :

```
D SELECT * FROM 'ds_pqt/**/*.parquet';
Error: Invalid Input Error: Unable to cast 'a' (from hive partition column 'KEY') to: 'BIGINT'
D 
D SELECT * FROM read_parquet('ds_pqt/**/*.parquet',  hive_types={'key': string});
┌─────────┬─────────┐
│   key   │  name   │
│ varchar │ varchar │
├─────────┼─────────┤
│ 1       │ Hannes  │
│ a       │ Mark    │
└─────────┴─────────┘
```
