### ISSUE TITLE
S3 region must always be set, even when working with non-AWS object store

### ISSUE THREAD

**Issue by janjagusch** [duckdb/duckdb#9778]
### What happens?

It's unclear from the documentation that you must provide an S3 region when working with a non-AWS object store, like MinIO or Apache Ozone.

**Context:**

For s3, the structure of the authorization header looks like this:

https://github.com/duckdb/duckdb/blob/eed7b7b6b61c1575a18293b16b09e143a98531c1/extension/httpfs/s3fs.cpp#L70-L71

Leaving `auth_params.region` will result in a 'Bad Request' error from the server.

When the `s3_region` option is not set, DuckDB tries to infer the default region from AWS environment variables (`AWS_REGION` and `AWS_DEFAULT_REGION`). DuckDB will fall back to an empty string if these environment variables are not defined.
https://github.com/duckdb/duckdb/blob/eed7b7b6b61c1575a18293b16b09e143a98531c1/extension/httpfs/include/s3fs.hpp#L21-L22

**Proposed solution:**

- Default to 'us-east-1' when the S3 region is not provided through the extension option or the environment variables.
- Raise an error in the `create_s3_header` function when `auth_params.region` is empty.
- Update the documentation to communicate that the `s3_region` value must always be set, even for non-AWS object storage.

### To Reproduce

This bug was encountered when fetching data from [Apache Ozone](https://ozone.apache.org/) through the [S3 protocol](https://ozone.apache.org/docs/1.0.0/interface/s3.html). My assumption is that this affects all self-hosted blob stores that expose a S3 interface, but I haven't tested that.

```sql
LOAD json;
LOAD httpfs;

SET s3_endpoint='localhost:9879';
SET s3_url_style='path';
SET s3_access_key_id='...';
SET s3_secret_access_key='...';

-- This returns a 400 (Bad Request) status code.
SELECT * FROM 's3://bucket/file.json';

SET s3_region='us-east-1';
-- This returns a 200 status code.
SELECT * FROM 's3://bucket/file.json';
```

### OS:

Linux

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

Jan-Benedikt Jagusch

### Affiliation:

QuantCo

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks @janjagusch for the detailed report. We are working on a fix (but cannot provide an ETA at this time).

**Comment by samansmink** [comment]
This should be fixed, the default is us-east-1 and with secrets: https://github.com/duckdb/duckdb/pull/10042, the correct default is also chosen
