### ISSUE TITLE
 Issue with "week" in date_add function

### ISSUE THREAD

**Issue by Fransoic** [duckdb/duckdb#9785]
### What happens?

When using the date_add function with the interval keyword "week," DuckDB throws a syntax error. This issue is specific to "week," as it works correctly with other keywords like "month."

### To Reproduce

1. Execute the following SQL query using DuckDB:

    ```
    SELECT date_add(INTERVAL 3 month, current_date);
    ```
    _Expected output: A date that is three months from the current date._
    
    Actual output: The query executes successfully, and the output is correct.

2. Execute the following SQL query using DuckDB:

    ```
    SELECT date_add(INTERVAL 3 week, current_date);
    ```
    _Expected output: A date that is three weeks from the current date._
    
    **Actual output: DuckDB throws a syntax error:**
    
    ```
    Parser Error: syntax error at or near "week"
    LINE 1: SELECT date_add(INTERVAL 3 week, current_date);
    ```

3. Execute the following SQL query using DuckDB as a workaround:
    
    ```
    SELECT date_add(INTERVAL '3 week', current_date);
    ```
    _Expected output: A date that is three weeks from the current date._
    
    Actual output: The query executes successfully, and the output is correct.

### OS:

https://shell.duckdb.org/

### DuckDB Version:

web

### DuckDB Client:

@duckdb/duckdb-wasm@1.28.1-dev23.0

### Full Name:

Francois CORIC

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
Postgres (whose parser we use) doesn't like these either. It doesn't overload `date_add` but simple addition gives a syntax error for both:

```sql
hawkfish=# select current_date + INTERVAL 3 month;
ERROR:  syntax error at or near "3"
LINE 1: select current_date + INTERVAL 3 month;
                                       ^
hawkfish=# select current_date + INTERVAL 3 week;
ERROR:  syntax error at or near "3"
LINE 1: select current_date + INTERVAL 3 week;
                                       ^
```

It does support both string casts (same as we do):

```sql
hawkfish=# select current_date + INTERVAL '3 month' d;
          d          
---------------------
 2024-02-24 00:00:00
(1 row)

hawkfish=# select current_date + INTERVAL '3 week' d;
          d          
---------------------
 2023-12-15 00:00:00
(1 row)
```

So it looks like we have extended the parser a bit, but not for all interval part names.

**Comment by hawkfish** [comment]
Looks like we have defined some constants but not used them:

```cpp
/* these are only for parsing intervals */
#define WEEK		24
#define DECADE		25
#define CENTURY		26
#define MILLENNIUM	27
```

**Comment by hawkfish** [comment]
Not to mention

```cpp
	// (we might add support if someone complains about it)
```

!
