### ISSUE TITLE
The query becomes sluggish when performing a join between a small Parquet file and a much larger one with 50 million records.

### ISSUE THREAD

**Issue by huzech** [duckdb/duckdb#9789]
### What happens?

Querying a small Parquet file and performing a join with a larger 50 million-row Parquet file is experiencing significant delays, taking more than 10 seconds. However, when executing the same operation in a PostgreSQL database with identical data, the process takes less than 1 second.

### To Reproduce

Executing the query
```
duckdb.sql('SELECT * FROM "tmp/uniprot1000.parquet" a join "tmp/uniprot5000.parquet" b on (b.index = a.index) limit 1')
```
is taking 5 seconds to complete. The "uniprot1000" Parquet file contains 10 million records, while the "uniprot5000" Parquet file contains 50 million records.

### OS:

windows x64

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

george

### Affiliation:

cloudna

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by huzech** [comment]
[data.zip](https://github.com/duckdb/duckdb/files/13457626/data.zip)
Please change the file extension to .7z and decompress. The package includes four files:
uniprot_small.parquet 5 records
uniprot10.parquet 100000 records
uniprot100.parquet 1000000 records
uniprot5000_2.parquet 49367000 records
You'll observe some interesting time cost results.
![image](https://github.com/duckdb/duckdb/assets/9508398/9b647d4a-5470-48c4-a2d1-54d10818d006)
![image](https://github.com/duckdb/duckdb/assets/9508398/2ad8971d-2d19-4b88-a1a0-fe75170ffc8f)

The query is significantly slower with the "limit 1" condition in a Parquet file containing only 5 records. Surprisingly, the query with 100,000 records is faster than the one with 5 records.

However, when using PostgreSQL, all queries are consistently fast

**Comment by szarnyasg** [comment]
Thanks. Here's a list of queries that run the full join for further investigation:
```sql
CREATE OR REPLACE TEMP TABLE t AS SELECT * FROM "uniprot_small.parquet" a join "uniprot5000_2.parquet" b on (b.index = a.index);
CREATE OR REPLACE TEMP TABLE t AS SELECT * FROM "uniprot10.parquet"     a join "uniprot5000_2.parquet" b on (b.index = a.index);
CREATE OR REPLACE TEMP TABLE t AS SELECT * FROM "uniprot100.parquet"    a join "uniprot5000_2.parquet" b on (b.index = a.index);
CREATE OR REPLACE TEMP TABLE t AS SELECT * FROM "uniprot5000_2.parquet" a join "uniprot5000_2.parquet" b on (b.index = a.index);
```
