### ISSUE TITLE
Collation Issue: Min/Max function doesn't use collations.

### ISSUE THREAD

**Issue by StarveZhou** [duckdb/duckdb#9795]
### What happens?

Collation does not seem to work in the Min/Max operation. 
IMHO, the following two queries should return the same result:
``` sql
select min(a) from tbl;
select a from tbl order by a limit 1;
```

Same as the following two queries
``` sql
select max(a) from tbl;
select a from tbl order by a desc limit 1;
```

### To Reproduce

``` sql
create table tbl (a varchar collate noaccent);
insert into tbl values ('ö'), ('o'), ('p');
-- max
select max(a) from tbl; -- this will return 'ö'
select a from tbl order by a desc limit 1; -- this will return 'p', which should be the right result

-- min
select min(a) from tbl; -- this will return 'o'
select a from tbl order by a limit 1; -- this will return 'ö', which should be the right result
```

But for comparison:
``` sql
select 'p' > 'ö'; -- this returns false
select 'p' > 'ö' collate noaccent; -- this returns true
```

Arg_max/Arg_min have the same issue.

``` sql
select arg_max(a, a) from tbl; -- return 'ö'
select arg_min(a, a) from tbl; -- return 'o'
```

### OS:

Linux x64

### DuckDB Version:

v0.9.2

### DuckDB Client:

CLI

### Full Name:

Zhou Jiayu

### Affiliation:

Huawei

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
I think this has since been solved. Can you update to v0.10.0 and give it a try?

**Comment by carlopi** [comment]
This can't be reproduced anymore, and there has been work going on on collations.

This is now solved, thanks for raising this!
