### ISSUE TITLE
Duckdb accesses arbitrary process data leading to process crash and/or data leaks

### ISSUE THREAD

**Issue by TheDerivator** [duckdb/duckdb#9801]
### What happens?

The following snippet of Python code can at random lead to different outcomes if you run it a large number of times. Some possible outcomes are pasted below. As part of a larger application I have also seen it crash the process instead of raising a Python exception and worse yet, leak arbitrary process data in variations but this is harder to reproduce in a minimal example.

The issue is likely caused by having multiple DuckDBPyRelation objects alive at the same time. It's not clear from the documentation if this is supported but the behaviour seems undesirable either way.

Possible outcome:
```
Doing 0
(...)
Doing 19
[(899, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), (898, 'ccccccccc'), (897, 'bbbb'), (896, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), (895, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')]
```

Also possible outcome:
```
Doing 0
Traceback (most recent call last):
  File "p:\_source\scripts\duckdbtest.py", line 14, in <module>
    result = rel1.fetchmany(size=5)
             ^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.Error: Invalid unicode (byte sequence mismatch) detected in value construction
```

### To Reproduce

```
import duckdb
con = duckdb.connect(':memory:')
con.execute(r'CREATE TABLE test(id INTEGER , name VARCHAR NOT NULL);')

words = ['aaaaaaaaaaaaaaaaaaaaaaa', 'bbbb', 'ccccccccc', 'ííííííííí']
lines = [(i, words[i%4]) for i in range(1000)]
con.executemany("INSERT INTO TEST (id, name) VALUES (?, ?)", lines)

rel1 = con.sql("""SELECT id, name FROM test ORDER BY id DESC """)
rel1.fetchmany(size=5)
result = con.sql("SELECT name from test order by id desc limit 1").fetchone()  # This causes the bug
for i in range(20):
    print(f"Doing {i}")
    result = rel1.fetchmany(size=5)
print(result)
```

### OS:

Windows 11

### DuckDB Version:

0.9.2

### DuckDB Client:

Python 3.11.6

### Full Name:

No Thx

### Affiliation:

Personal project

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

Sidenote, I looked into the documented examples and the issue goes away with an extra `execute`, so this is fine:

```
rel1 = con.sql("SELECT id, name FROM test ORDER BY id DESC").execute()
rel1.fetchmany(size=5)
result = con.sql("...").fetchone()
for i in range(20):
    rel1.fetchmany(size=5)
print(result)
```

**Comment by Mytherin** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/9968
