### ISSUE TITLE
Issue passing strings between nested UDFs

### ISSUE THREAD

**Issue by dino-rodriguez** [duckdb/duckdb#9804]
### What happens?

I am trying to make a nested UDF call in a SQL query, but passing the output of one UDF to the input of another seems to not work as expected.

Here is the C++ UDF code:

```
// Check if the string is a valid number
static inline bool isNumber(const std::string &s) {
    if (s.empty()) return false;
    return s.find_first_not_of("0123456789.-") == std::string::npos;
}

bool compare_nums(duckdb::string_t a_str, duckdb::string_t operator_str, duckdb::string_t b_str) {
    if (!isNumber(a_str.GetString())) {
        std::cout << "Not a number: " << a_str.GetString() << std::endl;
    }

    mp::cpp_dec_float_100 num_a(a_str.GetString());
    mp::cpp_dec_float_100 num_b(b_str.GetString());
    
    // Perform comparison based on the operator
    std::string op = operator_str.GetString();
    if (op == ">") {
        return num_a > num_b;
    } else if (op == "<") {
        return num_a < num_b;
    } else if (op == "==") {
        return num_a == num_b;
    } else if (op == ">=") {
        return num_a >= num_b;
    } else if (op == "<=") {
        return num_a <= num_b;
    } else if (op == "!=") {
        return num_a != num_b;
    }

    throw std::runtime_error("Unsupported operator");
}


duckdb::string_t wei_to_eth(duckdb::string_t wei_str) {
    mp::cpp_dec_float_100 wei(wei_str.GetString());
    mp::cpp_dec_float_100 eth = wei / mp::pow(mp::cpp_dec_float_100(10), 18);

    // 'std::fixed' ensures no scientific notation
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(6) << eth;
    std::string result = ss.str();

     // Remove any trailing null characters
    result.erase(std::find(result.begin(), result.end(), '\0'), result.end());

    if (!isNumber(result)) {
        std::cout << "Not a number: " << result << std::endl;
    }

    return duckdb::string_t(result);
}
```

I am using pybind to invoke the C++ code from python, so here are the queries I am calling:
```
import time

import duckdb_c  # type: ignore

query_1 = """
    SELECT * FROM read_parquet("parquet_test/*.parquet")
    WHERE wei_to_eth(_amountIn) IS NOT NULL
    """

query_2 = """
    SELECT * FROM read_parquet("parquet_test/*.parquet")
    WHERE compare_nums(_amountIn, '>', 0)
    """

query_3 = """
    SELECT * FROM read_parquet("parquet_test/*.parquet")
    WHERE wei_to_eth(_amountIn) > 0
    """

query_4 = """
    SELECT * FROM read_parquet("parquet_test/*.parquet")
    WHERE compare_nums(wei_to_eth(_amountIn), '>', 0)
    """

start = time.time()
res = duckdb_c.run_query(query_1)
end = time.time()
print(res.success)
print(res.error)
print(res.column_names)
print("Num results:", len(res.rows))
print("Time taken: ", end - start)

start = time.time()
res = duckdb_c.run_query(query_2)
end = time.time()
print(res.success)
print(res.error)
print(res.column_names)
print("Num results:", len(res.rows))
print("Time taken: ", end - start)

start = time.time()
res = duckdb_c.run_query(query_3)
end = time.time()
print(res.success)
print(res.error)
print(res.column_names)
print("Num results:", len(res.rows))
print("Time taken: ", end - start)

start = time.time()
res = duckdb_c.run_query(query_4)
end = time.time()
print(res.success)
print(res.error)
print(res.column_names)
print("Num results:", len(res.rows))
print("Time taken: ", end - start)
```

And here is the output of calling those queries:
```
True

['blockHash', 'blockNumber', 'chainId', 'from', 'gas', 'gasPrice', 'hash', 'input', 'maxFeePerGas', 'maxPriorityFeePerGas', 'methodId', 'nonce', 'r', 's', 'to', 'transactionIndex', 'type', 'v', 'value', '_amountIn', '_amountOutMin', '_path', '_to', '_deadline']
Num results: 40907
Time taken:  0.3674170970916748
True

['blockHash', 'blockNumber', 'chainId', 'from', 'gas', 'gasPrice', 'hash', 'input', 'maxFeePerGas', 'maxPriorityFeePerGas', 'methodId', 'nonce', 'r', 's', 'to', 'transactionIndex', 'type', 'v', 'value', '_amountIn', '_amountOutMin', '_path', '_to', '_deadline']
Num results: 40872
Time taken:  0.27791881561279297
False
Conversion Error: Could not convert string '690853471.681544\0\0\0' to INT32
[]
Num results: 0
Time taken:  0.04299187660217285
Not a number:
False
Invalid Error: Can not construct a floating point with non-numeric content
[]
Num results: 0
Time taken:  0.0115509033203125
```

Going through this, the output of the first query works as expected. The UDF executes.

The output of the second query also works as expected, also executes.

The output of the third query is expected to error - I am explicitly comparing a string to an integer so the error shows me the contents of the string. It looks like the string has null padding at the end of it, which I think may be the source of the problem. The strings should not contain these extra characters. Note in the `wei_to_eth` UDF i do strip the string of the null characters. But perhaps I need to do it after the cast to the duck_db::string_t type? Not super familiar with the intricacies of this type

The output of the final query is the actual issue at hand. The `compare_nums` UDF complains that the output of the `wei_to_eth` UDF is not a valid string -- perhaps because of the extra null characters.

---

I have confirmed there is no NULL values in the dataset I am working with and they are all valid integers represented as strings in the dataset.

### To Reproduce

As aI mentioned, I am calling this from python. To reproduce I will include all necessary files to run and the c++ files for reference. 

You should be able to unzip the folder and run `python test_duckdb_c.py` directly so long as you are running python11.
[debug.zip](https://github.com/duckdb/duckdb/files/13465237/debug.zip)

### OS:

MacOS

### DuckDB Version:

Latest release

### DuckDB Client:

C++

### Full Name:

Dino Rodriguez

### Affiliation:

Yoz Labs

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by dino-rodriguez** [comment]
Update:

I was able to add more visibility by printing out any non string characters at the beginning of the `compare_nums` function with:

```
static inline bool isNumber(const std::string &s) {
    if (s.empty()) return false;

    size_t non_numeric_pos = s.find_first_not_of("0123456789.-");
    if (non_numeric_pos != std::string::npos) {
        unsigned char non_numeric_char = s[non_numeric_pos];
        std::cout << "Non-numeric character found: '"
                  << non_numeric_char << "' (ASCII: " << static_cast<int>(non_numeric_char)
                  << ") at position " << non_numeric_pos
                  << " in string: " << s << std::endl;
        return false;
    }

    return true;
}
```

The output yields:
```
...
Non-numeric character found: '' (ASCII: 0) at position 8 in string: 0.000362
Non-numeric character found: '' (ASCII: 0) at position 8 in string: 0.000362
Non-numeric character found: '' (ASCII: 0) at position 8 in string: 0.000362
```

When calling the same function at the end of `wei_to_eth`, we do not see this output. So for whatever reason, when the strings are being passed into this function again as a `string_t` they are being padded with extra characters. Not sure what exactly is happening under the hood, but it seems like something is going on with the way duck db accepts `string_t` from another UDF as opposed to from the DB directly.

Here is the updated zip that can be run with the debugging output:
[debug.zip](https://github.com/duckdb/duckdb/files/13465629/debug.zip)

**Comment by dino-rodriguez** [comment]
Adding the `setup.py` as i think it would be helpful:

```
from pybind11.setup_helpers import Pybind11Extension, build_ext
from setuptools import setup

ext_modules = [
    Pybind11Extension(
        "duckdb_c",
        ["duckdb_c.cpp"],
        include_dirs=["/opt/homebrew/include", "/usr/local/include"],
        library_dirs=["/usr/local/lib"],
        libraries=["duckdb"],
    ),
]

setup(
    name="duckdb_c",
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
)
```

**Comment by dino-rodriguez** [comment]
@szarnyasg Any update on this? I noticed was marked under review earlier today

**Comment by szarnyasg** [comment]
Hi @dino-rodriguez, we reviewed this issue today. Unfortunately, the C++ API and custom UDFs are not covered by our [community support policy](https://duckdblabs.com/news/2023/10/02/support-policy.html#extensions-and-apis). If you are interested in commercial support, please see our [custom support option](https://duckdblabs.com/support/).
