### ISSUE TITLE
JSON write support to S3

### ISSUE THREAD

**Issue by pixie79** [duckdb/duckdb#9807]
### What happens?

I am trying to write a table out to S3 following hive partitioning but I am getting the following error:

```py
duck_con.sql(f"COPY results TO '{output_location + filename}.json' (ARRAY true)")
```
```
duckdb.duckdb.IOException: IO Error: Unable to connect to URL "https://<bucket_name>-data-refined.s3.amazonaws.com/egress/products/year%5C%3D2023/month%5C%3D11/day%5C%3D26/hour%5C%3D17/data.json
```

I get the same error if i cut the path to just egress/products/data.json

### To Reproduce

```py
bucket = "<bucket_name>"
product = "products"
path = f"egress/{product}/year={current_dateTime.year}/month={current_dateTime.month}/day={current_dateTime.day}/hour={current_dateTime.hour}/"
output_location = f"s3://{bucket}/{path}"

duck_con.sql(f"COPY results TO '{output_location + filename}.json' (ARRAY true)")
```

### OS:

Ubuntu x64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Mark Olliver

### Affiliation:

None - private learning

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @pixie79 can you write regular files (e.g. CSVs, or JSONs without `=` in the path) to your S3 bucket using DuckDB?

**Comment by pixie79** [comment]
Hi @szarnyasg 

Nope I tried that as well by ignoring the hive partitioning part and just writing out at /egress/products/data.json

**Comment by szarnyasg** [comment]
The reason I'm asking this is because you get a very generic error message ("Unable to connect to URL"). It seems that your S3 bucket's configuration is off - maybe you lack permission to write to the bucket?

**Comment by pixie79** [comment]
Nope not permissions, I have just written the file out locally and then used aws s3 cp to put the file in the same location no issues.

(Same environment variables set for AWS)

**Comment by szarnyasg** [comment]
So your credentials seem to be working for putting objects to S3 via the AWS CLI client (`aws s3 cp`). However, they don't seem to work when using DuckDB. Did you also set them in Python? You can do so like this:
```sql
import duckdb
duckdb.sql("SET s3_region='...';")
duckdb.sql("SET s3_access_key_id='...';")
duckdb.sql("SET s3_secret_access_key='...';")
```

**Comment by pixie79** [comment]
After some more testing I think I have found the issue. I need to export the environment variable
DUCKDB_S3_ENDPOINT=“s3.af-south-1.amazonaws.com”
As the target bucket is in the af-south-1 region.
This works for both buckets with Owner owns all objects, Version and Object lock. I do get the 400 error again if I turn on default retention on top of Object lock.

**Comment by szarnyasg** [comment]
Great, let us know if you bump into any further issues.
