### ISSUE TITLE
Segmentation fault occurs when calling concat_ws.

### ISSUE THREAD

**Issue by yiyuanliu** [duckdb/duckdb#9808]
### What happens?

```
D select concat_ws('.', list_reverse(string_split('1.2..3', '.')));
Segmentation fault (core dumped)
```

### To Reproduce

see above.

### OS:

ubuntu

### DuckDB Version:

0.9.2

### DuckDB Client:

cli

### Full Name:

Yiyuan Liu

### Affiliation:

High-Flyer AI

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Should be fixed by #9819
