### ISSUE TITLE
[c-api] duckdb_result_error() returns THE address of temporary string object

### ISSUE THREAD

**Issue by fanvanzh** [duckdb/duckdb#9823]
### What happens?

In the c-api, duckdb_result_error returns the address of temporary string object, which may cause to invalid memory-pointer

### To Reproduce

```
const char *duckdb_result_error(duckdb_result *result) {
	if (!result) {
		return nullptr;
	}
	auto &result_data = *(reinterpret_cast<duckdb::DuckDBResultData *>(result->internal_data));
	return !result_data.result->HasError() ? nullptr : result_data.result->GetError().c_str();
}
```
while `result_data.result->GetError()` returns a temporary string object, returns the address of GetError() may cause memory problem.

### OS:

linux

### DuckDB Version:

master

### DuckDB Client:

duckapi-c

### Full Name:

fanvanzh

### Affiliation:

fanvanzh

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
I see what you mean, but the error is owned by the `duckdb_result`, it's not a temporary string object

The docs on `duckdb_result_error` even say
```c
Note that after running `duckdb_query`, `duckdb_destroy_result` must be called on the result object even if the
query fails, otherwise the error stored within the result will not be freed correctly.
```

**Comment by fanvanzh** [comment]
this is my mistake
