### ISSUE TITLE
duckdb_free doesn't free correctly if the type is LIST

### ISSUE THREAD

**Issue by marwanhazemblnk** [duckdb/duckdb#9849]
### What happens?

When use duckdb_value_string and free it if the previous value is list which is equivalent to number 24 in your types enum.
When i use the variable next time I get a segementation fault which In my case i believe shows that it does not free correctly.

### To Reproduce

comment if you could not reproduce it and I'll create a test case.

### OS:

ubuntu 22

### DuckDB Version:

0.9.2

### DuckDB Client:

C++

### Full Name:

marwan

### Affiliation:

n/a

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
That sounds like it's either a double free or freeing stack memory, can you make a reproduction?
Without a reproduction there is very little for us to go off of

**Comment by marwanhazemblnk** [comment]
```
  #include "../headers/duckdb.hpp"
  #include <string.h>
  #include <iostream>
  using namespace std;
   int main()
   {

    duckdb_database duckDB;
    duckdb_open(nullptr, &duckDB);

    duckdb_connection con = NULL;
    duckdb_result result_c;
    duckdb_state query_state;
    string query = "CREATE TABLE test(id BIGINT, one DECIMAL(18,3)[] , two DECIMAL(18,3)[], three BIGINT, four DECIMAL(18,3)[]);";
    string query_2 = "INSERT INTO test VALUES (410, '[]', '[]',4,'[]');";
    string query_3 = "INSERT INTO test VALUES (412, '[]', '[]',4,'[]');";
    string query_4 = "select id,one,two,three,four from test;";

    duckdb_connect(duckDB, &con);
    query_state = duckdb_query(con, query.c_str(), &result_c);
    query_state = duckdb_query(con, query_2.c_str(), &result_c);
    query_state = duckdb_query(con, query_3.c_str(), &result_c);
    query_state = duckdb_query(con, query_4.c_str(), &result_c);    
    int row_count = duckdb_row_count(&result_c);
    int column_count = duckdb_column_count(&result_c);
    for (idx_t row = 0; row < row_count; row++)
    {
        for (idx_t col = 0; col < column_count; col++)
        {
            duckdb_string str_val =  duckdb_value_string(&result_c, col, row);
        }
    }

 }
```

**Comment by marwanhazemblnk** [comment]
comment not to remove
