### ISSUE TITLE
Unable to export database with user defined type

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#9851]
### What happens?

An exception "InternalException: INTERNAL Error: Logical Type can't be used as a User Defined Type" is raised exporting a database after executing 'create type'

### To Reproduce

```sql
CREATE TYPE my_struct AS STRUCT(a TEXT);
EXPORT DATABASE 'test';
```

### OS:

osx aarch64, windows x64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

eaubin

### Affiliation:

n/a

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/10569

Note: this is still suffering from the order issue in EXPORT DATABASE, you might have to manually fix the ordering in the created `schema.sql` file
