### ISSUE TITLE
Collation Issue: ORDER BY CONCAT

### ISSUE THREAD

**Issue by StarveZhou** [duckdb/duckdb#9854]
### What happens?

`select a from tbl order by a;` and `select a from tbl order by concat(a, a);` should return same order for single character string. But it's not with collations.

### To Reproduce

``` sql
create table tbl (a varchar collate noaccent);
insert into tbl values ('ö'), ('o'), ('p');
select a from tbl order by a; -- order is 'ö', 'o', 'p', which is correct
select a from tbl order by concat(a, a); -- order is 'o', 'p', 'ö'
```

### OS:

macos

### DuckDB Version:

v0.9.2

### DuckDB Client:

CLI

### Full Name:

Zhou Jiayu

### Affiliation:

Huawei

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by StarveZhou** [comment]
I clean the build directory and rebuild it, still have the issue.

```
D create table tbl (a varchar collate noaccent);
D insert into tbl values ('ö'), ('o'), ('p');
D select a from tbl order by a;
┌─────────┐
│    a    │
│ varchar │
├─────────┤
│ ö       │
│ o       │
│ p       │
└─────────┘
D select a from tbl order by concat(a, a);
┌─────────┐
│    a    │
│ varchar │
├─────────┤
│ o       │
│ p       │
│ ö       │
└─────────┘

```

Really weird. I built duckdb in debug mode and in macos 14.1.1. And current commit id is '9c91b3a329073ea1767b0aaff94b51da98dd03e2'.

**Comment by l1t1** [comment]
aarch64 linux version has the question. 
```
root@localhost:/data/data/com.termux/files/home/092# ./duckdb
v0.9.2 3c695d7ba9
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table tbl (a varchar collate noaccent);
D insert into tbl values ('ö'), ('o'), ('p');
D select a from tbl order by a;
┌─────────┐
│    a    │
│ varchar │
├─────────┤
│ ö       │
│ o       │
│ p       │
└─────────┘
D select a from tbl order by concat(a, a);
┌─────────┐
│    a    │
│ varchar │
├─────────┤
│ o       │
│ p       │
│ ö       │
└─────────┘
```

**Comment by StarveZhou** [comment]
x86_64 Ubuntu 22.04.3 LTS
```
D create table tbl (a varchar collate noaccent);
D insert into tbl values ('?'), ('o'), ('p');
D select a from tbl order by a;
┌─────────┐
│    a    │
│ varchar │
├─────────┤
│ ?       │
│ o       │
│ p       │
└─────────┘
D select a from tbl order by concat(a, a);
┌─────────┐
│    a    │
│ varchar │
├─────────┤
│ o       │
│ p       │
│ ?       │
└─────────┘
```

**Comment by StarveZhou** [comment]
It's not just `concat` function problem. Some return-string functions don't inherit children's `return_type`. I found these function got error results:
1. concat
2. lower
3. ltrim
4. nfc_normalize
5. printf
6. repeat
7. right
8. reverse
9. right_grapheme
...

Actually, I think all maybe all string-returned functions have this problem.

The problem can be fixed by resolve children's `return_type` with `BoundComparisonExpression::BindComparison`. But the actual problem is `BoundComparisonExpression::BindComparison` will raise exception for different collations. Like this:

``` sql
select concat(a collate nocase, b collate noaccent) from tbl; -- sql1
select * from tbl order by concat(a collate nocase, b collate noaccent); -- sql2
select * from tbl group by concat(a collate nocase, b collate noaccent); -- sql3
```

Maybe sql1 should run as usual but sql2 and sql3 should raise exception.
I will try to fix this problem based on this. And please let me know if you have any good ideas. @szarnyasg @l1t1

**Comment by tkhuawei** [comment]
> It's not just `concat` function problem. Some return-string functions don't inherit children's `return_type`. I found these function got error results:
> 
> 1. concat
> 2. lower
> 3. ltrim
> 4. nfc_normalize
> 5. printf
> 6. repeat
> 7. right
> 8. reverse
> 9. right_grapheme
>    ...

**starts_with** doesn't support collation as well, see example:
```
SELECT * FROM (SELECT 'A' COLLATE NOCASE) AS DERIVED(C1) WHERE c1 = 'a';
┌─────────┐
│   C1    │
│ varchar │
├─────────┤
│ A       │
└─────────┘
SELECT * FROM (SELECT 'A' COLLATE NOCASE) AS DERIVED(C1) WHERE starts_with(c1, 'a');
┌─────────┐
│   C1    │
│ varchar │
├─────────┤
│ 0 rows  │
└─────────┘
```

**Comment by tkhuawei** [comment]
Is it in the roadmap?

**Comment by Mytherin** [comment]
This has been implemented in https://github.com/duckdb/duckdb/pull/14717
