### ISSUE TITLE
pip no longer installs pre-release builds?

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#9859]
### What happens?

`pip install duckdb --upgrade --pre` no longer installs the pre-release version of DuckDB.  The lastest version it installs is 0.9.2.  

### To Reproduce

`pip install duckdb --upgrade --pre`

### OS:

Windows 10

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Vincent Munos

### Affiliation:

Admolly Network

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by davidjbrennan** [comment]
This might well be related.  The Python "nightly-build" workflows appear to be building duckdb with version 0.0.0.  

If I use the following

`pip install --upgrade --pre --no-cache-dir duckdb==0.0.0`

then I end up with v0.9.3-dev1565.

I would love to see this issue fixed.
