### ISSUE TITLE
Documentation and/or function for reserved keywords in duckdb

### ISSUE THREAD

**Issue by mskyttner** [duckdb/duckdb#989]
What are reserved duckdb keywords which may not be used as the names of tables, columns/fields etc without first requiring quoting? I didn't find any docs for this at the website or any mention amongst the issues. 

Comparing https://www.sqlite.org/lang_keywords.html to duckdb, using [a script here](https://gist.github.com/mskyttner/2f3d1a2a6964632f106e154c21cd8de3), it seems that several of those ~ 145 keywords that are "reserved" in SQLite can be used without "quoting" in duckdb as table names or field/column names. 

For example these reserved keywords in SQLite appear to not require "quoting" in duckdb when used as table or column/field names:

`abort, action, add, after, alter, always, attach, autoincrement, before, begin, between, by, cascade, commit, conflict, current, database, deferred, delete, detach, drop, each, escape, exclude, exclusive, exists, explain, fail, filter, first, following, generated, groups, if, ignore, immediate, index, indexed, insert, instead, key, last, match, no, nothing, nulls, of, others, over, partition, plan, pragma, preceding, query, raise, range, recursive, regexp, reindex, release, rename, replace, restrict, rollback, row, rows, savepoint, set, temp, temporary, ties, transaction, trigger, unbounded, update, vacuum, values, view, virtual, without
`

These seem to be reserved though, and will require quoting if used as table or field names:

`all, analyze, and, as, asc, case, cast, check, collate, column, constraint, create, cross, current_date, current_time, current_timestamp, default, deferrable, desc, distinct, do, else, end, except, for, foreign, from, full, glob, group, having, in, initially, inner, intersect, into, is, isnull, join, left, like, limit, natural, not, notnull, null, offset, on, or, order, outer, primary, references, right, select, table, then, to, union, unique, using, when, where, window, with`

There are probably more?

It would be nice to have a `duckdb_keywords()` function which would return reserved keywords, so one would know when quoting is required.

**Comment by mskyttner** [comment]
```
-- works
CREATE TABLE view (i integer);

-- doesn't work
CREATE TABLE desc (i integer);
```

**Comment by Mytherin** [comment]
This is mostly shared with PostgreSQL, a list can be found [here](https://github.com/cwida/duckdb/tree/master/third_party/libpg_query/grammar/keywords) (note: anything that has the suffix _P in there is actually the keyword without the _P suffix). Some additional docs can be found [here](https://www.postgresql.org/docs/current/sql-keywords-appendix.html). There are four categories of keywords:

* `reserved`
* `type_func_keyword`
* `column_name_keywords` 
* `unreserved_keywords`

Reserved keywords can generally not be used anywhere (besides as the keyword, or when quoted). Column name keywords can be used as column or table names, but not as functions or types. Type_func keywords can be used as types or functions, but not as column or table names. Unreserved keywords can be used anywhere without quotes.

**Comment by mskyttner** [comment]
The EXPORT DATABASE statement which generates `load.sql` along with schema.sql and exported data does not quote table names such as `desc` in statements (such as `COPY desc FROM '~/ducky/desc.parquet' (FORMAT 'parquet');`), so if those use reserved keywords, a parser error is given:

```r
# a connection to a duckdb exists
con %>% dbWriteTable(name = "desc", desc)
dbExecute(con, "EXPORT DATABASE '~/ducky' (FORMAT PARQUET)")
dbExecute(con, "IMPORT DATABASE '~/ducky'")

#Error in dbSendQuery(conn, statement, ...) : 
#  duckdb_prepare_R: Failed to prepare query IMPORT DATABASE '/home/markus/ducky'
#Error: Parser: syntax error at or near "desc"
```

**Comment by Mytherin** [comment]
Thanks for the report! Indeed they should be quoted here.

**Comment by mskyttner** [comment]
Thanks for the links, I stumbled on this when one of my tables was named "desc" - without the quotes ;). 

Maybe it is a good strategy from the client to "quote everything" when doing custom queries like import/export etc that are not yet wrapped in for example the R library? 

I tried to put together an R function that I can use to run table and column names through to check if I need to "quote" more discriminatingly in such custom queries, based on those links you sent with keywords. 


```r
duckdb_keywords <- function(use_cache = TRUE) {
  
  if (use_cache) {
    if (file.exists("~/duckdb-keywords.rds")) {
      keywords <- readRDS("~/duckdb-keywords.rds")
      return (keywords)
    }
  }
  
  keywords_url <- 
    "https://raw.githubusercontent.com/cwida/duckdb/master/third_party/libpg_query/grammar/keywords/"
  
  variants <- c(
    "unreserved_keywords.list", 
    "type_func_name_keywords.list",
    "reserved_keywords.list",
    "column_name_keywords.list")
  
  urls <- sprintf("%s%s", keywords_url, variants)
  
  read_keywords <- function(url) {
    lines <- readr::read_lines(url)
    sub("_P$", "", lines)
  }
  
  keywords <- 
    urls %>% purrr::map(read_keywords)
  
  names(keywords) <- sub("_keywords.list", "", variants, fixed = TRUE)
  
  saveRDS(keywords, "~/duckdb-keywords.rds")
  keywords
}

check_keyword <- function(x, quiet = FALSE) {

  kw <- duckdb_keywords()
  
  check <- list(
    is_reserved_everywhere = toupper(x) %in% kw$reserved,
    is_reserved_as_column_table = toupper(x) %in% kw$type_func_name,
    is_reserved_as_func_type = toupper(x) %in% kw$column_name,
    is_not_reserved = toupper(x) %in% kw$unreserved
    # The "unreserved" keywords list - wouldn't that be everything but the reserved ones, why are those explicitly stated? 
  )
  
  if (!any(unlist(check)))
    return (list(keyword = x, status = "unknown", check = check))
  
  if (check$is_not_reserved)
    return (list(keyword = x, status = "OK", check = check))
  
  if (!quiet && check$is_reserved_everywhere) {
    message(sprintf("Please quote keyword %s everywhere.", x))
  }
  
  if (!quiet && check$is_reserved_as_column_table) {
    message(sprintf("Please quote keyword %s when used as column or table name.", x))
  }
  
  if (!quiet && check$is_reserved_as_func_type) {
    message(sprintf("Please quote keyword %s when used as function or type name.", x))
  }
  
  keyword <- sprintf("\"%s\"", x)
  
  list(keyword = keyword, status = "reserved", check = check)
  
}

duckdb_check_keywords <- function(keywords, ...) {
  keywords %>% 
    purrr::map(function(x) check_keyword(x, ...)) %>% 
    purrr::map_chr(pluck("keyword"))
}

# check whether some strings should be quoted due to reserved keywords
valid_keywords <- 
  c("desc", "query", "view", "full", "national", "work") %>% 
  duckdb_check_keywords()

cat(valid_keywords)
# "desc" query view "full" "national" work

```

**Comment by mskyttner** [comment]
Is it possible to retrieve keywords, functions, extensions for the running version of duckdb through a query against a system table? For example to check from R whether the Full Text Search extension is installed in duckdb? Or if someone would be interested in doing something like https://github.com/dbcli/litecli/blob/master/litecli/sqlcompleter.py#L17-L253 but without "hardcoding" available functions/keywords?

**Comment by Mytherin** [comment]
We have the `duckdb_keywords` function now
