### ISSUE TITLE
is `owner` a keyword? it cannot be a column name, and error message isn't clear

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#9893]
### What happens?

I tried to use `owner` as the column name, and failed

### To Reproduce

```sql
create table t17 as select id,(id+random())%3 owner from range(1,1500)t(id);
Error: Parser Error: syntax error at or near "owner"
LINE 1: ...table t17 as select id,(id+random())%3 owner from range(1,1500)t(id);
                                                  ^
create table t17 as select id,(id+random())%3 oner from range(1,1500)t(id);                 --ok
```

### OS:

windows7 x64

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
It might be related to role related code left in the parser. You can quote it, "owner", to use it instead

**Comment by l1t1** [comment]
> It might be related to role related code left in the parser. You can quote it, "owner", to use it instead

it works, thank you.

**Comment by l1t1** [comment]
could the error message be improved? it's confusing.
