### ISSUE TITLE
JSONPath [*] isn't working when used with a WHERE clause

### ISSUE THREAD

**Issue by YongSa** [duckdb/duckdb#9901]
### What happens?

When trying to use the JSONPath Wildcard feature for lists, nothing get's selected when used in a WHERE clause. My goal is to get the row where in a list any id is greater or equals 12. As the usage of [*] returns are VARCHAR[] I understand that a search like that on a list might not work. I would then still expect list_filter to work for example. In general, I feel like I am missing something here.

### To Reproduce
```sql
CREATE TABLE example (j JSON);
INSERT INTO example VALUES ('{"id": 124,"testing": [{"id": 12, "switch": true},{"id": 15, "switch": false},{"id": 100, "switch": false}]}');
SELECT * FROM example WHERE j ->> '$.testing[*].id' >= 12;
```

### OS:

Windows 10.0.19045.3693, x64

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

CLI

### Full Name:

Marius Yong

### Affiliation:

-

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
This query:
```sql
SELECT j ->> '$.testing[*].id' AS x
FROM example;
```
Returns a single row with a list:
```
┌───────────────┐
│       x       │
│   varchar[]   │
├───────────────┤
│ [12, 15, 100] │
└───────────────┘
```

To filter that list based on their integer value, either `unnest` it and convert it to integers, or use `list_filter`:

```sql
SELECT list_filter(j ->> '$.testing[*].id', x -> x::INT >= 15) AS l FROM example;
```
```
┌───────────┐
│     l     │
│ varchar[] │
├───────────┤
│ [15, 100] │
└───────────┘
```

HTH

**Comment by szarnyasg** [comment]
This is not a bug: a wildcard jsonpath returns a list of varchar, which cannot be compared to an integer.

**Comment by user20230119** [comment]
json_extract works in WHERE clause
```
SELECT * FROM read_ndjson_objects('values.ndjson') WHERE json_extract(json,'id') = '"123"';
```

json_extract shortcut does not work in WHERE clause
```
SELECT * FROM read_ndjson_objects('values.ndjson') WHERE json->'id') = '"123"';
```
