### ISSUE TITLE
DISTINCT ON clause with ORDER BY triggers off  "INTERNAL Error: Attempted to access index m within vector of size n (m >= n)"

### ISSUE THREAD

**Issue by code1704** [duckdb/duckdb#9908]
### What happens?

DISTINCT ON clause with ORDER BY causes out-of-bounds access error.

### To Reproduce

```python
import duckdb
import pandas as pd

df = pd.DataFrame({'key': ['K3', 'K1', 'K2', 'K3', 'K4', 'K5'],
                    'A': [11, 12, 13, 14, 15, 16],
                    'B': [21, 22, 23, 24, 25, 26],
                    'C': [31, 32, 33, 34, 35, 36]})

sql = """
WITH cte AS (
    SELECT
        DISTINCT ON (key) key, C, A, B
    FROM df
    ORDER BY A
)
SELECT
    B
FROM cte
WHERE
    A >= 13
"""
df = duckdb.query(sql).df()
print(df)
```
The above Python script will give errors like
```
Error: INTERNAL Error: Attempted to access index 3 within vector of size 2
```

### OS:

Ubuntu 22.04.2 LTS, aarch64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Mark

### Affiliation:

bq

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting, this appears to be resolved in v0.10.0
