### ISSUE TITLE
s3_endpoint does not work with endpoints that include a path

### ISSUE THREAD

**Issue by tom-s-powell** [duckdb/duckdb#9917]
### What happens?

Using `s3_endpoint` with an endpoint like `http://127.0.0.1:8080/s3` results in various flavours of invalid requests. The path (`/s3`) gets included in the `Host` header which is not valid (it should simply be `<host>:<port>`, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host). This can lead to requests to be considered malformed and rejected. More importantly, the path is not included in `ParsedS3Url#path` which results in incorrect signature. 

Appreciate this is a relative edge case given likely `s3_endpoint` would like simply be a domain where S3 API is served at the root.

### To Reproduce

Slightly tricky to reproduce as it requires custom setup, but if you have an S3-compatible API on something like `http://127.0.0.1:8080/s3`, the following results in failed queries:
```
SET s3_access_key_id= ...;
SET s3_secret_access_key= ...;
SET s3_endpoint='http://127.0.0.1:8080/s3';
SET s3_url_style='path';
SET s3_use_ssl=false;
SELECT * from 's3://my-bucket/file.parquet';
```

### OS:

Any

### DuckDB Version:

0.9.1

### DuckDB Client:

Any

### Full Name:

Thomas Powell

### Affiliation:

Palantir

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment]
PR merged
