### ISSUE TITLE
Incorrect precedence between `-` and `::` (cast)

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#9929]
### What happens?

The operator precedence between `-` and `::` is incorrect, the expression tree is built in the wrong order, causing the possibility for the cast to fail before it gets negated

### To Reproduce

```sql
select -128::TINYINT;
```
Produces:
```
Error: Conversion Error: Type INT32 with value 128 can't be cast because the value is out of range for the destination type INT8
```

Whereas explicitly setting the order of operations it does work:
```sql
select (-128)::TINYINT;
```
```
┌───────────────────────┐
│ CAST(-128 AS TINYINT) │
│         int8          │
├───────────────────────┤
│                  -128 │
└───────────────────────┘
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Indeed this (with `INT` instead of `TINYINT`) works in Postgres:

```sql
postgres=# select -128::INT;
 ?column?
----------
     -128
(1 row)
```

**Comment by hannes** [comment]
We have behaviour consistent with Postgres
