### ISSUE TITLE
Unnamed structs are converted to dicts in pandas and therefore lose values

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#9939]
### What happens?

Unnamed structs (not sure about the right duckdb terminology) are converted to dictionaries in pandas dataframes. Thus, all but the last value is lost.

### To Reproduce

```
import duckdb
duckdb.sql("SELECT (1, 2) as x").to_df()
```
returns 
```
x
0	{'': 2}
```
but should probably return something like 
```
x
0	(1, 2)
```

### OS:

x64

### DuckDB Version:

9.0.2

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] Yes, I have

**Comment by Mytherin** [comment]
Fixed in #10174
