### ISSUE TITLE
Query planner bad interpretation with random() and ctes

### ISSUE THREAD

**Issue by jpmmcneill** [duckdb/duckdb#9940]
### What happens?

Hello 😄 another very niche bug from me! As always thank you for working on this amazing software.

When random() is used in combination with CTEs, I would expect the result of random() to be the same over all future references to that CTE expression. I imagine this is a common expectation.

However, this isn't the case which can easily be seen by the query planner:

<img width="397" alt="Screenshot 2023-12-10 at 19 41 27" src="https://github.com/duckdb/duckdb/assets/55981540/14424a5e-9d9a-4a9f-8eb0-35c096367e4a">

### To Reproduce

```sql
with a as (
    select random() <= 0.5 as is_lower_half
    from generate_series(9)
)

select (
    select count(*) from a where is_lower_half
) + (
    select count(*) from a where not is_lower_half
)
```

This query is not guaranteed to produce 10, which I would expect it to based on the CTE.

### OS:

MacOS

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

James McNeill

### Affiliation:

Hobbiest

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by jpmmcneill** [comment]
This is something I stumbled into while comparing duckdb and other tools in the python ecosystem for monte carlo simulations. I have a [thread](https://discord.com/channels/909674491309850675/921100786098901042/1183486328827031654) about this in discord.

**Comment by szarnyasg** [comment]
Hi James, thanks for the kind words. Did you consider using [materialized CTEs](https://duckdb.org/docs/sql/query_syntax/with.html#materialized-ctes)?

**Comment by l1t1** [comment]
> Hi James, thanks for the kind words. Did you consider using [materialized CTEs](https://duckdb.org/docs/sql/query_syntax/with.html#materialized-ctes)?
materialized CTE is much faster in my example
```

WITH t AS (
SELECT i, i*i*i*i*i AS i5 FROM range(1,150)t(i)
)
SELECT a.i, b.i, c.i, d.i, e.i
FROM t a, t b, t c, t d, t e
WHERE
a.i < b.i AND b.i < c.i AND c.i < d.i AND d.i < e.i AND
a.i5 + b.i5 + c.i5 + d.i5 = e.i5;

Run Time (s): real 25.015 user 26.972573 sys 7.940451

WITH t AS MATERIALIZED (
SELECT i, i*i*i*i*i AS i5 FROM range(1,150)t(i)
)
SELECT a.i, b.i, c.i, d.i, e.i
FROM t a, t b, t c, t d, t e
WHERE
a.i < b.i AND b.i < c.i AND c.i < d.i AND d.i < e.i AND
a.i5 + b.i5 + c.i5 + d.i5 = e.i5;
Run Time (s): real 1.108 user 1.092007 sys 0.015600
```

**Comment by jpmmcneill** [comment]
> > Hi James, thanks for the kind words. Did you consider using [materialized CTEs](https://duckdb.org/docs/sql/query_syntax/with.html#materialized-ctes)?
> 
> materialized CTE is much faster in my example
> 
> ```
> 
> 
> 
> WITH t AS (
> 
> SELECT i, i*i*i*i*i AS i5 FROM range(1,150)t(i)
> 
> )
> 
> SELECT a.i, b.i, c.i, d.i, e.i
> 
> FROM t a, t b, t c, t d, t e
> 
> WHERE
> 
> a.i < b.i AND b.i < c.i AND c.i < d.i AND d.i < e.i AND
> 
> a.i5 + b.i5 + c.i5 + d.i5 = e.i5;
> 
> 
> 
> Run Time (s): real 25.015 user 26.972573 sys 7.940451
> 
> 
> 
> WITH t AS MATERIALIZED (
> 
> SELECT i, i*i*i*i*i AS i5 FROM range(1,150)t(i)
> 
> )
> 
> SELECT a.i, b.i, c.i, d.i, e.i
> 
> FROM t a, t b, t c, t d, t e
> 
> WHERE
> 
> a.i < b.i AND b.i < c.i AND c.i < d.i AND d.i < e.i AND
> 
> a.i5 + b.i5 + c.i5 + d.i5 = e.i5;
> 
> Run Time (s): real 1.108 user 1.092007 sys 0.015600
> 
> ```
> 
> 

Hey @l1t1 thanks for the info! I see, so you can force the query planner to resolve these. But it's option rather than default. I think it'd be more intuitive if this happened automatically when random() is used to be honest. Of course, it's just a suggestion. What do you think?

**Comment by l1t1** [comment]
if materialize is better in most conditions, consider set it as default. 
in postgresql, materialize CTE is the default.

**Comment by l1t1** [comment]
if materialize CTE is better in most conditions, consider set it as default. 
in postgresql, materialize CTE is the default.

**Comment by jpmmcneill** [comment]
Bumping this @szarnyasg - I forgot to tag you in my response originally. The current behaviour is extremely confusing IMO.
