### ISSUE TITLE
Avoid `rand()` and `srand()`

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#9941]
### What happens?

R doesn't like when bundled libraries use functions like `rand()` and `srand()` . The skiplist refers to those, but apparently the functions they are used in are never used themselves.

Is it safe to remove those functions? Can we do it here (preferred) or through a patching mechanism in the R package?

### To Reproduce

- <https://github.com/duckdb/duckdb-r/actions/runs/7160751273/job/19495456017?pr=51#step:12:207>: NOTE from `R CMD check`
- [duckdb/duckdb-r@`2ad3324` (#51)](https://github.com/duckdb/duckdb-r/pull/51/commits/2ad3324aa8967959a1c11e6cedf38fe2b30b9aa1): Commit that removes the offending code without further consequences

### OS:

Ubuntu 22.04

### DuckDB Version:

e117c34a627eb73bee2c4c7c6bd7384b5525e7f7

### DuckDB Client:

Core

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
After https://github.com/duckdb/duckdb/pull/9772/files, those functions are never called, so can be most likely safely removed.

**Comment by hannes** [comment]
This should already be fixed in main?

**Comment by krlmlr** [comment]
Not in the version I tested, mentioned in this issue.

Hannes Mühleisen ***@***.***> schrieb am Mo. 11. Dez. 2023 um
11:11:
