### ISSUE TITLE
core dump when calling the `list` aggregate function.

### ISSUE THREAD

**Issue by yiyuanliu** [duckdb/duckdb#9949]
### What happens?

```sql
create table tbl as select unnest(generate_series(500000000)) as id;
select list(id) from tbl;
```
```
Segmentation fault (core dumped)
```

### To Reproduce

see above

### OS:

ubuntu 2204

### DuckDB Version:

v0.9.3-dev1411 7d5150c198

### DuckDB Client:

cli

### Full Name:

Yiyuan Liu

### Affiliation:

High-Flyer AI

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @yiyuanliu, this query completed on my MacBook Pro (32GB RAM).
How much memory / how many CPU core / what architecture (x86/arm64) did the machine have?

**Comment by yiyuanliu** [comment]
> Hi @yiyuanliu, this query completed on my MacBook Pro (32GB RAM). How much memory / how many CPU core / what architecture (x86/arm64) did the machine have? Of course, it should not result in a segfault even if the available resources are insufficient.

The machine architecture is x64, containing 2 NUMA nodes with a total of 128 physical cores. My testing was carried out inside a container configured with 32 CPU cores and 64GB of memory. Under the default configuration of DuckDB, the number of threads is also set to 32 cores.

**Comment by yiyuanliu** [comment]
> Hi @yiyuanliu, this query completed on my MacBook Pro (32GB RAM). How much memory / how many CPU core / what architecture (x86/arm64) did the machine have? Of course, it should not result in a segfault even if the available resources are insufficient.

This query also crashed on my MacBook Pro(M1 pro, 16GB RAM). It appears that the query itself executed successfully, but an incorrect memory address was accessed when converting the result to string for output.

```
(base) ➜  duckdb git:(main) ./build/release/duckdb
v0.9.3-dev1411 7d5150c198
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table tbl as select unnest(generate_series(500000000)) as id;
100% ▕████████████████████████████████████████████████████████████▏
D select list(id) from tbl;
100% ▕████████████████████████████████████████████████████████████▏
[1]    53751 segmentation fault  ./build/release/duckdb
```
