### ISSUE TITLE
Error when importing tsv file when a column starts with a quote

### ISSUE THREAD

**Issue by mrtimo** [duckdb/duckdb#9952]
### What happens?

Importing a .tsv file (tab separated value) when a column starts with a quote. It appears to throw the error message not when importing, but when trying to save as a parquet file (line 25)

Line 25: df.to_parquet('num'+file+'.parquet')

`  File "/Users/tim/Downloads/sec_notes/test_num.py", line 25, in <module>
    df.to_parquet('num'+file+'.parquet')
duckdb.duckdb.InvalidInputException: Invalid Input Error: Error in file "num.tsv" on line 1342935: quote should be followed by end of value, end of row or another quote. (  file=num.tsv
  delimiter='   '
  quote='"' (auto detected)
  escape='"' (auto detected)
  header=1
  sample_size=20480
  ignore_errors=0
  all_varchar=0). `

### To Reproduce

Run some code like this on a .tsv file with a column that starts with a quote:
` numdt = ['varchar', 'varchar', 'varchar', 'date', 'int', 'varchar', 'varchar', 'integer', 'double', 'varchar', 'integer', 'int', 'varchar', 'double', 'double', 'integer']
  da_format = "%Y%m%d"
  df = duckdb.read_csv('num.tsv', delimiter='\t', header=True, dtype=numdt, date_format=da_format)`
#then save to parquet
df.to_parquet('num.parquet')

When I manually delete the quote mark, it works. I am using the num.tsv contained in the 2019q3 file which can be downloaded here: [here](https://www.sec.gov/about/divisions-offices/division-economic-risk-analysis/data/financial-statement-and-notes-data-set)

### OS:

iOS

### DuckDB Version:

0.9.1

### DuckDB Client:

python

### Full Name:

Tim Olsen

### Affiliation:

Gonzaga University 

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Please provide a full script, ideally a [minimal working example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for reproduction.

**Comment by Prussian1870** [comment]
I'm having the same issue, on Windows 10 with version 9.1. read_csv_auto is throwing an error on tab delimited files that that have columns beginning with a quote.

**Comment by mrtimo** [comment]
Here is a google colab - run it and see the error. 
[https://colab.research.google.com/drive/1X9Opj_gIHBUlidGZdf38v36w8SWHDE67?usp=sharing](https://colab.research.google.com/drive/1X9Opj_gIHBUlidGZdf38v36w8SWHDE67?usp=sharing)

**Comment by JimCallahanOrlando** [comment]
I got same error message reading tab-separated file with quoted string in the middle of VARCHAR field. 
My **guess** is issue is unescaped quote, because message had additional info wrt :
<code>
quote='"' (default)
escape='"' (default)
</code>

Full message:
<code>
Traceback (most recent call last):
  File "f:\FVRS\FVRS2023Sep\test2_duckdb.py", line 19, in <module>
    with duckdb.connect("Voters2023-10.duckdb") as con:
  File "f:\FVRS\FVRS2023Sep\test2_duckdb.py", line 21, in <module>
    cur.execute("""
duckdb.duckdb.InvalidInputException: Invalid Input Error: Error in file ".\data\BRO_20230912.txt" on line 717310: quote should be followed by end of value, end of row or another quote. (  file=.\data\BRO_20230912.txt  quote='"' (default)
  escape='"' (default)
  header=0
  sample_size=20480
  ignore_errors=1
  all_varchar=0)
</code>

line 717310 contains the following field (1 and D are characters from adjacent VARCHAR fields):
<code>
1    "le Parc" Residential Tow       D
</code>

My **guess** is the read_csv() parser (while reading a tab delimited file) went ballistic on unescaped quotes.

This was an uncaught exception that terminated the process (ignore errors did not work).
Options (will try one or other tomorrow):
1. Use sed or Notepad++ to remove all quotes from tab delimited file
2. Use sed or Notepad++ to escape quote by changing 'space quote space' to 'space quote quote space' (change " to "" ).

**Comment by JimCallahanOrlando** [comment]
On second thought, Option 2 as specified by me won't edit because of adjacent characters -- so I will try option 1 tomorrow.

**Comment by mrtimo** [comment]
I got my code to work by adding this option: quote="" 
*Note the empty quote string. 
I believe this tells the parser that quotes are not important in parsing, so they can be ignored when determining which value goes where.

**Comment by Prussian1870** [comment]
Adding the option: quote="" fixed it for me as well.

**Comment by JimCallahanOrlando** [comment]
There is an additional issue when using the command line interface (CLI), the quote = "" option exptects exactly one character and does not recognize escape sequences. So, I was only able to get this to work by chosing a single byte character that was unlikely to occur in my corpus.  I chose the tilde character (~) which worked at the CLI. So there may be an additional issue with the CLI parser. 
read_csv( ... ignore_errors = true, quote = "");
Run Time (s): real 0.001 user 0.000000 sys 0.000000
Error: Parser Error: zero-length delimited identifier at or near """"
LINE 2: ...xt', header = false, sep = '\t', auto_detect = true, ignore_errors = true, quote = ""); 

read_csv( ... header = false, sep = '\t', ignore_errors = true, quote = '\0');
Run Time (s): real 0.001 user 0.000000 sys 0.000000
Error: Invalid Input Error: The quote option cannot exceed a size of 1 byte.

read_csv( ... header = false, sep = '\t',, auto_detect = true, ignore_errors = true, quote = '~');
100% ?████████████████████████████████████████████████████████████? 
Run Time (s): real 43.948 user 193.593750 sys 9.500000

At the CLI interface the version with quote = '~' sucessfully created a complete table (using my text files), 
the other two versions (also at the CLI) failed to create any table.  If your file contains any tildes this may blow up also.

I tend to debug SQL using the interactive CLI interface and then copy and paste the working SQL code into a Python doc-string (python for multi-line text string delimited with triple quotes ).

Fantastic that when it worked it read 67 files using a glob with more than 15 million records of 38 fields each.

**Comment by Prussian1870** [comment]
I'm having a similar problem with the one character limitation. In previous versions before 9, multiple characters were allowed for the quote option.

**Comment by tobilg** [comment]
As per the Discord chat, you can use `E'\t'` to escape those characters eventually: 

https://discord.com/channels/909674491309850675/921073327009853451/1252317019601240237

**Comment by notSapta** [comment]
> Adding the option: quote="" fixed it for me as well.
> 
> Thanks!!

I was watching a tutorial where the instructor put      quoting=3        .This was done to overcome errors that will be caused by double quotes. Any idea why quoting=3 would help?
