### ISSUE TITLE
DuckDB ODBC + Parquet + Excel: Unable to display timestamps in query results

### ISSUE THREAD

**Issue by MatinF** [duckdb/duckdb#9963]
### What happens?

I have a mini Parquet data lake as attached:

[test-data.zip](https://github.com/duckdb/duckdb/files/13647741/test-data.zip)

The data consists of timestamps and doubles, i.e. a simple time series Parquet file. 

When I query data from the file via the DuckDB CLI, it works as expected - see below query example:

```
D SELECT * FROM 'C:/Users/marti/Documents/ops-automation/grafana-athena-playgrounds/local-data-lake-test/3BA199E2/CAN2_gnssspeed/*/*/*/*.parquet';
┌───────────────────────────┬──────────────────────┬─────────────────────┬────────────┐
│             t             │        Speed         │    SpeedAccuracy    │ SpeedValid │
│         timestamp         │        double        │       double        │   double   │
├───────────────────────────┼──────────────────────┼─────────────────────┼────────────┤
│ 2020-10-28 14:35:38.3755  │                0.075 │               0.311 │        1.0 │
│ 2020-10-28 14:35:39.0856  │  0.10200000000000001 │               0.448 │        1.0 │
│ 2020-10-28 14:35:40.0287  │                0.182 │               0.421 │        1.0 │
│ 2020-10-28 14:35:41.1048  │                0.062 │               0.362 │        1.0 │
│ 2020-10-28 14:35:42.0149  │                0.044 │               0.366 │        1.0 │
│ 2020-10-28 14:35:43.089   │                0.196 │               0.321 │        1.0 │
│ 2020-10-28 14:35:43.98305 │  0.10300000000000001 │ 0.34600000000000003 │        1.0 │
│ 2020-10-28 14:35:45.0902  │                0.057 │               0.362 │        1.0 │
│ 2020-10-28 14:35:45.98425 │                0.014 │                0.32 │        1.0 │
│ 2020-10-28 14:35:47.01335 │ 0.009000000000000001 │               0.307 │        1.0 │
│ 2020-10-28 14:35:47.97945 │                0.101 │               0.364 │        1.0 │
│ 2020-10-28 14:35:49.09455 │                0.056 │               0.355 │        1.0 │
│ 2020-10-28 14:35:49.99465 │                0.061 │               0.358 │        1.0 │
│ 2020-10-28 14:35:51.09875 │                0.082 │               0.365 │        1.0 │
│ 2020-10-28 14:35:51.9528  │                 0.08 │               0.321 │        1.0 │
│ 2020-10-28 14:35:53.09695 │                0.053 │               0.328 │        1.0 │
│ 2020-10-28 14:35:54.01005 │                0.145 │               0.417 │        1.0 │
│ 2020-10-28 14:35:55.11115 │                0.098 │               0.405 │        1.0 │
│ 2020-10-28 14:35:56.00525 │                0.083 │               0.389 │        1.0 │
│ 2020-10-28 14:35:57.11035 │                0.023 │               0.316 │        1.0 │
│            ·              │                  ·   │                 ·   │         ·  │
│            ·              │                  ·   │                 ·   │         ·  │
│            ·              │                  ·   │                 ·   │         ·  │
│ 2020-10-29 15:20:18.741   │                3.833 │               0.097 │        1.0 │
│ 2020-10-29 15:20:19.7511  │                4.351 │                0.08 │        1.0 │
│ 2020-10-29 15:20:20.8068  │                4.856 │               0.078 │        1.0 │
│ 2020-10-29 15:20:21.7533  │                5.053 │               0.076 │        1.0 │
│ 2020-10-29 15:20:22.81495 │   4.5280000000000005 │               0.075 │        1.0 │
│ 2020-10-29 15:20:23.7365  │                3.908 │               0.082 │        1.0 │
│ 2020-10-29 15:20:24.74955 │                2.964 │               0.062 │        1.0 │
│ 2020-10-29 15:20:25.7667  │                2.236 │               0.063 │        1.0 │
│ 2020-10-29 15:20:26.7542  │                2.824 │               0.077 │        1.0 │
│ 2020-10-29 15:20:27.74215 │                 3.04 │ 0.07200000000000001 │        1.0 │
│ 2020-10-29 15:20:28.76165 │                2.581 │               0.067 │        1.0 │
│ 2020-10-29 15:20:29.73305 │                2.015 │               0.068 │        1.0 │
│ 2020-10-29 15:20:30.7275  │                2.025 │ 0.08700000000000001 │        1.0 │
│ 2020-10-29 15:20:31.7253  │                2.174 │ 0.07200000000000001 │        1.0 │
│ 2020-10-29 15:20:32.73005 │                1.699 │               0.074 │        1.0 │
│ 2020-10-29 15:20:33.73145 │                1.492 │               0.078 │        1.0 │
│ 2020-10-29 15:20:34.73255 │                0.915 │               0.096 │        1.0 │
│ 2020-10-29 15:20:35.74235 │                0.685 │ 0.10400000000000001 │        1.0 │
│ 2020-10-29 15:20:36.73455 │                0.131 │ 0.10400000000000001 │        1.0 │
│ 2020-10-29 15:20:37.73785 │                0.068 │               0.105 │        1.0 │
├───────────────────────────┴──────────────────────┴─────────────────────┴────────────┤
│ 2328 rows (40 shown)                                                      4 columns │
└─────────────────────────────────────────────────────────────────────────────────────┘
```
As evident, the timestamps show with the full resolution as expected.

Now, if I try using the DuckDB ODBC driver within Excel, I only get the date returned, not the full timestamp. See below:

1) Install the DuckDB ODBC driver as per the guide with no settings changes
2) Open Excel, go to "Get Data/From Other Sources/ODBC" 
3) Select DuckDB as the source and enter below query under Advanced:

```
SELECT * FROM 'C:/Users/marti/Documents/ops-automation/grafana-athena-playgrounds/local-data-lake-test/3BA199E2/CAN2_gnssspeed/*/*/*/*.parquet'
```
4) The result is below:

![image](https://github.com/duckdb/duckdb/assets/26184427/06e6612f-8474-48cb-9103-5902afbd5452)

![image](https://github.com/duckdb/duckdb/assets/26184427/8319a59d-b6b6-4c15-ac22-b9c7b806bf2f)

As evident, only the date is loaded - the hours, minutes, seconds etc are truncated away. This does not seem to be an issue with the query per se, but rather how Excel or the ODBC driver handles this. 

It should be noted that this problem does not arise with e.g. the Amazon Athena ODBC driver for comparison, using the same Parquet file. Here, the timestamp is returned in full. For comparison below is a similar test with Amazon Athena's ODBC driver using the query `SELECT * FROM   tbl_0bfd7754_can9_gnssspeed`:

![image](https://github.com/duckdb/duckdb/assets/26184427/7defabb2-4572-44d5-bca7-0f977f065c45)

Any suggestions on how to handle this?

### To Reproduce

See the data and steps above. 

### OS:

Windows 10

### DuckDB Version:

Latest

### DuckDB Client:

Excel + ODBC

### Full Name:

Martin Falch

### Affiliation:

CSS Electronics

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by MatinF** [comment]
Update: I am able to get Excel to show the rest of the timestamp by using the `strftime` function as below:

```
SELECT strftime(t,'%Y/%m/%d %H.%M.%S') AS time, AVG(Speed) as AVG_Speed FROM 'C:/Users/marti/Documents/ops-automation/grafana-athena-playgrounds/local-data-lake-test/3BA199E2/CAN2_gnssspeed/*/*/*/*.parquet' GROUP BY t;
```
Still, it seems like this solution is very dependent on Excel's locale settings, which does not seem to be an issue with Athena for comparison. Maybe I'm missing "the right way" to fetch a full timestamp into Excel.

Note that the above query requires some tweaking of the data type within the Power Query Editor of Excel. In my case, I needed to specify explicitly that the format was date/time and set the locale to English (Denmark), then refresh the pivot. After that I was able to get the pivot to properly recognize the full date and the timestamp.

I guess this can be closed, though it might be useful if there is a best practice for this.

**Comment by CurtHagenlocher** [comment]
I work on Power Query, and from our perspective we're calling SQLGetColAttribute with SQL_DESC_CONCISE_TYPE and getting back SQL_TYPE_DATE.

**Comment by MatinF** [comment]
I've not tested that one - in what way do you use it in a full query? Also, does it result in the timestamp being interpreted as a date-time type timestamp or only a date?

**Comment by CurtHagenlocher** [comment]
Power Query is the component in Excel you're using. I debugged your example to see what the DuckDB ODBC driver is returning, and it's saying that the column is of type date and not datetime. This is therefore something which ought to be easily reproducible outside Excel.
