### ISSUE TITLE
ADBC Windows support needs documentation

### ISSUE THREAD

**Issue by Prussian1870** [duckdb/duckdb#9969]
### What happens?

The documentation mentions that ADBC is not supported on Windows. It is now.

### To Reproduce

https://duckdb.org/docs/api/adbc

ADBC is not yet supported on Windows, but it is supported on macOS and Linux.

### OS:

Windows

### DuckDB Version:

10

### DuckDB Client:

9.1

### Full Name:

Jorge Rodrigues

### Affiliation:

Contracter

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, this is a documentation issue and will be tackled there.
