### ISSUE TITLE
list_has_all function returns wrong result when first argument uses a list comprehension or list transformation.

### ISSUE THREAD

**Issue by stevenlw-porpoise** [duckdb/duckdb#9970]
### What happens?

When doing a list comprehension in the first argument of the list_has_all function the result is true even though the correct result is false. 

The example below uses the identity transformation which should not affect the output result.
```
D select list_has_all(['a'], ['b']) as normal_result;
┌───────────────┐
│ normal_result │
│    boolean    │
├───────────────┤
│ false         │
└───────────────┘
D select list_has_all([x for x in ['a']], ['b']) as list_comp_result;
┌──────────────────┐
│ list_comp_result │
│     boolean      │
├──────────────────┤
│ true             │
└──────────────────┘
D select list_has_all(list_transform(['a'], x -> x), ['b']) as list_transform_result;
┌───────────────────────┐
│ list_transform_result │
│        boolean        │
├───────────────────────┤
│ true                  │
└───────────────────────┘
```

### To Reproduce

Run the queries above.

### OS:

MacOS Sonoma 14.1

### DuckDB Version:

v0.9.2

### DuckDB Client:

CLI

### Full Name:

Steven Litvack-Winkler

### Affiliation:

Obsidian Security

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by stevenlw-porpoise** [comment]
Just noticed something interesting.

```
D select list_has_all([x for x in ['a']], ['b']) as list_comp_result;
┌──────────────────┐
│ list_comp_result │
│     boolean      │
├──────────────────┤
│ true             │
└──────────────────┘
D select list_has_all([y for y in ['a']], ['b']) as list_comp_result;
┌──────────────────┐
│ list_comp_result │
│     boolean      │
├──────────────────┤
│ false            │
└──────────────────┘
```
It seems like things work weirdly if the variable 'x' in the source code macro is reused. https://github.com/duckdb/duckdb/blob/323724447b32499538630dfb052f231ff05c7a10/src/catalog/default/default_functions.cpp#L115

**Comment by szarnyasg** [comment]
That's wild, thanks for reporting!

**Comment by taniabogatsch** [comment]
```sql
D select list_transform([1,2], x -> list_transform([3,4], x -> x));
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
│ list_transform(main.list_value(1, 2), (x -> list_transform(main.list_value(3, 4), (x -> x)))) │
│                                           int32[][]                                           │
├───────────────────────────────────────────────────────────────────────────────────────────────┤
│ [[1, 1], [2, 2]]                                                                              │
└───────────────────────────────────────────────────────────────────────────────────────────────┘
```

Nice catch. This is reproducible without the `list_has_all`. It's a binder bug - we do not check if a lambda parameter name is already in use by an 'outer' lambda function. `list_has_all` 'hides' this from the user, and I assume it hasn't been caught before because users don't repeat variable names for nesting when typing the queries manually. I will open a PR to fix this.

**Comment by stevenlw-porpoise** [comment]
Thank you for looking in to the issue and writing a fix.
