### ISSUE TITLE
Segmentation fault when selecting from a recreated table.

### ISSUE THREAD

**Issue by michael-hlavacek** [duckdb/duckdb#9975]
### What happens?

When reading from a table which is being `create or repace`d by another thread, a segmentation fault occurs.

The setup is to do `create or replace table foo as select * from foo` in one thread, and `select * from foo` in another. The reading thread throws a segmentation fault.

However, if the read is wrapped by a transaction (conn.begin() before reading from the recreated table followed by a conn.commit()), the segfault is prevented. So the workaround is to wrap similar reads in a transaction.

### To Reproduce

Run the following python script and observe a segfault

```python
from threading import Thread

import duckdb

conn = duckdb.connect()

# Create a table which we'll be recreating later
conn.execute("create table foo(bar int); insert into foo(bar) select unnest(generate_series(1, 10));")


class ReadingThread(Thread):
    def __init__(self, conn):
        super().__init__()
        self.cursor = conn.cursor()

    def run(self):
        while True:
            # To prevent the segfault, do self.cursor.begin() here
            self.cursor.execute("select * from foo")
            # To prevent the segfault, do self.cursor.commit() here


class RecreatingThread(Thread):
    def __init__(self, conn):
        super().__init__()
        self.cursor = conn.cursor()

    def run(self):
        while True:
            self.cursor.execute("create or replace table foo as select * from foo")


RecreatingThread(conn).start()
ReadingThread(conn).start()
```

### OS:

Ubuntu x64 in WSL on Windows 11

### DuckDB Version:

v0.9.2 3c695d7ba9

### DuckDB Client:

Python

### Full Name:

Míma Hlaváček

### Affiliation:

Blindspot.ai

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! I have a fix up now here - https://github.com/duckdb/duckdb/pull/10923
