### ISSUE TITLE
SUMMARIZE returns error when query contains large values

### ISSUE THREAD

**Issue by jraymakers** [duckdb/duckdb#9978]
### What happens?

When `summarize` is used on a query with a result that contains values of some types close to the limits of their ranges, an error is returned.

### To Reproduce

Running the following command in the CLI returns the error below:
```sql
summarize select 9223372036854775296;
```
```
Error: Invalid Input Error: Type DOUBLE with value 9.223372036854776e+18 can't be cast because the value is out of range for the destination type INT64
```
Equivalently, this produces the same error:
```sql
summarize select bigint from test_all_types();
```
Although note that the error occurs with the value `9223372036854775296`, which is a bit smaller than the value `9223372036854775807` from test_all_types() (which also produces the error).

Note that the following (with the next smallest value from `9223372036854775296`) does not return an error:
```sql
summarize select 9223372036854775295;
```

Also, negative values of some types return similar but different errors:
```sql
summarize select -9223372036854775808::bigint;
```
```
Error: Conversion Error: Type INT128 with value 9223372036854775808 can't be cast because the value is out of range for the destination type INT64
```

Note that the cast to BIGINT is needed to produce this error, and the following (with a value one step closer to zero) does not result in an error:
```sql
summarize select -9223372036854775807::bigint;
```

### OS:

Mac OS X 13.5.2 (M2 chip)

### DuckDB Version:

0.9.3-dev1527

### DuckDB Client:

CLI

### Full Name:

Jeff Raymakers

### Affiliation:

MotherDuck

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
This is triggered in `ApproxQuantileScalarOperation::Finalize`. Which is a bit ironic, because the name suggests that perfect accuracy is not the top priority here...

**Comment by hawkfish** [comment]
The last failure is not an error: The cast fails because the number is too large (which is what the error message says):

```sql
select -9223372036854775808::bigint;
```

**Comment by jraymakers** [comment]
> The last failure is not an error: The cast fails because the number is too large (which is what the error message says):
> 
> ```sql
> select -9223372036854775808::bigint;
> ```

Good point. There is still an error more like the original one with large negative numbers, though:
```sql
summarize select hugeint from test_all_types() limit 1;

**Comment by jraymakers** [comment]
Sorry, didn't mean to close.
